### ISSUE TITLE
OpenSSL Internal Error on TLS 1.0 and TLS 1.1

### ISSUE THREAD

**Issue by PSanetra** [curl/curl#10002]
Curl somewhere after version 7.83.1 does not seem to be able to use TLS 1.0 and 1.1 anymore. The examples below are showing the result for TLS 1.1, but it is the same with 1.0.

### I did this

Execute the following script to show result with curl 7.86:

```
docker run -it --rm alpine:3.17 sh -c 'set -x && apk add --no-cache curl && curl --version && curl --tls-max 1.1 -vvvvv https://example.com'
+ apk add --no-cache curl
[...]
OK: 9 MiB in 20 packages
+ curl --version
curl 7.86.0 (x86_64-alpine-linux-musl) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss 
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
+ curl --tls-max 1.1 -vvvvv https://example.com
*   Trying 93.184.216.34:443...
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS header, Certificate Status (22):
* TLSv1.1 (IN), TLS handshake, Server hello (2):
* TLSv1.1 (IN), TLS header, Certificate Status (22):
* TLSv1.1 (IN), TLS handshake, Certificate (11):
* TLSv1.1 (IN), TLS header, Certificate Status (22):
* TLSv1.1 (IN), TLS handshake, Server key exchange (12):
* TLSv1.1 (OUT), TLS header, Unknown (21):
* TLSv1.1 (OUT), TLS alert, internal error (592):
* error:0A0C0103:SSL routines::internal error
* Closing connection 0
curl: (35) error:0A0C0103:SSL routines::internal error
```

### I expected the following

The same _successful_ result like with curl 7.83.1:

```
docker run -it --rm alpine:3.16 sh -c 'set -x && apk add --no-cache curl && curl --version && curl --tls-max 1.1 -vvvvv https://example.com'
+ apk add --no-cache curl
[...]
OK: 8 MiB in 19 packages
+ curl --version
curl 7.83.1 (x86_64-alpine-linux-musl) libcurl/7.83.1 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
+ curl --tls-max 1.1 -vvvvv https://example.com
*   Trying 93.184.216.34:443...
*   Trying 2606:2800:220:1:248:1893:25c8:1946:443...
* Immediate connect fail for 2606:2800:220:1:248:1893:25c8:1946: Address not available
* Connected to example.com (93.184.216.34) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS handshake, Server hello (2):
* TLSv1.1 (IN), TLS handshake, Certificate (11):
* TLSv1.1 (IN), TLS handshake, Server key exchange (12):
* TLSv1.1 (IN), TLS handshake, Server finished (14):
* TLSv1.1 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.1 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.1 (OUT), TLS handshake, Finished (20):
* TLSv1.1 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.1 / ECDHE-RSA-AES128-SHA
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Los Angeles; O=Internet�Corporation�for�Assigned�Names�and�Numbers; CN=www.example.org
*  start date: Mar 14 00:00:00 2022 GMT
*  expire date: Mar 14 23:59:59 2023 GMT
*  subjectAltName: host "example.com" matched cert's "example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Age: 303434
< Cache-Control: max-age=604800
< Content-Type: text/html; charset=UTF-8
< Date: Tue, 29 Nov 2022 18:00:03 GMT
< Etag: "3147526947+ident"
< Expires: Tue, 06 Dec 2022 18:00:03 GMT
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Server: ECS (dcb/7F84)
< Vary: Accept-Encoding
< X-Cache: HIT
< Content-Length: 1256
< 
<!doctype html>
<html>
[...]
</html>
* Connection #0 to host example.com left intact
```

### curl/libcurl version

curl 7.86.0 (x86_64-alpine-linux-musl) libcurl/7.86.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0

### operating system

Linux 42404fb962ba 5.15.78-1-MANJARO #1 SMP PREEMPT Thu Nov 10 20:50:09 UTC 2022 x86_64 Linux
(It is Alpine Linux in a container, but the host has a Manjaro Kernel)

**Comment by MarcelRaad** [comment]
Note that OpenSSL was updated from v1.1.1 to v3.0 at the same time, and there was a breaking change in OpenSSL that TLS 1.0 and 1.1 using SHA1 don't work by default anymore.

**Comment by bagder** [comment]
It is clearly  depending on OpenSSL (version).

My curl 7.86.0 version from Debian unstable with OpenSSL 3.0.7 reproduces the problem.

My 7.87.0-DEV build (current master branch) on the same machine using quictls 1.1.1 does not reproduce it.

Rebuilding the same code with OpenSSL 3.0.7 makes the issue reproduce.

Rebuilding the same code with OpenSSL 3.1.0 (from git master, updated some days ago) makes the issue reproduce.

**Comment by bagder** [comment]
Does OpenSSL 3 maybe have them disabled by default?

**Comment by MarcelRaad** [comment]
Yes, see the [migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html) and [release notes](https://www.openssl.org/news/openssl-3.0-notes.html). (Looks like it's not possible to link to specific parts, but just search for "TLS 1.1".)

**Comment by bagder** [comment]
Right!

So this works:
~~~
curl --tls-max 1.1 --ciphers DEFAULT@SECLEVEL=0 -vI https://example.com

**Comment by bagder** [comment]
So: works as intended I suppose.

**Comment by PSanetra** [comment]
@bagder thank you for clearing that up! Is it possible to get a better error message, though? `internal error` is quite generic message :sweat_smile:

**Comment by bagder** [comment]
That's the error OpenSSL provides. OpenSSL is truly awful when it comes to delivering (comprehensible) error messages. It would be very difficult for curl to override this message or provide something different since curl does not know the reason for this failure.

**Comment by PSanetra** [comment]
Maybe a prefix to the message would be helpful. Is it possible to get the name of the library that produces the error message?

**Comment by bagder** [comment]
> Maybe a prefix to the message would be helpful

What would such a prefix be? `OpenSSL says:` ?

> Is it possible to get the name of the library that produces the error message?

As it is a TLS connection problem error, I think it is reasonable to suspect that the TLS library you use is involved... This function does not know if if the library is called OpenSSL, BoringSSL, libressl or quictls though.

**Comment by PSanetra** [comment]
Yeah, probably more like `OpenSSL/3.0.7:`.

The current prefix `error:0A0C0103:SSL routines::` is not really indicating to a user if this is an ssl-related error of curl or of the underlying library.

**Comment by bagder** [comment]
Well, a user won't automatically know that a `OpenSSL/3.0.7` prefix means that we blame the underlying library either, it could just be the name of the library as far as a user is concerned...

I'm not saying a prefix can't be useful, just saying that it doesn't really indicate blame.

**Comment by jzakrzewski** [comment]
I feel like: the ones who know right away, they know. Others will google the error anyway, and will be pointed to the right places.

**Comment by PSanetra** [comment]
Yes, that was just a suggestion. I think it would also not helped me in finding the right solution for this issue. (Adding the `--ciphers DEFAULT@SECLEVEL=0` argument.) I guess hinting to the right solution is only solvable in the OpenSSL library. :confused:

**Comment by PSanetra** [comment]
Another question: Would it make sense for curl to use `--ciphers DEFAULT@SECLEVEL=0` implicitly if `--tls-max 1.1` or `--tls-max 1.0` is specified? Or could this be a security or any other kind of issue?
