### ISSUE TITLE
configure: Error unexpected token else in line 34360 compiling v 7.86.0

### ISSUE THREAD

**Issue by bodypheo** [curl/curl#10005]
Hello,
I am trying to compile curl from sources v7.86.0 and I run configure with this parameters:
./configure --disable-shared --with-zlib=/root/openssl/zlib --with-openssl=/opt/openssl/
And I get this output after a few seconds:
_______________
checking whether to enable Windows native IDN (Windows native builds only)... no
./configure: line 34360: syntax error near unexpected token `else'
./configure: line 34360: `else'
________________

My script-fu does not go much more beyond echo "hello world".
Is there some problem with the configure file or did I miss something?

Thanks

**Comment by bodypheo** [comment]
I downloaded the last tar.gz and ran autoreconf -fi to generate it.

**Comment by bagder** [comment]
What if you instead just use the one that is included in the tarball?

**Comment by bagder** [comment]
If that doesn't work either: what system are you running this on? Can you attach the `config.log` from your failed attempt?
