### ISSUE TITLE
hyper tests are broken since ca15b7512e

### ISSUE THREAD

**Issue by bagder** [curl/curl#10009]
### I did this

Build curl with hyper

~~~
cd tests
./runtests.pl 1
~~~

### Problem

I think the new `crlf="yes"` support from commit ca15b7512e should *only* be applied to the section where it is used, and not on the entire test case like it is now. Test 2500 only uses it for `<data>` so only that content should get crlf replaced.

**Comment by bagder** [comment]
The conversion could then be done explicitly without caring if it looks like HTTP or not.

**Comment by bagder** [comment]
> The conversion could then be done explicitly without caring if it looks like HTTP or not.

Eh, no. Because then we also add CRLF to the body in `<data>` etc and that changes the size of it...

**Comment by icing** [comment]
> > The conversion could then be done explicitly without caring if it looks like HTTP or not.
> 
> Eh, no. Because then we also add CRLF to the body in `<data>` etc and that changes the size of it...

I remember myself walking down that line of thinking. That is why I sticked to the HTTP pattern that was in place for hyper. The trouble we have now is that it also replaces \r\n with \r\r\n, it seems.

**Comment by bagder** [comment]
I'm trying out a few things in #10010. I want to be able to mark individual sections as `crlf="yes"` so that we long-term can move away from using CRLF lines within the source test files .

**Comment by icing** [comment]
Another idea would be to have some sort of `<reply><http-header>...` section where crlf is always normalized.

**Comment by bagder** [comment]
Or just a `<crlf>...</crlf>` within `<data>` etc

**Comment by bagder** [comment]
A challenge is to introduce such a new/better/different system in a way that can be gradually transitioned into, without us having to update 800+ test cases in a single blow.

**Comment by icing** [comment]
I was thinking of gradually changing test cases to use the new section. The old way of setting the server response could be left unchanged. But that is just a thought, you know best.

**Comment by bagder** [comment]
If I can get this working with my current simpler approach, I think I'll stick to this for now.
