### ISSUE TITLE
Curl cannot get SSH Key, but SSH can

### ISSUE THREAD

**Issue by andypillip** [curl/curl#1001]
See also  http://serverfault.com/questions/783648/why-cant-curl-retrieve-the-ssh-host-key-key-none

### I did this

`curl -u horst sftp://hostname.example.com:222/`

### what happened

```
Enter host password for user 'horst':
*   Trying [IPv4]...
* Connected to hostname.example.com ([IPv4]) port 222 (#0)
* SSH MD5 fingerprint: [the fingerprint]
* SSH host check: 2, key: <none>
* Closing connection 0
```

### I expected the following

A connect without asking for password, since a public key is stored on the server. 

### I verified the connection
I tried to verify with SSH, which worked as expected: the public key would be used, the server fingerprint accepted.
```
debug1: Local version string SSH-2.0-OpenSSH_7.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.0p1 Debian-4+deb7u6
```

Another server did have the same problem, now it works fine:

`debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8`

Maybe it's a difference between OpenSSH 6.0 and 6.6?

### curl/libcurl version

curl 7.47.1 (x86_64-redhat-linux-gnu) libcurl/7.47.1 NSS/3.25 zlib/1.2.8 libidn/1.33 libpsl/0.13.0 (+libidn/1.33) libssh2/1.7.0 nghttp2/1.7.1

### operating system

F24 64-bit

**Comment by bagder** [comment]
First: libssh2 does the knownhosts file reading and parsing so this bug is actually there and not in curl.

I haven't really keeping track of knownhosts file formats the last few years but I believe OpenSSH has introduced new and different digest algorithms so it is quite possible than the host you want to use is stored in a format that libssh2 doesn't support/understand.

**Comment by andypillip** [comment]
But isn't SSH using libssh2?

**Comment by bagder** [comment]
No, unfortunately not. ssh, as in openssh, is a totally separate implementation...

**Comment by andypillip** [comment]
@bagder thanks for pointing me in the right direction. I'll report the bug there.

**Comment by bagder** [comment]
Great. I actually wrote the known_hosts code for libssh2 but as I said, I haven't kept up with what openssh has been doing in that department lately. It isn't an area that is covered by standard or specs but is entirely up to openssh's own "whims".

**Comment by bagder** [comment]
This is strongly believed to be a libssh2 issue, If it turns out it isn't, we can reopen again.
