### ISSUE TITLE
curl sometimes reports "(6) Could not resolve host: xxx" when first DNS response is "no such name"

### ISSUE THREAD

**Issue by kmathewmk** [curl/curl#10018]
### 
I have curl making a HTTP request to a host and I have 3 DNS servers configured. One DNS 192.168.1.254 is in the local home router and two others are accessible via a VPN. To resolve the host, curl sends a lookup to the 3 DNS servers. The local DNS which does not have the same name often responds first and this seems to cause curl to report "(6) Could not resolve host: xxx" and exit without waiting for the other valid responses. (the closed port seems to result in ICMP port unreachable)
In the following example, first request succeeds and the remaining two fail:
![image](https://user-images.githubusercontent.com/52198810/205292871-0c00fff9-bfd7-43ee-875b-b6eda17f981d.png)

### I expected the following:
curl sends the request when there is atleast one valid DNS response

### curl/libcurl version

```
curl 7.86.0 (x86_64-pc-linux-musl) libcurl/7.86.0 OpenSSL/1.1.1q zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
```

### operating system
```
Linux LT4411 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

```

**Comment by bagder** [comment]
Your curl uses the `getaddrinfo()` function call to resolve the host, and if that returns error curl can do nothing about that. Given the OS name in your version output I assume you use the musl libc and its resolver function. If you think it behaves badly or wrong, that's the one to look into.

I don't recall the exact details on how the DNS protocol works, but I think that the error you get is correctly considered an error and that you should probably look at fixing your config.

**Comment by kmathewmk** [comment]
I tested the getaddrinfo on my machine by adapting the code [here](https://gist.github.com/jirihnidek/bf7a2363e480491da72301b228b35d5d) and I do not get lookup failures. However, I notice that the test code sends only one DNS request (to the first DNS server in my resolv.conf  10.18.0.50 which has the name being looked up).
![image](https://user-images.githubusercontent.com/52198810/205304891-11cdbaaf-b879-49e7-90e3-41eab1903275.png)
In the case of curl, DNS lookup requests go to all 3 listed DNS servers (local 192.168.1.254 being the last in my resolv.conf but which responds quicker). Does curl configure the getaddrinfo call in a specific way to have the multiple DNS parallel lookups?

**Comment by bagder** [comment]
> Does curl configure the getaddrinfo call in a specific way to have the multiple DNS parallel lookups?

No, and there is no such option for getaddrinfo so even if we wanted to, we couldn't!

The exact getaddrinfo function call in the code is here:

https://github.com/curl/curl/blob/73c4f9696adc77a47a79f215de99a00fe0dbee5a/lib/curl_addrinfo.c#L121

**Comment by kmathewmk** [comment]
Following your hint, I see that the explanation lies in the musl lib used by my curl versus libc.so.6 of my test code. Behavioural differences between musl libc and glibc are:

> _Traditional resolvers, including glibc’s, make use of multiple nameserver lines in resolv.conf by trying each one in sequence and falling to the next after one times out. musl’s resolver queries them all in parallel and accepts whichever response arrives first._ 

(Details [here](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS). Thanks to [this](https://jvns.ca/blog/2022/02/23/getaddrinfo-is-kind-of-weird/#musl-libc-getaddrinfo-is-different-from-glibc-s-version))
