### ISSUE TITLE
build-openssl.bat script will not build OpenSSL 1.1.0

### ISSUE THREAD

**Issue by SilverCookie** [curl/curl#1002]
The curl\projects\build-opensll.bat script for Windows no longer works with the latest version of OpenSSL (1.1.0).

The following errors occur:

```
'ms\do_ms' is not recognized as an internal or external command, operable program or batch file. 

NMAKE : fatal error U1052: file 'ms\nt.mak' not found Stop.

NMAKE : fatal error U1052: file 'ms\ntdll.mak' not found Stop.
The system cannot find the file specified.
```

Ref: https://curl.haxx.se/mail/archive-2016-09/0019.html

**Comment by lllaffer** [comment]
have a look here:
http://stackoverflow.com/questions/39076244/why-there-is-no-ms-do-ms-bat-after-perl-configure-vc-win64a/39247560#39247560

		:
		Starting with 1.1.0 there are no more ms\do_*.bat files.

		x32 compilation on Windows:
		
		perl Configure VC-WIN32
		nmake
		nmake test
		
		x64A compilation on Windows:
		
		perl Configure VC-WIN64A
		nmake
		nmake test
		:

**Comment by Noitidart** [comment]
Thank you @lllaffer I was trying to follow the steps here - http://www.askyb.com/windows/compiling-and-installing-openssl-for-32-bit-windows/

And got stuck at the step 6 `ms\do_ms`. Your steps really helped me out I just had to do `nmake` so easy! Thank you!

**Comment by gsilva2016** [comment]
How does libeay32 and ssleay32.lib get generated now in 1.1.x?

**Comment by MadalinaDemenescu** [comment]
Hi. I am trying to build openSSL 1.1.0f and I am getting the following error: LINK : fatal error LNK1181: cannot open input file 'ssleay32.lib'. Regarding the previous comment ( Note libeay32 and ssleay32.lib appears to have been renamed libcrypto and libssl ) do you have any idea where and what should be changed? Thanks!
