### ISSUE TITLE
bearssl: assign variable to zero at declaration

### ISSUE THREAD

**Issue by maddin200** [curl/curl#10035]
curl-master/lib/vtls/bearssl.c: line 156

may be better init with  size_t n = 0;

**Comment by bagder** [comment]
Why? It is always assigned before used on line 156.

**Comment by maddin200** [comment]
normally initlaized with if / else if but just to play safe

**Comment by danielgustafsson** [comment]
I would argue that initializing the variable would make the code less safe. If we in some way change the code to accidentally skip the intended initialization, the compiler will tell us that we're using an uninitialized variable. If we init it to a random value which holds no meaning to the code, like zero, the compiler will happily give us a binary which has a subtle bug.

**Comment by maddin200** [comment]
ok than no change

**Comment by danielgustafsson** [comment]
No change; but that doesn't mean your input isn't valuable. Thanks for your submission!
