### ISSUE TITLE
Wrong XDG default config path implementation (easy and fast fix)

### ISSUE THREAD

**Issue by WGRM** [curl/curl#10030]
Regarding the website, curl uses the following XDG path for the default runtime configuration:

"$XDG_CONFIG_HOME/.curlrc"

This is wrong:

"A user-specific version of the configuration file may be created in $XDG_CONFIG_HOME/subdir/**filename**, taking into account the default value for $XDG_CONFIG_HOME if $XDG_CONFIG_HOME is not set. " [Source](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

> There is no dot in the filename. So this "rule" was *implied*, but not *mentioned*. Anyway, noone uses dot file in the XDG directories, it is wrong to do so. Since there is only one file being looked up, it stays placed in the root of the directory, without subfolder. But you can still take the dot file with lower priority, if it exists.

Regards and thanks.

**Comment by bagder** [comment]
> curl uses the following XDG path for the default runtime configuration: `$XDG_CONFIG_HOME/.curlrc`

This is wrong. Using strace on curl 7.86.0 shipped by Debian:
~~~
strace curl 2>&1 | grep curlrc
openat(AT_FDCWD, "/home/daniel/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/daniel/.config/curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/daniel/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)

**Comment by emanuele6** [comment]
@bagder I think they are saying that, if `XDG_CONFIG_HOME` is set, `curl` checks `$XDG_CONFIG_HOME/.curlrc` instead of `/home/daniel/.config/curl/curlrc` which is what they expected.

Also, it seems `curl` only removes the `.` for the file `$XDG_CONFIG_HOME` if it is not set and is assumed to be `$HOME/.config/`.

I am not sure if using `$XDG_CONFIG_HOME/curlrc` instead of `$XDG_CONFIG_HOME/curl/curlrc` is not compatible with the XDG base directories specification since I am not very familiar with it, but i think, at least, not removing the `.` from `.curlrc` when `XDG_CONFIG_HOME` is set is an unintentional `curl` bug:

* With `XDG_CONFIG_HOME` not set... using `$XDG_CONFIG_HOME/curlrc`:

  ```bash
  bash-5.1$ (unset -v XDG_CONFIG_HOME; strace curl 2>&1 | grep curlrc)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.config/curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  ```

* With `XDG_CONFIG_HOME` set... using `$XDG_CONFIG_HOME/.curlrc`:

  ```bash
  bash-5.1$ XDG_CONFIG_HOME=hello strace curl 2>&1 | grep curlrc
  openat(AT_FDCWD, "hello/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  ```

* With `XDG_CONFIG_HOME` set to `$HOME/.config`... using `$HOME/.config/.curlrc` instead of `$HOME/.config/curlrc`:

  ```bash
  bash-5.1$ XDG_CONFIG_HOME=~/.config strace curl 2>&1 | grep curlrc
  openat(AT_FDCWD, "/home/emanuele6/.config/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
  ```

**Comment by emanuele6** [comment]
> but i think, at least, not using `curlrc` instead of `.curlrc` when `XDG_CONFIG_HOME` is set is an unintentional curl bug:

https://github.com/curl/curl/blob/1c567f797bce0befce109bceac6cf751331ae43f/docs/cmdline-opts/config.d#L60

Maybe that is not unintentional, since it is documented exactly like, but the inconsistency between `/home/emanuele6/.config/.curlrc` when `XDG_CONFIG_HOME` is set to `/home/emanuele6/.config` and `/home/emanuele6/.config/curlrc` when `XDG_CONFIG_HOME` is not set is probably unintentional.

**Comment by WGRM** [comment]
> > curl uses the following XDG path for the default runtime configuration: `$XDG_CONFIG_HOME/.curlrc`
> 
> This is wrong. Using strace on curl 7.86.0 shipped by Debian:
> 
> ```
> strace curl 2>&1 | grep curlrc
> openat(AT_FDCWD, "/home/daniel/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/home/daniel/.config/curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/home/daniel/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
> ```

I guess it has been addressed then, already. Here is my output:

~/> strace curl 2>&1 | grep curlrc
openat(AT_FDCWD, "/home/user/.config/.curlrc", O_RDONLY) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
openat(AT_FDCWD, "/home/user/.curlrc", O_RDONLY) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)
~/> curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

**Comment by WGRM** [comment]
> @bagder I think they are saying that, if `XDG_CONFIG_HOME` is set, `curl` checks `$XDG_CONFIG_HOME/.curlrc` instead of `$XDG_CONFIG_HOME/curl/curlrc` which is what they expected.
> 
> Also, it seems `curl` only uses `curlrc` instad of `.curlrc` if `$XDG_CONFIG_HOME` is not set and is assumed to be `$HOME/.config/`.
> 
> I am not sure if using `$XDG_CONFIG_HOME/curlrc` instead of `$XDG_CONFIG_HOME/curl/curlrc` is not compatible with the XDG base directory specification since I am not very familiar with it, but i think, at least, not using `curlrc` instead of `.curlrc` when `XDG_CONFIG_HOME` is set is an unintentional `curl` bug:
> 
>     * With `XDG_CONFIG_HOME` not set... using `$XDG_CONFIG_HOME/.curlrc`:
>       ```shell
>       bash-5.1$ (unset -v XDG_CONFIG_HOME; strace curl 2>&1 | grep curlrc)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.config/curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       ```
> 
>     * With `XDG_CONFIG_HOME` set... using `$XDG_CONFIG_HOME/.curlrc`:
>       ```shell
>       bash-5.1$ XDG_CONFIG_HOME=hello strace curl 2>&1 | grep curlrc
>       openat(AT_FDCWD, "hello/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       ```
> 
>     * With `XDG_CONFIG_HOME` set to `$HOME/.config`... using `$HOME/.config/.curlrc` instead of `$HOME/.config/curlrc`:
>       ```shell
>       bash-5.1$ XDG_CONFIG_HOME=~/.config strace curl 2>&1 | grep curlrc
>       openat(AT_FDCWD, "/home/emanuele6/.config/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       openat(AT_FDCWD, "/home/emanuele6/.curlrc", O_RDONLY) = -1 ENOENT (No such file or directory)
>       ```

There are only two options. You either follow XDG or you don't - the UNIX way.

You dont:
You either use '$HOME/.curlrc' for this one file, or you use '$HOME/.curl/somercs' for many.

You do:
Its the same, but in another hierarchy to declutter the home, but no dot files.
You either use '$XDG_CONFIG_HOME/curlrc' for this one file, or you use '$XDG_CONFIG_HOME/curl/somercs' for many.
The former is not mentioned, but conventional. E.g. KDE apps do so. (K3B and others)

There is never a question, if the variable is set. If you follow XDG, you are supposed to take '.config' as default.
Thats why it is the actual standard value of XDG_CONFIG_HOME.

I hope i could clarify. Because this is a topic i know aboout.
