### ISSUE TITLE
Segfault in addbyter() when using pycurl

### ISSUE THREAD

**Issue by pixjuan** [curl/curl#1003]
### I did this
wrote code in PyCurl
 check for more details https://github.com/pycurl/pycurl/issues/409

```
"""destURL returns sftp://AAAAAA.BBBBBBB.com:22/~/CCCCCCC/DDD/EEEEEEEEEEEEEEEEEEEEEE.jpg"""
def initCurl(self, filename):
        c = pycurl.Curl()
        c.setopt(pycurl.VERBOSE, self.curlVerbose)
        v = self.destUrl(filename)
        c.setopt(pycurl.URL, v)
        if len(self.password) > 0 and self.serverProtocol == 'ftp':
            c.setopt(pycurl.USERPWD, self.username + ':' + self.password)
        else:
            c.setopt(pycurl.USERPWD, self.username)
        if len(self.pubkey) > 0:
            c.setopt(pycurl.SSH_PUBLIC_KEYFILE , self.pubkey)
        if len(self.privkey) > 0:
            c.setopt(pycurl.SSH_PRIVATE_KEYFILE , self.privkey)
        return c

def upload(self, filename):
    c = self.initCurl(filename)
    f = open(filename)
    c.setopt(pycurl.INFILE, f)
    c.setopt(pycurl.UPLOAD, 1)

    try:
        c.perform()
    except pycurl.error as ex:
        template = "PyCurl exception of type {0} occured. Arguments:\n{1!r}"
        message = template.format(type(ex).__name__, ex.args)
        self.logger.error(message)
       return False
    return True
```

### I expected the following
dowloading without a crash
### curl/libcurl version
curl 7.50.2 (i686-pc-linux-gnu) libcurl/7.50.2 OpenSSL/1.0.1m zlib/1.2.8 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

### operating system
Intel Edison image-20160606

**Comment by jay** [comment]
That website `BBBBBBB.com` is pretty shady but I take it that's just some filler for your example. Can you give us a way to reproduce without pycurl? Does it happen with all URLs, or is there a specific URL?

**Comment by pixjuan** [comment]
Yes, BBB[.com] was just a filler example. It happens with simple FTP URLs or with SFTP URLs . The FTP server a Pyftpd based server which does nothing special.
And I forgot to mention that the crash happens after quite a lot of attempts, can't tell how many but it can stay up for 30 minutes.

I didn't try to reproduce the bug without Python. The PyCurl told me to open an issue here.
I was hoping that something would be obvious in the core dumps I posted in the PyCurl issue.
But it look like I'll have try to make a very simple piece of code that also trigger the crash.
it may be hard to reproduce because it looks like it's a kind of race condition, or maybe a file still being written while we try to upload it.

**Comment by bagder** [comment]
Do you run your curl stuff in a single thread or in multiple? This is a libcurl using the stock (sync) name resolver. Do you have a timeout set for the requeset or do you think you might be getting a signal ?

**Comment by pixjuan** [comment]
@bagder I do use curl in multiple threads and didn't set a timeout at first.
And it looks like it doesn't crash anymore now that I'm using a timeout with c.setopt(pycurl.TIMEOUT_MS, myTimeout)
Was it a known problem?

**Comment by jay** [comment]
I think you're just masking the issue. Please review [libcurl thread safety](https://curl.haxx.se/libcurl/c/threadsafe.html), it sounds like you need to set [CURLOPT_NOSIGNAL](https://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html).

**Comment by bagder** [comment]
I agree with @jay on this. A timeout won't make libcurl do threading better. The reason I asked about timeouts is that the stack trace in your original report seemed to indicate that you received a signal, which could've been a timeout in curl when built to use the synchronous name resolver.

This `addbyter()` crash signature is commonly seen when libcurl is used multi-threaded *without* the necessary mutex locks that @jay mentions [above](https://github.com/curl/curl/issues/1003#issuecomment-246587657)

**Comment by pixjuan** [comment]
Well, when I replied I just had a quick look at modification I made, and in fact, I also set CURLOPT_NO_SIGNAL.
So this is normal behavior? If this is just a RTFM related bug, sorry about that, we can close this issue.
I understand the problem but just find it a bit disturbing that I can so easily crash a Python app.

**Comment by bagder** [comment]
> So this is normal behavior?

I can't tell.

First, I'm afraid we don't have the full picture here so it's not really clear to me if the rules are being followed. But then, you're asking the curl project and we're responsible for how libcurl works and what its API delivers, that's not necessarily the exact same thing as what pycurl should  provide and deliver.

**Comment by jay** [comment]
Whether or not pycurl is supposed to do it for you I don't know, you'll have to ask them. Their homepage says libcurl is thread safe but if you click that it takes you to the libcurl page that says there are exceptions. Maybe it should be changed to thread-safe (with [exceptions](https://curl.haxx.se/libcurl/c/threadsafe.html)). A little messier but more of a chance it will be clicked.

/cc @p

**Comment by pixjuan** [comment]
@jay Yes, I agree about the idea to phrase it as "thread-safe (with [exceptions](https://curl.haxx.se/libcurl/c/threadsafe.html))"
