### ISSUE TITLE
curl 7.86 cannot reach servers that curl 7.85 can

### ISSUE THREAD

**Issue by dHannasch** [curl/curl#10048]
The failure does not occur with all servers.
Unfortunately, I have not been able to reliably produce a server that curl 7.86 will fail on. Whatever goes wrong, it depends on characteristics of the server, and I don't know which ones.
Fortunately, I don't need to, because the master branch reliably *succeeds*, on every server. So clearly whatever is going wrong, you already found it and you already fixed it. (Though after a quick scan through the recent commits I'm still not sure which fix was the key one.)
Unfortunately, the fix has not been released (and the context is wanting a working version in an OS package manager, so it kind of needs a proper release).
Fortunately, the release of curl 7.87 is already scheduled for Wednesday December 21.
So mostly I'm just leaving this here so that anyone else coming here about the same problem will hopefully see this when searching the issues and not need to go through the full debugging process.

### I did this

I tried to curl a server using curl 7.85, curl 7.86, and the master branch of curl.

See https://gitlab.alpinelinux.org/dHannasch/curl-7.86-cannot-reach-servers-and-curl-7.85-can/-/blob/master/.gitlab-ci.yml for details.
Key excerpt:
```
  - git clone --single-branch --branch curl-${CURL_VERSION} --depth=1 https://github.com/curl/curl.git
  - cd curl
  - autoreconf -fi
  - ./configure --with-openssl
  - make
  - make install
  - LD_LIBRARY_PATH=/usr/local/lib curl --silent --show-error --verbose $CI_SERVER_HOST
```

### I expected the following

I expected the same result in all three cases.

### curl/libcurl version

curl-7_85_0, curl-7_86_0, and master

[curl -V output]

curl 7.86, and only curl 7.86, fails with
```
$ LD_LIBRARY_PATH=/usr/local/lib curl --silent --show-error --verbose $CI_SERVER_HOST
...
> User-Agent: curl/7.86.0-DEV
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

### operating system

Ubuntu 22.10 and Alpine 3.17; see https://gitlab.alpinelinux.org/dHannasch/curl-7.86-cannot-reach-servers-and-curl-7.85-can/-/blob/master/.gitlab-ci.yml

**Comment by jay** [comment]
Could it be https://github.com/curl/curl/issues/9813#issuecomment-1315878462 ?

**Comment by bagder** [comment]
Is `$CI_SERVER_HOST` a `http://` URL? Can you perhaps give us the full host name too?

**Comment by bagder** [comment]
marked as **not-a-bug** since it isn't a bug anymore, will also close this soon
