### ISSUE TITLE
Memory allocation problem in verify host (openssl.c)

### ISSUE THREAD

**Issue by haroldstuart** [curl/curl#1005]
Look at openssl.c, function verifyhost. Look for the comment that starts "In OpenSSL 0.9.7d and earlier" and then look at the block that follows.

There are two ways of allocating peer_CN. The first uses CURL's memory allocation routine and the second does not (it's allocated by OpenSSL instead). This causes an abort if the second method is used and the memory is freed.

**Comment by bagder** [comment]
Thanks, I fixed this now by partially reverting the change that introduced that mistake. Please double-check the code now and see if you spot any further problems

**Comment by haroldstuart** [comment]
The fix looks good. Thanks for the quick turnaround.

On Sep 9, 2016, at 2:36 PM, Daniel Stenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, I fixed this now by partially reverting the change that introduced that mistake. Please double-check the code now and see if you spot any further problems
