### ISSUE TITLE
Problems with connection SSL status

### ISSUE THREAD

**Issue by monnerat** [curl/curl#10053]
### I did this
`curl --ssl smtps://...`

### I expected the following
Single SSL negotiation.

### curl/libcurl version
current github snapshot

[curl -V output]
```
curl 7.87.0-DEV (x86_64-pc-linux-gnu) libcurl/7.87.0-DEV OpenSSL/3.0.5 zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.51.0 librtmp/2.3 libgsasl/1.10.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd
```
### operating system
Fedora 37 64-bit

`Linux patrick.monnerat 6.0.11-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Comment
There are problems in `Curl_ssl_cf_get_ssl()`:
1) The first cfilter is skipped, resulting in missing a leading SSL layer.
2) A clear connection over an SSL proxy will be considered as encrypted with the proxy SSL layer.

We currently do not have test support for implicit SSL imap/pop3/smtp, thus I can't write tests for these.

I did not try the command above, but I'm pretty sure it negotiates  SSL twice. I discovered these problems while maintaining the SAFEAUTH PR and by reading the code.

**Comment by bagder** [comment]
/cc @icing 

Does the `--ssl` option change anything? I mean does the bug reproduce without it as well?

**Comment by monnerat** [comment]
> Does the --ssl option change anything? I mean does the bug reproduce without it as well?

Yes: it requires explicit SSL on an implicit SSL connection. Function `Curl_ssl_use()` returns FALSE after implicit negotiation because the SSL layer is the first in chain. Then the protocol retries to negotiate SSL.
Again, I did not try it.

**Comment by icing** [comment]
The first comment is correct, namely that one filter to much is skipped in checking.

The second does no longer apply to master. Checks if a connection is using SSL end-to-end are now done via `Curl_conn_is_ssl(data, sockindex)` and that check stops at a IP_CONNECT tunnel filter. Meaning a HTTPS proxy by itself will return FALSE, as it should.

**Comment by monnerat** [comment]
@bagder: you can remove the SMTP label: it affects all protocols that support implicit TLS and use function `Curl_ssl_use()` (that is: at least smtp/imap/pop3, I did not check others).

**Comment by bagder** [comment]
Doesn't that rather imply that I should add imap, pop3 and ftp? Since it reproduces with smtp it still seems correct.

**Comment by monnerat** [comment]
> Doesn't that rather imply that I should add imap, pop3 and ftp? Since it reproduces with smtp it still seems correct.

ftp should be ok: it does not call `Curl_ssl_use(`)

**Comment by bagder** [comment]
> I know we do not have proxies for mail protocols but this can become a source of bug.

Sure we do! Both SOCKS proxies and tunneling through HTTP(S) proxies should work fine.

**Comment by icing** [comment]
We will replace `Curl_ssl_use()` with `Curl_conn_is_ssl()`. I have  a local branch with it, am now just a tad distracted. Good that you reported this issue.

**Comment by monnerat** [comment]
> We will replace Curl_ssl_use() with Curl_conn_is_ssl(). I have a local branch with it, am now just a tad distracted. Good that you reported this issue.

You're welcome!

Maybe it's time to feature implicit SSL for those protocols in our test server ?

**Comment by bagder** [comment]
> Maybe it's time to feature implicit SSL for those protocols in our test server ?

That would certainly be a great addition, yes

**Comment by icing** [comment]
Working on a fix.
