### ISSUE TITLE
TLS session resume causes "SSL3_GET_RECORD:wrong version number"

### ISSUE THREAD

**Issue by joernheissler** [curl/curl#1006]
I'm making requests to https://webservices.ebay.com/

This server has two IP addresses, 66.211.160.101 (Server_A) and 66.135.209.59 (Server_B).
Their DNS server (g3.ebay.com) gives out one of the two addresses by random.
Server_A seems to support TLSv1.2 while Server_B only supports TLSv1.0.

The client first talks to Server_A, advertises TLSv1.2 support (which the server also uses) and establishes a new TLS session. After some time the TCP connection is terminated (didn't check why, should not be important). For the next request, a new DNS query is done and Server_B is used. The client sends the TLS session ID it got from the first connection on the Client Hello. Again, the client offers to use up to TLSv1.2, but this time the server selects TLSv1.0.
The client then decides to terminate the connection and sends the server an Alert "Protocol Version" and returns to the user "error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number".

If both requests/connections go to the same server, there is no error. If first request goes to Server_B, second goes to Server_A, there is no error: the client advertises only TLSv1.0 support no Client Hello.

If I disable the session cache (CURLOPT_SSL_SESSIONID_CACHE --> 0) it works, so I can use this as a workaround.

**System information for test case:**

 * Debian/Unstable on amd64
 * libcurl3 Version 7.50.1-1
 * libssl1.0.2 Version 1.0.2h-1

**System information for real environment:**

 * Ubuntu/14.04 on amd64
 * php5-5.5.9
 * libcurl3-7.35.0
 * libssl-1.0.1f

**Test case:**

    #include <stdlib.h>
    #include <stdio.h>
    #include <curl/curl.h>

    int main(void)
    {
        struct curl_slist *host0 = curl_slist_append(NULL,
            "webservices.ebay.com:443:66.211.160.101"
        );
        struct curl_slist *host1 = curl_slist_append(curl_slist_append(NULL,
            "-webservices.ebay.com:443"),
            "webservices.ebay.com:443:66.135.209.59"
        );
        long enable_sessionid_cache = 1; // Set to 0 to enable workaround

        CURL *curl = curl_easy_init();
        if (!curl) abort();

        CURLcode code;
        if (0
            || (code = curl_easy_setopt(curl, CURLOPT_WRITEDATA, fopen("/dev/null", "w")))
            || (code = curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L))
            || (code = curl_easy_setopt(curl, CURLOPT_FORBID_REUSE, 1L))
            || (code = curl_easy_setopt(curl, CURLOPT_RESOLVE, host0))
            || (code = curl_easy_setopt(curl, CURLOPT_URL, "https://webservices.ebay.com/"))
            || (code = curl_easy_setopt(curl, CURLOPT_SSL_SESSIONID_CACHE, enable_sessionid_cache))
            || (code = curl_easy_perform(curl))
            || (code = curl_easy_setopt(curl, CURLOPT_RESOLVE, host1))
            || (code = curl_easy_perform(curl))
        ) printf("Curl: %s\n", curl_easy_strerror(code)), abort();
    }

**Output:**

    * Added webservices.ebay.com:443:66.211.160.101 to DNS cache
    * Hostname webservices.ebay.com was found in DNS cache
    *   Trying 66.211.160.101...
    * Connected to webservices.ebay.com (66.211.160.101) port 443 (#0)
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: /etc/ssl/certs
    * SSL connection using TLSv1.2 / AES128-GCM-SHA256
    * ALPN, server did not agree to a protocol
    * Server certificate:
    *  subject: C=US; ST=California; L=San Jose; O=eBay, Inc.; OU=Site Operations; CN=webservices.ebay.com
    *  start date: Aug  6 00:00:00 2014 GMT
    *  expire date: Oct  3 23:59:59 2016 GMT
    *  subjectAltName: host "webservices.ebay.com" matched cert's "webservices.ebay.com"
    *  issuer: C=US; O=VeriSign, Inc.; OU=VeriSign Trust Network; OU=Terms of use at https://www.verisign.com/rpa (c)10; CN=VeriSign Class 3 Secure Server CA - G3
    *  SSL certificate verify ok.
    > GET / HTTP/1.1
    Host: webservices.ebay.com
    Accept: */*

    < HTTP/1.1 200 OK
    < Server: Apache-Coyote/1.1
    < ETag: W/"354-1117144930000"
    < Last-Modified: Thu, 26 May 2005 22:02:10 GMT
    < Content-Type: text/html
    < Content-Length: 354
    < Date: Sun, 11 Sep 2016 09:01:30 GMT
    <
    * Closing connection 0
    * Added webservices.ebay.com:443:66.135.209.59 to DNS cache
    * Hostname webservices.ebay.com was found in DNS cache
    *   Trying 66.135.209.59...
    * Connected to webservices.ebay.com (66.135.209.59) port 443 (#1)
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: /etc/ssl/certs
    * SSL re-using session ID
    * error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
    * Closing connection 1
    Curl: SSL connect error
    Aborted

**PCAP** file is available here [curl_sessionid_bug.pcap.b64.txt](https://github.com/curl/curl/files/465884/curl_sessionid_bug.pcap.b64.txt) or here: http://wulf.eu.org/curl_sessionid_bug.pcap

**Comment by bagder** [comment]
I can confirm that this happens for me as well curl from git master using OpenSSL 1.0.2h but it works with my OpenSSL 1.1.x build. I'd say this is a strong indication the problem is in OpenSSL.

**Comment by bagder** [comment]
Session resumption is only a "suggestion" from a client perspective that can easily just be refused by the server and then a full handshake is done instead. I don't see what else curl can do in this case and I don't think there's a compelling reason for OpenSSL to fail like this.

**Comment by joernheissler** [comment]
Thanks for having a look at it. Closing because it's most likely not a curl issue.
