### ISSUE TITLE
latest libcurl doesn't build on arm mac

### ISSUE THREAD

**Issue by arpadboda** [curl/curl#10066]
### I did this
building in using cmake

### I expected the following
simply being built

### curl/libcurl version
latest release (7.86)

### operating system
MacOS Darwin

Error message:
/Users/aboda/nifi-minifi-cpp/build/thirdparty/curl-src/lib/strerror.c:879:11: error: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
    char *msg = strerror_r(err, buffer, sizeof(buffer));
          ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Which highlights that arm mac has posix type of strerror_r, but the related ifdefs are somehow set incorrectly:

>  861 #if defined(HAVE_STRERROR_R) && defined(HAVE_POSIX_STRERROR_R)
>  862  /*
>  863   * The POSIX-style strerror_r() may set errno to ERANGE if insufficient
>  864   * storage is supplied via 'strerrbuf' and 'buflen' to hold the generated
>  865   * message string, or EINVAL if 'errnum' is not a valid error number.
>  866   */
>  867   if(0 != strerror_r(err, buf, max)) {
>  868     if('\0' == buf[0])
>  869       msnprintf(buf, max, "Unknown error %d", err);
>  870   }
>  871 #elif defined(HAVE_STRERROR_R) && defined(HAVE_GLIBC_STRERROR_R)
>  872  /*
>  873   * The glibc-style strerror_r() only *might* use the buffer we pass to
>  874   * the function, but it always returns the error message as a pointer,
>  875   * so we must copy that string unconditionally (if non-NULL).
>  876   */
>  877   {
>  878     char buffer[256];
>  879     char *msg = strerror_r(err, buffer, sizeof(buffer));
>  880     if(msg)
>  881       strncpy(buf, msg, max);
>  882     else
>  883       msnprintf(buf, max, "Unknown error %d", err);
>  884   }
>  885 #else
>  886   {
>  887     /* !checksrc! disable STRERROR 1 */
>  888     const char *msg = strerror(err);
>  889     if(msg)
>  890       strncpy(buf, msg, max);
>  891     else
>  892       msnprintf(buf, max, "Unknown error %d", err);
>  893   }
>  894 #endif

The first ifdef should be true on this system, but somehow the 2nd branch gets compiled

**Comment by nickzman** [comment]
I was able to build the latest curl code successfully on my ARM Mac. Are you sure you have the latest command line tools for Xcode installed for your OS version? Usually that's the culprit.

**Comment by arpadboda** [comment]
@nickzman I'm on macos 12.2, xcode installed, but using clang 15 installed via brew.

**Comment by nickzman** [comment]
Install Apple's compilers and headers by typing `xcode-select --install` at the command line, let it install, and then it ought to work. You need to do this for some packages on Homebrew anyway.

**Comment by arpadboda** [comment]
@nickzman : does nothing as command line tools are already installed as expected.

**Comment by bagder** [comment]
fresh checkout of curl, first try using cmake:

~~~
$ mkdir build
$ /opt/homebrew/bin/cmake -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl ..
$ make -sj
~~~
worked

~~~
curl 7.87.1-DEV (Darwin) libcurl/7.87.1-DEV OpenSSL/3.0.7 zlib/1.2.11 libpsl/0.21.2 (+libicu/71.1) libssh2/1.10.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets
~~~

I then checked out the 7.86.0 tag as well to make sure it also worked, and it did.

This is a problem in your environment @arpadboda, not a curl issue.
