### ISSUE TITLE
Authentication failed on POP3

### ISSUE THREAD

**Issue by tbjorheim** [curl/curl#10073]
### I did this

curl -l pop3s://user:password@pop.online.no

### I expected the following

Check if there is any e-mails on the server.

### curl/libcurl version

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

Also tried, but same issue:
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

### operating system

Linux Mint 19.3

I have been using this command to check for emails, and it has worked perfect for a long time. But it seems like Telenor which have the online.no e-mail now have changed their e-mail servers.

I now get the following error:
curl: (67) Authentication failed: 45

But if I connect to the server using "openssl s_client -connect pop.online.no:995" and use the USER and PASS commands, it works.

The verbose output gives this:

`< +OK POP3 Bigfoot v1.0 server ready <96413.1670625352@mail56c60.megamailservers.eu>
> CAPA
< +OK Capability list follows
< TOP
< USER
< RESP-CODES
< AUTH-RESP-CODE
< EXPIRE NEVER
< UIDL
< STLS
< IMPLEMENTATION Bigfoot-v1
< .
> APOP user encryptedpassword
< -ERR [AUTH] Invalid password or username
* Authentication failed: 45
`

I have replaced the username and the encrypted password in the output.

I guess it maybe has something to do with the APOP authentication.

I have tried to add --login-options "AUTH=PLAIN;AUTH=LOGIN;AUTH=NTLM"

and then the output is "No known authentication mechanisms supported!"

**Comment by bagder** [comment]
For some reason it decides to use `APOP` for you, which seems to be what makes it go wrong.

You are using an almost three years old curl version, but I suspect that this functionality is still the same.

**Comment by tbjorheim** [comment]
I tried to see if it was possible to use an option to not use APOP, but I didn't found an option for that.

I know it's an old version, but that's because it's the one available to install from the default repository. Also tried 7.74 on another computer, but same issue.

I can use IMAP, since that works, but prefer POP3 the way I use it.

If you like to look into it, I can provide you with a username and password for an account on the server if you should need that to test.
