### ISSUE TITLE
The «--remote-name-all» option does not work

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10072]
### I did this
Start PowerShell 7.3.0 under the MS Windows and execute commands:
PS >
```
.\curl.exe --progress-bar --remote-name-all `
    --dump-header "Header32.txt" `
    "https://curl.se/windows/dl-7.86.0_2/curl-7.86.0_2-win32-mingw.zip" `
--next `
    --dump-header "Header64.txt" `
    "https://curl.se/windows/dl-7.86.0_2/curl-7.86.0_2-win64-mingw.zip"

 32, 64 | %{(Get-Content -LiteralPath Header$_.txt).Count}
```
################################################################################ 100,0%
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
22
22
### I expected the following
Option «--remote-name-all» changes the default action for all given URLs as written in the manual.
### curl/libcurl version
Build: 7.86.0_2
[curl -V output]
curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.11.0 nghttp3/0.7.1 libgsasl/2.2.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### operating system
MS Windows 10 last version with all updates

**Comment by jay** [comment]
This is not a bug. --next resets --remote-name-all:

_-:, --next will reset all local options and only global ones will have their values survive over to the operation following the -:, --next instruction._

If an option is global it will say so in the documentation. Note [--remote-name-all](https://curl.se/docs/manpage.html#--remote-name-all) does not say it's global.
