### ISSUE TITLE
Incorrect exit codes

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10075]
### I did this
In Cmd.exe:
`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe -y a & Echo %ErrorLevel%`
curl: option -y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

2

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0

`curl.exe "https://x.x"|More & Echo %ErrorLevel%`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: x.x

0
### I expected the following
Correct results.
### curl/libcurl version
Build: 7.86.0_2
[curl -V output]
curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.11.0 nghttp3/0.7.1 libgsasl/2.2.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows 10 last version with all updates

**Comment by dfandrich** [comment]
You're seeing the exit code of "More", not "curl.exe"

**Comment by u20221022** [comment]
> You're seeing the exit code of "More", not "curl.exe"

`curl.exe -y a & Echo %Date% %Time% %ErrorLevel%`
curl: option -y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
10.12.2022 20:31:50,81 2

`curl.exe -y a & Echo %Date% %Time% %ErrorLevel%`
curl: option -y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
10.12.2022 20:31:59,45 2

`curl.exe "https://x.x" & Echo %Date% %Time% %ErrorLevel%`
curl: (6) Could not resolve host: x.x
10.12.2022 20:32:47,65 2

`curl.exe "https://x.x" & Echo %Date% %Time% %ErrorLevel%`
curl: (6) Could not resolve host: x.x
10.12.2022 20:33:03,05 6

`curl.exe "https://x.x" & Echo %Date% %Time% %ErrorLevel%`
curl: (6) Could not resolve host: x.x
10.12.2022 20:33:27,56 6

Лишь бы прокукарекать, а там хоть и не рассветай.  Только что перезагрузил операционную систему и ошибка воспроизводится.

**Comment by u20221022** [comment]
Это не ошибка, а нормальное поведение глючной программы.  Так?

**Comment by jay** [comment]
Please write in English and spare us your insults. This is not a bug. In Windows when you specify environment %VARIABLE% on the command line it is expanded immediately without delay, **before execution of the entire command line**.

~~~
curl.exe -y a & Echo %Date% %Time% %ErrorLevel%  <--- errorlevel from previous call, not shown
curl: option -y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
10.12.2022 20:31:50,81 2

curl.exe -y a & Echo %Date% %Time% %ErrorLevel%  <--- errorlevel from previous call, above, which is 2
curl: option -y: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
10.12.2022 20:31:59,45 2

curl.exe "https://x.x" & Echo %Date% %Time% %ErrorLevel%  <--- errorlevel from previous call, above, which is 2
curl: (6) Could not resolve host: x.x
10.12.2022 20:32:47,65 2
~~~

Here is an easier way to understand it:

echo %time% & timeout 10 >NUL & echo %time%
17:50:13.91
17:50:13.91

echo %time% && timeout 10 >NUL && echo %time%
17:50:26.19
17:50:26.19

**Comment by u20221022** [comment]
«!» but not «%»: !ErrorLevel!
Sorry, I was not right.
