### ISSUE TITLE
imap-append error

### ISSUE THREAD

**Issue by lukaszgn** [curl/curl#1008]
**I did this**

execute example from https://curl.haxx.se/libcurl/c/imap-append.html with next changes:

	curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "SELECT INBOX.Sent");
	//SELECT folder
	res = curl_easy_perform(curl);
	//...
	curl_easy_setopt(curl, CURLOPT_URL, imap://server:port/1904); 
	curl_easy_setopt(curl, CURLOPT_READFUNCTION, payload_source);
	curl_easy_setopt(curl, CURLOPT_READDATA, &upload_ctx);
	curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
	curl_easy_setopt(curl, CURLOPT_INFILESIZE, uploadsize);//Added this line  without it I had additional error

**I expected the following**

Message appended to mail server.

But I obtain message "NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.)"

If I change curl_easy_setopt(curl, CURLOPT_URL, imap://server:port/1904)  to curl_easy_setopt(curl, CURLOPT_URL, imap://server:port/INBOX.Sent;UID=432) it not return error.
But server return :
> A005 APPEND INBOX.Sent (\Seen) {699}
<   OK

and communication still waiting without appending message. Sending with smtp base on the same code work well.

**operating system**

Windows 10

**curl/libcurl version**
7.49.1

Unfortunatly I cannot find ansfer for this.
Thanks!

**Comment by bagder** [comment]
Your application provides the name of the mailbox to append to so in this case you need to prefix it correctly. We should therefore focus on "communication still waiting without appending message".

Can you elaborate on exactly what that means?

**Comment by lukaszgn** [comment]
Thank you for response. Yes, I tried with prefixes and url "imap://server:port/INBOX.Sent;UID=432" look for me ok. 

After I use curl_easy_perform server return OK and waiting. In app I have:
```
	res = curl_easy_perform(curl);
	if (res != CURLE_OK) {
```
And it never reaches if. No error, just waiting. Presumably it waiting for message content. When I set breakpoint in function set in CURLOPT_READFUNCTION it never reaches there. That same function is used for smtp and it go there and work well.

**Comment by bagder** [comment]
> And it never reaches if. No error, just waiting. Presumably it waiting for message content.

So what is the exact response curl gets from the server when it has issued the `APPEND` command?

**Comment by lukaszgn** [comment]
I set timeout and then server return:

```
* Found bundle for host questy.nazwa.pl: 0xc82858 [serially]
* Re-using existing connection! (#0) with host questy.nazwa.pl
* Connected to questy.nazwa.pl (85.128.198.39) port 143 (#0)
> A005 APPEND INBOX.Sent (\Seen) {699}
< + OK
* Operation timed out after 5000 milliseconds with 0 bytes received
* Closing connection 0
```

**Comment by jay** [comment]
I think you're right about having to have an upload size for APPEND. Without that I get '[Info: Cannot APPEND with unknown input file size](https://github.com/curl/curl/blob/curl-7_50_2/lib/imap.c#L769-L773)'. Once I set CURLOPT_INFILESIZE it works though.
~~~c
    {
      long infilesize = 0;
      const char **p = payload_text;
      do {
        infilesize += strlen(*p);
      } while(*++p);
      curl_easy_setopt(curl, CURLOPT_INFILESIZE, infilesize);
    }
 ~~~

As far as the + continuation from the server mine is slightly different,
~~~
<= Recv header, 0000000012 bytes (0x0000000c)
0000: 2b 20 67 6f 20 61 68 65 61 64 0d 0a             + go ahead..
== Info: IMAP 0x324030 state change from APPEND to STOP
== Info: DO phase is complete
== Info: STATE: DOING => DO_DONE handle 0x310e88; line 1730 (connection #0)
== Info: STATE: DO_DONE => WAITPERFORM handle 0x310e88; line 1781 (connection #0)
== Info: STATE: WAITPERFORM => PERFORM handle 0x310e88; line 1791 (connection #0)
~~~
This was on gmail so the sent box is different:
~~~
    curl_easy_setopt(curl, CURLOPT_URL, "imaps://imap.gmail.com/%5BGmail%5D%2FSent%20Mail");
~~~
Also at least on gmail if you append more than one with the same `Message-ID` it won't show up in the outbox so you have to change that for each append.

I would lose the CURLOPT_CUSTOMREQUEST or even better try with a fresh copy of the example and see if that works for you.

/cc @captain-caveman2k

**Comment by lukaszgn** [comment]
Thank you very much. I created an example from fresh copy and i used
`curl_easy_setopt(curl, CURLOPT_URL, "imap://questy.nazwa.pl/INBOX.Sent");`
Without inserting the UID there. I also changed infilesize counter to Your and it work.

I have a different structure of the message, and probably the main error was bad value infilesize. When it is correct, everything looks good.
