### ISSUE TITLE
There is no difference between --styled-output and --no-styled-output.

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10082]
### I did this
![Styled Output](https://user-images.githubusercontent.com/117870409/206934208-bc82d668-8628-4ff1-8a06-d5a14cf83b12.png)

### I expected the following
Any difference in font.
### curl/libcurl version
Build: 7.86.0_2
[curl -V output]
curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.11.0 nghttp3/0.7.1 libgsasl/2.2.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows 10 last version with all updates

**Comment by bagder** [comment]
This is not a bug. This functionality does not exist on Windows because the terminals on Windows don't support this.
