### ISSUE TITLE
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `Curl_md4it'

### ISSUE THREAD

**Issue by esdrasdemorais** [curl/curl#10104]
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
Please tell us a lot more details on how this happened and how we can reproduce or we will just close this again.

**Comment by esdrasdemorais** [comment]
Hi, Sorry for late in answer.

I tried compile in my Dell Laptop with Slackware Current Latest Version.

And this error happened after run make command.

**Comment by esdrasdemorais** [comment]
Sorry for my late reply.

I tried compile in my Dell Laptop with Slackware Current Latest Version.

And this error happened after run make command:

*/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `Curl_md4it'
#10104 <https://github.com/curl/curl/issues/10104>*

Linux darkstar.example.net 5.19.16 #1 <https://github.com/curl/curl/pull/1>
SMP PREEMPT_DYNAMIC Sat Oct 15 14:42:05 CDT 2022 x86_64 Intel(R) Core(TM)
i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
Esdras de Morais da Silva
***@***.***
