### ISSUE TITLE
Environment variables are not observed when the Windows version curl is running in the WSL.

### ISSUE THREAD

**Issue by fxzxmic** [curl/curl#10113]
### I did this

When I set environment variable `all_proxy` in the powershell:
![image](https://user-images.githubusercontent.com/54622331/208406048-47d1a714-1ca9-4e7a-8fa1-fbd31663fc95.png)
It works fine.
When I set environment variable `all_proxy` in WSL:
![image](https://user-images.githubusercontent.com/54622331/208406421-50815a32-26e6-4c33-a82d-367a8da85713.png)
It does not use this environment variable.

### I expected the following

Curl can follow WSL's environment variable settings.

### curl/libcurl version

```
curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.11.0 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
```

### operating system

```
Windows 11 Build 22623.1028
WSL Version 1
```

**Comment by bagder** [comment]
The version output you showed seems to be the windows curl, not the WSL curl which you say you have a problem with.

When I try `all_proxy` on my Linux this happens:
~~~
$ all_proxy=does.not.example curl localhost
curl: (5) Could not resolve proxy: does.not.example

**Comment by bagder** [comment]
Sorry, it seems you are running the same executable just in different environments, is that so?

**Comment by fxzxmic** [comment]
> Sorry, it seems you are running the same executable just in different environments, is that so?

Yes, it is.

**Comment by bagder** [comment]
The Windows executable uses `GetEnvironmentVariableA()` to get environment variables. Presumably that doesn't work correctly to get environment variables you have set in the WSL shell.

This could arguably be considered a Windows/WSL bug I guess.

**Comment by fxzxmic** [comment]
Maybe you are right. I just kept looking for information until I found this: [`WSLENV`](https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/).
Therefore, the correct usage should be: `WSLENV=$WSLENV:all_proxy Desktop/bin/curl.exe https://www.google.com`.
![image](https://user-images.githubusercontent.com/54622331/208423641-8c5f4694-7c7c-4755-8a53-1d8413bd57cb.png)

**Comment by bagder** [comment]
a Windows/WSL "quirk" at least :grinning:
