### ISSUE TITLE
CMakeLists.txt uses comparisons in if() functions that are unsupported by some of CMake versions specified in cmake_minimum_required

### ISSUE THREAD

**Issue by nick-telia** [curl/curl#10128]
### I did this

I tried running CMake version 3.5.1 to build the latest Curl release (7.87.0).

Since `CMakeLists.txt` contains the line `cmake_minimum_required(VERSION 3.2...3.16 FATAL_ERROR)` I didn't expect the command to fail with my version of CMake. Unfortunately the usage of `GREATER_EQUAL` and ``GREATER_EQUAL`` that [became available](https://cmake.org/cmake/help/latest/command/if.html#greater-equal) only in CMake 3.7 led to the following error:
```
CMake Error at CMakeLists.txt:1093 (if):
  if given arguments:

    "NOT" "MSVC" "OR" "(" "MSVC_VERSION" "GREATER_EQUAL" "1900" ")"

  Unknown arguments specified


   Called from: [1]	/curl-7.87.0/CMakeLists.txt
-- Configuring incomplete, errors occurred!
```

Somewhat related: https://github.com/curl/curl/issues/9237

### I expected the following

Successful run of CMake or a warning about incompatible version.

### curl/libcurl version

7.87.0

### operating system

I was running a container built from Ubuntu 16.04.5 LTS.

**Comment by bagder** [comment]
If I knew cmake, I would move that version number check into the C code that needs to be built and linked to check for the symbol to avoid having cmake do it. But as I don't know how to, I propose we instead raise the lowest accepted cmake version to 3.7. Released in November 2016.

Anyone objects?
