### ISSUE TITLE
Domain suffixes in noproxy/no_proxy no longer work in 7.86.0

### ISSUE THREAD

**Issue by TaoK** [curl/curl#10122]
Although there does not seem to be a standard for support of `noproxy`/`no_proxy` (or even alignment on which it should be and which should take precedence), curl has for a long time or forever supported entries like `.mydomain.com` as a "wildcard" for `a.mydomain.com`, `b.mydomain.com`, etc.

As of 7.86.0, now distributed in Git for Windows and Msys2 (among many other environments I imagine), this no longer works, and domains must be individually specified in full.

This looks, at a glance, like it must be a regression in #9773, although I haven't taken the time to understand the code changes.

This is likely to impact users in corporate and academic environments.

**Comment by TaoK** [comment]
@mcarbonneaux, @bagder, does this seem plausible? If so, what's the process for resolving this - should I be asking those projects I depend on (Git for Windows, Msys) to revert, or does it make more sense to "roll forward"?

**Comment by TaoK** [comment]
Never mind - I couldn't find it because it's already closed: #9884.

I did find it through Git for Windows eventually: https://github.com/git-for-windows/git/issues/4171

**Comment by bagder** [comment]
... and 7.87.0 ships tomorrow, including the necessary fixes.

**Comment by mcarbonneaux** [comment]
to awesome !

**Comment by michael-o** [comment]
I can confirm that a build from master fixes the issue with suffices regardless of comma or space separation.

**Comment by chkpnt** [comment]
I've just stumbled over this, as the current macOS 13.2.1 includes curl 7.86.0. As macOS 12.6.3, which has been released in January, includes the much older version 7.79.1 of curl, I'm concerned that macOS 13 will stay on 7.86.0 for some time. :-/

@bagder Do you have any experience, how often Apple updates the shipped version of curl?

PS: Congratulations on the anniversary and many thanks for your life's work!

**Comment by michael-o** [comment]
> I've just stumbled over this, as the current macOS 13.2.1 includes curl 7.86.0. As macOS 12.6.3, which has been released in January, includes the much older version 7.79.1 of curl, I'm concerned that macOS 13 will stay on 7.86.0 for some time. :-/
> 
> @bagder Do you have any experience, how often Apple updates the shipped version of curl?
> 
> PS: Congratulations on the anniversary and many thanks for your life's work!

What is the problem compile it yourself? You have LLVM and all the tools to solve the problem.

**Comment by chkpnt** [comment]
I can confirm, that macOS 13.3 contains curl 7.87.0. :-)

@michael-o: It's not about myself. It's about the tens of thousands users of macOS in corporates, who updates their system to macOS 13.2.1 and wonder, why several programs doesn't work any longer as expected. I talk about people who doesn't know curl at all or how their proxy is configured via environment variables.

**Comment by michael-o** [comment]
> I can confirm, that macOS 13.3 contains curl 7.87.0. :-)
> 
> @michael-o: It's not about myself. It's about the tens of thousands users of macOS in corporates, who updates their system to macOS 13.2.1 and wonder, why several programs doesn't work any longer as expected. I talk about people who doesn't know curl at all or how their proxy is configured via environment variables.

I understand and agree, but in corporates I would expect they have a service which manages the Macs and should upgrade necessary software centrally.
