### ISSUE TITLE
curl 7.87.0 seems to break `curl_multi_socket_action`

### ISSUE THREAD

**Issue by q234rty** [curl/curl#10146]
### I did this
```bash
cd docs/examples
gcc -lcurl -levent hiperfifo.c
./a.out
```
Then open another terminal and do 
`echo "https://envs.net" > hiper.fifo`
It took about 2 minutes for the program to finish the request.
### I expected the following
The request is finished in a timely manner.
### curl/libcurl version

```
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

Arch Linux with kernel 6.1.1-arch1-1, openssl 3.0.7-4, libevent 2.1.12-4

**Comment by q234rty** [comment]
Bisected this to https://github.com/curl/curl/commit/dafdb20a26d0c890e83dea61a104b75408481ebd

**Comment by bagder** [comment]
@icing I think we need to start out by double-checking what the *getsock() calls returns for this case. This has the smell of a problem in there.

**Comment by icing** [comment]
@bagder is there more information tbh on how curl multi is used in this case?

**Comment by icing** [comment]
Hmm, I am unable to reproduce on a 7.87.0 build. It opens (and keeps a HTTP/2) connection and performs all requests in time.

**Comment by q234rty** [comment]
@icing It's possible that reproducing this requires certain network conditions. If you need any debug output etc. from me feel free to comment on this issue.
