### ISSUE TITLE
Why curl: (56) Recv failure: Connection reset by peer? 

### ISSUE THREAD

**Issue by luofeiyu** [curl/curl#1016]
I have build forword proxy  on my vps.

    curl -x "vps_ip:80"  https://www.yahoo.com

It get normal output on my terminal.

  curl -x "vps_ip:80" https://dl-ssl.google.com/linux/linux_signing_key.pub

An error info occur.

    curl: (56) Recv failure: Connection reset by peer

Why [url]https://www.yahoo.com[/url] can get by curl with forword proxy,[url]https://dl-ssl.google.com/linux/linux_signing_key.pub[/url] can't get by the same forword proxy on the same machine?

**Comment by bagder** [comment]
If you enable debug tracing with `--trace-ascii dump.txt`, does it shed any more light? "Recv failure" is a really generic error so its hard for us to tell without more info. Can you attach such a debug trace here and we might be able to tell something more?

**Comment by luofeiyu** [comment]
cat /tmp/dump.txt
== Info: Hostname was NOT found in DNS cache
== Info:   Trying vps_ip...
== Info: Connected to vps_ip (vps_ip) port 80 (#0)
== Info: Establish HTTP proxy tunnel to dl-ssl.google.com:443
=> Send header, 126 bytes (0x7e)
0000: CONNECT dl-ssl.google.com:443 HTTP/1.1
0028: Host: dl-ssl.google.com:443
0045: User-Agent: curl/7.38.0
005e: Proxy-Connection: Keep-Alive
007c: 
== Info: Recv failure: Connection reset by peer
== Info: Received HTTP code 0 from proxy after CONNECT
== Info: Closing connection 0

**Comment by bagder** [comment]
It looks like your proxy simply doesn't respond properly here.

**Comment by luofeiyu** [comment]
To close the firewall ,problem solved.

**Comment by jay** [comment]
Ok thanks for the update.

**Comment by qingdi** [comment]
close firewall is workless
