### ISSUE TITLE
Exceeds the set speed limit when downloading a file

### ISSUE THREAD

**Issue by Noff1997** [curl/curl#10173]
Platform :
OS ALT: Workstation K 10.1 x86-64

Package:
curl 7.87.0-alt1

Step:
1) Start downloading file with speed limit
(example) curl --limit-rate 600K -O https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/patch-4.9.xz

Result:
download speed exceeded ( watch log)
[result.log](https://github.com/curl/curl/files/10313115/result.log)

Expected result:
The speed does not exceed the set speed limit

**Comment by bagder** [comment]
This is not an exact science. Virtually everyone has their own take on exactly rate limiting should work.

curl makes an effort to stay below the specified rate limit, based on the "current speed" which means the last few seconds, though always at least three seconds.

This algorithm will make it occasionally go above the limit, but over time it should stick to the limit.

Trying to make it more exact by some measurement will make it less exact by some other. I think it works good enough.

**Comment by Noff1997** [comment]
is a regression to curl-7.86.0-alt1

in version curl-7.86.0-alt1 values ​​do not exceed the set limit
using the same download file
watch the video

https://user-images.githubusercontent.com/96541774/209800592-fe178eea-f8bd-4096-97f8-185985b78c5a.mp4

**Comment by bagder** [comment]
The behavior may be slightly different due to some internal changes, my points still remain though and the rate limit logic still works exactly the same way.

**Comment by bagder** [comment]
As long as it is only marginally over (or under) the requested speed, I think that is fine and I consider that working as intended. It seems it is for you as well even if it is slightly different between the versions.

**Comment by Reclick55** [comment]
Funny how
You don't change nothing
On index speed for downloads or anything to do with anything being BLOCKED from cash out and have separate strings so on to decive you from what belong to you so anyways the hacks and scammers always changing my index and such strings to change into their index and collect everything from me well guys the JOKE ON YOU... as me I don't touch anything on my index's or codespaces and how did I get a coded machine attached too my laptop coding everything I do Hmmm yeah stupid timestamps being change and all well guys great run you think you got it all the trust haha ha you been had bye bye cunts
