### ISSUE TITLE
android4.2  System.loadLibrary("curl"); get errors.

### ISSUE THREAD

**Issue by luhuajcdd** [curl/curl#10177]
### I did this
 System.loadLibrary("curl");

### I expected the following
D/dalvikvm( 2918): Trying to load lib /data/app-lib/com.example.vdi.android_ios-1/libcurl2.so 0x42287ec8
F/libc    ( 2918): Fatal signal 8 (SIGFPE) at 0x00000b66 (code=0), thread 2918 (vdi.android_ios)
I/DEBUG   (30657): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (30657): Build fingerprint: 'rk31sdk/examplevdi_rk31/rk31sdk:4.2.2/JDQ39/eng.ubuntu.20221104.144906:eng/test-keys'
I/DEBUG   (30657): Revision: '0'
I/DEBUG   (30657): pid: 2918, tid: 2918, name: vdi.android_ios  >>> com.example.vdi.android_ios <<<
I/DEBUG   (30657): signal 8 (SIGFPE), code -6 (?), fault addr 00000b66
I/DEBUG   (30657):     r0 00000000  r1 00000008  r2 62001361  r3 6200136d
I/DEBUG   (30657):     r4 40056838  r5 00000016  r6 40056838  r7 00000025
I/DEBUG   (30657):     r8 62001360  r9 62001361  sl 62001361  fp 08f0a7f4
I/DEBUG   (30657):     ip ffffda28  sp bea080d0  lr 400498a4  pc 4004913c  cpsr 20000010
I/DEBUG   (30657):     d0  70612f617461642f  d1  6f632f62696c2d70
I/DEBUG   (30657):     d2  6f66676e61732e6d  d3  6e612e6964762e72
I/DEBUG   (30657):     d4  0000000000000000  d5  3f80000000000000
I/DEBUG   (30657):     d6  41e6f87800000000  d7  41e6f87800000000
I/DEBUG   (30657):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (30657):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (30657):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (30657):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (30657):     d16 000000df93e2fdca  d17 0000000000000000
I/DEBUG   (30657):     d18 bea05bc8bea05b80  d19 5cb31118bea05b78
I/DEBUG   (30657):     d20 0000000700000007  d21 0000000700000007
I/DEBUG   (30657):     d22 0000000000000000  d23 0000000000000000
I/DEBUG   (30657):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   (30657):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   (30657):     d28 0000000000000005  d29 0000000000000000
I/DEBUG   (30657):     d30 0000000000000000  d31 0000000000000000
I/DEBUG   (30657):     scr 8000001c
I/DEBUG   (30657): 
I/DEBUG   (30657): backtrace:
I/DEBUG   (30657):     #00  pc 0000913c  /system/bin/linker (kill+12)
I/DEBUG   (30657):     #01  pc 000098a0  /system/bin/linker (__aeabi_ldiv0+8)
I/DEBUG   (30657): 
I/DEBUG   (30657): stack:
I/DEBUG   (30657):          bea08090  bea08148  [stack]
I/DEBUG   (30657):          bea08094  5aeea230  
I/DEBUG   (30657):          bea08098  41e6f878  [heap]
I/DEBUG   (30657):          bea0809c  d690001d  
I/DEBUG   (30657):          bea080a0  00000001  
I/DEBUG   (30657):          bea080a4  b63def8d  
I/DEBUG   (30657):          bea080a8  5aeea230  
I/DEBUG   (30657):          bea080ac  5aeea230  
I/DEBUG   (30657):          bea080b0  41e6f878  [heap]
I/DEBUG   (30657):          bea080b4  d690001d  
I/DEBUG   (30657):          bea080b8  c0000000  
I/DEBUG   (30657):          bea080bc  00000038  
I/DEBUG   (30657):          bea080c0  00000037  
I/DEBUG   (30657):          bea080c4  00000000  
I/DEBUG   (30657):          bea080c8  df0027ad  
I/DEBUG   (30657):          bea080cc  00000000  
I/DEBUG   (30657):     #00  bea080d0  40056838  
I/DEBUG   (30657):          ........  ........
I/DEBUG   (30657):     #01  bea080d0  40056838  
I/DEBUG   (30657):          bea080d4  00000016  
I/DEBUG   (30657):          bea080d8  40056838  
I/DEBUG   (30657):          bea080dc  62000240  /data/app-lib/com.example.vdi.android_ios-1/libcurl2.so
I/DEBUG   (30657):          bea080e0  ffffda28  
I/DEBUG   (30657):          bea080e4  400498a4  /system/bin/linker (__aeabi_ldiv0+12)
I/DEBUG   (30657):          bea080e8  00000000  
I/DEBUG   (30657):          bea080ec  40043297  /system/bin/linker
I/DEBUG   (30657):          bea080f0  6200136d  /data/app-lib/com.example.vdi.android_ios-1/libcurl2.so
I/DEBUG   (30657):          bea080f4  40056838  
I/DEBUG   (30657):          bea080f8  00000016  
I/DEBUG   (30657):          bea080fc  40056838  
I/DEBUG   (30657):          bea08100  00539a0c  
I/DEBUG   (30657):          bea08104  62000000  /data/app-lib/com.example.vdi.android_ios-1/libcurl2.so
I/DEBUG   (30657):          bea08108  6202e9a4  /data/app-lib/com.example.vdi.android_ios-1/libcurl2.so
I/DEBUG   (30657):          bea0810c  4004334d  /system/bin/linker
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r2:
I/DEBUG   (30657):     62001340 000008c3 00000000 00000001 000000eb  
I/DEBUG   (30657):     62001350 00000001 0000001a 00000000 00000000  
I/DEBUG   (30657):     62001360 6c5f5f00 5f636269 74696e69 635f5f00  
I/DEBUG   (30657):     62001370 615f6178 69786574 5f5f0074 69676572  
I/DEBUG   (30657):     62001380 72657473 6674615f 006b726f 6c6c616d  
I/DEBUG   (30657):     62001390 6600636f 00656572 656d6974 636f6c00  
I/DEBUG   (30657):     620013a0 69746c61 7300656d 6d637274 6f660070  
I/DEBUG   (30657):     620013b0 006e6570 69727766 66006574 63747570  
I/DEBUG   (30657):     620013c0 6c666600 00687375 6f647473 73007475  
I/DEBUG   (30657):     620013d0 72656474 656d0072 706d636d 72747300  
I/DEBUG   (30657):     620013e0 00726863 72727473 00726863 6c727473  
I/DEBUG   (30657):     620013f0 6d006e65 68636d65 70660072 00737475  
I/DEBUG   (30657):     62001400 74727473 69006c6f 6c74636f 61657200  
I/DEBUG   (30657):     62001410 5f5f0064 6e727265 736c006f 366b6565  
I/DEBUG   (30657):     62001420 706f0034 66006e65 65706f64 6c63006e  
I/DEBUG   (30657):     62001430 0065736f 65727473 726f7272 72747300  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r3:
I/DEBUG   (30657):     6200134c 000000eb 00000001 0000001a 00000000  
I/DEBUG   (30657):     6200135c 00000000 6c5f5f00 5f636269 74696e69  
I/DEBUG   (30657):     6200136c 635f5f00 615f6178 69786574 5f5f0074  
I/DEBUG   (30657):     6200137c 69676572 72657473 6674615f 006b726f  
I/DEBUG   (30657):     6200138c 6c6c616d 6600636f 00656572 656d6974  
I/DEBUG   (30657):     6200139c 636f6c00 69746c61 7300656d 6d637274  
I/DEBUG   (30657):     620013ac 6f660070 006e6570 69727766 66006574  
I/DEBUG   (30657):     620013bc 63747570 6c666600 00687375 6f647473  
I/DEBUG   (30657):     620013cc 73007475 72656474 656d0072 706d636d  
I/DEBUG   (30657):     620013dc 72747300 00726863 72727473 00726863  
I/DEBUG   (30657):     620013ec 6c727473 6d006e65 68636d65 70660072  
I/DEBUG   (30657):     620013fc 00737475 74727473 69006c6f 6c74636f  
I/DEBUG   (30657):     6200140c 61657200 5f5f0064 6e727265 736c006f  
I/DEBUG   (30657):     6200141c 366b6565 706f0034 66006e65 65706f64  
I/DEBUG   (30657):     6200142c 6c63006e 0065736f 65727473 726f7272  
I/DEBUG   (30657):     6200143c 72747300 00707564 74727473 6d006b6f  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r4:
I/DEBUG   (30657):     40056818 5aee4000 40056714 5aee8e38 00000000  
I/DEBUG   (30657):     40056828 400566f4 00000001 5aee4000 00000000  
I/DEBUG   (30657):     40056838 6362696c 326c7275 006f732e 00000000  
I/DEBUG   (30657):     40056848 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056858 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056868 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056878 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056888 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056898 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     400568a8 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     400568b8 62000034 0000000b 00000000 62000000  
I/DEBUG   (30657):     400568c8 0053d000 00000000 62539504 00000000  
I/DEBUG   (30657):     400568d8 00000000 00000000 00000000 62001360  
I/DEBUG   (30657):     400568e8 62000240 00000000 00000000 00000000  
I/DEBUG   (30657):     400568f8 00000000 62539a00 6202e9a4 000000e2  
I/DEBUG   (30657):     40056908 62001c2c 000035ed 6251c980 00000002  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r6:
I/DEBUG   (30657):     40056818 5aee4000 40056714 5aee8e38 00000000  
I/DEBUG   (30657):     40056828 400566f4 00000001 5aee4000 00000000  
I/DEBUG   (30657):     40056838 6362696c 326c7275 006f732e 00000000  
I/DEBUG   (30657):     40056848 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056858 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056868 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056878 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056888 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     40056898 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     400568a8 00000000 00000000 00000000 00000000  
I/DEBUG   (30657):     400568b8 62000034 0000000b 00000000 62000000  
I/DEBUG   (30657):     400568c8 0053d000 00000000 62539504 00000000  
I/DEBUG   (30657):     400568d8 00000000 00000000 00000000 62001360  
I/DEBUG   (30657):     400568e8 62000240 00000000 00000000 00000000  
I/DEBUG   (30657):     400568f8 00000000 62539a00 6202e9a4 000000e2  
I/DEBUG   (30657):     40056908 62001c2c 000035ed 6251c980 00000002  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r8:
I/DEBUG   (30657):     62001340 000008c3 00000000 00000001 000000eb  
I/DEBUG   (30657):     62001350 00000001 0000001a 00000000 00000000  
I/DEBUG   (30657):     62001360 6c5f5f00 5f636269 74696e69 635f5f00  
I/DEBUG   (30657):     62001370 615f6178 69786574 5f5f0074 69676572  
I/DEBUG   (30657):     62001380 72657473 6674615f 006b726f 6c6c616d  
I/DEBUG   (30657):     62001390 6600636f 00656572 656d6974 636f6c00  
I/DEBUG   (30657):     620013a0 69746c61 7300656d 6d637274 6f660070  
I/DEBUG   (30657):     620013b0 006e6570 69727766 66006574 63747570  
I/DEBUG   (30657):     620013c0 6c666600 00687375 6f647473 73007475  
I/DEBUG   (30657):     620013d0 72656474 656d0072 706d636d 72747300  
I/DEBUG   (30657):     620013e0 00726863 72727473 00726863 6c727473  
I/DEBUG   (30657):     620013f0 6d006e65 68636d65 70660072 00737475  
I/DEBUG   (30657):     62001400 74727473 69006c6f 6c74636f 61657200  
I/DEBUG   (30657):     62001410 5f5f0064 6e727265 736c006f 366b6565  
I/DEBUG   (30657):     62001420 706f0034 66006e65 65706f64 6c63006e  
I/DEBUG   (30657):     62001430 0065736f 65727473 726f7272 72747300  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near r9:
I/DEBUG   (30657):     62001340 000008c3 00000000 00000001 000000eb  
I/DEBUG   (30657):     62001350 00000001 0000001a 00000000 00000000  
I/DEBUG   (30657):     62001360 6c5f5f00 5f636269 74696e69 635f5f00  
I/DEBUG   (30657):     62001370 615f6178 69786574 5f5f0074 69676572  
I/DEBUG   (30657):     62001380 72657473 6674615f 006b726f 6c6c616d  
I/DEBUG   (30657):     62001390 6600636f 00656572 656d6974 636f6c00  
I/DEBUG   (30657):     620013a0 69746c61 7300656d 6d637274 6f660070  
I/DEBUG   (30657):     620013b0 006e6570 69727766 66006574 63747570  
I/DEBUG   (30657):     620013c0 6c666600 00687375 6f647473 73007475  
I/DEBUG   (30657):     620013d0 72656474 656d0072 706d636d 72747300  
I/DEBUG   (30657):     620013e0 00726863 72727473 00726863 6c727473  
I/DEBUG   (30657):     620013f0 6d006e65 68636d65 70660072 00737475  
I/DEBUG   (30657):     62001400 74727473 69006c6f 6c74636f 61657200  
I/DEBUG   (30657):     62001410 5f5f0064 6e727265 736c006f 366b6565  
I/DEBUG   (30657):     62001420 706f0034 66006e65 65706f64 6c63006e  
I/DEBUG   (30657):     62001430 0065736f 65727473 726f7272 72747300  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near sl:
I/DEBUG   (30657):     62001340 000008c3 00000000 00000001 000000eb  
I/DEBUG   (30657):     62001350 00000001 0000001a 00000000 00000000  
I/DEBUG   (30657):     62001360 6c5f5f00 5f636269 74696e69 635f5f00  
I/DEBUG   (30657):     62001370 615f6178 69786574 5f5f0074 69676572  
I/DEBUG   (30657):     62001380 72657473 6674615f 006b726f 6c6c616d  
I/DEBUG   (30657):     62001390 6600636f 00656572 656d6974 636f6c00  
I/DEBUG   (30657):     620013a0 69746c61 7300656d 6d637274 6f660070  
I/DEBUG   (30657):     620013b0 006e6570 69727766 66006574 63747570  
I/DEBUG   (30657):     620013c0 6c666600 00687375 6f647473 73007475  
I/DEBUG   (30657):     620013d0 72656474 656d0072 706d636d 72747300  
I/DEBUG   (30657):     620013e0 00726863 72727473 00726863 6c727473  
I/DEBUG   (30657):     620013f0 6d006e65 68636d65 70660072 00737475  
I/DEBUG   (30657):     62001400 74727473 69006c6f 6c74636f 61657200  
I/DEBUG   (30657):     62001410 5f5f0064 6e727265 736c006f 366b6565  
I/DEBUG   (30657):     62001420 706f0034 66006e65 65706f64 6c63006e  
I/DEBUG   (30657):     62001430 0065736f 65727473 726f7272 72747300  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near fp:
I/DEBUG   (30657):     08f0a7d4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a7e4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a7f4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a804 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a814 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a824 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a834 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a844 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a854 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a864 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a874 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a884 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a894 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a8a4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a8b4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657):     08f0a8c4 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (30657): 
I/DEBUG   (30657): memory near sp:
I/DEBUG   (30657):     bea080b0 41e6f878 d690001d c0000000 00000038  
I/DEBUG   (30657):     bea080c0 00000037 00000000 df0027ad 00000000  
I/DEBUG   (30657):     bea080d0 40056838 00000016 40056838 62000240  
I/DEBUG   (30657):     bea080e0 ffffda28 400498a4 00000000 40043297  
I/DEBUG   (30657):     bea080f0 6200136d 40056838 00000016 40056838  
I/DEBUG   (30657):     bea08100 00539a0c 62000000 6202e9a4 4004334d  
I/DEBUG   (30657):     bea08110 5aeea230 5aeea230 41e6f878 d6a0001d  
I/DEBUG   (30657):     bea08120 00000001 bea081a0 400d89b4 40098020  
I/DEBUG   (30657):     bea08130 62000250 00000001 00000000 6202e9a4  
I/DEBUG   (30657):     bea08140 4005088c 62000240 62001360 000000e2  
I/DEBUG   (30657):     bea08150 bea08198 0000d1bc bea08198 40056838  
I/DEBUG   (30657):     bea08160 bea08198 625395e4 bea08218 bea081a4  
I/DEBUG   (30657):     bea08170 00000000 400d8a60 00000001 400442f5  
I/DEBUG   (30657):     bea08180 41e6f878 41e6f878 d6a0001d 5aeea230  
I/DEBUG   (30657):     bea08190 573efb18 40098010 400500ac 40050f40  
I/DEBUG   (30657):     bea081a0 40050cf8 00000000 573efb18 40098010  
I/DEBUG   (30657): 
I/DEBUG   (30657): code around pc:
I/DEBUG   (30657):     4004911c e3a070f0 ef000000 e8bd0090 e12fff1e  
I/DEBUG   (30657):     4004912c eaffffea e92d50f0 e3a07025 ef000000  
I/DEBUG   (30657):     4004913c e8bd50f0 e1b00000 512fff1e ea00091e  
I/DEBUG   (30657):     4004914c e240c001 e35c0002 e52de004 e24dd00c  
I/DEBUG   (30657):     4004915c 8a000006 e28d3004 eb0000f8 e3500000  
I/DEBUG   (30657):     4004916c 059d0004 1a000003 e28dd00c e8bd8000  
I/DEBUG   (30657):     4004917c eb0000f2 eafffffb e3e00000 eafffff9  
I/DEBUG   (30657):     4004918c e12fff1e 2400b513 94019400 e9e6f000  
I/DEBUG   (30657):     4004919c b508bd1c 220a2100 f84cf000 0000bd08  
I/DEBUG   (30657):     400491ac 43f0e92d 28004603 4a1dd031 6812447a  
I/DEBUG   (30657):     400491bc 2a006812 4680d02d cb01f810 0500f11c  
I/DEBUG   (30657):     400491cc 2501bf18 0f3df1bc 2400bf0c 0401f005  
I/DEBUG   (30657):     400491dc d1f02c00 0808ebc3 e0114614 9b01f816  
I/DEBUG   (30657):     400491ec d10d454f b1bd3d01 7b01f810 d1f52f00  
I/DEBUG   (30657):     400491fc ebc2e006 3001020c 600b1093 83f0e8bd  
I/DEBUG   (30657):     4004920c f85446a4 b1280b04 4645461e e8bde7eb  
I/DEBUG   (30657): 
I/DEBUG   (30657): code around lr:
I/DEBUG   (30657):     40049884 eb000016 e59de004 e28dd008 e8bd000c  
I/DEBUG   (30657):     40049894 e12fff1e e92d4002 e3a00008 eb00078c  
I/DEBUG   (30657):     400498a4 e8bd8002 e92d40f8 e1a04002 e1a06000  
I/DEBUG   (30657):     400498b4 e1a07001 e1a05003 eb00051c e59dc018  
I/DEBUG   (30657):     400498c4 e0030194 e0253590 e0832094 e0853003  
I/DEBUG   (30657):     400498d4 e0562002 e0c73003 e1cc20f0 e8bd80f8  
I/DEBUG   (30657):     400498e4 e92d40f8 e1a04002 e1a06000 e1a07001  
I/DEBUG   (30657):     400498f4 e1a05003 eb000626 e59dc018 e0050590  
I/DEBUG   (30657):     40049904 e0832490 e0255194 e0853003 e0562002  
I/DEBUG   (30657):     40049914 e0c73003 e1cc20f0 e8bd80f8 e5903000  
I/DEBUG   (30657):     40049924 e3130101 13833102 03c33102 e0800003  
I/DEBUG   (30657):     40049934 e12fff1e e92d4ff0 e1a04000 e59f51a8  
I/DEBUG   (30657):     40049944 e24dd014 e59f31a4 e2416002 e08f5005  
I/DEBUG   (30657):     40049954 e7953003 e3530000 0a000005 e1a00006  
I/DEBUG   (30657):     40049964 e28d100c ebffe622 e2509000 1a000007  
I/DEBUG   (30657):     40049974 ea000056 e59f3178 e59f2178 e7953003 

### curl/libcurl version
7.86.0

[curl -V output]

### operating system
android4.2

**Comment by bagder** [comment]
How is this a curl problem?
