### ISSUE TITLE
autobuilds/Solaris: FREE ERROR in test 1939 [curl_easy_cleanup without curl_multi_remove_handle - in CONNECT]

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#10194]
### I did this

Look at @dago 's Solaris autobuilds. Test 1939 fails with:
```
** MEMORY FAILURE
FREE ERROR: No memory allocated: MEM /lib/url.c:2068 free(0x629f0)
```

The first build with the error seems to be https://curl.se/dev/log.cgi?id=20221230160947-660168, with the most recent commit being
71b7e01 lib: connect/h2/h3 refactor

### I expected the following

Test 1939 succeeding.

### curl/libcurl version

```
Install prefix: /usr/local
Compiler: /opt/csw/bin/gcc
CFLAGS: -Werror-implicit-function-declaration -g -O0 -std=gnu89 -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wbad-function-cast -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wold-style-definition -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -ftree-vrp -Wdouble-promotion -Wformat=2 -Warray-bounds=2 -Wno-system-headers
CPPFLAGS: -isystem /opt/csw/include -isystem /opt/csw/include -isystem /opt/csw/include -isystem /opt/csw/include
LDFLAGS: -L/opt/csw/lib -L/opt/csw/lib -L/opt/csw/lib -L/opt/csw/lib -L/opt/csw/lib
LIBS: -lnghttp2 -lidn2 -lrtmp -lgsasl -lpsl -lssl -lcrypto -lssl -lcrypto -lldap -llber -lzstd -lbrotlidec -lz -lrt -lsocket -lnsl

curl version: 7.87.1-DEV
SSL: enabled (OpenSSL)
SSH: no (--with-{libssh,libssh2})
zlib: enabled
brotli: enabled (libbrotlidec)
zstd: enabled (libzstd)
GSS-API: no (--with-gssapi)
GSASL: enabled
TLS-SRP: enabled
resolver: default (--enable-ares / --enable-threaded-resolver)
IPv6: enabled
Unix sockets: enabled
IDN: enabled (libidn2)
Build libcurl: Shared=yes, Static=yes
Built-in manual: enabled
--libcurl option: enabled (--disable-libcurl-option)
Verbose errors: enabled (--disable-verbose)
Code coverage: disabled
SSPI: no (--enable-sspi)
ca cert bundle: no
ca cert path: no
ca fallback: no
LDAP: enabled (OpenLDAP)
LDAPS: enabled
RTSP: enabled
RTMP: enabled (librtmp)
PSL: enabled
Alt-svc: enabled (--disable-alt-svc)
Headers API: enabled (--disable-headers-api)
HSTS: enabled (--disable-hsts)
HTTP1: enabled (internal)
HTTP2: enabled (nghttp2)
HTTP3: no (--with-ngtcp2, --with-quiche --with-msh3)
ECH: no (--enable-ech)
WebSockets: no (--enable-websockets)
Protocols: DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SMB SMBS SMTP SMTPS TELNET TFTP
Features: GSASL HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets alt-svc brotli libz threadsafe zstd
```

### operating system

Solaris 10

**Comment by bagder** [comment]
Difficult, as this does not seem to trigger on any build in the CI setup. I also cannot make this happen on any of my machines even when trying the same configure line. I have not yet been able to get access to a Solaris machine to see if this can be reproduce at will there. (I can't seem to login to [cfarm](https://gcc.gnu.org/wiki/CompileFarm) machines at all atm...)

**Comment by dago** [comment]
Hi @bagder 

I can set up an account on the buildfarm for you, the two Solaris machines at cfarm are actually also the OpenCSW machines. However, getting the cfarm access restored would be best.

Best regards -- Dago

**Comment by bagder** [comment]
@dago: I can login fine to all/most other cfarm machines, but not to the gcc210/gcc211 hosts that are the Solaris  machines. Presumably there's some special ssh config magic needed.

**Comment by bagder** [comment]
@dago it would be super helpful if you could change the Solaris CI jobs to actually run 'make test' like other CI jobs and report errors correctly.

 [this CI job](https://buildfarm.opencsw.org/buildbot/builders/curl-unthreaded-solaris10-i386/builds/12360) reports green and successful, but the log shows it failing this 1939 test as well as 977...

**Comment by bagder** [comment]
For the record: this issue is not Solaris specific, it just happened to reproduce most easily on this machine. It is a generic bug. Test 1939 working exactly as intended.

**Comment by dago** [comment]
Hi Daniel,

> @dago it would be super helpful if you could change the Solaris CI jobs to actually run 'make test' like other CI jobs and report errors correctly.

Currently the CI test does `/tests/testcurl.pl` and I vaguely recall that this was the command to run for CI. I can of course run other commands if that helps. Should I just run `make test` afterwards or a completely different set of commands?
