### ISSUE TITLE
Accessing https://itunes.com using -I produces no output

### ISSUE THREAD

**Issue by fuglede** [curl/curl#1020]
### I did this

After coming across https://github.com/EFForg/https-everywhere/pull/6878, tried to check the headers of https://itunes.com and got the following:

    $ curl -I https://itunes.com
    curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

On the other hand, accessing the site using `curl -v https://itunes.com` results in the headers being listed. It's frankly not clear to me if this is an issue with curl or with the servers implementation of HEAD respones, but I figured I'd post it here to be on the safe side.

### I expected the following

The headers that the site apparently does manage to serve on ordinary GET requests.

### curl/libcurl version

    curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

### operating system

Debian Jessie.

**Comment by jay** [comment]
Thanks for your report but it's the server, it disconnects on HEAD. i have the same result using GnuTLS, mbedTLS, OpenSSL, WinSSL and wolfSSL. Sometimes it can be a missing header however I tried dressing it up browser style and that didn't work either. It's possible there is some magic apple header that it will not disconnect on HEAD, but that's beyond the scope here.

**Comment by fuglede** [comment]
Great, thanks for looking into it!
