### ISSUE TITLE
filename_effective didn't get from url_effective

### ISSUE THREAD

**Issue by walkerxk** [curl/curl#10216]
### I did this
curl -w '%{filename_effective} %{url_effective}\n' -sLO https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public%2Fbuild%2Farm64-v8a%2Ftarget.apk
public%2Fbuild%2Farm64-v8a%2Ftarget.apk https://firefoxci.taskcluster-artifacts.net/WF-7PAoJSW-puKRMnXaYhQ/0/public/build/arm64-v8a/target.apk

### I expected the following
target.apk https://firefoxci.taskcluster-artifacts.net/WF-7PAoJSW-puKRMnXaYhQ/0/public/build/arm64-v8a/target.apk
### curl/libcurl version

curl 7.87.1-DEV (x86_64-pc-linux-gnu) libcurl/7.87.1-DEV OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9

### operating system

Linux vm10-65-248-109 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
The man page for `-O`  says "The remote file name to use for saving is extracted from the given URL, nothing else"

The file name in your given URL is `public%2Fbuild%2Farm64-v8a%2Ftarget.apk`.

The man page for `%{filename_effective}` says : "The ultimate filename that curl writes out to", which seems to match as well.

You seem to rather want or expect `-O` to work differently than it is.

**Comment by walkerxk** [comment]
but https://firefoxci.taskcluster-artifacts.net/WF-7PAoJSW-puKRMnXaYhQ/0/public/build/arm64-v8a/target.apk is given by sever, i can't foreknow the url, and webbrowser like firefox and chrome use target.apk as download filename

**Comment by walkerxk** [comment]
w3m links works too

**Comment by bagder** [comment]
That is irrelevant. curl's `-O` option is documented to work in a specific way and then users will expect it to work like that.

You want it to work slightly different, and while you are not the first to ask this we cannot change `-O` to do this without breaking existing use cases.

We have previously discussed extending the `-J` for this purpose but nobody has yet made any serious attempt to my knowledge.

**Comment by walkerxk** [comment]
> That is irrelevant. curl's `-O` option is documented to work in a specific way and then users will expect it to work like that.
> 
> You want it to work slightly different, and while you are not the first to ask this we cannot change `-O` to do this without breaking existing use cases.
> 
> We have previously discussed extending the `-J` for this purpose but nobody has yet made any serious attempt to my knowledge.

thank you very much.
