### ISSUE TITLE
Doc: Can CURLOPT_PINNEDPUBLICKEY also pin intermediate/root certifiates?

### ISSUE THREAD

**Issue by rugk** [curl/curl#1022]
In the [documentation](https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html#PUBLIC) it is not clear whether CURLOPT_PINNEDPUBLICKEY can also pin intermediate/root certificates just like HPKP can.

I think clarifying this would be a good idea.

**Comment by jay** [comment]
Seems pretty clear:
> When negotiating a TLS or SSL connection, the server sends a certificate indicating its identity. A public key is extracted from this certificate and if it does not exactly match the public key provided to this option, curl will abort the connection before sending or receiving any data.

**Comment by rugk** [comment]
Well... it is not clear. Because actually most servers send at least two certificates: an intermediate and a leaf.
So which one is cURL using to check the identity? And is it also checking the root certificate here?

**Comment by jay** [comment]
It's checking the server certificate as it says,

> the server sends a certificate indicating its identity

I don't understand how that's unclear but I'll leave this open for other feedback.

**Comment by rugk** [comment]
Well... how would you interpret it? I mean when there is not only **one** (an) certificate send by the server, what happens?

**Comment by jay** [comment]
I interpret it exactly as its written. Those other certificates don't indicate the server's identity, they are intermediates sent to complete the chain. But I appreciate what you're saying and like I said I'll leave this open for a bit and others can weigh in.

**Comment by bagder** [comment]
Also, to be really strict and clear here: it doesn't pin the certificate at all - any of the certificates. It pins the public key the server provides. [public key pinning description here](https://developer.mozilla.org/en/docs/Web/Security/Public_Key_Pinning)

**Comment by bagder** [comment]
I consider this case resolved. I think it spells out rather clearly what it does.
