### ISSUE TITLE
quic ngtcp2 not call CURLOPT_SSL_CTX_FUNCTION

### ISSUE THREAD

**Issue by violetlige** [curl/curl#10222]
### Package:
curl 7.87.0

### File:
lib/vquic/ngtcp2.c 

maybe should add this code in function 'Curl_quic_connect' (after quic_ssl_ctx)

> because at mobile, verify cert through SSL_CTX_set_cert_verify_callback in CURLOPT_SSL_CTX_FUNCTION callback

```c
if(data->set.ssl.fsslctx) {
    Curl_set_in_callback(data, true);
    result = (*data->set.ssl.fsslctx)(data, qs->sslctx,
                                      data->set.ssl.fsslctxp);
    Curl_set_in_callback(data, false);
    if(result) {
      failf(data, "error signaled by ssl ctx callback");
      return result;
    }
  }
```
and maybe should set SSL_VERIFY_PEER like this in function 'quic_ssl_ctx' (wolfssl and so on)
> because at mobile, not config ssl_cafile and ssl_capath, verify cert through SSL_CTX_set_cert_verify_callback in CURLOPT_SSL_CTX_FUNCTION callback
```c
  if(conn->ssl_config.verifypeer) {
    SSL_CTX_set_verify(ssl_ctx, SSL_VERIFY_PEER, NULL);

    const char * const ssl_cafile = conn->ssl_config.CAfile;
    const char * const ssl_capath = conn->ssl_config.CApath;
    if(ssl_cafile || ssl_capath) {
    .......
}
```

**Comment by icing** [comment]
This sounds like a very good idea!

**Comment by icing** [comment]
Addressed the ctx callback in #10239.

Could you explain what you mean by the verify peer suggestion? I see support for this in the code, must be missing something. Thanks.

**Comment by violetlige** [comment]
> Addressed the ctx callback in #10239.
> 
> Could you explain what you mean by the verify peer suggestion? I see support for this in the code, must be missing something. Thanks.

@icing thank you for your quick response.

Because in my project(mobile products), i don't config STRING_SSL_CAPATH and STRING_SSL_CAFILE,
otherwise I use SSL_CTX_set_cert_verify_callback(through CURLOPT_SSL_CTX_FUNCTION callback to get ssl_ctx) 
to verify server peer tls cert.In this way I can use system api(like 'SecTrust' api on ios) to verify server cert, and also
i can provide callback for others(who use my product) to verify server tls certs.

**but in lib/vquic/ngtcp.c** 
if i not config STRING_SSL_CAPATH and STRING_SSL_CAFILE,  SSL_VERIFY_PEER is not set.
https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vquic/ngtcp2.c#L273-L301

**and in lib/vtls/openssl.c** 
SSL_VERIFY_PEER is only controlled by the verifypeer parameter(CURLOPT_SSL_VERIFYPEER)
https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L3780-L3785

and SSL_VERIFY_PEER is not binding with STRING_SSL_CAPATH and STRING_SSL_CAFILE
https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L3258-L3287

so I think the code logic of openssl and ngtcp about SSL_VERIFY_PEER should be consistent。

**Comment by icing** [comment]
Understood, thanks for the explanation. I updated #10239 so that openssl setup works the same in ngtcp2 and plain TLS. This allows also the shared X509_STORE feature to work here.

**Comment by icing** [comment]
@violetlige if this PR does what you expect, we'll merge it and close this ticket. WDYT?

**Comment by violetlige** [comment]
> @violetlige if this PR does what you expect, we'll merge it and close this ticket. WDYT?

@icing that is exactly what I expect, thank you very much for your quick processing.
