### ISSUE TITLE
After installing curl with vcpkg, find_package could not find the Config file

### ISSUE THREAD

**Issue by msclock** [curl/curl#10229]
Please see the pull request about curl https://github.com/microsoft/vcpkg/pull/28717

**Comment by bagder** [comment]
That sounds entirely like a vcpkg issue. A project separate and independent from this. It does not appear to be a curl issue.

**Comment by msclock** [comment]
> That sounds entirely like a vcpkg issue. A project separate and independent from this. It does not appear to be a curl issue.

Config files do conform to the case-insensitive lookup rules. Maybe vcpkg has some Config renaming problems when installing cmake scripts.
https://github.com/curl/curl/blob/24e4e57cf33d00e4ca8654a795ef7916d6e6ea04/CMakeLists.txt#L1618

**Comment by bagder** [comment]
Can you please explain how this is a curl issue?

**Comment by msclock** [comment]
> > That sounds entirely like a vcpkg issue. A project separate and independent from this. It does not appear to be a curl issue.
> 
> Config files do conform to the case-insensitive lookup rules. Maybe vcpkg has some Config renaming problems when installing cmake scripts.
> 
> https://github.com/curl/curl/blob/24e4e57cf33d00e4ca8654a795ef7916d6e6ea04/CMakeLists.txt#L1618

@bagder 
I tried to clone and build the installation, and the resulting Config file did not conform to the target ignore case lookup rule **target-config.cmake**. 
Here are some of the logs:
```
[build] -- Installing: /usr/local/include/curl/curl.h
[build] -- Installing: /usr/local/include/curl/urlapi.h
[build] -- Installing: /usr/local/include/curl/mprintf.h
[build] -- Installing: /usr/local/include/curl/stdcheaders.h
[build] -- Installing: /usr/local/include/curl/options.h
[build] -- Installing: /usr/local/include/curl/easy.h
[build] -- Installing: /usr/local/include/curl/header.h
[build] -- Installing: /usr/local/include/curl/curlver.h
[build] -- Installing: /usr/local/include/curl/system.h
[build] -- Installing: /usr/local/include/curl/websockets.h
[build] -- Installing: /usr/local/lib/cmake/CURL/CURLTargets.cmake
[build] -- Installing: /usr/local/lib/cmake/CURL/CURLTargets-debug.cmake
[build] -- Installing: /usr/local/lib/cmake/CURL/CURLConfigVersion.cmake
[build] -- Installing: /usr/local/lib/cmake/CURL/CURLConfig.cmake
[build] Build finished with exit code 0
```
Sorry, I just found the wrong place. The Config is configured here.
https://github.com/curl/curl/blob/24e4e57cf33d00e4ca8654a795ef7916d6e6ea04/CMakeLists.txt#L71
https://github.com/curl/curl/blob/24e4e57cf33d00e4ca8654a795ef7916d6e6ea04/CMakeLists.txt#L1391-L1395
The project configuration CRUL is uppercase, which causes the config generation to only look for CURLConfig.cmake. 
However, in order to avoid linux case sensitivity, cmake provides a fixed lowercase Config file naming lookup. 
Please check the https://cmake.org/cmake/help/v3.24/command/find_package.html#search-procedure. 

> Config mode
In this mode, CMake searches for a file called `<lowercasePackageName>-config.cmake` or `<PackageName>Config.cmake`. It will also look for `<lowercasePackageName>-config-version.cmake` or `<PackageName>ConfigVersion.cmake` if version details were specified (see [Config Mode Version Selection](https://cmake.org/cmake/help/v3.24/command/find_package.html#version-selection) for an explanation of how these separate version files are used).
>
>In config mode, the command can be given a list of names to search for as package names. The locations where CMake searches for the config and version files is considerably more complicated than for Module mode (see [Config Mode Search Procedure](https://cmake.org/cmake/help/v3.24/command/find_package.html#search-procedure)).

So the best practice is to use **target-config.cmake**

**Comment by Neumann-A** [comment]
> That sounds entirely like a vcpkg issue. A project separate and independent from this. It does not appear to be a curl issue.

no its not. 

> did not conform to the target ignore case lookup rule

there is no cmake convention forcing this. 

> So the best practice is to use target-config.cmake

Ah I see, a case of personal opinion. It is not best practice it is a personal/project choice. I also find `target-config.cmake` slightly better since case doesn't matter anymore and all of `curl` `CuRl` `CURL` `Curl` would work in `find_package`. This  gives a slightly better UX since the user doesn't need to care about case which thus allows an easier downstream use of the config.
