### ISSUE TITLE
libcurl.dll fails to load due to missing libeay32.dll

### ISSUE THREAD

**Issue by zhangyong0538** [curl/curl#1023]
### I did this
I build it with VS2012 Tools

### I expected the following
I expected get the x86 and x64 dll files

### curl/libcurl version
I build with the command "nmake /f Makefile.vc mode=dll vc=11 WITH_DEVEL=e:\\deps WITH_SSL=dll WITH_ZLIB=dll WITH_SSH2=dll MACHINE=x86"

### operating system
operating system is Win7 x64

**Comment by jay** [comment]
libeay32.dll and ssleay32.dll must be in your path or in the directory with libcurl.dll

**Comment by zhangyong0538** [comment]
I'm sorry I have just described the problem clearly just now.It did not work by the way you said just now. It
noticed the error "The ordinal 4445 could not be located in dynamic link library: libeay32.dll"

**Comment by bagder** [comment]
Is this a dupe of #984 perhaps?

**Comment by jay** [comment]
> Is this a dupe of #984 perhaps?

Doubt it. Now it sounds like a libeay32.dll other than the one he built with is being loaded. @zhangyong0538 go into the e:\deps and find the ssl DLLs and put them in the same directory as the libcurl.dll.

**Comment by zhangyong0538** [comment]
@jay .It is.Thanks very much.
