### ISSUE TITLE
Is the directory "deps-5.6-vc11-x86.7z" effective for the curl-7.50.3?

### ISSUE THREAD

**Issue by zhangyong0538** [curl/curl#1024]
Is the file "deps-5.6-vc11-x86.7z" effective for the curl-7.50.3 which I got from "http://windows.php.net/downloads/php-sdk/"?
I cann't build windows Lib or dll file,I doubt that if the file be used rightly.

**Comment by bagder** [comment]
1. That deps file is not something the curl project distributes
2. That curl download package you downloaded is not provided by the curl project so I have no idea if it needs or uses that deps file.
3. This is an issue tracker, not a support forum for asking questions. We have mailing lists for that.
