### ISSUE TITLE
Documentation for curl_mime_init() states curl_mime_free() called after curl_easy_cleanup() - correct?

### ISSUE THREAD

**Issue by egtvedt** [curl/curl#10254]
Looking at the documentation https://curl.se/libcurl/c/curl_mime_init.html, I see the code example will do
```
 CURL *easy = curl_easy_init();
...
 mime = curl_mime_init(easy);
...
 /* Clean-up. */
 curl_easy_cleanup(easy);
 curl_mime_free(mime);
```
I think it looks weird to call curl_easy_cleanup() before curl_mime_free(), is this mandatory? Or can the order be reversed, so you free in the reverse order of init?

Example
```
 CURL *easy = curl_easy_init();
...
 mime = curl_mime_init(easy);
...
 /* Clean-up. */
 curl_mime_free(mime);
 curl_easy_cleanup(easy);
```

This will allow goto label upon error to common free easy to implement.

**Comment by bagder** [comment]
First: that's an example, it doesn't say that's the mandatory sequence.

But in my mind, we hand over the mime pointer to the easy handle for use, so as long as the easy pointer is around then it has some reference left to the mime object. Then if I remove the mime object before the easy object, it feels like we risk having the easy pointer refer to an already freed object. So I figured this order of cleanup makes sense.

**Comment by egtvedt** [comment]
> First: that's an example, it doesn't say that's the mandatory sequence.
> 
> But in my mind, we hand over the mime pointer to the easy handle for use, so as long as the easy pointer is around then it has some reference left to the mime object. Then if I remove the mime object before the easy object, it feels like we risk having the easy pointer refer to an already freed object. So I figured this order of cleanup makes sense.

Ack, thank you for explaining, will stick to the order in documentation. Can check for nullptr on the way out when cleaning.
