### ISSUE TITLE
libcurl 7.87 is crashing in send_callback 

### ISSUE THREAD

**Issue by Abdul-test** [curl/curl#10282]
There is no issue with older release i.e., libcurl version 7.86. Only issue (SIGSEGV: segmentation fault signal 11) happens with newer release version libcurl version 7.87 during the de-initialize the AVS SDK Sample App. You can also refer to attached files herewith 'backtrace_curl_7.87.txt' and 'deinitialization_Sample_App.txt'.    

*** backtrace ***
#0  0xb5033634 in ossl_trace () from target:/lib/libcurl.so.4
#1  0xb6b6e7ec in do_ssl3_write.localalias () from target:/lib/libssl.so.1.1
#2  0xb6b6ec70 in ssl3_write_bytes () from target:/lib/libssl.so.1.1
#3  0xb6b756d0 in ssl3_write () from target:/lib/libssl.so.1.1
#4  0xb6b7f170 in SSL_write () from target:/lib/libssl.so.1.1
#5  0xb503254c in ossl_send () from target:/lib/libcurl.so.4
#6  0xb5036c3c in ssl_cf_send () from target:/lib/libcurl.so.4
#7  0xb500e550 in send_callback () from target:/lib/libcurl.so.4
#8  0xb6dc122c in nghttp2_session_send (session=0xaf6b6a50) at nghttp2_session.c:3213
#9  0xb50103f0 in Curl_http2_done () from target:/lib/libcurl.so.4
#10 0xb5009818 in Curl_http_done () from target:/lib/libcurl.so.4
#11 0xb501a6a4 in multi_done () from target:/lib/libcurl.so.4
#12 0xb501ad9c in curl_multi_remove_handle () from target:/lib/libcurl.so.4

# curl --version
curl 7.87.0 (arm-buildroot-linux-gnueabihf) libcurl/7.87.0 OpenSSL/1.1.1s nghttp2/1.29.0
Release-Date: 2022-12-21
Protocols: ftp ftps http https mqtt
Features: alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

# uname -a
Linux ak945897 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[backtrace_curl_7.87.txt](https://github.com/curl/curl/files/10397437/backtrace_curl_7.87.txt)
[deinitialization_Sample_App.txt](https://github.com/curl/curl/files/10397440/deinitialization_Sample_App.txt)

**Comment by bagder** [comment]
Any chance you can try a libcurl from git master to see if this is fixed already?

**Comment by Abdul-test** [comment]
Didn't observe the issue with the libcurl from git master.

**Comment by bagder** [comment]
Thanks, I suspect f39472ea9f4f fixed this issue.

**Comment by Abdul-test** [comment]
You are right, I created a 'openssl-remove-attached-easy-handles-from-SSL-instan.patch' using the fix https://github.com/curl/curl/commit/f39472ea9f4f4e12cfbc0500c4580a8d52ce4a59. then, applied to curl-v7.87 release and verified. All is good. Thanks.

**Comment by bagder** [comment]
Awesome, thanks for confirming!

**Comment by Abdul-test** [comment]
Thank you Daniel.
