### ISSUE TITLE
OS400 compiling a C++ program with the include curl.h fails.

### ISSUE THREAD

**Issue by johnsherrill** [curl/curl#10305]
The include curl.h includes systems.h
systems.h has this section for OS400

~~~c
#elif defined(__OS400__)
#  if defined(__ILEC400__)
#    define CURL_TYPEOF_CURL_OFF_T     long long
#    define CURL_FORMAT_CURL_OFF_T     "lld"
#    define CURL_FORMAT_CURL_OFF_TU    "llu"
#    define CURL_SUFFIX_CURL_OFF_T     LL
#    define CURL_SUFFIX_CURL_OFF_TU    ULL
#    define CURL_TYPEOF_CURL_SOCKLEN_T socklen_t
#    define CURL_PULL_SYS_TYPES_H      1
#    define CURL_PULL_SYS_SOCKET_H     1
#  endif           
~~~

`__ILEC400__` is only defined if using the C compiler 
If you what to  use curl in C++ code the compile fails 
since `CURL_TYPEOF_CURL_OFF_T` is not defined so the below code is not used

~~~c
/* Data type definition of curl_off_t. */

#ifdef CURL_TYPEOF_CURL_OFF_T
  typedef CURL_TYPEOF_CURL_OFF_T curl_off_t;
#endif                           
~~~
which causes errors in curl.h since curl_off_t is not defined.

adding || (__cplusplus) to the "#if defined(__ILEC400) line fixes the problem.

**Comment by jay** [comment]
> adding || (__cplusplus) to the "#if defined(__ILEC400) line fixes the problem.

@jonrumsey does this seem right to you?

**Comment by johnsherrill** [comment]
I can state with __cplusplus  added I can compile C++ that includes curl.h. Without it fails with curl_off_t not defined.

**Comment by jonrumsey** [comment]
Yes, `#if defined(__ILEC400__) || defined(__cplusplus)` would define those types for both C & C++ compilers, however you'll only be including the systems.h header when compiling a C/C++ module so just removing the check for `__ILEC400__` and leaving this under the `__OS400__` check is equally valid and perhaps a little clearer.

**Comment by johnsherrill** [comment]
I agree that would be cleaner.
