### ISSUE TITLE
mbedTLS PKCS#1 verification failed

### ISSUE THREAD

**Issue by adnan-kamili** [curl/curl#10301]
### The issue is specific to Ubuntu 22.04 and doesn't replicate on older versions of Ubuntu

The network request fails with the following error log:

```
Trying 35.71.***.**:443…
Connected to [api.***.com](http://api.***.com/) (35.71.***.**) port 443 (#0)
mbedTLS: Connecting to [api.***.com:443](http://api.***.com:443/)
mbedTLS: Set min SSL version to TLS 1.0
ALPN: offers h2
ALPN: offers http/1.1
ssl_handshake returned - mbedTLS: (-0x4380) RSA - The PKCS#1 verification failed
Closing connection 0
```

### libcurl version

libcurl v7.85.0

### operating system

Ubuntu 22.04

**Comment by jay** [comment]
Try running the command with `--verbose`. What's your `curl -V` ? Is it a packaged version of curl or one that you built? Can you give us a minimal self contained example that we can use to reproduce?

**Comment by bagder** [comment]
No response in two weeks.
