### ISSUE TITLE
IMAP APPEND example is wrong

### ISSUE THREAD

**Issue by bohwaz** [curl/curl#10300]
The [IMAP APPEND example](https://curl.se/libcurl/c/imap-append.html) has this part:

```
    /* This will create a new message 100. Note that you should perform an
     * EXAMINE command to obtain the UID of the next message to create and a
     * SELECT to ensure you are creating the message in the OUTBOX. */
    curl_easy_setopt(curl, CURLOPT_URL, "imap://imap.example.com/100");
```

But it is wrong:

1. you don't need to pass the message UID to do an APPEND, but you need to pass the folder name, so the URL should be `imap://imap.example.com/Sent`. In fact there is no UID used in the `imap_perform_append` function
2. Curl is already doing a SELECT in its append function, so there is no need to do a SELECT

This can lead to some confusion when the example is wrong :)

Thanks!

**Comment by jay** [comment]
Is this true of IMAP protocol or just the server you are using?

/cc @captain-caveman2k

**Comment by bagder** [comment]
No response, closing.

**Comment by bohwaz** [comment]
You didn't give me enough time to reply @bagder :)

@jay This is not related to the IMAP protocol, this is what the curl code is doing. Curl IMAP code for APPEND is never using the UID: https://github.com/curl/curl/blob/master/lib/imap.c#L763-L826

Everything is in my original message :)

**Comment by bagder** [comment]
okay @bohwaz so can you please tell us what you think the fix is? Perhaps with a PR for the example?

**Comment by bohwaz** [comment]
Hi @badger yes :)

The mentioned lines should be replace by this:

```
    /* This will create a new message in folder "Sent". */
    curl_easy_setopt(curl, CURLOPT_URL, "imap://imap.example.com/Sent");
```
