### ISSUE TITLE
Formatted String

### ISSUE THREAD

**Issue by xmha97** [curl/curl#10323]
# Description

In the `.cmd`/`.bat` script files on Windows, the --write-out option does not work and we have to use two percent signs (%%) instead of one percent signs (%) in the formatted string.

For example, the following command does not work:
```
curl --url "http://cachefly.cachefly.net/1mb.test" -qfsS --write-out "%{speed_download}\n" -o NUL
```

But this command works:
```
curl --url "http://cachefly.cachefly.net/1mb.test" -qfsS --write-out "%%{speed_download}\n" -o NUL
```

Please mention this point in this article because my friend thought that the Windows build of cURL has a problem:
https://everything.curl.dev/usingcurl/verbose/writeout
Thanks.

# What is the cause of this problem?

Actually, there is no problem. Command Prompt variables comprise a % character followed by a name, for example:
```
FOR /f %f in ('dir /b .') DO ECHO %f
```

**Comment by jay** [comment]
> In the `.cmd`/`.bat` script files on Windows, the --write-out option does not work and we have to use two percent signs (%%) instead of one percent signs (%) in the formatted string.

The manual [says](https://curl.se/docs/manpage.html#-w):

> **NOTE:** The %-symbol is a special symbol in the win32-environment, where all occurrences of % must be doubled when using this option.

The book [says](https://everything.curl.dev/usingcurl/verbose/writeout):

> (The %-symbol is special on the Windows command line, where all occurrences of % must be doubled when using this option.)

I think we could make it clearer though. The escaping is needed for batch files but cannot be done if the command is typed at the prompt. I've submitted two PRs, one for the book and one for manpage.

https://github.com/curl/curl/pull/10337
https://github.com/bagder/everything-curl/pull/279
