### ISSUE TITLE
Release tarballs and CurlSymbolHiding

### ISSUE THREAD

**Issue by verybigbadboy** [curl/curl#1032]
steps:
1. I downloaded latest source tarball from https://curl.haxx.se/download.html.
2. I tried to build it using cmake

result:
cmake fails because of "include(CurlSymbolHiding)"

reason:
CurlSymbolHiding file is missing in cmake directory.

**Comment by bagder** [comment]
Thanks for reporting!

I just  fixed this in commit 82279c82c8d. You can also fix your local copy by downloading it from [here](https://raw.githubusercontent.com/curl/curl/master/CMake/CurlSymbolHiding.cmake) and put it in your CMake subdir in the curl source tree.

Or you can download the next daily tarball  that is generated at https://curl.haxx.se/snapshots/
