### ISSUE TITLE
cacert.pem file download has been moved behind HTTPS

### ISSUE THREAD

**Issue by numair** [curl/curl#10324]
Hi, this is a repost of #644 -- the curl website once again prevents downloading of the cert package over HTTP. Since the other issue is locked, is this a WONTFIX? Thank you!

**Comment by jay** [comment]
There are no plans to make the CA bundle available cleartext HTTP.

**Comment by dfandrich** [comment]
If there's an issue in bootstrapping, you can use the -k flag to get it over HTTPS.
