### ISSUE TITLE
CURLOPT_READFUNCTION documentation return value confuses bytes with objects

### ISSUE THREAD

**Issue by briangreenery** [curl/curl#10328]
### I did this

I read the documentation at https://curl.se/libcurl/c/CURLOPT_READFUNCTION.html.

### I expected the following

I expected to understand if the return value should be the number of _bytes_ read, like the return value of [read](https://pubs.opengroup.org/onlinepubs/9699919799/functions/read.html), or the number of _objects_ read, like the return value of [fread](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html).

This is confusing because the documentation is not consistent with itself.

First, it says the return value should be the the number of bytes read:

https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/docs/libcurl/opts/CURLOPT_READFUNCTION.3#L47-L49

However the example it provides uses `fread`, which returns the number of objects read:

https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/docs/libcurl/opts/CURLOPT_READFUNCTION.3#L88

If the return value is indeed `bytes`, then it seems the example should instead be something like:

```C
    size_t retcode = fread(ptr, 1, size*nmemb, readhere); 
```

Scanning through the codebase, it looks like one of those arguments is always `1`, so in practice the difference might not matter. If that's the case, explicitly saying that the `size` argument is always `1` would also be helpful to make it less ambiguous.

**Comment by briangreenery** [comment]
I went back and forth on whether this was a bug in the documentation, or something I should discuss on the mailing list. If this is the wrong place, I can move this over to the mailing list 🙇

**Comment by jay** [comment]
Internally we always call those callbacks with an element size of 1. We have already documented this for CURLOPT_WRITEFUNCTION and I can't think of a reason why we couldn't do the same for CURLOPT_READFUNCTION.

**Comment by bagder** [comment]
Agreed. Adding this to the docs would be good.

**Comment by briangreenery** [comment]
Thank you!

**Comment by thcrt** [comment]
@bagder Sorry for necro'ing this old issue, but this is one of the only search results I could find: why is it that `size` is always `1`? Why pass it at all then?

**Comment by dfandrich** [comment]
For compatibility with fwrite(3).
