### ISSUE TITLE
Hi, team, I have a question please, could you give a callback function for the async communication to connect the proxy tunnel?

### ISSUE THREAD

**Issue by TheBetterSolution** [curl/curl#10330]
### I did this
Hi, team, I have a question please, I make a proxy tunnel connection and then communicate to target server from this tunnel asynchronously, but I can't find any callback function or the API to get current tunnel connection status.

curl version 7.87.0 works asynchronously:
static CURLcode recv_CONNECT_resp(struct Curl_easy *data,
                                  struct connectdata *conn,
                                  struct tunnel_state *ts,
                                  bool *done)
{
   ...
  while(ts->keepon) {
    ssize_t gotbytes;
    char byte;
    ...
    result = Curl_read(data, tunnelsocket, &byte, 1, &gotbytes);
    if(result == CURLE_AGAIN)
      /* socket buffer drained, return */
      return CURLE_OK;
   ...
}

My code need to work asynchronously, So I should call curl_multi_socket_action function multiple times until the connection is done, but I can't find any callback function and any query function (I try to get the connection code by CURLINFO_HTTP_CONNECTCODE) to get the tunnel connection status and then call curl_multi_socket_action again.

Could you provide a callback function or the targeted API to get the tunnel connection status?

Thanks!

### I expected the following
Tunnel connection status can be notified by callback function or curl provide good API to get it.

### curl/libcurl version
7.87.0

[curl -V output]
libcurl/7.87.0 OpenSSL/1.0.2 zlib/1.2.13

### operating system
Windows 11 AMD64

**Comment by dfandrich** [comment]
curl uses nonblocking sockets internally, so it's all asynchronous internally.
Are you trying to do a special protocol over the tunnel? If not, then just
fire and forget—let libcurl do the transfer and don't worry about when it's
happening. If you're doing a special protocol over the tunnel yourself, then
you should be using CURLOPT_CONNECT_ONLY in which case you'll get notification
when the connection has been made.

**Comment by TheBetterSolution** [comment]
Hi dfandrich, Thanks for your response, I have a question for the return value please:
I think the return value should be CURLM_CALL_MULTI_PERFORM when the tunnle connection have not done, but I got CURLM_OK, so I don't know whether or not to continue to connect.

And I have not found the example of ssl tunnel and curl_multi_socket_action work together in curl source code, could you please provide an example for this requirement? I think that's a very common requirement.

Thanks!

**Comment by dfandrich** [comment]
I'm pretty sure you perform a normal transfer through the multi interface,
then when the connection "completes", you can start using the send/recv
functions on the easy handle as normal. I don't think there's anything special
that needs to happen, but I'm not an expert on the multi interface.

**Comment by jay** [comment]
> And I have not found the example of ssl tunnel and curl_multi_socket_action work together in curl source code, could you please provide an example for this requirement? I think that's a very common requirement.

If you use [CURLOPT_CONNECT_ONLY](https://curl.se/libcurl/c/CURLOPT_CONNECT_ONLY.html) then once connected libcurl stops performing on the easy handle, it's done. If the multi API is used then after the connection is established the easy handle is marked as done and [curl_multi_info_read](https://curl.se/libcurl/c/curl_multi_info_read.html) will return the easy handle with CURLMSG_DONE. At that point you can `curl_easy_getinfo(m->easy_handle, CURLINFO_ACTIVESOCKET, &sockfd);` and use select, curl_easy_send, curl_easy_recv.

Connect-only easy handles in a multi handle is _not_ a "very common requirement" and I don't think we should offer an example.

Also, from CURLOPT_CONNECT_ONLY doc:

_"If the connect only transfer is done using the multi interface, the particular easy handle must remain added to the multi handle for as long as the application wants to use it."_

**Comment by jay** [comment]
Unless there is more information (maybe we misunderstood the situation?) I'm going to close this. The only other thing I can think of is [CURLOPT_PREREQFUNCTION](https://curl.se/libcurl/c/CURLOPT_PREREQFUNCTION.html) but there's no point in using that unless libcurl is going to handle the transfer after the connection is made. example:

~~~c
int prereq_callback(void *clientp,
                    char *conn_primary_ip, char *conn_local_ip,
                    int conn_primary_port, int conn_local_port)
{
  CURL *curl = (CURL *)clientp;
  long code = 0;
  CURLcode cc = curl_easy_getinfo(curl, CURLINFO_HTTP_CONNECTCODE, &code);
~~~

**Comment by TheBetterSolution** [comment]
Hi jay, thanks very much for your response, I understand.

My old code processes the return value CURLM_CALL_MULTI_PERFORM, I will change my code according to current version of curl.

I will close this issue.
