### ISSUE TITLE
Option «-r, --range <range>» – wrong documentation(?)

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10338]
### I did this
Citation from the cURL's manual:
«       -r, --range <range>
              (HTTP FTP SFTP FILE) Retrieve a byte range (i.e. a partial docu-
              ment) from an HTTP/1.1, FTP or SFTP  server  or  a  local  FILE.»

Oll korrect, version «1.1» ONLY.

`curl.exe --http1.0 -i -r -1 "https://curl.se/windows/dl-7.87.0_2/curl-7.87.0_2-win64-mingw.zip"`
HTTP/1.1 206 Partial Content
…

`curl.exe --http2 -i -r -1 "https://curl.se/windows/dl-7.87.0_2/curl-7.87.0_2-win64-mingw.zip"`
HTTP/2 206
…

`curl.exe --http3 -i -r -1 "https://curl.se/windows/dl-7.87.0_2/curl-7.87.0_2-win64-mingw.zip"`
HTTP/3 206
…
### I expected the following
«HTTP/1.1 206 Partial Content» in EACH case.
### curl/libcurl version

[curl -V output]
curl 7.87.0 (x86_64-w64-mingw32) libcurl/7.87.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.12.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
Windows 10 last version with all updates

**Comment by jay** [comment]
I'm not sure what you are reporting, can you explain further? HTTP/2 & 3 do not have status text so that is the expected output AFAICS.

**Comment by u20221022** [comment]
It seems to me that the documentation is ambiguous. She is misleading.

**Comment by dfandrich** [comment]
What's ambiguous? That snippet you provided? I don't see the ambiguity.

**Comment by bagder** [comment]
No response
