### ISSUE TITLE
curl do not ask password for pkcs12 files

### ISSUE THREAD

**Issue by dab18** [curl/curl#1034]
curl --cert-type P12 --cert my.p12 https://blablabla/...
"could not parse PKCS12 file, check password, OpenSSL error error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure".

I expected the following: valid server response.

curl 7.50.3 (i686-pc-linux-gnu) libcurl/7.50.3 OpenSSL/1.0.2h zlib/1.2.8 nghttp2/1.10.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS Largefile NTLM SSL libz TLS-SRP HTTP2 UnixSockets 

OS: Gentoo Base System release 2.2

#919

**Comment by bagder** [comment]
So this is just an issue for the exact same issue there's that pull request for?

**Comment by bagder** [comment]
Already being worked on in #919
