### ISSUE TITLE
Some potential error handling bugs

### ISSUE THREAD

**Issue by HaoranLiu14** [curl/curl#10350]
While reading the code, I found several potential error handling bugs.

In the function read_data, curl_saferealloc is called without checking its return value. In the functions init_fifo and clean_fifo, epoll_ctl is called without checking its return value.

They are currently not in danger of triggering an error, but there is still a risk that their error be triggered as the code is updated. Will you consider adding error handling for them in a future update?

**Comment by bagder** [comment]
> In the function read_data, curl_saferealloc is called without checking its return value

What version are you checking? The current code checks the return value.

> In the functions init_fifo and clean_fifo, epoll_ctl is called without checking its return value.

Those are in *examples* aren't they? We take some liberties of not doing complete error checks in examples in the name of keeping them simpler.

**Comment by HaoranLiu14** [comment]
> In the function read_data, curl_saferealloc is called without checking its return value
I just checked and I had mistaken a historical release for the latest one, my bad.
> We take some liberties of not doing complete error checks in examples in the name of keeping them simpler.
I understand, thanks!

**Comment by HaoranLiu14** [comment]
I found several more potential error handling bugs.

curl_easy_perform is called without checking its return value in the following functions : pull_one_url, run_one, SyncTime_CURL_Fetch, run_thread, test_cert_blob, send_request, and test_connect

curl_easy_init  is called without checking its return value in the following functions : add_transfer, make_handle, setup, add_download, pull_one_url, sftpGetRemoteFileSize, and run_thread.

malloc or calloc is called without checking its return value in the following functions : make_handle, init_memory, create_curl_context, addsock, new_conn.

These codes are similar to the codes we discussed last time, and I noticed that some of them have been fixed in your latest release. I also understand that some of them were intentionally removed for the purpose of simplifying your code. But I'm listing them anyway to help you maintain them in the future.

**Comment by bagder** [comment]
Adding a comment to an issue closed a long time ago is not helpful. If you think this is an issue in a current curl version, then submit a new issue.

Please consider *where* these functions are used before you do this. We are perfectly aware that example code don't do enough return code checks so no need to do blanket warnings for those. Unless you find specific cases where we really need to add them.
