### ISSUE TITLE
Empty CURLOPT_CAINFO_BLOB causes error

### ISSUE THREAD

**Issue by jay** [curl/curl#10351]
### I did this

@pgroke-dt [reported](https://curl.se/mail/lib-2023-01/0070.html) on the mailing list that, for curl 7.87.0 w/ OpenSSL backend, setting CURLOPT_CAINFO_BLOB to an empty string causes an error when peer verification is disabled.

The CA blob import function expects "[one or more certificates](https://curl.se/libcurl/c/CURLOPT_CAINFO_BLOB.html)" and returns an error if no certificate is read:

https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L3077-L3078

In 7.86.0 ossl_connect_step1 calls load_cacert_from_memory directly and ignores the result if peer verification is disabled. Since then, certificate caching support was added in 3c16697e. Now in 7.87.0 ossl_connect_step1 calls Curl_ssl_setup_x509_store which calls load_cacert_from_memory, but does not ignore the result.

### I expected the following

My first impression is this isn't a bug however AFAICT all other SSL backends that support CA blob either skip loading or ignore a bad load when peer verification is disabled.

### curl/libcurl version

curl 7.87.1-DEV (i386-pc-win32) libcurl/7.87.1-DEV OpenSSL/1.1.1s nghttp2/1.50.0

<br>

/cc @gvollant @tlsa @icing

**Comment by bagder** [comment]
Maybe just like this?
~~~diff
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index 31a8bfc4f..aba4f280d 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -3212,11 +3212,11 @@ static CURLcode populate_x509_store(struct Curl_cfilter *cf,
     else
       infof(data, "error importing Windows CA store, continuing anyway");
   }
 #endif
 
-  if(ca_info_blob) {
+  if(ca_info_blob && ca_info_blob->len) {
     result = load_cacert_from_memory(store, ca_info_blob);
     if(result) {
       if(result == CURLE_OUT_OF_MEMORY ||
          (verifypeer && !imported_native_ca)) {
         failf(data, "error importing CA certificate blob");

**Comment by pgroke-dt** [comment]
@bagder this would make setting `CURLOPT_CAINFO_BLOB` to an empty string equivalent to "un-setting" it with a null pointer value. Which is kind-of the opposite of what we want. We want to use `CURLOPT_CAINFO_BLOB` to give a final set of certificates (which may be empty) to curl in a way so that it won't add any default/fallback certificates. If `verifypeer` is off then the request should still succeed, and if `verifypeer` is on then we _want_ it to fail. And from what I could tell, this is exactly what curl 7.86 did.

Also IMO the behavior should be the same regardless of whether `CURLOPT_CAINFO_BLOB` designates an empty string or a non-empty string that doesn't contain any certificates (e.g. all white space or comment lines).

**Comment by bagder** [comment]
Ok, check the updated take.

**Comment by pgroke-dt** [comment]
I don't understand. https://github.com/curl/curl/commit/02f5d0332b1db22992f2934dafad5a8557d04772 and https://github.com/curl/curl/commit/e39532d4e78cc3f716f2fcad3ab7b0394eaf4935 are exactly identical (except that one is based on a newer version of `openssl.c` which has a few unrelated insertions which change the line numbers).

**Comment by bagder** [comment]
You should check #10359, which contains *two* commits now. The second one changes the take.

**Comment by pgroke-dt** [comment]
Thanks. Sorry for looking in the wrong place, the GitHub UI is still confusing to me :)

The new take now changes behavior when an empty BLOB is configured and `verifypeer` is _on_. 7.86 would fail-fast in this case vs. the new code which will attempt to continue with no certificates - and I assume fail later. I'm not saying this is a problem. It will probably lead to different error messages, but that may be OK. OTOH failing fast may be preferable.

**Comment by bagder** [comment]
So you would prefer it to return CURLE_SSL_CACERT_BADFILE immediately if you set verifypeer = ON and a blank CA blob?

**Comment by pgroke-dt** [comment]
I personally think failing fast would be preferable. Also it's what libcurl 7.86 used to do. So I think it may be the better option. But I can live with both :)

**Comment by bagder** [comment]
Fair enough, and since I changed the PR to only do the blob handling if `verifypeer` is set, I just restored the original logic for the error return.

How does the PR #10359 work for you now?

**Comment by pgroke-dt** [comment]
I think that will work well for me.
I also think (hope) it should work well for the zillions of other users of libcurl :)

**Comment by dfandrich** [comment]
The semantics of some setopts changing their behaviour depending on earlier
setopts seems new and fragile to me (except for mutually-exclusive ones like
POST and HTTPGET where the last one wins). Are there any other setopts that
work this way? I thought the order wasn't important, as long as they're all set
before the perform call.
