### ISSUE TITLE
http2-upload.c

### ISSUE THREAD

**Issue by Janeny2013** [curl/curl#10365]
AS FAQ  
5.5 Does CURLOPT_WRITEDATA and CURLOPT_READDATA work on win32 ?

  Yes, but you cannot open a FILE * and pass the pointer to a DLL and have
  that DLL use the FILE * (as the DLL and the client application cannot access
  each others' variable memory areas). If you set CURLOPT_WRITEDATA you must
  also use CURLOPT_WRITEFUNCTION as well to set a function that writes the
  file, even if that simply writes the data to the specified FILE *.
  Similarly, if you use CURLOPT_READDATA you must also specify
  CURLOPT_READFUNCTION.

but we can see that : 
  /* write to this file */
  curl_easy_setopt(hnd, CURLOPT_WRITEDATA, out);    file in docs/examples/http2-upload.c

**Comment by dfandrich** [comment]
Well, that example program might not work in Win32 then. It does have a comment
that says "somewhat unix-specific".

**Comment by bagder** [comment]
I believe this example already does not compile on Windows so then it isn't such a big deal. But sure, if someone feels inclined to fix this little nit then I think we could merge it.

**Comment by bagder** [comment]
If someone wants to improve the example, feel free. I don't think it *has* to be changed and I don't consider this a bug.
