### ISSUE TITLE
Unresolved symbols when static linking ngtcp2,nghttp3,nghttp2 using cmake and MSVC on Windows.

### ISSUE THREAD

**Issue by owent** [curl/curl#10363]
### I did this

+ Building static libraries of https://github.com/quictls/openssl.
+ Building static libraries of ngtcp2,nghttp3 and nghttp2 with openssl with quic above.
+ Uisng cmake to build curl with `cmake -G 'Visual Studio 17 2022' -A x64 '-DUSE_NGTCP2=ON' '-DUSE_NGHTTP2=ON' '-DCMAKE_PREFIX_PATH=<where to install openssl, ngtcp2, ngtcp3, nghttp2>' '-DBUILD_SHARED_LIBS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DBUILD_TESTING=OFF'  '-DCURL_USE_OPENSSL=ON' '-DOPENSSL_ROOT_DIR=<where to install openssl>' ...`.

### I expected the following

Building and install success. but got link error with some unresolved symbols of these libraries and also some system library symbols depended by openssl.

### curl/libcurl version

7.87.0

### operating system

Windows

### Additional

I found nghttp2,nghttp3 and ngtcp2 use `NGHTTP2_STATICLIB` , `NGHTTP3_STATICLIB` and `NGTCP2_STATICLIB` to tell compiler to use static library, but the find script do not check them.

**Comment by bagder** [comment]
Building statically is a game that curl's build scripts cannot keep up with. You need to provide the exact set of dependency libraries since it will likely also vary based on your build choices and over time.

**Comment by bagder** [comment]
I don't see anything to act on here.
