### ISSUE TITLE
Unable to specify locale=C for curl on Windows (running on git bash)

### ISSUE THREAD

**Issue by heckler** [curl/curl#1037]
### I did this

```
$ LC_ALL=pt_BR date
ter, 27 de set de 2016 18:51:59

$ LC_ALL=C date
Tue Sep 27 18:52:13 ESAST 2016

$ LC_ALL=C curl --silent --output /dev/nul --write-out "Total time: %{time_total}\n" google.com
Total time: 0,609
```
### I expected the following

Expected to see a DOT used as the decimal separator when LC_ALL=C, not a comma (which is the separator used in pt_BR)
### curl/libcurl version

```
$ curl -V
curl 7.50.3 (i386-pc-win32) libcurl/7.50.3 OpenSSL/1.1.0b zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.15.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2
```
### operating system

Microsoft Windows [Version 6.3.9600]
Windows number format set to Portuguese/Brazilian (pt_BR)
Git Bash 2.6
### Additional tests

Verified that under Ubuntu Linux curl correctly responds to locale settings: LC_ALL=C forces the use of a DOT as the decimal separator, and LC_ALL=pt_BR forces COMMA.

**Comment by bagder** [comment]
The Linux and windows versions run the same code for this, an sprintf("%.3f") really. It's a mystery to me why the Windows version wouldn't use the locale for this when the Ubuntu one does!

**Comment by jay** [comment]
The curl tool resets the locale from the 'C' default that all C programs start with to the environment's default locale by [calling](https://github.com/curl/curl/blob/curl-7_50_3/src/tool_operate.c#L1840) `setlocale(LC_ALL, "");`. The C standard does not say it has to read from `LC_ALL` or `LANG` environment variables, only that "a value of `""` for locale specifies the implementation-defined native environment". Microsoft's [setlocale](https://msdn.microsoft.com/en-us/library/x99tb11d.aspx) doc says "If locale points to an empty string, the locale is the implementation-defined native environment." Posix mentions the [LC_ environment variables](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html) specifically.

So this is acceptable behavior, unless I missed something. I set the defaults in a Win 7 VM to Portuguese and Brasil and then ran this:
~~~c
int main() {
  fprintf(stderr, "Locale: %s\n", setlocale(LC_ALL, ""));
  fprintf(stderr, "%.3f\n", x);
  fprintf(stderr, "Locale: %s\n", setlocale(LC_ALL, "C"));
  fprintf(stderr, "%.3f\n", x);
}
~~~
and the result, regardless of whether LC_ALL and/or LANG environment variable is set to 'C' beforehand:
~~~
Locale: Portuguese_Brazil.1252
0,609
Locale: C
0.609
~~~

If you build a program that uses setlocale in cygwin then it will use the LANG and LC_ variables. We could change this for Windows builds (other than cygwin) by calling getenv on all LC_ and then setlocale for each. It's possible we could end up breaking something for someone who has those set and does not expect curl will use them. Also I don't like that something like `pt_BR` will work with cygwin setlocale and not with the default Windows CRT setlocale, where you'd have to set instead `Portuguese_Brazil.1252` unless you are using a CRT later than 2010 (then pr-BR is ok.. [full list here](https://msdn.microsoft.com/en-us/library/39cwe7zf%28v=vs.110%29.aspx), choose 'other versions' to see how it differs between CRT). So let's say we have someone that set LC_ALL to pt_BR but runs a normal build ot curl in Windows (no cygwin layer), and then we pull that from the environment variable it may not set depending on which version of the CRT it's linked against.

Still though I think it's reasonable that the Windows user have some way to change the locale for just curl, especially in the case of C. I've made some changes to make it posixy by using the LC_ and LANG env vars, which solves this issue, but I'm ambivalent about it.
https://github.com/curl/curl/compare/master...jay:win32_import_locale_env?expand=1

**Comment by heckler-hp** [comment]
@jay, thanks for the _very through_ write-up and for proposing a fix!

I just wanted to add that I took your suggestion and did a further test under cygwin 2.876, confirming that indeed `setlocale(LC_ALL, "")` works in the POSIX expected way there:

```
$ LC_ALL=C curl --silent --output /dev/nul --write-out "Total time: %{time_total}\n" google.com
Total time: 0.415

$ LC_ALL=pt_BR curl --silent --output /dev/nul --write-out "Total time: %{time_total}\n" google.com
Total time: 0,103

$ curl -V
curl 7.50.3 (i686-pc-cygwin) libcurl/7.50.3 OpenSSL/1.0.2j zlib/1.2.8 libidn/1.29 libpsl/0.14.0 (+libidn/1.29) libssh2/1.7.0 nghttp2/1.14.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets Metalink PSL
```

**Comment by jay** [comment]
Note `/dev/nul` does not represent the null device, instead it is the path to a file, likely C:/msys64/dev/nul. In git/msys/cygwin bash you can do `/dev/null` or from the command prompt cmd shell use `NUL`.

**Comment by jay** [comment]
hm I just tested it and technically that goes to the nul device since it is a path that has the filename as nul.. my mistake.

**Comment by heckler** [comment]
Oops, my bad on the typo, even it it works as typed  :-)

**Comment by bagder** [comment]
@jay, any plans for this?

**Comment by jay** [comment]
I'll take it to the list, I'm not 100% on it and it needs more feedback. If I can't come to a solution I'll put it in known bugs. My concern is the same, different versions of the CRT expect different locale strings, PITA.
