### ISSUE TITLE
regression: CONNECT_TIME is always 0 between v7.85 and v7.87

### ISSUE THREAD

**Issue by mxschmitt** [curl/curl#10371]
### I did this

1. ~create a `simple.css` file in some directory and put something inside - content does not matter.~
2. ~create a web-server with `npx http-server .`~
3. ~compile the program and run it.~

See https://github.com/curl/curl/issues/10371#issuecomment-1410304514 for the latest repro.

### I expected the following

connect_time > 0

### curl/libcurl version

    curl 7.87.0-DEV (i386-pc-win32) libcurl/7.87.0-DEV Schannel WinIDN

### operating system

Windows 11

### Additional information

We encountered this bug on Webkit.

good: v7.85
bad: 7.87

**Comment by bagder** [comment]
What if you use many more decimals?

I cannot reproduce with this:
~~~
curl -w '%{time_connect}\n' https://curl.se/ -o /dev/null

**Comment by dfandrich** [comment]
I see connect times of < 1 ms in my tests to localhost which means you'd need at least 4 decimal places to see something other than 0.

**Comment by mxschmitt** [comment]
Daniel, you are right. I'm closing this issue for now and either reopen or re-file once I found more details about it, since we encountered some curl regression (either intended or not).

Thanks!

**Comment by mxschmitt** [comment]
I've got a new repro which is a bit different but demonstrates the issue:

```cpp
#include <iostream>
#include "curl/curl.h"
#include <string>
using namespace std;


size_t write_data(void* buffer, size_t size, size_t nmemb, void* userp)
{
    return size * nmemb;
}

int main(int argc, char* argv[])
{
    auto data = curl_version_info(CURLVERSION_NOW);
    fprintf(stderr, "Using curl versin %s\n", data->version);

    auto req = curl_easy_init();
    if (req == NULL)
    {
        fprintf(stderr, "curl_easy_init() failed\n");

    }
    curl_easy_setopt(req, CURLOPT_URL, "http://localhost:8907/one-style.css");
    // Stdio does not get polluted
    curl_easy_setopt(req, CURLOPT_WRITEFUNCTION, write_data);
        
    CURLcode res;
    double connect;

    // Request 1
    {
        res = curl_easy_perform(req);
        if (res != CURLE_OK)
        {
            fprintf(stderr, "curl_easy_operation() failed : %s\n", curl_easy_strerror(res));
        }
        res = curl_easy_getinfo(req, CURLINFO_CONNECT_TIME, &connect);
        if (CURLE_OK == res) {
            printf("Time: %lf\n", connect);
        }
    }

    // Request 2
    {
        res = curl_easy_perform(req);
        if (res != CURLE_OK)
        {
            fprintf(stderr, "curl_easy_operation() failed : %s\n", curl_easy_strerror(res));
        }
        res = curl_easy_getinfo(req, CURLINFO_CONNECT_TIME, &connect);
        if (CURLE_OK == res) {
            printf("Time: %lf\n", connect);
        }
    }

    curl_easy_cleanup(req);
    return 0;
}
```

Expected: have connect time available in both requests
Actual: its only available for the first request and for the second its 0.00000

Was able to verify that it shows the connect time in the second request in v7.85 but not in v7.87. I was able to bisect it to the following change: https://github.com/curl/curl/commit/dafdb20a26d0c890e83dea61a104b75408481ebd

**Comment by bagder** [comment]
If the connection is reused, the second request has no "connection time" to speak of so it will be zero.
