### ISSUE TITLE
CURLOPT_WRITEFUNCTION man page: Memory leak in example

### ISSUE THREAD

**Issue by Thomas1664** [curl/curl#10387]
The callback in the example for [`CURLOPT_WRITEFUNCTION`](https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) calls `realloc` but the memory is never freed in the calling code. Although it should be obvious I think it would be better to remind people that the buffer inside `memory` needs to be freed after using it.

I'd make a patch to fix this if you want.

**Comment by bagder** [comment]
Please do!

**Comment by bagder** [comment]
Fixed by #10390
