### ISSUE TITLE
regression: CURLOPT_SSL_SESSIONID_CACHE option support is broken in curl 7.87

### ISSUE THREAD

**Issue by tilicho** [curl/curl#10380]
### I did this
I turned off session cache support by setting CURLOPT_SSL_SESSIONID_CACHE option to 0 (using libcurl).
Or, I turned off session cache support using --no-sessionid option in curl utility. 
Example: ./curl --no-sessionid -kv https://google.com/

### I expected the following
I expected session id cache is not to be used and request would be completed successfully.
But I've got crash. 

Callstack example:

#0  0x00007ffff7f74e4b in ossl_trace (direction=1, ssl_ver=0, content_type=256, buf=0x555555608e23, len=5, ssl=0x5555555fdac0, userp=0x5555555c7a00) at lib/vtls/openssl.c:2674
#1  0x00007ffff7c41a76 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#2  0x00007ffff7c41f75 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#3  0x00007ffff7c7405d in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#4  0x00007ffff7c6b37e in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#5  0x00007ffff7c56d98 in SSL_do_handshake () from /lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007ffff7f76be4 in ossl_connect_step2 (cf=0x5555555c8990, data=0x5555555c8ae0) at lib/vtls/openssl.c:3901
#7  0x00007ffff7f78245 in ossl_connect_common (cf=0x5555555c8990, data=0x5555555c8ae0, nonblocking=true, done=0x7fffffffddbb) at lib/vtls/openssl.c:4441
#8  0x00007ffff7f78353 in ossl_connect_nonblocking (cf=0x5555555c8990, data=0x5555555c8ae0, done=0x7fffffffddbb) at lib/vtls/openssl.c:4474
#9  0x00007ffff7f79f4c in ssl_connect_nonblocking (cf=0x5555555c8990, data=0x5555555c8ae0, done=0x7fffffffddbb) at lib/vtls/vtls.c:357

Problem code (ossl_trace function):

```
2672   cf = (struct Curl_cfilter*) SSL_get_ex_data(ssl, cf_idx);
2673   DEBUGASSERT(cf);  // cf is 0 (but in my case debugassert is disabled)
2674   connssl = cf->ctx;  // crash here 
2675   DEBUGASSERT(connssl);
```

It seems that SSL_set_ex_data was not called for cf_idx, because condition config->primary.sessionid:

```
4855   if(config->primary.sessionid) {
4868       cf_status = SSL_set_ex_data(backend->handle, cf_idx, cf); 
```

### curl/libcurl version
7.87

### operating system
all

**Comment by bagder** [comment]
Can you try a curl built from master? I believe this problem is already fixed.

**Comment by tilicho** [comment]
Yes, it is fixed in master. Probably, it was fixed here: https://github.com/curl/curl/commit/f39472ea9f4f4e12cfbc0500c4580a8d52ce4a59#diff-03eaf320162ec20f67fab4e16f494e29735dadfa12425530869d42eea86bd2cc Thank you!
