### ISSUE TITLE
SSLKEYLOGFILE doesn't print all keys on TLS renegotiation

### ISSUE THREAD

**Issue by karelbilek** [curl/curl#10394]
### I did this

SSLKEYLOGFILE=/tmp/keys curl https://some-server-that-does-tls-renegotiation.com

### I expected the following

In /tmp/keys, I will have all the keys from all the renegotiated keys

However, there is just one, the initial one

### curl/libcurl version

```
curl 7.85.0 (x86_64-apple-darwin22.0) libcurl/7.85.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
```

### operating system

```
Darwin Karels-MacBook-Air.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
```

**Comment by karelbilek** [comment]
I find this a bit hard to test, as TLS renegotiation is unsafe and a lot of easy-to-setup servers don't support it

**Comment by bagder** [comment]
I'm not sure curl can do anything about that, I think this is then in the hands of libressl.

**Comment by jay** [comment]
LibreSSL and older versions of OpenSSL do not have a key callback function, so libcurl has its own function [ossl_log_tls12_secret](https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L810-L815) to extract and log the secret during the initial handshake (ossl_connect_step2).

https://github.com/curl/curl/blob/c12fb3ddaf48e709a7a4deaa55ec485e4df163ee/lib/vtls/openssl.c#L3902-L3909

Renegotiation is transparent for this SSL backend which means it happens during SSL_read/SSL_write. ossl_connect_step2 is not called again. [SSL_CTX_set_info_callback](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_info_callback.html) has a SSL_CB_HANDSHAKE_DONE that possibly could be used to extract the updated key.

I did test this using OpenSSL's s_server which has an 'r' command that sends a renegotiate for TLS 1.2 and below.

`openssl s_server -accept 8000 -cert [removed] -no_tls1_3 -keylogfile keys`

`SSLKEYLOGFILE=[removed] src/curl -k -v https://[removed]:8000 --tls-max 1.2`

(I hit 'r' after the connection was made and it renegotiated)

~~~
r
SSL_do_handshake -> 1
Read BLOCK
HTTP/1.1 200 OK
Content-Length: 0

DONE
shutting down SSL
CONNECTION CLOSED
~~~

`curl 7.87.1-DEV (x86_64-pc-linux-gnu) libcurl/7.87.1-DEV LibreSSL/3.7.0 zlib/1.2.8 nghttp2/1.50.0 librtmp/2.3`

key output created by openssl server:
~~~
# SSL/TLS secrets log file, generated by OpenSSL
CLIENT_RANDOM 5b6113b0100f336261ac3300a652b6108867a75d0bdac0d508545d0c6ec84072 a3d98ecc09bf2ac013f9b139bc76aa41d0dcc5b88bb70a463d0d88038998ee6ef284d44a8e77fca98fe04fb189231dcc
CLIENT_RANDOM 50371c016891a49347b7ec45f73024c3ea9cd89a02414c1256db4382e67faf6c a3d98ecc09bf2ac013f9b139bc76aa41d0dcc5b88bb70a463d0d88038998ee6ef284d44a8e77fca98fe04fb189231dcc
~~~

key output created by libcurl:
~~~
CLIENT_RANDOM 5B6113B0100F336261AC3300A652B6108867A75D0BDAC0D508545D0C6EC84072 A3D98ECC09BF2AC013F9B139BC76AA41D0DCC5B88BB70A463D0D88038998EE6EF284D44A8E77FCA98FE04FB189231DCC
~~~

I monitored the transfer in Wireshark and set the keyfile (Pref > Protocol > TLS) to the libcurl one. With just that one key it was able to decrypt the response sent after the renegotation took place. You'll notice the openssl key line is actually the master key is the same the second time but the client random is different. I'm not sure if that is guaranteed but long story short I can decrypt the session with only the first key.

So is this worth fixing in curl to save both client randoms? I don't know.

**Comment by karelbilek** [comment]
hm, interesting. When I tested that, I was not able to decrypt the data _after_ the renegotiation with just the first key. (The renegotiation added a client certificate.)

The server I call didn't want client cert before renegotiation, wanted after renegotiation. Maybe that has something to do with it.

I cannot provide you the code to the server though.

**Comment by karelbilek** [comment]
The renegotiation can in theory change the entire cipher suite, right?

**Comment by jay** [comment]
> The renegotiation can in theory change the entire cipher suite, right?

Yes. You can try to extract the key after the handshake done message to see if it's actually different.

**Comment by bagder** [comment]
Is there anything left for us to do here?

**Comment by karelbilek** [comment]
I wanted to provide a test code to show what will happen on the change of the keys, but... yeah whatever. Maybe I will reopen when I get to it.
