### ISSUE TITLE
Error: curl_multi_socket_action failed.  Reason: API function called from within callback at Curl.perform

### ISSUE THREAD

**Issue by gkit1980** [curl/curl#10404]
<!-- Only file bugs here! Ask questions on the mailing lists https://curl.se/mail/

I have version Node 10.19.
im running an angular project that it worked before updating my os(updated to Vendura 13.2)
 The code is:

private execute(curl: any): Promise<CurlNtlmRestResponse> {
    let promise = new Promise<CurlNtlmRestResponse>((resolve, reject) => {
      curl.on("end", (status: any, argBody: any, argHeader: any) => {
        let response = new CurlNtlmRestResponse(status, argBody, argHeader);
        resolve(response);
      });
      curl.on("error", (err: any, errCode: any) => {
        console.log("============>ERROR=======:" + err + "=====>ERRORCODE=====:" + errCode);
        reject(err);
      });
      curl.perform();
    });
    return promise;
  }
The error that appears is:
 Error: curl_multi_socket_action failed.  Reason: API function called from within callback at Curl.perform

Before the update of os it worked normally. I reinstalled everything except the os(i had Catalina before)
The version of curl is  v7.87 and im using node-libcurl 1.3.3.

If you can help me i would be gratefull!

### curl/libcurl version

[curl -V output]

### operating system
Mac Vendura 13.2

**Comment by bagder** [comment]
This is not enough information for us to act on. This sounds like you used the API wrongly.

**Comment by gkit1980** [comment]
Sorry! I thought i sent the proper info in the text box. Apologies!
i have updated the os for Mac(Vendura 13.2) and suddenly the node-libcurl (v1.3.3) appears an error:

**Error: curl_multi_socket_action failed. Reason: API function called from within callback at Curl.perform**

My code is:

private execute(curl: any): Promise<CurlNtlmRestResponse> {
    let promise = new Promise<CurlNtlmRestResponse>((resolve, reject) => {
      curl.on("end", (status: any, argBody: any, argHeader: any) => {
        let response = new CurlNtlmRestResponse(status, argBody, argHeader);
        resolve(response);
      });
      curl.on("error", (err: any, errCode: any) => {
        console.log("============>ERROR=======:" + err + "=====>ERRORCODE=====:" + errCode);
        reject(err);
      });
      curl.perform();       ///@@@@ here is the error
    });
    return promise;
  }

with: 

export class CurlNtlmRestResponse {
	public readonly contentType: string;
	public readonly isJSON: boolean;
	constructor(public readonly status: number, public readonly data: any, public readonly headers: Array<any>) {
		//extract content type
		if (this.headers && this.headers.length > 0) {
			let lastHeader = this.headers[this.headers.length - 1];
			this.contentType = lastHeader['Content-Type'] || lastHeader['content-type'];
		}
		else {
			this.contentType = undefined;
		}
		//is it json
		this.isJSON = this.contentType && this.contentType.toLowerCase().includes('application/json');
		//if it is JSON, parse it
		if (this.isJSON)
			this.data = JSON.parse(this.data);
	}
}

and:


export class CurlOAuthRestClient implements IceRestClient {

  private environmentVariables: any;
  private setvars: boolean = false;

  constructor(
    private verbose: boolean = false
  ) 
  { }

  public async request(config: any): Promise<any> {
   


    let bearerToken = config.data.token;
    if (config.data.token != undefined) {
    
    } else {
      console.error("token not defined");
    }


    if (!this.setvars) {
      this.environmentVariables = await this.getEnvironmentVariables('default');
      this.setvars = true;

    }
    config.baseURL = this.environmentVariables[config.baseURL] || config.baseURL;
   
    let curl = this.prepareRequest(config, bearerToken);
    var startTime = new Date().getTime();
    let response = await this.execute(curl);
  
    return response;
  }

  private prepareRequest(config: any, bearerToken: string) {
    let curl = new Curl();

    curl.setOpt(Curl.option.URL, config.baseURL + "/" + config.url);
    curl.setOpt(Curl.option.HTTPAUTH, Curl.auth.XOAUTH2_BEARER);
    curl.setOpt(Curl.option.VERBOSE, this.verbose);
    
    curl.setOpt(Curl.option.HTTPHEADER, [
      "Content-Type: application/json",
      `authorization: Bearer ${bearerToken} `
      
    ]);
    curl.setOpt(Curl.option.POSTFIELDS, JSON.stringify({}));
    curl.setOpt(Curl.option.SSL_VERIFYPEER, 0);

    curl.on("end", function (statusCode: any, body: any, headers: any) {
      
    });
    curl.setOpt(Curl.option.POSTFIELDS, JSON.stringify(config.data));

    return curl;
  }

  private execute(curl: any): Promise<CurlNtlmRestResponse> {
    let promise = new Promise<CurlNtlmRestResponse>((resolve, reject) => {
      curl.on("end", (status: any, argBody: any, argHeader: any) => {
        let response = new CurlNtlmRestResponse(status, argBody, argHeader);
        resolve(response);
      });
      curl.on("error", (err: any, errCode: any) => {
        console.log("============>ERROR=======:" + err + "=====>ERRORCODE=====:" + errCode);
        reject(err);
      });
      curl.perform();
    });
    return promise;
  }

  //
  // - loads environmentVariables from recipe 
  // - replace any key/value if present in process.env and
  // - adds all (non-object) app.locals values to it
  //
  private async getEnvironmentVariables(repoPath: string): Promise<any> {
    let repositoryService = new RepositoryService(repoPath);
    let environmentVariables = await repositoryService.getEnvironmentVariables();

    _.keys(environmentVariables).forEach((key: string) => {
      if (process.env[key] != null) environmentVariables[key] = process.env[key];
    });

    _.keys(process.env).forEach((key: string) => {
      let isObject = _.isObject(process.env[key]) && (!_.isArray(process.env[key]))
      if (isObject) return;
      environmentVariables[key] = process.env[key];
    });

    return environmentVariables;
  } 
}


I reinstall everything except os but it did not help!
If you can help i would appreciated it!

**Comment by dfandrich** [comment]
What is the libcurl version where this worked? In ver. 7.59.0 a number of checks were added for invalid recusive calls that might be the source of this, but that version is already several years old.

This is obviously using some kind of libcurl binding sitting on top of libcurl. You're probably better off reporting this to the binding authors.

**Comment by bagder** [comment]
This is not a curl bug, this is an application using the libcurl API in a way that is not supported and thus libcurl returns this error.
