### ISSUE TITLE
"packages" folder README disagrees with actual folder contents

### ISSUE THREAD

**Issue by jmporter34** [curl/curl#10416]
The README in the "packages" folder states "Currently, we have Win32 and Linux for [OS]. "
However, the folder only contains "Android", "OS400" and "vms" subfolders.
1. The README file is wrong.
2. Where are the Win32 and Linux packages ?

Sorry if #2 is a stupid question, I'm new to using curl.
thanks

**Comment by bagder** [comment]
If you want download curl, try [the download page](https://curl.se/download.html).

**Comment by jmporter34** [comment]
Thank you, the files that were missing in Github were in the zip file from
the download page.
Is Github not the master repository for this project ?
Regards,
John Porter

**Comment by bagder** [comment]
Answered in  #10417
