### ISSUE TITLE
"projects/Windows/VCxx" folders are all missing files

### ISSUE THREAD

**Issue by jmporter34** [curl/curl#10417]
Each of the six VCxx folders (VC10, VC11 etc.) contains a file named "curl.sln".
Each of those files reference "src\curl.vcxproj" and "lib\libcurl.vcxproj".
Those files are missing.
The "src" folders DO contain files named "curl.vcxproj.filters", and the "lib" folders DO contain files named "libcurl.vcxproj.filters".
Those files are also required, but are insufficient by themselves.  The missing file named "src\curl.vcxproj" and "lib\libcurl.vcxproj" are also required for VS to load the projects.
I attempted to load the sln files with VS 2022 Community and they won't load.
Thanks

**Comment by dfandrich** [comment]
I assume you're looking at the git repo. Some of those files are generated, so
you'll either need to generate them yourself or download a release tar ball
which has them already.

**Comment by jmporter34** [comment]
Thank you, the files that were missing in Github were in the zip file from
the download page.
Is Github not the master repository for this project ?
Regards,
John Porter

**Comment by dfandrich** [comment]
Yes, it's the master repository, but in the same way that we don't check in
DLLs into the repository, we also don't check in other generated files like
that. If you want to use git instead of a release archive, then read the
GIT-INFO file to find out how to build the missing files.

**Comment by jmporter34** [comment]
I understand that we don't check in DLLs, executables etc.  I just didn't
realize that VS vcxproj files could be generated.  Sheltered life I guess
:-)
Thanks very much for the help!
