### ISSUE TITLE
How to take advantage of HTTP/2

### ISSUE THREAD

**Issue by jeroenooms** [curl/curl#1041]
From the [HTTP/2 with curl](https://curl.haxx.se/docs/http2.html) manual it is still unclear to me how and when libcurl can use multiplexing. 

More specifically, I don't understand where the multi-handle joins connections from several easy-handles for multiplexing, and what happens after those easy-handles are done and get removed from the multi-handle.

To test this, I implemented a small web crawler which downloads a html page, and then recursively follows all html hyperlinks from that page that point to other pages on the same domain, and so on, until all links on the page have been visited. However I am not seeing expected performance boost for multiplexing, either with or without `nghttp2`.

Basically the application is designed like this:

 - One global multi-handle
 - For each request a new easy-handle is created and added to the multi-handle
 - In the callback of the easy handle: 
    - If response is `text/html`, parse document and add new easy-handles for each `href`
    - Remove itself from the multi handle and free itself

I tried this to by crawling an archive that is hosted on amazon cloudfront (http2). Hence because all requests go to a single fast HTTP/2 server, it seems this should benefit from multiplexing. However I found that the crawling speed was only affected by `CURLMOPT_MAX_HOST_CONNECTIONS`, I did not see any effect of `CURLMOPT_PIPELINING`. Hence I am not sure they were being multiplexed at all.

So my main questions are:

  - How do I inspect if the multi-handle is multiplexing requests from its easy-handles?
  - Is it possible to configure easy-handles to use a joined connection pool for multiplex?
  - One a request is done and the easy-handle is removed from the multi-handle, will other handles that are multiplexing on the same connection be affected?
  - Why would `CURLMOPT_MAX_HOST_CONNECTIONS` every need to be greater than 1 if `CURLPIPE_MULTIPLEX` has been set?

**Comment by jeroenooms** [comment]
I have created a small program to illustrate what I don't understand (see below). 

The test program makes 4 requests to `https://http2bin.org/delay/3`. The server supports HTTP/2 and takes exactly 3 seconds to return. Hence if requests would be multiplexed, the program should complete in about 3 sec...

However in reality the program takes 12 seconds to run, which means the requests are not getting multiplexed? The verbose output shows a lot of these messages:

```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Found bundle for host http2bin.org: 0x7fbd7242da00 [can multiplex]
* No more connections allowed to host: 1
* No connections available.
```

From this it seems that even though multiplex connections are available, libcurl still needs to open new connections to perform the other requests? Why doesn't it use the existing connection?

```c
/* Jeroen Ooms, 2016
 *
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* curl stuff */
#include <curl/curl.h>

int main(){
  //check nghttp2 supprt
  const curl_version_info_data *data = curl_version_info(CURLVERSION_NOW);
  if(data->features & CURL_VERSION_HTTP2){
    fprintf(stdout, "This libcurl DOES have HTTP2 support!\n");
  } else {
    fprintf(stdout, "This libcurl does NOT have HTTP/2 support!\n");
  }

  // Create multi handle with multiplex over a single connection
  CURLM *multi_handle = curl_multi_init();
  curl_multi_setopt(multi_handle, CURLMOPT_MAX_HOST_CONNECTIONS, (long) 1L);
  curl_multi_setopt(multi_handle, CURLMOPT_PIPELINING, CURLPIPE_HTTP1 & CURLPIPE_MULTIPLEX);

  // Add some requests
  int NUM_HANDLES = 3;
  CURL *easy[NUM_HANDLES];
  for(int i = 0; i < 3; i++){
    char url[1024];
    snprintf(url, 1024, "https://http2bin.org/delay/3?nocache=%d", i);
    easy[i] = curl_easy_init();
    curl_easy_setopt(easy[i], CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(easy[i], CURLOPT_URL, url);
    curl_easy_setopt(easy[i], CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);
    curl_multi_add_handle(multi_handle, easy[i]);
  }

  //perform requests
  int still_running = 1;
  while(still_running){
    curl_multi_perform(multi_handle, &still_running);
  }

  //cleanups
  for(int i = 0; i < NUM_HANDLES; i++)
    curl_easy_cleanup(easy[i]);
  curl_multi_cleanup(multi_handle);
  exit(0);
}
```

**Comment by jay** [comment]
It has something to do with `CURLPIPE_HTTP1`, it looks fine if I remove it:
~~~
("nocache": "0")	16	2016-09-28 21:34:39.708337	192.168.1.2	104.131.161.90	HTTP2	126	HEADERS
("nocache": "1")	20	2016-09-28 21:34:39.879053	192.168.1.2	104.131.161.90	HTTP2	112	HEADERS
("nocache": "2")	22	2016-09-28 21:34:39.962954	192.168.1.2	104.131.161.90	HTTP2	112	HEADERS

("nocache": "0")	24	2016-09-28 21:34:42.754834	104.131.161.90	192.168.1.2	HTTP2	516	HEADERS, DATA
("nocache": "1")	25	2016-09-28 21:34:42.904188	104.131.161.90	192.168.1.2	HTTP2	414	HEADERS, DATA
("nocache": "2")	27	2016-09-28 21:34:42.989000	104.131.161.90	192.168.1.2	HTTP2	414	HEADERS, DATA
~~~

The full wireshark trace from above is [attached](https://github.com/curl/curl/files/499352/http2_multiplex_3_transfers.zip):
```
capture_anon.keys      <--- ssl keys for capture
capture_anon.pcapng    <--- packet capture of demo
```
To view the packet capture load the file then load the keys:
`Edit > Preferences > Protocols > SSL > Master-Secret log`

**Comment by jeroenooms** [comment]
I found part of the bug in this example. I should probably use bitwise OR to enable both options, i.e `CURLPIPE_HTTP1 | CURLPIPE_MULTIPLEX` instead of `CURLPIPE_HTTP1 & CURLPIPE_MULTIPLEX`.

That doesn't answer my other questions yet though.

**Comment by jay** [comment]
> I found part of the bug in this example. I should probably use bitwise OR to enable both options, i.e CURLPIPE_HTTP1 | CURLPIPE_MULTIPLEX instead of CURLPIPE_HTTP1 & CURLPIPE_MULTIPLEX.

Oops I missed that. Yeah that'll do it!

> That doesn't answer my other questions yet though.

This is an issue tracker, you should take questions to the libcurl mailing list. Briefly though:

I don't know of an easy way to "inspect" what was sent to confirm it's actually multiplexed; you'd have to use something like CURLOPT_DEBUGFUNCTION or Wireshark.

When you remove an easy from multi the other easys multiplexing in the multi should not be affected.

Allowing more than one connection to a host may have performance gain or not depending on how the transfers are taking place
