### ISSUE TITLE
http3: segfault with quiche and openssl backend

### ISSUE THREAD

**Issue by Kangie** [curl/curl#10429]
### I did this
```
curl -vvvvv --http3 https://quic.rocks:4433/
*   Trying [2001:19f0:4:34::1]:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
[1]    49803 segmentation fault (core dumped)  curl -vvvvv --http3 https://quic.rocks:4433/
```

Running with gdb:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a99bc7 in bssl::set_version_bound(bssl::SSL_PROTOCOL_METHOD const*, unsigned short*, unsigned short) () from /usr/lib64/libquiche.so
```

### I expected the following

Successful web request!

### curl/libcurl version

```curl --version                              
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/1.1.1s zlib/1.2.13 c-ares/1.19.0 nghttp2/1.51.0 quiche/0.16.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: AsynchDNS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
```
### operating system

`Linux monolith 6.1.7-gentoo--bouncy-mouse #1 SMP PREEMPT_DYNAMIC Sun Jan 29 09:28:12 AEDT 2023 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux`

### Additional Information

See Also: https://bugs.gentoo.org/881711

Build Log: [curl-build.log.txt](https://github.com/curl/curl/files/10672251/curl-build.log.txt)

Reported as working in v7.86 with the gnutls and nghttp3 backends.

As per the bug and gdb segfault output this appears to be related to the ssl impl that quiche bundles.

**Comment by bagder** [comment]
I'm pretty sure this problem is already fixed in git. Can you try that and make sure?

**Comment by Kangie** [comment]
I'm seeing the same issue when built from `master`:

```bash
kangie@monolith /data/development/temp/curl (master) $ ./src/curl -vvvvv --http3 https://quic.rocks:4433/
*   Trying [2001:19f0:4:34::1]:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
[1]    355123 segmentation fault (core dumped)  ./src/curl -vvvvv --http3 https://quic.rocks:4433/
```

Some additional sleuthing has uncovered the following bug on the Gentoo side - https://bugs.gentoo.org/847583: net-libs/quiche-0.1[34].0: installs non-functional libquiche.so

I'm not sure if this is related - FWIW I'm using `net-libs/quiche-0.16.0`

**Comment by bagder** [comment]
It does not reproduce for me, but my IPv6 is not working and my curl with quiche does not connect over QUIC to quic.rocks:4433.

**Comment by Kangie** [comment]
Definitely not ipv6 related:

```bash
./src/curl -vvvvv --http3 https://quic.rocks:4433/ --ipv4
*   Trying 216.155.158.183:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
[1]    355794 segmentation fault (core dumped)  ./src/curl -vvvvv --http3 https://quic.rocks:4433/ --ipv4
```

**Comment by Kangie** [comment]
> Hmm, can do curl something here? It sounds as if the libquiche and bssl libs do not agree with each other on that system?

I'm honestly not sure! I was quietly hoping that this was a known issue that I'd missed in my initial investigation. I can try asking the quiche team about it - AFAIK quiche [vendors its boringssl](https://github.com/cloudflare/quiche/tree/master/quiche/deps)

**Comment by bagder** [comment]
They vendor it, but I build with a separate boringssl in my local builds and it works fine while the quiche CI jobs we have using the vendored take, and that runs fine as well.

**Comment by bagder** [comment]
If you think this is an actual problem in curl/quiche and not just in your build, then I would ask you to do a stand alone build with documented build steps that can be reproduced by others appropriately.

**Comment by andy5995** [comment]
@Kangie just a longshot, but can you add the compiler flags `-fsanitize=address,undefined` and rebuild. Then try running curl again, the same way you did before, and seeing if there's any more debug output?

**Comment by andy5995** [comment]
> @Kangie just a longshot, but can you add the compiler flags `-fsanitize=address,undefined` and rebuild. Then try running curl again, the same way you did before, and seeing if there's any more debug output?

Sorry, disregard that. I should have experimented a little myself. The build will fail if you add that.

**Comment by andy5995** [comment]
@Kangie I used  `CFLAGS="${CFLAGS} -fno-omit-frame-pointer -Wl,--allow-shlib-undefined -fsanitize=address,undefined"` and added `--disable-optimize --enable-debug` to the configure flags and the build completed.

**Comment by Kangie** [comment]
Ack. My Dev machine is out of action but should be good tomorrow - will report back!

**Comment by Kangie** [comment]
> If you think this is an actual problem in curl/quiche and not just in your build, then I would ask you to do a stand alone build with documented build steps that can be reproduced by others appropriately.

I can repro this building from master with the openssh backend and my system quiche, configured as: `./configure --with-quiche --with-openssl`

OpenSSL/1.1.1s
quiche/0.16.0

It should be trivial to repro in a Gentoo container; once my Dev machine is back up I'll look into that.

There's definitely an issue (I repro'd this based on the Gentoo bug reported by another user) however this issue could well be the way that Gentoo builds/packages quiche, which is my suspicion at the moment.

**Comment by bagder** [comment]
> OpenSSL/1.1.1s

This puzzles me. Are you building with *both* OpenSSL and BoringSSL? You should only use a single one: BoringSSL, when you build with quiche.

**Comment by Kangie** [comment]
> > OpenSSL/1.1.1s
> 
> This puzzles me. Are you building with _both_ OpenSSL and BoringSSL? You should only use a single one: BoringSSL, when you build with quiche.

Shouldn't configure treat those options as mutually exclusive in that case?

**Comment by SamTherapy** [comment]
> Shouldn't configure treat those options as mutually exclusive in that case?

From my cursory test, yes.
I believe this is a Gentoo-specific packaging problem, I was able to reproduce the crash using curl from Portage:
```
❯ curl --version
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 c-ares/1.19.0 nghttp2/1.51.0 quiche/0.16.0

Release-Date: 2022-12-21
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: AsynchDNS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets

❯ curl --http3 https://cloudflare-quic.com/ -I
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1981992==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000304 (pc 0x7fb551d2a8e5 bp 0x000000000001 sp 0x7fff62e0c0c0 T0)
==1981992==The signal is caused by a READ memory access.
==1981992==Hint: address points to the zero page.
    #0 0x7fb551d2a8e5  (/usr/lib64/libquiche.so+0x17d8e5)
    #1 0x7fb551c91229  (/usr/lib64/libquiche.so+0xe4229)
    #2 0x7fb551c59e76  (/usr/lib64/libquiche.so+0xace76)
    #3 0x7fb551c998a9 in quiche_conn_new_with_tls (/usr/lib64/libquiche.so+0xec8a9)
    #4 0x7fb5525aecb4  (/usr/lib64/libcurl.so.4+0x431cb4)
    #5 0x7fb552371792  (/usr/lib64/libcurl.so.4+0x1f4792)
    #6 0x7fb552378e1b  (/usr/lib64/libcurl.so.4+0x1fbe1b)
    #7 0x7fb5524a093d  (/usr/lib64/libcurl.so.4+0x32393d)
    #8 0x7fb55249e551 in curl_multi_perform (/usr/lib64/libcurl.so.4+0x321551)
    #9 0x7fb5523a8efc in curl_easy_perform (/usr/lib64/libcurl.so.4+0x22befc)
    #10 0x55833096777d  (/usr/bin/curl+0x1fe77d)
    #11 0x558330966109  (/usr/bin/curl+0x1fd109)
    #12 0x5583309645a5  (/usr/bin/curl+0x1fb5a5)
    #13 0x7fb551ea32cb  (/usr/lib64/libc.so.6+0x232cb)
    #14 0x7fb551ea3384 in __libc_start_main (/usr/lib64/libc.so.6+0x23384)
    #15 0x558330866590  (/usr/bin/curl+0xfd590)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libquiche.so+0x17d8e5)
==1981992==ABORTING
```
but a local build works just fine following the documentation from https://curl.se/docs/http3.html
```
❯ ./src/curl --version
WARNING: this libcurl is Debug-enabled, do not use in production

curl 7.87.1-DEV (x86_64-pc-linux-gnu) libcurl/7.87.1-DEV BoringSSL zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 nghttp2/1.51.0 quiche/0.16.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TrackMemory UnixSockets zstd

❯ ./src/curl --http3 https://cloudflare-quic.com/ -I
HTTP/3 200
```

Looks like the problem lies with the clashing OpenSSL and Quiche/BoringSSL configuration

**Comment by bagder** [comment]
> Shouldn't configure treat those options as mutually exclusive in that case?

quiche is a QUIC and HTTP/3 library and OpenSSL is a TLS library, they are not mutually exclusive.

The problem is that you build quiche to use one OpenSSL fork (BoringSSL) and then you tell curl to use another, and since they are both OpenSSL flavors they cannot really co-exist correctly in a single binary.

**Comment by thesamesam** [comment]
It doesn't look like quiche can use anything other than BoringSSL (so quiche always implies boringssl), so building curl with OpenSSL support is mutually exclusive with quiche?

(Unless you can make curl use BoringSSL, but we wouldn't want to do that given Google's statements about its suitability fo general use.)

What am I missing?

**Comment by bagder** [comment]
If you want to use quiche, you need to build curl against **the same** TLS library you built quiche with. Probably BoringSSL.

**Comment by bagder** [comment]
It should be noted that if you want to build curl with HTTP/3, you **cannot** use vanilla OpenSSL because they do not provide the necessary API. BoringSSL, libressl and quictls are three OpenSSL flavors that do.

OpenSSL will not provide the API until at best in a few years time.

**Comment by bagder** [comment]
I don't consider this a curl issue since it is "just" a build matter. Closing.
