### ISSUE TITLE
Could curl (7.87 version) do the total transfer based on the callback function? that's work with curl-7.86 and previous version.

### ISSUE THREAD

**Issue by TheBetterSolution** [curl/curl#10426]
### I did this
   1. Prepare one curl handle to access a valid url and add the curl handle to a multi handle.
   2. Call curl_multi_socket_all once.
   3. If the CURLMOPT_SOCKETFUNCTION is called then record the notified sockets and put the sockets to other thread (The polling thread) for polling, else exit.
   4. After the polling thread discovers any socket is ready to send/recv, the polling thread notify this case with socket information to main thread.
   5. Main thread calls curl_multi_sockate_action once with the parameters from the socket information to transfer remain data.
   7. Goto step 3.
### I expected the following
  Total transfer process is done.
  curl-7.86 and previous version can work with this model, but curl7.87 doesn't call CURLMOPT_SOCKETFUNCTION callback when call curl_multi_socket_all first time.

  I would prefer to use the callback function notification to do total transfer, but don't use the CURLMSG_DONE message returned by curl_multi_info_read and the output parameter runningHandles of curl_multi_socket_all/curl_multi_socket_action to determine if there is remain transfer and continue to call curl_multi_socket_all/curl_multi_socket_action directly.
  
   I add the log messages in the callback functions (CURLMOPT_SOCKETFUNCTION and CURLMOPT_TIMERFUNCTION) and before and after calling curl_multi_socket_all:

~~~c
   //The CURLMOPT_SOCKETFUNCTION callback:
   int socket_callback(CURL *curl,
                                  curl_socket_t sock,
                                  int action,
                                  void *data,
                                  void *socketp)
   {
      printf("Enter %s\n", __FUNCTION__);
      //...
      printf("Leave %s\n", __FUNCTION__);
   }

   //The CURLMOPT_TIMERFUNCTION callback:
   int timer_callback(CURLM *multi,
                               long timeoutMS,
                              void *data)
   {
      printf("Enter %s\n", __FUNCTION__);
      //...
      printf("Leave %s\n", __FUNCTION__);
   }

   /* ...
    * The code calling curl_multi_socket_all.
    */
   printf("Call curl_multi_socket_all begin\n");
   multiRes = curl_multi_socket_all(multiHandle, &runningHandles);
   printf("Call curl_multi_socket_all end: %d\n", multiRes));
~~~

   The output log messages are following:
   curl-7.86:
   Call curl_multi_socket_all begin
   ...
   Enter timer_callback
   Leave timer_callback
   Enter socket_callback
   Leave socket_callback
   ...
   Call curl_multi_socket_all end: 0

   curl-7.87:
   Call curl_multi_socket_all begin
   ...
   Enter timer_callback
   Leave timer_callback
   //CURLMOPT_SOCKETFUNCTION callback is not called, this model doesn't work.
   ...
   Call curl_multi_socket_all end: 0

### curl/libcurl version
7.87.0

[curl -V output]
libcurl/7.87.0 OpenSSL/1.0.2 zlib/1.2.13

### operating system
Windows 11 AMD64

**Comment by dfandrich** [comment]
Is there any chance that two threads are accessing the same handle at the same
time? That's not allowed. Does the program abide by everything in
https://curl.se/libcurl/c/threadsafe.html ?

**Comment by TheBetterSolution** [comment]
Hi @dfandrich,
There isn't any chance two thread are accessing the same handle, because main thread loses the handle control after send the socket to polling thread, and polling thread loses the handle control after send the socket to the main thread.

**Comment by bagder** [comment]
I suspect you see a bug in 7.87.0 that we have fixed since. Any chance you can try the current git master and see if this behaves better for you?

**Comment by botcher** [comment]
I'm seeing the same behavior when a proxy is set. @bagder Could you share the bug or commit info?

**Comment by bagder** [comment]
I suspect the #10160 change is what's needed

**Comment by bagder** [comment]
We've done a lot of refactoring of connect management since the 7.87.0 release so either way it would be helpful to know what the current status is.

**Comment by TheBetterSolution** [comment]
Hi @bagder thanks.
The error case happens if enable proxy tunnel, I try to find the reason, I found the following code in http_proxy.c :
`    
      case TUNNEL_RECEIVE:
      /* read what is there */
      result = recv_CONNECT_resp(data, cf->conn, ts, &done);
      if(Curl_pgrsUpdate(data)) {
        result = CURLE_ABORTED_BY_CALLBACK;
        goto out;
      }
      /* error or not complete yet. return for more multi-multi */
      if(result || !done)
        goto out;
      /* got it */
      tunnel_go_state(cf, ts, TUNNEL_RESPONSE, data);
      /* FALLTHROUGH */
`
By the comments: " error or not complete yet. return for more multi-multi", 
Does version 7.87 libcur need to call curl_multi_socket_all multiple times to establishes the proxy tunnel connection?
(curl-7.86 call curl_multi_socket_all once).

**Comment by cmoaciopm** [comment]
@bagder, we met the same issue in our product. Is there a plan to deliver a release to fix the issue recently?

**Comment by bagder** [comment]
7.88.0 will be released on Feb 15, 2023. See https://curl.se/dev/release-notes.html

**Comment by TheBetterSolution** [comment]
Hi @bagder @dfandrich ,The CURLMOPT_SOCKETFUNCTION can be called when I patched code with this suggested commit: https://github.com/curl/curl/pull/10160.
But I found the callback CURLMOPT_SOCKETFUNCTION doesn't be called on some network environment (must call curl_multi_socket_action with CURL_SOCKET_TIMEOUT after timeout to do the remain transfer, I don't use the runningHandles and CURLMSG_DONE to determine whether or not continue to call curl_multi_socket_action/curl_multi_perform).
Thanks for you and @dfandrich’s great support.

**Comment by TheBetterSolution** [comment]
Hi, I have a question please:
I don't find this asynchronous IO work model of callback in the related documents:
I only found the example code and description about the IO model based on the output parameter running_handles and use curl_multi_info_read.
So, I wish to known: Does curl support the callback work model officially? Could I find the documents and examples?
Thanks.

**Comment by bagder** [comment]
This issue is not very clearly articulated but as we believe it is fixed and nobody has contradicted this suspicion, I'm closing it.
