### ISSUE TITLE
--doh-url tries to resolve an ip address in --proxy

### ISSUE THREAD

**Issue by itslukej** [curl/curl#10427]
### I did this
```
$ curl --doh-url https://cloudflare-dns.com/dns-query --proxy socks5://127.0.0.1:1080 --head -v https://google.com
```

```
* a DOH request is completed, 0 to go
* DOH: Bad RCODE type A for 127.0.0.1
* DOH: Bad RCODE type AAAA for 127.0.0.1
* Closing connection 0
curl: (6) Couldn't resolve host name
```
### I expected the following

DOH should not attempt to resolve the socks proxy ip address (127.0.0.1), it does not need resolving.

### curl/libcurl version

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux - 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jay** [comment]
I can reproduce this in 7.68.0 but not later versions, so this is probably a bug that was fixed at some point. Please try the latest version and confirm it works for you.

**Comment by bagder** [comment]
We believe this is fixed already.
