### ISSUE TITLE
Please support "--compressed" in the Openwrt Version of curl

### ISSUE THREAD

**Issue by chuyueye** [curl/curl#10425]
### I did this
curl --compressed
### I expected the following
get response
### curl/libcurl version
7.86
[curl -V output]
curl 7.86.0 (aarch64-openwrt-linux-gnu) libcurl/7.86.0 mbedTLS/2.28.2 nghttp2/1.44.0
Release-Date: 2022-10-26
Protocols: file ftp ftps http https mqtt 
Features: alt-svc HSTS HTTP2 IPv6 Largefile SSL threadsafe
### operating system
openwrt (kernel 5.10.161,branch 01.10.2023 by Kiddin)

Linux OpenWrt 5.10.161 #0 SMP Sat Jan 7 20:00:16 2023 aarch64 GNU/Linux

**Comment by chuyueye** [comment]
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information

**Comment by chuyueye** [comment]
I am using " n lts ",and here is the result.
I am wondering why this version of curl can not support "--compressed".
Should I install another version of curl to make "n lts " succeed?

**Comment by bagder** [comment]
curl supports it fine, you just need to make sure that the version you use was built with it enabled.

Ask the person/team that provides your binary.

**Comment by jay** [comment]
Indeed, this is not a curl bug.
