### ISSUE TITLE
Incorrect format %zu for curl_off_t in ws.c

### ISSUE THREAD

**Issue by mikeduglas** [curl/curl#10439]
### I did this

in ws.c there are several calls of infof() function. For curl_off_t variables %zu format is used which breaks the output. %llu format works well, at least here in Visual Studio 2022, win32 platform.

### curl/libcurl version

curl 7.87.1-DEV (i386-pc-win32) libcurl/7.87.1-DEV Schannel WinIDN

### operating system

Windows 11
Visual Strudio 2022

**Comment by bagder** [comment]
I believe `%Ou` is the correct one for our own printf implementation:

https://github.com/curl/curl/blob/12e9186fc465b09487f4a28416949a3e5adda038/lib/mprintf.c#L360-L366

**Comment by mikeduglas** [comment]
I confirm that %Ou works as expected.
