### ISSUE TITLE
Missing CurlSymbolHiding cmake in distribution

### ISSUE THREAD

**Issue by m0ppers** [curl/curl#1043]
### I did this
Downloaded official release and tried adding it as a third-party dependency via cmake.

### I expected the following

it works

### curl/libcurl version

7.50.3

### Description

I downloaded the distribution here:

https://curl.haxx.se/download.html

But these archives do not contain a file that was recently introduced (and which is referenced from the cmake stuff): 

https://github.com/curl/curl/blob/master/CMake/CurlSymbolHiding.cmake

Using the releases tab on github the file seems to be there.

**Comment by bagder** [comment]
Yeps the one on github has it because that's just all files in git using the  tag while the tarballs are built with the maketgz script. This bug was fixed already in commit 82279c82c8d
