### ISSUE TITLE
build warning in old version of visual studio

### ISSUE THREAD

**Issue by jay** [curl/curl#10449]
build warning in old version of visual studio, in [cf_h2_send](https://github.com/curl/curl/blob/3de3ea6a646687de2bf4154ce647485a84e1c6f9/lib/http2.c#L1961) -1 is assigned to a size_t in a bunch of places, eg `len = -1`

..\..\..\..\lib\http2.c(1978): warning C4245: '=' : conversion from 'int' to 'size_t', signed/unsigned mismatch

I'm using a pre generated build configuration from the projects directory with enabled http2 added. Possibly needs `ssize_t sent` or I can just ignore it. I notice none of the CI builds show this warning.

@icing

**Comment by icing** [comment]
Indeed, that does not look sound. I'll add a `ssize_t` for the return value.

**Comment by icing** [comment]
Should be addressed in #10450.
