### ISSUE TITLE
7.50.3 is shown as 7.51.0

### ISSUE THREAD

**Issue by peterlaser** [curl/curl#1044]
### I did this

Build the latest version libcurl 7.50.3 

### I expected the following version
7.50.3

### actual curl/libcurl version
7.51.0

please see screenshots

![git](https://cloud.githubusercontent.com/assets/11938491/18979041/4689db40-86fa-11e6-9dac-a10524724c9e.jpg)
![7 51](https://cloud.githubusercontent.com/assets/11938491/18979042/473a2842-86fa-11e6-8507-36da7507bc80.PNG)

**Comment by jay** [comment]
Yeah the plan was to go from 7.50.2 to 7.51.0 but in the meantime there was a security issue so a patch release was put out, 7.50.3. Since you're building from the repo that's not unexpected.

**Comment by peterlaser** [comment]
Hi jay,
Will curl dev fix the issue?  What repo is expected? Thanks.

**Comment by bagder** [comment]
The repo is for curl development and for getting the source files from the tagged moment we did the release.

The only official release packages are the tarballs identified at https://curl.haxx.se/. They're also the only signed ones.

You can build the exact same source code from the code in git, but if you want the exact same contents as the tarballs you need to run `./buildconf` and then make a release archive with `./maketgz 1.2.3` as some files are generated and put into the tarball at release time. We don't put generated files in git.

**Comment by toast12** [comment]
Thanks. Same question as in c-ares forum:

We use git repo for our internal builds. So if I want to fix this internally, what is the most sustainable approach? I read in your libcurl forum that you run a build configuration utility. If I run it, will that fix this issue?

**Comment by toast12** [comment]
oops sorry, wrong forum
