### ISSUE TITLE
CURLOPT_CONNECTTIMEOUT slows down a connection

### ISSUE THREAD

**Issue by AntonBobylev** [curl/curl#10454]
### I did this

```
<?php

$c = curl_init();
$pipe = initPipe();

curl_setopt($c, CURLOPT_URL, "sftp://my_login:my_password@my_host:55555/");
curl_setopt($c, CURLOPT_FILE, $pipe);
curl_setopt($c, CURLOPT_CONNECTTIMEOUT, 90);
curl_setopt($c, CURLOPT_UPLOAD, false);
curl_setopt($c, CURLOPT_QUOTE, []);
curl_setopt($c, CURLOPT_HEADERFUNCTION, false);

$result = curl_exec($c);

if ($result === false) {
    echo "<pre style='color: red'>failed</pre>";
    return;
}

echo "<pre style='color: #00ef00'>success</pre>";

curl_close($c);


function initPipe()
{
    $pipe = fopen("php://temp", "rw");

    if ($pipe === false) {
        echo "<pre style='color: red'>failed to initialize pipe</pre>";
    }

    return $pipe;
}
```

### I expected the following

Fast connection.

### I've got the following

Very slow connection. I only wanted to connect to sftp but it takes about 14 sec

### BUT!

When I paste CURLOPT_CONNECTTIMEOUT 5. It connects about 5 sec.
If I paste 3 - 3 sec to connect.
If I paste 2 - 2 sec to connect.
If I paste 1 - failed to connect (I know why, there's too small value).
If I paste 0 - about 2.5 sec to connect.
If I paste 90 - it connects about 14 sec!

### curl/libcurl version

```
curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
Release-Date: 2022-05-13
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
```

### operating system

Windows 10 x64 Pro 22H2 19045.2486

### here is a problem in the video
https://user-images.githubusercontent.com/25329821/217819491-cb53eba8-d25c-4691-a89d-47916715d401.mp4

"таймаут" - means timeout.
"сек" - means seconds.

Please tell me is it my fault? Am I doing smth wrong?

**Comment by bagder** [comment]
Can you reproduce this with the command line tool? If so, against a public URL?

It would possibly be interesting to see the output if you add `-v --trace-time` to the command line.

**Comment by AntonBobylev** [comment]
Unfortunately I cannot do that, CMD tells me next:
`Warning: Couldn't find a known_hosts file!curl: (1) Protocol "sftp" not supported or disabled in libcurl`

**Comment by bagder** [comment]
The curl version you show above seems to be the tool's version, not the version of libcurl that you run in PHP. So which libcurl version are you using?

**Comment by AntonBobylev** [comment]
Oh, how can I find it?

**Comment by bagder** [comment]
https://stackoverflow.com/questions/26777200/php-print-version-number-of-curl

**Comment by AntonBobylev** [comment]
7.61.1

**Comment by AntonBobylev** [comment]
Oh, one more additional:
I use Windows and this bug fires on my computer.
My colleague uses MacOS, this bug doesn't fire on his computer.
I think Windows is acting up

**Comment by bagder** [comment]
Presumably he doesn't use the same libcurl version either...

I would strongly recommend you get a more modern version as a first step. If the problem persists then as well, then I would ask for a verbose output, but I don't know how you get one using PHP. 

Also, as you use SFTP you also have an SSH library in use in there that is relevant for this, so do make an effort to make sure that is also not one out of many years ago.

**Comment by AntonBobylev** [comment]
I didn't understand you about:
> I don't know how you get one using PHP

For now I don't send any data and do not use anything. 
I'm just trying to connect. This is like ping to SFTP server and it "pings" with the different time depends on CURLOPT_CONNECTTIMEOUT.
If I remove "CURLOPT_CONNECTTIMEOUT" option it will connect much faster: 14sec -> 2 sec

<br>

I don't think they bound with each other, aren't they?
> Presumably he doesn't use the same libcurl version either...

**Comment by bagder** [comment]
I'm talking about the verbose output, like the tool outputs with `-v --trace-time`.

> I don't think this is a libcurl version issue

Based on what?

**Comment by AntonBobylev** [comment]
Alright, how can I update libcurl, help me please?

**Comment by bagder** [comment]
I can't. You're using libcurl as a component within some product and I have no insights into how that has been done and I also don't use Windows myself. I don't know how you can update libcurl in that for yourself.

I  think you should upgrade your PHP stack to the latest release and insist that whoever provides that should ship something in the late 7.8X series.

**Comment by AntonBobylev** [comment]
Okay, I got you, thanks for your feedback!
