### ISSUE TITLE
The switch «clobber» has three positions

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10459]
0) Prepare file with name «AutoHotkey_1.1.36.02_setup.exe» (NOT «ahk-install.exe»):
`Echo.>AutoHotkey_1.1.36.02_setup.exe & Dir /B`
AutoHotkey_1.1.36.02_setup.exe

1) `curl.exe -J -O "https://www.autohotkey.com/download/ahk-install.exe"`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to open the file AutoHotkey_1.1.36.02_setup.exe: File exists
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (23) Failed writing header

2) `curl.exe -J -O "https://www.autohotkey.com/download/ahk-install.exe" --clobber`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 3269k    0 30056    0     0   4327      0  0:12:53  0:00:06  0:12:47  6096^C

3) `curl.exe -J -O "https://www.autohotkey.com/download/ahk-install.exe" --no-clobber`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 3269k    0  6268    0     0   1796      0  0:31:04  0:00:03  0:31:01  1800^C

P.S.  What means the phrase «even if -J, --remote-header-name or -J is specified» in manual?  Lines №№2702-2703.

**Comment by dfandrich** [comment]
This is how the option is documented. No option avoids clobbering an existing file, `--clobber` allows file clobbering, and `--no-clobber` does file renaming instead of clobbering.

The issue with the extra `-J` in the manual looks like a bug in the manual generation code. I've opened #10461 on that.
