### ISSUE TITLE
Issue while building curl with ngtcp2 + nghttp3

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#10468]
Hi @bagder 

while trying to create curl with ngtcp2 and nghttp2,below error is seen

make[2]: Entering directory '/src/curl/lib'
  CC       vquic/libcurl_la-curl_ngtcp2.lo
vquic/curl_ngtcp2.c: In function ‘quic_settings’:
vquic/curl_ngtcp2.c:234:26: error: ‘NGTCP2_DEFAULT_HANDSHAKE_TIMEOUT’ undeclared (first use in this function); did you mean ‘NGTCP2_ERR_HANDSHAKE_TIMEOUT’?
  234 |   s->handshake_timeout = NGTCP2_DEFAULT_HANDSHAKE_TIMEOUT;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          NGTCP2_ERR_HANDSHAKE_TIMEOUT
vquic/curl_ngtcp2.c:234:26: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:3211: vquic/libcurl_la-curl_ngtcp2.lo] Error 1
make[2]: Leaving directory '/src/curl/lib'

After chaging to vquic/curl_ngtcp2.c  curl ran sucessfully

Expected to raise and PR and change

root@ubuntu:/src/curl# curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Ubuntu
Linux ubuntu 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by icing** [comment]
The definition of `NGTCP2_DEFAULT_HANDSHAKE_TIMEOUT` was added to ngtcp2 on 2021-12-16.

What version of ngtcp2 are you trying to build with?

**Comment by vszakats** [comment]
It's deleted in the latest master, going in effect with the next ngtcp2 release. There is more under the linked PR.

**Comment by Karthikdasari0423** [comment]
> The definition of `NGTCP2_DEFAULT_HANDSHAKE_TIMEOUT` was added to ngtcp2 on 2021-12-16.
> 
> What version of ngtcp2 are you trying to build with?

I always clone the ngtcp2 and will not use any branch name or tags or relesed versions

**Comment by icing** [comment]
I will update our ngtcp2 versions we build and CI with and remove use of that constant.

**Comment by bagder** [comment]
Fixed via #10474
