### ISSUE TITLE
Passing signed integers to the `<ctype.h>` functions

### ISSUE THREAD

**Issue by emilengler** [curl/curl#10488]
The cURL source code passes a signed char to the functions defined in `<ctype.h>` (or wrappers thereof) at various places, which in fact is undefined behavior:

> The argument c must be EOF or representable as an unsigned char; otherwise, the result is undefined.

**Comment by bagder** [comment]
Examples?

**Comment by emilengler** [comment]
https://github.com/curl/curl/blob/4858e7af1c741df997d417d695467717bc9c5a5b/lib/imap.c#L1895

**Comment by bagder** [comment]
You mean the macro we provide  in `lib/curl_ctype.h` ? That's A) not `<ctype.h>` and B) not restricted to the same conditions (as you can see).
