### ISSUE TITLE
--version followed by --no-version does not turn off version output

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10490]
### I did this
`curl.exe --version --no-version "https://curl.se/"`
### I expected the following
Какой-нибудь глюк типа «not-a-bug» (#10459 и другие).  Иначе не стал бы время тратить на такую примитивную проверку.
«Верной дорогой идёте, товарищи!»©
### curl/libcurl version
7.87.0
[curl -V output]
curl 7.87.0 (x86_64-w64-mingw32) libcurl/7.87.0 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.51.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows

**Comment by jay** [comment]
Please tell us in English. I think you are saying you expect [--version](https://curl.se/docs/manpage.html#-V) followed by --no-version to turn off version output? The code says there is not supposed to be output for --no-version, but if --version was already specified it's too late because the code is going to show the version output and not parse --no-version. I'm tempted to leave this as is.

https://github.com/curl/curl/blob/7ce140ba97de1bf3e27299a72b0cc229c9e1364e/src/tool_getparam.c#L2353-L2356

**Comment by jzakrzewski** [comment]
In many tools specifying "-V" / "--version" causes complete different code path that disregards any other parameter and just shows the version. So I think it's OK how it it.

**Comment by bagder** [comment]
I don't think this is a bug.

**Comment by u20221022** [comment]
«Disable it again with --no-version.»(©`curl --manual`)

> I don't think this is a bug.

Me too. I think it is a lie.

**Comment by bagder** [comment]
It would help us if you actually explained what you talk about.

I now assume you talk about text in the curl man page that says `--no-version`works. It does indeed, because it is automatically added because how the option is said to work: `Multi: boolean`.

**Comment by u20221022** [comment]
Sorry, I do not know English well and I do not quite understand you (in particular: «Multi: boolean»).

Binary options or not:
--version/--no-version
--manual/--no-manual
--help/--no-help

Correct the manual, please.

**Comment by u20221022** [comment]
What about this:
`curl.exe -I --silent --no-silent "htps://curl.se/"`
`curl.exe -I --no-silent --silent "htps://curl.se/"`

«So I think it's OK how it it.»(©jzakrzewski)
