### ISSUE TITLE
Strange behaviour when (incorrectly) trying to mix PUT and POST request

### ISSUE THREAD

**Issue by cmeis** [curl/curl#10499]
### I did this

(Wrong) call to an HTTP URL with curl, making it mix PUT and POST by using `-d "messagetext"` (implying a POST request) and `-T <filename>` (implying a PUT request).

### I expected the following

Some kind of "correct" error handling, as this seems like an obvious error.

### What happens

curl is sending the whole body, but seems to cap the uploaded file to the length of the body.
So when doing a `curl -d "1234567890" -T "somebigfile.jpg"` I end up with the file being cut after 10 bytes (as "1234567890" is 10 bytes long).

### curl/libcurl version

curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Linux dosenfisch 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Thu Jan 12 10:05:00 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cmeis** [comment]
Ok, thanks for pointing out.
Unfortunately on RHEL 8 and even the current 9 (which ships curl 7.76.1) there's no warning about that.
But that's that drawback of a conservative distro like RHEL.

Do you have a version number handy where this better warning was introduced?
I didn't find anything in the changelog at first glance.

**Comment by bagder** [comment]
commit 01a1697a7, shipped in 7.83.0 (via #8715)
