### ISSUE TITLE
--limit-rate 25B as fast as 25M

### ISSUE THREAD

**Issue by jidanni** [curl/curl#10503]
This only goes slow about one out of six times I tried it:
curl --limit-rate 25B example.com example.net example.org
curl 7.87.0 Debian
Man page says
>  averaging over a period  of  multiple  seconds.

But I tried it for much larger examples too. Same problem.

Maybe it is talking about "During a single file", thus multiple small files
will always be too fast... OK mention that on the man page.

But wait, 25B was still ignored for each single file above.

Same problem for --rate,
curl --rate 1/m example.com example.net example.org
completes just as fast (1 second) as if I didn't use --rate 1/m.

```
# uname -a
Linux jidanni7 6.1.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.11-1 (2023-02-09) x86_64 GNU/Linux
```

**Comment by dfandrich** [comment]
Are those the only sites you see this with? Those URLs each send approximately
1 packet worth of data. There's not much that can be done to limit the rate of
a single packet. Rate limiting averages the rate over seconds, not
microseconds.

**Comment by bagder** [comment]
As far as I can see, this feature works as intended. As stated in the man page;

> The rate limiting logic works on averaging the transfer speed to no more than the set threshold over a period of multiple seconds.

What exactly do you think the man page should include that it does not already?

**Comment by jidanni** [comment]
I didn't want to hammer Wikimedia.
I tried every switch I could.
But when getting hundreds of ~1KB files,

```
url = "https://commons.wikimedia.org/w/index.php?title=File:Metal_Beach_Hazard_2_Lake_Michigan.jpg&action=raw"
output = "Metal_Beach_Hazard_2_Lake_Michigan.jpg.txt"

url = "https://commons.wikimedia.org/w/index.php?title=File:Metal_Beach_Hazard_Lake_Michigan.jpg&action=raw"
output = "Metal_Beach_Hazard_Lake_Michigan.jpg.txt"

url = "https://commons.wikimedia.org/w/index.php?title=File:Inverted_stop_sign_Illinois.jpg&action=raw"
output = "Inverted_stop_sign_Illinois.jpg.txt"

...
```
no switch I tried did anything.

So it was always expected that the user was downloading big files,
but nobody ever expected one would download lots of little files,
and still want to rate limit, apparently.

**Comment by bagder** [comment]
> no switch I tried did anything.

That's not helpful. You ask for our help, the **least** you can do is to be friendly and provide proper answers. You did not try every switch and all options did not do nothing. Clearly you managed to download stuff.

The rate limiting is documented and designed to even out data transfers over seconds.

Given your explanation, you would rather want to use the `--rate` option (in addition). (Although that is broken in 7.87.0 specifically)

**Comment by jidanni** [comment]
Yes, --rate was the first I tried.

I have an idea, implement a simple
--rest-between-fetches '<time unit>'

- It will be available if one of the more complicated methods fails.
- It is a simple alternative to "curl; sleep; curl; sleep"

**Comment by bagder** [comment]
With `--rate` present I don't see we why we need to add that.

**Comment by jidanni** [comment]
As a "backup emergency brake, in case the main brakes fail." (As happened in 7.87.)
I mean sure, bugs can always be fixed in the next version.
But as we saw, there was no way left to slow the car down if one of them failed.
So just like cars, it is always best to have a main brake, and an emergency brake.
If you think that has any merit, reopen this issue. I'll close it now first. Thanks.

**Comment by jidanni** [comment]
Another interesting concept would be allowing sleeps in a config file:
```
url = "https:
output = "Dea

sleep 2

url = "https:
output = "Ana

sleep 7

url = "https:
output = "San
```

**Comment by dfandrich** [comment]
You can already do basically that by interspersing requests to a slow server,
like https://httpstat.us/200?sleep=7000

**Comment by jidanni** [comment]
@dfandrich thanks but I am trying to be environmentally friendly. At least not doing something that accesses the network just to sleep.
