### ISSUE TITLE
Curl error: conflicting types

### ISSUE THREAD

**Issue by Bruno-glintt** [curl/curl#10502]
### I did this
Im trying to do docker-compose up of my project and im getting an error: 

....
CC libcurl_la-openssl.lo
vtls/openssl.c:267:23: error: conflicting types for 'errcode_t'
typedef unsigned long errcode_t;
^
In file included from /usr/include/krb5/krb5.h:8506:0,
from /usr/include/krb5.h:8,
from /usr/include/openssl/kssl.h:73,
from /usr/include/openssl/ssl.h:165,
from vtls/openssl.h:34,
from vtls/openssl.c:53:
/usr/include/et/com_err.h:22:14: note: previous declaration of 'errcode_t' was here
typedef long errcode_t;
^
make[2]: *** [libcurl_la-openssl.lo] Error 1
make[2]: Leaving directory /var/tmp/curl/lib' make[1]: *** [all] Error 2 make[1]: Leaving directory /var/tmp/curl/lib'
make: *** [all-recursive] Error 1
ERROR: Service 'generator' failed to build : The command '/bin/sh -c cd /var/tmp && git clone https://github.com/bagder/curl.git && cd curl && ./buildconf && ./configure --with-nghttp2=/usr/local --with-openssl && make && make install && \cp -f src/curl /usr/local/bin/curl && \cp -f src/curl /usr/bin/curl' returned a non-zero code: 2

### I expected the following

i think that's related with this commit https://github.com/curl/curl/commit/fc10d860112cfb9057b620fae3e33368008ffdae

### curl/libcurl version

curl 7.81.0

### operating system

Ubuntu 22.04 LTS

**Comment by bagder** [comment]
See #10500
