### ISSUE TITLE
7.87.0 cannot connect to webservice, previous versions can

### ISSUE THREAD

**Issue by kia-i20** [curl/curl#10506]
I was building/upgrading from 7.70 to.... 7.71, .... 7.87

I did preliminar tests for all versions, connecting to company provided webservice located on Amazon. All versions worked up to 7.86. Then 7.87 version is not able to connect to the webservice. So for time being we stay on 7.86.

curl 7.87

### operating system

Windows 10
macos 12.6.2, but version not important

**Comment by bagder** [comment]
Please provide (much more) details. Like curl -v output.

**Comment by calvin2021y** [comment]
> 

I guess the server is use https (I use 7.87 connect some https site keep get timeout).   try master branch.

**Comment by kia-i20** [comment]
Right; the service in amazon is using https only. The client application is running on mac and windows.
We had to catch up coming from version 7.70; and built / integrated all subsequent versions, now using 7.86 as working. 
Then 7.87 didn't. 
It will take some time to setup/build 7.87 again to reproduce and report back; but i will do.

**Comment by bagder** [comment]
Presumed to be fixed already.
