### ISSUE TITLE
curl adding unneeded query strings in the digest authorization header uri

### ISSUE THREAD

**Issue by mirzaprangon** [curl/curl#10505]
I am trying to use curl for a http request. I have to use it behind proxy server, and the remote host uses digest authentication.
I am using the following curl command.

But I get 400 bad request from server.
After investigating, I can see that curl is adding any query strings that it gets from proxy server to the authorizatoion header uri.

### I did this
`curl -x "http://proxy_username:proxy_pass@proxyIp.xxx.xxx.xxx:8080" -L -X GET "https://remote-host.something.com:443/tomcat_servlet/UploadServlet" --digest -u digest_auth_user:digest_auth_pass -v -k`

Output of curl is as follows
```
*   Trying proxyIp.xxx.xxx.xxx:8080...
* Connected to proxyIp.xxx.xxx.xxx (proxyIp.xxx.xxx.xxx) port 8080 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to remote-host.something.com:443
* Proxy auth using Basic with user 'proxy_username'
* Server auth using Digest with user 'digest_auth_user'
> CONNECT remote-host.something.com:443 HTTP/1.1
> Host: remote-host.something.com:443
> Proxy-Authorization: Basic NzA3NDcwNzg6VUJtV3QxMmFKTGY5
> User-Agent: curl/7.83.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Via:HTTP/1.1 s_proxy_nrt
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
* Server auth using Digest with user 'digest_auth_user'
> GET /tomcat_servlet/UploadServlet HTTP/1.1
> Host: remote-host.something.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Server: Cisco Umbrella
< Date: Tue, 14 Feb 2023 02:52:03 GMT
< Content-Type: text/html
< Content-Length: 190
< Connection: keep-alive
< Set-Cookie: swg_https_a2bc=1; Path=/; Expires=Tue, 14-Feb-23 03:02:03 GMT; domain=remote-host.something.com; SameSite=None; Secure
< Location: https://remote-host.something.com/tomcat_servlet/UploadServlet?swg_a2bc=1
< Via: HTTP/1.1 s_proxy_nrt
<
* Ignoring the response-body
* Connection #0 to host proxyIp.xxx.xxx.xxx left intact
* Issue another request to this URL: 'https://remote-host.something.com/tomcat_servlet/UploadServlet?swg_a2bc=1'
* Found bundle for host: 0x1a0ed47d970 [serially]
* Re-using existing connection #0 with proxy proxyIp.xxx.xxx.xxx
* Connected to proxyIp.xxx.xxx.xxx (proxyIp.xxx.xxx.xxx) port 8080 (#0)
* Server auth using Digest with user 'digest_auth_user'
> GET /tomcat_servlet/UploadServlet?swg_a2bc=1 HTTP/1.1
> Host: remote-host.something.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Tue, 14 Feb 2023 02:52:03 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 381
< Connection: keep-alive
< Server: Apache/2.4.48 (Win64) OpenSSL/1.1.1k
< WWW-Authenticate: Digest realm="https_transfer", nonce="redacted", algorithm=MD5, qop="auth"
< Via: HTTP/1.1 m_proxy_nrt
<
* Ignoring the response-body
* Connection #0 to host proxyIp.xxx.xxx.xxx left intact
* Issue another request to this URL: 'https://remote-host.something.com/tomcat_servlet/UploadServlet?swg_a2bc=1'
* Found bundle for host: 0x1a0ed47d970 [serially]
* Re-using existing connection #0 with proxy proxyIp.xxx.xxx.xxx
* Connected to proxyIp.xxx.xxx.xxx (proxyIp.xxx.xxx.xxx) port 8080 (#0)
* Server auth using Digest with user 'digest_auth_user'
> GET /tomcat_servlet/UploadServlet?swg_a2bc=1 HTTP/1.1
> Host: remote-host.something.com
> Authorization: Digest username="digest_auth_user",realm="https_transfer",nonce="redacted",uri="/tomcat_servlet/UploadServlet?swg_a2bc=1",cnonce="redacted",nc=00000001,algorithm=MD5,response="redacted",qop="redacted"
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Date: Tue, 14 Feb 2023 02:52:03 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 226
< Connection: keep-alive
< Server: Apache/2.4.48 (Win64) OpenSSL/1.1.1k
< Via: HTTP/1.1 m_proxy_nrt
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
* Connection #0 to host proxyIp.xxx.xxx.xxx left intact 
```
Indeed, cURL is adding some query it is getting from the proxy server in the authorization header.

### I expected the following
Can properly finish the http request. 
### curl/libcurl version

curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
Release-Date: 2022-05-13
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets

### operating system
Windows 10

**Comment by mirzaprangon** [comment]
Just tried with curl 7.87.0, which have the same problem.

**Comment by bagder** [comment]
> Indeed, cURL is adding some query it is getting from the proxy server in the authorization header.

Can you elaborate? How do you draw this conclusion?

**Comment by mirzaprangon** [comment]
@bagder 
Sorry if I am wrong, I am not that versed in http.

In the Authorization header of curl from the `-v` output, I can see the following
```
Authorization: Digest username="digest_auth_user",realm="https_transfer",nonce="redacted",uri="/tomcat_servlet/UploadServlet?swg_a2bc=1",cnonce="redacted",nc=00000001,algorithm=MD5,response="redacted",qop="redacted"
```
Here, the uri is `/tomcat_servlet/UploadServlet?swg_a2bc=1`, whereas the original uri was `/tomcat_servlet/UploadServlet`.

**Comment by jay** [comment]
there's a redirect to that location

> Location: https://remote-host.something.com/tomcat_servlet/UploadServlet?swg_a2bc=1

**Comment by mirzaprangon** [comment]
Yes there is a redirect to that location. The thing is I get 400 if I use curl, but httpie actually handles the request without problem. So I don't know what is the problem.

**Comment by mirzaprangon** [comment]
I just checked the forensic logs of httpd. httpie does not add the `swg_a2bc=1` in the authorization uri.

**Comment by jay** [comment]
hm. well, the digest RFC [says](https://www.rfc-editor.org/rfc/rfc7616#section-3.4) the uri should be the "[Effective Request URI](https://www.rfc-editor.org/rfc/rfc7230#section-5.5)" which says it should contain the query component. Unless I'm misunderstanding what is the effective request, because it seems to me if there's a redirect then that location is the effective request, but I can't find that anywhere.

**Comment by jzakrzewski** [comment]
Additionally:
> The authenticating server MUST assure that the resource designated by
   the "uri" parameter is the same as the resource specified in the
   Request-Line; if they are not, the server SHOULD return a 400 Bad
   Request error.  (Since this may be a symptom of an attack, server
   implementers may want to consider logging such errors.)  The purpose
   of duplicating information from the request URL in this field is to
   deal with the possibility that an intermediate proxy may alter the
   client's Request-Line.  This altered (but presumably semantically
   equivalent) request would not result in the same digest as that
   calculated by the client.

Which for me means that httpie either ignores the redirect completely (sends the request to the original URL), or sends an invalid (according to specs) authorization request.

**Comment by bagder** [comment]
Sorry, but I don't see an error by curl there. curl uses the redirect's URL and I don't see how it is curl's fault that the server gives you a 400 for this.

**Comment by mirzaprangon** [comment]
In the rfc, about the [request target of absolute-form](https://www.rfc-editor.org/rfc/rfc7230#section-5.3.2), the URI should be the absolute URI. Is it the URI to be used when using proxy?

> When making a request to a proxy, other than a CONNECT or server-wide
   OPTIONS request (as detailed below), a client MUST send the target
   URI in absolute-form as the request-target.
              absolute-form  = absolute-URI
   The proxy is requested to either service that request from a valid
   cache, if possible, or make the same request on the client's behalf
   to either the next inbound proxy server or directly to the origin
   server indicated by the request-target.  Requirements on such
   "forwarding" of messages are defined in [Section 5.7](https://www.rfc-editor.org/rfc/rfc7230#section-5.7).

**Comment by jay** [comment]
> When making a request to a proxy, other than a CONNECT

your request is done through an HTTP tunnel (CONNECT) refer to the verbose output

> CONNECT remote-host.something.com:443 HTTP/1.1

**Comment by mirzaprangon** [comment]
Thanks for your comment.

I captured packets from curl and httpie. Surprisingly the proxy server does not redirect httpie, but it does redirect curl once. The headers from the first httpie request is-
```
POST /httpserver_34/UploadServlet HTTP/1.1
Host: veri-spc1.extope.com
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 0
User-Agent: HTTPie/3.2.1
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Extope-Compression: true
```
The server responses with 401, and the digest authentication goes smoothly.


Whereas curl sends the first post as follows:
```
POST /httpserver_34/UploadServlet HTTP/1.1
Host: veri-spc1.extope.com
User-Agent: curl/7.81.0
Accept: */*
ExTOPE-Compression:true
```
This request from curl gets redirected, and the proxy server adds weird query in the URI.

Any idea on why it is?

**Comment by jay** [comment]
Show the command you are using. Note -X is [usually unnecessary](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/) and not the right way to go about POSTing. Use [curl -d ""](https://curl.se/docs/manpage.html#-d) to send a POST with no content.

**Comment by mirzaprangon** [comment]
Using the below command
```bash
/curl.exe -L -x "http://proxy_user:proxy_password@proxy_server:proxy_port" -X POST "https://somehost.example.com/servlet/endpoint" --digest -u digest_user:digest_password -v -H "Compression:true" -F "testid/filename.txt/123456=@/98765"
```

**Comment by jay** [comment]
The POST you are making with curl is using multipart/form-data and the POST you are making with httpie is using application/x-www-form-urlencoded.

The first POST has a 0 content length for both, so no data is actually sent, instead curl/httpie is waiting for the 401 Authorization Required, then it will send digest authentication and the POST data in the next request.

> ```
> POST /httpserver_34/UploadServlet HTTP/1.1
> Host: veri-spc1.extope.com
> User-Agent: curl/7.81.0
> Accept: */*
> ExTOPE-Compression:true
> ```
> 
> This request from curl gets redirected, and the proxy server adds weird query in the URI.

curl does not send the `Content-Type: multipart/form-data` header in the first request like it would for `Content-Type: application/x-www-form-urlencoded`. I don't know the reasons for that, but it could the problem. @monnerat 

You could try sending form data using the latter type, use [-d](https://curl.se/docs/manpage.html#-d) instead of [-F](https://curl.se/docs/manpage.html#-F). If not that then it could be some other difference in headers that the server doesn't like.

**Comment by monnerat** [comment]
> curl does not send the Content-Type: multipart/form-data header in the first request like it would for Content-Type: application/x-www-form-urlencoded. I don't know the reasons for that, but it could the problem.

I don't think it is the problem, but a symptom: the request looks like a GET request disguised in a POST (no Content-Length/Content-Type, no Expect). I suspect the headers shown do not match the submitted command above. A confirmation of that is given by the different (ExTOPE-)Compression header name. If curl "thinks" it is submitting a get request, it won't process input data at all. We need less fuzzy and more consistent/strict info to perform a precise analysis. And first, **do suppress the -X option !**

In addition, we are checking too many different things here: a get request then a (forged) post, redirection or not, authentication, different content-type, etc.  IMO, the first thing to determine is why their is a redirection for curl and not for httpie.

**Comment by mirzaprangon** [comment]
Sorry for late reply.

I tried without adding the file using httpie, as the same request in curl (meaning without sending the file) was redirected. But as you can see from my first post, even the `GET` did not work with curl.

After having a heated conversation with out infrastructure admin (the proxy is cisco umbrella), for trying things I had the host registered in authentication exception list of proxy. Now without using authentication, the proxy server does not redirect the request. Might be something with proxy server, might be something with curl. I do not know.
For reference I will add the verbose output of curl without the proxy authentication. Request should still use proxy server, but without authentication. I am using `-X POST` because that's the way the client program sends the request.

```bash
curl.exe -L -x "http://proxy.server.com:8080" -X POST "https://remote-host.something.com/tomcat_servlet/UploadServlet" --digest -u digest_user:digest_pass -H "ExTOPE-Compression:true" -F "testid/test_file.txt/12345678=@C:/1676338975234" -v
*   Trying xxx.xxx.xxx.xxx:8080...
* Connected to proxy.server.com (xxx.xxx.xxx.xxx) port 8080 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to remote-host.something.com:443
* Server auth using Digest with user 'admin'
> CONNECT remote-host.something.com:443 HTTP/1.1
> Host: remote-host.something.com:443
> User-Agent: curl/7.87.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Via:HTTP/1.1 s_proxy_nrt
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: C:\curl-ca-bundle.crt
*  CApath: none
* [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=JP; ST=\U6771\U4EAC\U90FD; L=\U6E2F\U533A; O=\U682A\U5F0F\U4F1A\U793E\U3000\U65E5\U7ACB\U30CF\U30A4\U30C6\U30AF; CN=*.extope.com
*  start date: May 20 00:39:11 2022 GMT
*  expire date: Jun 12 14:59:00 2023 GMT
*  subjectAltName: host "remote-host.something.com" matched cert's "*.something.com"
*  issuer: C=JP; O=Cybertrust Japan Co., Ltd.; CN=Cybertrust Japan SureServer CA G4
*  SSL certificate verify ok.
* Server auth using Digest with user 'admin'
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /tomcat_servlet/UploadServlet HTTP/1.1
> Host: remote-host.something.com
> User-Agent: curl/7.87.0
> Accept: */*
> ExTOPE-Compression:true
> Content-Length: 0
>
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Wed, 08 Mar 2023 00:26:05 GMT
< Server: Apache/2.4.55 (Win64) OpenSSL/1.1.1s
< WWW-Authenticate: Digest realm="digest_realm", nonce="tR7dklj2BQA=99ec56f9d0fc5aa25de064e6d18293290a7bb606", algorithm=MD5, qop="auth"
< Content-Length: 381
< Content-Type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host proxy.server.com left intact
* Issue another request to this URL: 'https://remote-host.something.com/tomcat_servlet/UploadServlet'
* Found bundle for host: 0x220933d8110 [serially]
* Can not multiplex, even if we wanted to
* Re-using existing connection #0 with proxy proxy.server.com
* Server auth using Digest with user 'admin'
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /tomcat_servlet/UploadServlet HTTP/1.1
> Host: remote-host.something.com
> Authorization: Digest username="digest_user",realm="digest_realm",nonce="tR7dklj2BQA=99ec56f9d0fc5aa25de064e6d18293290a7bb606",uri="/tomcat_servlet/UploadServlet",cnonce="29f8cb8b9a4c97490412bde42d3e22e4",nc=00000001,algorithm=MD5,response="389a2244dba3fbf820fe4544c8302cfe",qop="auth"
> User-Agent: curl/7.87.0
> Accept: */*
> ExTOPE-Compression:true
> Content-Length: 417
> Content-Type: multipart/form-data; boundary=------------------------7d5eea1bfd7ed93e
>
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):
* We are completely uploaded and fine
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200
< Date: Wed, 08 Mar 2023 00:26:05 GMT
< Server: Apache/2.4.55 (Win64) OpenSSL/1.1.1s
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 1
<
0* Connection #0 to host proxy.server.com left intact
```
Any clue here? Nothing jumps to me that is different for the first request. I want to get to the bottom of this. Reason being this program is part of a B2B platform, where different business/enterprise will have different proxy servers.

**Comment by monnerat** [comment]
This last listed request trace shows it succeeded: it did not issue an error and returned one data byte. We see it did not redirect.
>  I had the host registered in authentication exception list of proxy. 

I don't think this is your problem: the main point is the proxy connection is properly established in all cases. The same command as above should succeed with proxy authentication added. Your problem is on the **server** authentication.

From what I can decode above, the redirection is sent by the proxy, not the server. The proxy then acts as a "man in the middle" modifying messages and the digest authentication mechanism requested by the server is protected against this type of situation. Even if the proxy restores the original URL in the authorization header upon redirection, it will never be able to update the nonce accordingly, this is impossible unless it knows your password :-(
It is therefore mandatory to find the cause of the redirection and suppress it. From what I can read in the posted traces above, redirection occurred only when no `Content-Length` header as been sent in request (typically a GET request): this might be the problem. Keeping the `-X` option forces the request keyword, but will never turn a GET request structure into a POST one (and obfuscates the trace, BTW).
Else you should request help from Cisco support: I googled to find references to `svg_a2bc` and did not find any clear explanation about it: I think this is specific to this proxy, Maybe they have a relevant technical explanation. See also https://gist.github.com/aont/1e5fb48d9183c5a9ab5abd507f294797 that unfortunately lacks of comments but gave me some hints for the current reply.
I'm sure the problem does not come from curl. However if we had info about the proxy behavior, we possibly might find a workaround with additional parameters.
