### ISSUE TITLE
Unable to perform Windows MSVC build with option `WITH_PREFIX`

### ISSUE THREAD

**Issue by Shempp** [curl/curl#10510]
### I did this

1. Downloaded Curl `7.87.0` (tried from here https://curl.se/download.html and from here https://github.com/curl/curl/releases/tag/curl-7_87_0)
2. Unpacked the archive to `C:\curl-7.87.0`
3. Ran the following commands (https://github.com/curl/curl/tree/master/winbuild):

```bat
cd C:\curl-7.87.0
cd winbuild
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" x86
nmake /f Makefile.vc mode=static WITH_PREFIX=C:\curl
```

I am getting `nmake` error:
```
Copying libs...
NMAKE : fatal error U1077: if : return code "0x1"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\nmake.exe" : return code "0x2"
Stop.
```

I also tried (and used different paths):
```bat
nmake /f Makefile.vc mode=static WITH_PREFIX=C:/curl
```
```bat
nmake /f Makefile.vc mode=static WITH_PREFIX="C:\curl"
```
```bat
nmake /f Makefile.vc mode=dll WITH_PREFIX=C:\curl
```
```bat
nmake /f Makefile.vc mode=static VC=16 WITH_PREFIX=C:/curl
```

Launch Developer Command Prompt for VS 2019 via shortcut. Behavior is the same everywhere.

### I expected the following

Successful Windows MSVC build with option `WITH_PREFIX`
 
### curl/libcurl version 

7.87.0

### operating system

Windows 10 22H2 10.0.19045.2486

**Comment by jay** [comment]
I don't know what those errors are or how to get their context. I can't reproduce. I was able to build and install 7.88.0 from the download page release source and also from repo source, using Visual Studio 2022 and 2010. I used the "x86 Native Tools Command Prompt for VS 2022".

**Comment by Shempp** [comment]
I found the cause of the problem: if the folder that was specified in `WITH_PREFIX` already exists (an empty folder in my case), then the error described above appears. If there is no folder, the build will run normally.

In my case the strange error was in this line:
```
@if exist $(LIB_DIROBJ)\$(LIB_NAME_STATIC) copy $(LIB_DIROBJ)\$(LIB_NAME_STATIC) $(DIRDIST)\lib\ /y >nul 2<&1
```

**Comment by jay** [comment]
> if the folder that was specified in `WITH_PREFIX` already exists (an empty folder in my case),

Ok that looks like a bug. I can reproduce but only with an empty folder.

**Comment by bagder** [comment]
Can someone who understands the problem provide a paragraph about ir to add to the docs? It does not seem like anyone is up to fixing it. (Whatever the problem is.)

**Comment by bagder** [comment]
I don't understand the issue. Nobody has provided an answer. It does not move. It needs a documentation entry somewhere, and we will add one when we have one. Until then this is just closed.
