### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by abhishekchaudhary** [curl/curl#1051]
Hi,
I am using curl multiple(curl_multi_add_handle) requests in a sidekiq job using a gem Curb and getting this segmentation fault error and cfp consistency error intermittently.

### curl/libcurl version

curl 7.19.7 (x86_64-unknown-linux-gnu) libcurl/7.19.7 NSS/3.12.7.0 zlib/1.2.3 libidn/1.18 libssh2/1.2.2

### operating system
 using VM Cent OS 6

### Web framework
Ruby on rails

**Comment by bagder** [comment]
That problem is most likely already fixed or has changed in behavior significantly since then. You're using a severely outdated version that is almost 7 years old. We have quite literally fixed **thousands** of bugs since.
