### ISSUE TITLE
--silent/--no-silent

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10535]
### I did this
0) `curl.exe --manual | FindStr /C:"Providing -s, --silent" /C:"--no-silent" /N`
4309:              Providing -s, --silent multiple times has no extra effect.  Dis-
4310:              able it again with --no-silent.
1) `curl.exe -I --silent --no-silent "htps://curl.se/"`
2) `curl.exe -I --no-silent --silent "htps://curl.se/"`
curl: (1) Protocol "htps" not supported or disabled in libcurl
### I expected the following
Какой-нибудь глюк типа «not-a-bug» (https://github.com/curl/curl/issues/10459 и другие). Иначе не стал бы время тратить на такую примитивную проверку.
«Верной дорогой идёте, товарищи!»©
### curl/libcurl version
7.88.0
[curl -V output]
curl 7.88.0 (x86_64-w64-mingw32) libcurl/7.88.0 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2023-02-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows

**Comment by Earnestly** [comment]
Possibly with this change `--silent` no longer appears to work when used in conjunction with `-Z, --parallel`:

What I see now:

```
$ curl -sZ example.com > /dev/null
dl% ul%  dled  uled  xfers  live total     current  left    speed
100 --   1256     0     1     0  --:--:-- --:--:-- --:--:--  8000
$
```

What is expected:

```
$ curl -sZ example.com > /dev/null
$
```
