### ISSUE TITLE
"Content-Disposition" header is ignored

### ISSUE THREAD

**Issue by roughtex** [curl/curl#10533]
Try to download `https://www.xyplorer.com/xyfc/download/file.php?id=2599` using `--remote-header-name` option. The file is saved to `file.php` despite `Content-Disposition` header presence.

### I did this

`curl.exe --remote-name --remote-header-name https://www.xyplorer.com/xyfc/download/file.php?id=2599`

### I expected the following

`MicrosoftTermCollection-TBXY (PT, RU).zip`

or at least

`MicrosoftTermCollection-TBXY%20%28PT%2C%20RU%29.zip`

### curl/libcurl version

curl 7.88.0

### operating system

Windows

**Comment by vszakats** [comment]
The relevant header is:
```
Content-Disposition: attachment; filename*=UTF-8''MicrosoftTermCollection-TBXY%20%28PT%2C%20RU%29.zip
```

Incidentally I just mentioned this exact issue earlier today in: https://github.com/curl/curl/discussions/10446#discussioncomment-4995045

**Comment by bagder** [comment]
Yeah, percent decoding this into a specific encoding is a pain.

**Comment by vszakats** [comment]
FWIW, my hack to resolve it was this (for UTF-8 only, bash, python and python lib-specific):
```
name="$(curl --fail --silent --show-error --head "${url}" \
  | grep -a -i '^Content-Disposition:' | cut -c 21- \
  | grep -a -i -o -E "filename\*=UTF-8''[A-Za-z0-9%_~\.-]+" | cut -c 18- | urldecode)"
name="$(basename "${name}")"
```
```python
#!/usr/bin/env python3

import sys
import urllib.parse as ul

sys.stdout.write(ul.unquote_plus(sys.stdin.read()))
```

I'm sure this can be improved/simplified quite a bit, but it did the job at the time.

**Comment by bagder** [comment]
This is now documented in the man page. I think we can close this issue now.
