### ISSUE TITLE
Unable detect OpenSSL while set host to arm-linux-gnueabi

### ISSUE THREAD

**Issue by Guilty39** [curl/curl#10546]
While I configure the cURL 7.88.0 source with: 

> ./configure --with-openssl

It works correctly. 

But if I set host to arm-linux-gnueabi, configure like these: 

> ./configure --with-openssl --host=arm-linux-gnueabi

> ./configure --with-openssl --host=arm-linux-gnueabi --target=arm-linux-gnueabi

> ./configure --with-openssl --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

I got an error: 

> configure: error: --with-openssl was given but OpenSSL could not be detected

Ubuntu version is 14.04.6, arm-linux-gnueabi-gcc version is 4.7.3, OpenSSL version is 1.0.1f.

What's the reason and how can I solve it? Please help me, Thanks.

**Comment by bagder** [comment]
When configure fails to do what you expected it to, for example to find the libraries you wanted it to find, then the standard next step is to open `config.log` in a text editor, search for the library/test that didn't go the way you expected and see what you can figure out based on that.

We've learned that this is a very effective way and reading this file often reveals details that can take you further in debugging your build/configure issue.

**Comment by dfandrich** [comment]
Do you have an ARM version of OpenSSL available? If so, then use PKG_CONFIG_PATH to point to its .pc file. If not, then the message is right—there's no ARM OpenSSL around to detect.

**Comment by Guilty39** [comment]
I make an ARM version of OpenSSL by openssl-1.1.1t, and try to set PKG_CONFIG_PATH like these:

> ./configure --with-openssl=/XXX/openssl-1.1.1t/arm_openssl_gnuea/ssl --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

> ./configure --with-openssl=/XXX/openssl-1.1.1t/arm_openssl_gnuea/lib/pkgconfig/libcrypto.pc --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

> ./configure --with-openssl=/XXX/openssl-1.1.1t/arm_openssl_gnuea/lib/pkgconfig/libssl.pc --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

> ./configure --with-openssl=/XXX/openssl-1.1.1t/arm_openssl_gnuea/lib/pkgconfig/openssl.pc --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

> ./configure --with-openssl=/XXX/openssl-1.1.1t/arm_openssl_gnuea/lib/pkgconfig --host=arm-linux-gnueabi --target=arm-linux-gnueabi CC=arm-linux-gnueabi-gcc

But I got errors like this :

> configure: error: XXX is a bad --with-openssl prefix!

Maby I use a wrong way to set PKG_CONFIG_PATH or set a wrong path?

**Comment by dfandrich** [comment]
Please read INSTALL.md. Those arguments aren't being set correctly.
PKG_CONFIG_PATH is an environment variable. --with-openssl is a configure
option. Both take a path to a directory, not a file. If using PKG_CONFIG_PATH,
it must be set to the directory holding openssl.pc. If using --with-openssl
with a path, the path must be the root of the OpenSSL installation directory.

**Comment by Guilty39** [comment]
I export PKG_CONFIG_PATH to environment, now it works correctly, thanks for your help.
