### ISSUE TITLE
RELEASE-NOTES in 7.88.0 downloads were labelled 7.87.1

### ISSUE THREAD

**Issue by BrianInglis** [curl/curl#10565]
### I did this
```
$ head curl-7.88.0-1.x86_64/src/curl-7.88.0/RELEASE-NOTES
curl and libcurl 7.87.1

 Public curl releases:         213
 Command line options:         250
 curl_easy_setopt() options:   302
 Public functions in libcurl:  91
 Contributors:                 2812

This release includes the following changes:
```
### I expected the following
`curl and libcurl 7.88.0
...`
git shows RELEASE-NOTES went from 7.87.1 to 7.88.1
It is unclear from the available documentation what changes and bug fixes apply to 7.88.0
### curl/libcurl version
curl 7.88.0 (x86_64-pc-cygwin) libcurl/7.88.0 OpenSSL/1.1.1s zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0 libgsasl/2.2.0
Release-Date: 2023-02-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system
CYGWIN_NT-10.0-19044 3.4.6-1.x86_64 2023-02-14 13:23 UTC x86_64 Cygwin
Microsoft Windows [Version 10.0.19044.2364]

**Comment by bagder** [comment]
Yes, but 7.88.0 has already been shipped so there is no way to fix this.

**Comment by BrianInglis** [comment]
Official 7.88.1 release is one way to deal with it - great by me! ;^>

**Comment by BrianInglis** [comment]
And `RELEASE-NOTES` git tree could be juggled to have `7.88.0` between for completeness ;^>
