### ISSUE TITLE
I miss a list of all "global options" in the man page

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10566]
### I did this
`curl.exe --manual | FindStr /C:"Global options" /C:"--fail-early." /N`
2686:              the  -:,  --next  instruction. Global options include -v, --ver-
2687:              bose, --trace, --trace-ascii and --fail-early.
### I expected the following
Full and clear list of global options in manual or (better) existence of distinctive prefixes in their names.
### curl/libcurl version
7.88.0
[curl -V output]
curl 7.88.0 (x86_64-w64-mingw32) libcurl/7.88.0 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2023-02-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows 10

**Comment by bagder** [comment]
This is not a bug. Feel free to help extend the documentation.

**Comment by u20221022** [comment]
> Feel free to help extend the documentation.

How?

**Comment by bagder** [comment]
> I can not know it better than the developers.

We're all developers. This is an open source project and everyone is encouraged to help out.

**Comment by u20221022** [comment]
> We're all developers. This is an open source project and everyone is encouraged to help out.

Specifically, how can I help?  I did create the list above.  And what?

**Comment by bagder** [comment]
You can write the docs and provide a pull-request.

The list is helpful, but we also need to figure out how and where to present that list. We should probably describe the concept of *global* vs *non-global* options in association with that list.

>  The structure of cURL options is very chaotic.

They have been gradually and continuously been developed and added over twenty-five years and we don't break existing behavior. It's a mighty difficult task.
