### ISSUE TITLE
curl_easy_perform block 1s with proxy on version 7.87

### ISSUE THREAD

**Issue by Xuhuajie-2021** [curl/curl#10581]
### I did this
I use curl_easy_perform function as what I did before.
the log shows curl_easy_perform  takes 1500ms while 1000ms on waiting for 'connect establish'
![image](https://user-images.githubusercontent.com/53515032/220335885-830946ea-0d4d-4895-8e70-d4732ce20bea.png)
but wireshare shows that 'connect establish' only takes 100ms 

![image](https://user-images.githubusercontent.com/53515032/220334883-cb67b8a3-847d-4501-9a6a-1fc4862ba16e.png)
And I found where it blocking
![image](https://user-images.githubusercontent.com/53515032/220336541-2e3d112c-7f46-4cd0-98a6-14ac3e44c99c.png)
But old version is ok (7.86)
PS. The Problem Only Occurs With Proxy.

### curl/libcurl version
7.87
[curl -V output]

### operating system
Windows 10

**Comment by bagder** [comment]
We believe this problem is already fixed in later versions. Try upgrading!

**Comment by Xuhuajie-2021** [comment]
I try 7.88, it's ok.🤣
What causes the problem ?

**Comment by bagder** [comment]
Here's the fix: 728400f875e845
