### ISSUE TITLE
some options can be used in .curlrc

### ISSUE THREAD

**Issue by u20221022** [curl/curl#10586]
### I did this
1) `curl.exe --manual | FindStr /C:"Specify a te" /C:"line  arguments " /C:"were provi" /C:".curlrc  " /C:"--no-disable." /N`
503:              Specify a text file to read curl  arguments  from.  The  command
504:              line  arguments  found  in the text file will be used as if they
505:              were provided on the command line.
571:              On Windows two filenames are checked per location:  .curlrc  and
1021:              Disable it again with --no-disable.

2) `Type .curlrc`
help
--help
-h "И вечный сбой!  Работа только снится."

manual
--manual
-M "Мужской вижу, а где женский?  Дискриминация!  Куда смотрят феминистки?"

version "Воистину, скрытые тайны зонтика."
--version
-V Фау

--next "А тут можно писать что угодно, лишь бы в кавычках?"
url = https://curl.se/
--output Nul

--next "Цирк уехал; в качестве клоунов остались разработчики глючной программы cURL."

3) `curl.exe`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8313  100  8313    0     0   5319      0  0:00:01  0:00:01 --:--:--  5345
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

4) `curl.exe --disable`
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

5) `curl.exe --disable --no-disable`
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

### I expected the following
«not-a-bug»©
### curl/libcurl version
Last.
[curl -V output]
Does not show because this bug.
### operating system
MS Windows 10

**Comment by bagder** [comment]
Please *describe* the bug in the title!

**Comment by jzakrzewski** [comment]
Ok, listen, pal: there are bugs, and inconsistencies, and always will be, but you're being rude now. The fact, that we don't read or understand Russian does not mean, that we cannot use a translator.
Be civil, or be gone.

**Comment by bagder** [comment]
@u20221022 feel free to come back when you can be polite and friendly

**Comment by bagder** [comment]
Rude comments
