### ISSUE TITLE
Remote name all writes something to stdout and break Far panels

### ISSUE THREAD

**Issue by skipik** [curl/curl#10588]
### I did this

- run Far Manager
- run vs.cmd
`@echo off
rem Required cURL 7.66.0 or newer!
cd ..\
if not exist Installer (md Installer)
cd Installer
if exist vs_*.exe (del /f/s/q vs_*.exe) > nul & start /i /b C:\Soft\Far\curl.exe -C - -RLZOSs --remote-name-all https://aka.ms/vs/17/release/vs_BuildTools.exe https://aka.ms/vs/17/release/vs_Community.exe https://aka.ms/vs/17/release/vs_Enterprise.exe https://aka.ms/vs/17/release/vs_Professional.exe https://aka.ms/vs/17/release/vs_TeamExplorer.exe https://aka.ms/vs/17/release/vs_TestAgent.exe https://aka.ms/vs/17/release/vs_TestController.exe
exit /b`

### I expected the following

Far Manager panels shouldn't break as it was on all the previous curl verions but now it looks like something tries to write to stdout and I see panels artefacts at the bottod edge of Far

### curl/libcurl version

curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### operating system

Windows 11 22H2 x64

**Comment by vszakats** [comment]
Dupe: #10573

Next curl-for-win revision will include the patch for this.

**Comment by bagder** [comment]
The progress meter is written to stderr, and the problem is that `-s` is not acknowledged correctly for parallel downloads. You can work around by using `--no-progress-meter`. Fixed already via #10579

**Comment by vszakats** [comment]
New binaries with the fix: https://curl.se/windows/
