### ISSUE TITLE
SOCKETFUNCTION receives zero fd and socket_data for HTTP/3 connections

### ISSUE THREAD

**Issue by sfionov** [curl/curl#10593]
That leads to stalled reads.

### I did this

1) Set CURLMOPT_SOCKETFUNCTION to start polling on socket
2) Start request

socketfunction sometimes receives zero fd to poll, and also zero socket_data for it, with "IN" action.

As result, HTTP/3 connection becoming very slow because it can do reads only when some timeout is fired.

### I expected the following

socketfunction NEVER receives zero fd to poll (why to poll stdin?), and also zero socket_data for it.

### curl/libcurl version

libcurl 7.88.1 with ngtcp2 0.13.1 and nghttp2 0.7.1

It worked ok on libcurl 7.85 + ngtcp2 0.9.0

### operating system

macOS 12.6

**Comment by icing** [comment]
I reproduced this and indeed there is some fd 0 confusion. PR coming soon.
