### ISSUE TITLE
curl --proxy caused a failure inside Github Action

### ISSUE THREAD

**Issue by Mon-ius** [curl/curl#10621]
Recently, I created a docker image and publish it via `GitHub Action` to the docker hub. The goal of the image is to create a `socks5` proxy using `dante` inside the container;

I wrote another GitHub Action to verify the success of the image. The core thing is very simple:
`curl --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace"`

However, it always failed as `https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4281093831/jobs/7453680297` shows. And, curl without --proxy works fine.

The strange thing is when I entered the Action machine, everything just works fine. No error reports as it does in GitHub Action at all. No error within or without --proxy.

The detail of the cURL is 

```bash
shell: /usr/bin/bash -e {0}
  env:
    DOCKER_CONFIG: /home/runner/.docker
    DOCKER_CLI_EXPERIMENTAL: enabled
+ curl --version
curl [7](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4281093831/jobs/7453680297#step:5:7).[8](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4281093831/jobs/7453680297#step:5:8)1.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.[9](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4281093831/jobs/7453680297#step:5:9) zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

I spent the whole day and tried to find an answer through the internet and also the very popular AI-Language model and come across that it was probably a bug.

**Comment by bagder** [comment]
So not even an error message? What does curl return in the error case?

**Comment by Mon-ius** [comment]
Also, there is a more direct version of this problem.

```
set -x
  curl --version
  curl https://www.cloudflare.com/cdn-cgi/trace
  curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace
  shell: /usr/bin/bash -e {0}
  env:
    DOCKER_CONFIG: /home/runner/.docker
    DOCKER_CLI_EXPERIMENTAL: enabled
+ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/[3](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217#step:5:3).0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.[4](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217#step:5:4).8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
+ curl https://www.cloudflare.com/cdn-cgi/trace
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
fl=466f39
h=www.cloudflare.com
ip=20.168.1[5](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217#step:5:5)8.209
ts=1677473036.469
100   208    0   208    0     0   2240      0 --:--:-- --:--:-- --:--:--  2236
visit_scheme=https
uag=curl/7.81.0
+ curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace
colo=SJC
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
rbi=off
                                 Dload  Upload   Total   Spent    Left  Speed
kex=X25519

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (9[7](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217#step:5:7)) Connection to proxy closed
Error: Process completed with exit code [9](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217#step:5:9)7.
```

It was also recorded  In `Check proxy status` part of [github action](https://github.com/Mon-ius/Docker-Warp-Socks/actions/runs/4278975076/jobs/7449236217),

**Comment by Mon-ius** [comment]
I can also create a new one if it could help to target the problem

**Comment by bagder** [comment]
> curl: (97) Connection to proxy closed

This sounds like the proxy closes the connection.

**Comment by Mon-ius** [comment]
I thought about this situation at first time, then I use `lhotari/action-upterm@v1` to establish an ssh connection to the action server, then manually to perform `curl --proxy socks5h://127.0.0.1:9091 https://www.cloudflare.com/cdn-cgi/trace`, everything works just as expected.

**Comment by bagder** [comment]
I don't know what to do with this information. The error code says the connection is closed when curl handshakes with the proxy. Until proven otherwise I see no reason to question that.

**Comment by Mon-ius** [comment]
It's really weird, I designed over 5 methods to try to prove it. 

- First, check the network works normally, I set up a normal `cURL`, the same parameters, and no proxy option, works.
- Then, check if the firewall inside the action makes things different, I opened all `iptables` permission, no changes.
- After that, maybe the `ssh` connection makes `ENV` and network structure differently, then I tried to move it at the beginning to see the influence, but still no changes.
- I also tried `export` the proxy, but still no changes.

if you look into the action itself and debug it somehow, you may find the really bothering part. Just like Schrödinger's cat. 

> When looking outside the action `cURL` does not work, and shows cannot connect to the proxy. `cURL` with proxy is dead.

> When logging in via `SSH` into the action host, everything just works. `cURL` with proxy is still alive.

**Comment by Mon-ius** [comment]
After 3 days keep exploring, it turns out the GitHub Action runs too fast and the default shell `sh` has no support for `sleep` that caused this problem; after I add a related run step with `shell: bash` and `sleep 2` inside, then the issue was thus fixed; Hope it could help people who have such similar confusing experience.

For example, the following step will cause the issue
``` bash
      - name: Check proxy status
        id: check
        run: |
          set +e
          trace=$(curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
```

After adding `sleep 2` and `shell:bash`, it should act as it should normally.

``` bash
      - name: Check proxy status
        shell: bash
        id: check
        run: |
          set +e
          date && sleep 20 && docker ps -a && docker logs warp_socks && date
          trace=$(curl -v --proxy "socks5h://127.0.0.1:9091" "https://www.cloudflare.com/cdn-cgi/trace" | grep -w "warp=on")
          echo ::set-output name=trace::$trace
```

To be noticed that `date` is also required to have sure the action being observed.
