### ISSUE TITLE
Connection filter code attempts to resolve remote address for listen connection

### ISSUE THREAD

**Issue by piru** [curl/curl#10622]
### I did this

`curl -v --ftp-port "-" ftp://ftp.funet.fi`

In output I see a bogus error:
```
...
* sa_addr inet_ntop() failed with errno 47: Address family not supported by protocol family
...
```
The error is due to `set_remote_ip()` call in `Curl_conn_tcp_listen_set()` with unset `ctx->addr.sa_addr`. See https://github.com/curl/curl/blob/cf3e6ce92f1c9686129d0fd4a5d39c0fb38792ec/lib/cf-socket.c#L1816

### I expected the following

No superfluous errors being reported.

### curl/libcurl version

curl 7.88.1 (aarch64-apple-darwin22.3.0) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) nghttp2/1.52.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Darwin computername.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

**Comment by icing** [comment]
Thanks for the report. Please see #10642 for the fix.

**Comment by piru** [comment]
This fixes the issue for me, thanks!
