### ISSUE TITLE
Compiling with linker lld-link.exe leads to errors "duplicate symbol"

### ISSUE THREAD

**Issue by ValeV008** [curl/curl#10668]
### I did this

In cmd.exe I went to curl root folder and typed:
`call buildconf.bat -clean`
`call buildconf.bat`
`cd winbuild`
Changed by hand LNKLIB variable to "llvm-lib.exe" around line 65 in file "winbuild/MakefileBuild.vc".
Changed by hand CURL_LINK variable to "lld-link.exe" around line 550 in file "winbuild/MakefileBuild.vc".
`nmake /f Makefile.vc CC=clang-cl mode=static WITH_SSL=static WITH_ZLIB=static WITH_SSH2=static MACHINE=x64 SSL_PATH="[path]" ZLIB_PATH="[path]" SSH2_PATH="[path]"`

("[path]"s are absolute paths to openssl, zlib and ssh2 libraries, which were also compiled with clang-cl)

### What I got

lld-link: error: duplicate symbol: Curl_isspace
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isdigit
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isalnum
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isxdigit
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isgraph
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isprint
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isalpha
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_isupper
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_islower
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

lld-link: error: duplicate symbol: Curl_iscntrl
>>> defined at ..\builds\libcurl-vc-x64-release-static-ssl-static-zlib-static-ssh2-static-ipv6-sspi-obj-curl\curl_ctype.obj
>>> defined at libcurl_a.lib(curl_ctype.obj)

### I expected the following

The building to be successful.

### curl/libcurl version

Version 7.85.0.

### operating system

Windows 10 64bit.

**Comment by bagder** [comment]
Those functions no longer exist in current versions but I don't know why you get them twice nor do I understand why your use of compiler would introduce that problem.
