### ISSUE TITLE
Feature request: support dns resolution hook/callback

### ISSUE THREAD

**Issue by bsergean** [curl/curl#10696]
Sorry I didn't follow the guideline of asking in the mailing lists ... feel free to close this if this isn't ok.

The use case would be to let a user setup a callback that runs right after dns resolution, where he could get to the resolved address, and do whatever he wants.

The typical use case would be to cancel a request, if the resolved dns is to certain ip range (say localhost, or an ip the application level knows to be invalid).

**Comment by dfandrich** [comment]
Would CURLOPT_OPENSOCKETFUNCTION not work for this?

**Comment by bsergean** [comment]
Ah maybe, thanks for the info. We are using curl-multi with libuv fyi (there’s an example in lib curl which we changed a bit).
