### ISSUE TITLE
curl with --unix-socket failed for 7.88.1

### ISSUE THREAD

**Issue by linggao** [curl/curl#10695]
### I did this
````
curl -sSLw "%{http_code}" https://localhost/api/v1/objects/config.json --unix-socket /tmp/mypath/myfile.sock --cacert /mypath/cert.pem -u "myorg/myname:passwd" -v
Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
Closing connection 0
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
000
````

### I expected the following
It should return the output of `https://localhost/api/v1/objects/config.json` API.
### curl/libcurl version

[curl -V output]
curl 7.88.1 (x86_64-alpine-linux-musl) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

### operating system

Linux 405dc42f0607 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 Linux

**Comment by linggao** [comment]
This happens in a docker container with `alpine:latest` as the os base.  The curl version is 7.88.1.  The alpine is the latest version that just released in Feb, 2023.

**Comment by dfandrich** [comment]
This looks like #10633 which has already been fixed.
