### ISSUE TITLE
Unhelpful openssl error when connecting to a self signed certificate without trusting insecure certificates

### ISSUE THREAD

**Issue by SuperSandro2000** [curl/curl#10702]
### I did this

Try to connect to a host which has a self signed certificates without adding ``--inecure``

```
▶ curl https://ingress.example.com -v
*   Trying 10.0.0.10:443...
* Connected to ingress.example.com (10.0.0.0) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* OpenSSL/3.0.8: error:16000069:STORE routines::unregistered scheme
* Closing connection 0
curl: (35) OpenSSL/3.0.8: error:16000069:STORE routines::unregistered scheme
```

### I expected the following

An error message that is more helpful.

### curl/libcurl version

```
 ▶ curl -V
curl 7.88.0 (x86_64-pc-linux-gnu) libcurl/7.88.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.51.0
Release-Date: 2023-02-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

``Linux host 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux``

**Comment by bagder** [comment]
Well, OpenSSL delivers odd errors and as you can see on this error, it does not say it is a failed verification error. It seems to rather identify a problem in your CA store or something.

I'm not sure we can do much about this!

**Comment by SuperSandro2000** [comment]
Maybe it is not a bug, but the UX could be better. certificate validation is a bit far off the error message which only complains about the used scheme.

**Comment by milahu** [comment]
> Try to connect to a host which has a self signed certificates

another cause for this error are missing ca-bundle certificates
which usually are stored at `/etc/ssl/certs/ca-bundle.crt`

```
$ CURL_CA_BUNDLE= SSL_CERT_FILE= curl https://github.com/
curl: (35) OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme

$ SSL_CERT_FILE= git clone https://github.com/curl/curl
Cloning into 'curl'...
fatal: unable to access 'https://github.com/curl/curl/': OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme
```

**Comment by CyberShadow** [comment]
On Ubuntu and Arch Linux, `curl` prints the following message in this situation:

```console
$ curl https://self-signed.badssl.com/
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

However, on NixOS, I get the following:

```console
$ curl https://self-signed.badssl.com/         
curl: (35) OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
```

Since @SuperSandro2000 is a NixOS maintainer, I suspect that the problem is NixOS-specific. Though it's not excluded that it might still be a cURL bug, it is still probably caused by a difference in how cURL or OpenSSL is built and packaged.

**Comment by SuperSandro2000** [comment]
I think I found it. Going to open a PR against nixpkgs https://github.com/NixOS/nixpkgs/pull/351920
