### ISSUE TITLE
CURL -R (--remote-time) is not working with SFTP sites

### ISSUE THREAD

**Issue by StarFoxMcCloud** [curl/curl#1071]
### I did this
curl -k --progress-bar -O -R -z "FileName.txt" "sftp://RemoteURL/FileName.txt" --user RemoteUser:Password

### I expected the following
FileName.txt should download with the same time stamp from the remote server. However, it takes on the downloaded timestamp instead. This is happening to all SFTP sites I have tried. FTP works though (but this doesn't help me).

### curl/libcurl version
curl 7.29.0 (latest version from redhat yum repository)

curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.16.2.3 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz

### operating system
Red Hat Enterprise Linux Server release 7.2

**Comment by bagder** [comment]
Correct. Support for CURLINFO_FILETIME was added to SFTP in commit f9d27e0f8, relased in curl 7.49.0.

**Comment by StarFoxMcCloud** [comment]
Thanks. I compiled 7.50.3 and it is working (except the remote time and local time (after the file is downloaded) are not the same (probably due to UTC). Is there a way to read the remote time using the same time zone as the system running cURL?
