### ISSUE TITLE
Compiling on linux problem

### ISSUE THREAD

**Issue by Underground0** [curl/curl#1072]
Hello and sorry if i am posting here this problem, i've asked on other websites but still can't solve this.
I am trying to compile a plugin for linux that includes the **libcurl** and i can't get it working because i am getting some errors when i am trying to compile it statically.

First i installed the libcurl4-openssl-dev on my ubuntu machine with "apt-get install", i tried to compile it with "-lcurl" in the makefile, all worked fine but i want to compile it statically because i'll need it for using on another machines. 

I downloaded curl 7.46.0 version from here "https://curl.haxx.se/download/" and followed this tutorial for installing it on my ubuntu machine "https://www.jasom.net/how-to-install-curl-command-manually-on-debian-linux", after i installed 7.46.0 version i removed the "-lcurl" from the makefile and i added  the path to libcurl.a  ("/usr/local/lib/libcurl.a"), it compiled fine but when i run it it gives me the next errors: http://pastebin.com/rCBTHLaA.

**My "curl -V" output**
curl 7.46.0 (i686-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

I hope you'll help me in solving this problem, thanks!

**Comment by bagder** [comment]
@Underground0, this is the issue tracker where we track and work on "issues" with curl.

For regular questions and help on how to use and work with libcurl, we have [the curl-library mailing list](https://cool.haxx.se/cgi-bin/mailman/listinfo/curl-library) where we deal with questions and answers around these topics every day.

Please direct your questions there instead. And perhaps read up on how static linking requires you to specify **all** dependencies on the link command line so -lcurl is usually far from enough.
