### ISSUE TITLE
Specifying --with-openssl=openssl-1.1.1t points to non-existant lib directory

### ISSUE THREAD

**Issue by RenHoekNL** [curl/curl#10725]
I downloaded and compiled openssl-1.1.1t in a directory. I then configure curl to use that installation.

./configure --with-openssl=$(realpath ../openssl-*/)   # Other switches omitted

This goes wrong, because it cannot find the *.a files because it tries to find them in '/root/repo/hoard/openssl-1.1.1t/lib'. But the 'lib' directory doesn't exist. The *.a files are found in the 'openssl-1.1.1t' itself.

So I create a lib directory and copy the *.a files in there. Now at least I can configure.

I'd suggest replacing the --with-openssl with a --with-openssl-include and --with-openssl-libs switch.

**Comment by dfandrich** [comment]
curl is designed to use OpenSSL installed using its own install mechanism.
Alternately, curl will also use pkg-config to find it.  It sounds like you've
installed it some other way, in which you get the fun of getting to get it to
work.
