### ISSUE TITLE
-o option ignored after first url in list

### ISSUE THREAD

**Issue by jimmont** [curl/curl#1073]
### I did this
```
curl -s -w 'status:%{http_code} time:%{time_total} dns:%{time_namelookup} url:%{url_effective}\n' http://localhost http://localhost http://localhost -o /dev/null
curl -s -o /dev/null -w 'status:%{http_code} time:%{time_total} dns:%{time_namelookup} url:%{url_effective}\n' http://localhost http://localhost http://localhost
```
_urls can be anything_

### I expected the following
**all** output to wherever option `-o` designates:
```
status:200 time:0.006 dns:0.005 url:http://localhost/
status:200 time:0.000 dns:0.000 url:http://localhost/
status:200 time:0.000 dns:0.000 url:http://localhost/
```
### actual output
```
status:200 time:0.006 dns:0.005 url:http://localhost/
<response body for index.html>
status:200 time:0.000 dns:0.000 url:http://localhost/
<response body for index.html>
status:200 time:0.000 dns:0.000 url:http://localhost/
```

### curl/libcurl version 
```
curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
/usr/local/Cellar/curl/7.50.3/bin/curl --version
curl 7.50.3 (x86_64-apple-darwin15.6.0) libcurl/7.50.3 SecureTransport zlib/1.2.5
```

### operating system
OSX 10.11

**Comment by jay** [comment]
> -o option ignored after first url in list

Yeah that's expected, see [-o, --output](https://curl.haxx.se/docs/manpage.html#-o). So you would have to specify it once for each unless you're globbing. In other cases you could do 1>/dev/null but in this case the statistics would be suppressed.

You could call it once per URL with xargs but the connections won't be reused:
~~~
cat URLs.txt | xargs -n 1 curl -o /dev/null -s -w 'status:%{http_code} time:%{time_total} dns:%{time_namelookup} url:%{url_effective}\n'
~~~

We had discussed allowing write-out to redirect to stderr but I forget what happened with that... anyone remember? I can't find the discussion.

**Comment by bagder** [comment]
> We had discussed allowing write-out to redirect to stderr but I forget what happened with that

Mentioned in the [TODO](https://curl.haxx.se/docs/todo.html#w_output_to_stderr), was suggested in #613
