### ISSUE TITLE
Schannel regression: CURLOPT_SSL_CIPHER_LIST has no effect on Windows 10 >= 10.0.17763

### ISSUE THREAD

**Issue by zhihaoy** [curl/curl#10741]
### I did this

Set `CURLOPT_SSL_CIPHER_LIST` on a connection that uses Schannel, TLS 1.2, and make a connection to an HTTPS server.

### I expected the following

Investigate its Hello message, the cipher suites should match my settings.

### curl/libcurl version

libcurl 7.85.0 to the latest

### operating system

Fails (`CURLOPT_SSL_CIPHER_LIST` has no effect) on Windows 10 build 17763 and above, such as 10 Enterprise 1809 and 20H1.
Works (`CURLOPT_SSL_CIPHER_LIST` is in effect) on Windows 10 build 14393, such as Windows Server 2016

### Cause analysis

The problem was introduced by https://github.com/curl/curl/commit/8beff4355956e3d18ceb3afc21c1f3edec82543c. The change moved this chunk of code: https://github.com/curl/curl/blob/801bd5138ce31aa0d906fa4e2eabfc599d74e793/lib/vtls/schannel.c#L503-L510 to https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/lib/vtls/schannel.c#L1006-L1021 However, the new block was an else block started way above https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/lib/vtls/schannel.c#L790-L792 Then the logic becomes: Since only Windows 10 build 17763 supports TLS 1.3, we configure *only* TLS 1.3 ciphers on those systems; if we are on a lower version of Windows, we go ahead and configure TLS 1.2 (or lower) ciphers. So the combination of "on a newer version of Windows 10" and "using TLS 1.2" falls into neither branch. Support for `CURLOPT_SSL_CIPHER_LIST` under that combined condition was lost.

**Comment by jay** [comment]
I've submitted a fix in PR #10746 which should allow TLS < 1.3 ciphers to be set as long as TLS 1.3 ciphers are not set. I'm not sure if it's possible to combine the two because they use different credential structs and we are only allowed to pass a single credential struct to schannel. The PR is marked as draft for now. If anyone can investigate further that would be helpful.

/cc @wyattoday

**Comment by vszakats** [comment]
Does this bug mean that when running on Windows 10 1809+, curl (with Schannel) is forcing TLS 1.3 with no option to use TLS 1.2? Or, requiring `--tlsv1.2` option to access servers offering no TLS 1.3? Or, not even with an option?
