### ISSUE TITLE
Wasted CPU and slowed down transfer without CURLOPT_NOSIGNAL set to 1

### ISSUE THREAD

**Issue by jerstlouis** [curl/curl#10743]
### I did this
With a multi curl handle, a `curl_multi_perform()` loop wastes enormous amount of CPU and transfers way slower than it should unless `CURLOPT_NOSIGNAL` is set, because of `sigaction()` being called every single time continuously.

### I expected the following
I did not expect CPU to be wasted and transfer slowed down because of an obscure `CURLOPT_NOSIGNAL` option I had no idea about.

Setting `CURLOPT_NOSIGNAL` to 1 resulted in huge performance gain and no longer wasting CPU, but finding out about this was very costly. The cost associated with the default behavior is unexpected. Figuring this out required realizing that the cURL processing thread is busy most of the time calling _sigaction()_, and working backwards to _sigpipe_ignore()_, `no_signal`, and finally `CURLOPT_NOSIGNAL`. Not something that should be expected of developers using the library to get decent CPU usage / network performance.

### curl/libcurl version

curl 7.81.0 (x86_64-pc-linux-gnu)

### operating system

Linux hostname 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
I'm sorry, what do you expect us to do about this issue?

**Comment by jerstlouis** [comment]
@bagder Thank you. Well, how feasible is making `CURLOPT_NOSIGNAL` = 1 the default?

The problem is how expensive a call to `sigaction()` is from within `curl_multi_perform()`, which will typically be called at a high frequency. Whatever behavior is desired for `SIGPIPE` should be set *outside* of the loop.

At the very least, a mention of this performance issue in the [documentation page for curl_multi_perform()](https://curl.se/libcurl/c/curl_multi_perform.html) would help inform users about this problem.

**Comment by bagder** [comment]
Can you qualify what "enormous amount of CPU" means in more specific terms? I seem to be able to download data very fast with libcurl in spite of this.

> how feasible is making CURLOPT_NOSIGNAL = 1 the default?

Not feasible at all, that would be a major change in a behavior and we would need to bump the SONAME number of that.

> mention of this performance issue

I'm not sure I agree with you yet that is is an issue...

**Comment by jerstlouis** [comment]
@bagder Thank you for looking into this.

The CPU usage was maxed out and I went from downloading ~800 kilobytes / second to ~10 megabytes / second.
Note that this was range request for the first 1 MB parts for several (millions) of files on AWS S3.
Of course this is only issue if _curl_multi_perform()_ is called several times per second.

My cURL thread processing looked something like this:

```eC
      while(!terminated)
      {
         int runningHandles;
         long curl_timeo;
         int rc;

         curl_multi_timeout(multiHandle, &curl_timeo);
         if(curl_timeo < 0)
           curl_timeo = 1000;
         rc = curl_multi_poll(multiHandle, null, 0, (int)curl_timeo, null);
         switch(rc)
         {
            case -1: break;
            case 0: default: curl_multi_perform(multiHandle, &runningHandles); break;
         }

         while(!terminated)
         {
            int msgq = 0;
            struct CURLMsg *m = curl_multi_info_read(multiHandle, &msgq);
            if(!m) break;
            if(m->msg == CURLMSG_DONE)
              ; // do stuff
         }
      }
```

Most often _curl_multi_timeout()_ would return a small value ~60 or so.
I am using CURLMOPT_MAX_HOST_CONNECTIONS = 5 and CURLMOPT_PIPELINING = CURLPIPE_MULTIPLEX.

**Comment by bagder** [comment]
## Speed difference

I used the test code in [relative](https://github.com/curl/relative) on my local dev machine to see what "enormous amount of CPU" means.

Doing one million (1000000) transfers (HTTP/1, cleartext), 100 in parallel. Each transfer being 4205 bytes. Fastest out of three runs:

### Without setting CURLOPT_NOSIGNAL

Time: 7442003 us, 7.44 us/transfer

### With setting CURLOPT_NOSIGNAL to `1L`

Time: 6967241 us, 6.97 us/transfer

**Comment by jerstlouis** [comment]
@bagder That is definitely not the _enormous amount of CPU_ I experienced.
It was 1000% faster in my case. Possibly one of the following things came into play?

- Different cost of _sigaction()_ on the particular system (for an unknown reason)
- I had only 5 transfers in paralel
- Something about transferring larger blocks ( 1 mb )
- Network source and behavior
- Loop setup differences?

I guess the first thing to clarify would be exactly how many times per second _curl_multi_perform()_ is being called, and what timeout value is used with _curl_multi_poll()_.

**Comment by bagder** [comment]
I figure the cost would be higher with many smaller transfers (that can never fill up a large buffer) and do many  in parallel. And it should be CPU bound, not network. Hence my specific test. This on a fast current intel CPU running Debian Linux.

**Comment by jerstlouis** [comment]
@bagder My system where the issue occurs is an Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz running Ubuntu 22.04.2 LTS.

Regarding the network impact, I was thinking in terms of latency or small delays in starting several small transfers continuously that would cause _curl_multi_perform()_ to do very little work compared to the cost of calling _sigaction()_, but would result in _curl_multi_timeout()_ returning a small value or _curl_multi_poll()_ always returning quickly, but I dont' really understand what could do this.

**Comment by bagder** [comment]
If you aren't CPU bound then it would just loop and do it again as long as there is network data to read and then you should only waste CPU not see a network performance degradation.

**Comment by jerstlouis** [comment]
I do believe it was CPU bound (one core maxed out at 100% by the curl loop thread) by calling `sigaction()` too often, but I am not sure exactly of the scenario that could have resulted in it being called tons of times due to not being familiar enough with the inner workings of _curl_multi_timeout()_, _curl_multi_perform()_ and _curl_multi_poll()_.

**Comment by bagder** [comment]
It's still a mystery to me how just sigaction is able to cause such a big problem for you. Anyway, the  #10750 approach should at least reduce the amount of calls by a significant factor as it will typically reduce them to only one per `curl_multi_perform()` invoke.

**Comment by jerstlouis** [comment]
@bagder It may be that #10750 could address the root of the issue. If I had hundreds of thousands of easy handles added to my one multi handle (but really only 5 are downloading data at a time due to CURLMOPT_MAX_HOST_CONNECTIONS), but it was still calling _sigaction()_ twice (restore/ignore) for every single one of those easy handles, wouldn't that have been a huge cost?
Or am I missing something?

Are there some additional optimization that could be done to _curl_multi_perform()_ so as to skip the whole _multi_runsingle()_ aspect if the remaining hundreds of thousands of easy handles are not yet "live" (e.g., assuming they're sorted with the live ones at the head)?

**Comment by bagder** [comment]
> wouldn't that have been a huge cost?

It would indeed. This PR is at least a good step in the right direction.

> Are there some additional optimization that could be done to curl_multi_perform() so as to skip the whole multi_runsingle() aspect (i.e., break out of the data = data->next while loop early)

Yes. libcurl is certainly not optimized for that scenario just as you say it could be improved a lot in that aspect. Instead of just putting the handle in "pending" state, it should probably rather move it to a separate pending list...

**Comment by jerstlouis** [comment]
Thank you very much @bagder for getting to the bottom of it and solving this issue :) 

I am still of the opinion that CURLOPT_NOSIGNAL = 1 is a less surprising default, and the 6% performance increase in your test is not negligible, so perhaps something to keep in mind for the next time the SONAME gets bumped.

**Comment by bagder** [comment]
I also pretty sure my PR will decrease the 6% somewhat. I might go back and do another check later if I get the time.

**Comment by bagder** [comment]
No wait, pending handles are already in another list! :grinning:

**Comment by jerstlouis** [comment]
@bagder are they :S I am confused now. How many states are there? By "pending" do you mean _awaiting available connections for host_? (almost certain that was the state of the vast majority of my handles)

**Comment by bagder** [comment]
A single easy handle has many states it can be in. Check this [overview in everything curl](https://everything.curl.dev/internals/statemachines).

The pending state is when the easy handle is waiting to get a spot and get its transfer started. It could end up in pending because of several reasons. The max-connects-allowed-per-host is one such limitation.

**Comment by bagder** [comment]
Would you be able to test your use case with the PR code merged and the option as default, just to see what difference it makes for you?

**Comment by bagder** [comment]
pending handles _are_ in a separate list, but still remain in the main list. I've started a PR to improve this: #10762

**Comment by bagder** [comment]
I think we can consider this case addressed for now. The #10750 and #10762 PRs should hopefully make a noticeable impact.

If not, we should come back and continue working on other ways.

That fine with you @jerstlouis ?

**Comment by jerstlouis** [comment]
Yes thank you very much again @bagder .
