### ISSUE TITLE
Bug in the SPENGO implementation 

### ISSUE THREAD

**Issue by zhenyuy** [curl/curl#1074]
### I did this

Using curl to connect to an kerberorized service with the following options: 
curl  -X post --negotiate --service-name myservice.https --user "u:"
### I expected the following

Apparently, GSSContext.getSrcName() can return null, even if isEstablished() is true. 
### curl/libcurl version

dev ~ $ curl -V
curl 7.49.0 (x86_64-redhat-linux-gnu) libcurl/7.49.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.4.3 nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL
### operating system

centos7

**Comment by dolipandey06** [comment]
Android

**Comment by bagder** [comment]
@dolipandey06 What?

**Comment by bagder** [comment]
I'm sorry, can you please elaborate on what the problem is exactly and how we can reproduce it?

**Comment by michael-o** [comment]
Please provide more details. It is virtually impossible to help you without.

**Comment by bagder** [comment]
No response.
