### ISSUE TITLE
Connection reuse with --next and --resolve

### ISSUE THREAD

**Issue by masterinspire** [curl/curl#10755]
### I did this

https://dig.ping.pe/curl.se:A:8.8.8.8

**curl.se** resolves to following ips:
* 151.101.129.91
* 151.101.193.91
* 151.101.1.91
* 151.101.65.91

I want to check each ip's connection, use `--next` and `--resolve`. (`--parallel` can also be used.)

```
curl.exe -v "https://curl.se/" --resolve "curl.se:443:151.101.65.91" --output nul --silent --next "https://curl.se/" --output nul --silent --resolve "curl.se:443:151.101.1.91"
```

output reduced for clarity:

```
* Added curl.se:443:151.101.65.91 to DNS cache
* Hostname curl.se was found in DNS cache
*   Trying 151.101.65.91:443...
* Connected to curl.se (151.101.65.91) port 443 (#0)

* RESOLVE curl.se:443 is - old addresses discarded
* Added curl.se:443:151.101.1.91 to DNS cache
* Found bundle for host: 0x1cb8b5f2e10 [can multiplex]
* Re-using existing connection #0 with host curl.se
```

https://curl.se/docs/manpage.html
> When -:, --next is used, it resets the parser state and you start again with a clean option state, except for the options that are "global". Global options will retain their values and meaning even after -:, --next.
> The following options are global: --fail-early, --libcurl, --parallel-immediate, -Z, --parallel, -#, --progress-bar, --rate, -S, --show-error, --stderr, --styled-output, --trace-ascii, --trace-time, --trace and -v, --verbose. 

`--resolve` is not a global option, old addresses discarded, new one added to DNS cache, but then connection reused, which means the later `--resolve` option does not work.

### I expected the following

Connection reuse should take `--resolve` into consideration.

### curl/libcurl version

curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### operating system

Microsoft Windows [Version 10.0.19045.2673]

**Comment by masterinspire** [comment]
https://curl.se/libcurl/c/CURLOPT_FORBID_REUSE.html

It seems there is no related command line options for disable connection reuse.

**Comment by bagder** [comment]
> It seems there is no command line options for disable connection reuse.

That's correct. (A possibly work-around is sometimes to use `-H "Connection: close"`)

The connection cache and the DNS cache are both kept over `--next` boundaries. I think for your case it would be easier to just invoke curl multiple times.

**Comment by masterinspire** [comment]
Some websites use cloudfront which can resolves to 100+ ip addresses.

Initially I tried use `--parallel`, this problem makes `--parallel` useless.

Then I invoke curl multiple times to work around this problem, it's way too slow. 

(I can use libcurl for my use case)

**Comment by bagder** [comment]
Still, you are describing a behavior that is intended and as per design. Dropping connections and the DNS cache at will could of course be subject for some new option, but it seems rather niche. I am personally not like to work on anything in that direction anytime soon.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
