### ISSUE TITLE
local_ip, local_port, remote_ip, remote_port all not set when connection timed out

### ISSUE THREAD

**Issue by masterinspire** [curl/curl#10754]
### I did this

Following examples use a port `444`  that cannot be connected for testing purpose

use an ip, no dns query:
```
curl "https://1.1.1.1:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n"
```

use a domain, dns query needed:
```
curl "https://curl.se:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n"
```

use a domain with `--resolve`, no dns query:
```
curl "https://curl.se:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n" --resolve "curl.se:444:1.1.1.1"
```

`local_ip`, `local_port`, `remote_ip`, `remote_port` all not set:

* * *

```
curl "https://1.1.1.1:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n"
*   Trying 1.1.1.1:444...
* ipv4 connect timeout after 2000ms, move on!
* Failed to connect to 1.1.1.1 port 444 after 2013 ms: Timeout was reached
* Closing connection 0
local: :0
remote: :0


curl "https://curl.se:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n"
*   Trying 151.101.1.91:444...
* ipv4 connect timeout after 852ms, move on!
*   Trying 151.101.129.91:444...
* ipv4 connect timeout after 420ms, move on!
*   Trying 151.101.65.91:444...
* ipv4 connect timeout after 202ms, move on!
*   Trying 151.101.193.91:444...
* ipv4 connect timeout after 183ms, move on!
* Failed to connect to curl.se port 444 after 2004 ms: Timeout was reached
* Closing connection 0
local: :0
remote: :0


curl "https://curl.se:444/" -v --output nul --silent --connect-timeout 2 --write-out "local: %{local_ip}:%{local_port}\nremote: %{remote_ip}:%{remote_port}\n\n" --resolve "curl.se:444:1.1.1.1"
* Added curl.se:444:1.1.1.1 to DNS cache
* Hostname curl.se was found in DNS cache
*   Trying 1.1.1.1:444...
* ipv4 connect timeout after 1999ms, move on!
* Failed to connect to curl.se port 444 after 2010 ms: Timeout was reached
* Closing connection 0
local: :0
remote: :0


```
### I expected the following

ip should be set with whatever ip curl has resolved.

### curl/libcurl version

curl 7.88.1 (x86_64-w64-mingw32) libcurl/7.88.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.8.0 libgsasl/2.2.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### operating system

Microsoft Windows [Version 10.0.19045.2673]

**Comment by bagder** [comment]
That would then require us to pick one, since curl can try numerous IP addresses until it fails. Which IP did it then "use"? I would argue it used none of them.

It also did not use a local IP since that would require a setup connection.

**Comment by masterinspire** [comment]
@bagder 

https://curl.se/docs/manpage.html#-w
> remote_ip The remote IP address of the most recently done connection - can be either IPv4 or IPv6.

**Comment by bagder** [comment]
No, a connection could not be established. There was no connection. It may have tried several IPs.

**Comment by bagder** [comment]
I claim curl works as documented here.

**Comment by dolvany** [comment]
> That would then require us to pick one, since curl can try numerous IP addresses until it fails. Which IP did it then "use"? I would argue it used none of them.
> 
> It also did not use a local IP since that would require a setup connection.

I did not realize curl will try multiple IPs--interesting. It would be more appropriate to have a write-out for each attempt, including local/remote IP and exit code (or some indication of the error encountered). This would provide improved visibility versus obfuscating errors.

**Comment by icing** [comment]
I do not see any "obfuscating". curl clearly prints on `-v` what is happening. If you want more tcp related logging, add `--trace-config tcp`.

**Comment by dolvany** [comment]
Thanks, I was not aware of the trace functionality, but it looks very new. Perhaps `--fail-early` provides the deobfuscating I desire. Not sure if the json write-out provides the same detsail as `-v`, but the json write-out is what I use.
