### ISSUE TITLE
curl -JOL download failed

### ISSUE THREAD

**Issue by htqx** [curl/curl#10768]
### I did this
curl -LOJv 'https://box.nju.edu.cn/f/3f67e092e1ba441187d9/?dl=1'
message:
content-disposition: attachment;filename*="utf-8' 'linux-minimal.zip"
Warning: Remote filename has no length!
curl: (23) Failed writing header

### I expected the following
Download linux-minimal.zip

### curl/libcurl version

[curl -V output]
curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Linux arch-pc-lv3 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64 GNU/Linux

**Comment by bagder** [comment]
curl does not support the `filename*=` field in the header, which makes it finds no file name to use. This is mentioned in the man page for `-J`:

> This  feature  uses the name from the "filename" field, it does not yet support the "filename*" field (filenames with explicit character sets).
