### ISSUE TITLE
libcurl tags question

### ISSUE THREAD

**Issue by toast12** [curl/curl#1076]
Hi,

All the libcurl tags have -DEV suffixed to the version number in curlver.h as follows:

#define LIBCURL_VERSION "7.50.2-DEV"

Why is that? The release tarballs do not have a -DEV in there. Also the tag for 7_50_3 has LIBCURL_VERSION incorrectly written as 7_51_0-DEV

**Comment by bagder** [comment]
Because you're using tagged source code and not the release tarballs. The tarballs contain the releases, the git repository is tagged so that you can get all the files exactly as they were at the time of the release. We don't commit generated files and the release process generates a few files that get included in the release tarball.

**Comment by toast12** [comment]
Thanks. Same question as in c-ares forum:

We use git repo for our internal builds. So if I want to fix this internally, what is the most sustainable approach? I read in your libcurl forum that you run a build configuration utility. If I run it, will that fix this issue?

**Comment by bagder** [comment]
This is an issue tracker, not a support forum. Please take your questions and discussions to the curl-library mailing list.

**Comment by toast12** [comment]
Following up. Badger, can you please suggest?

**Comment by bagder** [comment]
I suppose you mean me. Can I suggest what?

**Comment by toast12** [comment]
We use git repo for our internal builds. So if I want to fix this internally, what is the most sustainable approach? I read in your libcurl forum that you run a build configuration utility. If I run it, will that fix this issue?

**Comment by jay** [comment]
Maybe some of what bagder told you was lost in translation. _It is correct that -DEV is appended if you are building from the repo._ There's no "fix" needed.

However.. I wrote a script that will get the latest curl release tag, fetch and checkout that tag, and then modify the version includes, but **it is not proper release source**.  [curl-checkout-latest-release.pl ](https://gist.github.com/jay/dcb5ca6813f7efb01382a4fb089e20fe) . Only tested in Linux, to get it working in Windows you'll need to adjust some of the quoting in the backticks from single quotes to double quotes.

To get actual release source download the release tarball or make it yourself using [maketgz](https://github.com/curl/curl/blob/master/maketgz).

**Comment by mback2k** [comment]
@bagder just updated the maketgz script to be able to update the version number without actually building a tgz file. Run `./maketgz x.y.z only` before `./buildconf` and you should be fine. I am doing the same for my autobuilds on tagged commits.

**Comment by toast12** [comment]
mback2k, running that script before buildconf throws an error for me:

./maketgz: line 131: ./config.status: No such file or directory
Runs automake --include-deps
configure.ac: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal).
configure.ac:184: required file `./config.guess' not found
configure.ac:184:   `automake --add-missing' can install `config.guess'
configure.ac:184: required file `./config.sub' not found
configure.ac:184:   `automake --add-missing' can install `config.sub'
Makefile.am:179: CROSSCOMPILING does not appear in AM_CONDITIONAL
make html
make: *** No rule to make target `html'.  Stop.
make pdf
make: *** No rule to make target `pdf'.  Stop.
make vc-ide
make: *** No rule to make target `vc-ide'.  Stop.
produce CHANGES
make dist
make: *** No rule to make target `dist'.  Stop.
Generating curl-7.51.0.tar.bz2
gzip: curl-7.51.0.tar.gz: No such file or directory
Generating curl-7.51.0.tar.lzma
gzip: curl-7.51.0.tar.gz: No such file or directory
Generating curl-7.51.0.zip
gzip: ../curl-7.51.0.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
mv: cannot stat `curl-7.51.0.zip': No such file or directory

**Comment by toast12** [comment]
Ok, never mind. It has to be run as maketgz x.y.z only
