### ISSUE TITLE
incomplete list of global options in curl.1

### ISSUE THREAD

**Issue by Bug-Not-Program-8-0-0** [curl/curl#10796]
### I did this
Read the manual.  List of global options.
```
       The following options are global: --fail-early, --libcurl,  --parallel-
       immediate,  -Z,  --parallel, -#, --progress-bar, --rate, -S, --show-er-
       ror, --stderr, --styled-output,  --trace-ascii,  --trace-time,  --trace
       and -v, --verbose.
```
### I expected the following
List will be truthful.
The true list is here (except for the added --rate): https://github.com/curl/curl/issues/10566
### curl/libcurl version
8.0.0_1
[curl -V output]
curl 8.0.0 (x86_64-w64-mingw32) libcurl/8.0.0 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.9.0 libgsasl/2.2.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
MS Windows 10

**Comment by bagder** [comment]
Can you please tell us exactly what you are missing instead of just trying to be rude?

**Comment by Bug-Not-Program-8-0-0** [comment]
My license is:
One error per each new version of cURL.  Enough for the rest of my life.
And no comments.
________________________________
От: Daniel Stenberg ***@***.***>
Отправлено: 20 марта 2023 г. 15:53
Кому: curl/curl ***@***.***>
Копия: Bug-Not-Program-8-0-0 ***@***.***>; Author ***@***.***>
Тема: Re: [curl/curl] Bugs again (Issue #10796)


Can you please tell us exactly what you are missing instead of just trying to be rude?
