### ISSUE TITLE
Something wrong with static libraries? (Windows, MinGW+MSYS)

### ISSUE THREAD

**Issue by randseed** [curl/curl#1079]
Compiled and installed libcurl:
```
./configure --prefix=/mingw --disable-shared --enable-static
make
make install
```
Then tried to compile a simple C program (only curl_easy_init):
```
gcc main.c `curl-config --static-libs` -static
```

Then I got multiple `undefined reference`'s. Without `-static` it worked.
Not sure but it's probably something wrong with static library building.

curl 7.50.2 (but tried the latest sources from github too)
OS: Windows 7 x64 (mingw32+msys, gcc 5.3.0)

#### Note
There was an interesting piece of code in `curl.h`:
```
#ifdef CURL_STATICLIB
#  define CURL_EXTERN
#elif defined(WIN32) || defined(_WIN32) || defined(__SYMBIAN32__)
#  if defined(BUILDING_LIBCURL)
#    define CURL_EXTERN  __declspec(dllexport)
#  else
#    define CURL_EXTERN  __declspec(dllimport)
#  endif
#elif defined(BUILDING_LIBCURL) && defined(CURL_HIDDEN_SYMBOLS)
#  define CURL_EXTERN CURL_EXTERN_SYMBOL
#else
#  define CURL_EXTERN
#endif
```
It seems like CURL_STATICLIB is undefined and it goes to `#define CURL_EXTERN  __declspec(dllexport)`.
It's wrong according to common sense because i'm trying to compile a static library.
Maybe this will help.

**Comment by jay** [comment]
When you build a static libcurl you have to define `CURL_STATICLIB` in your program before including curl.h. If you have built a static libcurl exclusively (no shared) then I believe `-DCURL_STATICLIB` should be added by `curl-config --cflags`. Do you see it? What is the output when you build?

**Comment by randseed** [comment]
>When you build a static libcurl you have to define CURL_STATICLIB in your program before including curl.h. 

That worked.
Thank you!

Unfortunately, I've already recompiled both static and shared versions so I can't answer your question.
