### ISSUE TITLE
Facing problem when using more than 1 URL with curl command

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#10791]
When i run curl command with more than 1 URL facing below error

### I did this
~~~
root@ubuntu:~# curl -v -k --parallel-immediate --parallel-max 500 -Z -# https://127.0.0.1/index.html -o index.html https://127.0.0.1/index.html -o index.html
*   Trying 127.0.0.1:443...
* Found bundle for host: 0x5633dc58a6c0 [serially]
* Server doesn't support multiplex (yet)
* Connection #0 is still name resolving, can't reuse
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1:443...
DL% UL%  Dled  Uled  Xfers  Live Total     Current  Left    Speed
--  --      0     0     2     2  --:--:-- --:--:-- --:--:--     0      * Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#1)
* ALPN: offers h2,http/1.1
~~~
### curl/libcurl version
~~~
root@ubuntu:~# curl -V
curl 8.0.0-DEV (x86_64-pc-linux-gnu) libcurl/8.0.0-DEV OpenSSL/3.0.8 zlib/1.2.11 brotli/1.0.9 nghttp2/1.53.0-DEV ngtcp2/0.14.0-DEV nghttp3/0.10.0-DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
~~~

### operating system

~~~
root@ubuntu:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@ubuntu:~#
~~~

I am not sure is this issue with curl or nginx or with my VM

 Could someone please help me with this 

Am I missing anything here

**Comment by bagder** [comment]
It's not clear to me what the error is? Does it not download two URLs and overwrite the same file twice?

**Comment by Karthikdasari0423** [comment]
Thank you for replying back.

no,it was able to download file but i am seeing this below logs at start of connection

* Server doesn't support multiplex (yet)
* Connection #0 is still name resolving, can't reuse

Is it a expected behaviour? and any info on this?

**Comment by bagder** [comment]
Those are just informationals. If you don't want them, remove `-v` from the command line.

**Comment by bagder** [comment]
Can you make the command line use public URLs so that we can reproduce it maybe? I still don't understand what you say is happening.

**Comment by Karthikdasari0423** [comment]
> Can you make the command line use public URLs so that we can reproduce it maybe? I still don't understand what you say is happening.

i tried with public URL and here is the output

root@ubuntu:~# curl -v -k --parallel-immediate --parallel-max 500 -Z -# https://quic.nginx.org/ -o index.html https://quic.nginx.org/ -o index.html
* Found bundle for host: 0x55c45f9786c0 [serially]
* Server doesn't support multiplex (yet)
* Connection #0 is still name resolving, can't reuse
DL% UL%  Dled  Uled  Xfers  Live Total     Current  Left    Speed
--  --      0     0     2     2  --:--:-- --:--:-- --:--:--     0      *   Trying 35.214.218.230:443...
* Hostname 'quic.nginx.org' was found in DNS cache
*   Trying 35.214.218.230:443...
* Connected to quic.nginx.org (35.214.218.230) port 443 (#1)
* ALPN: offers h2,http/1.1
} [5 bytes data]


I am seeing below lines in output 

1.Server doesn't support multiplex (yet)

2. Connection #0 is still name resolving, can't reuse

Hope these 2 lines are expected

**Comment by bagder** [comment]
That command line works fine for me on Linux using 7.88.1

> I am seeing below lines in output

Sure, but they are not errors.

**Comment by Karthikdasari0423** [comment]
yeah,okay
Thank you for clarification.
