### ISSUE TITLE
CURL -z (--time-cond) is not working with SFTP sites

### ISSUE THREAD

**Issue by StarFoxMcCloud** [curl/curl#1080]
### I did this

curl -k --progress-bar -O -R -z "FileName.txt" "sftp://RemoteURL/FileName.txt" --user RemoteUser:Password
### I expected the following

FileName.txt should only download if the remote file is newer than the local file. However, the file is downloaded every time without a comparison occurring. This is happening to all SFTP sites I have tried. 
### curl/libcurl version

curl 7.50.3

curl 7.50.3 (x86_64-pc-linux-gnu) libcurl/7.50.3 OpenSSL/1.0.1e zlib/1.2.7 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
### operating system

Red Hat Enterprise Linux Server release 7.2

**Comment by bagder** [comment]
So what time does the remote file have and what time does the local file get after download? Please tell us more details. What's your local time zone and what's the time zone of the server (if you know) ?

**Comment by StarFoxMcCloud** [comment]
As an example, on one SFTP site a file has the following remote time:
Oct 01 07:48 FileName.txt
After downloading, the local file has the following time:
Oct  1 03:48 FileName.txt
(Remote file time is 4 hours **ahead** of the Local file time once downloaded)

On another SFTP site, a file as the following remote time:
Oct  4 06:07 FileName.ZIP
After downloading, the local file has the following time:
Oct  4 09:07 FileName.ZIP
(Remote file time is 3 hours **behind** of the Local file time once downloaded)

My local time zone is EDT. I do not know what the time zones are for any of the remote servers I need to connect to.

**Comment by bagder** [comment]
The SFTP protocol is defined to return the time in number of seconds in the UTC time zone and the [CURLINFO_FILETIME](https://curl.haxx.se/libcurl/c/CURLINFO_FILETIME.html) docs says so too, but [curl doesn't adjust that for the local time zone](https://github.com/curl/curl/blob/master/src/tool_operate.c#L1685-L1690). The [utime](http://pubs.opengroup.org/onlinepubs/009695399/functions/utime.html) function used to set the time, and is not documented to take a UTC based number.

But we've seen this work for HTTP which also should get the time based on UTC, although indirectly from the [curl_getdate](https://curl.haxx.se/libcurl/c/curl_getdate.html)() function then. So why does HTTP work and not SFTP?

**Comment by StarFoxMcCloud** [comment]
I've been researching for a few days now and come up empty as to why this is not working with SFTP.

Using the second example from my previous comment, when I run **`TZ=utc ls -l`**, the local file shows the following date:
Oct 4 13:07 FileName.ZIP

If the SFTP protocol is suppose to return the time in UTC, these dates should match. Instead, it is 7 hours behind the UTC time.

Interestingly enough, I have also tried cURL -z with a time condition instead of a file, but the remote file is downloaded every time regardless if the date in my command is later than the date on the remote site.

**Comment by bagder** [comment]
With an openssh SFTP server running on my own machine, I just tried:

    $ curl -R sftp://localhost/test -o test2

... and when I check the time stamps afterward, both files had the exact same time and date. So at least it _can_ work when both sides are in the same time zone and the server is openssh.

**Comment by StarFoxMcCloud** [comment]
Did you try to see if the following works in that example:

``curl -R -z "test2" sftp://localhost/test -o test2``

From my understanding, cURL should do nothing in this case (assuming the local file "test2" has the same, or more recent timestamp than the remote file "test").

However, in all of my tests, cURL attempts to download the file every time.

Using http://www.monitis.com/traceroute/, I determined that one of the SFTP sites I am using is actually in the same time zone as my Linux server running cURL. However, the -z switch still appears to not be working as intended.

**Comment by bagder** [comment]
I suggest you debug what `data->info.filetime` gets set to here: https://github.com/curl/curl/blob/master/lib/ssh.c#L1709 and what utime() ends up setting the file time to here: https://github.com/curl/curl/blob/master/src/tool_operate.c#L1690

**Comment by bagder** [comment]
Possibly a bug, but nobody seems to debug it. Reopen it if you want to work on it or have additional details.
