### ISSUE TITLE
result code mismatch error buffer info when http3 racing failed

### ISSUE THREAD

**Issue by Cering** [curl/curl#10804]
Thanks for @icing's PR for http/3 happy eyeballs in curl-7.88.0.
I tried this new feature recently, it work well in most cases, but a little bug(?) about error buffer when http3 racing failed.

### I did this
- request an url **without** http/3 supporting, but enable `CURL_HTTP_VERSION_3` for racing
- print the `curl_easy_perform() result`, `curl_easy_strerror()` and `CURLOPT_ERRORBUFFER`
```cpp
CURL *http_handle = curl_easy_init();
curl_easy_setopt(handle, CURLOPT_URL, "https://cn.bing.com/");
curl_easy_setopt(handle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_3);
char mycurl_error_buffer[CURL_ERROR_SIZE] = {0};
curl_easy_setopt(handle, CURLOPT_ERRORBUFFER, mycurl_error_buffer);

CURLcode res = curl_easy_perform(http_handle);
printf("curl_code: %d\n", res);
printf("curl_strerr: %s\n", curl_easy_strerror(res));
printf("curl_errbuf: %s", mycurl_error_buffer);
```
- the result is `CURL_OK`, but the error buffer is not empty (**"quiche: connection to 202.89.233.101:443 refused"**)
```bash
curl_code: 0
curl_strerr: No error
curl_errbuf: quiche: connection to 202.89.233.101:443 refused
```

### I expected the following
- It seems that error buffer was filled when http/3's connection failed, although fallback to http/2 and succeed finally.
- When a request is finished with `CURL_OK`, the error buffer should be an empty string, for avoiding misunderstanding?

### curl/libcurl version
```bash
curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 BoringSSL zlib/1.2.7 brotli/1.0.9 nghttp2/1.41.0 quiche/0.14.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TrackMemory UnixSockets
```

### operating system
```bash
Linux mylinux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jay** [comment]
[CURLOPT_ERRORBUFFER](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html) doc says _"Do not rely on the contents of the buffer unless an error code was returned."_

**Comment by bagder** [comment]
I think the docs explain that this is allowed behavior. In some cases the code doesn't know if an error will be final / terminal error so it adds error info into the buffer just in case. It *could* of course be cleared again when confirmed not an error, but ...

**Comment by Cering** [comment]
Thanks! I didn't pay attention to this section in [CURLOPT_ERRORBUFFER](https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html) docs. Not bug and close.
