### ISSUE TITLE
Unsupported Protocol error in curl on ARM64 windows build

### ISSUE THREAD

**Issue by Bab95** [curl/curl#10805]
### I did this

I build libcurl for arm64 windows platfrom. when i tried to run simple test app (which just send request to example.com) i got Unsupported protocol error.
curl error code 1

curl build steps:

cmake -A ARM64 -B ..\curl-build
cmake --build ..\curl-build

Then simply used the libs in a cpp project which calls to example.com set the build configuration to arm64.

### I expected the following
curl request should be succedded.
### curl/libcurl version

latest (7.88.1)

### operating system
windows 11 ARM64

**Comment by Bab95** [comment]
``` 
   curl_version_info_data* vinfo = curl_version_info(CURLVERSION_NOW);
    if (vinfo->features && CURL_VERSION_SSL) {
        std::cout << "SSL supported!" << std::endl;
    }
```

I used above snippet to test if it's ssl supported or not.

**Comment by MaksymTymkovych** [comment]
Try to use another crypto api such as 
`
set(CURL_USE_SCHANNEL ON CACHE BOOL "USE SCHANNEL")
`
And check log in cmake:
`-- Enabled protocols: DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
`

**Comment by jay** [comment]
I missed a mistake in his snippet,
> if (vinfo->features && CURL_VERSION_SSL) {

should be `if (vinfo->features & CURL_VERSION_SSL) {`

Also I gave an example in both the discussion and this issue and he hasn't followed up. His cmake command shows he is building curl without TLS support. I suppose on Windows we could enable TLS by default, I wonder if that would be unexpected for anyone.

@Bab95 can you confirm?

**Comment by bagder** [comment]
No response.
