### ISSUE TITLE
Tests take a long time to run

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#10818]
Running the close to 1600 tests in the test suite takes a long time and slows developer productivity. This issue will consolidate efforts to speed up running tests, primarily by allowing them to run in parallel. The roadmap will be along this [design proposal](https://github.com/curl/curl/files/11023995/curl.parallel.testing.proposal.pdf).

**Comment by kdudka** [comment]
I like the idea!  Did you consider also running multiple HTTP(S) servers in parallel?  It is probably not something to begin with.  On the other hand, it would be good to design the solution in a way that such an extension could be introduced in the future.  Some users build (lib)curl with a configuration where HTTPS is the only enabled protocol and they would not gain anything if the parallelization used a single server instance for each protocol.

**Comment by dfandrich** [comment]
Daniel's explanation is right. My design will see many copies (possibly
O(hundreds)) of the business end of runtests.pl running, each one starting
whatever servers are necessary to execute perhaps a couple of dozen tests. If
each test runner ends up being given one HTTPS test among its dozen, then each
runner will start its own copy of an HTTPS server. With some intelligence, I
hope to avoid that by passing HTTPS tests to runners that are specializing in
HTTPS and FTP test to runners specializing in FTP so avoid the inefficiencies
of starting too many of the same kind of server.

When I first looked at this problem last decade, I prototyped a simpler
solution that allowed running tests of different protocols only in parallel,
which only had one server of each type running globally. But, since 55% of
tests are for HTTP/HTTPS, that solution could never drop the testing time even
in half so I didn't pursue it.

**Comment by dfandrich** [comment]
Step 2 in the implementation plan is complete, so the test suite is now at a point where it should be possible to run multiple test runner processes (each with their own test servers) in their own log directories without stepping on each other.

**Comment by dfandrich** [comment]
I'm finally seeing some fruit from all these changes. I'm getting sub-40 second test runs now (running 1494 tests) on my development branch on an old 6-core PC. If you drop the last 10 tests (which are slow ones) the time plummets to about 28 seconds (running 1484 tests). This is with a simplistic test scheduler and some known inefficiencies, so there's room to go down from here.
