### ISSUE TITLE
HTTP/2 missing textual status

### ISSUE THREAD

**Issue by silverwind** [curl/curl#1081]
### I did this
````
$ curl -sI https://silverwind.io | grep HTTP
HTTP/2 200
````
### I expected the following
````
$ curl -sI https://silverwind.io | grep HTTP
HTTP/2 200 OK
````
### curl/libcurl version
````
curl 7.51.0-DEV (armv7l-unknown-linux-gnueabihf) libcurl/7.51.0-DEV OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.7.0 nghttp2/1.15.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets
````
### operating system
````
Linux 4.4.23 armv7l
````

**Comment by bagder** [comment]
HTTP/2 has no such textual status in the protocol so there's really nothing to show!

**Comment by silverwind** [comment]
I know the text status is not in the protocol any more, but it'd certainly make it easier to read if it could be 'emulated'.

**Comment by bagder** [comment]
How would that work? A busload of texts to insert, one for each response code? I really don't see how that would be useful to anyone.

**Comment by silverwind** [comment]
Yes, a simple lookup in a mapping of status code to reason-phrase in [this table](https://tools.ietf.org/html/rfc7231#page-49). `200` becomes `200 OK`, `301` becomes `301 Moved Permanently`. If there's no phrase for a given code, print none.

Regarding the argument that this is not in the protocol, one could also say the string `'HTTP/2 200'` does not appear as curl prints it, so I think that argument is naught.

**Comment by bagder** [comment]
`HTTP/2 200` is provided to make the response look similar to how responses used to do with HTTP/1, in order to aid applications and users to enable HTTP/2 with less trouble and efforts.

Even in [HTTP/1.1](https://tools.ietf.org/html/rfc7230#section-3.1.2) the "reason-phrase" could be empty, so this still looks like a status-line could look like in the past.

**Comment by bagder** [comment]
I don't think curl needs to do this. I think it is wasteful to include a whole bunch of fixed strings only to include them in the status-line in the portion that clients *SHOULD ignore* according to spec.
