### ISSUE TITLE
CURLOPT_WRITEFUNCTION told to write too much data when any PIPELINING is enabled

### ISSUE THREAD

**Issue by edkimmel** [curl/curl#1082]
### I did this

I implemented the following example, actually writing data instead of discarding it.
https://curl.haxx.se/libcurl/c/asiohiper.html
I also added the following option:

curl_multi_setopt(multiHandle, CURLMOPT_PIPELINING, CURLPIPE_HTTP1);

If I make a batch of ~30 requests to the same server, I will regularly get a connection reading much more data than expected. E.g. a 380k png file ended up writing 1.1mb of data, all in 16384 chunks.
### I expected the following

The connections are correctly told how much data to write
### curl/libcurl version

curl 7.50.3
### operating system

Android armv7

**Comment by bagder** [comment]
Can you provide us with a full example source code that when runs repeats the problem for you?

Pipelining is unfortunately a known weak point in libcurl that has never gotten the sufficient attention to make flawless.

**Comment by edkimmel** [comment]
I've updated curl and my integration to match the new asiohiper example. All seems good 👍

**Comment by jay** [comment]
That example still has an outstanding bug, see https://github.com/curl/curl/pull/1219. Since I and some of the other developers aren't familiar with boost::asio it's very difficult to review examples like that. So bear in mind there's likely to be issues still.

**Comment by edkimmel** [comment]
I do have one particular piece of code that differs from the sample at https://curl.haxx.se/libcurl/c/asiohiper.html, that did fix a crash for me.

My "event_cb" function takes a curl_socket_t  parameter instead of a boost::asio::ip::tcp::socket. The very beginning of my function then checks that the curl_socket_t is in the socket_map.

I made a quick gist with the changes in asiohiper. There might be a syntax bug in there, but it shows the change https://gist.github.com/edkimmel/dd247ef222d581d09748b4c9ae90ac15

What that catches is the case where event_cb is called after close_socket/remsock

**Comment by bagder** [comment]
> What that catches is the case where event_cb is called after close_socket/remsock

That sounds like a different issue than what this is about. Can you perhaps make a pull request out of it so that we can see the difference better? At least a separate issue.
