### ISSUE TITLE
CURLOPT_CONNECTTIMEOUT man page:

### ISSUE THREAD

**Issue by xiaofuhub** [curl/curl#10826]
In the process of verifying the connection timeout, I set the parameter to 60 or 0. When viewing through the log, the connection timeout is prompted after only 21s, so I doubt whether the default value has been modified, and the relevant documents are not synchronized, or I verify problem with the way?

/* Complete the connection within 60 seconds */
curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 60L);

Log callback connect timer out 21049ms.

**Comment by dfandrich** [comment]
What resolver are you using?

**Comment by bagder** [comment]
`CURLOPT_CONNECTTIMEOUT` sets the *maximum* time you allow. The connect can still timeout and fail "on its own" - if the TCP stack decides for itself that has tried enough number of times already. This is not a bug, this is just how it works.

**Comment by xiaofuhub** [comment]
@bagder @dfandrich Thank you for your reply
