### ISSUE TITLE
The CPU usage of Curl_poll is high.

### ISSUE THREAD

**Issue by SaltedFishLChen** [curl/curl#10825]
### I did this

call curl_easy_perform function in my code 

According to the captured data
the CPU usage of __poll is 92% of that of Curl_poll.
the CPU usage of entry_SYSCALL_64_after_hwframe is 94% of that of __poll

thread stach

```
#0  0x00007f88e4a160ee in poll () from /usr/lib64/libc.so.6
#1  0x00007f88e7e854ba in poll (__timeout=<optimized out>, __nfds=1, __fds=0x7f861e7f20a0) at /usr/include/bits/poll2.h:46
#2  Curl_poll (ufds=0x7f861e7f20a0, nfds=1, timeout_ms=<optimized out>) at select.c:374
#3  0x00007f88e7e85583 in Curl_socket_check (readfd0=-1, readfd1=-1, writefd=252, timeout_ms=<optimized out>) at select.c:286
#4  0x00007f88e7ea91ee in Curl_is_connected (data=0x7f86100049f0, conn=0x7f86100067b0, sockindex=0, connected=<optimized out>) at connect.c:918
#5  0x00007f88e7e819b3 in multi_runsingle (multi=multi@entry=0x7f8610038630, nowp=nowp@entry=0x7f861e7f2370, data=data@entry=0x7f86100049f0) at multi.c:1956
#6  0x00007f88e7e82c9e in curl_multi_perform (multi=0x7f8610038630, running_handles=0x7f861e7f2478) at multi.c:2559
#7  0x00007f88e7e76b93 in easy_transfer (multi=<optimized out>) at easy.c:606
#8  easy_perform (events=false, data=0x7f86100049f0) at easy.c:696
#9  curl_easy_perform (data=0x7f86100049f0) at easy.c:715
```

### I expected the following

I want to know if the CPU usage is increasing due to an operating system exception or a code logic exception.

### curl/libcurl version

curl 7.78.0

**Comment by dfandrich** [comment]
That curl version is 15 releases out of date, and we've fixed 1855 bugs since
then. I recall one of those was one that fixed similar symptoms to what you're
describing. I recommend trying the latest version and seeing if you still have
the problem.

**Comment by SaltedFishLChen** [comment]
Since this is a sporadic issue, I can't confirm if the issue has been fixed with a replacement version at this time.

Can you recall the description of the problem? I can look it up.

**Comment by dfandrich** [comment]
I don't recall. It will probably say "busy loop" or "eat cpu" or something.  Here are some issues to start looking at: #10449 #10618 #9122 #8739 #8688 #7589 #7240

**Comment by bagder** [comment]
If you see high CPU usage with a specific command line then please provide that command line, and please try this with a recent version so that we don't have to chase ghost problems. Also, you did not mention what platform you're seeing this on.

**Comment by bagder** [comment]
I recommend doing a git bisect to find the fix. As this problem is fixed in the latest release, it is good enough for us!
