### ISSUE TITLE
SFTP error: Failure establishing ssh session: -12, 

### ISSUE THREAD

**Issue by mikeduglas** [curl/curl#10830]
### I did this
curl -k sftp://server.org.za/ --user "username:password"

### The result in curl 7.85 and newer up to the latest 8.0.1
*   Trying 111.222.33.444:22...
* Connected to server.org.za (111.222.33.444) port 22 (#0)
* Failure establishing ssh session: -12, 
* Closing connection 0
curl: (2) Failure establishing ssh session: -12, 

### I expected the following (curl 7.84 and older)
*   Trying 111.222.33.444:22...
* Connected to server.org.za (111.222.33.444) port 22 (#0)
* SSH MD5 public key: NULL
* SSH SHA256 public key: NULL
* SSH authentication methods available: password,keyboard-interactive
* Initialized password authentication
* Authentication complete
* Connection #0 to server.org.za left intact

### curl/libcurl version 8.0.1

curl 8.0.1 (i686-w64-mingw32) libcurl/8.0.1 OpenSSL/3.0.8 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 WinIDN libssh2/1.10.0 nghttp2/1.52.0 ngtcp2/0.13.1 nghttp3/0.9.0 libgsasl/2.2.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### curl/libcurl version 7.84.0

curl 7.84.0 (i386-pc-win32) libcurl/7.84.0 OpenSSL/3.0.4 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.48.0 ngtcp2/0.6.0 nghttp3/0.5.0 libgsasl/1.10.0
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets

**All binaries downloaded from https://curl.se/windows/** 

### operating system
Windows 10, 11.

### Note
curl 8.0.1 works as expected with free public SFTP servers, for example I tested test.rebex.net (see https://www.sftp.net/public-online-sftp-servers).

**Comment by johandkdes** [comment]
I have the same problem.

**Comment by mikeduglas** [comment]
@bagder Is there any updates on this?

**Comment by bagder** [comment]
Please tell us how to reproduce this. `server.org.za` does not resolve and I have no account there.

**Comment by johandkdes** [comment]
Hi @bagder ,
You can test on: hub.sacrra.org.za
SFTP
Port 22
It fails with or without a user & password.

Hope this helps.
Please let me know if you need more information.

**Comment by johandkdes** [comment]
Hi @bagder,

Any update/news on this?

**Comment by bagder** [comment]
Did you try with libssh2 1.11.0 ?

**Comment by mikeduglas** [comment]
curl v8.1.2.2 with libssh2 v1.11.0 works as expected. Thanks.

**Comment by apiskors** [comment]
Can you clarify how curl v8.1.2.2 and/or libssh2 v1.11.0 fix the problem, please?

I have this same problem using the curl 7.81.0 packaged with Ubuntu 22.04.3 LTS.  For some sftp sites, it cannot connect at all, always giving a "Failure establishing ssh session" error every time.


```
$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
$ grep DISTRIB_DESCRIPTION /etc/lsb-release 
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by mikeduglas** [comment]
Sorry, I have no idea how exactly they fixed the problem, I'm not a curl dev.

**Comment by dfandrich** [comment]
libssh2 1.11 added a number of new crypto algorithms. OpenSSH servers disabled some of the older ones by default recently so older libssh2 clients sometimes weren't able to agree on a mutual set of algorithms for a session.

**Comment by apiskors** [comment]
FYI, on Ubuntu 22.04.3 LTS we locally rebuilt the stock curl source packages "--with-libssh2 --without-libssh".  That was enough to fix this "Failure establishing ssh session" problem for us.  Our libssh2-1 package is still version 1.10.0-3.

Way back on 2018-08-11, Ubuntu purposely switched to building curl "--with-libssh --without-libssh2", while Debian has kept using "--with-libssh2 --without-libssh" all along.  I have no idea why Ubuntu wanted to use only the ssh-1 libraries and not ssh-2.  Here's that old change:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888449
curl: please conditionally disable libssh2 in Ubuntu

https://salsa.debian.org/debian/curl/-/commit/a7095c4ecd411e5d69512e2fa502db1f1e83bc9d
Disable libssh2 on Ubuntu

**Comment by bagder** [comment]
libssh and libssh2 are two separate libraries that both speak the SSH2 protocol. They have slightly different feature sets that have varied a little over time. I presume a specific feature at one point in time was the reason for the switch.
