### ISSUE TITLE
Compilation error on AIX OS 7100-03-03-1415

### ISSUE THREAD

**Issue by amandatta16** [curl/curl#1085]
### I did this

I compiled my program with the libcurl on AIX but got this issue:
curlrules.h", line 143.6: 1540-0231 (S) The array bound must be specified and must be a positive integral constant expression.
 
### I expected the following
I build the library on AIX got folders lib and include, used them to built my application but got error.

Same project building and running fine on other operating systems but failing on AIX

### curl/libcurl version

7.50.3

[curl -V output perhaps?]

### operating system

AIX OS 7100-03-03-1415

**Comment by bagder** [comment]
Please tell us more about your exact steps when you tried to build! Other people have managed to build curl 7.50.3 for AIX...

**Comment by amandatta16** [comment]
Thanks Bagder for replying, the problem i have found is conflict between 64bit Aix os and library i compiled was curl 7.50.3 may be 32 bit, so when i am giving 
 xlc++ libcurl.cpp -q64 libcurl.a
it is giving
 line 143.6: 1540-0231 (S) The array bound must be specified and must be a positive integral constant expression.

**Comment by bagder** [comment]
The 32 vs 64 bit problem is a known quirk. You can solve your libcurl install like mentioned in the [FAQ](https://curl.haxx.se/docs/faq.html#Install_libcurl_for_both_32bit_a) which is annoying. We want to have this issue fixed, and thus it is also mentioned in the [TODO](https://curl.haxx.se/docs/todo.html#Remove_the_generated_include_fil).

**Comment by amandatta16** [comment]
Thanks @bagder the FAQ helped and following commands helped to build 64 bit lib and header
export OBJECT_MODE=64
./configure CFLAGS=-q64
