### ISSUE TITLE
Mention SNI in the description of --resolve option

### ISSUE THREAD

**Issue by piotr-dobrogost** [curl/curl#10858]
Looking for a way to indicate server name (for SNI) when connecting using curl I found this https://stackoverflow.com/q/12941703/95735 and this https://curl.se/mail/archive-2015-01/0042.html both mentioning `--resolve` option as the solution.
However there's no mention of SNI in the description of `--resolve` option in the man page.
I think mentioning SNI in this description would be helpful.

**Comment by bagder** [comment]
But how? `--resolve` is really unrelated to SNI specifically. SNI is simply used when doing TLS handshakes so anything that does TLS to a named host will set the SNI field. `--resolve` simply helps the user to redirect that request to a custom IP address instead of what would otherwise be used...

**Comment by piotr-dobrogost** [comment]
Simply stating something like
> This option can be used to indicate server name for TLS Server Name Indication (SNI)

would be enough. Basically all that is needed is having SNI mentioned there somewhere :)

> `--resolve` is really unrelated to SNI specifically.
> `--resolve` simply helps the user to redirect that request to a custom IP address instead of what would otherwise be used...

The fact `--resolve` is unrelated to SNI specifically is exactly what makes it not obvious it can be used for SNI and the reason I'm suggesting mentioning this use case in the option's description. Having something like `--sni-hostname` mentioned in https://github.com/curl/curl/issues/607 would be way easier to find but not having it the second best thing is to better document what we have.

**Comment by bagder** [comment]
"This option can be used to indicate server name for TLS Server Name Indication (SNI)"

But since that's not true, it would be really weird to state that (and we can be sure someone would also report that as an issue). There's no dedicated curl option for using SNI, it will use it by itself always when using TLS.

**Comment by piotr-dobrogost** [comment]
What do you mean by "that's not true"? Do you mean that one does not indicate server name by passing this name as a value of this option? That's true but using this option "frees" the "main" curl's argument (url) as the one in which server name for SNI can be passed. So maybe something like

> This option can be used to "free" URL argument to curl for passing server name which will be used for TLS Server Name Indication (SNI)"


?
