### ISSUE TITLE
curl_easy_perform_failed (err: 7) - Failed to connect to xxx port 55443

### ISSUE THREAD

**Issue by tinypancake** [curl/curl#10863]
### I did this

My platform need to access other device by curl, but it occurs:

```
(230329_14:58:42.501)2023-03-29 06:58:42.470 [   61]  0 MRMLoggerDelegate:WHA:text=Device\:sendRemoteCommand\:url\=https\://xxx/control\, port\=55443\, body\=cmd\=getPeerCapabilities\, timeout\=10
(230329_14:58:42.501)2023-03-29 06:58:42.470 [   63] 0 MRMLoggerDelegate:WHA:text=Device\:sendRemoteCommand\:url\=https\://xxx/control\, port\=55443\, body\=cmd\=getPeerCapabilities\, timeout\=10
(230329_14:58:42.501)2023-03-29 06:58:42.470 [   62] I MRMLoggerDelegate:WHA:text=Device\:testVisibility\:reason\=sending\,fetchingCapabilities\=1\,uniqueId\=XXe9cd
(230329_14:58:42.501)2023-03-29 06:58:42.471 [   62] 0 MRMLoggerDelegate:WHA:text=Device\:sendRemoteCommand\:url\=https\://xxx/control\, port\=55443\, body\=cmd\=getPeerCapabilities\, timeout\=10
(230329_14:58:43.596)2023-03-29 06:58:43.629 [   63] E MRMLoggerDelegate:WHA:text=Http1Client\:sendRemoteCommand\:curl_easy_perform failed\, err\=7
(230329_14:58:43.635)2023-03-29 06:58:43.629 [   63] W MRMLoggerDelegate:WHA:text=Http1Client\:sendRemoteCommand\:curlDebug\=[1159] Failed to connect to xxx port 55443 after 1159 ms\: Error
```

### I expected the following

```
(230329_16:11:35.604)2023-03-29 08:11:35.421 [ 3b] 0 MRMLoggerDelegate:WHA:text=Device\:sendRemoteCommand\:url\=https\://xxx/control\, port\=55443\, body\=cmd\=getPeerCapabilities\, timeout\=10
(230329_16:11:35.604)2023-03-29 08:11:35.421 [ 3c] I MRMLoggerDelegate:WHA:text=Device\:testVisibility\:reason\=sending\,fetchingCapabilities\=0\,uniqueId\=XX00DF
(230329_16:11:35.604)2023-03-29 08:11:35.421 [ 3c] 0 MRMLoggerDelegate:WHA:text=Device\:sendRemoteCommand\:url\=https\://xxx/control\, port\=55443\, body\=cmd\=testVisibility&originalIp\=192.168.1.101\, timeout\=10
(230329_16:11:35.604)2023-03-29 08:11:35.423 [ 35] I MRMLoggerDelegate:WHA:text=Device\:testVisibilityFailed\:uniqueId\=XXf4c9\,reason\=28\,bssid\=2\,essid\=2\,wifiFrequency\=0\,networkTypeGuesses\=GUESS_5_0_GHZ
(230329_16:11:35.678).424 [ 35] 0 MRMLoggerDelegate:WHA:text=Device\:addReachabilityResult\:uniqueId\=XXf4c9\,newReachabilityResult\=2
```

Can connect to xxx port 55443 successfully

### curl/libcurl version

```
sh-5.1# curl -V
curl 7.88.1 (arm-poky-linux-gnueabi) libcurl/7.88.1 OpenSSL/3.0.7 nghttp2/1.47.0
Release-Date: 2023-02-20
Protocols: file ftp ftps http https
Features: alt-svc HSTS HTTP2 Largefile NTLM SSL threadsafe TLS-SRP UnixSockets
```

### operating system

```
sh-5.1# uname -a
Linux aud8532p1-emmc-c4a-mt7921-test 4.14.87 #1 SMP PREEMPT Tue Mar 28 16:23:29 UTC 2023 armv7l GNU/Linux
```

**Comment by bagder** [comment]
Are you saying that curl 7.69.1 works (every time) and curl 7.88.1 fails to connect (every time) to the same server + port?

**Comment by tinypancake** [comment]
Yes, It seems very strange, maybe something related to HTTPS-proxy

**Comment by bagder** [comment]
Well, you are not providing much info so it's impossible for anyone to tell. How can we reproduce?

**Comment by tinypancake** [comment]
I will try to provide the steps to you, it takes time for me to make clear the connect flow

**Comment by kwind** [comment]
@bagder 
I have similar problem, when run test,such as,

> 
curl/tests/http % sudo pytest -k "test_01_basic" -vvv
Password:
================================================ test session starts ================================================
platform darwin -- Python 3.10.10, pytest-7.2.2, pluggy-1.0.0 -- /usr/local/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
Testing curl 8.1.0-DEV
  httpd: 2.4.56, http:60852 https:60853
  httpd-proxy: 2.4.56, http:60854 https:60855
rootdir: /Users/zhangfugang/code/curl/curl/tests/http
collected 122 items / 117 deselected / 5 selected                                                                   

test_01_basic.py::TestBasic::test_01_01_http_get ERROR                                                        [ 20%]
test_01_basic.py::TestBasic::test_01_02_https_get ERROR                                                       [ 40%]
test_01_basic.py::TestBasic::test_01_03_h2_get ERROR                                                          [ 60%]
test_01_basic.py::TestBasic::test_01_04_h2_unsupported ERROR                                                  [ 80%]
test_01_basic.py::TestBasic::test_01_05_h3_get SKIPPED (h3 not supported)                                     [100%]

====================================================== ERRORS =======================================================
__________________________________ ERROR at setup of TestBasic.test_01_01_http_get __________________________________

env = <testenv.env.Env object at 0x109945750>

    @pytest.fixture(scope='package')
    def httpd(env) -> Httpd:
        httpd = Httpd(env=env)
        assert httpd.exists(), f'httpd not found: {env.httpd}'
        httpd.clear_logs()
>       assert httpd.start()
E       assert False
E        +  where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>()
E        +    where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start

conftest.py:62: AssertionError
------------------------------------------------ Captured log setup -------------------------------------------------
DEBUG    testenv.httpd:httpd.py:182 Server still not responding after 0:00:05
_________________________________ ERROR at setup of TestBasic.test_01_02_https_get __________________________________

env = <testenv.env.Env object at 0x109945750>

    @pytest.fixture(scope='package')
    def httpd(env) -> Httpd:
        httpd = Httpd(env=env)
        assert httpd.exists(), f'httpd not found: {env.httpd}'
        httpd.clear_logs()
>       assert httpd.start()
E       assert False
E        +  where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>()
E        +    where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start

conftest.py:62: AssertionError
___________________________________ ERROR at setup of TestBasic.test_01_03_h2_get ___________________________________

env = <testenv.env.Env object at 0x109945750>

    @pytest.fixture(scope='package')
    def httpd(env) -> Httpd:
        httpd = Httpd(env=env)
        assert httpd.exists(), f'httpd not found: {env.httpd}'
        httpd.clear_logs()
>       assert httpd.start()
E       assert False
E        +  where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>()
E        +    where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start

conftest.py:62: AssertionError
_______________________________ ERROR at setup of TestBasic.test_01_04_h2_unsupported _______________________________

env = <testenv.env.Env object at 0x109945750>

    @pytest.fixture(scope='package')
    def httpd(env) -> Httpd:
        httpd = Httpd(env=env)
        assert httpd.exists(), f'httpd not found: {env.httpd}'
        httpd.clear_logs()
>       assert httpd.start()
E       assert False
E        +  where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>()
E        +    where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start

conftest.py:62: AssertionError
============================================== short test summary info ==============================================
ERROR test_01_basic.py::TestBasic::test_01_01_http_get - assert False
ERROR test_01_basic.py::TestBasic::test_01_02_https_get - assert False
ERROR test_01_basic.py::TestBasic::test_01_03_h2_get - assert False
ERROR test_01_basic.py::TestBasic::test_01_04_h2_unsupported - assert False
=================================== 1 skipped, 117 deselected, 4 errors in 11.96s ==...

curl/tests/http% **curl -V**
curl 8.0.1-DEV (x86_64-apple-darwin22.1.0) libcurl/8.0.1-DEV OpenSSL/3.1.0 zlib/1.2.11 libidn2/2.3.4 nghttp2/1.52.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

**The curl code branch**
 curl/tests/http % git branch -a
* master
remotes/origin/HEAD -> origin/master
......

**the commit id:**
curl/tests/http % git log
commit 0409f633202abf064d070008b5832cc240f110db (HEAD -> master, origin/master, origin/HEAD)
Author: Viktor Szakats <commit@vsz.me>
Date:   Fri Mar 31 18:03:43 2023 +0000

    cmake: do not add zlib headers for openssl
......

**But runtests.pl is success，as follows**：
curl/tests % ./runtests.pl 3 -s
********* System characteristics ******** 
* curl 8.1.0-DEV (x86_64-apple-darwin22.1.0) 
* libcurl/8.1.0-DEV OpenSSL/3.1.0 zlib/1.2.11 libidn2/2.3.4 nghttp2/1.52.0
* Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP TrackMemory UnixSockets
* Disabled: 
* Host: B-Q1BDMD6R-2034.local
* System: Darwin B-Q1BDMD6R-2034.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
* OS: darwin
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 206474
***************************************** 
test 0003...OK (1   out of 1  , remaining: 00:00, took 1.417s, duration: 00:01)
TESTDONE: 1 tests were considered during 1 seconds.
TESTDONE: 1 tests out of 1 reported OK: 100%

**Comment by kwind** [comment]
> @bagder hi， I have similar problem, when run test,such as,
> 
> > 
> 
> curl/tests/http % sudo pytest -k "test_01_basic" -vvv Password: ================================================ test session starts ================================================ platform darwin -- Python 3.10.10, pytest-7.2.2, pluggy-1.0.0 -- /usr/local/opt/python@3.10/bin/python3.10 cachedir: .pytest_cache Testing curl 8.1.0-DEV httpd: 2.4.56, http:60852 https:60853 httpd-proxy: 2.4.56, http:60854 https:60855 rootdir: /Users/zhangfugang/code/curl/curl/tests/http collected 122 items / 117 deselected / 5 selected
> 
> test_01_basic.py::TestBasic::test_01_01_http_get ERROR [ 20%] test_01_basic.py::TestBasic::test_01_02_https_get ERROR [ 40%] test_01_basic.py::TestBasic::test_01_03_h2_get ERROR [ 60%] test_01_basic.py::TestBasic::test_01_04_h2_unsupported ERROR [ 80%] test_01_basic.py::TestBasic::test_01_05_h3_get SKIPPED (h3 not supported) [100%]
> 
> ====================================================== ERRORS ======================================================= __________________________________ ERROR at setup of TestBasic.test_01_01_http_get __________________________________
> 
> env = <testenv.env.Env object at 0x109945750>
> 
> ```
> @pytest.fixture(scope='package')
> def httpd(env) -> Httpd:
>     httpd = Httpd(env=env)
>     assert httpd.exists(), f'httpd not found: {env.httpd}'
>     httpd.clear_logs()
> ```
> 
> > ```
> >   assert httpd.start()
> > ```
> 
> E assert False E + where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>() E + where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start
> 
> conftest.py:62: AssertionError ------------------------------------------------ Captured log setup ------------------------------------------------- DEBUG testenv.httpd:httpd.py:182 Server still not responding after 0:00:05 _________________________________ ERROR at setup of TestBasic.test_01_02_https_get __________________________________
> 
> env = <testenv.env.Env object at 0x109945750>
> 
> ```
> @pytest.fixture(scope='package')
> def httpd(env) -> Httpd:
>     httpd = Httpd(env=env)
>     assert httpd.exists(), f'httpd not found: {env.httpd}'
>     httpd.clear_logs()
> ```
> 
> > ```
> >   assert httpd.start()
> > ```
> 
> E assert False E + where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>() E + where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start
> 
> conftest.py:62: AssertionError ___________________________________ ERROR at setup of TestBasic.test_01_03_h2_get ___________________________________
> 
> env = <testenv.env.Env object at 0x109945750>
> 
> ```
> @pytest.fixture(scope='package')
> def httpd(env) -> Httpd:
>     httpd = Httpd(env=env)
>     assert httpd.exists(), f'httpd not found: {env.httpd}'
>     httpd.clear_logs()
> ```
> 
> > ```
> >   assert httpd.start()
> > ```
> 
> E assert False E + where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>() E + where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start
> 
> conftest.py:62: AssertionError _______________________________ ERROR at setup of TestBasic.test_01_04_h2_unsupported _______________________________
> 
> env = <testenv.env.Env object at 0x109945750>
> 
> ```
> @pytest.fixture(scope='package')
> def httpd(env) -> Httpd:
>     httpd = Httpd(env=env)
>     assert httpd.exists(), f'httpd not found: {env.httpd}'
>     httpd.clear_logs()
> ```
> 
> > ```
> >   assert httpd.start()
> > ```
> 
> E assert False E + where False = <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>>() E + where <bound method Httpd.start of <testenv.httpd.Httpd object at 0x109a0a3e0>> = <testenv.httpd.Httpd object at 0x109a0a3e0>.start
> 
> conftest.py:62: AssertionError ============================================== short test summary info ============================================== ERROR test_01_basic.py::TestBasic::test_01_01_http_get - assert False ERROR test_01_basic.py::TestBasic::test_01_02_https_get - assert False ERROR test_01_basic.py::TestBasic::test_01_03_h2_get - assert False ERROR test_01_basic.py::TestBasic::test_01_04_h2_unsupported - assert False =================================== 1 skipped, 117 deselected, 4 errors in 11.96s ==...
> 
> curl/tests/http% **curl -V** curl 8.0.1-DEV (x86_64-apple-darwin22.1.0) libcurl/8.0.1-DEV OpenSSL/3.1.0 zlib/1.2.11 libidn2/2.3.4 nghttp2/1.52.0 Release-Date: [unreleased] Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
> 
> **The curl code branch** curl/tests/http % git branch -a
> 
> * master
>   remotes/origin/HEAD -> origin/master
>   ......
> 
> **the commit id:** curl/tests/http % git log commit [0409f63](https://github.com/curl/curl/commit/0409f633202abf064d070008b5832cc240f110db) (HEAD -> master, origin/master, origin/HEAD) Author: Viktor Szakats [commit@vsz.me](mailto:commit@vsz.me) Date: Fri Mar 31 18:03:43 2023 +0000
> 
> ```
> cmake: do not add zlib headers for openssl
> ```
> 
> ......
> 
> **But runtests.pl is success，as follows**： curl/tests % ./runtests.pl 3 -s ********* System characteristics ********
> 
> * curl 8.1.0-DEV (x86_64-apple-darwin22.1.0)
> * libcurl/8.1.0-DEV OpenSSL/3.1.0 zlib/1.2.11 libidn2/2.3.4 nghttp2/1.52.0
> * Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP TrackMemory UnixSockets
> * Disabled:
> * Host: B-Q1BDMD6R-2034.local
> * System: Darwin B-Q1BDMD6R-2034.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
> * OS: darwin
> 
> *** DISABLES memory tracking when using threaded resolver *
> 
> * Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6
> * Env:
> * Seed: 206474
> 
> test 0003...OK (1 out of 1 , remaining: 00:00, took 1.417s, duration: 00:01) TESTDONE: 1 tests were considered during 1 seconds. TESTDONE: 1 tests out of 1 reported OK: 100%

the curl.trace:
15:19:37.125160 == Info: !!! WARNING !!!
15:19:37.125763 == Info: This is a debug build of libcurl, do not use in production.
15:19:37.125789 == Info: Added one.http.curl.se:60852:127.0.0.1 to DNS cache
15:19:37.125802 == Info: STATE: INIT => CONNECT handle 0x7f8ab1011c08; line 1950 (connection #-5000)
15:19:37.125853 == Info: Added connection 0. The cache now contains 1 members
15:19:37.125863 == Info: Hostname one.http.curl.se was found in DNS cache
15:19:37.125874 == Info: STATE: CONNECT => CONNECTING handle 0x7f8ab1011c08; line 2003 (connection #0)
15:19:37.125951 == Info:   Trying 127.0.0.1:60852...
15:19:37.126069 == Info: connect to 127.0.0.1 port 60852 failed: Connection refused
15:19:37.126083 == Info: Failed to connect to one.http.curl.se port 60852 after 0 ms: Couldn't connect to server
15:19:37.126092 == Info: multi_done: status: 7 prem: 1 done: 0
15:19:37.126101 == Info: multi_done, not re-using connection=0, forbid=0, close=0, premature=1, conn_multiplex=0
15:19:37.126109 == Info: The cache now contains 0 members
15:19:37.126114 == Info: Curl_disconnect(conn #0, dead=1)
15:19:37.126123 == Info: Closing connection 0
15:19:37.126132 == Info: Expire cleared (transfer 0x7f8ab1011c08)

**Comment by bagder** [comment]
Any updates?

**Comment by bagder** [comment]
Dead
