### ISSUE TITLE
curl8.0.1

### ISSUE THREAD

**Issue by zjp99** [curl/curl#10873]
Failed sending data to the peer
Failure when receiving data from the peer
--------------------------------------------
I have encountered the above problems in the process of using；I don't seem to get it when I initialize every post request;
But I get this problem occasionally when I only want to initialize it once;
I want to save initialization time. How do I do that
 CURL* pCurl;
 pCurl = curl_easy_init();

**Comment by dfandrich** [comment]
Sorry about the race condition—I referenced the wrong issue.

**Comment by dfandrich** [comment]
You'll have to give more information. Can you provide a code snippet that reproduces the issue? Please include the curl -V output for the libcurl you're using. You'd be better off following the bug template next time.
