### ISSUE TITLE
curl: (6) getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by vnkgd** [curl/curl#10871]
We have problems with download files and send statistic from our desktop products.
So I made test with bad internet, using desktop app "clumsy v0.2" with option: inbound/all receiving packets (all Functions exept Tamper)
and try to download with curl small file (for example: curl https://habrastorage.org/getpro/habr/upload_files/106/e73/26d/106e7326d6ba2a4de75fb99a61f9ab6e.JPG) I get message: curl: (6) getaddrinfo() thread failed to start
When I use browser it works, download this file with no problem.
When I use wget, no problem. even with Functions "Tamper" it works (not allways, because this function realy broke connection).
Can you please help to figure out with it?

**Comment by bagder** [comment]
What platform? Which curl version?

**Comment by vnkgd** [comment]
Windows 10, any version of curl, even with 8.0.1

**Comment by jay** [comment]
Is the error message shown immediately or does it take some time, and if so how much time?

There was a report of that error message but it related to socketpair initialization, see #10561. If you have a way to reproduce you could try sprinkling some printfs in [Curl_socketpair](https://github.com/curl/curl/blob/curl-8_0_1/lib/socketpair.c#L62) to see if that is what is failing.

**Comment by vnkgd** [comment]
It takes 20 sec to wait, then I see message.
Сan you please try?: https://jagt.github.io/clumsy/ "clumsy v0.2" with option: inbound/all receiving packets (all Functions exept Tamper)
Why download works with browser and in wget, but doesn't work in curl?

Is there any way without printfs in code? just in command line?

**Comment by bagder** [comment]
I don't have any ideas for actions on this issue from our end. I think you need to keep researching while it can't start the thread in your case. We have a vast amount of curl users on Windows and you are the only one who reports this issue...
