### ISSUE TITLE
libcurl.so: undefined reference to 'fcntl64@GLIBC_2.28'

### ISSUE THREAD

**Issue by houaohui** [curl/curl#10885]
using arm-linux-gnueabihf-gcc coss compiler version 9.4.0，it coms this error:
libcurl.so: undefined reference to 'fcntl64@GLIBC_2.28'
but my cross compiler's GLIBC version is 2.31, Is it because my version is too high and there is no fcntl64 implementation?  should I lower the version and recompile? Does anyone know what to do?

**Comment by bagder** [comment]
I don't think this is a curl problem.

**Comment by houaohui** [comment]
this is my build option
```
./configure --host=arm-linux-gnueabihf --with-ssl=/home/hah/Downloads/openssl-3.1.0/build/install  --with-zlib=/home/hah/Downloads/zlib-1.2.11/build/install --enable-shared  --enable-static --prefix=$(pwd)/build/install CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ --without-zstd --enable-static --enable-zlib

make
make install
```
using nm tool I find the host glibc has two fcntl definition 
```
nm -D libc.so.6 
000000000010e470 W fcntl
000000000010e470 W fcntl64
```
but my coss compiler glibc only has one
`0008a271 W fcntl`
I dont konw if the compile curl link glibc link is wrong and linked to the local one , because in the configuration did not specify that the linked libeary is the cross-compiler glic

**Comment by houaohui** [comment]
I specified the coss-compiler's path and library,:
`./configure --host=arm-linux-gnueabihf --with-ssl=/home/hah/Downloads/openssl-3.1.0/build/install  --with-zlib=/home/hah/Downloads/zlib-1.2.11/build/install --enable-shared  --enable-static --prefix=$(pwd)/build/install CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ CFLAGS=-I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include LDFLAGS=-L/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/lib --without-zstd --enable-static --enable-zlib`
finally fcntl64 disappeared but this error appeared:
`libcurl.so: undefined reference to `fcntl@GLIBC_2.28'`
But luckily, compiled successfuly when using libcurl.a
but still dont know what the reason is

**Comment by TravoltaG** [comment]
This should resolve your errors
_--allow-shlib-undefined_
