### ISSUE TITLE
Incompatible pointer type in cleanarg() function (Windows build)

### ISSUE THREAD

**Issue by lordmulder** [curl/curl#10888]
I think `cleanarg()` in "tool_getparam.c" is incorrect on platforms where `argv_item_t` is `wchar_t` (e.g. Windows).

This has been observed in curl 8.0.1 when building with MSYS2/mingw-w64 on Windows:
```
tool_getparam.c: In function 'cleanarg':
tool_getparam.c:555:25: warning: passing argument 1 of 'strlen' from incompatible pointer type [-Wincompatible-pointer-types]
  555 |     size_t len = strlen(str);
      |                         ^~~
      |                         |
      |                         wchar_t * {aka short unsigned int *}
In file included from C:/msys64/mingw32/include/guiddef.h:154,
                 from C:/msys64/mingw32/include/winnt.h:648,
                 from C:/msys64/mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw32/include/windef.h:9,
                 from C:/msys64/mingw32/include/windows.h:69,
                 from ../lib/setup-win32.h:57,
                 from ../lib/curl_setup.h:248,
                 from tool_setup.h:38,
                 from tool_getparam.c:24:
C:/msys64/mingw32/include/string.h:64:37: note: expected 'const char *' but argument is of type 'wchar_t *' {aka 'short unsigned int *'}
   64 |   size_t __cdecl strlen(const char *_Str);
      |                         ~~~~~~~~~~~~^~~~

```

**Function in question:**
```
#ifdef HAVE_WRITABLE_ARGV
static void cleanarg(argv_item_t str)
{
  /* now that GetStr has copied the contents of nextarg, wipe the next
   * argument out so that the username:password isn't displayed in the
   * system process list */
  if(str) {
    size_t len = strlen(str);
    memset(str, ' ', len);
  }
}
#else
#define cleanarg(x)
#endif
```

**Suggested fix:**
```
#ifdef HAVE_WRITABLE_ARGV
static void cleanarg(argv_item_t str)
{
  /* now that GetStr has copied the contents of nextarg, wipe the next
   * argument out so that the username:password isn't displayed in the
   * system process list */
  if(str) {
#ifdef _UNICODE
    size_t len = wcslen(str);
    wmemset(str, L' ', len);
#else
    size_t len = strlen(str);
    memset(str, ' ', len);
#endif
  }
}
#else
#define cleanarg(x)
#endif
```

**Compare to definition of `argv_item_t`:**
```
#ifdef __VMS
#define argv_item_t  __char_ptr32
#elif defined(_UNICODE)
#define argv_item_t wchar_t *
#else
#define argv_item_t  char *
#endif
```

Thank you.

**Comment by gvanem** [comment]
How about simply:
```c
  if(str) {
    size_t len = sizeof(*str) * _tcslen(str);
    memset(str, ' ', len);
  }
```

**Comment by jay** [comment]
I thought that HAVE_WRITABLE_ARGV was not for Windows? Windows processes have a command line and then arguments are parsed from that and put into argv array, but changing that array doesn't change the command line.

**Comment by bagder** [comment]
Good catch. How come this windows build think it has a writable argv[] ?

**Comment by jay** [comment]
Well it does have a writable argv I just thought we weren't doing that HAVE_WRITABLE_ARGV clearing for Windows . The configure [test program](https://github.com/curl/curl/blob/3da642c4f0cc7dbc0bc428f8028e2b45f1eca379/configure.ac#L1789) just shows that argv is modifiable, which it is in programs built with VS2022 and msys2. Since only the latter uses autotools configure it is only defined there. Maybe we should call it ENABLE_CLEAN_ARG or something instead, and not define it for Windows.

**Comment by jay** [comment]
here's a quick fix

~~~diff
diff --git a/src/tool_getparam.c b/src/tool_getparam.c
index 6d6cac3..9a6ee73 100644
--- a/src/tool_getparam.c
+++ b/src/tool_getparam.c
@@ -545,7 +545,7 @@ static ParameterError GetSizeParameter(struct GlobalConfig *global,
   return PARAM_OK;
 }
 
-#ifdef HAVE_WRITABLE_ARGV
+#if defined(HAVE_WRITABLE_ARGV) && !defined(WIN32)
 static void cleanarg(argv_item_t str)
 {
   /* now that GetStr has copied the contents of nextarg, wipe the next
@@ -697,7 +697,7 @@ ParameterError getparameter(const char *flag, /* f or -long-flag */
     "ftps",
     NULL
   };
-#ifdef HAVE_WRITABLE_ARGV
+#if defined(HAVE_WRITABLE_ARGV) && !defined(WIN32)
   argv_item_t clearthis = NULL;
 #else
   (void)cleararg;
@@ -783,7 +783,7 @@ ParameterError getparameter(const char *flag, /* f or -long-flag */
       else if(!nextarg)
         return PARAM_REQUIRES_PARAMETER;
       else {
-#ifdef HAVE_WRITABLE_ARGV
+#if defined(HAVE_WRITABLE_ARGV) && !defined(WIN32)
         clearthis = cleararg;
 #endif
         *usedarg = TRUE; /* mark it as used */
~~~

**Comment by bagder** [comment]
Makes sense. But I suppose the real fix is to make sure the define is not set on Windows since it doesn't do any good there.

**Comment by bagder** [comment]
I don't think we would mind if someone would implement Windows support for this. It feels like a separate topic to me.

**Comment by lordmulder** [comment]
> Good catch. How come this windows build think it has a writable argv[] ?

In Windows, the command-line is available in the global variables `_acmdln` (ANSI) and `_wcmdln` (Unicode).

The `argv[]` array is created by the C runtime before it invokes `main()` or `wmain()`.

You _can_ modify/clear  `argv[]`, but it won't hide anything from Task Manager et al.

Instead, in order to hide sensitive information from command-line, you must wipe out  `_acmdln` and `_wcmdln` 😈 

```C
#include <stdio.h>
#include <memory.h>
#include <wchar.h>

_CRTIMP char **__cdecl __p__acmdln(void);
#define _acmdln (*__p__acmdln())
_CRTIMP wchar_t **__cdecl __p__wcmdln(void);
#define _wcmdln (*__p__wcmdln())

int main()
{
	printf("_acmdln: \"%s\"\n", _acmdln);
	wprintf(L"_wcmdln: \"%s\"\n", _wcmdln);
	puts("");

	memset(_acmdln, 'x', strlen(_acmdln));
	wmemset(_wcmdln, L'x', wcslen(_wcmdln));

	printf("_acmdln: \"%s\"\n", _acmdln);
	wprintf(L"_wcmdln: \"%s\"\n", _wcmdln);
	puts("");

	getchar();
}
```

![grafik](https://user-images.githubusercontent.com/470590/230475672-eb4ffff7-608d-425b-85f0-6eef01975c08.png)

**Comment by bagder** [comment]
`HAVE_WRITABLE_ARGV` should no longer be defined on Windows. Doesn't that sort of address this problem?

**Comment by lordmulder** [comment]
Well, it "solves" the problem by **not** clearing the command-line at all, I think 😏 

If you want the command-line to be cleared, as it was supposed to work, we need to wipe out `_acmdln` and `_wcmdln`.

**Comment by jay** [comment]
The issue you reported has been addressed. If you want to file a separate issue to add support for hiding the command line in native Windows builds you can. I will be against it.
