### ISSUE TITLE
libtool solaris 11.4 error

### ISSUE THREAD

**Issue by AIIleG** [curl/curl#10902]
Hi,

I ran into an issue with libtool on solaris 11.4. I tried differet curl versions down to 7.67 but they all have the same problem. Here is the line in question:

```
libtool: link: /usr/bin/nm -p  .libs/libcurl_la-altsvc.o .libs/libcurl_la-amigaos.o .libs/libcurl_la-asyn-ares.o
<snip>
vquic/.libs/libcurl_la-curl_ngtcp2.o vquic/.libs/libcurl_la-curl_quiche.o vquic/.libs/libcurl_la-vquic.o vssh/.libs/libcurl_la-libssh.o vssh/.libs/libcurl_la-libssh2.o vssh/.libs/libcurl_la-wolfssh.o   |  | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libcurl.exp
../libtool[1887]: eval: syntax error at line 1: `|' unexpected
gmake[2]: *** [Makefile:1683: libcurl.la] Error 3
```

So as you can see a bunch is missing at the end. Funny enough it works just fine on 11.2. Here is how it it looks there:

```
vssh/.libs/libcurl_la-libssh.o vssh/.libs/libcurl_la-libssh2.o vssh/.libs/libcurl_la-wolfssh.o   | /usr/bin/sed -n -e 's/^.*[	 ]\([BDRT][BDRT]*\)[	 ][	 ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' | /usr/bin/sed '/ __gnu_lto/d' | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libcurl.exp
```
Any help would be welcome!

**Comment by dfandrich** [comment]
This does look like a libtool issue. Try running 'libtoolize -fi' in the
pristine source tree on the working system, then copy the entire tree onto the
non-working system and try compiling it there again.  If Solaris has local
changes to its libtool system to get it working there that haven't been
upstreamed, this should fix it.

**Comment by dfandrich** [comment]
Instead of libtoolize -fi, try autoreconf -fi. That also updates (downgrades?)
autoconf files (not just libtool), since there's a relationship between their
versions.

**Comment by bagder** [comment]
This is most likely a libtool issue.
