### ISSUE TITLE
Coverity warns on suspected "Copy-paste error"

### ISSUE THREAD

**Issue by bagder** [curl/curl#10907]
It does look suspicious so it could use your double-check @icing!

This is the code:

https://github.com/curl/curl/blob/403364293005ed54ef6230a214acee43e867995d/lib/http2.c#L1035-L1038

The if() check uses `data`, `Curl_expire()` is called for `data` but `drain_this` uses `data_s` ...

It *looks* like most of them should rather use `data_s` ?

**Comment by icing** [comment]
Fix proposed in #10924.

**Comment by icing** [comment]
Fix was merged.
