### ISSUE TITLE
New min size for SIZEOF_CURL_OFF_T breaks MS-DOS/DJGPP build

### ISSUE THREAD

**Issue by SuperIlu** [curl/curl#10905]
### I did this
Try building curl with mbedTLS-2.28.3 and DJGPP yields the following error
```
In file included from base64.c:27:
curl_setup.h:445:2: error: #error "too small curl_off_t"
  445 | #error "too small curl_off_t"
      |  ^~~~~
```
Build is done using the following command line
`make -C $(CURL)/lib -f Makefile.mk CFG=-zlib-mbedtls-watt TRIPLET=i586-pc-msdosdjgpp WATT_ROOT=$(WATT32)`

### I expected the following
Working build as with 7.87.0

### curl/libcurl version
source release for 8.0.1

### operating system
MS-DOS/DJGPP using i586-pc-msdosdjgpp-gcc (GCC) 12.2.0

### cause of error
The change from https://github.com/curl/curl/pull/10597 is not compatible with the SIZEOF_CURL_OFF_T as defined in `curl-8.0.1\lib\config-dos.h`

### Solution
The build works if I use `#define SIZEOF_CURL_OFF_T 8` in `curl-8.0.1\lib\config-dos.h`. My TLS tests are still able to do HTTPS requests as with 7.87.0

**Comment by bagder** [comment]
Would you be able to provide a PR with the change that makes it work for you?

**Comment by SuperIlu** [comment]
Sure, I'll try to get that done tomorrow...

**Comment by gvanem** [comment]
> The build works if I use #define SIZEOF_CURL_OFF_T 8 in curl-8.0.1\lib\config-dos.h

I also did that and libcurl compiled on DJGPP. But I've not tried it. I assume it wont be able to transfer anything 
above > 2 GByte with this 32-bit `off_t`. But I see there is a  `typedef long long off64_t;` in DJGPP which is AFAICS
effective for `fseeko64()` only.

**Comment by SuperIlu** [comment]
Did some more tests yesterday with DOStodon and I noticed no problems.
