### ISSUE TITLE
Building with --enable-debug causes lots of warnings

### ISSUE THREAD

**Issue by tatsuhiro-t** [curl/curl#1091]
### I did this

./configure --enable-debug
and `make` printed lots of warnings like this:

```
/usr/bin/perl ../lib/checksrc.pl -D.        \
-W./tool_hugehelp.c ./*.[ch]
  CCLD     libcurltool.la
./hugehelp.c:25:83: warning: Longer than 79 columns (LONGLINE)
 "       curl  is  a tool to transfer data from or to a server, using one of the\n"
./hugehelp.c:26:83: warning: Longer than 79 columns (LONGLINE)
 "       supported protocols (DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS,  IMAP,\n"
...
./hugehelp.c:7668:11: warning: if with space (SPACEBEFOREPAREN)
         if (status == Z_STREAM_END)
           ^
./hugehelp.c:1:1: error: Missing copyright statement (COPYRIGHT)

 ^
checksrc: 0 errors and 1133 warnings
checksrc: 0 errors and 5 warnings suppressed
```
### I expected the following

`make` should finish without any warnings
### curl/libcurl version

I built from git master branch 2e750ce452c37ec4cd494538d2f3c94acde3e718
### operating system

Linux, clang 3.9.0

**Comment by jay** [comment]
Is it only hugehelp.c? In 7.29.0 the name was changed to tool_hugehelp.c and a lot has happened since then. Maybe that file is a leftover from bisecting?

**Comment by tatsuhiro-t** [comment]
You are right.  The error came from hugehelp.c only, and somehow it remained in my local disk drive.  Deleting it fixes issue.  Sorry for the noise.
