### ISSUE TITLE
Seg fault with 8.0.1-r2

### ISSUE THREAD

**Issue by InsOpDe** [curl/curl#10948]
I got with `8.0.1-r2` the following problem:
```
Segmentation fault      (core dumped) curl -s --header "PRIVATE-TOKEN:$RO_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA"
```
(didnt have it with r1)

**edit:**
Im running this on alpine `3.16.0` with `http://dl-cdn.alpinelinux.org/alpine/edge/community` as repository.

**Comment by bagder** [comment]
so what's the difference between `r1` and `r2`? Those are not our names/releases, those are the product of your distro presumably so only they know the difference. And you did not mention what distro/architecture/platform you're using.

We have no way to reproduce or analyze this as is.

**Comment by InsOpDe** [comment]
I was not aware that this repo wasnt responsible for these releases.

I have added the requested information as much as it was possible for me

**Comment by jzakrzewski** [comment]
From what I can tell, it's regular 8.0.1 release. No patches, etc.
Those are the configure options:
```
./configure \
		--build=$CBUILD \
		--host=$CHOST \
		--prefix=/usr \
		--enable-ipv6 \
		--enable-unix-sockets \
		--enable-static \
		--with-libidn2 \
		--with-nghttp2 \
		--with-openssl \
		--disable-ldap \
		--with-pic \
		--enable-websockets \
		--without-libssh2 # https://bugs.alpinelinux.org/issues/10222
```
See: https://git.alpinelinux.org/aports/tree/main/curl/APKBUILD?id=84a227baf001b6e0208e3352b294e4d7a40e93de

**Comment by InsOpDe** [comment]
Here is a repro with Docker (23.0.1 with buildkit enabled):
```
FROM alpine:3.16.0
RUN apk add --no-cache \
        --repository="http://dl-cdn.alpinelinux.org/alpine/edge/main" \
                curl
RUN curl --version
```

You can build it like so:
`docker build --progress=plain -t test .`

I earlier mentioned the alpine community repository - although this is the one I used: `http://dl-cdn.alpinelinux.org/alpine/edge/main`

**Comment by bagder** [comment]
The change from r1 to r2 causing this issue seems ... weird. AFAICT, this is the commit with the diff: https://git.alpinelinux.org/aports/commit/main/curl/APKBUILD?id=84a227baf001b6e0208e3352b294e4d7a40e93de

Ie: nothing in curl changed. Only something (unknown to me) in the distro.

**Comment by bagder** [comment]
Any chance you can build curl with debug symbols present and show us a stack trace of the crash?

**Comment by InsOpDe** [comment]
Im having this issue only inside Docker - so I'd need to build it inside Docker.

tbh i didnt build any thing from source, yet, so I dont currently have the expertise. However, it is possible that I  learn and build it on tuesday next week

**Comment by vszakats** [comment]
This was the commit message:
```
main/*: rebuild for dt_relr change
```
It touched 897 packages.

https://git.alpinelinux.org/aports/commit/?id=84a227baf001b6e0208e3352b294e4d7a40e93de

**Comment by vszakats** [comment]
I think they might have implemented this: https://maskray.me/blog/2021-10-31-relative-relocations-and-relr

**Comment by bagder** [comment]
I don't see what we can do about this issue. This crash is caused by outside changes and nobody else is reporting these.
