### ISSUE TITLE
I want to use opera.com https Proxy with CURL & PHP can that don

### ISSUE THREAD

**Issue by beshoo1** [curl/curl#1096]
opera start offering free VPN / will it is just https proxy .
Here is a demo of using https proxy in command line and  openssl s_client -connect

URL="http://www.opera.com" PROXY=68.71.44.125:443 HEADER="Proxy-Authorization: Basic QjY3MzEwOTFGNjAzMTIyQjc2NTM3OTg4MDYwQjk1ODY3RDY4QUI2MTo3QTkxQkJGMzAxOEI0RDFDRTk3QUY2QjU0NDNBNjY2MzU4Q0I3OThGREM5QjEzMkI1RTAxMTZEQzg5QTJCNTYz"; echo -e "GET $URL HTTP/1.0\n$HEADER\n\n" | openssl s_client -connect $PROXY -ign_eof

i want to do same thing using php and CURL 
dos this new CURL HTTPS PROXY lib help ? and how can i do that .

Regards
[curl -V output perhaps?]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

### operating system
Linux centos 6 64

**Comment by jay** [comment]
This is an issue tracker, for help with libcurl ask on [the mailing list](https://cool.haxx.se/mailman/listinfo/curl-library). Please first review PHP [curl_setopt](http://php.net/manual/en/function.curl-setopt.php), it sounds like you'll need CURLOPT_PROXYAUTH
