### ISSUE TITLE
test1097 failed:Address already in use (98)

### ISSUE THREAD

**Issue by eaglegai** [curl/curl#10976]
curl version: 7.79.1

runtests.pl(now servers.pm):
```
in sub runhttptlsserver {
    my $port = 24367;
    my ($httptlspid, $pid2);
    for (1 .. 10) {
        $port += int(rand(800));
        my $allflags = "--port $port $flags";

        my $cmd = "$httptlssrv $allflags > $logfile 2>&1";
        ($httptlspid, $pid2) = startnew($cmd, $pidfile, 10, 1);
```
the port range is (24367,25167)
```
in sub runhttpsserver {
    my $port = 24512; # start attempt
    for (1 .. 10) {
        $port += int(rand(600));
        my $options = "$flags --accept $port";

        my $cmd = "$perl $srcdir/secureserver.pl $options";
        ($httpspid, $pid2) = startnew($cmd, $pidfile, 15, 0);
```
the port range is (24512,25112)

in some case they whill use the same port,which causes test1097 failed by 'Address already in use'

**Comment by eaglegai** [comment]
here is the log:
test319:
startnew: /usr/bin/gnutls-serv --port 24687 --http --priority NORMAL:+SRP --srppasswd ../../tests/certs/srp-verifier-db --srppasswdconf ../../tests/certs/srp-verifier-conf > log/httptls_server.log 2>&1
startnew: .httptls_server.pid faked with pid=1671741
RUN: HTTPTLS server PID 1671741 port **24687**
* pid httptls => 1671741 1671741
......

test1097:
startnew: perl -I../../tests ../../tests/httpserver.pl --pidfile ".http_server.pid" --logfile "log/http_server.log" --portfile .http_server.port --ipv4 --port 0 --srcdir "../../tests/data/.."
RUN: ../src/curl --max-time 13 --output log/http_verify.out --silent --verbose --globoff "http://127.0.0.1:33787/verifiedserver" 2>log/http_verify.log
CMD (0): ../src/curl --max-time 13 --output log/http_verify.out --silent --verbose --globoff "http://127.0.0.1:33787/verifiedserver" 2>log/http_verify.log
RUN: HTTP server is on PID 1682919 port 33787
* pid http => 1682919 1682919
startnew: perl -I../../tests ../../tests/secureserver.pl --pidfile ".https_server.pid" --logfile "log/https_stunnel.log" --ipv4 --proto https --stunnel "/usr/bin/stunnel" --srcdir "../../tests" --connect 33787 **--accept 24687**
startnew: child process has died, server might start up
RUN: Process with pid 1682919 signalled to die
RUN: Process with pid 1682919 forced to die with SIGKILL
=== Start of file https_stunnel.log
 [ ] Clients allowed=500
 [.] stunnel 5.48 on aarch64-openEuler-linux-gnu platform
 [.] Compiled/running with OpenSSL 1.1.1m  14 Dec 2021
 [.] Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI
 [ ] errno: (*__errno_location ())
 [.] Reading configuration from file /root/rpmbuild/BUILD/curl-7.79.1/build-full/tests/https_stunnel.conf
 [.] UTF-8 byte order mark not detected
 [.] FIPS mode disabled
 [ ] Compression disabled
 [ ] No PRNG seeding was required
 [ ] Initializing service [curltest]
 [ ] Ciphers: HIGH:!aNULL:!SSLv2:!DH:!kDHEPSK
 [ ] TLS options: 0x02104004 (+0x00004000, -0x00000000)
 [ ] Loading certificate from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Certificate loaded from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Loading private key from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Private key loaded from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Private key check succeeded
 [ ] ECDH initialization
 [ ] ECDH initialized with curve prime256v1
 [.] Configuration successful
 [ ] Binding service [curltest]
 [ ] Listening file descriptor created (FD=7)
 [ ] Setting accept socket options (FD=7)
 [ ] Option SO_REUSEADDR set on accept socket
 [.] Binding service [curltest] to 0.0.0.0:24687: Address already in use (98)
 [ ] Listening file descriptor created (FD=7)
 [ ] Setting accept socket options (FD=7)
 [ ] Option SO_REUSEADDR set on accept socket
 **[.] Binding service [curltest] to :::24687: Address already in use (98)**
 [!] Binding service [curltest] failed
 [ ] Deallocating section defaults
 [ ] Unbinding service [curltest]
 [ ] Service [curltest] closed
 [ ] Deallocating section [curltest]
=== End of file https_stunnel.log

**Comment by bagder** [comment]
> the port range is (24512,25112)

It tries 10 times and it adds a random number to the attempted port number every loop. For one of them 0 .. 599 and the other 0 .. 699.  It make one range **24367 - 32367** and the other **24512 - 30512**. I don't think the port ranges is the problem.

The odds of them getting the same number should be low, but also the logic for the test servers *verifies* that it could create a server on the given port before it is satisfied. So if is satisfied but the server is not running on the port (because another server is already there) - it is a bug in the verification.

**Comment by eaglegai** [comment]
it seems try again and use 25070 as port, but this still says "Address already in use", and then curl failed, here are the full log about       
 test1097.
[full.log](https://github.com/curl/curl/files/11251507/full.log)

and when i change starting port from 24512 to 28000, tests passed.

**Comment by dfandrich** [comment]
There is a problem in the test server around this, but not specifically with server retrying. When this situation for test 1097 (port is in use) occurs on my system (near git HEAD) a new port is chosen and stunnel starts again on the new port and succeeds the second time. In reading the code, the only way I can see a situation happening where a new port is not selected and stunnel tried again is if stunnel fails to start correctly but doesn't actually exit, either. I could see this if the system is really slow or loaded, but I wouldn't expect it to happen consistently.

The actual problem that I alluded to above is that when the stunnel is restarted on a new port, the HTTP server is killed first. That leave no server to talk to once stunnel starts. I'll look into fixing that.

**Comment by dfandrich** [comment]
The other thing to keep in mind is that I'm looking at the current code whereas the report is on a version that's 1½ years old. It's possible something else changed in that time.

**Comment by dfandrich** [comment]
I've included a change in PR #10995 as part of a larger refactoring that should fix this.

**Comment by eaglegai** [comment]
I've tested commit 8dcce7b3 on 7.79.1
before patch:
1097 always failed
after patch:
tests passed

log is here:

```
test 1096...[Two FTP downloads, with failed RETR but re-used control connection]
../src/curl --output log/curl1096.out  --include --trace-ascii log/trace1096 --trace-time ftp://127.0.0.1:43153/dir/1096 ftp://127.0.0.1:43153/dir/1096 >log/stdout1096 2>log/stderr1096
CMD (19968): ../src/curl --output log/curl1096.out  --include --trace-ascii log/trace1096 --trace-time ftp://127.0.0.1:43153/dir/1096 ftp://127.0.0.1:43153/dir/1096 >log/stdout1096 2>log/stderr1096
--p----e--- OK (861 out of 1420, remaining: 05:25, took 0.087s, duration: 08:21)
RUN: Process with pid 350967 signalled to die
RUN: Process with pid 350983 signalled to die
RUN: Process with pid 350986 signalled to die
RUN: Process with pid 350986 gracefully died
RUN: Process with pid 350967 forced to die with SIGKILL
RUN: Process with pid 350983 forced to die with SIGKILL
startnew: perl -I../../tests ../../tests/httpserver.pl --pidfile ".http_server.pid" --logfile "log/http_server.log" --portfile .http_server.port --ipv4 --port 0 --srcdir "../../tests/data/.."
RUN: ../src/curl --max-time 13 --output log/http_verify.out --silent --verbose --globoff "http://127.0.0.1:40645/verifiedserver" 2>log/http_verify.log
CMD (0): ../src/curl --max-time 13 --output log/http_verify.out --silent --verbose --globoff "http://127.0.0.1:40645/verifiedserver" 2>log/http_verify.log
RUN: HTTP server is on PID 355784 port 40645
* pid http => 355784 355784
startnew: perl -I../../tests ../../tests/secureserver.pl --pidfile ".https_server.pid" --logfile "log/https_stunnel.log" --ipv4 --proto https --stunnel "/usr/bin/stunnel" --srcdir "../../tests" --connect 40645 --accept 24687
startnew: child process has died, server might start up
== Contents of files in the log/ dir after test 1097
=== Start of file http_server.log
 14:51:52.910213 exit_signal_handler: 15
 14:51:52.910509 signalled to die
 14:51:52.910690 ========> IPv4 sws (port 37359 pid: 350967) exits with signal (15)
 14:51:57.972920 Running HTTP IPv4 version on port 40645
 14:51:57.973272 Wrote pid 355784 to .http_server.pid
 14:51:57.973354 Wrote port 40645 to .http_server.port
 14:51:58.976655 ====> Client connect
 14:51:58.976738 accept_connection 3 returned 4
 14:51:58.976774 accept_connection 3 returned 0
 14:51:58.976813 Read 93 bytes
 14:51:58.976839 Process 93 bytes request
 14:51:58.976871 Got request: GET /verifiedserver HTTP/1.1
 14:51:58.976896 Are-we-friendly question received
 14:51:58.976956 Wrote request (93 bytes) input to log/server.input
 14:51:58.977021 Identifying ourselves as friends
 14:51:58.977213 Response sent (57 bytes) and written to log/server.response
 14:51:58.977244 special request received, no persistency
 14:51:58.977268 ====> Client disconnect 0
=== End of file http_server.log
=== Start of file http_verify.log
 *   Trying 127.0.0.1:40645...
 * Connected to 127.0.0.1 (127.0.0.1) port 40645 (#0)
 > GET /verifiedserver HTTP/1.1
 > Host: 127.0.0.1:40645
 > User-Agent: curl/7.79.1
 > Accept: */*
 >
 * Mark bundle as not supporting multiuse
 < HTTP/1.1 200 OK
 < Content-Length: 18
 <
 { [1 bytes data]
 * Connection #0 to host 127.0.0.1 left intact
=== End of file http_verify.log
=== Start of file http_verify.out
 WE ROOLZ: 355784
=== End of file http_verify.out
=== Start of file https_stunnel.log
 [ ] Clients allowed=500
 [.] stunnel 5.48 on aarch64-openEuler-linux-gnu platform
 [.] Compiled/running with OpenSSL 1.1.1m  14 Dec 2021
 [.] Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI
 [ ] errno: (*__errno_location ())
 [.] Reading configuration from file /root/rpmbuild/BUILD/curl-7.79.1/build-full/tests/https_stunnel.conf
 [.] UTF-8 byte order mark not detected
 [.] FIPS mode disabled
 [ ] Compression disabled
 [ ] No PRNG seeding was required
 [ ] Initializing service [curltest]
 [ ] Ciphers: HIGH:!aNULL:!SSLv2:!DH:!kDHEPSK
 [ ] TLS options: 0x02104004 (+0x00004000, -0x00000000)
 [ ] Loading certificate from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Certificate loaded from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Loading private key from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Private key loaded from file: /root/rpmbuild/BUILD/curl-7.79.1/tests/stunnel.pem
 [ ] Private key check succeeded
 [ ] ECDH initialization
 [ ] ECDH initialized with curve prime256v1
 [.] Configuration successful
 [ ] Binding service [curltest]
 [ ] Listening file descriptor created (FD=7)
 [ ] Setting accept socket options (FD=7)
 [ ] Option SO_REUSEADDR set on accept socket
 [.] Binding service [curltest] to 0.0.0.0:24687: Address already in use (98)
 [ ] Listening file descriptor created (FD=7)
 [ ] Setting accept socket options (FD=7)
 [ ] Option SO_REUSEADDR set on accept socket
 [.] Binding service [curltest] to :::24687: Address already in use (98)
 [!] Binding service [curltest] failed
 [ ] Deallocating section defaults
 [ ] Unbinding service [curltest]
 [ ] Service [curltest] closed
 [ ] Deallocating section [curltest]
=== End of file https_stunnel.log
=== Start of file server.input
 GET /verifiedserver HTTP/1.1
 Host: 127.0.0.1:40645
 User-Agent: curl/7.79.1
 Accept: */*
=== End of file server.input
=== Start of file server.response
 HTTP/1.1 200 OK
 Content-Length: 18
 WE ROOLZ: 355784
=== End of file server.response
startnew: perl -I../../tests ../../tests/secureserver.pl --pidfile ".https_server.pid" --logfile "log/https_stunnel.log" --ipv4 --proto https --stunnel "/usr/bin/stunnel" --srcdir "../../tests" --connect 40645 --accept 25070
RUN: HTTPS server is PID 355868 port 25070
* pid https => 355868 355871
test 1097...[HTTP POST using CONNECT with --proxy-ntlm but no auth is required]
../src/curl --output log/curl1097.out  --include --trace-ascii log/trace1097 --trace-time http://test.a.galaxy.far.far.away.1097:40645/1097 --proxy http://127.0.0.1:40645 --proxy-user foo:bar --proxy-ntlm -d "dummy=value" -p >log/stdout1097 2>log/stderr1097
CMD (0): ../src/curl --output log/curl1097.out  --include --trace-ascii log/trace1097 --trace-time http://test.a.galaxy.far.far.away.1097:40645/1097 --proxy http://127.0.0.1:40645 --proxy-user foo:bar --proxy-ntlm -d "dummy=value" -p >log/stdout1097 2>log/stderr1097
--pd---e--- OK (862 out of 1420, remaining: 05:32, took 12.135s, duration: 08:33)
test 1098...[FTP RETR twice over proxy confirming persistent connection]
../src/curl --include --trace-ascii log/trace1098 --trace-time ftp://ftp-site/moo/1098 ftp://ftp-site/moo/1098 --proxy http://127.0.0.1:40645 >log/stdout1098 2>log/stderr1098
CMD (0): ../src/curl --include --trace-ascii log/trace1098 --trace-time ftp://ftp-site/moo/1098 ftp://ftp-site/moo/1098 --proxy http://127.0.0.1:40645 >log/stdout1098 2>log/stderr1098
s-p----e--- OK (863 out of 1420, remaining: 05:31, took 0.053s, duration: 08:33)

```

**Comment by dfandrich** [comment]
Excellent! Thanks for verifying.
