### ISSUE TITLE
add further -o examples to man page

### ISSUE THREAD

**Issue by jidanni** [curl/curl#1097]
Man page should mention
````
$ curl -o aa example.com -o bb example.net
$ curl example.com -o cc example.net -o dd
````
are also possible.

**Comment by bagder** [comment]
It was actually already mentioned, but I expanded it somewhat now so the updated [version looks like this](https://curl.haxx.se/docs/manpage.html#-o):

> You may use this option as many times as the number of URLs you have. For example, if you specify two URLs on the same command line, you can use it like this:
> 
>   curl -o aa example.com -o bb example.net
> 
> and the order of the -o options and the URLs doesn't matter, just that the first -o is for the fir URL and so on, so the above command line can also be written as
> 
>   curl example.com example.net -o aa -o bb 

Good enough you think?

**Comment by jidanni** [comment]
Actually all the example.* sites produce the same output. Bad example
for testing. Oh and s/fir/first/; Also mention that
$ curl http://{a,b,c}.com/ -o x -o y -o z
won't work though, I think.
Also too bad there is no --dry-run / --simulate that would say what
would happen without actually going on the net...

**Comment by bagder** [comment]
Documenting what *doesn't work* isn't very good model I think since readers aren't always reading carefully and it risks that copying a snippet from the docs could copy a piece of text showing the *not working* section. I'd rather emphasize how it works.

About `--dry-run` I agree that would be an awesome feature. Feel free to work on it!

**Comment by bagder** [comment]
I consider this particular issued solved. I plan on improving the system for doing the curl tool man page, and hopefully that will aid us write more docs for each individual option. Stay tuned for that,
