### ISSUE TITLE
MacOS: Broken download progress bar when on narrow terminal

### ISSUE THREAD

**Issue by kraktus** [curl/curl#10970]
Hello, thank you for maintaining curl.

I've been redirected from https://github.com/Homebrew/brew/issues/15179, not sure if this is a bug report or rather an improvement request.

### I did this

Currently when the lateral size of the terminal is too small, the progress bar visually breaks like this:

![](https://user-images.githubusercontent.com/56031107/231872260-e66e7a1e-c6fe-4a9a-8222-c1ded320854a.png)
[Some comments](https://github.com/Homebrew/brew/issues/15179#issuecomment-1501193276) could suggest it's only happening when the screen is in split mode.

### I expected the following

Normal download bar

### curl/libcurl version

curl 7.87.0 (x86_64-apple-darwin22.0) libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets

### operating system

MacOS 13.3.1

**Comment by bagder** [comment]
I don't even understand that the problem is. Can you describe how it behaves and what you do with the terminal?

I've tested `-#` just now with a terminal narrower than 40 columns and it still worked fine for me. How narrow terminal are you talking about?

**Comment by kraktus** [comment]
Here's a recording of the issue on a 67x59 terminal
![](https://user-images.githubusercontent.com/56031107/232242595-8c88570d-89b7-4fbc-a991-a174d70a2b53.mov)

**Comment by bagder** [comment]
Did you forget to attach the recording?

**Comment by kraktus** [comment]
No, it’s in my previous comment. If it doesn’t show here’s the link: https://user-images.githubusercontent.com/56031107/232242595-8c88570d-89b7-4fbc-a991-a174d70a2b53.mov

**Comment by bagder** [comment]
That looks like a broken terminal?

Here's my setting up a 36x10 terminal and I run this command: `curl -# localhost/512K --limit-rate 100 -o /dev/null`  (to make sure the progress bar is really slow it downloads 512K at 100 bytes/sec)

I can't spot any obvious glitch.

![36x10-terminal](https://user-images.githubusercontent.com/177011/232246802-6622977e-b945-4572-96b5-617165ab57dd.png)

**Comment by kraktus** [comment]
This is probably OS specific, I could reproduce on hardware that was just out of factory settings, so it’s not a broken install.

Note that docker, cargo, npm, yarn, pnpm, pip, progress bar work fine, to give a few example,

**Comment by bagder** [comment]
Knowing this curl code, I do not believe this is OS specific at all.

If you create a 36x10 terminal window like I did and invoke curl like I did in said window, are you saying that the progress meter does not display correctly?

**Comment by kraktus** [comment]
I can confirm that on a MacBook Air, any terminal narrower than the issue occurs when there are tricky fewer than 79 columns.

**Comment by bagder** [comment]
That's strange because now I fired up my mac, made a really narrow terminal and voila, curl shows the `-#` progress bar correctly there.

**Comment by kraktus** [comment]
Thanks for trying up, that's strange indeed. Any additional diagnostics I could send? Will also try on other hardware when I get a hand on it and report here.

**Comment by bagder** [comment]
Yes: for example you can show us how it looks when you run such a command line in a 36 column wide terminal.

**Comment by jzakrzewski** [comment]
One thing to try would also be a plain `curl` command - not via `brew...`, because that could be srewing things up.

**Comment by sevan** [comment]
A copy of `printenv` output from terminal would also be useful, if the issue persists when running the `curl` command.

**Comment by kraktus** [comment]
I am unable to reproduce the issue directly running the `curl` command, no matter how narrow the terminal is.

**Comment by kraktus** [comment]
Thank you for the help, and sorry for the waisted time will comeback to the brew maintainers.
