### ISSUE TITLE
Duplicate curl_strnequal symbol when linking curl.exe

### ISSUE THREAD

**Issue by brucestephens** [curl/curl#1098]
Also `curl_strequal`. I think `strcase.obj` just wants removing from `CURL_FROM_LIBCURL` in `winbuild/MakefileBuild.vc`. (But maybe that would break buiiding with a static library or something.)

Anyway, these symbols are (the linker says) already in `strcase.obj` in `libcurl.lib(libcurl.dll)` and that causes the build to fail.

**Comment by bagder** [comment]
That looks like a correct fix, thanks!
