### ISSUE TITLE
Test 1139 [Verify that all libcurl options have man pages] failing

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#10985]
### I did this

Look at the autobuilds at https://curl.se/dev/builds.html.

### I expected the following

Everything green.

Instead, test 1139 [Verify that all libcurl options have man pages] is failing in the NetBSD autobuilds with:
```
--proxy-http2 is not in curl.1 (but in tool_getparam.c tool_listhelp.c)
```
https://curl.se/dev/log.cgi?id=20230415023627-1076303#prob1

The strange thing is that it passed in all other CI and autobuild runners.

### curl/libcurl version
```
* curl 8.1.0-DEV (armv7eb-unknown-netbsdelf9.3-eabihf)
* libcurl/8.1.0-DEV OpenSSL/1.1.1k zlib/1.2.10 libidn2/2.3.3 nghttp2/1.49.0
* Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP TrackMemory UnixSockets
```
Seems to be caused by https://github.com/curl/curl/commit/e39754f6a242c99a80a274280b61e884e5abcc7e.

### operating system

NetBSD 9.3

**Comment by bagder** [comment]
The option *should* be in the curl.1 file since the `docs/cmdline-opts/proxy-http2.d` is there, has the wrong syntax and this is tested in a huge amount of other builds. The question is why the curl.1 generation doesn't work on this system?

**Comment by bagder** [comment]
I suspect this is something wrong on the target system,

**Comment by MarcelRaad** [comment]
@mkauf Do you maybe have any idea what's wrong?

**Comment by mkauf** [comment]
There is an outdated `curl.1` in `/home/autobuild/curl/docs`, probably from an in-tree build.

The autobuild is performed in a temporary directory (out-of-tree build), e.g. `/home/autobuild/curl/build-26870`. The file `/home/autobuild/curl/docs/curl.1` is copied to `/home/autobuild/curl/build-26870/docs/curl.1` and it is not updated afterwards.

Probably the problem is in `/home/autobuild/curl/docs/Makefile.in`:

```
# $(abs_builddir) is to disable VPATH when searching for this file, which
# would otherwise find the copy in $(srcdir) which breaks the $(HUGE)
# rule in src/Makefile.am in out-of-tree builds that references the file in the
# build directory.
#
# First, seed the used copy of curl.1 with the prebuilt copy (in an out-of-tree
# build), then run make recursively to rebuild it only if its dependencies
# have changed.
$(abs_builddir)/curl.1:
        if test "$(top_builddir)x" != "$(top_srcdir)x" -a -e "$(srcdir)/curl.1"; then \
                $(INSTALL_DATA) "$(srcdir)/curl.1" $@; fi
        cd cmdline-opts && $(MAKE)
```

The `$(INSTALL_DATA)` command does not preserve the file timestamps. `/home/autobuild/curl/build-26870/docs/curl.1` gets the current time as the last modification timestamp. `cd cmdline-opts && $(MAKE)` does nothing because the timestamp of the `curl.1` file is up to date.

It would probably work if  the timestamp is preserved (`cp -p` or `install -p`). Or maybe remove this build optimization altogether?

**Comment by bagder** [comment]
> There is an outdated curl.1 in /home/autobuild/curl/docs, probably from an in-tree build.

Isn't the fix here to remove this leftover then?

**Comment by dfandrich** [comment]
> It would probably work if the timestamp is preserved (cp -p or install -p). Or
> maybe remove this build optimization altogether?

install -p isn't portable, but it looks like cp -p is and is already used that
way elsewhere in the makefile. That might be the solution. Removing this
altogether would mean that everybody would need nroff install to generate the
man page even if it wasn't changed in the downloaded package.

**Comment by bagder** [comment]
> everybody would need nroff install to generate the man page

strictly speaking we don't need nroff to generate the man page.

But once the man is generated, the hugehelp source file needs to get re-generated and **that** needs nroff.

**Comment by mkauf** [comment]
> Isn't the fix here to remove this leftover then?

I can delete the file if you want, this will make the autobuild green again.

**Comment by mkauf** [comment]
I have deleted the file, the next autobuild should be green again.
