### ISSUE TITLE
"protocols" and "feature_names" arrays returned by curl_version_info() are not properly terminated

### ISSUE THREAD

**Issue by Qriist** [curl/curl#10989]
### I did this
I'm wrapping libcurl for AHK. I'm trying to parse the `protocols` and `feature_names` arrays that `curl_version_info_data` returned pointers to. (man page: https://curl.se/libcurl/c/curl_version_info.html)

The docs suggest that there should be a NULL entry signifying the end of the array, which I (perhaps incorrectly) interpret to mean there should be two consecutive binary zeroes denoting termination (one being the separator of the last valid item and one being the actual NULL entry).

On the newest version (8.0.1), parsing `protocols` in this manner gives me a list of all protocols plus all feature names plus what appears to be a couple junk entries.

Parsing `feature_names` gives me the expected features plus the same junk entries as before.

this is what gets returned each time:
![image](https://user-images.githubusercontent.com/26832022/232589254-0cf9f004-6f89-47a8-ae2f-ea32e31bae40.png)

### I expected the following
On a lark, I tried reverting to a copy of 7.74.0 that I randomly had available. This version, parsed the same way, gave me the expected `protocols` list with no extra data. Obviously, `feature_names` is absent from the older structure and so I wasn't able to test that for extraneous entries.

### curl/libcurl version
8.0.1 and 7.74.0

### operating system
windows 10

Is 8.0.1's return data bugged? If not, how do I properly parse this array?

**Comment by bagder** [comment]
I wrote up a tiny example showing how the arrays can be accessed and printed fine:  #10991

**Comment by Qriist** [comment]
Thank you for your swift response.

Alright, so we might be getting into the weeds of differences between languages. I'm pretty fluent in AHK but have only some minimal knowledge of C conventions. 

I've provided a cut-down version of my current code. Obviously, it's in AHK, but you should be able to what I'm doing. 
```
    _curl_version_info() {
        verPtr := DllCall(this.curlDLLpath "\curl_version_info", "Int", 0xA, "Ptr")
        
        structStr := ""
			.   "int    age;"
			.   "UPtr   version;"
			.   "UInt   version_num;"
			.   "UPtr   host;"
			.   "Int    features;"
			.   "UPtr   ssl_version;"
			.   "Int    ssl_version_num;"
			.   "UPtr   libz_version;"
			.   "Ptr    protocols;"
			.   "UPtr   ares;"
			.   "int    ares_num;"
			.   "UPtr   libidn;"
			.   "int    iconv_ver_num;"
			.   "UPtr   libssh_version;"
			.   "UInt   brotli_ver_num;"
			.   "UPtr   brotli_version;"
			.   "UInt   nghttp2_ver_num;"
			.   "UPtr   nghttp2_version;"
			.   "UPtr   quic_version;"
			.   "UPtr   cainfo;"
			.   "UPtr   capath;"
			.   "UInt   zstd_ver_num;"
			.   "UPtr   zstd_version;"
			.   "UPtr   hyper_version;"
			.   "UPtr   gsasl_version;"
			.   "Ptr    feature_names;"
		
        ;creates the structure based on the previous string
        verStruct := Struct(structStr,verPtr)	
        
	;both of these give me the raw memory addresses where each Ptr array starts
	;AFAIK, AHK provides no other C-like information beyond this integer, not even that it is a pointer
	prot := NumGet(verStruct["protocols"],"Ptr")	
        feat := NumGet(verStruct["feature_names"],"Ptr")

	;just used for visual feedback while testing
        msgbox "PROTOCOLS:" "`n" this._walkStringArray(prot) "`n`n" "FEATURES:`n" this._walkStringArray(feat)
    }
	
	
	;simple interim method to join the array as a normal string
	;the pointer is manually advanced based on the length of the currently read string
	_walkStringArray(ptr){
		offset := 0
		loop{
			ret := StrGet(ptr, "UTF-8")
			retLen := StrLen(ret)
			if (retLen > 0){
				retStr .= ret "`n"
				ptr += retLen+1
			}
			else
				break
		}
		return retStr
    }```

My problem mainly seems to reside in processing the Ptr as libcurl delivers it.

[AHK doesn't have a NULL type](https://www.autohotkey.com/docs/v2/Concepts.htm#nothing) so checking for a NULL pointer is impossible.

I'm not sure how to resolve this conflict. I am open to ideas.

**Comment by bagder** [comment]
I would presume asking people in the AHK community would be a better idea than asking here. libcurl provides a C API. Most languages that access libcurl has a "binding"/glue that takes care of mapping things into the language in whatever way the particular language prefers.

**Comment by Qriist** [comment]
Okay, got it figured out, in no small part due to your clear explanation. 

There's a feature in AHK that can walk down pointer arrays. It's not really well documented, and what documentation exists is not where I'd expect to find it. I'll shoot the AHK maintainers some notes.

Thanks for entertaining my nonsense. 🙏

**Comment by bagder** [comment]
I think this concludes that this is not a curl issue.
