### ISSUE TITLE
Run CI on other Windows build systems

### ISSUE THREAD

**Issue by jay** [curl/curl#1099]
I think we should fix the CI builds to run other Windows build systems. I've noticed we have windows builds break rarely despite CI tests showing ok, and it appears this is because the CI isn't run on them. At the moment appveyor is testing cmake Windows builds, not the winbuild or generate or lib/Makefile.vc6. I don't know if it's possible to integrate any of that with the current build matrix in [appveyor.yml](https://github.com/curl/curl/blob/master/appveyor.yml). Any ideas @snikulov ?

**Comment by mback2k** [comment]
I am running release and autobuilds (debug) on msys1 and msys2 using mingw and mingw-w64 through my [buildbot](https://curlbuild.uxnr.de/waterfall) which reports to the curl autobuilds page and Github Status API. Do you think it would be worth to have AppVeyor run the same builds, too?

**Comment by jay** [comment]
Hey Marc. I don't think so because you are already running it and your build is listed in the checks (click on any green check or red x) in the [commit list](https://github.com/curl/curl/commits/master). So it is my understanding technically you are part of CI. If you are running more builds that do not show up there, and can make them show up that would be helpful.

**Comment by snikulov** [comment]
@jay Why not. It's required more scripting in appveyor.yml but it's possible.

**Comment by bagder** [comment]
It looks like @mback2k could even maintain his buildbots as-is and then use the github API to submit build information and then I think fail/success is enough. See the [github docs](https://developer.github.com/v3/repos/statuses/ ) for this

**Comment by mback2k** [comment]
@bagder That is what I am already doing, but I have to upgrade buildbot from 0.8.12 to 0.9.x in order to produce one status per builder instead of only the latest.

**Comment by snikulov** [comment]
@mback2k Will you cover missed windows cases, as @jay mentioned?

**Comment by mback2k** [comment]
Not in the near future. I am focusing on builds using msys/mingw. I may provide some Visual Studio based builds at some point, but I don't have an ETA yet.

**Comment by mback2k** [comment]
BTW-- I updated my buildbot to post one status context per builder instead of overwriting the same one over and over.

**Comment by jay** [comment]
Another thing I think would be good for the project is if we enabled "artifacts" from the build process in appveyor, or in other words curl.exe, libcurl.dll, libeay32.dll, ssleay32.dll and the respective pdbs. Someone recently reported a problem that we fixed, and does not know how to build curl. Not the first time it's happened, so I think it would be easier in cases like that to give the commit artifact (or whatever the terminology is) so that they can just use the curl.exe built by appveyor to test that the fix works for them.

I'm not too familiar with yml but this is what I have so far (untested)
~~~yaml
after_build:
  >- 7z a curl-%appveyor_repo_branch%-%appveyor_repo_commit%.zip
COPYING
%APPVEYOR_BUILD_FOLDER%\build.msvc2015\lib\Release\libcurl.dll
%APPVEYOR_BUILD_FOLDER%\build.msvc2015\lib\Release\libcurl.pdb
%APPVEYOR_BUILD_FOLDER%\build.msvc2015\src\Release\curl.exe
%APPVEYOR_BUILD_FOLDER%\build.msvc2015\src\Release\curl.pdb
C:\OpenSSL-Win64\bin\libeay32.dll
C:\OpenSSL-Win64\bin\ssleay32.dll


artifacts:
  - path: curl-$(appveyor_repo_branch)-$(appveyor_repo_commit).zip
~~~
I'm not sure if `>-` is the proper line continuing syntax.



I created an appveyor account but I don't know how to run test yml files without affecting the project. In other words, I can run appveyor from my fork but it seems to affect the curl/curl builds.

**Comment by snikulov** [comment]
@jay I've better idea to use CMake [install](https://cmake.org/cmake/help/v3.0/command/install.html) command.  Just need to investigate where and how to publish artifacts.

**Comment by mback2k** [comment]
@snikulov What about builds that do not use CMake? ;-)

**Comment by gvanem** [comment]
@jay 
> `C:\OpenSSL-Win64\bin\libeay32.dll`
> `C:\OpenSSL-Win64\bin\ssleay32.dll`

PS. these are named:
```
libcrypto-1_1.dll
libssl-1_1.dll
```
since some weeks ago.

**Comment by bagder** [comment]
This seems to not go anywhere in particular.

**Comment by jay** [comment]
Sadly. It would be good to have a winbuild CI for example, I'm just not familiar with how to do that for CI.

**Comment by mback2k** [comment]
Since I had this issue still marked as pending for myself, I just wanted to leave a comment here that I think we are now covering much more builds variants with our Windows CIs nowadays. ✅
