### ISSUE TITLE
--aws-sigv4 does not behave well with AWS VPC Lattice services

### ISSUE THREAD

**Issue by ajoga** [curl/curl#11007]
### I did this

Downloaded curl curl-8.0.1, patched like:

```
~/environment/curl-8.0.1 $ diff lib/http_aws_sigv4.c*
350c350
<   if(false) {
---
>   if(empty_payload || post_payload) {
488c488
<                 strcasecompare(service, "vpc-lattice-svcs"));
---
>                 strcasecompare(service, "s3"));
```

So I could run:

```
$ ./src/curl --aws-sigv4 "aws:amz:eu-west-1:vpc-lattice-svcs" --user "${ACCESS_KEY_ID}:${SECRET_ACCESS_KEY}" -H "x-amz-security-token: $SESSION_TOKEN" http://helloworld-XXXXXXX.XXXXXXX.vpc-lattice-svcs.eu-west-1.on.aws/hello 
yes this is patrick
```

### I expected the following

Same thing without the patch :)

### curl/libcurl version

```
$ ./src/curl -V
curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe UnixSockets
```

### operating system

```
$ uname -a
Linux xxxxxxxxxx 4.14.311-233.529.amzn2.x86_64 #1 SMP Thu Mar 23 09:54:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### More details

Our of the box, a `curl --aws-sigv4 "aws:amz:eu-west-1:vpc-lattice-svcs" --user "${ACCESS_KEY_ID}:${SECRET_ACCESS_KEY}" -H "x-amz-security-token: $SESSION_TOKEN" http://helloworld-XXXXXXX.XXXXXXX.vpc-lattice-svcs.eu-west-1.on.aws/hello` gave me the following error:

```
IncompleteSignatureException: Missing the 'x-amz-content-sha256' in canonical headers
```

Upon reading https://github.com/curl/curl/pull/8935#issuecomment-1329440791, I modified just the `strcasecompare` so vpc-lattice-svcs would get the same logic for signature than s3. It was not enough, as `curl` gave me `InvalidSignatureException: Signed payloads are not supported` (which is correct [according to this service's documentation: "VPC Lattice does not support payload signing, therefore you must send x-amz-content-sha256 header with value set to "UNSIGNED-PAYLOAD"."](https://docs.aws.amazon.com/vpc-lattice/latest/ug/sigv4-authenticated-requests.html)), hence my dirty bypass with the `if(false)` to the payload signing block. 

Relates to #8810 #8935

**Comment by bagder** [comment]
@ajoga would you mind providing your proposed fix as a PR?

**Comment by bagder** [comment]
This authentication thing is awful with checks for specific strings like `aws`and `s3` to decide how to act.

Can't you just say it is `s3` instead of `vpc-lattice-svcs` to make it work?

**Comment by ajoga** [comment]
Hi @bagder 

Thank you for your swift feedback. My apologies for not getting to that PR -- last C I wrote was many years ago and the "patch" in this bug report is breaking the initial intended logic of curl just to get my use case to work. I didn't get a big enough chunk of time to try to submit to you something that could be a base of discussion to merge.

> Can't you just say it is `s3` instead of `vpc-lattice-svcs` to make it work?

I tried it for you, on curl-8.0.1:
```
$ ./src/curl --aws-sigv4 "aws:amz:eu-west-1:s3" --user "${ACCESS_KEY_ID}:${SECRET_ACCESS_KEY}" -H "x-amz-security-token: $SESSION_TOKEN" http://helloworld-XXXXXXX.XXXXXXX.vpc-lattice-svcs.eu-west-1.on.aws/hello                                                                                                                                                                                                                         
InvalidSignatureException: Signed payloads are not supported
```

This is why I had in my patch an `if(false)` to get in the code path for the `UNSIGNED-PAYLOAD` at https://github.com/curl/curl/blob/curl-8_0_1/lib/http_aws_sigv4.c#L350-L357

**Comment by cbodley** [comment]
> Note: VPC Lattice does not support payload signing, therefore you must send x-amz-content-sha256 header with value set to "UNSIGNED-PAYLOAD".

this is the first i've seen UNSIGNED-PAYLOAD mentioned outside of the s3 docs. i find it strange that vpc-lattice-svcs doesn't support any kind of signed payloads, but still requires this x-amz-content-sha256 header. as a workaround without code changes, you could add `-H "x-amz-content-sha256: UNSIGNED-PAYLOAD"` to the command line, and the rest of the signing logic should work correctly

i could imagine adding a curl option to control which payload signing strategy to use. currently for s3, we make a best effort to calculate a real signature, then fall back to UNSIGNED-PAYLOAD. outside of s3, we do the same but the fallback is a sha256 checksum of an empty buffer

for vpc-lattive-svcs, it looks like the correct strategy would be to always use UNSIGNED-PAYLOAD. but adding `-H "x-amz-content-sha256: UNSIGNED-PAYLOAD"` accomplishes the same thing

> This authentication thing is awful with checks for specific strings like awsand s3 to decide how to act.

this is currently the only way for curl to know whether or not the server will accept UNSIGNED-PAYLOAD. we might add a separate curl option to allow the caller to pass this information manually, but i still think there's value in doing the right thing automatically for services like s3

**Comment by mrpackethead** [comment]
I tryed this, 

```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` 
INSTANCE_PROFILE=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/iam/security-credentials/`
METADATA=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/iam/security-credentials/$INSTANCE_PROFILE`
ACCESS_KEY_ID=$(echo "$METADATA" | jq .AccessKeyId)
SECRET_ACCESS_KEY=$(echo "$METADATA" | jq .SecretAccessKey)
SESSION_TOKEN=$(echo "$METADATA" | jq .Token)


curl --request GET "https://vpclatticealp-mylatticeserv-nrrcexutsqpe-0b17e5b0e8a993adf.7d67968.vpc-lattice-svcs.us-west-2.on.aws/goodbye" --aws-sigv4 "aws:amz:us-west-2:vpc-lattice-svcs" --user ${ACCESS_KEY_ID}:${SECRET_ACCESS_KEY} -H "x-amz-content-sha256: UNSIGNED-PAYLOAD" -H "x-amz-security-token: ${SESSION_TOKEN}" 
```

IncompleteSignatureException: 'x-amz-security-token' is named as a SignedHeader, but it does not exist in the HTTP request.sh-5.2$
   
   
   
Any cluses?

**Comment by bagder** [comment]
Nobody works on this. Will add to known-bugs and close the issue.

**Comment by klyubin** [comment]
FWIW, curl 8.1.2 works for me with AWS Lattice just fine (at least for GET requests). I wonder if `SESSION_TOKEN` was empty in https://github.com/curl/curl/issues/11007#issuecomment-1596781811. I get the same error when I provide an empty `x-amz-security-token`, but it works just with a correct non-empty one.

Let's say you got these creds from AWS:
```json
{"Version":1,"AccessKeyId":"ASIA...","SecretAccessKey":"sDH1tW8...","SessionToken":"IQo...", "Expiration":"2023-09-19T00:18:13Z"}
```

You can then do this:
```bash
$ export AWS_ACCESS_KEY_ID=ASIA...
$ export AWS_SECRET_ACCESS_KEY=sDH1tW8...
$ export AWS_SESSION_TOKEN=IQo...

$ curl \
    --aws-sigv4 "aws:amz:us-east-1:vpc-lattice-svcs" \
    --user "${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}" \
    -H "x-amz-security-token: ${AWS_SESSION_TOKEN}" \
    -H 'x-amz-content-sha256: UNSIGNED-PAYLOAD' \
    https://myservice-whatever-0d4307
e6be722e0d1.7d67968.vpc-lattice-svcs.us-east-1.on.aws/
```

**Comment by nbaws** [comment]
Tested in https://github.com/curl/curl/pull/17129 and working now.

```
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
CREDENTIALS=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/ssmrole)
AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS| jq -r .AccessKeyId)
AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r .SecretAccessKey)
AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r .Token)
AWS_REGION=ap-southeast-2
                                            

./src/curl -v https://test-02a07eb841ef93555.7d67968.vpc-lattice-svcs.ap-southeast-2.on.aws/a=あ --insecure \
  --aws-sigv4 aws:amz:${AWS_REGION}:vpc-lattice-svcs \
  --user "${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}" \
  --header "x-amz-security-token: ${AWS_SESSION_TOKEN}" \
  --header 'Accept: application/json' \
  --header "x-amz-content-sha256: UNSIGNED-PAYLOAD" 


...

* Request completely sent off
< HTTP/1.1 404 Not Found
< date: Tue, 20 May 2025 23:04:29 GMT
< server: Apache/2.4.62 (Amazon Linux) OpenSSL/3.2.2
< content-length: 196
< content-type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
* Connection #0 to host test-02a07eb841ef93555.7d67968.vpc-lattice-svcs.ap-southeast-2.on.aws left intact

```
