### ISSUE TITLE
Download gets stuck intermittently in curl_easy_perform() while downloading content from HTTPS URLs

### ISSUE THREAD

**Issue by snahar20** [curl/curl#11004]
We have a C/C++ application which utilizes curl to download data from streaming servers (specially OTT servers). We use lib-curl in our back-end . Although we are facing the issue while using the default curl version 7.29 available on the OS (Centos 7.9), the same behavior is observed too with libCurl 7.84 version.

There are concurrently 1000-2000 curl objects running in parallel. We access both HTTP as well as HTTPS URLs.

Recently we have observed while using the HTTPS URLs, randomly some of the connection will not execute properly and would hang indefinitely.

We have also observed that there are large numbers of TCP sockets that are stuck in CLOSE_WAIT state.

Please find below the call stack of the thread hung indefinitely.

 How to overcome this situation to gracefully come out of this hang? Is there any specific curl setting we need to enable to handle this situation.

 Thread 3121 (Thread 0x7f61a67fc700 (LWP 1669)): (please note Orion or OTT* are our classes)
#0 0x00007f68adfca965 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1 0x00007f68a89f9270 in PR_WaitCondVar () from /lib64/libnspr4.so
#2 0x00007f68a902d8ea in NSSRWLock_LockWrite_Util () from /lib64/libnssutil3.so
#3 0x00007f68a97d3dc8 in ssl_FreeSocket () from /lib64/libssl3.so
#4 0x00007f68a97c4940 in ssl_DefClose () from /lib64/libssl3.so
#5 0x00007f68ae442b7b in nss_setup_connect () from /lib64/libcurl.so.4
#6 0x00007f68ae4442df in nss_connect_common () from /lib64/libcurl.so.4
#7 0x00007f68ae445857 in Curl_ssl_connect_nonblocking () from /lib64/libcurl.so.4
#8 0x00007f68ae409c48 in https_connecting () from /lib64/libcurl.so.4
#9 0x00007f68ae40b36b in Curl_http_connect () from /lib64/libcurl.so.4
#10 0x00007f68ae41ded2 in multi_runsingle () from /lib64/libcurl.so.4
#11 0x00007f68ae41eb1e in curl_multi_perform () from /lib64/libcurl.so.4
#12 0x00007f68ae3fccc3 in curl_easy_perform () from /lib64/libcurl.so.4
#13 0x00007f68aee25275 in webservice::CCurlClient::StartDownload
#14 0x0000000000d53d68 in orion::CppnetLibSegmentDownloader::initRequest
#15 0x0000000000fe1ef1 in orion::CppnetLibSegmentDownloader::downloadSegment
#16 0x0000000000fe8cb1 in orion::CppnetLibSegmentDownloader::DownloadMediaSegment
#17 0x0000000000fefb50 in OTTVariantManager::CheckSegmentAvailabilityAndDownloadSegment
#18 0x000000000100d476 in OTTVariantManager::TDownloaderThread
#19 0x000000000133d3d9 in thread_proxy ()
#20 0x00007f68adfc6dd5 in start_thread () from /lib64/libpthread.so.0
#21 0x00007f68a9cfdead in clone () from /lib64/libc.so.6

**Comment by snahar20** [comment]
Thanks for your reply Dan. Yes we have tried to follow libcurl thread safety by carefully following the precautions listed.

**Comment by bagder** [comment]
> the same behavior is observed too with libCurl 7.84 version

What NSS version do you use? (We do ask for curl -V output for a reason)

**Comment by bagder** [comment]
No response
