### ISSUE TITLE
Create GitHub Release for 7.51.0

### ISSUE THREAD

**Issue by akerl** [curl/curl#1100]
Howdy!

Would it be possible to create the 7.51.0 release: https://github.com/curl/curl/releases

**Comment by bagder** [comment]
See https://github.com/curl/curl/releases/tag/curl-7_51_0

Now with a larger explanatory text in the description to help people better understand what the github "releases" are.

**Comment by akerl** [comment]
Awesome, thanks. For some clarity: I'm a somewhat strange person who builds his own musl-based packages, but more importantly I have a tool to check if new upstream releases for any of the 100 or so things I build have been released, and it checks for GitHub releases since they have a fairly friendly API and are re-usable across lots of projects.
