### ISSUE TITLE
curl_easy_perform() cause process restart

### ISSUE THREAD

**Issue by www222fff** [curl/curl#11028]
In our application we found process restarted happened sporadic when calling calling curl_easy_perform().
Applicaiton is trying to do rubustness testing, trigger put msg for keepalive(per 55s interval) and make the connection server down sometimes, in such scenario most of the respose can be reveiced.
But after long time testing application restart happen, may be at that time tcp connection server is down . Suspect curl_easy_perform() happened crash or stunk at that time.

So my question:
is there some existing knowm issues for this API curl_easy_perform? 
how to debug what happened to curl_easy_perform when issue happening?
is there some enhancement can be suggested?

2023/04/24-15:37:03.489286-196261-196266-433191088669589507-004- [INFO] 101 (SDL) [HttpConnection:158]HttpConnection PUT URL: https://[100.79.101.151]:32240/api/discovery/eb691850-e844-4dc2-ad71-f90751e73e01/keepalive
//process restarted and not got the PUT response. Below is our source code:

158     TRC_INFO("HttpConnection PUT URL: " << url);
159
160     CURLcode res = curl_easy_perform(m_curl);
161     TRC_INFO("HttpConnection PUT Response : " << res);
 
### 
[rtp99@udm6-udmuecm-75c468b8b6-25hh6 [oam] danny_debug]$ curl --version
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 

[rtp99@udm6-udmuecm-75c468b8b6-25hh6 [oam] danny_debug]$ uname -a
Linux udm6-udmuecm-75c468b8b6-25hh6 4.18.0-372.13.1.2207010901.el7_9.emrs.ulnx.x86_64 #1 SMP Wed Jul 13 18:23:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[rtp99@udm6-udmuecm-75c468b8b6-25hh6 [oam] danny_debug]$ cat /etc/redhat-release 
Rocky Linux release 8.7 (Green Obsidian)

**Comment by dfandrich** [comment]
curl has no code to restart a process. You'll need to provide a lot more
information about what's happening for us to help, starting with a backtrace in
the case of a crash and libcurl debug logs. It's possible libcurl is crashing,
but in the majority of cases crashes are due to problems in the application
code or misuse of the API. Also, the version of libcurl you're using is getting
close to five years old. If there was a problem in that version (and we have
fixed 4091 bugs since then) upgrading to the latest version might just solve
it.

**Comment by www222fff** [comment]
Yes,  application monitor restart instead of curl.
when libcurl is crashing, we did not get the pstack.
could you share some example to misuse API which can trigger crash?
issue can not be reproduce issue stably.

**Comment by www222fff** [comment]
Just want to know for below scenario is that possible to trigger curl_easy_perform crash?
1) tcp connection establish
2) client send PUT using curl_easy_perform
3) Server is closing tcp connection when client sending PUT.

**Comment by bagder** [comment]
We don't know of any situation where it crashes unless you do something strange.

If you told libcurl to ignore signals, you might get a SIGPIPE for this. But A) that's not a crash and B) you would be asking for it if this is the case.

**Comment by www222fff** [comment]
@bagder thanks for your support.
a little confuse, currently we are setting curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L); which means SIGPIPE will NOT be ignored? If we want to ignore SIGPIPE should not set as 1L, right?

**Comment by bagder** [comment]
Believed to be sorted.
