### ISSUE TITLE
curl fails to perform SFTP upload on newer OpenSSH Servers

### ISSUE THREAD

**Issue by benbalach** [curl/curl#11038]
### I did this

The SFTP file server is running Ubuntu 22.04 LTS 64-bit, output from "uname -a" command is:
```
Linux balachbubuntu 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
Here is the version of OpenSSH Server which is used by Ubuntu 22.04:
```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
```

I populated the known_hosts file on the client machine with the output of the "ssh-keyscan fileserveraddress" command.

Then to perform SFTP upload using password-based authentication, I ran:
```
echo "-u fileserverusername:fileserverpassword" | /usr/bin/curl -T /path/to/filetoupload.txt sftp://fileserveraddress/home/balachb/ --config -
```
which failed with:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (2) Failure establishing ssh session: -5, Unable to exchange encryption keys
```

**This only happens if the "ssh-rsa" host key for that file server is the first key for that host in the known_hosts file. When I move the "ssh-rsa" host key for that file server to be the last one, the above command succeeds. The above mentioned command also succeeds if there is no known_hosts file on the client, even without the "-k" option having to be specified to curl.**

**Even with the previously mentioned workaround, upload using key-based authentication does not work.** For upload using key-based authentication I ran:
```
/usr/bin/curl -T /path/to/filetoupload.txt sftp://fileserverusername@fileserveraddress/home/balachb/ --key /root/.ssh/id_rsa
```

which fails with:
```
curl: (67) Authentication failure
```

Even though I had copied the contents of the client's public key to the file server's authorized_keys file.

**These exact same commands work when tested against older SFTP servers.** The older SFTP server I used was on openSUSE Leap 15.4. Output of "uname -a" command is:
```
Linux s2-vcav-v1248-249-080 5.14.21-150400.24.55-default #1 SMP PREEMPT_DYNAMIC Mon Mar 27 15:25:48 UTC 2023 (cc75cf8) x86_64 x86_64 x86_64 GNU/Linux
```
Here is the OpenSSH Server version information for openSUSE Leap 15.4:
```
OpenSSH_8.4p1, OpenSSL 1.1.1l  24 Aug 2021 SUSE release 150400.7.31.2
```

It is worth noting that the "ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub" when executed on the client machine reports: "3072 SHA256:GWKyz+zzFLJG3bsJ7UdPgsaDXjwG2kW66IyoxbLvjT8 root@photon-machine (RSA)". The key-pair I generated on the client for key-based authentication was a RSA key without a passphrase. The "ssh-keygen -l -f /root/.ssh/id_rsa.pub" command on the client machine reports: "3072 SHA256:fJq0oPX9RGGkSlpjZPPge4WkD7l0nnwbUTWhnqf6/Rw root@photon-machine (RSA)".

I thought maybe it might be specific to Ubuntu 22.04 so I tried against an SFTP server on recent version of openSUSE Tumbleweed 20230424.

Command for upload using password-based authentication fails with the same error as mentioned before.

Command for upload using key-based authentication fails with a different error:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                               Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Segmentation fault (core dumped)
```

openSUSE Tumbleweed 20230424 reports the following for "uname -a":
```
Linux s2-vcav-v1248-253-118.eng.vmware.com 6.2.12-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr 20 11:01:10 UTC 2023 (eb3255d) x86_64 x86_64 x86_64 GNU/Linux
```
openSUSE Tumbleweed 20230424 reports the following version of OpenSSH Server:
```
OpenSSH_8.9p1, OpenSSL 3.0.8 7 Feb 2023
```

### I expected the following

SFTP upload using password-based authentication to work with the presence of a known_hosts file, regardless of the order of the keys for a given host, when uploading a file to an SFTP server running a recent version of OpenSSH Server. 

curl to not allow SFTP upload when no known_hosts file is present and "-k" option is not specified.

SFTP upload using key-based authentication to work on SFTP servers running recent versions of OpenSSH Server.

### curl/libcurl version
```
curl 8.0.1 (x86_64-unknown-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.7 zlib/1.2.11 zstd/1.5.2 libssh2/1.9.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```
### operating system

The following contains OS information for the client machine.

output from "uname -a" command:
```
Linux photon-machine 6.1.10-6.ph5-esx #1-photon SMP Wed Mar 29 21:58:42 UTC 2023 x86_64 GNU/Linux
```

distribution:
VMware Photon OS 5.0 RC

**Comment by bagder** [comment]
This is probably because you have an old libssh2 version and a rather new openssh server. Not actually a curl issue. A fix would be to either upgrade libssh2 or to enable the older algos on the server side.

**Comment by bagder** [comment]
This is (unfortunately) not a curl issue at all. It can only be solved by upgrading libssh2 or changing the server config.

**Comment by vszakats** [comment]
May related that OpenSSH 8.8 disabled `ssh-rsa` by default: https://www.openssh.com/txt/release-8.8

**Comment by bagder** [comment]
That's the one I thought of that seems to most commonly cause problems to users of old libssh2 versions.

**Comment by benbalach** [comment]
Just tried with latest version of libssh2 which is 1.10.0

running:
```
curl --version
```

reports:

```
curl 8.0.1 (x86_64-unknown-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.13 zstd/1.5.5 libssh2/1.10.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

and it fails with the same error.

If you suspect this is related to libssh2 I will forward the problem to them.

In the release notes of OpenSSH mentioned above, it says that RSA signatures that use the SHA-1 algorithm have have been disabled and that for most users, this change should be invisible and there is no need to replace ssh-rsa keys.

running:
```
ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub
```
on the client machine (VMware Photon OS 5.0 RC) reports that the key uses SHA-256 algorithm:
```
3072 SHA256:EFsuZ3o0hf8IrZfG2yt9YNWGoydByU/F973YiO8iFXQ root@photon-machine (RSA)
```

running:
```
ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub
```
on the SFTP server (Ubuntu 22.04) reports that the key also uses the SHA-256 algorithm:
```
3072 SHA256:mFyCoTJBLDA7UdHS/i4/5i25owB6nGm2y4eKc/f++h8 root@balachbubuntu (RSA)
```

**Comment by bagder** [comment]
> Just tried with latest version of libssh2 which is 1.10.0

That's the latest release version yes. I'm not sure that is new enough for the rsa thing. Do you recall @vszakats? libssh2 has not had a release since over 18 months.

> this change should be invisible

Clearly that statement was a bit exaggerated.

**Comment by vszakats** [comment]
For 8.8 and newer OpenSSH servers, these need to be added to `sshd_config` to use RSA hostkeys and auth keys (they also mention this in the release notes):
```
HostKeyAlgorithms +ssh-rsa
PubkeyAcceptedKeyTypes +ssh-rsa,ssh-rsa-cert-v01@openssh.com
```
Existing keys will then continue to work.

libssh2 1.10.0 with OpenSSL 1.1.1 also supports ed25519, which is the long-term solution for this. Next libssh2 will also support it with LibreSSL 3.7.0+.

**Comment by benbalach** [comment]
Modifying the ```sshd_config``` file on the SFTP server resolves the issue. However I don't think that is is the proper solution.

Without any modifications having to be made to the SFTP server's ```sshd_config``` file and when the ```ssh-rsa``` key for the SFTP server appears first in order in the ```known_hosts``` file on the client machine, which is the case when ```curl``` fails to perform upload, the ```sftp``` command, when executed on the same client machine, succeeds.

My understanding is that ```ssh-rsa``` keys are not deprecated, the SHA-1 algorithm is.

**Comment by vszakats** [comment]
If `ssh-rsa` is disabled on the server, no client will be able to use it. This is not up to curl or libssh2.

**Comment by benbalach** [comment]
I ran ```ssh -vvv user@localhost``` on the server and here is the relevant part:
```
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
```

Here is the entire output:
```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/balachb/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/balachb/.ssh/known_hosts2'
debug2: resolving "localhost" port 22
debug3: resolve_host: lookup localhost:22
debug3: ssh_connect_direct: entering
debug1: Connecting to localhost [127.0.0.1] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
debug1: identity file /home/balachb/.ssh/id_rsa type -1
debug1: identity file /home/balachb/.ssh/id_rsa-cert type -1
debug1: identity file /home/balachb/.ssh/id_ecdsa type -1
debug1: identity file /home/balachb/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/balachb/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/balachb/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/balachb/.ssh/id_ed25519 type -1
debug1: identity file /home/balachb/.ssh/id_ed25519-cert type -1
debug1: identity file /home/balachb/.ssh/id_ed25519_sk type -1
debug1: identity file /home/balachb/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/balachb/.ssh/id_xmss type -1
debug1: identity file /home/balachb/.ssh/id_xmss-cert type -1
debug1: identity file /home/balachb/.ssh/id_dsa type -1
debug1: identity file /home/balachb/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3ubuntu0.1
debug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3ubuntu0.1 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to localhost:22 as 'balachb'
debug1: load_hostkeys: fopen /home/balachb/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /home/balachb/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: no algorithms matched; accept original
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:tuzNEe/niq0SrMbX1YEXGGiZXiZexJG1VxYalT7WlNA
debug1: load_hostkeys: fopen /home/balachb/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /home/balachb/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: hostkeys_find_by_key_hostfile: trying user hostfile "/home/balachb/.ssh/known_hosts"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/balachb/.ssh/known_hosts does not exist
debug3: hostkeys_find_by_key_hostfile: trying user hostfile "/home/balachb/.ssh/known_hosts2"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/balachb/.ssh/known_hosts2 does not exist
debug3: hostkeys_find_by_key_hostfile: trying system hostfile "/etc/ssh/ssh_known_hosts"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts does not exist
debug3: hostkeys_find_by_key_hostfile: trying system hostfile "/etc/ssh/ssh_known_hosts2"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
```

On newer OpenSSH Servers ```ssh-rsa``` in the context of the ```HostkeyAlgorithms``` option in ```sshd_config``` is disabled by default and needs to be explicitly enabled. Explicitly mentioning that since ```ssh-rsa``` has different meaning depending on the context in which it is used. Enabling it only enables support for the deprecated RSA/SHA1 keys, but my host keys both on the client and on the server are not RSA/SHA1, they are RSA/SHA256.

**Comment by vszakats** [comment]
[ `ssh-rsa` in `HostKeyAlgorithms` enables SHA-1 _signatures_ with RSA keys. RSA host key pairs themselves are not using SHA1 or SHA2. ]

If what you're asking is why libssh2 isn't clicking together with the server when both have `rsa-sha2-*` algos enabled, without the server also advertising `ssh-rsa`? I don't know (and can't remember testing this), maybe someone over libssh2 does.

**Comment by benbalach** [comment]
Logged https://github.com/libssh2/libssh2/issues/1018

**Comment by bagder** [comment]
Taken to libssh2
