### ISSUE TITLE
Not all compilers support -Werror=partial-availability

### ISSUE THREAD

**Issue by bemoody** [curl/curl#1104]
Recently, curl's configure script was changed to unconditionally
add '-Werror=partial-availability' to the CFLAGS if $host_os is
darwin*.

This breaks compilation using diorcety's crosstool-ng, which
doesn't know about that option.  And it probably breaks lots of
other older compilers.

Please check that the C compiler actually understands a given
option before adding it to the CFLAGS.  For example:

    save_CFLAGS=$CFLAGS
    AC_MSG_CHECKING([whether $CC accepts -Werror=partial-availability])
    CFLAGS="$CFLAGS -Werror=partial-availability"
    AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
      [AC_MSG_RESULT([yes])],
      [AC_MSG_RESULT([no])
       CFLAGS=$save_CFLAGS])

**Comment by bagder** [comment]
So what about `-mmacosx-version-min`, is that also going to cause problems?

**Comment by bagder** [comment]
Just checking if `-Werror=partial-availability` works:

~~~~diff
diff --git a/acinclude.m4 b/acinclude.m4
index f959e3d..2abae8d 100644
--- a/acinclude.m4
+++ b/acinclude.m4
@@ -3230,9 +3230,16 @@ AC_DEFUN([CURL_MAC_CFLAGS], [
     if test -z "$min"; then
       AC_MSG_RESULT([set by user])
     else
       AC_MSG_RESULT([$min set])
     fi
+
+    old_CFLAGS=$CFLAGS
     CFLAGS="$CFLAGS -Werror=partial-availability"
+    AC_MSG_CHECKING([whether $CC accepts -Werror=partial-availability])
+    AC_COMPILE_IFELSE([AC_LANG_PROGRAM()],
+      [AC_MSG_RESULT([yes])],
+      [AC_MSG_RESULT([no])
+      CFLAGS=$old_CFLAGS])
   fi
 
 ])

**Comment by bemoody** [comment]
-mmacosx-version-min works for me; it seems to me that's been around for quite a while so it's probably safe.  But I'm not sure.

**Comment by bagder** [comment]
Thanks! Ok let's leave -mmacosx-version-min for now and see if people report anything. Pushed the fix for -Werror=partial-availability.
