### ISSUE TITLE
DNS resolving lasts too long while blocking

### ISSUE THREAD

**Issue by tawmoto** [curl/curl#11062]
Hi,

I am using `curl` as a static lib in my project, I build it like this:
``` 
cmake  -DCURL_TARGET_WINDOWS_VERSION=0x0601 -DBUILD_CURL_EXE=OFF -DBUILD_SHARED_LIBS=OFF -DENABLE_ARES=OFF -DCURL_DISABLE_LDAP=ON -DCURL_DISABLE_TELNET=ON -DCURL_DISABLE_DICT=ON -DCURL_DISABLE_FILE=ON -DCURL_DISABLE_TFTP=ON -DCURL_DISABLE_LDAPS=ON -DCURL_DISABLE_RTSP=ON -DCURL_DISABLE_POP3=ON -DCURL_DISABLE_IMAP=ON -DCURL_DISABLE_SMTP=ON -DCURL_DISABLE_GOPHER=ON -DENABLE_IPV6=ON -DCURL_USE_LIBSSH2=OFF -DCURL_ZLIB=OFF -DCURL_USE_OPENSSL=ON -DCURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG=ON -DCURL_USE_SCHANNEL=OFF -DCURL_STATIC_CRT=ON -DOPENSSL_ROOT_DIR="..." -G"NMake Makefiles" -DCMAKE_STATIC_LINKER_FLAGS=/SUBSYSTEM:CONSOLE,6.01 -DCMAKE_BUILD_TYPE=RELEASE
```

AFAIK, on Windows thread resolver is enabled by default

I have a small app that connects to a server and exchanges some jsons, using `curl_easy_perform`. If it's needed, I will create a small program for this problem. 
I set `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT`  100 seconds.
I modified the Windows settings to have a bad DNS.

![image](https://user-images.githubusercontent.com/35702340/235663325-540bd976-e3ae-453a-8c67-320476a36da6.png)

What is happening: I get `Couldn't resolve host name` error message from `curl` after 12 seconds of trying to connect. Everytime is 12 seconds, dunno why.
What I expect: To get the error faster, because it's blocking everything else.

`curl` version 8.0.1
`openssl` version 1.1.1.t
Windows 64 bit

Thanks

**Comment by bagder** [comment]
The name resolve obviously call takes this long to give up. If you think 12 seconds is too long, set a shorter `CURLOPT_CONNECTTIMEOUT`. This is not a curl bug.

**Comment by bagder** [comment]
Yes, that is probably related. You might want to try CURLOPT_QUICK_EXIT.

**Comment by bagder** [comment]
> If it's related to the other bug i understand, it doesn't seem to be a clear solution for it.

You can select between these three options:

1. wait the time it takes (since the name resolve call blocks in the thread and we need to wait for the thread to avoid leaking memory)
2. use CURLOPT_QUICK_EXIT and risk leaking memory
3. build libcurl to use c-ares for name resolving (comes with some other caveats)

**Comment by tawmoto** [comment]
Thank you Daniel, i have a last question pls: but shouldn't by default uses the thread resolver on another thread on windows, so it won't be blocking?

Or did I misunderstood this blog post:
https://daniel.haxx.se/blog/2011/04/25/libcurls-name-resolving/

**Comment by bagder** [comment]
Of course, a work-around if you have your client living longer, is to just keep the curl handle alive longer (and possibly reuse it later).

I don't think we can do a lot more.
