### ISSUE TITLE
Undefined symbol nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation

### ISSUE THREAD

**Issue by GCorbel** [curl/curl#11065]
### I did this

I updated Ubuntu from 22.10 to 23.04 this morning and have this issue when NetworkManager starts : 

> NetworkManager: symbol lookup error: /lib/x86_64-linux-gnu/libcurl-gnutls.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation

I tried to remove/reinstall libcurl and network-manager and all dependencies.

### I expected the following

I expect to have no error when NetworkManager start

### curl/libcurl version

libcurl4 : 7.88.1-8ubuntu1
libcurl3-gnu-tls : 7.88.1-8ubuntu1
libnghttp2-dev : 1.52.0-1
libnghttp2-14 : 1.52.0-1

### operating system

Linux ubuntu 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is not a curl bug. This is libcurl having been built with a nghttp2 version >= 1.50.0 (which has that function) and then at run-time it uses an older nghttp2 library that *doesn't* have the function.

**Comment by GCorbel** [comment]
Thanks for your fast answer. I suppose I have to reach the package owner.

**Comment by GCorbel** [comment]
For information and googlers, I created this ticket : https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2018342

**Comment by hansingt** [comment]
I've the same issue and checking the linkage, libcurl links against `libnghttp.so.14`, so only the so major version is constrainted. 

But the functionality was added to libnghttp2 in a backward compatible way in `14.24`. Thus, I'd think, that libcurl is required to link at least against version `14.24`, to make sure, that the function exists. 

But I'm not an expert in this and I'm not sure, whether it's possible to constain the linker on a major and a minor version of a library.
