### ISSUE TITLE
SMTP with --upload-file assumes headers already exist / does not inject a preceding newline

### ISSUE THREAD

**Issue by ProactiveServices** [curl/curl#1107]
### I did this
test.txt contains a single line of text e.g. "Test email"

curl smtp://mail.example.com --mail-from user@example.com --mail-rcpt user@example.com --upload-file test.txt

### I expected the following
The email to arrive and be readable in the client.

### What actually happened
The email was formed such that there was no newline before the contents of test.txt. This meant that the contents were invisible to the client as they were treated as a header.

### curl/libcurl version
curl 7.50.3 (x86_64-pc-win32) libcurl/7.50.3 OpenSSL/1.1.0b zlib/1.2.8 WinIDN libssh2/1.8.0 nghttp2/1.16.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2

### operating system
Windows 7 x64

Assumedly, some users will add headers into the file, some may not. Perhaps the --header option could be co-opted into use for SMTP headers and/or a file name for reading headers.

**Comment by dfandrich** [comment]
curl expects that the file to upload contains an RFC 5322 formatted message.
A file containing a single line of text "Test email" is not conformant to RFC
5322. Is there documentation that implied it should otherwise work?

**Comment by ProactiveServices** [comment]
The documentation doesn't state what cURL expects at all, hence reporting the issue.

**Comment by bagder** [comment]
Should we perhaps add a special mention in the `-T` section of the man page for when "uploading" to an SMTP server that describes what curl expects the file to contain/look like?

**Comment by bagder** [comment]
Like this perhaps:
~~~diff
diff --git a/docs/curl.1 b/docs/curl.1
index f5375ed..9e96d0c 100644
--- a/docs/curl.1
+++ b/docs/curl.1
@@ -1772,10 +1772,15 @@ the same URL globbing style supported in the URL, like this:
 curl -T "{file1,file2}" http://www.example.com
 
 or even
 
 curl -T "img[1-1000].png" ftp://ftp.example.com/upload/
+
+When uploading to an SMTP server: the uploaded data is assumed to be RFC 5322
+formatted. It has to feature the necessary set of headers and mail body
+formatted correctly by the user as curl will not transcode nor encode it
+further in any way.
 .IP "--tcp-nodelay"
 Turn on the TCP_NODELAY option. See the \fIcurl_easy_setopt(3)\fP man page for
 details about this option. (Added in 7.11.2)
 .IP "--tcp-fastopen"
 Enable use of TCP Fast Open (RFC7413). (Added in 7.49.0)

**Comment by ProactiveServices** [comment]
Looks good! In my case, I had checked the docs before trying to talk SMTP and this would have prompted me to make sure the attached file was correctly formatted.

**Comment by bagder** [comment]
I should also get working on the still [empty SMTP section in the curl book](https://ec.haxx.se/usingcurl-smtp.html)...

**Comment by bagder** [comment]
Ah, I actually used the momentum and wrote up a first version of the SMTP  section in the book as linked to above. A start at least!
