### ISSUE TITLE
runtests with custom curl and valgrind fails

### ISSUE THREAD

**Issue by bagder** [curl/curl#11074]
### I did this
~~~
$ cd tests
$ ./runtests.pl -c /usr/bin/curl 1
sh: 1: nghttpx -v 2>/dev/null: not found
readline() on closed filehandle $curlh at ./runtests.pl line 2190.
~~~

It works if I instead add `-n` to the command line like:
~~~
$ ./runtests.pl -n -c /usr/bin/curl 1
~~~

### I expected the following

It should work. I can run "valgrind /usr/bin/curl" just fine.

### curl/libcurl version

current git master

### operating system

This is a reasonably updated Debian Linux.

**Comment by bagder** [comment]
@dfandrich any obvious ideas?

**Comment by dfandrich** [comment]
On first glance, it looks like it was broken 8 years ago in 606b29fe0d. I'll
see about fixing it.

**Comment by bagder** [comment]
Thanks!
