### ISSUE TITLE
cURL doesn't find BoringSSL

### ISSUE THREAD

**Issue by andrewille** [curl/curl#11082]
### I did this
I followed your guide to compile curl with BoringSSL (https://everything.curl.dev/build/tls/boringssl).
I want to use the latest BoringSSL on the chromium-stable branch, but I also tried the main branch.
After the "configure" step it says that BoringSSL is enabled.
But when compiling curl, it doesn't even care about BoringSSL anymore. I can even rename the BoringSSL directory and it makes no difference. It falls back to OpenSSL in the end, I think.

### I expected the following
It should compile with BoringSSL and show that BoringSSL is in use when I run curl -V

### curl/libcurl version
Tested for 8.0.1 and 7.88.1

[curl -V output]
curl 7.88.1-DEV (x86_64-pc-linux-gnu) libcurl/7.88.1-DEV OpenSSL/3.0.2 zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe UnixSockets

### operating system
Linux Mint 21.1 Cinnamon
Linux andre-laptop 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
I tried again just now, with boringssl from their git master and curl from git master and it built just fine. We also build and tests this in our CI builds so we know this has worked fine for quite some time now.

These are my *exact* steps done just now:

## boringssl
~~~
$ cd $HOME/src/boringssl
[update from git]
$ cat mybuild
#!/bin/sh
CXX=g++ CC=gcc cmake -H. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=release -DBUILD_SHARED_LIBS=1 && cmake --build build
cp ./build/crypto/libcrypto.so ./lib/
cp ./build/ssl/libssl.so ./lib/

cmake --build build --target clean
rm -f build/CMakeCache.txt

CXX="g++" CC="gcc" cmake -H. -Bbuild -GNinja -DCMAKE_POSITION_INDEPENDENT_CODE=on && cmake --build build
cp ./build/crypto/libcrypto.a ./lib/
cp ./build/ssl/libssl.a ./lib/
$ . mybuild
... it builds openssl - twice, once shared and once  static
~~~

## curl to use boringssl
~~~
$ cd $HOME/src/curl
$ LDFLAGS="-Wl,-rpath,$HOME/src/boringssl/lib" LIBS=-lpthread ./configure  --with-ssl=$HOME/src/boringssl
$ make -sj
$ ./src/curl -V
... shows curl using boringssl
~~~
