### ISSUE TITLE
curl_multi_perform() gets stuck if DNS query response gets delayed.

### ISSUE THREAD

**Issue by aannurag** [curl/curl#11089]
On the Kubernetes environment, I am using curl to send HTTP requests to the server. Four DNS queries are sent every 60 seconds by our application microservice. For most of the DNS query requests, the response arrives within a few milliseconds. Intermittently, the DNS response gets delayed by 1 second. When this delay occurs, the function curl_multi_perform() gets stuck and becomes functional only when the response is received. This stucking-up behavior of curl_multi_perform() affects our other time-critical processes.   

### I expect

 that even if the DNS query response gets delayed by 1 second, the curl_multi_perform() should not get stuck and should work as expected. Since it is a non-blocking function.

### version

7.85.0

Linux xyz-xyz 5.4.17-2136.308.9.el8uek.x86_64 #2 SMP Mon Jun 13 20:36:40 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
It depends on what name resolver backend your curl was built to use. With threaded or c-ares, the name resolving does not block (the other transfers) within a multi handle.

**Comment by bagder** [comment]
No response
