### ISSUE TITLE
curl 7.51.0 build error on windows

### ISSUE THREAD

**Issue by toast12** [curl/curl#1108]
Hi,

When trying to build the latest version curl-7.51.0 on windows, I get this error:

nmake      INFO         libcurl.lib(libcurl.dll) : error LNK2005: _curl_strnequal already defined in strcase.obj
nmake      INFO         libcurl.lib(libcurl.dll) : error LNK2005: _curl_strequal already defined in strcase.obj

Don't know how to go about this. Please suggest

**Comment by jay** [comment]
This is a known issue (#1098) and was fixed in d7e5f18. You can either check that out of the repo or [apply it as a patch](https://github.com/curl/curl/commit/d7e5f182796c818e6fd412fdd4d2270d838612b5.diff).

**Comment by toast12** [comment]
Ok thanks. Looks like the fix was not applied in the tagged source, which is what we are using.

**Comment by bagder** [comment]
That fix landed after the release and the associated tag.
