### ISSUE TITLE
curl_easy_perform() stucks and cannot connect/reconnect and/or receive the data

### ISSUE THREAD

**Issue by jwolak** [curl/curl#11105]
Hello,

I’ve got a problem with version 8.0.1 of curl. **The same code works with 7.84.0, 7.85.0 and 7.86.0, but it stops from 7.87.0 (cfilters introduced) till the latest one.**
I had noticed that problem is caused by call of curl_easy_perform() function, which stucks for around 25s and then the rest go wrong (cannot reconnect and buffer is empty and reply delayed).
Maybe it is similar to https://github.com/curl/curl/issues/11004

Curl: 8.0.1 ( and all > 7.86.0)
Libwebsockets: 3.2.3 (server)
OS: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

For much/other logs and info - please let me know
Thanks in advance for any help and suggestions.

### I did this:
```
std::string url_ = "http://127.0.0.1:18443/";

static size_t header_callback(char *buffer, size_t size, size_t nitems,
		void *userdata) {
	return nitems * size;
}

CurlResponse response_;

curl_slist *slist_;

bool OpenConnection() {
	curl_easy_setopt(curl_, CURLOPT_URL, url_.c_str());
	if (url_.find("https") != -1) {
		curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYHOST, 0L);
	}
	curl_easy_setopt(curl_, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(curl_, CURLOPT_HEADERDATA, &response_);
	curl_easy_setopt(curl_, CURLOPT_HEADERFUNCTION, &header_callback);
	curl_easy_setopt(curl_, CURLOPT_VERBOSE, 1L);
	auto res = curl_easy_setopt(curl_, CURLOPT_HTTPHEADER, slist_);

	if (res != CURLE_OK)) {
		return false;
	}

	res = curl_easy_perform(curl_);
	if (res != CURLE_OK)) {
		return false;
	}

	res = curl_easy_getinfo(curl_, CURLINFO_RESPONSE_CODE, &response_.status);
	if (res != CURLE_OK)) {
		return false;
	}

	if (response_.status != 101) {
		Log::Error(
				"Server did not return 101, but instead:"
						+ std::to_string(response_.status));
		return false;
	}

	return true;
}
```
```
void ConnectToWeb() {

	auto connection_status = OpenConnection();
	Log::Info("Connection status: " + std::to_string(connection_status));
}
```

```
bool VerifyConnection() {
	bool is_socket_ready = false;
	int tries = 0;

	while (!is_socket_ready && (tries < max_retries)) {
		ConnectionStateResponse connectionStateResponse { };

		if (WaitForMessageFromWeb()) {
			Log::Info(std::string("Received following connection state response received:\n")
							+ connectionStateResponse.DebugString());

                        Log::Info("Websocket response ok.");
			is_socket_ready = true
		} else {
			Log::Warning("Websocket response wasn't received on time.");
		}

		++tries;

		if (!is_socket_ready) {
			auto connection_status = OpenConnection();
			Log::Info(std::string("Reopened connection to webserver. Current connection status: ")
							+ std::to_string(connection_status));
		}
	}

	return is_socket_ready;
}
```
```
bool WaitForMessageFromWeb() {
	bool retVal = false;

	int usedTime = 0;
	void *memoryBuffer = malloc(MAX_LENGTH);

	while (usedTime < timeoutms) {
		size_t readBytes(0);

		res = curl_easy_recv(curl_, memoryBuffer, MAX_LENGTH, &readBytes);

		if (res == CURLE_OK) {
			if (readBytes > 0) {
				retVal = true;

			} else {
				Log::Error("WebSocket connection was closed unexpectedly!");
				retVal = false;
				break;
			}
		} else if (res == CURLE_AGAIN) {
			std::this_thread::sleep_for(std::chrono::milliseconds(100));
			usedTime += 100;
		} else {
			retVal = false;
			break;
		}
	}

	return retVal;
}
```

### I expected the following:

```
* STATE: INIT => CONNECT handle 0x55829f326468; line 1879 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* family0 == v4, family1 == v6
*   Trying 127.0.0.1:18443...
* STATE: CONNECT => CONNECTING handle 0x55829f326468; line 1940 (connection #0)
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0x55829f326468; line 2072 (connection #0)
* STATE: PROTOCONNECT => DO handle 0x55829f326468; line 2095 (connection #0)
> GET / HTTP/1.1
Host: 127.0.0.1:18443
Accept: */*
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==
Sec-WebSocket-Protocol: abc
Sec-WebSocket-Version: 13
cookie: sa_client_id=9c8fcdef80d4724647a72ffa87772771bcc3f4cb; HttpOnly; Path=/

* STATE: DO => DID handle 0x55829f326468; line 2191 (connection #0)
* STATE: DID => PERFORMING handle 0x55829f326468; line 2310 (connection #0)

[INFO]  WebServer HTTP Unhandled event: 86 session_data: 0
[INFO]  WebServer HTTP [1] Unhandled WS event: 49 session_data 1
[INFO]  WebServer HTTP WebSocket upgrade request from 127.0.0.1
[INFO]  WebServer HTTP WebSocket upgrade request accepted!

* Mark bundle as not supporting multiuse
* HTTP 1.1 or later with persistent connection
< HTTP/1.1 101 Switching Protocols
< Upgrade: WebSocket
< Connection: Upgrade
< Sec-WebSocket-Accept: HSmrc0sMlYUkAGmm5OPpG2HaGWk=
< Sec-WebSocket-Protocol: abc
< 
* STATE: PERFORMING => DONE handle 0x55829f326468; line 2509 (connection #0)
* multi_done: status: 0 prem: 0 done: 0
* Connection #0 to host 127.0.0.1 left intact
* Expire cleared (transfer 0x55829f326468)

[INFO]  Connection status: 1
[INFO]  WebServer HTTP WebSocket connection established.
[INFO]  Received following connection state response received:
status: OK
type: CONNECTION_STATE
connection_state {
  state: CONNECTED
}

[INFO]  Websocket response ok.
[INFO]  Attempt 1. Inital response received: 1
```

### ...but I've got this:

```
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => CONNECT handle 0x55cb41ad0468; line 1940 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => CONNECTING handle 0x55cb41ad0468; line 1996 (connection #0)
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0x55cb41ad0468; line 2104 (connection #0)
* STATE: PROTOCONNECT => DO handle 0x55cb41ad0468; line 2134 (connection #0)
> GET / HTTP/1.1
Host: 127.0.0.1:18443
Accept: */*
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==
Sec-WebSocket-Protocol: abc
Sec-WebSocket-Version: 13
cookie: sa_client_id=d2cdd67c520c16230e3c77482986daf40d8b621d; HttpOnly; Path=/

* STATE: DO => DID handle 0x55cb41ad0468; line 2230 (connection #0)
* STATE: DID => PERFORMING handle 0x55cb41ad0468; line 2349 (connection #0)

[INFO]  WebServer HTTP [0] Unhandled event: 86 session_data: 0
[INFO]  WebServer HTTP Unhandled WS event: 49 session_data 1
[INFO]  WebServer HTTP WebSocket upgrade request from 127.0.0.1
[INFO]  WebServer HTTP WebSocket upgrade request accepted!

* HTTP 1.1 or later with persistent connection
< HTTP/1.1 101 Switching Protocols
< Upgrade: WebSocket
< Connection: Upgrade
< Sec-WebSocket-Accept: HSmrc0sMlYUkAGmm5OPpG2HaGWk=
< Sec-WebSocket-Protocol: abc
< 

WebServer HTTP WebSocket connection established.


**Time gap ~25s**


* nread <= 0, server closed connection, bailing
* STATE: PERFORMING => DONE handle 0x55cb41ad0468; line 2548 (connection #0)
* multi_done: status: 0 prem: 0 done: 0
* Connection #0 to host 127.0.0.1 left intact

[INFO]   Connection status: 1
[INFO]  WebSocket connection was closed unexpectedly!
[INFO]  Websocket response wasn't received on time.

* STATE: INIT => CONNECT handle 0x55cb41ad0468; line 1940 (connection #0)
* Added connection 1. The cache now contains 2 members
* Hostname 127.0.0.1 was found in DNS cache
* STATE: CONNECT => CONNECTING handle 0x55cb41ad0468; line 1996 (connection #1)
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#1)
* STATE: CONNECTING => PROTOCONNECT handle 0x55cb41ad0468; line 2104 (connection #1)
* STATE: PROTOCONNECT => DO handle 0x55cb41ad0468; line 2134 (connection #1)
* STATE: DO => DONE handle 0x55cb41ad0468; line 2187 (connection #1)
* multi_done: status: 0 prem: 0 done: 0
* Connection #1 to host 127.0.0.1 left intact
* Expire cleared (transfer 0x55cb41ad0468)

[ERROR] Server did not return 101, but instead:0
[INFO]  Reopened connection to webserver. Current connection status: 0
[WARN]  Websocket response wasn't received on time.

* STATE: INIT => CONNECT handle 0x55cb41ad0468; line 1940 (connection #1)
* Added connection 2. The cache now contains 3 members
* Hostname 127.0.0.1 was found in DNS cache
* STATE: CONNECT => CONNECTING handle 0x55cb41ad0468; line 1996 (connection #2)
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#2)
* STATE: CONNECTING => PROTOCONNECT handle 0x55cb41ad0468; line 2104 (connection #2)
* STATE: PROTOCONNECT => DO handle 0x55cb41ad0468; line 2134 (connection #2)
* STATE: DO => DONE handle 0x55cb41ad0468; line 2187 (connection #2)
* multi_done: status: 0 prem: 0 done: 0
* Connection #2 to host 127.0.0.1 left intact
* Expire cleared (transfer 0x55cb41ad0468)

[ERROR] Server did not return 101, but instead:0
[INFO]  Reopened connection to webserver. Current connection status: 0
[WARN]  Websocket response wasn't received on time.

* STATE: INIT => CONNECT handle 0x55cb41ad0468; line 1940 (connection #2)
* Added connection 3. The cache now contains 4 members
* Hostname 127.0.0.1 was found in DNS cache
* STATE: CONNECT => CONNECTING handle 0x55cb41ad0468; line 1996 (connection #3)
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#3)
* STATE: CONNECTING => PROTOCONNECT handle 0x55cb41ad0468; line 2104 (connection #3)
* STATE: PROTOCONNECT => DO handle 0x55cb41ad0468; line 2134 (connection #3)
* STATE: DO => DONE handle 0x55cb41ad0468; line 2187 (connection #3)
* multi_done: status: 0 prem: 0 done: 0
* Connection #3 to host 127.0.0.1 left intact
* Expire cleared (transfer 0x55cb41ad0468)

[ERROR] Server did not return 101, but instead:0
[INFO]  Reopened connection to webserver. Current connection status: 0
[WARN]  Websocket response wasn't received on time.

* STATE: INIT => CONNECT handle 0x55cb41ad0468; line 1940 (connection #3)
* Added connection 4. The cache now contains 5 members
* Hostname 127.0.0.1 was found in DNS cache
* STATE: CONNECT => CONNECTING handle 0x55cb41ad0468; line 1996 (connection #4)
*   Trying 127.0.0.1:18443...
* Connected to 127.0.0.1 (127.0.0.1) port 18443 (#4)
* STATE: CONNECTING => PROTOCONNECT handle 0x55cb41ad0468; line 2104 (connection #4)
* STATE: PROTOCONNECT => DO handle 0x55cb41ad0468; line 2134 (connection #4)
* STATE: DO => DONE handle 0x55cb41ad0468; line 2187 (connection #4)
* multi_done: status: 0 prem: 0 done: 0
* Connection #4 to host 127.0.0.1 left intact
* Expire cleared (transfer 0x55cb41ad0468)

[ERROR] Server did not return 101, but instead:0
[INFO]  Reopened connection to webserver. Current connection status: 0
[WARN]  Websocket response wasn't received on time.


```

### curl/libcurl version

[curl -V output]
```
curl 8.0.1 (x86_64-poky-linux-gnu) libcurl/7.86.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0)
Release-Date: 2023-03-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP TrackMemory UnixSockets
```

### operating system
```
Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Remarks
I think problem might start in function curl_multi_perform(), please consider this:
![image](https://github.com/curl/curl/assets/16519407/e4a55d1c-6d51-4978-85f7-85cc0f5323a0)

Some additional logs (might be useful):

[INFO] WebServer HTTP Unhandled event: 86 session_data: 0
[INFO] WebServer HTTP Unhandled WS event: 49 session_data 1
[INFO] WebServer HTTP WebSocket upgrade request from 127.0.0.1
[INFO] WebServer HTTP WebSocket upgrade request accepted!

CURL: ..and poll() returned: 1
CURL: return at the end
CURL: After Curl_poll...and returned: 1
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: transfer: Curl_read()
CURL: Curl_read: nread: 160
CURL transfer: data_pending
CURL: Curl_conn_ has data_pending
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..

[INFO]WebServer HTTP WebSocket connection established.

**...and "Time gap ~25s" starts..**

CURL: ..and poll() returned: 1
CURL: return at the end
CURL: After Curl_poll...and returned: 1
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: transfer: Curl_read()
CURL: Curl_read: nread: 11
CURL: transfer: data_pending
CURL: Curl_conn_ has data_pending
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: After Curl_poll...and returned: 1
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: transfer: Curl_read()
CURL: Curl_read: nread: 2
CURL transfer: data_pending
CURL: Curl_conn_ has data_pending
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive:1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: After Curl_poll...and returned: 0
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 0
CURL: curl_multi_perform: multi->num_alive: 1
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: multi_wait() Started
CURL: Curl_poll...
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: After Curl_poll...and returned: 1
CURL: multi_wait() Stopped
CURL: poll() called..
CURL: ..and poll() returned: 1
CURL: return at the end
CURL: transfer: Curl_read()
CURL: Curl_read: nread: 0
CURL: mstate(): num_alive decreased
CULR: set MSTATE_COMPLETED 3
CURL: curl_multi_perform: multi->num_alive: 0
CURL easy_transfer: curl_multi_perform: mcode: 0
CURL: curl_multi_remove_handle() in easy_perform()
CURL: data->mstate = MSTATE_COMPLETED

[INFO] Connection status: 1

**Comment by bagder** [comment]
I don't understand how I can reproduce this. What minimal libcurl using code should I compile and what server/URL can I point it to?

**Comment by bagder** [comment]
Please re-open or submit a new issue once you have more information for us.

**Comment by YopAndMail** [comment]
> Hello,
> 
> I’ve got a problem with version 8.0.1 of curl. **The same code works with 7.84.0, 7.85.0 and 7.86.0, but it stops from 7.87.0 (cfilters introduced) till the latest one.** I had noticed that problem is caused by call of curl_easy_perform() function, which stucks for around 25s and then the rest go wrong (cannot reconnect and buffer is empty and reply delayed). Maybe it is similar to [#11004](https://github.com/curl/curl/issues/11004)
> 
> Curl: 8.0.1 ( and all > 7.86.0) Libwebsockets: 3.2.3 (server) OS: Linux 5.4.0-109-generic [#123](https://github.com/curl/curl/pull/123)-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> 

Hi Jwolak,

I know it is old post but I am working on a portability to a new linux version and of course, there are some updates ^^
I am facing to a similar problem so.

The program I have to adapt uses curl_easy_perform to send some datas.
In the old environment, curl_easy_perform (libcurl v7.64) returns directly.
Now, with the libcurl v7.88, curl_easy_perform stucks around 10 seconds.

I have found a curl linux command which might do the same as my program. If i add "the --connect-timeout <value>" to curl , the curl command works but the program in C with the same options still doesn't (CURLOPT_CONNECTTIMEOUT).

Have you found a solution for his stuck ?
Your solution might help me.

Thanks.
