### ISSUE TITLE
cURL 8.1.0 `URL using bad/illegal format or missing URL` for URL starting with digit

### ISSUE THREAD

**Issue by PkAIR** [curl/curl#11129]
With latest release of cURL 8.1.0 now it impossible to use it for get/put requests with URLs starting with digits.

### I did this

curl http://10.xxx.xxx.xxx/composer/packages.json

### I expected the following

File was downloaded but got `URL using bad/illegal format or missing URL`

### curl/libcurl version

cURL 8.1.0

### operating system

Latest Alpine docker image

**Comment by bagder** [comment]
grrr...
