### ISSUE TITLE
Bug again

### ISSUE THREAD

**Issue by ghost** [curl/curl#11128]
### I did this
```
C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>CertUtil.exe -hashfile curl.exe
Хэш SHA1 curl.exe:
cc58bc14e67b1ccec487dcf230c8b1c0fbffb371
CertUtil: -hashfile — команда успешно выполнена.

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>CertUtil.exe -hashfile curl-ca-bundle.crt
Хэш SHA1 curl-ca-bundle.crt:
c9ce28427c32cc9144871b92eea0557f95c7d070
CertUtil: -hashfile — команда успешно выполнена.

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>CertUtil.exe -hashfile libcurl-x64.def
Хэш SHA1 libcurl-x64.def:
a3cc2b29484bb235a82d7592d7e9c574b4d07a71
CertUtil: -hashfile — команда успешно выполнена.

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>CertUtil.exe -hashfile libcurl-x64.dll
Хэш SHA1 libcurl-x64.dll:
416a00d64ac3e6e7db5b797c7238d327ee17d404
CertUtil: -hashfile — команда успешно выполнена.

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>Echo %ErrorLevel%
0

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>curl.exe -V

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>Echo %ErrorLevel%
-1073741571

C:\Глюк, а не программа\curl-8.1.0_1-win64-mingw\bin>PushD C:\Windows\System32

C:\Windows\System32>CertUtil.exe -hashfile curl.exe
Хэш SHA1 curl.exe:
f64457b2255a6bb2224eed25a0954b5274ec62d7
CertUtil: -hashfile — команда успешно выполнена.

C:\Windows\System32>Echo %ErrorLevel%
0

C:\Windows\System32>curl.exe -V
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

C:\Windows\System32>Echo %ErrorLevel%
0
```

### I expected the following
            Операторы обработки исключительных ситуаций («OnError», «Try», etc) известны более полувека.  Те, кто уважает пользователя, использует их в своих программах для информирования его о происходящем.  Те, кто за 25 лет так и не научился программировать (и гордится этим), оставляют перехват ошибок операционной системе (что она и делает, потому что её-то писали грамотные люди, а не дилетанты).
            Происходит ровно то, что я и ожидал – ошибку в глючной программе перехватывает ТОЛЬКО операционная система:
«-1073741571 == c00000fd. That's an error code from the OS and not curl.»(©https://github.com/curl/curl/issues/10802#issuecomment-1476884083)
            P.S.  Для тех, кому не нравится используемый мною язык, может, ещё и фразу «команда успешно выполнена» переводить, которую выдаёт системная программа «CertUtil»?  Потребуйте у Microsoft, чтобы «CertUtil» выдавала сообщения СРАЗУ НА ВСЕХ известных языках и вы могли бы выбрать удобный вам.
            P.P.S.  Плюя на пользователя, вы самим себе затрудняете поиск ошибок.  А я вам подсказывать не собираюсь.
### curl/libcurl version

[curl -V output]

### operating system
MS Windows 10

**Comment by bagder** [comment]
Pleas submit issues in English.
