### ISSUE TITLE
curl doesn't seem to retry on certain [transient] SSL errors - or maybe on "Connection reset by peer"

### ISSUE THREAD

**Issue by pfalcon** [curl/curl#11124]
We're using curl in CI pipeline, and of course, curl operations fail from time to time. One failure I just saw is (from build log):

```
00:00:43.364 + curl --fail --connect-timeout 5 --retry 5 -sLS -o /home/buildslave/workspace/tf-a-builder/workspace/mbedtls.tar.gz https://github.com/Mbed-TLS/mbedtls/archive/mbedtls-2.28.1.tar.gz
00:00:48.381 curl: (28) SSL connection timeout
00:05:20.165 curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

~~As the timestamps show, there unlikely were any retries, just single 5s connection timeout, after which curl just failed.~~ UPDATE: The previously written doesn't seem to be true, as after all it spent 5m2s running. But it still failed on "Connection reset by peer", and please below for a report where it fails on "Connection reset by peer" in 0.2s despite --retry.

The expected behavior is that it retries with exponential backoff.

That happens on Ubuntu Jammy, i.e. curl 7.81.0.

**Comment by pfalcon** [comment]
Actually, reading man for `-connect-timeout`:

> Maximum time in seconds that you allow curl's connection to take.  This only limits the connection phase, so if curl connects within the given period it will continue - if not it will exit.

If taken literally ("it will exit"), that it's clearly not the expected behavior of curl, given availability of the `--retry` option. Not being able to connect once is absolutely normal transient error for any more or less loaded system.

**Comment by bagder** [comment]
Maybe if you remove `-s` you get some more information that helps explain what's going on?

**Comment by bagder** [comment]
I would say so, but I am not convinced it always does. I would even like `-v` to be used to show more of what's happening.

**Comment by pfalcon** [comment]
Thanks for looking into this. We've seen another case like that, with different error:

```
00:02:31.590 Fetch: https://downloads.trustedfirmware.org/tf-a/css_scp_2.12.0/morello/release/morello-fvp-mcp-bl2.bin -> mcp_ram.bin
00:02:31.590 ++ curl --fail --connect-timeout 10 --retry 6 -sLS -o mcp_ram.bin https://downloads.trustedfirmware.org/tf-a/css_scp_2.12.0/morello/release/morello-fvp-mcp-bl2.bin
00:02:31.717 curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to downloads.trustedfirmware.org:443 
```

(For reference, the log is here: https://ci.trustedfirmware.org/job/tf-a-builder/2093525/console , but will expire soon.)

(Since initial report, I increased `--connect-timeout` and  `--retry`) Now that's for sure didn't try to do many retries, spending 0.2s before quitting with the error.

**Comment by pfalcon** [comment]
> That one gets a "Connection reset by peer" which is not considered a "transient error" so it stops there. I don't think that's the issue.

Thanks, I guess we nailed it. But why it's not considered a transient error? By all means, it is, it shows either capacity issues on the TCP/IP stack side (to many connections opened, so it starts to drop them), or a non-deterministic issue with a particular connection (e.g. ran out of retries on the TCP/IP stack side, e.g. because there was a glitch with a physical connection).

**Comment by bagder** [comment]
> By all means, it is

For you it might be. In general it is not. It is a connection problem with no hint about it being a transient problem.

You *can* make it retry for this as well with `--retry-all-errors`, but beware that this option is a pretty blunt hammer.

**Comment by pfalcon** [comment]
> You can make it retry for this as well with --retry-all-errors, but beware that this option is a pretty blunt hammer.

Ah, great, dunno how I overlooked that option! (Maybe because in man, they're sorted before `--retry`, which isn't intuitive/lexicographical sort, so once you read `--retry` and see then next option starts with "s", you don't expect that there're many more in store elsewhere). Should be better as the first try than engineering a shell script retry logic.

Actually, looking up that option in man, I see also:

`--retry-connrefused`

Well, if such an error has an option to treat as transient, than it would be not less worthy to have --retry-connreset. Because both can be signs of transient TCP/IP errors which are worth retrying, but ECONNREFUSED has very obvious "permanent" meaning - there's just no server running on that TCP port (or it went down, which is still more "sticky" than ECONNRESET which can happen any time non-deterministically and be gone on next try).


So, thanks for the prompt response and helpful discussion here, appreciated! I don't close the ticker myself in a humble attempt to lobby for `--retry-connreset` to be added ;-). But if it's not worth it, please close it.

**Comment by bagder** [comment]
I'm not convinced we should go down the route of adding `--retry-*` options for a growing number of errors. If someone deems this important enough, we should rather add a new option that tells exactly for which reasons retries should be performed in a list-style of way.
