### ISSUE TITLE
Missing info for the third arg in `curl_easy_getinfo` documentation

### ISSUE THREAD

**Issue by Hind-M** [curl/curl#11123]
Hello there!
We are using libcurl in a C++ project, and following the [docs](https://curl.se/libcurl/c/curl_easy_getinfo.html) we used `curl_easy_getinfo` with only the specified types for the third argument: a pointer to `long`, `char *`, `curl_slist *` or `double`.
One of our users had a segmentation fault because of using `CURLINFO_SPEED_DOWNLOAD_T` with `curl_easy_getinfo` which requires a pointer to `curl_off_t`. The latter can be `long` or `long long` depending on the platform (cf. [PR](https://github.com/mamba-org/mamba/pull/2528)).
Do you confirm that the documentation should be updated to specify that the third argument can be a pointer to `curl_off_t` and `long long` as well? (I can submit a PR in that case if needed).
Thanks!

**Comment by bagder** [comment]
Confirmed. But we don't use `long long` explicitly.

`curl_easy_getinfo()` can return data in these six different data types:

- `char *`
- `long`
- `double`
- `curl_off_t`
- `struct curl_list *`
- `curl_socket_t`

You can use publicly available `CURLINFO_*` symbols to figure out what a particular option wants based on the `CURLINFO_*` number.

**Comment by bagder** [comment]
Fixed via #11126 and de522c55ba23e7614978adcffb073fb41120ec82
