### ISSUE TITLE
`Curl_poll` may not ignore EINTR if 0 file descriptors are passed

### ISSUE THREAD

**Issue by pitrou** [curl/curl#11135]
I encountered this potential issue when trying to investigate a [user report](https://github.com/apache/arrow/issues/35318).

In the general case, `Curl_poll` will translate EINTR into a no-error return so that the caller may retry:
https://github.com/curl/curl/blob/a9f8fe28481fef7c28d85b4a12a3a35521408eaf/lib/select.c#L312-L318

However, if no valid fds are passed, `Curl_poll` delegates to `Curl_wait_ms` which doesn't try to eliminate EINTR errors:
https://github.com/curl/curl/blob/a9f8fe28481fef7c28d85b4a12a3a35521408eaf/lib/select.c#L94-L104

`Curl_poll` is used from `Curl_multi_wait` where it's not obvious whether a non-zero number of file descriptors is always [found](https://github.com/curl/curl/blob/a9f8fe28481fef7c28d85b4a12a3a35521408eaf/lib/multi.c#L1185-L1207).

This might be a red herring, but I suppose it wouldn't hurt fixing `Curl_wait_ms` (and/or `Curl_poll`) in any case.

**Comment by bagder** [comment]
@pitrou are you up to making a PR for this?

**Comment by pitrou** [comment]
I can try to do that.
