### ISSUE TITLE
Win 11 x64 nmake build fails

### ISSUE THREAD

**Issue by JW-Schuetz** [curl/curl#11145]
### I did this

On my Windows 11 64-Bit machine I executed in the "winbuild" directory in an "cmd"-window:

"nmake /f Makefile.vc mode=static VC=22 machine=x64 debug=no"

and get the following error in link step (translated from german to english)

..\builds\libcurl-vc22-x64-release-static-ipv6-sspi-schannel-obj-curl\tool_hugehelp.obj : fatal error LNK1112: modul computer type "x86" conflicting with target computer type "x64".
NMAKE : fatal error U1077: "link.exe /incremental:no /libpath:"..\builds\libcurl-vc22-x64-release-static-ipv6-sspi-schannel\lib" 

A x86 build works fine.

### I expected the following
A successful x64-build.

### curl/libcurl version
8.1.0

### operating system
Windows 11 Pro, Version 10.0.22621 Build 22621

**Comment by gvanem** [comment]
> A x86 build works fine.

Seems you did not run `vcvars64.bat` (or similar) prior to building.
Ref: https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170

**Comment by JW-Schuetz** [comment]
You are right. Thanks.
I missed to use the VS developer console :-(
