### ISSUE TITLE
running prog using libcurl built with CMake outputs: no version information available

### ISSUE THREAD

**Issue by bruno-kakele** [curl/curl#11158]
### I did this

I compiled libcurl following the instructions here: [https://github.com/curl/curl/blob/a64d7de61af5fb94b70972cd0981020e729c1499/docs/INSTALL.cmake](https://github.com/curl/curl/blob/a64d7de61af5fb94b70972cd0981020e729c1499/docs/INSTALL.cmake)

(cmake ../curl && make && make install)

### I expected the following

After installation, running `cmake --version` I get the following warning:

`cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)`

(cmake version 3.22.1). I expected that there would be version information available.

### curl/libcurl version

```
$ curl -V output
curl 7.87.0-DEV (Linux) libcurl/7.87.0-DEV OpenSSL/3.0.2 zlib/1.2.11 c-ares/1.18.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe UnixSockets
```

(I have built it with ares support, the instructions file seems outdated?)

### operating system

`Linux bruno 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

It seems that this is supported via `enable-versioned-symbols` with ./configure, but not with cmake? I apologize if this is working as intended and if this a feature request instead. Thanks in advance

**Comment by bagder** [comment]
> curl 7.87.0-DEV

That's not a release version, Does it contain 5de6848f104d7? That's when we added SONAME support to the cmake build.

**Comment by bruno-kakele** [comment]
Thanks badger for replying! I think it may have included that. I am trying now with 8.1.0:

```
git clone https://github.com/curl/curl /tmp/curl
...
git checkout tags/curl-8_1_0
...
cmake -D CMAKE_CXX_COMPILER=/usr/bin/clang++-14 -D CMAKE_C_COMPILER=/usr/bin/clang-14 -D CMAKE_BUILD_TYPE=Release -DENABLE_ARES=true -DCURL_ENABLE_SSL=true ../
make
make install
```

curl --version: 
```
curl 8.1.0-DEV (Linux) libcurl/8.1.0-DEV OpenSSL/3.0.2 zlib/1.2.11 c-ares/1.18.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe UnixSockets
```

cmake --version: 
```
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
cmake version 3.22.1
```

Please let me know if you need additional information, thanks.

**Comment by bagder** [comment]
Then I presume the way cmake creates the SONAME in the library is somehow bad? I don't know why it says this.

I suppose a workaround is to build with configure, which is a more proven and feature-compete build system for curl.
