### ISSUE TITLE
FreeBSD 14 "owns" struct http_req

### ISSUE THREAD

**Issue by bagder** [curl/curl#11163]
(Found here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271526, reported by "O. Hartmann")

> Just updating ports: curl 8.0.1 -> 8.1

~~~

[...]
In file included from cf-socket.c:56:
In file included from ../lib/urldata.h:168:
../lib/http.h:263:8: error: redefinition of 'http_req'
struct http_req {
       ^
/usr/include/netinet/tcp.h:466:8: note: previous definition is here
struct http_req {
~~~

I would say this is a bug in their `netinet/tcp.h` header file, but I doubt that helps. We should rename our struct.

**Comment by emaste** [comment]
> I would say this is a bug in their netinet/tcp.h header file

It certainly is, and we (FreeBSD) need to change it. But thank you for this change so that curl won't be broken until then.
