### ISSUE TITLE
failed to parse URL if password ends with #

### ISSUE THREAD

**Issue by dibalavs** [curl/curl#1116]
### I did this
I have credentials to host access:
login: login
password: pswd#
curl https://login:pswd#@host.com

curl returns error:
curl: (6) Could not resolve host: login

### I expected the following
success connection

### curl/libcurl version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

[curl -V output perhaps?]
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

### operating system
ubuntu 16.04

This issue happened after I installed latest security updates from ubuntu 16.04.
I think this issue related to fix CVE: https://curl.haxx.se/docs/adv_20161102J.html
and now # is not interprets as symbol from password.

**Comment by bagder** [comment]
The hash symbol (`#`) was never an allowed character like that, and the fact that it worked previously was mostly random. `#` is used in URLs to specify the 'fragment' part. You need to URL encode the password and then that symbol will appear as `%23`:

    curl https://login:pswd%23@host.com

The `#` is not the only letter in passwords that will cause problems so you're really better off always URL encoding the passwords you use in URLs to avoid future similar problems with other letters.

**Comment by dibalavs** [comment]
it works. thank you very much.
