### ISSUE TITLE
Undefined references when compiling a c program with gcc

### ISSUE THREAD

**Issue by slezercc** [curl/curl#11168]
C:\MinGW\bin>gcc.exe drax.c -o draxo.exe -I"C:\curl\include" -L"C:\curl\lib" -static -lcurl -lws2_32 -lwinmm -lgdi32

drax.c:(.text+0xfb): undefined reference to _imp__curl_easy_init'
drax.c:(.text+0x153): undefined reference to _imp__curl_easy_setopt'
drax.c:(.text+0x179): undefined reference to _imp__curl_easy_setopt'
drax.c:(.text+0x19f): undefined reference to _imp__curl_easy_setopt'
drax.c:(.text+0x1ad): undefined reference to _imp__curl_easy_perform'
drax.c:(.text+0x1d2): undefined reference to _imp__curl_easy_strerror'
drax.c:(.text+0x21b): undefined reference to _imp__curl_easy_cleanup'
collect2.exe: error: ld returned 1 exit status

Moving -lcurl to the end of the command gives the same error.
adding  -DCURL_STATICLIB before -lcurl doesn't do anything.

**Comment by emanuele6** [comment]
What does `curl-config.exe --libs --cflags` output?

**Comment by slezercc** [comment]
> What does `curl-config.exe --libs --cflags` output?

'curl-config.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by emanuele6** [comment]
See https://curl.se/docs/faq.html#Link_errors_when_building_libcur

**Comment by bagder** [comment]
`-DCURL_STATICLIB` for the the compile, not the link phase.

**Comment by slezercc** [comment]
> `-DCURL_STATICLIB` for the the compile, not the link phase.

What would be the command I would have to run in cmd with gcc.exe?
I tried this gcc.exe drax.c -o draxo.exe -I"C:\curl\include" -L"C:\curl\lib" -static -lcurl -lws2_32 -lwinmm -lgdi32
and this: gcc.exe drax.c -o draxo.exe -I"C:\curl\include" -L"C:\curl\lib" -static -lcurl -lws2_32 -lwinmm -lgdi32 -DCURL_STATICLIB

**Comment by slezercc** [comment]
Thanks for closing the issue and not actually resolving the problem I had!
