### ISSUE TITLE
configure stuck at "checking if compiler is Tiny C... no" with GCC 4.9.4

### ISSUE THREAD

**Issue by tawmoto** [curl/curl#11189]
I did this:

```
CFLAGS=" --sysroot=/opt/toolchains/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot -fPIC -DPIC -m64" ./configure --enable-ftp --enable-proxy --enable-ipv6 --enable-http --enable-nonblocking --enable-crypto-auth --enable-hidden-symbols --enable-soname-bump --enable-static --disable-shared --disable-dict --disable-ares --disable-telnet --disable-tftp --disable-manual --disable-rtsp --disable-file --disable-pop3 --disable-imap --disable-smtp --disable-ldap --disable-ldaps --disable-sspi --disable-ntlm --without-libssh2 --without-zlib --without-zstd --without-gnutls --without-nss --without-libidn --without-libidn2 --without-nghttp2 --without-librtmp --without-brotli --without-libpsl --prefix="..." --with-ssl="{openssl-dir}" --disable-openssl-auto-load-config --disable-rt --disable-threaded-resolver --disable-debug --disable-curldebug
```
I get
```
checking if compiler is GNU C... yes
checking if compiler is LCC... no
checking if compiler is SGI MIPSpro C... no
checking if compiler is SGI MIPS C... no
checking if compiler is SunPro C... no
checking if compiler is Tiny C... no -> hangs here
```

Very similar to
https://github.com/curl/curl/issues/11179

`curl` version 8.1.1
Xubuntu 22.04, but it happens on other Linuxes also.

There is a patch here: https://github.com/curl/curl/pull/11180

But I don't use `configure.ac` (the file changed by the patch), I am using `configure` directly, so it does not work

Thanks

**Comment by bagder** [comment]
After applying the #11180 patch you need to run `autoreconf -fi`, or you can download the daily snapshot tomorrow (May 24) from https://curl.se/snapshots/ since that will contain a freshly generated configure script.

**Comment by bagder** [comment]
This said, `checking if compiler is Tiny C` seems too early of a problem for it to be #11179. This looks like something else.

**Comment by tawmoto** [comment]
> After applying the #11180 patch you need to run `autoreconf -fi`, or you can download the daily snapshot tomorrow (May 24) from https://curl.se/snapshots/ since that will contain a freshly generated configure script.

I tried with `configure` from 8.1.0 and works perfeclty
thank you Daniel, I will wait for tomorrow's `configure` script then :+1:

**Comment by tawmoto** [comment]
Unfortunately it does not work, I will just use the old `configure` from 8.1.0 for now
```
[DEBUG] 	libtool: Version mismatch error.  This is libtool 2.4.7 Debian-2.4.7-5, but the
	[DEBUG] 	libtool: definition of this LT_INIT comes from libtool 2.4.6.
	[DEBUG] 	libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7 Debian-2.4.7-5
	[DEBUG] 	libtool: and run autoconf again.
```

**Comment by bagder** [comment]
Have you tried with the 8.1.2 release?

**Comment by tawmoto** [comment]
> Have you tried with the 8.1.2 release?

works perfectly, thanks a lot Daniel.
