### ISSUE TITLE
Unable to compile curl with latest ngtcp2 code

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#11190]
i cloned latest ngtcp2 code and curl code base.
i tried to build curl with latest ngtcp2 code base but failing with below error

root@ubuntu:/src/curl# make
Making all in lib
make[1]: Entering directory '/src/curl/lib'
make  all-am
make[2]: Entering directory '/src/curl/lib'
  CC       vquic/libcurl_la-curl_ngtcp2.lo
vquic/curl_ngtcp2.c: In function ‘quic_settings’:
vquic/curl_ngtcp2.c:329:6: error: ‘ngtcp2_settings’ has no member named ‘qlog’
  329 |     s->qlog.write = qlog_callback;
      |      ^~
vquic/curl_ngtcp2.c: At top level:
vquic/curl_ngtcp2.c:904:47: error: unknown type name ‘ngtcp2_crypto_level’; did you mean ‘ngtcp2_crypto_side’?
  904 | static int cb_recv_rx_key(ngtcp2_conn *tconn, ngtcp2_crypto_level level,
      |                                               ^~~~~~~~~~~~~~~~~~~
      |                                               ngtcp2_crypto_side
vquic/curl_ngtcp2.c:959:3: error: ‘cb_recv_rx_key’ undeclared here (not in a function)
  959 |   cb_recv_rx_key,
      |   ^~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: In function ‘cf_ngtcp2_connect’:
vquic/curl_ngtcp2.c:2394:6: error: implicit declaration of function ‘ngtcp2_conn_is_in_draining_period’; did you mean ‘ngtcp2_conn_in_draining_period’? [-Werror=implicit-function-declaration]
 2394 |      ngtcp2_conn_is_in_draining_period(ctx->qconn)) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      ngtcp2_conn_in_draining_period
cc1: some warnings being treated as errors
make[2]: *** [Makefile:3269: vquic/libcurl_la-curl_ngtcp2.lo] Error 1
make[2]: Leaving directory '/src/curl/lib'
make[1]: *** [Makefile:1506: all] Error 2
make[1]: Leaving directory '/src/curl/lib'
make: *** [Makefile:1266: all-recursive] Error 1
root@ubuntu:/src/curl#
root@ubuntu:/src/curl#

root@ubuntu:/src/curl# uname -a
Linux ubuntu 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/src/curl#

I beleive this is the commit causing this issue 
https://github.com/ngtcp2/ngtcp2/commit/82659de04079a985a4716c748f5570955f25871c

i just wanted to report this issue and Hope this is not a known issue.
(as per documentation i am using ngtcp2: v0.15.0,nghttp3: v0.11.0 and working fine)

**Comment by Karthikdasari0423** [comment]
Hope after this commit issue might be solved
https://github.com/curl/curl/pull/11184

**Comment by bagder** [comment]
We keep curl and curl's CI jobs in sync with the latest release tags of ngtcp2, which for now is still 0.15.0. It means that when they break their APIs like now, the current git master does not build with the current ngtcp2 master.

The #11184 made curl work with ngtcp2 master just hours ago for me so it should still be fine. We will not merge that though until ngtcp2 makes another release tag for us to use.

**Comment by Karthikdasari0423** [comment]
Thank you for update @bagder
