### ISSUE TITLE
CURLE_URL_MALFORMAT when numerical subdomain in URL

### ISSUE THREAD

**Issue by Robotista** [curl/curl#11191]
### I did this
curl "http://111.example.com"
I get curl: (3) URL using bad/illegal format or missing URL

### I expected the following
Content of the page printed out. Or in case of this dummy URL I expect output:
 curl: (6) Could not resolve host: 111.example.com

### curl/libcurl version
curl 8.1.0

[curl -V output]
curl 8.1.0 (i386-pc-win32) libcurl/8.1.0 Schannel zlib/1.2.11
Release-Date: 2023-05-17
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

### operating system
All

The numeric subdomains are perfectly valid, yet they are refused by CURL. This was not issue in older versions (worked in 7.40.0). The issue is that host name starting with numeric subdomain is recognized as IP adress (malformed one) by ipv4_normalize function. I guess the the IP/HOST_NAME recognition should be more rigid.

Thank you.

**Comment by emanuele6** [comment]
This has been fixed in the `8.1.1` patch release released today, upgrading should solve your problem.

Diplicate of #11129

**Comment by Robotista** [comment]
8.1.1 patch resolved the issue indeed. Thanks.
