### ISSUE TITLE
libcurl-axTLS reports CURLE_SSL_CONNECT_ERROR (35)

### ISSUE THREAD

**Issue by gnanagurun** [curl/curl#1120]
### curl/libcurl version

[curl -V output perhaps?]

**Comment by gnanagurun** [comment]
When i do https POST operation using libcurl (version curl-7.50.1 compiled with axTLS version 1.4.9), libcurl returns error code 35. Even i tried with disabling CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST. Please help me resolve this issue

**Comment by bagder** [comment]
Can you do a normal GET? Can you communicate with other HTTPS sites fine?

**Comment by bagder** [comment]
This said, my curl+axTLS 1.5.1 build can't do a get from https://curl.haxx.se/

And I haven't even managed to build axTLS 2.0.1 from source.

Changes are this is just axTLS being borked.

**Comment by gnanagurun** [comment]
Thanks for your response. The web site https://curl.haxx.se/libcurl/c/libcurl-errors.html saying the error code 35 is more related to SSH handshake failure. But couldn't figure on what condition the SSH handshake failure will occur.

**Comment by bagder** [comment]
Eh, no it says there's an SSL problem, which seems totally logical and matches what I see with my basic axtls-tests

> CURLE_SSL_CONNECT_ERROR (35)
> 
> A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

**Comment by gnanagurun** [comment]
yeah it is SSL handshake. So this issue could be with axTLS library?

**Comment by bagder** [comment]
It is for sure related to axTLS since we don't see this with any other TLS library/backend.

**Comment by bagder** [comment]
Closing this. Please file a bug with axTLS about this problem. It seems to be a limitation in that lib.

**Comment by gnanagurun** [comment]
Thank you very much. Yeah looking out the possibilities in axTLS to fix this SSL handshake issue
