### ISSUE TITLE
detect strerror_r flavor when cross-compiling with cmake

### ISSUE THREAD

**Issue by servusoft** [curl/curl#1123]
The cross compiling of `curl` fails becose macros `HAVE_GLIBC_STRERROR_R` or `HAVE_POSIX_STRERROR_R` can't be recognized. The recognize routine runs the compiled binary (eg. ARM) on AMD64 and (it's clear) will fail.  These method works well at native comiling and will always fail at cross compiling.

The goal is to determine which library provides the symbol `strerror_r`. This can be determine to the compile time. The macros `__GLIBC__`  and `__GLIBC_MINOR__` are defined by  file `features.h` unconditionally and can be used to test for GLIBC. On POSIX systems on which these functions are available, the symbol _POSIX_TIMERS is defined in `unistd.h` to a value greater than 0. 

The recognize routine should be extended for cross compiling (by using of the described logic).

**Comment by bagder** [comment]
The current configure check for `strerror_r` have been in place since at least 2008 (b93ad10f modified them, they were around before too). curl has been used and built *widely* cross-compiled since then, which tells me this isn't usually a problem for people. Also, the `strerror_r` check **does not** run any compiled code, it just verifies that it *can* compile the code and a cross-compiler should already be able to compile the code fine.

Detecting glibc header symbols to deduce if the glibc version of the function works seems more error-prone and I'm actually not at all sure how all the alternative libc versions on various embedded linux systems works etc.

@jay labeled this issue 'cmake'. Can you clarify if you used cmake or configure to build, @servusoft ?

**Comment by servusoft** [comment]
jdavidberger has alredy reportet about this issue:
https://github.com/curl/curl/pull/545

The `Macros.cmake` uses `try_run` function wich runs the compiled binary:
```
    message(STATUS "Performing Curl Test ${CURL_TEST}")
    try_run(${CURL_TEST} ${CURL_TEST}_COMPILE
      ${CMAKE_BINARY_DIR}
      ${CMAKE_CURRENT_SOURCE_DIR}/CMake/CurlTests.c
      CMAKE_FLAGS -DCOMPILE_DEFINITIONS:STRING=${MACRO_CHECK_FUNCTION_DEFINITIONS}
      "${CURL_TEST_ADD_LIBRARIES}"
      OUTPUT_VARIABLE OUTPUT)
```
The cmake log reports:

```  ... 
-- Looking for strerror_r
-- Looking for strerror_r - found
...
-- Check size of off_t
-- Check size of off_t - done
-- Performing Curl Test HAVE_GLIBC_STRERROR_R
-- Performing Curl Test HAVE_GLIBC_STRERROR_R - Failed
-- Performing Curl Test HAVE_POSIX_STRERROR_R
-- Performing Curl Test HAVE_POSIX_STRERROR_R - Failed
-- Check size of socklen_t
-- Check size of socklen_t - done
...```

The detecting over header symbols is less reliable, but I have no better idea. It may be used only at cross-compiling. The CMake variable `CMAKE_CROSSCOMPILING` is true at cross-compiling and it can be used as trigger for another detecting logic. 
more infos: http://www.vtk.org/Wiki/CMake_Cross_Compiling

**Comment by bagder** [comment]
Ah, so cmake it is. I personally have no idea how to do or fix cmake things for cross compiling. I would probably suggest you switch to the configure based build in the mean time until this is fixed, which has done cross-compiling fine for many years.

**Comment by servusoft** [comment]
I guess the cross compiling was done with autotools and also has worked. 
With cmake probably no one has yet tried.
I could make an adjustment and test it.

**Comment by jzakrzewski** [comment]
I suppose there are some tests where ```try_link``` should be used insted (and this is one of them). I'm a little out of time recently but will look into it as soon as things get better.

**Comment by servusoft** [comment]
If many cases try_link can be a good solution.
But in this particular case is tried how the error buffer is formatted 
(whether the buffer is in POSIX or in GLIBC style). 
The linking works in both cases, but runing works only once of them.

**Comment by bagder** [comment]
Nobody works on this. Now added as a known problem in `docs/INSTALL.cmake`.

**Comment by MaxSavenkov** [comment]
I propose a fix that relies of compile-time type check in #2443
