### ISSUE TITLE
Issue with self-signed certificates

### ISSUE THREAD

**Issue by mdziczkowski** [curl/curl#11243]
There seem to be a issue with curl, with is blocking block it on pages that use the Certbot (and alike) and so called "self-signed" certificates.

Currently, I don't see any avaliable option to bypass it in the CLI.

If it is notba bug then please convert it into a feature request. Thanks

**Comment by dfandrich** [comment]
Are you looking for the `--insecure` flag?

**Comment by bagder** [comment]
curl verifiers server certificates by default. You can disable that with `--insecure`, but we do not recommend that. Instead we recommend that you make sure that you have all your trusted CA certificates in your CA store.

If you use "certbot" to get certificates from Let's Encrypt for example, any decent CA store should have that CA certificate present. One option is to download a CA cert bundle from here: https://curl.se/docs/caextract.html - which is the CA store that Mozilla maintains, converted to a convenient PEM format.

More details, including how to make your self-signed cert into "CA cert" for use with curl here: https://curl.se/docs/sslcerts.html

**Comment by mdziczkowski** [comment]
@bagder

Thanks. Since it's not a bug, could you please convert it into a feature request?

It would be great if the next releases of curl would defaultly accept self-signed certificates as valid ones

**Comment by bagder** [comment]
curl already supports that fine (and has always done it), you just need to save the certificate and use the `--cacert` option
