### ISSUE TITLE
Cygwin build make check log message "WARNING: UNPROTECTED PRIVATE KEY FILE!"

### ISSUE THREAD

**Issue by BrianInglis** [curl/curl#11244]
Between tests 0581 and 0584 got multiple occurrences of:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '$HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Unable to load host key "$HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/": bad permissions
Unable to load host key: $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/
sshd: no hostkeys available -- exiting.
=== End of file $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/log/ssh_server.log
```
See in:
[Cygwin-curl-8.1.2-1-check.log](https://github.com/curl/curl/files/11644456/Cygwin-curl-8.1.2-1-check.log)
Script `sshd-curl-config` was generated under out of tree build dir ...`/build/tests/log/server/`, as were the key files `{curl_client_key,curl_host_rsa_key}{,.pub}`... so it seems that directory, or another created for the keys, should have their permissions limited to 0700, as expected for `~/.ssh/` directories, and if the higher level directory specified in the message is spurious, that should also be corrected.

### I did this
`make check`

### I expected the following
Tests build and run, possibly not all successfully.

### curl/libcurl version
```
$ curl-8.1.2-1.x86_64/inst/usr/bin/curl -V
curl 8.1.2 (x86_64-pc-cygwin) libcurl/8.1.2 OpenSSL/1.1.1t zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.53.0 libgsasl/2.2.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system
Cygwin 3.4.6 under Windows 10 [20]21H2 19044

**Comment by bagder** [comment]
What is curious is why this happens on cygwin and not elsewhere, as I figure openssh is as picky everywhere.

The `sshserver.pl`  script does use `chmod 600`:

https://github.com/curl/curl/blob/6854b6c58e6288c848a60f7732103726a6211c51/tests/sshserver.pl#L411-L413

What also puzzles me is why the warning messages use the directory name and not the specific file names:

> Unable to load host key "$HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/": bad permissions

**Comment by BrianInglis** [comment]
Those private key files `curl_client_key` `curl_host_rsa_key` are `0600`, but all other files in that directory and above are `0644`, and that directory `$HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/log/server/`, and its containers, up to the directory named, and used in the `curl_sshd_config` file (below), are all `0755`.
*[lightly sanitized for my protection]*
```ssh
# This is a generated file.  Do not edit.
# OpenSSH 9.3.0 sshd configuration file for curl testing
#
DenyUsers !$USER
AllowUsers $USER
AuthorizedKeysFile $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/
AuthorizedKeysFile2 $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/
HostKey $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/
PidFile $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/
...
```
*Cygwin* is up to date on *OpenSSH* `9.3p1` although we are lagging a bit on *OpenSSL* `1.1.1t`.

**Comment by bagder** [comment]
> AuthorizedKeysFile $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/

This is probably the best hint: it specifies the directory and not the correct file.

Is this the patch that is missing?
~~~diff
diff --git a/tests/sshserver.pl b/tests/sshserver.pl
index 2a6956189..8924e9f1f 100755
--- a/tests/sshserver.pl
+++ b/tests/sshserver.pl
@@ -450,13 +450,13 @@ if ($sshdid =~ /OpenSSH-Windows/) {
     $pidfile_config = pathhelp::sys_native_abs_path($pidfile);
     $sftpsrv_config = pathhelp::sys_native_abs_path($sftpsrv);
 }
 elsif (pathhelp::os_is_win()) {
     # Ensure to use MinGW/Cygwin paths
-    $clipubkeyf_config = pathhelp::build_sys_abs_path($clipubkeyf_config);
-    $hstprvkeyf_config = pathhelp::build_sys_abs_path($hstprvkeyf_config);
-    $pidfile_config = pathhelp::build_sys_abs_path($pidfile_config);
+    $clipubkeyf_config = pathhelp::build_sys_abs_path($clipubkeyf);
+    $hstprvkeyf_config = pathhelp::build_sys_abs_path($hstprvkeyf);
+    $pidfile_config = pathhelp::build_sys_abs_path($pidfile);
     $sftpsrv_config = "internal-sftp";
 }
 else {
     $clipubkeyf_config = abs_path(pp($clipubkeyf));
     $hstprvkeyf_config = abs_path(pp($hstprvkeyf));

**Comment by BrianInglis** [comment]
That patch is missing, but should be irrelevant on *Cygwin*, as it should always be treated just like any *newlib* based *Unix* (**never** like *Windows*!) and always take the `else`  option, but on *Cygwin* we do cross-build (and test) *Mingw* `mingw64-x86_64-curl` devel packages, as we do on *Fedora* (on which we also cross-build for *Cygwin*!), and *Mingw* is **native** *Windows*. 

I also noticed use of `cygpath`, which is only used for *Windows* path interop, never in "native" *Cygwin*, nor native *Windows*, although I think it is used with *Msys*, which uses *Cygwin* internally for native *Windows* development using *GNU* toolchain. 

*Cygwin* packages treat paths like *BSD*/*Linux*, and some utilities may be so transparent that *Windows* paths pass thru the emulation layer and may be used verbatim; but a lot of *Unix* utilities mess with paths, and we do not care if *Windows* paths cause problems: users are advised to use *Cygwin*/*Unix* paths, and use `cygpath` to convert *Windows* paths (if they really feel the need to use them) to valid form. 

[Personally, I have mostly used `/` in native *DOS/Windows* paths (except some annoying *MS* utilities that *require* `\`) since *DOS* supported `switchar` to allow `/` paths instead of `\` paths and `-options` instead of `/options`!
I automatically typed `\\` there, and found the escape was not needed in this markup, so deleted them ;^> ]

**Comment by bagder** [comment]
> That patch is missing

Does it make the test run fine when applied?

> but should be irrelevant on Cygwin

Feel free to propose a change that removes the use of it.

**Comment by vszakats** [comment]
Can't speak for Cygwin specifically, but since it runs on Windows, it _may_ be affected by Windows ACLs. To fix that in libssh2, I had to do this:
https://github.com/libssh2/libssh2/blob/187d89bb0740400e8fa0b5f1441d089392797f53/tests/test_sshd.test#L93-L98

**Comment by BrianInglis** [comment]
*Cygwin* emulates *Windows* ACLs as *Linux*/*NFSv4* ACLs and provides `getfacl`/`setfacl`, so the equivalent to your commands above is probably `setfacl -b $PRIVKEY`, to remove all non-default POSIX permissions, although the *Cygwin* package build scripts avoid issues by setting build tree dirs like that and also make them case sensitive (if supported, as on recent Windows), avoiding issues with some Linux sources, like e.g. Linux man pages. 
For example, `lsp` is a *Cygwin* `bash` function below which makes checking perms easier by showing output from `ls`, `getfacl`, and `icacls` on file args:
```
$ which lsp
lsp ()
{
    local p o='-n';
    for p in "$@";
    do
        echo $o;
        /bin/ls --color=auto -adlL "$p" && echo && getfacl "$p" && icacls "$(cygpath -m "$p")";
        o='';
    done
}
```
with lightly sanitized output from config/keys dir and some files:
```
$ lsp curl-8.1.2-1.x86_64/build/tests/log/server{,/curl_client_key*}
drwxr-xr-x 1 $USER None 0 Jun  6 16:08 curl-8.1.2-1.x86_64/build/tests/log/server

# file: curl-8.1.2-1.x86_64/build/tests/log/server
# owner: $USER
# group: None
user::rwx
group::r-x
other::r-x
default:user::rwx
default:group::r-x
default:other::r-x

curl-8.1.2-1.x86_64/build/tests/log/server $HOSTNAME/$USER:(F)
                                           $HOSTNAME/None:(RX)
                                           Everyone:(RX)
                                           CREATOR OWNER:(OI)(CI)(IO)(F)
                                           CREATOR GROUP:(OI)(CI)(IO)(RX)
                                           Everyone:(OI)(CI)(IO)(RX)

Successfully processed 1 files; Failed processing 0 files

-rw------- 1 $USER None 2602 Jun  3 16:37 curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key

# file: curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key
# owner: $USER
# group: None
user::rw-
group::---
other::---

curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key $HOSTNAME/$USER:(R,W,D,WDAC,WO)
                                                           $HOSTNAME/None:(Rc,S,RA)
                                                           Everyone:(Rc,S,RA)

Successfully processed 1 files; Failed processing 0 files

-rw-r--r-- 1 $USER None 570 Jun  3 16:37 curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key.pub

# file: curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key.pub
# owner: $USER
# group: None
user::rw-
group::r--
other::r--

curl-8.1.2-1.x86_64/build/tests/log/server/curl_client_key.pub $HOSTNAME/$USER:(R,W,D,WDAC,WO)
                                                               $HOSTNAME/None:(R)
                                                               Everyone:(R)

Successfully processed 1 files; Failed processing 0 files
```

**Comment by BrianInglis** [comment]
>> That patch is missing
> Does it make the test run fine when applied?
It eliminates that `@@@...` complaint, and makes the output more explicit, such that it appears obvious that the tests are getting confused between *Cygwin* and *Windows*, looks like they are trying to run *Windows* sshd with *Cygwin* sshd config:
[curl-8.1.2-1-check.log](https://github.com/curl/curl/files/11670877/curl-8.1.2-1-check.log)
where `curl_sshd_config` matches `/usr/sbin/sshd -V` (below):
```
# This is a generated file.  Do not edit.
# OpenSSH 9.3.0 sshd configuration file for curl testing
...
```
but messages show a *Windows* path to `curl_sshd_config`, with unrecognized options, ending with '\r' EoLs
`C:/.../src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/log/server/curl_sshd_config line 7: Deprecated option AuthorizedKeysFile2^M`
 and the path to the keys is wrong for the *Cygwin* build 
`Unable to load host key: $HOME/src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/curl_host_rsa_key`
whereas the config and keys are in `.../src/cygwin/curl/curl-8.1.2-1.x86_64/build/tests/log/server/`
FYI
```
$ /usr/sbin/sshd -V
OpenSSH_9.3, OpenSSL 1.1.1t  7 Feb 2023
$ `cygpath -S`/OpenSSH/sshd -V
unknown option -- V
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]
```


> > but should be irrelevant on Cygwin
> Feel free to propose a change that removes the use of it.
```
elsif (pathhelp::os_is_win()) {
    # Ensure to use MinGW/Cygwin^W paths
```
Fix perl `pathhelp::os_is_win()` so it always returns *false* for *Cygwin* like everything else, perhaps only use *Windows* paths if the *host* and *target* are *Windows* or *Mingw*, as *Cygwin* and *Fedora* cross-compile for *Mingw*, so should use *host* `sshd` with *Unix* paths.

**Comment by vszakats** [comment]
Can confirm that LF line-endings in keys and configs are necessary to make sshd happy on all platforms.

Did the snippet with `icacls` commands work when run from a Cygwin shell? Did they solve the permission problem?

**Comment by BrianInglis** [comment]
@vszakats [see above](https://github.com/curl/curl/issues/11244#issuecomment-1579551098)
Never need to use `icacls` under *Cygwin* as it emulates ACLs with `setfacl`/`getfacl` and package build processes always reset perms, attributes, and other *Windows* stuff, so the users and maintainers can ignore most of *Windows*.

**Comment by BrianInglis** [comment]
Hacking `pathhelp.pm` to force *Cygwin* not to be treated like *Windows* and `cygpath` not to be used:
[curl-8.1.2-test-pathhelp-pm-Cygwin-not-Win.patch](https://github.com/curl/curl/files/11672190/curl-8.1.2-test-pathhelp-pm-Cygwin-not-Win.patch)
```diff
--- origsrc/tests/pathhelp.pm	2023-05-15 04:55:59.000000000 -0600
+++ src/tests/pathhelp.pm	2023-06-06 20:58:26.638964400 -0600
@@ -77,8 +77,8 @@ BEGIN {
 {
     # Cached static variable, Perl 5.0-compatible.
     my $is_win = $^O eq 'MSWin32'
-              || $^O eq 'cygwin'
               || $^O eq 'msys';
+#             || $^O eq 'cygwin'
 
     # Returns boolean true if OS is any form of Windows.
     sub os_is_win {
@@ -96,7 +96,7 @@ BEGIN {
     }
 }
 
-my $use_cygpath;     # Only for Win32:
+my $use_cygpath = 0; # Only for Win32:
                      #  undef - autodetect
                      #      0 - do not use cygpath
                      #      1 - use cygpath
```
yields the following more detailed, lightly trimmed, and sanitized log:
[curl-8.1.2-check.log](https://github.com/curl/curl/files/11672200/curl-8.1.2-check.log)
which showed *NO* *Windows* paths, although all the detailed test log output lines between `test 0581 OK...` and `test 0584 OK...` had annoying `\r`/`^M` EoLs which have been stripped!

**Comment by vszakats** [comment]
`icacls` is the more universal solution (covering both Cygwin and non-Cygwin on Windows on top of a Windows FS), _if_ it works as expected when called from Cygwin. That's why it'd be useful to test that.

**Comment by BrianInglis** [comment]
The issue is that `icacls` and other *Windows* ACL interfaces do not easily support the *POSIX* ACL and permissions semantics that *Cygwin* enforces, and some *Windows* ACL interfaces (like *Explorer*) do not like the ("non-standard") ACL order *Cygwin* uses to achieve that, and as usual when trying to *fix* something it does not support, reorders the ACEs in the ACLs with devastating effects. 
It is quite easy under *Cygwin* to create files and directory trees that are inaccessible from *Windows* programs, even when those are using *elevated admin* privileges, as that is kind of the point of ACLs, blocking *System* and *Admin* users from even seeing what they should not know exists, requiring use of `setfacl` to restore "normal" *Windows* ACLs and DACLs for user and program access.  
*Windows* backup programs do not do what is required, so *Cygwin* `rsync` is often required when tree clones are more complex than `cp` can handle, like retaining *stIcky* bit user permissions under `/run/, `/tmp/`, and '/var/` directory trees:
```
$ lsp /run/ /tmp/ /var/
drwxrwxrwt 1 $USER None 0 Jun  6 23:22 /run/

# file: /run/
# owner: $USER
# group: None
# flags: --t
user::rwx
group::rwx
other::rwx
default:user::rwx
default:group::rwx
default:other::rwx

C:/.../cygwin64/run/ NULL SID:(DENY)(Rc,S,RD)
                           $HOSTNAME/$USER:(F)
                           $HOSTNAME/None:(RX,W)
                           Everyone:(RX,W)
                           CREATOR OWNER:(OI)(CI)(IO)(F)
                           CREATOR GROUP:(OI)(CI)(IO)(RX,W)
                           Everyone:(OI)(CI)(IO)(RX,W)

Successfully processed 1 files; Failed processing 0 files

drwxrwxrwt 1 $USER None 0 Jun  7 08:22 /tmp/

# file: /tmp/
# owner: $USER
# group: None
# flags: --t
user::rwx
group::rwx
other::rwx
default:user::rwx
default:group::rwx
default:other::rwx

C:/.../cygwin64/tmp/ NULL SID:(DENY)(Rc,S,RD)
                           $HOSTNAME/$USER:(F)
                           $HOSTNAME/None:(RX,W)
                           Everyone:(RX,W)
                           CREATOR OWNER:(OI)(CI)(IO)(F)
                           CREATOR GROUP:(OI)(CI)(IO)(RX,W)
                           Everyone:(OI)(CI)(IO)(RX,W)

Successfully processed 1 files; Failed processing 0 files

drwxr-xr-t 1 $USER Administrators 0 Jun  6 23:25 /var/

# file: /var/
# owner: $USER
# group: Administrators
# flags: --t
user::rwx
group::r-x
other::r-x
default:user::rwx
default:group::rwx
default:other::rwx

C:/.../cygwin64/var/ NULL SID:(DENY)(Rc,S,RD)
                           $HOSTNAME/$USER:(F)
                           BUILTIN/Administrators:(RX)
                           Everyone:(RX)
                           CREATOR OWNER:(OI)(CI)(IO)(F)
                           CREATOR GROUP:(OI)(CI)(IO)(RX,W)
                           Everyone:(OI)(CI)(IO)(RX,W)

Successfully processed 1 files; Failed processing 0 files
```

**Comment by jay** [comment]
@BrianInglis can you submit a PR with your proposed changes to fix this issue, then we'll see all the CI results

**Comment by jay** [comment]
Is there anyone familiar with cygwin that can take a look at this?

**Comment by BrianInglis** [comment]
Anyone familiar with `curl` testing, `Perl`, cross-build issues, and things like cross-building *Mingw* under *Fedora*, which works the same under *Cygwin*. 
*Cygwin* also bases package builds on *Fedora* specs converted to `cygport` scripts. 
*Cygwin* can also be cross-built under *Fedora*, as they are both *RedHat* originated projects, and the leads are still *RedHat* volunteers, who still mostly ssem to use *Fedora* for working, and *Cygwin* for just for testing.
