### ISSUE TITLE
curl consumes 100% CPU when sending a file with -F

### ISSUE THREAD

**Issue by l29ah** [curl/curl#11242]
### I did this
`curl -Ffile=@"VID_20230603_010956.mp4" https://0x0.st`

### I expected the following
Tiny CPU consumption appropriate for the pathetic ~200kB/s transfer speed on my i7 CPU.

### curl/libcurl version
```
curl 8.1.2 (x86_64-pc-linux-gnu) libcurl/8.1.2 GnuTLS/3.8.0 (OpenSSL/1.1.1u) zlib/1.2.13 c-ares/1.19.1 libidn2/2.3.4 nghttp2/1.52.0 librtmp/2.3
Release-Date: 2023-05-30
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtmp rtsp smtp smtps tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz MultiSSL NTLM SSL threadsafe TLS-SRP UnixSockets
```

### operating system
Gentoo Lignux
`Linux l29ah-x201 6.2.5+ #238 SMP PREEMPT_DYNAMIC Mon Mar 13 02:40:28 CET 2023 x86_64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz GenuineIntel GNU/Linux`

### top of perf report
```
# Children      Self  Command  Shared Object          Symbol                                          
# ........  ........  .......  .....................  ................................................
#
    27.96%     0.00%  curl     [unknown]              [.] 0x0000000000020003
            |
            ---0x20003
               |          
               |--4.68%--pthread_mutex_lock@@GLIBC_2.2.5
               |          
               |--3.98%--_gnutls_io_write_flush
               |          
               |--3.81%--_gnutls_record_overhead
               |          
               |--3.61%--_gnutls_epoch_get
               |          
               |--3.18%--record_overhead_rt
               |          
               |--2.50%--__GI___pthread_mutex_unlock_usercnt
               |          
               |--1.47%--gnutls_system_mutex_lock
               |          
               |--1.35%--_mbuffer_head_get_first
               |          
               |--1.06%--gnutls_system_mutex_unlock
               |          
                --0.91%--_gnutls_writev_emu.constprop.0

    12.93%     5.91%  curl     libc.so.6              [.] __send
            |          
            |--7.02%--__send
            |          
            |--0.60%--0x3c668934bc4645c5
            |          0x6a8
            |          |          
            |           --0.60%--__send
            |          
            |--0.53%--0x83df1832731fb4aa
            |          0x3e52
            |          |          
            |           --0.52%--__send
            |          
             --0.50%--0x7734ab5ea3b468f0
                       0x35ac
                       |          
                        --0.50%--__send

    10.99%     0.00%  curl     [unknown]              [.] 0000000000000000
            |
            ---0
               |          
                --10.99%--0x5575fc882990
                          |          
                          |--5.02%--nghttp2_session_send
                          |          
                          |--1.86%--send_callback
                          |          
                          |--1.15%--nghttp2_session_mem_send_internal
                          |          
                          |--1.14%--Curl_bufq_write_pass
                          |          
                          |--1.07%--nghttp2_session_adjust_idle_stream
                          |          
                           --0.58%--nghttp2_is_fatal
```

**Comment by bagder** [comment]
Does this by any chance use HTTP/2 when uploading? (if you add `-v` you'll see it mentioned)

**Comment by bagder** [comment]
@icing when you have a minute over, can you have a look at this?

**Comment by icing** [comment]
@l29ah would you be able to try #11247 in your setup? I made the code that sends the http2 data up more robust in handling EAGAIN situations.

**Comment by l29ah** [comment]
On Sun, Jun 04, 2023 at 03:46:30AM -0700, Stefan Eissing wrote:
> @l29ah would you be able to try #11247 in your setup? I made the code that sends the http2 data up more robust in handling EAGAIN situations.

Tried slapping it on top of 8.1.2, still 100% CPU.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by icing** [comment]
Could you make a build with `--enable-debug` for testing and run curl with

```
CURL_DEBUG=http/2 curl -v [your args]
```

Thank you!

**Comment by bagder** [comment]
I cannot reproduce. I tried sending a fairly large file to that same server using this curl version:
~~~
curl 8.2.0-DEV (x86_64-pc-linux-gnu) libcurl/8.2.0-DEV GnuTLS/3.7.9 zlib/1.2.13
brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3)
nghttp2/1.54.0 librtmp/2.3 libgsasl/2.2.0

**Comment by l29ah** [comment]
> CURL_DEBUG=http/2

https://tinystash.undef.im/il/2EQtfhvYcr9r9SPd1TkCyqudqFDNKSc9yaCHNAw9t4gsEdd9gKLaQUKAt2pBMiTgKow7kDcA2DhETsB8Q2ggAWsw

**Comment by icing** [comment]
In the log I see that the upload is progressing. So we have no stall or busy loop here, "just" the action of chunking your upload file into the 16KB frame data of the HTTP/2 protocol, encrypting those and passing them to the network.

I, so far, see nothing wrong, except that the implementation is not as efficient as you would like it to be.

**Comment by l29ah** [comment]
Downgraded curl to 8.0.1, now it consumes <1% CPU on the same scenario.

**Comment by icing** [comment]
Reproduced. You convinced me that this does not look right. Analyzing what I did here...

**Comment by icing** [comment]
Ok, if your find the time, you could give #11330 a try on your setup. This is a fix for the CPU and for stalled uploads that I observed here. Likelihood of those depend on network conditions. We are discussing how best to resolve that one.

But it would be good to know if this PR makes the upload work flawlessly for you.
