### ISSUE TITLE
Native Windows can't create UNIX sockets

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11258]
Many CI builds on Windows show warnings like this during CI runs, such as this one from the Appveyor *CMake, mingw-w64, Debug x86, Schannel, Static* build:
```
RUN: failed to start the HTTP-unix server
== Contents of files in the log/ dir after test 1435
=== Start of file http_unix_server.log
 06:39:33.828000 Error creating socket: (10047) Unknown error
 06:39:33.828000 ========> sws quits
=== End of file http_unix_server.log
test 1435 SKIPPED: failed starting HTTP-unix server
```
However, msys2 builds on Appveyor like *autotools, msys2, Debug, no SSL* run the test fine (I don't know if this is because msys2 does some kind of emulation for unix sockets that doesn't happen in native builds).  Cirrus msys2 builds like *Windows 64-bit shared/release Schannel/SSPI/WinIDN/libssh2* also show the failure. The failures have been happening for at least a couple of months on Appveyor. I don't know if those non-msys2 builds have ever worked.

Because the test server works around it by skipping the tests, it could have easily stopped working at some point without it being noticed.

According to this [MS blog post](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) Windows has supported `AF_UNIX` for more than 4 years, so I would expect this to be working on all Windows builds these days, assuming the CI services are using a modern-enough Windows.

**Comment by gvanem** [comment]
>  `06:39:33.828000 Error creating socket: (10047) Unknown error`

This is `WSAEAFNOSUPPORT`. Trying the same test myself, I get `10045 ==  WSAEOPNOTSUPP`:
```
RUN: failed to start the HTTP-unix server
== Contents of files in the log/ dir after test 1435
=== Start of file http_unix_server.log
 08:37:34.296000 Error binding socket: (10045) Unknown error
 08:37:34.296000 ========> sws quits
=== End of file http_unix_server.log
TESTDONE: 1 tests were considered during 5 seconds.
```

But I see `server/util.c` tests on `errno` where it in some places should be `SOCKERRNO`. Related?

**Comment by dfandrich** [comment]
I noticed that many servers were using the strerror() on socket errors, resulting in wrong/useless messages, so I've fixed those here as well.

**Comment by gvanem** [comment]
Both `logmsg()` + `perror()` seems overkill. The syslog `%m` format comes to mind. 
Couldn't `logmsg()` do similar?
Ref: https://www.oreilly.com/library/view/linux-security-cookbook/0596003919/ch09s33.html

**Comment by dfandrich** [comment]
Doing something better seemed like overkill to me :-)  logmsg just passes in
the parameters to mvsnprintf() so doing some special argument passing means
writing a new sprintf-like parsing function which seems like way too much
bother for test code. I could take win32_perror() and split off the
strerror-like code into a new function and use that in place of strerror() in
the original code.  That would bring the log messages back to a single function
call.

**Comment by dfandrich** [comment]
I just noticed that logmsg doesn't write to stderr by default, so I've gone with that alternative approach and created a strerror() replacement instead.

**Comment by dfandrich** [comment]
The latest commit now shows this message:
```RUN: failed to start the HTTP-unix server
  == Contents of files in the log/ dir after test 1435
  === Start of file http_unix_server.log
   05:05:28.109000 Error binding socket on path C:/msys64/tmp/curl-http-E2dVG0SO: (10045) The attempted operation is not supported for the type of object referenced.
   05:05:28.109000 ========> sws quits
  === End of file http_unix_server.log
  test 1435 SKIPPED: failed starting HTTP-unix server
```
I still don't know the root cause, but the error message seems at least more helpful now.

**Comment by gvanem** [comment]
> but the error message seems at least more helpful now.

Indeed it does.

**Comment by bagder** [comment]
I'm not sure it is worth fixing in a more elegant way? This problem makes the server fail so the test gets skipped. Sure, it would be nicer without the error message but until someone figures that out I think leaving it like this is not super bad.

**Comment by bagder** [comment]
We can leave this. It's not a big deal but *could* be fixed better at a later time.

**Comment by dfandrich** [comment]
It's probably worth adding to KNOWN_BUGS then.
