### ISSUE TITLE
Curl 8.1.2 arm64 container image is broken

### ISSUE THREAD

**Issue by dany74q** [curl/curl#11257]
### I did this
```
docker run -it --platform linux/arm64 curlimages/curl:8.1.2
docker: Error response from daemon: unable to find user curl_user: no matching entries in passwd file.
```

### I expected the following
`curl: try 'curl --help' or 'curl --manual' for more information`

### curl/libcurl version
`8.1.2`

Note: the amd64 image works great

**Comment by xquery** [comment]
already raised here

https://github.com/curl/curl-container/issues/3
