### ISSUE TITLE
curl does not compile with openssl path and no pkg-config installed

### ISSUE THREAD

**Issue by Rjinswand** [curl/curl#1128]
I've tried to compile curl that is linked to a specific version of openssl (1.0.2j) that is different to the version installed on the system.

I've called:
./configure --without-librtmp --without-libssh2 --with-ssl=/path/to/openssl --prefix=/somewhere --disable-ldap --disable-rtsp --without-winidn --without-libidn --without-ca-bundle --without-ca-path

make leads to this error:
  CCLD     curl
../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_alpn_protos'
../lib/.libs/libcurl.so: undefined reference to `SSL_COMP_free_compression_methods'
../lib/.libs/libcurl.so: undefined reference to `SSL_get0_alpn_selected'
collect2: error: ld returned 1 exit status
Makefile:775: recipe for target 'curl' failed

It seems that the linker tries to link against the version of openssl that is installed on the system:
echo "  CCLD    " curl;/bin/bash ../libtool --silent --tag=CC   --mode=link gcc  -O2 -Wno-system-headers   -L/home/anti/subse/subse/sbs_apps/thirdparty/curl/../openssl/lib -o curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  ../lib/libcurl.la    -lz  

An "-rpath-link" is missing.

Workaround:
Set LD_FLAGS:
LDFLAGS=-Wl,-rpath-link=/path/to/openssl/lib

This problem does not occur, if pkg-config is installed

**Comment by bagder** [comment]
But `-rpath-link` isn't used with pkg-config, is it? It certainly is not when I try my build on Linux on a custom OpenSSL path. To me it rather looks like you don't have the correct -L path, or optionally the ones that are used makes the linker find the older install by mistake. You can get the full compiler command visible with:

    $ rm src/curl
    $ make V=1

**Comment by Rjinswand** [comment]
The -L path is used for directly linked libs. Without pkg-config the openssl libs are not linked directly (-lssl and -lcrypto are missing), they are linked via libcurl. In this case a correct -rpath-link must be set.

With pkg-config the curl binary is linked to the openssl-libs directly:
libtool: link: gcc -O2 -Wno-system-headers -o .libs/curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  -L/usr/lib/x86_64-linux-gnu **-L/home/anti/subse/subse/sbs_apps/thirdparty/openssl/lib** ../lib/.libs/libcurl.so **-lssl -lcrypto** -lz -Wl,-rpath -Wl,/home/anti/subse/subse/sbs_apps/thirdparty/curl/lib

without pkg-config:
libtool: link: gcc -O2 -Wno-system-headers -o .libs/curl curl-slist_wc.o curl-tool_binmode.o curl-tool_bname.o curl-tool_cb_dbg.o curl-tool_cb_hdr.o curl-tool_cb_prg.o curl-tool_cb_rea.o curl-tool_cb_see.o curl-tool_cb_wrt.o curl-tool_cfgable.o curl-tool_convert.o curl-tool_dirhie.o curl-tool_doswin.o curl-tool_easysrc.o curl-tool_formparse.o curl-tool_getparam.o curl-tool_getpass.o curl-tool_help.o curl-tool_helpers.o curl-tool_homedir.o curl-tool_hugehelp.o curl-tool_libinfo.o curl-tool_main.o curl-tool_metalink.o curl-tool_mfiles.o curl-tool_msgs.o curl-tool_operate.o curl-tool_operhlp.o curl-tool_panykey.o curl-tool_paramhlp.o curl-tool_parsecfg.o curl-tool_strdup.o curl-tool_setopt.o curl-tool_sleep.o curl-tool_urlglob.o curl-tool_util.o curl-tool_vms.o curl-tool_writeenv.o curl-tool_writeout.o curl-tool_xattr.o ../lib/curl-strtoofft.o ../lib/curl-nonblock.o ../lib/curl-warnless.o  **-L/home/anti/subse/subse/sbs_apps/thirdparty/curl/../openssl/lib** ../lib/.libs/libcurl.so -lz -Wl,-rpath -Wl,/home/anti/subse/subse/sbs_apps/thirdparty/curl/lib

**Comment by bagder** [comment]
So why do you build openssl without pkg-config? It seems like you intentionally want to make it harder to build with. But sure, I wouldn't mind seeing the configure script handle this better. Feel free to suggest improvements or file pull requests!

**Comment by Brandon-T** [comment]
This issue happens on Raspberry Pi a lot for me.  Issued the command:

`./configure --with-nghttp2=/usr/local --with-ssl=/usr/local/ssl --prefix=/usr/local`

with no other OpenSSL versions installed. You get the same linker error.

I tried: `export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig` and then LD_FLAGS="-Wl,-rpath-link=/usr/local/lib"

Doesn't work. Any ideas?

**Comment by bagder** [comment]
@Brandon-T: it sounds like a different problem. You have only one version installed and you seem to have pkg-config as well. I think that's worth taking separately. And tell how you installed that openssl library.

**Comment by Brandon-T** [comment]
@bagder ;  I built ZLib, OpenSSL and Curl with:

````
sudo apt-get remove openssl
sudo apt-get remove ssl
sudo rm -rf /usr/bin/openssl
sudo rm -rf /usr/bin/ssl
sudo rm -rf /usr/lib/libssl*
sudo rm -rf /usr/include/openssl
sudo rm -rf /usr/lib/pkgconfig/openssl*


cd ~/Desktop/zlib-1.2.10
./configure
sudo make install


cd ~/Desktop/openssl-1.0.2j

perl Configure threads --prefix=/usr/local --openssldir=/usr/local/ssl shared linux-generic32 -DOPENSSL_THREADS
sudo make depend
sudo make install


cd ~/Desktop/nghttp2
sudo apt-get install g++ make binutils autoconf automake autotools-dev libtool pkg-config \
  zlib1g-dev libcunit1-dev libssl-dev libxml2-dev libev-dev libevent-dev libjansson-dev \
  libc-ares-dev libjemalloc-dev cython python3-dev python-setuptools
autoreconf -i
automake
autoconf
./configure --prefix=/usr/local
sudo make install


cd ~/Desktop/curl-7.52.1
export $PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
./configure --with-nghttp2=/usr/local --with-ssl=/usr/local/ssl --prefix=/usr/local
````



This did not work so I did:
````
export $PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
./configure --with-nghttp2 --with-ssl --prefix=/usr/local
````

and it finally worked after trying for hours.

**Comment by Rjinswand** [comment]
If pkg-config adds a directory to the library search path if it has found a configuration of a used library. In my case there's a pkgconfig file for the zlib:

```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.8

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}

```

Since the openssl lib of the system is located in the same directory as the libz and the "-L" for the libz is before the "-L" of the custom openssl lib, the linker takes the openssl lib of the system.

The sequence of the "-L" options are important. Maybe libraries that are found by pkg-config should be included last.

**Comment by bagder** [comment]
So if you just build openssl and install it *with* the pkg-config file (as it does by default) it works, so I don't really feel like working a lot on this edge case. If anyone else does, I'll be happy to reopen.
