### ISSUE TITLE
Private and public key resolving documentation needs improvement for scp and sftp

### ISSUE THREAD

**Issue by atjg** [curl/curl#11287]
### I did this

```
// Make ssh keyfiles work from current working dir
  unsetenv("HOME");
```
I generated keys in working directory of the process of my program and named them id_rsa and id_rsa.pub

I run my executable and it picked up id_rsa as private key, _but it did not pick up id_rsa.pub_. This leads to a try to extract public key from private key. Since curl is compiled against gnutls (where gcrypt does not support public key extraction from private key) the program was not able to authenticate an sftp connection. The generated keypair is proven to work on other platforms.

As solution I made my program work by explicitly setting private and public key locations:

```
#define SETOPT(opt, value)                         \
  if (curl_easy_setopt(c, CURLOPT_##opt, value)) { \
    LOG(LOG_ERR, "curl setopt " #opt " failed");   \
    goto error_cleanup;                            \
  }
  SETOPT(SSH_PRIVATE_KEYFILE, privkey);
  SETOPT(SSH_PUBLIC_KEYFILE, pubkey);
```

Related problem:
When I try the curl executable with-v -k -u=<user>: --key <privkey> --pubkey <pubkey> the result is basically the same (authentication fails), even if it seems the -v does not give verbose output on this platform so I am not 100% sure it's the same problem.

### I expected the following
According to documentation here:
https://curl.se/libcurl/c/CURLOPT_SSH_PUBLIC_KEYFILE.html
and here:
https://curl.se/libcurl/c/CURLOPT_SSH_PRIVATE_KEYFILE.html

only id_dsa and id_dsa.pub file names are supported according to documentation. This is not correct. id_rsa was picked up and because of this I expect also id_rsa.pub to be picked up as public key.

Versions.
Curl:
root@SpeedwayR-11-7A-BC:/cust# uname -a
Linux SpeedwayR-11-7A-BC 5.4.70 #1 PREEMPT Fri Jul 9 17:06:25 UTC 2021 armv5tejl GNU/Linux

root@SpeedwayR-11-7A-BC:/cust# curl -V
curl 7.72.0 (arm-buildroot-linux-gnueabi) libcurl/7.72.0 OpenSSL/1.1.1k zlib/1.2.11 libssh2/1.9.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets

sftp, scp

Libcurl:
SSH2VER=1.10.0
CURLVER=7.86.0
export PREFIX=/opt/codesourcery/arm-none-linux-gnueabi/libc/usr
...
cd curl-$CURLVER
#./configure --host $HOST --prefix=$PREFIX --enable-ipv6 --with-nghttp2=$PREFIX
./configure --host $HOST --prefix=$PREFIX --with-gnutls=$PREFIX --enable-ipv6 --with-nghttp2=$PREFIX --with-libssh2 --with-libidn2
nice make -j8 || exit 1
make install || exit 1
cd ..

**Comment by bagder** [comment]
You are right on `CURLOPT_SSH_PRIVATE_KEYFILE` but not for `CURLOPT_SSH_PUBLIC_KEYFILE`, which has no default file names at all. I made #11289 to correct the omission.

**Comment by bagder** [comment]
So this was just an issue about the omission in the man page? Can we then consider it addressed?

**Comment by atjg** [comment]
Yes, I think so.

**Comment by bagder** [comment]
Thanks
