### ISSUE TITLE
Problems with sftp using curl.

### ISSUE THREAD

**Issue by Q-coder** [curl/curl#11280]
The issue is a sftp transfer that writes an empty file on the target system. But with RHEL sftp shell command the same transfer works ok.

curl -k -T myFile.txt --key xxxmyKeyfile -u xxxUser sftp://xxxServer:2222

myFile is created on the target system but empty. No errors are returned from Proftpd.

sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile=xxxKeyfile xxxUser@xxxServer
put myFile.txt
quit

myFile.txt is put completely to the target system with the correct size.

What could be the cause of these issues ?
Curl is curl 7.61.1
lftp is LFTP | Version 4.8.4
It's running on RHEL 8.7

The target system runs CentOS 6.5 (I know it's out of support)
with ProFTPD Version 1.3.3g

**Comment by dfandrich** [comment]
> Curl is curl 7.61.1

This version is ancient history and likely highly patched by Red Hat. Does it
reproduce on a pristine recent version?

**Comment by bagder** [comment]
Also note that libssh2 (used for the underlying SSH connection) has been improved over the same time frame and would also help to upgrade.

**Comment by bagder** [comment]
The tool "sftp" comes from the OpenSSH project and shares *no* code with libssh2 or curl. libssh2 is a separate SSH implementation. The sftp tool does not use libssh2.

**Comment by bagder** [comment]
Assumed to work in modern versions.
