### ISSUE TITLE
Unable to build curl with ngtcp2 v0.15.0

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#11292]
I am trying to build curl with ngtcp2 and nghttp3

ngtcp2 version is  v0.15.0
nghttp3 is  v0.11.0
curl is latest 

Followed steps from below

https://github.com/curl/curl/blob/master/docs/HTTP3.md#build-with-openssl

 curl -V
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

 cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu

Linux ubuntu 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Error:-
=====
  CC       vquic/libcurl_la-curl_ngtcp2.lo
vquic/curl_ngtcp2.c: In function ‘quic_settings’:
vquic/curl_ngtcp2.c:353:6: error: ‘ngtcp2_settings’ has no member named ‘qlog_write’
  353 |     s->qlog_write = qlog_callback;
      |      ^~
vquic/curl_ngtcp2.c: At top level:
vquic/curl_ngtcp2.c:928:47: error: unknown type name ‘ngtcp2_encryption_level’; did you mean ‘ngtcp2_crypto_level’?
  928 | static int cb_recv_rx_key(ngtcp2_conn *tconn, ngtcp2_encryption_level level,
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~
      |                                               ngtcp2_crypto_level
vquic/curl_ngtcp2.c:983:3: error: ‘cb_recv_rx_key’ undeclared here (not in a function)
  983 |   cb_recv_rx_key,
      |   ^~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: In function ‘cb_h3_stop_sending’:
vquic/curl_ngtcp2.c:1233:8: error: too many arguments to function ‘ngtcp2_conn_shutdown_stream_read’
 1233 |   rv = ngtcp2_conn_shutdown_stream_read(ctx->qconn, 0, stream_id,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from vquic/curl_ngtcp2.c:28:
/var/local/ngtcp2/include/ngtcp2/ngtcp2.h:4374:19: note: declared here
 4374 | NGTCP2_EXTERN int ngtcp2_conn_shutdown_stream_read(ngtcp2_conn *conn,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: In function ‘cb_h3_reset_stream’:
vquic/curl_ngtcp2.c:1252:8: error: too many arguments to function ‘ngtcp2_conn_shutdown_stream_write’
 1252 |   rv = ngtcp2_conn_shutdown_stream_write(ctx->qconn, 0, stream_id,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from vquic/curl_ngtcp2.c:28:
/var/local/ngtcp2/include/ngtcp2/ngtcp2.h:4353:19: note: declared here
 4353 | NGTCP2_EXTERN int ngtcp2_conn_shutdown_stream_write(ngtcp2_conn *conn,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: At top level:
vquic/curl_ngtcp2.c:1277:3: warning: excess elements in struct initializer
 1277 |   NULL /* recv_settings */
      |   ^~~~
vquic/curl_ngtcp2.c:1277:3: note: (near initialization for ‘ngh3_callbacks’)
vquic/curl_ngtcp2.c: In function ‘cf_ngtcp2_connect’:
vquic/curl_ngtcp2.c:2429:6: error: implicit declaration of function ‘ngtcp2_conn_in_draining_period’; did you mean ‘ngtcp2_conn_is_in_draining_period’? [-Werror=implicit-function-declaration]
 2429 |      ngtcp2_conn_in_draining_period(ctx->qconn)) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      ngtcp2_conn_is_in_draining_period
cc1: some warnings being treated as errors
make[2]: *** [Makefile:3271: vquic/libcurl_la-curl_ngtcp2.lo] Error 1
make[2]: Leaving directory '/src/curl/lib'
make[1]: *** [Makefile:1508: all] Error 2
make[1]: Leaving directory '/src/curl/lib'
make: *** [Makefile:1267: all-recursive] Error 1
root@ubuntu:/src/curl#

ngtcp2 version:-
==========
git log
commit 0ad3c389d48517ac61301ca5c3d63bb295cee0ac (grafted, HEAD, tag: v0.15.0)
Author: Tatsuhiro Tsujikawa <tatsuhiro.t@gmail.com>
Date:   Wed Apr 26 18:26:30 2023 +0900

    Bump package and library versions
root@ubuntu:/src/ngtcp2#

nghttp3 version:-
==========

commit a0c9efde739193697c1ad432dde0461c5230be49 (HEAD, tag: v0.11.0)
Author: Tatsuhiro Tsujikawa <tatsuhiro.t@gmail.com>
Date:   Wed Apr 26 18:15:06 2023 +0900

    Bump package and library versions

curl version:-
========

commit 9e75932358fa24b8a49b7b13202e866d6e395a79 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Stenberg <daniel@haxx.se>
Date:   Fri Jun 9 19:10:30 2023 +0200

    CURLOPT_SSH_PRIVATE_KEYFILE.3: expand on the file search

    Reported-by: atjg on github
    Ref: #11287
    Closes #11289

**Comment by dfandrich** [comment]
HTTP/3 is still experimental in curl, so we only support the latest versions of ngtcp2 and nghttp3. Right now, that is versions 0.16.0 and 0.12.0, respectively. See #11184.

**Comment by Karthikdasari0423** [comment]
@dfandrich Thank you for updating
