### ISSUE TITLE
SMTP always uses VRFY (regression in 8.1)

### ISSUE THREAD

**Issue by netfenceventu** [curl/curl#11298]
Hello.

I'm using libcurl to send emails via SMTP.
In order *not* to use the VRFY command, option CURLOPT_UPLOAD must be set to 1.
However, since version 8.1.0 this option has no effect, and VRFY is always used.

I think what broke this is
commit 7815647d6582c0a4900be2e1de6c5e61272c496b
Author: Daniel Stenberg <daniel@haxx.se>
Date:   Tue Apr 25 08:28:01 2023 +0200

    lib: unify the upload/method handling
    
    By making sure we set state.upload based on the set.method value and not
    independently as set.upload, we reduce confusion and mixup risks, both
    internally and externally.
    
    Closes #11017

**Comment by bagder** [comment]
please tell us more. Like for example how to use curl when this happens.

**Comment by netfenceventu** [comment]
> please tell us more. Like for example how you use curl when this happens.

I'd gladly post the code I'm using, but I've tried to reduce it and it's not trivial due to several nested classes.

In any case it was originally derived from this example (and a few similar ones):
https://curl.se/libcurl/c/smtp-mail.html

One thing that differs is that the example uses:
    curl_easy_setopt(curl, CURLOPT_READFUNCTION, payload_source);
    curl_easy_setopt(curl, CURLOPT_READDATA, &upload_ctx);
while my code uses
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS,payload_text);

This used to work with 8.0, but now blocks with 8. 1 (when, I don't know how, I get to avoid VRFY).
So, for a start, is this expected to work as before?
Or did it work by chance and use of CURLOPT_READFUNCTION is the only supported way?

(I know this was not my original topic, but I'm having a hard time trying to get consistent results, so I'd like to get this out of the way in the meantime).

**Comment by bagder** [comment]
Aha. Using `CURLOPT_POSTFIELDS` for this is certainly creative, as I don't think we ever intended that to work. It also does not seem to be documented to work.

Right now I'm a little indecisive if this is actually something we should support or if we should just say: use the read callback for smtp.

I'm not sure it works (reliably) even with older versions. I built this code with a 8.1.0 and it does not work for me. Can you figure out what difference you did that made it work for you on that version?

~~~c
static const char *email =
  "From: different\r"
  "To: another\r"
  "\r"
  "body\r";

int test(char *URL)
{
  CURLcode ret;
  CURL *hnd;
  struct curl_slist *slist1;

  slist1 = NULL;
  slist1 = curl_slist_append(slist1, "recipient@example.com");

  hnd = curl_easy_init();
  curl_easy_setopt(hnd, CURLOPT_URL, URL);
  curl_easy_setopt(hnd, CURLOPT_POSTFIELDS, email);
  curl_easy_setopt(hnd, CURLOPT_VERBOSE, 1L);
  curl_easy_setopt(hnd, CURLOPT_MAIL_FROM, "sender@example.com");
  curl_easy_setopt(hnd, CURLOPT_MAIL_RCPT, slist1);

  ret = curl_easy_perform(hnd);

  curl_easy_cleanup(hnd);
  curl_slist_free_all(slist1);
  return (int)ret;
}

**Comment by netfenceventu** [comment]
> Aha. Using `CURLOPT_POSTFIELDS` for this is certainly creative, as I don't think we ever intended that to work. It also does not seem to be documented to work.

OK.
I'll change the code to use callback.
Then I'll see if VRFY still gets in the way and I'll report back.
It might take a while, as I'm about to leave for a few weeks.



> I built this code with a 8.1.0 and it does not work for me. Can you figure out what difference you did that made it work for you on that version?

No: it does NOT work with 8.1.x.
It did in previous versions (up to 8.0.1).


Thanks.

**Comment by olifes-c** [comment]
@FooBarWidget

**Comment by bagder** [comment]
I can't my test above work with 7.88.1 either.

**Comment by bagder** [comment]
This issue is based on undocumented (and unintended) functionality. If you cannot reproduce a bug with the callback, this is not actually a bug. postfields was never intended nor documented to work for smtp.
