### ISSUE TITLE
Test 1700 (HTTP/2 upgrade and reuse) fails rarely

### ISSUE THREAD

**Issue by jay** [curl/curl#1129]
Since changing the HTTP/2 window size and fixing a related test failure I ran the HTTP/2 tests repeatedly to see what would shake out and I've noticed that test 1700 rarely fails (1 in 100-300). It happens regardless of the window size (I tested both before and after the window size was changed).

[Test 1700](https://github.com/curl/curl/blob/master/tests/data/test1700) tests the scenario where one HTTP transfer is upgraded to HTTP/2 and then another HTTP transfer is supposed to go over that same upgraded HTTP/2 connection. In the fail case the connection is apparently dead so libcurl makes a new one, resulting in a second upgrade:
~~~diff
--- log/check-expected	2016-11-17 02:01:15.236590560 -0500
+++ log/check-generated	2016-11-17 02:01:15.236590560 -0500
@@ -14,6 +14,10 @@
 via: 1.1 nghttpx[CR][LF]
 [CR][LF]
 -foo-[LF]
+HTTP/1.1 101 Switching Protocols[CR][LF]
+Connection: Upgrade[CR][LF]
+Upgrade: h2c[CR][LF]
+[CR][LF]
 HTTP/2 200 [CR][LF]
 date: Thu, 09 Nov 2010 14:49:00 GMT[CR][LF]
 content-length: 6[CR][LF]
~~~
In the http_v2_server log I can see the connection is apparently deleted before libcurl reconnects, but I don't know if it's the server responding to a problem with the client or why it happens. Normally I think it should not happen.
~~~
17/Nov/2016:00:15:27 -0500 PID77233 [INFO] shrpx_client_handler.cc:480 [CLIENT_HANDLER:0x7fceadcfd000] Deleting
17/Nov/2016:00:15:27 -0500 PID77233 [INFO] shrpx_client_handler.cc:503 [CLIENT_HANDLER:0x7fceadcfd000] Deleted
17/Nov/2016:00:15:27 -0500 PID77233 [INFO] shrpx_connection_handler.cc:363 [LISTEN:0x7ffe6140fc30] Accepted connection from 127.0.0.1, fd=10
~~~
One thing I notice in the trace different between a good and bad run is the good run has this for the first transfer after the headers are received but before the second transfer:
~~~
00:53:55.350775 == Info: nread=9
00:53:55.350796 == Info: Got SETTINGS
00:53:55.350806 == Info: MAX_CONCURRENT_STREAMS == 100
00:53:55.350814 == Info: ENABLE_PUSH == TRUE
00:53:55.350822 == Info: nghttp2_session_mem_recv() returns 9
00:53:55.350830 == Info: All data in connection buffer processed
~~~
To run test1700 in a loop until it fails I'm using this script:
~~~shell
#!/bin/bash

COUNTER=0

while true; do
  echo COUNTER: $COUNTER
  ./runtests.pl -p 1700 || exit
  let COUNTER=COUNTER+1
done
~~~
Can anyone reproduce?
~~~
curl 7.52.0-DEV (x86_64-pc-linux-gnu) libcurl/7.52.0-DEV OpenSSL/1.0.2j zlib/1.2.8 nghttp2/1.16.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

Linux ubuntu1604-x64-vm 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
~~~

/cc @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
I'm running the above script, hoping that it reproduces this issue.  Wait & see...

**Comment by tatsuhiro-t** [comment]
@jay Do you have complete nghttpx log when this issue occurred?

**Comment by jay** [comment]
I have a http2_v2_server log if that's what you mean? I've attached the log dir from a good run and one from a bad run to this post.
[log.1700.good.and.bad.zip](https://github.com/curl/curl/files/598311/log.1700.good.and.bad.zip)
If there's anything I can do to get more information on this please let me know.

**Comment by bagder** [comment]
I get an intermittent problem with 1702 that I now wonder if it could be related or not. Have you guys tried to run test 1702 repeatedly? Here's my output when it fails (just ran it on git master, curl-7_51_0-64-g0b8d682):
~~~
test 1702...[HTTP/2 HEAD with Upgrade:]
sp----emv- OK (3   out of 7  , remaining: 00:09)
test 1702...[HTTP/2 HEAD with Upgrade:]
sp----emv- OK (4   out of 7  , remaining: 00:06)
test 1702...[HTTP/2 HEAD with Upgrade:]

 1702: stdout FAILED:
--- log/check-expected  2016-11-17 23:03:04.601239185 +0100
+++ log/check-generated 2016-11-17 23:03:04.601239185 +0100
@@ -8,6 +8,8 @@
 etag: "21025-dc7-39462498"[CR][LF]
 accept-ranges: bytes[CR][LF]
 content-length: 6[CR][LF]
+conne: [CR][LF]
+ction: close[CR][LF]
 content-type: text/html[CR][LF]
 funny-head: yesyes[CR][LF]
 server: cut-out[CR][LF]

 - abort tests
TESTDONE: 4 tests out of 5 reported OK: 80%
TESTFAIL: These test cases failed: 1702

**Comment by tatsuhiro-t** [comment]
Thank you for the log.

> One thing I notice in the trace different between a good and bad run is the good run has this for the first transfer after the headers are received but before the second transfer:

I think the second "Got SETTINGS" log is SETTINGS frame with ACK from server.  This is HTTP Upgrade, so SETTINGS ACK may be receive after the response header.
It seems that curl doesn't read socket after it satisfied with the active stream.  Depending on the packet alignment, SETTINGS ACK may be in the same packet with response header and body, or it is in the packet following the packet which includes response header and body.  curl can handle the former case well.  But not the latter.  In the latter case, we have data in the packet ready to be read.
curl uses SocketIsDead function to determine whether socket is closed or not.  It just check whether socket is readable or not.  In HTTP/1, this is fine, since all we can expect for dead socket is 0 byte read.  But for HTTP/2, we may have pending data in the socket, in our case, SETTINGS frame with ACK.  That makes curl think that connection is dead, and create another connection.

**Comment by jay** [comment]
Thanks for that explanation. This brings up an interesting point, should we mark/purge connections as dead and "disconnect" if they have pending data? Also, wouldn't that also hold true of SSL? Maybe purging should not be done at all with http2. Like [data_pending](https://github.com/curl/curl/blob/curl-7_51_0/lib/transfer.c#L306-L314). However then you would have connections that could possibly never be purged.

Further though not related to http2 but on this same pending data topic I don't know what we'd expect a user of [CURLOPT_CONNECT_ONLY](https://curl.haxx.se/libcurl/c/CURLOPT_CONNECT_ONLY.html) to do, they would call select (see [sendrecv](https://github.com/curl/curl/blob/curl-7_51_0/docs/examples/sendrecv.c) for example) but if data is already cached by libcurl or the SSL library how do they know? It would seem the only right way would be just keep reading until eagain, which I guess people are probably already doing?

**Comment by bagder** [comment]
I rather consider this case a sibling to [HTTP/2 frames while in the connection pool kill reuse](https://curl.haxx.se/docs/knownbugs.html#HTTP_2_frames_while_in_the_conne), and we *can* fix this in a nicer way than just prematurely killing the connection - which I don't see any point in doing.

> they would call select (see sendrecv for example) but if data is already cached by libcurl or the SSL library how do they know?

They won't. But I think `CONNECT_ONLY` as well as recv/send are causing us much more pain and tears than they offer benefits to people so I won't lose any sleep over some (mostly theoretical) issues with that API.
