### ISSUE TITLE
Intermittent test 1702 fails: HTTP/2 HEAD with Upgrade:

### ISSUE THREAD

**Issue by bagder** [curl/curl#1130]
I get an intermittent problem with test 1702. Has anyone else tried to run test 1702 repeatedly lately? Here's my output when it fails (just ran it on git master, curl-7_51_0-64-g0b8d682):
~~~
test 1702...[HTTP/2 HEAD with Upgrade:]
sp----emv- OK (3   out of 7  , remaining: 00:09)
test 1702...[HTTP/2 HEAD with Upgrade:]
sp----emv- OK (4   out of 7  , remaining: 00:06)
test 1702...[HTTP/2 HEAD with Upgrade:]

 1702: stdout FAILED:
--- log/check-expected  2016-11-17 23:03:04.601239185 +0100
+++ log/check-generated 2016-11-17 23:03:04.601239185 +0100
@@ -8,6 +8,8 @@
 etag: "21025-dc7-39462498"[CR][LF]
 accept-ranges: bytes[CR][LF]
 content-length: 6[CR][LF]
+conne: [CR][LF]
+ction: close[CR][LF]
 content-type: text/html[CR][LF]
 funny-head: yesyes[CR][LF]
 server: cut-out[CR][LF]

 - abort tests
TESTDONE: 4 tests out of 5 reported OK: 80%
TESTFAIL: These test cases failed: 1702 
~~~

Interesting snippet from `log/trace1702` after the failure shows that the `on_header` callback function gets called by nghttp2 like that, with a broken set of headers! I changed the infof() ad the bottom of that function to be:

> DEBUGF(infof(data_s, "h2 header: %d/%d  %.*s: %.*s\n", namelen, valuelen, namelen, name, valuelen, value));

... and that produced this output:
~~~
23:21:01.167862 == Info: h2 status: HTTP/2 200 (easy 0xc2cbc98)
23:21:01.174099 == Info: h2 header: 4/29  date: Thu, 09 Nov 2010 14:49:00 GMT
23:21:01.174388 == Info: h2 header: 13/29  last-modified: Tue, 13 Jun 2000 12:10:00 GMT
23:21:01.174915 == Info: h2 header: 4/20  etag: "21025-dc7-39462498"
23:21:01.175053 == Info: h2 header: 13/5  accept-ranges: bytes
23:21:01.175823 == Info: h2 header: 14/1  content-length: 6
23:21:01.177562 == Info: h2 header: 5/0  conne: 
23:21:01.177703 == Info: h2 header: 5/5  ction: close
23:21:01.177829 == Info: h2 header: 12/9  content-type: text/html
23:21:01.178009 == Info: h2 header: 10/6  funny-head: yesyes
23:21:01.178106 == Info: h2 header: 6/26  server: nghttpx nghttp2/1.17.0-DEV
23:21:01.178200 == Info: h2 header: 3/11  via: 1.1 nghttpx
~~~

See `conne` that is 5 bytes name with 0 bytes content and then 'ction' is 5 bytes name again with 5 bytes content!! @tatsuhiro-t, can you think of a way how we can cause this?

This is using nghttp2 from git master right now: v1.16.0-30-g00bd76f, https://github.com/nghttp2/nghttp2/commit/00bd76fc3def

**Comment by jay** [comment]
That's very weird, and to answer your question from #1129 no I didn't see that, and I ran each a total of 100 times, and since 1700 was the only one with sporadic failures I started focusing on it exclusively after that. I will run it for an hour or two and see what happens. Try to reproduce using the commit prior to when I changed the window size, it is 342aa47. This way we can (hoepfully) eliminate that change as a potential cause. Also check http_v2_server.log nghttp2 should record the headers it will send in that file and you can confirm it's actually sending them as expected.

**Comment by jay** [comment]
Also you should give your nghttp2 version, mine is 1.16.1. And if you want to get dirty put this patch on top https://github.com/curl/curl/compare/master...jay:openssl_dump_secrets and monitor in wireshark to be certain

**Comment by bagder** [comment]
I caught the case in gdb:
~~~
Breakpoint 1, on_header (session=0x5555558efc60, frame=0x5555558efdf8, 
    name=0x5555558f59e8 "conne", namelen=5, value=0x5555558f5a28 "", valuelen=0, 
    flags=0 '\000', userp=0x5555558e6c48) at http2.c:910
910         infof(data_s, "Suspect\n");
(gdb) bt
#0  on_header (session=0x5555558efc60, frame=0x5555558efdf8, name=0x5555558f59e8 "conne", 
    namelen=5, value=0x5555558f5a28 "", valuelen=0, flags=0 '\000', userp=0x5555558e6c48)
    at http2.c:910
#1  0x00007ffff7572902 in session_call_on_header (nv=0x7fffffffd300, frame=0x5555558efdf8, 
    session=0x5555558efc60) at nghttp2_session.c:3294
#2  inflate_header_block (call_header_cb=1, final=1, inlen=67, 
    in=0x5555558e7be6 "@\204\"Lz\277\204%\aA\177_\207I|\245\211\323M\037@\210\226ڪ\364\264\345\034\237\205\364Tz*?v\223\252iҚ\374\251Tӥ5\211\200\256\027W\002\327\360q|\210\n\341R\251\247J", <incomplete sequence \363>, readlen_ptr=<synthetic pointer>, frame=0x5555558efdf8, 
    session=0x5555558efc60) at nghttp2_session.c:3622
#3  nghttp2_session_mem_recv (session=0x5555558efc60, 
    in=0x5555558e7b91 "\210a\226\337=\277J\001\365\064\237\272\202", inlen=161)
    at nghttp2_session.c:6002
#4  0x0000555555599cf0 in http2_recv (conn=0x5555558e6c48, sockindex=0, 
    mem=0x5555558ab678 "HTTP/1.1 101 Switching Protocols\r\nConnection: Upgrade\r\nUpgrade: h2c\r\n\r\n", len=16384, err=0x7fffffffd424) at http2.c:1509
#5  0x0000555555583ff9 in Curl_read (conn=0x5555558e6c48, sockfd=5, 
    buf=0x5555558ab678 "HTTP/1.1 101 Switching Protocols\r\nConnection: Upgrade\r\nUpgrade: h2c\r\n\r\n", sizerequested=16384, n=0x7fffffffd4a0) at sendf.c:705
~~~

The [http_v2_server.log](https://github.com/curl/curl/files/598674/http_v2_server.log.txt) shows the broken header:

~~~
17/Nov/2016:23:59:41 +0100 PID26213 [INFO] shrpx_http2_upstream.cc:1817 [UPSTREAM:0x55601a305250] HTTP response headers. stream_id=1
:status: 200
date: Thu, 09 Nov 2010 14:49:00 GMT
last-modified: Tue, 13 Jun 2000 12:10:00 GMT
etag: "21025-dc7-39462498"
accept-ranges: bytes
content-length: 6
conne: 
ction: close
content-type: text/html
funny-head: yesyes
server: nghttpx nghttp2/1.17.0-DEV
via: 1.1 nghttpx
~~~

And the `log/server.response` says these headers were send from the HTTP/1.1 backend:
~~~
HTTP/1.1 200 OK
Date: Thu, 09 Nov 2010 14:49:00 GMT
Server: test-server/fake
Last-Modified: Tue, 13 Jun 2000 12:10:00 GMT
ETag: "21025-dc7-39462498"
Accept-Ranges: bytes
Content-Length: 6
Connection: close
Content-Type: text/html
Funny-head: yesyes

**Comment by bagder** [comment]
> Try to reproduce using the commit prior to when I changed the window size

I tested with the window size change reverted but there was no visible change.

**Comment by tatsuhiro-t** [comment]
This may be a nghttpx bug which mishandles headers from backend.  Will look
into it.

2016/11/18 8:08 "Daniel Stenberg" <notifications@github.com>:

**Comment by jay** [comment]
I ran it 1500 times here but all were ok.

**Comment by tatsuhiro-t** [comment]
I think this is a bug of nghttpx in master branch.  v1.16.1 is not affected.
This happens if response header fields from backend is split into 2 packets.  In our case, it seems that the header block is divided into 2 packets at the position "...conne" and "ction...".

**Comment by tatsuhiro-t** [comment]
I fixed this nghttpx bug just now.

**Comment by bagder** [comment]
Confirmed. I ran it 20 times in a row that just never worked before. Thanks a lot!
