### ISSUE TITLE
Running lots of libcurl requests in parallel on separate threads causes "Couldn't resolve host name" error

### ISSUE THREAD

**Issue by RaisinTen** [curl/curl#11316]
### I did this

> **Note**
> This issue reproduces with both the easy perform API (with manual threading) as well as the multi-handle API. You'll find info about the multi-handle API usage in the `additional info` section at the bottom of the issue.

I wrote a program to send a lot of requests using libcurl's easy perform API, each on separate threads, and write the results to a file:

<details>

```cc
#include <curl/curl.h>

#include <chrono>
#include <fstream>
#include <future>
#include <iostream>
#include <map>
#include <sstream>

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata) {
  *static_cast<std::ostringstream *>(userdata)
      << std::string{const_cast<const char *>(ptr), size * nmemb};
  return size * nmemb;
}

struct Response {
  std::string body;
  std::optional<std::string> error;
};

Response request(const std::string_view url) {
  CURL *curl;

  Response data;

  CURLcode res;

  curl = curl_easy_init();
  if (curl) {
    curl_easy_setopt(curl, CURLOPT_URL, url.data());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
    std::ostringstream write_callback_data;
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &write_callback_data);

    res = curl_easy_perform(curl);
    if (res != CURLE_OK) {
      data.error = curl_easy_strerror(res);
    } else {
      data.body = write_callback_data.str();
    }

    curl_easy_cleanup(curl);
  }
  return data;
}

int main() {
  constexpr int num_requests{100};

  std::vector<Response> responses;
  responses.reserve(num_requests);

  std::vector<std::future<Response>> futures;
  futures.reserve(num_requests);

  std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();

  for (int i = 0; i < num_requests; ++i) {
    futures.emplace_back(std::async([] {
      return request("https://postman-echo.com/get");
    }));
  }

  for (auto& future : futures) {
    responses.emplace_back(future.get());
  }

  std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();

  std::cout
    << "time to run all the requests: "
    << std::chrono::duration_cast<std::chrono::seconds>(end - begin).count()
    << "s"
    << std::endl;

  std::ofstream file{"output.txt"};
  for (int i = 0; i < responses.size(); ++i) {
    file << i << ": ";
    if (responses[i].error.has_value()) {
      file << "error: " << responses[i].error.value() << std::endl;
    } else {
      file << responses[i].body << std::endl;
    }
  }

  return 0;
}
```

</details>

It printed that it took ~35s to run the requests and wrote the request bodies to the `output.txt` file.

### I expected the following

I expected the program to succeed in sending all the requests and write something like this to the `output.txt` file:

<details>

```cc
0: {
  "args": {},
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-6489a736-166bbc6e61e17bc23076f5d4",
    "accept": "*/*"
  },
  "url": "https://postman-echo.com/get"
}
1: {
  "args": {},
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-6489a736-5f61fe877da452b255dbd1c8",
    "accept": "*/*"
  },
  "url": "https://postman-echo.com/get"
}
...
99: {
  "args": {},
  "headers": {
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "postman-echo.com",
    "x-amzn-trace-id": "Root=1-6489a141-628954aa569d0f5913961ccf",
    "accept": "*/*"
  },
  "url": "https://postman-echo.com/get"
}
```

</details>

However, the output is sprinkled with a lot of `Couldn't resolve host name` errors:
```
0: error: Couldn't resolve host name
1: error: Couldn't resolve host name
...
```

Additionally, I tried doing the same thing but using a threadpool this time using this header-only thread pool library - https://github.com/bshoshany/thread-pool/blob/cabb3df5876c9a6824b07fcb0ff73d4a0e506ca0/include/BS_thread_pool_light.hpp. Here's the program using the thread pool:

<details>

```cc
#include <curl/curl.h>

#include "BS_thread_pool_light.hpp"

#include <chrono>
#include <fstream>
#include <future>
#include <iostream>
#include <map>
#include <sstream>

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata) {
  *static_cast<std::ostringstream *>(userdata)
      << std::string{const_cast<const char *>(ptr), size * nmemb};
  return size * nmemb;
}

struct Response {
  std::string body;
  std::optional<std::string> error;
};

Response request(const std::string_view url) {
  CURL *curl;

  Response data;

  CURLcode res;

  curl = curl_easy_init();
  if (curl) {
    curl_easy_setopt(curl, CURLOPT_URL, url.data());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
    std::ostringstream write_callback_data;
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &write_callback_data);

    res = curl_easy_perform(curl);
    if (res != CURLE_OK) {
      data.error = curl_easy_strerror(res);
    } else {
      data.body = write_callback_data.str();
    }

    curl_easy_cleanup(curl);
  }
  return data;
}

int main() {
  constexpr int num_requests{100};

  BS::thread_pool_light pool{50};

  std::vector<Response> responses;
  responses.reserve(num_requests);

  std::vector<std::future<Response>> futures;
  futures.reserve(num_requests);

  std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();

  for (int i = 0; i < num_requests; ++i) {
    futures.emplace_back(pool.submit([] {
      return request("https://postman-echo.com/get");
    }));
  }

  for (auto& future : futures) {
    responses.emplace_back(future.get());
  }

  std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();

  std::cout
    << "time to run all the requests: "
    << std::chrono::duration_cast<std::chrono::seconds>(end - begin).count()
    << "s"
    << std::endl;

  std::ofstream file{"output.txt"};
  for (int i = 0; i < responses.size(); ++i) {
    file << i << ": ";
    if (responses[i].error.has_value()) {
      file << "error: " << responses[i].error.value() << std::endl;
    } else {
      file << responses[i].body << std::endl;
    }
  }

  return 0;
}
```

</details>

From my testing, this program works only if the thread pool size is <= 50 (with 50 threads, this takes ~6s to run all the requests). Otherwise, the output is again filled with the `Couldn't resolve host name` errors.

### curl/libcurl version

[curl -V output]

```sh
$ curl -V
WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.1.2-DEV (x86_64-apple-darwin22.4.0) libcurl/8.1.2-DEV OpenSSL/3.0.8 zlib/1.2.11 nghttp2/1.53.0 ngtcp2/0.15.0 nghttp3/0.9.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP TrackMemory UnixSockets
```

### operating system

```sh
Darwin Darshans-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
```

Also, number of logical CPUs, in case it's needed:
```sh
$ sysctl -n hw.logicalcpu
8
```

The limit of the maximum number of open sockets/files in a process:
```sh
$ ulimit -n
256
```

#### using multi handle API instead of manual threading is also affected by this

I also tried translating the program to use libcurl's multi handle API instead of handling threads manually myself and the issue reproduces there too. `Activity Monitor` tells me that this program uses ~35 threads during the first run after compilation (but that number keeps changing seemingly randomly each run).

<details>

```cc
#include <curl/curl.h>

#include <chrono>
#include <fstream>
#include <iostream>
#include <sstream>

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata) {
  *static_cast<std::ostringstream *>(userdata)
      << std::string{const_cast<const char *>(ptr), size * nmemb};
  return size * nmemb;
}

struct Response {
  std::string body;
  std::optional<std::string> error;
};

int main() {
  constexpr int num_requests{100};

  std::vector<Response> responses;
  responses.resize(num_requests);

  CURL *handles[num_requests];
  CURLM *multi_handle;
  std::vector<std::ostringstream> write_callback_data(num_requests);

  int still_running = 1; /* keep number of running handles */
  int i;

  CURLMsg *msg; /* for picking up messages with the transfer status */
  int msgs_left; /* how many messages are left */

  /* Allocate one CURL handle per transfer */
  for(i = 0; i < num_requests; i++) {
    handles[i] = curl_easy_init();
    curl_easy_setopt(handles[i], CURLOPT_URL, "https://postman-echo.com/get");
    curl_easy_setopt(handles[i], CURLOPT_WRITEFUNCTION, write_callback);
    curl_easy_setopt(handles[i], CURLOPT_WRITEDATA, &write_callback_data[i]);
  }

  /* init a multi stack */
  multi_handle = curl_multi_init();

  /* add the individual transfers */
  for(i = 0; i < num_requests; i++)
    curl_multi_add_handle(multi_handle, handles[i]);

  std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();

  while (still_running) {
    CURLMcode mc = curl_multi_perform(multi_handle, &still_running);

    if(still_running)
      /* wait for activity, timeout or "nothing" */
      mc = curl_multi_poll(multi_handle, NULL, 0, 1000, NULL);

    if(mc)
      break;
  }

  /* See how the transfers went */
  while((msg = curl_multi_info_read(multi_handle, &msgs_left))) {
    if(msg->msg == CURLMSG_DONE) {
      int idx;

      /* Find out which handle this message is about */
      for(idx = 0; idx < num_requests; idx++) {
        int found = (msg->easy_handle == handles[idx]);
        if(found)
          break;
      }

      CURLcode code = msg->data.result;
      if (code != CURLE_OK) {
        responses[idx].error = curl_easy_strerror(code);
      } else {
        responses[idx].body = write_callback_data[idx].str();
      }
    }
  }

  std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();

  std::cout
    << "time to run all the requests: "
    << std::chrono::duration_cast<std::chrono::seconds>(end - begin).count()
    << "s"
    << std::endl;

  /* remove the transfers and cleanup the handles */
  for(i = 0; i < num_requests; i++) {
    curl_multi_remove_handle(multi_handle, handles[i]);
    curl_easy_cleanup(handles[i]);
  }

  curl_multi_cleanup(multi_handle);

  std::ofstream file{"output.txt"};
  for (int i = 0; i < responses.size(); ++i) {
    file << i << ": ";
    if (responses[i].error.has_value()) {
      file << "error: " << responses[i].error.value() << std::endl;
    } else {
      file << responses[i].body << std::endl;
    }
  }

  return 0;
}
```

</details>

**Comment by bagder** [comment]
I suspect you run into the limit of the maximum number of open sockets in your process. I believe `ulimit -n` shows it.

**Comment by RaisinTen** [comment]
@bagder I've updated the issue with the `ulimit -n` output.

**Comment by bagder** [comment]
256 concurrently open "files" *per process* is low for doing large amount of concurrent transfers. This is likely to be the limit you run into as then libcurl will start getting errors which probably results in failures to resolve host names. I propose you raise the limit and see if that changes anything.

**Comment by RaisinTen** [comment]
Indeed, setting it to a much higher value like `ulimit -n 1000` works without errors for all the programs in the issue description.

Next, I tried to open 1000 parallel requests (by modifying the `num_requests` value to `1000` in the first code example in the issue) and that too had the same `Couldn't resolve host name` errors in the output. So I ran `ulimit -n 10000` (notice the extra `0` because now I'm running 1000 requests instead of 100) and the output now is a combination of correct response bodies and a lot of `A libcurl function was given a bad argument` errors (no `Couldn't resolve host name` errors this time). This ran for 7s using ~175 threads.

However, when I use the thread pool implementation with a much smaller thread pool size (like 11) that works without errors but it takes ~80s to run. I guess using a thread pool is necessary if I don't want the users of my program to manually run `ulimit -n`.

Let me know if my understanding is correct, then we can close this issue.

---

I wonder how Node.js' (v20.3.0) built-in networking layer is able to send 1000 requests in parallel (not all of them in individual threads, Node.js has a thread pool) with no errors without requiring me to manually set this value, in only ~12s.

<details>

This program sends 1000 requests and measures the time taken and finally writes the response bodies to `output.txt` if there are no errors.

```js
const https = require('node:https');
const fs = require('node:fs');

function request(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { timeout: 3600 }, (res) => {
      res.setEncoding('utf8');
      let rawData = '';
      res.on('data', (chunk) => { rawData += chunk; });
      res.on('end', () => {
        resolve(rawData);
      });
    }).on('error', (err) => {
      reject(err);
    });
  });
}

(async () => {
  let requests = [];
  console.time('time to run all the requests');
  for (let i = 0; i < 1000; ++i) {
    requests.push(request('https://postman-echo.com/get'));
  }
  const values = await Promise.all(requests);
  console.timeEnd('time to run all the requests');
  let output = '';
  for (let i = 0; i < values.length; ++i) {
    output += `${i}: ${values[i]}\n`;
  }
  fs.writeFileSync('output.txt', output);
})()
```

</details>

According to `Activity monitor`, this program uses 11 threads in total (some of those might be used for tasks unrelated to sending network requests) and it takes ~12s to complete all the requests.

Do you know off the top of your head? If not, I could probably try to run some benchmarks and find out.

**Comment by bagder** [comment]
You're mixing different things.

## Resources

Each libcurl transfer will use a few sockets. Let's say the numbers is S (1, 2, 3 something). The exact number depends on several different factors. Any process you run libcurl in needs to allow N open file descriptor to let you use N/S concurrent libcurl transfers at max. This is just how things work. There are things you can tweak, but the fundamental issue is a simple matter of resources that libcurl needs and that your system limits.

## Performance

Creating a new easy handle, do the transfer and then immediately killing that handle is a most **inefficient way** to use libcurl when doing multiple transfers. A key to getting fast transfers is to reuse easy handles as much as possible, in particular if you do multiple transfers from the same host name. In fact, using threads to do many transfers are often a less good alternative to using the multi interface - which runs in a single thread. Or put another way: the ideal threading layout for a high performance libcurl using app is to use one thread per CPU core and then use the multi interface in each such thread. 

Of course the exact details and best architecture choices depend on details and specifics that have not been discussed here and quite frankly are also off topic.

**Comment by RaisinTen** [comment]
That makes sense, thanks for the explanation!

> Any process you run libcurl in needs to allow N open file descriptor to let you use N/S concurrent libcurl transfers at max.

If I'm using the multi interface, is the number of concurrent libcurl transfers something I need to limit in the application code myself (not sure if there is a libcurl API to tweak that setting) or is that something that's supposed to be taken care of internally by the multi interface code? I'm asking because the code I've added in the `additional section` of the issue which uses the multi interface is also running into this error and I wasn't sure of a way to limit the number of concurrent transfers initiated by the multi interface through the libcurl APIs.

> In fact, using threads to do many transfers are often a less good alternative to using the multi interface - which runs in a single thread.

Not sure I understand the part about the multi interface running things on a single thread because the multi interface code seems to be spawning ~35 threads.

**Comment by bagder** [comment]
> If I'm using the multi interface, is the number of concurrent libcurl transfers something I need to limit in the application code myself

I will urge you to read the documentation on how to use libcurl. We spend a considerable amount of time and effort on documenting all the details and I believe the multi interface's ins and outs are covered fairly well. Well yes of course the number of open sockets issue happens for the multi interface as well. I told you about how it works with parallel transfers. That is true no matter how you do those parallel transfers.

Now, I consider this issue done. This is not a curl bug, this is a resource limitation.

If you have further questions on how to use libcurl and how libcurl works, I consider that  to be outside of this issue and therefore off-topic here. I will recommend you try to read up yourself first though before you continue asking.
