### ISSUE TITLE
Test reliability needs improvement

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11328]
The introduction of parallel testing (#10818) has caused timing differences in tests that make some of their flakiness more apparent. Some improvements have been made along the parallel testing work (e.g. #11231), but more improvements are needed.

This bug will track test improvements needed before parallel testing can be enabled by default.

One obvious one is that TFTP tests actually include timing information as part of the checked output, which causes failures  on slow/loaded servers.

**Comment by bagder** [comment]
This is still true, but this issue is too open ended that we can't know when it is fixed or not. We should rather file issues for specific issues or problems when we identify them.
