### ISSUE TITLE
NULL connection name sometimes in test 1506

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11327]
Occasionally, test 1506 fails with this diff output:
```
test 1506...[HTTP GET connection cache limit (CURLMOPT_MAXCONNECTS)]
 1506: output (log/4/stderr1506) FAILED:
--- log/4/check-expected	2023-06-16 12:00:10.750420100 -0700
+++ log/4/check-generated	2023-06-16 12:00:10.750420100 -0700
@@ -1,5 +1,5 @@
-* Connection #0 to host server1.example.com left intact[CR][LF]
-* Connection #1 to host server2.example.com left intact[CR][LF]
-* Connection #2 to host server3.example.com left intact[CR][LF]
+* Connection #0 to host (nil) left intact[CR][LF]
+* Connection #1 to host (nil) left intact[CR][LF]
+* Connection #2 to host (nil) left intact[CR][LF]
 * Closing connection[CR][LF]
-* Connection #3 to host server4.example.com left intact[CR][LF]
+* Connection #3 to host (nil) left intact[CR][LF]
== Contents of files in the log/4/ dir after test 1506
=== Start of file check-expected
```
e.g. https://cirrus-ci.com/task/6731810650980352?logs=test#L2570  Rather than the host name, `(nil)` (which is msnprintf's way of saying NULL) is displayed, which translates to either conn->conn_to_host.dispname or conn->host.dispname (in `multi_done` in multi.c).

The comment next to conn_to_host says `host name for the connection (may be NULL)` so it's possible this is OK, except that I would expect it to be consistent from run to run and not NULL some runs and containing a valid host name other runs. Both the URL and the name resolution come from fixed data (`CURLOPT_URL` and `CURLOPT_RESOLVE` in lib1506.c) so network delays, packet loss, timeouts etc. should have no effect on this.

**Comment by bagder** [comment]
I believe #11321 is fix for those.

**Comment by dfandrich** [comment]
I didn't notice that this issue has been going on now consistently on this build for some days. That proposed fix would explain it nicely.
