### ISSUE TITLE
Excessive "Connection #xx is still name resolving, can't reuse" messages after upgrading to libcurl 8.0.1

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#11323]
### I did this
After upgrading to libcurl version 8.0.1, I noticed that there is a significant increase in the number of "Connection #xx is still name resolving, can't reuse" messages in the logs. Previously, when using libcurl version 7.86.0, I did not experience this issue.

### I expected the following
I expected the libcurl upgrade to maintain the same behavior as the previous version and not produce excessive "Connection #xx is still name resolving, can't reuse" messages.

### curl/libcurl version
8.0.1

### operating system
Mac / Windows

**Comment by bagder** [comment]
Can you provide us with an example source code, maybe re-creating what you do, that reproduces this problem against a public URL? Without more information it is hard to us to act on this.

**Comment by ustcqidi** [comment]
@bagder 

This issue is related to a specific problem described in the GitHub pull request [link](https://github.com/curl/curl/pull/10456/files). After commenting out the connkeep code in the http.c file, the occurrence of "Connection #xx is still name resolving, can't reuse" messages has been eliminated.

**Comment by yushicheng7788** [comment]
@bagder  Good day, I ran the example [https://curl.se/libcurl/c/10-at-a-time.html](url), and replaced the urls array with urls which are belong to same host.  From log, I can see a lot of information shown "Connection #xxx is still name resolving, can't reuse".  If I revert the commit [https://github.com/curl/curl/pull/10456](url), there will no log about "Connection #xxx ...". Is this a normal issue?  It seems that the commit will make conn->bits.close equals false, which will make "ConnectionExists" function continue executing when checking "if (check->connect_only || check->bits.close)", but "check->primary_ip" is null which cause a lot of "Connection #xxx is still ....".

**Comment by bagder** [comment]
Fixed via 5413d24aae0
