### ISSUE TITLE
Test 2600 failures under load

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11355]
A recent CI test run with parallel testing enabled produced some test 2600 failures on GHA on Linux. The two types of failures were:
```
 unit2600.c:253 test failed: '1: expected 1 ipv4 creations, but got 0'
 unit2600.c:272 test failed: '1: expected max duration of 600ms, but took 701ms'
```
The test seems to be timing sensitive, so maybe the timeouts just need to be increased (especially for that second failure), but without digging in to the test I'm not sure if a bad timeout would cause the first failure, too.  Here are the failing logs from that run:
 - https://github.com/curl/curl/actions/runs/5326219621/jobs/9647954943
 - https://github.com/curl/curl/actions/runs/5326219621/jobs/9647955185
 - https://github.com/curl/curl/actions/runs/5326219621/jobs/9647956784
 - https://github.com/curl/curl/actions/runs/5326219621/jobs/9647956899

**Comment by icing** [comment]
Sometimes it takes longer. See #11690 for an attempt to address this.

**Comment by bagder** [comment]
@dfandrich I don't think I have seen many test 2600 failures lately. Is this issue still valid?
