### ISSUE TITLE
REUSE CI job says "The following files have no licensing information: * README"

### ISSUE THREAD

**Issue by bagder** [curl/curl#11359]
This just started . The README file has not changed. It is still mentioned in `.reuse/dep5` where it has copyright and license information provided... ?

Example output: https://github.com/curl/curl/actions/runs/5334029561/jobs/9665276498?pr=11346

**Comment by mxmehl** [comment]
Somewhat, yes. We introduced a bigger change in 2.0.0 removing an unintended function (merging of information from different sources) and introduced an improvement (clear order of precedence). Unfortunately, in some cases, this made lint jobs fail and we didn't consider the outfall properly.

We'll yank the 2.0.0 release, see fsfe/reuse-tool#775. Actually, the Docker images (and therefore REUSE Github action) should already use v1.1.2 again, so your tests should pass with the next run.

**Comment by bagder** [comment]
Thanks. And yes, the jobs seem to run fine again!
