### ISSUE TITLE
Tests broken with native Windows perl

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#11350]
### I did this

From an MSYS2 shell on Windows:
```
cd tests && ./runtests.pl
```

### I expected the following

Successful test run. Instead, I get:
```
No such signal: SIGUSR1 at ./runtests.pl line 274.
```

This is with MSYS2's perl used in its MINGW32 shell:
```
$ perl --version
This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x86-multi-thread-64int
```

Strangely, the error doesn't appear in the CI.

### curl/libcurl version

https://github.com/curl/curl/commit/2fe52412b1b6ce46f1437c5f7758215a2b9ce05e

### operating system

Windows 10 (MSYS2)

CC @dfandrich

**Comment by dfandrich** [comment]
SIGUSR1 has been part of POSIX from the beginning. What signals are available in this perl?

**Comment by MarcelRaad** [comment]
`perl -e 'print join(" ", keys %SIG)'` says:
```
ILL NUM10 NUM17 HUP NUM12 PIPE BREAK TERM NUM16 ALRM KILL INT NUM19 ABRT NUM05 CHLD STOP SEGV NUM07 NUM18 CONT CLD QUIT FPE NUM06 NUM24
```

Maybe I also did something wrong, this is the first time I've set up an MSYS2 development environment in a long time, and the last time I've manually run the tests in MSYS2 was last year.

**Comment by dfandrich** [comment]
For comparison, SIGUSR1 is #10 on Linux, #16 on Solaris, #30 on FreeBSD and
OpenBSD. "NUM10" and "NUM16" are both in your list, which makes it seem like
those are placeholders for a signal that isn't supported on that OS or that
perl version. The SIGUSR1 define has been a part of msys2 for at least 22 years
according to git, but I don't know about perl. I've also just read that Windows
doesn't even support sending signals like I'm using SIGUSR1 for, so maybe an
error setting this signal handler should simply be ignored on Windows.

**Comment by MarcelRaad** [comment]
> I've also just read that Windows
doesn't even support sending signals like I'm using SIGUSR1 for, so maybe an
error setting this signal handler should simply be ignored on Windows.

Sounds good to me!
