### ISSUE TITLE
Error: curl 56 HTTP/2 stream N was reset

### ISSUE THREAD

**Issue by georgii-sosnovikov** [curl/curl#11353]
When trying to push changes to a git repo that is in Azure DevOps, users get an error like "error: RPC failed; curl 56 HTTP/2 stream 7 was reset". Users start getting this kind of error after updating git version to [2.41.0.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.41.0.windows.1) (released 01/06/23) which uses [curl 8.1.2](https://github.com/curl/curl/releases/tag/curl-8_1_2) (released 30/05/23).

I see that just recently you had the same issues:
https://github.com/curl/curl/issues/11201 (and it doesn't depend on where a repository is.),
https://github.com/curl/curl/issues/11194

As I see it, the fix seems to be in the master and also in 8.1.2 on 25/05/23
https://github.com/curl/curl/commit/5c58cb0212bcf63cce33a974906bf9905948b4bb

So based on the dates, the fix is delivered, but it doesn't work.

Just in case, here's the issue reported in the Git repository https://github.com/git-for-windows/git/issues/4469

### I did this

Trying to git push to a repository hosted by Azure DevOps

### I expected the following

The push should be successful

### curl/libcurl version

`curl 8.1.2 (x86_64-w64-mingw32) libcurl/8.1.2 Schannel zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd`

### operating system

Windows 11

**Comment by icing** [comment]
The next release is curl 8.2.0 on July 19

**Comment by icing** [comment]
Could you build curl `master` and check that version in your setup? If it still happens, please open a new ticket.

**Comment by bagder** [comment]
(If you can't build yourself, note that we provide daily snapshots that include windows binaries.)

**Comment by bagder** [comment]
No response. We believe this is fixed.

**Comment by georgii-sosnovikov** [comment]
@bagder this issue does not occur for me, but has occurred for some users who tried to push changes to ADO repos. So I can't say if this fixed or not, maybe let's wait for a fix to be released?

**Comment by MoeHamdan** [comment]
No fixed, I am experiencing the issue right now. The issue is with one of the repos, others are working fine.

**Comment by bagder** [comment]
@MoeHamdan we need a lot more info than that if we are going to be able to do anything.

I propose you create a new issue if this happens with 8.2.1, with details for us to either reproduce or track/understand what is going on.

**Comment by leonandroid** [comment]
@bagder if this helps, I'm havign the same issue today, suddenly for a branch rc/demo <- and any other branch created from this one, I get this error:

Enumerating objects: 143, done.
Counting objects: 100% (143/143), done.
Delta compression using up to 12 threads
Compressing objects: 100% (93/93), done.
Writing objects: 100% (96/96), 69.87 KiB | 5.82 MiB/s, done.
Total 96 (delta 75), reused 0 (delta 0), pack-reused 0 **<-- this line hangs for like 2 minutes**
**error: RPC failed; curl 56 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly**
Everything up-to-date

What's odd, I try to push from another branch, and I don't have problems, is just with this one that is a very recent branch. 
What could be the issue?

**Comment by bagder** [comment]
@leonandroid it does not help. The fact that you get a similar error message does not say it is the same underlying problem, if it even is a curl problem to begin with. And you're not saying which curl version, component versions or platform you're on. Honestly, that sounds like a server issue from the brief description we see here.

**Comment by ccpjulia** [comment]
Hi, 
I am getting the same problem as of Friday the 18th of August when trying to push into an ADO repo. 

```
git push --set-upstream origin new-branch
Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 16 threads
Compressing objects: 100% (32/32), done.
Writing objects: 100% (34/34), 70.16 KiB | 5.01 MiB/s, done.
Total 34 (delta 11), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 56 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

No repo settings were changed and this just started all of a sudden. Creating a new branch doesn't help nor does re-starting the computer. The Totals line also hangs for me for a while until it goes into the reset. 

This is quite the issue for us, as this repo is unusable as of Friday.

**Comment by bagder** [comment]
1. if you're seeing this problem with a curl version before 8.2.1, then **upgrade** first before commenting here
2. if you see this problem with curl 8.2.1 (or later) then give us **details** on the operation. What components are involved, on which platform using what versions and what exactly happened or did not happen over the wire (enable extensive verbose/tracing).

**Comment by tedhudek** [comment]
Just anecdotally, I ran into this problem today with curl 8.0.1.0 on Windows 11, version 22H2.  I was trying to push a commit involving ~30 files to an existing branch of an ADO repo, and the error output was:

```
Total 96 (delta 61), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 56 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```

I then tested pushing a trivial change as a new branch with no problem.  I also tested pushing a trivial change to a different existing branch, no problem.

My fix was to do `git config --global http.version HTTP/1.1`, push, then `git config --global http.version HTTP/2`.

**Comment by christiangitter** [comment]
@tedhudek : Thanks man! 
Your Steps solved my problem.

**Comment by icing** [comment]
Thanks for documenting the workaround. 

8.0.1 indeed has this annoying bug. Sorry about that.

**Comment by ccpjulia** [comment]
@tedhudek Thanks that also worked for me!

**Comment by bagder** [comment]
I just mentioned this issue on [the git mailing list](https://marc.info/?l=git&m=169270480821400&w=2), to raise awareness.

**Comment by SoumyaMukhija** [comment]
I'm hoping this could also help someone who lands on this page - I was trying to push a large number of changes at once (same as @bagder ). Changing the buffer size of git so it would allow all my changes to pass through at once was what worked for me.

`git config --global http.postBuffer 157286400`

**Comment by LucasNeevs** [comment]
> I believe this could also help someone who lands on this page - I was trying to push a large number of changes at once (same as @bagder ). Changing the buffer size of git so it would allow all my changes to pass through at once was what worked for me.
> 
> `git config --global http.postBuffer 157286400`

Unfortunatelly here, it didn't work...I used @tedhudek solution that fit pretty well for me.

**Comment by niyozbekmirzayev** [comment]
@tedhudek 
Your solution solved my problem. Thank you

**Comment by Braincompiler** [comment]
Upgrade git on windows using `> git update-git-for-windows` resolved the problem for me. So consider to update to at least `git version 2.42.0.windows.2` to solve this problem. Better than every workaround of degradation the http.version before every push. The workaround should only used in environments you cannot update to the newest version of git-windows.

**Comment by Chrispako990210** [comment]
> When trying to push changes to a git repo that is in Azure DevOps, users get an error like "error: RPC failed; curl 56 HTTP/2 stream 7 was reset". Users start getting this kind of error after updating git version to [2.41.0.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.41.0.windows.1) (released 01/06/23) which uses [curl 8.1.2](https://github.com/curl/curl/releases/tag/curl-8_1_2) (released 30/05/23).
> 
> I see that just recently you had the same issues: #11201 (and it doesn't depend on where a repository is.), #11194
> 
> As I see it, the fix seems to be in the master and also in 8.1.2 on 25/05/23 [5c58cb0](https://github.com/curl/curl/commit/5c58cb0212bcf63cce33a974906bf9905948b4bb)
> 
> So based on the dates, the fix is delivered, but it doesn't work.
> 
> Just in case, here's the issue reported in the Git repository [git-for-windows/git#4469](https://github.com/git-for-windows/git/issues/4469)
> ### I did this
> 
> Trying to git push to a repository hosted by Azure DevOps
> ### I expected the following
> 
> The push should be successful
> ### curl/libcurl version
> 
> `curl 8.1.2 (x86_64-w64-mingw32) libcurl/8.1.2 Schannel zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 Release-Date: 2023-05-30 Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd`
> ### operating system
> 
> Windows 11

Don't know if this could help but the following worked for me : 
git config --global http.version HTTP/1.1

Im on windows 11.

**Comment by jamesulry** [comment]
> Don't know if this could help but the following worked for me : git config --global http.version HTTP/1.1
> 
> Im on windows 11 using AzureDevOps as git server

After increasing the buffer, then upgrading the git version, this is what worked for me.  I suppose at some date changing the Http version will come back to bite me.

**Comment by Kais4r** [comment]
just update to the newest git version and you will get no more error

**Comment by abdi4** [comment]
None of these worked for me. [This](https://stackoverflow.com/a/22317479/12593376) is the solution that worked for me
