### ISSUE TITLE
Add support for minimal TLS 1.x version of protocol

### ISSUE THREAD

**Issue by jkralik** [curl/curl#1136]
Now it is support only TLS1.0+ but in I want to set TLS1.1 and more.

I expected to set minimal TLS version that can be used by protocol.

A attached file is  a patch that implement this feature via CURL_SSLVERSION_MIN_TLSv1_x.
 
[0001-vtls-support-minimal-TLS-1.x-version-via-CURL_SSLVER.txt](https://github.com/curl/curl/files/608378/0001-vtls-support-minimal-TLS-1.x-version-via-CURL_SSLVER.txt)

**Comment by kdudka** [comment]
On Wednesday, November 23, 2016 00:37:56 jkralik wrote:
> Now it is support only TLS1.0+ but in I want to set TLS1.1 and more.
> 
> I expected to set minimal TLS version that can be used by protocol.
> 
> A attached file is  a patch that implement this feature via
> CURL_SSLVERSION_MIN_TLSv1_x.
> 
> [0001-vtls-support-minimal-TLS-1.x-version-via-CURL_SSLVER.txt](https://gith
> ub.com/curl/curl/files/608378/0001-vtls-support-minimal-TLS-1.x-version-via-
> CURL_SSLVER.txt)

Why do you define new set of enumeration constants CURL_SSLVERSION_MIN_TLSv1_X 
mapped to values incompatible with CURL_SSLVERSION_TLSv1_X?  Would not it be 
better to use the same values (with the same meaning) for both the options?

Kamil

**Comment by bagder** [comment]
Alternatively, we consider introducing an `*_OR_LATER` bit that we allow to be ORed into any other value so that we can support all versions *or later*.

**Comment by jkralik** [comment]
@kdudka : It uses same option CURLOPT_SSLVERSION .
@bagder : And when it will be implemented and how ? I can help if someone specify.

**Comment by kdudka** [comment]
On Wednesday, November 23, 2016 02:11:51 jkralik wrote:
> @kdudka : It uses same option CURLOPT_SSLVERSION .

OK, got it.  I originally understood it that the minimal TLS version could
be set independently of the maximal TLS version.  If you just want to be
able to specify TLS 1.X+, then the approach suggested by Daniel sounds more 
maintainable.

Anyway, I am not sure if such a solution is flexible enough from long-term 
perspective.  How would you e.g. disable just TLS 1.3 to avoid handshake 
failures when connecting to a TLS intolerant server?

Kamil

**Comment by jkralik** [comment]
The problem with "TLS intolerant server" is on server side. When you want to resolve your client you must iterate from up to down over TLS versions. This could be implemented in libcurl.

I will create patch with flag CURL_SSLVERSION_FLAG_OR_LATER that it extends arg "version" of option CURLOPT_SSLVERSION. 
BTW: CURL_SSLVERSION_TLSv1 has same problem with "TLS intolerant server".

**Comment by kdudka** [comment]
On Wednesday, November 23, 2016 05:25:55 Jozef Kralik wrote:
> The problem with "TLS intolerant server" is on server side.

Sure.  But people sometime need to connect such servers (and it is often not 
their decision whether the server part will be fixed or not).

> When you want to
> resolve your client you must iterate from up to down over TLS versions.

It is not really an iteration but rather a negotiation.  A compliant server
will just reply saying which TLS version it supports.

> This could be implemented in libcurl.

Not really.  At least not in a secure way.  There used to be an attempt to do 
that but it caused a lot of troubles, including vulnerability to MITM protocol 
downgrade attacks.

> I will create patch with flag CURL_SSLVERSION_FLAG_OR_LATER that it extends
> arg "version" of option CURLOPT_SSLVERSION. BTW: CURL_SSLVERSION_TLSv1 has
> same problem with "TLS intolerant server".

Yes and that is exactly the reason why CURL_SSLVERSION_TLSv1 does not enable 
TLS 1.3 for now despite certain TLS backends support it already.

Kamil

**Comment by TheDecryptor** [comment]
I don't think version intolerance will be an issue with TLS 1.3, at least until 1.4 is released and everything breaks again of course.

https://tlswg.github.io/tls13-spec/#backward-compatibility

1.3 fixes the handshake version to 1.2 and announces itself via a new extension, a 1.2 only server will just see a plain 1.2 handshake and should continue as normal.

**Comment by kdudka** [comment]
On Thursday, November 24, 2016 18:04:18 Alex wrote:
> I don't think version intolerance will be an issue with TLS 1.3, at least
> until 1.4 is released and everything breaks again of course.
> 
> https://tlswg.github.io/tls13-spec/#backward-compatibility
> 
> 1.3 fixes the handshake version to 1.2 and announces itself via a new
> extension, a 1.2 only server will just see a plain 1.2 handshake and should
> continue as normal.

In terms of specification, there is no problem.  The problem is that currently
available implementations of TLS 1.3 (both client and server-side) are mostly
experimental, which means they contain bugs.  There needs to be some mechanism
to work around these bugs.   For example, there was already a patch release of
NSS to re-disable TLS 1.3 by default:

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.27.1_release_notes

This should IMHO be also configurable at the level of libcurl API.

Kamil

**Comment by bagder** [comment]
I think it feels like unnecessary adventurous to enable TLS 1.3 by default before the spec is finalized and while all existing TLS 1.3-servers out there are still experimental. And there aren't even many servers to play with yet. So yes, I think we should keep treating 1.3 different than the earlier versions.

**Comment by kdudka** [comment]
Sure.  Still the question is whether it should be solely libcurl developers who decide whether TLS 1.3 is ready, or whether we should also give libcurl users a choice to disable TLS 1.3 if needed (even after it is marked stable by libcurl developers).

The currently proposed solution does not allow to enable TSL 1.1/1.2 only.  ```CURL_SSLVERSION_MIN_TLSv1_1``` or ```CURL_SSLVERSION_TLSv1_1|CURL_SSLVERSION_OR_LATER``` would work temporarily but once we (libcurl developers) enable TLS 1.3, users will have no mechanism to re-disable it except rebuilding a patched version of libcurl.

**Comment by bagder** [comment]
Right, so should we instead go for allowing a **minimum** and a **maximum** version in the API? Thus having the application set the range? That would probably give a sufficient flexibility for a long time ahead.

**Comment by jkralik** [comment]
I agree with you Daniel. We can extends CURLOPT_SSLVERSION by adding flags:
- `CURL_SSLVERSION_OR_UP_TO_DEFAULT`  = `CURL_SSLVERSION_OR_UP_TO_TLSv1_2` (for now)
- `CURL_SSLVERSION_OR_UP_TO_TLSv1_1` 
- `CURL_SSLVERSION_OR_UP_TO_TLSv1_2`
- `CURL_SSLVERSION_OR_UP_TO_TLSv1_3`

**Comment by bagder** [comment]
Seems doable!

It'll unfortunately require changes in a lot of places where the requested TLS version is checked and used in the TLS backend code.

**Comment by kdudka** [comment]
On Friday, November 25, 2016 01:25:04 Daniel Stenberg wrote:
> Right, so should we instead go for allowing a **minimum** and a **maximum**
> version in the API? Thus having the application set the range? 

Exactly.  I am not sure how many TLS backends support such a level of control 
but at least with NSS it would be possible to 1:1 map such libcurl API to the 
corresponding NSS API.

Kamil

**Comment by jkralik** [comment]
Hi Daniel and Kamil

I implement the feature as we talked 3 weeks ago. I tested it with openssl, gnutls and nss. Please, could someone review the attached patch?

Thx
BTW:
cyassl, axtls doesn't support this feature.

Jozef
[0001-Added-flags-CURL_SSLVERSION_OR_UP_TO_-to-CURLOPT_SSL.txt](https://github.com/curl/curl/files/650060/0001-Added-flags-CURL_SSLVERSION_OR_UP_TO_-to-CURLOPT_SSL.txt)

**Comment by jkralik** [comment]
Hi
Is there any progress, please?
Thx

**Comment by kdudka** [comment]
On Friday, December 16, 2016 02:07:30 Jozef Kralik wrote:
> Hi
> Is there any progress, please?
> Thx

Sorry, I have been too busy before the winter vacation, will have a look
at this next week unless someone is faster than me...

Kamil

**Comment by jkralik** [comment]
Ok. Thx

**Comment by bagder** [comment]
It is easier for us if you submit patches as pull request, then we can comment and review the code inline already here on github. And as we're in a feature freeze until Dec 21 we can't merge this until after that point in time anyway!

**Comment by jkralik** [comment]
Thanks for information and I created pull request for review: https://github.com/curl/curl/pull/1166

**Comment by bagder** [comment]
We've added CURL_SSLVERSION_MAX_* constants to CURLOPT_SSLVERSION that will ship in 7.54.0
