### ISSUE TITLE
Hyper CI build is running out of disk space

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11377]
The Hyper CI build on GHA has been failing regularly lately, and the [latest build](https://github.com/curl/curl/actions/runs/5348954251) provides a pretty good clue as to why:
```
hyper
The hosted runner: GitHub Actions 91 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

hyper
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB
```
The build fails in the `run tests` step, well after Hyper and curl have been built, so it's probably sufficient to delete the Hyper sources after it's built to recover some space.

**Comment by dfandrich** [comment]
I tried a [build](https://github.com/curl/curl/actions/runs/5366355632/jobs/9735735590) with code to clean up the Hyper sources and rust dependencies that it downloads before running the tests, but it didn't help with the disk space warnings. It may be that that the Hyper build has some super verbose logging enabled that rapidly fills up the disk, or it may be something completely different.

**Comment by icing** [comment]
I see an infinite loop with hyper in tests, just filling up the trace log. Investigating.
