### ISSUE TITLE
Extremely weird ipv6 behavior

### ISSUE THREAD

**Issue by sethvargo** [curl/curl#11388]
### I did this

Background context: we recently had a power outage. When my network came back online, apparently our ISP also deployed IPv6. However, this seems to be causing very strange behavior with `curl`.

```text
$ curl --disable -v https://github.com

*   Trying [2606:4700:3037::6815:5267]:443...
* Connected to github.com (2606:4700:3037::6815:5267) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* OpenSSL/3.1.1: error:0A000410:SSL routines::sslv3 alert handshake failure
* Closing connection 0
curl: (35) OpenSSL/3.1.1: error:0A000410:SSL routines::sslv3 alert handshake failure
```

Here's the full dump:

```text
== Info:   Trying [2606:4700:3037::6815:5267]:443...
== Info: Connected to github.com (2606:4700:3037::6815:5267) port 443 (#0)
== Info: ALPN: offers h2,http/1.1
=> Send SSL data, 5 bytes (0x5)
0000: 16 03 01 02 00                                  .....
== Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: 01 00 01 fc 03 03 e5 5a 2d 78 cd ff 25 24 d3 3f .......Z-x..%$.?
0010: d0 fa 72 16 11 d9 48 8e d5 17 51 1e e4 fb 6f d3 ..r...H...Q...o.
0020: 6d 8e 4e ec af 5f 20 06 99 94 40 9f a7 d0 04 56 m.N.._ ...@....V
0030: 76 da 71 0d 25 a9 f2 91 10 e3 ab bb 4a ab d8 cf v.q.%.......J...
0040: 9d a7 4f c8 00 5a 64 00 3e 13 02 13 03 13 01 c0 ..O..Zd.>.......
0050: 2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00 ,.0.........+./.
0060: 9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0 ..$.(.k.#.'.g...
0070: 14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00 ..9.....3.....=.
0080: 3c 00 35 00 2f 00 ff 01 00 01 75 00 00 00 0f 00 <.5./.....u.....
0090: 0d 00 00 0a 67 69 74 68 75 62 2e 63 6f 6d 00 0b ....github.com..
00a0: 00 04 03 00 01 02 00 0a 00 16 00 14 00 1d 00 17 ................
00b0: 00 1e 00 19 00 18 01 00 01 01 01 02 01 03 01 04 ................
00c0: 00 10 00 0e 00 0c 02 68 32 08 68 74 74 70 2f 31 .......h2.http/1
00d0: 2e 31 00 16 00 00 00 17 00 00 00 31 00 00 00 0d .1.........1....
00e0: 00 2a 00 28 04 03 05 03 06 03 08 07 08 08 08 09 .*.(............
00f0: 08 0a 08 0b 08 04 08 05 08 06 04 01 05 01 06 01 ................
0100: 03 03 03 01 03 02 04 02 05 02 06 02 00 2b 00 05 .............+..
0110: 04 03 04 03 03 00 2d 00 02 01 01 00 33 00 26 00 ......-.....3.&.
0120: 24 00 1d 00 20 b2 d8 2a 3b e7 40 26 80 03 4c 85 $... ..*;.@&..L.
0130: 51 82 15 ff 44 85 45 4f 1d 34 58 c3 6c a4 fd c3 Q...D.EO.4X.l...
0140: 8d 54 46 68 12 00 15 00 b7 00 00 00 00 00 00 00 .TFh............
0150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
<= Recv SSL data, 5 bytes (0x5)
0000: 15 03 01 00 02                                  .....
== Info: TLSv1.3 (IN), TLS alert, handshake failure (552):
<= Recv SSL data, 2 bytes (0x2)
0000: 02 28                                           .(
== Info: OpenSSL/3.1.1: error:0A000410:SSL routines::sslv3 alert handshake failure
== Info: Closing connection 0
```

Note that `2606:4700:3037::6815:5267` is not actually a valid IPv6 address for github.com. The same happens for twitter.com or any website that does not actually have AAAA records.

- Notably, sites that _do_ have AAAA records work just fine (google.com, seth.dev).

- Forcing ipv4 with `-4` will "fix" the issue.

- Another computer on the same exact network does _not_ have this problem, so I'm extra extra confused.

Other useful info:

```text
$ dig github.com +short

140.82.112.4
```

```text
$ dig AAAA github.com +short

# empty
```

```text
$ scutil --dns

DNS configuration

resolver #1
  search domain[0] : admins
  nameserver[0] : 2600:4041:4ad:ea01::1
  nameserver[1] : 10.0.10.1
  if_index : 15 (en0)
  flags    : Request A records, Request AAAA records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

# ...
```

```text
$ ping github.com

PING github.com (140.82.112.4): 56 data bytes
64 bytes from 140.82.112.4: icmp_seq=0 ttl=51 time=20.795 ms
64 bytes from 140.82.112.4: icmp_seq=1 ttl=51 time=15.069 ms
# truncate
```

I've also repeatedly flushed the DNS:

```text
$ dscacheutil -flushcache; killall -HUP mDNSResponder
```

And tried restarting multiple times.

### I expected the following

Curl should not erroneously resolve to invalid IPv6 addresses.

### curl/libcurl version

```text
curl 8.1.2 (aarch64-apple-darwin22.4.0) libcurl/8.1.2 (SecureTransport) OpenSSL/3.1.1 zlib/1.2.11 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.54.0 librtmp/2.3
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

(but I have tried every combo of system curl and openssl/libressl)

### operating system

Mac OS X, occurs on both homebrew curl and system curl and openssl curl and libressl curl

```text
Darwin comp.admins 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
```

**Comment by icing** [comment]
curl asks the system for the IP addresses of the domain. It then tries the addresses provided. The first TCP connect then clears all other attempts. And the TLS handshake continues. In your case that one then fails, as whoever is talking at the other end is not the valid server.

It seems to me that everything works as it should. If your system gives the wrong addresses, for whatever reasons in your configuration, this is not a curl mistake.

Unless I misread your report, what do you expect curl to do?

**Comment by sethvargo** [comment]
Hi @icing - thank you for the reply. 

> curl asks the system for the IP addresses of the domain

What syscall(s) is it using? As you can see in the output, `dig` and `ping` both correctly resolve github.com to the IPv4 address but `curl` is resolving to an invalid IPv6 address.

> Unless I misread your report, what do you expect curl to do?

I guess I expect `curl` to resolve the address the same as `dig` or `ping` or the browser.

**Comment by sethvargo** [comment]
Also note this _only_ happens if my Mac has an IPv6 address and curl tries to use IPv6. If I disable IPv6 in the adapter, curl works fine. If I force curl to use IPv4 (with `-4`), it works fine.

**Comment by bagder** [comment]
> What syscall(s) is it using?

getaddrinfo() on modern platforms (including macOS) - and it can be noted that curl and its name resolving works for quite a large number of users and the name resolving code has basically remained the same for several years.

**Comment by bagder** [comment]
Since you are alone with this problem, the curl functions for this have remained the same for a long time and github.com has work like this for a long time, I think everything here points to this being a problem in your specific system or network and not in curl.

We need a way to reproduce this elsewhere in order to act on it, and I cannot.

**Comment by sethvargo** [comment]
Hi @bagder understood. I have other computers on the same network with the same version of curl that are working fine, and curl was working fine for years before. I'll deal with it.
