### ISSUE TITLE
curl_easy_getinfo – HTTP request/response stages: request sending, response awaiting, and response receiving times

### ISSUE THREAD

**Issue by gzzz** [curl/curl#1138]
Hello.

If we using curl_easy_getinfo, we can try to figure out some HTTP request/response stages duration:
`DNS_resolve = time_namelookup`
`TCP_IP_connection = time_connect - time_namelookup`
`SSL_SSH_handshake = time_appconnect - time_connect` (if time_appconnect > 0)
`redirects = time_redirect`

The question is: how to figure out request send time (include POST data) and duration of a server response generation?

I've did some tests:
`curl -w "%{time_namelookup}:%{time_connect}:%{time_appconnect}:%{time_pretransfer}:%{time_redirect}:%{time_starttransfer}:%{time_total}" --data "@post-data.txt" -o NUL -s http://httpbin.org/delay/3`
post-data.txt – 13.7 MB text file.

Results:
```
time_namelookup	time_connect	time_appconnect	time_pretransfer	time_redirect	time_starttransfer	time_total
0,015	0,156	0,000	0,156	0,000	0,281	24,164
0,016	0,156	0,000	0,156	0,000	0,297	23,588
0,000	0,140	0,000	0,140	0,000	0,280	23,681
```

So, as we can see `time_starttransfer - time_pretransfer` does **not** contains request sending.
And also we can not count on `responce_receiveing = time_total - time_starttransfer`, because it **is** contains request sending.
3 seconds of server response “generation” is lost to.

Where is no way to figure out all this stages:
1. DNS resolve
2. TCP/IP connection
3. SSL/SSH handshake
4. request sending
5. response awaiting (request parsing and response generation on the server)
6. response receiving
?

**Comment by bagder** [comment]
Sorry, I don't understand the point of this. You can't extract all the info you want? I suggest you then instead look into how what's necessary to make curl able to provide that info.

**Comment by gzzz** [comment]
> Sorry, I don't understand the point of this. You can't extract all the info you want?

Yes, i can't.

I have a crawler, based on Curl. I want to do requests and collect information about request/response stages and its durations, to provide statistic about websites performance to webmasters.

Curl does not provide that information, only time points (except redirect_time – it is duration, not time point) of some operations. Even this time points does not contains info that i looking for.

> I suggest you then instead look into what's necessary to make curl able to provide that info.

I understand that there may be limitations of different protocols that curl supports.
How i can help Curl to collect and provide that kind of information?

**Comment by bagder** [comment]
> How i can help Curl to collect and provide that kind of information?

Suggest what code changes we need to do to support what you'd like to see, ideally as a pull request. If you can't do a PR, I suggest you take the discussion to the curl-library mailing list where it will reach a much wider audience. This issue tracker is for tracking "issues" in curl, not discussing new or expanded features.

Remember that we cannot break existing code or functionality so when you suggest improvements, they need to maintain the old behavior for the existing apps relying on that behavior.
