### ISSUE TITLE
Non-blocking mode when POSTing multipart/form-data

### ISSUE THREAD

**Issue by Konstantinusz** [curl/curl#1139]
### I did this

curl -# http://example.com/archive.zip | curl -# http://example.com/fileupload.php -F "file=@-"

### I expected the following

In this case one should see two hash mark process indicator running in the same time, syncronously. However I can see one hash mark process indicator for the download process and then another one hash mark process indicator for the upload / POSTing process which upload the data as a multipart/form-data.

Archive.zip file is stored in the memory, I think, and if the file archive.zip is big enough, then I get a pipe broken error message, because memory and virtual memory both became full. 

I have read in the manual that for FTP file upload (option -T) there is a non-blocking form, and one should use a single dot (.) instead of a "-" minus sign to use the non-blocking mode, when reading from the pipe.

Maybe a similar non-blocking mode for the http posting and file upload would be also helpful in such scenarios.

### curl/libcurl version

curl 7.51.0 (i686-pc-linux-gnu) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

[curl -V output perhaps?]
### operating system
I am on Arch Linux 4.8.8-2-ARCH

**Comment by bagder** [comment]
To quote the comment in `lib/formdata.c`:

~~~
            /* When uploading from stdin, we can't know the size of the file,
             * thus must read the full file as before. We *could* use chunked
             * transfer-encoding, but that only works for HTTP 1.1 and we
             * can't be sure we work with such a server.
             */
~~~

So sure, it can certainly be done but nobody has done the job yet. So this is actually working as intended right now. I personally do not plan to work on this in the short term so unless someone feels like starting on this, it will probably get added to the TODO soonish and this issue gets closed.

**Comment by Konstantinusz** [comment]
I see, when using named pipe with header "Transfer-Encoding: chunked" and maybe setting "Content-length:" to empty, this issue doesn't appear. One can upload files on the fly, coming from the named pipe. This is a temporary workaround.
