### ISSUE TITLE
Possible memory leak uploading to SCP

### ISSUE THREAD

**Issue by lsabouri74** [curl/curl#11401]
### I did this
    I run the following code in a loop while monitoring memory usage and I can detect a slow leak:
    const curl_off_t file_size = boost::filesystem::file_size( SrcFile.FileName() );
    FILE* src_file = fopen( Iti::ToSingle( SrcFile.FileName() ).c_str(), "rb" );
    ON_BLOCK_EXIT( &fclose, src_file ); // calls fclose when getting out of scope

    CURL* handle = curl_easy_init();
    curl_easy_setopt(handle , CURLOPT_READDATA, src_file );
    curl_easy_setopt(handle , CURLOPT_UPLOAD, 1L );
    curl_easy_setopt(handle , CURLOPT_INFILESIZE_LARGE, (curl_off_t)file_size );
    // URL is scp:// url
    curl_easy_setopt(handle , CURLOPT_URL, url.c_str() );
    curl_easy_setopt(handle , CURLOPT_USERNAME, UserName.c_str() );
    curl_easy_setopt(handle , CURLOPT_PASSWORD, UserPassword.c_str() );
    curl_easy_setopt(handle , CURLOPT_FTP_CREATE_MISSING_DIRS, 1L );

    CURLcode curl_res = curl_easy_perform( handle );
    
    curl_easy_cleanup(handle);

Using debugging tools for Windows, it reports the following stack trace to leak:

	...
        XMSmtpGateway!socket_open+11A (common\3rd\curl-8.1.2\lib\cf-socket.c, 276)
	XMSmtpGateway!cf_socket_open+D1 (common\3rd\curl-8.1.2\lib\cf-socket.c, 961)
	XMSmtpGateway!cf_tcp_connect+D8 (common\3rd\curl-8.1.2\lib\cf-socket.c, 1126)
	XMSmtpGateway!Curl_conn_cf_connect+79 (common\3rd\curl-8.1.2\lib\cfilters.c, 296)
	XMSmtpGateway!baller_connect+9E (common\3rd\curl-8.1.2\lib\connect.c, 548)
	XMSmtpGateway!is_connected+154 (common\3rd\curl-8.1.2\lib\connect.c, 603)
	XMSmtpGateway!cf_he_connect+19D (common\3rd\curl-8.1.2\lib\connect.c, 901)
	XMSmtpGateway!Curl_conn_cf_connect+79 (common\3rd\curl-8.1.2\lib\cfilters.c, 296)
	XMSmtpGateway!cf_setup_connect+C2 (common\3rd\curl-8.1.2\lib\connect.c, 1196)
	XMSmtpGateway!Curl_conn_connect+144 (common\3rd\curl-8.1.2\lib\cfilters.c, 351)
	XMSmtpGateway!multi_runsingle+863 (common\3rd\curl-8.1.2\lib\multi.c, 2109)
	XMSmtpGateway!curl_multi_perform+181 (common\3rd\curl-8.1.2\lib\multi.c, 2745)
	XMSmtpGateway!easy_transfer+9E (common\3rd\curl-8.1.2\lib\easy.c, 660)
	XMSmtpGateway!easy_perform+1B3 (common\3rd\curl-8.1.2\lib\easy.c, 750)
        ...

### I expected the following
I expect memory to be be stable

### curl/libcurl version
curl-8.1.2
libssh2-1.11.0
openssl-3.1.1

### operating system
Windows 10 Pro

**Comment by dfandrich** [comment]
> Using debugging tools for Windows, it reports the following stack trace to
> leak:
> 
> ...
>     XMSmtpGateway!socket_open+11A (common\3rd\curl-8.1.2\lib\cf-socket.c, 276)

This line is a "socket" call; it's not a memory allocation function. What
memory do you find is leaking? Are you sure it's a leak and not just the normal
work of the memory allocator as memory becomes fragmented?

**Comment by lsabouri74** [comment]
I stripped part of the stack track for clarity here is what is below socket_open:

	ntdll!RtlDebugAllocateHeap+3B
	ntdll!RtlpAllocateHeap+F5
	ntdll!RtlpAllocateHeapInternal+A2D
	KERNELBASE!GlobalAlloc+83
	WS2_32!WahInsertHandleContext+160
	WS2_32!WPUModifyIFSHandle+186
	mswsock!WSPSocket+28A
	WS2_32!WSASocketW+130
	WS2_32!socket+6E
	XMSmtpGateway!socket_open+11A (common\3rd\curl-8.1.2\lib\cf-socket.c, 276)
	...

Maybe the socket is not closed and whatever Windows allocate with the socket is not freed... I did not check if we are leaking sockets... I will take a look.

**Comment by lsabouri74** [comment]
I did some more runs and I got another stack trace:

	ntdll!RtlDebugAllocateHeap+3B
	ntdll!RtlpAllocateHeap+F5
	ntdll!RtlpAllocateHeapInternal+A2D
	ntdll!TpAllocWait+8C
	ntdll!RtlRegisterWait+19F
	KERNELBASE!RegisterWaitForSingleObjectEx+47
	bcrypt!RegisterReopenWait+50
	bcrypt!BCryptGenRandom+1F3
	XMSmtpGateway!ossl_pool_acquire_entropy+6B (common\3rd\openssl-3.1.1\providers\implementations\rands\seeding\rand_win.c, 75)
	XMSmtpGateway!seed_src_generate+EA (common\3rd\openssl-3.1.1\providers\implementations\rands\seed_src.c, 114)
	XMSmtpGateway!seed_get_seed+14A (common\3rd\openssl-3.1.1\providers\implementations\rands\seed_src.c, 205)
	XMSmtpGateway!get_entropy+160 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 243)
	XMSmtpGateway!ossl_prov_drbg_reseed+320 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 574)
	XMSmtpGateway!ossl_prov_drbg_generate+2D1 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 669)
	XMSmtpGateway!ossl_drbg_get_seed+130 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 178)
	XMSmtpGateway!get_entropy+160 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 243)
	XMSmtpGateway!ossl_prov_drbg_reseed+320 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 574)
	XMSmtpGateway!ossl_prov_drbg_generate+2D1 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg.c, 669)
	XMSmtpGateway!drbg_ctr_generate_wrapper+69 (common\3rd\openssl-3.1.1\providers\implementations\rands\drbg_ctr.c, 460)
	XMSmtpGateway!evp_rand_generate_locked+1E8 (common\3rd\openssl-3.1.1\crypto\evp\evp_rand.c, 558)
	XMSmtpGateway!EVP_RAND_generate+71 (common\3rd\openssl-3.1.1\crypto\evp\evp_rand.c, 580)
	XMSmtpGateway!RAND_bytes_ex+E1 (common\3rd\openssl-3.1.1\crypto\rand\rand_lib.c, 372)
	XMSmtpGateway!RAND_bytes+38 (common\3rd\openssl-3.1.1\crypto\rand\rand_lib.c, 382)
	XMSmtpGateway!_libssh2_openssl_random+43 (common\3rd\libssh2-1.11.0\src\openssl.c, 101)
	XMSmtpGateway!kexinit+40B (common\3rd\libssh2-1.11.0\src\kex.c, 3195)
	XMSmtpGateway!_libssh2_kex_exchange+193 (common\3rd\libssh2-1.11.0\src\kex.c, 3870)
	XMSmtpGateway!session_startup+227 (common\3rd\libssh2-1.11.0\src\session.c, 735)
	XMSmtpGateway!libssh2_session_handshake+3E (common\3rd\libssh2-1.11.0\src\session.c, 826)
	XMSmtpGateway!ssh_statemach_act+188 (common\3rd\curl-8.1.2\lib\vssh\libssh2.c, 1005)
	XMSmtpGateway!ssh_multi_statemach+6F (common\3rd\curl-8.1.2\lib\vssh\libssh2.c, 3100)
	XMSmtpGateway!protocol_connecting+90 (common\3rd\curl-8.1.2\lib\multi.c, 1689)
	XMSmtpGateway!multi_runsingle+A13 (common\3rd\curl-8.1.2\lib\multi.c, 2155)

Maybe the leak is in libssh2 or openssl. One note though, if I use SFTP instead of SCP, I don't have a leak.

**Comment by bagder** [comment]
Please provide us with a complete example that leaks memory. We run many tests with SCP that do not leak anything.

**Comment by lsabouri74** [comment]
I was able to isolate the issue and I can confirm it is not in curl. So I am closing this issue. Sorry for the inconvenience.
