### ISSUE TITLE
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssh2 -lssl -lcrypto -R/usr/lib -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -lzstd  -lz,   when use libssh2 version 1.11.0

### ISSUE THREAD

**Issue by HarinadhD** [curl/curl#11403]
### I did this
I am trying to build curl 8.1.1 with libssh2 version 1.11.0

%configure \
    --disable-static \
    --enable-threaded-resolver \
    --enable-hidden-symbols \
    --with-ssl \
    --with-gssapi \
    --with-libssh2 \
    --with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt

I am able to build curl with 8.0.1 and libssh2 1.11.0
But getting below configure error with curl 8.1.1

configure: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure: pkg-config: SSL_LDFLAGS: ""
configure: pkg-config: SSL_CPPFLAGS: ""
checking for HMAC_Update in -lcrypto... yes
checking for SSL_connect in -lssl... yes
checking for openssl/x509.h... yes
checking for openssl/rsa.h... yes
checking for openssl/crypto.h... yes
checking for openssl/pem.h... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for RAND_egd... yes
checking for BoringSSL... no
checking for AWS-LC... no
checking for libressl... no
checking for OpenSSL >= v3... yes
checking for "/dev/urandom"... yes
checking for SRP support in OpenSSL... yes
configure: built with one SSL backend
checking default CA cert bundle/path... /etc/pki/tls/certs/ca-bundle.crt
checking whether to use builtin CA store of SSL library... no
checking for library containing psl_builtin... no
configure: WARNING: libpsl was not found
checking for library containing gsasl_init... no
configure: WARNING: libgsasl was not found
checking for x86_64-unknown-linux-gnu-pkg-config... (cached) /bin/pkg-config
checking for libssh2 options with pkg-config... found
checking for libssh2_session_block_directions in -lssh2... no
checking for libssh2.h... yes
checking for RTMP_Init in -lrtmp... no
checking whether versioned symbols are wanted... no
checking whether to enable Windows native IDN (Windows native builds only)... no
checking whether to build with libidn2... (assumed) yes
checking for x86_64-unknown-linux-gnu-pkg-config... (cached) /bin/pkg-config
checking for libidn2 options with pkg-config... no
configure: IDN_LIBS: "-lidn2"
configure: IDN_LDFLAGS: ""
configure: IDN_CPPFLAGS: ""
configure: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... no
checking for idn2.h... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
checking for x86_64-unknown-linux-gnu-pkg-config... (cached) /bin/pkg-config
checking for libnghttp2 options with pkg-config... no
checking for nghttp2_session_set_local_window_size in -lnghttp2... no
checking for x86_64-unknown-linux-gnu-pkg-config... (cached) /bin/pkg-config
checking for fish options with pkg-config... no
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for sys/ioctl.h... yes
checking for sys/uio.h... yes
checking for unistd.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for arpa/inet.h... yes
checking for net/if.h... yes
checking for netinet/in.h... yes
checking for netinet/in6.h... no
checking for sys/un.h... yes
checking for linux/tcp.h... yes
checking for netinet/tcp.h... yes
checking for netinet/udp.h... yes
checking for netdb.h... yes
checking for sys/sockio.h... no
checking for sys/stat.h... (cached) yes
checking for sys/param.h... yes
checking for termios.h... yes
checking for termio.h... yes
checking for fcntl.h... yes
checking for io.h... no
checking for pwd.h... yes
checking for utime.h... yes
checking for sys/utime.h... no
checking for sys/poll.h... yes
checking for poll.h... yes
checking for socket.h... no
checking for sys/resource.h... yes
checking for libgen.h... yes
checking for locale.h... yes
checking for stdbool.h... yes
checking for arpa/tftp.h... yes
checking for sys/filio.h... no
checking for sys/wait.h... yes
checking for setjmp.h... yes
checking for an ANSI C-conforming const... yes
checking for compiler support of C99 variadic macro style... yes
checking for compiler support of old gcc variadic macro style... yes
checking for size_t... yes
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for struct timeval... yes
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssh2 -lssl -lcrypto -R/usr/lib -lssl -lcrypto -lssl -lcrypto -lgssapi_krb5 -lzstd  -lz

### I expected the following
curl should build without any errors 
### curl/libcurl version

[curl -V output]

### operating system
root@photon4 [ / ]# uname -a
Linux photon4 5.10.109-2.ph4 #1-photon SMP Sat May 14 03:01:41 UTC 2022 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
This typically happens when using a dynamic library that's installed in a
nonstandard location where the run-time linker can't found it. Looking at the
config.log file should give a clue as to which one. The most straightforward
way to fix it is to add the location of the library to /etc/ld.so.conf or set
the LD_LIBRARY_PATH variable.

**Comment by HarinadhD** [comment]
> /etc/ld.so.conf

I have tried but still same problem
root@p [ /usr/src/photon/BUILD/curl-8.1.1 ]# ls -l /lib/libssh2.so*
lrwxrwxrwx 1 root root     16 Jul  6 05:34 /lib/libssh2.so -> libssh2.so.1.0.1
lrwxrwxrwx 1 root root     16 Jul  6 05:34 /lib/libssh2.so.1 -> libssh2.so.1.0.1
-rwxr-xr-x 1 root root 319888 Jul  6 05:34 /lib/libssh2.so.1.0.1
root@p [ /usr/src/photon/BUILD/curl-8.1.1 ]# cat /etc/ld.so.conf
#       Begin /etc/ld.so.conf
/usr/local/lib
/lib/
/lib64/
/opt/lib
include /etc/ld.so.conf.d/*.conf
root@p [ /usr/src/photon/BUILD/curl-8.1.1 ]# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/

But configure was successful without libssh2 ("--with-libssh2")

**Comment by HarinadhD** [comment]
Gcc 12.2.0  : 
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libssh2 options with pkg-config... found
checking for libssh2_session_block_directions in -lssh2... yes
checking for libssh2.h... yes

Gcc 10.2.0  :  
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libssh2 options with pkg-config... found
checking for libssh2_session_block_directions in -lssh2... no
checking for libssh2.h... yes

**Comment by bagder** [comment]
To me, this rather hints that your gcc 10 installation is broken. The configure script of course works identically independent of those two different gcc versions.

**Comment by vszakats** [comment]
We fixed something recently in libssh2 that might be related:
https://github.com/libssh2/libssh2/commit/1209c16d93cba3c5e0f68c12fa4a5049f49c00d8

**Comment by outkastm** [comment]
this has fixed the issue for me, thanks
