### ISSUE TITLE
Connection kept open and used in subsequent connections even if client sends Connection: close

### ISSUE THREAD

**Issue by lucasnetau** [curl/curl#11418]
### I did this

- HTTP request sent with header 'Connection: close' send by client
- server responded 200 without Connection header set and server did not close the connection
- Curl kept the connection open. It was reused on subsequent requests

### I expected the following

Curl to close the client connection even if the server does not close the connection nor send the header.

Per RFC7230 I expected the client to close the connection as it is the sender of the Connection close header.

https://datatracker.ietf.org/doc/html/rfc7230#section-6.1

> The "close" connection option is defined for a sender to signal that
   this connection will be closed after completion of the response

https://datatracker.ietf.org/doc/html/rfc7230#section-6.6  (and the updated https://datatracker.ietf.org/doc/html/rfc9112#section-9.6)

> The Connection header field ([Section 6.1](https://datatracker.ietf.org/doc/html/rfc7230#section-6.1)) provides a "close"
>    connection option that a sender SHOULD send when it wishes to close
>    the connection after the current request/response pair

> A client that sends a "close" connection option MUST NOT send further
>    requests on that connection (after the one containing "close") and
>    MUST close the connection after reading the final response message
>    corresponding to this request.

### curl/libcurl version

curl 7.88.1 (x86_64-apple-darwin22.0) libcurl/7.88.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets

### operating system

Darwin iMac.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
libcurl does not expect the application to communicate its desires by HTTP headers (except in some rare circumstances). It provides dedicated API calls or options for that. To not reuse a connection after a transfer, like you seem to wish here, you set [CURLOPT_FORBID_REUSE](https://curl.se/libcurl/c/CURLOPT_FORBID_REUSE.html).

But sure, libcurl *could perhaps* be made to do the same if a `Connection: close` header is passed in. It would just be very quirky as it assumes the app has (more) knowledge of the protocol and it assumes that the transfer is going to use some specific HTTP versions where this works etc. I think using the dedicated API is way better.

**Comment by lucasnetau** [comment]
Adding CURLOPT_FORBID_REUSE is exactly what I did as a workaround if my library sees the Connection: close header being set. I hit this particular issue when making a request to a test server that specifically didn't close the connection to trip up clients causing the test framework to hang until the connections closed due to inactivity timeout (which needed to be done from the server side, I couldn't find a CURLOPT that specifies how long to persist a connection for before closing.

Fair enough on the other points. Connection header is the special connection management header where it controls the transport connection and not the HTTP request so I thought I would raise it here (and Connection: upgrade for websockets).

Perhaps a CURLOPT_RESPECT_CONNECTION_HEADER option that implies CURLOPT_FORBID_REUSE in the case that the header is set to Connection: close?

Thank you for considering.

**Comment by bagder** [comment]
Adding a new setopt option means more code, new tests and more docs to maintain and we still need to provide the old way that hundreds of apps are already using. I don't think adding such an option for this case adds more value than the cost and weight it would add.
