### ISSUE TITLE
wrong signature type Problem with OpenSSL 3.1 on some domains

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#11434]
Let's show you a sample with connecting to www.libxl.com domain, which seems to be affected.
The certificate seems to be modern with SHA-256 with RSA key.

So for some reason, the CURL SSL connection fails:

CURL 8.1.2 with OpenSSL 3.1.1:

  Trying 192.241.129.32:443...
Connected to www.libxl.com (192.241.129.32) port 443 (#0)
ALPN: offers http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (OUT), TLS alert, handshake failure (552):
OpenSSL/3.1.1: error:0A000172:SSL routines::wrong signature type
Closing connection 0

Older CURL 8.0.1 with OpenSSL 1.1.1t works:

  Trying 192.241.129.32:443...
Connected to www.libxl.com (192.241.129.32) port 443 (#0)
ALPN: offers http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
ALPN: server did not agree on a protocol. Uses default.
Server certificate:
 subject: CN=libxl.com
 start date: Dec 18 00:00:00 2022 GMT
 expire date: Dec  8 23:59:59 2023 GMT
 issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
 SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
using HTTP/1.x

In OpenSSL source code, it is around line 1579 in t1_lib.c file:

SSLfatal(s, SSL_AD_HANDSHAKE_FAILURE, SSL_R_WRONG_SIGNATURE_TYPE);

Because ssl_security returns an error.

        !ssl_security(s, SSL_SECOP_SIGALG_CHECK, secbits,
                      md != NULL ? EVP_MD_get_type(md) : NID_undef,
                      (void *)sigalgstr)) {

This call goes to ssl_security_default_callback, since curl doesn't have its own callback installed (which is okay).

And there the bits are checked:

bits: 64 minbits: 80

So it returns 0 and fails.

I can patch it away:

CURL 8.1.2 with OpenSSL 1.1.1t patched:

  Trying 192.241.129.32:443...
Connected to www.libxl.com (192.241.129.32) port 443 (#0)
ALPN: offers http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.2 (IN), TLS handshake, Certificate (11):
TLSv1.2 (IN), TLS handshake, Server key exchange (12):
TLSv1.2 (IN), TLS handshake, Server finished (14):
TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.2 (OUT), TLS handshake, Finished (20):
TLSv1.2 (IN), TLS handshake, Finished (20):
SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
ALPN: server did not agree on a protocol. Uses default.
Server certificate:
 subject: CN=libxl.com
 start date: Dec 18 00:00:00 2022 GMT
 expire date: Dec  8 23:59:59 2023 GMT
 issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
 SSL certificate verify result: self-signed certificate in certificate chain (19

I can comment out the part with calling ssl_security above and make it work.
We could call SSL_CTX_set_security_level in curl and set level 0 to make it work.
Or I can go to ssl_get_security_level_bits function and reduce from 80 to 64 for the minimum bit count in level 1, which makes it also work.

Does anyone know what is special about this certificate? 
And whether we should change CURL to allow setting the security level for the SSL context?

**Comment by MonkeybreadSoftware** [comment]
seems like people had this earlier:
https://github.com/curl/curl/issues/9186
and maybe also
https://github.com/curl/curl/issues/5138

**Comment by bagder** [comment]
This is OpenSSL and their/your default "seclevel". This is not a curl issue.

You can make it work by lowering the seclevel: `curl https://www.libxl.com  -v --ciphers 'DEFAULT@SECLEVEL=0`

**Comment by MonkeybreadSoftware** [comment]
Thanks. This works.
