### ISSUE TITLE
What is CURLOPT_SOCKS_PROXY* for ?

### ISSUE THREAD

**Issue by bagder** [curl/curl#1144]
We just merged two new socks proxy options in the HTTPS proxy works:

`CURLOPT_SOCKS_PROXY` and `CURLOPT_SOCKS_PROXYTYPE`

... but we already have options to set proxy and set type (including socks types). I read the docs for these new options but there's no explanation in there that explains how these are different to the already existing options. They sound like duplicates of the old options?

Please elaborate what these new options are needed for!

Ping @rousskov and @OkhinVI

**Comment by jay** [comment]
If most of the man pages for the _PROXY variants are the same why not deduplicate them, rather than when we have to make a change in eg CURLOPT_PROXY_CAINFO.3 then the same change has to be made in CURLOPT_CAINFO.3, why not just the latter represent both if all the options are basically the same.

**Comment by bagder** [comment]
If we can dedupe them without making them harder to read, sure. I can't say that I've figured out a way to do that comfortably. But this issue isn't really about duplicated man pages. It is about what seems like duplicated options but I'm pretty sure there are differences...

**Comment by jay** [comment]
ah. ok I haven't been following this one too closely.

**Comment by rousskov** [comment]
@bagder, it looks to me that both `docs/libcurl/opts/CURLOPT_SOCKS_PROXY.3` and
`docs/libcurl/opts/CURLOPT_SOCKS_PROXYTYPE.3` files where added by mistake when other manual pages were added for the new HTTPS proxy options. Please remove them or let us know if you want a PR to remove them.

**Comment by rousskov** [comment]
@bagder, my previous comment about the two manual pages was pretty much wrong. After confirming with @OkhinVI, I am re-answering your original question:

```but we already have options to set proxy and set type (including socks types).```

Before all the https-proxy changes, curl had one option to set the proxy. Thus, curl could support either a socks proxy or an HTTP proxy, but not both. After our changes, curl supports an optional _combination_ of socks and HTTP proxies. This is reflected in section 2 of my original change summary:

```
If both --socks* and --proxy options are given, Curl first connects to
the SOCKS proxy and then connects (through SOCKS) to the HTTP or HTTPS
proxy.
```

To configure such a combination, two options are required where just one option was sufficient before. In other words, we added the --socks* options to specify the SOCKS proxy (and its "type") when a SOCKS proxy is used in combination with an HTTP proxy.

**Comment by bagder** [comment]
That's really not clear in the documentation (which is why I submitted this issue). A few follow-up questions to help clarify:

1. What if a user only wants one SOCKS proxy (and no HTTP one), can this option be used then? If so, is there a difference to using the PROXY options set to be SOCKS? If not, why not?

2. Do we really need a proxytype option for this since we can prefix the host name with the socks type these days?

3. If this option is set and PROXY is set to be a SOCKS proxy, will it chain socks proxies then?

I feel strongly that this option should be renamed to "pre-proxy" or something like that to emphasize that this option is different and how it is different than the regular proxy option.

**Comment by bagder** [comment]
ping @rousskov 

I'm addressing (2) right now by removing the option.

**Comment by bagder** [comment]
BTW, I've now partially reverted curl code so that --socks keep setting the normal proxy variable. Thus --socks and --proxy cannot be used on the same command line as suggested in the original commit for this feature as it would risk breaking existing use cases.

I want it more explicit when pre-proxy is selected so it needs a new option.

**Comment by bagder** [comment]
Now they're **CURLOPT_PRE_PROXY** and **--preproxy**

**Comment by rousskov** [comment]
Sorry for the delay: I incorrectly thought that your three-item question was about another issue that github auto-subscribed me to (the one about environment variables overwriting command line options).

> What if a user only wants one SOCKS proxy (and no HTTP one), can this option be used then? 

Yes, I would expect --socks-proxy to be usable without --proxy. I have not tested that. Please let me know if we should test that.

> If so, is there a difference to using the PROXY options set to be SOCKS?

There is no difference. There are multiple ways to accomplish the same outcome.

> Do we really need a proxytype option for this since we can prefix the host name with the socks type these days?

If the SOCKS proxy type can be specified inside the --preproxy value, then I agree that no special option to configure that type is needed or desirable.


> If this option is set and PROXY is set to be a SOCKS proxy, will it chain socks proxies then?

I do not know or remember. Ideally, it should, but I do not know whether SOCKS proxies can be chained. Please let me know if you want us to test/verify this.

If you like the --preproxy name more than --socks, even though --preproxy does not support HTTP proxies, then who am I to argue?! You are exposed to the variety of use cases that may dictate different naming or side effects than our original design did. We were targeting just two or three use cases (including HTTP proxying through the SOCKS proxy IIRC).

**Comment by bagder** [comment]
> I do not know whether SOCKS proxies can be chained. Please let me know if you want us to test/verify this.

It can't. I haven't actually tried this, but you haven't added logic that makes a double SOCKS connect for that scenario. Or else I am mightily confused. The pre proxy is SOCKS and when a pre proxy is used, the second proxy needs to be a HTTP(S) proxy.

> If you like the --preproxy name more than --socks, even though --preproxy does not support HTTP proxies, then who am I to argue?!

It isn't so much about the name than about the overloading. Before 7.52.0 a user could set the `--proxy` to a proxy (like in a script or environment variable) and then set it again to a SOCKS proxy and then the last use would override the previous uses. You introduced a different meaning for `--socks` than what it used to have so I'm just being careful for such edge use cases. Plus I want it to be more clear to users (or me perhaps) which proxy they're actually specifying. I like to view them as the normal proxy and a possible pre proxy.

I've now also pushed a lot of man page updates for these features.

**Comment by rousskov** [comment]
You are absolutely right. We probably missed the important fact that, prior to our changes, `--socks` was _overwriting_ `--proxy`. In the ideal world, it would not overwrite (it would be a configuration error instead), but we should have noticed that it did and proposed a different mechanism to specify that both proxies are used. Your `--preproxy` solution is probably the best among all the backward compatible ones.

I find it interesting that  `--proxy` documentation in v7.27.0 does not say that `--proxy` overwrites `--socks*` AFAICT but perhaps that was fixed later. The `--socks*` documentation does mention the overwriting effect that we have missed.

**Comment by bagder** [comment]
Thanks for the help, I believe I have the answers now and they have mostly turned into updated docs and code. Closing this!
