### ISSUE TITLE
[GCC, MacOS 11] error: variably modified 'bytes' at file scope

### ISSUE THREAD

**Issue by smessmer** [curl/curl#11441]
Building libcurl with GCC on MacOS 11 fails with

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:42,
                 from /Users/runner/work/cryfs/cryfs/conan-cache/.conan/data/libcurl/8.1.2/_/_/build/2ccaef80415d22fc4aad75d8b407ef2d83097718/src/lib/vtls/sectransp.c:55:
/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:14: error: variably modified 'bytes' at file scope
  193 |         char bytes[kAuthorizationExternalFormLength];
      |              ^~~~~
  CC       vtls/libcurl_la-x509asn1.lo
```

This looks like a resurgence of https://github.com/curl/curl/issues/2651 / https://github.com/curl/curl/issues/2656 but in MacOS 11 this time.

Build Setup:
- Github Actions CI job on runner "macos-11".
- Depending on libcurl 8.1.2 via conan
- GCC versions tested: gcc9 to gcc 13
- Detailed Log: https://github.com/cryfs/cryfs/actions/runs/5549793476/jobs/10134257284

**Comment by bagder** [comment]
So what does it mean? That's an error in a header not provided by curl.

**Comment by smessmer** [comment]
Oh hadn't noticed that. This gets triggered by adding libcurl as a dependency though, and it seems this broken header is included from libcurl sectransp.c:55.

**Comment by bagder** [comment]
Right. And that include has been used by curl since 6d1ea388cb. To me, this rather says that something *other* than curl changed to break this.

**Comment by smessmer** [comment]
Possibly. I'm not sure who or what broke this and I haven't tried to build libcurl before so I don't know when the libcurl build broke.

**Comment by bagder** [comment]
We build curl on macOS several times per days since many years, but this is probably a combination of things that we don't test with so this failure is new to me. I would guess the "macos-11" + gcc combo is key to the problem.

**Comment by bagder** [comment]
I'm not convinced this issue is worth working on. Using an old macOS release to build curl to use secure transport with gcc. As it seems to work fine with a later macOS release and it works with using clang instead of gcc, I think this problem is also easy to work around.

**Comment by pheiduck** [comment]
I have contacted Apple about this issue due we had some issues with cmake and gcc on newer xcode versions.

> Hi Philip,
after reviewing the issue you reported, we found that it should be investigated and fixed by gcc - the third-party software you are using. Contact them and ask for support.
Apple does not supply or support gcc. We only support clang.
