### ISSUE TITLE
Curl tool not following "retry-after" header for redirect request

### ISSUE THREAD

**Issue by yairlenga** [curl/curl#11447]
As per HTTP standard (https://www.rfc-editor.org/rfc/rfc9110#field.retry-after):

> Servers send the "Retry-After" header field to indicate how long the user agent ought to wait before making a follow-up request. When sent with a [503 (Service Unavailable)](https://www.rfc-editor.org/rfc/rfc9110#status.503) response, Retry-After indicates how long the service is expected to be unavailable to the client. When sent with any [3xx (Redirection)](https://www.rfc-editor.org/rfc/rfc9110#status.3xx) response, Retry-After indicates the minimum time that the user agent is asked to wait before issuing the redirected request.

Currently, curl respect the retry-after only for transient error conditions. Per documentation: Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408, 429, 500, 502, 503 or 504 response code

The specific use case is to allow "curl" to follow "retry-after" when fetching API responses for time-consuming operation. The server can redirect the request to same URL, advertising a time when results may be expected. I'm using CURL to retrieve result for long-running calculation, via REST interface, where the server is using 303 with retry-after to implement retries, with backoff logic, based on the progress of the calculation.

Given that curl automatically respect retry-after for error condition - make sense to have this behavior by default (with command line options to override).

Tested with curl 7.29 - I do not have access to newer curl, but per documentation behavior in 8.X is the same as 7.66, when support was added to follow retry-after for error conditions.

**Comment by yairlenga** [comment]
Given it's a simple change. OK for me to submit code fix - for people with commit privilege to review and submit ?

**Comment by dfandrich** [comment]
You are free to open a PR and it will be reviewed. You can also describe your
proposal in more detail here for feedback before you start implementing, in
case the maintainers have some suggestions that would involve lots of rework.

**Comment by bagder** [comment]
It might not be as simple as you think. You need to stow away the handle for N seconds and then bring it back to continue working after that time has elapsed. Remember that libcurl internals are all non-blocking as you might be doing numerous other transfers simultaneously and they should not be negatively impact by the waiting done by a single transfer.

**Comment by bagder** [comment]
I could at that the redirect-following is done in the library code and not in the tool, which makes it more complicated than the existing retry-after logic which is done in the tool only.

**Comment by yairlenga** [comment]
Thank you for suggestion. I will down the code at take a look at the implementation of retry-after for 408, 429 and 525. Hopefully, I can reuse some of the logic.

in case it’s too complex to do it in the library, an reason not to implement it at the curl tool ?

**Comment by bagder** [comment]
> in case it’s too complex to do it in the library, an reason not to implement it at the curl tool ?

redirect following is done by the library

**Comment by Monochrome-debug** [comment]
I want to try the pull request thing again https://github.com/curl/curl/pull/16714
