### ISSUE TITLE
curl with CURLPROXY_SOCKS5 doesn't respect CURLOPT_IPRESOLVE option

### ISSUE THREAD

**Issue by Chilledheart** [curl/curl#11458]
### I did this

```
curl -v -6 --proxy socks5://<proxy-ip>:<proxy-port> http://localhost:43947/ 
```
where localhost is enabled with IPv6 address `::1`.

It outputed:
```
* SOCKS5 connect to IPv4 127.0.0.1:43947 (locally resolved)
```
When gdbing into the issue:
```
  case CONNECT_RESOLVED: {
    struct Curl_addrinfo *hp = NULL;
    size_t destlen;
    if(dns)
      hp = dns->addr;
    if(!hp) {
      failf(data, "Failed to resolve \"%s\" for SOCKS5 connect.",
            sx->hostname);
      return CURLPX_RESOLVE_HOST;
    }

    Curl_printable_address(hp, dest, sizeof(dest));
    destlen = strlen(dest);
    msnprintf(dest + destlen, sizeof(dest) - destlen, ":%d", sx->remote_port);

    len = 0;
```
It seems it used the first dns entry directly

### I expected the following

It should output the dns entries following in `CURLOPT_IPRESOLVE` when doing resolving locally.
```
* SOCKS5 connect to IPv6 [::1]:43947 (locally resolved)
```

### curl/libcurl version

```
curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.9 zlib/1.2.13 zstd/1.5.5 c-ares/1.19.1 nghttp2/1.51.0
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

```
Linux era 6.1.38-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul  6 11:15:11 CST 2023 x86_64 13th Gen Intel(R) Core(TM) i5-13600KF GenuineIntel GNU/Linux
```

**Comment by icing** [comment]
> It seems it used the first dns entry directly

Should it not? Which one should it use in your opinion? 

It seems your curl uses c-ares for name resolving. Is your question then why c-ares gives 127.0.0.1 for localhost?

**Comment by bagder** [comment]
`-6` is in this case controlling what IP version to use for curl's connection, which in this case is done to the proxy. There is in fact no option to ask curl to prefer IPv6 to the proxy to connect to for the given host name. And if I recall things correctly, SOCKS only allows for a single IP address to be provided.

**Comment by Chilledheart** [comment]
> `-6` is in this case controlling what IP version to use for curl's connection, which in this case is done to the proxy. There is in fact no option to ask curl to prefer IPv6 to the proxy to connect to for the given host name. And if I recall things correctly, SOCKS only allows for a single IP address to be provided.

If there are multiple addresses resovled in one domain name, I can use socks5h(HOSTNAME variant) for this case. But it remains implementation-dependent if you happens to use socks5 only (without HOSTNAME), because the local resolved ip address is picked from the very first entry in the result of Curl_resolve.

It took me some time to find out and it would be great if there is document about it.

**Comment by bagder** [comment]
> If there are multiple addresses resovled in one domain name, I can use socks5h(HOSTNAME variant) for this case. 

`socks5h` is the variant that forwards the name to the proxy and then have it resolve. It might certainly make it test multiple addresses if that is what your proxy does.

> But it remains implementation-dependent if you happens to use socks5 only (without HOSTNAME), because the local resolved ip address is picked from the very first entry in the result of Curl_resolve.

How is that "implementation-dependent" ? SOCKS5 allows the client to pass on exactly one single address. Which one do you think it should send if not the first one getaddrinfo() returns?

**Comment by Chilledheart** [comment]
In my memory of `ares_getaddrinfo`, it calls sort routine of the results at the last step. For `Curl_resolv`, I don't know how it works inside. Maybe you can explain more details about it.

**Comment by bagder** [comment]
> it remains a potential issue the behavior of resolving locally and the behavior of resolving remotely differ.

Sure, which is exactly why curl supports both. Everyone using SOCKS needs to make that decision. It's not anything curl can change or have an opinion about.

> It's not

Then you've identified a bug that should be corrected.

> [explanation]

Sure, two different getaddrinfo() implementations might return the addresses in different orders. That would be up to the resolver libraries. That fact that does not change the notion that curl uses the first address that getaddrinfo() returns.

> Maybe it is a problem that I am using the TOT c-ares

I don't know what that is so I have no idea.

> In my memory of ares_getaddrinfo, it calls sort routine of the results at the last step

All implementations of getaddrinfo() should return the addresses in a prio order according to the standards. That probably involves sorting in some way. But curl does not implement getaddrinfo, it assumes that the functions work that way and uses the addresses in the order they are provided: as that is the preferred order.

**Comment by Chilledheart** [comment]
> > it remains a potential issue the behavior of resolving locally and the behavior of resolving remotely differ.
> 
> Sure, which is exactly why curl supports both. Everyone using SOCKS needs to make that decision. It's not anything curl can change or have an opinion about.
> 
> > It's not
> 
> Then you've identified a bug that should be corrected.
> 
> > [explanation]
> 
> Sure, two different getaddrinfo() implementations might return the addresses in different orders. That would be up to the resolver libraries. That fact does not change the notion that curl uses the first address that getaddrinfo() returns.
> 
> > Maybe it is a problem that I am using the TOT c-ares
> 
> I don't know what that is so I have no idea.
> 
> > In my memory of ares_getaddrinfo, it calls sort routine of the results at the last step
> 
> All implementations of getaddrinfo() should return the addresses in a prio order according to the standards. That probably involves sorting in some way. But curl does not implement getaddrinfo, it assumes that the functions work that way and uses the addresses in the order they are provided: as that is the preferred order.

Thanks for the explanation. I know curl doesn't make up of getaddrinfo but it still differs how it uses the api. From my calculation, with c-ares backend, `Curl_resolv` internally calls into `ares_getaddrinfo` where it returns `AF_INET6` address at first, so it should return `AF_INET6` address first. It turns out not.

The only potential usage difference is that I was passing sock_flags `PF_UNSPEC` to `ares_getaddrinfo` while `Curl_resolv` might do `PF_INET` and `PF_INET6` seperately and glue the results manually.

At last, 

|                                                          |                             |                            |                                                         |
|----------------------------------------|--------------------|-------------------|---------------------------------------|
| When I did the curl:                          |      Curl_resolv      | -> getaddrinfo  | -> AF_INET first, AF_INET6 second |
| When I did the c-ares getaddrinfo:  | ...some wrapper... | -> getaddrinfo  | -> AF_INET6 first, AF_INET second |

What I mean implementation-dependent, it is about the wrapper.  You can give [my code][wrapper] a visit although it is C++.

[wrapper]: https://github.com/Chilledheart/yass/blob/develop/src/core/c-ares.cpp#L289

**Comment by Chilledheart** [comment]
As to [`TOT`][tot], it is short of `top of tree`. In my branch of c-ares, it reverts some commits which removes windows xp support and fixes some important recursive lookup on one `ares_getadddrinfo` call. You can give it a look, but except that it should remain almost the same with `1.19.1` release.

[tot]: https://github.com/Chilledheart/c-ares/commits/main

**Comment by bagder** [comment]
https://github.com/curl/curl/blob/f2aac0d108167bee5d06d6f9a307e0ff5193b816/lib/socks.c#L821-L874

**Comment by bagder** [comment]
All of this is now way off what this issue was originally about.

**Comment by Chilledheart** [comment]
Okay then. I will create another issue for the misbehaviour I mentioned in last post.

```
curl -v --proxy socks://proxyip.com:proxyport http://localhost:12345
```

and

```
curl -v http://localhost:12345
```

If the host is enabled with IPv6, the first command will visit `127.0.0.1` while without proxy the second `::1`. Both are resolved locally, and by curl's `Curl_resolv` call.

**Comment by Chilledheart** [comment]
As to the original issue, programatically, if `Curl_resolv` hits dns cache and call `fetch_addr` inside, it will respect `CURLOPT_IPRESOLVE` flag by checking `conn->ip_version`. It is strange that it doesn't do the same while it doesn't if cache miss. Doesn't it mean a potential issue?
 
https://github.com/curl/curl/blob/f2aac0d108167bee5d06d6f9a307e0ff5193b816/lib/hostip.c#L328-L351

Look at the connect.c code, it will respect `CURLOPT_IPRESOLVE`  whatever the dns response is.

https://github.com/curl/curl/blob/f2aac0d108167bee5d06d6f9a307e0ff5193b816/lib/connect.c#L761-L793
