### ISSUE TITLE
When using the -o option, some characters changed

### ISSUE THREAD

**Issue by vadhbka** [curl/curl#11461]
### I did this
cmd
"curl.exe" -o "ポ.html" "https://www.google.com/"
### I expected the following

I expect to run this command and save "ポ.html"
But what was actually saved was "ダ.html"
("ポ" reads po. "ダ" reads da in japanese)
When specifying a path with the -o option, if "ポ" is included, it seems to change to a different character for some reason.
I have confirmed that this bug occurs in version 8.1.2_5, but not in version 8.0.1.

### curl/libcurl version

curl 8.1.2 (x86_64-w64-mingw32) libcurl/8.1.2 OpenSSL/3.1.0 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 WinIDN libssh2/1.11.0 nghttp2/1.55.1 ngtcp2/0.15.0 nghttp3/0.11.0 libgsasl/2.2.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe UnixSockets zstd

### operating system
Windows10 64bit

**Comment by dfandrich** [comment]
What is the curl -V output of the working version?

**Comment by vadhbka** [comment]
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

This version is installed by default on windows 10 64bit. it's works.

**Comment by dfandrich** [comment]
There are some significant differences in the way the two versions were compiled. I suspect the problem has to do with that and not with the curl version number, for example ENABLE_UNICODE may have been selected in one of them.

**Comment by bagder** [comment]
The working version has `Unicode` listed as a feature, the other one doesn't. Unicode on Windows is a long and sad saga that never ends.

**Comment by vadhbka** [comment]
I Understand. Thank you.
I downloaded the version with the problem from the curl project.
there is a difference at compile time, will this problem be fixed?

**Comment by vszakats** [comment]
Yep, both Unicode and non-Unicode builds work either correctly or wrong depending on what one is expecting.

**Comment by vadhbka** [comment]
I understand that there are complicated circumstances with Unicode. Thank you.

**Comment by vszakats** [comment]
> I have confirmed that this bug occurs in version 8.1.2_5, but not in version 8.0.1

I wonder what the reason might be. AFAIK there was no related change in curl between these versions, nor any curl-for-win (official Windows build) updates that might introduce such difference. curl-for-for had Unicode enabled only between mid-2020 to mid-2021 releases.

**Comment by MichalPetryka** [comment]
> One good reason is that it makes the libcurl API behaviour undefined with regards to the expected encoding/codepage of strings accepted and returned.

What do you mean by this? I thought all libcurl APIs used UTF8 for strings?

**Comment by vszakats** [comment]
@MichalPetryka It's not defined in the libcurl documentation. libcurl handles strings transparently, without doing any translations internally. Except in some case (such as terminal output) in Windows non-Unicode builds, and except certain more cases in Windows Unicode builds.

**Comment by jay** [comment]
> AFAIK there was no related (intented) change in curl between these versions, nor any curl-for-win (official Windows build) updates that might introduce such difference. curl-for-win had Unicode enabled only between mid-2020 to mid-2021 releases.

The reporter is using a Unicode build of curl 8.0.1 that comes with Windows and the non-Unicode build of curl 8.1.2 from curl-for-win. So it's probably the lack of Unicode.

I think there's nothing to be done for this issue. However I also think we could add the UTF-8 manifest you proposed to Unicode builds which should improve Unicode support in those builds.

**Comment by vszakats** [comment]
> The reporter is using a Unicode build of curl 8.0.1 that comes with Windows and the non-Unicode build of curl 8.1.2 from curl-for-win. So it's probably the lack of Unicode.

This explains the difference indeed.

> I think there's nothing to be done for this issue. However I also think we could add the UTF-8 manifest you proposed to Unicode builds which should improve Unicode support in those builds.

Reopened #11482.

It's pending on how to update console output to omit translations in the "all-UTF-8" case. (This may not be critical anymore after your fix af3f4e419b9f339790de281c871640a773c391c0)
