### ISSUE TITLE
CHKSTRINGS build failure on OS/400

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#11472]
### I did this

Build libCurl 8.2.0 on OS400

STRING_LASTZEROTERMINATED(78) is not expected value(77).…curl_easy_setopt_ccsid() in packages/OS400/ccsidcurl.c may need updating if new strings are provided as input via the curl API.…ERROR: CHKSTRINGS failed!

I believe the value needs to be updated to STRING_HAPROXY_CLIENT_IP following commit 0a75964.

### I expected the following

Clean build

### curl/libcurl version

8.2.0

### operating system

OS400 V7R4M0

**Comment by dfandrich** [comment]
You may want to contribute to the thread at
https://curl.se/mail/lib-2023-07/0015.html about the lack of CI testing on
OS400.

**Comment by bagder** [comment]
Fixed by #11476
