### ISSUE TITLE
 HTTP/2 POST gives timeout/protocol error after upgrade from 8.1.2 to 8.2.0

### ISSUE THREAD

**Issue by OlekMazur** [curl/curl#11485]
### I did this

I did the same query as in #11194, and found a regression in 8.2.0 compared to 8.1.2.
Full output:
```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
> POST /api/v1/XXXXXX HTTP/2
> Host: eu-gb.functions.appdomain.cloud
> User-Agent: curl/8.2.0
> Accept: */*
> Content-Type: text/csv
> Content-Length: 0
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
     ... stucks here for 60s ...
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

### curl/libcurl version

curl 8.2.0 (x86_64-pc-linux-gnu) libcurl/8.2.0 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 nghttp2/1.52.0
Release-Date: 2023-07-19
Protocols: http https imap imaps smtp smtps
Features: AsynchDNS brotli HTTP2 HTTPS-proxy Largefile libz NTLM SSL threadsafe zstd

### operating system

Linux 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64 GNU/Linux

**Comment by icing** [comment]
I am very sorry that you got hit with that again. Please see #11487 for a fix.

This regression was introduced by c9ec85121110d7cbbbed2990024222c8f5b8afe5 which uncovered a missing internal event for signalling the EOF to the server. Unfortunately, our test servers are too tolerant of such requests to detect this.
