### ISSUE TITLE
CURL reuse connection even host ip has changed

### ISSUE THREAD

**Issue by sin5678** [curl/curl#11498]
### I did this
`

$curl = curl_init();

curl_setopt($curl, CURLOPT_URL, "https://www.google.com");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HEADER, true);
curl_setopt($curl, CURLOPT_NOBODY, true);
curl_setopt($curl, CURLOPT_FOLLOWLOCATION, false); 
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 2); 
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, true); 
curl_setopt($curl, CURLOPT_TIMEOUT, 3); 
curl_setopt($curl, CURLOPT_VERBOSE, true);
//curl_setopt($curl, CURLOPT_FORBID_REUSE, true);
curl_setopt($curl, CURLOPT_DNS_USE_GLOBAL_CACHE, false);
curl_setopt($curl, CURLOPT_RESOLVE, ['www.google.com:443:142.250.207.4']);

curl_exec($curl);

curl_setopt($curl, CURLOPT_RESOLVE, ['www.google.com:443:11.22.33.44']);

curl_exec($curl);

`

### I expected the following

can not get response when use fake IP , but curl returned real response cause reused the connection

### curl/libcurl version

libcurl/7.88.1

### operating system

MacOS

**Comment by bagder** [comment]
Connection reuse in curl is done per host name, independent of IP address. If there is a connection to the given name in the connection pool, that connection will be reused.
