### ISSUE TITLE
curl-8_2_0 error 55 Failed sending data to the peer

### ISSUE THREAD

**Issue by calvin2021y** [curl/curl#11496]
### I did this

use curl with libuv and multi handle,  add https://github.com/curl/curl/pull/11487 patch

### I expected the following

expect it work like 8.12.

### operating system

windows (curent only windows send batch request find this problem, not report by other platform yet)

**Comment by calvin2021y** [comment]
I find there is a `received GOAWAY, error=0, last_stream=599`,  maybe not a curl bugs.

**Comment by bagder** [comment]
Either way, you did not provide enough information for anyone to act on or to assess this claim upon. Please tell us how to reproduce this problem if you think it is a curl issue.

**Comment by calvin2021y** [comment]
Not am not sure "received GOAWAY, error=0, last_stream=599" is a curl issue. the only evidence is the problem raised after I upgrade curl. 

and I get this error:

```sh
HTTP/2 stream 3 was not closed cleanly: PROTOCOL_ERROR (err 1)

92: Stream error in the HTTP/2 framing layer
```

I am connect into cloudflare server,  it also could be server side problem.

**Comment by bagder** [comment]
Sure, but again, you need to provide a lot more information or a recipe to reproduce it as otherwise we cannot do anything and having an issue here that is impossible to act on will just make us close it.
