### ISSUE TITLE
Websocket with curl is not working

### ISSUE THREAD

**Issue by tarkanaktan** [curl/curl#11506]
### I did this

I tried the example code for websocket which is in this link "https://curl.se/libcurl/c/websocket.html". However, it returns "Unsupported protocol error" even if I have libcurl version 8.2.0. Also when I make it http and add headers to upgrade to websocket it works with curl_easy_perform but when I try to do it with curl_multi_perform it doesn't send any request to the server as much as I saw in the network logs. Altough it doesn't send any request curl_multi_perform return CURL_OK. 

### I expected the following

I am expecting the example run succesfully and to see correct network messages. Can you help me with this one?

### curl/libcurl version

curl 8.2.0

### operating system

ubuntu 22.04

**Comment by dfandrich** [comment]
Websocket support is considered experimental and you generally have to build your own libcurl to use it. That would explain the *Unsupported protocol error*. Adding those kind of headers yourself won't enable that support and is usually the wrong thing to do. The error code returned by `curl_multi_perform` isn't the same as the error code for the easy handle. To get the latter, you can call `curl_multi_info_read`.
