### ISSUE TITLE
time_connect is 0 for http3

### ISSUE THREAD

**Issue by nishanthsuraj** [curl/curl#11507]
### I did this

curl --http3-only -o /dev/null -s -w 'total_connect: %{time_connect}\nhttp_version: %{http_version}\n' https://google.com

### I expected the following

total_connect: **>0**
http_version: 3

I was expecting the "**total_connect**" to be more than 0 for **Http3**, which is the case for Http2 and Http1.1

### curl/libcurl version

curl 8.2.0

### operating system

Cent OS 7

**Comment by icing** [comment]
I'll close this issue now, as things seem to be as should. If you disagree, please comment and I'll reopen.

**Comment by nishanthsuraj** [comment]
Sure, Thanks!
