### ISSUE TITLE
Failing the debug callback

### ISSUE THREAD

**Issue by p** [curl/curl#1151]
This was reported to pycurl as https://github.com/pycurl/pycurl/issues/413, however the issue is not straightforward to resolve externally to libcurl.

libcurl expects the debug callback to always succeed. However, in case of Python/other high level language bindings this is not necessarily possible.

The sequence of events triggering the issue in a Python program is as follows:

1. A debug callback is set (and no other callbacks).
2. A curl transfer is started with `curl_easy_perform`.
3. User presses Ctrl-C.
4. Python catches the signal and arranges to raise `KeyboardInterrupt` exception at the next available opportunity. I take it libcurl does not do any signal handling, plus https://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html is a very commonly used/recommended option.
5. libcurl invokes pycurl's debug callback, which is implemented as C code. At this point Python's exception indicator, per Python C api, is not set.
6. pycurl invokes the Python debug callback set in step 1 via `PyEval`.
7. Due to step 4, Python runtime returns immediately (with an error) setting Python exception indicator. The Python debug callback set in step 1 does not seem to be executed at all, although it features in the Python stack trace.
8. pycurl debug callback reports the Python exception but returns success to libcurl.
9. libcurl continues the transfer.
10. When `curl_easy_perform` returns, the return is successful even though the user requested that the program stop itself. The program continues running.

At this point several thoughts/questions come to mind:

<b>Why use the debug callback?</b>

libcurl sends several headers by default with HTTP requests, and these headers are not exposed via its API. The only way for an application to know the exact request that is sent is, seemingly, to install a debug callback and parse the debug output.

<b>Why not handle this at Python level?</b>

This is impossible because the Python debug callback is not executed at all.

<b>Why not install a signal handler at Python level to deal with the signal?</b>

This does technically work but is incredibly ugly plus violates encapsulation and separation of concerns. For any real usage this is untenable.

<b>Why not handle this at pycurl level?</b>

This is the only option I see for making signals work with older libcurls, however it is still messy because there is no way to abort a libcurl request that is in progress <i>outside of a callback</i> (and debug callback is for this purpose "outside of a callback" because the debug callback's return value is ignored by libcurl).

This solution would involve pycurl tracking failures in debug callback invocations and subsequently failing `perform` calls if a debug callback failed. There are 3 problems which is why this solution is messy:

1. libcurl continues the transfer, potentially for a long time, because it is unaware that the user requested the abort. Image the user is downloading a big file and the transfer is working but slowly.
2. pycurl will report successful transfers as failed due to debug callback failures. This is more important for mutating requests (post/put/delete).
3. In order to provide this functionality for multi handles I imagine pycurl will have to loop through all easy handles in a multi handle and check each of those for debug callback failures, and do so on every multi perform invocation (otherwise - if only the multi handle is checked - if there are, for example, new transfers being added to a multi handle the failures would never surface as the multi handle remains continuously in use). One of the tenets of pycurl is low overhead on top of libcurl, and such looping and checking is rather opposite of low overhead.

Therefore I believe libcurl should allow the debug callback to fail, and fail the transfer when this happens.

Now, there is a big compatibility issue with this change in that while libcurl documentation states that the debug callback must return zero this return value up to now has not been looked at, and existing code may well not return anything specifically hence returning garbage. If libcurl begins to check return value of debug callback such client code will result in failed transfers.

Perhaps providing a method or an option to immediately abort a transfer <b>while in a callback</b> can be a good solution.

Another alternative is to provide an API to retrieve headers that libcurl sends by default, or actual sent headers of a request. Then there would be less of a need to use the debug callback although the problem with it would remain.

Thoughts?

### curl/libcurl version

curl 7.49.1 (amd64-portbld-freebsd10.2) libcurl/7.49.1 OpenSSL/1.0.1o zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by bagder** [comment]
The debug callback was documented to always return 0 exactly to allow a future change that would allow it to return something else. Sure that could potentially break an existing wrongly written application, but I really don't think we should cater much for those that so clearly don't follow the documentation. Added a new separate mechanism to accomplish that same thing seems like a much bigger operation that will only lead to even more future applications that can run with older libcurls.

**Comment by bagder** [comment]
This callback is called on many places and the parent function is not checking return code or returning back on error in most of them so adding this feature would be a rather massive change. I will therefore close this for now as I suspect this won't get done by a casual contributors.

However, the recommended work-around is instead to store an "exit now" state in a struct and check that state at entry in other callbacks, especially in the progress/xferinfo callback since that will for sure be called not long after the debug callback and then you can exit from there. Not as instant, but still typically within a subsecond.
