### ISSUE TITLE
Empty user-agent in config file is not allowed.

### ISSUE THREAD

**Issue by absorber** [curl/curl#1152]
### I did this
`echo 'user-agent = ""' | curl -K- ipinfo.io`

### I expected the following
I expected curl to send the HTTP request *without* the `user-agent` string, like when invoking curl like this: `curl --user-agent "" ipinfo.io`

### curl/libcurl version
```
$  curl -V
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

### operating system
Linux Mint 17.2 Rafaela x86_64

**Comment by bagder** [comment]
This problem was fixed in commit cee0fb3247d83d8c07eba62f539c8c0609609c43, to be shipped in the pending 7.52.0 release.
