### ISSUE TITLE
Error with installing CURL 8.2.1 - can not find OpenSSL

### ISSUE THREAD

**Issue by mokjasmine** [curl/curl#11526]
### I did this

I installed ngtcp2 with `vcpkg` and attempted to install curl:

```vcpkg install curl[libressl,http3,ipv6] --triplet x64-windows-webkit```

### I expected the following

I expected success but instead I got the following error:

```
CMake Error at C:/[...]/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "2.0.0")
Call Stack (most recent call first):
  C:/[...]/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/[...]/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindOpenSSL.cmake:613 (find_package_handle_standard_args)
  C:/[...]/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  CMakeLists.txt:430 (find_package)
```

### curl/libcurl version

curl 8.2.1

### operating system

Microsoft Windows [Version 10.0.19044.1645]

**Comment by dfandrich** [comment]
This looks to me like a vcpkg packaging problem that needs to be reported to the packagers.
Does it work if you build curl from source?

**Comment by bagder** [comment]
vcpkg related problems should primiarily be taken up with them: https://github.com/microsoft/vcpkg. That's not a build that we own nor provide.

We provide several different ways to build curl and if you have a problem with one of them, we are interested.
