### ISSUE TITLE
wolfSSL connect, sporadic CI errors

### ISSUE THREAD

**Issue by icing** [curl/curl#11533]
### I did this

Observe pytest jobs in CI like `ngtcp2-wolfssl`.

Some transfers fail during connect with `SSL_connect failed with error -425: The security parameter is invalid` when more than one connection are started at the same time.

### I expected the following

Successfull tests.

### curl/libcurl version

master

**Comment by bagder** [comment]
Do you have an example build log link to such a fail?

**Comment by icing** [comment]
If I disable session-reuse, the CI run works. There were some changes in wolfSSL v5.6.3 regarding session caching.

**Comment by icing** [comment]
@dgarske if you want me to try another revision/commit from wolfSSL, this can easily be done in #11623.

**Comment by dgarske** [comment]
> @dgarske if you want me to try another revision/commit from wolfSSL, this can easily be done in #11623.

@julek-wolfssl is working on it now. He believes the https://github.com/wolfSSL/wolfssl/pull/6686 may not resolve the issue. Would you mind trying it in the 11623 debugging?

**Comment by icing** [comment]
So, it looks as if your PR is working. And then I tested wolfSSL master and that looks also working. The fix must be some change between v5.6.3 and master and not related to your PR.

@bagder: I think we should go to v5.6.0 to have a stable CI and switch to the next wolfSSL when it comes out.

**Comment by icing** [comment]
Tried to switch the CI to v5.6.0 and v5.6.2 - now both show the failure again. Heisenbug. Hm...

**Comment by dgarske** [comment]
New fix in https://github.com/wolfSSL/wolfssl/pull/6697
This should resolve.

**Comment by icing** [comment]
@dgarske got it nailed down locally: 

* curl: starting 3 HTTP/1.1 transfers in parallel
* delaying TCP connects of transfer T1+T2 for 100ms, no delay for transfer T0
* T0 handshakes, session is retrieved and put into curl's cache
* T1 finds session in cache, sets it in its SSL*
* T2 finds session in cache, sets it in its SSL*
* T1 handshakes successfully
* T2 subsequently fails in `tls13.c:5174` with a mismatch in received and expected session id

Log extract with an additional fprintf in `tls13.c:5174` ("[n-m]" denotes transfer "n" on connection "m"):

```
13:18:41.699827 [0-0] * checking for SSL session  in cache
13:18:41.703972 [0-0] * adding SSL session to cache: '' (0x7f9ba00b8000, len=0)
13:18:41.799356 [1-1] * checking for SSL session  in cache
13:18:41.799483 [1-1] * re-using SSL session from cache: 'DJJALpPeV7bFx/uCyMOmCt+4EApktQQfiaNlkJWIm+k=' (0x7f9ba00b8000, len=32)
13:18:41.802799 [2-2] * checking for SSL session  in cache
13:18:41.802924 [2-2] * re-using SSL session from cache: 'DJJALpPeV7bFx/uCyMOmCt+4EApktQQfiaNlkJWIm+k=' (0x7f9ba00b8000, len=32)
13:18:41.804205 [1-1] * SSL session ID is already cached
wolfSSL: SSL session id does not match: theirs=32 our=32
13:18:41.807187 [2-2] * closing SSL session : 'yKc+q5O5O2REWJAll4W8OcBd3AKrLKH9ulUApBSiuGM=' (0x7f9ba00b8000, len=32)
```

Does wolfSSL alter the session id after a successful handshake, confusing connections that share the session?

**Comment by icing** [comment]
Yes, TLSv1.3. If we find a SESSION* in curl's cache, we set it on the SSL* before connecting.

If the session updates on an arriving Ticket, then it should create a new SESSION*, don't you think? Otherwise the application gets the issues we are seeing now, I guess.

For optimal use of a session cache, it would probably be best to register on new tickets and then update the cache. But that seems beside the confusion we are seeing and that fail the handshake.

**Comment by dgarske** [comment]
Are you building wolfSSL with `NO_SESSION_CACHE_REF`? If not can you try with it defined? This will ensure the session cache pointer returned by `wolfSSL_get_session()` is a pointer to the internal cache and not something allocated.

```c
/* NO_SESSION_CACHE_REF:
 *     wolfSSL_get_session on a client will return a reference to the internal
 *     ClientCache by default for backwards compatibility. This define will
 *     make wolfSSL_get_session return a reference to ssl->session. The returned
 *     pointer will be freed with the related WOLFSSL object. */
```

**Comment by icing** [comment]
@dgarske, the following fixes the problem for me:

```
diff --git a/src/internal.c b/src/internal.c
index ca166e8d9..552a8b9c2 100644
--- a/src/internal.c
+++ b/src/internal.c
@@ -30575,6 +30575,15 @@ exit_scv:
 #ifdef HAVE_SESSION_TICKET
 int SetTicket(WOLFSSL* ssl, const byte* ticket, word32 length)
 {
+    /* If the session is shared, we need to copy-on-write */
+    if (ssl->session->ref.count > 1) {
+        WOLFSSL_SESSION* nsession = wolfSSL_SESSION_dup(ssl->session);
+        if (nsession == NULL)
+            return MEMORY_E;
+        wolfSSL_FreeSession(ssl->ctx, ssl->session);
+        ssl->session = nsession;
+    }
+
     /* Free old dynamic ticket if we already had one */
     if (ssl->session->ticketLenAlloc > 0) {
         XFREE(ssl->session->ticket, ssl->heap, DYNAMIC_TYPE_SESSION_TICK);
```

**Comment by dgarske** [comment]
Excellent! You are more than welcome to put that up as a PR

**Comment by icing** [comment]
Status update: we are skipping the flaky wolfssl test in CI for now and added a test case that reproduces the problem reliably. We'll evaluate the next wolfSSL release.

**Comment by bagder** [comment]
The situation seems to be under control now, closing this.
