### ISSUE TITLE
Inclusion of libssh2 via pkg-config causes harmless build warning

### ISSUE THREAD

**Issue by TurtleWilly** [curl/curl#11538]
### I did this

When building `--with-libssh2` a minor warning is triggered during the configure process where the "-L" specification erroneously gets added to LIBS. Also "-lssh2" appears twice (some other libraries like ssl+crypto, zstd, z, and brotlidec also appear multiple times for some reason, but that doesn't trigger warnings at least.)

```
$ ./configure \
	--prefix=/usr/local/mystuff/curl/8.2.1 \
	--with-openssl \
	--with-libssh2 \
	--with-brotli \
	…
```

->

```
…
configure: using LIBS: -lcares -lnghttp2 -lidn2 -lrtmp -lz -lssl -lcrypto -lssh2 -L/usr/local/mystuff/libssh2/latest/lib -lssh2 -lssl -lcrypto -lssl -lcrypto -lzstd -lzstd -lbrotlidec -lbrotlidec -lz -lpsl -lgsasl
configure: LIBS note: LIBS should only be used to specify libraries (-lname).
configure: WARNING: Continuing even with errors mentioned immediately above this line.
…
```

The specifications only can get generated via the pkg-config system (I only hotlink the .pc files in `/usr/local/lib/pkgconfig`, and nothing else directly in the standard paths). So I'm guessing the configure script itself causes the problem. Maybe it is not using the correct `--libs-only-l`?

```
$ pkg-config --libs libssh2
-L/usr/local/mystuff/libssh2/latest/lib -lssh2

$ pkg-config --libs-only-l libssh2
-lssh2

$ pkg-config --libs-only-L libssh2
-L/usr/local/mystuff/libssh2/latest/lib
```

This pretty matches what other libs, like nghttp2, etc., are providing there too. And those don't trigger this faux pas. 

### I expected the following

```
…
configure: using LIBS: -lcares -lnghttp2 -lidn2 -lrtmp -lssl -lcrypto -lssh2 -lzstd -lbrotlidec -lz -lpsl -lgsasl
…
```

### curl/libcurl version

curl 8.2.1

### operating system

Mac OS X 10.10.5 (Yosemite)

**Comment by bagder** [comment]
> I'm guessing the configure script itself causes the problem. Maybe it is not using the correct --libs-only-l?

Scarily accurate guess :fearful: !

https://github.com/curl/curl/blob/40c63290e3d1aa4ee083b5f9ba1b9d2ced29be5f/configure.ac#L2245

Do you want to make the PR?

**Comment by TurtleWilly** [comment]
@bagder I think it will go much quicker for you to do it. Basically I'm just a user here and I'm not familiar with the git and github stuff at all (I still use Subversion for my own stuff), and before I would figure this out curl probably would have reached version 9 already. 😃
