### ISSUE TITLE
libcurl performance degradation after upgrading to Debian Bookworm with openssl 3

### ISSUE THREAD

**Issue by apsheronets** [curl/curl#11543]
### I did this

Here is the test case

`Dockerfile`:
```
#FROM debian:bullseye
FROM debian:bookworm
RUN apt-get update
RUN apt-get install -y aptitude build-essential ruby ruby-dev ruby-bundler libcurl4-openssl-dev curl
RUN gem install patron
WORKDIR /app
RUN curl https://pomf2.lain.la/f/lxhmf2f.txt > list
RUN curl https://pomf2.lain.la/f/0w69upl3.rb > test.rb
CMD ruby test.rb
```
Run: `docker run --rm -it $(docker build -q .)`

### I expected the following

On Debian Bullseye with 7.74.0: `cpu time: 0.483637529`
On Debian Bookworm with 7.88.1: `cpu time: 1.8279782530000002`
The exact numbers could fluctuate due to these links being a real links from the scary wild internet.
I also tested on Alpine with 8.2.1, and got `cput time: 1.289875884` - still not good.

I still haven't figured out is it a glitch of the Ruby library. That would be very embarrassing. But it took me forever to get even there, so here is a bug report.

### curl/libcurl version

curl 7.88.1

### operating system

Debian Bookworm

**Comment by bagder** [comment]
I propose you retry with the latest version as I believe this problem does not exist anymore.

**Comment by bagder** [comment]
Can you please clarify exactly which curl command line you say is slower?

**Comment by apsheronets** [comment]
I'm not metering a curl command. I'm metering my script in Ruby which uses libcurl under the hood. The curl command in this Dockerfile is only being used for downloading test data and the script.

By the way, I did a little profiling with linux-perf tool. I know nothing about how to use it properly, but it shows interesting results right of the bat.

The slow case:
```
54.45%  libcrypto.so.3       
31.56%  libc.so.6            
 5.89%  libruby-3.1.so.3.1.2 
 5.83%  [kernel.kallsyms]    
 0.70%  libcurl.so.4.8.0     
 0.55%  libz.so.1.2.13       
 0.53%  libssl.so.3          
 0.38%  ld-linux-x86-64.so.2 
 0.06%  libnghttp2.so.14.24.1
 0.05%  session_ext.so       
 ```

The fast case:
```
41.00%  libcrypto.so.1.1     
19.55%  libc-2.31.so         
18.04%  libruby-2.7.so.2.7.4 
14.09%  [kernel.kallsyms]    
 2.23%  libcurl.so.4.7.0     
 1.93%  libz.so.1.2.11       
 1.19%  libssl.so.1.1        
 0.94%  ld-2.31.so           
 0.61%  libpthread-2.31.so   
 0.31%  libnghttp2.so.14.20.1
 0.07%  [vdso]               
 0.04%  session_ext.so       
```

I also discovered miles of crying about performance degradation after upgrade to version 3 in openssl issues: https://github.com/openssl/openssl/issues/17064
That could be the cause. Debian Bullseye has libssl 1.1.1 and Debian Bookworm has 3.0.9

**Comment by bagder** [comment]
It is widely known and documented that OpenSSL 3 is way slower than OpenSSL 1, so a slowdown is expected. To see if this is curl related, you should keep all other components the same and just change the libcurl version.

**Comment by apsheronets** [comment]
"WIdely known". That really hurt my feelings.
I've just spent a few days trying to figure out why the performance of [my application](http://rss2tg.duck.consulting/) plummeted by half. I had all the good causes for that, like using one of the slowest scripting languages in the world, bloated ORMs, tons of XMLs to parse, etc., and the last thing I would ever check is the underlying low-level library having a massive performance degradation, brought up by a major upgrade of Debian, the "stablest" linux distribution.

By the way, I installed libcurl4-nss-dev, and it works totally fine by now.
I tried libcurl4-gnutls-dev before, but it was also slow, and I thought "it couldn't be about the TLS flavour".

The issue could be closed.

**Comment by dfandrich** [comment]
Note that support for libcurl4-nss-dev was removed yesterday.

**Comment by apsheronets** [comment]
oh no

**Comment by samueloph** [comment]
@apsheronets We (Debian) will keep supporting `libcurl4-nss-dev` for the lifecycle of Debian Bookworm (13) so you will have a few years until you're required to migrate to something else.

For now we will be dropping it from Debian unstable and testing, but you're not using that.

**Comment by apsheronets** [comment]
@samueloph We could always rely on Debian maintainers, guarding us from the malicious winds of progress. Until the next release comes.

**Comment by bagder** [comment]
> "WIdely known". That really hurt my feelings.

Sorry, but you can google yourself to lots of comments and writing about this topic. The OpenSSL project has said that their 3.1 release will be better, but I suppose that is left to be proven.

> We (Debian) will keep supporting libcurl4-nss-dev

Yes, or if you stick to building curl 8.2.1 (or earlier) from source yourself you can also keep using NSS. But if you want to keep up with modern curl I advice everyone to immediately get off the NSS train. It is not one with a bright future.
