### ISSUE TITLE
Strequal.obj remain in all MSVC makefiles

### ISSUE THREAD

**Issue by hellbard** [curl/curl#1154]
### I did this
Try to compile libcurl 7.51.0 downloaded as ZIP 6.12.2016
### I expected the following
that libcurl will compile
### curl/libcurl version
7.51.0
[curl -V output perhaps?]
LINK : fatal error LNK1181: cannot open input file 'release-dll-ssl-dll\strequal.obj'
### operating system
windows 10 x64
VS 2013
### Solution
I was not able to find STREQUAL in sources or headers, but it was requested in all MSVC makefiles. Removing STREQUAL from linked object resolved the problem.

**Comment by jay** [comment]
Thanks for your report. This issue has already been fixed in the repo.
