### ISSUE TITLE
Cmake not finding libssh2 on Windows

### ISSUE THREAD

**Issue by cguebert** [curl/curl#1155]
The current FindLibSSH2 cmake script does not find the ssh2 library on Windows if the file is named libssh2.lib

The obvious fix would be to modify CMake/FindLibSSH2.cmake, line 15:
`FIND_LIBRARY(LIBSSH2_LIBRARY NAMES ssh2 libssh2)`

I am not a CMake expert, so correct me if this is not the recommended way.

**Comment by bagder** [comment]
Nobody seems to want to work on this, closing. libssh2 is mentioned as a problem with cmake already in the `docs/INSTALL.cmake` file.

**Comment by Lekensteyn** [comment]
Since this is still mentioned in docs/INSTALL.cmake as an issue, this was fixed via https://github.com/curl/curl/pull/4804
(I'll update the docs soon)
