### ISSUE TITLE
error setting certificate file: /etc/ssl/certs/ca-certificates.crt

### ISSUE THREAD

**Issue by pl4yout** [curl/curl#11567]
### I did this

I have been using libcurl in my program for handling HTTPS requests successfully on my x86_64 bit Linux system. However, when I attempted to switch to an ARM-based architecture, I encountered the following error:

```
CURL* curl = curl_easy_init();
if (curl) {
    curl_easy_setopt(curl, CURLOPT_URL, "https://google.com");
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    curl_easy_perform(curl);
    curl_easy_cleanup(curl);
}
```

Output:
```
*   Trying 2a00:1450:4001:813::200e:443...
* Connected to google.com (2a00:1450:4001:813::200e) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate file: /etc/ssl/certs/ca-certificates.crt
* Closing connection 0
```

I have verified that the file `/etc/ssl/certs/ca-certificates.crt` exists, and I can successfully use the `curl` command in the terminal, as shown below:

```
$ curl-config --ca
/etc/ssl/certs/ca-certificates.crt

$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

### I expected the following

When using libcurl for HTTPS requests on the ARM architecture, I anticipated that everything would work smoothly, just like on my x86_64 bit Linux system.

### libcurl version (in my program)

libcurl/7.80.0 OpenSSL/3.0.0b zlib/1.2.11

### curl version (terminal)

curl 7.81.0 (aarch64-unknown-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.15

### operating system

Linux debian 4.19.0-24-arm64 #1 SMP Debian 4.19.282-1 (2023-04-29) aarch64 GNU/Linux

**Comment by bagder** [comment]
Both your curl versions there are close to 18 months old already. This issue would interest me a lot if you can reproduce with a modern version. Also, since it works in one of them and not the other and they are different versions, isn't there reason to suspect that this problem was fixed in either libcurl or OpenSSL between those used versions?

Your OpenSSL versions seem similarly old and it is not unlikely to suspect that this is a problem in OpenSSL, since libcurl basically just points OpenSSL to this file and the error is then returned by the OpenSSL function call. I would propose you try to upgrade that as well. If nothing else to check if perhaps this problem is already fixed.

**Comment by pl4yout** [comment]
I updated both to the latest version.

Terminal:
```
$ curl -V
curl 8.2.1 (aarch64-unknown-linux-gnu) libcurl/8.2.1 OpenSSL/3.0.2 zlib/1.2.11
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
```

Terminal test:
```
$ curl https://google.de
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.de/">here</A>.
</BODY></HTML>
```

Program:

Code:
```
    CURL* curl = curl_easy_init();
    if (curl) {
        CURLcode res;
        curl_easy_setopt(curl, CURLOPT_URL, "https://www.google.com");
        res = curl_easy_perform(curl);
        if (res != CURLE_OK) {
            std::cout << "curl error: " << curl_easy_strerror(res) << std::endl;
        }
        curl_easy_cleanup(curl);
    }
```

Output:
```
curl version: libcurl/8.2.1 OpenSSL/3.0.2 zlib/1.2.11
curl error: SSL connect error
```

**Comment by bagder** [comment]
but the curl tool uses the same libcurl, right? So the same code works in one invocation but not in the other? That feels like something in your application setup/environment is different than what the curl tool does and that causes this problem.

**Comment by pl4yout** [comment]
I have tried various things, but can no longer get away from this error.

I have now set up a completely new ARM64 Ubuntu 23.04 and installed the packages via apt install libssl-dev libcurl4-dev.

Terminal:
```
$ curl https://google.de
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.de/">here</A>.
</BODY></HTML>
```

Program:

```
$ ./program
curl version: libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.52.0 librtmp/2.3
*   Trying [2a00:1450:4001:82f::200e]:443...
* Connected to google.com (2a00:1450:4001:82f::200e) port 443 (#0)
* ALPN: offers h2,http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443
* Closing connection 0
curl error: SSL connect error

```

**Comment by dfandrich** [comment]
That looks like a completely different error.

**Comment by pl4yout** [comment]
The problem has been solved by trial-and-error!

The error occurred because a linked library had statically linked an outdated OpenSSL version. This caused the OpenSSL errors. I was able to contact the developer and he linked OpenSSL dynamically. And the problem disappeared.

Thanks for helping @bagder !
