### ISSUE TITLE
HTTP/2 on Windows?

### ISSUE THREAD

**Issue by joeparkerz** [curl/curl#1158]
There is no option to compile cURL under Windows with MSVC?

**Comment by bagder** [comment]
Please use the mailing lists for questions/support, this is an issue tracker only.

See the winbuild files in current git for building with nghttp2 on msvc.

**Comment by joeparkerz** [comment]
Yes but does it work with WinSSL?

**Comment by bagder** [comment]
Please use the mailing lists for questions/support, this is an issue tracker only.
