### ISSUE TITLE
Ranges in Data?

### ISSUE THREAD

**Issue by joeparkerz** [curl/curl#1159]
**### I did this**
curl -k -A "Mozilla 5.0" --data "s=[1-30:60]&dc=[1-30:60]" https://website.com/

**### I expected the following**
I expected 3 POST  requests with different parameter ranges.
"s=0&dc=0"
"s=30&dc=30"
"s=60&dc=60"

**### curl/libcurl version**
curl 7.51.0 (x86_64-pc-msys) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink

**### operating system**
Windows x64 8.1

**Comment by jay** [comment]
> curl -k -A "Mozilla 5.0" --data "s=[1-30:60]&dc=[1-30:60]" https://website.com/

There's no range for the --data option, you'll have to script something instead.
