### ISSUE TITLE
`--interface` and `CURLOPT_INTERFACE` does not work for IP address

### ISSUE THREAD

**Issue by tearfur** [curl/curl#11599]
### I did this

I set up a Linux VM with a host-only interface (no internet) and NAT interface (have internet). The host-only interface is named `ens224` and its IP address is `192.168.158.129`.

### I expected the following

Both of the following commands shouldn't be able to reach the server:

1. `curl --interface ens224 https://icanhazip.com/`
2. `curl --interface 192.168.158.129 https://icanhazip.com/`

But (2) is able to.

### curl/libcurl version

curl 8.0.1 (x86_64-redhat-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.5/openssl/zlib nghttp2/1.52.0 Release-Date: 2023-03-20 Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets

### operating system

Linux localhost.localdomain 6.4.4-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 19 16:32:49 UTC 2023 x86_64 GNU/Linux

**Comment by bagder** [comment]
I'm not convinced this is a curl bug.

curl binds the socket to the given address, if that then makes your connection work or not is out of curl's hands.

curl will return an error if it fails to bind to an address, which you can see if you provide a phony address.

Does binding it to "ens224" say the same IP address (shown if you use `-v') ?

**Comment by tearfur** [comment]
Something like this? I can't get it to show my source IP address when specifying interface by name.

```
$ curl --interface ens224 -v https://icanhazip.com
*   Trying 104.18.114.97:443...
*   Trying [2606:4700::6812:7261]:443...
* Immediate connect fail for 2606:4700::6812:7261: Network is unreachable
*   Trying [2606:4700::6812:7361]:443...
* Immediate connect fail for 2606:4700::6812:7361: Network is unreachable
* connect to 104.18.114.97 port 443 failed: No route to host
*   Trying 104.18.115.97:443...
* connect to 104.18.115.97 port 443 failed: No route to host
* Failed to connect to icanhazip.com port 443 after 7162 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to icanhazip.com port 443 after 7162 ms: Couldn't connect to server
```

**Comment by tearfur** [comment]
When specifying by IP address:

```
$ curl -v --interface 192.168.158.129 https://icanhazip.com
*   Trying 104.18.115.97:443...
* Name '192.168.158.129' family 2 resolved to '192.168.158.129' family 2
* Local port: 0
* Connected to icanhazip.com (104.18.115.97) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr  7 00:00:00 2023 GMT
*  expire date: Apr  6 23:59:59 2024 GMT
*  subjectAltName: host "icanhazip.com" matched cert's "icanhazip.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: icanhazip.com]
* h2h3 [user-agent: curl/8.0.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x56243b42d570)
> GET / HTTP/2
> Host: icanhazip.com
> user-agent: curl/8.0.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< date: Mon, 07 Aug 2023 03:51:50 GMT
< content-type: text/plain
< content-length: 16
< access-control-allow-origin: *
< access-control-allow-methods: GET
< set-cookie: __cf_bm=PBDwL8Vn1o9U.v8pzs63hTl.oHpyYiwv7IUF2jA44aI-1691380310-0-ARir6464+UISy+pAN/1zQi3bfVlgK/4eODxgkwY80Xjd+YSy4Refeok/rNKXzpyJfFe3TpZjnrFRLfYiPZNpAr0=; path=/; expires=Mon, 07-Aug-23 04:21:50 GMT; domain=.icanhazip.com; HttpOnly; Secure; SameSite=None
< server: cloudflare
< cf-ray: 7f2c903d0f8d04d4-HKG
< alt-svc: h3=":443"; ma=86400
<
-- My public IP hidden --
* Connection #0 to host icanhazip.com left intact
```

**Comment by bagder** [comment]
I hear you, but curl does bind the socket to your provided IP address. The `Local port` output you see there is done after a successful bind.

The fact that it still works is probably because your TCP stack finds a way through anyway. I don't think curl can do anything more about that. Feel free to single-step through the `bindlocal()` function in curl and you will see what I am talking about.

When binding to an interface, curl uses `SO_BINDTODEVICE` which is a "harder" bind, which is also probably why it behaves a little different. I did #11608 just now to better log when this is used.

**Comment by tearfur** [comment]
> The fact that it still works is probably because your TCP stack finds a way through anyway

Hmm... That doesn't feel right.

On Windows, the same 2 tests succeeds (by failing), so I believe you that this indeed isn't a curl bug.

I'm no expert, so I cannot raise any concrete examples, but isn't this quite dangerous? We potentially have applications that shouldn't be connecting to the Internet somehow escaping through the other interface.

I'd appreciate any advice on how to proceed with this.

**Comment by bagder** [comment]
> Hmm... That doesn't feel right.

I don't think we can do anything about how you feel. The bind is done successfully, the functionality beyond that is out of curl's hands. I'm pretty sure the entire reason for `SO_BINDTODEVICE` is that it makes a "better" binding to an interface, thus binding to the interface is a better idea on Linux.

> isn't this quite dangerous?

If this is your only way of limiting traffic , then it certainly does not do what you were expecting, yes.
