### ISSUE TITLE
-r/range doesn't work with --proxy

### ISSUE THREAD

**Issue by Uckpa** [curl/curl#1162]
OS: Ubuntu 14.04 LTS

> curl -V
curl 7.42.1 (x86_64-unknown-linux-gnu) libcurl/7.42.1 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

Doesn't work correctly. It shows full file instead of first 10 bytes:
>curl --proxy 193.34.13.188:8080 ftp://service.boulder.ibm.com/s390/holddata/month.txt -B -r 0-10

or

>curl -r 0-10 --proxy 190.104.245.39:8080 ftp://service.boulder.ibm.com/s390/holddata/month.txt

Work fine:
>curl ftp://service.boulder.ibm.com/s390/holddata/month.txt -B -r 0-10

I used free proxy from: http://hideme.ru/proxy-list/

**Comment by jay** [comment]
Either one of those commands should do the same thing, if you turn on verbose mode you'll see `Range: bytes=0-10` to request that range. I tried a bunch of proxies and none of them support Range for ftp, they just return the whole file instead. If the proxy allows CONNECTs you can try with [`--proxytunnel`](https://curl.haxx.se/docs/manpage.html#-p), I tried that in squid just now and it worked ok.
~~~
> GET ftp://service.boulder.ibm.com/s390/holddata/month.txt HTTP/1.1
> Host: service.boulder.ibm.com:21
> Range: bytes=0-10
> User-Agent: curl/7.50.0-DEV
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x27e8f68; line 1659 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x27e8f68; line 1786 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x27e8f68; line 1796 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Date: Mon, 12 Dec 2016 18:18:21 GMT
< FTP-Status: 226 Transfer complete.
< Content-Length: 62451
~~~
