### ISSUE TITLE
Call curl_easy_perform. Exception signal 11 occurs. The top of the call stack is in getenv.

### ISSUE THREAD

**Issue by LLLLLChen** [curl/curl#11633]
### I did this

call curl_easy_perform function in my code

Occasionally, the process terminates abnormally due to signal 11. Check the call stack information. The top of the stack is in the getenv function.

The call sequence is as follows:
getenv
GetEnv
curl_getenv
create_conn_helper_init_proxy
create_conn
Curl_connect
multi_runsingle
curl_multi_perform
easy_transfer
easy_perform
curl_easy_perform

### I expected the following

I want to know why this problem occurs and how to solve it

### curl/libcurl version

curl 7.79.1

**Comment by jay** [comment]
What is your `curl_version()` and operating system? Do you have a minimal self contained example that can be used to reproduce?

**Comment by LLLLLChen** [comment]
curl_version(): curl version: libcurl/7.79.1 OpenSSL/3.0.7 zlib/1.2.11
os: linux eulerosv2r11 arm
Since the problem is sporadic, I don't have a single example to make it happen.
