### ISSUE TITLE
Some CI jobs that use msys2 are broken

### ISSUE THREAD

**Issue by jay** [curl/curl#11634]
Some CI jobs that use msys2 are broken

Since 0f49b5ba (5 days ago, a commit with no CI change) most of the azure mingw jobs which use msys2 (v2_mingw) are broken due to failed module 'cryptography' which is needed by python. Two commits later (since ae91bb7e) the Cirrus CI jobs broke for the same reason.

For example failed msys v2_mingw32_openssl shows [this error](https://dev.azure.com/daniel0244/5571c33c-81e1-43d7-93ee-d3d4152f27b2/_apis/build/builds/16603/logs/124):
~~~
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
~~~

/cc @mback2k

**Comment by mback2k** [comment]
I will try to look into it this week.

**Comment by mback2k** [comment]
I attempted a fix of the msys2 containers last night. Looking good so far.

**Comment by mback2k** [comment]
The fix seems to be working: https://dev.azure.com/daniel0244/curl/_build/results?buildId=16760&view=results

**Comment by jay** [comment]
Thanks. What change did you make? Also, it's now happening in FreeBSD builds.

**Comment by mback2k** [comment]
I pre-installed more testsuite dependencies in the Windows containers, especially a pre-compiled version of the python cryptography module: https://github.com/mback2k/curl-docker-winbuildenv/commit/2607a31bcab544b41d15606e97f38cf312c1ce56

This also reminds me that I wanted to migrate that repository to the curl organization...
