### ISSUE TITLE
Build libcurl 7.51.0 failed due to error link strequal.obj on win7 

### ISSUE THREAD

**Issue by kuoshen** [curl/curl#1164]
### I did this
Try to build libcurl 7.51.0 on win7 and found this error on below:

01:14:48 LINK : fatal error LNK1104: cannot open file 'release-dll.x64\strequal.obj'
01:14:48 NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\link.exe"' : return code '0x450'
01:14:48 Stop.
01:14:48 NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
01:14:48 Stop.

### I expected the following
Looks like strequal.h and strequal.c both removed in 7.51.0 but still try to link strequal.obj in curl-7.51.0\lib\Makefile.vc11

Maybe Makefile.vc11 line 636 should be also removed:
$(DIROBJ)\strequal.obj \

### curl/libcurl version
7.51.0
[curl -V output perhaps?]

### operating system
win7

**Comment by bagder** [comment]
This is fixed in git already, thanks!
