### ISSUE TITLE
x86 built in x64

### ISSUE THREAD

**Issue by OriginLive** [curl/curl#1165]
~~Using winbuild on windows 10 and trying to compile for x64 ver. I get
..\builds\libcurl-vc14-x64-debug-static-ipv6-sspi-winssl-obj-lib/file.obj : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'~~

apparently it works if i use the correct vs console

**Comment by OriginLive** [comment]
using VC files gives me an issue with language in .rc file

**Comment by bagder** [comment]
So the first issue is solved and now you changed it to something else?

**Comment by OriginLive** [comment]
No, it's a bit unrelated. I managed to get it to compile (The x64 ver still has problems with debug and static lib). I should rather say the second issue is that i cannot open the included visual studio files, because they give me an error about .rc file having wrong language defined

**Comment by bagder** [comment]
and you feel that is our problem?

**Comment by OriginLive** [comment]
Yes, i would say a faulty libcurl.rc file is your problem

**Comment by bagder** [comment]
okay so how exactly is it faulty? What does "wrong language defined" mean?

**Comment by OriginLive** [comment]
I got an err: a resource in this file uses an unknown language 0x3
But it works now, for reasons unknown to me. So i guess this is problem solved
