### ISSUE TITLE
Curl can`t load cloudflare client certificates: Problem with the local SSL certificate (58)

### ISSUE THREAD

**Issue by hackovh** [curl/curl#11652]
### I did this

I use client certificates from cloudflare (mTLS)

```
const auto szCertificate = R"(-----BEGIN CERTIFICATE-----
const auto szPrivateKey = R"(-----BEGIN PRIVATE KEY-----

 struct curl_blob stblob;
        stblob.data = (void*)szCertificate;
        stblob.len = strlen(szCertificate);
        stblob.flags = CURL_BLOB_COPY;

   curl_easy_setopt(curl, CURLOPT_SSLCERT_BLOB, szCertificate);  // or stblob
        curl_easy_setopt(curl, CURLOPT_SSLCERTTYPE, "PEM");

        stblob.data = (void*)szPrivateKey;
        stblob.len = strlen(szPrivateKey);

        curl_easy_setopt(curl, CURLOPT_SSLKEY_BLOB, szPrivateKey); // or stblob
        curl_easy_setopt(curl, CURLOPT_SSLKEYTYPE, "PEM");

or
  curl_easy_setopt(curl, CURLOPT_SSLCERT, R"(certificate.pem)");
        curl_easy_setopt(curl, CURLOPT_SSLKEY, R"(privateKey.pem)");
```

### I expected the following

but if i use this code its work perfect

```
const options = {
  hostname: 'example.com',
  path: '/api',
  method: 'GET',
  key: fs.readFileSync('privateKey.pem'),
  cert: fs.readFileSync('certificate.pem'),
};

const req = https.request(options, (res) => {
  let data = '';

  res.on('data', (chunk) => {
    data += chunk;
  });

  res.on('end', () => {
    console.log(data);
  });
});
```

### curl/libcurl version

libcurl 8.2.1 from vcpkg

### operating system

Windows 10 1903

```
== Info: schannel: disabled automatic use of client certificate
```
or
```
== Info: schannel: disabled automatic use of client certificate
== Info: schannel: certificate format compatibility error  for certificate.pem
```
OR 
```
== Info: Connected to furia.cc (172.67.177.190) port 443
== Info: mbedTLS: Connecting to furia.cc:443
== Info: mbedTLS: Set min SSL version to TLS 1.0
== Info: mbedTLS: Handshake complete, cipher is TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
== Info: Cert verify failed: BADCERT_NOT_TRUSTED
== Info: Closing connection
```

**Comment by hackovh** [comment]
[curl_easy_setopt](https://curl.se/libcurl/c/curl_easy_setopt.html)(curl, [CURLOPT_SSL_VERIFYPEER](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html), 0L);
fixed

**Comment by hackovh** [comment]
123

**Comment by jay** [comment]
Disabling verifypeer is a bad fix. Please read the [documentation](https://curl.se/libcurl/c/CURLOPT_SSLCERTTYPE.html). If your backend is Schannel then the certificate will have to be in p12 format and the key will either have to be part of that file or already in the keychain. In other words, you cannot pass PEM formatted certificates.

**Comment by hackovh** [comment]
> Disabling verifypeer is a bad fix. Please read the [documentation](https://curl.se/libcurl/c/CURLOPT_SSLCERTTYPE.html). If your backend is Schannel then the certificate will have to be in p12 format and the key will either have to be part of that file or already in the keychain. In other words, you cannot pass PEM formatted certificates.

please suggest me another solution why curl is not accepting

**Comment by jay** [comment]
The only other solution would be to use a different SSL backend such as OpenSSL that accepts PEM certificates.

**Comment by hackovh** [comment]
> The only other solution would be to use a different SSL backend such as OpenSSL that accepts PEM certificates.
openssl say me
```
== Info: OpenSSL/3.1.2: error:80000002:system library::No such file or directory
== Info: Closing connection
```

**Comment by jay** [comment]
> Info: OpenSSL/3.1.2: error:80000002:system library::No such file or directory

Since there is no function name specified I don't know. You would have to figure out what in your program causes it. Maybe there is an incorrect path somewhere.

**Comment by hackovh** [comment]
> > Info: OpenSSL/3.1.2: error:80000002:system library::No such file or directory
> 
> Since there is no function name specified I don't know. You would have to figure out what in your program causes it. Maybe there is an incorrect path somewhere.
I checked the blob, path, mbelts, schannel, openssl
 can't pass client certificate verification
normal get reguest
```
=> Send SSL data, 0000000005 bytes (0x00000005)
0000: 15 03 03 00 02                                  .....
== Info: TLSv1.3 (OUT), TLS alert, unknown CA (560):
=> Send SSL data, 0000000002 bytes (0x00000002)
0000: 02 30                                           .0
== Info: OpenSSL/3.1.2: error:80000002:system library::No such file or directory
== Info: Closing connection
```

**Comment by jay** [comment]
> TLS alert, unknown CA (560)

Check the CAfile/CApath directories in the verbose output.
