### ISSUE TITLE
Unable to invoke openssl engine  ecc sign function during TLS 1.3 Handshaking

### ISSUE THREAD

**Issue by RaymWong** [curl/curl#11658]
### I did this

NGINX server has been configured to verify client's certificate. 
Engine Init and Bind function have been invoked correctly. Curl failed to invoke registered engine ECC sign as shown below after engine private key loading successfully  in the openssl engine. 
output on RPI: 
 * TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, internal error (592):
* error:100F907D:elliptic curve routines:ossl_ecdsa_sign_sig:missing private key
* Closing connection 0
curl: (35) error:100F907D:elliptic curve routines:ossl_ecdsa_sign_sig:missing private key

### I expected the following

Expect to see ECC sign operation via registered ECC function in engine init function.

### curl/libcurl version

curl 7.74

### operating system

Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
OpenSSL 1.1.1n  15 Mar 2022

**Comment by bagder** [comment]
> Curl failed to invoke registered engine ECC sign

I don't even understand what that means. Is that not functionality OpenSSL should do by itself?

**Comment by bagder** [comment]
Also: we've done 20+ releases since that version...

**Comment by RaymWong** [comment]
OpenSSL Engine Interface is designed to used external hardware security module for crypto operation that stores private keys like a safe.

curl -v --engine crypto_engine --key-type ENG --key 0xe0f1 --cert client_cert  https://127.0.0.1

**Comment by RaymWong** [comment]
> > Curl failed to invoke registered engine ECC sign
> 
> I don't even understand what that means. Is that not functionality OpenSSL should do by itself?

https://www.wolfssl.com/difference-hsm-tpm-secure-enclave-secure-element-hardware-root-trust/

**Comment by bagder** [comment]
> but failed to call the sign functions registered by the crypto engine

I still don't understand what curl is supposed to do about it.

**Comment by RaymWong** [comment]
> > but failed to call the sign functions registered by the crypto engine
> 
> I still don't understand what curl is supposed to do about it.
some info on curl to do with openssl , hope this helps abit
https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1940528

**Comment by bagder** [comment]
That's a link to an ancient bug against ubuntu. It does not help me at all.

**Comment by RaymWong** [comment]
Curl needs additonal openssl config to use custom HSM keys.
