### ISSUE TITLE
Basic authentication does not send password

### ISSUE THREAD

**Issue by xnoreq** [curl/curl#1167]
### I did this
`curl -v -s --basic --netrc "https://sub.example.net/test?param=value`
with $HOME/.netrc containing:
`machine sub.example.net login myuser password JKLsjlsdkfasdfJAAlsajfdls2de`

### I expected the following
curl should send this header:
\> Authorization: Basic bXl1c2VyOkpLTHNqbHNka2Zhc2RmSkFBbHNhamZkbHMyZGU=
(that's base64 encoded "myuser:JKLsjlsdkfasdfJAAlsajfdls2de")

### I got this instead
Instead, it sent the header like this:
\> Authorization: Basic bXl1c2VyOg==
(that's base64 encoded "myuser:")

### curl/libcurl version
curl 7.51.0 (x86_64-pc-linux-gnu) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libpsl/0.15.0 (+libicu/58.1) libssh2/1.8.0

[curl -V output perhaps?]

**Comment by jay** [comment]
I can't reproduce. I changed the name to www.example.com and it works ok:
~~~
* Server auth using Basic with user 'myuser'
> GET / HTTP/1.1
> Host: www.example.com
> Authorization: Basic bXl1c2VyOkpLTHNqbHNka2Zhc2RmSkFBbHNhamZkbHMyZGU=
> User-Agent: curl/7.51.0
> Accept: */*

curl 7.51.0 (x86_64-pc-linux-gnu) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 nghttp2/1.17.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

machine www.example.com login myuser password JKLsjlsdkfasdfJAAlsajfdls2de
~~~
I can't reproduce in Windows either. Maybe there is something wrong with your netrc, like maybe an earlier entry is missing some field? Is that really all that's in it?
