### ISSUE TITLE
manpage.html: --user-agent short form partially wrong

### ISSUE THREAD

**Issue by lukastribus** [curl/curl#11688]
### I did this

I read the man page in a browser at https://curl.se/docs/manpage.html#-A regarding `--user-agent`

### I expected the following

The documentation consistently referring to the correct short form of the command (-A), as opposed to erroneously referring to -u short form (which actually stands for --user ) in the "is provided several times, the last set value will be used." statement.

Also see the broken html:

    $ curl -s https://curl.se/docs/manpage.html | grep "agent is provided several"
    <p class="level1">If <a class="emphasis" href="#-u">-u, --user</a>-agent is provided several times, the last set value will be used. </p>
    $

Here's a screenshot:

![grafik](https://github.com/curl/curl/assets/15380567/540a6d36-f46d-4dab-b411-70ec6b8a60bf)

### curl/libcurl version

(it's really more about the website)
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

(it's really more about the website)
Linux dev 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lukastribus** [comment]
same here, I stopped checking at p/proxy, you get the idea:

```
--cert-type <type> 
If -E, --cert-type is provided several times, the last set value will be used. 

-c, --cookie-jar <filename> 
If -b, --cookie-jar is provided several times, the last set value will be used. 

--form-escape 
If -F, --form-escape is provided several times, the last set value will be used. 

--netrc-file <filename> 
If -n, --netrc-file is provided several times, the last set value will be used. 

--output-dir <dir> 
If -o, --output-dir is provided several times, the last set value will be used. 

--proxy-cacert <file> 
If -x, --proxy-cacert is provided several times, the last set value will be used. 

--proxy-capath <dir> 
If -x, --proxy-capath is provided several times, the last set value will be used. 

--proxy-cert-type <type> 
If -x, --proxy-cert-type is provided several times, the last set value will be used. 


```

Parser also fails here (although there is no short form):

```
--key-type <type> 
If --key-type is provided several times, the last set value will be used. 

--proto-default <protocol> 
If --proto-default is provided several times, the last set value will be used. 
```

While these options are missing the short form in this statement:

```
-C, --continue-at <offset> 
If --continue-at is provided several times, the last set value will be used. 


-D, --dump-header <filename> 
If --dump-header is provided several times, the last set value will be used. 

-P, --ftp-port <address> 
If --ftp-port is provided several times, the last set value will be used. 

-m, --max-time <fractional seconds> 
If --max-time is provided several times, the last set value will be used. 
```

**Comment by dfandrich** [comment]
This is the right component, as the problem lies in the script that generates man pages. Looks like bagder is already on the case, but the issue seems to be at line 119 of gen.pl which erroneously does a prefix match of "--user-agent" with "--user".

**Comment by lukastribus** [comment]
Maybe a regression caused by 439ff2052e219162708faddedacdf6f1242bb8c8 ?

It wasn't broken 10 days ago:

https://web.archive.org/web/20230807141925/https://curl.se/docs/manpage.html

**Comment by bagder** [comment]
Yeps, it broke with exactly that commit. #11689 is my attempt at a fix.
