### ISSUE TITLE
Behavioural change on requests where AAAA responses are dropped

### ISSUE THREAD

**Issue by jammar1** [curl/curl#11684]
### I did this

I embed curl + c-ares in my application. I upgraded from curl version 7.77 to version 8.1.2 and found that some users had connectivity issues. I also checked this against master and the issue is still present.

As it turns out, these users have faulty middleware boxes that drop (rather than reject) packets containing AAAA records in the response.
Requests seemed to work after the five second timeout before this change: https://github.com/curl/curl/commit/ba904db0705c931ff52b4181b21ae95e6e0af3cd but now they fail entirely.

To reproduce:
1. Break the network in a similar way to the users: `sudo iptables -I INPUT -p udp --dport 53 -m string --hex-string "|00001c|" --algo bm -j DROP`
2. Build curl 7.77 with ares then make an HTTP request. I think as long as both c-ares versions have `ares_getaddrinfo` this is reproducible, but I used 1.18.1
```
Curl 7.77, have to wait 5 seconds for the V6 request to timeout but afterwards it works:
./src/curl --version
curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 c-ares/1.18.1

./src/curl -O https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Spitzbergen-2_hg.jpg/440px-Spitzbergen-2_hg.jpg -m 15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49631  100 49631    0     0   9432      0  0:00:05  0:00:05 --:--:-- 11970

Curl master:
./src/curl --version
curl 8.3.0-DEV (x86_64-pc-linux-gnu) libcurl/8.3.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 c-ares/1.18.1

./src/curl -O https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Spitzbergen-2_hg.jpg/440px-Spitzbergen-2_hg.jpg -m 15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
curl: (28) Resolving timed out after 15001 milliseconds

No longer works and hits the timeout.
```

I also tested it with this change and it still doesn't work: https://github.com/c-ares/c-ares/issues/538

### I expected the following

I'm not entirely sure if this is a bug or if I should work around it in my application instead, but I'd like to check if this behavioral change is intentional?

Thanks!

### curl/libcurl version

./src/curl --version
curl 8.3.0-DEV (x86_64-pc-linux-gnu) libcurl/8.3.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

### operating system

Ubuntu 22.04

**Comment by bagder** [comment]
(It is confusing that you show a curl version that does not use c-ares as your used version. )

This sounds like a c-ares problem. If you rebuild without c-ares, does that work better?

You're also not using the latest c-ares which I would say would be a first step to check.

**Comment by jay** [comment]
I don't consider this a bug

**Comment by bagder** [comment]
I believe I consider it a bug, but in the name resolver function. Which is outside of curl.

**Comment by jammar1** [comment]
I'm not really sure it's a bug either (given it only happens on broken networks) - but it is a behavioural change I found when upgrading.

I haven't tried the threaded resolver, but one of the platforms I target has a very high cost for thread creation so I prefer to use c-ares.

I checked out the latest version of c-ares (1.19.1) and tried again:

Works after 5 second timeout:
```
./src/curl --version
curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 c-ares/1.19.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

./src/curl -O https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Spitzbergen-2_hg.jpg/440px-Spitzbergen-2_hg.jpg -m 15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49631  100 49631    0     0   9599      0  0:00:05  0:00:05 --:--:-- 11927
```

Doesn't work:
```
./src/curl --version
curl 8.3.0-DEV (x86_64-pc-linux-gnu) libcurl/8.3.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 c-ares/1.19.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

./src/curl -O https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Spitzbergen-2_hg.jpg/440px-Spitzbergen-2_hg.jpg -m 15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
curl: (28) Resolving timed out after 15001 milliseconds

```

**Comment by bagder** [comment]
Still seems like something c-ares could solve better, doesn't it?

**Comment by bagder** [comment]
I don't see how curl does anything like this, so the possible bug is not in curl code. It can possibly be argued that c-ares could have an improved behavior. It would be useful to compare what other getaddrinfo implementations do in this situation. But again, this is not a curl bug.
