### ISSUE TITLE
'CURL_PROGRESSFUNC_CONTINUE': undeclared identifier

### ISSUE THREAD

**Issue by SkyFallOfficial** [curl/curl#11692]
### I did this

Just a simple request with user credentials for authentication. Results are in JSON.

Request part of the code:
```c++
...

auto response = cpr::Get(cpr::Url{ "http://website.com:3000/users/" + loginName + "?password=" + loginPassword + "&apikey=" + "api_key"},
                    cpr::Header{ {"Accept", "application/json"} });
                if (response.status_code != 200) {
                    std::cout << "Error: " << response.status_code << std::endl;
                }
     
...     
```

I received the following error (**libcpr.1.10.0\build\native\Win32\Release\include\cpr\util.h(26,36)**):
```
error C2065: 'CURL_PROGRESSFUNC_CONTINUE': undeclared identifier
error C3861: 'CURL_PROGRESSFUNC_CONTINUE': identifier not found
```

### I expected the following

I was expecting the project to build (obviously), and to test the authentication.

### curl/libcurl version

curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

### operating system

Windows 10
22H2
19045.3324

**Comment by bagder** [comment]
1. cpr is not done by curl project
2. you seem to be using outdated headers, `CURL_PROGRESSFUNC_CONTINUE` was added in 7.68.0
