### ISSUE TITLE
invalid location output with IRI

### ISSUE THREAD

**Issue by 1268** [curl/curl#11699]
### curl/libcurl version

invalid location output with IRI

~~~
> curl --version
curl 8.2.1 (x86_64-w64-mingw32) libcurl/8.2.1 OpenSSL/3.1.2 (Schannel) zlib/1.3 brotli/1.0.9 zstd/1.5.5 WinIDN libssh2/1.11.0 nghttp2/1.55.1 ngtcp2/0.18.0 nghttp3/0.14.0 libgsasl/2.2.0
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe UnixSockets zstd

> curl -I https://wiktionary.org/wiki/Ῥόδος
HTTP/2 301
date: Sun, 20 Aug 2023 03:52:46 GMT
server: mw2407.codfw.wmnet
location: https://www.wiktionary.org/wiki/??d??
~~~

- <https://wiktionary.org/wiki/Ῥόδος>
- <https://wikipedia.org/wiki/Internationalized_Resource_Identifier>

compare to this Go program:

~~~go
package main

import "net/http"

func main() {
   req, _ := http.NewRequest("HEAD", "https://wiktionary.org/wiki/Ῥόδος", nil)
   res, _ := new(http.Transport).RoundTrip(req)
   // https://wiktionary.org/wiki/%E1%BF%AC%CF%8C%CE%B4%CE%BF%CF%82
   println(res.Header.Get("location"))
}
~~~

### operating system

.

**Comment by dfandrich** [comment]
You don't mention what character set/code page you are using on your terminal.
When you give curl a URL, that determines that bytes that get sent to the
server—it doesn't touch the path part of the URL. It *will* do IDN conversion on
the hostname if IDN is enabled (as your curl has), but that's not relevant here.
You must provide a URL-escaped URL if you want to avoid character set
conversion issues like this.

When I try that URL on my machine, which uses UTF-8, it works fine (that is,
the site redirects to
https://en.wiktionary.org/wiki/%e1%bf%ac%cf%8c%ce%b4%ce%bf%cf%82, which is the
URL-escaped version of Ῥόδος. If you want the same results in Windows, you'll
need to convert that string to UTF-8, then (optionally, for this server) URL
escape it before passing it to curl.  curl doesn't know what character set the
server expects, and the server doesn't know what character set the client
(your terminal) is using so a URL-encoded path is the only unambiguous way to
present such URLs.

**Comment by 1268** [comment]
> You must provide a URL-escaped URL if you want to avoid character set conversion issues like this.

no, thats not true. here is a better Go program for testing:

~~~go
package main

import (
   "net/http"
   "os"
)

func main() {
   req, _ := http.NewRequest("HEAD", os.Args[1], nil)
   res, _ := new(http.Transport).RoundTrip(req)
   println(res.Header.Get("location"))
}
~~~

like cURL, its now taking the URL from user input, unlike the original program. and it works perfectly:

~~~
> go run http.go https://wiktionary.org/wiki/Ῥόδος
https://www.wiktionary.org/wiki/Ῥόδος
~~~

> If you want the same results in Windows, you'll need to convert that string to UTF-8, then (optionally, for this server) URL escape it before passing it to curl.

again no, see above.

**Comment by gvanem** [comment]
That URL works fine in Lynx (except for some missing Greek letters):
![Lynx-rhodos](https://github.com/curl/curl/assets/945271/816cb553-7a53-4607-acea-6b752274a203)

With S-lang pre2.3.4-8 and not much else.

**Comment by bagder** [comment]
curl supports URLs as defined by RFC 3986 (plus some small extensions). This is not a valid URL per this spec.

**Comment by 1268** [comment]
OK, well I guess this is a feature request for RFC 3987 then?

https://datatracker.ietf.org/doc/html/rfc3987

**Comment by bagder** [comment]
It is obviously known and documented in several places.

But the problem is even more evolved. Those other tools you tested mostly likely mimic the browsers, and neither of them work with IRIs as defined by RFC 3987 either. They follow the [WHATWG URL Spec](https://url.spec.whatwg.org/), which is a similar but different beast.

There's simply no such thing as a "standard URL", but there are numerous different ways to parse them and there are rarely two parsers treating them exactly the same.

I have worked a bit to document some such [URL interop problems](https://github.com/bagder/docs/blob/master/URL-interop.md).

**Comment by 1268** [comment]
my issue is that regardless of other concerns, this is simply not correct:

~~~
location: https://www.wiktionary.org/wiki/??d??
~~~

the output should either be UTF-8 encoded text (ideal) or percent encoded. the current output is using some weird character replacement function

**Comment by bagder** [comment]
This case is *also* more complicated than simply "not correct".

I'm not sure what that header is. HTTP header values are never supposed to be unicode as per the HTTP RFC. 

When you ask curl to show headers in the terminal, it will simply output exactly what it got. If the server sends you weirdly encoded data, that might appear funny in the terminal - like if the terminal does not use UTF-8 but the encoded header did.

When curl tries to follow such a URL, it will still use a percent-encoded version of any byte values above 128.

**Comment by 1268** [comment]
upon further checking, it seems cURL is even mangling the request itself:

~~~
HEAD /wiki/??d?? HTTP/1.1
Host: wiktionary.org
User-Agent: curl/7.84.0
Accept: */*
Proxy-Connection: Keep-Alive
accept-encoding: identity
content-length: 0

HTTP/1.1 301 Moved Permanently
content-length: 0
location: https://wiktionary.org/wiki/??d??
server: HAProxy
x-cache: cp2033 int
x-cache-status: int-tls
connection: close
~~~

and if I download the result using `-O`, its just the https://wiktionary.org homepage, rather than the requested page. so cURL is not interpreting unicode input correctly, while as I have demonstrated in other comments, other tools are.

**Comment by 1268** [comment]
why was issue closed?

**Comment by bagder** [comment]
Because there is no curl issue here. There is possibly an identified "URL problem", but that is way bigger than just curl.

**Comment by 1268** [comment]
cURL mangled the input URL, did anyone see my previous comment? and other similar tools are not doing that with the same terminal, shell and input URL, as demonstrated by my other previous comments. if I can more clearly demonstrate the problem, I am happy to do so.

**Comment by bagder** [comment]
You gave curl an input, it showed you the response headers.

The URL you gave it was using unicode and curl could easily get that used wrongly. It seems however that curl actually managed to use it correctly, but you think the `location:`  header it shows looks wrong. That (probably) happens because it contains weird character codes that your terminal objects to and can't show. The latter *probably* because you use Windows and it does not do UTF-8 automatically. And HTTP header fields, and URLs in headers, are not supposed to be UTF-8. Nor unicode.

This is how curl works. You're welcome to help us improve curl further, but as I have tried to explain in several of my responses here, this is a very tricky area. You repeatedly say "other tools do it right", but that is a matter of what exact input you provide and what output you expect. "URLs" are not standardized (correctly), there is no single "right way" to deal with them in every situation.

**Comment by 1268** [comment]
> The URL you gave it was using unicode and curl could easily get that used wrongly.

"get that used wrongly"? what does that mean?

> It seems however that curl actually managed to use it correctly, but you think the `location:` header it shows looks wrong.

from this input:

https://wiktionary.org/wiki/Ῥόδος

cURL is creating this request:

~~~
HEAD /wiki/??d?? HTTP/1.1
Host: wiktionary.org
User-Agent: curl/7.84.0
Accept: */*
Proxy-Connection: Keep-Alive
accept-encoding: identity
content-length: 0
~~~

how is that correct?

> That (probably) happens because it contains weird character codes that your terminal objects to and can't show.

how can that be, when I have already shown two other programs that work correctly, on exactly the same terminal?

> The latter _probably_ because you use Windows and it does not do UTF-8 automatically.

again, two other tools are working as expected on same terminal.

> And HTTP header fields, and URLs in headers, are not supposed to be UTF-8. Nor unicode.

fine, but why is cURL creating an invalid request, as shown in the code block above?

> You're welcome to help us improve curl further, but as I have tried to explain in several of my responses here, this is a very tricky area.

OK, but why was the issue closed? that seems to communicate no interest in seeing this fixed, or even agreeing that its a problem.

> You repeatedly say "other tools do it right", but that is a matter of what exact input you provide and what output you expect.

if I am providing the same URL to multiple tools, with the same terminal, I would expect them to behave similar. if two are behaving as expected, and one is mangling the input, I would consider that an issue with that tool, rather than my system.

**Comment by bagder** [comment]
> cURL is creating this request:

If you want to see the exact byte codes curl sent/received, I propose you use `--trace`. The question marks you see there are probably not what was sent.

> why was the issue closed?

Because it is only repeating known problems and issues with (Windows) terminals and URLs.

If you say you want to work on improving this situation and you think it helps your work then sure, let's reopen this issue. But it is not bug per se, it is a known URL/terminal quirk that has existed for a long time and that nobody works on. It is primarily a problem on Windows since Windows is the uniquely weird creature in the modern world by *not* speaking UTF-8 by default.

**Comment by 1268** [comment]
> If you want to see the exact byte codes curl sent/received, I propose you use `--trace`. The question marks you see there are probably not what was sent.

~~~
0000: 48 45 41 44 20 2f 77 69 6b 69 2f 3f 3f 64 3f 3f HEAD /wiki/??d??
0010: 20 48 54 54 50 2f 32 0d 0a 48 6f 73 74 3a 20 77  HTTP/2..Host: w
0020: 69 6b 74 69 6f 6e 61 72 79 2e 6f 72 67 0d 0a 55 iktionary.org..U
0030: 73 65 72 2d 41 67 65 6e 74 3a 20 63 75 72 6c 2f ser-Agent: curl/
0040: 38 2e 31 2e 32 0d 0a 41 63 63 65 70 74 3a 20 2a 8.1.2..Accept: *
~~~

U+003F is Question Mark, so yes cURL is mangling the input. compare with this Go program:

~~~
package main

import (
   "fmt"
   "os"
)

func main() {
   arg := []byte(os.Args[1])
   for i := range arg {
      fmt.Printf("%x ", arg[i])
   }
}
~~~

correct output:

~~~
> go run hello.go Ῥόδος
e1 bf ac cf 8c ce b4 ce bf cf 82
~~~

> Because it is only repeating known problems and issues with (Windows) terminals and URLs.

OK but shouldnt an issue remain open until it is fixed? if another issue is already open cool, but I am not sure if thats the case.

> If you say you want to work on improving this situation and you think it helps your work then sure, let's reopen this issue.

I am willing to help test the problem and help as much as I am able.

> But it is not bug per se, it is a known URL/terminal quirk that has existed for a long time and that nobody works on.

its not a bug, but it works fine with other clients using the same terminal and input?

> It is primarily a problem on Windows since Windows is the uniquely weird creature in the modern world by _not_ speaking UTF-8 by default.

operating systems are different. so if the cURL team has decided that Windows is supported platform, then I think its reasonable that the Windows tool should work in a similar way to cURL on other platforms.
