### ISSUE TITLE
CURL_SIZEOF_LONG isssue - Openwrt Mipsel

### ISSUE THREAD

**Issue by acsdkquery** [curl/curl#1171]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
Compiling libcurl in openwrt Mipsel too chain

### I expected the following
in curlbild.h am excepting CURL_SIZEOF_LONG  is 8, But it was 4
Openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl$ vi curlbuild.h
....
/* The size of `long', as computed by sizeof. */
_#define_ CURL_SIZEOF_LONG 4
......

### curl/libcurl version
Curl-7.48.0
[curl -V output perhaps?]

### operating system
Linux
target-mipsel_1004kc+dsp_uClibc-0.9.33.2   - Openwrt

Issue:
openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curlrules.h:143:41: error: size of array '__curl_rule_01__' is negative
     [CurlchkszEQ(long, CURL_SIZEOF_LONG)];

Found : https://github.com/curl/curl/issues/813
I ported this fix, But not helped, Because curlbuild.h is auto generated in compile time.

If i manually changed the CURL_SIZEOF_LONG to 8, issue is gone , But linking time am facing error. Like,
/_openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/lib/libssl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status_

**Comment by bagder** [comment]
If you want to support both 32bit and 64bit builds interchangeably, you currently need to generate two curlbuild.h files manually and make sure the correct header is included dependent on the arch you use.

Also mentioned in FAQ: https://curl.haxx.se/docs/todo.html#Remove_the_generated_include_fil

**Comment by acsdkquery** [comment]
Thanks, I am not using both 32/64 bit and only 32bit. (so CURL_SIZEOF_LONG  is always 4, created on build time)

but while using this Libcurl in my own program, am getting this error, (my code also runs in same 32bit)

openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/include/curl/curlrules.h:143:41: error: size of array 'curl_rule_01' is negative
[CurlchkszEQ(long, CURL_SIZEOF_LONG)];


If i manually changed the CURL_SIZEOF_LONG to 8 in curlbuild.h, issue is gone , But linking time am facing error. Like,
/openwrt/staging_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/usr/l**ib/libssl.so: error adding symbols: File in wrong format**
collect2: error: ld returned 1 exit status

**Comment by bagder** [comment]
> If i manually changed the CURL_SIZEOF_LONG to 8 in curlbuild.h, issue is gone

Surely your long is not 8 bytes in 32 bit mode? That's 64 bits large. That would rather indicate that you're actually using 64bit when you link with libcurl...

**Comment by acsdkquery** [comment]
let me check on this,

**Comment by acsdkquery** [comment]
where to download 32bit Curl for openwrt

**Comment by bagder** [comment]
No feedback, closing
