### ISSUE TITLE
Unexpected behavior of curl_url_set for empty string (DEBUGASSERT)

### ISSUE THREAD

**Issue by ad0p** [curl/curl#11714]
### I did this

I am trying to use curl_url_set with CURLU_DEFAULT_SCHEME option to validate a string and check whether it's a valid URL. 

Now, our tests fail when calling curl_url_set on empty string with DEBUGBUILD. 

It fails on [urlapi.c:1245](https://github.com/curl/curl/blob/master/lib/urlapi.c#L1245)

`DEBUGASSERT(pathlen < urllen);`

With release build, it returns CURLUE_OK

Is it expected for empty string URL to fail here and just for DEBUGBUILD?

### I expected the following

Release build says that empty string is a valid URL, debug build fails on assertion. I would expect the same behavior in both.

### curl/libcurl version

curl 8.2.1

### operating system

not relevant

**Comment by bagder** [comment]
Setting a blank URL does not assert for me.

It should return an error.

~~~c
#include <curl/curl.h>

int main(void)
{
  curl_global_init(CURL_GLOBAL_ALL);
  CURLU *u = curl_url();
  curl_url_set(u, CURLUPART_URL, "", 0);
  curl_global_cleanup();
}

**Comment by ad0p** [comment]
I am sorry, I forgot to mention that we use curl_url_set with CURLU_DEFAULT_SCHEME options... you are right, without this flag, behavior is different.

**Comment by bagder** [comment]
#11715 now makes this return `CURLUE_MALFORMED_INPUT`
