### ISSUE TITLE
curl built with libssh gets stuck when uploading to sftp server

### ISSUE THREAD

**Issue by zuoxiaofeng** [curl/curl#11725]
### I did this

Use command to upload file: curl -T <local file> <sftp url> -k -Y 30 -y 60
disconnect network during uploading
curl command will stuch and now exit even timeout reach to timeout limitation

### I expected the following

when disconnect network during uploading, curl command should exit in about 60s.

libssh.cpp:
    case SSH_SFTP_INIT:
      ssh_set_blocking(sshc->ssh_session, 1);

It seems caused by the upload to SFTP using libssh blocking mode, that's caused the CURLOPT_LOW_SPEED_LIMIT, CURLOPT_LOW_SPEED_TIME doesn't work when use libssh.

libssh.cpp(2129-2134):
    if(block) {
      curl_socket_t fd_read = conn->sock[FIRSTSOCKET];
      /* wait for the socket to become ready */
      (void) Curl_socket_check(fd_read, CURL_SOCKET_BAD,  //it's seems block in here
                               CURL_SOCKET_BAD, left > 1000 ? 1000 : left);
    }

### curl/libcurl version

$ ./curl -V       
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.11 zstd/1.5.1 libssh/0.10.4/openssl/zlib
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system

Centos7

**Comment by bagder** [comment]
This is probably the same issue we have discussed before: https://curl.se/docs/knownbugs.html#libssh_blocking_and_infinite_loo

Unfortunately nobody has worked on this. Right now, the advice is to use the libssh2 backend instead as a work-around because that is properly non-blocking all the time.

**Comment by bagder** [comment]
> libssh2 doesn't support some ciphers

Are you sure? That *used* to be the case back in the day but is no longer so, I believe.

> I will look into this issue try to fix it if I can.

Awesome!

**Comment by zuoxiaofeng** [comment]
I found there are two merge request in progress to merge into libssh to handle libssh sftp transfer stuck problem.

Merge request for add timeout option for blocking mode:
https://gitlab.com/libssh/libssh-mirror/-/merge_requests/405
Merge request for add a non-blocking sftp transfer API
https://gitlab.com/libssh/libssh-mirror/-/merge_requests/404

**Comment by bagder** [comment]
That libssh2 list looks out of date and is incomplete but let's drop that conversation here. This is not a libssh2 forum.

**Comment by vszakats** [comment]
libssh2 pages are no longer out of date. Let us know there if there remains any inaccuracy.

**Comment by bagder** [comment]
This is a libssh issue. I recommend either working on fixing libssh or try using libssh2 instead, which does not suffer from this limitation.
