### ISSUE TITLE
CI pytest failing due to missing file

### ISSUE THREAD

**Issue by jay** [curl/curl#11761]
### I did this

aacbeae7 (#11677) changed the behavior of the curl tool to error on missing files rather than treat them as zero length data. This has caused a problem in CI pytest phase due to a missing file in an h2 test:

~~~
  curl: Failed to open /home/runner/work/curl/curl/tests/http/gen/data-100k--url
  curl: option --data-binary: error encountered when reading a file
~~~

https://github.com/curl/curl/actions/runs/6021838637/job/16335414183#step:21:275

### curl/libcurl version

.

### operating system

.

**Comment by icing** [comment]
A `,` was missing in the argument list.
