### ISSUE TITLE
Curl insists to do RETR instead of uploading a file in FTP

### ISSUE THREAD

**Issue by pferrucci** [curl/curl#11765]
### I did this

curl --user myuser:mypassword --retry-connrefused 0 --upload-file myfile.txt ftp://dummy.server.fr --verbose

### I expected the following

myfile.txt should be uploaded to the FTP server.

Instead I got this:

> * processing: http://0.0.0.0/myfile.txt
> *   Trying 0.0.0.0:80...
> * connect to 0.0.0.0 port 80 failed: Address not available
> * Failed to connect to 0.0.0.0 port 80 after 3 ms: Couldn't connect to server
> * Closing connection
> curl: (7) Failed to connect to 0.0.0.0 port 80 after 3 ms: Couldn't connect to server
> * processing: ftp://dummy.server.fr
> *   Trying dummy.server.fr:21...
> * Connected to dummy.server.fr (dummy.server.fr) port 21
> < 220 FTP Welcome
>  USER myuser
> < 331 Password required for gimel
>  PASS mypassword
> < 230 Logged on
>  PWD
> < 257 "/" is current directory.
> * Entry path is '/'
> * Request has same path as previous transfer
>  EPSV
> * Connect data stream passively
> * ftp_perform ends with SECONDARY: 0
> < 229 Entering Extended Passive Mode (|||65291|)
> * Connecting to dummy.server.fr (dummy.server.fr) port 65291
> *   Trying dummy.server.fr:65291...
> * Connected to dummy.server.fr (dummy.server.fr) port 21
>  TYPE A
> < 200 Type set to A
>  LIST
> < 150 Opening data channel for directory listing of "/"
> * Maxdownload = -1
> drwxr-xr-x 1 ftp ftp              0 Aug 29 12:34 bla bla blah
> * Remembering we are in dir ""
> < 226 Successfully transferred "/"
> * Connection # 1 to host dummy.server.fr left intact

I see two problems:
* why does it try to access 0.0.0.0:80 ? whereas I specified the server name and also the protocol "ftp://"
* why does it LIST the destination directory instead of uploading the file?

Note:
both behaviours happen when "--retry-connrefused" is used, with or without the use of "--retry 1".
If I remove it, it works as expected.

### curl/libcurl version

curl 8.2.1

### operating system

Windows 64bits

**Comment by bagder** [comment]
This:
~~~
curl --user myuser:mypassword --retry-connrefused 0 --upload-file myfile.txt ftp://dummy.server.fr --verbose
                                                  ^
~~~
The `0` there is a URL to curl, the first on this command line. The second being `ftp://dummy.server.fr`. The option `--retry-connrefused` does not take an extra argument.

**Comment by pferrucci** [comment]
Ouch. Confirmed.
Thanks.
