### ISSUE TITLE
Curl_ossl_seed() fail in Solaris

### ISSUE THREAD

**Issue by pwpo1999** [curl/curl#1177]
### I did this
I want to make SSL Client with libcurl and openssl 1.0.2.
I built success curl 7.52.2-DEV with openssl 1.0.2j.
but Request test fail(Request : curl -v -k https://${TESTURL}) with error message.
`Trying 172.16.97.92
TCP_NODELAY set
Failed to set TCP_KEEPALIVE on fd3
Connected to ${IP} ($IP) port 443 (#0)
libcurl is now using a weak random seed!
Closing connection 0`

Next, I built curl 7.51.0 with openssl 1.0.2j.
Request test success with no problem.

I found commit log
(https://github.com/curl/curl/commit/ddefc056b68e0eb8912080b6817d17f1a8ad406f)
so. I recovered the code below to curl 7.52.2-DEV
`   do {
      unsigned char randb[64];
      int len = sizeof(randb);
 (minus)   RAND_bytes(randb, len);
 (plus)    if(!RAND_bytes(randb, len))
 (plus)      break;
      RAND_add(randb, len, (len >> 1));
 (minus)  } while(!RAND_status());
 (plus) } while(!rand_enough());`
After. I built that source code. and Request test success with no problem.
I found RAND_bytes() return 0 in my environment.

Please confirm.

### operating system
Solaris Sparc 2.6

**Comment by bagder** [comment]
To me this sounds like a problem with your OpenSSL (build/install). libcurl can't function properly without a good random and since your openssl can't provide that random, it fails. What else can curl do?

**Comment by pwpo1999** [comment]
I found that /dev/random and /dev/urandom not work in my environment.
Also, egd not installed..
I found <Why do I get a "PRNG not seeded" error message> question in https://www.openssl.org/docs/faq.html
Solaris Vesion before 9 is required install "SUNWski Package".

Is there any other way?...

**Comment by bagder** [comment]
That still sounds like an OpenSSL issue. SSL/TLS **requires** good and strong random so you need to make such a source available to OpenSSL when you build that, and then libcurl will use the OpenSSL API properly to obtain random data when it needs to.

**Comment by pwpo1999** [comment]
Thank you for answer.
I will try to another way for making random data.
