### ISSUE TITLE
curl tool build fail in AIX

### ISSUE THREAD

**Issue by pwpo1999** [curl/curl#1178]
### I did this
I built curl 7.52.1 with openssl 1.0.2
but, build fail with error message.
In file included from /usr/include/netinet/tcp.h:69,
                         from tool_operate.c:39:
/usr/include/netinet/ip.h:115 error: parse error before "ip_xhl"
...

I guess this error occurred because the header was not included.
so. I add #include <arpa/inet.h> to tool_operate.c.
After, build success with no problem.

Please confirm.

### operating system
AIX 4.3

**Comment by bagder** [comment]
I doubt anyone else than other AIX users can confirm that - as it is basically a stupid system that doesn't handle its own header dependencies.

Can we do the reverse and instead remove the ` <netinet/tcp.h>` include? I suspect that's a leftover from the past.
