### ISSUE TITLE
8.2.1_9 for Windows gives erros "Header without colon"

### ISSUE THREAD

**Issue by escherstair** [curl/curl#11802]
### I did this

I send a HTTP GET request from cURL in Windows, to a HTTP server developed with Python.
The header for the answer is
```
HTTP/1 200 OK
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 08:01:26 GMT
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 08:04:31 GMT
Content-type: text/html
```

### I expected the following

I would expect having back the answer, but I get the error
```
* processing: http://localhost:8008/?IdBadge=1234
*   Trying [::1]:8008...
*   Trying 127.0.0.1:8008...
* Connected to localhost <127.0.0.1> port 8008
> GET /?IdBadge=1234 HTTP/1.0
> Host: localhost:8008
> User-Agent: curl/8.2.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.7.13
< Date: Tue, 05 Sep 2023 08:37:41 GMT
* Header without colon
* Closing connection
curl: (8) Header without colon 
```

The same request from Firefox 115.2 works perfectly.

### curl/libcurl version

curl 8.2.1_9

### operating system

Windows

**Comment by bagder** [comment]
I feel that there are details missing.

> HTTP/1 200 OK

First you state this is what is returned, which curl would not accept, but then in your later output you show it returning `HTTP/1.0 200 OK`.

Can you tell us the exact sequence of bytes the server responds with? I'm not on Windows, but the recipe you provide here works fine for me.

**Comment by escherstair** [comment]
Sorry, my fault.
The first snippet comes from Firefox.
curl receives 
`HTTP/1.0 200 OK`

Camn you tell me how to get the bytes?
Is there a command line in curl?

**Comment by bagder** [comment]
> Camn you tell me how to get the bytes?
> Is there a command line in curl?

curl has an option for this (`--trace`), but since this fails (early) it will not show that header that it does not accept, so curl will not tell us the exact contents of what makes it bail.

Since this is clear text HTTP, another option is to use Wireshark and listen/view the network traffic and use that to see the exact byte sequence.

I suspect there is a newline or something strange after that first `Date:` header.

**Comment by escherstair** [comment]
Here is the dump from Wireshark
```
0000   02 00 00 00 45 00 00 f7 6b a3 40 00 80 06 00 00   ....E...k.@.....
0010   7f 00 00 01 7f 00 00 01 1f 48 f5 69 7f 6d af ad   .........H.i.m..
0020   4c c2 4a 51 50 18 00 1f fe eb 00 00 48 54 54 50   L.JQP.......HTTP
0030   2f 31 2e 30 20 32 30 30 20 4f 4b 0d 0a 53 65 72   /1.0 200 OK..Ser
0040   76 65 72 3a 20 42 61 73 65 48 54 54 50 2f 30 2e   ver: BaseHTTP/0.
0050   36 20 50 79 74 68 6f 6e 2f 33 2e 37 2e 31 33 0d   6 Python/3.7.13.
0060   0a 44 61 74 65 3a 20 54 75 65 2c 20 30 35 20 53   .Date: Tue, 05 S
0070   65 70 20 32 30 32 33 20 30 38 3a 33 38 3a 32 34   ep 2023 08:38:24
0080   20 47 4d 54 0d 0a 48 54 54 50 2f 31 2e 30 20 32    GMT..HTTP/1.0 2
0090   30 30 20 4f 4b 0d 0a 53 65 72 76 65 72 3a 20 42   00 OK..Server: B
00a0   61 73 65 48 54 54 50 2f 30 2e 36 20 50 79 74 68   aseHTTP/0.6 Pyth
00b0   6f 6e 2f 33 2e 37 2e 31 33 0d 0a 44 61 74 65 3a   on/3.7.13..Date:
00c0   20 54 75 65 2c 20 30 35 20 53 65 70 20 32 30 32    Tue, 05 Sep 202
00d0   33 20 31 30 3a 30 38 3a 30 35 20 47 4d 54 0d 0a   3 10:08:05 GMT..
00e0   43 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65   Content-type: te
00f0   78 74 2f 68 74 6d 6c 0d 0a 0d 0a                  xt/html....
```

**Comment by icing** [comment]
There is the final `\r\n` missing at the end of the first response. Therefore, curl reads on and encounters the second response which starts with `HTTP/1.0 200 OK` which is not a valid header.

**Comment by escherstair** [comment]
Do you mean before this first `HTTP/1.0 200 OK`?
And so `\r\n` is missing after the following bytes?
```
02 00 00 00 45 00 00 f7 6b a3 40 00 80 06 00 00   ....E...k.@.....
0010   7f 00 00 01 7f 00 00 01 1f 48 f5 69 7f 6d af ad   .........H.i.m..
0020   4c c2 4a 51 50 18 00 1f fe eb 00 00   L.JQP.......
```

**Comment by bagder** [comment]
That reveals that your server responds like this:
~~~
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 08:38:24 GMT
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 10:08:05 GMT
Content-type: tex/html
~~~

Line 4 is a not a valid header. It is the initial status-line coming *again*.

It appears as if the server sends two responses concatenated somehow, but not correctly to make them two separate ones. curl is not going to be the only client that refuses to work with this.

**Comment by jzakrzewski** [comment]
This is probably some low-level protocol junk.
The issue is your server sends back something like:
```
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 08:01:26 GMT
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.7.13
Date: Tue, 05 Sep 2023 08:04:31 GMT
Content-type: text/html

``` 
Which is not a valid HTTP response, because of the second `HTTP/1.0 200 OK`.
Firefox, and probably other browsers, probably just ignores it, because browsers generally try to ignore any junk they don't understand, and work with what's left.

In short: fix the server.

**Comment by bagder** [comment]
curl rejects these bad headers since #8610

**Comment by escherstair** [comment]
I confirm a bug in the server. It has been fixed.
Thanks
