### ISSUE TITLE
I'm pretty sure Cookie.c tailsmatch does not work properly

### ISSUE THREAD

**Issue by xiolec** [curl/curl#1181]
static bool tailmatch(const char *cooke_domain, const char *hostname)

I'm pretty sure a cookie with the domain of ".example.com" should work for "www.example.com"

affects Curl_cookie_getlist

**Comment by xiolec** [comment]
Quick fix that just ignores that "." on the cookie domain is to add this at the beginning of tailsmatch. 

if (cooke_domain)
		if (cooke_domain[0] == '.')
			cooke_domain = cooke_domain + 1;

**Comment by bagder** [comment]
Please provide a case (test case or real world) that fails or works where it should/shouldn't.

**Comment by fchandur** [comment]
I ran into this issue as well. I have posted the contents of headers.txt and cookies.txt that were generated after the execution of the command below.

### I did this
`CURL -c cookies.txt -o page.txt -D headers.txt --url https://www.yahoo.com`

### I expected this
cookies.txt to have cookies from yahoo. 
### curl version information
```
>CURL --version
curl 7.52.1 (x86_64-pc-win32) libcurl/7.52.1 WinSSL zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
```
### headers.txt
```
HTTP/1.1 200 OK
Date: Fri, 13 Jan 2017 20:10:15 GMT
P3P: policyref="https://policies.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
Strict-Transport-Security: max-age=2592000
X-Frame-Options: DENY
Set-Cookie: autorf=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=www.yahoo.com
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
Age: 2
Transfer-Encoding: chunked
Connection: keep-alive
Via: http/1.1 ir3.fp.ne1.yahoo.com (ApacheTrafficServer)
Server: ATS
Cache-Control: no-store, no-cache, private, max-age=0
Expires: -1
```

### cookies.txt
```
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.
```

**Comment by jay** [comment]
I don't see how that's the same thing. Yahoo deletes that cookie by expiring it. autoref value in their script I assume is blank so php sets the value to deleted and then adds `expires=Thu, 01-Jan-1970 00:00:01 GMT` to actually delete it.

**Comment by fchandur** [comment]
You are right. This is a session cookie(?), and wouldn't be written to the cookie jar file.

**Comment by bagder** [comment]
libcurl has no notion of cookie sessions, you need to tell it when a session has ended with `CURLOPT_COOKIESESSION` so yes it will save session cookies just as well as any other cookie.

But it will expire timed-out cookies. A cookie with an expire date in 1970 will thus not be saved.

**Comment by xiolec** [comment]
Okay I think I know exactly what the problem I was having is now. I was trying to manually add cookies using the Curl_cookie_add function which removes the dot if you pass the domain in as a http header, but if you use the default domain parameter on the function and have the dot on the default domain it does not remove the dot. 

So, yeah the problem will really only come up if you are trying to manually add cookies that are not sent in as http headers.

**Comment by jay** [comment]
Just to clarify --and I assure you I did read what you just said-- you used the Curl_cookie_add function, and not the public API?

**Comment by bagder** [comment]
No comment, no recipe to reproduce, sounded like a user error. Closing.
