### ISSUE TITLE
undefined reference to `__mingw_basename' Curl (MinGW)

### ISSUE THREAD

**Issue by andeees** [curl/curl#1183]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this

First (while confuring curl-7.51.0 in msys)

`./configure --disable-shared --enable-static --prefix=C:/Libcurl/static_built --disable-ldap --disable-sspi --without-librtmp --disable-file --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-smb --without-libidn`

After:

`make`

Then:

`make install`

I have added ws2_32.a and libcurl.a to the linked libraries with the option `-static` and in search directories I have included curl\include and the /lib. And I added CURL_STATICLIB in defines.

Build Log of IDE (Using CodeBlocks):

mingw32-g++.exe -Wall -fexceptions -g -std=c++11 -DCURL_STATICLIB -IC:\Libcurl\static_built\include -IC:\c++\Tutorials\.cbp\libCurl -c C:\c++\Tutorials\.cbp\libCurl\main.cpp -o obj\Debug\main.o
    mingw32-g++.exe -LC:\Libcurl\static_built\lib -o bin\Debug\libCurl\.exe.exe obj\Debug\main.o  -static  C:\Libcurl\static_built\lib\libcurl.a C:\MinGW\lib\libws2_32.a
    C:\Libcurl\static_built\lib\libcurl.a(libcurl_la-formdata.o):formdata.c:(.text+0x491): undefined reference to __mingw_basename'
    collect2.exe: error: ld returned 1 exit status

Particularly the error:

    undefined reference to `__mingw_basename'

I was told to include a libgen library, but I don't seem to find anything like it in my computer.

### curl/libcurl version

curl-7.51.0

### operating system

Windows Home 10 64 bit

**Comment by jay** [comment]
try libmingwex.a

**Comment by andeees** [comment]
@jay Thanks, that solved my problem :)

**Comment by jay** [comment]
I just guessed from prior knowledge. How exactly are you building curl?

**Comment by andeees** [comment]
@jay I configured  with the MSYS console with the commands above (just http)

**Comment by jay** [comment]
Something about that output looks wrong, you are supposedly using autotools but at the same time it's building with mingw32-g++ and Windows paths? I've never seen it done that way. What makefile did you add the static libraries to?

**Comment by andeees** [comment]
@jay That build log is from my IDE (CodeBlocks) and not from the building log of the make files.

**Comment by jay** [comment]
Ok it makes sense now, thanks for the clarification.
