### ISSUE TITLE
Behaviour change due to git commit 2485547

### ISSUE THREAD

**Issue by ismail** [curl/curl#11845]
2485547da0ec0c1ad2561481de976106e3e0b9b2 changed the behaviour of http post to be max 64KB unless explicitly set to a larger value with `CURLOPT_UPLOAD_BUFFERSIZE`. This causes problem with some local code (still pending a proper reproducer) which sets `CURLOPT_POSTFIELDSIZE` to a large value (> 64KB) and sends data of that size.

With curl 8.3.0, only 64KB gets transferred as expected. I wonder if this is the desired behavior though, or should the following code from https://github.com/curl/curl/commit/2485547da0ec0c1ad2561481de976106e3e0b9b2#diff-14c8235d370910f1781de1a00ed1957ec948e84e88fdc52db87bd4eb7c7167ffR1390

```
    if(http && (sendsize > (size_t)data->set.upload_buffer_size))
      sendsize = (size_t)data->set.upload_buffer_size;
```

take `http.postsize` into account as well?

### curl/libcurl version

curl 8.3.0

### operating system

Linux

**Comment by bagder** [comment]
Please provide more info to let us reproduce.

**Comment by bagder** [comment]
No response
