### ISSUE TITLE
Test 977 fails on Solaris with libpsl

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#11856]
### I did this

Test 977 fails on Solaris 10 and 11, i386 and SPARC when compiled with libpsl 0.21.0. If libpsl support is disabled, the test passes. The failures can be see on the [curl autobuilds](https://curl.se/dev/builds.html) and I've reproduced it on another Solaris 11 machine.  Other successful CI builds on other OSes are also using the same version of libpsl without an error in the test. The output diff (file cookies977) looks like this:

```diff
--- log/check-expected 2023-09-11 10:52:00.015531500 +0200
+++ log/check-generated 2023-09-11 10:52:00.015401100 +0200
@@ -2,3 +2,4 @@
# https://curl.se/docs/http-cookies.html[LF]
# This file was generated by libcurl! Edit at your own risk.[LF]
[LF]
+.me.%09TRUE%09/%09FALSE%090%09a%09b[LF]
```
The whole point of the test seems to be that this cookie like not show up.

### I expected the following

Test 977 to pass.

### curl/libcurl version

curl 8.3.0-DEV (sparc-sun-solaris2.11) libcurl/8.3.0-DEV OpenSSL/1.0.2u zlib/1.2.13 brotli/1.0.2 zstd/1.4.5 libidn2/2.0.4 libpsl/0.21.0 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 libgsasl/1.8.0 OpenLDAP/2.4.40
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc brotli Debug gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system

Solaris 10 & Solaris 11

**Comment by dfandrich** [comment]
The root of the problem looks to be that the call to `psl_is_cookie_domain_acceptable(psl, "firsthost.me.", "me."` in cookie.c:1049 returns 1 on Solaris and 0 on Linux. Maybe a libpsl install problem? Or a libpsl compatibility problem on Solaris?

**Comment by dfandrich** [comment]
Another clue: if the PSL context is retrieved with `psl_builtin()`, then it works fine. If it's retrieved with `psl_latest(NULL)`, then it fails. So, it looks like a libpsl installation problem. In all the failing cases, libpsl comes from OpenCSW.

On further examination, when `psl_latest()` is handed such a file, it produces bad results. If it's handed a compressed file, however, it starts working. The data file supplied by OpenCSW (in /opt/csw/share/public_suffix_list.dat) is uncompressed. This may simply be the problem. @dago does this make sense?

**Comment by bagder** [comment]
This certainly sounds like a libpsl problem or just a bad install.

**Comment by dago** [comment]
This may very well be possible. I'll have a look next week.

**Comment by dfandrich** [comment]
Here's a standalone program I used for testing. 
[badpsl.c.txt](https://github.com/curl/curl/files/12617281/badpsl.c.txt)

**Comment by dago** [comment]
Hi, I did some testing with the latest libpsl 0.21.2 and noticed that all tests with `psl_is_public_suffix2` are failing:
```
loaded 8779 suffixes and 8 exceptions
builtin PSL has 8423 suffixes and 8 exceptions
psl_is_public_suffix2(co.am, PSL_TYPE_ICANN)=0 (expected 1)
psl_is_public_suffix2(co.am, PSL_TYPE_ICANN|PSL_TYPE_NO_STAR_RULE)=0 (expected 1)
psl_is_public_suffix2(co.am, PSL_TYPE_ANY)=0 (expected 1)
psl_is_public_suffix2(co.am, PSL_TYPE_ANY|PSL_TYPE_NO_STAR_RULE)=0 (expected 1)
...
```

Maybe this relates to the error we see in libcurl. Unfortunately I haven't had time yet to look into it more deeply. Apart from that I could not reproduce the error with the compressed suffix file - I tried both compress and gzip with the original filename and couldn't get `badpsl.c` to pass on the OpenCSW buildfarm host `unstable10s`.

**Comment by dfandrich** [comment]
libpsl uses a proprietary compression scheme tuned for its suffix format:
DAFSA, created with the psl-make-dafsa utility.

**Comment by dfandrich** [comment]
@dago, have you had a chance to look at this further? FWIW, creating the `public_suffix_list.dafsa` file is done with the `src/psl-make-dafsa` utility that's built with libpsl.

**Comment by dago** [comment]
Hi @dfandrich I can confirm that the error is no longer seen in your testcase when I use the dafsa-compressed version of the file. However, I still see these errors in the tetstsuite of the current libpsl 0.21.2:
```
psl_is_public_suffix2(co.am, PSL_TYPE_ICANN)=0 (expected 1)
psl_is_public_suffix2(co.am, PSL_TYPE_ICANN|PSL_TYPE_NO_STAR_RULE)=0 (expected 1)
```
I think the errors are connected and I wanted to look into that to also bring the issue upstream to Tim but had some busy weeks behind me. Sorry for the delay.

**Comment by bagder** [comment]
This does not seem to be a curl bug...
