### ISSUE TITLE
CURLOPT_MAX_RECV_SPEED_LARGE not work with curl_multi_perform

### ISSUE THREAD

**Issue by maoxing** [curl/curl#11857]
### I did this

//speed
if (speed != iter->second->_speed) {
//speed
curl_easy_setopt(iter->first, CURLOPT_MAX_RECV_SPEED_LARGE, (curl_off_t)speed);
iter->second->_speed = (curl_off_t)speed;
}

### I expected the following

set the CURLOPT_MAX_RECV_SPEED_LARGE option and find that the download speed is not effectively controlled. Can you provide some help?

this problem occurred after upgrading from version 7.52.1 to 8.1.2. 
Version 7.52.1 can work normally.

### curl/libcurl version

curl 8.1.2

### operating system

Windows and Android

**Comment by icing** [comment]
You'd need to elaborate a bit more. What speed are you setting and what are you observing on what size of transfer?

Background: when receiving a response from a server, there is no direct way to control how much data the server sends. Curl *tries* to pace the receiving, but that will only show visible effects if the transfer is large enough. It also varies by protocol. HTTP/1.1, HTTP/2 and HTTP/3 will all show slightly different behaviour.

**Comment by maoxing** [comment]
> You'd need to elaborate a bit more. What speed are you setting and what are you observing on what size of transfer?
> 
> Background: when receiving a response from a server, there is no direct way to control how much data the server sends. Curl _tries_ to pace the receiving, but that will only show visible effects if the transfer is large enough. It also varies by protocol. HTTP/1.1, HTTP/2 and HTTP/3 will all show slightly different behaviour.

Hello, the way I adjust the download speed is exactly the same as #6162. 

During the batch download process, a low-speed download speed will be dynamically adjusted according to the user's operations. 

Unfortunately, since I upgraded the curl version from 7.52.1 to 8.1. 2,  the speed limit is invalid.

so I am very confused about whether it has anything to do with the options of my compiled library, also I have tried other versions with the same result.

**Comment by icing** [comment]
Do you see differences for HTTP versions?

if you set `curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, version)` and try `CURL_HTTP_VERSION_1_1` and `CURL_HTTP_VERSION_2_0`. So you see differences? Maybe it is not working for HTTP/2 only?

**Comment by maoxing** [comment]
> Do you see differences for HTTP versions?
> 
> if you set `curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, version)` and try `CURL_HTTP_VERSION_1_1` and `CURL_HTTP_VERSION_2_0`. So you see differences? Maybe it is not working for HTTP/2 only?


Yes, i have confirmed that the http version is the same, we have always used HTTP/1.1

**Comment by bagder** [comment]
> a low-speed download speed will be dynamically adjusted according to the user's operations.

Please elaborate. What is the limit set to when the transfer starts and at what point do you change it to what new value? We want to reproduce...

**Comment by bagder** [comment]
No further response. Closing.
