### ISSUE TITLE
libcurl can hang indefinitely instead of failing or retrying.

### ISSUE THREAD

**Issue by jmarrero** [curl/curl#11873]
### I did this

libcurl is used as part of ostree, we are trying to enable doing a couple of retries when there are errors in the connection, while doing this we encountered an issue where curl just hangs forever. We can replicate it with the current ostree version, the issue just takes more time to appear.

To replicate I started qemu VM of FCOS:
and let this script run until the problem happens, this can take hrs...
```
#/bin/bash
sudo systemctl start iptables

sudo iptables -A OUTPUT -p tcp -m statistic --mode random --probability 0.20 -j REJECT --reject-with tcp-reset
sudo iptables -A OUTPUT -p tcp -m statistic --mode random --probability 0.30 -j REJECT --reject-with tcp-reset
sudo iptables -A OUTPUT -p tcp -m statistic --mode random --probability 0.20 -j REJECT --reject-with tcp-reset

ostree --repo=/home/core/repo init
cat /etc/ostree/remotes.d/fedora.conf >> /home/core/repo/config

while [ TRUE ]; do time sudo env G_MESSAGES_DEBUG=all OSTREE_DEBUG_HTTP=1 ostree --repo=/home/core/repo pull fedora:fedora/x86_64/coreos/next ; done
```

I attach the logs I have collected: please let me know if there is additional information that would be helpful.

[ostree-hang-curl.txt](https://github.com/curl/curl/files/12641855/ostree-hang-curl.txt)

### I expected the following

To libcurl to error out or retry but not hang forever.

### curl/libcurl version

curl-8.0.1-2.fc38.x86_64

### operating system

Fedora Linux 38 (CoreOS)

**Comment by bagder** [comment]
The log seems to show curl succeeding to connect, send a request using HTTP/2 but then nothing more happens. 

curl has no default timeout so that seems to work as expected. What am I missing?

**Comment by jmarrero** [comment]
If this is the expected behavior then I am the one missing how those should work. I am not super familiar with the timeout settings to pass to libcurl on this type of situation. We are already passing CURLOPT_CONNECTTIMEOUT. In this case also setting CURLOPT_TIMEOUT should be enough?

**Comment by bagder** [comment]
> I guess in this case also setting CURLOPT_TIMEOUT should be enough?

Yes. Or use CURLOPT_LOW_SPEED_LIMIT or make your own with CURLOPT_PROGRESSFUNCTION.

**Comment by jmarrero** [comment]
Thank you so much! I'll give these a try, sorry for the noise.
