### ISSUE TITLE
curl errors after too many redirects

### ISSUE THREAD

**Issue by Joshix-1** [curl/curl#11871]
### I did this

the command
```
curl -sSfLD - --max-redirs -1 -o /dev/null https://httpbin.org/absolute-redirect/1050
```
outputs the following (shortened):
```
HTTP/2 302 
date: Sat, 16 Sep 2023 20:37:42 GMT
content-type: text/html; charset=utf-8
content-length: 289
location: http://httpbin.org/absolute-redirect/1049
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

...

HTTP/1.1 302 FOUND
Date: Sat, 16 Sep 2023 20:39:03 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 283
Connection: keep-alive
Server: gunicorn/19.9.0
Location: http://httpbin.org/absolute-redirect/2
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

HTTP/1.1 302 FOUND
Date: Sat, 16 Sep 2023 20:39:03 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 283
Connection: keep-alive
Server: gunicorn/19.9.0
Location: http://httpbin.org/absolute-redirect/1
Access-Control-Allow-Origin: *
curl: (56) Too large response headers: 307226 > 307200
```

On a personal project with bigger response headers it exited more quickly (after less redirects). So I'm guessing that the size counter doesn't reset after a redirect.

### I expected the following

`--max-redirs -1` should work correctly. It should follow pointless redirects forever.

### curl/libcurl version

```
curl 8.3.0 (x86_64-pc-linux-gnu) libcurl/8.3.0 OpenSSL/3.1.2 zlib/1.3 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.56.0
Release-Date: 2023-09-13
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

could not reproduce on `7.76.1`

### operating system

Arch Linux

uname -a
```
Linux box 6.1.52-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 07 Sep 2023 05:17:41 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
That's not a "crash", it returns an error.

**Comment by bagder** [comment]
Regression from 3ee79c1674fd6

**Comment by bagder** [comment]
> It should follow pointless redirects forever.

It will not do that. curl keeps headers in memory for easy access after the transfer is done, which thus implicitly limits how many times it can loop when following redirects.

**Comment by Joshix-1** [comment]
Why does it need all the headers?

If it needs them, then that's fine with me, I just think it would need an error message mentioning that. (or an option to not keep all the headers in memory, if that isn't too much work for such a pointless thing)

**Comment by bagder** [comment]
> such a pointless thing

Your pointless is someone else's best feature. And vice versa.

No, it cannot be asked to not store the headers.
