### ISSUE TITLE
Inconsistencies between OpenSSL/GnuTLS and wolfSSL behavior handling CA certificates

### ISSUE THREAD

**Issue by michael-o** [curl/curl#11883]
### I did this

With the introduction of https://github.com/curl/curl/pull/11452 a few inconsistencies are now present in the wolfSSL provider compared to OpenSSL and GnuTLS. Some are even bugs, IMHO:

OpenSSL does:
* Null out CA file when CA info BLOB has been provided:
```
  const char * const ssl_cafile =
    /* CURLOPT_CAINFO_BLOB overrides CURLOPT_CAINFO */
    (ca_info_blob ? NULL : conn_config->CAfile);
  const char * const ssl_capath = conn_config->CApath;
```
but wolfSSL uses `conn_config->CAfile` directly.
* Test for either CA file or CA path when trying to load with `X509_STORE_load_file()`/ `X509_STORE_load_path()`, but:
```
    if(ssl_cafile || ssl_capath) {
```
and
```
  if(conn_config->CAfile) {
    if(1 != wolfSSL_CTX_load_verify_locations(backend->ctx,
                                              conn_config->CAfile,
                                              conn_config->CApath)) {
```
CA path test is missing.
* At the end, OpenSSL does:
```
#ifdef CURL_CA_FALLBACK
    if(!ssl_cafile && !ssl_capath &&
       !imported_native_ca && !imported_ca_info_blob) {
      /* verifying the peer without any CA certificates won't
         work so use openssl's built-in default as fallback */
      X509_STORE_set_default_paths(store);
    }
#endif
```
but wolfSSL does not implement `CURL_CA_FALLBACK` instead it does:
```
  /* load native CA certificates */
  if(ssl_config->native_ca_store) {
    if(wolfSSL_CTX_load_system_CA_certs(backend->ctx) != WOLFSSL_SUCCESS) {
      infof(data, "error importing native CA store, continuing anyway");
    }
    else {
      imported_native_ca = true;
      infof(data, "successfully imported native CA store");
    }
  }
```
If you look at the impl of `wolfSSL_CTX_load_system_CA_certs()`, it does the magic of curl on Windows and macOS to use the system stores, but any other system it does query for dirs and load certs from that. Logically, Both OpenSSL and GnuTLS could decide to do the same with their internal impl which will be opaque to us. I would expect wolfSSL behavior to be the same and not force users/devs to request `--native-ca` just to load certs from `/etc/ssl/certs` and similar. If you still want to confine the behavior of wolfSSL to load from dirs and not Windows Crypto API or Keychain one could use ifdefs around that. Then CA fallback would be consistent for all of these three providers.
OpenSSL: `X509_STORE_set_default_paths()`
GnuTLS: `gnutls_certificate_set_x509_system_trust()`. [This](https://github.com/gnutls/gnutls/blob/055be45c5b5652ecb3da0cc9c720255ae6010b59/lib/system/certs.c#L146) does already query Windows and macOS truststores, so wolfSSL provider is either inconsistent or the GnuTLS one needs to be changed.

If I am completely wrong on these, let me know!

### I expected the following

* Null out CA file
* Test for both CA file *and* CA path
* Use `CURL_CA_FALLBACK` instead of opt-in `--native-ca-store`

### curl/libcurl version

8.3.0

### operating system

FreeBSD 12-STABLE, but any will do with OpenSSL or wolfSSL.

PS: I don't use wolfSSL, but stumbled upon with investigating an improvement to the FreeBSD port of curl, though I strive and prefer consistency between TLS providers.

**Comment by bagder** [comment]
> Use CURL_CA_FALLBACK instead of opt-in --native-ca-store

I am not sure `CURL_CA_FALLBACK` necessarily implies using the native CA store. In fact, the CA fallback is a weirdo configure check and as such it is outside of the libcurl API so I much rather clearly define how the API is supposed to work and not relying on a custom build option.

**Comment by michael-o** [comment]
> > Use CURL_CA_FALLBACK instead of opt-in --native-ca-store
> 
> I am not sure `CURL_CA_FALLBACK` necessarily implies using the native CA store. In fact, the CA fallback is a weirdo configure check and as such it is outside of the libcurl API so I much rather clearly define how the API is supposed to work and not relying on a custom build option.

Honestly, I would rather prefer libcurl to use the default store of the TLS provider and the it can be overridden on request instead of forcing me to pass `CURL_CA_FALLBACK` during configuration time. Wether the TLS provider uses a native store or flat files, that is an implementation detail of the provider. Either way, it looks to me that the current approach with wolfSSL is wrong (point 3) comparing to the other two providers , Schannel and SecureTransport use native stores anyway.

**Comment by michael-o** [comment]
One of the reasons I report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273440

**Comment by bagder** [comment]
`configure --with-ca-fallback` is a custom build option not used by default. It changes behavior and thus it remains opt-in by those who are willing to take that "hit".

We don't do that by default as we want to keep the existing and documented behavior.

That option should not be necessary and in fact not using that option makes it easier for us to know and document curl's behavior more consistently.

**Comment by michael-o** [comment]
> `configure --with-ca-fallback` is a custom build option not used by default. It changes behavior and thus it remains opt-in by those who are willing to take that "hit".
> 
> We don't do that by default as we want to keep the existing and documented behavior.
> 
> That option should not be necessary and in fact not using that option makes it easier for us to know and document curl's behavior more consistently.

That is OK and I accept that, but then I would expect that the new wolfSSL function would be called when `--with-ca-fallback` is paseed, no?

**Comment by bagder** [comment]
> I would expect that the new wolfSSL function would be called when --with-ca-fallback is passed, no?

Would it? That would make it work differently than if you'd built curl with OpenSSL using that same option on for example Windows and macOS.

**Comment by michael-o** [comment]
> > I would expect that the new wolfSSL function would be called when --with-ca-fallback is passed, no?
> 
> Would it? That would make it work differently than if you'd built curl with OpenSSL using that same option on for example Windows and macOS.

True, but that is already the case for GnuTLS. Have a look at the link I provided. GnuTLS does already query native stores.

**Comment by michael-o** [comment]
OpenSSL issue regarding this: https://github.com/openssl/openssl/issues/15887

**Comment by bagder** [comment]
> Your logic wouldn't be valid anymore.

You're logic is funny. You file an issue identifying differences in OpenSSL vs wolfSSL handling, but now you are advocating that we should *willingly* add a new difference between them because *maybe* in a future they *might* then become the same again.

In my personal view, `--with-ca-fallback` is a custom build option and as such it is not a primary concern. We should clearly define exactly what that "fallback" means and what it should be allowed to do and then someone could go through and make sure all the TLS backends do the fallback in that manner.

**Comment by michael-o** [comment]
> > Your logic wouldn't be valid anymore.
> 
> You're logic is funny. You file an issue identifying differences in OpenSSL vs wolfSSL handling, but now you are advocating that we should _willingly_ add a new difference between them because _maybe_ in a future they _might_ then become the same again.

No, I don't. That was purely hypothetical.

> In my personal view, `--with-ca-fallback` is a custom build option and as such it is not a primary concern. We should clearly define exactly what that "fallback" means and what it should be allowed to do and then someone could go through and make sure all the TLS backends do the fallback in that manner.

I just strive for consistency when fallback is requested and wolfssl does provide an option to load default store.

**Comment by bagder** [comment]
> load default store

The option is documented to ask for `Use the built in CA store of the SSL library`. I never thought of that to mean the CA store of the system you run on, but that might just be my own lack of imagination.

**Comment by michael-o** [comment]
> > load default store
> 
> The option is documented to ask for `Use the built in CA store of the SSL library`. I never thought of that to mean the CA store of the system you run on, but that might just be my own lack of imagination.

...and that is an implementation detail of the library, no?

**Comment by bagder** [comment]
> ...and that is an implementation detail of the library, no?

Is it? if you ask the wolfSSL people what their "default store" is, I doubt they can even answer...

**Comment by michael-o** [comment]
> > ...and that is an implementation detail of the library, no?
> 
> Is it? if you ask the wolfSSL people what their "default store" is, I doubt they can even answer...

I can answer that myself looking into the code. From an API user perspective, I leave the decision from where to load it to the library and do the right thing.

**Comment by bagder** [comment]
> Did you look into the GnuTLS code? It is logically identical to wolfSSL.

I trust you on that. Not sure what that changes.

**Comment by bagder** [comment]
This issue mixes several different things. The wolfSSL API mixups are fixed now but the `--with-ca-fallback` difference is not so this issue remains open.

Since the configure option is not part of the API or our behavior promises it is of less importance to me. I have this feeling it was never really used or tested much for other TLS backends than OpenSSL.

**Comment by michael-o** [comment]
> This issue mixes several different things. The wolfSSL API mixups are fixed now but the `--with-ca-fallback` difference is not so this issue remains open.

Correct.

> Since the configure option is not part of the API or our behavior promises it is of less importance to me. I have this feeling it was never really used or tested much for other TLS backends than OpenSSL.

I tested three of them and that is why I am reporting this.

I mean, I can provide PRs to make it consistent with OpenSSL if you like. Maybe it will be clearer to you.

**Comment by bagder** [comment]
> I mean, I can provide PRs to make it consistent with OpenSSL if you like. Maybe it will be clearer to you.

Please do. I think it might also need a documentation snippet explaining what exactly `configure --with-ca-fallback` means and how it will make libcurl behave (for the different backends).

**Comment by michael-o** [comment]
> > I mean, I can provide PRs to make it consistent with OpenSSL if you like. Maybe it will be clearer to you.
> 
> Please do. I think it might also need a documentation snippet explaining what exactly `configure --with-ca-fallback` means and how it will make libcurl behave (for the different backends).

Here is the PR with two distinct commits for the first two issues: https://github.com/curl/curl/pull/11886

The third one I will do with a separate PR. It takes more than just C file changes.

**Comment by michael-o** [comment]
Thanks for the merge of #11884. I will prepare a PR draft for the third issue in the next couple of days which we can discuss.

**Comment by michael-o** [comment]
Working on a new PR already, so far very good. wolfSSL works very nicely with `CAfile` *and* `CApath` as well as CA fallback, just like with OpenSSL. Hope to complete it next week.

**Comment by michael-o** [comment]
Here is the concluding PR to this issue: https://github.com/curl/curl/pull/11934

**Comment by michael-o** [comment]
@bagder, would you mind to have another look? I'd like to start to work on the GnuTLS improvement next week when this is settled.

**Comment by michael-o** [comment]
Since my PR has been forcefully closed by going the discussion in circles I am closing this one. At least some improvements landed upstream.
