### ISSUE TITLE
undefined reference to `curl_ws_send even when WebSocket is enabled in curl

### ISSUE THREAD

**Issue by Sumit1270135** [curl/curl#11899]
### I did this

I install latest libcurl with WebSocket after that i getting this error when i try to compile websocket code.
am i missing something?

<img width="760" alt="image" src="https://github.com/curl/curl/assets/100773861/a77c6df5-3458-4cd1-93ee-df11a6997e16">
<img width="310" alt="image" src="https://github.com/curl/curl/assets/100773861/d3357041-d49b-48f4-a18b-bcf4008eb295">

### curl/libcurl version

curl 8.2.1

### operating system

CentOS Linux x86_64

**Comment by Sumit1270135** [comment]
#include <curl/curl.h>
  2 #include <curl/easy.h>
  3 #include <string.h>
  4
  5 #if 0
  6 int ping(CURL *curl, const char *send_payload)
  7 {
  8   size_t sent;
  9   CURLcode result =
 10     curl_ws_send(curl, send_payload, strlen(send_payload), &sent, 0,
 11                  CURLWS_TEXT);
 12   return (int)result;
 13 }
 14 #endif
 15 void main()
 16 {
 17     //CURL *curl = curl_easy_init();
 18     //if(curl) {
 19     CURL *curl = curl_easy_init();
 20     if(curl) {
 21         CURLcode ret;
 22         curl_easy_setopt(curl, CURLOPT_URL, "ws://example.com/");
 23         //curl_easy_setopt(curl, CURLOPT_CONNECT_ONLY, 2L);
 24         //curl_easy_setopt(curl, CURLOPT_WS_OPTIONS, (long)CURLWS_RAW_MODE);
 25         curl_easy_setopt(curl, CURLOPT_VERBOSE,1L);
 26          ret = curl_easy_perform(curl);
 27         if(ret == CURLE_OK) {
 28             /* only connected! */
 29         }
 30                 //ping(curl,"sumit");
 31     }

**Comment by dfandrich** [comment]
Websocket support is still experimental, so it's not enabled by default in
libcurl. You'll need to compile your own libcurl with it enabled to use it.

**Comment by jay** [comment]
./configure --enable-websockets ...

**Comment by Sumit1270135** [comment]
> Websocket support is still experimental, so it's not enabled by default in libcurl. You'll need to compile your own libcurl with it enabled to use it.

that i already did i enable the Websocket protocol in configuration file and install the libcurl, as you can see in the above screenshot in support protocol ws and wss is present.

**Comment by jay** [comment]
> as you can see in the above screenshot in support protocol ws and wss is present.

Ah I didn't see that. Ok. Please post text and not screenshots. Possibly what is happening is your program is loading a different libcurl shared library and not the one you built. Try `ldd ./a.out`
