### ISSUE TITLE
32-bit ARM: test 0650...FAILED

### ISSUE THREAD

**Issue by zv-io** [curl/curl#11900]
### I did this

Built curl on a 64-bit ARM machine in a 32-bit environment:

```
root@aarch64:/tmp# mkdir x
root@aarch64:/tmp# curl -sO https://distfiles.adelielinux.org/adelie/1.0-beta5/iso/adelie-rootfs-mini-armv7-1.0-beta5-20230829.txz
root@aarch64:/tmp# tar -C x -xf adelie-rootfs-mini-armv7-1.0-beta5-20230829.txz 
root@aarch64:/tmp# mount -B /dev x/dev
root@aarch64:/tmp# mount -t proc proc x/proc
root@aarch64:/tmp# mount -t sysfs sysfs x/sys
root@aarch64:/tmp# setarch linux32 chroot x /bin/sh
# cd
# apk add -q build-tools openssl-dev
# curl -sO https://curl.se/download/curl-8.3.0.tar.gz
# tar -xf curl-8.3.0.tar.gz 
# cd curl-8.3.0
# ./configure --with-openssl
# make -j$(nproc)
# make -j$(nproc) check
...
test 0647...OK (570 out of 1403, remaining: 03:54, took 1.118s, duration: 02:40)
test 0648...OK (571 out of 1403, remaining: 03:53, took 0.088s, duration: 02:40)
test 0649...OK (572 out of 1403, remaining: 03:53, took 0.085s, duration: 02:40)
test 0650...FAILED
test 0651...OK (574 out of 1403, remaining: 03:53, took 0.192s, duration: 02:41)
test 0652...OK (575 out of 1403, remaining: 03:53, took 0.338s, duration: 02:42)
test 0653...OK (576 out of 1403, remaining: 03:53, took 0.253s, duration: 02:42)
...
```

More information (including test logs):
* https://git.adelielinux.org/adelie/packages/-/issues/1060

### I expected the following

All tests to pass.

### curl/libcurl version

```
$ ./src/curl -V
curl 8.3.0 (armv7-foxkit-linux-musleabihf) libcurl/8.3.0 OpenSSL/1.1.1v zlib/1.3 zstd/1.5.4 libssh2/1.10.0 nghttp2/1.52.0
Release-Date: 2023-09-13
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

Adélie Linux (musl-based).

```
Linux builder-arm 5.10.35-00045-g8510b2d4996d #1 SMP PREEMPT Wed Dec 21 12:13:49 UTC 2022 armv7l GNU/Linux
```

**Comment by bagder** [comment]
See also previous comments in  #11882

**Comment by zv-io** [comment]
This bisects to 74b87a8af13a155c659227f5acfa78243a8b2aa6.

**Comment by dfandrich** [comment]
The NetBSD autobuilds are showing the problem as well. In that case, the stderr logs looked effectively identical between the working and non-working cases, but the http_server.log log shows differences. Adding up all the `Read X bytes` in that file, you end up with 28 bytes less in the failing case than the working case, which is exactly the number of bytes missing in the diff. The obvious (though hardly the only) explanation would be that curl is simply not sending those last bytes.

**Comment by bagder** [comment]
To add to the complication: @zv-io's test 650 fail diff here is different than @ncopa's in #11882. 

This diff shows a difference in sent data, while @ncopa's diff shows an unexpected `Cannot rewind mime/post data` message.

So not only does x86 differ from ARM 32 bit, we see two different ARM 32 bit fails!

**Comment by zv-io** [comment]
> To add to the complication: @zv-io's test 650 fail diff here is different than @ncopa's in #11882.
> 
> This diff shows a difference in sent data, while @ncopa's diff shows an unexpected `Cannot rewind mime/post data` message.
> 
> So not only does x86 differ from ARM 32 bit, we see two different ARM 32 bit fails!

The failure in the `diff` immediately above is from commit 74b87a8af13a155c659227f5acfa78243a8b2aa6; I also get `Cannot rewind mime/post data` with the `8.3.0` release tarball.
