### ISSUE TITLE
Curl curl_easy_perform return CURL_OUT_OF_MEMORY (27) 

### ISSUE THREAD

**Issue by AnnTonyt** [curl/curl#11902]
### I did this

while sending out a https curl request from ngixn, i am getting following error
CURL_OUT_OF_MEMORY (27)

size_t write_callback(void* contents, size_t size, size_t nmemb, std::string* output) {
    size_t total_size = size * nmemb;
    output->append(static_cast<char*>(contents), total_size);
    return total_size;
}

void sampleFunc(){}

    CURL *curl;
    CURLcode res;
    struct curl_slist *list = NULL;

    char post_data[1500];

    // TODO - remove the hardcoded
    string key = "777";

    curl_global_init(CURL_GLOBAL_SSL);

    curl =  curl_easy_init();
    if (curl)
    {

        parseConfigurationFile();

        std::string url = "https://" + ospHostIP + ":" + ospRLPort + "/" + cprApiURI + key  ;
        std::string response_data; // To store the response data

        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

        list = curl_slist_append(list, "Content-Type: application/json");

        std::string stemp(ospToken);

        std::string authHeader = "Authorization: Bearer " + stemp;
        list = curl_slist_append(list, authHeader.c_str());

        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, list);

        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);

        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_data);

        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

        res = curl_easy_perform(curl);

        if (res != CURLE_OK)
        {
           cout << "curl_easy_perform() failed: res =" << res << endl;
         }

        curl_slist_free_all(list);
        
        curl_easy_cleanup(curl);

    }

    curl_global_cleanup();

}

### curl/libcurl version

curl 7.87.0 (powerpc-ibm-aix7.2.4.0) libcurl/7.87.0 OpenSSL/1.1.1l
Release-Date: 2022-12-21

### operating system

AIX

**Comment by dfandrich** [comment]
> I expected the following
> 
> No response

I assume you mean: The response CURLE_OK 

The code doesn't show where and how list is defined and initialized. It's also
missing a check that curl_slist_append() doesn't return NULL.  The code for the
callbacks also isn't shown. Does it return CURLE_OUT_OF_MEMORY for a simple
program that just sets CURLOPT_URL and nothing else?

**Comment by AnnTonyt** [comment]
Updated the original msg with the missing data.

authHeader included in the header is a big string of 1502 characters

eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPMklRVFZ6eWJDRngxMzgtUkNKNFA2SkJxMU5aVEFsMlpxOHhtbDNUMmZJIn0.eyJleHAiOjE3NTc3MzU0NzksImlhdCI6MTY5NDY2MzQ3OSwianRpIjoiY2Y1NzEyYmItM2VjYy00NjAxLTkzMmMtYWUxMzhjNDg2ZjJiIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ1Ni9hdXRoL3JlYWxtcy9yb3V0ZWxpbmtjbGllbnQtYXV0aCIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjN2YxY2MzZi1jNmQ5LTQ3MWQtYTRhMi04YzM2MDJlM2NlMmYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyb3V0ZWxpbmtjbGllbnQtbmRiIiwic2Vzc2lvbl9zdGF0ZSI6IjU4MjA1MjE0LWU3YjgtNGM5OC05NTVhLTZkMmUyNWI3NjQwNSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ1NiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsicmxhZG1pbiIsImRlZmF1bHQtcm9sZXMtcm91dGVsaW5rY2xpZW50LWF1dGgiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicm91dGVsaW5rY2xpZW50LW5kYiI6eyJyb2xlcyI6WyJybG1vZGlmeSIsInJsdmlldyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiUm91dGVsaW5rIENsaWVudCBBZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6InJsYWRtaW4iLCJnaXZlbl9uYW1lIjoiUm91dGVsaW5rIENsaWVudCIsImZhbWlseV9uYW1lIjoiQWRtaW4ifQ.51RCf0YlWC23NfUBSnO4uhBEotYrbf7KSf4H_rgQ509eXLFSDC-Vsnk2iHu8dC86uPvijfKSA7sN6tCQXgAkPiuh5UMk1Do1ni9qbnyirIsRb-673LNmkHAvFq-LnQsJxH6XpmZ887NP-uQmA38dfqsgOtdDZTWWJHnJbrQqU-LiqTO2lINsyYlSZU2DKgDZKt9o2H44rnRCfK09n-vPVB_pe2LScgi93Kd82zP6QwsHOJrCOpXqqsI4ZSD1rrz3C21GTAkSjfd6fdpCN8uAlDJReRWo9osz3Jg9eBIyUp4IrcGrLtyZT5DGx1iF7zfnKRP___jtBbxw803fIY7Hzws

**Comment by dfandrich** [comment]
That update shows the definition of `list` but doesn't answer the remaining four points of my response.

**Comment by AnnTonyt** [comment]
For query 1:
        list = curl_slist_append(list, authHeader.c_str());
        if(list == NULL){
        nm_trace(func_name, 0,"  list is NULL \n");
          curl_easy_cleanup(curl); // Clean up libcurl resources
        return ;

For Query 3: updated the original text to include the callback function
size_t write_callback(void* contents, size_t size, size_t nmemb, std::string* output) {
size_t total_size = size * nmemb;
output->append(static_cast<char*>(contents), total_size);
return total_size;
}
For Query 3:
   This curl command is executed from nginx and it is a simple application

Please let me know if you need any other info.

As per the logs i dont get any log that says list is NULL

**Comment by dfandrich** [comment]
Then I suspect the answer to my query #4 will give the answer:
> Does it return CURLE_OUT_OF_MEMORY for a simple program that just sets CURLOPT_URL and nothing else?

I asked this because I guessed that there might be something in the environment that was causing this problem, and now finding out that it's running as a plug-in somewhere else gives some credence to this theory. My theory is that even the most basic curl call will also fail, meaning that you would need to debug the environment to find out why. It's unlikely to be related to libcurl itself in that case.

Note that you need to check the return code from `curl_global_init()` as well.

**Comment by AnnTonyt** [comment]
curl_global_init() returns 0.

**Comment by jay** [comment]
Can you try the [latest](https://curl.se/download.html#AIX) libcurl? Can you give us a self contained example that we can use to reproduce?

**Comment by bagder** [comment]
I believe this is a condition caused by the environment in which this application runs rather than an actual problem in libcurl. This theory can easily be disproven if we just get a stand-alone version that reproduces this problem.

**Comment by bagder** [comment]
No further feedback. If details pop out that contradict our theories, please let us know and we can reopen this again.

**Comment by AnnTonyt** [comment]
Sorry for the delay in response.

Please find below the sample code.
The https request works fine when the CURL request is sent via the standalone application.
the same code when executed from NGINX gives CURL out of memory error.




curl --version
curl 7.87.0 (powerpc-ibm-aix7.2.4.0) libcurl/7.87.0 OpenSSL/1.1.1l
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets



#include <iostream>
#include "curl.h"

int main() {
    CURL* curl;
    CURLcode res;

    // Initialize libcurl
    curl = curl_easy_init();
    if (curl) {
        // Set the target URL
        curl_easy_setopt(curl, CURLOPT_URL, "https://host-ip:port#/ndb/routelink/v1/inbound.api/cpr?sha1=123");

        // Set the HTTP method to GET
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "GET");

        // Set the 'Content-Type' header
        struct curl_slist* headers = NULL;
        headers = curl_slist_append(headers, "Content-Type: application/json");

        // Set the 'Authorization' header
        headers = curl_slist_append(headers, "Authorization: Bearer JWT_token");

        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

        // Allow connections to SSL/TLS sites without certificates
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

		
        // Perform the HTTP request
        res = curl_easy_perform(curl);

        // Check for errors
        if (res != CURLE_OK) {
            fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
        }

        // Clean up
        curl_easy_cleanup(curl);

        // Free the headers
        curl_slist_free_all(headers);

        // Cleanup libcurl
        curl_global_cleanup();
    }

    return 0;
}
