### ISSUE TITLE
Curl wttr.in/Plattsburgh command not working nor any other cities

### ISSUE THREAD

**Issue by ubuntuadam35a** [curl/curl#11933]
### I did this

I tried using the simple curl wttr.in/City and for about the tenth time in the past year it has simply returned error code 52; empty reply from server...Why is the server not reaponding to my Ubuntu terminal running from Termux on my Android. Using the most current version of Termux Linux terminal from the F-Droid website..??

### I expected the following

I am simply trying to pull the 3-day weather forecast with curl .wttr

### curl/libcurl version

most current

### operating system

Ubuntu 22 LTS

**Comment by gvanem** [comment]
Already reported: https://github.com/chubin/wttr.in/issues/856

**Comment by bagder** [comment]
This is not a curl issue.
