### ISSUE TITLE
how can i download and install libcurl.m4

### ISSUE THREAD

**Issue by almoharebh** [curl/curl#1193]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

how can i download and install libcurl.m4
on my pc 
i need link

**Comment by jay** [comment]
As I have already told you, this is an issue tracker. Please ask your libcurl questions on [the mailing list](https://cool.haxx.se/mailman/listinfo/curl-library). libcurl.m4 is in [docs/libcurl/libcurl.m4](https://github.com/curl/curl/blob/curl-7_52_1/docs/libcurl/libcurl.m4).
