### ISSUE TITLE
The Content-Disposition Header in Curl Response for Multipart/Form-Data Request

### ISSUE THREAD

**Issue by RobertPapros2** [curl/curl#11968]
### I did this

```
curl -vvv http://192.168.31.1/update --form "UpdateFile=@file.bin;type=application/octet-stream"  --form 'UpdateParameters={}'
* Expire in 0 ms for 6 (transfer 0x2125908)
*   Trying 192.168.31.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x2125908)
* Connected to 192.168.31.1 (192.168.31.1) port 80 (#0)
> POST /update HTTP/1.1
> Host: 192.168.31.1
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Length: 108526344
> Content-Type: multipart/form-data; boundary=------------------------517c102a522e34e1
> Expect: 100-continue
> 
* Expire in 1000 ms for 0 (transfer 0x2125908)
* Done waiting for 100-continue
< HTTP/1.1 202 Accepted
< Allow: POST
< OData-Version: 4.0
< Location: /TaskService/Tasks/0/Monitor
< Retry-After: 30
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: DENY
< Pragma: no-cache
< Cache-Control: no-Store,no-Cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:; form-action 'none'; frame-ancestors 'none'; object-src 'none'; base-uri 'none'
< Content-Type: application/json
< Date: Fri, 29 Sep 2023 22:02:15 GMT
< Content-Length: 151
< 
{
  "Status": "OK"
* Connection #0 to host 192.168.31.1 left intact
}
```

### I expected the following

I expected to see the 'Content-Disposition' field in the response when using options -v, -vv, or -vvv with curl. 
Is there a way to view this header when making a multipart/form-data request using the curl tool?

### curl/libcurl version

~ # curl -V
curl 7.64.0 (arm-unknown-linux-gnueabi) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system

~ # uname -a
Linux VDP5CFF35FB7A5E 5.4.124-ami #1 SMP Wed Aug 24 03:08:24 UTC 2022 armv7l GNU/Linux

**Comment by bagder** [comment]
(Using `-v` is a boolean, adding more vs will not do anything more.)

> I expected to see the 'Content-Disposition' field in the response

`-v` shows all the response headers. If you don't see a `Content-Disposition` there, the server did not send it.

You can use `--trace-ascii [file]` to get more detailed (full) tracing, but you already see all the response headers here.

**Comment by RobertPapros2** [comment]
@bagder  I've verified it, and on the server side, the 'Content-Disposition' header is present. There's code that rejects requests lacking this header.

**Comment by icing** [comment]
The header is dual-use, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

`curl` uses it on form uploads. It does there appear in the **body** of the request.

`curl` does *not* interpret it in responses, as it general does no parsing of response body data for HTTP. (As far as I know, @bagder correct me if I am wrong)

As suggested, a `--trace-ascii` should show what is send and received in the bodies.

**Comment by bagder** [comment]
> curl does not interpret it in responses

It can, if you use `-J, --remote-header-name`

**Comment by RobertPapros2** [comment]
@bagder maybe I wasn't precise enough. When I mentioned 'response,' I was actually referring to the result of the 'curl' command.

Of course, concerning 'Content-Disposition,' I'm talking about the request header.

Why did I ask this question?
I'm referring to the documentation for the POST method at https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST, which provides an example of using the multipart/form-data content type:

`POST /test HTTP/1.1
Host: foo.example
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="field1"

value1
--boundary
Content-Disposition: form-data; name="field2"; filename="example.txt"

value2
--boundary--`

I thought that after the line with 'boundary=--', 'curl' would display 'Content-Disposition.' But maybe I didn't fully understand the description of the multipart POST method and how the 'curl' command with the -v option works.

**Comment by bagder** [comment]
So you're asking about the header that is part of the **request body** when doing a multipart formpost (not a response header). if you use `--trace-ascii` as explained above you will see the entire chunk of data that curl sends, and then you can see for yourself that curl does indeed include that header in the data.

**Comment by RobertPapros2** [comment]
@icing , @bagder thanks for the response. The '--trace-ascii' option works well, and I can find what I need in the generated trace file.
