### ISSUE TITLE
Range (Start-Stop in bytes) for "--data-binary" option (feature request)

### ISSUE THREAD

**Issue by ricary37** [curl/curl#1198]
I'm trying to resume a 2Gb file upload to Google Drive using REST API.
=========What I have to send===========
PUT {session_uri} HTTP/1.1
Content-Length: 1073741824
Content-Range: bytes 1073741823-2147483647/2147483648

file bytes 1073741823-2147483647
============end of the data===========
However the option "--data-binary @largefile.zip" does not have Range key (Start-Stop in bytes) :(

My feature request:
Could you please add "Start-Stop" in bytes for "--data-binary" option:
Example of the option I would like to see: --data-binary @largefile.zip!1073741823-2147483647
So the curl will read bytes from 1073741823 to 2147483647 of the largefile.zip and send it to the server.

Thank you!

**Comment by bagder** [comment]
You'll have to provide those headers yourself. There's no standard upload resume or upload range in HTTP so curl can't really know what works with your particular server.

**Comment by ricary37** [comment]
bagder, sure I will provide headers.
I would like the curl post my own byte range myStart-myStop bytes (not default 0-FILESIZE).
