### ISSUE TITLE
Documentation: Conflicting statements for create_dirs and output_dir Options

### ISSUE THREAD

**Issue by Rob-S** [curl/curl#11991]
### I did this

Looking at the man page, in docs/cmdline-opts/create-dirs.d it says:

> This option creates the directories mentioned with the --output option, nothing else.

In docs/cmdline-opts/output-dir.d it says:

> If the specified target directory does not exist, the operation fails unless--create-dirs is also used.

### I expected the following

A) If in fact the `--create-dirs` option _creates the directories mentioned with the --output option, nothing else_ (_nothing else_, **including** the `--output-dir` option, for example), then for the `--output-dir` option, whether or not the operation fails would not depend on the `--create-dirs` option being used or not.

or B) If whether or not the operation fails depends on `--create-dir` also being used when the directory specified by `--output-dir` does not exist, then it sounds like the `--create-dirs` option creates directories mentioned in either the `--output` option **_or_** the `--output-dir` option (rather than just the `--output` option and _nothing else_).

I did not create a PR since 1) I'm not 100% sure which is the correct resolution above, A) or more likely B) and someone more familiar with curl internals would be able to use the correct terminology.

### curl/libcurl version

curl 7.87.0

### operating system

N/A

**Comment by bagder** [comment]
How about this as an update for the `--create-dirs` documentation?

When used in conjunction with the --output option, curl creates the necessary
local directory hierarchy as needed. This option creates the directories
mentioned with the --output option combined with the path possibly set with
--output-dir. If the combined output file name uses no directory, or if the
directories it mentions already exist, no directories are created.
