### ISSUE TITLE
remove libsuff in configue.ac

### ISSUE THREAD

**Issue by zhengjiezxxy** [curl/curl#1199]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
Currently, I need to build curl under 64bit machine.
At first, I build curl 7.50.1 by a script like following:
./buildconf
./configure  CFLAGS=-I/usr/local/include --without-zlib --disable-ldap --disable-ldaps --disable-pop3 --disable-imap --disable-smtp --without-libmetalink --with-ssl=/usr/local --with-libssh2=/usr/local --enable-debug --enable-curldebug --prefix=/usr/local --libdir=/usr/local/lib64/ &&
make

Then, I want to build curl 7.51.0, build fails for cannot find openssl and libssh2 library in the correct directory. The error is:
usr/local/lib/libssh2.so: could not read symbols: File in wrong format

But libssh2.so is actually in /usr/local/lib64/.
So at last I need to add a flags like this to make build works:
./buildconf
./configure  libsuff=64 CFLAGS=-I/usr/local/include --without-zlib --disable-ldap --disable-ldaps --disable-pop3 --disable-imap --disable-smtp --without-libmetalink --with-ssl=/usr/local --with-libssh2=/usr/local --enable-debug --enable-curldebug --prefix=/usr/local --libdir=/usr/local/lib64/ &&
make

But What confusing me is that previous build is successful, in the next build, I need add some hack to get work done, I cannot find the reason
### I expected the following
curl build succesfully
### curl/libcurl version
 curl 7.51.0
[curl -V output perhaps?]
usr/local/lib/libssh2.so: could not read symbols: File in wrong format
### operating system
redhat 6 64bit

**Comment by bagder** [comment]
I suspect this happens because `/usr/local/lib` has been added to the link path already before the libssh2 check so ld finds and uses the lib in the wrong path before it finds it in the specific path where the libssh2 tests check for it.

This configure script flaw is already mentioned in [KNOWN_BUGS](https://curl.haxx.se/docs/knownbugs.html#configure_finding_libs_in_wrong).

**Comment by zhengjiezxxy** [comment]
I don't this is a known bugs.
In my all Makefiles:
LDFLAGS = -L/usr/local/lib -L /usr/local/lib

This corresponding to two check (openssl and libssh2).
But I think it's caused by this part of code.
configure first use pkgconfig check ldflags, but hardcode lib in OPENSSL_PCDIR path.
and then give a guess.
So it generates the previous Makefile.
But libsuff is internal to libtool and I cannot find docs about how to use this variable.
So this cause undefined behaviour, I think.

~~~~
    dnl Try pkg-config even when cross-compiling.  Since we
    dnl specify PKG_CONFIG_LIBDIR we're only looking where
    dnl the user told us to look
    OPENSSL_PCDIR="$OPT_SSL/lib/pkgconfig"
    AC_MSG_NOTICE([PKG_CONFIG_LIBDIR will be set to "$OPENSSL_PCDIR"])
    if test -f "$OPENSSL_PCDIR/openssl.pc"; then
      PKGTEST="yes"
    fi

    dnl in case pkg-config comes up empty, use what we got
    dnl via --with-ssl
    LIB_OPENSSL="$PREFIX_OPENSSL/lib$libsuff"
~~~~

**Comment by bagder** [comment]
Oh, so does it work if we use `libsuff` for the directory name where we look for pkgconfig as well?
~~~
--- a/configure.ac
+++ b/configure.ac
@@ -1455,11 +1455,11 @@ if test "$curl_ssl_msg" = "$init_ssl_msg" && test X"$OPT_SSL" != Xno; then
     PREFIX_OPENSSL=$OPT_SSL
 
     dnl Try pkg-config even when cross-compiling.  Since we
     dnl specify PKG_CONFIG_LIBDIR we're only looking where
     dnl the user told us to look
-    OPENSSL_PCDIR="$OPT_SSL/lib/pkgconfig"
+    OPENSSL_PCDIR="$OPT_SSL/lib$libsuff/pkgconfig"
     AC_MSG_NOTICE([PKG_CONFIG_LIBDIR will be set to "$OPENSSL_PCDIR"])
     if test -f "$OPENSSL_PCDIR/openssl.pc"; then
       PKGTEST="yes"
     fi

**Comment by zhengjiezxxy** [comment]
The error is still the same.

build.sh
~~~~
./buildconf
#CFLAGS=-I$HOME/usr/include 
./configure CFLAGS=-I/usr/local/include --without-zlib --disable-ldap --disable-ldaps --disable-pop3 --disable-imap --disable-smtp --without-libmetalink --with-ssl=/usr/local --with-libssh2=/usr/local --enable-debug --enable-curldebug --prefix=/usr/local --libdir=/usr/local/lib64/ &&

make

~~~~
Makefile
~~~~
LDFLAGS = -L/usr/local/lib64 -L /usr/local/lib
~~~~

error
~~~~
 CC     libcurl_la-mbedtls.lo
  CCLD   libcurl.la
/usr/local/lib/libssh2.so: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
make[2]: *** [libcurl.la] Error 1
make[2]: Leaving directory `/root/iflash/curl/lib'
~~~~

diff
~~~~
diff --git a/configure.ac b/configure.ac
index 74f2316..13da166 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1457,7 +1457,7 @@ if test "$curl_ssl_msg" = "$init_ssl_msg" && test X"$OPT_SSL" != Xno; then
     dnl Try pkg-config even when cross-compiling.  Since we
     dnl specify PKG_CONFIG_LIBDIR we're only looking where
     dnl the user told us to look
-    OPENSSL_PCDIR="$OPT_SSL/lib/pkgconfig"
+    OPENSSL_PCDIR="$OPT_SSL/lib$libsuff/pkgconfig"
     AC_MSG_NOTICE([PKG_CONFIG_LIBDIR will be set to "$OPENSSL_PCDIR"])
     if test -f "$OPENSSL_PCDIR/openssl.pc"; then
       PKGTEST="yes"
~~~~

**Comment by bagder** [comment]
But now the fault is different, right? Which check adds `/usr/local/lib` to the -L path?

**Comment by zhengjiezxxy** [comment]
The fault is same. Because in configure.ac, libssh2 check is after openssl check.
and libsuff is empty, so 

~~~~
  dnl if given with a prefix, we set -L and -I based on that
  if test -n "$PREFIX_SSH2"; then
    LIB_SSH2="-lssh2"
    LD_SSH2=-L${PREFIX_SSH2}/lib$libsuff
    CPP_SSH2=-I${PREFIX_SSH2}/include
    DIR_SSH2=${PREFIX_SSH2}/lib$libsuff
~~~~~

This will add LD_SSH2 to LDFLAGS.

**Comment by neovasant** [comment]
Additional info to this conversation : I faced similar issue while compiling libcurl for both 32 and 64 bit arch. There was no issue with 32 bit compilation but for 64 bit LDFLAGS was pointing to 32 bit openssl location. Setting libsuff did not work for me and I had to override LDFLAGS before invoking make.

**Comment by bagder** [comment]
I'm totally lost on this issue and I need a reset and start over to get somewhere. Preferably start with a configure run completely without setting LDFLAGS, CFLAGS or LIBS.

**Comment by bagder** [comment]
I still need clarification and this seems to have gone stale. Closing.
