### ISSUE TITLE
Range (Start-Stop in bytes) for "--data-binary" option (feature request)

### ISSUE THREAD

**Issue by ricary37** [curl/curl#1200]
bagder, seems you didn't understand what I was trying to request in https://github.com/curl/curl/issues/1198 and closed the thread, so I will explain in other words. 

I don't want curl to set headers for "--data-binary".
I'd like curl to send exact set of bytes to the server.
Technially it would be like:

If I add the option "--data-binary @largefile.zip!1073741823-2147483647"
then curl does:
open(F, "largefile.zip");
seek(F, SEEK_SET, 1073741823);
read(F, $buf, 2147483647-1073741823+1);
send(SOCKET, $buf)

**Comment by bagder** [comment]
We don't keep feature requests open in the issue tracker, as they aren't really current issues. See https://curl.haxx.se/docs/bugs.html#TODO for an explanation how we use the tracker. Unfortunately, we're drowning in good ideas and it is always easy to bring more of those. Turning them into working and good code is however not as easy.

My suggestion for the short to medium term would be to a small script that
1. creates an intermediary file on disk with the 1073741823-2147483647 content
2. uploads that file (with whatever set of custom headers that are necessary)
3. removes the file again

**Comment by ricary37** [comment]
bagder, i've made my perl wrapper already :)
Could you please add this nice feature request in your long waiting/todo list.
I hope somebody will help us with the code.
