### ISSUE TITLE
SSL error unable to set private key file: '/iscp/tls/new.key' type PEM when running CURL command using SSL certificate

### ISSUE THREAD

**Issue by AnnTonyt** [curl/curl#12029]
### I did this

The cert and key file are generated using the below command

openssl req -x509 -days 365 -newkey rsa:2048 -keyout /iscp/tls/new.key -out /iscp/tls/new.crt

Code snippet
----------------

	  

        // Allow connections to SSL/TLS sites without certificates
        res = curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
        if (res != CURLE_OK)
        {
              nm_trace(func_name, 0,"  curl_easy_perform failed , 111 res : %d  \n", res);
        }
        res = curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 1L);
        if (res != CURLE_OK)
        {
              nm_trace(func_name, 0,"  curl_easy_perform failed , 111 res : %d  \n", res);
        }

        /* ask libcurl to use TLS version 1.0 or later */
        curl_easy_setopt(curl, CURLOPT_SSLVERSION, 3);

        // Set the path to your SSL certificate file
        curl_easy_setopt(curl, CURLOPT_SSLCERTTYPE, "PEM");
        curl_easy_setopt(curl, CURLOPT_SSLCERT, "/iscp/tls/new.crt");
        curl_easy_setopt(curl, CURLOPT_SSLKEY, "/iscp/tls/new.key");

        char errbuf[CURL_ERROR_SIZE];

         /* provide a buffer to store errors in */
        curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);

### curl/libcurl version

curl 8.3.0

### operating system

AIX

**Comment by embetrix** [comment]
@AnnTonyt you generated the key with a passphrase and you didn't configure it in curl :

https://curl.se/libcurl/c/CURLOPT_KEYPASSWD.html

**Comment by AnnTonyt** [comment]
Is it OK to generate the SSL certificate without the key and use the same certificate while sending curl request?

Does CURL accept certificate with .crt extension?

**Comment by embetrix** [comment]
It depends on your server configuration !

curl will accept either PEM oder DER formats :

https://curl.se/libcurl/c/CURLOPT_SSLCERTTYPE.html

**Comment by AnnTonyt** [comment]
Please consider the issue as closed. with curl 8.3.0 build with higher SSL version its working fine.
There was some compatibility issue.

Thanks again for the support!
