### ISSUE TITLE
some error while curl 7.52.1 build with '--with-darwinssl' on iOS

### ISSUE THREAD

**Issue by dustmob** [curl/curl#1202]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this

I tried to compile ios target with darwinssl.

### I expected the following

build library for ios (arm64) successfully.

### curl/libcurl version

[curl -V output perhaps?]

7.52.0 , 7.52.1

### operating system

macos sierra

**Comment by jay** [comment]
That isn't enough information. Please give us some detail on what happened, for example show us the log. Also, this is an issue tracker used for tracking bugs, not help requests. If you just have a question about building the library please close this issue and ask on [the mailing list](https://cool.haxx.se/mailman/listinfo/curl-library) instead. Thanks

**Comment by dustmob** [comment]
I got log below...

vtls/darwinssl.c:939:11: error: implicit declaration of function 'SecCertificateCopyCommonName' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
          SecCertificateCopyCommonName(cert, &common_name);
          ^

and I checked source code of curl library... (darwinssl.c)
then I found below

static OSStatus CopyIdentityWithLabel(char *label,
                                      SecIdentityRef *out_cert_and_key)
{
  OSStatus status = errSecItemNotFound;
  CFArrayRef keys_list;
  CFIndex keys_list_count;
  CFIndex i;
  CFStringRef common_name;

#if CURL_BUILD_MAC_10_7 || _**CURL_BUILD_IOS**_
  /* SecItemCopyMatching() was introduced in iOS and Snow Leopard.
     kSecClassIdentity was introduced in Lion. If both exist, let's use them
     to find the certificate. */
  if(SecItemCopyMatching != NULL && kSecClassIdentity != NULL) {
    CFTypeRef keys[5];
    CFTypeRef values[5];
    CFDictionaryRef query_dict;
    CFStringRef label_cf = CFStringCreateWithCString(NULL, label,
      kCFStringEncodingUTF8);

    /* Set up our search criteria and expected results: */
    values[0] = kSecClassIdentity; /* we want a certificate and a key */
    keys[0] = kSecClass;
    values[1] = kCFBooleanTrue;    /* we want a reference */
    keys[1] = kSecReturnRef;
    values[2] = kSecMatchLimitAll; /* kSecMatchLimitOne would be better if the
                                    * label matching below worked correctly */
    keys[2] = kSecMatchLimit;
    /* identity searches need a SecPolicyRef in order to work */
    values[3] = SecPolicyCreateSSL(false, NULL);
    keys[3] = kSecMatchPolicy;
    /* match the name of the certificate (doesn't work in macOS 10.12.1) */
    values[4] = label_cf;
    keys[4] = kSecAttrLabel;
    query_dict = CFDictionaryCreate(NULL, (const void **)keys,
                                    (const void **)values, 5L,
                                    &kCFCopyStringDictionaryKeyCallBacks,
                                    &kCFTypeDictionaryValueCallBacks);
    CFRelease(values[3]);

    /* Do we have a match? */
    status = SecItemCopyMatching(query_dict, (CFTypeRef *) &keys_list);

    /* Because kSecAttrLabel matching doesn't work with kSecClassIdentity,
     * we need to find the correct identity ourselves */
    if(status == noErr) {
      keys_list_count = CFArrayGetCount(keys_list);
      *out_cert_and_key = NULL;
      for(i=0; i<keys_list_count; i++) {
        OSStatus err = noErr;
        SecCertificateRef cert = NULL;
        *out_cert_and_key =
          (SecIdentityRef) CFArrayGetValueAtIndex(keys_list, i);
        err = SecIdentityCopyCertificate(*out_cert_and_key, &cert);
        if(err == noErr) {
          **_SecCertificateCopyCommonName_**(cert, &common_name);
          if(CFStringCompare(common_name, label_cf, 0) == kCFCompareEqualTo) {
            CFRelease(cert);
            CFRelease(common_name);
            status = noErr;
            break;
          }
          CFRelease(common_name);
        }
        *out_cert_and_key = NULL;
        status = 1;
        CFRelease(cert);
      }
    }

    CFRelease(query_dict);
    CFRelease(label_cf);
  }


SecCertificateCopyCommonName function is not allowed on iOS platform.

Thank you for your reply.

**Comment by bagder** [comment]
I believe this bug was already fix in git with commit 8db3afe16c091 can you try out git master?

**Comment by dustmob** [comment]
You're right!! git master source was built very well. 
I tried to build with source from downloaded archieve (curl-7.52.1.tar.gz).
Thank you :D

**Comment by bagder** [comment]
Cool, fixed!
