### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by DerXanRam** [curl/curl#12039]
### I did this

Hello sir.... sorry for opening this issue and sorry for my behavior :pray:  .. i'm trying to subscribe webscoket communication to 

`wss://bsc-mainnet.blastapi.io/c0f8ce24-de37-4003-ab56-9967b73f87e9`

i know websocket communication in curl is experimental and i aware of that. But i have no choice. I try a lot of thing, i searched over the internet and i asked [here in the discussion](https://github.com/curl/curl/discussions/12016) and i can't find any solution. I'm pretty new to curl and web programming using c++. Please help for the love of God. I stacked in the middle of my project.

What i was trying to accomplish using python is 

```python
import asyncio
import json
from web3 import Web3
from websockets import connect

infura_ws_url = 'wss://bsc-mainnet.blastapi.io/c0f8ce24-de37-4003-ab56-9967b73f87e9'
infura_http_url = 'https://bsc-mainnet.blastapi.io/01af2e8d-fbe7-4c5c-b1e4-86591aaed49f'
web3 = Web3(Web3.HTTPProvider(infura_http_url))

# Used if you want to monitor ETH transactions to a specific address
account = '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73' 

async def get_event():
    async with connect(infura_ws_url) as ws:
        await ws.send('{"jsonrpc": "2.0", "id": 1, "method": "eth_subscribe", "params": ["newPendingTransactions"]}')
        subscription_response = await ws.recv()
        print(subscription_response)

        while True:
            try:
                message = await asyncio.wait_for(ws.recv(), timeout=15)
                response = json.loads(message)
                txHash = response['params']['result']
                print(txHash)
            except:
                pass

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    while True:
        loop.run_until_complete(get_event())
```
if u ran this code u can clearly see stream of transaction hashes.  

I already build `libcurl` from source and enabled websocket....Pleasesssssss :pray:  :pray:  :pray:  :pray: 

### curl/libcurl version

curl 8.30

### operating system

Ubuntu 2022

**Comment by dfandrich** [comment]
libcurl is a low-level interface to WebSockets and you need to be pretty familiar with the protocol to use it. If you've gone through al the documentation and example programs and are still stuck, you should consider [commercial support](https://curl.se/support.html).

**Comment by DerXanRam** [comment]
I found another way.... here it is, it may help some one

```
#include <iostream>
#include <cpprest/ws_client.h>

using namespace std;
using namespace web;
using namespace web::websockets::client;

int main() {
  websocket_client client;
  client.connect("wss://api.poloniex.com").wait();

  websocket_outgoing_message out_msg;
  out_msg.set_utf8_message("test");
while(true)
{
  client.send(out_msg).wait();
  client.receive().then([](websocket_incoming_message in_msg) {
    return in_msg.extract_string();
  }).then([](string body) {
    cout << body << endl; // test
  }).wait();
}
  client.close().wait();

  return 0;
}
```
