### ISSUE TITLE
http3 quiche: QUIC connection is draining

### ISSUE THREAD

**Issue by mb** [curl/curl#12037]
### I did this

Running curl3 (curl with quiche) from AUR: https://aur.archlinux.org/packages/curl-http3
Connecting to the mozilla-central http3 test server using the first port outputted by the http3server.

    $ SSLKEYLOGFILE=~/tmp/test.keys curl3 -i --http3-only https://127.0.0.1:41996/hello --insecure -vv
    * processing: https://127.0.0.1:41996/hello
    *   Trying 127.0.0.1:41996...
    * Connected to 127.0.0.1 (127.0.0.1) port 41996
    * using HTTP/3
    * Using HTTP/3 Stream ID: 0
    > GET /hello HTTP/3
    > Host: 127.0.0.1:41996
    > User-Agent: curl/8.2.1
    > Accept: */*
    > 
    * QUIC connection is draining
    * Connection #0 to host 127.0.0.1 left intact
    curl: (95) QUIC connection is draining

The error is coming from:

* <https://github.com/curl/curl/blob/5ee0b9dd6eeea6ec66085fee128aa8173a60f0f6/lib/vquic/curl_quiche.c#L927>
* https://docs.rs/quiche/0.18.0/quiche/struct.Connection.html#method.is_draining
  > Returns true if the connection is draining.
  > 
  > If this returns true, the connection object cannot yet be dropped, but no new application data can be sent or received. An application should continue calling the recv(), timeout(), and on_timeout() methods as normal, until the is_closed() method returns true.
  >
  > In contrast, once is_draining() returns true, calling send() is not required because no new outgoing packets will be generated.

draining is not an error to drop the connection. As far as I can tell the connection is terminated on that error.

Test server binaries and wireshark capture including the SSLKEYLOGFILE: [test-setup.zip](https://github.com/curl/curl/files/12819131/test-setup.zip)

### I expected the following

I would expect the connection not to be terminated, but to be continued. I hope I understand it correctly and this is really a bug here, sorry if not.

### curl/libcurl version

```
$ curl3 --version
curl 8.2.1 (x86_64-pc-linux-gnu) libcurl/8.2.1 BoringSSL zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.56.0 quiche/0.17.2 librtmp/2.3
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe UnixSockets zstd
```

### operating system

```
$ uname -a
Linux archlinux 6.5.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
Can you reproduce this against a publicly available URL?

**Comment by mb** [comment]
I don't know any publicly available server with that error. I tried to setup the http3server on my test server. Unfortunately, I can't reproduce there https://curl-neqo.neon.rocks:4433. I don't get to the stage where I connect and haven't been able to send out the `GET /` request, because the connection gets reset for some reason. `curl3 -vv --http3-only https://curl-neqo.neon.rocks:4433`

```
 curl3 -vv --http3-only https://curl-neqo.neon.rocks:4433
* processing: https://curl-neqo.neon.rocks:4433
*   Trying 89.58.41.211:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*   Trying 89.58.41.211:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*   Trying 89.58.41.211:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*   Trying 89.58.41.211:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*   Trying 89.58.41.211:4433...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
[...]
```

```
curl3 -vv --http3-only https://curl-neqo.neon.rocks:4433 --insecure
* processing: https://curl-neqo.neon.rocks:4433
*   Trying 89.58.41.211:4433...
*   Trying 89.58.41.211:4433...
*   Trying 89.58.41.211:4433...
*   Trying 89.58.41.211:4433...
[...]
```

**Comment by icing** [comment]
@mb could you try the current `master`? We have made changes in the retry behaviour when connecting to servers that immediately go into DRAINING state.

**Comment by bagder** [comment]
@mb ?

I can't repro that problem with `--http3-only https://curl-neqo.neon.rocks:4433` just now:

~~~
$ curl --http3-only https://curl-neqo.neon.rocks:4433
curl: (8) Failed to connect to curl-neqo.neon.rocks port 4433 after 104 ms: Weird server reply

**Comment by icing** [comment]
You can send a URL to localhost with `curl  --resolve curl-nego.neon.rocks:4433:127.0.0.1`. Then the hostname the server sees may work better for you.

**Comment by bagder** [comment]
@mb does this still happen?

**Comment by mb** [comment]
I retried and yes it is still happening. I've enabled debug build now and it is panicing:
<details>

```
user@archlinux ~/g/curl (master)> curl -I --http3-only https://127.0.0.1:40668 --insecure -vv
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => SETUP handle 0x637fccf6eca8; line 1987
* STATE: SETUP => CONNECT handle 0x637fccf6eca8; line 2003
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => CONNECTING handle 0x637fccf6eca8; line 2039
*   Trying 127.0.0.1:40668...
* Server certificate:
*  subject: CN= HTTP2 Test Cert
*  start date: Jan  1 00:00:00 2017 GMT
*  expire date: Jan  1 00:00:00 2027 GMT
*  issuer: CN= HTTP2 Test CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Connected to 127.0.0.1 (127.0.0.1) port 40668
* using HTTP/3
* STATE: CONNECTING => PROTOCONNECT handle 0x637fccf6eca8; line 2147
* STATE: PROTOCONNECT => DO handle 0x637fccf6eca8; line 2176
* [HTTP/3] [0] OPENED stream for https://127.0.0.1:40668/
* [HTTP/3] [0] [:method: HEAD]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: 127.0.0.1:40668]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.8.1-DEV]
* [HTTP/3] [0] [accept: */*]
> HEAD / HTTP/3
> Host: 127.0.0.1:40668
> User-Agent: curl/8.8.1-DEV
> Accept: */*
> 
* STATE: DO => DID handle 0x637fccf6eca8; line 2272
* STATE: DID => PERFORMING handle 0x637fccf6eca8; line 2390
* QUIC connection is draining
* readwrite_data() -> 95
* Curl_readwrite() -> 95
* multi_done[PERFORMING]: status: 95 prem: 1 done: 0
* Connection #0 to host 127.0.0.1 left intact
* Expire cleared
curl: (95) QUIC connection is draining
thread '<unnamed>' panicked at library/core/src/panicking.rs:156:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
fish: Job 1, 'curl -I --http3-only https://12…' terminated by signal SIGABRT (Abort)
```
</details>

I've now an [rr recording](https://github.com/user-attachments/files/15513017/curl-rr.tar.xz.zip) and related [pernoco session](https://pernos.co/debug/IPoNMQGwz5QYd0rtvw3QsQ/index.html). Unfortunatly I don't know if you can access the latter for debugging :(. And sorry for weird file ending. xz was one of the only ones reaching <25MB and .zip is one of the few supported file endings here on github.

**Comment by mb** [comment]
* from_raw_parts doesn't allow null pointers for the data: https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety
* quiche passes reason string to from_raw_parts: https://github.com/cloudflare/quiche/blob/731510ee2027e533622b4c583a12632c1cbaaec5/quiche/src/ffi.rs#L973
* We pass in the null pointer here: https://github.com/curl/curl/blob/acb9effcdd647b6daf753526ac18c84cb903ee72/lib/vquic/curl_quiche.c#L1474
Either quiche needs to be changed to allow null pointers for the reason or we need to pass in a reason here. Not sure what is better, this is probably a separate bug though.
