### ISSUE TITLE
Test hangs in event mode

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#12033]
### I did this

Test 1233 (as well as 1272 and 1238, although I have less data about those) has been hanging 100% of the time in the event-based CI build ever since commit b5bb84cbef (PR #11939) . I can reproduce this 100% of the time on my local Linux machine by performing parallel tests enabling event mode and using the `FTP` keyword to select tests. The last log message produced by the curl under test is:
```
 0000: 229 Entering Passiv Mode (|||1|)
```

Running with the `GOPHER` keyword causes test 1272 to hang.

Running with the `TFTP` keyword cases test 1238 to hang for about 2000 seconds until it times out and fails.

The latter two test hangs can be reproduced easily without parallel mode, but the first one seems to need it.

- [X] fixed test 1233
- [ ] fixed test 1238
- [ ] fixed test 1272

### I expected the following

The tests should pass without hanging.

### curl/libcurl version

8.4.0-DEV

### operating system

CI build machine:

Linux fv-az736-78 6.2.0-1012-azure #12~22.04.1-Ubuntu SMP Thu Sep  7 14:07:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
@icing Maybe you have an idea abuot this?

**Comment by icing** [comment]
Interesting. Well, first of all, thanks for tracking this down.

I will have a look if the introduced change can be done in a better way.

**Comment by bagder** [comment]
Test 1233 is fixed by #12042.

**Comment by bagder** [comment]
And the other two by #12056
