### ISSUE TITLE
"--request" option and "location: www1" processing

### ISSUE THREAD

**Issue by ricary37** [curl/curl#1205]
### I did this
curl --request POST --data-binary @file.dat www1
www1 replied:
> HTTP/1.1 302 Object moved
> Location: http://www2

### I expected the following
that curl would followed the location correctly like:
>GET / HTTP/1.1
Host: www2

but curl sent:
>POST / HTTP/1.1
Host: www2

so I got error:
>HTTP/1.1 411 Length Required
### curl/libcurl version
7.52.1
### operating system
Windows 10 x64

**Comment by jay** [comment]
Don't set the request method to POST, when you do that then any redirect uses that method as well. Using --data-binary already sets it POST. See https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

> One of most obvious problems is that if you also tell curl to follow HTTP redirects (using -L or –location), the -X option will also be used  on the redirected-to requests which may not at all be what the server asks for and the user expected. Dropping the -X will make curl adhere to what the server asks for. And if you want to alter what method to use in a redirect, curl already have dedicated options for that named –post301, –post302 and –post303!

**Comment by ricary37** [comment]
could you add these options then:
>      --get301       Do not switch to POST after following a 301 redirect (H)
>      --get302       Do not switch to POST after following a 302 redirect (H)
>      --get303       Do not switch to POST after following a 303 redirect (H)

**Comment by jay** [comment]
From the [manual](https://curl.haxx.se/docs/manpage.html#-L):

> When curl follows a redirect and the request is not a plain GET (for example POST or PUT), it will do the following request with a GET if the HTTP response was 301, 302, or 303. If the response code was any other 3xx code, curl will re-send the following request using the same unmodified method.

So don't set a custom request of POST and by default it will switch your request to GET on 302.

**Comment by bagder** [comment]
Also, we already support: `--no-post301`, `--no-post302` and `--no-post303`

The `--no-` handling works for all boolean options.

**Comment by ricary37** [comment]
bagder,
1. "curl --help" does not show "--no-" option
2. "--no-post302" does not work. curl still sends POST instead of GET.
ps: curl 7.52.1 Windows x64.

**Comment by bagder** [comment]
1. "man curl" explains the `--no-` construct at the top of the **OPTIONS** section. Using `--no-` for a boolean option is the opposite of setting it: ie it switches it off. So if you'd set an option in your .curlrc or similar, you can switch it off again on the command line.
2. `"--no-post302` switches off `--post302`. So no, it won't send a POST in that case. But the "post30X" options do no override -X so if you set `-X POST`, you will still get that method used. Since you asked for it.
