### ISSUE TITLE
8.4.0 failing compilation on "RUN checksrc" with "--enable-debug"

### ISSUE THREAD

**Issue by xypiie** [curl/curl#12087]
### I did this

./configure --enable-debug --with-openssl
make

...
  CC       ../lib/libcurltool_la-version_win32.lo
  CC       ../lib/libcurltool_la-warnless.lo
  RUN      checksrc
  CC       ../lib/base64.o
  CC       ../lib/curl_multibyte.o
  CC       ../lib/dynbuf.o
  CC       ../lib/nonblock.o
  CC       ../lib/timediff.o
  CC       ../lib/version_win32.o
  CC       ../lib/strtoofft.o
  CC       ../lib/warnless.o
  CCLD     curl
./tool_stderr.c:62:1: warning: STDERR already disabled from line 35 (BADCOMMAND)
   /* !checksrc! disable STDERR 1 */
 ^
./tool_stderr.c:69:1: warning: STDERR already disabled from line 35 (BADCOMMAND)
   /* !checksrc! disable STDERR 1 */
 ^
./tool_stderr.c:35:18: warning: Unused ignore: STDERR (UNUSEDIGNORE)
   /* !checksrc! disable STDERR 1 */
                  ^
checksrc: 0 errors and 3 warnings
checksrc: 0 errors and 10 warnings suppressed
make[2]: *** [Makefile:2037: checksrc] Error 5

### I expected the following

successful build

### curl/libcurl version

curl 8.4.0

### operating system

archlinux

**Comment by Romain-Geissler-1A** [comment]
See #12084 and the upcoming fix for the release tarballs in #12085
