### ISSUE TITLE
Curl 8.4.0 fails to build because of a checksrc error. File src/.checksrc is missing from release tarball

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [curl/curl#12084]
### I did this

Hi,

See my comments in #11958, it seems that the release tarball for curl 8.4.0 misses the file `src/.checksrc`. When we try to build it from sources, we get this when checksrc is ran:

```
09:20:40  ./tool_stderr.c:62:1: warning: STDERR already disabled from line 35 (BADCOMMAND)
09:20:40     /* !checksrc! disable STDERR 1 */
09:20:40   ^
09:20:40  ./tool_stderr.c:69:1: warning: STDERR already disabled from line 35 (BADCOMMAND)
09:20:40     /* !checksrc! disable STDERR 1 */
09:20:40   ^
09:20:40  ./tool_stderr.c:35:18: warning: Unused ignore: STDERR (UNUSEDIGNORE)
09:20:40     /* !checksrc! disable STDERR 1 */
09:20:40                    ^
09:20:40  checksrc: 0 errors and 3 warnings
09:20:40  checksrc: 0 errors and 10 warnings suppressed
```

We have downloaded this tarball https://curl.se/download/curl-8.4.0.tar.gz where apparently the newly added file `src/.checksrc` is missing. If we apply this patch to add it back, it works:

```
This file is committed in git, but missing from the curl 8.4.0 tarball, and makes the build fail if missing.

--- /dev/null
+++ src/.checksrc
@@ -0,0 +1 @@
+enable STDERR
```

So... shall there be a new 8.4.1 release with the file included in the tarball ?

Cheers,
Romain

### I expected the following

Build works from the official tarball.

### curl/libcurl version

curl 8.4.0

### operating system

Ubuntu 22.04.

**Comment by Romain-Geissler-1A** [comment]
@tawmoto From what I see in the latest git commits, a release 8.4.1 is currently being cut, so I would expect "very soon" ;)

**Comment by bagder** [comment]
This has not been decided. From my perspective, this is a rather minor build nuisance that might not in itself suffice to make us to a quick patch release. The fact that we work on 8.4.1 now is just because we just shipped 8.4.0 so if we don't merge any feature, the next release will become 8.4.1.

But I'm not ruling it out either.

**Comment by tawmoto** [comment]
thank you, Daniel.
any chance to update the tarballs to contain the missing file for 8.4.0?

**Comment by bagder** [comment]
We cannot modify a release, we can only do new releases.

**Comment by MarcelRaad** [comment]
@bagder 
> From my perspective, this is a rather minor build nuisance that might not in itself suffice to make us to a quick patch release.

Building with `--enable-debug` fails by default, so I'd consider it rather major, no? At least together with the CMake cross-build failure from https://github.com/curl/curl/issues/12093, and maybe the Android and `CURL_DISABLE_VERBOSE_STRINGS` build breaks issues currently open, I think a patch release would make sense.
