### ISSUE TITLE
Can't build curl with wolfssl static

### ISSUE THREAD

**Issue by posterberg** [curl/curl#12080]
### I did this

# WOLFSSL
```
./configure --prefix=/home/kali/src/bullshit/libwolfssl --enable-distro --disable-benchmark  --disable-examples --enable-staticmemory --enable-static --enable-psa-lib-static
make -j4
make install
```

# CURL
```
env PKG_CONFIG_PATH=../libwolfssl/lib/pkgconfig ./configure  --without-ssl --disable-shared --enable-shared=no --enable-static --enable-static=yes --with-wolfssl=../libwolfssl
```

OUTPUT
======
snip
```
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for wolfssl options with pkg-config... found
configure: Check dir yes/lib/pkgconfig
configure: Add -L/home/kali/src/bullshit/libwolfssl/lib  to LDFLAGS
configure: Add -I/home/kali/src/bullshit/libwolfssl/include  to CPPFLAGS
configure: Add -lwolfssl  to LIBS
checking for wolfSSL_Init in -lwolfssl... no
configure: error: --with-wolfssl but wolfSSL was not found or doesn't work
```
/snip

Manual test for wolfSSL_Init with nm
====================================
```
 nm ../libwolfssl/lib/libwolfssl.a| grep wolfSSL_Init
000000000002e95a T wolfSSL_Init
```

### curl/libcurl version

CURL
git checkout curl-8_3_0

WOLFSSL
git checkout v5.5.3-stable

### operating system

Kali 2023.3

**Comment by dfandrich** [comment]
It could be that the wolfssl.pc file isn't set up properly for a static
library. Are you able to successfully link a hello world program to this
WolfSSL build using pkgconfig?  Also, look into config.log to see what
configure doesn't like about it.

**Comment by posterberg** [comment]
I am not all that used to pkgconfig. I did however get the same problem when not trying to use pkgconfig, but instead just using --with-wolfss=<path>.

The pkgconfig file looks like this
```
prefix=/home/kali/src/bullshit/libwolfssl
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: wolfssl
Description: wolfssl C library.
Version: 5.6.3
Libs: -L${libdir} -lwolfssl
Cflags: -I${includedir}
```
Thank's for the tip about `config.log`, it clearly says that I am missing `config.h`.

```
configure:28019: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers   -I/home/kali/src/bullshit/libwolfssl/include    -L/home/kali/src/bullshit/libwolfssl/lib  conftest.c -lwolfssl  -lz   >&5
conftest.c:45:10: fatal error: wolfssl/options.h: No such file or directory
   45 | #include <wolfssl/options.h>
      |          ^~~~~~~~~~~~~~~~~~~
```

Looking in the include folder shows that the file is missing. Question is why it wasn't included when I ran `make install`.  I've never used wolfssl before so I have no idea what I should expect to find in this folder. But I assume that options.h should be there...

```
➜ ls
openssl/  wolfcrypt/  callbacks.h  certs_test.h  crl.h  error-ssl.h  ocsp.h  quic.h  sniffer.h  sniffer_error.h  ssl.h  test.h  version.h  wolfio.h
```

Do you know why it is missing?

**Comment by dfandrich** [comment]
I don't know why that wasn't installed. I haven't used WolfSSL in a few years but options.h definitely used to be installed.

**Comment by posterberg** [comment]
The git repo `wolfssl` folder has several .h-files that didn't get copied to the install folder.

repo
```
ls
openssl/  wolfcrypt/  callbacks.h  certs_test.h  crl.h  error-ssl.h  include.am  internal.h  ocsp.h  options.h  options.h.in  quic.h  sniffer.h  sniffer_error.h  sniffer_error.rc  ssl.h  test.h  version.h  version.h.in  wolfio.h
```

Install folder
```
ls
openssl/  wolfcrypt/  callbacks.h  certs_test.h  crl.h  error-ssl.h  ocsp.h  quic.h  sniffer.h  sniffer_error.h  ssl.h  test.h  version.h  wolfio.h
```

I now manuallt copied everything from the repo folder to the installed include folder of wolfssl. After that it worked to configure curl.

Seems like there's something wrong with `make install` in wolfssl.

Thanks for the assistance!!

**Comment by jay** [comment]
> Seems like there's something wrong with `make install` in wolfssl.

If you can reproduce then report it to them https://github.com/wolfSSL/wolfssl/issues
