### ISSUE TITLE
Curl failing with Failed sending curl request with error:SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by Bab95** [curl/curl#12098]
### I did this

I am using libcurl version 7.87.0 in my application. In some cases i am seeing this error.

This error is not consistent. It happens in some environments.

`
Failed sending curl request with error:SSL peer certificate or SSH remote key was not OK
`
in curl call setting up basic options like below

```
curl_easy_setopt(curl_, CURLOPT_HTTPHEADER, headers_);
    curl_easy_setopt(curl_, CURLOPT_URL, url_.c_str());

    if (http_method_ == "POST") {
        curl_easy_setopt(curl_, CURLOPT_CUSTOMREQUEST, "POST");
        curl_easy_setopt(curl_, CURLOPT_POSTFIELDS, payload_.c_str());
        curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE, payload_.size());
        curl_easy_setopt(curl_, CURLOPT_CAINFO, "curl-ca-bundle.crt");
    }
    
#ifdef TRACE_LEVEL_HIGH
    Logger.log("TRACE_LEVEL_HIGH");
    curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, trace);
    curl_easy_setopt(curl, CURLOPT_DEBUGDATA, 1L);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_SSLv3 | CURL_SSLVERSION_MAX_TLSv1_2);
#endif

    curl_easy_setopt(curl_, CURLOPT_TIMEOUT, timeout_);

    std::string result;
    curl_easy_setopt(curl_, CURLOPT_WRITEFUNCTION, WriteResponseCallback);
    curl_easy_setopt(curl_, CURLOPT_WRITEDATA, &result);
```

curl-ca-bundle.crt is the the latest bundle downloaded form curl website. 

I have added the extra logging to get TLS handshake logs which are as follow:
 
```
 trace:63 == Info: Trying <IP Address>:443...
trace:63 == Info: Connected to <Attestation URL> (IP from Above) port 443 (#0)
 trace:63 == Info: ALPN: offers http/1.1
trace:63 == Info: CAfile: curl-ca-bundle.crt
trace:63 == Info: CApath: none
trace:74 => Send SSL data: <some characters>
trace:63 == Info: [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):
trace:74 => Send SSL data:
trace:83 <= Recv SSL data: <Some different characters>
trace:63 == Info: [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):
 trace:83 <= Recv SSL data: <Some different characters>
 trace:63 == Info: [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Certificate (11):
trace:83 <= Recv SSL data: <Some different characters>
 trace:74 => Send SSL data: <some characters>
 trace:63 == Info: [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS alert, unknown CA (560):
trace:74 => Send SSL data: <some characters>
 trace:63 == Info: SSL certificate problem: unable to get local issuer certificate
trace:63 == Info: Closing connection 0
curl::SendRequest:: Failed sending curl request with error:SSL peer certificate or SSH remote key was not OK
sendHttpRequest: Failed to send http request with error:Failed  sending curl request with error:SSL peer certificate or SSH remote key was not OK
sendAttestationRequest:Failed to send http request with error:Failed  sending curl request with error:SSL peer certificate or SSH remote key was not OK
```

### I expected the following

Https request should complete.

### curl/libcurl version

libucurl version **7.87**
Application linking type static
TLS backed: openssl static linking version **1.1.1**

### operating system

Windows Server 2022.
This issue is reproducing on some linux distros as well.

**Comment by bagder** [comment]
This sounds curl working as expected. You connect to a HTTPS site that uses a certificate that is not signed by a CA in your "CA store".

**Comment by jay** [comment]
This is unlikely to be a curl issue.

You can use [CURLINFO_CERTINFO](https://curl.se/libcurl/c/CURLINFO_CERTINFO.html) to see the certificates in the chain. The last certificate shown the issuer is the root CA (ie what should be in your CA store). Note you will have to temporarily disable peer verification (see the certinfo doc) because we don't record the certs from OpenSSL unless the TLS handshake is successful.

For example lines like this
~~~
Subject:C = US, O = DigiCert Inc, CN = DigiCert TLS RSA SHA256 2020 CA1
Issuer:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
~~~

`DigiCert Global Root CA` is what should be in the CA bundle (and it is).

**Comment by Bab95** [comment]
Yeah I got it. Do we have an option to use System's default cert store in case of OSSL TLS backend? I think I am asking for the following https://github.com/bch/curl/commit/fc7a6500ad448cccb34fe112b64ebe453c5bba44
If it is being supported in libcurl and if so how to use it?
If not implemented for libcurl can it be implemented?

**Comment by jay** [comment]
As you can see in that commit curl_easy_setopt(curl, [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html), CURLSSLOPT_NATIVE_CA).

You will probably not need a fall back since OpenSSL can check both at the same time:

> If you set this option and also set a CA certificate file or directory then during verification those certificates are searched in addition to the native CA store.
