### ISSUE TITLE
osreldate.h doesn't exist on PlayStation

### ISSUE THREAD

**Issue by fffaraz** [curl/curl#12107]
### I did this

Build fails on PlayStation due to missing `osreldate.h`

### curl/libcurl version

curl 8.4.0

### operating system

PlayStation

**Comment by jay** [comment]
https://github.com/curl/curl/blob/d755a5f7c009dd63a61b2c745180d8ba937cbfeb/include/curl/curl.h#L68-L71

FreeBSD manual [says](https://docs.freebsd.org/en/books/porters-handbook/porting-dads/#porting-versions) use `#include <sys/param.h>`.

I'm not sure why we're using osreldate, maybe for legacy reasons. What version of FreeBSD are you using? What happens if you `#include <sys/param.h>`

**Comment by bagder** [comment]
The include was brought in 2009, apparently to fix a build with FreeBSD < v8: https://github.com/curl/curl/commit/b89789d82fdb2df7adc8d00e7574ab0e531c3f7b

**Comment by bagder** [comment]
Maybe #12109 ?

**Comment by emaste** [comment]
osreldate.h should exist on any FreeBSD version, but sys/param.h is also fine for defining `__FreeBSD_version`.

Here's a rather recent commit I found when looking for details: https://github.com/freebsd/freebsd-src/commit/90eaf4b2f98f2678b3dc707f9781a887eee94b1a

**Comment by Freaky** [comment]
FreeBSD manual also says to use `osreldate.h`, [sysctl(3)](https://man.freebsd.org/cgi/man.cgi?query=sysctl&apropos=0&sektion=3&manpath=FreeBSD+13.2-RELEASE+and+Ports&arch=default&format=html):

    The userland release version is available from <osreldate.h>;
    parse this file if you need to get the release version of the
    currently installed userland.

It's used a fair bit by the base system, [including this example of how to find the FreeBSD version](https://github.com/freebsd/freebsd-src/blob/922337e8d3989e4f54a0338b7fc397e3e0af7832/share/examples/FreeBSD_version/FreeBSD_version.c).

**Comment by bagder** [comment]
Thank you both @emaste and @Freaky. This seems to rather imply that either @fffaraz's setup is bad somehow or Sony has done something "fun" for the PlayStation that requires a special take.

Either way, my take in 12109 seems incorrect.

**Comment by fffaraz** [comment]
PlayStation sdk does not have `osreldate.h` but it does have `sys/param.h` and it defines `__FreeBSD_version` as
`#define __FreeBSD_version 900044    /* Master, propagated to newvers */`

**Comment by dfandrich** [comment]
FWIW, I checked a FreeBSD 6.2 image I have lying around and either `sys/param.h` or `osreldate.h` work fine to define `__FreeBSD_version`.

**Comment by Freaky** [comment]
`osreldate.h` is generated during the build, while `sys/param.h` is a static source of truth in the source tree, used by `sys/conf/newvers.sh`.  Perhaps some setup step for the SDK's been missed?

**Comment by bagder** [comment]
Based on all the comments, I figure we can just include `sys/param.h` instead? I made #12123 for that.
