### ISSUE TITLE
error.message: HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by maassg** [curl/curl#12114]
### I did this

Connecting to **https://www.java.com/** does not work:

* WARNING: failed to open cookie file ""
*   Trying [2a02:26f0:1700:a::b856:6717]:443...
* Connected to www.java.com (2a02:26f0:1700:a::b856:6717) port 443
* ALPN: curl offers h2,http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=Redwood City; O=Oracle Corporation; CN=java.com
*  start date: Dec 13 00:00:00 2022 GMT
*  expire date: Dec 13 23:59:59 2023 GMT
*  subjectAltName: host "www.java.com" matched cert's "www.java.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://www.java.com/de/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: www.java.com]
* [HTTP/2] [1] [:path: /de/]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET /de/ HTTP/2
Host: www.java.com
User-Agent: curl/8.4.0
Accept: */*

* old SSL session ID is stale, removing
* HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
* Connection #0 to host www.java.com left intact
>>> status: 0
**error.message: HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)**

### I expected the following

content of page  https://www.java.com/de/

### curl/libcurl version

**curl 8.4.0** (x86_64-pc-linux-gnu) libcurl/8.4.0 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.11.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

older default version **7.88.1-10+deb12u4** of my linux distro doesn't work either.

### operating system

[CODE]MX-23_x64 Libretto July 31  2023 base: Debian GNU/Linux 12  (bookworm)[/CODE]

**Comment by jay** [comment]
Unfortunately it looks like java.com bans curl user agents. The server sends RST_STREAM with error INTERNAL_ERROR when curl/ is in the user agent. When I change the user agent to nonsense it works. When I change it to Google Chrome that works as well:

~~~
curl -v -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" https://www.java.com/en/
~~~

**Comment by maassg** [comment]
Thanks a lot!
