### ISSUE TITLE
Error: SSL routines::unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by GattoExpress999** [curl/curl#12122]
### I did this

I can't download any page from https://www.gigroup.it/ . Chrome can.
I know what is the problem, I know it's a server issue, but Curl can get through with the right ssl parameter, parameter that Curl has not at the moment.
I need a way to reach the site also if it is insecure in some way.
I'm stucked.

### curl/libcurl version

Curl

### operating system

Ubuntu

**Comment by jay** [comment]
Duplicate of #8943
