### ISSUE TITLE
Test 1014 failure on FreeBSD 6.2

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#12125]
### I did this

This test failues to to curl reporting `threadsafe` but not `curl-config`
```
Mismatch in features lists:
curl:        alt-svc asynchdns ipv6 largefile libz threadsafe unixsockets
curl-config: alt-svc asynchdns ipv6 largefile libz unixsockets
test 1014...[Compare curl --version with curl-config --features]
 1014: postcheck FAILED
== Contents of files in the log/1/ dir after test 1014
=== Start of file server.cmd
 Testnum 1014
=== End of file server.cmd
=== Start of file stdout1014
 curl 8.4.1-DEV (i586-unknown-freebsd6.2) libcurl/8.4.1-DEV zlib/1.2.3
 Release-Date: [unreleased]
 Protocols: dict file ftp gopher http imap mqtt pop3 rtsp smtp telnet tftp
 Features: alt-svc AsynchDNS IPv6 Largefile libz threadsafe UnixSockets
=== End of file stdout1014
```
The configure test `checking for stdatomic.h` returns `no`, which is correct—it doesn't exist. However, `pthread.h` does exist.

This may be related to #12090.

### I expected the following

No test errors.

### curl/libcurl version

curl-8.4.0-dev

### operating system

FreeBSD 6.2 i386

**Comment by jay** [comment]
Please try #12127 in autotools and cmake and see if it says threadsafe in the build results
