### ISSUE TITLE
curl tool won't search for curlrc (no leading dot) in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by jay** [curl/curl#12129]
### I did this

@b-jazz reported in [#8208 (comment)](https://github.com/curl/curl/issues/8208#issuecomment-1763283082) that when curl is searching for the .curlrc file, it searches XDG_CONFIG_HOME for .curlrc but does not search it for curlrc (no leading dot).

The original reporter of #8208 reported that as well. When that issue was fixed by 764e4f06 it did not fix that part of the issue. Instead it was written in a specific way to not do that. findfile will search for curlrc (no leading dot) in $CURL_HOME/.config/curlrc and $HOME/.config/curlrc, but only if XDG_CONFIG_HOME is not set and .curlrc has not been found anywhere else.

Here's two typical setups and how curl currently behaves:

If CURL_HOME is not set, and XDG_CONFIG_HOME is set, and HOME is set, then the order is:

- $XDG_CONFIG_HOME/.curlrc
- $HOME/.curlrc
- [`pw_dir`](https://pubs.opengroup.org/onlinepubs/009604499/basedefs/pwd.h.html)/.curlrc

If CURL_HOME is not set, and XDG_CONFIG_HOME is **not** set, and HOME is set, then the order is:

- $HOME/.curlrc
- $HOME/.config/curlrc _(this path is checked because XDG_CONFIG_HOME is not set)_
- [`pw_dir`](https://pubs.opengroup.org/onlinepubs/009604499/basedefs/pwd.h.html)/.curlrc

Note pw_dir is usually the same as $HOME.

Note for brevity I've excluded how we also search for _curlrc when .curlrc is not found, since that logic just complicates understanding this and AFAICT it's not relevant here.

### I expected the following

I'm not sure if this is a bug or not since the commit was written specifically not to strip the dot from curlrc when checking XDG_CONFIG_HOME, and I can't figure from the discussion why it was done that way.

### curl/libcurl version

curl 8.4.0

### operating system

Linux

**Comment by jay** [comment]
[-K, --config](https://curl.se/docs/manpage.html#-K) doc says it should be doing `$XDG_CONFIG_HOME/curlrc` so then is there not supposed to be any `$XDG_CONFIG_HOME/.curlrc`? If that's the case fixing it won't be as simple as turning on `withoutdot` member for XDG_CONFIG_HOME because there's logic that skips XDG_CONFIG_HOME in that case.

**Comment by b-jazz** [comment]
Other applications that put stuff in `~/.config` usually have no leading dot in that top level since the work of hiding all these configs is done at the top level itself.  But whatever the outcome is, the real bug might be that the man page doesn’t match the implementation in the current version and that will cause confusion.

**Comment by jay** [comment]
Well on further thought I think the ship has sailed so to speak, as it's likely that users are already using .curlrc in XDG_CONFIG_HOME since that's all that has worked, however we can add another ship for curlrc in XDG_CONFIG_HOME. It's too late now to recall it. Again I don't know why this wasn't done if it was a bug or what but I'm going to treat it as one and write up a PR

**Comment by bagder** [comment]
I think it is a bug.

**Comment by sukanto-earth** [comment]
Hi everyone,

I'm new to contributing to libcurl, and I'd like to work on this issue. I'll start investigating and update here with my progress. Any guidance or tips would be greatly appreciated.

Thanks,
Sukanto

**Comment by bagder** [comment]
@sukanto-earth I believe the core of this logic is in `src/tool_findfile.c:findfile()`
