### ISSUE TITLE
Create an official NuGet Package

### ISSUE THREAD

**Issue by rogersachan** [curl/curl#1213]
I think curl should create an official NuGet package because:

* NuGet has allowed the downloading of C++ libraries for use in C++ projects since 2013. 
* The unofficial downloads exceed 100K per month
* Makes it easier for development
* Most *unofficial* curl libraries available on NuGet date back to last year and are thousands of commits behind.
    * This leads unjust blame on curl for not maintaining "their" packages and creates issues for already fixed bugs. 
* NuGet works on Linux and Mac via build scripts
* Popular libraries like Boost are available and kept up to date.

**Comment by bagder** [comment]
What exactly does it mean to "support NuGet" ? Isn't it "just" to put a package together and announce it somehow?

Note that the curl project doesn't have *any* official binary packages. We ship source code. Everyone is entitled and encouraged to produce the packages that are useful from that source code.

**Comment by bagder** [comment]
There seems to be a [curl package](https://www.nuget.org/packages/rmt_curl/) there that is reasonably updated already.

**Comment by rogersachan** [comment]
@bagder NuGet can be used to package the source, not just the binaries.

Also note that this project linked is a by-product of the now defunct CoApp, so it lacks package splitting.

**Comment by bagder** [comment]
> NuGet can be used to package the source, not just the binaries

Okay. I don't think it changes my point much though,. Anyone and everyone is free to make such a package and upload it to nuget. And keep doing it for subsequent releases. That's how curl exists on all Linux/BSD distros, macOS and more.

> this project you linked to is a by-product of the now defunct CoApp

Sounds like a bug report to *them* or perhaps a reason for someone else to make a different nuget package.

I'm not completely opposed to someone wanting to do this as an "official curl package", but we're generally very short on people working on the Windows platform in general and I've so far never seen anyone in the project express a particular interest in in nuget, neither as user nor as producer of packages.

The curl project produces only one thing really: source code. This source code exists in a git repository and when we make releases we generate tarballs from that. The tarballs are then provided using a few different compression/archiving formats, but they all have the exact same contents.

We simply don't have the manpower to do much more. If there's really a *desire* to have a nuget package of curl, then I assume that there will also be at least one person out there willing to do the package. And apparently, as I linked to above, there is such a person. And if there's a problem with his7her package, I hope that you join in and help improving that package.

**Comment by rogersachan** [comment]
@bagder Thank you for your time
