### ISSUE TITLE
curl 8.3.0 no longer includes HTTP reason text in error message as curl 7.68.0 did

### ISSUE THREAD

**Issue by dschepler** [curl/curl#12159]
### I did this

I have the curl library connecting to a REST agent that includes some useful text in the HTTP header of a 422 response.  (With curl_easy_setopt of CURLOPT_FAILONERROR.)

### I expected the following

With curl 7.68.0, the error string returned in the CURLOPT_ERRORBUFFER reads: "The requested URL returned error: 422 Bad or missing txpos or rxpos"
With curl 8.3.0, the error string returned in the CURLOPT_ERRORBUFFER reads only: "The requested URL returned error: 422"

That extra information was useful to display to the user to help them and/or our support team to diagnose the cause of the error.  It would be nice if we could get this information back in the error message.

### curl/libcurl version

curl 8.3.0

### operating system

curl 7.68.0 is from the Ubuntu 20 packages
curl 8.3.0 is a custom build from source on Windows

**Comment by bagder** [comment]
Correct, that message was dropped from the error message many years ago. That "reason phrase" is also completely dropped from HTTP/2 and HTTP/3 where they cannot even be provided. This is not a bug, we just decided to unify the handling and we removed that error message output. It is extremely rare that the message is used for anything other than just the RFC standard string for the response code.
