### ISSUE TITLE
curl and send some commands to server then stalls

### ISSUE THREAD

**Issue by TheBetterSolution** [curl/curl#12151]
### I did this

A client app and server and the https protocol (by openssl3.0.8)
1. Client app connect to server and send 4 commands continuously to server.
2. Get the log message for the all commands : "We are completely uploaded and fine".
3. Server received the first 3 packets, processed them and returned the response to client.
4. From server log, the server received the 4th packet after about 5 minutes.
5. From the wireshark, the first 3 packets is sent immediately, the 4th packet is sent after about 5 minutes.

Please note:
1. The server add "connection:close" in the http header in every response, client will send "Encrypted alert (close)" after received server's response.
2. Use curl version 8.3 doesn't reproduce this case.

### I expected the following

The 4 packets will send continuously and immediately.

### curl/libcurl version

curl 8.4.0

### operating system

Windows/Linux/MacOS

**Comment by dfandrich** [comment]
"We are completely uploaded and fine" is only displayed once curl has sent all
the data to the lower layer for sending. Any delays from that point are due to
lower layers in the stack. My first guess would be plain network delays, but
there are other things going on depending on the protocol (you didn't say which
one you're using), or issues in the OS network layer. There have to be packets
received from the server during this time, but you didn't mention when they
came in in relation to the outgoing ones. You also didn't say which libcurl
options you're using, which can affect transfers, or whether you're using the
multi interface and what your multi loop looks like. Are you really seeing this
exact issue on three completely different operating systems?

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by TheBetterSolution** [comment]
Thanks for your response, @bagder 
Here is another strange case:
The timeout_ms in the timeout in 8.4 version callback is very longer than the value in 8.3 version.
    8.4 version:
    0, 90000, -1, 0, 90000, -1, 0, 90000, -1, 0, 90000, 0, 89890, 0, 89719, 87658, 0, 87818, 429965, 0, 90000, -1, 0, 90000, -1
   8.3 version:
    0, 199, -1, 0, 199, -1, 0, 199, -1, 0, 199, 0, 86, 55, 0, 31, 87593, 87615, 0, 199, 429787, -1, 0, 199, -1
The client and server deployment is complicated, that's not good choice for testing, I try to develop an test version to reproduce this error for you.

**Comment by TheBetterSolution** [comment]
> Thanks a lot for your report!
> 
> I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

I guess there is a special situation:
    1. Client send 4 requests to server (only 3 requests are sent, last request is in the internal sending buffer).
    2. Client received the server's response for the first request and the response contains the "connection: close" header.
    3. Client processed the response and close the connection.
    What's the status of the last request in the sending buffer?

**Comment by TheBetterSolution** [comment]
> es in the OS network layer.
Thanks for your response, there are the answers:
the protocol:
openssl 3.0.8 tls1.2 https

Issues in the OS network layer:
libcurl 8.3 can't reproduce this issue in the same environment.

When they came in in relation to the outgoing ones:
The responses for the first 3 request are received in time no longer than 100 ms, but the last one is about 5 minutes.

Whether you're using the multi interface:
We multi interface and we use the timer callback and the socket callback to drive multi interface to run.

Are you really seeing this exact issue on three completely different operating systems?
Yes, exactly.

Please note the libcurl version 8.3 is stable.

**Comment by bagder** [comment]
`curl https://curl.se https://curl.se https://curl.se https://curl.se`

Makes 4 requests in a serial fashion one by one against the same server. Works fine for me.

**Comment by TheBetterSolution** [comment]
> `curl https://curl.se https://curl.se https://curl.se https://curl.se`
> 
> Makes 4 requests in a serial fashion one by one against the same server. Works fine for me.

If I removed the "connection: close" http header, this issue can't be produced.

**Comment by bagder** [comment]
`curl curl.se curl.se curl.se curl.se`

Makes 4 requests in a serial fashion one by one against the same server. Works fine for me. **With** `connection: close` header.

**Comment by TheBetterSolution** [comment]
I found the difference log messages between the good connection and the delayed connection:

The good connection:
11:22:53.143+08:00: TEXT on request 0x55638af68da0: WARNING: failed to open cookie file ""
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] added
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] connect, init
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] connect, check h21
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [HAPPY-EYEBALLS] created ipv4 (timeout 90000ms)
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [HAPPY-EYEBALLS] ipv4 starting (timeout=90000ms)
11:22:53.143+08:00: TEXT on request 0x55638af68da0:   Trying 192.168.9.130:4443...
11:22:53.143+08:00: TEXT on request 0x55638af68da0:   Trying 192.168.9.130:4443...
11:22:53.143+08:00: TEXT on request 0x55638af68da0: [TCP] cf_socket_open() -> 0, fd=30
11:22:53.144+08:00: TEXT on request 0x55638af68da0: [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
11:22:53.144+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] connect -> 0, done=0
11:22:53.144+08:00: CURLMOPT_TIMERFUNCTION: timeout = 90000 msec
11:22:53.144+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] get_selected_socks(h21) -> 10000
11:22:53.144+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] get_selected_socks -> 10000
11:22:53.157+08:00: TEXT on request 0x55638af68da0: [HTTPS-CONNECT] connect, check h21
11:22:53.157+08:00: TEXT on request 0x55638af68da0: [TCP] connected
11:22:53.157+08:00: TEXT on request 0x5567fafb4b60: [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=1
11:22:53.157+08:00: TEXT on request 0x5567fafb4b60: Connected to 192.168.9.130 (192.168.9.130) port 4443
11:22:53.157+08:00: TEXT on request 0x5567fafb4b60: Connected to 192.168.9.130 (192.168.9.130) port 4443
11:22:53.157+08:00: TEXT on request 0x5567fafb4b60: [SSL] cf_connect()

The delayed connection:
11:22:53.367+08:00: TEXT on request 0x556282fdac26: WARNING: failed to open cookie file ""
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] added
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] connect, init
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] connect, check h21
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HAPPY-EYEBALLS] created ipv4 (timeout 90000ms)
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HAPPY-EYEBALLS] ipv4 starting (timeout=90000ms)
11:22:53.367+08:00: TEXT on request 0x556282fdac26:   Trying 192.168.9.130:4443...
11:22:53.367+08:00: TEXT on request 0x556282fdac26:   Trying 192.168.9.130:4443...
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [TCP] cf_socket_open() -> 0, fd=32
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] connect -> 0, done=0
11:22:53.367+08:00: CURLMOPT_TIMERFUNCTION: timeout = 90000 msec
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] get_selected_socks(h21) -> 10000
11:22:53.367+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] get_selected_socks -> 10000
11:24:23.367+08:00: CURLMOPT_TIMERFUNCTION: timeout = 104 msec
11:24:23.472+08:00: TEXT on request 0x556282fdac26: [HTTPS-CONNECT] connect, check h21
11:24:23.472+08:00: TEXT on request 0x556282fdac26: [TCP] connected
11:24:23.472+08:00: TEXT on request 0x556282fdac26: [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=1
11:24:23.472+08:00: TEXT on request 0x556282fdac26: Connected to 192.168.9.130 (192.168.9.130) port 4443
11:24:23.472+08:00: TEXT on request 0x556282fdac26: Connected to 192.168.9.130 (192.168.9.130) port 4443
11:24:23.472+08:00: TEXT on request 0x556282fdac26: [SSL] cf_connect()

Please note the elapsed time for HAPPY-EYEBALLS:
The delayed connection elapsed the seconds for connection timeout (90s).

Is it possible that timer for HAPPY-EYEBALLS isn't working correctly?

**Comment by TheBetterSolution** [comment]
> `curl curl.se curl.se curl.se curl.se`
> 
> Makes 4 requests in a serial fashion one by one against the same server. Works fine for me. **With** `connection: close` header.

The order for responses isn't same as the order for requests in my environment, that maybe different.

**Comment by bagder** [comment]
This log output for the TIMERFUNCTION callback makes me think your application is using `curl_multi_socket_action()`. Is it ?

If so, what sockets and activity is your application waiting for (that does not happen) in those 90 "stalling" seconds? It looks like the connect has happened but libcurl has not been told...

**Comment by TheBetterSolution** [comment]
> This log output for the TIMERFUNCTION callback makes me think your application is using `curl_multi_socket_action()`. Is it ?
Correct.

Thanks.

**Comment by bagder** [comment]
I think the second part of the question was the important part...

**Comment by TheBetterSolution** [comment]
> I think the second part of the question was the important part...

I found an issue that rarely happened:
1. Client creates curl instance 1 to start the request 1.
2. Curl opens a socket, for example: socket 1.
3. Do some work for request 1...
4. If Curl received the server's close connection message (for example: "connection: close"), the socket will be closed first, please refer to the socket_close function in https://github.com/curl/curl/blob/master/lib/cf-socket.c.
5. And then set the curl instance to be CURLMSG_DONE state, please refer to https://github.com/curl/curl/blob/master/lib/multi.c.
6. Client calls curl_multi_remove_handle to remove this curl instance, because it detects the  CURLMSG_DONE state.
7. Client removes the polling process for the socket 1 (just use socket as key to identify the polling process, isn't with curl instance).

But if a new request 2 is coming, and the same socket 1 is returned by socket() function again (because step 1 already closed it, OS can reuse this socket value) between the above step 4 and step 5, the new request 2 polling process may be removed, so, the new request is hanging.

Is that an expected behavior?

**Comment by bagder** [comment]
I don't fully understand your explanation. Are you saying that libcurl uses a socket in the second request that the SOCKETFUNCTION callback did not tell the application about?

I asked already explicitly about sockets and activities. I cannot help you if you do not answer.

**Comment by TheBetterSolution** [comment]
> I don't fully understand your explanation. Are you saying that libcurl uses a socket in the second request that the SOCKETFUNCTION callback did not tell the application about?
> 
> I asked already explicitly about sockets and activities. I cannot help you if you do not answer.

Thanks for your response.

Request 2 socket polling process is cancelled because request 2 use the same socket 1 as request 1, so client never call curl_multi_socket when there is a pending io.

**Comment by bagder** [comment]
> Request 2 socket polling process is cancelled because request 2 use the same socket 1 as request 1, so client never call curl_multi_socket when there is a pending io.

So the 4 transfers you do are all done in *parallel*, not *serially* ? Using HTTP/2 to the same host?

You filed this issue over a month ago and we still learn new details. It is a little frustrating.

So this is what happens?

1. You fire up more than one request and they use the same connection
2. When request 1 ends, SOCKETFUNCTION is called and removes socket 1
3. request 2 (and possibly more) is still there, using the same connections as request 1
4. since the socket was removed by SOCKETFUNCTION your application does not wait for any socket at all

?

**Comment by TheBetterSolution** [comment]
> > Request 2 socket polling process is cancelled because request 2 use the same socket 1 as request 1, so client never call curl_multi_socket when there is a pending io.
> 
> So the 4 transfers you do are all done in _parallel_, not _serially_ ? Using HTTP/2 to the same host?
> 
> You filed this issue over a month ago and we still learn new details. It is a little frustrating.
> 
> So this is what happens?
> 
> 1. You fire up more than one request and they use the same connection
> 2. When request 1 ends, SOCKETFUNCTION is called and removes socket 1
> 3. request 2 (and possibly more) is still there, using the same connections as request 1
> 4. since the socket was removed by SOCKETFUNCTION your application does not wait for any socket at all
> 
> ?

The real context:
  2 requests to the same host, but use different connection.
  Request 1 start firstly, request 2 start secondly.
  When request 1 end, close socket 1 (by close() api) first and then call SOCKETFUNCTION to remove socket 1 from polling process 
 in future.
  Request 2 is starting at the time after socket 1 is closed and before the call of SOCKETFUNCTION to remove socket 1 from polling process.
  Request call socket() to create new socket, but socket integer value is also 1, and the call of SOCKETFUNCTION to POLL_IN for socket 1 (of request 2) is called.
  Now, SOCKETFUNCTION to remove socket 1 of request 1 from polling process is called.

**Comment by bagder** [comment]
So there is no multiplexing (HTTP/2) in use?

**Comment by TheBetterSolution** [comment]
Yes, because we use http version 1.1, and not reuse connection, every one request creates a new connection.

**Comment by TheBetterSolution** [comment]
From the code logic, I think the possibility to reproduce this issue if start a new question in the moment between close(socket) and  the call of SOCKETFUNCTION with CURL_POLL_REMOVE.
I think it’s a possible solution to use the curl instance and socket as the key for removing the socket polling process in the call of SOCKETFUNCTION with CURL_POLL_REMOVE, because the input parameter “curl” of SOCKETFUNCTION will be the removed curl instance 1 for request 1 and now the socket 1 is changed to bind to curl instance 2 for request 2, please refer to the above “detailed context”.
But I don’t ensure this is a stable solution.

**Comment by TheBetterSolution** [comment]
From the code logic, I think the possibility to reproduce this issue if start a new question in the moment between close(socket) and  the call of SOCKETFUNCTION with CURL_POLL_REMOVE.

I think it's a possible solution to use the curl instance and socket as the key for removing the socket polling process in the call of SOCKETFUNCTION with CURL_POLL_REMOVE, because the input parameter "curl" of SOCKETFUNCTION will be the removed curl instance 1 for request 1 and now the socket 1 is changed to bind to curl instance 2 for request 2, please refer to the above "detailed context".

But I don't ensure this is a stable solution.

**Comment by TheBetterSolution** [comment]
From the code logic, I think the possibility to reproduce this issue if start a new question in the moment between close(socket) and  the call of SOCKETFUNCTION with CURL_POLL_REMOVE.

I think it's a possible solution to use the curl instance and socket as the key for removing the socket polling process in the call of SOCKETFUNCTION with CURL_POLL_REMOVE, because the input parameter "curl" of SOCKETFUNCTION will be the removed curl instance 1 for request 1 and now the socket 1 is changed to bind to curl instance 2 for request 2, please refer to the above "detailed context".

But I don't ensure this is a stable solution.

**Comment by TheBetterSolution** [comment]
> Any chance you can provide a (small) example code that reproduces this issue?

Because the condition to generate this issue is complex, I will try it.

**Comment by bagder** [comment]
> From the code logic, I think the possibility to reproduce this issue if start a new question in the moment between close(socket) and the call of SOCKETFUNCTION with CURL_POLL_REMOVE.

A situation when one transfer stops using socket N and then the next transfer starts using the same socket number N is not rare. It happens all the time. I think there is more to your problem scenario than just those basic steps.

**Comment by TheBetterSolution** [comment]
> Any chance you can provide a (small) example code that reproduces this issue?

Excuse me, because the real code is complex, include message loop, polling thread, request schedule, detailed network configuration/communication and the possible related features, etc, that need more time if I add all the codes that maybe related the issue, I think the best way is I describe the code's key working flow and we check whether the logic for curl:

1. App create a request by following apis:
   curl_easy_init
   curl_easy_setopt
   curl_multi_add_handle
 2. Enter a loop to use the multi handle process the socket io, timer, and process all socket.
   while (TRUE) {
      int runningHandles = 0;

      if (isTimer) {
         handle timer timeout by calling curl_multi_socket with CURL_SOCKET_TIMEOUT.
      } else if (socketIO) {
         handle socket io by calling curl_multi_socket with this socket.
      } else {
		 remove the msg_done state curl instances by call: curl_multi_info_read, curl_multi_remove_handle
         handle all sockets by calling curl_multi_socket_all
      }
	  
	  // Run the loop util CURLM_CALL_MULTI_PERFORM != returned value of the above functions;
   }
   remove the msg_done state curl instances by call: curl_multi_info_read, curl_multi_remove_handle
 . After the loop returned, search and start the all the pending requests by sending a message and these requests will do the above steps when handle the message.
  
 2. The socket function is common log:
 int socket_callback(CURL *curl,
                     curl_socket_t sock,
                     int action,
                     void *data,
                     void *socketp)
{
   if (CURL_POLL_REMOVE == action) {
      find the socket in hash, remove it from polling sockets.
   } else if (CURL_POLL_NONE != action) {
      find and update the socket action.
   }

   return 0;
}

4. The timer function is common logic:
int timer_callback(CURLM *multi,
                   long ms,
                   void *data)
{

   if (ms >= 0) {
      add the time out to the timer, the timer is based the message mechanism.
   }
   return 0;
}

And app may not wait current request be completed, and just start other requests to do the above steps.

Could I use this way to describe the code? sorry for the inconvenience.

**Comment by bagder** [comment]
> // Run the loop util CURLM_CALL_MULTI_PERFORM != returned value of the above functions;

CURLM_CALL_MULTI_PERFORM has not been returned by a libcurl function since before version 7.20.0. I think you can drop that.

> Could I use this way to describe the code?

You can, but we can't reproduce the bug this way. The point with getting a recipe is that we would be sure that we know an exact source code that reproduces the problem. This way just risk one of us spending a lot of time and then still not being to reproduce it.

For example, your description completely leaves out the details on how you keep track of and wait for socket activity + timeout.

**Comment by TheBetterSolution** [comment]
> > // Run the loop util CURLM_CALL_MULTI_PERFORM != returned value of the above functions;
> 
> CURLM_CALL_MULTI_PERFORM has not been returned by a libcurl function since before version 7.20.0. I think you can drop that.

Yes, that's true, because the code is the base layer code, we don't want to touch it, so the CURLM_CALL_MULTI_PERFORM was left.

> 
> > Could I use this way to describe the code?
> 
> You can, but we can't reproduce the bug this way. The point with getting a recipe is that we would be sure that we know an exact source code that reproduces the problem. This way just risk one of us spending a lot of time and then still not being able to reproduce it.
> 
> For example, your description completely leaves out the details on how you keep track of and wait for socket activity + timeout.

11:22:53.342: start_request: entry
11:22:53.342: start_request: add easy handle in multi: 0x5567fb1c2390
11:22:53.342: remove_msg_done: entry
11:22:53.342: remove_msg_done: Exit

                    *** curl_multi_socket_all call entry ***
11:22:53.343: curl log: on request 0x5567fb1de5c0: [TCP] cf_socket_close(32, active) !! please note: the error case close socket in curl_multi_socket_all(is called in start request), but correct case is in curl_multi_socket (is called in socket io callback).
11:22:53.343: socket_func_callback: entry ** with CURL_POLL_REMOVE
11:22:53.343: remove_socket_polling: remove socket from socket io polling: 32.
11:22:53.343: socket_func_callback: exit
11:22:53.343: socket_func_callback: entry *** ignore this line that's for other socket.
11:22:53.343: socket_func_callback: exit *** ignore this line that's for other socket.
11:22:53.346: open_socket_callback: socket 32 is created !!! In the same curl_multi_socket_all call, create new socket its integer value is same as the recently closed socket integer value.
11:22:53.346: curl log: on request 0x5567fb1c2160: [TCP] cf_socket_open() -> 0, socket=32
11:22:53.346: socket_func_callback: entry *** ignore this line that's for other socket.
11:22:53.346: socket_func_callback: exit *** ignore this line that's for other socket.
11:22:53.346: socket_func_callback: entry
11:22:53.346: add_socket_polling: add socket to socket io polling: 32.
11:22:53.346: socket_func_callback: exit
                    *** curl_multi_socket_all exit ***
				   
				   !!! please note: the socket 32 polling is remove from: curl_multi_remove_handle, that's not ocurred previously.
11:22:53.346: remove_msg_done: entry *** check CURLMSG_DONE and call curl_multi_remove_handle to remove the easy handle with msg done state.
11:22:53.346: socket_func_callback: entry ** with CURL_POLL_REMOVE
11:22:53.346: remove_socket_polling: remove socket from socket io polling: 32. !!! the error happened.
11:22:53.347: socket_func_callback: exit
11:22:53.347: remove_msg_done: remove easy handle : 0x5567fb1e0260
11:22:53.347: remove_msg_done: remove easy handle : 0x5567fb30c140 *** ignore this easy handle.
11:22:53.347: remove_msg_done: exit

                    *** next http request.
11:22:53.347: start_request: exit
11:22:53.360: on_socket_io_event_occur: entry
11:22:53.360: socket_func_callback: entry
11:22:53.360: socket_func_callback: exit
11:22:53.360: remove_msg_done: entry
11:22:53.360: remove_msg_done: remove easy handle : 0x5567fb30d610
11:22:53.360: remove_msg_done: exit
11:22:53.360: on_socket_io_event_occur: exit
11:22:53.361: start_request: entry
11:22:53.361: start_request: add easy handle in multi: 0x5567fb1e0260
11:22:53.361: remove_msg_done: entry
11:22:53.361: remove_msg_done: exit
11:22:53.367: curl log: on request 0x5567fb1c2160: [TCP] cf_socket_close(32, active)
11:22:53.367: open_socket_callback: socket 32 is created
11:22:53.367: curl log: on request 0x5567fb1ebef0: [TCP] cf_socket_open() -> 0, socket=32
11:22:53.367: socket_func_callback: entry
11:22:53.367: add_socket_polling: add socket to socket io polling: 32.
11:22:53.367: socket_func_callback: exit

11:22:53.367: remove_msg_done: entry
11:22:53.367: socket_func_callback: entry ** with CURL_POLL_REMOVE
11:22:53.367: remove_socket_polling: remove socket from socket io polling: 32. !!! same issue for next request.
11:22:53.367: socket_func_callback: exit
11:22:53.367: remove_msg_done: remove easy handle : 0x5567fb1c2390
11:22:53.367: remove_msg_done: exit
11:22:53.367: start_request: exit
              !!! app is hanging here.

The code calls the socket function callback with CURL_POLL_REMOVE:
CURLMcode curl_multi_remove_handle(struct Curl_multi *multi,
                                   struct Curl_easy *data)
{
  struct Curl_easy *easy = data;
  bool premature;
  struct Curl_llist_element *e;
  CURLMcode rc;
  ...
  /* change state without using multistate(), only to make singlesocket() do
     what we want */
  data->mstate = MSTATE_COMPLETED;


  /* This ignores the return code even in case of problems because there's
     nothing more to do about that, here */
  (void)singlesocket(multi, easy); /* to let the application know what sockets
                                      that vanish with this handle */
  ...


In singlesocket function:
    entry = sh_getentry(&multi->sockhash, s);  // !!! the entry for this socket is got from multi (can distinguish the new socket with the old socket?)
    /* if this is NULL here, the socket has been closed and notified so
       already by Curl_multi_closed() */
    if(entry) {
      unsigned char oldactions = data->actions[i];
      /* this socket has been removed. Decrease user count */
      entry->users--;
      if(oldactions & CURL_POLL_OUT)
        entry->writers--;
      if(oldactions & CURL_POLL_IN)
        entry->readers--;
      if(!entry->users) {
        if(multi->socket_cb) {
          set_in_callback(multi, TRUE);
          rc = multi->socket_cb(data, s, CURL_POLL_REMOVE,
                                multi->socket_userp, entry->socketp); // !!! please check why this line be called in this log: remove_msg_done: entry *** check CURLMSG_DONE and call curl_multi_remove_handle to remove the easy handle with msg done state.
          set_in_callback(multi, FALSE);
          if(rc == -1) {
            multi->dead = TRUE;
            return CURLM_ABORTED_BY_CALLBACK;
          }
        }
        sh_delentry(entry, &multi->sockhash, s);
      }
      else {
        /* still users, but remove this handle as a user of this socket */
        if(Curl_hash_delete(&entry->transfers, (char *)&data,
                            sizeof(struct Curl_easy *))) {
          DEBUGASSERT(NULL);
        }
      }
    }
  } /* for loop over numsocks */
  
  Do we need to use some flags to indicate the easy handle that's the socket's owner? if the socket's owner is changed, other easy handle's socket is invalid.

**Comment by TheBetterSolution** [comment]
> > // Run the loop util CURLM_CALL_MULTI_PERFORM != returned value of the above functions;
> 
> CURLM_CALL_MULTI_PERFORM has not been returned by a libcurl function since before version 7.20.0. I think you can drop that.
> 
> > Could I use this way to describe the code?
> 
> You can, but we can't reproduce the bug this way. The point with getting a recipe is that we would be sure that we know an exact source code that reproduces the problem. This way just risk one of us spending a lot of time and then still not being able to reproduce it.
> 
> For example, your description completely leaves out the details on how you keep track of and wait for socket activity + timeout.

Hi @bagder , I put the key log messages in the app working flow, is it useful?

Thanks.

**Comment by bagder** [comment]
> is it useful?

Not very. It does not change the fact that until I can reproduce this problem, I will have a hard time to understand it and even more figure out what a potential and working fix would be.

The log makes me want to ask more questions though:

It seems to show that after you start the second transfer, libcurl tells your application to stop listening to socket 32 after the second transfer started. Is that so? At that moment, surely your application is then also waiting for one or more other sockets? Do you know what socket 32 was used for until that moment it gets removed? It seems to be removed 20 milliseconds into the transfer, which is... very early.

**Comment by TheBetterSolution** [comment]
> Not very. It does not change the fact that until I can reproduce this problem, I will have a hard time to understand it and even more figure out what a potential and working fix would be.
> I understood, that's better if we can find the root cause from log, else I will try to develop an example but that will take time to find a stable process to reproduce this issue (include client and server).
> The log makes me want to ask more questions though:
> It seems to show that after you start the second transfer, libcurl tells your application to stop listening to socket 32 after the second transfer started. Is that so?
Yes.

> At that moment, surely your application is then also waiting for one or more other sockets?
Yes, there are least 2 other connections.

Do you know what socket 32 was used for until that moment it gets removed?
Yes, socket 32 is for handling a request, the time it gets removed is making a unblocked connection to server, and added the socket polling process to wait the connection done.

It seems to be removed 20 milliseconds into the transfer, which is... very early.
Yes, please note, there is a special case:
   . socket 32 of first request is for easy handle: 0x5567fb1e0260.
   . socket 32 of second request is for easy handle: 0x5567fb1c2390
   . socket 32 of first request is closed, recreated and added to polling process(remove old one, add new one, because app will do it for any change of easy handle, socket, action) in one curl_multi_socket_all call.
   . But I think there is a delayed socket function call with CURL_POLL_REMOVE when removing the first easy handle 0x5567fb1e0260 from multi, (I think the time for CURL_POLL_REMOVE for first request should be after first socket 32 closing time and before the connecting time using the recreated socket 32.

Thanks.

**Comment by bagder** [comment]
The problem with your log is that you focus so much on that single socket 32 when libcurl is likely to use multiple sockets for each transfer. The fact that it is added and removed again might not be a problem because it might very well happen. For example, libcurl uses a file descriptor while doing threaded name resolves and when doing happy-eyeballs connections, and those could both have life-times that are in the millisecond range.

Thus looking at a single file descriptor says very little.

**Comment by TheBetterSolution** [comment]
> The problem with your log is that you focus so much on that single socket 32 when libcurl is likely to use multiple sockets for each transfer. The fact that it is added and removed again might not be a problem because it might very well happen. For example, libcurl uses a file descriptor while doing threaded name resolves and when doing happy-eyeballs connections, and those could both have life-times that are in the millisecond range.
> 
> Thus looking at a single file descriptor says very little.

I have a question, if the same socket's owner is changed to other easy handle, the last owner of this socket can still maintain this socket's polling process? (it has lose the ownership of this socket)

Thanks.

**Comment by bagder** [comment]
> I have a question, if the same socket's owner is changed to other easy handle, the last owner of this socket can still maintain this socket's polling process? (it has lose the ownership of this socket)

A single socket can be used by multiple transfers.

I don't understand the question. libcurl tells you about what sockets to wait for and for what activity, your application does not have to care about which transfer that needs or uses it.

**Comment by TheBetterSolution** [comment]
> A single socket can be used by multiple transfers.

Thanks for your answer, @badger.
Yes, a single socket can be used by multiple transfer, but I think this socket be used at different times (transfer 2 can operate this socket util transfer 1 has released the socket), multiple transfers should not operate one socket at the same time.

> your application does not have to care about which transfer that needs or uses it. It is in fact not even possible for your application to know that for sure.

I watched this case transfer 1 operate socket 1 (polling process) after it already closed socket 1, and the same time socket 1 is owned by transfer 2, transfer 2 tells to app to poll this socket io, but transfer 1 tells app to cancel this socket io polling, 
so, socket 1 polling is cancelled, app is hanging.

I think that can be watched in the log that can show the calling frame stack, please refer to the log message:

*** curl_multi_socket_all call entry ***
11:22:53.343: curl log: on request 0x5567fb1de5c0: [TCP] cf_socket_close(32, active) !! please note: the error case close socket in curl_multi_socket_all(is called in start request), but correct case is in curl_multi_socket (is called in socket io callback).
11:22:53.343: socket_func_callback: entry ** with CURL_POLL_REMOVE
11:22:53.343: remove_socket_polling: remove socket from socket io polling: 32.
11:22:53.343: socket_func_callback: exit
11:22:53.343: socket_func_callback: entry *** ignore this line that's for other socket.
11:22:53.343: socket_func_callback: exit *** ignore this line that's for other socket.
11:22:53.346: open_socket_callback: socket 32 is created !!! In the same curl_multi_socket_all call, create new socket its integer value is same as the recently closed socket integer value.
11:22:53.346: curl log: on request 0x5567fb1c2160: [TCP] cf_socket_open() -> 0, socket=32
11:22:53.346: socket_func_callback: entry *** ignore this line that's for other socket.
11:22:53.346: socket_func_callback: exit *** ignore this line that's for other socket.
11:22:53.346: socket_func_callback: entry
11:22:53.346: add_socket_polling: add socket to socket io polling: 32.
11:22:53.346: socket_func_callback: exit
*** curl_multi_socket_all exit ***

11:22:53.346: remove_msg_done: entry *** checked this easy handle is in CURLMSG_DONE state and call curl_multi_remove_handle to remove the easy handle.
11:22:53.346: socket_func_callback: entry ** with CURL_POLL_REMOVE *** please note: by the call context, I should ensure  the polling process for socket is removed by the process for removing the transfer 1.
11:22:53.346: remove_socket_polling: remove socket from socket io polling: 32. !!! the error happened, socket 1 cancelled the polling process it should done.
11:22:53.347: socket_func_callback: exit
11:22:53.347: remove_msg_done: remove easy handle : 0x5567fb1e0260
11:22:53.347: remove_msg_done: remove easy handle : 0x5567fb30c140 *** ignore this easy handle.
11:22:53.347: remove_msg_done: exit

**Comment by bagder** [comment]
> multiple transfers should not operate one socket at the same time.

Except when they should. As I already said: multiple transfers can very well use the same socket. Primarily when multiplexing a single connection, but also for other things (for example when c-ares is used for DNS).

Which is why I come back to this: the application does not and should not care about which transfer(s) the socket may or may not belong to.

> I watched this case transfer 1 operate socket 1 (polling process) after it already closed socket 1, and the same time socket 1 is owned by transfer 2, transfer 2 tells to app to poll this socket io, but transfer 1 tells app to cancel this socket io polling,

That's not how the socket management in libcurl is done. It gathers the socket situation for all transfers and the collected status is what is being communicated.

**Comment by TheBetterSolution** [comment]
> > multiple transfers should not operate one socket at the same time.
> 
> Except when they should. As I already said: multiple transfers can very well use the same socket. Primarily when multiplexing a single connection, but also for other things (for example when c-ares is used for DNS).
> 
> Which is why I come back to this: the application does not and should not care about which transfer(s) the socket may or may not belong to.
> 
> > I watched this case transfer 1 operate socket 1 (polling process) after it already closed socket 1, and the same time socket 1 is owned by transfer 2, transfer 2 tells to app to poll this socket io, but transfer 1 tells app to cancel this socket io polling,
> 
> That's not how the socket management in libcurl is done. It gathers the socket situation for all transfers and the collected status is what is being communicated.

Thanks @bagder , I hope to say my opinion , I think the socket state notified from the log isn't correct, because the polling process for socket 1 isn't cancelled correctly, I watched from the log, do you believe that's true?

**Comment by bagder** [comment]
> I think the socket state notified isn't correct, because the cancelling time for the polling process for socket 1 isn't correct, I watched from the log, do you believe that's true?

I'm not following. I don't know.

**Comment by TheBetterSolution** [comment]
> > I think the socket state notified isn't correct, because the cancelling time for the polling process for socket 1 isn't correct, I watched from the log, do you believe that's true?
> 
> I'm not following. I don't know.

I understood, I try to make an example, please wait a week, because that's not easy to reproduce.
Thanks.

**Comment by bagder** [comment]
If you figure out a way to reproduce, let us know and we can reopen this again.
