### ISSUE TITLE
urlparse: fix for fragment parsing changes username:password behaviour

### ISSUE THREAD

**Issue by stevenh** [curl/curl#1216]
### I did this
curl -v 'http://user1:password#@host.com/path'

### I expected the following
The request should have made a request with
protocol: 'https'
username: 'user1'
password: 'password#' 
hostname: 'host.com'
path: '/path'

### curl/libcurl version
7.51.0

This has worked for a very long time but due to fix in 3bb273db7e40ebc284cff45f3ce3f0475c8339c2 this no longer works and instead of trying to connect to host.com it tries to resolve and connect to user1.

I believe this is correct and that the desired behaviour for a password containing a # can be restored by encoding it as %23, so just raising for confirmation and so that it can be found by others tripping over the change.

**Comment by bagder** [comment]
Ouch. Yes from my looking at this, this is what we get for being a bit liberal in the URL parsing area so we previously accepted the `#` there even if it by the URL spec shouldn't be allowed, so when we made the parser stricter, we no longer support it like we use to...

[RFC3986 section 2.3](https://tools.ietf.org/html/rfc3986#section-2.3) lists the "unreserved characters" that are legitimate to use within the "userinfo" part of the URL and it does not include the `#` character.

The question is then if there's anything we can or should do to mitigate the impact for users.

**Comment by stevenh** [comment]
As this is now a more correct behaviour I don't think it warrants any changes to the code personally.

However as one of those effected, I can say I'd be happy a mention in the release notes, along side this issue for reference.

**Comment by bagder** [comment]
Thanks for your report and making us aware of this.

I've now amended the [20161102J advisory](https://curl.haxx.se/docs/adv_20161102J.html) that details the `#` parsing change, to also mention this new limitation and it links back to this issue.
