### ISSUE TITLE
curl http0.9 bug when not allowed

### ISSUE THREAD

**Issue by goodthebest** [curl/curl#12183]
### I did this

curl ---verions

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.

### I expected the following
error:  **HTTP/0.9 when not allowed**
Is it some bug or is there a way to enable http0.9 in curl 7.68.0 ?

### curl/libcurl version

curl 7.68.0 

### operating system

Ubuntu 20.04

**Comment by bagder** [comment]
Let me quote the man page:

~~~

--http0.9
       (HTTP) Tells curl to be fine with HTTP version 0.9 response.

       HTTP/0.9  is  a  response without headers and therefore you can also connect
       with this to non-HTTP servers and still get a  response  since  curl  simply
       transparently downgrades - if allowed.

       HTTP/0.9 is disabled by default (added in 7.66.0)

       Providing  --http0.9  multiple  times has no extra effect.  Disable it again
       with --no-http0.9.

       Example:
        curl --http0.9 https://example.com

       See also --http1.1, --http2 and --http3. Added in 7.64.0.
