### ISSUE TITLE
axtls build error

### ISSUE THREAD

**Issue by boostiewj** [curl/curl#1220]
curl-7.52.1，axTLS-2.1.2，centos 6.8
1.
axTLS/os_int.h:45:16: error: two or more data types in declaration specifiers
   typedef char bool;
                ^
2.
vtls/axtls.c:269:13: error: too few arguments to function 'ssl_client_new'
       ssl = ssl_client_new(ssl_ctx, conn->sock[sockindex],

vtls/axtls.c:276:11: error: too few arguments to function 'ssl_client_new'
     ssl = ssl_client_new(ssl_ctx, conn->sock[sockindex], NULL, 0);

**Comment by bagder** [comment]
axTLS is naughty when it defines symbols (like `bool`) out of its name space. That's an axTLS bug, not a curl bug.

Regarding `ssl_client_new` it sounds as if they've changed their API?

**Comment by boostiewj** [comment]
@bagder yes.they've changed their API.add some features.That's an axTLS bug for bool,but refuse to submit bug [https://sourceforge.net/p/axtls/bugs/?source=navbar](url)

**Comment by bagder** [comment]
1. axTLS refuses to accept bug reports from users
2. I still can't build axTLS, `make` just returns with errors and during the minutes I looked into it I couldn't figure out why

So we can't report the axTLS bug and I can't work on fixing the libcurl side of things.

**Comment by bagder** [comment]
I got a config file from @dfandrich and using that I could build axTLS 2.1.2.

1. Remove the bool typedef from the axTLS public header. It shouldn't be there.
2. Apply my patch. It adapts to the new API for `ssl_client_new` and fixes a bug with session IDs that I noticed.

[0001-axtls-adapt-to-API-changes.patch.txt](https://github.com/curl/curl/files/718101/0001-axtls-adapt-to-API-changes.patch)

**Comment by bagder** [comment]
Does anyone think it is worth keeping support for the older axTLS API?

**Comment by camster444** [comment]
I'll remove the typedef char bool on the next build. But the API has changed due to SNI functionality being added. Looks like curl supports it: http://stackoverflow.com/questions/12941703/use-curl-with-sni-server-name-indication#12942331.

**Comment by bagder** [comment]
Of course curl supports SNI, it would be hard to function on the Internet without it! =) But quite apparently it does not do SNI with axTLS yet since we can't build with a axTLS version using the modified API.

I'm leaning towards just stating that we no longer build with older axTLS versions.
