### ISSUE TITLE
Return CURLE_WRITE_ERROR when CURLOPT_WRITEFUNCTION callback returns CURL_WRITEFUNC_ERROR

### ISSUE THREAD

**Issue by enwillyado** [curl/curl#12201]
### I did this

Make a `CURLOPT_WRITEFUNCTION` callback that returns `CURL_WRITEFUNC_ERROR` in order to **abort** the curl session.

For instance, if a large download need to be aborted without errors by user.

### I expected the following

![imagen](https://github.com/curl/curl/assets/16733813/527f8189-c053-4a4e-885c-e7f7873a9038)

The cURL session must return `CURLE_ABORTED_BY_CALLBACK`.

### curl/libcurl version

lib environment, last version

### operating system

Unix ARM.

**Comment by icing** [comment]
So, what did you see instead? What is the failure you'd like to report?

**Comment by enwillyado** [comment]
See the `chop_write` function:
https://github.com/curl/curl/blob/6ec70a9dd305e17b017f1283a034dfa1c03bbd7c/lib/sendf.c#L334

When a `CURLOPT_WRITEFUNCTION` callback called, the return size was stored in `wrote` variable. This function checks if the returned value was `CURL_WRITEFUNC_PAUSE`. If the special `CURL_WRITEFUNC_ERROR` return negative value is returned, a generic `CURLE_WRITE_ERROR`. Get the specific `CURLE_ABORTED_BY_CALLBACK` error is better in order to distinguish from a generic error.

**Comment by enwillyado** [comment]
Probably this report should be a suggestion to have a `CURL_WRITEFUNC_ABORT` special returned value, right?

**Comment by bagder** [comment]
I still don't understand. Your callback returns `CURL_WRITEFUNC_ERROR`.

What are you saying is returned and what are you saying you think *should* have been returned?

**Comment by enwillyado** [comment]
Yes, literally if the `CURLOPT_WRITEFUNCTION` callback needs to return a abort, now only `CURL_WRITEFUNC_ERROR` can used. Then, if this special value was returned, the curl sessions ends with `CURLE_WRITE_ERROR` final code. This is the same final code if callbacks get an error (not memory or something like this)... in this case, by _returning a amount that differs from the amount passed_ by curl, is enough.

So, my suggestion is: return `CURLE_ABORTED_BY_CALLBACK` when callback returns `CURL_WRITEFUNC_ERROR`, or better, make a new `CURL_WRITEFUNC_ABORT` special return value to use in callbacks in order to get the curl session final code `CURLE_ABORTED_BY_CALLBACK`.

**Comment by bagder** [comment]
Yes, maybe `CURLE_ABORTED_BY_CALLBACK` would be slightly more logical to use, but I am reluctant to change this now that it has been in use like this since 7.87.0. Applications and users have already adapted to this return code and I fear that changing it now might cause more problems than simply accepting defeat and better documenting the current state.

**Comment by enwillyado** [comment]
Thanks @bagder , please, consider to add a new `CURL_WRITEFUNC_ABORT` special return value for Callbacks in order to get a `CURLE_ABORTED_BY_CALLBACK` response code from curl session!

**Comment by bagder** [comment]
> consider to add a new CURL_WRITEFUNC_ABORT special return value for Callbacks in order to get a CURLE_ABORTED_BY_CALLBACK response code from curl session!

I like this idea!
