### ISSUE TITLE
'vquic/curl_msh3.c' and '-DCURL_DISABLE_SOCKETPAIR'

### ISSUE THREAD

**Issue by gvanem** [curl/curl#12213]
### I did this

Building libcurl with `-DCURL_DISABLE_SOCKETPAIR` and `-DUSE_MSH3`, gave me this link error:
  `curl_msh3.obj : error LNK2019: unresolved external symbol Curl_socketpair referenced in function cf_msh3_connect`

Perhaps the code should be:
```diff
--- a/vquic/curl_msh3.c 2023-10-26 09:20:23
+++ b/vquic/curl_msh3.c 2023-10-27 09:48:17
@@ -863,13 +863,15 @@

   CF_DATA_SAVE(save, cf, data);

+#if !defined(CURL_DISABLE_SOCKETPAIR)
   if(ctx->sock[SP_LOCAL] == CURL_SOCKET_BAD) {
-    if(Curl_socketpair(AF_UNIX, SOCK_STREAM, 0, &ctx->sock[0]) < 0) {
+    if(wakeup_create(&ctx->sock[0]) < 0) {
       ctx->sock[SP_LOCAL] = CURL_SOCKET_BAD;
       ctx->sock[SP_REMOTE] = CURL_SOCKET_BAD;
       return CURLE_COULDNT_CONNECT;
     }
   }
+#endif

   *done = FALSE;
```

since I see no other direct call to `Curl_socketpair()` and (MSH3 is for non-Windows too).

Not sure, but other places this is wrapped inside a `#ifdef ENABLE_WAKEUP`.

### I expected the following

The .DLL to link.

### curl/libcurl version

8.5.0-DEV

### operating system

Win-10.

**Comment by bagder** [comment]
First: disabling the IPC communication with msh3 seriously cripples how it works and frankly, I am not convinced allowing this is a good idea. If you want to use msh3, you want it used. It might make sense to rather create an error that says so.

A complete fix to make this code use the wakeup_-macros instead of hardcoded socketpair also needs to use`wakeup_write`, `wakeup_read` and `wakeup_close`.

**Comment by gvanem** [comment]
> I am not convinced allowing this is a good idea.

This combo? Fine by me, but where should the error be generated?

**Comment by bagder** [comment]
> This combo? Fine by me, but where should the error be generated?

I think maybe in msh3.c, because I believe it is msh3's design that makes socketpair/pipe necessary.

**Comment by icing** [comment]
Something like this maybe?

```
--- a/lib/vquic/curl_msh3.c
+++ b/lib/vquic/curl_msh3.c
@@ -46,6 +46,10 @@
 #include "curl_memory.h"
 #include "memdebug.h"

+#ifdef CURL_DISABLE_SOCKETPAIR
+#error "MSH3 cannot be build with CURL_DISABLE_SOCKETPAIR set"
+#endif
+
 #define H3_STREAM_WINDOW_SIZE (128 * 1024)
 #define H3_STREAM_CHUNK_SIZE   (16 * 1024)
 #define H3_STREAM_RECV_CHUNKS \
```

**Comment by bagder** [comment]
@icing yup!
