### ISSUE TITLE
Issue with CURL-8.4.0 on HP-UX (B.11.31 U ia64)  platform

### ISSUE THREAD

**Issue by 366anish** [curl/curl#12236]
### I did this

I am building curl-8.4.0 on more than one platform (Linux , Window32, 64, solaris and  AIX ) . After build we trigger the command to verify the executables. When we ran the cmd: 
"./curl  www.google.com " ,  I got the response back on all the platform except HP-UX.
The failure message I got on HP-UX  : "Failed to connect to www.google.com port 80 after 76376 ms: Could't connect to server"
When reverted back the changes, pull request: https://github.com/curl/curl/pull/11718 , started getting response on running cmd :  "./curl www.google.com".
FYI: Check with different urls also.
compiler used:      ACXX                  C.06.28        HP C/aC++ Compiler
                           C-ANSI-C              C.06.28        HP C/aC++ Compiler

### I expected the following

 Expect to get response when run the cmd "./curl www.google.com" on HP-UX machine.

### curl/libcurl version

curl 8.4.0

### operating system

HP-UX hpipf27 B.11.31 U ia64 0905684060 unlimited-user license

**Comment by michael-o** [comment]
Let me verify that, but first of all you must upgrade to aC++ 6.29. I won't test anything with an older Compiler. Download the depot from HPE support center.

**Comment by bagder** [comment]
@366anish exactly how did you build curl? What command line(s)? The 1a14f2179b756d commit looks totally sane to me.

**Comment by 366anish** [comment]
Hi @bagder , The cmd line used : 

TOOLVER=8.4.0 gmake tool-configure
TOOLVER=8.4.0 gmake prep-prgs-install

Note: zlib and OpenLDAP is disabled .

**Comment by 366anish** [comment]
> Let me verify that, but first of all you must upgrade to aC++ 6.29. I won't test anything with an older Compiler. Download the depot from HPE support center.

Okay @michael-o , We will try to upgrade the compiler then let you know the status.

**Comment by michael-o** [comment]
> Hi @bagder , The cmd line used :
> 
> TOOLVER=8.4.0 gmake tool-configure TOOLVER=8.4.0 gmake prep-prgs-install
> 
> Note: zlib and OpenLDAP is disabled .

That isn't helpful because those are you private tools, totally opaque to us.

**Comment by bagder** [comment]
@366anish what if you build with a plain configure command line and gmake? We need more details here in order to act, if there is anything to act on. For now, it seems more likely that your problem is due to your own scripts than curl.

**Comment by tejaswid328** [comment]
@366anish I am also getting the same connection issue on HPUX 64 bit machine. But when I reverted back the PR [#11718](https://github.com/curl/curl/pull/11718 ), the connection is successful.

**Comment by michael-o** [comment]
> @366anish I am also getting the same connection issue on HPUX 64 bit machine. But when I reverted back the PR [#11718](https://github.com/curl/curl/pull/11718), the connection is successful.

Share your build details...

**Comment by tejaswid328** [comment]
> Let me verify that, but first of all you must upgrade to aC++ 6.29. I won't test anything with an older Compiler. Download the depot from HPE support center.

Hi @michael-o, Is it possible for Curl to encounter failures when used with older HP compilers? Is there any pre-requisite(README or release note) stating that aC++ 6.29 compiler should be used for 8.40 Curl?

**Comment by michael-o** [comment]
> > Let me verify that, but first of all you must upgrade to aC++ 6.29. I won't test anything with an older Compiler. Download the depot from HPE support center.
> 
> Hi @michael-o, Is it possible for Curl to encounter failures when used with older HP compilers? Is there any pre-requisite(README or release note) stating that aC++ 6.29 compiler should be used for 8.40 Curl?

This I cannot tell, but 6.29 is already seven years old. There is ZERO reason not to use it especially because there won't be a newer one.

**Comment by michael-o** [comment]
Anyone updated the compiler and retried?

**Comment by bagder** [comment]
> Is there any pre-requisite (README or release note) stating that aC++ 6.29 compiler should be used for 8.40 Curl?

No. curl should be possible to build with older versions of your compiler, but in order to know how to correct this problem we need more details about the problem. The change you identified as the problem seems totally innocuous and correct to me.

If you cannot upgrade the compiler and test with that, I want you to help us and better identify what exactly is wrong with the change, or perhaps what in the change that caused your version of the compiler to behave badly.

**Comment by bagder** [comment]
Almost a month, no additional info. Closing.

**Comment by michael-o** [comment]
> Almost a month, no additional info. Closing.

Did you expect anything else?
