### ISSUE TITLE
Compiling libcurl x86_64 version failed on mac computer(mac computer system 13.5 (22G74) Intel Core i7)

### ISSUE THREAD

**Issue by yyzyllp** [curl/curl#12245]
### I did this

**config params:**
  ./configure \
		--disable-shared \
		--enable-static \
  	--enable-threaded-resolver  \
  	--disable-verbose \
  	--enable-ipv6 \
  	--host=${HOST} \
  	--prefix=${PREFIX} \
  	--disable-ftp \
  	--enable-file \
  	--disable-debug \
  	--disable-ldap \
  	--disable-ldaps \
  	--disable-rtsp \
  	--enable-proxy \
  	--disable-dict \
 	 	--disable-telnet \
  	--disable-tftp \
 		--disable-pop3 \
  	--disable-imap \
  	--disable-smtp \
  	--disable-gopher \
  	--disable-sspi \
 		--disable-manual \
  	--with-zlib \
	  --without-libidn2 \
    --disable-hidden-symbols \
        ${SSL_CONFIG}
        
**build function:**
function build_for_arch() {
  ARCH=$1
  HOST=$2
  SYSROOT=$3
  PREFIX=$4
  echo "####### build_for_arch SYSROOT: ${SYSROOT}"

  export CFLAGS=""
	export CPPFLAGS=""
	export LDFLAGS=""

  if [ "${ARCH}" == "mac_catalyst_x86_64" ]; then
    export CFLAGS="-arch x86_64 -pipe -Os -gdwarf-2 -target x86_64-apple-ios13.0-macabi -isysroot ${SYSROOT} -mmacosx-version-min=10.10 -g -gline-tables-only"
    export CPPFLAGS="-DCURL_BUILD_IOS"
    export LDFLAGS="-arch x86_64 -target x86_64-apple-ios13.0-macabi -isysroot ${SYSROOT} -mmacosx-version-min=10.10"
  else
    IPHONEOS_DEPLOYMENT_TARGET="9.0"
    if [[ ${SYSROOT} =~ "iPhoneSimulator.sdk" ]]; then
      IOS_VERSION_MIN="-mios-simulator-version-min=${IPHONEOS_DEPLOYMENT_TARGET}"
    else
      IOS_VERSION_MIN="-miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET}"
    fi
    export CC="${XCODE_CMDTOOL_BASE_DIR}/usr/bin/gcc"
    export CFLAGS="-arch ${ARCH} -pipe -Os -gdwarf-2 -isysroot ${SYSROOT} ${IOS_VERSION_MIN} -g -gline-tables-only"
    export CPPFLAGS="-DCURL_BUILD_IOS"
    export LDFLAGS="-arch ${ARCH} -isysroot ${SYSROOT}"
  fi

  if ${USE_OPENSSL}; then
    SSL_CONFIG=--with-ssl=${SCRIPTPATH}/../curl-external-libs/boringssl/ios
    export LIBS="-lc++ -lffmpeg"
    export CPPFLAGS="${CPPFLAGS} -I${SCRIPTPATH}/../curl-external-libs/boringssl/include"
    export LDFLAGS="${LDFLAGS} -L${SCRIPTPATH}/../curl-external-libs/boringssl/ios/lib"
  elif ${USE_EBEDTLS}; then
    SSL_CONFIG=--with-mbedtls=${SCRIPTPATH}/../curl-external-libs/mbedtls/ios/${ARCH}
    export CPPFLAGS="${CPPFLAGS} -I${SCRIPTPATH}/../curl-external-libs/mbedtls/include"
    export LDFLAGS="${LDFLAGS} -L${SCRIPTPATH}/../curl-external-libs/mbedtls/ios/${ARCH}/lib"
  else
    SSL_CONFIG=--without-ssl
  fi

  export CPPFLAGS="${CFLAGS} ${CPPFLAGS}"

  echo "BUILD FOR ARCH: ${ARCH}"
  echo "USE HOST: ${HOST}"
  echo "USE SYSROOT: ${SYSROOT}"
  echo "USE PREFIX: ${PREFIX}"
  echo "USE SSL_CONFIG: ${SSL_CONFIG}"

  cd ${CURLPATH}
  if [ ! -e "configure" ]; then
      ./buildconf
      check_result $?
  fi

  make clean
  .....
  
**error info:**

ld: warning: ignoring file ../lib/.libs/libcurl.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      _tool_list_engines in tool_help.o
      _post_per_transfer in tool_operate.o
      _create_transfer in tool_operate.o
      _single_transfer in tool_operate.o
  "_curl_easy_escape", referenced from:
      _data_urlencode in tool_getparam.o
      _add_file_name_to_url in tool_operhlp.o
      _varexpand in var.o
  "_curl_easy_getinfo", referenced from:
      _tool_debug_cb in tool_cb_dbg.o
      _tool_header_cb in tool_cb_hdr.o
      _tool_list_engines in tool_help.o
      _run_all_transfers in tool_operate.o
      _post_per_transfer in tool_operate.o
      _create_transfer in tool_operate.o
      _ourWriteOut in tool_writeout.o
      ...
  "_curl_easy_header", referenced from:
      _ourWriteOut in tool_writeout.o
      _headerJSON in tool_writeout_json.o
  "_curl_easy_init", referenced from:
      _tool_list_engines in tool_help.o
      _create_transfer in tool_operate.o
      _single_transfer in tool_operate.o
  "_curl_easy_nextheader", referenced from:
      _headerJSON in tool_writeout_json.o
  "_curl_easy_pause", referenced from:
      _tool_progress_cb in tool_cb_prg.o
      _tool_readbusy_cb in tool_cb_rea.o
      _tool_write_cb in tool_cb_wrt.o
      _xferinfo_cb in tool_progress.o
  "_curl_easy_perform", referenced from:
      _run_all_transfers in tool_operate.o
  "_curl_easy_setopt", referenced from:
      _add_parallel_transfers in tool_operate.o

### I expected the following

build success 

### curl/libcurl version

master 

### operating system

macOS 13.5 (22G74)

**Comment by dfandrich** [comment]
You don't say what version of libcurl you're building, but curl_easy_header was
added relatively recently, in 7.83.0.  I think the root of the problem is here:

> ld: warning: ignoring file ../lib/.libs/libcurl.a, building for iOS

It looks like the library is being built in a way that the linker doesn't like,
maybe with a bad -target or -arch. You show a bunch of low-level compiler and
linker options, so there's a good chance that something has gone wrong with
them and they're not working as you expect. When it comes time to link, the
linker doesn't like the libcurl.a that was built and so finds the system's
libcurl.a or libcurl.dylib and uses that instead. However, that version is
pre-7.83.0 and doesn't have all the necessary symbols and so fails. Which is
fortunate for you, because it gives a clear indication that the compile isn't
doing what you think it should.

**Comment by yyzyllp** [comment]
> You don't say what version of libcurl you're building, but curl_easy_header was added relatively recently, in 7.83.0. I think the root of the problem is here:
> ld: warning: ignoring file ../lib/.libs/libcurl.a, building for iOS
> It looks like the library is being built in a way that the linker doesn't like, maybe with a bad -target or -arch. You show a bunch of low-level compiler and linker options, so there's a good chance that something has gone wrong with them and they're not working as you expect. When it comes time to link, the linker doesn't like the libcurl.a that was built and so finds the system's libcurl.a or libcurl.dylib and uses that instead. However, that version is pre-7.83.0 and doesn't have all the necessary symbols and so fails. Which is fortunate for you, because it gives a clear indication that the compile isn't doing what you think it should.

The version I am using is the latest version of the mainline, and the commit id is ddb95c1. Can you help point out the low-level compilation options and link options you mentioned? I'll check them one by one, thank you very much

**Comment by jay** [comment]
> The version I am using is the latest version of the mainline, and the commit id is ddb95c1. Can you help point out the low-level compilation options and link options you mentioned? I'll check them one by one, thank you very much

He's referring to the options in your build script.

**Comment by bagder** [comment]
> attempting to link with file built for unknown-unsupported file format

This does not sound like a curl problem.

**Comment by bagder** [comment]
I can't see how there is anything actionable for us in this issue. Can you @yyzyllp ?

**Comment by bagder** [comment]
No response, I don't think this is a curl issue.
