### ISSUE TITLE
http2 post can not stop

### ISSUE THREAD

**Issue by JacksonLv** [curl/curl#1224]
I want to make a HTTP2 POST request to AVS following the guide of [avs http2 connection](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/avs-http2-requests#examples)
below is how I post
`curl --http2 --trace-ascii response.txt    \`
  `-H "authorization: Bearer ${TOKEN}" \`
  `-H "Content-Type: multipart/form-data; boundary=${BOUNDARY}" \`
  `--data-binary @multipart_body.txt \`
   `https://avs-alexa-na.amazon.com/v20160207/events`

as I run this the terminal ,I found it won't stop. So I checked the response.txt .I found it print
~~~
=> Send data, 0 bytes (0x0)
<= Recv SSL data, 5 bytes (0x5)
0000: ....W
<= Recv header, 13 bytes (0xd)
0000: HTTP/2 204 
<= Recv header, 32 bytes (0x20)
0000: access-control-allow-origin: *
<= Recv header, 82 bytes (0x52)
0000: x-amzn-requestid: 0e1d57fffeb8fd3b-00000
0040: 4ec98-0dc31ba3-1
<= Recv header, 2 bytes (0x2)
0000: 
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)
=> Send data, 0 bytes (0x0)......`  
~~~
It keep sending data although the data bytes is 0.It should finish the request.

### curl/libcurl version
7.52.1
### operating system
macOS Sierra 10.12.2

**Comment by bagder** [comment]
At this point, has curl already sent the POST data?

A 204 response has no body, but it looks like perhaps that stream isn't closed or something. Can you build libcurl with --enable-debug and rerun this to get some more details in the logged data and show us? Might reveal something more about the h2 streams.

**Comment by jay** [comment]
@JacksonLv if you are able to reproduce this issue with the latest curl can you please let us know the `curl -V`

**Comment by bagder** [comment]
The custom use of `boundary=` in the Content-Type header makes me suspect that the multi-part is malformed so that the receiver doesn't detect the end of the POST and that's the reason.

This, plus the fact @JacksonLv has not responded even to the initial questions from back in February, I consider this issue closed due to lack of evidence and no way to reproduce.
