### ISSUE TITLE
`-Wstringop-truncation` warnings with gcc 13 unity

### ISSUE THREAD

**Issue by vszakats** [curl/curl#12258]
### I did this

Did a curl-for-win build:
```
In file included from ./curl/bld-cmake-gcc-x64-ucrt/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:346:
In function 'Curl_strndup',
    inlined from 'strstore' at ./curl/lib/cookie.c:368:10,
    inlined from 'sanitize_cookie_path' at ./curl/lib/cookie.c:314:5:
./curl/lib/strdup.c:117:3: warning: 'strncpy' output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  117 |   strncpy(buf, src, length);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
In function 'Curl_strndup',
    inlined from 'strstore' at ./curl/lib/cookie.c:368:10,
    inlined from 'pathmatch' at ./curl/lib/cookie.c:180:5,
    inlined from 'Curl_cookie_getlist' at ./curl/lib/cookie.c:1419:26:
./curl/lib/strdup.c:117:3: warning: 'strncpy' output truncated before terminating nul copying 1 byte from a string of the same length [-Wstringop-truncation]
  117 |   strncpy(buf, src, length);                          
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~                           
In function 'Curl_strndup',                                   
    inlined from 'curl_url_get' at ./curl/lib/urlapi.c:1595:13:
./curl/lib/strdup.c:117:3: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  117 |   strncpy(buf, src, length);                          
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~                           
In file included from ./curl/bld-cmake-gcc-x64-ucrt/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:379:
./curl/lib/urlapi.c: In function 'curl_url_get':              
./curl/lib/urlapi.c:1593:22: note: length computed here       
 1593 |     size_t partlen = strlen(ptr);                     
      |                      ^~~~~~~~~~~                      
[ 12%] Built target libcurl_object                              
```

Possibly related:
4855debd8a2c1cbd0b0dbbb8319b1743c4644873 #12254
d3b3ba35a5c4f862df2aa3e12de983e5457b429a #12251

### I expected the following

No warnings.

### curl/libcurl version

8.5.0-DEV

### operating system

any

**Comment by bagder** [comment]
Oh wow what a useless warning. It warns for doing exactly what the function is there to do...

**Comment by bagder** [comment]
@jay do you feel strongly for your strncpy there or should we revert to duck from this silly thing?

**Comment by bagder** [comment]
Or maybe we should just discourage using `-Wstringop-truncation`...

**Comment by vszakats** [comment]
We don't explicitly enable this. It may come with `-Wextra`, I don't know.

I'm sorry for the "silly" warnings. They come up while doing unrelated 
curl-for-win tests, and I'm not even attempting to categorize them.

**Comment by bagder** [comment]
> We don't explicitly enable this. It may come with -Wextra, I don't know.

Ah, that of course makes it more complicated to disregard it.

> I'm sorry for the "silly" warnings. 

It's not your fault. I think gcc has gone a little overboard here.

**Comment by jay** [comment]
I can change it to memchr '\0',length to get the actual length

**Comment by bagder** [comment]
> I can change it to memchr '\0',length to get the actual length

Right, seems like a decent work-around. Slightly slower operation but should duck for the warning and we probably don't do this on overly long strings anyway...
