### ISSUE TITLE
TLS version options are not completely mirrored to their proxy counterparts

### ISSUE THREAD

**Issue by aaronmdjones** [curl/curl#12286]
### I did this

Reading the manpage and trying to use options directly even though they were not documented (to see if it was just a documentation oversight), followed by reading the source code (to confirm whether I simply guessed the option name incorrectly) confirms that there is incomplete mirroring between the TLS options (`--tlsv1`, `--tlsv1.0`, `--tlsv1.1`, `...`, `--tls-max`, `--curves`) and their proxy counterparts (`--proxy-tlsv1`, `...`).

In fact, the latter option (`--proxy-tlsv1`) is the only one implemented, leaving you unable to e.g. instruct curl to use only TLSv1.3 when talking to an HTTPS CONNECT proxy itself.

### I expected the following

It would be feature-complete to also have the following options:

```
--proxy-tls-max
--proxy-tlsv1.0
--proxy-tlsv1.1
--proxy-tlsv1.2
--proxy-tlsv1.3
--proxy-curves
```

### curl/libcurl version

```
curl 8.4.0 (x86_64-pc-linux-gnu) libcurl/8.4.0 OpenSSL/3.0.12 zlib/1.2.13 zstd/1.5.5 c-ares/1.19.1 libidn2/2.3.4 nghttp2/1.57.0
Release-Date: 2023-10-11
Protocols: dict file http https mqtt rtsp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

Gentoo Linux (amd64)

**Comment by bagder** [comment]
> It would be feature-complete to also have the following options:

I don't think we need to be "feature complete" to that extent, but some of those would probably make sense to offer. You're the first person to ask for them.
