### ISSUE TITLE
Unexpected Timing Data When Limiting Concurrent Connections

### ISSUE THREAD

**Issue by zousar** [curl/curl#12284]
### I did this

Implemented an average latency metric for a series of asynchronous HTTP1_1 requests using the multi API that is produced from:

> CURLINFO_STARTTRANSFER_TIME - CURLINFO_CONNECT_TIME

I also limited the number of concurrent connections using:

> CURLMOPT_MAX_TOTAL_CONNECTIONS = foo

### I expected the following

The latency metric would match the known latency as measured by calling the standalone curl executable to perform a basic GET request with a tiny response.

What I found instead is that when there were more requests in progress than the connection limit permitted (and without pipelining or HTTP2), the latency measurement would increase in a way that seemed aligned with requests being queued and awaiting a connection.  If I remove the connection limit, the latency measure is then accurate.

This class of issue was discussed previously and a theoretical solution was proposed but the discussion went stale and no fix was submitted:
https://github.com/curl/curl/issues/4776#issuecomment-570890159

Having locally attempted a modification of this nature to curl, I found that it corrected the issue I was seeing.  Is there a chance that a fix can be submitted for this issue?

### curl/libcurl version

8.4.0

### operating system

Microsoft Windows [Version 10.0.19042.2965]

**Comment by zousar** [comment]
My attempt to simply move the `*nowp = Curl_pgrsTime(data, TIMER_STARTSINGLE);` would cause failures during execution (I expect that some paths are expecting the timer to have been set for the sake of evaluating timeouts, but I'm not sure).  What I did locally instead was keep the existing line as-is, and if the outcome of Curl_connect was NOT CURLE_NO_CONNECTION_AVAILABLE, then update that timer field again with `Curl_pgrsTime(data, TIMER_STARTSINGLE);`.

**Comment by bagder** [comment]
As long as existing functionality is not broken, fixing this seems worthwhile.

**Comment by zousar** [comment]
This is my proposed PR:
https://github.com/curl/curl/pull/12293

I'll see if any issues surface in the checks.

**Comment by zousar** [comment]
While most checks passed, I'm trying to interpret the[ "msys2 mingw32" test failure](https://dev.azure.com/daniel0244/curl/_build/results?buildId=18477&view=logs&j=ccf9cc6d-2ef1-5cf2-2c09-30f0c14f923b&t=558afea8-781f-5090-b2ea-08765b43246c) to see whether it is legitimate or an infrastructure/testing issue.  As these are unfamiliar to me, I'm looking for guidance as to whether this is a previously known or intermittent issue.

**Comment by vszakats** [comment]
Just a CI glitch. A re-run should fix it.

**Comment by zousar** [comment]
Yes, a re-run seems to have addressed it.  Thanks @vszakats .

**Comment by bagder** [comment]
This is not a bug, this is by design and if it is not clear in the documentation we should clarify it. To offer a way to deduct queuing time, I have proposed #12368

**Comment by zousar** [comment]
Hi @bagder - sorry for the delayed response, but there were work items preventing me from revisiting this topic.  I've attempted a test run with this proposed change, but I'm not having success in computing an accurate latency measure that doesn't inflate when requests get queued due to the connection limit.

Specifically, I'm using this (pseudocode):
```
	const auto GetSizeInfo = [this](CURLINFO Info)
	{
		curl_off_t Value;
		curl_easy_getinfo(Curl, Info, &Value);
		return uint64(Value);
	};
	QueueTime = GetSizeInfo(CURLINFO_QUEUE_TIME_T)/1000000.0;
	printf("Curl Queue Time = %.3f ms", QueueTime*1000);
```

And what I find is that even in the periods when there are a large number of requests and things seem to be queued, the reported queue time is reported as fractions of a millisecond.

I've double checked that:
1. My repro with unaltered Curl 8.4.0 reports inflated latency values
2. My repro with my alteration in #12293 reports stable (not inflated) latency values
3. My repro with the alteration in #12368 reports inflated latency values when I use CURLINFO_QUEUE_TIME_T and subtract the value it provides when computing latency
