### ISSUE TITLE
Cookie file permissions are narrowed when saved as a different user

### ISSUE THREAD

**Issue by hwti** [curl/curl#12299]
### I did this

As `user1` :
 - `curl -c cookies.txt ...`
  - `chmod 0666 cookies.txt`

As `user2`
 - `curl -c cookies.txt ...`
=> `cookies.txt` mode is `0600`, so `user1` can no longer access it.

### I expected the following

`cookies.txt` stays at `0666`, or at least `0666 & ~umask`.

### curl/libcurl version

curl 8.4.0-DEV (Linux) libcurl/8.4.0-DEV OpenSSL/3.0.9 zlib/1.2.13 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4)

### operating system

Fedora 38

**Comment by bagder** [comment]
I've pondered a bit back and forth on this and yes, I think `0600 | sb.st_mode` is what we want. You up for writing a PR for this @hwti ?

**Comment by hwti** [comment]
What about the `fchmod`, should we do it without the uid/gid condition ?
If yes, then the `fstat` would actually be useless (no point to do a stat to avoid a chmod).

**Comment by bagder** [comment]
... but if we consider skipping `fstat()` to do `chmod` unconditionally, can't we then instead change the `open()` call to the version below, and cut out the entire `#ifdef` block?

~~~c
  fd = open(tempstore, O_WRONLY | O_CREAT | O_EXCL, (mode_t)sb.st_mode);

**Comment by bagder** [comment]
See  #12395 for my take on a fix.

**Comment by hwti** [comment]
> ... but if we consider skipping `fstat()` to do `chmod` unconditionally, can't we then instead change the `open()` call to the version below, and cut out the entire `#ifdef` block?
> 
> ```c
>   fd = open(tempstore, O_WRONLY | O_CREAT | O_EXCL, (mode_t)sb.st_mode);
> ```

Unlike `fchmod`, `open` is affected by the umask (typically `022`, so removing group / other write).
So if the permissions were modified outside of curl (or by calling curl with a modified umask, which is less likely), these additional modifications would be lost.

So to share a cookie file between users, there are several options :
 - run the program with a large umask (not great)
 - a manual `chmod` (for example when pre-creating the file) : it worked before 20f9dd6bae50b7223171b17ba7798946e74f877f, but now it would require a `fchmod` to set the full `0600 | sb.st_mode`
 - reverting 0c667188e0c6cda615a036b8a2b4125f2c404dde : `fopen(filename, FOPEN_WRITETEXT)` needs write permission on the file, but `rename()` doesn't (so it could work with `0644` files, nothing special would be needed)

In fact, 0c667188e0c6cda615a036b8a2b4125f2c404dde made the non-regular file check atomic, but at the same time truncated the file with `FOPEN_WRITETEXT`, which is not atomic.
I don't see an easy way to make both operations atomic, so we probably have to choose (unless maybe reopening `/proc/self/fd/%d`, but this would be Linux-specific, and I don't know if it would really work).
