### ISSUE TITLE
curl version 8.4.0 curl_easy_perform error: getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by nitrogene** [curl/curl#12291]
### I did this

Curl is cross-compiled using Fedora / Mingw using a dockerfile: 

```dockerfile
# Compile curl from source
RUN export CURL_BASE_URL="https://github.com/curl/curl/releases/download/curl-8_4_0/" \
    && export CURL_VERSION="curl-8.4.0" \
    && export CURL_SHA512="ab9d19a99e91b0eb3fcdd5c7156cd4330c884961aa211a3ffafa91781b38f74bb96a9779c67f9470b9f6d64de76045880f51318d5d0fad2bd0639a47ba37a29e" \
    && cd /tmp \
    && wget -q "${CURL_BASE_URL}${CURL_VERSION}".zip \
    && expected_checksum="${CURL_SHA512}"; sha512sum "${CURL_VERSION}".zip | { read actual_checksum _; [ "$actual_checksum" = "$expected_checksum" ] && printf "\033[0;32m${CURL_VERSION}.zip check sum is valid\033[0m\n" || exit "\033[0;31m${CURL_VERSION}.zip check sum is invalid\033[0m\n"; } \
    && unzip "${CURL_VERSION}".zip \
    && cd "${CURL_VERSION}" \
    && export ROOTDIR="${PWD}" \
    && export CROSS_COMPILE="i686-w64-mingw32" \
    && export CPPFLAGS="-I${ROOTDIR}/openssl/include -I${ROOTDIR}/zlib/include" \
    && export LDFLAGS="-L${ROOTDIR}/openssl/libs -L${ROOTDIR}/zlib/libs" \
    && export AR=${CROSS_COMPILE}-ar \
    && export AS=${CROSS_COMPILE}-as \
    && export LD=${CROSS_COMPILE}-ld \
    && export RANLIB=${CROSS_COMPILE}-ranlib \
    && export CC=${CROSS_COMPILE}-gcc \
    && export NM=${CROSS_COMPILE}-nm \
    && export LIBS="-lssl -lcrypto" \
    && ./configure --prefix=${ROOTDIR}/build --target=${CROSS_COMPILE} --host=${CROSS_COMPILE} --with-ssl --with-zlib  --disable-ldap --disable-ldaps \
    && rm -rf ${ROOTDIR}/build \
    && mkdir -p ${ROOTDIR}/build \
    && make \
    && make install \
    && cp -r ${ROOTDIR}/build/* /usr/i686-w64-mingw32/sys-root/mingw/ \
    && cd .. && rm -rf "${CURL_VERSION}"*
```

Curl is then used in an msi installer on a Windows 10 computer to check if a given API is reachable. Here's an excerpt of code:

```c++
std::pair<CURLcode, std::string> curl::get(const std::string& url, const std::string& proxy) {

  std::string errorString{};
  CURLcode res{CURLE_OK};

  SPDLOG_INFO("curl::get url=[{}], proxy=[{}]", url, proxy);

  curl::curl_handle handle{curl::handle()};

  // https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html
  char errbuf[CURL_ERROR_SIZE];
  curl_easy_setopt(handle.get(), CURLOPT_ERRORBUFFER, errbuf);

  // Setting proxy if required
  if(not proxy.empty()) {
    SPDLOG_INFO("Configuring curl to use set proxy");
    errbuf[0]=0;

    // https://curl.se/libcurl/c/CURLOPT_PROXY.html
    res = curl_easy_setopt(handle.get(), CURLOPT_PROXY, proxy.c_str());

    if(res!=CURLE_OK){
      // https://curl.se/libcurl/c/curl_easy_strerror.html
      errorString = curl_easy_strerror(res);
      if(strlen(errbuf)){
        errorString = errbuf;
        SPDLOG_ERROR("CURLOPT_PROXY error: {}", errorString);
      } else {
        SPDLOG_ERROR("CURLOPT_PROXY error: unexpected error");
      }
    }
  }
// Set get url
  if(res == CURLE_OK) {
    errbuf[0]=0;
    // https://curl.se/libcurl/c/curl_easy_perform.html
    res = curl_easy_setopt(handle.get(), CURLOPT_URL, url.c_str());

    if(res!=CURLE_OK){
      // https://curl.se/libcurl/c/curl_easy_strerror.html
      errorString = curl_easy_strerror(res);
      if(strlen(errbuf)){
        errorString = errbuf;
        SPDLOG_ERROR("CURLOPT_URL error: {}", errorString);
      } else {
        SPDLOG_ERROR("CURLOPT_URL error: unexpected error");
      }
    }
  }

  // Perform get
  if(res == CURLE_OK) {
    errbuf[0]=0;

    // https://curl.se/libcurl/c/curl_easy_perform.html
    res = curl_easy_perform(handle.get());

    if(res!=CURLE_OK){
      // https://curl.se/libcurl/c/curl_easy_strerror.html
      errorString = curl_easy_strerror(res);
      if(strlen(errbuf)){
        errorString = errbuf;
        SPDLOG_ERROR("curl_easy_perform error: {}", errorString);
      } else {
        SPDLOG_ERROR("curl_easy_perform error: unexpected error");
      }
    } 
  }

  return std::make_pair(res, errorString);
}
```

Here's a log extract:

```log
[15:24:37:934] Using curl version 8.4.0
[15:24:37:934] curl::get url=[http://www.google.com], proxy=[ ]
[15:24:37:939] curl_easy_perform error: getaddrinfo() thread failed to start
````

I am probably something obvious... but can't see what.

### curl/libcurl version

curl 8.4.0

### operating system

Windows 10

**Comment by bagder** [comment]
I presume a normal official curl 8.4.0 tool from https://curl.se/windows works just fine?

**Comment by nitrogene** [comment]
Here's the thing. As stated, libcurl is used in an installer for windows machine. I have to support (beside m'y w10 computer) some older version of windows such as windows 7 embedded. Official binaries do not seem to be compatible with such older systems - it complains about missing system DLL - that's why I had to cross-compile from sources.

**Comment by nitrogene** [comment]
Beside the error string "getaddrinfo() thread failed to start", I have the following error code: CURLE_COULDNT_RESOLVE_HOST (6)

**Comment by vszakats** [comment]
> Official binaries do not seem to be compatible with such older systems - it complains about missing system DLL - that's why I had to cross-compile from sources.

Can you say which DLL was missing and possibly an example to reproduce your use-case?

We aim to support Vista (with UCRT) as a minimum. UCRT needs to be present. That is shipped as a regular Windows Update on Windows 7 (if that is what's missing.)

**Comment by nitrogene** [comment]
> > Official binaries do not seem to be compatible with such older systems - it complains about missing system DLL - that's why I had to cross-compile from sources.
> 
> Can you say which DLL was missing and possibly an example to reproduce your use-case?
> 
> We aim to support Vista (with UCRT) as a minimum. UCRT needs to be present. That is shipped as a regular Windows Update on Windows 7 (if that is what's missing.)

Here's a quick test, using a [windows 7 embedded iso](https://www.microsoft.com/en-US/Download/confirmation.aspx?id=11887) 7  (close to one of our targeted system), and [libcurl official release for windows](https://curl.se/windows/dl-8.4.0_6/curl-8.4.0_6-win32-mingw.zip):
- it complains about missing api-ms-win-crt-conio-l1-1-0.dll

**Comment by vszakats** [comment]
Thanks, that's UCRT.

According to this page: https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c
UCRT is present since SP1, but it doesn't specifically mention 'embedded'.

Here's the Windows Embedded 7 SP1 download:
https://www.microsoft.com/en-us/download/details.aspx?id=11887

Does it also happen with this image? Or does the update package work from the first link?

**Comment by nitrogene** [comment]
@vszakats you linked the same url than I did I think.

**Comment by vszakats** [comment]
Sorry, that's not readily obvious by looking at the links. You didn't mention SP1.

I cannot double check, but it's certainly odd that Win 7 SP1 ships with a different
set of CRT libs with embedded and desktop!

Does the manual UCRT update fix this for you?

**Comment by nitrogene** [comment]
I must confess that I don't know how to manually install this update - I'll take a look.

**Comment by nitrogene** [comment]
Good news. Using [this link](https://www.elbacom.com/install-update-kb3125574-on-windows-embedded-standard-7/) I was able to install the above update. Curl does now launch properly on our Windows 7 Embedded VM. I'll try to link to official lib, and keep you updated.

**Comment by vszakats** [comment]
Meanwhile I've found an official page with a bugfixed UCRT package: https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-322bf30f-4735-bb94-3949-49f5c49f4732

**Comment by nitrogene** [comment]
I am facing another issue, while trying to use official libcurl.dll: it does required wldap32.dll, and I don't have it in my mingw build environment. Still investigating

**Comment by vszakats** [comment]
`wldap32.dll` is part of Windows. Maybe not included in the Embedded line?

**Comment by nitrogene** [comment]
Well. My issue is that our build chain also launch Google tests in a wine environment. Tests won't launch as wine does not have this DLL. I'll take a look tomorrow.

**Comment by vszakats** [comment]
`wldap32` has been around since Windows NT 4.0 (possibly earlier). Windows CE also supported it 20 years ago.

Is this an old WINE version? I believe WINE releases from the last 10 years at least should offer it. WINE started working on it in 2005.

**Comment by nitrogene** [comment]
I am quite new to this toolchain. I'll investigate.

Best regards,

Jean-Pierre
Le mer. 8 nov. 2023, 17:41, Viktor Szakats ***@***.***> a
écrit :

**Comment by nitrogene** [comment]
@vszakats by adding a wine-ldap package, I was able to successfully run the build chain. At least for now I will continue to work with the latest windows official build.
