### ISSUE TITLE
`curl_url_set`: Setting a host name with a port as `CURLUPART_URL` returns `CURLUE_UNSUPPORTED_SCHEME` instead of `CURLUE_BAD_SCHEME`

### ISSUE THREAD

**Issue by Fulgen301** [curl/curl#12297]
### I did this

As seen in the following MRE, `curl_url_set(url, CURLUPART_URL, "example.com:80", 0)` fails with `CURLUE_UNSUPPORTED_SCHEME` as opposed to `CURLUE_BAD_SCHEME` if the URL didn't have a port component or contained an IP address instead of a domain name.

```c
#include <stdio.h>

#define CURL_STRICTER
#include <curl/curl.h>

#define LOG_RESULT(call) \
	printf(#call " returned %s\n", curl_url_strerror(call))

int main(void)
{
	curl_global_init(CURL_GLOBAL_ALL);

	CURLU *url = curl_url();

	LOG_RESULT((curl_url_set(url, CURLUPART_URL, "example.com", 0)));
	LOG_RESULT((curl_url_set(url, CURLUPART_URL, "127.0.0.1", 0)));

	LOG_RESULT((curl_url_set(url, CURLUPART_URL, "example.com:80", 0)));
	LOG_RESULT((curl_url_set(url, CURLUPART_URL, "127.0.0.1:80", 0)));

	curl_url_cleanup(url);

	curl_global_cleanup();
	return 0;
}
```

Output:
```
(curl_url_set(url, CURLUPART_URL, "example.com", 0)) returned Bad scheme
(curl_url_set(url, CURLUPART_URL, "127.0.0.1", 0)) returned Bad scheme
(curl_url_set(url, CURLUPART_URL, "example.com:80", 0)) returned Unsupported URL scheme
(curl_url_set(url, CURLUPART_URL, "127.0.0.1:80", 0)) returned Bad scheme
```

### I expected the following

I expected parsing of all of the URLs without a scheme to fail with the same error code.

### curl/libcurl version

libcurl 8.4.0

### operating system

Windows 11 23H2

**Comment by bagder** [comment]
This is a not exactly a bug. In the case of `example.com:80`, The parser actually finds `example.com` used as a URL scheme (since you did not use `CURLU_GUESS_SCHEME` or `CURLU_DEFAULT_SCHEME`) - but it not a recognized one. Hence this error.
