### ISSUE TITLE
curl or github somehow changes an exe file

### ISSUE THREAD

**Issue by l-urk** [curl/curl#12309]
### I did this

curl -O https://github.com/myexe.exe
curl -L https://github.com/myexe.exe > myexe.exe
curl -LJO https://github.com/myexe.exe

All of which produced an exe at directory of curl as expected...

### I expected the following

My exe to run as normal. But I get this error
![image](https://github.com/curl/curl/assets/112792604/cba00513-d822-4e4c-acea-61a02004f7b2)
So what's going on?
My exe will run perfectly fine before uploading it to github...
To note. This is a batchfile that was converted into an exe. Maybe that has something to do with it?

### curl/libcurl version

curl 8.2.0

### operating system

Windows 10

**Comment by bagder** [comment]
You should be able to verify that the checksum of the download file is identical to the one on the server. This is not a curl bug.

**Comment by jay** [comment]
Download files in your repo using 'raw'. If you go to the blob there should be a 'raw' link or you can just replace 'blob' with 'raw'
~~~
https://github.com/l-urk/repo/blob/master/myexe.exe
curl -fLO https://github.com/l-urk/repo/raw/master/myexe.exe
~~~
if your exe does not work that's not a curl issue
