### ISSUE TITLE
Support ECH with wolfssl

### ISSUE THREAD

**Issue by theoparis** [curl/curl#12302]
### I did this

CFLAGS="-DWOLFSSL_QUIC=1" ./configure --prefix=/usr/local --enable-static --with-wolfssl=/usr/local --withnghttp3 --with-ngtcp2=/usr/local/lib/libngtcp2.a --enable-ech

```
checking whether ECH support is available... configure: error: --enable-ech ignored: No ECH support found
```

### I expected the following

Successful build, see https://github.com/wolfSSL/wolfssl/pull/5623 which was merged a while ago

### curl/libcurl version

master

### operating system

Linux debian 6.5.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1 (2023-11-03) x86_64 GNU/Linux

**Comment by vszakats** [comment]
There is no ECH support in curl yet (that autotools option is a blank).

If you'd like to try it, see this branch and progress at: #11922
