### ISSUE TITLE
cmake: *** No rule to make target '../docs/curl.1'

### ISSUE THREAD

**Issue by bagder** [curl/curl#1230]
### I did this

A fresh git clone.

    $ ./buildconf
    $ mkdir build && cd build
    $ cmake ..
    $ make

Which ends in:

~~~
make[2]: *** No rule to make target '../docs/curl.1', needed by 'src/tool_hugehelp.c'.  Stop.
~~~

### I expected the following

A successful build

### curl/libcurl version

git master since commit 4c49b835979694, as announced on the [curl-library list](https://curl.haxx.se/mail/lib-2017-01/0147.html).

### operating system

Any

**Comment by ivyliolia** [comment]
I met the same problem and have no way to get around.
