### ISSUE TITLE
Unable to exchange encryption keys

### ISSUE THREAD

**Issue by danielhalati** [curl/curl#12322]
### I did this

I am doing a simple SFPT listing by running: curl -v -k -u user:pass sftp://10.0.255.142/~/

### I expected the following

I expect to see the listing, but what I get from time to time is:

![image](https://github.com/curl/curl/assets/16553732/67724f09-e05b-4dd2-9ab1-eedde973358c)

With the downloaded binary 8.4.0 from the official website I cannot reproduce the issue. Where am I doing wrong?

### curl/libcurl version

curl 8.4.0 with libssh2 1.11.0 compiled in house

### operating system

Windows

**Comment by danielhalati** [comment]
I am using the same version 1.11.0. I tried to download it somewhere but I cannot find it. So I compiled it myself

**Comment by bagder** [comment]
Your report above says 1.10.0 though. So I presume you are saying that the version numbers in the downloaded version and your own build are the same?

**Comment by danielhalati** [comment]
I mistyped it. I am using 1.11.0. Yes the versions are the same

**Comment by vszakats** [comment]
Which crypto-backend does your libssh2 use?

If it's Schannel, it may be this flakyness issue:
https://github.com/libssh2/libssh2/issues/804

**Comment by danielhalati** [comment]
I cannot really tell from the CMake configuration. This is the output

`-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.

-- The C compiler identification is MSVC 19.29.30038.1

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped

-- Detecting C compile features

-- Detecting C compile features - done

-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 

-- Could NOT find wolfssl (missing: WOLFSSL_LIBRARY WOLFSSL_INCLUDE_DIR) 

-- Could NOT find Libgcrypt (missing: LIBGCRYPT_LIBRARY LIBGCRYPT_INCLUDE_DIR) 

-- The following features have been enabled:



 * Static library, creating libssh2 static library



-- The following features have been disabled:



 * Shared library, creating libssh2 shared library (.so/.dll)

 * Logging, Logging of execution with debug trace

 * Compression, using zlib for compression



-- The following OPTIONAL packages have not been found:



 * OpenSSL

 * wolfssl

 * Libgcrypt

 * mbedTLS



-- Configuring done

-- Generating done`

**Comment by vszakats** [comment]
Thanks, that is Schannel (the default and fallback option on Windows).

This will be made clear by the next libssh2 release after this recent patch: https://github.com/libssh2/libssh2/commit/20387285d300c74160f655b72ad5d762ee56166b / https://github.com/libssh2/libssh2/pull/1211

**Comment by danielhalati** [comment]
Compiling with OpenSSL and the problem is gone. Thanks a lot
