### ISSUE TITLE
Static library libcurl.lib VS2015 unresolved external symbol

### ISSUE THREAD

**Issue by steffenbrem** [curl/curl#1234]
### I did this
Compiled `libcurl.lib` using "LIB RELEASE" (x64) configuration. Then I moved the include headers and the library to my own win32 console project (x64) and set it up as follows:

```
VC++ => Include directories -> $(SolutionDir)includes (contains curl headers)
     => Library directories -> $(SolutionDir)libraries (contains libcurl.lib)
Linker => Additional Library Directories -> $(SolutionDir)libraries
       => Input -> libcurl.lib  
```

I can compile fine when I don't use any curl functions, but when I invoke `curl_easy_init()` in my own source code and compile, then it gives me the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_curl_easy_cleanup referenced in function "void __cdecl ee(void)" (?ee@@YAXXZ)	Console	C:\Users\Ik\Documents\Visual Studio 2015\Projects\SDK4\Console\Console.obj	1	
Error	LNK2019	unresolved external symbol __imp_curl_easy_init referenced in function "void __cdecl ee(void)" (?ee@@YAXXZ)	Console	C:\Users\Ik\Documents\Visual Studio 2015\Projects\SDK4\Console\Console.obj	1	
```

### I expected the following
I expected that the curl package is statically linked in my project and I can use curls functions properly.

### curl/libcurl version
curl-7.52.1

### operating system
Microsoft Windows [Version 10.0.14393]
Visual Studio 2015

**Comment by MarcelRaad** [comment]
You have to define CURL_STATICLIB when compiling your project. Otherwise, the linker expects libcurl as a DLL (and all the functions with the "__imp" prefix).

**Comment by bagder** [comment]
Also mentioned the FAQ: [Link errors when building libcurl on Windows](https://curl.haxx.se/docs/faq.html#Link_errors_when_building_libcur)
