### ISSUE TITLE
cURL 8.4.0 configure build fails to find OpenSSL 3.0.12 in non-default directory

### ISSUE THREAD

**Issue by prniii** [curl/curl#12341]
### I did this

cURL 8.4.0's configure fails to find openSSL.

RHEL 9 clone Rocky 9 using openSSL 3.0.12 built and installed into /opt/jmpdev with PKG_CONFIG_PATH set to /opt/jmpdev/lib64/pkgconfig.  I have also tried making both with nothing in my LD_LIBRARY_PATH, and LD_LIBRARY_PATH=/opt/jmpdev/lib64

Note: the cmake build did work using
cmake .. -DOPENSSL_ROOT_DIR:PATH=/opt/jmpdev -DCMAKE_INSTALL_PREFIX=/opt/jmpdev

I tried:
./configure --prefix=/opt/jmpdev --libdir=/opt/jmpdev/curl/lib64

configure: error: select TLS backend(s) or disable TLS with --without-ssl.

Select from these:

  --with-amissl
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl

./configure --prefix=/opt/jmpdev --libdir=/opt/jmpdev/curl/lib64 --with-openssl

checking for openssl options with pkg-config... found
configure: pkg-config: SSL_LIBS: "-lssl -lcrypto "
configure: pkg-config: SSL_LDFLAGS: "-L/opt/jmpdev/lib64 "
configure: pkg-config: SSL_CPPFLAGS: "-I/opt/jmpdev/include "
checking for HMAC_Update in -lcrypto... no
checking for HMAC_Init_ex in -lcrypto... no
checking OpenSSL linking with -ldl... no
checking OpenSSL linking with -ldl and -lpthread... no
configure: OPT_OPENSSL: yes
configure: OPENSSL_ENABLED: 
configure: error: --with-openssl was given but OpenSSL could not be detected

[panels@localhost curl-8.4.0]$

./configure --prefix=/opt/jmpdev --libdir=/opt/jmpdev/curl/lib64 --with-openssl =/opt/jmpdev

...

configure: OPT_OPENSSL: /opt/jmpdev/
configure: OPENSSL_ENABLED: 
configure: error: --with-openssl was given but OpenSSL could not be detected

and finally
./configure --prefix=/opt/jmpdev --libdir=/opt/jmpdev/curl/lib64 --with-openssl =/opt/jmpdev/ssl

...
configure: error: /opt/jmpdev/ssl is a bad --with-openssl prefix!

### I expected the following

A successful configuration

### curl/libcurl version

curl 8.4.0 source

### operating system

Rocky Linux 9 (RHEL 9 clone)

**Comment by bagder** [comment]
When configure fails to do what you expected it to, for example to find the libraries you wanted it to find, then the standard next step is to open `config.log` in a text editor, search for the library/test that didn't go the way you expected and see what you can figure out based on that.

We've learned that this is a very effective way and reading this file often reveals details that can take you further in debugging your build/configure issue.

**Comment by prniii** [comment]
The config.log shows that the configure script is attempting to link against the system's 3.0.0 OpenSSL, and getting a failure due to undefined reference to symbols that are new in 3.0.12.  

 pkg-config reports in the lines immediately preceding the link error: png-config:  SSL_LIBS: "-lssl -lcrypto " and png-config: SSL_LDFLAGS: "-L/opt/jmpdev/lib64 "

So I expected that the configure script should honor the specified locations rather than the default system location.  ( I tried with the pkg-config, and directly specifying the path in the --with-openssl)

**Comment by bagder** [comment]
> pkg-config reports in the lines immediately preceding the link error: pkg-config: SSL_LIBS: "-lssl -lcrypto " and pkg-config: SSL_LDFLAGS: "-L/opt/jmpdev/lib64 "

So it it outputs those flags but it does not use them? Or does it use them but still does not verify it fine?

**Comment by prniii** [comment]
[config.log](https://github.com/curl/curl/files/13379951/config.log)
Looks to me that it put the -L/opt/jpdev/lib64 on the build line but linking still attempted to use OS's libssl and libcrypto.  I did just use the default options in building openssl, so I think my build may include deprecated algorithms.

**Comment by bagder** [comment]
It looks like your build picks up an ldap lib that wants OpenSSL 3.0.0 ? I believe this breaks the detection.

~~~
symbol lookup error: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0

**Comment by prniii** [comment]
Configuring with --disable-ldap gets it through the configure step.And it compiled without error. Looks like I need to decide either on rebuilding the ldap library as well, or deciding whether I need the ldap functionality in my build of libcurl.  
Thanks,
Paul
