### ISSUE TITLE
Error 27 Out of memory occurs when the DoH server returns an failed response

### ISSUE THREAD

**Issue by lRoccoon** [curl/curl#12365]
### I did this

A DoH server (https://dig.bdurl.net/dns-query) has some problem，when I use this doh server and use `-4`, I got `Error 27: Out of memory`.

```shell
curl -4 --doh-url https://dig.bdurl.net/dns-query google.com
curl: (27) Out of memory
```

I suspect it's caused by TTL 

```
* Connection #1 to host dig.bdurl.net left intact
* a DoH request is completed, 0 to go
* DoH: Too small type A for google.com
* DoH Host name: google.com
* TTL: 2147483647 seconds
* Closing connection 0
curl: (27) Out of memory
```

### I expected the following

```shell
curl -4 --doh-url https://dig.bdurl.net/dns-query google.com
curl: (6) Couldn't resolve host name
```

### curl/libcurl version

curl 8.1.2 (x86_64-apple-darwin23.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets

### operating system

Linux 5.4.143
Mac OS 14.1

**Comment by bagder** [comment]
I can reproduce and I see why...
