### ISSUE TITLE
json-formatted write-output somehow missing obvious attributes

### ISSUE THREAD

**Issue by atrull** [curl/curl#12360]
### I did this

curl --write-out '%{json}' -o /dev/null https://whatever.com | jq

### I expected the following

I was expecting to see the actual response_body along with all the metadata - given the level of data captured, surely the actually response to the request itself (rather than just the metadata) should be there ? 

The argument is --write-out _not_ --write-out-metadata

### curl/libcurl version

curl 8.1.2

### operating system

Darwin faptop.lanly 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64

**Comment by dfandrich** [comment]
The body can be (literally) infinitely long, so it can't in the general case be
returned in that way and still be useful.  --write-out refers to what curl
writes out.
