### ISSUE TITLE
crash in ssl_cf_data_pending, as secure websocket client, sending huge amount of PING

### ISSUE THREAD

**Issue by undici77** [curl/curl#12389]
### I did this

I implemented a secure websocket client that, beside a bidirectiona communication, implement PING->PONG mechanism. As server I have simple python script. Randomly It crash as shown in image. The problem looks connected to PING->PONG mechanism
![Screenshot 2023-11-23 091637](https://github.com/curl/curl/assets/3197601/1f7f44cc-a72c-4c16-9909-187ba0d9e53d)

Libcurl is compiled  using vcpkg

### curl/libcurl version

libcurl 8.4.0

### operating system

Windows 10

**Comment by bagder** [comment]
I think we need more details. Like how to reproduce this, or a more detailed description of what goes wrong in the code.

**Comment by bagder** [comment]
No response after initial submission. Closing.
