### ISSUE TITLE
RTSP: 503 answer to CURL_RTSPREQ_SETUP is truncated with 'Excess found', CURLOPT_WRITEFUNCTION doesn't get called

### ISSUE THREAD

**Issue by joed74** [curl/curl#12414]
### I did this

After calling CURLOPT_RTSPREQ_SETUP my satip server has no more resources and sends back 503 with a No-More: parameter 
(see https://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf, page 53 - it's the only 5xx return code with optional body)

I captured the packet, it looks like this:

![grafik](https://github.com/curl/curl/assets/61152521/30c3c7ac-0275-40b0-b0d8-38a7369d2b31)

But: CURLOPT_WRITEFUNCTION doesn't get called at all! I tried CURLOPT_HEADER in the hope to get headers + data but all i get was this:

```
RTSP/1.0 503 Service Unavailable
CSeq:1001
Content-Length:18

```

CURLOPT_DEBUGFUNCTION returns as INFO `Excess found: excess = 18 url = / (zero-length body)`

I'm confused...

### I expected the following

CURLOPT_WRITEFUNCTION without CURLOPT_HEADER enabled should return 

```
No-More: sessions

```

or, with CURLOPT_HEADER enabled:

```
RTSP/1.0 503 Service Unavailable
CSeq:1001
Content-Length:18

No-More: sessions

```

### curl/libcurl version

curl 8.4.0 (selfcompiled), but same with jammy version 7.81.0

### operating system

Linux server 5.15.0-odroid-arm64 #&#8203;1 SMP PREEMPT Ubuntu 5.15.118-202306231801~jammy (2023-06-23) aarch64 aarch64 aarch64 GNU/Linux

**Comment by bagder** [comment]
Again a reference to satip.. curl speaks RTSP, not satip.

**Comment by joed74** [comment]
True, but I'm wondering why the body isn't returned when it is sent?

**Comment by bagder** [comment]
A bug?

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by joed74** [comment]
I wrote a fake server and a fake client:
[rtsp_fake_client_and_server.zip](https://github.com/curl/curl/files/13478883/rtsp_fake_client_and_server.zip)

The server listens on port 12345 and just answers with the message you see above (503).

The client was taken from rtsp.c example and cut down to SETUP only.

After issuing `./rtsp_fake_client rtsp://localhost:12345` you will get this output:

```
RTSP fake client (only SETUP) to show excess message V1.0
    curl V8.4.0 loaded

RTSP: SETUP rtsp://localhost:12345/
      TRANSPORT RTP/AVP;unicast;client_port=1234-1235
== Info:   Trying [::1]:12345...
== Info: Connected to localhost (::1) port 12345
=> Send header, 0000000101 bytes (0x00000065)
0000: 53 45 54 55 50 20 72 74 73 70 3a 2f 2f 6c 6f 63 SETUP rtsp://loc
0010: 61 6c 68 6f 73 74 3a 31 32 33 34 35 2f 20 52 54 alhost:12345/ RT
0020: 53 50 2f 31 2e 30 0d 0a 43 53 65 71 3a 20 31 0d SP/1.0..CSeq: 1.
0030: 0a 54 72 61 6e 73 70 6f 72 74 3a 20 52 54 50 2f .Transport: RTP/
0040: 41 56 50 3b 75 6e 69 63 61 73 74 3b 63 6c 69 65 AVP;unicast;clie
0050: 6e 74 5f 70 6f 72 74 3d 31 32 33 34 2d 31 32 33 nt_port=1234-123
0060: 35 0d 0a 0d 0a                                  5....
<= Recv header, 0000000034 bytes (0x00000022)
0000: 52 54 53 50 2f 31 2e 30 20 35 30 33 20 53 65 72 RTSP/1.0 503 Ser
0010: 76 69 63 65 20 55 6e 61 76 61 69 6c 61 62 6c 65 vice Unavailable
0020: 0d 0a                                           ..
RTSP/1.0 503 Service Unavailable
<= Recv header, 0000000008 bytes (0x00000008)
0000: 43 53 65 71 3a 31 0d 0a                         CSeq:1..
CSeq:1
<= Recv header, 0000000019 bytes (0x00000013)
0000: 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 31 Content-Length:1
0010: 38 0d 0a                                        8..
Content-Length:18

<= Recv header, 0000000002 bytes (0x00000002)
0000: 0d 0a                                           ..
== Info: Excess found: excess = 18 url = / (zero-length body)
== Info: Connection #0 to host localhost left intact
````

**Comment by bagder** [comment]
So there's a `Content-Legth:` header promising 18 bytes of content but instead the connection closes. How is that not an error?

**Comment by bagder** [comment]
It is not clear to me if this is actually important or not for doing normal RTSP transfers. I don't sense a lot of interest from peeps to work on this, so I mark this as a pending KNOWN BUGS subject.
