### ISSUE TITLE
progress meter and other verbose related data are going to stderr!

### ISSUE THREAD

**Issue by pesarkhobeee** [curl/curl#12416]
### I did this

We are using the curl command inside our Kubernetes cronjobs a lot! and the output of those containers are collecting by datadog automatically. Logs coming from container Stderr have a default status of Error:
https://docs.datadoghq.com/containers/docker/log/?tab=containerinstallationcollectedis

### I expected the following

We expect to only see real errors in the stderr and therefore inside our dataDog logs but the progress information is making those reports noisy and inaccurate, for now, we added  `--no-progress-meter`, and that made the situation relaxed a bit but all in all this kind of information should go to stdout.
<img width="489" alt="Screenshot 2023-11-27 at 16 54 37" src="https://github.com/curl/curl/assets/147461/1f9da9c6-3733-46b6-a91a-a587262495ae">

You can test this behavior locally too with a command like this:
```
curl -v https://pathseeker.ir  > test.stdout 2> test.stderr; cat test.stderr
```

### curl/libcurl version

curl 8.1.2

### operating system

Linux and Mac

**Comment by dfandrich** [comment]
> but all in all this kind of information should go to stdout.

I beg to differ. curl is all about transferring data from URLs, and that data
should go to stdout. Everything else (unless specifically requested) should go
to stderr. You want to be able to run "curl https://something | somefilter" and
know that only the data from that URL is going to be sent to the pipe. curl
provides ways to modify this behaviour in certain cases to meet specific needs
but the default should follow the UNIX philosophy.

**Comment by bagder** [comment]
I strongly agree with @dfandrich on this. This is a fundamental key part of and design decision in curl since day one. Only data is sent to stdout.

**Comment by dfandrich** [comment]
You can already do exactly that with the --write-out option.

**Comment by pesarkhobeee** [comment]
Thanks a lot, now it is clear as crystal for me :)
