### ISSUE TITLE
RTSP: CURL_RTSPREQ_OPTIONS doesn't set session header

### ISSUE THREAD

**Issue by joed74** [curl/curl#12413]
### I did this

curl isn't adding a session header to an CURL_RTSPREQ_OPTIONS request after a session id was set..

The offical satip specification (https://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf, page 35) says

> The Session header is required when the OPTIONS request is used for keeping a session alive.

curl documentation states (https://curl.se/libcurl/c/CURLOPT_RTSP_REQUEST.html)

> The session ID is not needed for this method

Wireshark shows me on VLC this:

![grafik](https://github.com/curl/curl/assets/61152521/ee3104e9-068f-41f8-880d-18c919f0600e)

I was unable to add header fields to RTSP requests

### I expected the following

curl should add the session header to **CURL_RTSPREQ_OPTIONS**, when it was set before with **CURLOPT_RTSP_SESSION_ID**

if backward compatibility is an issue, a new request could be added, e.g. **CURL_RTSPREQ_KEEPALIVE** which only works if the session id is set.

### curl/libcurl version

curl 8.4.0 (selfcompiled), but same with jammy version 7.81.0

### operating system

Linux server 5.15.0-odroid-arm64 #&#8203;1 SMP PREEMPT Ubuntu 5.15.118-202306231801~jammy (2023-06-23) aarch64 aarch64 aarch64 GNU/Linux

**Comment by joed74** [comment]
Ok, i cross-checked this with rfc2326 - so it would be nice to have an option to be able to add the session for satip servers on CURL_RTSPREQ_OPTIONS request

**Comment by bagder** [comment]
Thanks a lot for your report!

Can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by bagder** [comment]
I can't reproduce. I used this:
~~~c
#include <stdio.h>
#include <curl/curl.h>

int main(void)
{
  CURL *curl;
  CURLcode res;

  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_URL, "rtsp://example.com/");

    curl_easy_setopt(curl, CURLOPT_RTSP_SESSION_ID, "12345");

    curl_easy_setopt(curl, CURLOPT_RTSP_REQUEST, CURL_RTSPREQ_OPTIONS);

    /* Perform the request, res will get the return code */
    res = curl_easy_perform(curl);
    /* Check for errors */
    if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n",
              curl_easy_strerror(res));

    /* always cleanup */
    curl_easy_cleanup(curl);
  }
  return 0;
}

**Comment by joed74** [comment]
You are right, curl is sending the session header:
![image](https://github.com/curl/curl/assets/61152521/444c831f-ae5e-46e5-acae-7f2a8a4e4bd5)

I close the issue, sorry for the false report..
