### ISSUE TITLE
Respect ipv4hint/ ipv6hint instead of A record when ECH is enabled

### ISSUE THREAD

**Issue by NgoHuy** [curl/curl#12426]
### I did this

When I setup my ECH without A record - only HTTPS record, and when I tested with this repo, it cannot connect due to missing A record.

### I expected the following

curl should respect ipv4hints/ipv6hints as RFC 9460 instead of A record.

### curl/libcurl version

ECH-experimental branch

### operating system

Archlinux

**Comment by bagder** [comment]
curl has no ECH support yet to filing an issue against that seem premature.

Are you using the  #11922 PR code?

**Comment by NgoHuy** [comment]
Oops, my fault. I reported it to original author. But I did not aware the repo
