### ISSUE TITLE
curl_multi_add_handle  and curl_multi_remove_handle  - interface exception

### ISSUE THREAD

**Issue by xuquan316** [curl/curl#12436]
### I did this

global var:
static  std::atomic<int>   extra_all_num = 0;
one thread:
for (;;) {
	mc = curl_multi_perform(m_multi_handle, &keep_running_num);

	if (mc == CURLM_OK) {
		mc = curl_multi_poll(m_multi_handle, NULL, 0, 100, &nums_fds); //wait

		if (mc != CURLM_OK) {
			logger_instance()->error("mutl poll error,[{}]", mc);
			continue;
		}

		if (nums_fds > 0) {
			do {
				resp = curl_multi_info_read(m_multi_handle, &msg_num);
				if (resp && (resp->msg == CURLMSG_DONE)) {
				CURL* handle = resp->easy_handle;
				curl_multi_remove_handle(m_multi_handle, handle);
				--extra_all_num;
				log(extra_all_num );
			}while(resp);
		}
	} 
}
 other thread:
	func(){
		..........
		curl_multi_add_handle(m_multi_handle, curl);
		++extra_all_num ;
		log(extra_all_num );
		..........
	}

      
result exception:
curlcache ---- 93
curlcache ++++ 94
curlcache ---- 93
curlcache ++++ 94
curlcache ++++ 95
curlcache ---- 94
curlcache ---- 93
curlcache ++++ 94
curlcache ---- 93
curlcache ++++ 94
curlcache ---- 93
curlcache ++++ 94
curlcache ---- 93
curlcache ++++ 94
curlcache ++++ 95
curlcache ---- 94
.....  service excption

This EXTRA ALL NUM  is abnormal and continue to grow

### I expected the following

One thread is responsible for perform and poll as well as read and remove.

The other thread is responsible for add_handle and wakeup.
The number of curl contexts continues to grow

### curl/libcurl version

curl 8.4.0 and curl 7.74.0

### operating system

ubuntu 1804

**Comment by bagder** [comment]
You are using the same multi handle concurrently in more than one thread, which is against the [threading rules](https://curl.se/libcurl/c/threadsafe.html)

**Comment by xuquan316** [comment]
> You are using the same multi handle concurrently in more than one thread, which is against the [threading rules](https://curl.se/libcurl/c/threadsafe.html)

thanks
