### ISSUE TITLE
CURLINFO_PRETRANSFER_TIME_T and CURLINFO_PRETRANSFER_TIME descriptions disagree

### ISSUE THREAD

**Issue by eeverettrbx** [curl/curl#12431]
### I did this

The man page for CURLINFO_PRETRANSFER_TIME says
> It includes the sending of the protocol- specific protocol instructions that triggers a transfer.

but the man page for CURLINFO_PRETRANSFER_TIME_T says
> It does not involve the sending of the protocol- specific request that triggers a transfer.

despite the fact that both are obtained from `data->progress.t_pretransfer`

### I expected the following

It looks like the wording used to be the same until CURLINFO_PRETRANSFER_TIME's man page was updated in #6453 , presumably that one is correct and CURLINFO_PRETRANSFER_TIME_T's page just needs to be updated as well?

### curl/libcurl version

curl 8.4.0

### operating system

n/a

**Comment by jay** [comment]
Thanks
