### ISSUE TITLE
with c-ares library bug

### ISSUE THREAD

**Issue by nonamezhangsan** [curl/curl#12454]
### I did this

When using the c-ares library, if the IP address of virtual network card 8 (NAT mode) set by VMware Workstation Pro is the same as DNS, it will continuously report an error and cannot resolve the host. When not using the c-ares library, the address can be resolved normally

### I expected the following

When including the c-ares library, it can also be compatible with virtual network card conflicts

### curl/libcurl version

curl 8.4.0

### operating system

windows 11

**Comment by bagder** [comment]
1. You don't mention which c-ares version you're using
2. c-ares resolves DNS names, it does not know about network cards
3. This sounds like a potential c-ares issue, not a curl one?

**Comment by nonamezhangsan** [comment]
Sorry, I apologize for my unclear expression and would like to add some clarification:
1.I am using the MT static library compiled from c-ares-1.19.1
2. I suspect that the problem was caused by the default selection of connecting the host virtual adapter to the virtual network when VMware Workstation Pro was set up
3. When the situation I mentioned above occurs, if the c-ares library is not used, use the async thread. c file, and check at line 572 whether tdata is empty (its dns member is empty), because tdata is not empty and will not return CURLE_COULDNT_RESOLVE_HOST, while using the c-ares library, the async ares. c file is used, and its 411 line determines whether dns is empty, because if dns is empty, it will directly return CURLE_COULDNT_RESOLVE_HOST,  I suspect that this different judgment logic led to different behavioral outcomes in the end

Note: This situation can be reproduced stably. Simply open the virtual network editor of VMware Workstation Pro, modify the VMnet8 subnet IP to 223.5.0 and the remaining defaults, and then modify the local DNS to 223.5.1 and 127.0.0.1 (alternative DNS only needs to be disconnected). Then, it can be found that for any network page, using the curl library of the c-ares library will stabilize and quickly report an error CURLE_COULDNT_RESOLVE_HOST, while the curl library without using the c-ares library can stably connect

**Comment by nonamezhangsan** [comment]
commandline：
C:\Windows\System32>curl --version
curl 8.4.0 (Windows) libcurl/8.4.0 Schannel WinIDN
Release-Date: 2023-10-11
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

C:\Windows\System32>curl example.com
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>

C:\Windows\System32>cd /d "D:\curl-8.4.0\build\Win32\VC14.30\LIB Debug - LIB OpenSSL"

D:\curl-8.4.0\build\Win32\VC14.30\LIB Debug - LIB OpenSSL>.\curld --version
WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.4.0 (i386-pc-win32) libcurl/8.4.0 OpenSSL/3.1.4 zlib/1.3 c-ares/1.23.0
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe Unicode UnixSockets

D:\curl-8.4.0\build\Win32\VC14.30\LIB Debug - LIB OpenSSL>.\curld example.com
curl: (6) Could not resolve host: example.com

**Comment by bagder** [comment]
This sounds like you identify a case when c-ares does not resolve the host name correctly. Then this is a @c-ares problem, not a curl one. I propose you

1. try with the latest c-ares
2. if the problem remains, file an issue with the c-ares project and continue this investigation there

**Comment by nonamezhangsan** [comment]
async_ares. c This file belongs to the curl library, not the c-ares library. If this c-ares library is not used, dns member will still be empty, but it will follow another logic. Please do not arbitrarily assume that it is not a bug in curl
