### ISSUE TITLE
curl 56 HTTP/2 stream 7 was reset

### ISSUE THREAD

**Issue by emt2dev** [curl/curl#12457]
### I did this

attempted to push to azure devops
have prior working commits on this branch
![image](https://github.com/curl/curl/assets/86013234/9d37d13d-8bce-4725-881d-6143ab195724)

### I expected the following

to be able to send the git push

### curl/libcurl version

curl 8.4

### operating system

windows 11

**Comment by emt2dev** [comment]
> The `curl --version` output is for the curl command line tool in Windows, which is not the same version/build that your git is using. This is why the `Features` list does not contain HTTP/2...

thank you. can you direct me to locate a workaround?

**Comment by piru** [comment]
@emt2dev  what is the version of `git`? is the git from https://git-scm.com/ ? At least git from https://git-scm.com/ includes local libcurl dll, and if the git command is very old, some old libcurl might be in use. If the git is from https://git-scm.com/ it might be worth trying to update to the latest version and try again to see if anything changes.

**Comment by emt2dev** [comment]
> @emt2dev what is the version of `git`? is the git from https://git-scm.com/ ? At least git from https://git-scm.com/ includes local libcurl dll, and if the git command is very old, some old libcurl might be in use. If the git is from https://git-scm.com/ it might be worth trying to update to the latest version and try again to see if anything changes.

thank you very much. I found that this works for me: (changing to http 1/1
https://github.com/flox/flox/commit/a2212c5f3dd461a773ffd359057cf0c2445d30c5
