### ISSUE TITLE
Test 1477 fails with 8.5.0 release tarball because it lacks curl-8.5.0/tests/errorcodes.pl

### ISSUE THREAD

**Issue by xry111** [curl/curl#12462]
### I did this

Download https://curl.se/download/curl-8.5.0.tar.xz, build it and run "make test".

### I expected the following

All tests pass.

### curl/libcurl version

curl 8.5.0

### operating system

Linux From Scratch

**Comment by vszakats** [comment]
We have `.github/workflows/distcheck.yml`, but it's not catching these for some reason.

**Comment by samueloph** [comment]
I haven't investigated whether there's an issue specific to the Debian packaging yet, but even with the patch from https://github.com/curl/curl/commit/da8c1d15782c8161b455a7ee90197c16ae5edb90 we get a failure:
```
test 1477...[Verify that error codes in headers and libcurl-errors.3 are in sync]

 1477: stdout FAILED:
--- log/check-expected	2023-12-06 19:20:24.039606296 +0000
+++ log/check-generated	2023-12-06 19:20:24.039606296 +0000
@@ -1 +0,0 @@
-Result[LF]
== Contents of files in the log/ dir after test 1477
=== Start of file check-expected
 Result[LF]
=== End of file check-expected
=== Start of file commands.log
 perl -I. ./errorcodes.pl ./.. > log/stdout1477 2> log/stderr1477
=== End of file commands.log
=== Start of file server.cmd
 Testnum 1477
=== End of file server.cmd
=== Start of file stderr1477
 Can't open perl script "./errorcodes.pl": No such file or directory
=== End of file stderr1477
```

It looks like something very simple but I'll only be able to look at this on the weekend and someone might figure it out before me.

**Comment by samueloph** [comment]
> If you're patching the 8.5.0 tarball, then you'll need to include errorcodes.pl

I was confused by this since I had checked and the file was there... until I realized there are two files: `error-codes.pl` and `errorcodes.pl`, it would take me ages to figure out I was looking at the wrong file :(

Thank you.

**Comment by bagder** [comment]
> there are two files: error-codes.pl and errorcodes.pl

Oh, I didn't realize that. I should maybe rename one of them for better clarity...
