### ISSUE TITLE
[autotools] NTLM_WB support cannot be enabled

### ISSUE THREAD

**Issue by benoit-pierre** [curl/curl#12477]
### I did this

Using `./configure --with-openssl --enable-ntlm --enable-ntlm-wb` (with `ntlm_auth` in the standard location) does  result in a config with NTLM_WB support disabled.

### I expected the following

Support should be enabled.

It looks like the issue is checking for `fork` was removed in 2ba804942fda50bbd385c743309a7ec8aca2cf47, resulting in `ac_cv_func_fork` never being set to `yes`, so [this test in `m4/curl-confopts.m4`](https://github.com/curl/curl/blob/master/m4/curl-confopts.m4#L620) always fail.

### curl/libcurl version

curl 8.5.0

### operating system

Arch Linux.

**Comment by jay** [comment]
#12479

Also please see https://curl.se/dev/deprecate.html#ntlm_wb-auth

**Comment by benoit-pierre** [comment]
Thanks, I know about the deprecation. In fact, I'm not really interested in the support, I just noticed the issue while updating the Meson wrap for cURL to 8.5.0.

Additionally, there's actually one test for the feature (1310), which does not seem to work (tested on Arch Linux and Ubuntu 22.04).

**Comment by jay** [comment]
Since NTLM_WB is deprecated there are no plans to fix this. Thanks
