### ISSUE TITLE
Where can we find releases in the git repo?

### ISSUE THREAD

**Issue by pps83** [curl/curl#12473]
### I did this

Releases from https://curl.se/download.html aren't the same as code tagged in the git repo.

### I expected the following

Whatever in tags/curl-8_5_0 is different from what's released in https://curl.se/download/curl-8.5.0.tar.gz
Shouldn't it be part of public git repo as well? It seems like whatever gets releases in tar.gz cannot be retrieved as-is from git.

### curl/libcurl version

5.8.0

### operating system

none

**Comment by dfandrich** [comment]
This is by design. See the file GIT-INFO. Some files are generated at packaging
time and added to the tarball for user convenience.

**Comment by bagder** [comment]
The releases are *generated* using the files that are in the git repo. You can do it as well.
