### ISSUE TITLE
Async DNS resolution on Win8+ with GetAddrInfoExW

### ISSUE THREAD

**Issue by pps83** [curl/curl#12481]
### I did this

I tried to run a test on Windows under [asan](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170) where many fetches are tried when there is no internet. It appears that [starting/exiting threads under asan leaks memory badly](https://developercommunity.visualstudio.com/t/ASAN-causes-OOM-error-when-many-threads/10508715), it takes only a few seconds before all ram gets consumed.

### I expected the following

Although, this isn't a bug in libcurl, but in my case I had to fix the issue. It seems that libcurl without c-ares always starts a thread for dns requests since dns was always blocking before Win8. Starting from Win8 there is a non-blocking version is available with [GetAddrInfoExW](https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfoexw).
Alternatively, libcurl could have cached failed dns results for a very short time to avoid redoing the same requests multiple times: for example, if 1000 requests are made to the same host while there is no connection instead of starting 1000 threads in 10ms doing the same failing dns request it would be better to cache failures for 10ms or 1ms.

In my case, I ended up writing [code that uses GetAddrInfoExW on Win8](https://github.com/pps83/curl/commit/046c78285d64ff8c620c6b50299f59539357bf0e). Let me know if it's something worth to add to libcurl, and I'll make a PR.

### curl/libcurl version

curl 8.5.0

### operating system

WIndows 8+

**Comment by bagder** [comment]
> In my case, I ended up writing [code that uses GetAddrInfoExW on Win8](https://github.com/pps83/curl/commit/046c78285d64ff8c620c6b50299f59539357bf0e). Let me know if it's something worth to add to libcurl, and I'll make a PR.

By your description it certainly sounds like a worthwhile idea. Please do!

**Comment by pps83** [comment]
https://github.com/curl/curl/pull/12482
