### ISSUE TITLE
Memory leakage occurs in OpenSSL, which may be caused by libcurl

### ISSUE THREAD

**Issue by xuwenlong02** [curl/curl#12486]
### I did this

```c++
void AddTask()
{
// loop to add curl_easy handle to curl_multi every 300 milionsecons
}

void RunTask()
{
     //  normal code about curl_multi and curl_easy 
   while(isRun_) { 
    ......
  }
}

int main(int argc, char *argv[])
{
  CURLM *curlMulti =  curl_multi_init();
  std::thread task(RunTask);

   std::vector<std::thread> vecfunc;
   std::function<void()> f = [argv](){
        AddTask(argv[2]);
    };
    for(int i = 0; i < atoi(argv[1]); i++) {
        vecfunc.push_back(std::thread(f));
    }
    for(int i = 0; i < atoi(argv[1]); i++) {
        vecfunc[i].join();
    }

  getchar();
  task.join();
  curl_multi_clean(curlMulti);
}
```
We find that the memory increase before task.join(); I'm sure curl_easy is freed every time.

### I expected the following

Is there any problem with this use? If there is no problem, why does OpenSSL keep increasing?

### curl/libcurl version

8.4.0

### operating system

cross platform base on linux

**Comment by xuwenlong02** [comment]
![Uploading 20231208-111541(WeLinkPC).png…]()

**Comment by jay** [comment]
There's a known issue #12327 that affects curl with static OpenSSL in Windows. We are working on a fix. In that case, OPENSSL_thread_stop has to be called on every thread before the thread is terminated.

> Is there any problem with this use? If there is no problem, why does OpenSSL keep increasing?

That is a question for you not for us. We cannot analyze your application. If you can provide a minimal self-contained example that can be used to reproduce then we will take a look.

**Comment by dfandrich** [comment]
It's hard to speculate without full code, but it looks like you're sharing curl handles across threads. This is a no-no. See https://curl.se/libcurl/c/threadsafe.html

**Comment by xuwenlong02** [comment]
> It's hard to speculate without full code, but it looks like you're sharing curl handles across threads. This is a no-no. See https://curl.se/libcurl/c/threadsafe.html

We've added a lock to ensure that the CURL handle is secure.

**Comment by bagder** [comment]
Without a way for us to reproduce, there is nothing we can do unless you provide A LOT more details.

**Comment by xuwenlong02** [comment]
> Without a way for us to reproduce, there is nothing we can do unless you provide A LOT more details.

[http_demo.zip](https://github.com/curl/curl/files/13644005/http_demo.zip)

**Comment by xuwenlong02** [comment]
![image](https://github.com/curl/curl/assets/20473316/85696793-bbb4-4f9d-97e1-fc295e94b391)
The memory grew from the initial 3.7M to the final 4MB, but all the memory in the application layer was released

**Comment by xuwenlong02** [comment]
![image](https://github.com/curl/curl/assets/20473316/25b089d4-a47d-4f68-84b5-291d0cd5ad4f)
50 PUTs were run, and each 1000KB too.  Memory grew from 3.5M to 4.8M

**Comment by bagder** [comment]
@xuwenlong02 run your example with valgrind. Does it point out a leak afterwards?

**Comment by xuwenlong02** [comment]
> @xuwenlong02 run your example with valgrind. Does it point out a leak afterwards?

No memory leak by valgrind

![image](https://github.com/curl/curl/assets/20473316/77c8174b-77bf-48d3-a3e0-6705524f6fde)

**Comment by BrianInglis** [comment]
Local patch applied by Cygwin OpenSSL maintainer to test release; see [Test: openssl 3.0.16-2, mingw64-{i686,x86_64}-openssl-3.0.16-2](https://cygwin.com/pipermail/cygwin-announce/2025-May/012341.html) and 
[openssl and libcurl issue with cargo](https://cygwin.com/pipermail/cygwin/2025-May/258203.html)
