### ISSUE TITLE
Proxy display hostname is null pointer

### ISSUE THREAD

**Issue by jay** [curl/curl#1248]
### I did this

`curl -v --proxy http://example.com:80 http://example.com`

### I expected the following

* Connected to example.com (93.184.216.34) port 80 (#0)

but instead I got

* Connected to (nil) (93.184.216.34) port 80 (#0)

![clipboard02](https://cloud.githubusercontent.com/assets/965580/22639229/f3351136-ec1a-11e6-89c6-e4edf37968dc.png)

Probably a missing fix hostname call somewhere.

### curl/libcurl version
~~~
curl 7.52.1 (i386-pc-win32) libcurl/7.52.1 OpenSSL/1.0.2k nghttp2/1.19.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug Largefile NTLM SSL HTTP2 HTTPS-proxy
~~~

### operating system

Windows 7

**Comment by mkauf** [comment]
Fixed, thank you for reporting!
