### ISSUE TITLE
build curl but the lib name is wrong

### ISSUE THREAD

**Issue by geektcp** [curl/curl#12498]
### I did this

down the curl release 8.5.0 version :
down url :  https://curl.se/download/curl-8.5.0.tar.gz

build it and install. to my disk:
F:\install-curl

### I expected the following
the library name is 
‪F:\install-curl\lib\libcurl.dll.a

but it is : 
‪F:\install-curl\lib\libcurl-d.dll.a

why not is ‪:
libcurl.dll.a  or libcurl.dll or libcurl.a

if name is not correact , there is many error ,becanuse the old and new CMAKE version can not find the library.
because FindCURL can not find_library this lib file.

the FindCURL.cmake is here: 
```
find_library(CURL_LIBRARY NAMES
    curl
  # Windows MSVC prebuilts:
    curllib
    libcurl_imp
    curllib_static
  # Windows older "Win32 - MSVC" prebuilts (libcurl.lib, e.g. libcurl-7.15.5-win32-msvc.zip):
    libcurl
)
```

This problem is so frustrating。I trouble shoot it all the afternoon.

I confirm that this is the reason for it.

### curl/libcurl version

8.5.0

### operating system

windown 10 x 64

**Comment by vszakats** [comment]
`-d` is the default suffix for CMake Debug builds (not Release ones). With `cmake ... -DCMAKE_DEBUG_POSTFIX=` you should be able to clear or override this default.

**Comment by bagder** [comment]
I supposes this ends this issue?

**Comment by vszakats** [comment]
I think it does. In Windows there is no standard, or universal convention, for naming libs. The only solution is to offer enough customization to fit each specific use-case.

**Comment by geektcp** [comment]
> I supposes this ends this issue?

yeah，the solution (-d  cmake ... -DCMAKE_DEBUG_POSTFIX= ) can fix it . but other one maybe trouble shoot it again .
You can handle it yourself.
