### ISSUE TITLE
/etc/ssh/ssh_config does not take effect when using libcurl with libssh

### ISSUE THREAD

**Issue by laogaolao** [curl/curl#12530]
### I did this

I added the '**_HostKeyAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521_**' in the ssh_config.
When I used libcurl to upload file with SFTP, the network sniffer tool will catch a lot unexpected algorithms such ass **_ssh-dss_** which is not defined in ssh_config.
the code section is like:

    curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0);
    curl_easy_setopt(curl, CURLOPT_PROGRESSDATA, (void*)this);
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);
    curl_easy_setopt(curl, CURLOPT_PROGRESSFUNCTION, &FTSProgressFunction);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 60L);
    curl_easy_setopt(curl, CURLOPT_FAILONERROR, 1);
    curl_easy_setopt(curl, CURLOPT_LOW_SPEED_TIME, 900); // 15 minutes
    curl_easy_setopt(curl, CURLOPT_LOW_SPEED_LIMIT, 1);  // 1 byte
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 0);          // no 
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);
    curl_easy_setopt(curl, CURLOPT_USERNAME, username); 
    curl_easy_setopt(curl, CURLOPT_PASSWORD, password);

    long anAuthType = 0;
    anAuthType |= CURLSSH_AUTH_PASSWORD;  
    curl_easy_setopt(curl, CURLOPT_SSH_AUTH_TYPES, anAuthType);
    curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, filesize);
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1);
    curl_easy_setopt(curl, CURLOPT_URL, remote_curl);
    curl_easy_setopt(curl, CURLOPT_READDATA, hd_src);
    res = curl_easy_perform(curl);

### I expected the following

I expect when using libcurl the Host keyalgorithm still be the list in the ssh_config if using network sniffer tool

### curl/libcurl version

curl 7.82.0 (powerpc-fsl-linux-gnu) libcurl/7.82.0 OpenSSL/3.0.12 zlib/1.2.11 libssh2/1.10.0

### operating system

Linux System 5.10.199-rt97 #1 SMP Sat Nov 11 00:27:33 UTC 2023 ppc ppc ppc GNU/Linux

**Comment by dfandrich** [comment]
Are you talking about the /etc/ssh/ssh_config file?  That's a configuration
file for the OpenSSH client and has nothing to do with curl.

**Comment by laogaolao** [comment]
I think the libcurl depends on libssh, so does that means libssh not using /etc/ssh/ssh_config as well?

**Comment by laogaolao** [comment]
@dfandrich Is that possible for libcurl to set the Host keyalgorithm when upload file with SFTP? Thanks

**Comment by dfandrich** [comment]
libssh is also independent of OpenSSH so I don't believe it uses that config
file either (although I'm not as sure about that one).  curl can use one of
three ssh backends, and I'm pretty sure curl does not support setting crypto
algorithms on any of them.

**Comment by laogaolao** [comment]
@dfandrich  Thanks for the reply.

I found a page https://github.com/curl/curl/issues/4972 mentioned:

Set libcurl defaults through ssh_options_set()
Manually call ssh_options_parse_config() to parse the configuration files
.....
ssh_options_set() should be API of openssh, but it need ssh session, I dont know how to use this for libcurl. Can libcurl get the current ssh session?

**Comment by dfandrich** [comment]
ssh_options_set() is a libssh API call. It doesn't look like there's any way to get
the underlying session ID out of libcurl but in any case, it's likely that even if
you could get it (with curl_easy_getinfo, for example), it will already be too
late to adjust it without a new callback mechanism added (such as
CURLOPT_SSL_CTX_FUNCTION for TLS).  libcurl already calls
ssh_options_parse_config() before it connects to the remote server, so whatever
config files it reads should already be read.

**Comment by laogaolao** [comment]
@dfandrich I checked the libcurl code and see the function static CURLcode myssh_connect(struct Curl_easy *data, bool *done), so if using libcurl to connect server with SFTP, this method will be called everually, right? So I want to add some code call ssh_options_set to set the host key here, is that possible? Thanks.

**Comment by dfandrich** [comment]
If your libcurl is configured with libssh, then yes, this will be called before
an SFTP connect. That looks like the right place to add some more
ssh_options_set() calls if you need them.

**Comment by laogaolao** [comment]
@dfandrich Thanks for your help, very appreciate, I will try it.

**Comment by bagder** [comment]
I believe libssh might be parsing `ssh_config` files by default? [This docs](https://api.libssh.org/master/group__libssh__session.html#ga7a801b85800baa3f4e16f5b47db0a73d) mentions:

> `SSH_OPTIONS_PROCESS_CONFIG` Set it to false to disable automatic processing of per-user and system-wide 
> OpenSSH configuration files. LibSSH automatically uses these configuration files unless you provide it with
> this  option or with different file (bool).

**Comment by vszakats** [comment]
@bagder Noticed in Windows builds, that it uses hard-coded \*nix locations to load parameters from. Here's my comment about it: https://github.com/curl/curl-for-win/blob/a43acce3133361437c6d1b94ac0f852b342fa500/libssh.sh#L6-L8

**Comment by bagder** [comment]
> Noticed in Windows builds, that it uses hard-coded *nix locations to load parameters from

Ouch!

**Comment by bagder** [comment]
It seems to be that libssh is documented to read this file so if it does not, it might be a libssh problem. libcurl does not explicitly disable it, and their docs says it then will parse it.
