### ISSUE TITLE
Example programs for CURLMOPT_TIMERFUNCTION don't handle timeout_ms == -1 correctly

### ISSUE THREAD

**Issue by mkauf** [curl/curl#1253]
### I did this
Studied the code of the example programs for `CURLMOPT_TIMERFUNCTION`:

- [asiohiper.cpp](https://github.com/curl/curl/blob/curl-7_52_1/docs/examples/asiohiper.cpp)
- [evhiperfifo.c](https://github.com/curl/curl/blob/curl-7_52_1/docs/examples/evhiperfifo.c)
- [ghiper.c](https://github.com/curl/curl/blob/curl-7_52_1/docs/examples/ghiper.c)
- [hiperfifo.c](https://github.com/curl/curl/blob/curl-7_52_1/docs/examples/hiperfifo.c)
- [multi-uv.c](https://github.com/curl/curl/blob/curl-7_52_1/docs/examples/multi-uv.c)

These example programs don't handle `timeout_ms == -1` correctly.

### I expected the following

The [documentation](https://curl.haxx.se/libcurl/c/CURLMOPT_TIMERFUNCTION.html) for `CURLMOPT_TIMERFUNCTION` says:

> A timeout_ms value of -1 means you should delete your timer.

These example programs call `curl_multi_socket_action()` instead:

- asiohiper.cpp
- evhiperfifo.c
- multi-uv.c

These exampe programs schedule a new timer instead:
- ghiper.c
- hiperfifo.c

Note that the timeout value 0 also has a special meaning:
> A timeout_ms value of 0 means you should call curl_multi_socket_action or curl_multi_perform (once) as soon as possible.

### curl/libcurl version

7.52.1

### operating system

All

**Comment by bagder** [comment]
The good thing is that just having an extra timer running or calling `curl_multi_socket_action()` an extra time are all pretty harmless actions.

**Comment by bagder** [comment]
multi-uv.c seems to handle it already.

I've fixed asiohiper.cpp and evhiperfifo.c in commit d6bb1f1d5

**Comment by mkauf** [comment]
Thanks!
