### ISSUE TITLE
Progress bar jumps to new line when using vga console under illumos

### ISSUE THREAD

**Issue by bahamat** [curl/curl#12531]
### I did this

`curl --progress-bar <some url>`

### I expected the following

The progress bar to be on a single line instead of multiple lines

<img width="1136" alt="Screenshot 2023-12-15 at 10 00 30 AM" src="https://github.com/curl/curl/assets/1612974/60b758a9-d0ad-4e70-b4cf-71bef65880a6">

### curl/libcurl version

8.5.0, but this also happened with 8.4.0.

```
[root@ /]# curl -V
curl 8.5.0 (x86_64-pc-solaris2.11) libcurl/8.5.0 OpenSSL/3.0.12 zlib/1.2.3 libidn2/2.3.4
Release-Date: 2023-12-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
```

### operating system

SmartOS (illumos)

```
[root@ /]# uname -o ; uname -a
illumos
SunOS headnode 5.11 joyent_20231214T000645Z i86pc i386 i86pc
```

**Comment by bahamat** [comment]
It's worth noting that this occurs only on a VGA console. It doesn't happen over ssh or serial console.

It happens with both the platform curl, and curl via pkgsrc (our package manager).

SmartOS ISO images can be downloaded from <https://us-central.manta.mnx.io/Joyent_Dev/public/SmartOS/smartos.html>.

If you have Linux KVM set up with libvirt you can run this command to spawn a SmartOS instance with the graphical display on VNC to reproduce the issue:

```
sudo virt-install --connect qemu:///system \
        --name "smartos-curl-12531" --os-variant smartos \
        --vcpus 2 --ram 2048 \
        --cdrom "${iso}" \
        --network bridge=virbr0,model=virtio \
        --graphics vnc --boot hd --disk size=20,sparse=true
```

This issue also occurs using VMware or VirtualBox.

I can provide infrastructure and assistance for setting up a build environment to build curl on SmartOS if it helps.

**Comment by bagder** [comment]
That makes it sounds as if that terminal reports the width a column too wide or something....

**Comment by bagder** [comment]
> 8.5.0, but this also happened with 8.4.0.

The progress bar width math has been the same since 789b43fc9227380f36 (7.1.1) and this is the only report of a wrap around we have received. I think it hints that this specific terminal is different than others. I don't think we can make curl detect this situation.

You can work around this issue by setting the `COLUMNS` environment variable to a smaller value.

I hesitate to make the bar one column shorter unconditionally everywhere since this seems to be an isolated problem case.

**Comment by jay** [comment]
Here's the code from 8.5.0 for calculating the bar width, it may be useful for the reporter to step through and find out where the number is coming from.

https://github.com/curl/curl/blob/7161cb17c01dcff1dc5bf89a18437d9d729f1ecd/src/tool_cb_prg.c#L225-L285

**Comment by bahamat** [comment]
I've done some more digging on my side, and this looks like it might be an illumos bug (filed here: https://www.illumos.org/issues/16126).

I still find it curious that 7.51.0 didn't exhibit the issue.

**Comment by bagder** [comment]
> I still find it curious that 7.51.0 didn't exhibit the issue.

It is indeed. I suppose someone could figure it out though if they really wanted...

**Comment by bagder** [comment]
This is a terminal bug, not a curl one.
