### ISSUE TITLE
Certs Bundle Reading Slow

### ISSUE THREAD

**Issue by Bloodiko** [curl/curl#12556]
I've some automated scripts in windows. 

Since windows "invoke-webRequest" does not support TLS1.3 properly, or only in a far later version, I switched to using curl for windows for some tasks. 

Although this works amazingly well, it is quite slow in comparison. 

## TLDR
Reading Cert bundle is slow. Using a smaller cert bundle with only necessary root CAs instead of all CAs is a lot faster. ~10x in my Test

## Issue
Main issue is, that the crt bundle is read every single launch, which if you invoke curl multiple times, increases the wait time by a lot. 

Running Curl with only the help, runs instant.
Actually using curl to access an website, reads the crt bundle - as needed. 

### Tests
I made 2 Tests, once with the full bundle, and once with a radically reduced crt bundle with only a few root CAs (3kb instead of 219 kb) 

### Running Only Curl

```ps
# With small cert bundle
PS D:\Programme\curl-8.4.0_6-win64-mingw\bin> Measure-Command {&$curl}
curl: try 'curl --help' or 'curl --manual' for more information

TotalMilliseconds : 43,8244


# With Big Cert Bundle
PS D:\Programme\curl-8.4.0_6-win64-mingw\bin> Measure-Command {&$curl}
curl: try 'curl --help' or 'curl --manual' for more information

TotalMilliseconds : 50,847
```

### Running curl with Website Access

```ps
# curl with small cert bundle
PS D:\Programme\curl-8.4.0_6-win64-mingw\bin> Measure-Command {&$curl $url}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3471  100  3471    0     0  27435      0 --:--:-- --:--:-- --:--:-- 66750
TotalMilliseconds : 177,479

# curl with big cert bundle
PS D:\Programme\curl-8.4.0_6-win64-mingw\bin> Measure-Command {&$curl $url}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3471  100  3471    0     0   2085      0  0:00:01  0:00:01 --:--:--  2181

TotalMilliseconds : 1711,7204

```

**Comment by bagder** [comment]
The cert loading is typically done by the TLS library. I don't think we can do much about that.

On windows `--ca-native` might be faster since then you can avoid the file loading, but instead it relies on the Windows CA store.

You can possibly opt to use a cert dir instead of a single path with the OpenSSL fork family, which might load less data/faster?

> TotalMilliseconds : 1711,7204

That is indeed mighty slow.

On my Linux machine:

~~~
$ time curl https://curl.se
real    0m0.038s
~~~

So 38 milliseconds for the whole thing.

**Comment by vszakats** [comment]
Three more ways to try:
- Using the native Windows CA store (`--ca-native` option I think).
- 8.5.0 that comes with LibreSSL.
- Workaround to make multiple requests on one invocation.

**Comment by Bloodiko** [comment]
Well, since its an airgapped environment I basically only need one CA, so supplying Curl with the Root CA instead of the full bundle is enough I guess. 

Take this as more of an information, in case someone else might stumble across this issue. 

I'll still try using the new 8.5 and or the ca-native option. 
Thanks 🙏

**Comment by vszakats** [comment]
There are small differences between the two, but the major one is 8.4.0_6 using quictls (OpenSSL) 3.1.4, while 8.4.0_9 and newer are using LibreSSL 3.8.2.

Such large difference is certainly unexpected, I'm not sure what might be going on in the OpenSSL codebase.

**Comment by bagder** [comment]
It does not seem there is much more for us to do here. Closing.
