### ISSUE TITLE
CURLE_UNSUPPORTED_PROTOCOL due to garbage response

### ISSUE THREAD

**Issue by danevandyck** [curl/curl#12552]
### I did this

After upgrading libcurl from 7-46 to 8-4, a testcase around graceful handling of garbage responses to HTTP requests began to fail because the upgraded libcurl returns CURLE_UNSUPPORTED_PROTOCOL from curl_easy_perform when presented with garbage data *in the response*. The request is well formed; the test server writes random data to the response stream when handing a /garbage endpoint.

### I expected the following

The observed behavior does not seem consistent with the stated purpose of CURLE_UNSUPPORTED_PROTOCOL.

### curl/libcurl version

8.4

### operating system

Ubuntu Linux 22.

**Comment by dfandrich** [comment]
Can you provide the request and response that produces this behaviour, as well
as the run-time and configure options?  This could be normal behaviour,
depending on those specifics (e.g. redirects are enabled and Location: URL has
a garbage protocol) so we'll need more info to reproduce it. Running "curl
http://localhost:8000" against "head -1000c /dev/random | nc -l 8000" doesn't do that.

**Comment by danevandyck** [comment]
Configure options
```
--enable-threaded-resolver \
  --disable-ldap \
  --with-openssl
```

Runtime config
```
// initialize SSL
. . .
curl_global_init(CURL_GLOBAL_NOTHING);
```

I was able to replicate the error with `curl` on my system. Maybe it's non-deterministic based on the HTTP version check.

window 1
```
% head -1000c /dev/random | nc -l 8000
GET / HTTP/1.1
Host: localhost:8000
User-Agent: curl/7.81.0
Accept: */*
```
window 2
```
% curl http://localhost:8000
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by danevandyck** [comment]
The request
* HTTP
* GET
* /garbage

The response content is non-deterministic. But I seem to be able to reproduce this consistently with different garbage each time, both with the system's Curl (7.81) and programatically with libcurl (8.4).

**Comment by danevandyck** [comment]
Here's what I see from `wget`, which seems to explain the observation. HTTP/0.9 is assumed in the absence of headers. Maybe we can avoid this by asserting a minimum version somehow.

```
% wget http://localhost:8000
--2023-12-18 18:35:50--  http://localhost:8000/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
```

**Comment by danevandyck** [comment]
RCA

```
       --http0.9
              (HTTP) Tells curl to be fine with HTTP version 0.9 response.

              HTTP/0.9  is a completely headerless response and therefore you can also connect with this to non-HTTP servers and still get a response since curl will simply
              transparently downgrade - if allowed.

              Since curl 7.66.0, HTTP/0.9 is disabled by default. *** ding ding ding
```

So . . . I'm okay with this now that I know what's going on. Seems like Curl could clarify whether protocol issues are the result of client vs server behavior for the purpose of disambiguation, but that seems like an enhancement since the observed behavior appears to be by design.

**Comment by bagder** [comment]
> Seems like Curl could clarify whether protocol issues are the result of client vs server behavior for the purpose of disambiguation

~~~
$ curl localhost:22
curl: (1) Received HTTP/0.9 when not allowed
~~~

How is this not explaining the situation? What else could it say to help?

**Comment by danevandyck** [comment]
It's difficult to say whether the protocol error that occurred is due to client vs server behavior without depending on error message content. Curl client apps could benefit from the ability to disambiguate client/server protocol issues by error code, allowing decontextualized error handling / conversion.

In this case, my client should be resilient to a bad server based on error code. Ideally, such resilience would not include a client's attempts to issue an unsupported request.

I agree that this isn't a bug. Thanks for your time.

**Comment by bagder** [comment]
I agree that is the ideal situation, but we also cannot add a unique error code for every situation and I think one seemed to fit rather nicely...
