### ISSUE TITLE
Configuring libcurl(7.30.0) with openssl(1.1.0d) not supporting the HTTPS protocol

### ISSUE THREAD

**Issue by gnanagurun** [curl/curl#1256]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
I configured and build the libcurl --with-ssl=<path-where-openssl-lib-installed>. But the result shows that it supports only HTTP not HTTPS. This is the configure (./configure --enable-shared=yes --with-ssl=/usr/local --without-zlib --without-libidn --without-libssh2 --without-nss --enable-static=yes --enable-ipv6 --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-proxy --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-manual --disable-verbose --disable-cookies --disable-tls-srp --disable-sspi --disable-librtmp --disable-ares --disable-thread --disable-threaded-resolver --enable-hidden-symbols --host=arm-cortex_a8-linux-gnueabi)
Below is the output of the configure:

configure: Configured to build curl/libcurl:

  curl version:     7.30.0
  Host setup:       arm-cortex_a8-linux-gnueabi
  Install prefix:   /home/gnatarajan/CLM-7.5.0/src/apps/install/arm_cortex/logging
  Compiler:         arm-cortex_a8-linux-gnueabi-gcc
  SSL support:      no      (--with-{ssl,gnutls,nss,polarssl,cyassl,axtls,winssl,darwinssl} )
  SSH support:      no      (--with-libssh2)
  zlib support:     no      (--with-zlib)
  krb4 support:     no      (--with-krb4*)
  GSSAPI support:   no      (--with-gssapi)
  SPNEGO support:   no      (--with-spnego)
  TLS-SRP support:  no      (--enable-tls-srp)
  resolver:         default (--enable-ares / --enable-threaded-resolver)
  ipv6 support:     enabled
  IDN support:      no      (--with-{libidn,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   no
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   /etc/pki/tls/certs/ca-bundle.crt
  ca cert path:     no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     no      (--enable-rtsp)
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  Protocols:        HTTP

### I expected the following
I expected that SSL support should be yes
### curl/libcurl version
Libcurl - 7.30.0
OpenSSLl-1.1.0d
[curl -V output perhaps?]

### operating system
Doing cross compile in x86_64 for arm architecture

**Comment by jay** [comment]
Is there some reason you can't use the latest version of curl? That version is about 4 years old now. I haven't had to manually cross-compile anything in a while but I'm pretty sure I had to set environment variables and with-ssl to my cross compiled openssl.

I suggest reading the cross compile section in [install](https://curl.haxx.se/docs/install.html) and use the latest curl. If you can't get it working ask on the [curl-library mailing list](https://cool.haxx.se/mailman/listinfo/curl-library).
