### ISSUE TITLE
curl_easy_perform fails inside DLL

### ISSUE THREAD

**Issue by Spuckwaffel** [curl/curl#12577]
### I did this

Hey there, this issue was already mentioned in #2761, but OP fixed it by restarting VS or his OS, however this doesn't fix the issue for me.
The issue in general is that within a dll, Curl gets stuck when using a URL to resolve the ipv6, it just stops infinitely, not even a crash nor the verbose log logs anything. A simple request to https://www.google.com does not work, but a request to a ipv6 works.

Example code which fails at curl_easyperform:

```c++
#include <Windows.h>
#include <iostream>
#include <curl/curl.h>

size_t WriteCallback(void* contents, size_t size, size_t nmemb, std::string* output) {
    size_t totalSize = size * nmemb;
    output->append((char*)contents, totalSize);
    return totalSize;
}

int main() {
    // Initialize libcurl
    CURL* curl = curl_easy_init();
    if (!curl) {
        std::cerr << "Error initializing libcurl." << std::endl;
        return 1;
    }

    // Set the URL to visit
    const char* url = "https://www.google.com";
    curl_easy_setopt(curl, CURLOPT_URL, url);

    // Set the callback function to handle the response
    std::string response;
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);

    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

    // Perform the HTTP request
    CURLcode res = curl_easy_perform(curl);

    // Check for errors
    if (res != CURLE_OK) {
        std::cerr << "Failed to perform HTTP request. Error: " << curl_easy_strerror(res) << std::endl;
    } else {
        // Print the response
        std::cout << "Response from " << url << ":\n" << response << std::endl;
    }

    // Clean up
    curl_easy_cleanup(curl);

    return 0;
}

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        main();
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
```
The code works fine when i build an application, however not when building a dll and loading it.

### I expected the following

A valid http request and response or at least a error message

### curl/libcurl version

latest, 8.5.0

### operating system

Windows 10 x64

**Comment by Spuckwaffel** [comment]
also mentioned here: [https://github.com/curl/curl/issues/12483](url), but I don't see using a different thread as a valid fix, i want to know what exactly the issue is. Also for fun i tried to use inside the DLL via ``getProcAddress`` and ``LoadLibrary`` to load the official prebuilt and signed dll ``libcurl-x64.dll`` and via ``getProcAddress`` to ge tthe routines and call them, however the output is the exact SAME. This has to be some internal issue in curl possible with memory management or some loophole

**Comment by bagder** [comment]
> This has to be some internal issue in curl

- happens only on Windows it looks like
- related to threads?
- seems to be name resolve related

Seeing there is nothing new in curl's resolver/threading setup recently and people have used libcurl on Windows for decades, I suspect there are some additional details to this problem that we have not unveiled yet.

Personally I don't develop on Windows and I have don't a lot of clues to offer for this. One thing you could try is to see if using the non-threaded resolver makes things work, as then we can be sure it is related to the threaded resolver. 

You then probably need to edit code here:

https://github.com/curl/curl/blob/000c7381402d03c8de8605d56f55c69bc6dc34ca/lib/curl_setup.h#L617-L622

**Comment by Spuckwaffel** [comment]
hey there, i think i built it now using the non-threaded resolver (im unsure, all i did was change the elif line to `` #elif defined(USE_THREADS_POSIX) && defined(USE_THREADS_WIN32) `` which should always be FALSE and therefore CURLRES_SYNCH  should be defined.)

It works fine when creating an application, however when creating a dll it hangs here:
```
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => CONNECT handle 0x1f05a2f0fb8; line 1942
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x1f05a2f0fb8; line 1985
```
"Seeing there is nothing new in curl's resolver/threading setup recently and people have used libcurl on Windows for decades, I suspect there are some additional details to this problem that we have not unveiled yet." Well, the open issues to this issue are still open and unknown.

**Comment by jay** [comment]
you can do basically nothing in dllmain because it holds the loader lock. you're probably experiencing deadlock. this is not a curl issue afaics. in other words: don't call any libcurl functions from dllmain.

**Comment by Spuckwaffel** [comment]
Looks like I'm experiencing a deadlock, however it would be good to know where and what's the cause

**Comment by jay** [comment]
that's up to you. we can't support that behavior and we already [warn](https://curl.se/libcurl/c/curl_global_init.html) against it:

_If you are initializing libcurl from a Windows DLL you should not initialize it from **DllMain** or a static initializer because Windows holds the loader lock during that time and it could cause a deadlock._

also see https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices
