### ISSUE TITLE
Still need to set CURLSSLOPT_NATIVE_CA when CURLINFO_CAINFO is not specified using Schannel

### ISSUE THREAD

**Issue by xsgao-github** [curl/curl#12598]
### I did this

According to https://curl.se/libcurl/c/CURLOPT_CAINFO.html;

> (Schannel) This option is supported for Schannel in Windows 7 or later but we recommend not using it until Windows 8 since it works better starting then. If the option is not set, then curl uses the certificates in the Windows' store of root certificates (the default for Schannel).

and https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html:

> CURLSSLOPT_NATIVE_CA
>
> Tell libcurl to use the operating system's native CA store for certificate verification. If you set this option and also set a CA certificate file or directory then during verification those certificates are searched in addition to the native CA store.
>
> Works with wolfSSL on Windows, Linux (Debian, Ubuntu, Gentoo, Fedora, RHEL), macOS, Android and iOS (added in 8.3.0), with GnuTLS (added in 8.5.0) or on Windows when built to use OpenSSL (Added in 7.71.0).

I should not set `CURLOPT_CAINFO` and `CURLOPT_SSL_OPTIONS`/`CURLSSLOPT_NATIVE_CA` if I want to use Windows system root cert store.

So I build libcurl with ` curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.4.0` and did not specify anything in my code.

### I expected the following

I expected that libcurl should pick a root cert from my Windows personal trusted store root certificates, but it actually errored out.

It turned out that `CURLSSLOPT_NATIVE_CA` works on Schannel on Windows as well, and I **_MUST_** call `curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA)` in order to get libcurl load certs from Windows.

### curl/libcurl version

curl 8.4.0.

### operating system

Windows 2022

**Comment by jay** [comment]
That's not a bug.

**Comment by bagder** [comment]
I question if this is actually true. I see nothing in schannel.c that knows about the `CURLSSLOPT_NATIVE_CA` option. I don't think any curl command line users on Windows (using the native version provided by Microsoft) ever use `--ca-native` and yet they can use HTTPS fine.

**Comment by jay** [comment]
One way this could happen is if the reporter is using curl built for MultiSSL w/ OpenSSL and Schannel, and OpenSSL is the selected backend either by default or chosen by the user.

**Comment by bagder** [comment]
Agreed, but the description above doesn't make it sound like that's what is being used!

**Comment by xsgao-github** [comment]
> One way this could happen is if the reporter is using curl built for MultiSSL w/ OpenSSL and Schannel, and OpenSSL is the selected backend either by default or chosen by the user.

I am using vcpkg and on Windows 2022, and here is the `vcpkg.json`:

```
{
  "name": "xxxx",
  "version-string": "1.0.0",
  "dependencies": [
    "boost-test",
    "boost-thread",
    {"name": "curl", "version>=": "8.4.0"},
    "openssl"
  ],
  "overrides": [
  ],
  "builtin-baseline": "501db0f17ef6df184fcdbfbe0f87cde2313b6ab1"
}
```

The output when compiling libcurl: `curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.4.0`. So I am assuming I am using Schannel without OpenSSL?

If this is not a product bug, document needs to be updated to reflect that `CURLSSLOPT_NATIVE_CA` needs to be specified explicitly, and `CURLSSLOPT_NATIVE_CA` does work with Schannel on Windows.

**Comment by bagder** [comment]
> I am assuming I am using Schannel without OpenSSL?

I don't know what vcpkg provides for you. However, based on your description it sounds as if you **don't** use schannel...

> If this is not a product bug, document needs to be updated to reflect

schannel uses the native CA store by default and has done so for many years. There is no code for even considering  `CURLSSLOPT_NATIVE_CA` which makes your report very puzzling.

**Comment by xsgao-github** [comment]
If I added `openssl` feature in vcpkg.json, `{"name": "curl", "version>=": "8.4.0", "features": ["openssl"]}`, and then compiled libcurl , I got this output `curl[core,non-http,openssl,schannel,ssl,sspi]:x64-windows -> 8.4.0`, where `openssl` in explicitly added in the features.

When remembered that when I was using an old version of libcurl, 7.86.0, and compiled libcurl without openssl feature, add had `curl_easy_opt(curl, CURLOPT_PROXYTYPE, CURLPROXY_HTTPS)` in my code, I got error saying it's not supported. This matches https://curl.se/libcurl/c/CURLOPT_PROXYTYPE.html: 

> CURLPROXY_HTTPS
>
>HTTPS Proxy using HTTP/1. (Added in 7.52.0 for OpenSSL and GnuTLS. Since 7.87.0, it also works for BearSSL, mbedTLS, rustls, Schannel, Secure Transport and wolfSSL.)

That is why I am assuming I have a libcur without OpenSSL.

Is there a way to check what features are supported in my output `libcurl-d.dll`, like `curl --version` does?

**Comment by bagder** [comment]
[curl_version_info](https://curl.se/libcurl/c/curl_version_info.html)

**Comment by jay** [comment]
Yes, call curl_version() after curl_global_init(). Any inactive SSL libraries will be in parentheses. (note DEV builds of libcurl may not show this information due to a bug #12599)

You should see something like this: `libcurl/8.6.0-DEV OpenSSL/3.0.8 (Schannel) nghttp2/1.52.0`
In this example OpenSSL is the selected SSL backend.

**Comment by xsgao-github** [comment]
`libcurl->ssl_version` gave me `Schannel`.

**Comment by jay** [comment]
That doesn't make sense because as @bagder said CURLSSLOPT_NATIVE_CA does not affect Schannel. Are you sure your program is loading the right DLL? Try this:
~~~c
#define _CRT_NONSTDC_NO_DEPRECATE
#define _WIN32_WINNT 0x501

#include <windows.h>
#include <stdio.h>
#include <curl/curl.h>

int main()
{
  HMODULE module;
  char path[MAX_PATH];

  if(!GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                         GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                         (void *)curl_global_init, &module)) {
    fprintf(stderr, "GetModuleHandleExA error %d\n", GetLastError());
    exit(1);
  }

  if(!GetModuleFileNameA(module, path, MAX_PATH)) {
    fprintf(stderr, "GetModuleFileNameA error %d\n", GetLastError());
    exit(1);
  }
  path[MAX_PATH-1] = '\0';

  printf("The module that contains libcurl is \"%s\"\n", path);

  curl_global_init(CURL_GLOBAL_ALL);
  printf("\n%s\n", curl_version());

  return 0;
}
~~~

**Comment by xsgao-github** [comment]
There might be some invalid cache in my build directory. After doing a couple of clean rebuild, I can confirm that I don't need to set `CURLSSLOPT_NATIVE_CA` when using Schannel, and I do need to set it when using OpenSSL.

Thank you for all your help.
