### ISSUE TITLE
flag `--cacert` behavior isn't consistent between macOS and Linux

### ISSUE THREAD

**Issue by lunarwhite** [curl/curl#12604]
### I did this

Issued an ACME certificate from [Let's Encypt](https://letsencrypt.org/)(public trusted CA), for `<webapp.mydomain>`.

Tried to `curl -v https://<webapp.mydomain>`, cert works will both.

<details>
<summary>on macOS</summary>

```
$ curl -v https://<webapp.mydomain>
...
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: [NONE]
*  start date: Dec 28 11:18:25 2023 GMT
*  expire date: Mar 27 11:18:24 2024 GMT
*  subjectAltName: host "<webapp.mydomain>" matched cert's "<webapp.mydomain>"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: <webapp.mydomain>
> User-Agent: curl/8.4.0
> Accept: */*
>
...
```

</details>
<details>
<summary>on Fedora</summary>

```
$ curl -v https://<webapp.mydomain>
...
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: [NONE]
*  start date: Dec 28 11:18:25 2023 GMT
*  expire date: Mar 27 11:18:24 2024 GMT
*  subjectAltName: host "hello-openshift-hello.apps.yuewu413aws.qe.devcluster.openshift.com" matched cert's "hello-openshift-hello.apps.yuewu413aws.qe.devcluster.openshift.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: hello-openshift-hello.apps.yuewu413aws.qe.devcluster.openshift.com
> User-Agent: curl/8.0.1
> Accept: */*
...
```

</details>

But, when I gived a **wrong** `ca.crt` using flag `--cacert`, weird that it's not consistent

<details>
<summary>macOS will still work</summary>

```
$ curl -v https://<webapp.mydomain> --cacert ca.crt
...
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: ca.crt
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: [NONE]
*  start date: Dec 28 11:18:25 2023 GMT
*  expire date: Mar 27 11:18:24 2024 GMT
*  subjectAltName: host "<webapp.mydomain>" matched cert's "<webapp.mydomain>"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: <webapp.mydomain>
> User-Agent: curl/8.4.0
> Accept: */*
...
```

</details>
<details>
<summary>Fedora will hit error: curl: (60) SSL certificate problem: unable to get local issuer certificate</summary>

```
$ curl -v https://<webapp.mydomain> --cacert ca.crt
...
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: ca.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

</details>

### I expected the following

From the output, when I didn't specific `--cacert`, macOS and Linux will both use system CA bundle: `/etc/pki/tls/certs/ca-bundle.crt` for Linux and `/etc/ssl/cert.pem` for macOS.

One possible root cause I guess, when using `--cacert`, macOS curl will first use `ca.crt`, if not match, will continue use system CA bundle, which include Let's Encrypt's CA. While Linux curl won't use system CA bundle if not match.

### curl/libcurl version

on macOS:
```
curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
```

on Fedora:
```
curl 8.0.1 (x86_64-redhat-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.5/openssl/zlib nghttp2/1.52.0
```

### operating system

macOS
```
Darwin My-MacBook-Pro 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
```

Fedora
```
Linux fedora38-x86 6.5.13-my-fedora-vm-00116-gb64875927ef8 #1 SMP Wed Dec  6 22:19:46 UTC 2023 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
Is the macOS version the one shipped by Apple ?

**Comment by bagder** [comment]
I suspect this is the effect of the TLS libraries behaving differently and the problem is in the macOS+libresSSL case.

Apple might have modified it. In this case it clearly is wrong. If you read the curl source code, you can see that curl treats them the same so they *should* behave the same.

Does this reproduce if you build curl and libreSSL yourself?

**Comment by lunarwhite** [comment]
I had some trouble to build `curl` from source on macOS, so I just tried to install another `curl` using homebrew:
```
$ which curl
/opt/homebrew/opt/curl/bin/curl

$ curl -V
curl 8.5.0 (aarch64-apple-darwin23.0.0) libcurl/8.5.0 (SecureTransport) OpenSSL/3.2.0 zlib/1.2.12 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.58.0 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-12-06
```

Now it behaved same as Linux.
```
$ curl -v https://google.com --cacert ./ca.crt
...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: ./ca.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
...
```

**Comment by bagder** [comment]
> Now it behaved same as Linux.

Thank you. This makes it clear that this problem is created by Apple in the curl binary they ship. We cannot fix it. I have reached out to Apple about it.

**Comment by bagder** [comment]
Because this is not a bug in (our) curl, I consider this case closed.

**Comment by bagder** [comment]
I reported this as a security problem to Apple.

[They decided it is not](https://daniel.haxx.se/blog/2024/03/08/the-apple-curl-security-incident-12604/)

**Comment by jay** [comment]
> They decided it is not

Apple's most recent build of curl is a [patched 8.4.0](https://github.com/apple-oss-distributions/curl/blob/curl-154/curl/include/curl/curlver.h#L35). I compared [their openssl.c](https://github.com/apple-oss-distributions/curl/blob/curl-154/curl/lib/vtls/openssl.c) against [our openssl.c](https://github.com/curl/curl/blob/curl-8_4_0/lib/vtls/openssl.c) and there was hardly any difference. So the change is probably something they did to LibreSSL. Unfortunately I can't find their LibreSSL patched source on their [oss website](https://opensource.apple.com/releases/) or their [oss github organization](https://github.com/orgs/apple-oss-distributions/repositories?language=&q=ssl&sort=&type=all). If we had the source changes we could determine whether it is worthwhile to write a bypass.

**Comment by Kyle-Ye** [comment]
> > They decided it is not
> 
> Apple's most recent build of curl is a [patched 8.4.0](https://github.com/apple-oss-distributions/curl/blob/curl-154/curl/include/curl/curlver.h?rgh-link-date=2024-03-10T06%3A20%3A12Z#L35). I compared [their openssl.c](https://github.com/apple-oss-distributions/curl/blob/curl-154/curl/lib/vtls/openssl.c?rgh-link-date=2024-03-10T06%3A20%3A12Z) against [our openssl.c](https://github.com/curl/curl/blob/curl-8_4_0/lib/vtls/openssl.c?rgh-link-date=2024-03-10T06%3A20%3A12Z) and there was hardly any difference. So the change is probably something they did to LibreSSL. Unfortunately I can't find their LibreSSL patched source on their [oss website](https://opensource.apple.com/releases/) or their [oss github organization](https://github.com/orgs/apple-oss-distributions/repositories?language=&q=ssl&sort=&type=all). If we had the source changes we could determine whether it is worthwhile to write a bypass.

The OpenSSL source shipped with macOS 14.3 should be this repo and this branch (Found in https://opensource.apple.com/releases/)

https://github.com/apple-oss-distributions/OpenSSL098/tree/OpenSSL098-84.120.1

And checking their patches, I suspect this is due to this [patch](https://github.com/apple-oss-distributions/OpenSSL098/blob/OpenSSL098-84.120.1/patches/3028241%2B6497663-OSXROOTCERT.patch)

**Comment by bagder** [comment]
> The OpenSSL source shipped with macOS

LibreSSL is not OpenSSL

**Comment by Kyle-Ye** [comment]
> LibreSSL is not OpenSSL

Here is the results from Gemini. Correct me if the information is wrong.
LibreSSL:
• macOS: Apple uses LibreSSL as the default TLS/SSL library in macOS, including the curl implementation.
• Homebrew: Curl can be installed on macOS using Homebrew, which provides both OpenSSL and LibreSSL versions.
OpenSSL:
• Most platforms: Curl on most platforms (Linux, Windows, etc.) uses OpenSSL by default.
• Alpine Linux: OpenSSL is the preferred TLS/SSL library in Alpine Linux, including the curl implementation.

Looks like my env is using the homebrew openssl here. Will it effect the curl's behavior bundled in the OS?
```shell
# zsh
which openssl
/opt/homebrew/bin/openssl

openssl version
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)

where openssl
/opt/homebrew/bin/openssl
/usr/bin/openssl

/usr/bin/openssl version
LibreSSL 3.3.6
```

And `export OPENSSL_X509_TEA_DISABLE=1` did seem work here for me. I'm a little confused here.

**Comment by bagder** [comment]
>  • macOS: Apple uses LibreSSL as the default TLS/SSL library in macOS, including the curl implementation.

The default Apple TLS solution is called **Network Framework** these days. It used to be **Secure Transport**. curl can only get built with the latter, not the former.

curl as shipped by Apple is built to use LibreSSL, but I don't think Apple provides API access to that TLS library. curl on Apple used to be built against Secure Transport years ago.

If you build curl on macOS yourself, even if you want to use LibreSSL, you would (need to) build your own library anyway and not use the one Apple ships. Most people on macports or homebrew that build curl will build it against OpenSSL.

>  • Most platforms: Curl on most platforms (Linux, Windows, etc.) uses OpenSSL by default.

curl on Windows 10 and 11 as shipped by Microsoft uses Schannel. But yes, OpenSSL is the most commonly used TLS backend among curl users.

**Comment by Kyle-Ye** [comment]
> curl as shipped by Apple is built to use LibreSSL

Yes. This can be verified by running `/usr/bin/curl --version`.

> But `export OPENSSL_X509_TEA_DISABLE=1` did seem work here for me on macOS.

What bothered me is that why `OPENSSL_X509_TEA_DISABLE=1` can solve the issue here since the logic is in [their OpenSSL codebase](https://github.com/apple-oss-distributions/OpenSSL098/blob/OpenSSL098-84.120.1/patches/3028241%2B6497663-OSXROOTCERT.patch)?

Running some reverse engineering with the OS's openssl (`/usr/bin/openssl`/LibreSSL 3.3.6), I could also not found `"OPENSSL_X509_TEA_DISABLE"` string here.

**Comment by bagder** [comment]
It is hardly surprising to anyone that LibreSSL has (lots of?) code and functionality shared with OpenSSL even still.

**Comment by Kyle-Ye** [comment]
> It is hardly surprising to anyone that LibreSSL has (lots of?) code and functionality shared with OpenSSL even still.

Anyway using some tricks, I final understand the connection here between the patch and curl behavior here.

The Apple's logic actually happens on crypto.dylib product.

<img width="1371" alt="image" src="https://github.com/curl/curl/assets/43724855/fbba051a-67e4-43ba-97f8-f3f4043f8372">

And the dependency graph is `/usr/bin/curl → /usr/lib/libcurl.4.dylib(Cache) → /usr/lib/libcrypto.46.dylib(Cache)`

<img width="1485" alt="image" src="https://github.com/curl/curl/assets/43724855/70271530-f3f7-4310-abad-2bbaf55388b1">

> Note: the dylib files can't be directly access in file system. Instead they are cached as DYLD_CACHE in recent macOS versions.

**Comment by ProtoFoo** [comment]
> Here is the results from Gemini. Correct me if the information is wrong.

> Correct me 

Why? You did not bother to check the information in the first place and just trust an LLM generator instead. Why should we do the work for you, @Kyle-Ye?

**Comment by Kyle-Ye** [comment]
> > Here is the results from Gemini. Correct me if the information is wrong.
> 
> > Correct me
> 
> Why? You did not bother to check the information in the first place and just trust an LLM generator instead. Why should we do the work for you, @Kyle-Ye?

I'm not asking you to work for me, I'm just providing information that Apple does provide the relevant source code and that we can work around this issue with the relevant environment variables.

Since I don't know much about the history of OpenSSL and LibraSSL, I looked up Google and Gemini and posted them as part of my reply above. Glad bagder gave me more context on this.

Maybe I'm being overly sensitive, but I found your reply a bit offensive. Please don't continue this meaningless topic and @ me, otherwise I will treat it as spam.
