### ISSUE TITLE
libcurl memory leak

### ISSUE THREAD

**Issue by lyl-312** [curl/curl#12603]
### I did this

I use libcurl to make network requests, but there is a memory leak, the leaked stack can also be caught, please see what is this problem? I call the API after curl_easy_perform to release the memory, but the memory still cannot be released.The memory is not released after 1 hour.

~~~
CONF_modules_unload(1): Unloads all loaded OpenSSL modules.
EVP_cleanup(): Clears all EVP encryption algorithms and message digest algorithms.
Engine_cleanup(): Clears all OpenSSL engines.
CRYPTO_cleanup_all_ex_data(): Clears all OpenSSL extension data.
ERR_remove_state(0): Clears all error states.
ERR_free_strings(): Releases all error strings.
SSL_COMP_free_compression_methods(): Releases all SSL compression methods.
curl_easy_cleanup(curl): clears all easy handles of libcurl.
curl_global_cleanup(): Clears all libcurl global resources.
FreeCurlSlist(slist): Releases all libcurl slists.
~~~

Memory leaked stack:
~~~
 findnetwork	12.00 KB	100.00%
 ERR set mark /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	8.00 KB	66.67%
	ossl err get state int /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soar	8.00 KB	66.67% 
		 OPENSSL init crypto /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soe	8.00 KB 	66.67% 
			CRYPTO THREAD run once /system/lib64/chipset-pub-sdk/libcrypto opens... 	8.00 KB 	66.67%
				 pthread once /system/lib/ld-musl-aarch64.so.1	8.00 KB 	66.67% 
					 0x2567e4 /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	8.00 KB  	66.67% 
						ossl_err load crypto strings /system/lib64/chipset-pub-sdk/libcrypt...	8.00 KB  	66.67%
							ossl err load Ul strings /system/lib64/chipset-pub-sdk/libcrypto...	8.00 KB 	66.67% 
							  ERR load strings const /system/lib64/chipset-pub-sdk/libcrypt...	8.00 KB  	66.67% 
							     0x256917 /system/lib64/chipset-pub-sdk/libcrypto openssl.z...	8.00 KB  	66.67% 
~~~

### I expected the following

Invoke the libcurl interface. After curl_easy_cleanup, the OpenSSL memory is not released.

### curl/libcurl version

4.8.0

### operating system

# uname -a
Linux localhost 5.10.97+ #1 SMP PREEMPT Mon Dec 25 12:20:16 CST 2023 aarch64

**Comment by bagder** [comment]
> 4.8.0

That's not a curl version number, that looks like the SONAME. The version number is shown by `curl -V` or `curl_version()`.

**Comment by bagder** [comment]
The fact that memory is still in use after a long time is not a proof of a leak. It is probably just memory released at the final cleanups.

If `valgrind` identifies a leak, it most probably is. Does it?

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by lyl-312** [comment]
> > 4.8.0
> 
> That's not a curl version number, that looks like the SONAME. The version number is shown by `curl -V` or `curl_version()`.

curl  verdion is 8.4.0

**Comment by lyl-312** [comment]
> Thanks a lot for your report!
> 
> I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

****************
The main code is as follows:
Invoke the RequestHttpsDo interface to implement network requests.


#include <string>
#include "curl/easy.h"
#include "openssl/crypto.h"
#include "openssl/err.h"
#include "openssl/evp.h"
#include "openssl/conf.h"
#include "openssl/engine.h"
#include "openssl/ssl.h"
#include "crypto/err.h"



using std::ifstream;
using std::map;
using std::string;
using std::vector;



const std::int32_t HTTP_REQUEST_OK = 200;

void HttpCurl::GenerateCurlSlist(curl_slist *&curlList, const vector<string> &header)
{
    curlList = 0;
    for (const auto &s : header) {
        curlList = curl_slist_append(curlList, s.c_str());
    }
}

void HttpCurl::FreeCurlSlist(curl_slist *list)
{
    if (list != nullptr) {
        curl_slist_free_all(list);
        list = nullptr;
    }
}

size_t HttpCurl::OnWriteCallback(void *buffer, size_t size, size_t memb, void *ptr)
{
    if (ptr == nullptr || buffer == nullptr) {
        return -1;
    }
    string *value = reinterpret_cast<string *>(ptr);
    char *data = reinterpret_cast<char *>(buffer);
    value->append(data, size * memb);
    return size * memb;
}



void HttpCurl::RequestHttpsDo(FnRequest &fnReq, FnResponse &fnResp)
{
    CURLcode res;
    std::vector<std::string> headerList = {};

    CURL *curl = curl_easy_init();
    if (curl == nullptr) {
        fnResp.code = FnInnerErrCode::NETWORK_INNER_FAIL;
        fnResp.errorMessage = "curl init failed";
        return;
    }

    HttpCurl::SetCurlHeaders(fnReq, headerList);
    curl_slist *slist = nullptr;
    GenerateCurlSlist(slist, headerList);
    if (slist != nullptr) {
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, slist);  
    }
    std::string response;
    SetCurlHttpsOpt(curl, response, fnReq);

    curl_easy_setopt(curl, CURLOPT_SSL_SESSIONID_CACHE, 0L);

    // char curlErrorBuffer[100] = {};
    // curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, curlErrorBuffer);

    res = curl_easy_perform(curl);
    if (res != CURLE_OK) {
        fnResp.code = FnInnerErrCode::NETWORK_INNER_FAIL;
        fnResp.errorMessage = "curl perform failed";
        return;
    }

    long responseCode = 0;
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &responseCode);


    ERR_clear_error();
    EVP_cleanup();
    ERR_free_strings();


  
    FreeCurlSlist(slist);
    curl_easy_cleanup(curl);

    curl_global_cleanup();
    curl_version_info_data *p_version = curl_version_info(CURLVERSION_NOW);

    if (responseCode != HTTP_REQUEST_OK) {
        fnResp.code = responseCode;
        fnResp.errorMessage = response;
        return;
    }

    fnResp.code = FnInnerErrCode::SUCCESS_STATUS;
    fnResp.errorMessage = std::string("success. curl verdion:") + p_version->version;
    fnResp.data = response;
}

void HttpCurl::SetCurlHttpsOpt(CURL *curl, std::string &response, const FnRequest &fnReq)
{
    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, fnReq.method.c_str());
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, fnReq.body.c_str());
    curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, fnReq.body.size());
    curl_easy_setopt(curl, CURLOPT_URL, fnReq.url.c_str());

    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);

    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
    curl_easy_setopt(curl, CURLOPT_CAINFO, fnReq.caPath.c_str());

    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, fnReq.connectTimeout);  
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, fnReq.timeout);               
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, OnWriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, reinterpret_cast<void *>(&response));
    return;
}

void HttpCurl::SetCurlHeaders(const FnRequest &fnReq, std::vector<std::string> &headerList)
{
    headerList.push_back(HttpHeaderName::DEVICE_ID + ": " + fnReq.deviceid);
    headerList.push_back(HttpHeaderName::SRC_TRAN_ID + ": " + fnReq.srctranid);
    headerList.push_back(HttpHeaderName::VERSION + ": " + fnReq.version);
    headerList.push_back(HttpHeaderName::TIMESTAMP + ": " + fnReq.timestamp);
    headerList.push_back(HttpHeaderName::DEVICE_TYPE + ": " + fnReq.deviceType);
    headerList.push_back(HttpHeaderName::CONTENT_TYPE + ": " + fnReq.contentType);
    headerList.push_back(HttpHeaderName::ACCEPT + ": " + fnReq.accept);
    headerList.push_back(HttpHeaderName::SDK_VERSION + ": " + fnReq.sdkVersion);
    headerList.push_back(HttpHeaderName::OS_VERSION + ": " + fnReq.osVersion);
    headerList.push_back(HttpHeaderName::LANGUAGE + ": " + fnReq.language);
    headerList.push_back(HttpHeaderName::AUTHORIZATION + ": " + fnReq.authorization);
    headerList.push_back(HttpHeaderName::SIGN + ": " + fnReq.signature);
    return;
}

**Comment by bagder** [comment]
And where does valgrind say the memory leak is?

**Comment by bagder** [comment]
> The main code is as follows:

It does not compile.

**Comment by lyl-312** [comment]
> findnetwork	12.00 KB	100.00%
>  ERR set mark /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	8.00 KB	66.67%
> 	ossl err get state int /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soar	8.00 KB	66.67% 
> 		 OPENSSL init crypto /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soe	8.00 KB 	66.67% 
> 			CRYPTO THREAD run once /system/lib64/chipset-pub-sdk/libcrypto opens... 	8.00 KB 	66.67%
> 				 pthread once /system/lib/ld-musl-aarch64.so.1	8.00 KB 	66.67% 
> 					 0x2567e4 /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	8.00 KB  	66.67% 
> 						ossl_err load crypto strings /system/lib64/chipset-pub-sdk/libcrypt...	8.00 KB  	66.67%
> 							ossl err load Ul strings /system/lib64/chipset-pub-sdk/libcrypto...	8.00 KB 	66.67% 
> 							  ERR load strings const /system/lib64/chipset-pub-sdk/libcrypt...	8.00 KB  	66.67% 
> 							     0x256917 /system/lib64/chipset-pub-sdk/libcrypto openssl.z...	8.00 KB  	66.67%

**Comment by lyl-312** [comment]
> And where does valgrind say the memory leak is?

Memory doesn't grow all the time. After the first network request is complete, some memory is not released. The number of subsequent network requests does not increase.

The call stacks that do not release the memory are as follows:
  ERR_set_mark /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	
	ossl_err_get_state_int /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soar	
		 OPENSSL_init_crypto /system/lib64/chipset-pub-sdk/libcrypto openssl.z.soe	
			CRYPTO_THREAD_run_once /system/lib64/chipset-pub-sdk/libcrypto opens... 	
				 pthread_once /system/lib/ld-musl-aarch64.so.1	
					 0x2567e4 /system/lib64/chipset-pub-sdk/libcrypto openssl.z.so	
						ossl_err_load_crypto_strings /system/lib64/chipset-pub-sdk/libcrypt...	
							ossl_err_load_Ul_strings /system/lib64/chipset-pub-sdk/libcrypto...	
							  ERR_load_strings_const /system/lib64/chipset-pub-sdk/libcrypt...
