### ISSUE TITLE
The libcurl does not support deletion or algorithm sequence adjustment.

### ISSUE THREAD

**Issue by zzfzyz** [curl/curl#12628]
### I did this

The libcurl does not support deletion or algorithm sequence adjustment.

### I expected the following

It is hoped that libcurl can support deletion and algorithm sequence adjustment.

### curl/libcurl version

curl 8.2.0

### operating system

Linux

**Comment by dfandrich** [comment]
You'll have to be more specific. curl (as well as libcurl) supports deletion of
remote resources via mechanisms such as "-X DELETE" and "-Q rm foo". Or are you
talking about deleting cryptographic algorithms from the set offered to the
remote server?  That's supported through options like "--curves" and
"--ciphers". Or do you mean something completely different?
