### ISSUE TITLE
Test 1013 fails due to differences in protocol list

### ISSUE THREAD

**Issue by jay** [curl/curl#1262]
### I did this
Built a curl tool debug build using mingw32 msys:
~~~
make distclean
./buildconf
CFLAGS=-DNGHTTP2_STATICLIB \
CPPFLAGS=-DMEMDEBUG_LOG_SYNC \
LDFLAGS=-static \
PKG_CONFIG="pkg-config --static" \
./configure \
  --disable-shared \
  --disable-threaded-resolver \
  --enable-static \
  --enable-debug \
  --enable-sspi \
  --prefix=c:/mingw/msys/1.0/local \
  --with-ssl=c:/mingw/msys/1.0/local \
  --with-nghttp2=c:/mingw/msys/1.0/local \
  >config.out 2>&1
make V=1 curl_LDFLAGS=-all-static >make.out 2>&1
~~~
Of note is `--enable-sspi`.

### Test 1013 failed
~~~
test 1013...[Compare curl --version with curl-config --protocols]
Mismatch in protocols lists:
curl:        dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
curl-config: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
 postcheck FAILED
~~~
Of note is that `smb` and `smbs` are not listed protocols in `curl --version`.

### Analysis
configure.ac uses [this](https://github.com/curl/curl/blob/curl-7_52_1/configure.ac#L3769-L3778) logic to decide whether to put smb in the `curl-config --protocols` protocol list:
~~~shell
if test "x$CURL_DISABLE_SMB" != "x1" \
    -a "x$CURL_DISABLE_CRYPTO_AUTH" != "x1" \
    -a \( "x$OPENSSL_ENABLED" = "x1" -o "x$USE_WINDOWS_SSPI" = "x1" \
      -o "x$GNUTLS_ENABLED" = "x1" -o "x$MBEDTLS_ENABLED" = "x1" \
      -o "x$NSS_ENABLED" = "x1" -o "x$DARWINSSL_ENABLED" = "x1" \); then
  SUPPORT_PROTOCOLS="$SUPPORT_PROTOCOLS SMB"
  if test "x$SSL_ENABLED" = "x1"; then
    SUPPORT_PROTOCOLS="$SUPPORT_PROTOCOLS SMBS"
  fi
fi
~~~
Of note is OPENSSL_ENABLED and USE_WINDOWS_SSPI variables are true so SMB and SMBS are in the `curl-config --protocols` protocol list.

lib/version.c uses [this](https://github.com/curl/curl/blob/curl-7_52_1/lib/version.c#L241-L248) logic to decide whether to put smb in the `curl --version` protocol list:
~~~c
#if !defined(CURL_DISABLE_SMB) && defined(USE_NTLM) && \
   (CURL_SIZEOF_CURL_OFF_T > 4) && \
   (!defined(USE_WINDOWS_SSPI) || defined(USE_WIN32_CRYPTO))
  "smb",
#  ifdef USE_SSL
  "smbs",
#  endif
#endif
~~~
Of note is `(!defined(USE_WINDOWS_SSPI) || defined(USE_WIN32_CRYPTO))` which is also the logic lib/smb.c is guaraded with. For this `curl --version` case, which does not include smb, I've got `USE_WINDOWS_SSPI` defined in my lib/curl_config.h but not `USE_WIN32_CRYPTO`, and as a result means smb won't be enabled.

`USE_WIN32_CRYPTO` is only defined in lib/config-win32.h (which is not used here since I'm using autotools generated config) and with [this](https://github.com/curl/curl/blob/curl-7_52_1/lib/config-win32.h#L705-L708) logic:
~~~c
#if !defined(USE_OPENSSL) && !defined(USE_NSS)
#define USE_WIN32_CRYPTO
#endif
~~~

I'm not sure why only config-win32 defines `USE_WIN32_CRYPTO` and only under those circumstances, and what is correct here.

### curl/libcurl version

master e1187c4 2017-02-11
~~~
curl 7.53.0-DEV (i686-pc-mingw32) libcurl/7.53.0-DEV OpenSSL/1.0.2k zlib/1.2.11 nghttp2/1.19.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: Debug TrackMemory Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy
~~~

### operating system
Windows 7 x64 Enterprise

**Comment by bagder** [comment]
> I'm not sure why only config-win32 defines USE_WIN32_CRYPTO and only under those circumstances, and what is correct here.

It seems wrong on at least three ways:

1. We want to be able to explicitly select using wincrypto, not just implicitly like this by not selecting openssl or NSS.

2. Win builds could also use other crypto backends (like wolfssl).

3. we want to enable wincrypto in configure builds too

**Comment by MarcelRaad** [comment]
I've been bitten by this issue often enough to finally start working on it. I think the root cause is that the definition of `USE_NTLM` is not correct as it's not enough to actually build with NTLM support.
