### ISSUE TITLE
Support to IDNs 

### ISSUE THREAD

**Issue by paulrm** [curl/curl#12644]
### I did this

Calling 

`curl -v "https://ñ.lat" `

and I got the error:

`curl: (60) SSL: no alternative certificate subject name matches target host name 'ñ.lat'`

### I expected the following

consider the IDNs and translate as:

`curl -v  https://xn--ida.lat/`

### curl/libcurl version

```
curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
```

### operating system

`Darwin Marsala.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64`

**Comment by bagder** [comment]
curl has supported IDN since 2004. But you need to run a curl command that has the feature enabled, which you seem to not do. The `Features` list includes `IDN` then.

I guess you use the curl version shipped by Apple so then that's their decision to not include this.
