### ISSUE TITLE
PHP 7.1.2 compilation and libcurl error

### ISSUE THREAD

**Issue by Krazitchek** [curl/curl#1266]
PHP 7.1.2 is here, i tried to compile it with curl extension as usually but this time ./configure fail with these error:
    checking for cURL in default path... not found
    configure: error: Please reinstall the libcurl distribution - easy.h should be in /include/curl/

I'm on Debian Stretch (9).

I found libcurl4-openssl-dev is installed in /usr/include/x86_64-linux-gnu/curlwhen./configure expect it in/include/curl/`

libcurl4-openssl-dev on debian Jessie install curl in /usr/include/curl/ when Stretch install curl in /usr/include/x86_64-linux-gnu/curl.

With the last PHP version I compiled (7.1.1), I had no problems, but this time it failed.

To compile:

./buildconf --force && ./configure --prefix=/usr/local/php --with-config-file-path=/etc/php/lib --enable-bcmath --with-bz2 --with-zlib --enable-zip --enable-calendar --enable-exif --enable-ftp --with-gettext --with-gd --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xpm-dir --enable-mbstring --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-openssl --enable-intl --enable-soap --with-readline --with-curl --with-mcrypt --with-xsl --enable-sockets

curl and libcurl4-openssl-dev packages are installed.

I tried with --with-curl=/usr/include/x86_64-linux-gnu/curl/ but it doesn't work.

I don't know how to solve this, can someone knows please ?

**Comment by onetimeuser12** [comment]
command ->"whereis curl" will probably give you the viable curl location(s)?

**Comment by jay** [comment]
> I tried with --with-curl=/usr/include/x86_64-linux-gnu/curl/ but it doesn't work.

This is not a curl issue. Also that directory ending in /curl/ sounds wrong, where did you find the library? Isn't it usually in /usr/lib/x86_64-linux-gnu? I suggest you subscribe to a [PHP mailing list](http://php.net/mailing-lists.php) and then ask your question there. You may have to use CPPFLAGS and LDFLAGS.

**Comment by Krazitchek** [comment]
I'm on Debian 9 (testing), curl and libcurl were installed with apt-get install curl libcurl4-openssl-dev... nothing special here, until PHP 7.1.2 i didn't had this problem to compile PHP.

**Comment by Krazitchek** [comment]
I use locate easy.h to find where are files compilation tell me about error. And path is /usr/include/x86_64-linux-gnu/curl

**Comment by bagder** [comment]
@Krazitchek we hear you, but this is not the PHP project and we don't work with building PHP. The curl extension in PHP is *also* a part of the PHP project so you should ask the PHP developers for help on this. We're also not responsible for how Debian puts their packages together so even if you'd find a problem with libcurl in Debian, you should start out taking that issue to Debian.

If you can point to an actual libcurl problem then this is the exact right place and we would *love* to work on fixing it. But nothing that's been said so far here identifies any problem with something the curl project has delivered.
