### ISSUE TITLE
Unable to build Curl with QUIC support

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#12674]
### I did this

i followed below steps to build curl
https://github.com/curl/curl/blob/master/docs/HTTP3.md

i am getting below error
```
root@ubuntu:/src/curl# LDFLAGS="-Wl,-rpath,/var/local/openssl/lib" ./configure --with-openssl=/var/local/openssl --with-nghttp3=/var/local/nghttp3 --with-ngtcp2=/var/local/ngtcp2 --with-nghttp2=/var/local/nghttp2
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... (assumed) yes
checking whether to enable strict compiler warnings... no
checking for SRP support in OpenSSL... yes
configure: built with one SSL backend
checking default CA cert bundle/path... configure: want unset ca /etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs (capath)
checking whether to use builtin CA store of SSL library... no
checking for library containing psl_builtin... no
configure: error: libpsl was not found
root@ubuntu:/src/curl#
```

### I expected the following

i expect this to work

### curl/libcurl version

https://github.com/curl/curl
Master branch

### operating system

root@ubuntu:/src/curl# uname -a
Linux ubuntu 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/src/curl#

**Comment by Karthikdasari0423** [comment]
```
configure: WARNING: Cannot find libraries for LDAP support: LDAP disabled
configure: error: libpsl was not found
```
am i missing anything here?

**Comment by dfandrich** [comment]
> am i missing anything here?

Yes, libpsl.  It's now required by default.

**Comment by ia** [comment]
Hello.

> ```
> configure: WARNING: Cannot find libraries for LDAP support: LDAP disabled
> configure: error: libpsl was not found
> ```
> 
> am i missing anything here?

Since it looks you use `Ubuntu` to build `curl`, it _seems_ you need to install `libpsl-dev` package before running `./configure`, i.e.:
```
root@ubuntu:/src/curl# apt  install  libpsl-dev
```

And if you need `LDAP` support - install `libldap2-dev` as well (and/or `libldap-dev` depending on your `Ubuntu` version):
```
root@ubuntu:/src/curl# apt  install  libldap2-dev
```

Hope it will help.

**Comment by bagder** [comment]
This new behavior explained: https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/

**Comment by Karthikdasari0423** [comment]
Thank you @dfandrich @ia @bagder
