### ISSUE TITLE
curl_multi_fdset does not accept NULL sets

### ISSUE THREAD

**Issue by sfan5** [curl/curl#12691]
### I did this

```cpp
	int max_fd;
	mres = curl_multi_fdset(m_multi, nullptr, nullptr, nullptr, &max_fd);
```

The context here is that I am attempting to emulate `curl_multi_poll` on libcurl older than 7.66.0.
The idea I had is:
* check if libcurl has any fds it waits for
* if yes, just call `curl_multi_wait`
* if no, sleep for the wanted timeout

This actually means reporting this bug is pointless since the fallback code I am writing can never make use of a fix. Maybe you still want to update the docs :shrug: 

### I expected the following

No crash.

The [documentation for curl_multi_fdset](https://curl.se/libcurl/c/curl_multi_fdset.html) says (emphasis mine):

> **If the read_fd_set argument is not a null pointer**, it points to an object of type fd_set that on returns specifies the file descriptors to be checked for being ready to read.
> **If the write_fd_set argument is not a null pointer**, it points to an object of type fd_set that on return specifies the file descriptors to be checked for being ready to write.
> **If the exc_fd_set argument is not a null pointer**, it points to an object of type fd_set that on return specifies the file descriptors to be checked for error conditions pending. 

Checking the code reveals no attempt is made to check the sets against null:
https://github.com/curl/curl/blob/d7b6ce64ce0ad787ad2ed3ee05c94938a6b4f551/lib/multi.c#L1178-L1189
As far as I know `FD_SET(..., NULL)` is not specified to be safe either.

### curl/libcurl version

curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.58.0

### operating system

Arch Linux x86_64

**Comment by bagder** [comment]
It seems it has not supported that since at least 2006 so, yes, let's fix the docs.
