### ISSUE TITLE
Unsupported protocol for HttpVersion SetOpt

### ISSUE THREAD

**Issue by bethebest0622** [curl/curl#12729]
### I did this

`curl_easy_setopt(r, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);` error was `Unsupported protocol`

this setting is ok to run, when i used `yum install libcurl-devel`, which is version 7.82.0

after i install 8.5.0 by source code `make install`, it gives out the error

### I expected the following

use http2.0

### curl/libcurl version

8.5.0

### operating system

centos 8 stream

**Comment by icing** [comment]
What does `curl -V` on the curl that you using say?

**Comment by icing** [comment]
I think it says more than that. For example, my curl says:

```
curl 8.6.0-DEV (x86_64-apple-darwin23.2.0) libcurl/8.6.0-DEV OpenSSL/3.2.0 zlib/1.2.12 brotli/1.1.0 zstd/1.5.5 c-ares/1.21.0 libidn2/2.3.4 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.58.0 OpenSSL/3.2.0 nghttp3/1.1.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli Debug GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd
```

And you notice that `HTTP2` is listed among the features. Is that listed in your curl too?
