### ISSUE TITLE
Issue with 'curl --help all'

### ISSUE THREAD

**Issue by gvanem** [curl/curl#12723]
### I did this

I note that building with `-DUSE_WATT32`, the option `--wdebug` is not in the list of `--help all`.

I tried tinkering with adding this `docs/cmdline-opts/wdebug.d` file:
<details>
  <summary>wdebug.d</summary>

```
c: Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
SPDX-License-Identifier: curl
Long: wdebug
Help: Enable debug-trace for Watt-32
Category: misc verbose
Example: --wdebug
Added: 8.6.0
See-also: verbose
Multi: boolean
---
This option tells curl to write the Watt-32 trace to
the file specied in '$(WATT_ROOT)7wattcp.cfg' and the
'debug.file = file' setting.
```
</details>

So now `curl --help all` correctly prints:
```c
 ...
 -V, --version     Show version number and quit
     --wdebug      Enable debug-trace for Watt-32
 -w, --write-out <format> Use output FORMAT after completion
     --xattr       Store metadata in extended file attributes
```
And `curl --help verbose` prints:
```
 ...
 -v, --verbose     Make the operation more talkative
     --wdebug      Enable debug-trace for Watt-32
```

But how to print this only when `USE_WATT32` is defined? Add a new `Category: watt_32`?

Also BTW, the `docs/cmdline-opts/gen.pl` script is rather POSIX centric. It assumes the shell will expand all `*.d` files.
How about support for a response-file (`perl gen.pl listhelp @d_files`) ? Or have `perl gen.pl "*.d"` glob and expand the files itself?

### I expected the following

`curl --help all` to also print `--wdebug      Enable debug-trace for Watt-32`

### curl/libcurl version

```
WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.6.0-DEV (x86_64-pc-win32) libcurl/8.6.0-DEV zlib/1.3 brotli/1.1.0 zstd/1.5.5 WinIDN
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap ipfs ipns ldap ldaps mqtt pop3 rtsp smb smtp telnet tftp ws
Features: alt-svc brotli Debug HSTS IDN IPv6 Largefile libz MultiSSL NTLM threadsafe TrackMemory UnixSockets zstd
```

### operating system

Win-10.

**Comment by bagder** [comment]
> But how to print this only when USE_WATT32 is defined? Add a new Category: watt_32?

We don't have infra for that. The tool's options are supposed to be there independent of platform. The `--wdebug` is the exception and kind of a hack. I'm not against making something for this, but then I think we should consider making it a more generic option that can work for more platforms.

> Also BTW, the docs/cmdline-opts/gen.pl script is rather POSIX centric. It assumes the shell will expand all *.d files.

It actually does not assume that as you can see in `Makefile.am`. It works with all the files provided on the command line just as well. This approach has worked quite well for many years already.

**Comment by gvanem** [comment]
> ... I think we should consider making it a more generic option that can work for more platforms.

Like which? Perhaps let `-vv` replace `--wdebug` or something?

> It actually does not assume that as you can see in Makefile.am.

In `docs/cmdline-opts/Makefile.am`, I see `$(PERL) ./genl.pl mainpage $(DPAGES)`. And
`$(PERL) ./genl.pl listhelp *.d`. You mean it could be `$(PERL) ./genl.pl listhelp $(DPAGES)`?

**Comment by bagder** [comment]
> Like which? Perhaps let -vv replace --wdebug or something?

Can you explain what `--wdebug` is for and how you use it?

> You mean it could be $(PERL) ./genl.pl listhelp $(DPAGES)?

Correct.

**Comment by gvanem** [comment]
> Can you explain what --wdebug is for and how you use it?

It simply calls [`dbug_init()`](https://github.com/gvanem/Watt-32/blob/master/src/pcdbug.c#L2878) for debugging prior to creating a `socket()` etc. 
So with a `curl.exe --wdebug <what-ever>`, I get:
 * all network details in file specified  by `debug.file = f:\wattcp.dbg` in the Watt-32 config-file. And
 * all BSD-socket details in file specified by `sk_debug.device = f:\wattcp.sk` in the same Watt-32 config-file.

All this dumping takes some time. Hence `--wdebug` is to resolve problems mostly.

So testing this Watt-32 version (clang-cl built):
```
F:\MinGW32\src\inet\curl\src> curl.exe -4O --wdebug http://www.watt-32.net/watt-doc/watt-32.chm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.2M  100 21.2M    0     0   193k      0  0:01:52  0:01:52 --:--:--  161k
```

leaves me with `f:\wattcp.*` totalling 130 MByte of details.

But perhaps a `$CURL_WDEBUG` variable is better?

**Comment by bagder** [comment]
> But perhaps a `$CURL_WDEBUG` variable is better?

That's certainly more in line with how we do it for other debug-only special things, but it suffers from the same problem: it isn't visible to a user.

**Comment by bagder** [comment]
I don't consider this a bug. We don't support debug-specific options in the `--help` output.
