### ISSUE TITLE
[rustls] Make curl compatible with rustls-ffi 0.12.0

### ISSUE THREAD

**Issue by der-eismann** [curl/curl#12737]
### I did this

I tried to build curl with rustls-ffi 0.12.0, however it failed with the following errors:
```
vtls/rustls.c:418:13: error: call to undeclared function 'rustls_root_cert_store_new'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    roots = rustls_root_cert_store_new();
            ^
vtls/rustls.c:418:13: note: did you mean 'rustls_root_cert_store_free'?
/usr/include/rustls.h:1018:6: note: 'rustls_root_cert_store_free' declared here
void rustls_root_cert_store_free(const struct rustls_root_cert_store *store);
     ^
vtls/rustls.c:418:11: error: incompatible integer to pointer conversion assigning to 'struct rustls_root_cert_store *' from 'int' [-Wint-conversion]
    roots = rustls_root_cert_store_new();
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vtls/rustls.c:421:14: error: call to undeclared function 'rustls_root_cert_store_add_pem'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    result = rustls_root_cert_store_add_pem(roots, ca_info_blob->data,
             ^
vtls/rustls.c:431:14: error: call to undeclared function 'rustls_client_config_builder_use_roots'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    result = rustls_client_config_builder_use_roots(config_builder, roots);
             ^
vtls/rustls.c:441:14: error: call to undeclared function 'rustls_client_config_builder_load_roots_from_file'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    result = rustls_client_config_builder_load_roots_from_file(
             ^
vtls/rustls.c:441:14: note: did you mean 'rustls_root_cert_store_builder_load_roots_from_file'?
/usr/include/rustls.h:991:15: note: 'rustls_root_cert_store_builder_load_roots_from_file' declared here
rustls_result rustls_root_cert_store_builder_load_roots_from_file(struct rustls_root_cert_store_builder *builder,
              ^
5 errors generated.
make[2]: *** [Makefile:3193: vtls/libcurl_la-rustls.lo] Error 1
```

First I reported it [in their project](https://github.com/rustls/rustls-ffi/issues/384), but looks like it needs to be addressed in curl code. Also I just saw, that [docs/RUSTLS.md](https://github.com/curl/curl/blob/master/docs/RUSTLS.md) even speaks of 0.10.0, so I guess CI & docs need an update as well.

### I expected the following

curl should build with the latest rustls-ffi version.

### curl/libcurl version

curl 8.5.0

### operating system

Fedora 39

**Comment by bagder** [comment]
> it needs to be addressed in curl code

Sure, but it needs someone to research the rust-ffi API what code/calls to change and what to replace it *with*.

**Comment by der-eismann** [comment]
I'm sure some volunteer or rustls affiliated dev will offer their help, didn't expect you to do it. It was just recommended to open this issue to keep track of it :slightly_smiling_face:

**Comment by cpu** [comment]
We've done our best to document the changes in the upstream [CHANGELOG](https://github.com/rustls/rustls-ffi/blob/main/CHANGELOG.md). The 0.10 to 0.11 update is fairly minor. I think the 0.11 to 0.12 update is where the majority of the interesting changes happened.

I can't commit to doing the curl update work at this time but I would be happy to try and help support in code review or answering questions.

**Comment by bagder** [comment]
Unless someone volunteers for this within another week or so, I will add this as a TODO item and close this issue.
