### ISSUE TITLE
What will happen if curl_multi_perform upload data calling curl_multi_remove_handle?

### ISSUE THREAD

**Issue by mars9180** [curl/curl#1273]
I use multi interfaces of  libcurl communication with server implementation http2 ,I try to connect multiple streams of uploads and downloads to realize a communication experiment,I have an question.I add handler of easy to multi calls curl_multi_perform to upload the data,if I removed easy handler when I use curl_multi_remove_handle during some reason,What state is libcurl at this time should be? The stream closed http2?
I use libcurl version is 7.52.1

**Comment by bagder** [comment]
Please ask questions on the curl-library mailing list where you'll reach a much larger audience of people that can help out, this tracker is for "issues".

Yes, removing a handle should stop the stream appropriately.
