### ISSUE TITLE
Intermittent SSL Cert error in "Microsoft SQL Server Management Studio" while using the driver in combination with a linked server

### ISSUE THREAD

**Issue by AparnaSuriaraj18** [curl/curl#12744]
### I did this

In "Microsoft SQL Server Management Studio" while running the query using the driver in 
combination with a MS SQL Server linked server.

### I expected the following

in "Microsoft SQL Server Management Studio" while running the query using the driver in 
combination with a MS SQL Server linked server.
The error returned is:
OLE DB provider "STREAM" for linked server "(null)" returned message "[Simba][DriverSupport] (1210) Unable to load Client certificate or Client private key set via the connection attributes ClientCert or ClientPrivateKey. Please ensure the file exists, has read permission, and has the correct PEM format.".
We get the error from the curl side wherein the  function curl_easy_perform() returns the curl error code "CURLE_SSL_CERTPROBLEM (58)" when this error happens we could see that the correct 
cert file path is getting picked but issue might be occurring when the contents of the cert file is read. There are multiple SSL handshakes that takes place and in the initial handshake it is able to read the 
ssl file but it fails later with the error 
OpenSSL error error:80000005:system library::Input/output error, (no key found, wrong pass phrase, or wrong file format?) 
from the openssl.c file present in the curl thirdparty library.
This is an intermittent issue, which is observed only in "Microsoft SQL Server Management Studio" but 
the ODBC driver works fine outside of a linked server - e.g. the same queries are fine if run through SSIS/PowerShell,odbctest tool etc.
 
Any pointer that can help us in understanding this inconsistent behavior and resolving this intermittent error that we are getting.
 
Thanks in advance!

### curl/libcurl version

8.1.2

### operating system

windows

**Comment by bagder** [comment]
- Try building curl with another TLS library to see if the problem changes or brings more light to the issue
- Try upgrading curl and OpenSSL to use the latest versions
- Try reproducing the problem with openssl's tool directly without involving curl, as this seems to be a TLS related problem
- Ask the OpenSSL team what the error means and what the likely reasons for triggering that might be and then take it from there

**Comment by bagder** [comment]
No response. Nothing for us to act on.
