### ISSUE TITLE
idn2 tests 1035, 2046, 2047 fail

### ISSUE THREAD

**Issue by ismail** [curl/curl#1277]
Building on openSUSE Linux x86-64 with:

./configure --enable-ipv6 \
                  --with-ssl \
                  --with-ca-fallback \
                  --without-ca-path \
                  --without-ca-bundle \
                  --with-gssapi=/usr/lib/mit \
                  --with-libidn2 \
                  --with-libssh2 \
                  --enable-hidden-symbols \
                  --disable-static \
                  --enable-threaded-resolver \
                  --with-libmetalink

System has libidn2 01.6, the following tests fail:

test 1035...[HTTP over proxy with too long IDN host name]

 1035: protocol FAILED:
--- log/check-expected	2017-02-22 10:32:08.792857714 +0000
+++ log/check-generated	2017-02-22 10:32:08.792857714 +0000
@@ -1,5 +1,5 @@
-GET http://too-long-IDN-name-c�rl-r�les-la-la-la-dee-da-flooby-nooby.local/page/1035 HTTP/1.1[CR][LF]
-Host: too-long-IDN-name-c�rl-r�les-la-la-la-dee-da-flooby-nooby.local[CR][LF]
+GET http://too-long-idn-name-crl-rles-la-la-la-dee-da-flooby-nooby.local/page/1035 HTTP/1.1[CR][LF]
+Host: too-long-idn-name-crl-rles-la-la-la-dee-da-flooby-nooby.local[CR][LF]
 Accept: */*[CR][LF]
 Proxy-Connection: Keep-Alive[CR][LF]
 [CR][LF]

test 2046...[Connection re-use with IDN host name]

 2046: stdout FAILED:
--- log/check-expected	2017-02-22 10:33:36.165822947 +0000
+++ log/check-generated	2017-02-22 10:33:36.165822947 +0000
@@ -1,18 +1,6 @@
-HTTP/1.1 302 OK swsbounce[LF]
-Date: Thu, 09 Nov 2010 14:49:00 GMT[LF]
-Content-Length: 9[LF]
-Content-Type: text/plain[LF]
-Location: ./20460001[LF]
+0[LF]
+0[LF]
+0[LF]
+http://åäö.se:8990/2046[LF]
 [LF]
-HTTP/1.1 200 OK[LF]
-Date: Thu, 09 Nov 2010 14:49:00 GMT[LF]
-Content-Length: 3[LF]
-Content-Type: text/plain; charset=us-ascii[LF]
-[LF]
-OK[LF]
-1[LF]
-1[LF]
-3[LF]
-http://åäö.se:8990/20460001[LF]
-text/plain; charset=us-ascii[LF]
-200[LF]
+000[LF]

 test 2047...[Connection re-use with IDN host name over HTTP proxy]

 2047: stdout FAILED:
--- log/check-expected	2017-02-22 10:33:36.221823533 +0000
+++ log/check-generated	2017-02-22 10:33:36.221823533 +0000
@@ -13,6 +13,6 @@
 1[LF]
 1[LF]
 3[LF]
 -http://xn--4cab6c.se/20470001[LF]
 +http://.se/20470001[LF]
 text/plain; charset=us-ascii[LF]
 200[LF]

**Comment by bagder** [comment]
They still run fine for me with libidn2/0.16. What's your `$LANG` set to? I suppose this is `idn2_lookup_ul()` not handling the input the way we'd like. We should make the test script set the correct environment...

**Comment by ismail** [comment]
LANG is set to POSIX.
