### ISSUE TITLE
Whitespace-only Host header value shouldn't send Host header

### ISSUE THREAD

**Issue by verhovsky** [curl/curl#12782]
### I did this

```sh
curl -v -H 'Host:' -H 'Accept:' -H 'User-Agent:' example.com
curl -v -H 'Host: ' -H 'Accept: ' -H 'User-Agent: ' example.com
```

### I expected the following

Both commands to send a request with no headers

```
> GET / HTTP/1.1
> 

```

Instead, the second command sends a Host header with just one space after the `:`:

```
> GET / HTTP/1.1
> Host: 
> 

```

### curl/libcurl version

curl 8.5.0 (aarch64-apple-darwin23.0.0) libcurl/8.5.0 (SecureTransport) OpenSSL/3.2.0 zlib/1.2.12 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.58.0 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-12-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Darwin [...] 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64 arm Darwin

**Comment by dfandrich** [comment]
It seems that Host: is special in this regard. All the other headers I tried
are removed when there's a space after the colon, but Host: is not removed.
I also discovered another difference: other headers are removed regardless of
the case (e.g. both -H accept: and -H Accept: remove the Accept: header) but -H
host: does not remove the Host: header (-H Host: (no space) does, however).

**Comment by bagder** [comment]
The docs for -H / --header says pretty clearly:

> Remove an internal header by giving a replacement **without content** on the right side of the colon, as in: -H "Host:".

I see no wording indicating that it considers one or more spaces after the colon to not be content.

So, the **shouldn't send** part can be argued. Is there really a compelling reason why we should change this now after having worked like this for 25 years give or take?

**Comment by verhovsky** [comment]
The issue is here

https://github.com/curl/curl/blob/8edcfedc1a144f438bd1cdf814a0016cbe678aaf/lib/http.c#L2266-L2270

@bagder it's incosistent with the other headers. Either whitespace should cause headers to all send whitespace

```
$ curl -v -H 'Host: ' -H 'Accept: ' -H 'User-Agent: ' example.com
> GET / HTTP/1.1
> Host: 
> Accept: 
> User-Agent: 
> 

[...]
```

or none of them should

```
$ curl -v -H 'Host: ' -H 'Accept: ' -H 'User-Agent: ' example.com
> GET / HTTP/1.1
> 

[...]
```

> Is there really a compelling reason why we should change this

It would save me a few lines of code to not have to replicate this inconsistency.

**Comment by verhovsky** [comment]
Definitely the case-sensitive `strcmp` that @dfandrich pointed out would be good to fix.

**Comment by bagder** [comment]
> At least the case-sensitive strcmp that @dfandrich pointed out would be good to fix. i.e.

Right, but that is totally unrelated to this issue...

**Comment by verhovsky** [comment]
> after having worked like this for 25 years give or take

I think it used to work this way until this commit 9 years ago

https://github.com/curl/curl/commit/a5d994941c2b19a3c63402caa064c9683647de05

**Comment by bagder** [comment]
I see nothing about changed whitespace handling there?

**Comment by bagder** [comment]
still: the *documented* way to do this still works, the same way.

**Comment by jay** [comment]
This has come up before and if I remember right we purposely didn't document what would happen with just whitespace after the colon or semicolon since it could vary.

**Comment by bagder** [comment]
I don't think curl needs to have a consistent behavior for undocumented features/side effects.
