### ISSUE TITLE
Support `OPTIONS *` requests

### ISSUE THREAD

**Issue by BigBlueHat** [curl/curl#1280]
### I did this
```
curl -v -X OPTIONS "*" -H 'Host: www.w3.org' -H 'Upgrade: TLS/1.0' -H 'Connection: Upgrade'
```
while exploring [RFC 2817](https://tools.ietf.org/html/rfc2817#section-3.2). It resulted in a request being sent, but `*` got rewritten to a request for `*/`.

### I expected the following

The standard `OPTIONS *` to be sent....but then I found:
http://stackoverflow.com/a/36933053/507169

This is known as the `asterisk-form` in [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.3.4).

### curl/libcurl version

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

### operating system

Linux Subsystem (Ubuntu) on Windows 10

---
Thanks for considering this!

**Comment by bagder** [comment]
The use of the asterisk like that on the command line isn't expected to work and it will never work like that. It will instead work as a wildcard by the shell and then most likely get treated as a separate URL.

curl doesn't have the ability to send an "OPTIONS *" request as it will always send at least a slash. We've discussed making it possible to do so in the past, but nobody has yet pulled that through or provided the necessary code changes.

**Comment by BigBlueHat** [comment]
Thanks, @bagder. I should've focused on the quoted example. It seems like it would be a simple patch...but I'm sadly am not setup to code and test C...

I will change my request, though, to focus on the `"*"` usage only.

Here's the pertinent bit from the latest HTTP spec: https://tools.ietf.org/html/rfc7230#section-5.3.4

Thanks!

**Comment by bagder** [comment]
Thanks, now properly added in the TODO referring back to this issue.
