### ISSUE TITLE
infinitely allocating memory with curl while `curl`ing a url-kind filesystem path

### ISSUE THREAD

**Issue by TruncatedDinoSour** [curl/curl#12813]
### I did this

i ran `curl .` and curl decided to hog up my ram and give this output in `strace` :

```
mmap(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa0727fd000
brk(0x564daedfb000)                     = 0x564daedfb000
brk(0x564daee1c000)                     = 0x564daee1c000
brk(0x564daee3d000)                     = 0x564daee3d000
brk(0x564daee5e000)                     = 0x564daee5e000
brk(0x564daee7f000)                     = 0x564daee7f000
brk(0x564daeea0000)                     = 0x564daeea0000
brk(0x564daeec1000)                     = 0x564daeec1000
brk(0x564daeee2000)                     = 0x564daeee2000
brk(0x564daef03000)                     = 0x564daef03000
brk(0x564daef24000)                     = 0x564daef24000
brk(0x564daef45000)                     = 0x564daef45000
brk(0x564daef66000)                     = 0x564daef66000
brk(0x564daef87000)                     = 0x564daef87000
brk(0x564daefa8000)                     = 0x564daefa8000
brk(0x564daefc9000)                     = 0x564daefc9000
brk(0x564daefea000)                     = 0x564daefea000
brk(0x564daf00b000)                     = 0x564daf00b000
brk(0x564daf02c000)                     = 0x564daf02c000
brk(0x564daf04d000)                     = 0x564daf04d000
brk(0x564daf06e000)                     = 0x564daf06e000
brk(0x564daf08f000)                     = 0x564daf08f000
...
```

the program infinitely hangs

### I expected the following

on an older version of curl ( 7.88.1 on debian for example ) it exits with an error

```
ari@us:~$ curl .
curl: (6) Could not resolve host: .
```

which is expected

### curl/libcurl version

buggy version : `curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.12 zlib/1.3 c-ares/1.25.0 nghttp2/1.57.0
Release-Date: 2023-12-06
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets`

working version : `curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-02-20, security patched: 7.88.1-10+deb12u5
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd`

### operating system

gentoo linux with the following use flags : 

```
[ebuild   R   ] net-misc/curl-8.5.0  USE="adns alt-svc ftp hsts http2 imap openssl pop3 progress-meter smtp ssl tftp -brotli -gnutls -gopher -idn -kerberos -ldap -mbedtls (-nghttp3) -rtmp (-rustls) -samba -ssh (-sslv3) -static-libs -telnet -test -verify-sig -websockets -zstd" CURL_SSL="openssl -gnutls -mbedtls (-rustls)"
```

`7.88.1` working curl server on debian 12

**Comment by TruncatedDinoSour** [comment]
a person who has a versuon of same curl just with `PSL` + newer newer nghttp2 and openssl : 

```
curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.1.4 zlib/1.3 c-ares/1.25.0 libpsl/0.21.5 (+libidn2/2.3.4) nghttp2/1.58.0
Release-Date: 2023-12-06
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets
```

just  has it not resolve : 

![image](https://github.com/curl/curl/assets/71613062/dc22462a-0e9d-4c05-bbb2-bb0fbc992a0e)

**Comment by dfandrich** [comment]
I can't reproduce this using both curl and c-ares from current git. They all
return "Could not resolve host: ." and don't hang. What does your
/etc/resolv.conf file say?  Can you run the hanging curl under a debugger and
find out where it hangs?

**Comment by bagder** [comment]
I can't reproduce either, even used curl with the same c-ares version.

Maybe show us what `curl -v .` outputs?

**Comment by TruncatedDinoSour** [comment]
> I can't reproduce either, even used curl with the same c-ares version.
> 
> Maybe show us what `curl -v .` outputs?

i cant, i have tried, even now i tried and it just hangs, thats exactly why i only provided the strace output

**Comment by TruncatedDinoSour** [comment]
> I can't reproduce this using both curl and c-ares from current git. They all return "Could not resolve host: ." and don't hang. What does your /etc/resolv.conf file say? Can you run the hanging curl under a debugger and find out where it hangs?

```
# Generated by dhcpcd from wlp1s0.dhcp
# /etc/resolv.conf.head can replace this line
domain lan
nameserver 192.168.1.1
# /etc/resolv.conf.tail can replace this line
```

when compiling did you try the features and protocols ?

```
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
```

**Comment by TruncatedDinoSour** [comment]
heres my curl binary ( gzipped ), feel free to play around with it in a vm or something ? maybe its going to be at least some help

[curl.tar.gz](https://github.com/curl/curl/files/14074005/curl.tar.gz)

**Comment by bagder** [comment]
~~~
$ ./curl .
curl: (6) Could not resolve host: .
~~~

But that's just the tool you provided, not the library and whatever happens in your case is most likely the actions of libcurl, c-ares or another of the libraries the curl tool uses.

**Comment by TruncatedDinoSour** [comment]
> ```
> $ ./curl .
> curl: (6) Could not resolve host: .
> ```
> 
> But that's just the tool you provided, not the library and whatever happens in your case is most likely the actions of libcurl, c-ares or another of the libraries the curl tool uses.

true, but i thought maybe its going to be at least some help

**Comment by dfandrich** [comment]
I didn't try matching all the features and protocols, because this error occurs
really early on, during the name resolution stage so they (mostly) shouldn't
matter. I matched the resolver options AsynchDNS and c-ares but not the
specific versions (Daniel said he did match versions). Using gdb or strace to
find where it's hanging should give a pretty good clue as to what's happening.
How long did you wait before extrapolating to an infinite hang?

**Comment by TruncatedDinoSour** [comment]
![image](https://github.com/curl/curl/assets/71613062/4d1e06e9-325e-4e73-90ad-62717813457d)

now it has the desired behaviour but : 

- still allocates quite a bit of memory ( in this test case over 1 gb was allocated )
- takes a long while to finish ( i think this was like at least 7-8 minutes )
- this shouldnt happen i think

i think rebooting it fixed it in some way, though ive also rebuilt openssl as i needed to do so for my telegram client, i am confused

**Comment by TruncatedDinoSour** [comment]
> I didn't try matching all the features and protocols, because this error occurs really early on, during the name resolution stage so they (mostly) shouldn't matter. I matched the resolver options AsynchDNS and c-ares but not the specific versions (Daniel said he did match versions). Using gdb or strace to find where it's hanging should give a pretty good clue as to what's happening. How long did you wait before extrapolating to an infinite hang?

right, let me maybe try compiling curl from source

**Comment by TruncatedDinoSour** [comment]
`./configure --with-ssl --without-libpsl` still does the same
it hangs and allocates a lot of memory

**Comment by TruncatedDinoSour** [comment]
i have asked a few people around to try to produce it, nobody can, not even my own server or phone or anything, i think i just have messed something up as this is like a 2 day gentoo install, i'll close this as its not reproducible and it is likely that i have just messed up my configuration in some way

**Comment by dfandrich** [comment]
That strace snippet didn't show much, but it seemed to show issues with
contacting the local DNS resolver. It could be your local resolver is at fault.
You can at least avoid an 8 minute hang in this case by using --connect-timeout

**Comment by TruncatedDinoSour** [comment]
> That strace snippet didn't show much, but it seemed to show issues with contacting the local DNS resolver. It could be your local resolver is at fault. You can at least avoid an 8 minute hang in this case by using --connect-timeout

i dont think this is a curl issue anymore, even *git* does the same, i try to clone a repo, or pull it, it hogs up my cpu, ram and swap, and as always -- it hangs
very very weird, though i think its a kernel issue maybe ? ill try to configure it and see myself

**Comment by dfandrich** [comment]
> i dont think this is a curl issue anymore, even git does the same, i try to

git uses libcurl under the hood.

> clone a repo, or pull it, it hogs up my cpu, ram and swap, and as always -- it
> hangs
> very very weird, though i think its a kernel issue maybe ? ill try to configure
> it and see myself

It could be an issue with your local network configuration.

**Comment by TruncatedDinoSour** [comment]
> i dont think this is a curl issue anymore, even git does the same, i try to
> git uses libcurl under the hood.
> clone a repo, or pull it, it hogs up my cpu, ram and swap, and as always -- it hangs very very weird, though i think its a kernel issue maybe ? ill try to configure it and see myself
> It could be an issue with your local network configuration.

idk what i did, but it wasnt, i fixed it somehow
