### ISSUE TITLE
OPTIONS * to proxy

### ISSUE THREAD

**Issue by icing** [curl/curl#12820]
### I did this

I ran test case 1613 with curl master.

### I expected the following

When sending an "OPTIONS *" to a HTTP/1.1 proxy, the request needs to be forwarded as (RFC 9112, ch. 3.2.4)

```
OPTIONS http://www.example.org HTTP/1.1
```

instead, curl sends

```
OPTIONS * HTTP/1.1
Host: www.example.org
```

### curl/libcurl version

8.6.0-DEV

### operating system

macOS

**Comment by bagder** [comment]
I don't think this is a bug. This test uses `--request-target` which lets the user specify the exact string to pass in the "target" part of the request. In this case it sends `*` there (combined with the method `OPTIONS` set with `-X` ). This might be the wrong thing to send to a proxy, HTTP wise, but that's not what the test is about.

**Comment by icing** [comment]
The question is what does the user (and we) expect to happen? If we want to send `OPTIONS *` to the origin server, we need to send `OPTIONS http://origin` to the proxy. Otherwise we get the OPTIONS response from the proxy and not from the origin server. I believe...

**Comment by bagder** [comment]
I understand. But this test is there to verify the `OPTIONS *` part of the request and that it gets a response. It does not care if the answer is for the proxy or for the remote resource.

**Comment by jay** [comment]
it is functioning [as documented](https://curl.se/docs/manpage.html#--request-target)

**Comment by icing** [comment]
> it is functioning [as documented](https://curl.se/docs/manpage.html#--request-target)

This is what test 1299 verifies correctly. test 1613 does the same via a non-tunneling proxy and the HTTP/1.1 RFC says that the request to the proxy needs to be send differently to make a `OPTIONS *` to the origin server.

**Comment by bagder** [comment]
Right, but nothing in the test says this needs to be sent to the origin server. The test only verifies that the presumed request target is used, *even* if the destination is a proxy.

**Comment by icing** [comment]
There seems to be a communication breakdown somewhere here. Maybe at my end. I try to rephrase.

The test verifies what is documented. I do not want to argue about that. The question is: can a curl user send an 'OPTIONS *' through a proxy to the origin server or not?

If we decide that this is not possible with curl, then we do not need change anything. If we want that to work, we need to fix the code and the test expectations.

**Comment by bagder** [comment]
> The test verifies what is documented. I do not want to argue about that. The question is: can a curl user send an 'OPTIONS *' through a proxy to the origin server or not?

If a user wants to do that, I presume it would be done with:

`curl --request-target http://www.example.org -X OPTION -x proxy http://www.example.org`

or similar. `--request-target` is very crude and assumes knowledge of what is actually going on at protocol level.

**Comment by icing** [comment]
Thanks, then I close the issue, having misunderstood at what level this option works at.
