### ISSUE TITLE
the example "asiohiper" in tags is not working well on windows,please update

### ISSUE THREAD

**Issue by cimstu** [curl/curl#1282]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
1.get curl source and example "asiohiper" from tag:curl_7_52_1
2.build curl source using "DLL Debug - DLL OpenSSL"
3.test the  "asiohiper" example with url:"https:xxxx"
### I expected the following
i will get something from server,but no CURLMSG_DONE received,the connection just closed by curl when doing handshake
it takes about three weeks to find out why?At last i found threre are two problems:
1.the example "asiohiper" is so old in tag:curl_7_52_1
2.on windows openssl may have some problems
so...
1.update the example "asiohiper" on "https://curl.haxx.se/libcurl/c/asiohiper.html"
2.compile curl using "DLL Debug - DLL Windows SSPI"
CURLMSG_DONE comes!
### curl/libcurl version
curl_7_52_1
[curl -V output perhaps?]

### operating system
windows 7 64
vs2005
vs2015

**Comment by bagder** [comment]
You need to elaborate much more on exactly what the problem is or this will just be closed and ignored.

**Comment by bagder** [comment]
@cimstu I assume you talk about the bug fix in ed2fcd54283179df that was done *after* 7.52.1 was released. So, perfectly expected.

**Comment by cimstu** [comment]
Thanks a lot!
And could you fix the bug that "asiohiper" can't receive  CURLMSG_DONE using openssl on windows?

**Comment by bagder** [comment]
> could you fix the bug

If that is a bug in the current version of asiohiper.c then please file that as a separate issue and explain it with details and we'll work on that just like all other bugs.
