### ISSUE TITLE
curl verifies incorrect subject alternative name when contacting https proxy

### ISSUE THREAD

**Issue by HsiehYuho** [curl/curl#12831]
### I did this

I tried 
```
curl -x https://[proxy:ipv6]:8082 https://destination.hostname
```
It gives me SAN match failure. 
```
SSL:no alternative certificate subject name matches target hostname [proxy:ipv6]
```
However, the [proxy:ipv6] is in the proxy cert SAN field. 
When switching to 
```
curl -x https://[proxy:ipv6]:8082 https://[destination.ipv6]
```
the curl succeeds. 

We (my colleagues and me) are suspecting checks around here https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L2152 lead to that curl only checks the proxy SAN type that is same as the destination type 

### I expected the following

```
curl -x https://[proxy:ipv6]:8082 https://destination.hostname 
curl -x https://[proxy:ipv6]:8082 https://[destination.ipv6]
```
should at least give me the same result

### curl/libcurl version

curl 7.61.1 (x86_64-redhat-linux-gnu)

### operating system

Linux, but our company (meta) dev our own linux ..

**Comment by HsiehYuho** [comment]
I didn't spend time working on a repro but we fairly sure that there is at least inconsistent output where there shouldn't be.

**Comment by dfandrich** [comment]
That curl version is 5.4 years out of date. Does this reproduce with a recent
version?  What TLS library are you using?

**Comment by HsiehYuho** [comment]
Hi Dan, 
Yes, it is reproducible using the latest curl 
```
./src/.libs/curl --version
curl 8.6.0-DEV (x86_64-pc-linux-gnu) 
```
we are using openssl.

**Comment by icing** [comment]
@HsiehYuho I added a test case using '127.0.0.1' for the proxy and gave it a certificate with a x590 IPAddress in the alt names. This test works with curl 8.6.0.

Could you recheck your findings? Is there anything specific in your ipv6 address spec that we may not account for?

**Comment by knekritz** [comment]
@icing I think the issue is specific to IPv6 because of the `conn->bits.ipv6_ip` check at https://github.com/curl/curl/blob/f8513ee62ec72af996139d2756beeac8a828afd8/lib/vtls/openssl.c#L2154

**Comment by icing** [comment]
@knekritz thanks, that is exactly the right spot. Would you be able to verify that #12931 fixes the issue for you as well?

**Comment by HsiehYuho** [comment]
@icing i tried to verify it. I git clone your branch and follow https://github.com/curl/curl/blob/master/GIT-INFO to `make` the binary, then execute it through
```
[yhhsieh@mydev ~/curl (proxy-ipv6-cert-check)]$ ./src/.libs/curl telnet://DESTINATION_HOSTNAME:PORT -p -x  https://[PROXY:IPV6]:8082  --proxy-cert $PROXY_CERT --proxy-key $PRXOY_KEY -vvv 
```
but it seems not hit you fix. I suspect my build is wrong. the `./src/.libs/curl` was built but the commit seems not applied. Did i do anything wrong ?

**Comment by jay** [comment]
> ./src/.libs/curl

Use src/curl instead, which may be a libtool wrapper script that uses LD_LIBRARY_PATH to load the libcurl that's in lib/.libs

**Comment by icing** [comment]
@HsiehYuho if you run ./src/curl with options `-v --trace-config all` and your other arguments, what is the output?

**Comment by HsiehYuho** [comment]
@jay @icing  thank you guys so much! Yes if i replace with `./src/curl` then the fix kicks in and works! I think the fix is the right one!
