### ISSUE TITLE
8.6.0 Configure breaks if libpsl is not present.

### ISSUE THREAD

**Issue by rsbeckerca** [curl/curl#12830]
### I did this

Ran configure on NonStop. Configure ran until the following and aborted.
```
checking for library containing psl_builtin... no
configure: error: libpsl was not found
```

### I expected the following

Expected configure to continue and configure curl not to use `psl_builtin`.

### curl/libcurl version

curl 8.6.0

### operating system

`uname -a: NONSTOP_KERNEL tcmvns L23 08 NSV-I NSV NSV-I NonStop Kernel`

**Comment by vszakats** [comment]
8.6.0 made libpsl required by default (for security/privacy with cookies). An explicit `--without-libpsl` fixes it.

[ Maybe useful info that libpsl 0.21.5 now supports building it without the large dependencies that were required in previous releases, making it easier to use and much smaller, including the embedded PSL db. ]

PR #12661

**Comment by rsbeckerca** [comment]
> 8.6.0 made libpsl required by default (for security/privacy with cookies). An explicit `--without-libpsl` fixes it.
> 
> [ Maybe useful info that libpsl 0.21.5 now supports building it without the large dependencies that were required in previous releases, making it easier to use and much smaller, including the embedded PSL db. ]
> 
> PR #12661

libpsl 0.21.5 has numerous dependencies on Linux in the code that are not portable. It configures but does not come close to compiling on some POSIX-compliant systems (including requiring more recent C than c99, requiring `inet_pton`, and that's just in the first file I tried to compile.

**Comment by vszakats** [comment]
If it doesn't work for you, that's okay and probably worth taking to libpsl. The `inet_pton` issue is tracked here: The `inet_pton` dependency is tracked here: https://github.com/rockdaboot/libpsl/issues/226

**Comment by bagder** [comment]
I also blogged about the background to this decision: https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/

This is not a bug.

**Comment by rsbeckerca** [comment]
> I also blogged about the background to this decision: https://daniel.haxx.se/blog/2024/01/10/psl-in-curl/
> 
> This is not a bug.

I just wish PSL was more portable that it is. It has dependencies that are also not portable and do not build on standard POSIX environments. With that said, I understand the intent even if I cannot use this capability outside of the limited set of platforms PSL supports.

**Comment by vszakats** [comment]
All libpsl dependencies are optional since 0.21.5. We use to ship curl-for-win (also for Linux and macOS):
https://github.com/curl/curl-for-win/commit/3a0fd34f69186ad6204ee522fbf6389cfef2a674

**Comment by rsbeckerca** [comment]
> All libpsl dependencies are optional since 0.21.5. We use it to ship curl-for-win (also for Linux and macOS): [curl/curl-for-win@3a0fd34](https://github.com/curl/curl-for-win/commit/3a0fd34f69186ad6204ee522fbf6389cfef2a674).

This should probably go to the libpsl project. I have built curl without the functionality but I can see this turning into a CVE for the builds we have because libpsl requires more modern compilers and APIs that are available broadly.

**Comment by bagder** [comment]
I don't see how this is the fault of libpsl nor curl though... If you/your company want to see support for this where there is a lack of support today, then you step up or pay someone else to do the job. None of these projects has an **obligation** to support your platform.

**Comment by rsbeckerca** [comment]
I am willing to step up, but will need guidance on it. Case opened with libpsl asking for some assistance. We can close this conversation from a Curl perspective.

**Comment by vszakats** [comment]
> I did radically overestimated the effort to get the compile to work. Would curl support `libpsl.a` for linking or is a DLL required?

Either should work. E.g. curl-for-win links `libpsl.a` statically.

As for compiling it, it's one Python command to generate the embedded PSL header, then compiling the two .c files in `src` and making an .a of them: https://github.com/curl/curl-for-win/blob/ae856f2aa00ec899e9658f18c194169205d9e279/libpsl.sh#L31-L42
