### ISSUE TITLE
Brew libpsl won't link without specifying icu4c libraries

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#12847]
### I did this

In researching the OS X build failures in PR #12635 I discovered that on M1 libpsl 0.21.5 from Brew needs to link with -licuuc -licudata to resolve symbols and link properly. Without this, configure can't perform the test link of `psl_builtin()` and therefore concludes that libpsl is not available. Installing `icu4c` through Brew and configuring with `CPPFLAGS='-I/opt/homebrew/opt/libpsl/include -L/opt/homebrew/opt/libpsl/lib -I/opt/homebrew/Cellar/icu4c/73.2/include -L/opt/homebrew/Cellar/icu4c/73.2/lib' LIBS='-licuuc -licudata' ` lets that configure test succeed (only to hit problems at the libcurl link part of the build).

It's hard to debug this exclusively through the CI, so I'm hoping someone with an M1 Mac can take it further. I suspect that it's trying to link to the static libpsl instead of the dynamic one because I would expect any implied dependencies of libpsl.5.dylib should be picked up automatically at run time; there should be no need to add `LIBS` (if Mach-O works like ELF). I originally thought that switching to use `pkg-config` in configure for libpsl would fix this but I now think not, because libpsl.pc has `Requires.private: icu-uc` so it would only pull those in in a static link.

Brew itself builds curl with `--without-libpsl` and so bypasses this issue entirely. This is only a problem on M1. Linking works fine on x86_64.

### I expected the following

curl should build and link on M1 OS X with libpsl if available, automatically.

### curl/libcurl version

curl ~8.6.0

### operating system

Failing M1 system:
* System: Darwin distillers-Virtual-Machine.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:19 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_VMAPPLE arm64

Working x86_64 system:
* System: Darwin static.38.39.183.114.cyberlynk.net 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
I have none of these problems on my m1!

## my build

latest homebrew, current curl git master:

curl 8.6.1-DEV (aarch64-apple-darwin22.5.0) libcurl/8.6.1-DEV OpenSSL/3.2.1 zlib/1.2.11 brotli/1.1.0 zstd/1.5.5 c-ares/1.26.0 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.59.0 libgsasl/2.2.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli Debug gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

## my configure

Is a little convoluted:

LDFLAGS="-L/opt/homebrew/opt/gsasl/lib -L/opt/homebrew/opt/libpsl/lib -L/opt/homebrew/opt/libnghttp2/lib" CPPFLAGS="-I/opt/homebrew/opt/gsasl/include -I/opt/homebrew/opt/libpsl/include -L/opt/homebrew/opt/libnghttp2/include" ./configure --enable-debug --enable-maintainer-mode --with-openssl=/opt/homebrew/opt/openssl --with-libssh2=/opt/homebrew/opt/libssh2 --enable-websockets --with-brotli=/opt/homebrew/opt/brotli --with-zstd=/opt/homebrew/opt/zstd --enable-ares=/opt/homebrew/opt/c-ares --with-nghttp2

**Comment by bagder** [comment]
@dfandrich any update on this? It does not appear to be a general problem
