### ISSUE TITLE
[8.6.0] `docs/curl-config.1` contains duplicate content

### ISSUE THREAD

**Issue by jamacku** [curl/curl#12840]
### I did this

Release tarball of curl 8.6.0 contains duplicate content in `docs/curl-config.1`.

The whole man page content is there twice.

### I expected the following

Don't duplicate content in the manpage.

### curl/libcurl version

curl 8.6.0

### operating system

all

**Comment by bagder** [comment]
I believe this is fixed by #12818 already, but I failed to regenerate that particular file before I made the release tarball.

If you remove it and let the build regenerate it, I think it will be fine.

I'm not sure we need to ship the .1 version in the tarball...

**Comment by jamacku** [comment]
I have noticed this just because we [patched the manpage](https://src.fedoraproject.org/rpms/curl/blob/rawhide/f/0101-curl-7.32.0-multilib.patch#_71) to add a note about missing static libs in Fedora/RHEL.

Anyway, this can be closed. Daniel, thank you for the link to the fix.
