### ISSUE TITLE
curl -LO uses the wrong URL to derive a file name.

### ISSUE THREAD

**Issue by ewtoombs** [curl/curl#12845]
### I did this

```
>curl -LOJ https://is.gd/apkovl_master
```

### I expected the following

The file is downloaded to `./headless.apkovl.tar.gz`

Instead, the file is downloaded to apkovl_master.

Firefox gets this right. I expect curl to get it right too.

### curl/libcurl version

curl 8.5.0-1

### operating system

Linux myhostname 6.7.0-arch3-1 #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
The "right" name is subject to interpretation. The right name in this case is
the one that curl is documented to use, which is apkovl_master. -J uses the
Content-Disposition: header to determine a name, but the server does not send
that for this URL, so it falls back on the one in the path. It sounds like what
you want it to use is the one in the final, redirected URL, but curl doesn't
currently offer that as an option. You could have it renamed after the download
using --write-out '%{url_effective}' or lobby for a new option to do this.

**Comment by bagder** [comment]
Picking the name from the first, provided, URL also makes the output predictable, known and decided by the person/script invoking curl. This is by design.

**Comment by bagder** [comment]
Oh, and it can be added that `-J` is limited in what headers it supports so browsers are generally better at extracting and converting the name from `Content-Disposition` headers.
