### ISSUE TITLE
failed to upload file ( zipped file size is 3.2 GB) via curl POST - out of memory - Curl version 8.4.0

### ISSUE THREAD

**Issue by SF-VOL360** [curl/curl#12855]
### I did this

I already referred to this article and already tried the -T option and am still getting an error.
https://github.com/curl/curl/issues/1385

By using -T option , getting other error like could not resolve the host

### I expected the following

No error

### curl/libcurl version

8.4.0

### operating system

Windows Server

**Comment by bagder** [comment]
Can you show us a command line that reproduces the problem for you?

**Comment by bagder** [comment]
No response, can't reproduce, nothing to act on.
