### ISSUE TITLE
nmake don`t work for x64

### ISSUE THREAD

**Issue by Krzysztof044** [curl/curl#12853]
### I did this

cd D:\Programs\Microsoft Visual Studio\curl
.\buildconf.bat

cd D:\Programy\Microsoft Visual Studio\curl\winbuild
nmake /f Makefile.vc mode=static machine=x64

This give me: 
NMAKE : fatal error U1077: „"D:\Programs\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\nmake.exe" /NOLOGO /F MakefileBuild.vc”: return code „0x2”

it`s all working for nmake /f Makefile.vc mode=static, where machine=x86 by default

How to fix it?

### curl/libcurl version

curl-master 03.02.2024

### operating system

windows 11

**Comment by gvanem** [comment]
> cd D:\Programy\Microsoft Visual Studio\curl\winbuild
> nmake /f Makefile.vc mode=static machine=x64
> 
> This give me:
> NMAKE : fatal error U1077: „"D:\Programs\Microsoft Visual > Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\nmake.exe" /NOLOGO /F MakefileBuild.vc”: return code „0x2”

`return code 0x2` means a program/file is missing. Which?
Try with `nmake -K -I ..` to see which. 
But this Nmake build-system is rather confusing; No `VERBOSE=1` mode AFAICS.

**Comment by jay** [comment]
It probably says a lot more errors than that. Are you trying to build for x64 from the x86 native tools prompt? That's not going to work. If you tried that (and even if you then try x64) it won't work. You have to remove the build files from curl\builds and try again from an x64 tools prompt (eg "x64 Native Tools Command Prompt for VS 2022")

**Comment by Krzysztof044** [comment]
@jay thanks for suggestion about architecture of native tool prompt. I have changed tool prompt to x64 native tools command prompt and now everythings work. Thank you so much :)
