### ISSUE TITLE
--resolve option vs. "Host: xyz" latency

### ISSUE THREAD

**Issue by jc2479** [curl/curl#12873]
### I did this

Requests needs up to 20-30ms more when using 
`curl https://hostname --resolve hostname:443:123.123.123.123` 
instead of sending the information in header `curl -H "Host: hostname" https://123.123.123.123`

### I expected the following

I'd expect the same response times, because the ip and port are given in `--resolve` and the resolver shouldn't take 20ms to just substitute an ip address

### curl/libcurl version

curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-02-20, security patched: 7.88.1-10+deb12u5
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Debian 12 

Linux xxx 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

**Comment by bagder** [comment]
I suspect the difference is not in the DNS/name resolver handling but perhaps rather that you use `-k` in the latter case? Because then curl can skip loading and parsing the CA cert bundle...

**Comment by bagder** [comment]
I have no idea. I suggest you add `--trace-ascii - --trace-time` and see where there seems to be time spent. Possibly that bump you mention also changed the TLS library version.

**Comment by jc2479** [comment]
From what I can see, the majority of time loss occurs between lines 133 and 135, before the response body is received with curl 7.88.1
[trace_curl774.txt](https://github.com/curl/curl/files/14177960/trace_curl774.txt)
[trace_curl788.txt](https://github.com/curl/curl/files/14177961/trace_curl788.txt)

**Comment by bagder** [comment]
Right, which to me seems to indicate that the different OpenSSL versions behave differently. The gap is in the middle of incoming TLS traffic. Would be interesting to know if you can see the same gap using the latest curl...

**Comment by jc2479** [comment]
unfortunately same time gap at the same position with 
`curl 8.6.0 (x86_64-pc-linux-gnu) libcurl/8.6.0 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.3 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2024-01-31, security patched: 8.6.0-1
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd`

**Comment by icing** [comment]
Hmm, trying to make sense of this. In your `trace_curl774.txt` I see:

```
10:43:14.957890 => Send SSL data, 1 bytes (0x1)
10:43:14.973045 <= Recv SSL data, 5 bytes (0x5)
```

and in `trace_curl788.txt` there is:

```
10:42:04.156265 <= Recv SSL data, 1 bytes (0x1)
10:42:04.174698 <= Recv SSL data, 5 bytes (0x5)
```

are these the gaps you are talking about? Since both are "receives" I would suspect that they are triggered by a POLLIN event when new data arrived from the server. Or am I looking in the wrong location?

**Comment by jc2479** [comment]
I think the problem is the CA parsing/handling. 
In small requests it increases the response time by at least 100%.
Are there any workaround or fixes in progress for that?

**Comment by jc2479** [comment]
thank you very much for helping to clarify the behaviour. indeed, the topic "performance" seems to be hotly debated.

**Comment by bagder** [comment]
The CA cert bundle is needed to verify the TLS server certificate. It needs to be loaded and parsed in order for this to work. curl will cache that CA cert bundle in memory after that first load+parse so that for the next one it has already done the job, but if you only do a single request then of course that does not help you.

I don't think this is an issue we can fix. The slowdown you measure is probably caused by the changed OpenSSL versions.
