### ISSUE TITLE
Reusing curl handle is causing "CURLE_URL_MALFORMAT" error

### ISSUE THREAD

**Issue by andrewpitts15** [curl/curl#12918]
### I did this

I'm trying to reuse a curl handle for multiple requests, but on the second request the result is "CURLE_URL_MALFORMAT"

```
	struct curl_slist* slist1 = nullptr;
	slist1 = curl_slist_append(slist1, "Content-Type: application/json");

	std::string response;

	CURL* handle = curl_easy_init();
	curl_easy_setopt(handle, CURLOPT_URL, url.c_str());
	curl_easy_setopt(handle, CURLOPT_POSTFIELDS, json.c_str());
	curl_easy_setopt(handle, CURLOPT_HTTPHEADER, slist1);
	curl_easy_setopt(handle, CURLOPT_POST, 1L);
	curl_easy_setopt(handle, CURLOPT_WRITEFUNCTION, WriteCallback);
	curl_easy_setopt(handle, CURLOPT_WRITEDATA, &response);

	// parse response

	CURLcode ret;
	ret = curl_easy_perform(handle);

	if (ret == CURLE_OK)
	{
		// 
	}
	else
	{
		//
	}

	curl_easy_reset(handle);

	curl_easy_setopt(handle, CURLOPT_URL, url.c_str());
	curl_easy_setopt(handle, CURLOPT_POSTFIELDS, json.c_str());
	curl_easy_setopt(handle, CURLOPT_HTTPHEADER, slist1);
	curl_easy_setopt(handle, CURLOPT_POST, 1L);
	curl_easy_setopt(handle, CURLOPT_WRITEFUNCTION, WriteCallback);
	curl_easy_setopt(handle, CURLOPT_WRITEDATA, &response);

	ret = curl_easy_perform(handle);

	if (ret == CURLE_OK)
	{
		// 
	}
	else
	{
		//
	}

	curl_easy_cleanup(handle);
```

### I expected the following

CURL to successfully perform the requests. It only manages the first request though.

It sometimes also crashs on `curl_easy_reset`.

### curl/libcurl version

curl 7.86

### operating system

Windows 10

**Comment by jzakrzewski** [comment]
I don't know about the crash, but `curl_easy_reset` removed the URL from the handle - you have to put it back there.

**Comment by andrewpitts15** [comment]
> I don't know about the crash, but `curl_easy_reset` removed the URL from the handle - you have to put it back there.

Opps. I do set the URL for the second request, I just accidentally didn't include it in the code I included in my message.

**Comment by bagder** [comment]
This is not a reproducible example since it misses key parts of the code. Unless we can build and repeat the issue, what are you expecting us to do?

**Comment by andrewpitts15** [comment]
All I've removed is the specific URL and JSON content and parsing out the response because they are sensitive so it doesn't feel like it's relevant. Can you think why reusing a handle would result in "CURLE_URL_MALFORMAT"?

**Comment by bagder** [comment]
> Can you think why reusing a handle would result in "CURLE_URL_MALFORMAT"?

Only if the URL is malformed in the second case...

**Comment by jay** [comment]
Please try to reproduce with the latest version of curl.

**Comment by bagder** [comment]
No response.
