### ISSUE TITLE
openssl-3.0.13 - error: --with-openssl was given but OpenSSL could not be detected

### ISSUE THREAD

**Issue by RenHoekNL** [curl/curl#12916]
### I did this

OpenSSL 1.1.1x is end of life so I tried compiling with openssl-3. I'm doing a static build with musl-gcc but this should be irrelevant.

I first compiled OpenSSL, gave the path to configure and got back this error:

> checking OpenSSL linking with -ldl... no
> checking OpenSSL linking with -ldl and -lpthread... no
> checking for SSL_set_quic_use_legacy_codepoint... no
> configure: OpenSSL version does not speak QUIC API
> configure: OPT_OPENSSL: /root/curl-8.6.0/openssl-3.0.13
> configure: OPENSSL_ENABLED:
> configure: error: --with-openssl was given but OpenSSL could not be detected

I checked the config.log and it showed that during OpenSSL detection, curl is look for the crypto lib in the 'lib' directory. With OpenSSL the libcrypto.a is in the main directory.

So it looks like the config script needs an update.

A temporary fix is going into the openssl directory and doing a

> ln -s . lib

This allows configure to find the lib.

My configure command:

```
CC=musl-gcc ./configure \
  --prefix=/ \
  --disable-debug \
  --enable-optimize \
  --enable-static \
  --disable-shared \
  --disable-ares \
  --disable-curldebug \
  --disable-dict \
  --disable-doh \
  --disable-file \
  --enable-ftp \
  --disable-gopher \
  --disable-imap \
  --disable-ldap \
  --disable-ldaps \
  --disable-manual \
  --disable-mqtt \
  --disable-ntlm \
  --disable-pop3 \
  --disable-progress-meter \
  --disable-rtsp \
  --disable-smb \
  --disable-smtp \
  --disable-socketpair \
  --disable-telnet \
  --disable-tftp \
  --disable-unix-sockets \
  --disable-websockets \
  --without-libgsasl \
  --without-libidn2 \
  --without-libpsl \
  --without-msh3 \
  --without-nghttp2 \
  --without-nghttp3 \
  --without-ngtcp2 \
  --without-quiche \
  --without-winidn \
  --with-ca-fallback \
  --enable-get-easy-options \
  --enable-openssl-auto-load-config \
  --with-openssl=$(realpath ./openssl-*/ )
```

### I expected the following

For configure to run without errors

### curl/libcurl version

curl 8.6.0

### operating system

Ubuntu 22.04.3 LTS

**Comment by RenHoekNL** [comment]
Right.. but since I'm not doing an install of the compiled OpenSSL, there is not lib directory. Is that what you are saying?

Since I'm compiling with musl-gcc I don't want to install the lib files to my main system.

I just ran into the same issue with zlib btw. 

> configure:23593: result: yes
> configure:23839: checking for zlib.h
> configure:23839: musl-gcc -c -Werror-implicit-function-declaration -O2 -Wno-system-headers  -I/root/curl-8.6.0/zlib-1.3.1/include conftest.c >&5
> conftest.c:73:10: fatal error: zlib.h: No such file or directory
>    73 | #include <zlib.h>
>       |          ^~~~~~~~

Where I compile libz, and point to it in configure, it expects the library in a 'lib' directory, which it isn't.


In any case, just installing musl-gcc static libraries to the main system will lead to problems. I can fix it by just softlinking directories. Up to you then if this is intended behaviour. :)

**Comment by jzakrzewski** [comment]
The easiest solution is to install all the required libraries not system-wide, but into a prefix.
So something along the lines: `configure --prefix=$HOME/musl-root ... ; make ; make install;`
Then the file structure will be right.

**Comment by bagder** [comment]
> Since I'm compiling with musl-gcc I don't want to install the lib files to my main system.

You can install it anywhere you like and then point curl's configure to that location. There's no need for it to be the "main system".

As you have already figured out, you can also fiddle when your build directory to make it look like an install prefix and then curl can find it there. But that's not what configure tries to do. It finds libraries that are installed.

**Comment by RenHoekNL** [comment]
You are right. Thanks for reminding me that I can install to a non-main directory. Consider this issue closed then.

**Comment by srini7015** [comment]
I am also facing the issue , can someone help . i am getting the error 

./configure --disable-shared --without-zlib --with-openssl=/home/xyz1/xyz2/jenkinsopenssl ==> i am getting error as below.

configure: error: --with-openssl was given but OpenSSL could not be detected

I have installed the openssl at the /home/xyz1/xyz2/jenkinsopenssl

**Comment by jay** [comment]
> I am also facing the issue , can someone help . i am getting the error
> 
> ./configure --disable-shared --without-zlib --with-openssl=/home/xyz1/xyz2/jenkinsopenssl ==> i am getting error as below.
> 
> configure: error: --with-openssl was given but OpenSSL could not be detected

You would have to examine config.log to find out why

**Comment by artenax** [comment]
Help!

```
LDFLAGS="-static" ./configure --without-libpsl --disable-docs --disable-static --enable-shared --disable-debug --disable-rtsp --with-openssl=/usr/x86_64-w64-mingw32/sys-root/mingw --disable-ldap --disable-ldaps --without-brotli --without-zstd --without-nghttp2 --host=x86_64-w64-mingw32

configure: PKG_CONFIG_LIBDIR will be set to "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig"
checking for x86_64-w64-mingw32-pkg-config... (cached) /usr/bin/x86_64-w64-mingw32-pkg-config
checking for openssl options with pkg-config... found
configure: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure: pkg-config: SSL_LDFLAGS: ""
configure: pkg-config: SSL_CPPFLAGS: ""
checking for HMAC_Update in -lcrypto... no
checking for HMAC_Init_ex in -lcrypto... no
checking OpenSSL linking with -ldl... no
checking OpenSSL linking with -ldl and -lpthread... no
checking for SSL_set_quic_use_legacy_codepoint... no
configure: OpenSSL version does not speak QUIC API
configure: OPT_OPENSSL: /usr/x86_64-w64-mingw32/sys-root/mingw
configure: OPENSSL_ENABLED: 
configure: error: --with-openssl was given but OpenSSL could not be detected

cat config.log | grep ssl
  $ ./configure --without-libpsl --disable-docs --disable-static --enable-shared --disable-debug --disable-rtsp --with-openssl=/usr/x86_64-w64-mingw32/sys-root/mingw --disable-ldap --disable-ldaps --without-brotli --without-zstd --without-nghttp2 --host=x86_64-w64-mingw32
configure:26474: checking for openssl options with pkg-config
configure:26517: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure:26556: x86_64-w64-mingw32-gcc -o conftest.exe -Werror-implicit-function-declaration -O2 -Wno-system-headers    -static   conftest.c -lcrypto  -lssl -lcrypto -lz -lws2_32  >&5
/usr/lib/gcc/x86_64-w64-mingw32/14.1.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lssl: No such file or directory
configure:26609: x86_64-w64-mingw32-gcc -o conftest.exe -Werror-implicit-function-declaration -O2 -Wno-system-headers    -static   conftest.c -lcrypto  -lssl -lcrypto -lz -lws2_32  >&5
/usr/lib/gcc/x86_64-w64-mingw32/14.1.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lssl: No such file or directory
|          #include <openssl/err.h>
|            #include <openssl/err.h>
configure:27082: error: --with-openssl was given but OpenSSL could not be detected
CONFIGURE_OPTIONS='" '\''--without-libpsl'\'' '\''--disable-docs'\'' '\''--disable-static'\'' '\''--enable-shared'\'' '\''--disable-debug'\'' '\''--disable-rtsp'\'' '\''--with-openssl=/usr/x86_64-w64-mingw32/sys-root/mingw'\'' '\''--disable-ldap'\'' '\''--disable-ldaps'\'' '\''--without-brotli'\'' '\''--without-zstd'\'' '\''--without-nghttp2'\'' '\''--host=x86_64-w64-mingw32'\'' '\''host_alias=x86_64-w64-mingw32'\'' '\''LDFLAGS=-static'\''"'
SSL_LIBS='-lssl -lcrypto'
```

**Comment by artenax** [comment]
The mingw64-openssl package is installed. I also cross compiled openssl from source. I have also tried mingw in ubuntu 22.04, msys2 in win7 - nothing helps. The error is similar as here https://stackoverflow.com/questions/41792089/cannot-cross-compile-curl-with-openssl-support-for-windows

**Comment by bagder** [comment]
@artenax you are commenting in an old closed issue. This will not help you or anyone else.

If you have an issue, submit a new issue. If it's just a question, ask it in the discussions area.

**Comment by jrynkiew** [comment]
> checking for x86_64-w64-mingw32-pkg-config... (cached) /usr/bin/x86_64-w64-mingw32-pkg-config

This is your problem.

The mingw-w64-tools package is broken somehow, the tools it installs don't work. 

If you try to run the program, you will get this message:

`root@7bb6301bda86:/build/curl# /usr/bin/x86_64-w64-mingw32-pkg-config
Please install dpkg-dev to use pkg-config when cross-building`

Installing the package doesn't help, I already have that package installed.

`root@7bb6301bda86:/build/curl# apt list --installed | grep dpkg-dev
dpkg-dev/focal-updates,focal-updates,focal-security,focal-security,now 1.19.7ubuntu3.2 all [installed,automatic]`

I found that the key to successfully building it is setting the CC and LDFLAGS manually

Here is an excerpt from my build pipeline

`ENV BUILD_DIR=/build
ENV SRC_DIR=/src

ENV PREFIX=/opt/mingw/x86_64-w64-mingw32
ENV HOST=x86_64-w64-mingw32
ENV BUILD=x86_64-linux-gnu
ENV TARGET=x86_64-w64-mingw32
ENV CC=x86_64-w64-mingw32-gcc
ENV LDFLAGS="-L${PREFIX}/lib -lssl -lcrypto -lws2_32 -lbcrypt -lcrypt32 -lgdi32"

COPY --from=downloader ${SRC_DIR}/curl ${BUILD_DIR}/curl

WORKDIR ${BUILD_DIR}/curl

RUN ./configure \
        --enable-static \
        --disable-shared \
        --prefix=${PREFIX} \
        --host=${HOST} \
        --with-ssl=${PREFIX} \
        --without-libpsl \
        --without-nghttp2 && \
    make -j$(nproc) && \
    make install

RUN rm -rf ${BUILD_DIR}`

**Comment by rsbeckerca** [comment]
If it helps, NonStop x86 (32,64 bit) builds successfully with OpenSSL 3.0.13. We use libpsl, but not --enable-static.

**Comment by siliconej** [comment]
I found out that the reason is because python configure file tries to look for **$openssl_install_dir/lib** instead of **$openssl_install_dir/lib64** on my ubuntu x64 installation. I created symbolic_link from lib64 to lib, now the configure works.

checking for openssl/ssl.h in /usr/local/ssl... yes
checking whether compiling and linking against OpenSSL works... yes
checking for --with-openssl-rpath... 
checking whether OpenSSL provides required ssl module APIs... yes
checking whether OpenSSL provides required hashlib module APIs... yes
