### ISSUE TITLE
Command-line option --upload is undocumented

### ISSUE THREAD

**Issue by pajot** [curl/curl#12936]
### I did this

man curl

### I expected the following

To find a reference for --upload in the man page. There is --upload-file, but --upload is not mentioned there.

### curl/libcurl version

curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

$ uname -a
Linux pvw-wp-01 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

**Comment by danielgustafsson** [comment]
It's not documented since it's not an option..

**Comment by pajot** [comment]
I have tested it and it works. Was it removed in more recent versions?

**Comment by vszakats** [comment]
As tested with 8.4.0, curl seems to have supported abbreviating long option names. `--up` also worked. Just like e.g. `--cace` instead of `--cacert`.

But `--u` was too broad and failed:
```
curl: option --u: is ambiguous
```

`--ur` also failed like this, despite only matching `--url`.

This behaviour however (which might possibly be accidental?) is gone with 8.6.0.
```
curl: option --upload: is unknown
```
```
curl: option --up: is unknown
```

**Comment by danielgustafsson** [comment]
It was removed in 07dd60c05b5f6b00ff7cc0d65c6b46cb1a6938a2, from the commit message:
```
    - remove "partial match" feature. It was not documented, not tested and
      was always fragile as existing use could break when we add a new
      option
```
