### ISSUE TITLE
curl does not send trailers for small requests

### ISSUE THREAD

**Issue by mkauf** [curl/curl#12938]
### I did this

Trailers are sent only for "big" requests (approx. >= 64 KB). For "small" requests, trailers are not sent, and the function set by `CURLOPT_TRAILERFUNCTION` is not called.

**How to reproduce:**

For testing, I have added trailer support to the curl tool: [curl-trailers.patch.txt](https://github.com/curl/curl/files/14281359/curl-trailers.patch.txt) - build curl with this patch.

Create test data with:
```
( for N in $(seq 1000); do printf "param%d=%d&" $N $N; done ) > numbers-small.txt
( for N in $(seq 5000); do printf "param%d=%d&" $N $N; done ) > numbers.txt
```

Start netcat:
```
netcat -l localhost 8000
```

With this request, trailers are not sent:
```
curl -v -s --data @numbers-small.txt --header 'Transfer-Encoding: chunked' --header 'Trailer: MyTrailer' --trailer 'MyTrailer: My Trailer Value' http://localhost:8000/
```
Netcat output:
```
[...]
aram996=996&param997=997&param998=998&param999=999&param1000=1000&
0

```

When using the bigger "numbers.txt", trailers are sent:
```
curl -v -s --data @numbers.txt --header 'Transfer-Encoding: chunked' --header 'Trailer: MyTrailer' --trailer 'MyTrailer: My Trailer Value' http://localhost:8000/
```
Netcat output:
```
[...]
6&param4997=4997&param4998=4998&param4999=4999&param5000=5000&
0
MyTrailer: My Trailer Value
```

### I expected the following

Trailers are sent also for small requests.

### curl/libcurl version

curl master

### operating system

Fedora Linux 39

**Comment by icing** [comment]
Not quite there yet. Working on adding a test case.

**Comment by icing** [comment]
Ok, fix is verified to be in `master` with added test in #13009.
