### ISSUE TITLE
c-ares version check fails when linking thread-safe c-ares using --enable-ares

### ISSUE THREAD

**Issue by ndusart** [curl/curl#12940]
### I did this

- Build c-ares (starting from v1.22 with thread-safety feature) statically and install it in `$SYSROOT/usr/local`
- Configure cURL build using this command: `./configure --enable-static --disable-shared --with-pic --with-sysroot="${SYSROOT}" --prefix="/opt/build/curl/dist" --enable-ares="${SYSROOT}/usr/local"`

Check failed with :
```
checking that c-ares is good and 1recent enough... no
configure: error: c-ares library defective or too old
```

The problem stems from the fact that when using `--enable-ares` and pkg-config is not available the `ares_LIBS` is forced to `-lcares` while cares now relies on `-pthread` flag too if thread-safety is enabled.  (https://github.com/curl/curl/blob/master/m4/curl-confopts.m4#L507)

The check then fails.

Would it be possible to add `-pthread` in `ares_LIBS` or add a way to specify additional libraries ?

### I expected the following

The check should pass as it is a recent version of c-ares

### curl/libcurl version

Tested on curl 8.6.0 

### operating system

Linux dudu-x1 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux

**Comment by jay** [comment]
On the one hand I don't think we should be responsible for static dependencies but on the other hand we already have an -lpthread check for static OpenSSL.

**Comment by bagder** [comment]
Just because we were weak and caved in once does not mean we should do it more.

When building statically, users are mostly on their own. It's such a nightmare to try to keep up with it.

**Comment by ndusart** [comment]
I totally get your point. Being aligned with the transitive dependencies is a chore and should not be your responsability.
My point was not specifically to ask to keep up with this specific linker flag but to add a way to tell the configure tool that we handle this (as this is static linking and we are on our own) and we will correctly link the final application.

pkg-config is an option to defer the resolution of flags upstream, but the check fails the same because `-lpthread` is defined as a private library in the .pc file.

I do not have a proper solution to suggest. The best I can think of is that for each --enable-`xxx` flag there would be a -enable-`xxx`-static flag indicating that pkg-config should be used with `--static` flag so that the private libraries are used.
It wouldn't support static linking without pkg-config, but setting pkg-config is not that complicated and it avoid having to edit .m4 files of curl.

It's about defining where it si appropriate to let users be on their own. I can hear that editing .m4 file is where you put that line, but it would be much easier for us to be able to link against static libraries without having to touch on these files (still saving you from keeping track of the transitive dependencies).

Thanks for the consideration anyway :slightly_smiling_face:

**Comment by thomgree** [comment]
I worked around this by using CMake to configure the build instead of autotools.
