### ISSUE TITLE
Inconsistent behavior on Windows (error 56 and vcpkg)

### ISSUE THREAD

**Issue by ae-5th** [curl/curl#12967]
### I did this

This post is not a bug report. It is more like an info.

If anyone started to get error 56 from version 8.6 and is using the vcpkg dependency's generated DLL file. You need to replace it with a DLL from the curl site.

The error could be present always or sometimes. Behavior changes are dependent on the Windows version. Also, it could be the same version of Windows, but it's started on a different PC.

### curl/libcurl version

curl 8.6.0

### operating system

Windows

**Comment by bagder** [comment]
> This post is not a bug report. It is more like an info.

... and yet you filed it as an issue. There is no information here for us to act on, so unless you tell us a lot more, we will close this soon. Given what you write, this could even be a problem that comes from vcpkg somehow.

**Comment by ae-5th** [comment]
It should be closed. I just put it here if someone else gets sudden error 56.

It is not a curl bug. It is a problem with the vcpkg generated dll.

**Comment by ae-5th** [comment]
.
