### ISSUE TITLE
curl HTTP/3 does not return body

### ISSUE THREAD

**Issue by cowwoc** [curl/curl#12961]
### I did this

curl --http3 -verbose https://licensed.app:8443/

I expected to get back the document body but instead I got:

```
* Host licensed.app:8443 was resolved.
* IPv6: 2607:f2c0:948a:ba00:29cb:e324:bf4d:ca98
* IPv4: 69.165.149.235
*   Trying 69.165.149.235:8443...
* QUIC cipher selection: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_CCM_SHA256
*  CAfile: C:\util\curl\curl-ca-bundle.crt
*  CApath: none
*  subjectAltName: host "licensed.app" matched cert's "licensed.app"
* Verified certificate just fine
* Connected to licensed.app (69.165.149.235) port 8443
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://licensed.app:8443/
* [HTTP/3] [0] [:method: GET]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: licensed.app:8443]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.6.0]
* [HTTP/3] [0] [accept: */*]
* [HTTP/3] [0] [referer: rbose]
> GET / HTTP/3
> Host: licensed.app:8443
> User-Agent: curl/8.6.0
> Accept: */*
> Referer: rbose
>
< HTTP/3 200
< server: Jetty(12.0.7-SNAPSHOT)
< date: Mon, 19 Feb 2024 13:42:25 GMT
< vary: Accept-Encoding
< alt-svc: h3=":8443"; ma=300
< vary: Accept
< cache-control: max-age=300
* HTTP/3 stream 0 reset by server
* Connection #0 to host licensed.app left intact
curl: (95) HTTP/3 stream 0 reset by server
```

If I repeat the same request over HTTP/2 I get back a body.

### curl/libcurl version

curl 8.6.0 (x86_64-w64-mingw32) libcurl/8.6.0 LibreSSL/3.8.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.59.0 ngtcp2/1.2.0 nghttp3/1.1.0
Release-Date: 2024-01-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets zstd

### operating system

Microsoft Windows [Version 10.0.19045.4046]

**Comment by dfandrich** [comment]
Have you run that application on port 443 to make sure the problem is port
related? I think it's much more likely to be application/server related. Port
doesn't treat any more any more special than any other.

**Comment by cowwoc** [comment]
The problem was port-related. See https://github.com/jetty/jetty.project/issues/11417#issuecomment-1952897832.

Hey... Do you have any idea why adding a `Referrer-Policy: strict-origin-when-cross-origin` response header causes CURL to terminate the connection right before returning the response body?

**Comment by bagder** [comment]
> Hey... Do you have any idea why adding a Referrer-Policy: strict-origin-when-cross-origin response header causes CURL to terminate HTTP/3 connections right before returning the response body?

I take it you are now having a *different* issue than before? (So re-opening this was wrong?)

**Comment by cowwoc** [comment]
No. It's actually the same issue. If the header is absent, curl returns the response body. If it's present, it does not. I'm not sure why that is.

**Comment by dfandrich** [comment]
"referrer-policy" does not appear in the curl source code, so it's unlikely to
be a curl thing. More likely is that there's a proxy in the way that's silently
changing things, or the server itself is. You could try having curl send a
"Referer:" header and see if that changes things. It might be a bug that
triggers not on the header but on the size or timing of the request. Have you
tried the latest curl with the latest HTTP/3 backend?

**Comment by bagder** [comment]
Also, adding `--trace-config "http/3"` to the command line will add some extra HTTP/3 info that might help give a clue as so to why this happens. curl does not stop reading just because of this specific header.

**Comment by cowwoc** [comment]
> You could try having curl send a "Referer:" header and see if that changes things.

Unfortunately, it didn't change anything.

> It might be a bug that triggers not on the header but on the size or timing of the request.

That's what I was thinking as well, but so far I've only been able to reproduce the problem with this specific header.

> Have you tried the latest curl with the latest HTTP/3 backend?

I'm not sure how to do this given that I am running on Windows. I downloaded the latest version from https://curl.se/windows/ a few days ago and it is still the latest version as of today.

```
curl 8.6.0 (x86_64-w64-mingw32) libcurl/8.6.0 LibreSSL/3.8.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.59.0 ngtcp2/1.2.0 nghttp3/1.1.0
Release-Date: 2024-01-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets zstd
```

Are any of these dependencies out of date? If so, how would I get a version of curl for Windows that has the newer dependencies?

> Also, adding --trace-config "http/3" to the command line will add some extra HTTP/3 info that might help give a clue as so to why this happens.

That was very helpful! I will paste the logs below. I diffed them and at first glance, the thing that stands out is that `bad.txt` is missing a `Content-Length` header. I checked the server, and it doesn't seem to be sent out. I will contact the Jetty folks and get back to you with the result. Thanks again.

**Comment by bagder** [comment]
I believe this line in bad.txt is the key:

> * HTTP/3 stream 0 reset by server

The server stopped this transfer.
