### ISSUE TITLE
Curl sets `errno` without any error indication

### ISSUE THREAD

**Issue by Harazi** [curl/curl#12970]
### I did this

Using curl with cookie file option set, and localhost as the target, may trigger it to open `/usr/share/publicsuffix/effective_tld_names.dat`, even if the file doesn't exist. This behavior is especially problematic because `errno` will be set to `ENOENT` without any indication from curl side.

The server I was connecting to is [qBittorrent](https://github.com/qbittorrent/qBittorrent)'s WebAPI. I've tried several different services, but none triggered curl to open that file. I've even written a Go program to replicate the exact response from qBittorrent, but without luck.

You can use `strace` to see what file curl is trying to open:
```sh
$ strace -e newfstatat curl -sSb '' http://localhost:8069 >/dev/null
newfstatat(AT_FDCWD, "/usr/local/lib/glibc-hwcaps/x86-64-v3/", 0x7ffc05ccd120, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/lib/glibc-hwcaps/x86-64-v2/", 0x7ffc05ccd120, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/lib/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/glibc-hwcaps/x86-64-v3/", 0x7ffc05ccd120, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/glibc-hwcaps/x86-64-v2/", 0x7ffc05ccd120, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=359, ...}, 0) = 0
newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/share/publicsuffix/effective_tld_names.dat", 0x7ffc05ccd4e0, 0) = -1 ENOENT (No such file or directory)
+++ exited with 0 +++
```
if you remove the `-b` option, or change `localhost` to `127.0.0.1`, then it won't try to open that file.

And here is minimal libcurl program that you can conditionally enable cookie engine:
```c
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <curl/curl.h>

int main(int argc, char **argv)
{
	curl_global_init(CURL_GLOBAL_DEFAULT);
	CURL *curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:8069/");
	if (argc == 2 && argv[1][0] == '1')
		curl_easy_setopt(curl, CURLOPT_COOKIEFILE, ""); // enable cookie engine

	CURLcode res = curl_easy_perform(curl);
	if (res != CURLE_OK) {
		fprintf(stderr, "curl: %s\n", curl_easy_strerror(res));
		exit(EXIT_FAILURE);
	}

	printf("errno: %d\n", errno);

	curl_easy_cleanup(curl);
	curl_global_cleanup();
	return EXIT_SUCCESS;
}
```

```sh
$ strace -e newfstatat ./a.out 1 >/dev/null
newfstatat(AT_FDCWD, "/usr/local/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe1c3d7640, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe1c3d7640, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/lib/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/lib/glibc-hwcaps/x86-64-v3/", 0x7ffe1c3d7640, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/glibc-hwcaps/x86-64-v2/", 0x7ffe1c3d7640, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/publicsuffix/effective_tld_names.dat", 0x7ffe1c3d7b20, 0) = -1 ENOENT (No such file or directory)
errno: 2
+++ exited with 0 +++
```

### I expected the following

No random files are open. And `errno` is set to 0

### curl/libcurl version

```
curl 8.6.0 (x86_64-pc-linux-gnu) libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.59.0 nghttp3/1.2.0
Release-Date: 2024-01-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

```
Linux R3UB 6.7.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
I don't understand what you say the problem is. Is libcurl not doing what you ask it to do? If so, please elaborate.

The `effective_tld_names.dat` file is probably opened (and used) by the libpsl library, as it needs the PSL data and it can load that dynamically.

**Comment by jay** [comment]
This isn't a bug. errno may be set by any function even on success.

**Comment by dfandrich** [comment]
Even if libpsl can't find that file, it will use its internal database and run normally. If that file is missing, it's not necessarily an error.

**Comment by Harazi** [comment]
So how would I know if it was set by libpsl or there was an error in one of libc functions?

**Comment by Harazi** [comment]
Ideally, it should be set back to 0 by the caller

**Comment by dfandrich** [comment]
If you're looking for errors in the curl transfer, you should be looking at the
return code from curl_easy_perform(). libcurl can do all kinds of crazy things
under the hood that you don't need to worry about, but it will all be boiled
down to a CURLcode.

**Comment by Harazi** [comment]
yeah exactly, I expect if `CURLcode` equal `CURLE_OK`, then `errno` will also be 0.

I found the `stat` and `fopen` calls that don't reset `errno` in libpsl, I will send a patch there.

**Comment by dfandrich** [comment]
Not necessarily. The last operation that fails and sets errno might be (for
example) around the time of a socket close, but that doesn't matter for the
protocol and the operation still succeeds overall. I don't think libcurl makes
any guarantees about the state of errno after a transfer.

**Comment by bagder** [comment]
By definition errno should be checked **after an error** is returned from a function that is documented to also set errno. libcurl does not and will not guarantee any particular value in errno, because it does not provide information via that. Assuming anything else is a mistake.

**Comment by jzakrzewski** [comment]
Moreover - errno has absolutely no meaning if the last operation indicated success.
