### ISSUE TITLE
Missing cmake functionality for compile http3 with openssl and nghttp3

### ISSUE THREAD

**Issue by talregev** [curl/curl#12988]
Missing cmake functionality for compile http3 with openssl and nghttp:
This feature is done here: #12734 only in autoconf without support cmake functionality. 
Please implement cmake functionality for this option.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
