### ISSUE TITLE
Post a list of where the source files and how to compile libcurl using cl.exe directly.

### ISSUE THREAD

**Issue by AraHaan** [curl/curl#1299]
[ There are collections of known issues to be aware of:
  https://curl.haxx.se/docs/knownbugs.html https://curl.haxx.se/docs/todo.html ]

### I did this
I am trying to compile curlpp for C++ in an static library that would include an statically linked version of libcurl so that way I do not have to worry about DLL's And so that way the code would not reference DLL's not present in Windows like Windows XP or even in 32 bit Vista. Those DLL's that are normally Referenced in Visual Studio 2015 Since windows 7 and windows Vista x64 are ``api-ms-win-*.dll``. The issue is what if I am trying to target Windows XP, Vista, and 7+ without having to recompile on those older Windows versions that not everyone has?

### I expected the following
Documentation on what files and all to type in to the Developer Command prompt for compiling with cl.exe directly. Not to mention it does not mention where the actual source files to libcurl as an library can be located at for linking directly into my executable to avoid static linking if I wanted to do that as well.
### curl/libcurl version
latest master branch on github

[curl -V output perhaps?]
I have no use for the command line version of curl right now.
### operating system
Windows 7 Ultimate SP1 x64 Build 7601 (Has the latest C and C++ runtimes installed from Windows update)

**Comment by jay** [comment]
There are 4 ways to build static curl on Windows.

- **autotools** - see [docs/INSTALL.md](https://github.com/curl/curl/blob/curl-7_53_1/docs/INSTALL.md)
Example: `./configure --disable-shared --enable-static && make`
If you're building from the repo and not using release source you'll have to run `./buildconf` first.

- **CMake** - see [docs/INSTALL.cmake](https://github.com/curl/curl/blob/curl-7_53_1/docs/INSTALL.cmake)
Example: `cd .. && mkdir curlbuild && cmake ../curl -DCURL_STATICLIB=ON`

- **Premade Visual Studio projects** - see [projects/README](https://github.com/curl/curl/blob/curl-7_53_1/projects/README)
Example: `cd projects/Windows/VCxx && curl-all.sln` or just include `projects/Windows/VCxx/lib/libcurl.vcxproj` in your own solution. Choose a LIB configuration.
Though these are typically premade in common configs, if you're building from the repo and not using release source you'll have to generate them `buildconf.bat && cd projects && generate.bat`.

- **winbuild** - see [winbuild/BUILD.WINDOWS.txt](https://github.com/curl/curl/blob/curl-7_53_1/winbuild/BUILD.WINDOWS.txt)
Example: `cd winbuild && nmake /f Makefile.vc mode=static`

The source files for libcurl are located in lib. How this jives with curlpp I don't know, but it doesn't sound like a curl bug.

/cc @jpbarrette

**Comment by AraHaan** [comment]
Alright then so, I am going to try my best with invoking cl.exe with each one of those c files in lib. Thanks for the info where they are at. Would they in any way also require the files under ``include`` as well? Also this is needed because curlpp requires curl and the include files that curl comes with to build just to use curl with less code in C++ (it basically wraps it and takes all of the guess work out for me).

**Comment by jay** [comment]
> I am going to try my best with invoking cl.exe with each one of those c files in lib.

We have the aforementioned build methods to save you from that hassle; why not use one?

**Comment by AraHaan** [comment]
They all would reverence when building on the end result linking to files like ``api-ms-win-*.dll`` such files are not present on my Mom's 32 bit windows Vista. So it forces me to link using cl.exe directly.

**Comment by MarcelRaad** [comment]
@AraHaan I also used to build curl and curlpp statically, targetting Windows XP, and never had any problems. The VS project files of both libraries worked for me.
Have you selected the v140_xp toolset and set `_WIN32_WINNT` properly (you probably want 0x502 for Windows XP with SP2+)?

**Comment by rodwiddowson** [comment]
@aarHaan  Not sure what you are trying to achieve, but did you set the platform toolset and the CRTL DLLS correctly?

**Comment by jay** [comment]
If you compile curl using Visual Studio 2015 by default it's going to depend on Universal CRT api-ms-win-crt-*.dll and vcruntime140.dll. So if you then want to use that on your Vista computer you'll need these
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows
https://www.microsoft.com/en-us/download/details.aspx?id=53587

Please ask any further libcurl related questions on the [curl-library mailing list](https://cool.haxx.se/mailman/listinfo/curl-library).

**Comment by AraHaan** [comment]
Ok, Well that all helps and such but somehow I am now getting these errors when compiling:

    easy.c(343): error C2371: 'curl_easy_init': redefinition; different basic types
    e:\curl-master\include\curl\easy.h(28): note: see declaration of 'curl_easy_init'
    easy.c(862): error C2371: 'curl_easy_duphandle': redefinition; different basic types
    e:\curl-master\include\curl\easy.h(61): note: see declaration of 'curl_easy_duphandle'
    multi.c(355): error C2371: 'curl_multi_init': redefinition; different basic types
    e:\curl-master\include\curl\multi.h(123): note: see declaration of 'curl_multi_init'
    share.c(35): error C2371: 'curl_share_init': redefinition; different basic types
    e:\curl-master\include\curl\curl.h(2379): note: see declaration of 'curl_share_init'

I have no idea why right now.

**Comment by jay** [comment]
Ask on the list. You will need to be more specific, include some information about your build method and the source you are using so someone can try to reproduce.
