### ISSUE TITLE
Dropped --ftp-ssl

### ISSUE THREAD

**Issue by jordanbrown0** [curl/curl#13006]
### I did this

```
# curl --ftp-ssl
curl: option --ftp-ssl: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

```

### I expected the following

```
$ curl --ftp-ssl
Warning: --ssl is an insecure option, consider --ssl-reqd instead
curl: (2) no URL specified
curl: try 'curl --help' or 'curl --manual' for more information
```

### curl/libcurl version

# curl -V
curl 8.6.0 (x86_64-pc-solaris2.11) libcurl/8.6.0 OpenSSL/3.0.12 zlib/1.2.13 zstd/1.5.5 libidn2/2.3.0 libssh2/1.11.0 nghttp2/1.57.0 OpenLDAP/2.6.7
Release-Date: 2024-01-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Solaris 11.4 (development build)

**Comment by jordanbrown0** [comment]
Commit 9e4e527735bfd92132d102b2e7d102b8cb4f5a61 included C_FTP_SSL on the parse side, but did not include it in the switch.  (Perhaps because it appears to be an alias for `--ssl`; they were both coded as `$a` before the change.)

**Comment by bagder** [comment]
Confirmed. Fix coming. (`--ssl` has been the documented replacement option since 7.20.0.)
