### ISSUE TITLE
Torture test failure in test 56

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#13020]
### I did this

`make test TEST_Q='-a -p -n -t146 56'`

The test failed with:

```
test 0056...[HTTP POST with *HUGE* request and chunked transfer-encoding]
 166 functions to make fail
 system() returned 34304
 56: torture FAILED: function number 146 in test.
 invoke with "-t146" to repeat this single case.
```
 When run under gdb, the message:

`lt-curl: /home/dan/src/curl-git/lib/request.c:240: req_send_buffer_add: Assertion `(size_t)n == blen' failed.`

appears. The failure can also be seen in [this log](https://github.com/curl/curl/actions/runs/8105176164/job/22153092741). This line was last changed in commit 9369c30cd8 PR #12969 @icing 

### I expected the following

The test should pass the torture tests.

### curl/libcurl version

curl 8.7.0-DEV commit 89733e2dd

### operating system

Linux x86_64 glibc

**Comment by icing** [comment]
Nice find! Please see #13023 for the fix.
