### ISSUE TITLE
Curl tries to generate shell completions even when --without-*-functions-dir is given

### ISSUE THREAD

**Issue by av223119** [curl/curl#13027]
### I did this

After the commit 89733e2dd26b51c16b2c9f090881127dbba58ce8, curl tries to generate completions even when --without-*-functions-dir. This is bad when curl is built against the libraries residing in non-standard places:
```
./configure  --with-openssl=...   --without-zsh-functions-dir --without-fish-functions-dir
```
after the successful build, completion generation fails, as the linker couldn't find the libraries
```
make[1]: Entering directory 'curl/scripts'
if test -z "/usr/bin/perl"; then echo "No perl: can't install completion script"; else \
/usr/bin/perl ./completion.pl --curl ../src/curl --shell zsh > _curl ; fi
curl/src/.libs/curl: error while loading shared libraries: libssl.so.81.1.1: cannot open shared object file: No such file or directory
```

### curl/libcurl version

Curl 8.6.0 - 89733e2dd26b51c16b2c9f090881127dbba58ce8

### operating system

Ubuntu Linux

**Comment by dfandrich** [comment]
The --without-* flags still generate the completion files, but they're simply not installed in that case. curl is run using the normal libtool wrapper in src/curl so I don't know why it's not finding these libs. Are you able to run the test suite in this build configuration? Maybe it's broken all around.

It's probably safest to simply skip altogether the completion generation script step if the scripts have been disabled instead.

**Comment by BrianInglis** [comment]
Build no longer seems to default to build shell completions but requires explicit --with-fish-functions-dir and --with-zsh-functions-dir configure options specified! 
Was this the intent of the patch?

**Comment by dfandrich** [comment]
The old code didn't build shell completions by default, either, at least with configure;make;make install. What were you running that caused them to be built?

**Comment by BrianInglis** [comment]
We started installing shell completions in 2016-01 curl 7.47.0 without any config changes: 
https://cygwin.com/cgit/cygwin-packages/curl/commit/curl.cygport?id=ae7f8b46f2e6b74933da77e70df79be53c2523b3
and it only broke in 8.7.0/1 - we skipped the former!
