### ISSUE TITLE
curl command giving a format error in ubuntu 16.04

### ISSUE THREAD

**Issue by rajan-garg** [curl/curl#1307]
curl/libcurl version : 7.47.0

curl -V :
No download URL found!
File name: -V

operating system : Ubuntu 16.04.2 [LTS]

**command:** curl http://www.google.com
**output:** 
No download URL found!
File name: http://www.google.com

**command:** curl
**output:**
usage: curl [file] [URL]
            [file] [HTTP]     fetches a file from an 'http' URL
            [file] [HTTPS]    fetches a file from an 'https' URL
            [file] [FTP]      fetches a file from a 'ftp' URL

**Comment by jay** [comment]
Please do not post a screenshot of the output, simply copy it into this issue. Also the screenshot does not show anything. We need the `curl -V` and also the command line to reproduce.

**Comment by rajan-garg** [comment]
please check if this is fine.

**Comment by bagder** [comment]
I don't understand. What is the exact command line you used and what is the exact output from that?

**Comment by rajan-garg** [comment]
see this.

**Comment by bagder** [comment]
That looks like you have something else called curl that does those things. Those are not ordinary curl error outputs or behaviors. What does `which curl` show?

**Comment by rajan-garg** [comment]
/usr/local/bin/curl

**Comment by bagder** [comment]
So that's a custom curl, not the one shipped with Ubuntu. The ordinary one is installed in `/usr/bin/curl` and if you specify the full path to that you may get a different result.

**Comment by jay** [comment]
> So that's a custom curl, not the one shipped with Ubuntu.

It's a different curl...
https://pypi.python.org/pypi/curl/2016.2.1
https://github.com/cocodevienne/curl
@cocodevienne

**Comment by rajan-garg** [comment]
i didn't get it. i deleted curl from `/usr/local/bin/curl` . Now "which curl" output is `/usr/local/bin` , and error is still there.

**Comment by cocodevienne** [comment]
Guys how did you install my curl?? It can only be installed with Pip. And by executing `sudo apt-get install curl` you will get the normal always shipped with Linux, right?

**Comment by rajan-garg** [comment]
okay. i installed curl with sudo-apt get install curl, which installed this other curl. Downloading and installing curl from the official webstie worked for me. Thanks @jay

**Comment by cocodevienne** [comment]
How is that even possible?? @rajan-garg

**Comment by cocodevienne** [comment]
It's a python package!

**Comment by rajan-garg** [comment]
@cocodevienne  i might have installed curl with pip once in the past. and re-installing with apt was not replacing that curl.

**Comment by cocodevienne** [comment]
I should maybe rename it or something lol.

**Comment by cocodevienne** [comment]
@rajan-garg

**Comment by rajan-garg** [comment]
@cocodevienne  i removed that python curl and installed the correct curl. problem resolved!

**Comment by jay** [comment]
> I should maybe rename it or something lol.

@cocodevienne actually yes, it is not curl and there's a slew of scripts that depend on curl.
