### ISSUE TITLE
Report of ip & port number after entering passive ftp mode

### ISSUE THREAD

**Issue by DasKutti** [curl/curl#13084]
### I did this

Setup a ftps-connection with follow arguments:

%curl --user USERNAME:PASSWORD--disable-epsv  --ftp-pasv  --tlsv1.3   --ssl-reqd  --no-ftp-skip-pasv-ip -s  ftp:/ftp.somedomain.com/ -v

```
*   Trying 34.241.29.120:21...
* Connected to ftp.somedomain.com (34.241.29.120) port 21 (#0)
< 220 FTP Server ready.
> AUTH SSL
< 234 AUTH SSL successful
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
.
.
.
> PASV
* Connect data stream passively
* ftp_perform ends with SECONDARY: 0
{ [5 bytes data]
< 227 Entering Passive Mode (3,249,53,208,237,104).
* Connecting to 3.249.53.208 (3.249.53.208) port 60776
*   Trying 3.249.53.208:60776...
* Connected to ftp.somedomain.com  (34.241.29.120) port 21 (#0)
* SSL re-using session ID
```

### I expected the following

Confirmation of the connection with the new ip & destination port 
(here: ip 3.249.53.208 instead of (initial) 34.241.29.120  AND port 60776 instead of 21)

```
* Connected to ftp.somedomain.com  (3.249.53.208) port 60776 (#0)
```

### curl/libcurl version

%curl --version
curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.52.0 librtmp/2.3
Release-Date: 2023-02-20

### operating system

Ubuntu 23.04

**Comment by bagder** [comment]
Confirmed. It just repeats the same data from the primary connection...

**Comment by DasKutti** [comment]
Thank you @bagder .  It's just a very small thing. But perhaps there is still room for fix this.
