### ISSUE TITLE
Curl hangs with HTTP 2.0 request

### ISSUE THREAD

**Issue by etasse-cbsa** [curl/curl#13091]
### I did this

`curl https://server.example.com:3456/my-service/my-status`

### I expected the following

HTTP 200 OK
My Service status is running.

**Actual results:**
The process hangs

**Workarounds:**
1.  using --verbose, the process does not hang
2. using --http1.1, the process does not hang

### curl/libcurl version
`curl 8.6.0-1`
curl 8.6.0 (x86_64-w64-mingw32) libcurl/8.6.0 OpenSSL/3.2.1 (Schannel) zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7
libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0
Release-Date: 2024-01-31

### operating system
MINGW64_NT-10.0-19045 _REDACTED_ 3.4.10.x86_64 2024-02-10 08:39 UTC x86_64 Msys

**Comment by etasse-cbsa** [comment]
Note this is the same behavior in curl-windows:
```
curl 8.6.0 (x86_64-w64-mingw32) libcurl/8.6.0 LibreSSL/3.8.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.3.0 nghttp3/1.2.0
Release-Date: 2024-01-31
```

**Comment by icing** [comment]
Thanks for your report. You have to give us more detail in order to understand the problem, since you did not specify a public URL. If `curl -v` is unable to reproduce the problem, this is indeed tricky.

Any way for us to access the server you are testing with?

**Comment by etasse-cbsa** [comment]
@icing  > Any way for us to access the server you are testing with?

Unfortunately not. It's a protected server.  The only hint I can tell you is it is an IBM DataPower appliance server.
I will keep looking for a public server that exhibits the same behavior.

**Comment by bagder** [comment]
> Window10 fork of CURL defaults to HTTP1.1

It default to that because it does not know any later version. Most other curl installs know about HTTP/2 and will negotiate that over HTTPS by default.

**Comment by bagder** [comment]
Without transfer details and no way to reproduce, there is no way for us to act on this issue.
