### ISSUE TITLE
When CURLOPT_SSL_VERIFYPEER is set to "1", local cert does not verify.

### ISSUE THREAD

**Issue by enwillyado** [curl/curl#13099]
### I did this

Set `CURLOPT_SSL_VERIFYPEER` to `1`, local cert and `CURLOPT_SSLCERTTYPE` (PEM), `CURLOPT_KEYPASSWD`, `CURLOPT_SSLKEYTYPE` and `CURLOPT_SSLKEY`, and `CURLOPT_CAINFO` also.
I am using a local certificate **expired**.

I got `CURLE_OK `.

### I expected the following

`CURLE_SSL_CERTPROBLEM`, not `CURLE_OK`.

Probably, setting `CURLOPT_SSL_VERIFYPEER = 1L` is correct. Maybe `CURLOPT_SSL_VERIFYPEER = 2L` can use to implement both-side (local and remote certificates) verify, or create a new `CURLOPT_SSL_VERIFY(LOCAL)CERT`.

Server can reject request, but using a expired certificate is insecure.

### curl/libcurl version

Last.

### operating system

Linux.

**Comment by enwillyado** [comment]
Maybe this is a new feature, not a bug.

**Comment by bagder** [comment]
We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
