### ISSUE TITLE
Perl-collector is not working after Curl Upgrade

### ISSUE THREAD

**Issue by Suchi-P** [curl/curl#13109]
### I did this

Hello Team,

We have upgraded Curl from version 7.15.4 to 8.1.1 ; Tested in 3 different platforms : Linux, AIX and zLinux .
Seems to work in Linux and AIX but the perl collector fails in zLinux Platform , generates core dump .

Here is the stack of the generated core when debugged with gdb :
(gdb) bt
#0  0x000003ff80005c6c in ?? ()
#1  0x000003fffd378c7a in Curl_cache_addr () from ..../libNCPComms.so.1
#2  0x000003fffd379628 in Curl_resolv () from ..../libNCPComms.so.1
#3  0x000003fffd37996e in Curl_resolv_timeout ()
   from ..../libNCPComms.so.1
#4  0x000003fffd360f94 in Curl_connect () from ..../libNCPComms.so.1
#5  0x000003fffd34f42e in multi_runsingle () from ..../libNCPComms.so.1
#6  0x000003fffd3504ee in curl_multi_perform ()
   from ..../libNCPComms.so.1
#7  0x000003fffcfe53e4 in curlMulti_perform (envP=0x3fffb8aca78, curlMultiP=0xafc7f0e0, immediateWorkToDoP=0x3fffb8ac62c,
    runningHandlesP=0x3fffb8ac628) at curlmulti.c:139
#8  0x000003fffcfe3482 in doCurlWork (curlMultiP=<optimized out>, envP=<optimized out>, transStillRunningP=<optimized out>)
    at xmlrpc_curl_transport.c:539
#9  finishCurlMulti (envP=0x3fffb8aca78, curlMultiP=0xafc7f0e0, timeoutType=timeout_no, deadline=..., interruptP=0x0)
    at xmlrpc_curl_transport.c:602
#10 0x000003fffcfe451c in performRpc (interruptP=<optimized out>, curlMultiP=<optimized out>, rpcP=<optimized out>,
    envP=<optimized out>) at xmlrpc_curl_transport.c:1113
#11 call (envP=<optimized out>, clientTransportP=0xafc9aee0, serverP=<optimized out>, callXmlP=<optimized out>,
    responseXmlPP=0x3fffb8ac7d8) at xmlrpc_curl_transport.c:1489
#12 0x000003fffcfe2050 in xmlrpc_client_call2 (envP=0x3fffb8aca78, clientP=0xafc7c540, serverInfoP=0xafc7f370,
    methodName=<optimized out>, paramArrayP=0xafcb24e0, resultPP=0x3fffb8acaa8) at xmlrpc_client.c:607
#13 0x000003fffcfa1e7a in CDiscoXmlRpcAccess::CallMethod (this=<optimized out>, host=<optimized out>, port=8082,
    methodName=0x8000aa58 "GetInfo", signature=<optimized out>, args=..., maxResponseSize=52428800) at CDiscoXmlRpcAccess.cc:263
#14 0x0000000080009a5a in ?? ()

And here is the error found when checked log/trace of perl_collector process , where CollectorType, Host, Address etc seems to be NULL :
Seed in progress: reqType(-1), host(NULL), port(8082), sourceId(-1), address(NULL), mask(NULL), collectorType(NULL)
calling localhost:8082, GetInfo() )

Could you please help us to know , if the issue is specific to Curl or related to xmlrpc library [ As we are also working on to know if the versions of XMLRPC (1.25.25) and CURL(8.1.1) is not compatible for the specific platform ]

### I expected the following

Expected perl-collector to work as it is working with other 2 platforms

### curl/libcurl version

Curl 8.1.1

### operating system

zLinux

**Comment by bagder** [comment]
This is not enough for us to understand what happens, nor to reproduce the problem in our ends.

The general advice would be to make sure this follows [the threading guidelines](https://curl.se/libcurl/c/threadsafe.html), partly because the crash looks like one of those that sometimes happen when a handle is used cross-threads.

Also, I would recommend taking the jump all the way the latest curl release when at it.

**Comment by bagder** [comment]
> XMLRPC 1.25.25

That looks maybe twelve years old so maybe consider bumping up to a modern version for this as well? I could spot multiple curl related fixes in their changelog since your version was released.

**Comment by bagder** [comment]
No response
