### ISSUE TITLE
curl `--ipv6` on macOS will connect to an ipv4 address

### ISSUE THREAD

**Issue by jsoref** [curl/curl#13112]
### I did this

```sh
curl --no-progress-meter -6Iv ipv4.sidn.nl 2>&1 |grep ::
*   Trying [::ffff:212.114.120.63]:80...
* Connected to ipv4.sidn.nl (::ffff:212.114.120.63) port 80
```

### I expected the following

When I try to connect via ipv4 to an ipv6 only host, I get an error:
```sh
curl --no-progress-meter -4Iv ipv6.sidn.nl 2>&1
* Could not resolve host: ipv6.sidn.nl
* Closing connection
curl: (6) Could not resolve host: ipv6.sidn.nl
```

I'd expect to get an error when trying to connect via `--ipv6` to an ipv4 only host.

(I'm trying to use `--ipv6` to validate a remote server's support for ipv6, not my local kernel's ability to lie and do evil dual stack fallback stuff.)

### curl/libcurl version

curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets

### operating system

Darwin jsoref-mbp.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by bagder** [comment]
> *   Trying [::ffff:212.114.120.63]:80...
> * Connected to ipv4.sidn.nl (::ffff:212.114.120.63) port 80

This is an IPv6 address, a so called [IPv4-mapped address](https://en.wikipedia.org/wiki/IPv6_address#Transition_from_IPv4).

curl asks to resolve the name as IPv6-only and it gets an IPv6 address from the OS that it uses, and it works. I don't see what else curl can do here...

**Comment by jay** [comment]
is it though? it's IPv4 _mapped_. it's still IPv4 it's just making it look like IPv6 for compatibility

**Comment by bagder** [comment]
It is an IPv4 address mapped into an IPv6 address. IPv4 is 32 bit bit only, it couldn't have for the extra 16 bits of ffff in the beginning. So it is clearly partly IPv6-

**Comment by jay** [comment]
how about this
~~~diff
diff --git a/docs/cmdline-opts/ipv6.md b/docs/cmdline-opts/ipv6.md
index fbacbec..d4e9de1 100644
--- a/docs/cmdline-opts/ipv6.md
+++ b/docs/cmdline-opts/ipv6.md
@@ -22,3 +22,6 @@ Example:
 
 This option tells curl to use IPv6 addresses only when resolving hostnames,
 and not for example try IPv4.
+
+Note your resolver may respond to an IPv6-only resolve request by returning
+IPv6 addresses that contain "mapped" IPv4 addresses for compatibility purposes.
~~~

**Comment by bagder** [comment]
Yes, sensible. Maybe even highlight that macOS is known to do this.
