### ISSUE TITLE
curl -V shows wrong zlib version

### ISSUE THREAD

**Issue by firstrose** [curl/curl#1311]
Compile curl 7.53.1 with zlib 1.2.11

But curl -V shows it's using zlib 1.2.8
`curl 7.53.1 (i386-pc-win32) libcurl/7.53.1 zlib/1.2.8`
-----------------

curl 7.53.1
Mingw32
Windows 7 sp1

**Comment by bagder** [comment]
libcurl calls zlibVersion() to get that, so it is a string returned by zlib itself and thus if it is wrong you either built with the wrong version or zlib returns the wrong version.

**Comment by jay** [comment]
or an older zlib DLL is in your path and so that was loaded instead,

**Comment by firstrose** [comment]
Thank you.

I made a clean environment and got correct result. It looks that my mingw installation is polluted, a libz.a of 1.2.8 was linked.
