### ISSUE TITLE
Curl 8.2.0-DEV can't automatically redirect access in HTTP/3

### ISSUE THREAD

**Issue by jimmyZ0812** [curl/curl#13122]
### I did this

A web server that supports HTTP/3（QUIC).  When using curl accessing HTTP port 80, the web server will automatically redirect to HTTPS and the redirected port number is 8888, but I don’t know why curl still continues to access 443 instead of 8888. , I have used the -L  or --location parameter , but neither of them took effect. Not sure if this is a BUG? As a results ,please refer to below shown:

root@HTTP3-C:/home/a# 
root@HTTP3-C:/home/a# curl --http3 -v -L -k http://100.1.1.101
* processing: http://100.1.1.101
*   Trying 100.1.1.101:80...
* Connected to 100.1.1.101 (100.1.1.101) port 80
> GET / HTTP/1.1
> Host: 100.1.1.101
> User-Agent: curl/8.2.0-DEV
> Accept: */*
> 
< HTTP/1.1 302 Found
< Content-Length: 0
< Location: https://100.1.1.101/
< Alt-Svc: h3=":8888"
< Cache-Control: no-cache
< 
* Connection #0 to host 100.1.1.101 left intact
* Clear auth, redirects to port from 80 to 443
* Issue another request to this URL: 'https://100.1.1.101/'
*   Trying 100.1.1.101:443...
* QUIC: connection to 100.1.1.101 port 443 refused
* QUIC connect to 100.1.1.101 port 443 failed: Couldn't connect to server
* Failed to connect to 100.1.1.101 port 443 after 3 ms: Couldn't connect to server
*   Trying 100.1.1.101:443...
* connect to 100.1.1.101 port 443 failed: Connection refused
* Failed to connect to 100.1.1.101 port 443 after 3 ms: Couldn't connect to server
* Closing connection
curl: (7) QUIC: connection to 100.1.1.101 port 443 refused

### I expected the following

When curl receives http code 302 (redirect), it automatically accesses the corresponding URL and Port. Finally, QUIC can be used to establish an SSL handshake and get the correct page.

### curl/libcurl version

root@HTTP3-C:/home/a#curl -V
curl 8.2.0-DEV (x86_64-pc-linux-gnu) libcurl/8.2.0-DEV OpenSSL/3.0.9 ngtcp2/0.16.0 nghttp3/0.12.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

### operating system

Ubuntu 22.04.2 LTS

**Comment by jimmyZ0812** [comment]
For more, I tested that there is no problem when curl directly accesses the 8888 port of HTTP/3.
root@HTTP3-C:/home/a# curl --http3 -v -k https://100.1.1.101:8888
* processing: https://100.1.1.101:8888
*   Trying 100.1.1.101:8888...
* Skipped certificate verification
* Connected to 100.1.1.101 (100.1.1.101) port 8888
* using HTTP/3
* Using HTTP/3 Stream ID: 0
> GET / HTTP/3
> Host: 100.1.1.101:8888
> User-Agent: curl/8.2.0-DEV
> Accept: */*
> 
< HTTP/3 200 
< etag: "11-65ea6eb5-d7df;;;"
< last-modified: Fri, 08 Mar 2024 01:49:41 GMT
< content-type: text/html
< content-length: 17
< accept-ranges: bytes
< date: Thu, 14 Mar 2024 01:39:25 GMT
< server: LiteSpeed
< alt-svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, quic=":443"; ma=2592000; v="43,46"
< 
welcome to http3
* Connection #0 to host 100.1.1.101 left intact

**Comment by bagder** [comment]
The redirect does not mention port 8888. It uses a plain `https://` URL, which means port 443.

Port 8888 is in the alt-svc header and your command line does not tell curl to use alt-svc. You want `--alt-svc` for that.

**Comment by jimmyZ0812** [comment]
> The redirect does not mention port 8888. It uses a plain `https://` URL, which means port 443.
> 
> Port 8888 is in the alt-svc header and your command line does not tell curl to use alt-svc. You want `--alt-svc` for that.

Thanks Daniel for your quick reply. It has been confirmed that the http3 web server `location` field does not carry a port number. Thank you very much~
