### ISSUE TITLE
call the function curl_easy_getinfo error, when info is CURLINFO_STARTTRANSFER_TIME_T, the out param arg always is 0.

### ISSUE THREAD

**Issue by chensong1211** [curl/curl#13125]
### curl/libcurl version

curl 8.6.0

### operating system

Linux

**Comment by icing** [comment]
My test with curl 8.6.0 gives:

```
> curl -s -w '%{time_starttransfer}\n' https://curl.se -o /dev/null
0.054088
```

You'd have to give us more details or what you are doing and how to reproduce.

**Comment by chensong1211** [comment]
When I use curl to send a request, I use curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, OnHeaderCallback) to obtain CURLINFO_STARTTRANSFER_TIME_T in the OnHeaderCallback callback function. In version 8.4.0, I can obtain data. In version 8.6.0, The obtained data is always 0. When I try to obtain the data at the time of CURLOPT_XFERINFO FUNCTION, I can obtain the data normally.

**Comment by icing** [comment]
Thanks! I see that we indeed did set CURLINFO_STARTTRANSFER_TIME_T in 8.6.0 *after* the headers were received. In the current 8.7.0-dev we set it on the first header.

Would you be able to build the current development version yourself for verification? I'll work on adding a test case for this, so we'll not miss this in the future.

**Comment by chensong1211** [comment]
ok,i will.
Thank you for your reply.

**Comment by icing** [comment]
Added a test case for this in #13128.

**Comment by bagder** [comment]
This issue is actually already fixed in git.

**Comment by icing** [comment]
> This issue is actually already fixed in git.

Yes, but it did not have a test case.
