### ISSUE TITLE
request www.java.com  curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by ddatsh** [curl/curl#13123]
### I did this

curl  -L "https://www.java.com" -v

and get

curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### I expected the following

request success

### curl/libcurl version

curl 7.76.1

### operating system

AlmaLinux release 9.3 (Shamrock Pampas Cat)

**Comment by ddatsh** [comment]
> ### I did this
> curl -L "https://www.java.com" -v
> 
> and get
> 
> curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
> 
> ### I expected the following
> request success
> 
> ### curl/libcurl version
> curl 7.76.1
> 
> ### operating system
> AlmaLinux release 9.3 (Shamrock Pampas Cat)

----------------------
compile curl 8.6.0  hang 
 ./curl https://www.java.com -v
* Host www.java.com:443 was resolved.
* IPv6: 2600:1417:4400:c::1721:7e37, 2600:1417:4400:c::1721:7e3a
* IPv4: 23.44.175.188, 23.44.175.187
*   Trying 23.44.175.188:443...
*   Trying [2600:1417:4400:c::1721:7e37]:443...
* Immediate connect fail for 2600:1417:4400:c::1721:7e37: Network is unreachable
*   Trying [2600:1417:4400:c::1721:7e3a]:443...
* Immediate connect fail for 2600:1417:4400:c::1721:7e3a: Network is unreachable
* Connected to www.java.com (23.44.175.188) port 443
* ALPN: curl offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=Redwood City; O=Oracle Corporation; CN=java.com
*  start date: Oct 14 00:00:00 2023 GMT
*  expire date: Oct 16 23:59:59 2024 GMT
*  subjectAltName: host "www.java.com" matched cert's "www.java.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: www.java.com
> User-Agent: curl/8.6.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing

**Comment by bagder** [comment]
This looks like a server issue. Does other clients work with this site? It fails with HTTP/2 and it hangs with HTTP/1, even the latest curl.

**Comment by ddatsh** [comment]
> This looks like a server issue. Do other clients work with this site? It fails with HTTP/2 and it hangs with HTTP/1, even the latest curl.

brower like chrome,   http://www.java.com  works
postman  also works
don't know  server issue to effect curl result
and i try golang , also fail
```go
package main

import (
	"fmt"

	"net/http"
)

func main() {
	_, err := http.Get("https://www.java.com")
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

https://github.com/golang/go/issues/66306

**Comment by bagder** [comment]
I'm pretty sure this is the server playing tricks.

I did a copy-as-curl with Firefox, and using that monster command line **it works**:

----

curl 'https://www.java.com/' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: AKA_A2=A; ak_bmsc=6681C0FF4DBD6745B7DFA9CB3EF2FA72~000000000000000000000000000000~YAAQjIVlX2nClzaOAQAAClL8OxfEBh0PnDITl2PA+LWfEd5ml5B1JW5wv1jjks3wwQMNXFqsou70FL0BVNgdkc/9JMJ6bbLGFw8dbqjfVadIMIwRVGte7eQUf0AsKutPQBjtwsvYVa5Jjh1iPhFVC8Ep//MkpOAkYVuy5prgOBG+noNjKdW+UYir+K0OA/rKdSD1F4qY80QZYugAqWGS/Zx1wNMegbGqMFd6DdKUaJXx2I1IrpXmJM8VXy12ErzcvZiETM1He7/DN0nhLrcqwjR1UmjLIC4vUm37Q/ydy0fLeTEPTf8spv07qMlIFDk3LoHkHivziSY4wHJDrtuD+dblItKojekKAazChVDd6NcsJ6yqSLK1l+pw/TtZnXhX0oP+52jWfOdCDhqBCo/ZnvLo9TDcKc5m/onIvUv+HIs=; bm_sv=B15F8F6CE45D83858C43141055E78185~YAAQjIVlX3/ClzaOAQAAh1b8Oxf5EO+3acooyoNiEHDivMNEW7dTbwmb9FYWQEurSLttbCaXNcCncbTQ68X41Q0e3ECAD7dZFsp463v0o6jmNH9ahcfXX02kxHs1ABp71SJkQhH6Eyh8AbQvghsyTN9mkwZJIj8zfzNii7lsUkr6SVaITB/IVPudniKrFLAscV95j+6jsu+ZF5UVxNt9Cq9fgfH+BY1Zr5+O8jvU8KQc5qffNn9smvkQkCrcDA==~1; ORA_FLEX_CACHE_KEY=desktop-firefox_123-linux; TAsessionID=da35cde5-8a94-4e05-96d0-7136dea60a7a|NEW; notice_behavior=expressed,eu; bm_mi=8B015D1808056E1B85494C14D6B36E2D~YAAQjIVlX3nClzaOAQAA7lT8OxdtwoNmbcambKY8qigZmJ5YLf4hMNvoHApcCMZknWOjkEcXhB4yAIjYAlIEZQgFa1XHHhL/nFjP7LL2QPvPWMW3mpS2KptZw1t8fL5akkwRI37y+IZXRI1PAQ40v9ShGy+8jdUjU2pimgX9CYWPElfmHauqTaPeilSDpf9CZ9AjhZY+srkfbDIcS3GLvy+pK+JndCjJaf8AnqgayUu91TTwJGfxdFPaAq1KTM45bjiTHxEjhxuzvOpayizenH5jArw55DonY2+ETg6vgbXxsmthcOqrG0H6P9z8XBqoPHedk+l46jWtVh/1+6vvePW1iTqj+0CzYlZEEoBRrksMyz3cZqfbdY5madRvonpW+nKOebbNcn6w17M5Xqks9Q==~1' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'TE: trailers'
