### ISSUE TITLE
Error when configuring Curl project in `makefile.inc.cmake` transform

### ISSUE THREAD

**Issue by DISAPPEARED13** [curl/curl#13148]
### I did this

I figured the CURL in the Slicer, and errors occur below:

```
11>CMake Error at C:/Slice/Slicer-build2/curl-build/lib/Makefile.inc.cmake:1:
11>  Parse error.  Expected a command name, got unquoted argument with text
11>  "%TSD-Header-".
11>Call Stack (most recent call first):
11>  lib/CMakeLists.txt:36 (include)
11>
11>
11>-- Configuring incomplete, errors occurred!
```

after this, I tried to configure CURL on my own with the source code, and errors still occurs. I tried to ignore the code

```
transform_makefile_inc("Makefile.inc" "${CMAKE_CURRENT_BINARY_DIR}/Makefile.inc.cmake")
include(${CMAKE_CURRENT_BINARY_DIR}/Makefile.inc.cmake)
```
But LNK errors occurs, so I just cannot fix the CMakeList.txt on my own.

Inside the Makefile.inc.cmake:
```
%TSD-Header-###%?0!佩?毆d jR黟  €           @   茀R? 偱P 腔T
鵼It谮使???縋8 5?_?鲴剙W
饮獛籒z1E酝w_R$錏<G潧@?dF/?
```

### I expected the following

I can configure the CURL project and successfully build the project, which will be used in slicer.

### curl/libcurl version

curl 8.6.0

### operating system

Windows10 64bit 
with VS2017 MSVC 19.16.27050.0

**Comment by bagder** [comment]
I don't know what this means or even what is attempted here. I trust someone who knows more cmake than me can respond.

**Comment by DISAPPEARED13** [comment]
> I don't know what this means or even what is attempted here. I trust someone who knows more cmake than me can respond.

Thanks for your reply! 
But do you know that is it the `Makefile.inc.cmake` hex format, or it's just my system problem like encrypted? Big thanks again!

**Comment by bagder** [comment]
They are all plain text file as far as I can see:

~~~shell
$ find . -name Makefile.inc.cmake
./docs/cmdline-opts/Makefile.inc.cmake
./docs/libcurl/Makefile.inc.cmake
./lib/Makefile.inc.cmake
$ file `find . -name Makefile.inc.cmake`
./docs/cmdline-opts/Makefile.inc.cmake: ASCII text
./docs/libcurl/Makefile.inc.cmake:      ASCII text
./lib/Makefile.inc.cmake:               ASCII text


~~~

**Comment by jay** [comment]
TSD header appears to be some sort of encryption marker according to google, but in the links I read nobody is sure exactly what it is.

I don't see how it could happen with just our code.

https://github.com/curl/curl/blob/5ce164e0e9290c96eb7d502173426c0a135ec008/CMakeLists.txt#L1460-L1474

**Comment by DISAPPEARED13** [comment]
> TSD header appears to be some sort of encryption marker according to google, but in the links I read nobody is sure exactly what it is.
> 
> I don't see how it could happen with just our code.
> 
> https://github.com/curl/curl/blob/5ce164e0e9290c96eb7d502173426c0a135ec008/CMakeLists.txt#L1460-L1474

Thanks for all you guys reply. 
After times of check running it seems encryption problem is the reason why, after re-download the code from here instead of auto-generating code from Slicer, seems `makefile.inc.cmake` is correct now...

**Comment by DISAPPEARED13** [comment]
The final problem seems that, if `makefile.inc.cmake` is encryted, or shows weird code like `TSV-header` etc, (maybe sth else based on the language you used), better check inside the download code directory( `\lib\Makefile.inc`). If it's correct, curl's building seems fine.
