### ISSUE TITLE
CMake error building libcurl 8.6.0 with OpenSSL QUIC enabled

### ISSUE THREAD

**Issue by yushicheng7788** [curl/curl#13146]
### I did this

I used CMake to generate CURL xcode project by running follow commands:
```cmake
cmake ${PROJECT_DIR} -G "Xcode" \
    -DCMAKE_SYSTEM_NAME=Darwin \
    -DCMAKE_OSX_ARCHITECTURES=${ARCH} \
    -DCMAKE_OSX_DEPLOYMENT_TARGET="10.10" \
    -DCMAKE_INSTALL_PREFIX=${OUTPUT_DIR} \
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} \
    -DBUILD_CURL_EXE=OFF \
    -DCURL_HIDDEN_SYMBOLS=OFF \
    -DCURL_DISABLE_LDAP=ON \
    -DCURL_DISABLE_LDAPS=ON \
    -DCURL_USE_GSSAPI=ON \
    -DBUILD_SHARED_LIBS=${BUILD_SHARED} \
    -DOPENSSL_ROOT_DIR="${path of openssl}" \
    -DOPENSSL_CRYPTO_LIBRARY="${path of libcrypto.dylib}" \
    -DOPENSSL_SSL_LIBRARY="${path of libssl.dylib}"\
    -DCURL_USE_OPENSSL=ON \
    -DUSE_OPENSSL_QUIC=ON \
    -DUSE_NGTCP2=ON \
    -DNGHTTP3_LIBRARY="${path of libnghttp3.dylib}" \
    -DNGHTTP3_INCLUDE_DIR="${path of nghttp3 include dir}"
``` 
But there is a cmake error: **CMake Error at CMakeLists.txt:686 (message):
  QUIC support is missing in OpenSSL/LibreSSL/BoringSSL/wolfSSL.  Try setting
  -DOPENSSL_ROOT_DIR** when looking for SSL_CTX_set_quic_method. I noticed that we are looking for SSL_CTX_set_quic_method in openss/ssl.h, but in openssl version 3.2.0, there is no method named this.

### I expected the following

I expected the CMake commands work fine.

### curl/libcurl version

curl 8.6.0
openssl 3.2.0

### operating system

Darwin

**Comment by icing** [comment]
Not a cmake expert here, but

```
    -DUSE_OPENSSL_QUIC=ON \
    -DUSE_NGTCP2=ON \
```

will not work together. `ngtcp2` needs an SSL library like quictls/gnutls/boringssl and OpenSSL 3.2.*'s QUIC implementation does not work with `ngtcp2`.

**Comment by yushicheng7788** [comment]
@icing Thanks. I misunderstood the build method in https://curl.se/docs/http3.html. I will delete -DUSE_NGTCP2=ON and retry it.

**Comment by vszakats** [comment]
OpenSSL QUIC / `USE_OPENSSL_QUIC` support in CMake will arrive in 8.7.0, via #13034.

Earlier curl versions did not support it.

**Comment by vszakats** [comment]
Please retry and report with 8.7.1, where this has been shipped now.
