### ISSUE TITLE
 error: call to '_curl_easy_setopt_err_seek_cb' declared with attribute warning: curl_easy_setopt expects a curl_seek_callback argument for this option

### ISSUE THREAD

**Issue by nirvikb** [curl/curl#13160]
### I did this

static int seek_data_buf(void *arg, curl_off_t offset, int origin) {
...
}

foo() {
...
        cc = curl_easy_setopt(handle, CURLOPT_SEEKFUNCTION,  seek_data_buf);
...
}

The compilation failed with error:
error: call to '_curl_easy_setopt_err_seek_cb' declared with attribute warning: curl_easy_setopt expects a curl_seek_callback argument for this option [-Werror=attribute-warning]
  716 |         cc = curl_easy_setopt(handle, CURLOPT_SEEKFUNCTION,
      |              ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

### I expected the following

I expected compilation to succeed

### curl/libcurl version

curl 7.29.0

### operating system

oracle linux 9

**Comment by dfandrich** [comment]
I don't think you'll find much enthusiasm here for looking into a bug report on
a curl version that just celebrated its 11th birthday. Can you reproduce this
on 8.6.0?

**Comment by bagder** [comment]
This issue does not exist in modern versions.
