### ISSUE TITLE
Combined -XGET and --head gives ''curl: (8) Weird server reply"

### ISSUE THREAD

**Issue by davenonymous** [curl/curl#13170]
### I did this

The behavior of running `curl -XGET --head "https://google.de"` changed somewhere between 8.4.0 and 8.6.0.

### I expected the following

With the older version there was no error reported and the exit code was 0.
With the newer version it throws 'Weird server reply' with exit code 8.

The regression also results in `--location` not being respected anymore, e.g.
`curl -XGET --head --location --write-out '%{http_code}' "https://google.de"` now writes 301 instead of the expected 200.

Simply removing the `--head` option resolves this issue for us, but I assume this behavior was not intended.

### curl/libcurl version

curl 8.6.0 (x86_64-pc-linux-gnu) libcurl/8.6.0 OpenSSL/1.1.1v zlib/1.2.11 zstd/1.5.5 libidn2/2.0.5 libpsl/0.21.5 OpenLDAP/2.4.48
Release-Date: 2024-01-31

### operating system

Linux zk1 6.6.16-cx #1 SMP PREEMPT_DYNAMIC Tue Feb  6 12:18:09 CET 2024 x86_64 GNU/Linux

**Comment by bagder** [comment]
I cannot reproduce. It does not happen to me, not with 8.6.0 in debian nor with my current git build.

**Comment by davenonymous** [comment]
Odd. Maybe some issue with our build. I'll bisect and report back.

**Comment by bagder** [comment]
So what does the server respond to you? What does -v say?

**Comment by davenonymous** [comment]
```
 $ curl -v -XGET --head "https://google.de"
* Host google.de:443 was resolved.
* IPv6: 2a00:1450:4001:829::2003
* IPv4: 142.250.186.99
*   Trying 142.250.186.99:443...
* Connected to google.de (142.250.186.99) port 443
* ALPN: curl offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: none
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.google.de
*  start date: Feb 26 08:21:09 2024 GMT
*  expire date: May 20 08:21:08 2024 GMT
*  subjectAltName: host "google.de" matched cert's "google.de"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type ? (256/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type ? (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type ? (4096/128 Bits/secBits), signed using sha384WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: google.de
> User-Agent: curl/8.6.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Location: https://www.google.de/
Location: https://www.google.de/
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-v5uxL-I-t_HGKB8lUcqUzg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-v5uxL-I-t_HGKB8lUcqUzg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< Date: Fri, 22 Mar 2024 10:45:58 GMT
Date: Fri, 22 Mar 2024 10:45:58 GMT
< Expires: Sun, 21 Apr 2024 10:45:58 GMT
Expires: Sun, 21 Apr 2024 10:45:58 GMT
< Cache-Control: public, max-age=2592000
Cache-Control: public, max-age=2592000
< Server: gws
Server: gws
< Content-Length: 219
Content-Length: 219
< X-XSS-Protection: 0
X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

<
* Closing connection
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (8) Weird server reply
```

**Comment by davenonymous** [comment]
d7b6ce64ce0ad787ad2ed3ee05c94938a6b4f551 is the first bad commit.
b8c003832d730bb2f4b9de4204675ca5d9f7a903 fixes it again.

**Comment by davenonymous** [comment]
Yupp. I've applied the patch to our build and the issue is resolved. Our particular testcase is happy again.
Sorry for alarming about an already fixed issue.

**Comment by joanhey** [comment]
We have the same problem with the HEAD method. But only in some CURL versions.

We use CURL with PHP to test server responses. Before was working OK, but after update the CURL version in MacOS and windows it is failing with error: `(8) Weird server reply`.

We added the CURL version used, to find the problem, because before was working OK.

### GH Action
https://github.com/joanhey/AdapterMan/actions/runs/8053477301


- Curl/7.81.0 is working OK. (Ubuntu 22.04)
  https://github.com/joanhey/AdapterMan/actions/runs/8053477301/job/21995979834#step:5:10

- Curl/8.4.0 is woking OK. (Windows 10)
  https://github.com/joanhey/AdapterMan/actions/runs/8053477301/job/21995980945#step:5:11

- Curl/8.6.0 fail (MacOS and Windows 10)
  https://github.com/joanhey/AdapterMan/actions/runs/8053477301/job/21995981263#step:5:11

  https://github.com/joanhey/AdapterMan/actions/runs/8053477301/job/21995981263#step:5:11
  `cURL error 8:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by joanhey** [comment]
Tested sending body and headers, and only headers, always fail with `error 8`.

If we don't send the `Content-Length` header, don't show the error.

**Comment by davenonymous** [comment]
> If we don't send the `Content-Length` header, don't show the error.

That matches what the b8c003832d730bb2f4b9de4204675ca5d9f7a903 patch fixes:
```diff
--- a/lib/sendf.c
+++ b/lib/sendf.c
@@ -575,6 +575,9 @@ static CURLcode cw_download_write(struct Curl_easy *data,
     DEBUGF(infof(data, "did not want a BODY, but seeing %zu bytes",
                  nbytes));
     data->req.download_done = TRUE;
+    if(data->info.header_size)
+      /* if headers have been received, this is fine */
+      return CURLE_OK;
     return CURLE_WEIRD_SERVER_REPLY;
   }

```

**Comment by joanhey** [comment]
We can test a new CURL version in GH actions, when ready!!

**Comment by bagder** [comment]
As mentioned, this is already fixed (in git). The next release ships on March 27.
