### ISSUE TITLE
8.7.0 archives seems to have a mostly empty tool_hugehelp.c file

### ISSUE THREAD

**Issue by bs6mjb** [curl/curl#13195]
### I did this

Built libcurl on windows x64 using Visual Studio 2019 and nmake 

### I expected the following

Build to complete successfully but actually got a linker error for unresolved external symbol hugehelp referenced in function operate. I was able to resolve by copying the complete file from 8.6.0

### curl/libcurl version

curl 8.7.0

### operating system

Windows 10 64

**Comment by bagder** [comment]
Sorry for my mess. Try the 8.7.1 just uploaded.

**Comment by bs6mjb** [comment]
No worries - you are doing a fantastic job and it is much appreciated.
8.7.1 works perfectly - thank you!

**Comment by bagder** [comment]
Thanks for verifying!
