### ISSUE TITLE
Man page tests 1140 and 1173 fail on cmake

### ISSUE THREAD

**Issue by dfandrich** [curl/curl#13194]
These two tests when run via cmake fail. We have a few CI builds that run a failing configuration (on Appveyor), except that they explicitly disable these two tests so we don't see the failures. In tree and out-of-tree doesn't seem to matter. Old cmake or new cmake doesn't seem to matter. It shows for me with a plain-Jane cmake build:

`cmake . && make -j9 && make -j9 test-ci TFLAGS='1140 1173'`

(it fails without the TFLAGS, too; this is just quicker). It also fails on an Ubuntu 22.04 container with the minimum packages needed to build installed.

I'm completely confused as to why nobody else has reported this because my testing shows it happens in any cmake build. Does absolutely nobody using cmake run the test suite? Or do they all (including us, it seems) just disable those tests and go on with their day?

Here's an example failure log: https://github.com/curl/curl/actions/runs/8440831621/job/23118626767?pr=13029

_Originally posted by @dfandrich in https://github.com/curl/curl/issues/13028#issuecomment-1984253530_

**Comment by bagder** [comment]
It appears that it lacks generated manpage(s) where the tests looks for them...

**Comment by vszakats** [comment]
The actual errors:
```
 test1140.pl could not open [...]/curl/_bld/tests/../docs/*.1 at [...]/curl/tests/test1140.pl line 59.
 test1173.pl could not open [...]/curl/_bld/tests/../docs/*.1 at [...]/curl/tests/test1173.pl line 135.
```
Indeed, there is no `.1` file generated in the `docs` dir (`curl.1` is under `docs/cmdline-opts`). What other `.1` file is this test looking for there?

**Comment by bagder** [comment]
autotools builds generate `curl-config.1` and `mk-ca-bundle.1` there.

**Comment by vszakats** [comment]
Oh, right. I think CMake never had any logic to build these two. It also never distributed `mk-ca-bundle.pl`.

Patch attempt: #13197
