### ISSUE TITLE
Bug when using curl https://k08.chatzi.org/vscode/config.sh | bash

### ISSUE THREAD

**Issue by YiannisMpla** [curl/curl#13192]
### I did this

Hey,
I m an university student studying programming. In order to download the VSCode extensions we will need in a certain lesson, our instructor has sent us this command: curl https://k08.chatzi.org/vscode/config.sh | bash which we have to paste at our ubuntu (wsl for windows) app so the extensions will be added to our VSCode apps. Though the command isnt working for me and I get the following message instead: The installation directory /mnt/c/Users/ does not exist, aborting.
Please create it and try again. I ve searched it and on my pc there do exist the folders mnt/c/Users. Can u help me with that;;

### I expected the following

I expected the command to work and my vscode extensions to have been downloaded.

### curl/libcurl version

curl 8.6.0

### operating system

Windows 10

**Comment by bagder** [comment]
This is not a curl problem. curl gets the file just fine and sends it into bash, but then the script apparently finds a problem and reports that. That's a problem with the script and/or your setup. curl did its job.

**Comment by YiannisMpla** [comment]
Its not  a script problem as my other classmates can dowlnoad these extensions without any problem. Can u help me fix it cause i guess  its a setup problem or i should adress someone else?

**Comment by dfandrich** [comment]
It's a script problem. Your classmates are running the script on other
computers than yours. You will need to download the script and analyze it to
see where it goes wrong. You can start by piping it to "bash -x" to see a verbose
log of all the commands that are run so you can see better where it fails.
