### ISSUE TITLE
Certificate verification error message not informative enough with curl API

### ISSUE THREAD

**Issue by pitrou** [curl/curl#13199]
### I did this

Using the curl command line gives an informative error message when a certificate validation error occurs:
```console
$ curl --cacert ./t/miniocert/public.crt  https://127.0.0.1:9000
curl: (60) SSL: no alternative certificate subject name matches target host name '127.0.0.1'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

However, fetching the same URL using the API seems to return a more generic error message. Here I'm using libcurl through PyArrow and the AWS SDK for C++:
```python
>>> os.environ['SSL_CERT_FILE']
'/home/antoine/t/miniocert/public.crt'
>>> fs = S3FileSystem(endpoint_override="127.0.0.1:9000", scheme="https", access_key="minioadmin", secret_key="minioadmin")
>>> fs.get_file_info(FileSelector('', recursive=True))
Traceback (most recent call last):
  [...]
OSError: When listing buckets: AWS Error NETWORK_CONNECTION during ListBuckets operation: curlCode: 60, SSL peer certificate or SSH remote key was not OK
```

Both error messages ("no alternative certificate subject name matches target" and "SSL peer certificate or SSH remote key was not OK") seem to stem from different places in the libcurl source code. The former is from  `lib/vtls/openssl.c` and the latter is from `lib/strerror.c` .

### I expected the following

I would hope the curl API to provide the same insightful error message. The generic error message is not informative enough for users.

Downstream issue reference: https://github.com/apache/arrow/issues/37001#issuecomment-2022451857

### curl/libcurl version

libcurl 8.6.0

### operating system

Ubuntu 22.04

**Comment by bagder** [comment]
This is not a curl bug, this is the application not using CURLOPT_ERRORBUFFER while the curl command line tool does.

**Comment by pitrou** [comment]
Ahah, thanks for the reply! I'll have to move this to the AWS SDK bug tracker  then.
