### ISSUE TITLE
libcurl v7.53.1 cannot establish SSL connection to IMAP server through Proxy

### ISSUE THREAD

**Issue by abcdxwz** [curl/curl#1319]
Hi, guys

I receive SSL error when trying to connect IMAP Server:
```
Unknown SSL protocol error in connection to imap.serverMail.net:187
```
From my point of view libcurl mixes Server URL and Proxy port.

## C++ code snipped
IMAP server request:

```
curl_easy_setopt(curl_handle, CURLOPT_PROXY, http_proxy_host);
curl_easy_setopt(curl_handle, CURLOPT_PROXYPORT, http_proxy_port);

curl_easy_setopt(curl, CURLOPT_USERNAME, "nameUser");
curl_easy_setopt(curl, CURLOPT_PASSWORD, "pass");
curl_easy_setopt(curl, CURLOPT_LOGIN_OPTIONS, "AUTH=PLAIN");

curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

curl_easy_setopt(curl, CURLOPT_URL, "imaps://imap.serverMail.net:993");
```

### Result
```
"proxy host: 127.0.0.3"
"proxy port: 187"

* About to connect() to proxy 127.0.0.3 port 187 (#0)
*   Trying 127.0.0.3...
* connected
* Connected to 127.0.0.3 (127.0.0.3) port 187 (#0)
* Establish HTTP proxy tunnel to imap.serverMail.net:993
* Server auth using Basic with user 'nameUser'
> CONNECT imap.serverMail.net:993 HTTP/1.1
Host: imap.serverMail.net:993
Proxy-Connection: Keep-Alive

< HTTP/1.0 200 Connection established
<
* Proxy replied OK to CONNECT request
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/openssl/certs
* Unknown SSL protocol error in connection to imap.serverMail.net:187
* Closing connection #0
* SSL connect error
```

## When I do this request from CLI - it works
curl --insecure --url "imaps://imap.serverMail.net:993" --user "nameUser:pass" --login-options "auth=PLAIN"

```
* LIST (\Marked \HasNoChildren) "/" Archive
* LIST (\Marked \HasNoChildren) "/" INBOX
…
```

## My device is:
Operating system:  blackberry10

curl --version
```
curl 7.53.1 (arm-unknown-nto-qnx8.0.0eabi) libcurl/7.53.1 OpenSSL/1.0.1l zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```
Thanks

**Comment by bagder** [comment]
Agreed - based on your output! The code is here: https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L2310

The slightly misleading macro `SSL_IS_PROXY` there should return true if a HTTPS proxy is used so I'm a bit puzzled why it seems to show the `conn->host.name` (which seems like a correct choice) but not the port number from `conn->remote_port`! Can you figure that out?

**Comment by bagder** [comment]
@abcdxwz, it'd be great if you could help us out here!

**Comment by abcdxwz** [comment]
Hi, Daniel
It is HTTP proxy inside mobile device and I make tunnel to access IMAPs server.

I have made further research and found that I can connect to some servers and cannot for others.
In case when connection could not be established error message was:
```
Unknown SSL protocol error in connection to imap.serverMail.net:portProxy
```
The reason I was confused: in the message Server URL and Proxy port are mixed.

#### Now I see this as:
When we cannot connect to the Server we get incorrect Error message.

**Comment by jay** [comment]
> When we cannot connect to the Server we get incorrect Error message.

The "Unknown SSL protocol error" has now been changed to show the internal SSL_ERROR code instead when no detailed error is available. If you build from master and try to connect what error does it show?

**Comment by abcdxwz** [comment]
Hi, Jay

curl_easy_strerror():
```
SSL connect error
```
curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, … ):
```
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to imap.serverMail.net:993
```
libcurl version:    7.54.0-DEV

The Server URL and Port match each other.

**Comment by jay** [comment]
Ok. Maybe the server is overloaded or doesn't share any ciphers in common.

**Comment by abcdxwz** [comment]
I don't know the reason of the error. But seems that curl does its work now and I should turn my mind to OpenSSL. Thanks.

**Comment by mkauf** [comment]
The example code does not set ``CURLOPT_HTTPPROXYTUNNEL`` explicitly, but a tunnel will be used anyway because it's an SSL connection:
```
/*************************************************************
 * If the protocol is using SSL and HTTP proxy is used, we set
 * the tunnel_proxy bit.
 *************************************************************/
if((conn->given->flags&PROTOPT_SSL) && conn->bits.httpproxy)
  conn->bits.tunnel_proxy = TRUE;
```

In ``imap_setup_connection()``, there's this code (some "ifdef"s removed):
```
/* Set up the proxy if necessary */
if(conn->bits.httpproxy && !data->set.tunnel_thru_httpproxy) {
  /* Unless we have asked to tunnel IMAP operations through the proxy, we
     switch and use HTTP operations only */
  if(conn->handler == &Curl_handler_imap)
    conn->handler = &Curl_handler_imap_proxy;
  else {
    conn->handler = &Curl_handler_imaps_proxy;
  }

  /* set it up as an HTTP connection instead */
  return conn->handler->setup_connection(conn);
}
```

I don't understand what this code tries to achieve. Does it want to talk HTTP to an IMAP server?

Maybe ``conn->bits.httpproxy`` (actual value) should be used there instead of ``data->set.tunnel_thru_httpproxy`` (configured value).

Another possible reason for the bug are the definitions of ``Curl_handler_imap_proxy`` and ``Curl_handler_imaps_proxy``. They look like outdated versions of ``Curl_handler_http`` and ``Curl_handler_https``.

**Comment by bagder** [comment]
@abcdxwz: how does it work if you also set `CURLOPT_HTTPPROXYTUNNEL` ?

There's pending work in #1505 to make that option implied when using non-HTTP over a HTTP proxy, so in a future version you won't need to set it, but until then you should...

**Comment by bagder** [comment]
I believe this issue is fixed by using the option as mentioned above. In the future the "tunnel mode" will be set by default, once the #1505 work is merged. No feedback from reporter in a long while though, closing this issue.

**Comment by abcdxwz** [comment]
Hi, guys
sorry for delay.

With CURLOPT_HTTPPROXYTUNNEL it works.
