### ISSUE TITLE
etag changes incorrect

### ISSUE THREAD

**Issue by GrahamCampbell** [curl/curl#13222]
### I did this

There are many use cases for etags on non 2xx responses, such as caching redirects (in particular if curl instructed not to follow redirects) or not founds. I don't believe #12866 to be a correct change.

### curl/libcurl version

curl 8.7.1

### operating system

N/A

**Comment by bagder** [comment]
I find this a rather vaguely phrased issue. You say a previous change is wrong but you do not speak much of what it should rather do. For 3xx codes it seems easy to understand the use case, but 4xx or 5xx?

**Comment by bagder** [comment]
Older etag spec text specifically mentioned 2xx codes, but it was removed in later updates. I am still curious in use cases and/or explanations for etags use outside of 2xx .

**Comment by bagder** [comment]
No response
