### ISSUE TITLE
Regression: CURLINFO_REQUEST_SIZE returns 0 when the response is aborted

### ISSUE THREAD

**Issue by ergonjona** [curl/curl#13269]
### I did this

curl_easy_getinfo(curlh, CURLINFO_REQUEST_SIZE, &request_size); on a request hat was aborted during the response (incomplete response).

### I expected the following

request_size should be greater than 0.

This was the case with Version 8.6.0

### curl/libcurl version

8.7.1

### operating system

Linux la_luna 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux

**Comment by ergonjona** [comment]
This is reproducible with the curl binary.

Request: `curl --write-out "%{size_request}\n" localhost:8080`

The response must be cut short, e.g:
```
HTTP/1.1 200 OK
Date: Wed, 03 Apr 2024 08:09:55 GMT
Content-Length: 215
Content-Type: text/html; charset=iso-8859-1

<html>
```

I Did this with `nc -l -p 8080`, copy&pasting the response and aborting the response with Ctrl-C.

With curl version 8.6.0 the output is:
```
<html>
curl: (18) transfer closed with 208 bytes remaining to read
size_request: 77
```

With curl version 8.7.1 the output is:
```
<html>
curl: (18) transfer closed with 208 bytes remaining to read
size_request: 0
```

**Comment by bagder** [comment]
The documentation for `curl_easy_getinfo` says quite explicitly:

> The data is stored accordingly and can be relied upon only if this function returns CURLE_OK.

Meaning that this still follows the documentation. We could still *attempt* to do what we did before, but the API does not guarantee this.

**Comment by bagder** [comment]
(removed previous comment, it was wrong)

**Comment by mkauf** [comment]
First bad commit, found with `git bisect`: 37551535712c267141f425fcb56ec6c474e46123

**Comment by icing** [comment]
Please see https://github.com/curl/curl/pull/13275 for a fix.

**Comment by ergonjona** [comment]
#13275 fixed our issue.

Thank you!
