### ISSUE TITLE
[Regression] libcurl does not finish CURLOPT_UPLOAD request after a connection lost without data tranfer

### ISSUE THREAD

**Issue by ligurio** [curl/curl#13260]
### I did this

There was an issue in Tarantool [^1] due to regression in libcurl (#11769), it was reported on 23 Aug, 2023. Issue was fixed in upstream on 4 Sept, 2023 and fix was confirmed by our tests for Tarantool. Unfortunately, this fix was ruined by refactoring made in commit d7b6ce64ce0ad ("lib: replace readwrite with write_resp") [3] on 1 Dec 2023, and now it is reproduced again.

- Reproducer for Tarantool is described in [^1]
- Reproducer for libcurl is described in #11769, I'm not sure, it is worth to duplicate it here

[^0]: https://curl.se/mail/lib-2024-03/0060.html
[^1]: https://github.com/tarantool/tarantool/issues/9086

### I expected the following

- Apply reverted fix for #11769 
- Convert reproducer in #11769 to a test to avoid regression in a future.

### curl/libcurl version

8.6.0+

### operating system

`uname -a`: Linux pony 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 22.04.4 LTS

**Comment by icing** [comment]
Could you verify if #13271 addresses your issue?

**Comment by ligurio** [comment]
> Could you verify if https://github.com/curl/curl/pull/13271 addresses your issue?

Sure, will do and report soon.

**Comment by ligurio** [comment]
The issue is still present with a patch on top of the master (60971d665b9b1df870821e91b35373ec6dc4b19a).

Curl's output:

```
Captured stderr:
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => CONNECT handle 0x5d9a3121cbc8; line 1910
* Curl_client_reset(), clear readers
* Added connection 0. The cache now contains 1 members
* Host localhost:2379 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
* STATE: CONNECT => CONNECTING handle 0x5d9a3121cbc8; line 1964
*   Trying [::1]:2379...
* connect to ::1 port 2379 from ::1 port 52424 failed: Connection refused
*   Trying 127.0.0.1:2379...
* Connected to localhost (127.0.0.1) port 2379
* STATE: CONNECTING => PROTOCONNECT handle 0x5d9a3121cbc8; line 2072
* STATE: PROTOCONNECT => DO handle 0x5d9a3121cbc8; line 2101
* cr_exp100_read, start AWAITING_CONTINUE
> POST /v3/watch HTTP/1.1
Host: localhost:2379
Transfer-Encoding: chunked
Accept: */*
Connection: Keep-Alive
Keep-Alive: timeout=1
Expect: 100-continue

* STATE: DO => DID handle 0x5d9a3121cbc8; line 2197
* STATE: DID => PERFORMING handle 0x5d9a3121cbc8; line 2315
* cr_exp100_read, AWAITING_CONTINUE, not expired
* HTTP 1.1 or later with persistent connection
< HTTP/1.1 100 Continue
< 
* cr_exp100_read, pass through
* cr_in_read(len=65524, total=-1, read=0) -> 0, 0, 0
* nread <= 0, server closed connection, bailing
```

**Comment by ligurio** [comment]
> Could you verify this? Many thanks.

Sure. I can confirm that this version fixes the problem.

**Comment by icing** [comment]
Thanks, with the new test case in place, I hope we can avoid stumbling into this again in the future.
