### ISSUE TITLE
Extra Output in WebSocket Responses

### ISSUE THREAD

**Issue by cloud303-cholden** [curl/curl#13273]
### I did this

Encountering a very strange issue where an extra character is added to the output of a WebSocket response.

Here is the basic structure I'm using for my command:
```sh
curl http://localhost:3000/$(printf "%-${length}s" | tr ' ' 'a') \
    --output - \
    --no-buffer \
    -H 'Connection: upgrade' \
    -H 'Upgrade: websocket' \
    -H 'Sec-WebSocket-Version: 13' \
    -H "Sec-WebSocket-Key: $(openssl rand -base64 16)" \
    -X GET
```

The extra characters start when the response length is 32 and continue on indefinitely (I assume). Below is a sample:
```
31: `<message>`
32: ` <message>`
33: `!<message>`
34: `"<message>`
35: ...
```

I first noticed this with an axum HTTP server that upgrades connections to WebSocket. I reproduced the issue on the JavaScript server below:
```javascript
const http = require('http');
const WebSocket = require('ws');

// Create an HTTP server
const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('WebSocket server is running.');
});

// Create a WebSocket server
const wss = new WebSocket.Server({ server });

// Event listener for WebSocket connection
wss.on('connection', (ws, req) => {
  const id = req.url.slice(1); // Extract the id from the URL

  console.log(`Client connected with id: ${id}`);

  // Send the id back to the client
  ws.send(id);
  ws.terminate();
});

// Start the HTTP server
const PORT = 3000;
server.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
```
In order to set up the test, run the following commands:
```sh
npm install ws
node run <filename>
```
Then in a separate terminal, you can test number 33 in the sequence as follows:
```sh
length=33; \
curl http://localhost:3000/$(printf "%-${length}s" | tr ' ' 'a') \
    --output - \
    --no-buffer \
    -H 'Connection: upgrade' \
    -H 'Upgrade: websocket' \
    -H 'Sec-WebSocket-Version: 13' \
    -H "Sec-WebSocket-Key: $(openssl rand -base64 16)" \
    -X GET \
    -s
```
This returns `!aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.
The expected response is `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.

[This file](https://github.com/curl/curl/files/14857450/result.txt) is the sequence of 31-300. The responses are trimmed for brevity.

 The below script was used to acquire this:
```sh
for length in {31..300}; do
  response=$(curl http://localhost:3000/$(printf "%-${length}s" | tr ' ' 'a') \
    --output - \
    --no-buffer \
    -H 'Connection: upgrade' \
    -H 'Upgrade: websocket' \
    -H 'Sec-WebSocket-Version: 13' \
    -H "Sec-WebSocket-Key: $(openssl rand -base64 16)" \
    -X GET \
    -s) \
  && response_length=$(echo -n "$response" | wc -c) \
  && difference=$(($response_length - $length)) \
  && echo "${response:0:6}"
done
```

### I expected the following

No extra characters are added to WebSocket responses.

### curl/libcurl version

curl 8.7.1 (x86_64-pc-linux-gnu) libcurl/8.7.1 OpenSSL/3.2.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 c-ares/1.27.0 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 nghttp3/1.2.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system

Pop!_OS 22.04 LTS

**Comment by jay** [comment]
> This returns `!aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.
> The expected response is `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`.

you're returning the websocket raw data instead of letting curl handle the websocket data decoding, like why not this

~~~
for length in {31..300}; do
  response=$(curld -s ws://localhost:3000/$(printf "%-${length}s" | tr ' ' 'a')) \
  && response_length=$(echo -n "$response" | wc -c) \
  && difference=$(($response_length - $length)) \
  && echo "${response:0:6}"
done
~~~

should always return aaaaaa and server log should show:

~~~
Client connected with id: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Client connected with id: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Client connected with id: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Client connected with id: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Client connected with id: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
...
etc
~~~

**Comment by bagder** [comment]
If you make curl upgrade to WebSocket without using curl's own support for it, when you need to write your own WebSocket stream parser. curl gives you the HTTP stream when you ask for HTTP. I don't see how this is a curl issue.

**Comment by cloud303-cholden** [comment]
@jay Ah thanks that resolved it.
