### ISSUE TITLE
getting info: CURLINFO_CONTENT_LENGTH_DOWNLOAD broken

### ISSUE THREAD

**Issue by pipettes** [curl/curl#1328]
```c
#include <curl/curl.h>


int main(int argc, char** argv){
    CURL* handle = curl_easy_init();
    double* p = 0;
    curl_easy_getinfo(handle, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &p);
    std::cout << (*p == -1) << '\n';
    curl_easy_cleanup(handle);
}
```
SEGFAULT for deferencing p.

I expected either "-1" or the content length.

curl 7.53.1 (x86_64-pc-linux-gnu) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11 libpsl/0.17.0 (+libicu/58.2) libssh2/1.8.0

Working on linux.

**Comment by bagder** [comment]
Quoting the man page:

> Pass a pointer to a double to receive the content-length of the download

This example passes in a pointer to a pointer to a double.

Fixed version:
~~~c
#include <curl/curl.h>

int main(int argc, char** argv)
{
  CURL* handle = curl_easy_init();
  double p = 0;
  curl_easy_getinfo(handle, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &p);
  printf("%.3f\n", p);

  curl_easy_cleanup(handle);
}
