### ISSUE TITLE
HAVE_STRUCT_TIMEVAL fails on Ubuntu 22.04 when it shouldn't

### ISSUE THREAD

**Issue by jayrulez** [curl/curl#13308]
### I did this

Configuring curl build with cmake.
The HAVE_STRUCT_TIMEVAL will fail, generating a custom definition for the timeval struct in curl_setup_once.h
```C
#ifndef HAVE_STRUCT_TIMEVAL
struct timeval {
 long tv_sec;
 long tv_usec;
};
#endif
```

Building curl afterwards will fail because there is a duplicate definition from timeval

### I expected the following

I expected this the HAVE_STRUCT_TIMEVAL to succeed on Ubuntu 22.04

It fails because of how time.h inclusion gets evaluated.

I updated the test to include <sys/time.h> instead of <time.h> which allows the test to pass, and the curl build to succeed.

```C
#include <sys/time.h>
  int main(void)
  {
    struct timeval ts;
    ts.tv_sec  = 0;
    ts.tv_usec = 0;
    (void)ts;
    return 0;
  }
```

Would making a PR with this change be acceptable?

### curl/libcurl version

curl 7.86.0

### operating system

Ubuntu 22.04

**Comment by bagder** [comment]
People and CI jobs have built curl on Ubuntu using cmake for quite some time. Why does this suddenly reveal itself?

Can you tell us how you run cmake?

I presume this problem is also visible if you build curl from git master?

**Comment by vszakats** [comment]
The check already includes `sys/time.h`, if it was detected earlier via `check_include_file_concat()`:
https://github.com/curl/curl/blob/860cd5fc2dc8e165fadd2c19a9b7c73b3ae5069d/CMake/OtherTests.cmake#L63-L74

**Comment by jayrulez** [comment]
> People and CI jobs have built curl successfully on Ubuntu using cmake for quite some time. Why does this suddenly reveal itself?
> 
> Can you tell us how you run cmake?

I have curl as a submodule:
https://github.com/ZeroEngineProject/ZeroEngine/blob/main/Code/External/Curl/CMakeLists.txt

> 
> I presume this problem is also visible if you build curl from git master?

I'm using 7.86.0. I will try updating to the latest release and check again.

I didn't have the issue on Arch, only Ubuntu. I'm using clang there. I don't know if that makes a difference.

**Comment by bagder** [comment]
If you can reproduce in a clean build using a modern version let us know and we can reopen. Lots of people build curl on Ubuntu 22.04 just fine.
