### ISSUE TITLE
Change in behavior for --remote-header-name

### ISSUE THREAD

**Issue by morganwillcock** [curl/curl#13302]
### I did this

Commit 75d79a4486b279100209ddf8c7fdb12955fb66e9 seems to introduce a change in behavior where the filename used for the downloaded file may no longer be affected by the `--remote-header-name` option.

The easiest way to demonstrate the problem is to try downloading a file from Sourceforge:
```sh
curl -fLOJ https://sourceforge.net/projects/openofficeorg.mirror/files/4.1.15/README.md/download
```

### I expected the following

Currently the filename used will be "download".

In older versions of Curl and with commit 75d79a4486b279100209ddf8c7fdb12955fb66e9 reverted, the filename used will be "README.md". The issue was noticed due to CI workflows failing with the latest release of Curl, when downloading dependencies from Sourceforge.

This seems a significant change in behavior.  Is it completely intentional?

### curl/libcurl version

8.7.0-DEV (On commit `de7b3e89218467159a7af72d58cea8425946e97d`)

### operating system

Debian 12.5
`Linux hostname 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`

**Comment by jay** [comment]
Please try #13303

**Comment by morganwillcock** [comment]
That does fix it. Thank you.
