### ISSUE TITLE
libcurl compiled on OS X 10.11 fails to load on 10.8 (and earlier)

### ISSUE THREAD

**Issue by markovicpp** [curl/curl#1330]
### I did this
Compiled libcurl on OS X 10.11 with base SDK 10.11 and deployment target 10.8 but the product linking the libcurl stopped working in OS X 10.8 with following message:

>Symbol not found: _connectx
Expected in: /usr/lib/libSystem.B.dylib

The problem can be backtraced to introduction of TCP Fast open on OS X.
Officially _connectx()_ is introduced in Darwin 15.0.0 (OS X 10.11 / iOS 9.0).
It looks like the condition based on CONNECT_DATA_IDEMPOTENT value assumes that the library is never going to be used on system with lower version than the base SDK.

### I expected the following
The product compiled with base SDK 10.11 and linked with libcurl will work on OS X 10.8 with proper use availability macros.

### curl/libcurl version
curl 7.52.1 (x86_64-apple-darwin15.5) libcurl/7.52.1 SecureTransport zlib/1.2.8

### operating system
OS X 10.8

**Comment by bagder** [comment]
I suppose the mac build needs a an option like "lowest version I want this to work on"...

**Comment by markovicpp** [comment]
Something similar is done in lib/md5.c, this condition should work:
```c
#if (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && \
            (__MAC_OS_X_VERSION_MIN_REQUIRED >= 101100)) || \
    (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && \
            (__IPHONE_OS_VERSION_MIN_REQUIRED >= 90000))
```

**Comment by bagder** [comment]
You up to providing a full suggested fix as a pull request? I'd appreciate it!

**Comment by markovicpp** [comment]
Keen to do it, but it seems to be a little bit more complicated than I thought so.
I need to do some research about it, and find out why connectx() is not declared as weak-linked symbol. If it was so, the fix would be much easier with better backwards compatibility.

**Comment by markovicpp** [comment]
I’ve created two possible solutions to this problem:

The first one is simple compile time decision which does not allow targetting older systems and using --tcp-fastopen on newer using single library.

The second one redeclares connectx() function with missing attributes and checks for the its availability during the runtime. This way it’s possible to use same libcurl library on range on systems and enable --tcp-fastopen one those which have support for connectx().

**Comment by bagder** [comment]
I think we should decide on which way to go and kill of the other PR. It is highly confusing I think to drive both ways at once.

**Comment by markovicpp** [comment]
I definitely agree, I took the opportunity to work on two approaches and see where it might lead.

I think that despite the PR #1339 offers more flexibility, it’s becoming quite complex workaround requiring runtime check of the symbol availability **and** system version due to non-standard handling of connectx() function in Darwin libc.

PR #1336 offers simpler compile time but mutes tcp-fastopen feature by default (until it’s configured with targetting minimum system 10.11).
