### ISSUE TITLE
curl 7.88.1-10+deb12u5 fails to download with tftp

### ISSUE THREAD

**Issue by debananda-pal** [curl/curl#13318]
### I did this 

Hello,
We are upgrading to bookworm and used curl 7.88.1-10+deb12u5.

We are able to download file using http, but not with tftp.
Please find the output of both the commands below :

root prompt > curl -O http://100.104.120.171/tftpboot/users/debananda.pal/bookworm-installer-x86_64.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  bookworm-installer-x86_64.bin
                                 Dload  Upload   Total   Spent    Left  Speed
100  840M  100  840M    0     0  44.9M      0  0:00:18  0:00:18 --:--:-- 49.6M

root prompt > ls -l
total 860964
-rw-r--r-- 1 root root 881413922 Apr  7 16:32 bookworm-installer-x86_64.bin

root prompt > curl -O tftp://100.104.120.171/users/debananda.pal/bookworm-installer-x86_64.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  bookworm-installer-x86_64.bin
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:05:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:05:01 --:--:--     0
**curl: (28) getpeername() failed with errno 107: Transport endpoint is not connected**

Please let me know if there is any suggestion.

Regards,
D Pal

### I expected the following

I expect curl to download file without any error.

### curl/libcurl version

curl 7.88.1-10+deb12u5
libcurl3-gnutls:amd64          7.88.1-10+deb12u5
libcurl4:amd64                 7.88.1-10+deb12u5

### operating system

Debian 6.1.69-1  x86_64 GNU/Linux

**Comment by bagder** [comment]
I believe this was fixed in 355f4144df

**Comment by debananda-pal** [comment]
Thank you Bagder.
We are using  curl_7.88.1-10+deb12u5.debian.tar.xz  debian package and not able to find the respective file (lib/cf-socket.c) or function (static CURLcode set_local_ip).
But the approprite file and function are present in curl-7_88_1.zip.

Regards,
D Pal

**Comment by bagder** [comment]
I'm suggesting this was fixed in 8.2.0. If you want to just make a patch that works on the 7.88.1 source code, then you need to backport that or the equivalent fix.

**Comment by debananda-pal** [comment]
Thank you Bagder.

**Comment by bagder** [comment]
Fixed already in modern versions.
