### ISSUE TITLE
macOS: -Werror=partial-availability causes build problems

### ISSUE THREAD

**Issue by rcgordon** [curl/curl#1333]
If you build libcurl for macOS, using --with-darwinssl and an earlier minimum OS target, say, 10.6, the build will unnecessarily fail, even though it appears it should be able to support this case.

The problem is the addition of the -Werror=partial-availability check in the configure script, discussed here: https://github.com/curl/curl/issues/1104 ...here's the report @bagder was waiting for.  :)

libcurl will check for various symbols that were available in 10.8, as weak symbols, and use older APIs if not available (good). It blocks these off behind preprocessor checks to make sure the system headers offer details on these symbols (good). So you might have code like this, in curl-7.53.1/lib/vtls/darwinssl.c:827

#if CURL_BUILD_MAC_10_7
  /* Lion & later: Get the long description if we can. */
  if(SecCertificateCopyLongDescription != NULL)
    server_cert_summary =
      SecCertificateCopyLongDescription(NULL, cert, NULL);
  else
#endif /* CURL_BUILD_MAC_10_7 */
#if CURL_BUILD_MAC_10_6
  /* Snow Leopard: Get the certificate summary. */
  if(SecCertificateCopySubjectSummary != NULL)
    server_cert_summary = SecCertificateCopySubjectSummary(cert);
  else
#endif /* CURL_BUILD_MAC_10_6 */

...and that build will use the newer system API on 10.7 and later and the older one on 10.6, cool. But if you build with -mmacosx-version-min=10.6, so you generate a library that will have access to older versions of the OS, it appears Clang will trigger an error for any reference to a post-10.6 symbol, even if you are explicitly checking a weak symbol for its existence.

I would argue this is a bug/misfeature in Clang, but I guess it's supposed to catch any use of a potentially weak symbol at all? For something that took conscious effort to support binary compatibility with various versions of the OS, it seems like the partial-availability flag shouldn't be on at all, or at least be a warning and not a -Werror, but I might be misunderstanding all this.

### curl/libcurl version

7.53.1

### operating system

macOS 10.12

**Comment by markovicpp** [comment]
I agree that this is an issue if a library is supposed to support multiple versions.
I’ve just run into same problem when I experimented with runtime check for connectx function introduced in OS X 10.11.

On the other hand it’s probably quite useful to catch runtime linking errors with this check.
To support backwards compatibility it can be locally disabled in places where weak-linking is indented to be used, something that’s described here:
http://mjtsai.com/blog/2015/05/08/clangs-new-wpartial-availability/

**Comment by bagder** [comment]
> something that’s described here

That approach will fill up the code with ugly pragmas and more, won't it? A really messy "solution" if you ask me. But perhaps there's no other way around it?

**Comment by rcgordon** [comment]
I'm surprised that Clang isn't smart enough to only fire that warning on weak symbols that weren't explicitly checked against NULL, but since that isn't in our control, these would be my thoughts on a solution, in my order of preference:

- Turn off that specific -Werror entirely, since libcurl is responsibly checking for NULLs in weak symbols already.
- Leave it as a warning instead of promoting it to an error.
- Wrap just darwinssl.c in that pragma.
- Don't do anything; libcurl is a system-supplied library in macOS, so maybe the source code shouldn't be built against anything but the latest Apple SDK, and most developers should be using the preinstalled version and not their own build.

(I'll also open a bug with Clang and see if this is something they think should be improved on their end.)

**Comment by markovicpp** [comment]
The last one is probably something that Apple was expecting from developers to do, but it does not reflect the reality. In fact many developers distribute or bundle libcurl with their products, mostly cross-platform to have same set of features across platforms. Also there’s no guarantee that it will remain there in future OS versions.

Fixing that warning in compiler would be definitely the best thing, otherwise leaving it as a warning (and not promoting to an error) seems to me like a workable compromise (depends on amount of warnings issued).

**Comment by rcgordon** [comment]
Actually, hang on, the compiler warning tells you how the Clang developers intended it to be silenced:

> ../../lib/vtls/darwinssl.c:1177:6: note: explicitly redeclare 'SSLCreateContext' to silence this warning

This will let us explicitly declare that we meant to do this without a bunch of pragma salsa all over the place. I'm putting together a PR in a moment.

**Comment by rcgordon** [comment]
That PR makes sure everything compiles clean on macOS, targetting back to 10.5 (and maybe earlier?), and makes sure all of these things are weak symbols:

[icculus@caridad ~/projects/curl/x]$ nm -nm src/.libs/curl |grep weak
                 (undefined) weak external _clock_gettime (from libSystem)
[icculus@caridad ~/projects/curl/x]$ nm -nm lib/.libs/libcurl.dylib |grep weak
                 (undefined) weak external _SSLCopyPeerTrust (from Security)
                 (undefined) weak external _SSLCreateContext (from Security)
                 (undefined) weak external _SSLSetProtocolVersionMax (from Security)
                 (undefined) weak external _SSLSetProtocolVersionMin (from Security)
                 (undefined) weak external _SSLSetSessionOption (from Security)
                 (undefined) weak external _SecCertificateCopyLongDescription (from Security)
                 (undefined) weak external _SecCertificateCopySubjectSummary (from Security)
                 (undefined) weak external _SecCertificateCreateWithData (from Security)
                 (undefined) weak external _SecItemCopyMatching (from Security)
                 (undefined) weak external _SecPolicyCreateSSL (from Security)
                 (undefined) weak external _SecTrustEvaluateAsync (from Security)
                 (undefined) weak external _SecTrustGetCertificateAtIndex (from Security)
                 (undefined) weak external _SecTrustGetCertificateCount (from Security)
                 (undefined) weak external _SecTrustSetAnchorCertificatesOnly (from Security)
                 (undefined) weak external _clock_gettime (from libSystem)
                 (undefined) weak external _kSecAttrLabel (from Security)
                 (undefined) weak external _kSecClass (from Security)
                 (undefined) weak external _kSecClassIdentity (from Security)
                 (undefined) weak external _kSecMatchLimit (from Security)
                 (undefined) weak external _kSecMatchLimitAll (from Security)
                 (undefined) weak external _kSecMatchPolicy (from Security)
                 (undefined) weak external _kSecReturnRef (from Security)

I _think_ this solves the problem for everyone...?
