### ISSUE TITLE
File descriptor leakage

### ISSUE THREAD

**Issue by green-free** [curl/curl#13341]
### I did this

My network environment is malfunctioning. At this point, I wrote a program to connect to a URL by calling the library function. Since the URL is not an IP, but a domain name, DNS resolution will be performed first. I saw the DNS resolution packet, but when I timed out and exited the curl library function, I found that the socket seemed not to be closed.

This is my testing program:
~~~c
int curlDebugCallback(CURL *curl, curl_infotype type, char *data, size_t size, void *userptr) 
{
    switch (type) {
        case CURLINFO_TEXT:
            printf("curl Info: %s", data);
            break;
        case CURLINFO_HEADER_IN:
        case CURLINFO_HEADER_OUT:
            printf("curl Head: %s", data);
            break;
        case CURLINFO_DATA_IN:
        case CURLINFO_DATA_OUT:
            printf("curl Data: %s", data);
            break;
        default: /* in case a new one is introduced to shock us */
            return 0;
    }
    return 0;
}

int perform_curl()
{
	CURL *curl = NULL;
    CURLcode res = 0;

	curl = curl_easy_init();
	if (!curl) {
		syslog(LOG_ERR, "init curl filed!");
		return -1;
	}

	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 120L); // 120s
	curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 30L); // 30s
	curl_easy_setopt(curl, CURLOPT_URL, "xyz.com.cn");

    curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, curlDebugCallback);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

	res = curl_easy_perform(curl);
	if (res != 0) {
		printf("failed to perform http get,ret:%d, reason:%s \n", res, curl_easy_strerror(res));
		goto leave;
	}

	printf("perform curl success");
leave:

	curl_easy_cleanup(curl);
	return res;
}

int curl_test_main(int argc, char *argv[])
{
	int count  = 1000;

	for (count  = 1000; count > 0; count--) {
		perform_curl();
	}

	return 0;
}

~~~

![无标题](https://github.com/curl/curl/assets/52776582/49cfd94b-a789-4e15-9180-4835752565ed)
![无标题1](https://github.com/curl/curl/assets/52776582/3b56b352-7434-4b11-b684-cdbd70697568)

I used the trace tool to track and found the following information: This poll was interrupted by a signal, so it was not closed?

![image](https://github.com/curl/curl/assets/52776582/1c09affa-8c59-4883-806e-1b72b7f9157a)

### I expected the following

Fix file descriptor leakage

### curl/libcurl version

1. curl-8.7.1
2. curl-7.63.0
3. curl-8.5.0

### operating system

/var/tmp # uname -a
Linux Router 3.10.14 #7 Sun Feb 18 17:35:55 CST 2024 mips GNU/Linux

**Comment by dfandrich** [comment]
Do you see the same after calling curl_global_cleanup()?

**Comment by green-free** [comment]
> Do you see the same after calling curl_global_cleanup()?
Yes, curl_global_cleanup has been added and it also exists

**Comment by bagder** [comment]
I'm not convinced you have properly identified a resource leak. Also: what name resolver backend does your libcurl build use?

My tests show this:

~~~
$ valgrind curl does.not.exist
...
==876713== All heap blocks were freed -- no leaks are possible

**Comment by green-free** [comment]
> I'm not convinced you have properly identified a resource leak. Also: what name resolver backend does your libcurl build use?
> 
> My tests show this:
> 
> ```
> $ valgrind curl does.not.exist
> ...
> ==876713== All heap blocks were freed -- no leaks are possible
> ```

What do you mean by this?
I am a mips based Linux, but this should not be related to the architecture. As long as the library function interface is called, it should be reproducible in case of network problems

**Comment by bagder** [comment]
> Can you try not using the valgrind tool and only checking the information in the proc directory?

I deliberately did not do that because I am not convinced that is a correct way to detect leaks. I know valgrind is however.

**Comment by green-free** [comment]
> > Can you try not using the valgrind tool and only checking the information in the proc directory?
> 
> I deliberately did not do that because I am not convinced that is a correct way to detect leaks. I know valgrind is however.

Okay, I'll also use the tool you mentioned

**Comment by green-free** [comment]
> > Can you try not using the valgrind tool and only checking the information in the proc directory?
> 
> I deliberately did not do that because I am not convinced that is a correct way to detect leaks. I know valgrind is however.

I am running the same program on my Linux computer and cannot see any file descriptor leakage. The tools mentioned earlier cannot be used on mips

Linux computer uname -a
Linux macro 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
> I am running the same program on my Linux computer and cannot see any file descriptor leakage.

But you still insist that there is a leak?

The netstat results above shows (only) UDP connections to port 53. That's DNS. Meaning that curl is not directly responsible for them, the name resolver is.

**Comment by bagder** [comment]
No follow-up, presumed to not be a problem.

**Comment by green-free** [comment]
My fundamental problem is that the getaaddrinfo() on my Linux MiPS platform is interrupted by the alarm signal, which can cause file descriptor leakage.
So my solution was to set the curl disable signal:
`curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);`
