### ISSUE TITLE
File descriptor leakage  with multi handle and c-ares

### ISSUE THREAD

**Issue by calvin2021y** [curl/curl#13342]
### I did this

I write a app use libcurl with libuv multi, c-ares.  there is File descriptor leakage.

The app only fetch one domain by one IP, so I add  CURLOPT_RESOLVE to avoid DNS resolution process.

I notice there is File descriptor leakage, after strace I find the fd open by:

```sh
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY) = 13
newfstatat(13, "", {st_mode=S_IFREG|0644, st_size=21, ...}, AT_EMPTY_PATH) = 0
newfstatat(13, "", {st_mode=S_IFREG|0644, st_size=21, ...}, AT_EMPTY_PATH) = 0
lseek(13, 0, SEEK_SET)                  = 0
read(13, "nameserver 8.8.8.8\n", 21)  = 21
lseek(13, 21, SEEK_SET)                 = 21
close(13)                               = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY) = 13
newfstatat(13, "", {st_mode=S_IFREG|0644, st_size=494, ...}, AT_EMPTY_PATH) = 0
newfstatat(13, "", {st_mode=S_IFREG|0644, st_size=494, ...}, AT_EMPTY_PATH) = 0
lseek(13, 0, SEEK_SET)                  = 0
read(13, "# /etc/nsswitch.conf\n#\n# Example"..., 494) = 494
lseek(13, 494, SEEK_SET)                = 494
close(13)                               = 0
```
This is single thread app, and after DNS related syscall there is `connect` to the target host. (The IP is fixed by CURLOPT_RESOLVE)

I can see there are closed soon after open.  but some how still leaked. (maybe libuv bugs)

Then I try fix the problem by add CURLOPT_DNS_SERVERS, same problem.

### I expected the following

With CURLOPT_DNS_SERVERS and CURLOPT_RESOLVE, I expect the curl direct call `connect` without check `/etc/nsswitch.conf` and `/etc/resolv.conf`.   (I think CURLOPT_RESOLVE  should do the work)

Is there a CURL options to disable c-ares skip check the system settings ? (or I can call some c-ares function before start curl ?)

### curl/libcurl version

test on 8.7.1 and master branch.

### operating system

linux with 6.1.76 kernel.

**Comment by calvin2021y** [comment]
all leaked file descriptor number can be find from the strace call, all open by openat(AT_FDCWD,  "/etc/resolv.conf|/etc/nsswitch.conf".  (after one week , there is around 36000 leaked fd,  reach the ulimit then app no response)

**Comment by bagder** [comment]
Is this the same as #13341 ?

You mention c-ares, which version?

**Comment by calvin2021y** [comment]
I am not sure they are related to https://github.com/curl/curl/issues/13341

Test confirm with  c-ares `1.28.1` and `1.28`.  

beside the file descriptor leak problem,  I want to skip the c-ares openat(AT_FDCWD, "/etc/resolv.conf|/etc/nsswitch.conf" step,  to verify if them still leak.

**Comment by bagder** [comment]
Please explain how to reproduce this problem. I cannot make it happen and this is not a known issue.

I've reproduced my tests from #13341 with c-ares 1.28.1 and I see no leaks whatsoever.

**Comment by calvin2021y** [comment]
I am working on a minimal test case. before that, I try with http://ip without CURLOPT_RESOLVE, but use CURLOPT_HTTPHEADER to set the hostname.

It is http with ip ( no ssl).

Why I still get this syscall:

```sh
open("/etc/resolv.conf", O_RDONLY|O_LARGEFILE) = 29
lseek(29, 0, SEEK_END)                  = 21
lseek(29, 0, SEEK_CUR)                  = 21
lseek(29, 0, SEEK_SET)                  = 0
readv(29, [{iov_base="nameserver 8.8.8.8", iov_len=20}, {iov_base="\n", iov_len=1024}], 2) = 21
close(29)                               = 0
open("/etc/nsswitch.conf", O_RDONLY|O_LARGEFILE) = 29
lseek(29, 0, SEEK_END)                  = 494
lseek(29, 0, SEEK_CUR)                  = 494
lseek(29, 0, SEEK_SET)                  = 0
readv(29, [{iov_base="# /etc/nsswitch.conf\n#\n# Example"..., iov_len=493}, {iov_base="\n", iov_len=1024}], 2) = 494
close(29)                               = 0
open("/etc/netsvc.conf", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
open("/etc/svc.conf", O_RDONLY|O_LARGEFILE) = -1 ENOENT (No such file or directory)
getrandom("\xa0\x1e\xf2\x03\xe2\x51\x13\x5b\x95\x2d\xf5\xd6\x18\xbf\x7b\x84\x5d\x64\x2f\xe1\x83\xba\x61\x8d\x7a\x2c\x15\x40\x17\x60\x3b\x41"..., 256, 0) = 256
uname({sysname="Linux", nodename="test1", ...}) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x350f27}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x350f27}, NULL, 8) = 0
poll([{fd=33, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)

```

**Comment by bagder** [comment]
> Why I still get this syscall:

Your list shows several syscalls. Which one are you asking about?

**Comment by calvin2021y** [comment]
all of t syscalls before rt_sigaction.

Because when I connect a IP without ssl, they are not needed.

**Comment by bagder** [comment]
Those are name server config files so I would presume they are loaded by c-ares. Probably done unconditionally of the name resolve. Hardly relevant for this issue though...

**Comment by calvin2021y** [comment]
1) the app send 550 request every every minute.    for each request there is 16 syscall unnecessary.   

2) all  leaked fd is related to those fd open by "/etc/resolv.conf|/etc/nsswitch.conf",  I want to test if there still  leaked fd without them

**Comment by calvin2021y** [comment]
```sh
tail -n 100000 app_log.json | grep '2024-04-11T19:15'|wc
38398  153592 26739507
```

for every secs,  10239 syscall unnecessary.    (I start 2 stand alone app, each one use single thread)

**Comment by calvin2021y** [comment]
> Those are name server config files so I would presume they are loaded by c-ares. Probably done unconditionally of the name resolve. Hardly relevant for this issue though...

In my case, no DNS is needed since I use IP as url address.    so I want to know if we can skip the c-ares related call from curl side.

**Comment by calvin2021y** [comment]
> ```shell
> tail -n 100000 app_log.json | grep '2024-04-11T19:15'|wc
> 38398  153592 26739507
> ```
> 
> for every sec, 10239 syscall unnecessary. (I start 2 stand alone app, app use single thread)

This is wrong number. after I count the syscall call from strace, I think they are called for every new connection. (not every request)

**Comment by bagder** [comment]
We will welcome your optimizations, thank you.

In the mean time, this issue is about a file descriptor leak I have not managed to reproduce.

**Comment by calvin2021y** [comment]
after more test I confirm this is not a curl issue. sorry for the miss report.
