### ISSUE TITLE
mutli-thread crash with curl_share setting CURL_LOCK_DATA_CONNECT?

### ISSUE THREAD

**Issue by bethebest0622** [curl/curl#13347]
### I did this

I want to get lowest letency for parallelized http get/post requests. So, I need two features:

1. parallelized sending request without blocking.
2. try best to reuse connections. 

I try this code: (only list the main part)

```
curl_share_setopt(share_, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT);

Curl* curls[10];
for (int i = 0; i < 10; ++i) curl_easy_setopt(curls[i], CURLOPT_SHARE, share_);
threadpool tp(10);
std::atomic<int> cnt(0);

inline size_t curl_cb(char *content, size_t size, size_t nmemb, std::string* ptr) {
  ptr->append(content, size * nmemb);
  return size * nmemb;
}

void send_request(const std::string & url) {
  tp.enqueue([]() {
       std::string r;
       curl_easy_setopt(hb_curl_, CURLOPT_WRITEDATA, &r);
       curl_easy_perform(curls[cnt++]);
       std::cout << r << std::endl;
 });
}
```

### I expected the following

I expected it works well, but it always crashed in a multi-cpu machine.

I think the problem is `CURL_LOCK_DATA_CONNECT `not safe in multi-thread environment.

but i think it's a must setting in my requirements.

could you help on this?

### curl/libcurl version

curl 8.2.1

### operating system

centos stream 8

**Comment by bagder** [comment]
> I think the problem is CURL_LOCK_DATA_CONNECT not safe in multi-thread environment.

This is documented and known. Thus not a bug.

**Comment by bagder** [comment]
It would be weird to offer multiple methods to do the same thing where one of them doesn't work... No, this is the way it should be done. It just has not (yet) been done in a way that makes it multi-thread safe. You are of course most welcome to help us improve in this area.

**Comment by bagder** [comment]
Also already mentioned in the TODO document as something we want: https://curl.se/docs/todo.html#Better_and_more_sharing
