### ISSUE TITLE
Test cases sometimes timeout

### ISSUE THREAD

**Issue by rossburton** [curl/curl#13350]
### I did this

We install the test suite so that we can run it on target as part of integration testing.  Occasionally, one of the tests will timeout.  For an example of this, see https://autobuilder.yocto.io/pub/non-release/20240409-14/testresults/qemux86-64-ptest/curl.log.

This shows test 340 fails after waiting two minutes for a response from the server. I initially blamed a heavily loaded host machine (as the tests are running inside a qemu-system) but the test execution started at 12:51, test 340 started at 12:52, and times out two minutes later at 12:54.  This suggests that the other tests are all running quickly and the problem is not system load.

https://bugzilla.yoctoproject.org/show_bug.cgi?id=15268 is our tracker bug for this issue, it can be seen that there's no hugely obvious pattern (to me, at least) to what tests fail.  We also pass `!flaky !timing-dependent` to `runtests.pl` to filter out tests marked as such.

My hunch is that there's a subtle race in the test harness, which is only visible when running the tests frequently.

### curl/libcurl version

curl 8.7.1

### operating system

OpenEmbedded

**Comment by egorpugin** [comment]
I see all my curl-using programs experience major delays after 8.6.0->8.7.1 upgrade on linux (win & mac seems ok).
I'll see if I can debug them a bit.

**Comment by bagder** [comment]
Without being able to reproduce this locally, this feels next to impossible to fix.

**Comment by rossburton** [comment]
Absolutely agree.  I guess this was more a a cry of has anyone else seen this before, or have any hunches.

I'll try building curl on my lowest machine and seeing if I can make it replicate there.

**Comment by guilherme-puida** [comment]
Just as another data point, we are also seeing some timeouts in Debian's buildd network.

https://buildd.debian.org/status/fetch.php?pkg=curl&arch=amd64&ver=8.7.1-5%2Bexp1&stamp=1715630000&raw=0
https://buildd.debian.org/status/fetch.php?pkg=curl&arch=amd64&ver=8.7.1-5%2Bexp1&stamp=1715628225&raw=0
https://buildd.debian.org/status/fetch.php?pkg=curl&arch=i386&ver=8.7.1-5%2Bexp1&stamp=1715627959&raw=0
https://buildd.debian.org/status/fetch.php?pkg=curl&arch=arm64&ver=8.7.1-5%7Ebpo12%2B1&stamp=1715892677&raw=0
https://buildd.debian.org/status/fetch.php?pkg=curl&arch=arm64&ver=8.7.1-5%7Ebpo12%2B1&stamp=1715749009&raw=0

I also spend the day today rebuilding the package locally, and these tests also eventually timeout: 226, 350, 351, 352, 353, 354, 362, 401, 408, 409, 520, 525, 533, 534, 593, 661, 1028, 1055, 1057, 1096, 1107, 1108, 1114, 1149, 1206, 1224, 1226, 1380, 1381, 1383, 1384, 1386, 1390, 1393.

As far as I can see, they are all ftp-related. The timeouts only started appearing after we enabled parallel tests.

**Comment by rossburton** [comment]
The tests that we've seen fail are: 136 137 138 139 337 340 1062 1086 1091 1096 1103 1107 1108 1137 1149. Only three match, but if the bug/race is in the FTP harness and there's a lot of tests, that's not a surprise.

I think I'm just going to try filtering out the FTP tests and seeing if that stops them entirely, or if different tests fail then.

**Comment by guilherme-puida** [comment]
After doing some bisecting, the timeouts started to appear on f6513b998266dfe91ef5c52f67c416cc0a0de0a2, which fixed #12002. This might be wrong since the timeouts are somewhat infrequent on my machine, but it seems like a good starting point.

I'll try to hack on this code for a while, but I'm not sure I'll be able to fix it :^)

**Comment by rossburton** [comment]
@bagder: a small correction: the issue isn't that one test fails, the issue appears to be that the FTP tests are unstable.

**Comment by icing** [comment]
@rossburton have you tried the current `master`. I did some stabilizing in FTP data connection handling, which seems to have improved our CI "greenness". But maybe I am halucinating like the machines.

**Comment by rossburton** [comment]
> @rossburton have you tried the current `master`. I did some stabilizing in FTP data connection handling, which seems to have improved our CI "greenness". But maybe I am halucinating like the machines.

I have not, but if you can point to specific commits I can apply them and see what happens.

**Comment by guilherme-puida** [comment]
> have you tried the current master. I did some stabilizing in FTP data connection handling, which seems to have improved our CI "greenness". But maybe I am halucinating like the machines.

I feel like the failure rate is lower now, but I can still see some failing tests occasionally. I tested on 282b9fe8f, and after running the test suite a few times test case 587 failed.

```
 527: protocol FAILED!
 There was no content at all in the file log/19/server.input.
 Server glitch? Total curl failure? Returned: 125
```

>  I'm guessing the previous test would have had some interesting logs that would have given some clues as to how the system got into the state

I assume that _previous test_ does not relate to the numerical order. Is there a way to figure out what test ran just before the one that failed? I can try to send logging information.

**Comment by dfandrich** [comment]
Tests are normally run in numerically-increasing order, unless specific test numbers are given on the command-line or the -j -R or --repeat options are given to runtests.

**Comment by guilherme-puida** [comment]
> Tests are normally run in numerically-increasing order, unless specific test numbers are given on the command-line or the -j -R or --repeat options are given to runtests.

Yes, I'm using `-j56`. I assumed that the tests were only failing with parallel testing enabled, so I didn't even try to reproduce without it. I'll run them a few more times to see if I hit any more failures.

**Comment by dfandrich** [comment]
I can be tricky to find the "previous" test with -j, since previous in this
regard refers to the previous test run by the same test process/runner, which
isn't really logged. By specifying -k you can keep some previous log files
around and look at the time stamps but you still might not get enough
interesting information.
