### ISSUE TITLE
Please support setting adjustment algorithm sequence

### ISSUE THREAD

**Issue by 00558901liuxingyu** [curl/curl#13358]
### I did this

When libssh+lbcurl is used to run commands, CURL does not support SFTP. However, libssh2 is indirectly referenced to support SFTP. Because libcurl does not support algorithm sequence adjustment, insecure algorithm protocols are filtered out during command execution.

### I expected the following

Please support setting adjustment algorithm sequence

### curl/libcurl version

curl 7.79.1

### operating system

Linux  
4.18.0-147.5.2.8.h878.eulerosv2r10.x86_64 #1 SMP Wed Apr 6 16:12:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
No response.
