### ISSUE TITLE
Having error alert when ./configure curl in a folder with an ".app" extension on macOS 14 

### ISSUE THREAD

**Issue by mpepito13** [curl/curl#13357]
### I did this

Hello,

I have an Applescript application that launch a webserver that is compiled into it. This webserver is composed of httpd, php, openssl and curl among others. I'm using the `--prefix` parameter to compile everything where it needs to be.

Until macOS 13, I had no problem with this setup.

Since macOS 14, an error shows up in the Finder during the `./configure` of curl : "cannot open the Application My.app as it may be damaged or incomplete"
![WhatsApp Image 2024-04-05 at 14 29 57](https://github.com/curl/curl/assets/1489100/94f45edc-2911-4ed8-b5ed-b997b2b6a8a0)

When this dialog alert appears, the `./configure` script is suspended during :
```
configure:25088: checking whether to enable IPv6
configure:25137: gcc -o conftest -Qunused-arguments -O2 -Wno-pointer-bool-conversion -Werror=partial-availability  -I/Applications/MyApp.app/Contents/Resources/Webserver/zlib-1.3.1/include -L/Applications/MyApp.app/Contents/Frameworks -framework CoreFoundation -framework CoreServices -framework SystemConfiguration -L/Applications/MyApp.app/Contents/Resources/Webserver/zlib-1.3.1/lib conftest.c -lz  >&5
configure:25137: $? = 0
configure:25137: ./conftest
```

I tried the following with the conftest :
```
otool -L conftest

conftest:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2420.0.0)
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1226.0.0)
        /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1300.100.9)
        /Applications/MyApp.app/Contents/Resources/Webserver/zlib-1.3.1/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
```
The /Applications/MyApp.app/Contents/Resources/Webserver/zlib-1.3.1/lib/libz.1.dylib is present and signed for further Apple's notarization.

./conftest in another terminal window has the same result.

This error happens only when compiling inside a folder with an .app extension (which is assumed to be an application by macOS).
If I use the `--prefix` toward a folder without the .app extension, everything works fine.

Among every sources I compiled, curl is the only one causing me this.

I looked up to what could have changed from macOS 13 to 14 but I didn't find anything.

### I expected the following

It should compile as exepected.

### curl/libcurl version

curl 8.7.1

### operating system

macOS 14

**Comment by bagder** [comment]
I believe this is rather something your system does that needs to be managed. curl's configure basically works the same way it has done for decades. It will build a `conftest` program to test for various things.

**Comment by mpepito13** [comment]
I think so but I don’t know what may have changed, what should be done and to whom I could ask

**Comment by bagder** [comment]
Me neither. You should ask the vendor of your operating system what it means and what to do about it. This is not a curl bug.
