### ISSUE TITLE
Unix socket URL support

### ISSUE THREAD

**Issue by silverwind** [curl/curl#1338]
Currently to connect to a http unix socket at `/tmp/sock`, one has to do

```
curl --unix-socket /tmp/sock http://anyhost
```

There is a somewhat common but non-standard URL scheme for http(s) unix sockets using the protocols `http+unix` and `https+unix` protocols and a percent-encoded path as the hostname (necessary to the path can be parsed). A example invocation could be:

```
curl http+unix://%2Ftmp%2Fsock
```

If one attempts this right now, curl shows:

```
curl: (1) Protocol "http+unix" not supported or disabled in libcurl
```

Is this something curl wants to support?

**Comment by frenche** [comment]
IMO unix-socket support should be a simple tunneling feature in curl instead of trying to invent new protocols (which matches the way curl currently implements it, apart of the disable-proxy thing).
And btw, the hostname is needed in HTTP for many reasons, not only to be able to connect to it.

**Comment by bagder** [comment]
I'm with @frenche here and I don't see any point in supporting a non-standard scheme that doesn't even seem to work very well. When I tried to find some tools/libraries out in the wild that support URL schemes like that I came back empty handed (not saying such tools don't exist, just that I didn't find any).

**Comment by silverwind** [comment]
As for tools supporting it, I found:

- https://github.com/httpie/httpie-unixsocket
- https://github.com/msabramo/requests-unixsocket

Guess it's not worth it to support, as that scheme really reduce command length if one has to send the Host header manually if required.
