### ISSUE TITLE
curl: (35) mbedTLS: ssl_init failed when compiled with mbedtls 3.6

### ISSUE THREAD

**Issue by orangepizza** [curl/curl#13385]
### I did this

./configure --with-mbedtls
make
make install 
and call any https website

### I expected the following

prints whatever on site:
with printf debug on mbedtls side: 
* mbedTLS: psa_init 0
/home/c/mbedtls-3.6.0/library/ssl_tls.c:1339: The SSL configuration is TLS 1.3 or TLS 1.2.
/home/c/mbedtls-3.6.0/library/ssl_tls.c:1381: no RNG provided
* mbedTLS: ssl_init failed

it was because mbedtls_ssl_setup() was called before mbedtls_ssl_conf_rng, so moving ssl_setup code downward is downward was enough. more things will needed to enable tls1.3 on it (mbedtls 3.6 now supports that)

### curl/libcurl version

curl 8.7.1

### operating system

ubuntu 22.04

**Comment by bagder** [comment]
Fixed since #13314 ...

**Comment by orangepizza** [comment]
ouch for using release version, not master branch
guess I'd better spend more time about bring tls1.3 by mbedtls than
