### ISSUE TITLE
Segfault 

### ISSUE THREAD

**Issue by peter17** [curl/curl#13390]
### I did this

I am running Curl through a PHP script. I encounter a segmentation fault on a URL, which I cannot disclose.

I reproduced the segfault on both Mageia 9 package and php:8.3.4-fpm Docker container (Debian based)

My PHP script crashes with message "Segmentation fault". I installed the debug packages and ran the script again. I obtained the following stack trace:

```
#0  0x00007ffff7c27ab7 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffff77657b7 in memcpy (__len=332, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string_fortified.h:29
#2  on_frame_recv (session=<optimized out>, frame=0x1296548, userp=0x12a5300) at http2.c:912
#3  0x00007ffff770ddda in nghttp2_session_mem_recv () from /lib64/libnghttp2.so.14
#4  0x00007ffff7764387 in h2_process_pending_input (cf=cf@entry=0x12a5300, data=data@entry=0x11a0dd0, err=err@entry=0x7fffffff97ac) at http2.c:1472
#5  0x00007ffff7764e77 in cf_h2_recv (cf=0x12a5300, data=0x11a0dd0, buf=<optimized out>, len=16384, err=0x7fffffff97ac) at http2.c:1848
#6  0x00007ffff7780529 in Curl_read (data=data@entry=0x11a0dd0, sockfd=<optimized out>, 
    buf=buf@entry=0x11d4300 "HTTP/2 301 \r\nserver: nginx/1.19.8\r\ndate: Tue, 16 Apr 2024 13:32:05 GMT\r\ncontent-type: text/html; charset=utf-8\r\nlocation: https://www.XXXXXX.lt/7kh3w2p-q5snk6j1/\r\nx-powered-by: Nette Framework 3\r\nset-c"..., sizerequested=sizerequested@entry=16384, n=n@entry=0x7fffffff9810) at sendf.c:417
#7  0x00007ffff7792369 in readwrite_data (comeback=0x7fffffff986f, done=0x7fffffff986d, didwhat=<synthetic pointer>, k=0x11a0ea8, conn=0x11b5b60, data=0x11a0dd0) at transfer.c:461
#8  Curl_readwrite (conn=0x11b5b60, data=data@entry=0x11a0dd0, done=done@entry=0x7fffffff986d, comeback=comeback@entry=0x7fffffff986f) at transfer.c:1111
#9  0x00007ffff7777b8c in multi_runsingle (multi=multi@entry=0x1168850, nowp=nowp@entry=0x7fffffff98d0, data=data@entry=0x11a0dd0) at multi.c:2436
#10 0x00007ffff777958e in curl_multi_perform (multi=0x1168850, running_handles=running_handles@entry=0x7fffffff99c0) at multi.c:2714
#11 0x00007ffff7a19c88 in zif_curl_multi_exec (execute_data=0x7ffff7816e40, return_value=0x7ffff78169a0) at /usr/src/debug/php-8.3.4-4.mga9.x86_64/ext/curl/multi.c:230
#12 0x00000000008d2aea in execute_ex ()
#13 0x00000000008f3dfe in zend_generator_resume ()
#14 0x00000000008f4cc9 in zend_generator_iterator_rewind ()
#15 0x0000000000877cfe in zend_fe_reset_iterator ()
#16 0x000000000088c377 in ZEND_FE_RESET_R_SPEC_VAR_HANDLER ()
#17 0x00000000008cc6f5 in execute_ex ()
#18 0x00000000008f3dfe in zend_generator_resume ()
#19 0x00000000008bf1ed in zend_fe_fetch_object_helper_SPEC ()
#20 0x00000000008d2403 in execute_ex ()
#21 0x00000000008d5ee7 in zend_execute ()
#22 0x000000000084f50a in zend_execute_scripts ()
#23 0x00000000007ce5b4 in php_execute_script ()
#24 0x000000000095f98d in do_cli ()
#25 0x000000000064792d in main ()
```

### I expected the following

No crash.

Do you have enough information with this stack trace? I am not sure I will be able to give more information...

### curl/libcurl version

Mageia 9 :
curl 7.88.1 (x86_64-mageia-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.13 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh/0.10.6/gnutls/zlib nghttp2/1.54.0
Release-Date: 2023-02-20

Docker container :
curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.11 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2023-02-20, security patched: 7.88.1-10+deb12u5

### operating system

Mageia 9 / php:8.3.4-fpm Docker container (Debian based)

**Comment by bagder** [comment]
> Do you have enough information with this stack trace

No we need more. But perhaps more important, we have done 14 releases after the version you use and it is likely that your problem already has been addressed. It would make sense to try the same thing but using libcurl 8.7.1 instead before spending much time on researching the crash.

If it still crashes with 8.7.1 then things are a lot more interesting!
