### ISSUE TITLE
libcurl error 43 when performing HTTP POST on windows XP

### ISSUE THREAD

**Issue by GabrieleFrau** [curl/curl#1340]
### I compiled libcurl with both v140_xp and v141_xp toolset (vs2015 and vs2017) using cmake to create the solution (my win10 workstation has windows 7.1 sdk installed)

- [x] CURL_DISABLE_COOKIES 
- [x] CURL_DISABLE_CRYPTO_ATH
- [x] CURL_DISABLE_DICT
- [x] CURL_DISABLE_FILE
- [ ] CURL_DISABLE_FTP
- [x] CURL_DISABLE_GOPHER
- [ ] CURL_DISABLE_HTTP
- [x] CURL_DISABLE_IMAP
- [x] CURL_DISABLE_LDAP
- [x] CURL_DISABLE_LDAPS
- [x] CURL_DISABLE_POP3
- [x] CURL_DISABLE_PROXY
- [x] CURL_DISABLE_RTSP
- [x] CURL_DISABLE_SMTP
- [x] CURL_DISABLE_TELNET
- [x] CURL_DISABLE_TFTP
- [x] CURL_DISABLE_VERBOSE_STRINGS
- [x] CURL_HIDDEN_SYMBOLS
- [x] CURL_STATICLIB
- [ ] CURL_WINDOWS_SSPI
- [x] CURL_ZLIB 
- [ ] ENABLE_ARES
- [ ] ENABLE_CURLDEBUG
- [ ] ENABLE_DEBUG
- [ ] ENABLE_IPV6
- [ ] ENABLE_MANUAL
- [x] ENABLE_THREADED_RESOLVER
- [ ] ENABLE_UNIX_SOCKETS

### Any OS above XP works, Windows XP sp3 doesnt work with error 43 when performing a HTTP POST with form data

**Comment by bagder** [comment]
So if you enable `CURLOPT_VERBOSE` what's the last few lines you get?

Please show us an example libcurl-using source code that reproduces the problem!

**Comment by GabrieleFrau** [comment]
[this code](https://gist.github.com/GabrieleFrau/4d069dd7b79b0d649e0c2a291ae9b930) yields the same result as my project, ergo error 43 with no additional debug hints even when redirecting stderr to stdout in a cmd. 
I'll try recompiling with the all the debug flags on.

**Comment by bagder** [comment]
43 is `CURLE_BAD_FUNCTION_ARGUMENT` and my suspicion is that it is one of the places in lib/formdata.c that returns this code that is the one you experience. But I don't have XP myself and cannot reproduce this problem.

**Comment by GabrieleFrau** [comment]
I recompiled with `ENABLE_CURLDEBUG` and `ENABLE_DEBUG` to no avail.
I've just noticed that the problem lies with adding the file to the form. Just POSTing key-value pairs works

**Comment by bagder** [comment]
So maybe this line? https://github.com/curl/curl/blob/master/lib/formdata.c#L886

**Comment by GabrieleFrau** [comment]
It might be related to [Stat not working on windows xp with v140_xp](https://connect.microsoft.com/VisualStudio/feedback/details/1600505/stat-not-working-on-windows-xp-using-v14-xp-platform-toolset-vs2015) that might still be valid with v141_xp

**Comment by GabrieleFrau** [comment]
_Unfortunately_ I need c++14 support for other parts of the project so I will probably patch the code to replace stat with some non POSIX function like [GetFileSizeEx](https://msdn.microsoft.com/en-US/library/windows/desktop/aa364957(v=vs.85).aspx) or [GetFileAttributesEx](https://msdn.microsoft.com/en-US/library/windows/desktop/aa364946(v=vs.85).aspx).
Thanks for figuring out the exact line of code!

**Comment by jay** [comment]
I am not able to reproduce this. I took these steps:

Windows 7 SP1 x64:
- Install Visual Studio 2015 Community w/Update 3 (vs2015.3.com_enu.iso) and choose packages Visual C++, Windows 10 SDK (all), git for windows
- git clone curl repo (HEAD Is at 898b012)
- At command prompt curl/projects/ dir run `generate vc14`
- Open projects/VC14/curl-all.sln
- Change the active configuration to DLL Release|Win32
- For both projects (curl,libcurl) Configuration > General > Platform Toolset > v140_xp
- Build solution
- Copy build\Win32\VC14\DLL Release\curl.exe and libcurl.dll over to XP

Windows XP SP3 x86:
- Install [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587) (on XP that automatically installs universal CRT as well)
- Create a file a.txt with data: `test`
- In a command window run `socat tcp-listen:8000,reuseaddr,fork -`
- In a second command window run `curl -v -Ffile=@a.txt -Fkey=value http://localhost:8000/`

No error occurs. This is the data sent by curl:
~~~
POST / HTTP/1.1
Host: 192.168.1.80:8000
User-Agent: curl/7.54.0-DEV
Accept: */*
Content-Length: 284
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------398de5d3a7428686

--------------------------398de5d3a7428686
Content-Disposition: form-data; name="file"; filename="a.txt"
Content-Type: text/plain

test
--------------------------398de5d3a7428686
Content-Disposition: form-data; name="key"

value
--------------------------398de5d3a7428686--
~~~

**Comment by GabrieleFrau** [comment]
I forgot to mention that both curl and my project are compiled with the`/MT` switch so everything is statically linked. The DLL is required to work without any external DLL or additional setups. I am not sure universal CRT is required considering everything works on any machine that's not windows XP. I did read something about the toolset mixing the windows7.1 SDK and windows 10 sdk. Running procmon with curl DOES show the program searching api-ms-win-crt-runtime.dll and the such unsuccessfully

**Comment by jay** [comment]
> I forgot to mention that both curl and my project are compiled with the/MT switch so everything is statically linked.

Ok. It is better to install the redist if you can. I can reproduce if both projects (curl,libcurl) Configuration > C++ > Code Generation > Runtime Library > Multi-threaded (/MT).

Maybe the static CRT that Visual Studio 2015 Update 3 uses does not have the stat fix?

/cc @JamesMcNellis

**Comment by GabrieleFrau** [comment]
I've managed to workaround the problem by ignoring  the warning **LNK4098**: about **LIBCMT** conflicting with another library.Mind you, **everything was built with the /MT switch and there are no dependencies besides libcurl**. Apparently the toolset didn't apply the right switches and some dynamic libs still linger in the code confliting with the static LIBCMT which is one the required runtime libs.
This feels like a hack to me, but I'll close the issue until further developments/findings considering it's not really an issue with CURL.

**Comment by tanghongri** [comment]
2017年4月11日确认安装Microsoft Visual C++ 2015 Redistributable Update 3可以解决这个问题
