### ISSUE TITLE
curl 7.50.1 switch off SSL session id, but it is back in curl 7.52.0

### ISSUE THREAD

**Issue by lijian996** [curl/curl#1341]
### I did this
The client use curl 7.52.0 to access https two-way authentication,  then I find that the client hello handshake protocols hold the session id. 
But I remember that:
    Fixed in 7.50.1 - August 3 2016 
    • TLS: switch off SSL session id when client cert is used

Why the SSL session id is back now? 
Does it matter with the modification on this issue https://curl.haxx.se/bug/?i=1127 ?

I expect your reply, thank you.

### I expected the following
After curl 7.50.1 , client hello handshake protocol does not hold SSL session id .
### curl/libcurl version
curl 7.50.1 
curl 7.52.0
[curl -V output]

### operating system
linux

**Comment by bagder** [comment]
Can you please tell us your curl -V output? (preferably in both versions you compare)

**Comment by lijian996** [comment]
I have test several version,  client hello handshake protocol does not holds SSL session id in 7.50.3, 7.51.0, but 7.52.0 and 7.52.1 hold. I compare the codes bettween 7.51.0 and 7.52.0 .
I find a doubtful. I think curl uses Curl_ssl_addsessionid then call Curl_clone_ssl_config to add some configurations. Curl_clone_ssl_config has been changed to Curl_clone_primary_ssl_config in 7.52.0, and they perform similar function. But Curl_clone_primary_ssl_config does not set sessionid to FALSE when clientcert is used, wich is different from Curl_clone_ssl_config. 
I think the problem happens here very likely.

**Comment by lijian996** [comment]
@bagder any ideas ? wish your reply. Thank you.

**Comment by bagder** [comment]
This looks like a regression, yes.

**Comment by Rickeys666** [comment]
hi @bagder, 
Whether the issue is to be repaired in the future?

**Comment by lijian996** [comment]
hi @bagder,
 Shall we fix this issue in the latter versions?

**Comment by jay** [comment]
@lijian996 thanks for your report. This is a security issue and so it was discussed privately immediately after you reported it. The fix landed in 33cfcfd and will be in the next release of curl, scheduled to be released this Wednesday.
