### ISSUE TITLE
File name not be transformed

### ISSUE THREAD

**Issue by zhengqwe** [curl/curl#13420]
### I did this

Run `curl "https://archive.org/download/ucberkeley_webcast_EiUvYS2DT6I/CS%2061B%20Lecture%2029%20-%20Sorting%20I-EiUvYS2DT6I.mp4" -L -O`, saved file name is `CS%2061B%20Lecture%2029%20-%20Sorting%20I-EiUvYS2DT6I.mp4`

### I expected the following

Saved file name is `CS 61B Lecture 29 - Sorting I-EiUvYS2DT6I.mp4`

### curl/libcurl version

curl 8.7.1 (x86_64-w64-mingw32) libcurl/8.7.1 LibreSSL/3.8.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.4.0 nghttp3/1.2.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd

### operating system

Windows 10

**Comment by icing** [comment]
I believe the curl's handling is correct. There are lots of security issues around decoding the file name. Imagine it results in characters not permitted in the file system (/ or \) or attempting path traversals.

**Comment by bagder** [comment]
This is also exactly how the feature is documented to work.
