### ISSUE TITLE
Version 8.6.0 and 8.7.1 fails to compile for CentOS 7

### ISSUE THREAD

**Issue by kunkanon** [curl/curl#13443]
### I did this

I compiled curl version 8.7.1, 8.6.0 and 8.5.0
Error occurs in versions 8.7.1 and 8.6.0

Version 8.5.0 was generated with these packages and protocols:
**curl 8.5.0** (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/1.1.1w zlib/1.3.1 brotli/1.0.9 zstd/1.5.5 c-ares/1.10.0 libidn2/2.3.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.11.0 nghttp2/1.33.0 librtmp/2.3 libgsasl/1.8.0 OpenLDAP/2.5.17
Release-Date: 2023-12-06
**Protocols**: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
**Features**: alt-svc AsynchDNS brotli gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL TLS-SRP UnixSockets zstd

Configure:
[configure.txt](https://github.com/curl/curl/files/15064621/configure.txt)

Log curl 8.7.1
[error_curl8.7.1_centos7.txt](https://github.com/curl/curl/files/15064533/error_curl8.7.1_centos7.txt)
Log curl 8.6.0
[error_curl8.6.0_centos7.txt](https://github.com/curl/curl/files/15064534/error_curl8.6.0_centos7.txt)

Thanks.

### I expected the following

Build successfully.

### curl/libcurl version

curl 8.6.0 and 8.7.1

### operating system

CentOS Linux release 7.9.2009 (Core)
Linux ec2.internal 3.10.0-1160.114.2.el7.x86_64

**Comment by bagder** [comment]
Fixed in 978790298c23c529a673f32c91bf8488d3f3e3b8 I believe. That change makes `--disable-docs` imply `--disable-manual`.

**Comment by kunkanon** [comment]
Hello,
Thank you.
The issue has been solved when pass the parameters: 
--disable-manual --disable-docs

curl 8.7.1 (x86_64-pc-linux-gnu) libcurl/8.7.1 OpenSSL/1.1.1w zlib/1.3.1 brotli/1.0.9 zstd/1.5.5 c-ares/1.10.0 libidn2/2.3.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.11.0 nghttp2/1.33.0 librtmp/2.3 libgsasl/1.8.0 OpenLDAP/2.5.17
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL TLS-SRP UnixSockets zstd
