### ISSUE TITLE
version 8.7.1 fails to compile for IOS SDK 17.2

### ISSUE THREAD

**Issue by softavail** [curl/curl#13441]
### I did this

I am on Mac OS Sonoma 14.0
I am on iOS SDKs:	iOS 17.2
The following environment is used
```
SDK_PATH=/Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk
CC=/Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
```
Configure is invoked as follow:
```
./configure --prefix=~/libcurl/out_ios/curl-8.7.1/ios64 --host arm64-apple-darwin --disable-shared --enable-static --disable-smtp --disable-pop3 --disable-imap --disable-ftp --disable-tftp --disable-telnet --disable-rtsp --disable-ldap --disable-ntlm  --with-secure-transport
```

### I expected the following

- Configure succeeds 
- Make fails with the following error
```
CC       libcurl_la-nonblock.lo
nonblock.c:82:4: error: "no non-blocking method was found/used/set"
#  error "no non-blocking method was found/used/set"
   ^
```

### curl/libcurl version

curl 8.7.1

### operating system

Darwin mac-880.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64 x86_64

**Comment by dfandrich** [comment]
curlx_nonblock expects one of five different methods of setting nonblocking
mode to be available. Which one does iOS 17.2 support, and can you tell why it
wasn't detected in configure?  It's probably one of the first to methods.

**Comment by bagder** [comment]
I presume it worked in a previous version? Which non-blocking method did it select then?

The key to configure problems is often found in `config.log` after the fact, looking at the errors around the check in question.

**Comment by softavail** [comment]
In config.log there is an output bellow
```
configure:44230: checking how to set a socket into non-blocking mode 
configure:44243: result: unknown
configure:44246: WARNING: cannot determine non-blocking socket method.
```

**Comment by softavail** [comment]
Solved

I fixed the warning in `config.log` explaining that CFLAGS should not contain include directories. I moved include paths into CPPFLAGS instead and it get compiled :)

What was the waring in `config.log`
```
configure:4319: CFLAGS note: CFLAGS should only be used to specify C compiler flags, not include directories. Use CPPFLAGS for: -I/Applications/Xcode-15.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/usr/include
```

Thank you for the support

**Comment by bagder** [comment]
thanks for the update, glad you made it work!
