### ISSUE TITLE
test 345 fails on AppVeyor

### ISSUE THREAD

**Issue by bagder** [curl/curl#13458]
After 00bef95946d3 (came via #13432) it seems test 345 permafails on some (?) appveyor builds.

[example log](https://ci.appveyor.com/project/curlorg/curl/builds/49679114/job/3k3uj70qqo1v67a1?fullLog=true)

### curl/libcurl version

git master

### operating system

Windows

**Comment by bagder** [comment]
Possibly related to the ftruncate replacement function we use for Windows?

https://github.com/curl/curl/blob/f33ee2e73bd228c61d71706a61a030d2096fee33/src/tool_cb_see.c#L108-L119

It seems Windows has a [_chsize_s](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/chsize-s?view=msvc-170) function we could perhaps rather use there?

**Comment by vszakats** [comment]
I wonder if the manual override of `HAVE_FTRUNCATE` in `src/tool_cb_see.h` plays a role in this:
https://github.com/curl/curl/blob/f33ee2e73bd228c61d71706a61a030d2096fee33/src/tool_cb_see.h#L28-L38

In any case such override should be done in `curl_setup.h` to apply for all code in unity mode.

Haven't confirmed, but the problem could be that the replacement function isn't used in `tool_operate.c`.
