### ISSUE TITLE
Unable to upload file with curl when --limit-rate is set to specific value

### ISSUE THREAD

**Issue by TKTim** [curl/curl#13460]
### I did this

This command is for upload a xml file on to my server's interface.
Server is using C# .Net MVC.
```
bash -c 'curl --connect-timeout 10 -H "Content-Type: text/xml; charset=utf-8"  -H "SOAPAction:http://tempuri.org/UploadProcessResult" -d @redhat9-1AA2.xml -o redhat9-1AA2_output.xml --limit-rate 100K -S -k http://192.168.30.5/SIP/Interface/Interface.asmx'
```

### I expected the following

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  432k  100   393  100  431k      9  10189  0:00:43  0:00:43 --:--:--  9762
```
* The file is 600 KB
* When I remove " --limit-rate 100K ", It succeeds.
* When I change " --limit-rate 100K " to " --limit-rate 10K ", It succeeds.
* When I change " --limit-rate 100K " to " --limit-rate 1000K ", It succeeds.
* When I change " --limit-rate 100K " to " --limit-rate 200K ", It fails.

### curl/libcurl version

```
curl 7.76.1 (x86_64-redhat-linux-gnu) libcurl/7.76.1 OpenSSL/3.0.7 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.10.4/openssl/zlib nghttp2/1.43.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

RedHat 9

**Comment by bagder** [comment]
Note that you are using a three year old curl version.

Since e492c7c524263e47844ec9354102fcf200e686a8 we have test cases verifying this functionality, which indicates that current curl supports this fine.

**Comment by TKTim** [comment]
@bagder Thanks for the reply, I will give the new version a try.

**Comment by bagder** [comment]
Presumed to be fixed already.
