### ISSUE TITLE
Build in mingw for libcurl with OpenSSL and HTTP2 support fails with "undefined reference to 'sk_num'" in openssl.c

### ISSUE THREAD

**Issue by reesul** [curl/curl#1347]
I built nghttp2 and openssl (1.1.0e), and ran ./configure in the mingw32 shell of msys2.  The output from configure told me that openssl and http2 were both enabled.  When calling make, shows CC  libcurl_la-foo.lo for a number of files (~50), and then gets down to the line "CCLD libcurl.la", and fails here.  I get about 15 messages stating an undefined reference (e.g. vtls/.libs/libcurl_la-openssl.o:openssl.c:(.text+0xbda): undefined reference to `sk_num' OR vtls/.libs/libcurl_la-openssl.o:openssl.c:(.text+0x48f9): undefined reference to `ERR_free_strings').  Following these lines are the actual error messages:

vtls/.libs/libcurl_la-openssl.o:openssl.c:(.text+0x4912): undefined reference to 'SSL_COMP_free_compression_methods'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:893: libcurl.la] Error 1
make[2]: Leaving directory '/c/curl2/curl-7.53.1/lib'
make[1]: *** [Makefile:734: all] Error 2
make[1]: Leaving directory '/c/curl2/curl-7.53.1/lib'
make: *** [Makefile:893: all-recursive] Error 1

I am building curl/libcurl version 7.53.1 on Windows 10 (64-bit) using msys2 for mingw32 build.  Looking through the openssl.c file in question, a few of the "undefined references" are in fact in the in the file, but there are no instances of sk_num, sk_value, or sk_pop_free which the make command determines as undefined references.  Any idea what is wrong here?

**Comment by jay** [comment]
This is an issue tracker, if you have questions that you are unsure if they are a bug please ask them on the mailing list. Since you asked this there as well I [answered](https://curl.haxx.se/mail/lib-2017-03/0081.html) there. Please follow up on the mailing list.
