### ISSUE TITLE
Ambiguous error message when decompressing brotli stream

### ISSUE THREAD

**Issue by GreenYun** [curl/curl#13488]
### I did this

1. compile curl with broti support
2. run curl command line: `curl --compressed -o example https://example.com`
3. got "curl: (23) Failed writing received data to disk/application" while the downloaded file is intact

### I expected the following

The error message should be omitted if end of downloading stream encountered.

After digging into the code as well as the server response, I found:

1. the server did not send `Content-Length` and curl may not know when the stream ends (current Nginx implementation will strip `Content-Length` because the stream length after compressed is not predictable)
2. Botli support in curl returns CURLE_WRITE_ERROR when unexpectedly reaching end of stream, ref: https://github.com/curl/curl/blob/c8e0cd1de8db9eba00c284ebf5fd5b3cba263e06/lib/content_encoding.c#L676

P.S. Zstd writer in curl will not return CURLE_WRITE_ERROR when `Content-Length` is not specified in response header.

### curl/libcurl version

curl 8.7.1

### operating system

macOS 12.7.4

**Comment by bagder** [comment]
I believe this is already fixed in master via b30d694a027eb771c02a3db0dee0ca03ccab7377.

**Comment by bagder** [comment]
First reported in #13209
