### ISSUE TITLE
wolfSSL HTTP/3 peer verification is lacking

### ISSUE THREAD

**Issue by bagder** [curl/curl#13487]
### I did this

build curl with ngtcp2 + nghttp3 + wolfSSL

Issue a request that should fail the certificate check, like this:

~~~
curl --http3 --resolve example:443:151.101.129.91 https://example
~~~

The problem is likely here:

https://github.com/curl/curl/blob/c8e0cd1de8db9eba00c284ebf5fd5b3cba263e06/lib/vquic/vquic-tls.c#L325-L330

This does not really verify the peer certificate. For TCP connections this works as it is wired into the wolfSSL connect() implementation and gives a special return code on such a fail.

### I expected the following

A request to a server that fails the check should error out.

### curl/libcurl version

git master

### operating system

independent

**Comment by bagder** [comment]
@icing feel free to edit/follow-up with corrections or added details as you see fit

**Comment by bagder** [comment]
This appears to be a wolfSSL problem, would you agree @icing? I see nothing in the [wolfSSL docs](https://www.wolfssl.com/doxygen/group__Setup.html#gab9b75f5fb10ce88f0026c57716858074) that suggests that this would not work for QUIC connections but only for TCP. Or am I missing something?

**Comment by icing** [comment]
I agree that I found no obvious way to do this with the wolfSSL API.

**Comment by bagder** [comment]
Since we believe this problem is in the wolfSSL end, I'm closing this issue.

**Comment by julek-wolfssl** [comment]
Its a curl bug. Fix @ https://github.com/curl/curl/pull/13680.
