### ISSUE TITLE
CURL_VERSION_GSSAPI is not display on curl tool.

### ISSUE THREAD

**Issue by talregev** [curl/curl#13492]
### I did this

compile curl with krb5 with the flag (use_gssapi)
then on curl:
./curl --version
Not version nor the library that it compile like other similar vars do.

### I expected the following

I expect to show the lib name I compile with the version number (krb5-gssapi v1.21.2).

### curl/libcurl version

curl version 7.8.1 

### operating system

wsl2 ubuntu 22.04

**Comment by bagder** [comment]
`GSS-API` appears as a listed features in the `Features` list.

**Comment by bagder** [comment]
The library is not though. `curl_version_info()` does not export that information.

**Comment by talregev** [comment]
Thank you for your respond.
Can it export the lib name + version, like curl doese for other libs / other version vars?

**Comment by bagder** [comment]
It certainly *could* do that, yes. It just needs someone to do the work and write the code...
