### ISSUE TITLE
libcurl protocol POP3

### ISSUE THREAD

**Issue by jkiape** [curl/curl#1355]
_**curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteMemoryCallback)**_

after

_**curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "STAT")**_

NOT WORKING !

**Comment by bagder** [comment]
Please give us more details. Exactly what did you do, what did you expect would happen that didn't happen and what happened instead? And which libcurl version do you use on what platform?

**Comment by jkiape** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
 
#include <curl/curl.h>
 
struct MemoryStruct 
{
	char *memory;
	size_t size;
};
 
static size_t
WriteMemoryCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
	size_t realsize = size * nmemb;
	struct MemoryStruct *mem =(struct MemoryStruct *)userp;
	
	mem->memory =(char *)realloc(mem->memory, mem->size + realsize + 1);
	if (mem->memory == NULL)
	{
		/* out of memory! */ 
		printf("not enough memory (realloc returned NULL)\n");
		return 0;
	}
	
	memcpy(&(mem->memory[mem->size]), contents, realsize);
	mem->size += realsize;
	mem->memory[mem->size] = 0;
	
	return realsize;
}
 
int main(void)
{
  CURL *curl_handle;
  CURLcode res;
 
  struct MemoryStruct chunk;
 
  chunk.memory =(char *)malloc(1);  /* will be grown as needed by the realloc above */ 
  chunk.size = 0;    /* no data at this point */ 
 
  curl_global_init(CURL_GLOBAL_ALL);
 
  /* init the curl session */ 
	curl_handle = curl_easy_init();
	curl_easy_setopt(curl_handle, CURLOPT_USERNAME, "***************");
    curl_easy_setopt(curl_handle, CURLOPT_PASSWORD, "***************");
	curl_easy_setopt(curl_handle, CURLOPT_URL, "pop3s:// pop.mail.yahoo.com:995");
	curl_easy_setopt(curl_handle, CURLOPT_USE_SSL, CURLUSESSL_ALL); 
    curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0); 
    curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0);
	curl_easy_setopt(curl_handle, CURLOPT_CUSTOMREQUEST, "STAT"); // **## I want to retrieve the number of emails and copy it to a string**
	curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);
 	curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, (void *)&chunk);
	res = curl_easy_perform(curl_handle);

	printf("STAT returns : %s\n",(char *)chunk.memory); //**## NOTHING PRINTS HERE !!!**
  
 
  /* cleanup curl stuff */ 
  curl_easy_cleanup(curl_handle);
 
  free(chunk.memory);
 
  /* we're done with libcurl, so clean it up */ 
  curl_global_cleanup();
 
  return 0;
}

**Comment by gvanem** [comment]
Add a:
```
curl_easy_setopt(curl_handle, CURLOPT_NOBODY, 1L);
```
But there's other bugs in your program.

**Comment by jkiape** [comment]
@gvanem 
It works fine !
Thank you very much.

**Comment by bagder** [comment]
Awesome, case closed!
