### ISSUE TITLE
with the location flag, getting "curl: (18) transfer closed with X bytes remaining to read"

### ISSUE THREAD

**Issue by kasperk81** [curl/curl#13558]
### I did this

```sh
$ curl -sSL -XHEAD http://apt.llvm.org/jammy 
curl: (18) transfer closed with 586 bytes remaining to read
```

### I expected the following

no error.

just like when executed without the location flag:
```sh
$ curl -sS -XHEAD http://apt.llvm.org/jammy
$ echo $?
0
```

### curl/libcurl version

8.5.0

### operating system

ubuntu 24.04

**Comment by bagder** [comment]
This is design. It does not happen without `-L` because then the server sends no body.

If you want to do a HEAD and following redirects, I recommend `curl -LI http://apt.llvm.org/jammy`
