### ISSUE TITLE
(MSYS2/MinGW/GCC 14) nonblock.c: In function 'curlx_nonblock': no non-blocking method was found/used/set

### ISSUE THREAD

**Issue by LigH-de** [curl/curl#13579]
### I did this

Compiling in media-autobuild suite for Win32 target
```
  CC       libcurl_la-nonblock.lo
../../lib/nonblock.c: In function 'curlx_nonblock':
../../lib/nonblock.c:82:4: error: #error "no non-blocking method was found/used/set"
   82 | #  error "no non-blocking method was found/used/set"
      |    ^~~~~
make[2]: *** [Makefile:2831: libcurl_la-nonblock.lo] Error 1
```
[logs.zip](https://github.com/curl/curl/files/15273796/logs.zip)

HAVE_IOCTLSOCKET_FIONBIO should be defined as 1 in lib/config-win32.h

### I expected the following

successful compilation

### curl/libcurl version

HEAD

### operating system

MSYS2/MinGW

**Comment by bagder** [comment]
How do you build curl?

**Comment by LigH-de** [comment]
I start the media-autobuild_suite.bat and wait...

Details are in the attached log file. Head of the make log:
```
CPPFLAGS:  -DGNUTLS_INTERNAL_BUILD -DNGHTTP2_STATICLIB -DPSL_STATIC
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
make -j4 
```

Configuration:
`$ ../configure --prefix=/local32 --disable-shared --enable-static --bindir=/local32/bin-global --with-nghttp2 --with-openssl --without-gnutls --without-mbedtls --without-libssh2 --without-random --without-ca-bundle --without-ca-path --without-librtmp --with-brotli --enable-sspi --disable-debug`

**Comment by vszakats** [comment]
Normally for mingw-w64, `HAVE_IOCTLSOCKET_FIONBIO` is defined by autotools via the generated `curl_config.h`.
Since it isn't, it suggests that the auto-detection fails for some unrelated reason, maybe due to the extra passed options.
Peeking into `config.log` could give the answer.

**Comment by LigH-de** [comment]
Yesterday and the day before it still compiled...

**Comment by vszakats** [comment]
Thanks. It's a legit complaint from the compiler, but this check has been like this since forever.

Would this be explained by a compiler upgrade? gcc 14 just happened.

**Comment by LigH-de** [comment]
Indeed possible...

> gcc.exe (Rev2, Built by MSYS2 project) 14.1.0

**Comment by vszakats** [comment]
Would this patch fix the build for you?:
https://github.com/curl/curl/pull/13587/commits/4bab28f0661d95bb6421d9ae3630cb1cca2fc487

**Comment by LigH-de** [comment]
I have only little experience in editing the shall scripts used by the suite.
Are you able to provide this change as diff patch? Maybe github can do that if I just know how to build the matching URL...

**Comment by vszakats** [comment]
This link gives you the raw .diff:
https://github.com/curl/curl/commit/4bab28f0661d95bb6421d9ae3630cb1cca2fc487.diff

**Comment by LigH-de** [comment]
Yes, I discovered how to add this patch and curl builds again.

**Comment by vszakats** [comment]
@LigH-de Thanks for testing, and reporting! The fix is merged now.

**Comment by mickmack1213** [comment]
Sorry for reviving this. I just wanted to point [this line](https://github.com/curl/curl/blob/master/m4/curl-functions.m4#L3253) out. I think a similar issue might happen at some point, as the wrong pointer type is passed (long instead of int though)

**Comment by vszakats** [comment]
@mickmack1213 Can you paste which line do you mean or give a permalink?

**Comment by LigH-de** [comment]
> [this line](https://github.com/curl/curl/blob/master/m4/curl-functions.m4#L3253)

This actually **is the permalink**, it highlights the matching line 3253 in the source view in a reasonably modern webbrowser.

```
  if test "$curl_cv_func_ioctlsocket_camel" = "yes"; then
    AC_MSG_CHECKING([if IoctlSocket FIONBIO is compilable])
    AC_COMPILE_IFELSE([
      AC_LANG_PROGRAM([[
        $curl_includes_bsdsocket
      ]],[[    # <===
        long flags = 0;
        if(0 != IoctlSocket(0, FIONBIO, &flags))
          return 1;
      ]])
    ],[
      AC_MSG_RESULT([yes])
      tst_compi_ioctlsocket_camel_fionbio="yes"
    ],[
      AC_MSG_RESULT([no])
      tst_compi_ioctlsocket_camel_fionbio="no"
    ])
  fi
```

**Comment by vszakats** [comment]
Ah okay, thanks for the snippet.

(In my browser, your link points to `]],[[`. This will change if anything is pushed to master. By permalink, I mean one that contains a commit hash to avoid ambiguity: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)

**Comment by vszakats** [comment]
Do you have a documentation link for `IoctlSocket()`?

**Comment by LigH-de** [comment]
The official [Microsoft Winsock2 documentation](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-ioctlsocket) specifies the `flag` (or `iMode` in the example there) as `u_long` (assuming that means `unsigned long`).

**Comment by vszakats** [comment]
Are you sure this snippet is for Windows? the casing of the function looks different.

**Comment by LigH-de** [comment]
No, I only remembered that IoctlSocket is one of the functions in Winsock[2]. But now I noticed that the presence of `$curl_includes_bsdsocket` slipped me; and [BSD Sockets](https://www.keil.com/pack/doc/mw6/Network/html/group__bsd__routines.html#ga0b42eb9e32b55aff7130ef48afd8b885) are quite the same.
