### ISSUE TITLE
error when make,how to  resolve ?  error massage :final link failed: symbol needs debug section which does not exist

### ISSUE THREAD

**Issue by musexiaoluo** [curl/curl#13607]
### I did this

./configure --host=arm-linux   CC=/opt/gcc-r3/gcc-sigmastar-9.1.0-2019.11-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-9.1.0-gcc    --with-mbedtls=/usr/local/ --enable-optimize --disable-debug --disable-curldebug --disable-symbol-hiding --disable-dict --disable-gopher --disable-imap --disable-pop3 --disable-rtsp --disable-smtp --disable-telnet --disable-sspi --disable-smb --disable-ntlm-wb --disable-tls-srp --disable-soname-bump --disable-manual --disable-file --disable-ldap --disable-tftp --enable-http --disable-ftp --disable-ipv6  --without-debug

error when make,how to  resolve ?

error massage :

/opt/gcc-r3/gcc-sigmastar-9.1.0-2019.11-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: /usr/local//lib/libmbedtls.a(debug.o)(.text+0x21a): unresolvable R_ARM_THM_CALL relocation against symbol `vsnprintf@@GLIBC_2.4'
/opt/gcc-r3/gcc-sigmastar-9.1.0-2019.11-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: final link failed: symbol needs debug section which does not exist
collect2: error: ld returned 1 exit status
Makefile:1696: recipe for target 'libcurl.la' failed

![image](https://github.com/curl/curl/assets/31032620/20e8c61b-4932-4cba-be9e-00b0c4710d0b)

### curl/libcurl version

curl8.5

### operating system

linux

**Comment by musexiaoluo** [comment]
![image](https://github.com/curl/curl/assets/31032620/a4763cc7-1a2b-4258-b161-9637d62011d2)

**Comment by bagder** [comment]
> libmbedtls.a(debug.o)(.text+0x21a): unresolvable R_ARM_THM_CALL relocation against symbol `vsnprintf@@GLIBC_2.4'

**libmbedtls.a** is a key there. That's your mbedTLS library that the linker does not like.
