### ISSUE TITLE
`wakeup_create` implementations "leak" file descriptors to process children

### ISSUE THREAD

**Issue by unlightable** [curl/curl#13618]
### I did this

`curl_multi_init()` is enough to create a `pipe` or a `socketpair` with no `FD_CLOEXEC`/`SOCK_CLOEXEC` set.

### I expected the following

A way to set those flags to not inherit file descriptors by fork-exec'ed children of the process.
Kinda related issue: https://github.com/curl/curl/issues/2252

### curl/libcurl version

master

### operating system

doesn't matter

**Comment by bagder** [comment]
Mentioned in the [TODO](https://curl.se/docs/todo.html#FD_CLOEXEC) since 0cbfff98953155c590f447f15422e78ca64d49c4
