### ISSUE TITLE
Disabling USE_UNIX_SOCKETS does not remove the use of AF_UNIX when compiling libcurl.

### ISSUE THREAD

**Issue by b5i** [curl/curl#13620]
### I did this

I tried to compile Curl using the curl_config.h in attachement 
[curl_config.h.zip](https://github.com/curl/curl/files/15296128/curl_config.h.zip) and with the `BUILDING_LIBCURL` and `HAVE_CONFIG_H` enabled. Changing  `AF_UNIX` to `AF_INET` in `src/socketpair.h` when defining `wakeup_create(p)` does the trick and libcurl builds successfully.

### I expected the following

The curl_config.h file contains `//#define USE_UNIX_SOCKETS 1` because ESP32 with FreeRTOS and the `xtensa-esp32-elf` toolchain don't support them. Therefore, `AF_UNIX` shouldn't be used when compiling libcurl as it would be undefined (error: `/src/socketpair.h:41:42: error: 'AF_UNIX' undeclared (first use in this function); did you mean 'AF_INET'?`). Would changing it to `AF_INET` when USE_UNIX_SOCKETS = 0 be a good workaround?

### curl/libcurl version

curl 8.8.0-DEV

### operating system

Darwin MBP-de-Antoine 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 arm64, compiling with `toolchain-xtensa-esp32@8.4.0+2021r2-patch5/xtensa-esp32-elf` from PlatformIO.

**Comment by bagder** [comment]
Does it actually still work then? Or is your build using the `Curl_socketpair()` "emulation" function?

**Comment by b5i** [comment]
> Does it actually still work then? 

Do you mean if libcurl builds? In that case yes when changing AF_UNIX to AF_INET. 
If you meant whether curl actually works when built that's what I'm testing right now with a simple project to make sure it's not broken.

> Or is your build using the `Curl_socketpair()` "emulation" function?
I guess so as HAVE_SOCKETPAIR is not defined in my curl_config.h.

**Comment by b5i** [comment]
I can confirm that I'm able to do POST and GET requests when compiling with the workaround.

**Comment by bagder** [comment]
Are you up for providing it as a PR?

**Comment by bagder** [comment]
Fixed in #13666
