### ISSUE TITLE
curl+openssl crashed 

### ISSUE THREAD

**Issue by xuvw** [curl/curl#13657]
### I did this

0   libsystem_pthread.dylib       	0x00000001f15ee54c pthread_rwlock_wrlock + 0 (inline_internal.h:87)
1   KNet                          	0x0000000108b52cf4 CRYPTO_THREAD_write_lock + 12 (threads_pthread.c:78)
2   KNet                          	0x0000000108b31b48 RAND_get_rand_method + 88 (rand_lib.c:851)
3   KNet                          	0x0000000108b320b8 RAND_status + 12 (rand_lib.c:960)
4   KNet                          	0x0000000108898118 rand_enough + 12
5   KNet                          	0x00000001088980ac ossl_seed + 64
6   KNet                          	0x0000000108898c10 ossl_connect_step1 + 1612
7   KNet                          	0x0000000108898220 ossl_connect_common + 232
8   KNet                          	0x0000000108896cf8 ossl_connect_nonblocking + 56
9   KNet                          	0x000000010889fff0 Curl_ssl_connect_nonblocking + 212
10  KNet                          	0x0000000108854a8c https_connecting + 68
11  KNet                          	0x00000001088549d4 Curl_http_connect + 320
12  KNet                          	0x000000010886ebb4 protocol_connect + 336
13  KNet                          	0x000000010886be20 multi_runsingle + 1944
14  KNet                          	0x000000010886b4a4 curl_multi_perform + 176
15  KNet                          	0x000000010884ad7c easy_transfer + 140
16  KNet                          	0x0000000108849b74 easy_perform + 404
17  KNet                          	0x00000001088499d4 curl_easy_perform + 32
18  KNet                          	0x000000010870c2c4 -[KNetDataTask startCurlLoading] + 1708 (KNetDataTask.m:408)
19  KNet                          	0x000000010870b744 -[KNetDataTask startLoading] + 188 (KNetDataTask.m:0)
20  KNet                          	0x000000010870b5b4 -[KNetDataTask resume_] + 220 (KNetDataTask.m:157)

### I expected the following

no crash 

### curl/libcurl version

curl 7.84.0 
OpenSSL 1.1.1k  25 Mar 2021

### operating system

iPhone14 OS version:17.3.1

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by xuvw** [comment]
> Thanks a lot for your report!
> 
> I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

This is occasional and difficult to reproduce.

**Comment by bagder** [comment]
Presumed fixed in modern versions.
