### ISSUE TITLE
curl_easy_perform() failed: Unsupported protocol (WSS)

### ISSUE THREAD

**Issue by Lifeda92** [curl/curl#13677]
### I did this

1. Downloaded .ZIP from: " [https://curl.se/download/curl-8.7.1.zip](https://curl.se/download/curl-8.7.1.zip) "
2. Builded using x86 Native Tools Command Prompt for VS 2019

set RTLIBCFG=static
nmake /f Makefile.vc mode=static vc=15 debug=yes

set RTLIBCFG=static
nmake /f Makefile.vc mode=static vc=15 debug=no

3. Added all dependends in project in properties.

4. Try using example code from: " [https://curl.se/libcurl/c/websocket.html](https://curl.se/libcurl/c/websocket.html) "

5. Got error: curl_easy_perform() failed: Unsupported protocol

### I expected the following

Success using WSS protocol.

### curl/libcurl version

libcurl version libcurl/8.7.1 Schannel WinIDN

### operating system

Windows 10

**Comment by vszakats** [comment]
WebSocket support is not yet enabled by default.

An option is coming up in 8.8.0 to enable it with this build method:
eb4fe6c6340c3d5b0c347c6e30be004d4f9117d7 #13232

Another way is the option `-DENABLE_WEBSOCKETS=ON` with CMake.
