### ISSUE TITLE
cmake build on linux fails

### ISSUE THREAD

**Issue by bagder** [curl/curl#1370]
### I did this

I just fixed a few mistakes that has made the recent tarballs broken for the cmake build, so I made my own tarball with the current git master:

    $ ./maketgz 7.54.0-test
    [unpack in a suitable fresh dir]
    $ cd curl-7.54.0-test
    $ mkdir cmake-build
    $ cmake ..
    $ make

The snapshots starting 2017-03-31 should have the correct tarballs so then you can download one from https://curl.haxx.se/snapshots/

### I expected the following

A successful build. Instead. I get this (the last set of lines in my terminal):

```
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/nss.c.o
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/polarssl.c.o
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/polarssl_threadlock.c.o
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/axtls.c.o
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/cyassl.c.o
[ 20%] Building C object lib/CMakeFiles/libcurl.dir/vtls/schannel.c.o
[ 21%] Building C object lib/CMakeFiles/libcurl.dir/vtls/darwinssl.c.o
[ 21%] Building C object lib/CMakeFiles/libcurl.dir/vtls/gskit.c.o
[ 21%] Building C object lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o
Linking C shared library libcurl.so
[ 21%] Built target libcurl
docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:51: warning: overriding recipe for target 'docs/curl.1'
docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:50: warning: ignoring old recipe for target 'docs/curl.1'
Scanning dependencies of target generate-curl.1
docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:51: warning: overriding recipe for target 'docs/curl.1'
docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:50: warning: ignoring old recipe for target 'docs/curl.1'
make[2]: page-header: Command not found
docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/build.make:51: recipe for target 'docs/curl.1' failed
make[2]: *** [docs/curl.1] Error 127
CMakeFiles/Makefile2:1118: recipe for target 'docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/all' failed
make[1]: *** [docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2

```

### curl/libcurl version

Current git master: f8952932e

### operating system

Linux. cmake 2.8.12.1

I suspect PR #1305 wasn't complete. Any ideas @Lekensteyn ?

**Comment by Lekensteyn** [comment]
(Had to run `./buildconf && ./configure` and obtain roffit before maketgz or it would fail in strange ways.)

Could not reproduce problem on Ubuntu 16.04 (cmake 3.5.1).
Reproduced on Ubuntu 14.04 (cmake 2.8.12.2).

Something is very wrong with the generation process, a list variable does not seem to be split up properly:
```
docs/curl.1: ../docs/cmdline-opts/abstract-unix-socket.d;anyauth.d;append.d;basic.d;cacert.d;...
docs/curl.1: ../docs/cmdline-opts/page-footer;page-header
```

I'll investigate further
