### ISSUE TITLE
urlencode data result not expect 

### ISSUE THREAD

**Issue by Skymemory** [curl/curl#13715]
### I did this

execute blow command:
`curl -s -o /dev/null -w '%{url_effective}' --get --data-urlencode 'paas-aiplatform-service/2022-03-22/aliyun@4d26e3b4-8a54-4a16-aae4-ac99dae37ce2-7274_jpg687995c2-fd20-4ca4-9b6d-2a09becf4ec1.png' ''`

output result:
`/?`

### I expected the following

expect output result is urlencoded data:
`paas-aiplatform-service%2F2022-03-22%2Faliyun%404d26e3b4-8a54-4a16-aae4-ac99dae37ce2-7274_jpg687995c2-fd20-4ca4-9b6d-2a09becf4ec1.png`

### curl/libcurl version

<img width="759" alt="curl-os-release" src="https://github.com/curl/curl/assets/19942947/46591e7d-b977-4c23-904d-baab74394c51">

### operating system

see above picture.

**Comment by pkropachev** [comment]
In case using newer version (`curl 8.8.0-DEV` from current `master` branch) I get the follwoing output:

```
curl: option --data-urlencode: error encountered when reading a file
curl: try 'curl --help' or 'curl --manual' for more information
```

Not sure that you use correct format of data for `--data`, `--data-urlencode` parameters.

**Comment by bagder** [comment]
If you don't want curl to treat the left side of the `@` as the name and the right side as a filename, I urge you to prefix the string with `=`, as that will then treat all the rest as "content" and it is probably what you want?

See [manpage section](https://curl.se/docs/manpage.html#--data-urlencode)

**Comment by Skymemory** [comment]
> If you don't want curl to treat the left side of the `@` as the name and the right side as a filename, I urge you to prefix the string with `=`, as that will then treat all the rest as "content" and it is probably what you want?
> 
> See [manpage section](https://curl.se/docs/manpage.html#--data-urlencode)

Yeah，thank you very much.
