### ISSUE TITLE
HEAD requests fail with: HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jeroen** [curl/curl#13725]
Users of the R bindings [found that](https://github.com/Bioconductor/BiocFileCache/issues/48) after a recent libcurl update, the following started failing: 

```sh
curl --compressed -IL "http://www.dropbox.com/s/srkb2ife75px2yz/modeling_results_BayesSpace_k09.Rdata?dl=1"
# HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (
```

If we disable HTTP/2 the request also errors but with `chunk hex-length char not a hex digit: 0x1f` error:

```sh
curl --compressed  -IL --http1.1 "http://www.dropbox.com/s/srkb2ife75px2yz/modeling_results_BayesSpace_k09.Rdata?dl=1"
# chunk hex-length char not a hex digit: 0x1f
```

### curl/libcurl version

I confirmed the problem started appearing on curl 8.6.0 and 8.7.1 on MacOS.

I also confirmed the problem did not appear on curl 8.4.0 on MacOS.

### operating system

MacOS

**Comment by jeroen** [comment]
FYI it is not just `http/2` it also happens with http 1.1.

**Comment by icing** [comment]
The server sends a response to the HEAD request which includes bytes after the headers. This is invalid HTTP (in 1.1 and 2). curl 8.4 ignored these bytes with a warning while 8.6 and newer fail.

I am working on a PR to get back the previous behaviour.
