### ISSUE TITLE
configure : Failed to find size of size_t

### ISSUE THREAD

**Issue by vortexilation** [curl/curl#13783]
### I did this

When trying to compile for/targeting OpenWrt x86_64 musl, I am getting the following : 
```
checking for struct timeval... no
checking size of size_t... configure: error: Failed to find size of size_t
```

From config.log : 
```
configure:34866: ccache x86_64-openwrt-linux-musl-gcc -c -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fno-caller-saves -fno-plt -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fhonour-copts -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -fmacro-prefix-map=/home/user/works/openwrt/build_dir/target-x86_64_musl/curl-8.8.0=curl-8.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -Werror-implicit-function-declaration -Wno-system-headers -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include conftest.c >&5
conftest.c:71:16: error: duplicate 'unsigned'
   71 | #define size_t unsigned int
      |                ^~~~~~~~
In file included from /usr/include/bits/endian.h:35,
                 from /usr/include/endian.h:24,
                 from /usr/include/sys/types.h:176,
                 from conftest.c:76:
/usr/include/bits/endianness.h:9:9: warning: "__BYTE_ORDER" redefined
    9 | #define __BYTE_ORDER __LITTLE_ENDIAN
      |         ^~~~~~~~~~~~
In file included from /home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/stddef.h:19,
                 from /usr/include/sys/types.h:144:
/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/bits/alltypes.h:5:9: note: this is the location of the previous definition
    5 | #define __BYTE_ORDER 1234
      |         ^~~~~~~~~~~~
In file included from /usr/include/sys/select.h:37,
                 from ../../../staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify/sys/select.h:22,
                 from /usr/include/sys/types.h:179:
/usr/include/bits/types/struct_timeval.h:11:3: error: unknown type name '__time64_t'; did you mean '__timer_t'?
   11 |   __time64_t tv_sec;            /* Seconds.  */
      |   ^~~~~~~~~~
      |   __timer_t
In file included from /usr/include/sys/select.h:39:
/usr/include/bits/types/struct_timespec.h:14:3: error: unknown type name '__time64_t'; did you mean '__timer_t'?
   14 |   __time64_t tv_sec;            /* Seconds.  */
      |   ^~~~~~~~~~
      |   __timer_t
conftest.c: In function 'main':
conftest.c:83:8: error: duplicate case value
   83 |        case (sizeof(size_t) == 1):;
      |        ^~~~
conftest.c:82:8: note: previously used here
   82 |        case 0:
      |        ^~~~
configure:34866: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.se/mail/"
| #define PACKAGE_URL ""
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_STDATOMIC_H 1
| #define HAVE_ATOMIC 1
| #define PACKAGE "curl"
| #define VERSION "-"
| #define OS "x86_64-openwrt-linux-gnu"
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_LDAP_SSL 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_CLOCK_GETTIME_MONOTONIC 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_CLOCK_GETTIME_MONOTONIC_RAW 1
| #define HAVE_LIBZ 1
| #define HAVE_LIBZSTD 1
| #define HAVE_ZSTD_H 1
| #define HAVE_ZSTD 1
| #define HAVE_LBER_H 1
| #define HAVE_LDAP_H 1
| #define HAVE_LDAP_URL_PARSE 1
| #define HAVE_LDAP_INIT_FD 1
| #define USE_OPENLDAP 1
| #define USE_IPV6 1
| #define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1
| #define HAVE_LIBSSL 1
| #define HAVE_OPENSSL_X509_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_RSA_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_CRYPTO_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_PEM_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_SSL_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_ERR_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL3 1
| #define HAVE_SSL_SET_QUIC_USE_LEGACY_CODEPOINT 1
| #define HAVE_OPENSSL_SRP 1
| #define CURL_CA_BUNDLE "/etc/ssl/certs/ca-certificates.crt"
| #define HAVE_LIBSSH2 1
| #define USE_LIBSSH2 1
| #define HAVE_IDN2_H 1
| #define HAVE_LIBIDN2 1
| #define HAVE_NGHTTP2_NGHTTP2_H 1
| #define USE_NGHTTP2 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_SYS_STAT_H 1
| #define size_t unsigned int
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| /* end confdefs.h.  */
| 
| #include <sys/types.h>
| 
| 
| int main (void)
| {
| switch(0) {
|        case 0:
|        case (sizeof(size_t) == 1):;
|      }
| 
|  ;
|  return 0;
| }
configure:34880: error: Failed to find size of size_t
```

gcc 14.1.0

full config.log : 
[config.log](https://github.com/curl/curl/files/15446074/config.log)

### I expected the following

curl configure script able to find sizeof of every types.

### curl/libcurl version

curl 8.8.0

### operating system

Debian SID glibc x86_64
Linux user 6.7.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1 (2024-04-24) x86_64 GNU/Linux

**Comment by bagder** [comment]
I believe the size check macro has been unchanged since 9e11c2791fb960758ad46b53c80fa37029c5501b (7.85.0) so it is unexpected to suddenly cause problems now.

**Comment by vortexilation** [comment]
I think the key in here is using gcc 14.1.0 & musl, while before is using gcc 13 and below on most distro or even OpenWrt itself.

gcc 14.1.0 hasn't becoming the default in OpenWrt, still defaulting with gcc 13.

My previous compilation targeting OpenWrt x86_64 glibc & gcc 14.1.0 hasn't encountered this error. Musl is the default libc for OpenWrt.

**Comment by bagder** [comment]
It looks like this happens because the `size_t` check that runs before this check could not find it? That's why there's a `#define size_t...` in this test code, which then apparently causes an error when including `<sys/types.h>`.

**Comment by bagder** [comment]
The check for `size_t` in config.log shows a long range of compiler errors.

**Comment by vortexilation** [comment]
> The check for `size_t` in config.log shows a long range of compiler errors. (starting at line 10254)

That's looks like 'fortify', a way to hardening code & binary in OpenWrt. I probably report this to OpenWrt then.

Thanks for this.

**Comment by vortexilation** [comment]
After reconsidering, I wanted to report that, perhaps curl able to work better regarding this cross compiling case with different toolchain than host/build system, the issues happened because and after libngtcp2 check adding "-I/usr/include" : 

after diving through the config.log , found out that -I/usr/include is being added after libngtcp2 check being run : 
```
configure:31302: checking for libngtcp2 options with pkg-config
configure:31316: result: found
configure:31330: -l is -lngtcp2
configure:31339: -I is -I/usr/include
configure:31349: -L is -L/usr/lib
configure:31359: checking for ngtcp2_conn_client_new_versioned in -lngtcp2
configure:31382: ccache x86_64-openwrt-linux-musl-gcc -o conftest -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fno-caller-saves -fno-plt -fhonour-copts -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -fmacro-prefix-map=/home/user/works/openwrt/build_dir/target-x86_64_musl/curl-8.8.0=curl-8.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -DHAVE_ULONG -Werror-implicit-function-declaration -Wno-system-headers -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/usr/include -L/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/lib -L/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/lib -fuse-ld=bfd -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/lib -Wl,-rpath-link=/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/lib -Wl,-rpath-link=/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/lib -znow -zrelro -Wl,--gc-sections  -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/usr/lib conftest.c -lngtcp2  -lngtcp2 -lnghttp2 -lidn2 -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lldap -llber -lzstd -lzstd -lz  >&5
configure:31382: $? = 0
configure:31392: result: yes
configure:31399: checking for ngtcp2/ngtcp2.h
configure:31399: ccache x86_64-openwrt-linux-musl-gcc -c -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fno-caller-saves -fno-plt -fhonour-copts -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -fmacro-prefix-map=/home/user/works/openwrt/build_dir/target-x86_64_musl/curl-8.8.0=curl-8.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -DHAVE_ULONG -Werror-implicit-function-declaration -Wno-system-headers -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/usr/include conftest.c >&5
In file included from ../../../staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify/stdio.h:22,
                 from conftest.c:69:
/usr/include/stdio.h:52:9: error: unknown type name '__gnuc_va_list'
   52 | typedef __gnuc_va_list va_list;
      |         ^~~~~~~~~~~~~~
/usr/include/stdio.h:52:24: error: conflicting types for 'va_list'; have 'int'
   52 | typedef __gnuc_va_list va_list;
      |                        ^~~~~~~
```
So instead using the intended cross compilation toolchain that are already defined, the header searching into "/usr/include" after the libngtcp2 check being done.
 
The temporary workaround for libngtcp2 on OpenWrt is this : 
```
$(SED) 's| -I$$$${includedir}||' $(1)/usr/lib/pkgconfig/libngtcp2.pc
```

Is there anything curl could do to ignore this include dir addition in cross compilation case?.

**Comment by bagder** [comment]
> Is there anything curl could do to ignore this include dir addition in cross compilation case?.

Yes, fix the buggy pkg-config from libngtcp2.

**Comment by bagder** [comment]
This is a bug in the pkg-config file brought by a 3rd party library, so the fix should be done there.

**Comment by Albresky** [comment]
> After reconsidering, I wanted to report that, perhaps curl able to work better regarding this cross compiling case with different toolchain than host/build system, the issues happened because and after libngtcp2 check adding "-I/usr/include" :
> 
> after diving through the config.log , found out that -I/usr/include is being added after libngtcp2 check being run :
> 
> ```
> configure:31302: checking for libngtcp2 options with pkg-config
> configure:31316: result: found
> configure:31330: -l is -lngtcp2
> configure:31339: -I is -I/usr/include
> configure:31349: -L is -L/usr/lib
> configure:31359: checking for ngtcp2_conn_client_new_versioned in -lngtcp2
> configure:31382: ccache x86_64-openwrt-linux-musl-gcc -o conftest -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fno-caller-saves -fno-plt -fhonour-copts -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -fmacro-prefix-map=/home/user/works/openwrt/build_dir/target-x86_64_musl/curl-8.8.0=curl-8.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -DHAVE_ULONG -Werror-implicit-function-declaration -Wno-system-headers -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/usr/include -L/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/lib -L/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/lib -fuse-ld=bfd -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/lib -Wl,-rpath-link=/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/lib -Wl,-rpath-link=/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/lib -znow -zrelro -Wl,--gc-sections  -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/usr/lib conftest.c -lngtcp2  -lngtcp2 -lnghttp2 -lidn2 -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lldap -llber -lzstd -lzstd -lz  >&5
> configure:31382: $? = 0
> configure:31392: result: yes
> configure:31399: checking for ngtcp2/ngtcp2.h
> configure:31399: ccache x86_64-openwrt-linux-musl-gcc -c -march=tigerlake -mtune=tigerlake -O3 -funsafe-math-optimizations -ffp-contract=fast -ftree-vectorize -fno-caller-saves -fno-plt -fhonour-copts -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -fmacro-prefix-map=/home/user/works/openwrt/build_dir/target-x86_64_musl/curl-8.8.0=curl-8.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -DHAVE_ULONG -Werror-implicit-function-declaration -Wno-system-headers -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/usr/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include -I/home/user/works/openwrt/staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libiconv-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/lib/libintl-full/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/user/works/openwrt/staging_dir/target-x86_64_musl/usr/include -I/usr/include conftest.c >&5
> In file included from ../../../staging_dir/toolchain-x86_64_gcc-14.1.0_musl/include/fortify/stdio.h:22,
>                  from conftest.c:69:
> /usr/include/stdio.h:52:9: error: unknown type name '__gnuc_va_list'
>    52 | typedef __gnuc_va_list va_list;
>       |         ^~~~~~~~~~~~~~
> /usr/include/stdio.h:52:24: error: conflicting types for 'va_list'; have 'int'
>    52 | typedef __gnuc_va_list va_list;
>       |                        ^~~~~~~
> ```
> 
> So instead using the intended cross compilation toolchain that are already defined, the header searching into "/usr/include" after the libngtcp2 check being done.
> 
> The temporary workaround for libngtcp2 on OpenWrt is this :
> 
> ```
> $(SED) 's| -I$$$${includedir}||' $(1)/usr/lib/pkgconfig/libngtcp2.pc
> ```
> 
> After this "/usr/include" addition into include dir list, if not removed as above workaround, creating error as first report.
> 
> Is there anything curl could do to ignore this include dir addition in cross compilation case?.

---

HI~ I encounted the same problem like you did while compiling Openwrt. I wonder how did you solved this problem?

**Comment by bagder** [comment]
Any pkg-config file that adds `/usr/include` as an include and/or `/usr/lib` as a lib dir is a bad pkgconfig file and should be fixed.

**Comment by Albresky** [comment]
> Any pkg-config file that adds `/usr/include` as an include and/or `/usr/lib` as a lib dir is a bad pkgconfig file and should be fixed.

---
Yes, you are right.

**Comment by Albresky** [comment]
> Any pkg-config file that adds `/usr/include` as an include and/or `/usr/lib` as a lib dir is a bad pkgconfig file and should be fixed.

---
Yes, you are right.

**Comment by Albresky** [comment]
> Is there anything curl could do to ignore this include dir addition in cross compilation case?.
---
I've solved this problem through converting the content of `ngtcp/Makefile` from CMake into Automake.
