### ISSUE TITLE
manpage paragraph incorrect indentation

### ISSUE THREAD

**Issue by jay** [curl/curl#13803]
The manpages display correctly in [curldown](https://github.com/curl/curl/blob/curl-8_8_0/docs/CURLDOWN.md) format but paragraphs may have incorrect indentation when converted to [nroff format](https://manpages.ubuntu.com/manpages/jammy/en/man7/groff_man.7.html#description) (via [cd2nroff](https://github.com/curl/curl/blob/curl-8_8_0/scripts/cd2nroff)) and then further to html (via [roffit](https://github.com/bagder/roffit)). The incorrect indentation is visible in a few places in the libcurl option website documentation.

The problem seems to be `## header` in curldown format starts indented paragraph format (`.IP`) for nroff but there's no way to stop the indentation for future paragraphs in the same section. [CURLOPT_SSLVERSION](https://curl.se/libcurl/c/CURLOPT_SSLVERSION.html) for example:

https://github.com/curl/curl/blob/fd567d4f06857f4fc8e2f64ea727b1318f76ad33/docs/libcurl/opts/CURLOPT_SSLVERSION.md?plain=1#L66-L82

In this example `## CURL_SSLVERSION_TLSv1_3` will be converted by [cd2nroff](https://github.com/curl/curl/blob/curl-8_8_0/scripts/cd2nroff) as `.IP CURL_SSLVERSION_TLSv1_3` and then subsequent paragraphs are all indented so says nroff format. However that is not desired because the second paragraph that starts "The maximum TLS version..." is not supposed to be indented. In the pictures below I used a red arrow to indicate where the paragraph should be.

`scripts/cd2nroff < docs/libcurl/opts/CURLOPT_SSLVERSION.md | nroff -Tascii -man | grep ""`

![nroff2](https://github.com/curl/curl/assets/965580/b066c710-da0e-47f5-9088-2f2190351ace)

[website version](https://curl.se/libcurl/c/CURLOPT_SSLVERSION.html#CURLSSLVERSIONTLSv13) after roffit conversion of nroff generated by cd2nroff:

![website2](https://github.com/curl/curl/assets/965580/6189ac48-668f-4dd9-8a2c-4b2928f107a5)

Older versions of curl used the nroff manpage format and so they had .RS/.RE for relative start/end of indentation, and roffit knew to end the indentation. For example this from 8.5.0:

https://github.com/curl/curl/blob/7161cb17c01dcff1dc5bf89a18437d9d729f1ecd/docs/libcurl/opts/CURLOPT_SSLVERSION.3#L57-L70

---

I tried for some time to fix this but nothing worked well enough that I want to build on it. The simplest fix I tried was resetting subsequent paragraph style via `.PP` rather than processing .RS .RE. Though that works for nroff to reset the indentation it does not work for roffit. Also- I'm not sure if this does what I intend in nroff anyway albeit it seems to work visually, at the cost of ending all indented paragraphs after a single paragraph.

~~~diff
--- a/scripts/cd2nroff
+++ b/scripts/cd2nroff
@@ -459,7 +459,7 @@ sub single {
         else {
             # don't output newlines if this is the first content after a
             # header
-            push @desc, "\n" if($blankline && !$header);
+            push @desc, ".PP\n" if($blankline && !$header);
             $blankline = 0;
             $header = 0;
 ~~~

**Comment by bagder** [comment]
For the cmdline docs (parsed by `managen`) we use a "blank" `##` header to signal the end of the list of `.IP`, and I think that might work here was well without it feeling very invasive. It requires a minor edit of the source file, but gives us more control and the output seems to be fine. Let me do a PR to show you what I mean.

**Comment by jay** [comment]
That's a good idea but it runs into the same issue I had with .PP when generating the html via roffit. If I decrease the indent level on .pp that seems to work. Or maybe reset the indent level to 0? 
~~~diff
diff --git a/roffit b/roffit
index 56c1fda..c01cfef 100755
--- a/roffit
+++ b/roffit
@@ -499,12 +499,13 @@ sub parsefile {
             elsif($keyword =~ /^pp$/i) {
                 # PP ends a TP section, but some TP sections don't use it
                 # Often used to separate paragraphs
                 $within_tp=0;
                 showp(@p);
                 @p="";
+                $indentlevel-- if ($indentlevel);
             }
             elsif($keyword =~ /^fi$/i) {
                 # .fi = fill-in, extra space will be ignored and text that is
                 # entered like this, the fill-in command will continue until
                 # you enter a .nf command and vice-versa

~~~

**Comment by bagder** [comment]
That seems to be a roffit issue as the man page looks fine with this fix.

**Comment by jay** [comment]
> That seems to be a roffit issue as the man page looks fine with this fix.

Thanks. Yes I agree, see proposal at bagder/roffit#48
