### ISSUE TITLE
IPV6 curl sftp known_host key validation failure

### ISSUE THREAD

**Issue by Krisscut** [curl/curl#13811]
### I did this

In our software, at some point we try to perform a file upload towards an ipv6 address. (**fd5f:4268:2387:97c1:0000:0000:0000:0002**)
Before that, populate the know_host file with the ip and its associated key, see in the logs below.

But when we perform the curl command 
**curl -v --trace-time  --user 'sftpTmp05231490155798:mysftppasswd'  --upload-file /trace2.log sftp://[fd5f:4268:2387:97c1:0000:0000:0000:0002]:/~/trace2.log** , it fails to perform the host key check because it uses the "compacted" ipv6 version and does not detect that it is actually the same ip: **fd5f:4268:2387:97c1::2**

I'm not sure if this is a bug, it could be expected behavior but I wasn't able to find details about it.
Or maybe it is an issue with the underlying SSH implementation, but I wanted to first check with curl team

> 2024-05-23 10:41:54/INF:UE_APP-OAM/orusw[RU01]: o-ran-file-management.c:556 - orusw_rpc_file_upload_cb() - <RPC> /o-ran-file-management:file-upload upload O-RAN/log/troubleshooting1-2024-05-23_10-40-54.log to sftp://sftpTmp05231490155798@[fd5f:4268:2387:97c1:0000:0000:0000:0002]/troubleshooting1-2024-05-23_10-40-54.log
>  
> 2024-05-23 10:41:54,897 DEBG 'orusw' stdout output:
> Showing known host content:
> 172.21.0.2 ssh-rsa <key>
> fd5f:4268:2387:97c1:0000:0000:0000:0002 ssh-rsa <key>
>  
> 2024-05-23 10:41:54,897 DEBG 'orusw' stdout output:
> 2024-05-23 10:41:54/INF:UE_APP-OAM/orusw[RU01]: o-ran-common.cpp:246 - shellExec() - execute shell: cat /root/.ssh/known_hosts succeeded
>
> 2024-05-23 10:41:54,929 DEBG 'orusw' stdout output:
> 2024-05-23 10:41:54/ERR:UE_APP-OAM/orusw[RU01]: o-ran-common.cpp:737 - shellExecRetVal() - shellExecRetVal failed to run command 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>  
>                                  Dload  Upload   Total   Spent    Left  Speed
>  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     010:41:54.164782 *   Trying [fd5f:4268:2387:97c1::2]:22...
>  
> 10:41:54.165280 * Connected to fd5f:4268:2387:97c1::2 (fd5f:4268:2387:97c1::2) port 22 (#0)
>  
> 10:41:54.165436 * Did not find host fd5f:4268:2387:97c1::2 in /root/.ssh/known_hosts
>  
> 10:41:54.187703 * SSH MD5 public key: NULL
>  
> 10:41:54.187745 * SSH SHA256 public key: NULL
>  
> 10:41:54.187789 * SSH host check: 2, key: <none>
>  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
>  
> 10:41:54.188084 * Closing connection 0
>  
> curl: (60) SSL peer certificate or SSH remote key was not OK
>  
> More details here:
> https://curl.se/docs/sslcerts.html
>  
>  
> curl failed to verify the legitimacy of the server and therefore could not
>  
> establish a secure connection to it. To learn more about this situation and
>  
> how to fix it, please visit the web page mentioned above.
>  
> how to fix it, please visit the web page mentioned above.

### I expected the following

Curl to successfully validate the host key since the ip provided in the curl command is present in the know_host file.
Here curl uses the short ipv6 and seems to perform a strict check in the file.

But maybe all the ips in the know_hosts file are mandatory to be in the short version in ipv6 ?

### curl/libcurl version

curl 8.0.1-DEV (x86_64-pc-linux-gnu) libcurl/8.0.1-DEV OpenSSL/3.0.13 zlib/1.2.11 zstd/1.4.9 libssh2/1.10.0-216-ga7a2fcd
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Linux fct-0a 5.15.148-0855470b96-nokia_sm_x86 #1 SMP PREEMPT Tue Apr 30 12:04:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

(Running in a lxc)

**Comment by bagder** [comment]
When curl parses a URL with an IPv6 numeral address, it *canonicalizes* it and converts it into the shortest possible version. Since a single IPv6 address can be written in a nearly infinite number of ways, this is a way to increase the chances that an IPv6 address ends up the same way independently of how it is provided.

You could argue that the known_hosts file format is notoriously bad for handling IPv6 addresses because of their "flexible" nature.

**Comment by Krisscut** [comment]
Yes I think it's fair to proceed this way, but maybe curl should also try to apply the same canonicalization on the ip listed in the _known_hosts_ before comparing them to make sure they are in the same format ?

I don't know if there is a specification/documentation on how the ip should be formatted in the _know_hosts_ file, maybe they should always be put in their short form in the first place. (Meaning it would be the responsibility of our app to canonicalize the ip)

**Comment by Krisscut** [comment]
Yes it's what I was checking in the code, indeed it seems I created the issue on the wrong component, sorry.

In our case with libssh2 it would happen here I guess:
https://github.com/curl/curl/blob/def7d05382743ea7aa1d356d1e41dcb22ecdd4d7/lib/vssh/libssh2.c#L483
Then here:
https://github.com/curl/curl/blob/def7d05382743ea7aa1d356d1e41dcb22ecdd4d7/lib/vssh/libssh2.c#L538

And the location where maybe some canonicalization could be added is here in libssh2:
https://github.com/libssh2/libssh2/blob/master/src/knownhost.c#L409

Do you think I should raise a new issue on libssh2 to go at the bottom of this ? 
On my side I worked around for now by formatting the ipv6 in its shortest form in the know_hosts but I think semantically it should have worked as well without changes.

**Comment by bagder** [comment]
> Do you think I should raise a new issue on libssh2 to go at the bottom of this ?

Yes, I think that is the right thing to do.

**Comment by bagder** [comment]
I think we do the right thing in curl. We should look into canonicalizing the IPv6 addresses inside libssh2.
