### ISSUE TITLE
No failure when the header file can't be written

### ISSUE THREAD

**Issue by bofh69** [curl/curl#13836]
### I did this

curl -D /dev/full  https://github.com/ > /dev/null
and got 0 as exit code.

### I expected the following

I expected to get an exit code 23 from curl when the headers couldn't be written because of ENOSPC.

### curl/libcurl version

curl 7.81.0, curl from master (acb9effcdd647b6daf753526ac18c84cb903ee72).

### operating system

Linux LUM-PF3VPCE9 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
It does not return an error because fwrite() returns success every time.

**Comment by bofh69** [comment]
@bagder that is an allowed way for fwrite to work. If buffering is in use (and large enough), the write to the buffer works fine and it returns the right amount of data written to the buffer.

One has to check the return value of fflush or fclose to see that everything was written.

**Comment by bagder** [comment]
ah, of course!
