### ISSUE TITLE
no Negotiate NTLM fallback

### ISSUE THREAD

**Issue by talksinmath** [curl/curl#1384]
When using curl with the `negotiate`option the expected behavior is that the client responds to a challenge. In the `negotiate` case the server may respond with a kerberos token or a NTLM token, depending on which can be obtained from the OS. 

It seems that curl does not respond to the provided NTLM continue token in the negotiate challenge. In the log file we see that server sends a challenge containing a NTLM token with a response code of 401. The expected behavior is that curl takes this continue token and answers with an appropriate second token.

Logout:

```
curl.exe -v --negotiate -u : http://DESKTOP-RQN4RNE.fritz.box:8080/info

*   Trying 192.168.100.183...
* TCP_NODELAY set
* Connected to DESKTOP-RQN4RNE.fritz.box (192.168.100.183) port 8080 (#0)
> GET /info HTTP/1.1
> Host: DESKTOP-RQN4RNE.fritz.box:8080
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 401
< Connection: keep-alive
< WWW-Authenticate: Negotiate
< Content-Length: 0
< Date: Tue, 04 Apr 2017 07:20:28 GMT
<
* Connection #0 to host DESKTOP-RQN4RNE.fritz.box left intact
* Issue another request to this URL: 'http://DESKTOP-RQN4RNE.fritz.box:8080/info'
* Found bundle for host DESKTOP-RQN4RNE.fritz.box: 0x29a89df3cf0 [can pipeline]
* Re-using existing connection! (#0) with host DESKTOP-RQN4RNE.fritz.box
* Connected to DESKTOP-RQN4RNE.fritz.box (192.168.100.183) port 8080 (#0)
* Server auth using Negotiate with user ''
> GET /info HTTP/1.1
> Host: DESKTOP-RQN4RNE.fritz.box:8080
> Authorization: Negotiate TlRMTVNTUAABAAAAt4II4gAAAAAAAAAAAAAAAAAAAAAKADk4AAAADw==
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 401
< WWW-Authenticate: Negotiate TlRMTVNTUAACAAAAHgAeADgAAAA1gorikipK0Fo9TY0AAAAAAAAAAJgAmABWAAAACgA5OAAAAA9EAEUAUwBLAFQATwBQAC0AUgBRAE4ANABSAE4ARQACAB4ARABFAFMASwBUAE8AUAAtAFIAUQBOADQAUgBOAEUAAQAeAEQARQBTAEsAVABPAFAALQBSAFEATgA0AFIATgBFAAQAHgBEAEUAUwBLAFQATwBQAC0AUgBRAE4ANABSAE4ARQADAB4ARABFAFMASwBUAE8AUAAtAFIAUQBOADQAUgBOAEUABwAIAOxrdu8TrdIBAAAAAA==
< Connection: keep-alive
< Transfer-Encoding: chunked
< Date: Tue, 04 Apr 2017 07:20:28 GMT
<
* Connection #0 to host DESKTOP-RQN4RNE.fritz.box left intact
```

### curl/libcurl version

curl 7.53.1 (x86_64-pc-win32) libcurl/7.53.1 WinSSL zlib/1.2.8 WinIDN
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz

### operating system

Windows 10

**Comment by frenche** [comment]
Can you post the full command and output (using -v).
Usually when curl gets the www-authenticate with the Negotiate response (containing NTLM challenge inside the SPNEGO token), it will pass it to InitializeSecurityContext (SSPI), and if it fails to handle it curl should return some error.

**Comment by talksinmath** [comment]
The command is `curl.exe --negotiate -u : http://DESKTOP-RQN4RNE.fritz.box:8080/info`
The logging output is in the first message (I added the command there, too).

Thanks!

**Comment by frenche** [comment]
So I compiled git-master using  mingw32 (turns out it's rather simple), but it doesn't reproduce for me...
Maybe it's the 'Transfer-Encoding: chunked' that makes the difference, or the high-port? strange.
Was it working for you with older versions of curl?

**Comment by talksinmath** [comment]
Tried it with 7.46.0
Same behaviour: The server sends a continue token, curl does not take this token into account and ends the communication.

**Comment by frenche** [comment]
Sorry, can't reproduce it.

**Comment by talksinmath** [comment]
Seems like it is not reproducable on every machine. One idea is that the provided continue token from the server might be corrupt and is silently dropped by curl. In this case I would expect an error message and an appropriate exit code. Instead curl just silently exits.

Thanks for your effort!

**Comment by frenche** [comment]
Ah ok, it does reproduce if I corrupt the token, but then the authentication fails and you get 401, so I'd say rather expected.
In gssapi we print an error in case of failure, perhaps we should print something in SSPI too, like:
```diff
diff --git a/lib/vauth/spnego_sspi.c b/lib/vauth/spnego_sspi.c
index 5fa95e2..9555dec 100644
--- a/lib/vauth/spnego_sspi.c
+++ b/lib/vauth/spnego_sspi.c
@@ -224,6 +224,7 @@ CURLcode Curl_auth_decode_spnego_message(struct Curl_easy *data,
   free(chlg);

   if(GSS_ERROR(nego->status)) {
+    infof(data, "InitializeSecurityContext() failed\n");
     return CURLE_OUT_OF_MEMORY;
   }

**Comment by jay** [comment]
What does it look like now

**Comment by frenche** [comment]
...
< HTTP/1.1 401 Unauthorized
< Date: Thu, 06 Apr 2017 18:34:15 GMT
< Server: Apache/2.4.25 (Fedora) OpenSSL/1.0.2j-fips PHP/5.6.29 mod_auth_gssapi/1.5.1 mod_auth_radius/1.6.1-git-623fd4b
* InitializeSecurityContext() failed
< WWW-Authenticate: Negotiate TlRMTVxTxAxCxAxAxAxMxDxAxAx1xoxixTxXxqxyxSxAxAxAxAxAxExAxgxExAxAxgxAxAxAxAxGxExAxAxPxFxAxQxBxAxAxgxFxExAxwxSxExAxgxWxFxAxwxSxExAxwxUxExAxAxJxExAxgxDxAxAxgxlxGxAxwxyxGxAxwxIxFxExmxEx9xBAAAAAA==
< Content-Length: 4
< Content-Type: text/html; charset=iso-8859-1
<
* Connection #0 to host 192.168.43.250 left intact

**Comment by frenche** [comment]
```raw
< HTTP/1.1 401 Unauthorized
< Date: Thu, 06 Apr 2017 18:34:15 GMT
< Server: Apache/2.4.25 (Fedora) OpenSSL/1.0.2j-fips PHP/5.6.29 mod_auth_gssapi/1.5.1 mod_auth_radius/1.6.1-git-623fd4b
* InitializeSecurityContext() failed
< WWW-Authenticate: Negotiate TlRMTVxTxAxCxAxAxAxMxDxAxAx1xoxixTxXxqxyxSxAxAxAxAxAxExAxgxExAxAxgxAxAxAxAxGxExAxAxPxFxAxQxBxAxAxgxFxExAxwxSxExAxgxWxFxAxwxSxExAxwxUxExAxAxJxExAxgxDxAxAxgxlxGxAxwxyxGxAxwxIxFxExmxEx9xBAAAAAA==
< Content-Length: 4
< Content-Type: text/html; charset=iso-8859-1
<
* Connection #0 to host 192.168.43.250 left intact

**Comment by jay** [comment]
Is this recoverable and would it be better to show the users the actual error if we're going to show that, example:
failf(data, "InitializeSecurityContext failed: %s", Curl_sspi_strerror(conn, sspi_status));

**Comment by frenche** [comment]
Yes, much better:
```raw
* InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid
```
```diff
diff --git a/lib/vauth/spnego_sspi.c b/lib/vauth/spnego_sspi.c
index 5fa95e2..b05c92d 100644
--- a/lib/vauth/spnego_sspi.c
+++ b/lib/vauth/spnego_sspi.c
@@ -34,6 +34,7 @@
 #include "warnless.h"
 #include "curl_multibyte.h"
 #include "sendf.h"
+#include "strerror.h"

 /* The last #include files should be: */
 #include "curl_memory.h"
@@ -224,6 +225,8 @@ CURLcode Curl_auth_decode_spnego_message(struct Curl_easy *data,
   free(chlg);

   if(GSS_ERROR(nego->status)) {
+    failf(data, "InitializeSecurityContext failed: %s",
+      Curl_sspi_strerror(data->easy_conn, nego->status));
     return CURLE_OUT_OF_MEMORY;
   }

**Comment by jay** [comment]
lgtm with one nitpick column alignment the second line should start after the (
~~~c
failf(data, "InitializeSecurityContext failed: %s",
      Curl_sspi_strerror(data->easy_conn, nego->status));
~~~

**Comment by talksinmath** [comment]
Thanks!
