### ISSUE TITLE
Crash when using CURL_LOCK_DATA_CONNECT in Curl_conn_close  at cfilters.c:165

### ISSUE THREAD

**Issue by valbok** [curl/curl#13840]
### I did this

Trying to reuse connections for easy handlers but on multiple concurrent threads.

Create share handle once:
```cpp
shareHandle = curl_share_init();
curl_share_setopt(shareHandle, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT);
curl_share_setopt(shareHandle, CURLSHOPT_USERDATA, this);
curl_share_setopt(shareHandle, CURLSHOPT_LOCKFUNC, lockcb);
curl_share_setopt(shareHandle, CURLSHOPT_UNLOCKFUNC, unlockcb);
```

On concurrent threads:
```cpp
curl = curl_easy_init();
curl_easy_setopt(curl, CURLOPT_SHARE, shareHandle);
curl_easy_perform(curl);
curl_easy_cleanup(curl);
```

But this leads to crash:
```bash
#0  0x00007fffdd10fea3 in Curl_conn_close (data=0x555556720b20, index=1) at /opt/curl/lib/cfilters.c:165
#1  0x00007fffdd195e48 in conn_shutdown (data=0x555556720b20) at /opt/curl/lib/url.c:566
#2  0x00007fffdd196250 in Curl_disconnect (data=0x555556720b20, conn=0x7ffca4040b30, dead_connection=false) at /opt/curl/lib/url.c:675
#3  0x00007fffdd11263e in Curl_conncache_return_conn (data=0x7ffc7c004140, conn=0x7ffc7c003380) at /opt/curl/lib/conncache.c:397
#4  0x00007fffdd15e768 in multi_done (data=0x7ffc7c004140, status=CURLE_OK, premature=false) at /opt/curl/lib/multi.c:813
#5  0x00007fffdd161d06 in multi_runsingle (multi=0x7ffc7c002d80, nowp=0x7ffca0ff6230, data=0x7ffc7c004140) at /opt/curl/lib/multi.c:2616
#6  0x00007fffdd1621fa in curl_multi_perform (multi=0x7ffc7c002d80, running_handles=0x7ffca0ff6320) at /opt/curl/lib/multi.c:2780
#7  0x00007fffdd1258d7 in easy_transfer (multi=0x7ffc7c002d80) at /opt/curl/lib/easy.c:675
#8  0x00007fffdd125b60 in easy_perform (data=0x7ffc7c004140, events=false) at /opt/curl/lib/easy.c:769
#9  0x00007fffdd125bd2 in curl_easy_perform (data=0x7ffc7c004140) at /opt/curl/lib/easy.c:788
(gdb) p data->conn
$1 = (struct connectdata *) 0x0
```

Does it mean `data->conn` is cleared already?

### I expected the following

The documentation for `CURL_LOCK_DATA_CONNECT` says:
> It is not supported to share connections between multiple concurrent threads.

I understood it like I should not expect the connection to be shared on different threads _at the same time_. 
But it should be possible to reuse the connection after easy handle is cleaned up (curl_easy_cleanup). Since the connection is not closed immediately and expected it to be returned to internal connection pool?

Does it mean that it is not allowed to use the share handle with `CURL_LOCK_DATA_CONNECT`
between _unique_ easy handlers for concurrent threads at all?

### curl/libcurl version

8.8.1-DEV

### operating system

Ubuntu 22.04

**Comment by bagder** [comment]
I believe you missed this important piece of information in the CURLSHOPT_SHARE manpage:

> It is not supported to share connections between multiple concurrent threads.

**Comment by bagder** [comment]
It has never worked. If you did not get complaints, you circumstances were simply fortunate .
