### ISSUE TITLE
failed to upload file with size 24GB via curl POST - out of memory

### ISSUE THREAD

**Issue by Wizzy-wooz** [curl/curl#1385]
### I did this
Used incorrectly --data-binary option 
and got curl: option --data-binary: out of memory

### I expected the following
file uploaded 

### curl/libcurl version
7.40 version

[curl -V output]

### operating system
Ubuntu Server 16

**Comment by bagder** [comment]
I don't understand your included verbose output. It shows two separate and different attempts and only the second has the "out of memory" error you filed this issue about. You seem to not have figured out how your upload should be done, and frankly, "file uploads" over HTTP are almost always done with -F posts.

The reason for the out of memory is that `--data` and its friends all read the data into memory before sending it off to the server. You can work around that easily by doing `-T <filename> -X POST`, but I still believe you went wrong already in your initial -F test.

**Comment by Wizzy-wooz** [comment]
Thank you for the prompt answer.

My situation is: I need to make 2 POST request:

1) curl -v --insecure "$PORTAL_URL/shipments/$SHIPMENT_ID/uploads" -H 'Content-Type: multipart/form-data' -H 'Accept: application/json, text/plain, */*' -H "X-Auth-Token: $AUTH_TOKEN" -F filename="$FILE_NAME" -F filesize="$FILE_SIZE"  - via form I am sending filename and file size which I'd like to upload - that's how the portal I am uploading to is working

2)curl -v --insecure -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: */*' -H "X-Auth-Token: $AUTH_TOKEN" -T "@$FILE_NAME" -X POST "$PORTAL_URL/chunks?resumableChunkNumber=1&resumableChunkSize=1048576&resumableCurrentChunkSize=$FILE_SIZE&resumableTotalSize=$FILE_SIZE&resumableIdentifier=$FILE_SIZE-$FILE_NAME_WITHOUT_EXTENSION&resumableFilename=$FILE_NAME&resumableRelativePath=$FILE_NAME&uploadId=$UPLOAD_ID" - by this POST I am actually sending a large zipped file (nearly 24GB)

I tried to send via -T but got 
curl: Can't open '@02600002_EU.zip'!

Can you please help? Thanks.

**Comment by bagder** [comment]
`-T` takes a file name, presumably your file name does not actually have a `@` as first letter.

**Comment by jzakrzewski** [comment]
That's because you shouldn't use "@" with -T

**Comment by Wizzy-wooz** [comment]
Thanks guys 👍 It was the issue. However, if I use -T option instead of --data-binary I see file upload but at the end it terminates with HTTP/1.1 400 Bad Request - how can I properly use -T with chunks?

**Comment by Wizzy-wooz** [comment]
I used -H "Transfer-Encoding: chunked"  - no luck.

**Comment by bagder** [comment]
This is no longer an issue with curl though, it is now an issue with how you use curl against your particular server/service.  `-H "Transfer-Encoding: chunked"` works fine to enable chunked transfer when `-T` is used.

**Comment by Wizzy-wooz** [comment]
Hi, guys,

I am back again with the question. Please forgive me for troubling. It's not a problem with curl, it;s rather urgent question. Is there any possibility that I can post a whole zip file by chunks? I can't split this zip to partitions. It must go to the client as single zip. But as I need to send it as stream by chunks no more than 1M. How can I do it?

I wrote a command:
curl -v --insecure -H 'Accept: */*' -H 'Content-Type: application/zip' -H "X-Auth-Token: $AUTH_TOKEN" -T "$FILE_NAME" -X POST "$PORTAL_URL/chunks?resumableChunkNumber=1&resumableChunkSize=1048576&resumableCurrentChunkSize=1048576&resumableTotalSize=1048576&resumableIdentifier=$FILE_SIZE-$FILE_NAME_WITHOUT_EXTENSION&resumableFilename=$FILE_NAME&resumableRelativePath=$FILE_NAME&uploadId=$UPLOAD_ID"

But it does not work as it do not send it by chunks.

Thank you so much in advance.

**Comment by jay** [comment]
I think you are now asking questions that belong on [curl-users](https://curl.haxx.se/mail/) instead of this issue tracker. To your question though, @bagder already gave you the answer earlier in the thread:

> -H "Transfer-Encoding: chunked" works fine to enable chunked transfer when -T is used.

If you want to send a chunked upload use `--header "Transfer-Encoding: chunked"`. Also I notice your URL has a lot of fields with "resume" in the name, I should point out I don't believe curl has auto support for HTTP upload via resume. The reason for this I assume is curl doesn't know the size of the uploaded data accepted by the server before the interruption. If you can request the size from the server separately then you could pass it to `--continue-at`, but know the way you are doing it now curl is going to start from the beginning every time.

Maybe we should document that --data loads the file into memory?

**Comment by bagder** [comment]
> Maybe we should document that --data loads the file into memory?

I think we should. The hard part is probably the phrasing as the man page is for users and the "loading into memory first" is very specific and technical.

**Comment by jay** [comment]
Yeah it's hard to explain. Also the more I think about this it seems highly unlikely.

**Comment by bagder** [comment]
Closing this issue. This is not really a curl bug, just a limitation in how it works and curl can still send 24GB posts fine, just using other options.
