### ISSUE TITLE
MBEDTLS_SSL_SESSION_TICKETS_ENABLED

### ISSUE THREAD

**Issue by andreensteven** [curl/curl#13960]
### I did this

curl\lib\vtls\mbedtls.c
function: mbed_connect_step1

code: 
```
#if defined(MBEDTLS_SSL_SESSION_TICKETS)
  mbedtls_ssl_conf_session_tickets(&backend->config,
                                   MBEDTLS_SSL_SESSION_TICKETS_DISABLED);
#endif
```

### I expected the following
```
#if defined(MBEDTLS_SSL_SESSION_TICKETS)
  mbedtls_ssl_conf_session_tickets(&backend->config,
                                   MBEDTLS_SSL_SESSION_TICKETS_ENABLED);
#endif
```
mybe param2 is MBEDTLS_SSL_SESSION_TICKETS_ENABLED.

### curl/libcurl version

master

### operating system

windows 10

**Comment by bagder** [comment]
They are disabled because there is no code for managing tickets with mbedTLS. Are you saying it just magically works if we just enable them?

**Comment by andreensteven** [comment]
**mbedtls 3.6 is ok**
![image](https://github.com/curl/curl/assets/137030007/3461eeec-8fc3-4581-9289-5db42141b57a)
@bagder

**Comment by bagder** [comment]
That looks like a cryptic screenshot implying that there was a session ticket involved over TLS. But what's the point if there is no code for mbedTLS in curl that receives the ticket and can use it in subsequent handshakes?

**Comment by bagder** [comment]
No response.
