### ISSUE TITLE
Curl 8.6.0+ doesn't allow empty string in args

### ISSUE THREAD

**Issue by matthewhughes934** [curl/curl#13966]
### I did this

```
$ curl "" --silent www.example.com
```

And I saw an error:

```
curl: option : blank argument where content is expected
curl: try 'curl --help' for more information
```

### I expected the following

Curl to run as if I had passed it `curl --silent www.example.com` based on https://github.com/curl/curl/issues/13144 (I think it was also introduced with 07bcae89d5d0090f1d11866d5f9c98c3720a2838), though similar to there I'm not sure if this is a bug or intentional behaviour but thought I'd post all the same for visibility, given there is a behaviour change.

building at `07bcae89d5d0090f1d11866d5f9c98c3720a2838~` (i.e. f59223f500ebeee8ef6d882242fd4418f9e96c52) and I see the following behaviour:

```console
$ ./src/curl "" www.example.com >/dev/null
curl: (3) URL rejected: Malformed input to a URL function
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1256  100  1256    0     0   7399      0 --:--:-- --:--:-- --:--:--  7431
$ ./src/curl "" --silent www.example.com >/dev/null
```

I.e. the request to `www.example.com` is made in both cases and the `--silent` option is used in the second.

I noticed this behaviour as a result of https://github.com/karancode/kustomize-github-action/issues/46. The root cause of that is the `curl` invocation https://github.com/karancode/kustomize-github-action/blob/883a86ec3535e4e7d0fe6450a85f8325c97d2a7b/src/entrypoint.sh#L54 where `${with_token[@]}"` being empty it will result in a `""` in the args.

### curl/libcurl version

```
$ curl --version
curl 8.8.0 (x86_64-pc-linux-gnu) libcurl/8.8.0 OpenSSL/3.3.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.62.1 nghttp3/1.3.0
Release-Date: 2024-05-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

Tested with the same result at current `master` (04739054cdac5a0614fb94e3655e313c03399f35)

### operating system

Arch Linux  6.6.32-1-lts

**Comment by dfandrich** [comment]
GIGO? An empty argument is always an error by the caller, so curl is right to
warn the user about it. Second guessing the user about the meaning behind an
empty argument could hide a serious problem. If you don't want such errors,
don't provide invalid arguments to curl.

**Comment by matthewhughes934** [comment]
> Second guessing the user about the meaning behind an empty argument could hide a serious problem. If you don't want such errors, don't provide invalid arguments to curl.

I tend to agree. I have no objection to this issue being closed, mostly I just wanted to open it for visibility for anyone else that sees the same error

**Comment by bagder** [comment]
curl was never documented to support empty arguments or URLs. The fact that they did work was just a (un)lucky circumstance. I think it could have been 887b998e6e11076 that fixed that bug.
