### ISSUE TITLE
Cannot load certificate via ThumbPrint in Windows - (58) could not load PEM client certificate from LocalMachine

### ISSUE THREAD

**Issue by stephannn** [curl/curl#13962]
### I did this

I execute following command:
`curl --cert "LocalMachine//My//a49e0cb1c5ea10050a1c7771fde5475a1a933f74" {URI}`
where a49e0cb1c5ea10050a1c7771fde5475a1a933f74 is my local client certificate.
The output is:
`curl: (58) could not load PEM client certificate from LocalMachine//My//a49e0cb1c5ea10050a1c7771fde5475a1a933f74, LibreSSL error error:02FFF002:system library:func(4095):No such file or directory, (no key found, wrong pass phrase, or wrong file format?)`

Regarding documentation ThumbPrint can be used: https://curl.se/docs/manpage.html#-E

### I expected the following

That the certificate is found.

I thought is post maybe related: https://github.com/curl/curl/issues/3480 but is solved.

### curl/libcurl version

8.8.0_2

### operating system

Windows 10 - 64 Bit

**Comment by vszakats** [comment]
The manual says that the ThumbPrint feature is Schannel only.
The output however comes from a curl built with LibreSSL (possibly the official binary).

**Comment by stephannn** [comment]
Hi @vszakats,
I tried setting _set CURL_SSL_BACKEND=schannel_ in my windows cmd but the outcome is the same. I do not really understand what I am doing wrong.

**Comment by stephannn** [comment]
Ah, I understand. One curl version comes with windows. I downloaded curl for Windows that is different regarding schannel. Using the Windows version is fine.

**Comment by vszakats** [comment]
@stephannn Official curl builds no longer come with Schannel as a secondary backend because MultiSSL is incompatible with HTTP/3. That's why `CURL_SSL_BACKEND` was ineffective.
