### ISSUE TITLE
when use curl report as shell variable value direct, the value is unexpected. when filtered by pipe, it is write

### ISSUE THREAD

**Issue by tkgup** [curl/curl#13961]
### I did this

value=$(curl -k -s -X get  www.google.com  -D- -s -o/dev/null)
echo $value

the value is little and bad format value，such as:
![image](https://github.com/curl/curl/assets/61499462/31b6ba1f-0ba0-4145-8502-10ed09c21691)

when filtered by pipe, the result is right
value=$(curl -k -s -X get  www.google.com  -D- -s -o/dev/null | grep Content-Type)
echo $value
![image](https://github.com/curl/curl/assets/61499462/3c4893d6-c418-457c-912b-cfbd3619dd5d)

### I expected the following

like this:
HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 17 Jun 2024 07:20:58 GMT
Content-Type: text/html
Content-Length: 150
Connection: close

### curl/libcurl version

curl   7.71.1 and 7.79.1

### operating system

on window by git ( 7.71.1)
on linux 7.79.1

**Comment by bagder** [comment]
That's simply how your shell works, nothing curl can change.
