### ISSUE TITLE
autotools: pkgconf can't find zstd

### ISSUE THREAD

**Issue by L4cache** [curl/curl#14005]
### I did this

Use [media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite) to build mediainfo, and during configure, mediainfo can't find zstd required by libcurl required by libmediainfo.
There's libzstd.pc, but libcurl.pc file generated by autoconf uses "zstd" in Requires.private, pkgconf can't find it. CMake on the other hand uses "libzstd", so maybe it's a typo in configure.ac?

More detail: https://github.com/m-ab-s/media-autobuild_suite/issues/2723

https://github.com/curl/curl/commit/f057de5a1a950a90d1920021db152a4b695f1a8a#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810R1562

https://github.com/curl/curl/commit/f057de5a1a950a90d1920021db152a4b695f1a8a#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR606

### curl/libcurl version

curl 8.9.0-DEV

### operating system

MSYS2

**Comment by L4cache** [comment]
I think I should change the title because the problem is not exactly about the difference.

**Comment by vszakats** [comment]
Nice that you spotted that, cmake and autotools should definitely use the same name here.

I'll open a PR for this shortly.

**Comment by vszakats** [comment]
@L4cache Thanks for your report. Please open a new Issue if this persist after the merged fix.
