### ISSUE TITLE
CI: synopsis workflow no longer running

### ISSUE THREAD

**Issue by vszakats** [curl/curl#14032]
### I did this

Noticed that the SYNOPSIS workflow stopped running:
https://github.com/curl/curl/actions/workflows/synopsis.yml

It would trigger on `.3` file updates, but we replaced them
with `.md` files a while back.

`.github/scripts/verify-synopsis.pl` is unused too as a result.

### I expected the following

The workflow to run.

### curl/libcurl version

master

### operating system

N/A

**Comment by pheiduck** [comment]
Looks very simple will provide a patch for that issue. ;)

**Comment by vszakats** [comment]
Ref: #14038
