### ISSUE TITLE
HTTP/3 failure on mac due to active_connection_id_limit from ngtcp2

### ISSUE THREAD

**Issue by alexsn** [curl/curl#14043]
### I did this

Tried to use HTTP/3 to fetch a url:
```
> curl -vvv --http3 https://graph.oculus.com
* Host graph.oculus.com:443 was resolved.
* IPv6: (none)
* IPv4: 157.240.3.49
* WARNING: no socket in pollset, transfer may stall!
*   Trying 157.240.3.49:443...
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* Connected to graph.oculus.com (157.240.3.49) port 443
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://graph.oculus.com/
* [HTTP/3] [0] [:method: GET]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: graph.oculus.com]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.9.0-DEV]
* [HTTP/3] [0] [accept: */*]
> GET / HTTP/3
> Host: graph.oculus.com
> User-Agent: curl/8.9.0-DEV
> Accept: */*
>
* Request completely sent off
* Connection #0 to host graph.oculus.com left intact
curl: (56) Failure when receiving data from the peer
```

Note that I'm running the above command on mac, same thing works on linux:
```
curl -vvv --http3 https://graph.oculus.com                                                               ─╯
* Host graph.oculus.com:443 was resolved.
* IPv6: 2a03:2880:f262:c9:face:b00c:0:32c2
* IPv4: 157.240.24.54
*   Trying [2a03:2880:f262:c9:face:b00c:0:32c2]:443...
*  CAfile: /etc/pki/tls/certs/fb_certs.pem
*  CApath: none
* Connected to graph.oculus.com (2a03:2880:f262:c9:face:b00c:0:32c2) port 443
* using HTTP/3
* [HTTP/3] [0] OPENED stream for https://graph.oculus.com/
* [HTTP/3] [0] [:method: GET]
* [HTTP/3] [0] [:scheme: https]
* [HTTP/3] [0] [:authority: graph.oculus.com]
* [HTTP/3] [0] [:path: /]
* [HTTP/3] [0] [user-agent: curl/8.8.0-DEV]
* [HTTP/3] [0] [accept: */*]
> GET / HTTP/3
> Host: graph.oculus.com
> User-Agent: curl/8.8.0-DEV
> Accept: */*
> 
* Request completely sent off
< HTTP/3 400 
< vary: Origin
< vary: Accept-Encoding
...
```

After debugging the error is coming from ngtcp2 [here](https://github.com/ngtcp2/ngtcp2/blob/main/lib/ngtcp2_conn.c#L7780) where `active_connection_id_limit` defaults to `NGTCP2_DEFAULT_ACTIVE_CONNECTION_ID_LIMIT` which is 2. ngtcp2 allows us to set `->active_connection_id_limit` explicitly which resolves the issue for me with the following change in libcurl:
```
diff --git a/lib/vquic/curl_ngtcp2.c b/lib/vquic/curl_ngtcp2.c
index 26c50029f..09430b465 100644
--- a/lib/vquic/curl_ngtcp2.c
+++ b/lib/vquic/curl_ngtcp2.c
@@ -412,6 +412,7 @@ static void quic_settings(struct cf_ngtcp2_ctx *ctx,
   t->initial_max_streams_bidi = QUIC_MAX_STREAMS;
   t->initial_max_streams_uni = QUIC_MAX_STREAMS;
   t->max_idle_timeout = (ctx->max_idle_ms * NGTCP2_MILLISECONDS);
+  t->active_connection_id_limit = 3;
   if(ctx->qlogfd != -1) {
     s->qlog_write = qlog_callback;
   }
```

libcurl currently doesn't provide any way to override ngtcp2 params, @bagder would it be acceptable to have a -DCURL_NGTCP2_DEFAULT_ACTIVE_CONNECTION_ID_LIMIT so this can be configured during compilation or maybe have a fixed value higher then 2 (we use active_connection_id_limit = 7 in other http libraries)?

### Possible fix
Maybe something like this:
```
@@ -78,6 +78,7 @@
 #define QUIC_MAX_STREAMS (256*1024)
 #define QUIC_MAX_DATA (1*1024*1024)
 #define QUIC_HANDSHAKE_TIMEOUT (10*NGTCP2_SECONDS)
+#define QUIC_ACTIVE_CONNECTION_ID_LIMIT 7
 
 /* A stream window is the maximum amount we need to buffer for
  * each active transfer. We use HTTP/3 flow control and only ACK
@@ -412,6 +413,7 @@
   t->initial_max_streams_bidi = QUIC_MAX_STREAMS;
   t->initial_max_streams_uni = QUIC_MAX_STREAMS;
   t->max_idle_timeout = (ctx->max_idle_ms * NGTCP2_MILLISECONDS);
+  t->active_connection_id_limit = QUIC_ACTIVE_CONNECTION_ID_LIMIT;
   if(ctx->qlogfd != -1) {
     s->qlog_write = qlog_callback;
   }
```

### I expected the following

I expect the HTTP GET command to not error out with an internal curl error

### curl/libcurl version

curl 8.9.0-DEV (aarch64-apple-darwin23.5.0) libcurl/8.9.0-DEV wolfSSL/5.7.0 zlib/1.2.12 libidn2/2.3.7 nghttp2/1.61.0 ngtcp2/1.6.0 nghttp3/1.4.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz SSL threadsafe UnixSockets

### operating system

Darwin titan 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

**Comment by bagder** [comment]
> would it be acceptable to have a -DCURL_NGTCP2_DEFAULT_ACTIVE_CONNECTION_ID_LIMIT so this can be configured during compilation or maybe have a fixed value higher then 2 (we use active_connection_id_limit = 7 in other http libraries)?

Yes!

What exactly does this limit? The number of concurrently open QUIC connections allowed by ngtcp2? If so, then 2 indeed seems very low.

/cc @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
RFC 9000 defines active_connection_id_limit as follows:

> active_connection_id_limit (0x0e):
>
> This is an integer value specifying the maximum number of connection IDs from the peer that an endpoint is willing to store. This value includes the connection ID received during the handshake, that received in the preferred_address transport parameter, and those received in NEW_CONNECTION_ID frames. The value of the active_connection_id_limit parameter MUST be at least 2. An endpoint that receives a value less than 2 MUST close the connection with an error of type TRANSPORT_PARAMETER_ERROR. If this transport parameter is absent, a default of 2 is assumed. If an endpoint issues a zero-length connection ID, it will never send a NEW_CONNECTION_ID frame and therefore ignores the active_connection_id_limit value received from its peer.

Notice that the default value is 2.

> An endpoint MUST NOT provide more connection IDs than the peer's limit.

and

> A NEW_CONNECTION_ID frame might cause an endpoint to add some active connection IDs and retire others based on the value of the Retire Prior To field. After processing a NEW_CONNECTION_ID frame and adding and retiring active connection IDs, if the number of active connection IDs exceeds the value advertised in its active_connection_id_limit transport parameter, an endpoint MUST close the connection with an error of type CONNECTION_ID_LIMIT_ERROR.

So if Connection ID management in ngtcp2 is correct, the server sends more Connection IDs than curl allows, which is subject to connection error.

**Comment by bagder** [comment]
> Note that I'm running the above command on mac, same thing works on linux:

If this problem is due to this limit in ngtcp2, why does it not always fail? It seems to work all the time for me...

**Comment by bagder** [comment]
Apparently there is one specific IP that causes the problem while others work fine. The problem can be triggered with this:

    curl -v --http3 https://graph.oculus.com --resolve graph.oculus.com:443:157.240.3.49

**Comment by icing** [comment]
Ok, our tests show that it is independent of the OS curl runs on. Instead the difference is if you talk to 157.240.3.49 or 2a03:2880:f20a:c1:face:b00c:0:32c2.

We can raise the limit, but to what value? Are you running a different server version on the ipv4 one?

**Comment by tatsuhiro-t** [comment]
I also wondering why.  The failure case uses IPv4, on the other hand, the successful one uses IPv6.  That might make a difference if the server behaves differently.

**Comment by bagder** [comment]
> I also wondering why. The failure case uses IPv4, on the other hand, the successful one uses IPv6. That might make a difference if the server behaves differently.

I tried with `-4` to limit testing to IPv4, but that works most of the time as well. It really seems to be a few specific hosts that trigger this.

**Comment by icing** [comment]
quiche also fails on that host, it has the same default limit of 2 cids.

**Comment by tatsuhiro-t** [comment]
I do not think we should raise the limit.  The remote endpoint must honor the limit, otherwise dropping a connection is a right thing to do.

**Comment by tatsuhiro-t** [comment]
The server that has particular IP returns more NEW_CONNECTION_ID frames than curl permits:

```
I00000218 0xffae23bfbeed1ec2aeb83f832b208ff2fa frm rx 16220664 1RTT NEW_CONNECTION_ID(0x18) seq=1 cid=0xa92a002f011bd8cd retire_prior_to=0 stateless_reset_token=0x40e75ffcfc1f73ebb78ce54dd12792f9
I00000218 0xffae23bfbeed1ec2aeb83f832b208ff2fa frm rx 16220664 1RTT NEW_CONNECTION_ID(0x18) seq=2 cid=0xaf2a002f011db3cb retire_prior_to=0 stateless_reset_token=0xf515f8e4aa34190377dbd7f04a226354
ngtcp2_conn_read_pkt: ERR_CONNECTION_ID_LIMIT
```

While the successful case, it returns just one additional Connection ID.  I think the failing server is broken or misconfigured.

**Comment by alexsn** [comment]
Thanks for debugging this further @tatsuhiro-t / @icing / @bagder , I'll reach out the people maintaining the hosts in question.

**Comment by alexsn** [comment]
> The server that has particular IP returns more NEW_CONNECTION_ID frames than curl permits:
> 
> ```
> I00000218 0xffae23bfbeed1ec2aeb83f832b208ff2fa frm rx 16220664 1RTT NEW_CONNECTION_ID(0x18) seq=1 cid=0xa92a002f011bd8cd retire_prior_to=0 stateless_reset_token=0x40e75ffcfc1f73ebb78ce54dd12792f9
> I00000218 0xffae23bfbeed1ec2aeb83f832b208ff2fa frm rx 16220664 1RTT NEW_CONNECTION_ID(0x18) seq=2 cid=0xaf2a002f011db3cb retire_prior_to=0 stateless_reset_token=0xf515f8e4aa34190377dbd7f04a226354
> ngtcp2_conn_read_pkt: ERR_CONNECTION_ID_LIMIT
> ```
> 
> While the successful case, it returns just one additional Connection ID. I think the failing server is broken or misconfigured.

@tatsuhiro-t - how did you enable those logs?

**Comment by alexsn** [comment]
[ngtcp2 example client ](https://github.com/ngtcp2/ngtcp2/blob/main/examples/client.cc#L810) sets this value to 7 which is suppose to be best practice for clients. Any idea why they do that?

**Comment by tatsuhiro-t** [comment]
It is just an arbitrary value.  The important thing is server must not exceed the limit.

**Comment by alexsn** [comment]
Confirming this is a server side issue on our end. Thanks everyone for debugging this.
