### ISSUE TITLE
No way to safely initialize libcurl from a plug-in

### ISSUE THREAD

**Issue by DemiMarie** [curl/curl#1405]
### I did this

Looked up the documentation for libcurl and noticed the docs on `curl_global_init`.  I found this:

> This function is not thread safe. You must not call it when any other thread in the program (i.e. a thread sharing the same memory) is running. This doesn't just mean no other thread that is using libcurl. Because curl_global_init calls functions of other libraries that are similarly thread unsafe, it could conflict with any other thread that uses these other libraries.

### I expected the following

Some way to safely initialize libcurl from an already-multithreaded application (such as a JVM, which spawns multiple threads before running any user Java code).  The docs say

> The global constant situation merits special consideration when the code you are writing to use libcurl is not the main program, but rather a modular piece of a program, e.g. another library. As a module, your code doesn't know about other parts of the program -- it doesn't know whether they use libcurl or not. And its code doesn't necessarily run at the start and end of the whole program.
> 
> A module like this must have global constant functions of its own, just like curl_global_init and curl_global_cleanup. The module thus has control at the beginning and end of the program and has a place to call the libcurl functions. Note that if multiple modules in the program use libcurl, they all will separately call the libcurl functions, and that's OK because only the first curl_global_init and the last curl_global_cleanup in a program change anything. (libcurl uses a reference count in static memory).

but that requires that the API the module conforms to *provide* such functions.  There are many cases (JNI and .NET P/Invoke come to mind) where it does not – by the time the first piece of user code is run, multiple threads have already been launched.  So compliance with this requirement in a Java application is *impossible.*

Worse, those runtimes allow for native code to be loaded lazily, so there may be multiple threads using libraries such as OpenSSL by the time the module responsible for libcurl takes control.  An Eclipse plugin would be one example.  Another example is when using libcurl from Rust – again, there is no way for a library author to ensure the requirement is met and still conform to standard Rust safety rules (which require that *all* global functions be thread-safe).

The only solution I can think of is to use my own copy of libcurl, that is statically linked against its dependencies (except for libc on *nix).  This ensures that libcurl and its dependencies have their own private set of global variables, so calling the `curl_global_init` in this library cannot stomp on other code running in other libraries.

I don't care which SSL library I use.  GnuTLS is obviously ruled out.

### curl/libcurl version

curl 7.51.0 (x86_64-redhat-linux-gnu) libcurl/7.51.0 NSS/3.29.3 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.11) libssh2/1.8.0 nghttp2/1.13.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL 

### operating system
Linux, but this problem is OS-independent.

**Comment by bagder** [comment]
The threading limitations libcurl specifies are purely because of the third party libraries it might use. Nothing libcurl does by itself makes it thread unsafe in the initialization phase. So, we really cannot address this issue. You can, by only building libcurl against third party libraries that are totally thread-safe even in the init function cals.

**Comment by jay** [comment]
> Nothing libcurl does by itself makes it thread unsafe in the initialization phase

I'm not sure if I'm interpreting that wrong but libcurl global init uses static variables, so it is not thread safe.

**Comment by bagder** [comment]
Ah you're right. That was poorly worded by me. I should've said something in the style that libcurl itself doesn't really need this thread unsafe state but it is required to work like this due to third party libraries, and in order to support this libcurl _does_ use static variables that are in themselves not thread safe.

**Comment by DemiMarie** [comment]
@bagder What are some choices of 3rd-party libraries that are thread safe?  BoringSSL seems like the best option.

**Comment by bagder** [comment]
OpenSSL 1.1.0+, NSS, BoringSSL, schannel, securetransport, wolfssl are all thread-safe by default to the best of my knowledge. See our [thread safety documentation](https://curl.haxx.se/libcurl/c/threadsafe.html).
