### ISSUE TITLE
fatal error: 'zstd.h' file not found when building libcurl with Zstd support

### ISSUE THREAD

**Issue by Ishan09811** [curl/curl#14057]
### I did this

I'm encountering a build issue when trying to compile libcurl with Zstd support. The error message indicates that the zstd.h header file is not found, even though the Zstd library is installed on the system.

**Error Message:**
/home/runner/work/Troppical/Troppical/android/app/src/main/cpp/libraries/libcurl/lib/content_encoding.c:48:10: fatal error: 'zstd.h' file not found
  #include <zstd.h>
           ^~~~~~~~
  1 error generated.

### I expected the following

The build process should correctly locate the zstd.h header file and link against the Zstd library without errors.

### curl/libcurl version

8.9.0-DEV

### operating system

Ubuntu 22.04 GitHub Action CI

**Comment by Ishan09811** [comment]
This issue is also coming with opensslconf.h and brotli

**Comment by bagder** [comment]
We need more information.

1. How did (try to) you build curl
2. How did you install the dependencies you're telling the build to use?

**Comment by Ishan09811** [comment]
@bagder 
Actually I am building curl to use with an android project and you can see my full building script

```Android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode and save keystore
        env:
         ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
        run: |
         echo "$ANDROID_KEYSTORE_B64" | base64 --decode > ${{ github.workspace }}/android/app/ks.jks

      - name: Check isPr
        id: get_is_pr
        run: |
          is_pr=${{ github.event_name == 'pull_request' }}
          echo "::set-output name=is_pr::$is_pr"
      
      - name: Build with Gradle
        run: |
          sudo apt update
          sudo apt install m4 libtool automake autoconf libzstd-dev
          dpkg -L libzstd-dev | grep include
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install
          ./vcpkg install brotli
          export PKG_CONFIG_PATH=$(pwd)/packages/brotli_x64-linux/lib/pkgconfig
          cd ..
          cd android/app/src/main/cpp/libraries/libcurl/
          ./buildconf
          ./configure --with-openssl --without-brotli --without-zstd
          cd ../../../../../../..
          cd android/ 
          chmod +x gradlew
          ./gradlew assembleRelease
          cd ../..
        env:
          ANDROID_KEYSTORE_FILE: ks.jks
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          GITHUB_TOKEN: ${{ secrets.BUILD }}
          IS_PR: ${{ steps.get_is_pr.outputs.is_pr }}
        

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: troppical-android
          path: ./android/app/build/outputs/apk/release/app-release.apk```

**Comment by Ishan09811** [comment]
actually after many tries the zstd problem not solved so I tried to build without zstd but now the same error is causing with opensslconf.h

**Comment by bagder** [comment]
Then you are not installed the correct dependencies. You need to install -dev packages that include all the necessary includes etc.

We build with these dependencies all the time in CI and countless users and distros do it as well.

**Comment by Ishan09811** [comment]
> Then you have not installed the correct dependencies. You need to install -dev packages that include all the necessary includes etc.
> 
> We build with these dependencies all the time in CI and countless users and distros do it as well.

You can clearly see that I installed all correct dependencies 
``sudo apt install m4 libtool automake autoconf libzstd-dev`` including zstd

**Comment by bagder** [comment]
< You can clearly see that I installed all correct dependencies

1. There is no openssl-dev there.
2. You disable brotli and zstd in the build.

**Comment by bagder** [comment]
It will probably be easier if you stick to a fixed build instead of changing it, so that we can get to bottom of the problem. zstd, brotli and OpenSSL have worked fine with configure builds for a long time so we should just figure out what makes they glitch for you.

**Comment by Ishan09811** [comment]
@bagder 
actually it is still causing when zstd is enabled

**Comment by bagder** [comment]
Then decide what build you want to debug, stick to that. Tell us your configure line, your installed deps and show us your config.log from the failed build.

**Comment by Ishan09811** [comment]
> Then decide what build you want to debug, stick to that. Tell us your configure line, your installed deps and show us your config.log from the failed build.

But how can I provide the config.log as I am building it in workflow and I just want to solve the opensslconf.h problem

**Comment by bagder** [comment]
> But how can I provide the config.log as I am building it in workflow

Make the CI jobs display the log? Work it out locally first? That's not a curl issue.

> I just want to solve the opensslconf.h problem

1. That's not what the title of this issue says.
2. Then maybe start with installing the libssl-dev package?

**Comment by Ishan09811** [comment]
I already by installing libssl-dev but didn't work

**Comment by vszakats** [comment]
> > Then you have not installed the correct dependencies. You need to install -dev packages that include all the necessary includes etc.
> > We build with these dependencies all the time in CI and countless users and distros do it as well.
> 
> You can clearly see that I installed all correct dependencies `sudo apt install m4 libtool automake autoconf libzstd-dev` including zstd

Are Linux native `libzstd-dev`, `libssl-dev` packages the correct dependencies to cross-build an Android binary?

**Comment by bagder** [comment]
The configure invocation does not look like a cross-compile either. Should it?

**Comment by vszakats** [comment]
> The configure invocation does not look like a cross-compile either. Should it?

Yes, it's also a native build, and should look different for a cross-target.

**Comment by Ishan09811** [comment]
@bagder 
I also saw that the libssl.so is located in /lib/x86_64-linux-gnu/libssl.so
and the includes are located at /usr/include/openssl/
and you can also see my cmakeLists.txt for more information 
```cmake_minimum_required(VERSION 3.10.2)
project(troppical)

set(CMAKE_CXX_STANDARD 11)

add_library(apkdownloader SHARED apk_downloader.cpp)


add_library(OpenSSL::SSL STATIC IMPORTED)
add_library(OpenSSL::Crypto STATIC IMPORTED)
set_target_properties(OpenSSL::SSL PROPERTIES IMPORTED_LOCATION /lib/x86_64-linux-gnu/libssl.so)
set_target_properties(OpenSSL::Crypto PROPERTIES IMPORTED_LOCATION /lib/x86_64-linux-gnu/libcrypto.so)

set(Zstd_INCLUDE_DIRS "/usr/include/")
set(Zstd_LIBRARIES "/usr/lib/x86_64-linux-gnu/libzstd.so")

add_subdirectory(libraries/libcurl)
include_directories(${CMAKE_SOURCE_DIR}/include /usr/include/)

if (TARGET libcurl)
    set(CURL_LIB libcurl)
else()
    find_package(CURL REQUIRED)
    set(CURL_LIB ${CURL_LIBRARIES})
endif()

target_link_libraries(apkdownloader ${CURL_LIB})

find_library(log-lib log)
target_link_libraries(apkdownloader ${log-lib})```

**Comment by bagder** [comment]
Without answers and logs, we cannot assist you further.

**Comment by Ishan09811** [comment]
> Without answers and logs, we cannot assist you further.

Can you tell me where the logs will be generated so I can upload it as a artifact and provide you

**Comment by bagder** [comment]
I don't know.

**Comment by pheiduck** [comment]
You may need to install `libzstd-dev`.

**Comment by bagder** [comment]
This is a broken cross-compile for android, for which the dependencies seem to not be installed (correctly) and no build logs or answers to questions can be provided. I don't see how we can help any further. Mind-reading is fun, but too flaky.
