### ISSUE TITLE
failed to build debug static file in windows

### ISSUE THREAD

**Issue by Ashish2000L** [curl/curl#14089]
### I did this

I am using msvc 2022 for building the curl project version 8.8.0 using msvc developer cmd with nmake. 
I was using the command:
> cd winBuild
> nmake /f MakeFile.vc mode=static vc=17 debug=yes

but this is giving error while building: 
`
>nmake /f MakeFile.vc mode=static vc=17 debug=yes
Microsoft (R) Program Maintenance Utility Version 14.38.33133.0
Copyright (C) Microsoft Corporation.  All rights reserved.
configuration name: libcurl-vc17-x86-debug-static-ipv6-sspi-schannel
        C:\Users\user\AppData\Local\Android\Sdk\ndk\27.0.11902837\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi35-clang /Od /D_DEBUG /RTC1 /Z7 /LDd /MTd /DCURL_STATICLIB /I. /I ../lib /I../include /nologo /W4 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL  /DUSE_WIN32_IDN  /DUSE_IPV6  /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL /Fo"..\builds\libcurl-vc17-x86-debug-static-ipv6-sspi-schannel-obj-lib\\"  ..\lib\altsvc.c ..\lib\amigaos.c ..\lib\asyn-ares.c ..\lib\asyn-thread.c ..\lib\base64.c ..\lib\bufq.c ..\lib\bufref.c ..\lib\c-hyper.c ..\lib\cf-h1-proxy.c ..\lib\cf-h2-proxy.c ..\lib\cf-haproxy.c ..\lib\cf-https-connect.c ..\lib\cf-socket.c ..\lib\cfilters.c ..\lib\conncache.c ..\lib\connect.c ..\lib\content_encoding.c ..\lib\cookie.c ..\lib\curl_addrinfo.c ..\lib\curl_des.c ..\lib\curl_endian.c ..\lib\curl_fnmatch.c ..\lib\curl_get_line.c ..\lib\curl_gethostname.c ..\lib\curl_gssapi.c ..\lib\curl_memrchr.c ..\lib\curl_multibyte.c ..\lib\curl_ntlm_core.c ..\lib\curl_path.c ..\lib\curl_range.c ..\lib\curl_rtmp.c ..\lib\curl_sasl.c ..\lib\curl_sha512_256.c ..\lib\curl_sspi.c ..\lib\curl_threads.c ..\lib\curl_trc.c ..\lib\cw-out.c ..\lib\dict.c ..\lib\dllmain.c ..\lib\doh.c ..\lib\dynbuf.c ..\lib\dynhds.c ..\lib\easy.c ..\lib\easygetopt.c ..\lib\easyoptions.c ..\lib\escape.c ..\lib\file.c ..\lib\fileinfo.c ..\lib\fopen.c ..\lib\formdata.c ..\lib\ftp.c ..\lib\ftplistparser.c ..\lib\getenv.c ..\lib\getinfo.c ..\lib\gopher.c ..\lib\hash.c ..\lib\headers.c ..\lib\hmac.c ..\lib\hostasyn.c ..\lib\hostip.c ..\lib\hostip4.c ..\lib\hostip6.c ..\lib\hostsyn.c ..\lib\hsts.c ..\lib\http.c ..\lib\http1.c ..\lib\http2.c ..\lib\http_aws_sigv4.c ..\lib\http_chunks.c ..\lib\http_digest.c ..\lib\http_negotiate.c ..\lib\http_ntlm.c ..\lib\http_proxy.c ..\lib\idn.c ..\lib\if2ip.c ..\lib\imap.c ..\lib\inet_ntop.c ..\lib\inet_pton.c ..\lib\krb5.c ..\lib\ldap.c ..\lib\llist.c ..\lib\macos.c ..\lib\md4.c ..\lib\md5.c ..\lib\memdebug.c ..\lib\mime.c ..\lib\mprintf.c ..\lib\mqtt.c ..\lib\multi.c ..\lib\netrc.c ..\lib\nonblock.c ..\lib\noproxy.c ..\lib\openldap.c ..\lib\parsedate.c ..\lib\pingpong.c ..\lib\pop3.c ..\lib\progress.c ..\lib\psl.c ..\lib\rand.c ..\lib\rename.c ..\lib\request.c ..\lib\rtsp.c ..\lib\select.c ..\lib\sendf.c ..\lib\setopt.c ..\lib\sha256.c ..\lib\share.c ..\lib\slist.c ..\lib\smb.c ..\lib\smtp.c ..\lib\socketpair.c ..\lib\socks.c ..\lib\socks_gssapi.c ..\lib\socks_sspi.c ..\lib\speedcheck.c ..\lib\splay.c ..\lib\strcase.c ..\lib\strdup.c ..\lib\strerror.c ..\lib\strtok.c ..\lib\strtoofft.c ..\lib\system_win32.c ..\lib\telnet.c ..\lib\tftp.c ..\lib\timediff.c ..\lib\timeval.c ..\lib\transfer.c ..\lib\url.c ..\lib\urlapi.c ..\lib\version.c ..\lib\version_win32.c ..\lib\warnless.c ..\lib\ws.c
clang: error: no such file or directory: '/Od'
clang: error: no such file or directory: '/D_DEBUG'
clang: error: no such file or directory: '/RTC1'
clang: error: no such file or directory: '/Z7'
clang: error: no such file or directory: '/LDd'
clang: error: no such file or directory: '/MTd'
clang: error: no such file or directory: '/DCURL_STATICLIB'
clang: error: no such file or directory: '/I.'
clang: error: no such file or directory: '/I'
clang: error: no such file or directory: '/I../include'
clang: error: no such file or directory: '/nologo'
clang: error: no such file or directory: '/W4'
clang: error: no such file or directory: '/EHsc'
clang: error: no such file or directory: '/DWIN32'
clang: error: no such file or directory: '/FD'
clang: error: no such file or directory: '/c'
clang: error: no such file or directory: '/DBUILDING_LIBCURL'
clang: error: no such file or directory: '/DUSE_WIN32_IDN'
clang: error: no such file or directory: '/DUSE_IPV6'
clang: error: no such file or directory: '/DUSE_WINDOWS_SSPI'
clang: error: no such file or directory: '/DUSE_SCHANNEL'
clang: error: no such file or directory: '/Fo..\builds\libcurl-vc17-x86-debug-static-ipv6-sspi-schannel-obj-lib\'
NMAKE : fatal error U1077: 'C:\Users\user\AppData\Local\Android\Sdk\ndk\27.0.11902837\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi35-clang /Od /D_DEBUG /RTC1 /Z7 /LDd /MTd /DCURL_STATICLIB /I. /I ../lib /I../include /nologo /W4 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL  /DUSE_WIN32_IDN  /DUSE_IPV6  /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL /Fo"..\builds\libcurl-vc17-x86-debug-static-ipv6-sspi-schannel-obj-lib\\"  ..\lib\altsvc.c ..\lib\amigaos.c ..\lib\asyn-ares.c ..\lib\asyn-thread.c ..\lib\base64.c ..\lib\bufq.c ..\lib\bufref.c ..\lib\c-hyper.c ..\lib\cf-h1-proxy.c ..\lib\cf-h2-proxy.c ..\lib\cf-haproxy.c ..\lib\cf-https-connect.c ..\lib\cf-socket.c ..\lib\cfilters.c ..\lib\conncache.c ..\lib\connect.c ..\lib\content_encoding.c ..\lib\cookie.c ..\lib\curl_addrinfo.c ..\lib\curl_des.c ..\lib\curl_endian.c ..\lib\curl_fnmatch.c ..\lib\curl_get_line.c ..\lib\curl_gethostname.c ..\lib\curl_gssapi.c ..\lib\curl_memrchr.c ..\lib\curl_multibyte.c ..\lib\curl_ntlm_core.c ..\lib\curl_path.c ..\lib\curl_range.c ..\lib\curl_rtmp.c ..\lib\curl_sasl.c ..\lib\curl_sha512_256.c ..\lib\curl_sspi.c ..\lib\curl_threads.c ..\lib\curl_trc.c ..\lib\cw-out.c ..\lib\dict.c ..\lib\dllmain.c ..\lib\doh.c ..\lib\dynbuf.c ..\lib\dynhds.c ..\lib\easy.c ..\lib\easygetopt.c ..\lib\easyoptions.c ..\lib\escape.c ..\lib\file.c ..\lib\fileinfo.c ..\lib\fopen.c ..\lib\formdata.c ..\lib\ftp.c ..\lib\ftplistparser.c ..\lib\getenv.c ..\lib\getinfo.c ..\lib\gopher.c ..\lib\hash.c ..\lib\headers.c ..\lib\hmac.c ..\lib\hostasyn.c ..\lib\hostip.c ..\lib\hostip4.c ..\lib\hostip6.c ..\lib\hostsyn.c ..\lib\hsts.c ..\lib\http.c ..\lib\http1.c ..\lib\http2.c ..\lib\http_aws_sigv4.c ..\lib\http_chunks.c ..\lib\http_digest.c ..\lib\http_negotiate.c ..\lib\http_ntlm.c ..\lib\http_proxy.c ..\lib\idn.c ..\lib\if2ip.c ..\lib\imap.c ..\lib\inet_ntop.c ..\lib\inet_pton.c ..\lib\krb5.c ..\lib\ldap.c ..\lib\llist.c ..\lib\macos.c ..\lib\md4.c ..\lib\md5.c ..\lib\memdebug.c ..\lib\mime.c ..\lib\mprintf.c ..\lib\mqtt.c ..\lib\multi.c ..\lib\netrc.c ..\lib\nonblock.c ..\lib\noproxy.c ..\lib\openldap.c ..\lib\parsedate.c ..\lib\pingpong.c ..\lib\pop3.c ..\lib\progress.c ..\lib\psl.c ..\lib\rand.c ..\lib\rename.c ..\lib\request.c ..\lib\rtsp.c ..\lib\select.c ..\lib\sendf.c ..\lib\setopt.c ..\lib\sha256.c ..\lib\share.c ..\lib\slist.c ..\lib\smb.c ..\lib\smtp.c ..\lib\socketpair.c ..\lib\socks.c ..\lib\socks_gssapi.c ..\lib\socks_sspi.c ..\lib\speedcheck.c ..\lib\splay.c ..\lib\strcase.c ..\lib\strdup.c ..\lib\strerror.c ..\lib\strtok.c ..\lib\strtoofft.c ..\lib\system_win32.c ..\lib\telnet.c ..\lib\tftp.c ..\lib\timediff.c ..\lib\timeval.c ..\lib\transfer.c ..\lib\url.c ..\lib\urlapi.c ..\lib\version.c ..\lib\version_win32.c ..\lib\warnless.c ..\lib\ws.c ' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86\nmake.exe" /NOLOGO /F MakefileBuild.vc' : return code '0x2'
Stop.`

### I expected the following

I am expecting to get the debug build so that I can add the same to my msvc project.

### curl/libcurl version

curl 8.8.0

### operating system

windows 11 x86

**Comment by bagder** [comment]
> clang: error: no such file or directory

That indicates that you are trying this with clang, not Visual C++ for which the winbuild makefiles are written.

**Comment by jzakrzewski** [comment]
Even better: `C:\Users\user\AppData\Local\Android\Sdk\ndk\27.0.11902837\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi35-clang`
