### ISSUE TITLE
Curl 8.8.0 return http_code 000

### ISSUE THREAD

**Issue by evyaroshevich** [curl/curl#14105]
### I did this

1. `docker run -ti --rm registry.gitlab.com/security-products/container-scanning:6 sh`

2. `sudo apt update && sudo apt install -y curl`

3. `$ curl --version`
curl 8.8.0 (x86_64-pc-linux-gnu) libcurl/8.8.0 GnuTLS/3.8.5 zlib/1.3.1 brotli/1.0.9 zstd/1.5.6 libidn2/2.3.3 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.52.0 ngtcp2/1.5.0 nghttp3/1.3.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2024-05-22, security patched: 8.8.0-2
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

4. `$ cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

5. `$ curl -v --write-out %{http_code} https://github.com/`
* Host github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.121.3
*   Trying 140.82.121.3:443...
* Connected to github.com (140.82.121.3) port 443
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* found 140 certificates in /etc/ssl/certs/ca-certificates.crt
* found 420 certificates in /etc/ssl/certs
* SSL connection using TLS1.3 / ECDHE_RSA_AES_128_GCM_SHA256
*    Subject: CN=github.com
*    Issuer: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
*    Version: 2
*    Serial Number: 4e:28:f7:86:b6:6c:1a:3b:94:2c:d2:c4:0e:b7:42:a5:
* Closing connection
curl: (43) A libcurl function was given a bad argument
000

### I expected the following

curl http_code return 200, 301, etc.

### curl/libcurl version

curl 8.8.0 (x86_64-pc-linux-gnu) libcurl/8.8.0

### operating system

Debian GNU/Linux 12 (bookworm)

**Comment by bagder** [comment]
I think this is a duplicate of #13845, already fixed in master

**Comment by bagder** [comment]
This became a problem with the switch to GnuTLS because when OpenSSL was used, libcurl's own parser for this (which has the bug) was not used.

**Comment by ksidirop-laerdal** [comment]
> This became a problem with the switch to GnuTLS because when OpenSSL was used, libcurl's own parser for this (which has the bug) was not used.

Any hints as to when the new release of curl (containing this bug fix) will be out?

**Comment by icing** [comment]
"curl 8.9.0 is scheduled to ship on July 24, 2024": https://curl.se/docs/releases.html
