### ISSUE TITLE
Email payload is broken when set CURLOPT_CRLF = 1

### ISSUE THREAD

**Issue by vuonganh1993** [curl/curl#14165]
### I did this

My program sends emails by curl with CURLOPT_CRLF = 1. Everything worked fine with 7.76.0. Recently, we upgraded to curl 8.8.0 and the email is always broken if the payload is greater than 64Kb. I found out that the payload is missing some data.
![image](https://github.com/user-attachments/assets/8b67e643-b030-4c30-9020-55279ea28986)

To fix the issue, I need to set CURLOPT_CRLF = 0 and add "\r\n" to the end of every line in the payload. it works fine again.

### curl/libcurl version

curl 8.8.0

### operating system

Windows Enterprise 11

**Comment by bagder** [comment]
please tell us a way how we can reproduce this!

**Comment by vuonganh1993** [comment]
Hi @bagder ,
Attach the sample code and the sample email file.
For testing, I place the email file at "C:\test_email.txt", and then read the content as the input stream.

[test_email.txt](https://github.com/user-attachments/files/16192501/test_email.txt)
[send_email_code.txt](https://github.com/user-attachments/files/16192537/send_email_code.txt)

**Comment by icing** [comment]
I can verify that there is a bug with input larger than 64.

**Comment by vuonganh1993** [comment]
Thank @icing

**Comment by icing** [comment]
I propose #14169 as fix for this, including a modified test case to trigger the bug.

If you can build curl yourself it would be nice if you could verify this. (There is a Windows nightly build out there, I think, but could not find a link. Someone can help out here?)

**Comment by vszakats** [comment]
Daily Windows builds can be found here, scroll down to Artifacts:
https://github.com/curl/curl-for-win/actions/workflows/daily.yml

(don't mind the red, it affects mac builds and pushed a(nother) fix just today.)
