### ISSUE TITLE
tests: 1705 fails when running around UTC midnight

### ISSUE THREAD

**Issue by vszakats** [curl/curl#14173]
### I did this

Pushed PR to curl. 1705 did not pass in many jobs. They turned green when re-run.

```
Sat, 13 Jul 2024 00:05:33 GMT test 1705...[managen makes manpage]
Sat, 13 Jul 2024 00:05:33 GMT
Sat, 13 Jul 2024 00:05:33 GMT 1705: stdout FAILED:
Sat, 13 Jul 2024 00:05:33 GMT --- log/check-expected	2024-07-13 00:05:33.202554551 +0000
Sat, 13 Jul 2024 00:05:33 GMT +++ log/check-generated	2024-07-13 00:05:33.202554551 +0000
Sat, 13 Jul 2024 00:05:33 GMT @@ -24,7 +24,7 @@
Sat, 13 Jul 2024 00:05:33 GMT .\"[LF]
Sat, 13 Jul 2024 00:05:33 GMT .\" DO NOT EDIT. Generated by the curl project managen man page generator.[LF]
Sat, 13 Jul 2024 00:05:33 GMT .\"[LF]
Sat, 13 Jul 2024 00:05:33 GMT -.TH curl 1 "2024-07-12" "curl 8.9.0" "curl Manual"[LF]
Sat, 13 Jul 2024 00:05:33 GMT +.TH curl 1 "2024-07-13" "curl 8.9.0" "curl Manual"[LF]
Sat, 13 Jul 2024 00:05:33 GMT .SH DESCRIPTION[LF]
Sat, 13 Jul 2024 00:05:33 GMT \fBcurl\fP is a tool for transferring data from or to a server using URLs. It[LF]
Sat, 13 Jul 2024 00:05:33 GMT supports these protocols: DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS,[LF]
Sat, 13 Jul 2024 00:05:33 GMT == Contents of files in the log/ dir after test 1705
```
Ref: https://github.com/curl/curl/actions/runs/9915475186/job/27396416495?pr=14172#step:23:3240
Ref: https://github.com/curl/curl/actions/runs/9915475193/job/27396380286?pr=14172

Maybe we should set `SOURCE_DATE_EPOCH` for tests and also honor it for `%DATE` in test data?

### I expected the following

Tests to pass.

### curl/libcurl version

master

### operating system

any

**Comment by dfandrich** [comment]
If so, we could reset it every month (or even every day) like the random seed to make sure it gets a variety of values eventually.

**Comment by bagder** [comment]
> Maybe we should set SOURCE_DATE_EPOCH for tests and also honor it for %DATE in test data?

I think that's the best fix, yes.
