### ISSUE TITLE
Some files cannot be downloaded normally

### ISSUE THREAD

**Issue by ProgramCX** [curl/curl#14222]
### I did this

I developed an app using libcurl.I used the app to download Visual Studio 2022 by pasting the url,https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030:6960014b3c8749bdaf1056f497cf285d ,to the text box in my app,but instead it downloaded an aspx file.
![image](https://github.com/user-attachments/assets/a4468f42-89dd-48a7-8932-3175d333762e)

### I expected the following

I hope it could prase the url and download an excutable file that I want.

### curl/libcurl version

curl 8.8.0

### operating system

Windows 11 24h2

**Comment by icing** [comment]
What happens when you use the command line `curl` with that url?

**Comment by ProgramCX** [comment]
![image](https://github.com/user-attachments/assets/e24a7d19-ce39-4b64-83c9-6a44565283bd)
It says that "channel" is not an inner or external command.

**Comment by ProgramCX** [comment]
![image](https://github.com/user-attachments/assets/ad798442-a4fa-4254-bd23-9101528f30af)
It says that "channel" is not an inner or external command.The terminal mistakenly takes the word "channel" as a command.

**Comment by icing** [comment]
I think you need to put the url into double quotes, otherwise the command line chops it up.

**Comment by ProgramCX** [comment]
Could you give some solution to the problem?It seems that curl couldn't analyse some url that couldn't be used to download a file directly.

**Comment by icing** [comment]
I am not familiar enough with Windows, but the `downloadVS.aspx` file is the one the server returned. Now, curl does by default not save it under the name the server suggests. For that, you can invoke curl with the open `-JO`like in:

```
 ./src/curl -JO 'https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030:6960014b3c8749bdaf1056f497cf285d'
```

Then it saves the file in `VisualStudioSetup.exe`.

**Comment by ProgramCX** [comment]
It works.Thank you very much.But is there any APIs available so that I can use them in my app?

**Comment by icing** [comment]
The workings of `-J`, or in longer form `--remote-name`, are implemented in the curl tool itself, not libcurl. You can read the source code to see how that works. In short, you need to inspect the HTTP headers sent back by the server to catch the name it suggests.

**Comment by ProgramCX** [comment]
> The workings of `-J`, or in longer form `--remote-name`, are implemented in the curl tool itself, not libcurl. You can read the source code to see how that works. In short, you need to inspect the HTTP headers sent back by the server to catch the name it suggests.

OK.Thanks a  lot.
