### ISSUE TITLE
HTTPS GET Json Response Headers with out Content-Length, default as 0; this case no json body;

### ISSUE THREAD

**Issue by 919858271** [curl/curl#14231]
### I did this

call https://stock.xueqiu.com/v5/stock/realtime/quotec.json?symbol=SZ002236; Json Response with Content-Length: 0; no body output; but it has

### I expected the following

support

### curl/libcurl version

curl 8.8.0

### operating system

windows 10

**Comment by dfandrich** [comment]
If the Content-Length: is 0 then there is, by definition, no body. If you're getting different results with another client, like a browser, then there's probably a different header to which the server responds differently.

**Comment by bagder** [comment]
If the server says the content size is nothing but at the same time tries to report content, then that is a server error - not a curl issue.

**Comment by 919858271** [comment]
for same url. using python requests lib ,the body response is ok; but curl does not work well

**Comment by bagder** [comment]
That's not a strong argument if the server is misbehaving. If you can provide a URL where we can reproduce this, we can take a look.
