### ISSUE TITLE
docs: mention additional details about arguments

### ISSUE THREAD

**Issue by icy17** [curl/curl#14248]
### Specify which documentation you found a problem with

[curl_easy_strerror](https://curl.se/libcurl/c/curl_easy_strerror.html)
[curl_easy_cleanup](https://curl.se/libcurl/c/curl_easy_cleanup.html)
[curl_slist_free_all](https://curl.se/libcurl/c/curl_slist_free_all.html)
[curl_free](https://curl.se/libcurl/c/curl_free.html)
[curl_url_cleanup](https://curl.se/libcurl/c/curl_url_cleanup.html)
[curl_multi_add_handle](https://curl.se/libcurl/c/curl_multi_add_handle.html)
[curl_multi_cleanup](https://curl.se/libcurl/c/curl_multi_cleanup.html)
[curl_multi_perform](https://curl.se/libcurl/c/curl_multi_perform.html)
[curl_mime_addpart](https://curl.se/libcurl/c/curl_mime_addpart.html)
[curl_multi_setopt](https://curl.se/libcurl/c/curl_multi_setopt.html)
[curl_mime_init](https://curl.se/libcurl/c/curl_mime_init.html)

### The problem

There are other types of security rules that are missing in the documentation. I believe incorporating these rules could help developers learn how to correctly use APIs and reduce the risk of security issues.

I will provide a table describing the missing security rules:
| API | parameter index (begin with 1) | Security rules | URL |
|:----------:|:----------:|:----------:|:----------:|
| curl_slist_free_all | 1 | parameter must not be used later (without re-initialize) | https://curl.se/libcurl/c/curl_slist_free_all.html |
| curl_multi_cleanup | 1 | parameter must not be used later (without re-initialize) | https://curl.se/libcurl/c/curl_multi_cleanup.html |
| curl_easy_strerror | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_easy_strerror.html |
| curl_free | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_free.html |
| curl_multi_add_handle | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_multi_add_handle.html |
| curl_multi_cleanup | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_multi_cleanup.html |
| curl_multi_perform | 2 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_multi_perform.html |
| curl_mime_addpart | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_mime_addpart.html |
| curl_mime_init | 1 | parameter must be initialized using xxx (other API) | https://curl.se/libcurl/c/curl_mime_init.html |
| curl_easy_cleanup | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_easy_cleanup.html |
| curl_slist_free_all | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_slist_free_all.html |
| curl_free | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_free.html |
| curl_url_cleanup | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_url_cleanup.html |
| curl_multi_cleanup | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_multi_cleanup.html |
| curl_multi_cleanup | 1 | Do not call this API multiple times for the same parameter. | https://curl.se/libcurl/c/curl_multi_cleanup.html |

**Comment by bagder** [comment]
> curl_easy_strerror

What do you mean this should mention?

> curl_free

Please elaborate and give me an example that would match your requirement.

**Comment by bagder** [comment]
The "must be initialized using" and "Do not call this API multiple times" remarks I don't quite agree with and will leave unchanged.

**Comment by icy17** [comment]
Perhaps rules that describe the parameters can be helpful? For example, for the API `curl_easy_strerror`, the rules to describe "parameter must be initialized using xxx (other API)" might be: The `curl_easy_strerror` function returns a string describing the CURLcode error code passed in the argument errornum. _The CURLcode error code is obtained from the return value of other APIs._
For a rule describing "Do not call this API multiple times," for `curl_free`, it might be: curl_free reclaims memory that has been obtained through a libcurl call _and should not be freed before._

**Comment by bagder** [comment]
> The CURLcode error code is obtained from the return value of other APIs.

But it doesn't have to. It just converts from a number to a string, the error code does not have to be obtained from any specific function.

> for curl_free, it might be: curl_free reclaims memory that has been obtained through a libcurl call and should not be freed before.

That's just silly.
