### ISSUE TITLE
docs: no mention that NULL is not OK as argument

### ISSUE THREAD

**Issue by icy17** [curl/curl#14247]
### Specify which documentation you found a problem with

[curl_easy_escape](https://curl.se/libcurl/c/curl_easy_escape.html)
[curl_multi_perform](https://curl.se/libcurl/c/curl_multi_perform.html)

### The problem

Hi, I've observed that some security rules are absent from the documentation.

For the security rule "parameters must not be NULL," its omission in the documentation can lead to significant security issues.

Firstly, while best programming practices dictate that developers should avoid passing NULL parameters to an API, this guideline may not be obvious to less experienced developers, increasing the risk of overlooking necessary security checks.

Secondly, many APIs receive parameters from other functions or APIs, which might not be adequately checked for NULL, posing a risk even for experienced developers.

Therefore, it is crucial to explicitly mention in the documentation that NULL checks must be conducted on specified parameters before an API is used. Including these security rules will help developers identify potential security issues more effectively during testing.

I will provide a list of APIs requiring checks along with their corresponding parameters：
| API | parameter index (begin with 1) | URL |
|:----------:|:----------:|:----------:|
| curl_easy_escape | 2 | https://curl.se/libcurl/c/curl_easy_escape.html |
| curl_multi_perform| 2 | https://curl.se/libcurl/c/curl_multi_perform.html |

**Comment by icy17** [comment]
> What are you proposing we say? We really mean that you pass on the input arguments as documented?

I've found that NULL pointers are bad for a very small number of APIs, while other APIs implement NULL checking inside the API. However, I have to admit that for the APIs mentioned above, it is very obvious that the developers shouldn't pass a NULL pointer. Therefore, I'm not sure if the documentation should include such rules like _"The caller must not assign a NULL value to the parameter 2"_ to clearly remind the user.

**Comment by bagder** [comment]
I decided to opt to make the functions a little more resilient to NULL arguments.
