### ISSUE TITLE
SSL verification fails

### ISSUE THREAD

**Issue by finkandreas** [curl/curl#14243]
### I did this

I have a self-signed certificate with 3 DNS alternative names and one IP address as alternative name. The certificate shows this when inspecting with `openssl x509 -text`:
```
            X509v3 Subject Alternative Name: critical
                DNS:*.vault-internal, DNS:*.vault-internal.vault.svc.cluster.local, DNS:*.vault, IP Address:127.0.0.1
```

Now doing `curl --cacert /path/to/root.crt https://127.0.0.1:8200` works perfectly fine, but doing `curl --cacert /path/to/root.crt https://vault-0.vault-internal:8200` fails with the message
```
curl: (60) SSL: no alternative certificate subject name matches target host name 'vault-0.vault-internal'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

 I do not understand why the wildcard alternative host name `*.vault-internal` would not match `vault-0.vault-internal`.

### I expected the following

Curl should accept both forms for contacting the server.

### curl/libcurl version

```bash
~ $ curl -V
curl 8.8.0 (x86_64-pc-linux-musl) libcurl/8.8.0 OpenSSL/3.1.5 zlib/1.3.1 brotli/1.1.0 libidn2/2.3.4 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.58.0
Release-Date: 2024-05-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets
```

### operating system

```bash
~ $ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```
I am running the curl docker container.

**Comment by bagder** [comment]
Because a certificate wildcard cannot be `*.tld`, there needs to be another dot in there.

**Comment by finkandreas** [comment]
Ok, but  the same error when I am trying it with the long name, i.e. `curl https://vault-0.vault-internal.vault.svc.cluster.local:8200`
```bash
testpod:~# curl https://vault-0.vault-internal.vault.svc.cluster.local:8200
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
The DNS entry `*.vault-internal.vault.svc.cluster.local` in the certificate looks good to me, it should've matched `vault-0.vault-internal.vault.svc.cluster.local`.

**Comment by finkandreas** [comment]
Ah got it. Thanks for the explaination. With the long name it works, i.e. `curl --cacert /path/to/root.crt https://vault-0.vault-internal.vault.svc.cluster.local:8200`
