### ISSUE TITLE
multi-uv.c always produces a "bad file descriptor" error in `curl_perform`

### ISSUE THREAD

**Issue by TrifleMichael** [curl/curl#14254]
### Specify which documentation you found a problem with

https://curl.se/libcurl/c/multi-uv.html

### The problem

I've found that in the example the first time a socket is opened it is almost immediately closed with the aforementioned error.  After that, the socket is opened again and only then the download begins and finishes.

I've tested this on both Ubuntu 24.04 and 20.04, also both with on a remote production server and a localhost test server.

The error can be shown by checking the status in `curl_perform`:

```
static void curl_perform(uv_poll_t *req, int status, int events)
{
  if (status != 0) {
    char buff[1000];
    uv_strerror_r(status, buff, 1000);
    std::cout << "UV error - " << buff << "\n";
  }
  int running_handles;
  int flags = 0;
  curl_context_t *context;
 
  if(events & UV_READABLE)
    flags |= CURL_CSELECT_IN;
  if(events & UV_WRITABLE)
    flags |= CURL_CSELECT_OUT;
 
  context = (curl_context_t *) req->data;
 
  curl_multi_socket_action(curl_handle, context->sockfd, flags,
                           &running_handles);
 
  check_multi_info();
}
```

**Comment by bagder** [comment]
Which libcurl version did you experience this with?

**Comment by TrifleMichael** [comment]
> Which libcurl version did you experience this with?

I'm using:
libcurl version: 8.5.0
libuv version: 1.48.0 (77824)

**Comment by TrifleMichael** [comment]
I've made an additional observation, that this error only pops up when a socket is opened for which `curl_sockaddr->family` is equal to 10 in `CURLOPT_OPENSOCKETFUNCTION`.

**Comment by bagder** [comment]
I just tested it now with libcurl 8.9.0 and libuv 1.48.0 but I cannot reproduce.

Does IPv6 connections normally work for you? Can you share a command line (URL) that triggers the problem for you?

**Comment by TrifleMichael** [comment]
Something seems to be wrong with how my machine handles IPv6, as both `curl -6 google.com` and `ping {IPv6 address of google}` hangs without response. As such I'm closing the issue as it seems it's not related to libcurl specifically.
