### ISSUE TITLE
test failures with simulated EAGAINs

### ISSUE THREAD

**Issue by icing** [curl/curl#14263]
### I did this

Making 90% of socket send() calls to return EAGAIN.

```
make -j20 && (cd tests && make -j20 && CURL_DBG_SOCK_WBLOCK=90 ./runtests.pl -a -j40)
```

On master 4111d10803cc3b81265f12cdf147750ca3031b60, with #14525 and #14526:

```
FAIL 652: 'SMTP with encoded huge mime data contents' SMTP, MIME
FAIL 1191: 'MQTT PUBLISH' MQTT, MQTT PUBLISH
FAIL 1193: 'MQTT PUBLISH 2k payload' MQTT, MQTT PUBLISH
FAIL 1198: 'MQTT PUBLISH empty payload, single space topic' MQTT, MQTT SUBSCRIBE
FAIL 1200: 'Gopher index' GOPHER, INDEX
FAIL 1201: 'Gopher selector' GOPHER, SELECTOR
FAIL 1202: 'Gopher query' GOPHER, QUERY
FAIL 1203: 'Gopher IPv6 index' GOPHER-ipv6, IPv6, INDEX
FAIL 1272: 'Gophers index' GOPHER, GOPHERS, INDEX
FAIL 1916: 'MQTT PUBLISH with no POSTFIELDSIZE set' MQTT, MQTT PUBLISH
FAIL 2201: 'MQTT PUBLISH with user and password valid' MQTT, MQTT PUBLISH
FAIL 3017: 'MQTT SUBSCRIBE with pathological PUBLISH length' MQTT, MQTT SUBSCRIBE

TESTFAIL: These test cases failed: 652 1191 1193 1198 1200 1201 1202 1203 1272 1916 2201 3017
```

### I expected the following

test runs to succeed.

### curl/libcurl version

curl 8.9.0-DEV (x86_64-apple-darwin23.5.0) libcurl/8.9.0-DEV quictls/3.1.4 zlib/1.2.12 brotli/1.1.0 zstd/1.5.6 c-ares/1.28.1 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.62.1 ngtcp2/1.6.0 nghttp3/1.4.0 librtmp/2.3

### operating system

Darwin xxx 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64

**Comment by calvin2021y** [comment]
I guess for a busy event base multi handle case, timeout with proxy could be related with EAGAIN?

**Comment by icing** [comment]
> I guess for a busy event base multi handle case, timeout with proxy could be related with EAGAIN?

I plan to work on fixing these failures, using our DEBUG options to simulate rare network conditions.

**Comment by icing** [comment]
I split off the failure of test652 into #14527 and added items for MQTT and Gopher in TODO per #14528.

Closing this issue now.
