### ISSUE TITLE
configure check for static openssl dependency -ldl is broken

### ISSUE THREAD

**Issue by jay** [curl/curl#1426]
### I did this

I ran configure with a custom ssl path to static openssl and it could not detect that -ldl is required. In my case the detection is never done because HAVECRYPTO is never properly detected.

configure will [check for crypto lib](https://github.com/curl/curl/blob/curl-7_53_1/configure.ac#L1512-L1525) by trying to link using function HMAC_Update and HMAC_Init_ex. The problem is at this point the -lssl (which requires -ldl in this static case) is already in LIBS and therefore is used for the link test:

~~~
configure:22350: checking for HMAC_Update in -lcrypto
configure:22372: gcc -o conftest -O2 -Wno-system-headers   -I/home/owner/openssl-1.0.2k/../openssl/include  -L/home/owner/openssl/lib -L/home/owner/openssl-1.0.2k/../openssl/lib conftest.c -lcrypto  -lssl -lcrypto -llber -lldap -lz  >&5
/home/owner/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
...
~~~

So HAVECRYPTO is never set yes and the subsequent checks that should be done are never called. One of those is the [check for -ldl](https://github.com/curl/curl/blob/curl-7_53_1/configure.ac#L1528-L1566). So -lssl I think would have to be removed somehow for the HAVECRYPTO test. Also -lcrypto is already in LIBS at this point as well so maybe we could just skip the test in that case.

Since -ldl afaik is required by -lssl static I don't know why we're only testing it if HAVECRYPTO, and it should probably be tested regardless.

Also I think SSLeay_add_all_algorithms in the -ldl test will need to be replaced for a function that is also in OpenSSL 1.1.0.

Ref: #1420
/cc @tessus

**Comment by bagder** [comment]
Yeah, the openssl static lib detection fails without -ldl provided in `LIBS` so the -ldl check is clearely wrong. We should probably either
1. re-run the openssl check with -ldl if it fails to see if we should add -ldl, or
2. just rip out the -ldl check and go back to how we had it before.

**Comment by jay** [comment]
I tested this issue again with OpenSSL 1.0.2 static now that #1427 is in master.

~~~
configure: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure: pkg-config: SSL_LDFLAGS: "-L/home/owner/openssl-static-installdir/lib"
configure: pkg-config: SSL_CPPFLAGS: "-I/home/owner/openssl-static-installdir/include"
checking for HMAC_Update in -lcrypto... no
checking for HMAC_Init_ex in -lcrypto... no
checking OpenSSL linking with -ldl... yes
checking for SSL_connect in -lssl... no
checking for ssl with RSAglue/rsaref libs in use... checking for SSL_connect in -lssl... (cached) no
no
configure: error: OpenSSL libs and/or directories were not found where specified!
~~~

config.log portion
~~~
configure:22508: checking for SSL_connect in -lssl
configure:22530: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers -isystem /home/owner/openssl-static-installdir/include  -I/home/owner/openssl-static-installdir/include/openssl -I/home/owner/openssl-static-installdir/include -L/home/owner/openssl-static-installdir/lib  -L/home/owner/openssl-static-installdir/lib conftest.c -lssl  -ldl -lssl -lcrypto -llber -lldap -lz  >&5
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x402): undefined reference to `dlerror'
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x474): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x532): undefined reference to `dlerror'
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x599): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5fd): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x635): undefined reference to `dlerror'
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x6d1): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x739): undefined reference to `dlerror'
/home/owner/openssl-static-installdir/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x792): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
~~~

Notice it's -lssl  -ldl -lssl -lcrypto. LIBS may be set [too early](https://github.com/curl/curl/blob/63503a9/configure.ac#L1503). If -ldl and -lpthread are needed I think LIBS should probably look like `LIBS=$SSL_LIBS -lpthread -ldl $LIBS`

**Comment by bagder** [comment]
It works for me with my custom OpenSSL build from their git master. It needs both -ldl and -lpthread.

I'm reluctant to spend much more time on this and I rather go back to the old: auto-detecting dependencies for static libs properly is a race we can never win.

**Comment by bagder** [comment]
The original issue this is filed for was basically a ghost case and no bug to begin with. During the struggle we fixed some details. Now let's consider this case closed. If there are additional quirks in the configure script (or others) to address, let's open new dedicated issues focused on those.
