### ISSUE TITLE
`%` for stderr is documented for `--trace`, but not `--trace-ascii`

### ISSUE THREAD

**Issue by emanuele6** [curl/curl#14265]
### Specify which documentation you found a problem with

>     --trace <file>
>            Save a full trace dump of all incoming and outgoing data, includ‐
>            ing descriptive information, in the given output file. Use "-" as
>            filename to have the output sent to stdout. Use "%"  as  filename
>            to have the output sent to stderr.

---
>     --trace-ascii <file>
>            Save a full trace dump of all incoming and outgoing data, includ‐
>            ing descriptive information, in the given output file. Use "-" as
>            filename to have the output sent to stdout.

### The problem

`--trace-ascii` also supports `%` to output to stderr, but it is not documented.

**Comment by bagder** [comment]
I added a mention in commit 15e8cebd64701e6c4ac44b6bda5860af4ebb8e2b already!

**Comment by emanuele6** [comment]
Sorry! I forgot to verify that the issue still existed on the master brach of the repository.
