### ISSUE TITLE
iOS: fatal error: 'Security/cssmtype.h' file not found

### ISSUE THREAD

**Issue by sergio-nsk** [curl/curl#14269]
### I did this

Got build errors:
```
In file included from curl/lib/vtls/sectransp.c:58:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:28:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:50:10: fatal error: 'Security/cssmtype.h' file not found
#include <Security/cssmtype.h>
         ^~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks/Security.framework/Headers/SecCertificate.h:50:10: note: did not find header 'cssmtype.h' in framework
      'Security' (loaded from '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.5.sdk/System/Library/Frameworks')
1 error generated.
```
@vszakats, the error is caused by this change: https://github.com/curl/curl/commit/ff784af461175584c73e7e2b65af00b1a5a6f67f

### curl/libcurl version

curl 8.9.0

### operating system

macOS 14.5, target platforn iOS 17.5

**Comment by cajus** [comment]
Same here.

**Comment by vszakats** [comment]
Can you try reducing that change, and see which one fixes it, e.g. by
1. deleting the local `TARGET_*` logic
2. deleting the `sys/types.h` include.
3. moving back the `TargetConditionals.h` include to its original position.

If we know which one is causing this, we can continue figuring out why.

**Comment by sergio-nsk** [comment]
Sure, I can localize a line, tomorrow or next day.

**Comment by sergio-nsk** [comment]
Wonder, why you use such construct like `defined(TARGET_OS_MAC) && TARGET_OS_MAC`. See [3.8.1 Conditional inclusion](https://port70.net/~nsz/c/c89/c89-draft.html#3.8.1) - Semantics in C89:
> <...> then all remaining identifiers are replaced with 0. <...>

- If `TARGET_OS_MAC` is defined as 0: `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 1 && 0 is 0
- If `TARGET_OS_MAC` is defined as 1: `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 1 && 1 is 1
- If `TARGET_OS_MAC` is undefined: `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 0 && 0 is 0.

`#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` can be reduced to `#if TARGET_OS_MAC`.

The second part `defined(TARGET_OS_OSX) && !TARGET_OS_OSX` can't be reduced and perhaps is a root error here.

**Comment by MarcelRaad** [comment]
According to https://stackoverflow.com/questions/12132933/preprocessor-macro-for-os-x-targets, `TARGET_OS_MAC` is for all Apple platforms, not just macOS. The commit looks like it assumes `TARGET_OS_MAC` being specific to macOS, right?

**Comment by vszakats** [comment]
> Wonder, why you use such construct like `defined(TARGET_OS_MAC) && TARGET_OS_MAC`. See [3.8.1 Conditional inclusion](https://port70.net/~nsz/c/c89/c89-draft.html#3.8.1) - Semantics in C89:
> 
> > <...> then all remaining identifiers are replaced with 0. <...>
> 
> * If `TARGET_OS_MAC` is defined as 0: `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 1 && 0 is 0
> * If `TARGET_OS_MAC` is defined as 1 (not zero): `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 1 && 1 is 1
> * If `TARGET_OS_MAC` is undefined: `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` is 0 && 0 (replaced) is 0.
> 
> `#if defined(TARGET_OS_MAC) && TARGET_OS_MAC` can be reduced to `#if TARGET_OS_MAC`.

Are you saying the logic is wrong, or that it's unnecessarly verbose?

I used to fix compiler warnings when the macro is undefined and checking for its value anyway. Hence this.

> The second part `defined(TARGET_OS_OSX) && !TARGET_OS_OSX` can't be reduced and perhaps is a root error here.

My intent was to set OSX to the MAC value, if OSX was set 0, and MAC was set to non-0.

I assumed (confirmed by testing macOS builds) that MAC is a synonym for OSX. Perhaps this is wrong? llvm 18 source code sets them like this:
```
// Apple (Mac) targets.
TARGET_OS(TARGET_OS_MAC, Triple.isOSDarwin())
TARGET_OS(TARGET_OS_OSX, Triple.isMacOSX())
```

It's both "Mac", but with slight difference in the source of these values.

Can you verify how are the `TARGET_*` macros pre-defined when compiling for iOS?

**Comment by sergio-nsk** [comment]
`#define TARGET_OS_OSX TARGET_OS_MAC` breaks iOS build.

**Comment by vszakats** [comment]
The problem the commit fixes is valid. The SDK is setting these macros wrongly given a combination of pre-defined macros, in llvm's before v18.

The fix is clearly not good in this form by interfering with iOS.

How to fix this, I don't know.

**Comment by vszakats** [comment]
Perhaps checking for non-mac TARGET's being set would fix this, but I have no iOS SDK to test it with, and so far nobody contributed iOS CI tests to test it there.

I'm reluctant to spend more days on this just to endure more bashing, but feel free propose a fix that doesn't break the macOS case while fixing the rest. The 3 weeks spent on macOS and the mess that is Apple and non-Apple compilers, was probably the worse idea to spend my time on in my FLOSS contribution history.

**Comment by sergio-nsk** [comment]
Are you sure it was not an issue in the SDK 14.4 or your local? I don't get errors with the iOS and macOS SDK 14.5 if I revert your changes. This is macOS successful build dump with the reverted commit.
```
-- The CXX compiler identification is Clang 18.1.8
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/opt/llvm/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done

<...>

% cmake --build out/client -t libcurl_static
[29/232] Building C object third_party/zlib-ng/CMakeFiles/zlib.dir/arch/arm/arm_features.c.o
third_party/zlib-ng/arch/arm/arm_features.c:28:25: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
   28 | static int arm_has_crc32() {
      |                         ^
      |                          void
1 warning generated.
[226/232] Building C object third_party/curl/lib/CMakeFiles/libcurl_static.dir/vtls/sectransp.c.o
third_party/curl/lib/vtls/sectransp.c:2626:6: warning: variable 'nread' may be uninitialized when used here [-Wconditional-uninitialized]
 2626 |   if(nread > 0) {
      |      ^~~~~
third_party/curl/lib/vtls/sectransp.c:2577:16: note: initialize the variable 'nread' to silence this warning
 2577 |   ssize_t nread;
      |                ^
      |                 = 0
1 warning generated.
[232/232] Linking C static library Debug/libcurl-d.a
```

**Comment by sergio-nsk** [comment]
Maybe it was similar manipulations with pre-defined macros in your project, and the issue is there and irrelevant to curl, macOS SDK, LLCM-18.

**Comment by vszakats** [comment]
No, it's not a corrupt copy on my local system. I've first seen it in CI, using the SDK and llvm@15 compiler pre-installed on the GHA macos runner image. I've included the link to the CI log line where it happened.

It needs the open-source llvm compiler, any version earlier than v18.

My assessment could be wrong, but the error is not.

**Comment by sergio-nsk** [comment]
Ok, LLVM-15 fails. Then this is LLVM-15 issue and should be solved with `target_compile_definitions()` in CMakeLists if LLVM-15 is detected. Changing OS specific macros in curl is a wrong solution - user code uses `TARGET_OS_OSX 1` if it includes "curl/curl.h" and uses `TARGET_OS_OSX 0` if it does not include "curl/curl.h" - that may result in hard bugs in user projects.

**Comment by vszakats** [comment]
It has nothing to do with CMake. It's also not an llvm@15 issue, but an llvm < 18 issue. The build system cannot set such macro, because it would apply to all targets, not just macOS ones.

It's also not an llvm-15 bug: llvm cannot figure out that N years after its release, Apple decides that it's next SDK release will no longer work correctly unless the standard C compiler pre-defines some newly invented macros.
