### ISSUE TITLE
socket_function callbacks for unrelated sockets that are never removed

### ISSUE THREAD

**Issue by JulesRapanga** [curl/curl#14280]
### I did this

We use libcurl in our software via the multi API driven with libev. After updating from 8.7.1 to 8.9.0 our program would start using 100% cpu after a couple of minutes. On boot we make HTTP requests a several hosts and (when idle) make a single request to one host every minute. It seems that when we make the second request to this host we get callbacks to the function provided to `CURLMOPT_SOCKETFUNCTION` telling us to monitor several sockets that are connected to different hosts. Subsequently `libev` constantly tells us there is activity on these sockets and we call `curl_multi_socket_action` but to no effect or error. After the request finishes we are told to stop monitoring the socket that was actually used for the request but not for the spurious ones, so we continue to spin.

### curl/libcurl version

curl 8.9.0

### operating system

Ubuntu Focal

**Comment by icing** [comment]
This seems a side effect of the connection shutdown changes we made in 8.9. I assume that the shutdown triggers the socket monitoring, but then never causes the sockets to be removed again. Or do you seen "unkown" sockets to appear there?

**Comment by JulesRapanga** [comment]
They're not unknown, they're all ones that have been used for previous requests.

**Comment by JulesRapanga** [comment]
Is there a particular commit I could try backing out to see if that fixes it?

**Comment by icing** [comment]
That would be difficult. It was a larger operation. I'll have a look at it next week, see what I can find. Can you build a libcurl with which we can test changes?

**Comment by JulesRapanga** [comment]
Yeah we can build whatever patches you provide and say what it says

**Comment by CountMurphy** [comment]
Seeing similar behavior when running rtorrent.

**Comment by icing** [comment]
I made #14283 with extra DEBUG output on connection shutdown and its event handling. If you could build a libcurl with `--enable-debug` and set a CURLOPT_DEBUGFUNCTION on the transfers, we should get some traces to show us what is going wrong, hopefully.

**Comment by JulesRapanga** [comment]
@icing 
[libcurl.log](https://github.com/user-attachments/files/16396694/libcurl.log)

The sockets `23, 49, 50, 265, 281` were spuriously passed to the socket callback at `20:45:15`

**Comment by icing** [comment]
Thanks for the log! I see that we are on the right track. The sockets are, correctly, added for shutting down the connections in the multi's connection cache when they are considered to be "too old". But the cache's is never called in invoke the events on these sockets.

I added a fix for that and some additional logging to #14283. Could you run that again in your setup? Thanks!

**Comment by JulesRapanga** [comment]
There was a segfault in the debug (`data->conn` can be `nullptr`) but I dealt with that and the fix seems to have fixed it. CPU is back to normal and no spurious callbacks.

**Comment by icing** [comment]
Thanks for the quick test! I'll work on the real fix next week, now that I know where the deficiencies are.

What fix did you apply?

**Comment by JulesRapanga** [comment]
Just printing None instead of `connection_id` if `data->conn` was NULL

**Comment by icing** [comment]
@JulesRapanga  and others: I propose #14296 as the "real" fix for this issue. It would be great if you could verify this. Thanks!

Note: this will no longer produce the debug output as in the previous PR. I guess we need to add some `CURLMOPT_DEBUGFUNCTION` in the future to add tracing to this.

Also, in addition, this PR will make connection shutdown timeouts happen. So, in case a server is slow responding, you should see the sockets for shutdowns be removed after lastest 2 seconds.

**Comment by JulesRapanga** [comment]
Verified
