### ISSUE TITLE
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012)

### ISSUE THREAD

**Issue by ProgramCX** [curl/curl#14315]
### I did this
- `curl -JO "https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community"`
- I tried to download VS2022 installer using curl.But it reported an error that next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK.
![image](https://github.com/user-attachments/assets/a857b7a9-d520-45e2-b971-a192013201a4)
![image](https://github.com/user-attachments/assets/77ff7e81-3b1c-4263-897b-e7cde659ec44)

**url**
https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community
PS：IDM can download the file,which means there is no problem with the server.

### I expected the following

I hope that it can download the file VisualStudioSetup.exe normally.

### curl/libcurl version

curl 8.9.0 and curl 8.8.0

### operating system

Windows11 24H2

**Comment by bagder** [comment]
Try setting `CURLSSLOPT_NO_REVOKE` in [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) ?

**Comment by bagder** [comment]
oh wait, the command line tool...

**Comment by bagder** [comment]
Try using `--ssl-no-revoke`

**Comment by ProgramCX** [comment]
Ok,I will try it.I found that FastGithub caused the problem.But why did IDM could download the file,but curl couldn't.

**Comment by ProgramCX** [comment]
![image](https://github.com/user-attachments/assets/3342a0e7-0070-4695-a0d3-70328f4ca78a)
It seems that Curl didn't follow the redirection.

**Comment by ProgramCX** [comment]
It happened when FastGithub was running.I will close it and try again.

**Comment by ProgramCX** [comment]
> It happened when FastGithub was running.I will close it and try again.
> ![image](https://private-user-images.githubusercontent.com/124671913/353501226-3342a0e7-0070-4695-a0d3-70328f4ca78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTA1MzUsIm5iZiI6MTcyMjM1MDIzNSwicGF0aCI6Ii8xMjQ2NzE5MTMvMzUzNTAxMjI2LTMzNDJhMGU3LTAwNzAtNDY5NS1hMGQzLTcwMzI4ZjRjYTc4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNDM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzUyNDdlOWY4NDY4Y2NlZWMzYWEyODFmNTU2ZDJlOTEwNmY5NTZlMmEyZTBhNDdhYmEwZWFiZDgzMzI2ZjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.drrV45GOSYDmi8oxK79MRM4-FmbzGw9QHYr920Qbq64) It seems that Curl didn't follow the redirection.

It still happens when FastGithub has been closed.

**Comment by ProgramCX** [comment]
`E:\Desktop>curl -IL "https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community"
HTTP/1.1 302 Found
Cache-Control: private
Content-Length: 176
Content-Type: text/html; charset=utf-8
Location: https://officeredir.microsoft.com/r/rlidO15C2RServiceOutage
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 30 Jul 2024 14:46:17 GMT

HTTP/1.1 301 Moved Permanently
Date: Tue, 30 Jul 2024 14:46:18 GMT
Server: Kestrel
Location: http://offline.officeapps.live.com/outage.html
X-CorrelationId: 0138359c-2437-434b-ba95-87a35a7211a6
X-OfficeFE: ORedirFE_IN_3
X-OfficeVersion: 16.0.17922.30526
X-OfficeCluster: weu-000.ocsredir.officeapps.live.com
X-Backend: DotNetCore

HTTP/1.1 200 OK
Accept-Ranges: bytes
ETag: "2c46b5059d19c33bfc0d5af8dee44452:1391643301"
Last-Modified: Wed, 05 Feb 2014 23:35:01 GMT
Server: AkamaiNetStorage
Content-Length: 2873
Date: Tue, 30 Jul 2024 14:46:19 GMT
Connection: keep-alive
Content-Type: text/html`

**Comment by bagder** [comment]
because it delivers HTML?

**Comment by bagder** [comment]
The command line option worked to work around the revocation error, closing this case.

**Comment by ProgramCX** [comment]
![image](https://github.com/user-attachments/assets/df2ce494-4138-46dd-9aff-f5c66a13fb54)
