### ISSUE TITLE
Error 403 when User-Agent contains Mozilla

### ISSUE THREAD

**Issue by StephaneTinseau** [curl/curl#1431]
Hi All,

When i run this command from windows terminal, using CURL **7.47.1**
```
curl 7.47.1 (x86_64-pc-win32) libcurl/7.47.1 OpenSSL/1.0.2g zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2
```
 or **7.53.1**
```
curl 7.53.1 (i386-pc-win32) libcurl/7.53.1 OpenSSL/1.1.0e zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.21.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy
```

`curl.exe -k -v --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" https://www.fsa.usda.gov/Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt`
*You should change the date in the filename

I received an error 403

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying xxx.xxx.xxx.xxx...
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3427 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [262 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* Server certificate:
*        subject: C=US; ST=District Of Columbia; L=Washington; O=United States Department of Agriculture; CN=www.fsa.usda.gov
*        start date: Feb  8 00:00:00 2017 GMT
*        expire date: Oct 14 23:59:59 2017 GMT
*        issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust SSL CA - G3
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt HTTP/1.1
> Host: www.fsa.usda.gov
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Server: AkamaiGHost
< Mime-Version: 1.0
< Content-Type: text/html
< Content-Length: 335
< Expires: Wed, 19 Apr 2017 12:23:52 GMT
< Date: Wed, 19 Apr 2017 12:23:52 GMT
< Connection: close
< Strict-Transport-Security: max-age=31536000; preload
<
{ [335 bytes data]
100   335  100   335    0     0   1024      0 --:--:-- --:--:-- --:--:--  1024
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
11

```

This request work well with CURL **7.40**.
```
curl 7.40.0 (x86_64-pc-win32) libcurl/7.40.0 OpenSSL/1.0.1g zlib/1.2.8 WinIDN libssh2/1.4.3_DEV
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
```

These tests have been done on Windows 10 and Windows 7, with and without proxy.

During our tests, we have found 2 workarounds.

1- Change the User-Agent and not use the word mozilla.
`curl.exe -k -v --user-agent "Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14" https://www.fsa.usda.gov/Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt`

2- force the header to remove Accept parameter
`curl.exe -k -v --header "Accept:" --user-agent "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" https://www.fsa.usda.gov/Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt`

These two case work well with all versions.
Could you please check why we need to use one of these workaround ?

Thanks
Regards

**Comment by bagder** [comment]
The decision to respond with a 403 in these cases is entirely up to the server. It seems to have decided that those `Accept:` headers and `User-Agent:` header content are bad so it responds with a 403 for such requests. There's nothing curl can do about that. This is not a client issue. I suggest you contact the server admins and ask them about this.

**Comment by StephaneTinseau** [comment]
I understand that the response is on server side, but how to explain that it's working on CURL 7.40 ?
It's working also with the browser with the same User-Agent.

**Comment by bagder** [comment]
Since the decision to respond with a 403 or not is made on the server side, the explanation to why one works and another one doesn't is in the hands of the server - we can only guess and try to draw conclusion based on trial and error. If you use the latest curl and make it send the request to look exactly like it did with 7.40.x, chances are it'll work.

**Comment by mathieu-tr** [comment]
Hi,

I am facing the same issue.

Download is working with libcurl 7.38 while it's failing with any upper version.
I tried with the last release 7.54 which is failing also.

Any way to get some people investigating on changes that could be the root cause within libcurl ?

Thanks and regards

**Comment by bagder** [comment]
@mathieu-tr: I maintain that this is caused by the server, not the client. Possibly it is triggered by some specific header content that curl sends, but clearly this is the server that decides to reject some (otherwise fully legal and fine) requests.

**Comment by jay** [comment]
I tried this out today, it's the header order. Newer versions of curl put `Host` before `User-Agent` and AkamaiGhost does not like that.

older (reply 200):
~~~
GET /Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: www.fsa.usda.gov
Accept: */*
~~~

newer (reply 403):
~~~
GET /Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt HTTP/1.1
Host: www.fsa.usda.gov
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept: */*
~~~

newer but the hosts header is bumped to the end by removing and adding it back (`-H "Host:" -H "Host: www.fsa.usda.gov"`) (reply 200):
~~~
GET /Internet/FSA_DACO_ComOps_Rpts/mkt170419.txt HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept: */*
Host: www.fsa.usda.gov
~~~

So it needs the user agent before the host header for some reason? Maybe it's caching based on agent. [RFC7230 header order](https://tools.ietf.org/html/rfc7230#section-3.2.2) says in part:

> The order in which header fields with differing field names are received is not significant.  However, it is good practice to send header fields that contain control data first, **such as Host on requests** and Date on responses, so that implementations can decide when not to handle a message as early as possible.

I don't see anything about user agent, though I imagine it could be considered of similar priority. I think we should kick this to Akamai.

**Comment by mathieu-tr** [comment]
Thanks Jay for this constructive and demonstrative answer.
Any idea about a timeframe to get a fix ?

**Comment by bagder** [comment]
Commit a5d994941c2b19a (March 2015) changed the header order to conform to the RFC 7230 language. The bug report was here: https://sourceforge.net/p/curl/bugs/1491/

> Any idea about a timeframe to get a fix ?

This isn't really a curl bug so its hard to say what a fix from our end would be. Reverting this change would fix this particular case for you but there's a risk that it breaks something else. As @jay just wrote: the server is wrong here and is the one to blame...

**Comment by jay** [comment]
I opened a case with akamai e-mail support, F-CS-2188755, I'll let you know what happens.

**Comment by bagder** [comment]
A friend at Akamai checked this out (independently of the mentioned email), but sadly the only response he could provide was:

> Not a server issue. Unfortunately, I cannot comment any further on customer configuration.

**Comment by jay** [comment]
Akamai told me about the same thing, they implied it's a configuration issue and they can't discuss it. I forwarded their reply to USDA web operations. I'll update the thread with any replies.
