### ISSUE TITLE
curl_multi_socket_action -> data->conn is NULL

### ISSUE THREAD

**Issue by wookietreiber** [curl/curl#14325]
### I did this

See [original issue with mpdscribble](https://github.com/MusicPlayerDaemon/mpdscribble/issues/60) especially [this post](https://github.com/MusicPlayerDaemon/mpdscribble/issues/60#issuecomment-2260188703) hinting at an issue here.

### I expected the following

:shrug: 

### curl/libcurl version

curl 8.9.0 (x86_64-pc-linux-gnu) libcurl/8.9.0 OpenSSL/3.3.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.62.1 nghttp3/1.4.0
Release-Date: 2024-07-24
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Archlinux / Linux aimob 6.10.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000 x86_64 GNU/Linux

**Comment by wookietreiber** [comment]
**Note:** Since I'm opening this in response to https://github.com/MusicPlayerDaemon/mpdscribble/issues/60#issuecomment-2260188703 feel free to modify title and description, because I didn't write the mpdscribble code and haven't used libcurl myself.

**Comment by icing** [comment]
This seems to be the bug we fixed in curl 8.9.1, released today. See https://github.com/curl/curl/issues/14280.

**Comment by wookietreiber** [comment]
> This seems to be the bug we fixed in curl 8.9.1, released today. See #14280.

Sounds great, waiting for Archlinux to bump curl ...

**Comment by wookietreiber** [comment]
Already out in testing, seems to have fixed it.
