### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK(60)

### ISSUE THREAD

**Issue by anil9811** [curl/curl#14334]
### I did this

We are using curl setoptions for transfering file in secure mode, To enable secure mode we used sslverifypeer setpotions and set to 1 . Used proper CA certs and private certs for managing secure connection which is generated on openssl commands. File transfer is failing with error  curlError: SSL peer certificate or SSH remote key was not OK(60). Could you please help to check?

### curl/libcurl version

curl 8.8.0

### operating system

RedHat Enterprise Linux 9

**Comment by bagder** [comment]
Please tell us how to reproduce the problem. It sounds like your CA cert bundle is not good enough.

**Comment by anil9811** [comment]
We have our own software. Is it possible to connect and  reproduce the issue ?

**Comment by bagder** [comment]
if curl returns CURLE_PEER_FAILED_VERIFICATION there is something wrong in the server cert. It is either a problem with the name or the server certificate (or an intermediate cert) was not signed by a CA present in the CA store. Since we don't know your server, your host name, your cert or your CA store, I cannot think of anything more we can do for you here.

**Comment by anil9811** [comment]
Manually if we perform file download operation with curl command using server certs the file download operation is success but in the code execution it return failed. Not clear how you justify it is a Server cert issue . If server cert is having problem then it should not work in command execution in console as well.

**Comment by bagder** [comment]
> if we perform file download operation with curl command using server certs the file download operation is success but in the code execution it return failed

Do both setups use the same URL , same CA bundle against the same server? If not, how do they differ?

> If server cert is having problem then it should not work in command execution in console as well.

You tell me. Are all the circumstances identical in both cases? Then yes, both should work the same.

But again: you are only giving me small snippets of information about this and I do the best I can accordingly. I cannot fix this issue for you.

**Comment by anil9811** [comment]
> > if we perform file download operation with curl command using server certs the file download operation is success but in the code execution it return failed
> 
> Do both setups use the same URL , same CA bundle against the same server? If not, how do they differ?
> Yes, URL is same in both setups and same CA bundle against the same server.


> > If server cert is having problem then it should not work in command execution in console as well.
> 
> You tell me. Are all the circumstances identical in both cases? Then yes, both should work the same.
> 
> But again: you are only giving me small snippets of information about this and I do the best I can accordingly. I cannot fix this issue for you.



> > if we perform file download operation with curl command using server certs the file download operation is success but in the code execution it return failed
> 
> Do both setups use the same URL , same CA bundle against the same server? If not, how do they differ?
> 
> > If server cert is having problem then it should not work in command execution in console as well.
> 
> You tell me. Are all the circumstances identical in both cases? Then yes, both should work the same.
> 
> But again: you are only giving me small snippets of information about this and I do the best I can accordingly. I cannot fix this issue for you.

**Comment by anil9811** [comment]
Yes, URL is same in both setups and same CA bundle against the same server.

Attaching the sample code with certs used which is working but when we use same code in our product we see below issue. Could you please help to check this further?

 **file transfer failed: https://10.68.xxx.xx:29242/data/topology/RNC-1_RNWPLANU.XML.gz -> /var/opt/OMSftproot/pddb_files_tmp/1RNC-1_RNWPLANU.XML.gz, responseCode=0, curlError: SSL peer certificate or SSH remote key was not OK(60) pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040**

[samplecodewithcerts.zip](https://github.com/user-attachments/files/16496120/samplecodewithcerts.zip)

**Comment by bagder** [comment]
That URL uses a (private) IP address. Are you saying that you have an actual and real certificate setup for that IP address? A server certificate for an IP address is possible but extremely unusual.

> Can we have teams meeting if possible so that we can show the issue in the setup and discuss further?

For free support it is better if we keep the discussion here so that more people can be involved and learn.

**Comment by anil9811** [comment]
> That URL uses a (private) IP address. Are you saying that you have an actual and real certificate setup for that IP address? A server certificate for an IP address is possible but extremely unusual.
> No, Private IP  mentioned in the URL is simulator where our product is downloading the file by using secure HTTPS over TLSv1.3 . During file download curl reports the certificate NOT OK error. Attaching complete curl debug log. Could you Please help to check further?


Mon Aug  5 22:23:50 2024 #0000078336 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: TEXT  Data: TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
 pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078337 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078338 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078339 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_IN  Data: ^D pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078340 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078341 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078342 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_OUT  Data: ^W^C^C pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078343 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078344 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078345 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_OUT  Data: ^U pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078346 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078347 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078348 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: TEXT  Data: TLSv1.3 (OUT), TLS alert, close notify (256):
 pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078349 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078350 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078351 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_OUT  Data: ^A pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078352 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078353 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078354 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_IN  Data: ^W^C^C pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078355 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078356 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078357 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_IN  Data: ^V pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078358 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078359 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078360 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: TEXT  Data: TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
 pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078361 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
FunctionCallback [line 291] Header: TEXT  Data: TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
 pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078361 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078362 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078363 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: SSL_DATA_IN  Data: ^D pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078364 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078365 OMS::TRACE DEBUG <NemuFTP.cpp:233> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   ENTER pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078366 OMS::TRACE DEBUG <NemuFTP.cpp:291> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback [line 291] Header: TEXT  Data: old SSL session ID is stale, removing
 pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078367 OMS::TRACE DEBUG <NemuFTP.cpp:301> CLA-0 CurlDebugFunctionCallback: CNemuFTP::CurlDebugFunctionCallback   EXIT pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078368 OMS::TRACE DEBUG <NemuFTP.cpp:1649> CLA-0 GetFile: CNemuFTP::GetFile perform end pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040
Mon Aug  5 22:23:50 2024 #0000078369 OMS::TRACE DEBUG <NemuFTP.cpp:1773> CLA-0 GetFile: CNemuFTP::GetFile: file transfer failed: https://10.68.196.88:29511/data/topology/RNC-1UploadTopology.xml -> /var/opt/OMSftproot/topology_upload_files//1RNC-1UploadTopology.xml, responseCode=0, curlError: SSL peer certificate or SSH remote key was not OK(60) pgrp=6326 pid=6326 tid=140277817759296 uid=9012 gid=5040

**Comment by bagder** [comment]
> No, Private IP mentioned in the URL is simulator where our product is downloading the file by using secure HTTPS over TLSv1.3 .

I don't understand. The outputs you have shown here in this issue include a URL that definitely is using an IP address and then the certificate check fails. Carrying all the signs of the certificate not being done for the IP address used in the URL.

**Comment by anil9811** [comment]
Can you please share what you didn't understand about the issue so that I can clarify more in detail.

**Comment by bagder** [comment]
Why does your code and your logs show an IP address as a URL if you are using a hostname?

**Comment by anil9811** [comment]
We don't have hostname. It is a IP to IP address communication using certificates which are mentioned already in the attachment earlier.

**Comment by anil9811** [comment]
Can we have short call to explain you in detail about the product and issue. After discussion, we can explain conclusion here so others learn and understand.

**Comment by anil9811** [comment]
There is no difference in setopts as well same has been used in the product application as we done in the sample application but curl behaviour is different. 

Created a wolf ticket. can we have meeting link ?

https://wolfssl.zendesk.com/hc/en-us/requests/18421

**Comment by anil9811** [comment]
Is curl of version (8.71.1 or above) is tested with openssl3.0? How about the test result?

**Comment by bagder** [comment]
curl has worked fine with all versions of OpenSSL ever released. It works excellently with OpenSSL 3.

**Comment by bagder** [comment]
Nothing to act on here. I don't think this is a problem in curl.

**Comment by ah123666** [comment]
May I ask how this problem was ultimately resolved? We also have the same issue: only when using libcurl to call the download interface, the above problem occurs, while other interfaces work normally
