### ISSUE TITLE
OOM error on large JSON files

### ISSUE THREAD

**Issue by aduh95** [curl/curl#14337]
### I did this

```sh
curl --config - <<'EOF'
request = "POST"
fail-with-body
verbose
show-error
url = "http://172.16.22.1:12507/"
header = "Expect:"
insecure
max-time = "300"
data-urlencode = "transloadit@/path/to/data.json"
globoff
create-dirs
max-redirs = "5"
max-filesize = "128849018880"
EOF
```

I'd rather not share `data.json`, but I can disclose it's a 16M JSON file.

### I expected the following

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 172.16.22.1:12507...
```

Instead got `curl: <stdin>:9: 'data-urlencode' out of memory`

### curl/libcurl version

git bisect pointed me to https://github.com/curl/curl/commit/f37840a46e5eddaf109c16fa783c8dd8ef639271. I can confirm that reverting this commit does solve the issue for me.

### operating system

Reproduced with macOS 14.5 and Linux 6.8.0

**Comment by bagder** [comment]
Hm, right. It stops at 8MB now...

**Comment by bagder** [comment]
I'll fix
