### ISSUE TITLE
curl -- --connect-timeout : Its order seems to be mandatory

### ISSUE THREAD

**Issue by asifansari80** [curl/curl#14342]
### I did this

Curl taking --connect-timeout 5 as 0.0.0.5 to connect to,

```
/bin/curl -s --noproxy **--connect-timeout 5** --header "Content-Type: application/xml" --request POST --data '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.subscribermodel.tpapps.nokia.com/"><soapenv:Header/><soapenv:Body><ws:read><deviceId>D002</deviceId></ws:read></soapenv:Body></soapenv:Envelope>' https://localhost:8443/soap/device -v -k
* About to connect() to 5 port 80 (#0)
*   Trying 0.0.0.5...
* Failed to connect to 0.0.0.5: Invalid argument
* couldn't connect to host at 5:80
* Closing connection 0
* About to connect() to localhost port 8443 (#1)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#1)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
```

curl need --connect-timeout as the first argument.
Ideally, the order should not significant here.

```
/bin/curl --connect-timeout 5 -s --noproxy --header "Content-Type: application/xml" --request POST --data '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.subscribermodel.tpapps.nokia.com/"><soapenv:Header/><soapenv:Body><ws:read><deviceId>D002</deviceId></ws:read></soapenv:Body></soapenv:Envelope>' https://localhost:8443/soap/device -v -k
* Could not resolve host: Content-Type; Name or service not known
* Closing connection 0
* About to connect() to localhost port 8443 (#1)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#1)
```

### I expected the following

The order should not be significant here. At any place --connect-timeout is placed, it should work.

### curl/libcurl version

curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.90 zlib/1.2.7 libidn/1.28 libssh2/1.8.0

### operating system

Linux asif-me 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
`--noproxy` takes an argument that you don't provide so it takes the next option as its argument.

This command:

`curl -s --noproxy --connect-timeout 5`

This makes it set `--connect-timeout` as our noproxy pattern and then the remaining `5` is treated as an URL. A URL without a scheme and `5` is actually a valid IPv4 numeral address, treated as 0.0.0.5. So that's where curl tries to connect.

**Comment by asifansari80** [comment]
Thanks a lot. Its clear now.
