### ISSUE TITLE
test/data/Makefile.inc moved but still used

### ISSUE THREAD

**Issue by icing** [curl/curl#14371]
### I did this

run the curl tests, get error messages like:

```
Warning: test1023 not present in tests/data/Makefile.inc
Warning: test1024 not present in tests/data/Makefile.inc
Warning: test1025 not present in tests/data/Makefile.inc
Warning: test1026 not present in tests/data/Makefile.inc
Warning: test1027 not present in tests/data/Makefile.inc
```

Also there are places in the documentation that refer to `Makefile.inc`.

### I expected the following

The move seems incomplete.

### curl/libcurl version

curl 8.10.0-DEV (x86_64-apple-darwin23.5.0) libcurl/8.10.0-DEV GnuTLS/3.8.5 zlib/1.2.12 brotli/1.1.0 zstd/1.5.6 c-ares/1.28.1 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.62.1 ngtcp2/1.6.0 nghttp3/1.4.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli Debug GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system

Darwin xxx 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64

**Comment by vszakats** [comment]
Thanks @icing, opened #14372.
