### ISSUE TITLE
curl doesn't like "✌️.lord.geek.nz"

### ISSUE THREAD

**Issue by d-lord** [curl/curl#1441]
Hey, not an expert in this but this seems like odd behaviour.
I've set up a punycode DNS entry for `✌️.lord.geek.nz`, and redirection from http to https. Curl will correctly resolve and retrieve that subdomain, for queries resulting in 200 and 301 responses.
However, if you use `--location`/`-L` and receive a 301 response, it doesn't resolve the new domain properly.

### I did this
`curl -v xn--7bi.lord.geek.nz` -- correctly displays a 301 to `https://✌️.lord.geek.nz`
`curl -v https://xn--7bi.lord.geek.nz` -- correctly displays the 200 & resulting page (some HTML)

This is the error case:
`curl -v -L xn--7bi.lord.geek.nz` -- doesn't translate properly from UTF-8: 
```curl: (6) Could not resolve host: %e2%9c%8c%ef%b8%8f.lord.geek.nz```

macOS' character info says that the character is formed of two code points:
Unicode: U+270C U+FE0F, or UTF-8: E2 9C 8C EF B8 8F

Note that curl's error output references the UTF-8 form.

### I expected the following
curl would follow the redirect to `https://✌️.lord.geek.nz` and resolve it to `https://xn--7bi.lord.geek.nz`, producing the 200 & resulting HTML.
The output should be identical to `curl https://✌️.lord.geek.nz`.

### Other

Curl also considers the certificate invalid (ie doesn't compare `✌️` to the `xn--7bi` SNI), but it does explicitly warn about this.

```
curl -v https://✌️.lord.geek.nz
* Rebuilt URL to: https://✌️.lord.geek.nz/
* IDN support not present, can't parse Unicode domains
*   Trying 103.16.129.109...
* TCP_NODELAY set
* Connected to ✌️.lord.geek.nz (103.16.129.109) port 443 (#0)
* SSL certificate problem: Invalid certificate chain
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
```

### curl/libcurl version

```
curl -V
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

### operating system
macOS 10.12.4

**Comment by bagder** [comment]
First, your **Features:** doesn't doesn't include `IDN` which says your curl can't talk Internation Domain Names at all. You need to build curl with libidn2 for that.

But then, even if built with libidn2, this URL doesn't work because libidn2 refuses to consider it ok: `Failed to convert ✌️.lord.geek.nz to ACE; string contains a disallowed character`, at [this point](https://github.com/curl/curl/blob/master/lib/url.c#L4061) in the code.

I don't know why libidn2 consider it disallowed. This IDN URL works in current Firefox, which presumably also speaks IDNA2008.

**Comment by d-lord** [comment]
Ah, of course. Sorry for not checking for `IDN`.

I checked out libidn2 and read `idn2_lookup_u8` (called by `idn2_lookup_ul` as used in curl.c), didn't find anything explicit. It may be something to do with the glyph using [VARIANT-16](http://www.fileformat.info/info/unicode/char/fe0f/index.htm) to denote the emoji variant when Chrome strips out that code point (showing only the text variant), but I'm having enough trouble building libidn2 that I'm not likely to investigate further.

It's a really minor problem from a user perspective.

PS - thanks for maintaining such a useful project!

**Comment by bagder** [comment]
I filed an [issue in the libidn2 project](https://gitlab.com/libidn/libidn2/issues/25) hoping they can help shed some light on this.

**Comment by bagder** [comment]
This code point only works with IDNA2008 **transitional**, and libcurl only does **non-transitional** right now. It turns out the browsers mostly do IDNA2008 transitional so therefore this works there. An approach forward is to make libcurl first *try* non-transitional and if that fails with a `IDN2_DISALLOWED` return code, we attempt the same thing transitional.

However...

There was a bug in libidn2 that made it also fail on this code point for transitional, and that is [fixed now](https://gitlab.com/libidn/libidn2/commit/8d8e76eee1f00988244b848730041f0a23dcedcb) after my report but still of course requires that for the work-around above to work at all, a fixed libidn2 is needed and there hasn't been any fixed version released yet...

**Comment by gvanem** [comment]
BTW, it's possible to *accidentally* build libcurl with 2 IDN libraries:
```
curl 7.54.1-DEV (i386-pc-win32) libcurl/7.54.1-DEV OpenSSL/1.1.1 zlib/1.2.8 libidn2/2.0.0 WinIDN ...
...
Features: ... IDN
```
It's not clear which gets used at runtime. But from `url.c` is seems `LIBIDN2` is the winner.
Should not be possible IMHO. Just my 2 €.

**Comment by jay** [comment]
> BTW, it's possible to accidentally build libcurl with 2 IDN libraries:

hm I'm not sure if there's a reason for that but I can't find one. How about if WinIDN is detected don't use libidn?

~~~diff
diff --git a/lib/curl_setup.h b/lib/curl_setup.h
index dda1c75..46bdbca 100644
--- a/lib/curl_setup.h
+++ b/lib/curl_setup.h
@@ -588,7 +588,7 @@ int netware_init(void);
 #endif
 #endif
 
-#if defined(HAVE_LIBIDN2) && defined(HAVE_IDN2_H)
+#if defined(HAVE_LIBIDN2) && defined(HAVE_IDN2_H) && !defined(USE_WIN32_IDN)
 /* The lib and header are present */
 #define USE_LIBIDN2
 #endif
~~~

**Comment by bagder** [comment]
WinIDN instead of libidn2 there sounds reasonable to me...

**Comment by jay** [comment]
I think it's possible for USE_LIBIDN2 to already be enabled at that point so here's draft2:
~~~diff
diff --git a/lib/curl_setup.h b/lib/curl_setup.h
index dda1c75..88e89c1 100644
--- a/lib/curl_setup.h
+++ b/lib/curl_setup.h
@@ -593,6 +593,10 @@ int netware_init(void);
 #define USE_LIBIDN2
 #endif
 
+#if defined(USE_LIBIDN2) && defined(USE_WIN32_IDN)
+#error "Both libidn2 and WinIDN were enabled, choose one."
+#endif
+
 #ifndef SIZEOF_TIME_T
 /* assume default size of time_t to be 32 bit */
 #define SIZEOF_TIME_T 4
~~~
Also I notice the .m32 makefiles still define USE_LIBIDN instead of USE_LIBIDN2. I can submit a PR for that.

**Comment by jeroen** [comment]
FWIW I have libcurl v7.54.1 with winidn and the retrieving ` https://✌️.lord.geek.nz` works, however retrieving ` http://✌️.lord.geek.nz` works until the redirect but then errors because the `Location` url does not seem to get punycoded:

```
> curl::curl_fetch_memory(lords, handle = new_handle(verbose=T))
* Rebuilt URL to: http://✌️.lord.geek.nz/
* Found bundle for host xn--7bi.lord.geek.nz: 0x1f6ce350 [can pipeline]
* Re-using existing connection! (#6) with host ✌️.lord.geek.nz
* Connected to ✌️.lord.geek.nz (103.16.129.109) port 80 (#6)
> GET / HTTP/1.1
Host: xn--7bi.lord.geek.nz
User-Agent: R (3.4.1 i386-w64-mingw32 i386 mingw32)
Accept: */*
Accept-Encoding: gzip, deflate

< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.10.2
< Date: Sun, 09 Jul 2017 11:14:54 GMT
< Content-Type: text/html
< Content-Length: 185
< Connection: keep-alive
< Location: https://✌️.lord.geek.nz
< 
* Ignoring the response-body
* Connection #6 to host ✌️.lord.geek.nz left intact
* Issue another request to this URL: 'https://%e2%9c%8c%ef%b8%8f.lord.geek.nz'
* Rebuilt URL to: https://%e2%9c%8c%ef%b8%8f.lord.geek.nz/
* timeout on name lookup is not supported
* getaddrinfo(3) failed for %e2%9c%8c%ef%b8%8f.lord.geek.nz:443
* Couldn't resolve host '%e2%9c%8c%ef%b8%8f.lord.geek.nz'
* Closing connection 8
Error in curl::curl_fetch_memory(lords, handle = new_handle(verbose = T)) : 
  Couldn't resolve host '%e2%9c%8c%ef%b8%8f.lord.geek.nz'
```

**Comment by salshaaban** [comment]
The issue referred to by @jeroen is caused by the call to strcpy_url() in [Curl_follow()](https://github.com/curl/curl/blob/d6c8def82a2cfc0d177acc81e4244221d4e98f2f/lib/transfer.c#L1705).

strcpy_url() should be modified to copy the domain name as is, then start doing conversions, right?

**Comment by bagder** [comment]
> strcpy_url() should be modified to copy the domain name as is, then start doing conversions, right?

Pretty much, sure. Or put another way: the IDNification needs to be done on URLs even when doing redirects. URLs are finicky business.

**Comment by salshaaban** [comment]
> Pretty much, sure. Or put another way: the IDNification needs to be done on URLs even when doing redirects. URLs are finicky business.


Indeed they are :smile:
OK, I will give this a shot.

**Comment by bagder** [comment]
Sorry, the redirect bug is fixed but the main bug this issue is about is not fixed I believe. Unless perhaps a later libidn2 version helps?

**Comment by salshaaban** [comment]
> Sorry, the redirect bug is fixed but the main bug this issue is about is not fixed I believe. Unless perhaps a later libidn2 version helps?

Yes, with WinIDN everything should be fine now.
With libidn2 I think we should do what you suggested earlier, try non-transitional first then transitional if that fails. This works with the git version of libidn2, and it should work too with the latest 2.0.3.

**Comment by salshaaban** [comment]
```diff
diff --git a/lib/url.c b/lib/url.c
index 71d4d8bb7..a1ad5279d 100644
--- a/lib/url.c
+++ b/lib/url.c
@@ -4100,15 +4100,20 @@ static void fix_hostname(struct connectdata *conn, struct hostname *host)
 #ifdef USE_LIBIDN2
     if(idn2_check_version(IDN2_VERSION)) {
       char *ace_hostname = NULL;
+      int rc;
 #if IDN2_VERSION_NUMBER >= 0x00140000
       /* IDN2_NFC_INPUT: Normalize input string using normalization form C.
          IDN2_NONTRANSITIONAL: Perform Unicode TR46 non-transitional
          processing. */
-      int flags = IDN2_NFC_INPUT | IDN2_NONTRANSITIONAL;
+      rc = idn2_lookup_ul((const char *)host->name, &ace_hostname,
+                          IDN2_NFC_INPUT | IDN2_NONTRANSITIONAL);
+      if(rc == IDN2_DISALLOWED)
+        rc = idn2_lookup_ul((const char *)host->name, &ace_hostname,
+                            IDN2_NFC_INPUT | IDN2_TRANSITIONAL);
 #else
-      int flags = IDN2_NFC_INPUT;
+      rc = idn2_lookup_ul((const char *)host->name, &ace_hostname,
+                          IDN2_NFC_INPUT);
 #endif
-      int rc = idn2_lookup_ul((const char *)host->name, &ace_hostname, flags);
       if(rc == IDN2_OK) {
         host->encalloc = (char *)ace_hostname;
         /* change the name pointer to point to the encoded hostname */
```

I have tested this with version 2.0.3 of libidn2 and it's working fine.
Is this good enough for a PR? Do I have to add a separate test or anything else?

**Comment by bagder** [comment]
> Is this good enough for a PR

Yes!

> Do I have to add a separate test or anything else?

I don't think you *have to*, but it would be awesome to get one that verifies that this approach works and that we won't mess it up in the future. Test 165, 1034, 1035 and 2046 might work as good inspiration on how a HTTP IDN test can be written.

**Comment by salshaaban** [comment]
The thing is, the test in this case should target codepoints like '✌' which are disallowed in IDNA2008 but valid in transitional mode.

As far as I understand all such codepoints are affected by the libidn2 bug you helped fix. This means that if we add such a test we will have to require the latest version of libidn2 in the configure script, right?

And that will break a lot of builds, including maybe the CI.

TBH such changes scare me lol.
