### ISSUE TITLE
FTP Perf: CWD is sent despite CURLOPT_QUOTE/CURLOPT_NOBODY

### ISSUE THREAD

**Issue by Zenju** [curl/curl#1443]
The issue affects 7.54:

When sending a single FTP command to the server (e.g. FEAT) using 
CURLOPT_QUOTE + CURLOPT_NOBODY, libcurl unnecessarily sends CWD even though the Quote was processed successfully and there is no actual data to download (due to CURLOPT_NOBODY).
The CWD is an unnecessary round-trip: Can this CWD be avoided in case of CURLOPT_NOBODY or maybe libcurl needs an option to suppress CWD for pure Quote commands?

**Comment by Zenju** [comment]
Just tested CURLOPT_FTP_FILEMETHOD +  CURLFTPMETHOD_NOCWD, but strangely "CWD /" is still being logged by CURLOPT_DEBUGFUNCTION... Not sure if this is a bug.

**Comment by bagder** [comment]
I'd say it would be a bit of a gamble to remove it. There's also `CURLOPT_POSTQUOTE` for example, and people may very well have used that with the assumption that libcurl has changed to the correct directory at the time those commands are executed...

**Comment by bagder** [comment]
Seems to have stalled, and as this isn't really a bug but mostly a possible optimization I'm going to leave it as-is.
