### ISSUE TITLE
getenv() used instead of curl_getenv()

### ISSUE THREAD

**Issue by ralfjunker** [curl/curl#14448]
### I did this

I see this:

https://github.com/curl/curl/blob/3ac1569c166de9156f7508db0cba8685456e6682/lib/vquic/vquic.c#L644

### I expected the following

```C
const char *qlog_dir = curl_getenv("QLOGDIR");
```

Rationale: `getenv()` is only used in debugging sections (see same file [here](https://github.com/curl/curl/blob/3ac1569c166de9156f7508db0cba8685456e6682/lib/vquic/vquic.c#L99-L108)) all other calls use `curl_getenv()`.

### curl/libcurl version

GIT master branch head.

### operating system

All.

**Comment by bagder** [comment]
But is this really a problem?

**Comment by ralfjunker** [comment]
Yes, according to this comment:

https://github.com/curl/curl/blob/3ac1569c166de9156f7508db0cba8685456e6682/lib/getenv.c#L39-L40

**Comment by bagder** [comment]
(FTR: I both added this code in vquic.c and I wrote the comment in getenv.c)

`QLOGDIR` is a modern invention, I doubt there are many Windows users trying the Windows-specific %-variables in it, not to mention that QLOGDIR is an env variable used by other QUIC tools and I doubt they do this Windows adjustment.

I therefore deem this use of `getenv()` fine. It saves us a malloc + free.
