### ISSUE TITLE
`--cookie` ignores `Secure` attribute when value is provided inline instead of filepath reference

### ISSUE THREAD

**Issue by polarathene** [curl/curl#14489]
### I did this

```bash
# Sends cookie HTTP (bad):
curl --url http://insecure.example.test --cookie 'session={"key":"value"}; Secure; HttpOnly; Path=/'

# Content of /tmp/cookies for cookie-jar below:
# #HttpOnly_insecure.example.test     FALSE   /       TRUE    0       session    %7B%22key%22%3A%22value%22%7D

# Ignores cookie for HTTP (good):
curl --url http://insecure.example.test --cookie /tmp/cookies.txt --cookie-jar /tmp/cookies.txt
# Sends cookie for HTTPS (good):
curl --url https://insecure.example.test --cookie /tmp/cookies.txt --cookie-jar /tmp/cookies.txt
```

### I expected the following

Since the scheme is HTTP and the cookie has `Secure` attribute set, it should not have sent the cookie.

For context, the URL points to `172.16.42.2`. I'm aware of the `localhost` treatment (_not sure if that applies to `insecure.example.localhost`, but I assume it's whatever resolves to `127.0.0.1` / `[::1]`_), hence the alternative (_DNS and private network subnet managed by Docker_).

If I use `--cookie path/to/file` (_optionally with `--cookie-jar path/to/file`_), the request behaves correctly omitting the `Set-Cookie` header (_while connecting over `https://` instead does set the header as expected_).

I am under the impression that the behaviour here should be the same, regardless of inline cookie value or file input?

### curl/libcurl version

```
curl 8.9.0 (x86_64-alpine-linux-musl) libcurl/8.9.0 OpenSSL/3.1.4 zlib/1.3.1 brotli/1.1.0 c-ares/1.27.0 libidn2/2.3.4 nghttp2/1.58.0
Release-Date: 2024-07-24
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
```

```
curl 8.6.0 (x86_64-redhat-linux-gnu) libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.3.0.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.10.6/openssl/zlib nghttp2/1.59.0 OpenLDAP/2.6.7
Release-Date: 2024-01-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets
```

### operating system

```
Linux 9a0dc992b3f1 5.15.123.1-microsoft-standard-WSL2 #1 SMP Mon Aug 7 19:01:48 UTC 2023 x86_64 Linux
```

`curl` was however run via Alpine and Fedora containers.

**Comment by bagder** [comment]
That's simply not how `--cookie` works and I don't think there is any documentation that says so.

The "fixed" cookie you set with `--cookie` is for **outgoing** requests. You set exactly what curl should send. If you tell it to send `key=value; Secure;`,  that is exactly what it sends in the cookie header:

    Cookie: key=value; Secure;

**Comment by polarathene** [comment]
> That's simply not how `--cookie` works and I don't think there is any documentation that says so.

Apologies, I think I made a mistake when attempting to make the value generic for the report. I've corrected that along with additional context.

At [these docs](https://curl.se/docs/http-cookies.html):

> ![image](https://github.com/user-attachments/assets/8272a1cf-de5c-43b1-a90d-d1e4752440f6)

To clarify the issue (_or my misunderstanding_), `--cookie` is behaving differently with `Secure` set via how the value is provided to `--cookie`.

- As a raw value the service receives it and reads that cookie content provided. Other clients are not receiving the cookie unless I explicitly remove the `Secure` attribute.
- When `curl` instead uses `--cookie` to load the content from the service written in a prior request via `--cookie-jar`, it correctly prevents sending the `Secure` cookie.

Have I misunderstood something here?

**Comment by bagder** [comment]
`--cookie` has a slightly weird functionality as it has a double purpose:

1. Load a cookie jar into memory and then use that
2. Specify an exact cookie "string", a set of cookies, to send in the outgoing request

In the first case, the read cookies are managed and subsequently sent (or not) according to the cookie rules, hostname and path matching etc. That includes respect for cookies that has been stored in the jar as `Secure`.

The second case has no way for `Secure` to be applied. It is assumed that you *know* what to send in the request and therefore you tell curl exactly what to send. You decide if a previous `Secure` should be applied or not. Sending whatever you want is a blunt tool when you really want to make sure to send a specific cookie, no matter what the cookie rules would otherwise say etc. Not that there is no *Secure* keyword in outgoing cookies from a client, so passing that is just going to be weird.

**Comment by polarathene** [comment]
> `--cookie` has a slightly weird functionality as it has a double purpose

Ok, so that was unexpected with typical CLI UX. I am familiar with detecting file paths to load a value instead, but did not expect the actual behaviour to change with how the cookie would be processed.

The docs as shown above don't communicate that difference which didn't help either (_perhaps it attempted to by referring to the "cookie engine"?_).

At first I thought `--cookie-jar` was an alternative to persist a session, but quickly realized it was write-only (_I had not looked up curls official docs at the time_), then learned about `--cookie` taking the same file path to get that session store behaviour, but was surprised by the different behaviour (_working as I originally expected `--cookie` to_). Thus it seemed like a bug to me, otherwise I might as well just use `-H 'Set-Cookie ...'`? I figured `--cookie` was the way to get that parsed as a conditional header, but thanks for clarifying that is only the case if sourcing from a file 👍 

---

That also explains what I observed with `--cookie-jar /tmp/cookies.txt` below:

```bash
# POST request to ensure session inserts the initial key/value, response is secure cookie that is stored in jar:
curl --url http://insecure.example.test --cookie /tmp/cookies.txt  --cookie-jar /tmp/cookies.txt -X POST

# Clears the entry if it existed (or potentially replaces the entire file? not verified):
# Response shows cookie was read with value from request, response sets the secure cookie with updated value
curl --url http://insecure.example.test --cookie 'session={"key":"value"}; Secure; HttpOnly; Path=/'  --cookie-jar /tmp/cookies.txt

# Seed cookie jar again, then continue:
# Does not remove `Secure` entry, presumably because cookie was not sent?:
# Response had no session found as expected, no cookie returned.
curl --url http://insecure.example.test --cookie /tmp/cookies.txt  --cookie-jar /tmp/cookies.txt
```

---

> Note that there is no Secure keyword in outgoing cookies from a client, so passing that is just going to be weird.

That would make sense 👍

I am clearly a newbie with this cookie logic, hence the misunderstanding on my part. I have just realized in dev tools I was looking at the response headers not request headers 🤦‍♂️ I had been going on the assumption of how the feature prevents sending the cookies if they have `Secure` and was confused why other clients were behaving expected but not curl.

Apologies for the noise. I'll close the issue, although the docs for the `--cookie` option maybe could better distinguish the caveat 😅
