### ISSUE TITLE
Connection redirect rule with --connect-to option ignored for connections to the proxy server

### ISSUE THREAD

**Issue by fffaraz** [curl/curl#14481]
### I did this

I have an HTTPS proxy server with mutual TLS authentication. 
For some reason (ahem, DPI ahem), I can't directly connect to the proxy server's IP address, so I use a local app to establish connections to my proxy server.

My HTTPS proxy server is running at "1.2.3.4:8443"
My local app is listening on port 8080 and for each incoming connection, it simply establishes a new TCP connection to my proxy server at "1.2.3.4:8443"

So I did this:
```
curl --verbose \
    --connect-to 1.2.3.4:8443:127.0.0.1:8080 \
    --proxytunnel \
    --proxy https://1.2.3.4:8443 \
     --proxy-cacert server.crt \
     --proxy-cert client.crt \
     --proxy-key client.key \
     https://ipv4.icanhazip.com/
```

### I expected the following

Since the proxy server's IP address is matching my redirect rule in `--connect-to`, I expect curl to connect to my local app instead. However, it ignores that and tries to directly connect to the proxy server's IP address.

If I remove `--connect-to` and replace my proxy IP address in `--proxy` with "127.0.0.1:8080" it complains about the SNI mismatch in my TLS certificate and drops the connection. It will work if I also add `--proxy-insecure`

I want to get it to work without `--proxy-insecure`. I guess adding a new option like `--proxy-sni` to explicitly set the SNI for the proxy server would work for my use case too.

### curl/libcurl version

curl 7.81.0 (also tested with the current master branch build)

### operating system

Pop!_OS 22.04 LTS

**Comment by bagder** [comment]
This was never intended to work. I think primarily because I have not seen a point in having this for proxies.

I think the documentation could be clarified to reduce the confusion. This functionality operates on the hostname and port numbers given in the URL.

**Comment by bagder** [comment]
but yeah, I did not consider the case of HTTPS proxies running on another machine at the time.

**Comment by otonoton** [comment]
> This was never intended to work. I think primarily because I have not seen a point in having this for proxies.

@bagder My usecase is that I have `all_proxy` defined in my `.bashrc`, so it's always active, and it uses `socks5h://`. So when I went to use `--connect-to`, the option was seemingly silently ignored. Eventually I figured out that I needed to remove the `h` from all_proxy temporarily in order to use `--connect-to` during a one-off test.
