### ISSUE TITLE
Use index.html with -O option when there is no name

### ISSUE THREAD

**Issue by ih8Gh** [curl/curl#14493]
### I did this

curl -O https://www.google.com/

curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application

### I expected the following

File index.html to be created, as it is the default name.

### curl/libcurl version

curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux [...] 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by samueloph** [comment]
I believe this was solved with https://github.com/curl/curl/pull/13988 which should appear in the next curl release.

**Comment by bagder** [comment]
Since curl picks a name without knowing what content that comes, we decided not to use an extension that might be wrong `curl_response` is the selected default file name.

**Comment by bagder** [comment]
> @bagder Makes sense. Can curl_response be changed?

My ideas was that if you want a name of your own, you use `-o`...
