### ISSUE TITLE
Curl crash with SSL connection

### ISSUE THREAD

**Issue by ankisawant58** [curl/curl#14517]
### I did this

Hi Team,
I am using curl 8.7.1
language - C
I am getting below crash when I send high volume of requests to one of our SSL servers. Non-ssl works fine. Please advise!

(dbx) where
.(??, ??, ??, ??, ??, ??, ??, ??, ??, ??, ??, ??, ??, ??, ??) at 0x100000000
look_str_cb@AF19_12() at 0x10063efac
int_cb_LHASH_DOALL_ARG() at 0x100544f58
doall_util_fn@AF15_10() at 0x1005243e8
engine_table_doall() at 0x100544fa8
ENGINE_pkey_asn1_find_str() at 0x10063e8dc
EVP_PKEY_asn1_find_str() at 0x1005a7b88
get_optional_pkey_id() at 0x1007c8c28
IPRA.$ssl_cipher_get_disabled() at 0x1007c9858
ssl_create_cipher_list() at 0x1007caf6c
SSL_CTX_set_cipher_list() at 0x1007c2644
ossl_connect_step1() at 0x1007b9508
ossl_connect_common() at 0x1007bc4f8
Curl_ssl_connect_nonblocking() at 0x1007b0b7c
Curl_http_connect() at 0x10085eb04
IPRA.$multi_runsingle() at 0x100825eec
curl_multi_perform() at 0x100827278
easy_perform() at 0x1007aea10
internal error: unexpected value 120 at line 5214 in file stabstring.c
internal error: unexpected value 120 at line 5214 in file stabstring.c
internal error: unexpected value 120 at line 5214 in file stabstring.c

### curl/libcurl version

curl 8.7.1

### operating system

AIX 7.2

**Comment by jay** [comment]
> I am getting below crash when I send high volume of requests to one of our SSL servers.

It looks like the crash is in OpenSSL not curl. If you are threading please refer to [thread safety guidelines](https://curl.se/libcurl/c/threadsafe.html).

**Comment by rsbeckerca** [comment]
> > I am getting below crash when I send high volume of requests to one of our SSL servers.
> 
> It looks like the crash is in OpenSSL not curl. If you are threading please refer to [thread safety guidelines](https://curl.se/libcurl/c/threadsafe.html).

What version of OpenSSL is this and what type of threading, if you are? I am aware that there have been some issues in lhash but none with this stack trace. Can you install a debug version?

**Comment by Shackster** [comment]
This version/package of curl for AIX has openssl 1.1.1 incorporated into it.

**Comment by ankisawant58** [comment]
curl 8.7.1 (powerpc-ibm-aix7.1.5.0) libcurl/8.7.1 **OpenSSL/1.1.1v** zlib/1.2.13 libssh2/1.10.0 nghttp2/1.58.0 OpenLDAP/2.5.16
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM SPNEGO SSL threadsafe UnixSockets

**Comment by bagder** [comment]
@ankisawant58 I suggest you build with debug symbols present and then debug the case when it happens using a debugger. As @jay mentioned, this looks like a clear case of a crash inside OpenSSL that might not be related to curl at all.

According to the OpenSSL project itself, version 1.1.1 is **out of support and should not be used**

**Comment by Shackster** [comment]
I imagine that in order to use a later version of OpenSSL, you would have to build curl with that later version from source. Do you have any recommendations for a good AIX debugger? Can this be done with DBX?

**Comment by bagder** [comment]
I personally prefer gdb on any platform. It was about 30 years since I last touched AIX, but if you don't know a debugger to use then probably no debugger is going to help you.

**Comment by bagder** [comment]
This has all the signs of not-a-curl-bug and the initial discussions in the OpenSSL discussion linked above indicate this as well.
