### ISSUE TITLE
Cross-compiler checked non-blocking mode error

### ISSUE THREAD

**Issue by TXTT2016** [curl/curl#14520]
### I did this

I build libcurl with conan, by using profile host and profile build to set up cross-compiler settings.
When I build locally, it worked, but when I build by docker, non-blocking mode configured unknown.

this is the locally build log:
[local-build.txt](https://github.com/user-attachments/files/16593769/local-build.txt)

this is docker build log:
[docker-build.txt](https://github.com/user-attachments/files/16593771/docker-build.txt)

### I expected the following

I want to know libcurl how to configure the non-blocking mode, and configured error by using docker 

### curl/libcurl version

curl 7.86.0

### operating system

locally system: 
```txt
Linux ubuntu 5.15.0-117-generic #127~20.04.1-Ubuntu SMP Thu Jul 11 15:36:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
docker system:
```txt
Linux ubuntu 5.15.0-117-generic #127~20.04.1-Ubuntu SMP Thu Jul 11 15:36:12 UTC 2024 x86_64 GNU/Linux
```

**Comment by dfandrich** [comment]
Here are a few things to note:

That version is almost 2 years old. I would try the latest version before
trying to debug this too deeply.

There is a configure warning that's being displayed that you should heed:

configure: CFLAGS note: CFLAGS should only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D__MUSL__=1


Macros (like __MUSL__) that start with an underscore are reserved by the
system, so setting them is likely to be dangerous. In this case, it may confuse
curl's configure into thinking that MUSL is in use when it's likely actually
Bionic.

Running under Docker could completely change the environment, so it's not
surprising that there are differences. Once you've dealt with the above, try
looking at the config.log to get some clues as to why one environment is
detecting setting non-blocking mode and the other isn't (I'm assuming you're
talking about the configure like "checking how to set a socket into
non-blocking mode").

**Comment by TXTT2016** [comment]
> Here are a few things to note: That version is almost 2 years old. I would try the latest version before trying to debug this too deeply. There is a configure warning that's being displayed that you should heed: configure: CFLAGS note: CFLAGS should only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D__MUSL__=1 Macros (like __MUSL__) that start with an underscore are reserved by the system, so setting them is likely to be dangerous. In this case, it may confuse curl's configure into thinking that MUSL is in use when it's likely actually Bionic. Running under Docker could completely change the environment, so it's not surprising that there are differences. Once you've dealt with the above, try looking at the config.log to get some clues as to why one environment is detecting setting non-blocking mode and the other isn't (I'm assuming you're talking about the configure like "checking how to set a socket into non-blocking mode").

The cross-compiler tools is clang, And I have defined  CFLAGS and CXXFLAGS env by export.

```txt
export CFLAGS="-fPIC -D__MUSL__=1"
export CXXFLAGS="-fPIC -D__MUSL__=1"
```

Maybe I need to set the cross compiler cmake toolchains? I will have a try, Thanks :)

**Comment by TXTT2016** [comment]
> Here are a few things to note: That version is almost 2 years old. I would try the latest version before trying to debug this too deeply. There is a configure warning that's being displayed that you should heed: configure: CFLAGS note: CFLAGS should only be used to specify C compiler flags, not macro definitions. Use CPPFLAGS for: -D__MUSL__=1 Macros (like __MUSL__) that start with an underscore are reserved by the system, so setting them is likely to be dangerous. In this case, it may confuse curl's configure into thinking that MUSL is in use when it's likely actually Bionic. Running under Docker could completely change the environment, so it's not surprising that there are differences. Once you've dealt with the above, try looking at the config.log to get some clues as to why one environment is detecting setting non-blocking mode and the other isn't (I'm assuming you're talking about the configure like "checking how to set a socket into non-blocking mode").

I export these env before libcurl compiler:

```
export CFLAGS="--target=aarch64-linux-ohos -fPIC -D__MUSL__=1"
export CXXFLAGS="--target=aarch64-linux-ohos -fPIC -D__MUSL__=1"
```

But it doesn't seem to worked?

**Comment by TXTT2016** [comment]
I modified some options and solved the non-blocking configure. But another error happened.

```txt
configure: WARNING: Continuing even with errors mentioned immediately above this line.
cookie.c:236:12: warning: call to undeclared function 'memrchr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    last = memrchr(domain, '.', len);
           ^
cookie.c:236:10: error: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
    last = memrchr(domain, '.', len);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
cookie.c:238:13: error: incompatible integer to pointer conversion assigning to 'const char *' from 'int' [-Wint-conversion]
      first = memrchr(domain, '.', (last - domain));
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cookie.c:839:20: warning: call to undeclared function 'memrchr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        endslash = memrchr(path, '/', (queryp - path));
                   ^
cookie.c:839:18: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
        endslash = memrchr(path, '/', (queryp - path));
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 3 errors generated.
```

**Comment by dfandrich** [comment]
memrchr is a standard POSIX function that should be defined in string.h. Does the libc you're using support it? The log snippet you show is clearly not including some error logs.

**Comment by TXTT2016** [comment]
> memrchr is a standard POSIX function that should be defined in string.h. Does the libc you're using support it? The log snippet you show is clearly not including some error logs.

This is the config log, it seems memrchr have found.

[config.log](https://github.com/user-attachments/files/16607102/config.log)

**Comment by TXTT2016** [comment]
The target system is HarmonyOs. Cross-tool chain provider suggest the env set like these:

```
export OHOS_SDK=/home/owner/tools/OHOS_SDK/ohos-sdk/linux/                   ## 配置SDK路径，此处需配置成自己的sdk解压目录
export AS=${OHOS_SDK}/native/llvm/bin/llvm-as
export CC="${OHOS_SDK}/native/llvm/bin/clang --target=aarch64-linux-ohos"    ## 32bit的target需要配置成 --target=arm-linux-ohos
export CXX="${OHOS_SDK}/native/llvm/bin/clang++ --target=aarch64-linux-ohos" ## 32bit的target需要配置成 --target=arm-linux-ohos
export LD=${OHOS_SDK}/native/llvm/bin/ld.lld
export STRIP=${OHOS_SDK}/native/llvm/bin/llvm-strip
export RANLIB=${OHOS_SDK}/native/llvm/bin/llvm-ranlib
export OBJDUMP=${OHOS_SDK}/native/llvm/bin/llvm-objdump
export OBJCOPY=${OHOS_SDK}/native/llvm/bin/llvm-objcopy
export NM=${OHOS_SDK}/native/llvm/bin/llvm-nm
export AR=${OHOS_SDK}/native/llvm/bin/llvm-ar
export CFLAGS="-fPIC -D__MUSL__=1"                                            ## 32bit需要增加配置 -march=armv7a
export CXXFLAGS="-fPIC -D__MUSL__=1"                                          ## 32bit需要增加配置 -march=armv7a
```

Maybe CC and CXX env can't append the --target option?

**Comment by dfandrich** [comment]
The first logs had mentions of android throughout them. The new one does not. Are you trying to solve more than one build problem in this issue?

The last config logs says "checking if memrchr is prototyped: yes" so there should be a prototype (unless that check is failing). Could it be that it's only visible in the header files under certain conditions?

**Comment by TXTT2016** [comment]
`string.h` have the prototyped, Maybe the `_GNU_SOURCE` need define?

```
#ifdef _GNU_SOURCE
#define	strdupa(x)	strcpy(alloca(strlen(x)+1),x)
char *strchrnul(const char *, int);
char *strcasestr(const char *, const char *);
void *memmem(const void *, size_t, const void *, size_t);
void *memrchr(const void *, int, size_t);
void *mempcpy(void *, const void *, size_t);
#ifndef __cplusplus
char *basename();
#endif
#endif
```

**Comment by dfandrich** [comment]
> Maybe the _GNU_SOURCE need define?

That's a good guess.

**Comment by TXTT2016** [comment]
I found local compiler（don't use docker）. The `memrchr` prototyped are not found, so it compilered 🤣。Mayby I can try to use curl_memrchr 🤣

**Comment by TXTT2016** [comment]
> Maybe the _GNU_SOURCE need define?
> That's a good guess.

I add this define and compiler passed :D
