### ISSUE TITLE
MacOS Catalyst: broken ciphers with secure-transport backend

### ISSUE THREAD

**Issue by konradglas** [curl/curl#14547]
### I did this

trying to establish an ssl connection to "https://example.com". Works on MacOS and iOS
      curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");
...
      curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_string);

### I expected the following

... to successfully connect.
Instead, I got a message about `curl_easy_perform() failed: Could not use specified SSL cipher`
The reason seems to be that the in sectransp.c the `default_ciphers` are of int16_t* type. Whereas the cipher types for CATALYST are 

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Versions/A/Headers/CipherSuite.h

```
#if ((TARGET_OS_IPHONE && !TARGET_OS_MACCATALYST) || (TARGET_OS_OSX && TARGET_CPU_ARM64))
/* 16-bit value on iOS */
typedef uint16_t SSLCipherSuite;
#else
/* 32-bit value elsewhere */
typedef uint32_t SSLCipherSuite; <<==== THIS
#endif
```
Leading to a mismatch. Note that if I just set the raw ciphers without checking default_ciphers here
```
  err = SSLSetEnabledCiphers(ssl_ctx, ciphers, supported_len);
```
the error goes away. (Of course not a valid solution ... just my findings)

### curl/libcurl version

current master

### operating system

MacOS Catalyst

**Comment by jan2000** [comment]
From your report I gather you are able to build your own libcurl. Could you replace `sectransp_set_default_ciphers` in `sectransp.c` with the following and provide the output here? That could greatly help.

```c
static CURLcode sectransp_set_default_ciphers(struct Curl_easy *data,
                                              SSLContextRef ssl_ctx)
{
  CURLcode ret = CURLE_SSL_CIPHER;
  size_t count = 0, i, j;
  OSStatus err;
  size_t supported_len;
  SSLCipherSuite *ciphers = NULL;

  ciphers = sectransp_get_supported_ciphers(ssl_ctx, &supported_len);
  if(!ciphers) {
    failf(data, "SSL: Failed to get supported ciphers");
    goto failed;
  }

#ifdef TARGET_OS_MAC
  printf("TARGET_OS_MAC: %i\n", TARGET_OS_MAC);
#else
  printf("TARGET_OS_MAC: not defined\n");
#endif
#ifdef TARGET_OS_EMBEDDED
  printf("TARGET_OS_EMBEDDED: %i\n", TARGET_OS_EMBEDDED);
#else
  printf("TARGET_OS_EMBEDDED: not defined\n");
#endif
#ifdef TARGET_OS_IPHONE
  printf("TARGET_OS_IPHONE: %i\n", TARGET_OS_IPHONE);
#else
  printf("TARGET_OS_IPHONE: not defined\n");
#endif
#ifdef TARGET_OS_MACCATALYST
  printf("TARGET_OS_MACCATALYST: %i\n", TARGET_OS_MACCATALYST);
#else
  printf("TARGET_OS_MACCATALYST: not defined\n");
#endif
#ifdef MAC_OS_X_VERSION_MAX_ALLOWED
  printf("MAC_OS_X_VERSION_MAX_ALLOWED: %i\n", MAC_OS_X_VERSION_MAX_ALLOWED);
#else
  printf("MAC_OS_X_VERSION_MAX_ALLOWED: not defined\n");
#endif
#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
  printf("__IPHONE_OS_VERSION_MAX_ALLOWED: %i\n", __IPHONE_OS_VERSION_MAX_ALLOWED);
#else
  printf("__IPHONE_OS_VERSION_MAX_ALLOWED: not defined\n");
#endif
  for(i = 0; i < supported_len; i++)
    printf("SUPPORTED_CIPHERS: 0x%04x\n", ciphers[i]);
  for(j = 0; j < DEFAULT_CIPHERS_LEN; j++)
    printf("DEFAULT_CIPHERS: 0x%04x\n", default_ciphers[j]);

  /* Intersect the ciphers supported by Secure Transport with the default
   * ciphers, using the order of the former. */
  for(i = 0; i < supported_len; i++) {
    for(j = 0; j < DEFAULT_CIPHERS_LEN; j++) {
      if(default_ciphers[j] == ciphers[i]) {
        ciphers[count++] = ciphers[i];
        break;
      }
    }
  }

  if(count == 0) {
    failf(data, "SSL: no supported default ciphers");
    goto failed;
  }

  err = SSLSetEnabledCiphers(ssl_ctx, ciphers, count);
  if(err != noErr) {
    failf(data, "SSL: SSLSetEnabledCiphers() failed: OSStatus %d", err);
    goto failed;
  }

  ret = CURLE_OK;
failed:
  Curl_safefree(ciphers);
  return ret;
}
```

**Comment by konradglas** [comment]
here you go
```
TARGET_OS_MAC: 1
TARGET_OS_EMBEDDED: 0
TARGET_OS_IPHONE: 1
TARGET_OS_MACCATALYST: 1
MAC_OS_X_VERSION_MAX_ALLOWED: 140000
__IPHONE_OS_VERSION_MAX_ALLOWED: 170400
SUPPORTED_CIPHERS: 0xc02bc02c
SUPPORTED_CIPHERS: 0xc023c024
SUPPORTED_CIPHERS: 0xc009c00a
SUPPORTED_CIPHERS: 0xc030c008
SUPPORTED_CIPHERS: 0xc028c02f
SUPPORTED_CIPHERS: 0xc014c027
SUPPORTED_CIPHERS: 0xc012c013
SUPPORTED_CIPHERS: 0xc02dc02e
SUPPORTED_CIPHERS: 0xc025c026
SUPPORTED_CIPHERS: 0xc004c005
SUPPORTED_CIPHERS: 0xc032c003
SUPPORTED_CIPHERS: 0xc02ac031
SUPPORTED_CIPHERS: 0xc00fc029
SUPPORTED_CIPHERS: 0xc00dc00e
SUPPORTED_CIPHERS: 0x9e009f
SUPPORTED_CIPHERS: 0x67006b
SUPPORTED_CIPHERS: 0x330039
SUPPORTED_CIPHERS: 0x9d0016
SUPPORTED_CIPHERS: 0x3d009c
SUPPORTED_CIPHERS: 0x35003c
SUPPORTED_CIPHERS: 0xa002f
SUPPORTED_CIPHERS: 0x13021301
SUPPORTED_CIPHERS: 0xa71303
SUPPORTED_CIPHERS: 0x6c00a6
SUPPORTED_CIPHERS: 0x34006d
SUPPORTED_CIPHERS: 0x1b003a
SUPPORTED_CIPHERS: 0xc010c006
SUPPORTED_CIPHERS: 0xc00bc001
SUPPORTED_CIPHERS: 0xae00af
SUPPORTED_CIPHERS: 0x8c008d
SUPPORTED_CIPHERS: 0xb1008b
SUPPORTED_CIPHERS: 0x2c00b0
SUPPORTED_CIPHERS: 0x2003b
SUPPORTED_CIPHERS: 0x0001
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
SUPPORTED_CIPHERS: 0x0000
DEFAULT_CIPHERS: 0x000a
DEFAULT_CIPHERS: 0x002f
DEFAULT_CIPHERS: 0x0035
DEFAULT_CIPHERS: 0xc009
DEFAULT_CIPHERS: 0xc00a
DEFAULT_CIPHERS: 0xc013
DEFAULT_CIPHERS: 0xc014
DEFAULT_CIPHERS: 0x003c
DEFAULT_CIPHERS: 0x003d
DEFAULT_CIPHERS: 0x0067
DEFAULT_CIPHERS: 0x006b
DEFAULT_CIPHERS: 0x009c
DEFAULT_CIPHERS: 0x009d
DEFAULT_CIPHERS: 0x009e
DEFAULT_CIPHERS: 0x009f
DEFAULT_CIPHERS: 0xc023
DEFAULT_CIPHERS: 0xc024
DEFAULT_CIPHERS: 0xc027
DEFAULT_CIPHERS: 0xc028
DEFAULT_CIPHERS: 0xc02b
DEFAULT_CIPHERS: 0xc02c
DEFAULT_CIPHERS: 0xc02f
DEFAULT_CIPHERS: 0xc030
DEFAULT_CIPHERS: 0xcca8
DEFAULT_CIPHERS: 0xcca9
DEFAULT_CIPHERS: 0x1301
DEFAULT_CIPHERS: 0x1302
DEFAULT_CIPHERS: 0x1303
```

**Comment by jan2000** [comment]
When you are building libcurl in the header file `CipherSuite.h` (supplied by the Security framework) `SSLCipherSuite` gets typdef `uint32_t`, but the library you are linking against is built with typedef `uint16_t`.

So, probably one or more of these defines has a wrong value when you are building libcurl: `TARGET_OS_IPHONE` `TARGET_OS_MACCATALYST` `TARGET_OS_OSX` `TARGET_CPU_ARM64`. Check you build target settings, and see `TargetConditionals.h` for more info.

It seems this is not a libcurl bug. There is not much libcurl can do if there is a mismatch between the header file and library for a dependency.

**Comment by konradglas** [comment]
My application is linking against a statically built libcurl version. I don't understand what you mean by "the library you are linking against". You mean the Security Framework? I cannot find anything wrong there in my linker commands at least.

The `default_cyphers` are of int16_t and those are hard coded/required by libcurl itself. The `SSLCipherSuite` is int32_t indeed. Because I am building for `TARGET_OS_MACCATALYST`. It _should_ be exactly the same as when compiling for `TARGET_OS_OSX` on `X86_64`. 
I actually also tried exactly that combination. Which (unsurprisingly) actually works. So it is actually not the mismatch of types itself that causes the issue. What I am really surprised by is that `SSLGetSupportedCiphers` gives back such weird values in the case of catalyst. They really look like int16_t values packed in int32_t.
Regarding the defines ... I don't find anything wrong there? If building for catalyst those defines should be enabled:
`TARGET_OS_MACCATALYST ` and `TARGET_OS_MAC ` and `TARGET_OS_IPHONE `
So either
a) I am missing something/haven't understood your feedback (which would be great because it would be the easiest fix)
b) There is a bug in the Security Framework ... but only with `TARGET_OS_MACCATALYST`
c) curl somehow needs to handle that special case and it doesn't yet

**Comment by konradglas** [comment]
I just tried a very simple Catalyst App without curl which also tries to do the same thing.
```
#include "sec_test.h"
#include <Security/Security.h>


void print_cyphers(void)
{
    SSLContextRef ssl_ctx = SSLCreateContext(NULL, kSSLClientSide, kSSLStreamType);

    SSLCipherSuite *ciphers = NULL;
    OSStatus err = noErr;
    int len = 0;

    err = SSLGetNumberSupportedCiphers(ssl_ctx, &len);
    if(err != noErr)
        return;

    ciphers = malloc(len * sizeof(SSLCipherSuite));
    if(!ciphers)
        return;
    err = SSLGetSupportedCiphers(ssl_ctx, ciphers, &len);
    if(err != noErr)
        return;
    
    for (int i = 0; i < len; ++i) {
        printf("SUPPORTED_CIPHERS: 0x%04x\n", ciphers[i]);
    }
}
```
I get the exact same result that I pasted before. 

There are a ton of warnings about Security being deprecated/unsupported for `macCatalyst 13.1` and above. Should use Network instead.

**Comment by jan2000** [comment]
> My application is linking against a statically built libcurl version. I don't understand what you mean by "the library you are linking against". You mean the Security Framework? I cannot find anything wrong there in my linker commands at least.

Yes the library provided by the Security Framework. In this case that is built with typedef `uint16_t`.

> The default_cyphers are of int16_t and those are hard coded/required by libcurl itself.

This is by design, because of integer promotion the comparison `default_ciphers[j] == ciphers[i]` works with SSLCipherSuite that is either `uint16_t` or `uint32_t`.

> The SSLCipherSuite is int32_t indeed. Because I am building for TARGET_OS_MACCATALYST. It should be exactly the same as when compiling for TARGET_OS_OSX on X86_64.

For the library of the Security Framework you are linking against it should be `uint16_t`.

> I actually also tried exactly that combination. Which (unsurprisingly) actually works. So it is actually not the mismatch of types itself that causes the issue. What I am really surprised by is that SSLGetSupportedCiphers gives back such weird values in the case of catalyst. They really look like int16_t values packed in int32_t.

The memory set by the Security Framework library is a `uint16_t` array. However, curl is being build with typedef `uint32_t`, and thus the memory is misinterpreted as such. Hence the combined values. The problem is that at time of building curl, in the header file provided by the Security Framework the type of SSLCipherSuite is `uint32_t`, while it should match the library and must be `uint16_t`.

> Regarding the defines ... I don't find anything wrong there? If building for catalyst those defines should be enabled:
TARGET_OS_MACCATALYST and TARGET_OS_MAC and TARGET_OS_IPHONE 
> So either
> a) I am missing something/haven't understood your feedback (which would be great because it would be the easiest fix)

The defines controls what type SSLCipherSuite gets when building curl. In this case that should be `uint16_t`.

> b) There is a bug in the Security Framework ... but only with TARGET_OS_MACCATALYST

Could be.

>c) curl somehow needs to handle that special case and it doesn't yet

It should not.

**Comment by konradglas** [comment]
>The defines controls what type SSLCipherSuite gets when building curl. In this case that should be uint16_t.

why do you say that? Look at the define I pasted in CypherSuite.h. The value takes int32_t size which is correct
for Mac catalyst:
```
// for a catalyst build those are defined 
TARGET_OS_MACCATALYST=1
TARGET_OS_IPHONE=1
#if ((TARGET_OS_IPHONE && !TARGET_OS_MACCATALYST) || (TARGET_OS_OSX && TARGET_CPU_ARM64))
/* 16-bit value on iOS */
typedef uint16_t SSLCipherSuite;
#else
/* 32-bit value elsewhere */
typedef uint32_t SSLCipherSuite; <<==== Hence we get THIS
#endif
```
>The memory set by the Security Framework library is a uint16_t array. 

Yes ... it seems so indeed. At least I would also interpret the values it spits out like that.

Also regarding my post about my simple minimal reproduction example. It seems that libcurl is not supported then for Mac Catalyst unless you upgrade to the Network framework? Because there we seem to have the exact same problem. The array seems to be filled as an int16_t but the `SSLCipherSuite ` is correctly typedefed as int32_t

**Comment by jan2000** [comment]
> why do you say that? Look at the define I pasted in CypherSuite.h. The value takes int32_t size which is correct
for Mac catalyst:

No it is not. Again, for the library of the Security Framework you are linking against it should be uint16_t, because it is uint16_t in that library.

> It seems that libcurl is not supported then for Mac Catalyst and Security Transport backend unless you upgrade to the Network framework?

Network framework support is unlikely, see:
https://curl.se/mail/lib-2024-05/0007.html

**Comment by konradglas** [comment]
>No it is not. Again, for the library of the Security Framework you are linking against it should be uint16_t, because it is uint16_t in that library.

Fair enough :)  We have a discrepancy between what is returned by the framework and what it is _supposed_ to be returned which is clearly defined as int32_t for Catalyst. 

What would be great to know from you:
Is it something that is within my power to change? I am not aware that I am doing anything wrong in using that library.

I get that maybe Mac Catalyst is too obscure to support for libcurl. In that case you should mark it as unsupported in combination with Security

**Comment by jan2000** [comment]
> Is it something that is within my power to change?

First, you should double check your build settings. Either you are linking against the wrong target library (from the Security framework), or the build settings (the TARGET_ defines) when building libcurl are wrong, or the discrepancy is due to an Apple bug. In case of the latter, you could try something really janky as adding `#define SSLCipherSuite uint16_t` to sectranp.c (after the includes). Or you could use a different SSL backend for libcurl.

**Comment by konradglas** [comment]
Yes I fear I will try the janky one ... the build TARGET_ defines are obviously out of my reach and are correct. 
The linking cannot be more vanilla. Especially in my min example (I am really just adding the Security framework which is the same as `-framework Security` in the linker flags).
I will close this issue now because I don't think it is something that will be fixed on your side (working around an Apple bug from a deprecated library). I hope other people running into the same thing will find this thread helpful :)
