### ISSUE TITLE
cURL Segmentation fault

### ISSUE THREAD

**Issue by RealYukiSan** [curl/curl#14592]
### I did this

`curl -F 'file=@-' 0x0.st < msys2-x86_64-20240727.exe`

download the file [here](https://github.com/msys2/msys2-installer/releases/download/2024-07-27/msys2-x86_64-20240727.exe)

### I expected the following

file uploaded successfully

### curl/libcurl version

```
$ curl -V
curl 8.9.1 (x86_64-pc-linux-gnu) libcurl/8.9.1 OpenSSL/3.3.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.62.1 nghttp3/1.4.0
Release-Date: 2024-07-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

Arch Linux

```
$ uname -a
Linux ASUS 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
The site 0x0.st sends `Segmentation fault` as response data. It is not a crash. if you add -v to the command line you'll see it more clearly.

**Comment by RealYukiSan** [comment]
Ah my bad, I didn't cross-check using the verbose option. Sorry for the confusion.
