### ISSUE TITLE
Missing "tool_convert.h" prototypes

### ISSUE THREAD

**Issue by gvanem** [curl/curl#1460]
When compiling ./src/curl.exe, I get these warnings on missing prototypes:
```
tool_cb_dbg.c(260): warning C4013: 'convert_char' undefined; assuming extern returning int
tool_formparse.c(335): warning C4013: 'convert_to_network' undefined; assuming extern returning int
tool_getparam.c(1324): warning C4013: 'convert_to_network' undefined; assuming extern returning int
```
Using MSVC-2015, 32-bit and `-DHAVE_ICONV -DCURL_DOES_CONVERSIONS`.
The fix should simply be to add a: 
```
#include "tool_convert.h"
```
in those 3 files AFAICS.

**Comment by jay** [comment]
Thanks, landed in 5b13619. Also, I notice CURL_DOES_CONVERSIONS without HAVE_ICONV doesn't work since convert_char depends on convert_from_network. Is that expected, it seems that the former requires the latter.

**Comment by bagder** [comment]
Curl_convert_from_network() seems to be able to be performed with a callback instead of iconv so I think it is correct.

Isn't this issue now fixed in git so we can close it?

**Comment by jay** [comment]
Ok. It was related which is why I left it open.
