### ISSUE TITLE
curl 8.9.1 reports HTTP/2 stream was not closed cleanly: PROTOCOL_ERROR for 416

### ISSUE THREAD

**Issue by xandris** [curl/curl#14620]
### I did this

```
$ curl -vvvS --fail-early -Lo go1.23.0.src.tar.gz https://go.dev/dl/go1.23.0.src.tar.gz

# whoops, I didn't see if that finished. try again to be sure

$ curl -vvvS --fail-early -Lo go1.23.0.src.tar.gz --continue-at - https://go.dev/dl/go1.23.0.src.tar.gz
HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

### I expected the following

Either the download to be completed or a harmless 416. Maybe this is a problem with go.dev, but I can't tell one way or the other. `--http1.1` works.

### curl/libcurl version

curl 8.9.1 (aarch64-apple-darwin23.4.0) libcurl/8.9.1 OpenSSL/3.3.1 (SecureTransport) zlib/1.2.12 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libssh2/1.11.0 nghttp2/1.61.0 librtmp/2.3
Release-Date: 2024-07-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Darwin 58mbp1591 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031 arm64

**Comment by jay** [comment]
I can reproduce this. In Wireshark I can see Google's server replies to the request by sending HEADERS with a content length of 0 followed immediately by a bunch of DATA frames, of what I don't know and doesn't make sense, and libcurl (or nghttp2 on its own) sends back a RST_STREAM set to PROTOCOL_ERROR.

**Comment by bagder** [comment]
I have reached out to a Google person pointing out their flaw. Hopefully that helps getting this resolved. I'm closing this issue now as this is not a curl problem.
