### ISSUE TITLE
FTP upload error: Uploaded unaligned file size (92030 out of 92048 bytes), though the upload is complete

### ISSUE THREAD

**Issue by Fecovagyok** [curl/curl#14713]
### I did this

Upload a text file to an FTP server through curllib with CURLOPT_TRANSFERTEXT set to 1 and CURLOPT_INFILESIZE (or INFILESIZE_LARGE) set to the file's size. The upload fails with error code 18 (CURL_PARTIAL_FILE_SIZE) and on the print callbacks the 'Uploaded unaligned file size (92030 out of 92048 bytes)' error message is visible. Mind you the contents of the file are intact, the file transfer was actually successful.

The text file should be at least ~72 kilobytes (I think it has to do something with the upload buffer size, because increasing the buffer size above 100 kilobytes makes the issue disappear), it should contain at least 6000 newline characters (so the LF->CRLF conversion would make the file ~12 kilobytes bigger) for this change to materialize itself.

Setting CURLOPT_TRANSFERTEXT to 0 disabled the LF->CRLF conversion, and the issue disappeared in this case the uploaded bytes were equal to the file size. Unsetting the INFILESIZE option also resolved this issue (with TRANSFERTEXT on), in this case the transferred bytes were ~12 kilobytes more, than the file size on the disk (supposedly, because of the LF->CRLF conversion).
Also, setting CURLOPT_CRLF to 1, also resolved this issue.

So it seems like in case of the combo of CUROPT_TRANSFERTEXT and  CURLOPT_INFILESIZE file size estimation is not working correctly if the file size is bigger than the UPLOAD_BUFFERSIZE.

The code I am maintaining is quite rigid and buggy, so I don't want to mess around and try what happens turning off either of these options.
On 7.86.0 it just works without saying
On 8.8.0 it doesn't

### curl/libcurl version

8.8.0

### operating system

Linux 3.10.108

**Comment by bagder** [comment]
I made #14717 to try to repro this, but it works fine locally.

**Comment by bagder** [comment]
> increasing the buffer size above 100 kilobytes makes the issue disappear

Can you clarify what buffer size you use when you see the problem?

**Comment by Fecovagyok** [comment]
I did not change the buffer size, so to my knowledge it was on the default buffer size of 65536 bytes.
> increasing the buffer size above 100 kilobytes makes the issue disappear

I believe in that case the file I was trying to upload was about 71 kilobytes, so I concluded that changing the buffer size so that the whole file fits into one buffer is the thing that resolves the issue.

> I made https://github.com/curl/curl/pull/14717 to try to repro this, but it works fine locally.

I have crafted a text file where I tested all these. 
I'll upload it here so if you find the time can try to reproduce by uploading that file as well? You might have better luck with that.
[crafted_text_file_for_crl_ftp_issue.txt](https://github.com/user-attachments/files/16796561/crafted_text_file_for_crl_ftp_issue.txt)

**Comment by icing** [comment]
@Fecovagyok we found the issue. It has been fixed in 8.9.0 and was reported as #14165, fixed by #14169.

**Comment by Fecovagyok** [comment]
That would be awsome, I'll test it and get back to you!

**Comment by Fecovagyok** [comment]
You were right, it's fixed in 8.9.0, thank you for the quick response!
