### ISSUE TITLE
BoringSSL: certificate routines:OPENSSL_internal:CERT_ALREADY_IN_HASH_TABLE

### ISSUE THREAD

**Issue by pkropachev** [curl/curl#14740]
### I did this

Hello Team!

I faced with strange behaviour in case build `curl` from the current master branch with [quiche](https://github.com/cloudflare/quiche) and BoringSSL.
I get the following error in case attempt to request any URLs:
`BoringSSL: error:0b000069:X.509 certificate routines:OPENSSL_internal:CERT_ALREADY_IN_HASH_TABLE`

```
#> curl --version
curl 8.10.0-DEV (x86_64-pc-linux-gnu) libcurl/8.10.0-DEV BoringSSL zlib/1.2.11 c-ares/1.33.1 libpsl/0.21.0 nghttp2/1.63.0 quiche/0.22.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets
```

```
#> curl -v https://curl.se -s -o /dev/null
* Host curl.se:443 was resolved.
* IPv6: 2a04:4e42:200::347, 2a04:4e42:e00::347, 2a04:4e42:c00::347, 2a04:4e42::347, 2a04:4e42:400::347, 2a04:4e42:600::347, 2a04:4e42:800::347, 2a04:4e42:a00::347
* IPv4: 151.101.129.91, 151.101.65.91, 151.101.1.91, 151.101.193.91
*   Trying 151.101.129.91:443...
* Connected to curl.se () port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* BoringSSL: error:0b000069:X.509 certificate routines:OPENSSL_internal:CERT_ALREADY_IN_HASH_TABLE
* closing connection #0
```

In the same time all works correct in case build `curl` from `curl_8_9_1` tag.

```
#> curl --version
curl 8.9.1-DEV (x86_64-pc-linux-gnu) libcurl/8.9.1-DEV BoringSSL zlib/1.2.11 c-ares/1.33.1 libpsl/0.21.0 nghttp2/1.63.0 quiche/0.22.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets
```

```
#> curl -v https://curl.se -s -o /dev/null
* Host curl.se:443 was resolved.
* IPv6: 2a04:4e42:200::347, 2a04:4e42:e00::347, 2a04:4e42:c00::347, 2a04:4e42::347, 2a04:4e42:400::347, 2a04:4e42:600::347, 2a04:4e42:800::347, 2a04:4e42:a00::347
* IPv4: 151.101.129.91, 151.101.65.91, 151.101.1.91, 151.101.193.91
*   Trying 151.101.129.91:443...
* Connected to curl.se (151.101.129.91) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1384 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
...
*  SSL certificate verify ok.
{ [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://curl.se/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: curl.se]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.9.1-DEV]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET / HTTP/2
> Host: curl.se
> User-Agent: curl/8.9.1-DEV
> Accept: */*
> 
* Request completely sent off
{ [5 bytes data]
< HTTP/2 200 
...
```

In both cases versions quiche and BoringSSL are the same.

### curl/libcurl version

curl 8.10.0-DEV (current master)

### operating system

Ubuntu 20.04.6 LTS

**Comment by bagder** [comment]
It does not reproduce for me when I build with BoringSSL from current master.

Since you build with quiche however, I suspect you use the old BoringSSL version that quiche still works with? Because quiche from their current master does not work with current BoringSSL (due to C++ issues)

**Comment by pkropachev** [comment]
I use release version of quiche 0.22.0 and corresponding submodule BoringSSL. Strange that just switching between curl version solves the problem.

Ok, thanks! I will double-check on other computer.

**Comment by bagder** [comment]
I strongly recommend you switch to using ngtcp2 for QUIC in curl.

**Comment by bagder** [comment]
This said, we do run HTTP/3 CI jobs fine on current master using quiche 0.22.0

**Comment by pkropachev** [comment]
> This said, we do run HTTP/3 CI jobs fine on current master using quiche 0.22.0

It means that `curl` from the current master should work with quiche 0.22.0 and BoringSSL ([f1c7534](https://github.com/google/boringssl/tree/f1c75347daa2ea81a941e953f2263e0a4d970c8d)) used by quiche.
Perhaps problem is in my environment. I will check on another computer.

**Comment by bagder** [comment]
That BoringSSL commit is **three years old**. Just emphasizing you should not use quiche (as it currently stands).

I just mean that the combination quiche+boring at least works for some use cases.

**Comment by bagder** [comment]
I don't think this is actionable for us. This sounds like a problem with the ancient BoringSSL version. The recommendation is to use a more recent BoringSSL if you want to use that TLS library, and use ngtcp2+nghttp3 if you want a more reliable HTTP/3 solution (but then presumably with another TLS library than boring).
