### ISSUE TITLE
Disabling CURLOPT_SSL_VERIFYPEER causes Host: header to lose the port number

### ISSUE THREAD

**Issue by cwarner-8702** [curl/curl#14742]
### I did this

I'm using libcurl to communicate to a proxy application that records and replays network calls for more stable testing.  The proxy depends on the `Host:` header for part of it's request matching, expecting it to exactly match the recorded header.

When I disable the CURLOPT_SSL_VERIFYPEER option (also necessary for other tests), the `Host:` header sent to the proxy seems to lose the port component of the base URL, and the proxy does not find a matching request.

Minimal repro code:

```c++
CURL* curl = curl_easy_init();
curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);
curl_easy_setopt(curl, CURLOPT_URL, "https://demo.geo-solutions.it:443/geoserver");
curl_easy_setopt(curl, CURLOPT_PROXY, "127.0.0.1");
curl_easy_setopt(curl, CURLOPT_PROXYPORT, 8888);
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
curl_easy_perform(curl);
```

Relevant libcurl output:

```
...
* CONNECT phase completed
* CONNECT tunnel established, response 200
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: connection hostname (demo.geo-solutions.it) validated against certificate name (demo.geo-solutions.it)
* ALPN: server did not agree on a protocol. Uses default.
* using HTTP/1.x
> GET /geoserver HTTP/1.1
Host: demo.geo-solutions.it
Accept: */*
...
```

### I expected the following

`Host:` header to contain the port number regardless of the `CURLOPT_SSL_VERIFYPEER` setting:

```
...
> GET /geoserver HTTP/1.1
Host: demo.geo-solutions.it:443
Accept: */*
...
```

### curl/libcurl version

curl 8.9.1

### operating system

Windows and macOS 14.6

**Comment by bagder** [comment]
This behavior is unrelated to what you set `CURLOPT_SSL_VERIFYPEER` to.

libcurl *never* passes the port number in the `Host:` header if it is the same port number as the default for the protocol it uses (80 for HTTP, 443 for HTTPS). Simply because that causes interop issues in the wild.

**Comment by cwarner-8702** [comment]
You're right.  With `SSL_VERIFYPEER` still enabled, it looks like the proxy never makes it passed the `CONNECT` phase.  My mistake and apologies.

Sounds like you're very much against passing the default port number for `Host:`.  There's no way around that, such as by using `CURLOPT_CURLU`?  Or adding a `CURLOPT_` option or flag to `curl_url_set(..., CURLUPART_PORT, ...)`?

**Comment by bagder** [comment]
I would prefer to turn it around: your server end will not interoperate very well with general HTTP clients if it insists that port 443 must be used in the `Host:` header when the HTTPS server runs on port 443.

Also: curl has worked like this for decades and I think we can say with some level of certainty that it interoperates well with HTTPS servers "out there".

**Comment by dfandrich** [comment]
Sounds like the proxy server is broken, but it should be possible to add the
port number to the Host: header by completely redefining the header with
CURLOPT_HTTPHEADER. Which isn't something you really want to be doing in the
general case.
