### ISSUE TITLE
MACOS fails with --proxy-negotiate or --proxy-ntlm while windows succeed.

### ISSUE THREAD

**Issue by lisalisal** [curl/curl#14757]
### I did this

I setup a wingate proxy server in a windows server which join our domain, and the proxy server enables negotiate and NTLM authentication.
I have a windows machine which also join domain, and run following commands, both succeed.
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-negotiate --proxy-user :  -v'
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-ntlm --proxy-user :  -v'

Attached the windows curl output for both '--proxy-negotiate' and '--proxy-ntlm', it worked as expected.
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-negotiate --proxy-user :  -v'
<img width="972" alt="windows curl negotiate" src="https://github.com/user-attachments/assets/68cd867c-ce4a-42e7-977d-b8dc1dae090b">

'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-ntlm --proxy-user :  -v'
<img width="972" alt="windows curl ntlm" src="https://github.com/user-attachments/assets/02c0accb-b01b-4c44-bc29-9bb8f114dd2c">

But in macos, my mac machine also join the same domain, I login machine with a domain user, but when run following curl commands, both failed with a 2nd ' 407 Proxy Authentication Required', where above windows returns 'HTTP/1.1 200 Connection established', in macos, it returns a 2nd ' 407 Proxy Authentication Required', then the authentication failed.
Attached the mac curl output for both '--proxy-negotiate' and '--proxy-ntlm', it failed.
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-negotiate --proxy-user :  -v'
<img width="1157" alt="mac curl negotiate" src="https://github.com/user-attachments/assets/8d57da5d-686b-42c1-b73e-55cb48fe92a4">

'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-ntlm --proxy-user :  -v'
<img width="1154" alt="mac cutl ntlm" src="https://github.com/user-attachments/assets/43823c0d-08ab-447d-9443-0578ac87923f">

### I expected the following

I expect in macos, with same curl command, the proxy authentication should return '200 Connection established'.

### curl/libcurl version
MAC output for 'curl --version'
curl 8.7.1 (x86_64-apple-darwin23.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe UnixSockets

Windows output for 'curl --version'
curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-03-27
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

### operating system

MACOS 14.6.1 (23G93)

**Comment by icing** [comment]
That sounds tricky to analyze. Is 8.7.1 also the curl version on Windows that succeeds?

**Comment by lisalisal** [comment]
Yes, windows curl version is also '8.7.1'.

For MAC machine, I just join the domain, and logged with domain user, and I check the 'klist', there is valid credential. And didn't do other configurations on macos.  

Proxy server is in the same domain.

In this case, should curl do the proxy authentication successfully with following curl command ? I am afraid I miss some configurations on macos.
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-negotiate --proxy-user :  -v'
and
'curl  --proxy proxy-server-address:port https://connection-server-address:443  --proxy-ntlm --proxy-user :  -v'

**Comment by pkropachev** [comment]
@lisalisal, could you check logs of WinGate? Why does WinGate reject HTTP CONNECT (response to NTLM challenge) came from Mac? Perhaps logs contain some useful information.

**Comment by michael-o** [comment]
Man, Kerberos relies on hostnames and SPN, not IP addresses this is why it fails for you and falls back to NTLM. Fix your setup and macOS Heimdal will be able to obtain a service ticket for your HTTP (!) proxy server.

**Comment by bagder** [comment]
config problem, closing
