### ISSUE TITLE
The received CURLINFO_PRIVATE  instance of the curl instance is null in the callback of CURLMOPT_SOCKETFUNCTION, but CURLOPT_PRIVATE is configured just after the curl instance is

### ISSUE THREAD

**Issue by TheBetterSolution** [curl/curl#14767]
### I did this

1. Do the curl initialization work (Include the step to set the CURLMOPT_SOCKETFUNCTION).
`   multi = curl_multi_init();

  if (!multi)
  {
     return;
  }

  curl_multi_setopt(multi,
                    CURLMOPT_SOCKETFUNCTION,
                    SocketCurlCallback);
  curl_multi_setopt(multi,
                    CURLMOPT_SOCKETDATA,
                    NULL);
  curl_multi_setopt(multi,
                    CURLMOPT_TIMERFUNCTION,
                    TimerCurlCallback);
  curl_multi_setopt(multi,
                    CURLMOPT_TIMERDATA,
                    NULL);
  curl_multi_setopt(multi,
                    CURLMOPT_MAX_HOST_CONNECTIONS,
                    12L);`
3. Create the curl instance and do the initialization for it (include the step to set the CURLOPT_PRIVATE for it).
  ...
   request->curl = curl_easy_init();
   if (NULL == request->curl)
   {
      GOTO(0, abort);
   }
   ...
   curl_easy_setopt(request->curl, CURLOPT_HEADERFUNCTION, HeaderCallback);
   curl_easy_setopt(request->curl, CURLOPT_WRITEHEADER, request);
   curl_easy_setopt(request->curl, CURLOPT_READFUNCTION, ReadCallback);
   curl_easy_setopt(request->curl, CURLOPT_READDATA, request);
   curl_easy_setopt(request->curl, CURLOPT_WRITEFUNCTION, WriteCallback);
   curl_easy_setopt(request->curl, CURLOPT_WRITEDATA, request);
   curl_easy_setopt(request->curl, CURLOPT_IOCTLFUNCTION, IoctlCallback);
   curl_easy_setopt(request->curl, CURLOPT_IOCTLDATA, request);
   curl_easy_setopt(request->curl, CURLOPT_PRIVATE, request);
   curlMErr = curl_multi_add_handle(multi, request->curl);
   ...
5. Call curl_multi_socket_all:
       curlMErr = curl_multi_socket_all(multi,
                                                        &handles);
6. The CURLMOPT_SOCKETFUNCTION is called, but the value of CURLINFO_PRIVATE is null.
   ...
   curl_easy_getinfo(curl, CURLINFO_PRIVATE, (void *)&request);
   if (request) // request is null.
   {
      ...
   }

My question is why the pointer CURLOPT_PRIVATE already set for the curl instance can be retrieved **on curl 8.9.1? the 8.7.1 version and previous versions of curl never received null value for CURLOPT_PRIVATE.**

Thanks very much for everyone in curl team.

### I expected the following

The received the pointer of CURLOPT_PRIVATE isn't null.

### curl/libcurl version

curl 8.9.1

### operating system

Ubuntu 2204.

**Comment by icing** [comment]
I believe what you see is the effect of curl's new "graceful" connection shutdown. Here is what is happening:

* while your transfer (easy handle) is ongoing, the socket/timer callbacks get call with that easy handle and you can retrieve your private data.
* when the easy handle is done, the connection is placed into the connection pool and kept there for reuse.
* at some point in time, the connection will be discarded, e.g. shut down and closed. During this shutdown, the socket/timer callbacks will be invoked with an internal easy handle that does not have any PRIVATE data set.

Since the original easy handle is done and probably has been cleaned up, curl cannot make use of it or its settings any longer. It would be unsafe to return the PRIVATE data somehow, since it is unclear if it disappeared together with its easy handle or not.

If you want to associate data with a *connection* instead of a transfer, maybe CURLINFO_CONN_ID can help you.

**Comment by bagder** [comment]
The socket callback is called for the entire multi handle, so the exact `easy` handle that is in the first argument can appear a little... unpredictable to an application.

**Comment by TheBetterSolution** [comment]
> I believe what you see is the effect of curl's new "graceful" connection shutdown. Here is what is happening:
> 
>     * while your transfer (easy handle) is ongoing, the socket/timer callbacks get call with that easy handle and you can retrieve your private data.
> 
>     * when the easy handle is done, the connection is placed into the connection pool and kept there for reuse.
> 
>     * at some point in time, the connection will be discarded, e.g. shut down and closed. During this shutdown, the socket/timer callbacks will be invoked with an internal easy handle that does not have any PRIVATE data set.
> 
> 
> Since the original easy handle is done and probably has been cleaned up, curl cannot make use of it or its settings any longer. It would be unsafe to return the PRIVATE data somehow, since it is unclear if it disappeared together with its easy handle or not.
> 
> If you want to associate data with a _connection_ instead of a transfer, maybe CURLINFO_CONN_ID can help you.

Thanks a lot for your answer, @icing:
I compared the 8.9.1 with older version, curl 8.9.1 used the internal instance to call the callback:
https://github.com/curl/curl/blob/8ca60308398e42d77d140ebe5c3331c6e086d355/lib/conncache.c#L771
https://github.com/curl/curl/blob/8ca60308398e42d77d140ebe5c3331c6e086d355/lib/conncache.c#L1114
but 8.7.1 doesn't call the callback at the same context, so, the above codes just add more conditions to call the callback, and the conditions to call the callback on 8.7.1 are not changed in 8.9.1, so, I can just ignore calling when the curl parameter is the internal instance if I only need to keep same function of 8.7.1.

Thanks for everyone.

**Comment by TheBetterSolution** [comment]
> The socket callback is called for the entire multi handle, so the exact `easy` handle that is in the first argument can appear a little... unpredictable to an application.

Thanks a lot, @bagder .
