### ISSUE TITLE
Crash on NULL pointer dereference in 8.9.1

### ISSUE THREAD

**Issue by Trzik** [curl/curl#14779]
### I did this

Updated to curl 8.9.1 from 8.8.0, observed a rare crash on Windows 11 x64.

```
Curl_multiuse_state(Curl_easy * data, int bundlestate) Line 3753
Curl_alpn_set_negotiated(Curl_cfilter * cf, Curl_easy * data, const unsigned char * proto, unsigned __int64 proto_len) Line 2252
schannel_connect_step3(Curl_cfilter * cf, Curl_easy * data) Line 1757
schannel_connect_common(Curl_cfilter * cf, Curl_easy * data, bool nonblocking, bool * done) Line 1907
schannel_recv(Curl_cfilter * cf, Curl_easy * data, char * buf, unsigned __int64 len, CURLcode * err) Line 2303
schannel_shutdown(Curl_cfilter * cf, Curl_easy * data, bool send_shutdown, bool * done) Line 2574
ssl_cf_shutdown(Curl_cfilter * cf, Curl_easy * data, bool * done) Line 1771
Curl_conn_shutdown(Curl_easy * data, int sockindex, bool * done) Line 218
connc_run_conn_shutdown(Curl_easy * data, connectdata * conn, bool * done) Line 819
connc_discard_conn(conncache * connc, Curl_easy * last_data, connectdata * conn, bool aborted) Line 700
Curl_disconnect(Curl_easy * conn, connectdata *) Line 655
prune_dead_connections(Curl_easy *) Line 860
create_conn(Curl_easy * data, connectdata * * in_connect, bool * async) Line 3548
Curl_connect(Curl_easy * data, bool * asyncp, bool * protocol_done) Line 3787
multi_runsingle(Curl_multi * multi, curltime * nowp, Curl_easy * data) Line 1972
curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2740
easy_transfer(Curl_multi *) Line 676
easy_perform(Curl_easy * data, bool events) Line 771
```

Crash happens on `conn->bundle->multiuse = bundlestate;` because `conn->bundle` is `NULL`. The content of the `conn` structure looks otherwise valid to me.

The crash occurs rarely and there is no reliable repro case. It did not occur in version 8.8.0 at all.

### I expected the following

Not crashing, obviously.

### curl/libcurl version

curl 8.9.1

### operating system

Windows 11 (x64, 22631)

**Comment by icing** [comment]
Thanks for the report. This looks like a connection is being shut down before it has fully connected. But Schannel manages to finish the handshake during shutdown and tries to update a connection status that is no longer available. That would explain the rare occurance.

In the upcoming 8.10 release, we reworked this part in 1be704e17e70b626f89108f33b59bcdeb16f4b0e and there is no longer a `conn->bundle` and the setting of it is gone.

if you need a patch for 8.9.1, I'd just NULL check `conn->bundle` and avoid the setting of multiuse. It will do no harm in the shutdown phase.
