### ISSUE TITLE
I email my issues to curl-users-request@cool.haxx.se and nothing crickets

### ISSUE THREAD

**Issue by shaka25** [curl/curl#1477]
I email my issues to curl-users-request@cool.haxx.se and nothing crickets
### I expected the following
a response
### curl/libcurl version
latest version
[curl -V output]

### operating system
Ms server r2 2012

**Comment by bagder** [comment]
As described on https://cool.haxx.se/mailman/listinfo/curl-users

> To post a message to all the curl-users list members, send email to curl-users@cool.haxx.se. You must be subscribed before you post, as otherwise your mail will simply be silently discarded.
