### ISSUE TITLE
mbedtls_ssl_setup  There seems to be a memory leak

### ISSUE THREAD

**Issue by Zhangshoukui** [curl/curl#14774]
### I did this

The mbedtls_ssl_setup function is used to initialize the SSL context，

  ssl->in_buf = mbedtls_calloc(1, in_buf_len);
    if (ssl->in_buf == NULL) {
        MBEDTLS_SSL_DEBUG_MSG(1, ("alloc(%" MBEDTLS_PRINTF_SIZET " bytes) failed", in_buf_len));
        ret = MBEDTLS_ERR_SSL_ALLOC_FAILED;
        goto error;
        
  He has opened up a block of memory and should call mbedtls_free when he is finished using it.
  Are there any good solutions?

### I expected the following

Fix this memory leak

### curl/libcurl version

curl master branch

### operating system

20.04.1-Ubuntu

**Comment by dfandrich** [comment]
Are you reporting a memory leak in mbedtls? Because that's not curl code you
are showing. If so, then you need to report the issue to them instead. curl
calls mbedtls_ssl_free on the mbedtls_ssl_context in mbedtls_close as the
connection is torn down.

**Comment by Zhangshoukui** [comment]
got it. close this issue. thanks
