### ISSUE TITLE
POP3 LIST msg shows delay

### ISSUE THREAD

**Issue by ralfjunker** [curl/curl#14801]
### I did this

POP3 `LIST msg` (that is, with message-number present) still shows a delay as reported in https://github.com/curl/curl/issues/14677.

Reason seems that it is marked as multi-line whereas [RFC 1939](https://datatracker.ietf.org/doc/html/rfc1939) indicates it is not:

https://github.com/curl/curl/blob/56f90637ada4200a615f3a9fd9584650ecfeb343/lib/pop3.c#L218

If I change this to

```C
  { "LIST", 4, TRUE, FALSE },
```

the delay is gone.

### curl/libcurl version

Current GIT master.

### operating system

Windows 11.

**Comment by icing** [comment]
Thanks! You are correct. I made #14808 to fix the behaviour as suggested.
