### ISSUE TITLE
IPFS should be under enable- / disable- control

### ISSUE THREAD

**Issue by reardonia** [curl/curl#14824]
### I did this

Build 8.9.1 from source.

### I expected the following

Expect all protocols to be under enable/disable control.  IPFS is the ONLY protocol not under option control.

### curl/libcurl version

curl 8.4.0 and on.  Currently a problem in 8.9.1

### operating system

Debian testing (13+)

**Comment by bagder** [comment]
IPFS not really a "protocol" per se, it is a URL scheme that gets translated to HTTP(S). And you can disable HTTP(S) at will.

You can use `--proto` to deny specific schemes to be accepted in URLs, including `IPFS`.

**Comment by reardonia** [comment]
I get it... but it is still a new vector for attacks.

**Comment by bagder** [comment]
Still, adding code to allow disabling features is work that needs to be done and it needs to be maintained so we cannot add that ability for everything new we add.
