### ISSUE TITLE
Broken libcurl package.

### ISSUE THREAD

**Issue by ProfessorLongBeard** [curl/curl#14838]
### I did this

Tried to install and even manually build the package on Linux Mint 22. I get stuff like undefined references to curl_easy_init().

### I expected the following

I expected to be able to use this library, but kept running into this error:

In file included from /media/austin/Scratch/SpecialistBot/test.c:2:
/usr/local/include/curl/easy.h:41:1: error: unknown type name ‘CURL_EXTERN’
   41 | CURL_EXTERN CURL *curl_easy_init(void);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:41:18: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
   41 | CURL_EXTERN CURL *curl_easy_init(void);
      |                  ^
/usr/local/include/curl/easy.h:42:1: error: unknown type name ‘CURL_EXTERN’
   42 | CURL_EXTERN CURLcode curl_easy_setopt(CURL *curl, CURLoption option, ...);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:42:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_setopt’
   42 | CURL_EXTERN CURLcode curl_easy_setopt(CURL *curl, CURLoption option, ...);
      |                      ^~~~~~~~~~~~~~~~
/usr/local/include/curl/easy.h:43:1: error: unknown type name ‘CURL_EXTERN’
   43 | CURL_EXTERN CURLcode curl_easy_perform(CURL *curl);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:43:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_perform’
   43 | CURL_EXTERN CURLcode curl_easy_perform(CURL *curl);
      |                      ^~~~~~~~~~~~~~~~~
/usr/local/include/curl/easy.h:44:12: error: expected ‘;’ before ‘void’
   44 | CURL_EXTERN void curl_easy_cleanup(CURL *curl);
      |            ^~~~~
      |            ;
/usr/local/include/curl/easy.h:44:36: error: unknown type name ‘CURL’
   44 | CURL_EXTERN void curl_easy_cleanup(CURL *curl);
      |                                    ^~~~
/usr/local/include/curl/easy.h:59:1: error: unknown type name ‘CURL_EXTERN’
   59 | CURL_EXTERN CURLcode curl_easy_getinfo(CURL *curl, CURLINFO info, ...);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:59:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_getinfo’
   59 | CURL_EXTERN CURLcode curl_easy_getinfo(CURL *curl, CURLINFO info, ...);
      |                      ^~~~~~~~~~~~~~~~~
/usr/local/include/curl/easy.h:74:1: error: unknown type name ‘CURL_EXTERN’
   74 | CURL_EXTERN CURL *curl_easy_duphandle(CURL *curl);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:74:18: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
   74 | CURL_EXTERN CURL *curl_easy_duphandle(CURL *curl);
      |                  ^
/usr/local/include/curl/easy.h:87:12: error: expected ‘;’ before ‘void’
   87 | CURL_EXTERN void curl_easy_reset(CURL *curl);
      |            ^~~~~
      |            ;
/usr/local/include/curl/easy.h:87:34: error: unknown type name ‘CURL’
   87 | CURL_EXTERN void curl_easy_reset(CURL *curl);
      |                                  ^~~~
/usr/local/include/curl/easy.h:97:1: error: unknown type name ‘CURL_EXTERN’
   97 | CURL_EXTERN CURLcode curl_easy_recv(CURL *curl, void *buffer, size_t buflen,
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:97:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_recv’
   97 | CURL_EXTERN CURLcode curl_easy_recv(CURL *curl, void *buffer, size_t buflen,
      |                      ^~~~~~~~~~~~~~
/usr/local/include/curl/easy.h:108:1: error: unknown type name ‘CURL_EXTERN’
  108 | CURL_EXTERN CURLcode curl_easy_send(CURL *curl, const void *buffer,
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:108:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_send’
  108 | CURL_EXTERN CURLcode curl_easy_send(CURL *curl, const void *buffer,
      |                      ^~~~~~~~~~~~~~
/usr/local/include/curl/easy.h:119:1: error: unknown type name ‘CURL_EXTERN’
  119 | CURL_EXTERN CURLcode curl_easy_upkeep(CURL *curl);
      | ^~~~~~~~~~~
/usr/local/include/curl/easy.h:119:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_easy_upkeep’
  119 | CURL_EXTERN CURLcode curl_easy_upkeep(CURL *curl);
      |                      ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/sp_bot.dir/build.make:76: CMakeFiles/sp_bot.dir/test.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sp_bot.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Mind you this happens with a manual build and install or with the package shipped by Mint

### curl/libcurl version

curl-8.9.1

### operating system

Linux Mint 22

**Comment by bagder** [comment]
If you have a problem after you install a package from Linux mint, you should primarily direct your report to the ones providing that package.

If you build curl from a tarball provided by the curl project, then please tell us what you did to get the problem.

**Comment by ProfessorLongBeard** [comment]
I found out it has to do with CMake. Sorry to waste your time!
