### ISSUE TITLE
Docs header is not bold

### ISSUE THREAD

**Issue by styfle** [curl/curl#1484]
### I did this
1. Visit https://curl.haxx.se/docs/faq.html
2. Scroll to the very bottom

### I expected this
Bold header **7.4 Does PHP/CURL have dependencies?**

### I saw this
The header was not bold. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/229881/26007457/8b9910b0-370e-11e7-9d06-691a8ea03a83.png)

**Comment by bagder** [comment]
Thanks, this is fixed now and the site should update itself in a moment.

**Comment by styfle** [comment]
@bagder Wow that was quick, thanks!
