### ISSUE TITLE
libCurl 7.70.0 stuck in TLS handshake, 'certification(11)'

### ISSUE THREAD

**Issue by Mervyen** [curl/curl#14842]
### I did this

I  used libcurl **7.70.0** in my app on windows 11.
It will always stucks in TLS handshake, the curl log shows that there is no more action after 'certification(11)'.

The app code  about using libcurl is correct, the https request is ok in my mac, ios and android.

The curl log about TLS steps:
> 09-09 10:27:06.571  TLSv1.3 (OUT), TLS handshake, Client hello (1):
09-09 10:27:06.611 TLSv1.3 (IN), TLS handshake, Server hello (2):
09-09 10:27:06.611 TLSv1.2 (IN), TLS handshake, Certificate (11):

The wireshark capture. this shows the windows system do recive the server's `certificate`,`Server Key Exchange` and `Server Hello Done` but my app doesn't work correct, the app only deal with the `certificate` :
<img width="1989" alt="image" src="https://github.com/user-attachments/assets/8d426968-684f-46ec-9e36-be8d2dd5d73d">

the action I have taken:
1、reset the winsock , use `netsh winsock reset` .this doesn't work for me
2、reset the mtu != 1500, use `netsh interface ipv4 set subinterface "Ethernet" mtu=1400 store=persistent`. this doesn't work for me

pls let me know if you need more infos

### I expected the following

success in https TLS handshake

### curl/libcurl version

curl 7.70.0

### operating system

windows 11

**Comment by bagder** [comment]
7.70.0 is over 4 years old, I would recommend you at least try a recent version first before spending too much time on this. And if it still reproduces with the latest curl, it has much better logging abilities that can help us track down what is going on.

You did not mention with TLS library and version you use.

**Comment by Mervyen** [comment]
> 7.70.0 is over 4 years old, I would recommend you at least try a recent version first before spending too much time on this. And if it still reproduces with the latest curl, it has much better logging abilities that can help us track down what is going on.
> 
> You did not mention with TLS library and version you use.

sorry I also want to update the version. But I have to use the specific `7.70.0` version for some reason. So I have to solve this. 
Maybe you can give me a rough idea of ​​how to locate this problem?  thx!!! 

I use OpenSSL/1.1.1k

**Comment by pkropachev** [comment]
Just to check with the latest released version 8.9.1 to make sure that your scenario works well.
If all is ok then schedule migration to newer version. I believe nobody will try to find out problems in so old version.

**Comment by bagder** [comment]
> Maybe you can give me a rough idea of ​​how to locate this problem?

1. Run the problematic case in a debugger. See where it hangs. Figure out why it hangs there. Adjust the code. Repeat and retry.

or

2. If the latest version works, git bisect your way to the commit that fixed the behavior

**Comment by Mervyen** [comment]
> Just to check with the latest released version 8.9.1 to make sure that your scenario works well. If all is ok then schedule migration to newer version. I believe nobody will try to find out problems in so old version.

OK,thx I will try to update.

**Comment by Mervyen** [comment]
> 2\. If the latest version works, git bisect your way to the commit that fixed the behavior

thx, I will try to do this.  Maybe I think this issue can be closed. if there is any new discover I will still write on this issue.
thx again for your reply.
