### ISSUE TITLE
curl v8.10.0 fail to compile

### ISSUE THREAD

**Issue by Keitagit-kun** [curl/curl#14866]
### I did this

I'm compiling curl v8.10.0 (+ nghttp2 v1.63.0, nghttp3 v1.5.0, OpenSSL v3.3.2) with cmake v3.12.4 & mingw-w64 x86_64-7.2.0-win32-seh-rt_v5-rev1 but get errors:
```
Scanning dependencies of target libcurl_object
[  0%] Building C object lib/CMakeFiles/libcurl_object.dir/altsvc.c.obj
[  1%] Building C object lib/CMakeFiles/libcurl_object.dir/amigaos.c.obj
[...cut most `lib` source for brevity...]
[ 95%] Building C object lib/CMakeFiles/libcurl_object.dir/vquic/curl_ngtcp2.c.obj
[ 95%] Building C object lib/CMakeFiles/libcurl_object.dir/vquic/curl_osslq.c.obj
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:285:23: error: field 'tls' has incomplete type
   struct curl_tls_ctx tls;
                       ^~~
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c: In function 'cf_osslq_ctx_close':
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:331:3: error: implicit declaration of function 'Curl_vquic_tls_cleanup'; did you mean 'Curl_client_cleanup'? [-Werror=implicit-function-declaration]
   Curl_vquic_tls_cleanup(&ctx->tls);
   ^~~~~~~~~~~~~~~~~~~~~~
   Curl_client_cleanup
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:331:3: warning: nested extern declaration of 'Curl_vquic_tls_cleanup' [-Wnested-externs]
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c: In function 'cf_osslq_verify_peer':
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:568:10: error: implicit declaration of function 'Curl_vquic_tls_verify_peer'; did you mean 'cf_osslq_verify_peer'? [-Werror=implicit-function-declaration]
   return Curl_vquic_tls_verify_peer(&ctx->tls, cf, data, &ctx->peer);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          cf_osslq_verify_peer
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:568:10: warning: nested extern declaration of 'Curl_vquic_tls_verify_peer' [-Wnested-externs]
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c: In function 'cf_osslq_ctx_start':
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:1171:12: error: implicit declaration of function 'Curl_vquic_tls_init'; did you mean 'Curl_waitfds_init'? [-Werror=implicit-function-declaration]
   result = Curl_vquic_tls_init(&ctx->tls, cf, data, &ctx->peer,
            ^~~~~~~~~~~~~~~~~~~
            Curl_waitfds_init
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:1171:12: warning: nested extern declaration of 'Curl_vquic_tls_init' [-Wnested-externs]
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c: In function 'cf_osslq_connect':
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:1734:16: error: implicit declaration of function 'Curl_vquic_tls_before_recv'; did you mean 'Curl_cf_def_recv'? [-Werror=implicit-function-declaration]
       result = Curl_vquic_tls_before_recv(&ctx->tls, cf, data);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                Curl_cf_def_recv
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:1734:16: warning: nested extern declaration of 'Curl_vquic_tls_before_recv' [-Wnested-externs]
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c: In function 'cf_osslq_verify_peer':
C:\Temp\curl-8.10.0-OpenSSL3.3\curl-8.10.0\lib\vquic\curl_osslq.c:569:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
cc1.exe: some warnings being treated as errors
mingw32-make[2]: *** [lib\CMakeFiles\libcurl_object.dir\build.make:2331: lib/CMakeFiles/libcurl_object.dir/vquic/curl_osslq.c.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:124: lib/CMakeFiles/libcurl_object.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2
```

### I expected the following

no errors - curl v8.9.1 compiled OK

### curl/libcurl version

libcurl v8.10.0

### operating system

Windows XP x64

**Comment by vszakats** [comment]
Can you post the the cmake configure output for the successful 8.9.1 build vs. 8.10.0? And cmake configure options?

**Comment by Keitagit-kun** [comment]
cmake configure options:
`BUILD_STATIC_LIBS		ON
CURL_BROTLI			ON
CURL_ENABLE_SSL			ON
CURL_LTO			ON
CURL_STATIC_CRT			ON
CURL_USE_OPENSSL		ON
CURL_WINDOWS_SSPI		ON
CURL_ZLIB			AUTO
CURL_ZSTD			ON
ENABLE_ARES			ON
ENABLE_UNICODE			ON
ENABLE_UNIX_SOCKETS		ON
PICKY_COMPILER			ON
USE_NGHTTP2			ON
USE_OPENSSL_QUIC		ON
USE_WIN32_LDAP			ON

all others not checked/default`

curl v8.9.1 cmake output:

`Using CMake version 3.12.4
The C compiler identification is GNU 7.2.0
Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-win32-seh-rt_v5-rev1/mingw64/bin/gcc.exe
Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-win32-seh-rt_v5-rev1/mingw64/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
curl version=[8.9.1]
Performing Test OPT_Wdouble_promotion
Performing Test OPT_Wdouble_promotion - Success
Performing Test OPT_Wenum_conversion
Performing Test OPT_Wenum_conversion - Failed
Performing Test OPT_Wpragmas
Performing Test OPT_Wpragmas - Success
Performing Test OPT_Wunused_const_variable
Performing Test OPT_Wunused_const_variable - Success
Picky compiler options: -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wsign-conversion -Wno-error=sign-conversion -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wstrict-aliasing=3 -Wtrampolines -Wno-pedantic-ms-format -Wformat=2 -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Wdouble-promotion -Wpragmas -Wunused-const-variable
Found CARES: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libcares.a  
Found Perl: E:/ProgrammingTools/Perl_x64_Strawberry/perl/bin/perl.exe (found version "5.28.1") 
Found OpenSSL: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libcrypto.dll.a   
Looking for OPENSSL_IS_BORINGSSL
Looking for OPENSSL_IS_BORINGSSL - not found
Looking for OPENSSL_IS_AWSLC
Looking for OPENSSL_IS_AWSLC - not found
Found ZLIB: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libz.a (found version "1.3.1") 
Found Brotli: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libbrotlidec.a  
Found Zstd: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libzstd.a (found version "1.5.6") 
Looking for SSL_set0_wbio
Looking for SSL_set0_wbio - found
Looking for SSL_CTX_set_srp_username
Looking for SSL_CTX_set_srp_username - found
Found NGHTTP2: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libnghttp2.a  
Found OpenSSL: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libcrypto.dll.a (Required is at least version "3.3.0")  
Found NGHTTP3: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libnghttp3.a  
Performing Test HAVE_WIN32_WINNT
Performing Test HAVE_WIN32_WINNT - Success
Found _WIN32_WINNT=0x0502
Looking for 13 include files winsock2.h, ..., stdatomic.h
Looking for 13 include files winsock2.h, ..., stdatomic.h - found
Looking for stdint.h
Looking for stdint.h - found
Check size of size_t
Check size of size_t - done
Check size of ssize_t
Check size of ssize_t - done
Check size of long long
Check size of long long - done
Check size of long
Check size of long - done
Check size of int
Check size of int - done
Check size of __int64
Check size of __int64 - done
Check size of time_t
Check size of time_t - done
Looking for strtok_r
Looking for strtok_r - found
Check size of ADDRESS_FAMILY
Check size of ADDRESS_FAMILY - done
Performing Test HAVE_FILE_OFFSET_BITS
Performing Test HAVE_FILE_OFFSET_BITS - Success
Performing Test HAVE_ATOMIC
Performing Test HAVE_ATOMIC - Success
Check size of off_t
Check size of off_t - done
Check size of curl_off_t
Check size of curl_off_t - done
Check size of curl_socket_t
Check size of curl_socket_t - done
LTO supported and enabled
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets alt-svc brotli libz threadsafe zstd
Enabled SSL backends: OpenSSL
Configuring done


Using CMake version 3.12.4
curl version=[8.9.1]
Picky compiler options: -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wsign-conversion -Wno-error=sign-conversion -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wstrict-aliasing=3 -Wtrampolines -Wno-pedantic-ms-format -Wformat=2 -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Wdouble-promotion -Wpragmas -Wunused-const-variable
Found OpenSSL: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libcrypto.dll.a   
Found OpenSSL: C:/Temp/curl-8.9.1-OpenSSL3.3/deps/lib/libcrypto.dll.a (Required is at least version "3.3.0")  
Performing Test HAVE_WIN32_WINNT
Performing Test HAVE_WIN32_WINNT - Success
Found _WIN32_WINNT=0x0502
LTO supported and enabled
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets alt-svc brotli libz threadsafe zstd
Enabled SSL backends: OpenSSL
Configuring done
Generating done
`

curl v8.10.0 cmake output:

`Using CMake version 3.12.4
The C compiler identification is GNU 7.2.0
Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-win32-seh-rt_v5-rev1/mingw64/bin/gcc.exe
Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-win32-seh-rt_v5-rev1/mingw64/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
CMake platform flags: WIN32 GCC MINGW
curl version=[8.10.0]
Performing Test HAVE_WIN32_WINNT
Performing Test HAVE_WIN32_WINNT - Success
Found _WIN32_WINNT=0x0502
Performing Test OPT_Wdouble_promotion
Performing Test OPT_Wdouble_promotion - Success
Performing Test OPT_Wenum_conversion
Performing Test OPT_Wenum_conversion - Failed
Performing Test OPT_Wpragmas
Performing Test OPT_Wpragmas - Success
Performing Test OPT_Wunused_const_variable
Performing Test OPT_Wunused_const_variable - Success
Picky compiler options: -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wsign-conversion -Wno-error=sign-conversion -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wstrict-aliasing=3 -Wtrampolines -Wno-pedantic-ms-format -Wformat=2 -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Walloc-zero -Wduplicated-branches -Wno-format-overflow -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Wdouble-promotion -Wpragmas -Wunused-const-variable
Found Cares: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/include (found version "1.17.2") 
Found Perl: E:/ProgrammingTools/Perl_x64_Strawberry/perl/bin/perl.exe (found version "5.28.1") 
Found ZLIB: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/lib/libz.a (found version "1.3.1") 
Found Brotli: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/include  
Found Zstd: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/include (found version "1.5.6") 
Found NGHTTP2: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/include (found version "1.63.0") 
Found OpenSSL: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/lib/libcrypto.dll.a (Required is at least version "3.3.0")  
Found NGHTTP3: C:/Temp/curl-8.10.0-OpenSSL3.3/deps/include (found version "1.5.0") 
Looking for 14 include files winsock2.h, ..., stdatomic.h
Looking for 14 include files winsock2.h, ..., stdatomic.h - found
Looking for stdint.h
Looking for stdint.h - found
Check size of size_t
Check size of size_t - done
Check size of ssize_t
Check size of ssize_t - done
Check size of long long
Check size of long long - done
Check size of long
Check size of long - done
Check size of int
Check size of int - done
Check size of __int64
Check size of __int64 - done
Check size of time_t
Check size of time_t - done
Looking for strtok_r
Looking for strtok_r - found
Check size of ADDRESS_FAMILY
Check size of ADDRESS_FAMILY - done
Performing Test HAVE_FILE_OFFSET_BITS
Performing Test HAVE_FILE_OFFSET_BITS - Success
Performing Test HAVE_ATOMIC
Performing Test HAVE_ATOMIC - Success
Check size of off_t
Check size of off_t - done
Check size of curl_off_t
Check size of curl_off_t - done
Check size of curl_socket_t
Check size of curl_socket_t - done
LTO supported and enabled
Protocols: dict file ftp gopher http imap ipfs ipns ldap ldaps mqtt pop3 rtsp smb smtp telnet tftp
Features: AsynchDNS HTTP2 HTTP3 IPv6 Kerberos Largefile NTLM SPNEGO SSPI Unicode UnixSockets alt-svc brotli libz threadsafe zstd
Enabled SSL backends: 
Configuring done

Using CMake version 3.12.4
CMake platform flags: WIN32 GCC MINGW
curl version=[8.10.0]
Performing Test HAVE_WIN32_WINNT
Performing Test HAVE_WIN32_WINNT - Success
Found _WIN32_WINNT=0x0502
Picky compiler options: -Werror-implicit-function-declaration -W -Wall -pedantic -Wbad-function-cast -Wconversion -Winline -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-long-long -Wno-multichar -Wpointer-arith -Wshadow -Wsign-compare -Wundef -Wunused -Wwrite-strings -Waddress -Wattributes -Wcast-align -Wdeclaration-after-statement -Wdiv-by-zero -Wempty-body -Wendif-labels -Wfloat-equal -Wformat-security -Wignored-qualifiers -Wmissing-field-initializers -Wmissing-noreturn -Wno-format-nonliteral -Wno-system-headers -Wold-style-definition -Wredundant-decls -Wsign-conversion -Wno-error=sign-conversion -Wstrict-prototypes -Wtype-limits -Wunreachable-code -Wunused-parameter -Wvla -Wclobbered -Wmissing-parameter-type -Wold-style-declaration -Wstrict-aliasing=3 -Wtrampolines -Wno-pedantic-ms-format -Wformat=2 -Warray-bounds=2 -ftree-vrp -Wduplicated-cond -Wnull-dereference -fdelete-null-pointer-checks -Wshift-negative-value -Wshift-overflow=2 -Walloc-zero -Wduplicated-branches -Wno-format-overflow -Wformat-truncation=2 -Wimplicit-fallthrough -Wrestrict -Wdouble-promotion -Wpragmas -Wunused-const-variable
LTO supported and enabled
Protocols: dict file ftp gopher http imap ipfs ipns ldap ldaps mqtt pop3 rtsp smb smtp telnet tftp
Features: AsynchDNS HTTP2 HTTP3 IPv6 Kerberos Largefile NTLM SPNEGO SSPI Unicode UnixSockets alt-svc brotli libz threadsafe zstd
Enabled SSL backends: 
Configuring done
Generating done
`

**Comment by Keitagit-kun** [comment]
also - when configuring curl 8.10.0 - cmake d'not show found include libs paths

**Comment by vszakats** [comment]
Thanks!

> also - when configuring curl 8.10.0 - cmake d'not show found include libs paths

Indeed, though it's unrelated. I can see now it doesn't match the build-ins OpenSSL/ZLIB detection modules. I may revisit this, it's part cosmetics but not entirely.

What's odd is that with 8.10.0 there is no attempt to detect `OPENSSL_IS_BORINGSSL` and `OPENSSL_IS_AWSLC`. I cannot see any obvious update that may make such difference.

The outcome resembles header path confusion, where OpenSSL 3.3.x is detected, but then an earlier version gets picked up at compile-time.

Would you mind posting the good and bad `CMakeCache.txt` files?

**Comment by Keitagit-kun** [comment]
[8.9.1 CMakeLists.txt](https://github.com/user-attachments/files/16970182/8.9.1.CMakeLists.txt)
[8.10.0 CMakeLists.txt](https://github.com/user-attachments/files/16970194/8.10.0.CMakeLists.txt)

**Comment by Keitagit-kun** [comment]
sorry wrong files

[8.9.1 CMakeCache.txt](https://github.com/user-attachments/files/16970353/8.9.1.CMakeCache.txt)
[8.10.0 CMakeCache.txt](https://github.com/user-attachments/files/16970356/8.10.0.CMakeCache.txt)

**Comment by vszakats** [comment]
More odd: With 8.10.0 the initial OpenSSL detection is _not_ attempted (only at a later stage via NGHTTP3, that's why BoringSSL/AWC-LC detection is missing).

**Comment by vszakats** [comment]
> 8.10.0 CMakeCache.txt

In this case `CURL_USE_OPENSSL` is disabled. Are you sure it's enabled on the command-line?

**Comment by Keitagit-kun** [comment]
i re-checked - and yes - `CURL_USE_OPENSSL` was disabled after cmake configure. But why? In case 8.9.1 it's enabled and it's dependent option...
after enabling `CURL_USE_OPENSSL` compilation was success

ah! it' because of:
`set(_openssl_default ON)
if(WIN32 OR CURL_USE_SECTRANSP OR CURL_USE_SCHANNEL OR CURL_USE_MBEDTLS OR CURL_USE_WOLFSSL)
  set(_openssl_default OFF)<<<<<<<<<<<<<<<<<<< 
endif()
cmake_dependent_option(CURL_USE_OPENSSL "Enable OpenSSL for SSL/TLS" ${_openssl_default} CURL_ENABLE_SSL OFF)`

I'm under win, but use openSSL so my script changet `set(openssl_default OFF)` to `set(openssl_default ON)` but variable `openssl_default `was renamed to `_openssl_default` and regexp failed.

**Comment by vszakats** [comment]
Oh, okay. Instead of patching it would also work to just pass `CURL_USE_OPENSSL=ON`, wouldn't it?

I've opened a PR to make sure OpenSSL is enabled and detected when using OpenSSL QUIC. This would likely avoid this. → #14872

**Comment by vszakats** [comment]
That PR is merged, so in the event of a failed local patch or just simplify missing to enable OpenSSL, QUIC will stay and a warning shown.

**Comment by bagder** [comment]
Case closed. OpenSSL needs to be explicitly enabled.
