### ISSUE TITLE
curl_url_set() chokes on mailto: URIs

### ISSUE THREAD

**Issue by ralfjunker** [curl/curl#14871]
### I did this

```C
curl_url_set(URL, CURLUPART_URL, "mailto:Joe@example.com", CURLU_NON_SUPPORT_SCHEME);
```

returns `CURLUE_BAD_SLASHES`.

### I expected the following

I expect the code above to accept the URI and return `CURLUE_OK`.

Rationale: `mailto:...` is a valid URI according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986).

The `CURLUE_BAD_SLASHES` returned above also causes [the minimal reference resolution example](https://datatracker.ietf.org/doc/html/rfc3986#section-5.4.1) to fail:

`"g:h"           =  "g:h"`

### curl/libcurl version

Current GIT.

### operating system

OS independent.

**Comment by dfandrich** [comment]
I suspect you'll also need CURLU_NO_AUTHORITY set since mailto: URLs don't have hostnames as such.

**Comment by bagder** [comment]
curl only supports URLs with :// separators. It means it does not support mailto.

**Comment by bagder** [comment]
This is also documented in the `curl_url_set()` manpage.

**Comment by ralfjunker** [comment]
Thanks for the explanation!
