### ISSUE TITLE
Compile libCurl with CURL_DISABLE_CRYPTO_AUTH and USE_NTLM causes curl_sasl.c to fail to compile

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#1487]
### I did this

Defined both CURL_DISABLE_CRYPTO_AUTH and USE_NTLM.

### I expected the following

A successful compilation. Instead I got an error saying "serverdata" was undefined (because it was being "defined" out).

### curl/libcurl version

7.54.0

### operating system

Windows, Visual Studio 2017.

### Solution:

In curl_sasl.c, around line 417-ish (in Curl_sasl_continue() ), move `char *serverdata;` outside of the the `#if !defined(CURL_DISABLE_CRYPTO_AUTH)` define.

Or, alternatively, replace this:

```
#if !defined(CURL_DISABLE_CRYPTO_AUTH)
  char *serverdata;
  char *chlg = NULL;
  size_t chlglen = 0;
#endif
```

With this:

```
#if !defined(CURL_DISABLE_CRYPTO_AUTH) || defined(USE_NTLM) || defined(USE_KERBEROS5)
  char *serverdata;
#endif

#if !defined(CURL_DISABLE_CRYPTO_AUTH)
  char *chlg = NULL;
  size_t chlglen = 0;
#endif
```

**Comment by bagder** [comment]
Ah yes, thanks! A third alternative would be to declare `serverdata` in every instance. I'll do the first version since it makes the code nicer than the second, and the "unused variable" warning it may create for some combination of disabled features is still harmless.

**Comment by bagder** [comment]
Thanks!
