### ISSUE TITLE
curl_multi is broken in libcurl 8.10.0 - PHPs curl_multi_exec still_running argument is now always non-zero, causing endless loop in reading servers response

### ISSUE THREAD

**Issue by vityank** [curl/curl#14898]
### I did this

```
<?php


// start testing
  echo "*** Testing curl_exec() : basic functionality ***\n";

  $url = "http://127.0.0.1:32550/get.inc?test=get";
  //$url = "http:/127.0.0.1/index.php";
  echo "Preparing handles array...\n";
  $chs = array(
    0 => curl_init(),
    1 => curl_init(),
    2 => curl_init(),
  );

  echo "Starting ob...\n";
  ob_start(); // start output buffering

  $options = array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => $url,
  );

  echo "Setting options...\n";
  curl_setopt_array($chs[0], $options); //set the options
  curl_setopt_array($chs[1], $options); //set the options
  curl_setopt_array($chs[2], $options); //set the options

  echo "About to call multi init...\n";
  $mh = curl_multi_init();

  // add handlers
  echo "Adding handlers...\n";
  curl_multi_add_handle($mh, $chs[0]);
  curl_multi_add_handle($mh, $chs[1]);
  curl_multi_add_handle($mh, $chs[2]);

  $running=null;
  //execute the handles
  echo "Entering loop...\n";
  do {
    $vst = curl_multi_exec($mh, $running);
    echo "cURL Code is: $vst\n";
  } while ($running > 0);

  echo "Pulling content...\n";
  $curl_content = '';
  $curl_content .= curl_multi_getcontent($chs[0]);
  $curl_content .= curl_multi_getcontent($chs[1]);
  $curl_content .= curl_multi_getcontent($chs[2]);

  //close the handles
  echo "Cleaning up...\n";
  curl_multi_remove_handle($mh, $chs[0]);
  curl_multi_remove_handle($mh, $chs[1]);
  curl_multi_remove_handle($mh, $chs[2]);
  echo "Closing multi handle...\n";
  curl_multi_close($mh);

  var_dump( $curl_content );
```

### I expected the following

*** Testing curl_exec() : basic functionality ***
Preparing handles array...
Starting ob...
Setting options...
About to call multi init...
Adding handlers...
Entering loop...
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
cURL Code is: 0
Pulling content...
Cleaning up...
Closing multi handle...
string(75) "Hello World!
Hello World!Hello World!
Hello World!Hello World!
Hello World!"

### curl/libcurl version

curl 8.10.0

### operating system

RHEL 9.4

**Comment by vityank** [comment]
I've completed the bisecting. The commit which causes this regression is the large one here:
https://github.com/curl/curl/commit/a58b50fca6eb543896a7c1cb05bb21aa1fc49251

**Comment by bagder** [comment]
I created the following C version of this code, using public URLs, but I cannot make it reproduce. Not with 8.10.0 and not with current git master,

~~~c
#include <stdio.h>
#include <string.h>
#include <curl/curl.h>

int main(void)
{
  CURL *http_handle;
  CURL *http_handle2;
  CURL *http_handle3;
  CURLM *multi_handle;

  int still_running = 1; /* keep number of running handles */

  http_handle = curl_easy_init();
  http_handle2 = curl_easy_init();
  http_handle3 = curl_easy_init();

  curl_easy_setopt(http_handle, CURLOPT_URL, "https://www.example.com/");
  curl_easy_setopt(http_handle3, CURLOPT_URL, "https://www.example.org/");
  curl_easy_setopt(http_handle2, CURLOPT_URL, "https://curl.se/");

  multi_handle = curl_multi_init();

  curl_multi_add_handle(multi_handle, http_handle);
  curl_multi_add_handle(multi_handle, http_handle2);
  curl_multi_add_handle(multi_handle, http_handle3);

  while(still_running) {
    CURLMsg *msg;
    int queued;
    CURLMcode mc = curl_multi_perform(multi_handle, &still_running);

    if(still_running)
      /* wait for activity, timeout or "nothing" */
      mc = curl_multi_poll(multi_handle, NULL, 0, 1000, NULL);

    if(mc)
      break;

    do {
      msg = curl_multi_info_read(multi_handle, &queued);
      if(msg) {
        if(msg->msg == CURLMSG_DONE) {
          fprintf(stderr, "Transfer completed\n");
        }
      }
    } while(msg);
  }

  curl_multi_remove_handle(multi_handle, http_handle);
  curl_multi_remove_handle(multi_handle, http_handle2);
  curl_multi_remove_handle(multi_handle, http_handle3);

  curl_multi_cleanup(multi_handle);

  curl_easy_cleanup(http_handle);
  curl_easy_cleanup(http_handle2);
  curl_easy_cleanup(http_handle3);

  return 0;
}

**Comment by icing** [comment]
Same here. Is it possible to get php to collect trace information? It would be nice to see if all transfers actually get the server's responses or not.

**Comment by vityank** [comment]
Hi, I've changed the @bagder C test a little to be more similar to PHP's code(Just w/o the content storing for simplicity).
Also I use HTTP without encryption - This removes the possible vector of SSL libraries influence(My build uses GNUTls).
Also (Like @icing noticed) it uses classic HTTP 1.1 - So as simple as possible(And this is used by original PHP test as well).
This changed version reproduces the issue(8.10 freezes, Older version works just fine.)
So it has something to do with curl_multi_perform not progressing on its own(without curl_multi_poll - which PHP's code doesn't call)
```
#include <stdio.h>
#include <string.h>
#include <curl/curl.h>

static size_t curl_write(char *data, size_t size, size_t nmemb, void *clientp)
{
  /* Let's do nothing for simplicity */
  return size*nmemb;
}

int main(void)
{
  CURL *http_handle;
  CURL *http_handle2;
  CURL *http_handle3;
  CURLM *multi_handle;

  int still_running = 0; /* keep number of running handles */

  http_handle = curl_easy_init();
  http_handle2 = curl_easy_init();
  http_handle3 = curl_easy_init();

  curl_easy_setopt(http_handle, CURLOPT_URL, "http://curl.se/");
  curl_easy_setopt(http_handle3, CURLOPT_URL, "http://curl.se/");
  curl_easy_setopt(http_handle2, CURLOPT_URL, "http://curl.se/");

  curl_easy_setopt(http_handle, CURLOPT_WRITEFUNCTION, curl_write);

  multi_handle = curl_multi_init();

  curl_multi_add_handle(multi_handle, http_handle);
  curl_multi_add_handle(multi_handle, http_handle2);
  curl_multi_add_handle(multi_handle, http_handle3);

  do {
    CURLMsg *msg;
    int queued;
    CURLMcode mc = curl_multi_perform(multi_handle, &still_running);
  } while (still_running > 0);

  curl_multi_remove_handle(multi_handle, http_handle);
  curl_multi_remove_handle(multi_handle, http_handle2);
  curl_multi_remove_handle(multi_handle, http_handle3);

  curl_multi_cleanup(multi_handle);

  curl_easy_cleanup(http_handle);
  curl_easy_cleanup(http_handle2);
  curl_easy_cleanup(http_handle3);

  printf("Test finished - We did not freeze\n");
  return 0;
}
```

**Comment by icing** [comment]
@vityank you mean you see the problem with this C sample?

**Comment by vityank** [comment]
@icing , yes, with altered one in my previous post. @bagder 's original one did not reproduce.

**Comment by bagder** [comment]
Reproduces. It seems to require to not use the curl_multi_poll() for it to reproduce, which of course is a bit unwise (but common in PHP programs) and should still work

**Comment by icing** [comment]
Found the problem. Should be fixed by #14901.

**Comment by vityank** [comment]
Hi, @icing.
I've just checked 8.10 with #14901 applied on top - My PHP test and several PHP's full cURL tests, which there failing before are now passing just fine.

**Comment by bagder** [comment]
@vityank an advice though (unrelated to this issue): you want a call to **curl_multi_select** in there, as your example code will busy-loop and use 100% CPU during the entire transfer otherwise.

**Comment by vityank** [comment]
Thanks for advice @bagder,
Actually in our own code we do(And even have extra safety sleeps as mechanism intended for RPC-ing): :)
```
$isActive = true;
if (curl_multi_select($mh) != -1)
	$mrc = curl_multi_exec($mh, $isActive);
if ($isActive)
	usleep(self::WAIT_BETWEEN_PROBES);
```

The sample here resembles PHP's official testsuite and those have their own mini-server embeeded with short responses, so I don't think they care about CPU spikes during execution of those(And they indeed also have CPU and IO intensive tests there).

**Comment by bagder** [comment]
A usleep is an inefficient and bad replacement. But I'll stop now.
