### ISSUE TITLE
If --enabe-ares configure option is given, --dns-servers must be passed to cli, otherwise always report curl: (6) Could not resolve host: xxx

### ISSUE THREAD

**Issue by leleliu008** [curl/curl#14891]
### I did this

If --enabe-ares configure option is given, --dns-servers must be passed to cli, otherwise always report curl: (6) Could not resolve host: xxx

I create a github actions https://github.com/fpliu1214/test/actions/runs/10841274207 , if you want to see build process logs.

my strace result files:

[strace-curl--dns-servers-8.8.8.8.txt](https://github.com/user-attachments/files/16987931/strace-curl--dns-servers-8.8.8.8.txt)
[strace-curl.txt](https://github.com/user-attachments/files/16987932/strace-curl.txt)
[strace-wget.txt](https://github.com/user-attachments/files/16987933/strace-wget.txt)

I found someone report a similar issue: https://github.com/curl/curl/issues/9647

My case is curl runs on Android [Termux](https://termux.dev/) 
My Android device is android-12

I also built wget and linked libcares, it works without --dns-servers=

### I expected the following

curl should work if --dns-servers argument is not given.

### curl/libcurl version

WARNING: this libcurl is Debug-enabled, do not use in production

curl 8.10.0 (aarch64-unknown-linux-android) libcurl/8.10.0 OpenSSL/3.3.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 c-ares/1.31.0 nghttp2/1.61.0
Release-Date: 2024-09-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP TrackMemory UnixSockets zstd

### operating system

Linux localhost 4.19.157-perf-g403d33afcbbf-dirty #1 SMP PREEMPT Wed Mar 1 16:59:02 CST 2023 aarch64 Android

**Comment by dfandrich** [comment]
When you build c-ares for Android, is it being configured to get its DNS
servers from the proper Android location? I don't recall if that happens
automatically. Do the c-ares test program work correctly on Android? In any
case, this is unlikely to be a curl issue.

**Comment by leleliu008** [comment]
wget also used libcares. wget works fine.

**Comment by leleliu008** [comment]
I try to build for Linux and macOS, They all work well, only Android don't work if --dns-servers is not given.

**Comment by bagder** [comment]
libcurl inits and uses c-ares as documented and identically on all platforms. If there's a problem with c-ares on Android, then that issue is probably inside c-ares, not curl.

**Comment by leleliu008** [comment]
@bagder This is not a bug in c-ares but a limitation for Android 8 and later. see https://github.com/c-ares/c-ares/issues/964

I have a suggestion:

At the moment, curl determine whether user want to use c-ares to query ip address by `--enable-ares` configure option.

IMO, `--enable-ares` just enable this feature, but whether to use c-ares to query ip address should be determined by checking if user set `CURLOPT_DNS_SERVERS` ,  if user set `CURLOPT_DNS_SERVERS` , it means user want to query ip address using c-ares, otherwise, they want to use system's getaddrinfo function to query.
