### ISSUE TITLE
Xonotic hangs while downloading map data using curl 8.10

### ISSUE THREAD

**Issue by janp20** [curl/curl#14903]
### I did this

selected a xonotic server

### I expected the following

download the current map data

### curl/libcurl version

curl 8.10, I downgraded to 8.9.1 and it worked.

### operating system

Arch Linux latest

**Comment by bagder** [comment]
You need to tell us **a lot more** for this to be actionable.

Lots of specifics, protocols, versions and what are you doing etc.

**Comment by janp20** [comment]
Hi, I am using xonotic 0.8.6-2 on archlinux (hence fully updated). It's an online FPS game, like Quake. When you connect to a site the current map is downloaded using curl (no idea about how xonotic calls curl). Ultil two days ago everithing worked well. Yesterday I noticed that the download hangs and that no map file is downloaded. I discovered that in the meantime curl was upgraded to version 8.10, then I downgraded curl to v 8.9.1, and it worked again. This is all what I know. Maybe curl changed the way is has to be called and the problem is on the xonotic side, but since normally, the compatibility is the first thing, I concluded that the problem was on curl. Thank you.

**Comment by icing** [comment]
I wonder if people see the effect of #14898 too on their systems. @janp20 do you see a busy cpu core while the download is not progressing?

**Comment by janp20** [comment]
I upgraded again to 8.10, the behavior is described on the following screenshot.  I.e., instead of the amount of Kb to be downloaded there are 3 question marks. The download hangs until maybe a timeout happens and the game goes ahead but it is incomplete (black background normally). I didn't notice any extra load on the machine. Thank you.

![image](https://github.com/user-attachments/assets/d2f8aa2a-3daf-4c72-b9d1-1e38a5948bc9)

**Comment by bones-was-here** [comment]
DarkPlaces engine maintainer here,  
I think this will be the same bug as #14898 and hopefully fixed by a33bcc9b53b9d6ea9f879624e8abea0b012b008e.  
As mentioned in https://gitlab.com/xonotic/xonotic/-/issues/383 only old DP versions (like the one used in Xonotic 0.8.6) are affected.  Current DP versions call curl_multi_wait() (nearly the same as curl_multi_poll()) while downloading, old versions never call curl_multi_wait() or curl_multi_poll().

**Comment by andreymal** [comment]
Installing curl-git from AUR fixes this issue on my Arch, so it seems to be fixed in the master branch

**Comment by bagder** [comment]
fixed by a33bcc9b53b9d6ea9f879624e8abea0b012b008

**Comment by Vorondanil54** [comment]
So I have the same issue on Windows 10. Can anyone help me?
