### ISSUE TITLE
Building deletes curlbuild.h

### ISSUE THREAD

**Issue by graywolf** [curl/curl#1491]
### I did this

    $ cd /tmp/curl
    $ git status
    On branch master
    nothing to commit, working tree clean

    $ mkdir /tmp/build
    $ cd /tmp/build
    $ /tmp/curl/configure --prefix=/tmp/mingwroot/curl --with-ssl=/tmp/mingwroot/ssl --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu
    $ make
    $ make install

    $ cd /tmp/build
    $ git status
    On branch master
    Changes not staged for commit:
      (use "git add/rm <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            deleted:    curl-7.54.0/include/curl/curlbuild.h

### I expected the following

    $ cd /tmp/curl
    $ git status
    On branch master
    nothing to commit, working tree clean

    $ mkdir /tmp/build
    $ cd /tmp/build
    $ /tmp/curl/configure --prefix=/tmp/mingwroot/curl --with-ssl=/tmp/mingwroot/ssl --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu
    $ make
    $ make install

    $ cd /tmp/curl
    $ git status
    On branch master
    nothing to commit, working tree clean

### curl/libcurl version

7.54.0

### operating system

Updated archlinux, cross compiling for 64bit windows.

**Comment by bagder** [comment]
AFAIK it is `buildconf` that removes curlbuild.h, and it does that only as a precaution so that there won't end up two different curlbuild.h files after the build - with different contents!

curlbuild.h is soon going away completely (#1383) so I don't think it is worth losing much sleep over this particular behavior.

**Comment by graywolf** [comment]
cool :)
