### ISSUE TITLE
curl_multi_fdset() returns a write fd instead of read fd

### ISSUE THREAD

**Issue by thanhphamhuu** [curl/curl#14915]
### I did this

my system makes a request to the center to verify the PIN code via HTTP.
we use
+mc = curl_multi_fdset(multi, &fdread, &fdwrite, &fdexcep, &maxfd);
+ret = select(maxfd + 1, &fdread, &fdwrite, &fdexcep, &timeout);
+CURLMcode mc = curl_multi_perform(multi, &still_running);
in version V7.81.0 our system was fine but in version V8.4.0 the system had a problem.
the problem we encountered was that curl_multi_fdset **returned fdwrite instead of fdread**
I tested on version from V7.81.0 - V7.86.0 it still returned fdread but from version V7.87.0 our system had an error.

### I expected the following

mc = curl_multi_fdset(multi, &fdread, &fdwrite, &fdexcep, &maxfd);
returns fdread on version v8.4.0

### curl/libcurl version

curl 8.4.0

### operating system

Linux

**Comment by CriticalThinking028** [comment]
您好，我已经收悉您的邮件，随后将回复您！
祝您身体健康，工作顺利！

**Comment by pkropachev** [comment]
@thanhphamhuu , could provide a minimal sample that shows the failure?

**Comment by thanhphamhuu** [comment]
@bagder, sorry, i am late reply
I have sample as follows:


```
#include <stdio.h>
#include <string.h> 
/* somewhat unix-specific */
#include <sys/time.h>
#include <unistd.h> 
/* curl stuff */
#include <curl/curl.h>  
#define HANDLECOUNT 3 /* Number of simultaneous transfers */
#define HTTP_HANDLE 0 /* Index for the HTTP transfer */
#define FTP_HANDLE 1  /* Index for the FTP transfer */ 
int main(void)
{
    CURL *handles[HANDLECOUNT];
    CURLM *multi_handle; 
    int still_running = 0; /* keep number of running handles */
    int i; 
    CURLMsg *msg;  /* for picking up messages with the transfer status */
    int msgs_left; /* how many messages are left */
    curl_global_init(CURL_GLOBAL_DEFAULT);
    /* Allocate one CURL handle per transfer */
    for (i = 0; i < HANDLECOUNT; i++){
        handles[i] = curl_easy_init();
    }
    /* set the options (I left out a few, you will get the point anyway) */
    curl_easy_setopt(handles[HTTP_HANDLE], CURLOPT_URL, "https://example.com");
    curl_easy_setopt(handles[FTP_HANDLE], CURLOPT_URL, "ftp://example.com");
    curl_easy_setopt(handles[FTP_HANDLE], CURLOPT_UPLOAD, 1L);
    /* init a multi stack */
    multi_handle = curl_multi_init();
    if (multi_handle != NULL)
    {
        printf("multi_handle ok\n");
    }
    /* add the individual transfers */
    for (i = 0; i < HANDLECOUNT; i++){
        curl_multi_add_handle(multi_handle, handles[i]);
    }
    /* we start some action by calling perform right away */
    curl_multi_perform(multi_handle, &still_running); 
    while (true)
    {
        //struct timeval timeout;
        int ret;       /* select() return code */
        CURLMcode mc; /* curl_multi_fdset() return code */
 
        fd_set fdread;
        fd_set fdwrite;
        fd_set fdexcep;
        int maxfd = -1; 
        FD_ZERO(&fdread);
        FD_ZERO(&fdwrite);
        FD_ZERO(&fdexcep); 
        /* get file descriptors from the transfers */
        for (i = 0; i < HANDLECOUNT; i++)
        {
            mc = curl_multi_fdset(multi_handle, &fdread, &fdwrite, &fdexcep, &maxfd);
            if (mc != CURLM_OK)
            {
                fprintf(stderr, "curl_multi_fdset() failed, code %d.\n", mc);
                break;
            }
        } 
        ret = select(maxfd + 1, &fdread, &fdwrite, &fdexcep, NULL);
        if (-1 == ret)
        {
            printf("select() failed. errno:%d", errno);
            continue;
        }
 
        for (int index = 0; index < HANDLECOUNT; index++)
        {
            **if (FD_ISSET(maxfd, &fdread))** // bug -> remove this condition, I can see that the function can get the information after 2 or 3 loop
            {
                const char *szUrl = NULL;
                size_t headerSize = 0;
                char *location = NULL;
 
                int still_running = 0;
                CURLMcode mc = curl_multi_perform(m_pHttpContext->curlContext.hMulti, &still_running);
                printf("curl_multi_perform. CURLMcode:%d still_running:%d", mc, still_running);
                if(CURLM_OK != mc)
                {
                    return;
                }
                if(1 == still_running)
                {
                    return;
                }
 
                // Get HTTP status code
                //curl_easy_getinfo(handles[HTTP_HANDLE], CURLINFO_RESPONSE_CODE, &m);
                curl_easy_getinfo(handles[FTP_HANDLE], CURLINFO_PRIVATE, &szUrl);
                curl_easy_getinfo(handles[FTP_HANDLE], CURLINFO_HEADER_SIZE, &headerSize);
                ....
                curl_easy_getinfo(.....);
                printf(...)
            }
        }
    } 
    curl_multi_cleanup(multi_handle);
    for (i = 0; i < HANDLECOUNT; i++)
    {
        curl_easy_cleanup(handles[i]);
    }
    curl_global_cleanup();
    return 0;
}
```
Issue:
+ In version v7.81.0 with sample on our system still runs stably. We tested and found that the first time curl_multi_perform() -> curl_multi_fdset() -> returned fdread
+ when we upgraded to v8.4.0 we encountered an error.

> - We tested and found that the first time curl_multi_perform() -> curl_multi_fdset() -> returned fdwrite. Therefore, "if (FD_ISSET(maxfd, &fdread))" this condition is not satisfied -> the next block of commands is not executed -> our system does not receive data.
> - When we remove that condition and after 2->3 loops, the system receives data.

Q&A:

> + Please tell me what is the difference when I use the two versions above V7.81.0 and V8.4.0?
> + What do we need to do to fix the above situation when upgrading to the new version

?

**Comment by bagder** [comment]
- Your application calls `curl_multi_fdset` multiple times each loop instead of just once.
- I recommend using curl_multi_poll() instead for an easier API

> We tested and found that the first time curl_multi_perform() -> curl_multi_fdset() -> returned fdwrite. 

Why do you consider this is an error?

**Comment by thanhphamhuu** [comment]
I don't consider it a bug but since it returns us fdwrite so not satisfying this condition causes my system to loop infinitely in while(true) loop.
![image](https://github.com/user-attachments/assets/cabd5086-4a9a-43f4-a176-5e0fcdcdda89)

**Comment by bagder** [comment]
> not satisfying this condition causes my system to loop infinitely

*That* assumption is your error.

**Comment by thanhphamhuu** [comment]
> _That_ assumption is your error.
Yes, but I still don't understand why V7.81.0 is fine, and when upgrading to V8.4.0, a bug occurs.

**Comment by thanhphamhuu** [comment]
> Your assumption that a transfer only progresses on being in `fdread` is wrong. Protocols like HTTP/2, for example, require sending while receiving a response. The old HTTP/1.x way of only sending the request and then only receiving the response no longer holds.
can you explain more? i am handling it by calling curl_multi_perform multiple times. Is it ok?

**Comment by icing** [comment]
> > Your assumption that a transfer only progresses on being in `fdread` is wrong. Protocols like HTTP/2, for example, require sending while receiving a response. The old HTTP/1.x way of only sending the request and then only receiving the response no longer holds.
> > can you explain more? i am handling it by calling curl_multi_perform multiple times. Is it ok?

Your code checks that `maxfd`, the one socket added last to the set, is readable. What about the, possibly, other sockets? They seem to be never checked. If your 3 transfers all use the same connection, this might work, unless the transfers need to send something before receiving.

In newer curl versions, the settings in `fdread` and `fdwrite` have been implemented more correctly. Older curl versions will have set bits in `fdread` where it really was not correct. So, what you see with 7.81 compared to 8.4 differs.

The correct way to use the curl API is to run `curl_multi_perform()` whenever one of the 1...maxfd sockets signals something, be it read or write.

**Comment by bagder** [comment]
> The correct way to use the curl API is to run curl_multi_perform() whenever one of the 1...maxfd sockets signals something, be it read or write.

And only call it *once*, independently of how many sockets that readable and writable. Then loop.

**Comment by bagder** [comment]
The [multi-double](https://curl.se/libcurl/c/multi-double.html) example shows how this can be done a little simpler.

**Comment by thanhphamhuu** [comment]
> > The correct way to use the curl API is to run curl_multi_perform() whenever one of the 1...maxfd sockets signals something, be it read or write.
> 
> And only call it _once_, independently of how many sockets that are readable and writable. Then loop.

@bagder @icing , so what should we do to best fix this bug. can we use curl_multi_wait or curl_multi_poll ? to fix this error?

**Comment by bagder** [comment]
1. Stop assuming that you'll get a read activity to wait for first
2. Run the perform call independently of what socket activity there was (as documented)
3. Only run perform *once* when one (or more) sockets indicate activity

Maybe take another loop over the documentation and existing examples that show this.
