### ISSUE TITLE
can't build curl on os400 

### ISSUE THREAD

**Issue by lomberd2** [curl/curl#14938]
### I did this

I installed following the instructions in packages/os400/readme.os400

I narrowed it down to that it fails somewhere in make-lib.sh - (It almost fully compiles)
[makelog.txt](https://github.com/user-attachments/files/17017683/makelog.txt)

### I expected the following

To create the curl PGM on OS400

### curl/libcurl version

OS/400 ILE

### operating system

OS400 V7R4M0

**Comment by bagder** [comment]
@lomberd2 curl version?

**Comment by lomberd2** [comment]
@bagder LTS I guess?. I cloned the master REPO yesterday. 

FYI: I also tried it with another version like 1 or 2 months ago, but I had not set my "LANG" var in WRKENVVAR correctly back then. Obviously not even a single module got installed then.

**Comment by lomberd2** [comment]
I tried with CURL/8.10.0 now. Sadly same result, can't install curl in the end. 
Makelog included. One without CCSID Override one with Override config (attached also with .txt ending because github)

[makelog_withoutOverride.txt](https://github.com/user-attachments/files/17031759/makelog_withoutOverride.txt)
[makelog_withOverride.txt](https://github.com/user-attachments/files/17031760/makelog_withOverride.txt)
[config400.override.txt](https://github.com/user-attachments/files/17031762/config400.override.txt)

**Comment by jonrumsey** [comment]
I think this is the same issue https://github.com/curl/curl/issues/14952
