### ISSUE TITLE
CURLE_FTP_COULDNT_SET_TYPE when uploading to openload.co

### ISSUE THREAD

**Issue by yoursunny** [curl/curl#1494]
### I did this

`date | curl -v -T - ftp://username:password@ftp.openload.co/date.txt`

### I expected the following

Upload is successful.

### curl/libcurl version

```
curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

### operating system

Ubuntu 12.04 amd64

### Actual Output

```
shijunxiao@maestro:~$ date | curl -v -T - ftp://username:password@ftp.openload.co/date.txt
* About to connect() to ftp.openload.co port 21 (#0)
*   Trying 185.163.108.43...   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0connected
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 220 openload FTP server (report errors at http://openload.co)
> USER username
< 331 Password required for username.
> PASS password
< 230 User username logged in from ::ffff:128.196.203.35.
> PWD
< 257 "/" is current directory.
* Entry path is '/'
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||51101|)
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0connected
* Connecting to 185.163.108.43 (185.163.108.43) port 51101
> TYPE I
< 150 Opening ASCII mode data connection.
* Couldn't set desired mode
* Remembering we are in dir ""
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
* Connection #0 to host ftp.openload.co left intact
curl: (17) Couldn't set desired mode
> QUIT
< 200 type set.
* Closing connection #0
```

The server emits **150** response when the passive socket is connected. curl incorrectly interprets this line as the response to **TYPE I**, and fails the transaction with error `CURLE_FTP_COULDNT_SET_TYPE`.
The server then returns **200 type set** in reply to **TYPE I** but it's too late.

**Comment by bagder** [comment]
7.22.0 is over 5 years and 43 releases old and I can't access this FTP server. Can you check with a reasonably modern curl version and see if this problem still remains?

**Comment by yoursunny** [comment]
To get access to this server, an account at https://openload.co is needed.

`curl 7.47.0 (i686-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3` on Ubuntu 16.04 **does not have this bug**.
Wireshark shows `200 type set.` comes before `150 Opening ASCII mode data connection`, although I don't see any difference except timing.

`curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3` on Ubuntu 14.04 **still has this bug**.
It seems that I need to talk to Ubuntu 14.04 LTS maintainers for a backport.
