### ISSUE TITLE
Problems on NativeKit to compile curl with ssl

### ISSUE THREAD

**Issue by prsolucoes** [curl/curl#1496]
Im building a library for mobile/desktop systems that use curl and openssl for HttpClient option. But only on linux now, i cant compile curl with HTTPS support. On mac and android is ok, but on linux HTTPS is disabled and i dont know what is wrong.

The project is here:
https://github.com/prsolucoes/native-kit

The command to build is:

```
make docker-run task=build-curl-linux64
```

If you are on Linux, you can run direct:

```
make build-curl-linux64
```

The script that build is here:
https://github.com/prsolucoes/native-kit/blob/master/projects/curl-linux64/build.sh

Thanks for any help.

**Comment by bagder** [comment]
But that's another project! If you have problems with their scripts you should probably report it there and work with them to fix those.

If you want help to build curl, please tell us exactly what you did with scripts/methods *we provide* and what happened.

**Comment by prsolucoes** [comment]
No man, it is my project. Im trying make it, im trying build curl for my project.

**Comment by bagder** [comment]
Then please show us what you do and what happens! Which SSL library are you building with and how did you install that etc.

**Comment by prsolucoes** [comment]
But i show it on that .sh file.

Nothing happens, but when i call "./configure ..." with that params, it is showing that dont have HTTPS support, but im passing the params used in other build, like on Android script:
https://github.com/prsolucoes/native-kit/blob/master/projects/curl-android/build.sh

But on Linux, it compile without problems, but without SSL support:

```
SSL support:      no      (--with-{ssl,gnutls,nss,polarssl,mbedtls,cyassl,axtls,winssl,darwinssl} )
```

Thanks.

**Comment by bagder** [comment]
> But i show it on that .sh file.

But we discuss the bug here and that script doesn't show enough.

So again: Which SSL library are you building with and how did you install that (your script seems to imply an OpenSSL flavor but I'd like that confirmed from you). What does your `config.log` file say about the SSL checks after configure failed to detect it?

**Comment by prsolucoes** [comment]
Ok, i will post the log to try understand.

I download the openssl last version in real time (version: 1.1.0e).

The log relevant to SSL:

```
configure:3821: using CFLAGS: -I/native-kit/vendor/zlib-linux64/include -I/native-kit/vendor/openssl-linux64/include
```

```
configure:3835: CFLAGS note: CFLAGS should only be used to specify C compiler flags, not include directories. Use CPPFLAGS for: -I/native-kit/vendor/openssl-linux64/include
```

```
| 
| 
| #ifdef __cplusplus
| extern "C"
| #endif
| char ssl_version ();
| int main (void)
| {
| return ssl_version ();
|  ;
|  return 0;
| }
configure:25169: result: no
configure:25202: WARNING: SSL disabled, you will not be able to use HTTPS, FTPS, NTLM and more.
configure:25204: WARNING: Use --with-ssl, --with-gnutls, --with-polarssl, --with-cyassl, --with-nss, --with-axtls, --with-winssl, or --with-darwinssl to address this.
configure:25215: checking default CA cert bundle/path
configure:25327: result: /etc/ssl/certs/ca-certificates.crt
configure:25345: checking whether to use builtin CA store of SSL library
configure:25359: result: no
```

**Comment by bagder** [comment]
Why are you setting `CFLAGS` like that? The common approach would be to just use:

`./configure --with-zlib=/native-kit/vendor/zlib-linux64 --with-ssl=/native-kit/vendor/openssl-linux64`

As you can see in the lib test failure from your log, you don't have a working OpenSSL lib in the specified path prefix. Ie the two libs should be in $prefix/lib.

I also see that you're building static-only so just be aware that if you did the same with openssl when you installed that, you may need to tell curl's configure about OpenSSL prerequisites to make the linking work in the tests. LIBS="-ldl -lpthread" for openssl 1.1.0 usually works. (slightly improved in commit c68fed8751f7, to be included in the next release)

**Comment by prsolucoes** [comment]
Hi, i already try put libs in "lib" folder, but it doesnt work. Nothing change. See:
<img width="242" alt="screenshot 2017-05-19 13 29 24" src="https://cloud.githubusercontent.com/assets/395096/26257504/43529bbc-3c97-11e7-842b-e568179594cd.png">

I have removed all flags and leave only what you say:

```
# build process
cd ${LIBRARY_DIR}

export LIBS="-ldl -lpthread"

./configure \
	--prefix=${PWD}/build \
	--with-ssl=${VENDOR_DIR}/openssl-linux64 \
	--with-zlib=${VENDOR_DIR}/zlib-linux64 \
	--enable-static \
	--disable-shared \
	--disable-verbose \
	--enable-threaded-resolver \
	--enable-libgcc \
	--enable-ipv6 \
	--disable-ldaps \
	--disable-ldap \
	--disable-ftp \
	--disable-file \
	--disable-telnet \
	--disable-dict \
	--disable-tftp \
	--disable-pop3 \
	--disable-imap \
	--disable-smtp \
	--disable-rtsp \
	--disable-gopher

make
make install
```

**Comment by bagder** [comment]
Back to the `config.log` then and check the openssl detection, what linker flags it uses, what error message it gets and then adjust accordingly. Consider attaching the whole thing here.

**Comment by prsolucoes** [comment]
Hi,

Related log:

```
configure:22165: PKG_CONFIG_LIBDIR will be set to "/native-kit/vendor/openssl-linux64/lib/pkgconfig"
configure:22348: checking for HMAC_Update in -lcrypto
configure:22370: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers  -I/native-kit/vendor/openssl-linux64/include -I/native-kit/vendor/openssl-linux64/include/openssl  -L/native-kit/vendor/openssl-linux64/lib conftest.c -lcrypto  -lgcc -ldl -lpthread >&5
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x3b): undefined reference to `inflate'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xb4): undefined reference to `deflate'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_finish':
c_zlib.c:(.text+0xe9): undefined reference to `inflateEnd'
c_zlib.c:(.text+0xf2): undefined reference to `deflateEnd'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_init':
c_zlib.c:(.text+0x1b4): undefined reference to `inflateInit_'
c_zlib.c:(.text+0x230): undefined reference to `deflateInit_'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_free':
c_zlib.c:(.text+0x2b5): undefined reference to `inflateEnd'
c_zlib.c:(.text+0x2e0): undefined reference to `deflateEnd'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_ctrl':
c_zlib.c:(.text+0x56c): undefined reference to `deflate'
c_zlib.c:(.text+0x63c): undefined reference to `zError'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
c_zlib.c:(.text+0x76a): undefined reference to `deflate'
c_zlib.c:(.text+0x83c): undefined reference to `zError'
c_zlib.c:(.text+0x8a6): undefined reference to `deflateInit_'
/native-kit/vendor/openssl-linux64/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_read':
c_zlib.c:(.text+0x988): undefined reference to `inflate'
c_zlib.c:(.text+0xa04): undefined reference to `zError'
c_zlib.c:(.text+0xa7e): undefined reference to `inflateInit_'
collect2: error: ld returned 1 exit status
```

This is the full log:
https://www.dropbox.com/s/y3rlta6ysbs8myg/curl-config.log?dl=0


Thanks for the help.

**Comment by prsolucoes** [comment]
And im building openssl with the z library with this:

```
./Configure no-shared zlib --with-zlib-include=${VENDOR_DIR}/zlib-linux64/include --with-zlib-lib=${VENDOR_DIR}/zlib-linux64 --openssldir=. linux-x86_64

make clean
make depend
make all
```

**Comment by gvanem** [comment]
The `libz.a` functions are missing. Try a `export LIBS="-lz -ldl -lpthread"`?

**Comment by prsolucoes** [comment]
Tried, but if i set:

```
export LIBS="-lz -ldl -lpthread"
```

I got errors:

```
Task to run on docker: build-curl-linux64
docker run -it -v /Users/paulo/Developer/workspaces/cpp/native-kit:/native-kit native-kit make build-curl-linux64
cd projects/curl-linux64 && ./build.sh
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... (assumed) yes
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to enable c-ares for DNS lookups... no
checking whether to disable dependency on -lrt... (assumed no)
checking for path separator... :
checking for sed... /bin/sed
checking for grep... /bin/grep
checking for egrep... /bin/grep -E
checking for ar... /usr/bin/ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/native-kit/projects/curl-linux64/tmp/curl-7.54.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:115: recipe for target 'build-curl-linux64' failed
make: *** [build-curl-linux64] Error 77
make: *** [docker-run] Error 2
```

And config.log is empty.

**Comment by gvanem** [comment]
Nice! My advice; try to stay away from this *autoshit* tools and create a Makefile people can understand.

**Comment by bagder** [comment]
> /usr/bin/ld: cannot find -lz

I think this speaks for itself.

**Comment by prsolucoes** [comment]
No man. Lib "z" is on the folder that i said.

<img width="163" alt="screenshot 2017-05-20 07 05 50" src="https://cloud.githubusercontent.com/assets/395096/26274879/c97ef1e8-3d2a-11e7-8950-73803a5688cb.png">

And the command is:

```
export LIBS="-lz -ldl -lpthread"

./configure \
	--prefix=${PWD}/build \
	--with-ssl=${VENDOR_DIR}/openssl-linux64 \
	--with-zlib=${VENDOR_DIR}/zlib-linux64 \
	--enable-static \
	--disable-shared \
	--disable-verbose \
	--enable-threaded-resolver \
	--enable-libgcc \
	--enable-ipv6 \
	--disable-ldaps \
	--disable-ldap \
	--disable-ftp \
	--disable-file \
	--disable-telnet \
	--disable-dict \
	--disable-tftp \
	--disable-pop3 \
	--disable-imap \
	--disable-smtp \
	--disable-rtsp \
	--disable-gopher

make
make install
```

**Comment by bagder** [comment]
Yes, but if you pass in `LIBS=-lz` you ask for all link commands in configure to use zlib - but without telling it where to find the lib, so apparently it doesn't find it and fails. Since you don't provide the lib in the default path the linker searches for it.

If you want to unconditionally provide -lz to all link commands, you should also provide the necessary -L flag to find said library.

Your static openssl library seems to require zlib so you should probably do exactly this.

**Comment by prsolucoes** [comment]
If i removed the "-lz" that you said to put and back to my original, i got:

```
configure:20917: checking zlib.h usability
configure:20917: gcc -c -Werror-implicit-function-declaration -O2 -Wno-system-headers  -I/native-kit/vendor/zlib-linux64/include conftest.c >&5
configure:20917: $? = 0
configure:20917: result: yes
configure:20917: checking zlib.h presence
configure:20917: gcc -E  -I/native-kit/vendor/zlib-linux64/include conftest.c
configure:20917: $? = 0
configure:20917: result: yes
configure:20917: checking for zlib.h
configure:20917: result: yes
configure:20922: checking for gzread in -lz
configure:20944: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers  -I/native-kit/vendor/zlib-linux64/include  -L/native-kit/vendor/zlib-linux64/lib conftest.c -lz  -lgcc -ldl -lpthread >&5
configure:20944: $? = 0
configure:20953: result: yes
configure:21005: found both libz and libz.h header
```

Command:

```
export LIBS="-ldl -lpthread"

./configure \
	--prefix=${PWD}/build \
	--with-ssl=${VENDOR_DIR}/openssl-linux64 \
	--with-zlib=${VENDOR_DIR}/zlib-linux64 \
	--enable-static \
	--disable-shared \
	--disable-verbose \
	--enable-threaded-resolver \
	--enable-libgcc \
	--enable-ipv6 \
	--disable-ldaps \
	--disable-ldap \
	--disable-ftp \
	--disable-file \
	--disable-telnet \
	--disable-dict \
	--disable-tftp \
	--disable-pop3 \
	--disable-imap \
	--disable-smtp \
	--disable-rtsp \
	--disable-gopher
```

**Comment by bagder** [comment]
But the openssl detection still fails due to not finding the zlib, doesn't it?

**Comment by prsolucoes** [comment]
I think i discovered the problem. I need put libz.a inside "lib" folder.

This is a defualt for all libraries? Or only to curl?

**Comment by bagder** [comment]
Yes, libraries are installed in `$prefix/lib` and its headers in `$prefix/include`. Not following that pattern means asking for trouble.

**Comment by prsolucoes** [comment]
So i can follow it for all my libraries? And for all libraries that i use? "libz, openssl, curl, sqlite, ..."?

**Comment by bagder** [comment]
Yes, I think you should. To minimize problems.

**Comment by prsolucoes** [comment]
Ok, thanks. I will try recompile all here and post the results.

**Comment by prsolucoes** [comment]
It is working. Thanks man :p
