### ISSUE TITLE
HAVE_POLL_FINE is always false when cross-compiling for Android

### ISSUE THREAD

**Issue by vvb2060** [curl/curl#15013]
### I did this

./configure

### I expected the following

#define HAVE_POLL_FINE 1

### curl/libcurl version

curl 8.10.1

### operating system

Android

**Comment by vvb2060** [comment]
#14734

**Comment by dfandrich** [comment]
Are you using autoconf or cmake? If the former, can you show the snippet of config.log around this check?

**Comment by vvb2060** [comment]
@vszakats _POSIX_C_SOURCE has been deleted in https://r.android.com/237770/6/libc/include/sys/cdefs.h : With bionic, you always get all C and POSIX API.

**Comment by vszakats** [comment]
At compile-time, how to we detect Bionic and this version of Bionic where fine poll is unconditionally available?

**Comment by vvb2060** [comment]
https://android.googlesource.com/platform/bionic/+/main/docs/defines.md

**Comment by bagder** [comment]
I propose  #15037
