### ISSUE TITLE
cURL 8.10.1 --with-ca-embed does not work with relative path

### ISSUE THREAD

**Issue by ecnepsnai** [curl/curl#15025]
### I did this

Trying to compile curl for iOS targeting openssl with an embedded CA file worked on 8.10.0 but stopped working on 8.10.1, likely due to #14879 

Build variables:
```
CC="/Applications/Xcode.app/Contents/Developer/usr/bin/gcc" CFLAGS="-arch arm64 -pipe -Os -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk -miphoneos-version-min=12.0"
CPPFLAGS="-I/Users/ian/Developer/curl-ios/build/openssl/openssl_arm64-iphoneos/artifacts/include" LDFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk -L/Users/ian/Developer/curl-ios/build/openssl/openssl_arm64-iphoneos/artifacts/lib"
```

Configure parameters:
```
--host="arm-apple-darwin" --disable-shared --enable-static --with-openssl --without-libpsl --with-ca-embed=apple_ca_bundle.pem --prefix /Users/ian/Developer/curl-ios/build/curl_arm64-iphoneos/artifacts
```

But it fails with:

```
make[1]: *** No rule to make target `apple_ca_bundle.pem', needed by `tool_ca_embed.c'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC       tool_xattr.o
  CC       var.o
make: *** [all-recursive] Error 1
```

The `tool_ca_embed.c` does not exist anywhere within `src`

### I expected the following

Curl to compile

### curl/libcurl version

8.10.1

### operating system

iOS

**Comment by ecnepsnai** [comment]
Workaround (and maybe intended behaviour?) pass an absolute path to `--with-ca-embed`

**Comment by vszakats** [comment]
@ecnepsnai Thanks for your report. Yes, an absolute path is necessary for this option to work.

This was also true for 8.10.0.

Considering both ./configure and make need to find it at different stages of the build (also in tree, out of tree, after moving the dir around), I can't see a reasonable way to make relative paths work.

**Comment by bagder** [comment]
It generally goes for *all* paths specified to configure.

**Comment by ecnepsnai** [comment]
Thanks! I submitted a PR to clarify the help text of ./configure to help avoid this confusion in the future. #15033
