### ISSUE TITLE
cmake builds don't include architecture in curl version

### ISSUE THREAD

**Issue by jay** [curl/curl#1502]
curl versions OS field (ie destination host) vary depending on how they're built, for example:

curl 7.53.1 (**x86_64-pc-linux-gnu**) <-- gcc example
curl 7.54.1-DEV (**x86_64-pc-win32**) <-- visual studio example (prebuilt project files, or winbuild)
curl 7.54.1-DEV (**Windows**) <-- cmake with any compiler in Windows

I expected something like 'i386-pc-win32' or 'i386-pc-windows' or instead.

The way it works in the cmake build is the OS define is [set](https://github.com/curl/curl/blob/curl-7_54_0/CMakeLists.txt#L70) to [CMAKE_SYSTEM_NAME](https://cmake.org/cmake/help/v3.0/variable/CMAKE_SYSTEM_NAME.html) which on some platforms comes from `uname -s` (eg "Linux") or for OSes where that is not available it will use the already known name (eg "Windows").

I had figured it would be in a host triplet like destination cpu-machine-os. cmake it appears to me doesn't have an easy way to get the destination architecture in particular, for example it would be nice if we could do something like `set(OS "\"$CMAKE_ARCH-pc-LOWERCASE(${CMAKE_SYSTEM_NAME})\"")` or however that's supposed to be done, I don't know cmake.

@webmaster128 has a cmake helper [platformtest.c](https://gist.github.com/webmaster128/e08067641df1dd784eb195282fd0912f) that it looks like can properly detect architecture, but I don't know how to integrate it.

### curl/libcurl version
edd7603 2017-05-21

### operating system
Windows 7
cmake version 3.8.1
Microsoft Visual Studio Community 2015
Version 14.0.25420.01 Update 3

**Comment by webmaster128** [comment]
I'll check the target platform test and provide the missing cmake component to the .c file

**Comment by webmaster128** [comment]
Here you can find the CMake module for the Gist you linked: https://github.com/kullo/CrosscompileTargetProcessorType including a description of how it works.

Please let me know if you need something else in terms of features, cmake support, license or whatever.

**Comment by snikulov** [comment]
@jay I have a shorter proposal for this. Could you please check #1720 on Windows?
