### ISSUE TITLE
schannel: failed to read data from server: SEC_E_DECRYPT_FAILURE (0x80090330) - The specified data could not be decrypted.

### ISSUE THREAD

**Issue by korDen** [curl/curl#15024]
### I did this

using libcurl version 8.9.1, I'm randomly getting this error downloading a large number of files from cloudflare. No solid repro, but I have a large set of files to download, and after awhile this consistently happens.

### I expected the following

the download should complete without any errors

### curl/libcurl version

curl 8.9.1

### operating system

Windows 11 24H2

**Comment by pkropachev** [comment]
Is this version shipped with Windows? If so, then make sense to report about the issue to Microsoft.

In some cases such failure happens in case using modern version of TLS. Try to decrease used version of TLS using `--tls-max` options.

E.g.:

```
curl --tls-max 1.2 https://example.com
```

**Comment by korDen** [comment]
No, it's version I installed from vcpkg

**Comment by pkropachev** [comment]
@korDen , have you tried to check TSL version and change it to check if behavior is changed? You can use corresponding `CURL_SSLVERSION` options.

As far as I understand `vcpkg` compiles libraries and tools by his own rules.

I don't think that curl works with schannel in some wrong way. So, `SEC_E_DECRYPT_FAILURE` doesn't look like a curl problem.

**Comment by korDen** [comment]
I tried setting CURLOPT_SSLVERSION to CURL_SSLVERSION_TLSv1_2 and CURL_SSLVERSION_MAX_TLSv1_2 and it didn't help. Clock is correct, Windows 10 isn't outdated.

**Comment by jay** [comment]
There's not enough information here to indicate that this is a curl problem. If you can find a way to reproduce we'll take a look, otherwise we will close

**Comment by bagder** [comment]
Lack of information, closing.
