### ISSUE TITLE
Can't resolve (some?) hostnames

### ISSUE THREAD

**Issue by pekatour** [curl/curl#15036]
### I did this

I tried `curl https://apt.armcord.app/public.gpg`
Or `curl https://dl.flathub.org/repo/flathub.flatpakrepo`

Which are totally working URLs in my web navigator.

I get "Could not resolve host:"
Also see https://github.com/flatpak/flatpak/issues/5943#issue-2543141627 for a related situation.

### I expected the following

The command to complete successfully

### curl/libcurl version

curl 8.5.0

### operating system

Ubuntu 24.04 LTS

**Comment by dfandrich** [comment]
What resolver backend is the problematic curl using? Are other programs able
to resolve those names, like "getent hosts dl.flathub.org"?

**Comment by bagder** [comment]
is this using the plain curl package shipped by ubuntu? if so, quite a few users seem to be able to use it already without this problem so we need more details to pinpoint exactly what makes your problem unique and special
