### ISSUE TITLE
OS400 fails to build 7.54.0

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#1504]
### I did this
Build 7.54.0 source on OS/400 V7R2M0 

### I expected the following
Clean build, fails in link due to use of assert macro in rand.c

### curl/libcurl version
7.54.0

### operating system
OS/400 V7R2M0

**Comment by bagder** [comment]
Thanks for reporting, the fix in commit 8589e1fe3 makes sure we use `DEBUGASSERT` instead, which has more preprocessor magic protection to make sure it works.
