### ISSUE TITLE
Windows file:/// upload quirks

### ISSUE THREAD

**Issue by ralfjunker** [curl/curl#15043]
### I did this

I run code inspired by https://github.com/curl/curl/blob/master/docs/examples/fileupload.c.

### I expected the following

I expect the file to "upload", but the upload fails if the file already exists and returns `CURLE_WRITE_ERROR`.

Looking at the source, I observe that [file_connect()](https://github.com/curl/curl/blob/da94b0237260f2fbc149f880c00c24a90fb7c5af/lib/file.c#L153) tries to open the file in read-only mode, regardless of upload or download.

Later, the actual [file_upload](https://github.com/curl/curl/blob/da94b0237260f2fbc149f880c00c24a90fb7c5af/lib/file.c#L296) once more tries to open the file, but this time for writing - which now fails because the file is already open in read-only mode and therefore locked for writing.

It seems to help if `file_connect()` does not open the file when uploading, thus replacing

https://github.com/curl/curl/blob/da94b0237260f2fbc149f880c00c24a90fb7c5af/lib/file.c#L212

with

```C
  if(data->state.upload)
    fd = -1;
  else
    fd = open_readonly(actual_path, O_RDONLY|O_BINARY);
```

### curl/libcurl version

Current master.

### operating system

Windows 11.

**Comment by dfandrich** [comment]
We had test 204 for a regular file: upload but no test of file: with overwrite. I've added a test in #15045 so we can see exactly where it's having problems.

**Comment by dfandrich** [comment]
That new test 1490 is succeeding in all the Windows targets (and all the others). Is there some other precondition needed to see it fail?

**Comment by ralfjunker** [comment]
I am not aware of other precondition.

This is the basic code, it needs to fill in the `CURLOPT_READFUNCTION` callback:

```C
curl_easy_setopt(easy_handle, CURLOPT_URL, "file:///Z:\\test.txt");
curl_easy_setopt(easy_handle, CURLOPT_UPLOAD, 1);
curl_easy_setopt(easy_handle, CURLOPT_READFUNCTION, @curl_read_function);
curl_easy_setopt(easy_handle, CURLOPT_INFILESIZE_LARGE, size);
curl_easy_perform(easy_handle);
```

**Comment by dfandrich** [comment]
If you run this from the command-line (substituting the correct path), do you get the expected result? (i.e. a "skips" message and "bar")
```
echo foo >foo
echo bar >bar
curl file:///path/to/foo -o bar --skip-existing -v
type bar
```

**Comment by ralfjunker** [comment]
Yes. Here is the result:

```
Z:\curl-8.10.1_1-win64-mingw\bin>echo foo >foo
Z:\curl-8.10.1_1-win64-mingw\bin>echo bar >bar
Z:\curl-8.10.1_1-win64-mingw\bin>curl file:///Z:\curl-8.10.1_1-win64-mingw\bin\foo -o bar --skip-existing -v
Note: skips transfer, "bar" exists locally
Note: Using embedded CA bundle, for proxies (228633 bytes)
Z:\curl-8.10.1_1-win64-mingw\bin>type bar
bar
```

**Comment by ralfjunker** [comment]
**All-clear**: The reason is a non-standard `_wopen()` which does not grant write sharing to files opened in read-only mode. If write sharing is allowed, libcurl behaves as expected. Apologies for the false alarm!

Still, the file to upload is opened twice, which uses two file handles, which is not necessary, and which I think could be optimized. See initial thread message for details.
