### ISSUE TITLE
`curl_multi_cleanup` leads to unexpected timeouts

### ISSUE THREAD

**Issue by steve-chavez** [curl/curl#15079]
### I did this

Using the [ephiperfifo.c](https://curl.se/libcurl/c/ephiperfifo.html) example, I modify it to do many requests in loops and calling `curl_multi_init/curl_multi_cleanup` at the start/end of the loops leads to some requests fail with timeouts. The failure happens when doing around ~5K requests. Increasing this number leads to more failures and reducing it leads to less likelihood of failures (1k requests or less never fails). 

The thing here is if `curl_multi_init/curl_multi_cleanup` is done at the start/end of the program, no timeouts happen. Even when increasing the number to 20K requests and more. So that leads me to believe there's something wrong with `curl_multi_cleanup`. For my use case, I have a long lived program so I have to do `curl_multi_cleanup` before the program ends, otherwise memory usage keeps increasing.

I provide a snippet and a temporary server with Nginx to reproduce the problem:

https://gist.github.com/steve-chavez/75a85d222f5efac35122cb759c91047e

When this is ran:

```
...
DONE: http://18.221.56.101/ => (28) Connection timed out after 5000 milliseconds
DONE: http://18.221.56.101/ => (28) Connection timed out after 5000 milliseconds
...

Succeeded: 4525, Failed: 475, Latest error: Timeout was reached
```

Using the following patch (`curl_multi_cleanup` at the end of the program), removes the timeouts:

```patch
 curl/repro_timeouts.c | 16 +++++++++-------
 1 file changed, 9 insertions(+), 7 deletions(-)

diff --git a/curl/repro_timeouts.c b/curl/repro_timeouts.c
index d4a88f8..7c86eb4 100644
--- a/curl/repro_timeouts.c
+++ b/curl/repro_timeouts.c
@@ -361,13 +361,14 @@ int main(void)
   fprintf(MSG_OUT, "Entering wait loop\n");
   fflush(MSG_OUT);
 
-  for(size_t i = 0; i < TOTAL_REQUESTS/BATCH_SIZE; i++) {
-    g.multi = curl_multi_init();
+  g.multi = curl_multi_init();
+
+  curl_multi_setopt(g.multi, CURLMOPT_SOCKETFUNCTION, sock_cb);
+  curl_multi_setopt(g.multi, CURLMOPT_SOCKETDATA, &g);
+  curl_multi_setopt(g.multi, CURLMOPT_TIMERFUNCTION, multi_timer_cb);
+  curl_multi_setopt(g.multi, CURLMOPT_TIMERDATA, &g);
 
-    curl_multi_setopt(g.multi, CURLMOPT_SOCKETFUNCTION, sock_cb);
-    curl_multi_setopt(g.multi, CURLMOPT_SOCKETDATA, &g);
-    curl_multi_setopt(g.multi, CURLMOPT_TIMERFUNCTION, multi_timer_cb);
-    curl_multi_setopt(g.multi, CURLMOPT_TIMERDATA, &g);
+  for(size_t i = 0; i < TOTAL_REQUESTS/BATCH_SIZE; i++) {
 
     for (size_t ii = 0; ii < BATCH_SIZE; ii++) {
       new_conn(URL, &g);
@@ -387,9 +388,10 @@ int main(void)
       }
     } while (g.still_running > 0);
 
-    curl_multi_cleanup(g.multi);
   }
 
+  curl_multi_cleanup(g.multi);
+
   fprintf(MSG_OUT, "Succeeded: %d, Failed: %d, Latest error: %s\n", g.count_success, g.count_error, g.latest_error);
   fprintf(MSG_OUT, "Exiting normally.\n");
   fflush(MSG_OUT);
```

### I expected the following

No timeouts.

### curl/libcurl version

- curl 8.10.1
- curl 8.8.0
- curl 8.7.1

### operating system

Pop!_OS 22.04 LTS x86_64

**Comment by bagder** [comment]
> otherwise memory usage keeps increasing

No it won't. That would imply a memory-leak, and would be a bug, but I can't recall any noticeable leaks as of late.

**Comment by steve-chavez** [comment]
> otherwise memory usage keeps increasing
> No it won't. That would imply a memory-leak, and would be a bug, 

I've confirmed on a long-lived program that is indeed the case, memory usage increases unless `curl_multi_cleanup` is called. @bagder I'm also guided by your comment here:.

> If you never clean it up, you will never get the memory and resources "back" that is allocated in relation to that handle.
> https://stackoverflow.com/a/59908528/4692662

Unless there's a different way to use `curl_multi_cleanup` nowadays?

That being said, the timeouts happening because of `curl_multi_cleanup` seem like a different issue.

**Comment by bagder** [comment]
> the timeouts happening because of curl_multi_cleanup seems like a bug.

What exactly is timing out? It looks to me like your program logic waits until all transfers are complete before you call multi_cleanup, so what is then timing out if there is no transfers left running?

**Comment by steve-chavez** [comment]
> What exactly is timing out? 

As mentioned [above](https://github.com/curl/curl/issues/15079#issue-2553597083):
> Succeeded: 4525, Failed: 475, Latest error: Timeout was reached

475 requests time out out of 5000 requests.

The example is reproducible (took a lot of work to isolate this too) so you can try it yourself.

> waits until all transfers are complete before you call multi_cleanup, so what is then timing out if there is no transfers left running?

Yes, that's what is confusing. It's like some file descriptors of previously cleaned multi handles are getting tainted and reused by new multi handles somehow?

**Comment by bagder** [comment]
Unfortunately, your example code edited to use `http://localhost`, runs without any issue here for me, time after time. I'm using git master (on Linux), but I can't see how that is much different to 8.10.1 when it comes to this.

**Comment by steve-chavez** [comment]
Yes, it doesn't happen on localhost, that's why I provided a server. I believe name resolution has to be involved for the error to show.

**Comment by icing** [comment]
Can it be that you just underestimate the benefits of connection reuse? If you keep the `multi` open for all your batch requests, they will reuse the existing connections. If you `cleanup` after each batch, the connection cache will be cleared after each batch. This makes you use new connections for each batch. 

Since close down of connections at the server may take some time and require a lingering close, your server may become unresponsive intermittently.

**Comment by bagder** [comment]
> Yes, it doesn't happen on localhost, that's why I provided a server. I believe name resolution has to be involved for the error to show.

Your example uses a numerical IP address, there is no name resolution used then.

I also tested to run the example again using a DNS name and the server not being on my local machine, and it still ran fine (*) for me.

(*) = it can be noted that the example calls `curl_multi_assign()` from within the callback called by `curl_multi_cleanup()`, which then libcurl considers to be a "bad" handle so it returns an error code instead (and a debug-build aborts). I can't see how that explains anything here though.

**Comment by steve-chavez** [comment]
> Can it be that you just underestimate the benefits of connection reuse? If you keep the multi open for all your batch requests, they will reuse the existing connections. If you cleanup after each batch, the connection cache will be cleared after each batch. This makes you use new connections for each batch.

@icing This makes a lot of sense, but I wasn't underestimating simply I wasn't aware of any connection caching. This is [connection cache](https://everything.curl.dev/internals/caches.html#connection-cache) right? Perhaps this could be warned on the `curl_multi_cleanup` doc? Like `this will also cleanup the connection cache, so subsequent requests to the same URL might take longer`?

> Your example uses a numerical IP address, there is no name resolution then.

Right, my bad. I copy/pasted the wrong URL when sharing it here. But as cleared up now name resolution is not the issue.

**Comment by icing** [comment]
I agree that the relationship between `multi` lifetime and its connection cache could be made more clear in the documentation.

**Comment by bagder** [comment]
I made #15109 in an attempt to help shed some more light on this.

**Comment by steve-chavez** [comment]
This is solved now then. Many thanks!
