### ISSUE TITLE
Network is Normal but Curl Always Returns CURLE_COULDNT_CONNECT Due to FD_SETSIZE Limitation

### ISSUE THREAD

**Issue by churchill-zhang** [curl/curl#15080]
### Description
Our project uses libuv and curl for network communication. The application spawns many threads, with each thread using libuv and curl. As a result, the total file descriptor (fd) usage is quite high, peaking above 1024. We used setrlimit to increase the maximum number of fds to 32768. However, in curl, the internal limit is set by FD_SETSIZE to 1024, leading to an issue.

In curl's select.h at line 1024, FD_SETSIZE is used as the fd limit. This causes VERIFY_SOCK in select.c to set the global errno via SET_SOCKERRNO when fd exceeds FD_SETSIZE.

This exception causes SOCKET_WRITABLE(ctx->sock, 0) at line 1346 in cf-socket.c to return a non-zero rc, leading to the error branch at line 1363. The call to verifyconnect(ctx->sock, &ctx->error) at line 1364 ignores the return value, causing a normal connection to be mistakenly treated as an error, resulting in CURLE_COULDNT_CONNECT at line 1365.

From the application's perspective, the network is normal, but curl continuously returns CURLE_COULDNT_CONNECT.

### Steps to Reproduce
Create an application that uses libuv and curl in multiple threads.
Increase the maximum number of file descriptors to 32768 using setrlimit.
Observe that curl returns CURLE_COULDNT_CONNECT when fd usage peaks above 1024.
Expected Behavior
curl should handle file descriptors above 1024 correctly and not return CURLE_COULDNT_CONNECT erroneously.

### Actual Behavior
curl returns CURLE_COULDNT_CONNECT due to the FD_SETSIZE limit being exceeded.

### Additional Context
Here are the relevant code links:

select.h (line 1024): https://github.com/curl/curl/blob/master/lib/select.h
select.c (VERIFY_SOCK): https://github.com/curl/curl/blob/master/lib/select.c
cf-socket.c (lines 1346-1365): https://github.com/curl/curl/blob/master/lib/cf-socket.c

### I expected the following

# #https://github.com/curl/curl/blob/master/lib/cf-socket.c 1352
```
else if((rc & CURL_CSELECT_ERR) || rc == CURL_CSELECT_OUT || cf->conn->bits.tcp_fastopen) {
    if(verifyconnect(ctx->sock, &ctx->error)) {
      /* we are connected with TCP, awesome! */
      ctx->connected_at = Curl_now();
      set_local_ip(cf, data);
      *done = TRUE;
      cf->connected = TRUE;
      CURL_TRC_CF(data, cf, "connected");
      return CURLE_OK;
    }
    if (rc & CURL_CSELECT_ERR) {
      result = CURLE_COULDNT_CONNECT;
    }
  }
```
# #https://github.com/curl/curl/blob/master/lib/select.h 106
```
#define VERIFY_SOCK(x) do {                     \
    if(!VALID_SOCK(x)) {      \
      SET_SOCKERRNO(EINVAL);                    \
      return -1;                                \
    }                                           \
  } while(0)
#endif
```

### curl/libcurl version

master and 8.10.0

### operating system

Android and iOS

**Comment by dfandrich** [comment]
This shouldn't happen if poll is used. I suspect this is issue
https://github.com/curl/curl/issues/15013 which was just fixed a few days ago.
Does this still happen if you use a nightly snapshot of libcurl?

**Comment by bagder** [comment]
Alternatively, edit `lin/curl_config.h` after configure has run and make sure these are defined:
~~~c
/* If you have a fine poll */
#define HAVE_POLL_FINE 1

/* Define to 1 if you have the <poll.h> header file. */
#define HAVE_POLL_H 1

**Comment by churchill-zhang** [comment]
When using HAVE_POLL_FINE, the VERIFY_SOCK function is not called, which allows us to avoid checks for file descriptors exceeding FD_SETSIZE. However, the select branch still has issues with how it handles FD_SETSIZE. It is advisable not to use FD_SETSIZE as the upper limit for file descriptors, as this does not account for scenarios where the limit is dynamically modified via setrlimit.

In practice, when making connect or connectx system calls, if the file descriptor exceeds the limit, the system will automatically set errno to indicate an invalid file descriptor. Therefore, there is no need for an explicit check for this condition.

**Comment by churchill-zhang** [comment]
I am using libcurl in a manner similar to the example described at https://curl.se/libcurl/c/multi-uv.html.

**Comment by dfandrich** [comment]
> In practice, when making connect or connectx system calls, if the file
> descriptor exceeds the limit, the system will automatically set errno to
> indicate an invalid file descriptor. Therefore, there is no need for an
> explicit check for this condition.

That's true when poll() is being used, but not with select(). I hope there
aren't any checks in the poll case.

**Comment by bagder** [comment]
> It is advisable not to use FD_SETSIZE as the upper limit for file descriptors, as this does not account for scenarios where the limit is dynamically modified via setrlimit.

Feel free to propose improvements to the code if you can think of any. It needs to be portable and I'm pretty sure some systems use the FD_SETSIZE macro in the FD_*() macros so having it set to a value that is lower than the actual amount of possible sockets is likely to not work properly.

Basically, using select() beyond 1024 sockets is a tricky thing to get right. I think your focus should be to get  poll() recognized and used. Or perhaps even use another event method that scales better.

**Comment by beingPro007** [comment]
> > It is advisable not to use FD_SETSIZE as the upper limit for file descriptors, as this does not account for scenarios where the limit is dynamically modified via setrlimit.
> 
> Feel free to propose improvements to the code if you can think of any. It needs to be portable and I'm pretty sure some systems use the FD_SETSIZE macro in the FD_*() macros so having it set to a value that is lower than the actual amount of possible sockets is likely to not work properly.
> 
> Basically, using select() beyond 1024 sockets is a tricky thing to get right. I think your focus should be to get poll() recognized and used. Or perhaps even use another event method that scales better.

I'm new to system programming, and I’m eager to learn. I've figured out what FD_SETSIZE is and have some understanding of different system calls. I just need your simple guidance on what steps to take next. Your help is really important to me, and I’m ready to give it my all! Sir eagerly waiting for your reply...

**Comment by churchill-zhang** [comment]
> > > It is advisable not to use FD_SETSIZE as the upper limit for file descriptors, as this does not account for scenarios where the limit is dynamically modified via setrlimit.
> > 
> > 
> > Feel free to propose improvements to the code if you can think of any. It needs to be portable and I'm pretty sure some systems use the FD_SETSIZE macro in the FD_*() macros so having it set to a value that is lower than the actual amount of possible sockets is likely to not work properly.
> > Basically, using select() beyond 1024 sockets is a tricky thing to get right. I think your focus should be to get poll() recognized and used. Or perhaps even use another event method that scales better.
> 
> I'm new to system programming, and I’m eager to learn. I've figured out what FD_SETSIZE is and have some understanding of different system calls. I just need your simple guidance on what steps to take next. Your help is really important to me, and I’m ready to give it my all! Sir eagerly waiting for your reply...

Forcing -DHAVE_POLL_FINE=ON can be a workaround, allowing you to bypass the FD_SETSIZE check

**Comment by beingPro007** [comment]
Let me try can you assign it to me

**Comment by bagder** [comment]
> Let me try can you assign it to me

What does that mean? The main issue discussed here is already fixed - poll should be detected fine when running configure for cross-compiled Android.

**Comment by churchill-zhang** [comment]
> Let me try can you assign it to me

Curl doesn't need any changes for now. I have forced the use of specific code in vcpkg

```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS 
        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/cmake-project-include.cmake"
        "-DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}"
        ${FEATURE_OPTIONS}
        ${OPTIONS}
        -DHAVE_POLL_H=ON
        -DHAVE_POLL_FINE=ON
        -DBUILD_TESTING=OFF
        -DENABLE_CURL_MANUAL=OFF
        -DCURL_CA_FALLBACK=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_Perl=ON
    OPTIONS_DEBUG
        -DENABLE_DEBUG=ON
)
```
and applied a patch. Additionally, verifyconnect will return CURLE_OK when it returns true.
```
diff --git a/lib/cf-socket.c b/lib/cf-socket.c
index 729e38f88..b8a5f0f99 100644
--- a/lib/cf-socket.c
+++ b/lib/cf-socket.c
@@ -1348,7 +1348,7 @@ static CURLcode cf_tcp_connect(struct Curl_cfilter *cf,
     CURL_TRC_CF(data, cf, "not connected yet");
     return CURLE_OK;
   }
-  else if(rc == CURL_CSELECT_OUT || cf->conn->bits.tcp_fastopen) {
+  else if((rc & CURL_CSELECT_ERR) || rc == CURL_CSELECT_OUT || cf->conn->bits.tcp_fastopen) {
     if(verifyconnect(ctx->sock, &ctx->error)) {
       /* we are connected with TCP, awesome! */
       ctx->connected_at = Curl_now();
@@ -1358,10 +1358,9 @@ static CURLcode cf_tcp_connect(struct Curl_cfilter *cf,
       CURL_TRC_CF(data, cf, "connected");
       return CURLE_OK;
     }
-  }
-  else if(rc & CURL_CSELECT_ERR) {
-    (void)verifyconnect(ctx->sock, &ctx->error);
-    result = CURLE_COULDNT_CONNECT;
+    if (rc & CURL_CSELECT_ERR) {
+      result = CURLE_COULDNT_CONNECT;
+    }
   }
 
 out:

```

**Comment by bagder** [comment]
> and applied a patch. Additionally, verifyconnect will return CURLE_OK when it returns true.

This patch seems unrelated to this issue. Can you elaborate on why you need this and what it fixes? Maybe even consider doing it as a PR if you think this is an improvement for everyone?

**Comment by churchill-zhang** [comment]
> is

Based on the definition and implementation of the verifyconnect function, if the function returns true, it indicates that the socket is currently usable. Previously, there was an issue with SOCKET_WRITABLE, but it can now be caught and has been restored. Therefore, I believe the return value of verifyconnect should not be ignored, and CURLE_COULDNT_CONNECT should not be returned. I'm unsure if my thoughts conflict with the original author's design, which is why I haven't submitted a PR. What are your thoughts on this issue of ignoring the return value?

**Comment by bagder** [comment]
> What are your thoughts on this issue of ignoring the return value?

I think you are adding a second *completely different* subject in the same issue; which is considered a bad idea. Please create a separate issue for this.

**Comment by churchill-zhang** [comment]
> > What are your thoughts on this issue of ignoring the return value?
> 
> I think you are adding a second _completely different_ subject in the same issue; which is considered a bad idea. Please create a separate issue for this.

I think this response makes sense. I will close the current issue and open a new one.
