### ISSUE TITLE
Tracing doesn't log all SETTINGS parameters

### ISSUE THREAD

**Issue by bt90** [curl/curl#15093]
### I did this

```sh
curl -s --trace - --trace-config http/2 https://caddyserver.com
```

```
== Info: [HTTP/2] [0] <- FRAME[SETTINGS, len=30]
== Info: [HTTP/2] [0] MAX_CONCURRENT_STREAMS: 250
== Info: [HTTP/2] [0] ENABLE_PUSH: TRUE
== Info: [HTTP/2] [0] notify MAX_CONCURRENT_STREAMS: 250
```

### I expected the following

curl should log all known settings parameters and their values. This is crucial to simplify debugging cases like https://github.com/caddyserver/caddy/pull/6567#issuecomment-2381418598 where the presence of `ENABLE_CONNECT_PROTOCOL` changes how websockets are bootstrapped.

### curl/libcurl version

curl 8.10.1

### operating system

curlimages/curl

**Comment by bagder** [comment]
This is not a bug, just something with room for improvement. Feel free to help curl improve.
