### ISSUE TITLE
curl 7.54.0 compiling with SSL not taking custom location

### ISSUE THREAD

**Issue by saeohioalpha** [curl/curl#1510]
### I compiled OpenSSL and CURL from source. 
While compiling CURL I attempted to use a manually compiled version of OpenSSLv1.1.0e that I have already downloaded and compiled for my nginx install. 

I am unable to get ./configure to recognize the custom version of OpenSSL
I specified (trying to cover all my bases here)

> SSL_CPPFLAGS="-I/opt/nginx_ssl/include" 
> CPPFLAGS="-I/opt/nginx_ssl/include" 
> LDFLAGS="-L/opt/nginx_ssl/lib" 
> SSL_LDFLAGS="-L/opt/nginx_ssl/lib" 
> OPENSSL_CFLAGS="-I/opt/nginx_ssl/include" 
> SSL_LIBS="-L/opt/nginx_ssl/lib -lssl -lcrypto" 
> OPENSSL_LIBS="-L/opt/nginx_ssl/lib -lssl -lcrypto" 
> PKG_CONFIG_PATH="/opt/nginx_ssl/lib/pkgconfig/"

and I get 

> checking for pkg-config... (cached) /usr/bin/pkg-config
checking for openssl options with pkg-config... found
configure: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure: pkg-config: SSL_LDFLAGS: ""
configure: pkg-config: SSL_CPPFLAGS: ""

If I specify the path in --with-ssl=/opt/nginx_ssl It actually picks up the pkg-config variables, but doesn't actually configure to include SSL. 

> configure: PKG_CONFIG_LIBDIR will be set to "/opt/nginx_ssl/lib/pkgconfig"
> checking for pkg-config... (cached) /usr/bin/pkg-config
> checking for openssl options with pkg-config... found
> configure: pkg-config: SSL_LIBS: "-lssl -lcrypto"
> configure: pkg-config: SSL_LDFLAGS: "-L/opt/nginx_ssl/lib"
> configure: pkg-config: SSL_CPPFLAGS: "-I/opt/nginx_ssl/include"
> checking for HMAC_Update in -lcrypto... no
> checking for HMAC_Init_ex in -lcrypto... no
> checking for ssl_version in -laxtls... no
> configure: WARNING: SSL disabled, you will not be able to use HTTPS, FTPS, NTLM and more.
> configure: WARNING: Use --with-ssl, --with-gnutls, --with-polarssl, --with-cyassl, --with-nss, --with-axtls, --with-winssl, or --with-darwinssl to address this.
> 

### curl/libcurl version

[curl -V output]
curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.2k zlib/1.2.8 nghttp2/1.23.0-DEV librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

/usr/bin/openssl version
OpenSSL 1.0.2k  26 Jan 2017

/opt/nginx_ssl/bin/openssl version
OpenSSL 1.1.0e  16 Feb 2017

### operating system
ub16.04.2
Linux web01 4.9.15-x86_64-linode81 #1 SMP Fri Mar 17 09:47:36 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
Did you install only the static versions of the libs? Then you need to tell configure to use -ldl and -lpthread.

When --with-ssl isn't enough, the clues of what's wrong and what's needed are all in config.log. If it can't find "HMAC_Update", the lib isn't working. But if the problem is the static-only version as mentioned above, there are usually also some error messages in config.log that helps pointing in that direction.

I really don't think this is a bug in the configure script. I've built with custom openssl installs using configure, almost daily, for years.

**Comment by saeohioalpha** [comment]
Thanks for that heads up, didnt realize I needed that. Also for the variables to be detected, I had to include them on the same line as the ./configure. 

So I was able to get it to compile correctly using:

`CPPFLAGS="-I/opt/nginx_ssl/ -I/opt/nginx_ssl/include" LDFLAGS="-L/opt/nginx_ssl/lib" LIBS="-ldl -lpthread" ./configure --with-nghttp2=/usr/local --with-ssl 
`

> curl -V
> curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.54.0 OpenSSL/1.1.0e zlib/1.2.8 nghttp2/1.23.0-DEV librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
> Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy



However now I have another issue, not sure if it's related:
/usr/local/lib/libcurl.so.4: no version information available

I was able to see a few reports of this online, but what I see involves having curl installed via system repositories as in addition to the statically compiled one. I only have the static one (removed the system on prior to compilation). 

also, I checked in /usr/local/lib it has the newly compiled (by timestamp) version

> lrwxrwxrwx  1 root root    16 May 25 17:09 libcurl.so -> libcurl.so.4.4.0
> lrwxrwxrwx  1 root root    16 May 25 17:09 libcurl.so.4 -> libcurl.so.4.4.0
> -rwxr-xr-x  1 root root  3.8M May 25 17:09 libcurl.so.4.4.0

**Comment by jay** [comment]
> /usr/local/lib/libcurl.so.4: no version information available

Which program shows you that? I think that happens if you've compiled a program against a libcurl that has versioned symbols, but when the program runs the libcurl it loads doesn't. Try passing `--enable-versioned-symbols` to configure.

**Comment by saeohioalpha** [comment]
I noticed 2 programs showing that so far, cmake and PassengerAgent.

I will try that configure option and see how it works.

**Comment by jay** [comment]
Yes I see that with cmake in Ubuntu, so that is what is happening. If the versions are the same you don't need to worry about it

**Comment by saeohioalpha** [comment]
I tried with the enable-versioned-symbols, now I get

PassengerAgent: /usr/local/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by PassengerAgent)

**Comment by saeohioalpha** [comment]
I double checked, my openssl version supports SSLv3 if that is what this error is referring to

> openssl ciphers -v 'SSLv3'
ECDHE-RSA-AES256-SHA    SSLv3 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES256-SHA  SSLv3 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1

**Comment by jay** [comment]
The symbols don't match I guess, probably they were built against different SSL backends. dump the symbols in your system packaged libcurl:
objdump -T  /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
you should see a bunch of things like
0000000000039320 g    DF .text	00000000000007c5  CURL_OPENSSL_3 curl_getdate
0000000000028450 g    DF .text	00000000000000bb  CURL_OPENSSL_3 curl_mfprintf
but probably OPENSSL is some other SSL name

**Comment by saeohioalpha** [comment]
Indeed I see 

> 000000000006d0b0 g    DF .text	00000000000002dc  CURL_OPENSSL_4 curl_multi_setopt
> 0000000000071190 g    DF .text	00000000000007c2  CURL_OPENSSL_4 curl_getdate
> 00000000000613c0 g    DF .text	00000000000000bb  CURL_OPENSSL_4 curl_mfprintf
> 000000000006f680 g    DF .text	0000000000000041  CURL_OPENSSL_4 curl_multi_socket
> 000000000005f1f0 g    DF .text	0000000000000116  CURL_OPENSSL_4 curl_version
> 00000000000671c0 g    DF .text	00000000000000ac  CURL_OPENSSL_4 curl_easy_send
> 00000000000667e0 g    DF .text	000000000000004f  CURL_OPENSSL_4 curl_global_cleanup
> 0000000000061480 g    DF .text	000000000000002d  CURL_OPENSSL_4 curl_mvsprintf
> 

Is there anyway to get this to work without having two installed versions, if thats even possible?

**Comment by saeohioalpha** [comment]
I don't know if I am causing myself headaches down the line, but I have fixed the issue (so far).

I edited the curl-7.54.0/lib/libcurl.vers.in file
I replaced
`CURL_@CURL_LT_SHLIB_VERSIONED_FLAVOUR@4`
with
`CURL_@CURL_LT_SHLIB_VERSIONED_FLAVOUR@3`

recompiled/installed and now I have the CURL_OPENSSL_3 versions listed. Also, the programs cmake and PassengerAgent are not throwing issues and starting without a problem.

Also the CLI curl program is working without giving me an issue.

**Comment by jay** [comment]
I don't know why they show CURL_OPENSSL_3 even though it's 4.4.0, and I don't know if it's appropriate to change that. @ghedo ?

**Comment by bagder** [comment]
Either way, decisions and builds done on and for Debian or Ubuntu aren't really issues for this project to deal with. I can't see any curl issue left to handle here...

**Comment by saeohioalpha** [comment]
Fair enough, thanks for everyones help getting this to compile!
