### ISSUE TITLE
semi-random crash

### ISSUE THREAD

**Issue by zmangen** [curl/curl#15127]
### I did this

hello, a seemingly random crash after update to 8.10.1 , happens on both x86 and x64, with the following stack traces:

### Stack trace 1
```c
Curl_node_next(Curl_llist_node * n) Line 228    C
Curl_cpool_check_limits(Curl_easy * data, connectdata * conn) Line 319              C
create_conn(Curl_easy * data, connectdata * * in_connect, bool * async) Line 3558        C
Curl_connect(Curl_easy * data, bool * asyncp, bool * protocol_done) Line 3720 C
multi_runsingle(Curl_multi * multi, curltime * nowp, Curl_easy * data) Line 1900            C
curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2653             C
``` 

```c
FAULTING_SOURCE_CODE:  
   224: size_t Curl_llist_count(struct Curl_llist *list)
   225: {
   226:   DEBUGASSERT(list);
   227:   DEBUGASSERT(list->_init == LLISTINIT);
>  228:   return list->_size;
   229: }
``` 
![image](https://github.com/user-attachments/assets/2a05eb8e-fc14-411a-97ed-67f985e727d1)

### Stack trace 2
```c
Curl_node_elem(Curl_llist_node * n) Line 236   C
cpool_bundle_get_oldest_idle(cpool_bundle * bundle) Line 538              C
Curl_cpool_check_limits(Curl_easy * data, connectdata * conn) Line 323              
create_conn(Curl_easy * data, connectdata * * in_connect, bool * async) Line 3558        C
Curl_connect(Curl_easy * data, bool * asyncp, bool * protocol_done) Line 3718 C
multi_runsingle(Curl_multi * multi, curltime * nowp, Curl_easy * data) Line 1900            C
curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2653             C
``` 

the **n->_ptr;** and the **n** pointer is uninitialized, having value **0xdddddddddddddddd**. Similarly, the entire pointer bundle referencing the **cpool_bundle** structure is in the same state.

![image](https://github.com/user-attachments/assets/c2d9db5d-b717-4e05-8ea4-8dab610aa886)

### Stack trace 3
```cCurl_node_elem(Curl_llist_node * n) Line 236   C
cpool_bundle_get_oldest_idle(cpool_bundle * bundle) Line 538              C
Curl_cpool_check_limits(Curl_easy * data, connectdata * conn) Line 323              C
create_conn(Curl_easy * data, connectdata * * in_connect, bool * async) Line 3558        C
Curl_connect(Curl_easy * data, bool * asyncp, bool * protocol_done) Line 3718 C
multi_runsingle(Curl_multi * multi, curltime * nowp, Curl_easy * data) Line 1900            C
curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2653             C
```
![image](https://github.com/user-attachments/assets/7f3aee60-d801-498e-ac5e-3bed5d38c3e4)

following commit seems to be related
[https://github.com/curl/curl/commit/1be704e17e70b626f89108f33b59bcdeb16f4b0e](https://github.com/curl/curl/commit/1be704e17e70b626f89108f33b59bcdeb16f4b0e)

**any help is greatly appreciated,
thank you**

### I expected the following

no crash

### curl/libcurl version

curl 8.10.1

### operating system

Windows 7, 10, and 11 on x86 and x64.

**Comment by jay** [comment]
If you are threading it would be helpful if you could confirm that you are following the [guidelines](https://curl.se/libcurl/c/threadsafe.html). Linked list crashes are usually related. However there have been some changes as you rightly pointed out, so that might need investigating.

/cc @icing

**Comment by bagder** [comment]
Without a way for us to reproduce this problem, @jay's advice is the only thing we can offer right now.

**Comment by honzaq** [comment]
Hello, we experienced the same with 8.10.1, we just moved from the older version. Crash is rare hard to reproduce so I cannot give you tip how to reproduce it.

Stack trace 1:
```
Curl_node_next+0x6 [curl\lib\llist.c @ 228]
Curl_cpool_check_limits+0xcb [curl\lib\conncache.c @ 319]
create_conn+0x555 [curl\lib\url.c @ 3558]
Curl_connect+0x2a [curl\lib\url.c @ 3720]
multi_runsingle+0x21b [curl\lib\multi.c @ 1900]
curl_multi_perform+0xa0 [curl\lib\multi.c @ 2653]
```

Stack trace 2:
```
Curl_dyn_len+0x6 [curl\lib\dynbuf.c @ 266]
cpool_bundle_get_oldest_idle+0x36 [curl\lib\conncache.c @ 538]
Curl_cpool_check_limits+0x10d [curl\lib\conncache.c @ 323]
create_conn+0x555 [curl\lib\url.c @ 3558]
Curl_connect+0x2a [curl\lib\url.c @ 3720]
multi_runsingle+0x21b [curl\lib\multi.c @ 1900]
curl_multi_perform+0xa0 [curl\lib\multi.c @ 2653]
```

**Comment by bagder** [comment]
Let's me reemphasize that this issue has nothing for us to act on.

**Comment by zmangen** [comment]
> Let me reemphasize that this issue has nothing for us to act on.

thanks, we believe the fix has been already made in master, with this commit:
https://github.com/curl/curl/commit/699a2df3505898393733a67bf3e9243637b87400
from what we could gather, the while loop spun even after the connection pool was empty and caused the crash

**Comment by bagder** [comment]
Excellent, thanks for confirming things for us!

**Comment by honzaq** [comment]
Hi, we still experiencing this crash even with [699a2df](https://github.com/curl/curl/commit/699a2df3505898393733a67bf3e9243637b87400) fix. So this issue is not solved.

**Comment by icing** [comment]
> Hi, we still experiencing this crash even with [699a2df](https://github.com/curl/curl/commit/699a2df3505898393733a67bf3e9243637b87400) fix. So this issue is not solved.

Unless you see the same crash, e.g. stacktrace, open a new issue with details, please.

**Comment by honzaq** [comment]
Callstack seems to be same 
```
[0x1]   Curl_cpool_check_limits+0x12f
[0x2]   create_conn+0x79d
[0x3]   Curl_connect+0x49
[0x4]   multi_runsingle+0x26b
[0x5]   curl_multi_perform+0xbe
[0x6]   asw::repository::multi_curl::process_active_requests+0x18
[0x7]   asw::repository::multi_curl::worker+0x169
```
on
`while(bundle && (Curl_llist_count(&bundle->conns) >= dest_limit)) {`

**Comment by icing** [comment]
Thanks. I fail to see how this could be possible with the fix in 699a2df. Do you have the value of `bundle` at the time of the crash?

**Comment by honzaq** [comment]
![memory](https://github.com/user-attachments/assets/295619c4-2305-4928-ab37-1aebe52a26cf)

**Comment by icing** [comment]
@honzaq I am trying to reproduce a test case that triggers this, but have no luck so far. Can you tell me anything more about your application?

* does it run multi-threaded?
* does it limit the connections to hosts, e.g. `CURLMOPT_MAX_HOST_CONNECTIONS`
* does it use a CURLSH share object for caching connections?

Thanks.

**Comment by honzaq** [comment]
hi, first the crash is rare, and we are not able to reproduce it with some exact steps.
* only one thread using the curl_multi_perform 
* only think we share is CURL_LOCK_DATA_SSL_SESSION
* we set CURLMOPT_MAX_HOST_CONNECTIONS and we even reduce the number when connection is bad
