### ISSUE TITLE
CURLOPT_PREQUOTE not working for SFTP

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#1514]
We use libCURL and CURLOPT_PREQUOTE works fine for FTP.
But for SFTP (SSH), the CURLOPT_QUOTE and CURLOPT_POSTQUOTE work.

We would like to use CURLOPT_PREQUOTE for a mkdir command, but it is not executed.

Tested with LibCURL 7.53.1, LibSSH 1.8.0.

**Comment by bagder** [comment]
Ack. Seems we just never implemented PREQUOTE for SFTP, contrary to what the documentation claims...

**Comment by bagder** [comment]
Thanks for pointing this out. Unfortunately the only "fix" so far is adding this issue to the TODO and an update to the man page so that the list of protocols for which the option works is correct.
