### ISSUE TITLE
Missing libcurl.lib

### ISSUE THREAD

**Issue by blul1ghtz** [curl/curl#15158]
### I did this

included all include files into my project to build with curl but am getting unresolved externals (likely missing libcurl.lib)

### I expected the following

it to work

### curl/libcurl version

8.10.1

### operating system

Windows

**Comment by jay** [comment]
This post is lacking a lot of information. How did you build libcurl? What is the actual output of your project? Did you read any of the documentation? For example, winbuild readme has a section [Building your own application with libcurl (Visual Studio example)](https://github.com/curl/curl/blob/curl-8_10_1/winbuild/README.md#building-your-own-application-with-libcurl-visual-studio-example).

**Comment by blul1ghtz** [comment]
I cant remember but i either downloaded this git repo or the files at curl.se 8.10 and many others and attempted to build one of them, couldn't find libcurl.lib anywhere including in any other files i downloaded, unless im just confused and ur actually meant to build ur project alongside curl project somehow, im pretty inexperienced with visual studios layout.

**Comment by jay** [comment]
Sorry but without information about how you built curl we can't help you with that. Please read the readme for whichever build method you are using.

**Comment by blul1ghtz** [comment]
i compiled it with visual studio console "make --build" pretty sure

**Comment by jay** [comment]
That is not enough information. You may have done xxx or yyy is just not enough. Generally speaking if you use Visual Studio to build libcurl then you should end up with a lib file. I suggest use the winbuild build method that I linked to earlier. It's pretty straightforward.
