### ISSUE TITLE
CURLOPT_FTP_CREATE_MISSING_DIRS not working for SFTP

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#1515]
We use libCURL and CURLOPT_FTP_CREATE_MISSING_DIRS works fine for FTP.
But for SFTP it has no effect.

Tested with LibCURL 7.53.1, LibSSH 1.8.0.

**Comment by bagder** [comment]
It is used in the code: https://github.com/curl/curl/blob/master/lib/ssh.c#L1798 can you break-point and see why it doesn't help your case?

**Comment by MonkeybreadSoftware** [comment]
I in the log I see

Authentication complete
Upload failed: Permission denied (3/-31)

for another server I see:

Authentication complete
Creating directory '/test6'
We are completely uploaded and fine

Maybe it would be good if we get some details on the errors like using libssh2_session_last_error to get more details?

**Comment by bagder** [comment]
> Maybe it would be good if we get some details on the errors like using libssh2_session_last_error to get more details?

Sure, I recommend sprinkling the code with informational code in order to better understand the state when it gets there. That's also why I recommend break-pointing since then you can easily look at all the local variables and more.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by VishnuvardhanReddyAnde** [comment]
Hi,

We use LIBCURL (7.53.1) and CURLOPT_FTP_CREATE_MISSING_DIRS, works fine for FTP.
But for SFTP, it is not working.

Getting below error.

Authentication complete
Upload failed: Permission denied (3/-31)

Could you please let us know the possible reasons for this failure?

Thanks,
Vishnu

**Comment by bagder** [comment]
If you can tell us how to reproduce (on a modern curl version) then we can consider re-opening this bug. If not, give us a lot more details on what happens within curl and libssh2 when the problem is triggered.

**Comment by hauhan** [comment]
Hi,

I have same problem with SFTP that CURLOPT_FTP_CREATE_MISSING_DIRS not create directory. (Use SolarWinds SFTP/SCP) Maybe it is SolarWinds problem not curl, but Filezilla SFTP can create directory.

curl return CURLE_REMOTE_ACCESS_DENIED (9)

Thanks, :)
hauhan
