### ISSUE TITLE
Semicolon using -F is not working like expected

### ISSUE THREAD

**Issue by Neptunespace** [curl/curl#15202]
### I did this

Hello everyone,

Today i want to report a bug using the -F in curl that not manage correctly the semicolon ";" symbol.

When i do this command, inside trace.txt we can see curl sending only "John" even with a backslash before the semicolon i get only "John" in the exported data from curl to my api server :
```curl -sL --insecure "https://127.0.0.1/api" -F "name=John; Doe" -F "city=new york" --trace trace.txt```

but when i use curl with --data-binary, the ";" is send and i get full name "John; Doe" in my api

### I expected the following

Curl need to send the ";" and the following stuff to my api using the -F option

### curl/libcurl version

curl 8.9.1

### operating system

Alpine 3.20.2 (docker container)

**Comment by dfandrich** [comment]
The documentation explains how --form works:

    Quoting must also be applied to non-file data if it contains semicolons,
    leading/trailing spaces or leading double quotes:

Try putting quotes around the data, i.e. -F 'name="John; Doe"'

**Comment by emanuele6** [comment]
You can also just use `--form-string` instead of `-F`: `--form-string 'name=John; Doe'`.
That is what you should be using in scripts instead of `-F "name=$v"` to not allow the arbitrary `$v` value to inject special `curl -F` syntax.
