### ISSUE TITLE
curl_easy_getinfo with CURLINFO_TLS_SSL_PTR not able to get compiled

### ISSUE THREAD

**Issue by gnanagurun** [curl/curl#1524]
### I did this
curl_easy_getinfo with CURLINFO_TLS_SSL_PTR gives compilation error - "call to '_curl_easy_getinfo_err_curl_slist' declared with attribute warning: curl_easy_getinfo expects a pointer to 'struct curl_slist *' for this info". I just passing the address of this variable struct curl_tlssessioninfo *tls_ssl" to curl_easy_getinfo. To solve this compilation issue, i have tried to replace this with "struct curl_slist*". Able to compile with this change but while running it gives segmentation fault even there is NULL checking in my code.
### curl/libcurl version
libcurl version: 7.52.1 / OpenSSL version: 1.1.0d
[curl -V output]

### operating system
Centos 6.5

**Comment by gnanagurun** [comment]
Below is the code snippet
_// struct curl_tlssessioninfo *tls_ssl = NULL; commented out due to compilation issue
 struct curl_slist *tls_ssl = NULL;
curl_easy_getinfo(curl_handle, CURLINFO_TLS_SSL_PTR, &tls_ssl);
if (tls_ssl && tls_ssl->data) // NULL checking
{
printf("tls_ssl ->data = %s\n", tls_ssl->data); // --> This is the place where segfault occur
}_

Please let me know how to resolve the compilation issue when use "struct curl_tlssessioninfo"

**Comment by jzakrzewski** [comment]
I don't think that ```tls_ssl->data``` is a NULL-terminated string. I'd guess that printf simply reads too much because of that and this is the cause of the segfault.

**Comment by gnanagurun** [comment]
This cannot be the cause of segfault. Even it occur if i just access the first character of tls_ssl->data[0]. It seems the type should be **struct curl_tlssessioninfo**. How to solve the compilation issue?

**Comment by bagder** [comment]
See #1525 for my suggested fix.
