### ISSUE TITLE
NetworkManager crashes during connectivity check with latest libcurl 8.10.1

### ISSUE THREAD

**Issue by fschrempf** [curl/curl#15276]
### I did this

Upgraded my Manjaro system to use NM 1.48.12 and curl 8.10.1. Now the NetworkManager crashes when doing a connectivity check using curl.

Downgrading curl to 8.10.0 resolves the problem. A bisect shows that the commit that triggers the crash is this one: https://github.com/curl/curl/commit/48f61e781a01e6a8dbc4a347e280644b1c68ab6a. Reverting the commit on top of 8.10.1 makes the issue go away.

I opened a [report for NM here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1646), as the crash seems to happen within NM and not within libcurl. Still, I guess the API hasn't changed and a change in libcurl shouldn't cause such a problem (unless NM does something completely wrong, I guess). Please correct me if reporting a bug here is the wrong conclusion.

Further details can be found in [this thread in the Manjaro](https://forum.manjaro.org/t/networkmanager-crashing-after-recent-update-of-curl-package/) forum.

### I expected the following

no crashes

### curl/libcurl version

curl 8.10.1

### operating system

Manjaro "Xahea" 24.1.1

**Comment by bagder** [comment]
Without more details and possibly a stack trace it is not really possible for us to tell if this is a problem in network manager or not or even it is is a curl problem. libcurl was changed in a way that has surprised a few applications.

It is possible that 461ce6c6160b86439 changes things a little.

**Comment by fschrempf** [comment]
> It is possible that [461ce6c](https://github.com/curl/curl/commit/461ce6c6160b86439ddd74c59541231ec9e8558e) changes things a little.

Thanks, cherry-picking this on top of 8.10.1 makes the crash go away for me. Is this enough to justify a bugfix release or do we need to do further debugging in some ways?

**Comment by bagder** [comment]
That commit will be in the curl version planned to ship on November 5.

**Comment by fschrempf** [comment]
Ok, I guess I won't spend any more time debugging this and just wait for the new release to land. Thanks for your help and your work!
