### ISSUE TITLE
[cli] `--remote-name` with multiple URLs *sometimes* outputs content

### ISSUE THREAD

**Issue by tobwen** [curl/curl#15304]
### I did this

``` sh
mkdir out
for f in {1..50}; do
    curl -sO --output-dir out/ --url "https://www.example.org/1" --url "https://www.example.org/2" | grep doctype;
done | wc -l
```

### I expected the following

1. I expected two files in directory "out", since neither one of the `--fail` commands nor `--remove-on-error` nor others are supplied (the website throws error `404` on both links). Sometimes file `1` is created, sometimes not.
2. `wc -l` should either be `0` (never output HTML on error) or `50` (always output HTML on error), but the amount is somewhere in between (I got `28`, `32`, `37`, etc. on various runs).
3. This bug also occures on `--parallel`.
4. This bug also occures on `--config` with multiple `url = https://...`.
5. I also tried adding `-J`, with the same behaviour.

### curl/libcurl version

```
curl 8.11.0-DEV (x86_64-pc-linux-gnu) libcurl/8.11.0-DEV OpenSSL/3.0.14 zlib/1.2.13 libpsl/0.21.2 nghttp2/1.52.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets
```

### operating system

```
Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
```

**Comment by dfandrich** [comment]
-O (a.k.a. --remote-name) only works with a single URL.  To write all URLs to files, you want --remote-name-all

**Comment by tobwen** [comment]
> -O (a.k.a. --remote-name) only works with a single URL. To write all URLs to files, you want --remote-name-all

oops, I thought `--remote-name` would do both. So `--remote-header-name-all` is missing?
