### ISSUE TITLE
MacOS: curl --insecure shouldn't disable SNI

### ISSUE THREAD

**Issue by schweikert** [curl/curl#1533]
### I did this

    $ curl --insecure https://david.schweikert.ch >/dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

### I expected the following

It seems that when --insecure is specified, curl doesn't do SNI on MacOS. That is a problem also with environments such as OpenShift, where the SNI information is used to route the traffic to the correct application. Note that this behavior is also not documented (i.e. that --insecure has an effect on how the SSL handshake is done). Disabling SNI should be a separate option, if required.

### curl/libcurl version

    $ curl --version
    curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
    Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

### operating system

MacOS Sierra 10.12.5

**Comment by schweikert** [comment]
brew install curl --with-openssl -> works (SNI is enabled also with --insecure)
brew install curl -> doesn't work (SNI disabled)

**Comment by schweikert** [comment]
Sorry, duplicate of #998

**Comment by wraila** [comment]
@schweikert I'm faced with similar issue in Openshift. You described a solution
```
brew install curl --with-openssl -> works (SNI is enabled also with --insecure)
```
which did not work for me. You also reference closed issue #998, which indicates there is not a solution.

Did you actually get this to work with `brew install curl --with-openssl `?

**Comment by schweikert** [comment]
@wraila: Yes, it did. Make sure that you use homebrew's version of curl (not /usr/bin/curl).

**Comment by bagder** [comment]
In the most recent macos version, Apple switched to LibreSSL for curl so now it is possible to do with the native one as well.
