### ISSUE TITLE
websocket, avoid blocking sends

### ISSUE THREAD

**Issue by zhufan** [curl/curl#15378]
### I did this

curl_ws_send may block when generating a 0-length frame: 

https://github.com/curl/curl/blob/b327a53f09f58bf27a634d5cd11e63f22bd9d558/lib/ws.c#L1243-L1250

pull request: https://github.com/curl/curl/pull/14458

I think we can introduce a function called curl_ws_try_flush to flush sendbuf. 
User call curl_ws_try_flush when socket is writeable. This avoid blocking sending.
If you think this suggestion is reasonable, I can help submit the corresponding code.

By the way: I have never quite understood why partial write of the data in a curl callback could mess up ws framing. Can someone provide an example？

### I expected the following

curl_ws_send not block

### curl/libcurl version

newest

### operating system

none

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
