### ISSUE TITLE
libcurl crashes on Windows with VisualStudio libcurl build

### ISSUE THREAD

**Issue by joa-quim** [curl/curl#1537]
### curl/libcurl version

7.54.0

### operating system

Windows10

This code crashes at the  curl_easy_perform() call. It crashes because the ``curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, my_fwrite);`` is not being used and, according to the docs, the default one is expected. That is what actually happens on linux where the code works.

I have build a debug libcurl.dll and catch the crashing point to be at ... 

![capture](https://cloud.githubusercontent.com/assets/537321/26755288/4579c888-4882-11e7-863a-772a6802e755.JPG)

so the ``writebody`` function doesn't seam appropriate.

````
#include <stdio.h>
#include <stdlib.h>
#include "curl/curl.h"

int main(int argc, char **argv) {
	int curl_err = 0;
	CURL *Curl = NULL;
	FILE *fp = NULL;
	char local_path[] = "lix.dat";
	char url[] = "ftp://ftp.soest.hawaii.edu/gmt/data/cache/some_data.txt";


  	if ((Curl = curl_easy_init ()) == NULL) {
		fprintf(stderr, "Screw1 merda0\n");
		return 0;
	}
	curl_easy_setopt (Curl, CURLOPT_SSL_VERIFYPEER, 0L);	/* Tell libcurl to not verify the peer */
	if ((fp = fopen (local_path, "wt")) == NULL) {
		fprintf(stderr, "Screw2\n");
		return 0;
	}

 	if (curl_easy_setopt (Curl, CURLOPT_URL, url)) {	/* Set the URL to copy */
		fprintf(stderr, "Screw3\n");
		return 0;
	}
	if (curl_easy_setopt (Curl, CURLOPT_WRITEFUNCTION, NULL)) {	/* Make sure it uses the internall callback function */
		fprintf(stderr, "Screw40\n");
		return 0;
	}
	if (curl_easy_setopt (Curl, CURLOPT_WRITEDATA, fp)) {	/* Set output file */
		fprintf(stderr, "Screw41\n");
		return 0;
	}
	fprintf(stderr, "Dowloading %s\n", url);
	if ((curl_err = curl_easy_perform (Curl))) {	/* Failed, give error message */
		fprintf(stderr, "Screw5\n");
	}
	curl_easy_cleanup (Curl);

	fclose (fp);
}
````

**Comment by bagder** [comment]
A suitable quote from the [CURLOPT_WRITEDATA](https://curl.haxx.se/libcurl/c/CURLOPT_WRITEDATA.html) man page:

> If you're using libcurl as a win32 DLL, you MUST use the CURLOPT_WRITEFUNCTION if you set this option or you will experience crashes.

**Comment by joa-quim** [comment]
Sorry, didn't see it but I consider that I program's crash is never a user's fault. 
I do some programming myself too.

**Comment by bagder** [comment]
Unfortunately there are numerous ways for a library to crash if you pass in the wrong data where the library can't tell if the data is right or wrong. We make sure to document what the right input is to avoid that from happenings.
