### ISSUE TITLE
Email Subject and Content is empty from Curl Version 8.7.0

### ISSUE THREAD

**Issue by Ponselvarani** [curl/curl#15389]
### I did this

Our application Uses Curl to send Email notification whenever there is any Application event occurs in the server
This was working fine till Curl V8.6.0 
From Curl V8.7.0 We observed email subject/Body is empty, but it sends notification with empty email
No code changes made in our application source code. we have upgraded only Curl Version to 8.7.0. Same behavior with latest Curl as well(8.10.0)

Below the code snippet used in application
===============
			std::string creds = cfgSenderAddrs + ":" + password;
			std::string strPort = utils::Conversion::to_string(port);
			std::string url = strProtocol + "://" + serverName + ":" + strPort;
			hnd = curl_easy_init();
			curl_easy_setopt(hnd, CURLOPT_INFILESIZE_LARGE, (curl_off_t)37);
			curl_easy_setopt(hnd, CURLOPT_URL, url.c_str());
			curl_easy_setopt(hnd, CURLOPT_UPLOAD, 1L);
			curl_easy_setopt(hnd, CURLOPT_USERPWD, creds.c_str());
			curl_easy_setopt(hnd, CURLOPT_MAIL_AUTH, creds.c_str()),
				curl_easy_setopt(hnd, CURLOPT_USERAGENT, " ");
			curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
			curl_easy_setopt(hnd, CURLOPT_HTTPAUTH, (long)CURLAUTH_ANY);
			curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYPEER, 0L);
			curl_easy_setopt(hnd, CURLOPT_SSL_VERIFYHOST, 0L);
			curl_easy_setopt(hnd, CURLOPT_VERBOSE, 1L);
			if (isAuthLogin) {
				/* Set the username and password */
				curl_easy_setopt(hnd, CURLOPT_USERNAME, userName.c_str());
				curl_easy_setopt(hnd, CURLOPT_PASSWORD, password.c_str());
				/* Force AUTH LOGIN authentication */
				curl_easy_setopt(hnd, CURLOPT_LOGIN_OPTIONS, "AUTH=LOGIN");
			}
			if (m_use_ssl) {
				curl_easy_setopt(hnd, CURLOPT_USE_SSL, 3L);
			}
			else {
				curl_easy_setopt(hnd, CURLOPT_USE_SSL, 0L);
			}
			curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);
			curl_easy_setopt(hnd, CURLOPT_MAIL_FROM, cfgSenderAddrs.c_str());
			curl_easy_setopt(hnd, CURLOPT_MAIL_RCPT, slist1);

			curl_easy_setopt(hnd, CURLOPT_READFUNCTION, payload_source);
			curl_easy_setopt(hnd, CURLOPT_READDATA, &upload_ctx);
			curl_easy_setopt(hnd, CURLOPT_UPLOAD, 1L);
			curl_easy_setopt(hnd, CURLOPT_WRITEDATA, &response_write_cxt);
			
			curl_easy_setopt(hnd, CURLOPT_WRITEFUNCTION, read_response_payload);
			
			
			ret = curl_easy_perform(hnd);

### I expected the following

Expectation is to receive email same as v8.6 with subject and content , as there were no code changes from application side

### curl/libcurl version

curl 8.7.0

### operating system

Windows

**Comment by bagder** [comment]
Can you perhaps provide a complete stand-alone example that works with the previous version and reproduces the problem with the latest libcurl?

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bagder** [comment]
No response
