### ISSUE TITLE
Crashes with FILE protocol on original MinGW

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#1540]
### I did this
```
./configure --enable-sspi --enable-debug --enable-curldebug --enable-warnings --enable-werror --enable-optimize CFLAGS="-Wno-error=deprecated-declarations"
make
```

Tests 203 and 1146 are crashing because of access violations in curl.exe, what they do is:
```
../src/curl.exe file:C:/MinGW/msys/1.0/home/[...]/tests//log/test203.txt
```
```
../src/curl.exe --proto-default file C:/MinGW/msys/1.0/home/[...]/tests//log/test1146.txt
```

The output before the crash is sometimes (curl occupies just a few KB of RAM):
```
curl: (27) Out of memory
```

### curl/libcurl version

git master a1b275a41ec5d479b3701ac618d2c9c11d5cedc3
```
curl 7.54.1-DEV (i686-pc-mingw32) libcurl/7.54.1-DEV zlib/1.2.8
Release-Date: [unreleased]
Protocols: dict file ftp gopher http imap ldap ldaps pop3 rtsp smtp telnet tftp
Features: Debug Largefile SSPI Kerberos SPNEGO NTLM libz
```
```
********* System characteristics ********
* curl 7.54.1-DEV (i686-pc-mingw32)
* libcurl/7.54.1-DEV zlib/1.2.8
* Features: Debug Largefile SSPI Kerberos SPNEGO NTLM libz
* Host: [...]
* System: MINGW32_NT-6.2 [...] 1.0.19(0.48/3/2) 2016-07-13 17:45 i686 Msys
* Servers:
* Env:
*****************************************
```

### operating system
Windows 10.0.15063.332 Home x64

It might take some time until I get to this as I have no experience with GDB.

**Comment by bagder** [comment]
First step though:

```
$ cd tests
$ ./runtests -g 203
(gdb) run
[runs until crash]
(gdb) bt
```
`bt` is the command for "back trace", which shows the stack frames and thus where it is and how it ended up there, which is a good start. As a next step, you can explore the local variables at the different stack frames to figure out why it ended up there like this....

**Comment by MarcelRaad** [comment]
@bagder Thanks a lot! After being confused by the two curl executables in src and src/.libs, I'm able to debug now.

**Comment by MarcelRaad** [comment]
This is a bit more painful than expected because Windows' Fault Tolerant Heap just won't let curl crash unless I reset it all the time even though I've disabled it in the registry :-(

Interim findings:
in url.c:parseurlandfillconn, the `if(rebuild_url)` block:
`path` = "/C:/MinGW/msys/1.0/home/marci/curl/tests//log/test1146.txt" (`plen` = 58)
`data->change.url` = "C:/MinGW/msys/1.0/home/marci/curl/tests//log/test1146.txt" (`urllen = 57`)
`protop` = "file" (`prefixlen` = 7)
`reurl` = "C:/MinG/C:/MinGW/msys/1.0/home/marci/curl/tests//log/test1146.txt"
Which is 66 bytes, but only 59 bytes were allocated.
So `path` is prepended with "C:/MinG" instead of "file://" or nothing.

**Comment by MarcelRaad** [comment]
Fixed in https://github.com/curl/curl/commit/5d7952f52e410e1d4a8ff1965e5cc6fc1bde86aa. Thanks!
