### ISSUE TITLE
mbedtls not skip cert verification

### ISSUE THREAD

**Issue by fork1488** [curl/curl#15428]
### I did this

 curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L); // Skip SSL peer verification
 curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L); // Skip SSL host verification

### I expected the following

not CURLE_PEER_FAILED_VERIFICATION

### curl/libcurl version

[last](mbedtls:x64-windows-static                        2.28.1)
curl:x64-windows-static                           8.9.1#1  

### operating system

Windows 11 22h3

**Comment by icing** [comment]
Not sure I understand the report. If you set `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L)` you tell libcurl to skip the peer verification. Why do you expect `CURLE_PEER_FAILED_VERIFICATION` as a result?

I adde two test cases to check this in our CI in #15429.

**Comment by fork1488** [comment]
> Not sure I understand the report. If you set `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L)` you tell libcurl to skip the peer verification. Why do you expect `CURLE_PEER_FAILED_VERIFICATION` as a result?
> 
> I added two test cases to check this in our CI in #15429 to verify the behaviour.

I get CURLE_PEER_FAILED_VERIFICATION.
 skip verification doesn't work

**Comment by icing** [comment]
Got it, you expected to **not** get CURLE_PEER_FAILED_VERIFICATION. Looking at your comment at the PR: 

```
mbedtls:x64-windows-static                        2.28.1
```

that is a rather old version. I tested in the PR with mbedtls 3.6.x and there it works. Maybe it is a behaviour they fixed?

**Comment by bagder** [comment]
Using mbedTLS/3.6.0 on my Linux, it seems to work for me.

~~~
$ ./src/curl https://moo.haxx.se --resolve moo.haxx.se:443:159.253.31.95 
curl: (60) mbedTLS: The certificate Common Name (CN) does not match with the expected CN
The certificate is not correctly signed by the trusted CA
...

$ ./src/curl https://moo.haxx.se --resolve moo.haxx.se:443:159.253.31.95 --insecure
[html output showing that skipping the verification works]

**Comment by fork1488** [comment]
solved, get last version
