### ISSUE TITLE
Curl progress bar (`-#`) does not really work with verbose flag

### ISSUE THREAD

**Issue by Euphrasiologist** [curl/curl#15432]
### I did this

curl -v -# <URL>

### I expected the following

I expect the progress bar to remain consistent along the bottom.

### curl/libcurl version

curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Ubuntu GNU Linux

**Comment by bagder** [comment]
If you don't want the verbose messaging, why do you ask for it? How do you propose curl satisfy both these options to your liking?

**Comment by Euphrasiologist** [comment]
In general, I don't want verbose messaging but in this particular instance I wanted to have a dump for more information (as there were some errors before) and I wanted to know how long the command might take, hence the progress bar. I understand this is probably a rare user case! But it would have been nice to have the progress bar formatted properly at the bottom :)

**Comment by bagder** [comment]
Here's my command line, which shows a fine progress bar:
~~~
$ curl -v http://localhost/512M -v -# -o /dev/null
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
* using HTTP/1.x
> GET /512M HTTP/1.1
> Host: localhost
> User-Agent: curl/8.10.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Mon, 28 Oct 2024 15:09:05 GMT
< Server: Apache/2.4.62 (Debian)
< Upgrade: h2,h2c
< Connection: Upgrade
< Last-Modified: Mon, 27 Mar 2023 11:05:22 GMT
< ETag: "20000000-5f7dfb819bd33"
< Accept-Ranges: bytes
< Content-Length: 536870912
< 
{ [65283 bytes data]
################################################################################## 100.0%* Connection #0 to host localhost left intact

**Comment by Euphrasiologist** [comment]
I'm getting something like this:

```
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23): #         #
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):     #        #
{ [5 bytes data]
```

**Comment by Euphrasiologist** [comment]
Okay, looks like I need to upgrade... thank you for the info on this!
