### ISSUE TITLE
Display name of error code instead of number

### ISSUE THREAD

**Issue by jeroen** [curl/curl#15473]
When the `curl` command line has an error, the numeric value of the error enum is printed, for example below `(35)`:

```sh
curl "https://packages.r-universe.dev"
curl: (35) OpenSSL/3.3.2: error:0A000458:SSL routines::tlsv1 unrecognized name
```

This is too very informative. We can easily convert this into readable code using `curl_easy_option_by_id(x)->name` such that we get the string `CURLE_SSL_CONNECT_ERROR`, which is a bit more informative.

Would it be a suggestion to print the error name (minus the curle_ prefix) such that it would look like:

```
curl: (ssl_connect_error) OpenSSL/3.3.2: error:0A000458:SSL routines::tlsv1 unrecognized name
```

### curl/libcurl version

curl 8.10.1

**Comment by bagder** [comment]
I don't think we should remove the number. I think we should make sure to have the error string/explanation to be as god as possible.

**Comment by jeroen** [comment]
I think the named error code would be easier for users to google than a number. The error buffer is of course also important but sometimes that information does not explain why curl errored.

Either way, just a suggestion :)

**Comment by bagder** [comment]
I don't want to remove the number since it has been there for years and is now an established way curl shows errors. Also, the error name is not enough to fully explain most errors either - that's what we have a full error message for.
