### ISSUE TITLE
curl+Schannel fails to set TLS 1.3 cipher suite selections correctly

### ISSUE THREAD

**Issue by bagder** [curl/curl#15482]
### I did this

(this issue was originally reported by **newfunction** on hackerone)

The curl doc page [SSL Ciphers](https://curl.se/docs/ssl-ciphers.html) says: "Setting TLS 1.3 cipher suites is supported by curl with [...] Schannel (curl 7.85.0+)." But when curl uses Schannel as its TLS backend, it incorrectly enforces the TLS 1.3 cipher suites selection. For example, if I run `curl.exe --tlsv1.3 --tls13-ciphers TLS_AES_128_GCM_SHA256 -v https://example.com`, curl surprisingly still accepts cipher suite **TLS_AES_256_GCM_SHA384**.

/cc @jay @DHowett 

### I expected the following

The selected cipher to be used.

### curl/libcurl version

curl 8.9.1 (shipped in Windows 10/11) but also current git master

### operating system

Windows

**Comment by jay** [comment]
Thanks to newfunction for his report and Dustin Howett for his research. As I said in the report, which I hope will be made public soon, IMO this is really an intractable issue managing TLS 1.3 ciphers through the Windows API. The API doesn't offer a guarantee that only the ciphers we want will be used.

/cc @wyattoday

**Comment by jeroen** [comment]
I have been trying to debug intermittent Schannel connect failures to cloudflare servers that started happening somewhere around curl 8. I wonder if this is related.

**Comment by wyattoday** [comment]
> Thanks to newfunction for his report and Dustin Howett for his research. As I said in the report, which I hope will be made public soon, IMO this is really an intractable issue managing TLS 1.3 ciphers through the Windows API. The API doesn't offer a guarantee that only the ciphers we want will be used.
> 
> /cc @wyattoday

Huh, that's odd. Don't have time right now to dig into this deeply, but based on a quick eye-ball of the code, nothing obvious is jumping out to me. It looks like it should correctly limit to only the `TLS_AES_128_GCM_SHA256` cipher based on those options.

Can you reference what you means to Dustin Howett's research? He works at Microsoft. Is this a bug in SChannel affecting particular versions of Windows? I do remember testing this thoroughly when I added the TLS 1.3 to SChannel, and it correctly limited to particular ciphers we chose. But that was several years ago at this point.

**Comment by jay** [comment]
> I have been trying to debug intermittent Schannel connect failures to cloudflare servers that started happening somewhere around curl 8. I wonder if this is related.

Are you using the [--tls13-ciphers](https://curl.se/docs/manpage.html#--tls13-ciphers) option with the Schannel backend? If not then this issue doesn't affect you and I suggest open a new issue. Cloudflare does unusual things like block by TLS client hello, so if some robot somewhere makes thousands of requests using the same client hello and it's enough to throw off the ratio of good requests to bad requests (?or however they make the determination) then they can ban the client hello. Cloudflare has said the clients ask for that. Ok fine but some people understand what they're enabling, like what are they actually asking for, they may be signaling they don't want abuse and I understand that but it's a roughshod way to limit requests. But for all I know at this point maybe it's a bug in curl and you should ignore this rant..

> Can you reference what you means to Dustin Howett's research? He works at Microsoft. Is this a bug in SChannel affecting particular versions of Windows? I do remember testing this thoroughly when I added the TLS 1.3 to SChannel, and it correctly limited to particular ciphers we chose. But that was several years ago at this point.

The report is public so you can check it out now.

**Comment by wyattoday** [comment]
Can you link what you’re talking about? Sorry I’m not following the mailing lists or subscribed to the issue tracker, so I can’t easily find what you’re referring to.

**Comment by jay** [comment]
Oops. Sure: 

[curl | Report #2792484 - When curl uses Schannel as TLS backend, it fails to enforce TLS 1.3 cipher suite selections correctly | HackerOne](https://hackerone.com/reports/2792484)

**Comment by wyattoday** [comment]
Oh, that’s interesting. Looks like it’s just a bug in SChannel. Maybe the best thing to do is to add warnings or errors when people try to limit to particular AES_GCM_SHA* ciphers. Or even a hard error when that happens.

**Comment by jay** [comment]
While we could do that then it would only work for poly1305. If poly1305 is specified there's no guarantee that in the future that will be the only cipher sent in the hello. The API doesn't have that guarantee that only the specified will be used. To me, that is the bigger problem. I'm hesitant to patch in a way that allows the TLS 1.3 cipher option to continue to work for the Schannel backend.

**Comment by wyattoday** [comment]
Yeah, honestly you’re right. There are only 6 ciphersuites for TLS 1.3 anyway, and SChannel only supports 3 of them has broken selection for the 2 most secure ones, so I’m on board with just removing the TLS cipher selection for SChannel until/unless Microsoft spends a little less money on AI-slop and a little more on their bugs.

TLS cipher selection is a bit of a foot-gun anyway (which is why TLS 1.3 limits the choices in the first place).

I can do a PR tomorrow afternoon. I’ll just remove the TLS 1.3 cipher selection (and make a note of the change in the docs).

**Comment by jay** [comment]
Ok
