### ISSUE TITLE
Incompability with libssh 0.10.6

### ISSUE THREAD

**Issue by henrikjehgmti** [curl/curl#15522]
### I did this

I have:
# curl --version
curl 8.10.1 (arm-unknown-none) libcurl/8.10.1 OpenSSL/3.0.15 zlib/1.2.11 libssh/0.10.6/openssl/zlib
Release-Date: 2024-09-18

I want to do a sftp download from an IPv6 server, but get the following output:
curl -u test:password -k sftp://[fd4d:5449:7400:111:626d:3cff:fedf:4d39]/file -o file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (2) Could not set remote host

I analyzed the LibSsh code, and found that LibSsh was not happy about the host name due to missing brackets around the IPv6 address.

I did a workaround in curl/src/lib/vssh/libssh.c to reinsert the brackets. 
[curl_ip6_libssh0_10_6.patch](https://github.com/user-attachments/files/17679182/curl_ip6_libssh0_10_6.patch)

~~~diff
Index: ../sw_apps_linux/curl/src/lib/vssh/libssh.c
===================================================================
--- ../sw_apps_linux/curl/src/lib/vssh/libssh.c (revision 5373)
+++ ../sw_apps_linux/curl/src/lib/vssh/libssh.c (working copy)
@@ -2186,7 +2186,22 @@
     return CURLE_FAILED_INIT;
   }

+  struct in6_addr ip6result;
+
+  if (inet_pton(AF_INET6, conn->host.name, &ip6result) == 1) // success!
+  {
+      char newIp6[64];
+      sprintf(newIp6, "[%s]", conn->host.name);
+      rc = ssh_options_set(ssh->ssh_session, SSH_OPTIONS_HOST, newIp6);
+  }
+  else
+  {
+      rc = ssh_options_set(ssh->ssh_session, SSH_OPTIONS_HOST, conn->host.name);
+  }
~~~

I ended up doing it here as I fear that host.name is used for e.g. TLS name verification, but I could not see if that was the case. 

Do you already have a better solution for this, or can you use it (it should be under LIBSSH version flags perhaps)? I was not able to find any existing bugs that mentions this configuration, so I hope that this is not a duplicate.

### curl/libcurl version

curl 8.10.1 (arm-unknown-none) libcurl/8.10.1 OpenSSL/3.0.15 zlib/1.2.11 libssh/0.10.6/openssl/zlib

### operating system

Linux mti-ru 5.15.0 #79 SMP PREEMPT Fri Jul 5 14:00:08 CEST 2024 aarch64 GNU/Linux

**Comment by bagder** [comment]
@henrikjehgmti I made #15524 based on your patch but just a tad bit different.

**Comment by henrikjehgmti** [comment]
Thank you very much, and thanks a lot for the quick turnaround time.
