### ISSUE TITLE
more than 100 errors in all files of include folder together

### ISSUE THREAD

**Issue by HarnitskyMaksym** [curl/curl#15532]
### I did this

![image](https://github.com/user-attachments/assets/1fc913d5-494e-46e4-a760-703ec66bebcb)

the almost every error is in this form:
curl/easy.h:41:1: error: 'CURL_EXTERN' does not name a type (x10)

### I expected the following

Excepted, that will compile successfully

### curl/libcurl version

curl 8.11.0

### operating system

Windows 10

**Comment by bagder** [comment]
Please tell us (exactly) what you did otherwise we can't help.

**Comment by vszakats** [comment]
Passing all libcurl sources (or curl headers?) to the compiler (as the screenshot suggests)
is unlikely work. Curl also needs a C compiler instead of a C++ one.

The supported build methods are CMake or `./configure`. Have you tried those?

**Comment by bagder** [comment]
We recommend building curl as documented and supported. If that causes problems we will be happy to help you sort them out.
