### ISSUE TITLE
Cross Compiling for Amiga OS - Error implicit declaration of function 'ioctl'

### ISSUE THREAD

**Issue by boingball** [curl/curl#15537]
### I did this

using GCC = m68k-amigaos-gcc version 13.2.0
AmigaSSL v5 (Latest Oct 24)
Zlib 1.3.1 (Cross Compiled with soft-float by me)
In hopes of - Building curl 8.11.1-DEV (m68k-unknown-amigaos) OpenSSL/3.4.0 zlib/1.3.1

The configure command was as follows (this was based on a older forum post and added to make it compile)
`./buildconf && PKG_CONFIG=true ./configure --host=m68k-amigaos --build=$(uname -m)-pc-linux-gnu CC=m68k-amigaos-gcc AR=m68k-amigaos-ar --disable-shared --disable-ipv6 --prefix=/opt/amiga13 --disable-netrc --without-libpsl --with-amissl --disable-threaded-resolver CFLAGS="-fomit-frame-pointer -msoft-float -Wno-system-headers -mcrt=clib2" CPPFLAGS="-D__AMIGA__ -DHAVE_IOCTLSOCKET_CAMEL_FIONBIO=1" LIBS="-lnet -lm -lc -lz -lunix -latomic" `

When trying to cross compile anything above 8.4.0 the cross compile fails with

` CC       libcurl_la-nonblock.lo
nonblock.c: In function 'curlx_nonblock':
nonblock.c:70:10: error: implicit declaration of function 'ioctl' [-Werror=implicit-function-declaration]
   70 |   return ioctl(sockfd, FIONBIO, &flags);
      |          ^~~~~`

this seems to coming from #elif defined(HAVE_IOCTL_FIONBIO) which has comments older unix - there is an Amiga elif further down - If I swap the order in nonblock.c as below - the compile completes (it doesn't work on the amiga correctly however)

```
#elif defined(HAVE_IOCTLSOCKET_CAMEL_FIONBIO) 
    /* Amiga */
    long flags = nonblock ? 1L : 0L;
    return IoctlSocket(sockfd, FIONBIO, (char*)&flags); 

#elif defined(HAVE_IOCTL_FIONBIO)

  /* older Unix versions */
  int flags = nonblock ? 1 : 0;
  return ioctl(sockfd, FIONBIO, &flags);
```

On the Amiga - typing any CURL URL gives the error message

> curl: (3) URL using bad/illegal format or missing URL

I'm not a C programmer or an expert at compiling with GCC  - just thought I'll give this all a try to see if I could make the latest CURL work on the AmigaOS (test system is latest classic AmigaOS 3.2.2.1)

so not sure if there are two bugs here - or my configuration statement is causing this issue.

### I expected the following

Compilation works first try and the Amiga program runs and works as intended.

### curl/libcurl version

curl 8.11.1-DEV (m68k-unknown-amigaos) libcurl/8.11.1-DEV OpenSSL/3.4.0 zlib/1.3.1

### operating system

Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Amiga OS 3.2.2.1

**Comment by bagder** [comment]
There won't be many people around here to help get this to build on Amiga.

**Comment by boingball** [comment]
> There won't be many people around here to help get this to build on Amiga.

Yeah I thought it might be a little light on Amiga users in here - 

The thing compiles - just doesn't work as intended - every URL you give it, brings back this error when running on the Amiga

![amicurl](https://github.com/user-attachments/assets/dc0bf58e-d92c-4f06-9723-c4ae66f35b74)

I've had a look through the code, and don't know where to start - I assume the URL string is not being picked up correctly - all the -(options) work correctly when used.

**Comment by bagder** [comment]
You should probably set a break-point in `lib/urlapi.c:parseurl()` and single-step forward to see at what point it bails out.

**Comment by boingball** [comment]
> You should probably set a break-point in `lib/urlapi.c:parseurl()` and single-step forward to see at what point it bails out.

Thanks for the tip on that, I don't have an IDE on the amiga - as it's a cross compile I can't step in to the built exe on that platform.

I did however put some printf's in to see if I could work our where it bombs out, but I think it's outside of this function as coving all breaks on URL_MALFORMed it still pops up as the error  - the URL is parsed fine and it detects the protocol correctly. -then gives that error of bad/illegal url

I'm wondering if it could be a missing define at compile time causing this issue: 
as I'm using configure to make this (the old way was the makefile route which doesn't work) I wonder if the defines that are in /libs/config-amigaos.h are not being picked up by Configure - I know this as the HAVE_IOCTLSOCKET_CAMEL_FIONBIO defined in that file doesn't get picked up at compile time even through it's set in config-amigaos.h.

There is a lot of defines in that file which I'll have to translate to the configure.ac file as AC_DEFINE, AC_SUBST to test.

Hopefully I can make something work.

**Comment by boingball** [comment]
So i've tested with all the defines in config-amigaos.h by putting them in the configure statement manually

`./buildconf && PKG_CONFIG=true ./configure --host=m68k-amigaos --build=$(uname -m)-pc-linux-gnu CC=m68k-amigaos-gcc AR=m68k-amigaos-ar --disable-shared --disable-ipv6 --prefix=/opt/amiga13 --disable-netrc --without-libpsl --with-amissl --disable-threaded-resolver CFLAGS="-fomit-frame-pointer -m68040 -O2 -msoft-float -Wno-system-headers -mcrt=clib2" CPPFLAGS="-D__AMIGA__ -DHAVE_ARPA_INET_H=1 -DHAVE_CLOSESOCKET_CAMEL=1 -DHAVE_IOCTLSOCKET_CAMEL=1 -DHAVE_IOCTLSOCKET_CAMEL_FIONBIO=1 -DHAVE_LONGLONG=1 -DHAVE_NETDB_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_NET_IF_H=1 -DHAVE_PWD_H=1 -DHAVE_SELECT=1 -DHAVE_SIGNAL=1 -DHAVE_SOCKET=1 -DHAVE_STRCASECMP=1 -DHAVE_STRDUP=1 -DHAVE_STRICMP=1 -DHAVE_STRINGS_H=1 -DHAVE_STRUCT_TIMEVAL=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_SOCKIO_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UTIME=1 -DHAVE_UTIME_H=1 -DHAVE_WRITABLE_ARGV=1 -DHAVE_SYS_IOCTL_H=1 -DNEED_MALLOC_H=1 -DSIZEOF_INT=1 -DSIZEOF_SIZE_T=1 -DSIZEOF_CURL_OFF_T=8 -DUSE_MANUAL=1 -DCURL_DISABLE_LDAP=1 -DCURL_OS=AmigaOS -DSTDC_HEADERS=1 -DF_OK=0 -DHAVE_RECV=1 -DHAVE_SEND=1" LIBS="-lnet -lm -lc -lz -lunix -latomic"`

but that doesn't fix the bug - every url passed to curl gives the error curl: (3) URL using bad/illegal format or missing URL

This error is triggered on CURLUE_MALFORMED_INPUT

Putting a  fprintf(stderr, "Location\n"); in before each break statement I can see it's failing at the code

`if (!nalloc)
 /* a blank URL is not a valid URL */
 return CURLUE_MALFORMED_INPUT;`

Trying to debug backwards now to work out how it got to !nalloc

**Comment by boingball** [comment]
Hard to debug with fprintf statements, but some little progress :

if I run curl google.com
curl_url_set receives the url as google.com
it passes this to parse and replace function correctly.
This in turn passes it over to  parseurl
This guesses the scheme correctly and then I get to the end with a 0 result - the url seems to vanish here somewhere.
curl_url_set runs again but this time the url is blank
and then we get the error curl: (3) URL using bad/illegal format or missing URL)

**Comment by boingball** [comment]
Thanks for the guidance on this Jay

so after many more fprintfs I can confirm it seems to run in this order

curl google.com

curl_url_set first run

CURLcode create_conn runs 
!use_set_uh runs
I can only fprintf the state.url in decimal so it does contain something (In decimal 142924196)~
and it leaves via
 result = parseurlandfillconn(data, conn);
  if(result){
    goto out;
  }

curl_url set 2nd run

Error URL Using bad/illagal fomat of missing URL

the fprintf don't seem to go in that order - not sure if one part calls before the other and fprintf is just catching up

I don't know if this helps in anyway - defiantly something doesn't go through 

screenshot of the various fprintf parts below 

![IMG_2806](https://github.com/user-attachments/assets/6ee2334a-b011-44dd-9585-c5f40ee61fc4)

**Comment by jay** [comment]
> I can only fprintf the state.url in decimal so it does contain something (In decimal 142924196)~

That doesn't make any sense to me. Are you using the %s format? `fprintf(stderr, "data->state.url: %s\n", data->state.url);`

> and it leaves via
> result = parseurlandfillconn(data, conn);
> if(result){
> goto out;
> }

`if(result)` is shorthand for `result != CURLE_OK` which means that the function failed. I don't know in what case that curl_url_set would be called again. Turn on verbose mode `-v`.

On my Windows machine I see 3 calls to curl_url_set for `curl google.com`. The first call is to check if the URL is for IPFS. The second call is the parseurlandfill call. The third call is after the transfer to parse the Location URL, as I suspected.

**Comment by boingball** [comment]
Hi Jay
The more fprintf I put in the more it crashes,
if i try and use %s on the data->state.url it crashes the amiga to a software failure - no idea why.

now doing curl -v google.com - doesn't print any verbose out to the console? just my fprintfs come out.

I've recompiled 8.11.0 to a new folder - and curl -v google.com does the same, no verbose.
Just straight to the curl: (3) URL using bad/illegal format of missing URL

Could it be curl is not making a connection and not reporting it somehow?

This bug started off with the nonblock.c code not compiling as it picked up the unix method until I moved the part of the code ahead

```
#elif defined(HAVE_IOCTLSOCKET_CAMEL_FIONBIO)

  /* Amiga */
  long flags = nonblock ? 1L : 0L;
  return IoctlSocket(sockfd, FIONBIO, (char *)&flags);
```

Could that have something to do with it?

or do I need to check the code for the bsdsocket.library - has it somehow failed to do anything with this.

Apologies if I get some of this wrong, I'm not a C Programmer - so reading C is me looking in the C Manual and then doing

**Comment by jay** [comment]
I think it is unlikely that changing to IoCtlSocket would cause crashes in this area and that there is memory corruption occurring somewhere else. I don't know how to better debug this in Amiga except with printfs to find a good point before the corruption occurs. Apparently stack traces are possible, see https://wiki.amigaos.net/wiki/Using_Crash-Logs_for_Debugging

**Comment by boingball** [comment]
> I think it is unlikely that changing to IoCtlSocket would cause crashes in this area and that there is memory corruption occurring somewhere else. I don't know how to better debug this in Amiga except with printfs to find a good point before the corruption occurs. Apparently stack traces are possible, see https://wiki.amigaos.net/wiki/Using_Crash-Logs_for_Debugging

Thanks for the assistance Jay this is much appreciated!

So tonight's testing, I can confirm there is no network tcp stack working in the curl compiled exe.
If I turn off the amiga TCP stack (Roadshow) the same error occurs. curl (3): URL using bad/illegal format or missing URL

I've been trying to work our how the curl code works with Amiga TCP stacks
Looking at libs/amigaos.c this has code to open the bsdsocket.library for AmigaOS3 and fail if it doesn't work.
it also is referencing amitcp/socketbasetags.h if we are using AmiSSL
The Amiga GCC has this included in the amitcp folder so should be OK

My Amiga uses Roadshow as it's TCP stack (it's newer - and my other Amiga use this) I assume it shouldn't matter on the Amiga side, as bsdsocket.library is included with Roadshow as well.

I've tried changing this to roadshows newer TCP SDK by changing the include to <bsdsocket/socketbasetags.h> as well but so far all builds have no TCP stack support.

More testing this weekend

**Comment by boingball** [comment]
So tonight I'm concentrating on the Amigaos.c and Amigaos.H

Amigaos.h seems to have a couple of functions in it that setup curl for Amiga and how to attach the socket library

Getting them to add there functions in at build time gives an error - 

  CCLD     curl
/opt/amiga13/lib/gcc/m68k-amigaos/13.2.0/../../../../m68k-amigaos/bin/ld: /opt/amiga13/lib/libamisslauto.a(autoinit_assl.o):autoinit_assl.o:(.data+0x4): multiple definition of `SocketBase'; ../lib/.libs/libcurl.a(libcurl_la-amigaos.o):libcurl_la-amigaos.o:(.bss+0x0): first defined here

it seems that the socketbase in amigaos.c is also conflicting with amissl's socketbase

Will look at this more tomorrow - I can't work out what options we should be running to make sure we use the correct method for socket in AmigaOS3

**Comment by boingball** [comment]
We have life in Curl on AmigaOS3! 

I had to add to the configure.ac to set the Amiga nonblocking method and change nonblock.c to make sure the Amiga nonblocking method works. 

![image](https://github.com/user-attachments/assets/2f98d4d7-2abe-4d91-9f85-15031295c223)

Downside it's not stable, this maybe a compiler option problem so working on that next. It curls or crashes 

I'll put the changes up on my folk this weekend once I'm happy with it.

**Comment by boingball** [comment]
It's very compiler sensitive. Setting it down to m68000 with no optimisations makes it run correctly. 

So i have a build that's stable

Pushing my changes over now since it's confirmed working. 

![image](https://github.com/user-attachments/assets/316c4181-775b-43de-bb43-e07975ceb993)
