### ISSUE TITLE
Openssl 3.0.15 build issue

### ISSUE THREAD

**Issue by barbacar** [curl/curl#15548]
### I did this

While trying to build libcurl with openssl 3.0.15(3.0.x is the version that will be maintained for the longest time) i m getting following error.

[100%] Linking CXX executable ../../bin/app
/usr/bin/ld: missing --end-group; added as last command line option
/usr/bin/ld: /tmp/.conan/data/libcurl/8.10.1/_/_/package/eb62b0453b264b36d119eaa1d1d001a2531663d5/lib/libcurl.a(libcurl_la-openssl.o): in function `ossl_connect_step2':
/home/conan/workspace/prod-v1/bsr/97928/dcddb/.conan/data/libcurl/8.10.1/_/_/build/eb62b0453b264b36d119eaa1d1d001a2531663d5/src/lib/vtls/openssl.c:4304: undefined reference to `SSL_get0_group_name'
collect2: error: ld returned 1 exit status

https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L4294-L4301

can you please help me about this?
thank you

### curl/libcurl version

8.10.1

### operating system

Ubuntu 22

**Comment by bagder** [comment]
Please tell us what steps you perform when you build it. It looks like you maybe aren't using a curl provided build system?

**Comment by barbacar** [comment]
No, i m trying to build libcurl 8.10.1 library via conan to use it in my applicaton 
and it is breaking in linking stage  undefined reference to SSL_get0_group_name'  , 
maybe this problem is related with conan package, what i see is 
 that OPENSSL_VERSION_NUMBER is not properly set.
