### ISSUE TITLE
 Document --cert escape handling #9349 --This makes no sense

### ISSUE THREAD

**Issue by jarcogna** [curl/curl#15541]
### I did this

$ curl --cert \:Common\:default.crt --key \:Common\:default.key https://google.com
curl: (58) could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?)

### I expected the following

If I use the Tab key to create the filenames, we end up with:

`curl --cert \:Common\:default.crt --key \:Common\:default.key https://google.com
`

as the filenames are :Common:default.crt and :Common:default.key

But if we look at Bug #9349 we see we actually need to set the filenames as:

`curl --cert \\:Common\\:default.crt --key \:Common\:default.key https://google.com
`

and then the command works as expected.

So we see that for the --cert option we need to "double" escape the : but for the --key, only a single escape. This makes no sense. I would expect that if I use the Tab completion to create the filenames, they should work

### curl/libcurl version

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Linux quantum 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is because your shell removes one layer of quoting when you provide the string like this, so unless you double-quote it does not get passed to curl itself. You probably want to use single-quotes around the argument to prevent your shell from doing this. curl can't help that your shell does this.
