### ISSUE TITLE
can't build curl from repo in ubuntu 14 due to libtool version mismatch

### ISSUE THREAD

**Issue by jay** [curl/curl#1554]
### I did this

In Ubuntu 14 LTS:
~~~
git clone https://github.com/curl/curl.git
cd curl
./buildconf
./configure
make
~~~

### Output

make fails due to libtool version mismatch error:
~~~
make[1]: Entering directory `/home/owner/cross-compile/curl-7.54.0/curl/lib'
make  all-am
make[2]: Entering directory `/home/owner/cross-compile/curl-7.54.0/curl/lib'
  CC       libcurl_la-file.lo
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-2
libtool: and run autoconf again.
make[2]: *** [libcurl_la-file.lo] Error 63
make[2]: Leaving directory `/home/owner/cross-compile/curl-7.54.0/curl/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/owner/cross-compile/curl-7.54.0/curl/lib'
make: *** [all-recursive] Error 1
~~~

### Bisect

bisected to 4271695. I automated it though to save myself some time, so as long as nobody sees an error in the script below then that commit should be accurate.

~~~sh
#!/bin/bash

# Sample script to run an automated bisect.
# git bisect start master curl-7_39_0
# git bisect run ./a.sh

# if git clean fails then bisect skip
git clean -fdx -e a.sh || exit 125

# if buildconf fails then bisect skip
./buildconf || exit 125

# if configure fails then bisect skip
./configure --without-nghttp2 || exit 125

# if make succeeds then bisect good
echo "Running make and redirecting output to a file."
make &>out && exit 0 

# if libtool error message found then bisect bad
grep "Version mismatch error" out && exit 1

# make/grep failed for unknown reason, bisect skip
exit 125
~~~

### Other

Since switching to Ubuntu 16 LTS VMs about a year ago I have not used 14 LTS very much.

/cc @michael-o

**Comment by MarcelRaad** [comment]
Strange, I used the Ubuntu 14.04 LTS that came with Windows 10 1607 on one of my computers until some weeks ago and never encountered that problem.

**Comment by jay** [comment]
I don't recall having this problem either. It might be the snapshot. I'll try rebooting and some other snapshots that have the curl repo already set up.

**Comment by michael-o** [comment]
@jay That's weird. I usually test on RHEL 6, FreeBSD and HP-UX. I'll try my Ubuntu VM later this week. This could also be an issue with the Debian-distributed version of libtool.

**Comment by michael-o** [comment]
Just tried on:

    Linux ubuntu1404.local 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 15:58:13 UTC 2016 i686 i686 i686 GNU/Linux
    ~# cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

    configure: Configured to build curl/libcurl:
    
      curl version:     7.54.1-DEV
      Host setup:       i686-pc-linux-gnu
      Install prefix:   /usr/local

      CC       ../lib/curl-nonblock.o
      CC       ../lib/curl-warnless.o
      CCLD     curl
    make[2]: Verzeichnis »/home/mosipov/Projekte/curl/src« wird verlassen
    make[1]: Verzeichnis »/home/mosipov/Projekte/curl/src« wird verlassen
    Making all in include
    make[1]: Verzeichnis »/home/mosipov/Projekte/curl/include« wird betreten
    Making all in curl
    make[2]: Verzeichnis »/home/mosipov/Projekte/curl/include/curl« wird betreten
    make  all-am
    make[3]: Verzeichnis »/home/mosipov/Projekte/curl/include/curl« wird betreten
    make[3]: Verzeichnis »/home/mosipov/Projekte/curl/include/curl« wird verlassen
    make[2]: Verzeichnis »/home/mosipov/Projekte/curl/include/curl« wird verlassen
    make[2]: Verzeichnis »/home/mosipov/Projekte/curl/include« wird betreten
    make[2]: Für das Ziel »all-am« ist nichts zu tun.
    make[2]: Verzeichnis »/home/mosipov/Projekte/curl/include« wird verlassen
    make[1]: Verzeichnis »/home/mosipov/Projekte/curl/include« wird verlassen
    make[1]: Verzeichnis »/home/mosipov/Projekte/curl« wird betreten
    make[1]: Für das Ziel »all-am« ist nichts zu tun.
    make[1]: Verzeichnis »/home/mosipov/Projekte/curl« wird verlassen

Works for me...

**Comment by jay** [comment]
> Works for me...

When you run ./buildconf do you see `libtoolize: Remember to add `LT_INIT' to configure.ac.`

**Comment by michael-o** [comment]
Yes:

    $ ./buildconf
    buildconf: autoconf version 2.69 (ok)
    buildconf: autom4te version 2.69 (ok)
    buildconf: autoheader version 2.69 (ok)
    buildconf: automake version 1.14.1 (ok)
    buildconf: aclocal version 1.14.1 (ok)
    buildconf: libtoolize version 2.4.2 (ok)
    buildconf: GNU m4 version 1.4.17 (ok)
    buildconf: running libtoolize
    libtoolize: putting auxiliary files in `.'.
    libtoolize: copying file `./ltmain.sh'
    libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
    libtoolize: copying file `m4/libtool.m4'
    libtoolize: copying file `m4/ltoptions.m4'
    libtoolize: copying file `m4/ltsugar.m4'
    libtoolize: copying file `m4/ltversion.m4'
    libtoolize: copying file `m4/lt~obsolete.m4'
    libtoolize: Remember to add `LT_INIT' to configure.ac.
    buildconf: converting all mv to mv -f in local m4/libtool.m4
    buildconf: running aclocal
    buildconf: converting all mv to mv -f in local aclocal.m4
    buildconf: running autoheader
    buildconf: running autoconf
    buildconf: running automake
    configure.ac:131: installing './compile'
    configure.ac:185: installing './config.guess'
    configure.ac:185: installing './config.sub'
    configure.ac:131: installing './install-sh'
    configure.ac:132: installing './missing'
    docs/examples/Makefile.am: installing './depcomp'
    parallel-tests: installing './test-driver'
    buildconf: OK

**Comment by jay** [comment]
hm. mine doesn't end like that
~~~
libtoolize: Remember to add `LT_INIT' to configure.ac.
buildconf: converting all mv to mv -f in local m4/libtool.m4
buildconf: running aclocal
buildconf: converting all mv to mv -f in local aclocal.m4
buildconf: running autoheader
buildconf: running autoconf
buildconf: running automake
buildconf: config.guess not found
buildconf: OK
~~~
I'll investigate

**Comment by jay** [comment]
It looks like what happened is the automake detects it isn't in the top directory even though it is. In other words put curl in another project that also uses autoconf, which is what I was trying to do:

foo/configure.ac
foo/configure
foo/install-sh
etc
foo/curl/configure.ac

In this case automake when run via buildconf in the curl directory seems to go up a level and detect the completed foo stuff when install-sh is present there. A comparison shows curl ac_aux_dir is set up a level (ie foo/curl/../) but abs_top_{builddir,srcdir} are correct.
~~~
< AMDEP_TRUE="" ac_aux_dir="."
---
> AMDEP_TRUE="" ac_aux_dir="./.."
720c720
< ac_aux_dir='.'
---
> ac_aux_dir='./..'
~~~
buildconf says config.guess not found because it's never actually generated in foo/curl/.

I have also reproduced this in Fedora 25 and Ubuntu 16. If I delete foo/install-sh then automake in the curl directory will set the proper ac_aux_dir and the missing files. Does this sound like a bug in autotools or curl bootstrapping now that it expects install-sh to be generated?

**Comment by bagder** [comment]
I don't think this is curl's fault but more an effect of how configure works. `install-sh` is created when `./buildconf` is run so I think that is correct and not strictly related to your issue.

configure has a lot of magic for when you run configure out of another directory than the current one, out-of-tree, and it seems that something in that handling triggers a problem for you. Not sure why you get this here and now though.
