### ISSUE TITLE
OpenSSF Best Practices - Outdated

### ISSUE THREAD

**Issue by wertzuz** [curl/curl#15571]
### Specify which documentation you found a problem with

https://www.bestpractices.dev/en/projects/63/

### The problem

[The project MUST have performed a security review within the last 5 years.](https://www.bestpractices.dev/en/projects/63?criteria_level=2#security)
Has outdated Information referring to 2016.

Also on several [occasions](https://www.bestpractices.dev/en/projects/63?criteria_level=2#quality) the github URL is misspelled as http://github.com/curl/curl or http://github,com/curl/curl

**Comment by bagder** [comment]
This is not a curl bug. We have had several reviews since 2016.

**Comment by wertzuz** [comment]
As far as my knowledge goes, it's the responsibility of the curl maintainers to provide the information to the site, as it is a voluntary certification based on information provided by the developers of the project.
