### ISSUE TITLE
EBCDIC conversion of argments on IBMi(OS400) is broken

### ISSUE THREAD

**Issue by andrewkirillov-ibm** [curl/curl#15570]
### I did this

I compiled 8.11.0 release on IBM i V7R4M0 system. For this I applied a fix suggested in #15566, as the released version does not build on IBMi. However CURL does not seem to be function well.

```
> ./curl --version                                                 
  curl: option : blank argument where content is expected          
  curl: try 'curl --help' or 'curl --manual' for more information  
  $                                                                
> ./curl www.google.com                                            
  curl: option : blank argument where content is expected          
  curl: try 'curl --help' or 'curl --manual' for more information  
```
  
The reason for this is the fix to #15214. As a result of it iconv_open() fails to initialize conversion. The IBMi docs say that both to/from conversion codes are 32 byte long strings. And all reserved fields MUST be set to zeros.
https://www.ibm.com/docs/en/i/7.5?topic=ssw_ibm_i_75/apis/iconvopn.html

### I expected the following

I expect CURL command to handle command line arguments correctly on IBMi/OS400 platform.

### curl/libcurl version

8.11.0

### operating system

OS400 V7R4M0

**Comment by andrewkirillov-ibm** [comment]
The fix below fixes CURL so it does work fine on IBMi.
packages/OS400/curlmain.c

```
@@ -59,12 +59,14 @@ int main(int argc, char **argv)
   char *inbuf;
   char *outbuf;
   size_t inbytesleft;
   size_t outbytesleft;
   char dummybuf[128];
-  const char *tocode = "IBMCCSID01208"; /* Use UTF-8. */
-  const char *fromcode = "IBMCCSID000000000010";
+  /* To/From codes are 32 byte long strings with
+     reserved fields initialized to ZEROs */
+  const char tocode[32]   = {"IBMCCSID01208"}; /* Use UTF-8. */
+  const char fromcode[32] = {"IBMCCSID000000000010"};
 
   ebcdic_argc = argc;
   ebcdic_argv = argv;
 
   /* Build the encoding converter. */
```

**Comment by bagder** [comment]
Any chance you can provide this patch as a full fledged PR?

**Comment by andrewkirillov-ibm** [comment]
Will work on it.
