### ISSUE TITLE
Curl and Libcurl Exit Silently

### ISSUE THREAD

**Issue by rjarratt** [curl/curl#15595]
### I did this

I am using Curl to retrieve an audio stream for something called Internet Teletype. To do this I use the following command, which anyone can try:

`curl -N -s http://internet-tty.net:8000/ITTY`

This is supposed to be a continuous audio feed but at the end of each encoded message curl just silently exits. I have looked at tcpdump traces and I can't see anything unusual, my side just sends a FIN packet. I can't tell if this is because curl died or because curl decided there was a problem and chose to end.

If you want to see how the audio stream is decoded install lame and minimodem and then use the following command:

`curl -N -s http://internet-tty.net:8000/ITTY | lame --decode --quiet --mp3input - - | minimodem rtty -i -a -q --rx-one -R 11025 -f -`

I tried writing my own code using libcurl. The call to curl_multi_perform just causes the program to exit silently at the same point. You can see my code here: `https://github.com/rjarratt/itty/blob/main/itty.c`. I tried using `atexit()` to catch the termination but it doesn't get called, the program dies very abruptly. I tried setting CURLOPT_VERBOSE but that didn't give me any clues. Incidentally, I know that my write function isn't really necessary.

I am looking for suggestions on how to diagnose this problem please.

### I expected the following

While there could be an issue with the feed itself I would expect Curl not to exit silently or at least to print an error message.

### curl/libcurl version

curl 7.88.1

### operating system

Debian Bookworm (on Raspberry Pi Model 2)

**Comment by dfandrich** [comment]
> While there could be an issue with the feed itself I would expect Curl not to
> exit silently or at least to print an error message.

If you read the man page you will see that it says:

  -s, --silent: Silent or quiet mode. Do not show progress meter or error
  messages. Makes Curl mute.

Try running without that option if you'd like error messages.

**Comment by rjarratt** [comment]
Well that is embarassing! I failed to spot that. However, I think it ought to be possible to disable the progress display while not disabling the display of errors, so that it can be used in a piped command. Having removed the -s option I get

`curl: (23) Failure writing output to destination`

I suspect the problem is with the program that I am piping the curl output to, that might be the thing that is failing. However, why would libcurl die silently as well?

**Comment by nbanb** [comment]
Dear @rjarratt 

> I think it ought to be possible to disable the progress display while not disabling the display of errors

You should try : 
```bash
curl -sS URL
```

From documentation : 

```bash
       -S, --show-error
              When used with -s, --silent, it makes curl show an error message
              if it fails.

              This option is global and does not need to be specified for each
              use of -:, --next.

              Providing -S, --show-error multiple times has no  extra  effect.
              Disable it again with --no-show-error.

              Example:
               curl --show-error --silent https://example.com

              See also --no-progress-meter.

       -s, --silent
              Silent  or  quiet mode. Do not show progress meter or error mes-
              sages. Makes Curl mute. It will still output the  data  you  ask
              for, potentially even to the terminal/stdout unless you redirect
              it.

              Use -S, --show-error in  addition  to  this  option  to  disable
              progress meter but still show error messages.

              Providing -s, --silent multiple times has no extra effect.  Dis-
              able it again with --no-silent.

              Example:
               curl -s https://example.com

              See also -v, --verbose, --stderr and --no-progress-meter.


```

Kind regards
nbanba

**Comment by dfandrich** [comment]
> However, why would libcurl die silently as well?

libcurl should never "die"—that would be a bug (either in the application or in
libcurl itself). However, it leaves the user interface completely up to the
application, which is responsible for retrieving any error codes and messages
after the transfer and notifying the user in the most appropriate way.

**Comment by rjarratt** [comment]
I have realised what my mistakes were. First not reading all the curl options in the man page, second I missed adding tracing to my write function in my own code. Sorry for the noise.

**Comment by nbanb** [comment]
Dear @rjarratt 

A dirty way to go arround the issue with curl command could be to write something which makes it persistent like:
```bash
while true
        do 
        curl -N -sS http://internet-tty.net:8000/ITTY | lame --decode --quiet --mp3input - - | minimodem rtty -i -a -q --rx-one -R 11025 -f -
        # here add a break conditions 
done  2>/path/to/error/logfile 
```
Sure better can be done but it works after the FIN and the tcp RST sent by the client when the stream fails 

Kind regards 
nbanba

**Comment by rjarratt** [comment]
I discovered that my error was in the minimodem command, change `--rx-one` to `--rx` and it works. I played with killing processes further down the pipeline and it always led to curl having the error "Failure writing output to destination", which makes sense if the rest of the pipeline has failed. Of course I am sure there could be other reasons for curl to fail, but stopping minimodem from exiting is certainly one of them and is definitely the main cause of the behaviour I was seeing.

**Comment by nbanb** [comment]
Thanks for answer.
The stream failed on the exact same bytes on 2 different machines : 
![image](https://github.com/user-attachments/assets/82d4dc5c-44c7-41ef-b36f-0f98cfb5558c)
And from minimodem documentation, minimodem --rx-one failed when there are carrier problems 

```bash  
     --rx-one
              Quit after the first carrier/no-carrier event (applies to --rx mode only).
```
(in other word, when the input stream lag or failed)

thanks for the case, interresting and I did not know it was possible to easy transcript an mp3 stream
Kind regards
nbanba
