### ISSUE TITLE
-z does absolutely nothing over SFTP on Windows

### ISSUE THREAD

**Issue by AstrOsu** [curl/curl#1560]
### I did this
`curl -k -u USER:PASS sftp://HOST/PATH/image[1-9].jpg -z "2018 Jun 08"`

I've tried dozens of dates with and without - based on [this man page](https://linux.die.net/man/3/curl_getdate), I tried -z "$FILE" that's newer than the file on the server, and every file in that directory was modified on a different date within the past.  

### I expected the following
No file on Earth was made after that date, so nothing should download.  And yet, no matter what I do, every file in my local directory is replaced by the one on in the remote directory.  

Does -z not work over SFTP, or am I just using it wrong?  It may be exclusive to Windows (I don't have access to my linux machine atm), but my curl is mostly up to date so either way it's an issue.
### curl/libcurl version

curl 7.51.0 (x86_64-w64-mingw32) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.8.0 nghttp2/1.16.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 Metalink

### operating system
Windows 10, using Mingw64 as my shell

**Comment by bagder** [comment]
The man page section describing [-z](https://curl.haxx.se/docs/manpage.html#-z) actually lists this feature to work for HTTP and FTP, **not** SFTP and this matches the code. There's no support for time conditional transfer with SFTP in curl (although it is probably possible to add this feature if someone is willing to write the code).

**Comment by AstrOsu** [comment]
Ah, my bad.  I just assumed SFTP and FTP were similar enough for it to work, shows what I know haha.
I'll see if I can implement it myself but no promises, I'll likely end up doing a quick workaround instead.

I'd appreciate if you added something saying "not SFTP" somewhere to prevent any further confusion from others like myself.  

Thanks for you time, and for maintaining this FREE library!
