### ISSUE TITLE
Error message omitted when the certificate is missing or invalid

### ISSUE THREAD

**Issue by hiimmat** [curl/curl#15612]
### I did this

I made a HTTP request with SSL verification enabled, but the certificate that I used had expired. The response included the error code `SSL_REMOTE_CERTIFICATE_ERROR` but did not provide a message.

### I expected the following

In earlier versions, the response provided an error message alongside the error code:
`SSL certificate problem: unable to get local issuer certificate.`

Tracking it down, I discovered that this message was removed in the following pull request:
https://github.com/curl/curl/pull/15474/files#diff-03eaf320162ec20f67fab4e16f494e29735dadfa12425530869d42eea86bd2ccL4282

### curl/libcurl version

curl 8.11.0

### operating system

Windows 10

**Comment by Mwileman232** [comment]
I have also run into this issue yesterday with curl 8.11.0 (working in 8.10.1) and determined the same cause.  Error messages like "SSL certificate problem: certificate has expired" and "SSL certificate problem: certificate revoked" are no longer reported in my case.
