### ISSUE TITLE
Stream 1: Solicitud de una página HTML

### ISSUE THREAD

**Issue by Dominicpalaciod** [curl/curl#15610]
### Specify which documentation you found a problem with

Conexión HTTP 2.0
Stream 1
Stream 2
Stream 2
Stream 1
DATOS
HEADERS
DATA
DATA
......
.......
Stream 5
.......
...
DATA
.
.......
Servidor
Cliente
1 conexión TCP

### The problem

Stream 1: Solicitud de una página HTML

**Comment by bagder** [comment]
Please clarify (in English) what the problem is.

**Comment by bagder** [comment]
Nothing to act on.
