### ISSUE TITLE
setopt(CURL_IPRESOLVE_V4) not work

### ISSUE THREAD

**Issue by lzqustc** [curl/curl#15611]
### I did this

libcurl v7.78.0, support ipv6 when compile the libcurl.so.

```
  CURL *curl = curl_easy_init();
  //setopt xxx

Retry:
  CURLcode res = curl_easy_perform(curl); 

  if( res == CURLE_COULDNT_RESOLVE_HOST || res == CURLE_OPERATION_TIMEDOUT) {
    curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
    printf("setopt: CURL_IPRESOLVE_V4 and Retry!!!");
    goto Retry;
  }
```

now the test network used VPN which only support IPV4, and when tcpdump the packages, we can see the dns(AAAA) request timeout, but there is not IPV4 dns request even the logs show  setopt CURL_IPRESOLVE_V4 and goto Retry.

### I expected the following

when IPV6 failed, it can switch to IPV4 and retry the request.

### curl/libcurl version

curl 7.78.0

### operating system

Android 13, API 33

**Comment by bagder** [comment]
Can you retry this with the latest version and see what happens? This is an old version and we have fixed related behaviors since.

**Comment by lzqustc** [comment]
ok, i found curl 7.86 has fixed it, thanks.
