### ISSUE TITLE
Win10 SDK: winsock2.h includes wincrypt.h which clashes with boringssl

### ISSUE THREAD

**Issue by BurningEnlightenment** [curl/curl#1562]
### I did this
I tried to compile libcurl with MSVC 14.10.25017, httponly and boringssl and ran into a spurious compiler error `C2059` in `openssl/base.h:248` complaining about a missing parameter list. Offending line:
`typedef struct X509_name_st X509_NAME;`
After doing some research I found out that there is a well known name collision between a define in `wincrypt.h` and said boringssl symbols. According to the curl mailing list this has already been worked around within the ldap implementation, but I ran into this issue while compiling completely ldap unrelated files like `base64.c` and `md5.c`. So I just forced msvc to output the include graph with `/showIncludes` and the important part is this:
```
../include\curl/curl.h
    [...]
    %winkit%\include\10.0.14393.0\um\winsock2.h
        [...]
        %winkit%\include\10.0.14393.0\um\windows.h
            [...]
            %winkit%\include\10.0.14393.0\um\winsock.h
            %winkit%\include\10.0.14393.0\um\wincrypt.h
```
Obviously `curl.h` transitively includes `wincrypt.h` in newer WinSDK versions and this leads to the above compiler error in every source file which includes `curl.h` and any openssl header. I worked around this by adding
```c
#ifdef HAVE_BORINGSSL
#  undef X509_NAME
#  undef X509_CERT_PAIR
#  undef X509_EXTENSIONS
#endif
```
to the end of `curl_setup.h` and `/DHAVE_BORINGSSL` to the CFLAGS in `MakefileBuild.vc`. I'm not sure whether this is the preferred fix which is why I haven't submitted a pr. HTH

### I expected the following
no compiler error

### curl/libcurl version
7.54 tarball
`curl -V` output:
```
curl 7.54.0 (x86_64-pc-win32) libcurl/7.54.0 BoringSSL WinIDN
Protocols: http https
Features: AsynchDNS IDN IPv6 Largefile NTLM SSL HTTPS-proxy
```
### operating system
Windows 10 Pro x64 Build 1703

### build command line:
```
nmake /f Makefile.vc mode=static ^
  WITH_DEVEL=..\deps    ^
  WITH_SSL=static    ^
  ENABLE_SSPI=no     ^
  ENABLE_WINSSL=no   ^
  DEBUG=no           ^
  MACHINE=x64        ^
  > build.log
```

**Comment by bagder** [comment]
I suppose we need to do this, even if the fault here is entirely with wincrypt and boringssl and not curl and it feels awkward to do it. We're just the victims here. But I think that by putting the logic into `curl_setup.h` as suggested we can also remove it from the ldap source...

Can you make a "proper" PR out of it?

**Comment by gvanem** [comment]
It would be easier to add `-DWIN32_LEAN_AND_MEAN` to the `CFLAGS` in `MakefileBuild.vc`. Thus `<wincrypt.h>` won't be included.

**Comment by BurningEnlightenment** [comment]
@gvanem have you already verified that it works with the latest Win SDK? I'm currently relatively busy and won't be able to test/touch this until Friday.

**Comment by gvanem** [comment]
@BurningEnlightenment I have just built libcurl with BoringSSL using MSC-2015 + WindowsKit version 10.0.15063.0. I assume this is the latest. If I do *not* add `-DWIN32_LEAN_AND_MEAN`, I get the error you reported.

**Comment by BurningEnlightenment** [comment]
> @BurningEnlightenment I have just built libcurl with BoringSSL using MSVC-2015 + WindowsKit version 10.0.15063.0. I assume this is the latest. If I do not add -DWIN32_LEAN_AND_MEAN, I get the error you reported.

Indeed, that's the latest and ~~greatest~~ problematic version. I also think that adding the `WIN32_LEAN_AND_MEAN` define with a commandline switch is the superior fix for the problem, would you mind opening a pr?
