### ISSUE TITLE
Cannot set options required for FTP transfers in libcurl with HTTP and MQTT disabled

### ISSUE THREAD

**Issue by momontyo** [curl/curl#15634]
### I did this

I have built libcurl using curl 8.11.0 sources, with only FTP/FTPS enabled.
This version responds with `CURLE_UNKNOWN_OPTION`(48) with the following option settings.

`CURLcode result = curl_easy_setopt(curl, CURLOPT_USERNAME, username);`

When tracked down in the debug run, `CURLOPT_USERNAME` and a number of other optional operating conditions in `setopt_cptr` were disabled in the compile condition.

The `#if` block starting with the following condition has a lot of impact and the `#endif` comment is incorrect.
Is there some error in manipulating nested relationships, etc.?

`#if !defined(CURL_DISABLE_HTTP) || !defined(CURL_DISABLE_MQTT)`
https://github.com/curl/curl/blob/ae016b0ccea79eeb0e5f1fd1d27dbf58a24059b5/lib/setopt.c#L1723-L2197

For builds with HTTP and MQTT disabled,
`CURLOPT_URL`, `CURLOPT_READDATA`, `CURLOPT_WRITEDATA`, etc. are also disabled.

### I expected the following

curl_easy_setopt should return CURLE_OK(zero).

### curl/libcurl version

curl 8.11.0 (i386-pc-win32) libcurl/8.11.0 OpenSSL/1.1.1w
Release-Date: 2024-11-06
Protocols: ftp ftps
Features: AsynchDNS Largefile SSL threadsafe UnixSockets

We use our own built module for FTP transfers.
Problem did not reproduce when building curl 8.10.1 source

### operating system

Windows 10 22H2 OS Build 19045.5011

**Comment by jay** [comment]
Please try #15640

**Comment by momontyo** [comment]
@jay 
Thanks for providing the pullrequest.
I immediately applied the lib/setopt.c patch to the 8.11.0 source and built it, and confirmed that the title issue is resolved.
I have not checked all the options, but I can confirm that FTP Download/Upload/Wildcard(Listing) works.

**Comment by jay** [comment]
Thanks
