### ISSUE TITLE
Curl installation problem with Homebrew on Mac Lion

### ISSUE THREAD

**Issue by viterzbayraku** [curl/curl#1563]
Curl is basic instrument for homebrew for install other applications. But my native curl application on Mac Lion 10.7.5 have issues. And I want reinstall it. I am trying to do this with command brew install curl but getting error "one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lldap -lz" And I do not understand how I can fix it :) Help :)

**Comment by bagder** [comment]
> my native curl application on Mac Lion 10.7.5 have issues. And I want reinstall it.

Isn't your "native curl" the version that comes bundled with macOS ? For all I know, you don't reinstall that with homebrew. You typically install the homebrew version next to the native (original) one.

>  I am trying to do this with command brew install curl but getting error 

That sounds like a problem with homebrew and not necessarily with curl. If you instead have build/install issues using the means we provide (configure or cmake etc), I think we'll be able to help.

**Comment by viterzbayraku** [comment]
This problem with libs i have only with latest version of curl. For example curl-7.43.0 installed without problems.

**Comment by bagder** [comment]
Then please show us how you invoke configure and some details on where you have the libraries installed. The key to most configure related problems is to investigate the `config.log` file after the run and see details for the particular check that failed.

The *not available run-time* error usually means that you've asked configure to use shared libraries from paths that aren't searched through by the run-time linker.

**Comment by viterzbayraku** [comment]
Hello again. Thank you for trying help me.
For install curl I am using `brew install curl` commang.
homebrew generating .configure like `./configure --disable-silent-rules --prefix=/usr/local/Cellar/curl/7.54.0 --with-ssl=/usr/local/opt/openssl --with-ca-bundle=/usr/local/etc/openssl/cert.pem --with-ca-path=/usr`... (i can not see all option in one line)

> checking for sys/socket.h... (cached) yes
> checking for struct timeval... yes
> checking run-time libs availability... failed
> configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lldap -lz 

config.log uploaded to attachment 
[config.log.txt](https://github.com/curl/curl/files/1067279/config.log.txt)

**Comment by bagder** [comment]
At config.log, line 4250 you can see a serious problem with your compiler/setup when the trivial test program crashes:
```
configure:27939: ./conftest
./configure: line 2237: 13442 Segmentation fault: 11  ./conftest$ac_exeext

```
... which the script takes, I should say quite legitimately, as a lack of verification that the libs work at run time. This is not a curl bug. This is something wrong with homebrew or your setup.

**Comment by viterzbayraku** [comment]
Daniel, thank you very much for your explanation :-)

**Comment by alet** [comment]
Hi,

There is a hardcoded CFLAG macosx-version-min in configure. You may want change value to 10.7. To install from brew:
1. brew install curl --debug
2. Choose shell
3. Fix macosx-version-min in configure
4. Look ./configure args in config.log
5. Run ./configure ARGS
6. Exit shell
7. Choose ignore

**Comment by mav2287** [comment]
I had this same issue and fixing that flag resolved it.
