### ISSUE TITLE
Inconsistent behaviour when mixing --continue-at with --no-clobber or --remove-on-error

### ISSUE THREAD

**Issue by piru** [curl/curl#15645]
### I did this

```
$ echo plop > robots.txt
$ curl --no-clobber -C 1 -O https://curl.se/robots.txt
```
The downloaded content is appended to`robots.txt` file.

and

```
echo plop > important
curl --remove-on-error -C 1 -o important https://nonexisting.curl.se/
```
The file `important` is removed.

### I expected the following

Curl should likely report and error instead of behaving inconsistently, or the documentation should be improved to mention the behaviour in these scenarios.

### curl/libcurl version

8.11.0

### operating system

Any

**Comment by bagder** [comment]
In the first case with `--no-clobber` and `--continue-at`, what could the user possibly want to happen? Is there a legit use case there? Should we make it simple and just deny that option combination?

**Comment by icing** [comment]
Since these options are fairly new, I think denying it makes sense.

**Comment by piru** [comment]
I think erroring out is the correct thing to do.

**Comment by meuUsuarioIo2007** [comment]
fod@
