### ISSUE TITLE
Missing typedef for curl_header_callback

### ISSUE THREAD

**Issue by polarina** [curl/curl#15654]
### I did this

The option `CURLOPT_HEADERFUNCTION` takes in a callback. A typedef for the header callback is missing from the public `curl/curl.h` header.

### I expected the following

I expected to be able to define a struct referencing the various callbacks needed to be set with `curl_easy_setopt`:
```c
#include <curl/curl.h>

struct curlopts {
	curl_debug_callback DEBUGFUNCTION;
	curl_header_callback HEADERFUNCTION;
	curl_opensocket_callback OPENSOCKETFUNCTION;
	curl_read_callback READFUNCTION;
	curl_write_callback WRITEFUNCTION;
};
```
Compiling this code gives an error:
```sh
$ gcc -S curl-struct.c
curl-struct.c:5:9: error: unknown type name ‘curl_header_callback’; did you mean ‘curl_read_callback’?
    5 |         curl_header_callback HEADERFUNCTION;
      |         ^~~~~~~~~~~~~~~~~~~~
      |         curl_read_callback
```

### curl/libcurl version

curl 8.11.0

### operating system

```
Linux kotek 6.11.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
It uses the same callback prototype as *WRITEFUNCTION: `curl_write_callback`

**Comment by polarina** [comment]
> It uses the same callback prototype as *WRITEFUNCTION: curl_write_callback

Have you considered adding `curl_header_callback` as an alias? Writing `curl_write_callback HEADERFUNCTION;` in my struct's definition would surely raise eyebrows during code-reviews as it would look like a mistake.

**Comment by bagder** [comment]
We have not for over twenty years. no. I rather not introduce it now either since it is superfluous and we in fact have the typechecker-gcc checks etc check that the argument is a curl_write_callback so it would not be entirely clean and straight forward.

**Comment by polarina** [comment]
Fair enough and thanks again for your time. I'll close the issue and consider the matter resolved.
