### ISSUE TITLE
FAQ and tutorial recommends insecure `--ftp-ssl` over `--ssl-reqd`

### ISSUE THREAD

**Issue by SuperStormer** [curl/curl#15658]
### Specify which documentation you found a problem with

https://curl.se/docs/tutorial.html
https://curl.se/docs/faq.html#FTPS_does_not_work

### The problem

https://curl.se/docs/tutorial.html suggests:
```
curl --ftp-ssl ftp://files.are.example.com/secrets.txt
```

https://curl.se/docs/faq.html#FTPS_does_not_work suggests:
> To use explicit FTPS, you use an FTP:// URL and the --ftp-ssl option (or one of its related flavors).

However, [the documentation for `--ftp-ssl`](https://curl.se/docs/manpage.html#--ssl) states that it is insecure and `--ssl-reqd` should be used instead as it won't revert to an insecure connection if the server doesn't support TLS. I suggest that the aforementioned docs be updated to recommend `--ssl-reqd` as well.

**Comment by Braga9823** [comment]
> ### Specify which documentation you found a problem with
> https://curl.se/docs/tutorial.html https://curl.se/docs/faq.html#FTPS_does_not_work
> 
> ### The problem
> https://curl.se/docs/tutorial.html suggests:
> 
> ```
> curl --ftp-ssl ftp://files.are.example.com/secrets.txt
> ```
> 
> https://curl.se/docs/faq.html#FTPS_does_not_work suggests:
> 
> > To use explicit FTPS, you use an FTP:// URL and the --ftp-ssl option (or one of its related flavors).
> 
> However, [the documentation for `--ftp-ssl`](https://curl.se/docs/manpage.html#--ssl) states that it is insecure and `--ssl-reqd` should be used instead as it won't revert to an insecure connection if the server doesn't support TLS. I suggest that the aforementioned docs be updated to recommend `--ssl-reqd` as well.
