### ISSUE TITLE
MSYS64 mingw64 calling curl_global_init before curl_easy_init causes error

### ISSUE THREAD

**Issue by irhyoreirrhtoi4etuiodfndvieont** [curl/curl#15664]
### I did this

Using mingw64 enviroment
```c
#include <curl/curl.h>

int main(int argc, char ** argv){
    curl_global_init(0);
    CURL * handle = curl_easy_init();

    printf("%p\n", handle);

    printf("URL: %i\n", curl_easy_setopt(handle, CURLOPT_URL, "https://en.wikipedia.org"));
    printf("VERB: %i\n", curl_easy_setopt(handle, CURLOPT_VERBOSE, 1L));
    printf("PER: %i\n", curl_easy_perform(handle));

    curl_easy_cleanup(handle);
    curl_global_cleanup();
    return 0;
}
```
installed mingw-w64-x86_64-curl
installed mingw-w64-x86_64-gcc
installed mingw-w64-x86_64-SDL2
installed mingw-w64-x86_64-SDL2_ttf

compiled with
```bash
/mingw64/bin/gcc.exe \
./main.c -o ./main.exe \
"-IC:\msys64\mingw64\include" \
"-LC:\msys64\mingw64\bin" -l:libcurl-4.dll
```

Folder 
[replicate.zip](https://github.com/user-attachments/files/17969235/replicate.zip)
also linked

### I expected the following

I expected it to connect to wikipedia.
[```curl_easy_init``` is said to automatically call ```curl_global_init``` if needed](https://curl.se/libcurl/c/curl_easy_init.html), but that it is discouraged, so I put ```curl_global_init``` before it. however, when I call ```curl_easy_perform``` I get:
```
URL: 0
VERB: 0
* getaddrinfo() thread failed to start
* Could not resolve host: en.wikipedia.org
* closing connection #0
PER: 6
```
I then commented out the global init call and it worked!

### curl/libcurl version

curl 8.11.0 (Windows) libcurl/8.11.0 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.63.0 nghttp3/1.6.0
Release-Date: 2024-11-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd

### operating system

MINGW64_NT-10.0-22631 penguin 3.5.4-0bc1222b.x86_64 2024-11-14 09:08 UTC x86_64 Msys

Windows build:
Edition	Windows 11 Home
Version	23H2
Experience	Windows Feature Experience Pack 1000.22700.1047.0
2 hidden fields for privacy

**Comment by dfandrich** [comment]
A zero flag is equivalent to CURL_GLOBAL_NOTHING, so nothing would be
initialized. If something needed to be initialized (but it wasn't) I could see
there being problems. What if you change that to CURL_GLOBAL_DEFAULT instead?

**Comment by irhyoreirrhtoi4etuiodfndvieont** [comment]
im stupid

**Comment by irhyoreirrhtoi4etuiodfndvieont** [comment]
it works

**Comment by irhyoreirrhtoi4etuiodfndvieont** [comment]
i read a lot of documentation but didn't read it for curl_global_init 🤦
