### ISSUE TITLE
curl 56 SSL_read: SSL_ERROR_SYSCALL, errno 0 - OpenSSL 3.3 & curl 8.9..8.11

### ISSUE THREAD

**Issue by pesto153** [curl/curl#15669]
### I did this

```
curl https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp
[...]
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0
```

This problem can be recreated, and it's like another issue found here: https://github.com/curl/curl/issues/13389

I also tested it with different versions of the Alpine/PHP container.

I'm sorry if this isn't a problem with curl. Right now, I don't know if the issue is with openssl, curl, or php.
This happened when I updated PHP to a new minor version.

I also tried different tests with other versions of the Alpine/PHP container. See:
```
$ docker run -it php:8.3-alpine3.18 sh

	# openssl version
	OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)

	# curl --version
	curl 8.5.0 (x86_64-alpine-linux-musl) libcurl/8.5.0 OpenSSL/3.1.4 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 nghttp2/1.57.0
	Release-Date: 2023-12-06
	Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
	Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSocket

	# curl https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp
	OK


$ docker run -it php:8.3-alpine3.19 sh

	# openssl version
	OpenSSL 3.1.7 3 Sep 2024 (Library: OpenSSL 3.1.7 3 Sep 2024)
	
	# curl --version
	curl 8.9.1 (x86_64-alpine-linux-musl) libcurl/8.9.1 OpenSSL/3.1.7 zlib/1.3.1 brotli/1.1.0 c-ares/1.27.0 libidn2/2.3.4 nghttp2/1.58.0
	Release-Date: 2024-07-31
	Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
	Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets

	# curl https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp
	OK



$ docker run -it php:8.3-alpine3.20 sh

	# openssl version
	OpenSSL 3.3.2 3 Sep 2024 (Library: OpenSSL 3.3.2 3 Sep 2024)
	
	# curl --version
	curl 8.11.0 (x86_64-alpine-linux-musl) libcurl/8.11.0 OpenSSL/3.3.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 c-ares/1.33.1 libidn2/2.3.7 libpsl/0.21.5 nghttp2/1.62.1
	Release-Date: 2024-11-06
	Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
	Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets zstd

	# curl https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublica.asp
	curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0

```

### I expected the following

Return without `curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0`

### curl/libcurl version

curl 8.11.0

### operating system

Alpine 3.20.3

**Comment by dfandrich** [comment]
This happens with the official curlimages/curl:8.11.0 container as well. The
end of the log with -vvv shows this:

00:00:38.051374 [0-0] == Info: [WRITE] cw_out, wrote 3725 body bytes -> 3725
00:00:38.051427 [0-0] == Info: [WRITE] download_write body(type=1, blen=3725) -> 0
00:00:38.051482 [0-0] == Info: [WRITE] client_write(type=1, len=3725) -> 0
00:00:38.051559 [0-0] == Info: [WRITE] xfer_write_resp(len=3725, eos=0) -> 0
00:00:38.051624 [0-0] == Info: [SSL] ossl_bio_cf_in_read(len=5) -> 0, err=0
00:00:38.051696 [0-0] == Info: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0
00:00:38.051808 [0-0] == Info: [SSL] cf_recv(len=102400) -> -1, 56
00:00:38.051922 [0-0] == Info: [WRITE] cw-out done
00:00:38.052012 [0-0] == Info: closing connection #0
00:00:38.052075 [0-0] == Info: [HTTPS-CONNECT] close
00:00:38.052182 [0-0] == Info: [SETUP] close
00:00:38.054255 [0-0] == Info: [SETUP] destroy
00:00:38.054326 [0-0] == Info: [HTTPS-CONNECT] destroy
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0

I don't know enough to say for certain but I suspect the server is not
performing a proper TLS close handshake. curl has become more stringent about
that in recent versions.

**Comment by bagder** [comment]
curl with GnuTLS identifies the problem:

`curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.`

a debug build with quictls as well:

`curl: (56) quictls SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)`

Meaning: the server is not shutting down the TLS connection correctly.

**Comment by icing** [comment]
> I'll try to report this to the company. Is there anything else we can do, like skip this check or something?
> 
> And thanks for taking a look.

This check cannot be disabled. It is there to assure that the server has send the complete response, e.g. your down is as it should be. The server in your example does not send a `Content-Length:` header. Without a "proper" close, curl cannot be certain if it has gotten the full response or just a part of it.
