### ISSUE TITLE
Multiple unit tests depends on documentation/manual pages being enabled and fails otherwise

### ISSUE THREAD

**Issue by diizzyy** [curl/curl#15703]
### I did this

Using CMake:
Build with ```BUILD_LIBCURL_DOCS``` , ```BUILD_MISC_DOCS``` and ```ENABLE_CURL_MANUAL``` disabled
Execute unit tests (test-nonflaky)

### I expected the following

test481 and test482 fails because of this:
```curl: try 'curl --help' for more information```
vs
```curl: try 'curl --help' or 'curl --manual' for more information```

..and a few more tests:
FAIL 1139: 'Verify that all libcurl options have man pages' source analysis, symbols-in-versions, documentation, --manual
FAIL 1140: 'Verify the nroff of manpages' source analysis, symbols-in-versions, documentation
FAIL 1173: 'Manpage syntax checks' source analysis, documentation, --manual
FAIL 1177: 'Verify that feature names and CURL_VERSION_* in lib and docs are in sync' source analysis, CURL_VERSION
FAIL 1477: 'Verify that error codes in headers and libcurl-errors.3 are in sync' documentation

### curl/libcurl version

curl master branch, 59fec5a

### operating system

FreeBSD 14.1-RELEASE

**Comment by vszakats** [comment]
Thanks for you report!

Fix proposal:
#15704 (also for `./configure`, where there was additonal issue)

I'm not sure how to fix 481 and 482. They expect a fixed string
which is different depending the bulit-in manual option.

**Comment by diizzyy** [comment]
Thanks for the quick fix!
