### ISSUE TITLE
Not entirely portable use of usleep() in tests

### ISSUE THREAD

**Issue by rsbeckerca** [curl/curl#15711]
### I did this

Compiled curl with OpenSSL and c99 on NonStop x86, and got a compile error on `usleep(100*1000)`. This function is only available in threaded code on NonStop. I need to use `sleep(100)` instead if not threaded.

Any objection if I put a pull request together for this?

### I expected the following

Clean compile of the test suite.

### curl/libcurl version

curl 8.11.0

### operating system

NonStop L24.08

**Comment by vszakats** [comment]
Any reason not to use `sleep()` on all platforms? (Except on Windows, which needs it remapped to `Sleep()`)

**Comment by rsbeckerca** [comment]
> Any reason not to use `sleep()` on all platforms? (Except on Windows, which needs it remapped to `Sleep()`)

I would have though that the technique used for `Sleep()` throughout the code would be better, but I'm somewhat confused as to how that even works. However, `sleep()` on NonStop does not appear to be thread blocking in all threading models, while `usleep()` has a safe wrapper. This is only in `ws-data.c` and `ws-pingpong.c`.

**Comment by rsbeckerca** [comment]
My proposed PR is now up.

**Comment by bagder** [comment]
> Any reason not to use `sleep()` on all platforms? (Except on Windows, which needs it remapped to `Sleep()`)

Because POSIX `sleep()` is in number of **seconds**, usleep is microseconds. Apparently NonStop has a special  sleep().

**Comment by vszakats** [comment]
> > Any reason not to use `sleep()` on all platforms? (Except on Windows, which needs it remapped to `Sleep()`)
> 
> Because POSIX `sleep()` is in number of **seconds**, usleep is microseconds. Apparently NonStop has a special sleep().

Ah, micro vs. milli got me!

**Comment by rsbeckerca** [comment]
> > > Any reason not to use `sleep()` on all platforms? (Except on Windows, which needs it remapped to `Sleep()`)
> > 
> > 
> > Because POSIX `sleep()` is in number of **seconds**, usleep is microseconds. Apparently NonStop has a special sleep().
> 
> Ah, micro vs. milli got me!

Actually I meant milli, but `sleep()` is seconds.
