### ISSUE TITLE
Automatic proxy detection

### ISSUE THREAD

**Issue by paulharris** [curl/curl#1572]
Hi,

I wrote a proxy detector (for Windows) which has worked well in my experience,
I'd like to suggest that you somehow add it to libcurl so everyone can benefit and improve on it.
You are welcome to chop the important bits out of it, the real code is not very long.

https://github.com/paulharris/libdetectproxy

cheers,
Paul

**Comment by bagder** [comment]
I suggest you either kick off the work on this as a pull request or you ask for help/assistance on the curl-library mailing list (or both!). This topic isn't strictly a bug or a problem in curl/libcurl so this isn't "an issue" strictly speaking.
