### ISSUE TITLE
why not encode the request url as default behavior?

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [curl/curl#1573]
first, thanks a lot for your work.  
This problem is not a bug or error, But some time it annoy me. In China, many programmer use chinese character as variable or file name, so the url usually contains non ascii character too, and curl only has  --data-urlencoded , which just encode parameters but not the url itself, I have to do the encode by other way, so I want to know why not add a parameter like "--encode-url" or make it (encode url) as default behavior for curl ?

**Comment by bagder** [comment]
Thanks for the suggestion, but...

First, this is an issue tracker and not a suitable place to ask for features. You're better off discussing these matters on the curl-library mailing list.

It is not a straight-forward operation to simply "encode" what's *almost* a URL into a legitimate URL. It requires a set of assumptions or conditions which at least I am not at all sure of. If you can specify to us with more details on exactly how you envision that this could work then we should be able to evaluate how feasible it is and what we can do or not do to make it happen. But again, that's for the mailing list. Or perhaps even better if you can write up a first attempt as code and submit as a pull request?

**Comment by hh-in-zhuzhou** [comment]
thanks for your reaction.
I'm sorry if I write these at the wrong place, then I will try to describe details  of what I met at right place and may write some code to submit.
thanks again.
