### ISSUE TITLE
REQ: output viewer

### ISSUE THREAD

**Issue by pepa65** [curl/curl#1574]
Feature request (I looked through todo.html to check it wasn't already listed):

### I did:
`curl -sL --viewpipe https://url.to/script |bash`
### I expected the following:
viewing the downloaded script with the option to abort or continue
### curl/libcurl version:
all
### curl -V output:
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```
### operating system:
Ubuntu linux 16.04

This request has to do with about piping curl-downloaded scripts into bash, (or some other interpreter) often to install programs or do other tasks. Some say you should never do this (always download and view the script before executing it manually), but the practice remains because it is so convenient. If only it were safe..!

Background:
https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/
https://sysdig.com/blog/friends-dont-let-friends-curl-bash/

My feature request is to include a tiny text viewer with the curl binary that can be activated by a command line switch, that allows users to view what has been downloaded before piping it on. Ctrl-C would abort, and some other key would signify it's OK to continue.

curl -sL --viewpipe https://url.to/script |bash

I understand your first reaction would be feature creep, but it would make the world a safer place for people engaging in piping wget into bash. The alternate option would be to have a little application in between curl and bash, except that application also doesn't exist, and it most likely would not be installed, and it's less convenient overall. The added size would be really minimal.

Wouldn't that be a great added value??
Peter

**Comment by bagder** [comment]
First, this is an issue tracker and not a suitable place to ask for features. You're better off discussing these matters on the curl-users mailing list.

So `--viewpipe` would be the equivalent of downloading to a file, running less on it and then send it all to stdout after some magic key is pressed?

I'm not convinced this is a good idea.

1. (re-)Implementing "less" is a lot of code and complicated to make it work everywhere (multi platform) in a decent way
2. it would require the introduction of storing downloaded contents somewhere while this processing is taking place, downloads that risk lingering around and cause annoyances
3. you're asking for functionality that is **trivially** and **widely** available already, just not built-in. Just download the script and use more or less on it first, then pass it on to bash. As the FAQ states: *We do not add things to curl that other small and available tools already do very well at the side.*
4. I think the assumption that people would be able to add `--viewpipe` into a command line they copy and paste from the web but not download to a file and run less on the data is far too optimistic.

**Comment by pepa65** [comment]
Thanks for your response. I did post on curl-users, but got no replies yet. Some instructions on participating caused me to think posting an issue would be acceptable.

1. less is extremely complex and feature-rich. I was thinking an ultra-basic viewer. I thought curl would already have all the bits in place to implement it.
2. Store in memory. These scripts are often less than 1 kB. If they would be over 1MB, reviewing them like this would be utterly unreasonable. These days using 100MB of RAM is peanuts... :-(
3. Of course, everybody just downloads and just views then. But, I just learned about vipe (in moreutils) which does what I want. So this point stands clear. I didn't know about this when I posted.
4. These types of commandlines are often suggested. So a responsible someone who would offer this method of installation would include `--viewpipe`, that's the idea.

Thank you for offering your point of view and sorry for posting here.

**Comment by bagder** [comment]
No, curl has no viewing code already. It can't save it all in memory unconditionally since you may transfer a humongously huge file so the logic to store on disk still needs to be there.

Ultimately I think this idea suffers from the problem that the people who should use `--viewpipe` won't and those who would know about and use it are the ones who can download and inspect the file already as it is.

Thanks a lot for your thoughts and ideas on how to improve curl though!

**Comment by pepa65** [comment]
I understand you closed this, but allow me one comeback:
- Even if it would just be outputting it plainly to the screen, that would already be a huge improvement.
- I would suggest no storage logic necessary, as soon as the file size is past say 5KB, you start ignoring the `--viewpipe` flag.
- Sites advocating the usage of curl for installing would use the `--viewpipe` flag, and 'recipes' would start to include the flag, articles will be written saying that piping from the internet into bash is only OK with the `--viewpipe` flag. But if it doesn't exist, that can't happen.
I totally understand your unwillingness, but getting a flag like this into curl would be the best for these use cases. Or into wget. If that doesn't work, perhaps in less? But that would be an explicit extra addition to the pipe. Well, thanks for engaging with this.
