### ISSUE TITLE
Curl rejects connection to https://boinc-files.bakerlab.org/ while Chrome connects without https errors.

### ISSUE THREAD

**Issue by kotenok2000** [curl/curl#15747]
### I did this

I ran curl https://boinc-files.bakerlab.org/rosetta/download/
Result: curl: (60) SSL certificate problem: unable to get local issuer certificate.

### I expected the following

Connection without https errors 

### curl/libcurl version

Curl 7.81.0

### operating system

Ubuntu 22.04

**Comment by dfandrich** [comment]
This site has issues with its certificate. Chrome has probably cached an
intermediate certificate which it uses, but a brand-new Chrome install will
likely also fail on this site. You can see the issue (Chain issues: Incomplete)
at https://www.ssllabs.com/ssltest/analyze.html?d=boinc%2dfiles.bakerlab.org&latest
which gives the site a "B" grade.  It's not a curl issue.

**Comment by kotenok2000** [comment]
I have installed firefox  and checked from there. It works too.

**Comment by dfandrich** [comment]
It works the same way. The certificate chain is bad, and the browsers try to work 
around the problem as best they can. If you start a new Firefox profile, it
will likely fail as well.

**Comment by kotenok2000** [comment]
It is able to connect if i use app.any.run sandbox.
![image](https://github.com/user-attachments/assets/dcafa377-8c1d-4e9d-9515-cf84d565c51f)

**Comment by bagder** [comment]
An incomplete chain, as in missing intermediate certs, is a server malconfig.

There are ways browsers and other tools do to work around the problems with this, but curl does not do those and will instead fail like this. The cert chain is incomplete. curl cannot trust that site. This is not a curl bug. This is a bad server.

**Comment by kotenok2000** [comment]
There could be websites that prevent scraping like this.
