### ISSUE TITLE
cmake install error for android on release 8.11.1 

### ISSUE THREAD

**Issue by YiQiu1984** [curl/curl#15754]
### I did this

my build script :
~~~shell
#!/bin/bash


source ./build-android-env.sh

INSTALL_DIR=$BUILD_DIR/curl

if [ ! -d $INSTALL_DIR ]; then
    mkdir -p $INSTALL_DIR
fi

cd curl-curl-8_11_1


function build() {
    export TARGET_HOST=$1
    export ANDROID_ARCH=$2
    export OPENSSL_ROOT_DIR=$BUILD_DIR/openssl/$ANDROID_ARCH

    echo $BUILD_DIR/zlib/$ANDROID_ARCH
    echo $BUILD_DIR/openssl/$ANDROID_ARCH


    echo $(pwd)
    cmake -B $INSTALL_DIR/$ANDROID_ARCH \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/Android.toolchain.cmake \
                -DANDROID_ABI=$ANDROID_ARCH \
                -DANDROID_PLATFORM=$MIN_SDK_VERSION \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -DCURL_DISABLE_LDAP=ON  \
                -DCURL_USE_OPENSSL=ON \
                -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR

    make -j8
    make install
    make clean
}


build aarch64-linux-android arm64-v8a
build armv7a-linux-androideabi armeabi-v7a
#build i686-linux-android x86
#build x86_64-linux-android x86_64

cd ..
~~~

OPENSSL_ROOT_DIR is my local openssl output dir.  I failed to run the build script and gave out  the error message below:
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.30/Modules/FindOpenSSL.cmake:689 (find_package_handle_standard_args)
  CMakeLists.txt:634 (find_package)

### curl/libcurl version

curl 8.11.1

### operating system

macOS Sonoma 14.2

**Comment by vszakats** [comment]
You may find out more on why OpenSSL isn't detected by looking inside
`CMakeFiles/CMakeConfigureLog.yaml`.

**Comment by vszakats** [comment]
The above error can be normal (I don't know if it is or not for Android specifically),
but unrelated to OpenSSL detection.

It seems CMake doesn't leave much hints in this file regarding OpenSSL detection,
so the next best thing is enabling CMake debug facilities, for example `--debug-find`.

**Comment by YiQiu1984** [comment]
> The above error can be normal (I don't know if it is or not for Android specifically), but unrelated to OpenSSL detection.
> 
> It seems CMake doesn't leave much hints in this file regarding OpenSSL detection, so the next best thing is enabling CMake debug facilities, for example `--debug-find`.

After adding OPENSSL_CRYPTO_LIBRARY and OPENSSL_INCLUDE params to the CMake cmd, the entire cmd is below:
`cmake -B $INSTALL_DIR/$ANDROID_ARCH --debug-find \
                -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/Android.toolchain.cmake \
                -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR \
                -DANDROID_ABI=$ANDROID_ARCH \
                -DANDROID_PLATFORM=$MIN_SDK_VERSION \
                -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -DCURL_DISABLE_LDAP=ON  \
                -DCURL_USE_OPENSSL=ON \
                -DCURL_ZLIB=ON \
                -DZLIB_INCLUDE_DIR=$ZLIB_DIR/include \
                -DZLIB_LIBRARY=$ZLIB_DIR/lib/libzlib.a \
                -DOPENSSL_CRYPTO_LIBRARY=$OPENSSL_ROOT_DIR/lib/libcrypto.a \
                -DOPENSSL_INCLUDE_DIR=$OPENSSL_ROOT_DIR/include \
                -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR `

A new error is appeared:
-- Looking for SSL_set0_wbio
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSL_SSL_LIBRARY
    linked by target "cmTC_f781c" in directory /Users/qiuyi/Code/third_party/build/curl/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-IXkVeP

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.30/Modules/CheckSymbolExists.cmake:154 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.30/Modules/CheckSymbolExists.cmake:66 (__CHECK_SYMBOL_EXISTS_IMPL)
  CMakeLists.txt:839 (check_symbol_exists)
  CMakeLists.txt:866 (openssl_check_symbol_exists)

BTW, OpenSSL version is 3.4.0

**Comment by vszakats** [comment]
Have you tried pointing `OPENSSL_SSL_LIBRARY` to `libssl.a`?
