### ISSUE TITLE
Can't post formdata ;type= with number

### ISSUE THREAD

**Issue by IcedCoffeee** [curl/curl#15761]
### I did this

```bash
curl -X POST -F "file=@video.mp4;type=video/mp4" https://example.com
curl: (26) Failed to open/read local data from file/application
```
and
```bash
curl -F "data=test;type=test/test1" https://example.com
Warning: garbage at end of field specification: 1
```

however, removing the number in either of the types stops that error from occurring and uploads the file/data as expected.

### I expected the following

This used to work, but from searching around a bit, I think this is what's causing the issue
https://github.com/curl/curl/blob/a3585c9576abccddbd27200058912cef900c3c0f/src/tool_formparse.c#L504
which got changed in 9664d5a and would explain why it stopped working recently.

### curl/libcurl version

curl 8.11.1 (x86_64-pc-linux-gnu) libcurl/8.11.1 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.64.0 nghttp3/1.6.0

### operating system

Arch Linux

**Comment by bagder** [comment]
That's my silly mistake. I'll fix.
