### ISSUE TITLE
Incorrect mbedtls_ssl_write usage causes ranges of bytes to get lost

### ISSUE THREAD

**Issue by LBPHacker** [curl/curl#15801]
### I did this

Using mbedtls 3.6.2 = Mbed-TLS/mbedtls@107ea89daaef and nghttp2 1.50.0 = nghttp2/nghttp2@87fef4ab71be, HTTP/2 requests with large-ish (600kB+) request bodies often fail with `HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)`. Wireshark traces I have taken show that the data stream ends sooner than the content-length header would suggest, and the server gives up after some inactivity and fails the request. Matching up frames with known data shows that ranges of bytes inside the TLS stream occasionally get lost.

This has prompted me to look at how data is passed to mbedtls:

https://github.com/curl/curl/blob/7eb8c048470ed2cc14dca75be9c1cdae7ac8498b/lib/vtls/mbedtls.c#L1169-L1194

Given [the documentation on mbedtls_ssl_write](https://mbed-tls.readthedocs.io/projects/api/en/v3.6.2/api/file/ssl_8h/#ssl_8h_1a5bbda87d484de82df730758b475f32e5), which states that when `MBEDTLS_ERR_SSL_WANT_WRITE` is returned, the same arguments must be passed the next time, this seems incorrect: simply returning `CURLE_AGAIN` allows for *more* data to be given to this function than the amount given at the previous call.

I have made a change locally that makes sure that when `MBEDTLS_ERR_SSL_WANT_WRITE` is returned, the exact same arguments are passed the next time around, even if `mbed_send` has more data to send than the last time (and return an appropriate `ret`), and indeed, this fixes my issue.

This is not a pull request because the underlying issue seems to be one of design, and I am not willing to tackle fixing it: as far as I can tell, libcurl is designed with [write(2)](https://linux.die.net/man/2/write)-like behaviour in mind, i.e. ranges of bytes that are reported sent *have been* sent (or the stream breaks later, etc.), and ranges reported to have been left unsent are not sent, but also *not committed* anywhere. The issue with mbedtls seems to be that it effectively commits ranges of bytes internally, which is not compatible with this design.

### I expected the following

I expected the aforementioned requests to succeed. Excuse me for filling this field with such an abstract answer; the issue I am facing is also abstract.

### curl/libcurl version

curl 8.10.1 = 7eb8c048470e

### operating system

Windows 10.0.19045.3570

**Comment by LBPHacker** [comment]
All that said, if it can be guaranteed that any data ever presented to `mbed_send` is effectively committed, in the sense that it will not change between calls even in the case of partial writes (I have been unable to confirm this), a potential fix may be as simple as remembering how much data was passed to `mbedtls_ssl_write` in the previous call if it returned `MBEDTLS_ERR_SSL_WANT_WRITE` and trying to send only as many the next call.

**Comment by icing** [comment]
@LBPHacker nice find. I think we'll need to adapt the repeated write behaviour for that backend.

**Comment by LBPHacker** [comment]
Thanks for confirming. Does this mean that this repeated write behaviour is already present somewhere in the codebase?

**Comment by icing** [comment]
> Thanks for confirming. Does this mean that this repeated write behaviour is already present somewhere in the codebase?

No, we have to adapt our mbedtls backend implementation.

**Comment by icing** [comment]
I propose a fix for this in #15846. I was able to reproduce the problem with a special, local setup, but could not make it into a reliable test case. Would be nice if you could verify that the PR works for you.

**Comment by LBPHacker** [comment]
Thank you, I will test this in a bit. However, I have concerns regarding the fix.

As far as I can tell, it is essentially what I proposed in my second comment, but I have as yet been unable to confirm that libcurl in any way prevents passing `mbed_send` data *different*  from the last call. In fact, I am fairly sure that when using `CURLOPT_CONNECT_ONLY`, calling `curl_easy_send` from user code ultimately resolves to a call to `mbed_send`, which suggests that it is entirely up to user code to keep in mind and deal with this pickiness of mbedtls.

Further, calling `mbedtls_ssl_write` with 0 bytes of data is allowed and produces a TLS frame, and most likely can also yield `MBEDTLS_ERR_SSL_WANT_WRITE` (I have seen no indication of the contrary). As far as I can tell, `curl_easy_send` passes such empty ranges of bytes to `mbedtls_ssl_write` without question, so this is also doable from user code. However, the fix uses 0 as a special value to indicate "not blocked in mbedtls".

Are these concerns valid? Am I missing context here?

**Comment by icing** [comment]
Just pushed the change to the PR. If your system is still hot, would be nice to get a verification. Thanks!

**Comment by LBPHacker** [comment]
Nope, that last change broke it. Most likely because this line:

https://github.com/curl/curl/blob/6d416d649da694c579c9f5c284393e5a23be62e4/lib/vtls/mbedtls.c#L1223

still uses `backend->send_blocked_len` to decide whether the write is being blocked, and that variable never gets reset to 0.

**Comment by icing** [comment]
Arg, my bad. Just pushed a fix.

**Comment by LBPHacker** [comment]
Working as intended now :+1:
