### ISSUE TITLE
install problem on linux mint 18.1

### ISSUE THREAD

**Issue by jjssoftware** [curl/curl#1581]
I built and installed 7.54.1 from source as follows:

`./configure --prefix=/usr --disable-static --enable-threaded-resolver --with-ca-path=/etc/ssl/certs && make`

`sudo make install`

All tests passed fine when run, yet the problem I encountered was a broken install because libcurl.so.4.4.0 wasn't copied to /usr/lib/x86_64-linux-gnu/ as part of make install. It was enough to manually fix after the event.

Any idea what went wrong?

**Comment by bagder** [comment]
[This is not a bug, please don't use the issue tracker for support questions.]

`make install` installs the lib into $prefix/lib by default.

**Comment by jjssoftware** [comment]
With respect, this could well be a bug and not a support question. In my opinion you've prematurely closed this down.

I understand that libcurl.so.4.4.0 will end up in $prefix/lib at install time, this behavior is documented here: https://curl.haxx.se/libcurl/using/curl-config.html

Yet there's nothing documented to enable this behavior to be overridden and from my tests, the install doesn't work out the correct target location for libcurl.so.4.4.0 on Linux Mint 18.1. As a result users can end up with a broken install by default. Personally I call that a bug.

btw as an aside at the time of writing, https://curl.haxx.se/download.html reports 7.54.1 as the latest Released on the 14th of June 2017 yet https://github.com/curl/curl/releases advises 7.54.0 as the latest release.

**Comment by jay** [comment]
> Yet there's nothing documented to enable this behavior to be overridden and from my tests, the install doesn't work out the correct target location for libcurl.so.4.4.0 on Linux Mint 18.1. As a result users can end up with a broken install by default. Personally I call that a bug.

I don't see how this is a bug. It seemed to have installed to the prefix you told it to which is not a broken install. If you really want to get detailed about it can't you use these from `./configure --help`:
~~~
Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
  --mandir=DIR            man documentation [DATAROOTDIR/man]
  --docdir=DIR            documentation root [DATAROOTDIR/doc/curl]
  --htmldir=DIR           html documentation [DOCDIR]
  --dvidir=DIR            dvi documentation [DOCDIR]
  --pdfdir=DIR            pdf documentation [DOCDIR]
  --psdir=DIR             ps documentation [DOCDIR]
~~~

Note /usr/lib/x86_64-linux-gnu/ is a system location. When you install libraries usually the default prefix is /usr/local then it goes in /usr/local/lib. For example it's possible to have a packaged system libcurl that comes in /usr/lib/x86_64-linux-gnu and then your own which goes in /usr/local/lib

**Comment by jjssoftware** [comment]
Thanks that makes sense, much appreciated.
