### ISSUE TITLE
HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by 0xCognition** [curl/curl#15811]
### I did this

curl https://www.homes.com/
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

FYI --- This is likely either an accidental misconfiguration on the server or an intentional misconfiguration to prevent clients from connecting. Either way, homes.com is a very popular website, and the thought is a user might simply expect their curl request to "just work," even when dealing with potentially non-compliant servers. This site happens to not implement a fallback to HTTP/1.1, so conceivably non-compliant servers could be a bigger problem in the future --- especially if intentional.

### I expected the following

Actual data in the response

### curl/libcurl version

curl 8.5.0

### operating system

Ubuntu 24.04

**Comment by bagder** [comment]
This reproduces for me with 8.11.1 as well, both using GnuTLS and OpenSSL. Although the OpenSSL build gives me a different error and it takes longer to get it shown:

~~~
curl: (16) Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.

**Comment by jay** [comment]
I can also reproduce. Wireshark shows the server is sending a SETTINGS and RST_STREAM together immediately in reply

**Comment by bagder** [comment]
That could imply that they do this on purpose.

**Comment by bagder** [comment]
This works, proving the server denies curl on purpose:

~~~
curl https://www.homes.com/ -A "Mozilla"
