### ISSUE TITLE
Most autobuilds failing because of SSCANF checksrc warnings

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#15821]
### I did this

Look at the autobuilds at https://curl.se/dev/builds.html, for example:
https://curl.se/dev/log.cgi?id=20241223170611-2352984#prob1

### I expected the following

No checksrc warnings.

Instead, most autobuilds are red because of SSCANF checksrc warnings in tests/server, even though it's disabled in tests/server/.checksrc. The file is also present in the daily snapshot.

### curl/libcurl version

https://github.com/curl/curl/commit/c2ac9ea1eebe929b79c23f90038cafefee1ef4be

### operating system

Windows, Solaris, NetBSD, Linux

**Comment by bagder** [comment]
Hm, curious. What makes the script fail there but work in the CI?

**Comment by vszakats** [comment]
23749bfd04b72c21e30d7f53e740fad1759ed7ea changed the per-directory config local logic a little. It might have caused a local `.checksrc` to no longer kick in in libssh2: https://github.com/libssh2/libssh2/commit/1117b677a0c5e3b195f1504a49ed3b61472fcc07.

In curl root, it replicates with `scripts/checksrc.pl $(git ls-files '*.c')`,
where the per-dir configs are missed.

This works as expected:
```
scripts/checksrc.pl docs/examples/*.c tests/server/*.c
```
but `tests/server/.checksrc` doesn't seem to be loaded.

(It's possible I'm holding it wrong.)

**Comment by bagder** [comment]
The logic for loading `.checksrc` gets wrong if the script gets multiple directories in the same command line invoke, since it only reads it from the first directory used. But I don't think we invoke it like that anywhere?

But when I try `./scripts/checksrc.pl tests/server/*.c` it reads `./tests/server/.checksrc` correctly. And when I do `cd tests/server` and invoke `../../scripts/checksrc.pl *.c` it reads `./.checksrc`.

**Comment by bagder** [comment]
I made #15834 which probably fixes this and makes more sense in general I think since it follows the already established practice when warning about use of specific functions.

**Comment by MarcelRaad** [comment]
Works now after https://github.com/curl/curl/pull/15835, thanks!
