### ISSUE TITLE
OpenSSL headers and library versions do not match

### ISSUE THREAD

**Issue by dertin** [curl/curl#1583]
1- Install OpenSSL 1.1.0f in Debian 8.8 x32:
 ```
  ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
  make
  make test
  make install
  openssl version -v
```
2- Install nghttp2

3- Problems to install curl 7.54.1 `./configure --with-nghttp2 --with-ssl`

OpenSSL version: [opensslv.h](https://github.com/openssl/openssl/files/1082643/opensslv.h.txt)
CURL: [config.log](https://github.com/openssl/openssl/files/1082660/config.log.txt)

**CURL Error:**
> checking for OpenSSL headers version... 1.1.0 - 0x1010006fL
> checking for OpenSSL library version... 1.0.1
> checking for OpenSSL headers and library versions matching... no
> configure: WARNING: OpenSSL headers and library versions do not match.
> ...
> ...
> ...
> ...
> vtls/openssl.c: In function ‘Curl_ossl_seed’:
> vtls/openssl.c:279:5: error: implicit declaration of function ‘RAND_egd’ [-Werro r=implicit-function-declaration]
> int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
> ^
> cc1: some warnings being treated as errors
> Makefile:2030: recipe for target 'vtls/libcurl_la-openssl.lo' failed
> make[2]: *** [vtls/libcurl_la-openssl.lo] Error 1
> make[2]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:741: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:902: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
> Making install in lib
> make[1]: Entering directory '/var/tmp/curl_build/curl_src/lib'
> CC vtls/libcurl_la-openssl.lo
> vtls/openssl.c: In function ‘Curl_ossl_seed’:
> vtls/openssl.c:279:5: error: implicit declaration of function ‘RAND_egd’ [-Werro r=implicit-function-declaration]
> int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
> ^
> cc1: some warnings being treated as errors
> Makefile:2030: recipe for target 'vtls/libcurl_la-openssl.lo' failed
> make[1]: *** [vtls/libcurl_la-openssl.lo] Error 1
> make[1]: Leaving directory '/var/tmp/curl_build/curl_src/lib'
> Makefile:902: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

**In config.log see:**
> configure:23234: Added /usr/local/lib to LD_LIBRARY_PATH
> configure:23244: **checking for OpenSSL headers version**
> configure:23274: gcc -E   -I/usr/local/include   conftest.c
> configure:23274: $? = 0
> configure:23335: result: 1.1.0 - 0x1010006fL :thumbsup:
> configure:23344: **checking for OpenSSL library version**
> configure:23412: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers   **-I/usr/local/include   -L/usr/lib/i386-linux-gnu  -L/usr/local/lib**  conftest.c -lssl -lcrypto -lssl -lcrypto  -llber -lldap -lz  >&5
> /tmp/cconm5OL.o: In function `main':
> conftest.c:(.text.startup+0x12): undefined reference to `SSL_CTX_set_not_resumable_session_callback'
> collect2: error: ld returned 1 exit status :-1:
> configure:23412: $? = 1
> configure: failed program was:

**Can there be a problem with the order of the directories ?**
Seen in config.log: `-I/usr/local/include   -L/usr/lib/i386-linux-gnu  -L/usr/local/lib`

**# ldconfig -p | grep libcrypto**
```
        libcrypto.so.1.1 (libc6) => /usr/local/lib/libcrypto.so.1.1
        libcrypto.so.1.0.0 (libc6, hwcap: 0x0008000000008000) => /usr/lib/i386-linux-gnu/i686/cmov/libcrypto.so.1.0.0
        libcrypto.so.1.0.0 (libc6, hwcap: 0x0004000000000000) => /usr/lib/i386-linux-gnu/i586/libcrypto.so.1.0.0
        libcrypto.so.1.0.0 (libc6) => /usr/lib/i386-linux-gnu/libcrypto.so.1.0.0
        libcrypto.so (libc6) => /usr/lib/i386-linux-gnu/libcrypto.so
        libcrypto.so (libc6) => /usr/local/lib/libcrypto.so
```
**# openssl version -v**
`OpenSSL 1.1.0f  25 May 2017`

Installer script: https://gist.github.com/dertin/8de14e458dd4f0d3acb5f0deff120951

**Comment by jay** [comment]
The last report of this I can find is #1420 and it had to do with pkg-config not excluding a system directory for zlib. It looks like this may be similar. The config.log doesn't record the result of zlib pkg-config so I'm not sure. What is the result of `/usr/bin/pkg-config --libs-only-L zlib`

**Comment by dertin** [comment]
**# /usr/bin/pkg-config --libs-only-L zlib**
`-L/usr/lib/i386-linux-gnu`

Should the result be /usr/local/lib/ ?

**Comment by jay** [comment]
> **# /usr/bin/pkg-config --libs-only-L zlib**
> -L/usr/lib/i386-linux-gnu

Ok that's the issue then, but it's not a curl issue. You might try `pkg-config --debug --print-errors`. pkg-config is supposed to detect system directories and exclude them from -L output. Why it's not doing that I don't know, you'll have to ask in a Debian forum.

By specifying CPPFLAGS/LDFLAGS you should be able to make /usr/local come first, for example
~~~
CPPFLAGS=-I/usr/local/include \
LDFLAGS=-L/usr/local/lib \
./configure 
~~~

**Comment by dertin** [comment]
The -L parameters are being included correctly. ?

> gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers   -I/usr/local/include 
 **-L/usr/lib/i386-linux-gnu**  -L/usr/local/lib  conftest.c -lssl -lcrypto -lssl -lcrypto  -llber -lldap -lz  >&5

If I did not have an old OpenSSL library in /usr/lib/i386-linux-gnu
Maybe it would work.

That the zlib library is located in "/usr/lib/i386-linux-gnu" instead of "/usr/local/lib" could cause me some problem.?

**Comment by jay** [comment]
No, it is not correct. -L/usr/lib/i386-linux-gnu being returned by pkg-config is not a curl issue, I can only assume it's a Debian issue since pkg-config seems to work fine for everyone else. I would ask in a Debian forum to see if anyone can reproduce and if so then file a bug with Debian.

**Comment by dertin** [comment]
it works! Solved.

It occurred to me, compile zlib. This way the library would be in "/usr/local/lib"

Look at my installation script: https://gist.github.com/dertin/8de14e458dd4f0d3acb5f0deff120951

I do not understand why the parameter -L /usr/lib/i386-linux-gnu is added to check the openssl library. Maybe it is done because zlib is used.
But, it uses the previous version of the OpenSSL library of that directory

I do not speak English very well. I hope you can understand me.

Thanks for the help.

**Comment by dertin** [comment]
Oops, I have recently realized that curl is not using the latest version of OpenSSL.

I will continue trying.

**Comment by jay** [comment]
You may need to set an rpath
~~~
CPPFLAGS=-I/usr/local/include \
LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" \
./configure
~~~

**Comment by dertin** [comment]
Solved.

It worked, thank you.
I share the compilation sequence I make in case you want to suggest me to remove something or add.

> Debian 8.8 x32 - DigitalOcean
> Linux framework 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2 (2017-04-30) i686 GNU/Linux

**OpenSSL 1.1.0f**:
```
  CPPFLAGS=-I/usr/local/include \
  LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" \
  LIBS="-ldl" \
  ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' no-comp no-zlib no-zlib-dynamic shared
  
  make
  make test
  sed -i 's# libcrypto.a##;s# libssl.a##;/INSTALL_LIBS/s#libcrypto.a##' Makefile
  make MANSUFFIX=ssl install
  #mv -v /usr/share/doc/openssl{,-1.1.0f}
  #cp -vfr doc/* /usr/share/doc/openssl-1.1.0f

  ldconfig
  ldconfig -p | grep libcrypto

  needrestart -r l
```

**zlib 1.2.11**:
```
  CPPFLAGS=-I/usr/local/include \
  LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" \
  LIBS="-ldl" \
  ./configure --shared

  make
  make install

  ldconfig
```

**Nghttp2 v1.23.1**:
```
 CPPFLAGS=-I/usr/local/include \
  LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" \
  LIBS="-ldl" \
  ./configure
  
  make
  make install
  
  ldconfig
```

**curl 7.54.1**:
```
./buildconf

  CPPFLAGS=-I/usr/local/include \
  LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" \
  LIBS="-ldl" \
  ./configure --enable-threaded-resolver --with-ssl=/usr/local/ssl --with-libssl-prefix=/usr/local/ssl --with-nghttp2 --with-zlib=/usr/local/zlib
  
  make
  make install
    
  ldconfig
```

**# curl -V**
```
curl 7.54.1 (i686-pc-linux-gnu) libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libssh2/1.4.3 nghttp2/1.23.1 librtmp/2.3
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by dertin** [comment]
Hello, I share my script in case you are useful:
https://github.com/dertin/lemp-stack-debian/blob/develop/install.sh
