### ISSUE TITLE
Build and test for Linux/ARM64 

### ISSUE THREAD

**Issue by odidev** [curl/curl#15831]
### I did this

For aarch64 platform, I have built "Curl" from source.  

   

## Steps   

Following [STEPS](https://curl.se/docs/install.html) were used for the building and installation:  

  

``` 

sudo apt update 

sudo apt install build-essential autoconf libtool libssl-dev libz-dev make cmake git wget -y 

wget https://github.com/curl/curl/releases/download/curl-7_43_0/curl-7.43.0.tar.gz 

tar -xvf curl-7.43.0.tar.gz 

cd curl-7.43.0 

./buildconf 

./configure --with-openssl 

make -j$(nproc) 

sudo make install 

```  

  

## Outcome  

To validate that the build was successful we ran version check. The version info returned matched expected value.  

  

All this information is also added to [Software Ecosystem Dashboard for Arm] (https://www.arm.com/developer-hub/ecosystem-dashboard/).  

### curl/libcurl version

curl 7.43.0 

### operating system

Ubuntu 22.04.5 LTS

**Comment by bagder** [comment]
> curl 7.43.0

9.5 years old. I propose you upgrade.
