### ISSUE TITLE
Multiple calls to curl_multi_remove_handle with same easy handle no longer returns CURLM_OK

### ISSUE THREAD

**Issue by seragh** [curl/curl#15844]
### I did this

I have some code which calls curl_multi_remove_handle on application shutdown on an easy handle that might have already been removed on successfully doing it's work. Guess the original authors intention was to make sure curl gets shutdown cleanly irrespective.

Reproducer:
```c
int main() {
    CURLM* mhandle = curl_multi_init();
    CURL* ehandle = curl_easy_init();

    curl_multi_add_handle(mhandle, ehandle);
    CURLMcode code1 = curl_multi_remove_handle(mhandle, ehandle);
    if (code1 != CURLM_OK) {
        printf("Failed first with %d\n", code1);
        return 1;
    }
    CURLMcode code2 = curl_multi_remove_handle(mhandle, ehandle);
    if (code2 != CURLM_OK) {
        printf("Failed second with %d\n", code2);
        return 1;
    }

    curl_easy_cleanup(ehandle);
    curl_multi_cleanup(mhandle);
}
```
Fails with "Failed second with 2", where in the past the second invocation returned CURLM_OK;

Bisecting points to ba235ab269080dc66e35835c829f7ac4290dbc1d introducing this change.

### I expected the following

Strictly speaking this could be considered a regression, but maybe you want to call it a legit bug fix. Let me know what your take is so I can decide how to go about it.

### curl/libcurl version

8.10+

### operating system

Linux, Debian (original reporter) and Gentoo (me)

**Comment by icing** [comment]
There can certainly be opinions about this. I think failing a remove for an already removed handle is the better way.

**Comment by jay** [comment]
In my opinion this is a bug. libcurl's return code for this situation varies depending on whether or not other easy handles are in the multi aka `multi->num_easy`:

https://github.com/curl/curl/blob/75a2079d5c28debb2eaa848ca9430f1fe0d7844c/lib/multi.c#L789-L795

I propose restoring the old behavior, see #15852.

**Comment by icing** [comment]
I change my mind. Removing an already removed handle should be ok.
