### ISSUE TITLE
1-line patch to make libcurl build in VC++ 2017

### ISSUE THREAD

**Issue by robinrowe** [curl/curl#1586]
Windows 10
LIBCURL_VERSION "7.55.0-DEV"

Simply include winsock2.h at line 378 of system.h, like so:

    #elif defined(_MSC_VER)
    #include <winsock2.h>
    #  if (_MSC_VER >= 900) && (_INTEGRAL_MAX_BITS >= 64)

Without that, VC++ error due to SOCKET unknown type.

Hope this helps.

Robin

**Comment by gvanem** [comment]
> _MSC_VER >= 900

900? Should be 1900, no?

**Comment by MarcelRaad** [comment]
@gvanem This line already exists, the addition is the include above.

@robinrowe Thanks for the patch! Could you post the full error message, please? I don't have any build problems with Visual C++ 2017.

**Comment by bagder** [comment]
Yes I'm curious too since we build fine on a large number of windows machines in the CI builds.

**Comment by bagder** [comment]
And further, why does `system.h` complain on `SOCKET`, it doesn't use it?

**Comment by bagder** [comment]
@robinrowe, can you please help us clarify this?

**Comment by bagder** [comment]
No response, closing
