### ISSUE TITLE
Compilation for ESP32 on XTENSA architecture

### ISSUE THREAD

**Issue by nkolban** [curl/curl#1598]
In the current build environment for libcurl, we find the file called:

`curl/include/curl/system.h`

contains environmental definitions.  In my environment, I wish to build on the ESP32 MCU which uses the XTENSA chip set/architecture.   GCC on this environment supplies the pre-defined macro called `__XTENSA__`.  This issue requests a change of the source in `system.h` from this:

```
#elif defined(__GNUC__)
#  if !defined(__LP64__) && (defined(__ILP32__) || \
      defined(__i386__) || defined(__ppc__) || defined(__arm__) || \
      defined(__sparc__) || defined(__mips__) || defined(__sh__))
```

and change to:

```
#elif defined(__GNUC__)
#  if !defined(__LP64__) && (defined(__ILP32__) || \
      defined(__i386__) || defined(__ppc__) || defined(__arm__) || \
      defined(__sparc__) || defined(__mips__) || defined(__sh__) || defined(__XTENSA__))
```

**Comment by jay** [comment]
does it build ok with that change, are the types in that section correct for your platform?

**Comment by bagder** [comment]
fixed in ceff21ab76f83e

**Comment by jay** [comment]
I'd still like to know if this was actually tested on that platform. That section assumes sizeof long is 4 which may not be right

**Comment by nkolban** [comment]
I had a number of ESP32 users test the suggested change and so far so good.  See:

https://github.com/nkolban/esp32-snippets/issues/18

**Comment by jay** [comment]
ok. on your platform is sizeof(long) 4 or 8

**Comment by nkolban** [comment]
On the ESP32 device, sizeof(long) evaluates to 4 bytes.

**Comment by jay** [comment]
ok. thanks for clearing that up
