### ISSUE TITLE
Retry on `Network is unreachable` (7)

### ISSUE THREAD

**Issue by drcrallen** [curl/curl#1603]
In one of our systemd units that depends on `network.target`, we had an odd scenario where the network bounced a bit on startup. This happened to have a down period when right when a `curl` command tried to fetch over http. The command failed with `Immediate connect fail for 169.254.169.254: Network is unreachable` and did NOT retry despite having retry flags set (`--max-time 10 --retry 5 --retry-delay 10`).

As far as I can tell this is because the retry mechanics at https://github.com/curl/curl/blob/curl-7_54_0/src/tool_operate.c#L1573 do not check for `CURLE_COULDNT_CONNECT`(7), even though the network being unreachable is often transient or temporary.

This is very easily reproducible by being on a laptop and disabling wireless (assuming no wired connection) and attempting a curl command with retry. Then enabling the wireless and trying again.

### I did this
Executed curl with retry flags set but with no network active. For example, turn off wireless on your laptop and do

```
$ /usr/local/Cellar/curl/7.54.0/bin/curl -v 8.8.8.8 --max-time 60 --retry 5 --retry-delay 10 --retry-max-time 30 --retry-connrefused
* Rebuilt URL to: 8.8.8.8/
*   Trying 8.8.8.8...
* TCP_NODELAY set
* Immediate connect fail for 8.8.8.8: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

### I expected the following
Retry on errors

### curl/libcurl version

```
curl 7.54.0 (x86_64-cros-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.2k zlib/1.2.11 c-ares/1.12.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

### operating system
Linux 4.9 (CoreOS)

**Comment by drcrallen** [comment]
wait, there's an explicit flag, nevermind

**Comment by drcrallen** [comment]
Actually, I take that back, https://github.com/curl/curl/blob/curl-7_54_0/src/tool_operate.c#L1583 seems to only consider connection refused, and not consider the network being unavailable. So I'm not sure the flag will work.

**Comment by bagder** [comment]
I don't consider most instances of `CURLE_COULDNT_CONNECT` to be transient. Usually that happens when the server is down, you're using the wrong port number or the wrong IP address or similar. In such cases a retry is pointless.

But I could probably agree to having `retry-connrefused` also consider "couldn't connect" as a form of refused, and thus make retry even for that condition if this option is used.

**Comment by drcrallen** [comment]
Thanks @bagder 

Looking at http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html would the following make sense to add in addition to the already present `ECONNREFUSED`?

- [ ] `ENETDOWN`
- [ ] `ENETUNREACH` 
- [ ] `ENETRESET`

**Comment by bagder** [comment]
@gnawhleinad, do you have any opinions on this, as you brought the `--retry-connrefused` option in the first place?

**Comment by gnawhleinad** [comment]
> > would the following make sense to add in addition to the already present ECONNREFUSED?
> >
> > - [ ] `ENETDOWN`
> > - [ ] `ENETUNREACH`
> > - [ ] `ENETRESET`
> 
> do you have any opinions on this, as you brought the --retry-connrefused option in the first place?

@bagder, @drcrallen, how about, instead, making it (more) consistent with `wget`'s implementation (in [`src/connect.c#L652-L661`](https://github.com/jay/wget/blob/099d8ee3da3a6eea5635581ae517035165f400a5/src/connect.c#L652-L661)) and add `ENETUNREACH` and `EHOSTUNREACH`?

**Comment by bagder** [comment]
I don't think consistency with wget is important in this regard as I really don't users expect our options to work identically. What's important is what we consider "connection refused" might be. What network errors can we consider being transient and suitable for retry when this option is used.

So @gnawhleinad suggest adding two errnos to be considered for "retry for connection refused", out of which one overlaps with @drcrallen's three new suggested errnos... Not sure where this puts us...

**Comment by jay** [comment]
> What's important is what we consider "connection refused" might be. What network errors can we consider being transient and suitable for retry when this option is used.

transient is open to interpretation. netreset could be transient but it doesn't strike me as similar to a connrefused type situation since the transfer may have already started. i think the rest could be considered connrefused

**Comment by gnawhleinad** [comment]
I think we had this conversation/idea but we could (additionally) introduce a separate flag (e.g. `--retry-oserrno`) to accept an arbitrary set of `oserrno` to be considered transient.

In any case, I'm more than happy to write a pull-request in any direction(s). Let me know how I can help!

**Comment by drcrallen** [comment]
Network unreachable solves my immediate problem. The other two were suggestive. Adopting the criteria what uses seems like a reasonable step and we can see if anyone else complains about the lack of the other error codes. 

Oserrno sounds like a good catch-all, but is not very portable. This means the suggested use should probably be "only use until there is community consensus on how to handle this kind of error." Does that sound accurate?

**Comment by wkornewald** [comment]
I've hit this issue indirectly when accessing localhost for a service that only listens on IPv4 127.0.0.1. In this case, curl also tries ::1 which is unreachable and just fails:

```
/ # curl --retry 15 --retry-connrefused --connect-timeout 4 --retry-delay 1 -v http://localhost
* Rebuilt URL to: http://localhost/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network unreachable
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network unreachable
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80: Connection refused
```

**Comment by pvgoran** [comment]
> I don't think consistency with wget is important in this regard as I really don't users expect our options to work identically.

Well, I kind of expected that curl's `--retry-connrefused` would do the same thing. Then I discovered that curl doesn't retry on "No route to host", and I was like "damn, curl can't do this... I'll have to stick with wget which I like less".

So, I don't say that curl needs to implement this option in the same way as wget does, but it would be nice to have *some* option that would allow retrying when the host is unreachable or when the network is down overall. Maybe it could be `--retry-noroute` which would handle `ENETDOWN`, `ENETUNREACH` and `EHOSTUNREACH`, maybe these error codes could be handled by `--retry-connrefused`...

**Comment by pvgoran** [comment]
How comes https://github.com/curl/curl/commit/ccd1ec7aa8a0c0da9106c9a39e0d7de531d04dfb closes this issue?.. The functionality is still not there, it's just added to the TODO, right?

**Comment by bagder** [comment]
That is what we do with issues that don't seem to be going anywhere. Explained here: https://curl.haxx.se/docs/bugs.html#Lack_of_time_interest

If anyone wants to work on this, we can reopen this issue again or create a new!

**Comment by pvgoran** [comment]
Thanks for the explanation.
