### ISSUE TITLE
CURLOPT_RESOLVE has a bug

### ISSUE THREAD

**Issue by wlfzsd** [curl/curl#1605]
Multithreading using CURLOPT_RESOLVE
If the remote IP does not respond, curl_easy_perform can easily cause permanent blocking.
Can only restart the local connection to solve
verison:
7.54.0
7.54.1
---
windows 7
visual studio 2017

**Comment by bagder** [comment]
What do you mean? If you give a hostname the wrong IP address with `CURLOPT_RESOLVE`, then libcurl will attempt to connect to that IP right? How is that a bug?

**Comment by bagder** [comment]
No response. Closing.

**Comment by wlfzsd** [comment]
Sorry, it's my code bug.
The reason is that the setting timeout is 0
