### ISSUE TITLE
libcurl: progress is printed to console when using curl_easy_perform

### ISSUE THREAD

**Issue by webmaster128** [curl/curl#1608]
### I did this

Upgraded from curl 7.53.1 to 7.54.1.

### I expected the following

My application specific integration tests downloading some websites remain passing on all platforms (Linux, macOS, Windows) without any noise on the console.

### What happened instead

After upgrading to 7.54.1, my integration tests write progress data to the console on Windows (not happening on Linux or Mac):

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
```

 * [Log using 7.54.1](https://gist.github.com/webmaster128/9f0ccf482cac4deded27cef989214a6f#file-integrationtests_curl-7-54-1): extra progress output
 * [Log using 7.54.0](https://gist.github.com/webmaster128/9f0ccf482cac4deded27cef989214a6f#file-integrationtests_curl-7-54-0): no extra progress output

Note: the connection errors in the logs are a different regression 7.53.1->7.54.0, which I'll report separately.

### curl/libcurl version

Regression bug 7.54.0 -> 7.54.1

### operating system

Windows 10, MSVS 2015, buildconf.bat/nmake/Makefile.vc

**Comment by bagder** [comment]
Can you show us a small sample program that can reproduce this? I assume you haven't set `CURLOPT_NOPROGRESS` to 0?

**Comment by webmaster128** [comment]
`CURLOPT_NOPROGRESS` is not set in this case, so the default value is used.

Making a reproducible example is not easy for me as we're using curl in a bigger build system including curlcpp and all the C++ setup (my C is very poor). But if necessary to understand this, I'll try.

**Comment by bagder** [comment]
I'm looking at [this code section](https://github.com/curl/curl/blob/master/lib/progress.c#L441-L562) which is the one outputting the internal progress meter. It should not run if the `PGRS_HIDE` bit is set, which it should be by default and only `CURLOPT_NOPROGRESS` should be able to clear that bit.

So I can't see why this happens to you!

**Comment by webmaster128** [comment]
Thanks for the feedback. This must have been a really strange miscompilation that manifested in a compiler cache. After clearing all caches, everything works fine :) Sorry for the false alarm
