### ISSUE TITLE
How to reduce memory (RAM) usage for big files?

### ISSUE THREAD

**Issue by cookiengineer** [curl/curl#1609]
I have a server running which has very limited capacities, the VPS only has around 512MB RAM available overall (so around 100 constantly blocked, which means less than 400MB available).

However, I thought that `curl` (speaking of the binary, not the library) had a flag that allowed to reduce or limit its memory usage when downloading very big files.

I could not find suggested flags for that topic in the man page, nor the interwebz (aka stackoverflow), so I'm opening this issue here.

Is there any flag available that forces curl to not use all available RAM? Because in the VPS scenario, using like 511MB of 512MB means that the server is force-shut-off by the VPS management daemon on the host system, which is obviously very bad.

### I did this

```bash
curl -SL https://github.com/Artificial-Engineering/lycheejs-runtime/releases/download/2017.06.23/lycheejs-runtime.zip; # 495MB file size
```

Outcome was the following:

```bash
root@censored:/opt/lycheejs-buildbot# curl -SL $DOWNLOAD_URL > /tmp/lycheejs/bin/runtime.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0    780      0 --:--:-- --:--:-- --:--:--   780
 83  495M   83  414M    0     0  16.1M      0  0:00:30  0:00:25  0:00:05 21.2MKilled
```

I also tried searching for buffer, MB, stream, memory, ram - no luck in neither man pages, interwebz or the `curl --help`. Identical effect when using `--no-buffer` or `-N`.

### I expected the following

curl being able to not use all available RAM, or having a stream mode that does not use more memory than the file size that is downloaded.

### curl/libcurl version

curl 7.54.1

(though all earlier versions are affected for this, I guess)

### operating system

Debian Jessie (stable), because VPS.
Same problem on Arch Linux x64 (same VPS hoster).

edit:// Not affected seems to be my local Arch machine(s), so it seems to be definitely some weird VPS config.

**Comment by bagder** [comment]
(with a debug build of curl)

```
$ export CURL_MEMDEBUG=$HOME/tmp/curlmem.log
$ ./src/curl -SL https://github.com/Artificial-Engineering/lycheejs-runtime/releases/download/2017.06.23/lycheejs-runtime.zip -o /dev/null
$ ./tests/memanalyze.pl -v $HOME/tmp/curlmem.log
Mallocs: 54
Reallocs: 15
Callocs: 24
Strdups:  46
Wcsdups:  0
Frees: 124
Allocations: 139
Maximum allocated: 179442

```

... meaning that whoever is allocating a lot of memory for you, it isn't curl directly. I suspect the SSL library that curl uses to do the HTTPS download uses more memory than this, but I can't understand why that would make it up to much more than a few megs of ram.

**Comment by cookiengineer** [comment]
Hm, maybe it's totally related to the VPS setup and not to curl itself. I will recompile curl on the VPS and try to figure out whether this keeps happening on the new versions, too - or whether it is related to some weird Debian VPS configuration of my hoster.

Thanks anyways, I now know what to do to debug it further and will report back as soon as I find out what's causing this.

**Comment by jay** [comment]
I would add [--fail](https://curl.haxx.se/docs/manpage.html#-f) to your options, not that it will help with ram. Try [-O](https://curl.haxx.se/docs/manpage.html#-O) instead of redirecting stdout to a file, maybe that has something to do with it. Also give us the curl -V

**Comment by jay** [comment]
Another thing it could be, check /tmp since you're writing there and see if it's ram. Try `> /dev/null` and `-o /dev/null` and see if there's a difference with either of those

**Comment by bagder** [comment]
I don't see a curl bug here, closing.
