### ISSUE TITLE
Rename and other quoted commands require real path

### ISSUE THREAD

**Issue by JohnDeHelian** [curl/curl#1613]
### I did this
         snprintf(command1, sizeof(command1),"rename %s.tmp %s", serverFile, serverFile);
         headerlist = curl_slist_append(headerlist, command1);
         curl_easy_setopt(curl, CURLOPT_USERPWD, userPassword );
         curl_easy_setopt(curl, CURLOPT_URL, urlString);
         curl_easy_setopt(curl, CURLOPT_UPLOAD, 1);
         /* now specify which file to upload */ 
         curl_easy_setopt(curl, CURLOPT_READDATA, myFile);
         curl_easy_setopt(curl, CURLOPT_POSTQUOTE, headerlist);
         curl_easy_setopt(curl, CURLOPT_SSH_AUTH_TYPES, CURLSSH_AUTH_PASSWORD);
         curl_easy_setopt(curl, CURLOPT_PATH_AS_IS, 1L );

Using sftp to rename file fails unless I provide the full (real) path. However I don't always know the full login path and while relative paths work for upload and download they don't work for any of the quoted commands that require a path. I noticed that for upload and download the real path is calculated.
 I suggest adding a function:
static CURLcode get_realPathname(const char **cpp, char **path, char **pwd)
That would return the real path of sshc->quote_path1 and sshc->quote_path2. Otherwise I think they are unusable unless you know the login root user path.

I tried this and it works. I'm not real familiar with open source rules but if it helps I could provide the code I created for this purpose. I also apologize in advance if the problem was already reported. But I couldn't find anything.

### curl/libcurl version
curl 7.55.0-DEV (arm-unknown-linux-gnu) libcurl/7.55.0-DEV OpenSSL/1.0.2h zlib/1.2.8 libssh2/1.7.0

[curl -V output]

**Comment by bagder** [comment]
> I tried this and it works. I'm not real familiar with open source rules but if it helps I could provide the code I created for this purpose. 

Yes please, it will certainly help! Send us the code a diff (made with `diff -u oldfile newfile`), or preferably and if if you're going for bonus points: make it a full fledged pull-request: https://help.github.com/articles/creating-a-pull-request/

**Comment by JohnDeHelian** [comment]
Thanks Daniel
I created a patch. I chose to create a new function. But it might be just as well to change the original function. Also, I only checked for leading '/' to determine where to start from to create the real path. But it might be good to include "./" and "~/".
Let me know if you need anything else.

John


On Tuesday, June 27, 2017, 4:39:09 AM EDT, Daniel Stenberg <notifications@github.com> wrote:



I tried this and it works. I'm not real familiar with open source rules but if it helps I could provide the code I created for this purpose.


Yes please, it will certainly help! Send us the code a diff (made with diff -u oldfile newfile), or preferably and if if you're going for bonus points: make it a full fledged pull-request: https://help.github.com/articles/creating-a-pull-request/

**Comment by bagder** [comment]
> Let me know if you need anything else.

I really can't tell until you show us the patch. Ideally as a pull request...

**Comment by bagder** [comment]
Fixed in #1900
