### ISSUE TITLE
typo in doc page for curl_strequal

### ISSUE THREAD

**Issue by JesseChisholm** [curl/curl#1623]
### I did this
Browsed to: https://curl.haxx.se/libcurl/c/curl_strequal.html

### I observed the following:
In the `SYNOPSIS` section, the method `curl_strnequal` is misspelled `curl_strenqual`

**Comment by bagder** [comment]
Thanks! (the site will automatically update to this fixed version in a while)

**Comment by bagder** [comment]
Interestingly, that typo had been around since commit 01f04b9a4127, March 2002...
