### ISSUE TITLE
How to use RST_STREAM with libcurl

### ISSUE THREAD

**Issue by user963** [curl/curl#1624]
Hi,
How to use libcurl library to stop an http/2 stream with RST_STREAM ?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
