### ISSUE TITLE
Improving WinSSL error messages

### ISSUE THREAD

**Issue by jeroen** [curl/curl#1626]
We are trying to move our windows bindings from openssl to winssl. This works, however the error messages are not very helpful. For example with OpenSSL we get:

```r
curl_fetch_memory('https://widget.mytastenld.com')
>> Peer certificate cannot be authenticated with given CA certificates
```

However for WinSSL we only see:

```r
curl_fetch_memory('https://widget.mytastenld.com')
>>  SSL connect error
```

The message ***SSL connect error*** is not very helpful for the user to debug what is going on. Perhaps we can get something more specific? In R we use the following to print windows error messages:

```c
formatError(GetLastError());
```

```c
const char *formatError(DWORD res){
  static char buf[1000], *p;
  FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                NULL, res,
                MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
                buf, 1000, NULL);
  p = buf+strlen(buf) -1;
  if(*p == '\n') *p = '\0';
  p = buf+strlen(buf) -1;
  if(*p == '\r') *p = '\0';
  p = buf+strlen(buf) -1;
  if(*p == '.') *p = '\0';
  return buf;
}
```

**Comment by gvanem** [comment]
Why shouldn't `Curl_sspi_strerror()` cover this case? It already calls `FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM...)`.

**Comment by jeroen** [comment]
Maybe it could? But it seems that it's not working for `Schannel` errors? All I'm seeing is "SSL connect error"...

**Comment by gvanem** [comment]
What libcurl version is this? If I test with a WinSSL/Schannel-built libcurl with:
```
curl -v https://widget.mytastenld.com
```
I do a get sensible error:
```
curl: (35) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL 
(0x80090322) - The target principal name is incorrect.
```
So it seems `FormatMessage()` is called fine.

**Comment by jeroen** [comment]
I'm writing my own bindings. Latest `libcurl`. All i'm getting back is a `CURLE_SSL_CONNECT_ERROR` which `curl_easy_strerror()` translates to *SSL connect error* . How am I supposed to translate this into a user friendly error?

**Comment by bagder** [comment]
@jeroen: with [CURLOPT_ERRORBUFFER](https://curl.haxx.se/libcurl/c/CURLOPT_ERRORBUFFER.html) ?

**Comment by jeroen** [comment]
@bagder thanks I wasn't aware of that option. Going to test if that gives me more information about failing SSL connects :)

**Comment by jeroen** [comment]
Thanks! This solved my issue.
