### ISSUE TITLE
The newest version has a compile error on ubuntu 16.04

### ISSUE THREAD

**Issue by Qchrlis** [curl/curl#1670]
### I did this
git clone https://github.com/curl/curl.git
cd curl
./buildconf
mkdir build 
cd build
../configure    // no error prompt
make -j10

### I expected the following
No error

### curl/libcurl version
The master branch,commit ID: b54e0babd74839159b0f0d34a6469f7ca327358c

[curl -V output]
  CC       libcurl_la-amigaos.lo
  CC       libcurl_la-hostasyn.lo
  CC       libcurl_la-hostip4.lo
../../lib/strerror.c: In function ‘Curl_strerror’:
../../lib/strerror.c:634:3: error: unknown type name ‘DWORD’
   DWORD old_win_err;
   ^
../../lib/strerror.c:640:17: error: implicit declaration of function ‘GetLastError’ [-Werror=implicit-function-declaration]
   old_win_err = GetLastError();
                 ^
../../lib/strerror.c:730:5: error: implicit declaration of function ‘SetLastError’ [-Werror=implicit-function-declaration]
     SetLastError(old_win_err);
     ^
cc1: some warnings being treated as errors
Makefile:1558: recipe for target 'libcurl_la-strerror.lo' failed
make[2]: *** [libcurl_la-strerror.lo] Error 1
make[2]: *** Waiting for unfinished jobs....

### operating system
ubuntu 16.04(64bit)

**Comment by asavah** [comment]
+1
Regression introduced here https://github.com/curl/curl/commit/af0216251b94e751baa47146ac9609db70793b8e

**Comment by bagder** [comment]
ping @jay

**Comment by bagder** [comment]
I think they're fixed now as of a5834e525deb6d2

**Comment by Qchrlis** [comment]
OK
