### ISSUE TITLE
Integer Overflow or Wraparound

### ISSUE THREAD

**Issue by ovidiu-benea** [curl/curl#1675]
Ran a Veracode (https://www.veracode.com) static scan of our application windows 32-bit binaries that are using libcurl.
Used the following compiler/linker flags, see "Compilation Instructions for C/C++ on Windows" here:
https://help.veracode.com/reader/4EKhlLSMHm5jC8P8j3XccQ/3Lu03OATx74TyUh~WCn8wQ
It found 1 very high security issue in libcurl:
Integer Overflow or Wraparound in: lib/multi.c line: 1030

curl/libcurl version: curl-7.53.1

Operating system: Windows 10 Pro 64-bit

Expected: No very high security issues.

**Comment by jay** [comment]
https://github.com/curl/curl/blob/curl-7_53_1/lib/multi.c#L1030
~~~c
  if(nfds || extra_nfds) {
    ufds = malloc(nfds * sizeof(struct pollfd)); /* this is L1030 */
    if(!ufds)
      return CURLM_OUT_OF_MEMORY;
  }
  nfds = 0;
~~~
I don't see that ever overflowing, it would require a count of several hundred million file descriptors

**Comment by bagder** [comment]
I'd call that a false positive and move on. It is not a "high security issue" by any means. We *could* add a check for a maximum number of additional sockets to check for, but it would be more for being paranoid than for practical reasons.
