### ISSUE TITLE
* SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

### ISSUE THREAD

**Issue by wsc770984857** [curl/curl#1679]
I set CURLOPT_SSL_VERIFYPEER 0L, CURLOPT_SSL_VERIFYHOST 0L, CURLOPT_NOSIGNAL 1L to make a https request,.
It have issue when the curl creat ssl connect successful, but the server exit, curl call SSL_shutdown Can lead to program exit, I think it is a bug.

openssl 1.0.1l

curl version 7.52.1

* SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

**Comment by jay** [comment]
I don't understand what you're saying here. Also you ignored the template. Can you give us steps to reproduce?

**Comment by bagder** [comment]
No response
