### ISSUE TITLE
Unknown SSL protocol error

### ISSUE THREAD

**Issue by Zuikkis** [curl/curl#1681]
### I did this

Actually this bug originates from my own  www page with php and libcurl. However I noticed the same bug is in the command line version of curl as well, which makes it much easier for you to debug.

The url below is publicly available from matkahuolto's web page, so I did not hide it. It is a "test" address anyway, for testing their API.

Command line:

curl https://mhhkiweb1.matkahuolto.fi/scripts101c/mhshipmentxmltesti.wsc/ovtinxml

result:
curl: (35) Unknown SSL protocol error in connection to mhhkiweb1.matkahuolto.fi:443

I tried to force protocol with --tlsv1 and other switches, but it's not helping. -2 and -3 don't work because Debian's curl is compiled without sshv2 or v3 support.

However, my home machine has slightly older version of curl, and that works ok!

### curl/libcurl version

This does not work:

curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

This works:

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

Obvious difference is between these two is OpenSSL and GnuTLS..

### operating system
Debian stable (stretch), running on Linode

**Comment by jay** [comment]
This isn't a curl bug. What is happening is the older server Microsoft-IIS/6.0 is really particular about what it accepts. You may be able to work around it by limiting the size of the ClientHello. For example if you have curl built against OpenSSL 1.0.2 you can use curl switch `--cipher` and specify just one [cipher](https://www.openssl.org/docs/man1.0.2/apps/ciphers.html#TLS-v1.0-cipher-suites). As far as I can see that server chooses TLS_RSA_WITH_3DES_EDE_CBC_SHA even though it's last on the list... so I think you'll probably have to use that. This command works for me:
~~~
# curl 7.54.0 (i386-pc-win32) libcurl/7.54.0 OpenSSL/1.0.2l nghttp2/1.23.1
curl -v --tlsv1 --ciphers DES-CBC3-SHA https://mhhkiweb1.matkahuolto.fi/scripts101c/mhshipmentxmltesti.wsc/ovtinxml
~~~
That may or may not work for you. As I said it's particular about the size of the ClientHello, so likely if you do that and your ClientHello is still over 255 bytes it won't work (mine was at 204 with just that one cipher). Use Wireshark to check the size if you still can't connect. You can read more about it here https://github.com/ssllabs/research/wiki/Long-Handshake-Intolerance

**Comment by Zuikkis** [comment]
Thanks, this was a good hint forwards. I undestand that I should maybe continue this on Debian bugreport, as this seems to be more of a problem in the debian build..

It seems Debian ships with super retarded version of openssl that doesn't have many ciphers... It does not have TLS_RSA_WITH_3DES_EDE_CBC_SHA you suggested, for example.

I created a list of ciphers with: 

openssl ciphers -v 'ALL'  

It shows 125 ciphers..

Then I created a bash script to try each cipher with curl. :) No luck, nothing worked. Interestingly though, many of the ciphers listed by openssl were not available in curl. I got three kinds of error messages depending on the cipher, here's a few for example:

CAMELLIA256-SHA:
curl: (35) Unknown SSL protocol error in connection to mhhkiweb1.matkahuolto.fi:443 

PSK-AES256-CBC-SHA384:
curl: (59) failed setting cipher list: PSK-AES256-CBC-SHA384

PSK-AES256-CBC-SHA:
curl: (35) error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available

Oh and I forgot to tell in the original message, I had this system working for maybe four years now, until recently when I upgraded the system to Debian Stretch..

**Comment by slongholio** [comment]
I was having this issue today and thought I'd offer something that helped.  We have multiple IPs, and the default IP was sending the request, which is rejected by the firewall.  This is even though I could use netcat to same IP:port and get success.  To get curl to work, I had to use the -s switch, to tell it what source IP to send from.

So add something like -s 10.244.8.80 in with the rest of your options. resolved it for me.
