### ISSUE TITLE
cUrl compilation failure in telnet.c and tftp.c

### ISSUE THREAD

**Issue by ydnath** [curl/curl#1688]
### I did this
When I built the 7.54.0 version with CURL_NO_OLDIES, there is a compilation error for 

1) https://github.com/curl/curl/blob/master/lib/telnet.c#L902
CURLE_UNKNOWN_TELNET_OPTION is defined at https://github.com/curl/curl/blob/master/include/curl/curl.h#L576 but under #ifndef CURL_NO_OLDIES

2) https://github.com/curl/curl/blob/master/lib/tftp.c#L1348
CURLE_BAD_CALLING_ORDER is defined at 
https://github.com/curl/curl/blob/master/include/curl/curl.h#L586 but under #ifndef CURL_NO_OLDIES

### I expected the following
Define CURLE_UNKNOWN_TELNET_OPTION and CURLE_BAD_CALLING_ORDER under the new enum set or reuse one of the enums defined. [I did reuse and it fixed the compilation issues]

### curl/libcurl version
7.54.0
[curl -V output]

### operating system
FreeBSD

**Comment by bagder** [comment]
I think a fix should make the code not use these return codes anymore, and probably make sure that libcurl always gets built with `NO_OLDIES` set...

**Comment by ydnath** [comment]
Thank you @bagder for the confirmation. Will submit a pull request.

**Comment by jay** [comment]
> I think a fix should make the code not use these return codes anymore, and probably make sure that libcurl always gets built with NO_OLDIES set...

The fix that just landed replaces the codes, thanks to @ydnath. If you want to build it with no oldies by default how about something like this in curl_setup
~~~diff
diff --git a/lib/curl_setup.h b/lib/curl_setup.h
index fc597d7..4a3b85c 100644
--- a/lib/curl_setup.h
+++ b/lib/curl_setup.h
@@ -22,6 +22,10 @@
  *
  ***************************************************************************/
 
+#if defined(BUILDING_LIBCURL) && !defined(CURL_NO_OLDIES)
+#define CURL_NO_OLDIES
+#endif
+
 /*
  * Define WIN32 when build target is Win32 API
  */
~~~

**Comment by bagder** [comment]
@jay, I'd 👍 such a PR! =)
