### ISSUE TITLE
SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 

### ISSUE THREAD

**Issue by gnanagurun** [curl/curl#1689]
### I did this
When my device posting the data to server via https, i'm seeing this below error by curl frequently. Libcurl is configured with OpenSSL. On seeing the errno 104, i can understand that the connection is getting closed by peer when SSL read happens. I googled it to understand what condition the server would close the connection but couldn't get. Can you help me to resolve this issue

**"SSL read: error:00000000:lib(0):func(0):reason(0), errno 104"**

### curl/libcurl version
Libcurl version : 7.52.1
OpenSSL version: 1.1.0d
[curl -V output]

### operating system
Linux

**Comment by bagder** [comment]
To me, this sounds like the server is prematurely closing the connection. Since the server isn't supposed to do this, it isn't easy to tell why it does this.

**Comment by bagder** [comment]
No response, and this is probably a server issue (even if the curl error message for this could use improvements).
