### ISSUE TITLE
--data-urlencode needs examples

### ISSUE THREAD

**Issue by jidanni** [curl/curl#1690]
On the man page --data-urlencode <data> needs examples.
E.g.. the user wants -d 'A=B&C=D'  where ABCD are all CJK characters, to get properly encoded, without disturbing any of the =s and &s.
The user cannot figure out what to do.

**Comment by jidanni** [comment]
Or else the user will just have to first run the string through
perl -C -MURI::Escape -nwle 'print uri_escape_utf8( $_,   "\x00-\x1f\x7f-\xff" );')

**Comment by bagder** [comment]
...that solution then of course assumes that you provide the bytes using UTF8, which isn't a given in all circumstances.

If you can think of a way to explain this, please tell us. I think it is rather tricky...

**Comment by jidanni** [comment]
Forget about explaining it!
Just explain it via examples!
E.g., the common case where the user has
-d 'A=B&C=D', and only B and D need to be %encoded... and as UTF-8 characters too.
As far as how to write the examples... well unfortunately I have no idea
of what the man page is saying either, so well, probably only you would know.

**Comment by bagder** [comment]
The documentation for `--data`  that it refers to, already explains how using the option multiple times will make each separate use get concatenated with a `&` in between so in my view that is already explained and documented so no, I don't know what's missing. Should we perhaps repeat that information in the data-urlencode section ?

`--data-urlencode A=B --data-urlencode C=D`

**Comment by jidanni** [comment]
Ah thanks OK I now think I see what is going on.

Perhaps the 80+ lines which describing the --data family of options can
be compressed:

DATA FAMILY OF OPTIONS
   GENERAL RULES
   ....
   SPECIFIC RULES FOR EACH OPTION
   ....

This would also enable you to remove most of the back and forth "See
Also"s amongst them.

Or at least put the important
       -d, --data <data>
section before all the rest of the --data-* sections.

P.S., after

              name=content
                     This  will make curl URL-encode the content part and pass
                     that on. Note that the name part is expected to  be  URL-
                     encoded already.

please add

                     No, currently curl has no way to URL-encode the
                     name portion. You will just have to do that
                     yourself if really required.

**Comment by bagder** [comment]
Each command line option is documented individually so there's no good way for us to put a summary for a selection of options - that's why most of them refer to the `--data` option as that has the lengthiest description of the set. Also, the options are documented in a strict alphabetical order so changing the order is... tricky.

**Comment by bagder** [comment]
The [URL encoding](https://ec.haxx.se/http-post.html#url-encoding) chapter in the Everything curl book has a few more examples. To me, that's a better place to expand with more examples.

**Comment by bagder** [comment]
Let's be happy with that.
