### ISSUE TITLE
DarwinSSL + deflate error

### ISSUE THREAD

**Issue by jeroen** [curl/curl#1691]
We are experiencing a problem with a server that gives SSL errors only on DarwinSSL and WinSSL and only when the client supports compression. Somehow the problem does not appear when either gzip is disabled or when using an openssl build of libcurl. 

The problem appears after running this command **several times in a row**:

```sh
curl -v -H 'Accept-Encoding: gzip,deflate' https://digital.library.unt.edu 
```
```
{ [3741 bytes data]
* SSLRead() return error -9806
* Curl_http_done: called premature == 1
100 13997    0 13997    0     0  17288      0 --:--:-- --:--:-- --:--:-- 17280
* Closing connection 0
curl: (56) SSLRead() return error -9806
```

Is this a bug in libcurl or a malconfigured server?

**Comment by nickzman** [comment]
Misconfigured server. Error -9806 means the server threw an error and closed the connection.

**Comment by misea** [comment]
Thank you. Are there known differences between openssl and  DarwinSSL/WinSSL that would cause a server to throw on one vs the other? (Obviously any difference in raw request data could cause this, but wondering if this is a known issue with certain servers. I don't know anything about this particular server).

**Comment by nickzman** [comment]
I've never heard of this happening before on any server. You could check to see if it's reproducible in Safari, and if so, you can file a bug with Apple.

**Comment by misea** [comment]
No problems in Safari. Even used javascript fetch API from within a web page so I could control the headers being sent. Got gzip content back with no errors.

**Comment by jay** [comment]
> Are there known differences between openssl and DarwinSSL/WinSSL that would cause a server to throw on one vs the other?

schannel backend by default libcurl does a close notify check and afaict openssl no. here you have http 1.0 response, no content length so libcurl just keeps reading until it closes, which the server does without close notify. if you turn on verbose you'll see this:
~~~
* schannel: server closed abruptly (missing close_notify)
~~~
recv error is set [here](https://github.com/curl/curl/blob/curl-7_54_1/lib/vtls/schannel.c#L1347-L1366). it's possible darwinssl/securetransport may have some similar check, either in libcurl or in the os
