### ISSUE TITLE
Unable to use OpenSSL 1.1.1 devel tls 1.3 draft 18 with curl 7.54.1

### ISSUE THREAD

**Issue by iz8mbw** [curl/curl#1695]
Hi.
I want to build curl using "OpenSSL 1.1.1 devel tls 1.3 draft 18" (shared libraries) to use it with TLSv1.3.

In my Linux system I have "OpenSSL 1.1.0f" already built and the libraries (.so) are installed in "/opt/ssl/lib" (/etc/ld.so.conf point also here, so them are "system" shared libraries)

In my Linux system I have "OpenSSL 1.1.1 devel tls 1.3 draft 18" already built and the libraries (.so) are installed in "/opt/ssldevel/lib"

If I try to build curl 7.54.1 using "OpenSSL 1.1.1 devel tls 1.3 draft 18" to benefit of TLS 1.3, during configure I see:

```
configure: Added /opt/ssldevel/lib to LD_LIBRARY_PATH
checking for OpenSSL headers version... unknown - 0x10101000L
checking for OpenSSL library version... 1.1.0
checking for OpenSSL headers and library versions matching... no
configure: WARNING: OpenSSL headers and library versions do not match.
```

This is the configure command:

```
./configure --with-cc-opt="-I/opt/ssldevel/include" --with-ld-opt="-L/opt/ssldevel/lib -ldl -Wl,-rpath,/opt/ssldevel/lib" -enable-shared=zlib --with-ssl=/opt/ssldevel --with-nghttp2 --with-zlib --enable-debug --with-gssapi
```

It seems that configure is going to use "OpenSSL 1.1.1 devel tls 1.3 draft 18" for headers, but it's using "OpenSSL 1.1.0f" for libraries...

In fact, after configure and after make:

```
curl 7.54.1 (armv7l-unknown-linux-gnueabihf) libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libssh2/1.4.2 nghttp2/1.24.0 librtmp/2.3
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug TrackMemory Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

So curl is going to use "OpenSSL 1.1.0f" and not "OpenSSL 1.1.1 devel" also if in the "configure" I setted "--with-cc-opt="-I/opt/ssldevel/include" --with-ld-opt="-L/opt/ssldevel/lib -ldl -Wl,-rpath,/opt/ssldevel/lib" -enable-shared=zlib --with-ssl=/opt/ssldevel".
Where I wrong?

Thanks

**Comment by bagder** [comment]
`config.log` is usually your friend to detect why the configure check fails. Many developers build curl with openssl from master regularly so this is known to work if you just tell configure properly how to act. Note that building with static OpenSSL libs more tricky than with shared ones.

**Comment by iz8mbw** [comment]
If I build curl with "OpenSSL 1.1.0f" shared libraries it works, I have the problem only with "OpenSSL 1.1.1 devel tls 1.3 draft 18".

I need shared libraries because the same "OpenSSL 1.1.1 devel tls 1.3 draft 18" shared libraries are used for nginx (without problems).

Here: https://www.pastefs.com/pid/22363 the "config.log" file.

I'm not an expert to read the "config.log" file, but I can see the same problem: WARNING: OpenSSL headers and library versions do not match.

Is there a possbility to skip this warning and let curl to use the shared libraries available in the path specified in the configure?

**Comment by bagder** [comment]
> It seems the problem already was detected form other users

The OpenSSL warning configure shows you is just a warning, it doesn't make configure behave differently. Removing that won't help. It's a sign of a problem, it's not the actual problem.

In your case it *probably* triggers becasue `-I/usr/local/include` is prepended to your CFLAGS  so configure finds the wrong openssl headers? (But I can't spot why that path is added)

**Comment by bagder** [comment]
(that path comes from zlib's pkg-config)

**Comment by iz8mbw** [comment]
OK so if the warning is only a warning for now we can skip it.

So focus on the problem: just to summarise the problem is that `configure` of curl will NOT use the specified version on OpenSSL specified/forced via `rpath` in the `configure` (`./configure --with-cc-opt="-I/opt/ssldevel/include" --with-ld-opt="-L/opt/ssldevel/lib -ldl -Wl,-rpath,/opt/ssldevel/lib" -enable-shared=zlib --with-ssl=/opt/ssldevel --with-nghttp2 --with-zlib --enable-debug --with-gssapi`).

In `/usr/local/lib` I don't have any OpenSSL library, I have other library such as `zlib`, `libnghttp2` and `libidn2` (but this does not matter).

So, if I configure curl to use OpenSSL shared libraries available on `/opt/ssldevel/lib` why it use, anyway, the OpenSSL specified in `/etc/ld.so.conf`? This is the problem.

For your info this is my `/etc/ld.so.conf`

``` 
root@server:~# cat /etc/ld.so.conf
/opt/ssl/lib
/usr/local/lib
include `/etc/ld.so.conf`.d/*.conf
```

As already saw, curl uses always the shared libraries available/specified in `/etc/ld.so.conf`.
If I modify the `/etc/ld.so.conf` with a new path for libraries and then run `ldconfig`, the new `ldd` on the same curl binary will show the new path for shared library...
This is the problem.

**Comment by bagder** [comment]
> if I configure curl to use OpenSSL shared libraries available on /opt/ssldevel/lib why it use, anyway, the OpenSSL specified in /etc/ld.so.conf?

Mabye because the configure script doesn't support `--with-ld-opt`? The `--help` output doesn't say it does. It doesn't support `--with-cc-opt` either. Neither of them seem to be very widely used nor standard configure options.

You could set `LDFLAGS` and `CFLAGS` though, which I suppose could help accomplish the same thing.

The curo configure script doesn't do anything special or magic when it creates the library. You just need to tell it correctly what to do.

**Comment by iz8mbw** [comment]
Sorry for using `--with-ld-opt` and `--with-cc-opt`.

If I try to set `LDFLAGS=-L/opt/ssldevel/lib` and `CPPFLAGS=-I/opt/ssldevel/include` curl anyway will go to use the system OpenSSL library...

I found this way on Internet and it works: 
`LDFLAGS="-L/opt/ssldevel/lib -Xlinker -rpath=/opt/ssldevel/lib"` and `CPPFLAGS="-I/opt/ssldevel/include"`

So now:
```
root@server:~# curl -V
curl 7.54.1 (armv7l-unknown-linux-gnueabihf) libcurl/7.54.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.0 libssh2/1.4.2 nghttp2/1.24.0 librtmp/2.3
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug TrackMemory IDN Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

**Comment by iz8mbw** [comment]
Thanks for your support and thanks for this fantastic tool!!
