### ISSUE TITLE
 Centos web panel, curl bug

### ISSUE THREAD

**Issue by jedixraja** [curl/curl#1697]
i gues am having a curl bug

http://vids.realwaparz.net/getvideo.php?videoid=ciz79BppuO4&type=Download

this link shows download links on webuzo panel but doesnt show on centos web panel, i want to know why? i have enabled curl and every other thing, but its still not showing, what needs to be done, this is my phpinfo file  http://vids.realwaparz.net/phpinfo.php , thanks

**Comment by bagder** [comment]
Can you please elaborate on how we can reproduce this problem? You didn't fill in the info we ask for and didn't provide it using any other means.

**Comment by jedixraja** [comment]
it suppose to curl youtube download links, but its not working, i think curlget() is not working for my cpanel, it works well when am on webuzo web panel but not when i am on centos web panel nor vesta cp

**Comment by bagder** [comment]
Sorry, but I'll say it again: please explain how we can reproduce the problem or you need to elaborate with extensive details.

**Comment by bagder** [comment]
Lack of information.
