### ISSUE TITLE
GetTickCount64 / GetTickCount function issue on winxp (NT < 0x600) 

### ISSUE THREAD

**Issue by cuteUser** [curl/curl#1698]
### I did this
I tried to build 0x86 Windows XP compatible  on my Win 10 , Visualstudio 2015.
But On my Win XP, it failed and printed this error msg "GetTickCount64" is not located in Kernel32.dll.
**Then I checked libcurl C source file, I found /lib/timeval.c has mistake that I think.**
Code below is line 35 ~44 in /lib/timeval.c
```
#if !defined(_WIN32_WINNT) || !defined(_WIN32_WINNT_VISTA) || \
    (_WIN32_WINNT < _WIN32_WINNT_VISTA)
  DWORD milliseconds = GetTickCount();
  now.tv_sec = milliseconds / 1000;
  now.tv_usec = (milliseconds % 1000) * 1000;
#else
  ULONGLONG milliseconds = GetTickCount64();
  now.tv_sec = (long) (milliseconds / 1000);
  now.tv_usec = (long) (milliseconds % 1000) * 1000;
#endif
```
**I think this logical operator makes all windows library to use GetTickCount64 rather than GetTickCount.** 
I modified code like below and successed for my goal. 
`defined(_WIN32_WINNT) || defined(_WIN32_WINNT_VISTA) ||   (_WIN32_WINNT < _WIN32_WINNT_VISTA)`

### curl/libcurl version
7.54.0

### operating system
Windows 10

**Comment by MarcelRaad** [comment]
Thanks for the report! However, I don't see a bug in the existing logic. Only if targeting at least Windows Vista is explicitly requested or a higher default from the Windows SDK is used, GetTickCount64 is used. The change would make GetTickCount64 never get used.

What have you set `_WIN32_WINNT` to? What build system are you using (Visual Studio projects, winbuild/nmake, CMake)?

**Comment by cuteUser** [comment]
Sorry for mistake. below is my code
defined(_WIN32_WINNT) && defined(_WIN32_WINNT_VISTA) &&
 (_WIN32_WINNT < _WIN32_WINNT_VISTA) 

In original code, Because of ** !define (_WIN32_WINNT)||   **, it makes condition false against all Windows Versions. So all cases use GetTickCount64(). Check this logic one more time please.

**Comment by jay** [comment]
i don't understand what you are saying. !defined(_WIN32_WINNT) and it uses GetTickCount. That's what it's supposed to do. Can you try again to explain the problem please?

**Comment by naprelsky** [comment]
I have some problem. I'm using VS 2013 on Windows 10 for build curl+openssl static libs. If I build with command "nmake /f Makefile.vc mode=static VC=12 DEBUG=no MACHINE=x64 WITH_SSL=static ENABLE_IPV6=no WITH_DEVEL=%OPENSSL_SRC_64% RTLIBCFG=static", then in output libcurl.lib there is GetTickCount64 function, and this lib don't work on Windows XP.

Can you add in MakefileBuild.vc parameter "CUSTOMFLAGS" or something else in "CFLAGS = $(CFLAGS) $(CUSTOMFLAGS) /I"$(DEVEL_INCLUDE)".

Then can build with command: "nmake /f Makefile.vc mode=static VC=12 DEBUG=no MACHINE=x64 WITH_SSL=static ENABLE_IPV6=no RTLIBCFG=static CUSTOMFLAGS="/D_USING_V110_SDK71_ /D_WIN32_WINNT=0x0501"

**Comment by cuteUser** [comment]
Dear jay
Sorry It's my fault. When I compiled with VS14 nmake, there's GetTickCount64 in the lib. So I doubt that logic upper. I found the problem which is exactly like what naprelsky did. Because of Windows 10, WIN32_WINNT is defined as 0xA00. After  defining WIN32_WINNT in the curl src, I could build lib for win xp. I didn't know about I can customize some constant in nmake. I'm sorry for this issue.

**Comment by naprelsky** [comment]
For me changing curl src isn't good choice because I build libs through batch file (downloading, extracting, building ect).

**Comment by cuteUser** [comment]
Your choice is better. In my case, I didn't know how to set constants in nmake option. I learned a lot! thank you naprelsky and jay. Maybe this issue doesn't need to carry on.

**Comment by jay** [comment]
> Can you add in MakefileBuild.vc parameter "CUSTOMFLAGS" or something else in "CFLAGS = $(CFLAGS) $(CUSTOMFLAGS) /I"$(DEVEL_INCLUDE)".
>
> Then can build with command: "nmake /f Makefile.vc mode=static VC=12 DEBUG=no MACHINE=x64 WITH_SSL=static ENABLE_IPV6=no RTLIBCFG=static CUSTOMFLAGS="/D_USING_V110_SDK71_ /D_WIN32_WINNT=0x0501"

@naprelsky try this
nmake /E CC="cl /D_USING_V110_SDK71_ /D_WIN32_WINNT=0x0501" /f Makefile.vc ...

**Comment by naprelsky** [comment]
@jay, thanks a lot for the advice, it's working
