### ISSUE TITLE
Wrong order of entries in DT_RPATH/DT_RUNPATH of binary so file 

### ISSUE THREAD

**Issue by chros73** [curl/curl#1701]
I saw something similar on [known bugs](https://curl.haxx.se/docs/knownbugs.html#configure_finding_libs_in_wrong) page, and it can be the cause of this.

Imagine the following small part of a building script that adds relative `rpath` linking:
```sh
export CARES_VERSION=1.13.0
export CURL_VERSION=7.54.1

export LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -L$DSTD/lib${LDFLAGS:+ }${LDFLAGS}"

echo "======================   c-ares   =========================="
[[ -e "c-ares-$CARES_VERSION.tar.gz" ]] || wget -q http://c-ares.haxx.se/download/c-ares-$CARES_VERSION.tar.gz
tar zxf c-ares-$CARES_VERSION.tar.gz

( cd ${SRCD}/c-ares-$CARES_VERSION \
  && ./configure \
  && make -j4 \
  && make DESTDIR=$DSTD prefix= install )

sed -i -e s:/usr/local:$DSTD: $DSTD/lib/pkgconfig/*.pc $DSTD/lib/*.la

echo "======================   curl   =========================="
[[ -e "curl-$CURL_VERSION.tar.gz" ]] || wget -q http://curl.haxx.se/download/curl-$CURL_VERSION.tar.gz
tar zxf curl-$CURL_VERSION.tar.gz

( cd ${SRCD}/curl-$CURL_VERSION \
  && ./configure --enable-ares \
  && make -j4 \
  && make DESTDIR=$DSTD prefix= install )

sed -i -e s:/usr/local:$DSTD: $DSTD/lib/pkgconfig/*.pc $DSTD/lib/*.la
```
#### Result

```sh
$ objdump -p libcurl.so | grep PATH
  RPATH                /home/user1/lib/rtorrent2/lib:$ORIGIN/../lib
```

#### Expected result

```sh
$ objdump -p libcurl.so | grep PATH
  RPATH                $ORIGIN/../lib:/home/user1/lib/rtorrent2/lib
```

The problem is with the current implementation is that the full path is used first to find any library (e.g. libcares.so): if that directory exists and the given so file in it then that one will be used instead of the relative path (other packages handles this well, e.g. rtorrent).

If you know a quick solution for this problem I'd be thankful.
More complete story (with links for the full script) is [here](https://stackoverflow.com/questions/45282061/how-when-where-to-set-script-variables-of-libtool-e-g-hardcode-minus-l).

#### Operating systems

Probably all of them, tested on: Ubuntu 14.04, Ubuntu 17.04, Debian 9.

Thanks!

**Comment by bagder** [comment]
(This is obviously not the the known issue linked to, as that is about finding *other* libs in the same directory you point out to find libs earlier in the script.)

> The problem is with the current implementation is that the full path is used first to find any library (e.g. libcares.so)

I don't understand what you're saying the script does wrong. When you set `LDFLAGS` manually, you override the configure's detection logic so you basically tell it what to use and how to link.

Can you elaborate exactly what you say the configure script in your script does that it shouldn't when you use `--enable-ares`? If you want to link with c-ares from a specific prefix, why not pass that to the option?

**Comment by chros73** [comment]
Thanks for your reply!

> When you set LDFLAGS manually, you override the configure's detection logic so you basically tell it what to use and how to link.

That's correct.

> that it shouldn't when you use --enable-ares? 

It's not related to the usage of that option, it happens without it. (I just wanted to show you a real world example when it's not right.)

> I don't understand what you're saying ...
> Can you elaborate exactly what you say the configure script in your script does...

The problem relates to relative rpath linking. Using this LDFLAGS:
- `export LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -L$DSTD/lib${LDFLAGS:+ }${LDFLAGS}"`
- `-Wl,-rpath,'$ORIGIN/../lib'` specifies relative rpath.

And rpath/runpath works at runtime similarly as `PATH` env var:
- first path is served first
  - and that's the problem with the order of the generated rpath entries

Feel free to ask more if it's still unclear.
Thanks

**Comment by bagder** [comment]
Are you saying that curl's configure script is rearranging the LDFLAGS order from the one you pass in? Or how does your specified order change by the time the library is eventually linked?

**Comment by chros73** [comment]
Almost, actually the specified order is irrelevant, I tried out both ways, e.g.:
`export LDFLAGS="-L$DSTD/lib -Wl,-rpath,'\$\$ORIGIN/../lib'${LDFLAGS:+ }${LDFLAGS}"`

The strange thing is that [rtorrent](https://github.com/rakshasa/rtorrent) puts them in the right order, no matter what order was specified. It also has just couple of build related files (libtool takes care the rest of it):
- autogen.sh , configure.ac , Makefile.am , and m4 macros in scripts dir

Honestly, if I could just get rid of the `-L` specified absolute path from `RPATH`/`RUNPATH`, that would solve my problem.

**Comment by bagder** [comment]
ok, but neither curl's configure nor makefile rearranges the order of the LDFLAGS, so I'm inclined to say that if this is truly a bug, it is either in libtool or in ld.

If you run 'make V=1' and investigate the actual final linker command line, is that wrong according to you? If so, can you figure out what made it wrong?

**Comment by chros73** [comment]
Sorry for the late reply, I didn't have time to play with it earlier.

> I'm inclined to say that if this is truly a bug, it is either in libtool or in ld

I don't know either, honestly.  What made me think of that is (as I mentioned above) rtorrent with it's minimalistic files produced the same thing in the right order.

> f you run 'make V=1' and investigate the actual final linker command line

I don't see anything interesting in it that relates to ordering:
```
/bin/bash ../libtool --tag=CC --mode=link gcc -O2 -Wno-system-headers -Wl,-rpath,'$ORIGIN/../lib' -L/home/user1/curlbuild/compiled/lib ......
libtool: link: gcc -Werror-implicit-function-declaration -O2 -Wno-system-headers -Wl,-rpath -Wl,\$ORIGIN/../lib ...... -L/home/user1/curlbuild/compiled/lib ../lib/.libs/libcurl.so -lssl -lcrypto -lz -Wl,-rpath -Wl,/home/user1/curlbuild/compiled/lib
```

Here's a small, slightly modified version of the original script but fully working, with which you can also produce the same thing:
- note that I removed the `-L` from `LDFLAGS`, and we still get the same result

`buildcurl.sh`
```bash
#! /usr/bin/env bash

export CARES_VERSION=1.13.0
export CURL_VERSION=7.54.1

export SRCD=$(cd $(dirname $0) && pwd)
export DTSD=$SRCD/compiled
mkdir -p $DTSD

export LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib'${LDFLAGS:+ }${LDFLAGS}"

export MAKE_OPTS=V=1

echo "======================   c-ares   =========================="
[[ -e "c-ares-$CARES_VERSION.tar.gz" ]] || wget -q http://c-ares.haxx.se/download/c-ares-$CARES_VERSION.tar.gz
tar zxf c-ares-$CARES_VERSION.tar.gz

( cd ${SRCD}/c-ares-$CARES_VERSION \
  && ./configure --prefix=$DTSD \
  && make $MAKE_OPTS \
  && make $MAKE_OPTS install )

echo "======================   curl   =========================="
[[ -e "curl-$CURL_VERSION.tar.gz" ]] || wget -q http://curl.haxx.se/download/curl-$CURL_VERSION.tar.gz
tar zxf curl-$CURL_VERSION.tar.gz

( cd ${SRCD}/curl-$CURL_VERSION \
  && ./configure --prefix=$DTSD --enable-ares=$DTSD \
  && make $MAKE_OPTS  \
  && make $MAKE_OPTS install )

echo "====== diag ======"
objdump -p $DTSD/lib/libcares.so | grep PATH
objdump -p $DTSD/lib/libcurl.so | grep PATH
ldd $DTSD/lib/libcurl.so
```

Thanks

**Comment by bagder** [comment]
I still claim this is a behavior imposed by libtool and not curl's build files or configure files. If you have additional detail pointing to it *not* being the case, then please present such and we can reopen again.
