### ISSUE TITLE
Request (outbound) headers not shown with -i option

### ISSUE THREAD

**Issue by olesteban** [curl/curl#1704]
### Sample request:
```
C:>curl.exe -i https://ec.haxx.se/http-requests.html -s
HTTP/2 200
age: 619
content-encoding: identity
content-type: text/html
...
````
If I use the --trace-ascii option, in the file I can find
```
=> Send header, 90 bytes (0x5a)
0000: GET /http-requests.html HTTP/2
0020: Host: ec.haxx.se
0032: User-Agent: curl/7.54.1
004b: Accept: */*
0058:
```
### Expected
I expected these lines also in stdout. I'd say they appear in linux (I don't have a linux machine right now to say). To be honest, my idea of this behavior in linux didn't include httpS, so this could be the cause.

Well, using plain http in Windows results in the same output:
```
C:>curl.exe -i http://www.curlpp.org/  -s
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: text/html; charset=utf-8
Last-Modified: Fri, 05 May 2017 05:25:58 GMT
...
```

### curl/libcurl version
```
C:>curl.exe -V
curl 7.54.1 (x86_64-pc-win32) libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.24.0
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy
```
### operating system
Windows 10 Pro v1607 64 bits

**Comment by bagder** [comment]
`-i` is for showing the response headers to the same output destination as the body. It doesn't not mean you'll see the outgoing request. To see the request. use `-v` or one of the `--trace*` options.

**Comment by jay** [comment]
What do you think about changing the doc to: Include the _response_ HTTP-header in the output.

**Comment by bagder** [comment]
Thanks, both of you!
