### ISSUE TITLE
curl: (56) GnuTLS recv error (-54): Error in the pull function.

### ISSUE THREAD

**Issue by loretoparisi** [curl/curl#1707]
### I did this
curl https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.zip -o wiki.en.zip
### I expected the following
no error, `wiki.en.zip` file saved.
### curl/libcurl version

```
$ curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```
### operating system
```
$ lsb_release -s -d
Ubuntu 16.04.2 LTS
```

### notes
`wget` works. `date` is correct.

**Comment by jay** [comment]
Is this reproducible with just curl? It could be a temporary network problem.

**Comment by loretoparisi** [comment]
It happens every time for the same command/machine/network. It depends on that machine, since on the same subnet it works on a different macOS machine.
At 2-3% of download it returns with error for every execution.Which additional tests can I do?
	_____________________________

**Comment by jay** [comment]
It looks like a temporary network problem. Using that same packaged version in Ubuntu 16 I downloaded 20% in about an hour and the speed was all over the place. It is far too slow for me to complete the whole thing.

**Comment by bagder** [comment]
Try adding `-v` to the command and see if that tells something more. If the transfer ends before the 9877MB are transferred (it showed me `Content-Length: 10356881301`), it really should output an error.

Like @jay, I cannot reproduce a problem with this URL, although I built the current git master and ran the command line tool using **GnuTLS/3.5.14**. I got the whole file downloaded (in my first and only attempt to get the whole thing) in 11m03, at about a 14.8 megabytes/second transfer rate on average.

I tried from another machine with **curl 7.47.0 (i586-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.5.5** and it also managed to download the first part of the file just fine. I didn't bother to wait for the whole file there.

**Comment by loretoparisi** [comment]
@bagder Thank you for the tests and details:

```
ubuntu@ubuntu-docker:~$ curl -v https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.zip -o wiki.en.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.219.20.57...
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Connected to s3-us-west-1.amazonaws.com (52.219.20.57) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.s3-us-west-1.amazonaws.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=Washington,L=Seattle,O=Amazon.com Inc.,CN=*.s3-us-west-1.amazonaws.com
* 	 start date: Mon, 18 Jul 2016 00:00:00 GMT
* 	 expire date: Thu, 26 Oct 2017 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert Baltimore CA-2 G2
* 	 compression: NULL
* ALPN, server did not agree to a protocol
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0> GET /fasttext-vectors/wiki.en.zip HTTP/1.1
> Host: s3-us-west-1.amazonaws.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-amz-id-2: FH7SGJ4iHgBhxVz6OcsbC0nQdbPDY3J2k1pgT7Fc/UJWLjEjAKAqhOhPLi/2/d2Wj2KIgBvHq2I=
< x-amz-request-id: EA7F3707E34C72B8
< Date: Fri, 28 Jul 2017 08:44:41 GMT
< Last-Modified: Tue, 06 Jun 2017 22:33:00 GMT
< ETag: "285a926643e22fbcbb4615c4f2175ae4-1235"
< Accept-Ranges: bytes
< Content-Type: application/zip
< Content-Length: 10356881301
< Server: AmazonS3
< 
{ [16360 bytes data]
 26 9877M   26 2652M    0     0  3368k      0  0:50:02  0:13:26  0:36:36     0* GnuTLS recv error (-54): Error in the pull function.
 26 9877M   26 2652M    0     0  3366k      0  0:50:04  0:13:26  0:36:38     0
* Closing connection 0
curl: (56) GnuTLS recv error (-54): Error in the pull function.
```

**Comment by bagder** [comment]
That seems to be an error detected by and returned from a GnuTLS function. I've googled around for it a bit but it didn't give me any clear answers. I think it hints to a problem with that GnuTLS version, possibly in combination with something in your network/environment that makes it trigger for you. It's hard to know better without a way to reproduce it...

**Comment by loretoparisi** [comment]
@bagder agreed, there is no evidence that is nothing than a network/env problem, so closing this.

**Comment by KelseyDH** [comment]
I'm getting a similar problem and frustratingly can't find any good advice on how to fix or resolve this.  Surely something is wrong with `curl` if so many users are shooting themselves in the foot with this?!

**Comment by jay** [comment]
> Surely something is wrong with curl if so many users are shooting themselves in the foot with this?!

There's never been any information to indicate that error is anything other than a network problem, not a curl problem. If you have a public URL that you can consistently fetch using wget w/gnutls but not curl w/gnutls then open a new issue and we will try to reproduce.

**Comment by DavidPerezIngeniero** [comment]
I get this error when doing:
```
curl -v https://google.es/
```

**Comment by bagder** [comment]
@DavidPerezIngeniero: this is an old closed issue that wasn't a real curl problem. If you can reproduce this problem with a modern curl version, then please file a new issue.
