### ISSUE TITLE
FTP Bug: Curl sends "CWD /" despite CURLFTPMETHOD_NOCWD

### ISSUE THREAD

**Issue by PeterLamare** [curl/curl#1718]
Reproduce:
Set CURLFTPMETHOD_NOCWD and access different URLs reusing the same easy handle.

Consequence:
Killing the performance gain of reusing an easy handle by needless CWD round trips.

Fix:
The bug seems to be in src/lib/ftp.c ftp_parse_url_path():
it compares "ftpc->prevpath" with "data->state.path", and sets "ftpc->cwddone = TRUE" if equal.
This is obviously incorrect for CURLFTPMETHOD_NOCWD where the working directory is not set to state.path, instead it should compare "ftpc->prevpath" against ""

-Lama

**Comment by bagder** [comment]
I think the condition needs an exception for `CURLFTPMETHOD_NOCWD`, so that the code also handles the case when the method is actually changed between two requests.
