### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by samwise** [curl/curl#1724]
### I did this
build curl statically on windows with:
nmake /f Makefile.vc mode=static ENABLE_SSPI=no ENABLE_IPV6=no ENABLE_ID=no ENABLE_WIN_SSL=yes DEBUG=no MACHINE=x64

### I expected the following
The build to work

### curl/libcurl version
master 

### operating system
windows server 2016

### failure
NMAKE : fatal error U1073: don't know how to make '..\src\tool_hugehelp.c'

Note that there is no src\tool_hugehelp.c , but there is a src\tool_hugehelp.c.cvs with dummy content

**Comment by jay** [comment]
As stated in [GIT-INFO](https://github.com/curl/curl/blob/master/GIT-INFO) run buildconf.bat to generate src/tool_hugehelp.c

**Comment by samwise** [comment]
Thanks, perhaps a pointer to that from the windows build instructions is in order?

**Comment by bagder** [comment]
good idea @samwise, added in 6f6cfc90bef1fa5
