### ISSUE TITLE
Openvms issue with easy.c 

### ISSUE THREAD

**Issue by johnleal** [curl/curl#1726]
### curl/libcurl version - 7_53_1

[curl -V output]

  38059 struct Curl_easy *curl_easy_init(void)
                ..................1
%CC-E-NOTCOMPAT, (1) In this declaration, the type of "curl_easy_init" is not compatible with the type of a previous declaration of "curl_easy_init" at line number 28 in 7_53_1.INCLUDE.CURL]EASY.H;3.

**Comment by bagder** [comment]
Why does it complain on that line? And why aren't you building the latest version instead?

**Comment by johnleal** [comment]
I am going to just that

**Comment by bagder** [comment]
Today the OpenVMS packages on the download page were updated to 7.55.1, indicating that it does compile for some on this platform.

**Comment by johnleal** [comment]
Thank you.
