### ISSUE TITLE
Support for compression in SCP/SFTP via libssh2

### ISSUE THREAD

**Issue by vszakats** [curl/curl#1732]
It'd be great to have a way to enable compression for SCP/SFTP. AFAICS the required low-level logic is already implemented as part of `libssh2` (via `LIBSSH2_FLAG_COMPRESS` [`libssh2_session_flag()`](https://www.libssh2.org/libssh2_session_flag.html) option), but currently it's never enabled by `libcurl`.

This works only for HTTP (as per its [documentation](https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html)):
```c
curl_easy_setopt( curl, CURLOPT_ACCEPT_ENCODING, "" );
```

**Comment by vszakats** [comment]
Proposed patch, which seems to be effective, according to Wireshark:
```diff
diff --git a/docs/libcurl/opts/CURLOPT_ACCEPT_ENCODING.3 b/docs/libcurl/opts/CURLOPT_ACCEPT_ENCODING.3
index 3a5fc166d..27646ada7 100644
--- a/docs/libcurl/opts/CURLOPT_ACCEPT_ENCODING.3
+++ b/docs/libcurl/opts/CURLOPT_ACCEPT_ENCODING.3
@@ -64,7 +64,7 @@ option.
 .SH DEFAULT
 NULL
 .SH PROTOCOLS
-HTTP
+HTTP, SCP, SFTP
 .SH EXAMPLE
 .nf
 CURL *curl = curl_easy_init();
diff --git a/lib/ssh.c b/lib/ssh.c
index 9443e24b9..ad1b50ee0 100644
--- a/lib/ssh.c
+++ b/lib/ssh.c
@@ -2935,6 +2935,13 @@ static CURLcode ssh_connect(struct connectdata *conn, bool *done)
     return CURLE_FAILED_INIT;
   }
 
+#if LIBSSH2_VERSION_NUM >= 0x010208
+  if(data->set.str[STRING_ENCODING] &&
+     libssh2_session_flag(ssh->ssh_session, LIBSSH2_FLAG_COMPRESS, 1) < 0) {
+    infof(data, "Failure to enable compression for ssh session");
+  }
+#endif
+
 #ifdef HAVE_LIBSSH2_KNOWNHOST_API
   if(data->set.str[STRING_SSH_KNOWNHOSTS]) {
     int rc;
```

**Comment by jay** [comment]
Ok but I don't think it's appropriate to piggyback on that option, it's too different. I suggest making it a separate option like CURLOPT_SSH_COMPRESSION or curl_easy_setopt(curl, CURLOPT_SSH_FLAGS, CURLSSHFLAG_COMPRESSION) etc

**Comment by vszakats** [comment]
@jay: Thank you for your feedback. If the quick patch is fine, I'll try to hammer up a new one with a separate option. Am I supposing right, that we're going to need a new command-line option for this as well? (F.e. `--compress-ssh`)

**Comment by vszakats** [comment]
Here's the patch that adds `CURLOPT_SSH_COMPRESSION` and `--compressed-ssh` options:
https://github.com/vszakats/curl/tree/ssh_compress

**Comment by vszakats** [comment]
Closing this in favour of new PR: https://github.com/curl/curl/pull/1735
