### ISSUE TITLE
CentOS6 Build fail

### ISSUE THREAD

**Issue by fubarhouse** [curl/curl#1743]
### I did this

Built as per usual, tests are passing for 19 platforms, and failing via the same test on CentOS6
* See https://travis-ci.org/fubarhouse/ansible-role-curl/builds/261293746 

### I expected the following

Pass on all similar platforms, but failed on CentOS6.

### curl/libcurl version

Information not available - attempting to install curl-7.54.0 or above via make.

### operating system

CentOS6

See the failing test (scroll to the bottom) https://travis-ci.org/fubarhouse/ansible-role-curl/jobs/261293779

Details of stderr:

````
    "stderr_lines": [
        "/bin/sh: ../src/mkhelp.pl: Permission denied", 
        "/usr/bin/iconv: conversion stopped due to problem in writing the output", 
        "make[1]: *** [tool_hugehelp.c] Error 126", 
        "make[1]: *** Deleting file `tool_hugehelp.c'", 
        "make: *** [all-recursive] Error 1"
    ], 
````

As this is passing on CentOS7 among other operating systems, how would I be able to either fix? If not a bug with the project, are there additional dependencies for this platform not already noted?

**Comment by jay** [comment]
Try chmod +x src/mkhelp.pl. If that works I propose this:

~~~diff
From 0601b0c0af01c9234c5c99bd64756dbd724159a2 Mon Sep 17 00:00:00 2001
From: Jay Satiro <raysatiro@yahoo.com>
Date: Wed, 9 Aug 2017 02:59:18 -0400
Subject: [PATCH] mkhelp.pl: enable execute permission (chmod +x)

Fixes https://github.com/curl/curl/issues/1743
---
 src/mkhelp.pl | 0
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 src/mkhelp.pl

diff --git a/src/mkhelp.pl b/src/mkhelp.pl
old mode 100644
new mode 100755
-- 
1.9.5.msysgit.1
~~~

**Comment by bagder** [comment]
The configure script doesn't find perl, so it can't run mkhelp.pl at all... The easiest fix for this is to make sure perl is installed when you build curl, not only for the mkhelp script but for other parts as well.

**Comment by fubarhouse** [comment]
That is now passing... As I am not overly familiar with perl conventions - at least I haven't been so for years I am sorry for wasting your time.

I thank you very much for the really quick response and resolution though!
