### ISSUE TITLE
libCurl cmake build fails: "cmake_uninstall.cmake.in does not exist"

### ISSUE THREAD

**Issue by Dani-Hub** [curl/curl#1755]
### I  invoke the cmake-based build using cmake 3.8.1 and Visual Studio 2012 (vc110) (via CMakeLists.txt in the root directory), but the build fails as follows:

[INFO] -- Check size of struct sockaddr_storage
[INFO] -- Check size of struct sockaddr_storage - done
[INFO] -- Enabled features: IPv6 AsynchDNS Largefile
[INFO] -- Enabled protocols: DICT FILE FTP GOPHER HTTP IMAP LDAP POP3 RTSP SMTP TELNET TFTP
[INFO] CMake Error: File E:/Development/workspace_cpp_4_2/se.haxx.libcurl/src/cmake_uninstall.cmake.in does not exist.
[INFO] CMake Error at CMakeLists.txt:1345 (configure_file):
[INFO]   configure_file Problem configuring file
[INFO] -- Configuring incomplete, errors occurred!
[INFO] See also "E:/Development/workspace_cpp_4_2/se.haxx.libcurl/build/win32-x86-vc110/CMakeFiles/CMakeOutput.log".
[INFO] See also "E:/Development/workspace_cpp_4_2/se.haxx.libcurl/build/win32-x86-vc110/CMakeFiles/CMakeError.log".

### I expected a successful cmake build (We use the cmake-based build since years, including the last official version 7.54.1)

The error can be very likely attributed to a change of the root CMakeLists.txt between the last official libCurl release 7.54.1 and 7.55.0. These last lines are

```
if(NOT TARGET uninstall)
  configure_file(
      ${CMAKE_CURRENT_SOURCE_DIR}/cmake_uninstall.cmake.in
      ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake
      IMMEDIATE @ONLY)

  add_custom_target(uninstall
      COMMAND ${CMAKE_COMMAND} -P
      ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake)
endif()
```

The problem is that there does not exist any file ``cmake_uninstall.cmake.in`` as part of the libCurl source code. The attached zip file contains the two log files mentioned in the log output mentioned above.

[CMakeErrorLogs.zip](https://github.com/curl/curl/files/1214641/CMakeErrorLogs.zip)

**Comment by bagder** [comment]
[This file](https://github.com/curl/curl/blob/master/cmake_uninstall.cmake.in) is missing in the release.

**Comment by Dani-Hub** [comment]
Thanks very much for your quick reaction!
