### ISSUE TITLE
multi_socket() callback says REMOVE after socket is already closed when c-ares is used

### ISSUE THREAD

**Issue by zero-rp** [curl/curl#1776]
### I did this
USE_ARES=1
use poll and curl_multi
### I expected the following
Before the CURL_POLL_REMOVE event arrives, arse closes the fb, causing fb to be invalid when processing poll in the CURL_POLL_REMOVE event
### curl/libcurl version
7.50.1
[curl -V output]

### operating system
win10

**Comment by bagder** [comment]
Right, for this mechanism to work really good and be able to send `CURL_POLL_REMOVE` *before* the close is actually performed we need to use callbacks from c-ares that tell us when it intends to close its sockets. Also probably when it opens them.

The current code uses [ares_fds](https://c-ares.haxx.se/ares_fds.html), but that needs to be polled and will then not know when a close is about to happen but will work after-the-fact.

It might also require a fairly new c-ares version.

**Comment by zero-rp** [comment]
think you,I use this code https://curl.haxx.se/libcurl/c/multi-uv.html,Do you have any good suggestions?

**Comment by zero-rp** [comment]
After I update the Ares, it seems that the problem has been solved

**Comment by bagder** [comment]
Cased closed then.
