### ISSUE TITLE
IMAP requests cause fails (56) on version 7.55 (regression?)

### ISSUE THREAD

**Issue by maysara** [curl/curl#1778]
using v7.55 on centos from curl downloads 
curl -k --url imaps://IPADDRESS/INBOX\;UID=1 --user "user@domain"

I get curl: (56) Failure when receiving data from the peer

same command on v7.35 on bash on windows works just fine

~~~
curl 7.55.0 (x86_64-redhat-linux-gnu) libcurl/7.55.0 NSS/3.28.4 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.8.0 nghttp2/1.21.1
Release-Date: 2017-08-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink PSL
~~~
and 
~~~
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
~~~

**Comment by bagder** [comment]
and if you use `-v`, can you show us what it logs? (edit out sensitive info before pasting anything here)

**Comment by maysara** [comment]
Greetings @bagder; I've run it with -v and figured out how to work around that issue (I'm not sure if the current behavior is ideal though).

The issue was with the AUTH= used, on the linux subsystem on windows, curl selected NTLM, while on Centos I've got:

< A001 OK CAPABILITY completed.
* gss_init_sec_context() failed: No Kerberos credentials available (default cache: KEYRING:persistent:1000).
* Closing connection 0
curl: (56) Failure when receiving data from the peer

passing --login-options AUTH=NTLM or --login-options AUTH=PLAIN to the curl command on Centos now works identical/similar to that on the linux subsystem.

**Comment by maysara** [comment]
The complete output on Centos is/was:

$ curl -v -k --url imaps://IP/INBOX/ --user "USER"
Enter host password for user 'USER':
*   Trying IP...
* TCP_NODELAY set
* Connected to IP (IP) port 993 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=SRVNAME
*       start date: Dec 11 20:09:13 2016 GMT
*       expire date: Dec 11 20:09:13 2021 GMT
*       common name: SRVNAME
*       issuer: CN=SRVNAME
< * OK The Microsoft Exchange IMAP4 service is ready.
> A001 CAPABILITY
< * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
< A001 OK CAPABILITY completed.
* gss_init_sec_context() failed: No Kerberos credentials available (default cache: KEYRING:persistent:1000).
* Closing connection 0
curl: (56) Failure when receiving data from the peer
