### ISSUE TITLE
connect to HTTPS site through proxy "Recv failure: Connection was reset" curl_errno: 56

### ISSUE THREAD

**Issue by mrmax2000** [curl/curl#1780]
I've got the following problem: there is an HTTPS web site, and I need to connect to it through a proxy. Here are my cURL setopts:

```
$url="https://bearsmyip.com/";
$ch = curl_init(trim($url));

curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_NOBODY, false);
curl_setopt($ch, CURLOPT_HTTPPROXYTUNNEL, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1);
curl_setopt($ch, CURLOPT_CAINFO, dirname(__FILE__) .'/cert.pem');
curl_setopt($ch, CURLOPT_COOKIEFILE, dirname(__FILE__) .'./cookie.txt');
curl_setopt($ch, CURLOPT_COOKIE, "cookiename=0");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_PROXY,'xxx.xxx.xxx.xxx:8085');
echo curl_exec($ch);
var_dump(curl_error($ch));		
echo "curl_errno: ".curl_errno($ch)."<br>";
```
i got this error

**"Recv failure: Connection was reset" curl_errno: 56**

if remove proxy its working 

PHP Version 5.6.30
cURL Information | 7.51.0
window 10
appserv

**Comment by mrmax2000** [comment]
can you help me Mr Daniel ???
its very important for me

**Comment by bagder** [comment]
That's a PHP program, and that's a binding using libcurl which makes it complicated. We don't work on the PHP binding here.

What does the `VERBOSE` output say, how far does it reach in the connection/transfer phase? What proxy software/version is this?  Does it work if you run over another proxy?

**Comment by mrmax2000** [comment]
Thank you Mr Daniel for your replay
verbose result

```
*   Trying 79.110.25.216...
* TCP_NODELAY set
* Connected to 79.110.25.216 (79.110.25.216) port 8085 (#0)
* Establish HTTP proxy tunnel to bearsmyip.com:443
> CONNECT bearsmyip.com:443 HTTP/1.1
Host: bearsmyip.com:443
Proxy-Connection: Keep-Alive

* Recv failure: Connection was reset
* Received HTTP code 0 from proxy after CONNECT
* Curl_http_done: called premature == 0
* Closing connection 0

```
my proxy `ip address` is paid and Binding to my ip address 
no problem in php if change url to ` https://www.facebook.com  ` or ` https://www.google.com ` its will work with current proxy with out any problem
but on some sites 
like this :` https://bearsmyip.com` , `https://www.coursera.org`
 return empty page after 2 second with this

 `"Recv failure: Connection was reset" curl_errno: 56`
if can help me i will very happy Thank you

**Comment by bagder** [comment]
Are you sure that's a HTTP proxy at all? It doesn't respond at all so if it is, it is a very broken one.

**Comment by mrmax2000** [comment]
its not broken it's work with http but when go through https on this :https://bearsmyip.com , https://www.coursera.org
return empty page in in https://www.facebook.com or https://www.google.com work very good
the proxy will not work with you because Binding to my ip address
this free proxy you can try 
`171.255.199.57:80`

**Comment by bagder** [comment]
The point I'm trying to make is that the proxy doesn't respond with proper HTTP in this case and thus it is  broken - it doesn't help us much that it works fine with other hosts. There's nothing curl can do about a proxy that disconnects without even giving an error code. This is a proxy issue and you should ask the proxy admins about it.

**Comment by mrmax2000** [comment]
Thank you Mr Daniel for help
you are the big boss in curl world,
I am sure it will not be difficult for you because there are those who have the way but unfortunately refused to give me the solution,
This site link uses https: `https://www.att.com/`
and Here is the site of proxies `https://free-proxy-list.net/`
if you please can you try my code with any **HTTP IP ADRESS** you want from proxy site above 
with any way or any php code you like to display `https://www.att.com/` throw **HTTP proxy** 
thank you very much for you time

**Comment by bagder** [comment]
If you need help with your PHP program, then please talk to PHP people.

I could run this;

`curl -x 138.204.145.39:80 https://curl.haxx.se/`

... using a proxy from that list. But it took several tries because a lot of those proxies don't support `CONNECT`, like your original issue here shows. Again, that's due to how the proxy is configured or built, it is strictly not a curl problem. You just need to make sure that you use a proxy that supports what you want to do with the proxy.

This issue is hereby considered closed.
