### ISSUE TITLE
http2 requests fail on some hosts, but not all

### ISSUE THREAD

**Issue by ithinkihaveacat** [curl/curl#1791]
I have a curl built with nghttp2 on Linux which successfully connects to some hosts over http2:

```sh
$ curl -sS -D - -o /dev/null --http2 https://www.cloudflare.com/
HTTP/2 200
...
```

However, it will only connect to some hosts (which otherwise support http2) over http1.1:

```sh
$ curl -sS -D - -o /dev/null --http2 https://pwa.today/
HTTP/1.1 200 OK
...
```

```sh
$ curl -sS -D - -o /dev/null --http2 https://www.standard.co.uk/
HTTP/1.1 200 OK
...
```

(Both of these hosts support http2 when loaded via Chrome, and also according to https://tools.keycdn.com/http2-test.)

I don't know why the two latter hosts fail, but other succeed, though one reason may be because they have a large number of alternate names ([pwa.today](https://www.ssllabs.com/ssltest/analyze.html?d=pwa.today&s=151.101.65.195&latest), [standard.co.uk](https://www.ssllabs.com/ssltest/analyze.html?d=www.standard.co.uk&s=151.101.129.184&latest)).

`curl -V` output:

```sh
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.1f zlib/1.2.8 nghttp2/1.24.0
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```

**Comment by bagder** [comment]
Your problem: `OpenSSL/1.0.1f`

This version of OpenSSL doesn't support ALPN, which is the TLS extension needed to negotiate HTTP/2 with the HTTPS server. You need OpenSSL 1.0.2 or later for this.

Some HTTP/2 servers (like https://www.cloudflare.com/) also allows NPN to be used to negotiate HTTP/2 (as that was originally used for SPDY) - and OpenSSL 1.0.1 supports that! But as browsers have dropped NPN support a while ago, the number of servers that allow this are likely to diminish over time.

An NPN negotiated HTTP2 will say this in the verbose output:
`* NPN, negotiated HTTP2 (h2)`

... while an ALPN negotiated HTTP2 says:
`* ALPN, server accepted to use h2`
