### ISSUE TITLE
Configure error with Android NDK r15c

### ISSUE THREAD

**Issue by BillPyne** [curl/curl#1801]
While upgrading to Android NDK r15c and libcurl 7.55.1, I encountered an error with cross-compiling libcurl on OS X (10.12.6) for Android API 15. Specifically, the error occurred in the configure script.
```
checking for recv... no
configure: error: Unable to link function recv
```
Note, libcurl 7.50.1 is the most recent version I can compile with NDK r15c. I never get as far as #1738 with newer libcurl versions.

**Comment by bagder** [comment]
Now that's curious since @destman got further and #1738 is fixed now.

If you check your `config.log` after the configure failure, can you submit that to us or just investigate what it reveals from the `recv()` presence check?

**Comment by destman** [comment]
Not long ago i compile for r15c and libcurl 7.55.1 compiled without any problem.
Android API level was 14 for arm, mips, x86 (all 32 bit) and 21 for arm64, mips64, x86_64(all 64 bit) 
Btw i use `libc++` stl and i have to add some linker flags (`LDFLAGS=-lc++_static -lm -ldl -latomic`) so proper library for stl was used.

**Comment by BillPyne** [comment]
Thank you, @bagder, for your prompt response. Below is a snippet from the log when checking for recv.
```
configure:29733: checking for recv
configure:29771: {some path}/cURL/android_toolchain-x86-plat-15/bin/i686-linux-android-clang -o conftest -isystem {some path}/libs/Android/x86/include -L{some path}/libs/Android/x86/lib -Qunused-arguments -Os -mmacosx-version-min=10.8 -Werror=partial-availability  -I/opt/local/include  -L/opt/local/lib conftest.c -lz  >&5
{some path}/cURL/android_toolchain-x86-plat-15/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: z: no archive symbol table (run ranlib)
clang50: error: linker command failed with exit code 1 (use -v to see invocation)
configure:29771: $? = 1
configure: failed program was:
```

I appreciate the feedback, @destman. We have compiled a few versions of libcurl in the past without issue also with static libc++. The last time was with NDK r14b for armeabi, armeabi-v7a, and x86 (sadly, no 64-bit yet). Do you also build on OS X?

**Comment by bagder** [comment]
> `error: z: no archive symbol table (run ranlib)`

That sounds like a problem with your zlib somehow. As a test, try passing `--without-zlib` to configure and see if it does anything different.

**Comment by DanAlbert** [comment]
> error: z: no archive symbol table (run ranlib)

I've seen this happen if you're using the system's (darwin's, iirc) ar instead of the one in the NDK. Make sure your build is using `android_toolchain-x86-plat-15/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ar` rather than just a raw `ar` or `/usr/bin/ar` or whatever.

**Comment by BillPyne** [comment]
Thank you both for the suggestions!

When passing `--without-zlib`, libcurl compiles for me. We intend to use the version of zlib shipped with the NDK. After looking over our scripts, I don't see how we pass that intention on to the configure script for curl. Perhaps that is our issue? Is there a proper way to specify that?

In regards to `ar` @DanAlbert, we setup the standalone toolchain and set `AR`. Hopefully that is sufficient?

**Comment by destman** [comment]
@BillPyne Yes i compile at macOS . 
Here is some parts of Makefile that compile libs:
```sh
PREFIX=${CURDIR}/build/Android/${ARCH}
TOOLCHAIN=toolchain/${ARCH}
LIBDIR=${PREFIX}/lib
INCLUDEDIR=${PREFIX}/include
TC_PATH=$(CURDIR)/${TOOLCHAIN}/bin:${PATH}
AR=${HOST}-ar #(HOST is arm-linux-androideabi, aarch64-linux-android, etc)
CXX=clang++
CC=clang
LDFLAGS=-lc++_static -lm -ldl -latomic
CXXFLAGS=-O3 -std=c++14
CFLAGS=-O3
...
${LIBDIR}/libcurl.a: ${LIBDIR}/libssl.a | ${CURL_DIR}
	cd ${CURL_DIR} && env PATH=${TC_PATH} CXX=${CXX} CC=${CC} AR=${AR} CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS} -L${LIBDIR}" CFLAGS="${CFLAGS} -I${INCLUDEDIR}" \
	./configure --with-ssl --disable-shared --enable-static --disable-verbose --enable-ipv6 --enable-hidden-symbols --enable-threaded-resolver --host=${HOST} --prefix=${PREFIX} &&\
	env PATH=${TC_PATH} ${MAKE} clean install
```

Toolchains created like this:
```
make_standalone_toolchain.py --stl libc++ --arch arm --api 14 --install-dir "toolchain/arm"
```

**Comment by bagder** [comment]
I'm not considering this a curl issue anymore but mostly a question of setting up your cross compiler environment correctly. Is there really anything the curl configure script could've done better / differently here?

**Comment by BillPyne** [comment]
@bagder: I apologize for the delay. Some urgent issues needed to be attended to the last days. As yourself and others mentioned, the issue is probably on our side.

> Is there really anything the curl configure script could've done better / differently here?

Everything has room for improvement. Once the exact issue is determined in our case (need time to look into it more), I will send any suggestions your way, _if_ any arise.

**Comment by bagder** [comment]
Lovely!
