### ISSUE TITLE
dict-schema URLs show the underlying protocol, not just the result

### ISSUE THREAD

**Issue by RalphCorderoy** [curl/curl#1809]
Hi, curl 7.55.1-1 on Arch Linux.

This invocation shows just the data and not the underlying protocol, and
that's what I'd expect.

    $ curl -sSL http://httpbin.org/links/0; echo
    <html><head><title>Links</title></head><body>0 </body></html>
    $

So why does this one have the `220', etc., clutter?

    $ curl -sSL dict://dict.org/d:yagni:foldoc
    220 pan.alephnull.com dictd 1.12.1/rf on Linux 4.4.0-1-amd64 <auth.mime> <57904075.12995.1503155897@pan.alephnull.com>
    250 ok
    150 1 definitions retrieved
    151 "yagni" foldoc "The Free On-line Dictionary of Computing (18 March 2015)"
    You aren't gonna need it
    YAGNI

       <programming> (YAGNI) A motto of {extreme programming} expressing
       the principle that functionality should not be implemented until
       it is needed.  The traditional {waterfall model} makes it
       difficult to add features after the specification has been signed
       off, tempting the specifier to add features that may never be used
       but which take time to program, debug, test and document.

       (2014-03-27)

    .
    250 ok [d/m/c = 1/0/9; 0.000r 0.000u 0.000s]
    221 bye [d/m/c = 0/0/0; 0.000r 0.000u 0.000s]
    $

**Comment by bagder** [comment]
I can't think of a good reason other than that nobody ever cleaned it up...
