### ISSUE TITLE
Curl sends "CWD /" despite CURLFTPMETHOD_NOCWD

### ISSUE THREAD

**Issue by PeterLamare3** [curl/curl#1811]
This is in reference of:

https://github.com/curl/curl/issues/1782

The topic is closed, so I wasn't sure if this is still monitored.

The bug fix in https://github.com/curl/curl/commit/c95eff4a11575a5973fad20619ff7ca3989316db revives https://github.com/curl/curl/issues/1718 from the dead.

Here's how:

Consider a first call using CURLFTPMETHOD_MULTICWD,  (ftpc->prevpath == "/subfolder" => ftpc->cwdcount = 1)
then the easy handle is reused with CURLFTPMETHOD_NOCWD:

The new code in ftp.c, ftp_parse_url_path() makes sure that "ftpc->cwddone" remains "FALSE".

Then the code in ftp_state_cwd() will issue a CWD as expected:
This is because ftpc->cwdcount = 1 for our reused easy handle so your "no CWD necessary" code does not kick in: https://github.com/curl/curl/pull/1727

BUT: The state machine ends the CWD sequence again with ftpc->cwdcount == 1 even though ftpc->prevpath == ""!
( See "if (++ftpc->cwdcount <= ftpc->dirdepth)")

This means the next use of this easy handle with CURLFTPMETHOD_NOCWD will again issue CWD, and so on and so on...

Suggestion: Adapt ftp_parse_url_path() as follows:

```
    if (ftpc->prevpath)
    {
+		if (data->set.ftp_filemethod == FTPFILE_NOCWD)
+		{
+			if (strcmp(ftpc->prevpath, "") == 0)
+			{							
+				infof(data, "Request has same path (\"%s\") as previous transfer\n", ftpc->prevpath);
+				ftpc->cwddone = TRUE;
+			}
+		}
+		else
+		{
			/* prevpath is "raw" so we convert the input path before we compare the
			   strings */
			size_t dlen;
			char* path;
			CURLcode result =
				Curl_urldecode(conn->data, data->state.path, 0, &path, &dlen, FALSE);
			if (result)
			{
				freedirs(ftpc);
				return result;
			}

			dlen -= ftpc->file?strlen(ftpc->file):0;
			if ((dlen == strlen(ftpc->prevpath)) &&
				!strncmp(path, ftpc->prevpath, dlen))
			{
				infof(data, "Request has same path as previous transfer\n");
				ftpc->cwddone = TRUE;
			}
			free(path);
+		}
    }
```

This will solve https://github.com/curl/curl/issues/1782, https://github.com/curl/curl/issues/1718, make the changes in https://github.com/curl/curl/pull/1727/files#diff-f154d33834bd51804f9b45a55084f5dbR890 redundant, and also solve an issue in your new fix: https://github.com/curl/curl/commit/c95eff4a11575a5973fad20619ff7ca3989316db#diff-f154d33834bd51804f9b45a55084f5dbL4308

```
(ftpc->prevmethod == data->set.ftp_filemethod)) {
       infof(data, "Request has same path as previous transfer\n");
       ftpc->cwddone = TRUE;
     }
```

This is suboptimal, e.g. consider:

A first FTP call using CURLFTPMETHOD_NOCWD and  a second call to CURLFTPMETHOD_MULTICWD accessing a file in the  entry folder.
The working folder is equal to the entry folder in both cases, but the "ftpc->cwddone = TRUE;" will be skipped due to the different file methods used and a CWD will be sent needlessly.

I'd love to create a patch, but I'm sorry to be in a rush with different projects now.

Keep up the good work!
-Lama

**Comment by bagder** [comment]
Can you please help me make an example that reproduces this bug so that I can write up a test case?

1. Do `CURLFTPMETHOD_MULTICWD` with what URL?
2. Set `CURLFTPMETHOD_NOCWD` with what URL?

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
