### ISSUE TITLE
Most of the premade lib/config-* files need SIZEOF_LONG defined

### ISSUE THREAD

**Issue by jay** [curl/curl#1816]
Since replacing CURL_SIZEOF_LONG with SIZEOF_LONG in the source, there are some premade config files that don't have SIZEOF_LONG defined and should be addressed. They are:

~~~
config-amigaos.h
config-dos.h
config-mac.h
config-os400.h
config-riscos.h
config-symbian.h
config-tpf.h
~~~

If you are using one of these systems can you tell us your sizeof(long)?

DOS I think is 4. @gvanem have you ever built using config-dos.h?

**Comment by jay** [comment]
more info: os400 if __ILEC400__ appears to be long 4 according to the [7.55.1 system.h](https://github.com/curl/curl/blob/curl-7_55_1/include/curl/system.h#L266). also all the dos compilers have long as size 4. and tpf is 8. i don't see anything mac specific or any of the other platforms.

**Comment by bagder** [comment]
That matches my conclusions as well.

**Comment by gvanem** [comment]
`config-dos.h` should have some more patches as well:
```diff
--- a/config-dos.h 2016-11-22 14:33:02
+++ b/config-dos.h 2017-08-21 11:13:33
@@ -7,7 +7,7 @@
  *                            | (__| |_| |  _ <| |___
  *                             \___|\___/|_| \_\_____|
  *
- * Copyright (C) 1998 - 2015, Daniel Stenberg, <daniel@haxx.se>, et al.
+ * Copyright (C) 1998 - 2017, Daniel Stenberg, <daniel@haxx.se>, et al.
  *
  * This software is licensed as described in the file COPYING, which
  * you should have received as part of this distribution. The terms
@@ -40,8 +40,10 @@
 #define PACKAGE  "curl"

 #define HAVE_ARPA_INET_H       1
+#define HAVE_ASSERT_H          1
 #define HAVE_ERRNO_H           1
 #define HAVE_FCNTL_H           1
+#define HAVE_FREEADDRINFO      1
 #define HAVE_GETADDRINFO       1
 #define HAVE_GETNAMEINFO       1
 #define HAVE_GETPROTOBYNAME    1
@@ -85,9 +87,11 @@

 #define RETSIGTYPE             void
 #define SIZEOF_INT             4
+#define SIZEOF_LONG            4
 #define SIZEOF_LONG_DOUBLE     16
 #define SIZEOF_SHORT           2
 #define SIZEOF_SIZE_T          4
+#define SIZEOF_CURL_OFF_T      4
 #define STDC_HEADERS           1
 #define TIME_WITH_SYS_TIME     1
```

Allthough DJGPP have a `off64_t` (8 byte), but >4GB files are tricky on DOS. Not sure worth the effort.

**Comment by gvanem** [comment]
@jay Yes, I periodicall build the djgpp version under Win-10 using this djgpp cross-compiler: https://github.com/andrewwutw/build-djgpp/releases . Not a single warning using `-Wall`!

**Comment by bagder** [comment]
Thanks @gvanem, landed that patch now.

**Comment by bagder** [comment]
@jay, are you going to patch the rest of the files or do you want me to do it?

**Comment by jay** [comment]
Yes for TPF. The rest I was hoping someone would come along and tell us, I'm not sure on those. I can take it to the list for a wider audience.

**Comment by jay** [comment]
I'd guess most of them are 4 but I've asked on the lists anyway.
https://curl.haxx.se/mail/archive-2017-08/0030.html
https://curl.haxx.se/mail/lib-2017-08/0105.html

**Comment by bagder** [comment]
I think we can come to conclusions on 4 of the remaining 5 systems:

1. [Amiga m68k has long long](https://github.com/kusma/amiga-dev/blob/master/targets/m68k-amigaos/include/stdint.h#L9) (and in existing `config-amigaos.h`) so `curl_off_t` should be 8 bytes.

2. Os400 already has 8 bytes long long and size_t, so `curl_off_t` should be 8 there too.

3. RISCOS has long long undefined, so I'd say it only does 32bit data types.

4. Symbian has long long so `curl_off_t` should use that and be 8 bytes.

MacOS 9 remains a mystery.

**Comment by jay** [comment]
It looks like all except win32/dos will also need SIZEOF_CURL_OFF_T. I wonder how many people use those premade config files, with the exception of win32 I think not many or we would have heard something by now.

**Comment by bagder** [comment]
Also, I think those are platforms that curl isn't built for very often so it might take a while until we get reports on them.

**Comment by jay** [comment]
@bagder your deleted post seems like some good research, why gone?

**Comment by Renata27** [comment]
Hey @jay  and @bagder , just to register in this issue: I find these errors when building with recently curl directly from github.

![captura de tela 2017-08-25 13 29 05](https://user-images.githubusercontent.com/29973991/29749434-b5adc104-8b2b-11e7-97e0-869dfe815bc2.png)
![screenshot 2017-08-24 20 38 54](https://user-images.githubusercontent.com/29973991/29749435-b5c80c12-8b2b-11e7-9b5b-b13367675d38.png)

With previously downloaded curl (from May, I think...), I was able to build again.
I have done this from @nkolban:
https://github.com/nkolban/esp32-snippets/tree/master/curl/build_files

Now, even with the new instructions below from his book launched this month (August 2017)
 (https://leanpub.com/kolban-ESP32 - page 389), it isn't building, as you saw above on the prints.

He says: _To build libcurl we create a components directory and perform some commands within.
The curl source can be downloaded from github using:_
`$ git clone https://github.com/curl/curl.git`
Next we run:
`$ ./buildconf
$ ./configure`

_Remove the following from_ *lib/curl_config.h*
```
HAVE_LIBSSL
USE_OPENSSL
HAVE_ZLIB
HAVE_LIBZ
HAVE_SIGSETJMP
HAVE_SYS_POLL
HAVE_POLL
HAVE_POLL_H
HAVE_CLOCK_GETTIME_MONOTONIC
HAVE_NET_IF_H
HAVE_SYS_IOCTL_H
HAVE_SYS_SELECT_H
HAVE_SYS_UN_H
HAVE_NETINET_TCP_H
HAVE_MSG_NOSIGNAL
HAVE_POLL_FINE
USE_UNIX_SOCKETS
HAVE_IFADDRS_H
HAVE_STROPTS_H
HAVE_GETIFADDRS
HAVE_IOCTL_SIOCGIFADDR
HAVE_GETHOSTNAME
HAVE_GETEUID
HAVE_BASENAME
HAVE_SIGNAL
```
_When building curl, we may need to set some definitions:
The following can be found include/curl/curlbuild.h:_ **I know we don't need this anymore, but he came again with this on the new book**
```
• CURL_SIZEOF_LONG – 4 – The size in bytes of a long.
• CURL_TYPEOF_CURL_SOCKLEN_T – unsigned int – The data type that is a
socklen_t.
• CURL_TYPEOF_CURL_OFF_T – long
• CURL_FORMAT_CURL_OFF_T – "ld"
• CURL_FORMAT_CURL_OFF_TU – "lu"
• CURL_FORMAT_OFF_T – "%ld"
• CURL_SIZEOF_CURL_OFF_T – 4
• CURL_SUFFIX_CURL_OFF_T – L
• CURL_SUFFIX_CURL_OFF_TU – UL
```
_We also need a lib/curl_config.h
We will also need a component.mk with the following entries:_
```
COMPONENT_SRCDIRS:=lib
COMPONENT_PRIV_INCLUDEDIR:=lib include
include $(IDF_PATH)/make/component_common.mk
```
_We need to say that we don't have includes:_
```
• netinet/in.h – HAVE_NETINET_IN_H
• arpa/inet.h – HAVE_ARPA_INET_H
• net/if.h – HAVE_NET_IF_H
• sys/ioctl.h – HAVE_SYS_IOCTL_H
• process.h – HAVE_PROCESS_H
• fcntl.h – HAVE_FCNTL_H
• netinet/tcp.h – HAVE_NETINET_TCP_H
```
__________________________________________
As I have already said in another issue, for curl in my environment to work (msys32) Eclipse ESP IDF, it was never required to do this:
./buildconf
./configure
make
_For buildconf (not buildconf.bat) to work, you need the following software
installed:_

o autoconf 2.57 (or later)
o automake 1.7 (or later)
o libtool 1.4.2 (or later)
o GNU m4 (required by autoconf)

But, as I've had the errors, I've given that a try. But, the errors are the same!
So, I think for new curl, same changes are requested.

Thank you for your constant support!

**Comment by Renata27** [comment]
Here you find previously discussions on that:

https://github.com/nkolban/esp32-snippets/issues/18

https://github.com/nkolban/esp32-snippets/issues/8

**Comment by jay** [comment]
@Renata27 as I said in nkolban/esp32-snippets#42 recent changes in curl will require premade configuration files to be adjusted _for the next release_. I think some of your problem may come from the [directions](https://github.com/nkolban/esp32-snippets/tree/master/curl/build_files#building-curl) you have that say to clone the repo but don't say exactly what to build from, so I'll guess you're building from master. I strongly recommend using the latest release unless there's something stopping you from doing that. `git checkout curl-7_55_1` Also, we cannot be responsible for that special build method if it does not work. You'll have to wait until someone in the ESP32 world addresses it.

**Comment by bagder** [comment]
I propose we close this issue now and instead open specific ones in the future if/when people experience problems.

**Comment by jay** [comment]
> I propose we close this issue now and instead open specific ones in the future if/when people experience problems.

a while back you had posted some analysis of the situation which you deleted, but it seemed spot on, I think you had said they're all probably 4. but i don't know why you deleted it

**Comment by bagder** [comment]
iirc, my analyses that I deleted was (mistakenly) about `off_t` and not long so since it wasn't relevant I took it away.

**Comment by bagder** [comment]
it doesn't change the way I feel about this issue though. I think we should either fill in a guesswork now, or we close it and deal with it when someone gets a problem later on.

**Comment by jay** [comment]
Ok then. I'll close rather than guess.
