### ISSUE TITLE
imap does not support PREAUTH

### ISSUE THREAD

**Issue by nmorey** [curl/curl#1818]
I'm working on tunneling support for git imap-send (run curl through a preopened socket using
CURLOPT_OPENSOCKETFUNCTION and CURLOPT_SOCKOPTFUNCTION.

The command to open the socket (stdin/stdout) during testing is this one
```
ssh -q -C localhost /usr/sbin/imapd ./Maildir
```
It returns:
```
* PREAUTH [CAPABILITY IMAP4REV1 I18NLEVEL=1 LITERAL+ IDLE UIDPLUS NAMESPACE CHILDREN MAILBOX-REFERRALS BINARY UNSELECT ESEARCH WITHIN SCAN SORT THREAD=REFERENCES THREAD=ORDEREDSUBJECT MULTIAPPEND] Pre-authenticated user [...]
```
This is not supported by curl although part of the IMAP RFC.

**Comment by bagder** [comment]
PR #1820 implements a first shot at this, a very basic support of `PREAUTH`.
