### ISSUE TITLE
Compiling for Windows XP using Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by jveazey** [curl/curl#1825]
I'm wondering if there is an easier way to do this. Right now, to compile for Windows XP (SP3), when using Visual Studio 2015 Update 3, I have to manually modify MakefileBuild.vc and add a couple of defines to CFLAGS and CURL_CFLAGS. Specifically, the ones below

/D_USING_V110_SDK71_ /D_WIN32_WINNT=0x502

Is there a way to specify additional defines from the command line when using "nmake /f MakeFile.vc"?

Note: I realize 0x502 is Windows Server 2003, not XP; but this value is also good for Service Pack 3 of Windows XP.

**Comment by rodwiddowson** [comment]
Its a hack, but with care you can use 

Nmake  /f Makefile.vc  MAKE="NMAKE /e"

and add your own defines. Takes some tinkering but you can get what you need done

> Note: I realize 0x502 is Windows Server 2003, not XP; but this value is also good for Service Pack 
> 3 of Windows XP.
And x64 (which is 2003 under the hood)

**Comment by bagder** [comment]
We use this issue tracker for issues/bugs, not for questions and support. Please take those to the mailing list. Now you still got an answer but I'm closing here.
