### ISSUE TITLE
facing issue with latest curl 7.55.1 with latest openssl-1.1.0f

### ISSUE THREAD

**Issue by amit1990sumit** [curl/curl#1834]
I am getting error given below. Although these errors are in openssl but invoke from curl lib.

1) error: invalid use of incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
/ossl_typ.h:145:16: error: forward declaration of 'SSL_CTX {aka struct ssl_ctx_st}'
2)error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
ossl_typ.h:144:16: error: forward declaration of 'SSL {aka struct ssl_st}'

I queried same to openssl team and they have suggested given below.
**"If you're building against OpenSSL 1.1.0 (regardless of letter release), then SSL_CTX has become opaque and you must use available accessor functions to create and use them."**
 
I am using status **curl_easy_setopt(curlHandle, CURLOPT_SSL_CTX_FUNCTION, SslPreInitListener);**
SslPreInitListener contains three paramter(CURL * curlHandle, SSL_CTX * sslCtx, void * ctxData) which is invoke by curl, now how I will handle this because I am not created SSL_CTX instead getting this from curl as a callback return and if access sslCtx->app_verify_arg = ctxData; it gives error.

**Comment by bagder** [comment]
Is this a problem with building curl or building your app? Either way, please give us more details so that we can reproduce. We use OpenSSL 1.1.0 a lot without any problems.

**Comment by amit1990sumit** [comment]
This issue comes while building the app. there are lots of changes in openssl-1.1.0 and since some structures have become opaque you can't directly access the member any more  and cannot allocate objects directly on the stack so need to alloc the object.

Here I am facing issue because SSL_CTX object getting from curl as callback return.
**steps**
1) I am using curl_easy_setopt(curlHandle, CURLOPT_SSL_CTX_FUNCTION, sslListener);
2) And using call back method as 
CURLcode sslListener(CURL * curlHande, SSL_CTX * sslCtx, void * sslCtxData)
    {
        sslCtx->app_verify_arg = sslCtxData;
        return CURLE_OK;
    }
when I am accessing **sslCtx->app_verify_arg** it gives error "error: invalid use of incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
/ossl_typ.h:145:16: error: forward declaration of 'SSL_CTX {aka struct ssl_ctx_st}'"

When I asked with openssl team they suggest to allloc the SSL_CTX and then use but I do not have that control.

Please help.

Thanks,

**Comment by bagder** [comment]
OK, so OpenSSL has changed its API so you need to use functions instead of directly accessing struct members in `SSL_CTX`. What can *we* do about that?

**Comment by amit1990sumit** [comment]
Thanks for reply,
Here I just want to confirm that SSL_CTX object return as callback parameter is allocated from curl end or not.
As per new openssl-1.1.0 we need to use SSL_CTX_new().

Please correct me if I am wrong in understanding,

Thanks for kind help.

**Comment by bagder** [comment]
That doesn't make much sense. The SSL_CTX pointer is of course allocated with ` SSL_CTX_new()`. It always was and still is.

**Comment by jay** [comment]
Please show us the post or issue where the OpenSSL team told you that you had to allocate the ctx. Judging by your initial quote they said you'd have to use accessor functions. How is that a curl problem? 

How about https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_cert_verify_callback.html

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by amit1990sumit** [comment]
Sorry for delay response,
 I got my answer from OpenSSL. Some of API's are private in openssl-1.1.0f, therefore, facing the issue.
Thanks again for help.
