### ISSUE TITLE
build error on Solaris 10

### ISSUE THREAD

**Issue by sivadath** [curl/curl#1838]
### curl/libcurl version

[curl -V output]

**Comment by sivadath** [comment]
Im using solaris 10

**Comment by bagder** [comment]
Which curl version do you try to build and what compiler are you using?

**Comment by bagder** [comment]
And do consider pasting the last 20-30 lines of your terminal output to show us what the error looks like for you.

**Comment by sivadath** [comment]
7.55.1/7.55.0 versions of curl were used

Making all in lib
make: Fatal error in reader: Makefile, line 3517: Badly formed macro assignment
Current working directory /export/home/dath/Desktop/ws1/curl-7.55.1/lib
*** Error code 1
The following command caused the error:
fail=; \
if (target_option=k; case ${target_option-} in  ?) ;;  *) echo
"am__make_running _with_option: internal error: invalid"  "target
option '${target_option-}' speci fied" >&2;  exit 1;;  esac;
has_opt=no;  sane_makeflags=$MAKEFLAGS;  if {  if t est -z ''; then
false;  elif test -n ''; then  true;  elif test -n '' && test - n '';
then  true;  else  false;  fi;  }; then  sane_makeflags=$MFLAGS;  else
 ca se $MAKEFLAGS in  *\\[\ \       ]*)  bs=\\;
sane_makeflags=`printf '%s\n' "$MAK EFLAGS"  | sed "s/$bs$bs[$bs $bs
     ]*//g"`;;  esac;  fi;  skip_next=no;  st rip_trailopt ()  {
flg=`printf '%s\n' "$flg" | sed "s/$1.*$//"`;  };  for flg i n
$sane_makeflags; do  test $skip_next = yes && { skip_next=no;
continue; };  ca se $flg in  *=*|--*) continue;;  -*I) strip_trailopt
'I'; skip_next=yes;;  -*I?* ) strip_trailopt 'I';;  -*O)
strip_trailopt 'O'; skip_next=yes;;  -*O?*) strip_t railopt 'O';;
-*l) strip_trailopt 'l'; skip_next=yes;;  -*l?*) strip_trailopt ' l';;
 -[dEDm]) skip_next=yes;;  -[JT]) skip_next=yes;;  esac;  case $flg in
 *$t arget_option*) has_opt=yes; break;;  esac;  done;  test $has_opt
= yes); then \
  failcom='fail=yes'; \
else \
  failcom='exit 1'; \
fi; \
dot_seen=no; \
target=`echo all-recursive | sed s/-recursive//`; \
case "all-recursive" in \
  distclean-* | maintainer-clean-*) list='lib src tests packages
scripts include  docs' ;; \
  *) list='lib src' ;; \
esac; \
for subdir in $list; do \
  echo "Making $target in $subdir"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-am"; \
  else \
    local_target="$target"; \
  fi; \
  (CDPATH="${ZSH_VERSION+.}:" && cd $subdir && make  $local_target) \
  || eval $failcom; \
done; \
if test "$dot_seen" = "no"; then \
  make  "$target-am" || exit 1; \
fi; test -z "$fail"


make: Fatal error: Command failed for target `all-recursive'


I'm using gcc

**Comment by sivadath** [comment]
And thanks for responding.

**Comment by sivadath** [comment]
-rm -f ./$(DEPDIR)/libcurl_la-splay.Plo

**Comment by bagder** [comment]
You sure? That doesn't look like any "Badly formed macro assignment". Can you find something like that on some line near this `rm`?

**Comment by sivadath** [comment]
it looks like something wrong with my make version I'm using , it went fine with GNU MAKE gmake command , So sorry for wasting your time for my mistake. And thank you for the responding. This conversation might help if someone else faces the same problem while working on solaris 10 and lower versions. Thank you
