### ISSUE TITLE
CURLOPT_PINNEDPUBLICKEY does not work on cURL 7.55 with winssl

### ISSUE THREAD

**Issue by prixone** [curl/curl#1852]
### I did this

I have 2 builds of cURL, one with winssl and another with openssl.

On the build with OpenSSL, if I set these options as follow:

```
curl_easy_setopt(curl, CURLOPT_PINNEDPUBLICKEY, "SOME RANDOM PIN THAT DOES NOT MATCH");
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
```

It will properly fail the request, and if I change it to the actual PIN code(the one that matches), it will pass and complete the request.

When using the build with WinSSL, it will simple ignore those variables and give you the complete request directly.

Let me know if additional information is required, 
Thanks.

### I expected the following

That setting those 2 variable will make the WinSSL request fail if the PIN does not match, and pass if it matches, like it does for OpenSSL.

### curl/libcurl version

```
curl 7.55.0 (i386-pc-win32) libcurl/7.55.0 WinSSL
Release-Date: 2017-08-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp
smb smbs smtp smtps telnet tftp
Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL
```

### operating system

Windows 7 SP1

**Comment by jay** [comment]
Public key pinning is not yet [available](https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html#AVAILABILITY) for WinSSL, curl_easy_setopt should return an [error](https://github.com/curl/curl/blob/curl-7_55_0/lib/url.c#L2219-L2230) in that case. There's a proposal to add support for it in #1429, so maybe some day.

**Comment by prixone** [comment]
I've checked that page and not sure how I missed that `Other SSL backends not supported.`.

Thanks for the answer and the further link to a feature request of it I will follow that.
