### ISSUE TITLE
Set up curl lib for Visual Studio 2008

### ISSUE THREAD

**Issue by vudoancs** [curl/curl#1863]
Hello,

I set up curl lib for VS Studio 2008 using static lib, but I got the below error and have been tried to fix it for several hours, but I cant find the solution.

`1>libcurl_a_debug.lib(idn_win32.obj) : error LNK2019: unresolved external symbol __imp__IdnToAscii@20 referenced in function _curl_win32_idn_to_ascii
1>libcurl_a_debug.lib(idn_win32.obj) : error LNK2019: unresolved external symbol __imp__IdnToUnicode@20 referenced in function _curl_win32_ascii_to_idn`

I appreciate if anyone helps me.
Thank in advance!

**Comment by jzakrzewski** [comment]
You have to add ```Normaliz.lib``` to your linker (see: https://msdn.microsoft.com/en-us/library/windows/desktop/dd318149%28v=vs.85%29.aspx ).

**Comment by bagder** [comment]
Three years ago @jay [wrote](https://curl.haxx.se/mail/lib-2014-12/0084.html):

> VS2008 default SDK doesn't have IdnToAscii or IdnToUnicode in normaliz.lib.

and encouraged the user to build with:

`nmake /f Makefile.vc mode=dll VC=9 ENABLE_IDN=no`

**Comment by vudoancs** [comment]
@jzakrzewski 
Thank you very much!
I already added Normaliz.lib and also got the same problem.

@bagder 
Thank you for your help.

I did like this and then run. I got the message about libcurl.dll.

Can you tell me how to put libcurl.dll in the project?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
