### ISSUE TITLE
undefined reference to `idn2_check_version'

### ISSUE THREAD

**Issue by esfomeado** [curl/curl#1869]
### I did this

./configure --disable-shared --enable-optimize --enable-threaded-resolver --disable-libcurl-option --disable-ares --disable-rt --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-ipv6 --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-unix-sockets --without-zlib --without-winssl --without-ssl --without-libssh2 --without-nghttp2 --disable-cookies --without-ca-bundle --without-librtmp --disable-verbose --disable-versioned-symbols --enable-hidden-symbols

Built my application and got:
undefined reference to `idn2_check_version'

### I expected the following
To build successfully.

### curl/libcurl version

curl 7.55.1 (x86_64-w64-mingw32) libcurl/7.55.1 libidn2/2.0.3
Release-Date: 2017-08-14
Protocols: http
Features: AsynchDNS IDN Largefile

### operating system
Windows 10 x64 using mingw

**Comment by bagder** [comment]
You probably didn't provide libidn2 in your build's link options. Optionally you can select to build curl with winssl on a windows by using `--with-winidn`

**Comment by esfomeado** [comment]
I used --without-libidn2 to solve the problem.

**Comment by bagder** [comment]
Either way, not a curl bug...
