### ISSUE TITLE
Feature missing between versions

### ISSUE THREAD

**Issue by duytrung** [curl/curl#1883]
### I did this
```
curl 7.50.3 (i686-pc-msys) libcurl/7.54.1 OpenSSL/1.0.2k zlib/1.2.11 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink
```

```
curl --version
curl 7.55.1 (i386-pc-win32) libcurl/7.55.1 OpenSSL/1.1.0f zlib/1.2.11 WinIDN libssh2/1.8.0 nghttp2/1.25.0
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy
```
### I expected the following
missing features, for example, metalink support
### curl/libcurl version
7.55.1

[curl -V output]

### operating system
Windows 10

I'm wondering where can I download the version of curl that support all features?

Thanks!

Regards

**Comment by bagder** [comment]
In the curl project we ship source code. Friendly volunteers build and offer binary downloads for many platforms, including Windows. We do our best in trying to point to places where you can download binaries on the download page, but they're not actually built and provided by the curl project itself.

You could try downloading the newer version from the same place you downloaded the older version from, in the expectation that they would keep roughly the same feature set over time. Or you can ask the source of your recent download if they can add some features to the build.

Failing that, you can of course build curl yourself with the exact feature set you like.

**Comment by bagder** [comment]
As this isn't really a curl bug, I'm closing.
