### ISSUE TITLE
socks4 parse error

### ISSUE THREAD

**Issue by Jackarain** [curl/curl#1892]
https://github.com/curl/curl/blob/c8666089c82625a385e5d43df538b951635bccc8/lib/socks.c#L309
https://github.com/curl/curl/blob/c8666089c82625a385e5d43df538b951635bccc8/lib/socks.c#L319
https://github.com/curl/curl/blob/c8666089c82625a385e5d43df538b951635bccc8/lib/socks.c#L329
https://github.com/curl/curl/blob/c8666089c82625a385e5d43df538b951635bccc8/lib/socks.c#L338

should be:

(((unsigned char)socksreq[3] << 8) | (unsigned char)socksreq[4])

**Comment by bagder** [comment]
Sorry but that doesn't make sense, the sockreq[4] is already shown as the first byte of the IP address.

The short documentation in the comment above would however imply that index 2 and 3 are the ones that hold the port number.

**Comment by Jackarain** [comment]
*     +----+----+----+----+----+----+----+----+
     *     | VN | CD | DSTPORT |      DSTIP        |
     *     +----+----+----+----+----+----+----+----+
     * # of bytes:  1    1      2              4

**Comment by bagder** [comment]
That's the comment I referred to. It mentions `DSTPORT` on index 2 and 3.

**Comment by jay** [comment]
Thanks, landed in 6d43664. I worked on those lines last but I didn't catch it. It's been like that since it was added in 2006, see a15d107. My guess is it was copied over from some SOCKS5 error message parsing since in a SOCKS5 response the port comes after the ip address.
