### ISSUE TITLE
CLient certificate auth not supported through schannel

### ISSUE THREAD

**Issue by ravisuhane** [curl/curl#1897]
When certificate private key is stored on Windows certificate store / TPM (you can not export the private key), there is not way to supply the client certificate to curl schannel. 

code in schannel.c tries to continue without client cert and authetication fails with server which mandates client auth. 

/* If the server has requested a client certificate, attempt to continue
the handshake without one. This will allow connections to servers which
request a client certificate but do not require it. */
if(sspi_status == SEC_I_INCOMPLETE_CREDENTIALS &&
!(connssl->req_flags & ISC_REQ_USE_SUPPLIED_CREDS)) {
connssl->req_flags |= ISC_REQ_USE_SUPPLIED_CREDS;
connssl->connecting_state = ssl_connect_2_writing;
infof(data, "schannel: a client certificate has been requested\n");
return CURLE_OK;
}

there should be a way to supply the windows certificate context to curl/schannel.

I tested latest curl code with schannel and TLS session does not use client certificate for auth and it fails.

If this can not be fixed soon, can someone give me idea where can I add my custom method in curl which can supply windows certificate context to curl for schannel ?

**Comment by bagder** [comment]
I can't spot any code that adds support for client certificates when the schannel backend is used. This information should be provided in the `CURLOPT_SSLCERT` man page I think but it isn't.

> can someone give me idea where can I add my custom method in curl which can supply windows certificate context to curl for schannel ?

`lib/vtls/schannel.c` has all the schannel specific code.

**Comment by ravisuhane** [comment]
Yes there is no code code which gets the certificate context from Windows store and supply it to AcquireCredentialsHandle. This is required for schannel.  

It would be helpful if you can suggest where should I add my custom method which I can call from my app to pass the cert context to curl from connect method in schannl.c  can use that.

**Comment by bagder** [comment]
> It would be helpful if you can suggest where should I add my custom method which I can call from my app to pass the cert context to curl from connect method in schannel.c can use that.

The libcurl API that an application typically sets to ask for a client cert to be used is the [CURLOPT_SSLCERT](https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERT.html) option for the cert and [CURLOPT_SSLKEY](https://curl.haxx.se/libcurl/c/CURLOPT_SSLKEY.html) for the private key etc.

You seem to suggest that you need to pass in a "cert context". Where is that coming from?

Please understand that we're hardly anyone around that are masters of schannel and the winssl specific TLS details, so it will be helpful if you assume that we don't know much about schannel at all when you describe for us what needs and requirements you may have for this to function.

**Comment by ravisuhane** [comment]
schannel needs windows OS specific "cert context" to perform client certificate authentication.
This "cert context" is coming from windows OS  (specific to Win OS ) which will be consumed by schannel to perform mutual auth.  

Please note that private key is installed on Windows OS store / TPM/ smartcard from where private key can not be extracted. so CURLOPT_SSLKEY is not useful here.

**Comment by bagder** [comment]
> This "cert context" is coming from windows OS

Sure, but *how* ? Isn't that cert accessed (extracted) by name or something?

We want to avoid (to a very high degree) introducing a *new* API way to activate this that would be schannel specific.

**Comment by ravisuhane** [comment]
Yes I know  its not good idea to introduce specific API.

I have some idea that would require changes only in shchannel.c implementation and no changes in existing API.

I will update once i implement and test that.

Thanks for your  time.
ravi suhane

**Comment by dhoelzl** [comment]
We use client certificate authentication on Windows via `CURLOPT_SSL_CTX_FUNCTION`/`SSL_CTX_set_client_cert_cb` and code-parts (e.g. `RSA_new` and `RSA_set_method` with the RSA delegation methods to the Windows Crypto API) of the Crypto API Engine from OpenSSL (https://github.com/openssl/openssl/blob/master/engines/e_capi.c). The client certificate can be selected by the user via `CryptUIDlgSelectCertificateFromStore`.
But this way I could not find a possibility to support smart cards.

**Comment by bagder** [comment]
Feel free to re-open when more data/information is provided.

**Comment by tsaridas** [comment]
I suppose there is no interest in adding this feature ?

**Comment by bagder** [comment]
@tsaridas: feel free to help us out!

**Comment by mback2k** [comment]
This feature is not yet implemented and on the TODO list, see: https://github.com/curl/curl/blob/master/docs/TODO#L772
