### ISSUE TITLE
coverity defect: 1418138 Dereference after null check

### ISSUE THREAD

**Issue by bagder** [curl/curl#1898]
[found in current git master]

1. code on [mime.c:976](https://github.com/curl/curl/blob/master/lib/mime.c#L976) implies that `part`can be NULL in this loop.
2. `part` is passed into the `readback_part` function on [mime.c:980](https://github.com/curl/curl/blob/master/lib/mime.c#L980), where it gets dereferenced unconditionally (== potentially crashing).

So, either the pointer *can* be NULL and we should deal with it properly. Or it *can't* be NULL and then the check on line 976 is superfluous...

curl defects detected by Coverity can be seen here: https://scan.coverity.com/projects/curl/view_defects - you need to apply for "membership" first there to get proper permissions but I generally approve everyone.

I assign this to you @monnerat at once, as I believe you have the insights here!

**Comment by monnerat** [comment]
I don't think this is wrong:

- test at line 976 is in state MIMESTATE_BOUNDARY2, where part can be NULL after having flushed the final boundary. It does not move to MIMESTATE_CONTENT if part is NULL.
- call to readback_part() is in state MIMESTATE_CONTENT, where part can never be NULL.
- part is reset at the top of the loop (line 944).

This seems to be a coverity false positive. Maybe there is some way to silent it ? If not, I will reorganize this code.

**Comment by bagder** [comment]
> Maybe there is some way to silent it ?

Oh yes there is, I can mark it as "on purpose" or even "false positive". The question is possibly if there is a better way to write the code to make it more obvious to a reader, machine or human.

Maybe at a comment at the point `part` is assigned that says something about if it can be NULL or not for different states?

**Comment by monnerat** [comment]
Fixed (I hope!): a7bcf274ccf3dd6eca86c5fbdf2d568690e0c494

**Comment by bagder** [comment]
Awesome, Coverity is happy with that and we're now back to zero defects detected by Coverity. Thanks @monnerat!
