### ISSUE TITLE
coverity defect: 1418134 Explicit null dereferenced

### ISSUE THREAD

**Issue by bagder** [curl/curl#1899]
[present in current git master]

On [mime.c:1607](https://github.com/curl/curl/blob/master/lib/mime.c#L1607), there is an explicit use of a NULL pointer that will lead to a crash if executed.

It also tells me we have no test that exercises this code path...

(assigned to you @monnerat as I believe you have the clues on what the correct thing to would be here)

**Comment by monnerat** [comment]
Fixed, thanks.

> It also tells me we have no test that exercises this code path...

The code in the test should normally never be executed. It is a security in case it occurs, and I don't imagine right now how to force it: if the transfer is aborted while outputting curl-generated headers then restarted, new headers are generated before the calling code rewinds the mime structure, so this code is here to prevent an hypothetical reference to dangling old headers (this would imply output restarts without a mime rewind).

**Comment by bagder** [comment]
Fixed in f3042018686c0e565
