### ISSUE TITLE
curl_easy_perform fails while running in a loop after 200 times

### ISSUE THREAD

**Issue by VParande** [curl/curl#1901]
### I run this below code in my environment. After 200 time curl_easy_perform fails. It returns error code 7. The content hosted locally. 

~~~c
#include <stdio.h>
#include <curl/curl.h>

int main(void)
{
    CURL *curl;
    CURLcode res;
    int i;
    for(i=0; i<5000; i++)
    {
        curl = curl_easy_init();
        if(curl) {
            curl_easy_setopt(curl, CURLOPT_URL, "http://local_server.index.m3u8");
            curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
            
            res = curl_easy_perform(curl);

            if(res != CURLE_OK){
                printf ("res = %d\n",res);
                fprintf(stderr, "curl_easy_perform() failed: %s\n",curl_easy_strerror(res));
               curl_easy_cleanup(curl);
             }
        }
    }
    return 0;
}
~~~

### curl/libcurl version :  libcurl/7.50.1 OpenSSL/1.0.2h zlib/1.2.8

[curl -V output] : res = 7
curl_easy_perform() failed: Error

**Comment by jay** [comment]
Error 7 is [CURLE_COULDNT_CONNECT](https://curl.haxx.se/libcurl/c/libcurl-errors.html), "Failed to connect() to host or proxy." Turn on [CURLOPT_VERBOSE](https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html) or use [CURLOPT_ERRORBUFFER](https://curl.haxx.se/libcurl/c/CURLOPT_ERRORBUFFER.html) to get a better idea of what's happening. For connect specifically you could instead use [CURLINFO_OS_ERRNO](https://curl.haxx.se/libcurl/c/CURLINFO_OS_ERRNO.html) to see why connect failed.

**Comment by bagder** [comment]
The code doesn't cleanup the handle, but creates a new one in every iteration. It could mean that your server simply stops accepting more connections from the same IP after you have 200 opened connections to it...

Your loop should rather **re-use** the same curl handle for all 5000 transfers.

I can't see any bug in libcurl here...

**Comment by VParande** [comment]
But I am calling curl_easy_cleanup() every time. Is calling curl_easy_cleanup() doesn't clean up the handles?
Please suggest how to do clean up.

**Comment by VParande** [comment]
I don't think request reaching server, because i check TCP dump after 200 I did not see any request.

**Comment by bagder** [comment]
Then go back up and read @jay's [comment](https://github.com/curl/curl/issues/1901#issuecomment-330953186).

**Comment by VParande** [comment]
I re-used the same handle again and it fixed my issue.
Thank you helping me.
I am closing the issue.
