### ISSUE TITLE
CURLOPT_SSL_CTX_DATA example wrong

### ISSUE THREAD

**Issue by pwpo1999** [curl/curl#1907]
### I did this
I tested https://curl.haxx.se/libcurl/c/CURLOPT_SSL_CTX_DATA.html EXAMPLE Code
with "mypem variable" that modified to my own root ca cert 

### I expected the following
I expected to verify certificate success with my own root ca cert 

### curl/libcurl version
7.51.0 with OpenSSL 1.0.2

[curl -V output]
res = 77(CURLE_SSL_CACERT_BADFILE )

### operating system
Ubuntu Desktop 16.04

### check point
I set additional option "CURLOPT_CAINFO" to "NULL"
after, I got expected result.

**Comment by jay** [comment]
CURLOPT_CAINFO isn't used in that example so I don't see how the example is wrong. If you are using OpenSSL as your backend then CURLE_SSL_CACERT_BADFILE is only returned when there's an error setting the certificate verify locations. Use [CURLOPT_VERBOSE](https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html) and it will show you an error with the CAfile and CApath. One or both of those will be the problem.
