### ISSUE TITLE
pop3 download yields no data

### ISSUE THREAD

**Issue by libBletchley** [curl/curl#1914]
### I did this
```
curl -v --socks4a 127.0.0.1:9050 pop3://userid%40elude.in:password@eludemaillhqfkh5.onion/
```
I also tried a normal non-onion pop3 service, and results were the same.  But note in both cases I proxied over Tor.

### I expected the following

A local file in the current directory containing the new e-mail, or perhaps e-mail written straight to the terminal.  Instead, there was nothing written to the disk, and there was a one-line indication that a message exists, but it's not retrieved. 

The official documentation gives no pop3 examples.  The basis for my attempt was derived from this forum post:

https://curl.haxx.se/mail/lib-2010-06/0019.html

Consequently, I think it would be useful to have an example documented in a more organized way, perhaps in the man pages (after the bug is fixed, of course).  It would also be particularly useful to have documentation on how to delete retrieved messages from the server.

### curl/libcurl version

curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP 

### operating system

Jessie

**Comment by libBletchley** [comment]
I just tried adding a "1" to the end of the URL, apparently indicating the message number to download, and it worked.  So the documentation is simply wrong.  If anyone knows how to delete retrieved messages please mention it.

I'll leave the ticket open in case developers want to update the documentation, but it seems there is no bug in the code.

**Comment by libBletchley** [comment]
If examples are put in the documentation, this is what I suggest:

To list message numbers and sizes:
```
curl --netrc --url pop3://mail.bitmessage.ch/
```
To download message 1:
```
curl --netrc --url pop3://mail.bitmessage.ch/1
```
To delete message 1:
```
curl --netrc --request dele --url pop3://mail.bitmessage.ch/1
```
Note the `dele` command doesn't work ATM (see bug https://github.com/curl/curl/issues/1915)

**Comment by bagder** [comment]
Those examples are now mentioned in the [curl book](https://ec.haxx.se/usingcurl-reademail.html).
