### ISSUE TITLE
pop3 delete, list, and stat commands hang

### ISSUE THREAD

**Issue by libBletchley** [curl/curl#1915]
### I did this
```
curl -v --ssl-reqd --netrc --socks4a 127.0.0.1:9050\
  --request list\
  --url pop3://mail.bitmessage.ch/1
```
to list the first message.  It hung.  I also hung when "list" was replaced with "stat".  And to delete the first message, I did this:
```
curl -v --ssl-reqd --netrc --socks4a 127.0.0.1:9050\
  --request dele\
  --url pop3://mail.bitmessage.ch/1
```
When the dele command executes, it looks like this:
```
< +OK Mailbox locked and ready
> dele 1
< +OK msg deleted
```
but then hangs without committing.
### I expected the following
I expected the list command to show me the size of the first message and exit.  It indeed showed the size of the first message, but hung.  It did not exit, because apparently the pop3 server is waiting for cURL to do a `quit`.  Same problem for using the `dele` command to delete a message.  The message is marked for deletion, but not committed because the session hangs without sending a `quit`.

Note that I gathered information about the need for a `quit` at the end from this document:
https://www.stavros.io/tutorials/email/

### curl/libcurl version

curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

### operating system

jessie

**Comment by bagder** [comment]
We have done 27 releases since curl 7.38.0.

Test 858 in the test suite verifies that "DELE" works as intended (sends "DELE", gets "+OK", sends "QUIT"), so clearly something is working ok (in current versions - can't tell how it worked back in 7.38.0).

**Comment by bagder** [comment]
So, unless you can reproduce this problem in a recent version I'm going to assume that this has been fixed since 7.38.0...

**Comment by bagder** [comment]
Can't reproduce on current version.

**Comment by tester0077** [comment]
I am having the very same issue with curl under windows
curl 7.58.0 (i386-pc-win32) libcurl/7.58.0 zlib/1.2.8
Release-Date: 2018-01-24
I can issue the command
curl --request UIDL -u userxxxx:password --url pop3://pop.myisp.net
and get the expected output. 
curl --request STAT -u userxxxx:password --url pop3://pop.myisp.net
hangs
I am relatively new to curl itself and I have tested this problem in DOS Box on Win 10 because I had similar issues using the same version libcurl
