### ISSUE TITLE
mingw link errors

### ISSUE THREAD

**Issue by a101010** [curl/curl#1929]
building on windows 10 with MinGW (g++ v 6.3.0) I get the following link errors:

CMakeFiles\libcurl.dir/objects.a(timeval.c.obj):timeval.c:(.text+0xb5): undefined reference to `GetTickCount64'
CMakeFiles\libcurl.dir/objects.a(asyn-thread.c.obj):asyn-thread.c:(.text+0x228): undefined reference to `InitializeCriticalSectionEx'

additional information:
curl commit 6aa86c493bd77b70d1f5018e102bc3094290d588

commands used to build:
cmake -G "MinGW Makefiles" ..\curl\
mingw32-make

**Comment by a101010** [comment]
the correct answer seems to be: don't use cmake.
Instead, read docs/Install.md.
However, note that it says to run 'mingw32-make mingw32'
This seems to exist in the .zip source archive, but when building from the git repository you must use
mingw32-make -f Makefile.dist mingw32
There doesn't seem to be any information about creating a distribution after building that way.
default output is:
src/curl.exe
lib/libcurl.dll
lib/libcurl.a

**Comment by bagder** [comment]
[GIT-INFO](https://github.com/curl/curl/blob/master/GIT-INFO) contains that info.

**Comment by a101010** [comment]
Ah, yes, that does help. Thanks!
