### ISSUE TITLE
curl test of certificate pinning not work with sha1 digest

### ISSUE THREAD

**Issue by faeldix** [curl/curl#1931]
### I did this

> sha256
d9W9zyq64Gw8JEA/siAixfvoRRwZVpSgbYJV//0CeKM= (**generate by** openssl s_client -connect uol.com.br:443 | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64)

./curl --pinnedpubkey "sha256//d9W9zyq64Gw8JEA/siAixfvoRRwZVpSgbYJV//0CeKM=" https://uol.com.br
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://www.uol.com.br/">here</a>.</p>
</body></html>

> sha1
BQr5oEtKUmTzlcelRcWvGvMnQzk= (**generate by** openssl s_client -connect uol.com.br:443 | openssl x509 -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha1 -binary | openssl enc -base64)

./curl --pinnedpubkey "sha1//BQr5oEtKUmTzlcelRcWvGvMnQzk=" https://uol.com.br
curl: (90) SSL: public key does not match pinned public key!

### I expected the following

I expected the same result of sha256 test but i receive: **curl: (90) SSL: public key does not match pinned public key!**

### curl/libcurl version

./curl -V

curl 7.55.1 (x86_64-apple-darwin16.0.0) libcurl/7.55.1 SecureTransport zlib/1.2.8 Release-Date: 2017-08-14 Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

### operating system

Darwin Admins-MacBook-Pro.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
I'm sorry, but I find no documentation that says `sha1//` is a recognized prefix by curl. What makes you think curl supports that?

**Comment by faeldix** [comment]
Because no one error is throwed. But its true, in documentation only sha256 is used. 
Thank you for your response.
