### ISSUE TITLE
curl --remote-time, timestamp is wrong, one month too old

### ISSUE THREAD

**Issue by apiskors** [curl/curl#1940]
I am downloading gzipped files from an ftp server, which I believe is running MicroSoft Windows with NTFS.

When I download with command-line curl -R (--remote-time), it sets the WRONG timestamp on the file.  Interestingly, it appears to be exactly one month too old.  See examples further below.

TclCurl has the same problem (so presumably libcurl does as well).  When I do 'getinfo filetime', the time value I get is exactly one month too old.

When I use an interactive ftp client and do an ls -l, the remote timestamps are displayed correctly.

Conveniently, the files I am downloading happen to be gzipped.  Since gzip stores the original modification time inside the file, after I download them to my local Linux system, 'file' reports the correct original modification time, and 'gunzip' correctly sets the Linux mtime from that.  From this, I confirm that the wrong time really is EXACTLY one month too old, accurate to one second.

I am usuing Linux, Ubuntu 16.04.2 LTS, x86-64, with these software versions:

   curl 7.47.0, package curl, 7.47.0-1ubuntu2.2
libcurl 7.47.0, package libcurl4-openssl-dev, 7.47.0-1ubuntu2.2
TclCurl 7.22.0, package tclcurl, 7.22.0+hg201
 
$ curl -V 
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 libssh2/1.5.0 librtmp/2.3 
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp  
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets  

Example of the problem:

Filename         | Remote       | Downloaded   | clock format filetime     | getinfo filetime
-----------------|--------------|--------------|---------------------------|-----------------
file.20170920.gz | Sep 20 20:20 | Aug 20 20:20 | 2017-08-20 20:20:30 -0400 | 1503274830      
file.20170921.gz | Sep 21 20:17 | Aug 21 20:17 | 2017-08-21 20:17:28 -0400 | 1503361048      
file.20170922.gz | Sep 22 20:18 | Aug 22 20:18 | 2017-08-22 20:18:42 -0400 | 1503447522      
file.20170925.gz | Sep 25 20:06 | Aug 25 20:06 | 2017-08-25 20:06:06 -0400 | 1503705966      
file.20170926.gz | Sep 26 20:05 | Aug 26 20:05 | 2017-08-26 20:05:22 -0400 | 1503792322      
file.20170927.gz | Sep 27 20:13 | Aug 27 20:13 | 2017-08-27 20:13:58 -0400 | 1503879238      
file.20170928.gz | Sep 28 20:20 | Aug 28 20:20 | 2017-08-28 20:20:26 -0400 | 1503966026      
file.20170929.gz | Sep 29 20:15 | Aug 29 20:15 | 2017-08-29 20:15:56 -0400 | 1504052156

**Comment by apiskors** [comment]
More information:  Using the 'lftp' version 4.6.3a ftp client, when I do "ls -l" (or "rels -l") I see the correct remote timestamps, while "cls -l" (or "recls -l") gives me the wrong month-old ones.  Perhaps both lftp's "cls" and Curl are using the ftp MDTM command here, while the correct timestamp is coming from some other method.

**Comment by bagder** [comment]
@apiskors: add `-v` to your command line and investigate what curl sends and in particular what it receives in the response to the `MDTM` command. To me it sounds as if this server sends back a 213 with a month number that is one-off...

**Comment by apiskors** [comment]
I think the "213 20170829002026" response below after the MDTM is what you're after - it appears to give the wrong month-old date.  Removing passwords and such, curl -v  looks roughly like this:

```
< 220-CSI FTP server 
<     WarFTPd 1.81.01 (Aug  8 2002) Ready 
<     (C)opyright 1996 - 2002 by Jarle (jgaa) Aase - all rights reserved. 
 
> MDTM file.20170928.gz 
* ftp_perform ends with SECONDARY: 0 
< 213 20170829002026 
> EPSV 
* Connect data stream passively 
< 500 'EPSV': command not understood. 
* Failed EPSV attempt. Disabling EPSV 
> PASV 
```

**Comment by bagder** [comment]
> 213 20170829002026

Correct, this server says August 29, 2017...

**Comment by apiskors** [comment]
I will ask the server owner why his software is giving bogus responses to MDTM.

But is there some way to work around that on my end?  Where does the correct (but only precise to one minute) human-readable ls -l timestamp come from?  Is it possible to tell curl to fetch the timestamp with the ftp MLST command instead of MDTM ?
 
https://tools.ietf.org/html/rfc3659#section-7

**Comment by bagder** [comment]
that ls output is probably the normal `LIST` response, which is server-specific and traditionally a real pain for programs to parse since the format can be anything really.

**Comment by bagder** [comment]
As curl is clearly just representing what it gets from the server here, I consider this case closed for us!

**Comment by apiskors** [comment]
You're right, it's definitely the server's fault, not a bug in Curl.  It might merit an enhancement request.  E.g., an option to have Curl try to get file mtime and other info via the ftp MLST command instead of MDTM.

Thank you for responding so quickly to this!  Your pointers on how to debug, etc., were very helpful.

**Comment by bagder** [comment]
> It might merit an enhancement request

Right, I can see how you'd like to just try another code path but for a "weirdo" server like this, what are the odds that you'd get the another time back simply by using another command? Also, as `MDTM` is an older command it probably has a higher likelihood than `MLST` to work on a random server.

The time `MLST` is defined to return is even using the same format as the `MDTM` response, so I would guess that most server implementation would use the same function to generate those strings and thus both commands would return the same time stamp for the same path entry.

This said, I wouldn't reject work on adding support for MLST. I just probably won't work on it myself anytime soon.

**Comment by apiskors** [comment]
One minor addition to this closed ticket:  Now that it is the new year, that same buggy ftp server is responding to MDTM requests with the string "20180001224742", AKA the bogus date '2018-00-01 22:47:42' (double zero month).  Although that is an impossible date, it would be quite helpful for me to see it, and Tcl's 'clock scan' actually interprets it as 2017-12-01.  Unfortunately, TclCurl's 'getinfo filetime' returns only -1, presumably because it is using a stricter date parsing library.  It'd be nice to have a programmatic Curl option to get the original bogus date string directly from the server MDTM response, for working around buggy ftp servers like this.

**Comment by jay** [comment]
> Now that it is the new year, that same buggy ftp server is responding to MDTM requests with the string "20180001224742", AKA the bogus date '2018-00-01 22:47:42' (double zero month). Although that is an impossible date, it would be quite helpful for me to see it, and Tcl's 'clock scan' actually interprets it as 2017-12-01.

How do you know if it's 2017-12-01 or 2018-01-01? That doesn't make any sense. What server is it? Try running curl -X HELP or FEAT if there's no banner on login.

You're right that it's the date parser that won't accept that date. You could modify the [parsedate](https://github.com/curl/curl/blob/curl-7_57_0/lib/parsedate.c#L320-L332) function but that would affect parsing for all protocols. Rather I suggest you add a workaround in [ftp_state_mdtm_resp](https://github.com/curl/curl/blob/curl-7_57_0/lib/ftp.c#L2053-L2064) before parsedate is called. Say for example 2018-00-01 is actually supposed to be 2018-01-01 (again I don't know how you would know that), then it should be easy:

~~~diff
diff --git a/lib/ftp.c b/lib/ftp.c
index 8042edf..be29693 100644
--- a/lib/ftp.c
+++ b/lib/ftp.c
@@ -2056,6 +2056,9 @@ static CURLcode ftp_state_mdtm_resp(struct connectdata *conn,
         char timebuf[24];
         time_t secs = time(NULL);
 
+        if(month == 0)
+          month = 1;
+
         snprintf(timebuf, sizeof(timebuf),
                  "%04d%02d%02d %02d:%02d:%02d GMT",
                  year, month, day, hour, minute, second);
~~~

It's very unlikely such a change will make it upstream.

**Comment by bagder** [comment]
Handling illegal date formats would be a different issue, and yes I would be very hard to convince that curl should handle such abominations just like that!
