### ISSUE TITLE
libCurl build fails with CURL_DISABLE_CRYPTO_AUTH and USE_SSL (causes vtls.c to fail to compile)

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#1945]
### I did this

Defined both `CURL_DISABLE_CRYPTO_AUTH` and `USE_SSL`.

### I expected the following

A successful compilation. Instead I get the following errors:

```
1>vtls\vtls.c(1065): error C2065: 'MD5_context' : undeclared identifier
1>vtls\vtls.c(1065): error C2065: 'MD5pw' : undeclared identifier
1>vtls\vtls.c(1069): error C2065: 'MD5pw' : undeclared identifier
1>vtls\vtls.c(1069): error C2065: 'Curl_DIGEST_MD5' : undeclared identifier
1>vtls\vtls.c(1070): error C2065: 'MD5pw' : undeclared identifier
1>vtls\vtls.c(1072): error C2065: 'MD5pw' : undeclared identifier
1>vtls\vtls.c(1073): error C2065: 'MD5pw' : undeclared identifier
```

### curl/libcurl version

7.56.0

### operating system

Windows, Visual Studio 2017.

### A solution (but maybe not the best solution)

In vtls.c add `#ifndef CURL_DISABLE_CRYPTO_AUTH` around the `Curl_none_md5sum` function. Then set `Curl_ssl_multi` md5sum parameter to `NULL` (instead of `Curl_none_md5sum`). Do the same for `Curl_ssl_schannel` md5sum parameter.

**Comment by toonetown** [comment]
I am also seeing this when compiling for android, iOS, or macOS.

**Comment by bagder** [comment]
Let me know if (any of) you have any feedback or comments on my proposed fix. If not, I'll merge it soonish.

**Comment by wyattoday** [comment]
Everything works now, thanks.

**Comment by bagder** [comment]
Thanks!
