### ISSUE TITLE
Build 7.56.0  fails on CentOS 5.11 i686 and x64 

### ISSUE THREAD

**Issue by javyer** [curl/curl#1955]
### I did this
./configure --enable-shared=yes --with-ssl
make
...
  CC       vtls/libcurl_la-openssl.lo
vtls/openssl.c: In function ‘cert_stuff’:
vtls/openssl.c:845: error: implicit declaration of function ‘EVP_PKEY_id’
make[2]: *** [vtls/libcurl_la-openssl.lo] Error 1
make[2]: Leaving directory `/tmp/curl-7.56.0/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/curl-7.56.0/lib'
make: *** [all-recursive] Error 1
### I expected the following

build without errors

### curl/libcurl version
curl 7.56.0, Released on the 4th of October 2017.
curl-7.56.0.tar.gz

[curl -V output]
N/A
### operating system
CentOS release 5.11 (Final)
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008 
rpm openssl-devel-0.9.8e-40.el5_11 & openssl-0.9.8e-40.el5_11 (official)
gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)
Copyright (C) 2006 Free Software Foundation, Inc.

**Comment by bagder** [comment]
Please let me know how/if the #1956 fix works for you!

**Comment by javyer** [comment]
Thanks Badger, it builds ;-)
