### ISSUE TITLE
Segfault when add mime as subpart to itself

### ISSUE THREAD

**Issue by moteus** [curl/curl#1962]
### I did this
``` C
curl_mime *mime = curl_mime_init(easy);
curl_mimepart *part = curl_mime_addpart(mime);
CURLcode a1 = curl_mime_subparts(part, mime);
curl_mime_free(mime);
```

### I expected the following
`curl_mime_free(mime);` should not crash but `curl_mime_subparts(part, mime);` should returns `CURLE_BAD_FUNCTION_ARGUMENT` and do nothing.

### curl/libcurl version
curl 7.56.0 (i386-pc-win32) libcurl/7.56.0 WinSSL
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
Windows 7 x64

**Comment by bagder** [comment]
I'm not convinced this is something we _have_ to protect against, but it should be easy to at least prevent this bad use.

**Comment by bagder** [comment]
Let me know what you think of this fix!
