### ISSUE TITLE
unknown type name 'MD5_context'

### ISSUE THREAD

**Issue by ben29** [curl/curl#1972]
Centos 7.1 last version
trying to do make for curl version 7.56.0

configure options:

```
./configure \
	--disable-debug \
	--disable-dict \
	--disable-ipv6 \
	--disable-telnet \
	--disable-ftp \
	--disable-tftp \
	--disable-crypto-auth
```

>  CC       vtls/libcurl_la-vtls.lo
> vtls/vtls.c: In function 'Curl_none_md5sum':
> vtls/vtls.c:1065:3: error: unknown type name 'MD5_context'
>    MD5_context *MD5pw;
>    ^
> vtls/vtls.c:1069:3: error: implicit declaration of function 'Curl_MD5_init' [-Werror=implicit-function-declaration]
>    MD5pw = Curl_MD5_init(Curl_DIGEST_MD5);
>    ^
> vtls/vtls.c:1069:25: error: 'Curl_DIGEST_MD5' undeclared (first use in this function)
>    MD5pw = Curl_MD5_init(Curl_DIGEST_MD5);
>                          ^
> vtls/vtls.c:1069:25: note: each undeclared identifier is reported only once for each function it appears in
> vtls/vtls.c:1072:3: error: implicit declaration of function 'Curl_MD5_update' [-Werror=implicit-function-declaration]
>    Curl_MD5_update(MD5pw, input, curlx_uztoui(inputlen));
>    ^
> vtls/vtls.c:1073:3: error: implicit declaration of function 'Curl_MD5_final' [-Werror=implicit-function-declaration]
>    Curl_MD5_final(MD5pw, md5sum);
>    ^
> cc1: some warnings being treated as errors
> make[2]: *** [vtls/libcurl_la-vtls.lo] Error 1

**Comment by bagder** [comment]
Same as #1945 ?

**Comment by ben29** [comment]
yea, I did the patch it's working...

**Comment by bagder** [comment]
Lovely, thanks for confirming!
