### ISSUE TITLE
use of --fail hides http headers/body

### ISSUE THREAD

**Issue by lexinator** [curl/curl#1978]
### I did this
```
% curl --fail --dump-header - --request POST --data-urlencode foo=bar 127.0.0.1:9999
curl: (22) The requested URL returned error: 403 Forbidden
% echo $?
22
```
### I expected the following
```
% curl --fail --dump-header - --request POST --data-urlencode foo=bar 127.0.0.1:9999
HTTP/1.0 403 Forbidden
Server: foo/1.0
Date: Tue, 10 Oct 2017 16:36:03 GMT
Content-type: text/html

<html><body><h1>POST!</h1></body></html>

%echo $?
22
```

### curl/libcurl version

[curl -V output]
```
% curl -V
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```
### operating system
```
% uname -a
Darwin sequel 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by bagder** [comment]
You're actually using and experiencing `--fail` exactly as it is intended to work, how it is documented to work and how it has worked since its introduction some 15 years ago.

**Comment by lexinator** [comment]
ok i guess that means I'm requesting a new option that behaves like this?

**Comment by jay** [comment]
What's your use case? You could use [--write-out](https://curl.haxx.se/docs/manpage.html#-w) to save the http code in a variable, which is easy as long as you are redirecting the server output somewhere. If you for some reason you want server output to go directly to stdout then I think you'd have to open a separate file descriptor like [this](https://superuser.com/a/862395).

**Comment by lexinator** [comment]
my use case is to capture the http body and have a non zero exit code for non 2xx status codes.

thanks for the tip/link as that seems like the path I'll have to go down if I want to do this with existing curl version.

**Comment by lexinator** [comment]
so i guess that means i don’t get a new flag doing the more straight forward solution?

**Comment by bagder** [comment]
No, I find it very hard to motivate a new flag with a functionality that is so close to the existing functionality, and when you can achieve what you want with very little extra effort on your behalf.

**Comment by lexinator** [comment]
ok. thanks for your reply.
