### ISSUE TITLE
Tests 600 and 601 fail on Travis with `set -eo pipefail` for some jobs

### ISSUE THREAD

**Issue by cmeister2** [curl/curl#1983]
### I did this
PR for #1966. https://travis-ci.org/curl/curl/jobs/285946126 failed.

### I expected the following
Tests 600 and 601 not to fail: https://travis-ci.org/curl/curl/jobs/285946126#L7955

This is perhaps because the coverage build uses Precise, where everything else uses Trusty: https://github.com/curl/curl/blob/master/.travis.yml#L69

### curl/libcurl version
devel

**Comment by bagder** [comment]
Those are memory leaks in that old libssh2 version I believe are already fixed in a later version. Tricky to deal with but should ideally probably be able to blacklist somehow.

**Comment by cmeister2** [comment]
For whenever in the future this gets fixed; the relevant lines from .travis.yml need uncommenting: https://github.com/curl/curl/blob/master/.travis.yml#L115

**Comment by bagder** [comment]
Doesn't seem to happen (anymore) in https://github.com/curl/curl/pull/2541 now merged to master
