### ISSUE TITLE
html page when downloaded  from https isn't complete  with loss of data

### ISSUE THREAD

**Issue by moh-hassan** [curl/curl#1984]
### I did this
		curl -v -k -S -o api.html  "https://docs.microsoft.com/en-us/dotnet/api/?view=netstandard-2.0&term=System.Runtime.Serialization.DataContractSerializer"

### I expected the following
I expect downloading a complete html page and  saved to the file api.html with data in the tags 
			<table class="api-search-results" .... />
Like what I get in firefox or IE 
but the page api.html is downloaded with information loss of the tags  <table class="api-search-results" .... /> 			

### curl version
[curl -V output]

curl 7.46.0 (i386-pc-win32) libcurl/7.46.0 OpenSSL/1.0.2e zlib/1.2.8 WinIDN libssh2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtspscp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz

### operating system
Window 7 SP1

### curl trace
[curl trace](https://pastebin.com/raw/SC1WQGQ4)

**Comment by jay** [comment]
That's not a curl problem you have to use their docs API, which I'd guess is documented somewhere but I don't know where. I used Fiddler web debugger to see it in action, the search queries look like this:

curl -fLsS "https://docs.microsoft.com/api/apibrowser/dotnet/search?api-version=0.2&search=System.Runtime.Serialization.DataContractSerializer&$filter=monikers/any(t:%20t%20eq%20%27netstandard-2.0%27)"

**Comment by moh-hassan** [comment]
Thanks for help.
The docs API haven't yet REST API, and i request this feature [user voice](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/31843894-support-the-net-api-browser-as-a-service-and-p)
