### ISSUE TITLE
Undocumented behavior in `curl_formget`

### ISSUE THREAD

**Issue by moteus** [curl/curl#1987]
### I did this
```C
static size_t abort_writer(void *arg, const char *buf, size_t len){
  return 0;
}

static void test_form_write_abort(){
  struct curl_httppost *post=NULL, *last=NULL;
  char name[] = "name"; size_t name_len = sizeof(name) - 1;
  char cont[] = "data"; size_t cont_len = sizeof(cont) - 1;

  CURLcode code = curl_formadd(&post, &last,
    CURLFORM_PTRNAME,     name, CURLFORM_NAMELENGTH,   (long)name_len,
    CURLFORM_PTRCONTENTS, cont, LCURL_FORM_CONTENTLEN, (LCURL_LEN_TYPE)cont_len,
    CURLFORM_CONTENTTYPE, "text/plain",
    CURLFORM_END);

  code = curl_formget(post, NULL, abort_writer);
  // libcurl < 7.56.0 returns -1
  // libcurl 7.56.0 return CURLE_READ_ERROR
}
```

### I expected the following
I think documentation should describe what behaviour is correct.

### curl/libcurl version

libcurl 7.56.0

**Comment by bagder** [comment]
The man page for `curl_formget` says:

> "0 means everything was ok, non-zero means an error occurred"

... and for all I can tell, that is still true...

**Comment by moteus** [comment]
I mean document error code when `curl_formget_callback` reutrns 0.
Like `CURLE_ABORTED_BY_CALLBACK` when read callback returns `CURL_READFUNC_ABORT`
or somethink like this.
But if it is not defined except `not zero` i can live with that.

**Comment by bagder** [comment]
`curl_formget` is not even documented to return a `CURLcode`, just an int. I'm not sure its worth the effort to document its return codes  to any further extent then it currently is. This function is very rarely used, and the new mime API doesn't even have a version of it.
