### ISSUE TITLE
[regression] CURLFORM_CONTENTTYPE "plain/text" gets dropped

### ISSUE THREAD

**Issue by jeroen** [curl/curl#1989]
As of curl 7.56, setting `CURLFORM_CONTENTTYPE` to `"text/plain"` does not work: the value will not be included in the multipart. Setting any other value than `text/plain` does work. For example:

```c
curl_formadd(&post, &last, CURLFORM_COPYNAME, "val", CURLFORM_COPYCONTENTS, "This is a test", CURLFORM_CONTENTTYPE, "text/plain", CURLFORM_END);
```

In curl 7.54.1 this posts:

```
--------------------------c7f57e6483f9c3db
Content-Disposition: form-data; name="val"
Content-Type: text/plain

This is a test
--------------------------c7f57e6483f9c3db--
```

In curl 7.56.0 I get:
```
--------------------------4c3a52f30efe7cf7
Content-Disposition: form-data; name="val"

This is a test
--------------------------4c3a52f30efe7cf7--
```

Setting any other value than `"text/plain"` does seem to work. Is this intended?

**Comment by bagder** [comment]
and 0401734dfd doesn't fix this?

**Comment by jeroen** [comment]
Ah probably does thanks! I was testing from your branch https://github.com/curl/curl/pull/1988 which did not include that fix yet....

**Comment by jeroen** [comment]
Assuming this is a dupe.
