### ISSUE TITLE
curl_mime_data does not change Content-Length when change data after perform

### ISSUE THREAD

**Issue by moteus** [curl/curl#1999]
### I did this
I create mime with simple text then I did perform and curl correcly send data.
After that I change data in text part but when I did perform again curl
send Content-Length for first data. If I change data without doing perform then
curl send correct Content-Length. This is my snippet on Lua, but I think
it quite easy to understand.

```Lua
local easy = curl.easy()
local mime = easy:mime()

easy:setopt{
  url            = "http://127.0.0.1:7090/get";
  customrequest  = "GET";
  mimepost       = mime;
  writefunction  = function()end;
}

local part = mime:addpart()

part:data('1234567890')
easy:perform() -- here curl send Conten-Length: 136 (which is correct)

part:data('abcd')
easy:perform() -- here curl send same Conten-Length: 136 but data size is 130
```

### I expected the following
I expected that curl send correct Content-Length

### curl/libcurl version

libcurl/7.56.0 WinSSL

### operating system

Windows 7 x64

**Comment by monnerat** [comment]
Many tanks for the report: the bug is confirmed.
I will produce a fix and a test case in the next hours.

**Comment by monnerat** [comment]
Fix pushed: https://github.com/curl/curl/commit/cea27d3454114a663e96099f9944333b3232b392
Test for this case: https://github.com/curl/curl/commit/8351ab45105c3e58c38205c045477198ff887829
