### ISSUE TITLE
libcurl: Disconnect after custom request (MLSD) (C++)

### ISSUE THREAD

**Issue by dlodyakov** [curl/curl#2000]
### I did this
Send custom request with MLSD command
### I expected the following
Command works fine, but curl disconnect me after it, and don't disconnect after LIST
### curl/libcurl version
Curl and libcurl 7.57.0
[curl -V output]

### operating system
Windows 10

**Comment by gvanem** [comment]
Can you show some `CURLOPT_VERBOSE` output? 
Maybe changing to FTP-Active mode would help.

**Comment by dlodyakov** [comment]
Trying 127.0.0.1...
TCP_NODELAY set
Connected to localhost (127.0.0.1) port 21 (#0)
220-FileZilla Server 0.9.60 beta
220-written by Tim Kosse (tim.kosse@filezilla-project.org)
220 Please visit https://filezilla-project.org/
220-written by Tim Kosse (tim.kosse@filezilla-project.org)
220 Please visit https://filezilla-project.org/
220 Please visit https://filezilla-project.org/
USER user
331 Password required for user
la-project.org/
PASS user@user.user
230 Logged on
quired for user
PWD
257 "/" is current directory.
Entry path is '/'
EPSV
Connect data stream passively
229 Entering Extended Passive Mode (|||53631|)
  Trying 127.0.0.1...
TCP_NODELAY set
Connecting to 127.0.0.1 (127.0.0.1) port 53631
ftp_perform ends with SECONDARY: 0
Connected to localhost (127.0.0.1) port 21 (#0)
TYPE A
200 Type set to A
ed Passive Mode (|||53631|)
RETR response: 211
Remembering we are in dir ""
Connection #0 to host localhost left intact
Found bundle for host localhost: 0x11935f7b3e0 [serially]
Re-using existing connection! (#0) with host localhost
Connected to localhost (127.0.0.1) port 21 (#0)
Request has same path as previous transfer
EPSV
Connect data stream passively
  Trying 127.0.0.1...
TCP_NODELAY set
Connecting to 127.0.0.1 (127.0.0.1) port 62709
ftp_perform ends with SECONDARY: 0
Connected to localhost (127.0.0.1) port 21 (#0)
OPTS UTF8 ON
202 UTF8 mode is always enabled. No need to send this command.
RETR response: 202
Remembering we are in dir ""
Connection #0 to host localhost left intact
Found bundle for host localhost: 0x11935f7b3e0 [serially]
Re-using existing connection! (#0) with host localhost
Connected to localhost (127.0.0.1) port 21 (#0)
Request has same path as previous transfer
EPSV
Connect data stream passively
229 Entering Extended Passive Mode (|||58018|)
 this command.
  Trying 127.0.0.1...
TCP_NODELAY set
Connecting to 127.0.0.1 (127.0.0.1) port 58018
ftp_perform ends with SECONDARY: 0
Connected to localhost (127.0.0.1) port 21 (#0)
CLNT Clinet_Name
200 Don't care
ended Passive Mode (|||58018|)
RETR response: 200
Remembering we are in dir ""
Connection #0 to host localhost left intact
Found bundle for host localhost: 0x11935f7b3e0 [serially]
Re-using existing connection! (#0) with host localhost
Connected to localhost (127.0.0.1) port 21 (#0)
Request has same path as previous transfer
Wildcard - Parsing started
EPSV
Connect data stream passively
229 Entering Extended Passive Mode (|||49332|)
 this command.
  Trying 127.0.0.1...
TCP_NODELAY set
Connecting to 127.0.0.1 (127.0.0.1) port 49332
ftp_perform ends with SECONDARY: 0
Connected to localhost (127.0.0.1) port 21 (#0)
MLSD
150 Opening data channel for directory listing of "/"
226 Successfully transferred "/"
Maxdownload = -1
type=dir;modify=20171011123205; AppData
type=dir;modify=20171019073155; Projects
type=dir;modify=20171011123108; System Volume Information
type=dir;modify=20171019155748; Temp
Remembering we are in dir ""
226 Successfully transferred "/"
pData
type=dir;modify=20171019073155; Projects
type=dir;modify=20171011123108; System Volume Information
type=dir;modify=20171019155748; Temp
Connection #0 to host localhost left intact
Found bundle for host localhost: 0x11935f7b3e0 [serially]
Re-using existing connection! (#0) with host localhost
Connected to localhost (127.0.0.1) port 21 (#0)
Closing connection 0

**Comment by bagder** [comment]
> Connection #0 to host localhost left intact

To me, that sounds like the connection was left open.

Then you seem to do a second request immediately following, that closes the connection. I presume because of some sort of failure/abort.

Please provide a recipe on how we can reproduce this issue!

**Comment by dlodyakov** [comment]
This is my code

```
void FtpThread::initCurl()
{
    curl_easy_setopt(_curl, CURLOPT_NOBODY, 0L);
    curl_easy_setopt(_curl, CURLOPT_HEADER, 0L);

    curl_easy_setopt(_curl, CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(_curl, CURLOPT_STDERR, 0L);

    curl_easy_setopt(_curl, CURLOPT_DEBUGFUNCTION, ftp_trace);
    curl_easy_setopt(_curl, CURLOPT_DEBUGDATA, this);

    curl_easy_setopt(_curl, CURLOPT_CHUNK_BGN_FUNCTION, file_is_coming);

    curl_easy_setopt(_curl, CURLOPT_WRITEFUNCTION, write_to_file);

    curl_easy_setopt(_curl, CURLOPT_CHUNK_DATA, this);
    curl_easy_setopt(_curl, CURLOPT_WRITEDATA, this);

    curl_easy_setopt(_curl, CURLOPT_CUSTOMREQUEST, 0);
    curl_easy_setopt(_curl, CURLOPT_WILDCARDMATCH, 1L);

    curl_easy_setopt(_curl, CURLOPT_FTP_FILEMETHOD, CURLFTPMETHOD_SINGLECWD);
}

void getFiles(...)
{
    initCurl();

    curl_easy_setopt(_curl, CURLOPT_URL, _url.toUtf8().constData());

    if (_opts[FO_MLSD]) // TODO: Bug (?) disconnect after CUSTOMREQUEST
    {
        rc = curl_easy_setopt(_curl, CURLOPT_CUSTOMREQUEST, "MLSD");
    }
    else
    {
        curl_easy_setopt(_curl, CURLOPT_CUSTOMREQUEST, 0);
    }

    rc = curl_easy_perform(_curl);
}
```

**Comment by bagder** [comment]
I can't reproduce a disconnect using `MLSD`. But since you're asking for wildcard matching, selecting a command different than `LIST` will most likely cause the parser to not match anything since it is made to parse `LIST` outputs and nothing else.

**Comment by bagder** [comment]
If you (or anyone else) can provide a full example that reproduces this problem we can open it again. Thanks!
