### ISSUE TITLE
curl -L is not following 302 Location header using GET when using -XPOST

### ISSUE THREAD

**Issue by ryanflegel** [curl/curl#2007]
### I did this

I used `curl --location -XPOST` command line to post to a URL and follow the Location.

### I expected the following

I expected the URL in the Location header to be fetched with GET, but curl is fetching it with POST. The response status is 302.

I've tried with 301/302/303 status and PUT/POST methods.

From the curl manpage:

> When curl follows a redirect and the request is not a plain GET (for example POST or PUT), it will do the following request with a GET  if  the  HTTP  response  was  301,  302, or 303. If the response code was any other 3xx code, curl will re-send the following request using the same unmodified method.
>
> You can tell curl to not change the non-GET request method to GET after a 30x response by using the dedicated  options  for  that:
> --post301, --post302 and -post303.

Unless I've missed something, this behaviour seems contradictory to the manpage. It seems like `--post302` (for example) should be required to get the behaviour I'm seeing.

I've created a script that demonstrates the issue ([curl-redir.sh.txt](https://github.com/curl/curl/files/1408440/curl-redir.sh.txt)) and included the script output ([curl-redir.txt](https://github.com/curl/curl/files/1408436/curl-redir.txt)). You can see that the second request is a POST to http://localhost:9991/ instead of a GET.

### curl/libcurl version

I've tried three versions (7.43.0, 7.35.0, 7.15.5) on three different OS's and get the same behaviour.

```
sw_vers && echo && uname -a && echo && curl -V
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108

Darwin myhost 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSocket
```

```
$ lsb_release -sri && echo && uname -a && echo && curl -V
Ubuntu
12.04

Linux myhost 3.2.61-grsec-modsign #1 SMP Tue Aug 12 09:58:26 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

```
$ lsb_release -sir && echo && uname -a && echo && curl -V
RedHatEnterpriseServer 5.11

Linux myhost 2.6.18-419.el5 #1 SMP Wed Feb 22 22:40:57 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

### operating system

OS X, Ubuntu and RHEL (see previous section).

**Comment by bagder** [comment]
This is documented behavior as described in the [-X](https://curl.haxx.se/docs/manpage.html#-X) man page section:

> The method string you set with -X, --request will be used for all requests, which if you for example use -L, --location may cause unintended side-effects when curl doesn't change request method according to the HTTP 30x response codes - and similar.
