### ISSUE TITLE
--max-redirs -1 leads to error "bad argument"

### ISSUE THREAD

**Issue by cbartl** [curl/curl#2038]
### I did this

curl --max-redirs -1 http://dummy.restapiexample.com/api/v1/employees

### I expected the following

Get a JSON with HTTP status 200

### instead got the following

> curl: (43) A libcurl function was given a bad argument

### curl/libcurl version

```
curl 7.56.1 (x86_64-suse-linux-gnu) libcurl/7.56.1 OpenSSL/1.0.2l zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.27.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy Metalink PSL 
```

### operating system

openSUSE Tumbleweed

### Notes

Use `--max-redirs 9999` instead of `-1` as workaround.

Did a little research and found commit f121575c0b5fe4bc10371c993bcb78fec23428ec to be a candidate for cause.

```c
  case CURLOPT_MAXREDIRS:
    /*
     * The maximum amount of hops you allow curl to follow Location:
     * headers. This should mostly be used to detect never-ending loops.
     */
    arg = va_arg(param, long);
    if(arg < 0)
      return CURLE_BAD_FUNCTION_ARGUMENT;
    data->set.maxredirs = arg;
    break;
```

**Comment by bagder** [comment]
Confirmed. Patch coming...
