### ISSUE TITLE
PHP curl through proxy generating high CPU load

### ISSUE THREAD

**Issue by ztmztm** [curl/curl#2040]
After investigating the reasons for the high CPU load generated by an application sending many curl requests with 20 parallel PHP-cli scripts, I've found out the main reason is the PROXY option set to the curl handle.

The following code is generating a 0.5-1.5% CPU load at the moment of curl_exec when run without the proxy and 12-25% when using any proxy (I've tried many different ones).

With many threads running many requests at the same time, it soon becomes critical.

I'm using: 
Ubuntu 16.04 
PHP 7.0.22 
curl 7.55.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 libssh2/1.8.0
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

Is there a fix or workaround I can apply?

$address = 'xxx';
$port = 'xxx';
$url = 'https://api.ipify.org?format=json';

do {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_ENCODING, 'identity');
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_PROXY, $address);
    curl_setopt($ch, CURLOPT_PROXYPORT, $port);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_exec($ch);
    curl_close($ch);
    sleep(10);

} while (true);

**Comment by bagder** [comment]
I assume `$address` is a HTTP proxy (address)?

**Comment by ztmztm** [comment]
Yes, $address and $port are for a working proxy. I tried different ones, just to be sure.

**Comment by bagder** [comment]
> $address and $port are for a working proxy

For a working **HTTP** proxy was more what I asked about? As in not *HTTPS* or *SOCKS* ...

**Comment by ztmztm** [comment]
I have used multiple proxies from 2 different batches. On the FAQs of the first supplier I read "These are HTTP/HTTPS & Socks 4/5 proxies.", I can't find out for the second batch.

I am just using the code above and connecting to HTTPS URLs. What can I check to give you further info about this topic?

**Comment by bagder** [comment]
If you didn't specify what proxy type it was (with a scheme part), they were treated as HTTP proxies.

So how large resources did you download? The handshake over a HTTP proxy is certainly going to be more CPU consuming than without a proxy, but if you download huge contents the handshake will drown among the rest. What's the RTT to the proxy from your host?

If you run the same thing with the curl command line tool, can you reproduce the same issue?

**Comment by ztmztm** [comment]
The URL just returns a JSON with the request source IP, you can try it: https://api.ipify.org?format=json

I tried multiple proxies, the last one returns the ping in 9 ms.

I'm not sure if the test is valid, but I've tried with the two following commands and they both look to use 0.7% CPU max, so the issue does not seem to apply to command line curl.

Any suggestion about the possible cause when using via PHP?

**Comment by ztmztm** [comment]
It does not look to be happening with this option:
curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);

Also, it does not seem possible to set HTTPS as proxy type in PHP.

**Comment by bagder** [comment]
> Also, it does not seem possible to set HTTPS as proxy type in PHP.

The CURL binding for PHP is maintained by the PHP team, not the curl project. So that comment/issue is better reported to them. The curl project makes the libcurl library and the curl command line tool.

**Comment by ztmztm** [comment]
Yes, of course :)
I'll report the bug to PHP then, as it only seems to be happening when PHP is using curl.
Thanks for the support

**Comment by jay** [comment]
When you file with them please tell us the link here so we can track it
