### ISSUE TITLE
some of webpages blocks my curl request & showing 503 service temp. not available

### ISSUE THREAD

**Issue by prafullwizorbit** [curl/curl#2041]
I hit some url directly to my crome browser then it work perfectly but when i send request of that url using curl then it show nothing & like 503 service temp. not available. 

so anyone please suggest me how to treat my curl like real browser activity & get unblock. I don't know either target server block my ip, or track my user agent etc.I will highly thankfull if any one suggest any help regrading this.

Thanks

**Comment by bagder** [comment]
I appreciate that you're experiencing a problem with repeating a browser request here, but there's no sign or indication of this being a curl bug so this is not the place for this discussion.

I would recommend "copy as curl" in Firefox or Chrome as a starting point, or even [h2c](https://curl.haxx.se/h2c/), and if none of those helps I would recommend asking on a curl mailing list (curl-users if you use the command line tool, curl-library if you use the libcurl library).

**Comment by prafullwizorbit** [comment]
Thanks for quick answer.
