### ISSUE TITLE
-f option is mutually exclusive of needing authentication

### ISSUE THREAD

**Issue by brianjmurrell** [curl/curl#2042]
### I did this
curl -f --proxy-negotiate -x http://proxy.example.com:3128 $URL

### I expected the following
To fetch $URL via the proxy with Negotiatie

### curl/libcurl version
$ curl --version
curl 7.53.1 (x86_64-redhat-linux-gnu) libcurl/7.53.1 NSS/3.33 zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.3) libssh2/1.8.0 nghttp2/1.21.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink PSL 

### operating system
Fedora Linux

Instead of fetching `$URL`, `curl` returned an error due to the proxy returning 407 and curl's `-f` parameter.

Should 407 really be a response that triggers `-f`?

**Comment by bagder** [comment]
That's not why your command line doesn't work. You need to use `-U` to trigger proxy authentication to get used.

**Comment by brianjmurrell** [comment]
The `-U` argument is in my `~/.curlrc` file.  To be absolutely clear about what is not working vs. what is:

```
$ curl -H "Pragma:" --proxy-negotiate -x http://proxy.example.com:3128 -u : -f -o /dev/null $URL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 407 Proxy Authentication Required

$ curl -H "Pragma:" --proxy-negotiate -x http://proxy.example.com:3128 -u : -o /dev/null $URL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3643  100  3643    0     0   471k      0 --:--:-- --:--:-- --:--:--  508k
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

**Comment by jay** [comment]
It's not supposed to do that if you've specified _proxy authentication_. Code:

https://github.com/curl/curl/blob/c514af5a4f5ac3ce724065cc6a8e009373436f78/lib/http.c#L3416-L3426

as you can see there it fails if 407 and there's no proxy username and password. are you sure you specified the uppercase -U and not the lowercase -u in your rc? It may be easier to understand which is which if you use [`--proxy-user`](https://curl.haxx.se/docs/manpage.html#-U) instead of `-U`.

**Comment by brianjmurrell** [comment]
Oh wow.  That's a long-standing issue with my `~/.curlrc`!:

```
$ cat ~/.curlrc 
-H "Pragma:"
--proxy-negotiate
-x http://proxy.example.com:3128
-u :
```

That last line of course should be a `-U :` and unsurprisingly, when I fix that, this problem goes away.

That error in my `~/.curlrc` has gone unnoticed for what has to be years now.  Apologies for the noise.
