### ISSUE TITLE
Conan package for libcurl

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [curl/curl#2049]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by bagder** [comment]
I'm sorry, but no.

The curl project doesn't make or provide *any* binary packages at all. We ship source code archives. We hope that those who like and want to provide binary curl and libcurl packages will do that - and we're grateful to those who do. We're also very happy to point out all those other packages and downloads from our web page.

**Comment by gvanem** [comment]
> Do you know about Conan package manager? 

Never heard of it. But I just installed it and tried some stuff. It looks awesome!
