### ISSUE TITLE
Curl do not give a newline after uploading files using --upload-file option

### ISSUE THREAD

**Issue by lzzy12** [curl/curl#2050]
However this one is a very minor problem but is annoying and considerable.
I did the following :  
`root@x24v7:/home/jhashivam2020/ak# curl --upload-file LegendKernel_j7velte.zip https://transfer.sh/LegendKernel_j7velte.zip`
and it returned me this : 
`https://transfer.sh/SuNfV/LegendKernel_j7velte.ziproot@x24v7:/home/jhashivam2020/ak# `

So as you can see there's no newline after url and the host name which is sometimes very annoying. 
Hope you people will fix it soon

**Comment by bagder** [comment]
curl doesn't add any extra output it just outputs what it gets from the server, so if the remote response doesn't end with a newline, that's the expected outcome. That's intended and by design.

**Comment by lzzy12** [comment]
@bagder 
But, I think you can do a small change here. You can code the tool to give a newline after curl receives the response from server. However that depends completely on you whether you will do it or not. 
Thanks

**Comment by bagder** [comment]
Sure, its just code so we can make it do whatever we think is right. But I don't think adding a newline to the output is the right thing. I think curl should show/output *exactly* what it gets from the server and nothing else.
