### ISSUE TITLE
curl --upload-file . hang if delay in STDIN

### ISSUE THREAD

**Issue by bdry** [curl/curl#2051]
### I did this

`(echo start; sleep 1; echo end) | curl --upload-file . http://mywebsite -vv`

Curl hang

### I expected the following

Working upload of stdin

### curl/libcurl version

```
curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.56.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.8.0 nghttp2/1.26.0 librtmp/2.3
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system

Debian GNU/Linux buster/sid

```
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  curl           7.56.1-1     amd64        command line tool for transferrin
```

**Comment by mkauf** [comment]
Same bug as #932 (I think that issue should not have been closed without a solution)

**Comment by bagder** [comment]
@mkauf open bugs with no action makes no sense to keep open, that only clutters our tracker. Clearly nobody cared about the bug enough to take it anywhere. It should probably have been added to the `KNOWN_BUGS` document though.
