### ISSUE TITLE
imap CURLOPT_CUSTOMREQUEST Callback or printout data incomplete

### ISSUE THREAD

**Issue by yizhanfinish** [curl/curl#2055]
imap c++ Use  curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[1]")
Callback or printout data incomplete
I think my system has problems, and the replacement system compilation problem still exists.

**Comment by bagder** [comment]
> Callback or printout data incomplete

Can you please clarify and elaborate what exactly this means? What did you expect to get and what did you get instead?

What libcurl version on what platform are you using?

**Comment by yizhanfinish** [comment]
hello!
  I use the platform is windows10，
  in Visual Studio 2017 c++compiled return incomplete data error，


`#include <iostream>
#include <curl/curl.h>
#include <string>
using namespace std;

size_t httpDataWriter(void* buffer, size_t size, size_t nmemb, void* content)
{
	long totalSize = size*nmemb;
	std::string* symbolBuffer = (std::string*)content;
	if (symbolBuffer)
	{
		symbolBuffer->append((char *)buffer, ((char*)buffer) + totalSize);
		return size * nmemb;
	}
	else
	{
		printf("ClusterCurl httpDataWriter data error(%d) \n", errno);
		return 0;
	}

}



int main(void)
{
	CURL *curl;
	CURLcode res = CURLE_OK;
	string data;
	curl = curl_easy_init();
	if (curl) {
		curl_easy_setopt(curl, CURLOPT_USERNAME, "xxxx@163.com");
		curl_easy_setopt(curl, CURLOPT_PASSWORD, "xxxx");
        curl_easy_setopt(curl, CURLOPT_URL,"imap://imap.163.com/INBOX");
		curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");//The problem is that the data is incomplete after adding this sentence.
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, httpDataWriter);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*)&data);
                res = curl_easy_perform(curl);
		
		cout << data;

		if (res != CURLE_OK)
			cout << "err:" << curl_easy_strerror(res);
	   }	
		
	    curl_easy_cleanup(curl);
		
	    cin.get();
	return (int)res;
}
`
		
![1](https://user-images.githubusercontent.com/33376859/32442482-932098f8-c336-11e7-99c1-290f2fc7235b.jpg)
Used in the diagram above
“Curl_easy_setopt (curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");”
Printing data is incomplete
![2](https://user-images.githubusercontent.com/33376859/32442560-d71ce0f2-c336-11e7-8060-a02e1f435036.jpg)
Get rid of it in the chart above
“Curl_easy_setopt (curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");”
Print data integrity。

Using the "CURLOPT_CUSTOMREQUEST" program to return data is incomplete. Please fix this problem. Thank you

**Comment by bagder** [comment]
1. You didn't tell us what libcurl version you're using
2. The [imap-fetch.c example](https://curl.haxx.se/libcurl/c/imap-fetch.html) shows how to fetch an email without using a custom request.

**Comment by yizhanfinish** [comment]
I'm using the latest version of your website

**Comment by jay** [comment]
> Using the "CURLOPT_CUSTOMREQUEST" program to return data is incomplete.

[CURLOPT_CUSTOMREQUEST](https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html):
> "When you change the request method by setting CURLOPT_CUSTOMREQUEST to something, you don't actually change how libcurl behaves or acts in regards to the particular request method, it will only change the actual string sent in the request."

If you need to get the body then make that request part of the URL. It can be seen in the example @bagder gave. For your FETCH 1 BODY[1] it would look like this:
imap://imap.163.com/;UID=1/;SECTION=1

If you use CURLOPT_CUSTOMREQUEST then in most cases curl will not parse the data out to a body because it is a custom request. So in those cases the data remains part of  the header. You would have to use [CURLOPT_HEADERFUNCTION](https://curl.haxx.se/libcurl/c/CURLOPT_HEADERFUNCTION.html). But there is no reason to do that if you are fetching a body, just use the URL format.

**Comment by yizhanfinish** [comment]
No, I really need to use it "CURLOPT_CUSTOMREQUEST"
However, I find that there is an uncoordinated problem in the return length of callbacks

**Comment by yizhanfinish** [comment]
I also use the official document to test, but the problem still exists, the real problem is that because the callback function returns the length of the data and the actual length of the received data variables are not consistent, this is an internal error, hoping to repair

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>
#include <iostream>
using namespace std;

struct MemoryStruct {
	char *memory;
	size_t size;
};

static size_t
WriteMemoryCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
	size_t realsize = size * nmemb;
	struct MemoryStruct *mem = (struct MemoryStruct *)userp;

	mem->memory = (char*)realloc(mem->memory, mem->size + realsize + 1);
	if (mem->memory == NULL) {
		/* out of memory! */
		printf("not enough memory (realloc returned NULL)\n");
		return 0;
	}

	memcpy(&(mem->memory[mem->size]), contents, realsize);
	mem->size += realsize;
	mem->memory[mem->size] = 0;

	return realsize;
}

int main(void)
{
	CURL *curl_handle;
	CURLcode res;

	struct MemoryStruct chunk;

	chunk.memory =(char*) malloc(1);  /* will be grown as needed by the realloc above */
	chunk.size = 0;    /* no data at this point */

	curl_global_init(CURL_GLOBAL_ALL);

	/* init the curl session */
	curl_handle = curl_easy_init();

	/* specify URL to get */
	curl_easy_setopt(curl_handle, CURLOPT_URL, "imap://imap.163.com/INBOX");
	curl_easy_setopt(curl_handle, CURLOPT_USERNAME, "xxx@163.com");
	curl_easy_setopt(curl_handle, CURLOPT_PASSWORD, "xxx");
	curl_easy_setopt(curl_handle, CURLOPT_CUSTOMREQUEST, "Select INBOX");
	/* send all data to this function  */
	curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);

	/* we pass our 'chunk' struct to the callback function */
	curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, (void *)&chunk);

	/* some servers don't like requests that are made without a user-agent
	field, so we provide one */
	//curl_easy_setopt(curl_handle, CURLOPT_USERAGENT, "libcurl-agent/1.0");

	/* get it! */
	res = curl_easy_perform(curl_handle);

	/* check for errors */
	if (res != CURLE_OK) {
		fprintf(stderr, "curl_easy_perform() failed: %s\n",
			curl_easy_strerror(res));
	}
	else {
		/*
		* Now, our chunk.memory points to a memory block that is chunk.size
		* bytes big and contains the remote file.
		*
		* Do something nice with it!
		*/

		printf("%s\n", chunk.memory);
	}

	/* cleanup curl stuff */
	curl_easy_cleanup(curl_handle);

	free(chunk.memory);

	/* we're done with libcurl, so clean it up */
	curl_global_cleanup();
	cin.get();
	return 0;
}`

**Comment by gvanem** [comment]
And if the callback never gets called, this:
```
	printf("%s\n", chunk.memory);
```
will print random garbage. At least do `printf("%.*s\n", chunk.size, chunk.memory)`.

I tried your sample with my own IMAP-server, and your code never reached the `WriteMemoryCallback()`.

**Comment by bagder** [comment]
> curl_easy_setopt(curl_handle, CURLOPT_CUSTOMREQUEST, "Select INBOX");

That's an unusual and unexpected way to use a custom request. You typically replace the *command*, not the target of the command. The mailbox name is provided in the URL so users would tend to only do:

`curl_easy_setopt(curl_handle, CURLOPT_CUSTOMREQUEST, "SELECT");`

... and the write callback works identically and is totally independent of the custom request so its not likely to be related I think.

**Comment by bagder** [comment]
> I'm using the latest version of your website

That's a very unspecific way to tell us. When did you check the web site? Can you please be exact?

**Comment by bagder** [comment]
@yizhanfinish, we still want a full test program source code or a more detailed clarification on this bug before we can do anything.

**Comment by yizhanfinish** [comment]
@bagder ，I am sorry, this time is relatively busy, I take the time to explain in detail, I came from China, at the same time through the translation exchange, to express some difficulties, please forgive me

**Comment by jay** [comment]
This does not appear to be a bug in curl, but is instead a bug in the reporter's program (see gvanem's comment) and also they may not be checking the header (see my comment). Whether we should return customrequests in the body instead of the header for imap is a matter of debate, I believe it has come up before but I don't remember the reasons for/against.
