### ISSUE TITLE
Can't use static openssl to compile curl on travis

### ISSUE THREAD

**Issue by cmeister2** [curl/curl#2059]
### I did this
Compiled dev curl against a static version of openssl 1.0.2m using gcc on travis: https://travis-ci.org/curl/curl-fuzzer/jobs/297343844

### I expected the following
curl to compile. Instead, it fails with the error: `configure: error: OpenSSL libs and/or directories were not found where specified!`. This fails in `gcc` only; `clang` appears to be fine. 

Running with travis debug mode seems to indicate a problem with ordering of static libraries; the test for SSL_connect uses `-lssl  -ldl -lssl -lcrypto   -lldap -llber -lz`, which doesn't appear to work.  `pkg-config --static --libs openssl` gives
```
23:19 # pkg-config --static --libs openssl
-lssl -ldl -lcrypto -ldl
```
Trying to get curl to use `pkg-config --static` didn't appear to work in my limited testing.

This issue appears to be a followon to https://github.com/curl/curl/issues/1426 which was closed expecting new issues to be raised.

**Comment by jay** [comment]
Are you using it like `PKG_CONFIG="pkg-config --static" ./configure ...`

**Comment by cmeister2** [comment]
I did
```
export PKG_CONFIG="pkg-config --static"
```
at the top of the script when I was testing it. I'd hope that would suffice. I could retest it doing in a proper build rather than a travis debug build in case that helps.

**Comment by jay** [comment]
@cmeister2 please see if #2234 fixes your issue

**Comment by cmeister2** [comment]
It appears to have allowed the curl-fuzzer builds to work, so yes! Thanks!

**Comment by jay** [comment]
Thanks for testing
