### ISSUE TITLE
curl -b/--cookie option failed to send cookie from a file

### ISSUE THREAD

**Issue by hundan2020** [curl/curl#2066]
### I did this
curl 127.0.01 -b cookies.txt 
### I expected the following
send cookie which in cookies.txt
![11111](https://user-images.githubusercontent.com/9510938/32656469-e677565e-c64c-11e7-8310-77cf72829dd4.jpg)

### curl/libcurl version
curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/2.0.2 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.8.0 nghttp2/1.26.0 librtmp/2.3
Release-Date: 2017-10-23

### operating system
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux

**Comment by bagder** [comment]
Your file probably didn't have any matching cookies?

**Comment by bagder** [comment]
The cookie file needs to be using "netscape format" or less ideally: be HTTP headers.

**Comment by hundan2020** [comment]
Solved, thank you for answering, maybe i should read a curl menual cautious
