### ISSUE TITLE
SFTP Authentication failure

### ISSUE THREAD

**Issue by chenjin0624** [curl/curl#2070]
SFTP Authentication failure,because **`va_arg(param, long)`** use twice.

Modify the following(In url.c 2714 line):
  case CURLOPT_SSH_AUTH_TYPES:
    `arg = va_arg(param, long);`
    if(arg < CURLSSH_AUTH_NONE)
      return CURLE_BAD_FUNCTION_ARGUMENT;
    //cause authentication failure
    //`data->set.ssh_auth_types = va_arg(param, long);`
    // The modified
    data->set.ssh_auth_types = arg;
    break;

**Comment by chenjin0624** [comment]
The latest version:7.56.1,please fix it.

**Comment by jay** [comment]
I think what you are reporting was fixed in 462f3ca, please check

**Comment by bagder** [comment]
and/or 961c8667d22 =)

**Comment by chenjin0624** [comment]
@bagder @jay OK,Because I was a script compiler, it has not been found to have been updated, thank you.I will close it.
