### ISSUE TITLE
garbage at end of field specification

### ISSUE THREAD

**Issue by ahungry** [curl/curl#2094]
### I did this
` curl -F 'dump=this,is,a,test' http://example.com -o /dev/null`

### I expected the following
Form field to send up with dump equal to the string of "this,is,a,test", as happens with previous/older versions of curl.

It looks like this is related to this: https://github.com/curl/curl/blob/master/src/tool_formparse.c#L846

I see no mention in the man page that field separator was altered for `;` to `,` or a way to fix this error.

### curl/libcurl version
7.56.1

[curl -V output]
curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.56.1 OpenSSL/1.1.0g zlib/1.2.11 libpsl/0.18.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.27.0                                                         
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
Arch Linux

**Comment by jay** [comment]
That sounds like #2022 which has been fixed. Can you try master?

/cc @monnerat

**Comment by bagder** [comment]
No reponse but looks exactly like the already fixed issue. Closing
