### ISSUE TITLE
"make distclean" fails

### ISSUE THREAD

**Issue by mkauf** [curl/curl#2097]
### I did this

```
./buildconf
./configure
make distclean
```

### I expected the following

I expected that "make distclean" runs successfully. Instead I got this error message:

```
...
make[1]: Leaving directory '/home/pi/curl/include'
Making distclean in docs
make[1]: Entering directory '/home/pi/curl/docs'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/home/pi/curl/docs'
Makefile:907: recipe for target 'distclean-recursive' failed
make: *** [distclean-recursive] Error 1
```

### curl/libcurl version

current curl master

### operating system

Linux

**Comment by jay** [comment]
d24838d but I don't see why. docs is now distclean, fine, but what exactly is needed in there that it's missing?

**Comment by bagder** [comment]
"distclean" apparently uses the `DIST_SUBDIRS` variable
