### ISSUE TITLE
Option CURLOPT_CAINFO is not ignored while using DarwinSSL

### ISSUE THREAD

**Issue by antonte** [curl/curl#2103]
According to the page: https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html 

> For SSL engines that don't support certificate files the CURLOPT_CAINFO option is ignored.

Page https://curl.haxx.se/docs/ssl-compared.html reads for DarwinSSL
> Uses Certificate/Key Files: no.

But curl actually uses the file specified in CURLOPT_CAINFO, and if it missing returns error code CURLE_SSL_CACERT_BADFILE (77), and if it formatted incorrectly returns error code CURLE_SSL_CACERT (60).

Documentation should be updated and read:

> Uses Certificate/Key Files: Yes

Curl version: 7.55.1

**Comment by nickzman** [comment]
Yes; Apple resumed shipping macOS with that bundle starting in 10.13. They also switched their libcurl's engine from Secure Transport to BoringSSL in 10.13, which was why it was necessary.

**Comment by bagder** [comment]
They actually switched to LibreSSL for curl (but they ship BoringSSL too):

> $ curl -V
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 

(Note that 2.0.20 is not an official LibreSSL release but whispers claim that it is actually the 2.2.7 version.)

**Comment by antonte** [comment]
Ah... ok I missed the part with iOS and macOS. Thanks you for clarification.
