### ISSUE TITLE
how to receive upload progress

### ISSUE THREAD

**Issue by noisedog** [curl/curl#2115]
### I did this

static int progressCallback(void *adapterp, double dltotal, double dlnow, double ultotal, double ulnow);

curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
curl_easy_setopt(curl, CURLOPT_HTTPPOST, formpost);
curl_easy_setopt(curl, CURLOPT_TIMEOUT, 180);
//curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, getSessionCallback);
curl_easy_setopt(curl, CURLOPT_WRITEDATA, &data);

//curl_easy_setopt(curl, CURLOPT_READFUNCTION, read_func);
//curl_easy_setopt(curl, CURLOPT_READDATA, file);
 curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);
//curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE,(curl_off_t)file_info.st_size);
curl_easy_setopt(curl, CURLOPT_PROGRESSFUNCTION, progressCallback);
curl_easy_setopt(curl, CURLOPT_PROGRESSDATA,adapter);
### I expected the following
can call progressCallback method,but it doesn't perform above
### curl/libcurl version
the latest
[curl -V output]

**Comment by jay** [comment]
Are you asking a question or reporting a bug, there is not enough information to tell. In the future please ask questions on [the mailing list](https://curl.haxx.se/mail/list.cgi?list=curl-library).

Run curl_version() to get the version string. Is it possible you forgot to call curl_easy_init or curl_easy_perform? This is not a complete example so I'm trying to imagine what could be missing from your code that would cause progressCallback not to be called.

I ran your code using against libcurl master `libcurl/7.57.0-DEV OpenSSL/1.0.2m nghttp2/1.27.0` with a few adjustments at the beginning to get it to compile since I don't know what url form and adapter are.
~~~c
int main(void)
{
  string url = "http://httpbin.org/post";
  struct curl_httppost *formpost = NULL, *lastptr = NULL;
  curl_formadd(&formpost,
               &lastptr,
               CURLFORM_COPYNAME, "submit",
               CURLFORM_COPYCONTENTS, "send",
               CURLFORM_END);
  char *adapter = "anything";
  curl = curl_easy_init();
  curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

... your code went here ...

  curl_easy_perform(curl);
~~~

I used this progressCallback:
~~~c
static int progressCallback(void *adapterp, double dltotal, double dlnow, double ultotal, double ulnow)
{  
  fprintf(stderr, "dltotal: %.0f , dlnow: %.0f, ultotal: %.0f, ulnow: %.0f, time: %.0f\n",
          dltotal, dlnow, ultotal, ulnow, difftime(time(NULL), 0));
  return 0;
}
~~~

dltotal: 394 , dlnow: 394, ultotal: 145, ulnow: 145, time: 1511757738
dltotal: 394 , dlnow: 394, ultotal: 145, ulnow: 145, time: 1511757738
dltotal: 394 , dlnow: 394, ultotal: 145, ulnow: 145, time: 1511757738
dltotal: 394 , dlnow: 394, ultotal: 145, ulnow: 145, time: 1511757738

**Comment by noisedog** [comment]
Yes,it is a question .And I will notice to ask questions on the mailing list next time.I had search many examples,but all of it is the same and is about download.I hava no idea to solve it now.so asking for a help here.thanks for your reply.

The curl version I use is 7.50.0-DEV

and my code is：
  void* DeviceAdapter::sendApkFile(DeviceAdapter* adapter)
{
	CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl) 
	{
        std::string url = "http://.........";
        std::string data;

        struct curl_httppost *formpost = NULL;
        struct curl_httppost *lastptr = NULL;
        curl_formadd(&formpost, &lastptr,
            CURLFORM_COPYNAME, "FileName",
                     CURLFORM_FILE, TV_REMOTE_INSTALL::UpgradeManager::getInstance()->getApkFilePath().c_str(),
            CURLFORM_CONTENTTYPE, "application/octet-stream",
            CURLFORM_END);
//UpgradeManager::getInstance()->getApkFilePath() is like "/storage/emulated/0/1902936695_tv_video_3.0.0.1050_android_15104.apk"
        //struct stat file_info;

        //FILE* file = fopen(UpgradeManager::getInstance()->getApkFilePath().c_str(), "rb");
        //fstat(fileno(file), &file_info);
        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_HTTPPOST, formpost);
        curl_easy_setopt(curl, CURLOPT_TIMEOUT, 180);
        //curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, getSessionCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &data);

        //curl_easy_setopt(curl, CURLOPT_READFUNCTION, read_func);
        //curl_easy_setopt(curl, CURLOPT_READDATA, file);
        curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);
        //curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE,(curl_off_t)file_info.st_size);
        curl_easy_setopt(curl, CURLOPT_PROGRESSFUNCTION, progressCallback);
        curl_easy_setopt(curl, CURLOPT_PROGRESSDATA,adapter);

        // write curl response to string variable..
        res = curl_easy_perform(curl);

        /* Check for errors */
        if (res == CURLE_OK) 
		{
            Json::Reader *reader = new Json::Reader(Json::Features::strictMode());
            Json::Value value;

            if (reader->parse(data, value)) {
                if (value["data_status"].asInt() == 200)
				{   

                    if (NULL != adapter->mpInternalInstallCallBackFunc)
                    {
                        adapter->mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLED,INSTALL_CODE_SUCCESS,100,"success");
                    }
                    
                }
				else
				{
					if (NULL != adapter->mpInternalInstallCallBackFunc)
					{
                        adapter->mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLED,INSTALL_CODE_FAIL,0,data);
//                        adapter->m_installCallBack->onInstalled(INSTALL_CODE_FAIL, data);
                    }
				}
            }
        } 
		else 
		{
            if (NULL != adapter->mpInternalInstallCallBackFunc)
            {
                adapter->mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLED,INSTALL_CODE_CURL_CONNECT_FAIL,0,"curl connect fail");

            }

        }

        curl_easy_cleanup(curl);
        curl_formfree(formpost);
	}
    return NULL;
}
size_t DeviceAdapter::getSessionCallback(void *ptr, size_t size, size_t count, void *stream)
{
    ((std::string *) stream)->append((char *) ptr, 0, size * count);
    return size*count;
}
int XiaoMiDeviceAdapter::progressCallback(void *adapterp, double dltotal, double dlnow, double ultotal, double ulnow)
{
    fprintf(stderr, "dltotal: %.0f , dlnow: %.0f, ultotal: %.0f, ulnow: %.0f, time: %.0f\n", dltotal, dlnow, ultotal, ulnow, difftime(time(NULL), 0));
    DeviceAdapter* adapter = (DeviceAdapter*)adapterp;
    
    if ( dltotal > -0.1 && dltotal < 0.1 )
    {
        return 0;
    }
    int nPos = (int) ( (dlnow/dltotal)*100 );

    //LOGI("progress:ultotal:%d ulnow:%d nPos:%d",(long)dltotal,(long)dlnow,nPos);

    if(adapter->mpInternalInstallCallBackFunc)
    {
adapter>mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLING,INSTALLING_UPDATE_PROGRESS,nPos,"installing");
    }

    return 0;
}

**Comment by jay** [comment]
I don't see the problem in your code. Turn on [CURLOPT_VERBOSE](https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html) and check the output to confirm a transfer is taking place.

**Comment by noisedog** [comment]
I turn on CURLOPT_VERBOSE by adding curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L).and the file has been send successfully.and the following is the output.

11-27 14:43:56.598 30687-30900/com.ktcp.crossplatformremoteinstall I/XiaoMiDeviceAdapter: [remote_install_help][XiaoMiDeviceAdapter][XiaoMiDeviceAdapter]install
11-27 14:43:56.599 30687-30900/com.ktcp.crossplatformremoteinstall I/installJNI: [remote_install_help][installJNI]onInstalling
11-27 14:43:56.599 30687-30900/com.ktcp.crossplatformremoteinstall I/java: wwh--onInstalling code:0 msg:0
11-27 14:43:56.654 30687-30901/com.ktcp.crossplatformremoteinstall I/XiaoMiDeviceAdapter: [remote_install_help][XiaoMiDeviceAdapter][XiaoMiDeviceAdapter]install, url=http://192.168.1.102:6095/phoneAppInstallV2?session=3376
11-27 14:43:57.338 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:43:57.344 17883-17883/? I/NetworkSpeedManagerEx: value=464935.66speed = 454K/s
11-27 14:43:57.345 17883-17883/? I/NetworkSpeedView: /update(), speed=454K/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:43:57.372 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:43:57.378 17883-17883/? I/NetworkSpeedManagerEx: value=464935.66speed = 454K/s
11-27 14:43:57.379 17883-17883/? I/NetworkSpeedView: /update(), speed=454K/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:43:57.613 445-1360/? I/gralloc: alloc_device_free:586: Free handle(0x7043e0ff00)
11-27 14:43:57.614 445-1360/? I/gralloc: alloc_device_free:586: Free handle(0x702c667800)
11-27 14:43:57.665 1228-17769/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:43:57.690 1793-27771/? I/DownloadState: @@@@@@@@@@@@ uid :10125 download :true
11-27 14:43:57.690 1793-27771/? I/PGServer: report state:5 event type:1 pid:0 uid:10125 pkg:null to pid: 1228
11-27 14:43:57.693 30687-30687/com.ktcp.crossplatformremoteinstall W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 14:43:57.697 30687-30687/com.ktcp.crossplatformremoteinstall W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 14:43:57.707 445-459/? I/gralloc: alloc_device_free:586: Free handle(0x7043e36400)
11-27 14:43:57.707 445-459/? I/gralloc: alloc_device_free:586: Free handle(0x7043e36900)
11-27 14:43:57.898 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-29 "TP-LINK_5E85"WPA_PSK
11-27 14:43:57.931 445-445/? I/gralloc: alloc_device_free:586: Free handle(0x7043e36600)
11-27 14:43:58.212 445-445/? I/gralloc: alloc_device_free:586: Free handle(0x702c667300)
11-27 14:43:58.556 1228-1228/? I/TrafficMonitor: update:rxPkts:341,txPkts:2933,rxBytes:21403,txBytes:4092210
11-27 14:43:58.556 1228-1228/? I/TrafficMonitor: no expired. level:2
11-27 14:43:58.556 1228-1228/? I/TrafficMonitor: gettimer:interval=2000
11-27 14:43:58.557 1228-1228/? I/TrafficMonitor: during_ms:2004,period_ms:2000
11-27 14:43:58.557 1228-1228/? I/TrafficMonitor: count:998,rx_sum:341,tx_sum:2933,rxBytes:21403,during_ms:2004,rx_speed:10680.139720558882,tx_speed:2042020.9580838324,rto:0.11626321172860553
11-27 14:43:58.742 1228-1228/? I/MQoS: onSignal: mSubId=0,currDataSubID=0
11-27 14:43:58.742 1228-1228/? I/MQoS: received cell-signal:5
11-27 14:43:58.752 1228-2475/? I/SendBroadcastPermission: action:android.intent.action.SIG_STR, mPermissionType:0
11-27 14:43:59.416 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-31 "TP-LINK_5E85"WPA_PSK
11-27 14:43:59.427 1228-1449/? I/HuaweiWifiWatchdogStateMachine: spd good count:0, add sc:0.0, rate:1.0
11-27 14:43:59.427 1228-1449/? I/HuaweiWifiWatchdogStateMachine: current mHighDataFlowRate = 1.0
11-27 14:43:59.427 1228-1449/? I/HuaweiWifiWatchdogStateMachine: POta txb txg rxg:0, 4570, 0. Lr =0% Totpkt=4570
11-27 14:43:59.429 1228-1228/? I/QosMonitor: queryRtt: rtt_type = 3
11-27 14:43:59.429 1228-1228/? I/WifiProJNI: ######### GET RTT:3 ########
11-27 14:43:59.429 1228-1228/? I/WifiProJNI: ######### CMD_QUERY_PKTS ########
11-27 14:43:59.430 1228-1447/? I/QosMonitor: postEventFromNative: msg=100,arg1=4,arg2=9
11-27 14:43:59.430 1228-1447/? W/WifiProJNI: poll before: g_monitor_fd =251
11-27 14:43:59.430 1228-1447/? I/QosMonitor: postEventFromNative: msg=100,arg1=0,arg2=9
11-27 14:43:59.431 1228-1447/? W/WifiProJNI: poll before: g_monitor_fd =251
11-27 14:43:59.431 1228-1228/? I/MQoS: rtt=280,tcp_tx_pkts=9806737,tcp_rx_pkts=20560768
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: PTcp RTT:0, rtt pkt=0, tcp_rx=0, tcp_tx=0, tcp_reTran=0, rtRate=0
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine:  pkt chk not bad, reset sc to 0.
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: net speed good
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: judge good link######, goodLinkLevel=3
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: sendResultMsgToQM bssid:ec:26:**:**:5e:85, qoslevel=3
11-27 14:43:59.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: link good reported, good base rssi:-35
11-27 14:43:59.447 1228-3840/? I/MQoS: QOS_level:0(0),wifi-link;SIM error;use level-0
11-27 14:43:59.627 571-571/? E/Thermal-daemon: [charger_ic] temp_new :36  temp_old :35
11-27 14:43:59.628 571-571/? E/Thermal-daemon: Report temperature: [charger_ic] temp :36  report_threshold:1
11-27 14:43:59.632 571-571/? E/Thermal-daemon: [ap] temp_new :36  temp_old :35
11-27 14:43:59.633 571-571/? E/Thermal-daemon: Report temperature: [ap] temp :36  report_threshold:1
11-27 14:43:59.772 1228-1438/? E/HwCHRWebMonitor: WebMonitor [mNetWorkIsSuck=0 mUIDIsSuck=]  WebSpeed [WEBSENDSEGS=0  WEBRESENDSEGS=0  WEBRECVSEGS=0  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=0  WEBRTTSEGS=0  WEBSRTT=280  WEBSNDDUPACKS=0  SENDSEGS=5359  RESENDSEGS=0  RECVSEGS=537  ERRSEGS=0  OUTRSTS=0  ESTABLISRST=0  RTTDURATION=32615  RTTSEGS=535  SNDDUPACKS=0  suckTimes=0 recovage_times=0]
11-27 14:43:59.772 1228-1438/? E/HwCHRWifiRSSIGroupSummery: updateTcpSummery mRSSI:-33  HwCHRWifiRSSIGroup [rssi_index=4, rtt_tcp_packets=131, rtt_tcp_duration=3835, rtt_lan_duration=472, rtt_lan_failures=0, rtt_lan_succ=24, rtt_lan_max=30, rtt_lan_min=14,same_area_frequency=0,adjacent_area_frequency=0]
11-27 14:43:59.778 1228-1438/? E/HwCHRWebMonitor: HwCHRWifiPacketCnt [mTXGood=5360, mTXbad=0, mRXGood=578] rssi=-33
11-27 14:43:59.778 1228-1438/? E/HwCHRWebMonitor: Good NetWork Traffic , so mOnAppSuckTime, mUnModifyCount reset 0
11-27 14:43:59.793 1228-1248/? I/EventHub: EventHub monitor: no key events in the past 1208s, 
11-27 14:44:00.023 2568-2568/? I/HwLauncher: Model  onReceive intent=Intent { act=android.intent.action.TIME_TICK flg=0x50000014 (has extras) }
11-27 14:44:00.023 2568-2568/? I/HwLauncher: Model  onReceive user=UserHandle{0}
11-27 14:44:00.027 17883-17883/? W/HwKeyguardDragHelper: AnimationBlocked
11-27 14:44:00.050 1228-1818/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.057 17883-17883/? W/HwKeyguardDragHelper: AnimationBlocked
11-27 14:44:00.060 17883-17883/? I/EventCenter: EventCenter Get :android.intent.action.TIME_TICK
11-27 14:44:00.061 17883-17883/? W/ResourceType: Failure getting entry for 0xffffffff (t=254 e=65535) (error -2147483647)
11-27 14:44:00.062 17883-17883/? E/DateLunarView: mDateString is: 11月27日星期一
11-27 14:44:00.067 17883-17883/? W/ResourceType: Failure getting entry for 0xffffffff (t=254 e=65535) (error -2147483647)
11-27 14:44:00.067 17883-17883/? E/DateLunarView: mDateString is: 11月27日星期一
11-27 14:44:00.104 1228-2555/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.114 1228-2555/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.117 17883-17883/? W/HwKeyguardDragHelper: AnimationBlocked
11-27 14:44:00.121 1228-2555/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.124 1228-2555/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.345 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:00.350 17883-17883/? I/NetworkSpeedManagerEx: value=2634894.2speed = 2.5M/s
11-27 14:44:00.351 17883-17883/? I/NetworkSpeedView: /update(), speed=2.5M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:00.381 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:00.387 17883-17883/? I/NetworkSpeedManagerEx: value=2677709.0speed = 2.6M/s
11-27 14:44:00.387 17883-17883/? I/NetworkSpeedView: /update(), speed=2.6M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:00.560 1228-1228/? I/TrafficMonitor: update:rxPkts:509,txPkts:4222,rxBytes:28861,txBytes:5899300
11-27 14:44:00.560 1228-1228/? I/TrafficMonitor: start expired. level:2
11-27 14:44:00.560 1228-1228/? I/TrafficMonitor: gettimer:interval=2000
11-27 14:44:00.719 1228-17769/? E/Process: isHighLoadProcess: get cpu failed
11-27 14:44:00.904 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-32 "TP-LINK_5E85"WPA_PSK
11-27 14:44:01.169 20674-30960/? W/HwSystemManager: AdBlockResultHandle:handleAdApkDownload adBlock is null
11-27 14:44:02.127 2453-4880/? I/VRService: no vr mode
11-27 14:44:02.134 17883-17883/? W/KeyguardUpdateMonitor: ACTION_BATTERY_CHANGED AMP: 0; Volt: 0
11-27 14:44:02.138 22416-27416/? I/CloudAlbum[8.0.1.304]: [OperationUtil] cancelNotify
11-27 14:44:02.156 2303-2303/? I/iMonitor: create: 903001012
11-27 14:44:02.158 2303-2303/? E/iMonitor: Bad param for imonitor_set_param, paramid: 11
11-27 14:44:02.162 2303-2303/? E/iMonitor: Bad param for imonitor_set_param, paramid: 12
11-27 14:44:02.162 2303-2303/? E/iMonitor: Bad param for imonitor_set_param, paramid: 10
11-27 14:44:02.163 2303-2303/? I/iMonitor: send: 903001012
11-27 14:44:02.163 588-1096/? I/logserver: handle_exception_events enter
11-27 14:44:02.180 17883-17883/? W/KeyguardUpdateMonitor: ChargingSpeed  Wattage: -1 ST: 5000000 --> 7500000
11-27 14:44:02.180 17883-17883/? I/KgBattery: BatteryInfo updated:  2lPc-1
11-27 14:44:02.180 17883-17883/? W/AppHandler: sendMessage with obj100
11-27 14:44:02.182 2303-2363/? E/LogCollectService: illegal eventid
11-27 14:44:02.184 17883-17883/? W/HwLockScreenPanel: Handle message: 100
11-27 14:44:02.184 17883-17883/? W/KgBattery: getCharge info with type: text
11-27 14:44:02.187 17883-17883/? W/HwLockScreenPanel: refreshBatteryInfo: null
11-27 14:44:02.563 1228-1228/? I/TrafficMonitor: update:rxPkts:579,txPkts:3767,rxBytes:36274,txBytes:5091436
11-27 14:44:02.564 1228-1228/? I/TrafficMonitor: no expired. level:3
11-27 14:44:02.564 1228-1228/? I/TrafficMonitor: gettimer:interval=2000
11-27 14:44:02.564 1228-1228/? I/TrafficMonitor: during_ms:2004,period_ms:2000
11-27 14:44:02.564 1228-1228/? I/TrafficMonitor: count:1000,rx_sum:579,tx_sum:3767,rxBytes:36274,during_ms:2004,rx_speed:18100.798403193614,tx_speed:2540636.7265469064,rto:0.15370321210512344
11-27 14:44:03.352 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:03.375 17883-17883/? I/NetworkSpeedManagerEx: value=2605892.8speed = 2.5M/s
11-27 14:44:03.376 17883-17883/? I/NetworkSpeedView: /update(), speed=2.5M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:03.387 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:03.391 17883-17883/? I/NetworkSpeedManagerEx: value=2624211.2speed = 2.5M/s
11-27 14:44:03.391 17883-17883/? I/NetworkSpeedView: /update(), speed=2.5M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:03.919 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-33 "TP-LINK_5E85"WPA_PSK
11-27 14:44:04.567 1228-1228/? I/TrafficMonitor: update:rxPkts:666,txPkts:4152,rxBytes:39159,txBytes:5510840
11-27 14:44:04.568 1228-1228/? I/TrafficMonitor: start expired. level:3
11-27 14:44:04.568 1228-1228/? I/TrafficMonitor: gettimer:interval=2000
11-27 14:44:04.634 571-571/? E/Thermal-daemon: [charger_ic] temp_new :37  temp_old :36
11-27 14:44:04.635 571-571/? E/Thermal-daemon: Report temperature: [charger_ic] temp :37  report_threshold:1
11-27 14:44:04.637 571-571/? E/Thermal-daemon: [ap] temp_new :37  temp_old :36
11-27 14:44:04.637 571-571/? E/Thermal-daemon: Report temperature: [ap] temp :37  report_threshold:1
11-27 14:44:04.742 1228-1228/? I/MQoS: onSignal: mSubId=0,currDataSubID=0
11-27 14:44:04.743 1228-1228/? I/MQoS: received cell-signal:5
11-27 14:44:04.744 1228-1705/? I/SendBroadcastPermission: action:android.intent.action.SIG_STR, mPermissionType:0
11-27 14:44:04.780 1228-1438/? E/HwCHRWebMonitor: WebMonitor [mNetWorkIsSuck=0 mUIDIsSuck=]  WebSpeed [WEBSENDSEGS=10  WEBRESENDSEGS=0  WEBRECVSEGS=10  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=270  WEBRTTSEGS=4  WEBSRTT=580  WEBSNDDUPACKS=0  SENDSEGS=10211  RESENDSEGS=0  RECVSEGS=1636  ERRSEGS=0  OUTRSTS=0  ESTABLISRST=0  RTTDURATION=230986  RTTSEGS=1636  SNDDUPACKS=0  suckTimes=0 recovage_times=0]
11-27 14:44:04.780 1228-1438/? E/HwCHRWifiRSSIGroupSummery: updateTcpSummery mRSSI:-34  HwCHRWifiRSSIGroup [rssi_index=4, rtt_tcp_packets=135, rtt_tcp_duration=4105, rtt_lan_duration=472, rtt_lan_failures=0, rtt_lan_succ=24, rtt_lan_max=30, rtt_lan_min=14,same_area_frequency=0,adjacent_area_frequency=0]
11-27 14:44:04.783 1228-1438/? E/HwCHRWebMonitor: HwCHRWifiPacketCnt [mTXGood=10222, mTXbad=0, mRXGood=1704] rssi=-34
11-27 14:44:04.783 1228-1438/? E/HwCHRWebMonitor: Good NetWork Traffic , so mOnAppSuckTime, mUnModifyCount reset 0
11-27 14:44:06.377 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:06.383 17883-17883/? I/NetworkSpeedManagerEx: value=1820742.4speed = 1.7M/s
11-27 14:44:06.384 17883-17883/? I/NetworkSpeedView: /update(), speed=1.7M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:06.392 17883-17883/? I/NetworkSpeedManagerEx: mIsStop = false
11-27 14:44:06.399 17883-17883/? I/NetworkSpeedManagerEx: value=1759609.0speed = 1.7M/s
11-27 14:44:06.399 17883-17883/? I/NetworkSpeedView: /update(), speed=1.7M/s parent class:class com.android.systemui.statusbar.HwSystemIcons
11-27 14:44:06.570 1228-1228/? I/TrafficMonitor: update:rxPkts:232,txPkts:1370,rxBytes:15474,txBytes:1842038
11-27 14:44:06.570 1228-1228/? I/TrafficMonitor: start expired. level:-1
11-27 14:44:06.570 1228-1228/? I/TrafficMonitor: gettimer:interval=2000
11-27 14:44:06.940 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-31 "TP-LINK_5E85"WPA_PSK
11-27 14:44:07.402 30687-30901/com.ktcp.crossplatformremoteinstall I/XiaoMiDeviceAdapter: [remote_install_help][XiaoMiDeviceAdapter]install, rsp:
11-27 14:44:07.424 1228-1370/? E/WifiConfigManager: updateConfiguration freq=2462 BSSID=ec:26:ca:af:5e:85 RSSI=-29 "TP-LINK_5E85"WPA_PSK
11-27 14:44:07.433 1228-1228/? I/QosMonitor: queryRtt: rtt_type = 3
11-27 14:44:07.433 1228-1228/? I/WifiProJNI: ######### GET RTT:3 ########
11-27 14:44:07.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: spd good count:0, add sc:0.0, rate:1.0
11-27 14:44:07.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: current mHighDataFlowRate = 1.0
11-27 14:44:07.434 1228-1449/? I/HuaweiWifiWatchdogStateMachine: POta txb txg rxg:0, 11882, 0. Lr =0% Totpkt=11882
11-27 14:44:07.434 1228-1228/? I/WifiProJNI: ######### CMD_QUERY_PKTS ########
11-27 14:44:07.434 1228-1447/? I/QosMonitor: postEventFromNative: msg=100,arg1=4,arg2=9
11-27 14:44:07.435 1228-1447/? W/WifiProJNI: poll before: g_monitor_fd =251
11-27 14:44:07.435 1228-1447/? I/QosMonitor: postEventFromNative: msg=100,arg1=0,arg2=9
11-27 14:44:07.435 1228-1447/? W/WifiProJNI: poll before: g_monitor_fd =251
11-27 14:44:07.435 1228-1228/? I/MQoS: rtt=580,tcp_tx_pkts=9806747,tcp_rx_pkts=20560778
11-27 14:44:07.435 1228-1228/? I/QosMonitor: resetRtt: rtt_type = 3
11-27 14:44:07.435 1228-1228/? I/WifiProJNI: ######### RESET RTT:3 ########
11-27 14:44:07.438 1228-1449/? I/HuaweiWifiWatchdogStateMachine: PTcp RTT:580, rtt pkt=4, tcp_rx=10, tcp_tx=10, tcp_reTran=0, rtRate=0
11-27 14:44:07.439 1228-1449/? I/HuaweiWifiWatchdogStateMachine:  pkt chk not bad, reset sc to 0.
11-27 14:44:07.439 1228-1449/? I/HuaweiWifiWatchdogStateMachine: net speed good
11-27 14:44:07.449 1228-3840/? I/MQoS: QOS_level:0(0),wifi-link;SIM error;use level-0
11-27 14:44:07.565 1228-1228/? I/TrafficMonitor: expired arrive. level:-1
11-27 14:44:07.566 1228-1228/? I/TrafficMonitor: during_ms:2002,period_ms:2000
11-27 14:44:07.566 1228-1228/? I/TrafficMonitor: count:1002,rx_sum:232,tx_sum:1370,rxBytes:15474,during_ms:2002,rx_speed:7729.27072927073,tx_speed:920098.9010989012,rto:0.16934306569343066

**Comment by jay** [comment]
None of that is curl output, do you see curl output? The only thing I can think of is maybe your server is not returning content length of the body or the content length of the body is 0? In both cases dltotal would remain 0 and so mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLING would not be called in the progress function.

~~~
dltotal: 0 , dlnow: 0, ultotal: 207, ulnow: 207, time: 1511766393
dltotal: 0 , dlnow: 0, ultotal: 207, ulnow: 207, time: 1511766393
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Connection: keep-alive
* Server meinheld/0.6.1 is not blacklisted
< Server: meinheld/0.6.1
< Date: Mon, 27 Nov 2017 07:06:32 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Powered-By: Flask
< X-Processed-Time: 0.000865936279297
< Content-Length: 396    <-------------HERE
< Via: 1.1 vegur
<
~~~

**Comment by bagder** [comment]
> all of it is the same and is about download

The progress callbacks work identically for both upload and download!

**Comment by noisedog** [comment]
@bagder 
Download a file can call the progress callback method.But when I change it to upload a file,I can't receive the progress callback.For above,I ran my code and sent the file I want successfully.

**Comment by jay** [comment]
> Download a file can call the progress callback method.But when I change it to upload a file,I can't receive the progress callback.

I really don't see how that would be since it's called in numerous places regardless of whether you upload or download. Did you investigate what I said in the previous post? If dltotal is 0 (as it would be before the upload takes place, see my output) then DeviceAdapter::progressCallback will return early and mpInternalInstallCallBackFunc( will not be called.

~~~c
    if ( dltotal > -0.1 && dltotal < 0.1 )
    {
        return 0;
    }
~~~

(You could just write that as !dltotal.)

and then after that:

~~~c
    if(adapter->mpInternalInstallCallBackFunc)
    {
adapter>mpInternalInstallCallBackFunc(INSTALL_TYPE_INSTALLING,INSTALLING_UPDATE_PROGRESS,nPos,"installing");
    }
~~~

I'd guess you meant adapter->mpInternalInstallCallBackFunc and not adapter>mpInternalInstallCallBackFunc.

**Comment by noisedog** [comment]
Sorry，maybe I don't tell my problem clearly. I mean I have printed the output in the DeviceAdapter::progressCallback method like follow :" fprintf(stderr, "dltotal: %.0f , dlnow: %.0f, ultotal: %.0f, ulnow: %.0f, time: %.0f\n", dltotal, dlnow, ultotal, ulnow, difftime(time(NULL), 0));",And I don't see any output. 
   When download a file,I can see the output in my log.But when I modify my code to upload a apk file,I can't see any output like above in my log.So I don't know why the callback hasn't been called.

**Comment by jay** [comment]
Can you clarify this. Are you saying when you download the file you see 
dltotal / dl now / ultotal / ulnow 
... but not when you upload?

**Comment by bagder** [comment]
no response
