### ISSUE TITLE
CURLOPT_CONNECT_ONLY not honoured when connecting through HTTPS proxy 

### ISSUE THREAD

**Issue by mirtchovski** [curl/curl#2116]
### I am attempting to use libcurl to set up the connection to a HTTPS server _through_ an HTTPS proxy, but I want to negotiate the TLS with the server myself (don't care about the proxy's TLS, libcurl can do that)

I did the following:

```
curl_easy_setopt(handle, CURLOPT_CONNECT_ONLY, 1);
curl_easy_setopt(handle, CURLOPT_URL, "http://server:443"); // note http vs https: 
curl_easy_setopt(handle, CURLOPT_PROXY, "proxyhost");
curl_easy_setopt(handle, CURLOPT_PROXYPORT, 443);
curl_easy_setopt(handle, CURLOPT_PROXYTYPE, CURLPROXY_HTTPS);
```

### I expected to be able to receive a handle on which I can do SSL_new() and set up TLS, however I am seeing that curl has already negotiated TLS to the server and any subsequent attempts to do so result in this error (from openssl, not from libcurl):

`error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

### curl/libcurl version

```
$ export/bin/curl -V
curl 7.56.0 (x86_64-apple-darwin16.7.0) libcurl/7.56.0 OpenSSL/1.0.2l zlib/1.2.8
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```

**Comment by bagder** [comment]
`CURLOPT_CONNECT_ONLY` has never been about just doing a TCP connect to allow the application to to the TLS handshake, and I don't think adding HTTPS proxy to the mix changes that.

**Comment by mirtchovski** [comment]
I think I understand where the issue is coming from. even though I am trying to negotiate a TLS context with the server, I still need to talk TLS with the proxy, and that context has been set up by curl. I don't think this is an issue with libcurl at all. Closing.
