### ISSUE TITLE
Inifinite loop inside libcurl curl_multi_perform 

### ISSUE THREAD

**Issue by zhaoguangqiang** [curl/curl#2130]
### I did this
 I use libcurl(7.54.1) and I found an infinite loop in libcurl.  I have two thread to start http request .Two threads blocked when request a thousand times. I found an infinite loop in curl_multi_perform when i add a gdb break .

The problem phenomenon is quite similar the #2004 issue you have been resolved,
but i found my time_t is long int.It might be not a similar problem.

### I expected the following
my thread not be blocked, curl_multi_perform don't infinite loop
### curl/libcurl version
i found issue in version 7.54.1

### operating system
raspbian on raspberry 3B(is a linux system).
first this issue occure on some android native system,then we can reproduce raspbian on raspberry 3B.
other linux system maybe occur.
Detailed problem description

### Detailed problem description
i try to reproduce this problem. but it too hard to reproduce. We always test thousand times then it occur one time.When this time occur,i found multi->timetree->larger address == multi->timetree address. compare multi->timetree->key and now, it had been expired. Then i try to config this state to write a unittest. The result is inifinate loop in curl_multi_perform.I want to know how it occur multi->timetree->larger address == multi->timetree address and  multi->timetree->key expired

**Comment by zhaoguangqiang** [comment]
I found another infinite loop ,when multi->timetree->larger == multi->timetree->smaller == multi->timetree,the point address is similar, the process infinite loop. I follow it in curl_multi_perform's curl_splay function cannot break out.

**Comment by bagder** [comment]
That's been reported many times in the past when users haven't followed the multi-threading rules for libcurl. Are you totally sure your threads aren't sharing handles at any point? Can you provide a minimal example code that reproduces this problem?

We have test cases for the splay tree code, I feel pretty confident about it...

**Comment by zhaoguangqiang** [comment]
I have simulated test when the tree parent or son points is similar. Cannot provide whole test. Because i also donnot know when the problem occur in throusands of loop test. And it only occur in my campany code :(
My method is create a libcurl multi thread, our client thread create a thread include easy handle. When  we need a http connection, client thread add easy handle to multi thread'libcurl. when finish this connection ,we use curl_easy_reset to reuse this easy handle

**Comment by bagder** [comment]
I can't reproduce the problem. You can't provide a reproducible function. That makes it really hard for us to do anything.

Then look into test [case 1309](https://github.com/curl/curl/blob/master/tests/unit/unit1309.c) and try to use the splay code directly to reproduce a similar problem!

Alternatively, I would suggest you try to run your code as a single-threaded function to see if I'm not right in suspecting that the threading is what is involved in triggering this.

**Comment by jay** [comment]
please review [libcurl thread safety](https://curl.haxx.se/libcurl/c/threadsafe.html)

**Comment by zhaoguangqiang** [comment]
@bagder Thanks a lot, i try to transplant out curl_splay from libcurl code. From my infinate loop process's curl_multi_perform call stack to write a infinate  unittest. Expect be helpful to resolve my puzzle.

[curl_splay.zip](https://github.com/curl/curl/files/1520220/curl_splay.zip)

**Comment by bagder** [comment]
I'm sorry but I don't know what to do with this!

I hoped that you'd write a small program that uses the (unmodified) libcurl functions the way they are supposed to be used, and reproduce a bug that way. Now you instead seem to reimplement libcurl functions and you modify individual struct fields in a way the API does not, so I don't see how this reproduces any existing bug.

**Comment by zhaoguangqiang** [comment]
@bagder @jay Thanks to everyone who helped me.We checked our code again and found curl_multi_add_handle curl_multi_perform be used in two different threads.And this operation may be destory multi's timetree.Then i read libcurl soures code.These functions don't have lock.We need provide lock by ourself.Then this issue never happened.
Thank you for reminding me,best wishes!

**Comment by bagder** [comment]
Thanks a lot for confirming this!
