### ISSUE TITLE
curl commandline data truncated by character '\x00'

### ISSUE THREAD

**Issue by geekgao** [curl/curl#2131]
### I did this
curl --request POST --data-binary $'\x6e\x69\x6f\x00\x6e\x69\x6f' http://127.0.0.1:8080/testman
### I expected the following
The result shoud be fully catched by my web backend,but now it truncated by character '\x00' .
I guessed C function strlen is evil here ?

### curl/libcurl version
curl 7.43.0 (x86_64-apple-darwin15.0.0) libcurl/7.43.0
[curl -V output]
curl 7.43.0 (x86_64-apple-darwin15.0.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
### operating system
OSX

**Comment by bagder** [comment]
It's actually even worse. The command line arguments are passed to curl as an array with zero-terminated strings. There's no way for curl to know if the zero is the end of the string or a binary zero you added there on purpose, as there's no other mechanism to get the length of the string!

A work-around for you is to pass the data to curl on stdin and use `--data-binary @-` as when reading from stdin embedded zero bytes are not a problem.
