### ISSUE TITLE
libssh build warning

### ISSUE THREAD

**Issue by bagder** [curl/curl#2135]
### I did this

`./configure --with-libssh`  on debian unstable
```

$ dpkg -l | grep libssh
ii  libssh-4:amd64                                0.8.0~20170825.94fa1e38-1             amd64        tiny C SSH library (OpenSSL flavor)
ii  libssh-dev                                    0.8.0~20170825.94fa1e38-1             amd64        tiny C SSH library. Development files (OpenSSL flavor)

```
And when building I get this warning:

```
ssh-libssh.c: In function ‘myssh_is_known’:
ssh-libssh.c:316:3: warning: ‘ssh_get_publickey’ is deprecated [-Wdeprecated-declarations]
   rc = ssh_get_publickey(sshc->ssh_session, &pubkey);
   ^~
In file included from ssh-libssh.c:34:0:
/usr/include/libssh/libssh.h:489:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_get_publickey(ssh_session session, ssh_key *key);
                               ^~~~~~~~~~~~~~~~~

```

### I expected the following

No warnings.

### curl/libcurl version

git master right now, commit b7f5345976

### operating system

Debian Linux

**Comment by bagder** [comment]
ping @nmav, can you look into this?

**Comment by nmav** [comment]
It seems to have been replaced by `ssh_get_server_publickey`. I'll make a pr.

**Comment by nmav** [comment]
Actually, I take it back. It has been replaced in libssh master by `ssh_get_server_publickey` but there is no released version containing `ssh_get_server_publickey`. The latest I can find is 0.7.5. What does debian ship?

**Comment by bagder** [comment]
Interesting choice to mark it as deprecated before they offer an alternative...

As shown above, my debian unstable lists libssh at `0.8.0~20170825.94fa1e38-1` but curl -V shows it as `libssh/0.7.0/openssl/zlib`.

So we get a compiler warning we can't really remove :-(

**Comment by bagder** [comment]
Okay, we blame libssh for this and move on. It should be fine once we upgrade to later versions.
