### ISSUE TITLE
Digest authentication ignores changed nonce

### ISSUE THREAD

**Issue by rb07** [curl/curl#2136]
The original application was collectd with the curl_json plugin, reported with the same title to the curl-library list.

I'm adding a self-contained test that shows the same problem.  It tests against a device which I own, you'll have to find a similar device/service that keeps changing the nonce.

### I did this

Ran my sample program, which retrieves some values from a device (serial number, timestamp, current power, max power of solar panels).

### I expected the following

The initial output is fine, shows the readings, but any subsequent attempt (with the same curl session) fails on authentication.

The problem is that libcurl keeps reusing the original nonce, even after receiving a 401 error code, and a new nonce.

The library doesn't retry after the 401 error when it has a nonce.

### curl/libcurl version

libcurl/7.56.1

### operating system

Tested on Linux, and re-tested on Cygwin, both have the same curl version, both show the same failure.

**Comment by jay** [comment]
Ref: https://curl.haxx.se/mail/lib-2017-11/0091.html

> I'm adding a self-contained test that shows the same problem.

? I don't see it

> Tested on Linux, and re-tested on Cygwin, both have the same curl version, both show the same failure.

please give curl_version() and SSPI info
~~~c
  {
    int features = curl_version_info(CURLVERSION_NOW)->features;
    printf("SSPI is %s\n", ((features & CURL_VERSION_SSPI) ? "on" : "off"));
    printf("%s\n", curl_version());
  }
~~~

**Comment by rb07** [comment]
Test program:  
[digest-auth.sample.zip](https://github.com/curl/curl/files/1522844/digest-auth.sample.zip)

Test output:

> $ ./digest-auth.sample
> Curl lib version: libcurl/7.56.1 OpenSSL/1.0.2m zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.7.0 nghttp2/1.23.1
> -----
> * STATE: INIT => CONNECT handle 0x600057250; line 1423 (connection #-5000)
> * Added connection 0. The cache now contains 1 members
> *   Trying 192.168.10.14...
> * TCP_NODELAY set
> * STATE: CONNECT => WAITCONNECT handle 0x600057250; line 1475 (connection #0)
> * Connected to 192.168.10.14 (192.168.10.14) port 80 (#0)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057250; line 1592 (connection #0)
> * Marked for [keep alive]: HTTP default
> * STATE: SENDPROTOCONNECT => DO handle 0x600057250; line 1610 (connection #0)
> * Server auth using Digest with user 'envoy'
> > GET /api/v1/production/inverters HTTP/1.1
> Host: 192.168.10.14
> User-Agent: curl/7.56.1
> Accept: */*
> 
> * STATE: DO => DO_DONE handle 0x600057250; line 1689 (connection #0)
> * STATE: DO_DONE => WAITPERFORM handle 0x600057250; line 1814 (connection #0)
> * STATE: WAITPERFORM => PERFORM handle 0x600057250; line 1824 (connection #0)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> < HTTP/1.1 401 Unauthorized
> < Date: Fri, 01 Dec 2017 19:43:05 GMT
> * Marked for [closure]: Connection: close used
> < Connection: close
> < Date: Fri, 01 Dec 2017 19:43:05 GMT
> < WWW-Authenticate: Digest qop="auth", realm="enphaseenergy.com", nonce="ybAhWooB8L/pc80VX8gEc7LskbA="
> < Content-Type: application/json
> < Content-Length: 90
> <
> * multi_done
> * Closing connection 0
> * The cache now contains 0 members
> * Issue another request to this URL: 'http://192.168.10.14/api/v1/production/inverters'
> * STATE: PERFORM => CONNECT handle 0x600057250; line 1974 (connection #-5000)
> * Added connection 1. The cache now contains 1 members
> * Hostname 192.168.10.14 was found in DNS cache
> *   Trying 192.168.10.14...
> * TCP_NODELAY set
> * STATE: CONNECT => WAITCONNECT handle 0x600057250; line 1475 (connection #1)
> * Connected to 192.168.10.14 (192.168.10.14) port 80 (#1)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057250; line 1592 (connection #1)
> * Marked for [keep alive]: HTTP default
> * STATE: SENDPROTOCONNECT => DO handle 0x600057250; line 1610 (connection #1)
> * Server auth using Digest with user 'envoy'
> > GET /api/v1/production/inverters HTTP/1.1
> Host: 192.168.10.14
> Authorization: Digest username="envoy", realm="enphaseenergy.com", nonce="ybAhWooB8L/pc80VX8gEc7LskbA=", uri="/api/v1/production/inverters", cnonce="NGQ1Y2Q0YjJmMzIwYWViYjFiOGMzNzAyYTZhNTJhMTQ=", nc=00000001, qop=auth, response="f95ac1e777f68c155b55e3923cd35bd3"
> User-Agent: curl/7.56.1
> Accept: */*
> 
> * STATE: DO => DO_DONE handle 0x600057250; line 1689 (connection #1)
> * STATE: DO_DONE => WAITPERFORM handle 0x600057250; line 1814 (connection #1)
> * STATE: WAITPERFORM => PERFORM handle 0x600057250; line 1824 (connection #1)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> < HTTP/1.1 200 OK
> < Date: Fri, 01 Dec 2017 19:43:05 GMT
> * Marked for [closure]: Connection: close used
> < Connection: close
> < Date: Fri, 01 Dec 2017 19:43:05 GMT
> < Content-Type: application/json
> < Content-Length: 607
> <
> [
>   {
>     "serialNumber": "121727000935",
>     "lastReportDate": 1512157365,
>     "devType": 1,
>     "lastReportWatts": 231,
>     "maxReportWatts": 267
>   },
>   {
>     "serialNumber": "121727005655",
>     "lastReportDate": 1512157366,
>     "devType": 1,
>     "lastReportWatts": 231,
>     "maxReportWatts": 267
>   },
>   {
>     "serialNumber": "121726069995",
>     "lastReportDate": 1512157367,
>     "devType": 1,
>     "lastReportWatts": 231,
>     "maxReportWatts": 267
>   },
>   {
>     "serialNumber": "121727012633",
>     "lastReportDate": 1512157363,
>     "devType": 1,
>     "lastReportWatts": 235,
>     "maxReportWatts": 272
>   }
> ]
> * STATE: PERFORM => DONE handle 0x600057250; line 1993 (connection #1)
> * multi_done
> * Closing connection 1
> * The cache now contains 0 members
> * Expire cleared
> * STATE: INIT => CONNECT handle 0x600057250; line 1423 (connection #-5000)
> * Added connection 2. The cache now contains 1 members
> * Hostname in DNS cache was stale, zapped
> *   Trying 192.168.10.14...
> * TCP_NODELAY set
> * STATE: CONNECT => WAITCONNECT handle 0x600057250; line 1475 (connection #2)
> * Connected to 192.168.10.14 (192.168.10.14) port 80 (#2)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057250; line 1592 (connection #2)
> * Marked for [keep alive]: HTTP default
> * STATE: SENDPROTOCONNECT => DO handle 0x600057250; line 1610 (connection #2)
> * Server auth using Digest with user 'envoy'
> > GET /api/v1/production/inverters HTTP/1.1
> Host: 192.168.10.14
> Authorization: Digest username="envoy", realm="enphaseenergy.com", nonce="ybAhWooB8L/pc80VX8gEc7LskbA=", uri="/api/v1/production/inverters", cnonce="NGQ1Y2Q0YjJmMzIwYWViYjFiOGMzNzAyYTZhNTJhMTQ=", nc=00000002, qop=auth, response="b670551d1d7f64e48b3f01e9e65e5528"
> User-Agent: curl/7.56.1
> Accept: */*
> 
> * STATE: DO => DO_DONE handle 0x600057250; line 1689 (connection #2)
> * STATE: DO_DONE => WAITPERFORM handle 0x600057250; line 1814 (connection #2)
> * STATE: WAITPERFORM => PERFORM handle 0x600057250; line 1824 (connection #2)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> < HTTP/1.1 401 Unauthorized
> < Date: Fri, 01 Dec 2017 19:48:05 GMT
> * Marked for [closure]: Connection: close used
> < Connection: close
> < Date: Fri, 01 Dec 2017 19:48:05 GMT
> * Authentication problem. Ignoring this.
> < WWW-Authenticate: Digest qop="auth", realm="enphaseenergy.com", nonce="9bEhWn2P0j16BYfjBYi/CsEE2xk="
> < Content-Type: application/json
> < Content-Length: 90
> <
> {
>   "status": 401,
>   "error": "",
>   "info": "Authentication required",
>   "moreInfo": ""
> }
> * STATE: PERFORM => DONE handle 0x600057250; line 1993 (connection #2)
> * multi_done
> * Closing connection 2
> * The cache now contains 0 members
> * STATE: INIT => CONNECT handle 0x600057250; line 1423 (connection #-5000)
> * Added connection 3. The cache now contains 1 members
> * Hostname in DNS cache was stale, zapped
> *   Trying 192.168.10.14...
> * TCP_NODELAY set
> * STATE: CONNECT => WAITCONNECT handle 0x600057250; line 1475 (connection #3)
> * Connected to 192.168.10.14 (192.168.10.14) port 80 (#3)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057250; line 1592 (connection #3)
> * Marked for [keep alive]: HTTP default
> * STATE: SENDPROTOCONNECT => DO handle 0x600057250; line 1610 (connection #3)
> * Server auth using Digest with user 'envoy'
> > GET /api/v1/production/inverters HTTP/1.1
> Host: 192.168.10.14
> Authorization: Digest username="envoy", realm="enphaseenergy.com", nonce="9bEhWn2P0j16BYfjBYi/CsEE2xk=", uri="/api/v1/production/inverters", cnonce="Yjg4ZTlmYWVkZTk4MzVkZmY1ZjA1NWY2NzE2ZWI2ZjA=", nc=00000001, qop=auth, response="2a5ef363c7e773043ea4f6fbb2d55df3"
> User-Agent: curl/7.56.1
> Accept: */*
> 
> * STATE: DO => DO_DONE handle 0x600057250; line 1689 (connection #3)
> * STATE: DO_DONE => WAITPERFORM handle 0x600057250; line 1814 (connection #3)
> * STATE: WAITPERFORM => PERFORM handle 0x600057250; line 1824 (connection #3)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> < HTTP/1.1 401 Unauthorized
> < Date: Fri, 01 Dec 2017 19:53:06 GMT
> * Marked for [closure]: Connection: close used
> < Connection: close
> < Date: Fri, 01 Dec 2017 19:53:06 GMT
> * Ignoring duplicate digest auth header.
> < WWW-Authenticate: Digest qop="auth", realm="enphaseenergy.com", nonce="IrMhWgvUMPk8gSoPFuGOtS4gm+Q="
> < Content-Type: application/json
> < Content-Length: 90
> <
> * multi_done
> * Closing connection 3
> * The cache now contains 0 members
> * Issue another request to this URL: 'http://192.168.10.14/api/v1/production/inverters'
> * STATE: PERFORM => CONNECT handle 0x600057250; line 1974 (connection #-5000)
> * Added connection 4. The cache now contains 1 members
> * Hostname 192.168.10.14 was found in DNS cache
> *   Trying 192.168.10.14...
> * TCP_NODELAY set
> * STATE: CONNECT => WAITCONNECT handle 0x600057250; line 1475 (connection #4)
> * Connected to 192.168.10.14 (192.168.10.14) port 80 (#4)
> * STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057250; line 1592 (connection #4)
> * Marked for [keep alive]: HTTP default
> * STATE: SENDPROTOCONNECT => DO handle 0x600057250; line 1610 (connection #4)
> * Server auth using Digest with user 'envoy'
> > GET /api/v1/production/inverters HTTP/1.1
> Host: 192.168.10.14
> Authorization: Digest username="envoy", realm="enphaseenergy.com", nonce="9bEhWn2P0j16BYfjBYi/CsEE2xk=", uri="/api/v1/production/inverters", cnonce="Yjg4ZTlmYWVkZTk4MzVkZmY1ZjA1NWY2NzE2ZWI2ZjA=", nc=00000002, qop=auth, response="1ffdb46349db12a96e7005bec3492a75"
> User-Agent: curl/7.56.1
> Accept: */*
> 
> * STATE: DO => DO_DONE handle 0x600057250; line 1689 (connection #4)
> * STATE: DO_DONE => WAITPERFORM handle 0x600057250; line 1814 (connection #4)
> * STATE: WAITPERFORM => PERFORM handle 0x600057250; line 1824 (connection #4)
> * HTTP 1.1 or later with persistent connection, pipelining supported
> < HTTP/1.1 401 Unauthorized
> < Date: Fri, 01 Dec 2017 19:53:06 GMT
> * Marked for [closure]: Connection: close used
> < Connection: close
> < Date: Fri, 01 Dec 2017 19:53:06 GMT
> * Authentication problem. Ignoring this.
> < WWW-Authenticate: Digest qop="auth", realm="enphaseenergy.com", nonce="IrMhWgvUMPk8gSoPFuGOtS4gm+Q="
> < Content-Type: application/json
> < Content-Length: 90
> <
> {
>   "status": 401,
>   "error": "",
>   "info": "Authentication required",
>   "moreInfo": ""
> }
> * STATE: PERFORM => DONE handle 0x600057250; line 1993 (connection #4)
> * multi_done
> * Closing connection 4
> * The cache now contains 0 members
> * Expire cleared
>

**Comment by rb07** [comment]
SSPI is off
libcurl/7.56.1 OpenSSL/1.0.2m zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.7.0 nghttp2/1.23.1

**Comment by rb07** [comment]
The device I'm communicating with is running Linux (i.e. I don't see the relevance of SSPI).

**Comment by bagder** [comment]
This appears to be a server flaw.

[RFC 2617](https://www.ietf.org/rfc/rfc2617.txt) documents HTTP Digest (recently updated with [RFC 7616](https://tools.ietf.org/html/rfc7616)) and I quote from the section **3.2.1 The WWW-Authenticate Response Header** where it explains the `stale` flag in the header:

>      A flag, indicating that the previous request from the client was
>      rejected because the nonce value was stale. If stale is TRUE
>      (case-insensitive), the client may wish to simply retry the request
>      with a new encrypted response, without reprompting the user for a
>      new username and password. The server should only set stale to TRUE
>      if it receives a request for which the nonce is invalid but with a
>      valid digest for that nonce (indicating that the client knows the
>      correct username/password). If stale is FALSE, or anything other
>      than TRUE, or the stale directive is not present, the username
>      and/or password are invalid, and new values must be obtained.

There's no stale flag in the second 401 response, so curl treats it as an authentication error and not as a request to update the nonce.

curl could *possibly* compare the newly received nonce with the one it used formerly in the previous request and take that as a strong hint what the server wants, but I'm hesitant to go down that slippery slope...

**Comment by rb07** [comment]
> This appears to be a server flaw.
> 
> RFC 2617 <https://www.ietf.org/rfc/rfc2617.txt> documents HTTP Digest
> (recently updated with RFC 7616 <https://tools.ietf.org/html/rfc7616>)
> and I quote from the section *3.2.1 The WWW-Authenticate Response
> Header* where it explains the |stale| flag in the header:
...
> There's no stale flag in the second 401 response, so curl treats it as
> an authentication error and not as a request to update the nonce.
> 
> curl could /possibly/ compare the newly received nonce with the one it
> used formerly in the previous request and take that as a strong hint
> what the server wants, but I'm hesitant to go down that slippery slope...

Seems reasonable, except that "nonce" by definition (in a general context, i.e. the meaning of the word) is to be used only once.

I do agree that the server should have verified it, and add the "stale" flag.

From RFC 7616:

"nonce

      A server-specified string which should be uniquely generated each
      time a 401 response is made."

This is what the server is doing.

The RFC does leave open the reuse, or one-time use, as valid options.  But gives a description close to what we are seeing in section 3.6:

"The client response to a WWW-Authenticate challenge for a protection
   space starts an authentication session with that protection space.
   The authentication session lasts until the client receives another
   WWW-Authenticate challenge from any server in the protection space.
   A client SHOULD remember the username, password, nonce, nonce count,
   and opaque values associated with an authentication session to use to
   construct the Authorization header field in future requests within
   that protection space.  The Authorization header field MAY be
   included preemptively; doing so improves server efficiency and avoids
   extra round trips for authentication challenges.  The server MAY
   choose to accept the old Authorization header field information, even
   though the nonce value included might not be fresh.  Alternatively,
   the server MAY return a 401 response with a new nonce value in the
   WWW-Authenticate header field, causing the client to retry the
   request; by specifying "stale=true" with this response, the server
   tells the client to retry with the new nonce, but without prompting
   for a new username and password."

The addition of "stale" seems optional from this description, its just a shortcut to tell the client to use the (included) new nonce.

**Comment by bagder** [comment]
If wrong or no credentials are passed to the server, it responds with a new nonce too, so for a client to know that the credentials are right but the nonce is stale (ie to properly differentiate between a right and wrong situation), it has to pass the `stale` keyword. 

I don't think this sentence leaves a lot of room for interpretation:

**If stale is FALSE, or anything other than TRUE, or the stale directive is not present, the username and/or password are invalid, and new values must be obtained.**

It is possible to work around that server flaw in the client but it'll require some ugly checks and probably a counter that makes it stop if it tried twice or something. If you want to go down that path, I won't object as long as we keep things as sane as possible, but I'm also not terribly eager to write that code myself.

**Comment by rb07** [comment]
I agree.

There is no indication in the response that the nonce is stale.  The server makes it impossible to differentiate between wrong user, or password, and stale nonce.

At the same time its generating a new nonce with the 401 response (and then doesn't generate a new one with subsequent 401 response; weird implementation).

I won't pursue this further, I have a workaround in place since I stumbled into this (use curl in a script, instead of libcurl on the plugin).

Thanks for your time.

**Comment by jay** [comment]
I suggest contacting the manufacturer of the device to let them know. In libcurl you can reset the handle or use a separate handle for each request as a workaround. Basically you could move the code in main to a function and add a write function and then if(getinverters(&jsonstr) == 200) for each request. If there are redirects you would likely need to handle them on your own using CURLINFO_REDIRECT_URL.
