### ISSUE TITLE
limit speed after curl_easy_perform failed

### ISSUE THREAD

**Issue by zhangzihua** [curl/curl#2140]
I don't know if this is a bug.
I just want to limit my libcurl up or down speed after curl_easy_perform. I call curl_easy_setopt(curl_, CURLOPT_MAX_SEND(RECV)_SPEED_LARGE...) in the callback function of CURLOPT_READFUNCTION,CURLOPT_WRITEFUNCTION,CURLOPT_XFERINFOFUNCTION.
But I failed.Speed will be 0 B/s after I limit.
my libcurl is 7.54.1 on windows (vs2015)
thank you!

**Comment by bagder** [comment]
We can't help you unless you give us many more details. For example a small reproducible example source code that we can use to repeat the problem?

**Comment by zhangzihua** [comment]
I'm sorry. I find one bug of my code. 
This is my mistake and not curl bug.
Thank you very much!
