### ISSUE TITLE
scan-build warnings in ssh-libssh.c

### ISSUE THREAD

**Issue by bagder** [curl/curl#2141]
### I did this

I build current git master with clang's scan-build static analyzer tool.

I fixed a few warnings, but these seems to be imply we're lacking something. We should either make use of these return codes or just remove the function calls?

```
ssh-libssh.c:899:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssh-libssh.c:919:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssh-libssh.c:935:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssh-libssh.c:952:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssh-libssh.c:967:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ssh-libssh.c:982:9: warning: Value stored to 'err' is never read
        err = sftp_get_error(sshc->sftp_session);
        ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### I expected the following

No new warnings.

### curl/libcurl version

git master commit 10bb0b471

### operating system

Linux

**Comment by bagder** [comment]
We also have five additional defects detected by coverity that could use some help. Head over to the [curl coverity page](https://scan.coverity.com/projects/curl?tab=overview), apply to become a "member" and you'll be able to see the current defects.

**Comment by nmav** [comment]
Thanks. I'll follow up with a PR. In gnutls we included a scan-build with clang and cppcheck run in the CI builds. They don't always catch everything that coverity finds, but they proved to reduce the number of bugs found later by coverity.

**Comment by bagder** [comment]
Adding scan-build to the CI build is "problematic" (see #2099) for several reasons, and we would need to add a very large amount of builds to cover all 3rd party library combinations. But I'll see to it that our [daily scans](https://curl.haxx.se/scans/) get going again.
