### ISSUE TITLE
broken SSH_SFTP_QUOTE_STATVFS logic?

### ISSUE THREAD

**Issue by bagder** [curl/curl#2142]
Line 997 in lib/ssh-libssh.c:

`      statvfs = sftp_statvfs(sshc->sftp_session, sshc->quote_path1);
`
This is said to [return NULL on error](http://api.libssh.org/master/group__libssh__sftp.html#ga8654c581979d66fcf5cf1f1b67226cd2)

Then follows:

```
      if(statvfs != 0 && !sshc->acceptfail) {
        Curl_safefree(sshc->quote_path1);
        err = sftp_get_error(sshc->sftp_session);
```

So shouldn't the first condition rather be

`  if(!statvfs && !sshc->acceptfail) {
`

Ie if it *is* NULL there's a problem if it isn't allowed to fail?

And what if it is allowed to fail? Then it'll continue to the else clause, which dereferences the NULL pointer unconditionally...

(CID 1424906, detected by coverity)

/cc @nmav

**Comment by nmav** [comment]
Your analysis is correct. This seems to be a usage of the libssh2 convention of error checking.

**Comment by bagder** [comment]
Unfortunately the pointer deref is still there. Now the first check is fine, but if the pointer returns NULL and `sshc->acceptfail` is TRUE, the else clause will dereference the NULL pointer!

**Comment by nmav** [comment]
Sorry about this.

**Comment by bagder** [comment]
No worries! It's a lot of new code and finding and fixing these before a first public release is nothing but good!
