### ISSUE TITLE
in6addr_any missing from HPE NonStop NSE

### ISSUE THREAD

**Issue by rsbeckerca** [curl/curl#2146]
I found a compile problem in the test suite for curl 7.57.0 (may be old as this is the first time we're trying to build with IPv6 enabled. I have a patch for this that I can provide in a pull request if desired, although the in6.h and in6addr_any may be distinct issues making the patch not entirely perfect.

### I did this
When building curl on NSK-TANDEM-NSE, the definition in6addr_any is not found in in.h.  In addition, IPv6 is defined in in6.h on this platform, which did not seem to be an issue for the main curl build.

```c
    struct sockaddr_in6  sa6;
                         ^
"/home/git/curl/tests/server/server_sockaddr.h", line 34: error(163):
          incomplete type is not allowed


      me.sa6.sin6_addr = in6addr_any;
                         ^
"/home/git/curl/tests/server/rtspd.c", line 1321: error(114): identifier
          "in6addr_any" is undefined
```

### I expected the following
Clean compile - rather obviously.

### curl/libcurl version
```curl
7.57.0 (nse-tandem-nsk) libcurl/7.57.0 OpenSSL/1.0.2m zlib/1.2.8
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

### operating system
HPE NonStop J06.20

**Comment by rsbeckerca** [comment]
I did miss a few required sources in this which I can add as part of a pull request:

- lib/curl_addrinfo.h
- lib/hostcheck.c
- lib/hostip.c
- lib/urldata.h

**Comment by bagder** [comment]
note that `in6addr_any` is only used by the test suite servers, not by curl or libcurl

**Comment by rsbeckerca** [comment]
Yes, however, in6.h is required for the above lib files because of sockaddr_in6, which on this platform is also in in6h.

**Comment by bagder** [comment]
aha!
