### ISSUE TITLE
curl interface for resumed download is a bit confusing

### ISSUE THREAD

**Issue by xhacker** [curl/curl#2161]
curl interface for resumed download is a bit confusing

### I did this
1. curl -L -O -C - http://releases.ubuntu.com/17.10/ubuntu-17.10-desktop-amd64.iso
2. ^C
3. curl -L -O -C - http://releases.ubuntu.com/17.10/ubuntu-17.10-desktop-amd64.iso

### I expected the following
In step 3, the download resumes from the last position. However, the UI makes me feel that it’s starting from scratch, because the `Received` and `%` fields are cleared:
```
➜  Downloads curl -L -O -C - http://releases.ubuntu.com/17.10/ubuntu-17.10-desktop-amd64.iso 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 12 1431M   12  177M    0     0  2826k      0  0:08:38  0:01:04  0:07:34 2869k^C
➜  Downloads curl -L -O -C - http://releases.ubuntu.com/17.10/ubuntu-17.10-desktop-amd64.iso
** Resuming transfer from byte position 186933248
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4 1253M    4 52.2M    0     0  2560k      0  0:08:21  0:00:20  0:08:01 3067k^C
```

I would suggest the `Total` field to always be the file size, and the `Received` field to always be the size that I’ve already downloaded.

### curl/libcurl version
curl 7.54.0

**Comment by TylerNichols** [comment]
@bagder If the suggestion from xhacker is acceptable, I would be interested in implementing this.

**Comment by bagder** [comment]
I think it sounds reasonable!

**Comment by s-3ntinel** [comment]
I started working on this issue recently, and since i got no reply to my email sent to curl-library, I'm going to ask here.

I adjusted TOTAL field as per issue request ( + removed percentage for TOTAL since it it doesnt make sense in this format), but my question is it better to leave TIME SPENT to count from 0 every time i resume a download or continue the timer from where it left of upon termination?

**Comment by bagder** [comment]
You *did* get a [reply](https://curl.haxx.se/mail/lib-2018-02/0080.html). (Assuming that was you.)

**Comment by s-3ntinel** [comment]
My bad, it was in a spam folder.

**Comment by jay** [comment]
@s-3ntinel's branch is here: https://github.com/curl/curl/compare/master...s-3ntinel:fix-bug-%232161?expand=1

**Comment by bagder** [comment]
This this is not strictly a bug and nobody is acting on it since a long time, I'm closing...
