### ISSUE TITLE
CURLOPT_WRITEFUNCTION documentation error

### ISSUE THREAD

**Issue by kd0gls** [curl/curl#2176]
On this page

https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

1) The Return Value section is confusing as the return value (as described in the Description section) is supplied by the user.

**Comment by bagder** [comment]
So how do you think it should be better explained? I personally think it is pretty clearly described...

**Comment by kd0gls** [comment]
Daniel,

I did offer up my suggestions back in mid-December.  Did you not receive them?  I’d be happy to resend them if not.

Regards,
Brent

**Comment by bagder** [comment]
While we can (should?) improve the documentation and I'll welcome that, I don't think this is a bug so I'm now closing this issue.
