### ISSUE TITLE
curl_easy_perform block forever even set timeout in Xiaomi phone

### ISSUE THREAD

**Issue by renwotao** [curl/curl#2187]
### I did this
when I complied libcurl for android，I found curl_easy_perform blocked in Xiaomi phone even set timeout

### curl/libcurl version
curl Version：curl-7.57.0

[curl -V output]

### operating system
Xiaomi Phone

**Comment by bagder** [comment]
Is that build using the stock synchronous name resolver?

Does Android support signals otherwise? signals are used to abort slow name resolves when the synch name resolver is used.

"Forever" is a long time, how long did you wait? In what state did libcurl actually get stuck? If you enable VERBOSE you'll see that. What exactly did you do when it got stuck? Protocol/host/options etc.

**Comment by renwotao** [comment]
I use stock synchronous name resolver.

I enable VERBOSE but does not work，set debug but does not work too.

    curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, curl_debug);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);
    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &json_str);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 3000);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, 3000);
    curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1);

**Comment by bagder** [comment]
This is still not enough information for anyone to act on. IDEBUGFUNCTION works fine on Android exactly like on all other platforms, so you can use that to collect the verbose output in case regular stderr isn't good enough for you.

You also didn't say what protocol or URL you're using or what's special in the case where it blocks "forever". Does it *always* block forever? Do you call `curl_easy_perform()` or drive your code differently?

Preferably, you give us a full small example source code that reproduces the problem!

**Comment by bagder** [comment]
No response and lack of data.
