### ISSUE TITLE
Connecting to HTTPS server through HTTPS proxy on non-standard port reverts to HTTP

### ISSUE THREAD

**Issue by sedimentation-fault** [curl/curl#2191]
I think I have found a _curl_ bug - bear with me if I found a feature instead! :-)
### I did this
`curl -o xxx.html  "https://some-server.com:YYYY" --proxy "https://xxx.yyy.zzz:YYYY"  --proxy-cacert some-cert.crt --proxy-basic --proxy-user 'some-user:some-pass' --verbose`

i.e. tried to connect to server some-server.com with HTTPS at a non-standard port YYYY through an HTTPS connection to proxy xxx.yyy.zzz at the same non-standard port YYYY. 

The connection to the proxy works fine, but then _curl_ reverts to HTTP and tries to connect to http://some-server.com:YYYY, which of course returns a HTTP 503 (Service Unavailable). 

### I expected the following
I expected _curl_ to try to connect to https://some-server.com:YYYY, not to http://some-server.com:YYYY, through the proxy at https://xxx.yyy.zzz:YYYY.
Here is the (slightly redacted) log:

```
* Rebuilt URL to: https://some-server.com:YYYY/
*   Trying 12.34.56.78...
* TCP_NODELAY set
* Connected to xxx.yyy.zzz (12.34.56.78) port YYYY (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/ca-certificates/some.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [86 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1374 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [783 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [262 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Proxy certificate:
* ...
*  SSL certificate verify ok.
* allocate connect buffer!
* Establish HTTP proxy tunnel to some-server.com:YYYY
* Proxy auth using Basic with user 'some-user'
} [5 bytes data]
> CONNECT some-server.com:YYYY HTTP/1.1^M
> Host: some-server.com:YYYY^M
> Proxy-Authorization: Basic ZZZZZZZZZZZZZZZZZZZZZZZZZZZ^M
...
{ [5 bytes data]
< HTTP/1.0 503 Service Unavailable^M
...
* The requested URL returned error: 503
* CONNECT phase completed!
```
The bug is at the line

`CONNECT some-server.com:YYYY HTTP/1.1`

It should be HTTPS, not HTTP. Obviously, it is trying a 'tunnel' using HTTP CONNECT. But I didn't ask that. I asked it to connect through HTTPS to port YYYY of some-server.com.
When the user explicitly specifies the HTTPS protocol for the destination, curl should not interpret a non-standard port on that destination as a request for an HTTP connection to that port through a tunnel. It should simply try HTTPS on that port.

### curl/libcurl version
curl 7.57.0 (i686-pc-linux-gnu) libcurl/7.57.0 OpenSSL/1.0.2k zlib/1.2.8 libidn2/0.16 nghttp2/1.19.0 librtmp/2.3
Release-Date: 2017-11-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy Metalink

### operating system
Gentoo Linux

**Comment by jay** [comment]
> The bug is at the line
> 
> CONNECT some-server.com:YYYY HTTP/1.1
> 
> It should be HTTPS, not HTTP. Obviously, it is trying a 'tunnel' using HTTP CONNECT. But I didn't ask that. I asked it to connect through HTTPS to port YYYY of some-server.com.

I'm not sure what you want. curl tunnels HTTPS via proxy. In other words you connect to the proxy (any proxy) and then if the URL is HTTPS curl requests the proxy open a connection to that destination host:port, and then curl will try to negotiate ssl. The error message you are seeing is from the proxy because it appears it can't open a connection.

There is #2156 which will allow curl to ask the proxy to request HTTPS URLs rather than tunneling to the server. The reason curl doesn't do that already is because it's less secure since it's not end-to-end, the proxy can MITM the connection.

**Comment by sedimentation-fault** [comment]
After some more thought, I think you are right. It seems that the destination does not accept connections from _that_ proxy. I was irritated by reading "HTTP" at the CONNECT line - but looking at other, working examples, I now realize that it has always been that way, so it can't be that.

Feel free to close this issue. It was a feature after all. :-)

**Comment by jay** [comment]
Just to be clear, the error message was from the proxy. curl said CONNECT and the proxy replied 503 service unavailable.
