### ISSUE TITLE
feature request: Add --proxy-pinnedpubkey option

### ISSUE THREAD

**Issue by sedimentation-fault** [curl/curl#2192]
I would love to see a _--proxy-pinnedpubkey_ option, i.e. a way to pin the public key of an SSL proxy used to connect to a server, in addition to the already existing option of pinning the public key of the server itself with _--pinnedpubkey_. It will help reduce the risk of a MITM attack.

I guess it's not even a big deal to implement - just a copy of the _--pinnedpubkey_ functionality, this time for the proxy.

**Comment by bagder** [comment]
Please note that this tracker is for bugs/problems and not feature-requests so this entry will be closed soon.

Feel free to work on adding this option and file a PR, ask for help on the curl-library list if you need assistance.
