### ISSUE TITLE
multi_runsingle function long time

### ISSUE THREAD

**Issue by xiewenjie1314** [curl/curl#2193]
Dear,
     Using libcurl 7.30.0 version,multi_runsingle function long time.how do I fix this problem.
CURLMcode curl_multi_perform(CURLM *multi_handle, int *running_handles)  
{  
    struct Curl_multi *multi=(struct Curl_multi *)multi_handle;  
    struct Curl_one_easy *easy;  
    CURLMcode returncode=CURLM_OK;  
    struct Curl_tree *t;  
  
    if(!GOOD_MULTI_HANDLE(multi))  
        return CURLM_BAD_HANDLE;  
  
    easy=multi->easy.next;  
    while(easy != &multi->easy) {  
        CURLMcode result;  
        struct WildcardData *wc = &easy->easy_handle->wildcard;  
  
        if(easy->easy_handle->set.wildcardmatch) {  
            if(!wc->filelist) {  
                CURLcode ret = Curl_wildcard_init(wc); /* init wildcard structures */  
                if(ret)  
                    return CURLM_OUT_OF_MEMORY;  
            }  
        }  
  
        do  
            result = multi_runsingle(multi, easy);  
        while (CURLM_CALL_MULTI_PERFORM == result);
......
......

**Comment by bagder** [comment]
First, please try a recent version and see if you still can reproduce the problem.

If you can, please provide a small stand-alone example code that we can use to spot the problem. You didn't even mention what protocol or what libcurl option you've used.
