### ISSUE TITLE
how to cancel the network request in threadA when the request has already entered the curl_easy_perform() in threadB?

### ISSUE THREAD

**Issue by seekforwings** [curl/curl#2195]
### curl/libcurl version

[curl -V output]

**Comment by jay** [comment]
In the future please fill out the form. This is an issue tracker. Please ask your questions on one of [the mailing lists](https://curl.haxx.se/mail/) like curl-library for libcurl instead.

To answer your question, or what I think you are asking, you could check in the [progress function](https://curl.haxx.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html) for a shared resource that you set in another thread and then abort by returning CURLE_ABORTED_BY_CALLBACK, which would cause curl_easy_perform to return.
