### ISSUE TITLE
Why isn't CURL_STATICLIB set upon configuring on Windows?

### ISSUE THREAD

**Issue by softwarefailure** [curl/curl#2196]
I'm building curl like this on Windows:

    nmake /f makefile.vc mode=static debug=no machine=x64 with_zlib=static

This creates a static library and the corresponding include files in the directory `builds/libcurl-vc-x64-release-static-zlib-static-ipv6-sspi-winssl`. What is confusing me, however, is the fact that none of the includes generated actually have `CURL_STATICLIB` set. This means that I have to manually define `CURL_STATICLIB` in my project that I want to link against `libcurl` because otherwise all libcurl prototypes will be declared as DLL imports which is of course not what I want for static linkage.

Thus I think that when configuring curl for a static build `CURL_STATICLIB` should be set automatically in the corresponding includes.

**Comment by jay** [comment]
> Thus I think that when configuring curl for a static build CURL_STATICLIB should be set automatically in the corresponding includes.

libcurl can be built both shared and static and use the same set of includes. For that reason I don't consider it a bug that CURL_STATICLIB is not defined.

**Comment by softwarefailure** [comment]
But when I run

    nmake /f makefile.vc mode=static debug=no machine=x64 with_zlib=static

I am configuring a build which is specifically designed for static linkage as the build directory name `libcurl-vc-x64-release-static-zlib-static-ipv6-sspi-winssl` says. When I configure a build for shared linkage, it is placed inside a different directory. Thus, shared and static builds never share their includes because they are placed in different directories. That's why I'd expect to have `CURL_STATICLIB` automatically defined in includes generated for a static build and undefined for includes generated for a shared build.

**Comment by jay** [comment]
Sure I understand your point, but there are many different ways to build curl and not all of them build with separate include directories.

**Comment by bagder** [comment]
This is by design. The header files are generic and can be shared and used for multiple builds and even multiple targets and architectures. This is not a bug.
