### ISSUE TITLE
Env CURL_SSL_BACKEND is undocumented

### ISSUE THREAD

**Issue by jay** [curl/curl#2209]
Although multi-ssl builds of the curl tool are shipping it's not documented how to change the SSL backend that curl will use. I recently [answered](https://curl.haxx.se/mail/archive-2018-01/0001.html) a question on curl-users about a curl with multissl, and it was kind of a lot to explain.

We should explain somewhere that setting `CURL_SSL_BACKEND` can change the SSL library. Also, I'm not convinced that it's intuitive to show the inactive SSL libraries in parentheses. Maybe we should do it like
~~~
curl 7.57.0 (i686-w64-mingw32) libcurl/7.57.0 OpenSSL/1.0.2h zlib/1.2.8 WinIDN libssh2/1.7.0_DEV
MultiSSL: OpenSSL/1.0.2h (enabled), WinSSL
Release-Date: 2017-11-30
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTPS-proxy MultiSSL
~~~
?

/cc @dscho

**Comment by bagder** [comment]
The `CURL_SSL_BACKEND` variable is now documented in the brand new libcurl-env.3 man page. View it online [here](https://curl.haxx.se/libcurl/c/libcurl-env.html)!

**Comment by bagder** [comment]
The missing docs is the title of this issue, which is now fixed so closing...

**Comment by jay** [comment]
I still could use some feedback from you guys regarding splitting up the multissl in a separate line. Also what would you think if I add the ssl backend names to that doc?

**Comment by bagder** [comment]
Fire away a PR and we can see how it looks. I think it sounded like a good idea!
