### ISSUE TITLE
Recursive lock with CURLSHOPT_SHARE / CURL_LOCK_DATA_CONNECT

### ISSUE THREAD

**Issue by prapin** [curl/curl#2218]
### I did this

I enabled the shared connection pooling feature (`CURL_LOCK_DATA_CONNECT`), newly introduced in 7.57.0. I used a C++ `std::mutex` to implement locking for shared object.
That new feature mostly works from the first tests I did (in particular, on Wireshark I could verify that keep-alive HTTP feature works correctly). 
But in a different context, I experienced a self dead-lock. `CURL_LOCK_DATA_CONNECT` was trying to lock again while it is already locked by a previous function in the same thread. Using a recursive mutex `std::recursive_mutex` avoids the problem.

The stack trace when the dead-lock appears is like this (removed lower frames unrelated to cURL):

    frame #0: 0x0000000101837446 (anonymous namespace)::CurlShared::lock(handle=0x000062a000030200, data=CURL_LOCK_DATA_CONNECT, access=CURL_LOCK_ACCESS_SINGLE, userptr=0x0000614000014c40) at BaseCurlHttpRequest.cpp:48
    frame #1: 0x00000001016c4e58 Curl_share_lock(data=0x000062a000030200, type=CURL_LOCK_DATA_CONNECT, accesstype=CURL_LOCK_ACCESS_SINGLE) at share.c:227
    frame #2: 0x0000000101592ce6 Curl_conncache_remove_conn(connc=0x00006110000a0ce0, conn=0x000061d00003de80) at conncache.c:275
    frame #3: 0x000000010170fc08 Curl_disconnect(conn=0x000061d00003de80, dead_connection=true) at url.c:773
    frame #4: 0x000000010173484b disconnect_if_dead(conn=0x000061d00003de80, data=0x000062a000030200) at url.c:1015
    frame #5: 0x00000001017344e5 call_disconnect_if_dead(conn=0x000061d00003de80, param=0x000062a000030200) at url.c:1031
    frame #6: 0x00000001015933af Curl_conncache_foreach(data=0x000062a000030200, connc=0x00006110000a0ce0, param=0x000062a000030200, func=(call_disconnect_if_dead at url.c:1029)) at conncache.c:325
    frame #7: 0x0000000101727870 prune_dead_connections(data=0x000062a000030200) at url.c:1046
    frame #8: 0x000000010171904e create_conn(data=0x000062a000030200, in_connect=0x000062a000030210, async=0x00007000076ac230) at url.c:4396
    frame #9: 0x0000000101714dbe Curl_connect(data=0x000062a000030200, in_connect=0x000062a000030210, asyncp=0x00007000076ac230, protocol_done=0x00007000076ac240) at url.c:4680
    frame #10: 0x0000000101667237 multi_runsingle(multi=0x0000615000016380, now=(tv_sec = 1515152950, tv_usec = 929201), data=0x000062a000030200) at multi.c:1432
    frame #11: 0x000000010166549f curl_multi_perform(multi=0x0000615000016380, running_handles=0x00007000076ad1e0) at multi.c:2162
    frame #12: 0x00000001015c3fba easy_transfer(multi=0x0000615000016380) at easy.c:683
    frame #13: 0x00000001015c0a93 easy_perform(data=0x000062a000030200, events=false) at easy.c:769
    frame #14: 0x00000001015c07b7 curl_easy_perform(data=0x000062a000030200) at easy.c:788

### I expected the following

I expected that the mutex needed to implement `CURLSHOPT_LOCKFUNC` and `CURLSHOPT_UNLOCKFUNC` did not need to be recursive. At least I didn't found a notice in the documentation saying that a recursive mutex is needed for `CURL_LOCK_DATA_CONNECT`.

### curl/libcurl version

7.57.0

### operating system

On macOS. Most probably platform independent.

**Comment by jay** [comment]
Likely fixed in #2151. Please try reproducing with master.

**Comment by prapin** [comment]
I confirm that master branch (commit 2a6dbb8) does not yield the problem.
