### ISSUE TITLE
Not able to enable https protocol on cURL 7.56.0

### ISSUE THREAD

**Issue by Abinayasandhiya** [curl/curl#2226]
Hi,

Our customer is using cURL 7.56.0.
They request me to enable https on cURL.
So I have installed openssl and use --with-ssl option while building the cURL.
But it seems to be not enable https and I could see only below output when using "curl -V"

[XXX@XXX bin]$ /opt/curl/x86_64/7.56.0/bin/curl -V
curl 7.56.0 (x86_64-redhat-linux-gnu) libcurl/7.56.0 zlib/1.2.3 libssh2/1.4.2
Release-Date: 2017-10-04
**Protocols: dict file ftp gopher http imap pop3 rtsp scp sftp smtp telnet tftp**
Features: AsynchDNS IPv6 Largefile libz UnixSockets
[XXX@XXX bin]$

### I expected the following
I expect to enable Https with cURL 7.56.0

### curl/libcurl version
[XXX@XXX bin]$ /opt/curl/x86_64/7.56.0/bin/curl -V
curl 7.56.0 (x86_64-redhat-linux-gnu) libcurl/7.56.0 zlib/1.2.3 libssh2/1.4.2
Release-Date: 2017-10-04
Protocols: dict file ftp gopher http imap pop3 rtsp scp sftp smtp telnet tftp
Features: AsynchDNS IPv6 Largefile libz UnixSockets
[XXX@XXX bin]$

### operating system
Red Hat Enterprise Linux Server release 6.8
Red Hat Enterprise Linux Server release 7, 7.0, 7.1, 7.2

Please help me on this asap.

**Comment by jay** [comment]
> So I have installed openssl and use --with-ssl option while building the cURL.
> But it seems to be not enable https and I could see only below output when using "curl -V"

Did you install the openssl dev package or you built it yourself? Did you specify the path to OpenSSL like `--with-ssl=/usr/local/ssl` ? Check the configure output and config.log to find out what's failing.

**Comment by Abinayasandhiya** [comment]
Hello,

Thanks.

Trying to rebuild the cURL with correct path of ssl.
let you know the result.

**Comment by Abinayasandhiya** [comment]
Hello Jay,

Issues has been fixed.

I have done following steps:
>> Installed openssl-devel
>> and have specified the PATH of SSL library.

Now I could see the https protocol in cURL:
[XXX@XXX ~]$ curl -V
curl 7.56.0 (x86_64-redhat-linux-gnu) libcurl/7.56.0 OpenSSL/1.0.1e zlib/1.2.3 libssh2/1.4.2
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy

Thank you for your comment and help:)
