### ISSUE TITLE
Double Posting of Request

### ISSUE THREAD

**Issue by jlubinda** [curl/curl#2228]
### I did this
I send a POST request which has an auto generated unique token and confirmation of receipt code which i auto incremental

### I expected the following
Each request with it unique token should only have one unique receipt confirmation code. However each unique request had two different confirmation codes which are incrementally sequential which means curl is posting the same request twice when evoked once.

### curl/libcurl version
7.45.0

[curl -V output]

### operating system
x86_64-redhat-linux-gnu

**Comment by dfandrich** [comment]
Please use the mailing lists for support questions.  It will be much easier to
diagnose this if you include a verbose debug log. My gut feeling is that it has
to do with multiple round trips due to authentication, but the logs would prove
that.

**Comment by bagder** [comment]
No response after 5 days to immediate follow-up clarification request. Closing.
