### ISSUE TITLE
Problem with the SSL CA cert (path? access rights?) on Debian

### ISSUE THREAD

**Issue by cuihaikuo** [curl/curl#2229]
I wrote a program to test libcurl, here is the code:

```c
#include <curl/curl.h>
#include <string.h>
int main()
    {
    int ret;
    static char buf[10000];
    CURL *curl = curl_easy_init();
    if(curl) {
            curl_easy_setopt(curl, CURLOPT_URL, "https://www.baidu.com");
            curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, buf);
            curl_easy_setopt(curl, CURLOPT_CAINFO, "/etc/ssl/certs/ca-certificates.crt");

            ret = curl_easy_perform(curl);
            if (ret == CURLE_OK)
                    printf("OK\n");
            else {
                    size_t len = strlen(buf);
                    fprintf(stderr, "\nlibcurl: (%d) ", ret);
                    if(len)
                            fprintf(stderr, "%s%s", buf,
                                    ((buf[len - 1] != '\n') ? "\n" : ""));
                    else
                            fprintf(stderr, "%s\n", curl_easy_strerror(ret));
                    }
            curl_easy_cleanup(curl);
    }
}
```

This code works fine with CentOS and Ubuntu, but throw "Problem with the SSL CA cert (path? access rights?)" on debian, the CA file I specified is right and can be read, and when I run curl -v https://www.baidu.com in terminal, it shows
```
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs
```
should I do some other steps when using Debian? Any hint appreciated.

[curl -V output]

**Comment by jay** [comment]
So you are saying on the machine running Debian `curl https://www.baidu.com` works but the same thing in libcurl doesn't work? Are you sure that curl is using that same version of libcurl? Run `curl -V` and in libcurl `curl_version()` and compare. Also enable [CURLOPT_VERBOSE](https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html) for more information.

Note errbuf only has to be CURL_ERROR_SIZE , for example `char errbuf[CURL_ERROR_SIZE] = { 0, };`

**Comment by cuihaikuo** [comment]
The output of `curl_version()` is 
`libcurl/7.57.0 NSS/3.34 zlib/1.2.8 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.29.0 librtmp/2.3`, 
and the output of `curl -V` is 
`curl 7.57.0 (x86_64-pc-linux-gnu) libcurl/7.57.0 OpenSSL/1.0.2n zlib/1.2.8 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.29.0 librtmp/2.3`,
the verbose info: `* Initializing NSS with certpath: none
* WARNING: failed to load NSS PEM library libnsspem.so. Using OpenSSL PEM certificates will not work.
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* Closing connection 0`,

the interesting thing is, I compiled the code on an Ubuntu machine and moved binary file to Debian, the file can be run with no error,  my Debian version is 8.6

**Comment by jay** [comment]
I see, it's a different build of libcurl. OpenSSL backend works but NSS doesn't. This may be why: 

> * Initializing NSS with certpath: none

I think this is only happens when /etc/pki/nssdb does not exist. 

> * WARNING: failed to load NSS PEM library libnsspem.so. Using OpenSSL PEM certificates will not work.

So since it can't process PEM files it can't read /etc/ssl/certs/ca-certificates.crt.

Why those two things are I don't know. Possibly related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726073

**Comment by bagder** [comment]
curl using NSS cannot read PEM files unless it can also load libnsspem.so, which is used for exactly that purpose.
