### ISSUE TITLE
Build fails; "Curl_setopt()" still referenced in OS400 ccsidcurl.c

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#2230]
### I did this
Compile Curl 7.57.0 on OS400

### I expected the following
Clean build, however linking LIBCURL *SRVPGM fails as Curl_setopt is still prototyped in lib/url.h and called in packages/OS400/ccsidcurl.c, looks like it was removed from url.c in #1944.

result = Curl_setopt(data, tag, arg);

I think the fix is to make a call to curl_setstropt() instead and to tidy up and remove the old function prototype for Curl_setopt() from url.h.

result = Curl_setstropt(tag, arg);

### curl/libcurl version

[curl -V output]
7.57.0

### operating system
OS400

**Comment by monnerat** [comment]
Well... I have no OS400 access for 18 months but I will try to make it OK again!

Many thanks for reporting, however your hint is not OK: Curl_setstropt() only knows to set string options given a string index. This is not what we want to do.

I have prepared a git branch with a proposed fix: https://github.com/monnerat/curl/tree/setopt400. Please clone/download it and build on OS400, then report results here. If OK, I'll push it in the master.

**Comment by jonrumsey** [comment]
Thanks for the quick response, your proposed fixes solve the problem.

**Comment by monnerat** [comment]
Thanks for your help in testing this fix. Commited in master now: https://github.com/curl/curl/commit/3b548ffde9f0ea85dd320ae6af23a2e3fdbb6d29
