### ISSUE TITLE
http/2 connection unnecessary closed when single transfer stopped

### ISSUE THREAD

**Issue by bagder** [curl/curl#2237]
### I did this

"lali .cpp" [reported this issue on the mailing list](https://curl.haxx.se/mail/lib-2018-01/0056.html):

>The client gives the server 1 second to respond, the server intentionally
> chooses a random value between 0 to 2000 ms to wait before replying to the
> client. So sometimes the request doesn't "complete" and so libcurl
> "tearsdown" the connection when curl_multi_remove_handle is called(which
> ideally it shouldn't for http2)

There are example code provided by the reporter to reproduce the issue in the email.

### I expected the following

If the connection is setup, removing an individual HTTP/2 transfer should not close the connection.

### curl/libcurl version

libcurl 7.57.0

### operating system

Probably not relevant

**Comment by dhakiptk** [comment]
[patch.txt](https://github.com/curl/curl/files/1634489/patch.txt)
I am attaching a patch. Do you think that it makes sense. I am able to see that it fixes the issues of connection "teardown", but want to be sure that it won't cause problems elsewhere(especially in the curl_multi_cleanup API).

**Comment by bagder** [comment]
Yes, I think it should be fine! @dhakiptk, can you make a PR out of this so that we get some tests run on it before we merge? (if not, I can do it for you)

**Comment by dhakiptk** [comment]
Thank you very much for including these changes.
