### ISSUE TITLE
Android 5.0 "error: only position independent executables (PIE) are supported."

### ISSUE THREAD

**Issue by yxm4109** [curl/curl#2241]
### when i push the curl and openssl to /system/bin but it not work,
the error info is:  "error: only position independent executables (PIE) are supported."

**Comment by jay** [comment]
according to [android 5.0 release notes](https://source.android.com/security/enhancements/enhancements50):

> non-PIE linker support removed. Android now requires all dynamically linked executables to support PIE (position-independent executables). This enhances Android’s address space layout randomization (ASLR) implementation.

so I guess you will need to provide some switch for PIE

**Comment by bagder** [comment]
@yxm4109: can you please tell us why this is (curl) problem?

**Comment by bagder** [comment]
Not clear how this is really a (curl) bug and no response on clarification requests.
