### ISSUE TITLE
digest auth return 401 auth failed

### ISSUE THREAD

**Issue by michaelllh** [curl/curl#2243]
### I did this
Everthing works fine.Suddenly ,Server went wrong ,reply a 401 auth failed. And I re-enter the username and password to curl, curl return 401. Server using digest auth method.
curl get response from server:
 HTTP/1.1 401 Anonymous Request Disallowed
and it directly return the result, did not continue to send auth info to server
### I expected the following
Not get 401. Auth success.
### curl/libcurl version
7.52.1
[curl -V output]

### operating system
Linux

**Comment by jay** [comment]
What makes you think this is a curl problem? The server is expected to send a WWW-Authenticate digest header in the 401 reply. If it does not then curl cannot continue.

**Comment by michaelllh** [comment]
I did not say it is a curl problem. Just want to discuss with this problem.
The  server did reply header with WWW-Authenticate: Digest and other auth method option Basic/Negotiate/NTLM, In the whole process ,Only one request get result like this ,others were getting a 401 auth failed and then request again and get a 200OK success result.

**Comment by jay** [comment]
Just to be clear are you saying that of many requests that used --digest, you received one reply that was a 401 Anonymous Request Disallowed _and_ had a WWW-Authenticate digest header _and_ curl did not follow up? Is it reproducible, and can you please check the verbose output and also try the latest curl.

**Comment by michaelllh** [comment]
Ok, Thanks ,I will try.

**Comment by bagder** [comment]
This sounds like a server problem. If you still think it is a curl problem, please show us the exact headers curl sends and receives so that we can help analyze them (and we can re-open this issue). If you're only asking questions about curl, please use a dedicated curl mailing list instead.
