### ISSUE TITLE
cURL does not work with URL containing special characters

### ISSUE THREAD

**Issue by marcomarsala** [curl/curl#2244]
### I did this
curl "https://www.astegiudiziarie.it/vendita-asta-appartamento-genova-via-san-giovanni-d'acri-14-1360824"

### I expected the following
It should download the same page you can see with a web browser. Instead, the server replies with a server error page because it got a badly encoded URL.

### curl/libcurl version
7.47.0

[curl -V output]
url 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

### operating system
tested on Windows 10 and Ubuntu

**Comment by bagder** [comment]
You have a single quote in there that confuses the shell so your given command line doesn't seem to work at all. If you put that URL within double quotes however, it seems to work fine for me:

    curl -L "https://www.astegiudiziarie.it/vendita-asta-appartamento-genova-via-san-giovanni-d'acri-14-1360824"

**Comment by marcomarsala** [comment]
Sorry for the typo, however I was running it with double quotes.
`curl -L "https://www.astegiudiziarie.it/vendita-asta-appartamento-genova-via-san-giovanni-d'acri-14-1360824"` gives incorrect results. The returned page is an error page (you can read the message "La richiesta effettuata non può essere elaborata a causa di un problema di natura tecnica." that is an error message in Italian language). If you load the same page in a web browser, you'll get the correct result.

The URL is sent with bad encoding for special characters. A modern web browser will URLencode the "path" part of the URL.

**Comment by bagder** [comment]
> A modern web browser will URLencode the "path" part of the URL.

Yes, and curl will instead insist that the URL you give it is the URL you want to work with so any encoding needs to be done by you.

"modern web browsers" have decided to break compatibility with URLs the way curl speaks them (RFC 3986) with their WHATWG URL spec and for several reasons curl do not adhere to that spec - the overlap is however significant so it is only causing a problem to users occasionally. I find this unfortunate and believe me I've tried hard to make the WHATWG understand and respect non-browsers more and better, but that's a battle I find very lonely.

So no, curl does not "re-encode" the URL for you.

**Comment by bagder** [comment]
Closing this as I don't consider this to be a curl bug.
