### ISSUE TITLE
Build errors with MSVC2012

### ISSUE THREAD

**Issue by AngelTs** [curl/curl#2253]
It is impossible to add my static lib (which use curl-7.26.0) to my exe project in MSVC2012.
-Compiling only of this lib is ok and without warnings or errors!
-Without this lib my exe compiles and works correct!!!
-With this lib (but with disabled curl-7.26.0) my exe compiles and works correct!!!
-Compiling of curl-7.26.0 is passed without warnings or errors in MSVC2012!
So many combinations, so many tires, 2 days are gone with this s...t
Just for comparison how "good" is curl-7.26.0: pcre-7.9 and pthreads-2.9.1 works ok in my static lib->placed in my exe, only curl not work!!!

ERRORS:
2>lib-vanitygenplus-oclvanityminer.lib(strequal.obj) : error LNK2019: unresolved external symbol __imp__strnicmp referenced in function _curl_strnequal
2>OLDNAMES.lib(strnicmp.obi) : error LNK2001: unresolved external symbol __imp__strnicmp
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_init referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_unbind_s referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_set_option referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_simple_bind_s referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_search_s referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_msgfree referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_err2string referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_first_entry referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_next_entry referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_first_attribute referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_next_attribute referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_get_values_len referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_value_free_len referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_get_dn referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_memfree referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ber_free referenced in function _Curl_ldap
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : error LNK2019: unresolved external symbol __imp__fileno referenced in function _file_upload
2>OLDNAMES.lib(fileno.obi) : error LNK2001: unresolved external symbol __imp__fileno
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : error LNK2019: unresolved external symbol __imp__close referenced in function _file_done
2>OLDNAMES.lib(close.obi) : error LNK2001: unresolved external symbol __imp__close
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : error LNK2019: unresolved external symbol __imp__open referenced in function _file_connect
2>OLDNAMES.lib(open.obi) : error LNK2001: unresolved external symbol __imp__open
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : error LNK2019: unresolved external symbol __imp__read referenced in function _file_do
2>OLDNAMES.lib(read.obi) : error LNK2001: unresolved external symbol __imp__read
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : error LNK2019: unresolved external symbol __imp___fstat64 referenced in function _file_do
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : error LNK2019: unresolved external symbol __imp___stat64 referenced in function _AddFormData
2>E:\MyProjects\angelcoin-0.8.6.2-portedMSVC2012\MSVC\Win32\Debug\\AngelcoinQt.exe : fatal error LNK1120: 24 unresolved externals

WARNINGS:
lib-vanitygenplus-oclvanityminer.lib(strerror.obj) : warning LNK4217: locally defined symbol _strerror imported in function _Curl_strerror
2>lib-vanitygenplus-oclvanityminer.lib(netrc.obj) : warning LNK4049: locally defined symbol _strncpy imported
2>lib-vanitygenplus-oclvanityminer.lib(strerror.obj) : warning LNK4217: locally defined symbol _strncpy imported in function _Curl_strerror
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _strncpy imported
2>lib-vanitygenplus-oclvanityminer.lib(telnet.obj) : warning LNK4049: locally defined symbol _strncpy imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strncpy imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strrchr imported
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : warning LNK4049: locally defined symbol _strrchr imported
2>lib-vanitygenplus-oclvanityminer.lib(strerror.obj) : warning LNK4217: locally defined symbol _strrchr imported in function _Curl_strerror
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4049: locally defined symbol _strrchr imported
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4049: locally defined symbol _strrchr imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _strrchr imported
2>lib-vanitygenplus-oclvanityminer.lib(strerror.obj) : warning LNK4217: locally defined symbol ___sys_nerr imported in function _Curl_strerror
2>lib-vanitygenplus-oclvanityminer.lib(easy.obj) : warning LNK4217: locally defined symbol _strdup imported in function _curl_easy_init
2>OLDNAMES.lib(strdup.obi) : warning LNK4049: locally defined symbol _strdup imported
2>lib-vanitygenplus-oclvanityminer.lib(easy.obj) : warning LNK4217: locally defined symbol _calloc imported in function _curl_easy_init
2>lib-vanitygenplus-oclvanityminer.lib(md5.obj) : warning LNK4049: locally defined symbol _free imported
2>lib-vanitygenplus-oclvanityminer.lib(easy.obj) : warning LNK4217: locally defined symbol _free imported in function _curl_easy_init
2>lib-vanitygenplus-oclvanityminer.lib(dict.obj) : warning LNK4049: locally defined symbol _free imported
2>lib-vanitygenplus-oclvanityminer.lib(gopher.obj) : warning LNK4049: locally defined symbol _free imported
2>lib-vanitygenplus-oclvanityminer.lib(http_proxy.obj) : warning LNK4049: locally defined symbol _free imported
2>lib-vanitygenplus-oclvanityminer.lib(easy.obj) : warning LNK4217: locally defined symbol _malloc imported in function _curl_easy_init
2>lib-vanitygenplus-oclvanityminer.lib(dict.obj) : warning LNK4049: locally defined symbol _malloc imported
2>lib-vanitygenplus-oclvanityminer.lib(md5.obj) : warning LNK4049: locally defined symbol _malloc imported
2>lib-vanitygenplus-oclvanityminer.lib(easy.obj) : warning LNK4217: locally defined symbol _realloc imported in function _curl_easy_init
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _isdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol _isdigit imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4049: locally defined symbol _isdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(mprintf.obj) : warning LNK4217: locally defined symbol _isdigit imported in function _dprintf_DollarString
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4049: locally defined symbol _isdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(smtp.obj) : warning LNK4049: locally defined symbol _isdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _isdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(mprintf.obj) : warning LNK4217: locally defined symbol ___iob_func imported in function _curl_mprintf
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol ___iob_func imported in function _cookie_output
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol ___iob_func imported
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : warning LNK4049: locally defined symbol ___iob_func imported
2>lib-vanitygenplus-oclvanityminer.lib(mprintf.obj) : warning LNK4217: locally defined symbol _fputc imported in function _curl_mfprintf
2>lib-vanitygenplus-oclvanityminer.lib(mprintf.obj) : warning LNK4217: locally defined symbol _sprintf imported in function _dprintf_formatf
2>lib-vanitygenplus-oclvanityminer.lib(smtp.obj) : warning LNK4049: locally defined symbol _strtol imported
2>lib-vanitygenplus-oclvanityminer.lib(tftp.obj) : warning LNK4049: locally defined symbol _strtol imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strtol imported
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol _strtol imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(mprintf.obj) : warning LNK4217: locally defined symbol _strtol imported in function _dprintf_Pass1
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _strtol imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _strtol imported
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4049: locally defined symbol _strtol imported
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol _strchr imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(http_digest.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(curl_gethostname.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(inet_pton.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(dict.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _strchr imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(strtok.obj) : warning LNK4049: locally defined symbol _strchr imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _strncmp imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(connect.obj) : warning LNK4049: locally defined symbol _strncmp imported
2>lib-vanitygenplus-oclvanityminer.lib(rtsp.obj) : warning LNK4217: locally defined symbol _strncmp imported in function _Curl_rtsp_parseheader
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol _strncmp imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : warning LNK4049: locally defined symbol _fclose imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _fclose imported in function _Curl_cookie_init
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _fclose imported
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4049: locally defined symbol _fclose imported
2>lib-vanitygenplus-oclvanityminer.lib(netrc.obj) : warning LNK4049: locally defined symbol _fclose imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _fgets imported in function _Curl_cookie_init
2>lib-vanitygenplus-oclvanityminer.lib(netrc.obj) : warning LNK4049: locally defined symbol _fgets imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _fopen imported in function _Curl_cookie_init
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4217: locally defined symbol _fopen imported in function _file_connect
2>lib-vanitygenplus-oclvanityminer.lib(netrc.obj) : warning LNK4049: locally defined symbol _fopen imported
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : warning LNK4049: locally defined symbol _fopen imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _fputs imported in function _cookie_output
2>lib-vanitygenplus-oclvanityminer.lib(rtsp.obj) : warning LNK4217: locally defined symbol _sscanf imported in function _rtsp_do
2>lib-vanitygenplus-oclvanityminer.lib(socks.obj) : warning LNK4217: locally defined symbol _sscanf imported in function _Curl_SOCKS5
2>lib-vanitygenplus-oclvanityminer.lib(http_proxy.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(telnet.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _sscanf imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(hostip.obj) : warning LNK4217: locally defined symbol _sscanf imported in function _create_hostcache_id
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _sscanf imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol _qsort imported in function _Curl_cookie_getlist
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4049: locally defined symbol __strtoi64 imported
2>lib-vanitygenplus-oclvanityminer.lib(http_proxy.obj) : warning LNK4217: locally defined symbol __strtoi64 imported in function _Curl_proxyCONNECT
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol __strtoi64 imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol __strtoi64 imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol __strtoi64 imported
2>lib-vanitygenplus-oclvanityminer.lib(imap.obj) : warning LNK4049: locally defined symbol __strtoi64 imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol __strtoi64 imported
2>lib-vanitygenplus-oclvanityminer.lib(tftp.obj) : warning LNK4049: locally defined symbol __time64 imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol __time64 imported
2>lib-vanitygenplus-oclvanityminer.lib(cookie.obj) : warning LNK4217: locally defined symbol __time64 imported in function _Curl_cookie_add
2>lib-vanitygenplus-oclvanityminer.lib(hostip.obj) : warning LNK4217: locally defined symbol __time64 imported in function _Curl_global_host_cache_init
2>lib-vanitygenplus-oclvanityminer.lib(curl_rand.obj) : warning LNK4049: locally defined symbol __time64 imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol __time64 imported
2>lib-vanitygenplus-oclvanityminer.lib(asyn-thread.obj) : warning LNK4217: locally defined symbol __errno imported in function _init_resolve_thread
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4217: locally defined symbol __errno imported in function _Curl_ftp_parselist
2>lib-vanitygenplus-oclvanityminer.lib(hostip.obj) : warning LNK4217: locally defined symbol _tolower imported in function _create_hostcache_id
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _tolower imported
2>lib-vanitygenplus-oclvanityminer.lib(tftp.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4217: locally defined symbol _strstr imported in function _concat_url
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(smtp.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _strstr imported
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4217: locally defined symbol _fread imported in function _Curl_readrewind
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4049: locally defined symbol _fread imported
2>lib-vanitygenplus-oclvanityminer.lib(formdata.obj) : warning LNK4217: locally defined symbol _fread imported in function _AddFormData
2>lib-vanitygenplus-oclvanityminer.lib(transfer.obj) : warning LNK4217: locally defined symbol _fseek imported in function _Curl_readrewind
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4217: locally defined symbol _isxdigit imported in function _parse_proxy
2>lib-vanitygenplus-oclvanityminer.lib(escape.obj) : warning LNK4049: locally defined symbol _isxdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4049: locally defined symbol _isxdigit imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4217: locally defined symbol _memmove imported in function _parseurlandfillconn
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4049: locally defined symbol _memmove imported
2>lib-vanitygenplus-oclvanityminer.lib(imap.obj) : warning LNK4049: locally defined symbol _memmove imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4217: locally defined symbol _fwrite imported in function _Curl_init_userdefined
2>lib-vanitygenplus-oclvanityminer.lib(sendf.obj) : warning LNK4049: locally defined symbol _fwrite imported
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4049: locally defined symbol _fwrite imported
2>lib-vanitygenplus-oclvanityminer.lib(url.obj) : warning LNK4217: locally defined symbol _strtoul imported in function _parse_remote_port
2>lib-vanitygenplus-oclvanityminer.lib(http_chunks.obj) : warning LNK4049: locally defined symbol _strtoul imported
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _strtoul imported
2>lib-vanitygenplus-oclvanityminer.lib(escape.obj) : warning LNK4049: locally defined symbol _strtoul imported
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4217: locally defined symbol _isalpha imported in function _parsedate
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4049: locally defined symbol _isalpha imported
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4217: locally defined symbol _isalnum imported in function _parsedate
2>lib-vanitygenplus-oclvanityminer.lib(rtsp.obj) : warning LNK4049: locally defined symbol _isalnum imported
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4049: locally defined symbol _isalnum imported
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4049: locally defined symbol _isalnum imported
2>lib-vanitygenplus-oclvanityminer.lib(parsedate.obj) : warning LNK4217: locally defined symbol __gmtime64 imported in function _Curl_gmtime
2>lib-vanitygenplus-oclvanityminer.lib(curl_threads.obj) : warning LNK4217: locally defined symbol __beginthreadex imported in function _Curl_thread_create
2>lib-vanitygenplus-oclvanityminer.lib(http_digest.obj) : warning LNK4217: locally defined symbol _isspace imported in function _Curl_input_digest
2>lib-vanitygenplus-oclvanityminer.lib(ftplistparser.obj) : warning LNK4049: locally defined symbol _isspace imported
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4049: locally defined symbol _isspace imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4217: locally defined symbol _isspace imported in function _Curl_add_custom_headers
2>lib-vanitygenplus-oclvanityminer.lib(ftp.obj) : warning LNK4049: locally defined symbol _isspace imported
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4049: locally defined symbol _isspace imported
2>lib-vanitygenplus-oclvanityminer.lib(rtsp.obj) : warning LNK4049: locally defined symbol _isspace imported
2>lib-vanitygenplus-oclvanityminer.lib(http.obj) : warning LNK4217: locally defined symbol _memchr imported in function _Curl_http_readwrite_headers
2>lib-vanitygenplus-oclvanityminer.lib(tftp.obj) : warning LNK4217: locally defined symbol _memchr imported in function _tftp_connect
2>lib-vanitygenplus-oclvanityminer.lib(progress.obj) : warning LNK4217: locally defined symbol _fflush imported in function _Curl_pgrsUpdate
2>lib-vanitygenplus-oclvanityminer.lib(telnet.obj) : warning LNK4217: locally defined symbol _atoi imported in function _check_telnet_options
2>lib-vanitygenplus-oclvanityminer.lib(file.obj) : warning LNK4217: locally defined symbol __lseeki64 imported in function _file_do
2>lib-vanitygenplus-oclvanityminer.lib(getenv.obj) : warning LNK4217: locally defined symbol _getenv imported in function _GetEnv
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4217: locally defined symbol _isupper imported in function _loop
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4217: locally defined symbol _islower imported in function _loop
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4217: locally defined symbol _isprint imported in function _loop
2>lib-vanitygenplus-oclvanityminer.lib(curl_fnmatch.obj) : warning LNK4217: locally defined symbol _isgraph imported in function _loop
2>OLDNAMES.lib(strdup.obi) : warning LNK4049: locally defined symbol __strdup imported
2>OLDNAMES.lib(stricmp.obi) : warning LNK4049: locally defined symbol __stricmp imported
2>OLDNAMES.lib(strnicmp.obi) : warning LNK4049: locally defined symbol __strnicmp imported
2>OLDNAMES.lib(fileno.obi) : warning LNK4049: locally defined symbol __fileno imported
2>OLDNAMES.lib(close.obi) : warning LNK4049: locally defined symbol __close imported
2>OLDNAMES.lib(open.obi) : warning LNK4049: locally defined symbol __open imported
2>OLDNAMES.lib(read.obi) : warning LNK4049: locally defined symbol __read imported

**Comment by bagder** [comment]
I recommend going with the latest release and follow the instructions in the `winbuild/` sub.directory. I don't know how you build your old version and I don't know what problems we might have had with it back then.

If you have questions or need help and assistance, ask on the curl-library mailing list. Many people build (lib)curl on Windows, our CI builds build every commit on Windows. We know it works, although it can of course always go wrong and the documentation can always be further improved.

**Comment by AngelTs** [comment]
latest release broke the links with other libraries and is potential mess^10=>so it is not an option

**Comment by jay** [comment]
> latest release broke the links with other libraries and is potential mess^10=>so it is not an option

You are using a version of libcurl from 5+ years ago. Please use the latest version since we cannot investigate problems from that long ago. In Windows if you build a static libcurl you will have to define CURL_STATICLIB in your program before the libcurl includes. Based on your output though it looks like there is a CRT mismatch. You will need to resolve that, but it is not a curl problem. It looks like you have built the two libraries too differently to the point where they can't link together. We have a RTLIBCFG switch that can be used to link to the static CRT, if necessary (but I'm not sure that's what the problem is). Refer to the BUILD.WINDOWS.txt for more information.

**Comment by AngelTs** [comment]
Some kind of progression to reduce 31 errors and 160 warnings to 17 Errors:
In "vc6curl.dsw"->libcurl->Property Pages->C/C++->Code Generation->Runtime Library=replace "Multi-threaded Debug DLL" with "Multi-threaded Debug"

The 17 Errors are:
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_init referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_unbind_s referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_set_option referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_simple_bind_s referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_search_s referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_msgfree referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_err2string referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_first_entry referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_next_entry referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_first_attribute referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_next_attribute referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_get_values_len referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_value_free_len referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_get_dn referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ldap_memfree referenced in function __ldap_free_urldesc
2>lib-vanitygenplus-oclvanityminer.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp__ber_free referenced in function __ldap_free_urldesc
2>E:\MyProjects\angelcoin-0.8.6.2-portedMSVC2012\MSVC\Win32\Debug\\AngelcoinQt.exe : fatal error LNK1120: 16 unresolved externals

**Comment by AngelTs** [comment]
Finally I did it- O Errors, 0 Warnings, work OK:
Resolution:
In my static lib->Property Pages->Librarian->Additional Dependencies=add "Wldap32.lib"

I hope this to help to anyone in my situation (2 days are gone seeking solution about it)
