### ISSUE TITLE
command line arguments parse error

### ISSUE THREAD

**Issue by vvxvv** [curl/curl#2254]
### I did this
1. touch /tmp/file
2. curl -vs --upload-file /tmp/file -o /dev/null http://www.example.com/ 2>&1 | grep PUT 
output:
 PUT /file HTTP/1.1

### I expected the following
 PUT / HTTP/1.1

### curl/libcurl version
7.52.1 / 7.52.1

[curl -V output]
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.29.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by bagder** [comment]
This is totally intentional and documented:

> If there is no file part in the specified URL, curl will append the local file name.

**Comment by jay** [comment]
> This is totally intentional

+1 You have to specify the file to PUT to in the URL or curl will use the name of the upload file.
