### ISSUE TITLE
Wrong "msvcproj.head", "vc6libcurl.dsp" and "vc6curlsrc.dsp"

### ISSUE THREAD

**Issue by AngelTs** [curl/curl#2256]
Replace "/MDd" and "/MD" with respective "/MTd" and "/MT" for "LIB Debug" and "LIB Release" sections in these three files

**Comment by bagder** [comment]
Are you perhaps referring to old files we no longer have in git nor ship in releases? I can't find any such files ...

**Comment by jay** [comment]
As previously discussed you are using a version of libcurl that is over 5 years old and no longer supported. Those files no longer exist. Current Windows build methods that can use Visual Studio default to the CRT DLL. For winbuild if you want MT then use option RTLIBCFG. Refer to BUILD.WINDOWS.txt. For cmake if you want MT then use option CURL_STATIC_CRT. There's also premade VS project files in common configurations in projects/ (much like your vc6libcurl.dsp) and you would have to change to MT in C/C++ > Code Generation > Runtime Library (or something similar depending on your VS version).
