### ISSUE TITLE
Fix link to the second advisory in v7.58.0

### ISSUE THREAD

**Issue by dscho** [curl/curl#2261]
On https://curl.haxx.se/news.html, the link to https://curl.haxx.se/news.html points to https://curl.haxx.se/docs/adv_2013-b3bf.html but it wants to link to https://curl.haxx.se/docs/adv_2018-b3bf.html instead (note the 2013 -> 2018).

**Comment by bagder** [comment]
Thanks, fixed now in https://github.com/curl/curl-www/commit/927f3fa55d46c589fa!
