### ISSUE TITLE
Build: Redundant assignment of libraries like "LIBS = -lssl -lcrypto -lssl -lcrypto" in Makefile

### ISSUE THREAD

**Issue by dgdy9hvz** [curl/curl#2301]
There are two different versions of OpenSSL installed in the same computer. One is in "/opt/openssl" and the other is in "/usr".

The libraries of the former are `/opt/openssl/lib/libcrypto*` and `/opt/openssl/lib/libssl*`.

The libraries of the latter are `/usr/lib/libcrypto*` and `/usr/lib/libssl*`.

I want to build curl with the libraries from "/opt/openssl" but not from "/usr".

PkgConfig points at only "/opt/openssl" but not "/usr".

### I did this

    export PKG_CONFIG='/opt/pkg-config/bin/pkg-config'
    export PKG_CONFIG_PATH='/opt/pkg-config/lib/pkgconfig'
    ./configure --enable-static --enable-shared --without-zlib --disable-ldap

### what happened expectedly

config.log tells the following

    pkg-config: SSL_LIBS: "-lssl -lcrypto"
    pkg-config: SSL_LDFLAGS: "-L/opt/openssl/lib"
    pkg-config: SSL_CPPFLAGS: "-I/opt/openssl/include"

### I further expected the following

Makefile would tell the following

    LIBCURL_LIBS = -lssl -lcrypto
    LIBS = -lssl -lcrypto

### what happened unexpectedly

Makefile tells the following

    LIBCURL_LIBS = -lssl -lcrypto -lssl -lcrypto
    LIBS = -lssl -lcrypto -lssl -lcrypto

-lssl appears twice on each line.
-lcrypto appears twice on each line.

This doubleness is very confusing.  This doubleness makes me worry that both versions (`/opt/openssl/lib` and `/usr/lib`) of OpenSSL libraries will be mixedly linked/loaded.

### Further Consideration

`otool -L curl` and `otool -L libcurl.4.dylib` show that
OpenSSL libraries that "curl" or "libcurl.4.dylib" uses are
only those in "/opt/openssl/lib" but not in "/usr/lib".

However, since `otool -L` is not very helpful for static objects, I cannot tell whether "libcurl.a" has been built with OpenSSL libraries in "/opt/openssl/lib" or in "/usr/lib" or both.

If curl is actually built with OpenSSL libraries from only "/opt/openssl/lib" without any addition from "/usr/lib", then the configure script should cause Makefile to hold

    LIBCURL_LIBS = -lssl -lcrypto
    LIBS = -lssl -lcrypto

but not

    LIBCURL_LIBS = -lssl -lcrypto -lssl -lcrypto
    LIBS = -lssl -lcrypto -lssl -lcrypto

### environment

curl-7.58.0
Mac OS X

**Comment by bagder** [comment]
You can only use one openssl lib at a time, otherwise you see errors or complaints. If you invoke curl -V, you'll see which openssl version curl uses.

**Comment by jay** [comment]
The double inclusion should be harmless, but I don't know why it's happening. It may have to do with the way it's detected or special LIBS or something. Can you share the config.log? To your concern about where the shared libraries are loaded from, that depends on your loader. In Linux for example you can use LDFLAGS and set an rpath to force a location. I'm not sure how you would do that in Mac unix though.

**Comment by bagder** [comment]
No further info given after three weeks, nothing to act on. Closing.
