### ISSUE TITLE
pop3 stat command hangs

### ISSUE THREAD

**Issue by tester0077** [curl/curl#2309]
I am having the very same issue with curl under windows as the closed issue #1915 and I have left a comment there, but figured I should open a new issue

curl 7.58.0 (i386-pc-win32) libcurl/7.58.0 zlib/1.2.8
Release-Date: 2018-01-24
I can issue the command
```
curl --request UIDL -u userxxxx:password --url pop3://pop.myisp.net
and get the expected output. but
curl --request STAT -u userxxxx:password --url pop3://pop.myisp.net
```
hangs
I am relatively new to curl itself and I also have tested this problem in DOS Box on Win 10 because I had similar issues using the same version libcurl and the STAT command, using the STAT sample from the curl website, compiled under MSVC.

Running the sample STAT code actually seems to work in that the server responds ( as verified by a capture of the conversation using Wireshark) and provides the information, but nothing ever shows in the DOS box. (I suppose the curl_easy_setopt(curl, CURLOPT_NOBODY, 1L); is the cause.

When running curl directly in a DOS box, the server also responds with the correct data, but since curl hangs, it never sends the QUIT command to close the transaction and again, the user sees nothing and has to terminate curl with Ctrl-C.
If I replace `curl_easy_setopt(curl, CURLOPT_NOBODY, 1L); `in the sample with
```
struct MemoryStruct chunk;
/* send all data to this function */
curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);

/* we pass our 'chunk' struct to the callback function */
curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&chunk);_
```
Then the 'modified' sample code act as the direct call to curl - the server responds with the correct data, but the sample never sends QUIT and instead hangs.

**Comment by monnerat** [comment]
The pop3 STAT command only returns a status line and no data, as expected by curl's custom command. curl is therefore waiting for data that never comes.
There is currently no way to submit such a "non-data" custom command with curl.

**Comment by tester0077** [comment]
Is there then a way to at least obtain at least the status line?

**Comment by bagder** [comment]
> There is currently no way to submit such a "non-data" custom command with curl.

The `CURLOPT_NOBODY` option, as set with -I / --head, is typically the "do everything but don't get the data from the transfer" instruction for other protocols. Would it make sense to have that work for this as well?

**Comment by tester0077** [comment]
I'd very much like to be able to retrieve whatever the remote end sends as reply to a command.
For instance, the POP server I am working with, replies with the data equivalent to the CAPA command and it would be useful to have that information without having to send the same command again later.
In my case, adding the CURL_NOBODY option allows things to not hang. 
Still having the data from the STAT command would also help as it contains information which would be useful and might avoid sending further requests.

**Comment by tester0077** [comment]
Finally found curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_callback);
which seems to give me the information I was looking for in 'buffer'
