### ISSUE TITLE
HTTP headers are delivered in pieces

### ISSUE THREAD

**Issue by bagder** [curl/curl#2314]
### I did this

Get a HTTP response with one or more headers longer than 16K. Get the headers sent to the header callback in 16K pieces.

### I expected the following

To get the full headers delivered to the `CURLOPT_HEADERFUNCTION` as per the documentation.

### curl/libcurl version

current git master

### operating system

any

Reported-by: Guido Berhoerster
Bug: https://curl.haxx.se/mail/lib-2018-02/0056.html

**Comment by jay** [comment]
See #801 which went stale when I moved on to other things. There might be something salvageable in there
