### ISSUE TITLE
curl_easy_getinfo() failed: A libcurl function was given a bad argument

### ISSUE THREAD

**Issue by Nicanord** [curl/curl#2321]
### I did this

~~~c
#include <stdio.h>
#include <curl/curl.h>

int main(void)
{
  CURL *curl;
  CURLcode res;
  
  curl = curl_easy_init();
  if(curl) {
    
    curl_easy_setopt(curl, CURLOPT_URL, "http://example.com");
    res = curl_easy_perform(curl);

    if(CURLE_OK == res) {
        long port_number;
        res = curl_easy_getinfo(curl, CURLINFO_LOCAL_PORT, &port_number);
        
        if(CURLE_OK == res) {
        printf("We used local port_number: %ld\n", port_number);
        }
        else {
            fprintf(stderr, "curl_easy_getinfo() failed: %s\n", curl_easy_strerror(res));
        }
    }
        /* always cleanup */
        curl_easy_cleanup(curl);
    }
    return 0;
}
~~~
### I expected the following
~~~
<!doctype html>
<html>
........
</html>
We used local port_number: XXXXX
~~~
### Actual result:
~~~
<!doctype html>
<html>
........
</html>
curl_easy_getinfo() failed: A libcurl function was given a bad argument
~~~

### curl/libcurl version
curl 7.59.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.59.0-DEV OpenSSL/1.0.1e zlib/1.2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy

### operating system
CentOS 6.9

**Comment by jay** [comment]
> curl_easy_getinfo() failed: A libcurl function was given a bad argument

I can't reproduce. Also I've walked through it in master 2427d94 2018-02-20 and I don't see how it could possibly happen, CURLE_BAD_FUNCTION_ARGUMENT is not returned along any code path for that symbol. Check your curl_version() to see if your program is actually using an older version of libcurl.

**Comment by bagder** [comment]
Case closed. That version didn't support `CURLINFO_LOCAL_PORT`!
