### ISSUE TITLE
Curl https issue ssl3_get_record when behind proxy

### ISSUE THREAD

**Issue by neel** [curl/curl#2324]
This happens only when behind proxy (works fine when not behind proxy). I have tried switching different proxy servers from https://free-proxy-list.net/. Issue persists for all proxies.

### I did this
$ curl https://abcd
$ curl https://google.com
$ curl https://v4.ifconfig.co

curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
### I expected the following
HTTP output
### curl/libcurl version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
### operating system
Antergos

**Comment by bagder** [comment]
How exactly are you invoking curl? For example, what proxy type are you using/telling curl it is.

curl works with proxies for a lot of people (and is tested so in numerous test cases), please help us and mention an exact proxy name/instance that causes problems so that we can try to reproduce and understand what you're seeing.

**Comment by neel** [comment]
Yes I am using curl behind proxy for 3 years. This was embarrassing for me as well. I found something very interesting. I switched DE from `Deepin` to `Gnome` and now curl works fine as expected. I never expected a DE can cause curl not to work behind proxy. Possibly this is a Deepin Bug. Not Curl bug then.

**Comment by michalnik** [comment]
I have the same issue. Proxy is taken from environment look :

```bash
curl -v https://www.seznam.cz
* Rebuilt URL to: https://www.seznam.cz/
*   Trying 10.3.1.25...
* TCP_NODELAY set
* Connected to proxy.vlp.cz (10.3.1.25) port 3128 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
I set proxy i numerous ways see :
```bash
1)

cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

http_proxy="http://proxy.vlp.cz:3128/"
https_proxy="https://proxy.vlp.cz:3128/"

2)

    gsettings set org.gnome.system.proxy.http host "proxy.vlp.cz";
    gsettings set org.gnome.system.proxy.http port "3128";
    gsettings set org.gnome.system.proxy.https host "proxy.vlp.cz";
    gsettings set org.gnome.system.proxy.https port "3128";
    gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '::1']"
    gsettings set org.gnome.system.proxy mode manual;
```

This event/issue appeared after upgrade from 16.04 LTS to 18.04 LTS Ubuntu on my laptop. So you know, it is probably Ubuntu fail but what I should do?

**Comment by febzhang** [comment]
@jay works for me!

```
z@Z:~$ export https_proxy=https://192.168.x.x:8080/
z@Z:~$ curl https://google.com
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
z@Z:~$ export https_proxy=http://192.168.x.x:8080/
z@Z:~$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
z@Z:~$ 

```

**Comment by jarvisdev** [comment]
@jay dude I was getting the same error after **upgrading to 18.04 from 16.04**. In 16.04 this was working fine. I changed my https_proxy="**http**://..."and it worked. What is the reason behind it?

**Comment by jay** [comment]
> What is the reason behind it?

Older versions of curl like 7.35 silently ignored invalid proxy scheme https and treated it as http. Later versions like 7.50 showed an error. [Since 7.52](https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/) curl supports https proxies so https may be a valid proxy scheme.
