### ISSUE TITLE
Windows: No execute on suitable sections

### ISSUE THREAD

**Issue by rodwiddowson** [curl/curl#2328]
Over [Here ](https://curl.haxx.se/mail/lib-2018-02/0075.html)Daniel noted (channelling Stefan Kanthak):
-----------
Explicitly enable string pooling, COMDATs, ASLR and DEP alias "no execute"!

```
--- curl-7.58.0/winbuild/MakefileBuild.vc    2018-01-22 09:55
+++ curl-patch/winbuild/MakefileBuild.vc
@@ -112,2 +112,2 @@
-CFLAGS         = $(CFLAGS) /I"$(DEVEL_INCLUDE)"
-LFLAGS         = $(LFLAGS) "/LIBPATH:$(DEVEL_LIB)"
+CFLAGS         = $(CFLAGS) /I"$(DEVEL_INCLUDE)" /GA /GF /Gy
+LFLAGS         = $(LFLAGS) /LIBPATH:"$(DEVEL_LIB)" /DYNAMICBASE /FIXED:NO /NXCOMPAT /RELEASE
```
-------
Note(Rod)  that dynamic base is default since Longhorn/Vista (IIRC)

**Comment by bagder** [comment]
In case others too are curious on the suggestion options. I looked them up and here's a brief explanation and links. I think everyone except /GA sound sensible.

[/GA (Optimize for Windows Application)](https://msdn.microsoft.com/en-us/library/yetwazx6.aspx) includes this comment _"Using /GA for a DLL can result in bad code generation"_ - sounds like one we shouldn't use for libcurl code.

[/GF (Eliminate Duplicate Strings)](https://msdn.microsoft.com/en-us/library/s0s0asdt.aspx)

[/Gy (Enable Function-Level Linking)](https://msdn.microsoft.com/en-us/library/xsa71f43.aspx)

[/DYNAMICBASE (Use address space layout randomization)](https://msdn.microsoft.com/en-us/library/bb384887.aspx)

[/FIXED (Fixed Base Address)](https://msdn.microsoft.com/en-us/library/w368ysh2.aspx) 

[/NXCOMPAT (Compatible with Data Execution Prevention)](https://msdn.microsoft.com/en-us/library/ms235442.aspx)

[/RELEASE (Set the Checksum)](https://msdn.microsoft.com/en-us/library/h8ksa72a.aspx)

**Comment by mkauf** [comment]
From the linked documentation:
* /GF: "is in effect when /O1 or /O2 is used"
* "By default, /DYNAMICBASE is on"
* "By default, /NXCOMPAT is on"

So these options are not needed for the current version of Visual C++.

But maybe it makes sense to specify /DYNAMICBASE and /NXCOMPAT anyway for older versions of Visual C++. These parameters have been introduced in Visual C++ 2005: https://blogs.msdn.microsoft.com/vcblog/2009/05/21/dynamicbase-and-nxcompat/

**Comment by jay** [comment]
I think we can narrow this down to /NXCOMPAT and /DYNAMICBASE (implies FIXED:NO) which were as @mkauf said added in VS2005. They were enabled in 2008 by default but only for subsystem Vista and higher and since 2010 they're just the default. I think that's enough. A quick way to add it though would be 

```
!IF "$(VC)"=="8" || "$(VC)"=="9"
LFLAGS  = $(LFLAGS) /NXCOMPAT /DYNAMICBASE
!ENDIF
```

that doesn't cover if VC isn't defined

**Comment by mkauf** [comment]
The corresponding MinGW options are ``-Wl,--nxcompat`` and ``-Wl,--dynamicbase``

**Comment by jay** [comment]
can we just assume if not msvc then gcc or what else are people using with cmake

**Comment by bagder** [comment]
Since all the important options are enabled by default in modern compiler versions, I figure we're rather just encourage people to use them and leave this as-is. Closing.
