### ISSUE TITLE
Use call rather than batch scripts directly

### ISSUE THREAD

**Issue by rodwiddowson** [curl/curl#2330]
Over [Here ](https://curl.haxx.se/mail/lib-2018-02/0075.html) @bagder noted (channelling Stefan Kanthak):
-----------

Apply the following changes to "winbuild/Makefile.vc" to fix build errors when AppLocker or SAFER alias Software Restriction Policies are in effect

```
--- curl-7.58.0/winbuild/Makefile.vc    2018-01-22 09:55
+++ curl-patch/winbuild/Makefile.vc
@@ -251,1 +251,1 @@
-    @gen_resp_file.bat $(LIBCURL_OBJS)
+    @CALL gen_resp_file.bat $(LIBCURL_OBJS)
```

```
--- curl-7.58.0/winbuild/Makefile.vc    2018-01-22 09:55
+++ curl-patch/winbuild/Makefile.vc
@@ -256,1 +256,1 @@
-    @gen_resp_file.bat $(CURL_OBJS)
+    @CALL gen_resp_file.bat $(CURL_OBJS)
```

Always use CALL to run batch scripts!

**Comment by MarcelRaad** [comment]
Looks good to me. Would you create a PR?
