### ISSUE TITLE
mac: libcurl version doesnt provide needed version

### ISSUE THREAD

**Issue by steventheuniverse** [curl/curl#2338]
>>> import UnbinnedAnalysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/StevenZakirov/Desktop/Fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python/UnbinnedAnalysis.py", line 12, in <module>
    import pyLikelihood as pyLike
  File "/Users/StevenZakirov/Desktop/Fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/python/pyLikelihood.py", line 7, in <module>
    import lib_pyLikelihood
ImportError: dlopen(/Users/StevenZakirov/Desktop/Fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/lib_pyLikelihood.so, 2): Library not loaded: /opt/local/lib/libcurl.4.dylib
  Referenced from: /Users/StevenZakirov/Desktop/Fermi/ScienceTools-v11r5p3-fssc-20180124-x86_64-apple-darwin16.7.0/x86_64-apple-darwin16.7.0/lib/libxerces-c-3.1.dylib
  Reason: Incompatible library version: libxerces-c-3.1.dylib requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

**Comment by bagder** [comment]
libcurl doesn't provide needed version of what? This report is highly confusing...

**Comment by steventheuniverse** [comment]
basically, I'm trying to install the software Enrico to run Fermi Science tools and it requires me to check if the python support of ST is installed and from what I can see the reason is libcurl.4.dylb doesn't provide the right version of the support libxerces-c-3.1.dylib needs.

**Comment by jay** [comment]
> Incompatible library version: libxerces-c-3.1.dylib requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0

> basically, I'm trying to install the software Enrico to run Fermi Science tools and it requires me to check if the python support of ST is installed and from what I can see the reason is libcurl.4.dylb doesn't provide the right version of the support libxerces-c-3.1.dylib needs.

You probably have multiple versions of libcurl installed (homebrew?) and the wrong one is being loaded. I'm not sure how to work around that on Mac.

**Comment by bagder** [comment]
> from what I can see the reason is libcurl.4.dylb doesn't provide the right version

That sounds like an installation problem in your system and not a curl bug.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
