### ISSUE TITLE
Missing File / Manual Edit

### ISSUE THREAD

**Issue by VR51** [curl/curl#2342]
The manual references formfind.pl at around line [302](https://github.com/curl/curl/blob/2d5fa35e85c6e0ba84e6922e321bbe3a4511cdf9/docs/MANUAL). Formfind is apprently no longer a member of the included Curl packages. I have added a backup of the orignal formfind.pl file [here](https://github.com/VR51/formfind/blob/master/formfind.pl).

Should Formfind still be mentioned in Curl's documentation, should it be re-added to the package list or should the docs be updated to state that formfind.pl can be found via an internet search? Either way, thought I'd let you know about the oversight.

**Comment by bagder** [comment]
Thanks!

**Comment by VR51** [comment]
You are welcome!

**Comment by monnerat** [comment]
> Edit to add: I've just realised your personal GitHub repository is where I originally found formfind back in 2010/11.

Since git keeps the whole history, you can even still retrieve it from the official repo, for example at https://github.com/curl/curl/blob/3a973517a915ce4ad408d239f9220b869ff8cf40/perl/contrib/formfind :-)
