### ISSUE TITLE
passing an object that undergoes default argument promotion to 'va_start' has undefined behavior

### ISSUE THREAD

**Issue by pps83** [curl/curl#2344]
```In file included from ../../App/util/libcurl.c:291:
../../ThirdParty/curl/lib\../lib/easy.c:397:17: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
  va_start(arg, tag);
                ^
../../ThirdParty/curl/lib\../lib/easy.c:388:50: note: parameter of type 'CURLoption' is declared here
CURLcode curl_easy_setopt(CURL *curl, CURLoption tag, ...)
                                                 ^
../../ThirdParty/curl/lib\../lib/easy.c:866:17: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]
  va_start(arg, info);
  ```

I think latest curl also has identical issue if compiled with clang and `-Werror,-Wvarargs`

**Comment by monnerat** [comment]
By googling around, I've found https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-support/nss/nss/disable-Wvarargs-with-clang.patch that can help understand the problem and workaround.
I've also found comments stating this occurs with clang 3.9, but not with 4.0.
Changing the curl_easy_setopt() tag type would probably break the ABI on many platforms.

**Comment by MarcelRaad** [comment]
That was fixed with https://github.com/curl/curl/commit/f8548e84adc4cc55c274beb23690b8a5f5b827bf.

**Comment by monnerat** [comment]
@MarcelRadd: Thanks for pointing it. Closing.
