### ISSUE TITLE
Retry on any error

### ISSUE THREAD

**Issue by gtirloni** [curl/curl#2350]
I understand there have been many issues and emails discussions when curl should retry connections, what is a transient error, etc.

I'm opening this issue to suggest curl could offer an option (e.g. `--retry-always`) where it would retry regardless if the error is transient or a not according to curl's understanding, since that's frequently open for interpretation.

My use case currently is that we're testing an application that misbehaves on the first request with a ECONNRESET error and curl fails to retry even with `--retry --retryconnrefused`. Yes, the application should be fixed but I'm not in the position of fixing it so I would like curl to retry, regardless of the error. Everything will be fine on the 2nd attempt.

As curl is our swiss-army knife, I think it would be nice if it offered this flexibility (otherwise we have to wrap it in some error detection code).

**Comment by bagder** [comment]
I consider this to be basically the same idea already summed up here: https://curl.haxx.se/docs/todo.html#retry_on_network_is_unreachable

Someone just needs to go ahead and write code for it.

**Comment by bagder** [comment]
Feel free to work on this and ideally submit a PR. But since this isn't a bug or a problem, I'm closing this issue.

**Comment by gtirloni** [comment]
@bagder Agreed, thanks. I'll give it a shot.
