### ISSUE TITLE
NO_PROXY doesn't work for IPv6 literals.

### ISSUE THREAD

**Issue by steelman** [curl/curl#2353]
I use TOR as a proxy. TOR actually refuses to establish connection to localhost, so I set NO_PROXY
```
NO_PROXY=localhost,127.0.0.1,::1
```
It enables connections to http://localhost and http://127.0.0.1 and does not work for http://[::1] at all.
Apparently the problem is caused by an [assumption](https://github.com/curl/curl/blob/7e35eb77292fe6464889ddc8329c6a64136f969d/lib/url.c#L2577) that a hostname cannot contain a colon.

**Comment by bagder** [comment]
Yes, seems like an accurate observation. Time to add a test case with an IPv6 numerical for this too...

**Comment by bagder** [comment]
It'd be great if you can just verify my patch in #2355. I'll try to add a test case for it before I merge anyway.

**Comment by steelman** [comment]
I will verify it. You, however, may consider documenting the format of IPv6 entries in  NO_PROXY, with or without square brackets. If I undetstand the patch brackets are required in NO_PROXY. I am not sure this is good.

**Comment by bagder** [comment]
Docs is good indeed. But no, the brackets are not used in the NO_PROXY list. They are however mandatory in the URL itself.

**Comment by steelman** [comment]
Works for me (-:
