### ISSUE TITLE
configure.ac failed to generate configure

### ISSUE THREAD

**Issue by zhangysh1995** [curl/curl#2360]
### I did this
For some reasons, I need to use `autotools` to build this project. 
````
zhangysh1995@ubuntu-zhangyushao:~/data/curl$ mkdir build
zhangysh1995@ubuntu-zhangyushao:~/data/curl$ cd build/
zhangysh1995@ubuntu-zhangyushao:~/data/curl/build$ ../configure.ac 
../configure.ac: line 22: dnl: command not found
../configure.ac: line 24: syntax error near unexpected token `2.57'
../configure.ac: line 24: `AC_PREREQ(2.57)'
````

`autoconf` infomation:
````
zhangysh1995@ubuntu-zhangyushao:~/data/curl/build$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
...
````
And the [doc](https://curl.haxx.se/docs/install.html) tells to use `./configure`, while there is no such a file.

### I expected the following
generate correct  `configure` file

### curl/libcurl version
newest

[curl -V output] _not used_

### operating system
Ubuntu 16.04 latest docker image

**Comment by jzakrzewski** [comment]
It looks like you're building from the git sources instead of release tarball. I'd suggest to use the tarball or take a look at the [GIT-INFO](https://github.com/curl/curl/blob/master/GIT-INFO)

**Comment by zhangysh1995** [comment]
Thanks! closed.
