### ISSUE TITLE
curl_version_info() documentation is out of date

### ISSUE THREAD

**Issue by lietusme** [curl/curl#2364]
I was searching how to identify SSL backend in runtime, got to this page:
https://curl.haxx.se/libcurl/c/curl_version_info.html

> ssl_version is an ASCII string for the **_OpenSSL version_** used. If libcurl has no SSL support, this is NULL.

In reality ssl_version returns these values when built with different backends:
"WinSSL"
"SecureTransport"
"OpenSSL/1.1.0g"
etc.

Used ibcurl/7.57.0.

Fix would be documentation side I guess, to avoid future confusion. Documenting if this is good way for checking SSL backend would be also useful, I found only this on topic: https://curl.haxx.se/mail/lib-2015-09/0083.html and used empiric methods to get to implementation:

```
        auto info = curl_version_info(CURLVERSION_NOW);
        if (nullptr != info && nullptr != info->ssl_version && nullptr != strstr(info->ssl_version, "OpenSSL"))
```

**Comment by bagder** [comment]
Any chance you want to work on fixing this and submitting a PR for it?

**Comment by bagder** [comment]
Thanks!
