### ISSUE TITLE
install package on raspberry pi

### ISSUE THREAD

**Issue by yonghuming** [curl/curl#2370]
the bin file on codewith.mu site could not install on raspberry
any install package

**Comment by yonghuming** [comment]
there is no plotter on raspberry 1.0.0 beta 15

**Comment by monnerat** [comment]
This issue tracker is about curl, a file transfer client tool and library.

Are you sure you reported at the correct place ???

**Comment by monnerat** [comment]
Some reporter's activity since last comment on what seems to be the right tracker (https://github.com/mu-editor/mu/issues/375). Closing.
