### ISSUE TITLE
Configuring for cross compile fails at conftest

### ISSUE THREAD

**Issue by luii** [curl/curl#2374]
Im trying to cross compile libcurl
I did everything according to `docs/Install.md` 

### I did this

```bash
PATH: '/home/luii/Dokumente/git/nodeos-libcurl/node_modules/nodeos-cross-toolchain/bin:/home/luii/.nvm/versions/node/v9.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl',
CROSS_COMPILE: 'x86_64-nodeos-linux-musl',
  AR: 'x86_64-nodeos-linux-musl-ar',
  AS: 'x86_64-nodeos-linux-musl-as',
  LD: 'x86_64-nodeos-linux-musl-ld',
  RANLIB: 'x86_64-nodeos-linux-musl-ranlib',
  CC: 'x86_64-nodeos-linux-musl-gcc',
  NM: 'x86_64-nodeos-linux-musl-nm',
  CXX: 'x86_64-nodeos-linux-musl-g++' 
```

`./configure --with-random=/dev/urandom --disable-manual --disable-shared --enable-static --build=x86_64-cross-linux-gnu --host=x86_64-cross-linux-gnu --target=x86_64-nodeos-linux-musl --prefix=/home/luii/Dokumente/git/nodeos-libcurl/out/nocona`

### got following

https://hastebin.com/jasejomika.makefile

```bash
configure:4772: $? = 1
configure:4791: checking whether the C compiler works
configure:4813: x86_64-nodeos-linux-musl-gcc    conftest.c  >&5
configure:4817: $? = 0
configure:4865: result: yes
configure:4868: checking for C compiler default output file name
configure:4870: result: a.out
configure:4876: checking for suffix of executables
configure:4883: x86_64-nodeos-linux-musl-gcc -o conftest    conftest.c  >&5
configure:4887: $? = 0
configure:4909: result: 
configure:4930: checking whether we are cross compiling
configure:4938: x86_64-nodeos-linux-musl-gcc -o conftest    conftest.c  >&5
configure:4942: $? = 0
configure:4949: ./conftest
./configure: line 4951: ./conftest: No such file or directory
configure:4953: $? = 127
configure:4960: error: in `/home/luii/Dokumente/git/nodeos-libcurl/deps/curl':
configure:4962: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

### I expected the following

To configure properly but it fails to find ./conftest

### curl/libcurl version

`7.57.0`

### operating system

Arch Linux

**Comment by bagder** [comment]
Something is truly wrong since it isn't supposed to try to run programs when cross-compiling...

**Comment by luii** [comment]
@bagder Do you have a Idea what can cause this. I think it's a fault i caused but i didn't changed anything big because it worked flawlessly before. If i try to compile it without any Flags or args it runs just fine.

**Comment by luii** [comment]
Somehow the `configure` command doesn't like the `--build=x86_64-cross-linux-gnu` option.
