### ISSUE TITLE
Cannot link custom OpenSSL when pkg-config and a system OpenSSL are present

### ISSUE THREAD

**Issue by vojtechkral** [curl/curl#2378]
### I did this
I have OpenSSL 1.0.1 and pkg-config installed in the system.
I tried running `./configure` with either

- `PKG_CONFIG_PATH=...`
- `PKG_CONFIG_LIBDIR=...`
- `--with-ssl=...`

and also with all of them present, but could not make libcurl link against my own OpenSSL build. I had to either remove the system OpenSSL package and then the pkg-config env vars would work, or remove the pkg-config package and then `--with-ssl` would work. But with both packages present in the system, it seems there's no way to make libcurl link against my OpenSSL build.

### I expected the following
Link against my own OpenSSL build

### curl/libcurl version
7.58.0

### operating system
Debian Jessie

**Comment by bagder** [comment]
Is your custom build using shared libs or static? If shared, how did you make sure curl used the custom build at run time?

**Comment by vojtechkral** [comment]
@bagder 

> Is your custom OpenSSL build using shared libs or static?

Both. In this particular case, shared libs are used.

> If shared, how did you make sure curl used the custom build at run time?

Well, the usecase is packaging our application using AppImage. In general the build should also be able to produce static binaries.

However, the problem is apparent by just running `./configure`, since it prints out the version of OpenSSL that it found and I can see it's a wrong one. Of course, this causes problems at runtime too, because OpenSSL 1.1 lacks some symbols that are present in older versions ...

**Comment by vojtechkral** [comment]
Also, another thing that makes the problem harder to work around it that when `pkg-config` is present on the build system, curl's `configure` script apparently completely ignores the `--with-ssl=...` path and simply uses whatever pkg-config knows about.

**Comment by vojtechkral** [comment]
Ok, so it looks like I had an incorrect (default) prefix in my OpenSSL build, which curl's `configure` ends up using via `pkg-config` to locate headers. With the prefix set to the OpenSSL build location and with the `--with-ssl=...` option I am able to build libcurl against the right OpenSSL.

My takeaway is this is not a bug in curl's build per se, however, I still find it kind of confusing that `--with-ssl=...` behaves differently depending on the presence of pkg-config. Ideally I'd welcome the option to disable pkg-config usage entirely in `configure`.

**Comment by bagder** [comment]
Whenever you have a configure problem, any configure problem really, the key is almost always stored in the `config.log` file after a completed invoke. I'm pretty sure it contains clues for this case as well.

But then I'm not sure why you would insist on building without pkg-config? That comes by default with an OpenSSL build + install, doesn't it?

**Comment by jay** [comment]
> Edit: It seems that without pkg-config, --with-ssl=... doesn't work at all for me. The pkg-config + --with-ssl=... combo seems to be the only one working for me right now, the PKG_* env vars don't work and also openssl needs to not be installed, otherwise I am getting:

I have two installations of OpenSSL in Ubuntu and I use --with-ssl to the _installed_ prefix for the one I want, `--with-ssl=/usr/local/ssl`. That should be all that is needed. If that doesn't work please show us the command line you ran and upload your config.log and we'll take a look.

**Comment by vojtechkral** [comment]
> Whenever you have a configure problem, any configure problem really, the key is almost always stored in the `config.log` file after a completed invoke. I'm pretty sure it contains clues for this case as well.

Got it. I'll look for it.

> But then I'm not sure why you would insist on building without pkg-config? That comes by default with an OpenSSL build + install, doesn't it?

Actually it wasn't present on one of my systems and OpenSSL built fine. I don't necessarily need to build without pkg-config, I'm just looking for a setup that works and has as few assumptions about packages installed on the build system as possible... Ie. one that doesn't break when a package is installed or removed on the build system (because of some other reason).

I was generally tring to follow [this document](https://github.com/curl/curl/blob/master/docs/INSTALL.md).

**Comment by vojtechkral** [comment]
[Here's the `config.log`](https://gist.githubusercontent.com/vojtechkral/bc61f2aac8c242426b4663f0973fdcef/raw/4224177a556cf6f56fa78e9c198e8f106ffe5ecc/config.log) file.

I suspect the problem might be this:

    LDFLAGS='-L/usr/lib/x86_64-linux-gnu -L/home/user/slic3r-destdir/usr/local/lib'

Seems to me if there are openssl libs in `/usr/lib/x86_64-linux-gnu`, they will get precedence over the ones in the  custom path.

**Comment by 3081629721m** [comment]
Everybody is good I have a problem Ask the questions about apple ID lock of mobile solutions The amount of lock with ID lock phone and all the ID of the machine is not account and password can't activate cell phones are forgotten password and account Can't find these materials has a lot of these phones being thrown into the secondary market cheap processing If can unlock or online can do cell phones with cable to connect the computer ID lock The market chain huge economic benefits If you have to do You can contact me can cooperation can long-term money a lot of money

My contact email: 3081629721 @qq.com

Have to solve this ID lock can see back to you to contact me for cooperation

**Comment by bagder** [comment]
> Seems to me if there are openssl libs in /usr/lib/x86_64-linux-gnu, they will get precedence over the ones in the custom path

Yes, because that's exactly what your `LDFLAGS` tells the linker!

**Comment by bagder** [comment]
I suspect it is your pkg-config for zlib that brings that `-L` option to `LDFLAGS`

**Comment by vojtechkral** [comment]
@bagder Yes, most likely that's what's going on. What is the recommended approach here? I suppose I could install zlib into the same dir where the custom openssl build is installed...

I presume my setup is non-standard enough to be in the "you're on your own" bucket...

**Comment by jay** [comment]
> I suspect it is your pkg-config for zlib that brings that -L option to LDFLAGS

pkg-config is not supposed to add standard lib locations to its --libs output for exactly this reason. If it is doing that it is a bug. I think there is one other report here of that happening but I can't find it atm. If it is not doing that and you are doing it manually then you will need to stop doing that. You may need to reorder your locations manually as well.
