### ISSUE TITLE
make -v write to stdout

### ISSUE THREAD

**Issue by toStronger** [curl/curl#2385]
### I did this
curl -v -k url > a.txt
### I expected the following
i wish -v`s info will be in a.txt, but actually, only the response will be in a.txt
### curl/libcurl version
didn`t care, at least the last vesion
[curl -V output]
didn`t care, at least the last vesion
### operating system
didn`t care, mostly windows & linux

**Comment by jzakrzewski** [comment]
Works as intended. The output of `-v` goes to stderr so you'd have to redirect this one also. For example like this:
```sh
curl -v -k url > a.txt 2>&1
```

**Comment by bagder** [comment]
As @jzakrzewski says, it works as intended and also, changing this behavior would break countless scripts and command lines so it's also not possible to change.
