### ISSUE TITLE
Documentation is missing for CURLINFO_SSL_VERIFYRESULT

### ISSUE THREAD

**Issue by komar007** [curl/curl#2400]
The documentation for CURLINFO_SSL_VERIFYRESULT (`docs/libcurl/opts/CURLINFO_SSL_VERIFYRESULT.3`)  does not explain the meaning of the value stored in the third argument of `curl_easy_getinfo`.
The source code suggests that 0 means success, non-zero - verification error.
It also seems that the example given contradicts the actual behavior of the library, printing "fine" on verification error, and "BAAAD" when the verification is ok.

**Comment by bagder** [comment]
Yeah, the example seems reversed... and from all I can tell, `CURLINFO_SSL_VERIFYRESULT` is only set by the NSS and OpenSSL/libressl/boringssl backends...

**Comment by bagder** [comment]
The value is specific for the TLS backend curl is built to use so I don't think we will document the values any further than so. To get a feel for what the values mean in OpenSSL, check out their [x509_vfy.h file](https://github.com/openssl/openssl/blob/master/include/openssl/x509_vfy.h#L99-L186).
