### ISSUE TITLE
type checker for c++

### ISSUE THREAD

**Issue by pps83** [curl/curl#2404]
That would be nice to have it for c++ (in gcc and clang at least).

https://github.com/curl/curl/blob/ea233e5b4b3a3a3ca1d2d92c7d686c3a7341eaee/include/curl/curl.h#L2763

Perhaps this option should be off by default for c++, pretty sure most of c++ project will fail this check.

**Comment by bagder** [comment]
Right. Which is why it already is off when included by a C++ compiler! See the condition on the line above the #include...

**Comment by pps83** [comment]
But there is no way to enable it without changing the code, that's why I created this ticket. I'm using curl in c++ and I'd like to update my code to use correct types and use typechecker in c++

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
