### ISSUE TITLE
The example of "asiohiper" cause exception on win7

### ISSUE THREAD

**Issue by cimstu** [curl/curl#2407]
### I did this
trying to run asiohiper,when I set a invalid systerm proxy by some tools(proxifier on my pc), it must cause crash! 
when the systerm proxy is valid it works well!

### curl/libcurl version
7.52.1

[curl -V output]
These are asiohiper outputs, call stack in the attachment
timer_cb:
multi_timer_cb: timeout_ms 2
REMAINING: 1
timer_cb:
multi_timer_cb: timeout_ms 2
REMAINING: 1
timer_cb:
multi_timer_cb: timeout_ms 2
REMAINING: 1
timer_cb:
multi_timer_cb: timeout_ms 2
REMAINING: 1
timer_cb:
multi_timer_cb: timeout_ms 2
REMAINING: 1
timer_cb:
opensocket :
Opened socket 148*   Trying 46.82.174.68...
* TCP_NODELAY set

sock_cb: socket=148, what=2, sockp=00000000
socket callback: s=148 e=003320A8 what=OUT
Adding data: OUT
setsock: socket=148, act=2, fdp=003285C0
watching for socket to become writable
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

### operating system
win7 64bit
vs2005
[callstacks.txt](https://github.com/curl/curl/files/1828634/callstacks.txt)

**Comment by cimstu** [comment]
anyone help?
i tried asiohiper example on vs2017 , it' s still crash!

**Comment by bagder** [comment]
Set a break-point and figure out what's wrong?

**Comment by cimstu** [comment]
I know little about asio, so even i got the call stacks i can do nothing 
so I want a health and strong example.

**Comment by bagder** [comment]
I think the problem with that example exists exactly because nobody with knowledge about both asio and libcurl has taken a proper look at it. I know next to nothing about asio myself and I'm sorry but fixing up that example is very low on my personal TODO list.

**Comment by virtulis** [comment]
I'm trying to reproduce this and failing.

Which Boost version are you using? Could it be one released before this commit?

https://github.com/boostorg/asio/commit/a50a3503109d938a36211a272b3d3bd6b729d4c1#diff-52db8b158e9995dce1dbce6c9ed95425

**Comment by virtulis** [comment]
Scratch that, I managed to reproduce the crash, but **only** when you try proxying access to 127.0.0.1 with Proxifier (whether the actual proxy works or not doesn't seem to matter) (why would anyone actually do that?).

**Comment by virtulis** [comment]
It seems that the crash happens because `async_write_some` expects the socket to *not be* in an errored state *already*. I added a kludge here that seems to help but I'm not entirely sure that it's a good solution or that it doesn't introduce other problems.

https://github.com/virtulis/curl/commit/c874ca9fa5835604a3ba71c3b6cbfff9dd199824

**Comment by bagder** [comment]
@cimstu does that fix your issue?
