### ISSUE TITLE
need a specification of "-b -" in the man page

### ISSUE THREAD

**Issue by mudongliang** [curl/curl#2410]
### Description

When our group did fuzzing about curl, we found a seed input which makes curl hang on there.
After we analyzed the problem, we found we have one string "-b-" inside the config file and curl asked input content. So it hangs on.

### curl/libcurl version

curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 zlib/1.2.8
Release-Date: 2017-08-14
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: Debug TrackMemory IPv6 Largefile libz UnixSockets 

### operating system

Ubuntu 14.04 LTS

**Comment by bagder** [comment]
Thanks, the man page is now updated! (the web version will reflect this soon too, but it can take up to 24 hours until it does)
