### ISSUE TITLE
expose URL parser

### ISSUE THREAD

**Issue by lambdafu** [curl/curl#2412]
Does libcurl expose the URL parser within curl?  Using a different URL parser can lead to security problems, for example when matching the target domain (see https://docs.google.com/presentation/d/e/2PACX-1vSTFsJ9t0DatXbjmEGL8sKxt53gf6a1djHp_8Wbj2ZeTB6IfR-HsRD537-L5PgzVrs97bJu1tzJ1Smo/pub?start=false&loop=false&delayms=60000&slide=id.g32d0ed6ec2_0_41).

It would be good if libcurl could expose the URL parser, so it can be reused and/or tested against alternative implementations.

**Comment by bagder** [comment]
This is an issue tracker, not a question or support forum. We have dedicated [mailing lists](https://curl.haxx.se/mail/) for that.

We've had requests for URL parsing APIs for a long time and I would like to see it added, but so far nobody has done the necessary work...
