### ISSUE TITLE
"An unknown option was passed in to libcurl" when using -O option in 7.59.0

### ISSUE THREAD

**Issue by Bazze** [curl/curl#2413]
Our docker image builds stopped working yesterday with the error `An unknown option was passed in to libcurl`. After some investigation we found it's failing on our installation of pip where we are downloading the `get-pip.py` script using `curl -O`.

Feels like it could be related to latest curl release?

### I did this
```
curl -O https://bootstrap.pypa.io/get-pip.py
```

### I expected the following
The `get-pip.py` file to be downloaded to current directory

### I got this error
```
/opt/app # curl -O https://bootstrap.pypa.io/get-pip.py
curl: (48) An unknown option was passed in to libcurl
```

### curl/libcurl version
```
/opt/app # curl -V
curl 7.59.0 (x86_64-alpine-linux-musl) libcurl/7.57.0 OpenSSL/1.0.2j zlib/1.2.8 libssh2/1.7.0
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

### operating system
Alpine 3.4.6
```
/opt/app # cat /etc/alpine-release
3.4.6
/opt/app # uname -a
Linux ddd8585d376e 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 Linux
```

**Edit:** I just want to add that I can verify that it was working perfectly fine with curl 7.58.0-r1 in the same setup.

**Comment by jzakrzewski** [comment]
It seems you have mixed up your libraries. The curl executable is 7.59.0 and curl library 7.57.0. They should be equal or it's possible that the newer binary would try to set an option that the library doesn't know.

**Comment by Bazze** [comment]
Ah, nice spotting! Didn't see the libcurl version mismatched. However, curl is installed through the alpine package manager. I guess I should head over there and see what might have gone wrong.

**Comment by bagder** [comment]
I think this can be said to be **working as intended** ... I suppose ideally it should say something more about what exact option that was tried as well.

**Comment by Bazze** [comment]
Thanks, bug created over at Alpine instead. https://bugs.alpinelinux.org/issues/8703

Closing this.

**Comment by Bazze** [comment]
FYI: Issue was not in alpine package repository but actually due to docker image layer cache. My theory: A parent image had installed curl and then uninstalled curl, but libcurl was still there (with an old version) causing the curl install in a sub image to get the latest curl client version but not libcurl. 🤔
