### ISSUE TITLE
Unexpected file type.

### ISSUE THREAD

**Issue by em92** [curl/curl#2422]
### I did this
curl -v -L https://cdni.rt.com/russian/images/2018.03/original/5ab3ab7e183561ab028b45d3.jpg >1.jpg

### I expected the following
Valid downloaded jpeg file. But no.

### If I do this
curl -v -L https://cdni.rt.com/russian/images/2018.03/original/5ab3ab7e183561ab028b45d3.jpg >1.jpg.gz

I receive valid jpg file in gzip. In both situations I get "content-encoding: gzip", so I expect curl to decode this.

### curl/libcurl version

curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 GnuTLS/3.5.8 zlib/1.2.8 libidn/1.33 libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets 

### operating system
Debian 9
`Linux eugene-pc 4.5.0-2-amd64 #1 SMP Debian 4.5.5-1 (2016-05-29) x86_64 GNU/Linux`

**Comment by bagder** [comment]
See the man page and [--compressed](https://curl.haxx.se/docs/manpage.html#--compressed). curl does not uncompress by default.

**Comment by em92** [comment]
Thanks
