### ISSUE TITLE
--max-time parameter does not accept decimal precision

### ISSUE THREAD

**Issue by gersonfs** [curl/curl#2426]
### I did this

https://ec.haxx.se/usingcurl-timeouts.html

./curl --max-time 5.5 https://example.com/
curl: option --max-time: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information

### I expected the following
5.5s max-time timeout

### curl/libcurl version

curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.0.2k zlib/1.2.7
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy 

### operating system

CentOS 7

**Comment by bagder** [comment]
Cannot reproduce. Tried 7.58.0 and 7.60.0-DEV. This feature has existed since 7.32.0 with commit d8c04909fa.

**Comment by gersonfs** [comment]
I downloaded the source and compiled the curl because the version that comes with CentOS 7 is 7.29.0, which did not support decimal values.
I compiled with
./configure --prefix = ...
make && make install
Missing any parameters?

**Comment by bagder** [comment]
I would guess that your curl then finds the older libcurl in your system and uses that unless you've taken measures to fix it. But your curl -V output looks correct.

A test would be to set `LD_LIBRARY_PATH` to your new libcurl dir and see if that makes a difference.

**Comment by gersonfs** [comment]
``export LD_LIBRARY_PATH=/opt/onehost/curl/lib:$LD_LIBRARY_PATH
root@brasil11 /opt/onehost/curl/bin # echo $LD_LIBRARY_PATH 
/opt/onehost/curl/lib:
root@brasil11 /opt/onehost/curl/bin # /opt/onehost/curl/bin/curl --max-time 5.5 https://example.com
curl: option --max-time: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
root@brasil11 /opt/onehost/curl/bin # /opt/onehost/curl/bin/curl -V
curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.0.2k zlib/1.2.7
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy 
``

Crazy

**Comment by bagder** [comment]
Very puzzling!

**Comment by bagder** [comment]
Is your locale possibly not using a dot for numerical fractions?

**Comment by gersonfs** [comment]
Of course, I did not think of this possibility.
I tried with a comma and it worked. Thank you and sorry for the inconvenience.

**Comment by bagder** [comment]
I think we should probably clarify that detail in the docs...

**Comment by gersonfs** [comment]
Yes, it will help.
