### ISSUE TITLE
build-openssl.bat dont have option for custom path for VS and perl

### ISSUE THREAD

**Issue by patelvivekv1993** [curl/curl#2430]
### I did this
 I was trying to use the .bat file to build openssl but it was saying visual studio not found even if it was installed. On inspecting i found visual studio was installed on a different path in my PC. Similarly for the perl library no custom path can be set if user is having portable library.
### I expected the following
.bat file should be able to provide multiple options to the user.
### curl/libcurl version
v1.3
[curl -V output]

### operating system
Windows

**Comment by patelvivekv1993** [comment]
I would like to contribute and make the .bat file more generalized. Let me know if this issue is accepted.

**Comment by bagder** [comment]
Please go ahead, I'm sure it'll be appreciated!

**Comment by bagder** [comment]
See also #2189
