### ISSUE TITLE
ABI breakage, cannot run application due to CURL_OPENSSL_3 issue

### ISSUE THREAD

**Issue by probonopd** [curl/curl#2433]
### I did this

Run application (that uses libcurl) compiled on Ubuntu 14.04 on a Ubuntu 18.04 target system

### I expected the following

Application runs

### curl/libcurl version

libcurl.so.4 CURL_OPENSSL_3

![](https://user-images.githubusercontent.com/1345457/37701513-3ff574e2-2d2a-11e8-9ba0-1d93b97368da.png)

### operating system

Ubuntu 18.04

---

https://curl.haxx.se/libcurl/abi.html states a notable goal:

> In the vast majority of all cases, a typical libcurl upgrade does not break the ABI at all. Your application can remain using libcurl just as before, only with less bugs and possibly with added new features. 

However: 

> The previous major library soname number bumps (breaking backwards compatibility) have happened the following times (...)

The latest one listed there is libcurl 7.16.0 from October 2006. 

Why then is it not possible to run an application which was compiled on Ubuntu 14.04 on a Ubuntu 18.04 target system?

Reference:
https://github.com/getinsomnia/insomnia/issues/805

**Comment by bagder** [comment]
That symbol looks like something Debian/Ubuntu have introduced. There is no such name in any curl source code or build script that comes from us. So, no, we didn't break the ABI as you show and we can't take responsibility for what distributors and others do with the libcurl versions they ship. Sorry. I'd advice you to take this discussion to your distribution and see what you and they can do to improve things now and for the future.

**Comment by probonopd** [comment]
Thanks @bagder for the clarification.

**Comment by jay** [comment]
Possibly related: https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294

**Comment by probonopd** [comment]
Is there a way for libcurl3 and libcurl4 to coexist?

**Comment by bagder** [comment]
> Is there a way for libcurl3 and libcurl4 to coexist?

From a pure libcurl and SONAME angle: sure. If you can install both versions at the same time on debian/ubuntu? Probably not.

> And why can Debian decide to introduce a new version of libcurl when in fact there isn't? Is that good practice?

That seems like a question to ask Debian people.

**Comment by jay** [comment]
Yes. It's a distro issue you'll have to wait and see what they do with it. There is a difference between libcurl so 3 and 4 but it appears they had some compatibility layer that broke.

**Comment by probonopd** [comment]
On Ubuntu 18.04 applications compiled against an older version of libcurl (e.g.: Spotify) fail with the error `version `CURL_OPENSSL_3' not found`. A workaround that works for me is to bundle a private copy of libcurl with the application.

Reference:
https://github.com/AppImage/AppImages/issues/187#issuecomment-385532167

**Comment by DavidLDawes** [comment]
I'm taking a loom, will follow up.

**Comment by DavidLDawes** [comment]
If you run this command:
``` sudo apt-get install libgconf-2-4 ```
The Agama wallet will run properly after.
I ran it in the Agama-linux-x64 directory.

**Comment by DavidLDawes** [comment]
Looks like after the libgconf install I hit the issue you ran into in libcurl, so I'm looking at that now.

**Comment by DavidLDawes** [comment]
I was able to get it to work by installing libgconf-2-4 then libcurl3.
Install libgconf-2-4 with apt-get:
``` sudo apt-get install libgconf-2-4 ```
Then add a mirror to the list in /etc/apt/sources.list, I added 
``` deb http://security.ubuntu.com/ubuntu xenial-security main ```
and finally install libcurl3
``` sudo apt-get install libcurl3 ```
