### ISSUE TITLE
Feature request: Display human-readable exit code status text

### ISSUE THREAD

**Issue by DaveJarvis** [curl/curl#2437]
The information at https://ec.haxx.se/usingcurl-returns.html is quite useful. It would be helpful if it was possible to generate that documentation from cURL itself.

**Replicate**
In Windows (UNIX would be similar):

1. curl --fail --silent https://slartybartfastinator.com
1. curl --help-exit %ERRORLEVEL%

**Expected Results**
Console shows:
> Couldn't resolve host. The given remote host's address was not resolved. The address of the given server could not be resolved. Either the given host name is just wrong, or the DNS server is misbehaving and doesn't know about this name when it should or perhaps even the system you run curl on is misconfigured so that it doesn't find/use the correct DNS server.

**Actual Results**
Console shows:
```
curl: option --help-exit: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

**Additional Details**
Having https://ec.haxx.se/usingcurl-returns.html and the code in cURL use the same source for the textual content would be ideal. Such as:

```
<?xml version="1.0"?>
<help>
<error level="6">
<summary>Couldn't resolve host.</summary>
<description>The given remote host's address was not resolved. The address of the given server could not be resolved. Either the given host name is just wrong, or the DNS server is misbehaving and doesn't know about this name when it should or perhaps even the system you run curl on is misconfigured so that it doesn't find/use the correct DNS server.</description>
</error>
</help>
```

This would lead naturally to:

```
curl --help-exit-summary %ERRORLEVEL%
curl --help-exit-description %ERRORLEVEL%
```

**Comment by bagder** [comment]
So this would just be a way to express the error in more words and save the user from having to use the manual to understand it?

**Comment by DaveJarvis** [comment]
> So this would just be a way to express the error in more words...

The use case is for when cURL is wrapped in a script, such as:

```batch
      set "CMD_CURL=curl --fail --silent --insecure --globoff"

      %CMD_CURL% !REQUEST_URL! > %FILE_JSON%

      IF NOT ERRORLEVEL 0 (
        echo cURL responded with error level %ERRORLEVEL%
        echo See https://ec.haxx.se/usingcurl-returns.html
        exit /b
      )
```

It would be quite convenient to inform the user of the error directly:

```batch
      set "CMD_CURL=curl --fail --silent --insecure --globoff"

      %CMD_CURL% !REQUEST_URL! > %FILE_JSON%

      IF NOT ERRORLEVEL 0 (
        set EXIT_LEVEL=%ERRORLEVEL%
        %CMD_CURL% --help-exit-summary %EXIT_LEVEL%

        IF "%ARG_DEBUG%"=="true" %CMD_CURL% --help-exit-description %EXIT_LEVEL%
        exit /b
      )
```

Also, on Windows (I know...) there are no man pages for cURL.

**Comment by bagder** [comment]
I'm not at all convinced this is a good idea, and we don't keep feature-requests around here.

A script that wants to display an explanation can easily just extract the list from the documentation and show the appropriate one on demand.

I'm closing this issue now. If you want to drum up some more interest from others for this idea, I suggest you ask for support on the curl-users mailing list and see if others are interested.
