### ISSUE TITLE
Compiling libcurl with mbedTLS 2.8.0 (compiled with MBEDTLS_DEPRECATED_REMOVED) fails

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#2442]
### I did this

We compiled the current version of mbedTLS (2.8.0) with "MBEDTLS_DEPRECATED_REMOVED", and we compiled libcurl to reference that library. Compilation of libcurl fails with:

```
../lib/.libs/libcurl.a(libcurl_la-mbedtls.o): In function `Curl_mbedtls_sha256sum':
vtls/mbedtls.c:(.text.Curl_mbedtls_sha256sum+0xa): undefined reference to `mbedtls_sha256'
```

### I expected the following

Successful compilation.

### curl/libcurl version

7.59.0

### operating system

Linux / FreeBSD

### Fix:

In "lib/vtls/mbedtls.c" change the include from: "`mbedtls_sha256(`" to "`mbedtls_sha256_ret(`"

The [`mbedtls_sha256()` was recently deprecated](https://tls.mbed.org/api/sha256_8h.html#a25c94940f4217c4dd7ad6a4e7da61b47) (and replaced with `mbedtls_sha256_ret()`).

**Comment by bagder** [comment]
Thanks, any chance you can make a PR with the fix that also makes older versions still work?

**Comment by wyattoday** [comment]
Sure, I’ll put it together on Monday.

**Comment by jay** [comment]
> Sure, I’ll put it together on Monday.

I started on this but I didn't finish, maybe you can pick up where I stopped. This is what I have so far:
~~~diff
diff --git a/lib/vtls/mbedtls.c b/lib/vtls/mbedtls.c
index 28251a3..f679793 100644
--- a/lib/vtls/mbedtls.c
+++ b/lib/vtls/mbedtls.c
@@ -1029,7 +1029,11 @@ static void Curl_mbedtls_sha256sum(const unsigned char *input,
                                     size_t sha256len UNUSED_PARAM)
 {
   (void)sha256len;
+#if MBEDTLS_VERSION_NUMBER < 0x02070000
   mbedtls_sha256(input, inputlen, sha256sum, 0);
+#else
+  mbedtls_sha256_ret(input, inputlen, sha256sum, 0);
+#endif
 }
 
 static void *Curl_mbedtls_get_internals(struct ssl_connect_data *connssl,
~~~

Basically the functions are the same except the old one returns void and the new one returns int, but it doesn't say in [the documentation](mbedtls_sha256_ret) what the return values are. Looking at [the code](https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.7.0/library/sha256.c) I can see 0 is returned on success and from what I see in the functions it is always success. The commit that added it ARMmbed/mbedtls@72a7f53 says it was done for hardware accelerators. Regardless, at some point it could return a value != 0. To address this properly I think would be to change our sha256sum to return a CURLcode the same as we do with md5sum already:

https://github.com/curl/curl/blob/4d6bd91ab33328c6d27eddc32e064defc02dc4fd/lib/vtls/vtls.h#L73-L76

Then once that is changed you would need to go through all the other backend files in vtls/ and change their sha256 prototypes to match and return CURLE_OK. For mbedtls fail case the closest thing we have I guess is CURLE_BAD_FUNCTION_ARGUMENT. Then go into whatever is calling the abstract vtls sha256sum and check the return code != CURLE_OK like CURLcode x = Curl_ssl->sha256sum(... ; if x != CURLE_OK return x;

**Comment by wyattoday** [comment]
Thanks Jay. Still testing the changes with the return code for all the sha256() variants . Should have the completed pull request sometime tomorrow.

**Comment by wyattoday** [comment]
Thanks for merging. Closing this issue.
