### ISSUE TITLE
curl + IIS 10.0 with Negotiate:Kerberos auth problem

### ISSUE THREAD

**Issue by DarovskikhAndrei** [curl/curl#2449]
Environment:
IIS 10.0 (Windows 10 component). Public site with Windows auth Negotiate:Kerberos + NTLM.
Authentication is customized: 
system.webServer/security/authorization like as
```
        <security>
            <authorization bypassLoginPages="false">
                <add accessType="Allow" users="<domain\someuser>" />
            </authorization>
        </security>
```
Host in domain. <domain\someuser> = current user in domain.

exec: 
curl http://server/site -u ":" --negotiate
has status code 401 (auth failed)

curl http://server/site -u ":" --ntlm
has status code 200 (auth accepted)

curl 7.59 (and 7.57)

**Comment by michael-o** [comment]
Just showing a 401 isn't enough. We need OS, MIT Kerberos version, verbose output and `KRB5_TRACE` enabled.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
