### ISSUE TITLE
curl dont work with russian charaters in Windows

### ISSUE THREAD

**Issue by vitassecuriti** [curl/curl#2454]
### I did this
     
I send GET a request I use curl from the command line Windows 7
codepage = 866
> > curl -v "http://crierbot.appspot.com/R4M8OiI1Ec3G6huozgdUZT7e9jnPpKyW/send?mess
> ge=Hello"
>    Trying 64.233.161.153...
>  TCP_NODELAY set
>  Connected to crierbot.appspot.com (64.233.161.153) port 80 (#0)
>  GET /R4M8OiI1Ec3G6huozgdUZT7e9jnPpKyW/send?message=Hello HTTP/1.1
>  Host: crierbot.appspot.com
>  User-Agent: curl/7.59.0
>  Accept: */*
> 
>  HTTP/1.1 200 OK
>  Content-Type: text/html; charset=utf-8
>  Cache-Control: no-cache
>  X-Cloud-Trace-Context: 01b0e53a7b486f82445eaded3698f0ad
>  Date: Wed, 04 Apr 2018 08:40:52 GMT
>  Server: Google Frontend
>  Content-Length: 0
> 
>  Connection #0 to host crierbot.appspot.com left intact

Everything works

But, if I use the Russian symbols in the text of inquiry, I receive a mistake

> >curl -v "http://crierbot.appspot.com/R4M8OiI1Ec3G6huozgdUZT7e9jnPpKyW/send?mess
age=Привет"
*   Trying 64.233.161.153...
* TCP_NODELAY set
* Connected to crierbot.appspot.com (64.233.161.153) port 80 (#0)
> GET /R4M8OiI1Ec3G6huozgdUZT7e9jnPpKyW/send?message=Привет HTTP/1.1
> Host: crierbot.appspot.com
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html; charset=utf-8
< Cache-Control: no-cache
< X-Cloud-Trace-Context: 28a6c43ba37c9cd0b3d75629f8b00406
< Date: Wed, 04 Apr 2018 08:42:43 GMT
< Server: Google Frontend
< Content-Length: 3173
<
<html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1535,
in __call__
    rv = self.handle_exception(request, response, e)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1529,
in __call__
    rv = self.router.dispatch(request, response)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1278,
in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1102,
in __call__
    return handler.dispatch()
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 572, i
n dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 570, i
n dispatch
    return method(*args, **kwargs)
  File &quot;/base/data/home/apps/s~crierbot/20171026t112333.405066909921162586/
main.py&quot;, line 83, in get
    message = self.request.get('message')
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 175, i
n get
    param_value = self.get_all(argument_name)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 212, i
n get_all
    param_value = self.params.getall(argument_name)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webob-1.1.1/webob/multidict.py&quot;, line
327, in getall
    return map(self._decode_value, self.multi.getall(self._encode_key(key)))
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_lib/versions/third_party/webob-1.1.1/webob/multidict.py&quot;, line
301, in _decode_value
    value = value.decode(self.encoding, self.errors)
  File &quot;/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipp
ed/python27_dist/lib/python2.7/encodings/utf_8.py&quot;, line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 0: invalid c
ontinuation byte
</pre>
  </body>
</html>* Connection #0 to host crierbot.appspot.com left intact

I tried to change the code page, but the mistake remains (1251,65001,866)

### I expected the following

I expect that a request will be sent and I will receive the answer.
HTTP/1.1 200 OK
### curl/libcurl version
>curl --version
curl 7.59.0 (x86_64-pc-win32) libcurl/7.59.0 OpenSSL/1.1.0h (WinSSL) zlib/1.2.11
 brotli/1.0.3 WinIDN libssh2/1.8.0 nghttp2/1.31.0
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s
 rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli
 TLS-SRP HTTP2 HTTPS-proxy MultiSSL

### operating system
Windows 7 x64 Pro

**Comment by bagder** [comment]
I'm afraid you're expecting curl to do something here that it won't.

curl supports and assumes URLs according to RFC 3986, which basically means you need to provide those Cyrillic (Russian) letters percent-encoded.

curl is very liberal in what it accepts here, so even when you provide a URL that contains letters curl itself doesn't really think are valid, it won't prevent them from being included and passed on in the request. The server most probably does not expect the bytes to appear like that though.

**Comment by vitassecuriti** [comment]
Thanks for the answer

but the same requests sent through curl with linux of cars go without problems.

**Comment by bagder** [comment]
That's because they're different requests. The windows character encoding CP-866 will send the Cyrillic differently, using different bytes, than a Linux command line (presumably using UTF-8). curl doesn't encode them in any way but will send them as you provide them on the command lines.

**Comment by bagder** [comment]
A URL according to curl should use ascii there, possibly url encoded. This is unfortunately not a bug. This is URLs being in a limbo when it comes to how they're supposed to work...
