### ISSUE TITLE
libcurl alternative to command one

### ISSUE THREAD

**Issue by su8** [curl/curl#2461]
What is the libcurl setopt alternative to **--write-out** `curl -o /dev/null -s -w "%{time_total}\n" wordpress.com` ?

I would like to write a program that returns the total time it took to [RTT](https://en.wikipedia.org/wiki/Round-trip_delay_time).

**Comment by bagder** [comment]
That's not a bug, so not a topic for this issue tracker. It is however an excellent question to ask on the curl-library mailing list, or to just check the code what it does... It says [CURLINFO_TOTAL_TIME](https://curl.haxx.se/libcurl/c/CURLINFO_TOTAL_TIME.html).
