### ISSUE TITLE
Curl multi_exec times out

### ISSUE THREAD

**Issue by ironusmaidenus** [curl/curl#2467]
Hello,

I am using the multi_exec example from the php.net website: 

http://php.net/manual/en/function.curl-multi-exec.php

And am running into an issue where it will continuously timeout 

### I did this

Copy example script from 

http://php.net/manual/en/function.curl-multi-exec.php 

Run

Times out
### I expected the following

I expected it to at least return an error. However it contentiously times out  until hitting max_execution_time 

The code sample provided by PHP seems to have worked at one point ( I assume because it's in php's documentation' ) 

### curl/libcurl version
cURL Information => 7.55.1

[curl -V output]

### operating system

Fedora 27

**Comment by bagder** [comment]
I'm afraid that's a PHP/CURL issue you should take to the PHP team, probably over at https://bugs.php.net/ . In the curl project (this tracker) we deal with the curl command line tool and the libcurl library, not the PHP binding. That's handled by the PHP team.
