### ISSUE TITLE
Random crash in Curl_thread_destroy

### ISSUE THREAD

**Issue by rouault** [curl/curl#2469]
This is extracted from a oss-fuzz crash on the GDAL project ( https://oss-fuzz.com/v2/testcase-detail/6214536202813440 : probably not public ), which uses curl master.
It reports a , unfortunately non-reproducible, crash in curl (but this occurs from time to time still). I cannot exclude that GDAL would be the cause, but perhaps you'll see if something is wrong in curl with the following trace:

ERROR: Ran out of file reading SECTUndefinedBehaviorSanitizer:DEADLYSIGNAL
  | ==4==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000390 (pc 0x7fb367b22855 bp 0x7ffd79e72be0 sp 0x7ffd79e72bc8 T4)
  | ==4==The signal is caused by a READ memory access.
  | ==4==Hint: address points to the zero page.
  | #0 0x7fb367b22854 in pthread_detach
  | #1 0x288c2f5 in Curl_thread_destroy gdal/curl/lib/curl_threads.c:86:5 https://github.com/curl/curl/blob/c990eadd12779a22f73c834db8e1c30c6dcf0f9c/lib/curl_threads.c#L86
  | #2 0x283658c in destroy_async_data gdal/curl/lib/asyn-thread.c:363:7
https://github.com/curl/curl/blob/c990eadd12779a22f73c834db8e1c30c6dcf0f9c/lib/asyn-thread.c#L363
  | #3 0x282b908 in multi_done gdal/curl/lib/multi.c:554:3
  | #4 0x282b384 in curl_multi_remove_handle gdal/curl/lib/multi.c:692:13

**Comment by jay** [comment]
if it's not reproducible we're at a loss, however most threading issues are solved by following [libcurl thread safety](https://curl.haxx.se/libcurl/c/threadsafe.html). the only other thing i can think of is if this is somehow related to #1968

**Comment by rouault** [comment]
> however most threading issues are solved by following libcurl thread safety

I'm pretty sure that GDAL in that test just uses a single thread, but it probably attaches several easy handles to the multi handle.

**Comment by bagder** [comment]
No news or ways for us to reproduce this, this closed due to not actionable.
