### ISSUE TITLE
fail to cross-compile curl 7.59.0 with '--with-shared' flag

### ISSUE THREAD

**Issue by it-ailen** [curl/curl#2470]
### I did this
I configured curl as following
```sh
CPPFLAGS="-fPIC -DPIC" ./configure --prefix={mydir}/tmp_install --host=mipsel-none-linux CC=msdk-linux-gcc CXX=msdk-linux-g++ --with-ssl={openssl_dir} --with-ca-bundle=/etc/ssl/ca-bundle.crt
```
Then I get result 
![image](https://user-images.githubusercontent.com/9998223/38467799-2419b18a-3b70-11e8-9677-d741d90c3209.png)
Then I make, everything(libcurl.a/libcurl.la were compiled fine) went well until link the final curl with the missing libcurl.so
![image](https://user-images.githubusercontent.com/9998223/38467864-94885a52-3b70-11e8-9af0-8250c9047445.png)
Then I checked the directory(lib/.libs), and found there are broken symbol links here.
![image](https://user-images.githubusercontent.com/9998223/38467890-e3c3bd64-3b70-11e8-8f6a-d5a261267e6d.png)
The target so(libcurl.so.4.5.0) was missing. And there were not any errors

Finally I had to build without shared version, which worked fine.
Hi there,
### I expected the following
I prefer to use the shared version of libcurl.

### curl/libcurl version
7.59.0
### operating system
My host system is ubuntu 16.04
![image](https://user-images.githubusercontent.com/9998223/38467930-8232ed8a-3b71-11e8-9a22-0f5886572fdf.png)

Thanks,
Allen

**Comment by bagder** [comment]
Presumably the build failed to create `libcurl.so` earlier, and you should probably investigate that closer.

**Comment by it-ailen** [comment]
Hi, bagder, 
Thanks for your reply. I checked the whole log and didn't find where the libcurl.so to be linked. Should I turn some debug switches on to enable more logs?

**Comment by bagder** [comment]
You can try `make V=1` to get all the build commands shown.

**Comment by it-ailen** [comment]
Thank you very much , I'll try

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
