### ISSUE TITLE
It's impossible to remove "Proxy-Connection" header when using proxy

### ISSUE THREAD

**Issue by germn** [curl/curl#2481]
How to reproduce:
```
curl --proxy http://127.0.0.1:62142/ http://localhost:62141/
```
and then
```
curl --proxy http://127.0.0.1:62142/ -H "Proxy-Connection:" http://localhost:62141/
```
(where 127.0.0.1/localhost is proxy/server)

Header would be presented in both requests, while it's certainly unexpected in second one.
It looks like removing header [worked earlier](https://stackoverflow.com/a/23095946/1113207), but it doesn't work now.

I tested this on curl 7.59.0, windows 10 x64.

**Comment by bagder** [comment]
A while back we changed curl so that `--header` is for headers sent to a remote server while `--proxy-header` is what you use for headers sent to a proxy...

    curl --proxy http://127.0.0.1:62142/ --proxy-header "Proxy-Connection:" http://localhost:62141/
