### ISSUE TITLE
curl download speed is very slow

### ISSUE THREAD

**Issue by YousefSaber** [curl/curl#2482]
downloading vagrant boxes is very slow sometimes and the download doesn't take the full bandwidth of my connection ???
my internet speed on speedtest is 6.6 Mbps Down

![image](https://user-images.githubusercontent.com/33742499/38589421-1edf7486-3d2b-11e8-84d1-18ed21c24452.png)

and the curl download speed only takes 2 Mbps of my bandwidth please fix this problem

![image](https://user-images.githubusercontent.com/33742499/38589425-298b4162-3d2b-11e8-9450-5e40609ee1f6.png)

**Comment by bagder** [comment]
Then please try downloading that contents using a recent curl version directly, like on a command line, and see how that performs. It helps if we can rule out other components from the mix.

**Comment by YousefSaber** [comment]
@badger

(try downloading that contents using a recent curl version directly, like on a command line,)

 could you please send me some documentation on how to do it and show me the steps 

I'm still quite beginner

**Comment by bagder** [comment]
run 

    curl -O https://...full...URL

in a shell and see what speed it outputs. Then also try a few other URLs and see if the speed is consistently less than for example your browser on the same machine. Also tell us what curl version you're using, as the bug report template asked for!

**Comment by YousefSaber** [comment]
@bagder  I'll try this out in the next time 

![image](https://user-images.githubusercontent.com/33742499/38768310-14ca63f6-3ff2-11e8-8672-ad0fd18ff892.png)

**Comment by YousefSaber** [comment]
@bagder I really tried but nothing woks I don't know a specific URL to use to download virtualbox of Ubuntu servers directly and I've encounter this issue again 

![image](https://user-images.githubusercontent.com/33742499/38771005-92bfd18c-401b-11e8-843c-a6615bade0d0.png)

**Comment by bagder** [comment]
Please enter *text* here. It makes these issues searchable and readable in text-only emails etc. Screenshots with text hinder that.

> I really tried but nothing woks

*nothing* works? That's a rather wide-going statement.

> I don't know a specific URL to use to download virtualbox of Ubuntu servers directly

What about the URL you mention in your screenshots? Isn't that the URL that is downloaded by your tool?

**Comment by YousefSaber** [comment]
@bagder 

( What about the URL you mention in your screenshots? Isn't that the URL that is downloaded by your tool? )

you mean 
( https:vagrantcloud.com/Ubuntu/boxex/xneial ..... etc )

didn't work out the download couldn't even start

**Comment by bagder** [comment]
So you can't find any URL on the Internet with contents you can download? Here's a URL for a 221MB file to try to download and see how fast it is for you:

https://curl.haxx.se/video/curlup-2018/2018-04-14_Daniel-Stenberg-welcome-to-curlup.webm

What operating system is this? Windows 10?

**Comment by YousefSaber** [comment]
@bagder Yes

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by YousefSaber** [comment]
@bagder 

Hi I've faced this issue again and I've tried the link you've provided and CURL doesn't take the full bandwidth of my connection 

while speedtest shows me 6.9Mbps of down speed 


curl takes between 1 to 3Mbps and when upgrading my bionic beaver virtual box it takes less than 1Mbps 


```
curl -O https://curl.haxx.se/video/curlup-2018/2018-04-14_Daniel-Stenberg-welcome-to-curlup.webm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  220M    2 5405k    0     0   257k      0  0:14:36  0:00:20  0:14:16  278k
```

**Comment by bagder** [comment]
So what operating system and version are you running that command line on?

**Comment by YousefSaber** [comment]
@bagder 

it's ok I guess I've discovered the reason behind this issue it took from me a deep look 

packet loss !

I guess that packet loss causes this issue 

when I faced this issue I decided to test my internet connection and pinged some famous websites ( including cloudflare DNS server 1.1.1.1/ 1.0.0.1 )


and found that my internet connection suffers a packet loss of 1%


when I tried to update VirtualBox again later that day with no packet loss issues 


it downloaded just fine 


```
$ curl -V
curl 7.60.0 (x86_64-w64-mingw32) libcurl/7.60.0 OpenSSL/1.0.2o (WinSSL) zlib/1.2.11 libidn2/2.0.5 nghttp2/1.31.1
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL Metalink

```


I'm on windows 10 version 1803
