### ISSUE TITLE
support multiple recipients (RCPT TO) with invalid recipients

### ISSUE THREAD

**Issue by junho85** [curl/curl#2483]
### I did this
There are correct address and wrong address like below
```
recipients = curl_slist_append(recipients, "correct@example.com");
recipients = curl_slist_append(recipients, "wrong@example.com");
```
I tried to send email. but failed.

```
< 250 2.1.5 <correct@example.com>... Recipient ok
> RCPT TO:<wrong@example.com>
< 550 5.1.1 RUSR 111.222.111.222: No such user: <wrong@example.com>
* RCPT failed: 550
> QUIT
< 221 2.0.0
```

### I expected the following
success for sending email to correct@example.com address

### curl/libcurl version
7.59.0

### operating system
osx 10.13.4

**Comment by bagder** [comment]
This is unfortunately a known bug, already mentioned here https://curl.haxx.se/docs/knownbugs.html#SMTP_to_multiple_recipients

Feel free to work on a fix!
