### ISSUE TITLE
Do not export LD_LIBRARY_PATH globally

### ISSUE THREAD

**Issue by mikhirev** [curl/curl#2490]
Hello!

In `configure.ac` paths to SSL libraries are added to `LD_LIBRARY_PATH`, that is exported immediately after that. In some cases this leads to breaking the toolchain, improper configuration and impossibility to compile.

In my particular case, I have custom openssl installation in non-standard prefix, and some other libraries, including zlib, there. After openssl is found and its path is added to `LD_LIBRARY_PATH`, some subsequent tests fail because `ccache` segfaults (it uses zlib to compress/decompress cached object files). `./configure` finishes successfully, but compilation fails because of incorrect configuration.

As custom `LD_LIBRARY_PATH` is needed to execute tests only, it is better to set it when running tests, but not during configuration and build.

### curl/libcurl version

Applicable to any version, including `master`.

### operating system

Solaris 10 with gcc and ccache from opencsw, but also possible to reproduce on any Unix-like system.

**Comment by bagder** [comment]
If you look closer, you'll see that the configure scripts builds and executes a few of the tests. Those tests will fail if it can't link with the libs it has already detected it should use. Your bad ccache install is perhaps the first thing to fix here...

If you can make configure only use `LD_LIBRARY_PATH`  in some more limited contexts and have that work, I'd welcome that.

**Comment by mikhirev** [comment]
Adding `-L<PATH>` to linker options (is't it already there&) and executing tests with `env LD_LIBRARY_PATH="$MY_LD_LIBRARY_PATH" ./sometest` will solve the problem with tests in `configure`. My `ccache` installation is fine, but it needs to use system libraries, but not those I want to link curl to.

**Comment by bagder** [comment]
`-L` is for link-time, so it doesn't help the run-time when executing tests.

I presume we can make a wrapper macro for `AC_RUN_IFELSE` that sets and unsets the `LD_LIBRARY_PATH` accordingly to make it only affect the actual running of the the tests...

**Comment by bagder** [comment]
Does my suggested change make it better for you?

**Comment by mikhirev** [comment]
@bagder thank you, it does exactly what I need. Test build in my environment passed successfully.

**Comment by bagder** [comment]
Lovely, thanks for the confirmation. I'll merge that...
