### ISSUE TITLE
Unable to compile with cyassl despite configured

### ISSUE THREAD

**Issue by totszwai** [curl/curl#2505]
Trying to compile libcurl with cyassl, is there a way to directly tell libcurl what to use?

```
./configure \
--host=arm-linux \
--without-testapps \
--without-zlib \
--without-ssl \
--with-cyassl=/home/cyassl/wolfssl-3.6.8-fips/src/.libs/libcyassl.so \
--with-gnu-ld \
--enable-versioned-symbols \
--enable-static \
--enable-shared 
```

Also tried with 
* --with-cyassl
* --with-cyassl=/home/cyassl/wolfssl-3.6.8-fips/src/.libs

In the configure log file, is obvious that it didn't take it:

> checking for CyaSSL_Init in -lcyassl... no
> checking for CyaSSL_Init in -lwolfssl... no
> checking for ssl_version in -laxtls... no
> configure: WARNING: SSL disabled, you will not be able to use HTTPS, FTPS, NTLM and more.

And obviously when trying to use curl call, it still tells me that https is disabled.

> * Protocol "https" not supported or disabled in libcurl
> * Closing connection -1

What is the proper way to get it to work?

**Comment by totszwai** [comment]
Needed to change the following:

> CPPFLAGS+=-I<my cyassl include location>
> LDFLAGS+=-L<my cyassl lib location> -lcyassl

Weird thing is, i need to manually do **-lcyassl** into the LDFLAGS.

**Comment by jay** [comment]
--with-cyassl requires the location that the lib and include were installed to. Like if you install in /usr/local then --with-cyassl=/usr/local. In your case you pointed it directly to the shared object which is not correct. It has to be to where it was installed.

**Comment by totszwai** [comment]
Yeah well the build system/mechanism I need to work with is pretty dated and bad. They don't "install" the libs.. which is why I was trying to manually point to the location. Since I couldn't do that, my workaround became using -lcyassl under the LDFLAGS.

Is just that for libpcre, it had the option to point directly to the .so, I thought perhaps I could do something similar here. :)
