### ISSUE TITLE
curl 7.47.0 is much slower than 7.22.0

### ISSUE THREAD

**Issue by dontreboot** [curl/curl#2506]
curl (7.47.0) spent lots of time reading CA certs before sending "client hello":
[curl_7.47.0_strace.txt](https://github.com/curl/curl/files/1925414/curl_7.47.0_strace.txt)

>cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
>curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

> strace -s1024 -tt -o curl_7.47.0.strace curl -w "@curl-format.txt" https://170.199.194.0:4443/@p1/heartbeat/ -k -s -o /dev/null
    time_namelookup:  0.000
       time_connect:  0.001
    time_appconnect:  0.256
   time_pretransfer:  0.256
      time_redirect:  0.000
 time_starttransfer:  0.257
                    ----------
         time_total:  0.257

On the other hand, curl 7.22.0 didn't spend time reading CA certs before a "client hello" and after "server hello" was received and it only read few CA certs. This made significant difference in term of response time between 7.22.0 and 7.47.0.
[curl_7.22.0_strace.txt](https://github.com/curl/curl/files/1925413/curl_7.22.0_strace.txt)
>cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"

>strace -s1024 -tt -o curl_7.22.0.strace curl -w "@curl-format.txt" https://170.199.194.0:4443/@p1/heartbeat/ -k -s -o /dev/null
    time_namelookup:  0.000
       time_connect:  0.001
    time_appconnect:  0.009
   time_pretransfer:  0.009
      time_redirect:  0.000
 time_starttransfer:  0.011
                    ----------
         time_total:  0.011

Why does curl 7.47.0 spend so much time reading CA certs and it seems very single CA cert before sending a "client hello"?

**Comment by jay** [comment]
Maybe a difference of SSL library or the CA certificate option. For example 7.47 is reading from a whole certificate bundle and 7.22 is reading individual certificates from a directory, depending on the server. What is the `curl --version` ?

Try --verbose and see if it shows the locations. It should for 7.47 but I'm not sure about 7.22.

**Comment by bagder** [comment]
If the Ubuntu version is any similar to the Debian build (which seems like a pretty good guess), the slowness is indeed mostly due to how it is built by them so that it has to load (too) many files on start. My local builds are not *that* slow.

**Comment by bagder** [comment]
Two more things:

1. even 7.47.0 is very old. Even if you *would* find some problem there, we would want to reproduce them with a modern version for us to be really interested in working on it.

2. You should really make sure you build the two versions you compare with the same TLS libraries and similar build options before you know for sure. Relying on others' builds will not necessary identify curl problems, but is likely to at least involve the build decisions done by those whose builds you're using, and in the curl project we ship source code and we do not control how users build curl for their users.

**Comment by dontreboot** [comment]
I can confirm now that the problem was with different TLS libraries and build option.
When I built 7.47.0 with libssl and it ran much faster than with gnutls. With gnutls and --with-ca-path=/etc/ssl/certs, I could see curl/gnutls read every cert from /etc/ssl/certs. If I only complied curl with gnutls and --with-ca-bundle, curl ran a bit faster because it didn't read certs from /etc/ssl/certs; however, gnutls was still much slow than libssl.

$ ./configure --prefix=/tmp/curl-7.47_ssl --with-ca-path=/etc/ssl/certs --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
$ /tmp/curl-7.47_ssl/bin/curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
$ /tmp/curl-7.47_ssl/bin/curl -w "@/home/users/szhou/curl-format.txt" -k https://10.255.2.2:443/@p1/heartbeat -o /dev/null -s
    time_namelookup:  0.000
       time_connect:  0.000
    time_appconnect:  0.012
   time_pretransfer:  0.012
      time_redirect:  0.000
 time_starttransfer:  0.013
                    ----------
         time_total:  0.013

$ ./configure --without-ssl --with-gnutls --prefix=/tmp/curl-7.47_gnutls --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt --with-ca-path=/etc/ssl/certs
$ /tmp/curl-7.47_gnutls/bin/curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
$/tmp/curl-7.47_gnutls/bin/curl -w "@/home/users/szhou/curl-format.txt" -k https://10.255.2.2:443/@p1/heartbeat -o /dev/null -s
    time_namelookup:  0.000
       time_connect:  0.000
    time_appconnect:  0.108
   time_pretransfer:  0.108
      time_redirect:  0.000
 time_starttransfer:  0.110
                    ----------
         time_total:  0.110

**Comment by bagder** [comment]
I'd say this pretty much confirms this isn't really a curl bug, but more a question of how to build curl best for performance. Case closed.
