### ISSUE TITLE
Can't found file configure 

### ISSUE THREAD

**Issue by abetday** [curl/curl#2523]
when I download it done,  I can't found the file: configure , 
so I cannot excute ./configure , 
what should I do ?
--------------------------------------------------------------------------------
===> Should I excute buildconf  first ?
--------------------------------------------------------------------------------
===> Now I come to a new problem,  After I run command follows:
    ./configure  --prefix=/home/xxx/out
    make
    make install
    cd  /home/xxx/out/bin 
then I found a ' curl ' in the directory , but I can't using  this ' curl ' to  download anything, and get Reply follows:
     curl: (48) An unknown option was passed in to libcurl
And who can tell me how to use this ' curl ' .

**Comment by bagder** [comment]
This is a bug tracker, not a forum for questions.

It seems your new curl binary finds and uses an older libcurl version that you might have in your system.

**Comment by jay** [comment]
What is the `curl -V`? Check if the location of libcurl (I assume /home/xxx/out/lib) is in your shared library path and it's loading. `ldd /home/xxx/out/bin/curl | grep libcurl`

If you want just that curl to load the shared libcurl then the easiest way is set rpath at build time like
~~~
LDFLAGS='-Wl,-rpath,/home/xxx/out/lib' ./configure  --prefix=/home/xxx/out ...
~~~

If instead you want that libcurl in the shared library path you can add the path in /etc/ld.so.conf then run `sudo ldconfig` to rebuild the cache and then check it for libcurl like `ldconfig -p |grep libcurl` then run ldd again

If you don't want the location in your shared library path or you know it isn't then you can build curl to use a static libcurl like `--disable-shared --enable-static`.
