### ISSUE TITLE
Building a totally static curl/openssl with musl failure

### ISSUE THREAD

**Issue by mrunc** [curl/curl#2559]
I'm trying to build a complete static curl/openssl with musl for an application everthing goes fine when building libraries but errors starts to show when building the application

    OPENSSL_VERSION=1.1.0h
    CURL_VERSION=7.59.0

OpenSSL configuration:

	CC="/usr/local/bin/x86_64-linux-musl-gcc -static" \
	LD="/usr/local/bin/x86_64-linux-musl-ld -static" \
	AR="/usr/local/bin/x86_64-linux-musl-ar" \
	RANLIB="/usr/local/bin/x86_64-linux-musl-ranlib" \
	PERL="/usr/bin/perl" \
	./Configure no-shared no-async no-hw no-zlib no-pic no-dso no-threads linux-x86_64

Curl configuration:

	CC="/usr/local/bin/x86_64-linux-musl-gcc -static" 
	LD="/usr/local/bin/x86_64-linux-musl-ld -static" 
	AR="/usr/local/bin/x86_64-linux-musl-ar" 
	RANLIB="/usr/local/bin/x86_64-linux-musl-ranlib" 
	PERL="/usr/bin/perl"
	PKG_CONFIG="pkg-config --static" 
	CPPFLAGS="-I${LIBS_DIR}/openssl-${OPENSSL_VERSION}/ -I${LIBS_DIR}/openssl-${OPENSSL_VERSION}/include/" \
	LDFLAGS="-L${LIBS_DIR}/openssl-${OPENSSL_VERSION}" \
	./configure \
	--with-ssl="${LIBS_DIR}/openssl-${OPENSSL_VERSION}" --disable-zlib --without-zlib \
	--disable-shared --enable-static  \
	--disable-ldap --disable-sspi \
	--without-librtmp --disable-ftp \
	--disable-file --disable-dict \
	--disable-telnet --disable-tftp \
	--disable-manual --disable-ldaps \
	--disable-dependency-tracking \
	--disable-librtsp --disable-pop3 \
	--disable-imap --disable-smtp \
	--disable-gopher --disable-smb \
	--without-libidn --disable-proxy \
	--with-ca-bundle="/usr/local/etc/openssl/cert.pem" \
	--disable-verbose --host=x86_64-linux

    make curl_LDFLAGS=-all-static

Curl configure results:

	curl version:     7.59.0
	Host setup:       x86_64-pc-linux-gnu
	Install prefix:   /usr/local
	Compiler:         /usr/local/bin/x86_64-linux-musl-gcc -static
	SSL support:      enabled (OpenSSL)
	SSH support:      no      (--with-libssh2)
	zlib support:     no      (--with-zlib)
	brotli support:   no      (--with-brotli)
	GSS-API support:  no      (--with-gssapi)
	TLS-SRP support:  enabled
	resolver:         POSIX threaded
	IPv6 support:     enabled
	Unix sockets support: enabled
	IDN support:      no      (--with-{libidn2,winidn})
	Build libcurl:    Shared=no, Static=yes
	Built-in manual:  no      (--enable-manual)
	--libcurl option: enabled (--disable-libcurl-option)
	Verbose errors:   no
	SSPI support:     no      (--enable-sspi)
	ca cert bundle:   /usr/local/etc/openssl/cert.pem
	ca cert path:     no
	ca fallback:      no
	LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
	LDAPS support:    no      (--enable-ldaps)
	RTSP support:     enabled
	RTMP support:     no      (--with-librtmp)
	metalink support: no      (--with-libmetalink)
	PSL support:      no      (libpsl not found)
	HTTP2 support:    disabled (--with-nghttp2)
	Protocols:        HTTP HTTPS RTSP

I get static .a libs after make without a problem but when I try to build my application I get libcurl errors about missing openssl funcitions

	/usr/local/bin/x86_64-linux-musl-gcc -static -fPIC -I../../lib/openssl-1.1.0h/include -I../../lib/curl-7.59.0/include -Wall -Wextra -std=c99 -pedantic -Os -DDEBUG -c -o obj1.o obj1.c
	
	/usr/local/bin/x86_64-linux-musl-gcc -static -fPIC -I../../lib/openssl-1.1.0h/include -I../../lib/curl-7.59.0/include -Wall -Wextra -std=c99 -pedantic -Os -DDEBUG -c -o obj2.o obj2.c
	
	/usr/local/bin/x86_64-linux-musl-gcc -static -fPIC -I../../lib/openssl-1.1.0h/include -I../../lib/curl-7.59.0/include -Wall -Wextra -std=c99 -pedantic -Os -DDEBUG obj1.o obj2.o -L../../lib/openssl-1.1.0h -L../../lib/	curl-7.59.0/lib/.libs -o ../../bin/app-debug-linux-x86_64-musl app.c -lssl -lcrypto -lcurl

Output:
	
        ../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_recv':
	openssl.c:(.text+0x3ce): undefined reference to `SSL_read'
	openssl.c:(.text+0x3fe): undefined reference to `SSL_get_error'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step2':
	openssl.c:(.text+0x916): undefined reference to `SSL_connect'
	openssl.c:(.text+0x92d): undefined reference to `SSL_get_session'
	openssl.c:(.text+0x961): undefined reference to `SSL_get_client_random'
	openssl.c:(.text+0x971): undefined reference to `SSL_SESSION_get_master_key'
	openssl.c:(.text+0xafe): undefined reference to `SSL_get_error'
	openssl.c:(.text+0xb72): undefined reference to `SSL_get_verify_result'
	openssl.c:(.text+0xb98): undefined reference to `X509_verify_cert_error_string'
	openssl.c:(.text+0xd09): undefined reference to `SSL_get0_alpn_selected'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_data_pending':
	openssl.c:(.text+0xec2): undefined reference to `SSL_pending'
	openssl.c:(.text+0xee7): undefined reference to `SSL_pending'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_shutdown':
	openssl.c:(.text+0xf85): undefined reference to `SSL_read'
	openssl.c:(.text+0xf97): undefined reference to `SSL_get_error'
	openssl.c:(.text+0xfd5): undefined reference to `SSL_free'
	openssl.c:(.text+0x1065): undefined reference to `SSL_get_shutdown'
	openssl.c:(.text+0x10e2): undefined reference to `SSL_shutdown'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_version':
	openssl.c:(.text+0x1117): undefined reference to `OpenSSL_version_num'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_send':
	openssl.c:(.text+0x123c): undefined reference to `SSL_write'
	openssl.c:(.text+0x126e): undefined reference to `SSL_get_error'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_close.isra.2':
	openssl.c:(.text+0x1411): undefined reference to `SSL_shutdown'
	openssl.c:(.text+0x141d): undefined reference to `SSL_set_connect_state'
	openssl.c:(.text+0x1429): undefined reference to `SSL_free'
	openssl.c:(.text+0x1441): undefined reference to `SSL_CTX_free'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_seed.isra.3.part.4':
	openssl.c:(.text+0x15a6): undefined reference to `RAND_file_name'
	openssl.c:(.text+0x15bc): undefined reference to `RAND_load_file'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_seed.isra.3':
	openssl.c:(.text+0x162b): undefined reference to `RAND_load_file'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step1':
	openssl.c:(.text+0x18f6): undefined reference to `TLS_client_method'
	openssl.c:(.text+0x1927): undefined reference to `SSL_CTX_free'
	openssl.c:(.text+0x194a): undefined reference to `SSL_CTX_new'
	openssl.c:(.text+0x1984): undefined reference to `SSL_CTX_ctrl'
	openssl.c:(.text+0x1c3a): undefined reference to `SSL_CTX_set_msg_callback'
	openssl.c:(.text+0x1c53): undefined reference to `SSL_CTX_ctrl'
	openssl.c:(.text+0x1c88): undefined reference to `SSL_CTX_set_options'
	openssl.c:(.text+0x1cfc): undefined reference to `SSL_CTX_set_cipher_list'
	openssl.c:(.text+0x1d4f): undefined reference to `X509_LOOKUP_file'
	openssl.c:(.text+0x1d67): undefined reference to `SSL_CTX_get_cert_store'
	openssl.c:(.text+0x1d93): undefined reference to `X509_load_crl_file'
	openssl.c:(.text+0x1e4a): undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
	openssl.c:(.text+0x1e59): undefined reference to `SSL_CTX_set_default_passwd_cb'
	openssl.c:(.text+0x1f0e): undefined reference to `PKCS12_parse'
	openssl.c:(.text+0x1ff9): undefined reference to `SSL_CTX_set_alpn_protos'
	openssl.c:(.text+0x201c): undefined reference to `SSL_CTX_set_next_proto_select_cb'
	openssl.c:(.text+0x20ea): undefined reference to `SSL_CTX_set_srp_username'
	openssl.c:(.text+0x2125): undefined reference to `SSL_CTX_set_srp_password'
	openssl.c:(.text+0x2172): undefined reference to `SSL_CTX_set_cipher_list'
	openssl.c:(.text+0x21fc): undefined reference to `SSL_CTX_use_certificate_chain_file'
	openssl.c:(.text+0x2254): undefined reference to `SSL_CTX_get_cert_store'
	openssl.c:(.text+0x228a): undefined reference to `SSL_CTX_set_verify'
	openssl.c:(.text+0x22e1): undefined reference to `SSL_free'
	openssl.c:(.text+0x2303): undefined reference to `SSL_new'
	openssl.c:(.text+0x234e): undefined reference to `SSL_set_connect_state'
	openssl.c:(.text+0x23c0): undefined reference to `BIO_f_ssl'
	openssl.c:(.text+0x2400): undefined reference to `SSL_set_bio'
	openssl.c:(.text+0x252e): undefined reference to `SSL_CTX_use_PrivateKey'
	openssl.c:(.text+0x2575): undefined reference to `SSL_CTX_use_certificate_file'
	openssl.c:(.text+0x2673): undefined reference to `SSL_CTX_load_verify_locations'
	openssl.c:(.text+0x278e): undefined reference to `SSL_CTX_use_certificate'
	openssl.c:(.text+0x27d8): undefined reference to `SSL_set_fd'
	openssl.c:(.text+0x283d): undefined reference to `SSL_CTX_use_certificate'
	openssl.c:(.text+0x28e1): undefined reference to `SSL_CTX_use_PrivateKey_file'
	openssl.c:(.text+0x293a): undefined reference to `SSL_new'
	openssl.c:(.text+0x2958): undefined reference to `SSL_get_certificate'
	openssl.c:(.text+0x2981): undefined reference to `SSL_get_privatekey'
	openssl.c:(.text+0x29aa): undefined reference to `SSL_get_privatekey'
	openssl.c:(.text+0x29d7): undefined reference to `SSL_free'
	openssl.c:(.text+0x29eb): undefined reference to `SSL_CTX_check_private_key'
	openssl.c:(.text+0x2a57): undefined reference to `SSL_set_session'
	openssl.c:(.text+0x2b10): undefined reference to `SSL_ctrl'
	openssl.c:(.text+0x2b30): undefined reference to `SSL_ctrl'
	openssl.c:(.text+0x2d2d): undefined reference to `SSL_CTX_use_PrivateKey'
	openssl.c:(.text+0x2d85): undefined reference to `SSL_free'
	openssl.c:(.text+0x2daa): undefined reference to `SSL_CTX_check_private_key'
	openssl.c:(.text+0x2dec): undefined reference to `SSL_CTX_add_client_CA'
	openssl.c:(.text+0x2e08): undefined reference to `SSL_CTX_ctrl'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `servercert':
	openssl.c:(.text+0x32f4): undefined reference to `SSL_get_peer_certificate'
	openssl.c:(.text+0x359a): undefined reference to `PEM_read_X509'
	openssl.c:(.text+0x3810): undefined reference to `SSL_get_peer_cert_chain'
	openssl.c:(.text+0x3f21): undefined reference to `PEM_write_bio_X509'
	openssl.c:(.text+0x417d): undefined reference to `SSL_ctrl'
	openssl.c:(.text+0x41ad): undefined reference to `OCSP_response_status'
	openssl.c:(.text+0x41c0): undefined reference to `OCSP_response_status_str'
	openssl.c:(.text+0x4662): undefined reference to `SSL_get_verify_result'
	openssl.c:(.text+0x46b6): undefined reference to `X509_verify_cert_error_string'
	openssl.c:(.text+0x4856): undefined reference to `OCSP_response_get1_basic'
	openssl.c:(.text+0x4874): undefined reference to `SSL_get_peer_cert_chain'
	openssl.c:(.text+0x4888): undefined reference to `SSL_CTX_get_cert_store'
	openssl.c:(.text+0x4898): undefined reference to `OCSP_basic_verify'
	openssl.c:(.text+0x48dc): undefined reference to `OCSP_resp_count'
	openssl.c:(.text+0x48f0): undefined reference to `OCSP_resp_get0'
	openssl.c:(.text+0x4915): undefined reference to `OCSP_single_get0_status'
	openssl.c:(.text+0x4939): undefined reference to `OCSP_check_validity'
	openssl.c:(.text+0x4a25): undefined reference to `OCSP_crl_reason_str'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_common':
	openssl.c:(.text+0x4e63): undefined reference to `SSL_get1_session'
	openssl.c:(.text+0x4f5e): undefined reference to `SSL_SESSION_free'
	../../lib/curl-7.59.0/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_session_free':
	openssl.c:(.text+0x371): undefined reference to `SSL_SESSION_free'
	collect2: error: ld returned 1 exit status

**Comment by bagder** [comment]
I don't think this is a curl bug/issue, this is just about how to link. Tried to put the OpenSSL libs on the right side of the curl library on the link command line? Order is typically annoyingly important when linking statically...

**Comment by jiamo** [comment]
Thanks. 
I create a https://gist.github.com/jiamo/1cb759fa9d3bceaa2146cae08e47ee52
For how to build success.  (May be have some change. I modify and can't remember too small change)

**Comment by mrunc** [comment]
Damn this is really simple!! in my mind I thought that if CURL needs OpenSSL then OpenSSL should be first in line.
also is there any need for "-fPIC" in gcc flags and "no-pic" OpenSSL config option while building an all static application with musl? 
Thank you so much

**Comment by bagder** [comment]
If those options are important, you'll get link failures if you didn't do it right...

**Comment by mrunc** [comment]
Thanks, I figured out that "-fPIC" is not needed if I'm not building any shared libraries and "no-pic" is fine in this case for openssl
