### ISSUE TITLE
curl -O should save file at the url-decoded filename

### ISSUE THREAD

**Issue by nagisa** [curl/curl#2573]
`curl url-encoded-URI -O` saves the url-encoded filename to the file system, even though it is pretty obvious that the intent is to have it be url-decoded.

### curl/libcurl version

curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.8.0 nghttp2/1.24.0
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

**Comment by monnerat** [comment]
See also https://github.com/curl/curl/issues/2030#issuecomment-340369825

**Comment by p** [comment]
wget seems to be able to URL decode the file name, maybe look at how it does that.

**Comment by bagder** [comment]
I didn't say it was impossible, just perhaps trickier than what it first may sound like. Feel free to work on it!
