### ISSUE TITLE
curl doesn't pass username:password to proxy

### ISSUE THREAD

**Issue by zeniitti** [curl/curl#2575]
I'm trying to use webservice labelary.com via command line tool from Windows. In our company we have http proxy and opening IE it will bypass username:password to proxy automatically on "open way" to the internet. After opening IE, curl will work perfectly with labelary and result will be readable pdf-file.
Check usage from http://labelary.com/service.html#curl

However, if user have not opened IE and has not been involved with proxy in that login session, there are no "open way" to the internet. I've tried to use switch -u to add username:password but it just is a no-go. Our proxy will reject it and won't accept authentication. I've tried also with domain/username:password but with same results. And also without http://.

LABEL.DTA is zebra label file made with zebra programming language.

### I did this CMD command:
curl -u user:password -x http://proxy.ourdomain.net:80 --request POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ --form file=@LABEL.DTA --header "Accept: application/pdf" > C:\TEMP\123456789012.pdf"

### I expected
the labelary to respond with real readable pdf-file, but I get html-file reply from proxy named 123456789012.pdf. File won't be opened to pdf-reader, but when opened with notepad, it's html-file from proxy.

### curl/libcurl version

curl 7.59.0 (x86_64-w64-mingw32) libcurl/7.59.0 OpenSSL/1.0.2h (WinSSL) zlib/1.2.8 WinIDN libssh2/1.7.0_DEV
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTPS-proxy MultiSSL

### operating system

Microsoft Windows 10 Enterprise
Version 1607 (OS Build 14393.2189)

**Comment by jzakrzewski** [comment]
You want to use `-U user:password`. The `-u` sends credentials to the website, `-U` to the proxy.

**Comment by zeniitti** [comment]
Thanks for the quick reply. I've tested this few times with different combinations (domain\username:password and with/without http:// before proxy). However the outcome is still the same. Proxy won't accept these credentials.

It's giving error:
_Authentication is required to access the Internet using this system.
A valid user ID and password must be entered when prompted._

**Comment by bagder** [comment]
Your proxy is probably requiring a different auth method. If you show us the 407 headers you get back, those will tell...

**Comment by zeniitti** [comment]
Here is the whole file which was got back as reply. Does it answer your question?
[123456789012.pdf.htm.txt](https://github.com/curl/curl/files/2008561/123456789012.pdf.htm.txt)

**Comment by bagder** [comment]
No, the **HTTP headers** that are sent back are the interesting ones. Not the body. Add `-v` to the command line.

**Comment by zeniitti** [comment]
Here it is:

```
C:\temp>curl -v -U username:password -x http://proxy.domain.net:80 --request POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ --form file=@LABEL.DTA --header "Accept: application/pdf" > C:\TEMP\123456789012.pdf"
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 999.999.999.999...
* TCP_NODELAY set
* Connected to proxy.domain.net (999.999.999.999) port 80 (#0)
* Proxy auth using Basic with user 'username'
> POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ HTTP/1.1
> Host: api.labelary.com
> Proxy-Authorization: Basic [some cryptic letters and numbers]
> User-Agent: curl/7.59.0
> Proxy-Connection: Keep-Alive
> Accept: application/pdf
> Content-Length: 358
> Content-Type: multipart/form-data; boundary=------------------------bd2e82cf3f9e93c3
>
} [358 bytes data]
< HTTP/1.1 407 Proxy Authentication Required
< Mime-Version: 1.0
< Date: Wed, 16 May 2018 13:33:57 EEST
< Via: 1.1 proxy.domain.net:80 (Cisco-WSA/10.1.1-235)
< Content-Type: text/html
< Proxy-Authenticate: NTLM
< Connection: close
* HTTP/1.1 proxy connection set close!
< Proxy-Connection: close
< Content-Length: 2113
<
{ [2113 bytes data]
100  2471  100  2113  100   358   4664    790 --:--:-- --:--:-- --:--:--  5454
* Closing connection 0
```

**Comment by bagder** [comment]
> Proxy-Authenticate: NTLM

See? It wants NTLM. [--proxy-ntlm](https://curl.haxx.se/docs/manpage.html#--proxy-ntlm) is probably what you want.

**Comment by zeniitti** [comment]
Thank you all involved! This really helped and now I can forward username:password to the proxy the correct way. I'll keep testing this with service account and not my own. If I don't post this thread anymore, everything works correctly.

So after all, it wasn't curl issue, it was user issue.

**Comment by zeniitti** [comment]
Unfortunately I headed towards problems.

Normally our proxy authentication is valid for certain amount of time, for example 60 mins. After that, it needs authentication. During normal internet brwwsing, users don't really see the difference, because browser forwards credentials automatically. Some programs that doesn't forwards credentials, head to the proxy error page.

With my new working command, the first authentication works fine and I get proper label from labelary. However, when I run the command again, it won't work. The respond from labelary is **_"ERROR: you requested the 1st label, but the specified ZPL doesn't generate any labels"_** and the command is:

```
C:\temp>curl -v --proxy-ntlm -U domain\username:password --proxy http://proxy.domain.net:80 --request POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ --form file=@LABEL.DTA --header "Accept: application/pdf" > C:\TEMP\123456789012.pdf
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 999.999.999.999...
* TCP_NODELAY set
* Connected to proxy.domain.net (999.999.999.999) port 80 (#0)
* Proxy auth using NTLM with user 'domain\username'
> POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ HTTP/1.1
> Host: api.labelary.com
> Proxy-Authorization: NTLM TlRMTSERGSERGSERGB4IIogAASERGTSERGSERGAAAKADk4AAAADw==
> User-Agent: curl/7.59.0
> Proxy-Connection: Keep-Alive
> Accept: application/pdf
> Content-Length: 0
>
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: X-Total-Count
< Date: Thu, 17 May 2018 05:31:23 GMT
< Vary: Accept-Encoding
< X-Total-Count: 0
< X-Vcap-Request-Id: 4dfa0383-476c-475a-55e1-70fa841d6366
< Keep-Alive: 60
< Content-Length: 85
< Content-Type: text/plain
< Via: HTTP/1.1 proxy11107, 1.1 proxy.domain.net:80 (Cisco-WSA/10.1.1-235)
< Connection: keep-alive
< Proxy-Connection: keep-alive
<
{ [85 bytes data]
100    85  100    85    0     0    271      0 --:--:-- --:--:-- --:--:--   271
* Connection #0 to host proxy.domain.net left intact
```

If I run the same command without --proxy-ntlm, it works. I just doubt that after some time, it needs the authentication and once again, doesn't work.

Working command after authentication:

```
C:\temp>curl -v -U domain\username:password --proxy http://proxy.domain.net:80 --request POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ --form file=@LAPPUD.DTA --header "Accept: application/pdf" > C:\TEMP\123456789012.pdf
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 999.999.999.999...
* TCP_NODELAY set
* Connected to proxy.domain.net (999.999.999.999) port 80 (#0)
* Proxy auth using Basic with user 'domain\username'
> POST http://api.labelary.com/v1/printers/8dpmm/labels/4.1x8.4/0/ HTTP/1.1
> Host: api.labelary.com
> Proxy-Authorization: Basic YmVtaXawerfaerfOktla2tvNTAw
> User-Agent: curl/7.59.0
> Proxy-Connection: Keep-Alive
> Accept: application/pdf
> Content-Length: 358
> Content-Type: multipart/form-data; boundary=------------------------c1e09aawefawefe90e
>
} [358 bytes data]
100   358    0     0  100   358      0   1634 --:--:-- --:--:-- --:--:--  1634< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: X-Total-Count
< Cache-Control: no-transform, max-age=86400
< Date: Thu, 17 May 2018 05:40:37 GMT
< Vary: Accept-Encoding
< X-Total-Count: 1
< X-Vcap-Request-Id: fbc3a4c9-16e1-4153-4c47-5087a81eb4a9
< Transfer-Encoding: chunked
< Content-Type: application/pdf
< Via: HTTP/1.1 proxy11107, 1.1 proxy.domain.net:80 (Cisco-WSA/10.1.1-235)
< Connection: close
* HTTP/1.1 proxy connection set close!
< Proxy-Connection: close
<
{ [2462 bytes data]
100 41787    0 41429  100   358  64631    558 --:--:-- --:--:-- --:--:-- 65190
* Closing connection 0
```

**Comment by bagder** [comment]
So `--proxy-anyauth` then?

**Comment by zeniitti** [comment]
Great! Now it seems to work all the time. I've tested it with two different usernames and workstations.
