### ISSUE TITLE
install---no configure script provided

### ISSUE THREAD

**Issue by Tomarron** [curl/curl#2577]
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
Please use the template and provide the info we ask for. We can't understand nor do anything if we don't understand what you're reporting.

**Comment by jzakrzewski** [comment]
My crystal ball tells me that you're trying to run `configure` on the git repository checkout.
Please either use the release tarball or read [GIT-INFO](https://github.com/curl/curl/blob/master/GIT-INFO) first.
