### ISSUE TITLE
Access denided for putFile on FTP

### ISSUE THREAD

**Issue by DarovskikhAndrei** [curl/curl#2585]
If FTP server has special settings of access rights for user, like it:
/ (root, access)
  folder (no access)
     folder (access)
cURL cann't put file to /folder/folder/file.ext because cURL execs some commands:
CWD / - successfull
CWD folder - access denided 550

but CWD /folder/folder - working successfull.

**Comment by bagder** [comment]
See [--ftp-method](https://curl.haxx.se/docs/manpage.html#--ftp-method)

**Comment by DarovskikhAndrei** [comment]
Great. Thanks.

**Comment by bagder** [comment]
Case closed then?
