### ISSUE TITLE
./configure --with-ssl=/path/to/openssl broken

### ISSUE THREAD

**Issue by bwalle** [curl/curl#2586]
After commit 2d4c2152c9eb3dbdf943de46ed8fc11285f1b90b, configure doesn't work any more. It fails with 

<pre>
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lz 
</pre>

I call `configure` with `--with-ssl=/path/to/openssl/lib/` with following contents:

<pre>
engines/            libcrypto.so        libssl.a            libssl.so.1.0.0     
libcrypto.a         libcrypto.so.1.0.0  libssl.so           pkgconfig/          
</pre>

The system contains

<pre>
ls -l /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 357024 Okt  7  2017 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 738444 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     13 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 431232 Mär 29 13:10 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
-rw-r--r-- 1 root root 442920 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
</pre>

Even if I replace `AC_TRY_RUN` in `CURL_VERIFY_RUNTIMELIBS` with some code that sets `LD_LIBRARY_PATH`, the next test (`AC_CHECK_SIZEOF`) fails.

Reverting 2d4c2152c9eb3dbdf943de46ed8fc11285f1b90b works, but then #2492 is unresolved.

**Comment by bagder** [comment]
The option wants the install _prefix_, not the lib directory. Which in your case probably would be `configure --with-ssl=/path/to/openssl`. Does that change anything?

If not, can you attach your `config.log` file after a failed run to let us have a look?

**Comment by bwalle** [comment]
Sorry, that was wrong in my report. I _did_ call `./configure --with-ssl=/path/to/openssl`.

Attached is the config.log.
[config.log](https://github.com/curl/curl/files/2019181/config.log)
