### ISSUE TITLE
Cannot get the paused state of curl easy handle.

### ISSUE THREAD

**Issue by basuke** [curl/curl#2588]
### Background

We need to pause/unpause the connection. Actual connection is handled in worker thread.

### Problem

When main thread request pause/unpause, the event is dispatched into worker thread. At this moment, I need to know whether curl handle is paused or not to avoid unnecessary curl_easy_pause() which end up of calling of Curl_updatesocket(). Currently we manage that by flag aside with easy handle but ideally it's better to get the information from curl handle.

### I expected the following

CURLcode curl_easy_get_paused(easy, &state);

or

CURLcode curl_easy_getinfo(easy, CURLINFO_PAUSE_STATE, &state);

### curl/libcurl version

libcurl 7.60.0

### operating system

Windows 10 / FreeBSD

**Comment by basuke** [comment]
If I implement this one, which is better? adding new function or add to getinfo?

**Comment by bagder** [comment]
I prefer `curl_easy_getinfo`, since that makes it easier for application to soft-fail in run-time if this ability isn't present in their particular version of the library...

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
