### ISSUE TITLE
tftp.c: 'state->rpacket.data' might be not null terminated, but is passed to a function (strlen) expecting a null terminated string.

### ISSUE THREAD

**Issue by Eason-Yu** [curl/curl#2593]
In tftp.c's tftp_receive_packet(...):
`  state->rbytes = (int)recvfrom(state->sockfd,
                                (void *)state->rpacket.data,
                                state->blksize + 4,
                                0,
                                (struct sockaddr *)&fromaddr,
                                &fromlen);`

'state->rpacket.data' might be not null terminated, but is passed to a function (strlen) expecting a null terminated string.

Call stack as follows:
tftp_receive_packet() -> tftp_parse_option_ack() -> tftp_option_get() -> strlen()

I think, in recvfrom(..), should specify 'len' with the size of buffer - 1 ( state->blksize + 4 - 1), and add a terminated '\0' to the buffer after return.

**Comment by bagder** [comment]
If that can indeed happen, then `tftp_option_get()` is wrong isn't it? It checks for two strings ending with zeroes and if they're not present the function is supposed to return NULL.

**Comment by Eason-Yu** [comment]
ah..., sorry fo overlooking the two checks for NULL term in `tftp_option_get()`. So `&buf[strlen(*option) + 1]` in `tftp_option_get()`, array index should not be out of range. It's not a BUG.

**Comment by bagder** [comment]
That's how I read it as well!
