### ISSUE TITLE
close the wifi shared  by MAC mini, libcurl could not unpause the connection on iphone 

### ISSUE THREAD

**Issue by DaisyMoney** [curl/curl#2595]
### I did this
We use the WIFI shared by MAC mini and pause/unpause the connection too many times. Then we close the Internet Sharing on MAC mini, if the connection is paused, libcurl could not unpause the connection. Only on IOS system(iphones and pads) , Android phone is OK.

We use CURL_WRITEFUNC_PAUSE in writefunction to pause the connection, and use curl_easy_pause(m_curlHandle,CURLPAUSE_RECV_CONT) to unpause the connection in ProgressFunction;

### curl/libcurl version 
libcurl 7.60.0

[curl -V output]

**Comment by bagder** [comment]
I would urge you to try to write up an example source code that can reproduce this problem on another machine and provide this here.

If we can't reproduce this isue or get a **much** more detailed description of exactly is done and what happens, then there's not a lot we can do about this. We can't even rule out that the API is used incorrectly.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
