### ISSUE TITLE
Hint when compiling with another openssl library

### ISSUE THREAD

**Issue by AlBundyLoves69** [curl/curl#2615]
I would like to provide an information which could be published in the installation manual in order to help others.

When curl is compiled with another openssl version than the system default it is often not possible to set the library path from the new openssl version in `/etc/ld.so.conf` because this may break the system.

In this case the `configure` script fails running `conftest` when it is using the openssl libraries with `./conftest: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`.

The only way in this case is to use the `rpath` linker option.

**_Solution:_**
Before running `./configure` execute `export LDFLAGS="-Wl,--rpath=/<path-to-correct-openssl-libraries>"`

**Comment by bagder** [comment]
Are you suggesting that as a change for `docs/INSTALL` ?

Personally I tend to just set `LD_LIBRARY_PATH` if this is more of a temporary thing/work-around.

**Comment by bagder** [comment]
> When the openssl libraries are somewhere else which is not set in /etc/ld.so.conf then configure script fails

No it doesn't. If it does, that's a bug! The configure script sets and uses `LD_LIBRARY_PATH` specifically to deal with this.

I would be very happy if you would provide your suggested phrasing as actual diffs to the source file. Also note that you're talking about linker options to a specific linker so any docs would need to clarify that this is system/linker specific. And as you say, possibly even version specific.

**Comment by AlBundyLoves69** [comment]
Wait, it must be a **new** bug because I tried it with curl 7.58 and there it works! So check the changes from 7.58 to 7.60! Thank you for mentioning it because I almost _forgot_. I had to solve it so I was working on it last weekend until I found the solution with the `rpath` linker option.

This is the command line:

`./configure --prefix=/FaF/curl --with-ssl=/FaF/openssl --disable-ldap --without-zlib --disable-proxy --disable-ipv6 --disable-manual`

With 7.58 it works **without any additional** `LDFLAGS` setting, with 7.60 it fails.

**Comment by bagder** [comment]
Yes, #2586 for example is a fix since 7.60.0 and is directly related to this. So please try a [daily snapshot](https://curl.haxx.se/snapshots/) first.

**Comment by AlBundyLoves69** [comment]
Yep, I confirm, the latest daily snapshot works! I will check out periodically if a new version is available.

------

So, there would be more or less only the hint in the installation guide regarding the `rpath` linker option or preceding `LDFLAGS` with `-Wl,` so it works for gcc.

**Comment by bagder** [comment]
Thanks for confirming. The next release date is planned for July 11th.

**Comment by bagder** [comment]
Thanks @AlBundyLoves69, the updated description has now landed!
