### ISSUE TITLE
Got warning when build on debian 9 ppc64le (curl 7.60.0)

### ISSUE THREAD

**Issue by elephoenix** [curl/curl#2617]
### I did this
Got following  message when build on debian 9 ppc64le

  CC       vtls/libcurl_la-mbedtls.lo
  CCLD     libcurl.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/foobar/curl60/curl-7.60.0/lib'

### I expected the following
no warning "/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')"

### curl/libcurl version
7.60.0

### operating system
foobar@deb9le-dev01:~$ uname -a
Linux deb9le-dev01 4.9.0-3-powerpc64le #1 SMP Debian 4.9.30-2 (2017-06-12) ppc64le GNU/Linux

**Comment by bagder** [comment]
I get this as well on current Debian unstable (sid) on x86-64. I blame libtool.

**Comment by bagder** [comment]
This "hack" removes the warning:
~~~diff
--- libtool~    2018-05-29 08:28:28.766037457 +0200
+++ libtool     2018-05-29 08:29:09.234334404 +0200
@@ -147,7 +147,7 @@
 AR="/usr/bin/ar"
 
 # Flags to create an archive.
-AR_FLAGS="cru"
+AR_FLAGS="cr"
 
 # How to feed a file listing to the archiver.
 archiver_list_spec="@"

**Comment by elephoenix** [comment]
OK, Thanks!

I also searched, found this workaround
https://github.com/kimwalisch/primesieve/issues/16
