### ISSUE TITLE
curl_multi_wait in debug build calls infof(NULL,..) ?

### ISSUE THREAD

**Issue by dtzWill** [curl/curl#2627]
Well, I assume "debug build" is what `DEBUGF` macro is for.

Anyway, just spotted this while debugging my application....

Look at: https://github.com/curl/curl/blob/6d8c6289122dad7f0a05b6363d8e3c2cc73d096a/lib/multi.c#L1086
(current master, and I think at least 7.60)

It's not hard to trace control-flow paths to this line from execution of `while(data) { ... ; data = data->next; }` loops.  I was considering the situation where curl has no fds (`curlfds`) and there's extrafds-- but at a glance I think this can be triggered even when no extra fd's are used.

I haven't tried building things to force the issue, apologies if this can't happen, but thought I'd share "just in case".

If someone's enabled debugging the last thing they need is extra crashing behavior that doesn't occur otherwise :P.

**Comment by bagder** [comment]
Nice catch, thanks! I think I can just remove that line as I don't think it helps us much with anything these days!
