### ISSUE TITLE
curl_fetch_memory won't register VPN change

### ISSUE THREAD

**Issue by ghostrecon27** [curl/curl#2639]
> widget = curl::curl_fetch_memory("https://api.ipify.org?format=json")
> rawToChar(widget$content)
[1] "{\"ip\":\"123.123.123.123\"}"
#After I change my VPN
> widget = curl::curl_fetch_memory("https://api.ipify.org?format=json")
> rawToChar(widget$content)
[1] "{\"ip\":\"123.123.123.123\"}"

When I used readLines() it registers my change in VPN but no matter what I try when I use curl_fetch_memory it only queries with my actual IP not my VPN IP.

**Comment by bagder** [comment]
`curl::curl_fetch_memory` is not a curl/libcurl function. You're probably using the R binding to libcurl? I think you should file the issue with them primarily...
