### ISSUE TITLE
curl build don't recognize openssl engine

### ISSUE THREAD

**Issue by helenebb** [curl/curl#2641]
I build curl to use it with OpenSSL with command : 
`nmake /f Makefile.vc mode=dll WITH_SSL=dll SSL_PATH=C:\OpenSSL-Win32`

OpenSSL is : OpenSSL 1.0.2o  27 Mar 2018
I have add my engine on openssl configuration file (OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
```
[openssl_init]
engines=engine_section

[engine_section]
pkcs11=pkcs11_section

[pkcs11_section]
engine_id=pkcs11
dynamic_path=C:/Users/Helene/Desktop/libp11-0.4.7/libp11-0.4.7/src/pkcs11.dll
MODULE_PATH=C:/Windows/SysWOW64/module.dll
init=0
```

When I list engine with OpenSSL, my engine is OK : 
```
>openssl engine -t
(rdrand) Intel RDRAND engine
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
(pkcs11) pkcs11 engine
     [ available ]
```

But if I list engine with my build curl, I have nothing : 
```
>curl.exe --engine list
Build-time engines:
  <none>
```

If I use installed curl (with SSL support), I have no problem.

Is it my build curl not correct ?

**Comment by bagder** [comment]
I'm pretty sure that's because your build doesn't have `HAVE_OPENSSL_ENGINE_H` defined. See the code that lists the available engine: https://github.com/curl/curl/blob/9ff67f7b00f16da9f9f3377b6b8f5859dd9cd2cb/lib/vtls/openssl.c#L1167-L1185

**Comment by helenebb** [comment]
Indeed, it was the problem. Thank you for your help

**Comment by bagder** [comment]
I'm not exactly sure what fix I propose for this, but I think the engine support is there by default since some openssl version and would probably be a better check.
