### ISSUE TITLE
building under macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by thierrygosselin** [curl/curl#2656]
recommendation:
Update documentation that specify user must use clang as default compiler, because GCC raises errors.

```
cd Downloads
wget https://curl.haxx.se/download/curl-7.60.0.tar.gz
tar -zxvf curl-7.60.0.tar.gz
cd curl-7.60.0
CC="/usr/local/bin/clang" ./configure --without-ssl --with-darwinssl
make -j8
sudo make install
```

**Comment by nickzman** [comment]
The problem isn't the documentation... The problem is the code should be changed to not assume everyone building libcurl against the High Sierra SDK is using Clang to do so.
