### ISSUE TITLE
CURLOPT_XOAUTH2_BEARER does not set Authentication header

### ISSUE THREAD

**Issue by sspiri** [curl/curl#2661]
### I did this
```
int main(){
    CURL* handle = curl_easy_init();

    if(handle){
        curl_easy_setopt(handle, CURLOPT_URL, "https://example.net");
        curl_easy_setopt(handle, CURLOPT_VERBOSE, 1);
        curl_easy_setopt(handle, CURLOPT_XOAUTH2_BEARER, "TOKEN");

        curl_easy_perform(handle);
        curl_easy_cleanup(handle);
    }
}
```
### I expected the following
I expected this sets the "Authentication: Bearer TOKEN" header.
I also noticed CURLAUTH_BEARER was removed but the documentation was not updated.
### curl/libcurl version
```
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.31.1
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by bagder** [comment]
> I also noticed CURLAUTH_BEARER was removed but the documentation was not updated.

`CURLAUTH_BEARER` was *added* in 239a7061f...

**Comment by sspiri** [comment]
Hello,

I got the curl package from arch linux core repository which in turn gets the files from curl.haxx.se/download/curl-7.60.0.tar.gz

I looked inside, and indeed it's missing.

**Comment by bagder** [comment]
That's because 239a706 was committed after 7.60.0 was released...

**Comment by sspiri** [comment]
True dat.

**Comment by bagder** [comment]
Is this still an issue in 7.61.1?

**Comment by bagder** [comment]
I think this is ńow handled, and no response in a month. Closing.
