### ISSUE TITLE
curl(1) TLS version 1.3 missing from --tlsv1 description

### ISSUE THREAD

**Issue by andreaso** [curl/curl#2692]
The `curl(1)` man page has the following to say about the `--tlsv1` option.

> (SSL) Tells curl to use TLS version 1.x when negotiating with a remote TLS server. That means TLS version 1.0, 1.1 or 1.2.

Shouldn't that description also mention version 1.3? Something like the following.

> (SSL) Tells curl to use TLS version 1.x when negotiating with a remote TLS server. That means TLS version 1.0, 1.1, 1.2 or 1.3.

### curl/libcurl version
```
curl 7.61.0-DEV (x86_64-pc-linux-gnu) libcurl/7.61.0-DEV OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system
Ubuntu 18.04

**Comment by bagder** [comment]
That's because so far libcurl doesn't do TLS 1.3 by default, only when you explicitly ask for it. But I think that's more because we haven't remembered to change that since back when we added it with a bit of precaution... I'll file a PR to change this! (both docs and code)
