### ISSUE TITLE
curl not adding Authorization header

### ISSUE THREAD

**Issue by theasteve** [curl/curl#2699]
I am trying to make a curl request to the Seamless.gov API. On a different computer the same curl command works. However, when I run the curl command on my machine it doesn't work.

```curl -X GET -H "Content-Type: application/json" -H "Date: 1530285602" -H "Authorization: HMAC-SHA256 api_key=XXXXXXXX nonce=12335 signature=XXXXXXXXXXXXX" -d 'false' https://nycopp.seamlessdocs.com/api/form/CO1708XXXXXXXXXXXXX/elements```
I have the following version of curl:

> 
> curl: stable 7.60.0 (bottled), HEAD [keg-only] Get a file from an HTTP, HTTPS or FTP server https://curl.haxx.se/ /usr/local/Cellar/curl/7.60.0 (423 files, 3MB)   Poured from bottle on 2018-06-29 at 11:44:32 From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb
> ==> Dependencies Build: pkg-config ✔ Optional: openssl ✘, rtmpdump ✘, libssh2 ✘, c-ares ✘, libmetalink ✘, nghttp2 ✘
> ==> Options
> --with-c-ares   Build with C-Ares async DNS support
> --with-gssapi   Build with GSSAPI/Kerberos authentication support.
> --with-libmetalink  Build with libmetalink support.
> --with-libssh2  Build with scp and sftp support
> --with-nghttp2  Build with HTTP/2 support (requires OpenSSL)
> --with-openssl  Build with OpenSSL instead of Secure Transport
> --with-rtmpdump     Build with RTMP support
> --HEAD  Install HEAD version
> ==> Caveats This formula is keg-only, which means it was not symlinked into /usr/local, because macOS already provides this software and installing another version in parallel can cause all kinds of trouble.
> 
> If you need to have this software first in your PATH run:   echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile
> 
> For compilers to find this software you may need to set:
>     LDFLAGS:  -L/usr/local/opt/curl/lib
>     CPPFLAGS: -I/usr/local/opt/curl/include For pkg-config to find this software you may need to set:
>     PKG_CONFIG_PATH: /usr/local/opt/curl/lib/pkgconfig

Here is the error I get even though I have an Authorization header
 ```
{
    "error": true,
    "error_log": [
        {
            "error_code": "missing_header",
            "error_message": "Request is missing header: `Authorization`",
            "error_description": "{\"Host\":\"XXXX.seamlessdocs.com\",\"Connection\":\"close\",\"X-Real-IP\":\"161.185.7.10\",\"X-Forwarded-For\":\"161.185.7.10\",\"X-Forwarded-Host\":\"nycopp.seamlessdocs.com\",\"X-Forwarded-Port\":\"443\",\"X-Forwarded-Proto\":\"https\",\"X-Original-URI\":\"\\\/api\\\/form\\\/CO1XXXXXXXXXXXXXXX\\\/elements\",\"X-Scheme\":\"https\",\"Content-Length\":\"5\",\"user-agent\":\"curl\\\/7.54.0\",\"accept\":\"*\\\/*\",\"content-type\":\"application\\\/json\",\"date\":\"1530285602\",\"authorization\":\"HMAC-SHA256 api_key=XXXXXXXXXXXXXXX nonce=12335 signature=XXXXXXXXXXXXXX\"}"
        },
        {
```
I'm running on OS High Sierra 10.13.3

**Comment by bagder** [comment]
If you add the `-v` option, or even `--trace-ascii logfile.txt`, I am convinced you'll see that header being added and used in the request.

**Comment by bagder** [comment]
I'm suggesting the header *is* being sent and that this isn't a curl error.

**Comment by bagder** [comment]
No response, closing
