### ISSUE TITLE
Switch "-fail" writes http header to downloaded file

### ISSUE THREAD

**Issue by WolfgangHG** [curl/curl#2707]
This is my curl call:
curl.exe -fail -o wildfly-13.0.0.Final.zip http://download.jboss.org/wildfly/13.0.0.Final/wildfly-13.0.0.Final.zip

The resulting zip is corrupt: the http header is added in front of the zip file:
![downloaded_zip_file](https://user-images.githubusercontent.com/138049/42269832-925f41ac-7f7f-11e8-916a-ff85a7eeaaf6.png)

If I remove "-fail", all is fine. So it seems to work like the "-i" switch.

This happens with the win binaries downloaded from https://bintray.com/vszakats/generic/curl/ ("curl-7.60.0-win32-mingw.zip"). My OS is Win 10 1803, and it also happens with Win 7 and curl 7.57.0

The reason why I use "-fail": I have a download batch, and I want to cancel the batch if e.g. the download file is not found, so I check for error code:

```
@IF NOT %ERRORLEVEL%==0 (
  @echo Curl error: %ERRORLEVEL%
  @pause
  @goto :EOF
)
```

**Comment by dfandrich** [comment]
On Wed, Jul 04, 2018 at 02:49:09AM -0700, WolfgangHG wrote:
> If I remove "-fail", all is fine. So it seems to work like the "-i" switch.

Indeed, it works like that because it *is* using the -i switch. This is the
equivalent of -f -a -i -l. You probably want --fail instead.

**Comment by WolfgangHG** [comment]
Ouch, you are right! What a dumb typo... Sorry for the confusion and many thanks for the fast help!

Wolfgang
