### ISSUE TITLE
Threaded resolver crashes with some versions of OpenSSL

### ISSUE THREAD

**Issue by clbr** [curl/curl#2716]
https://github.com/curl/curl/issues/new

### I did this
Build current master with defaults, which enable the threaded resolver. OpenSSL 1.0.2d

Going with this curl to bitcoincharts.com in Fifth, I get the following crash:
```
Program received signal SIGBUS, Bus error.
0x00007ffff3f3bcd0 in malloc_consolidate () from /lib/libc.so.6
(gdb) bt
#0  0x00007ffff3f3bcd0 in malloc_consolidate () from /lib/libc.so.6
#1  0x00007ffff3f3deec in _int_malloc () from /lib/libc.so.6
#2  0x00007ffff3f3f540 in malloc () from /lib/libc.so.6
#3  0x00007ffff45ba768 in CRYPTO_malloc () from /usr/lib/libcrypto.so.1.0.0
#4  0x00007ffff4641ebf in ?? () from /usr/lib/libcrypto.so.1.0.0
#5  0x00007ffff463f3ce in BIO_set () from /usr/lib/libcrypto.so.1.0.0
#6  0x00007ffff463f44a in BIO_new () from /usr/lib/libcrypto.so.1.0.0
#7  0x00007ffff49a8be2 in ssl_init_wbio_buffer () from /usr/lib/libssl.so.1.0.0
#8  0x00007ffff4996f14 in ssl23_connect () from /usr/lib/libssl.so.1.0.0
#9  0x00007ffff7bca9ea in ossl_connect_step2 (sockindex=<optimized out>, conn=<optimized out>)
    at vtls/openssl.c:2616
#10 ossl_connect_common (conn=0x2b3f9c0, sockindex=0, nonblocking=true, done=0x7fffffff9ce5)
    at vtls/openssl.c:3456
#11 0x00007ffff7bcc796 in Curl_ssl_connect_nonblocking (conn=0x2b3f9c0, sockindex=0,
    done=0x7fffffff9ce5) at vtls/vtls.c:272
#12 0x00007ffff7b7e03b in https_connecting (conn=0x7fffa8000020, done=0x7fffa8000080)
    at http.c:1441
#13 0x00007ffff7ba1315 in multi_runsingle (multi=0x7fffa802e200, now=..., data=0x7fffa83a4d10)
    at multi.c:1607
#14 0x00007ffff7ba2240 in curl_multi_perform (multi=0x7fffa802e200, running_handles=0x7fffffff9f04)
    at multi.c:2159
```

I bisected this to d86e9182, which enabled the threaded resolver by default.
If I build master with --disable-threaded-resolver, there is no crash.
Curiously --enable-ares crashes similarly.

So it looks like some OpenSSL versions are too buggy to be used with the threaded resolver 
(and ares for some reason). Would be good to detect this somehow in configure, if possible. I haven't found if the openssl bug was reported somewhere with quick googling. Going to try other openssl versions now.

### I expected the following
Working threaded resolver and working ares.

### curl/libcurl version

curl 7.61.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2d zlib/1.2.3 
librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp smb smbs 
smtp smtps telnet tftp
Features: AsynchDNS Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

### operating system
Linux x86_64

**Comment by clbr** [comment]
Noting that while valgrind logs would be useful, valgrinding webkit takes so long I'd die of old age. I gave up at the 15 minutes point.

**Comment by clbr** [comment]
Making a standalone source would be a big endeavor too, but reading the threading pages, it seems this may be resolved by adding the openssl 1.0.2 locks. It's weird that the crash only happens with those two options, and there shouldn't be curl threading on my side either, but I'll report back later.

**Comment by bagder** [comment]
> Making a standalone source would be a big endeavor too

If this bug is a basic problem with libcurl built with the threaded resolver, then surely a very [simple example](https://curl.haxx.se/libcurl/c/simple.html) would also trigger this issue? If not, then is this bug really a libcurl one and not caused by your application somehow?

**Comment by bagder** [comment]
If you can't show us source code that triggers this crash and we can't reproduce it with curl or with one of the sample source codes, then I don't think we have enough to identify that bug is even in curl. We certainly don't have details enough to let us debug it from our side. What do you want from us that will help you track this down?

**Comment by clbr** [comment]
I was hoping the backtrace would ring bells with some of the curl hackers. We can close this in a couple weeks if no progress happens in any direction.

**Comment by jay** [comment]
Do you get anything useful if you build it with asan for example `-fsanitize=address,undefined -fno-sanitize-recover -fno-omit-frame-pointer -Wformat -Werror=format-security -Werror=array-bounds -g`

**Comment by clbr** [comment]
Building webkit takes an hour, so I haven't yet had time to try the SSL locks, but asan is a good suggestion too.

**Comment by donny-dont** [comment]
@clbr is this WinCairo? We're the only public webkit port using curl.

**Comment by clbr** [comment]
No, WebkitFLTK (Fifth), which is my port.

**Comment by clbr** [comment]
So it was WSS, secure websockets, being in a thread, combined with a double free in the WSS logic. Nothing to do with curl, sorry for the distraction.
