### ISSUE TITLE
I am not able to use libcurl

### ISSUE THREAD

**Issue by DerexScript** [curl/curl#2720]
### I did this
People, I can not use libcurl!
Can someone help me?
Teach me how to compile this correctly!
Because I'm following every step that comes in a doc along with the project itself. >> BUILD.WINDOWS.txt <<, which is inside the >> winbuild << folder.

Follow the video of the steps I'm following here to compile!
I can compile normally, but at the time of use it says that the functions have not been defined

Follow link >> https://www.youtube.com/watch?v=cG5yA_fiBoY

### curl/libcurl version

[curl 7.60.0]

### operating system
Windows 10 x64

**Comment by jay** [comment]
This is covered in the FAQ, [5.7 Link errors when building libcurl on Windows!](https://curl.haxx.se/docs/faq.html#Link_errors_when_building_libcur). Add `CURL_STATICLIB` to your preprocessor #defines in codeblocks compiler settings.

This is an issue tracker used for reporting bugs. If you cannot find the answer in the docs or FAQ please ask future libcurl questions on the [mailing list](https://cool.haxx.se/mailman/listinfo/curl-library).

**Comment by DerexScript** [comment]
So folks, I got it sorted out!

report my solution!
I was compiling the lib correctly!
But I was trying to use it in codeblocks!
In Code :: Blocks you have to make some settings to work!

Already in Visual Studio 15 2017, it worked without making any extra configuration!
Just call lib to the project!

In Code :: Blocks I downloaded the generic lib already compiled directly from the official libcurl download page
Link >> https://bintray.com/artifact/download/vszakats/generic/curl-7.60.0-win32-mingw.zip
It already comes in the right format for you to include inside the compiler folder of Code :: Blocks!
Ex: "C:\Program Files (x86)\CodeBlocks\MinGW\"
Including in the compiler folder of Code :: Blocks simply add the include "curl / curl.h" and add the following >> -lcurl flag to your project!
Finally you must compile the lib in release mode to be able to access the dll, in order to run the compiled file!
dll goes to the same folder as the compiled file!
