### ISSUE TITLE
Misleading option --post303

### ISSUE THREAD

**Issue by vfaronov** [curl/curl#2723]
[The documentation for the `--post303` option](https://github.com/curl/curl/blob/0b4ccc97f26316476d4c2abbd429952bf61b6375/docs/cmdline-opts/post303.d) says:

> respect RFC 7231/6.4.4 and not convert POST requests into GET requests when following a 303 redirection. The non-RFC behaviour is ubiquitous in web browsers

But [RFC 7231 Section 6.4.4](https://tools.ietf.org/html/rfc7231#section-6.4.4) actually says:

> [...] intended to provide an indirect response to the original request.  A user agent can perform a retrieval request targeting that URI (a GET or HEAD request if using HTTP) [...]

The user agent is not supposed to blindly resubmit the original request to the new URI, which is the whole point of distinguishing 303 from 302. So browsers get this just right.

I guess the option could be useful for some applications that get this *wrong*, but its description is misleading.

**Comment by bagder** [comment]
Agreed, that text is a copy and paste from the other --post30X options and incorrect.

**Comment by bagder** [comment]
@vfaronov do you think #2726 fixes it good enough?

**Comment by vfaronov** [comment]
Yes, looks fine.
