### ISSUE TITLE
Configurable loading of OpenSSL configuration file

### ISSUE THREAD

**Issue by phlipsi** [curl/curl#2724]
The libcurl library calls the OpenSSL function `CONF_modules_load_file()` in `openssl.c`, `Curl_ossl_init()`. This is obviously a good idea for freely configurable clients like curl in order to allow the users to tweak the underlying OpenSSL configuration. In our case this is rather undesirable: Our client is tightly coupled with a fixed server with a given TLS-configuration. We regard any changes in the OpenSSL configuration as a security risk or at least as unnecessary.

Feature-Request: Please add a configuration switch or something similar to disable the `CONF_modules_load_file()` call.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by phlipsi** [comment]
That sounds quite understandable and fair. Thank you for your explanation!
