### ISSUE TITLE
with curl version 7.58 and above I cannot upload file with post on https site

### ISSUE THREAD

**Issue by vagk77** [curl/curl#2725]
### I did this

I am trying to upload a file together with other text post information to an https site with login information. 
It works up to version 7.52
The command below works on Ubuntu 14 and 16 or Debian 8 and 9 without problems for years but does not work on curl 7.58 and above

curl -v -s -k -F "var1=text1" -F "uploaded=@filetoupload" https://username:pass@www.myserver.gr:port/upload.php

I also downloaded latest curl 7.60 on both Debian and Ubuntu and result is the same. No file uploaded.

Is there a changed option or something in the new version of curl to upload files with post together with text data?

### I expected the following

File to be uploaded together with the text info. However only the text info uploaded successfully and not the file

### curl/libcurl version
[curl -V output]
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
Ubuntu 18.04

**Comment by bagder** [comment]
What does curl return/say? What response headers does the server respond with?

**Comment by vagk77** [comment]
Here is the verbose result from curl 7.58 (changed only the sensitive data)

i cannot spot differences with what version 7.52, that works, returned except the Content-Length which is 1334 on version 7.52 and 1528 on version 7.58

*   Trying 1.2.3.4 ...
* TCP_NODELAY set
* Connected to www.myserver.gr (1.2.3.4) port 11111 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.myserver.gr
*  start date: Sep 18 00:00:00 2016 GMT
*  expire date: Sep 18 23:59:59 2019 GMT
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Server auth using Basic with user 'myuser'
> POST /upload.php HTTP/1.1
> Host: www.myserver.gr:11111
> Authorization: Basic dWJ1bnR1c3J2MTh2bToxNTQzMDk5OTE2MjI4MTY0
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 1528
> Content-Type: multipart/form-data; boundary=------------------------9b228641ea4f03af
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Date: Mon, 09 Jul 2018 12:29:55 GMT
< Server: Apache/2.4.10 (Debian)
< X-Powered-By: PHP/5.6.36-0+deb8u1
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<

**Comment by bagder** [comment]
Thanks. That looked all fine and dandy. Can you run the command with `--trace-ascii log.txt` added to the command line, and submit that log file here? (edit out sensitive data again, maybe upload a fake file that contains something bogus)

**Comment by vagk77** [comment]
I am attaching the log from curl version 7.58 of the following command
 ````
curl --trace-ascii log.txt -s -k -F "action=xxxxx" -F "licenceuser=xxxxx" -F "licencekey=xxxxx" -F "organization=xxxxx" -F "usermail=xxxxx" -F "updatecode=xxxxx" -F "confirmcode=xxxxx" -F "uploaded=@/root/tlf" https://myuser:mypass@www.myserver.gr:11111/lc/update.php
````
[log.txt](https://github.com/curl/curl/files/2176338/log.txt)

**Comment by vagk77** [comment]
On the php side the following code
`print_r($_FILES["uploaded"]);`
with curl 7.52 outputs the contents of the uploaded file
with curl 7.58 outputs nothing

**Comment by bagder** [comment]
Ack, this is a curl bug. The 'updatecode' part suddenly gets marked as "multipart/mixed" where it shouldn't!

 @monnerat, any idea?

**Comment by vagk77** [comment]
I rearranged the file upload post variable, to be before the updatecode variable and it uploaded!

Everything after this variable including updatecode variable is not processed on server side

So I checked the variable contents and found out this

Running this command with 2nd variable contents starting with left bracket ( 
`curl --trace-ascii log.txt -s -k -F action1=test -F "action2=(test" -F "uploaded=@file"  https://user:pass@www.myserver:11111/upload.php`
makes action2 marked as "multipart/mixed" and everything after that is not processed correctly

So the problem is **any variable contents starting with left bracket**. If left bracket character is on 2nd char, then no problem. 

Running this command with 1st variable contents starting with left bracket, it even outputed trace info on stdout instead of log.txt
`curl --trace-ascii log.txt -s -k -F "action1=(test" -F "uploaded=@file"  https://user:pass@www.myserver:11111/upload.php`

**Comment by monnerat** [comment]
> Ack, this is a curl bug

I don't think it is: since 7.56.0, the form `=( `denotes a multipart, as `=@` denotes a file. Such string data should then be escaped or specified with `--form-string`,

The only thing that could be done is to consider the `(` as a multpart indication only if alone, removing the problem for parts with multi-character data. But if the real data is `(` alone, it would still need being escaped.

We may also encounter the problem with `=)`.

Maybe this is only a problem of documentation.

**Comment by monnerat** [comment]
I just checked for proper data with an equivalent of (please note the quoting change):

`curl --trace-ascii log.txt -s -k -F 'action1="(test"' -F "uploaded=@file" https://user:pass@www.myserver:11111/upload.php`

It works: `action1` is not a multipart and its data is correct.

**Comment by bagder** [comment]
Right, [the original command line](https://github.com/curl/curl/issues/2725#issuecomment-403480537) didn't really reveal what was going on so I was mislead into suspecting curl. I no longer think this is a bug.

If you really want to throw "any" variable as a form part, then consider using `--form-string` which doesn't support those magic letters to trigger more functionality.

**Comment by vagk77** [comment]
Good to know the 2 options (double quotes and --form-string) to pass text when it is possible it can start with characters having special meaning in curl.

An update to the documentation for the new option =( will help also.

Thank you!

**Comment by bagder** [comment]
> An update to the documentation for the new option =( will help also.

It is already [there](https://curl.haxx.se/docs/manpage.html#-F)!

**Comment by vagk77** [comment]
Many thanks for helping me and solving this so quickly!
:+1:

**Comment by bagder** [comment]
All right, we then consider this case closed. Thanks for playing!
