### ISSUE TITLE
Discrepancy in SSL error codes between major TLS implementations

### ISSUE THREAD

**Issue by sweatybridge** [curl/curl#2729]
Hello,

Our team is developing a cross platform application on top of libcurl that relies on the error codes returned by `curl_easy_perform` to determine problems with different stages of SSL handshake. Unfortunately, there are discrepancies between the error codes returned by major TLS implementations such as openssl, darwinssl, and schannel. In particular, when we were testing a server with intentionally misconfigured certificate, the [schannel implementation](https://github.com/curl/curl/blob/master/lib/vtls/schannel.c#L781) reports a generic `CURLE_SSL_CONNECT_ERROR` while the darwinssl implementation reports a more specific `CURLE_SSL_CACERT` error. We believe such discrepancies should be resolved at the library level by unifying `CURLE_*` error codes returned across different implementations for the same type of error.

Since this bug / feature request involves a fair bit of work understanding implementation specific error codes and matching them to the most appropriate `CURLE_*` error codes, we would like to get your opinion on whether these changes will likely be accepted before proceeding. If you agree that's a good idea, we would be happy to submit a PR for these changes.

Hope to hear from you soon.

### I did this
```sh
curl -L 160.34.18.199
```
### I expected the following
On Windows with schannel:
```
curl: (35) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - The target principal name is incorrect.
```
On MacOS with darwinssl:
```
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
```
The error code returned should be same across platforms since it's a server side issue.

### curl/libcurl version
```
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

### operating system
MacOS and Windows

**Comment by bagder** [comment]
> If you agree that's a good idea, we would be happy to submit a PR for these changes.

I totally agree both that the discrepancy is bad and that unified behavior is good. I would be thrilled to see a PR for this!

**Comment by nickzman** [comment]
FWIW, it appears that the OpenSSL back-end raises error code 51 on that particular host.
