### ISSUE TITLE
curl generating 10 processes on MacOS for a single command

### ISSUE THREAD

**Issue by ChrisADR** [curl/curl#2730]
Hi all,

### I did this

So today at work we noticed a strange behaviour, not sure if a bug or a feature, but on MacOS, we issued a curl command to an IP that we blocked through our firewalls. As expected, curl was unable to fetch the contents from the IP, but we saw a strange behaviour.

Even when the user only executed the command once, we saw 10 processes, 9 of them belonging to PID 0, kernel_task.

It turns out that after digging a bit in the code I found that file curl/src/macos/src/macos_main.cpp contains a 10 loop that execs `exec_commands` those 10 times... maybe it is the source? not 100% sure but I guess that's a possible cause.

### I expected the following

We expected to only see one log entry for the curl command, while reviewing the FireEye acquisition, we found 10 processes trying to connect to the IP that we blocked.

### curl/libcurl version

No info available, I can request it if you need to.

### operating system

MacOS

**Comment by bagder** [comment]
The source file `curl/src/macos/src/macos_main.cpp` is used for macos builds when the version is < X, which by all measurements is an ancient version. It is not used in maxOS 10.* builds.

curl doesn't start processes at all. A default curl build on mac will create a thread (as in a single one) for the name resolving phase, but that will be killed again when the resolve is complete. Thus, any additional processes started will have been done by someone/something else.

**Comment by bagder** [comment]
I know basically nothing about macOS, its kernel or how it is supposed to act in different situations so I'm not sure I will be able to help out much. It sounds more like a macOS bug/issue than a curl one to me (even more so if you're using the curl version that Apple ships bundled with macOS), so perhaps you should consider posting this to Apple (as well) ?

**Comment by ChrisADR** [comment]
@bagder Thanks for the replay and sorry for the delay, I'll dig a bit deeper and see if it's indeed something merely kernel related or something else, if not I'll reopen this one ;) Regards,
