### ISSUE TITLE
Filename is not parsed correctly

### ISSUE THREAD

**Issue by Markvy** [curl/curl#2735]
### I did this
curl -O -J SOME_URL
The Content-Disposition header looked like this:
attachment; filename*=UTF-8''file.txt;
### I expected the following
A file called file.txt gets created.
### curl/libcurl version
curl 7.58.0 (x86_64-w64-mingw32) libcurl/7.58.0 OpenSSL/1.0.2n (WinSSL) zlib/1.2.11 libidn2/2.0.4 nghttp2/1.29.0
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS Debug IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy MultiSSL Metalink
### operating system
x86_64-w64-mingw32
(More specifically, I'm on Windows 7; this curl is bundled with git.)

**Comment by bagder** [comment]
We have this topic listed in our TODO: [UTF-8 filenames in Content-Disposition](https://curl.haxx.se/docs/todo.html#UTF_8_filenames_in_Content_Dispo), so yes this is a known missing feature. curl only parses the "old" `filename=` parameter.

Nobody works on this as far as I know so the task is up for grabs!

**Comment by Markvy** [comment]
Ah, sorry for the duplicate.  I mistakenly only looked at the OPEN issues.

**Comment by bagder** [comment]
a TODO item, would love to see it worked on...
