### ISSUE TITLE
Application is crashing when specifying invalid header (HTTPS, HTTP/2)

### ISSUE THREAD

**Issue by loganek** [curl/curl#2743]
I've noticed that second https HTTP/2 request causes a crash of the application, if the request contains invalid header (contains `\r\n` characters)

### I did this
I've written a following code (I know that's probably not perfect curl-base application, but we're talking about a crash, so I guess it doesn't matter).
```c
#include <curl/curl.h>

#include <unistd.h>

struct CURLM* _curl_multi_handle = NULL;

CURL* create_easy(const char* url)
{
  struct curl_slist* headers = curl_slist_append(NULL, "header: value\r\n");
  struct CURL* curl = curl_easy_init();
  curl_easy_setopt(curl, CURLOPT_URL, url);

  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

  curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2TLS);

  return curl;
}

void do_multi_perform()
{
  int still_running = 0;
  curl_multi_perform(_curl_multi_handle, &still_running);
  while (1)
    {
      int numfds = 0;
      int res = curl_multi_wait(_curl_multi_handle, NULL, 0, 60*1000, &numfds);

      if (res != CURLM_OK)
        {
	  curl_multi_cleanup(_curl_multi_handle);
	  return;
        }

      int prev_still_running = still_running;
      curl_multi_perform(_curl_multi_handle, &still_running);
      if (prev_still_running > still_running || still_running == 0)
        {
	  break;
        }
    }

  CURLMsg* msg = NULL;
  int msgs_left = 0;
  while ((msg = curl_multi_info_read(_curl_multi_handle, &msgs_left)))
    {
      if (msg->msg != CURLMSG_DONE)
        {
	  continue;
        }

      printf("Client code: %d\n", msg->data.result);

      curl_multi_remove_handle(_curl_multi_handle, msg->easy_handle);
    }
}


int main()
{
  curl_global_init(CURL_GLOBAL_ALL);

  _curl_multi_handle = curl_multi_init();
  curl_multi_setopt(_curl_multi_handle, CURLMOPT_PIPELINING, CURLPIPE_MULTIPLEX);

  while (1)
    {
      curl_multi_add_handle(_curl_multi_handle, create_easy("https://www.joomlaworks.net/templates/joomlaworks/images/template/topBackground.jpg"));

      do_multi_perform();
      usleep(5000);
    }

  return 0;
}
```

### I expected the following
Infinite loop with `Cliend code: 55` messages.

### But I got following:
```
Client code: 55
Segmentation fault
```
Callstack:
```
#0  0x00007ffff7b8e880 in Curl_multi_connchanged () from /usr/local/lib/libcurl.so.4
#1  0x00007ffff7ba546a in on_frame_recv () from /usr/local/lib/libcurl.so.4
#2  0x00007ffff757c9fe in ?? () from /usr/lib/x86_64-linux-gnu/libnghttp2.so.14
#3  0x00007ffff757fedf in nghttp2_session_mem_recv () from /usr/lib/x86_64-linux-gnu/libnghttp2.so.14
#4  0x00007ffff7ba5867 in h2_process_pending_input () from /usr/local/lib/libcurl.so.4
#5  0x00007ffff7ba6ba1 in http2_conncheck () from /usr/local/lib/libcurl.so.4
#6  0x00007ffff7b7b5a9 in extract_if_dead () from /usr/local/lib/libcurl.so.4
#7  0x00007ffff7b6932a in ConnectionExists () from /usr/local/lib/libcurl.so.4
#8  0x00007ffff7b7fbbb in Curl_connect () from /usr/local/lib/libcurl.so.4
#9  0x00007ffff7b90333 in multi_runsingle () from /usr/local/lib/libcurl.so.4
#10 0x00007ffff7b91064 in curl_multi_perform () from /usr/local/lib/libcurl.so.4
#11 0x0000000000400cee in do_multi_perform ()
#12 0x0000000000400e4c in main ()
```

I can provide a core dump, if that helps.

### curl/libcurl version
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2g zlib/1.2.8 nghttp2/1.7.1
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 

### nghttp version
nghttp nghttp2/1.7.1

### operating system
Ubuntu 16.04
Linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by loganek** [comment]
I've spent some time investigating this issue. Looks like the bug was introduced in db1b2c7fe9b093f8c3d33304a47657ea4a6e65b4 and it was fixed in 2c15693a3c355d8296a1828123a864397296460b so the bug doesn't exist in curl 7.61 and higher.
Let me know if you plan to release 7.60.1 and where can I find the branch, so I can backport the fix. If not, feel free to resolve the ticket and I'll just update curl version to 7.61 in my project.

**Comment by bagder** [comment]
Thanks for the update. We will release a patch version in a week or two. There are some nasty http2 bugs I want to resolve first.

**Comment by loganek** [comment]
Thanks for reply. Let me know if there's anything related to this ticket that I could help with.

**Comment by bagder** [comment]
This issue is already fixed in master as mentioned above, closing.
