### ISSUE TITLE
7.61.0 github release?

### ISSUE THREAD

**Issue by dtzWill** [curl/curl#2745]
The new release is on the curl website but isn't on github as "latest release".

Is this a sign that it's not quite fully released yet, or just a (small, no worries) oversight?

Thanks! <3

**Comment by bagder** [comment]
Argh, silly me. That's what I do when I'm not following my own checklist by the letter! :-( Please give me a few more days as I'm not in my usual environment.

**Comment by bagder** [comment]
Thanks for pointing this out. Fixed now!
