### ISSUE TITLE
Ambiguous diagnostics: "ALPN, server did not agree to a protocol"

### ISSUE THREAD

**Issue by craigphicks** [curl/curl#2749]
### I did this

 ```
curl  -v --user "api:key-xxxxxxxxxxxxxxxxxxxxxxxxxx" \
     "https://api.mailgun.net/v3/xxxxxxxxxxxxxx/messages" \
     -F to="xxxxxxxxxxxxxx@gmail.com" \
     -F from="xxxxxxxxx@pindertek.com" \
     -F subject="test" \
     -F text="hello"
```

### I expected the following

Diagnostic output unambiguously indicating successful transmission over a secure connection.

Instead I got this ambiguous output:

    ...
    * ALPN, server did not agree to a protocol
    ...

Full diagnostic output included below.

### curl/libcurl version

[curl -V output]

```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```
### operating system

`Linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### suggest fix

Output the protocol to which the server did not agree, and indicate that an alternative succeeded.  In particular it should be unambiguously clear that (1) TLS is not being downgraded. (2) it is not reason for some other failure the client may be experiencing.

E.g.

    * ALPN, server did not agree to http2 protocol, continuing with http1.1

if that is indeed the true case.

###  background

Google `ALPN, server did not agree to a protocol`, you will find thousands of results, representing a lot of wasted time.

### full diagnostic output

```
* Connected to api.mailgun.net (34.215.83.50) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 1060 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.mailgun.net (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=San Francisco,O=MAILGUN TECHNOLOGIES\, INC,OU=MAILGUN TECHNOLOGIES\, INC,CN=*.mailgun.net
* 	 start date: Thu, 18 Jan 2018 00:00:00 GMT
* 	 expire date: Wed, 18 Mar 2020 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=Thawte TLS RSA CA G1
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'api'
> POST /v3/pindertek.com/messages HTTP/1.1
> Host: api.mailgun.net
> Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 464
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------df265bf86c971664
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
```

**Comment by jay** [comment]
http 1.1 may be sent as alpn as well. i don't think it's ambiguous to say alpn server did not agree to protocol, that is exactly what happened.

**Comment by craigphicks** [comment]
Your have a priori knowledge that the context of that diagnostic message is a choice between http1.1 and http2.  You are implicitly saying that it is reasonable to expect that a priori knowledge to be known. Without that a priori knowledge it is an ambiguous message.  Cleartext/SSL/TLS are also a family of protocols.  Basic Auth/O Auth are also a family of protocols.  

That is exactly what happened, but that is not the only possible interpretation without a priori knowledge of that context, in which case some effort is required to clear the doubt.   If the message were explicit there could be no doubt.

**Comment by bagder** [comment]
> If the message were explicit there could be no doubt.

How would you suggest it should rather be phrased?

**Comment by bagder** [comment]
> ALPN, server did not agree to http2 protocol, continuing with http1.1

I would not like that because at that point the handshake it really means that ALPN didn't agree to *any* protocol and the TLS handshake does not know what HTTP version that will be used then. It could be 1.1, 1.0 or even 0.9!

**Comment by craigphicks** [comment]
You make a good point.  In that case I think this would be sufficient:

    ALPN, server agreed to some http protocol; TLS informed

or 

    ALPN, server agreed to some http protocol; TLS ok.

Firstly it shows a positive result (no sweat).  Also we know (1) It was choice of http protocol, and (2) TLS is still valid.

**Comment by bagder** [comment]
But the server (using the ALPN extension) didn't agree to any protocol when given the choice. That's exactly what that log line means. Why would that imply anything about TLS being fine or not?

**Comment by bagder** [comment]
I believe it is important that the message is correct and well scoped. Making it sound "less dangerous" by blurring the message or making it outright lie is not a good fix.

I have not seen any better suggestion than what is currently being used and nothing has happened for a month. Closing this.

**Comment by realtebo** [comment]
Sorry for late joining. I just add an other user case. 

I am running in this issue 

    * ALPN, offering http/1.1
    * SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
    * 	 server certificate verification OK
    * 	 server certificate status verification SKIPPED
    * 	 common name: pihole2.mydomain.tld (matched)
    * 	 server certificate expiration date OK
    * 	 server certificate activation date OK
    * 	 certificate public key: RSA
    * 	 certificate version: #3
    * 	 subject: CN=pihole2.mydomain.tld
    * 	 start date: Tue, 21 Aug 2018 23:09:42 GMT
    * 	 expire date: Mon, 19 Nov 2018 23:09:42 GMT
    * 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
    * 	 compression: NULL
    * ALPN, server did not agree to a protocol
    > GET / HTTP/1.1

Actually I've no idea of what this error means. And I not see any info helping me to understand what to fix in the server or proxy config. Yes I'll google more, but I have not idea if is broken SSL dialog and exactly in which point the dialog is broken.

Also, not clear why I requested https and got http anyway. I used --verbose hoping in more infos but ... not.

**Comment by bagder** [comment]
> Actually I've no idea of what this error means.

It's not an error. It's information about what was and wasn't negotiated in the handshake.

> not clear why I requested https and got http anyway

You didn't loose HTTPS. What makes you think that? HTTPS is however always HTTP and TLS together, so HTTPS can still be HTTP/1.1 ...

**Comment by realtebo** [comment]
@badger: thanks for explanations. Now it's clear. The point was that the message instead is not clear. But ok for me. I discovered ALPN term for the first time, Googled, explained the term, but without this thread the meaning of 'did not agree to a protocol' was obscure.

PS: Whole world is using curl. A whole world of thanks.

**Comment by bagder** [comment]
Right, thanks. If you can think of a better way to phrase it, that would explain the situation in a way that would sound less "scary" to users but still reveals the same information I'm all ears.

**Comment by gaillard** [comment]
I actually currently have the opposite in a case of mine. I have curl responding to a server of mine with:
```
= Info: SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
== Info: ALPN, server accepted to use h2
== Info: Server certificate:
== Info:  subject: O=Something
== Info:  start date: Oct  6 01:30:09 2018 GMT
== Info:  expire date: Oct  1 01:30:09 2038 GMT
== Info:  issuer: O=Something
== Info:  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
=> Send SSL data, 5 bytes (0x5)
0000: 17 03 03 00 63                                  ....c
=> Send header, 75 bytes (0x4b)
0000: 47 45 54 20 2f 68 69 20 48 54 54 50 2f 31 2e 31 GET /hi HTTP/1.1
```

when something successfully going to http2 using alpn would have lines like:
```
== Info:  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
== Info: Using HTTP2, server supports multi-use
== Info: Connection state changed (HTTP/2 confirmed)
```

So a message no matter what happened with alpn would be useful as currently I can't make heads or tails why it fell through to http1.1.

**Comment by bagder** [comment]
I would certainly agree with that desire in the case like above!
