### ISSUE TITLE
Windows makefile looks for libeay32.lib

### ISSUE THREAD

**Issue by illera88** [curl/curl#2758]
I just tried to compile curl with OpenSSL and the Makefile is trying to look for `libeay32` but:
Since version 1.1.0 OpenSSL have changed their library names from:
libeay32 -> libcrypto
ssleay32 -> libssl

### operating system
windows 10 x64

**Comment by rodwiddowson** [comment]
Which version of Curl? And which version of building (there are three).
I know that the NMAKE based one works since forever.

**Comment by illera88** [comment]
I just cloned the master branch.

**Comment by bagder** [comment]
@illera88 ... and **how** did you (try to) build curl?

**Comment by kdekker** [comment]
The stuff in winbuild (MakefileBuild.vc) takes care for this:

```
!IF "$(WITH_SSL)"=="dll" || "$(WITH_SSL)"=="static"
!IF EXISTS("$(SSL_LIB_DIR)\libssl.lib")
SSL_LIBS     = libssl.lib libcrypto.lib
!ELSE
SSL_LIBS     = libeay32.lib ssleay32.lib
!ENDIF
USE_SSL      = true
SSL          = $(WITH_SSL)
!IF "$(WITH_SSL)"=="static"
WIN_LIBS     = $(WIN_LIBS) gdi32.lib user32.lib crypt32.lib
!ENDIF
!ENDIF
```
