### ISSUE TITLE
accessing nullptr on curl_easy_cleanup when using SSL

### ISSUE THREAD

**Issue by Artenuvielle** [curl/curl#2764]
I am building on windows 10 64bit, with Visual Studio 2017, a static version of libcurl (based on this [commit](https://github.com/curl/curl/tree/db2ac90eaf45f995608cf97bb1b2f811a143477e), build options: `nmake /f Makefile.vc mode=static MACHINE=x64 DEBUG=yes`).

When trying to make a simple get request with HTTPS and calling curl_easy_cleanup I get a read access violation on this callstack:
```
    Curl_ssl_sessionid_lock(connectdata * conn) line 283 (vtls.c)
    Curl_schannel_shutdown(connectdata * conn, int sockindex) line 1916 (schannel.c)
    Curl_ssl_shutdown(connectdata * conn, int sockindex) line 557 (vtls.c)
    Curl_schannel_close(connectdata * conn, int sockindex) line 1821 (schannel.c)
    Curl_ssl_close(connectdata * conn, int sockindex) line 553 (vtls.c)
    Curl_disconnect(Curl_easy * data, connectdata * conn, bool dead_connection) line 796 (url.c)
    Curl_conncache_close_all_connections(conncache * connc) line 575 (conncache.c)
    curl_multi_cleanup(Curl_multi * multi) line 2263 (multi.c)
    Curl_close(Curl_easy * data) line 331 (url.c)
    curl_easy_cleanup(Curl_easy * data) line 826 (easy.c)
```

I is probably due to the line 317 in conncache.c (function Curl_conncache_remove_conn) added in the [commit](https://github.com/curl/curl/commit/1b76c38904f0033ac1403ec4b31c28f23805c0d4). It sets conn->data to null and gets called in line 786 of conncache.c (function Curl_disconnect) before Curl_ssl_close (see stack).

**Comment by mpustovoyt** [comment]
I fixed it just by adding check for null of data in macro, file "lib\vtls\vtls.c" line 71:

/* convenience macro to check if this handle is using a shared SSL session */
#define SSLSESSION_SHARED(data) (data && data->share &&                        \
                                 (data->share->specifier &             \
                                  (1<<CURL_LOCK_DATA_SSL_SESSION)))

Regardless of actual reason and fix the code must check for null always here

**Comment by Artenuvielle** [comment]
Yes, the given commit resolves the issue.

**Comment by donny-dont** [comment]
Resolved for WinCairo WebKit port as well. Thanks for figuring this out!
