### ISSUE TITLE
curl: (60) SSL certificate problem: certificate is not yet valid

### ISSUE THREAD

**Issue by xuqifu** [curl/curl#2766]
### I did this
install configure:
./configure --prefix=/home/software/curl-7.54' '--host=arm-linux' 'CC=/usr/local/arm/linaro-armv7ahf-2017.02-gcc6.3/bin/arm-linux-gnueabihf-gcc' 'CXX=/usr/local/arm/linaro-armv7ahf-2017.02-gcc6.3/bin/arm-linux-gnueabihf-g++' 'CPPFLAGS=-I/home/software/openssl/include -I/home/software/nghttp2/include' 'LDCFLAGS=-L/home/software/openssl/usr/lib -L/home/software/nghttp2/usr/lib' 'LIBS=-lssl -lcrypto' '--with-nghttp2=/home/software/nghttp2/usr' '--with-ssl=/home/software/openssl/usr' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' '--with-ca-path=/etc/ssl/certs'

i have put "ca-certificates.crt " in directory : /etc/ssl/certs

I'm trying this command:
curl -I https://baidu.com/
### I expected the following
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

### curl/libcurl version
 7.54.0
[curl -V output]
curl 7.54.0 (arm-unknown-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.2h nghttp2/1.33.0-DEV
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL HTTP2 UnixSockets HTTPS-prox

### operating system
linux

could you give me adevice ?   
thanks !

**Comment by bagder** [comment]
It sounds like perhaps your clock is not set correctly (to a fine date) which makes it reject the otherwise legitimate certificate?

**Comment by bagder** [comment]
No further response after three weeks. Closing.
