### ISSUE TITLE
--max-time option NOT working

### ISSUE THREAD

**Issue by TithiK** [curl/curl#2770]
### I did this
Executed below command to sftp a file:
curl -k -u user_id:password -B -T <source_filename>  sftp://<remote_host>/<target_direcotry> -m 120

### I expected the following
When target_direcotry is full on the remote host, the curl command getting hung forever. -m --max-time 120 is not working

### curl/libcurl version

[curl -V output]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

### operating system
Linux <host_name> 2.6.32-696.30.1.el6.x86_64 #1 SMP Fri May 18 11:50:44 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
> curl 7.19.7 

Please upgrade to a modern version and retry. We've fixed thousands of issues since then.

**Comment by TithiK** [comment]
Thanks

**Comment by TithiK** [comment]
The command: yum list curl*
shows that:
Installed Packages
curl.x86_64                7.19.7-53.el6_9                 @rhel-6-server-rpms

Linux administration team told that latest version of curl has already been installed.

Please confirm if --max-time (-m) 120 works with the curl version (curl.x86_64  7.19.7-53.el6_9)
