### ISSUE TITLE
libcurl.pc Libs.private contains non-linker flags

### ISSUE THREAD

**Issue by nh2** [curl/curl#2775]
On Ubuntu 16.04, `./configure --prefix=$HOME/curl --with-gssapi`, commit 7bc118043749, ends me up with:

```
% grep Libs.private libcurl.pc 
Libs.private: -lrtmp -lssl -lcrypto -lssl -lcrypto -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,-Bsymbolic-functions -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -llber -lz
```

There are `-Wl,` flags in the linker flags, which are `cc` flags, not `ld` flags.

I believe those do not belong there.

Because of that `pkg-config --libs --static libcurl` outputs flags that are not suitable to be passed directly to a linker like `ld`, which breaks my use case.

Who puts these flags in there, is it curl's build system, or am I looking at an issue of a dependency?

**Comment by bagder** [comment]
No response. The source for this is *probably* in a 3rd party pkg-config file.
