### ISSUE TITLE
the PUT request  is timeout with HTTP2.

### ISSUE THREAD

**Issue by huiguangjun** [curl/curl#2778]
### I did this
I uses libcurl as http client to test my RESTFUL API in HTTP2.
Step 1: do HEAD request,  and gets the expected response.
Step 2: re-using the connection,  and  do PUT reqeust.
Step 3:  gets operation timeout instead of successful  200 code. 
 
In  transfer.c->Curl_readwrite  function, if the conn->data->state.drain is non-zero, the send operation will be ignored. 
After HEAD request finished,  the conn->data->state.drain is not reset,  the operation that re-using the connect to send data  is failed. 

### I expected the following
The  function http2_handle_stream_close should be called before the connect  left intact.
Or Curl_easy.state.drain should be reset before reusing the connect handle.

### curl/libcurl version
curl 7.60.0-DEV (i386-pc-win32) libcurl/7.60.0-DEV OpenSSL/1.0.2o zlib/1.2.11 WinIDN nghttp2/1.32.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz HTTP2 HTTPS-proxy

[curl -V output]
...>curl -I -v "https://nghttp2.org" -k
* Rebuilt URL to: https://nghttp2.org/
*   Trying 139.162.123.134...
* TCP_NODELAY set
*   Trying 2400:8902::f03c:91ff:fe69:a454...
* TCP_NODELAY set
* connect to 2400:8902::f03c:91ff:fe69:a454 port 443 failed: Network unreachable
* Connected to nghttp2.org (139.162.123.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nghttp2.org
*  start date: Jul 20 00:00:10 2018 GMT
*  expire date: Oct 18 00:00:10 2018 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* nghttp2_session_mem_recv() returns 0
* http2_send len=78
* h2 header: :method:HEAD
* h2 header: :path:/
* h2 header: :scheme:https
* h2 header: :authority:nghttp2.org
* h2 header: User-Agent:curl/7.60.0-DEV
* h2 header: Accept:*/*
* Using Stream ID: 1 (easy handle 0x5081c8)
* before_frame_send() was called
* on_frame_send() was called, length = 37
> HEAD / HTTP/2
> Host: nghttp2.org
> User-Agent: curl/7.60.0-DEV
> Accept: */*
>
* http2_recv: easy 0x5081c8 (stream 1), len:102400
* nread=27
* nghttp2_session_mem_recv() befor returns 27
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* nghttp2_session_mem_recv() after returns 27
* All data in connection buffer processed
* http2_recv returns AGAIN for stream 1
* http2_recv: easy 0x5081c8 (stream 1), len:102400
* nread=9
* nghttp2_session_mem_recv() befor returns 9
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* nghttp2_session_mem_recv() after returns 9
* All data in connection buffer processed
* http2_recv returns AGAIN for stream 1
* http2_recv: easy 0x5081c8 (stream 1), len:102400
* nread=230
* nghttp2_session_mem_recv() befor returns 230
* on_begin_headers() was called
* h2 status: HTTP/2 200 (easy 0x5081c8)
* h2 header: date: Mon, 23 Jul 2018 06:45:18 GMT
* h2 header: content-type: text/html
* h2 header: last-modified: Tue, 08 May 2018 13:53:22 GMT
* h2 header: etag: "5af1abd2-19d8"
* h2 header: accept-ranges: bytes
* h2 header: content-length: 6616
* h2 header: x-backend-header-rtt: 0.001752
* h2 header: strict-transport-security: max-age=31536000
* h2 header: server: nghttpx
* h2 header: via: 2 nghttpx
* h2 header: x-frame-options: SAMEORIGIN
* h2 header: x-xss-protection: 1; mode=block
* h2 header: x-content-type-options: nosniff
* on_frame_recv() header 1 stream 1
* Store 395 bytes headers from stream 1 at 0x512958
* on_frame_recv() header 0 stream 1
* on_stream_close(), NO_ERROR (err 0), stream 1
* Removed stream 1 hash!
* nghttp2_session_mem_recv() after returns 230
* All data in connection buffer processed
* http2_recv: returns 395 for stream 1
< HTTP/2 200
HTTP/2 200
< date: Mon, 23 Jul 2018 06:45:18 GMT
date: Mon, 23 Jul 2018 06:45:18 GMT
< content-type: text/html
content-type: text/html
< last-modified: Tue, 08 May 2018 13:53:22 GMT
last-modified: Tue, 08 May 2018 13:53:22 GMT
< etag: "5af1abd2-19d8"
etag: "5af1abd2-19d8"
< accept-ranges: bytes
accept-ranges: bytes
< content-length: 6616
content-length: 6616
< x-backend-header-rtt: 0.001752
x-backend-header-rtt: 0.001752
< strict-transport-security: max-age=31536000
strict-transport-security: max-age=31536000
< server: nghttpx
server: nghttpx
< via: 2 nghttpx
via: 2 nghttpx
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
x-content-type-options: nosniff

<
* Connection #0 to host nghttp2.org left intact

### operating system
win7

**Comment by bagder** [comment]
For me (post the #2809 landing) this command line now works fine:

 `curl -v -I https://nghttp2.org --next -T tiny https://nghttp2.org`

**Comment by huiguangjun** [comment]
Sorry for  late to reply to your message.
I have checked it in my environment, it works fine  now.

**Comment by bagder** [comment]
Thanks for confirming @huiguangjun !
