### ISSUE TITLE
7.61 regression: -O -J with http://foo/bar/ URL stopped working

### ISSUE THREAD

**Issue by 0-wiz-0** [curl/curl#2783]
### I did this
curl -OJ http://some/url/

### I expected the following
A file based on the `Content-Disposition: attachment; filename="..."` to be created.
Instead I got
````
Warning: Remote filename has no length!
* Failed writing header
````

### curl/libcurl version

Works with:
curl 7.60.0 (x86_64--netbsd) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.10 libidn2/2.0.4
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

Broken with:
curl 7.61.0 (x86_64--netbsd) libcurl/7.61.0 OpenSSL/1.1.0h zlib/1.2.10 libidn2/2.0.4
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system
NetBSD, but I don't think it matters.

**Comment by bagder** [comment]
We should also make sure that we write a test case for this so that we make sure the fix sticks!
