### ISSUE TITLE
is Curl_pp_sendf blocking function?

### ISSUE THREAD

**Issue by bingzhang** [curl/curl#2785]
Hello:

I have quick question, I read the source code of Ftp part. It seems all ftp commands are seding in the function of ``Curl_pp_sendf''. May I know Curl_pp_sendf is blocking to wait for the remote server's reply coming back, please?

and this repos is the source code of curl command shipped with Ubuntu? On my machine, my curl is 

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

Thanks.

**Comment by bagder** [comment]
Questions should be take to the curl-library mailing list. This is a tracker for bugs.

No, it's not blocking.
