### ISSUE TITLE
Test case 1133 fails on Windows

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#2796]
### I did this

`./runtests.pl -p -v 1133`

### I expected the following

Success. Instead, I got `protocol FAILED` and

```
=== Start of file stderr1133
Warning: setting file log/test1133,a"nd;.txt failed
Warning: setting file log/test1133,a"nd;.txt failed
Warning: setting file log/test1133,a"nd;.txt failed
Warning: setting file log/test1133,a"nd;.txt failed
```

This is because `"` is not a valid character for file names on Windows.

Should we split the "double quotes in filenames" case out to its own test and disable it for Windows with `<precheck>` like done in test 2072? Other suggestions?

### curl/libcurl version

7.61.1-DEV, configuration is irrelevant

### operating system

Windows 10

**Comment by bagder** [comment]
> Should we split the "double quotes in filenames" case out to its own test and disable it for Windows with <precheck> like done in test 2072?

That sounds like a sensible idea, yes!
