### ISSUE TITLE
Debug logs for TLS alerts contain wrong messages

### ISSUE THREAD

**Issue by djelinski** [curl/curl#2806]
While examining debug output of #2801, I noticed that the debug output for TLS alerts is garbage. The output currently reads:
> TLSv1.2 (IN), TLS alert, Client hello (1):

### I expected the following
> TLSv1.2 (IN), TLS alert, warning / close notify (1/0)

### curl/libcurl version
[curl -V output]
curl 7.60.0 (i386-pc-win32) libcurl/7.60.0 OpenSSL/1.1.0h (WinSSL) zlib/1.2.11 brotli/1.0.4 WinIDN libssh2/1.8.0 nghttp2/1.32.0
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli TLS-SRP HTTP2 HTTPS-proxy MultiSSL

### operating system
Windows 2008R2

**Comment by bagder** [comment]
Any suggestion on how to reproduce this?

**Comment by djelinski** [comment]
Gist of code used to reproduce:
> curl_easy_setopt(curl, CURLOPT_URL, "https://s3.amazonaws.com");
			curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
			curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, DebugCallback);
			curl_easy_perform(curl);
			Sleep(5950); // experimental, server seems to close connection after about this time
			curl_easy_perform(curl);

Debug function:
>    int DebugCallback(CURL *handle,curl_infotype type,char *datasize_t size,void *userptr)
	{
      if(type >= CURLINFO_DATA_OUT) return 0;
	  printf("%s",string(data, data+size).c_str());
      return 0;
	}

It seems to me that the detailed messages are only valid for TLS handshake, for other message types they don't make sense.
