### ISSUE TITLE
--max-time option NOT working

### ISSUE THREAD

**Issue by TithiK** [curl/curl#2814]
### I did this
Executed below command to transmit a file through sftp:
curl -k -u user_id:password -B -T <source_filename> sftp://<remote_host>/<target_direcotry> -m 120

### I expected the following
When target_direcotry is full on the remote host, the above-mentioned curl sftp command is getting hung for forever. -m i.e. --max-time 120 is not working

### curl/libcurl version
The command: yum list curl*
shows:
Installed Packages
curl.x86_64 7.19.7-53.el6_9 @rhel-6-server-rpms

Linux administration team told that latest version of curl has already been installed.

But,
[curl -V output]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

Please confirm if --max-time (-m) 120 works with the curl version (curl.x86_64 7.19.7-53.el6_9)

### operating system
Linux <host_name> 2.6.32-696.30.1.el6.x86_64 #1 SMP Fri May 18 11:50:44 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
You're asking about a curl version released in 2009. If you have problems with that, we can only recommend you upgrade to a modern version.

**Comment by TithiK** [comment]
Linux administration team is saying "curl.x86_64 7.19.7-53.el6_9 @rhel-6-server-rpms" is the latest version on Oracle Linux

**Comment by bagder** [comment]
I'm sorry, but then you better ask your administration team or Oracle for support and help with that version. We're too small of a project to be able to consider any other versions than the last few releases. If you can reproduce the problem with the latest version I'll be very interested in details and I'll get right onto fixing it. If not, I have a bazillion other more important tasks...

**Comment by TithiK** [comment]
Thanks!
I'll talk to Administration team.
