### ISSUE TITLE
Should the `name`  of `curl_mime_name()` contain no file extension?

### ISSUE THREAD

**Issue by kgbook** [curl/curl#2820]
prototype:
`CURLcode curl_mime_name(curl_mimepart *part, const char *name)`

https://curl.haxx.se/libcurl/c/libcurl-tutorial.html, at "Converting from deprecated form API to MIME API" chapter, 
```c
curl_formadd(&post, &last,
              CURLFORM_COPYNAME, "memfile",
              CURLFORM_BUFFER, "memfile.bin",
              CURLFORM_BUFFERPTR, databuffer,
              CURLFORM_BUFFERLENGTH, (long) sizeof databuffer,
              CURLFORM_END);
```
becomes:
```c
 part = curl_mime_addpart(multipart);
 curl_mime_name(part, "memfile");
 curl_mime_data(part, databuffer, (curl_off_t) sizeof databuffer);
 curl_mime_filename(part, "memfile.bin");
```
Ihe string pass to `curl_mime_name` is not `memfile.bin` but `memfile`.

It indicates that the `name` shouldn't contain file extension, right?
And What will happen if I pass `name` with file extension, libcurl open and read the file?

**Comment by kgbook** [comment]
I puzzled how to convert to mime API,  for example:
```c
curl_formadd(post, &last,
                         CURLFORM_COPYNAME, "image",
                         CURLFORM_BUFFER, img.filename().c_str(),
                         CURLFORM_BUFFERPTR, img.buffer,
                         CURLFORM_BUFFERLENGTH, img.bufferLength(),
                         CURLFORM_END);
```
I have read the binary data into `img.buffer`.
```c
            field = curl_mime_addpart(form);
            curl_mime_name(field, "image");
            curl_mime_filename(field, img.filename().c_str());
            curl_mime_data(field, (const char *)img.buffer, (curl_off_t)img.bufferLength);
```
Is there any problem?
- should I extract the file extension of  `img.filename().c_str()`?
- I don't want to reopen and reread the binary,  I used `curl_mime_data` API after `curl_mime_filename`, not `curl_mime_filedata`, Is it OK?

**Comment by bagder** [comment]
First, this is a bug tracker. If you have questions, use the curl-library mailing list.

curl_mime_name - sets a name for the part
curl_mime_filename - sets the *filename* of the part

You and only you decide what to name the part and the file name. Typically the part is named by the form that you're posting this "to".
