### ISSUE TITLE
duphandle doesn't preserve CURLOPT_SSLENGINE

### ISSUE THREAD

**Issue by lbonn** [curl/curl#2829]
Similar to #2485, an option is not propagated to duplicated handles.

### I did this

```
CURL *curl = curl_easy_init(), *curl_clone;
curl_easy_setopt(curl, CURLOPT_SSLENGINE, "pkcs11");

curl_clone = curl_easy_duphandle(curl);

...

curl_easy_perform(curl_clone);
```

### I expected the following

`curl_easy_perform` uses the specified SSL engine. In reality, `curl_easy_setopt` needs to be called again on the cloned handle to make it work.

### curl/libcurl version

```
curl -V
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.0.2o zlib/1.2.11
Release-Date: 2018-07-11
Protocols: file ftp ftps http https
Features: AsynchDNS IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
```

### operating system

Linux

**Comment by bagder** [comment]
Confirmed. I think we need to store the name separately so that we can set it again when dup'ed...

@lbonn are you interested in making a PR to fix this?

**Comment by lbonn** [comment]
Yes, I can take a shot.
