### ISSUE TITLE
--disable-symbol-hiding not working anymore?

### ISSUE THREAD

**Issue by MoMuBud** [curl/curl#2830]
when configuring curl with "--disable-symbol-hiding" it used to expose the functions 

"Curl_base64_encode" and "Curl_base64_decode"

nm ./lib/.libs/libcurl.so | grep encode

[2051] | 68028| 72|FUNC |GLOB |0 |12 |Curl_base64_encode
[2542] | 68100| 72|FUNC |GLOB |0 |12 |Curl_base64_decode 

Somewhere along the way this behaviour changed and with the current version 7.61.0 they are no longer exposed and "nm" command shows that they are classified as "LOCL".

For more details please look at the discussion:  https://curl.haxx.se/mail/lib-2018-07/0136.html
where Dan Fandrich shares more inside details.

**Comment by bagder** [comment]
@dfandrich also found out that [libtool is to blame](https://curl.haxx.se/mail/lib-2018-08/0013.html)

**Comment by bagder** [comment]
The offending commit that caused the regression (found by @dfandrich): 4b414249107a
