### ISSUE TITLE
Filename not correct with -O with aws s3 presigned url

### ISSUE THREAD

**Issue by yangyadi1993** [curl/curl#2832]
### I did this

I presigned a aws s3 file with my credentials using
`aws s3 presign s3://foo/bar.txt`
And then tried to download this file using curl
`curl -O https://foo/bar.txt?AWSAccessKeyId=XXXX&Expires=XXXX&Signature=XXXX%3D`

### I expected the following
bar.txt

But I got bar.txt?AWSAccessKeyId=XXXX&Expires=XXXX&Signature=XXXX%3D

### curl/libcurl version

[curl -V output]
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

### operating system
macOS
debian

**Comment by yangyadi1993** [comment]
Besides, there is no filename in the response header and no redirect. I could get the right filename by using web browser.

**Comment by bagder** [comment]
It is by design. `-O` will take whatever is on the right side of the rightmost slash and use that as a file name.

> I could get the right filename by using web browser.

Well, it's not the "right" as per how curl behaves... I recommend using the `-o` option and set your own file name to be whatever you like!

**Comment by jay** [comment]
If the server specifies the filename in its response headers you can use [-J, --remote-header-name](https://curl.haxx.se/docs/manpage.html#-J).
