### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [curl/curl#2838]
Would you like to [replace any double quotes](https://github.com/curl/curl/blob/4af40b3646d3b09f68e419f7ca866ff395d1f897/lib/urldata.h#L139 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by bagder** [comment]
Why? We use double quotes for local include files, why should we not?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by elfring** [comment]
* How do you think about to avoid potential confusion around the wording “local (or current) directory”?
* Do you expect that (header) files for such a software library will be used from a storage location where they were installed?

-----

There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?

**Comment by bagder** [comment]
This is an issue tracker.

Do you have a specific problem with the include files?

**Comment by elfring** [comment]
I am trying to achieve that the needed files are actually retrieved from trusted directories according to preferred software build parameters.
How much will the selected file inclusion style matter then?

**Comment by bagder** [comment]
> I am trying to achieve that the needed files are actually retrieved from trusted directories

Are you building curl/libcurl with something else than one of the shipped build mathods and this method has a problem with C source files using include files within double quotes? What method/compiler/setup is this?

**Comment by elfring** [comment]
I suggest to take another look at the following difference.

```
…
#include <curl/curl.h>
…
#include "curl_sspi.h"
…
```

**Comment by bagder** [comment]
> I suggest to take another look at the following difference.

I looked. I see no problem. Do you?

**Comment by jzakrzewski** [comment]
@bagder I don't get this guy. He opens basically the same issues in various repositories. Everyone tells him "no" for more or less the same reasons you have stated and he just keeps going. The argumentation is basically a copy-paste.

The conclusion from one of the threads ( https://github.com/json-c/json-c/issues/440 ) was that he's a carbon-based bot ;)

**Comment by elfring** [comment]
* From which storage location should a library file be picked up preferably?
  * Known installation directory
  * Random (or temporary) software development status
* Do inclusion specifications for files like “curl.h” and “curl_sspi.h” refer to the same library version?

**Comment by bagder** [comment]
`"curl.h”` should never be included. We suggest `<curl/curl.h>` for applications since the header is supposed to be included from the system include path.

`curl_sspi.h` is a private header file that only libcurl uses when you build it, which is why it is included with double quotes. This is never included by applications.

**Comment by elfring** [comment]
>We suggest `<curl/curl.h>` for applications since the header is supposed to be included from the system include path.

Can this expectation fit to any more inclusion specifications of other software components?


>`curl_sspi.h` is a private header file that only libcurl uses when you build it, which is why it is included with double quotes.

How “private” is [such a header file](https://github.com/curl/curl/blob/4af40b3646d3b09f68e419f7ca866ff395d1f897/lib/curl_sspi.h#L1 "Declarations for cURL SSPI") during the mentioned software build process?


>This is never included by applications.

Would you like to increase the distinction for the safe reuse of software components there and at other stages of programming?

**Comment by bagder** [comment]
> Can this expectation fit to any more inclusion specifications of other software components?

Other libraries have their headers and defined use.

> How “private” is such a header file during the mentioned software build process?

Entirely private.

> Would you like to increase the distinction for the safe reuse of software components there and at other stages of programming?

What are you talking about?

I now conclude that you do not experience an issue with the include files, and therefore I close this issue.
