### ISSUE TITLE
Torture test 1502 fails with GCC 8

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#2861]
### I did this

Try to update GCC in travis to version 8:
https://github.com/MarcelRaad/curl/pull/4

### I expected the following
Successful CI checks.
Instead, the coverage job failed because test 1502 failed in torture test mode:
https://travis-ci.org/MarcelRaad/curl/jobs/414383771#L9163

### curl/libcurl version

7.61.1-DEV

### operating system

Ubuntu Trusty-based Travis

**Comment by bagder** [comment]
I can reproduce. Will look into it!
