### ISSUE TITLE
Make HTTP/0.9 opt-in

### ISSUE THREAD

**Issue by bagder** [curl/curl#2873]
### I did this

Use curl to get data from a server that isn't responding with a proper HTTP/1 or HTTP/2 response.

curl will gladly hand over the received data as HTTP body. This is because it supports "HTTP/0.9", which is how HTTP used to work before 1.0 (1996): that's just body bytes that ends with a closed connection.

### I expected the following

It should report an error if the response is not HTTP protocol compliant. I suspect this "liberal in what you accept" and treating everything as HTTP/0.9 might be surprising to users and I'm also afraid it could cause some unexpected behaviors.

HTTP/0.9 support should therefor be done opt-in. [mentioned on the mailing list in July 2018](https://curl.haxx.se/mail/lib-2018-07/0006.html) - no objections there.

### curl/libcurl version

curl 7.61.1 still has it supported by default.

### operating system

All

### Releated

HTTP/0.9 detection was improved in #2872 after which fixing this issue should be pretty easy.

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/issues/2420

@danielgustafsson are you working on `--http0.9`

**Comment by danielgustafsson** [comment]
> On 13 Aug 2018, at 20:43, Jay Satiro <notifications@github.com> wrote:
> 
> Ref: #2420
> 
> @danielgustafsson are you working on —http0.9

I was, but it fell off my radar due to ETOOMUCHLIFE happening, I’ll try to rebase it on top of the referenced commit this week to finalize it now that the http check went in.

**Comment by bagder** [comment]
FYI: I'm grabbing this!

**Comment by danielgustafsson** [comment]
> On 17 Dec 2018, at 15:19, Daniel Stenberg <notifications@github.com> wrote:
> 
> FYI: I'm grabbing this!

Thanks! I’ve had a hard time bubbling this one to the top of my TODO.
