### ISSUE TITLE
curl building with nss SSL backend on Debian 6

### ISSUE THREAD

**Issue by adnan-kamili** [curl/curl#2878]
I am trying to compile libcurl with NSS support for HTTPS. I installed `libnss3-dev` and following worked fine on debian 7:

`CPPFLAGS="-I/usr/include/nspr" ./configure --prefix=$PWD/build/libcurl3 --without-ssl --with-nss --with-pic --disable-ftp --disable-file --disable-ldap --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-ares --disable-debug  --disable-rtmp  --without-librtmp --without-zlib --without-libidn --disable-shared`

But same fails to detect NSS on Debian 6.

```
checking whether to enable Windows native SSL/TLS (Windows native builds only)... no
checking whether to enable Apple OS native SSL/TLS... no
checking for pkg-config... no
checking for SSL_VersionRangeSet in -lnss3... no
checking for ssl_version in -laxtls... no
configure: WARNING: SSL disabled, you will not be able to use HTTPS, FTPS, NTLM and more.
configure: WARNING: Use --with-ssl, --with-gnutls, --with-polarssl, --with-cyassl, --with-nss, --with-axtls, --with-winssl, or --with-darwinssl to address this.
```

**Comment by bagder** [comment]
When configure fails, always check `config.log` around the failed check for clues about what specifically that failed. curl has been built with NSS for a long time so this is likely to be a missing dependency or something.

The `checking for SSL_VersionRangeSet in -lnss3... no` could imply that your NSS installation is simply too old?

**Comment by adnan-kamili** [comment]
The installed NSS version is: `3.12.8-1+squeeze14`
 Following is the log:

```
configure:25306: checking for SSL_VersionRangeSet in -lnss3
configure:25328: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers -isystem /usr/include/nspr -I/usr/include/nss   conftest.c -lnss3  -L/usr/lib -lssl3 -lsmime3 -lnss3 -lnssutil3 -lrt >&5
/tmp/cc80C6QV.o: In function `main':
conftest.c:(.text+0x7): undefined reference to `SSL_VersionRangeSet'
collect2: ld returned 1 exit status
```

**Comment by bagder** [comment]
That's it. curl requires NSS 3.14.x or later since 7.34.0 (commit 30e7e7552ba4397)

**Comment by adnan-kamili** [comment]
Thanks! So, I guess the only option left is to use v7.33

**Comment by bagder** [comment]
I'd rather recommend to get a newer NSS installed.

**Comment by adnan-kamili** [comment]
I doubt Debian 6 allows for a newer version.

**Comment by bagder** [comment]
Closing this issue since it wasn't really a bug.
