### ISSUE TITLE
curl not outputting line breaks consistently across version/OS

### ISSUE THREAD

**Issue by andscoop** [curl/curl#2881]
### I did this
I ran `curl https://api.github.com/repos/astronomerio/astro-cli/releases/latest` on three separate machines.

#### Machine 1
OS: OsX 10.3.16
curl version: `curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0`

#### Machine 2
OS: Arch Linux
curl version:  `curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.32.0`

#### Machine 3
OS: Ubuntu 18.04.1 LTS
curl version: `curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3`

### I expected the following

I expect prettified (non minified) json output.

#### Actual Outcomes
- Machine 1: `pass`
- Machine 2: `pass`
- Machine 3: `fail`

#### Significane
The minified json output prevents a user from `grep`'ing the output and parsing matching lines.
ie. 
https://github.com/goreleaser/godownloader/blob/0c87c49c85d1a59ff62e087be26c12fd9c64c047/shellfn.go#L190

**Comment by bagder** [comment]
I don't have such a system but the versions I've tried do not reproduce. Can you show us how the "3" case's request headers differ from the other requests?

`curl -v -s https://api.github.com/repos/astronomerio/astro-cli/releases/latest -o /dev/null 2>&1 | grep '^> '`

I have a feeling they won't differ much and that the server-end is to blame for sending back something different. You can try to set a different user-agent on the "3" system to see if it returns something else:

`curl -A moo/2000 https://api.github.com/repos/astronomerio/astro-cli/releases/latest`

**Comment by jay** [comment]
I'm not sure why you think curl is responsible for this. Can you attach the output of each of the 3? What happens when you use jq?

`curl --fail --location -sS --proto =https https://api.github.com/repos/astronomerio/astro-cli/releases/latest | jq --raw-output ".assets[].browser_download_url"`

**Comment by bagder** [comment]
curl's default user-agent header field is `curl/[version]`. You set it with `-A` and you can edit `~/.curlrc` if you want to set it for all command line invokes. See [-K](https://curl.haxx.se/docs/manpage.html#-K).

**Comment by andscoop** [comment]
Update:

In the case of the ubuntu system (Machine 3) it appears that `Mozilla/5.0 Gecko` is overwritten in in the .curlrc file. Commenting out that line allowed it to go back to using the expected default.

Thank you for your help @bagder @jay
