### ISSUE TITLE
SFTP upload is slow

### ISSUE THREAD

**Issue by zhanghailiang-1986** [curl/curl#2884]
LibCurl:curl-7.61.0
Agreement: SFTP
Server: serve -u running on local network
Client: embedded device
             The compiler of my device is arm_v5t_le-gcc. In order to enable the device to support SFTP, I compiled libcurl.so. Then upload the file time-consuming, I upload the file server for serve-u, 120K file size will take 17 seconds, feel too long.

Any help is this regard is appreciated.

Thanks!

**Comment by bagder** [comment]
Try changing `UPLOAD_BUFSIZE` in `lib/urldata.h` (to something like 128KB or so), rebuild libcurl and try again. Also make sure that you're using a recent ssh library (I assume you're using libssh2 ?)

**Comment by zhanghailiang-1986** [comment]
i used libssh2-1.8.0.tar. ok, i try it. thanks.

**Comment by zhanghailiang-1986** [comment]
l find it. if set CURLOPT_FORBID_REUSE 0,wasting time is only 1s. thanks all the same.

**Comment by bagder** [comment]
Also, if you set `CURLOPT_VERBOSE` to `1L` you'll get information about what curl actually does in that time, which can turn out to be useful clues.

**Comment by zhanghailiang-1986** [comment]
Yes, indeed, every new connection takes a long time and is not the reason for modifying CURLOPT_FORBID_REUSE. I looked at the service-u server log, uploading the file took only one second, and connecting it took 13 seconds, and the server log also showed that the first connection failed and the second succeeded. But libcurl didn't return the error here. All I saw was a longer upload time. Here is serve-u's log:

[31] Wed 15Aug18 15:48:22 - (001525) SSH2_MSG_USERAUTH_FAILURE: 登录失败
[30] Wed 15Aug18 15:48:22 - (001525) SSH2_MSG_USERAUTH_REQUEST: 用户： zhang；服务： ssh-connection；类型： password
[02] Wed 15Aug18 15:48:22 - (001525) 用户 "zhang" 已登录
[31] Wed 15Aug18 15:48:22 - (001525) SSH2_MSG_USERAUTH_SUCCESS: 登录成功

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
