### ISSUE TITLE
Self-defined Cerificate Verifier Support？

### ISSUE THREAD

**Issue by elviswoo** [curl/curl#2897]
hi，Is there a way that make me define a custom certificate verifier when i use curl https？

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
