### ISSUE TITLE
Cant compile using winbuild and developer console

### ISSUE THREAD

**Issue by Hasplit** [curl/curl#2907]
### I did this
In VS2017 Developer console i typed `nmake /f H:\Libraries\sleepy-discord-master\deps\cpr\opt\curl\winbuild\Makefile.vc mode=static VC=14` and it output 

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build>nmake /f H:\Libraries\sleepy-discord-master\deps\cpr\opt\curl\winbuild\Makefile.vc mode=static VC=14

Microsoft (R) Program Maintenance Utility Version 14.15.26726.0
Copyright (C) Microsoft Corporation.  All rights reserved.

H:\Libraries\sleepy-discord-master\deps\cpr\opt\curl\winbuild\Makefile.vc(69) : fatal error U1052: file '../lib/Makefile.inc' not found
Stop.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build>
```
### I expected the following
Well i expected it to build 

### curl/libcurl version
7.61.0

### operating system
Win10

**Comment by bagder** [comment]
The `BUILD.WINDOWS.txt` says:

> Once you are in the console, go to the winbuild directory in the Curl
> sources:
>    cd curl-src\winbuild

> Then you can call nmake /f Makefile.vc with the desired options (see below).

You seem to have skipped that initial `cd` and thus the relative paths won't work.

**Comment by bagder** [comment]
No response yet but basically triggered by a minor mistake. Closing this issue.
