### ISSUE TITLE
SCP and SFTP tests fail with openssh-7.8p1

### ISSUE THREAD

**Issue by kdudka** [curl/curl#2917]
`ssh-keygen -t rsa` with `openssh-7.8p1` produces private key in a format that current versions of libssh and libssh2 do not understand.  Consequently, the `-m PEM` option of ssh-keygen needs to be used with up2date openssh for curl to work:

https://src.fedoraproject.org/cgit/rpms/curl.git/tree/0105-curl-7.61.0-tests-ssh-keygen.patch?id=8bff7e0d

Unfortunately, the `-m` option of `ssh-keygen` is not available on older versions of openssh.  So it should be used, only if the utility actually supports it.  As I do not speak perl, I do not feel like writing the upstream fix myself.

### curl/libcurl version
`curl-7_61_0-132-gcc67b0a2e`

### related bug in RHBZ
https://bugzilla.redhat.com/1622594

**Comment by vszakats** [comment]
It may be a long shot (I haven't tested it yet), but have you tried with the latest libssh2 master? It contains this patch, which might help: https://github.com/libssh2/libssh2/commit/03092292597ac601c3f9f0c267ecb145dda75e4e

**Comment by kdudka** [comment]
@vszakats You are right!  https://github.com/libssh2/libssh2/commit/03092292597ac601c3f9f0c267ecb145dda75e4e fixes it.

**Comment by kdudka** [comment]
Works as expected with `libssh-0.8.3`, too.

**Comment by bagder** [comment]
Closing as this is not really a curl bug.
