### ISSUE TITLE
-o <filename> option not work when multiple URL requested in -K <a_config_file>

### ISSUE THREAD

**Issue by abdulbadii** [curl/curl#2921]
I type in terminal:

curl -L -K tt.txt -o MYBOOK.pdf

but only downlload the first URL , the rest is dumped on terminal output

[tt.txt](https://github.com/curl/curl/files/2335146/tt.txt)

Anyone care this.. Thanks in advance

**Comment by bagder** [comment]
This is in fact the expected and documented behavior.

You're supposed to use one `-o` (or `-O`) for each URL you specify. Or `--remote-name-all`.

**Comment by abdulbadii** [comment]
still not work after being updated..
[tt.txt](https://github.com/curl/curl/files/2339941/tt.txt)
..

**Comment by bagder** [comment]
The `-o` arguments need to be on a separate line, the config parser only handles on option per line in the file iirc.

**Comment by abdulbadii** [comment]
Yeah, I'm just very new to curl now simply works like a charm!
