### ISSUE TITLE
* Resolve xx.co:4433:47.254.129.48,47.88.188.111 found illegal!

### ISSUE THREAD

**Issue by bigbrother323** [curl/curl#2933]
### I did this
	host = curl_slist_append(host, "xx.co:4433:47.254.129.48,47.88.188.111");
	curl_easy_setopt(curl_handle, CURLOPT_RESOLVE, host);
### I expected the following
        if one ip cannot connect, libcurl can auto use another ip for the host
### curl/libcurl version

[curl -V output]
cURL/7.61.0 
### operating system
win10
vs2017

**Comment by bagder** [comment]
curl --resolve example.com:80:192.168.0.40,127.0.0.1 http://example.com -v

This works fine for me on Linux. Fails to connect to the first IP, then tries the second and succeeds...

**Comment by jay** [comment]
We need your actual `curl -V` if you're using the curl tool or `curl_version()` if you're using libcurl because you may not be using the version that you think you are.

**Comment by bigbrother323** [comment]
It work on command line,I must have made a mistake somewhere.

**Comment by bagder** [comment]
So do we consider this case closed?
