### ISSUE TITLE
PHP7 no cURL SSL support

### ISSUE THREAD

**Issue by fesarlis** [curl/curl#2934]
Hello.

I follow a standard procedure for years to compile PHP, Apache, OpenSSL etc under CentOS 64-bit. After upgrading to PHP7 I am facing an issue with cURL. While it compiles fine, PHP does not seem to recognise the OpenSSL package that cURL was compiled against.
As a result, under phpinfo page cURL shows neither SSL nor HTTP/2 support. It also does not show OpenSSL version.

**I do not have any of these issues with PHP 5.6 (same procedure followed).**

PHP compilation time pops a warning like the following:

`#warning "libcurl was compiled with SSL support, but configure could not determine which
`
etc

also I notice the following:

```
checking for cURL 7.10.5 or greater... 7.61.0
...
checking for openssl support in libcurl... no
```

I would appreciate some help. Please let me know if you need some extra clarifications.

**Comment by fesarlis** [comment]
Thank you for your reply.
I understand. However it is not quite clear whether this is a curl or php issue, so I decided to inform you as well. curl was compiled like this:

`./configure --prefix=/opt/servers/curl --with-ssl=/opt/servers/openssl --with-nghttp2=/opt/servers/nghttp2`

**Comment by bagder** [comment]
And in the end of curl's configure run, does it say it found and used OpenSSL or not?

**Comment by fesarlis** [comment]
Here is the output you mention:

```
  curl version:     7.61.0
  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /opt/servers/curl
  Compiler:         gcc
  SSL support:      enabled (OpenSSL)
  SSH support:      no      (--with-libssh2)
  zlib support:     enabled
  brotli support:   no      (--with-brotli)
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  enabled
  resolver:         POSIX threaded
  IPv6 support:     enabled
  Unix sockets support: enabled
  IDN support:      no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   /etc/pki/tls/certs/ca-bundle.crt
  ca cert path:     no
  ca fallback:      no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     enabled
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  PSL support:      no      (libpsl not found)
  HTTP2 support:    enabled (nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
```
Also, here are some warnings produced during PHP's make:

```
/opt/packages/php-7.2.9/ext/curl/interface.c:74:5: warning: #warning "libcurl was compiled with SSL support, but configure could not determine which" "library was used; thus no SSL crypto locking callbacks will be set, which may " "cause random crashes on SSL requests" [-Wcpp]
 #   warning \
     ^
In file included from /opt/servers/curl/include/curl/curl.h:2787:0,
                 from /opt/packages/php-7.2.9/ext/curl/interface.c:39:
/opt/packages/php-7.2.9/ext/curl/interface.c: In function ‘_php_curl_setopt’:
/opt/servers/curl/include/curl/typecheck-gcc.h:74:42: warning: call to ‘_curl_easy_setopt_err_progress_cb’ declared with attribute warning: curl_easy_setopt expects a curl_progress_callback argument for this option [enabled by default]
         _curl_easy_setopt_err_progress_cb();                                  \
                                          ^
/opt/packages/php-7.2.9/ext/curl/interface.c:2803:4: note: in expansion of macro ‘curl_easy_setopt’
    curl_easy_setopt(ch->cp, CURLOPT_PROGRESSFUNCTION, curl_progress);
    ^
```

**Comment by bagder** [comment]
> SSL support:      enabled (OpenSSL)

This line says curl's configure found OpenSSL just fine and that you'll build with that support enabled.

I *guess* that your PHP building problem is then possibly because you have more than one libcurl installed in your system and your build doesn't detect/use your most recent one. But again: PHP build issues should be taken to a PHP forum to get the attention they need.

**Comment by fesarlis** [comment]
Thank you Daniel.
Sadly the libcurl installed is required by Centos as you may know. The strange thing (as I previously mentioned) is that the issue does not occur with PHP 5.6. In any case I will try to ask something in some PHP forum.
Thank you for your time.
