### ISSUE TITLE
SFTP (libssh2) postquotes are executed despite operation will be retried

### ISSUE THREAD

**Issue by tomaszewskip** [curl/curl#2939]
### I did this

1. Setup cURL easy interface to do some operations on the sftp server (let's call it `sftp://server`),
2. call curl_easy_perform to execute operation from previous step,
3. call curl_easy_reset to clear structures, but leave handle to reuse existing connection,
4. setup CURLOPT_URL to download file from `sftp://server` (`sftp://server/file1`),
5. setup CURLOPT_POSTQUOTE to remove `sftp://server/file1` when download is successful,
6. call curl_easy_perform

Following code shows this approach
<pre>
CURL *handle = curl_easy_init();
// setup some operation here, which is done on sftp://server
curl_easy_perform(handle);
curl_easy_reset(handle);
curl_easy_setopt(handle, CUROPT_URL, "sftp://server/file");
curl_easy_setopt(handle, CURLOPT_POSTQUOTE, "*rm sftp://server/file");
// setup write functions
curl_easy_perform(handle)
</pre>

### What may happen:
- first curl_easy_perform is successful,
- during second curl_easy_perform, it is decided to retry operation, as existing connection cannot be reused,
- sftp_done is called to cleanup connection,
- post quote commands are executed and `sftp://server/file` is removed,
- new connection is established and it fails as `sftp://server/file` does not exist.

### I expected the following

Postquote commands are not executed when retry operation is going to be executed, as explained here: https://curl.haxx.se/libcurl/c/CURLOPT_POSTQUOTE.html
<pre>
[...]  The commands will only be run if no error occurred [...]
</pre>

Following patch does the thing:
<pre>
Index: curl-7.61.0/lib/ssh.c
===================================================================
--- curl-7.61.0.orig/lib/ssh.c
+++ curl-7.61.0/lib/ssh.c
@@ -3218,8 +3218,10 @@ static CURLcode sftp_done(struct connect
   if(!status) {
     /* Post quote commands are executed after the SFTP_CLOSE state to avoid
        errors that could happen due to open file handles during POSTQUOTE
-       operation */
-    if(!status && !premature && conn->data->set.postquote) {
+       operation. This step is skipped if this is retry operation, to avoid
+       executing postquotes when operation is not successful.*/
+    if(!status && !premature && conn->data->set.postquote
+               && !conn->bits.retry) {
       sshc->nextstate = SSH_SFTP_POSTQUOTE_INIT;
       state(conn, SSH_SFTP_CLOSE);
     }
</pre>

### curl/libcurl version
7.61.0

### operating system
Ubuntu 16.04 (libssh2 1.8.0)

**Comment by bagder** [comment]
Thanks! I noticed the libssh backend has the exact same logic so I copied your fix into that function as well and made a PR out of your patch: #2940
