### ISSUE TITLE
libcurl.so: undefined reference to `X509_get_version'

### ISSUE THREAD

**Issue by jungle-boogie** [curl/curl#2945]
### I did this

`git pull` on my openbsd -current x64 machine, which was previously running and installed curl without any issue.
```
$ curl -V
curl 7.61.0 (x86_64-unknown-openbsd6.4) libcurl/7.61.0 LibreSSL/2.8.0 zlib/1.2.3 nghttp2/1.32.1
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

However, it now fails to build:
```
/home/jungle/bin/curl/build/lib/libcurl.so: undefined reference to `X509_get_version'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error 1 in . (src/CMakeFiles/curl.dir/build.make:1197 'src/curl')
*** Error 1 in . (CMakeFiles/Makefile2:1069 'src/CMakeFiles/curl.dir/all')
*** Error 1 in /home/sean/bin/curl/build (Makefile:141 'all')
```

### I expected the following

Successful build of current from github.

**Comment by bagder** [comment]
`X509_get_version` is a function in libressl that both 7.61.0 and 7.61.1 use. I can't see why that would suddenly fail...

**Comment by jungle-boogie** [comment]
Hi,

I think this was an issue with compiling. Carefully reviewing the output of
`curl - v` above, I can see some subtle differences with what it should be.
Deleting the curl directory I had, cloning, and doing the build processed
proved to be successful.

Sorry for the noise.

>
