### ISSUE TITLE
How to get the statistics of SFTP sever? 

### ISSUE THREAD

**Issue by piakchu** [curl/curl#2946]
###I want to use C++ with the library libcurl to do it. The official website shows that the command "statvfs file" can do it like the title says. I have tried but failed. The error code is 'CURLE_QUOTE_ERROR (21)'.  Even it is right, I still don't know how to extract the information. I mean I don't have a container to store these information.

### My code is here:
```
int main ()
{
        CURL *curl;
	CURLcode res = CURLE_OK;
        curl_global_init(CURL_GLOBAL_DEFAULT);
	curl = curl_easy_init();
	if (curl) {
		curl_easy_setopt(curl, CURLOPT_URL, "my sftp server url");
		curl_easy_setopt(curl, CURLOPT_USERPWD, "username:password");
		curl_slist *headerlist = NULL;
		const char* s1 = "statvfs xxx.txt";
		headerlist = curl_slist_append(headerlist, s1);
		curl_easy_setopt(curl, CURLOPT_QUOTE, headerlist);
		curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
		res = curl_easy_perform(curl);
		if (res != CURLE_OK)
			fprintf(stderr, "%d\n", res);
		std::cout << headerlist->data << std::endl;
		curl_easy_cleanup(curl);
	}
	curl_global_cleanup();
	return (int)res;
}
```

### curl/libcurl version 7.61.1

[curl -V output]

**Comment by bagder** [comment]
This is an issue tracker, not a forum for questions - please use the curl-library mailing list for that. The results for `statvfs` are passed as a header, so presumably you receive it easiest with the header callback.
