### ISSUE TITLE
rename curl_easy_conn_upkeep() to curl_easy_upkeep() ?

### ISSUE THREAD

**Issue by bagder** [curl/curl#2951]
Hey @cmeister2,

(Follow-up to 7b655fcbad and #1641)

I propose we remove the "conn" part from the name (and the associated option) to:

1. make the name shorter
2. allow it to possibly do other "upkeep" things that aren't strictly related to connections (if we can think of any)
3. the use of singular "conn" is wrong anyway, isn't it?

Whatdoyousay?

**Comment by danielgustafsson** [comment]
:+1: on changing due to #3, I don't mind long names but "conn" implies that it works on a single connection which is incorrect.

**Comment by bagder** [comment]
I did some quick search-n-replacing so that nobody else would have to, and if we go down this line #2952 is here now.

**Comment by cmeister2** [comment]
I have no problem with this.
