### ISSUE TITLE
Callback for extended SSL certificate validation

### ISSUE THREAD

**Issue by xim** [curl/curl#2978]
https://curl.haxx.se/libcurl/c/CURLINFO_TLS_SSL_PTR.html#LIMITATIONS refers to issue #685, which is closed for comments. If it were open, I might have submitted my comment there.

I am writing a piece of software that uses libcurl compiled against the windows SSL implementation, SCHANNEL. I want to do verification of a self-signed certificate against a local cache (something akin to openssh style, authorized fingerprint per host).

So, to answer the “How are you using this option? Are you affected by any of these limitations? Please let us know”:

* I am using it to manually verify that the certificate fingerprint stays the same for a given host/IP.
* I am not affected by the limitations noted AFAIK, but would like to be able to abort the connection before any data is sent if the validation fails. I could probably use a callback for some other purpose (`CURLOPT_WRITEFUNCTION`?) + `CURLINFO_TLS_SSL_PTR` and try to fail the request from there, but that certainly feels like a hack...

**Comment by bagder** [comment]
> If it were open, I might have submitted my comment there

Right. Unfortunately we've felt a need to auto-close older issues since they're magnets to (mostly unrelated and unwanted) comments.

> openssh style, authorized fingerprint per host

And not just [public key pinning](https://curl.haxx.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html)?

> would like to be able to abort the connection before any data is sent if the validation fails

That's usually how people use `CURLOPT_SSL_CTX_FUNCTION`, but I see that schannel isn't supported for that option...

Since this is not really a bug, this issue will soon be closed.

**Comment by xim** [comment]
> And not just public key pinning?

I realize now that the text was far from clear on several points, let me elaborate =)

The first time I'm connecting I'd like to show a “This host has fingerprint xx::xx, do you wish to connect?” -> {yes{, and remember},no}.

Then, once it's in the cache, I can pin the certificate. I may still want to do an extended validation callback that happens on first connection after app restart, so I can do a “The certificate has changed, do you want to connect anyway?” prompt. Just pinning and failing, then reconnecting after the user has opted to remove the old fingerprint, might also be fine.

> That's usually how people use `CURLOPT_SSL_CTX_FUNCTION`

As far as I've understood it, that hooks too early in the process; It happens before the connection has been made. I would need a callback called after the connection has been made, but before any data is sent.

Any workarounds that would allow this e.g. for HTTPS only, or on OpenSSL only, would also be appreciated; I'd like not to have to include OpenSSL, but if I need to then so be it =)

**Comment by bagder** [comment]
Ok, thanks. But there's no bug in here right? We can close this now?

**Comment by xim** [comment]
> Ok, thanks. But there's no bug in here right? We can close this now?

No, more of a feedback on the limitations of `CURLINFO_TLS_SSL_PTR` / `CURLOPT_SSL_CTX_FUNCTION` as requested. If you want to make a feature such as this or not has to be up to you =)

For now, my code will do a "dummy" request against the service at the beginning of each session and use `CURLINFO_TLS_SSL_PTR` to get the cert, then ask for user input as required, then pin the certificate.

**Comment by bagder** [comment]
Thanks a lot!
