### ISSUE TITLE
Error building curl with --enable-ares=<path>

### ISSUE THREAD

**Issue by BradNewton** [curl/curl#2982]
### I did this
I built and installed c-ares with a destdir:
```
./configure --prefix=/usr
make
make DESTDIR=/code/curl/build/c-ares/instroot install
```
Then tried to build curl with --enable-ares specifying the installed dir:
```
./configure --enable-ares=/code/curl/build/c-ares/instroot/usr
```

### I expected the following
Configure would succeed.
### What happened

> checking for libcares options with pkg-config... found
> configure: pkg-config: ares LIBS: "-lcares  "
> configure: pkg-config: ares LDFLAGS: " "
> configure: pkg-config: ares CPPFLAGS: " "
> checking that c-ares is good and recent enough... no
> configure: error: c-ares library defective or too old

config.log shows that ares.h was not found
(the file is located at: /code/curl/build/c-ares/instroot/usr/include, but the ares CPPFLAGS  is empty.)

### What I've tried
It seems to be ignoring the path supplied with the --enable-ares parameter.

I've looked at the code in m4/curl-confopts.m4, it all looks good to me (I thought that [https://github.com/curl/curl/pull/2658/commits/94094d2b6bcb72e0dab076a0ae0ebc85362fc9f1](https://github.com/curl/curl/pull/2658/commits/94094d2b6bcb72e0dab076a0ae0ebc85362fc9f1) could have been related to this issue).

I'm not configuring pkg-config.
However if I change /code/curl/build/c-ares/instroot/usr/lib/pkgconfig/libcares.pc to have my install dir in the exec_prefix and use that as the includedir instead of ${prefix} then it succeeds.
e.g. change:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
```
to:
```
prefix=/usr
exec_prefix=/code/curl/build/c-ares/instroot${prefix}
libdir=${exec_prefix}/lib
includedir=${exec_prefix}/include
```

### curl/libcurl version
Curl v7.61.1
c-ares v1.14.0 (originally using v1.10.0, both have same issue)

This used to work using curl v7.51.0, I've just upgraded to 7.61.1 and found this issue.

### operating system
Linux Mint 17.3 (Ubuntu 14.04.5)

(Same issue on CentOS 7)

**Comment by dfandrich** [comment]
On Wed, Sep 12, 2018 at 03:28:32AM -0700, Brad wrote:
> Then tried to build curl with --enable-ares specifying the installed dir:
> 
> ./configure --enable-ares=/code/curl/build/c-ares/instroot/usr

Have you tried: 

./configure --enable-ares=/code/curl/build/c-ares/instroot

**Comment by dfandrich** [comment]
Actually, my suggestion is unlikely to work. I think the root of the problem is
installing with DESTDIR and expecting the code to work in that location.
DESTDIR is intended to be used when installing to a location that will be moved
to the final location later. For example, when building a package or binary tar
ball, the files can be staged at a nonprileged location temporarily, then
packaged up and installed properly later at the final location. If you want
c-ares installed at that location, you should be setting
--prefix=/code/curl/build/c-ares/instroot/usr not and using DESTDIR at all.

**Comment by BradNewton** [comment]
Thanks for the suggestion.
I'm not sure why we're using DESTDIR in our build script (although it is a temporary install as we're building a libcurl library to be used elsewhere).
I've just changed it to not use DESTDIR and have the full path in the c-ares prefix as you suggested.
It worked.
Thanks.

**Comment by bagder** [comment]
So this wasn't really a bug then and we can close this, right?

**Comment by BradNewton** [comment]
You can specify the path where c-ares was installed.
The path given to --enable-ares is stored in $want_ares_path and then if no pkg-config is found, it's used:
```
ares_CPPFLAGS="-I$want_ares_path/include"
ares_LDFLAGS="-L$want_ares_path/lib"
```
I think the issue I was having is that it's looking for the pkg-config in the location that c-ares would have put one:
`ARES_PCDIR="$want_ares_path/lib/pkgconfig"` so then `CURL_CHECK_PKGCONFIG` would successfully find a config, which obviously doesn't contain the value given to enable-ares.
So from a curl point of view it looked for a config, found one and used it.

We were installing c-ares to a temporary location, so I think using DESTDIR was valid, but as that isn't added to the pkgconfig/libcares.pc curl wouldn't find it.

I'll close this issue as there is a solution for it (don't use DESTDIR in c-ares if you're installing it for use with curl).
