### ISSUE TITLE
Assume OpenSSL engine support in 0.9.8 or later

### ISSUE THREAD

**Issue by rainerjung** [curl/curl#2983]
Commit d6417f6c2ddb10099da2c7ad0ffeebaa732aa824 added inclusion of engine.h when OpenSSL is of version 1.0.0 or newer. That's good, but the conservative approach t limit the fix to OpenSSL >= 1.0.0 isn't correct. ENGINE_cleanup() and other needed symbols, which get used to HAVE-checks and need engine.h were already introduced at least in 0.9.8. I tried building curl 7.61.1 against OpenSSL 0.9.8 for testing with some old setup and building curl fails.

The following will fix it at least for 0.9.8. I have not tested with 0.9.7, so will rstrict the fix to 0.9.8. Patch:

```
--- lib/vtls/openssl.c 2018-09-04 22:46:08.000000000 +0200
+++ lib/vtls/openssl.c 2018-09-12 13:25:38.298075000 +0200
@@ -69,7 +69,7 @@
 #include <openssl/ocsp.h>
 #endif

-#if (OPENSSL_VERSION_NUMBER >= 0x10000000L) && /* 1.0.0 or later */     \
+#if (OPENSSL_VERSION_NUMBER >= 0x0090800fL) && /* 1.0.0 or later */     \
   !defined(OPENSSL_NO_ENGINE)
 #define USE_OPENSSL_ENGINE
 #include <openssl/engine.h>
```

**Comment by bagder** [comment]
I figure the comment needs an update too!

**Comment by bagder** [comment]
I turned it into a PR (with you as author).
