### ISSUE TITLE
DOH test 1650 sometimes crashing

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#2987]
### I did this

Every few days, an autobuild crashes on test 1650. For example here:
https://curl.haxx.se/dev/log.cgi?id=20180912075757-1213#prob2

```
test 1650...[DOH]
./unit/unit1650 - >log/stdout1650 2>log/stderr1650
sh: line 1: 9864 Segmentation fault ./unit/unit1650 - > log/stdout1650 2> log/stderr1650
CMD (35584): ./unit/unit1650 - >log/stdout1650 2>log/stderr1650

unit1650 returned 139, when expecting 0
```

### I expected the following

No crashes

### curl/libcurl version

Nightly build, e.g. curl-7.62.0-20180912

### operating system

MinGW-w64 on Windows

**Comment by bagder** [comment]
Can you reproduce it manually if you just repeatedly run this test many times? I just can't, but then I don't test on the same target platform. It is difficult to figure out without more details... :-/

**Comment by MarcelRaad** [comment]
I couldn't reproduce it with a few tries, but I'll try harder in the coming days and try to get a callstack.

**Comment by MarcelRaad** [comment]
So the crash is at https://github.com/curl/curl/blob/f2b1a1897537d1915ac2f840b13a8991018755c4/tests/unit/unit1650.c#L274:
```
      snprintf((char *)buffer, sizeof(buffer), "%d.%d.%d.%d\n",

               a->ip.v4 & 0xff, (a->ip.v4>>8) & 0xff,

               (a->ip.v4>>16) & 0xff, a->ip.v4 >>24);
```
where `a` is first dereferenced.

My MinGW-w64's GCC 7.3.0 also warns about this, which seems to be the cause:
```
unit1650.c:271:18: warning: array subscript is above array bounds [-Warray-bounds]
       a = &d.addr[i];
```

`i` isw 50 here.

**Comment by bagder** [comment]
Thanks @MarcelRaad, that clearly identified the flaw. Submitted a PR I believe corrects it. An out of buffer access that wasn't detected because the check below was also wrong!
