### ISSUE TITLE
SecureDNS.eu isnd

### ISSUE THREAD

**Issue by beerisgood** [curl/curl#2990]
Damn. I push enter button to fast and whole issue is broken.

Title: SecureDNS.eu isn't out-of-date

Message: The guys fix the problems

**Comment by bagder** [comment]
I don't understand a single word of this.

Is there a problem or isn't there? If there is, can you please spell it out with details?

**Comment by beerisgood** [comment]
On https://github.com/curl/curl/wiki/DNS-over-HTTPS#out-of-date-servers SecureDNS.eu is listed as out-of-date
But they fix their problems and it's now up-2-date

**Comment by bagder** [comment]
You're talking about a wiki page - that's open for everyone to help out to edit. If you have updates, please update. This is not a curl bug!
