### ISSUE TITLE
darwinssl: linking without weak link?

### ISSUE THREAD

**Issue by liran999** [curl/curl#3007]
hey :)
i am building curl for IOS with darwinssl.
i'm trying to link libcurl.a to a dylib that must not have weak linking.
i've added the -Wl,-no_weak_imports to LDFLAGS for this purpose but i'm still getting this error:
weak import of symbol '_SSLCopyALPNProtocols' not supported because of option: -no_weak_imports

is there a way to use darwinssl without weak linking?
Thanks!

**Comment by liran999** [comment]
still interested in some help :) thanks!

**Comment by bagder** [comment]
Is there actually anything that suggests that you can do this without weak linking at all?
