### ISSUE TITLE
Spuriously corrupt data with HTTP/2 and SOCKS proxy

### ISSUE THREAD

**Issue by alexcrichton** [curl/curl#3009]
### I did this

This unfortunately isn't a very precise bug report, but I'm opening in hopes that I can get some help in reducing the bug to something that can be worked on!

For quite some time Cargo, [the Rust programming language's package manager](https://doc.rust-lang.org/stable/cargo/), has used libcurl as its backend for downloading files over HTTP. Bindings for libcurl in Rust are present at https://github.com/alexcrichton/curl-rust and wrap up the low-level C APIs in a more Rust-y and safe API. We've just now recently started [adding HTTP/2 support](https://github.com/rust-lang/cargo/pull/6005) to Cargo to leverage downloading crates in parallel, getting some awesome speedups along the way!

When testing out proxy support with libcurl and HTTP/2, however, we started to get some weird behavior. Detailed in [this comment](https://github.com/rust-lang/cargo/pull/6005#issuecomment-422136781) it appears that downloads will spuriously fail for a variety of reasons. Some downloads are flat out truncate, others appear corrupt and fail our checksum test, and some print out scary nghttp2 warnings! In all cases though the behavior is nondeterministic and changes from run-to-run.

The SOCKS proxy in use is `ssh $host -vND 1080` (using ssh's built-in capabilities for this) and configured via `HTTPS_PROXY=socks5a://localhost:1080`.

Now this unfortunately definitely isn't very reproducible for you, the curl developers! I was wondering, though, what I could do to best help out. Is the various logging I could turn on to perhaps get some debug information to see what's going on here? Or is this perhaps a known issue? In any case, just let me know!

### I expected the following

I expected that using a proxy with HTTP/2 would work reliably as it does with HTTP/1.1, in that the same way of configuring a proxy in HTTP/1.1 would work transparently with HTTP/2. This may be wrong though (and may require more configuration?) so just let me know!

### curl/libcurl version

* We're using the [7.61.1 release](https://github.com/curl/curl/tree/432eb5f5c254ee8383b2522ce597c9219877923e) compiled from source
* Similarly `nghttp2` is [compiled from source](https://github.com/nghttp2/nghttp2/tree/ed7c9db2a657005fa80eb44593f99dbbf57e6dec) as well

### operating system

Linux (ubuntu 16.04)

**Comment by alexcrichton** [comment]
Hm so I'm a little perplexed now. I managed to [reduce this](https://gist.github.com/alexcrichton/d05b4ee0e641b9e3258eb79c2b92daa0) to only using the C API, but originally after I created that reproduction I couldn't get the same errors! Oddly enough when I reverted the `curl` git checkout to the same commit Cargo is testing with I was actually able to reproduce the same errors (302 status codes instead of 200, partial transfer errors, etc).

So maybe this was a bug that was fixed on the master branch? Looking over the commits I don't necessarily see anything directly related, however. Are there known fixes in [this range](https://github.com/curl/curl/compare/curl:432eb5f...curl:927cb37)?

Plugging the master branch of this repository into Cargo does indeed appear to fix the issue as well. I'm no longer getting spurious checksum failures in Cargo or other sorts of various errors.

In any case, if the root cause isn't needed I'm fine closing this!

**Comment by bagder** [comment]
A possible explanation for the changed/fixed behavior could be that we've deprecated support for pipelining; the `CURLPIPE_HTTP1` bit no longer does anything (since f7208df7d9d5). (Our http 1.1 pipelining support is known to be a little flaky, which is a primary reason for the deprecation).

You can verify this by retrying your original recipe but without that bit set.

Either way, we don't particular need the root cause - as long as the current master cannot reproduce we're happy and fine!

**Comment by alexcrichton** [comment]
Ok thanks for the info! Another team member for Cargo is [seeing errors](https://github.com/rust-lang/cargo/pull/6005#issuecomment-422218901) still after using the master branch of `curl`, but I can't reproduce myself yet. I'll go ahead and close this in the meantime.

You're right as well that removing `CURLPIPE_HTTP1` seems to fix the issue I was seeing before with a local ssh socks proxy, thanks for the tip!
