### ISSUE TITLE
How to use curl.exe to support Chinese in Form-Data

### ISSUE THREAD

**Issue by luoyouchun** [curl/curl#3020]
I use to curl to uppload a File to http server
the command is:
 **.\curl.exe http://127.0.0.1:3128/upload -F "file=@c:\我.txt;filename=我.txt";**
The operator is succeed. but the filename is wrong.

how to use iconv to transfer the unicode(gb)to UTF-8 ?

**Comment by bagder** [comment]
(This is a bug tracker, not a forum for questions. Please use a [mailing list](https://curl.haxx.se/mail/) for questions/help.)

An easy approach is to just provide another file name manually, like this:

    curl.exe http://127.0.0.1:3128/upload -F "file=@c:\我.txt;filename=plainfilename.txt"
