### ISSUE TITLE
‘CURLU’ was not declared in this scope

### ISSUE THREAD

**Issue by chenguang9239** [curl/curl#3028]
### I want to use "curl_url_get" to get host and path form a url string, my file looks like:
```
#include <curl/curl.h>
#include <iostream>
#include <string>

int main(){
    std::string url;
    curl_global_init(CURL_GLOBAL_ALL);
    CURLU *h = curl_url();
    //"https://example.com/path?q=name"
    curl_url_set(h, CURLUPART_URL, urlString.c_str(), 0);
    char *host,*path;
    curl_url_get(h, CURLUPART_HOST, &host, 0);
    url += host;
    curl_free(host);

    curl_url_get(h, CURLUPART_PATH, &path, 0);
    url += path;
    curl_free(path);

    std::cout << url << std::endl;

    return 0;
}
```

### after running make, some error like:
```
error: ‘CURLU’ was not declared in this scope
```

### curl/libcurl curl-7.61.1

[curl -V output]

**Comment by chenguang9239** [comment]
I can not find the declaration of "CURLU" in all the header files in /usr/local/include/curl, did I install libconfig in a wrong way?

**Comment by bagder** [comment]
The URL API didn't exist in 7.61.1. It exists in git master and will be in 7.62.0 as the first release...

**Comment by chenguang9239** [comment]
> The URL API didn't exist in 7.61.1. It exists in git master and will be in 7.62.0 as the first release...

thanks, so i have to download the git master

**Comment by bagder** [comment]
git master or a daily snapshot, yes
