### ISSUE TITLE
NTLM fails

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#3041]
When authenticating against mail server using NTLM from a Mac, it seems to fail always.

I 'd expect it to work.
curl-7.61.1

Mac OS 10.13.6.

**Comment by MonkeybreadSoftware** [comment]
Sample output like this:

Mac:
* OK The Microsoft Exchange IMAP4 service is ready.
A001 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
A001 OK CAPABILITY completed.
A002 AUTHENTICATE NTLM
+
TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=
+ 
<Base64 codierte Daten>
<Base64 codierte Daten>
A002 OK AUTHENTICATE completed.
…

Win:
* OK The Microsoft Exchange IMAP4 service is ready.
A001 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
A001 OK CAPABILITY completed.
A002 AUTHENTICATE NTLM
+
TlRMTVNTUAABAAAABoIAAAAAAAAAAAAAAAAAAAAAAAA=
A002 NO AUTHENTICATE failed.
Closing connection 0
TLSv1.0 (OUT), TLS alert, Client hello (1):

**Comment by bagder** [comment]
Is this a regression? Did it work in previous versions?

**Comment by MonkeybreadSoftware** [comment]
A client has trouble sending emails via CURL, SMTP and NTLM authorization. MacOS works and Windows not.


MacOS:

* OK The Microsoft Exchange IMAP4 service is ready.
A001 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
A001 OK CAPABILITY completed.
A002 AUTHENTICATE NTLM
+
TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=
+ 
...
A002 OK AUTHENTICATE completed.
…




Windows:

* OK The Microsoft Exchange IMAP4 service is ready.
A001 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
A001 OK CAPABILITY completed.
A002 AUTHENTICATE NTLM
+
TlRMTVNTUAABAAAABoIAAAAAAAAAAAAAAAAAAAAAAAA=
A002 NO AUTHENTICATE failed.
Closing connection 0
TLSv1.0 (OUT), TLS alert, Client hello (1):



4E544C4D53535000010000000682080000000000000000000000000000000000
4E544C4D53535000010000000682000000000000000000000000000000000000
.............................^

There is an 8 or not.

4E544C4D53535000 -> header
010000000 -> version
682000000 -> flags
000000000000000000000000000000

So this is NTLM2FLAG, set to NTLMFLAG_NEGOTIATE_NTLM2_KEY

#if defined(USE_NTRESPONSES) && defined(USE_NTLM2SESSION)
#define NTLM2FLAG NTLMFLAG_NEGOTIATE_NTLM2_KEY
#else
#define NTLM2FLAG 0
#endif


So why is this set on MacOS and not Windows?

Does someone know details?

**Comment by MonkeybreadSoftware** [comment]
Adding

#define USE_NTLM2SESSION

to curl_ntlm_core.h around line 45 seems to work.

USE_WIN32_CRYPTO is defined and it's okay on Windows for us to either use OpenSSL or crypto functions.

**Comment by MonkeybreadSoftware** [comment]
Client reports it works now.
So May I recommend to tune the USE_NTLM2SESSION define there to be activated, even if USE_WIN32_CRYPTO is defined?

**Comment by bagder** [comment]
If you say it works and there's no obvious downside, then I don't see why not! Will you provide pull-request for this so that we can make sure the CI also likes it?

(This preprocessor conditional was brought in 97e90d7b89 by @captain-caveman2k in 2014.)

**Comment by MonkeybreadSoftware** [comment]
Pull request made:
enable USE_NTLM2SESSION always #3703

**Comment by bagder** [comment]
Fixed with #3704
