### ISSUE TITLE
Is on the fly compression option available with curl sftp command?

### ISSUE THREAD

**Issue by AbhijitKundu123** [curl/curl#3047]
### I did this
Using below curl sftp command to transmit a file. If file size is huge e.g. 45 MB, getting timeout error:
curl -k -u user_id:password -B -T <source_filename> sftp://<remote_host>/<target_direcotry> -m 300

when --compressed option added, it is taking same time. But, we were expecting to take less time in compressed mode.
curl -k -u user_id:password --compressed -B -T <source_filename> sftp://<remote_host>/<target_direcotry> -m 300

### I expected the following
On the fly compression option should be available with curl sftp command and file transmit time should be less in compressed mode.

### curl/libcurl version
[curl -V output]
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

### operating system
Linux

**Comment by bagder** [comment]
1. curl 7.19.7 is **very** old. Approaching 9 years now.
2. it didn't support SSH based compression, `--compressed-ssh` wasn't added until 7.56.0
3. it is still a negotiation so it could still end up not being compressed
4. depending on the nature of the content, maybe it wouldn't compress much anyway...
