### ISSUE TITLE
Procedure entry point SSL_CTX_set_ciphersuites not found in libcurl-4.dll

### ISSUE THREAD

**Issue by Ede123** [curl/curl#3061]
Unfortunately this issue only occurs in a very specific and rather arcane scenario, so debugging might not be easy, but maybe it's enough to get to the bottom of this.

I'm using MSYS2/mingw-w64 together with AppVeyor CI to continuously build Inkscape.

The latest update of the curl library introduced a crash when attempting to run the compiled Inkscape executable (which is linked against poppler, which is linked against curl which is linked against openssl):
![error_ci](https://user-images.githubusercontent.com/904570/46231430-2c2f9400-c36c-11e8-91d5-25f89a4b31b0.png)

While I'm consistently seeing this on the virtual machine of the CI, locally I was not able to reproduce the issue (the MSYS2 environment *should* be identical).  
What differs might be environment variables and the OS (the CI machine runs on 
Microsoft Windows Server 2012 R2 Datacenter, my local machine uses Windows 10).

### curl/libcurl version

curl 7.61.1 (x86_64-w64-mingw32) libcurl/7.61.1 OpenSSL/1.1.1 (WinSSL) zlib/1.2.11 brotli/1.0.6 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli TLS-SRP HTTP2 HTTPS-proxy MultiSSL PSL Metalink

### operating system

Microsoft Windows Server 2012 R2 Datacenter

**Comment by bagder** [comment]
[SSL_CTX_set_ciphersuites](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_ciphersuites.html) was added in OpenSSL 1.1.1 so libcurl will use that function if built with 1.1.1 or later, and not if built with an earlier version.

If you get this error, it suggests your libcurl finds/uses an older OpenSSL that lacks this function.

**Comment by Ede123** [comment]
Cause is in fact an older version of OpenSSL that is installed into C:\Windows\system32 on AppVeyor build servers.

It wasn't apparent from output of ldd-like tools that the wrong library was loaded, so I didn't catch it earlier.

Unfortunately Windows looks for DLLs in the order "executable dir -> system directories -> working directory -> PATH", so there's usually no easy way to avoid applications from loading incompatible DLLs except for copying them all into the executable's install location.
