### ISSUE TITLE
URl-API broke test 1146 [--proto-default file]

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#3070]
### I did this
./runtests.pl -p -v 1146
resulting in
```
=== Start of file stderr1146
curl: (1) Protocol "c" not supported or disabled in libcurl
=== End of file stderr1146
```
which was fixed when test 1146 was created in https://github.com/curl/curl/commit/1d4202ade602dd4f1192c69aed5cc905e7a9b4e2#diff-8fb104c402dc51bdffef05a372f32aa2R4290.

### I expected the following
Test passing, like it did with commit 17ca0ccff4aeacc63bf7fa90314ea58d23464617 before the URL-API reintegrate.

### curl/libcurl version
```
curl 7.62.0-DEV (i686-w64-mingw32) libcurl/7.62.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.0.5 nghttp2/1.32.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy
```

### operating system
Windows 10

**Comment by MarcelRaad** [comment]
See also for example https://curl.haxx.se/dev/log.cgi?id=20180927042156-4042#prob6.

**Comment by bagder** [comment]
This is a windows-specific failure, 1146 works on linux and did green on travis before merge... :disappointed:

**Comment by MarcelRaad** [comment]
Yes :-( According to https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin, the AppVeyor images have MSYS2, Cygwin, and even classic MinGW with MSYS 1.0 installed. Maybe we can somehow get it to run the tests. Or just add another build running the tests.

**Comment by MarcelRaad** [comment]
Yes, I'll experiment in my own fork. Invoking them on Windows works just like on Linux: open an MSYS or Cygwin shell and run runtests.pl. And probably use `-c` if built with Visual Studio, though I haven't tried yet.
