### ISSUE TITLE
Avoid crashes due to openssl engines conflicts using OPENSSL_config instead of CONF_modules_load_file()

### ISSUE THREAD

**Issue by pmgdeb** [curl/curl#3072]
We have observed that the call to CONF_modules_load_file() introduced in 
https://github.com/curl/curl/commit/7d2f61f66ab4e047fc9aefc2effc1ac6d340a66a to work with a broken openssl config files breaks zypper calls to libcurl in SLES 15.

The problem is caused by an openssl engine conflict. Basically zypper calls to libcurl, which on init also reads openssl.cnf.

Trying to load the ibmca engine a second time causes an engine conflict, which results in the engine being destroyed i.e., its data structures freed. When zypper uses crypto operations calling the engine _after_ returning from libcurl, garbage pointers are being dereferenced, leading to the observed SIGSEV/SIGILLs.

See the attached backtrace.txt file.

The problem with libcurls openssl init (Curl_ossl_init) is that it calls to CONF_modules_load_file _directly_, which has no thread-locking/run-once mechanisms in place, causing the described problem.

[backtrace.txt](https://github.com/curl/curl/files/2434816/backtrace.txt)

**Comment by pmgdeb** [comment]
Attached an example patch for libcurl that fixes the problem.
[ibmca.txt](https://github.com/curl/curl/files/2434836/ibmca.txt)

**Comment by jay** [comment]
What is your `curl_version()`? libcurl calls `CONF_modules_load_file` in the same order as OpenSSL 1.0.2.

https://github.com/openssl/openssl/blob/OpenSSL_1_0_2p/crypto/conf/conf_sap.c#L79-L94

> Attached an example patch for libcurl that fixes the problem.

Calling OPENSSL_config may fix it for you but break it for someone else. However I don't see where in OpenSSL source code that exit() is called and the bug is [too old](http://rt.openssl.org/Ticket/Display.html?id=3488&user=guest&pass=guest) so I can't read what happened.

/cc @Jan-E

**Comment by bagder** [comment]
OPENSSL_config did call exit() back in the days. They fixed that bug in https://github.com/openssl/openssl/commit/abdd677125f3a9e3082f8c5692203590fdb9b860 (January 2015)

**Comment by bagder** [comment]
> The problem with libcurls openssl init (Curl_ossl_init) is that it calls to CONF_modules_load_file directly, which has no thread-locking/run-once mechanisms in place, causing the described problem

Changing these function calls is not a fix for lack of thread-locking, it seems more like a happy coincidence that might or might not work depending on your particular OpenSSL versions! OpenSSL (before 1.1.0) requires mutex callbacks to be set to function in a multitreaded environment. And if you have them set, then surely it is OpenSSL's job to make sure those work?

**Comment by bagder** [comment]
The original curl bug and discussion is still around on sourceforge: https://sourceforge.net/p/curl/bugs/1401/ . You can also find the link to the issue I filed with OpenSSL about it, but that doesn't seem to be available anymore (and they didn't give me/us credit when they ultimately fixed this).

**Comment by pmgdeb** [comment]
Thanks for your quick answer! We are using curl version 7.60.0 and this happened when updating OpenSSL from 1.1.0g version to 1.1.0h. OPENSSL_config is marked as deprecated in OpenSSL 1.1.0, we'll try to fix it using CONF_modules_load_file(). You can close the bug as already fixed. Thanks!

**Comment by bagder** [comment]
Cool, thanks for getting back with this.
