### ISSUE TITLE
option 'ciphers ' does not handle several valid ciphers.

### ISSUE THREAD

**Issue by Ricky-Tigg** [curl/curl#3077]
### I did this:
I specified two **valid** ciphers (ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-GCM-SHA384) according to undocumented **syntax** in Curl manual, with purpose to get the last one selected in the connection. Option is used **once**.

_curl(1)_ – sample
>  --ciphers [list of ciphers]
> (TLS) Specifies which ciphers to use (...) https://curl.haxx.se/docs/ssl-ciphers.html
> If this option is used several times, the last one will be used.
 
```
$ curl --ciphers ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 -OL https://getfedora.org/static/checksums/Fedora-Server-29_Beta-1.5-x86_64-CHECKSUM
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256 (...)
```
### I expected the following
a valid output as in:
```
$ curl --ciphers ECDHE-RSA-AES256-GCM-SHA384 -OL https://getfedora.org/static/checksums/Fedora-Server-29_Beta-1.5-x86_64-CHECKSUM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1213  100  1213    0     0   1589      0 --:--:-- --:--:-- --:--:--  1587
```

### curl/libcurl version
```
curl 7.59.0 (x86_64-redhat-linux-gnu) libcurl/7.59.0 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh/0.8.3/openssl/zlib nghttp2/1.32.1
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink
```

### operating system
```
$ cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
```

**Comment by bagder** [comment]
I believe the cipher names should be separated by colon (when OpenSSL is used).

In your first use case shown above, you separate them with space without quotes, which makes curl treat the second cipher name as a URL.

**Comment by Ricky-Tigg** [comment]
Yet locating each ciphers between ' ' ' or ' " ' while keeping spaces lead to the same result.

**Comment by jay** [comment]
You'll have to use a colon to separate OpenSSL ciphers, @bagder has fixed the doc to clarify this.
`--ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384`
sends these in the ClientHello:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

In the doc it says if this option is used several times the last one will be used and that means for example
`--ciphers ECDHE-RSA-AES128-GCM-SHA256 --ciphers ECDHE-RSA-AES256-GCM-SHA384`
sent in ClientHello:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by Ricky-Tigg** [comment]
I realise that I did not interpret the post illustrated by the link https://github.com/curl/curl/commit/835a2fe694214341b601b2439082a30a24cc9da9 as a comment. In that context I kept searching an unofficial way to make the function perform as desired. One pertinent result I got at last: when specifying **multiple** cipher names under a **same** ciphers option (_--ciphers_), separating them with comma (`,`) was validated by _curl_ function.

Since there is **two approaches** involving the use of **multiple ciphers within a same** _curl_ **function**, and **one** was documented –the one involving multiple '--ciphers' options–, then approach involving  **multiple** cipher names specified under a **same** ciphers option (_--ciphers_) does obviously remain **unknown**.

In that last approach, illustrated here by the command `curl --ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384`, does the **order** according to which ciphers are **arranged** matter?  What does this means both from a **user** and **server** perceptive?

**Comment by bagder** [comment]
> separating them with comma (,) was validated by curl function

curl just accepts whatever string you tell it, and it will pass it on to the TLS library. You can separate them in however way you want and curl won't complain. As long as they're passed as a single string.

> Since there is two approaches involving the use of multiple ciphers within a same curl function

I don't think there is.

> one involving multiple '--ciphers' options

That just makes the second use override the previous one, that's not really multiple ciphers.

> does the order according to which ciphers are arranged matter?

The OpenSSL document says the string is an "ordered SSL cipher preference list", which makes me suspect that the order is the preference.

**Comment by jay** [comment]
> The OpenSSL document says the string is an "ordered SSL cipher preference list", which makes me suspect that the order is the preference.

Wireshark dumps confirm this.

**Comment by Ricky-Tigg** [comment]
Time will come also for me to use_Wireshark_, since needed addition of a _dnscrypt_ dissector is to come. You had right intuition regarding SSL ciphers preference order. Yet what could be the **use-case** that would justify the last option to override the previous ones regarding a command involving **multiple** `ciphers` **options**? I could not seasonably conceive any appropriate use-case by myself.

**Comment by jay** [comment]
scripting, make your last setting for an option override any previous one. like for example if you set a $CURL variable to use some common options like curl --ciphers foo and then in your script you have $CURL --ciphers bar, or in your curlrc you have --ciphers foo and on the command line you use --ciphers bar in either case bar overrides foo.

If you're using Wireshark you can use [SSLKEYLOGFILE](https://ec.haxx.se/tls-sslkeylogfile.html) environment variable which curl 7.56.0+ w/OpenSSL 1.0.2+ supports and then you see the decrypted transfer.

**Comment by jay** [comment]
That ClientHello does not look as it should if you are using curl with OpenSSL. Turn on verbose mode `-v` and check that the cipher selection is set:
~~~
* Cipher selection: ECDHE-RSA-AES256-GCM-SHA384
~~~
If you don't see that line it's possible you are using curl with an SSL backend that doesn't support cipher selection or requires a different format.

Different issue:

> Probably Curl will support TLS 1.3 cipher suites too when that version becomes to be widely used by servers.

You can set [TLS 1.3 ciphers](https://github.com/curl/curl/blob/master/docs/CIPHERS.md#tls-13-cipher-suites) by using option [--tls13-ciphers](https://curl.haxx.se/docs/manpage.html#--tls13-ciphers) since 7.61.0. I will clarify this in the CIPHERS doc.

**Comment by Ricky-Tigg** [comment]
Using `curl --ciphers ECDHE-RSA-AES256-GCM-SHA384 -OLX POST (...)`,  I got now server to pick up the set cipher:
```
(...)
* Cipher selection: ECDHE-RSA-AES256-GCM-SHA384
(...)
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
(...)
* Using HTTP2, server supports multi-use
(...)
> POST /static/checksums/Fedora-Server-29_Beta-1.5-x86_64-CHECKSUM HTTP/2
> Host: getfedora.org
> User-Agent: curl/7.61.1
(...)
```
Might it be a way to get a list of cipher suites supported by server using the _v_ option in curl command ? For instance regarding a cipher suite using _Chacha_ –**0x1303**– which is supported by client curl and supported by OpenSSL, using TLS13-CHACHA20-POLY1305-SHA256 in curl command.
