### ISSUE TITLE
"--trace" do change a request method to POST

### ISSUE THREAD

**Issue by nefedov-da** [curl/curl#3089]
### I did this
curl -s -v --trace --request GET -d "qwerty" https://google.com
curl -s -v --trace --request PUT -d "qwerty" https://google.com

A request is changed to POST if -d and --trace presents.

### I expected the following
GET / HTTP/1.1
PUT / HTTP/1.1

but get:
POST / HTTP/1.1

### curl/libcurl version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

### operating system
Linux 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
This isn't a bug. --trace takes a file as an argument, which in this case ends
up being --request, which eats that option.  But note that --request is seldom
the right option to use.  Look at --get and --upload-file for example.

**Comment by jzakrzewski** [comment]
This may be because `--trace` requires an argument (file name), so it probably eats the `--request` option.
BTW: `--trace` and `-v` do not belong together.

**Comment by bagder** [comment]
As mentioned, a user error.

Also, since 7.61.1, curl will warn if you specify a file name to `--trace` that starts with a dash which could've helped to discover the error here.
