### ISSUE TITLE
CURLOPT_SSL_VERIFYHOST changed in openssl 1.1.1

### ISSUE THREAD

**Issue by jeroen** [curl/curl#3095]
My bindings have a unit test to test `CURLOPT_SSL_VERIFYHOST` by receiving `https://172.217.17.132/` which is the ip address of google.com. After Debian updated libcurl 1.1.0 to 1.1.1 this test started failing. 

```r
> curl::curl_fetch_memory('https://172.217.17.132', new_handle(ssl_verifyhost = 0))
Error: SSL certificate problem: self signed certificate
```

Something has changed in openssl 1.1.1 causing `CURLOPT_SSL_VERIFYHOST` no longer to be sufficient to retrieve a page if the domain on the cert does not match the domain.

I confirmed that I can fix the problem by adding `CURLOPT_SSL_VERIFYPEER = 0`  so there is an easy fix but I want to make sure there is not a bigger problem somewhere.

Downstream issue: https://github.com/jeroen/curl/issues/164

@mattcaswell @kroeckx @levitte

**Comment by bagder** [comment]
I can reproduce this. It works with OpenSSL 1.0.2 but fails with 1.1.1.

I don't think this is a curl bug though, since the exact same code works with the older OpenSSL versions. To me this looks like an OpenSSL issue.

Also, it fails even before `servercert` is called, which is the function that normally verifies the hostname against the SANs in the cert. `SSL_connect()`  in the ossl_connect_step2 function fails really fast. It is almost like they added a name check of their own... ?

**Comment by mattcaswell** [comment]
Read the SNI section on this page:

https://wiki.openssl.org/index.php/TLS1.3#Server_Name_Indication

Note in particular the bit about "Some sites want to encourage the use of SNI and configure a default certificate that fails WebPKI authentication when the client supports TLS 1.3". Google is on of those sites, i.e. they detect that you are using TLSv1.3 (as is the default case with 1.1.1), and then behave differently wrt SNI.

That's my guess as to what is happening anyway. If so then the answer is to make sure you send SNI.

**Comment by bagder** [comment]
Thanks @mattcaswell. Sounds like a very reasonable explanation.

@jeroen can you elaborate on what you want to accomplish with this "fun" operation? Why connect without a proper name to a google server? I mean, we can certainly go further and try to confirm @mattcaswell's theory but I'm mostly seeing a very weird use case not going through and I'm not understanding what the upside is in spending time on this...

**Comment by jeroen** [comment]
It's not important for me, it is merely a unit test which suddenly started failing. Sometimes users want to use `CURLOPT_SSL_VERIFYHOST = 0` so we have a unit test for that :) If you think the change in behavior is harmless and expected then I'll remote this unit test, and we can close this issue.

**Comment by bagder** [comment]
You could still do a test for `CURLOPT_SSL_VERIFYHOST = 0` if you want to, but with using a name in the URL so that it will use SNI. Or perhaps consider using a server you control yourself that doesn't behave this way...

**Comment by jeroen** [comment]
Right, many solutions. Just wanted to make sure there was no deeper underlying problem with openssl 1.1.0 -> 1.1.1 update.
