### ISSUE TITLE
test 2100 - DoH from command line - is flaky on travis

### ISSUE THREAD

**Issue by bagder** [curl/curl#3107]
See [this build](https://travis-ci.org/curl/curl/builds/437809638?utm_source=github_status&utm_medium=notification) as an example set where two of the Travis-CI builds fail test 2100 (event-based).

The tests *usually* build fine if we retrigger the tests. 

I have not managed to trigger this test failure in my own development environments!

### curl/libcurl version

current git master, and DoH support has not been in a release yet

### operating system

~~Linux~~ macOS, at least

### Test fail log.

I copied the details from the first of the build failures linked to above and it can be view here: [fail-2100.txt](https://github.com/curl/curl/files/2452983/fail-2100.txt)

### Theory

Looking  at the log, it might be a case where the two DoH requests are sent over the wire in reversed order...

**Comment by MarcelRaad** [comment]
Have you actually seen this on Linux? The four or five failures I've looked at were all on Mac OS.

**Comment by bagder** [comment]
Oh, you're right... but fortunately I don't think that particular detail matters much!
