### ISSUE TITLE
cmake build doesn't support 'make show' in tests

### ISSUE THREAD

**Issue by bagder** [curl/curl#3109]
### I did this

See the Windows tests run by appveyor. Build to enable tests, then run all tests.

The `tests/runtests.pl` script invokes `make show` in the tests/data directory to figure out which test cases that the makefile knows about. With a cmake build, I think this fails so runtests.pl then (wrongly) thinks the makefile knows of *no* test files which will lead to the following issue.

[example](https://ci.appveyor.com/project/curlorg/curl/builds/19314139/job/tvq3of02h58bl28e#L5974)

### I expected the following

The normal output **without** lines like this:

`[00:11:42] Warning: test904 not present in tests/data/Makefile.inc`

This warning appears when the script runs a test that it hasn't seen in the makefile with `make show`, as mentioned above.

### curl/libcurl version

current git master

### operating system

I presume this happens on all systems when built with cmake.

**Comment by bagder** [comment]
It seems we don't support running tests with at all with cmake builds so there's a lot more than just that warning that's left to fix... The appveyor cmake build that run tests is a bit of a work-around.

**Comment by MarcelRaad** [comment]
Oh, I thought that was the only thing. What else have you found?

**Comment by bagder** [comment]
Aaah. When I build with cmake there's no way to invoke the builds against my current build. Researching further, this is because I always build with cmake out-of-tree...

An autotool build makes 'make check' work even for out-of-tree builds. With a cmake build I need to build in-tree to be able to `cd tests && ./runtests.pl`.

**Comment by MarcelRaad** [comment]
Ah, I didn't know this was possible with the autotools build. I'll read up on that subject, but probably my autotools and CMake knowledge is too low yet.

**Comment by snikulov** [comment]
@bagder I've tried to implement some [changes](https://github.com/snikulov/curl/commit/7ebd4482fc66a64fe00c66c297ee8c9fa6319f1c) to be able to run tests with CMake build. It was related to changing runtests.pl to use BINDIR environment variable.

**Comment by snikulov** [comment]
@bagder I've rebased my branch to latest master so if you'll try to execute
`bindir=<path to cmake build dir> ./runtests.pl` in tests directory - it should work

**Comment by jzakrzewski** [comment]
I've tried to make those tests working but figured that changes to runtest.pl would be required. Not knowing even enough perl to be dangerous, I've abandoned the idea.
I must check you patch when I have some time.

**Comment by KangLin** [comment]
> 
> 
> @bagder I've tried to implement some [changes](https://github.com/snikulov/curl/commit/7ebd4482fc66a64fe00c66c297ee8c9fa6319f1c) to be able to run tests with CMake build. It was related to changing runtests.pl to use BINDIR environment variable.

It is recommended to pass the command line parameters at the same time.
