### ISSUE TITLE
curl error: out of memory (27)

### ISSUE THREAD

**Issue by BlueSky5300** [curl/curl#3117]
### I did this
Run curl command using java Runtime.exec(command)

Java Version: 1.8.0_172 64-Bit Server VM, mixed mode

### I expected the following
no error and download file from server.
### curl/libcurl version
7.61.1
[curl -V output]

### operating system
Windows 7

**Comment by bagder** [comment]
You're running the command line tool from java and it outputs/returns what? Can you show us a full command line and output, preferably with `-v` (for verbose) used?

And what happens if you run the same command line from a regular "windows shell" prompt?

**Comment by BlueSky5300** [comment]
If use command line from a regular "windows shell", that's fine and no errors.
But when I use java runtime exec, the outputs is empty. Just get an error log with curl: out of memory (27)

**Comment by bagder** [comment]
As you can imagine, curl actually works the same no matter how or from where you invoke it - it is after all the same binary executable. When it fails with an out of memory error immediately, without even saying anything like you say, I can't but to presume that the environment you start it in is inadequate for running curl in. Can you start other programs from there? If you *only* invoke `curl -V` from that java code, does that work?

**Comment by bagder** [comment]
> Maybe once curl request resource on the internet when running using java runtime, it will be out of memory.

This is not a problem with java runtime in general, this is a problem with your java runtime in particular (it working for you on mac is also an indication of this) so it's not easy for us to say why you get this problem. curl is invoked from java programs by lots of people every day without these problems.

**Comment by bagder** [comment]
I don't see how this can be a curl issue.
