### ISSUE TITLE
CMake: unusable tool_hugehelp.c with MinGW

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#3125]
### I did this

`cmake -G "MSYS Makefiles" [...] && cmake --build .`

I got a compile error because my tool_hugehelp.c contains:

```
C:/MinGW/msys/1.0/* built-in manual is disabled, blank function */
```

### I expected the following

Successful compilation and no [POSIX path conversion](http://www.mingw.org/wiki/Posix_path_conversion), like with the autotools build.

CMake version:
https://github.com/curl/curl/blob/69328490fc91bfa00a6a90da84239524b01f5527/src/CMakeLists.txt#L30
Automake version:
https://github.com/curl/curl/blob/b801b453af6de75838c3298137628f05e94ffb48/src/Makefile.am#L128

### curl/libcurl version

git master https://github.com/curl/curl/commit/12dde22b4c64e6f8ece65aa9e22addf345d4d32c

### operating system

Windows 10

**Comment by bagder** [comment]
It seems to require perl and nroff:

https://github.com/curl/curl/blob/master/CMakeLists.txt#L211-L213

I don't think hugehelp generation actually needs nroff though...

**Comment by MarcelRaad** [comment]
Ah, you're right! When using the autotools build, I do have a tool_hugehelp.c without this comment, still without nroff.

**Comment by bagder** [comment]
No, I was wrong! `src/Makefile.am` uses nroff to build the huge help output. It runs the equivalent of:

     nroff -man curl.1 | perl mkhelp.pl docs/MANUAL >> huge.c

... after curl.1 has been generated of course.

**Comment by MarcelRaad** [comment]
Right, I do have `groff` in `$PATH`, only the CMake build won't use it...

**Comment by KangLin** [comment]
Reference: https://github.com/KangLin/RabbitThirdLibrary
Build script:
https://github.com/KangLin/RabbitThirdLibrary/blob/master/build_script/build_libcurl.sh
