### ISSUE TITLE
POP3 USER/PASS without CURL_DISABLE_CRYPTO_AUTH 

### ISSUE THREAD

**Issue by ericmjones** [curl/curl#3127]
### I did this
Using libcurl: it is impossible to log in to a POP3 server which only supports USER/PASS comand and does not have SASL or APOP.

### I expected the following
[https://github.com/curl/curl/blob/master/lib/pop3.c#L528](pop3.c:528) Instead of requiring CURL_DISABLE_CRYPTO_AUTH to be defined to support USER/PASS, this code.should have an optional fall-through to support both APOP and USER/PASS method in the same build config.

### curl/libcurl version
7.61.1
[curl -V output]

### operating system
W7/10

**Comment by bagder** [comment]
> this code.should have an optional fall-through to support both APOP and USER/PASS method in the same build config.

I don't understand. Why wouldn't the same config support both if you build with crypto auths enabled? Can you provide a patch/PR to show what you suggest we should do?

**Comment by bagder** [comment]
No response after 4 weeks. Closing.
