### ISSUE TITLE
HTTP2 framing layer error with particular file

### ISSUE THREAD

**Issue by jmccl** [curl/curl#3130]
I'm opening this per the suggestion of @bagder in #2976 . This is happening on Manjaro, but doesn't seem to happen anywhere else. 

I found this as a consequence of trying to upgrade Visual Studio Code on Manjaro. (Doing so via pacman now doesn't result in this error, I assume because the version of Visual Studio Code has been upgraded so a different file is curled.) However, raw curl (below) still fails.

> $ curl -V
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

> $ curl https://az764295.vo.msecnd.net/stable/431ef9da3cf88a7e164f9d33bf62695e07c6c2a9/code-stable-1538751479.tar.gz
curl: (16) Error in the HTTP2 framing layer

> $ ldd /usr/bin/curl
	linux-vdso.so.1 (0x00007fff7cd59000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f7d2e25a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f7d2e239000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f7d2e075000)
	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007f7d2e04d000)
	libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f7d2de30000)
	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f7d2dc02000)
	libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007f7d2d9f0000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f7d2d960000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f7d2d68e000)
	libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f7d2d440000)
	libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f7d2d157000)
	libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f7d2cf24000)
	libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f7d2cf1c000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f7d2cd05000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f7d2e346000)
	libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f7d2c985000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f7d2c980000)
	libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f7d2c773000)
	libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f7d2c76b000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f7d2c752000)

**Comment by bagder** [comment]
I checked out 7.61.1, rebuilt and tried. I can't reproduce either (using OpenSSL 1.1.1) and this is my `-V` output:

~~~
curl 7.61.1-DEV (x86_64-pc-linux-gnu) libcurl/7.61.1-DEV (GnuTLS/3.5.19) OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.6 c-ares/1.14.0 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.1_DEV nghttp2/1.33.0-DEV librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy MultiSSL PSL Metalink

**Comment by mtompkins** [comment]
I see this on Arch, with the referenced VSCode link:
https://vscode-update.azurewebsites.net/1.28.1/linux-x64/stable

```
curl -V
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by jmccl** [comment]
[3130pcap.zip](https://github.com/curl/curl/files/2474817/3130pcap.zip)

Files attached.

It seems to be some kind of timing issue. If I'm not running tcpdump, it happens 100% of the time. If I'm running tcpdump, it happens about 25% of the time; the other 75% it does the http2 upgrade and downloads the file.

**Comment by indecisivemal** [comment]
I have the same issue on arch with https://pbs.twimg.com/ and some other twitter domains (though twitter.com itself is fine).
It doesn't seem to be path-dependent for either twitter's or the msecnd link above.
Interestingly, my firefox (62.0.3) seems to also have trouble with those domains, "An error occurred during a connection to az764295.vo.msecnd.net."

**Comment by indecisivemal** [comment]
... I think just as I posted that they changed something, as after reliably failing for over a day, pbs.twimg.com works in both firefox and curl.
One obvious change is that the server stopped offering TLS 1.3

**Comment by bagder** [comment]
(Regarding timing, I could just add that in my case I successfully downloaded the 61.5 MB file in 585 milliseconds, thus pretty much saturated my 1gbit/sec connection...)

**Comment by jmccl** [comment]
I'm on 20Mb up, 2Mb down, fwiw.

**Comment by jay** [comment]
Slight correction, I forgot about [CURLOPT_ERRORBUFFER](https://curl.haxx.se/libcurl/c/CURLOPT_ERRORBUFFER.html) which if set the buffer will receive the more detailed error. However in this case we can assume no detailed error is received since curl sets that buffer and then prefers it over generic errors:

https://github.com/curl/curl/blob/432eb5f5c254ee8383b2522ce597c9219877923e/src/tool_operate.c#L1803-L1808

**Comment by jmccl** [comment]
I was about to put a bug in on Visual Studio Code, but it's not reproducing anymore for me. My best guess is they fixed some config on their distribution servers. I'm going to close this as I don't see that there's any more to be done. 

Thanks for looking at it.
