### ISSUE TITLE
Unable decode Brotli

### ISSUE THREAD

**Issue by LArctic** [curl/curl#3136]
I don't have a programming foundation, just call libcurl.dll using a scripting language.

I use curl to download bing search,
Specify the "CURLOPT_ACCEPT_ENCODING" parameter as: "br"
Use "easy" mode, return error code: "23"

And if the "CURLOPT_ACCEPT_ENCODING" parameter is specified as: "gzip", everything works fine.

My problem is: that curl has built support for "Brotli" since version 7.57.0. Why does it return an error when decoding Brotil data? Need additional tools?

libcurl.dll 32 7.61.1
win 10 64
Script language: autohotkey

**Comment by bagder** [comment]
We need many more details to be able to help out. Like for example how to reproduce this problem and how you built your libcurl and which versions/features it was built to provide. We could start with a `curl -V` output from your build!

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Comment by LArctic** [comment]
Sorry, please forgive me for forgetting this question.
I won't compile the DLL, I downloaded the DLL from "curl.haxx.se".
I only use "libculr.dll" and I don't use curl.exe.
Except that it can't decode Brotli, it works fine.

https://curl.haxx.se/download.html

Windows 32 bit 	7.61.1 	binary 	Stefan Kanthak

curl-7.61.1.cab\I386\LIBCURL.DLL

**Comment by LArctic** [comment]
Is it not an official version? It is the only version I found that can be loaded normally.
So where can I find a version that supports BR? (Compiling with MSVC, LoadLibrary can't load mingw compiled DLL)

**Comment by bagder** [comment]
There is no "official" libcurl build for Windows. We recommend you build it yourself from source.

**Comment by LArctic** [comment]
Thank you. It seems that I need to learn some basic knowledge of C++.

**Comment by bagder** [comment]
You don't need to know C++ just to build libcurl - it's already written! You just need to follow the instructions...

**Comment by LArctic** [comment]
I installed Cygwin, but I have no idea how to compile curl.dll.
Is there a BAT script that can compile it quickly?

**Comment by nickzman** [comment]
You don't even need Cygwin to build it; just follow the instructions in winbuild/BUILD.WINDOWS.txt if you have Visual Studio installed.
