### ISSUE TITLE
curl-config assumes that bc is present

### ISSUE THREAD

**Issue by dimpase** [curl/curl#3143]
`bc` might not be installed on the box (typical for VMs, e.g. if you use a default Debian install on a Google Compute node). Then `curl-config --checkfor` reports nonsense.
```
$ curl-config --checkfor 7.22
/usr/bin/curl-config: 1: /usr/bin/curl-config: bc: not found
/usr/bin/curl-config: 1: /usr/bin/curl-config: bc: not found
/usr/bin/curl-config: 112: test: Illegal number:
requested version 7.22 is newer than existing 7.52.1
```

not sure what the right fix is. 

A platform-specific fix for Debian would add `bc` to pre-reqs for libcurl, but well, perhaps it can be improved generically.

**Comment by dimpase** [comment]
One does not need any external tools here. Indeed, the [1st line](https://github.com/curl/curl/blob/df54b14fb77bc7f62f31971ed8bb26ec24bf27d5/curl-config.in#L110) using `bc` can be written as
```
checknum="$(($cmajor*256*256 + $cminor*256 + ${cpatch:-0}))"
```
Similarly if you don't use `@VERSIONNUM@`, but parse `@CURLVERSION@` in the same way as you parse the input and get `checknum`, you can get `nownum` from the shell.

If'd care to take a pull request fixing this, I can do it...

**Comment by bagder** [comment]
> If you'd care to take a pull request fixing this, I can do it.

Yes please. Just make sure you're also not doing any bash'isms as I believe `$()` is? And I don't think a plain shell evaluates math expressions like that...

**Comment by infinnovation** [comment]
Using only Bourne sh, expr and sed:
```sh
        checknum=`expr $cmajor \* 256 \* 256 + $cminor \* 256 + ${cpatch:-0}`
        numdigits=`echo @VERSIONNUM@ | sed -e 'y/abcdef/ABCDEF/; s/0x//; s/./ &/g; s/[ABCDEF]/1&/g; y/ABCDEF/012345/'`
        nownum=0
        for d in $numdigits; do nownum=`expr $nownum \* 16 + $d`; done

```

**Comment by dimpase** [comment]
`expr` is another external program. 

Anyway, I do not understand why one needs to do the arithmetic of this sort, as you can start by comparing major versions, if they are equal move to the minor ones, and finally, if needed, to the patch level... Yes it would be few lines longer, but much less cryptic.

**Comment by infinnovation** [comment]
expr is typically part of a coreutils package and available on any sensible distro.  But I think you're right about unnecessary arithmetic.  Just unpick @CURLVERSION@ in the same way as $checkfor, rather than unhexifying @VERSIONNUM@.

**Comment by dimpase** [comment]
Would testing with FreeBSDs `/bin/sh` suffice, or you recommend some other "bad" shell to test with?

**Comment by bagder** [comment]
Yes, I think that would be a good test. Or 'dash' on a Linux system.

**Comment by bagder** [comment]
The challenge is to make a conversion from or a comparison with a hexadecimal number without using a separate tool. I don't think that's possible. Then the question is really which separate tool that is most likely to be around and thus least troublesome to depend on... Contenders include `bc` and `printf`. I don't think `expr` alone can do it?

**Comment by dimpase** [comment]
I don't understand why you insist on having to deal with that hexadecimal number --- as instead you can using the normal split version format right away.

**Comment by bagder** [comment]
Oh yes, you can indeed. I was just too stuck in the same mindset that code is currently written! The solution could be to simply use `@CURLVERSION@` instead of `@VERSIONNUM@`.

Alternatively, we remove all dependencies (even on sh) and go with #3154

**Comment by danielgustafsson** [comment]
We can indeed use `@CURLVERSION@`, but we still don't get away from requiring a shell which has POSIX `cut` and  `test` utils, and I don't think that's entirely representative of the platforms where curl builds. (granted, a tool like curl-config has perhaps the most use in a unix environment toolchain, but that's not to say that someone with a build from MSVC can't find it useful)

**Comment by dimpase** [comment]
Thanks!
