### ISSUE TITLE
MTLS certificate loading on Windows 10 is broken

### ISSUE THREAD

**Issue by JonathanHenson** [curl/curl#3145]
### I did this
Used the source code here:
https://github.com/curl/curl/blob/2e5651a5ce0ee18d610cacfaa2b3ec5073a40c34/lib/vtls/schannel.c#L390

as a reference to look at the api usage to load a system installed certificate.

### I expected the following
CertOpenStore to succeed. It does not, because the function expects a null terminated path for the system store. For example instead of "MY\<thumbprint>", it should just be "MY".

### Code I wrote that works:
char store_path[128] = { 0 };
    assert(location_of_next_segment - store_path_start < sizeof(store_path));
    memcpy(store_path, store_path_start, location_of_next_segment - store_path_start);

*cert_store = CertOpenStore(CERT_STORE_PROV_SYSTEM_A, 0, (HCRYPTPROV)NULL, 
        CERT_STORE_OPEN_EXISTING_FLAG | store_val, store_path);

### curl/libcurl version
HEAD of the repo

### operating system
Windows 10

**Comment by bagder** [comment]
Thanks! Can you perhaps make a proper pull-request with your suggested fix?
