### ISSUE TITLE
flickcurl (http://librdf.org/flickcurl/) hangs when uploading big images with 7.61.1

### ISSUE THREAD

**Issue by jacmet** [curl/curl#3151]
After updating to 7.61.1 I noticed that flickcurl hangs when uploading big images. I am using the openssl backend and openssl 1.0.2p. flickcurl does a multipart form post to https://up.flickr.com.
It starts nicely sending blocks of ~16KB data but then gets stuck in a poll loop:
`write(3, "\27\3\3@\30\3\211\345\316\202\24\354\16\264\21\206I$\210\357\236\21\3508\373\255\265\251\204\243\237\241"..., 16413) = 16413 poll([{fd=3, events=POLLIN}], 1, 110) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) poll(NULL, 0, 1000) = 0 (Timeout) poll([{fd=3, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout) poll([{fd=3, events=POLLIN}], 1, 1000) = 0 (Timeout) `

7.61.0 works. Bisecting 7.61.0..1 ends up with:
`
8c80a9d1e26be192d30a075e2c7397f8f12498c6 is the first bad commit
commit 8c80a9d1e26be192d30a075e2c7397f8f12498c6
Author: Daniel Stenberg <daniel@haxx.se>
Date:   Fri Aug 17 11:36:12 2018 +0200

    upload: change default UPLOAD_BUFSIZE to 64KB

    To make uploads significantly faster in some circumstances.

    Part 2 of #2888
    Closes #2892
`

I don't know if there is something wrong on the flickcurl side (but from a quick look it seemed sane), the flickr servers or in the openssl backend. I was NOT able to reproduce it by a simple HTTP post to localhost.

**Comment by jacmet** [comment]
The bisect script was simply: https://gist.github.com/jacmet/935dfc1f8f1183ddf129334a13f4b827

**Comment by bagder** [comment]
Have you tried the lastest git master version just to see if it is still there? (I would presume so) It would be interesting if changing `CURLOPT_UPLOAD_BUFFERSIZE` (this option was added after the 7.61.1 release) to 16K actually fixes the problem or if it remains anyway.

If you redirect the upload to a https server of your own, can you reproduce the issue then?

**Comment by bagder** [comment]
This is really tricky to work on without a way to reproduce.

**Comment by bagder** [comment]
Any more data or info on this? Does it behave the same with 7.64.1?

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
