### ISSUE TITLE
connection cache uses incorrect port

### ISSUE THREAD

**Issue by meastman** [curl/curl#3157]
### I did this

- Created a multi handle that had `CURLMOPT_PIPELINING` = `CURLPIPE_MULTIPLEX` set
- Modified `hashkey` in `lib/conncache.c` to print various inputs and its result
- Created 3 easy handles (each described below) that each had the following set:
  - `CURLOPT_HTTP_VERSION` = `CURL_HTTP_VERSION_2_0`
  - `CURLOPT_VERBOSE` = `1L`

#### First request

Created a request for `http://127.0.0.1:8080/` (server1, which supports HTTP/2)

```
hashkey:
  host.name = 127.0.0.1
  port = 80
  remote_port = 8080
  result = 80127.0.0.1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
Host: 127.0.0.1:8080
Accept: */*
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA

< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: h2c
* Received 101
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=15
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< content-type: text/plain; charset=utf-8
< content-length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

#### Second request

Created a request for `http://127.0.0.1:28080/` (server2, which only supports HTTP/1.1)

```
hashkey:
  host.name = 127.0.0.1
  port = 80
  remote_port = 28080
  result = 80127.0.0.1
* Found bundle for host 127.0.0.1: 0x221af90 [can multiplex]
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 28080 (#1)
> GET / HTTP/1.1
Host: 127.0.0.1:28080
Accept: */*
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA

< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #1 to host 127.0.0.1 left intact
```

#### Third request

Created a request for `http://127.0.0.1:8080/` (server1, which supports HTTP/2)

```
hashkey:
  host.name = 127.0.0.1
  port = 80
  remote_port = 8080
  result = 80127.0.0.1
* Found bundle for host 127.0.0.1: 0x221af90 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Using Stream ID: 3 (easy handle 0x222dc20)
> GET /api/node/1 HTTP/2
Host: 127.0.0.1:8080
Accept: */*

< HTTP/2 200 
< content-type: text/plain; charset=utf-8
< content-length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

### I expected the following

The first connection to port 8080 should have been reused for the third request. Instead, the connection to port 28080 was found in the connection cache and was ignored.

If the 2nd request is not made, everything works correctly. Also, if one of the hostnames is changed from 127.0.0.1 to localhost, everything works correctly as well.

### curl/libcurl version

```
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: http https 
Features: AsynchDNS IPv6 Largefile SSL HTTP2 UnixSockets HTTPS-proxy 
```

### operating system

```
$ uname -a
Linux cw-pc-88 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

**Comment by bagder** [comment]
How do you determine this? The verbose output from your report contradicts your conclusions so I'm quite confused now.

    * Found bundle for host 127.0.0.1: 0x221af90 [can pipeline]
    * Could pipeline, but not asked to!
    * Re-using existing connection! (#0) with host 127.0.0.1

This says it reuses `#0`, which was the first connection, not the second.

    * Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)

It says port 8080.

    * Using Stream ID: 3 (easy handle 0x222dc20)
    > GET /api/node/1 HTTP/2

It issues a HTTP/2 request and gets a HTTP/2 response, and is you said the second request used a HTTP/1 server without HTTP/2 support this really was the first connection being reused.

What am I missing?

**Comment by meastman** [comment]
> How do you determine this? The verbose output from your report contradicts your conclusions so I'm quite confused now.
> What am I missing?

You're right - after tweaking the example and re-running this several times to get simpler output, I ended up with a case that doesn't exactly match my initial issue I encountered. I will try to reproduce that again and update the information.

However, in the example above, the following messages are somewhere between confusing and wrong:
```
(request 2)
* Found bundle for host 127.0.0.1: 0x221af90 [can multiplex]
(request 3)
* Found bundle for host 127.0.0.1: 0x221af90 [can pipeline]
* Could pipeline, but not asked to!
```

**Comment by bagder** [comment]
> I will try to reproduce that again and update the information.

If you end up with an example that reproduces, that would be golden too to attach here!

> somewhere between confusing and wrong

Yeah, they're certainly confusing. I don't think we need to work hard on cleaning them up at this point though, as we recently (commit f7208df7d9d5) deprecated pipelining support completely (to be removed in ~6 months) and when that happens I'm sure we'll have reasons to go through and update messaging like that.
