### ISSUE TITLE
`curl_slist_append` uses a suboptimal algorithm

### ISSUE THREAD

**Issue by gzxu** [curl/curl#3164]
Disclaimer: This issue might be too academical

As shown in https://github.com/curl/curl/blob/curl-7_61_1/lib/slist.c#L77, the `Curl_slist_append_nodup` routine, which is called by `curl_slist_append`, finds the last one in the linked list before appending a new item. Therefore the time complexity of constructing a `struct curl_slist` is `O(n^2)`. This could be optimized to `O(n)` by adding extra information of the last node in `struct curl_slist`.

Thank you very much!

**Comment by bagder** [comment]
That's an entirely correct observation. But since `struct curl_slist` is a publicly defined struct we can't modify that and still remain ABI compatible...

**Comment by bagder** [comment]
I don't see that there's anything we can do about this.

**Comment by dfandrich** [comment]
It could be added to the Next major release section in the TODO for when we
next break backward compatibility.
