### ISSUE TITLE
SOCKS5 layer expects replies to have a minimum length of 10; actual minimum length appears to be 7

### ISSUE THREAD

**Issue by i336** [curl/curl#3165]
### I did this

I happen to need to do some dynamic network-fiddling for a specific program, and determined the best solution would be to write a tiny SOCKS proxy. This turned out to be much much more straightforward than I anticipated (<10-page RFCs FTW!) and I expect it to be successful.

I used `curl` to debug and test my implementation, and became very confused when careful (re)reading of RFC 1928 resulted in a `curl` that was stubbornly hung at the connection acknowledgement stage - until sending precisely three bytes of junk padding (which were eaten) mysteriously made everything work perfectly, even for **https**://example.com/.

O.o

---

For reference, the explanation table from https://tools.ietf.org/html/rfc1928 as listed in socks.c:

https://github.com/curl/curl/blob/6ae6b2a533e8630afbb21f570305bd4ceece6348/lib/socks.c#L705-L711

For my MVP "learn how the protocol works" implementation, I decided to see if I could get away with using an `ATYP` of 3 (DOMAINNAME) and then specifying said domain name as being of zero length.

I knew `curl` would never be acting upon the information anyway (in the context of using the commandline program for testing), and odd things like specifications of zero length fields coming in over a network protocol should never produce memory or logic issues, so I figured I was good to go. (Particularly considering SOCKS5 doesn't define a zero-length domain name to be invalid. Hmm.)

In this specific scenario, counting the lengths (not the values) of the parts, it's possible for

VER (1) + REP (1) + RSV (1) + ATYP (1) + BND.ADDR (1) + BND.PORT (2) = 7.

(BND.ADDR's minimum length is 1 - the size specifier here denoting the string as length 0.)

---

### I expected the following

[Here's my MVP server code.](https://github.com/curl/curl/files/2510419/socks5server.php.txt)

When run in a terminal it simply just re-makes all requested connections itself. Chromium seems to work with it just fine (via `--proxy-server=socks5://127.0.0.1:1080`, and perhaps also `--user-data-dir=blah`).

This is enough encouragement for me to think my determination that the true minimum length can legally be 7.

As of current repo state, the glitch is on line 680.

https://github.com/curl/curl/blob/6ae6b2a533e8630afbb21f570305bd4ceece6348/lib/socks.c#L680

I am admittedly a bit curious to find out what may have influenced the minimum of `10`, if this information is known. (Root cause analysis is always a nice-to-have.) A quick read of the SOCKS4 portion of the proxy code (particularly line 261) doesn't seem like it influenced the SOCKS5 part.

### curl/libcurl version

```
curl 7.61.1 (x86_64-pc-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system

Arch Linux

### thanks

Thanks for curl! It "just handles" more things than I realize need handling. :)

<sub><sub>Edit: ...forgot to actually attach the script</sub></sub>

**Comment by i336** [comment]
While mentally reviewing a few things I just realized I forgot a small tidbit I meant to include when I submitted this last night.

In case the attached server implementation is used for testing, line 83 is meant to be un/commented to demonstrate adding/not adding the 3 bytes of padding. I see I forgot to prefix a decimal point to the string - when uncommenting the `//"xxx"` it should look like `."xxx"`.

Thanks again.

**Comment by bagder** [comment]
Thanks for your report! I can only assume that socks type 3 with that short domain name is very rare as nobody has fell over this before.

> I am admittedly a bit curious to find out what may have influenced the minimum of 10,

I can't remember, but looking at the code it seems like just a way to filter out possible junk input and simplify the code.

Are you willing to work on a PR to fix this?

**Comment by bagder** [comment]
Can you clarify how exactly I can reproduce a bug here? I can't seem to find any way to trigger a problem.

**Comment by hlindqvist** [comment]
I think that the assumption that a SOCKS5 *CONNECT reply* has a minimum size of 10 octets appears to be valid.

In the description of the CONNECT reply in the spec, it does not sound like ATYP can actually be X'03' (DOMAINNAME) in this type of message.

From [rfc1928 section 6 "Replies"](https://tools.ietf.org/html/rfc1928#section-6) (emphasis added):

> CONNECT
> 
>    **In the reply to a CONNECT**, BND.PORT contains the port number that the
>    server assigned to connect to the target host, while **BND.ADDR
>    contains the associated IP address**.  The supplied BND.ADDR is often
>    different from the IP address that the client uses to reach the SOCKS
>    server, since such servers are often multi-homed.  It is expected
>    that the SOCKS server will use DST.ADDR and DST.PORT, and the
>    client-side source address and port in evaluating the CONNECT
>    request.


Now, of course, maybe this should be caught and handled somehow, but I don't think that the custom SOCKS5 server implementation used in the repro is actually sending a valid reply.

**Comment by bagder** [comment]
Thanks, based on this discussion I can't see a bug that we can verify and I will close this issue. If we get more details or figure out how to reproduce a problem we can always reopen or create a new issue in the future.
