### ISSUE TITLE
Slow Client Hello when using libcurl with openssl

### ISSUE THREAD

**Issue by pps83** [curl/curl#3167]
### I did this

curl https://www.roblox.com/testfarm/empty.ashx

### I expected the following

Client Hello should happen within 50ms from starting ssl connection, while when using openssl version of curl I get occasionally 400ms delay (attached screenshot has 150ms extra). If I use winssl then I never see that delayed Client Hello.

Originally I experienced this problem when using libcurl 7.61.1, but then I saw that same problem happens when I use curl executable that I have ("curl 7.59.0 (x86_64-w64-mingw32) libcurl/7.59.0 OpenSSL/1.0.2h (WinSSL) zlib/1.2.8 WinIDN libssh2/1.7.0_DEV"). If I use WinSSL version libcurl or curl build with WinSSL then I never see that `Client Hello` delay.
If use current curl binary ("curl 7.61.1 (x86_64-pc-win32) libcurl/7.61.1 OpenSSL/1.1.1 (WinSSL) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.8.0 nghttp2/1.34.0") then I don't see that delay. 

When I use libcurl in my code I use it with "OpenSSL 1.0.2o  27 Mar 2018" and get that `Client Hello` delay like 80% of the time.
Any ideas what could be wrong? Seems the issue is somehow related to openssl?..

![image](https://user-images.githubusercontent.com/1614246/47472021-dced4f80-d7c1-11e8-98ec-3953369e97f0.png)

### curl/libcurl version

[curl -V output]

7.61.1

### operating system

Win 10 pro

**Comment by bagder** [comment]
Curious. I've never seen this on Linux and I tried this URL just now with current git using OpenSSL 1.0.2 vs 1.1.1 and I can't see any difference between them and no delays.

**Comment by pps83** [comment]
When I tried that on mac I don't see any delays either. Only get that on Windows

**Comment by pps83** [comment]
What's interesting is that curl binary consistently does around 150ms delay for `Client Hello`, while my own libcurl build consistently does 400ms delay.

curl 7.59.0 (x86_64-w64-mingw32) libcurl/7.59.0 OpenSSL/1.0.2h (WinSSL) zlib/1.2.8 WinIDN libssh2/1.7.0_DEV:
![image](https://user-images.githubusercontent.com/1614246/47518180-0f895d80-d83f-11e8-8e87-e6a05bedaecf.png)

libcurl 7.61.1 + OpenSSL 1.0.2o 27 Mar 2018:
![image](https://user-images.githubusercontent.com/1614246/47518227-33e53a00-d83f-11e8-8959-c7fea8ecc207.png)

If I start three parallel requests (using libcurl):

![image](https://user-images.githubusercontent.com/1614246/47518994-54ae8f00-d841-11e8-90b7-bff14a3134e4.png)


Also, if ssl connection terminates and I make another connection to this host (from the same process) then second connection doesn't have that `Client Hello` delay even if connection is made from another port:
![image](https://user-images.githubusercontent.com/1614246/47519073-89224b00-d841-11e8-8ecc-8a47c0ff0856.png)

**Comment by pps83** [comment]
If I start three requests using WinSSL I don't have any delays:

![image](https://user-images.githubusercontent.com/1614246/47519252-00f07580-d842-11e8-8d6d-da889f21dc0f.png)

By the way, can I build libcurl with both winssl and openssl at the same time and then select either one based on some runtime setting?

**Comment by pps83** [comment]
I tried to figure out what's going on and I suspect that OpenSSL does "something" on first time use that takes this much time. In my test code I simply query that my test url every 5 seconds. If I simply query https://google.com first and 5 seconds later my test url, then I never see that delay when accessing my test url.

I also tried to use `OpenSSL 1.1.0h` and I do not see delayed `Client Hello`.

**Comment by bagder** [comment]
if you run with `--trace-time` or otherwise debug curl, can you figure out where in the code/flow this pause occurs? Is it curl waiting for something or is it an OpenSSL call or something?

**Comment by pps83** [comment]
Unrelated but somewhat similar weird timing observed with libcurl. I time requests myself (from the moment I added them to curlmuti, to the moment when I handle result), and some requests consistently take way more time than what CURLINFO_TOTAL_TIME reports. For example, a request that I'm looking into always takes around 400ms according to my measurements, but lib curl reports CURLINFO_TOTAL_TIME of just 46ms.

I'm 99.9% sure that curl multi simply does not return me the result for that long time. The code that runs curl multi is approximately like this:
        {
        sleep(1ms);
        while (CURLMsg* msg = curl_multi_info_read(curlMulti, &msgsInQueue))
            if (msg->msg == CURLMSG_DONE)
                handleResult(msg);
        }

I added logs just to make sure that handlaResult for some request doesn't take too much time and delays other requests and according to my logging I run the loop code around 100 time per second, and at worst the delay was 5ms max. So, somehow curl_multi_info_read delays results for some requests by more than 300ms in my case. Any ideas what could be wrong, or what i should try to check?

**Comment by zeux** [comment]
Any chance this is because of RAND_poll? Earlier versions of OpenSSL used very very very expensive code on Windows that made a snapshot of process tree, traversed application heap and did some other things that could easily take hundreds of milliseconds depending on the environment to generate entropy. I think this was fixed in a later version of OpenSSL to just use Win32 Crypto API: https://github.com/openssl/openssl/pull/1079

**Comment by pps83** [comment]
I took that openssl commit and can confirm that was the source of the problem. That code was a real mess

**Comment by bagder** [comment]
Good call there @zeux !

@pps83, can we consider this case closed then?
