### ISSUE TITLE
Transfer-Encoding: chunked,use libcurl how to get each chunk data & its length

### ISSUE THREAD

**Issue by DaisyMoney** [curl/curl#3169]
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
