### ISSUE TITLE
Failed writing body on Windows

### ISSUE THREAD

**Issue by bagder** [curl/curl#3175]
For this command  `curl https://www.vg.no`, I'm *always* getting a 

`Failed writing body (16366 != 16384)`. The sizes can differ.
Options `-N`, `-B` does not help. Writing to a file is no problem.

_Originally posted by @gvanem in https://github.com/curl/curl/pull/3161#issuecomment-432221558_

**Comment by bagder** [comment]
@bitcrazed; I presume you don't see this?

@gvanem: what compiler/build did you use when you get this?

**Comment by gvanem** [comment]
> what compiler/build did you use when you get this?

MSVC-2017 (both libcurl.dll and static). I also tried with MinGW (gcc 5.1). It also happens there. 
But more with something like:
```
Failed writing body (1399 != 1400)
```
smaller chunks and differences. But it depends on URL.

Maybe other Windows users can test a command like:
```
curl -vL https://www.vg.no
```

**Comment by bitcrazed** [comment]
@bagder Not seen this before. Will take a look this weekend.

**Comment by bitcrazed** [comment]
@bagder - Just confirmed that I don't see the error you describe above in the curl shipped in-box in the Win10 1809 build, though I do see the following appended to the end of `curl -vL https://www.vg.no`:

`* Connection #0 to host www.vg.no left intact`:

![image](https://user-images.githubusercontent.com/961950/47887427-89e84d80-ddfc-11e8-9719-a88f84ce85a8.png)

**Comment by gvanem** [comment]
>  Connection #0 to host www.vg.no left intact:

It's irrelevant AFAICS. I fixed it by either:

* disable the call to `configure_terminal()`.
* merging https://github.com/curl/curl/pull/3212.

The problem is also gone either way. So I'll assume it's the fault of current `configure_terminal()`.

*BTW*, how does this call know if *VT output* has any effect. It seems to *ass-u-me* CMD is used. I use 4NT as my shell.

**Comment by bitcrazed** [comment]
@gvanem Looks like the `Connection #0 to host www.vg.no left intact:` message is related to forcing the codepage to 65001. @mattn's approach in #3212 is a better & more complete solution that also removes the forced switch to 65001.

Currently, the only way to know whether the call to `SetConsoleMode(…ENABLE_VIRTUAL_TERMINAL_PROCESSING)` actually works is to subsequently call `GetConsoleMode(…)` and test if the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode flag is still set. In versions of Windows 10 < 1809, the flag can be set but will be ignored and won't 'stick'.

**Comment by gvanem** [comment]
I still get the `curl: (23) Failed writing body (0 != 3942)` with `curl -o NUL ..`.

**Comment by gvanem** [comment]
I don't follow all the `OutStruct` members, but testing for:
```c
  if (!outs->s_isreg && !outs->fopened) {
```
instead is maybe better?

**Comment by binkley** [comment]
What I observe on the curl shipped with _Git for Windows_:
```
$ curl -X POST -NsS http://localhost:8080/actuator/shutdown >/dev/null
curl: (23) Failed writing body (0 != 35)
```
I've tried several variations (`-o /dev/null`), etc.  Perhaps this is a problem with msys/mingw?
Version:
```
$ uname -a
MINGW64_NT-10.0 BREE 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
```

**Comment by gvanem** [comment]
@binkley 
You mean from this: https://git-scm.com/download/win.
The Portable version there has a curl version of 7.63.0 which exhibit that same  `Failed writing body` error.

**Comment by opav** [comment]
Version **7.64.0** still failing with same Failed writing body error.

Only way to get curl working for me is to fallback to a version **7.61.0** from https://dl.uxnr.de/build/curl/curl_winssl_msys2_mingw32_stc/curl-7.61.0/curl-7.61.0.zip

Hopefully curl authors can fix it in next version.

**Comment by opav** [comment]
Version **7.64.0** still failing with same Failed writing body error with command `curl -o NUL`, same for 7.63 and 7.62.

Only way to get curl working for me is to fallback to a version **7.61.0** from https://dl.uxnr.de/build/curl/curl_winssl_msys2_mingw32_stc/curl-7.61.0/curl-7.61.0.zip

Hopefully curl authors can fix it in next version.

**Comment by jay** [comment]
> Version **7.64.0** still failing with same Failed writing body error

Yes you are right I forgot this wasn't fully solved. Try this:

~~~diff
diff --git a/src/tool_cb_wrt.c b/src/tool_cb_wrt.c
index 195d6e7..1944f16 100644
--- a/src/tool_cb_wrt.c
+++ b/src/tool_cb_wrt.c
@@ -79,6 +79,9 @@ size_t tool_write_cb(char *buffer, size_t sz, size_t nmemb, void *userdata)
   struct OperationConfig *config = outs->config;
   size_t bytes = sz * nmemb;
   bool is_tty = config->global->isatty;
+#ifdef WIN32
+  CONSOLE_SCREEN_BUFFER_INFO console_info;
+#endif
 
   /*
    * Once that libcurl has called back tool_write_cb() the returned value
@@ -156,7 +159,9 @@ size_t tool_write_cb(char *buffer, size_t sz, size_t nmemb, void *userdata)
   }
 
 #ifdef _WIN32
-  if(isatty(fileno(outs->stream))) {
+  if(isatty(fileno(outs->stream)) &&
+     GetConsoleScreenBufferInfo(
+       (HANDLE)_get_osfhandle(fileno(outs->stream)), &console_info)) {
     DWORD in_len = (DWORD)(sz * nmemb);
     wchar_t* wc_buf;
     DWORD wc_len;
~~~

I think we should probably use is_tty which is just config->global->isatty but it looks like that's dependent on the progress meter logic. Anyway that may be a better way to tackle it
https://github.com/curl/curl/blob/f3294d9d86e6a7915a967efff2842089b8b0d071/src/tool_operate.c#L747-L757

**Comment by bagder** [comment]
funny that I added that label exactly while you were writing your comment =)

> I think we should probably use is_tty which is just config->global->isatty but it looks like that's dependent on the progress meter logic

It doesn't have to be though.

**Comment by jay** [comment]
With consideration of the next release I used my original patch rather than rewrite global->isatty logic. If the same console check is needed elsewhere we can revisit it.
