### ISSUE TITLE
Content-Encoding: gzip not decoded by default

### ISSUE THREAD

**Issue by staktrace** [curl/curl#3192]
### I did this

curl --location -D headers https://index.taskcluster.net/v1/task/gecko.v2.try.revision.82e2aa09bb6ef19b6309f156a813b408d8783a23.firefox.win64-searchfox-debug/artifacts/public/build/target.json > foo

### I expected the following

The `foo` output file to be JSON. But actually it was gzip'd JSON. The `headers` file shows that the server is sending the content with `Content-Encoding: gzip` so I would expect `curl` to unzip it for me. I don't know if that expectation is realistic or not. Running the same command with `--compressed` produces the desired behaviour. However I think that shouldn't be necessary because (a) the documentation around `--compressed` implies it primarily controls to what `curl` requests rather than how it processes what it receives, and (b) decompressing the content-encoding seems like the more useful default behaviour.

### curl/libcurl version

curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

### operating system

macOS 10.13.6

**Comment by bagder** [comment]
This is by design, although we can of course discuss changing defaults if done carefully and with consideration. The best thing to do that would be to bring the suggestion to the curl-users mailing list and help out with a transition that might be done over an extended period of time.

**Comment by staktrace** [comment]
Is there a writeup somewhere of why the current default is the way it is? (Or arguments in favour of this default)? I'd just like to understand the rationale for it before I make a more formal proposal to change it on a mailing list.

**Comment by bagder** [comment]
It matches everything else curl does. It does the basic request by default, everything else is opt-in or enable-feature. Before curl got the `--compressed` option (back when dinosaurs wandered on earth) `curl $URL` would download the gzipped content, and we maintained that behavior when that option was subsequently added (or when it isn't built). It is as simple as that. And then we've maintained this behavior over the years.

I should add that I don't think anyone has actually ever worked on or suggested changing this default so it has just remained as-is.

I wonder if we can figure out/find any existing users who would be upset or whose scripts would break if we change this...

**Comment by staktrace** [comment]
For posterity, the email thread is here: https://curl.haxx.se/mail/archive-2018-10/0025.html

**Comment by bagder** [comment]
Since this isn't a bug, this issue is now closed. The discussion if this should be done by default basically ended (stalled?) with the voiced risk that this will break scripts for some amount of users who expect the compressed version to get downloaded when the option is not used.
