### ISSUE TITLE
Missing upkeep API for multi/share handles

### ISSUE THREAD

**Issue by mkauf** [curl/curl#3199]
### I did this

I found the new upkeep API in the latest curl version: [curl_easy_upkeep()](https://curl.haxx.se/libcurl/c/curl_easy_upkeep.html)

### I expected the following

A corresponding multi API to keep up connections that are managed by a multi handle (curl_multi_upkeep).

Or maybe curl_multi_perform() already does these "upkeep" tasks? (even if all transfers have completed...?)

Probably also a corresponding share API is needed (curl_share_upkeep) because the connection cache can be shared.

### curl/libcurl version

7.62.0

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
