### ISSUE TITLE
--resolve erroring but --connect-to works fine with same argument

### ISSUE THREAD

**Issue by jshort** [curl/curl#3203]
### I did this
`--resolve 'example.com:443:127.0.0.1:6443'`

But got:

```
* Resolve address '127.0.0.1:6443' found illegal!
* Couldn't parse CURLOPT_RESOLVE entry 'example.com:443:127.0.0.1:6443'!
*   Trying <public IP example.com resolves to>..
```
However, if I pass the same argument string to `--connect-to`, it works fine.

### curl/libcurl version

curl 7.61.0 (x86_64-apple-darwin16.7.0) libcurl/7.61.0 OpenSSL/1.0.2p zlib/1.2.8
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

### operating system
MacOS Sierra

**Comment by bagder** [comment]
`--resolve` doesn't take the same arguments as `--connect-to`. As the man page explains, `--resolve` wants `<host:port:address[,address]...>`, while you seem to have tried to add more than one port number...
