### ISSUE TITLE
A command involving an URL whose domain name is calomel.org fails

### ISSUE THREAD

**Issue by Ricky-Tigg** [curl/curl#3205]
### I did this
For the **first time** in **active session**, run command '`curl --tls13-ciphers TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256 -vX POST https://calomel.org`/'. Alternatively command may be run **without** _tls13-ciphers_ option.

Command performs **successfully** and **completely** as expected. Since the previous attempt, following attempts to run that command produce only those strings:
```
$ curl -vX POST https://calomel.org/
*   Trying 100.16.251.204...
* TCP_NODELAY set
```
**Logout** then **login** have no effect on present issue.

### I expected the following
All attempts to be successful as it is the case when an URL whose domain name is _wireshark.org_ – which uses _TLS v. 1.3_ as well – is involved in that command.

### curl/libcurl version
```
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.5 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.3/openssl/zlib nghttp2/1.34.0
(...)
```

### operating system
_Fedora 29_

**Comment by bagder** [comment]
It seems the site stops answering after a `POST` (I could do several GETs first with no problem). This is not a curl problem. You can easily try with telnet or whatever and that won't connect anymore either. The server has stopped responding, not much for curl to do about that!

**Comment by Ricky-Tigg** [comment]
Probably. Testing on SSL labs service at www.ssllabs.com seems to confirm that:

"SSL Report: calomel.org (100.16.251.204)
Assessed on:  Mon, 05 Nov 2018 10:19:49 UTC

Assessment failed: Unable to connect to the server
(...)
SSL Report v1.32.6"
