### ISSUE TITLE
7.62.0 giving "HTTP/2 stream 0 was not closed cleanly" error (7.61.1 was ok)

### ISSUE THREAD

**Issue by dr0biwan** [curl/curl#3206]
### I did this
I'm using libcurl as a shared dll to do a lot of my download handling which also includes downloading podcast feeds (e.g. http://www.bbc.co.uk/programmes/p016tmt2/episodes/downloads.rss). Since updating to 7.62.0 (previously using 7.61.1) it is now giving me "HTTP/2 stream 0 was not closed cleanly: FLOW_CONTROL_ERROR (err 3)" when trying to access content from my website & when downloading podcasts feeds on HTTP/2 compatible connections.

### I expected the following
HTTP/1 connections are working ok & the urls / feeds I'm now having issues with are handled ok when disabling HTTP/2 support in the library by removing the USE_NGHTTP2 compile flag (though I'd prefer not to have to disable this).

### curl/libcurl version
The version info of the shared library dll is: libcurl/7.62.0 OpenSSL/1.1.1 zlib/1.2.11.zlib-ng brotli/1.0.7 & is running on Windows. The library is built as a shared dll using VS2008 32-bit & other than updating to 7.62.0 nothing was changed in supporting libraries I'm already using. I've not yet been able to try it out using a stand-alone build of curl.exe with comparable libraries but can try to do so if that's helpful.

### operating system
I've only been able to test it on Windows 10 x64 1803

Thanks

**Comment by bagder** [comment]
Can you give us a full URL to something that causes you this HTTP/2 error? Is that RSS URL giving you that error?

Also, what nghttp2 version are you using?

**Comment by dr0biwan** [comment]
Sorry, I posted the version info from the build with HTTP/2 disabled. It was being built using nghttp2/1.34
The RSS url posted is one of the urls I'm seeing the issue with after the update where it's failing to download it completely so I can't then parse the response out. A simpler one is https://getwacup.com/versions.json which I'm using for version updates & that gives the same error on trying to download it.

**Comment by jay** [comment]
bisected to becfe123 which enabled Windows VT Support. Does it go away if you write to a file?

May be related: `curl -H "Cache-Control: no-cache" https://nn.cbcb.us/register.php` as seen [here](https://curl.haxx.se/mail/archive-2018-10/0017.html).

/cc @bitcrazed

**Comment by jay** [comment]
Clarify: the error I see is because fwrite failed ("Failed writing body"), I cannot reproduce FLOW_CONTROL_ERROR.

~~~
curl 7.62.0-DEV (i386-pc-win32) libcurl/7.62.0-DEV OpenSSL/1.0.2p nghttp2/1.33.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug Largefile NTLM SSL HTTP2 HTTPS-proxy
~~~

**Comment by bagder** [comment]
I cannot reproduce this at all on Linux...

**Comment by dr0biwan** [comment]
I've been trying to look at things under the debugger & I'm getting the FLOW_CONTROL_ERROR arise in the update_remote_initial_window_size_func(..) method in nghttp2. Also it looks like that leads to the "stream 0" when it was internally running against stream 1 & that is reset to zero on clean-up in libcurl prior to the error message being generated (not sure if that's correct behaviour or not).

In addition, I've gone back over the 7.62.0 changelog & I've just tried setting CURLOPT_HTTP_VERSION=CURL_HTTP_VERSION_1_1 which now gets it working with HTTP/2 support enabled but that doesn't seem right to me & I've got to assume now that I wasn't even using the HTTP/2 support for the last 2 years.

Maybe this is all because I'm using the library version instead of the standalone exe & there's some other default values that have changed or some other parameter that I'm not using but I'm stumped.

Would it help if I provide a simple version of the code I'm using (e.g. for getting my versions.json file) ?

**Comment by jay** [comment]
> Would it help if I provide a simple version of the code I'm using (e.g. for getting my versions.json file) ?

Yes, please provide that. Can you reproduce using the curl tool?

**Comment by xm74** [comment]
Same issue with 7.61.1 and 7.62.0

```
# curl -V 'https://nexxt.social/photo/93e2bdf1c1a02fa49f095f526c3e8a991ef3471e4580afb380857933a997f154-1.png'
curl 7.61.1 (amd64-portbld-freebsd11.2) libcurl/7.61.1 OpenSSL/1.0.2o zlib/1.2.11 brotli/1.0.7 libidn2/2.0.5 nghttp2/1.34.0
Release-Date: 2018-09-05
# curl -IL -v 'https://nexxt.social/photo/93e2bdf1c1a02fa49f095f526c3e8a991ef3471e4580afb380857933a997f154-1.png'
*   Trying 85.13.135.61...
* TCP_NODELAY set
* Connected to nexxt.social (85.13.135.61) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=nexxt.social
*  start date: Oct 12 05:29:52 2018 GMT
*  expire date: Jan 10 05:29:52 2019 GMT
*  subjectAltName: host "nexxt.social" matched cert's "nexxt.social"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x8046a2000)
> HEAD /photo/93e2bdf1c1a02fa49f095f526c3e8a991ef3471e4580afb380857933a997f154-1.png HTTP/2
> Host: nexxt.social
> User-Agent: curl/7.61.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host nexxt.social left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

```

**Comment by bagder** [comment]
Thanks, I also get this error with this command line using git master. I'll dig deeper!

**Comment by bitcrazed** [comment]
Hey @bagder - could you please drop me a mail - I have a ton of noob questions: rich at bitcrazed dot com. 

TIA.

**Comment by bagder** [comment]
(trying to lump one issue together with a bunch of other randomly reported issues will not help)

This issue is most likely a problem with the nexxt.social server. Let me show you what wireshark catches when I invoked:

    SSLKEYLOGFILE=~/tmp/tlskey ./src/curl -IL -v 'https://nexxt.social/photo/93e2bdf1c1a02fa49f095f526c3e8a991ef3471e4580afb380857933a997f154-1.png

![screenshot-curl-nexxt social](https://user-images.githubusercontent.com/177011/48306708-c115d780-e53d-11e8-8197-1662c79a4f87.png)

See especially how the server sends back a `RST_STREAM` to curl (after it sent its initial `SETTINGS` frame) saying "protocol error". I suspect this is simply the server rejecting the HEAD request in a terrible way.

If I instead send a GET request with

    curl -L -v 'https://nexxt.social/photo/93e2bdf1c1a02fa49f095f526c3e8a991ef3471e4580afb380857933a997f154-1.png' -o /dev/null

It works perfectly fine.

You can work around this with `--http1.1`.

**Comment by bagder** [comment]
This is a broken server and not a curl problem.
