### ISSUE TITLE
7.62.0 breaks on redirects to unsupported protocol even if not followed

### ISSUE THREAD

**Issue by bradking** [curl/curl#3210]
### I did this

Build curl 7.62.0 from source with `--without-ssl` to disable https support.  Then try to GET a http URL that redirects to https via 301, e.g.:

```console
$ curl -v http://cmake.org
...
< HTTP/1.1 301 Moved Permanently
...
< Location: https://cmake.org/
...
* Closing connection 0
curl: (1) Unsupported protocol
```

It now fails because https is unsupported even though `-L` is not passed.

### I expected the following

```console
$ curl -v http://cmake.org
...
< HTTP/1.1 301 Moved Permanently
...
< Location: https://cmake.org/
...
* Connection #0 to host cmake.org left intact
```

### curl/libcurl version

7.62.0.  The failure bisects to commit 46e164069d1a5230e4e64cbd2ff46c46cce056bb from PR #3017.

**Comment by bagder** [comment]
Indeed - a side-effect of parsing the URL already in `Curl_follow()` and not allowing "unknown" URL schemes there...

**Comment by bradking** [comment]
Confirmed, thanks!
