### ISSUE TITLE
Windows VT Support and UTF-8 output doesn't restore font

### ISSUE THREAD

**Issue by bagder** [curl/curl#3211]
This is very ugly change. Changing console codepage effect console font. Also you probably notice that curl doesn't restore original font.

![shoei](https://user-images.githubusercontent.com/10111/47857303-a1d7c580-de2c-11e8-99e2-47211284bdc1.gif)

@bitcrazed This is NOT right way to show unicode. You should use wide string APIs.

_Originally posted by @mattn in https://github.com/curl/curl/issues/3008#issuecomment-435056354_

**Comment by bitcrazed** [comment]
Thanks for fixing @mattn

**Comment by bagder** [comment]
So, an innocent question from someone not usually on Windows: how annoying is this bug for a typical user? Would you say this is a reason enough to do a patch release or can we live with it for six weeks?

**Comment by bitcrazed** [comment]
My feel for this is that this is fundamentally a cosmetic issue (i.e. I don't _think_ it breaks functionality/behavior, right?), though to what degree is a good question for @Mattn.

**Comment by mattn** [comment]
IMO, This doesn't break functionality but curl harms to console. For example, if we use curl in Vim plugin, console is broken. I strongly wish getting this fix immediately.

![terminal6](https://user-images.githubusercontent.com/10111/47887159-4683f280-de81-11e8-9fbe-532a747240d4.gif)
