### ISSUE TITLE
7.62.0 Netrc Lookup Failure

### ISSUE THREAD

**Issue by alexcumbers** [curl/curl#3213]
There appears to be a bug with this change where netrc lookup now fails to select the correct entry, instead defaulting to the first user entry every time.  This was working in v7.61.1 and earlier.

Example netrc file:
machine ftp.gam.com login inet_web password INCORRECT
machine ftp.gam.com login fdxfer password ----
machine ftp.gam.com login impldn password -----
machine ftp.gam.com login pharo password ----
machine ftp.gam.com login pilling password ----

Version:
curl 7.62.0 (sparc-sun-solaris2.10) libcurl/7.62.0 OpenSSL/1.0.2p zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

The following examples running under Solaris 11 pick up the wrong netrc user entry:

**curl --verbose --netrc --user fdxfer: ftp://ftp.gam.com**
*   Trying 193.202.226.107...
* TCP_NODELAY set
* Failed to set TCP_KEEPALIVE on fd 4
* Connected to ftp.gam.com (193.202.226.107) port 21 (#0)
< 220 ftp.gam.com FTP server ready.
**> USER inet_web**
< 331 Password required for inet_web.
> PASS INCORRECT
< 530 Login incorrect.

**curl --verbose --netrc --user pilling: ftp://ftp.gam.com**
*   Trying 193.202.226.107...
* TCP_NODELAY set
* Failed to set TCP_KEEPALIVE on fd 4
* Connected to ftp.gam.com (193.202.226.107) port 21 (#0)
< 220 ftp.gam.com FTP server ready.
**> USER inet_web**
< 331 Password required for inet_web.
> PASS INCORRECT
< 530 Login incorrect.

_Originally posted by @alexcumbers in https://github.com/curl/curl/pull/3122/comment#issuecomment-435113881_

**Comment by bagder** [comment]
@mkauf, feel like taking a closer look at this?

**Comment by mkauf** [comment]
@bagder OK, will do.
@alexcumbers  thank you for reporting this issue.

**Comment by alexcumbers** [comment]
thanks - it might be useful to obscure the exposed password emitted after 331 output.

**Comment by mkauf** [comment]
This bug was caused by commit 46e1640 . Commit d48e6b7 is unrelated.

I have proposed a bugfix in #3224 .
