### ISSUE TITLE
IPv6 address in URL

### ISSUE THREAD

**Issue by tpaukrt** [curl/curl#3218]
### I did this

curl http://[fd00:a41::50]

### I did not expected the following

curl: (3) URL using bad/illegal format or missing URL

### curl/libcurl version

curl 7.62.0 (arm-unknown-linux-gnu) libcurl/7.62.0 OpenSSL/1.0.2o zlib/1.2.11
Release-Date: 2018-10-31
Protocols: ftp ftps http https
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy

**Comment by bagder** [comment]
Clearly a regression from the URL parser overhaul. I'm on it. A work-around that seems to avoid this bug is to add the port number:

    curl 'http://[fd00:a41::50]:80/'
