### ISSUE TITLE
unexpected bad/illegal url format error. A short host + port is treated as a scheme!

### ISSUE THREAD

**Issue by hagai-auro** [curl/curl#3220]
The scenario is that I have a hostname `boing` in `/etc/hosts` pointing to 127.0.0.1 , and I port-forward to the real host.
### I did this
``$ curl boing:80``
``curl: (3) URL using bad/illegal format or missing URL``

and if I did:
``$ curl http://boing:80``
it worked

### I expected the following 
I expected it to actually issue the request, but to illustrate the change from a previous version, if I hadn't defined `boing` in `/etc/hosts`, I'd get this:
``$ curl  boing:80``
``curl: (6) Could not resolve host: boing``

### curl/libcurl version
`$ curl -V`
``curl 7.62.0 (x86_64-apple-darwin16.7.0) libcurl/7.62.0 OpenSSL/1.0.2p zlib/1.2.8 libidn2/2.0.5
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy ``

### operating system
`` $ uname -a``
``Darwin hagai-mba-osx 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin``

**Comment by gvanem** [comment]
And curiously a `curl boing` will try to resolve `boing`.

**Comment by bagder** [comment]
Ack, a regression from  46e1640. PR coming up.

**Comment by bagder** [comment]
commit d9abebc7ee2 reverted the fix temporarily since it broke tests on windows. #3235 should ideally fix it "proper".
