### ISSUE TITLE
curl doesn't sending files in form

### ISSUE THREAD

**Issue by ashot11091950** [curl/curl#3228]
### I want to upload files to server and I was execute this: 

    curl -F 'send=@aa.mp3' 127.0.0.1/synchrone/synchrone.php -D -

### the server php code is:
    echo "GET: \n";
    foreach($_GET as $key => $value){
        echo $key." => ".$value;    
    }
    echo "POST: \n";
    foreach($_POST as $key => $value){
        echo $key." => ".$value;    
    }
    echo "FILES: \n";
    foreach($_FILES as $key => $value){
        echo $key." => ".$value;    
    }
    echo "REQUEST: \n";
    foreach($_REQUEST as $key => $value){
        echo $key." => ".$value;    
    }
### I got this: 

    HTTP/1.1 200 OK
    Host: 127.0.0.1
    Date: Sun, 04 Nov 2018 00:36:25 +0400
    Connection: close
    X-Powered-By: PHP/7.2.9-1
    Content-type: text/html; charset=UTF-8

    GET: 
    POST: 
    FILES: 
    REQUEST: 

### curl/libcurl version

[curl -V output]
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.1.0g zlib/1.2.8 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.8.0 nghttp2/1.27.0 librtmp/2.3
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
Kali GNU/Linux Rolling 2017.3R

**Comment by bagder** [comment]
If you add `--trace-ascii dump.log` you'll see a full log of what curl did in that file - and when I do with a command line like your I see a full file getting POSTed. I can't reproduce your problem.

**Comment by ashot11091950** [comment]
== Info:   Trying 127.0.0.1...
== Info: TCP_NODELAY set
== Info: Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
=> Send header, 231 bytes (0xe7)
0000: POST /synchrone/synchrone.php HTTP/1.1
0028: Host: 127.0.0.1
0039: User-Agent: curl/7.61.0
0052: Accept: */*
005f: Content-Length: 12140515
0079: Content-Type: multipart/form-data; boundary=--------------------
00b9: ----534e82f12118234a
00cf: Expect: 100-continue
00e5: 
== Info: Done waiting for 100-continue
=> Send data, 16384 bytes (0x4000)

there was data

<= Recv header, 17 bytes (0x11)
0000: HTTP/1.1 200 OK
<= Recv header, 17 bytes (0x11)
0000: Host: 127.0.0.1
<= Recv header, 39 bytes (0x27)
0000: Date: Tue, 06 Nov 2018 22:49:47 +0400
<= Recv header, 19 bytes (0x13)
0000: Connection: close
<= Recv header, 27 bytes (0x1b)
0000: X-Powered-By: PHP/7.2.9-1
<= Recv header, 40 bytes (0x28)
0000: Content-type: text/html; charset=UTF-8
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 31 bytes (0x1f)
0000: GET: .POST: .FILES: .REQUEST: .
== Info: Closing connection 0

**Comment by bagder** [comment]
> there was data

Right. So then is there really a curl problem here?

**Comment by ashot11091950** [comment]
but before updating curl it was work

**Comment by bagder** [comment]
So exctly what doesn't work now? You said it sends data... If you run both an old curl and a new and use `--trace-ascii`  on both and compare what they send, can you spot a difference?

**Comment by bagder** [comment]
A month later with no response and no obvious bug. Closing.
