### ISSUE TITLE
Support IDN by URL API

### ISSUE THREAD

**Issue by moteus** [curl/curl#3232]
I think it may be useful support punycode encoding for host names.
I think thre 2 separate task
1. Add falgs similar to CURLU_URLENCODE/CURLU_DECODE to HOST part
2. Decode IDN urls provided in unicode in punycode form.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
