### ISSUE TITLE
Non-blocking pipe as stdout doesn't work correcly

### ISSUE THREAD

**Issue by kunyavskiy** [curl/curl#3239]
### I did this

Create a pipe with 
`pipe2(pipe, O_CLOEXEC | O_NONBLOCK) `

In child redirect stdout to one end of pipe using dup2 and exec to curl (yes, I really need to use curl like this, not using libcurl). 

In parent read from pipe in event loop, maybe with some delays. 

### I expected the following

Read stdout of curl from pipe. But really, I got only part of stdout with 23 Failed writing body  error.

As I understand this happend because tool_write_cb doesn't respect EAGAIN error returned from fwrite (or by write inside it), when stdout is non-blocking file. So, it writes some part, got EAGAIN, because pipe buffer finished, and reported this as fatal error, instead of retrying.  

### curl/libcurl version

curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Debian stretch

### code sample to reproduce issue

```
#define _GNU_SOURCE
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>

int main() {
  int pipes[2];
  if (pipe2(pipes, O_CLOEXEC | O_NONBLOCK) < 0) {
    fprintf(stderr, "Failed to create pipes: %m\n");
    return 1;
  }

  int p = fork();
  if (p < 0) {
    fprintf(stderr, "Failed to fork: %m\n");
    return 1;  
  } else if (p == 0) {
    if (dup2(pipes[1], 1) < 0) {
      fprintf(stderr, "Failed to dup2: %m\n");
      return 1;      
    }
    // page size should be at least 64k
    execl("/usr/bin/curl", "curl", "https://github.com/curl", NULL);
    fprintf(stderr, "Failed to exec: %m\n");
    return 1;
  }

  while (1) {
    int status;
    if (waitpid(p, &status, WNOHANG) > 0) {
      fprintf(stderr, "son finished\n");
    }
    sleep(1); // without this sleep it reprodeces anyway, but more stable with it
    char buf[4096];
    errno = 0;
    int r = read(pipes[0], buf, sizeof(buf));
    if (r < 0) {
      break;
    }
    if (r == 0 && errno != EAGAIN) {
      break;
    }
    int w = 0;
    while (w < r) {
      w += write(1, buf + w, r - w);
    }
  }
}

```

**Comment by bagder** [comment]
> tool_write_cb doesn't respect EAGAIN error returned from fwrite when stdout is non-blocking file

I also don't think there's any such promise given...

**Comment by kdudka** [comment]
On Monday, November 5, 2018 11:36:44 PM CET Daniel Stenberg wrote:
> > tool_write_cb doesn't respect EAGAIN error returned from fwrite when
> > stdout is non-blocking file
> I also don't think there's any such promise given...

This is a common problem.  Many stdio-based programs will fail to write
their output if you give them a non-blocking file descriptor as stdout.
I was recently trying to make tee(1) work properly in this case but the
patch was not accepted by GNU coreutils upstream:

http://lists.gnu.org/archive/html/coreutils/2018-09/msg00010.html

Kamil

**Comment by bagder** [comment]
I don't think this is something we claim curl handles and as @kdudka says it is also a common restriction among other utilities. If someone wants to work on improving curl's behavior in this regard then I think we might accept a patch if it isn't too intrusive.

Closing this issue now.
