### ISSUE TITLE
windows, Address already in use problem

### ISSUE THREAD

**Issue by 2741248158** [curl/curl#3245]
### I did this
while (1)
{
curl_multi_add_handle(curl_handle, handle);
}
// keep sending http reqs
quickly the libcurl print logs: 

* connect to 192.168.2.210 port 22200 failed: Address already in use
* Failed to connect to 192.168.2.210 port 22200: Address already in use
* Closing connection 382
* Hostname 192.168.2.210 was found in DNS cache
*   Trying 192.168.2.210...
* TCP_NODELAY set

### I expected the following
how to avoid this, or have some good method to set the reuse option

### curl/libcurl version
current latest version

### operating system
win64

**Comment by bagder** [comment]
Thanks for your report!

Please provide a more complete way to reproduce or understand this issue. The details above are not enough! How about a full but minimal example source code?

**Comment by 2741248158** [comment]
my computer's max port limit not set, not a problem.
