### ISSUE TITLE
curl does not implement BoringSSL TLS renegotiation API

### ISSUE THREAD

**Issue by JeremR** [curl/curl#3258]
BoringSSL rejects peer renegotiations by default as explained in [PORTING.md#tls-renegotiation](https://github.com/google/boringssl/blob/master/PORTING.md#tls-renegotiation).

To support TLS renegotiation, needed when client auth is requested after initial handshake, curl need to call `SSL_set_renegotiate_mode` API which is specific to BoringSSL.

### I did this
Generate certificates (ca, server, client) for testing:
```
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.pem -batch -subj "/CN=fakeca"
openssl req -newkey rsa:2048 -nodes -keyout server.key -out server.req -batch -subj "/CN=localhost"
openssl x509 -req -in server.req -CA ca.pem -CAkey ca.key -CAcreateserial -out server.pem
openssl req -newkey rsa:2048 -nodes -keyout client.key -out client.req -batch -subj "/CN=fakeclient"
openssl x509 -req -in client.req -CA ca.pem -CAkey ca.key -CAcreateserial -out client.pem
```

Start openssl server in a terminal:
`openssl s_server -key server.key -cert server.pem -accept 44330 -CAfile ca.pem`

Connect with curl in another terminal:
`curl -v --cacert ca.pem --cert client.pem --key client.key https://localhost:44330`

curl successfully connect to server:
```
......
> GET / HTTP/1.1
> Host: localhost:44330
> User-Agent: curl/7.62.0-DEV
> Accept: */*
> 
* STATE: DO => DO_DONE handle 0x90af88; line 1696 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x90af88; line 1820 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x90af88; line 1835 (connection #0)
```

In openssl server terminal, type `R` to request renegotiation. curl fails as BoringSSL by default disable renegotiation as explained in doc, see error:
```
* TLSv1.2 (IN), TLS handshake, Hello request (0):
* TLSv1.2 (OUT), TLS alert, no renegotiation (612):
* BoringSSL SSL_read: error:100000b6:SSL routines:OPENSSL_internal:NO_RENEGOTIATION, errno 0
* Marked for [closure]: Transfer returned error
* multi_done
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (56) BoringSSL SSL_read: error:100000b6:SSL routines:OPENSSL_internal:NO_RENEGOTIATION, errno 0
```

### I expected the following
Curl with BoringSSL shall correctly handle TLS renegotiation request from server in order to authenticate client with client certificate.

### curl/libcurl version
Ubuntu 16.04 with latest curl and BoringSSL:
`curl 7.62.0-DEV (x86_64-pc-linux-gnu) libcurl/7.62.0-DEV BoringSSL zlib/1.2.8 librtmp/2.3`

Android Pie (9):
`curl 7.58.0 (Android) libcurl/7.58.0 BoringSSL zlib/1.2.11`

### operating system
I recompiled latest curl and BoringSSL in Ubuntu 16.04 but this can be reproduced in Android too.

**Comment by davidben** [comment]
Note renegotiation is an extremely dangerous protocol feature. It is disabled by default in BoringSSL for security reasons and was removed in TLS 1.3.

Enabling it is also non-compliant with HTTP/2 which requires it be disabled:
https://httpwg.org/specs/rfc7540.html#rfc.section.9.2.1

**Comment by bagder** [comment]
Oh right, I had somehow forgotten those details. Thanks @davidben for reminding me/us.

We should put the renegotation feature behind an option that's off by default. @JeremR, you up to looking into that?

**Comment by JeremR** [comment]
Hi, I understand that there are security issues related to TLS renegotiation, that's why it is disabled by default in BoringSSL. Still TLS renegotiation in BoringSSL is far less problematic as in OpenSSL due to limitation in its implementation as explained in [PORTING.md#tls-renegotiation](https://github.com/google/boringssl/blob/master/PORTING.md#tls-renegotiation) and [ssl.h#3462](https://boringssl.googlesource.com/boringssl/+/master/include/openssl/ssl.h#3462).

Also renegotiation is working with OpenSSL by default, is there a dedicated flag for it ? Didn't find one in `./lib/vtls/openssl.c` .

I can say it is enabled in OpenSSL as my code was working properly on Ubuntu which use curl and OpenSSL and failed in Android which use BoringSSL. I did find it while inspecting TLS traffic with wireshark, thanks to https://daniel.haxx.se/blog/2018/01/15/inspect-curls-tls-traffic/ . In my case server is requesting renegotiation to authenticate client with certificates if a SAS token is not found in HTTP headers. 

For what it worth, [Conscrypt](https://github.com/google/conscrypt) which is Android apps and framework Java Security Provider enable renegotiation by default, see [`NativeCrypto_SSL_accept_renegotiations`](https://github.com/google/conscrypt/blob/master/common/src/jni/main/cpp/conscrypt/native_crypto.cc#L7420-L7429) called by [`NativeSsl.initialize()`](https://github.com/google/conscrypt/blob/master/common/src/main/java/org/conscrypt/NativeSsl.java#L287-L290) .

Maybe add more conditional for TLS < 1.3 and HTTP 1.1 ? Is this even possible or needed ?

**Comment by davidben** [comment]
> In that case, you'd also ship your own copy of your TLS library, which can just as well be OpenSSL if you like.

I should have said that it *should* be OpenSSL. As noted in BoringSSL's README, BoringSSL is designed to meet Google's needs. We don't expect external Android applications to use it.
https://boringssl.googlesource.com/boringssl/

**Comment by JeremR** [comment]
About Conscrypt, what do you call by _legacy compatibility reasons_ ? Is my case of server requesting client cert through renegotiation if security token is not found in HTTP headers considered legacy ?

About my app, I'm in the BSP side of Android (below SDK) so shipping my own copy of TLS library is not desired in my point of view. Maybe I should have pushed my patch to AOSP version of [curl](https://android.googlesource.com/platform/external/curl/) so this way you would have better control of it when you'll want to drop the feature in BoringSSL ?

@bagder As my code is using the libcurl (and not curl), I tried to fix this renegotiation issue by using a callback while connection is setup. But as I'm using `curl_easy_init()` I didn't find a good way to access the `SSL *` object as it seems to be created in `curl_easy_perform()`. Do you have an idea ?

Thanks
