### ISSUE TITLE
Can not Compiling with LibreSSL on Windows with MinGW

### ISSUE THREAD

**Issue by SourcePowered** [curl/curl#3260]
Can not Compiling with LibreSSL on Windows with MinGW.

**Comment by bagder** [comment]
Please show us what you tried and what happened!

**Comment by SourcePowered** [comment]
Using MinGW-w64 GCC 7.3.0 x64 on Windows 10

1. set OPENSSL_PATH=c:\libressl-2.8.2
2. `mingw32-make mingw32-ssl`
3. Wait for a moment ...
4.

**Comment by MarcelRaad** [comment]
The problem here seems to be that `CURL_STATICLIB` is defined after the curl.h include, so the linker looks for the dynamic version of the symbols.

**Comment by bagder** [comment]
@SourcePowered that seems to be the simple explanation. Without further feedback, we will consider this done.

**Comment by gvanem** [comment]
@SourcePowered Why are the objects in your `libssl.a` named like they were compiled using MSVC?

Like in the `ld` error `libssl.a(bio_ssl.c.obj)`. Should AFAICS be `libssl.a(bio_ssl.c.o)` if MinGW was used throughout.

**Comment by bagder** [comment]
No response after several weeks. Closing.
