### ISSUE TITLE
curl does not maintain custom set headers order

### ISSUE THREAD

**Issue by alkorsan** [curl/curl#3282]
### I did this

`curl -X POST --data-binary @"$file" -H 'Connection: keep-alive' -H 'Transfer-Encoding: chunked' -H 'Content-Type: $content' -H 'User-Agent: $UA' -H 'Accept-Encoding: $enc' -H 'Accept-Language: $lang'   --user-agent "$UA"  --output - "$link"`

### I expected the following
when I send that command to a HTTPS link, curl makes a handshake then it send POST, the problem is that my headers are not respected in the handshake ,but they are respected in POST!

for example `user-agent `  is fine , the order follow my order (handshake+POST).
but `Connection: keep-alive ` does not respect the order in the handshake. it respect my order only in the POST.

using --keepalive and overwriting it with `-H 'User-Agent: $UA' `  does not solve the problem.

How can I make curl respect the order of headers that I gaved to him? thank you

### curl/libcurl version
curl 7.56.1 (i686-pc-cygwin)
[curl -V output]
```
$ curl -V
curl 7.56.1 (i686-pc-cygwin) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.7.0 nghttp2/1.31.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy Metalink PSL

```
### operating system
win 7 sp1

**Comment by jay** [comment]
The order is not guaranteed but typically libcurl will append the user specified headers after its own. Technically curl headers are user specified headers, that is how libcurl sees them. So for example the Host header is set by libcurl so if you update the host header it appears in the order of libcurl headers, before any user specified header not set by libcurl. If you update the user agent header that is set by the curl tool so it appears after IIRC.

Can you tell us why you want to do that? The RFC says the [field order is not significant](https://tools.ietf.org/html/rfc7230#section-3.2.2). Also can you explain what you mean by this:

> my headers are not respected in the handshake ,but they are respected in POST!

**Comment by alkorsan** [comment]
> Can you tell us why you want to do that?

for privacy, some servers use the order of headers to track who play with the headers, or who use a cli instead of a browser...etc

> can you explain what you mean by this:
> 
> my headers are not respected in the handshake ,but they are respected in POST!

when I send that curl command I get the following:
1 - a handshake that uses curl order for headers ignoring my defined headers order.
2 - after the succusful handshake curl send my POST using the same order of headers as I wrote them, it respect my order.

>  The RFC says the field order is not significant.

so there is no solution using curl? thank you

**Comment by jay** [comment]
> for privacy, some servers use the order of headers to track who play with the headers, or who use a cli instead of a browser...etc

Where? I've seen header order recorded for fraud prevention but I don't recall seeing it for any other reason.

> 1 - a handshake that uses curl order for headers ignoring my defined headers order.
> 2 - after the succusful handshake curl send my POST using the same order of headers as I wrote them, it respect my order.

I don't know what you mean by handshake, how is that separate from your POST transfer? There is a request and response. As far as I can tell you have one request your POST with your headers.

> so there is no solution using curl? thank you

There's no solution that's guaranteed. If you delete each header before setting it then you can control the order but it's not documented behavior and subject to change. For example if you write -H "Host:" -H "Host: foo" libcurl will delete the Host from its internal headers and then append it as a user-specified header. Also regarding my earlier comments on user-agent it depends how you add it, if you add it via -H it's a user-specified header but if you add it via --user-agent I'm pretty sure it's considered an internal header then because it's set differently.

**Comment by alkorsan** [comment]
> Where? I've seen header order recorded for fraud prevention but I don't recall seeing it for any other reason.

if scraping is considered fraud , then yes lol, but google have to pay a lot in that situation, but thanks to God I don  t think scraping is illegal yet, it s only not beneficial to one part, and this differ from fraud...

I m using this to talk to the web api speech , which is diferent than the google cloud api speech. chrome is permitted to use unlimited quota of this API, so I want to use this service from the CLI. that s all my secret (dangerous? lol ) proyect. I don t think it is a fraud , the service is free and the API key for unlimited quota is used by everybody outside the browser, like for example : https://pypi.org/project/SpeechRecognition/
 so if it is posible in python , why i will not be able to do it in bash... that s all

> I don't know what you mean by handshake,

sorry , I meant three-way handshake. the handshake have diferent headers than the POST, because there is more than one comunication when it s https.

> For example if you write -H "Host:" -H "Host: foo" libcurl will delete the Host

this works for some headers but not all, for example the `Connection: Keep-Alive` nothing affect it. it s always at the end in the 3 way handshake.

> You cannot fully control the header order in curl requests. It has been mentioned in the TODO document since a very long time.

thank you. scapy is my last solution :( or forget my home speech to text proyect  :cry:

**Comment by jay** [comment]
> this works for some headers but not all, for example the Connection: Keep-Alive nothing affect it. it s always at the end in the 3 way handshake.

Can you use httpbin.org or some other test service to create a minimal example?

**Comment by alkorsan** [comment]
`curl -X POST "https://httpbin.org/post" -H "accept: application/json" -H 'Connection:'`

now use wireshark and look to the 3 way handshake,it shows:
```
CONNECT httpbin.org:443 HTTP/1.1
Host: httpbin.org:443
User-Agent: curl/7.56.1
Connection: Keep-Alive
````
then 
```
POST https://httpbin.org/post HTTP/1.1
Host: httpbin.org
User-Agent: curl/7.56.1
accept: application/json
```

look how Connection: Keep-Alive is preserved in the handshake for example.

**Comment by bagder** [comment]
(First, "3 way handshake" is the TCP connection. You talk of HTTP here so there's no 3-way handshake.)

You don't need wireshark to view the requests. just use `--trace-ascii -`.

Are you talking about header differences between the CONNECT request and the POST request?

`-H` does not modify "proxy headers" (since 7.37.0) so you should rather use `--proxy-header` if you want to change/add headers to the CONNECT request.

**Comment by alkorsan** [comment]
> First, "3 way handshake" is the TCP connection

oops sorry, in the tcp world I lose the street to my house sometimes. this explain all, I forgot I m using a proxy to filter the traffic locally for ease of snifing. I saw this CONNECT all the time, and did not realize that it happens only inside my proxy,so I said it s the handshake of the ssl :man_facepalming: ... thank you

> --trace-ascii -

If I had know this I would not lost all this time because of the proxy. wanderfull

> --proxy-header

I just know too now of this option, here is the test:

`curl ... --proxy-header 'User-Agent: Mozilla...' --proxy-header 'Connection:' --proxy-header 'Connection: keep-alive' `

result
```
...
Connection: Keep-Alive
Connection: keep-alive
User-Agent: Mozilla...
...
```

 
`curl ... --proxy-header 'User-Agent: Mozilla...' --proxy-header 'Connection:' `

result
```
...
Connection: Keep-Alive
User-Agent: Mozilla...
...
```
conclusion : I think it is not posible to change the position of the Connection tag or remove it. but it s ok because POST works fine and this is the important. CONNECT happens only inside my local. in the other hand this option can change the other headers that I coulded test, it have only problems with the ordering of "Connection:.." .

> You cannot fully control the header order in curl requests. It has been mentioned in the TODO document since a very long time.

is there any list of the headers that do not obbey the rules please? 

thank you very much for your time and for all the info and help you gaved to me.

**Comment by alkorsan** [comment]
> I can't reproduce that with my git version. I get:

here is a full test if you want to see it:
download fiddler
run it and stop the auto capture
then run in bash
```
export http_proxy="127.0.0.1:8888"
export https_proxy="127.0.0.1:8888"
export ftp_proxy="127.0.0.1:8888"
# for audio.flac you can put any file because the problem happens before talking to google
curl -X POST --data-binary @"audio.flac" -H 'Expect:' -H 'Content-Type: audio/x-flac; rate=16000;' "https://www.google.com/speech-api/v2/recognize?client=chromium&lang=en_US&key=<redacted>" -v -k
```
curl says that:

```
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.59.0 
> Proxy-Connection: Keep-Alive
>
```

```
> POST /speech-api/v2/recognize?client=chromium&lang=en_US&key=<redacted> HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.59.0
> Accept: */*
> Content-Type: audio/x-flac; rate=16000;
> Content-Length: 81588
>
```

fiddler says that:
```
CONNECT www.google.com:443 HTTP/1.1
Host: www.google.com:443
User-Agent: curl/7.59.0
Connection: Keep-Alive 
```

```
POST https://www.google.com/speech-api/v2/recognize?client=chromium&lang=en_US&key=<redacted> HTTP/1.1
Host: www.google.com
User-Agent: curl/7.59.0
Accept: */*
Content-Type: audio/x-flac; rate=16000;
Content-Length: 81588
```
> The CONNECT request doesn't use Connection: at all by default, but I can remove the Proxy-Connection: header 

as you see above the `Connection` always appears and `Proxy-Connection: ` does not appears never!! I think fiddler is not good to inspect , he change the request he make a new conexcion and he don t even talk http2, so he was all this time converting curl http2 upgrade to http1.1...

> Doesn't obey to what rules? curl speak HTTP by the book and obeys to the rules.

you said before that :  
> You cannot fully control the header order in curl requests.

so I asked what headers curl cannot fully control their order? there is a list of that headers ? I searched but could not find nothing about them.
thank you

**Comment by alkorsan** [comment]
thank you very much sir.

**Comment by bagder** [comment]
The feature that would allow libcurl to [rearrange the header order](https://curl.haxx.se/docs/todo.html#Rearrange_request_header_order) has been listed in the TODO since a very long time. This is not a bug, this is a missing feature.
