### ISSUE TITLE
Renegotiation should be disabled by default

### ISSUE THREAD

**Issue by bagder** [curl/curl#3283]
Enabling it is also non-compliant with HTTP/2 which requires it be disabled:
https://httpwg.org/specs/rfc7540.html#rfc.section.9.2.1

_Originally posted by @davidben in https://github.com/curl/curl/issues/3258#issuecomment-437560013_

Commit 27cb3846791 made it enabled by default for BoringSSL.

cc  @JeremR

**Comment by mkauf** [comment]
For OpenSSL >= 1.1.0h, we could disable renegotiation with the Flag ``SSL_OP_NO_RENGOTIATION``.

For OpenSSL <= 1.0.2, there is an undocumented flag, see https://github.com/openssl/openssl/issues/4739 :

```
SSL *connection;
...
connection->s3->flags |= SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS;
```

Both approaches do not work for OpenSSL 1.1.0 - 1.1.0g.

**Comment by JeremR** [comment]
From OpenSSL documentation, https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_options.html in case of:
>Patched client and server
> Connections and renegotiation are always permitted by OpenSSL implementations.

If renegotiation should be disabled by default in OpenSSL, then option `SSL_OP_NO_RENEGOTIATION` shall be set.

Currently behavior is different between both libs.

**Comment by bagder** [comment]
> If renegotiation should be disabled by default

Until someone argues for something else I think it should be. I'll welcome PRs to fix!
