### ISSUE TITLE
Schannel can't disable only CURLOPT_SSL_VERIFYPEER and still verify the host name

### ISSUE THREAD

**Issue by bagder** [curl/curl#3284]
### I did this

Martin Galvan [reported on the mailing list](https://curl.haxx.se/mail/lib-2018-10/0113.html):

> I was looking at the WinSSL code which processes
> CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST, and noticed that,
> if CURLOPT_SSL_VERIFYPEER isn't enabled, the host name checking won't
> be performed:

> https://github.com/curl/curl/blob/master/lib/vtls/schannel_verify.c#L539
> https://github.com/curl/curl/blob/master/lib/vtls/schannel.c#L1117

### I expected the following

If the TLS backend has the API for it, the options should be independent.

### curl/libcurl version

current git master

### operating system

Windows

**Comment by jay** [comment]
I'll take a look but I thought it was already independent.
https://github.com/curl/curl/blob/196677150f711a96c38ed123e621f1d4e995b2e5/lib/vtls/schannel.c#L536-L541

**Comment by jay** [comment]
It fails with SEC_E_WRONG_PRINCIPAL when verifypeer is enabled, but succeeds when it's disabled. (I'm using https://cdn0.nflximg.net as test server). When verifypeer is disabled then manual verification is enabled SCH_CRED_MANUAL_CRED_VALIDATION. What I think is happening is the manual verification disables the server name check even though we don't. Seems like they could have warned us of that in the doc.

**Comment by bagder** [comment]
@jay any idea on how to deal with this? Should we just close or can we document this somehow somewhere?
