### ISSUE TITLE
NTLMv2 not fully functional

### ISSUE THREAD

**Issue by huaraz** [curl/curl#3286]
### I did this

  I used the latest curl Version to authenticate against a porxy with --proxy-ntlm. The proxy was joined to AD which only accepts secure NTLMv2.
  
  Internet Explorer  NTLM exchange looks like:
IE NTLM type 1

Proxy-Authorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==\r\n
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_NEGOTIATE (0x00000001)
        Negotiate Flags: 0xa2088207, Negotiate 56, Negotiate 128, Negotiate Version, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate OEM, Negotiate UNICODE
            1... .... .... .... .... .... .... .... = Negotiate 56: Set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..1. .... .... .... .... .... .... .... = Negotiate 128: Set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..1. .... .... .... .... .... .... = Negotiate Version: Set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 0... .... .... .... .... .... = Negotiate Target Info: Not set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...0 .... .... .... .... = Target Type Domain: Not set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..1. = Negotiate OEM: Set
            .... .... .... .... .... .... .... ...1 = Negotiate UNICODE: Set
        Calling workstation domain: NULL
        Calling workstation name: NULL
        Version 6.1 (Build 7601); NTLM Current Revision 15
            Major Version: 6
            Minor Version: 1
            Build Number: 7601
            NTLM Current Revision: 15

IE(McAfee) NTLM type 2

Proxy-Authenticate: NTLM TlRMTVNTUAACAAAAAAAAAAAAAAAFgomgTynGuLy0QXwAAAAAAAAAAAAAAAAAAAAA\r\n
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_CHALLENGE (0x00000002)
        Target Name: NULL
        Negotiate Flags: 0xa0898205, Negotiate 56, Negotiate 128, Negotiate Target Info, Negotiate Extended Security, Target Type Domain, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate UNICODE
            1... .... .... .... .... .... .... .... = Negotiate 56: Set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..1. .... .... .... .... .... .... .... = Negotiate 128: Set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..0. .... .... .... .... .... .... = Negotiate Version: Not set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 1... .... .... .... .... .... = Negotiate Target Info: Set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...1 .... .... .... .... = Target Type Domain: Set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..0. = Negotiate OEM: Not set
            .... .... .... .... .... .... .... ...1 = Negotiate UNICODE: Set
        NTLM Server Challenge: 4f29c6b8bcb4417c
        Reserved: 0000000000000000
        Target Info List: Empty

IE NTLM type 3

 [truncated]Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAIQAAABoAGgAnAAAAAYABgBYAAAADAAMAF4AAAAaABo......
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_AUTH (0x00000003)
        Lan Manager Response: c5e5415ee4abe5e53111eb4c57ca317d6efc344bad2542a6
            Length: 24
            Maxlen: 24
            Offset: 132
        NTLM Response: 785714e1caa79f519213e4ae82d2f9b50101000000000000...
            Length: 104
            Maxlen: 104
            Offset: 156
            NTLMv2 Response: 785714e1caa79f519213e4ae82d2f9b50101000000000000...
                NTProofStr: 785714e1caa79f519213e4ae82d2f9b5
                Response Version: 1
                Hi Response Version: 1
                Z: 000000000000
                Time: Nov  8, 2018 16:58:10.360678400 UTC
                NTLMv2 Client Challenge: 6efc344bad2542a6
                Z: 00000000
                Attribute: Restrictions
                    NTLMV2 Response Item Type: Restrictions (0x0008)
                    NTLMV2 Response Item Length: 48
                    Restrictions: 30000000000000000000000000200000856e7b86caf2ee6f...
                Attribute: End of list
                    NTLMV2 Response Item Type: End of list (0x0000)
                    NTLMV2 Response Item Length: 0
                Z: 00000000
        Domain name: XXX
            Length: 6
            Maxlen: 6
            Offset: 88
        User name: user01
            Length: 12
            Maxlen: 12
            Offset: 94
        Host name: DESKTOP000001
            Length: 26
            Maxlen: 26
            Offset: 106
        Session Key: Empty
        Negotiate Flags: 0xa2888205, Negotiate 56, Negotiate 128, Negotiate Version, Negotiate Target Info, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate UNICODE
            1... .... .... .... .... .... .... .... = Negotiate 56: Set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..1. .... .... .... .... .... .... .... = Negotiate 128: Set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..1. .... .... .... .... .... .... = Negotiate Version: Set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 1... .... .... .... .... .... = Negotiate Target Info: Set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...0 .... .... .... .... = Target Type Domain: Not set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..0. = Negotiate OEM: Not set
            .... .... .... .... .... .... .... ...1 = Negotiate UNICODE: Set
        Version 6.1 (Build 7601); NTLM Current Revision 15
            Major Version: 6
            Minor Version: 1
            Build Number: 7601
            NTLM Current Revision: 15
        MIC: 87dec4750a7b6c9e0a8e9d8795a6cb94

Curl NTLM exchange is:

curl NTLM type 1

Proxy-Authorization: NTLM TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=\r\n
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_NEGOTIATE (0x00000001)
        Negotiate Flags: 0x00088206, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate OEM
            0... .... .... .... .... .... .... .... = Negotiate 56: Not set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..0. .... .... .... .... .... .... .... = Negotiate 128: Not set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..0. .... .... .... .... .... .... = Negotiate Version: Not set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 0... .... .... .... .... .... = Negotiate Target Info: Not set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...0 .... .... .... .... = Target Type Domain: Not set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..1. = Negotiate OEM: Set
            .... .... .... .... .... .... .... ...0 = Negotiate UNICODE: Not set
        Calling workstation domain: NULL
        Calling workstation name: NULL

curl (McAfee) NTLM type 2

Proxy-Authenticate: NTLM TlRMTVNTUAACAAAAAAAAAAAAAAAGgokAXmf7HuqyuFEAAAAAAAAAAAAAAAAAAAAA\r\n
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_CHALLENGE (0x00000002)
        Target Name: NULL
        Negotiate Flags: 0x00898206, Negotiate Target Info, Negotiate Extended Security, Target Type Domain, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate OEM
            0... .... .... .... .... .... .... .... = Negotiate 56: Not set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..0. .... .... .... .... .... .... .... = Negotiate 128: Not set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..0. .... .... .... .... .... .... = Negotiate Version: Not set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 1... .... .... .... .... .... = Negotiate Target Info: Set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...1 .... .... .... .... = Target Type Domain: Set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..1. = Negotiate OEM: Set
            .... .... .... .... .... .... .... ...0 = Negotiate UNICODE: Not set
        NTLM Server Challenge: 5e67fb1eeab2b851
        Reserved: 0000000000000000
        Target Info List: Empty

Curl type 3

Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAEAAAAAYABgAWAAAAAMAAwBwAAAABg......
    NTLM Secure Service Provider
        NTLMSSP identifier: NTLMSSP
        NTLM Message Type: NTLMSSP_AUTH (0x00000003)
        Lan Manager Response: a70028552819d71e00000000000000000000000000000000
            Length: 24
            Maxlen: 24
            Offset: 64
        LMv2 Client Challenge: a70028552819d71e
        NTLM Response: a7b5c28a0e8d60b9dc12ba0cef407f562347f71d4fd15234
            Length: 24
            Maxlen: 24
            Offset: 88
        Domain name: XXX
            Length: 3
            Maxlen: 3
            Offset: 112
        User name: user01
            Length: 6
            Maxlen: 6
            Offset: 115
        Host name: host01
            Length: 6
            Maxlen: 6
            Offset: 121
        Session Key: Empty
        Negotiate Flags: 0x00898206, Negotiate Target Info, Negotiate Extended Security, Target Type Domain, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate OEM
            0... .... .... .... .... .... .... .... = Negotiate 56: Not set
            .0.. .... .... .... .... .... .... .... = Negotiate Key Exchange: Not set
            ..0. .... .... .... .... .... .... .... = Negotiate 128: Not set
            ...0 .... .... .... .... .... .... .... = Negotiate 0x10000000: Not set
            .... 0... .... .... .... .... .... .... = Negotiate 0x08000000: Not set
            .... .0.. .... .... .... .... .... .... = Negotiate 0x04000000: Not set
            .... ..0. .... .... .... .... .... .... = Negotiate Version: Not set
            .... ...0 .... .... .... .... .... .... = Negotiate 0x01000000: Not set
            .... .... 1... .... .... .... .... .... = Negotiate Target Info: Set
            .... .... .0.. .... .... .... .... .... = Request Non-NT Session: Not set
            .... .... ..0. .... .... .... .... .... = Negotiate 0x00200000: Not set
            .... .... ...0 .... .... .... .... .... = Negotiate Identify: Not set
            .... .... .... 1... .... .... .... .... = Negotiate Extended Security: Set
            .... .... .... .0.. .... .... .... .... = Target Type Share: Not set
            .... .... .... ..0. .... .... .... .... = Target Type Server: Not set
            .... .... .... ...1 .... .... .... .... = Target Type Domain: Set
            .... .... .... .... 1... .... .... .... = Negotiate Always Sign: Set
            .... .... .... .... .0.. .... .... .... = Negotiate 0x00004000: Not set
            .... .... .... .... ..0. .... .... .... = Negotiate OEM Workstation Supplied: Not set
            .... .... .... .... ...0 .... .... .... = Negotiate OEM Domain Supplied: Not set
            .... .... .... .... .... 0... .... .... = Negotiate Anonymous: Not set
            .... .... .... .... .... .0.. .... .... = Negotiate NT Only: Not set
            .... .... .... .... .... ..1. .... .... = Negotiate NTLM key: Set
            .... .... .... .... .... ...0 .... .... = Negotiate 0x00000100: Not set
            .... .... .... .... .... .... 0... .... = Negotiate Lan Manager Key: Not set
            .... .... .... .... .... .... .0.. .... = Negotiate Datagram: Not set
            .... .... .... .... .... .... ..0. .... = Negotiate Seal: Not set
            .... .... .... .... .... .... ...0 .... = Negotiate Sign: Not set
            .... .... .... .... .... .... .... 0... = Request 0x00000008: Not set
            .... .... .... .... .... .... .... .1.. = Request Target: Set
            .... .... .... .... .... .... .... ..1. = Negotiate OEM: Set
            .... .... .... .... .... .... .... ...0 = Negotiate UNICODE: Not set

 

The difference can be seen in the typ3 response

IE:

        NTLM Response: 785714e1caa79f519213e4ae82d2f9b50101000000000000...
            Length: 104
            Maxlen: 104
            Offset: 156
            NTLMv2 Response: 785714e1caa79f519213e4ae82d2f9b50101000000000000...
Curl:
        Lan Manager Response: a70028552819d71e00000000000000000000000000000000
            Length: 24
            Maxlen: 24
            Offset: 64
        LMv2 Client Challenge: a70028552819d71e
       
A change in lib/vauth/ntlm.c  

 
#if defined(USE_NTRESPONSES) && defined(USE_NTLM_V2)
//MM No idea why this works, but it does
//   if(ntlm->target_info_len) {
  if(ntlm->flags & NTLMFLAG_NEGOTIATE_TARGET_INFO ) {
    unsigned char ntbuffer[0x18];
    unsigned char entropy[8];

### I expected the following

I expected successful authentication, but received a rejection.

### curl/libcurl version

> src/curl -V
curl 7.63.0-DEV (i686-suse-linux-gnu) libcurl/7.63.0-DEV OpenSSL/1.0.1g zlib/1.2.7 libssh2/1.4.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system

SLES 11

**Comment by bagder** [comment]
@huaraz would you mind making a PR out of your suggested change? Then it will get some rudimentary testing and we'll see the proposed change better.

**Comment by huaraz** [comment]
Ok. I am just reading https://msdn.microsoft.com/en-us/library/cc236621.aspx  to understand the NTLM flags and which of them could indicate the use of the existing codes sections.

Markus

**Comment by huaraz** [comment]
Created pull request #3287

**Comment by huaraz** [comment]
Can someone help verifying the pull request works in all cases ?  

Thank you
Markus
