### ISSUE TITLE
CMake: TRY_RUN() invoked in cross-compiling mode

### ISSUE THREAD

**Issue by bagder** [curl/curl#3292]
### I did this

Build for android using the cmake build files. See #3268 and in particular this [build failure](https://ci.appveyor.com/project/curlorg/curl/builds/20318714/job/5rmd7gwgr9haou77#L695). 

Towards the end of the cmake run it says
~~~
-- Performing Test HAVE_POLL_FINE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_POLL_FINE_EXITCODE (advanced)
   HAVE_POLL_FINE_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see C:/projects/curl/build/TryRunResults.cmake
-- Performing Test HAVE_POLL_FINE - Failed
~~~

### I expected the following

The build to succeed

### curl/libcurl version

git master

### operating system

a build for Android on Windows

**Comment by snikulov** [comment]
@bagder regarding this issue. 
Is this really need run executable to understand that poll is present on target OS?
Aren't compilation and linking (or symbol presence) enough?

**Comment by snikulov** [comment]
Looks like the issue is related to [this 
 line](https://github.com/curl/curl/blob/master/CMake/OtherTests.cmake#L181)

**Comment by bagder** [comment]
The check tries to see if the `poll()` implementation works by running a small test, designed to detect a particular known problem with old macOS poll() implementations. Since we can't run programs for cross-compiled systems, a sensible default is probably the only thing we can do...

**Comment by snikulov** [comment]
@bagder hmm... but according to reference I've provided this check is disabled for APPLE targets...
`if(NOT APPLE)` will disable this check on macOS and perform it for all others OS.
What I can suggest is add to this check additional condition something like
`if(NOT APPLE AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)`

**Comment by bagder** [comment]
Right, now it comes back to me.

We once introduced that check in order to detect a working poll() but when macOS broke their poll **again** in 10.12 we gave up (configure change a34c7ce that was also done to cmake in 6aa9cfa2b90a818e0).

It is questionable if that check is useful right now...

**Comment by snikulov** [comment]
@bagder Anyway my proposal is the same - should remove `check_c_source_runs` if CMake generates for cross-compilation. 
So if you've no objections I can provide PR for this.
Other checks for MacOS will not be performed since I've no Mac to check them :)

**Comment by snikulov** [comment]
BTW, someone should enable `T=cmake` for `os=osx` on travis-ci...

**Comment by bagder** [comment]
> should remove check_c_source_runs if CMake generates for cross-compilation.

:+1: 

> someone should enable T=cmake for os=osx on travis-ci...

:+1: See #3467 !

**Comment by bagder** [comment]
> Looks like for cross-compilation poll will never be used.

Yeah. I think that's a mistake but I figure it is also rarely a big deal if poll or select is used... 

> Maybe it is better to explicitly state what to use?
> For example ./configure --enable-poll --disable-select?

For cross-compiling that would certainly help, or users have to edit `lib/curl_config.h` after configure ran.
