### ISSUE TITLE
Windows: GetTickCount has too low timer resolution

### ISSUE THREAD

**Issue by pps83** [curl/curl#3309]
GetTickCount does not necessarily have good precision if somebody tries to debug/analyze timings. It could have 1 or even 10 ms precision.
Would it be acceptable to submit a patch that adds a CURL option that sets TIMER FUNCTION that would be used to retrieve timestamps instead?

Alternatively it could simply use [QueryPerformanceCounter/QueryPerformanceFrequency](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx) on windows.

https://github.com/curl/curl/blob/27a5e1f1119b0e205544f15e1fe1662e5a15aef9/lib/timeval.c#L38

**Comment by bagder** [comment]
> option that sets TIMER FUNCTION that would be used to retrieve timestamps instead?

That would imply that some users would want different timestamps. I've never heard of such users.

> Alternatively it could simply use ...

I think it would be good enough if we just used the best available high resolution timer by default.

**Comment by pps83** [comment]
> I think it would be good enough if we just used the best available high resolution timer by default.

See proposed fix: timeval: use QueryPerformanceCounter on Windows #3318
