### ISSUE TITLE
CURLE_BAD_CONTENT_ENCODING on "Content-Encoding: none"

### ISSUE THREAD

**Issue by southernedge** [curl/curl#3315]
I did this:
1. created the download on the https://wetransfer.com
2. download with help dll (curl-7.58.0,curl-7.62.0, 2018)
3. received CURLE_BAD_CONTENT_ENCODING
4. download with help dll (curl-7.45, 2015)
5. received CURLE_OK
6. received HTTP header is
HTTP/1.1 200 OK 	
Content-Type: application/x-msdownload 	
Content-Length: 29893021 	
Connection: keep-alive 	
Server: nginx/1.12.2 	
Date: Tue, 27 Nov 2018 11:36:59 GMT 	
Content-Transfer-Encoding: binary 	
Content-Encoding: none 	
Cache-Control: private, no-transform, no-store 	
Allow: GET, HEAD 	
Content-Disposition: attachment 	
X-Revision: 01538850f79b561527c926f637728b710ceec468 	
X-Transfer-Id: 25de132ff624fecd7f71fab21b2b99a920181125060802 	
Accept-Ranges: bytes 	
X-Fast-Send-Dispatch: hijack 	
X-Cache: Miss from cloudfront 	
Via: 1.1 465e661d27b2b6a1c349a5550c745b0f.cloudfront.net (CloudFront) 	
X-Amz-Cf-Id: HJrivIdeIldW5AVjKS5Q7ef4C3x1D8CWN_s2Ml2eHUlSyVk_D4N3Qg== 	

I expected the following: 
Browsers have no problem downloading this file. I don't think the Content-Encoding: none parameter has a fatal error.

operating system: Win7x64, win10x64

Thank you help and for your very useful project!

**Comment by southernedge** [comment]
I did this:
1. created the download on the https://wetransfer.com
2. download if with help dll (curl-7.58.0,curl-7.62.0, 2018)
3. received CURLE_BAD_CONTENT_ENCODING
4. download if with help dll (curl-7.45, 2015)
5. received CURLE_OK
6. received HTTP header is
HTTP/1.1 200 OK 	
Content-Type: application/x-msdownload 	
Content-Length: 29893021 	
Connection: keep-alive 	
Server: nginx/1.12.2 	
Date: Tue, 27 Nov 2018 11:36:59 GMT 	
Content-Transfer-Encoding: binary 	
Content-Encoding: none 	
Cache-Control: private, no-transform, no-store 	
Allow: GET, HEAD 	
Content-Disposition: attachment 	
X-Revision: 01538850f79b561527c926f637728b710ceec468 	
X-Transfer-Id: 25de132ff624fecd7f71fab21b2b99a920181125060802 	
Accept-Ranges: bytes 	
X-Fast-Send-Dispatch: hijack 	
X-Cache: Miss from cloudfront 	
Via: 1.1 465e661d27b2b6a1c349a5550c745b0f.cloudfront.net (CloudFront) 	
X-Amz-Cf-Id: HJrivIdeIldW5AVjKS5Q7ef4C3x1D8CWN_s2Ml2eHUlSyVk_D4N3Qg== 	

I expected the following: 
Browsers have no problem downloading this file. I don't think the Content-Encoding: none parameter has a fatal error.

operating system: Win7x64, win10x64

**Comment by bagder** [comment]
First, we'll note that `none` is not a [registered](https://www.iana.org/assignments/http-parameters/http-parameters.xhtml) a content-encoding.

**Comment by bagder** [comment]
I can't reproduce this using current git master nor curl 7.62.0. Can you either show us a curl command line that reproduce this or explain how you use libcurl to make it fail?

I tried:

1. uploaded something to wetransfer but it doesn't provide the file with `Content-Encoding: none` for me.
2. I wrote a new test for curl that sends `Content-Encoding: none` with `--compressed` but it doesn't reproduce either.  See #3317

**Comment by mkauf** [comment]
This is a duplicate of #2298

**Comment by bagder** [comment]
Right, except that that was fixed in 7.59.0 and @southernedge says it exists still...

**Comment by jay** [comment]
@southernedge Please confirm by calling [curl_version()](https://curl.haxx.se/libcurl/c/curl_version.html). It's possible that the libcurl DLL you are reproducing with is an older version.

**Comment by southernedge** [comment]
Thank you for your quick responce!
There is my test that every time give me "Content-Encoding: none" here
https://wetransfer.com/downloads/25de132ff624fecd7f71fab21b2b99a920181125060802/3fc595c691eaec31c95a372e18dddd4d20181125060802/c931ac?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email
Could you try ithis link?

----------------------------------------------------------
I want to close this question.
Confusion occurred. I can not download a working library from
Windows 32 bit 7.62.0 binary Stefan Kanthak
Windows 32 bit 7.62.0 binary Viktor Szakats
libcurl.exe gives crash.
libcurl.dll returns error ERROR_INVALID_ADDRESS   487L
I cannot do an additional test for you and I should come back to working old 7.45 version. :(

Very sorry!

**Comment by bagder** [comment]
I tried that link. It doesn't give such a response header to me, neither with HTTP/1.1 nor HTTP/2 and I tried with and without `--compressed`.

**Comment by southernedge** [comment]
**Log from an extension of Chrome browser:
the first request** 
BSH GET https://wetransfer.com/downloads/25de132ff624fecd7f71fab21b2b99a920181125060802/3fc595c691eaec31c95a372e18dddd4d20181125060802/c931ac?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email
background_CH3.js:2292 Upgrade-Insecure-Requests: 1
background_CH3.js:2292 User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.62 Safari/537.36
background_CH3.js:2292 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
background_CH3.js:2292 Accept-Encoding: gzip, deflate, br
background_CH3.js:2292 Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
background_CH3.js:2292 Cookie: _wt_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTBjNTE4N2UyNDY5MTY5ZDllZmNjN2EzYWJmMWZlMzRiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWh4NWNRQjBlM1F6bHp6MWl5dE1UNWlXcDAwVDA2dlZuQ0ZjN1lXUkFtakE9BjsARg%3D%3D--2d1fce190208ffbf5131aada114d48078630d813; sp=9a717c38-ddaf-4fec-a9d2-7eff75a8cd1c; wt_tandc=20180508; wt_first_visit=1543126331671; _ga=GA1.2.1505206807.1543126332; _gid=GA1.2.201027236.1543126332; wt_team_onboarded=true; wt_downloaded=31; _wt_snowplowid.38f1=60d45abd-3496-43ac-b522-5d484bd70f07.1543126329.15.1543381999.1543324024.70d9f278-2122-4b8d-9713-8cb659e6cdf4; _sp_id.38f1=43bc307f-1a27-4301-95a1-87e5ef140c05.1543126329.7.1543381999.1543324024.a9531f87-e5cd-4685-8246-44bc2a75d1e3
background_CH3.js:2412 
HR GET https://wetransfer.com/downloads/25de132ff624fecd7f71fab21b2b99a920181125060802/3fc595c691eaec31c95a372e18dddd4d20181125060802/c931ac?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email
HTTP/1.1 200 
background_CH3.js:2413 status: 200
background_CH3.js:2413 date: Wed, 28 Nov 2018 10:06:35 GMT
background_CH3.js:2413 content-type: **text/htm**l; charset=utf-8
background_CH3.js:2413 x-frame-options: SAMEORIGIN
background_CH3.js:2413 x-xss-protection: 1; mode=block
background_CH3.js:2413 x-content-type-options: nosniff
background_CH3.js:2413 cache-control: no-cache, no-store, max-age=0, must-revalidate
background_CH3.js:2413 pragma: no-cache
background_CH3.js:2413 expires: Fri, 01 Jan 1990 00:00:00 GMT
background_CH3.js:2413 vary: Accept-Encoding, Origin
background_CH3.js:2413 **content-encoding: gzip** ------------------------> **ok GZIP**
background_CH3.js:2413 x-request-id: b6221161-b908-42fd-9d40-cb4a1c24a3a6
background_CH3.js:2413 x-opaque: 91033c281b1ceca75bdef16c84d2386dac96b56c-05cefb0415ad07848-4095
background_CH3.js:2413 x-runtime: 0.056671
background_CH3.js:2413 strict-transport-security: max-age=15552000; includeSubDomains;
background_CH3.js:2291 


**file receipt**

BSH GET https://download.wetransfer.com/eu2/25de132ff624fecd7f71fab21b2b99a920181125060802/AntDM.1.10.2-setup.exe?token=eyJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWUiOiIyNWRlMTMyZmY2MjRmZWNkN2Y3MWZhYjIxYjJiOTlhOTIwMTgxMTI1MDYwODAyIiwicHJvZmlsZSI6ImV1MiIsImZpbGVuYW1lIjoiQW50RE0uMS4xMC4yLXNldHVwLmV4ZSIsImVzY2FwZWQiOiJmYWxzZSIsImV4cGlyZXMiOjE1NDM0MDAyMDEsImNhbGxiYWNrIjoie1wiZm9ybWRhdGFcIjp7XCJhY3Rpb25cIjpcImh0dHA6Ly9wcm9kdWN0aW9uLmZyb250ZW5kLXYzLnNlcnZpY2UuZXUtd2VzdC0xLnd0OjMwMDAvYXBpL2JhY2tlbmQvdHJhbnNmZXJzLzI1ZGUxMzJmZjYyNGZlY2Q3ZjcxZmFiMjFiMmI5OWE5MjAxODExMjUwNjA4MDIvZG93bmxvYWRzLzUwMDE1MzkxMTQvY29tcGxldGVkLzNmYzU5NWM2OTFlYWVjMzFjOTVhMzcyZTE4ZGRkZDRkMjAxODExMjUwNjA4MDJcIn0sXCJmb3JtXCI6e1wic3RhdHVzXCI6W1wicGFyYW1cIixcInN0YXR1c1wiXSxcImRvd25sb2FkX2lkXCI6XCI1MDAxNTM5MTE0XCJ9fSIsIndheWJpbGxfdXJsIjoiaHR0cDovL3Byb2R1Y3Rpb24uYmFja2VuZC5zZXJ2aWNlLmV1LXdlc3QtMS53dDo5MjkyL3dheWJpbGwvdjEvZjQ4Nzg1ZjcwNGRiMzIyZmI0OTczYjBmMDFjYTc0NDI0NGM0NDYyY2ZlMzczNjNiNThhNmFkZTkzZTFmIn0.WNrLQIK5giGB4bqWmEaaoOxl0nkljv_eM7NMRGwCp9w
background_CH3.js:2292 Upgrade-Insecure-Requests: 1
background_CH3.js:2292 User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.62 Safari/537.36
background_CH3.js:2292 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
background_CH3.js:2292 Referer: https://wetransfer.com/
background_CH3.js:2292 Accept-Encoding: gzip, deflate, br
background_CH3.js:2292 Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
background_CH3.js:2292 Cookie: _wt_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTBjNTE4N2UyNDY5MTY5ZDllZmNjN2EzYWJmMWZlMzRiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWh4NWNRQjBlM1F6bHp6MWl5dE1UNWlXcDAwVDA2dlZuQ0ZjN1lXUkFtakE9BjsARg%3D%3D--2d1fce190208ffbf5131aada114d48078630d813; sp=9a717c38-ddaf-4fec-a9d2-7eff75a8cd1c; wt_tandc=20180508; wt_first_visit=1543126331671; _ga=GA1.2.1505206807.1543126332; _gid=GA1.2.201027236.1543126332; wt_team_onboarded=true; _wt_snowplowses.38f1=*; _wt_snowplowid.38f1=60d45abd-3496-43ac-b522-5d484bd70f07.1543126329.16.1543399599.1543381999.9589d21f-eb58-4273-9d93-9cb520a9c02b; _gat_UA-11792855-4=1; wt_downloaded=32
background_CH3.js:2412 
HR GET https://download.wetransfer.com/eu2/25de132ff624fecd7f71fab21b2b99a920181125060802/AntDM.1.10.2-setup.exe?token=eyJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWUiOiIyNWRlMTMyZmY2MjRmZWNkN2Y3MWZhYjIxYjJiOTlhOTIwMTgxMTI1MDYwODAyIiwicHJvZmlsZSI6ImV1MiIsImZpbGVuYW1lIjoiQW50RE0uMS4xMC4yLXNldHVwLmV4ZSIsImVzY2FwZWQiOiJmYWxzZSIsImV4cGlyZXMiOjE1NDM0MDAyMDEsImNhbGxiYWNrIjoie1wiZm9ybWRhdGFcIjp7XCJhY3Rpb25cIjpcImh0dHA6Ly9wcm9kdWN0aW9uLmZyb250ZW5kLXYzLnNlcnZpY2UuZXUtd2VzdC0xLnd0OjMwMDAvYXBpL2JhY2tlbmQvdHJhbnNmZXJzLzI1ZGUxMzJmZjYyNGZlY2Q3ZjcxZmFiMjFiMmI5OWE5MjAxODExMjUwNjA4MDIvZG93bmxvYWRzLzUwMDE1MzkxMTQvY29tcGxldGVkLzNmYzU5NWM2OTFlYWVjMzFjOTVhMzcyZTE4ZGRkZDRkMjAxODExMjUwNjA4MDJcIn0sXCJmb3JtXCI6e1wic3RhdHVzXCI6W1wicGFyYW1cIixcInN0YXR1c1wiXSxcImRvd25sb2FkX2lkXCI6XCI1MDAxNTM5MTE0XCJ9fSIsIndheWJpbGxfdXJsIjoiaHR0cDovL3Byb2R1Y3Rpb24uYmFja2VuZC5zZXJ2aWNlLmV1LXdlc3QtMS53dDo5MjkyL3dheWJpbGwvdjEvZjQ4Nzg1ZjcwNGRiMzIyZmI0OTczYjBmMDFjYTc0NDI0NGM0NDYyY2ZlMzczNjNiNThhNmFkZTkzZTFmIn0.WNrLQIK5giGB4bqWmEaaoOxl0nkljv_eM7NMRGwCp9w
HTTP/1.1 200 OK 
background_CH3.js:2413 Content-Type: application/x-msdownload
background_CH3.js:2413 Content-Length: 29893021
background_CH3.js:2413 Connection: keep-alive
background_CH3.js:2413 Server: nginx/1.12.2
background_CH3.js:2413 Date: Wed, 28 Nov 2018 10:06:42 GMT
background_CH3.js:2413 Content-Transfer-Encoding: binary
background_CH3.js:2413 **Content-Encoding: none**
background_CH3.js:2413 Cache-Control: private, no-transform, no-store
background_CH3.js:2413 Allow: GET, HEAD
background_CH3.js:2413 Content-Disposition: attachment
background_CH3.js:2413 X-Revision: 01538850f79b561527c926f637728b710ceec468
background_CH3.js:2413 X-Transfer-Id: 25de132ff624fecd7f71fab21b2b99a920181125060802
background_CH3.js:2413 Accept-Ranges: bytes
background_CH3.js:2413 X-Fast-Send-Dispatch: hijack
background_CH3.js:2413 X-Cache: Miss from cloudfront
background_CH3.js:2413 Via: 1.1 5d40d4ac7c3a1e18748166636540091f.cloudfront.net (CloudFront)
background_CH3.js:2413 X-Amz-Cf-Id: PpQu-uEUcEwhC9ZCyZLELmrlkiuomonEvT5ShUynCp6I0Nh4RIXhkA==
background_CH3.js:2291

**Comment by bagder** [comment]
@southernedge so can you reproduce this issue with a recent version of the curl command line tool? If so, how? If you're using libcurl to reproduce, then please show us a small source code that reproduces it (so that we understand what options you use etc) and show us your `curl_version()` output!

**Comment by southernedge** [comment]
I would show you everything with my pleasure, but as I wrote above I cannot reanimate libcurl.dll of 7.62

> Confusion occurred. I can not download a working library from
> Windows 32 bit 7.62.0 binary Stefan Kanthak
> Windows 32 bit 7.62.0 binary Viktor Szakats
> libcurl.exe gives crash.
> libcurl.dll returns error ERROR_INVALID_ADDRESS 487L

:( I'm so sorry

**Comment by bagder** [comment]
Repeating that isn't really driving this issue forward. You keep saying this is a bug for you and we can't reproduce.

On Windows you're best off building libcurl yourself for use with your application and you can easily do that. Or you can tell us which other libcurl version (7.59.0 or later) that you use that shows this problem. Your initial comment claims you used 7.62.0 while your later comments says you can't use it. It is inconsistent.

If you're using something older than 7.59.0 then this is just a duplicate of #2298.

**Comment by southernedge** [comment]
Sorry about 7.62. it's my mistake. I have several versions and rearranging them among themselves, I made a mistake.
curl_version=libcurl/7.58.0 WinSSL zlib/1.2.11
7.58 returns CURLE_BAD_CONTENT_ENCODING
Unfortunately I do not have a later version then 7.58, which I could test without extra effort.

**Comment by bagder** [comment]
Then I consider this a duplicate and we can close it, thanks for reporting! This header works fine in recent versions, and will also be tested so via #3317.
