### ISSUE TITLE
do not support ipv6  with zone index

### ISSUE THREAD

**Issue by tonystz** [curl/curl#3319]
### I did this
$curl -v  https://[fe80::250:56ff:fea7:da15%25eth3]/
*Closing connection -1
curl: (3) URL using bad/illegal format or missing URL

I have applied the **patch** 
 https://github.com/curl/curl/issues/3218

### I DO NOT expected the following
curl: (3) URL using bad/illegal format or missing URL

### curl/libcurl version

[curl -V output]
curl 7.62.0 (x86_64-redhat-linux-gnu) libcurl/7.62.0 OpenSSL/1.0.1e zlib/1.2.7 c-ares/1.13.0 libssh2/1.4.3
Release-Date: 2018-10-31

### operating system
centos 7

**Comment by tonystz** [comment]
It seems the code in the API parse_port() of file urlapi.c should be modified (add "th" in scan set)like this:

`if(1 == sscanf(hostname, "[%*45[0123456789abcdethfABCDEF:.%%]%c%n",&endbracket, &len)){`

**Comment by jzakrzewski** [comment]
I don't think the "th" would be enough. I only on my current machine have "eno1", "docker0", and "vboxnet0" interfaces...
