### ISSUE TITLE
Curl with NTLM option and POST gives HTTP error 411

### ISSUE THREAD

**Issue by dgtlrift** [curl/curl#3326]
### I did this
curl  v -D- -u user:pass --ntlm -X POST http://ourTFSserver/tfs/DefaultCollection/_apis/wit/workitems/yadaYadaYada?api-version=4.1&...

### I expected the following
Some rest output

instead, I got

```
* STATE: INIT => CONNECT handle 0x600057a20; line 1404 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x600057a20; line 1440 (connection #0)
*   Trying 10.1.160.239...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x600057a20; line 1521 (connection #0)
* Connected to ourTFSserver (10.1.160.239) port 8080 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057a20; line 1573 (connection #0)
* Marked for [keep alive]: HTTP default
* STATE: SENDPROTOCONNECT => DO handle 0x600057a20; line 1591 (connection #0)
* Server auth using NTLM with user 'user'
> POST /tfs/DefaultCollection/_apis/wit/workitems/yadaYadaYada?api-version=4.1&... HTTP/1.1
> Host: ourTFSserver:8080
> Authorization: NTLM TlRMTVNTUAABanonizedAAAAAAA=
> User-Agent: curl/7.59.0
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600057a20; line 1670 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057a20; line 1795 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057a20; line 1811 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 411 Length Required
HTTP/1.1 411 Length Required
< Content-Type: text/html; charset=us-ascii
Content-Type: text/html; charset=us-ascii
* Server Microsoft-HTTPAPI/2.0 is not blacklisted
< Server: Microsoft-HTTPAPI/2.0
Server: Microsoft-HTTPAPI/2.0
< Date: Thu, 29 Nov 2018 15:51:43 GMT
Date: Thu, 29 Nov 2018 15:51:43 GMT
* Marked for [closure]: Connection: close used
< Connection: close
Connection: close
< Content-Length: 344
Content-Length: 344
<
Length Required
Length Required
HTTP Error 411. The request must be chunked or have a content length.
* STATE: PERFORM => DONE handle 0x600057a20; line 1980 (connection #0)
* multi_done
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
--
```

### curl/libcurl version

```
curl 7.59.0 (x86_64-unknown-cygwin) libcurl/7.59.0 OpenSSL/1.0.2p zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.7.0 nghttp2/1.31.0                          Release-Date: 2018-03-14                                                                                                                                                         Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp                                                   Features: AsynchDNS Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink
--
```

### operating system

CYGWIN_NT-6.1 on Win 8 x86_64
--

### Workaround
curl  v -D- -u user:pass --ntlm -FContent-Length=0 -X POST http://ourTFSserver/tfs/DefaultCollection/_apis/wit/workitems/yadaYadaYada?api-version=4.1&...
included -FContent-Length=0  on command line and initated the serives above HTTP server side

Is this related to the NTLM flag?  It looks like https://github.com/curl/curl/pull/1242 should have fixed this issue before the release I'm using.

**Comment by bagder** [comment]
You basically ask for this request by using `-X POST` (which we repeatedly and often argue against using). You should probably rather do `-d ""` if you really want a zero length POST.

**Comment by bagder** [comment]
No response and appear to mostly be a user error.

**Comment by bagder** [comment]
Sure, the Internet is full of these bad command lines as [I've blogged about before](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/).

The verbose output already points out this out and I don't think we can bump that into a warning on the console. I don't know what else we can do.

Functionality wise, I've been thinking about adding support for another value for `CURLOPT_ FOLLOWLOCATION` that if set will make curl override the user-specified request in the redirect for the response code says so. That could possibly be what the command line tool should use then. A slightly change in behavior, but possibly it will *fix* more problems than it will create...
