### ISSUE TITLE
Timeout for response for invalid server IP is very slow.

### ISSUE THREAD

**Issue by HimanshuNandu** [curl/curl#3332]
When i try to enter invalid server IP, curl_easy_perform returns error code CURL_COULDNT_CONNECT,that's good. But the response for this error is very slow everytime, it takes more than 20 seconds.

I am not setting or using CURLOPT_CONNECTTIMEOUT option, Is this mandatory? I am using CURLOPT_TIMEOUT option set to 30 seconds.

Should not the connection error repsonse return immediately for invalid server IP.

Curl/libcurl version used is curl-7.48.0

Operating system: Windows 10

**Comment by HimanshuNandu** [comment]
@bagder : Is something wrong with the implementation or the library?

**Comment by bagder** [comment]
I think that rather implies that something is funny in your network that makes it take a very long time for the stack to discover this fact and report it to curl. curl doesn't wait for this kind of response, it'll return a failure back immediately when a failure is detected. I've never seen a failure take any extra time like this.

Can we reproduce this with curl against a public URL somehow?

If you run wireshark and check the TCP SYN attempt, do you see the failed connect immediately over the network?

Also note that 7.48.0 is getting a bit old by now... (but I don't think we've ever had a bug that would appear like this)

**Comment by HimanshuNandu** [comment]
I tried using command line approach instead of running it from my code base.

Command line option i used:
curld --trace-ascii d.txt --trace-time http://10.84.119.140/login.jsp

I see below log file
00:40:29.859000 == Info: STATE: INIT => CONNECT handle 0xbd68e0; line 1108 (connection #-5000) 
00:40:29.859000 == Info: Added connection 0. The cache now contains 1 members
00:40:29.875000 == Info:   Trying 10.84.119.140...
00:40:29.875000 == Info: STATE: CONNECT => WAITCONNECT handle 0xbd68e0; line 1161 (connection #0) 
00:40:51.062000 == Info: connect to 10.84.119.140 port 80 failed: Timed out
00:40:51.062000 == Info: Failed to connect to 10.84.119.140 port 80: Timed out
00:40:51.062000 == Info: Closing connection 0
00:40:51.062000 == Info: The cache now contains 0 members

if you can see the delay of 21.1s is consistent for all invalid server calls

**Comment by HimanshuNandu** [comment]
with or without proxy, does not make a difference

**Comment by HimanshuNandu** [comment]
@bagder : Any comments or suggestions?
This used to work before when we were using boost with openssl.
Now we replaced that with libcurl and winssl.

**Comment by bagder** [comment]
What happens when you `telnet 10.84.119.140 443` ?

> TCP re transmission packets

The mere fact that it retransmits packets means that it isn't an "invalid" address. It's an address to which it tries to make a connection but there's no response and then I believe 21 seconds is the standard  timeout after three resends.

> This used to work before when we were using boost with openssl

How? If the TCP stack just tries in vain to connect for a while, the only way to cancel that before 21 seconds is to have a timeout that gives up earlier.

**Comment by HimanshuNandu** [comment]
i was wrong, I retested the same with boost and it behaves the same. Thanks Daniel..
We can close this issue as no issue
