### ISSUE TITLE
CURL port 80 problem

### ISSUE THREAD

**Issue by davidhay45** [curl/curl#3338]
### I did this

curl http://wsprnet.org/post

### I expected the following

<html>
<body>
Nothing to do.<br>Processing took 0 milliseconds.<br>
Old database interface is now <a href='olddb'>here</a>.
</body>
</html>

### I got the following

rp-f0575e:~# curl http://wsprnet.org/post
curl: (7) Failed to connect to wsprnet.org port 80: Operation timed out

### curl/libcurl version

[curl -V output]

rp-f0575e:~# curl -V
curl 7.61.1 (armv6-alpine-linux-musleabihf) libcurl/7.61.1 LibreSSL/2.0.0 zlib/1.2.11 libssh2/1.8.0 nghttp2/1.32.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

### operating system

see above

I am using a Redpitaya running Alpine Linux.  When it is connected directly to my broadband router it works correctly but when I connect to a wifi extender ethernet port I get the port 80 issue as above.  

nmap gives:

rp-f0575e:~# nmap -p80 wsprnet.org
Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-03 14:21 UTC
Nmap scan report for wsprnet.org (50.235.87.130)
Host is up (0.096s latency).

PORT   STATE SERVICE
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 1.35 seconds

So although the port is open, curl will not connect.

I have used --trace but that gives no more information:

== Info:   Trying 50.235.87.130...
== Info: TCP_NODELAY set
== Info: connect to 50.235.87.130 port 80 failed: Operation timed out
== Info: Failed to connect to wsprnet.org port 80: Operation timed out
== Info: Closing connection 0

see also nmap to my router:

rp-f0575e:~# nmap -p1-1023 192.168.1.254
Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-03 14:49 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 1.23 seconds

rp-f0575e:~# nmap -Pn -p1-1023 192.168.1.254
Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-03 14:53 UTC
Nmap done: 1 IP address (0 hosts up) scanned in 1.21 seconds

When I run curl on my Windows 10 machine connected in the same way it works correctly.

Any ideas anyone?  Or where else to ask for help?

**Comment by bagder** [comment]
> When it is connected directly to my broadband router it works correctly but when I connect to a wifi extender ethernet port I get the port 80 issue as above

It seems unlikely that curl would work differently depending on your extender being there or not, why I would suggest the problem is in your network environment.

**Comment by davidhay45** [comment]
I appreciate you having taken the time to reply.

This is really weird.  The wifi extender support people confirm that the extender cannot block any ports and I have confirmed that port 80 is “open” using nmap.  The address resolution is working so it looks like there is no issue with dhcp.  I am not a linux expert but as far as I can see the route parameters are the same on the client irrespective of the connection being via the wifi extender or not.

In normal operation curl establishes a socket connection from the client to port 80 on the server but is that just the initial port, does it then negotiate a data transfer socket via a different port?

Where else can I ask this question?

Thanks

David

**Comment by jay** [comment]
Use Wireshark and set a capture filter for `host wsprnet.org`

**Comment by davidhay45** [comment]
I had to rename it .log as the system would not accept a .pcapng

[output_wifi.pcapng.log](https://github.com/curl/curl/files/2653807/output_wifi.pcapng.log)

I tried a power line extender in place of the wifi extender and all works ok, albeit slowly.

**Comment by davidhay45** [comment]
It now looks like it was a hardware fault that was solid and has now become just flaky.

Thanks for the suggestion to use wireshark, it helped a lot and if/when it fails again I will know how to diagnose it.


![wireshark1](https://user-images.githubusercontent.com/33960957/49637388-248c0b80-f9fd-11e8-80a5-b634b171a246.png)
