### ISSUE TITLE
NTLM requires a downgrade to HTTP/1.1

### ISSUE THREAD

**Issue by dscho** [curl/curl#3341]
### I did this

```sh
git clone https://tfs.example/Collection/_git/Project/
```

where `tfs.example` refers to an NTLM-authenticated, self-hosted Team Foundation Service.

### I expected the following

I expected a successful clone, but it showed this instead:

```
Authentication failed for 'https://tfs.example/Collection/_git/Project/'
```

### curl/libcurl version

```
curl 7.62.0 (x86_64-w64-mingw32) libcurl/7.62.0 OpenSSL/1.1.1a (WinSSL) zlib/1.2 .11 libidn2/2.0.5 nghttp2/1.35.0                                                 Release-Date: 2018-10-31                                                         Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s  rtsp smtp smtps telnet tftp                                                     Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SR P HTTP2 HTTPS-proxy MultiSSL Metalink
```

### operating system

Windows

### Additional information

This issue was reported originally in https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/812. I started [talking about it in a vaguely related PR](https://github.com/curl/curl/pull/2709#issuecomment-444080768).

Apparently [NTLM is incompatible with HTTP/2](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#when-is-http2-not-supported).

However, with the new default in libcurl 7.62.0, it seems that we're upgrading to HTTP/2 before realizing that we cannot authenticate via NTLM, and then the connection is closed without success.

Please note that this happens with the OpenSSL backend, but apparently not with the Secure Channel backend (which cURL calls "winssl").

**Comment by dscho** [comment]
So I did some digging into the question why the "winssl" backend works: it is simply because Git for Windows' version of libcurl is compiled using MINGW, and therefore the `SecApplicationProtocolNegotiationExt_ALPN` symbol is unavailable (read: the Secure Channel backend is compiled without ALPN support).

**Comment by dscho** [comment]
After trying for hours to find a way to downgrade a connection to HTTP/1.1, I conclude that there is none, and that's even by design (judging by reading the comment https://bugs.chromium.org/p/chromium/issues/detail?id=685741#c9 among other things on the web).

So it seems that we should somehow detect the error condition `HTTP_1_1_REQUIRED` and fall back to trying again, this time preventing HTTP/2 to be used?

**Comment by bagder** [comment]
> we should somehow detect the error condition HTTP_1_1_REQUIRED and fall back to trying again, this time preventing HTTP/2 to be used?

Yes, that sounds exactly what we should do. It could be handled internally basically like a redirect with just some flag set to alter behavior in the next attempt.

Of course, an application that *knows* it will use NTLM could also forcibly ask for HTTP/1 right away.

**Comment by dscho** [comment]
> It could be handled internally basically like a redirect with just some flag set to alter behavior in the next attempt.

Do you have any tips/pointers how I could implement that (e.g. commits to imitate)?

> Of course, an application that _knows_ it will use NTLM could also forcibly ask for HTTP/1 right away.

That's my plan, for now. Do note, though, that Git does not know which authentication will be used. It could be NTLM, it could be Basic. To accommodate for NTLM, we'll force Git for Windows to use HTTP/1.1 *always* for now, until I get the better fix into cURL.

**Comment by bagder** [comment]
I think by calling `Curl_follow()` with ` FOLLOW_RETRY` here:

https://github.com/curl/curl/blob/027d66e5f1b6946257ecf3bca2d4983579e461cf/lib/multi.c#L2003

`retry` would need to get set prior to that (when h2 was used with `HTTP_1_1_REQUIRED` returned) to signal that it isn't an actual redirect.

**Comment by dscho** [comment]
@bagder sorry it took me so long. For some reason, this approach did not really work for me, and I realized only late in the game that I need to call `connclose()`; otherwise no reconnect will be forced.

Here is the Pull Request: https://github.com/curl/curl/pull/3345
