### ISSUE TITLE
ossl_connect_common crash

### ISSUE THREAD

**Issue by linyu92** [curl/curl#3357]
libsystem_pthread.dylib    0x1a696be6    __pthread_rwlock_lock + 22
mobile    0xc5d113    _CRYPTO_THREAD_read_lock + 9
mobile    0xc5d113    _CRYPTO_THREAD_read_lock + 9
mobile    0xc21127    _ERR_error_string_n + 111
mobile    0xc9fb11    _ossl_connect_common + 6073
mobile    0xca10d1    _Curl_ssl_connect_nonblocking + 75
mobile    0xc78155    _https_connecting + 15
mobile    0xc89729    _multi_runsingle + 989
mobile    0xc892a7    _curl_multi_perform + 95
mobile    0xc86033    _curl_easy_perform + 217
mobile    0xbd3575    reportsdk::HttpRequest::start() (httprequest.cpp:294)

### I did this
a http post  request

### I expected the following
every right~ but crash indeed

### curl/libcurl version
curl 7.62.0 with openssl 1.1.1

### operating system
iOS10.1.1 iphone5 armv7

**Comment by bagder** [comment]
Can you please also provide a minimal example source code for an application that reproduces this issue?

**Comment by linyu92** [comment]
I am very sorry, this question is occasional for my app. Can you find a clue from the stack?

**Comment by bagder** [comment]
No, it doesn't give enough information to do anything or make any intelligent conclusions.
