### ISSUE TITLE
curl fails without port number after IPv6 numerical address

### ISSUE THREAD

**Issue by GitYuanQu** [curl/curl#3379]
I notice the improve from 7.62.0 at file Urlapi.c, if they judge user has not input port after ipv6 separator ']', it will return as error. and I check the newest release source code 7.63.0, it has same behavior. the source code as below:
### 7.62.0
~~~c
static CURLUcode parse_port(struct Curl_URL *u, char *hostname)
...
portptr = &hostname[len];
    if (*portptr != ':')
      return CURLUE_MALFORMED_INPUT;
~~~
### 7.63.0
~~~c
static CURLUcode parse_port(struct Curl_URL *u, char *hostname)
...
/* this is a RFC2732-style specified IP-address */
    if(portptr && *portptr) {
      if(*portptr != ':')
        return CURLUE_MALFORMED_INPUT;
    }
~~~

I try to upload file to sftp and ftp with ipv4/v6, for ipv4, no matter I add the port or not, the file will upload to sftp/ftp server success, but for ipv6, only succcess in I add the port.

I expected if I did not add port for ipv6, it will add default port directly.

### curl/libcurl version
7.63.0

[curl -V output]

### operating system
ALL

**Comment by GitYuanQu** [comment]
Please handler this or give me reply as soon as possible, thanks.

**Comment by bagder** [comment]
I believe this is already fixed in master. Can you verify?

**Comment by GitYuanQu** [comment]
yeah, I could verify this if you give me your beta release or new release.

**Comment by bagder** [comment]
The latest code is always available here: https://github.com/curl/curl

And packaged in daily snapshots here: https://curl.haxx.se/snapshots/

**Comment by GitYuanQu** [comment]
sorry for reply this so late..
I don't think you have solve this issue, I just read the new code and found that the segment dose not changed any:
=======================
UNITTEST CURLUcode Curl_parse_port(struct Curl_URL *u, char *hostname)
...
/* this is a RFC2732-style specified IP-address */
    if(portptr && *portptr) {
      if(*portptr != ':')
        return CURLUE_MALFORMED_INPUT;
    }
...
=======================
below is my case with curl command:
[srcbuilder@rhel6x64-builder src]$ ./curl --version
curl 7.63.0-20181217 (x86_64-pc-linux-gnu) libcurl/7.63.0-20181217 OpenSSL/1.0.1e zlib/1.2.3
Release-Date: 2018-12-17
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy

[srcbuilder@rhel6x64-builder src]$ ./curl --url sftp://root:********@[2002:97b:c2bb:830:10:240:196:14]/home ../configure
curl: (1) Protocol "sftp" not supported or disabled in libcurl
curl: (6) Could not resolve host: ..

**Comment by GitYuanQu** [comment]
upper case is error caused by my compile issue, through retest, it can work with new code. so shall we need update our curl to 7.64.0 or later? and when will your plan to release a new build to fix this issue? could take it more quick?

**Comment by bagder** [comment]
Thanks for confirming that this issue is fixed already.

The coming 7.64.0 release is planned for February 6, 2019.

**Comment by GitYuanQu** [comment]
Hi Daniel:

It's a bad news that your plan time is so late for us, could you move it more earlier?

**Comment by bagder** [comment]
Sorry. I don't consider this bug(-fix) to be important enough to adjust the release schedule. If you are in a hurry you can always patch your own build or downgrade to a working version until the official release comes.
