### ISSUE TITLE
`curl -JO` appends data to an existing output file

### ISSUE THREAD

**Issue by kdudka** [curl/curl#3380]
### I did this
```
curl -JO --location https://github.com/curl/curl/releases/download/curl-7_63_0/curl-7.63.0.tar.xz.asc
curl -JO --location https://github.com/curl/curl/releases/download/curl-7_63_0/curl-7.63.0.tar.xz.asc
```

### I expected the following
I expected `curl-7.63.0.tar.xz.asc` to be written only once.  However, it was written twice and concatenated together.  Note that it is not needed to use `--location` to trigger the bug.  It looks like the fix in #2813 was incomplete.  Originally reported at https://bugzilla.redhat.com/1658574

### curl/libcurl version
`curl-7_63_0-13-g9e6518481`

[curl -V output]
```
curl 7.63.0-DEV (x86_64-pc-linux-gnu) libcurl/7.63.0-DEV OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.7 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.35.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system
Linux

**Comment by bagder** [comment]
grrr, typo closed the wrong issue!
