### ISSUE TITLE
Digest auth does not send "Authorization" header

### ISSUE THREAD

**Issue by GauthamBanasandra** [curl/curl#3385]
I'm trying to make an HTTP request with Digest auth as shown in the `Everything-curl` book - https://ec.haxx.se/http-auth.html
### I did this
```
$ curl --digest --user username:password http://localhost:9090 --verbose
* Rebuilt URL to: http://localhost:9090/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9090 (#0)
* Server auth using Digest with user 'username'
> GET / HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 18 Dec 2018 05:23:36 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
```
Here's a simple HTTP server in Golang that I used - https://gist.github.com/GauthamBanasandra/8d6f27e25a4bb1a805e11716aa4bb66c . It just prints all the headers in the incoming HTTP request.

### I expected the following header to be sent
```
Authorization: Digest username="username", ...
```
But the server didn't receive it. Here are the headers received by the server -
```
User-Agent: [curl/7.54.0]
Accept: [*/*]
```
### curl/libcurl version
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 

### operating system
macOS Sierra
Version 10.12.6

**Comment by bagder** [comment]
That's totally expected.

When using the **Digest** authentication, there can be no such header in the first outgoing request. Digest is a challenge-response kind of auth and it first needs a 401 (or 407) response back (containing the necessary `nonce`), and only then can curl send a `Authorization:` header.

**Comment by GauthamBanasandra** [comment]
Thanks. I changed the server code to respond 401 with the necessary `WWW-Authenticate Digest` headers - https://gist.github.com/GauthamBanasandra/8d6f27e25a4bb1a805e11716aa4bb66c#file-print-headers-401-go
But I see that curl doesn't automatically make another request -
```
$ curl --digest --user username:password http://localhost:9090 --verbose
* Rebuilt URL to: http://localhost:9090/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9090 (#0)
* Server auth using Digest with user 'username'
> GET / HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Tue, 18 Dec 2018 10:08:42 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
```
If I try to make another request on my own, it would be treated as a new request as it won't have the previous curl handle.
Am I missing something here?

**Comment by dfandrich** [comment]
That log doesn't show any WWW-Authenticate: headers.

**Comment by GauthamBanasandra** [comment]
I was able to figure out where the problem was. I find myself to be a victim Golang's notorious idiosyncrasies.
According to this - https://stackoverflow.com/questions/39427544/golang-http-response-headers-being-removed , I'm supposed to call `WriteHeader()` at the end. It is working fine after doing so.
Thanks and sorry for the trouble.
