### ISSUE TITLE
Memory leak in wolfssl in threaded function

### ISSUE THREAD

**Issue by kirill-782** [curl/curl#3387]
Having this code

```
	while ( true )
	{
		boost::thread( [] {
			string error;
			SendVKMessage( error, "", 0, "" );
		} );

		MILLISLEEP( 1000 );

bool SendVKMessage( string & error, string text, int32_t to, string accessToken )
{
	string HTTPAnswer;
	curl_mime *form = NULL;
	curl_mimepart *field = NULL;
	CURL *ch = curl_easy_init( );
	char CURLError[CURL_ERROR_SIZE];

	form = curl_mime_init( ch );

	field = curl_mime_addpart( form );
	curl_mime_name( field, "access_token" );
	curl_mime_data( field, accessToken.c_str( ), CURL_ZERO_TERMINATED );

	string toid = UTIL_ToString( to );

	field = curl_mime_addpart( form );
	curl_mime_name( field, "peer_id" );
	curl_mime_data( field, toid.c_str( ), CURL_ZERO_TERMINATED );

	field = curl_mime_addpart( form );
	curl_mime_name( field, "v" );
	curl_mime_data( field, "5.85", CURL_ZERO_TERMINATED );


	field = curl_mime_addpart( form );
	curl_mime_name( field, "message" );
	curl_mime_data( field, text.c_str( ), CURL_ZERO_TERMINATED );

	curl_easy_setopt( ch, CURLOPT_URL, "https://api.vk.com/method/messages.send" );
	curl_easy_setopt( ch, CURLOPT_CAINFO, "cacert.pem" );
	curl_easy_setopt( ch, CURLOPT_ERRORBUFFER, CURLError );
	curl_easy_setopt( ch, CURLOPT_MIMEPOST, form );
	curl_easy_setopt( ch, CURLOPT_WRITEFUNCTION, &writer );
	curl_easy_setopt( ch, CURLOPT_WRITEDATA, &HTTPAnswer );

	CURLcode result = curl_easy_perform( ch );
	curl_mime_free( form );
	curl_easy_cleanup( ch );

	if ( result != CURLcode::CURLE_OK )
	{
		error = string( CURLError );
		return false;
	}

        return true;
}
```

if not use boost thread, memory leak not repeated.

https://irinabot.ru/curlleak.txt

curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 wolfSSL/3.4.8 zlib/1.2.8
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSL libz UnixSockets

**Comment by bagder** [comment]
I can reproduce as well when using curl + WolfSSL + threads. It seems we might need some more cleanups for WolfSSL ?

Here's a little pthread-using example showing the same kind of leak, and I saw it using WolfSSL 3.14.0:
[wolfssl.c](https://github.com/curl/curl/files/2693876/wolfssl.c.txt)

**Comment by dgarske** [comment]
Thanks @bagder and @kirill-782. These leaks are from the wolfCrypt fixed point ECC cache when `FP_ECC` is defined. 

You can either:
1. Disable the fixed point ECC cache with `./configure --disable-fpecc` or `#undef FP_ECC` in your user_settings.h.

2. Add a cleanup call to make sure these get free'd. The FP cache is free'd when one of the following is called: `wolfSSL_Cleanup();` or `wolfCrypt_Cleanup();` or `wc_ecc_fp_free();`. There is currently no openssl compatibility API for SSL_Cleanup, so this will need to be added into libcurl.

Pushed a patch to #3395.

Thanks,
David Garske, wolfSSL

**Comment by bagder** [comment]
Fixed in #3395 and already landed!

**Comment by kirill-782** [comment]
Or am I doing something wrong. Or problemma remained. Or without --disable-fpecc fixes do not work

**Comment by dgarske** [comment]
@kirill-782 : The wolfSSL ECC Fixed Point cache can use either thread local storage or a mutex (assuming threading is enabled). If you are using THREAD_LS (HAVE_THREAD_LS) then you must call `wc_ecc_fp_free();` when each thread exits. Otherwise you can disable thread local storage using `./configure CFLAGS="-DNO_THREAD_LS"` or `#define NO_THREAD_LS`. Then it will use a single shared global for ECC cache with mutex. Or you can disable threading and build in single threaded mode with `./configure --enable-singlethreaded` or `#define SINGLE_THREADED`.

The ECC code that provides the ECC Fixed Point cache is here:
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L7096

Thanks,
David Garske, wolfSSL

**Comment by kirill-782** [comment]
That is, to call wc_ecc_fp_free (); I have to add a title from wolfssl and not only to it, but also to my application.
