### ISSUE TITLE
FTP and NoBody not working properly

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#3396]
When we a download of a file via FTP URL with option set to nobody, we see output coming with:

Content-Length: 11582
Accept-ranges: bytes

This is debug messages and data:

220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-Local time is now 14:49. Server port: 21.
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 30 minutes of inactivity.
331 User xxx OK. Password required
230 OK. Current restricted directory is /
257 "/" is your current location
200 TYPE is now 8-bit binary
213 11582
Content-Length: 11582
350 Restarting at 0
Accept-ranges: bytes

Full Log:

 Trying xxx...
TCP_NODELAY set
 Trying xxx...
TCP_NODELAY set
Connected to ftp.xxx.de (xxx) port 21 (#0)
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-Local time is now 14:49. Server port: 21.
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 30 minutes of inactivity.
USER xxx
331 User xxx OK. Password required
PASS xxx
230 OK. Current restricted directory is /
PWD
257 "/" is your current location
Entry path is '/'
TYPE I
ftp_perform ends with SECONDARY: 0
200 TYPE is now 8-bit binary
SIZE xxx.jpg
213 11582
REST 0
350 Restarting at 0
Remembering we are in dir ""
Connection #0 to host ftp.xxx.de left intact

With command line tool I see the same:

curl -I -v -u xxx -o test.txt ftp://ftp.xxx.de/backup.log

We even get this:

Last-Modified: Fri, 27 Jul 2018 08:53:08 GMT
Content-Length: 6563628
Accept-ranges: bytes

This used to work in older version.

**Comment by bagder** [comment]
I don't understand. What is the problem? What happened that you didn't expect to happen?

**Comment by bagder** [comment]
No response, closing.
