### ISSUE TITLE
imap download broken

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#3397]
Did the imap download break in last releases?

To test without my own software, I just build a fresh copy of the command line tool:

curl 7.63.0 (x86_64-apple-darwin17.7.0) libcurl/7.63.0 OpenSSL/1.1.0e zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

A query with imap://imap.macsw.de/INBOX/ finds the list of mailboxes.

A query with --request "FETCH 1:* FLAGS" returns:

A004 FETCH 1:* FLAGS
< * 1 FETCH (FLAGS (\Seen))
* 1 FETCH (FLAGS (\Seen))
< * 2 FETCH (FLAGS (\Seen))
* 2 FETCH (FLAGS (\Seen))
< * 3 FETCH (FLAGS (\Seen))
* 3 FETCH (FLAGS (\Seen))
< * 4 FETCH (FLAGS (\Seen))
* 4 FETCH (FLAGS (\Seen))

Now the call with "imap://imap.macsw.de/INBOX/;UID=1" gives error 78.

This is output:

< A002 OK Logged in
A003 SELECT INBOX
< * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
< * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
< * 4 EXISTS
< * 0 RECENT
< * OK [UIDVALIDITY 1273175154] UIDs valid
< * OK [UIDNEXT 107] Predicted next UID
< * OK [HIGHESTMODSEQ 41] Highest
< A003 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
A004 UID FETCH 1 BODY[]
< A004 OK Fetch completed (0.001 + 0.000 secs).
A005 LOGOUT
< * BYE Logging out
< A005 OK Logout completed (0.001 + 0.000 secs).
* Closing connection 0
curl: (78) Remote file not found

Can anyone confirm?
Is this a bug?
Or did something change?

**Comment by MonkeybreadSoftware** [comment]
In libcurl/7.61.0 and libcurl/7.61.1 this seems to work well.
libcurl/7.62.0  is broken.

**Comment by bagder** [comment]
Is this due to the same reason as #3398 ?

**Comment by MonkeybreadSoftware** [comment]
No. This is simply the question what text goes to output and what to debug messages.
Similar problem with FTP here: https://github.com/curl/curl/issues/3396

**Comment by MonkeybreadSoftware** [comment]
I see the data via header callback:

> * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
> * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN
> A001 OK Pre-login capabilities listed, post-login capabilities have more.
> * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY SPECIAL-USE COMPRESS=DEFLATE QUOTA
> A002 OK Logged in
> * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
> * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
> * 4 EXISTS
> * 0 RECENT
> * OK [UIDVALIDITY 1273175154] UIDs valid
> * OK [UIDNEXT 107] Predicted next UID
> * OK [HIGHESTMODSEQ 41] Highest
> A003 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
> * 1 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
> Message-Id: <6F3B718F-8427-4EFB-B291-106A8ABFC1AA@monkeybreadsoftware.de>
> 
> )
> * 2 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {75}
> Message-Id: <20180513143045.88FCF186080F@xxx>
> 
> )
> * 3 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
> Message-Id: <CD138D19-86B0-4EC6-921B-0D7CB0C861A9@monkeybreadsoftware.de>
> 
> )
> * 4 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {88}
> Message-ID: <620169242.91311542275549379@xxx>
> 
> )
> A004 OK Fetch completed (0.001 + 0.000 secs).
> 

but the middle part used to be in output:

> * 1 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
> Message-Id: <6F3B718F-8427-4EFB-B291-106A8ABFC1AA@monkeybreadsoftware.de>
> 
> )
> * 2 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {75}
> Message-Id: <20180513143045.88FCF186080F@xxx>
> 
> )
> * 3 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
> Message-Id: <CD138D19-86B0-4EC6-921B-0D7CB0C861A9@monkeybreadsoftware.de>
> 
> )
> * 4 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {88}
> Message-ID: <620169242.91311542275549379@xxx>
> 
> )

Why did that change?

**Comment by MonkeybreadSoftware** [comment]
The workaround would be to take the text from header and return it as output, so our existing application can keep working.

**Comment by MonkeybreadSoftware** [comment]
Okay, we'll adapt and take info from debug log.
