### ISSUE TITLE
imap fetch broken

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#3398]
./curl --verbose --url "imap://imap.macsw.de/INBOX/" -u xxx:yyy --request "FETCH 1:* (FLAGS BODY[HEADER.FIELDS (Message-Id)])" --output test.txt

When I run this the output of fetch goes to debug messages and not to the file.

The file only contains:

* 1 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
* 2 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {75}
* 3 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
* 4 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {88}

But the debug log shows the message IDs:

A004 FETCH 1:* (FLAGS BODY[HEADER.FIELDS (Message-Id)])
< * 1 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
< Message-Id: <6F3B718F-8427-4EFB-B291-106A8ABFC1AA@monkeybreadsoftware.de>
< 
< )
< * 2 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {75}
< Message-Id: <20180513143045.88FCF186080F@quake.server.clever-zoeger.de>
< 
< )
< * 3 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {77}
< Message-Id: <CD138D19-86B0-4EC6-921B-0D7CB0C861A9@monkeybreadsoftware.de>
< 
< )
< * 4 FETCH (FLAGS (\Seen) BODY[HEADER.FIELDS (MESSAGE-ID)] {88}
< Message-ID: <620169242.91311542275549379@filemaker-jc-t-wa02.dynphx1.jivehosted.com>
< 
< )
< A004 OK Fetch completed (0.001 + 0.000 secs).

Does anyone know why this output goes to log instead of file?

We see this in curl command line tool and our own software using libcurl.

curl 7.63.0 (x86_64-apple-darwin17.7.0) libcurl/7.63.0 OpenSSL/1.1.0e zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

**Comment by MonkeybreadSoftware** [comment]
In libcurl/7.61.1 this used to work correctly.
But in libcurl/7.62.0, I get error 78 for loading email.

**Comment by MonkeybreadSoftware** [comment]
Fix is to use MAILINDEX= instead of UID= in the URL as internally in curl.
Bad, as we have to update lots of projects.

**Comment by danielgustafsson** [comment]
For reference, this is the relevant discussion on this #2789

**Comment by bagder** [comment]
This topic has been discussed several times outside of that issue as well over the years. The unfortunate truth is that we used the URL wrongly, or rather we issued the wrong set of IMAP commands based on the contents of the URL and when we fixed the previous error, we then consequently made old applications that were relying on the old (wrong) behavior possibly break. The `MAILINDEX` thing is at least a fairly easy way to get back to the former behavior.

**Comment by MonkeybreadSoftware** [comment]
I got a workaround. In case of error 78, we replace UID with MAILINDEX to fix transparently:


```
CURLcode curl_easy_performX(CURL *curl)
{
	CURLcode e = _curl_easy_perform(curl);
	
	if (e == CURLE_REMOTE_FILE_NOT_FOUND)
	{
		char *effectiveURL = nil;
		CURLcode e2 = _curl_easy_getinfo(curl, CURLINFO_EFFECTIVE_URL, &effectiveURL);
		DebugMessage("curl_easy_getinfo returns", e2);
		
		if (e2 == CURLE_OK)
		{
			DebugMessage("effectiveURL", effectiveURL);
			if (effectiveURL)
			{
				if (strncasecmp(effectiveURL, "imap", 4) == 0)
				{
					// is IMAP
					const char* UID = ";UID=";
					size_t UIDlen = strlen(UID);
					const char* pos = strstr(effectiveURL, UID);
					if (pos != NULL)
					{
						// found UID, so replace with MAILINDEX
						size_t len = strlen(effectiveURL);
						char* newURL = (char*) AllocateClearMemory(len + 12);
						FreeMemoryLater(newURL);
						if (newURL)
						{
							const char* MailIndex = ";MAILINDEX=";
							size_t MailIndexLen = strlen(MailIndex);
							size_t PrefixLen = pos-effectiveURL;
							
							memcpy(newURL, effectiveURL, PrefixLen);
							memcpy(newURL + PrefixLen, ";MAILINDEX=", MailIndexLen);
							memcpy(newURL + PrefixLen+MailIndexLen, pos + UIDlen, len - PrefixLen - UIDlen);
							DebugMessage("newURL", newURL);
							
							e = _curl_easy_setopt(curl, CURLOPT_URL, newURL);
							DebugMessage("_curl_easy_setopt CURLOPT_URL returns", e);

							if (e == CURLE_OK)
							{
								e = _curl_easy_perform(curl);
							}
						}
					}
				}
			}
		}
	}
	
	return e;
}
```
