### ISSUE TITLE
Add option to save parsed headers

### ISSUE THREAD

**Issue by diekhans** [curl/curl#3404]
Enhancement request to add an option to save parsed results header and then be able to get them by header name or get the full list.

This would be easier than having to define a callback.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
