### ISSUE TITLE
Crash with WinSSL

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#3412]
### I did this

See the WinSSL autobuilds since December 23 on https://curl.haxx.se/dev/builds.html:

```
test 2043...[Disable certificate revocation checks]
../src/curl.exe --output log/curl2043.out --include --trace-ascii log/trace2043 --trace-time --ssl-no-revoke -I https://revoked.grc.com/ >log/stdout2043 2>log/stderr2043
sh: line 1: 6648 Segmentation fault
```

### I expected the following

No segmentation fault

### curl/libcurl version

Daily tarball since December 23

### operating system

Windows 10, MSYS2 shell, MinGW-w64

I'll try to have a look when I'm back from my holidays tomorrow.

**Comment by gvanem** [comment]
Verified from the cmd-line using a MSVC-built `curl.exe`.
Here:
```c
void Curl_ssl_sessionid_lock(struct connectdata *conn)
{
  if(SSLSESSION_SHARED(conn->data))
```

`conn->data == NULL`!

**Comment by danielgustafsson** [comment]
Could fb445a1e18d12f577964c9347bc5bca74b37cd08 and/or f3ce38739fa49008e36959aa8189c01ab1bad5b5 be related to this?

**Comment by MarcelRaad** [comment]
Full call stack:
```
Curl_ssl_sessionid_lock(connectdata * conn=0x000001d48f950560) Line 286
Curl_schannel_shutdown(connectdata * conn=0x000001d48f950560, int sockindex=0) Line 2017
Curl_ssl_shutdown(connectdata * conn=0x000001d48f950560, int sockindex=0) Line 560
Curl_schannel_close(connectdata * conn=0x000001d48f950560, int sockindex=0) Line 1922
Curl_ssl_close(connectdata * conn=0x000001d48f950560, int sockindex=0) Line 556
Curl_disconnect(Curl_easy * data=0x000001d48f91eef0, connectdata * conn=0x000001d48f950560, bool dead_connection=false) Line 804
Curl_conncache_close_all_connections(conncache * connc=0x000001d48a21d9b0) Line 580
curl_multi_cleanup(Curl_multi * multi=0x000001d48a21d8c0) Line 2287
```

**Comment by MarcelRaad** [comment]
Bisected to fb445a1e18d12f577964c9347bc5bca74b37cd08.

**Comment by bagder** [comment]
Thanks. I'll look into it asap...

**Comment by bagder** [comment]
I would've expected f3ce38739fa490 to have addressed that issue since it brings back the `conn->data` assignment in `Curl_disconnect`:

https://github.com/curl/curl/blob/251cabfb4a9968e92a488635a7ac5071b3f260bd/lib/url.c#L786

@MarcelRaad can you see what exactly is wrong at vtls/vtls.c:286 ?

**Comment by MarcelRaad** [comment]
What happens is that `conn->data` gets set to `NULL` at https://github.com/curl/curl/blob/ba266b3ed74abecdc02e6b036e8bbf018e01ed9c/lib/url.c#L793 and the crash because of that happens at https://github.com/curl/curl/blob/ba266b3ed74abecdc02e6b036e8bbf018e01ed9c/lib/url.c#L802 then with the call stack posted above.

**Comment by bagder** [comment]
I think it looks like a mistake that `Curl_ssl_shutdown` gets called when a single connection is closed (from within `Curl_schannel_close`). Looking at `vtls/openssl:Curl_ossl_close()` as a comparison it doesn't do that (and neither does any other TLS backend). There's a separate call to the shutdown function.

The shutdown function needs a 'data' pointer to find the session_id cache (and lock/unlock it).

I'm not sure what the best fix for this is now, but it might be to allow the shutdown to just skip the lock/unlock if there's no transfer associated with the connection anymore. Maybe like this:
~~~diff
diff --git a/lib/vtls/schannel.c b/lib/vtls/schannel.c
index 56fd93e1e..ef9b068fa 100644
--- a/lib/vtls/schannel.c
+++ b/lib/vtls/schannel.c
@@ -5,11 +5,11 @@
  *                            | (__| |_| |  _ <| |___
  *                             \___|\___/|_| \_\_____|
  *
  * Copyright (C) 2012 - 2016, Marc Hoersken, <info@marc-hoersken.de>
  * Copyright (C) 2012, Mark Salisbury, <mark.salisbury@hp.com>
- * Copyright (C) 2012 - 2018, Daniel Stenberg, <daniel@haxx.se>, et al.
+ * Copyright (C) 2012 - 2019, Daniel Stenberg, <daniel@haxx.se>, et al.
  *
  * This software is licensed as described in the file COPYING, which
  * you should have received as part of this distribution. The terms
  * are also available at https://curl.haxx.se/docs/copyright.html.
  *
@@ -2011,13 +2011,15 @@ static int Curl_schannel_shutdown(struct connectdata *conn, int sockindex)
     Curl_safefree(BACKEND->ctxt);
   }
 
   /* free SSPI Schannel API credential handle */
   if(BACKEND->cred) {
-    Curl_ssl_sessionid_lock(conn);
+    if(conn->data)
+      Curl_ssl_sessionid_lock(conn);
     Curl_schannel_session_free(BACKEND->cred);
-    Curl_ssl_sessionid_unlock(conn);
+    if(conn->data)
+      Curl_ssl_sessionid_unlock(conn);
     BACKEND->cred = NULL;
   }
 
   /* free internal buffer for received encrypted data */
   if(BACKEND->encdata_buffer != NULL) {

**Comment by MarcelRaad** [comment]
@bagder Can you push that please? It's necessary for testing https://github.com/curl/curl/pull/3321.

**Comment by chris-araman** [comment]
I'm still seeing something similar, even after https://github.com/curl/curl/commit/6ee672970972a40603d8141293ca91c4d4854187.

I think we may need to check that `data` is not `NULL` here:
https://github.com/curl/curl/blob/6ee672970972a40603d8141293ca91c4d4854187/lib/sendf.c#L264

...because `Curl_schannel_shutdown` also passes `data` to `failf`/`Curl_failf`. The `infof`/`Curl_infof` call already makes this check here:
https://github.com/curl/curl/blob/6ee672970972a40603d8141293ca91c4d4854187/lib/sendf.c#L235

**Comment by chris-araman** [comment]
@gvanem, thanks. I agree it looks like the same invariant is at issue in #3505. I will move my discussion there.
