### ISSUE TITLE
[C++] throw exception in HEADERFUNCTION callback

### ISSUE THREAD

**Issue by sspiri** [curl/curl#3413]
### I did this

Not sure if you care about my problem because its c++. I want to throw an exception from my WRITEFUNCTION callback inside curl_easy_perform(). After catching the exception and resetting the CURL handle with curl_easy_reset() i try to redo the head request. This fails indicating my easy handle is being used by a multi handle

Here is my code:
```c
#include <curl/curl.h>
#include <iostream>


ssize_t write_callback(char* buffer, ssize_t size, ssize_t blocks, void* ){
    throw 0;
}

void set_options(CURL* p){
    curl_easy_setopt(p, CURLOPT_URL, "google.com");
    curl_easy_setopt(p, CURLOPT_VERBOSE, true);
    curl_easy_setopt(p, CURLOPT_HEADERFUNCTION, &::write_callback);
    curl_easy_setopt(p, CURLOPT_FOLLOWLOCATION, true);
    curl_easy_setopt(p, CURLOPT_NOBODY, true);
}

int main(){
    curl_global_init(CURL_GLOBAL_ALL);
    auto* p = curl_easy_init();

    if(p){
        set_options(p);

        try{
            curl_easy_perform(p);
        }

        catch(...){
            std::cerr << "Error\n";
        }

        curl_easy_reset(p);
        set_options(p);

        try{
            curl_easy_perform(p);
        }

        catch(...){
            std::cerr << "Error\n";
        }

        curl_easy_cleanup(p);
    }
}
```

Here is program output:
```
*   Trying 172.217.194.100...
* TCP_NODELAY set
* Connected to google.com (172.217.194.100) port 80 (#0)
> HEAD / HTTP/1.1
Host: google.com
Accept: */*

< HTTP/1.1 301 Moved Permanently
Error
* easy handle already used in multi handle
```

### I expected the following

I thought this could work because of curl_easy_reset(). Possible workaround is to simply curl_easy_cleanup()/curl_easy_init() this handle.

### curl/libcurl version

[curl -V output]
```
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
### operating system
x86_64 GNU/Linux

**Comment by bagder** [comment]
libcurl is a C library and the callbacks need to be written using C code. I have no idea what "throw" in one of those callbacks will do, but I suspect they deeply confuse everything and you get to keep both pieces of the breakage. I don't think this is a libcurl bug...

**Comment by sspiri** [comment]
Hi,

i solved my problem using try/catch blocks around the callbacks, storing the possible exception into an std::exception_ptr and rethrow it after curl_easy_perform() returns. This works nice :)

Thanks anyway!
