### ISSUE TITLE
Missing doc for curl_mime_*

### ISSUE THREAD

**Issue by git001** [curl/curl#3414]
### I did this

I looked into the c api documentation but haven't seen the `curl_mime_*` doc
https://curl.haxx.se/libcurl/c/

### I expected the following

It would be nice to have at least a link to https://curl.haxx.se/libcurl/c/curl_mime_init.html as the https://curl.haxx.se/libcurl/c/curl_formadd.html will be deprecated and it links to the `curl_mime_init` page.

**Comment by bagder** [comment]
Thanks! (actually a bug in the curl-www repo and fixed in there)
