### ISSUE TITLE
Please check the curl-security mail list

### ISSUE THREAD

**Issue by leonwxqian** [curl/curl#3418]
We have found a security problem in curl, and we have sent the report to curl-security#haxx.se some days ago, but we still got no response. May I know the progress? Thank you.

**Comment by bagder** [comment]
@leonwxqian I can't explain why I haven't seen those as it sounds like you've done it correctly. Please try again and I'll make sure to make it go through and we'll respond within soon.

**Comment by leonwxqian** [comment]
Thank you, briefly speaking, I found a vulnerability and I already mailed curl-security at haxx.se.

But my mail is being held from the mail list and I didn't got a reply from it.

So I'd like to know the progress if possible, thank you.

The report mail was sent from leonwxqian@gmail.com.

**Comment by bagder** [comment]
Yes but please try again, older mails are discarded when not handled and I seem to have missed yours.

**Comment by leonwxqian** [comment]
Hi @badger,

Thank you, I have resent the email.

I used leonwxqian@gmail.com and the title of the mail is "Vulnerability Report".

**Comment by bagder** [comment]
In progress.
