### ISSUE TITLE
The code I write with /usr/bin/curl works, but the code I write with php curl is not working. Where am I making a mistake?

### ISSUE THREAD

**Issue by fatihag** [curl/curl#3419]
### I did this
Terminal: /usr/bin/curl -s -X POST "https://api.xxxxxxx.com/action.json?type=modifycontact&resellerno=3040267&resellerpwd=xxxxxxx&lang=tr&responsetype=json" -d "registrycode=81386095&ownercontactid=81045261&admincontactid=81045261&billcontactid=81045261&techcontactid=81045261"

PHP: 
$url = "https://api.xxxxxxx.com/action.json?type=modifycontact&resellerno=3040267&resellerpwd=xxxxxxx&lang=tr&responsetype=json";
$value = "registrycode=81386095&ownercontactid=81045261&admincontactid=81045261&billcontactid=81045261&techcontactid=81045261";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);

        curl_setopt ($ch, CURLOPT_POST, 1);
        curl_setopt ($ch, CURLOPT_POSTFIELDS, $value);
        curl_setopt($ch, CURLOPT_HEADER, FALSE); 
        curl_setopt($ch, CURLOPT_NOBODY, FALSE); 
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 3);
        curl_setopt($ch, CURLOPT_TIMEOUT, 3);
        //$son = array();
        $sonlu = curl_exec($ch);
        $son['sonuc'] = (isset($sonlu) AND !empty($sonlu)) ? $sonlu : json_encode($sunucuhata);
        $son['httpcode'] = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $son['error'] = curl_error($ch);
        $son['errorno'] = curl_errno($ch);
        curl_close($ch);
print_r($son);

Terminal response: {"status":"success","description":"OK"}

PHP response: Array
(
    [sonuc] => {"status":"error","description":"4553 missing parameter"}
    [httpcode] => 200
    [error] => 
    [errorno] => 0
)

### I expected the following
I have written two code scripts below on the terminal I'm working on, I'm writing with php doesn't work and I'm getting a missing parameter alert.
### curl/libcurl version
Terminal : curl 7.54.0
Php: 7.45.0
[curl -V output]
PHP:
Array ( [version_number] => 470272 [age] => 3 [features] => 573981 [ssl_version_number] => 0 [version] => 7.45.0 [host] => x86_64-apple-darwin10.8.0 [ssl_version] => OpenSSL/1.0.2j [libz_version] => 1.2.8 [protocols] => Array ( [0] => dict [1] => file [2] => ftp [3] => ftps [4] => gopher [5] => http [6] => https [7] => imap [8] => imaps [9] => ldap [10] => ldaps [11] => pop3 [12] => pop3s [13] => rtsp [14] => smb [15] => smbs [16] => smtp [17] => smtps [18] => telnet [19] => tftp ) )

Terminal:
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 

### operating system
Mac AND Centos 7

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
