### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_curl_easy_init"

### ISSUE THREAD

**Issue by amitbobade2007** [curl/curl#3422]
### I did this
I am developing simple UI app for Magic Leap. I am using curl library for rest API call. I am getting "Undefined symbols for architecture x86_64: "_curl_easy_init"".
Using Visual Code 1.30.1.

**Comment by bagder** [comment]
It sounds like you forgot to link with libcurl. It does not sound like a curl bug at all...

**Comment by bagder** [comment]
Not enough details, no feedback.
