### ISSUE TITLE
CURL_LOCK_DATA_CONNECT results in memory corruption

### ISSUE THREAD

**Issue by pps83** [curl/curl#3430]
Seems to be similar/related bug: https://github.com/curl/curl/issues/2132
I've enabled `CURL_LOCK_DATA_CONNECT` in my code and now I get random memory corruption issues/crashes.
I use libcurl easy interface, I verified that the same bug exists if I use v.61.1 or v.62. In general I run something like 100M http requests per second 24/7, so before enabling that option it's pretty safe to assume that it worked well, when I simply enabled that option my tests started to fail randomly.

This is sample backtrace of the crash:

>	Curl_num_addresses(const Curl_addrinfo * addr) Line 157	C
 	Curl_connecthost(connectdata * conn, const Curl_dns_entry * remotehost) Line 1185	C
 	Curl_setup_conn(connectdata * conn, bool * protocol_done) Line 4620	C
 	Curl_connect(Curl_easy * data, connectdata * * in_connect, bool * asyncp, bool * protocol_done) Line 4663	C
 	multi_runsingle(Curl_multi * multi, curltime now, Curl_easy * data) Line 1442	C
 	curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2171	C
 	easy_transfer(Curl_multi * multi) Line 686	C
 	easy_perform(Curl_easy * data, bool events) Line 779	C
 	curl_easy_perform(Curl_easy * data) Line 798	C

Inside `Curl_connecthost` `remotehost->addr` seem to point to garbage/deleted memory:
![image](https://user-images.githubusercontent.com/1614246/50624229-d3274d00-0ed2-11e9-8db8-8465442b9432.png)

If it matters I start 16 threads and each one fetches data using http1.1. Before enabling `CURL_LOCK_DATA_CONNECT` I had CURL_LOCK_DATA_COOKIE, CURL_LOCK_DATA_DNS, CURL_LOCK_DATA_SSL_SESSION and I use CURLSHOPT_LOCKFUNC/CURLSHOPT_UNLOCKFUNC for each type of data (I have 4 mutexes for all these plus CURL_LOCK_DATA_CONNECT).

**Comment by bagder** [comment]
Do you have any example source code that reproduces this crash? Can you try the current git master to see if the problem is still around or perhaps fixed since fb445a1e1 and the follow-up f3ce38739 commits?

**Comment by bagder** [comment]
No response, probably already fixed. Closing.
