### ISSUE TITLE
curl_multi_socket_action with large posts won't multiplex properly

### ISSUE THREAD

**Issue by TvdW** [curl/curl#3436]
### I did this

I'm performing multiple concurrent requests to a HTTP/2 server, each with a large POST body. The server execution takes exactly 1 second (because `sleep(1000)`), and can run many in parallel. Using `curl_multi_perform`, this takes one second as expected. Using `curl_multi_socket_action`, it takes one second per request.

Code: https://gist.github.com/TvdW/c41cb1e74feb0c5f79be83f9d330a74b - argv[1] refers to the server to test with, I've been using https://home.xifon.eu/sleep/1000 which runs a http2 server that sleeps for exactly one second. When commenting out the "BAD" section (thus allowing the "GOOD" section to run), the difference can be seen.

### I expected the following

Doing 10 concurrent requests that each take one second should take one second total.

### curl/libcurl version

```
$ ./bin/curl -V
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.0.2k zlib/1.2.7 c-ares/1.15.0 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 
```

### operating system

CentOS 7

**Comment by TvdW** [comment]
Some further debugging shows that when I get the fd_set from curl_multi_fdset, it differs from the ones passed to me via `socketfunction` in that it asks for a write on the socket, but using those sets instead does not mitigate the problem. It seems that curl_multi_perform is doing some additional processing that curl_multi_socket_action does not.

**Comment by TvdW** [comment]
Just to be sure this isn't a recent regression: this is reproducible on 7.55.1.

**Comment by TvdW** [comment]
Thanks for checking. I'm not using `curl_multi_fdset` in the code, and the `curl_multi_perform` in the bottom of the file is no-opped by the loop above it so there should be no mix of event-based and non event-based code in the file (unless I'm missing something).

The timeout logic is indeed broken but should be sufficient for the purpose of demonstrating the issue.

**Comment by bagder** [comment]
I've figured it out. Now I just need to fix it too ... =)
