### ISSUE TITLE
curl/urlapi.h missing include on curl.h

### ISSUE THREAD

**Issue by benkohler** [curl/curl#3438]
I believe the new urlapi.h should have #include "curl.h" in it.  Without that change, #include "curl/urlapi.h" throws ugly errors.

### I did this
cc -c -o tm -x c - <<< "#include \"curl/urlapi.h\""
### I expected the following
return success
### curl/libcurl version
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.0j zlib/1.2.11
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy
### operating system
Gentoo Linux

**Comment by benkohler** [comment]
In file included from <stdin>:1:
/usr/include/curl/urlapi.h:84:1: error: unknown type name ‘CURL_EXTERN’
 CURL_EXTERN CURLU *curl_url(void);
 ^~~~~~~~~~~
/usr/include/curl/urlapi.h:84:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 CURL_EXTERN CURLU *curl_url(void);
                   ^
/usr/include/curl/urlapi.h:91:12: error: expected ‘;’ before ‘void’
 CURL_EXTERN void curl_url_cleanup(CURLU *handle);
            ^~~~~
            ;
/usr/include/curl/urlapi.h:97:1: error: unknown type name ‘CURL_EXTERN’
 CURL_EXTERN CURLU *curl_url_dup(CURLU *in);
 ^~~~~~~~~~~
/usr/include/curl/urlapi.h:97:19: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
 CURL_EXTERN CURLU *curl_url_dup(CURLU *in);
                   ^
/usr/include/curl/urlapi.h:104:1: error: unknown type name ‘CURL_EXTERN’
 CURL_EXTERN CURLUcode curl_url_get(CURLU *handle, CURLUPart what,
 ^~~~~~~~~~~
/usr/include/curl/urlapi.h:104:23: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_url_get’
 CURL_EXTERN CURLUcode curl_url_get(CURLU *handle, CURLUPart what,
                       ^~~~~~~~~~~~
/usr/include/curl/urlapi.h:112:1: error: unknown type name ‘CURL_EXTERN’
 CURL_EXTERN CURLUcode curl_url_set(CURLU *handle, CURLUPart what,
 ^~~~~~~~~~~
/usr/include/curl/urlapi.h:112:23: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘curl_url_set’
 CURL_EXTERN CURLUcode curl_url_set(CURLU *handle, CURLUPart what,
                       ^~~~~~~~~~~~

**Comment by bagder** [comment]
We can probably view this as a bug, but note that all documentation says you should `#include <curl/curl.h>` and I don't think we ever suggest you should directly include any other header when using libcurl... Thus, I don't think your command line test is correct.
