### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [curl/curl#3451]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by gvanem** [comment]
You seems to have opened [13 issues](https://github.com/search?q=Create+an+AppDir+manually&type=Issues) on Github requesting the same. 

With exactly the same text. Are you a *bot*?

**Comment by zero77** [comment]
@gvanem 
No, i find AppImages just makes things a lot easier to manage.
In this circumstance lots of new installs don't have curl installed which is a pain if you are not root.
Therefore, using an AppImage would solve this.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by bagder** [comment]
The curl project provides *source code* for curl and libcurl. Binary curl packages are as far as possible made and hosted by others. It is much better of such packages are made by the experts of the particular environments and package formats used. We are not.

So, a feature-request that doesn't belong in our bug tracker, for a feature we're not likely to satisfy within the project. I'll be happy to link to any "appimage" curl binaries available for download, from the curl download page, if any appears.
