### ISSUE TITLE
7.63.0 - OS400 build fails in os400sys.c/ccsidcurl.c

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#3453]
### I did this
Attempted to build 7.63.0 on OS400, fails with the following errors in curl_url_get_ccsid() packages/OS400/ccsidcurl.c

*part = dynconvert(ccsid, s, -1, ccsid, ASCII_CCSID);
*=SEVERE==========> a - CZM0099  Unexpected argument.

Looks like this was added in a77b640cc0ddace57758946881294db6f03db16e, I think the code should be;

*part = dynconvert(ccsid, s, -1, ASCII_CCSID);

### I expected the following
Clean build

### curl/libcurl version
[curl -V output]

### operating system
OS400 V7R2M0

**Comment by bagder** [comment]
ping @monnerat

**Comment by danielgustafsson** [comment]
> On 10 Jan 2019, at 11:33, jonrumsey <notifications@github.com> wrote:
> 
> I did this
> 
> Attempted to build 7.63.0 on OS400, fails with the following errors in curl_url_get_ccsid() packages/OS400/ccsidcurl.c
> 
> *part = dynconvert(ccsid, s, -1, ccsid, ASCII_CCSID);
> *=SEVERE==========> a - CZM0099 Unexpected argument.
> 
> Looks like this was added in a77b640, I think the code should be;
> 
> *part = dynconvert(ccsid, s, -1, ASCII_CCSID);

Agreed, judging by the function prototype this seems like a correct conclusion.

**Comment by monnerat** [comment]
Yes, you're right: thanks for testing.
I will fix it in a few minutes.

**Comment by jonrumsey** [comment]
Thanks for the quick response, I think there is also a right bracket missing to complete this if statement on line 1442; 

if(result == CURLUE_OK) {

**Comment by danielgustafsson** [comment]
> On 10 Jan 2019, at 11:54, jonrumsey <notifications@github.com> wrote:
> 
> Thanks for the quick response, I think there is also a right bracket missing to complete this if statement on line 1442;
> 
> if(result == CURLUE_OK) {

To my reading, thats correct again.

**Comment by monnerat** [comment]
> I think there is also a right bracket missing to complete this if statement on line 1442;

Thanks again for reporting: fixed in 30ac449042ec2d03104ef6ab4b8bf76425f6846c.
As you may know, I do not have access to an OS400 anymore and can only perform a very imperfect "optical" check on changes for this platform. Thus I appreciate your testing and reporting :-)

**Comment by danielgustafsson** [comment]
> On 10 Jan 2019, at 12:21, monnerat <notifications@github.com> wrote:
> I think there is also a right bracket missing to complete this if statement on line 1442;
> 
> Thanks again for reporting: fixed in 30ac449 <https://github.com/curl/curl/commit/30ac449042ec2d03104ef6ab4b8bf76425f6846c>.
> As you may know, I do not have access to an OS400 anymore and can only perform a very imperfect "optical" check on changes for this platform. Thus I appreciate your testing and reporting :-)
> 
Seconded, much appreciated!

**Comment by jonrumsey** [comment]
No problem, really appreciate the quick responses.
