### ISSUE TITLE
SSL_get_tlsext_status_ocsp_resp expects pointer to non-const pointer

### ISSUE THREAD

**Issue by pps83** [curl/curl#3477]
vtsls/openssl.c:

    const unsigned char *p;
    ...
    long len = SSL_get_tlsext_status_ocsp_resp(BACKEND->handle, &p);

However, SSL_get_tlsext_status_ocsp_resp [is declared as](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_tlsext_status_ocsp_resp.html) `long SSL_get_tlsext_status_ocsp_resp(ssl, unsigned char **resp);`

`SSL_get_tlsext_status_ocsp_resp` is preprocessed into a call to `long SSL_ctrl(SSL *ssl, int cmd, long larg, void *parg);` where parg is the last `p` argument. Effectively, const gets lost if `const unsigned char**` gets converted to `void*`. In ms compiler that results in a compilation error.
If I change declaration to `unsigned char *p;` then it fails to compile on linux a few lines below:
> openssl.c:1712:33: error: passing 'unsigned char **' to parameter of type 'const unsigned char **' discards qualifiers in nested pointer types

https://github.com/curl/curl/blob/2fa0d57e2e3b7a808af55e52912827813d19c38f/lib/vtls/openssl.c#L1695

**Comment by bagder** [comment]
How about this?
~~~diff
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index 45e72d6a3..9d11b89e5 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -1690,27 +1690,28 @@ static CURLcode verifyhost(struct connectdata *conn, X509 *server_cert)
     !defined(OPENSSL_NO_OCSP)
 static CURLcode verifystatus(struct connectdata *conn,
                              struct ssl_connect_data *connssl)
 {
   int i, ocsp_status;
+  unsigned char *status;
   const unsigned char *p;
   CURLcode result = CURLE_OK;
   struct Curl_easy *data = conn->data;
 
   OCSP_RESPONSE *rsp = NULL;
   OCSP_BASICRESP *br = NULL;
   X509_STORE     *st = NULL;
   STACK_OF(X509) *ch = NULL;
 
-  long len = SSL_get_tlsext_status_ocsp_resp(BACKEND->handle, &p);
+  long len = SSL_get_tlsext_status_ocsp_resp(BACKEND->handle, &status);
 
-  if(!p) {
+  if(!status) {
     failf(data, "No OCSP response received");
     result = CURLE_SSL_INVALIDCERTSTATUS;
     goto end;
   }
-
+  p = status;
   rsp = d2i_OCSP_RESPONSE(NULL, &p, len);
   if(!rsp) {
     failf(data, "Invalid OCSP response");
     result = CURLE_SSL_INVALIDCERTSTATUS;
     goto end;

**Comment by pps83** [comment]
yes, this will work
