### ISSUE TITLE
LGPL m4/ax_code_coverage.m4 conflicts with ISC license of curl source package

### ISSUE THREAD

**Issue by wrowe** [curl/curl#3497]
The file m4/ax_code_coverage.m4 was introduced to Curl two years ago;
https://github.com/curl/curl/commit/f6e0f4556eabc8c2629d16ae599a153392d30d05
and distributed in source bundles since 7.54.1. It is incorporated into 
the project's ./configure script as part of the automake/autoconf
preparation. This renders the source code package contents including
generated ./configure incompatible with the ISC license from COPYING,
as portions of ./configure are then under LGPL 2.1 terms. The terms of
m4/ax_code_coverage.m4 license further place the burden on Curl to
share the LGPL 2.1 document when distributing this macro.

This macro, as opposed to most autoconf/automake macros, failed 
to offer the following licensing exception which is used to make usable
automake and autoconf for ISC, BSD and similarly licensed works;

~~~
#   As a special exception, the respective Autoconf Macro's copyright owner
#   gives unlimited permission to copy, distribute and modify the configure
#   scripts that are the output of Autoconf when processing the Macro. You
#   need not follow the terms of the GNU General Public License when using
#   or distributing such scripts, even though portions of the text of the
#   Macro appear in them. The GNU General Public License (GPL) does govern
#   all other use of the material that constitutes the Autoconf Macro.
~~~

I have confirmed the current sources contain the same defect;
http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_code_coverage.m4
If the 6 authors agreed on adding the clause, they could elect to relicense.
In the interim, I believe the patch needs to be reverted.

**Comment by bagder** [comment]
I agree with the conclusions and as a consequence I'm doing a rewrite and simplification of that logic to remove the dependency without losing functionality.

**Comment by bagder** [comment]
Thanks for the report. Issued fixed!
