### ISSUE TITLE
Slow loading of directory content via SFTP when timeout is set

### ISSUE THREAD

**Issue by DiceMaster** [curl/curl#3506]
Directory listing is wery slow when connecting to a SFTP server with CURLOPT_TIMEOUT or -m cmd option. Without a timeout everything works fast.

Tested on my Mac (macos 10.14.2) when connecting to other Mac with curl v7.64.0 (or with daily snapshot 20190129) with following command:
`curl sftp://<host>/ -m 20 -u <user>`

There is some delay for loading of each subdirectory/file.
In curl v7.61.0 the same command performs almost instantly.

After some investigation I found that the bug was introduced with changes to lib/ssh.c in commit 1a890997a47d4d22df58b5183181685e49ed6e61

**Comment by koskokos2** [comment]
Noticed the very same problem and for me it works very slow even without any additional arguments just:
`curl sftp://<auth>@<host>/`

In version 7.61.0 that command takes (for folder with 4 entries) 0.7s and in 7.61.1 (first affected version) it takes 6.7s for a localhost sftp server

**Comment by manfredsc** [comment]
Same for me, 7.61.1 is way slower than version 7.61.0 when doing a simple sftp listing.
The trace-ascii output is exactly the same for both versions.

It seems curl-7.61.1 does exactly one line of print-out per second as one can see with --trace-time:
```
14:45:01.186936 => Send data, 60 bytes (0x3c)
0000: drwxr-xr-x    3 0        root         4096 Jun 12  2014 dev.
14:45:02.187983 => Send data, 60 bytes (0x3c)
0000: drwxr-xr-x    2 0        root         4096 Jun 12  2014 lib.
14:45:03.189041 => Send data, 60 bytes (0x3c)
0000: drwxr-xr-x    2 0        root         4096 Oct  7  2014 bin.
14:45:04.190077 => Send data, 60 bytes (0x3c)
0000: drwxr-xr-x    2 0        root         4096 Jun 12  2014 tmp.
```
So there is somewhere an artificial 1 second delay per printed line! Hope this rings some bells...
Please tell how to further narrow this annoying bug. Thanks.

**Comment by bagder** [comment]
I can reproduce. Fix pending.

**Comment by manfredsc** [comment]
Works for me, version 7.64.0 plus this patch.
Thanks!

**Comment by bagder** [comment]
Thanks for confirming!
