### ISSUE TITLE
Verbose mode returns nothing

### ISSUE THREAD

**Issue by apach3guy** [curl/curl#3510]
I compiled curl straight from the source. It returns nothing whatsoever (yep, that’s right, NOTHING) when executing a get request on any URL. Even with the verbose flag set. Here is everything you need:
~~~
ubuntu@ninjablock:~$ curl -V
curl 7.63.0 (armv7l-unknown-linux-gnueabihf) libcurl/7.29.0 OpenSSL/1.0.1c zlib/1.2.7 libidn/1.25 librtmp/2.3
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
ubuntu@ninjablock:~$ curl -v http://192.168.1.1
ubuntu@ninjablock:~$ uname -a
Linux ninjablock 3.8.8-bone14 #1 SMP Wed Apr 24 13:59:33 UTC 2013 armv7l armv7l armv7l GNU/Linux

**Comment by bagder** [comment]
**libcurl/7.29.0** indicates you're running a funny mix of a brand new curl with a very old libcurl. That *should* work as well but I think it isn't what you intend.

**Comment by apach3guy** [comment]
Indeed. Solution was to place /usr/local/lib at the top of ld.so.conf so that the configure script would find the correct (newer) library version. Would be nice if the configure script were smart enough to detect that the system installed libcurl is out of date.

`root@ninjablock:/usr/local/src/curl# curl -V
curl 7.63.0 (armv7l-unknown-linux-gnueabihf) libcurl/7.63.0 OpenSSL/1.0.2q zlib/1.2.7
`

**Comment by bagder** [comment]
> Would be nice if the configure script were smart enough to detect that the system installed libcurl is out of date

I disagree. The configure script is all about setting up the build of the curl and libcurl in your source directory. It doesn't care about what curl versions you might have installed otherwise.

Closing this now since the reason was found and fixed.
