### ISSUE TITLE
Unsupported protocol reported as bad/illegal format

### ISSUE THREAD

**Issue by twouters** [curl/curl#3511]
Not 100% sure this is a bug, it's at least an unexpected behavioral change.

Curl suddenly reports unsupported protocols as bad/illegal format when their length is >7 characters.

e.g. PHP tests currently rely on this https://github.com/php/php-src/blob/master/ext/curl/tests/curl_basic_009.phpt

### I did this

```
$ curl -v aaaaaaa://localhost/
* Protocol "aaaaaaa" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "aaaaaaa" not supported or disabled in libcurl
$ curl -v aaaaaaaa://localhost/
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL
```

### I expected the following

```
$ curl -v aaaaaaa://localhost/
* Protocol "aaaaaaa" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "aaaaaaa" not supported or disabled in libcurl
$ curl -v aaaaaaaa://localhost/
* Protocol "aaaaaaaa" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "aaaaaaaa" not supported or disabled in libcurl
```

### curl/libcurl version

curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.0 libpsl/0.20.2 (+libidn2/2.1.0) libssh2/1.8.0 nghttp2/1.35.1
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by bagder** [comment]
I can see how this is annoying for you, but at the same time I'm not sure we can guarantee that we always will return the same error value for something bad.

You expect ">7" characters to return the same error as "<7" characters. Would that also apply if the used scheme is let's say 22MB large? I assume we need to set a limit somewhere to avoid wasting time to search for a colon if nothing else. I'm not married to this particular limit, but it is based on the fact that libcurl doesn't support any protocols with a URI scheme longer than 6 characters.

We don't test for this in curl itself so it feels strange that someone would insist on this without pushing a similar test to the curl repo to catch such an error in time. We already shipped this release and behavior some 45 days ago...

**Comment by twouters** [comment]
Yeah, tbh I don't really have a problem with it.
I couldn't find anything about it in the changelog (or I've missed it) and thought it was an accidental regression.

I understand the reasoning here so I'll check with the php devs to see how their unittest can be adapted.

**Comment by bagder** [comment]
> I couldn't find anything about it in the changelog 

Right. This change came from the internal URL parser rewrite and URL API (that are mentioned) and I hadn't noticed or considered this until you pointed it out.
