### ISSUE TITLE
"--remote-header-name" and "--continue-at -" options are incompatible

### ISSUE THREAD

**Issue by tomjakubowski** [curl/curl#3512]
### I did this

I ran this command:
```
curl -LJO -C - http://some/crazy/url/to/a/huge/file
```

Then, about halfway through the transfer, I interrupted it.  I ran again:

```
curl -LJO -C - http://some/crazy/url/to/a/huge/file
```

### I expected the following

I expected that the `-C-` flag would cause cURL to check the partially downloaded file, see how many bytes had been downloaded, and resume the transfer from that point. Instead, `-J`'s documented behavior kicked in:

> If the server specifies a file name and a file with that name already exists in the current working directory it will not be overwritten and an error will occur.

Accordingly, cURL quit with an error saying it would not overwrite the file.

In the typical case, without use of `--continue-at -`, this behavior is perfectly reasonable. However, if `-C -` is also passed, it seems reasonable to me to infer the user's intent: the file was only partly downloaded, and they would like to resume.

For what it's worth, I can work around this by passing `-o actual-filename` rather than `-O`. But that somewhat defeats the purpose of `-J`!

### curl/libcurl version

curl 7.54.0

### operating system

macOS

**Comment by bagder** [comment]
The sad truth is that this has been a [known bug](https://curl.haxx.se/docs/knownbugs.html#J_with_C_fails) for almost six years already. It was originally filed in the [old bug tracker](https://sourceforge.net/p/curl/bugs/1169/). It clearly hasn't been a prioritized enough issue for us. Maybe the time is finally here!
