### ISSUE TITLE
building curl with boringssl fails

### ISSUE THREAD

**Issue by loganaden** [curl/curl#3520]
### I did this
https://ec.haxx.se/building-boringssl.html
### I expected the following
make successful
### curl/libcurl version
master branch
[curl -V output]
  CCLD     libcurl.la
/usr/bin/ld: /home/logan/git/boringssl/lib/libssl.a(bio_ssl.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/logan/git/boringssl/lib/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:907: recipe for target 'libcurl.la' failed
make[2]: *** [libcurl.la] Error 1
make[2]: Leaving directory '/home/logan/git/curl/lib'
Makefile:746: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/logan/git/curl/lib'
Makefile:920: recipe for target 'all-recursive' failed

### operating system
ubuntu-16 server

**Comment by jay** [comment]
Are you trying to link a static library in a shared library? Try doing what it says and compile BoringSSL with -fPIC

**Comment by loganaden** [comment]
Thanks. I used this option with cmake: -DBUILD_SHARED_LIBS=1, and still the same issue.
