### ISSUE TITLE
Unable to resolve ipv6 addresses on OS X

### ISSUE THREAD

**Issue by SerialVelocity** [curl/curl#3521]
### I did this

```
> /usr/local/opt/curl/bin/curl -6 6.ipquail.com/ip
curl: (6) Could not resolve host: 6.ipquail.com
```

### I expected the following
```
> /usr/local/opt/curl/bin/curl -6 6.ipquail.com/ip --resolve '6.ipquail.com:80:2604:a880:1:20::8a:b001'
<my ipv6 address>
```

### curl/libcurl version

```
/usr/local/opt/curl/bin/curl -V
curl 7.63.0 (x86_64-apple-darwin17.7.0) libcurl/7.63.0 SecureTransport zlib/1.2.11
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

### operating system

MacOS High Sierra 10.13.3

### Notes

- This works on Linux (tested on a Raspberry Pi with the same setup)
- This is probably because I only have an IPv4 DNS server. I think Linux is using the IPv4 DNS server to get the AAAA record while on OS X it is trying to use an IPv6 DNS server which I do not have.
- Chrome/ping/dig/nslookup all work and find the correct IPv6 address

**Comment by nickzman** [comment]
FWIW, I tried it with the latest code, and curl resolved the IPv6 address. But I have an IPv6 DNS server.

**Comment by SerialVelocity** [comment]
Nevermind, this is my lack of OSX networking knowledge.
```
DNS configuration

resolver #1
  search domain[0] : openvpn
  nameserver[0] : 172.31.255.254
  nameserver[1] : 8.8.8.8
  flags    : Request A records
  reach    : 0x00000002 (Reachable)
```
There should be a flag for Requesting AAAA records. There's an issue on Tunnelblick for this:
https://github.com/Tunnelblick/Tunnelblick/issues/490
