### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by pps83** [curl/curl#3523]
We love libcurl, but we also need to use websocket (specifically signalr). If we use any websocket lib we end up linking all the basic http/ssl/networking code that comes with these websocket libs.
How can I use libcurl for websocket communication? Effectively, I'd just need http/https connection establishment and then for the rest of the lifetime of the connection I'd handle myself entire data. Is that possible with libcurl, any suggestions?

Thanks

**Comment by bagder** [comment]
@mkauf presented [an idea for libcurl to do basic websocket support](https://curl.haxx.se/video/curlup-2017/2017-03-19_05_Michael_Kaufmann_Websocket_support_for_curl.mp4) already at curl up 2017, but we haven't taken that anywhere since. Maybe it is about time?
