### ISSUE TITLE
Upload multiple files with smb

### ISSUE THREAD

**Issue by mb720** [curl/curl#3535]
Thanks a lot for curl! 👍

### I did this

    curl --upload-file "{file_1,file_2,file_3}" -u 'domain\username:password' smb://172.16.17.52/ShareName/Path/To/Dir/

### I expected the following

I'd expect to see three files in the remote directory with contents identical to the local files `file_1`, `file_2`, and `file_3`.

Yet, I see only one file in the remote directory, named `file_1` with the contents of the file given last, `file_3`.

### curl/libcurl version

    curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.0 libpsl/0.20.2 (+libidn2/2.1.0) libssh2/1.8.0 nghttp2/1.36.0
    Release-Date: 2018-12-12
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
Arch Linux 4.20.6

**Comment by godeater** [comment]
I've just tried this myself on a very similar setup. 
I'm running Arch on kernel 4.20.6, but my curl is now 7.64.0.

I ran this:
`curl --upload-file "{file_1,file_2,file_3}" -u '.\user:password' smb://server/media/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6    0     0  100     6      0    122 --:--:-- --:--:-- --:--:--   122
100     6    0     0  100     6      0    545 --:--:-- --:--:-- --:--:--   545
100     6    0     0  100     6      0    545 --:--:-- --:--:-- --:--:--   545`

And all three files appeared on the samba server with the write content, and the right file names.

So, a couple more questions:
Which shell did you invoke your command from (I'm assuming bash, but maybe it wasn't), and what OS / Samba version is the target server running? Is it possible to get any logs from it?

**Comment by mb720** [comment]
Fascinating.

Yes, my shell is bash 5.0.0.

The target server runs Windows Server 2016, 1607.

Executing `Get-SmbServerConfiguration` on the target server yields:

    EnableMultiChannel: True
    ...
    EnableSMB1Protocol: True
    EnableSMB2Protocol: True
    ...
    MaxWorkItems      : 1


Searching for "smb" in the Windows event log returned not a single result; making me wonder whether I'm looking in the right place.

---

By the way, my current workaround is to pass each file name of the local directory via `xargs` to `curl`:

    find local_dir -maxdepth 1 -type f | xargs -I file_to_upload curl --upload-file file_to_upload --user 'domain/user:password' smb:server/Service/RemoteDir/

**Comment by mb720** [comment]
Holy smokes, the issue is gone with curl 7.64!
