### ISSUE TITLE
Rubbish LD variable contents not detected by configure

### ISSUE THREAD

**Issue by copelnug** [curl/curl#3543]
### Reproduction
I tried to cross compile libcurl and I did a mistake while settings the LD environment variable. 

`export LD=oops`
`./configure --disable-ldap --disable-telnet --disable-dict --disable-file --disable-tftp --disable-smtp --disable-pop3 --disable-imap --disable-gopher --without-zlib --without-ca-path --without-libssh2 --without-libidn --disable-ssl`
![curl_build_bug_configure](https://user-images.githubusercontent.com/8868864/52502134-ff0faf80-2baf-11e9-9da3-53da9d1c80ea.JPG)
`cd lib`
`make`

### The problem
Event if the make operation succeeded and is configured with `shared=yes`, the shared library was not created as the result of  `ls -l .libs` show:
![curl_build_bug_listresult](https://user-images.githubusercontent.com/8868864/52502193-21093200-2bb0-11e9-9226-fd040c065baa.JPG)

This means that the next operation that need it will fail (either linking the curl exec as [2470](https://github.com/curl/curl/issues/2470) or the `make install`).

From the logs, I got the libtool command and it succeeded without creating the shared library.
> /bin/sh ../libtool  --tag=CC   --mode=link /opt/rh/devtoolset-2/root/usr/bin/gcc  -fvisibility=hidden -O2 -Wno-system-headers   -version-info 8:0:4     -lssl -lcrypto -lssl -lcrypto -lrt  -o libcurl.la **...**
> libtool: link: rm -fr  .libs/libcurl.a .libs/libcurl.la .libs/libcurl.lai .libs/libcurl.so .libs/libcurl.so.4 .libs/libcurl.so.4.4.0
> libtool: link: (cd ".libs" && rm -f "libcurl.so.4" && ln -s "libcurl.so.4.4.0" "libcurl.so.4")
> libtool: link: (cd ".libs" && rm -f "libcurl.so" && ln -s "libcurl.so.4.4.0" "libcurl.so")
> libtool: link: /opt/rh/devtoolset-2/root/usr/bin/ar cru .libs/libcurl.a  **...**
> libtool: link: ranlib .libs/libcurl.a
> libtool: link: ( cd ".libs" && rm -f "libcurl.la" && ln -s "../libcurl.la" "libcurl.la" )
> make[1]: Leaving directory `/app/target/src/curl-7.51.0/lib'

### I expected the following
I expected the `configure` script to fail if `LD` is either:
- Invalid.
- Incompatible with the compiler.

### curl/libcurl version
Curl 7.51.0

### operating system
- Centos 6
- Debian Jessie

### Reparation
The only way to repair the build is to correct the `LD` value and then restart the build completely including the `configure` step.

**Comment by bagder** [comment]
We could certainly consider adding some test to configure that verifies that `LD` is indeed a working tool, but since we use libtool to link most things in curl that's a lot of second-guessing. I tend to think of this as garbage in, garbage out.

Since configure itself doesn't need/use LD, adding a strict check could possibly break use-cases where you setup LD in configure first, and then in a second step make it work before you invoke make. It should therefor probably be at most a warning and not a fatal error.

**Comment by copelnug** [comment]
Just to be clear, changing LD between the configure and the make does not work. Configure generate the libtool file and put the line `LD="oops -m elf_x86_64"` in it. As such, you really need to redo a `configure` after fixing the variable.

Thus, I feel that adding a check on LD could help a lot even if only checking the file existence.

**Comment by jay** [comment]
> From the logs, I got the libtool command and it succeeded without creating the shared library.

So then isn't this a libtool bug?

**Comment by bagder** [comment]
> Just to be clear, changing LD between the configure and the make does not work. Configure generate the libtool file and put the line LD="oops -m elf_x86_64" in it. As such, you really need to redo a configure after fixing the variable.

Well, you could still run configure first and *then* make your `oops` binary available, run make and everything builds fine... Since configure doesn't *use* LD, that tool doesn't have to work at the time that script runs.

I agree with @jay that this sounds like a libtool issue.

**Comment by bagder** [comment]
Deemed to be a libtool issue (or possibly bug). Please take it to them and discuss what possible fix that should be implemented.
