### ISSUE TITLE
mbedtls: disable MBEDTLS_VERSION_C

### ISSUE THREAD

**Issue by MAntoniak** [curl/curl#3553]
### I did this

I am trying to build a curl library using the mbedtls library. In mbedtls has disable run-time version information (comment MBEDTLS_VERSION_C). The Curl_mbedtls_version function refers to the mbedtls_version_get_number function, which is disabled. As a result, it is not possible to build a project.

### I expected the following

Build succeeded.

Perhaps using the MBEDTLS_VERSION_STRING may solve this problem:
`return msnprintf(buffer, size, "mbedTLS/%s", MBEDTLS_VERSION_STRING);`

### curl/libcurl version

[curl -V output]
curl 7.64.0 mbedTls/2.7.9
Release-Date: 2019-02-06
Protocols: http

### operating system

Embedded system.

**Comment by bagder** [comment]
@MAntoniak does my proposed fix in #3556 work for you?

**Comment by MAntoniak** [comment]
Yes, it works. Thanks!
