### ISSUE TITLE
error: two or more data types in declaration specifiers

### ISSUE THREAD

**Issue by JonasVautherin** [curl/curl#3567]
Building the latest curl master (`$ git clone --depth 1 https://github.com/curl/curl` run yesterday) with dockcross `manylinux-x64` on Ubuntu 16.04.2 LTS (Xenial Xerus), I get the following error:

```
[  0%] Building C object lib/CMakeFiles/libcurl.dir/file.c.o
In file included from /work/lib/curl_setup.h:59:0,
                 from /work/lib/file.c:23:
/work/build/lib/curl_config.h:1008:17: error: two or more data types in declaration specifiers
 #define ssize_t long
```

I am building with the following:

```
cmake -DCMAKE_USE_OPENSSL=OFF -DCURL_CA_PATH_SET=OFF -DHAVE_POSIX_STRERROR_R=1 -Bbuild -H.
make -Cbuild
```

It builds fine on my Arch Linux and using Dockcross `linux-armv6` on Ubuntu, but not using Dockcross `manylinux-x64`. Steps to reproduce (say in `/tmp/curl-issue`):

```
mkdir /tmp/curl-issue
cd /tmp/curl-issue
git clone --depth 1 https://github.com/curl/curl
docker run --rm dockcross/manylinux-x64 > ./dockcross
cd curl
../dockcross cmake -DCMAKE_USE_OPENSSL=OFF -DCURL_CA_PATH_SET=OFF -DHAVE_POSIX_STRERROR_R=1 -Bbuild -H.
../dockcross make -Cbuild
```

Note that it seems related to #2358, which is supposed to be fixed. I must say I don't really get if that is related to `manylinux` or if that could come from the curl CMake configuration.

Would you have an idea about that?

**Comment by bagder** [comment]
I don't understand the error message. I suspect it identifies the wrong line. Have you checked the generated `/work/build/lib/curl_config.h` file to see if you spot anything obvious?

(This said, I don't even know what dockcross does or changes.)

**Comment by jzakrzewski** [comment]
@bagder dockross is just a docker image with a cross-toolchain installed and applied automatically for the builds. In case of manylinux it's based on some older CentOS and gcc like 6.4.

**Comment by JonasVautherin** [comment]
I ran it again, and this time it worked. I really don't get why, I tried it quite a few times before...

Closing for now, hopefully that will never happen again :sweat_smile:.

Thanks for the comments and sorry for the inconvenience :confused:
