### ISSUE TITLE
Formpost tests failing

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#3576]
### I did this

```
make clean && ./buildconf && ./configure --enable-threaded-resolver --disable-pthreads --enable-debug --enable-warnings --enable-curldebug --enable-optimize --enable-static --disable-shared --enable-http --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-libcurl-option --enable-ipv6 --enable-sspi --disable-cookies --without-zlib --without-libpsl --without-libmetalink --without-libssh2 --without-librtmp --without-winidn --without-libidn2 --without-nghttp2 --without-zsh-functions-dir --without-brotli --disable-proxy --disable-crypto-auth --with-ssl && make && cd tests && make && ./runtests.pl 9 && cd ..
```

15 tests in my two HTTP-only MinGW autobuilds have been failing since Febrary 12:
https://curl.haxx.se/dev/log.cgi?id=20190212052138-2829
https://curl.haxx.se/dev/log.cgi?id=20190212055218-12631

The failing Tests are:
test 0009...[HTTP RFC1867-type formposting]
test 0039...[HTTP RFC1867-type formposting with filename= and type=]
test 0041...[HTTP formpost with missing file]
test 0044...[HTTP RFC1867-type formposting without Expect: header]
test 0071...[HTTP and -F upload in config file]
test 0158...[HTTP multipart formpost with only a 100 reply]
test 0163...[HTTP multipart formpost with contents from a file]
test 0166...[HTTP formpost a file with spaces in name]
test 0173...[HTTP RFC1867-formpost a file from stdin with "faked" filename]
test 0186...[HTTP RFC1867-type formposting with types on text fields]
test 0277...[HTTP RFC1867-type formposting with custom Content-Type]
test 1053...[HTTP RFC1867-type formposting from file with Location: following]
test 1133...[HTTP RFC1867-type formposting with filename/data contains ',', ';', '"']
test 1315...[HTTP RFC1867-type formposting - -F with three files, one with explicit type]
test 2073...[HTTP form posts with handle reset]

### I expected the following
Successful test runs.

stderr not containing:
> curl: (43) A libcurl function was given a bad Argument

The error is from this location:
https://github.com/curl/curl/blob/179927c12a54ea810bbc7c6c6fb970ad90b89eef/lib/mime.c#L1484

gdb says:
```
(gdb) print part->easy
$2 = (struct Curl_easy *) 0x119a6b8
(gdb) print subparts->easy
$3 = (struct Curl_easy *) 0x1
```

### curl/libcurl version

Git bisect says failing since https://github.com/curl/curl/commit/b75fb9b5a6ee02beb9e2c6ed43556603f4ef64cf. I find that hard to believe as only the next commit (https://github.com/curl/curl/commit/cac0e4a6ad14b42471ebc62e82ecdb7dad164702) modified the curl tool code that uses the failing libcurl code, but I ran bisect twice and ran the above command for each revision.
However, when running `make` again after that, I get:
```
  CC       curl-tool_cb_dbg.o
  CC       curl-tool_cb_hdr.o
  CC       curl-tool_cb_prg.o
  CC       curl-tool_cb_rea.o
  CC       curl-tool_cb_see.o
  CC       curl-tool_cb_wrt.o
  CC       curl-tool_cfgable.o
  CC       curl-tool_doswin.o
  CC       curl-tool_formparse.o
  CC       curl-tool_getparam.o
  CC       curl-tool_helpers.o
  CC       curl-tool_main.o
  CC       curl-tool_msgs.o
  CC       curl-tool_operate.o
  CC       curl-tool_operhlp.o
  CC       curl-tool_paramhlp.o
  CC       curl-tool_parsecfg.o
  CC       curl-tool_setopt.o
  CC       curl-tool_urlglob.o
  CC       curl-tool_writeout.o
  CCLD     curl.exe
  CC       libcurltool_la-tool_cb_dbg.lo
  CC       libcurltool_la-tool_cb_hdr.lo
  CC       libcurltool_la-tool_cb_prg.lo
  CC       libcurltool_la-tool_cb_rea.lo
  CC       libcurltool_la-tool_cb_see.lo
  CC       libcurltool_la-tool_cb_wrt.lo
  CC       libcurltool_la-tool_cfgable.lo
  CC       libcurltool_la-tool_doswin.lo
  CC       libcurltool_la-tool_formparse.lo
  CC       libcurltool_la-tool_getparam.lo
  CC       libcurltool_la-tool_helpers.lo
  CC       libcurltool_la-tool_main.lo
  CC       libcurltool_la-tool_msgs.lo
  CC       libcurltool_la-tool_operate.lo
  CC       libcurltool_la-tool_operhlp.lo
  CC       libcurltool_la-tool_paramhlp.lo
  CC       libcurltool_la-tool_parsecfg.lo
  CC       libcurltool_la-tool_setopt.lo
  CC       libcurltool_la-tool_urlglob.lo
  CC       libcurltool_la-tool_writeout.lo
  CCLD     libcurltool.la
```
and after that, the tests succeeds for this commit and fails as expected for the next one, so I'm very confused now and either my toolchain or my brain seems to be broken.

### operating system

MSYS2 with MinGW-w64 on Windows 10

**Comment by MarcelRaad** [comment]
Oh, and I just noticed this - why isn't it flagged as a warning on the autobuilds page?

```
CC libcurltool_la-tool_operate.lo
In file included from [...]/curl-7.64.1-20190212/src/tool_operate.c:65:0:
[...]/curl-7.64.1-20190212/src/tool_operate.c: In function 'operate_do':
[...]/curl-7.64.1-20190212/include/curl/typecheck-gcc.h:104:9: warning: call to '_curl_easy_setopt_err_curl_mimepost' declared with attribute warning: curl_easy_setopt expects a 'curl_mime *' argument for this option
_curl_easy_setopt_err_curl_mimepost(); \
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]/curl-7.64.1-20190212/src/tool_setopt.h:33:13: note: in definition of macro 'SETOPT_CHECK'
result = (v); \
^
[...]/curl-7.64.1-20190212/src/tool_setopt.h:144:16: note: in expansion of macro 'curl_easy_setopt'
SETOPT_CHECK(curl_easy_setopt(x, y, z))
^~~~~~~~~~~~~~~~
[...]/curl-7.64.1-20190212/src/tool_operate.c:948:11: note: in expansion of macro 'my_setopt_mimepost'
my_setopt_mimepost(curl, CURLOPT_MIMEPOST, config->mimepost);
^~~~~~~~~~~~~~~~~~
```

**Comment by bagder** [comment]
Oh, and yeah this looks wrong. @monnerat this now seems like the opposite: it passes the tool-private struct to libcurl... ?

(and why this isn't noticed in the CI builds I haven't yet figured out)

**Comment by bagder** [comment]
The key here that causes this bug is `--disable-libcurl-option`.

**Comment by monnerat** [comment]
> The key here that causes this bug is --disable-libcurl-option

Wow, I didn't notice this existed :-(
I will check and keep you informed here.

**Comment by monnerat** [comment]
I just created PR #3583 fixing it...

**Comment by monnerat** [comment]
Commit e49e5ea fixes it: works with and without `--disable-libcurl-option`.

**Comment by MarcelRaad** [comment]
Great, thanks!
