### ISSUE TITLE
source code warnings generated by our scanner

### ISSUE THREAD

**Issue by lqiulin** [curl/curl#3590]
### I did this
Our bug scanner has reported some bugs.
Bug triggering files are attached.

**Bug-1:div/mod-zero**

1. in function `size_t hash_fd`,[multi.c#L278](https://github.com/curl/curl/blob/master/lib/multi.c#L278)

```c++
return (fd % slots_num);
```

Divisor: slots_num
Result: Could be 0, Please Check.

2.in function `Curl_hash_str`,[hash.c#L268](https://github.com/curl/curl/blob/master/lib/hash.c#L268)

```c++
  return (h % slots_num);
```

Divisor: slots_num
Result: Could be 0, Please Check.

3.in function `fly`,[tool_cb_prg.c#L78#L80#L82#L84](https://github.com/curl/curl/blob/master/src/tool_cb_prg.c#L78)

```c++
pos = sinus[bar->tick%200] / (10000 / check);
```
```c++
pos = sinus[(bar->tick + 5)%200] / (10000 / check);
```
```c++
pos = sinus[(bar->tick + 10)%200] / (10000 / check);
```
```c++
pos = sinus[(bar->tick + 15)%200] / (10000 / check);
```
Divisor: check
Result: Could be 0, Please Check.

**Bug-2:array index**
1. in function `callback`,[libntlmconnect.c#L48#L51#L74](https://github.com/curl/curl/blob/master/tests/libtest/libntlmconnect.c#L48)

```c++
counter[idx] += (int)(size * nmemb);
```
```c++
code = curl_easy_getinfo(easy[idx], CURLINFO_LASTSOCKET, &longdata);
```
```c++
fprintf(stderr, "Handle %d started on socket %d and moved to %d\n", curlx_sztosi(idx), (int)sockets[idx], (int)sock);
```

Array expression: counter[idx], easy[idx], sockets[idx]
needs bound checking: 0<=idx<3

2.in function `init`,[lib540.c#L94](https://github.com/curl/curl/blob/master/tests/libtest/lib540.c#L94)

```c++
  curl_easy_cleanup(eh[num]);
```

Array expression: eh[num]
needs bound checking: 0<=num<2

3.in function `init`,[ib1900.c#L116#L117](https://github.com/curl/curl/blob/master/tests/libtest/lib1900.c#L116)

```c++
msnprintf(urlbuf, sizeof(urlbuf), "%s%s", base_url, urlstring[handlenum]);
```
```c++
curl_easy_setopt(handles[handlenum], CURLOPT_URL, urlbuf);
```
Array expression: urlstring[handlenum]
needs bound checking: 0<=handlenum<200

4.in function `Curl_ssl_getsessionid`,[vtls.c#L315](https://github.com/curl/curl/blob/master/lib/vtls/vtls.c#L315)

```c++
const bool isProxy = CONNECT_PROXY_SSL();
```

Array expression: conn->bits.proxy_ssl_connected[sockindex]
needs bound checking: 0<=sockindex<2

5.in function `Curl_ssl_addsessionid`,[vtls.c#L423](https://github.com/curl/curl/blob/master/lib/vtls/vtls.c#L423)

```c++
const bool isProxy = CONNECT_PROXY_SSL();
```

Array expression: conn->bits.proxy_ssl_connected[sockindex]
needs bound checking: 0<=sockindex<2

6.in function `Curl_recv_plain`,[sendf.c#L448](https://github.com/curl/curl/blob/master/lib/sendf.c#L448)

```c++
curl_socket_t sockfd = conn->sock[num];
```

Array expression: conn->sock[num]
needs bound checking: 0<=num<2

7.in function `ossl_send`,[openssl.c#L3700#L3701](https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L3700)

```c++
      if(ERR_GET_LIB(sslerror) == ERR_LIB_SSL &&
         ERR_GET_REASON(sslerror) == SSL_R_BIO_NOT_SET &&
         conn->ssl[sockindex].state == ssl_connection_complete &&
         conn->proxy_ssl[sockindex].state == ssl_connection_complete)
```

Array expression: conn->ssl[sockindex], conn->proxy_ssl[sockindex]
needs bound checking: 0<=sockindex<2

8.in function `Curl_pgrsUpdate`,[progress.c#L412#L444](https://github.com/curl/curl/blob/master/lib/progress.c#L412)

```c++
data->progress.speeder_time [ nowindex ] = now;
```
```c++
curl_off_t amount = data->progress.speeder[nowindex]-data->progress.speeder[checkindex];
```
Array expression: data->progress.speeder[nowindex]
needs bound checking: 0<=sockindex<6

9.in function `fly`,[tool_cb_prg.c#L79](https://github.com/curl/curl/blob/master/src/tool_cb_prg.c#L79)

```c++
buf[pos] = '#';
```

Array expression: buf[pos]
needs bound checking: 0<=pos<256

10.in function `tool_progress_cb`,[tool_cb_prg.c#L181](https://github.com/curl/curl/blob/master/src/tool_cb_prg.c#L181)

```c++
line[num] = '\0';
```

Array expression: line[num]
needs bound checking: num>=0

**Bug-3:security-sensitive function**
1.in function `readcallback`,[lib555.c#L64](https://github.com/curl/curl/blob/master/tests/libtest/lib555.c#L64)

```c++
strcpy(ptr, uploadthis);
```

[strcpy] is a security-sensitive function using tainted data: [ptr]

2.in function `Curl_multissl_version`,[vtls.c#L1260#L1262](https://github.com/curl/curl/blob/master/lib/vtls/vtls.c#L1260)

```c++
memcpy(buffer, backends, total + 1);
```
```c++
memcpy(buffer, backends, size - 1);
```
[memcpy] is a security-sensitive function using tainted data: [buffer  ]

3.in function `inet_ntop4`,[inet_ntop.c#L69](https://github.com/curl/curl/blob/master/lib/inet_ntop.c#L69)

```c++
strcpy(dst, tmp);
```

[strcpy] is a security-sensitive function using tainted data: [dst  ]

4.in function `inet_ntop6`,[inet_ntop.c#L166](https://github.com/curl/curl/blob/master/lib/inet_ntop.c#L166)

```c++
strcpy(dst, tmp);
```

[strcpy] is a security-sensitive function using tainted data: [dst  ]

5.in function `gzip_unencode_write`,[content_encoding.c#L515](https://github.com/curl/curl/blob/master/lib/content_encoding.c#L515)

```c++
memcpy(z->next_in + z->avail_in - nbytes, buf, nbytes);
```

[memcpy] is a security-sensitive function using tainted data: [nbytes  ]

6.in function `check_telnet_options`,[telnet.c#L849](https://github.com/curl/curl/blob/master/lib/telnet.c#L849)

```c++
strncpy(tn->subopt_ttype, option_arg, 31);
```

[strncpy] is a security-sensitive function using tainted data: [tn-&gt;subopt_ttype  ]

7.in function `check_telnet_options`,[telnet.c#L857](https://github.com/curl/curl/blob/master/lib/telnet.c#L857)

```c++
strncpy(tn->subopt_xdisploc, option_arg, 127);
```

[strncpy] is a security-sensitive function using tainted data: [tn-&gt;subopt_xdisploc  ]

8.in function `passwd_callback`,[openssl.c#L427](https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L427)

```c++
memcpy(buf, global_passwd, klen + 1);
```

[memcpy] is a security-sensitive function using tainted data: [buf  ]

9.in function `smb_format_message`,[smb.c#L349#L352](https://github.com/curl/curl/blob/master/lib/smb.c#L349)

```c++
memset(h, 0, sizeof(*h));
```
```c++
memcpy((char *)h->magic, "\xffSMB", 4);
```
[memset] is a security-sensitive function using tainted data: [h  ]
[memcpy] is a security-sensitive function using tainted data: [(char *)h-&gt;magic  ]

10. in function `smb_send_message`,[smb.c#L417](https://github.com/curl/curl/blob/master/lib/smb.c#L417)

```c++
memcpy(conn->data->state.ulbuf + sizeof(struct smb_header),msg, msg_len);
```

[memcpy] is a security-sensitive function using tainted data: [msg_len  ]

11.in function `smb_send_setup`,[smb.c#L469#L470#L471#L472](https://github.com/curl/curl/blob/master/lib/smb.c#L469)

```c++
MSGCATNULL(smbc->user);
MSGCATNULL(smbc->domain);
MSGCATNULL(OS);
MSGCATNULL(CLIENTNAME);
```

[strcpy] is a security-sensitive function using tainted data: [(smbc-&gt;user)  ]

12.in function `smb_send_tree_connect`,[smb.c#L496#L497#L498#L499](https://github.com/curl/curl/blob/master/lib/smb.c#L496)

```c++
MSGCAT(conn->host.name);
MSGCAT("\\");
MSGCATNULL(smbc->share);
MSGCATNULL(SERVICENAME); 
```

[strcpy] is a security-sensitive function using tainted data: [p  ]

13.in function `smb_send_write`,[smb.c#L590](https://github.com/curl/curl/blob/master/lib/smb.c#L590)

```c++
memset(msg, 0, sizeof(*msg));
```

[memset] is a security-sensitive function using tainted data: [msg  ]

14.in function `encoder_qp_read`,[mime.c#L588](https://github.com/curl/curl/blob/master/lib/mime.c#L588)

```c++
memcpy(ptr, buf, len);
```

[memcpy] is a security-sensitive function using tainted data: [ptr  ]

15.in function `Curl_mime_initpart`,[mime.c#L1237](https://github.com/curl/curl/blob/master/lib/mime.c#L1237)

```c++
memset((char *) part, 0, sizeof(*part));
```

[memset] is a security-sensitive function using tainted data: [(char *)part  ]

16.in function `Curl_ip2addr`,[curl_addrinfo.c#L430#L436](https://github.com/curl/curl/blob/master/lib/curl_addrinfo.c#L430)

```c++
memcpy(addrentry, inaddr, sizeof(struct in_addr));
```
```c++
memcpy(addrentry, inaddr, sizeof(struct in6_addr));
```

[memcpy] is a security-sensitive function using tainted data: [addrentry  ]

17.in function `Curl_get_pathname`,[curl_path.c#L181](https://github.com/curl/curl/blob/master/lib/curl_path.c#L181)

```c++
strcpy(*path, homedir);
```

[strcpy] is a security-sensitive function using tainted data: [homedir  ]

18.in function `glob_match_url`,[tool_urlglob.c#L687](https://github.com/curl/curl/blob/master/src/tool_urlglob.c#L687)

```c++
Curl_safefree(target);
```

[free] is a security-sensitive function using tainted data: [(target)  ]

### curl/libcurl version

curl -7.63.0

### operating system
Linux x86_64

**Comment by bagder** [comment]
These are not *bugs*. These are locations in the code this tool points out to areas that perhaps *could* be problematic. And sure, taken out of context each of them could possibly be wrong but I've taken a glance through the list and I could not detect any notable remarks. Can you?

If you know of any **bugs** among these, then please highlight those and let's look closer and discuss. Just handing over a long list with vague warnings is rather useless.

**Comment by bagder** [comment]
No response after a week. No bug found here.
