### ISSUE TITLE
How do I get help ?? It is not obvious from the home page. The only way I can see is to record an issue 

### ISSUE THREAD

**Issue by MRLBEL** [curl/curl#3594]
### curl/libcurl version

[curl -V output]

**Comment by MRLBEL** [comment]
I have come to this comment page ... I have no idea what I am looking at.
I just want to ask a question ..

**Comment by MRLBEL** [comment]
It's okay  ... I found it .. thks

**Comment by jzakrzewski** [comment]
On the curl homepage ( https://curl.haxx.se/ ) there's "Get Help" entry in the main navigation menu. It will direct you to various resources including mailing lists where you can ask your questions.

**Comment by MRLBEL** [comment]
Thank you..
