### ISSUE TITLE
SCP: Curl not reading all data on ssh channel causing it to report a false upload success

### ISSUE THREAD

**Issue by lsabouri74** [curl/curl#3603]
### I did this
I tried to upload a file to SolarWinds SCP server using libcurl and although upload was reported as success, the file was not uploaded. When I enabled logging i saw the following line: 

== Info: Channel failed to close: -34 libssh2_channel_wait_closed() invoked when channel is not in EOF state

By using debugger I saw the following data (I put only human readable data) still on socket causing libssh2_channel_eof to return 0:
Wscp: Failed to open file '/SCP/30175426-D12A-4EDE-99FE-6BA85AEE1ED2_0-IF_1_test.xml' 

I think that somehow SCP failed to read an error response and left some data on the socket. And because of that reported the upload as successful.

NOTE: I reproduced it with following curl command (see curl.log attached) :
curl -T 00.TIF scp://192.168.83.156/./SCP/ -u test:test -k -v --trace curl.log

### I expected the following
There was a permission issue on SolarWinds server causing the error. I would have expected curl to report the upload as failed 
### curl/libcurl version
curl 7.64.0 (i386-pc-win32) libcurl/7.64.0 OpenSSL/1.1.1a (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.8.0 nghttp2/1.36.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz brotli TLS-SRP HTTP2 HTTPS-proxy MultiSSL

### operating system
Windows 10 Enterprise 1809 10.0.17763.316 Client
[curl.log](https://github.com/curl/curl/files/2894875/curl.log)

**Comment by bagder** [comment]
To me this looks like a possible libssh2 flaw. curl enters the `SSH_SCP_WAIT_EOF` state to wait for EOF and only once that has been received it will move on to the `SSH_SCP_WAIT_CLOSE` state where it it calls libssh2 which then claims EOF hasn't arrived!?

**Comment by lsabouri74** [comment]
A bit of details I noticed while debugging.

1. function channel_wait_closed is called
2. channel_wait_closed calls libssh2_channel_eof
3. in libssh2_channel_eof, before checking the eof flag, there is a loop that checks that there is no SSH_MSG_CHANNEL_DATA or SSH_MSG_CHANNEL_EXTENDED_DATA remaining.

The issue is that it finds some unprocessed data in which I can see this:

> Wscp: Failed to open file '/SCP/30175426-D12A-4EDE-99FE-6BA85AEE1ED2_0-IF_1_test.xml'

So I am not sure why, but it seems that some data was not read/processed. It seems like an error response for the SCP server, but it was ignored by the libcurl/libssh2 and because of that even though file upload has failed, curl reports a success.

**Comment by bagder** [comment]
Can you provide a recipe on how to reproduce this? I still claim this is a libssh2 problem and not a curl one, unless you have anything else that contradicts that, this bug should rather be filed in that repo.

**Comment by lsabouri74** [comment]
1. Install SolarWinds SCP server (it is free for testing)
2. Use default setting and make sure SCP is enabled
3. Upload a file to SCP using following command:
`curl -T 00.TIF scp://192.168.83.156/./SCP/ -u test:test -k -v --trace curl.log`

curl will report upload as successful, but file is not uploaded. When debugging I can see so unread data is ssh buffers that says that the file failed to open (see my previous post). Somehow curl did not read that data and because of that did not report the error.

**Comment by lsabouri74** [comment]
> Can you provide a recipe on how to reproduce this? I still claim this is a libssh2 problem and not a curl one, unless you have anything else that contradicts that, this bug should rather be filed in that repo.

How do I report this on libssh2? The only way I know how to reproduce this is by using curl/libcurl.

**Comment by bagder** [comment]
Build one the SCP examples from the libssh2 project and see if that reproduces the problem? If so, then discuss with the libssh2 team or file an issue there. If it doesn't reproduce this problem, then it would rather indicate that the issue is somewhere within how curl is using libssh2.

**Comment by lsabouri74** [comment]
I was able to reproduce with a libssh2 example, so the issue seems to be in libssh2. I entered issue [#382](https://github.com/libssh2/libssh2/issues/382) on libssh2 github. I am closing this one.
