### ISSUE TITLE
Test 2043 can never be run

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#3609]
### I did this

```
./configure --enable-debug --without-ssl --with-winssl --enable-static --disable-shared && make && cd tests && make && ./runtests.pl 2043
```

Results in:
```
test 2043 SKIPPED: curl lacks WinSSL support
```

The test was added in https://github.com/curl/curl/commit/172b2beba6b89b632c09be7a88645e3a0607cfe9#diff-4dd1fa7586ffcf4267ac687f7604d9b7.

### I expected the following

The test to be run.

Probably related, test 1014 says:
```
test 1014...[Compare curl --version with curl-config --features]
Mismatch in features lists:
curl:        asynchdns ipv6 kerberos ntlm spnego ssl sspi
curl-config: asynchdns ipv6 kerberos ntlm spnego sspi winssl
```

### curl/libcurl version

```
********* System characteristics ********
* curl 7.64.1-20190225 (i686-w64-mingw32)
* libcurl/7.64.1-20190225 Schannel
* Features: AsynchDNS Debug TrackMemory IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
* Host: DevBuild-MS1
* System: MINGW32_NT-10.0 DevBuild-MS1 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: HTTP-IPv6 FTP-IPv6
* Env:
* Ports:
* HTTP/8990 FTP/8992 FTP2/8995 RTSP/9007
* TFTP/8997 HTTP-IPv6/8994 RTSP-IPv6/9008 FTP-IPv6/8996
* GOPHER/9009 GOPHER-IPv6/9010
* SSH/8999 SOCKS/9000 POP3/9001 IMAP/9003 SMTP/9005
* POP3-IPv6/9002 IMAP-IPv6/9004 SMTP-IPv6/9006
* HTTPTLS/9011 HTTPTLS-IPv6/9012
*****************************************
```
and
```
********* System characteristics ******** 
* curl 7.64.1-DEV (Windows) 
* libcurl/7.64.1-DEV Schannel
* Features: AsynchDNS Debug TrackMemory IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL 
* Host: APPVYR-WIN
* System: MSYS_NT-10.0 APPVYR-WIN 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: HTTP-IPv6 FTP-IPv6 
* Env: 
*****************************************
```

### operating system

MSYS2 using MinGW-w64 on Windows 10

**Comment by bagder** [comment]
The first problem is probably that `curl -V` now reports "Schannel" and not "winssl":

https://github.com/curl/curl/blob/66637b4d8fbc52aa1b57845cf45c7ccc7a95880f/lib/vtls/schannel.c#L2098

... while `runtests,pl` still looks for winssl:

https://github.com/curl/curl/blob/66637b4d8fbc52aa1b57845cf45c7ccc7a95880f/tests/runtests.pl#L2691

It should probably be made to look for both. Tests still depend on "winssl" so we better not break that (or we'd have to update the tests that do, if we want to change to only "schannel").

The test 1014 problem is weird and I haven't yet figured out why it happens. The feature should be "ssl" and not "winssl" but for some reason curl-config doesn't think so...

**Comment by bagder** [comment]
@MarcelRaad I'd appreciate if you could give my PR a test and see if that fixes this issue!
