### ISSUE TITLE
Proxy with SSL and multithreading

### ISSUE THREAD

**Issue by Lifeda92** [curl/curl#3638]
Hello. I want use proxies with ssl and multithreading.
But when i trying code below, sometimes i get APPCRASH.
Help me pls. Thanks.

I try this code:
~~~c
#define CURL_STATICLIB

#include <stdio.h>
#include <iostream>
#include <thread>
#include <string>
#include <vector>
#include "curl.h"
#include <fstream>
#include <future>
#include <mutex>

static size_t counter = 0;
static size_t proxyPos = 0;
static std::mutex mtx;

int writer(char *data, size_t size, size_t nmemb, std::string *buffer)
{
	int result = 0;
	if (buffer != NULL)
	{
		buffer->append(data, size * nmemb);
		result = size * nmemb;
	}
	return result;
}

static int thread_func(std::vector<std::string> *proxies, size_t id) {
	CURL *curl;
	CURLcode cRes;
	std::string buffer;
	std::string proxy;

	curl = curl_easy_init();
	if (curl) {
		mtx.lock();
		proxy = (*proxies)[proxyPos];
		if (proxyPos == proxies->size()) proxyPos = 0;
		else proxyPos++;
		mtx.unlock();

		curl_easy_setopt(curl, CURLOPT_URL, "https://google.com/");
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writer);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buffer);
		curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);

		curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str());
		curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);

		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

		cRes = curl_easy_perform(curl);
		curl_easy_cleanup(curl);
		
		std::lock_guard<std::mutex> lock(mtx);
		if (cRes != CURLE_OK) std::cout << ++counter << ": unsuccessful finished.\n";
		else std::cout << ++counter << ": successful finished.\n";

		return 0;
	}
	else {
		std::lock_guard<std::mutex> lock(mtx);
		std::cout << ++counter << ": unsuccessful finished.\n";

		return -1;
	}
}

int main() {
	std::vector<std::string> proxies;
	std::vector<std::future<int>> tArr;

	std::ifstream in;
	in.open("proxies.txt", std::ios_base::in);
	if (!in.is_open()) return -1;
	while (!in.eof()) {
		std::string buff;
		in >> buff;
		proxies.push_back(buff += '\n');
	}
	in.close();

	curl_global_init(CURL_GLOBAL_ALL);
	for (size_t i = 0; i < 80; ++i)
		tArr.push_back(std::async(std::launch::async, thread_func, &proxies, i));

	for (size_t i = 0, len = tArr.size(); i < len; ++i)
		tArr[i].get();

	getchar();

	return 0;
}

**Comment by Lifeda92** [comment]
I cant understand this: https://curl.haxx.se/libcurl/c/threaded-ssl.html 
Its one way?

**Comment by Lifeda92** [comment]
![default](https://user-images.githubusercontent.com/27778666/53687809-f723d500-3d41-11e9-873e-837ea41adda5.png)

**Comment by Lifeda92** [comment]
used this proxies

`139.199.113.249:1080
106.13.85.20:1080
132.145.36.9:1080
142.93.97.91:1080
222.186.45.65:50055
140.143.247.221:1080
222.186.45.65:64621
222.186.45.133:51380
222.186.45.116:60063
222.186.45.65:56302
222.186.45.65:53098
193.112.189.52:21071
222.186.45.120:61504
169.239.221.90:50802
222.186.45.120:51168
222.186.45.65:53806
222.186.45.120:51112
222.186.45.133:62200
222.186.45.133:53766
222.186.45.120:59733
222.186.45.120:55884
222.186.45.120:54031
222.186.45.120:53846
222.186.45.120:53335
222.186.45.120:53218
222.186.45.120:51646
222.186.45.120:49449
222.186.45.120:50317
222.186.45.120:50536
222.186.45.120:50381
222.186.45.120:60933
222.186.45.120:54240
222.186.45.120:64869
222.186.45.120:64464
222.186.45.120:62368
222.186.45.120:61871
192.169.237.123:62428
192.169.233.35:41502
118.24.177.211:1080
118.24.28.26:1080
47.94.19.105:3001
41.85.184.122:9999
129.28.124.245:1080
193.112.212.15:21071
54.39.16.26:64802
193.112.216.235:21071
222.186.45.144:60421
222.186.45.133:57509
222.186.45.133:52488
222.186.45.120:61904
222.186.45.133:52287
207.154.221.152:1080
182.61.18.142:1080
222.186.45.127:53299
222.186.45.127:49920
222.186.45.133:63239
222.186.45.126:49589
222.186.45.127:57250
222.186.45.133:52436
222.186.45.126:51234
222.186.45.133:58433
193.112.187.5:21071
222.186.45.133:61835
193.112.165.236:21071
193.112.127.1:21071
54.38.81.12:40967
222.186.45.133:64522
193.112.168.41:21071
193.112.168.78:21071
193.112.195.9:21071
193.112.198.74:21071
54.39.16.26:37318
45.125.223.38:52868
222.186.45.133:64690
182.113.54.181:1080
119.3.87.145:1080
129.28.123.163:1080
119.3.81.219:1080
193.112.153.111:21071
193.112.128.218:21071
50.63.13.135:53104
47.101.134.138:1080
148.70.14.248:1080
132.148.13.47:43773
18.236.101.165:1080
118.190.206.86:9999
87.228.31.93:9999
39.104.82.178:1080
222.186.45.127:64098
222.186.45.127:52493
222.186.45.127:52077
222.186.45.127:51786
192.3.45.252:1080
222.186.45.126:62923
222.186.45.126:51467
162.243.251.78:47837
114.116.124.81:1080
222.186.45.127:64771
222.186.45.127:53700
54.38.81.12:36260
106.12.81.217:1080
129.28.72.203:1080
54.38.81.12:58868
54.38.81.12:52085
120.31.71.224:9999
148.70.210.13:1080
47.93.251.207:3001
193.112.142.34:21071
47.98.38.247:1080
150.109.198.17:1080
45.76.187.188:21345
77.247.94.153:8888
222.186.45.133:61329
222.186.45.115:60923
47.94.244.28:3001
192.169.189.215:38953
119.23.238.228:1080
120.79.191.248:1080
192.169.237.19:38699
192.169.232.12:55017
193.112.58.184:1080
193.112.187.8:21071
113.106.122.226:1080
123.207.147.126:1080
193.112.129.155:21071
193.112.172.132:21071
193.112.163.8:21071
193.112.163.6:21071
193.112.158.103:21071
193.112.138.1:21071
193.112.138.5:21071
193.112.185.192:21071
128.127.57.150:9999
162.243.7.181:39276
94.130.1.45:1080
80.11.233.17:38711
178.62.200.107:1080
222.186.45.116:51907
50.63.13.254:23889
129.28.75.80:1080
139.159.181.199:1080
47.106.74.192:1080
166.62.85.232:16397
129.28.112.95:1080
111.223.75.178:8888
148.70.73.204:1080
123.206.190.11:9999
47.104.199.230:1080
54.39.16.26:43992
118.25.20.177:9999
59.61.220.148:1080
104.225.218.185:58094
193.112.221.61:21071
193.112.194.8:21071
129.28.88.250:1080
193.112.188.9:21071
193.112.123.218:21071
193.112.203.5:21071
193.112.185.198:21071
193.112.172.47:21071
193.112.127.3:21071
193.112.215.70:21071
193.112.175.196:21071
193.112.127.191:21071
193.112.195.2:21071
92.243.31.212:29089
222.186.45.127:55821
132.148.142.205:47281
149.56.27.45:1080
132.148.3.216:64529
118.24.7.218:1080
138.68.143.47:16500
193.150.121.70:1080
198.50.217.202:1080
35.185.64.205:1080
222.186.45.133:62787
192.109.76.91:1080
192.169.193.54:20322
192.169.156.211:19561
193.112.153.5:21071
193.112.142.35:21071
149.202.136.73:3128
193.112.129.117:21071
193.112.125.58:21071
162.243.210.52:54433
178.62.159.94:54346
50.63.132.99:64232
163.172.164.90:12080
132.148.143.175:20954
172.104.245.70:1080
86.120.134.23:1080
123.206.27.132:1080
108.46.171.184:45093
193.112.184.7:21071
129.28.88.52:1080
193.112.203.7:21071
193.112.211.3:21071
139.224.239.129:443
209.124.69.39:13964
193.112.245.35:21071
193.112.185.141:21071
193.112.182.7:21071
72.66.6.184:39874
94.55.226.62:1080
129.28.123.104:1080
129.28.123.53:1080
78.205.51.30:21026
193.112.144.10:21071
193.112.169.7:21071
193.112.215.210:21071
193.112.155.228:21071
118.190.107.191:1080
193.112.177.163:21071
95.110.227.5:60703
5.160.89.51:18916
94.177.240.6:443
193.112.244.154:21071
193.112.195.7:21071`

**Comment by Lifeda92** [comment]
used this proxies (SOCKS5) but with HTTPS sometimes APPCRASH too.

139.199.113.249:1080
106.13.85.20:1080
132.145.36.9:1080
142.93.97.91:1080
222.186.45.65:50055
140.143.247.221:1080
222.186.45.65:64621
222.186.45.133:51380
222.186.45.116:60063
222.186.45.65:56302
222.186.45.65:53098
193.112.189.52:21071
222.186.45.120:61504
169.239.221.90:50802
222.186.45.120:51168
222.186.45.65:53806
222.186.45.120:51112
222.186.45.133:62200
222.186.45.133:53766
222.186.45.120:59733
222.186.45.120:55884
222.186.45.120:54031
222.186.45.120:53846
222.186.45.120:53335
222.186.45.120:53218
222.186.45.120:51646
222.186.45.120:49449
222.186.45.120:50317
222.186.45.120:50536
222.186.45.120:50381
222.186.45.120:60933
222.186.45.120:54240
222.186.45.120:64869
222.186.45.120:64464
222.186.45.120:62368
222.186.45.120:61871
192.169.237.123:62428
192.169.233.35:41502
118.24.177.211:1080
118.24.28.26:1080
47.94.19.105:3001
41.85.184.122:9999
129.28.124.245:1080
193.112.212.15:21071
54.39.16.26:64802
193.112.216.235:21071
222.186.45.144:60421
222.186.45.133:57509
222.186.45.133:52488
222.186.45.120:61904
222.186.45.133:52287
207.154.221.152:1080
182.61.18.142:1080
222.186.45.127:53299
222.186.45.127:49920
222.186.45.133:63239
222.186.45.126:49589
222.186.45.127:57250
222.186.45.133:52436
222.186.45.126:51234
222.186.45.133:58433
193.112.187.5:21071
222.186.45.133:61835
193.112.165.236:21071
193.112.127.1:21071
54.38.81.12:40967
222.186.45.133:64522
193.112.168.41:21071
193.112.168.78:21071
193.112.195.9:21071
193.112.198.74:21071
54.39.16.26:37318
45.125.223.38:52868
222.186.45.133:64690
182.113.54.181:1080
119.3.87.145:1080
129.28.123.163:1080
119.3.81.219:1080
193.112.153.111:21071
193.112.128.218:21071
50.63.13.135:53104
47.101.134.138:1080
148.70.14.248:1080
132.148.13.47:43773
18.236.101.165:1080
118.190.206.86:9999
87.228.31.93:9999
39.104.82.178:1080
222.186.45.127:64098
222.186.45.127:52493
222.186.45.127:52077
222.186.45.127:51786
192.3.45.252:1080
222.186.45.126:62923
222.186.45.126:51467
162.243.251.78:47837
114.116.124.81:1080
222.186.45.127:64771
222.186.45.127:53700
54.38.81.12:36260
106.12.81.217:1080
129.28.72.203:1080
54.38.81.12:58868
54.38.81.12:52085
120.31.71.224:9999
148.70.210.13:1080
47.93.251.207:3001
193.112.142.34:21071
47.98.38.247:1080
150.109.198.17:1080
45.76.187.188:21345
77.247.94.153:8888
222.186.45.133:61329
222.186.45.115:60923
47.94.244.28:3001
192.169.189.215:38953
119.23.238.228:1080
120.79.191.248:1080
192.169.237.19:38699
192.169.232.12:55017
193.112.58.184:1080
193.112.187.8:21071
113.106.122.226:1080
123.207.147.126:1080
193.112.129.155:21071
193.112.172.132:21071
193.112.163.8:21071
193.112.163.6:21071
193.112.158.103:21071
193.112.138.1:21071
193.112.138.5:21071
193.112.185.192:21071
128.127.57.150:9999
162.243.7.181:39276
94.130.1.45:1080
80.11.233.17:38711
178.62.200.107:1080
222.186.45.116:51907
50.63.13.254:23889
129.28.75.80:1080
139.159.181.199:1080
47.106.74.192:1080
166.62.85.232:16397
129.28.112.95:1080
111.223.75.178:8888
148.70.73.204:1080
123.206.190.11:9999
47.104.199.230:1080
54.39.16.26:43992
118.25.20.177:9999
59.61.220.148:1080
104.225.218.185:58094
193.112.221.61:21071
193.112.194.8:21071
129.28.88.250:1080
193.112.188.9:21071
193.112.123.218:21071
193.112.203.5:21071
193.112.185.198:21071
193.112.172.47:21071
193.112.127.3:21071
193.112.215.70:21071
193.112.175.196:21071
193.112.127.191:21071
193.112.195.2:21071
92.243.31.212:29089
222.186.45.127:55821
132.148.142.205:47281
149.56.27.45:1080
132.148.3.216:64529
118.24.7.218:1080
138.68.143.47:16500
193.150.121.70:1080
198.50.217.202:1080
35.185.64.205:1080
222.186.45.133:62787
192.109.76.91:1080
192.169.193.54:20322
192.169.156.211:19561
193.112.153.5:21071
193.112.142.35:21071
149.202.136.73:3128
193.112.129.117:21071
193.112.125.58:21071
162.243.210.52:54433
178.62.159.94:54346
50.63.132.99:64232
163.172.164.90:12080
132.148.143.175:20954
172.104.245.70:1080
86.120.134.23:1080
123.206.27.132:1080
108.46.171.184:45093
193.112.184.7:21071
129.28.88.52:1080
193.112.203.7:21071
193.112.211.3:21071
139.224.239.129:443
209.124.69.39:13964
193.112.245.35:21071
193.112.185.141:21071
193.112.182.7:21071
72.66.6.184:39874
94.55.226.62:1080
129.28.123.104:1080
129.28.123.53:1080
78.205.51.30:21026
193.112.144.10:21071
193.112.169.7:21071
193.112.215.210:21071
193.112.155.228:21071
118.190.107.191:1080
193.112.177.163:21071
95.110.227.5:60703
5.160.89.51:18916
94.177.240.6:443
193.112.244.154:21071
193.112.195.7:21071

**Comment by bagder** [comment]
If you think this is a curl related problem then please help us understand where and how it crashes and why you think this is a curl problem.

**Comment by Lifeda92** [comment]
Program crash when i using proxy with SSL connection 
All is good, if i delete this: curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str()); Or if i change curl_easy_setopt(curl, CURLOPT_URL, "https://google.com/"); "https" to "http" like this curl_easy_setopt(curl, CURLOPT_URL, "http://google.com/");
Why program crash when i using proxies?

**Comment by Lifeda92** [comment]
Sometimes program not crash. But sometimes it crash... 
I think, maybe some kind of proxy list can affect

**Comment by Lifeda92** [comment]
sometimes there are proxies for which curl hangs.

**Comment by Lifeda92** [comment]
Without proxies program never crash. Why?

**Comment by Lifeda92** [comment]
Using SSL connection without proxies with multithreading and never crash. Byt with some proxies it crash.

**Comment by bagder** [comment]
Don't mix matters and add more things into this single issue. Stick to the topic. Please don't just post numerous single-line comments, you'll appear as a lunatic.

Please elaborate and be specific. Exactly which libcurl function crashes and what's the result. Ideally, you provide us with a (complete) sample program that reproduces the crash. If it crashes in libcurl, have you tried building a debug version to see where within libcurl the crash happens?

What libcurl version are you using and on what platform does it run?

Do you follow the multi threading guidelines when you use multiple threads?

**Comment by Lifeda92** [comment]
i just used socks4 proxy, its work great. But with some https or socks5 proxies it was crush. 
If all work with socks4 type proxy, then in my code all ok i think.
I using curl-7.64.0 and windows 7 sp1
When i using:
curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str());
curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5); or curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_HTTPS);
I have APPCRASH somtimes, whith some proxy not all proxy.

When i using:
curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str());
curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS4);
All is great, no APPCRASH.

I grab proxies from https://best-proxies.ru

**Comment by Lifeda92** [comment]
I dont know why curl crash with some socks5 or https proxies.

**Comment by Lifeda92** [comment]
I testing. Socks4 crashes too but very very rare. One crash to 10000 connection. I think its because curl so reacts to some proxies.

**Comment by jay** [comment]
**We need the curl_version().** Both the form you filled out and a member have asked you for that information. We aren't going to investigate without that information. Also please make sure you are following the [thread safety guidelines](https://curl.haxx.se/libcurl/c/threadsafe.html).

**Comment by Lifeda92** [comment]
I using curl-7.64.0 on windows 7 sp1 and VS 2017

I using CURL like this code:
`#define CURL_STATICLIB

#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <thread>
#include <mutex>

#include "curl.h"

static size_t t_count = 40;
static const char *proxiesWay = "proxies.txt";

static int writer(char *data, size_t size, size_t nmemb, std::string *buffer) {
	int result = 0;

	if (buffer != NULL) {
		buffer->append(data, size * nmemb);
		result = size * nmemb;
	}
	return result;
}

static std::mutex mtx;
static void thread_func(std::vector<std::string> *proxies) {
	CURL *curl;
	std::string buffer;
	std::string proxy;
	static size_t proxyPos = 0;

	curl = curl_easy_init();
	if (curl) {
		mtx.lock();
		proxy = (*proxies)[proxyPos++];
		if (proxyPos == proxies->size()) proxyPos = 0;
		mtx.unlock();

		curl_easy_setopt(curl, CURLOPT_URL, "https://google.com/");
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writer);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buffer);
		curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);

		curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str()); // i think problem here, when i using some proxy with ssl connection
		curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);

		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

		curl_easy_perform(curl);

		curl_easy_cleanup(curl);
	}
}

int main() {
	std::vector<std::string> proxies;
	std::vector<std::thread> tArr;

	try {
		std::ifstream in;
		in.open(proxiesWay, std::ios_base::in);
		if (!in.is_open()) throw std::exception("Cant open file with proxies.");
		while (!in.eof()) {
			std::string buff;
			in >> buff;
			proxies.push_back(buff += '\n');
		}
		in.close();

		curl_global_init(CURL_GLOBAL_ALL);
		for (size_t i = 0; i < t_count; ++i)
			tArr.push_back(std::thread(thread_func, &proxies));

		for (size_t i = 0, len = tArr.size(); i < len; ++i)
			tArr[i].join();

	}
	catch (std::exception &e) {
		std::cerr << e.what() << std::endl;
	}

	getchar();

	return 0;
}`

**Comment by jay** [comment]
~~~c
proxy = (*proxies)[proxyPos];
if (proxyPos == proxies->size()) proxyPos = 0;
else proxyPos++;
~~~
not a curl problem. run your code in debug not release.

**Comment by Lifeda92** [comment]
I'm sorry I did not write correctly.

I changed the code here:

`mtx.lock();
proxy = (*proxies)[proxyPos++];
if (proxyPos == proxies->size()) proxyPos = 0;
mtx.unlock();`

Try this code:
`#define CURL_STATICLIB

#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <thread>
#include <mutex>

#include "curl.h"

static const size_t t_count = 40;
static const char *proxiesWay = "proxies.txt";

static int writer(char *data, size_t size, size_t nmemb, std::string *buffer) {
	int result = 0;

	if (buffer != NULL) {
		buffer->append(data, size * nmemb);
		result = size * nmemb;
	}
	return result;
}

static std::mutex mtx;
static void thread_func(std::vector<std::string> *proxies) {
	CURL *curl;
	std::string buffer;
	std::string proxy;
	static size_t proxyPos = 0;

	curl = curl_easy_init();
	if (curl) {
		mtx.lock();
		proxy = (*proxies)[proxyPos++]; // first get then increase
		if (proxyPos == proxies->size()) proxyPos = 0;
		mtx.unlock();

		curl_easy_setopt(curl, CURLOPT_URL, "https://google.com/");
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writer);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buffer);
		curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10);

		curl_easy_setopt(curl, CURLOPT_PROXY, proxy.c_str()); // i think problem here, when i using some proxy with ssl connection
		curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);

		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

		curl_easy_perform(curl);

		curl_easy_cleanup(curl);
	}
}

int main() {
	std::vector<std::string> proxies;
	std::vector<std::thread> tArr;

	try {
		std::ifstream in;
		in.open(proxiesWay, std::ios_base::in);
		if (!in.is_open()) throw std::exception("Cant open file with proxies.");
		while (!in.eof()) {
			std::string buff;
			in >> buff;
			proxies.push_back(buff += '\n');
		}
		in.close();

		curl_global_init(CURL_GLOBAL_ALL);
		for (size_t i = 0; i < t_count; ++i)
			tArr.push_back(std::thread(thread_func, &proxies));

		for (size_t i = 0; i < t_count; ++i)
			tArr[i].join();

	}
	catch (std::exception &e) {
		std::cerr << e.what() << std::endl;
	}

	getchar();

	return 0;
}`

You can try analogy code with proxyPos: [cpp.sh/4jrf7](url)

**Comment by bagder** [comment]
see [my earlier comment](https://github.com/curl/curl/issues/3638#issuecomment-468968984)

**Comment by Lifeda92** [comment]
You can try with this proxies: cpp.sh/3r6s6

**Comment by bagder** [comment]
And when you run your code in debug mode where does it crash and why?

**Comment by Lifeda92** [comment]
![5](https://user-images.githubusercontent.com/27778666/53698162-9350e900-3de1-11e9-923d-edd64e2fa852.png)

**Comment by bagder** [comment]
Aha! I think you see a bug that was already fixed, since this commit: 4015fae044c (issue #3542)

**Comment by Lifeda92** [comment]
Nice! I need change the url.c for https://github.com/curl/curl/blob/4015fae044ce52a639c9358e22a9e948f287c89f/lib/url.c
and rebuild. Yes?

**Comment by bagder** [comment]
I would recommend checking out the full tree from the current git master, then build and try that.

**Comment by Lifeda92** [comment]
Ok, thank you. I will try

**Comment by Lifeda92** [comment]
I builded. Tested with differrent proxies. Great works. Thx!

**Comment by bagder** [comment]
Cool, thanks for confirming. Then this case is closed!
