### ISSUE TITLE
Issue with curl_multi and curl_error returning errors for successful requests in PHP

### ISSUE THREAD

**Issue by jonthemiller** [curl/curl#3652]
### I did this

We have a library built on cURL in our PHP webapp to make requests/etc. We noticed in the latest cURL version, the PHP function `curl_error` will return an error for a second batch of requests even if the request itself was successful. I tested multiple versions of PHP, from 7.1 to the latest 7.3.2 and it only manifests when cURL 7.64.0 is installed. Please let me know if this issue is not with cURL but instead with PHP or the [docker image](https://github.com/docker-library/php/blob/master/7.3/alpine3.9/fpm/Dockerfile).

#### Test script:

    <?php

    class CurlTest
    {
        public function __construct()
        {
            $this->setupRequests(['https://www.cnet.com/reviews/']);
            $this->sendRequests();

            $this->setupRequests(['https://www.cnet.com', 'https://www.cnet.com/news/']);
            $this->sendRequests();
        }

        public function sendRequests()
        {
            do {
                if (empty($this->requests)) {
                    curl_multi_close($this->multi);
                    return;
                }
                $active = $this->doSocketPerform();

                if ($active) {
                    // give multi select a low timeout
                    if (curl_multi_select($this->multi, 0.001) == -1) {
                        if (empty($noSelectSince)) {
                            $noSelectSince = microtime(true);
                        } else if (microtime(true) - $noSelectSince > 400) {
                            throw new \Exception('Could not select socket after 400 usec.');
                        }

                        // see http://php.net/manual/en/function.curl-multi-select.php#115381
                        usleep(1);
                    } else {
                        $noSelectSince = null;
                    }
                }
            } while (true);
        }

        public function setupRequests($urlsToRequest = [])
        {
            $this->multi = curl_multi_init();
            $this->requests = [];

            foreach ($urlsToRequest as $url) {
                $request = curl_init();
                curl_setopt($request, CURLOPT_URL, $url);
                curl_setopt($request, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($request, CURLOPT_CUSTOMREQUEST, 'GET');
                curl_setopt($request, CURLOPT_TIMEOUT, 5);
                curl_setopt($request, CURLOPT_CONNECTTIMEOUT, 1);
                $this->requests[(string) $request] = $request;

                curl_multi_add_handle($this->multi, $request);
                echo "added request to '{$url}'\n";
            }
        }

        public function doSocketPerform()
        {
            $active = false;

            curl_multi_exec($this->multi, $active);

            while ($info = curl_multi_info_read($this->multi)) {
                // if the given request isn't done yet, keep looping
                if ($info['msg'] !== CURLMSG_DONE) {
                    continue;
                }
                $key = (string) $info['handle'];

                curl_multi_remove_handle($this->multi, $this->requests[$key]);
                $url = curl_getinfo($this->requests[$key], CURLINFO_EFFECTIVE_URL);
                $resCode = curl_getinfo($this->requests[$key], CURLINFO_HTTP_CODE);
                $error = curl_error($this->requests[$key]);
                echo "request to '{$url}', response code: '{$resCode}', error string: '{$error}'\n";
                unset($this->requests[$key]);
            }

            return $active;
        }
    }

    echo 'cURL version: ' . curl_version()['version'] . "\n";
    $test = new CurlTest();

#### Bad result:

    $ docker run -v ~/src/cnet/web/curl_test.php:/var/www/html/curl_test.php php:7.3-fpm-alpine sh -c "apk upgrade && php curl_test.php"
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
    (1/4) Upgrading libcurl (7.63.0-r0 -> 7.64.0-r1)
    (2/4) Upgrading curl (7.63.0-r0 -> 7.64.0-r1)
    (3/4) Upgrading tar (1.31-r0 -> 1.32-r0)
    (4/4) Upgrading libxml2 (2.9.9-r0 -> 2.9.9-r1)
    Executing busybox-1.29.3-r10.trigger
    OK: 18 MiB in 32 packages
    cURL version: 7.64.0
    added request to 'https://www.cnet.com/reviews/'
    request to 'https://www.cnet.com/reviews/', response code: '200', error string: ''
    added request to 'https://www.cnet.com'
    added request to 'https://www.cnet.com/news/'
    request to 'https://www.cnet.com/news/', response code: '200', error string: ''
    request to 'https://www.cnet.com', response code: '200', error string: 'Could not resolve host: www.cnet.com'

The call to `curl_error` for the 3rd request returns 'Could not resolve host: www.cnet.com' even though the request succeeded. 

### I expected the following

    $ docker run -v ~/src/cnet/web/curl_test.php:/var/www/html/curl_test.php php:7.3-fpm-alpine php curl_test.php
    cURL version: 7.63.0
    added request to 'https://www.cnet.com/reviews/'
    request to 'https://www.cnet.com/reviews/', response code: '200', error string: ''
    added request to 'https://www.cnet.com'
    added request to 'https://www.cnet.com/news/'
    request to 'https://www.cnet.com/news/', response code: '200', error string: ''
    request to 'https://www.cnet.com', response code: '200', error string: ''

### curl/libcurl version

curl 7.64.0 (x86_64-alpine-linux-musl) libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 libssh2/1.8.0 nghttp2/1.35.1
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

### operating system
PHP 7.3.2/7.2.15/7.1.26, Alpine 3.9

**Comment by jzakrzewski** [comment]
It looks a lot like #3629 which is in fact not a curl bug but has been addressed in #3630 nevertheless. Please see the aforementioned entities for details.

**Comment by jonthemiller** [comment]
Yes, that looks exactly like it. Will close this one in that case.
