### ISSUE TITLE
Running curl with --doh-url seems to turn on verbose output

### ISSUE THREAD

**Issue by bikeseat** [curl/curl#3660]
### I did this
`curl --doh-url https://1.1.1.1/dns-query ipinfo.io/8.8.8.8`

### I expected the following
I expected non-verbose output. This gives me what I expect
`curl --doh-url https://1.1.1.1/dns-query ipinfo.io/8.8.8.8 2>/dev/null`

### curl/libcurl version
`curl 7.64.1-DEV (x86_64-apple-darwin18.2.0) libcurl/7.64.1-DEV SecureTransport zlib/1.2.11 libidn2/2.1.1 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets`

### operating system
macOS Mojave 10.14.3 (18D109)

**Comment by jay** [comment]
Confirmed.
~~~diff
diff --git a/lib/doh.c b/lib/doh.c
index f06ed33..746b8ca 100644
--- a/lib/doh.c
+++ b/lib/doh.c
@@ -242,7 +242,6 @@ static CURLcode dohprobe(struct Curl_easy *data,
     ERROR_CHECK_SETOPT(CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);
 #endif
     ERROR_CHECK_SETOPT(CURLOPT_TIMEOUT_MS, (long)timeout_ms);
-    ERROR_CHECK_SETOPT(CURLOPT_VERBOSE, 1L);
     doh->set.fmultidone = Curl_doh_done;
     doh->set.dohfor = data; /* identify for which transfer this is done */
     p->easy = doh;
~~~
@bagder left in by accident?

**Comment by jay** [comment]
on second thought it should inherit from the easy handle
~~~diff
diff --git a/lib/doh.c b/lib/doh.c
index f06ed33..5040248 100644
--- a/lib/doh.c
+++ b/lib/doh.c
@@ -242,7 +242,8 @@ static CURLcode dohprobe(struct Curl_easy *data,
     ERROR_CHECK_SETOPT(CURLOPT_PROTOCOLS, CURLPROTO_HTTPS);
 #endif
     ERROR_CHECK_SETOPT(CURLOPT_TIMEOUT_MS, (long)timeout_ms);
-    ERROR_CHECK_SETOPT(CURLOPT_VERBOSE, 1L);
+    if(data->set.verbose)
+      ERROR_CHECK_SETOPT(CURLOPT_VERBOSE, 1L);
     doh->set.fmultidone = Curl_doh_done;
     doh->set.dohfor = data; /* identify for which transfer this is done */
     p->easy = doh;
~~~

also what's a good test site for doh, I tried cloudflare but it's not working
curld -v --doh-url https://cloudflare-dns.com/dns-query http://www.test.com
...
* DOH: Too small type A for www.test.com
* DOH: Too small type AAAA for www.test.com

**Comment by bagder** [comment]
> left in by accident?

Oops...

**Comment by jay** [comment]
Thanks
