### ISSUE TITLE
Host header must be identical to the authority component of an absolute target URI

### ISSUE THREAD

**Issue by dunjut** [curl/curl#3664]
### I did this

```
curl -v http://192.168.99.100:8080/hi -H 'Host: hi.foo.com' -x http://127.0.0.1:20000
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 20000 (#0)
> GET http://192.168.99.100:8080/hi HTTP/1.1
> Host: hi.foo.com
> User-Agent: curl/7.58.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
```

### I expected the following

Per [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.4):
```
A client MUST send a Host header field in all HTTP/1.1 request
   messages.  If the target URI includes an authority component, then a
   client MUST send a field-value for Host that is identical to that
   authority component
...
When a proxy receives a request with an absolute-form of
   request-target, the proxy MUST ignore the received Host header field
   (if any) and instead replace it with the host information of the
   request-target.  A proxy that forwards such a request MUST generate a
   new Host field-value based on the received request-target rather than
   forward the received Host field-value.
```

Host header in the sending request must be 192.168.99.100:8080

### curl/libcurl version

curl 7.58.0 (x86_64-apple-darwin16.3.0) libcurl/7.58.0 OpenSSL/1.0.2p zlib/1.2.8 nghttp2/1.31.0
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

### operating system

Darwin mbp-4.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
Sorry but I don't understand.

You tell curl you want to use a custom `Host:` header in the request so you provide that one.

Then you file a bug that curl uses that custom `Host:` header and not the "real" `Host:` header that the spec says should be used? Can you elaborate a little more on exactly you wanted your command line to do that it didn't?

**Comment by dunjut** [comment]
@bagder Thanks for the quick reply.

One of our customers complains that

```
curl -v http://192.168.99.100:8080/hi -H 'Host: hi.foo.com'
```
works well, but failed when curl through our proxy:

```
curl -v http://192.168.99.100:8080/hi -H 'Host: hi.foo.com' -x <proxyAddress>
```

IMHO, in the latter case, users may not be aware of what they are doing is wrong, so I expect curl ignores the custom Host header and maybe throw a warning, because that violates RFC spec.

**Comment by jzakrzewski** [comment]
I don't think it should. The point is curl does the right thing by default. If you overwrite the defaults it's basically telling curl "I know better what must be done". And this behaviour is quite useful if you have some weird/broken servers or you're testing your own implementation of something.

**Comment by dunjut** [comment]
>this behaviour is quite useful if you have some weird/broken servers or you're testing your own implementation of something

@jzakrzewski I second this but let users do what is wrong without at least a warning is not good, and that brings confusion. I don't think they really 'know better what must be done', they don't...

**Comment by jzakrzewski** [comment]
The rule of the thumb is: If you touched the defaults an it doesn't work, stop touching the defaults! If curl always assumed the user does not know what they're doing, it would have to warn about every other option!

**Comment by bagder** [comment]
> expect curl ignores the custom Host header and maybe throw a warning, because that violates RFC spec.

The first case (that works for this user) violates the spec at least as much as the second case. The `-H` option is there for the user to craft and change their requests as they see fit. I don't think displaying a warning for every time that command line option is used will serve any user or do any good. On the contrary I think that would only add to "warning fatigue".

**Comment by dunjut** [comment]
Using `-H` under a relative target request is totally valid thus shouldn't be warned, this is not the same kind of case as I issued.

As I see, warnings shouldn't be full of a lot or the contrast no one at all. I suggest warning at critical circumstances and other cases that are frequently misused.

**Comment by bagder** [comment]
> Using -H under a relative target request is totally valid thus shouldn't be warned

You mean `-H Host:*` (since `-H` can be used to passed in basically anything).

Sending a custom Host: header value is specifically against what the spec says. Without a `-H Host:` command line option, curl already acts exactly as the spec mandates and uses the spec compliant header. Using the -H option to alter what Host: header to send will make it *not* follow the spec.

That way of not following the spec is typically what a user wants when this option is used. In your two cases above, curl does what the command line says and it violates what the spec says in *both* cases. Yet in one of the cases the end result was what the user expected and the other it wasn't. I cannot see how curl could anticipate that and I also cannot see what curl would warn a user for here.

Besides, a user who doesn't already understand what breakage a `-H Host:` can cause most likely would not understand a warning about "sending Host: when using a HTTP proxy might not do what the user wants".

**Comment by dunjut** [comment]
Could you please leave a reference about `sending a custom Host header violates the spec`?

Not for arguing here, just because I always think one server serves different services by different Hosts is a very common use case. I'm starting to doubting myself... :-(

Thanks, really appreciate!

**Comment by jay** [comment]
This isn't a bug. curl didn't violate the RFC, your customer did. Nevermind that sometimes there are good reasons to do so. I don't think we should be expected to cover these cases with a warning.

**Comment by jay** [comment]
If the proxy supports tunneling add [--proxytunnel](https://curl.haxx.se/docs/manpage.html#-p) to the command line to tunnel the connection to the server through the proxy. The proxy will not interfere with the headers in that case afaik because it's just bouncing the TCP stream.
