### ISSUE TITLE
Response FIN-ACK not sent in HTTPS connection

### ISSUE THREAD

**Issue by nachopol** [curl/curl#3665]
### I did this
I'm using a client using libcurl to send several REST POST requests to a mockoon REST Server (HTTP/1.1) using both HTTP and HTTPS.
The server eventually tries to close the connection by sending a FIN message to the libcurl client and when I try to send a new request with _curl_easy_perform_:

- If HTTP, libcurl first sends a FIN-ACK response and then the new request (that's correct). [capture 1]
- If HTTPS, libcurl directly tries to send the new request, so the sever sends a RST. Then libcurl use to restart the SSL connection and resend the new message [capture 2]. This is the usual behaviour but sometimes does nothing after the RST (neither the SSL connection nor the the resend) and the request is finally discarded [capture 3].

Please, find attached the wireshark captures. Each request-response is shown with a brace on the left (I hope it's all clear enough)

### I expected the following
In HTTPS, libcurl should send the FIN-ACK response and then reconnect before sending the new request as in HTTP.

### curl/libcurl version
curl 7.36.0 (i786-stratus-vos) libcurl/7.36.0 OpenSSL/1.0.2n zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

### operating system
OpenVOS Release 19.1.0ap (Stratus) 

**[capture 1 - HTTP OK]**
![libcurl_http_OK](https://user-images.githubusercontent.com/10621498/54116451-1b8d4a80-43ef-11e9-8ab1-aabbd6126276.JPG)

**[capture 2 - HTTPS FIN just responded after RST but request resent]**
![libcurl_https_NoOK](https://user-images.githubusercontent.com/10621498/54116459-22b45880-43ef-11e9-8736-918f06555784.JPG)

**[capture 3 - HTTPS FIN request discarded]**
![libcurl_https_NoOK_Request_discarded](https://user-images.githubusercontent.com/10621498/54116458-221bc200-43ef-11e9-9f25-7bf5f3c8274c.JPG)

**Comment by bagder** [comment]
I realize you don't want me to say this, but I need to say it anyway: you're using a **5** years old curl version. I think it is highly unlikely that this is an existing issue in the current version, so I think you'd benefit from trying out a modern version first before spending more time on this issue.

**Comment by nachopol** [comment]
Haha, I understand. This is the version currently installed in our systems. I'm checking with the manufacturer what's the latest version ported to OpenVOS.

In the meantime, let me try to reproduce the same issue in Windows with the latest curl version just to check if it has the same behaviour so we can leave the issue opened or close it. I'll keep you informed asap

**Comment by bagder** [comment]
Thanks!

**Comment by nachopol** [comment]
Hi again. I've tried with latest version provided for CYGWIN (7.59) with same both behaviours when using HTTPS.

Let me know if you need further details to reproduce the issue.

curl --version:
curl 7.59.0 (i686-pc-cygwin) libcurl/7.59.0 OpenSSL/1.0.2r zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh2/1.7.0 nghttp2/1.31.0
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

**Comment by bagder** [comment]
Yes please, tell us how to reproduce.

(and surely you can build the latest version for cygwin?)

**Comment by nachopol** [comment]
Please find attached a source cpp example tu reproduce the issue. 

To use it you have to use a REST https server which eventually closes connections. In my test environment I've used mockoon [https://mockoon.com/]. You have to configure the url provided by this server in line 209 of the source
`	strcpy(url, "https://your_rest_https_server:3000/dolphins");`

Sorry but I don't know how to build the latest version. Do you suspect this issue could have been solved since version 7.59?

[example.zip](https://github.com/curl/curl/files/2956311/example.zip)

**Comment by nachopol** [comment]
Despite what I said posts ago, in this version I'm not currently getting any timeout, libcurl always resends the requests. It's not the same behaviour as in http and maybe is not the best way to handle the server closing connections but I think it would work and no request is lost, so I don't know if it's still an issue or not... your choice.

Anyway, if you want to go ahead, what I see from gdb is that libcurl tries to close the socket in url.c _conn_free_ function in this code lines:

```
  if(CURL_SOCKET_BAD != conn->sock[FIRSTSOCKET])
    Curl_closesocket(conn, conn->sock[FIRSTSOCKET]);
```
then it eventually closes the socket but after sending the request through the same socket (I couldn't find where it is done). After all that, libcurl resends the request.

The stack is:
#0  conn_free (conn=conn@entry=0x20071508)
    at /usr/src/debug/curl-7.59.0-1/lib/url.c:667
#1  0x6faf4e57 in Curl_disconnect (conn=0x20071508,
    dead_connection=dead_connection@entry=true)
    at /usr/src/debug/curl-7.59.0-1/lib/url.c:790
#2  0x6faf8d82 in prune_dead_connections (data=0x2005e048)
    at /usr/src/debug/curl-7.59.0-1/lib/url.c:1020
#3  create_conn (async=0x22c55e, in_connect=0x2005e050, data=0x2005e048)
    at /usr/src/debug/curl-7.59.0-1/lib/url.c:4389
#4  Curl_connect (data=data@entry=0x2005e048,
    in_connect=in_connect@entry=0x2005e050, asyncp=asyncp@entry=0x22c55e,
    protocol_done=protocol_done@entry=0x22c55f)
    at /usr/src/debug/curl-7.59.0-1/lib/url.c:4667
#5  0x6fb0b19f in multi_runsingle (multi=multi@entry=0x20066d88, now=...,
    data=data@entry=0x2005e048)
    at /usr/src/debug/curl-7.59.0-1/lib/multi.c:1418
#6  0x6fb0c305 in curl_multi_perform (multi=multi@entry=0x20066d88,
    running_handles=running_handles@entry=0x22c624)
    at /usr/src/debug/curl-7.59.0-1/lib/multi.c:2151
#7  0x6fb02605 in easy_transfer (multi=0x20066d88)
    at /usr/src/debug/curl-7.59.0-1/lib/easy.c:697
#8  easy_perform (events=false, data=0x2005e048)
    at /usr/src/debug/curl-7.59.0-1/lib/easy.c:786
#9  curl_easy_perform (data=0x2005e048)
    at /usr/src/debug/curl-7.59.0-1/lib/easy.c:805

**Comment by bagder** [comment]
I don't understand what you're saying. You say you can't reproduce the bug anymore and then you ask something, but I can't understand the question.

curl will, if it tries to send a request over a connection that it discovers is "dead", close that connection, setup a new one and send the request over that one instead.

**Comment by nachopol** [comment]
I reported 2 bugs for libcurl client when sending requests to a server (REST server in my case):

- **Issue 1:** With **https**, if the server has previously closed the socket (has sent a FIN), libcurl always sends the next request through this socket, **it doesn't close the connection** as you said it should. Then the external server sends a RST and just after that, libcurl setup a new connection and resends the request (at least with 7.59 version - cygwin).
- **Issue 2**: Same as Issue 1 but sometimes libcurl not even setup a new connection and the current request is lost. <-- **This is the issue that I'm not reproducing anymore in version 7.59.**

This issue doesn't happen if the connection is http. In http libcurl does close this connections

**Comment by bagder** [comment]
Thanks. Let's ignore the issue that doesn't reproduce anymore. That's fixed and gone. So let's focus on the "issue 1" as explained above:

> Issue 1: With https, if the server has previously closed the socket (has sent a FIN), libcurl always sends the next request through this socket, it doesn't close the connection as you said it should.

You're making definite claims about behavior that isn't that straight forward and simple in the real world. Of course libcurl will close the connection and not try to use it any further - *if it finds out that this is the situation*. You're probably talking about a situation where the server has closed the connection when curl didn't read anything from the connection and hasn't been able to detect that it is in fact "dead" (in spite of trying) and then it might end up trying the connection first, before realizing this fact.

That procedure and code flow works the same for HTTP and HTTPS but might of course possibly not trigger the same way in the real world.

Since curl detects the situation, handles it and sends off a new request on a new connection I can't agree that there is an issue here. It seems curl does exactly what it is told to do. Right?

If there is a step in this procedure in which curl *should have* detected that the connection is closed, but didn't, and still went on with this procedure - then there's is a bug in there. But then I'd need some help in identifying where and when that is!

**Comment by bagder** [comment]
I'm not aware of any bug in this procedure.
