### ISSUE TITLE
How can I get the signal when the connection is established？

### ISSUE THREAD

**Issue by YouRancestor** [curl/curl#3673]
I use curl for websocket client.
I set options and call curl_easy_perform in a subthread, then opensocket_callback is invoked and I create a socket and save it before return.
After that, I want to send message to server using saved socket. But how do I know if the connection is established?  Is there any callback for this case?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

If you're using `CONNECT_ONLY`, which I presume you do, then `curl_easy_perform()` simply returns when it is connected.
