### ISSUE TITLE
Curl crashes after exactly 999 calls

### ISSUE THREAD

**Issue by ikolic** [curl/curl#3685]
### I did this

Called curl_easy_perform(curl) 998 times and everything is fine.
If I try to call it one more time then it crashes with "Access violation reading location 0x00000000000000F8."

### I expected the following

Not to crash.

### curl/libcurl version
7.64.0-DEV
compiled via: nmake /f Makefile.vc mode=dll VC=14.1 ENABLE_WINSSL=yes DEBUG=no MACHINE=x64

[curl -V output]

Workaround: keep a counter and before call 999 reinitialize with curl = curl_easy_init() and reset the counter to 0

### operating system
Windows 10

**Comment by bagder** [comment]
Just to be clear, if you build and run this example (feel free to use another suitable URL), it crashes for you? If so, can you build it debug-enabled and tell us more specifically where it crashes?
~~~c
#include <stdio.h>
#include <curl/curl.h>

int main(void)
{
  CURL *curl;
  CURLcode res;

  curl = curl_easy_init();
  if(curl) {
    int i;
    curl_easy_setopt(curl, CURLOPT_URL, "http://localhost/");
    for(i=0; i < 1003; i++) {
      res = curl_easy_perform(curl);
    }
    curl_easy_cleanup(curl);
  }
  return 0;
}

**Comment by ikolic** [comment]
Hi, I've checked that example and everything works fine, but I think that problem occuress only when URL is always changing (and app is run i release mode - in debug I'm using different dll/lib so I can't speculate).
I've tested many different URL-s and modes, and this combination is crashing at call 999 (in release mode):

```c++
size_t WriteCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
    ((std::string*)userp)->append((char*)contents, size * nmemb);
    return size * nmemb;
}

int main(void)
{
    CURL *curl;
    CURLcode res;

    curl = curl_easy_init();
    if(curl)
    {
        curl_easy_setopt(curl, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36");
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 0L);
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, NULL);
        curl_easy_setopt(curl, CURLOPT_HTTPGET, 1L);
        curl_easy_setopt(curl, CURLOPT_POST, 0);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        for (int i = 0; i < 1003; i++)
        {
            std::string result;
            std::string url = "https://api.pro.coinbase.com/products/btc-usd/trades?after=" + std::to_string(10000 + i) + "&limit=1";
            curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
            curl_easy_setopt(curl, CURLOPT_WRITEDATA, &result);
            res = curl_easy_perform(curl);
            printf("%d: %s\n", i, result.c_str());
            Sleep(333); // THERE IS A RATE LIMIT SO DON'T CHANGE THIS!!!
        }
        curl_easy_cleanup(curl);
    }
}
```

**Comment by ikolic** [comment]
Accidentaly closed the ticket. Reopening....

**Comment by bagder** [comment]
Well, since I can't reproduce the problem and you can't tell where it crashes so I guess we're at the end of the road here?

Changing the URL for every loop doesn't cause any problem for me:
~~~c
#include <stdio.h>
#include <curl/curl.h>

int main(void)
{
  CURL *curl;
  CURLcode res;

  curl = curl_easy_init();
  if(curl) {
    int i;
    char url[128];
    for(i=0; i < 1003; i++) {
      snprintf(url, 128, "http://localhost/?%d", i);
      curl_easy_setopt(curl, CURLOPT_URL, url);
      res = curl_easy_perform(curl);
    }
    curl_easy_cleanup(curl);
  }
  return 0;
}

**Comment by bagder** [comment]
I'm testing this with HTTP and HTTPS URLs on Linux, using OpenSSL, while the bug is said to happen on a Windows build using Schannel.

**Comment by bagder** [comment]
Another question: you say `7.64.0-DEV` which seems odd to me. Why don't you get the latest git master and try first since it might be a problem already fixed?

**Comment by ikolic** [comment]
I've tried that example too and it works (at least it does in debug mode with OpenSSL and without write callback).

So to conclude, this combination is crashing:
Windows 10, Release mode, WinSSL (no OpenSSL) compiled with "nmake /f Makefile.vc mode=dll VC=14.1 ENABLE_WINSSL=yes DEBUG=no MACHINE=x64"
URL alway different,
Write callback (the best is to try with my above sample)
It takes about 10 minutes or so to get to the 999 call because of the rate limit.

I guess you can't test it on Linux so thanks for your help. Workaround is good enough for now.
One other thing: calling curl_easy_cleanup also crashes in this particular case.

**Comment by bagder** [comment]
I don't need to rate limit the tests against my own nginx, it just takes a few seconds. And I think this problem is already fixed in git master.

**Comment by ikolic** [comment]
OK - I'll compile the latest version and let you know (tomorrow).
Rate limit is just for that particular URL - they alow only 3 requests per second.

**Comment by bagder** [comment]
I would suggest you debug this against a local test server instead. It would also be an important extra data point if you can reproduce against other URLs.

**Comment by ikolic** [comment]
So - I've pulled the latest master, compiled it, tested in release mode and now everything works.
I guess issue has been solved within the last two months (that's how old was my previous compile).

Thanks for all the help
