### ISSUE TITLE
How to separate header and content form a http response

### ISSUE THREAD

**Issue by fszhaoholo** [curl/curl#3694]
hi ,
         I had a problem on parsing http response. I just want to get response code and the content which server sent. The code i can get via function "curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &code)" , but the content i only can split the whole string and get the part which after a blank line. Does any function in curl could instead it ?
         The example is as follow, 200 is the code ,  "access_token:..... " is the content which mean.

HTTP/1.1 200 
Date: Thu, 21 Mar 2019 11:14:52 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx/1.12.2

{"access_token":"fe94041dfd4bef13f999dbe37cdd57c5cf7a99ff91018922f6371799e5ea899a","token_type":"bearer","expires_in":86447}**

**Comment by falconindy** [comment]
It seems you're talking about libcurl (as opposed to the `curl` cmdline tool), so I'll suggest that you can use CURLOPT_WRITEDATA/CURLOPT_WRITEFUNCTION to receive the body of the response via a callback.

**Comment by jzakrzewski** [comment]
First of all we use github issues for bugs. The questions should be asked on the mailing list.

But to the point. You did not specify how you get the content. Curl has separate callbacks for headers and body. Take a look at https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

**Comment by fszhaoholo** [comment]
> First of all we use github issues for bugs. The questions should be asked on the mailing list.
> 
> But to the point. You did not specify how you get the content. Curl has separate callbacks for headers and body. Take a look at https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

thx, i will close this issue.

**Comment by fszhaoholo** [comment]
> It seems you're talking about libcurl (as opposed to the `curl` cmdline tool), so I'll suggest that you can use CURLOPT_WRITEDATA/CURLOPT_WRITEFUNCTION to receive the body of the response via a callback.

thx
