### ISSUE TITLE
certinfo: b0rked pubkey/signature algorithm with openssl>=1.0.2

### ISSUE THREAD

**Issue by m6w6** [curl/curl#3706]
### I did this
Retrieved CURLINFO_CERTINFO

### I expected the following
Sane Public Key/Signature Algorithm entries.

### Got instead
```
==========
Public Key Algorithm:    Signature Algorithm: sha256WithRSAEncryption
sha256WithRSAEncryption
==========
```

### curl/libcurl version

master + openssl 1.1.1b

### operating system

Linux

### Testcase

https://gist.github.com/m6w6/7acc0943b024eee3bdc60df70d1f8e3e

**Comment by bagder** [comment]
Ugh. That's one of the dark magic parts of the OpenSSL APIs that I really don't understand much. But yeah, I can confirm that running your test code with openssl 1.0.2 returns a different output than with an openssl 1.1.1 build for me as well. :confused:

**Comment by m6w6** [comment]
Yeah, I tried to fix it, but that openssl API is, well, *ugh*

**Comment by bagder** [comment]
@m6w6 can you confirm if #4030 fixes your case?

**Comment by m6w6** [comment]
> @m6w6 can you confirm if #4030 fixes your case?

Yes, it does!

**Comment by m6w6** [comment]
Sorry, posted the output (now as expected) over at #4030 
```
==========
Signature Algorithm:sha256WithRSAEncryption
==========
==========
Public Key Algorithm:id-ecPublicKey
==========
==========
Signature Algorithm:sha256WithRSAEncryption
==========
==========
Public Key Algorithm:rsaEncryption
==========
```
