### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by nedres** [curl/curl#3708]
### I did this
Attempted to compile. Our build system uses FastBuild to call `cl.exe`.

### I expected the following
A successful build.

### got instead
```
D:\dev\3rdparty\curl\lib\vauth\ntlm.c(624): error C2220: warning treated as error - no 'object' file generated
D:\dev\3rdparty\curl\lib\vauth\ntlm.c(624): warning C4013: 'Curl_ssl_md5sum' undefined; assuming extern returning int
```

### operating system
Windows 10 Pro

### more info
`USE_SSL` is not defined.   
`CURL_DISABLE_CRYPTO_AUTH` is not defined.

**Comment by bagder** [comment]
which version is this?

**Comment by nedres** [comment]
The most recent commit in the log is `9130ead` from Tuesday 3/26-- this is a recent source code pull.

**Comment by bagder** [comment]
Hm, so did 9130ead break the build for you or was it already broken?

**Comment by nedres** [comment]
It is a recent break, but I'm not sure when our last pull was before today.

**Comment by bagder** [comment]
can you try just reverting that and see?  `git revert 9130ead` - since the release is imminent, it would be good to know if we should do a last minute revert...

**Comment by nedres** [comment]
yes, the revert fixes it.

**Comment by bagder** [comment]
Thanks, I will revert that one and we need to do it another way. What puzzles me is that I think we have non-SSL build in appveyor and we didn't spot any build errors there...

**Comment by nedres** [comment]
Thanks very much!
