### ISSUE TITLE
Possible ABI break when updating curl from 7.64.0 to 7.64.1

### ISSUE THREAD

**Issue by Lctrs** [curl/curl#3712]
Hi!
 In [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) we're trying to keep ABI compatibility when updating elements like curl to new releases. In order to achieve this we use [libabigail](https://sourceware.org/libabigail/) tool to automate ABI compat checks. During curl update from 7.64.0 to 7.64.1, our tool produced following complaint:

```
┌─────────────────────────┐
│ ABI Break: libcurl.so.4 │
└─────────────────────────┘

Functions changes summary: 0 Removed, 2 Changed, 0 Added functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

2 functions with some indirect sub-type change:

  [C]'function CURLcode curl_easy_setopt(Curl_easy*, CURLoption, ...)' at setopt.c:2702:1 has some indirect sub-type changes:
    parameter 2 of type 'typedef CURLoption' has sub-type changes:
      underlying type 'enum __anonymous_enum__' at curl.h:941:1 changed:
        type size hasn't changed
        2 enumerator insertions:
          '__anonymous_enum__::CURLOPT_ALTSVC_CTRL' value '286'
          '__anonymous_enum__::CURLOPT_ALTSVC' value '10287'

        1 enumerator change:
          '__anonymous_enum__::CURLOPT_LASTENTRY' from value '286' to '10288' at curl.h:959:1


  [C]'function CURLsslset curl_global_sslset(curl_sslbackend, const char*, const curl_ssl_backend***)' at vtls.c:1307:1 has some indirect sub-type changes:
    parameter 3 of type 'const curl_ssl_backend***' has sub-type changes:
      in pointed to type 'const curl_ssl_backend**':
        in pointed to type 'const curl_ssl_backend*':
          in pointed to type 'const curl_ssl_backend':
            in unqualified underlying type 'typedef curl_ssl_backend' at curl.h:2471:1:
              underlying type 'struct {curl_sslbackend id; const char* name;}' at curl.h:2444:1 changed:
                type size hasn't changed
                1 data member change:
                 type of 'curl_sslbackend id' changed:
                   underlying type 'enum __anonymous_enum__' at curl.h:137:1 changed:
                     type size hasn't changed
                     1 enumerator deletion:
                       '__anonymous_enum__::CURLSSLBACKEND_DARWINSSL' value '9'

                     1 enumerator insertion:
                       '__anonymous_enum__::CURLSSLBACKEND_SECURETRANSPORT' value '9'
```

As part of our [discussion](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1133) about what to do with that we would like to ask about your opinion on the matter. Especially I wanted to ask if reported change was intentional and if it's safe for backward compatibility thus if above report is a false positive. I would be grateful if you can find time to respond. Thank you.

**Comment by bagder** [comment]
By adding more options to `*setopt()` we don't break the ABI. I find it curious that you respond to this change now when we basically do this sort of addition of options for almost every release of libcurl since many years back. These two are option number 266 and 267! (In this particular case, both these options are even documented as experimental and users are discouraged from using them in production before that label is changed so we will not even guarantee that their functionality will remain verbatim going forward.)

The second complaint also looks like a false positive to me since we provide the older name with a `#define` so the exact same numbers will be used both before and after this change.

**Comment by Lctrs** [comment]
Okay. We have proceeded with the update.

I don't know why our tool reported an ABI break in this update and not in the others. I'm a fairly new contributor to freedesktop-sdk and don't know libabigail at all.

Thanks for your quick - and precise - answer. I'm closing this issue.
