### ISSUE TITLE
tool_help.c compilation failure: error: implicit declaration of function ‘strcasecmp’; did you mean ‘strncmp’?

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#3715]
### I did this

Compile curl using gcc 8.2.1. (using x86 compiler, but it doesn't matter)

### I expected the following

Successful build.

### curl/libcurl version

7.64.1

### operating system

CentOS 6.

The build failed when compiling "tool_help.c":

```
tool_help.c: In function ‘featcomp’:
tool_help.c:553:10: error: implicit declaration of function ‘strcasecmp’; did you mean ‘strncmp’? [-Werror=implicit-function-declaration]
   return strcasecmp(* (char * const *) p1, * (char * const *) p2);
          ^~~~~~~~~~
          strncmp
cc1: some warnings being treated as errors
```

Bug was introduced in this PR: https://github.com/curl/curl/pull/3611

**Solution**: add `#include <strings.h>` above the "memdebug.h" include.

**Comment by bagder** [comment]
Curious that the CI builds nor my own builds get this... ?

**Comment by wyattoday** [comment]
Maybe your CI servers don't treat that warning as an error (`implicit-function-declaration`).

The toolset we use is based on the Redhat compilation of the gcc toolset (basically what amounts to devtoolset-8). My guess is they have `-Werror=implicit-function-declaration` set by default (seeing as [they recommend it as a default](https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/))
