### ISSUE TITLE
Travis CI compiler errors not detected

### ISSUE THREAD

**Issue by jay** [curl/curl#3730]
### I did this

https://travis-ci.org/curl/curl/jobs/515938887#L6033

~~~
connect.c: In function ‘Curl_is_connected’:
connect.c:846:14: error: unused variable ‘buffer’ [-Werror=unused-variable]
         char buffer[STRERROR_LEN];
              ^~~~~~
connect.c: In function ‘tcpnodelay’:
connect.c:902:8: error: unused variable ‘buffer’ [-Werror=unused-variable]
   char buffer[STRERROR_LEN];
        ^~~~~~

...

cc1: all warnings being treated as errors
make[2]: *** [libcurl_la-connect.lo] Error 1
make[2]: Leaving directory `/home/travis/build/curl/curl/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/travis/build/curl/curl/lib'
make: *** [all-recursive] Error 1

...

Done. Your build exited with 0.
~~~

#10260.5 passed

### I expected the following

#10260.5 errored

**Comment by bagder** [comment]
Weird! I can't see that we've changed anything to make this stop working... ?

**Comment by webmaster128** [comment]
There is an endless debate about Travis status code handling and fast failing of scripts, e.g. in [this thread about set -e in .travis.yml](https://github.com/travis-ci/docs-travis-ci-com/issues/1672). At lot of those problems are a result of Travis composing a single bash script out of everything in .travis.yml plus their own setup. In my experiance the only thing that works reliably is [calling a main travis bash script](https://github.com/iov-one/iov-core/blob/v0.13.0/.travis.yml#L58) as the only step in `script`. In that main script, `set -o errexit -o nounset -o pipefail` can be used independent of the surrounding shell context to harden the execution.

Nice to have: custom output folding can be done using [custom fold_start/fold_end functions](https://github.com/iov-one/iov-core/blob/v0.13.0/scripts/travis/_includes.sh#L3-L12) in the custom shell script (like [this](https://github.com/iov-one/iov-core/blob/v0.13.0/scripts/travis/main.sh#L9-L11)).

**Comment by jay** [comment]
Alright let's try that. Please review PR #3755 and let me know what I did wrong because I'm sure there will be something.

**Comment by webmaster128** [comment]
For the fast failing issue also see https://github.com/travis-ci/travis-ci/issues/1066

**Comment by bagder** [comment]
I propose we just drop this issue as this is not a major concern and nobody seems to work on it?

**Comment by jay** [comment]
Resurrected
