### ISSUE TITLE
cmake: DarwinSSL setting not passed to curl configuration

### ISSUE THREAD

**Issue by webmaster128** [curl/curl#3733]
In https://github.com/curl/curl/pull/3619, `USE_DARWINSSL`was renamed to `USE_SECTRANSP`. However, in https://github.com/curl/curl/blob/curl-7_64_1/CMakeLists.txt#L344 the old configuration is used.

This currently leads to an active DarwinSSL feature but no SSL backend:

```
$ bash /build_dir/curl/curl-config --features
DarwinSSL
IPv6
unix-sockets
libz
AsynchDNS
```

```
$ bash /build_dir/curl/curl-config --ssl-backends

```

(btw: where does this empty output line come from?).

I'm working on a PR to get this fixed.

**Comment by webmaster128** [comment]
In configure.ac, `SUPPORT_FEATURES` does not contain the individual SSL backends, but [in CMakeLists.txt they are listed individually](https://github.com/curl/curl/blob/curl-7_64_1/CMakeLists.txt#L1180-L1213), which leads to different results in `curl-config` and `libcurl.pc`.

I think this should be standardized before adding a new feature name to that list ("Secure Transport" or "SecureTransport"). What do you think?

**Comment by bagder** [comment]
It's even called `secure-transport` at times in the configure script. I think if the name can be done with a space then the full official name is the better option, but I opted for the space-less version in the version output just to make it simpler for shell scripts that typically separate strings on spaces.

The specific SSL backend is not a "feature" so it doesn't need to be listed there. It should contain `SSL` if built with SSL support present, that's the feature.

**Comment by webmaster128** [comment]
Done by https://github.com/curl/curl/pull/3769
