### ISSUE TITLE
simple curl program fails on win10-64/codeblocks/mingw

### ISSUE THREAD

**Issue by meir100** [curl/curl#3748]
### I did this
downloaded mingw from:
https://sourceforge.net/projects/mingw-w64/files/
from: files-->tab-->download latest version (.exe)

### curl/libcurl version
downloaded curl from: https://curl.haxx.se/windows/  curl for 64 bit (7.64.1)

[curl -V output]

curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system

simple curl program fails on win10-64 / codeblocks17.12 / mingw-w64  C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0
/ curl-7.64.1-win64-mingw

the program:
~~~c
#include <stdio.h>
#include <stdlib.h>
#include <curl/curl.h>

int main()
{
    curl_global_init(CURL_GLOBAL_ALL);
    CURL* myHandle;
    CURLcode result; // We’ll store the result of CURL’s webpage retrieval, for simple error checking.
    myHandle = curl_easy_init();
    // Notice the lack of major error checking, for brevity
    //curl_easy_setopt(myHandle, CURLOPT_URL, "http://www.example.com");
	curl_easy_setopt(myHandle, CURLOPT_URL, "http://www.kav.org.il");
    result = curl_easy_perform(myHandle);
    curl_easy_cleanup(myHandle);
    printf("LibCurl rules!\n");
    return 0;
}
~~~
the output:
~~~
||=== Build: Debug in crawler (compiler: GNU GCC Compiler) ===|
obj\Debug\curlhtml_1.o||In function `main':|
C:\SOFTWARE  RAPIDJSON  CURL  SPIDER\curlhtml_1.cpp|7|undefined reference to `_imp__curl_global_init'|
C:\SOFTWARE  RAPIDJSON  CURL  SPIDER\curlhtml_1.cpp|10|undefined reference to `_imp__curl_easy_init'|
C:\SOFTWARE  RAPIDJSON  CURL  SPIDER\curlhtml_1.cpp|13|undefined reference to `_imp__curl_easy_setopt'|
C:\SOFTWARE  RAPIDJSON  CURL  SPIDER\curlhtml_1.cpp|14|undefined reference to `_imp__curl_easy_perform'|
C:\SOFTWARE  RAPIDJSON  CURL  SPIDER\curlhtml_1.cpp|15|undefined reference to `_imp__curl_easy_cleanup'|
||error: ld returned 1 exit status|
||=== Build failed: 6 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by bagder** [comment]
This is mentioned in the [FAQ](https://curl.haxx.se/docs/faq.html#Link_errors_when_building_libcur) and happens because you build with a static lib on windows without specifying so at compile-time:

> When building an application that uses the static libcurl library, you must add -DCURL_STATICLIB to your CFLAGS. Otherwise the linker will look for dynamic import symbols. If you're using Visual Studio, you need to instead add CURL_STATICLIB in the "Preprocessor Definitions" section.
