### ISSUE TITLE
curl.vcxproj is missing

### ISSUE THREAD

**Issue by yazi1297** [curl/curl#3754]
There is a different between the source code I download from github and download from curl.haxx.se
I am a Windows programmer. And now I'm studying how to use curl. I'm trying to build it by my self.
I download curl source code from github at first. when I opened the curl_all.sln which located in projects, vs told me it can't find curl.vcxproj file. I think it's impossible and I tried to find it, but it's really missed.
Then, I download a source code zip from curl.haxx.se, after I unziped it, I found curl.vcxproj in my directory.
I think maybe you just forget to push this file into github.

**Comment by jay** [comment]
You'll have to run generate.bat if you're working from the repo:

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/projects/README#L140-L142
