### ISSUE TITLE
What is CMAKE_USE_OPENSSL for?

### ISSUE THREAD

**Issue by JonasVautherin** [curl/curl#3756]
Running the following:

```sh
cmake -DCMAKE_USE_OPENSSL=NO -DCURL_CA_PATH_SET=OFF ..
make
```

I get a libcurl.so that gives me:

```sh
$ ldd libcurl.so
	...
	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f6fff76f000)
	...
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f6fff163000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f6ffee8d000)
	...
```

Which suggests that `CMAKE_USE_OPENSSL` is not there for compiling without openssl, right?

**Comment by jay** [comment]
cmake output should say if it's using OpenSSL or not. Check libcurl direct dependencies for example `readelf -d ./lib/.libs/libcurl.so.4.4.0 | grep -i needed`

**Comment by JonasVautherin** [comment]
Hmm that's interesting, `readelf` doesn't show OpenSSL as "needed". Why does it appear in `ldd` then? :smile: :thinking: 

If I build with `-DHTTP_ONLY=ON -DCMAKE_USE_LIBSSH2=OFF`, then the OpenSSL libs disappear from the output of `ldd` as well. Why is that?

**Comment by jay** [comment]
> Hmm that's interesting, `readelf` doesn't show OpenSSL as "needed". Why does it appear in `ldd` then?

ldd shows all dependencies and not just direct dependencies. It's probably a dependency of libssh2.

**Comment by JonasVautherin** [comment]
It does make sense! Thanks a lot @jay!
