### ISSUE TITLE
Mac OS app has been rejected because of LDAP

### ISSUE THREAD

**Issue by nianxuejie** [curl/curl#3786]
Mac OS app has been rejected with following reason:

Your app app links against the following non-public framework(s):
/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP

Can we remove ldap at compile time?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

Yes, you can disable ldap at build time. See `./configure --help` output.
