### ISSUE TITLE
SIGPIPE in ossl_close

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#3787]
Crash at ossl_close, here is the call stack.

![image](https://user-images.githubusercontent.com/2238185/56279463-c0135280-613a-11e9-8fbb-c57aa57b4189.png)

### curl/libcurl version

curl-7.64.0

### operating system
Linux

**Comment by bagder** [comment]
That looks like the known `SIGPIPE` behavior of OpenSSL (it writes to the socket during shutdown when the connection already has died). Did you ask libcurl to not ignore the signals? libcurl will ignore these by default...

**Comment by ustcqidi** [comment]
thank you @bagder   

I have checked my code. 
We have set CURLOPT_NOSIGNAL option: **curl_easy_setopt(m_hCurl, CURLOPT_NOSIGNAL, 1L);**

So, should we keep the option as default ?

**Comment by bagder** [comment]
If you want libcurl to ignore them, then yes. See the [CURLOPT_NOSIGNAL](https://curl.haxx.se/libcurl/c/CURLOPT_NOSIGNAL.html) man page for details.

**Comment by jay** [comment]
I notice GnuTLS is already (somewhat) protected from this 

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/curl_setup_once.h#L121-L125

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/curl_setup_once.h#L197-L200

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/vtls/gtls.c#L157-L166

not ssl proxy though?

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/vtls/gtls.c#L179-L182

Anyway we could probably do the same for OpenSSL with a BIO I think.

**Comment by bagder** [comment]
> we could probably do the same for OpenSSL with a BIO I think

Yes, we certainly could and it would be a good thing...

**Comment by bagder** [comment]
For now though, this issue is fixed by not switching off `CURLOPT_NOSIGNAL` or by ignoring the signal in the application itself.
