### ISSUE TITLE
curl_easy_perform bug

### ISSUE THREAD

**Issue by mingpuwu** [curl/curl#3788]
### I did this
I use curl_easy_perform download  file in my project, sometimes ,the function may return when the file not download yet,and the return value is 0.
### I expected the following
I want to know when this will happen and how I can avoid it.  Thank you very much！Looking forward to your reply！
### curl/libcurl version
7.61.0
[curl -V output]

### operating system
linux

**Comment by bagder** [comment]
Please give us more details. What *exactly* do you do? Protocol, options, and possibly show us sent/received headers or protocol data. How do you reproduce this? How can *we* reproduce this?

**Comment by dfandrich** [comment]
Could it be that the server is returning a 302 redirect code in this case and
your code doesn't request that redirects be followed?

**Comment by mingpuwu** [comment]
Ok，i get it. I will sort it out and send it to you tomorrow.

发自我的 iPhone

**Comment by mingpuwu** [comment]
```
                curl_easy_setopt(curl,CURLOPT_URL,in_param.download_url.c_str());
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
                curl_easy_setopt(curl, CURLOPT_TIMEOUT,DOWNLOAD_TIME_OUT);
                //curl_easy_setopt(curl,CURLOPT_CONNECTTIMEOUT,TIME_OUT);
                curl_easy_setopt(curl, CURLOPT_RESUME_FROM, (long)local_size);
                curl_easy_setopt(curl,CURLOPT_WRITEDATA,fp);
                curl_easy_setopt(curl,CURLOPT_WRITEFUNCTION,write_function);
                curl_easy_setopt(curl,CURLOPT_NOPROGRESS,1L);
                return_num  = curl_easy_perform(curl);
```
this is my code ,protocol is https,This URL is the address of the download package.but i can't provide the information of  protolcol ,and i can't  reproduce this ,when i retry many times. i just run the code normally.

**Comment by mingpuwu** [comment]
Sorry, I'm not familiar with 302. Previously, it was okay.302 means that the website will chage other website when connect the web.

**Comment by jay** [comment]
That isn't enough information. Turn on verbose mode `curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);` so you can see what is happening.

**Comment by dfandrich** [comment]
If it's due to a redirect, setting CURLOPT_FOLLOWLOCATION will solve it. But
enabling logs will show you.

**Comment by mingpuwu** [comment]
> That isn't enough information. Turn on verbose mode `curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);` so you can see what is happening.

ok，i will turn on it,thanks

**Comment by mingpuwu** [comment]
> If it's due to a redirect, setting CURLOPT_FOLLOWLOCATION will solve it. But enabling logs will show you.

the url  is normal In previous times.About redirect,Is it likely to change abruptly? it's prove that the website have not redirect ? thanks!

**Comment by dfandrich** [comment]
I can't say anything about the server since I know nothing about it. I'm just
speculating based on the minimal information you've given about the problem.

**Comment by bagder** [comment]
@mingpuwu show us the HTTP responses headers you got and they might tell us what's going on!

**Comment by bagder** [comment]
No response, closing.
