### ISSUE TITLE
Cannot use PKCS12 certificate

### ISSUE THREAD

**Issue by tamlyn** [curl/curl#3791]
### I did this

First I generated a key pair and converted it to PKCS12:

    openssl genrsa 2048 > private.pem
    openssl req -x509 -days 1000 -new -key private.pem -out public.pem
    openssl pkcs12 -export -in public.pem -inkey private.pem -out cert.p12

I then tried to use it to connect to a server:

    # Using the PEM files works as expected
    curl --cert public.pem --key private.pem  https://github.com

    # Using the PKCS12 file results in an error
    curl --cert cert.p12 https://github.com

### I expected the following

I expected to be able to specify the certs in either format but using PKCS12 results in an error:

`curl: (58) could not load PEM client certificate, LibreSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?)`

I tried on MacOS High Sierra, latest Ubuntu and CentOS with the same results. Strangely though using PKCS12 **does** work on a colleague's workstation running the older MacOS Sierra. His version of curl is the same but his OpenSSL is older.

According to the man page:

       -E, --cert <certificate[:password]>
              (TLS)  Tells  curl to use the specified client certificate file when getting 
              a file with HTTPS, FTPS or another SSL-based protocol. The certificate
              must be in PKCS#12 format if using Secure Transport, or PEM format if 
              using any other engine.

I initially read that to mean that PEM is not supported under Secure Transport but PKCS12 is supported everywhere. But now I'm wondering if maybe it means that PKCS12 is *only* supported under Secure Transport?

### curl/libcurl version

curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0

### operating system

MacOS High Sierra 10.13.6

**Comment by bagder** [comment]
The latter. It is only supported when built with Secure Transport.

**Comment by tamlyn** [comment]
I see, thanks. Has this always been the case? The [original patch](https://curl.haxx.se/mail/lib-2004-12/0202.html) makes no mention of Secure Transport. Closing as I guess this is not a bug.
