### ISSUE TITLE
curl: (77) Problem with the SSL CA cert (path? access rights?) with centOS on Plesk

### ISSUE THREAD

**Issue by adiamantakidis** [curl/curl#3793]
Task "curl &quot;https://mysite.com/folder1/folder2/cron.php&quot;" completed with error in 0 seconds, output:

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
curl: (77) Problem with the SSL CA cert (path? access rights?)       

### operating system centOS

The "http" address curl does not give error, but still not working at the other end.

How can that be solved, I applied all suggestion found on the net, nothing worked so far.
Many thanks.

**Comment by bagder** [comment]
Your certificate bundle doesn't contain the correct CA cert for curl to verify this server. This is not a curl bug, this is working as intended!

**Comment by adiamantakidis** [comment]
I got in contact with the SSL provider and I also changed and downloaded a tested new CA cert but nothing, the issue persists. I also tried to switch to the Let's Encrypt Certificate but same error is shown. Is this a Plesk issue then? Any suggestions on how to fix it?
Many thanks!

**Comment by adiamantakidis** [comment]
> Your certificate bundle doesn't contain the correct CA cert for curl to verify this server. This is not a curl bug, this is working as intended!

I got in contact with the SSL provider and I also changed and downloaded a tested new CA cert but nothing, the issue persists. I also tried to switch to the Let's Encrypt Certificate but same error is shown. Is this a Plesk issue then? Any suggestions on how to fix it?
Many thanks!

**Comment by bagder** [comment]
> I got in contact with the SSL provider and I also changed and downloaded a tested new CA cert but nothing, the issue persists. I also tried to switch to the Let's Encrypt Certificate but same error is shown.

Maybe you just did something wrong? Let's Encrypt certificates "just work" if you have a reasonably updated CA cert store.

> Is this a Plesk issue then?

I don't even know what Plesk is or how that suddenly got involved in this issue so I can't tell!

> Any suggestions on how to fix it?

You need to make sure that your curl uses a CA store that contains the cert for the CA that was used to sign the certificate the server uses.

**Comment by adiamantakidis** [comment]
Plesk's staff solved the problem. I report here the solution. 

Summarizing:

> When
> 
>  attempting to run a curl command using https, you were receiving the following:
> curl: (77) Problem with the SSL CA cert (path? access rights?)
> 
> CURL Error: Peer's Certificate issuer is not recognized. - Code 60
> 
> This is caused by the wrong certificate being used on curl. To fix the problem the following was executed:
> Download the cacert.pem file from the Curl's site: https://curl.haxx.se/docs/caextract.html;
> 
> Log into Plesk;
> 
> Place certificate inside the domain's root directory using Domains > example.com > File Manager;
> 
> Specify the path to it in the Domains > example.com > PHP Settings > Additional directives  as follows:
> 

`[curl]`
`curl.cainfo = /var/www/vhosts/theurbanmoda.com/httpdocs/cacert.pem`
> 
> After such steps, I was able to run the task successfully, remember to always use the -k option when using https:

**Comment by jay** [comment]
> curl.cainfo = /var/www/vhosts/example.com/httpdocs/cacert.pem

The directions Plesk gave you should work, however most servers contain certificates that are kept updated by the OS and those should be used instead if possible.

> After such steps, I was able to run the task successfully, remember to always use the -k option when using https:

The -k option disables host and peer verification. It shouldn't be used in production unless you don't care about the security of the transfer, which will rarely be the case.
