### ISSUE TITLE
curl failing to init on windows

### ISSUE THREAD

**Issue by johnayoub** [curl/curl#3798]
### I did this

run curl no arguments from the command line

### I expected the following

curl to run however I get the following message 

curl: error initializing curl library
curl: try 'curl --help' or 'curl --manual' for more information

### curl/libcurl version

7.64.1

### operating system

Windows Server 2016

**Comment by jay** [comment]
That's highly unusual. Unfortunately we don't output which part of initialization failed except in debug builds. Perhaps we should change that. Did you build curl or download it already built? Can you try this one https://curl.haxx.se/windows/

Ref: https://github.com/curl/curl/blob/curl-7_64_1/lib/easy.c#L141

**Comment by johnayoub** [comment]
I downloaded the already built version!! Tried several older versions but no luck. It was working at some point and have no idea what happened. I tried to follow along in the source code where that error message is thrown but I'm no C expert :(

Ref: https://github.com/curl/curl/blob/d1b5cf830bfe169745721b21245d2217d2c2453e/src/tool_main.c#L183

**Comment by jay** [comment]
> Tried several older versions but no luck.

So all older versions you've tried also have the same problem in Server 2016? Are you running any anti-virus software that may be interfering with the execution?

**Comment by johnayoub** [comment]
Yes! Only Windows defender is running and it doesn't seem to be interfering. I discovered the issue originally through git when I couldn't pull/push any longer. I then downloaded the curl program  to test it directly. No windows update have been applied either or anything of that sort. I only deleted some software (a citrix one) but I can't understand how that could even have any effect. I'm completely stumped and not having git working is a big deal :(

It's just baffling to be honest.....

**Comment by jay** [comment]
curl has an undocumented option --dump-module-paths that you can use to see which DLLs are loaded in the process. Can you show us that output? The official binary builds should not show anything other than Windows DLLs since all 3rd party dependencies are static.

**Comment by johnayoub** [comment]
here's the output

C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\tsappcmp.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\System32\MSASN1.dll
C:\WINDOWS\System32\Normaliz.dll
C:\WINDOWS\System32\WLDAP32.dll
C:\WINDOWS\System32\WS2_32.dll

**Comment by jay** [comment]
I don't see anything unusual there. I don't have Server 2016 but given that it was working before and it's not now it's probably something specific to your system.

What happens if you set the curl ssl backend to schannel? From a command prompt `set CURL_SSL_BACKEND=schannel` or from a powershell prompt `$env:CURL_SSL_BACKEND="schannel"` then run `curl -V`.

If that doesn't work I'm out of ideas. You can build curl from [source](https://curl.haxx.se/download.html) using Visual Studio and walk through the initialization to find out exactly where it's failing. There are some generated project files in projects/

**Comment by gvanem** [comment]
> curl: error initializing curl library
> curl: try 'curl --help' or 'curl --manual' for more information

I'd recommend building a version with `-DDEBUGBUILD=1` and retry since several things could fail in `global_init()`. 

IMHO, doing a `curl -v` should do always print these vital messages.

**Comment by jay** [comment]
Basically nothing happens before initialization. This is such a rare thing we don't have thorough debugging output for it but yes that should give a general idea.

**Comment by johnayoub** [comment]
> I don't see anything unusual there. I don't have Server 2016 but given that it was working before and it's not now it's probably something specific to your system.
> 
> What happens if you set the curl ssl backend to schannel? From a command prompt `set CURL_SSL_BACKEND=schannel` or from a powershell prompt `$env:CURL_SSL_BACKEND="schannel"` then run `curl -V`.
> 
> If that doesn't work I'm out of ideas. You can build curl from [source](https://curl.haxx.se/download.html) using Visual Studio and walk through the initialization to find out exactly where it's failing. There are some generated project files in projects/

That didn't help still the same issue. I'll try to build locally. Will keep you posted!

Really appreciate your help here :)

**Comment by johnayoub** [comment]
So some progress here. I was able to get a build working with the following configuration `DLL Debug - DLL Windows SSPI` 

I'm trying to get a build with openssl and everything that is packaged with the official version could you tell me how to do that? I know openssl needs to be downloaded separately just not sure where from.

```
D:\Downloads\curl-7.64.1\build\Win64\VC15\DLL Debug - DLL Windows SSPI>curld.exe -V
curl 7.64.1 (x86_64-pc-win32) libcurl/7.64.1 Schannel
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI
```

**Comment by jay** [comment]
> I'm trying to get a build with openssl and everything that is packaged with the official version could you tell me how to do that?

Use build-openssl.bat in the projects directory.

build-openssl -help

You'll have to download the OpenSSL 1.0.2 source, which is not what is packaged with the official build. The official build is reproducible but not with Visual Studio. You can find out more at https://github.com/curl/curl-for-win

**Comment by johnayoub** [comment]
@jay thanks I'll try that.

So IT installed a citrix app on my machine and the modules list has changed! Please see blow

C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\tsappcmp.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\System32\MSASN1.dll
C:\WINDOWS\System32\Normaliz.dll
C:\WINDOWS\System32\WLDAP32.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files (x86)\Citrix\system32\MfApHook64.dll
C:\Program Files (x86)\Citrix\system32\CtxMFPlugin64.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\System32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files (x86)\Citrix\system32\CtxGraphicsHelper64.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files (x86)\Citrix\system32\mmhook64.dll
C:\Program Files (x86)\Citrix\system32\Sfrhook64.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\Program Files (x86)\Citrix\system32\ShellHook64.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\windows.storage.dll
C:\WINDOWS\System32\shlwapi.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\profapi.dll
C:\Program Files (x86)\Citrix\system32\scardhook64.dll
C:\Program Files (x86)\Citrix\system32\cxinjime64.dll
C:\WINDOWS\system32\secur32.dll
C:\WINDOWS\system32\SSPICLI.DLL
C:\WINDOWS\system32\mswsock.dll

**Comment by jay** [comment]
If you have IT you should ask them why it is not working. The updated modules list shows Citrix has injected into the process. That is likely expected. Anyway, they may know what is happening and why libcurl doesn't work, and that could save you time from having to figure it out for yourself.

**Comment by gvanem** [comment]
I've never used Citrix, but this paragraph  [here](
https://helgeklein.com/blog/2015/10/citrix-xenappxendesktop-api-hooking-explained/):

> Due to that nature hooks may cause problems. 
> If you experience weird application malfunctions it might be a good idea to test 
> with some or all hooks disabled.

could be important. 

Or adding a:
`HKLM\SOFTWARE\Citrix\CtxHook\ExcludedImageNames = curl.exe`

**Comment by johnayoub** [comment]
@gvanem @jay I tried the registry trick and that didn't seem to help. I have asked IT to restore the machine to an earlier state and everything is working again. I still have no idea what went wrong but I at least have a working machine now :)

Thank you both for your help and efforts.
