### ISSUE TITLE
https slow speed

### ISSUE THREAD

**Issue by pastia** [curl/curl#3810]
my english is so broken. I hope you get the idea.
i wanna request https link 300~500 times per seconds.
i tried curl_multi_* and curl_share_* functions,  
the multi interface always done in a flash. but i want a sustainable function, It's best to send data every millisecond.
so , how can i do it? Or is there any documentation.
thank you!

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
