### ISSUE TITLE
Clarify use of CURLOPT_RANGE on upload

### ISSUE THREAD

**Issue by jay** [curl/curl#3814]
### I did this

Christopher Head (@Hawk777) [reported](https://curl.haxx.se/mail/lib-2019-04/0075.html) on the mailing list that [CURLOPT_RANGE](https://curl.haxx.se/libcurl/c/CURLOPT_RANGE.html) does not work properly for ranged PUTs. I replied saying PUT is only for complete replacement of a resource, not partial. He replied saying Amazon allows ranged PUTs ([doc](https://docs.aws.amazon.com/amazonglacier/latest/dev/api-upload-part.html)).

### I expected the following

The documentation does not specify the behavior of CURLOPT_RANGE on upload, so we should clarify that and in doing so decide whether or not what was reported is a bug (I think it's not since it's against the RFC).

**Comment by bagder** [comment]
curl has an approach to resumed uploads with PUT, even though it isn't encouraged nor specified in the RFC. It has however existed for a long time so we don't want to break it either.

For example, test 1001 and 1041 verify the existing functionality.

**Comment by jay** [comment]
What do you think about changing the doc to link to caution against using CURLOPT_RANGE for PUT uploads?

**Comment by bagder** [comment]
Absolutely, propose a change if you can come up with wording you think will help users!

**Comment by Simonair99** [comment]
# @https://curl.haxx.se/libcurl/c/CURLOPT_RANGE.html
