### ISSUE TITLE
URL parsing regression

### ISSUE THREAD

**Issue by arewx** [curl/curl#3817]
### I did this
[xiaomen@localhost bin]$ ls
c_rehash  curl  curl-config  openssl
[xiaomen@localhost bin]$ ./curl -V
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.0.2r zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP TrackMemory UnixSockets
[xiaomen@localhost bin]$ ./curl --url sftp://root:SYS2009health@[fe80::20c:29ff:fe9c:409b%eth0]  -T ../file_dx -k
curl: (3) URL using bad/illegal format or missing URL
[xiaomen@localhost bin]$ ping6 fe80::20c:29ff:fe9c:409b%eth0
PING fe80::20c:29ff:fe9c:409b%eth0(fe80::20c:29ff:fe9c:409b) 56 data bytes
64 bytes from fe80::20c:29ff:fe9c:409b: icmp_seq=1 ttl=64 time=5.42 ms
64 bytes from fe80::20c:29ff:fe9c:409b: icmp_seq=2 ttl=64 time=0.231 ms
64 bytes from fe80::20c:29ff:fe9c:409b: icmp_seq=3 ttl=64 time=0.263 ms
64 bytes from fe80::20c:29ff:fe9c:409b: icmp_seq=4 ttl=64 time=0.316 ms
64 bytes from fe80::20c:29ff:fe9c:409b: icmp_seq=5 ttl=64 time=0.318 ms
^C
--- fe80::20c:29ff:fe9c:409b%eth0 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4857ms
rtt min/avg/max/mdev = 0.231/1.309/5.421/2.056 ms
[xiaomen@localhost bin]$ 

But 
[xiaomen@localhost bin]$ ls
c_rehash  curl  curl-config  openssl
[xiaomen@localhost bin]$ ./curl -V
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.0.2r zlib/1.2.11 libssh2/1.8.2
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
[xiaomen@localhost bin]$ ./curl --url sftp://root:SYS2009health@[fe80::20c:29ff:fe9c:409b%eth0]  -T ../file_dx -k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3897    0     0  100  3897      0  22789 --:--:-- --:--:-- --:--:-- 23618
100  3897    0     0  100  3897      0  22789 --:--:-- --:--:-- --:--:-- 22789
[xiaomen@localhost bin]$
Why curl-7.60.0 can upload files successfully and curl-7.64.1 fails
### curl/libcurl version
expect file could uploaded success
[curl -V output]
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.0.2r zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https rtsp scp sftp smb smbs telnet tftp
Features: AsynchDNS Debug HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP TrackMemory UnixSockets
### operating system
ALL

**Comment by bagder** [comment]
1. comparing with ping is a bad idea since ping doesn't deal with URLs
2. a scope id in a URL is written as '%25[id]'
3. this is a regression in the sense that we did handle this before
