### ISSUE TITLE
Website Broken Link Report

### ISSUE THREAD

**Issue by Joombalaya** [curl/curl#3818]
The link https://support.microsoft.com/kb/140584/en-us (in INSTALL.md) for "How to link with the correct C Run-Time CRT library" is currently down. I am not sure if this link needs to be removed or updated to point to more current Windows information.

**Comment by bagder** [comment]
Since Microsoft removed it, we should probably not try to link to it but I found it archived here:

https://jeffpar.github.io/kbarchive/kb/140/Q140584/
https://web.archive.org/web/20140320202443/http://support.microsoft.com/kb/140584

Is the info still relevant? Should we maintain our own docs for it?

**Comment by Joombalaya** [comment]
I am a novice when it comes to cURL. I simply noticed as a matter of course when going through the documents for the first time, so I do not know if the information is still relevant. I imagine users who compile on the Windows environment need to be aware of the caveats associated with DLL vs Static regardless.

**Comment by jay** [comment]
> Is the info still relevant? Should we maintain our own docs for it?

It has some outdated info, it says the default switch is single threaded but in any recent compiler it's the multithreaded crt dll (release /MD, debug /MDd). The crt mixing part is also covered in [How To Use the C Run-Time](https://support.microsoft.com/kb/94248/en-us) and the compiler switches are [documented elsewhere](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library) so we could link to that instead

~~~diff
diff --git a/docs/INSTALL.md b/docs/INSTALL.md
index f2f9322..e1a0a3c 100644
--- a/docs/INSTALL.md
+++ b/docs/INSTALL.md
@@ -122,7 +122,7 @@ libressl.
  understanding if you are not going to follow the advice given above.
 
  - [How To Use the C Run-Time](https://support.microsoft.com/kb/94248/en-us)
- - [How to link with the correct C Run-Time CRT library](https://support.microsoft.com/kb/140584/en-us)
+ - [Run-Time Library Compiler Options](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library)
  - [Potential Errors Passing CRT Objects Across DLL Boundaries](https://msdn.microsoft.com/en-us/library/ms235460)
 
 If your app is misbehaving in some strange way, or it is suffering from
~~~

**Comment by bagder** [comment]
Sounds good to me!
