### ISSUE TITLE
Possible null dereference in cookie.c

### ISSUE THREAD

**Issue by JMoerman** [curl/curl#3820]
I had to look for bugs in curl using Coverity for an assignment and encountered this in cookie.c:
https://github.com/curl/curl/blob/b898b4c06cf8f821fbcd27808f42115b16a151b0/lib/cookie.c#L875-L878
According to the first if statement `co->name` can be null and `co->name` is passed to `strncasecompare` (`Curl_strncasecompare`) which does not check for null and dereferences this parameter.

```
int Curl_strncasecompare(const char *first, const char *second, size_t max)
{
  while(*first && *second && max) {
...
```

Encountered when analyzing 9e8f28a8f1fe90c5e88c18f56f82f6c28f804839, still present in b898b4c06cf8f821fbcd27808f42115b16a151b0 (which currently is the latest commit in master).

I don't think that it is a huge issue, but it doesn't seem to be a false positive and could potentially cause a crash.

**Comment by danielgustafsson** [comment]
Thanks for the report, it is indeed a low-risk NULL pointer deref case. I've opened PR #3821 to fix this.
