### ISSUE TITLE
Multithreaded share interface segfault

### ISSUE THREAD

**Issue by JustZhenya** [curl/curl#3827]
### I did this
1. downloaded https://curl.haxx.se/libcurl/c/threaded-shared-conn.html
2. compiled
3. run
4. got segfault at random places
http://localhost/4K is avaliable and returns Apache 404 error, but I think that's not the problem.

### I expected the following
No segfault

### curl/libcurl version
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Raspbian Testing armhf, also reproduced on Debian Testing x86_64

**Comment by bagder** [comment]
This sounds very similar to a bug we fixed in 7.64.1 so I'd encourage you to try that out!

**Comment by JustZhenya** [comment]
YES! I have downloaded 7.64.1 and it helped!
I was experiencing this bug since december 2018.
Now waiting for Debian release
