### ISSUE TITLE
CURLOPT_WILDCARDMATCH with CURLOPT_CHUNK_BGN_FUNCTION: curl_fileinfo->time == 0

### ISSUE THREAD

**Issue by JCMais** [curl/curl#3829]
### I did this

Used libcurl with `CURLOPT_WILDCARDMATCH` set to true and set a `CURLOPT_CHUNK_BGN_FUNCTION` callback.

The `curl_fileinfo` argument received has `time` member set to `0`

### I expected the following

`curl_fileinfo` `time` to be set to the unix timestamp of the file.

This can be tested with this url: `ftp://ftp.rz.uni-wuerzburg.de/*`

### curl/libcurl version

curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.0i zlib/1.2.11 libidn2/2.1.1 libssh2/1.8.2 nghttp2/1.32.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

### operating system
Linux (Ubuntu)

**Comment by bagder** [comment]
Acknowledged! But this functionality unfortunately never worked as it was never actually implemented. The empty date parsing function that was provided in the initial implementation from May 2010 (commit 0825cd80a) was removed in 2015 in commit 86e2197337632.

I personally don't have any strong desire to implement this now and would probably prefer to document this struct field as always set to zero, which is the truth.

**Comment by JCMais** [comment]
@bagder thanks for answering, makes sense for me. Library users can still parse the date string available on `strings.time` themselves.
