### ISSUE TITLE
pthread_attr_setstacksize() not called prior to pthread_join()

### ISSUE THREAD

**Issue by nihilus** [curl/curl#3840]
Which leads to every thread to default to the archictures default stack size (usually 8MB) which might invoke the OOM-killer and such on embedded platforms.

I've tested setting the minimum stacksize for pthreads and so far it works fine after 1 month of testing.

**Comment by bagder** [comment]
That has worked for you. I tried in #3843 and I got immediate segfaults with minimum stack size and even with a 100K on some systems. I don't think we have enough information to be able to set a universal "good" stack size. The particular pthread implementations actually have a better insight since they're typically built and adapted for the target platforms.

I'm leaning towards saying that yes, this can be optimized if you have knowledge of your platform but is very hard for us to do in a general fashion.

**Comment by jay** [comment]
@nihilus threads in libcurl are currently used just for the threaded resolver IIRC. You can switch to libcurl built with c-ares resolver which is also asynchronous. I'm guessing though that's only going to delay the inevitable if you're using a 32-bit platform that is running out of memory for other reasons.

**Comment by nihilus** [comment]
I might check that out, is it using select/poll?

**Comment by bagder** [comment]
Yes, the c-ares-using backend will do select/poll to get the results.

**Comment by nihilus** [comment]
How much flash storage does it eats, seems to be kind of a beast. Could I fit it into an EMMA2 system (iirc had some issues with the port when going Linux 2.6 aeons ago ;)) to take a real world scenario? And would it be a fast response?

**Comment by bagder** [comment]
If you want really tiny you use the stock/sync resolver. I have a libcurl.so on x86-64 with HTTPS enabled at 135KB on disk (requires #3844, lots of features disabled and some hands-on).

**Comment by nihilus** [comment]
Neat, seems to remove proxy support and DoH among other things; things however tend to go on the other way.

However as long as things are working(?) I prefer to wait for a stable release.

**Comment by nihilus** [comment]
It might be an uClibc difference from other libcs that make this working on my devices for instance.

**Comment by bagder** [comment]
Right. You can focus on a change for a limited platform while our change will run on large variety of different platforms and libcs etc so its much harder to make a generic decision for the world rather than for a narrow and specific platform you know and control...

**Comment by nihilus** [comment]
Indeed, musl is by default allocating 80kb as thread stack size.

However I think there is some awareness to be raised about it; I think it could be optionally configured in the configure-script for those interested (that will imply that the milage my vary).

**Comment by jay** [comment]
> I think it could be optionally configured in the configure-script

How many people would use that though? How would they know what to set? We don't even know what to set. This seems like an issue that's specific to you.

**Comment by bagder** [comment]
That would just be a huge footgun, basically guiding users into doing something that will then blow up in their faces. A disservice. Unless we also can guide them to a sensible number, which we can't. Sorry, but I agree with @jay and I can't see how we can offer something good with this.

**Comment by bagder** [comment]
Neither we nor users have a sensible way to determine what a "large enough" stack is.
