### ISSUE TITLE
--with-gssapi with Heimdal is ignored on macOS unless you also pass --with-gssapi-libs

### ISSUE THREAD

**Issue by JCMais** [curl/curl#3841]
This happens because of this check:
https://github.com/curl/curl/blob/c86d635b66ee0bf769076cfb1c187ccac032d41a/configure.ac#L1411-L1416

It ignores completely the cases where `GSSAPI_ROOT` is different than the default (`/usr`, set here https://github.com/curl/curl/blob/master/configure.ac#L1316)

I discovered that by building a static linked version of libcurl with Heimdal.

The curl binary was being linked with `-lgssapi_krb5` instead of `-lgssapi` which is the library reported by `$path_to_heimdal/bin/krb5-config --libs gssapi`

For Kerberos (MIT) it works correctly, in reality it fails if we pass `--with-gssapi-libs`, because it then tries to link against `-lgssapi` but on Kerberos it's `-lgssapi_krb5`.

**Comment by JCMais** [comment]
ty @stale bot, but the problem still exists

**Comment by bagder** [comment]
@JCMais any chance you can propose a fix? Otherwise I believe this issue will get mentioned in KNOWN_BUGS and this issue here get closed.

**Comment by JCMais** [comment]
@bagder tt's unlikely I will be able to propose a fix to this issue.

Feel free to mention it on KNOWN_BUGS and close the issue. 👍
