### ISSUE TITLE
configure  script fails to link with static version of LDAP (built with OpenSSL)

### ISSUE THREAD

**Issue by JCMais** [curl/curl#3845]
I don't know if this has been brought up before, could not find any similar issue.

I don't know if it's expected, but when using an OpenLDAP version that depends on OpenSSL, libcurl does not seem to add OpenSSL path that was given to it via ./configure when trying to find the correct libraries to link with OpenLDAP. It pass only `-lcrypto -lssl`, as can be seen here: https://github.com/curl/curl/blob/1e853653d2022bec831af62ec55765e6df62e356/acinclude.m4#L795

I had to add the OpenSSL path directly using `LDFLAGS`

Steps:

1. build a static version of OpenLDAP with an also static version of OpenSSL
2. Set  `CPPFLAGS="-I$OPENLDAP_BUILD_FOLDER/include"` and `LDFLAGS="-L$OPENLDAP_BUILD_FOLDER/lib"`
3. call `./configure` with `--disable-shared --with-ssl=$path_to_openssl --enable-ldap --enable-ldaps`

LDAP related output from `./configure`:
```
configure:21593: result: cannot find LDAP libraries
configure:21614: WARNING: Cannot find libraries for LDAP support: LDAP disabled
```

The reason:
```
cannot find -lssl
cannot find -lcrypto
```

Is that something expected to happen and the correct fix is to add OpenSSL paths to `LDFLAGS` like I did?

libcurl version: 7.64.1

config.log: https://gist.github.com/JCMais/58fbabf599727e9c60ea259e8321609d

**Comment by bagder** [comment]
We only make a minimum effort of building with static versions of the dependencies since chasing their respective dependencies and do checks for those is really complicated and hard. A never-ending race.

For static dependencies, I think letting the user provide the correct LDFLAGS and LIBS extra setup is okey.

**Comment by JCMais** [comment]
Got it, closing this then, since it's not a real issue.
