### ISSUE TITLE
custom --styled-output

### ISSUE THREAD

**Issue by cup** [curl/curl#3847]
Currently I am using this script to style cURL headers:

~~~awk
#!/usr/bin/awk -f
BEGIN {
   while ("curl -I -L " ARGV[1] | getline) {
      if (index($1, ":")) {
         $1 = sprintf("\33[1;33m%s\33[m", $1)
      }
      print
   }
}
~~~

However I noticed that as of 7.61.0 a similar method is available:

https://curl.haxx.se/docs/manpage.html#--styled-output

but it seems to have no way to customize it. I would prefer the keys to be
"yellow bold" instead of just "bold". Does cURL have some way to do this?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

But the answer is: no - curl only has the simple bold headers and there are no plans in making it more advanced or configurable.
