### ISSUE TITLE
No linefeed after JSON string in recent curl update

### ISSUE THREAD

**Issue by marioroy** [curl/curl#3851]
### Edge case for recent 7.64.x.

curl 7.64.1 outputs * Closing connection without a line feed character causing JSON extraction and parsing to be problematic. A prior release 7.63.0 is fine.

```
{"status":"success"}* Closing connection 0
```

### I expected the following.

```
# Please insert leading line feed "\n* Closing connection 0\n".

{"status":"success"}
* Closing connection 0
```

### Operating system.

```
FreeBSD 12.0
```

**Comment by jay** [comment]
> {"status":"success"}* Closing connection 0

curl only outputs what was received from the server. It will not add a line feed. I'm not sure why the difference though. Run both with `--trace -` to see the output in hex (do not add `-v` for verbose since it overrides trace mode).

> causing JSON extraction and parsing to be problematic.

How's that? Are you mixing stdout and stderr? `* Closing connection 0` is output to stderr.

**Comment by marioroy** [comment]
Ah, yes stderr is directed to stdout as you suspected in our application.

Output from curl 7.63.0. There is one blank line.
```
* Connection #0 to host 127.0.0.1 left intact
{"status":"success"}

Status code: 200
```

And the output from curl 7.64.1. We will need to capture stdout and stderr separately. Notice the two blank lines.
```
* Connection #0 to host 127.0.0.1 left intact
{"status":"success"}* Closing connection 0


Status code: 200
```

**Comment by jay** [comment]
Absolutely. Catch them separately. It's still unclear to me why the output is consistently different though, I expect it would be the same.
