### ISSUE TITLE
Using -d @filename.json to POST strips out newline characters

### ISSUE THREAD

**Issue by 6wl** [curl/curl#3859]
### I did this
Make a POST like the following:-
curl -vs -XPOST -d @test.json -H "content-type: application/json" http://webhook.site/21d7ff53-49b1-4b69-a67a-d0ad4dee5c9a

Where the file test.json was
wc test.json 
  31   62 1051 test.json

(ie 1051 bytes)

However, the curl added content-length header was 1020.  If I captured the POST data, it was the json file, but missing the newline characters.

However, if I use
curl -v -XPOST -H "content-type: application/json" -d '{
  "sequenceId": 2,
  "id": "b3f234cf-db23-4e85-963f-a38dd8516df4",
  "name": "dynamic-content.snapshot.published",
  "requestId": "ae4a0b32-4fbb-4e6f-a6e2-82037074bfd8",
  "resource": "5b6ab07e52faff0001267193",
  "payload": {
    "id": "5cd53abbc9e77c000106e299",
    "comment": "Publish Manifest for content item text-area-en",
    "createdDate": "2019-05-10T08:47:55.133Z",
    "createdBy": "15a10f53-3685-4cf1-95f5-0f1d2fdcb604",
    "createdFrom": "content-item",
    "type": "SYSTEM",
    "meta": [],
    "taggedEditions": [],
    "locale": null,
    "rootContentItem": {
      "label": "Text area EN",
      "contentTypeUri": "http://ec2-54-229-148-158.eu-west-1.compute.amazonaws.com:8081/content_types/text-area.json",
      "id": "84a68172-bc22-48ad-b64a-4ae808bb13fe"
    },
    "_links": {
      "self": {
        "href": "https://apigee-dev.adis.ws/v2/content/snapshots/5cd53abbc9e77c000106e299"
      },
      "snapshot": {
        "href": "https://apigee-dev.adis.ws/v2/content/snapshots/5cd53abbc9e77c000106e299"
      }
    }
  }
}' http://webhook.site/21d7ff53-49b1-4b69-a67a-d0ad4dee5c9a

(ie the content of the json file single quote wrapped, with last newline removed), the content-length is as expected. 1050.

### I expected the following
Using -d @filename.json -H 'content-type: application/json' should include the newline characters

### curl/libcurl version
curl 7.64.0 (x86_64-redhat-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.7/openssl/zlib nghttp2/1.38.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

### operating system
Fedora 29 (but also seen on Mac)

**Comment by bagder** [comment]
To quote the man page

> When `--data` is told to read from a file like that, carriage returns and newlines will be stripped out.

Maybe use `--data-binary` instead?

**Comment by 6wl** [comment]
Sorry, indeed works, the difference in the inline posting of the data and from a file threw me.

Appreciated.
