### ISSUE TITLE
Fail to check is url exist

### ISSUE THREAD

**Issue by linherest** [curl/curl#3871]
### I did this

I wrote a func to check is url exist like this:
`
function is_url_exist($url) {

    $ch = curl_init($url);    
    curl_setopt($ch, CURLOPT_NOBODY, true);
    curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    if ($code == 200) {

        $status = true;
    } else {

        $status = false;

    curl_close($ch);

    return $status;
}
`
### I expected the following

INPUT:
`$url = 'http://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&amp;gadget=a&amp;no_expand=1&amp;refresh=604800&amp;url=https://s18.directupload.net/images/user/190511/z33rbe7z.png';`

EXPECTED RESULT:
`$status = true;`

ACTUAL RESULT: 
`$status = false;`

### curl/libcurl version

7.45.0

### operating system

- Apache/2.4.29 (Unix)
- PHP version: 7.1.12

**Comment by dfandrich** [comment]
When I try the equivalent with the curl command-line (curl -I) I get a result
HTTP/1.1 400 Bad Request. So, the server doesn't support NOBODY.

**Comment by bagder** [comment]
This means the code works exactly as intended. We can't really help that the server returns a 400...
