### ISSUE TITLE
Casing of header not shown with curl

### ISSUE THREAD

**Issue by Ryuno-Ki** [curl/curl#3877]
### I did this

`curl --head https://webmention.rocks/test/7`

### I expected the following

Same casing as in Python's `requests` library (formatted for readability):

```py
import requests

response = requests.head("https://webmention.rocks/test/7")
print(response.headers)
# {
#   'Date': 'Sun, 12 May 2019 19:29:36 GMT',
#   'Connection': 'keep-alive',
#   'Transfer-Encoding': 'chunked',
#   'LinK': '<https://webmention.rocks/test/7/webmention?head=true>; rel=webmention',
#   'Access-Control-Allow-Origin': '*',
#   'Server': 'nginx/1.14.2',
#   'Access-Control-Allow-Methods': 'GET, POST',
#   'Content-Type': 'text/html; charset=UTF-8'
# }
```
### Instead I saw the following

```
HTTP/2 200 
server: nginx/1.14.2
date: Sun, 12 May 2019 19:25:17 GMT
content-type: text/html; charset=UTF-8
link: <https://webmention.rocks/test/7/webmention?head=true>; rel=webmention
access-control-allow-origin: *
access-control-allow-methods: GET, POST
```

Note, that `link` is not shown as defined:
https://github.com/aaronpk/webmention.rocks/blob/846b7f8510c38941e1da9a6f9632eff671026d95/lib/Rocks/DiscoveryTestData.php#L68

### curl/libcurl version

```
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.0.2r zlib/1.2.11 libidn2/2.0.4 nghttp2/1.33.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

Sabayon Linux. `uname -a` shows:

```
Linux t520 5.0.0-sabayon #1 SMP Wed Apr 3 19:23:26 UTC 2019 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by bagder** [comment]
This is not a bug.

As you can see, the curl request is done using HTTP/2. With HTTP/2 all headers are done lowercase and that's exactly what curl shows. I presume your Python comparison used HTTP/1, and if you do the same request with curl and tells it to use HTTP/1 you'll see that curl will show you the same casing as it receives over the wire.

**Comment by Ryuno-Ki** [comment]
Closing then after filled against the webmention.rocks repository.
Thanks for your reply!
