### ISSUE TITLE
CURLOPT_READFUNCTION doc should be improved

### ISSUE THREAD

**Issue by RoyBellingan** [curl/curl#3885]
It would be nice to have a reference function implementation that shows how should be used, like https://curl.haxx.se/libcurl/c/getinmemory.html for https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

In addition the page https://curl.haxx.se/libcurl/c/CURLOPT_UPLOAD_BUFFERSIZE.html has a link to https://curl.haxx.se/libcurl/c/CURLOPT_READFUNCTION.html but not the opposite.

**Comment by jay** [comment]
The [EXAMPLE](https://curl.haxx.se/libcurl/c/CURLOPT_READFUNCTION.html#EXAMPLE) section links to https://curl.haxx.se/libcurl/c/ftpupload.html is that not sufficient?

**Comment by bagder** [comment]
That option is used by numerous examples, for example [ftpuploadfrommem](https://curl.haxx.se/libcurl/c/ftpuploadfrommem.html).

**Comment by bagder** [comment]
Apart from that little fix I don't see any actionable item here. @RoyBellingan can you elaborate on what specifically the existing documentation for this option doesn't cover?

**Comment by RoyBellingan** [comment]
@bagder I have never seen the ftpuploadfrommem ! I think just having this one linked is enough!
@jay No sorry, in that example the comment in the function says ... that well this is just an example, and real world usage will be different

**Comment by bagder** [comment]
> real world usage will be different

But that goes for all examples! They are after all *examples*, we don't expect any of them to be used exactly verbatim by people. They're there to show how the APIs are used and that example does show how the API is used even if the exact implementation possibly won't be used in applications.

**Comment by jay** [comment]
I agree. Examples are just that, examples.
