### ISSUE TITLE
connect fails when done in a thread on MIPS32

### ISSUE THREAD

**Issue by abhijitsahu** [curl/curl#3889]
### I did this
We are able to download successfully using below libcurl lib in main application. 
However if the same download api , calling from separate thread (using pthread) it is unable to download. 
Same issue can able to reproduce in the example app "threaded-ssl.c" as well.In this example we have enabled **CURLOPT_VERBOSE**.

(For PC - Cross-compiled with GCC toolchain both in main application as well as separate thread app/multi-threaded ; download successful!!! )

_Issue/Error observed:_
                           Curl  download fails with below error.
'* Hostname was NOT found in DNS cache
'*   Trying 209.132.180.131...
'* Immediate connect fail for 209.132.180.131: Success
'* Closing connection 0

We are cross compiling with mipsel-linux-gcc MIPS32 toolchain.

[root@localhost curl-7.37.1]#export CROSS_COMPILE="mipsel-linux"
[root@localhost curl-7.37.1]# **CPPFLAGS="-I/home/work_bench/libcurl_openssl/openssl-1.0.2o/my_build/lib -I/home/work_bench/libcurl_openssl/openssl-1.0.2o/my_build/include -I/home/work_bench/libcurl_openssl/new/c-ares-1.15.0/my_build/include" LDFLAGS="-L/home/work_bench/libcurl_openssl/new/c-ares-1.15.0/my_build/lib -lcares -L/home/work_bench/libcurl_openssl/openssl-1.0.2o/my_build/lib -lssl -L//home/work_bench/libcurl_openssl/openssl-1.0.2o/my_build/lib -lcrypto -ldl -lpthread" ./configure --prefix=/home/work_bench/libcurl_openssl/new/curl-7.37.1/my_build --target=${CROSS_COMPILE} --host=${CROSS_COMPILE} --with-ssl --enable-ares --enable-threads**

**[root@localhost curl-7.37.1]# file my_build/lib/libcurl.so.4.3.0** 
my_build/lib/libcurl.so.4.3.0: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, with debug_info, not stripped

### I expected the following

It should download successfully(as similar to download without thread function).

### curl/libcurl version

[curl -V output]
curl 7.37.1 (mips-unknown-linux-gnu) libcurl/7.37.1 OpenSSL/1.0.2o c-ares/1.15.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS Largefile NTLM NTLM_WB SSL TLS-SRP 

**NOTE:** _Also we have verified with latest **curl version "7.64.1"** and "openssl 1.1.1b" , able to reproduce the very same issue_

### operating system
MIPS32 toolchain
**[root@localhost curl-7.37.1]# file my_build/lib/libcurl.so.4.3.0** 
my_build/lib/libcurl.so.4.3.0: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, with debug_info, not stripped

**Comment by jay** [comment]
> * Immediate connect fail for 209.132.180.131: Success

That means the connect() system call failed and errno afterwards was 0. When connect fails errno should be set. It makes no sense that it would be set to 0/success. I don't know why you would see that and I can't find any similar issue. Here is the relevant code from 7.64.1:

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/connect.c#L1117-L1170

I doubt this is a curl issue but I'm not certain. Please make sure you are following the [thread safety guidelines](https://curl.haxx.se/libcurl/c/threadsafe.html).

**Comment by bagder** [comment]
So there's some threading issues on this platform that we're not ware of so no precautions or fixes for it are applied. What @jay says makes it feel like errno might be affected. It is very curious since curl works multi-threaded on Linux on other architectures and has done so for decades. How is threading different on mipsel?

**Comment by abhijitsahu** [comment]
Thanks for quick input and making correction on subject. We are looking into it further, will be come back asap. Thank you again.

**Comment by abhijitsahu** [comment]
@jay has rightly pointed out the issue.Thank you.

We have double confirmed and verified the same. System call "connect()" fails however error number set to "0" instead proper error code. Without libcurl lib - also we have written one sample server/client program to reproduce it from **thread** ,when connect() fails and check the error code it has **NOT** set properly. However in error case connect() system call set error code properly in main app/single thread application.

So we are assuming issue might be tool-chains libs/kernel side, need further analysis on this.

Thank you again @jay @bagder for the patience and such a wonderful support! Now we may close this issue. Thanks.

**Comment by bagder** [comment]
Suspected problem in the tool-chains libs/kernel side. Closing for now.
