### ISSUE TITLE
With "-C -" and "-o out" command line option, curl doesn't resume but appends to existing file

### ISSUE THREAD

**Issue by img2tab** [curl/curl#3898]
### I did this

`curl -o BaseSystem.dmg 'http://swcdn.apple.com/content/downloads/21/07/041-59913/m210y0lkn7bsiqsi98vfuyk08x2z4to1qk/BaseSystem.dmg' -C -`
(Keyboard interrupt - CTRL-C - before the transfer is complete, then attempt to resume)
`curl -o BaseSystem.dmg 'http://swcdn.apple.com/content/downloads/21/07/041-59913/m210y0lkn7bsiqsi98vfuyk08x2z4to1qk/BaseSystem.dmg' -C -`

### I expected the following

curl should "automatically find out where/how to resume the transfer." Instead, curl downloads the file from the beginning, and appends the received data to the existing file.

The download resumes correctly with other downloaders, for example `wget -c` and Firefox 66.0.5.

### curl/libcurl version

curl 7.64.1 (x86_64-pc-cygwin) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.4 libpsl/0.18.0 (+libidn2/2.0.2) libssh/0.8.7/openssl/zlib nghttp2/1.37.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets

**Comment by bagder** [comment]
Cannot reproduce. I verified doing these steps:
## Crate a 1M partial file
    $ truncate -s 1M BaseSystem.dmg
## Get the remainder:
    $ curl -o BaseSystem.dmg 'http://swcdn.apple.com/content/downloads/21/07/041-59913/m210y0lkn7bsiqsi98vfuyk08x2z4to1qk/BaseSystem.dmg' -C -
## Check the final size
    $ ls -l BaseSystem.dmg 
    -rw-r--r-- 1 daniel daniel 479908177 maj 18 22:11 BaseSystem.dmg
## Check the remote size
    $ curl -sI 'http://swcdn.apple.com/content/downloads/21/07/041-59913/m210y0lkn7bsiqsi98vfuyk08x2z4to1qk/BaseSystem.dmg' | grep -i Content-Length:
    Content-Length: 479908177

I tested with 7.64.0 vanilla from a Debian Linux (sid) and with my 7.65.0-DEV version.

**Comment by img2tab** [comment]
I can't reproduce either. Server-side error that was fixed?
