### ISSUE TITLE
Difference between --noproxy and --no-proxy?

### ISSUE THREAD

**Issue by HRK44** [curl/curl#3906]
I can't find any documentation on it, or maybe it's just a weird behavior...

I have a curl command like this (simplified) that it is executed on a server behind a proxy, and I don't want to use the proxy for a specific route :

curl toto:1337/api -> doesn't work because of the proxy

curl toto:1337/api --no-proxy toto:1337/api -> works fine...

curl toto:1337/api --noproxy toto:1337/api -> doesn't work (hits the proxy)

curl toto:1337/api --noproxy toto -> works fine...

Anyone can explain the difference or link to some docs for --no-proxy ?

Thanks

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

`--proxy` sets the proxy string to use.
`--noproxy` defines what domains to not use proxy for

`--no-proxy` is just wrong and should probably generate an error. As it is trying to negate an option that isn't a boolean.

**Comment by HRK44** [comment]
Hi @bagder 

`curl toto:1337/api --no-proxy toto:1337/api ` this works tho in my example, that's why I'm kinda confused...

**Comment by bagder** [comment]
Yes, because `--no-proxy` will act exactly like `--proxy`. The `--no-` prefix only has a meaning for boolean command line options.

**Comment by bagder** [comment]
I intend to make `--no-proxy` cause an error since it doesn't make sense. See #3907.

**Comment by HRK44** [comment]
@bagder thanks !
