### ISSUE TITLE
Can't upload file: "curl: (52) Empty reply from server"

### ISSUE THREAD

**Issue by timur-orudzhov** [curl/curl#3909]
I'm trying to automate file uploading to an storage via curl and when i run curl, it's fails with: **curl: (52) Empty reply from server**

command, that i run:

```sh
curl -i -v -XPUT "https://api.selcdn.ru/v1/SEL_xxxxx/backup/" -H "X-Auth-Token: $SELECTEL_ACCESS_TOKEN" -H "X-Delete-After: $SELECTEL_DELETE_AFTER" -T "file.txt"
```

But when i run with explicit token it works as expected and upload file.

### curl/libcurl version

curl 7.61.1 (x86_64-alpine-linux-musl) libcurl/7.61.1 LibreSSL/2.0.0 zlib/1.2.11 libssh2/1.8.2 nghttp2/1.32.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 

[curl -v output]
```
* TCP_NODELAY set
* Connected to api.selcdn.ru (92.53.68.204) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.selcdn.ru
*  start date: Oct 23 00:00:00 2018 GMT
*  expire date: Dec 21 12:00:00 2020 GMT
*  subjectAltName: host "api.selcdn.ru" matched cert's "*.selcdn.ru"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=RapidSSL RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5627355965e0)
> PUT /v1/SEL_64924/container_name/file HTTP/2
> Host: api.selcdn.ru
> User-Agent: curl/7.61.1
> Accept: */*
> X-Auth-Token: xxxxxxxxxxxxx
> X-Delete-After: 259200
> Content-Length: 129
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* Empty reply from server
* Connection #0 to host api.selcdn.ru left intact
curl: (52) Empty reply from server
```

### operating system

alpine v. 3.8.4

**Comment by timur-orudzhov** [comment]
@bagder Thanks for your attention! If you need more info, i'll do my best to provide it!

**Comment by bagder** [comment]
This could be a server error as it looks like it doesn't respond anything but just closes the connection. An HTTP server should always respond *something*.

This request negotiates and uses HTTP/2. Can you do other transfers on this server over HTTP/2?

If you try adding `--http1.1` to your command line to force-use HTTP/1.1, does that make the transfer work?

**Comment by timur-orudzhov** [comment]
@bagder i after debugging we've realized that this bug is not related with curl. I'm sorry for distraction. The problem was in the token itself and we got sort of like this: 'xxxxxxx\r'. Of course, **\r** is source of a problem.
