### ISSUE TITLE
curl 7.65.0 does not work when --disable-proxy is set

### ISSUE THREAD

**Issue by jsopenrb** [curl/curl#3931]
### I did this
Running curl from command line produces `curl: (48) Error`

### curl/libcurl version
curl 7.65.0 (arm-openwrt-linux-gnu) libcurl/7.65.0 OpenSSL/1.0.2r zlib/1.2.11 librtmp/2.3
Release-Date: 2019-05-22
Protocols: file ftp ftps http https rtmp rtsp
Features: AsynchDNS HTTPS-proxy Largefile libz NTLM NTLM_WB SSL UnixSockets

Commit `proxy: acknowledge DISABLE_PROXY more` added many `#ifndef CURL_DISABLE_PROXY` checks. This causes `vsetopt` to return `CURLE_UNKNOWN_OPTION` when proxy is disabled during compilation. Compiling without `--disable-proxy` makes it work again.

**Comment by jay** [comment]
Probably a duplicate of #3926

**Comment by bagder** [comment]
And a PR to fix it is suggested in #3929

**Comment by jsopenrb** [comment]
My bad, haven't looked at recent PRs
