### ISSUE TITLE
Apple Secure Transport: ignore errSSLPeerAuthCompleted if CURLOPT_SSL_VERIFYPEER is 0

### ISSUE THREAD

**Issue by smuellerDD** [curl/curl#3932]
### I did this

my code contains:
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);

I use curl with Apple Secure Transport.

During the handshake SSLRead returns -9841 which translates into https://developer.apple.com/documentation/security/1503828-secure_transport_result_codes/errsslpeerauthcompleted

Curl terminates the connection due to SSLRead returned an error. The select call in the function sectransp_recv chooses the "default" entry.

### I expected the following

I would presume that this return code is expected when CURLOPT_SSL_VERIFYPEER is set to 0.

Thus, curl should gracefully accept that return code with CURLOPT_SSL_VERIFYPEER set to 0.

### curl/libcurl version

7.54

However, the issue seems to be present in the current GIT HEAD.

### operating system

macOS 10.14.5

**Comment by bagder** [comment]
Clearly the code doesn't expect -9841 to be returned from SSLRead() but has code for it when returned from SSLHandshake():

https://github.com/curl/curl/blob/0edf6907ae37e2020722e6f61229d8ec64095b0a/lib/vtls/sectransp.c#L2371-L2377

Is this perhaps a renegotiation or something? @nickzman, do you have any thoughts?

The [error code is documented](https://developer.apple.com/documentation/security/errsslpeerauthcompleted) as:

> A non-fatal result indicating the peer certificate is valid, or was ignored if verification is disabled.

Does this imply we should just call the function again?

**Comment by smuellerDD** [comment]
Am Donnerstag, 23. Mai 2019, 16:42:47 CEST schrieb Daniel Stenberg:

Hi Daniel,

> Does this imply we should just call the function again?

As I read it, the code should just proceed like in the code you pointed to. 
The TLS stack informed curl that the cert could not be verified.

Ciao
Stephan

**Comment by bagder** [comment]
If you can reproduce this case, can you try #3933 ? I couldn't try it out, I just wrote it "blindly".
