### ISSUE TITLE
multi socket: segfault when given a redirect

### ISSUE THREAD

**Issue by TvdW** [curl/curl#3952]
### I did this

https://gist.github.com/TvdW/3807e802463c712e2c5909c772a9d863

This code segfaults for me. Could be related to #3904, not sure.

### I expected the following

No segfault

### curl/libcurl version

```
curl 7.65.0 (x86_64-pc-linux-gnu) libcurl/7.65.0 OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.1 c-ares/1.15.0 nghttp2/1.38.0
Release-Date: 2019-05-22
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

### operating system

CentOS 7, custom-built curl

**Comment by bagder** [comment]
Looks very similar to #3904
