### ISSUE TITLE
fix cookie query support without write to jar file.

### ISSUE THREAD

**Issue by xwxbug** [curl/curl#3954]
### I did this
i want query cookie info.
but don't like write to file.
i read this documen:
https://curl.haxx.se/libcurl/c/CURLINFO_COOKIELIST.html

  /* enable the cookie engine with a non-existing file */
  curl_easy_setopt(curl, CURLOPT_COOKIEFILE, "-");

if code running on windows,program will wait for stdin input....

maybe write a option to setting non-existing cookie file?without waitting for input someting...
### curl/libcurl version

[curl -V output]
7.65
### operating system
windows 7/VS 2017

**Comment by bagder** [comment]
The [docs](https://curl.haxx.se/libcurl/c/CURLOPT_COOKIEFILE.html) clearly describes both how to not use a file and that "-" is stdin:

> Given an empty or non-existing file or by passing the empty string ("") to this option, you can enable the cookie engine without reading any initial cookies. If you tell libcurl the file name is "-" (just a single minus sign), libcurl will instead read from stdin.

**Comment by xwxbug** [comment]
OK,Got it.
