### ISSUE TITLE
multi: requests may get response for request issued in parallel (or timeout, or errors)

### ISSUE THREAD

**Issue by TvdW** [curl/curl#3956]
https://gist.github.com/TvdW/f4815f8080d9dc30daa5d74b1f878dae

There's a nginx server running on 127.0.0.1, listening on port 80 for http/1.1, and on port 81 for http/2 (no TLS on either). I guess a simple nginx config to reproduce would be along the lines of

```
server {
listen *:80;
root /var/empty;
location / { }
}
server {
listen *:81 http2;
root /var/empty;
location / { }
}
```

Full log: https://gist.github.com/TvdW/37f7e01bf7b3b8763557d0a1c204379f

Seems to be a new bug in 7.65.0, 7.64.1 did not have it.

**Comment by TvdW** [comment]
(This was originally reported as #3951 but I accidentally stumbled upon a different bug while minimizing the test case and reported that bug instead.)

**Comment by bagder** [comment]
I can reproduce the (unexpected) timeout. It seems always be one of the h1 requests...
~~~
* Operation timed out after 1001 milliseconds with 0 bytes received
* Marked for [closure]: Disconnected with pending data
