### ISSUE TITLE
Potentially uninitialized pointer usage in parse_proxy()

### ISSUE THREAD

**Issue by bnason-nf** [curl/curl#3959]
Hi,

Starting with curl-7_65_0 when building with MSVC and Whole Program Optimization (/GL and /LTCG), I get a link time warning that parse_proxy() has a potentially uninitialized pointer usage.

I think the linker here is complaining that in `parse_proxy()`, `portptr` is defined without being initialized. If the `curl_url_get(`) call that typically initializes `portptr` exits early because the `CURLU` parameter is null, then `portptr` would be uninitialized when it is used in the block immediately following that call.

I'm not sure if this can ever actually happen, bit to address it would be trivial by either initializing `portptr` to null, or ensuring that all paths of `curl_url_get()` initialize the third parameter if not null.

I'm happy to submit a pull request for either of these, or some other fix, depending on which you prefer.

Thanks,
Benbuck

**Comment by bagder** [comment]
Thanks. Agreed! Fix pending...

**Comment by bagder** [comment]
The fix was so easy and straight-forward I just pushed it right away!

**Comment by bnason-nf** [comment]
Thanks
