### ISSUE TITLE
WinBuild Visual Studio 2019

### ISSUE THREAD

**Issue by qtKite** [curl/curl#3960]
I followed the instructions in winbuild -> Opened the Developer Command Prompt, Ran buildconf.bat then navigated to the Winbuild directory and executed:
nmake /f Makefile.vc mode=static

This resulted in the following issues:
`libcurl_a.lib(url.obj) : error LNK2019: unresolved external symbol if_nametoindex referenced in function zonefrom_url
..\builds\libcurl-vc-x64-release-static-ipv6-sspi\bin\curl.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

Any idea what could have gone wrong?

**Comment by captain-caveman2k** [comment]
We have a static build issue which is currently impacting the Visual Studio builds.

There a couple of solutions in PR's #3934 and #3958.
