### ISSUE TITLE
Use system proxy on Windows

### ISSUE THREAD

**Issue by schlamar** [curl/curl#3965]
On Windows, the proxy is usually not configured in the `http_proxy` environment variable, but in the control panel at "internet options".

There are various downstream issues where proxy support is in a bad state because configuration right now is a hassle (e.g. https://github.com/desktop/desktop/issues/2789, https://github.com/git-for-windows/git/issues/1670).

It would be the best solution if curl automatically retrieves proxy settings from Windows if `http_proxy` is not defined.

**Comment by bagder** [comment]
Already mentioned in the TODO: https://curl.haxx.se/docs/todo.html#auto_detect_proxy

**Comment by dscho** [comment]
And didn't we have a (now-closed) ticket about this already?

*clicketyclick*

Yes. This ticket: https://github.com/curl/curl/issues/352

**Comment by bagder** [comment]
and #977

**Comment by vszakats** [comment]
I've implemented such logic for Windows in the past, based on Chromium code. It should support all desktop Windows version back to at least XP without requiring any build-time feature detection (though `HBWIN_HAS_WINHTTP_H` can be passed if the environment supports the Windows SDK header `winhttp.h`). I did not try the `HBWIN_USE_WINHTTP_DHCP` option, which is commented as problematic in the Chromium code. This implementation is a function for a high-level language, so it contains some glue code. Anyhow, it may be useable: https://github.com/vszakats/harbour-core/blob/master/contrib/hbwin/win_proxyc.c

The container project is archived, but speaking of this particular source file, it is identical to the latest version, which is being used in production.

**Comment by vszakats** [comment]
(Oh and BTW, what may make integrating proxy auto-detection somewhat problematic, is that the proxy may be different for each URL. Meaning that detection must take place before each transfer, instead of being a one-time thing at curl startup. Not sure how widespread practice it is to have per-URL proxies configured.)

**Comment by bagder** [comment]
It is at least very common to have rules to excludes specific domains/URLs which implies the check has to be done per URL. In enterprise environment it is also very common to have *different* proxies for different URLs. The latter is typically handled by PAC files for proxies, not sure the windows proxy magic deals with that...

**Comment by vszakats** [comment]
It does support PAC, as per the docs:
https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpgetproxyforurl
https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/ns-winhttp-__unnamed_struct_4

**Comment by bagder** [comment]
Thanks for your interest in improving curl. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker. (And this idea is even already listed there.)

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
