### ISSUE TITLE
Curl hangs on 204: No-Content with Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by omarroth** [curl/curl#3968]
### I did this

Ran `curl http://localhost:8080 -trace -` against minimal example:
```python
from http.server import HTTPServer, BaseHTTPRequestHandler

class HTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(204)
        self.send_header('Connection', 'keep-alive')
        self.send_header('Transfer-Encoding', 'chunked')
        # self.send_header('Content-Length', '0')
        self.end_headers()

httpd = HTTPServer(('localhost', 8080), HTTPRequestHandler)
httpd.serve_forever()

```

### I expected the following

Expected curl to terminate, instead hangs permanently or until exited.

Similar issue described in https://serverfault.com/q/870072 from 2017, although doesn't appear to have been reported.

As an important note testing with #3702 the above works as expected. Since the mentioned PR appears to be fixing a different issue I think it's still important to mention here, but please let me know if this should be closed in favor of #3702.

### curl/libcurl version

```
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

```
$ uname -srv
Linux 5.1.5-arch1-2-ARCH #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019
```

**Comment by bagder** [comment]
> it appears #3702 fixes this

Can you try it and see that it actually does fix it for you?

**Comment by omarroth** [comment]
Yep, I checked before opening this, testing with #3702 works as expected. Sorry for not being clear.
