### ISSUE TITLE
error: one or more libs available at link-time are not available run-time. Libs used at link-time

### ISSUE THREAD

**Issue by nephaste** [curl/curl#3969]
Hi Curl Team

i am trying to compile Curl 7.2.65 against another libc with dynamic-linker in LDFLAGS (yes my target system is pretty old)
all dependencies were correctly compiled for and in my $PREFIX

unfortunately autoconf suck me in segmentation fault error ...

`checking for struct timeval... yes
checking run-time libs availability... ./configure: line 28730: 10614 Segmentation fault      cat confdefs.h -  > conftest.$ac_ext <<_ACEOF
/* end confdefs.h.  */

int main()
{
  return 0;
}

_ACEOF

./configure: line 2315: 10617 Segmentation fault      sed 's/^/| /' conftest.$ac_ext 1>&5
./configure: line 2315: 10618 Segmentation fault      rm -rf conftest.dSYM conftest_ipa8_conftest.oo
failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2   -lidn2   -lssh2 -lssh2 -lpsl -lssl -lcrypto -lssl -lcrypto   -L/opt/Apache73/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/opt/Apache73/lib -L/opt/Apache73/lib -Wl,-rpath,/opt/Apache73/lib -Wl,--rpath=/opt/Apache73/lib -Wl,--dynamic-linker=/opt/Apache73/lib/ld-linux.so.2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -llber -lbrotlidec -lbrotlidec -lz
./configure: line 28: 10628 Segmentation fault      exit $1
./configure: line 83: 10623 Done                    ( set ) 2>&1
     10624 Done(139)               | case $as_nl`(ac_space=' '; set) 2>&1` in
    *${as_nl}ac_space=\ *)
        sed -n "s/'/'\\\\''/g;
          s/^\\([_$as_cr_alnum]*_cv_[_$as_cr_alnum]*\\)=\\(.*\\)/\\1='\\2'/p"
    ;;
    *)
        sed -n "/^[_$as_cr_alnum]*_cv_[_$as_cr_alnum]*=/p"
    ;;
esac
     10625 Segmentation fault      | exit $1
./configure: line 83: 10629 Broken pipe             for ac_var in $ac_subst_vars;
do
    eval ac_val=\$$ac_var; case $ac_val in
        *\'*)
            ac_val=`$as_echo "$ac_val" | sed "s/'/'\\\\\\\\''/g"`
        ;;
    esac; $as_echo "$ac_var='$ac_val'";
done
     10630 Segmentation fault      | exit $1
./configure: line 83: 10631 Segmentation fault      exit $1
./configure: line 86: 10632 Segmentation fault      exit $1
`
using

`
PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"  \
CXXFLAGS="-O2 -I${PREFIX}/include -I${PREFIX}/include/ncursesw"     \
LDFLAGS="-L${PREFIX}/lib -Wl,--rpath=${PREFIX}/lib  -Wl,--dynamic-linker=${PREFIX}/lib/ld-linux.so.2" \
CPPFLAGS="-O2 -I${PREFIX}/include -I${PREFIX}/include/ncursesw "     \
./configure \
--prefix=${PREFIX} \
--bindir=${PREFIX}/bin \
--sbindir=${PREFIX}/bin \
--libexecdir=${PREFIX}/libexec \
--libdir=${PREFIX}/lib \
--datadir=${PREFIX}/share \
--datarootdir=${PREFIX}/share \
--sysconfdir=${PREFIX}/etc \
--sharedstatedir=${PREFIX}/com \
--localstatedir=${PREFIX}/var \
--includedir=${PREFIX}/include \
--oldincludedir=${PREFIX}/include \
--infodir=${PREFIX}/share/info \
--localedir=${PREFIX}/share/locale \
--enable-threaded-resolver \
--with-ssl=$PREFIX \
--with-libssh2=$PREFIX  \
--with-libssh=$PREFIX \
--with-gssapi=$PREFIX \
--with-nghttp2=$PREFIX \
--with-brotli=$PREFIX \
`
i really dont understand the problem here... does anyone has an idea on how to fix this ?

Full config.log on Pastebin

https://pastebin.com/pj8R5Kf7

thanks a lot to any one who can help me to fix it

**Comment by nephaste** [comment]
found.. my zlib was making mess

**Comment by bagder** [comment]
Sorry but your report here is a mess. Can you tell us clearly what command line you used and what you expected it to do?

**Comment by nephaste** [comment]
Hi Badler, 

Finally it is not still getting this segmentation fault when performing autoconf...
I wonder to know if anyone has any clue... i recompiled all dependencies with my dynamic-linker...
Just curl refuse to perform .. stuck on runtime issue

https://pastebin.com/bSem5U7p

it us not command line... it is compilation time... with ./configure

**Comment by bagder** [comment]
It seems your gcc is segfaulting when the configure script invokes it for its checks. That's a problem with your setup, not with the configure script!

**Comment by nephaste** [comment]
mmm strange... never had this issue with the 100th dependencies i build...
i applied same skeleton each time.... 
I used the gcc 4.8.4 from ubuntu trusty (same i used to build the glibc 2.25 which is dynamically linked to all the dependencies)

dont understand how it could be possible... more over all built dependencies are working and binaries correctly linked to my custom libc.so.6 ...  may be there is a flag to bypass this runtime check...

**Comment by bagder** [comment]
The log file shows you the exact command line that segfaults. You can debug it if you want by invoking it manually on your system. configure shouldn't be able to do anything that makes your compiler segfault, without the compiler being the one to blame, that I can think of.

> may be there is a flag to bypass this runtime check

There's no existing option to bypass that check, no, but you can edit configure.ac (and create a new configure with autopconf) and thus bypass whatever you want. I don't think that will help you though, as a segfault like this is a sign of major badness and I would imagine that you will run into that problem from a different angle even if you edit out this particular check.

**Comment by nephaste** [comment]
you mean this line ?

```
configure:28714: gcc -o conftest -O2 -isystem /opt/Apache73/include -isystem /opt/Apache73/include/ncursesw -Werror-implicit-function-declaration -Wno-system-headers -O2 -isystem /opt/Apache73/include -isystem /opt/Apache73/include/ncursesw -I/opt/Apache73/include   -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include   -I/opt/Apache73/include  -I/opt/Apache73/include   -I/opt/Apache73/include   -L/opt/Apache73/lib -Wl,--rpath=/opt/Apache73/lib  -Wl,--dynamic-linker=/opt/Apache73/lib/ld-linux.so.2 -L/opt/Apache73/lib   -L/opt/Apache73/lib -L/opt/Apache73/lib   -L/opt/Apache73/lib  -L/opt/Apache73/lib   -L/opt/Apache73/lib   conftest.c -lnghttp2   -lidn2   -lrtmp -lssh2 -lssh2 -lpsl -lssl -lcrypto -lssl -lcrypto   -L/opt/Apache73/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/opt/Apache73/lib -L/opt/Apache73/lib -Wl,-rpath,/opt/Apache73/lib -Wl,--rpath=/opt/Apache73/lib -Wl,--dynamic-linker=/opt/Apache73/lib/ld-linux.so.2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lbrotlidec -lbrotlidec -lz -lldap -llber >&5
./configure: line 2324: 27883 Segmentation fault      $CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5
configure:28714: $? = 139
configure: program exited with status 139
```
I will try but i am afraid to not enought knownledge

**Comment by bagder** [comment]
Yes, that one.

>  i am afraid to not have enough knowledge

Then find someone who can help you with your system setup/gcc installation because that's where this problem originates.

**Comment by nephaste** [comment]
I will check.. think something in script is doing an export LD_LIBRARY_PATH to my $PREFIX/lib
then generating this segfault....

**Comment by bagder** [comment]
The configure script will set `LD_LIBRARY_PATH` when it checks that it can actually use the libs at run-time.

**Comment by nephaste** [comment]
indeed just removed 

```
   old=$LD_LIBRARY_PATH
   LD_LIBRARY_PATH=$CURL_LIBRARY_PATH:$old
   export LD_LIBRARY_PATH
```
on line 28696 

and it passed.. and compiled fine

`  Host setup:       i686-pc-linux-gnu
  Install prefix:   /opt/Apache73
  Compiler:         gcc
   CFLAGS:          -O2 -isystem /opt/Apache73/include -isystem /opt/Apache73/include/ncursesw -Werror-implicit-function-declaration -Wno-system-headers
   CPPFLAGS:        -O2 -isystem /opt/Apache73/include -isystem /opt/Apache73/include/ncursesw -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include -I/opt/Apache73/include
   LDFLAGS:         -L/opt/Apache73/lib -Wl,--rpath=/opt/Apache73/lib -Wl,--dynamic-linker=/opt/Apache73/lib/ld-linux.so.2 -L/opt/Apache73/lib -L/opt/Apache73/lib -L/opt/Apache73/lib -L/opt/Apache73/lib -L/opt/Apache73/lib -L/opt/Apache73/lib -L/opt/Apache73/lib
   LIBS:            -lcares -lnghttp2 -lidn2 -lrtmp -lssh2 -lssh2 -lpsl -lssl -lcrypto -lssl -lcrypto -L/opt/Apache73/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/opt/Apache73/lib -L/opt/Apache73/lib -Wl,-rpath,/opt/Apache73/lib -Wl,--rpath=/opt/Apache73/lib -Wl,--dynamic-linker=/opt/Apache73/lib/ld-linux.so.2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lbrotlidec -lbrotlidec -lz -lldap -llber

  curl version:     7.65.0
  SSL:              enabled (OpenSSL)
  SSH:              enabled (libSSH2)
  zlib:             enabled
  brotli:           enabled (libbrotlidec)
  GSS-API:          enabled (MIT Kerberos/Heimdal)
  TLS-SRP:          enabled
  resolver:         c-ares
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              enabled (libidn2)
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   /etc/ssl/certs/ca-certificates.crt
  ca cert path:     no
  ca fallback:      no
  LDAP:             enabled (OpenLDAP)
  LDAPS:            enabled
  RTSP:             enabled
  RTMP:             enabled (librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              enabled
  Alt-svc:          no      (--enable-alt-svc)
  HTTP2:            enabled (nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP LDAPS POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         SSL UnixSockets libz brotli AsynchDNS IDN GSS-API PSL SPNEGO Kerberos NTLM NTLM_WB TLS-SRP HTTP2 HTTPS-proxy
`
and all libs are finally well linked to the final binary

`root@ubuntu32:/SRC/curl-7.65.0# ldd /opt/Apache73/bin/curl
        linux-gate.so.1 =>  (0xf77ec000)
        libcurl.so.4 => /opt/Apache73/lib/libcurl.so.4 (0xf775d000)
        libz.so.1 => /opt/Apache73/lib/libz.so.1 (0xf7741000)
        libc.so.6 => /opt/Apache73/lib/libc.so.6 (0xf759e000)
        libcares.so.2 => /opt/Apache73/lib/libcares.so.2 (0xf758b000)
        libnghttp2.so.14 => /opt/Apache73/lib/libnghttp2.so.14 (0xf7562000)
        libidn2.so.0 => /opt/Apache73/lib/libidn2.so.0 (0xf7544000)
        librtmp.so.1 => /opt/Apache73/lib/librtmp.so.1 (0xf7523000)
        libssh2.so.1 => /opt/Apache73/lib/libssh2.so.1 (0xf74f5000)
        libpsl.so.5 => /opt/Apache73/lib/libpsl.so.5 (0xf74e4000)
        libssl.so.1.1 => /opt/Apache73/lib/libssl.so.1.1 (0xf7457000)
        libcrypto.so.1.1 => /opt/Apache73/lib/libcrypto.so.1.1 (0xf71c7000)
        libgssapi_krb5.so.2 => /opt/Apache73/lib/libgssapi_krb5.so.2 (0xf717f000)
        libbrotlidec.so.1 => /opt/Apache73/lib/libbrotlidec.so.1 (0xf7171000)
        libldap-2.4.so.2 => /opt/Apache73/lib/libldap-2.4.so.2 (0xf7133000)
        liblber-2.4.so.2 => /opt/Apache73/lib/liblber-2.4.so.2 (0xf7126000)
        /opt/Apache73/lib/ld-linux.so.2 => /lib/ld-linux.so.2 (0x56613000)
        libunistring.so.2 => /opt/Apache73/lib/libunistring.so.2 (0xf6faa000)
        libpthread.so.0 => /opt/Apache73/lib/libpthread.so.0 (0xf6f8d000)
        libdl.so.2 => /opt/Apache73/lib/libdl.so.2 (0xf6f88000)
        libkrb5.so.3 => /opt/Apache73/lib/libkrb5.so.3 (0xf6ec1000)
        libk5crypto.so.3 => /opt/Apache73/lib/libk5crypto.so.3 (0xf6e8c000)
        libcom_err.so.3 => /opt/Apache73/lib/libcom_err.so.3 (0xf6e86000)
        libkrb5support.so.0 => /opt/Apache73/lib/libkrb5support.so.0 (0xf6e78000)
        libbrotlicommon.so.1 => /opt/Apache73/lib/libbrotlicommon.so.1 (0xf6e56000)
        libresolv.so.2 => /opt/Apache73/lib/libresolv.so.2 (0xf6e40000)
        libsasl2.so.3 => /opt/Apache73/lib/libsasl2.so.3 (0xf6e23000)
        libiconv.so.2 => /opt/Apache73/lib/libiconv.so.2 (0xf6d3d000)
`

thanks to point me in the right direction.... may be an improvment to do in autoconf script ^^

**Comment by bagder** [comment]
No.

This is your compiler/setup that is faulty. It is not a configure problem.
