### ISSUE TITLE
Infinite loop in singlesocket

### ISSUE THREAD

**Issue by ericwuseattle** [curl/curl#3970]
(gdb) p *entry
$29 = {
  list = {
    head = 0x80be848,
    tail = 0x80be848,
    dtor = 0x0,
    size = 1
  },
  action = 1,
  socketp = 0x0,
  users = 1,
  readers = 1,
  writers = 0
}

1) the loop i = 0 to MAX_SOCKSPEREASYHANDLE
https://github.com/curl/curl/blob/master/lib/multi.c#L2234

2) i was setting back to 0
https://github.com/curl/curl/blob/master/lib/multi.c#L2255

3) when entry action == comboaction will go back 1) and i = 1, 2) will set to 0 again. loop forever.
// comboaction = 1, entry->action = 1
https://github.com/curl/curl/blob/master/lib/multi.c#L2306

could we make a change to use index rather re-using i?
For example:
/* check if new for this transfer */
int index = 0;
for(index; index < data->numsocks; index++) {

**Comment by bagder** [comment]
Thanks, I agree with your conclusion and I've proposed PR #3973 to fix this!

**Comment by ericwuseattle** [comment]
Sounds great, thanks Daniel.
________________________________
