### ISSUE TITLE
No libcurl-nss.so on Manjaro

### ISSUE THREAD

**Issue by MGlolenstine** [curl/curl#3979]
### I did this
- Downloaded the curl source
- Ran ./buildconf
- Ran ./configure --without-ssl --with-nss
- Ran make
- Ran make install
### I expected the following
- I expected to get /usr/local/lib/libcurl-nss.so.4
### I got this
- error while running the program requiring libcurl-nss:
`error while loading shared libraries: libcurl-nss.so.4: cannot open shared object file: No such file or directory`
### curl/libcurl version

[curl -V output]
curl 7.65.1-DEV (x86_64-pc-linux-gnu) libcurl/7.65.1-DEV NSS/3.44 zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) nghttp2/1.36.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL UnixSockets

### operating system
uname -a: Linux lifeordeath-pc 4.19.45-1-MANJARO #1 SMP PREEMPT Wed May 22 17:16:41 UTC 2019 x86_64 GNU/Linux

**Comment by bagder** [comment]
Building libcurl from source creates `libcurl.so`. If you instead want it named *libcurl-nss* then you need to rename it.
