### ISSUE TITLE
curl doesn't abort the transfer when the network cable is unplugged

### ISSUE THREAD

**Issue by Sleepingbug** [curl/curl#3981]
Setting the timeout is too large and it will not be disconnected in time

1) try to post a file and set timeout as beblow:

curl_easy_setopt( curl, CURLOPT_TIMEOUT, 600 );
...
curl_easy_setopt( curl, CURLOPT_XFERINFOFUNCTION, myCallback );
...
int result = curl_easy_perform( curl );
...

2) Unplug the network cable At the beginning of uploading a file ( yes,  to make sure it is disconnected )

3) it is not disconnected until it reaches timeout(600 seconds )

**Comment by Sleepingbug** [comment]
it will not execute the code to next line to curl_easy_perform until reaches timeout(600 seconds )

**Comment by bagder** [comment]
[Why doesn't curl return an error when the network cable is unplugged?](https://curl.haxx.se/docs/faq.html#Why_doesn_t_curl_return_an_error)

**Comment by Sleepingbug** [comment]
thank you very much.

**Comment by Sleepingbug** [comment]
@bagder thank you very much
