### ISSUE TITLE
Building Android 21 with clang results in fread_chk linker errors

### ISSUE THREAD

**Issue by jbfitb** [curl/curl#3987]
### I did this

Tried to build curl for Android using the following configure command:

```
        CC="${CC}" \
        CXX="${CXX}" \
        CFLAGS="-fstack-protector-strong -D__ANDROID_API__=${API_LEVEL}" \
        CPPFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector-strong -D__ANDROID_API__=${API_LEVEL} -I${INSTALL_TARGET_INCLUDE}" \
        LDFLAGS="-L${INSTALL_TARGET_LIB}" "${CURL_LIBRARY_SOURCE}/configure" \
                ${DISABLE_RPATH} \
                --prefix="${INSTALL_TARGET}" \
                --with-sysroot="${SYSROOT}" \
                --host="${TOOLCHAIN_HOST}" \
                --build="${TOOLCHAIN_BUILD}" \
                --enable-optimize \
                --enable-hidden-symbols \
                --enable-cookies \
                --disable-largefile \
                --disable-static \
                --disable-ftp \
                --disable-file \
                --disable-ldap \
                --disable-rtsp \
                --disable-proxy \
                --disable-dict \
                --disable-telnet \
                --disable-tftp \
                --disable-pop3 \
                --disable-imap \
                --disable-smb \
                --disable-smtp \
                --disable-gopher \
                --disable-manual \
                --disable-verbose \
                --disable-sspi \
                --disable-crypto-auth \
                --disable-tls-srp \
                --disable-unix-sockets \
                --without-zlib \
                --without-ca-bundle \
                --without-ca-path \
                --with-ssl \
                --with-libssl-prefix="${INSTALL_TARGET}" \
                --with-nghttp2="${INSTALL_TARGET}" \
```

using android-ndk-r19c and Android 21 API level

### I expected the following

Expected the build to complete successfully.

Actual result:

```
../lib/.libs/libcurl.so: error: undefined reference to '__fread_chk'
../lib/.libs/libcurl.so: error: undefined reference to '__fwrite_chk'
clang80: error: linker command failed with exit code 1 (use -v to see invocation)
```

### curl/libcurl version
https://github.com/curl/curl/tree/curl-7_65_0

### operating system

MacOS 10.14.4. Cross-compiling for Android API level 21, architecture armeabi-v7a using `android-ndk-r19c` toolchain clang: `~/Library/Android/ndk/toolchains/android-ndk-r19c/toolchain-armeabi-v7a/android-21/bin/arm-linux-androideabi-clang`

**Comment by bagder** [comment]
Those look like functions [provided by bionic](https://android.googlesource.com/platform/bionic/+/fed2659/libc/bionic/__fread_chk.cpp) itself. I don't know what the build should do to find them or why they're not just automatically found by the compiler already.

**Comment by bagder** [comment]
I don't think this is a problem with curl or curl's configure script. I think this is a problem with your setup/compiler/libc. Possibly this problem is triggered by you setting `-D_FORTIFY_SOURCE=2`, but that still doesn't make it a curl issue...

**Comment by bagder** [comment]
No response and suspected issue with the build/environment. Closing.
