### ISSUE TITLE
Curl post request issue using two headers?

### ISSUE THREAD

**Issue by kchetans** [curl/curl#3988]
# **I am trying to hit curl post method but I am facing the issue, but the same thing I am doing using postman it's working.**

I TRIED USING CURL CMD

1. curl -X POST -H "x-csrf-token: k2SEjLbc90ox5JRCJHllagGciIvkFEO5HojPdfvj+63mK+YKAKT76d8E/ROGsoEqkwVqqy3dQvIXMV0qPT3MMg==" -H "Content-Type: application/json" -d '{"userName":"ABEAS", "password":"ZWthdXNoYWw="}' http://13.232.166.60/api/user/v1/login.

2. curl -X POST -d "userName=ABEAS&password=ZWthdXNoYWw=" -H "Content-Type: application/x-www-form-urlencoded" -H "x-csrf-token: k2SEjLbc90ox5JRCJHllagGciIvkFEO5HojPdfvj+63mK+YKAKT76d8E/ROGsoEqkwVqqy3dQvIXMV0qPT3MMg==" http://13.232.166.60/api/user/v1/login

RESPONSE:- Unauthorized

WHEN I TRIED USING POSTMAN

![alt text](https://i.stack.imgur.com/ms6Rt.png)

![alt text](https://i.stack.imgur.com/F4Wah.png)

**Comment by jay** [comment]
Ref: https://stackoverflow.com/questions/56443297/facing-curl-post-request-issue-using-two-headers

This is an issue tracker and what you are reporting is not a curl issue, it is a question about using the curl tool. Please read the [FAQ](https://curl.haxx.se/docs/faq.html) and use mailing list [curl-users](https://cool.haxx.se/mailman/listinfo/curl-users) to ask questions about curl.

Postman has a 'Code' link that can [convert requests](https://learning.getpostman.com/docs/postman/sending_api_requests/generate_code_snippets/) to lots of different formats including the curl tool.
