### ISSUE TITLE
Re-think curl_global_init() and curl_global_cleanup()

### ISSUE THREAD

**Issue by nicowilliams** [curl/curl#3990]
There are two issues with the current `curl_global_init()`/`curl_global_cleanup()` functions:

 - They are currently not thread-safe.

   This is a problem for users of `libcurl` that are themselves libraries.  If a threaded application uses two or more libraries that each uses `libcurl`, then there can be races to initialize/cleanup -- the disparate callers of `libcurl` cannot coordinate `libcurl` initialization/cleanup.

   This is a recurring problem in many libraries.  OpenSSL used to have this problem, especially as to lock callbacks and such.  OpenSSL 1.1 and up is now self-initializing.

 - Having an explicit global init/cleanup function call requirement is not very developer-friendly.

    - Developers can forget to initialize.

   - Arranging to cleanup via `atexit()` is racy because it is difficult to arrange `atexit()` callback order in a process that has more than one library (and/or the executable itself) calling `atexit()`.

   Self-initialization and self-cleanup, if it really is needed, is much more developer-friendly.

Possible actions to take here include:

 - Make these two functions thread-safe, and keep an atomically-incremented/decremented count of calls to `curl_global_init()` so that only the last matching `curl_global_cleanup()` actually cleans up.

   I'd do this with a mutex.

 - Make `libcurl` self-initialize via either `pthread_once()` (POSIX) / `InitOnceExecuteOnce()` (WIN32), or `.init` section (ELF), / `DllMain() (WIN32), and self-cleanup, if it really is needed, via `.fini` ("destructors", ELF platforms) / `DllMain()` (WIN32), is much better.  Preferably do not use `atexit()` as noted above.

   Self-initialization via `pthread_once()`/`InitOnceExecuteOnce()` entails having any `libcurl` function that needs the library to have been initialized call an internal init function that calls the once-initializer.  This approach is more invasive and annoying, and will add the overhead of post-once calls to `pthread_once()`/`InitOnceExecuteOnce()` (which is low, but not zero).

   Self-initialization via `.init` text or `DllMain()` is much better, but cleanup via `.fini` text or `DllMain()` is racy for multi-threaded applications that call `exit()` instead of `_exit()` when they still have active threads.  Some such applications are bound to exist, and though they are effectively engaging in UB, nonetheless you might hesitate before doing something that might push them over the edge.

   In the self-initialization case you'll still need to leave behind `curl_global_init()` and `curl_global_cleanup()` for API and ABI backwards-compatibility -- either as do-nothing functions, or as functions that keep an atomic count of initializations.

   If you want to support mixed self-initialization and explicit cleanup, then you will need to have one global boolean that gets set to true if ever `libcurl` gets self-initialized before any calls to `curl_global_init()` then not even the last matching `curl_global_cleanup()` will induce cleanup.

I might author and contribute a PR, but before I do I would like to hear your preferences as to how to handle this.  Doing nothing is an option too, but IMO it's a poor option (and we, the community, would have to end up applying local patches to make initialization safe anyways).

Regarding `libcurl` global finalization (cleanup), if it can at all be avoided, I would prefer to do that.  I'm not too interested in doing it just to placate leak detectors.  There can be good reasons to have global finalization, but I'm generally skeptical of the need for it.  For example, if an application repeatedly loads and unloads a library, maybe it's better to load it once and keep it loaded, and the library can force this by getting and leaking a handle to itself.

**Comment by kdudka** [comment]
On Wednesday, June 5, 2019 1:14:00 AM CEST Nico Williams wrote:
> Possible actions to take here include:
> 
>  - Make these two functions thread-safe, and keep an
> atomically-incremented/decremented count of calls to `curl_global_init()`
> so that only the last matching `curl_global_cleanup()` actually cleans up.
> 
>    I'd do this with a mutex.

The problem is that the mutex object itself needs to be explicitly initialized 
on some platforms, so you would run into a chicken-egg problem.  One of the 
responsibilities of curl_global_init() is actually to initialize mutexes ;-)

>  - Make `libcurl` self-initialize via either `pthread_once()` (POSIX) /
> `InitOnceExecuteOnce()` (WIN32), or `.init` section (ELF), / `DllMain()
> (WIN32), and self-cleanup, if it really is needed, via `.fini`
> ("destructors", ELF platforms) / `DllMain()` (WIN32), is much better. 
> Preferably do not use `atexit()` as noted above.
> 
>    Self-initialization via `pthread_once()`/`InitOnceExecuteOnce()` entails
> having any `libcurl` function that needs the library to have been
> initialized call an internal init function that calls the once-initializer.
>  This approach is more invasive and annoying, and will add the overhead of
> post-once calls to `pthread_once()`/`InitOnceExecuteOnce()` (which is low,
> but not zero).
> 
>    Self-initialization via `.init` text or `DllMain()` is much better, but
> cleanup via `.fini` text or `DllMain()` is racy for multi-threaded
> applications that call `exit()` instead of `_exit()` when they still have
> active threads.  Some such applications are bound to exist, and though they
> are effectively engaging in UB, nonetheless you might hesitate before doing
> something that might push them over the edge.
> 
>    In the self-initialization case you'll still need to leave behind
> `curl_global_init()` and `curl_global_cleanup()` for API and ABI
> backwards-compatibility -- either as do-nothing functions, or as functions
> that keep an atomic count of initializations.
> 
>    If you want to support mixed self-initialization and explicit cleanup,
> then you will need to have one global boolean that gets set to true if ever
> `libcurl` gets self-initialized before any calls to `curl_global_init()`
> then not even the last matching `curl_global_cleanup()` will induce
> cleanup.

The proposed solutions might work better in _some_ cases but I do not think 
that any of them would would _in general_ work better than what we have now.

> I might author and contribute a PR, but before I do I would like to hear
> your preferences as to how to handle this.  Doing nothing is an option too,
> but IMO it's a poor option (and we, the community, would have to end up
> applying local patches to make initialization safe anyways).

From my observation, the transparent initialization feature is missing not 
because devlopers were lazy to put the code in, but because it is nearly 
impossible to implement correctly, covering all the corner cases we care 
about.

> Regarding `libcurl` global finalization (cleanup), if it can at all be
> avoided, I would prefer to do that.  I'm not too interested in doing it
> just to placate leak detectors.  There can be good reasons to have global
> finalization, but I'm generally skeptical of the need for it.  For example,
> if an application repeatedly loads and unloads a library, maybe it's better
> to load it once and keep it loaded, and the library can force this by
> getting and leaking a handle to itself.

In that case, you can just omit the call to curl_global_cleanup() with the 
current API.  Am I missing anything?

Kamil

**Comment by nicowilliams** [comment]
Thanks for the reply.

> The problem is that the mutex object itself needs to be explicitly initialized on some platforms, so you would run into a chicken-egg problem. One of the responsibilities of curl_global_init() is actually to initialize mutexes ;-)

This is a non-issue.  In the absolute worst case you can have a spin lock using atomic operations to initialize a mutex if the platform lacks static initializers.  None of the modern platforms lack a way to do automatic initialization though: on Windows you can just use `DllMain()`, while on all ELF platforms you can use `.init` sections, leaving only `a.out`-based static linking as a concern, but on most of those you can use mutexes (because `pthreads` includes static initializers).

For an (unnecessary!) example of a spin lock see [this SO answer](https://stackoverflow.com/questions/3555859/is-it-possible-to-do-static-initialization-of-mutexes-in-windows/9490113#9490113) about how to emulate `pthreads` static mutex initializers on Windows.  (Unnecessary because initialization on Windows can be done in `DllMain()`.)

> The proposed solutions might work better in _some_ cases but I do not think
that any of them would would _in general_ work better than what we have now.

What you have now is _not_ thread-safe!  It is a disaster waiting to happen.

You can keep the `curl_global_init()` and `curl_global_cleanup()` functions so that in statically-linked non-ELF cases there is a way to initialize and finalize, but make them no-ops (or mostly no-ops) in all other cases.

>From my observation, the transparent initialization feature is missing not
because devlopers were lazy to put the code in, but because it is nearly
impossible to implement correctly, covering all the corner cases we care
about.

Eh, I didn't say or imply anything about the curl devs being lazy.

OpenSSL self-initializes nowadays.  OpenSSL had the same problem, but worse because OpenSSL is used by more libraries than `libcurl` -- the problem had to be fixed.

> >  Regarding `libcurl` global finalization (cleanup), if it can at all be avoided, I would prefer to do that.  [...]
> In that case, you can just omit the call to curl_global_cleanup() with the current API. Am I missing anything?

Yes: `curl_global_init()` is NOT thread-safe.  It is thread-unsafe.  It is dangerous.  It needs fixing.

I'm asking for guidance before I write a PR.

**Comment by kdudka** [comment]
On Wednesday, June 5, 2019 5:58:44 PM CEST Nico Williams wrote:
> What you have now is _not_ thread-safe!  It is a disaster waiting to happen.

Yes, curl_global_init() and curl_global_cleanup() are not thread-safe.  This
fact has been documented since 2006:

    https://github.com/curl/curl/commit/4c35a408#diff-fe9de52fb4cb39d2122d87fce7a3d625R29

The current libcurl documentation also explains why calling curl_global_init()
from DllMain() is a bad idea:

    https://github.com/curl/curl/commit/19ca4010

> I'm asking for guidance before I write a PR.

To be clear, I am not driving this project.  I have just expressed my personal
opinion on the proposal.

**Comment by bagder** [comment]
This area is worth exploring and if possible, improve. It is however a messy situation.

It should be noted that the thread unsafety is due to requirements by 3rd party libraries and not really because of our choices. So, if a libcurl-using application is also using one of these 3rd party libraries, those libraries are in fact thread-unsafe to init no matter who does it so even if you would fix libcurl's init to be safe by enforcing the use of a thread library (which we haven't done so far so libcurl can very well be used without a thread library), that won't make the application safe from thread problems if they would use the same 3rd party library in some other way...

**Comment by nicowilliams** [comment]
@bagder ah, hey, I'm not saying you've done something bad, and it's true that the thread-unsafety issue comes from... libcurl being so good that other libraries want to use it.  What I am saying is that that means it's time to improve the situation.  This happens and has happened to other libraries like libcurl, such as OpenSSL.

Regarding "enforcing the use of a thread library"...  a `./configure` `--disable-thread` option can always be had that gets one the previous thread-unsafe behavior, and requiring the use of the platform's thread library as a _default_ is quite fine, really.  Long gone are the days when one had to worry that finding an appropriate thread library might be difficult.

So, my initial proposal is as follows:

 - keep `curl_global_init()` and `curl_global_cleanup()`
 - have `curl_global_init()` call a private `global_init()` function that uses `pthread_once()` or similar
 - add a self-initalization step that calls `global_init()` in functions like `curl_easy_init()`
 - if self-initialized, then finalization won't be done
    - or maybe self-finalization can then be done in a `.fini` (ELF) or `DllMain()` (Windows)

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
