### ISSUE TITLE
`CURLOPT_NOSIGNAL` should be on by default

### ISSUE THREAD

**Issue by nicowilliams** [curl/curl#3996]
Using `siglongjmp()` to "cancel" a slow `getaddrinfo()` call is unsafe.  Calling any C library functions after that can result in a deadlock, especially calling `getaddrinfo()` again.  In June 2018 I had a mission-critical application deadlock this way on many hosts at once due to a DNS outage causing timeouts that made `getaddrinfo()` slow enough to trip the connection timeout I was setting on the curl easy handle.

Libraries must not use `alarm(2)`, though it's reasonable in the case libcurl when the caller is the `curl(1)` executable, but  generally it's not reasonable.

A better way to timeout `getaddrinfo()` is to start a detached thread to run `getaddrinfo()` and the `pthread_cond_timedwait()` for it.  If there are no threads, then `vfork()`/`exec()`/`spawn()`/`posix_spawn()` a helper and wait for it by polling on a pipe.

**Comment by bagder** [comment]
1. The default curl build uses the threaded resolver and thus will not use `alarm()` or `siglongjmp()` cancel name resolves.
2. Yes, this a known flaw in the current legacy resolver setup. I'm not however very keen at changing this default at this point.

**Comment by bagder** [comment]
This problem is discussed in the [TODO](https://curl.haxx.se/docs/todo.html#signal_based_resolver_timeouts).

**Comment by nicowilliams** [comment]
Oh, so the fix is to use `./configure --enable-ares`?  Will that honor things like `/etc/hosts` and `/etc/nsswitch.conf`?  There seems to be code in `lib/asyn-thread.c` for using a thread to call `getaddrinfo()`, no?

**Comment by bagder** [comment]
If you want to use c-ares for name resolving, yes. The default is using the stock resolver in a separate thread using pthreads and that's selected without any option.
