### ISSUE TITLE
"Unsupported protocol"Protocol "https"   not supported or disabled in libcurl

### ISSUE THREAD

**Issue by scjaiyueliang** [curl/curl#3998]
it shows that
curl -V
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.1.0g zlib/1.2.8
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

but a problem comes
"Unsupported protocol"Protocol "https"
  not supported or disabled in libcurl

**Comment by bagder** [comment]
That looks like you gave curl a very weird URL to work with?

**Comment by bagder** [comment]
Please show us a complete command line that reproduces this problem!

**Comment by scjaiyueliang** [comment]
I solve this problem through the methods in the links below
"https://www.bountysource.com/issues/31029799-automatic-hunter-download-fails-with-protocol-https-not-supported-or-disabled-in-libcurl"

**Comment by scjaiyueliang** [comment]
Thank you all the same!
