### ISSUE TITLE
travis coverage build hangs

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#4004]
### I did this

Since either https://github.com/curl/curl/commit/8581e1928ea8e125021408ec071fcedb0276c7fe (canceled) or https://github.com/curl/curl/commit/2f11fbf208c78d38e9a19b1224238c4ecff5989f (failed), coverage builds are failing because `No output has been received in the last 10m0s` after event-based `test 0089...[HTTP with NTLM and follow-location]`.
See https://travis-ci.org/curl/curl/builds and https://coveralls.io/github/curl/curl.

### I expected the following

The job to succeed.

### operating system

Ubuntu Xenial on Travis

**Comment by MarcelRaad** [comment]
I've restarted the canceled coverage build:
https://travis-ci.org/curl/curl/jobs/538157881
Also trying to reproduce locally.

**Comment by bagder** [comment]
#3997 is supposedly the medicine for that too...

**Comment by MarcelRaad** [comment]
Ah, yes, the coverage build there was successful now!

**Comment by MarcelRaad** [comment]
I can confirm that current master still fails (Ithought that maybe https://github.com/curl/curl/commit/680f1413321c0bad593a69a86511df4d98a3b5df would have fixed it as it only occurs in the event-based test) and https://github.com/curl/curl/pull/3997 fixes it!
