### ISSUE TITLE
curl Head request postman request working but curl not why?

### ISSUE THREAD

**Issue by kchetans** [curl/curl#4008]
# I am doing a head request using curl 
 **

> curl -X HEAD -I http://13.232.166.60/api/user/v1

**
**Response:-**
```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: the way you want. Consider using -I/--head instead.
HTTP/1.1 200 OK
Server: nginx/1.12.1
Date: Mon, 10 Jun 2019 10:22:52 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Expose-Headers: X-CSRF-Token
Set-Cookie: _csrf=MTU2MDE2MjE3MnxJa05aVm5KcE9ESkRObkZ5TjFWNk15OVZkVTFzYmtnd1lXNXpZeTluTUdOSVREUmlXV1ZVVVRBMVlsRTlJZ289fJgSxNu3XehxKKKRfTgLLdrTimDly5SM83gHOrvt_PNY; Path=/
Vary: Cookie
Vary: Origin
X-Csrf-Token: EeI35vg4c1tfeGeNdZqkLTy5ytPGmI5YCFcmYTCs8BoYZ1xtNbqZ8aQrWnIneYGxQaNUFPkbyV8n0f4YBJgVrg==
```
## I am using that 
X-Csrf-Token: EeI35vg4c1tfeGeNdZqkLTy5ytPGmI5YCFcmYTCs8BoYZ1xtNbqZ8aQrWnIneYGxQaNUFPkbyV8n0f4YBJgVrg==

In Second API call but I am getting **Unauthorized**

> curl -X POST -H "x-csrf-token: H7A+TUwYf596RUAGAUSaO3zhXqmVw6HyTpsBtO5hE4Zq/1zL+mBzPJSlKVejj3577ni8iVwKoLlHIpPrKL8kGQ==" -H "application/json" -d '{                  
>     "userName": "ABEAS",
>     "password":"ZWthdXNoYWw="
>   }' http://13.232.166.60/api/user/v1/login

**Response:-**
`**Unauthorized**`

But the Same thing in Postman it's working

WHEN I TRIED USING POSTMAN

![alt text](https://i.stack.imgur.com/ms6Rt.png)

![alt text](https://i.stack.imgur.com/F4Wah.png)

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

If you really want to understand the difference, then compare the two sets requests + headers that they send. Cookies? User-agent? Something else?
