### ISSUE TITLE
Add non-blocking support for aborting smtp operations

### ISSUE THREAD

**Issue by jon-harris7** [curl/curl#4015]
### I did this
Called `curl_multi_remove_handle()` when an SMTP transfer was in progress to a non-responsive server.
### I expected the following
The function call to return fairly quickly.  However, it hung until the timeout I had specified (60 seconds in my case).  I found documentation of this bug in the libcurl source for smtp.c `smtp_done()` function:

    /* Run the state-machine

       TODO: when the multi interface is used, this _really_ should be using
       the smtp_multi_statemach function but we have no general support for
       non-blocking DONE operations!
    */

So I'm requesting that this known issue be resolved in a future version.

I have discovered a work-around for my issue, which it to set the timeout to 0 immediately before calling `curl_multi_remove_handle()`:

    curl_easy_setopt(pEasy, CURLOPT_TIMEOUT, 1);
    curl_multi_remove_handle(pMulti, pEasy);

If this issue can't be easily resolved, then perhaps this work around suggestion could be added to the documentation somewhere.

### curl/libcurl version
7.64.1
[curl -V output]
cURL Version libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11

### operating system
Linux

**Comment by bagder** [comment]
[This TODO entry](https://curl.haxx.se/docs/todo.html#Non_blocking_curl_multi_remove_h) has listed this as something we want done for a very long time already. I would welcome a fix for that!

(We don't keep feature-request issues open, we only use this for tracking open bugs/issues. Expect this to get closed soon.)

**Comment by jon-harris7** [comment]
Thanks for the pointer to the docs.  Unfortunately I am unable to help with a fix.

**Comment by bagder** [comment]
Let's hope that someone else will, or pay someone else, at some point. It would certainly make libcurl better!
