### ISSUE TITLE
Consult %APPDATA% also for _netrc

### ISSUE THREAD

**Issue by raspy** [curl/curl#4016]
### I did this
I have set up `%HOMEDRIVE%%HOMEPATH%\_netrc` and `%APPDATA%\_netrc` for the server I want to connect, but it seems that neither is consulted:

```
curl.exe -nv _url_requiring_authentication_
* Couldn't find host _host_ in the _netrc file; using defaults
...
< HTTP/1.1 401 Unauthorized
```

### I expected the following
As %HOME% is not commonly set on Windows, I expected curl to consult also %APPDATA%. It is done for _curlrc, but not for _netrc. It would be good to resolve _netrc the same way. Currently it looks like no path is considered due to %HOME% not being set.

- https://github.com/curl/curl/blob/3538026f6f145b2811f4d515992565d6cbe969b0/src/tool_parsecfg.c#L59
- https://github.com/curl/curl/blob/697b1f911b6fee51ff2b271a292488fd7f9cdcda/lib/netrc.c#L80
- https://github.com/curl/curl/blob/f762fec323f36fd7da7ad6eddfbbae940ec3229e/src/tool_homedir.c#L63

The change would not impact non-Windows platforms and would not affect current behavior when %HOME% is set, since it's the first considered in homedir() function.

### curl/libcurl version
```
> curl.exe -V
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

### operating system
Microsoft Windows [Version 10.0.18362.175]

**Comment by bagder** [comment]
Maybe do it as a step in the #3989 work? What do you think @captain-caveman2k ?
