### ISSUE TITLE
Extended passive mode FTP broken on IBM i platform

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#4037]
### I did this
Moved from 7.64.1 to 7.65.1 level and built LIBCURL *SRVPGM on IBM i V7R2M0, tested extended passive mode ftp transfer

### I expected the following
libcurl to open a new socket to data port on the same ftp server following EPSV 229 response, however this failed with "Cannot resolve new host : 12345". Attached a debugger and found that various string fields on conn structure that were used to derive the host were empty.

The regression appears to have been triggered by a commit in May "libcurl: #ifdef away more code for disabled features/protocols". IBM i platform doesn't use a configure script and so various "HAVE_" defines are not set for the platform.

I can confirm that a local fix of adding HAVE_GETPEERNAME and HAVE_GETSOCKNAME to defines in "packages/OS400/initscript.sh" resolves the problem.

### curl/libcurl version
libcurl/7.65.1

### operating system
IBM i V7R2M0

**Comment by jonrumsey** [comment]
Thanks, the update to lib/config-os400.h resolves the problem.

**Comment by bagder** [comment]
Excellent, thanks for confirming!
