### ISSUE TITLE
Windows and USE_UNIX_SOCKETS

### ISSUE THREAD

**Issue by gvanem** [curl/curl#4040]
Using MSVC or clang-cl, tried to build some program under `tests/server`.
This failed miserably with things like:
```c
In file included from rtspd.c:55:
./server_sockaddr.h(41,24):  error: field has incomplete type 'struct sockaddr_un'
  struct sockaddr_un   sau;
                       ^
```

Since `USE_UNIX_SOCKETS` is set in `./lib/config-win32.h` for `NTDDI_WIN10_RS4`.
But no `#include <afunix.h>` is present under `tests/server`. 
The comment in `sws.c`:
```
* Systems which have Unix sockets will also have lstat */
```
is just assuming some Posix system; not Windows at.

My quick fix was simply:
```diff
--- a/server_sockaddr.h 2018-05-09 19:58:12
+++ b/server_sockaddr.h 2019-06-18 15:01:54
@@ -25,6 +25,8 @@

 #ifdef HAVE_SYS_UN_H
 #include <sys/un.h> /* for sockaddr_un */
+#elif WIN32
+#undef USE_UNIX_SOCKETS  /* No way */
 #endif
```
### operating system
Win-10 (1809, build 17763.557).

**Comment by bagder** [comment]
That makes an sws *without* unix-sockets support while curl in the same setup would get built *with* support, which then presumably will make those tests fail miserably...

**Comment by gvanem** [comment]
But is seems impossible for sws to run using e.g. Strawberry Perl on Windows (due to `fork()` last time I tried). So building sws using MSVC (and running with that) is probably no point (?). Others probably know more.

**Comment by bagder** [comment]
I don't know what magic that's needed (I bet @MarcelRaad can tell more), but appveyor runs the test suite on Windows for every PR and push to master like this:

https://github.com/curl/curl/blob/cf35bd79bdbe7b2155c87ed5a5da7815367ec9de/appveyor.yml#L129

**Comment by gvanem** [comment]
But I'm not sure AppVeyor uses a Windows Kit that has a `#define NTDDI_WIN10_RS4`.
So the problem is masked.  I have the Windows Kit v. 10.0.18362.0 installed here.

Where is the log of AppVeyor's build of the `tests/server` source?

**Comment by jay** [comment]
You'd have to view the full log of one of the TESTING=ON builds that uses MSVC and then search for sws. For example [here's one](https://ci.appveyor.com/project/curlorg/curl/builds/25372348/job/9pvp5oaijcar3ukf?fullLog=true#L6000) from master.

**Comment by gvanem** [comment]
Thanks Jay, but still there's no info of what Windows Kit version AppVeyor uses here. 
Probably an older version that has no `#define NTDDI_WIN10_RS4`.
Besides the CMake test fails:
```
-- Performing Test USE_UNIX_SOCKETS - Failed
```
which is a lie since that is set [here](https://github.com/curl/curl/blob/master/lib/config-win32.h#L724).

**Comment by bagder** [comment]
The cmake build doesn't use `config-win32.h`, it generates a `curl_config.h` file much in the same style as configure does.

This might rather imply that the unix sockets check in cmake is broken?

**Comment by jzakrzewski** [comment]
CMake bases the check on the presence of `sockaddr_un.sun_path`.
https://github.com/curl/curl/blob/48016832dc179a6cfd819bb7925f4723904eaaaa/CMakeLists.txt#L636-L642

**Comment by gvanem** [comment]
> ... it generates a curl_config.h file ...

Oh, I didn't see that. Which means `USE_UNIX_SOCKETS` on Windows can never be set for `tests/server/*.c`? Rather confusing IMHO.

**Comment by bagder** [comment]
> Which means USE_UNIX_SOCKETS on Windows can never be set for tests/server/*.c?

Sure it can, if the cmake check detects it and then sets the define.

**Comment by gvanem** [comment]
Then how does `struct sockaddr_un` gets pulled in for `WIN32`? It's in `<afunix.h>` which I fail to see gets included for `tests/server/*.c`. 
Please give me a link to an AppVeyor log that compiles `sws.c` with `USE_UNIX_SOCKETS`.

**Comment by bagder** [comment]
Right, as long as the cmake check is broken it doesn't work.

And since the check is then used for both curl and the test server, the unix-socket tests aren't attempted on windows since the client isn't built with the support.
