### ISSUE TITLE
ssh session error with the official curl.exe connecting to sftp

### ISSUE THREAD

**Issue by leeeqian** [curl/curl#4041]
### curl.exe does not work with certain sftp site anymore

I could not use the new official curl.exe connecting the certain sftp site, it could not exchange encryption keys

If I build the curl.exe with same libssh2/1.8.2 on visual studio 17, it works

I'm not sure if this has anything to do with the build or not

curl.exe -u <user>:<password> sftp://ftp.wrightexpress.com/ -l -k --verbose
> *   Trying 208.64.196.5:22...
> * TCP_NODELAY set
> * Connected to ftp.wrightexpress.com (208.64.196.5) port 22 (#0)
> * Failure establishing ssh session: -43, Unable to exchange encryption keys
> * Closing connection 0
> curl: (2) Failure establishing ssh session: -43, Unable to exchange encryption keys

the ssh-keyscan ftp.wrightexpress.com:22, show the server is SSH-2.0-mod_sftp/0.9.7

### I expected the following

curl.exe -u <user>:<password> sftp://ftp.wrightexpress.com/ -l -k --verbose
> * Expire in 0 ms for 6 (transfer 0x844d30)
> * Expire in 1 ms for 1 (transfer 0x844d30)
> * Expire in 0 ms for 1 (transfer 0x844d30)
> * Expire in 2 ms for 1 (transfer 0x844d30)
> * Expire in 1 ms for 1 (transfer 0x844d30)
> * Expire in 2 ms for 1 (transfer 0x844d30)
> * Expire in 4 ms for 1 (transfer 0x844d30)
> * Expire in 4 ms for 1 (transfer 0x844d30)
> * Expire in 5 ms for 1 (transfer 0x844d30)
> * Expire in 8 ms for 1 (transfer 0x844d30)
> *   Trying 208.64.196.5...
> * TCP_NODELAY set
> * Expire in 200 ms for 4 (transfer 0x844d30)
> * Connected to ftp.wrightexpress.com (208.64.196.5) port 22 (#0)
> * SSH MD5 fingerprint: <fingerprint>
> * SSH authentication methods available: publickey,hostbased,password
> * Using SSH private key file ''
> * SSH public key authentication failed: Would block requesting userauth list
> * Initialized password authentication
> * Authentication complete
> .
> ..
> <file list here>

### curl/libcurl version

**The official curl.exe  - not working**

curl 7.65.1 (i386-pc-win32) libcurl/7.65.1 OpenSSL/1.1.1c (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.8.2 nghttp2/1.39.1
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

**The curl.exe built by visual studio 2017 - works**

curl 7.64.0 (i386-pc-win32) libcurl/7.64.0 Schannel WinIDN libssh2/1.8.2
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
Windows 10 Pro - x64

**Comment by bagder** [comment]
Can you also try to build 7.65.1 yourself? That would make it a better comparison as then we'd know the reason is in the build and not in the source itself.

**Comment by leeeqian** [comment]
> Can you also try to build 7.65.1 yourself? That would make it a better comparison as then we'd know the reason is in the build and not in the source itself.

Yes, 7.65.1 also works with visual studio build

> curl 7.65.1 (i386-pc-win32) libcurl/7.65.1 Schannel WinIDN libssh2/1.8.2
> Release-Date: 2019-06-05
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI

Could this be similar to the following issue in 2012 ?

[ProFTPD SFTP connection problem](https://www.libssh2.org/mail/libssh2-devel-archive-2012-10/0037.shtml)

**Comment by leeeqian** [comment]
The exe built by Marc Hörsken seems to be working, 

Although he is using libssh2/1.8.1_DEV

> curl 7.64.1 (i686-w64-mingw32) libcurl/7.64.1 OpenSSL/1.1.1b (Schannel) zlib/1.2.11 WinIDN libssh2/1.8.1_DEV
> Release-Date: 2019-03-27
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
> Features: AsynchDNS HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP

**Comment by bagder** [comment]
Is this a problem that occurs when libssh2 >= 1.9.0 is used and it works on older libssh2 versions? If so, that would make this seem like a libssh2 bug...

**Comment by bagder** [comment]
@leeeqian is this a problem with the current curl versions we offer on the curl web site?

**Comment by bagder** [comment]
No response, closing.

**Comment by consulion** [comment]
Hi,
we are experiencing the same problem with the current version of libcurl (8.2.1).
The curl.exe from the curl website works, but when we build it ourselves with VS2022 (both when using the solution in projects\Windows\VC14.30 and when muilding with nmake as described in winbuidl/Readme.md)

Output of curl.exe looks like this:
`.\curl.exe --verbose -u test: --key key.pem sftp://192.168.100.16
* processing: sftp://192.168.100.16
*   Trying 192.168.100.16:22...
* Connected to 192.168.100.16 (192.168.100.16) port 22
* Found host 192.168.100.16 in C:\Users\test\.ssh/known_hosts
* Set "rsa-sha2-256,rsa-sha2-512,ssh-rsa" as SSH hostkey type
* SSH MD5 public key: NULL
* SSH SHA256 public key: NULL
* SSH host check: 0, key: AAAAB3NzaC1yc2EAAAABIwAAAQEArsgK03EqD7Hzt62P5+paCGQk9W3p4bA4MKnrUKZN/ediLVZv0Yj1u7ymSibVFbP9/nYrKtkbZO6D1OHKMAG/Y8Ska5E6WYgUjXw/vlsnBGA84BeqzkAphhjzz0dB1ahqTVoM3MbmTZyaH1UMCyAd9aJSMPumAigg5pR5KuMBuzne6cR88yyBzUB2rF/y7k1SI6dqUbQzQcumykFD6L0JF/i5y5f2jks3gThRdnhwjfmX5bslDDBRChyUnT3gtiw4VV2HwWvWUYplUcrh/Rhy3OAfVm87stAvTYay8iea4Trl+wpcz1qWNbi85wmcZ31kXxHEw6P1IboM7e2Dp0ocqw==
* SSH authentication methods available: publickey,password
* Using SSH private key file 'key.pem'
*** SSH public key authentication failed: Would block requesting userauth list**
* Failure connecting to agent
* Authentication failure
* Closing connection
curl: (67) Authentication failure`

interestingly, it doesn't matter if the key file exists at all, output stays the same.
When opening the same connection with libcurl (which is what we are trying to achieve), simply "CURLE_LOGIN_DENIED" is returned, the error buffer just says "Authentication failure".
We also tried getting libcurl through vcpkg with the same result.

Is there any way to get a version of libcurl for Windows32 that supports sftp correctly?
Could we help solving this problem somehow? Do you need any more information?

Thanks,
Ole

**Comment by jay** [comment]
Please don't hijack old issues like this, open a new issue instead. Compare the `curl -V` or `curl_version()` information from the curl build that works and the build that doesn't. Probably the libssh2 versions are different.

**Comment by consulion** [comment]
Sorry, i just added it here as this was one of the few google results when searching the error message `SSH public key authentication failed: Would block requesting userauth list`, but i opened a new issue #11837
