### ISSUE TITLE
--haproxy-protocol for other protocols such as FTP

### ISSUE THREAD

**Issue by kevy1234** [curl/curl#4047]
Is it possible to make --haproxy-protocol option work with other protocols such as FTP?

**Comment by bagder** [comment]
curl only supports that for HTTP(S) and RTSP(S), but I suppose the code could be modified to support other protocols as well. FTP seems a weird fit though since the HAPROXY protocol means sending a header the first thing, while FTP is a protocol where the server typically sends first.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
