### ISSUE TITLE
Multiple HTTP/2(CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE) parallel transfers with PIPEWAIT

### ISSUE THREAD

**Issue by kunalekawde** [curl/curl#4049]
### I did this
Multiple HTTP/2(with prior knowwledge) parallel transfers with PIPEWAIT

### I expected the following
HTTP/2 transfers to complete successfully

### curl/libcurl version
curl git master over 7.65.1

### operating system
Fedora 28

This is more likely a clarification which could result in issue.
 If we have CURLOPT_PIPEWAIT along with CURLPIPE_MULTIPLEX , new connection is not attempted.
Ideally when there is load/capacity run, the time period for detecting server support for multiplexing would result in send error due to "No connections available". This is immediate if PIPEWAIT is set and MAXHOSTCONNECTS post exhausting this limit.

Can we use multiplex without knowing the server support when version is set to CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE ? (In bundle creation, set to multiuse incase of http2 with prior knowledge)

**Comment by kunalekawde** [comment]
Another associated clarification under multiplexing is, the multiple http/2 transfers doesnt seem to use the same connection and multiplex, instead create new connection when max connects per host is greater than 1.

https://gist.github.com/kunalekawde/55361016249976573e2fb2bb89248eb3
This example simulates it.

**Comment by bagder** [comment]
Your code doesn't set `CURLOPT_PIPEWAIT`, and then libcurl will create new connections rather than waiting to see if it can add the request as a stream to a connection that doesn't yet exist.

**Comment by kunalekawde** [comment]
Hmm yes, probably my observation was not correct -- missed to see the pending transfers on pipe wait were attempted later. I shall close this after some more verification
