### ISSUE TITLE
CURLOPT_UPLOAD_BUFFERSIZE is not defined

### ISSUE THREAD

**Issue by ribtoks** [curl/curl#4056]
I'm trying to make use of `CURLOPT_UPLOAD_BUFFERSIZE` but I'm getting compiler error that it is not defined and indeed, it is not defined in `<curl/curl.h>` and it's brothers. I used 7.65.1 libcurl (latest you can get as of today).

**Comment by danielgustafsson** [comment]
> On 20 Jun 2019, at 17:02, Taras Kushnir <notifications@github.com> wrote:
> 
> I'm trying to make use of CURLOPT_UPLOAD_BUFFERSIZE but I'm getting compiler error that it is not defined and indeed, it is not defined in <curl/curl.h> and it's brothers. Downloaded latest 7.65.1 libcurl

It is defined using the CINIT() macro, can you show us code where you use it and how you compile your code?

**Comment by ribtoks** [comment]
I'm using it as in example `curl_easy_setopt(curl_handle, CURLOPT_UPLOAD_BUFFERSIZE, some-number-here);`, nothing special. I'm using headers from 7.65.1 and building libcurl on my own. I saw some makefiles in the headers directory. Does that imply that I should "build" headers for my system first? I was using same headers for building on mac/windows/linux.

**Comment by ribtoks** [comment]
@danielgustafsson  `CURLOPT_UPLOAD_BUFFERSIZE` is not defined in `<curl/curl.h>` with `CINIT` or without. Let me show you this page https://github.com/curl/curl/search?q=CURLOPT_UPLOAD_BUFFERSIZE

**Comment by bagder** [comment]
It's defined here: 

https://github.com/curl/curl/blob/972bdffb9f675e44abb85d93fd26507d9602d90d/include/curl/curl.h#L1903

Since 7.62.0:

https://github.com/curl/curl/blob/972bdffb9f675e44abb85d93fd26507d9602d90d/docs/libcurl/symbols-in-versions#L634

**Comment by ribtoks** [comment]
@bagder thanks a lot! It's weird, but I can see it now. Will look for an error on my end.
