### ISSUE TITLE
man page lacks examples

### ISSUE THREAD

**Issue by SoniEx2** [curl/curl#4058]
### I did this

`man curl`

### I expected the following

`EXAMPLES`

### curl/libcurl version

```
curl 7.65.1 (x86_64-pc-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

```
Linux soniex-pc 5.1.11-1-ck-ivybridge #1 SMP PREEMPT Tue Jun 18 18:26:39 EDT 2019 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
Yes please that'd be great but this is not really a bug report but a request for an enhancement and it will be closed soon. Everyone can and is encouraged to help us improve the docs.

Perhaps you could tell us some specific things you think we should include examples for?

**Comment by SoniEx2** [comment]
lack of examples isn't a bug?

**Comment by bagder** [comment]
I don't think so. It's a sweeping generalization.
