### ISSUE TITLE
Unable to build curl-7_65_1 on Universal Windows Platform (UWP)

### ISSUE THREAD

**Issue by djp952** [curl/curl#4060]
### I did this
Attempted to build libcurl for Universal Windows Platform (UWP) from source as part of an existing project

### I expected the following
A successful build based on the same project settings as used with curl-7_65_0

### curl/libcurl version
source: tag: curl-7_65_1

### operating system
Universal Windows Platform (UWP)

There was a breaking change introduced in cURL 7.65.1 (tag curl-7_65_1) in the system_win32.c file that prevents successful linking on UWP.  The snippet of the breaking change begins on line 98:

```
 s_hIpHlpApiDll = Curl_load_library(TEXT("iphlpapi.dll"));
 if(s_hIpHlpApiDll) {
   /* Get the address of the if_nametoindex function */
   IF_NAMETOINDEX_FN pIfNameToIndex =
     CURLX_FUNCTION_CAST(IF_NAMETOINDEX_FN,
                         (GetProcAddress(s_hIpHlpApiDll, "if_nametoindex")));

    if(pIfNameToIndex)
     Curl_if_nametoindex = pIfNameToIndex;
 }
```

The Win32 API functions GetModuleHandle() and LoadLibrary() are not available for UWP projects, attempting to load iphlpapi.dll and then acquiring the address of the if_nametoindex function is not possible on this platform.

As a workaround I have provided stubs for GetModuleHandle() and LoadLibrary() that return NULL in my project, which does not use the URL API so should not be adversely affected.

I suggest placing the following guard directives around the affected code, but am unsure as to the ramifications of not having the if_nametoindex function available to cURL.

`#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)`

Thanks!

**Comment by bagder** [comment]
Maybe even add a CI build that does this to make sure we catch it earlier next time!

**Comment by bagder** [comment]
Removing the `if_nametoindex` function will make curl unable to handle zone ids in IPv6 URLs and also in the proxy string option.

**Comment by bagder** [comment]
Okay, based on your description I made #4072. Is that how you meant it? Does it work? I don't build on Windows myself so this just might be totally rubbish...

**Comment by djp952** [comment]
This solves the immediate problem, thank you!  Cleanly compiled for UWP without a need for any fake declarations.

If I get some time, I will try to help out with this, those functions being accessed dynamically with LoadLibrary() should all exist on UWP but they have to be statically linked.  I'm not really into UWP either, my project uses cURL for fairly simple operations so the missing functionality isn't causing me any grief at all.  It could others in the future, though.

Thanks again! Much appreciated!
