### ISSUE TITLE
valgrind invalid read

### ISSUE THREAD

**Issue by kunalekawde** [curl/curl#4062]
### I did this
valgrind run app with libcurl.a with nghttp2 1.38.0

### curl/libcurl version
git master over 7.65.1

```
==307== Invalid read of size 8
==307==    at 0x603CBC1: ConnectionExists (url.c:1190)
==307==    by 0x6041FD6: create_conn (url.c:3704)
==307==    by 0x60427C3: Curl_connect (url.c:3972)
==307==    by 0x6008A42: multi_runsingle (multi.c:1374)
==307==    by 0x600AFD1: multi_socket (multi.c:2553)
==307==    by 0x600B6A2: curl_multi_socket_action (multi.c:2666)
```

```
1189       if(CONN_INUSE(check) && check->data &&
1190          (check->data->multi != needle->data->multi))
```

**Comment by bagder** [comment]
Please tell us how to reproduce, this output alone is not enough to do anything.

**Comment by kunalekawde** [comment]
Its HTTP/2 2000 parallel transfers for a sec on my app, there is no crash. I'll try valgrind run on sample test program may be and update.

**Comment by kunalekawde** [comment]
no luck yet to reproduce this using sample program.

**Comment by bagder** [comment]
So, 14 days and no way to reproduce. Closing. If you can come up with a way to reproduce, please comment with more details or file a new issue!
