### ISSUE TITLE
block curl from processing gab URLs

### ISSUE THREAD

**Issue by SoniEx2** [curl/curl#4069]
not a bug report but curl should return an error if an attempt to process gab URLs is found.

**Comment by bagder** [comment]
What is a "gab URL" and why should curl return an error on such a URL?

**Comment by SoniEx2** [comment]
a "gab URL" is any URL from one of the nazi domains related to what's known as "gab". curl should disallow nazis. this is especially useful with PHP on one of those cheap PHP hosts where you can't modify the curl.

**Comment by bagder** [comment]
curl itself has no host or domain filter and will not offer one. You can easily filter out anything you like in your application before you ask curl to use a URL. That's not a task for curl.

**Comment by Ekultek** [comment]
You shouldn't discriminate against Nazi's, they're people too you jerk!

**Comment by computerslut** [comment]
#staysalty xoxo

**Comment by veryyynice** [comment]
#staysalty tho

**Comment by peterptron** [comment]
#staysalty

**Comment by GhostFire90** [comment]
#staysalty

**Comment by crow-bit** [comment]
#staysalty
