### ISSUE TITLE
Unresolved external symbol UI_OpenSSL with latest OpenSSL 3.0.0

### ISSUE THREAD

**Issue by Liastre** [curl/curl#4073]
### I did this
I've built latest Curl master with latest OpenSSL master

### I expected the following
Successful build

### curl/libcurl version
7.65.2-DEV

### operating system
Building under UWP using VS2017

### details
I've got following errors:

> Curl.lib(openssl.obj) : error LNK2019: unresolved external symbol _UI_OpenSSL referenced in function _ssl_ui_reader

According to this document https://www.openssl.org/news/changelog.txt `UI_OpenSSL()` were deprecated and disabled, not sure if suggested `UI_null()` is safe to use with `UI_method_get_reader`

Usage of `UI_OpenSSL()` detected here https://github.com/curl/curl/blob/6c2b7d44e3171b634f88a6840176d780e08d8790/lib/vtls/openssl.c#L578 and there https://github.com/curl/curl/blob/6c2b7d44e3171b634f88a6840176d780e08d8790/lib/vtls/openssl.c#L596

**Comment by bagder** [comment]
I'm puzzled.

This is what their changelog says about `UI_OpenSSL()`, exactly:

> The UI API becomes a permanent and integral part of libcrypto, i.e. not possible to disable entirely.  However, it's still possible to disable the console reading UI method, UI_OpenSSL() (use UI_null() as a fallback).

**still possible to disable** doesn't mean it *is* disabled. I just built openssl from git master (again) and then subsequently curl against that lib and it worked just fine with no such linker error:

~~~
$ ./src/curl -V
curl 7.65.2-DEV (x86_64-pc-linux-gnu) libcurl/7.65.2-DEV OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.7 c-ares/1.14.0 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.40.0-DEV librtmp/2.3
~~~

How are you building your openssl when you get that disabled?

**Comment by Liastre** [comment]
I'm using build steps according the description for windows uwp:

    perl Configure VC-WIN32-UWP --prefix="path" --openssldir="path" 
    nmake
    
It might be I missed some flags

**Comment by bagder** [comment]
I have no idea what `VC-WIN32-UWP` does for the OpenSSL build but presumably this then disables that function. We need to understand what define you get set for this so that we can have the curl build use the same one and avoid trying to use `UI_OpenSSL()` when used.

Do you perhaps get `OPENSSL_NO_UI_CONSOLE` or `OPENSSL_NO_UI` defined or something?

**Comment by gvanem** [comment]
> I have no idea what VC-WIN32-UWP does for the OpenSSL build
> but presumably this then disables that function. 

Seems it's disabled for UWP. From OpenSSL's `Configurations/50-win-onecore.conf`:
```
    "VC-WIN32-UWP" => {
        inherit_from    => [ "VC-WIN32-ONECORE" ],
        lflags          => add("/APPCONTAINER"),
        defines         => add("WINAPI_FAMILY=WINAPI_FAMILY_APP",
                               "_WIN32_WINNT=0x0A00"),
        dso_scheme      => "",
        disable         => [ 'ui-console', 'stdio', 'async', 'uplink' ],
```

**Comment by Liastre** [comment]
Hey @gvanem ah I see now, thanks. I found [original pull-request discussion](https://github.com/openssl/openssl/pull/8917), there no any clue why it's been disabled.

**Comment by bagder** [comment]
@Liastre maybe something like this?
~~~diff
diff --git a/lib/vtls/openssl.c b/lib/vtls/openssl.c
index fa6d0201a..3cdcbfeb9 100644
--- a/lib/vtls/openssl.c
+++ b/lib/vtls/openssl.c
@@ -73,11 +73,11 @@
 #if (OPENSSL_VERSION_NUMBER >= 0x0090808fL) && !defined(OPENSSL_NO_OCSP)
 #include <openssl/ocsp.h>
 #endif
 
 #if (OPENSSL_VERSION_NUMBER >= 0x0090700fL) && /* 0.9.7 or later */     \
-  !defined(OPENSSL_NO_ENGINE)
+  !defined(OPENSSL_NO_ENGINE) && !defined(OPENSSL_NO_UI_CONSOLE)
 #define USE_OPENSSL_ENGINE
 #include <openssl/engine.h>
 #endif
 
 #include "warnless.h"

**Comment by gvanem** [comment]
> ... there no any clue why it's been disabled.

@Liastre, presumably since there are no `<wincon.h>` functions in UWP? So `UI_OpenSSL()` method won't work.

**Comment by Liastre** [comment]
Yay @bagder, that works! Everything is ok now. By the way I've tried and was unable to build with enabled `ui-console`, some unsupported win32 code involved.
