### ISSUE TITLE
curl --compressed not decompressing data successfully

### ISSUE THREAD

**Issue by ericcurtin** [curl/curl#4092]
### I did this

I wrote a simple http server:

https://github.com/ericcurtin/asio/commit/1d37a1d225d1e812a747b595c02f9770ebd75dd0

When I request content from the server and pipe the output to gunzip all works fine

```
curl -x "" 127.0.0.1:5000/main.cpp --output - | gunzip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   758  100   758    0     0   740k      0 --:--:-- --:--:-- --:--:--  740k
// g++ -O0 main.cpp server.cpp connection_manager.cpp request_handler.cpp
// connection.cpp reply.cpp mime_types.cpp request_parser.cpp -lboost_system
// -lpthread -lz
//
// run like: ./a.out 0.0.0.0 5000 .
//
// main.cpp
// ~~~~~~~~
//
// Copyright (c) 2003-2017 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <iostream>
#include <string>
#include <boost/asio.hpp>
#include "server.hpp"

int main(int argc, char* argv[])
{
  try
  {
    // Check command line arguments.
    if (argc != 4)
    {
      std::cerr << "Usage: http_server <address> <port> <doc_root>\n";
      std::cerr << "  For IPv4, try:\n";
      std::cerr << "    receiver 0.0.0.0 80 .\n";
      std::cerr << "  For IPv6, try:\n";
      std::cerr << "    receiver 0::0 80 .\n";
      return 1;
    }

    // Initialise the server.
    http::server::server s(argv[1], argv[2], argv[3]);

    // Run the server until stopped.
    s.run();
  }
  catch (std::exception& e)
  {
    std::cerr << "exception: " << e.what() << "\n";
  }

  return 0;
}
```

But when I try and decompress via --compressed curl flag it fails after the first 512 bytes:

```
curl -x "" 127.0.0.1:5000/main.cpp --compressed
// g++ -O0 main.cpp server.cpp connection_manager.cpp request_handler.cpp
// connection.cpp reply.cpp mime_types.cpp request_parser.cpp -lboost_system
// -lpthread -lz
//
// run like: ./a.out 0.0.0.0 5000 .
//
// main.cpp
// ~~~~~~~~
//
// Copyright (c) 2003-2017 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <iostream>
curl: (23) Failed writing received data to disk/application
#include <string
```

### I expected the following

I expected --compressed to decompress the response content successfully like gunzip did.

### curl/libcurl version

curl -V
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Ubuntu 18.04

**Comment by jay** [comment]
Try master. If that doesn't help check #3796 and try #3825. If that doesn't help please give us  the raw output from the server (ie --no-compressed) so that we can reproduce it easily. You will probably have to upload it as a .zip for github to allow it as an attachment.

**Comment by ericcurtin** [comment]
[file.txt](https://github.com/curl/curl/files/3368699/file.txt)

Tried master, unfortunately it didn't work. Here is the raw output, I appreciate your help, thanks!

**Comment by ericcurtin** [comment]
I'll try the two patches now

**Comment by ericcurtin** [comment]
#3825 doesn't work

**Comment by jay** [comment]
~~~
while true; do (perl -e 'print ("HTTP/1.1 200 OK\r\nContent-Encoding: gzip\r\n\r\n")'; cat file.txt) | nc -4l localhost 8000; done
~~~

This is similar to #3796 in that your server is non compliant and should be sending one compressed stream but instead is sending multiple compressed streams concatenated together. Each stream appears to contain <=512 bytes of uncompressed data.

This is not similar to #3796 in that this is a rather unambiguous mistake. [Z_FINISH](http://www.zlib.net/manual.html) is making separate streams. The solution is fix your implementation to send all the data in one stream rather than multiple streams.

/cc @monnerat
