### ISSUE TITLE
Compiling 7.65.0 with clang 8.0.0 and OSX SDK 10.11 fails

### ISSUE THREAD

**Issue by mxaddict** [curl/curl#4098]
### I did this 
Compiled using clang 8.0.0 and OSX SDK 10.11

### I expected the following
Expected it to compile

### curl/libcurl version
7.65.0

### operating system
Linux Ubuntu 18.04

ERRORS:
```
Undefined symbols for architecture x86_64:                                                                                                                                                                           
  "_CFBundleGetVersionNumber", referenced from:                                                                                                                                                                      
      ___clang_at_available_requires_core_foundation_framework in libcurl.a(libcurl_la-connect.o)                                                                                                                    
  "___isOSVersionAtLeast", referenced from:                                                                                                                                                                          
      _singleipconnect in libcurl.a(libcurl_la-connect.o)                                                                                                                                                            
ld: symbol(s) not found for architecture x86_64                                                                                                                                                                      
clang: error: linker command failed with exit code 1 (use -v to see invocation)                                                                                                                                      
Makefile:921: recipe for target 'curl' failed                                                                                                                                                                        
make[3]: *** [curl] Error 1                                                                                                                                                                                          
make[3]: Leaving directory '/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.1-30dcae20edd/src'                                                                      
Makefile:1966: recipe for target 'all-recursive' failed                                                                                                                                                              
make[2]: *** [all-recursive] Error 1                                                                                                                                                                                 
make[2]: Leaving directory '/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.1-30dcae20edd/src'                                                                      
Makefile:922: recipe for target 'all-recursive' failed                                                                                                                                                               
make[1]: *** [all-recursive] Error 1                                                                                                                                                                                 
make[1]: Leaving directory '/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.1-30dcae20edd'                                                                          
funcs.mk:251: recipe for target '/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.1-30dcae20edd/./.stamp_built' failed                                               
make: *** [/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.1-30dcae20edd/./.stamp_built] Error 2                                                                    
```

**Comment by mxaddict** [comment]
Copiling older version of curl `7.43.0` works with clang 8.0.0 and OSX SDK 10.11

**Comment by nickzman** [comment]
I am able to build the code just fine when I configure a static build in macOS 10.14 with Xcode 10.x, with or without Secure Transport enabled. Are you using some alternate toolchain, by any chance?

**Comment by mxaddict** [comment]
> I am able to build the code just fine when I configure a static build in macOS 10.14 with Xcode 10.x, with or without Secure Transport enabled. Are you using some alternate toolchain, by any chance?

Sorry, I forgot to mention I was compiling on Ubuntu 18.04

Not on OSX, this is related to the depends dir builds on bitcoin and navcoin core wallets.

**Comment by mxaddict** [comment]
I'm developing on navcoin-core wallet and need to update libcurl to never version in combination to OSX SDK 10.11

**Comment by nickzman** [comment]
curl on macOS uses __builtin_available() to see if certain functions are available on the user's OS. There should've been a configure-time check to see if that feature actually worked, and not compiled that code if the check failed. If you check the configure log, do you see the test passing?

I don't cross-compile macOS apps from Ubuntu, so I don't have any way of diagnosing this myself. It should work if you build it on macOS using Xcode 9 or later, though.

**Comment by mxaddict** [comment]
Is there a way to tell which feature is using those symbols?

So that I can simply disable them if I don't need them.

**Comment by nickzman** [comment]
It's in the singleipconnect() function in lib/connect.c, but that code isn't supposed to be compiled unless HAVE_BUILTIN_AVAILABLE is defined. I'm not sure why that would be defined on your cross-compiling setup if it doesn't actually work.

**Comment by mxaddict** [comment]
Thanks, i can disable that feature I think, since I don't need it.

**Comment by bagder** [comment]
@mxaddict it would be helpful if you could figure out how you got `HAVE_BUILTIN_AVAILABLE` defined in the first place, as we try to actually detect if that works and only set it if it does, which in your case it seems it doesn't!

**Comment by mxaddict** [comment]
> @mxaddict it would be helpful if you could figure out how you got `HAVE_BUILTIN_AVAILABLE` defined in the first place, as we try to actually detect if that works and only set it if it does, which in your case it seems it doesn't!

ACK, I'll see if I can debug further

**Comment by bagder** [comment]
No updates, probably a toolchain/setup issue.
