### ISSUE TITLE
Build-breaking typo in release 7.65.1.

### ISSUE THREAD

**Issue by AceCrow** [curl/curl#4102]
### I did this
1. I downloaded the latest release from https://curl.haxx.se/download.html.
2. (I created a dummy file GIT-INFO, because it needs to exist for 3).
3. I ran buildconf.bat without any errors from cmd.
4. I `cd winbuild`.
5. I ran `nmake /f Makefile.vc mode=dll`.
6. The compilation failed because the file `src/tool_hugehelp.c` included `tool_hugehelp.hd`.
7. I changed `tool_hugehelp.hd` to `tool_hugehelp.h` and recompiled. This time succesfully.
8. I tried to look up`src\tool_hugehelp.c` on github, but the file does not seem to exist there.

### curl/libcurl version
    curl 7.65.1 (x86_64-pc-win32) libcurl/7.65.1 Schannel WinIDN
    Release-Date: 2019-06-05
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
    Features: AsynchDNS IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets

### operating system
Windows 10

**Comment by danielgustafsson** [comment]
Fixed, thanks!

**Comment by AceCrow** [comment]
Np. Quick question. Why does GIT-INFO need to exist btw? The build seems to work fine with just a dummy file.

**Comment by danielgustafsson** [comment]
GIT-INFO signals that the tree comes from a git repository and not a release tarball, and so the configure script needs to be built as it's not included.
