### ISSUE TITLE
curl_error returns an empty string

### ISSUE THREAD

**Issue by iva3682** [curl/curl#4105]
### I did this
Is the php code:

```
<?php
$curlInit = curl_init('ht tp://004.ru/');

if(curl_exec($curlInit) === false) {
	$ermsg = curl_error($curlInit);
	$ercode = curl_errno($curlInit);
	$ermsgcode = curl_strerror($ercode);
	
	echo 'Error curl: ' . $ermsg . '. Code: ' . $ercode . '. MsgCode: ' . $ermsgcode;
}
else {
    echo 'No error';
}

curl_close($curlInit);

?>
```

Output: Error curl: . Code: 3. MsgCode: URL using bad/illegal format or missing URL

### I expected the following
After Error curl: an error message is expected, but curl_error returns an empty string.
### curl/libcurl version
curl 7.65.1 (x86_64-pc-linux-gnu) libcurl/7.65.1 OpenSSL/1.1.1 zlib/1.2.8
Release-Date: 2019-06-05
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

### operating system
Debian GNU/Linux 9
PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cli) (built: May 31 2019 11:27:35) ( NTS )

**Comment by dfandrich** [comment]
That error message isn't produced by curl/libcurl but by the PHP binding (or
your application). We'd be interested if you can reproduce this with the curl
command-line tool, otherwise take it to the PHP/CURL team.

**Comment by iva3682** [comment]
no, when using curl command line, the error is returned correctly. The problem only occurs when using curl in php.
