### ISSUE TITLE
Inconsistent brotli package name in CMake

### ISSUE THREAD

**Issue by aasivov** [curl/curl#4117]
It seems that brotli package name is inconsistent in cmake files.
CMakeLists.txt contains string _find_package(**BROTLI** QUIET)_
but there is a file _CMake/**FindBrotli**.cmake_

It seems that either _CMake/FindBrotli.cmake_ should be renamed to _CMake/FindBROTLI.cmake_ or _find_package(BROTLI QUIET)_ should be replaced with _find_package(Brotli QUIET)_

Otherwise find_package fails to find brotli on Linux machine with the following message:

> By not providing "FindBROTLI.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "BROTLI", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "BROTLI" with any
>   of the following names:
> 
>     BROTLIConfig.cmake
>     brotli-config.cmake
> 
>   Add the installation prefix of "BROTLI" to CMAKE_PREFIX_PATH or set
>   "BROTLI_DIR" to a directory containing one of the above files.  If "BROTLI"
>   provides a separate development package or SDK, be sure it has been
>   installed.
>

**Comment by jay** [comment]
Thanks
