### ISSUE TITLE
curl 7.65.1 crashes dereferencing NULL pointer inside curl_multi_socket_action()

### ISSUE THREAD

**Issue by b-spencer** [curl/curl#4120]
Curl 7.65.1 crashes when dereferencing a NULL pointer to an internal easy handle while processing inside `curl_multi_socket_action()`.  I've observed this in the unit tests for our general use of curl, and was able to easily reproduce it one of the example programs that ships with curl that demonstrates the use of the `curl_multi_socket_action()` API.

After experiencing the crash in real tests and programs, I was able to make the `docs/examples/ephiperfifo.c` program that ships with curl crash in the same way.  The main commonality between my programs and this modified example is their use of `curl_multi_socket_action()` to drive multiple HTTP requests that are issued back-to-back.

I can reproduce the issue on Debian 9 Linux (for example) with the system OpenSSL 1.1 and c-ares packages installed.  I've also reproduced it with custom-built different versions of OpenSSL and c-ares.

```
tar xf curl-7.65.1.tar.gz
cd curl-7.65.1
./configure --with-openssl --enable-ares --disable-shared
make
# Edit ephiperfifo.c so it actually compiles, and make it issue three immediate requests (see below)
gcc -Wall -Wno-unused -o prog docs/examples/ephiperfifo.c -Llib/.libs -lcurl -lcares -lssl -lcrypto -lz -ldl -lpthread
./prog
...
Progress: https://www.example.com/ (0/0)
socket callback: s=6 e=0x55b1b8120880 what=IN Changing action from OUT to IN
REMAINING: 3
Segmentation fault (core dumped)
```

It's useful to use `ldd prog` to confirm that the new version of libcurl.a is really being used:
```
$ ldd prog
        linux-vdso.so.1 (0x00007ffe219f9000)
        libcares.so.2 => /usr/lib/x86_64-linux-gnu/libcares.so.2 (0x00007fdc51365000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fdc510f9000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fdc50c60000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdc50a46000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc50842000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc50625000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc50286000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdc517ec000)
```

The edits I refer to are:
1. Remove [line 343](https://github.com/curl/curl/blob/curl-7_65_1/docs/examples/ephiperfifo.c#L343), which seems to be cruft.
2. On [line 515](https://github.com/curl/curl/blob/curl-7_65_1/docs/examples/ephiperfifo.c#L515), add three calls to `new_conn()` to issue three simultaneous requests to `https://www.example.com/`.

```
  new_conn("https://www.example.com/", &g);
  new_conn("https://www.example.com/", &g);
  new_conn("https://www.example.com/", &g);
```

Doing this ensures they really all start in the same loop spin and avoids timing variations that can happen if you instead feed the URLs in to the named pipe this example makes.  In fact, you can remove the part of this example that creates and processes the named pipe and still see the crash with the above three requests.  There might still be time-sensitive aspects to this test, but it's consistently failed for me.

(BTW, the example's use of _Unused as a user-defined symbol is probably ill-advised since names starting with underscore and a capital letter are [reserved for the language implementation](https://stackoverflow.com/a/228797/693212).)

In the case of both `ephiperfifo.c` and my programs and tests, the crash is in `multi_socket()`, which finds a linked list entry that has an unexpected NULL `Curl_easy`:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555ab57b in multi_socket (multi=0x555555b3a650, checkall=false, s=9, ev_bitmask=2, running_handles=0x7fffffffe298) at curl/curl-7.65.1/lib/multi.c:2514
2514            if(data->conn && !(data->conn->handler->flags & PROTOPT_DIRLOCK))
```
There's even an assert right above that line that clarifies that `data` is never expected to be NULL here.  (Enabling debug and maintainer mode will make this assert fire, but no others that I saw.)

Because the same behaviour happens in this example program and my own very different programs, I don't think this is a peculiarity of the example itself.

I suspect something has gone awry in how the linked list is managed in recent versions.  I have not tracked down the offending change.  My hope is that someone familiar with recent changes might be able to immediately identify the cause.

**Comment by bagder** [comment]
We fixed several of things related to that already so please try current master/7.65.2 and see if the problems remain or not!

**Comment by bagder** [comment]
> the example's use of _Unused as a user-defined symbol is probably ill-advised

What does this refer to?

**Comment by b-spencer** [comment]
> please try current master/7.65.2

Will do.

> > the example's use of _Unused as a user-defined symbol is probably ill-advised
> 
> What does this refer to?

In [line 77 of the example](https://github.com/curl/curl/blob/curl-7_65_1/docs/examples/ephiperfifo.c#L77), it defines the name `_Unused`.  I believe such names are reserved for the implementation.  i.e. A system or toolchain header could define `_Unused` to mean whatever it wants, and the program is not allowed to redefine it, use it, etc.

**Comment by bagder** [comment]
ah, I'll welcome a PR to correct that!

**Comment by b-spencer** [comment]
👍  It looks like 7.65.2 fixed this.

What good luck that the new version seems to have been released between the time I drafted this bug report and the time you responded. :)

> ah, I'll welcome a PR to correct that!

If I can, I will take a look at some of the related examples.

**Comment by bagder** [comment]
> the new version seems to have been released between the time I drafted this bug report and the time you responded

My life is now complete! :grinning:
