### ISSUE TITLE
add the option CURLKHSTAT_FINE_REPLACE_TO_FILE

### ISSUE THREAD

**Issue by mickae1** [curl/curl#4128]
Hi,

In the function specify by CURLOPT_SSH_KEYFUNCTION : 

When the event CURLKHMATCH_MISMATCH is triggered
 I would like to use  CURLKHSTAT_FINE_REPLACE_TO_FILE instead of CURLKHSTAT_FINE_ADD_TO_FILE. 

the option CURLKHSTAT_FINE_REPLACE_TO_FILE would replace the mismatch fingerprint with the new one. instead of added a new one.

Is it possible ?

**Comment by bagder** [comment]
It's just code so it seems entirely possible.

But what would the difference be? can't your application already simply remove the old fingerprint on its own when `CURLKHSTAT_FINE_ADD_TO_FILE` is used?

**Comment by bagder** [comment]
No response and I don't think any action is necessary.
