### ISSUE TITLE
curl built with DarwinSSL doesn't collect server cert

### ISSUE THREAD

**Issue by 0golovatyi** [curl/curl#4130]
### I did this
./buildconfig
./configure --withdarwin-ssl
make
cd docs/examples
make && certinfo

### I expected the following
1 certs!
...some cert data here...

### curl/libcurl version

built from the latest master  (aa73eb47bc8583070734696b25b34ad54c2c1f5e).

### operating system

macOS 10.14.5

**Comment by 0golovatyi** [comment]
The output I see with running `certinfo` is `0 certs!`

**Comment by bagder** [comment]
It isn't supported with the Secure Transport backend. Allow me to quote the [CURLINFO_CERTINFO](https://curl.haxx.se/libcurl/c/CURLINFO_CERTINFO.html) man page:

# AVAILABILITY
This option is only working in libcurl built with OpenSSL, NSS, Schannel or GSKit support. Schannel support added in 7.50.0

**Comment by 0golovatyi** [comment]
@bagder Thank you for the information. 

Is there any other way to collect server cert info in security layer independent way? Seems like now my options are to check CURLINFO_TLS_SSL_PTR, then get a pointer to a backend (openssl, darwinssl, etc.) and use that backend API.

**Comment by bagder** [comment]
Other than write a patch for curl that brings the certinfo feature to the Secure Transport backend, no.
