### ISSUE TITLE
CURLINFO_STARTTRANSFERTIME(_T) returns 0 for POST requests on libcurl versions newer than 7.64.0

### ISSUE THREAD

**Issue by JCMais** [curl/curl#4136]
### I did this

Made a POST request and tried to retrieve the value of `CURLINFO_STARTTRANSFERTIME(_T)`.

### I expected the following

The value returned should be greater than `0`, `CURLINFO_PRETRANSFER_TIME` itself is greater than `0`, so `CURLINFO_STARTTRANSFERTIME` must be too.

It is reproducible with the `curl` binary:
#### libcurl 7.65.3
> curl -d "data data data" -w "lookup:        %{time_namelookup}\nconnect:       %{time_connect}\nappconnect:    %{time_appconnect}\npretransfer:   %{time_pretransfer}\nredirect:      %{time_redirect}\nstarttransfer: %{time_starttransfer}\ntotal:         %{time_total}\n"  "http://requestbin.fullcontact.com/16dxjre1"
```
ok
lookup:        0,009254
connect:       0,035072
appconnect:    0,000000
pretransfer:   0,035231
redirect:      0,000000
starttransfer: 0,000000
total:         0,582735
```

It seems to work with a `GET`:
> curl -w "lookup:        %{time_namelookup}\nconnect:       %{time_connect}\nappconnect:    %{time_appconnect}\npretransfer:   %{time_pretransfer}\nredirect:      %{time_redirect}\nstarttransfer: %{time_starttransfer}\ntotal:         %{time_total}\n"  "http://requestbin.fullcontact.com/16dxjre1"
```
ok
lookup:        0,009284
connect:       0,032880
appconnect:    0,000000
pretransfer:   0,033062
redirect:      0,000000
starttransfer: 0,582286
total:         0,582642
```

The first version that this problem starts happening is `7.64.1`, old libcurl version seems to work:
#### libcurl 7.64.1
```
ok
lookup:        0,034794
connect:       0,056868
appconnect:    0,000000
pretransfer:   0,057023
redirect:      0,000000
starttransfer: 0,000000
total:         0,874881
```

#### libcurl 7.64.0
```
ok
lookup:        0,008550
connect:       0,037006
appconnect:    0,000000
pretransfer:   0,037191
redirect:      0,000000
starttransfer: 0,574312
total:         0,574859
```

### curl/libcurl version
```
curl 7.65.3 (x86_64-pc-win32) libcurl/7.65.3 OpenSSL/1.1.1c (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.1
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz
```

### operating system
Windows 10 x64

This was initially reported here https://github.com/JCMais/node-libcurl/issues/183, so I suspect it's not platform-specific.

**Comment by jay** [comment]
bisected to 65eb65f `urldata: simplify bytecounters` @bagder 

https://github.com/curl/curl/blob/521bbbe29928f9bc1c61306df612e856d45cbe5a/lib/transfer.c#L638-L643

now that writebytecount is part of the request it's no longer 0 here so progress.t_starttransfer is never set

**Comment by JCMais** [comment]
Thanks @jay and @bagder!
