### ISSUE TITLE
error_encoding in Curl_build_unencoding_stack result request failed

### ISSUE THREAD

**Issue by workai** [curl/curl#4146]
curl_multi_info_read return with msg->data.result == CURLE_BAD_CONTENT_ENCODING

Debug info: In first time response Content-Encoding is gzip, but in following responses Content-Encoding are ResponseContentEncoding.

libcurl version curl-7.64.1

operating system win10

**Comment by jay** [comment]
What makes you think this is a curl problem? It sounds like your server is returning the wrong content encoding.

**Comment by workai** [comment]
chrome, curl.exe and even old version libcurl can download file from the
same url sucessfully.

Jay Satiro <notifications@github.com> 于2019年7月25日周四 上午12:39写道：

**Comment by bagder** [comment]
Can you please tell us how we can reproduce this issue?

It sounds to me like this server is sending a bad Content-Encoding type that libcurl reports an error for (and browsers just ignore and pretend it didn't exist)...

**Comment by bagder** [comment]
I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem? We can't act on this bug without more info!

**Comment by workai** [comment]
The file download url is valid for a few minutes, so I can not give it to you for test. But I just not set error_encoding and it looks like running properly.

**Comment by jay** [comment]
Closing, this sounds like user error.
