### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by skysley** [curl/curl#4150]
### I did this
Downloading some random file:
`curl -O --trace-ascii - http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/15268/parallel_studio_xe_2019_update3_cluster_edition.tgz`

or via IP address:
`curl -O --trace-ascii - -H "Host: registrationcenter-download.intel.com" http://23.58.216.6/akdlm/irc_nas/tec/15268/parallel_studio_xe_2019_update3_cluster_edition.tgz`

### I expected the following
I expected the download to start. Using wget, the same URL/IP address will download the file.

### curl/libcurl version

curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
OS: Antergos (Arch Linux)
uname -r: 5.2.2-arch1-1-ARCH

### notes
The specific URL mentioned above is not important. Downloading via AUR (Arch user repo) which is using curl, for instance, does not work in most cases. 

I have no file ~/.curlrc. 

I've already asked about the issue on the mailing list:
https://curl.haxx.se/mail/archive-2019-07/0021.html
https://curl.haxx.se/mail/archive-2019-07/0026.html

Thanks!

**Comment by dfandrich** [comment]
That command works fine for me (although, I didn't wait for the entire download
to complete). What exactly are you seeing?

**Comment by skysley** [comment]
When I run
```
curl -O  http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/15268/parallel_studio_xe_2019_update3_cluster_edition.tgz
```
I see this output (with time "Time Spent" counting up):

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:14:26 --:--:--     0
```
With option `--trace` it get this output file:

```
== Info: STATE: INIT => CONNECT handle 0x559b990db8a8; line 1356 (connection #-5000)
== Info: Added connection 0. The cache now contains 1 members
== Info: STATE: CONNECT => WAITRESOLVE handle 0x559b990db8a8; line 1397 (connection #0)
== Info:   Trying 23.58.216.6:80...
== Info: TCP_NODELAY set
== Info: STATE: WAITRESOLVE => WAITCONNECT handle 0x559b990db8a8; line 1476 (connection #0)
== Info: Connected to registrationcenter-download.intel.com (23.58.216.6) port 80 (#0)
== Info: STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x559b990db8a8; line 1530 (connection #0)
== Info: Marked for [keep alive]: HTTP default
== Info: STATE: SENDPROTOCONNECT => DO handle 0x559b990db8a8; line 1550 (connection #0)
=> Send header, 176 bytes (0xb0)
0000: 47 45 54 20 2f 61 6b 64 6c 6d 2f 69 72 63 5f 6e GET /akdlm/irc_n
0010: 61 73 2f 74 65 63 2f 31 35 32 36 38 2f 70 61 72 as/tec/15268/par
0020: 61 6c 6c 65 6c 5f 73 74 75 64 69 6f 5f 78 65 5f allel_studio_xe_
0030: 32 30 31 39 5f 75 70 64 61 74 65 33 5f 63 6c 75 2019_update3_clu
0040: 73 74 65 72 5f 65 64 69 74 69 6f 6e 2e 74 67 7a ster_edition.tgz
0050: 20 48 54 54 50 2f 31 2e 31 0d 0a 48 6f 73 74 3a  HTTP/1.1..Host:
0060: 20 72 65 67 69 73 74 72 61 74 69 6f 6e 63 65 6e  registrationcen
0070: 74 65 72 2d 64 6f 77 6e 6c 6f 61 64 2e 69 6e 74 ter-download.int
0080: 65 6c 2e 63 6f 6d 0d 0a 55 73 65 72 2d 41 67 65 el.com..User-Age
0090: 6e 74 3a 20 63 75 72 6c 2f 37 2e 36 35 2e 33 0d nt: curl/7.65.3.
00a0: 0a 41 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a .Accept: */*....
```

**Comment by skysley** [comment]
Same result if I compile curl from source.
```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli Debug HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP TrackMemory UnixSockets
```
[config.log](https://github.com/curl/curl/files/3430377/config.log)

**Comment by dfandrich** [comment]
It sounds like there may be a proxy or firewall in the way that's interfering.
Try the same command on a different network and different machine to see if that's the case.

**Comment by skysley** [comment]
From within this network here, it is not working on any machine. From another network it seems to be working.
Strange that it works with wget from within this network.

**Comment by bagder** [comment]
> with time "Time Spent" counting up

It means curl has the connection setup, it issued the request and is then waiting for the server to send the data. It seems highly unlikely that this issue is actually due to curl - and the rest of the details and stories in this issue seem to corroborate that.

**Comment by skysley** [comment]
I figured it out. Something seems to block HTTP traffic where the user agent is set to curl.

This one does not work:
```
curl -O  -H "Host: registrationcenter-download.intel.com" http://23.58.216.6/akdlm/irc_nas/tec/15268/parallel_studio_xe_2019_update3_cluster_edition.tgz
```
But this one does:
```
curl -O --user-agent "lionking/0.0" -H "Host: registrationcenter-download.intel.com" http://23.58.216.6/akdlm/irc_nas/tec/15268/parallel_studio_xe_2019_update3_cluster_edition.tgz
```
According to my tests it seems like that anything is blocked as long as the user agent is of the form "curl/<something>" (--> "foo/curl" works).

So the problem is actually not on curl's side.
