### ISSUE TITLE
schannel should not ignore windows trusted certs when CURLOPT_CAINFO is set

### ISSUE THREAD

**Issue by jeroen** [curl/curl#4156]
After upgrading libcurl 7.59.0 -> 7.64.1 we start to get [bug reports](https://github.com/jeroen/curl/issues/193) from corporate Windows users that their corporate certs are no longer working. The R bindings are configured to use schannel on Windows.

The problem is that some 3rd party R packages are setting `CURLOPT_CAINFO` to some known cert bundle. They do this in case the user is running a statically linked curl-openssl. Previously, `CURLOPT_CAINFO` was ignored if the user runs `curl-schannel`, hence connections would work as expected on corporate networks with windows certs.

However as of https://github.com/curl/curl/pull/1325 libcurl schannel will treat the CA certs set by `CURLOPT_CAINFO` and ignore the trusted certs from the windows. The latter is causing problem for corporate networks that store their root certs in the Windows store. 

What makes it extra bad is that due to https://github.com/curl/curl/issues/3711 the certs in the bundle aren't working properly we don't support AltNames when targeting Windows 7, which is what mingw-w64 targets by default.

What is needed is an option (or default) to make schannel use root certs in `CURLOPT_CAINFO` __in addition to windows root certs__. If that for whatever reason is impossible, I would need a configure option to completely disable `CURL_CA_BUNDLE` icw/ the schannel backend.

**Comment by jay** [comment]
If you set a certificate bundle then that is what curl will use, if it is supported. However I don't recall how other backends behave in regards to this problem. In the curl tool we don't set the bundle if schannel is the backend:

https://github.com/curl/curl/blob/aa73eb47bc8583070734696b25b34ad54c2c1f5e/src/tool_operate.c#L249-L270

Regarding #3711 you're right that's an issue I've just focused on other things.

/cc @king2bob

**Comment by jeroen** [comment]
@jay thanks. As a short-term solution, could you help me suggesting a local patch or build flag that I can use to build a version of libcurl that ignores `cainfo` icw/ schannel as it did previously? 

I'm getting bug reports from R users where https no longer works due to 3rd party code that sets `cainfo` unconditionally. This is fine for curl+openssl configurations, but on Windows this results in a [mostly non-working SSL](https://github.com/curl/curl/issues/3711#issuecomment-477878906).

Of course I understand implementing schannel AltNames is not easy to implement quickly, but I much prefer to disable it completely when targeting Win7, and just fall back on the old behavior that users the Windows native cert validation.

**Comment by jay** [comment]
You can unset CURLOPT_CAINFO set by the user by setting it to NULL afterwards. Otherwise if the user has set a certificate bundle using CURLOPT_CAINFO then that bundle is used for manual validation, if such API is available. If it is not available then the use of CURLOPT_CAINFO will cause an error. The only way to really change that behavior is to modify libcurl.

https://github.com/curl/curl/blob/aa73eb47bc8583070734696b25b34ad54c2c1f5e/lib/vtls/schannel.c#L473-L492

**Comment by jeroen** [comment]
So if I would patch the above snipped in my build such that `if(SSL_CONN_CONFIG(CAfile))` is changed into `if(0)` then `CURLOPT_CAINFO` is ignored for schannel (as it was before) and curl will always use the windows cert store to validate certs?

**Comment by jay** [comment]
> Does that sound correct?

Yes that is the way it is written now but there's no guarantee we'll keep it that way. I think a better way is ignore CURLOPT_CAINFO in your binding until #3711 is addressed.

**Comment by jeroen** [comment]
> Yes that is the way it is written now but there's no guarantee we'll keep it that way. I think a better way is ignore CURLOPT_CAINFO in your binding until #3711 is addressed.

I can't ignore it unconditionally, because the option should still work for users that have a libcurl that was built with openssl. On Linux systems, the bindings are compiled against whatever libcurl ships on that system so I need to make sure I only ignore it for schannel configurations.

I built a version of libcurl-schannel with the patch above and it seems to avoid the problem. So this fixes it for me right now. I'll disable cainfo icw/ schannel until either https://github.com/curl/curl/issues/3711 is fixed or mingw-w64 starts targeting Windows 8.1.
