### ISSUE TITLE
AUTH NTLM for SMTP will be crash

### ISSUE THREAD

**Issue by OUC-MYM** [curl/curl#4164]
I use libcurl/7.29.0 NSS/3.15.4.
When I tried to send smtp mail in AUTH NTLM mode, the program crashed.

```
(gdb) bt
#0  0x00007ffff58ee32f in PK11_DigestOp () from /lib64/libnss3.so
#1  0x00007ffff727a86a in Curl_nss_md5sum () from /lib64/libcurl.so.4
#2  0x00007ffff7286659 in Curl_ntlm_create_type3_message () from /lib64/libcurl.so.4
#3  0x00007ffff72805ec in smtp_statemach_act () from /lib64/libcurl.so.4
#4  0x00007ffff727f33e in smtp_multi_statemach () from /lib64/libcurl.so.4
#5  0x00007ffff726a938 in multi_runsingle () from /lib64/libcurl.so.4
#6  0x00007ffff726b811 in curl_multi_perform () from /lib64/libcurl.so.4
#7  0x00007ffff7262bd3 in curl_easy_perform () from /lib64/libcurl.so.4
```

I read the code and guessed that the PK11_CreateDigestContext function returned a null pointer.
https://github.com/curl/curl/blob/a2ab576768442f669040837c7f0667e672cf7d48/lib/vtls/nss.c#L2368

**Comment by bagder** [comment]
libcurl 7.29.0 was released in early 2013. If you can reproduce this problem with a modern libcurl version we will be very interested in learning how, until then this is just a curiosity and most likely a bug we already fixed...

**Comment by bagder** [comment]
No response and ancient curl version, closing.
