### ISSUE TITLE
Windows: no_proxy environment variable ignored when longer than (258) chars

### ISSUE THREAD

**Issue by myfonj** [curl/curl#4174]
### I did this

`no_proxy` (user) environment variable on my machine is 966 characters long [1] and  `http_proxy` and `https_proxy` variables set. I've observed that as long as I keep `no_proxy` length above 258 characters, cURL requests are always passed to proxy on my system.

 <details><summary>cURL calls with 258 and 259 characters long `no_proxy` environment variable in my CMD:</summary>

```
C:\apps\cmd>set no_proxy=localhost,127.0.0.*,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

C:\apps\cmd>curl --location --head http://localhost/
HTTP/1.1 200 OK
Date: Tue, 30 Jul 2019 15:46:25 GMT
Server: Apache/2.4.37 (Win64) PHP/7.3.3
Last-Modified: Thu, 18 Jul 2019 15:02:45 GMT
ETag: "2000-58df5e7002ac0"
X-Clacks-Overhead: GNU Terry Pratchett
Content-Type: text/html;charset=UTF-8

C:\apps\cmd>set no_proxy=localhost,127.0.0.*,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

C:\apps\cmd>curl --location --head http://localhost/
HTTP/1.1 503 Service Unavailable
Server: squid/(...)
(...)
```

</details>

### I expected

Both cURL calls had the same outcome.

### `curl -V`

<details><summary>7.65.3</summary>

```
curl 7.65.3 (x86_64-pc-win32) libcurl/7.65.3 OpenSSL/1.1.1c (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.1
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz
```
</details>

### Operating system

Windows 10, 10.0.16299, build 1709

### Notes

System settings GUI for (user) environment variable allows 2047 characters on my system.

---

[1] don't ask why; just copied what was in the Network settings GUI (inetcpl.cpl) in Exceptions field, replaced semicolons and added it to my CMDer user_profile.cmd script an/or User Environment Variables settings panel as `no_proxy` entry.

**Comment by bagder** [comment]
Oh... and here's the explanation:

https://github.com/curl/curl/blob/cb46b193f18d67c92fc30e91171719ecbf666816/lib/getenv.c#L38

We should expand that array quite a bit...
