### ISSUE TITLE
Build of cURL 7.65.3 fails on Red Hat 6

### ISSUE THREAD

**Issue by lanceeware** [curl/curl#4176]
Attempting build of cURL 7.65.3 on Red Hat Enterprise Linux 6 machine fails with following messages:

>   ...
  CC       curl-tool_helpers.o
  CC       curl-tool_homedir.o
  HUGE     tool_hugehelp.c
  CC       curl-tool_hugehelp.o
tool_hugehelp.c:8330:6: error: redefinition of ‘hugehelp’
 void hugehelp(void)
      ^
tool_hugehelp.c:8:6: note: previous definition of ‘hugehelp’ was here
 void hugehelp(void)
      ^
make[3]: *** [curl-tool_hugehelp.o] Error 1
make[3]: Leaving directory '/home/builder/lware/RDVAS-2027/curl_new/src-static/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/builder/lware/RDVAS-2027/curl_new/src-static/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/builder/lware/RDVAS-2027/curl_new/src-static'
make: *** [libcurl] Error 2

After some investigation I found that this line in src/Makefile.in is the culprit:

`@HAVE_LIBZ_FALSE@@USE_MANUAL_TRUE@	$(HUGECMD)(echo '#include "tool_setup.h"' > $(HUGE):    \`

The colon near the end of the line causes it to create a file named "tool_hugehelp.c:", which is not what is intended. Changing the colon character to a semicolon fixes the problem:

`@HAVE_LIBZ_FALSE@@USE_MANUAL_TRUE@	$(HUGECMD)(echo '#include "tool_setup.h"' > $(HUGE);    \`

**Comment by bagder** [comment]
Ack, seems accurate. And you trigger this because you build without libz present, which clearly is pretty unusual since this regression was done in 5cf5d57ab9 (7.64.1) on March 14 2019...

I'll push a pull request for this in a minute.
