### ISSUE TITLE
Linker error when building against a static libcurl built against macOS SSL implementation

### ISSUE THREAD

**Issue by Adnn** [curl/curl#4178]
We are using a static build of libcurl for macOS, using the system SSL implementation. We are trying to update to latest stable (7.65.3).

Our build recipe relies on CMake, with the following definitions:

* CMAKE_USE_OPENSSL=False
* CMAKE_USE_SECTRANSP=True
* CURL_CA_PATH="none"
* CURL_CA_BUNDLE="none"
* CURL_STATIC_LIB=1
* BUILD_TESTING=False
* BUILD_CURL_EXE=False

The static library builds successfuly

Yet, we cannot build a minimal application linking against this library, because of linker errors:

> Undefined symbols for architecture x86_64:
>   "_SSLCopyALPNProtocols", referenced from:
>       _sectransp_connect_step2 in libcurl.a(sectransp.c.o)
>   "_SSLSetALPNProtocols", referenced from:
>       _sectransp_connect_common in libcurl.a(sectransp.c.o)

We saw #2835, yet we are at the latest non-beta macOS (10.14.6), and this issue is still occuring for us.

## Our minimal client

CMakeLists.txt

```
cmake_minimum_required(VERSION 2.8.12)
project(PackageTest CXX)

find_package(CURL CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example PRIVATE CURL::libcurl)
```

example.cpp

```
#include <curl/curl.h>

int main() 
{
    CURL *curl = curl_easy_init();
    curl_easy_cleanup(curl);
}
```

**Comment by bagder** [comment]
According to Apple docs, they're [deprecated](https://developer.apple.com/documentation/security/2867327-sslsetalpnprotocols?language=objc) but we've not seen anyone else having problems with them...

Any clues here @nickzman?

**Comment by nickzman** [comment]
@Adnn, this can happen if you built libcurl with the macOS 10.13 or later SDK, and targeted a later macOS deployment target than your app or framework targets. If you don't set a deployment target, then the SDK is the deployment target. The ALPN symbols were introduced in macOS 10.13.4; if you build libcurl to target an earlier macOS version, then those symbols will be marked for weak linking. So just rebuild libcurl with the desired macOS target set (by putting "-mmacosx-version-min=${VERSION}" in your CFLAGS prior to running configure), and that ought to fix it.

@bagder, all of Secure Transport has been deprecated by Apple in favor of BoringSSL. Yes, Apple has come full circle with their security back-end. The catch is, they don't publish the BoringSSL headers, and want everyone to use it indirectly via their new Networking framework.

**Comment by Adnn** [comment]
@nickzman Thank you for your response. Nevertheless, I am building libcurl and  the minimal example app by targeting the same  deployment target (I don't set one explicitly for both, so, targetting the current SDK).

From your answer, it seems that this should work for our dev system, which is 10.14.6?

**Comment by nickzman** [comment]
It works on 10.14.x. If the deployment target is the same, did you also link the code against the Security and CoreFoundation frameworks? That is required, and not done automatically.

**Comment by Adnn** [comment]
@nickzman Thank you for the further precision. It appears the problem was not the macOS version, but the Xcode version.

Provisioning a VM with macOS 10.14.6 and Xcode 10.3, you are right the minimal example above compiled as expected.
With the same OS version, but Xcode 9.2, the example fails as described in the top post. I think 9.2 only comes with the 10.13 SDK, which might explain the situation.

---

As a related note, when using the `CURL::libcurl` imported target provided by `find_package(CURL CONFIG REQUIRED)`, we do **not** need to explicitly link the code against  any extra macOS framework (that might be done.
They are already provided by CURLTargets.cmake.

**Comment by bagder** [comment]
I guess this issue can be closed then?

**Comment by bagder** [comment]
It seems to have been fixed by upgrading Xcode.
