### ISSUE TITLE
callbacks invoked after curl_easy_perform returned

### ISSUE THREAD

**Issue by 0x002A** [curl/curl#4202]
curl/libcurl version: 7.58.0
running on ubuntu 18.04.2 lts

### Code
```c
CURL *curl = curl_easy_init();
if(curl) {
  CURLcode res;
  curl_easy_setopt(curl, CURLOPT_URL, "http://example.com");
  curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
  curl_easy_setopt(curl, CURLOPT_WRITEDATA, &write_data); 
  curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_callback); 
  curl_easy_setopt(curl, CURLOPT_HEADERDATA, &header_data); 
  res = curl_easy_perform(curl);
  curl_easy_cleanup(curl);
}
```
### Expected behavior
As the documentation states:

> curl_easy_perform performs the entire request in a blocking manner and returns when done, or if it failed.

I expect that all callbacks are made until _curl_easy_perform_ returns. This seems to be the case for _CURLOPT_WRITEFUNCTION_. _CURLOPT_HEADERFUNCTION_ on the other side seems to get called even after _curl_easy_perform_ returned.

Is this is wanted/expected behavior?

**Comment by falconindy** [comment]
Could you provide a working example of the header callback being invoked between curl_easy_perform and curl_easy_cleanup?

**Comment by dfandrich** [comment]
Once curl_easy_perform returns, there is no longer any libcurl code running and
so it's impossible for it to call any further callback functions.

**Comment by bagder** [comment]
No response, closing.
