### ISSUE TITLE
crash in Curl_llist_insert_next

### ISSUE THREAD

**Issue by yzpgryx** [curl/curl#4205]
### curl/libcurl version
7.51
[curl -V output]

### operating system
Android

Stack: 
pid: 662, tid: 1923, name: GNetDoCurl_4  >>> UNKNOWN <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
    r0 9a40f450  r1 ffffffff  r2 00000000  r3 00000000
    r4 a234a850  r5 00000000  r6 9a40f260  r7 964ff588
    r8 00000014  r9 a234a850  sl 9a40f260  fp 95eeb2e0
    ip 95ea3018  sp 964ff578  lr 00000018  pc a015ab52  cpsr 600f0030
stack:
         964ff538  00000000  00000000  
         964ff53c  00000000  00000000  
         964ff540  00000000  00000000  
         964ff544  6fe6f78d  0014178d  /data/dalvik-cache/arm/system@framework@boot.oat
         964ff548  3f800000  00000000  
         964ff54c  00000000  00000000  
         964ff550  95ea3000  00063000  [anon:libc_malloc]
         964ff554  a234a850  0000a850  [anon:libc_malloc]
         964ff558  00000000  00000000  
         964ff55c  9a40f260  0008f260  [anon:libc_malloc]
         964ff560  964ff588  000fd588  
         964ff564  00000014  00000000  
         964ff568  a234a850  0000a850  [anon:libc_malloc]
         964ff56c  9a40f260  0008f260  [anon:libc_malloc]
         964ff570  95eeb2e0  000ab2e0  [anon:libc_malloc]
         964ff574  a015ab15  0001ab15  /system/lib/libcurl.so (Curl_llist_insert_next+24)
    #00  964ff578  964ff5a0  000fd5a0  
         964ff57c  95e823c0  000423c0  [anon:libc_malloc]
         964ff580  9e6be294  0007e294  [anon:libc_malloc]
         964ff584  9a40f230  0008f230  [anon:libc_malloc]
         964ff588  964ff5a0  000fd5a0  
         964ff58c  a01558cd  000158cd  /system/lib/libcurl.so (Curl_hash_add+144)
    #01  964ff590  9a40f230  0008f230  [anon:libc_malloc]
         964ff594  95eeb2e0  000ab2e0  [anon:libc_malloc]
         964ff598  9a40f234  0008f234  [anon:libc_malloc]
         964ff59c  9a40f230  0008f230  [anon:libc_malloc]
         964ff5a0  964ff5c4  000fd5c4  
         964ff5a4  00000013  00000000  
         964ff5a8  95e4c000  0000c000  [anon:libc_malloc]
         964ff5ac  00000001  00000000  
         964ff5b0  00000000  00000000  
         964ff5b4  a0155ff3  00015ff3  /system/lib/libcurl.so (Curl_cache_addr+90)
    #02  964ff5b8  96002500  001c2500  [anon:libc_malloc]
         964ff5bc  95eeb300  000ab300  [anon:libc_malloc]
         964ff5c0  00000000  00000000  
         964ff5c4  964ff5e4  000fd5e4  
         964ff5c8  95e4c000  0000c000  [anon:libc_malloc]
         964ff5cc  95e4c000  0000c000  [anon:libc_malloc]
         964ff5d0  964ff68c  000fd68c  
         964ff5d4  a0155ccd  00015ccd  /system/lib/libcurl.so (Curl_addrinfo_callback+56)
    #03  964ff5d8  96002500  001c2500  [anon:libc_malloc]
         964ff5dc  9a40f220  0008f220  [anon:libc_malloc]
         964ff5e0  00000000  00000000  
         964ff5e4  964ff5fc  000fd5fc  
         964ff5e8  960028a0  001c28a0  [anon:libc_malloc]
         964ff5ec  a014afdb  0000afdb  /system/lib/libcurl.so (Curl_resolver_is_resolved+70)
    #04  964ff5f0  96002500  001c2500  [anon:libc_malloc]
         964ff5f4  9a3ea380  0006a380  [anon:libc_malloc]
         964ff5f8  95ee4680  000a4680  [anon:libc_malloc]
         964ff5fc  964ff6a0  000fd6a0

**Comment by bagder** [comment]
1. Please provide a stand-alone example program that can reproduce the problem. This stack trace is far from enough for us to act on.
2. *Usually* (at almost a 100% hit-rate) when we get crash reports on the linked list functions, this happened because the user didn't follow the [libcurl thread-safety rules](https://curl.haxx.se/libcurl/c/threadsafe.html). Please double-check that.
3. This is a fairly old curl version, I'd suggest an upgrade

**Comment by yzpgryx** [comment]
Thanks for the quick reply， I got the stack from my customer, so , I don't have a sample code that can reproduce the problem.

Thans for you advice,  "libcurl thread-safety rules", I'll read and check it.
Thanks you verfy much. 
I think this issue should be closed, I have no more information to offer about it, Sorry.
