### ISSUE TITLE
Unable to authenticate with SPNEGO/Kerberos

### ISSUE THREAD

**Issue by ManzoniMatteo** [curl/curl#4218]
### I did this
Try to authenticate with SPNEGO/Kerberos to a Microsoft certification authority web interface but I got 401 access denied.
With a proxy (burp suite in my case) it works, with an older version of curl it works.
### I expected the following
Successful authentication
#### Current version
curl 7.65.3 (x86_64-redhat-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c-fips zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.38.0
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

#### Older compiled and working version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.1.1c
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL TLS-SRP UnixSockets HTTPS-proxy

### operating system
Fedora 30

**Comment by ManzoniMatteo** [comment]
A little update, I compiled from source curl 7.65.3 without nghttp2 and now it's working again.
The upstream version of nghttp2 in Fedora's repositories is 1.38.0

**Comment by bagder** [comment]
nghttp2 really has nothing at all to do with SPNEGO/Kerberos, so it doesn't seem like a very plausible reason...

**Comment by ManzoniMatteo** [comment]
After a night of trial and error I found the real issue, Microsoft.
IIS doesn't support Kerberos over HTTP/2 but also fails to fall back to HTTP/1.1
