### ISSUE TITLE
Username and password in URL no longer works when using digest authentication through a proxy

### ISSUE THREAD

**Issue by mikecrowe** [curl/curl#4228]
Ever since 46e164069d1a5230e4e64cbd2ff46c46cce056bb, it appears that attempts to use a username and password as part of an HTTP URL whilst communicating via a proxy fails. libcurl does not send an Authorization header.

Steps to reproduce:

 curl --proxy http://proxy:3128/ --digest http://unittest:password@host/

Originally raised in the thread at https://curl.haxx.se/mail/lib-2019-08/0002.html

Test case added in https://github.com/mikecrowe/curl/tree/mac/authentication-in-url-with-proxy-bug

**Comment by bagder** [comment]
[test335](https://github.com/curl/curl/files/3506144/test335.txt) from Mike's repo

**Comment by mikecrowe** [comment]
That fix works perfectly. Thanks!

**Comment by bagder** [comment]
Thanks for confirming!
