### ISSUE TITLE
SSL_ERROR_SYSCALL failure on docker if https_proxy has https:// prefix.

### ISSUE THREAD

**Issue by SoftwareApe** [curl/curl#4232]
### I did this
Tried to do:
`curl https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list`

with
`export https_proxy=https://docker.for.win.localhost:3128`

And got this:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to docker.for.win.localhost:3128`

### I expected the following
```
# os-specific listings first
yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml osx

# generic
yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
gbpdistro https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml fuerte

# newer distributions (Groovy, Hydro, ...) must not be listed anymore, they are being fetched from the rosdistro index.yaml instead
```

However this only worked with:
`export https_proxy=docker.for.win.localhost:3128`

On the other hand `wget` works with both.

### curl/libcurl version
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system
Ubuntu 18.04 (on Docker).

**Comment by SoftwareApe** [comment]
I'm guessing this is a simple check: if the URL starts with [a-z]+:// don't prepend it.

**Comment by bagder** [comment]
When you tell curl the proxy is prefxed with `https://`, it means this is a HTTPS proxy, not a HTTP proxy.

Setting `https_proxy` to a host name tells curl to use a HTTP proxy for its HTTPS connections.

They're not the same thing.

**Comment by SoftwareApe** [comment]
It's a https website and the https_proxy that works with other programs. I don't quite understand, why curl should be a special case?

Especially this I don't understand:
>Setting https_proxy to a host name tells curl to use a HTTP proxy for its HTTPS connections.

So if I have a https proxy curl believes it _shouldn't_ use https? That doesn't seem very obvious.

**Comment by bagder** [comment]
There are HTTP proxies and there are HTTPS proxies. Both kinds can proxy both HTTP and HTTPS.

You seem to be using a HTTP proxy. Therefore, you should not tell curl that the proxy is a HTTPS proxy.

**Comment by SoftwareApe** [comment]
Ah thank you, that explains it. Now I only have the issue that some other applications complain if https_proxy isn't https://, but I guess it isn't CURL's fault then.

**Comment by bagder** [comment]
I would claim that's wrong on their behalf. `https_proxy` was always historically a way to set the proxy for HTTPS transfers. (it was a hostname originally and not a URL)

Insisting that the proxy name starts with HTTPS:// if it isn't indeed using a HTTPS proxy seems like a mistake.
