### ISSUE TITLE
CURL_CA_FALLBACK should define to 

### ISSUE THREAD

**Issue by davebenson** [curl/curl#4251]
Without this, it appears that all callers will have to supply a CA dir or file.  Which is highly unexpected for casual users, and the ultimate fix is far removed from the immediately reported error.

afaict from acinclude.m4, the default build sets this ON by default for OPENSSL and GNUTLS (the main vendors).

**Comment by davebenson** [comment]
To be clear the change is (in CMakeLists.txt):

**Comment by bagder** [comment]
> Without this, it appears that all callers will have to supply a CA dir or file

Not exactly. The default behavior is for configure to find and set a default CA path. We can only use `CURL_CA_FALLBACK` if the TLS backend supports that and we those two mention backends are the only ones so far. Just setting the define in the build for another backend will not be enough for you!

**Comment by davebenson** [comment]
I see... so basically we have to replicate that logic in cmake...  It doesn't really seem appropriate for applications to be dealing with this stuff, but i guess curl isn't the average app.

Actually, i'm having trouble finding this code to look at it... i've checked acinclude.m4 and configure.ac ... where is the ca-dir guessing?

**Comment by dfandrich** [comment]
It's in the CURL_CHECK_CA_BUNDLE macro in acinclude.m4.

**Comment by bagder** [comment]
>  It doesn't really seem appropriate for applications to be dealing with this stuff

That's why we setup a default CA path in configure so that the library sets something sensible without the application needing to know or care too much. That's how libcurl ships in all Linux distros and BSDs etc.

> where is the ca-dir guessing?

The configure function starts here: https://github.com/curl/curl/blob/master/acinclude.m4#L2159

The cmake logic for the same check is here: https://github.com/curl/curl/blob/master/CMakeLists.txt#L683-L698

**Comment by davebenson** [comment]
OK, well, in a standalone test those do indeed find the file and the whole library works.  [they find the same file as the autotools version-- my system openssl appears to use the cert directory instead, hmm]  But it isn't finding it when including curl as part of a "superbuild".

so this is probably user-error (and can be closed at maintainers' discretion).  But it might be nice to warn to user in VERBOSE if there's no cacert dir or file.

**Comment by bagder** [comment]
> But it isn't finding it when including curl as part of a "superbuild".

That sounds more like a bug in your superbuild then?

> it might be nice to warn to user in VERBOSE if there's no cacert dir or file.

I disagree as that's the comment setup on some systems. I would rather suggest configure could warn if it didn't find it.

**Comment by bagder** [comment]
The conclusion I draw thus far is that this is not a bug in curl...

**Comment by davebenson** [comment]
I agree... although it cost me a while diagnosing it, and i'm not sure
there's any notable harm in using CURL_CA_FALLBACK.  Feel free to close,
since my needs are addressed.
