### ISSUE TITLE
macro name is a reserved identifier

### ISSUE THREAD

**Issue by patnyb** [curl/curl#4254]
https://github.com/curl/curl/issues/148
"This is not a problem in the real world though."

Well now for me it is - is this possible to fix or do I have to manually fix it each time (curl is used in a number of projects and I don't wanna turn this flag off)?

curl: 7.62.0
compiler: embarcadero c++-builder 10.3.2/clang (5?) c++17

flags: -Weverything -Werror et al

error E2300: macro name is a reserved identifier:

include\curl\curl.h(2,9)
include\curl\curlver.h(2,9)
include\curl\system.h(2,9)
include\curl\system.h(484,13)
include\curl\system.h(488,11)
include\curl\easy.h(2,9)
include\curl\multi.h(2,9)
include\curl\urlapi.h(2,9)

https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier
"Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use."

**Comment by jzakrzewski** [comment]
The same comment in #148 also states:
"If someone brings a patch for it then I'll merge"

So just do it once and send a pull request!

**Comment by bagder** [comment]
I still stand by that comment. The defines are harmless and won't cause anyone any troubles, but if go ahead and fix them and I'll accept the PR.

**Comment by bagder** [comment]
BTW, clang's -Weverything option warns on totally fine things as well as some misguided attempt to be "helpful" which makes the option less useful to use when building curl and I'll advice against it.

Things like that it pads structs or finds "unknown command tag name" (email addresses) in comments.

**Comment by patnyb** [comment]
> The defines are harmless and won't cause anyone any troubles

Obviously they are causing _me_ trouble so "almost anyone" ...


> .. when building curl ...

This is happening when compiling projects including curl ...

**Comment by bagder** [comment]
They trigger warnings with that clang option enabled, does it cause any other (real) harm?

**Comment by bagder** [comment]
Here's how to identify most of them:

    find . -name "*.[ch]" | xargs grep '#define *_'

**Comment by patnyb** [comment]
> 
> 
> They trigger warnings with that clang option enabled, does it cause any other (real) harm?

[In my case warnings=errors] Apart from being non standard compliant, of course not.

I'll try to upgrade to the latest version of curl next week and fix a patch.

**Comment by bagder** [comment]
The combination of those flags causes this build problem but without -Weverything, -Werror is fine and we use it as a standard in our builds.

**Comment by patnyb** [comment]
> 
> 
> The same comment in #148 also states:
> "If someone brings a patch for it then I'll merge"
> 
> So just do it once and send a pull request!

Well elfring did it seems.

**Comment by bagder** [comment]
I never saw a PR for this

**Comment by bagder** [comment]
@patnyb does #4255 fix the issues for you?

**Comment by patnyb** [comment]
> @patnyb does #4255 fix the issues for you?

Yes - all curl-related warnings are gone - thanks alot! :)
