### ISSUE TITLE
What happens if TLS SRP and TLS 1.3 are used together?

### ISSUE THREAD

**Issue by sayrer** [curl/curl#4262]
From <https://tools.ietf.org/html/draft-barnes-tls-pake-04>:

"In prior versions of TLS, this functionality has been provided by the integration of the Secure Remote Password PAKE protocol (SRP) [RFC5054].  The specific SRP integration described in RFC 5054 does not immediately extend to TLS 1.3 because it relies on the Client Key Exchange and Server Key Exchange messages, which no longer exist in 1.3."

It doesn't seem like this combination will work. I guess maybe some docs should be added.

**Comment by bagder** [comment]
Sounds like a good idea, but this is the first I learn about this so I could use some help on what to say...
