### ISSUE TITLE
allow CURLOPT_DOH_URL accept http://127.0.0.1  

### ISSUE THREAD

**Issue by patrickkh7788** [curl/curl#4284]
like chrome accept localhost worker thread,  localhost dow service should be able work without https to improve speed.

**Comment by bagder** [comment]
I don't think `CURMOPT_DOH_URL` belongs in the multi handle. It is still related to the specific transfer and thus the easy handle.

**Comment by patrickkh7788** [comment]
It not  belongs in the multi handle in the API.  I think maybe DNS cache is shared for multi easy handle,  make it   belongs in the multi handle could reduce the need to call it for each easy handle.

**Comment by bagder** [comment]
1. That's still an option that is per-transfer and thus it will remain set per easy handle.

2. As for allowing `http://`, the RFC states **This protocol MUST be used with the https URI scheme** and the very name of the protocol says HTTPS. I don't think going away from that it is a good idea.

**Comment by patrickkh7788** [comment]
If so,  can we add DNS callback function pointer to allow custom DNS ?

`DNS callback function pointer`:  allow CURL send a DNS request to env(It can work on async or sync mode)

And a new api to allow user notify CURL handle DNS resolve results. 

Because the user can not prepare every domain name from `CURLOPT_RESOLVE` ( redirect, alt-svc), we need a solution to allow user resolve domain on request.

**Comment by bagder** [comment]
> can we add DNS callback function pointer to allow custom DNS ?

Sure!

It has been attempted before and I would be all for it. Just be aware that in order to provide a *good* custom name resolving backend, it might need a level of flexibility that makes this idea larger than just an afternoon's work to provide in a good way. And we of course need test cases and documentation...

**Comment by bagder** [comment]
I don't think this is a good idea as explained above. Closing.
