### ISSUE TITLE
CA List Used By Curl

### ISSUE THREAD

**Issue by pschaeffer** [curl/curl#4285]
Mr. Stenberg,

I am not sure if this is really a bug, an issue, or whatever. Someone tried to use Curl to access a website and got error 60. The same website (and URL) work fine with Firefox and Chrome. Some research revealed why. Curl uses a certificate list with 140 entries (currently). The Curl “trust” list does not include.

Go Daddy Secure Certificate Authority - G2

By contrast, the Firefox, Chrome, Edge (etc.) certificate lists do include (and “trust”)

Go Daddy Secure Certificate Authority - G2

I built a certificate file from all of the entities “trusted” by Firefox. I has 223 entries. It is attached. 

Using this certificate file, Curl is able to establish an https connection to the target system. In other words, standard Curl fails. However, issuing Curl (really curl) with the –cacert option (pointing to the file derived from the Firefox certificates) works.

This raises an important question. Should curl “trust” the same entities as Firefox and/or Chrome? A related point is that the error message does not it clear that Curl is missing a certificate to verify the target system. Most folks think that error message means that Curl can not find the certificate file at all.

Thank you

Peter Schaeffer

P.S. The attached file is not really a log file at all. It is a PEM file. However, GitHub has problems witb PEM files.

[combinedcacerts.log](https://github.com/curl/curl/files/3562857/combinedcacerts.log)

**Comment by bagder** [comment]
We, as in the curl project, doesn't ship the CA store you or your users use. curl uses the given CA store and it is up to users to make sure it is updated and correct and contain the certs that should be trusted. Most distros and operating systems that ship curl make sure to also offer an updated CA store for this purpose.

The particular file you refer to may be old, it might be provided by someone who removed some certs, or something else.

This is not a curl bug.

We offer [Mozilla's list of CA certs in PEM format](https://curl.haxx.se/docs/caextract.html), but that's just a service we provide. If you use that or not is up to you. The latest one contains two Go Daddy certificates:
~~~
Go Daddy Class 2 CA
Go Daddy Root Certificate Authority - G2

**Comment by pschaeffer** [comment]
Mr. Stenberg,

 

Thank you for your reply.

 

I checked the Ubuntu distribution (the SSL Cert store) on my Ubuntu machine and AWS (Ubuntu 18.04.01 LTS).

 

Both have 

 

Go Daddy Class 2 CA

Go Daddy Root Certificate Authority - G2

 

But not

 

Go Daddy Secure Certificate Authority - G2

 

Firefox has

 

Go Daddy Root Certificate Authority - G2

Go Daddy Secure Certificate Authority - G2

 

Chrome has 

 

Go Daddy Class 2 Certification Authority

Go Daddy Root Certificate Authority – G2

 

As Trusted Root Certification Authorities

 

Chrome also has 

 

Go Daddy Secure Certificate Authority - G2

Go Daddy Secure Certification Authority

 

As Intermediate Certification Authorities

 

It appears that Chrome and Microsoft Edge (under Windows 10) actually use the Windows certificate store.

 

Once again, thank you for your help.

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Mr. Stenberg,

 

This is not a bug report or a problem report. My intent is to provide information that is hopefully helpful.

 

Recently, I needed to use pycurl to access some AWS files. This ultimately worked correctly. However, to make this work I needed to provide a private key and a public key. As it turns out I already had a .ppk file (from AWS) that I thought might work. The .ppk file does work with the Windows version of Putty and the Windows version of FileZilla Pro.

 

The file (the .ppk file) did not work directly with SFTP using pycurl. I was able to use the Windows version of puttygen (PuTTY Key Generator) to obtain files that did work with SFTP/pycurl.

 

1. The private key was obtained by using the first of the puttygen conversion options (Export OpenSSH key). The ‘Save private key’ mechanism did not work (at all).

 

2. The public key was obtained by copying and pasting the public key from the program (from the ‘Public key for pasting into OpenSSH authorized_keys file:’ box). The public key was not obtained by using ‘Save public key’.

 

Thank you

 

Peter Schaeffer

 

From: Peter Schaeffer [mailto:peter_schaeffer@yahoo.com] 
Sent: Saturday, August 31, 2019 9:47 PM
To: 'curl/curl'; 'curl/curl'
Cc: 'Author'
Subject: RE: [curl/curl] CA List Used By Curl (#4285)

 

Mr. Stenberg,

 

Thank you for your reply.

 

I checked the Ubuntu distribution (the SSL Cert store) on my Ubuntu machine and AWS (Ubuntu 18.04.01 LTS).

 

Both have 

 

Go Daddy Class 2 CA

Go Daddy Root Certificate Authority - G2

 

But not

 

Go Daddy Secure Certificate Authority - G2

 

Firefox has

 

Go Daddy Root Certificate Authority - G2

Go Daddy Secure Certificate Authority - G2

 

Chrome has 

 

Go Daddy Class 2 Certification Authority

Go Daddy Root Certificate Authority – G2

 

As Trusted Root Certification Authorities

 

Chrome also has 

 

Go Daddy Secure Certificate Authority - G2

Go Daddy Secure Certification Authority

 

As Intermediate Certification Authorities

 

It appears that Chrome and Microsoft Edge (under Windows 10) actually use the Windows certificate store.

 

Once again, thank you for your help.

 

Peter Schaeffer

**Comment by jay** [comment]
If you are using the latest certificate bundle my guess is the server you are connecting to is not configured properly. `Go Daddy Root Certificate Authority - G2` is included in the curl certificate bundle (which is just Mozilla's bundle) and is the issuer of `Go Daddy Secure Certificate Authority - G2`. `Go Daddy Secure Certificate Authority - G2` is an intermediate certificate _not_ a root certificate, therefore it is not included. Firefox and Chrome cache intermediate certificates when they encounter them, which is hiding that the server you are accessing is likely misconfigured and not sending the right certificate chain. It is not required to cache intermediate certificates.
