### ISSUE TITLE
FTP CWD doesn't always work in steps

### ISSUE THREAD

**Issue by Erroneous1** [curl/curl#4292]
I sometimes have to FTP to servers that require files to be put into folders like `FOLDA/FOLDB`. curl is breaking this into `CWD FOLDA` then `CWD FOLDB` but I don't have access to FOLDA even though I do have access to FOLDB.
```
< 230 User logged in.
> PWD
< 257 "/" is current directory.
* Entry path is '/'
> CWD FOLDA
* ftp_perform ends with SECONDARY: 0
< 550 Access is denied. 
* Server denied you to change to the given directory
```
If I use the ftp command to login to the server I get this:
```
230 User logged in.
Remote system type is Windows_NT.
ftp> cd FOLDA/FOLDB
250 CWD command successful.
ftp> pwd
257 "/FOLDA/FOLDB" is current directory.
```

I can currently work around it by specifying the path as `FOLDA\\FOLDB` but anticipate having an FTP server in the future that doesn't take a `\` as a folder separator in which case I'd be stuck. My thought is to have some kind of option to CWD all at once and/or maybe specify a folder separator character/string, which is my guess for why it is doing multiple CWD in the first place.

**Comment by bagder** [comment]
This is not really a curl bug but a "funny" server setup (the specs say that it should do the CWD series using the paths given in the URL). See `--ftp-method` for how to work around it.

**Comment by Erroneous1** [comment]
Ah thanks! Sorry I didn't see this before, I think I must've been looking for CD instead of CWD.
