### ISSUE TITLE
Curl with wolfSSL can not set  CURLOPT_CERTINFO

### ISSUE THREAD

**Issue by patrickkh7788** [curl/curl#4293]
I try build curl 7.65.3 with woflSSL v4.1.0, test `https://curl.haxx.se/libcurl/c/CURLINFO_CERTINFO.html`

`curl_easy_setopt(curl, CURLOPT_CERTINFO, 1L);` return this error:

```sh
A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

my worlfSSL build with `--enable-certgen=yes --enable-certreq=yes --enable-certext=yes --enable-sessioncerts=yes` 

I alto try `CURLINFO_PRIMARY_IP` =1048608, CURLINFO_PRIMARY_PORT, return null & 0;

**Comment by bagder** [comment]
Let me quote the  CURLOPT_CERTINFO man page:

**AVAILABILITY**
This option is supported by the OpenSSL, GnuTLS, Schannel, NSS and GSKit backends.

**Comment by patrickkh7788** [comment]
Thanks for the tip.  The curl document is really good and I should read more carefully.

If so, is there a way to let client know if the connect is base on TLS1.3 or not ?

**Comment by bagder** [comment]
> is there a way to let client know if the connect is base on TLS1.3 or not ?

Not that I can recall, no. The libcurl API doesn't provide that info easily... `CURLOPT_CERTINFO` would not help there either.

**Comment by bagder** [comment]
Since this is a known and documented limitation, I'm closing.
