### ISSUE TITLE
Forcing TLS version should ensure to bypass the OpenSSL OS default

### ISSUE THREAD

**Issue by cnotin** [curl/curl#4298]
This is a follow-up to #4097 
I had a few things to suggest after the issue was closed and I think it won't be seen there and I cannot re-open it myself so I open this one. I hope it's fine with you :)
Please see:
https://github.com/curl/curl/issues/4097#issuecomment-525853346

I know that what I shared is not ready for PR but if you think it's a good idea, then I can work on it and suggest something better!

**Comment by bagder** [comment]
I think it seems like a good idea, and I think submitting a PR is a better way to offer code! =)

**Comment by cnotin** [comment]
Thanks for the confirmation. I'll suggest proper code then 😉

**Comment by cnotin** [comment]
Fixed by #4304
