### ISSUE TITLE
curl 7.65.3 won't add SSL when configured with --with-secure-transport

### ISSUE THREAD

**Issue by mxaddict** [curl/curl#4312]
### I did this
Compiled curl/libcurl using `--without-ssl --with-secure-transport`

### I expected the following
I expect to get a lib and bin with SSL support

### curl/libcurl version
7.65.3

### operating system (compiled on)
Linux Ubuntu 18.04

### operating system (ran on)
OSX 10.14

**Comment by mxaddict** [comment]
Full configure call:
```
./configure --host=x86_64-apple-darwin14 --disable-dependency-tracking --prefix=/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14 --enable-static --disable-shared --without-libidn2 --with-pic --without-ssl --with-secure-transport CC="clang -target x86_64-apple-darwin14 -mmacosx-version-min=10.10 --sysroot /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9" CXX="clang++ -target x86_64-apple-darwin14 -mmacosx-version-min=10.10 --sysroot /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9 -stdlib=libc++ NM=x86_64-apple-darwin14-nm RANLIB=x86_64-apple-darwin14-ranlib AR=x86_64-apple-darwin14-ar CFLAGS=-pipe -O2     CXXFLAGS=-pipe -O2     CPPFLAGS=-I/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/include     LDFLAGS=-L/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/lib"
```

Compiled binary when run on OSX has this version info:
```
curl 7.65.3 (x86_64-apple-darwin14) libcurl/7.65.3 zlib/1.2.11
Release-Date: 2019-07-19
Protocols: dict file ftp gopher http imap ldap ldaps pop3 rtsp smtp telnet tftp 
Features: AsynchDNS IPv6 Largefile libz UnixSockets
```

**Comment by mxaddict** [comment]
./configure output after running the configure call pasted in last comment:
```
configure: Configured to build curl/libcurl:

  Host setup:       x86_64-apple-darwin14
  Install prefix:   /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14
  Compiler:         clang -target x86_64-apple-darwin14 -mmacosx-version-min=10.10 --sysroot /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9
   CFLAGS:          -pipe -O2 -pipe -O2 -Qunused-arguments -mmacosx-version-min=10.8 -Werror=partial-availability
   CPPFLAGS:        -isystem /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/share/../include/ -isystem /home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/include -I/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/include
   LDFLAGS:         -L/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/share/../lib -L/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/lib -L/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/x86_64-apple-darwin14/lib
   LIBS:            -lldap -lz

  curl version:     7.65.3
  SSL:              no      (--with-{ssl,gnutls,nss,mbedtls,wolfssl,schannel,secure-transport,mesalink,amissl} )
  SSH:              no      (--with-libssh2)
  zlib:             enabled
  brotli:           no      (--with-brotli)
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          no      (--enable-tls-srp)
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     
  ca fallback:      
  LDAP:             enabled (OpenLDAP)
  LDAPS:            enabled
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          no      (--enable-alt-svc)
  HTTP2:            disabled (--with-nghttp2)
  Protocols:        DICT FILE FTP GOPHER HTTP IMAP LDAP LDAPS POP3 RTSP SMTP TELNET TFTP
  Features:         IPv6 UnixSockets libz AsynchDNS

```

**Comment by mxaddict** [comment]
I see these lines in configure.ac: https://github.com/curl/curl/blob/74e152f11915cdd46792daf5c5728be1b0dd9503/configure.ac#L1548-L1557

Which leads me to think that this is the cause, as it's checking for the existence of `/System/Library/Frameworks/Security.framework` DIR

which on my system is located here: `/home/mxaddict/Projects/mxaddict/navcoin-temp/depends/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework`

**Comment by jay** [comment]
Something to do with sysroot not supported there I guess.

/cc @nickzman

**Comment by mxaddict** [comment]
The --sysroot value that I used in the congigure step is passed to the CXX and CC values, not the configure directly, if I pass those to the ./configure step, should that fix the issue?

Thanks for the hint, I'll check it out.

**Comment by nickzman** [comment]
Yeah, that test ignores sysroot and expects the Security library to be at the path where macOS normally places it, because I didn't write this code with cross-compiling from non-Apple operating systems in mind. I don't think that was even a thing at the time I wrote that.

If you can fix that, then please create a PR that fixes it without breaking support for building it on macOS.

**Comment by mxaddict** [comment]
> Yeah, that test ignores sysroot and expects the Security library to be at the path where macOS normally places it, because I didn't write this code with cross-compiling from non-Apple operating systems in mind. I don't think that was even a thing at the time I wrote that.
> 
> If you can fix that, then please create a PR that fixes it without breaking support for building it on macOS.

Ok, I'll see what I can come up with, I need to first get my build working, once I get it working, then I'll be sure to create a PR for it.

**Comment by mxaddict** [comment]
@nickzman what is the minimum version of OSX SDK that is required to compile with secure-transport?

Our project is using OSX SDK 10.11

**Comment by mxaddict** [comment]
I've managed to get `./configure` to move on with secure-transport, but it's failing on compiler check:
```
checking for x86_64-apple-darwin14-gcc... clang -target x86_64-apple-darwin14 -mmacosx-version-min=10.10 --sysroot /home/mxaddict/Projects/mxaddict/navcoin-core/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9
checking whether the C compiler works... no
configure: error: in `/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.3-7c2f9892456':
configure: error: C compiler cannot create executables
```

**Comment by mxaddict** [comment]
> I've managed to get `./configure` to move on with secure-transport, but it's failing on compiler check:
> 
> ```
> checking for x86_64-apple-darwin14-gcc... clang -target x86_64-apple-darwin14 -mmacosx-version-min=10.10 --sysroot /home/mxaddict/Projects/mxaddict/navcoin-core/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9
> checking whether the C compiler works... no
> configure: error: in `/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.3-7c2f9892456':
> configure: error: C compiler cannot create executables
> ```

I'm assuming this is either because of clang version `3.7.1` or our SDK version `10.11`

**Comment by mxaddict** [comment]
More info on the error:
```
configure:4276: checking whether the C compiler works
configure:4298: clang -target x86_64-apple-darwin14 -arch x86_64 -mmacosx-version-min=10.10 -isysroot /home/mxaddict/Projects/mxaddict/navcoin-core/depends/SDKs/MacOSX10.11.sdk -mlinker-version=253.9 -pipe -O2     -I/home/mxaddict/Projects/mxaddict/navcoin-core/depends/x86_64-apple-darwin14/include     -L/home/mxaddict/Projects/mxaddict/navcoin-core/depends/x86_64-apple-darwin14/lib     conftest.c  >&5
/usr/bin/ld: unrecognised emulation mode: acosx_version_min
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4302: $? = 1
configure:4340: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.haxx.se/mail/"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int main (void)
| {
| 
|  ;
|  return 0;
| }
configure:4345: error: in `/home/mxaddict/Projects/mxaddict/navcoin-core/depends/work/build/x86_64-apple-darwin14/curl/7.65.3-8b5500fae10':
configure:4347: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by nickzman** [comment]
The minimum SDK for Secure Transport is macOS 10.5, iOS 5.0, watchOS 2.0, and any tvOS release.

**Comment by nickzman** [comment]
That error looks like an SDK problem, not a curl problem, to me.

**Comment by mxaddict** [comment]
> That error looks like an SDK problem, not a curl problem, to me.

Any idea where I should start looking into the issue?

**Comment by mxaddict** [comment]
@nickzman So I think I've managed to get it working

I was doing something wrong with buildconf aparently, so instead of modifying the configure.ac, I patched the configure file that comes with source downloads from mirror

Here is the patch:
```patch
--- a/configure
+++ b/configure
@@ -22234,8 +22234,7 @@ fi
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether to enable Secure Transport" >&5
 $as_echo_n "checking whether to enable Secure Transport... " >&6; }
 if test -z "$ssl_backends" -o "x$OPT_SECURETRANSPORT" != xno; then
-  if test "x$OPT_SECURETRANSPORT" != "xno" &&
-     test -d "/System/Library/Frameworks/Security.framework"; then
+  if test "x$OPT_SECURETRANSPORT" != "xno"; then
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }

@@ -21647,7 +21647,7 @@
       { $as_echo "$as_me:${as_lineno-$LINENO}: checking for gdi32" >&5
 $as_echo_n "checking for gdi32... " >&6; }
       my_ac_save_LIBS=$LIBS
-      LIBS="-lgdi32 $LIBS"
+      LIBS="$LIBS -lgdi32"
       cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 #include <windef.h>
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -55,7 +55,7 @@ include Makefile.inc
 curl_SOURCES = $(CURL_FILES)

 # This might hold -Werror
-CFLAGS += @CURL_CFLAG_EXTRAS@
+CFLAGS += @CURL_CFLAG_EXTRAS@ -DBUILDING_LIBCURL

 # Prevent LIBS from being used for all link targets
 LIBS = $(BLANK_AT_MAKETIME)
```

**Comment by mxaddict** [comment]
@nickzman do you think it's worth it for me to create PR to change configure.ac to allow for cross-compiling with secure-transport?

**Comment by nickzman** [comment]
We'll consider it if you make it. I wouldn't completely remove the check for Security.framework, though. We kind of need to know that the user has a Security framework so compiling and linking will work.

**Comment by mxaddict** [comment]
> We'll consider it if you make it. I wouldn't completely remove the check for Security.framework, though. We kind of need to know that the user has a Security framework so compiling and linking will work.

Ok, what do you suggest as an alternative way to check?

Does the configure.ac have access to the sysroot value?

**Comment by mxaddict** [comment]
If configure.ac has access to sysroot, then I can add that to the check.

**Comment by bagder** [comment]
How would you propose it gets knowledge about it? configure can run any shell commands. It could even try to find out in environment variables or allowing it to get set by a command line argument.

**Comment by mxaddict** [comment]
I'll see what I can do. And create a PR
