### ISSUE TITLE
macos:  __builtin_available() must only be used in dynamic-linked libraries

### ISSUE THREAD

**Issue by robohack** [curl/curl#4314]
I've been having trouble using a static-only build of `libcurl.a` on more recent macOS systems (e.g. 10.14).  (For example we only use static versions of third party libraries to avoid having to distribute any of them with our product binaries.)

The Clang specific `__builtin_available()` compiler built-in function is (on macOS) using at least one function (`__isOSVersionAtLeast()`) supplied for runtime use by a dynamic-linked helper library (i.e. it is not available in `/usr/lib/libSystem.B.dylib`).

This means that when certain values of `-mmacosx-version-min=` are used to build the static `libcurl.a` library, in combination with certain versions of the MacOSX SDK, the compiler will sometimes have been unable to optimize away the use of `__builtin_available()` and the link of a program (e.g. `curl` itself) using the static `libcurl.a` may fail with an error like the following:

<pre>
  CCLD     curl
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _singleipconnect in libcurl.a(libcurl_la-connect.o)
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

The following change works around this issue, but is perhaps not complete:

<pre>
diff -u curl-7.65.3/lib/connect.c\~ curl-7.65.3/lib/connect.c
--- curl-7.65.3/lib/connect.c~	2019-07-16 03:24:31.000000000 -0700
+++ curl-7.65.3/lib/connect.c	2019-09-09 12:05:15.000000000 -0700
@@ -1103,7 +1103,8 @@
   if(!isconnected && (conn->socktype == SOCK_STREAM)) {
     if(conn->bits.tcp_fastopen) {
 #if defined(CONNECT_DATA_IDEMPOTENT) /* Darwin */
-#  if defined(HAVE_BUILTIN_AVAILABLE)
+#  if defined(HAVE_BUILTIN_AVAILABLE) && !defined(CURL_STATICLIB)
+      /* XXX N.B. __builtin_available() won't work with static libraries! */
       /* while connectx function is available since macOS 10.11 / iOS 9,
          it did not have the interface declared correctly until
          Xcode 9 / macOS SDK 10.13 */
</pre>

I've also seen at least one other person who encountered this same problem suggest using some special linker options that would force the runtime linker (since it's always used on macOS anyway) to still resolve the missing symbol at runtime despite having been loaded from a static library.  However such a solution would require all users of the static `libcurl.a` library so built to add these linker options to all their builds, and that's really not very scalable.

BTW, generally it is not a very good idea for a library build to automatically try to set `macosx-version-min` in the first place, especially since this may have to be done globally across dependencies by the user for other purposes.  For example anyone using a more recent macOS SDK, e.g. from 10.14, can only target 10.9 and newer, so trying to force libcurl to build with 10.8 causes incompatible object files.  As a result I've also had to override the value of this option when building curl.

See also the following for how to detect if `__builtin_available()` can be used:

[Clang Language Extensions:  Feature Checking Macros](http://clang.llvm.org/docs/LanguageExtensions.html#id2)

Also, has anyone really tested if `connectx()` actually causes libcurl to use TCP Fast Open on macOS?  The manual page suggests it will only work when data is passed via a `struct iovec`, but I don't see any obvious calls to `writev()` or `sendmsg()` in libcurl.  Perhaps this whole exercise to use `connectx()` on macOS has been in vain?

### I did this

configure with `--enable-static --disable-shared` and build with `osxcross` and clang-8.0.1 against the MacOSX10.14 SDK.

### I expected the following

clean builds of programs (including `curl` itself) using the static `libcurl.a`

It may be possible to demonstrate this link error directly on a macOS build too, but I've not yet tried the various combinations of `macosx-version-min` to see 

### curl/libcurl version

<pre>
build-x64-darwin/curl-7.65.3/src/curl -V
curl 7.65.3 (x86_64-apple-darwin18) libcurl/7.65.3 OpenSSL/1.0.2h zlib/1.2.5 c-ares/1.15.0
Release-Date: 2019-07-19
Protocols: file ftp ftps http https smb smbs smtp smtps 
Features: AsynchDNS HTTPS-proxy Largefile libz NTLM NTLM_WB SSL UnixSockets
</pre>

### operating system

macos 10.14

**Comment by nickzman** [comment]
I take it you are building libcurl on another operating system, and cross-compiling it with macOS. I don't want to say that we don't support that, however, when we make changes specific to macOS, they are typically made with building on actual macOS running Apple's latest developer tools in mind. That works for most people, but might not work on more esoteric environments.

I build the static library on macOS using Apple's compiler all the time. I just built a minimal libcurl with the deployment target set to 10.6, and it worked.

I don't believe libcurl sets `macosx-version-min` to anything other than the default, unless you changed that by setting CFLAGS prior to running the configure script. All binary code on macOS must have a minimum OS version set, and by default, it's the current OS version.

If I'm right and you're cross-compiling, please make a pull request that fixes the problem for you and doesn't break the macOS/iOS/tvOS build on macOS.

**Comment by robohack** [comment]
Re `macosx-version-min`:

See the macro `CURL_MAC_CFLAGS` in `acinclude.m4` starting at about line 2505.

**Comment by robohack** [comment]
Note the patch I have supplied will clearly not break any build, and has been tested with a native build on macOS

**Comment by bagder** [comment]
> Note the patch I have supplied will clearly not break any build

Can you please submit that as a pull-request if that is what you propose we should merge?

**Comment by robohack** [comment]
Done!  Sorry for the delay!
