### ISSUE TITLE
curl with -Z won't finish all requests

### ISSUE THREAD

**Issue by TvdW** [curl/curl#4316]
### I did this

    ./curl -Z https://home.xifon.eu/{1..200} -v --parallel-max 2

I would expect all 200 requests to be executed. Instead, it only executes a few: sometimes four, sometimes twenty, but I haven't seen it get all the way to 200. Look at the "GET /$x" to see how far it gets.

### curl/libcurl version

    curl 7.66.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.66.0-DEV OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.1 c-ares/1.15.0 nghttp2/1.39.1
    Release-Date: [unreleased]
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
    Features: AsynchDNS brotli HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

**Comment by bagder** [comment]
Does it make a difference if you remove `--parallel-max 2` or change the number?

**Comment by TvdW** [comment]
Certainly does! With 1 it really only ever executes a single request. With 10 it gets half way there. Without passing it it finishes all the way.

Here's a hunch: curl seems to run until there are 0 *active* transfers, rather than waiting until it processed every URL given on the command line.

**Comment by bagder** [comment]
Thanks, this issue really proves that we haven't tested this feature much... :disappointed: PR coming up!

**Comment by bagder** [comment]
Does #4317 fix the problem for you?

**Comment by TvdW** [comment]
Well, yes and no.

Yes: it's much better

No: it skips the last request

    ./curl -Z https://home.xifon.eu/{1..2} --parallel-max 1

^only shows one response (should do two)

**Comment by bagder** [comment]
pushed an update

**Comment by TvdW** [comment]
Seems to work now! 😃

**Comment by bagder** [comment]
Lovely!
