### ISSUE TITLE
FTP listing: CURLFTPMETHOD_NOCWD leaves trailing slash

### ISSUE THREAD

**Issue by Zenju** [curl/curl#4320]
Hi,

curl currently leaves a trailing slash on the directory listing command issued when CURLFTPMETHOD_NOCWD is set, e.g.

curl --ftp-method nocwd ftp://mirrors.sonic.net//mint/
LIST /mint/

curl --ftp-method nocwd ftp://mirrors.sonic.net//
LIST /

curl --ftp-method nocwd ftp://mirrors.sonic.net/%2fmint/
LIST /mint/

curl --ftp-method nocwd ftp://mirrors.sonic.net/%2f/
LIST //

This seems to still mostly work, except for the last case, were some servers respond with:
"LIST // 501 Syntax error in parameters or arguments"

Ideally, curl should remove the trailing slash (except for /) because it isn't really part of the path, but required by curl?

**Comment by bagder** [comment]
Agreed!

**Comment by Zenju** [comment]
Problem solved, thanks for accepting the patch!
