### ISSUE TITLE
Curl 7.66.0 Link error on Windows 

### ISSUE THREAD

**Issue by SteffenAL** [curl/curl#4322]
LINK : fatal error LNK1181: cannot open input file '..\builds\libcurl-vc15-x86-release-dll-zlib-dll-winssl-obj-lib\vssh\libssh2.obj'

Curl 7.65.3 was building fine

### I did this
nmake /f makefile.vc vc=15 WITH_DEVEL=C:\VC15\Win32\deps-curl-WinSSL mode=dll USE_SSPI=yes USE_IPV6=yes USE_IDN=no MACHINE=x86 WITH_ZLIB=dll ENABLE_WINSSL=yes

### I expected the following
Build without errors

### curl/libcurl version
7.66.0

### operating system
Windows server 2019

**Comment by bagder** [comment]
Please try #4323 and see if it fixes it for you!

**Comment by SteffenAL** [comment]
Thanks!

All fine now.
