### ISSUE TITLE
AF_LOCAL does not exist on Solaris

### ISSUE THREAD

**Issue by dago** [curl/curl#4328]
When building the latest curl 7.66.0 on Solaris 10 the build fails with
```
gmake[2]: Entering directory '/home/dam/mgar/pkg/curl/trunk/work/solaris10-sparc/build-isa-sparcv8plus-features-minimal/curl-7.66.0/lib'
  CC       libcurl_la-asyn-thread.lo
"asyn-thread.c", line 248: undefined symbol: AF_LOCAL
cc: acomp failed for asyn-thread.c
```

This is because `AF_LOCAL` does not exist on Solaris. As a suggested workaround `AF_UNIX` could be used.

**Comment by dago** [comment]
I wonder why this did not pop up on the continuous build environment.

**Comment by bagder** [comment]
> why this did not pop up on the continuous build environment

That's indeed a mystery!

So does it work for you if we simply use `AF_UNIX` there instead?

**Comment by dago** [comment]
Yes, this seems to work and the compilation and testsuite passes.

**Comment by bagder** [comment]
Thanks!
