### ISSUE TITLE
clear instructions for building latest curl for fedora rawhide

### ISSUE THREAD

**Issue by omac777** [curl/curl#4330]
The latest available builds for fedora rawhide on the main curl website do not have http3 enabled on them.
This is why I was motivated to do this.

```
I'm attempting to build the latest http3/parallelized curl(https://github.com/curl/curl) with quiche on fedora rawhide. There are no packages available for the latest curl yet.

Here are the steps I tried to accomplish:

git clone https://boringssl.googlesource.com/boringssl
cd boringssl/
emacs CMakeLists.txt &
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
mkdir build
cd build/
cmake ..
make

cargo install cargo-rpm

git clone https://github.com/cloudflare/quiche
cd quiche/
QUICHE_BSSL_PATH="/home/davidm/Downloads/boringssl" cargo build --release
cargo rpm init ################this is the one that fails since library-type package creation using the "cargo-rpm" crate is not supported yet.
cargo rpm build

git clone https://github.com/curl/curl
cd curl/
./buildconf 
./configure --with-quiche=/home/davidm/Downloads/quiche  #####this fails since it's looking for a package config file. ######quiche.pc
```

**Comment by bagder** [comment]
It seems you want to build a HTTP/3 enabled version using quiche? Note that it is still marked **experimental** so even when Fedora catches up they most likely would provide such a build yet.

Did you try following the instructions exactly as detailed in [HTTP3.md](https://github.com/curl/curl/blob/master/docs/HTTP3.md#build-1)?

**Comment by bagder** [comment]
@omac777, if you want to reproduce a distro build then you're better of checking the distro's specific build setup and sources. The curl repo does not contain dedicated build scripts for distros and making such packages, but each distro is responsible for their own curl build scripts.

But again, I doubt any of them enable HTTP/3 yet and I would strongly advice anyone from doing that for packages that might get used in production. HTTP/3 support is still highly experimental.

**Comment by bagder** [comment]
I don't think this is an actual issue, closing.
