### ISSUE TITLE
how does it now support concurrent transmitting or should I call it parallel transmitting? 

### ISSUE THREAD

**Issue by zzz6519003** [curl/curl#4334]

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
