### ISSUE TITLE
Unable to parse network drive for --cert

### ISSUE THREAD

**Issue by Korkki** [curl/curl#4337]
It seems flag --cert has an issue parsing network drives. For example for this query:

curl -k -X GET [corporate internal service].json -o "\\[corporate network drive]\output.json" --key "\\[corporate network drive]\decrypted_private_key.pem" --cert "\\[corporate network drive]\public_cert.pem"

Gives out an error: 

curl: (58) could not load PEM client certificate, OpenSSL error error:02001003:system library:fopen:No such process, (no key found, wrong pass phrase, or wrong file format?)

This can be fixed by adjusting folder path for --cert:

curl -k -X GET [corporate internal service].json -o "\\[corporate network drive]\output.json" --key "\\[corporate network drive]\decrypted_private_key.pem" --cert "//[corporate network drive]/public_cert.pem"

Notice that parsing is working as intended for flags -o and --key.

Version used:

curl 7.65.3 (x86_64-pc-win32) libcurl/7.65.3 OpenSSL/1.1.1c (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.1 Release-Date: 2019-07-19

OS: Windows 10 Enterprise 64-bit 17763.720

**Comment by Korkki** [comment]
Reported to OpenSSL project https://github.com/openssl/openssl/issues/10009

**Comment by bagder** [comment]
Not our bug. Closing.
