### ISSUE TITLE
Potential Hang Issue With Transfer-Encoding: Chunked

### ISSUE THREAD

**Issue by sylvanaar** [curl/curl#4341]
I am not completely certain that this is a curl issue and not an issue with a bad server implementation, but I wanted to open this here for review.

I can reproduce this 100% of the time, and will be happy to provide any additional information requested.

### I did this

I made a call to the docker API using curl, it returned a response using `Transfer-Encoding: chunked`

Curl Command

`curl  --trace - --unix-socket /var/run/docker.sock http:/v1.27/containers/json?all=1&filters={%22status%22:[%22created%7Crestarting%7Crunning%22]}`

Curl transfered the JSON payload from the api and output it.

It then output the message:

`== Info: Connection #0 to host http left intact`

And did not exit.

Info from `--trace`

```
Get chunk of size 0x5751 in 2 data reads with trailing zero chunk

First read 

<= Recv data, 16174 bytes (0x3f2e)
0000: 35 37 35 31 0d 0a 5b 7b 22 49 64 22 3a 22 39 35 5751..[{"Id":"95

...

3f20: 66 39 62 66 64 62 32 35 63 22 2c 22 49 6d       f9bfdb25c","Im



Now we have 0x5751 - (0x3f2e - 0x6)  = 0x1829 remaing

Second Read

<= Recv data, 6192 bytes (0x1830)
0000: 61 67 65 49 44 22 3a 22 73 68 61 32 35 36 3a 61 ageID":"sha256:a

...

1820: 74 73 22 3a 5b 5d 7d 5d 0a 0d 0a 30 0d 0a 0d 0a ts":[]}]...0....
```

### I expected the following

Curl should recognize the end of the chunked transfer and terminate.

### curl/libcurl version

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

### operating system

Ubuntu 16.04.4 LTS

**Comment by bagder** [comment]
What HTTP server and version is that? Can we reproduce this against a public URL somewhere?

Or can you perhaps extract the full "raw" response so that we can create a stand-alone test case reproducing it? I suspect a server-side issue here...

**Comment by sylvanaar** [comment]
It is the golang HTTP server library. https://golang.org/pkg/net/http/

It is the API endpoint for Docker CE 18.09.3

**Comment by bagder** [comment]
Yes please, we need a way to reproduce this problem otherwise there's nothing we can do! It would be enough if we can get the headers and the raw response body so that we can replay those in our test suite.

**Comment by bagder** [comment]
Cannot reproduce and no response in over a month. Closing.
