### ISSUE TITLE
curl_multi_poll: symbol not found

### ISSUE THREAD

**Issue by hehoo** [curl/curl#4357]
### After I updated curl version to 7.66.0-r0 then I got the error below when I run "curl http://www.google.com"

**Error relocating /usr/bin/curl: curl_multi_poll: symbol not found**

**Comment by bagder** [comment]
`curl_multi_poll()` was introduced in 7.66.0. This error seems to suggest that your curl finds an older libcurl in run-time.

**Comment by hehoo** [comment]
Does `apk update; apk add curl` also upgrade curl's latest dependencies, i.e. libcurl?  I also tried `apk update; apk add libcurl cur`, but it doesn't work either.  When I tried to install a older version of curl by using apk `apk update; apk add curl=7.65.3-r0`. I got the error below: 
```
ERROR: unsatisfiable constraints:
  curl-7.66.0-r0:
    breaks: world[curl=7.65.3-r0]
```

**Comment by hehoo** [comment]
It seems like I have to run apk upgrade after apk add to upgrade all curl's dependencies. 
```
apk add curl && apk upgrade
```
At least it solved my problem. 
Thanks @bagder , your comments remind me a lot.

**Comment by jogu** [comment]
> It seems like I have to run apk upgrade after apk add to upgrade all curl's dependencies. Very confused why `apk add` would not update the package's dependencies automatically? Per apk's documentation, it should update all dependencies. But it seems it doesn't for this case.
> 
> ```
> apk add curl && apk upgrade
> ```

whilst this works fine, I believe it will upgrade everything on the system (which may or may not be desirable) - for a lower impact alternative we're using:

```
apk add --update-cache --upgrade curl
```

**Comment by hehoo** [comment]
@jogu thanks for your comment, will give it a try :)
