### ISSUE TITLE
HTTP/3 and libcurl-multi

### ISSUE THREAD

**Issue by puzza007** [curl/curl#4362]
I'm adding support for http/3 to my libcurl-based library and have come across a strange issue. I add a curl_multi_add_handle as usual and the first request works fine, however when I submit the second I receive no callbacks to my `CURLOPT_HEADERFUNCTION` or `CURLOPT_WRITEFUNCTION` and the request times out. I've built curl using quiche on OSX as per the instructions [here](https://github.com/curl/curl/blob/master/docs/HTTP3.md#quiche-version). Is there anything I should be aware of? For what it's worth my code is [here](https://github.com/puzza007/katipo/pull/96/files). The same code is fine with both HTTP 1.1 and HTTP/2.

Curl ver: 7.66.0-DEV
OS: OSX

**Comment by bagder** [comment]
It *should* work exactly like it works with the other versions, but as this is still early days there's probably some mistake left in there to fix.

**Comment by bagder** [comment]
I can reproduce with the attached test code:  [multi-h3.c](https://github.com/curl/curl/files/3618394/multi-h3.c.txt)

**Comment by bagder** [comment]
I can no longer reproduce this with the above mentioned test code. Can you (using git master) ?

**Comment by puzza007** [comment]
Works for me using git master. Thanks!
