### ISSUE TITLE
Setting CURL_LOCK_DATA_CONNECT sets errno without returning an error

### ISSUE THREAD

**Issue by gquintard** [curl/curl#4370]
### I did this

```
#include <assert.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <curl/curl.h>
int
main(int argc, char *argv[])
{
	FILE *file;
	CURLSH *c;
	int e = 0;
	errno = 0;

	c = curl_share_init();
	assert(c);
	e = curl_share_setopt(c, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT);
	printf("curl_share_setopt returned %d, errno is %d\n", e, errno);
	return(0);
}
```

got:

```
curl_share_setopt returned 0, errno is 2
```

### I expected the following

```
curl_share_setopt returned 0, errno is 0
```

### curl/libcurl version

```
$ dpkg -l | grep curl
ii  libcurl4:amd64               7.64.0-4                     amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl4-openssl-dev:amd64   7.64.0-4                     amd64        development files and documentation for libcurl (OpenSSL flavour)
```

### operating system
Running on the `debian:buster` image from the docker hub

**Comment by jay** [comment]
This is not a curl issue, any function called by libcurl may set errno. errno is only valid after a function that has documented support for it, and usually it would only be valid if an error occurred.

The function you are calling returns an error code if one occurred, of type [CURLSHcode](https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLSHcode).

**Comment by gquintard** [comment]
Fair enough, thank you for the quick feedback
