### ISSUE TITLE
How does curl select a host to establish a connection with?

### ISSUE THREAD

**Issue by pmyjavec** [curl/curl#4376]
### I did this

I use curl to connect to one of three instances we have running:

```
dig service.internal +short
10.2.145.21
10.2.0.83
10.2.74.20
```

When I run curl it consistently connects to one of the hosts:

```
$ curl -v service.internal:8080
* Rebuilt URL to: service.internal:8080/
*   Trying 10.2.0.83...
* TCP_NODELAY set
* Connected to service.internal (10.2.0.83) port 8080 (#0)
```

This happens over and over again and always connects to the same host; However if I look at what curl is doing under the hood using strace, it seems to try to connect to all three hosts and consistently connects to the same one:

```
14255 connect(3, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("10.2.74.20")}, 16 <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696199959}) = 0
14255 <... connect resumed> )           = 0
14254 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>14255 getsockname(3,  <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696231196}) = 0
14255 <... getsockname resumed> {sa_family=AF_INET, sin_port=htons(41384), sin_addr=inet_addr("10.2.16.94")}, [28->16]) = 0
14254 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
14255 connect(3, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16 <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696269279}) = 0
14255 <... connect resumed> )           = 0
14254 rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fce9ca151f0},  <unfinished ...>
14255 connect(3, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("10.2.145.21")}, 16 <unfinished ...>
14254 <... rt_sigaction resumed> NULL, 8) = 0
14255 <... connect resumed> )           = 0
14254 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
14255 getsockname(3,  <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696335507}) = 0
14255 <... getsockname resumed> {sa_family=AF_INET, sin_port=htons(33172), sin_addr=inet_addr("10.2.16.94")}, [28->16]) = 0
14254 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
14255 connect(3, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16 <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696366191}) = 0
14255 <... connect resumed> )           = 0
14254 clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
14255 connect(3, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("10.2.0.83")}, 16 <unfinished ...>
14254 <... clock_gettime resumed> {tv_sec=2980211, tv_nsec=696393997}) = 0
14255 <... connect resumed> )           = 0
14254 clock_gettime(CLOCK_MONOTONIC
```

My theory is, one of these hosts (for whatever reasons) responds first and that is the one selected.

### I expected the following

I gues curl should respect the DNS round-robin values and not play games trying to guess which host it should connect to.

### curl/libcurl version

`curl 7.61.1 (x86_64-koji-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k zlib/1.2.7 libidn2/2.0.4 libssh2/1.4.3 nghttp2/1.31.1`

### operating system

Amazon Linux 2 without a local DNS caching service.

**Comment by bagder** [comment]
libcurl can resolve names in [several different ways](https://curl.haxx.se/docs/faq.html#How_does_libcurl_resolve_host_na) - decided at build-time (DoH not even included there), but by default and on most systems it uses `getaddrinfo` in a separate resolver tread.

When it gets a list of addresses back, it will connect to them one bye one until one of them works. In a dual-stack (IPv4 + IPv6) setup, it uses "happy eyeballs" which races two connections (one IPv4 and one IPv6) with each other at the same time and it goes with the one that connects first and discards the slower one.

[getaddrinfo() does *not* return the addresses in a "round-robin" fashion](https://daniel.haxx.se/blog/2012/01/03/getaddrinfo-with-round-robin-dns-and-happy-eyeballs/). It is not curl's fault.

To aid applications to still achieve something in that vein, libcurl offers [CURLOPT_DNS_SHUFFLE_ADDRESSES](https://curl.haxx.se/libcurl/c/CURLOPT_DNS_SHUFFLE_ADDRESSES.html). This option is not (yet?) exposed to users in the curl tool.
