### ISSUE TITLE
Build issues on AIX with version 7.66.0

### ISSUE THREAD

**Issue by aixtools** [curl/curl#4390]
### I did this
```
AIX does not have AF_LOCAL in socket.h

I modified <sys/socket.h> to include AF_LOCAL

/*
 * Level number for (get/set)sockopt() to apply to socket itself.
 */
#define SOL_SOCKET      0xffff          /* options for socket level */

/*
 * Address families.
 */
#define AF_UNSPEC       0               /* unspecified */
#define AF_UNIX         1               /* local to host (pipes, portals) */
#define AF_LOCAL        AF_UNIX
#define AF_INET         2               /* internetwork: UDP, TCP, etc. */
#define AF_IMPLINK      3               /* arpanet imp addresses */

After this change the build fails with:

+ /opt/bin/make > .buildaix/make.out
ld: 0711-317 ERROR: Undefined symbol: .curl_multi_poll
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.

The configure statement I use(d) is:

==> curl-7.65.0/config.log <==
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by curl configure -, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ../src/curl-7.65.0/configure --prefix=/opt --sysconfdir=/var/curl/etc --sharedstatedir=/var/curl/com --localstatedir=/var/curl --mandir=/usr/share/man --infodir=/opt/share/info/curl --with-ca-bundle=/var/ssl/cacert.pem --with-libssh2=/opt --with-zlib=/opt --enable-ldap --enable-ldaps --with-ldap=/opt

==> curl-7.66.0/config.log <==
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by curl configure -, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ../src/curl-7.66.0/configure --prefix=/opt --sysconfdir=/var/curl/etc --sharedstatedir=/var/curl/com --localstatedir=/var/curl --mandir=/usr/share/man --infodir=/opt/share/info/curl --with-ca-bundle=/var/ssl/cacert.pem --with-libssh2=/opt --with-zlib=/opt --enable-ldap --enable-ldaps --with-ldap=/opt


```

### I expected the following
A successful build

### operating system

AIX 6.1 (my build system). The issue with AF_LOCAL is the same on AIX 7.1

**Comment by bagder** [comment]
Ack, this was also an issue on Solaris and we fixed in in #4333. Can you check if that fixes your problem?

**Comment by aixtools** [comment]
Without the change I get, as expected:

+ /opt/bin/make > .buildaix/make.out
"../../src/curl-7.66.0/lib/asyn-thread.c", line 248.17: 1506-045 (S) Undeclared identifier AF_LOCAL.

After applying the change I get:
+ /opt/bin/make > .buildaix/make.out
ld: 0711-317 ERROR: Undefined symbol: .curl_multi_poll
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.

Now I am at home -- the additional out put is:

...
FILELIST: Number of previously inserted files processed: 57
(ld): resolve
RESOLVE: 539 of 15061 symbols were kept.
(ld): addgl /usr/lib/glink.o
ADDGL: Glink code added for 119 symbols.
(ld): er full
ld: 0711-318 ERROR: Undefined symbols were found.
        The following symbols are in error:
 Symbol                    Inpndx  TY CL Source-File(Object-File) OR Import-File{Shared-object}
                              RLD: Address  Section  Rld-type Referencing Symbol
 ----------------------------------------------------------------------------------------------
 .curl_multi_poll          [170]   ER PR ../../src/curl-7.66.0/src/tool_operate.c(curl-tool_operate.o)
                                   000005a4 .text    R_RBR    [18]    <.parallel_transfers>
ER: The return code is 8.

root@x066:[/data/prj/aixtools/curl/curl-7.66.0/src]Wl,-blibpath:/opt/lib:/usr/vac/lib:/usr/lib:/lib -bloadmap:mamfelt.map                                             <
ld: 0711-317 ERROR: Undefined symbol: .curl_multi_poll
ld: 0711-344 See the loadmap file mamfelt.map for more information.

File is added as mamfelt.map.txt
[mamfelt.map.txt](https://github.com/curl/curl/files/3638706/mamfelt.map.txt)

**Comment by bagder** [comment]
>  ld: 0711-317 ERROR: Undefined symbol: .curl_multi_poll

`curl_multi_poll()` is a new function added in 7.66.0.

**Comment by aixtools** [comment]
Ah. And I thought it had been around for a long time. :)

So, when I have some time I'll look for the file with the function and send the compiler listing.

Still on me for now.

**Comment by aixtools** [comment]
Resolved - for now.

There may still be a minor issue around the build process - as my resolution was to uninstall an older version of curl. It appears the linker was accessing the old library - lacking in `curl_multi_poll `support.

So, after manual application of #4333 and linking with no curl installed, curl built successfully,

Running tests now. Will update, and then. I expect, close issue.

**Comment by aixtools** [comment]
Sadly - to me - did not pass all tests. That will be a new issue when I have more time to research. For now, just the summary.

Warning: dict server unexpectedly alive
TESTDONE: 975 tests out of 979 reported OK: 99%
TESTFAIL: These test cases failed: 168 1435 1436 1452
TESTDONE: 1266 tests were considered during 696 seconds.
