### ISSUE TITLE
Building on Windows using nmake with WinSSL fail to use HTTP2

### ISSUE THREAD

**Issue by bennyAv10** [curl/curl#4391]
### I did this
I followed the instructions on [BUILD.WINDOWS.txt](https://github.com/curl/curl/blob/master/winbuild/BUILD.WINDOWS.txt)

Here is my build commands:
```
nmake -f Makefile.vc mode=dll MACHINE=x64 WITH_DEVEL=c:/curl/curl-7.56.1/deps WITH_NGHTTP2=dll WITH_ZLIB=static WITH_SSH2=dll
```

### I expected the following
Running `curl -V` and http2 appears on the feature list, but when running `.\curl -http2 -I https://nghttp2.org/` to use HTTP2, but it keeps using HTTP1.1.

```
curl --http2 -I https://nghttp2.org/
HTTP/1.1 200 OK
Date: Sat, 21 Sep 2019 00:30:57 GMT
Content-Type: text/html
Last-Modified: Mon, 19 Aug 2019 13:20:36 GMT
Etag: "5d5aa224-19d8"
Accept-Ranges: bytes
Content-Length: 6616
X-Backend-Header-Rtt: 0.00102
Strict-Transport-Security: max-age=31536000
Server: nghttpx
Via: 2 nghttpx
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
```

The issue is similar to #2591, which is solved since 7.61, but the solution only works if you build with CMake but not when following the instructions on [BUILD.WINDOWS.txt](https://github.com/curl/curl/blob/master/winbuild/BUILD.WINDOWS.txt).

To recapture, using OpenSSL or building with CMake HTTP2 works, but using nmake isn't.

### curl/libcurl version
7.64.1

[curl -V output]
```
curl 7.64.1 (x86_64-pc-win32) libcurl/7.64.1 Schannel zlib/1.2.11 WinIDN libssh2/1.8.2 nghttp2/1.32.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI libz
```

### operating system
Windows 10 build 18362.356

**Comment by jay** [comment]
I assume you mean `--http2` and not `-http2`. http2 in schannel is only supported with a recent sdk, as far as I know

https://github.com/curl/curl/blob/9cd755e1d768bbf228e7c9faf223b7459f7e0105/lib/vtls/schannel.c#L68-L75

/cc @JDepooter @MarcelRaad

**Comment by bagder** [comment]
In the non-functional build, what does curl -v show against for example `https://nghttp2.org/` ? Is it the `HAS_ALPN` condition that isn't right? 

https://github.com/curl/curl/blob/0801343e27d4540afcdbbd8fe46aabaddd9da321/lib/vtls/schannel.c#L73-L75

**Comment by JDepooter** [comment]
I believe the problem is that there is no manifest embedded in the exe. Most of the work to add manifest embedding was done in pull #1221, but the changes to the `CURL_RC_FLAGS` value were being overwritten later in the makefile.

I have created a pull request which I believe will solve this problem:
https://github.com/curl/curl/pull/4399
I haven't tested with nghttp2, but I can verify that with this change there is a manifest in the exe.

**Comment by bennyAv10** [comment]
First, thanks all for replying.

1.
@JDepooter, I've tried your commit from https://github.com/curl/curl/pull/4399 pull request, and it worked. Thanks!

2.
@jay: Yes, I meant `--http2`. For the Windows SDK version, I beleive Windows 10 18362 is new enough. My MSVC version is  19.22.27905.

3.
@bagder: The output I pasted above is for non working curl:
```
curl 7.64.1 (x86_64-pc-win32) libcurl/7.64.1 Schannel zlib/1.2.11 WinIDN libssh2/1.8.2 nghttp2/1.32.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI libz
```

The output for the working curl (The one built with CMake):
```
curl 7.64.1 (Windows) libcurl/7.64.1 Schannel zlib/1.2.10 nghttp2/1.32.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS HTTP2 IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI libz
```
