### ISSUE TITLE
Compile/Linker error when compiling for iOS with OpenSSL 1.1.1d

### ISSUE THREAD

**Issue by sk2212** [curl/curl#4419]
### I did this
Compile libcurl for iOS 12.4 wit OpenSSL 1.1.1d:

  ARCH=$1
  HOST=$2
  SYSROOT=$3
  PREFIX=$4
  IPHONEOS_DEPLOYMENT_TARGET="12.4"
  export PATH="${DEVROOT}/usr/bin/:${PATH}"
  export CFLAGS="-DCURL_BUILD_IOS -arch ${ARCH} -pipe -Os -gdwarf-2 -isysroot ${SYSROOT} -miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET} -fembed-bitcode"
  export LDFLAGS="-arch ${ARCH} -isysroot ${SYSROOT}"
  CPPFLAGS="-I/${HOME}/libcurl_tmp/openssl/include" LDFLAGS="-L/${HOME}/libcurl_tmp/openssl/macos_ios" ./configure --disable-shared --without-zlib --enable-static --with-ssl --enable-ipv6 --host="${HOST}" --prefix=${PREFIX} && make -j8 && make install

### I expected the following
libcurl compiled successfully
### curl/libcurl version
7.65.3
[curl -V output]

### operating system
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

I got following error during compile/linking:
Undefined symbols for architecture arm64:
  "_ENGINE_by_id", referenced from:
      _Curl_ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_ctrl", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_ctrl_cmd", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_finish", referenced from:
      _Curl_ossl_close_all in libcurl.a(libcurl_la-openssl.o)
      _Curl_ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_free", referenced from:
      _Curl_ossl_close_all in libcurl.a(libcurl_la-openssl.o)
      _Curl_ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_first", referenced from:
      _Curl_ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_id", referenced from:
      _Curl_ossl_set_engine_default in libcurl.a(libcurl_la-openssl.o)
      _Curl_ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_get_next", referenced from:
      _Curl_ossl_engines_list in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_init", referenced from:
      _Curl_ossl_set_engine in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_load_builtin_engines", referenced from:
      _Curl_ossl_init in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_load_private_key", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
  "_ENGINE_set_default", referenced from:
      _Curl_ossl_set_engine_default in libcurl.a(libcurl_la-openssl.o)

Configure Setup:
  Host setup:       arm-apple-darwin
  Install prefix:   /Local/Users/technisat/libcurl_tmp/build_libcurl/arm64
  Compiler:         gcc
   CFLAGS:          -DCURL_BUILD_IOS -arch arm64 -pipe -Os -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=12.4 -fembed-bitcode -Qunused-arguments -Werror=partial-availability
   CPPFLAGS:        -isystem //Local/Users/technisat/libcurl_tmp/openssl/include
   LDFLAGS:         -L//Local/Users/technisat/libcurl_tmp/openssl/macos_ios
   LIBS:            -lssl -lcrypto

  curl version:     7.65.3
  SSL:              enabled (OpenSSL)
  SSH:              no      (--with-libssh2)
  zlib:             no      (--with-zlib)
  brotli:           no      (--with-brotli)
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          enabled
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          no      (--enable-alt-svc)
  HTTP2:            disabled (--with-nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         SSL IPv6 UnixSockets AsynchDNS NTLM NTLM_WB TLS-SRP HTTPS-proxy

OpenSSL is built like this:
./Configure ios64-cross --prefix=$(pwd)/temp_build/ -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -O3 -fomit-frame-pointer -fno-common -Wall -DOPENSSL_NO_ASM -DOPENSSL_NO_INLINE_ASM -no-shared

**Question**
What is OpenSSL Engine used for in libcurl? Is it fine to compile with "-DOPENSSL_NO_ENGINE" for iOS platform?

P.S:
OpenSSL version 1.0.2t is working fine.

**Comment by pps83** [comment]
> **Question**
> What is OpenSSL Engine used for in libcurl? Is it fine to compile with "-DOPENSSL_NO_ENGINE" for iOS platform?

AFAIK engine cannot be used, as it requires DSO, which isn't available on iOS.

**Comment by sk2212** [comment]
> > **Question**
> > What is OpenSSL Engine used for in libcurl? Is it fine to compile with "-DOPENSSL_NO_ENGINE" for iOS platform?
> 
> AFAIK engine cannot be used, as it requires DSO, which isn't available on iOS.

So, it is save to compile with "-DOPENSSL_NO_ENGINE"?

**Comment by sk2212** [comment]
*Ping*

**Comment by pps83** [comment]
You cannot have DSO and cannot have engine as a result. OpenSSL builds scripts always disable it for iOS:
https://github.com/openssl/openssl/blob/master/Configurations/15-ios.conf#L13

**Comment by sk2212** [comment]
Thanks for reply. But this does not answer my question:

So, it is save to compile with "-DOPENSSL_NO_ENGINE"?

**Comment by pps83** [comment]
> Thanks for reply. But this does not answer my question:
> 
> So, it is save to compile with "-DOPENSSL_NO_ENGINE"?

I'll repeat what I wrote before: AFAIK engine cannot be used, as it requires DSO, which isn't available on iOS.
Also I wrote: You cannot have DSO and cannot have engine as a result. OpenSSL build scripts always disable it for iOS.
This means that you have two choices: either you cannot build OpenSSL if you insist on having ossl engine, or you build openssl as usual, as openssl itself configures iOS builds (eg without engine).
Is that safe?.. Ask OpenSSL mailing list if their default iOS config is "safe". Your other option is to be "safe" without OpenSSL. The point is: you cannot have openssl engine on iOS, that's it.

**Comment by bagder** [comment]
I don't see anything more for us to act on here.

**Comment by ugochirico** [comment]
@pps83 as in my knowledge, on iOS you cannot have dynamic engine but you can have static engine implemented in your app.
I'm trying to use libcurl with openssl and a static engine on iOS.
I've already built openssl with static engine support and wrote my engine.
Now I need to build libcurl with engine support for iOS. How can I do that?
