### ISSUE TITLE
cookie engine enabled without asked to

### ISSUE THREAD

**Issue by bagder** [curl/curl#4429]
### I did this

curl $URL $URL

... where the $URL sets a cookie.

### I expected the following

No cookie would be sent in the second request, but it actually is!

This is likely to be a regression from 7.66.0 when this is using the share interface as compared to how things worked before.

### curl/libcurl version

7.66.0

### operating system

Any

**Comment by jay** [comment]
bisected to b889408 `curl: support parallel transfers`
cookie engine is enabled for both transfers
from master:
https://github.com/curl/curl/blob/9cd755e1d768bbf228e7c9faf223b7459f7e0105/src/tool_operate.c#L2294-L2298
https://github.com/curl/curl/blob/9cd755e1d768bbf228e7c9faf223b7459f7e0105/lib/share.c#L78-L88

**Comment by bagder** [comment]
Yes exactly. But I think it is an API problem/misbehavior that this curl change brought into light, so that is where I've done my fix for this in #4434 .
