### ISSUE TITLE
HTTP redirect not working... hangs

### ISSUE THREAD

**Issue by nesc1** [curl/curl#4432]
using curl version 7.66

### I did this
curl.exe "http://img.youtube.com/vi/_k3Rb19PGLk/mqdefault.jpg" --output f -v

### I expected the following
image downloaded to f file

### curl/libcurl version
curl 7.66.0 (x86_64-pc-win32) libcurl/7.66.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

### operating system
Windows 10

I think the problem is that the redirect handling is not working, because if i try with https version it worked fine.

Best regards,
Nuno

**Comment by bagder** [comment]
1. It has nothing to do with HSTS (which curl doesn't support)
2. There's no redirect here (for me)
3. That command line works for me with the Linux version of 7.66.0, it gets a JPEG file that's 320x180 pixels.

You say it "hangs". At what point does it stop? Can you show us the last 10-20 lines of output before that point?

**Comment by jay** [comment]
works for me as well, tested builds with openssl and schannel

**Comment by nesc1** [comment]
@bagder yes i know that it works on Linux, the issue clearly indicates that is in a windows 10 problem.
@jay in each operating system did you tested?

**Comment by bagder** [comment]
>  i know that it works on Linux

You did not indicate that in your description.

> HTTP redirect not working... 

There's no redirect!

**Comment by nesc1** [comment]
hi @bagder my opera browser says it does:

![image](https://user-images.githubusercontent.com/23531252/65755118-614efd80-e10a-11e9-8805-118c0581811d.png)

**Comment by bagder** [comment]
Your browser is lying.

I run `curl -I http://img.youtube.com/vi/_k3Rb19PGLk/mqdefault.jpg` and this is the response:
~~~
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 15868
Timing-Allow-Origin: *
Date: Fri, 27 Sep 2019 08:40:59 GMT
Expires: Fri, 27 Sep 2019 08:45:59 GMT
Cache-Control: public, max-age=300
ETag: "1569435991"
X-Content-Type-Options: nosniff
Server: sffe
X-XSS-Protection: 0
~~~

I **guess** your browser's "Internal Redirect" is due to it having a HSTS header for that site/domain already and thus upgrades it to HTTPS. It's not a HTTP redirect though.

**Comment by nesc1** [comment]
ok... so in this side and on my machine something is wrong as you can see:
```
λ curl.exe -V
curl 7.66.0 (x86_64-pc-win32) libcurl/7.66.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

λ curl.exe "http://img.youtube.com/vi/_k3Rb19PGLk/mqdefault.jpg" --output f -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 216.58.201.174:80...
* TCP_NODELAY set
* Connected to img.youtube.com (216.58.201.174) port 80 (#0)
> GET /vi/_k3Rb19PGLk/mqdefault.jpg HTTP/1.1
> Host: img.youtube.com
> User-Agent: curl/7.66.0
> Accept: */*
>
  0     0    0     0    0     0      0      0 --:--:--  0:01:25 --:--:--     0
```
... and it stays here ... it's not normal 1:25 trying to download a small image right

Is there any way of sending to you a more detail log? that can help you see what is the problem?

Thanks for the atention.
Regards

**Comment by bagder** [comment]
Maybe not normal but you get the progress meter there and it shows curl sitting there idling its thumbs waiting for data to come and none is coming. That's far from clear that curl is doing anything wrong at all! If you change the URL to use `https://` instead, does that work?

I presume it also works fine if you do `curl -I [URL]` ?

**Comment by nesc1** [comment]
yes with -I it works... and in another machin (win7) it worked without -I... so i'm guessing that is machine problem related...

**Comment by bagder** [comment]
Anti-virus? Something else interfering with the traffic?

**Comment by nesc1** [comment]
don't know.. but that is strange why opera redirects to https...
thanks for the help i will try to understand the problem with my machine

**Comment by bagder** [comment]
Opera and most modern browsers redirect to HTTPS automatically by themselves since it has a preloaded list of HSTS domains to do that for. And if they're not preloaded they can be set when visiting HTTPS sites. curl does not (yet) have that ability. (There's initial work on support for HSTS in #4126 )
