### ISSUE TITLE
Secure Transport Certificate Revoked or Chain Invalid

### ISSUE THREAD

**Issue by georgeok** [curl/curl#4436]
### I did this
`curl -vvv https://revoked.grc.com` and curl report an `Invalid certificate chain` error while Chrome and Safari report a `Revoked Certificate` error which I think it's the correct error for this url.

### I expected the following
Curl to report the SSL Revoked error. On Windows (VM on the same machine) `curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_REVOKED (0x80092010) - The certificate is revoked` is reported in contrast.

On macOS calling [SSLHANDSHAKE(...)](https://github.com/curl/curl/blob/master/lib/vtls/sectransp.c#L2360) returns [errSSLXCertChainInvalid](https://github.com/curl/curl/blob/master/lib/vtls/sectransp.c#L2429) instead of [errSSLPeerCertRevoked](https://github.com/curl/curl/blob/master/lib/vtls/sectransp.c#L2456).

### curl/libcurl version
```
curl 7.64.1 (x86_64-apple-darwin18.2.0) libcurl/7.64.1 SecureTransport zlib/1.2.11
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```
### Output
```
curl -vvv https://revoked.grc.com
*   Trying 4.79.142.205...
* TCP_NODELAY set
* Connected to revoked.grc.com (4.79.142.205) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: Invalid certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### operating system
`macOS mojave` and `macOS Sierra` and possibly other mac versions

**Comment by nickzman** [comment]
There's not much we can do about this. SSLHandshake() is Apple's function, not ours. If it returned errSSLPeerCertRevoked like it probably should have done, then the error message produced by libcurl would be more accurate.

You could file a ticket with Apple, but since they deprecated Secure Transport recently, I wonder if they'll ever address it.

And in case you're wondering, Safari switched from Secure Transport to BoringSSL about 1-2 years ago.
