### ISSUE TITLE
curl: symbol lookup error: curl: undefined symbol: curl_mime_free

### ISSUE THREAD

**Issue by hongyi-zhao** [curl/curl#4448]
The latest git version:

```
$ curl -V
curl 7.67.0-DEV (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2s zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
curl: symbol lookup error: curl: undefined symbol: curl_mime_free

$ curl www.baidu.com
curl: (48) An unknown option was passed in to libcurl
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
```

How to solve it?

**Comment by dfandrich** [comment]
On Tue, Oct 01, 2019 at 04:09:22AM -0700, hongyi-zhao wrote:
> The latest git version:
> 
> $ curl -V
> curl 7.67.0-DEV (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2s zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
                                        ^^^^^^^^^^^^^^
There's the problem—curl was built from git but it's using an older libcurl.
You need to make sure the executable built from git is using the libcurl built
from git by e.g., using LD_LIBRARY_PATH or -rpath when linking.

**Comment by hongyi-zhao** [comment]
I don't have experience on using this option for curl compile.   Could you please give  the corresponding commands?

**Comment by dfandrich** [comment]
The quickest way around the problem is to run curl with:

  LD_LIBRARY_PATH=/path/to/your/libcurl curl www.baidu.com

where the file /path/to/your/libcurl/libcurl.so.4 is your home-built libcurl.

**Comment by hongyi-zhao** [comment]
Still not so clear.  

I only using the make to make curl, and don't know how to  make libcurl.

**Comment by hongyi-zhao** [comment]
Got it, the make will also make libcurl and put it in the following location:
LD_LIBRARY_PATH=/usr/local/lib curl www.baidu.com

Regards

**Comment by mfernea** [comment]
This might help https://gist.github.com/fideloper/f72997d2e2c9fbe66459

**Comment by winkee01** [comment]
This might help.
![libcurl_problem](https://user-images.githubusercontent.com/49930785/74834445-61b89100-5356-11ea-8233-f0cd1c506a2f.png)

**Comment by Joeycho** [comment]
@winkee01 

Yes, your screenshot saved me! :)
