### ISSUE TITLE
~43ms delay between WRITEFUNCTION callback when using curl_easy_reset or curl multi

### ISSUE THREAD

**Issue by deadeyegoodwin** [curl/curl#4450]
### I did this
Using curl_easy interface to send multiple requests, where each
request gets a newly created CURL object (using curl_easy_init), I see
that the WRITEFUNCTION callback is called at a reasonable rate. In
this case my WRITEFUNCTION callback takes a timestamp and does about
60us of work.

Request 0:
WRITEFUNCTION: 16080 bytes, microseconds 1569945516350512
WRITEFUNCTION: 16384 bytes, microseconds 1569945516350610   <-- 98us between callbacks
WRITEFUNCTION: 16384 bytes, microseconds 1569945516350677   <-- 67us between callbacks
WRITEFUNCTION: 16384 bytes, microseconds 1569945516350745   <-- 68us between callbacks
WRITEFUNCTION: 353 bytes,   microseconds 1569945516350808   <-- 63us between callbacks

Request 1:
WRITEFUNCTION: 16080 bytes, microseconds 1569945516351692
WRITEFUNCTION: 16384 bytes, microseconds 1569945516351790   <-- 98us
WRITEFUNCTION: 16384 bytes, microseconds 1569945516351857   <-- 67us
WRITEFUNCTION: 16384 bytes, microseconds 1569945516351922   <-- 65us
WRITEFUNCTION: 353 bytes,   microseconds 1569945516351985   <-- 63us

I see similar results over subsequent requests. Note how the interval
between WRITEFUNCTION callbacks is very consistent.

But if I use a single CURL object and instead use curl_easy_reset in
between requests, or if I use the curl multi interface I instead see
this:

Request 0:
WRITEFUNCTION: 16080 bytes, microseconds 1569947091464718
WRITEFUNCTION: 16384 bytes, microseconds 1569947091464897   <-- 179us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091464992   <-- 95us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091465106   <-- 114us
WRITEFUNCTION: 353 bytes,   microseconds 1569947091465189   <-- 83us

Request 1:
WRITEFUNCTION: 16080 bytes, microseconds 1569947091465886
WRITEFUNCTION: 16384 bytes, microseconds 1569947091509163   <-- 43277us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091509253   <-- 90us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091509343   <-- 90us
WRITEFUNCTION: 353 bytes,   microseconds 1569947091509410   <-- 67us

Request 2:
WRITEFUNCTION: 16080 bytes, microseconds 1569947091510036
WRITEFUNCTION: 16384 bytes, microseconds 1569947091553158   <-- 43122us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091553225   <-- 67us
WRITEFUNCTION: 16384 bytes, microseconds 1569947091553302   <-- 77us
WRITEFUNCTION: 353 bytes,   microseconds 1569947091553368   <-- 66us

Note that the first curl-easy performed/completed by the curl multi
has callback intervals that are a little longer than the first case
but otherwise ok. But the second and subsequent requests have a long
~43ms delay between the first callback and the second.

Curiously the delay does not occur between the requests. For example,
the time between the last callback for the first request
(1569947091465189) and the first callback for the next request
(1569947091465886) is 697us.

In all cases the curl-easy setopts are identical, and we are setting
CURLOPT_TCP_NODELAY = 1L (but I didn't see it make a difference either
way).

### I expected the following
curl multi behavior should be the same as curl-easy in that there should be no large delay between WRITEFUNCTION callbacks.

### libcurl version
curl-7_66_0

### operating system
ubuntu 18.04

**Comment by bagder** [comment]
That's certainly puzzling. The code-paths taken should be identical after it has gotten the handles created and setup different ways, for all I can think of.

Can you share the code you've used for this so that we can see if we can reproduce in our ends?

I figure we need to dive deeper and start to narrow in exactly what it does during all that time! I presume this is a larger download so it is certain that there actually is incoming data to read but it just doesn't happen fast enough for some reason?

**Comment by deadeyegoodwin** [comment]
I will work on a simple repo (currently it is embedded in a larger app, https://github.com/NVIDIA/tensorrt-inference-server). Each request is 64k bytes as shown above and it always is delivered by 5 callbacks... it is just the timing that differs.

**Comment by deadeyegoodwin** [comment]
I started working on a repo and from that I discovered that it was actually a configuration issue on the server side. It took some time to diagnose because by changing the client I could get good results from the server. Anyway, there is nothing to be done here for now. Thanks.

**Comment by bagder** [comment]
Ah, glad to know you figured it out and also that it wasn't actually a problem in curl! :grin:
