### ISSUE TITLE
curl --parallel -v --max-redirs 2 -L --http3 infinite loop 

### ISSUE THREAD

**Issue by puzza007** [curl/curl#4451]
### I did this

```shell
curl --parallel  -v --max-redirs 2 -L  --http3 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6 https://cloudflare-quic.com/b/redirect/6
```

A strange request but I'm having issues with http3 concurrency in my library and wanted to see if I could reproduce using the command line app.

### I expected the following

Command to finish

### What happened

In ~1/10 attempts curl seemed to get into an infinite loop. Logs available https://gist.github.com/puzza007/0187dbd0a554e69c57a6434f282233eb.

The error `Send failure: Bad file descriptor` led me to try stracing and `truss` seems to show the same syscall (and error) being repeatedly called in both `curl` and my app e.g.:

```
sendto(0xFFFFFFFFFFFFFFFF, 0x104AAD000, 0x6A)		 = -1 Err#9
```

### curl/libcurl version

git `ac830139`

```shell
curl -V
curl 7.67.0-DEV (x86_64-apple-darwin18.7.0) libcurl/7.67.0-DEV BoringSSL zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 nghttp2/1.39.2 quiche/0.1.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

### operating system

OSX

**Comment by bagder** [comment]
I suspect this is because we have not made the HTTP/3 transfers get multiplexed properly (with either backend). Mentioned on the [HTTP3 state](https://github.com/curl/curl/wiki/HTTP3) page in the wiki.

**Comment by puzza007** [comment]
Ah I missed this - sorry! Feel free to close.

**Comment by bagder** [comment]
Yes, I think I'll do that and we make sure to come back to testing this out once we have code that is meant to deal with it! Thanks.
