### ISSUE TITLE
Building static library on windows with llvm toolset, MANIFEST:NO linker option is passed and build fails. 

### ISSUE THREAD

**Issue by mardanmustak** [curl/curl#4464]
### I did this
Compiled libcurl conan package on windows vs2017 using llvm toolset(1.0.363769) and clang as compiler.  In Latest llvm toolset <UseLlvmLib> is turned on by default, which would fail to recognize /MANIFEST:NO option when compiled as static library. 

#### I expected the following
libcurl to be compiled .  

In CMakeLists.txt:1118 line needs to be modified 
Fault code: 
  # Disable default manifest added by CMake
 set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO")
Compiled code: 
  # Disable default manifest added by CMake
  if(ENABLE_SHARED)
	set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO")
  endif() 

### curl/libcurl version
libcurl 7.66.0 
llvm-lib.exe version 8.0.1
llvm toolset(1.0.363769) 
[curl -V output]

### operating system
Windows 10

**Comment by bagder** [comment]
I don't understand. Is that a change you suggest we add? The build does work for a lot of platforms and compilers though, shouldn't that change then be conditional on some specific condition for this case only?

**Comment by bagder** [comment]
No response or clarification.
