### ISSUE TITLE
Division by zero in Curl_now

### ISSUE THREAD

**Issue by liuaifu** [curl/curl#4472]
### I did this
My program has been run thousands of times and has now found a crash in libcurl. My code was developed on the basis of the sample.
### I expected the following
no crash
### curl/libcurl version
curl-7.66.0
[curl -V output]
STACK_TEXT:  
06d4f650 6833ac93 082a499e 00000001 00000000 downloader!_alldvrm+0x4e
06d4f67c 6832d28f 06d4f694 04dae570 04da3640 downloader!Curl_now+0x33
06d4f6a4 6832a14f 04da3640 06d4f6ec 04da3640 downloader!Curl_resolver_is_resolved+0x9f
06d4f708 68329381 04d12ef8 0000058d 00000000 downloader!multi_runsingle+0x38f
06d4f74c 683248d8 04d12ef8 06d4f768 04d12ef8 downloader!curl_multi_perform+0x71
06d4f76c 6832487a 04d12ef8 04f10af0 04e52230 downloader!easy_transfer+0x38
06d4f784 6832473d 04da3640 00000000 06d4f878 downloader!easy_perform+0xca
06d4f794 68321c01 04da3640 04da3640 0000003c downloader!curl_easy_perform+0xd
### operating system
win7 sp1 7601

**Comment by bagder** [comment]
This hasn't triggered before. I presume this is the code that runs: 

https://github.com/curl/curl/blob/63791638779778d390f9722a1b47c76f5321741b/lib/timeval.c#L34-L39

So in this case `QueryPerformanceCounter()` must've returned with a zero `Curl_freq.QuadPart` and then it goes totally wrong.

The [documentation for this function](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter) says:

> On systems that run Windows XP or later, the function will always succeed and will thus never return zero.

... which then leaves us wondering: what happened here?

The division is also what MS use themselves in this [more tutorial like docs page for high resolution timers](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps).

**Comment by jay** [comment]
> My program has been run thousands of times and has now found a crash in libcurl.

This is weird because how would it be zero just that once and work the other times? Possibly some corruption in your program?

> The [documentation for this function](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter) says:

I assume you meant [QueryPerformanceFrequency](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency) which writes Curl_freq.QuadPart just once. It is documented the same never to fail (ie return zero) but more importantly, that the param Curl_freq will never receive zero:

_"If the installed hardware doesn't support a high-resolution performance counter, this parameter can be zero (this will not occur on systems that run Windows XP or later)."_

**Comment by liuaifu** [comment]
I have reviewed thread safety guidelines, I have not call curl_global_init, but curl_easy_init, and not set CURLOPT_NOSIGNAL. Now, I have add it, hope doesn't crash again. Thank you, @jay.

**Comment by jay** [comment]
Sure. Note curl_easy_init will call curl_global_init if curl was not initialized. So another way it could happen is if two threads call curl_easy_init when curl_global_init wasn't called to initialize curl beforehand.

Also it is just a theory I do not know for certain. I walked through QueryPerformanceFrequency in user mode and it does not zero out Curl_freq before assigning, instead it does a syscall and passes the Curl_freq address to kernel but I didn't debug kernel.
