### ISSUE TITLE
Incorrect windows version

### ISSUE THREAD

**Issue by mcrndonnager** [curl/curl#4473]
### I did this
Downloaded curl for windows from https://curl.haxx.se/windows/

### I expected the following
Was expecting 7.66.0 which has options for parallel downloads; however, option -Z/--parallel is not available, and when running curl.exe -V it says that it's 7.55.1, even though it's posted on the website as 7.66.

### curl/libcurl version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

[curl -V output]

### operating system
windows 10

**Comment by bagder** [comment]
That's because you then run the curl version shipped with Windows itself and not the one you just downloaded.

**Comment by mcrndonnager** [comment]
Oops my bad - thanks!
