### ISSUE TITLE
Confusing help for --no-progress-meter

### ISSUE THREAD

**Issue by infinnovation-dev** [curl/curl#4474]
Although I'm fully in favour of a new option to disable the progress indication, I think the help is a little confusing.  (I do appreciate that retro-fitting this sort of thing while maintaining historical compatibility is tricky.)

It is shown as

     --progress-meter Show the progress meter

but the user is only likely to want --no-progress-meter

It's not even clear that the "no-" variant is available (especially since the help explicitly lists other default-on options in the negative sense: --no-alpn, --no-buffer etc.)

The user might also be forgiven for thinking that "bar" and "meter" are two styles of progress indication, and would therefore be surprised that

    curl --progress-bar --no-progress-meter $URL

and

    curl --progress-meter --no-progress-bar $URL

are not symmetrical.

I would prefer something like

    --[no-]progress   Show or hide the progress indicator
    --progress-bar    Display progress as a bar

and maybe even

    --progress-meter  Display progress as a meter

### curl/libcurl version

curl 7.67.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.67.0-DEV OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Debug HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TrackMemory UnixSockets

### operating system

Scientific Linux 7.4 (Nitrogen)

**Comment by bagder** [comment]
Thanks for the quick feedback on this new option docs. I think you're right and I documented it like this to avoid documenting the negative version of the option but after your issue I noticed we actually already do that for a few others so it wouldn't be the first. How about we instead document it like this in the man page:
~~~
       --no-progress-meter
              Option to switch off the progress meter output without muting or other‐
              wise  affecting  warning  and  informational messages like -s, --silent
              does.

              Note that this is the negated option name documented. You can thus  use
              --progress-meter to enable the progress meter again.

              See also -v, --verbose and -s, --silent. Added in 7.67.0.
~~~
PR coming right up.
