### ISSUE TITLE
CURLOPT_SHARE for alt-svc

### ISSUE THREAD

**Issue by candrews** [curl/curl#4476]
### I did this
There is no `CURLOPT_SHARE` option for ALTSVC (see https://ec.haxx.se/libcurl-sharing.html). Ideally, the alt-svc cache (configured using the `CURLOPT_ALTSVC` and `CURLOPT_ALTSVC_CTRL` options) should be shareable in the same way as the cookie and DNS caches.

### I expected the following
A way to share the ALTSVC cache using `CURLOPT_SHARE`.

### curl/libcurl version
```
$ curl -V
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libssh2/1.9.0 nghttp2/1.39.2 librtmp/2.3
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Largefile libz Metalink NTLM SSL TLS-SRP UnixSockets
```

### operating system
Linux

**Comment by bagder** [comment]
I completely agree that this is needed to make the ALTSVC support really cool.
