### ISSUE TITLE
Run web-platform-tests url tests and compare results with browsers on wpt.fyi

### ISSUE THREAD

**Issue by zcorpan** [curl/curl#4477]
### I did this

I visited https://wpt.fyi/results/url?label=experimental&label=master&aligned

### I expected the following

Expected to see `curl` test results. Well, not really, but I think it would be interesting to have.

Context: https://twitter.com/zcorpan/status/1181869515195535360

> I assume you'd need a custom runner, similar to https://github.com/web-platform-tests/wpt/blob/master/url/resources/a-element.js but using libcurl API.
The format that https://wpt.fyi results receiver expects is documented here https://github.com/web-platform-tests/wpt.fyi/blob/master/api/README.md#results-creation

This could allow finding the interesting differences, find real-world URLs in httparchive or something for those, and make a case to change either curl or browsers to improve both web compat and interop for URLs. Or possibly just spark some renewed interest from browsers to improve interop for URLs.

**Comment by bagder** [comment]
This basically requires a little program that performs these steps:
1. the [JSON input])(https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json) is read
2. iterate over all URL tests (they're almost 400 different ones)
3. for each test, the input URL is passed to `curl_url_set()`
4. the parsed results from that call is compared to the JSON fields for that test
5. output match/not match
6. loop

Done!
