### ISSUE TITLE
crash on query_completed_cb

### ISSUE THREAD

**Issue by ericwuseattle** [curl/curl#4478]
The crash happening callback If resolving DNS get canceled.

crashing on this line "res->num_pending--";
https://github.com/curl/curl/blob/curl-7_66_0/lib/asyn-ares.c#L540

res is invalid address coming from `res = (struct ResolverResults *)conn->async.os_specific`
~~~
(gdb) print conn->async
$3 = {hostname = 0x21 <Address 0x21 out of bounds>, port = 8, dns = 0x7497ff0, done = 64, status = 0, os_specific = 0x21}
~~~

How do you think change the code into
~~~c
if (status == ARES_EDESTRUCTION || status == ARES_ECANCELLED)
~~~
https://github.com/curl/curl/blob/curl-7_66_0/lib/asyn-ares.c#L533

Thanks,
Eric

**Comment by bagder** [comment]
Can you please help us reproduce this problem first? I don't see any logic in c-ares that would make such a special cases needed for `ARES_ECANCELLED` and I find nothing to that effect mentioned in the c-ares docs.

**Comment by ericwuseattle** [comment]
Sorry Daniel, I have no way to reproduce it. it only happens couple times in the past months, I believe it's related to networking issue of DNS issue.

As the code comments
/*
 * ares_cancel() cancels all ongoing requests/resolves that might be going on
 * on the given channel. It does NOT kill the channel, use ares_destroy() for
 * that.
 */
void ares_cancel(ares_channel channel)

getting called.
/*
 * Cancel all possibly still on-going resolves for this connection.
 */
void Curl_resolver_cancel(struct connectdata *conn)
{
  if(conn->data && conn->data->state.resolver)
    ares_cancel((ares_channel)conn->data->state.resolver);
  destroy_async_data(&conn->async);
}

CURLcode Curl_resolver_wait_resolv(struct connectdata *conn,
                                   struct Curl_dns_entry **entry)
{
......
// result could be 
// CURLE_OPERATION_TIMEDOUT
// CURLE_ABORTED_BY_CALLBACK
// CURLE_COULDNT_RESOLVE_PROXY
if(result)
    /* failure, so we cancel the ares operation */
    ares_cancel((ares_channel)data->state.resolver);
......
}

and in c-ares treating these two error the same way.

static void addr_callback(void *arg, int status, int timeouts,
                          unsigned char *abuf, int alen)
{
......
else if (status == ARES_EDESTRUCTION || status == ARES_ECANCELLED)
    end_aquery(aquery, status, NULL);
......
}

**Comment by bagder** [comment]
> I have no way to reproduce it

Isn't that strange? If this is really a problem with canceling c-ares name resolves, couldn't we just make a sample program that times out transfers at various early times and set up the handle to use a non-responding DNS server and then iterate over a range of different timeout values?

> Sample in c-ares of treating these two errors in the same way.

The only place that happens is in gethostbyaddr code that isn't used here. And I'm not even sure that is relevant.

We have cancelled c-ares name resolves like this for a long time, I think we need to have plenty on our feet to consider changing this!

**Comment by ericwuseattle** [comment]
BTW, when crashing the status parameter in query_completed_cb is ARES_ECANCELLED, and conn->async is invalid value.

(gdb) print conn->async
$3 = {hostname = 0x21 <Address 0x21 out of bounds>, port = 8, dns = 0x7497ff0, done = 64, status = 0, os_specific = 0x21}

**Comment by bagder** [comment]
Do does this example crash for you? If no, why not?
~~~c
#include <stdio.h>
#include <curl/curl.h>

/* use with a c-ares build */

int main(void)
{
  CURLcode res;
  long timeout;

  for(timeout = 1; timeout < 3000; timeout++) {
    CURL *curl = curl_easy_init();
    if(curl) {
      curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");
      curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, timeout);

      /* Perform the request, res will get the return code */
      printf("run with timeout %ldms\n", timeout);
      res = curl_easy_perform(curl);
      /* Check for errors */
      if(res != CURLE_OK)
        fprintf(stderr, "curl_easy_perform() failed: %s\n",
                curl_easy_strerror(res));

      /* always cleanup */
      curl_easy_cleanup(curl);
    }
  }
  return 0;
}

**Comment by bagder** [comment]
No response, no way to reproduce. Closing.
