### ISSUE TITLE
Use VS2017 to build curl.exe for window XP

### ISSUE THREAD

**Issue by bingjun2019** [curl/curl#4481]
I use VS2017 to execute
```
  nmake /E CC="cl /D_USING_V110_SDK71_ /D_WIN32_WINNT=0x0501" /E RTLIBCFG=static  /f Makefile.vc mode=static DEBUG=no GEN_PDB=yes ENABLE_IDN=no
```
to get curl.exe，but get the error message "not a valid Win32 application"
because in MakefileBuild.vc
CURL_LFLAGS   = /out:$(DIRDIST)\bin\$(PROGRAM_NAME) /subsystem:console $(LFLAGS)
How do I append ",5.01" to /subsystem:console or other solutions.

**Comment by bagder** [comment]
Thanks! Can you clarify this: What happens exactly and what are you saying is the solution? Is this something change has changed in VS2017 from previous versions?

**Comment by jay** [comment]
It sounds like he's trying to build for Windows XP (5.1) using winbuild with VS2017. I don't know if there's a working way to do that? I have a note about 
`nmake /E CC="cl /D_USING_V110_SDK71_ /D_WIN32_WINNT=0x0501"`
but I don't recall using it. Also v110 might need to be adjusted. Anyway, if the subsystem isn't set as a result of that you could use editbin.

**Comment by gvanem** [comment]
> How do I append ",5.01" to /subsystem:console or other solutions.

Try adding a `-version:5.0` to the link flags manually. 
But it could be other issues running on Win-XP.

**Comment by bagder** [comment]
It seems to be a question for VS2017 people rather than us...

**Comment by jay** [comment]
it is possible to pass linker options to cl by using `/link` which causes the rest of the arguments to be treated as linker options, so conceivably the reporter could do something like `nmake /E CC="cl /DSOMEOPT /DSOMEOPT /link /SUBSYSTEM:CONSOLE,5.01 /OSVERSION:5.01"`.

**Comment by jay** [comment]
Nevermind I just tried that and it's not compatible with the way winbuild builds it. Someone would need to try with VS2017 to find a proper solution, my versions are older.

**Comment by bagder** [comment]
No response or added details after many days and provided suggestions. Closing.
