### ISSUE TITLE
libcurl can't resolved external symbol 

### ISSUE THREAD

**Issue by mengzhisuoliu** [curl/curl#4492]
### I did this
i use the curl-7.66.0 version to complie lib Release - Lib OpenSSL - Lib LibSSH2 with vs2017,the compile is ok.
it generate libcurl.lib ,i use libcurl.lib for the project,it can't work!it show like this:
Error	LNK2019	unresolved external symbol _Curl_ssh_init referenced in function _global_init	
Error	LNK2019	unresolved external symbol _Curl_ssh_cleanup referenced in function _curl_global_cleanup	
Error	LNK2001	unresolved external symbol _Curl_handler_scp		
Error	LNK2001	unresolved external symbol _Curl_handler_sftp		
Error	LNK2019	unresolved external symbol _Curl_ssh_version referenced in function _curl_version		
Error	LNK1120	5 unresolved externals
### curl/libcurl version
curl-7.66.0
[curl -V output]

### operating system
WIN10,

**Comment by bagder** [comment]
1. How do you build libcurl?
2. Doesn't the default build also build the curl tool this lib and that works?

**Comment by bagder** [comment]
No response and lots of people have built curl without getting this. Closing.

**Comment by bagder** [comment]
@zogvm What files are you then talking about that need this fix?

**Comment by xMikan09** [comment]
it worked after I put :
#pragma comment(lib, "libcurl_imp.lib") 

but I forgot where I downloaded the "libcurl_imp.lib" since the project only creates "libcurl.lib"

**Comment by bagder** [comment]
I would strongly discourage everyone from downloading and using a library from a random site that isn't vetted and trusted. It is then much better to get the source package and built it yourself to be completely sure what you're running and how to (re-)produce it etc.

**Comment by jay** [comment]
I don't think what @xMikan09 is related. Otherwise this is a bug though. Please try fix in #4607.
