### ISSUE TITLE
SMB upload - bad encoding filename

### ISSUE THREAD

**Issue by dl2v** [curl/curl#4495]
### I did this
Upload file from Ubuntu to windows server 2008R2 using CURL console command:
`$ curl -v -T doc-template.pdf -u "${CLOUD_USER}:${CLOUD_PASS}" "smb://cloud/home/Шаблон документа.pdf"`

### I expected the following
I expected the file name "Шаблон документа.pdf", and received:
![изображение](https://user-images.githubusercontent.com/56632364/66909819-15f78300-f016-11e9-91a6-b2395e6f339b.png)
How to solve a problem?

### curl/libcurl version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

### operating system
Ubuntu 16.04.6 LTS

**Comment by dfandrich** [comment]
What is the output of "locale charmap"? Does it work if you specify the URL path
in a different encoding, e.g.

$ curl -v -T doc-template.pdf -u "${CLOUD_USER}:${CLOUD_PASS}" $(iconv -t cp1251 <<<"smb://cloud/home/Шаблон документа.pdf")

curl doesn't convert the given URL path so GIGO. I'm not sure what the latest
standards say w.r.t. non-ASCII characters in URLs but I'm pretty sure there's
no agreement on how they are to be encoded.

**Comment by bagder** [comment]
curl 7.47.0 is fairly old but I bet this problem remains...

**Comment by dl2v** [comment]
```
$ locale charmap
UTF-8
```
```
* Connection #0 to host cloud left intact
* Rebuilt URL to: ���������.pdf/
* Input domain encoded as `UTF-8'
* Failed to convert ���������.pdf to ACE; Could not convert string in locale encoding
```

**Comment by dfandrich** [comment]
What was the exact command you ran that gave that output? The message implies
that the URL was missing the scheme. Also, please try this with a newer curl
since the URL code was completely rewritten recently.

**Comment by dl2v** [comment]
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.0.2g zlib/1.2.8 librtmp/2.3
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

`curl -v -T Тест.txt -u "${CLOUD_USER}:${CLOUD_PASS}" "smb://cloud/home/"`
Without changes......

**Comment by dfandrich** [comment]
Is that really the exact URL because the log shows
"<garbage>.pdf" and ".pdf" isn't anywhere in
"smb://cloud/home/"

**Comment by dl2v** [comment]
Garbage was when running CURL 7.47.0 with iconv:
`$ curl -v -T doc-template.pdf -u "${CLOUD_USER}:${CLOUD_PASS}" $(iconv -t cp1251 <<<"smb://cloud/home/Шаблон документа.pdf")`

**Comment by bagder** [comment]
The URLs curl supports are defined by RFC 3986. They don't define anything that isn't US ASCII really.

curl supports IDN domain names but when it comes to providing non-ASCII letters in other parts of the URL, curl doesn't encode them in any particular way but will just use the bytes as provided. I presume that's not the way this particular SMB server wants them.

Unfortunately, this seems to be more of a usage problem than an actual curl bug. You can basically not just pass Cyrillic in a URL to curl and expect it to work like that.

I'm not sure I see a bug here.

**Comment by bagder** [comment]
No further input or comments.
