### ISSUE TITLE
parallel calls done with PHP/CURL

### ISSUE THREAD

**Issue by 310K** [curl/curl#4497]
Hi !

I ran into the same problem for multiple days now and I have no idea how to fix it...

My vuejs app send multiple ajax query to a Laravel application. This laravel application makes API calls to other Laravel application (on the same machines) throug cUrl. Everything work fines if ajax queries are sent in sequence (meaning that API calls between Laravel applications will also be called sequentially). But when two (or more) ajax queries are sent in parallele (meaning that two instance of the same Laravel application will make the same API call through cUrl), I've got:

`cURL error 28: Operation timed out after 10070 milliseconds with 0 bytes received ...`

It is of course not a timeout problem because I also tried to increase it to 2 minutes with the same effect... It is the with `0 bytes received` that I find strange.

More visually: 
```
vuejs ---- ajax 1 ----> Laravel App A ---- curl ---> Laravel App B
vuejs ---- ajax 2 ----> Laravel App A ---- curl ---> Laravel App B
```

It's working when ajax 1 and ajax 2 are sequentially executed but doesn't work when ajax 1 and ajax 2 are on the same time.

I'm using MAMP Pro on MacOS 10.14 - PHP 7.3.8 - nginx (last version). No firewall on the machine.

I tried to increase php configuration like memory, max_execution_time, ... does not work.
I've also tried with Apache, same problem...

Do I miss something ?

Is it impossible to make multiple cUrl calls at the same time to the same resource (I can not use curl multi because we are on different instance on the Laravel application because of the two ajax queries) ?

**Comment by dfandrich** [comment]
curl can handle parallel calls just fine. This problem looks very much like a
server limitation. There are many things that could go wrong to cause problems
like this, from request pools or threads being too low, to improper locking or
other to multithreaded race conditions in the server or application. Look
through the documentation on the web server and framework you're using to see
what they have to say about parallel requests then dig in to the server code to
figure out why it's hanging.

**Comment by bagder** [comment]
We (in the curl/curl github repository) are the project that creates the library libcurl with is the foundation beneath the surface of the PHP/CURL module that you seem to be using. For issues with the PHP side of things, we need to refer you to the [PHP project](https://www.php.net/).

**Comment by bagder** [comment]
Not an issue for us.
