### ISSUE TITLE
libcurl.so:-1: error: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by zhengxiangwen** [curl/curl#4504]
I use curl in qt Creator,but it is fail. the error messages are:
/usr/local/lib/libcurl.so:-1: error: file not recognized: File format not recognized

Note: I want to use by Cross compile, beacase my target os is Embedded Linux(arm-himix200-linux).

**I don't know why,please help me! Thank you. This is my configure：**

export PATH=$PATH:/opt/hisi-linux/x86-arm/arm-himix200-linux/bin
export CPPFLAGS="-I/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/include"
export AR=arm-himix200-linux-ar
export AS=arm-himix200-linux-as
export LD=arm-himix200-linux-ld
export RANLIB=arm-himix200-linux-gcc-ranlib
export CC=arm-himix200-linux-gcc
export NM=arm-himix200-linux-nm
./configure --build=x86_64-linux-gnu --target=arm-himix200-linux --host=arm-himix200-linux --prefix=/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/local --exec-prefix=/usr/local

**And this my config.log:**
[https://pan.baidu.com/s/1-kSMGR9ohI5HpdCMv3sukw&shfl=sharepset](url)

**Comment by bagder** [comment]
I can't figure out how to see or download the config.log from there! My Chinese is a little lacking.

Further: your command line seems to hint that you want to install your cross-compiled build into `/usr/local` ? That seems unusual and not to be advised as you typically have your native libs there.

That error message you mention, when do you get that and how?

**Comment by zhengxiangwen** [comment]
sorry! I use a new link for config.log now: [https://padbott2.oss-cn-hangzhou.aliyuncs.com/test/config.log](https://padbott2.oss-cn-hangzhou.aliyuncs.com/test/config.log)

And I have changed a new directory that cross-compiled build into. The new configure is:
export PATH=$PATH:/opt/hisi-linux/x86-arm/arm-himix200-linux/bin
export CPPFLAGS="-I/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/include"
export AR=arm-himix200-linux-ar
export AS=arm-himix200-linux-as
export LD=arm-himix200-linux-ld
export RANLIB=arm-himix200-linux-gcc-ranlib
export CC=arm-himix200-linux-gcc
export NM=arm-himix200-linux-nm
./configure --build=x86_64-linux-gnu --target=arm-himix200-linux --host=arm-himix200-linux --prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/includepath --exec-prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib

But the errors still exist.
My IDE is "Qt Creator", and my project need to integrate the curl library as shown in the [screenshot](https://padbott2.oss-cn-hangzhou.aliyuncs.com/test/qt_curl_error.jpg), the error occurs when I click "Rebuild" button.
Maybe,the curl library is not compiling properly, but I don't know why.

**Comment by bagder** [comment]
I don't spot any obvious mistake in the curl build and you do seem to get a library built and installed there...

If you run `file /home/linkpi/work/3519A/BaiduFaceSdk/curl/lib/libcurl.so`, does it say that the file is of the correct type? If so, then I would rather look from the other end and figure out why "Qt Creator" says this.

**Comment by zhengxiangwen** [comment]
I think the question is: the file format of libcurl.so doesn't match my embedded Linux operating system.
Because, when I execute the command: **file libcurl.so.4.6.0**
The result is: 
**libcurl.so.4.6.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=af189e2b96487dcfcc6113827ed1d7d48420b72d, not stripped**
It's x86-64, But my embedded Linux is armv7l.
(In my embedded Linux,when I execute the command:**uname -a**  The result is:**Linux 192.168.2.222 4.9.37 #13 SMP Thu Jul 25 17:14:50 CST 2019 armv7l GNU/Linux**)

And on my virtual machine(x86-64 Ubuntu) my configure is:
export PATH=$PATH:/opt/hisi-linux/x86-arm/arm-himix200-linux/bin
export CPPFLAGS="-I/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/include"
export AR=arm-himix200-linux-ar
export AS=arm-himix200-linux-as
export LD=arm-himix200-linux-ld
export RANLIB=arm-himix200-linux-gcc-ranlib
export CC=arm-himix200-linux-gcc
export NM=arm-himix200-linux-nm
./configure --build=x86_64-linux-gnu --target=armv7l-linux-gnu --host=armv7l-linux-gnu --prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/includepath --exec-prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib

Why the file format of libcurl.so is not armv7l?

**Comment by bagder** [comment]
which libcurl.so ? The one in `/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib` ? If so, then I propose you rebuild with `make V=1` and check the compile and linker command lines and make sure they are the cross-compiled versions.

**Comment by zhengxiangwen** [comment]
Yes, it's the one in `/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib`.
I execute the command:`make V=1` and the log is [here](https://padbott2.oss-cn-hangzhou.aliyuncs.com/test/make.log).
Please help me analyze the log. Are they the cross-compiled versions? Thank you very much!

**This is my configure:**
`export PATH=$PATH:/opt/hisi-linux/x86-arm/arm-himix200-linux/bin
export CPPFLAGS="-I/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/include"
export AR=arm-himix200-linux-ar
export AS=arm-himix200-linux-as
export LD=arm-himix200-linux-ld
export RANLIB=arm-himix200-linux-gcc-ranlib
export CC=arm-himix200-linux-gcc
export CXX=arm-himix200-linux-c++
export NM=arm-himix200-linux-nm
export STRIP=arm-himix200-linux-strip
export OBJDUMP=arm-himix200-linux-objdump
./configure --build=x86_64-linux-gnu --target=arm-linux-gnueabi --host=arm-linux-gnueabi --prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/includepath --exec-prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib`

**Comment by zhengxiangwen** [comment]
Thank you! The problem has been solved. Because `RANLIB` is not  set correct and not execute commands through the shell. So it's use the defualt compiler that not `arm-himix200-linux-gcc`.
This is my new configure that execute through the shell:
`export PATH=$PATH:/opt/hisi-linux/x86-arm/arm-himix200-linux/bin CPPFLAGS="-I/opt/hisi-linux/x86-arm/arm-himix200-linux/target/usr/include" AR=arm-himix200-linux-ar AS=arm-himix200-linux-as LD=arm-himix200-linux-ld RANLIB=arm-himix200-linux-ranlib CC=arm-himix200-linux-gcc CPP=arm-himix200-linux-cpp NM=arm-himix200-linux-nm STRIP=arm-himix200-linux-strip OBJDUMP=arm-himix200-linux-objdump GCOV=arm-himix200-linux-gcov
./configure --host=arm-himix200-linux --prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/includepath --exec-prefix=/home/linkpi/work/3519A/BaiduFaceSdk/curl/lib
make && make install`

**Comment by dfandrich** [comment]
Consider configuring with --host=arm-himix200-linux instead of setting all
those environment variables manually. See the cross-compiling section of
INSTALL.md for more info.

**Comment by bagder** [comment]
Issue resolved. Closing!
