### ISSUE TITLE
AmigaOS with AmiSSL: Cannot be compiled/configured

### ISSUE THREAD

**Issue by OliverUrbann** [curl/curl#4510]
Due to movement of check for proto/bsdsocket.h it is now required to use clib2 instead of libnix. Libnix includes a libsocket.a which is thus found and the check for a amiga native gethostbyname is thus not executed. However, a succesfull native check is required to enable AmiSSL.

_Originally posted by @chris-y in https://github.com/curl/curl/pull/3677/commits/a203e4ce0020fa07ab42a0c974f587213e8b67e1_

**Comment by OliverUrbann** [comment]
Additionally, using clib2 checking for proto/bsdsocket.h seems to be not the right header and leads to conflicting types, e.g. using m68k-amigaos-gcc 6.5.0b from [here](https://github.com/bebbo/amiga-gcc). Rather checking for libraries/bsdsocket.h?

**Comment by chris-y** [comment]
Maybe it should be proto/socket.h?
proto/bsdsocket.h isn't always present depending on the network stack headers being used (a lot of them aren't expecting GCC anyway).
It works with clib2 and the Roadshow SDK here.

The libnix thing I can't answer, it sounds like the check needs moving.

You're probably better off fixing the issues and creating a pull request then raising a bug report.

**Comment by OliverUrbann** [comment]
Which compiler are you using?

Probably libnix is not adequate as it uses the library and offers a network stack. I read somewhere curl should not use a wrapper of the bsdsocket.library. 

Ok, ticket can then be closed, I will see what I can do. Thx so far!

**Comment by chris-y** [comment]
Ancient gcc 3.4, I've never successfully managed to get anything newer working.

You should be OK using the built-in wrapper, just be a bit careful as in amiga.c it opens bsdsocket.library and you could get conflicts.  I tried to unravel this when I wrote my patch, so lack of HAVE_PROTO_BSDSOCKET_H ought to stop it opening bsdsocket but I may have missed something libnix-specific.
