### ISSUE TITLE
which version can curl_multi use timeout_ms ? I find curl.so 7.35 the opt timeout_ms < 1000ms not work. The curl.so 7.29 timeout is always 10s

### ISSUE THREAD

**Issue by flycode310** [curl/curl#4521]
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
