### ISSUE TITLE
TLS 1.3 not working with Secure Transport

### ISSUE THREAD

**Issue by kathampy** [curl/curl#4524]
### I did this
```
/usr/local/opt/curl/bin/curl -v --tlsv1.3 --head https://1.1.1.1
*   Trying 1.1.1.1:443...
* TCP_NODELAY set
* Connected to 1.1.1.1 (1.1.1.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* WARNING: using IP address, SNI is being disabled by the OS.
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: cloudflare-dns.com
* Server certificate: DigiCert ECC Secure Server CA
* Server certificate: DigiCert Global Root CA
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
```

### I expected the following
```
/usr/local/opt/curl-openssl/bin/curl -v --tlsv1.3 --head https://1.1.1.1
*   Trying 1.1.1.1:443...
* TCP_NODELAY set
* Connected to 1.1.1.1 (1.1.1.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl@1.1/cert.pem
  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=cloudflare-dns.com
*  start date: Jan 28 00:00:00 2019 GMT
*  expire date: Feb  1 12:00:00 2021 GMT
*  subjectAltName: host "1.1.1.1" matched cert's IP address!
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert ECC Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
```

### curl/libcurl version
```
/usr/local/opt/curl/bin/curl -V
curl 7.66.0 (x86_64-apple-darwin19.0.0) libcurl/7.66.0 SecureTransport zlib/1.2.11 brotli/1.0.7 c-ares/1.15.0 libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL UnixSockets
```
```
/usr/local/opt/curl-openssl/bin/curl -V
curl 7.66.0 (x86_64-apple-darwin19.0.0) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 c-ares/1.15.0 libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

### operating system
macOS Catalina 10.15 (19A602)

**Comment by chris-wood** [comment]
This is expected. TLS 1.3 is *not supported* by the SecureTransport API.

**Comment by bagder** [comment]
Maybe we should consider providing that feedback better?

**Comment by kathampy** [comment]
I see `Secure Transport` is deprecated in favour of `Network.framework`. I wonder if it's flexible enough to be a `curl` backend.

**Comment by bagder** [comment]
in the most recent macOS versions, Apple ships curl built against libressl... Secure Transport is a thing of the past.

**Comment by kathampy** [comment]
> in the most recent macOS versions, Apple ships curl built against libressl... Secure Transport is a thing of the past.
I don't think `LibreSSL` is an "official" macOS library either. It doesn't seem to be built with TLS 1.3 support.

**Comment by bagder** [comment]
I don't know what you mean with official. It comes bundled and installed with macOS. Isn't official enough?

> It doesn't seem to be built with TLS 1.3 support.

Correct. It seems [libressl doesn't support it?](https://github.com/libressl-portable/portable/issues/228)

**Comment by kathampy** [comment]
> I don't know what you mean with official. It comes bundled and installed with macOS. Isn't that official enough?

I suspect it's because they didn't want to remove applications like `curl` and there was no other backend. There is no mention of `LibreSSL` anywhere on Apple's developer website, but they did passingly mention `OpenSSL` before it was removed.
They probably want everyone to use the macOS frameworks where ever possible.

**Comment by bagder** [comment]
curl + Secure Transport *can* actually do TLS 1.3, or should be able to according to @nickzman, our resident expert on this. Since commit 3e492e03b37ce76c and according to source code comments. If built with clang at least (commit b78d1a3d4563a055a mentions gcc can't make it work).

**Comment by kathampy** [comment]
It might need to be enabled with
`sudo defaults write /Library/Preferences/com.apple.networkd tcp_connect_enable_tls13 1`
as well.
Are there instructions to build with clang? I'm using the build steps from this script: https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb

**Comment by chris-wood** [comment]
To clarify (I maintain TLS at Apple), it's not possible to use TLS 1.3 with SecureTransport.

**Comment by kathampy** [comment]
> To clarify (I maintain TLS at Apple), it's not possible to use TLS 1.3 with SecureTransport.

In that case do you recommend `LibreSSL` or `Secure`Transport` for building applications like `curl`?

**Comment by bagder** [comment]
Hehe, thanks for that clarity @chris-wood!

**Comment by nickzman** [comment]
The Secure Transport headers [have a constant](https://developer.apple.com/documentation/security/sslprotocol/ktlsprotocol13?language=objc) for TLS 1.3, but in practice, it doesn't work. Maybe I should reverse that commit if it's confusing people.

I should probably start working on supporting the Network framework. I wonder if it supports starting TLS on demand, instead of at connection time, for things like explicit FTPS. That's my main concern.

**Comment by chris-wood** [comment]
> I should probably start working on supporting the Network framework. I wonder if it supports starting TLS on demand, instead of at connection time, for things like explicit FTPS. That's my main concern.

@nickzman it does indeed! (This was needed for STARTTLS.) The basic idea is to make a "framer" object that does whatever custom handshake is needed, and then prepend TLS to the protocol stack when necessary. Take a look at the following documentation links for pointers to get started:

- https://developer.apple.com/documentation/network/nw_framer_t
- https://developer.apple.com/documentation/network/3141918-nw_framer_prepend_application_pr

I'm happy to connect you with the maintainers of that framework if you need further assistance!
