### ISSUE TITLE
curl timeout continuously when download a large number of url. (Version 7.64.1) 

### ISSUE THREAD

**Issue by dangvohoanganhvn** [curl/curl#4548]
I have a mobile application ( IOS)  which use curl (version 7.64.1) to download a large number of photos ( <2MB). It will return a timeout code (28) although I limit max download at the same time is 3 (other requests will be put in a Queue and wait for their turns)  and the network and server are still good. In my application, When a timeout event return occur I have to wait for a minute to download successfully next requests ( They maybe be unsuccessful download requests before).

+ I use these options for controlling timeout in my application
       curl_easy_setopt(m_easy_handler, CURLOPT_CONNECTTIMEOUT, 5L);
      curl_easy_setopt(m_easy_handler, CURLOPT_LOW_SPEED_TIME, 10L);
      curl_easy_setopt(m_easy_handler, CURLOPT_LOW_SPEED_LIMIT, 50L);

Please let me know why I have this issue.
+Note: 
      -curl version: 7.64.1
      -Platform:Mobile IOS (any version)

**Comment by bagder** [comment]
I can't recall any such bugfix done since 7.64.1 and nobody else has reported this. I think you need to provide VERBOSE logs or a way for us to reproduce this! 

> When a timeout event return occur I have to wait for a minute to download successfully next requests

That makes it sound like the sever is deliberately throttling you, so it might not be a curl issue at all...

**Comment by bagder** [comment]
No response, sounds like a server issue.
