### ISSUE TITLE
Compile on Windows fails with error (nmake)

### ISSUE THREAD

**Issue by ronginme** [curl/curl#4553]
```
NMAKE : fatal error U1073: don't know how to make '..\src\tool_hugehelp.c'
Stop.
```
Also I noticed the src\tool_hugehelp.c.`csv` exists instead of `src\tool_hugehelp.c`  
https://github.com/curl/curl/blob/master/src/tool_hugehelp.c.cvs  

Build succeeded after replacing `src\tool_hugehelp.c.csv` with `src\tool_hugehelp.c`  

### I did this
nmake /f Makefile.vc mode=dll WITH_SSL=dll SSL_PATH="%SSL_PATH%"

### I expected the following
build succeeded

### curl/libcurl version
master branch
https://github.com/curl/curl/commit/2839cfdc53c38df341a818549820303fde641452

### operating system
Windows10  
VS Community 2017  

nmake /? 
Microsoft (R) Program Maintenance Utility Version 14.14.26430.0

**Comment by jay** [comment]
https://github.com/curl/curl/blob/9cd755e1d768bbf228e7c9faf223b7459f7e0105/winbuild/BUILD.WINDOWS.txt#L40-L42
