### ISSUE TITLE
configure says IPv6 enabled when it isn't

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#4555]
### I did this

```
./buildconf
./configure --enable-debug --with-winssl --enable-alt-svc
```

configure says:
```
IPv6:             enabled
```
because of https://github.com/curl/curl/blob/2839cfdc53c38df341a818549820303fde641452/configure.ac#L1231.

But curl_config.h says:
```
/* Define if you want to enable IPv6 support */
/* #undef ENABLE_IPV6 */
```
because of https://github.com/curl/curl/blob/2839cfdc53c38df341a818549820303fde641452/configure.ac#L3968.

### I expected the following

The output of configure to match `ENABLE_IPV6`. And probably `ENABLE_IPV6` being independent of `HAVE_GETADDRINFO`.

### curl/libcurl version

https://github.com/curl/curl/commit/2839cfdc53c38df341a818549820303fde641452

```
curl 7.67.0-DEV (i686-pc-mingw32) libcurl/7.67.0-DEV Schannel zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug Kerberos Largefile libz NTLM SPNEGO SSL SSPI TrackMemory
```

### operating system

Classic MinGW with MSYS 1.0 on Windows 10

**Comment by bagder** [comment]
I don't think there's any point in making them independent of each other. We can only do IPv6 "proper" if `getaddrinfo()` exists.
