### ISSUE TITLE
curl -m / --max-time : not working. Connection timeout default MAX to 15mins. 

### ISSUE THREAD

**Issue by preeti-gm** [curl/curl#4562]
### I did this
I have bash cmd to CURL -GET on my endpoint. My intention is to open the connection till response is received. Response time get varied according to the load. 
In few cases when RSP time > 30 mins, such scenario RSP code 000 was returned.

Below code for CURL with Max time didnt help to hold the connection. 

curl  --max-time 400 --write-out %{http_code} --silent --output /dev/null "$targetHost" --header "Authorization: Bearer $tok")

Note: --max-time is taking seconds as input, tested couple by passing 2 and verified connection time outs at 2 second.

### I expected the following
1) -max-time : to hold connection as per defined seconds.

### curl/libcurl version
[curl -V output]
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

### operating system
Linux

**Comment by jay** [comment]
> curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0

That's an old version of curl, there's been 6 years of improvements since then. 

> Below code for CURL with Max time didnt help to hold the connection.
> 
> curl --max-time 400 --write-out %{http_code} --silent --output /dev/null "$targetHost" --header "Authorization: Bearer $tok")

That's not what it does. From the [--max-time](https://curl.haxx.se/docs/manpage.html#-m) doc:

"_Maximum time in seconds that you allow the whole operation to take. This is useful for preventing your batch jobs from hanging for hours due to slow networks or links going down._"

In your example you are allowing a maximum of 400 seconds (6m40s).

Please review the [curl book timeouts section](https://ec.haxx.se/usingcurl-timeouts.html). If you do not set timeouts then curl will wait for a reply indefinitely. As noted in the book curl uses TCP keepalive by default to make sure the connection is still alive.

I suggest enable [--verbose](https://curl.haxx.se/docs/manpage.html#-v) to watch the request.

**Comment by preeti-gm** [comment]
Thanks for reply.

Quick question,

  1.  With latest version dose CURL hold the session still the RSP is received ?

At this moment, connection times out by default of 15mins and irrespective of max-time.





Thanks,

Preeti

**Comment by jay** [comment]
> 1. With latest version dose CURL hold the session still the RSP is received ? At this moment, connection times out by default of 15mins and irrespective of max-time.

If the connection is made curl will wait indefinitely for the server if you do not have max timeout enabled, this is true of all versions. If the connection cannot be made you may find the [--retry](https://curl.haxx.se/docs/manpage.html#--retry) options helpful. The default connect timeout is 5 minutes but your OS may not allow for that long. I reiterate use verbose mode to find what's happening, my guess is the server is closing the connection.

**Comment by preeti-gm** [comment]
Appreciate your reply.

Was getting SSL read error- TCP connection reset by Peer. Is this related to network cut out connection ? Please shed some lights.

>
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0* SSL read: errno -5961 (PR_CONNECT_RESET_ERROR)
* TCP connection reset by peer
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
* Closing connection 0
curl: (56) TCP connection reset by peer


Thanks,
Preeti

**Comment by jay** [comment]
> * TCP connection reset by peer

It is what it says. This is not a curl issue. If you have curl questions in the future please use [the mailing lists](https://curl.haxx.se/mail/).
