### ISSUE TITLE
Can't install with ssl

### ISSUE THREAD

**Issue by MESWEB** [curl/curl#4564]
### I did this
`./configure --with-ssl=./usr/local/ssl`
`make`
>   CCLD     libcurl.la
/usr/bin/ld: /usr/local/ssl/lib/libssl.a(t1_enc.o): relocation R_X86_64_PC32 against symbol stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/ssl/lib/libcrypto.a(cryptlib.o): relocation R_X86_64_PC32 against symbol stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/ssl/lib/libcrypto.a(ui_openssl.o): relocation R_X86_64_PC32 against symbol stdin@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/ssl/lib/libcrypto.a(gost_eng.o): relocation R_X86_64_PC32 against symbol stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/ssl/lib/libcrypto.a(txt_db.o): relocation R_X86_64_PC32 against symbol stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1230: libcurl.la] Error 1
make[2]: Leaving directory '/home/xxx/.local/share/Trash/files/curl-7.67_3782237855496.0/lib'
make[1]: *** [Makefile:1049: all] Error 2
make[1]: Leaving directory '/home/xxx/.local/share/Trash/files/curl-7.67_3782237855496.0/lib'
make: *** [Makefile:946: all-recursive] Error 1

### I expected the following
Install complete?
### curl/libcurl version

[curl -V output]
7.67.0

**Comment by bagder** [comment]
The linker doesn't like the OpenSSL libraries you have in that directory. I don't think there's anything we/curl can do about that. How did you build and install that OpenSSL?

**Comment by jzakrzewski** [comment]
The linker has already told you what's wrong - static version of OpenSSL libraries has been found and it's compiled without position independent code (-fPIC), so it cannot be linked into a dynamic library.

Solutions:
* rebuild static OpenSSL with -fPIC
* build dynamic OpenSSL
* build static curl

**Comment by MESWEB** [comment]
@bagder @jzakrzewski I was get installed Open SSL v 1.0.2t by my mistake - on home page this link was first and I was think it's latest stable version.
After update Open SSL to newest version it's work. Please add option to check version of Open SSL when we try install with SSL

**Comment by bagder** [comment]
It's not curl's or curl's configure's job to tell you what 3rd party library version you should use. Lots of existing users use OpenSSL 1.0.2 (or older!) for reasons and curl works fine with those.

**Comment by MESWEB** [comment]
Yes it's works if you install older version of curl. New version is not working.
