### ISSUE TITLE
libssh2/mbedtls: can't login to sftp using ONLY private key

### ISSUE THREAD

**Issue by nojb** [curl/curl#4568]
### I did this

I am trying to login to an sftp server where with private key **ONLY**.

```
$ curl -v -s -k --key <path to private key> sftp://<login>:<sftp server>
* Rebuilt URL to: sftp://<login>:<sftp server>
*   Trying 208.22.57.176...
* TCP_NODELAY set
* Connected to <sftp server> (208.22.57.176) port 22 (#0)
* SSH MD5 fingerprint: 6bd3192a0dda65da1c962a3e00e7ee57
* SSH authentication methods available: publickey,password,keyboard-interactive
* Using SSH private key file '<path to private key>'
* SSH public key authentication failed: Username/PublicKey combination invalid
* Failure connecting to agent
* Authentication failure
* Closing connection 0
```

### I expected the following

To be able to log in the server. This used to work with WinCNG and supposedly works with OpenSSL as well (but I have not tested it personally).

### curl/libcurl version

```
curl 7.54.1 (x86_64-pc-win32) libcurl/7.54.1 mbedTLS/2.16.3 zlib/1.2.11 WinIDN libssh2/1.9.0
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz
```

### operating system

Windows

**Comment by dfandrich** [comment]
Does the equivalent OpenSSH sftp command work?

**Comment by nojb** [comment]
> Does the equivalent OpenSSH sftp command work?

Yes, just tried it.

**Comment by bagder** [comment]
> This used to work with WinCNG and supposedly works with OpenSSL as well (but I have not tested it personally).

You're then talking about different libssh2 builds, right? And if so, isn't this then just a problem with libssh2 and not curl?

**Comment by nojb** [comment]
> You're then talking about different libssh2 builds, right? And if so, isn't this then just a problem with libssh2 and not curl?

Yes, that may be it. Sorry, it was a bit unclear in my mind about the division of responsibilities between the two libraries. Should I close this issue and open a new issue in the `libssh2` repository ?

**Comment by bagder** [comment]
If the issue is caused by just replacing the libssh2 library, then the problem can with some certainty be said to be within libssh2 and then it is a libssh2 issue that's best filed there.
