### ISSUE TITLE
libCurl build fails with CURL_DISABLE_CRYPTO_AUTH and USE_NTLM (causes curl_ntlm_core.c to to compile with unresolved symbol `Curl_md4it`)

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#4569]
### I did this

Built libCurl with `USE_NTLM` and `CURL_DISABLE_CRYPTO_AUTH` defined (as well as `USE_WIN32_CRYPTO`, `USE_WINDOWS_SSPI`). 

In `curl_ntlm_core.c` the `Curl_ntlm_core_mk_nt_hash` function is compiled (although unused from any other code in curl due to the defines chosen). That function calls `Curl_md4it(...)` which is not compiled (because `CURL_DISABLE_CRYPTO_AUTH`) and thus this warning is output:

```
curl\lib\curl_ntlm_core.c(559,13): warning C4013: 'Curl_md4it' undefined; assuming extern returning int
```

Which seems innocuous, but really means that any code that embeds the library will fail because `Curl_md4it` is not defined (by design).

### I expected the following

Compile without that warning (failure).

### curl/libcurl version

7.67.0

### operating system

Windows 10. But a similar set of defines for Unix OSes will result in the same failure.

**Comment by bagder** [comment]
*With* NTLM and still *without* crypto-auth sounds like a strange ask. What exactly did you expect that to do?

**Comment by wyattoday** [comment]
With a name like "crypto-auth" you'd think we'd want it. But we don't need (or want) HTTP Digest and SASL, and thus want to exclude them from the builds.

So, perhaps a longer-term goal would be to make "CURL_DISABLE_CRYPTO_AUTH" named something more specific (because it's definitely confusing, and whenever we review our defines that one makes us do a double-take to ensure we *actually* want to have that build-define).

Also, `Curl_ntlm_core_mk_nt_hash` is unused in the builds with the defines we've chosen (although, the latest MSVC isn't smart enough to exclude it from the build).

**Comment by bagder** [comment]
You seem to ask for a way to disable individual authentication mechanisms when building, and I wouldn't mind having that, but that's not where we are and support right now. "crypto auths" are simply all authentications that use some sort of crypto" - and that includes NTLM. So the combo you ask for isn't supported by the code right now.

> Also, Curl_ntlm_core_mk_nt_hash is unused in the builds with the defines we've chosen

That sounds like an unclever linker in combination with us having a set of #ifdefs for all the code that invoke that function ...

**Comment by wyattoday** [comment]
> So the combo you ask for isn't supported by the code right now.

Fair enough. Thanks, Daniel.
