### ISSUE TITLE
How to build curl with wolfssl?

### ISSUE THREAD

**Issue by myvcgit** [curl/curl#4580]
### I did this
I'm trying to build curl with wolfssl on Windows 10 use vs 2019.
I have wolfssl built OK.
How can i do to build curl with wolfssl?
### curl/libcurl version

[curl -V output]

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
