### ISSUE TITLE
Possible busy-looping in curl_multi_poll

### ISSUE THREAD

**Issue by 3dyd** [curl/curl#4594]
Take a look at this piece of code at the end of `Curl_multi_wait`:
https://github.com/curl/curl/blob/7a46aeb0be3fa00826b0c47a8bc06eddff448659/lib/multi.c#L1150-L1161
If `curl_multi_poll` is given valid empty multi handle (no easy handles were added to it [yet]) without extra `curl_waitfd` structures then `sleep_ms` receives value -1 from `curl_multi_timeout` effectively avoiding waiting for given `timeout_ms` period. So function returns immediately.

Is this intended behavior, and such edge case still has to be accounted by the caller to avoid busy-looping?

**Comment by bagder** [comment]
I think it should wait for the timeout period in this case. Something like this?
~~~diff
diff --git a/lib/multi.c b/lib/multi.c
index 7e8e38dc9..db08ac636 100755
--- a/lib/multi.c
+++ b/lib/multi.c
@@ -1155,10 +1155,12 @@ static CURLMcode Curl_multi_wait(struct Curl_multi *multi,
 
     /* Avoid busy-looping when there's nothing particular to wait for */
     if(!curl_multi_timeout(multi, &sleep_ms) && sleep_ms) {
       if(sleep_ms > timeout_ms)
         sleep_ms = timeout_ms;
+      else if((sleep_ms < 0) && extrawait)
+        sleep_ms = timeout_ms;
       Curl_wait_ms((int)sleep_ms);
     }
   }
 
   return CURLM_OK;

**Comment by 3dyd** [comment]
Not sure if notification is fired if one comments diff directly, so I am duplication it here:
```
else if((sleep_ms < 0) && extrawait)
```

`extrawait` is always true in this block.

**Comment by 3dyd** [comment]
Confirmed the change has fixed described issue.
