### ISSUE TITLE
Make curl_easy_getinfo / CURLINFO_REDIRECT_URL usable in more situations

### ISSUE THREAD

**Issue by Bylon2** [curl/curl#4611]
I hesitated to file that under "security"... but since the workaround is easy, let's do a "normal" bug report!

### I did this
Tried to do curl_easy_getinfo / CURLINFO_REDIRECT_URL on a request where the curl callback for the body explicitly ends the writing.

Although the header has: HTTP 302 FOUND and a Location header, the  curl_easy_getinfo / CURLINFO_REDIRECT_URL fails.

### I expected the following

I expect it not to fail from the moment the Location: header was received. This is a simple string lookup, and should not fail!

### curl/libcurl version

libcurl Version 7.47

### operating system

Linux 4.4.0-169-generic

### Security related stuff:

The situation is as follow.
I am getting an URL which I expect leads to a "redirect" in order to get the resource I need.
But there are 2 unknown adverse possible actions a misbehaving server can do that could trigger **denial of service** on the client.

On the first request (the one we expect has a "redirect") the server could send a big amount of data.
This is easily fixed, with:
- a callback on the HTTP Headers
- the callback uses curl_easy_getinfo / CURLINFO_RESPONSE_CODE and tests if we got the expected code and otherwise aborts the curl operation returning 0.

This ALWAYS work in http(s) because the first time the callback headers is triggered is on the response code line.

So now we are protected from this first possible issue and we have the header callback got the redirect.

There is now a second issue. Since RF2616 says under 302:
> Unless the request method was HEAD, the entity of the  response SHOULD contain a short hypertext note with a hyperlink to  the new URI(s).

So this means a request body is valid (and expected) after a 302 (or equivalent). Here again, the server could send a lot of data.
It is not uncommon to see that the "short hypertext note" recommended is now a full page of several KB.

So we might want to do the following simple code:
- set a callback for the body of the request
- return 0 on the callback

This would stop curl from pulling any data after the headers, and ensure we have the Location: header, even if it was the last buffer.

But doing so, curl returns as expected with CURLE_WRITE_ERROR, and the curl_easy_getinfo / CURLINFO_REDIRECT_URL fails!

### fallback:

Not use curl_easy_getinfo / CURLINFO_REDIRECT_URL and write your own code

.... which sort of defeats the purpose of having a library function!

### Demo program:
```
#include <stdio.h>
#include <curl/curl.h>

static size_t header_check(char *buffer, size_t size,
			   size_t nmemb, void *curl)
{
	long http_code;
	
	curl_easy_getinfo((CURL *)curl, CURLINFO_RESPONSE_CODE, &http_code);

	if (302 != http_code) {
		printf("We expect 302 and got: %ld.\nAbort.\n", http_code);
		return 0;
	}

	/* From here we have the redirect */
	printf("We got 302: Continue.\n");
	curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, NULL);
	curl_easy_setopt(curl, CURLOPT_HEADERDATA, NULL);
	return size * nmemb;
}
	
static size_t no_body(char *buffer, size_t size,
		      size_t nmemb, void *userdata)
{
	/* We are not interested in reading the body */
	return 0;
}

static size_t full_body(char *buffer, size_t size,
		        size_t nmemb, void *userdata)
{
	/* We are obliged to read the full body! */
	return size * nmemb;
}

int main(int argc, char *argv[]) {
	CURLcode res;
	char *url = NULL;

	CURL *curl = curl_easy_init();
	if(curl) {
		curl_easy_setopt(curl, CURLOPT_URL, argv[1]);
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, no_body);
		curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_check);
		curl_easy_setopt(curl, CURLOPT_HEADERDATA, curl);
		res = curl_easy_perform(curl);
		printf("curl_easy_perform ended with %d\n", res);
		res = curl_easy_getinfo(curl, CURLINFO_REDIRECT_URL, &url);
		printf("curl_easy_getinfo: %d, Redirect to: %s\n", res, url);

		/* Take 2: now reading full body /!\ D.o.S. is possible */
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, full_body);
		curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_check);
		curl_easy_setopt(curl, CURLOPT_HEADERDATA, curl);
		res = curl_easy_perform(curl);
		printf("curl_easy_perform ended with %d\n", res);
		res = curl_easy_getinfo(curl, CURLINFO_REDIRECT_URL, &url);
		printf("curl_easy_getinfo: %d, Redirect to: %s\n", res, url);
	}
	curl_easy_cleanup(curl);
	return 0;
}
```

Compiles with:
`gcc bug.c -o bug -Wall $(curl-config --cflags) $(curl-config --libs)`

Run:
```
./bug https://1fichier.com/?12345678901234567890
We got 302: Continue.
curl_easy_perform ended with 23
curl_easy_getinfo: 0, Redirect to: (null)
We got 302: Continue.
curl_easy_perform ended with 0
curl_easy_getinfo: 0, Redirect to: https://a-8.1fichier.com/p444444444

```

(Note links were altered, put your own valid links to try it)

What was expected is that the first "pass" would work since all the headers have been read, and we just stop at the first byte of the body.

Instead, for that simple code, we have to read the full body... which could be gigabytes with risks of denial of service, or triggering big bills on limited phone subscriptions.

**Comment by bagder** [comment]
Quote from the [curl_easy_getinfo man page](https://curl.haxx.se/libcurl/c/curl_easy_getinfo.html):

> The data pointed-to will be filled in accordingly and can be relied upon only if the function returns CURLE_OK.

To me, it seems match your described behavior.

That said, we can of course discuss if we should improve this for the reasons you outline.

**Comment by jay** [comment]
If you're worried about content length why not peek at it with a HEAD request
curl -v --write-out "%{redirect_url}" google.com

or in libcurl the equivalent is CURLOPT_NOBODY

the problem with aborting like you do, besides what you've already discovered, is it kills the connection, and ideally you'd want to stay on the existing connection rather than establish a new one for response.

**Comment by Bylon2** [comment]
**@Jay** many thanks, so far HEAD was not working on this server (1fichier.com) but I have tried again, and now it works! Indeed, when the server supports HEAD, that is the right method to use.

Aborting the request was not an issue in this use case. 1fichier is a cloud storage provider, which means the GET/HEAD on the "file link" is served on a web frontend which responds (302) with another link to the actual server where the resource has been stored. So in that case, the IP is different, and you have to open different sockets to get the resource behind the redirect.
But indeed, keeping the connection opened could allow for example querying other locations.

**@bagder** you are completely correct, it works as documented. I even had to change the example to make the point, since the example (curl online documentation) tests the return code of curl_easy_perform before trying to get the redirect URL.

> That said, we can of course discuss if we should improve this for the reasons you outline.

Yes please!

When using curl_easy_getinfo on strings, it returns a pointer on an internal memory allocated by curl, that will be freed with curl_easy_cleanup. So the caller MUST NOT call free on the pointer, and when he intends to use the string after curl_easy_cleanup, some kind of strdup must be made before calling curl_easy_cleanup, or you will use a freed memory zone!

So a good reason for NOT responding with the redirect_url would have been that curl might free its internal buffers if a write error is returned from the write callback. I did not read the code, but running it with valgrind does not report that I am in any case using a freed zone!

### More complex code to illustrated even further:
```
#include <stdio.h>
#include <curl/curl.h>


static size_t dump_headers(char *buffer, size_t size,
			   size_t nmemb, void *curl)
{
	CURLcode res;
	char *url = NULL;

	printf("Header: %.*s\n", (int)(size * nmemb), buffer);
	res = curl_easy_getinfo(curl, CURLINFO_REDIRECT_URL, &url);
	printf("+curl_easy_getinfo: %d, Redirect to: %s\n", res, url);

	return size * nmemb;
}

static size_t header_check(char *buffer, size_t size,
			   size_t nmemb, void *curl)
{
	long http_code;
	
	curl_easy_getinfo((CURL *)curl, CURLINFO_RESPONSE_CODE, &http_code);

	if (302 != http_code) {
		printf("We expect 302 and got: %ld.\nAbort.\n", http_code);
		return 0;
	}

	/* From here we have the redirect */
	printf("We got 302: Continue.\n");
	curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, dump_headers);
	return size * nmemb;
}
	
static size_t no_body(char *buffer, size_t size,
		      size_t nmemb, void *userdata)
{
	/* We are not interested in reading the body */
	return 0;
}

static size_t full_body(char *buffer, size_t size,
		        size_t nmemb, void *userdata)
{
	/* We are obliged to read the full body! */
	return size * nmemb;
}

int main(int argc, char *argv[]) {
	CURLcode res;
	char *url = NULL;

	res = curl_global_init(CURL_GLOBAL_ALL);
	if (CURLE_OK != res)
		return res;
	CURL *curl = curl_easy_init();
	if(curl) {
		curl_easy_setopt(curl, CURLOPT_URL, argv[1]);
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, no_body);
		curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_check);
		curl_easy_setopt(curl, CURLOPT_HEADERDATA, curl);
		res = curl_easy_perform(curl);
		printf("curl_easy_perform ended with %d\n", res);
		res = curl_easy_getinfo(curl, CURLINFO_REDIRECT_URL, &url);
		printf("curl_easy_getinfo: %d, Redirect to: %s\n", res, url);

		/* Take 2: now reading full body /!\ D.o.S. is possible */
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, full_body);
		curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_check);
		curl_easy_setopt(curl, CURLOPT_HEADERDATA, curl);
		res = curl_easy_perform(curl);
		printf("curl_easy_perform ended with %d\n", res);
		res = curl_easy_getinfo(curl, CURLINFO_REDIRECT_URL, &url);
		printf("curl_easy_getinfo: %d, Redirect to: %s\n", res, url);
	}
	curl_easy_cleanup(curl);
	curl_global_cleanup();
	return 0;
}

```

run:
```
$ valgrind --leak-check=full ./bug https://1fichier.com/?12345678901234567890
==4558== Memcheck, a memory error detector
==4558== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4558== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4558== Command: ./bug https://1fichier.com/?12345678901234567890
==4558== 
We got 302: Continue.
Header: Server: nginx

+curl_easy_getinfo: 0, Redirect to: (null)
Header: Date: Mon, 18 Nov 2019 15:53:43 GMT

+curl_easy_getinfo: 0, Redirect to: (null)
Header: Content-Type: text/html; charset=utf-8

(...)
Header: Location: https://a-9.1fichier.com/p444444444

+curl_easy_getinfo: 0, Redirect to: (null)
Header: 

+curl_easy_getinfo: 0, Redirect to: (null)
curl_easy_perform ended with 23
curl_easy_getinfo: 0, Redirect to: (null)
We got 302: Continue.
Header: Server: nginx

+curl_easy_getinfo: 0, Redirect to: (null)
Header: Date: Mon, 18 Nov 2019 15:53:44 GMT

+curl_easy_getinfo: 0, Redirect to: (null)
Header: Content-Type: text/html; charset=utf-8

(...)
+curl_easy_getinfo: 0, Redirect to: (null)
Header: Location: https://a-9.1fichier.com/p444444444

+curl_easy_getinfo: 0, Redirect to: (null)
Header: 

+curl_easy_getinfo: 0, Redirect to: (null)
curl_easy_perform ended with 0
curl_easy_getinfo: 0, Redirect to: https://a-9.1fichier.com/p444444444
==4558== 
==4558== HEAP SUMMARY:
==4558==     in use at exit: 0 bytes in 0 blocks
==4558==   total heap usage: 336,449 allocs, 336,449 frees, 127,410,591 bytes allocated
==4558== 
==4558== All heap blocks were freed -- no leaks are possible
==4558== 
==4558== For counts of detected and suppressed errors, rerun with: -v
==4558== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```

This illustrate that we could naively think getting info on the location is simply a string manipulation function. Thus the alternative idea, same as we use the get_info on the HTTP Code on the header callback, do the same for the redirect URL.

On the header callback, we are immune to a "freing" syndrome that would prevent curl from returning the location, since when we read that precise header, it is in memory!

But as you can see, the dump_header function correctly dumps that there is a header with:
`Location: https://a-9.1fichier.com/p444444444`

But calling get_info for redirect url just after that returns NULL.

Valgrind reports no use of freed memory nor any remaining unfreed memory (added the global_init/global_cleanup for that).

### Conclusions:

The solutions (when HEAD is not usable) could be:
- accept the risk that the body is huge (risk we would like to mitigate for obvious security reasons)
- write your own code to extract the "Location"
- extract the code from libcurl (it is probably of better quality than home-made poorly tested code!) provided there is no license incompatibility.

Although that is "work as design", the current library does not cover this security risk nicely.

So yes, it "works as designed", but if you could **discuss that "design"** to include the use case in this report, that would be super nice.

Hence this is: **Feature Request/Whishlist** (whatever you call it!)

(As for my own case, I'll go with Jay's suggestion, because when HEAD works, there is no issue!)

**Comment by bagder** [comment]
> the current library does not cover this security risk nicely.

I disagree that it is a security risk (caused by libcurl). Of course an application would never allocate more memory than is sensible - and if the response isn't valuable in the first place so why keep it in memory at all? We cannot protect applications against stupid developers.

Figuring out the redirect URL is a function call that simply is never called if an error is caught prior to where it would get invoked.

Changing `curl_easy_getinfo()` to also work when the transfer has failed and make that claim in the documentation would require a pretty significant effort but maybe we could get the information variables done at at a time. Pull-requests in this direction will be appreciated.

**Comment by Bylon2** [comment]
_"Excuse my French"_ (pun intended, as I am French).

My sentence was poorly worded, what I really meant is:

> There is a security risk, the current state of the library does not help to mitigate it.

You both acknowledged the security risk. It is indeed completely unrelated to libcurl.

When the server does not support HEAD and the client is interested only with the "headers" of the request (which is typical when expecting a "redirect"), the way some parts of `curl_easy_getinfo` are designed forbids their use in the mitigation of the issue.

Note that some parts of `curl_easy_getinfo` do actually work, like getting `RESPONSE_CODE`, as demonstrated in the example. You can use that in the first line of the header_callback, it works like a charm.

I have not tested all of them, but looking for example at `CURLINFO_CONTENT_LENGTH_DOWNLOAD_T`, I can think of many uses where it might be super useful to be able to have that value **before** reading the whole body : memory allocation, filtering "too big", etc... Also, once you have read the body, counting bytes is so easy that it looses a lot of its interest to have a function doing that. I guess since this one is a number, it could work the same as  `RESPONSE_CODE` (unlike the example in the libcurl documentation shows: testing the return code of `curl_easy_perform` first)

So indeed, we could say:

Having the result from **all** `curl_easy_getinfo` values **as soon as they are available** -in the headers- (and not at the end of the transfer if it worked!) would be very useful in many cases!

The feature request does not break compatibility with the existing behaviour, it just adds more possible uses of the library. Using this function after a successful `curl_easy_perform` should still work!

**Comment by bagder** [comment]
> You both acknowledged the security risk

Users who fail to read documentation and instead guess how things work and *guess wrong*, and then write application code based on said wrong guess can of course cause a security problem. But that's not limited to this functionality, to libcurl, or to any specific API. It goes with virtually all functions and I don't think this function is much different in that regard. So sure, it can be a security problem in the sense that all wrong assumptions can be.

> Having the result from all curl_easy_getinfo values as soon as they are available -in the headers- (and not at the end of the transfer if it worked!) would be very useful in many cases

I won't disagree with that. But I might not feel very strongly about it myself to put this very high up on my personal TODO-list...

**Comment by Bylon2** [comment]
Changed the title accordingly to the discussion.
It is indeed not at all a bug or a security risk due to the library and works as designed and documented.

**@Badger**, I read the documentation carefully, and explicitly said that I changed the example on purpose. It's not the point of this report since in that case I don't let libcurl handle the redirect but want to do it myself, but what would happen when libcurl handles the redirect and the server was hacked and responds with 10GB of data after a 302? As Jay pointed out, closing the socket can be suboptimal, but reading 10GB too!

"There is no defense against that" could be an answer... but I don't like it!

> I won't disagree with that. But I might not feel very strongly about it myself to put this very high up on my personal TODO-list...

100% Ok with that, there are probably more pressing matters!

**Suggest:** low priority?

**Comment by bagder** [comment]
We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document - and there they don't really have any priority. We basically drown in good ideas so they don't do much use in our tracker.

**Comment by Bylon2** [comment]
Agreed!
Close it.

Basically **http.c** from **line 3866** where is gets the content-length catches the idea quite well already:

> k->size = contentlength;
> k->maxdownload = k->size;
> /* we set the progress download size already at this point
>  just to make it easier **for apps/callbacks to extract this**
>  **info as soon as possible** */

although here it sets the progress meter, this "idea" could benefit other headers.

Thanks.
