### ISSUE TITLE
Curl Authentication failure on regular intervals due to 401 Authorization

### ISSUE THREAD

**Issue by Muruganfly03** [curl/curl#4616]
We are trying to hit APPD controller, on regular intervals we receive below error. I also provided the command which we used. Suggest any additional attribute required to ignore this Authorization error.

Command:

**curl -kv --user user@test1:$**** https://x.x.x.x:8181/controller/rest/applications?output=JSON |grep -i test_app**

* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.174.220.200...
* Connected to xxx.com (10.x.x.x port 8181 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using AES128-SHA
* Server certificate:
* 	 subject: 
* 	 start date: 2019-10-22 20:52:48 GMT
* 	 expire date: 2022-10-22 21:02:48 GMT
* 	 issuer: 
* 	 SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Server auth using Basic with user 'user@test1'
> GET /controller/rest/applications?output=JSON HTTP/1.1
> Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> User-Agent: curl/7.35.0
> Host: xxx.com:8181
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: BASIC realm="controller_realm"
< Date: Sun, 17 Nov 2019 13:48:03 GMT
< Content-Length: 0
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host xxx.com left intact
please check appd service broker or host controller

**Comment by dfandrich** [comment]
Note that you've just posted your username and password to the world. You
should change it before anything else.

**Comment by jay** [comment]
Your log doesn't show anything unusual. You may need to enable cookies and first use a different URL to login, for example , like https://x.x.x.x:8181/controller/auth?action=login

I suggest you ask in the [appdynamics forums](https://community.appdynamics.com/t5/Forums-Community-AppDynamics/ct-p/Discussions).
