### ISSUE TITLE
IPv6 fails to be enabled (even with --enable-ipv6) when strict compiler is used

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#4617]
### I did this

Configured like so:

```
export CC=gcc

./configure CFLAGS="-m32 -std=c17 -fPIC -ffunction-sections -fdata-sections -Os -s -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -I/root/sources/mbedtls/include" LDFLAGS="-Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections" --disable-debug --disable-curldebug --enable-optimize --enable-shared=no --enable-static --without-ssl --without-zlib --without-ca-bundle --without-ca-path --without-libssh2 --without-librtmp --disable-versioned-symbols --disable-cookies --enable-hidden-symbols --disable-ares --enable-ipv6 --disable-dict --disable-file --disable-ftp --disable-imap --disable-pop3 --disable-rtsp --disable-smtp --disable-manual --disable-telnet --disable-tftp --disable-ldap --disable-ldaps --disable-gopher --disable-unix-sockets --disable-smb --disable-smbs --disable-verbose --disable-doh --disable-mime --disable-netrc --disable-parsedate --disable-dnsshuffle --disable-ntlm-wb --disable-progress-meter --with-mbedtls="/root/sources/mbedtls/include"
```

Using devtoolset-8 on CentOS 7. `cc --version` returns: `cc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
`

IPv6 is not being built (see above and you'll see it's being passed correctly)...

```
  IPv6:             no      (--enable-ipv6)
```
... because `getaddrinfo` is not being properly detected:

```
checking if getaddrinfo can be linked... no
checking if getaddrinfo might be used... no
```

Digging into the config.log and I can see where things go screwy:

```
configure:33130: checking if getaddrinfo can be linked
configure:33151: gcc -o conftest -m32 -std=c17 -fPIC -ffunction-sections -fdata-sections -s -fvisibility=hidden -fno-unwind-tables -fno-asynchronous-unwind-tables -isystem /root/sources/mbedtls/include -Werror-implicit-function-declaration -Os -Wno-system-headers  -I/root/sources/mbedtls/include/include -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections -L/root/sources/mbedtls/include/lib conftest.c -lmbedtls -lmbedx509 -lmbedcrypto  >&5
conftest.c: In function 'main':
conftest.c:203:15: error: implicit declaration of function 'getaddrinfo' [-Werror=implicit-function-declaration]
       if(0 != getaddrinfo(0, 0, 0, 0))
               ^~~~~~~~~~~
cc1: some warnings being treated as errors
configure:33151: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.haxx.se/mail/"
| #define PACKAGE_URL ""
| #define PACKAGE "curl"
| #define VERSION "-"
| #define OS "x86_64-pc-linux-gnu"
| #define _FILE_OFFSET_BITS 64
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define CURL_DISABLE_FTP 1
| #define CURL_DISABLE_FILE 1
| #define CURL_DISABLE_LDAP 1
| #define CURL_DISABLE_LDAPS 1
| #define CURL_DISABLE_RTSP 1
| #define CURL_DISABLE_DICT 1
| #define CURL_DISABLE_TELNET 1
| #define CURL_DISABLE_TFTP 1
| #define CURL_DISABLE_POP3 1
| #define CURL_DISABLE_IMAP 1
| #define CURL_DISABLE_SMB 1
| #define CURL_DISABLE_SMTP 1
| #define CURL_DISABLE_GOPHER 1
| #define TIME_WITH_SYS_TIME 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_TIME_H 1
| #define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1
| #define USE_MBEDTLS 1
| #define STDC_HEADERS 1
| #define HAVE_MALLOC_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_SYS_SELECT_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_SYS_IOCTL_H 1
| #define HAVE_SYS_UIO_H 1
| #define HAVE_ASSERT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_ARPA_INET_H 1
| #define HAVE_NET_IF_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_SYS_UN_H 1
| #define HAVE_LINUX_TCP_H 1
| #define HAVE_NETINET_TCP_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_PARAM_H 1
| #define HAVE_TERMIOS_H 1
| #define HAVE_TERMIO_H 1
| #define HAVE_SGTTY_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_ALLOCA_H 1
| #define HAVE_TIME_H 1
| #define HAVE_PWD_H 1
| #define HAVE_UTIME_H 1
| #define HAVE_SYS_POLL_H 1
| #define HAVE_POLL_H 1
| #define HAVE_SYS_RESOURCE_H 1
| #define HAVE_LIBGEN_H 1
| #define HAVE_LOCALE_H 1
| #define HAVE_ERRNO_H 1
| #define HAVE_STDBOOL_H 1
| #define HAVE_ARPA_TFTP_H 1
| #define HAVE_SYS_WAIT_H 1
| #define HAVE_SETJMP_H 1
| #define HAVE_VARIADIC_MACROS_C99 1
| #define HAVE_VARIADIC_MACROS_GCC 1
| #define TIME_WITH_SYS_TIME 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_TIME_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_STRUCT_TIMEVAL 1
| #define SIZEOF_SIZE_T 4
| #define SIZEOF_LONG 4
| #define SIZEOF_INT 4
| #define SIZEOF_SHORT 2
| #define SIZEOF_TIME_T 4
| #define SIZEOF_OFF_T 8
| #define SIZEOF_CURL_OFF_T 8
| #define HAVE_LONGLONG 1
| #define HAVE_LL 1
| #define HAVE_BOOL_T 1
| #define CURL_SA_FAMILY_T sa_family_t
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_POLL_H 1
| #define HAVE_SYS_POLL_H 1
| #define HAVE_STRUCT_SOCKADDR_STORAGE 1
| #define HAVE_SIGNAL_H 1
| #define HAVE_SIG_ATOMIC_T 1
| #define RETSIGTYPE void
| #define HAVE_SYS_SELECT_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define SELECT_TYPE_ARG1 int
| #define SELECT_TYPE_ARG234 fd_set *
| #define SELECT_TYPE_RETV int
| #define SELECT_QUAL_ARG5 
| #define SELECT_TYPE_ARG5 struct timeval *
| #define HAVE_SELECT 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define RECV_TYPE_ARG1 int
| #define RECV_TYPE_ARG2 void *
| #define RECV_TYPE_ARG3 size_t
| #define RECV_TYPE_ARG4 int
| #define RECV_TYPE_RETV int
| #define HAVE_RECV 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define SEND_TYPE_ARG1 int
| #define SEND_TYPE_ARG3 size_t
| #define SEND_TYPE_ARG4 int
| #define SEND_TYPE_RETV int
| #define SEND_QUAL_ARG2 const
| #define SEND_TYPE_ARG2 void *
| #define HAVE_SEND 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_MSG_NOSIGNAL 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_ALARM 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_STRING_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_LIBGEN_H 1
| #define HAVE_BASENAME 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_CONNECT 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_FCNTL 1
| #define HAVE_FCNTL_O_NONBLOCK 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_SOCKET_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_IFADDRS_H 1
| #define HAVE_FREEIFADDRS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_XATTR_H 1
| #define HAVE_FSETXATTR 1
| #define HAVE_FSETXATTR_5 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_STDLIB_H 1
| /* end confdefs.h.  */
| 
| 
|       /* includes start */
| #ifdef HAVE_WINDOWS_H
| #  ifndef WIN32_LEAN_AND_MEAN
| #    define WIN32_LEAN_AND_MEAN
| #  endif
| #  include <windows.h>
| #  ifdef HAVE_WINSOCK2_H
| #    include <winsock2.h>
| #    ifdef HAVE_WS2TCPIP_H
| #       include <ws2tcpip.h>
| #    endif
| #  endif
| #endif
| /* includes end */
|       /* includes start */
| #ifdef HAVE_SYS_TYPES_H
| #  include <sys/types.h>
| #endif
| #ifdef HAVE_SYS_SOCKET_H
| #  include <sys/socket.h>
| #endif
| /* includes end */
|       /* includes start */
| #ifdef HAVE_SYS_TYPES_H
| #  include <sys/types.h>
| #endif
| #ifdef HAVE_NETDB_H
| #  include <netdb.h>
| #endif
| /* includes end */
| 
| int main (void)
| {
| 
|       if(0 != getaddrinfo(0, 0, 0, 0))
|         return 1;
| 
|  ;
|  return 0;
| }
| 
configure:33159: result: no
configure:33321: checking if getaddrinfo might be used
configure:33337: result: no
```

### I expected the following

Successful detection of getaddrinfo (and other functions that fail to be correctly detected) and thus successful IPv6 detection and enablement.

### curl/libcurl version

7.67.0

### operating system

CentOS 7 compiled with devtoolset-8 with default warnings.

**Comment by wyattoday** [comment]
I can work around this problem by adding `-D_GNU_SOURCE` to the CFLAGS, but should this be necessary? I really don't know the answer to that. We didn't need it in the past (but maybe because the previous versions of the compilers implicitly enabled that).

Food for thought, I guess.

**Comment by MarcelRaad** [comment]
Maybe IPv6 was actually silently disabled before? If `getaddrinfo` was not found, `configure` said `IPv6: yes`, but `ENABLE_IPV6` was not set. This was fixed for 7.67.0 in https://github.com/curl/curl/commit/07f8986051b5ad8f6f34b82036f615c70f7fbb3e.

As `getaddrinfo` is not ISO C but a POSIX extension amd you're specifying `-std=c17` rather than `-std=gnu17`, this sounds to me like it's on purpose.

**Comment by bagder** [comment]
I'm a bit with @MarcelRaad here.

My Linux man page for `getaddrinfo` says it needs three include files and those three include files are included in the configure check and yet the error 

`conftest.c:203:15: error: implicit declaration of function 'getaddrinfo' [-Werror=implicit-function-declaration]`

 ... indicates that it didn't get any prototype for the function with the includes.

**Comment by wyattoday** [comment]
Honestly, the more I think about this, this is less a bug report (the correct std selector of `-std=gnu17` as @MarcelRaad suggested, or using `-std=c17` with `-D_GNU_SOURCE`) and more of a feature request. Namely, I know I want to build curl. And I know I want to build it with a particular spec standard (in this case c17) to match other libraries being built for the same end-product. But I didn't (but now) know that I needed to explicitly request GNU-extensions for libcurl to build in which the way I expected.

So, I guess my feature request is this: if the build script knows curl is being compiled with a gnu compiler, and `_GNU_SOURCE` is not defined, then define it so that the appropriate features can be compiled.

**Comment by bagder** [comment]
I would even argue that asking for c17 when building curl is questionable. curl is c89 compliant. curl doesn't need nor use any gnu extensions.

**Comment by wyattoday** [comment]
> I would even argue that asking for c17 when building curl is questionable.

I'm aware that curl doesn't require newer standards, but as a rule we like to compile all of our dependencies with the same compiler options (including code standard) as our products themselves.


> "curl is c89 compliant. curl doesn't need nor use any gnu extensions."

Right, but it's odd that current gcc compiler versions require `_GNU_SOURCE` to be defined (or `-std=gnu17` as a standard) for the available POSIX features to actually work as expected.

It seems like modern gcc versions, when a C standard is defined as part of the compile options (whether it's a modern one like c17, or an older one like c99) it actually drops the [`_POSIX_C_SOURCE` value](http://man7.org/linux/man-pages/man7/feature_test_macros.7.html).

That's why I'm suggesting a feature in either the config script or an early config header of something along the lines of:

```
#ifndef _POSIX_C_SOURCE
    #define _POSIX_C_SOURCE 1
#endif
```

Which would tell gcc to use "POSIX.1-1990" features if the compiler had decided to drop them because a C standard was specified.

Tell me your thoughts.

**Comment by dfandrich** [comment]
Are you saying that you compile your dependencies without POSIX support? Then I
guess curl won't do for you because it requires POSIX for some features. But,
if you compile your dependencies with the same options and your dependencies
need POSIX, then I suggest you enable POSIX for *all* your dependencies, curl
included, with an appropriate _POSIX_C_SOURCE value.

**Comment by wyattoday** [comment]
> Are you saying that you compile your dependencies without POSIX support?

No, that's not what I'm saying. I'm saying we compile with a specific C standard across all of our dependencies. Some dependencies require POSIX features (including our main products).

Ultimately what I'm suggesting is working around a bug (or, let's call it a quirk) in gcc. Namely, specify _POSIX_C_SOURCE if it's not already defined (when using gcc).

**Comment by dfandrich** [comment]
But, your toolchain is running (implicitly) without POSIX support due to a
combination of compiler and compiler flags, right? How is that a curl problem?

**Comment by wyattoday** [comment]
It's not curl's problem. Hence: feature request. Workaround bug in gcc.

Look, this problem is already solved for us. We've dug into, figured out what we needed to do, documented it internally, etc., etc. We're all set.

What I'm suggesting is to help the next person that comes along and assumes things will work correctly when a C standard is explicitly defined in the compile flags. Namely, curl depends on POSIX, so if a modern gcc is used and the correct POSIX flags are not defined, then define them.

That's all I'm suggesting: save some people some time.

I'm not suggesting something radical. curl already works around bugs in compilers, environments, build systems, etc. I'm suggesting one more workaround for a bug/quirk in a modern, popular compiler.

Either way (whether the suggestion is adopted or not) this document exists to expose this problem.

**Comment by dfandrich** [comment]
I've previously relied on this behaviour of gcc/glibc by deliberately not
enabling the POSIX (or X/Open) options in order to ensure that my programs are
not relying on any POSIX/X/Open features. If curl were to turn these on behind
my back, then this would type of testing would silently fail. Since curl will
work around the absence of these features already (albeit, with reduced
functionality) it's certainly possible that some people want this behaviour.
Printing a warning at configure time might be useful or even a configure option
to do this, but I'd be against turning it on unconditionally.

**Comment by MarcelRaad** [comment]
> If curl were to turn these on behind
my back, then this would type of testing would silently fail. Since curl will
work around the absence of these features already (albeit, with reduced
functionality) it's certainly possible that some people want this behaviour.
Printing a warning at configure time might be useful or even a configure option
to do this, but I'd be against turning it on unconditionally.

Fully agree - or even an error if the user explicitly requests IPv6 but it cannot be enabled? I always miss the warnings in the huge configure output when I don't read every single line while trying to find something specific.

**Comment by bagder** [comment]
Summary: "Fixing" this in configure risks hurting some use cases while this is a problem that is already easily fixed (or worked around) by the user by simply not insisting on this compiler option.

This makes me lean heavily towards: *leave as is*.

**Comment by MarcelRaad** [comment]
Having merged https://github.com/curl/curl/pull/4662, there will be a behavior change again for the next version: general IPv6 support will be enabled even without `getaddrinfo` and the configure output will show `IPv6: yes` again. But DNS resolution to IPv6 addresses still won't work if there's neither `getaddrinfo` nor c-ares available. I don't think there's any sane way to do that which doesn't break some use cases.

**Comment by jay** [comment]
> general IPv6 support will be enabled even without getaddrinfo

Can you clarify what is `curl -V` expected to show now without getaddrinfo, will it show IPv6 in features even when there's actually no IPv6 support? Because if so that would be confusing.

**Comment by jay** [comment]
Nevermind, I see what you did, the IPv6 addresses are supported just no resolve. Guess I should've read the issue first...

**Comment by bagder** [comment]
Closing and leaving as-is.
