### ISSUE TITLE
FTP EPSV not working.

### ISSUE THREAD

**Issue by mithunFeb** [curl/curl#4619]
FTP EPSV 2nd connection not working. On debuging found issue in below line.
https://github.com/curl/curl/blob/821171dbfd72982607701054158764577efefb04/lib/hostip.c#L180

Here pointer increment happens incorrectly in my project. Moved the increment operation to next line and resolved issue

*ptr = (char)TOLOWER(*name);
ptr++; name++;

**Comment by jay** [comment]
> Here pointer increment happens incorrectly in my project.

Not a bug. Can you explain what makes you think that? Did you change anything else? If not then it probably was a server issue that resolved itself.

**Comment by bagder** [comment]
If that line would be wrong, lots of things would break for lots of users - and not just for FTP EPSV.

Precedence rules in C makes the `*`-operator happen on the value before the increment so your edit shouldn't change the logic of that code.

**Comment by mithunFeb** [comment]
Issue is happening due to some parenthisis in macro TOLOWER
#define TOLOWER(x)  (tolower((int)  ((unsigned char)x)))
Put a debug print and noticed ptr (variable name) address incremented by 4bytes instead of 1byte, i.e
(int *)++ is happening instead of (char *)++.

**Comment by bagder** [comment]
Hm, that's interesting. What compiler does that? Incrementing by 4 instead of 1 surely will cause a read outside of the buffer (crash) occasionally?

Does it make anything different if the `x` is parenthesized an extra level? Like:
~~~c
 #define TOLOWER(x) (tolower((int) ((unsigned char)(x))))

**Comment by jay** [comment]
that still doesn't make any sense, the associativity is right to left
(unsigned char)*name++
name++ evaluates to name then it's dereferenced then cast to unsigned char
(unsigned char)(*name++) is the same

**Comment by bagder** [comment]
Agreed!

**Comment by mithunFeb** [comment]
It seems to be issue with my project. Please close the ticket. Thank you

**Comment by jay** [comment]
> And would this be the reason for misbehaviour?

No. Probably a server issue. No evidence of a bug here.
