### ISSUE TITLE
DOH: possible double invocation of de_cleanup()

### ISSUE THREAD

**Issue by niallor** [curl/curl#4626]
https://github.com/curl/curl/blob/8487734e8bc2783448da135355e05302947bf830/lib/doh.c#L1001

It looks to me that this line should be moved inside the following **else** block, before 
`return CURLE_OK;`, so that, whenever this **return** is by-passed, *de_cleanup()* 
is not invoked a second time before `return CURLE_COULDNT_RESOLVE_HOST;`

**Comment by bagder** [comment]
Looks like a correct observation. Will you submit a PR to fix it?

**Comment by niallor** [comment]
On 21 Nov 2019, at 14:48, Daniel Stenberg wrote:

> Looks like a correct observation. Will you submit a PR to fix it?

It’s covered by [#4629](https://github.com/curl/curl/pull/4629).

/Niall

**Comment by bagder** [comment]
Fixed since #4629 was merged!
