### ISSUE TITLE
No Output on SMTP

### ISSUE THREAD

**Issue by entc** [curl/curl#4634]
Hi,
using the libcurl library I'm running into an issue. I used the recommended way to send an email by SMTP and the curl library. All went fine and the email was queue at the mail server. Unfortunately using the following lines

curl_easy_setopt (curl, CURLOPT_WRITEFUNCTION, curl_smtp__write);
curl_easy_setopt (curl, CURLOPT_WRITEDATA, output_stream);

have no effect and the 'curl_smtp__write' is not called. The output_stream stays empty.
This might be not needed in most of the cases, but it would be good to fetch information received by the email server like

250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 5C9611A1A60

to follow the queue ID's trace later. I'm aware of the verbose output, but it would be more convenience to receive the output, without activating the verbose messages.

Cheers

**Comment by bagder** [comment]
That data you say you want to see look like *headers*, they are never sent to the `WRITEFUNCTION`, they're sent to the `HEADERFUNCTION`...

**Comment by entc** [comment]
Hi,
thanks! I used the headers functions now and I got the data from the SMTP response.

This can be closed? It might be good to have a hint in the WRITEFUNCTION section of the documentation.

Cheers

**Comment by bagder** [comment]
> It might be good to have a hint in the WRITEFUNCTION section of the documentation.

What exactly do you propose it should say there? That it doesn't get headers passed to it?

**Comment by bagder** [comment]
No response and I think these man pages are already explaining this.
