### ISSUE TITLE
HTTP/2 performance issue(s) in multi-handle 

### ISSUE THREAD

**Issue by martinschmatz** [curl/curl#4639]
I did this: I'm using libcurl and its multi-handle functionality to repeatedly issue small GET requests to a server using HTTP/2 (with nghttp2) with TLS1.3 (via OpenSSL). 
For tests, I'm using a single connection (= a single multi-handle), pipelined easy-handle requests/streams, with up to 64 streams in the connection. Whenever an easy-handle is complete after a `curl_multi_perform`, I remove it, get the data, and (re-)add it to the multi-handle again for the next GET request. 

I expected the following: Given that all these HTTP/2 requests go to the same server, I'd expected full connection re-use for the easy-handles with virtually no time spent to establish connectivity after a connection is established and maintained. One key value proposition of HTTP/2 is efficient use of streams inside a connection. 

I see this: The time spent in the `CURLM_STATE_CONNECT` state in `multi_runsingle` (in `multi.c`) is in the order of 40us (small Xeon CPU, 10G network, hop over a single switch inside data-center). This seems to be the - by far - limiting factor for request throughput (resulting a ~5x performance penalty [!!] compared to a native nghttp2 implementation).
One reason might be that `data->conn` is detached and NULL-ified when a request is complete, but there's most probably more than that. 

Side remark: While searching for limiting factor for throughput performance, I also had the impression that each easy-handle is executing its own `select` call (potentially followed by an `SSL_read`), even though another easy-handle might already have read (all recent) HTTP/2 data for a specific connection from the wire, such that this data would already be available in the nghttp2 buffers.

Potential mitigation: 
1) Refine the connection reuse for repeatedly used easy-handles inside a multi-handle in case of re-using the same HTTP/2 connection.
2) Only check/read the "wire" for a specific HTTP/2 connection once in `curl_multi_perform`

Any suggestion of how the above mitigations could be addressed and implemented? 
I'd be willing to help, but I wouldn't call myself as being fluid in cURL source code.

curl/libcurl version: Latest version built from sources from git
operating system: Linux Ubuntu 18.04 LTS

**Comment by bagder** [comment]
Thanks for your report. I'm sure there are several areas in the code where we can improve HTTP/2 performance. One of the primary challenges with HTTP/2 in libcurl is that the API is transfer-oriented and protocol agnostic. The main state machine and a lot of internal machinery is written to work with all the protocols. HTTP/2 is one of the now three primary HTTP versions libcurl supports, and they're all pretty different from each other implementation wise.

I think maybe we can focus on your primary observation and leave the "side remarks" for later to stay focused and address one thing at a time?

> The time spent in the CURLM_STATE_CONNECT state in multi_runsingle (in multi.c) is in the order of 40us. This seems to be the - by far - limiting factor for request throughput

Arriving to this state, it should basically be a single call to `curl_connect()`, which should find an existing connection to add the transfer to and then it should move on to the next state. (Most of the matching of existing connections etc is done from within `create_conn`.) How many connections do you typically have alive when you see this? Any chance you can narrow down further what parts of create_conn it is that takes time? Is it `ConnectionExists()` ?

**Comment by martinschmatz** [comment]
I'll try to better instrument the sequence of operations in `CURLM_STATE_CONNECT` and come back.

To your questions:
- I'm totally fine to focus on the primary observation (time spent in `CURLM_STATE_CONNECT` for cases where a HTTP2/TLS1.3 connection already exists) and leave the "side remarks" (number of `select`/`SSL_read` calls for same connection) for later - one step after the other is always a good approach...
- I'm having a single connection active when I measure timing, with up to 64 streams (= repeatedly used easy-handles) inside this connection.

**Comment by martinschmatz** [comment]
I've instrumented the `CURLM_STATE_CONNECT` some more, in particularly `curl_connect()`. 
Unfortunately, there seems not a single culprit to be responsible for he latency, but the latency is rather distributed over many, many calls...:-(

I also quickly tried to memorize `data->conn` for an easy-handle in a variable which is persistent, and then re-use it when using the same easy-handle again. Unfortunately, I wasn't able to catch all setup sequences such that this didn't work either.

**Comment by bagder** [comment]
"memorizing" `data->conn` is not the answer to any problems anyway, on the contrary. When a transfer is done it is removed from a connection and has no association with it anymore. It cannot "remember" what connection it was on and use that for anything usable later on. A subsequent request may or may not use that same connection, depending on many different factors.

I would propose that you create some sort of synthetic performance test or application to share with us, that when used illustrates the slowness you're talking about so that others get an easier entry into this and can offer help.

**Comment by bagder** [comment]
> the latency is rather distributed over many, many calls...:-(

You can't even identify a first set that would be good candidates to take a look at?

**Comment by martinschmatz** [comment]
I've tried to instrument, but had to recognize that qualitatively, the many sub-routine calls each add a small amount, which nevertheless add up. 
I'm on vacation till early January, at which point I'll repeat the instrumentation and will come back with a table. Sorry for the delay.

**Comment by bagder** [comment]
Anything more on this? We don't really have anything actionable in this report...

**Comment by bagder** [comment]
Lack of details and specifics.
