### ISSUE TITLE
curl_multi_wait returns immediately when no handle are registered.

### ISSUE THREAD

**Issue by thothothotho** [curl/curl#4643]
### I did this

Given a multi handle with no easy_handle, do this:

    curl_multi_wait(handle, nullptr, 0, 10, &remainingTransfert);

The call returns immediately.

### I expected the following

The call should wait 10ms.

Documentation says

 > It will block until activity is detected on at least one of the handles or timeout_ms has passed

As a rigorist logician, if there is no handle, the first condition cannot happen, then the 
timeout should be honored.  

Either the doc is wrong, or there is a bug.
It makes more sense to do as the doc says.  This is the choice made by `select`, by the way.   From http://man7.org/linux/man-pages/man2/select.2.html

>       Some code calls select() with all three sets empty, nfds zero, and a
>       non-NULL timeout as a fairly portable way to sleep with subsecond
>       precision.

Doing that way avoid callers to makes a special case for the empty multi handle.  And this also avoid a special case in `curl_multi_wait`. I suppose there must be a

        if(handle_empty)
               return;
        select(...)

somewhere in the implementation of `curl_multi_wait`.  This could be simplified.

### curl/libcurl version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system
Linux 4.15.0-69-generic #78-Ubuntu SMP Wed Nov 6 11:30:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
It also happens on Windows.

**Comment by bagder** [comment]
The fourth paragraph in the man page explicitly highlights what you talk about:

> If no extra file descriptors are provided and libcurl has no file descriptor to offer to wait for, this function will return immediately.

This is also the reason we introduced `curl_multi_poll()` recently. It is basically identical to `curl_multi_wait()` but without that behavior.

I don't think this is a bug.

**Comment by thothothotho** [comment]
Sorry I missed that one.  Maybe the doc could be updated for lazy people like me who don't read the whole doc (add something that hints there is more specfic details on the behavior, later in the doc; or group everything in one section of the doc)

`curl_multi_poll`/`curl_multi_wakeup` are exactly what I need, but I've never discovered them.  I strongly suggest you do more marketing about them in the documentation, because it is the best API.  They seem reference from nowhere.  You should mention them in https://curl.haxx.se/libcurl/c/libcurl-multi.html and/or https://curl.haxx.se/libcurl/c/curl_multi_wait.html

  * google curl_multi_wait returns about 6 000 results.
  * google curl_multi_poll returns just 300 results.

This is probably normal if the feature is very recent.

Thanks a lot.

**Comment by bagder** [comment]
> for lazy people like me who don't read the whole doc

It is by definition impossible to write complete docs for those who don't read the complete docs.
