### ISSUE TITLE
curl_multi_perform still return still_running as 1 even network restart

### ISSUE THREAD

**Issue by ckt1010** [curl/curl#4648]
### I did this
I called curl_easy_perform to post http request to transfer object, then it in easy_transfer loop and calling curl_multi_perform again and again. At this time, I restart my network.
Then it loop calling curl_multi_perform forever and always return still_running as 1.
### I expected the following
It should return still_running as 0, when I restart network.
### curl/libcurl version
7.67.0
[curl -V output]
curl 7.67.0 (arm-unknown-linux-gnueabihf) libcurl/7.67.0
Release-Date: 2019-11-06
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp
Features: AsynchDNS IPv6 Largefile UnixSockets
### operating system
Linux dra7xx-evm 4.4.84 #15 SMP PREEMPT Tue Nov 12 14:51:43 CST 2019 armv7l GNU/Linux

**Comment by bagder** [comment]
This is probably just a variation of the old [why doesn't curl return error when unplugging the network](https://curl.haxx.se/docs/faq.html#Why_doesn_t_curl_return_an_error).

If curl doesn't get an error returned from the underlying socket or function calls it uses, then it won't detect any problem. I'm not sure "restarting the network" actually affects existing sockets at all.

**Comment by ckt1010** [comment]
Sorry, I should ready it clearly. I will use connect timeout to fix it.
