### ISSUE TITLE
Configuring with custom openssl directory fails

### ISSUE THREAD

**Issue by chorman0773** [curl/curl#4666]
I'm building a project on GNU/Linux which has all of its dependencies self-contained (with a few exceptions, namely libc). Curl and openssl are both such dependencies. Because I need https, I am building curl against the project's openssl, or rather attempting to. 
When I try to configure openssl it can't detect the openssl headers which I am passing in via CPPFLAGS. This causes it to error if I explicitly put `--with-ssl` and not be configured for ssl if I do not. 
These are my CPPFLAGS on the configure command line. 
`CPPFLAGS="-I$ac_abs_top_srcdir/openssl/include -I$ac_abs_top_srcdir/zlib"` (called from a top level configure script, so `$ac_abs_top_srcdir` is being replaced with the absolute path to the source directory).
Configuring w/o --with-ssl, I can see that the expansion looks correct for both (where the -I was replaced with -isystem). Additionally, I have confirmed that the headers configure is looking for, (including `openssl/ssl.h` are all present at the configuration directory. 
openssl is present on the system, however the system version conflicts with the project-level version at link time, and the ability to have all of the dependencies self-contained is part of the project itself.

**Comment by dfandrich** [comment]
I suggest following the instructions for using a custom OpenSSL in INSTALL.md
and report back your success or lack thereof.

**Comment by chorman0773** [comment]
The relevant instructions are
```
 If you have OpenSSL installed, but with the libraries in one place and the
header files somewhere else, you have to set the `LDFLAGS` and `CPPFLAGS`
environment variables prior to running configure.  Something like this should
work:

    CPPFLAGS="-I/path/to/ssl/include" LDFLAGS="-L/path/to/ssl/lib" ./configure
```
Correct?
In that case, this is indeed what I already do (though to be fair, at configuration time, the libraries do not exist in the path I have set, as openssl has yet to be built, however, by the time curl is built, openssl will have been built, my project's Makefile ensures this).

**Comment by dfandrich** [comment]
That's the third and least desirable option. The PKG_CONFIG_PATH option is the
most reliable when it's available.

**Comment by chorman0773** [comment]
I can't trust that the information provided by the openssl build (which is not installed, only built), will be correct. Even if it is made to be correct, the include path and the library path will not have the same immediate parent and may not be  (as the include path is in the source directory for openssl, and the library path is the build directory for openssl, which are only guaranteed to be the same if the build directory of the top-level project is the same as the source directory, something which is not supported by the project).

**Comment by bagder** [comment]
> though to be fair, at configuration time, the libraries do not exist in the path I have set

How do you expect configure and curl to work with the headers that don't exist?

**Comment by jay** [comment]
> I can't trust that the information provided by the openssl build (**which is not installed, only built**), will be correct.

This is the problem, **emphasis mine**. curl configure doesn't work that way, you'll have to provide a location to an installed openssl. Set the prefix when you are building openssl then install it to that prefix, then you can give that to curl configure.

**Comment by chorman0773** [comment]
The issue then becomes, where would I install openssl. If I pick a location in the build tree, I have to move a huge amount of build steps to project-level configure. I also have to make sure that location is available whenever I might try to reconfigure and build curl. Its also an additional step which becomes redundant when I consolidate all the dependencies. If I pick a system location, then I violate one of the premises for the project, that it is completely self-contained, and it also adds steps which have to be done manually by the builder (and may not even be possible to do so, in some circumstances). 
It also seems like an issue that curl's configure can't detect headers which I have confirmed to exist, with the flags being set correctly, which is what the issue was originally about.

**Comment by bagder** [comment]
configure uses the installed openssl headers (and library) to figure out details about the particular version and existing capabilities. That's by design.

> It also seems like an issue that curl's configure can't detect headers which I have confirmed to exist, with the flags being set correctly

Then please explain what you did, and show us your `config.log` from that invocation and I would think we can figure it out.

**Comment by bagder** [comment]
No response and I think configure works in this regard as I use it plenty to link with OpenSSL in custom directories.
