### ISSUE TITLE
Error: An unknown option was passed in to libcurl when using CURLOPT_SSL_ENABLE_ALPN

### ISSUE THREAD

**Issue by shailcompsit** [curl/curl#4668]
### What I did,
As per this [man page](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_ENABLE_ALPN.html) for `CURLOPT_SSL_ENABLE_ALPN`, the option is enabled by default, and we can see the ALPN extension set in Client Hello using Wireshark. However, I want to disable that option, so that ALPN extension is not present in Client Hello (TLS Handshake).  I tried below code, 

`CURLcode res = CURLE_OK; `
`res = curl_easy_setopt(curl_, CURLOPT_SSL_ENABLE_ALPN, 0L); `
`if(res == CURLE_OK){`
         `cout<<"CURLOPT_SSL_ENABLE_ALPN to 0L res = "<<res;`
`}else{`
         `cout<<"Error: res = "<<res<<"\t"<<curl_easy_strerror(res);`
`}`

### Output: 
Error: res = 48    An unknown option was passed in to libcurl
### I expected the following
CURLOPT_SSL_ENABLE_ALPN to 0L res = 0
### curl/libcurl version
libcurl Version: 7.67.0
openssl version: OpenSSL 1.1.0l
### libcurl configuration options
`./configure --prefix= " << full path to installation directory >> "
--disable-manual --enable-ipv6 --disable-ntlm-wb 
--without-krb4 --without-gssapi 
--with-ssl=" << full path to openssl folder containing library and include files >> " 
--without-gnutls --without-polarssl --without-cyassl 
--without-nss --without-axtls --without-libmetalink 
--without-libssh2 --disable-ldap --without-libidn 
LDFLAGS="-Wl,-rpath -Wl, << full path to openssl library folder >> "`
### operating system
Linux, MACOSX

Even though this option throws error in MacOSX also, ALPN extension is not present in TLS Handshake on MacOSX
Is this option deprecated? Or am I missing something here?

**Comment by jay** [comment]
Those options erroneously require HTTP/2 support:
https://github.com/curl/curl/blob/2e9b725f67d49a9d7a1f053fe52dd4920c9ab1ad/lib/setopt.c#L2615-L2622

If that is your issue then please try the fix in #4672. If that doesn't work then give us this output:
~~~c
    curl_version_info_data *info = curl_version_info(CURLVERSION_NOW);
    printf("SSPI is %s\n", ((info->features & CURL_VERSION_SSPI) ? "on" : "off"));
    printf("HTTP2 is %s\n", ((info->features & CURL_VERSION_HTTP2) ? "on" : "off"));
    printf("%s\n", curl_version());
~~~

**Comment by shailcompsit** [comment]
@jay Replicated the changes committed by you. This solves the issue. 
I can see the output as expected: "CURLOPT_SSL_ENABLE_ALPN to 0L res = 0"
Also, monitored the TLS Handshake, and ALPN extension is absent in Client Hello now. 
Thanks a lot!
When can we expect the next release of libcurl ?

**Comment by bagder** [comment]
> When can we expect the next release of libcurl ?

See the [pending release-notes](https://curl.haxx.se/dev/release-notes.html) page: January 8th 2020 is the scheduled release date for the coming 7.68.0 release.

You can however always download the current state from git or as a [daily snapshot](https://curl.haxx.se/snapshots/) to try out the coming changes even before they ship!

**Comment by jay** [comment]
Thanks
