### ISSUE TITLE
there is memory leak when use https url

### ISSUE THREAD

**Issue by SRC-xiaojin** [curl/curl#4675]
~~~c
pCurl = curl_easy_init();
    multi_handle = curl_multi_init();
if(pCurl && multi_handle){
        std::string url = _"https://***.***.***";_
        headerlist = curl_slist_append(headerlist, "Content-Type: application/json;charset=UTF-8");
        curl_easy_setopt(pCurl, CURLOPT_HTTPHEADER, headerlist);

        /* what URL that receives this POST */
        curl_easy_setopt(pCurl, CURLOPT_URL, url.c_str());
        if (dwTimeout != 0)
        {
            long lTimeout = dwTimeout;
            curl_easy_setopt(pCurl, CURLOPT_TIMEOUT, lTimeout);
            curl_easy_setopt(pCurl, CURLOPT_CONNECTTIMEOUT, lTimeout);
            curl_easy_setopt(pCurl, CURLOPT_NOSIGNAL,1L);
        }

        //CURLOPT_POST
        curl_easy_setopt(pCurl, CURLOPT_POST, 1L);
        curl_easy_setopt(pCurl, CURLOPT_POSTFIELDS, strPostData.c_str());
        curl_easy_setopt(pCurl, CURLOPT_POSTFIELDSIZE, strPostData.size());
        curl_multi_add_handle(multi_handle, pCurl);
        curl_multi_perform(multi_handle, &still_running);

        while(still_running) {
            struct timeval timeout;
            int rc; /* select() return code */
            CURLMcode mc; /* curl_multi_fdset() return code */

            fd_set fdread;
            fd_set fdwrite;
            fd_set fdexcep;
            int maxfd = -1;

            long curl_timeo = -1;

            FD_ZERO(&fdread);
            FD_ZERO(&fdwrite);
            FD_ZERO(&fdexcep);

            /* set a suitable timeout to play around with */
            timeout.tv_sec = 1;
            timeout.tv_usec = 0;

            curl_multi_timeout(multi_handle, &curl_timeo);
            if(curl_timeo >= 0) {
                timeout.tv_sec = curl_timeo / 1000;
                if(timeout.tv_sec > 1)
                    timeout.tv_sec = 1;
                else
                    timeout.tv_usec = (curl_timeo % 1000) * 1000;
            }

            /* get file descriptors from the transfers */
            mc = curl_multi_fdset(multi_handle, &fdread, &fdwrite, &fdexcep, &maxfd);

            if(mc != CURLM_OK) {
                fprintf(stderr, "curl_multi_fdset() failed, code %d.\n", mc);
                break;
            }

            /* On success the value of maxfd is guaranteed to be >= -1. We call
             select(maxfd + 1, ...); specially in case of (maxfd == -1) there are
             no fds ready yet so we call select(0, ...) --or Sleep() on Windows--
             to sleep 100ms, which is the minimum suggested value in the
             curl_multi_fdset() doc. */

            printf("maxfd is [%d]\n",maxfd);
            if(maxfd == -1) {
                /* Portable sleep for platforms other than Windows. */
                struct timeval wait = { 0, 100 * 1000 }; /* 100ms */
                rc = select(0, NULL, NULL, NULL, &wait);
            }
            else {
            /* Note that on some platforms 'timeout' may be modified by select().
               If you need access to the original value save a copy beforehand. */
                rc = select(maxfd + 1, &fdread, &fdwrite, &fdexcep, &timeout);
           }

            switch(rc) {
                case -1:
                    /* select error */
                    break;
                case 0:
                default:
                /* timeout or readable/writable sockets */
                    printf("perform!\n");
                    curl_multi_perform(multi_handle, &still_running);
                    printf("running: %d!\n", still_running);
                    break;
           }
       }
       
       /* always cleanup */
       curl_multi_remove_handle(multi_handle,pCurl);

       /* free slist */
       curl_slist_free_all(headerlist);
       
       curl_easy_cleanup(pCurl);

       curl_multi_cleanup(multi_handle);
   }
~~~
These is my source code, when I change https to http, there is no memory leak.

**Comment by dfandrich** [comment]
On what version of libcurl and TLS backend do you see this?

**Comment by bagder** [comment]
Also: on what OS is this running and how did you detect the leak?

**Comment by SRC-xiaojin** [comment]
> On what version of libcurl and TLS backend do you see this?



> Also: on what OS is this running and how did you detect the leak?

Os is centos 3.10.0-514.21.1.el7.x86_64.I detect my process, the memory gradually increase.this is my build config.
curl-config --configure
 '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--enable-hidden-symbols' '--enable-ipv6' '--enable-ldaps' '--enable-manual' '--enable-threaded-resolver' '--with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt' '--with-gssapi' '--with-libidn' '--with-libssh2' '--without-ssl' '--with-nss' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro '

is is releated with option '--without-ssl' ?

**Comment by SRC-xiaojin** [comment]
> On what version of libcurl and TLS backend do you see this?

libcurl version is 7.29.0 .
curl-config --configure
'--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-static' '--enable-hidden-symbols' '--enable-ipv6' '--enable-ldaps' '--enable-manual' '--enable-threaded-resolver' '--with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt' '--with-gssapi' '--with-libidn' '--with-libssh2' '--without-ssl' '--with-nss' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro '

is is releated with option '--without-ssl' ?

**Comment by bagder** [comment]
1. The fact that it grows for a while is not necessarily a proof it is a leak
2. You're using a "vintage" libcurl version we released early 2013.
3. I checked the commit messages since that release. We've mentioned "memory leak" in at least 118 fixes since then.

If you indeed suffer from a bug, chances are we already fixed it years ago.

**Comment by bagder** [comment]
Due to the old age of the reported used libcurl I'm closing this issue with no action.

If you can show an actual leak with a *recent* libcurl, please let us know and we can reopen and start investigating.
