### ISSUE TITLE
[Question] Where is the default STRING_USERAGENT set?

### ISSUE THREAD

**Issue by tarnh** [curl/curl#4676]
Dear developers,

I'm trying to understand where the default STRING_USERAGENT is set.

Am I right that it's considered in either url.c or http.c and can be set through setopt.c?
```
  if(data->set.str[STRING_USERAGENT]) {
    Curl_safefree(conn->allocptr.uagent);
    conn->allocptr.uagent =
      aprintf("User-Agent: %s\r\n", data->set.str[STRING_USERAGENT]);
    if(!conn->allocptr.uagent)
      return CURLE_OUT_OF_MEMORY;
  }
```

But where is the default value, e.g. `curl/7.67.0`, coming from?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

libcurl has/uses no default user-agent header!
