### ISSUE TITLE
checksrc: ASSIGNWITHINCONDITION check broken

### ISSUE THREAD

**Issue by jay** [curl/curl#4683]
### I did this

Recent changes in ba82673 to improve on the ASSIGNWITHINCONDITION regex check actually [broke it further](https://github.com/curl/curl/commit/ba82673dac3e8d00a76aa5e3779a0cb80e7442af#diff-840acaaca93c176729713fd1ce05a623R460). Some suggestions have been made in the linked to discussion. I'd prefer we move the discussion here for tracking purposes.

To test regexes and see colored results (which you may find very helpful) I suggest https://regex101.com in PCRE mode which is pretty close to perl.

### I expected the following

A single line if(expression) should always be checked by ASSIGNWITHINCONDITION.

### curl/libcurl version

master 147fa06 2019-12-07

**Comment by bagder** [comment]
I propose we revert the change and instead fix the macros so that we don't do multiple expressions like that one the same line. We discourage that in the code style document already!

**Comment by danielgustafsson** [comment]
Regardless of what we do, we should probably change the macros to match the mandated style. The bigger question is, should we at all attempt this since we cannot test the full expression due to the single-line mode of checksrc? Maybe enabling the MSVC Level4 assignment-within-conditional warning in a CI build is a better catch-all (C4706)?

**Comment by jay** [comment]
I'd rather have something that works somewhat than not at all. I also like that we can disable warnings in checksrc. Anyway though I don't think we should be doing assignments in conditionals ever so it seems appropriate to enable that MSVC warning if it's not already.

**Comment by bagder** [comment]
Having  an **assignment-within-conditional** warning enabled in compiler should only be a good thing for us!
