### ISSUE TITLE
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection

### ISSUE THREAD

**Issue by akitaTian** [curl/curl#4684]
### I did this
./curl --ciphers ALL  https://IP  -k   --> report curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection 

but when i order the ALL ciphers by SSLv2, SSLv3, TLS...  it's work
And server side is IIS6.0

The SSLScan output 
     Supported Server Cipher(s):
Preferred TLSv1.0  128 bits  RC4-MD5
Accepted  TLSv1.0  128 bits  RC4-SHA
Accepted  TLSv1.0  112 bits  DES-CBC3-SHA
Accepted  TLSv1.0  56 bits   DES-CBC-SHA
Preferred SSLv3    128 bits  RC4-MD5
Accepted  SSLv3    128 bits  RC4-SHA
Accepted  SSLv3    112 bits  DES-CBC3-SHA
Accepted  SSLv3    56 bits   DES-CBC-SHA 

the ALL string contains 'Supported Server Cipher'
### I expected the following
the ciphers list string ALL can access the https site

### curl/libcurl version

curl   version 7.61.1 
----------
compile options 
./configure --prefix=${OUTPUT_DIR}/curl --disable-shared --enable-static --disable-ldap --disable-ldaps --enable-ipv6 --enable-ares=${OUTPUT_DIR}/c-ares --with-zlib=${OUTPUT_DIR}/zlib --with-ssl=${OUTPUT_DIR}/openssl

openssl  version 1.0.2k
----------
compile options 
./config --prefix=/root/openssl1_0_2k  shared zlib threads sctp enable-krb5 --with-krb5-flavor=MIT enable-weak-ssl-ciphers enable-ssl2 enable-ssl3

[curl -V output]
----------
curl 7.61.1-DEV (x86_64-unknown-linux-gnu) libcurl/7.61.1-DEV OpenSSL/1.0.2k zlib/1.2.7 c-ares/1.14.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

### operating system
CentOS Linux release 7.0

**Comment by jay** [comment]
curl passes the `--ciphers` string to OpenSSL [SSL_CTX_set_cipher_list](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_cipher_list.html). According to their [doc for ALL](https://www.openssl.org/docs/man1.0.2/man1/ciphers.html#CIPHER-STRINGS) it should use all ciphers. What happens when you use the openssl tool?
~~~
openssl s_client -cipher ALL -servername httpbin.org -connect httpbin.org:443
~~~
(Replace httpbin.org with your hostname or IP. If it's an IP then remove the -servername option.)

**Comment by akitaTian** [comment]
> openssl s_client -cipher ALL -servername httpbin.org -connect httpbin.org:443

**Comment by akitaTian** [comment]
> curl passes the `--ciphers` string to OpenSSL [SSL_CTX_set_cipher_list](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_cipher_list.html). According to their [doc for ALL](https://www.openssl.org/docs/man1.0.2/man1/ciphers.html#CIPHER-STRINGS) it should use all ciphers. What happens when you use the openssl tool?
> 
> ```
> openssl s_client -cipher ALL -servername httpbin.org -connect httpbin.org:443
> ```
> 
> (Replace httpbin.org with your hostname or IP. If it's an IP then remove the -servername option.)

the OpenSSl output 
CONNECTED(00000003)
140291652220816:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 364 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1575916670
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

**Comment by jay** [comment]
This is not a curl issue. The server may be so old it can't handle a max of TLS 1.2 in the handshake. You can try this:
curl [--tls-max](https://curl.haxx.se/docs/manpage.html#--tls-max) 1.0 https://IP

**Comment by akitaTian** [comment]
> This is not a curl issue. The server may be so old it can't handle a max of TLS 1.2 in the handshake. You can try this:
> curl [--tls-max](https://curl.haxx.se/docs/manpage.html#--tls-max) 1.0 https://IP

this work,  
But I don't know why I sort ciphers  is ok  ?   -.-

**Comment by akitaTian** [comment]
At the same time, I used tcpdump to view the ssl package. Only the cipher suite order is different.

**Comment by bagder** [comment]
Since you can repro the same behavior with the openssl cmdline tool then the issue is in OpenSSL or even in how TLS is designed to work, not a curl issue. I don't see anything for us to do here!

**Comment by akitaTian** [comment]
Thanks anyway！
