### ISSUE TITLE
which version can test http3?

### ISSUE THREAD

**Issue by CodeLife2012** [curl/curl#4687]
https://daniel.haxx.se/blog/tag/quic/

`curl --http3-direct ` seems not work on latest  version.

```
curl 7.67.0 (x86_64-apple-darwin18.7.0) libcurl/7.67.0 SecureTransport zlib/1.2.11
Release-Date: 2019-11-06
````

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

Read up on HTTP/3 in curl [here](https://github.com/curl/curl/blob/master/docs/HTTP3.md)
