### ISSUE TITLE
Coveralls isn't solid enough

### ISSUE THREAD

**Issue by bagder** [curl/curl#4694]
### I did this

I've tried to rely on coveralls to tell us data about test coverage. It keeps reporting ridiculous numbers and very often shows bogus red warnings like this:

![Screenshot_2019-12-10 Fixes for `--disable-doh` by MarcelRaad · Pull Request #4692 · curl curl](https://user-images.githubusercontent.com/177011/70508121-0be19480-1b2e-11ea-87bd-20ec6a2cd754.png)

(screenshot from #4692 - the coverage was never 81% so this claimed 7% decrease is a complete lie)

### I expected the following

Reliable info. As this works now, I think it typically does more harm than good: it generates red builds completely arbitrary and even when green the numbers it shows are then hard to trust.

### Action

The test coverage is valuable information but changes very rarely. We could probably change the coveralls to get run in a cronjob somewhere every now and then instead. I intend to switch it off from the CI system due to its "unreliablity".

**Comment by dfandrich** [comment]
There's at least one other code coverage tool I've seen used in projects:
https://github.com/marketplace/codecov  I have no idea if it's appropriate for
curl, though.
