### ISSUE TITLE
Curl not sending http CONNECT to proxy

### ISSUE THREAD

**Issue by hugo-marello** [curl/curl#4700]
### I did this
I've downloaded the curl source code version 7.67.0, unzipped and ran `./configure`, `sudo make`, `sudo make install`.
I'm trying to make a curl request for https site. For example I did: `curl -v https://google.com`. But it fails to send the package to my proxy.

### I expected the following
Google index page

### curl/libcurl version
Curl version 7.67.0, installed from source.
~~~
curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2q zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
~~~

### operating system
Deepin 15.11 (based on debian version 9.0)

### the output i received

```
* Rebuilt URL to: https://google.com/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to (nil) (127.0.0.1) port 3128 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to 127.0.0.1:3128 
* Curl_http_done: called premature == 0
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:3128 
curl: symbol lookup error: curl: undefined symbol: curl_mime_free
```
I also captured the tcp packages sent by curl, what was odd is that there wasn't any CONNECT http requests, which is supposed to start http connections to the proxy (when ssl is involved).
[capture image](http://imgsafe.org/image/00ede872e3)

**Comment by jay** [comment]
> curl: symbol lookup error: curl: undefined symbol: curl_mime_free

> curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.52.1

curl is using an older version of libcurl, which is noted in the WARNING:

> WARNING: curl and libcurl versions do not match. Functionality may be affected.

You can try `sudo ldconfig` and if that doesn't work then you will either have to add libcurl's library path so that the loader can find it or add an rpath in the curl tool when you build it. For example if the curl tool is in /usr/local/bin then libcurl should be in /usr/local/lib:
LDFLAGS="-Wl,-rpath,/usr/local/lib" ./configure ...

> curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:3128 

I'm not sure if this is related, fix the version mismatch then try again and let us know.

**Comment by hugo-marello** [comment]
So unfortunately my OS crashed and I had to install another. This time installed directly from apt repository. No issues with proxy so far. I'm going to close the issue.
