### ISSUE TITLE
curl_exec returns {"statusCode":403,"message":"CSRF token missing"}

### ISSUE THREAD

**Issue by ScgBob** [curl/curl#4708]
<!-- Only file bugs here! Ask questions on the mailing lists https://curl.haxx.se/mail/

Version 7.67.0

Using curl to verify a PayPal IPN message. This has worked for several years but suddenly stopped working in November. I believe BlueHost upgraded to version 7.67.0 around November 15, 2019.
The return from curl_exec is: {"statusCode":403,"message":"CSRF token missing"}

### I did this
		curl_setopt($payPal, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
		curl_setopt($payPal, CURLOPT_POST, 1);
		curl_setopt($payPal, CURLOPT_RETURNTRANSFER,1);
		curl_setopt($payPal, CURLOPT_POSTFIELDS, $parameters);
		curl_setopt($payPal, CURLOPT_SSL_VERIFYPEER, 1);
		curl_setopt($payPal, CURLOPT_SSL_VERIFYHOST, 2);
		curl_setopt($payPal, CURLOPT_FORBID_REUSE, 1);
		curl_setopt($payPal, CURLOPT_CONNECTTIMEOUT, 30);
		curl_setopt($payPal, CURLOPT_HTTPHEADER, array('Connection: Close'));
		curl_setopt($payPal, CURLOPT_CAINFO, "/Documents/cacert.pem");

		$result = curl_exec($payPal);
### I expected the following
$result = "VERIFIED"

### curl/libcurl version
7.67.0
[curl -V output]

### operating system

BlueHost: PHP version 7.0.33, cURL information: 7.67.0

**Comment by bagder** [comment]
1. `curl_exec` is a PHP/CURL function call, not a libcurl call. You should probably direct your question to the team behind that.
2. Getting JSON back means that the HTTP transfer worked. Then curl did its job. The *contents* is not curl's problem.
