### ISSUE TITLE
ALPN, server did not agree to a protocol

### ISSUE THREAD

**Issue by dhineshbabuelango** [curl/curl#4711]
I am trying to route a traffic from nginx to AWS loadbalncer, when I try to curl the nginx url which has to send the traffic to an aws loadbalancer which is listening on TCP 443, i am getting ALPN server did not agree to a protocol
~~~
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 593 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: *.internal.pcpc.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=*.internal.pcpc.com
* 	 start date: Fri, 13 Dec 2019 03:17:12 GMT
* 	 expire date: Wed, 13 Jan 2021 04:17:12 GMT
* 	 issuer: C=SG,O=ndipcpc,OU=ndipcpc,ST=SG,CN=ndipcpc,L=SG
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /otp HTTP/1.1
> Host: nginx.internal.pcpc.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 426 Upgrade Required
< Server: nginx/1.10.3 (Ubuntu)
< Date: Fri, 13 Dec 2019 11:36:52 GMT
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host nginx.internal.pcpc.com left intact

**Comment by bagder** [comment]
Did you expect it to not get that or what do you say the problem is with this?

**Comment by dhineshbabuelango** [comment]
Actually when I try to curl the load balancer directly it works, but when I try to curl the load balancer from another https url i am getting this error, the only change is my nginx.internal.pcpc.com is listening on tls 443 and the load balancer is listening on TCP 443.

**Comment by bagder** [comment]
So one of them supports ALPN and the other not? It seems you don't ask for HTTP/2 anyway so what's the practical impact of this?

(Side-note: TLS has no port number, it is in the transport layer so port 443 is in TCP.)

**Comment by dhineshbabuelango** [comment]
I am trying to do a path based routing to a loadbalancer which listens on TCP 443 from nginx

**Comment by bagder** [comment]
And how is this ALPN detail relevant for that mission?

**Comment by bagder** [comment]
`server did not agree to a protocol` is not a problem for curl, just a plain statement of fact and is also very common.
