### ISSUE TITLE
Document the need for CURL_STATICLIB better?

### ISSUE THREAD

**Issue by mvittiglio** [curl/curl#4716]
This is by design. The header files are generic and can be shared and used for multiple builds and even multiple targets and architectures. This is not a bug.

_Originally posted by @bagder in https://github.com/curl/curl/issues/2196#issuecomment-360915806_

Could we perhaps get some output indicating that CURL_STATICLIB needs to be defined after the build is completed? I discovered this solution on my own but it definitely took me by surprise as the build process obscured the CURL_STATICLIB definition from me so I could only assume that the "include" directory that was in the build location was set for the resulting artifact. Even an "IF YOU'RE USING STATIC TO BUILD IN WINDOWS THEN REMEMBER THIS PREPROCESSOR DIRECTIVE" message would be helpful. 

Anyhoo, just my 2 cents but thanks regardless for this amazing bit of software. Have a happy holidays.

**Comment by bagder** [comment]
It is only needed when you build with a static libcurl and sure, feel free to suggest where and how we should document this better.

**Comment by mvittiglio** [comment]
https://github.com/curl/curl/compare/master...mvittiglio:patch-1 @bagder

**Comment by bagder** [comment]
Awesome!

Please submit that as a pull request and we can take it from there.

**Comment by mvittiglio** [comment]
DOH! Sorry, I usually don't edit from GitHub directly so muscle memory failed. Here you go! https://github.com/curl/curl/pull/4721

**Comment by jay** [comment]
Landed in b0a9e3c
