### ISSUE TITLE
Cross-site Request Forgery Problem

### ISSUE THREAD

**Issue by ScgBob** [curl/curl#4718]
<!-- Only file bugs here! Ask questions on the mailing lists https://curl.haxx.se/mail/
I have been using this code with a PayPal IPN program for years and it has always worked. Now it appears version 7.67.0 fails to pick up the CSRF token and return it.

		curl_setopt($payPal, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
		curl_setopt($payPal, CURLOPT_POST, 1);
		curl_setopt($payPal, CURLOPT_RETURNTRANSFER,1);
		curl_setopt($payPal, CURLOPT_POSTFIELDS, $parameters);
		curl_setopt($payPal, CURLOPT_SSL_VERIFYPEER, 1);
		curl_setopt($payPal, CURLOPT_SSL_VERIFYHOST, 2);
		curl_setopt($payPal, CURLOPT_FORBID_REUSE, 1);
		curl_setopt($payPal, CURLOPT_CONNECTTIMEOUT, 30);
		curl_setopt($payPal, CURLOPT_HTTPHEADER, array('Connection: Close'));
		curl_setopt($payPal, CURLOPT_CAINFO, "/Documents/cacert.pem");

		$result = curl_exec($payPal);

$result == {"statusCode":403,"message":"CSRF token missing"}

This code works in version 7.58.0.

### I expected the following
$result == "VERIFIED"
### curl/libcurl version

[curl -V output]

### operating system
PHP version 7.0.33 running on Blue Host shared hosting.

**Comment by jay** [comment]
As already explained in #4708, the server error you receive is not curl's problem. This is not a curl issue.
