### ISSUE TITLE
curl_easy_setopt man page: [Website bug] https://curl.haxx.se/libcurl/c/curl_easy_setopt.html not displaying linked pages

### ISSUE THREAD

**Issue by Bylon2** [curl/curl#4719]
### I did this
Browse (Firefox)
https://curl.haxx.se/libcurl/c/curl_easy_setopt.html

Click on any link of an "OPT" on the page, for example the first one:
https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html

It displays a page with only the title and no detail at all.

### I expected the following
To have the details of the OPT, since it is there in the github's man pages.

### curl/libcurl version
Website, assuming showing "last" version

### operating system
Linux

### more info
Sorry, "report a bug" on the page at https://curl.haxx.se/libcurl/c/ lead here.

I don't know how this website is related to the github, but indeed the "missing text" in the page can be read from the ma pages under opt/

The manpages seem correct.

The bug is about the **website**!

If the website is unrelated to this github, please just close this bug report... and then it would be fine to report to whoever manages the website!

**Comment by jay** [comment]
Yeah this is a big problem. CURLOPT pages are broken, they're missing the roffit generated content `<!-- generated with roffit -->`. Possibly due to recent changes in bagder/roffit @bagder?

**Comment by bagder** [comment]
Yes it seems I broke them. I'll fix them!

**Comment by Bylon2** [comment]
Many thanks in advance! It is easier to read the "_man_" on the website than browsing the opt/ on github and reading the source of the manpages!

**Comment by bagder** [comment]
I think it works now again. My web site fix from the other day was partial and broken.

**Comment by Bylon2** [comment]
Confirmed: it works at my place too. Thanks!

**Comment by bagder** [comment]
Thanks for the report!
