### ISSUE TITLE
HTTP upload used with -m switch does not stop / where is the process ?

### ISSUE THREAD

**Issue by willemijns** [curl/curl#4724]
### I did this
curl.exe -T d:\whatever.file http://bouygues.testdebit.info/ --limit-rate 0 -m 13
curl: (28) Operation timed out after 13000 milliseconds with 0 bytes received            

### I expected the following
stopping file sending on the internet = close curl app after 13 seconds... 

in fact, the file transfer continues after the 13 seconds in background.... where ? can not find the process on taskman.... the process is hidden  and lost by windows ???

you can test yourself, it is an public HTTP upload test server for anyone (to test internet upload BW  ;)

it is not a transfer from another software, i tested 5 times after 5 reboots... ALWAYS a few bytes/s 
BW before launching this curl command line... if file is big, it can last a long time...

### curl/libcurl version
[curl -V output]
curl 7.67.0 (x86_64-pc-win32) libcurl/7.67.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

### operating system
Windows 10 laste version

**Comment by jay** [comment]
If you ignore the template we can't help you. What did you do, What did you expect, `curl -V` or `curl_version()`, and your OS.

**Comment by willemijns** [comment]
Oops ! i did not deleted the first line and the whole message was considered as a message !

**Comment by bagder** [comment]
> in fact, the file transfer continues after the 13 seconds in background

No it doesn't. It stopped at that point and showed you that message. curl has no code for "continuing in the background".

**Comment by willemijns** [comment]
They are 2 troubles here:
1) the main trouble explained on the first message
2) displays "bytes received" as an download action. No ! it is an upload so it must be "bytes transferred/transmitted" ;)

Hmmmmmmmm..... if you limit-rate the transfer like "66K" ALL WILL BE GOOD, seems it is only when "--limit-rate" is equal to 0

**Comment by jay** [comment]
I tried [that same version of curl](https://curl.haxx.se/windows/) in Windows 10 just now and sending ceases immediately before curl terminates. I don't see how it could be otherwise unless some OS TCP queue continues to send from the queue which doesn't make any sense. I used NetMeter to confirm:

![netmeter](https://user-images.githubusercontent.com/965580/70948712-0bfbfb80-202a-11ea-9efa-a525a61de921.png)

**Comment by willemijns** [comment]
https://www.youtube.com/watch?v=aMYoanxVTc8

**Comment by jay** [comment]
In your video repro you are using Microsoft's packaged version of curl:
~~~
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
~~~

Either wireless packets are being retransmitted or there is some other OS queue. I tried on a Windows 10 (1809) x64 laptop just now with a broadcom wireless card and I tried it the farthest away from the base that I could go and I still can't reproduce that. Taskmgr shows sending drops immediately before curl termination.

**Comment by bagder** [comment]
> displays "bytes received" as an download action. No ! it is an upload so it must be "bytes transferred/transmitted" ;)

It shows the number of downloaded bytes transmitted, as that's what it decides to show as information when it gets aborted in a timeout like this. Most HTTP uploads will also get data downloaded so when that output says `0` it is an indication it stopped before any response was sent from the server.

> --limit-rate 0

What do you want to accomplish with setting the rate to zero?

**Comment by willemijns** [comment]
You right, old curl.exe version was on my c:\windows\system :-X

i added the good path for the 'curl -V' and the curl.exe commandfline bug line trouble still appears.

**Comment by willemijns** [comment]
> What do you want to accomplish with setting the rate to zero?

it was to use less date for my tests because i'm not on an unlimited data plan but big enough...  i removed the switch just for you... same result :-(  

So so strange than this commandline works only with a capped BW (66K in my example)

**Comment by willemijns** [comment]
```
cls
set pathh=C:\$TEST\
%pathh%curl -V
rem set added_option=--limit-rate 66K
%pathh%curl -T d:\file.file http://bouygues.testdebit.info/ -m 13
pause
`
```

**Comment by willemijns** [comment]
I give you the batch and the "file.file" file
http://dl.free.fr/qMokaJ9Y4
Test yourself....

```
cls
set pathh=C:\$TEST\
%pathh%curl -V
set added_option=--limit-rate 66K
%pathh%curl %added_option% -T d:\w10usb.svp http://bouygues.testdebit.info/ -m 13
echo OK
pause
%pathh%curl -T d:\w10usb.svp http://bouygues.testdebit.info/ -m 13
echo NOK
pause
```

**Comment by jay** [comment]
There's no reason to test further. This is not a curl issue.
