### ISSUE TITLE
How to use curl write an request by using HTTP/2

### ISSUE THREAD

**Issue by xp19870106** [curl/curl#4726]
like the title, how can i make a http2 request by using curl? In code not command line

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

See also: [CURLOPT_HTTP_VERSION](https://curl.haxx.se/libcurl/c/CURLOPT_HTTP_VERSION.html)
