### ISSUE TITLE
Create a http/2 stream and send data

### ISSUE THREAD

**Issue by xp19870106** [curl/curl#4727]
how to create a http/2 stream and use it to send data

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

Ask for HTTP/2 and use the suitable HTTP request you need.
