### ISSUE TITLE
unresolved external symbol SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by xp19870106** [curl/curl#4729]
### I did this
I build curl with the instructions in file winbuild\BUILD.WINDOWS.txt
the build command is "nmake /f Makefile.vc mode=dll WITH_SSL=dll"
but I get the following error 

Creating library ..\builds\libcurl-vc-x86-release-dll-ssl-dll-ipv6-sspi-obj-l
ib\libcurl.lib and object ..\builds\libcurl-vc-x86-release-dll-ssl-dll-ipv6-sspi
-obj-lib\libcurl.exp
openssl.obj : error LNK2019: unresolved external symbol _SSL_CTX_set_alpn_protos
 referenced in function _ossl_connect_step1
openssl.obj : error LNK2019: unresolved external symbol _SSL_get0_alpn_selected
referenced in function _ossl_connect_step2
openssl.obj : error LNK2019: unresolved external symbol _SSL_COMP_free_compressi
on_methods referenced in function _Curl_ossl_cleanup
..\builds\libcurl-vc-x86-release-dll-ssl-dll-ipv6-sspi-obj-lib\libcurl.dll : fat
al error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\link.exe"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

### curl/libcurl version
curl-7.67.0

### operating system
win7 64

**Comment by bagder** [comment]
That would indicate that you try to link with an old OpenSSL version that lacks this function but the header files curl found is newer (it then thinks the ALPN function exists).
