### ISSUE TITLE
src/tool_parsecfg.c:288 -- free(pathalloc) is not required in parseconfig()

### ISSUE THREAD

**Issue by bxac** [curl/curl#4730]
### I did this

mkdir build_x64_shared
cd build_x64_shared
cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_USE_WINSSL=ON -DCURL_WINDOWS_SSPI=ON -DCURL_STATICLIB=OFF -DCURL_STATIC_CRT=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF ..
cmake --build . --config Debug -- /m

### I expected the following

Expecting working curl.exe, but it fires debug assertion in debug_heap.cpp:996 ( _ASSERTE(__acrt_first_block == header); )

### curl/libcurl version

curl 7.68.0-DEV (Windows) libcurl/7.68.0-DEV Schannel
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI

### operating system

Microsoft Windows [Version 10.0.18362.535]

**Comment by dfandrich** [comment]
What command-line causes this?

**Comment by bagder** [comment]
(and the `free()` is obviously needed, as otherwise that function would leak that memory)

**Comment by bxac** [comment]
> What command-line causes this?

Just "curl.exe" w/o parameters.

> (and the free() is obviously needed, as otherwise that function would leak that memory)

Seems "pathalloc" isn't allocated from heap at this point.

**Comment by bagder** [comment]
> Seems "pathalloc" isn't allocated from heap at this point.

If it isn't, then it is NULL, right? Because if you can get it to be non-NULL and not allocated then I'm curious how!

**Comment by bxac** [comment]
No, it is not NULL (checked in VS debugger).

> Because if you can get it to be non-NULL and not allocated then I'm curious how!

I'm curious too. That's why I've created this issue instead of pull-request with fix.

**Comment by bagder** [comment]
If you run it in the debugger, how about setting a break-point on the first line of the function and just single-step until that `free()` and see where it gets assigned? It seems likely to be a call to `curl_maprintf()` ...

**Comment by bxac** [comment]
> where it gets assigned? It seems likely to be a call to curl_maprintf() ...

Yes, in line
        pathalloc = curl_maprintf("%s%s%ccurlrc", home, DIR_CHAR, prefix);

And if I add
        free(pathalloc);
after that line, I got assert there.

But free(home) works without assert.

**Comment by bagder** [comment]
Ah, it should be a `curl_free()` !

**Comment by bagder** [comment]
Will work on the fix in #4731
