### ISSUE TITLE
Error in json formatting

### ISSUE THREAD

**Issue by Xavier59** [curl/curl#4737]
### I did this

`curl  -H "Content-Type: application/json" http://localhost:8080/api/endpoint --proxy "localhost:8888" -d '{"kind":"test"}'`

I took example on the documentation to send the json data (https://gist.github.com/subfuzion/08c5d85437d5d4f00e58#curl-usage) : 
`-d '{"key1":"value1", "key2":"value2"}'`

### I expected the following

```
POST http://localhost:8080/api/endpoint HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.67.0
Accept: */*
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 16

{"kind":"test"}
```

### I got the following

```
POST http://localhost:8080/api/endpoint HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.67.0
Accept: */*
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 13


'{kind:test}'
```

### curl/libcurl version

```
curl 7.67.0 (x86_64-pc-win32) libcurl/7.67.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz
```

### operating system

Windows 10

**Comment by bagder** [comment]
This is not a bug. You followed a random advice on internet and it didn't do what you expected.

On Windows command prompts, single quotes don't work.

**Comment by jay** [comment]
To send that from the command line you'd have to use double quotes and escape the inner ones, like `"{\"kind\":\"test\"}"`
