### ISSUE TITLE
Missing STRINGPOINT   definition in curl.h

### ISSUE THREAD

**Issue by rammishr** [curl/curl#4739]
In curl.6.67.0 version following definition is missing in curl.h. 
  #define STRINGPOINT   CURLOPTTYPE_OBJECTPOINT
  #define SLISTPOINT   CURLOPTTYPE_OBJECTPOINT

This results in compilation failure on AIX with IBM xlc 13.1.3 compiler. 
This is because in else condition for CURL_ISOCPP, these definitions are missing in curl.h.
Adding them resolves the issue.

**Comment by bagder** [comment]
Thanks! Can you just verify that #4740 fixes it?

**Comment by rammishr** [comment]
thanks for the response. It fixes the issue.
