### ISSUE TITLE
LDAP and LDAPS not disabled while building 7.67.0 statically

### ISSUE THREAD

**Issue by rammishr** [curl/curl#4741]
I am seeing another issue on nt32 and nt64. 
when i perform a static build of curl-6.67.0 using static openssl 1.1.1d with following options, LDAP and LDAPS remains enabled. 

configure_options_disabled := --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-s
spi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-soname-bump

configure_options_without := --without-zlib --without-gnutls --without-libssh2 --without-librtmp --without-winidn --without-libidn --without-nghttp2

other_configure_options  += --enable-static --disable-shared

This result in compile time failures with errors as follows. 
libcurl_a.lib(ldap.obj) : error LNK2019: unresolved external symbol __imp_ldap_init referenced in function Curl_ldap

Following is the curl --version output. 

./curl --version
curl 7.67.0 (x86_64-pc-win32) libcurl/7.67.0 OpenSSL/1.1.1d
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI

**Comment by bagder** [comment]
1. Is `CURL_DISABLE_LDAP` defined in `lib/curl_config.h` after you ran configure?
2. Did you `make clean` before you did `make` again so that no old leftovers got in?

lib/ldap.c is the only file that uses `Curl_ldap()`, and it has an `#if` condition at the very top...

**Comment by rammishr** [comment]
I tried to find more information. 
So, the mentioned configuration was for UNIX platforms. 
For windows, we are building the burl as below.

 cd curl-src\winbuild
nmake nmake /f Makefile.vc mode=static WITH_DEVEL=<path_to_openssl> WITH_SSL=static ENABLE_IDN=no VC=14 MACHINE=x64

I did not find option to disable ldap or ldaps for this make option.

**Comment by jay** [comment]
I don't think that's possible in winbuild but you can try passing `CURL_DISABLE_LDAP` to the compiler yourself
nmake /E CC="cl /DCURL_DISABLE_LDAP" /f ....

**Comment by rammishr** [comment]
Thanks for the information. That helps.
