### ISSUE TITLE
The path of the header is not end with slash

### ISSUE THREAD

**Issue by lixiaomeng8520** [curl/curl#4746]
### I did this

I use `curl http://www.google.com -v` to print header:
`> GET http://www.google HTTP/1.1`
the path is not end with slash

### I expected the following

The path of the header is end with /
`> GET http://www.google/ HTTP/1.1`

### curl/libcurl version

curl 7.19.7

### operating system

CentOS release 6.5 (Final)

**Comment by jzakrzewski** [comment]
The curl version you're using is over 10 years old.
I have 7.47 at hand (also far from the newest) and it prints:
```
$ curl http://www.google.com -v
* Rebuilt URL to: http://www.google.com/
*   Trying 172.217.168.68...
* Connected to www.google.com (172.217.168.68) port 80 (#0)
> GET / HTTP/1.1
> Host: www.google.com

```

**Comment by bagder** [comment]
Out of date. Fixed since ages ago.
