### ISSUE TITLE
multi download files is more slowly？

### ISSUE THREAD

**Issue by panguclick** [curl/curl#4749]
### I did this
download file setting.

  /* set URL to get here */
  curl_easy_setopt(curl_handle, CURLOPT_URL, url_.c_str());
  curl_easy_setopt(curl_handle, CURLOPT_VERBOSE, 1L);
  /* enable TCP keep-alive for this transfer */
  curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPALIVE, 1L);
  /* keep-alive idle time to 120 seconds */
  curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPIDLE, 1200L);
  /* interval time between keep-alive probes: 60 seconds */
  curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPINTVL, 600L);
  curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_FAILONERROR, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_TIMEOUT, 1800);
  curl_easy_setopt(curl_handle, CURLOPT_CONNECTTIMEOUT, 100);
  curl_easy_setopt(curl_handle, CURLOPT_HEADERFUNCTION, write_header);
  curl_easy_setopt(curl_handle, CURLOPT_HEADERDATA, (void*)&headers);
  /* we pass our 'chunk' struct to the callback function */
  curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, (void*)this);
  /* send all data to this function  */
  curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, write_data);
  curl_easy_setopt(curl_handle, CURLOPT_XFERINFOFUNCTION, progress_callback);
  curl_easy_setopt(curl_handle, CURLOPT_PROGRESSDATA, this);
  curl_easy_setopt(curl_handle, CURLOPT_NOPROGRESS, 0L);
  curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0L);
  curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0L);
  //curl_easy_setopt(curl_handle, CURLOPT_FRESH_CONNECT, 1L);
  //curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_FOLLOWLOCATION, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_MAXREDIRS, 3L);
  curl_easy_setopt(curl_handle, CURLOPT_AUTOREFERER, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_LOW_SPEED_LIMIT, 1L);
  curl_easy_setopt(curl_handle, CURLOPT_LOW_SPEED_TIME, 5L);
  curl_easy_setopt(
      curl_handle, CURLOPT_USERAGENT,
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/36.0.1985.143 Safari/537.36");  // user-agent
  curl_easy_setopt(curl_handle, CURLOPT_FORBID_REUSE, 1L);
### I expected the following
I use curl to  download files. 
use it download more than one file, the download speed change to slow.
### curl/libcurl version
7.66.0
[curl -V output]

### operating system
windows 10

**Comment by jay** [comment]
> I use curl to download files.
> use it download more than one file, the download speed change to slow.

I don't understand the issue. Can you please be more specific, give us your curl_version() and a way to reproduce?

**Comment by panguclick** [comment]
> I don't understand the issue. Can you please be more specific, give us your curl_version() and a way to reproduce?

1）I use multiple threads at the same time and each thread creates a curl object with 
      CURL *curl = curl_easy_init();
2）each CURL object set the properties as follows：
     /* set URL to get here /
curl_easy_setopt(curl_handle, CURLOPT_URL, url_.c_str());
curl_easy_setopt(curl_handle, CURLOPT_VERBOSE, 1L);
/ enable TCP keep-alive for this transfer /
curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPALIVE, 1L);
/ keep-alive idle time to 120 seconds /
curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPIDLE, 1200L);
/ interval time between keep-alive probes: 60 seconds /
curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPINTVL, 600L);
curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
curl_easy_setopt(curl_handle, CURLOPT_FAILONERROR, 1L);
curl_easy_setopt(curl_handle, CURLOPT_TIMEOUT, 1800);
curl_easy_setopt(curl_handle, CURLOPT_CONNECTTIMEOUT, 100);
curl_easy_setopt(curl_handle, CURLOPT_HEADERFUNCTION, write_header);
curl_easy_setopt(curl_handle, CURLOPT_HEADERDATA, (void)&headers);
/* we pass our 'chunk' struct to the callback function /
curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, (void)this);
/* send all data to this function */
curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, write_data);
curl_easy_setopt(curl_handle, CURLOPT_XFERINFOFUNCTION, progress_callback);
curl_easy_setopt(curl_handle, CURLOPT_PROGRESSDATA, this);
curl_easy_setopt(curl_handle, CURLOPT_NOPROGRESS, 0L);
curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0L);
curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0L);
//curl_easy_setopt(curl_handle, CURLOPT_FRESH_CONNECT, 1L);
//curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
curl_easy_setopt(curl_handle, CURLOPT_FOLLOWLOCATION, 1L);
curl_easy_setopt(curl_handle, CURLOPT_MAXREDIRS, 3L);
curl_easy_setopt(curl_handle, CURLOPT_AUTOREFERER, 1L);
curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
curl_easy_setopt(curl_handle, CURLOPT_LOW_SPEED_LIMIT, 1L);
curl_easy_setopt(curl_handle, CURLOPT_LOW_SPEED_TIME, 5L);
curl_easy_setopt(
curl_handle, CURLOPT_USERAGENT,
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
"Chrome/36.0.1985.143 Safari/537.36"); // user-agent
curl_easy_setopt(curl_handle, CURLOPT_FORBID_REUSE, 1L);

3）Then multiple threads start the download task at the same time.

4) 
The result is that if only one thread took 10 seconds to download a file,
If there are three threads downloading the same url file at the same time, each writing to a different local file takes 60 seconds,
If there are six threads downloading the same url file at the same time, each writes a different local file, which takes 3 minutes.


As the number of simultaneous download tasks increases, the download time will increase dramatically.

**Comment by panguclick** [comment]
> > I use curl to download files.
> > use it download more than one file, the download speed change to slow.
> 
> I don't understand the issue. Can you please be more specific, give us your curl_version() and a way to reproduce?

**Comment by jay** [comment]
Ok. That doesn't sound like a curl issue. It could be but it's unlikely. Does it happen with a specific file or all files? Can you give us a self-contained example that can be used reproduce? Also we need the `curl_version()` please run that function and give us the output.

**Comment by panguclick** [comment]
> Ok. That doesn't sound like a curl issue. It could be but it's unlikely. Does it happen with a specific file or all files? Can you give us a self-contained example that can be used reproduce? Also we need the `curl_version()` please run that function and give us the output.

curl_version：
libcurl/7.66.0 Schannel WinIDN
