### ISSUE TITLE
Crash in Curl_connect 

### ISSUE THREAD

**Issue by xinyei** [curl/curl#4752]
#0  0x00007fd1aa10f4fd in malloc_consolidate () from /lib64/libc.so.6
#1  0x00007fd1aa111069 in _int_malloc () from /lib64/libc.so.6
#2  0x00007fd1aa113b4a in calloc () from /lib64/libc.so.6
#3  0x00007fd1ac881341 in Curl_connect () from /usr/lib/libcurl.so.4
#4  0x00007fd1ac8937a3 in multi_runsingle () from /usr/lib/libcurl.so.4
#5  0x00007fd1ac8944b9 in curl_multi_perform () from /usr/lib/libcurl.so.4

### I did this
No crash
### curl/libcurl version

[curl -V output]
7.40.0
### operating system
Linux version 4.9.32-15.41.amzn1.x86_64

**Comment by jay** [comment]
This doesn't appear to be a crash in curl. Also, you are using an old version of curl. I suggest using the latest version.
