### ISSUE TITLE
cURL Reset --dump-header File Contain

### ISSUE THREAD

**Issue by GaneJ** [curl/curl#4753]
### I did this
--dump-header
and download multiply files with that options.

### I expected the following
cURL reset my --dump-header "file contain" if there is no header receive by cURL.
for example:
My first header download www.example1.com/object.exe write by cURL on my --dump-header file, downloading the second object www.example2.com/object.exe without header information, cURL delete my previous header.
This happen when using cURL v7.67.0 but not with v7.65.3.

### curl/libcurl version
7.65.3 and 7.67.0

### operating system
Windows

**Comment by emilengler** [comment]
What do you expect? That it should append the new header to the file or that it should give an error that such a file exists?

**Comment by emilengler** [comment]
I'm not 100% sure though but I believe 4849267197682e69cfa056c2bd7a44acd123a917 is the "bad boy". Probably it is more a feature than a bug.

**Comment by jay** [comment]
It's a bug. I bisected it to b889408 (parallel transfers) but I'll check that commit as well.
~~~
curld --dump-header x httpbin.org/bytes/9 www.test.com && cat x
~~~
~~~
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.16.1
Date: Tue, 24 Dec 2019 22:20:47 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=20
X-DIS-Request-ID: 92fe6f159dfd17de61606c5b1d68155f
Location: https://www.test.com/

tion: 1; mode=block
Content-Length: 9
Connection: keep-alive
~~~
The headers from the first transfer are being overwritten by the second transfer.

**Comment by emilengler** [comment]
Should the header from the second transfer be appended to the file?

**Comment by jay** [comment]
> Should the header from the second transfer be appended to the file?

Yes.

**Comment by emilengler** [comment]
Will have a look at it

**Comment by emilengler** [comment]
Just played around with 4849267197682e69cfa056c2bd7a44acd123a917 which is **NOT** the cause of this bug

**Comment by emilengler** [comment]
It was indeed b88940850002a3f1c25bc6488b95ad30eb80d696 which broke it.

**Comment by emilengler** [comment]
I think the problem is that the new `per_transfer` is a linked list and all the sturcts (`outs`, `heads`, etc.) are not switching to `->next`. Therefore only the header of the first element is provided

**Comment by emilengler** [comment]
Should be fixed now :)
