### ISSUE TITLE
curl has bug in resolve

### ISSUE THREAD

**Issue by netroby** [curl/curl#4755]
I want to connect the target ip, with a domain name, but not in standard 80 port

```
[C:\~]$ curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL 

[C:\~]$ curl -v  --resolve api.demo.cn:9901:10.1.60.69  http://api.demo.cn:9901/hello -H 'Host: api.demo.cn'
* Added api.demo.cn:9901:10.1.60.69 to DNS cache
* Hostname api.demo.cn was found in DNS cache
*   Trying 10.1.60.69...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to api.demo.cn (10.1.60.69) port 9901 (#0)
> GET /hello HTTP/1.1
> Host: api.demo.cn:9901
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 500
< Server: nginx/1.15.1
< Date: Tue, 24 Dec 2019 11:28:45 GMT
< Content-Length: 0
< Connection: keep-alive
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host api.demo.cn left intact
* Added api.demo.cn:9901:10.1.60.69 to DNS cache
* Rebuilt URL to: api.demo.cn'/
* Could not resolve host: api.demo.cn'
* Closing connection 1
curl: (6) Could not resolve host: api.demo.cn'


```

The curl does not respect the Header setting.
why append port number in the Host string?

**Comment by falconindy** [comment]
Doesn't look like a bug in curl, but a problem with your usage.

You're using windows, so single quote characters are literal. 'Host: api.demo.cn' is treated as two words here -- `Host:` as the argument to -H, and ` .api.demo.cn'` as an additional non-option argument for curl to try to fetch.

Use double quotes instead.

**Comment by netroby** [comment]
![QQ截图20191225093709](https://user-images.githubusercontent.com/278153/71428202-3fa9e600-26fa-11ea-8684-4fce588fb2b0.png)

while using resolve, it Add Host with wrong string, port number should not in the Host header.

can u see it ?

@jay @falconindy

**Comment by netroby** [comment]
@bagder can u please see this?

**Comment by falconindy** [comment]
Why do you believe this is a bug? RFC2616 states that the header can and should include a port. Lack of a port in the value implicitly means the default port.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

So, curl is correct here because `api.demo.cn:9901` is a different host than `api.demo.cn`.

**Comment by netroby** [comment]
@falconindy ok, Now it's feature request. How to not force add port number with hostname.
Is it possible to let user decide how to make request. Not force just append the port number with hostname.
I really want 

```
Host: api.demo.cn
```
This is my want, but i can not do it with curl

**Comment by netroby** [comment]
Using -H , and double quote make it works

**Comment by netroby** [comment]
thanks @falconindy
