### ISSUE TITLE
CURLOPT_HEADERFUNCTION man page:

### ISSUE THREAD

**Issue by gevaerts** [curl/curl#4758]
the man page for CURLOPT_WRITEFUNCTION mentions that "the size of that data is nmemb; size is always 1", the man page for CURLOPT_HEADERFUNCTION mentions no constraints about size. I think it would be a good idea to clarify if this will also always be 1, or, if not, to explicitly mention that size!=1 might be the case.

**Comment by jay** [comment]
Why do we need to be explicit about it? I like that there's some wiggle room, also we'd have to go back to all previous versions to find out how it handles that to make sure it's correct.

**Comment by jay** [comment]
After reading #2787 I changed my mind. Also, I went all the way back (using git gui blame and repeatedly blamed parent) and it's always been 1. Thanks.
