### ISSUE TITLE
Android: curl return error "couldn't resolve host" when enable c-ares

### ISSUE THREAD

**Issue by thiennguu** [curl/curl#4760]
I build curl with option --enable-ares for android application. When I run my application, if I don't set dns server then curl always return error "couldn't resolve host". I didn't get this error when running on the desktop application. How I can fix it?

**Comment by jay** [comment]
Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
