### ISSUE TITLE
`curl_multi_poll` hangs forever on negative timeout

### ISSUE THREAD

**Issue by hamstergene** [curl/curl#4763]
### This program hangs forever

```
#include <curl/curl.h>

int main(int narg, char**argv) {
    curl_global_init( CURL_GLOBAL_ALL );
    CURLM* mh = curl_multi_init();
    curl_multi_poll( mh, 0, 0, /*timeout_ms*/-1, 0 );
}
```

### I expected the following

The function interface takes signed integer (`int`) it must be ready to handle negative numbers.

### curl/libcurl version

7.68.0-20191218

### operating system

macOS 10.14.6

**Comment by dfandrich** [comment]
Using a negative timeout is undocumented, so you're hitting undefined
behaviour. Don't do undefined things if you don't want to be surprised by what
happens.

**Comment by hamstergene** [comment]
Positive and zero are also undocumented. The is simply no documentation on which values are valid. One has to document something first before claiming that everything else is undocumented.

**Comment by jay** [comment]
It's implied though we should error if negative. I couldn't find a good error code for it so I've added one in #4765 and if approved that will address this issue in the release after next.

**Comment by tomalakgeretkal** [comment]
I don't understand why we cannot accept -1 for "forever" so that this functions like POSIX poll(). It's easy to make it behave properly with expiry timeouts: I'd submitted a PR for it before realising that this new validation had been added, which breaks my fix. https://github.com/curl/curl/pull/4932
