### ISSUE TITLE
Windows getenv() and GetEnvironmentVariable() are not the same

### ISSUE THREAD

**Issue by jay** [curl/curl#4774]
@cmb69 [reported](https://curl.haxx.se/mail/lib-2020-01/0006.html) on the mailing list that Windows environment variables set via [SetEnvironmentVariable](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setenvironmentvariable) are visible to [GetEnvironmentVariable](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable) but not to [getenv](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=vs-2019). I've confirmed this.

Some builds of Windows php for their own API putenv call SetEnvironmentVariable instead of putenv. That can lead to a [bug](https://bugs.php.net/bug.php?id=79051). In that case a user  set some PROXY variables via php's putenv and when curl retrieved them via getenv they were not found. (Christoph please correct this if I misinterpreted)

### Related issues

cmb69's e-mail also points out getenv is not thread safe but I assume he means if the environment block is modified. This is a well known issue for various runtimes and perhaps we should warn about using putenv in the thread safety guidelines.

The curl tool's GetEnv already uses GetEnvironmentVariable instead of getenv and there is a comment *"Don't use getenv(); it doesn't find variable added after program was started"*. Frankly that doesn't make a lot of sense, and as far as I can tell is not true (set a variable with putenv and it's immediately avaiable via getenv). It's possible the author was mistaken and had the same issue discussed here.
https://github.com/curl/curl/blob/2e9b725f67d49a9d7a1f053fe52dd4920c9ab1ad/src/tool_homedir.c#L32-L42

### Remedy

To completely remedy this in curl would require a bit of work since we call getenv multiple places without having to worry about memory management, like we would with curl_getenv. We could at least address the php bug by improving on curl_getenv to obtain variables via GetEnvironmentVariable instead of getenv. The easiest way to do that is c&p of GetEnv from the tool and use it in the lib:

~~~diff
diff --git a/lib/getenv.c b/lib/getenv.c
index e444a6a..9ca8f19 100644
--- a/lib/getenv.c
+++ b/lib/getenv.c
@@ -34,17 +34,31 @@ char *GetEnv(const char *variable)
   (void)variable;
   return NULL;
 #else
+  char *env = NULL;
 #ifdef WIN32
-  char env[4096];
-  char *temp = getenv(variable);
-  env[0] = '\0';
-  if(temp != NULL)
-    ExpandEnvironmentStringsA(temp, env, sizeof(env));
-  return (env[0] != '\0')?strdup(env):NULL;
+  char  buf1[1024], buf2[1024];
+  DWORD rc;
+
+  /* Don't use getenv(); it doesn't find variable added after program was
+   * started. Don't accept truncated results (i.e. rc >= sizeof(buf1)).  */
+
+  rc = GetEnvironmentVariableA(variable, buf1, sizeof(buf1));
+  if(rc > 0 && rc < sizeof(buf1)) {
+    env = buf1;
+    variable = buf1;
+  }
+  if(strchr(variable, '%')) {
+    /* buf2 == variable if not expanded */
+    rc = ExpandEnvironmentStringsA(variable, buf2, sizeof(buf2));
+    if(rc > 0 && rc < sizeof(buf2) &&
+       !strchr(buf2, '%'))    /* no vars still unexpanded */
+      env = buf2;
+  }
 #else
-  char *env = getenv(variable);
-  return (env && env[0])?strdup(env):NULL;
+  /* no length control */
+  env = getenv(variable);
 #endif
+  return (env && env[0]) ? strdup(env) : NULL;
 #endif
 }
~~~

Is there an acceptable way to deduplicate functions used by both the tool and lib? I know of curlx but I understand those are deprecated, therefore if I wanted change GetEnv in the tool to call curlx_getenv (which would then call GetEnv in the lib and now has the same code) would that be acceptable?

To address this fully would require banning getenv and then replacing it with curl_getenv everywhere, and I think that's unnecessary. I'd rather note KNOWN_BUGS there may be circumstances where curl may not recognize variables set via SetEnvironmentVariable.

### curl/libcurl version

curl 7.68.0-DEV (i386-pc-win32) libcurl/7.68.0-DEV

**Comment by cmb69** [comment]
Thanks! I've not much to add, except for

> cmb69's e-mail also points out getenv is not thread safe but I assume he means if the environment block is modified. This is a well known issue for various runtimes and perhaps we should warn about using putenv in the thread safety guidelines.

Yes, please at least document this in the thread safety guidelines. [MSDN explicitly points out](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=vs-2019):
> The _putenv and _getenv families of functions are not thread-safe. _getenv could return a string pointer while _putenv is modifying the string, causing random failures. Make sure that calls to these functions are synchronized.

POSIX doesn't mandate that `getenv()` has to be thread-safe either.

**Comment by bagder** [comment]
~~~diff
-  char *env = getenv(variable);
-  return (env && env[0])?strdup(env):NULL;
+  /* no length control */
+  env = getenv(variable);
~~~

This section removes the `strdup()` which surely will introduce bad `free()` calls?

**Comment by bagder** [comment]
(removed erroneous comment)

Shouldn't you create a PR with this to see what the tests say about it?

**Comment by jay** [comment]
> Shouldn't you create a PR with this to see what the tests say about it?

It's a preliminary for discussion. I'm unsure on how best to proceed. I think the duplication is a crude way to fix it. I'd rather share the code between the lib and the tool. It'll do the job though.

**Comment by jay** [comment]
Any opinion here? Should I turn it into a curlx or just submit it with the duplication?

**Comment by bagder** [comment]
I don't have any particular strong opinion either way. I think you can do what's easiest for you. The curlx method often turns out cumbersome so it isn't necessary a clear win to share code that way.

**Comment by jay** [comment]
@cmb69 please check if #4683 fixes your issue

**Comment by cmb69** [comment]
@jay, yes that would fix my issue. Thanks! I left 2 inline comments regarding implementation details.
