### ISSUE TITLE
Invalid handling of SSL_ERROR_SYSCALL with libressl and probably openssl

### ISSUE THREAD

**Issue by nihilus** [curl/curl#4777]
This should not yield in an error:
> Error: curl: (56) LibreSSL SSL_read: Success Request:

**Comment by bagder** [comment]
We lack a lot of details in this report, but before you go down that route, isn't this problem already fixed in git?

**Comment by nihilus** [comment]
Seems like it has been fixed yes. I wish I knew which commit.

**Comment by jay** [comment]
Duplicate of #4624
