### ISSUE TITLE
Consider having --remote-name extract the local filename from the final redirect URL

### ISSUE THREAD

**Issue by jwatt** [curl/curl#4778]
Using curl 7.65.3 on Ubuntu 19.10 I ran the following:

```
curl -LOJ https://update.code.visualstudio.com/latest/darwin/stable
```

This redirects to the URL:

```
https://az764295.vo.msecnd.net/stable/26076a4de974ead31f97692a0d32f90d735645c0/VSCode-darwin-stable.zip
```

I expected this to extract the local filename from the final URL and end up with a file called `VSCode-darwin-stable.zip`, but I end up with a file named `stable`, which is less helpful.

Note: this would be consistent with how browsers behave when opening the context menu on a link and selecting Save As, in which case the save dialog is prepopulated with the name as extracted from the final URL. Here's the link from above for testing - https://update.code.visualstudio.com/latest/darwin/stable

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

This is already a TODO item: https://curl.haxx.se/docs/todo.html#consider_file_name_from_the_redi

**Comment by jwatt** [comment]
Thanks for the reply and extra info. I'm afraid I don't have the cycles to push this further than simply reporting the issue to you (and besides that, for my own immediate use case I discovered that `wget` has the `--trust-server-names` option which does what I need).

**Comment by bagder** [comment]
Since this is already mentioned in the TODO, I'm closing this.
