### ISSUE TITLE
CURLOPT_READFUNCTION man page: wrong arg passed for CURLOPT_READDATA

### ISSUE THREAD

**Issue by joycepg** [curl/curl#4787]
### I read this
 /* pass in suitable argument to callback */
  curl_easy_setopt(curl, CURLOPT_READDATA, uploadthis);
### I expected the following
 /* pass in suitable argument to callback */
  curl_easy_setopt(curl, CURLOPT_READDATA, file);
### curl/libcurl version

[curl -V output]

**Comment by jay** [comment]
Thanks
