### ISSUE TITLE
FTP Download on Windows 7 hangs or stuck

### ISSUE THREAD

**Issue by PlusMixDev** [curl/curl#4795]
**[C++]**
I made FTP Client
that's work correctly on Windows 10
but in Windows 7 it stuck on this

`  schannel: shutting down SSL/TLS connection with serverip... port ...`

and next function not working

**NOTE**
1. Connect to server work correctly.
2. It hang when ` curl_easy_perform ` was call on my download function
3. It's Dll Project
4. I'm using curl static library

**Comment by bagder** [comment]
Since this says Schannel shuts down the connection, are you using FTPS?

**Comment by PlusMixDev** [comment]
Yes

**Comment by PlusMixDev** [comment]
> 
> 
> Since this says Schannel shuts down the connection, are you using FTPS?

yes.
Edit: My code
Note 2
It 32 Bit
`
FILE* file;
CURLcode res;
bool Response;
char Url[256];
sprintf_s(Url, "ftps://Server-IP/Arita-FTP/%s",FileName.c_str());
/------------------/
`
curl_easy_setopt(ARPNETDATA.FTP_Handle, CURLOPT_NOBODY, FALSE);
curl_easy_setopt(ARPNETDATA.FTP_Handle, CURLOPT_URL, Url);
curl_easy_setopt(ARPNETDATA.FTP_Handle, CURLOPT_VERBOSE, 1L);
curl_easy_setopt(ARPNETDATA.FTP_Handle, CURLOPT_WRITEFUNCTION, write_data);
file = fopen(LocalPath.c_str(), "wb");
if (file) {
	curl_easy_setopt(ARPNETDATA.FTP_Handle, CURLOPT_WRITEDATA, file);
	res = curl_easy_perform(ARPNETDATA.FTP_Handle);
	fclose(file);
}
`

**Comment by jay** [comment]
In Windows 7 I am able to use the curl tool w/ schannel backend to download a file ftps from a server using that same version of filezilla (0.9.41).

Does it happen if you use the curl tool? What's the output of your `curl_version()`? 

~~~
curl 7.67.0 (i386-pc-win32) libcurl/7.67.0 Schannel WinIDN
~~~

**Comment by PlusMixDev** [comment]
> 
> 
> In Windows 7 I am able to use the curl tool w/ schannel backend to download a file ftps from a server using that same version of filezilla (0.9.41).
> 
> Does it happen if you use the curl tool? What's the output of your `curl_version()`?
> 
> ```
> curl 7.67.0 (i386-pc-win32) libcurl/7.67.0 Schannel WinIDN
> ```

Output: libcurl/7.68.0 Schannel WinIDN

**AND**
how curl and libcurl different ?

**Comment by jay** [comment]
> Output: libcurl/7.68.0 Schannel WinIDN

I tried with that version and I cannot reproduce. Test with the curl tool. That way you can determine if the problem is with your code.

**Comment by PlusMixDev** [comment]
> 
> 
> > Output: libcurl/7.68.0 Schannel WinIDN
> 
> I tried with that version and I cannot reproduce. Test with the curl tool. That way you can determine if the problem is with your code.

Thanks for suggestion , i switch to Windows 7 using http and Windows 10 using FTP
that work correctly
