### ISSUE TITLE
document cookie format in CURLINFO_COOKIELIST

### ISSUE THREAD

**Issue by bsammon** [curl/curl#4805]
It would be nice if the CURLINFO_COOKIELIST had some documentation as to the format of the cookie strings that it returns, or a pointer to such documentation. (is it a standard format?)

By experimentation, I've determined that it seems to be tab-delimited, with a predictable ordering of the fields.

**Comment by bagder** [comment]
I agree, it should be mentioned there or point to where the documentation for it exists.

Currently, it is at least documented in Everything curl: https://ec.haxx.se/libcurl-http/libcurl-http-cookies#cookie-file-format

**Comment by jay** [comment]
Also see the example in https://curl.haxx.se/libcurl/c/CURLOPT_COOKIELIST.html
