### ISSUE TITLE
Travis CI test failures due to missing server or lack of ports

### ISSUE THREAD

**Issue by jay** [curl/curl#4811]
### I saw this
~~~
 0000: PASV
 03:49:26.055887 <= Recv header, 20 bytes (0x14)
 0000: 500 no free ports
 03:49:26.055917 == Info: Bad PASV/EPSV response: 500
 03:49:26.055926 == Info: DO phase failed
 03:49:26.055934 == Info: multi_done
 03:49:26.055946 == Info: Remembering we are in dir "first/dir/here/"
 03:49:26.056259 == Info: Connection #0 to host 127.0.0.1 left intact
~~~

### I expected the following

Free ports. I suspect this is also why the servers occasionally fail to restart as described [here](https://github.com/curl/curl/pull/4717#issuecomment-570714987). What could cause this, it couldn't possibly be our tests could it?

---

/cc @marc-groundctl

**Comment by bagder** [comment]
Do you have any links around to one of those failed builds? 'sockfilt' returns 'fail' for several different failures but it should write something to its log so it might be possible to get a little more details.

**Comment by jay** [comment]
I don't, I restarted the failed builds. I'll keep my eye out.

**Comment by bagder** [comment]
As we can't reproduce this, I don't think it adds much value to keep this issue open.
