### ISSUE TITLE
wolfssh: publickey auth doesn't work

### ISSUE THREAD

**Issue by bagder** [curl/curl#4820]
### I did this

Run test 582 in a wolfssh build. It fails.

### I expected the following

The test should run fine.

### curl/libcurl version

git master

**Comment by emilengler** [comment]
On master I get with this config 
```
LD_LIBRARY_PATH=/usr/local/lib ./configure CC=/usr/lib/ccache/clang CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib --enable-debug --disable-shared -without-ssl --with-wolfssl --with-wolfssh
```
These fails: `TESTFAIL: These test cases failed: 165 962 963 964 965 966 967 1013 1448 2046 2047 `
Executing this specific test gives me
```
cannot find sshd
RUN: failed to start the SSH server
test 0582 SKIPPED: failed starting SSH server
```
which is not a failure

**Comment by emilengler** [comment]
Turns I need an ssh server installed....
Now I can reproduce

**Comment by bagder** [comment]
wolfSSH has subsequently fixed their end and now provide the necessary APIs to allow us to fix this. It will take a little reading up.

**Comment by emilengler** [comment]
> wolfSSH has subsequently fixed their end and now provide the necessary APIs to allow us to fix this. It will take a little reading up.

It already works fine with the wolfSSH demo server found in wolfSSH/examples/echoserver/echoserver

Running `src/curl -k sftp://localhost:22222 -u jill:upthehill` works fine

**Comment by emilengler** [comment]
Nevermind, this is not pubkey auth...
