### ISSUE TITLE
building under Mac OS 10.15.2 (Catalina) with gcc-9 fails

### ISSUE THREAD

**Issue by karen-arutyunov** [curl/curl#4821]
Building curl 7.68.0 under Mac OS 10.15.2 with gcc-9 with the Secure Transport enabled fails with the following errors:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:42,
                 from vtls/sectransp.c:45:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified 'bytes' at file scope
  193 |  char bytes[kAuthorizationExternalFormLength];
      |       ^~~~~
vtls/sectransp.c: In function 'show_verbose_server_cert':
vtls/sectransp.c:2713:6: error: 'SecTrustEvaluateAsync' undeclared (first use in this function); did you mean 'SecTrustEvaluate'?
 2713 |   if(SecTrustEvaluateAsync != NULL) {
      |      ^~~~~~~~~~~~~~~~~~~~~
      |      SecTrustEvaluate
vtls/sectransp.c:2713:6: note: each undeclared identifier is reported only once for each function it appears in
```

### I did this
```
% curl -O https://curl.haxx.se/download/curl-7.68.0.tar.gz
% tar xf curl-7.68.0.tar.gz
% cd curl-7.68.0
% CC=gcc-9 ./configure --with-darwinssl
% make
```

### I expected the following

I expected to successfully build curl.

### curl/libcurl version

7.68.0

### operating system

Mac OS 10.15.2

**Comment by bagder** [comment]
That first error is not in curl code...

**Comment by karen-arutyunov** [comment]
Yeah, seems there is no C standard that allows the definition in the header:

```
static const size_t kAuthorizationExternalFormLength = 32;

typedef struct {
        char bytes[kAuthorizationExternalFormLength];
} AuthorizationExternalForm;
```

**Comment by nickzman** [comment]
If you're using GCC, try it again with Clang; it ought to work with Clang. Neither error is in curl code; the first one looks like something Clang supports but GCC does not, and the second is because `SecTrustEvaluateAsync()` is defined behind a preprocessor definition GCC might not have defined (`__BLOCKS__`).

**Comment by karen-arutyunov** [comment]
Yes, it builds with Clang. Just inability to build curl with GCC on MacOS is quite an unfortunate.

**Comment by bagder** [comment]
Sure, but since this is at least one error that isn't ours *we* can't even fix this...

**Comment by jzakrzewski** [comment]
Judging from a quick googling this is not a new problem. GCC just doesn't like it. The common answer is: use clang...

**Comment by bagder** [comment]
This is not a problem in our lap.
