### ISSUE TITLE
SMTP IDN in CURLOPT_MAIL_FROM causes syntax error

### ISSUE THREAD

**Issue by ygthien** [curl/curl#4828]
### I did this
I tried SMTP with IDN in sender email, but I got a syntax error
```
220  ESMTP q20si0ins.0 - gsmtp

EHLO insq20

250- at your service, [2002:a05:6600:2c54::]

250-SIZE 35882577

250-8BITMIME

250-STARTTLS

250-ENHANCEDSTATUSCODES

250-PIPELINING

250-CHUNKING

250 SMTPUTF8

MAIL FROM:<envelopefrom@好的idn.ws>

555 5.5.2 Syntax error. q20si0ins.0 - gsmtp

MAIL failed: 555
QUIT

221 2.0.0 closing connection q20si0ins.0 - gsmtp
```

### I expected the following

I expected SMTP to support IDN in both sender and recipient addresses to have IDN (similar python library does).

### curl/libcurl version

[curl -V output]

### operating system

Linux

**Comment by bagder** [comment]
Can you show us more exactly how you used curl to get this issue?

**Comment by bagder** [comment]
Without more information we will close this within shortly without action.

**Comment by bagder** [comment]
Lack of information.

**Comment by ygthien** [comment]
Hi, 

Sorry, I just got back from a 2 week vacation.

I call curl through the `curl_easy_perform()` API, with argument setup with `curl_easy_setopt macro`

- `curl_easy_perform() API` - https://github.com/curl/curl/blob/master/lib/easy.c#L715
- `curl_easy_setopt macro` - https://github.com/curl/curl/blob/master/include/curl/curl.h#L2882

Let me know if you need more information

**Comment by bagder** [comment]
The problem you show above is the server reacting to `MAIL FROM` and that's an address you set with `CURLOPT_MAIL_FROM`. curl doesn't do anything special with that address but presumes that you pass in a working one, and obviously an IDN doesn't look like its working - at least not on this server.

**Comment by bagder** [comment]
We should *at least* improve the documentation for this.

**Comment by ygthien** [comment]
Is this something that can be fixed instead? 
AFAIK, the Python curl library seems to work with IDN in CURLOPT_MAIL_FROM.

**Comment by bagder** [comment]
Yes, it should certainly be possible to fix.

**Comment by bagder** [comment]
@captain-caveman2k, anything you feel like taking a bite at?

**Comment by captain-caveman2k** [comment]
Sure - I will take a look.

**Comment by captain-caveman2k** [comment]
I've had a first quick stab at this which I've posted in PR #4892 

I've asked some questions in the pull request and would appreciate some feedback.

Cheers.

**Comment by captain-caveman2k** [comment]
I think I'm pretty much code complete. @ygthien would you be able to take a look at the implementation in #4892 and give your feedback?

**Comment by ygthien** [comment]
#4892 looks great to me! This is more than what I need, and should benefit more people.

Thanks!

**Comment by ygthien** [comment]
Do we know which release can this change get in? Can we make it for the upcoming `v7.69.0` release?

**Comment by bagder** [comment]
@ygthien yes, this is already merged into master and is scheduled to ship in 7.69.0

**Comment by ygthien** [comment]
Thanks for your great work!
