### ISSUE TITLE
It should be possible to dynamically decide if the Curl_multi should use socketpair 

### ISSUE THREAD

**Issue by Andersbakken** [curl/curl#4829]
### I did this

I did not use curl_multi_wait in my app

### I expected the following

For curl not to allocate a socketpair for each multi handle

### curl/libcurl version

master

[curl -V output]

### operating system

linux

Ideally Curl should allow one or more of these options:

1) configure switch to decide if you want to enable socketpairs for waking up the multi
2) make socket pairs on demand with multi_opt to toggle enabledness

regards

**Comment by bagder** [comment]
I presume you want this because the socketpair creates some kind of problem or nuisance for you. Can you elaborate on why you want/need this?

**Comment by Andersbakken** [comment]
Some of our platforms are rather constrained on resources and since we're not calling curl_multi_wakeup the sockets will just sit there. 

This wouldn't be so bad for if it weren't for the fact that we have a multi handle per websocket connection. We've implemented websockets on top of CURLOPT_CONNECT_ONLY and ran into some issues with socket pooling.

**Comment by rcombs** [comment]
I'm running into this as well (with easy handles); the extra sockets just sit there and pile up until I run out of dynamic ports on loopback, even if I have connection reuse enabled for my main sockets.
Is there a reason this has to be a socket pair at all, rather than just an anonymous pipe? It's only ever used in one direction.

**Comment by jay** [comment]
My PR to fix this did not gain enough support. I still think some remedy for this issue is a good idea. Someone will have to implement something more agreeable, or eventually I will close it in known issues (or TODO).

**Comment by rcombs** [comment]
Is this a problem for you on non-Windows platforms? If so, what resource are you running out of exactly?

**Comment by jay** [comment]
#5850 has added a build-time option to `--disable-socketpair`.
