### ISSUE TITLE
README instructions out of date

### ISSUE THREAD

**Issue by brackleian** [curl/curl#4830]
The README file has incorrect info on how to build CURL.

### I did this
Downloaded source from github. Read the file README, which told me to see the file INSTALL for how-to-build instructions.

### I expected the following
To find an INSTALL file. Failing that, a "configure" file.
After some research, I found https://curl.haxx.se/docs/install.html which had the correct build instructions.

### curl/libcurl version
7.68.0

### operating system
Xubuntu

**Comment by jay** [comment]
how about
~~~diff
diff --git a/README b/README
index c439dab..2b3f8d1 100644
--- a/README
+++ b/README
@@ -21,6 +21,8 @@ README
   curl binaries or other binaries that involve libcurl, you might enjoy the
   LICENSE-MIXING document.
 
+  All of those documents and more can be found in the docs directory.
+
 CONTACT
 
   If you have problems, questions, ideas or suggestions, please contact us
~~~
