### ISSUE TITLE
curl_multi_perform bad_alloc exception after sending request to server:

### ISSUE THREAD

**Issue by rahul233343** [curl/curl#4844]
### I did this
i created the curl message using c++ and added in curl_multi, than called "curl_multi_add_handle" after this i performed "curl_multi_perform" it is giving me bad_alloc exception after sending the message to server.

### I expected the following
the Response should be written to the curl message for further processing, but it is not.
### curl/libcurl version
curl 7.47.0

[curl -V output]

### operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Comment by bagder** [comment]
First: we need more details to be able to act in any way at all. Preferably you show us a complete example source code that you used to reproduce the problem!

7.47.0 turns 4 years old in a week (we've done 35 releases since). We've fixed a huge amount of bugs since that release. It will make sense to try a modern libcurl version to see if this problem hasn't been fixed already!

**Comment by rahul233343** [comment]
Thanks
ok let me try with new version, and i will revert back to you.

**Comment by rahul233343** [comment]
Sorry can't use the new version of the libCurl due to some reason.

But one thing i tested, if same query is done with easy curl it is giving the true result. is there something am i missing?

**Comment by bagder** [comment]
If you show us a full example source code that reproduces your problem then we might be able to tell that!

**Comment by rahul233343** [comment]
sorry i can't send this code. Can i send you back trace logs?

**Comment by bagder** [comment]
Since curl works it could be a mistake in your code that leads to the problem, I doubt we can spot that in back trace logs.

**Comment by rahul233343** [comment]
i hope we can figure out through logs.


#0  0x00007ffff5cdc428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff5cde02a in __GI_abort () at abort.c:89
#2  0x00007ffff5d1e7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff5e37ed8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5d2737a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff5e37fe8 "double free or corruption (out)", 
    action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ffff5d2b53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x00007ffff66af52d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff66b0833 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x0000000000572f35 in writer (data=0x15dd760 "Date: Fri, 24 Jan 2020 06:09:56 GMT\r\n", size=1, nmemb=37, buffer_in=0x7fffed437020)
    at xyz.cpp:25
#9  0x00007ffff7615a95 in Curl_client_chop_write () from /home/user9/pre/curl/build/lib/libcurl.so
#10 0x00007ffff7615bb7 in Curl_client_write () from /home/user9/pre/curl/build/lib/libcurl.so
#11 0x00007ffff7614a71 in Curl_http_readwrite_headers () from /home/user9/pre/curl/build/lib/libcurl.so
#12 0x00007ffff76308ce in readwrite_data () from /home/user9/pre/curl/build/lib/libcurl.so
#13 0x00007ffff7631b52 in Curl_readwrite () from /home/user9/pre/curl/build/lib/libcurl.so
#14 0x00007ffff763f1e6 in multi_runsingle () from /home/user9/pre/curl/build/lib/libcurl.so
#15 0x00007ffff763f9be in curl_multi_perform () from /home/user9/pre/curl/build/lib/libcurl.so

**Comment by bagder** [comment]
That's a problem in your write callback, not in libcurl...

**Comment by rahul233343** [comment]
But this function gives me the correct result for GET Request.

**Comment by bagder** [comment]
I doubt you need my blind guesses on what's wrong in that code of yours that you haven't shown.

**Comment by bagder** [comment]
This problem exists in user's own callback function.
