### ISSUE TITLE
Extremely rare segfault

### ISSUE THREAD

**Issue by kreuzerkrieg** [curl/curl#4874]
Not sure it is curl fault, but saw several issues in openssl pointing your direction guys.
Once in a while (really rarely) I get something like this

> 0x563aa8be2ccd large_dalloc /root/project/obj-x86_64-linux-gnu/../contrib/jemalloc/include/jemalloc/internal/atomic.h:55
> 0x563aa8bd52b2 free /root/project/obj-x86_64-linux-gnu/../contrib/jemalloc/src/jemalloc.c:2689
> 0x563aae801df5 recallocarray /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/compat/recallocarray.c:80
> 0x563aae79986f BUF_MEM_grow_clean /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/buffer/buffer.c:121
> 0x563aae7d9136 PEM_read_bio /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/pem/pem_lib.c:724
> 0x563aae84d4bd PEM_X509_INFO_read_bio /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/pem/pem_info.c:124
> 0x563aae7eb069 X509_load_cert_crl_file /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/by_file.c:252
>  0x563aae7eb19a by_file_ctrl /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/by_file.c:118
>  0x563aae7ec378 X509_STORE_load_locations /root/project/obj-x86_64-linux-gnu/../contrib/ssl/crypto/x509/x509_d2.c:96
>  0x563aadf85e85 ossl_connect_step1 /root/project/contrib/curl/lib/vtls/openssl.c:2343
>  0x563aadf88c7e ossl_connect_common /root/project/contrib/curl/lib/vtls/openssl.c:3287
>  0x563aadf5ac37 Curl_ssl_connect_nonblocking /root/project/contrib/curl/lib/vtls/vtls.c:273
>  0x563aadf5fbf2 https_connecting /root/project/contrib/curl/lib/http.c:1393
>  0x563aadf66a46 Curl_protocol_connect /root/project/contrib/curl/lib/url.c:1652
>  0x563aadf4c036 multi_runsingle /root/project/contrib/curl/lib/multi.c:1573
>  0x563aadf4cf84 curl_multi_perform /root/project/contrib/curl/lib/sigpipe.h:66
>  0x563aadf46dd4 curl_easy_perform /root/project/contrib/curl/lib/easy.c:699
>  0x563aadee71ab Aws::Http::CurlHttpClient::MakeRequestInternal(Aws::Http::HttpRequest&, std::shared_ptr<Aws::Http::Standard::StandardHttpRespo
>  0x563aadee91c1 Aws::Http::CurlHttpClient::MakeRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInte
>  0x563aadec2a35 Aws::Client::AWSClient::AttemptOneRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&,
>  0x563aadec3150 Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod,
>  0x563aadec408b Aws::Client::AWSXMLClient::MakeRequest(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char

 Is this some known issue?

According to RELEASE-NOTES files in my source tree it is Curl and libcurl 7.58.0
OS - Ubuntu 18.04

**Comment by bagder** [comment]
Thanks!

What makes you suspect that this is a curl issue in the first place? The crash is clearly deep within OpenSSL and its PEM file reader.

What OpenSSL version is this? Is this a multi-threaded use and if so, is that protected correctly?

**Comment by kreuzerkrieg** [comment]
> Thanks!
> 
> What makes you suspect that this is a curl issue in the first place? The crash is clearly deep within OpenSSL and its PEM file reader.
Since I didnt find any openssl issue referencing to this (or similar) callstack. Then I've found this issue mentioning `curl_multi_perform`, so I wanted to check here, maybe it is some known issue. Yep it looks like double `free` in ssl, but I'm just checking.

> What OpenSSL version is this? 
OpenSSL 1.1.1  11 Sep 2018
> Is this a multi-threaded use and if so, is that protected correctly?
AWS guys are claiming their client is thread safe, do they protect it correctly? I guess yes, I'm not the only one using their SDK, so I guess this problem would surface a while ago.

**Comment by bagder** [comment]
I don't recognize this issue as something we've seen reported or happened before and OpenSSL is the by far most popular TLS library used by curl users - and your curl version is about two years old. I don't want to point fingers, but I can't spot any curl mistake in the stack trace and if there's no for us to reproduce this I'm not sure I can reach much further.

> OpenSSL 1.1.1 11 Sep 2018

That sounds like OpenSSL 1.1.1d (which was tagged in that time frame) but when I git blamed on that tag, the line numbers in the stack trace didn't match what my output showed. I don't think it matters too much though.

> AWS guys are claiming their client is thread safe

Yes, with OpenSSL 1.1.1 that should not be a problem.

**Comment by kreuzerkrieg** [comment]
Ok then, may be next failure will yield more info on the callstack. Thanks in any case!
