### ISSUE TITLE
smtp-mime.c example

### ISSUE THREAD

**Issue by toutant** [curl/curl#4891]
### I did this
used code from https://curl.haxx.se/libcurl/c/smtp-mime.html

### I expected the following
to be able to view as html first / text second
gmail / yahoo / outlook.com web based emails - display alttext  only

### curl/libcurl version

LIBCURL_VERSION "7.65.2-DEV"

[curl -V output]

### operating system
windows 10

**Comment by bagder** [comment]
Aren't you getting:
1. `multipart/alternative` in the top mail headers
2. `text/plain` in the first alternative and
3. `text/html` as the second alternative

? If you do, and none of those services show the html version, then I don't know why those services do that. I'm not totally convinced this is a curl bug (to care about).

**Comment by bagder** [comment]
No response in over a week on a fresh report. Closing.
