### ISSUE TITLE
Problems in Finding Curl

### ISSUE THREAD

**Issue by QihanLiu** [curl/curl#4895]
I am using Ubuntu 18.04.4 LTS, and I used to have anaconda.
But after I uninstall anaconda 3, it seems like Ubuntu can't find curl.
I installed the version 7.68.0. I can find it at /usr/local/bin/curl. 
But when I run "curl", it shows -bash: /home/ql/anaconda3/bin/curl: No such file or directory.

How can I redir curl?

**Comment by QihanLiu** [comment]
I've tried apt-get as well. It installs version 7.58 at /usr/bin.
I can run that file when I indicate the path like "/usr/bin/curl". But I can't do "curl".
They have the same question, I guess.

**Comment by emilengler** [comment]
The close probably meant that you no longer have the problem but what is the output of
```
echo $PATH
```
and what is the output of
```
whereis curl
```
