### ISSUE TITLE
alt-svc should fallback if alt-svc doesn't work

### ISSUE THREAD

**Issue by candrews** [curl/curl#4908]
### I did this
Using curl with alt-svc support compiled in:
```
$ curl --alt-svc test.txt https://integralblue.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.integralblue.com/">here</a>.</p>
<hr>
<address>Apache Server at integralblue.com Port 443</address>
</body></html>

$ curl --alt-svc test.txt https://integralblue.com
curl: (7) Failed to connect to 3dbbdetxoyw4nsp6c3cc456oj2aysmzhbfzz6s43ezxzsfxxri3h5xqd.onion port 443: Connection refused
```
https://integralblue.com uses an alt-svc header pointing to a tor .onion address. Cloudflare does this too: https://blog.cloudflare.com/cloudflare-onion-service/

### I expected the following
The second curl invocation should have worked.

According to https://tools.ietf.org/html/rfc7838#section-2.4
> Furthermore, if the connection to the alternative service fails or is
> unresponsive, the client MAY fall back to using the origin or another
> alternative service.

So falling back is okay.

I can see a few of approaches:
* Only add the alt-svc to the cache when curl determines that the service is reachable. This is what Chrome and Firefox do.
* Always add the alt-svc to cache (which is what curl does today), but then fall back to the original origin if the alt-svc isn't reachable. This is like how the IPv6 to IPv4 fallback works.

### curl/libcurl version

```
$ curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libssh2/1.9.0_DEV nghttp2/1.40.0 quiche/0.2.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz Metalink NTLM SSL TLS-SRP UnixSockets
```

### operating system
```
$ uname -a
Linux irrational 5.4.0-rc6 #2 SMP Fri Nov 8 19:09:49 EST 2019 x86_64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz GenuineIntel GNU/Linux
```

**Comment by bagder** [comment]
You're right. The current alt-svc code is just a switch without fall-back logic. Not good enough.

>  Only add the alt-svc to the cache when curl determines that the service is reachable. This is what Chrome and Firefox do.

Well, that would basically just force us to have two caches since we still need to store the information about all the *possible* alternatives until they've been verified. I don't think that's good approach. Also, an alternative that works now can suddenly not work the next time, or vice versa.

>   Always add the alt-svc to cache (which is what curl does today), but then fall back to the original origin if the alt-svc isn't reachable. This is like how the IPv6 to IPv4 fallback works.

In my mind this is the most sensible way to go about it. I presume that actually will rather be translated into a *list* of options to try in a given order until one works, as there can be several listed alternatives and the "un-alternative" version would then be the last to try...

**Comment by candrews** [comment]
Here's a relevant issue report in Firefox regarding their plans for alt-svc use:
https://bugzilla.mozilla.org/show_bug.cgi?id=1498663

**Comment by bagder** [comment]
That still sounds like "ideas" rather than "plans", but sure. I don't think we should race all alternatives as our first option.

**Comment by xquery** [comment]
for completeness - same behaviour observed with nghttp2

`curl 7.69.1-DEV (x86_64-pc-linux-gnu) libcurl/7.69.1-DEV OpenSSL/1.1.1d c-ares/1.14.0 libssh2/1.8.0 nghttp2/1.30.0 ngtcp2/0.1.90 nghttp3/0.1.90`

investigating

**Comment by xquery** [comment]
leaning towards implementing the following fall back

1. check all alt-svc 
2. on failure of all #1 use original origin

Network connections are transient we make no assumptions about state and continue to push alt-svc to cache  alt-svc to the cache. 

Will also investigate implementing 'persist' behaviour which may have some part to play here ... note - 'persist' has no default value defined in the spec.

**Comment by bagder** [comment]
Sounds fair. If there are more than one alternative to try, it also becomes interesting in which order why try them...

On default "persist", section 3.1 says:

>   By default, cached alternative services will be cleared when the
>   client detects a network change.  Alternative services that are
>  intended to be longer lived (such as those that are not specific to
>   the client access network) can carry the "persist" parameter with a
>   value "1" as a hint that the service is potentially useful beyond a
>   network configuration change.

... which sure sounds like persist is 0 by default.

**Comment by xquery** [comment]
yes of course you are right - I lost the thread on this bug some time ago, trying to pick it back up

**Comment by bagder** [comment]
@xquery, what's your status on this?

**Comment by xquery** [comment]
Aspirational ... that is I need a nudge in a few right directions to make progress ... you did graciously offer time to set me straight. Otherwise I wanted to blame covid, unemployment (actually I am doing contract work till Nov 3rd to see if the world begins anew before taking on long term employment), toddler wanting to 'play with dad' for more hours there are in the day (this is not a bad thing), other distractions like putting a gui on top of libcurl to learn golang (a topic for next curlup), but none of those are accurate eg. I have failed miserably ... will try to schedule time soon with you (if the offer is still open).

**Comment by bagder** [comment]
That offer is always open!

**Comment by nevakrien** [comment]
this bug apears to work diffrently now... I have ran the same code trying to reproduce and got a fairly weird error message

```bash
(base) user@user-System-Product-Name:~/Desktop/open_source_work/curl$ ./src/curl -V
curl 8.13.1-DEV (x86_64-pc-linux-gnu) libcurl/8.13.1-DEV OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 nghttp2/1.59.0 OpenLDAP/2.6.7
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets zstd
(base) user@user-System-Product-Name:~/Desktop/open_source_work/curl$ ./src/curl --alt-svc test.txt https://integralblue.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.integralblue.com/">here</a>.</p>
<hr>
<address>Apache Server at integralblue.com Port 443</address>
</body></html>
(base) user@user-System-Product-Name:~/Desktop/open_source_work/curl$ ./src/curl --alt-svc test.txt https://integralblue.com
curl: (6) Not resolving .onion address (RFC 7686)
(base) user@user-System-Product-Name:~/Desktop/open_source_work/curl$ 
```

the issue seems similar in nature however so its not really important.
will try fixing it myself
