### ISSUE TITLE
runtests: log/curl.log doesn't exist!

### ISSUE THREAD

**Issue by bagder** [curl/curl#4911]
### I did this

`cd tests && ./runtests.pl 1`

### I expected the following

There should be a log file left after the run, called `tests/log/curl.log` showing each command line invoke done in the test. The file doesn't exist.

### curl/libcurl version

current git master, but I believe this flaw has existed for a while. I cannot remember at which point it broke. It used to work.

### operating system

Linux, but I think it might exist everywhere.

**Comment by bagder** [comment]
This puzzles me and I don't really have any good ideas how to debug it. What could possibly make it behave like this?

**Comment by emilengler** [comment]
> This puzzles me and I don't really have any good ideas how to debug it. What could possibly make it behave like this?

I may be totally wrong on this as I have absolutely no experience with Perl and how it behaves but as far as I looked at the code, the `CMDLOG` file stream was already used in function on line ~3000. However the file stream is being created in line ~5000. Maybe the runtime doesn't even have access to the variable yet. Maybe move the function a bit down.

**Comment by bagder** [comment]
1. It used to work
2. They're used in the correct order, so the filehandle is created before it gets used and it seems to be closed after all uses of it.

**Comment by bagder** [comment]
For the record: commit 6617db6a7ed322d28322896aa20bcabf3a479e7c (June 27, 2019) broke  it
