### ISSUE TITLE
TLS Session ID(ClientHello) not populated on Darwin

### ISSUE THREAD

**Issue by brompwnie** [curl/curl#4917]
### I did this

curl https://x.x.x.x

### I expected the following
In the ClientHello Record, I expected a SessionID value and SessionID Length >0 but instead got Session ID Length=0 and no Session ID value populated even when multiple successful TLS connections have been made.

### curl/libcurl version

curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54
.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https im
ap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp 
smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerbero
s SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets H
TTPS-proxy 

### operating system
OSX

**Comment by bagder** [comment]
You did multiple connections how? Repeated invokes of the curl command cannot reuse session ids.

**Comment by brompwnie** [comment]
Multiple connections meaning that curl was issued against a single host multiple teams, it's expected that after the initial connection, any connections afterwards should have a populated SessionID.

**Comment by brompwnie** [comment]
According to RFC5246 https://tools.ietf.org/html/rfc5246#section-7.4.1.2

**Comment by bagder** [comment]
> any connections afterwards should have a populated SessionID

Not if the application has exited in between. Did it?

**Comment by brompwnie** [comment]
No, there were no exits during the execution of the curl command. Literally running "curl https://x.x.x.x \r\n [ENTER]" and another "https://x.x.x.x\r\n [ENTER]". The TLS handshake is occurring successfully and the HTTP request is getting a successful response. I've attempted this multiple times, against multiple different hosts and the SessionID is never populated. Would you like a PCAP?

**Comment by bagder** [comment]
A subsequent invoke of the curl command cannot reuse SessionID from any previous command/invocation. There's no persistent storage or cache for that. They're separate and a new invoke will start fresh. This is expected.

If you do multiple URLs on the same command line they should be able to reuse the sessionid for connects, but then it will also prefer to reuse the entire connection which is even better and faster.
