### ISSUE TITLE
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by joanix** [curl/curl#4922]
### I did this

curl.exe "https://SomeServerUsingHTTP2.com/intemp.xml"

### I expected the following

(the xml file being downloaded)

### curl/libcurl version

curl 7.68.0 (x86_64-pc-win32) libcurl/7.68.0 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

### operating system

Microsoft Windows [Versión 10.0.18363.657]
(Windows 10 Pro, 64 bits, Spanish language)

**Comment by jay** [comment]
This is not a curl issue, the frames sent by curl are correct but the server is sending a RST_STREAM INTERNAL_ERROR in reply. Also the server closes the connection without a reply when HTTP/1.1 is used.

(What happened to the invalid label?)
