### ISSUE TITLE
CURLINFO_COOKIELIST man page example: non-existing file is stdin

### ISSUE THREAD

**Issue by 3dyd** [curl/curl#4930]
Hello,

From CURLINFO_COOKIELIST example:
```
/* enable the cookie engine with a non-existing file */
curl_easy_setopt(curl, CURLOPT_COOKIEFILE, "-");
```

But "-" stands for `stdin`, isn't it?

**Comment by jay** [comment]
Thanks

**Comment by 3dyd** [comment]
Also could you satisfy my curiosity?

Documentation of `curl_easy_getinfo` says:
_The data pointed-to will be filled in accordingly and can be relied upon only if the function returns CURLE_OK._

So in this part of example:
```
res = curl_easy_getinfo(curl, CURLINFO_COOKIELIST, &cookies);
if(!res && cookies) {
  ...
  curl_slist_free_all(cookies);
}
```

Why one would need to check that `cookies != NULL`?

If "just in case", then why not to be consistent and go further with
```
res = curl_easy_getinfo(curl, CURLINFO_COOKIELIST, &cookies);
if(!res) {
  ...
}
if (cookies) {
  curl_slist_free_all(cookies);
}
```

**Comment by jay** [comment]
The documentation for the specific option always takes precedence, however in this case there is no conflict. If curl_easy_getinfo returns CURLE_OK then cookies was written to but is NULL if there were no cookies.

**Comment by 3dyd** [comment]
Perfect. Thank you.
