### ISSUE TITLE
CURLM_RECURSIVE_API_CALL returned on curl_multi_add_handle() erroneously?!

### ISSUE THREAD

**Issue by Andreas7506** [curl/curl#4938]
Hi!

I have a deamon implementing cURL for doing downloads and other HTTP requests. The daemon can be called multiple times, asynchronously. If i start a download and while that download is in progress, try to add another request by calling curl_multi_add_handle(), on occasion i get CURLM_RECURSIVE_API_CALL error.
The reason for this as i can see is that i try to add the multi handle from one thread (an HIDL call), while cURL calls progress update callback function. I would expect it to be possible to process the progress update callback and simultaneously, NOT from inside the callback, add another multi handle by calling curl_multi_add_handle(). That is currently not possible since there is no check that the call to curl_multi_add_handle() is performed from inside the callback, only that a callback is currently being called. Do i need to check by my self that i am not currently executing a callback function when i try to add a new multi handle from another thread?

I use libcurl version 7.68.0 on an Android platform

Regards
Andreas

**Comment by bagder** [comment]
> Do i need to check by my self that i am not currently executing a callback function when i try to add a new multi handle from another thread?

**Yes**. You must never use the same handle simultaneously in more than one thread. As the [thread-safe](https://curl.haxx.se/libcurl/c/threadsafe.html) document says

*"You must never share the same handle in multiple threads. You can pass the handles around among threads, but you must never use a single handle from more than one thread at any given time."*

**Comment by Andreas7506** [comment]
Thanks for the clarification and the link! :)

For my understanding...

I currently only have one thread using the handle at any given time. The callback functions i register in libcurl are called from libcurl on a thread other than my "main" thread. Doesn't this mean that i always risk running in to this scenario if libcurl calls a callback function and i try to add a new multi handle at the same time from my main thread?

Regards

**Comment by bagder** [comment]
If the callback is called in another thread, it means that curl is *running* and using that handle in another thread. Then you must not use that same handle in another thread (until you've stopped using the handle in the first thread).

One way to solve this is to simply message the first thread about the new handle to add and then it can add it in its thread at next opportunity.

**Comment by Andreas7506** [comment]
Thanks!

Will add code to make sure we don't try to access the handle simultaneously.

Regards
Andreas
