### ISSUE TITLE
Feature: SSH style --proxycommand

### ISSUE THREAD

**Issue by fasmide** [curl/curl#4941]
### I did this
`man curl` :)

### I expected the following
I expected to find a `-pc, --proxycommand` which, [ssh ProxyCommand style](https://man.openbsd.org/ssh_config.5#ProxyCommand), would allow the user to make curl run a command and use its stdio to make requests and not do any network connection by itself. 

That way, it would be really easy to use ssh as a means of transport to another network, e.g.

```
curl --proxycommand 'ssh pi@raspberrypi.local -W 10.1.1.75 80' \
       http://some/otherwise/unavailable/service.php
```

Today, bash scripts have to run, maintain and close an ssh session prior to running curl, which in my opinion is rather cumbersome

I do realize its often possible to turn the situation around, by SSH'ing to the remote host and, if available, run curl on the remote - while being a good workaround in a lot of cases there is always this one time where you have multiple `-F` parameters (so you cannot really use `@-` for POST input) or just don't want to expose auth details with the remote.

I'm just the average curl user and as such haven't read the documentation thoroughly - but I have a feeling the [Opensocket and Closecosket](https://ec.haxx.se/libcurl/libcurl-callbacks/callback-openclosesocket) options can be used to achieve this

**Comment by bagder** [comment]
Thanks, I think that's an excellent idea. 

We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document and we will close this feature-request when we do that.

**Comment by HACKClown** [comment]
IPv4 vs IPv6 Proxy list
