### ISSUE TITLE
Compile on Windows fails with fatal error U1077

### ISSUE THREAD

**Issue by kvonbargen** [curl/curl#4948]
### I did this
1. Downloaded the source code from Github.
2. Ran ```buildconf.bat```
3. With VS2015 x64 Prompt:
    ```C:\curl\winbuild>nmake /f Makefile.vc mode=dll VC=14 MACHINE=x64```
Error:
```
C:\curl\lib\config-win32.h(722): fatal error C1083: File could not be open: "sdkddver.h": No such file or directory
NMAKE: fatal error U1077: ""C:\Program Files(x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"": Code "0x2"
Stop.
NMAKE: fatal error U1077: ""C:\Program Files(x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"": Code "0x2"
Stop.
```
Previous Output of running the buildconf.bat:
```
Generating prerequisite files
* C:\Curl\Makefile
* C:\Curl\src\tool_hugehelp.c

Warning: The curl manual could not be integrated in the source. This means when you build curl the manual will not be available (curl --man). Integration of the manual is not required and a summary of the options will still be available (curl --help). To integrate the manual your PATH is required to have groff(nroff, perl and optionally gzip for compression.
```

### I expected the following
No Error and libcurl.dll created in
```C:\Curl\builds\libcurl-vc14-x64-release-dll-ipv6-sspi-winssl\bin```

(Atleast according to a guide on how i have to setup Curl for another project)
### curl/libcurl version

Latest verion
master-branch
3735107

### operating system
Windows10
VS Community 2015

**Comment by bagder** [comment]
> C:\curl\lib\config-win32.h(722): fatal error C1083: File could not be open: "sdkddver.h": No such file or directory

Our header includes that unconditionally for `_MSC_VER >= 1500`, doesn't that perhaps imply that you should have that header with your VS install?

**Comment by kvonbargen** [comment]
Thanks for the quick response!
I don't fully understand what you mean...
Accoding to https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd
VS2015 [14.x] has a _MSC_VER>=1900>1500

**Comment by kvonbargen** [comment]
However just calling :
``` C:\Curl\winbuild>nmake /f Makefile.vc mode=dll```
results in the exact same Error Message

**Comment by bagder** [comment]
I meant that you're supposed to have that header file so why doesn't the compiler find it?

**Comment by kvonbargen** [comment]
So I could have probably forgot the install sth necessary in the installation of VS ? ...
And now I should try to find out what I'm missing or if all PATH systemvariables are assigned correctly.
Sry I'm not that into cpp etc. yet ...
