### ISSUE TITLE
Lets Encrypt wild card certificate

### ISSUE THREAD

**Issue by tobbe-eklov** [curl/curl#4950]
### I did this

curl https://routerboard.se

### I expected the following
Not this:
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

### curl/libcurl version

[curl -V output]
7.67 in Ubuntu and 7.68 in Catalina

### operating system

Catalina 10.15.3, curl from homebrew
Darwin  19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

and 

Ubuntu 20.04 apt updare/upgrade done

Linux 5.4.0-14-generic #17-Ubuntu SMP Thu Feb 6 22:47:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
1. This wildcard cert is for `*.routerboard.se` which thus doesn't match the host name `routerboard.se`
2. I believe the server doesn't provide the full cert chain in the handshake.

SSLlabs points out problem (1) immediately: https://www.ssllabs.com/ssltest/analyze.html?d=routerboard.se&hideResults=on

**Comment by bagder** [comment]
When telling SSLlabs to go on [in spite of the name mismatch](https://www.ssllabs.com/ssltest/analyze.html?d=routerboard.se&s=91.202.156.9&hideResults=on&ignoreMismatch=on&latest) it also confirmed my (2): "This server's certificate chain is incomplete. Grade capped to B.". There's an intermediate cert missing: "Let's Encrypt Authority X3 "

**Comment by tobbe-eklov** [comment]
Damned! :)
I checked it at internet.nl but not SSLlabs.
Thanks Daniel!

**Comment by bagder** [comment]
Case closed, the server has issues and this isn't a curl bug.
