### ISSUE TITLE
HTTPS transfer stalled when using pause/continue

### ISSUE THREAD

**Issue by andrsbub** [curl/curl#4966]
### I did this
I have an application that is (ab)using the pause/continue feature of libcurl.
The application is having the CURLOPT_WRITEFUNCTION write the http data to a
small buffer, pausing the transfer when this buffer space is running low.  The
issue is that, on occasion, the transfer is not properly resumed after calling
`curl_easy_pause(... CURLPAUSE_CONT)`. The buffer with the data that caused the
CURL_WRITEFUNC_PAUSE return is always delivered, but no new data is received.
The application is using the normal `curl_multi_perform()` to drive the
transfer.

### libcurl version
libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.39.2 librtmp/2.3

### operating system
Linux hilbert 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
@andrsbub also posted [an example code](https://curl.haxx.se/mail/lib-2020-02/att-0063/curlpause.c) that can reproduce this issue when [he posted to the mailing list](https://curl.haxx.se/mail/lib-2020-02/0063.html)

**Comment by bagder** [comment]
The fix was reverted, this issue is back.
