### ISSUE TITLE
Curl_socketpair is not using socket callbacks

### ISSUE THREAD

**Issue by elsamuko** [curl/curl#4991]
Here:
https://github.com/curl/curl/blob/master/lib/socketpair.c#L72
The code is not using the callbacks for socket() and setsockopt(). Maybe related to #4829.

### I did this
Set `CURLOPT_OPENSOCKETFUNCTION` to a callback function.

### I expected the following
curl is not using socket()

### curl/libcurl version
7.68.0

### operating system
Windows 10

**Comment by bagder** [comment]
Fair point. It could indeed be a way to satisfy #4829 ...

**Comment by bagder** [comment]
Ah, well except that socket callbacks are set per easy handle and the socketpair used for the multi handle doesn't have an easy handle and therefor no callback...
