### ISSUE TITLE
Using proxy with negotiate, POST with content length zero ends with too many redirects

### ISSUE THREAD

**Issue by IvanoG** [curl/curl#4996]
Operating system: Windows 2016
curl version: 7.68

curl.exe -X POST -x user:password@proxy --proxy-negotiate server_address -d ""

I expected to receive an answer from the server_address.

The result is "too many redirects". It works with -d "something"

**Comment by bagder** [comment]
You need to show us details from the HTTP protocol exchange! Without that we can't do anything. (and you don't want/need `-X POST` in that command line)

Perhaps add `--trace-ascii log.txt` to the command line and attach that file here? (after you'd made sure it doesn't contain anything sensitive)

**Comment by IvanoG** [comment]
I attached the requested file [log.txt](https://github.com/curl/curl/files/4270175/log.txt)

**Comment by bagder** [comment]
I have an idea. I'll propose a PR in a sec...

**Comment by bagder** [comment]
@IvanoG, it would be great if you could confirm that this patch actually fixes your problem!

**Comment by IvanoG** [comment]
The fix solved the problem. Thanks.
