### ISSUE TITLE
Tests do not complete on Linux and Macos

### ISSUE THREAD

**Issue by captain-caveman2k** [curl/curl#5014]
## I did this

I compiled the latest code from the repository, via `make`, and ran the tests, via `make test`,

### I expected the following

The tests to finish and report the status of those tests ran.

### curl/libcurl version

git master

### operating system

Myself:

1. Ubuntu 16.04 - Linux 4.4.0-174-generic # 204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

2. Ubuntu 18.04 - Linux server031 4.15.0-88-generic # 88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

3. Ubuntu 18.04 (WSL) - Linux 4.4.0-18362-Microsoft # 476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

CI Tests:

Not known but seen in Linux and Macos being kill after 60 minutes as seen [here](https://github.com/curl/curl/pull/5012/checks?check_run_id=478483412) and [here](https://github.com/curl/curl/pull/4956/checks?check_run_id=478437047).

## Additional information:

From my own autobuilds and `runtests.pl` it looks like test670 enters an infinite loop as...

stderr670 ends up outputting the folowing over and over again, with no end in sight:

````
* Curl_readwrite: forcibly told to drain data
* Curl_readwrite: forcibly told to drain data
* Curl_readwrite: forcibly told to drain data
````
memdump also has an equal amount of:

````
RECV /home/steve/Development/curl/lib/sendf.c:460 recv(16384) = -1
RECV /home/steve/Development/curl/lib/sendf.c:460 recv(16384) = -1
RECV /home/steve/Development/curl/lib/sendf.c:460 recv(16384) = -1
````

**Comment by captain-caveman2k** [comment]
Disabling test670, test671, test672 and test673 locally, in a very limited test, allows `runtest.pl` to continue.

I have temporarily modified my autobuilds to pass `--runtestopts="!670 !671 !672 !673"` into `testcurll.pl`.

**Comment by jay** [comment]
Try git revert fa0216b see what happens. drain is tricky and I don't totally understand it so I won't be much help here.

/cc @bagder @monnerat @tatsuhiro-t

**Comment by captain-caveman2k** [comment]
Cheers @jay... I'll try that later - at least for now I've stopped my autobuilds from infinite looping so I can now go to bed for a few hours kip.

**Comment by mback2k** [comment]
I am also seeing this issue on most of my builds.

**Comment by bagder** [comment]
See #5015

**Comment by mback2k** [comment]
FYI: I cancelled stuck (long-running or never-ending) Azure Pipeline jobs related to this issue.
