### ISSUE TITLE
AppVeyor builds failing due to issues with proxy related tests

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5022]
### I did this
During the development of PR #5021 the following failing tests have been detected:
![image](https://user-images.githubusercontent.com/231943/75717608-ba324b80-5cd1-11ea-96d6-e99b43daeeb0.png)
![image](https://user-images.githubusercontent.com/231943/75717678-d7671a00-5cd1-11ea-82d5-9a3dbfba067c.png)

### I expected the following
No tests failing.

### curl/libcurl version
Current master branch

### operating system
AppVeyor CI Windows VMs

**Comment by mback2k** [comment]
Link to example build: https://ci.appveyor.com/project/curlorg/curl/builds/31191630

**Comment by mback2k** [comment]
This seems to be related to the fact that AppVeyor is running its API service on localhost at port 50078. They say they use a random port, but that does not seem to be true.

**Comment by bagder** [comment]
I've run test 63 1255 1256 1257 1265 repeated locally on linux and I don't spot any problem.

Can you try to revert 0caae3c4be4 in this branch and see if makes a diff?

**Comment by mback2k** [comment]
Will do tomorrow. I will try to find out if this is a curl issue or a CI environment issue.

**Comment by bagder** [comment]
In the mean time, I noticed that only three appveyor builds failed in the [most recent merge to master](https://github.com/curl/curl/commit/0e539970e423fb562a42de6e5aa3f4cd3866999b) and only one of them seemed to fail a similar set of tests. I've restarted those CI jobs now to see if they reproduce or if I learn something else.

**Comment by bagder** [comment]
In the re-run, one of the three tests failed again and this time only with the "normal" single 1501 test fail that we've seen for a very long time.

**Comment by mback2k** [comment]
I think we can close this issue as the problem I was seeing is fixed with https://github.com/curl/curl/pull/5021/commits/133da5ba52dc0ce2da331e77b9cb6005fb7e91e0.
