### ISSUE TITLE
cirrus-ci FreeBSD 13.0 builds permafail

### ISSUE THREAD

**Issue by bagder** [curl/curl#5028]
### I did this

CI builds on the freebsd-13-0-snap image results in this error, seemingly permanent:

~~~
pkg install -y autoconf automake libtool pkgconf brotli openldap-client heimdal libpsl libmetalink libssh2 openssh-portable libidn2 librtmp libnghttp2 nghttp2 stunnel
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
Fetching packagesite.txz: .......... done
Processing entries: .......
pkg: wrong architecture: FreeBSD:13.0:amd64 instead of FreeBSD:13:amd64
pkg: repository FreeBSD contains packages with wrong ABI: FreeBSD:13.0:amd64
Processing entries... done
Unable to update repository FreeBSD
Error updating repositories!

Exit status: 3
~~~

[Example](https://github.com/curl/curl/runs/481759104)

### I expected the following

Green builds

**Comment by fkorotkov** [comment]
I don't think there is anything on our side that we can do about:

> pkg: repository FreeBSD contains packages with wrong ABI: FreeBSD:13.0:amd64

Cirrus is using images available on Google Cloud Platform (here is a full list). And since you are using 

```yaml
image_family: freebsd-13-0-snap
```

to point to the latest available image you might get such unexpected behaviour.

There were already couple of images release in 2020 of FreeBSD 13:

```console
freebsd-13-0-current-amd64-v20200102  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200109  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200116  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200123  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200130  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200206  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200213  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200220  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
freebsd-13-0-current-amd64-v20200227  freebsd-org-cloud-dev  freebsd-13-0-snap              READY
```

You can try to pin `image` (instead of using `image_family`) to pin to a specific version:

```yaml
image: freebsd-13-0-current-amd64-v20200220
```

/cc @emaste

**Comment by dfandrich** [comment]
13.0 is still probably close to a year away from a stable release, so such
breakages don't surprise me much. We could also just remove 13.0 for now and
add it back once it works again.

**Comment by emaste** [comment]
TBH breakage like this does surprise me, I'd usually expect more subtle breakage. But yes I think the most expedient fix will be to disable 13.0 for now.

**Comment by bagder** [comment]
Thanks for excellent feedback everyone. So lets disable the FreeBSD 13 builds for now and come back and enable it again in another six months or so.

**Comment by emaste** [comment]
Here's the FreeBSD bug tracking this issue: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244549

**Comment by dfandrich** [comment]
FWIW, the FreeBSD 13.0 image seems to be working again.
