### ISSUE TITLE
Test 1117 takes nearly 30 seconds

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5032]
### I did this
I took a look at the CI runs trying to find out why some take longer than expected.

For some reason test 1117 takes quite long, between 20 and 30 seconds.

Is this expected behaviour of this test? If yes, I think it should be documented.

### I expected the following
Most tests take less than 1 second, some around 1 second.

### curl/libcurl version
CI builds from current master.

### operating system
CI VMs.

**Comment by jay** [comment]
That test is purposely delayed but I don't know why it's delayed 30 seconds. It takes 23 seconds for me.
https://github.com/curl/curl/blob/2cfac302fbeec68f1727cba3d1705e16f02220ad/tests/data/test1117#L33-L35
writedelay means delay 1 second per packet so for each header line that's sent it's 1 second if I understand it right. Here is the last reply for example:

~~~
15:42:34.020505 <= Recv header, 30 bytes (0x1e)
0000: HTTP/1.1 206 Partial Content
15:42:36.053055 <= Recv header, 37 bytes (0x25)
0000: Date: Thu, 09 Sep 2010 14:49:01 GMT
15:42:37.056390 <= Recv header, 22 bytes (0x16)
0000: Accept-Ranges: bytes
15:42:39.094748 <= Recv header, 32 bytes (0x20)
0000: Content-Range: bytes 10-18/155
15:42:40.095696 <= Recv header, 20 bytes (0x14)
0000: Content-Length: 13
15:42:41.111276 <= Recv header, 26 bytes (0x1a)
0000: Content-Type: text/plain
15:42:41.111593 <= Recv header, 2 bytes (0x2)
0000: 
15:42:41.111680 <= Recv data, 11 bytes (0xb)
0000: partial bod
15:42:42.125480 <= Recv data, 2 bytes (0x2)
0000: y.
~~~

**Comment by mback2k** [comment]
I guess the random jitter up to 30 seconds comes from varying VM performance, especially for non-Unix environments.

Thanks for the explanation, I guess this can be closed then.
