### ISSUE TITLE
Problem with resolving hostname with socks5 proxy on 7.69.0

### ISSUE THREAD

**Issue by vitaha85** [curl/curl#5053]
Hi,
I have some problems with resolving host name

~ curl --version
curl 7.69.0 (x86_64-apple-darwin19.3.0) libcurl/7.69.0 SecureTransport zlib/1.2.11
Release-Date: 2020-03-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

When trying to use socks5 proxy after upgrade i get : 
* Closing connection 0
curl: (6) Couldn't resolve host name

Command: curl -x socks5://username:password@11.11.11.11:1080 https://google.com -v

if I use socks5h everything ok
Command curl -x socks5h://username:password@11.11.11.11:1080 https://google.com -v

On version 7.68.0 command curl -x socks5://username:password@11.11.11.11:1080 https://google.com -v works well

**Comment by bagder** [comment]
No doubt an efffect from #4907 and 4a4b63daa. I'll investigate.

**Comment by amishmm** [comment]
**Does the fix apply to socks4 proxy too?**

I am using socks4 and facing similar problem after upgrading from curl 7.67.0 to 7.69

> $ ssh -D 8888 -fN foo@bar.com
> $ curl -v -x socks://127.0.0.1:8888 https://google.com
> *   Trying 127.0.0.1:8888...
> * SOCKS4 communication to google.com:443
> * SOCKS4 non-blocking resolve of google.com
> * Closing connection 0
> curl: (6) Couldn't resolve host name


It worked fine with 7.67.0

**Comment by bagder** [comment]
> Does the fix apply to socks4 proxy too?

It does not, as I wasn't aware of any problem there. Can you please submit this as a new issue and I'll see if it has the same bug there perhaps...
