### ISSUE TITLE
Mistakes in autotools code (configure.ac)

### ISSUE THREAD

**Issue by fullincome** [curl/curl#5067]
### operating system
CentOS 6 with gcc 4.9.2.

### curl/libcurl version
upstream (commit 94ced8e368243fd53f8185d0cf1fbb5394f42ca6)

### I did this
1) Add this line between 64-65 and 275-276 in configure.ac:
`echo "Compiler info: $compiler_id, $compiler_num\n"`

2) ./buildconf && ./configure --enable-werror

### I expected the following
Some compiler id and version number (492) in output

### I got
Empty $compiler_id, $compiler_num at first echo
And wierd $compiler_num (= 409) at second

### Problems and possible solutions:
1. Condition in configure.ac:68:
`if test "$compiler_num" -ge "500"; then`
is always false, because compiler_num and compiler_id will defined only after CURL_CHECK_COMPILER macro.

As solution: put code about CURL_CFLAG_EXTRAS after CURL_CHECK_COMPILER.

2.  Code in m4/curl-compilers.m4:165-167 determine gcc version wierd. In my view it must be like:
```
diff --git a/m4/curl-compilers.m4 b/m4/curl-compilers.m4
index c64db4bc6..9eb68f698 100644
--- a/m4/curl-compilers.m4
+++ b/m4/curl-compilers.m4
@@ -164,8 +164,9 @@ AC_DEFUN([CURL_CHECK_COMPILER_GNU_C], [
     compiler_id="GNU_C"
     gccver=`$CC -dumpversion`
     gccvhi=`echo $gccver | cut -d . -f1`
-    gccvlo=`echo $gccver | cut -d . -f2`
-    compiler_num=`(expr $gccvhi "*" 100 + $gccvlo) 2>/dev/null`
+    gccvme=`echo $gccver | cut -d . -f2`
+    gccvlo=`echo $gccver | cut -d . -f3`
+    compiler_num=`(expr $gccvhi "*" 100 + $gccvme "*" 10 + $gccvlo) 2>/dev/null`
     flags_dbg_all="-g -g0 -g1 -g2 -g3"
     flags_dbg_all="$flags_dbg_all -ggdb"
     flags_dbg_all="$flags_dbg_all -gstabs"
```

**Comment by bagder** [comment]
For (1), yes that seems correct.

For (2), that seems insufficient. On my machine:

~~~
$ gcc -dumpversion 
9
$ gcc --version
gcc (Debian 9.2.1-30) 9.2.1 20200224
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ gcc -v 2>&1 | grep ^gcc
gcc version 9.2.1 20200224 (Debian 9.2.1-30) 
~~~
Checking older gcc versions it seems configure is okay:
~~~
$ gcc-4.7 -dumpversion
4.7
$ gcc-5 -dumpversion
5.5.0
$ gcc-6 -dumpversion
6.5.0
$ gcc-7 -dumpversion
7
$ gcc-8 -dumpversion
8

**Comment by bagder** [comment]
BTW, why is (2) a problem in your case? The number logic makes 1.2.3 into "102" but that's intended. It should work fine for gcc < 7.

**Comment by fullincome** [comment]
No problem for me anymore, thanks.

(2) - If it intended - ok. Translation of version 1.2.3 -> 102 confused me a little .
With gcc >= 7 there is still a mistake.

**Comment by bagder** [comment]
For (2) it's not really a mistake either since nothing depends on the minor version to be in the number, so I made sure to better document how the number is created in #5069
