### ISSUE TITLE
Test 1129 failing with 5 digit runtests.pl base port number

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5070]
### I did this
`runtests.pl -b50085`

Example CI build:
https://ci.appveyor.com/project/curlorg/curl/builds/31364504/job/7w1w3w6gcstexj3w?fullLog=true#L3746

### I expected the following
I expected the tests to still work with another port number.

### curl/libcurl version
master branch

### operating system
CI builds

**Comment by bagder** [comment]
The ending `</file>` tag uses a capital F and does isn't match so the file ends at the end of `</client>` instead, which makes it include the command line... which has a different size!

**Comment by mback2k** [comment]
Nice catch! Should I create a PR to fix this and update Content-Length accordingly, or will you?

**Comment by bagder** [comment]
Go ahead if you're on it. If not, I can take a look later tonight.
