### ISSUE TITLE
Creating objects in Riak but getting error, need help for it

### ISSUE THREAD

**Issue by ashishsme14** [curl/curl#5075]
We are using below code

1. curl -v -X PUT -H 'Link: </riak/friendship/mark>; riaktag="supervisor", Link: </riak/friendship/sean>; riaktag="supervisor"' -H "content-type: text/plain" http://localhost:8098/riak/friendship/john -d 'My name is John'

2. curl -v -X PUT -H 'Link: </riak/friendship/sean>; riaktag="friend", Link: </riak/friendship/justin>; riaktag="friend"' -H "content-type: text/plain" http://localhost:8098/riak/friendship/mark -d 'My name is Mark'

3. curl -v -X PUT -H 'Link: </riak/friendship/mark>; riaktag="friend", Link: </riak/friendship/kevin>; riaktag="friend"' -H "content-type: text/plain" http://localhost:8098/riak/friendship/sean -d 'My name is Sean'

4. curl -v -X PUT -H 'Link: </riak/friendship/kevin>; riaktag="supervises"' -H "content-type: text/plain" http://localhost:8098/riak/friendship/justin -d 'My name is justin'

after running this we getting below error, please help us -
~~~
   Trying ::1...
* connect to ::1 port 8098 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8098 (#0)
> PUT /riak/friendship/justin HTTP/1.1
> Host: localhost:8098
> User-Agent: curl/7.47.0
> Accept: */*
> Link: </riak/friendship/kevin>; riaktag="supervises"
> content-type: text/plain
> Content-Length: 17
>
* upload completely sent off: 17 out of 17 bytes
< HTTP/1.1 204 No Content
< Vary: Accept-Encoding
< Server: MochiWeb/1.1 WebMachine/1.10.9 (cafe not found)
< Date: Wed, 11 Mar 2020 07:26:40 GMT
< Content-Type: text/plain
< Content-Length: 0
<
* Connection #0 to host localhost left intact

**Comment by bagder** [comment]
I don't see any error? The server sends a 204 response back and curl seems to behave appropriately. What did you expect it to do that it didn't?

Also note that you use a very old curl version.

**Comment by ashishsme14** [comment]
> I don't see any error? The server sends a 204 response back and curl seems to behave appropriately. What did you expect it to do that it didn't?
> 
> Also note that you use a very old curl version.

how to upgrade curl version

**Comment by bagder** [comment]
That's not a question for this issue tracker - which is dedicated for discussions about issues and bugs. Usually you make sure you ugprade using your OS/distro or you download a new version.

Should I read that as you don't see this issue as a curl bug?

**Comment by ashishsme14** [comment]
> That's not a question for this issue tracker - which is dedicated for discussions about issues and bugs. Usually you make sure you ugprade using your OS/distro or you download a new version.
> 
> Should I read that as you don't see this issue as a curl bug?

runinng all 4 scripit still cannot complete required course hands on

**Comment by bagder** [comment]
You haven't told us what these commands didn't do that you expected them to do, so we can't act on this unless you give us more data.
