### ISSUE TITLE
tests: smb server won't start

### ISSUE THREAD

**Issue by bagder** [curl/curl#5077]
### I did this

    cd tests && ./runtests.pl 1451

It takes several seconds with nothing visible happen, and then it outputs:
~~~
RUN: SMB server failed verification
== Contents of files in the log/ dir after test 1451
=== Start of file smb_server.log
 2020-03-11 10:50:26,008 INFO  [SMB] setting up SMB server on port 9016
 2020-03-11 10:50:26,008 ERROR [Errno 2] No such file or directory: u''
 Traceback (most recent call last):
   File "./smbserver.py", line 376, in <module>
     rc = smbserver(options)
   File "./smbserver.py", line 96, in smbserver
     smb_server.processConfigFile()
   File "./python_dependencies/impacket/smbserver.py", line 4166, in processConfigFile
     cred = open(credentials_fname)
 IOError: [Errno 2] No such file or directory: u''
 2020-03-11 10:50:26,009 INFO  [SMB] Returning 2
=== End of file smb_server.log
~~~

I'm a Python newbie and I have a billion (well, almost) versions installed. I'm sure this used to work for me at some point and I don't know when it broke or what made it so.

The `u'` error makes me suspect it has something to do with unicode and Python version 2 vs 3 etc, but I don't know what to do about that.

### I expected the following

The test to complete successfully.

### curl/libcurl version

current git master

### operating system

my up-to-date Debian unstable Linux, kernel 5.4.0-4-amd64

**Comment by bagder** [comment]
I have no idea why, this this patch makes the server start again for me.
~~~diff
diff --git a/tests/smbserver.py b/tests/smbserver.py
index 4fcd34f2b..5f5ff6686 100755
--- a/tests/smbserver.py
+++ b/tests/smbserver.py
@@ -26,14 +26,11 @@ from __future__ import (absolute_import, division, print_function)
 import argparse
 import os
 import sys
 import logging
 import tempfile
-try: # Python 3
-    import configparser
-except ImportError: # Python 2
-    import ConfigParser as configparser
+import ConfigParser as configparser
 
 # Import our curl test data helper
 import curl_test_data
 
 # This saves us having to set up the PYTHONPATH explicitly

**Comment by mback2k** [comment]
argh, please do not commit this as it will break Python 3 support again!

Please tell me, which is your default python? What do you get with `python -V`?

**Comment by bagder** [comment]
That commit is temporarily part of #5071 while I work on this, and it doesn't seem to break too much...

But as said above I have no idea what I'm doing but I find not being able to run tests a pain.

`python -V` shows 2.7.17 for me, but if I try to invoke `./smbserver.py` with python3, that just gives me a busload of other errors instead.

**Comment by MarcelRaad** [comment]
Any idea what could have caused this? I had seen that in @bagder 's autobuilds, but nowhere else.

**Comment by mback2k** [comment]
I was unable to reproduce it yet. I am still thinking that there is some Python library path mess-up somewhere, either in @bagder machines or in general Debian unstable does something weird with Python 3 libraries showing up in Python 2 runtime.

**Comment by jay** [comment]
I can't reproduce in python2.
~~~
owner@ubuntu1604-x64-vm:~/curl/tests$ python2 ./smbserver.py --srcdir=.
2020-03-11 19:06:43,356 INFO  [SMB] setting up SMB server on port 9017
2020-03-11 19:06:43,356 INFO  Config file parsed
~~~
In python3 it wouldn't start due to missing SocketServer (impacket uses this but python3 expects lowercase socketserver) and after I fixed that there were more python2-esque type problems. So I think impacket in the repo is outdated.

**Comment by mback2k** [comment]
@jay: see #5085
