### ISSUE TITLE
Immediate connect failures may cause unexpected retries

### ISSUE THREAD

**Issue by jay** [curl/curl#5083]
### I did this

If happy eyeballs is used and the second attempted connection has an immediate connect failure then addresses in that address family will be retried. This is done by libcurl and separate of the retry logic in the tool and AFAICT does not appear to be intended.

Seen in https://github.com/curl/curl/issues/5080#issuecomment-597923701 but since that uses retry logic in the tool it may be harder to understand so I'm using a repro that's a little different.

Patch libcurl to cause an immediate connect fail for any IPv6 address (I only tested this in Windows, adjustments may be needed for Linux):
~~~diff
diff --git a/lib/connect.c b/lib/connect.c
index 0a7475c..722d14e 100644
--- a/lib/connect.c
+++ b/lib/connect.c
@@ -1248,10 +1248,15 @@ static CURLcode singleipconnect(struct connectdata *conn,
 #endif
     }
     else {
-      rc = connect(sockfd, &addr.sa_addr, addr.addrlen);
+      if(addr.family == AF_INET6)
+        rc = -1;
+      else
+        rc = connect(sockfd, &addr.sa_addr, addr.addrlen);
     }
 
-    if(-1 == rc)
+    if(addr.family == AF_INET6)
+      error = 99;
+    else if(-1 == rc)
       error = SOCKERRNO;
 #ifdef ENABLE_QUIC
     else if(conn->transport == TRNSPRT_QUIC) {
~~~

Then try to connect to localhost with the IPv6 address last:
```
curld --resolve localhost:9999:127.0.0.1,[::1], -v localhost:9999
```

Output:
~~~
* Added localhost:9999:127.0.0.1,[::1], to DNS cache
* STATE: INIT => CONNECT handle 0x9b9b80; line 1619 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* Hostname localhost was found in DNS cache
*   Trying 127.0.0.1:9999...
* STATE: CONNECT => WAITCONNECT handle 0x9b9b80; line 1675 (connection #0)
*   Trying ::1:9999...
* Immediate connect fail for ::1: Unknown error 99 (0x63)
* connect to 127.0.0.1 port 9999 failed: Connection refused
*   Trying ::1:9999...
* Immediate connect fail for ::1: Unknown error 99 (0x63)
*   Trying ::1:9999...
* Immediate connect fail for ::1: Unknown error 99 (0x63)
* Failed to connect to localhost port 9999: Connection refused
* multi_done
* Closing connection 0
* The cache now contains 0 members
* Expire cleared (transfer 0x9b9b80)
curl: (7) Failed to connect to localhost port 9999: Connection refused
~~~

Note the two extra connections to ::1. Reverse it and they aren't attempted...
~~~
curld --resolve localhost:9999:[::1],127.0.0.1, -v localhost:9999
~~~

Output:
~~~
* Added localhost:9999:[::1],127.0.0.1, to DNS cache
* STATE: INIT => CONNECT handle 0x889b80; line 1619 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* Hostname localhost was found in DNS cache
*   Trying ::1:9999...
* Immediate connect fail for ::1: Unknown error 99 (0x63)
*   Trying 127.0.0.1:9999...
* STATE: CONNECT => WAITCONNECT handle 0x889b80; line 1675 (connection #0)
* connect to 127.0.0.1 port 9999 failed: Connection refused
* Failed to connect to localhost port 9999: Connection refused
* multi_done
* Closing connection 0
* The cache now contains 0 members
* Expire cleared (transfer 0x889b80)
curl: (7) Failed to connect to localhost port 9999: Connection refused
~~~

### I expected the following

I'm like 99% sure this is unexpected. Why would libcurl retry on immediate connect failures and only if the second attempted one? I walked through but could not figure out how it happens. In the unexpected case trynextip is called and sees addresses to try (ie try ::1 again and again) which I don't think it should. Something should be clearing it or advancing it so the next ip is null but I'm not sure what. I've walked through both expected and unexpected multiple times and I don't see what causes it.

### curl/libcurl version

master f0e8160 2020-03-08
~~~
curl 7.69.1-DEV (i386-pc-win32) libcurl/7.69.1-DEV OpenSSL/1.0.2t nghttp2/1.40.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL
~~~

### operating system

Windows 7 Enterprise

/cc @Marco01809

**Comment by bagder** [comment]
Is this maybe also what #4954 sees?

**Comment by jay** [comment]
> Is this maybe also what #4954 sees?

Probably. It looks similar but there's more retries in that one. In my repro above I observe always 2 retries of the IPv6 address. I ran it a number of times.

**Comment by bagder** [comment]
In the #4954 case it probably goes on for a longer time because the IPv4 connect attempt is black holed and thus doesn't get any response but will fail due to a timeout.

**Comment by jay** [comment]
> In the #4954 case it probably goes on for a longer time because the IPv4 connect attempt is black holed and thus doesn't get any response but will fail due to a timeout.

Makes sense. I've marked this as a duplicate of #4954.
