### ISSUE TITLE
curl --next use

### ISSUE THREAD

**Issue by taylorwin** [curl/curl#5084]
I want use the same connection submitting two URL ，i  can use the "--next" option.

`curl -X "GET" xxxx.com/1  --next -X "POST" -d @file  xxxx.com/2`

how can i  submit the first URL  and  submit seconde URL  use the same connection after **deal with some date**   ?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

**Comment by taylorwin** [comment]
Thank you for your reply.
I don't know if curl has this feature.
I will confirm if there is such usage through https://curl.haxx.se/mail/

**Comment by bagder** [comment]
I don't understand what feature you mean, so when you post the question to the list, perhaps try to elaborate or rephrase?

**Comment by taylorwin** [comment]
I want send tow requests  **use the same connection**
The second request needs to be submitted after processing the first response。
