### ISSUE TITLE
cmake finds non-existing stropts.h so build fails

### ISSUE THREAD

**Issue by bagder** [curl/curl#5092]
### I did this

    cmake .
    make

...
~~~
/home/daniel/src/curl/lib/if2ip.c:47:12: fatal error: stropts.h: No such file or directory
   47 | #  include <stropts.h>
      |            ^~~~~~~~~~~
compilation terminated.
~~~

    $ grep STROPT lib/curl_config.h
    #define HAVE_STROPTS_H 1

### I expected the following

Since I don't have a `stropts.h` header, I would've expected cmake to not find it and thus not claim that it can be included so that the build works...

### curl/libcurl version

current git master

### operating system

Debian Linux, unstable/sid. cmake 3.16.3

I'll welcome suggestions and ideas on how this can be debugged!

**Comment by jzakrzewski** [comment]
Start by checking $BUILD_DIR/CMakeFiles/CMakeOutput.log.

**Comment by bagder** [comment]
Thanks! Unfortunately 

In there I can see that it runs this command line...
~~~
/usr/bin/cc -DLDAP_DEPRECATED=1  -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -Wdouble-promotion -Wno-system-headers    -o CMakeFiles/cmTC_35099.dir/HAVE_STROPTS_H.c.o   -c /home/daniel/src/curl/CMakeFiles/CheckIncludeFiles/HAVE_STROPTS_H.c
~~~
... to check if the header exists. If I run that manually, I get:
~~~
/home/daniel/src/curl/CMakeFiles/CheckIncludeFiles/HAVE_STROPTS_H.c:45:10: fatal error: stropts.h: No such file or directory
   45 | #include <stropts.h>
      |          ^~~~~~~~~~~
compilation terminated.
~~~
So I don't understand why cmake doesn't get the same or why it think the header is fine? It also seems to be a problem unique for me since the CI builds and lots of other people seem to be able to build with cmake...

**Comment by jay** [comment]
> So I don't understand why cmake doesn't get the same or why it think the header is fine?

`find / -name stropts.h 2>/dev/null`

**Comment by bagder** [comment]
Sorry for the noise. For some reason I can't explain, it worked fine after I removed `CMakeCache.txt` and all the old cmake files and reran it. No point in chasing this anymore.
