### ISSUE TITLE
curl_easy_duphandle() bug after 7.69.1

### ISSUE THREAD

**Issue by kn007** [curl/curl#5097]
I try it on 7.69.1 and 7.69.2-dev, same problem. 7.69.0 working well.

```
  OS               Linux CentOS Linux release 8.1.1911 (Core)
  Kernel           5.5.5-1.el8.elrepo.x86_64
```

```
--disable-static --enable-threaded-resolver --with-gssapi --with-nghttp2 --enable-ares
```

```
curl 7.69.2-DEV (x86_64-pc-linux-gnu) libcurl/7.69.2-DEV OpenSSL/1.1.1c-fips zlib/1.2.11 c-ares/1.16.0 libidn2/2.2.0 nghttp2/1.40.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

dnf:
```
CentOS-8 - AppStream                                                                                             0.0  B/s |   0  B     00:00
Error: Failed to download metadata for repo 'AppStream': Cannot prepare internal mirrorlist: curl_easy_duphandle() call failed
```

git:
```
Cloning into 'curl'...
warning: curl_multi_add_handle failed: Invalid easy handle
fatal: unable to access 'https://github.com/curl/curl/': failed to start HTTP request
```

**Comment by bagder** [comment]
Can you provide a simple stand-alone example code showing this problem? Both the tools you refer to above are huge and complex applications that make things really hard to debug or even understand what they're doing.

**Comment by kn007** [comment]
Sorry, I'm afraid that I can't.
I guess it happened after commit: https://github.com/curl/curl/commit/c8f086bcc315d9dec6a7438f39c3c36dfeb27e42
let me try it.

**Comment by kn007** [comment]
My guess is correct.
After run
`git reset --hard e364546fb3371ac27f59f897e4c55acce7fc824e`
make curl and it working fine.

but reset to c8f086bcc315d9dec6a7438f39c3c36dfeb27e42 , it's broken..

**Comment by bagder** [comment]
I still can't see what's wrong in there...

**Comment by jay** [comment]
If c-ares is too old or IPv6 support is disabled (like is the case here) those functions could return CURLE_NOT_BUILT_IN:

https://github.com/curl/curl/blob/b81e0b07784dc4c1e8d0a86194b9d28776d071c0/lib/asyn-ares.c#L788-L812

I don't know for sure this is the problem but I don't see what else it could be. #5100 should fix this, @kn007 can you please try it?

**Comment by kn007** [comment]
Ok, let me try it, wait a minute.

my c-ares is 1.16.0, IPv6 is disabled.

**Comment by kn007** [comment]
@jay Yes, it's working fine after patch https://github.com/curl/curl/pull/5100 .
Thanks for your work.

**Comment by bagder** [comment]
But why is the build IPv6-disabled, no such configure option was shown?

**Comment by kn007** [comment]
My OS disabled the ipv6 on grub.
```
GRUB_CMDLINE_LINUX = ... ipv6.disable=1
```
Some people like me, will change it on the sysctl.conf file.

**Comment by jay** [comment]
Thanks

**Comment by michael-o** [comment]
To whom it may concern, the one off patch has already been applied to the FreeBSD Ports system: https://svnweb.freebsd.org/changeset/ports/530365
