### ISSUE TITLE
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto 

### ISSUE THREAD

**Issue by ekhanad** [curl/curl#5098]
I am trying to build curl on AIX and I want to add a runtime search path to the curl executable. 
I have added the following flag

LDFLAGS='-bsvr4 -Wl,-R\$ORIGIN/../lib -L$WORKSPACE/externals/lib'

curl builds without the '-bsvr4 -Wl,-R\$ORIGIN/../lib' but then cannot be run as it cannot find the openssl libs as it links against the system version.

What I want to achieve is that curl can find the openssl libs (libssl and libcrypto) from a custom location. I have openssl installed on two different locations ( custom and system). It is not possible for me to uninstall the custom one.

Curl version is curl-7.69.1.

**Comment by bagder** [comment]
You probably also need to use `--with-ssl=...` to point out the location (prefix really) of the openssl lib to use in configure.

**Comment by ekhanad** [comment]
I am pointing to the base directory of the openssl.  I have the libs under $WORKSPACE/externals/libs

--with-ssl=$WORKSPACE/externals

**Comment by bagder** [comment]
Doesn't configure also say `Added $LIB_OPENSSL to CURL_LIBRARY_PATH` and identifying the correct lib and path?

**Comment by ekhanad** [comment]
15:13:51  configure: Added /jenkins2/workspace/Tools/Build-and-Upload-curl-to-Artifactory/externals/lib to CURL_LIBRARY_PATH
15:13:51  checking for OpenSSL headers version... 1.1.1 - 0x1010102fL
15:13:51  checking for OpenSSL library version... 1.1.1
15:13:51  checking for OpenSSL headers and library versions matching... yes15:13:51  configure: Added /jenkins2/workspace/Tools/Build-and-Upload-curl-to-Artifactory/externals/lib to CURL_LIBRARY_PATH
15:13:51  checking for OpenSSL headers version... 1.1.1 - 0x1010102fL
15:13:51  checking for OpenSSL library version... 1.1.1
15:13:51  checking for OpenSSL headers and library versions matching... yes

.....
....
...
checking run-time libs availability... failed
15:13:56  configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lz

**Comment by bagder** [comment]
> `Added /jenkins2/workspace/Tools/Build-and-Upload-curl-to-Artifactory/externals/lib to CURL_LIBRARY_PATH`

That's good and shows configure found it in the right dir.

If you look in `config,log` (after configure failed) around that failure, does it give any clues? I see it also found and uses zlib at that point, is that accessed correctly too?

**Comment by ekhanad** [comment]
I Found the following in the **config.log**

Could not load module /jenkins2/workspace/Tools/Build-and-Upload-curl-to-Artifactory/externals/lib/libssl.so.
Dependent module `/usr/lib/libcrypto.a(libcrypto64.so.1.1)` could not be loaded.
Member libcrypto64.so.1.1 is not found in archive 
Could not load module conftest.
Dependent module /jenkins2/workspace/Tools/Build-and-Upload-curl-to-Artifactory/externals/lib/libssl.so could not be loaded.
configure:28571: $? = 255
configure: program exited with status 255
configure: failed program was:

I can confirm that the lib exists at the location.  Configure is looking at the default locations and seems to ignore the LDFLAGS

**Comment by bagder** [comment]
It is the compiler (linker really) that uses `LDFLAGS` and configure can't even make it *not* use it as far as I know.

When configure runs that command line, xlc obviously still thinks it should look in /usr/lib (first) for libraries, even if `-L` points out another directory (twice even). I don't know why it would do that as it makes it really hard to link with alternative libs that are also present in the default path...

**Comment by ekhanad** [comment]
ok! I have to find some other way of adding  run time libs to the binary.  One option could be to update the curl executable (XCOFF file)  at install time.

**Comment by bagder** [comment]
I don't see what we can do differently in the configures script for this case.

**Comment by ekhanad** [comment]
Right!
I have implemented the other solution now where we update the R path in the executable at installation time.
Thanks for your fast support.
