### ISSUE TITLE
windres: error: invalid output format: `COFF'

### ISSUE THREAD

**Issue by muv1** [curl/curl#5099]
Currently Mingw cURL call Windres like this:

https://github.com/curl/curl/blob/0845ecbb6dcaadad4a4891f7e85efb8c8e626ff6/lib/Makefile.m32#L101-L102

but the output should actually be spelled `coff`, lower case:

<https://sourceware.org/binutils/docs/binutils/windres.html>

and in fact will fail with certain compilers:

~~~
$ cd lib
$ mingw32-make -f Makefile.m32
[...]
windres --include-dir=../include -DDEBUGBUILD=0 -O COFF -F pe-x86-64
   -i libcurl.rc -o libcurl.res
windres: error: invalid output format: `COFF'
mingw32-make: *** [Makefile.m32:378: libcurl.res] Error 1
~~~

<https://github.com/mstorsjo/llvm-mingw>

**Comment by muv1** [comment]
This seems to be a workaround:

~~~sh
mingw32-make -f Makefile.m32 RCFLAGS='-O coff'
~~~

**Comment by jay** [comment]
Please try #5101
