### ISSUE TITLE
execessive memory use with GnuTLS

### ISSUE THREAD

**Issue by woodcoder** [curl/curl#5102]
I'm running s3fs, built on libcurl.  By default this creates a pool of 20 `curl_easy_init` handles and reuses them with a `curl_easy_reset` between each `curl_easy_perform`.  `curl_easy_cleanup` is called when the pool is destroyed.

After a while the memory usage grows hugely.  Valgrind massif logging shows 100MB of ASN data:

```
 89.99% (286,590,012B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->34.88% (111,074,304B) 0x94E5122: ??? (in /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.5)
| ->24.97% (79,520,320B) 0x94E249F: ??? (in /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.5)
| | ->12.85% (40,930,560B) 0x94E1A7A: asn1_der_decoding2 (in /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.5)
| | | ->12.85% (40,930,560B) 0x747818A: gnutls_x509_crt_import (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | ->12.85% (40,930,560B) 0x747C4A3: gnutls_x509_crt_list_import (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | | ->12.85% (40,930,560B) 0x747C786: gnutls_x509_crt_list_import2 (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |   ->12.85% (40,930,560B) 0x74852F0: gnutls_x509_trust_list_add_trust_mem (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |     ->12.85% (40,930,560B) 0x74857B5: gnutls_x509_trust_list_add_trust_file (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |       ->09.65% (30,717,984B) 0x7485A7B: ??? (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |       | ->09.65% (30,717,984B) 0x7485AC9: gnutls_x509_trust_list_add_trust_dir (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |       |   ->09.65% (30,717,984B) 0x74254F8: gnutls_certificate_set_x509_trust_dir (in /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.10)
| | | | |       |     ->09.65% (30,717,984B) 0x50CC456: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |       ->09.65% (30,717,984B) 0x50CE148: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |         ->09.65% (30,717,984B) 0x50807F0: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |           ->09.65% (30,717,984B) 0x508D124: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |             ->09.65% (30,717,984B) 0x50A2AB4: ??? (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |               ->09.65% (30,717,984B) 0x50A3A31: curl_multi_perform (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
| | | | |       |                 ->09.65% (30,717,984B) 0x5099A12: curl_easy_perform (in /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0)
:
```

It looks like `gnutls_certificate_set_x509_trust_dir` might be *adding* certificates on every call to `curl_easy_perform`?

Should `gnutls_certificate_free_credentials` be being called in `curl_easy_reset` (as it is in `curl_easy_cleanup`)?  Or should the call to `gnutls_certificate_set_x509_trust_dir` be being made in `curl_easy_init` maybe?

### curl/libcurl version

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system

Linux my-server 4.15.0-1057-aws #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jay** [comment]
Please try to reproduce using the [latest curl](https://curl.haxx.se/download.html). AFAIK gnutls_certificate_free_credentials isn't called on reset because [curl_easy_reset](https://curl.haxx.se/libcurl/c/curl_easy_reset.html) doesn't reset connections. It is called when the connection is closed conn_shutdown => Curl_ssl_close => Curl_ssl->close_one => Curl_gtls_close => close_one => gnutls_certificate_free_credentials

**Comment by woodcoder** [comment]
Thanks Jay, I'll try with the latest.  Understood about not resetting connections.  Do you know what the reasoning behind calling `gnutls_certificate_set_x509_trust_dir` multiple times (on every `curl_easy_perform`) is then, rather than just calling it once in `curl_easy_init`?

**Comment by bagder** [comment]
> calling gnutls_certificate_set_x509_trust_dir multiple times (on every curl_easy_perform) is

It is called once per connection:

https://github.com/curl/curl/blob/0845ecbb6dcaadad4a4891f7e85efb8c8e626ff6/lib/vtls/gtls.c#L628

It could probably benefit from getting stored in the easy handle rather than per connection.

**Comment by bagder** [comment]
I cannot reproduce any memory leak with curl-gnutls (GnuTLS/3.6.12) using the current code and valgrind. I do get a few `Conditional jump or move depends on uninitialised value(s)` warnings though, but they're deep inside GnuTLS and I think curl is innocent.

**Comment by nmav** [comment]
>>  calling gnutls_certificate_set_x509_trust_dir multiple times (on every curl_easy_perform) is
> It is called once per connection:

Hmm, the certificate credentials is intended to be shared among connections and it can take a lot of memory depending on the system (i.e., whether it is using a file store or a PKCS#11 store, etc). 

I saw incidentally that high memory usage has been reported at:
https://github.com/transmission/transmission/issues/313
and is solved by switching the curl back-end. There may be value in solving it irrespective of a leak.

**Comment by woodcoder** [comment]
Thanks for investigating, I've been trying to track what the value of GnuTLS's `BACKEND->cred->ncreds` ended up being after repeated calls, but my build/link skills failed me on this occasion.

I think you may be right that it isn't a memory leak as such, just high memory usage (sorry for my use of poor terminology).

Early indications in my testing are that switching to using OpenSSL does indeed solve the problem in the case of s3fs too.

**Comment by jay** [comment]
Is there anything for us to fix here or is this something that should be reported to GnuTLS?

**Comment by bagder** [comment]
That trust context could be stored per transfer instead of per connection in curl, which could save memory when the same handle is used for multiple connections.
