### ISSUE TITLE
SMB tests on Debian?

### ISSUE THREAD

**Issue by bagder** [curl/curl#5104]
### I did this

`apt install python3-impacket`

`cd tests && ./runtests.pl 1451`

~~~
Python package impacket needs to be installed!
Use pip or your package manager to install it.
RUN: failed to start the SMB server
~~~

(I could run them fine before 4be2560e01ed40)

### I expected the following

To be able to run test 1451

### curl/libcurl version

Current git master

### operating system

Debian Linux, unstable. Updated just now.

cc: @mback2k

**Comment by bagder** [comment]
Also, I think the `tests/README` should be updated with the impacket info.

**Comment by mback2k** [comment]
Your Python is still at version 2, so you need to install` python-impacket` instead of `python3-impacket`.

I will do a follow-up PR for `tests/README` and additional CI installs.

**Comment by bagder** [comment]
There is no `python-impacket` anymore, only `python3-impacket`.

**Comment by mback2k** [comment]
Then you will have to a wait a little until I have ported our `smbserver.py` to Python 3. ;-)

**Comment by bagder** [comment]
(strictly speaking, I think it is a regression even if you're on track of fixing it...)

**Comment by mback2k** [comment]
I don't think so, as `smbserver.py` was never Python 3 compatible and you could also just install the Python 2 version of impacket via `pip2 install impacket`.

**Comment by bagder** [comment]
> you could also just install the Python 2 version of impacket via pip2 install impacket

That was not conveyed until now...

**Comment by mback2k** [comment]
> That was not conveyed until now...

Sorry for that, I should have explained that earlier.

**Comment by mback2k** [comment]
New issue for impacket due to missing dependency in their setup.py: https://github.com/SecureAuthCorp/impacket/issues/798
