### ISSUE TITLE
Test 323 is failing now that we have stunnel installed on CI

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5105]
### I did this
I added the stunnel tool to our CI builds via ac566834382340d9de2737aa41c82fea7814590b.

### I expected the following
I expected all existing tests to pass at least on Debian/Ubuntu based builds.

### curl/libcurl version
master branch

### operating system
Ubuntu: https://dev.azure.com/daniel0244/curl/_build/results?buildId=1097&view=logs&j=d75b1133-14f1-5b7f-c1b2-9c6e00513385&t=b4f1d978-9c37-5163-5779-00d93a32ab54&l=1579

cc @bagder

**Comment by bagder** [comment]
The test works fine on my machines. It'd be cool if someone who can repro the failure could single step the TLS connection code and see how come it lets the connection go through when it shouldn't...

**Comment by mback2k** [comment]
Maybe it depends on the stunnel version? Just an idea though.

**Comment by bagder** [comment]
Perhaps, but test 323 is from 2011 and we've used numerous stunnel versions on numerous platforms since...
