### ISSUE TITLE
Torture tests 2034 and 2037 are failing now that we have stunnel installed on CI

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5108]
### I did this
I added the stunnel tool to our CI builds via ac566834382340d9de2737aa41c82fea7814590b.

The following memory leak occurs:
```
** MEMORY FAILURE
Leak detected: memory still allocated: 28 bytes
At 5652c038ae68, there's 28 bytes.
 allocated by vtls/vtls.c:119
LIMIT vtls/vtls.c:125 strdup reached memlimit
```

### I expected the following
I expected all existing tests to pass at least on Debian/Ubuntu based builds.

### curl/libcurl version
master branch

### operating system
Ubuntu:
- test 2034: https://dev.azure.com/daniel0244/curl/_build/results?buildId=1103&view=logs&j=885ef527-7eea-5bf1-0556-10256f64fa14&t=666c7f3f-c4cd-5d93-1667-18caddd5a59f&l=3692
- test 2037: https://dev.azure.com/daniel0244/curl/_build/results?buildId=1103&view=logs&j=885ef527-7eea-5bf1-0556-10256f64fa14&t=666c7f3f-c4cd-5d93-1667-18caddd5a59f&l=4293

cc @bagder

**Comment by bagder** [comment]
I don't think this is a regression, as in this memory leak seems to have landed here a very long time ago...
