### ISSUE TITLE
How to get more information about error code 7?

### ISSUE THREAD

**Issue by lsong0905** [curl/curl#5121]
Hello,

My application is trying to access to a host, and getting Curl error code 7. 
`Curl returned error code 7 - Couldn't connect to server`

I need to diagnose this a bit deeper and see what is happening. I've already implemented a callback function with CURLOPT_DEBUGFUNCTION, and the function displays messages related to "CURLINFO_TEXT", "CURLINFO_HEADER_IN" or "CURLINFO_HEADER_OUT". 

However, all I see in our log file is the above message with error code 7. It seems like I am not getting (and Curl is not logging) the error message or code from openssl or socket calls (if ever exist). 

Is there a way to retrieve that? I would appreciate if you can pinpoint the code that does that. 

The version of libcurl is 7_66_0

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

You might want to use [CURLINFO_OS_ERRNO](https://curl.haxx.se/libcurl/c/CURLINFO_OS_ERRNO.html).
