### ISSUE TITLE
[FEATURE] Able to set client ip when using haproxy protocol

### ISSUE THREAD

**Issue by nunofernandes** [curl/curl#5125]
### Requested feature

When using haproxy-protocol option, allow the possibility of setting the client ip "inside" the haproxy header.
This would allow testing servers with different client ip addresses (without using x-forward-for header).

### Example of usage

`curl --haproxy-protocol --haproxy-clientip=1.2.3.4 https://localhost/`

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
