### ISSUE TITLE
what is the meaning of error code 1020?

### ISSUE THREAD

**Issue by geekyouth** [curl/curl#5127]
### I did this
curl -s http://ip.cn/
![image](https://user-images.githubusercontent.com/12899262/77134635-e1936180-6aa2-11ea-8d97-1f9c487b9157.png)

### I expected the following
您现在的 IP：124.****
所在地理位置：浙江省杭州市 联通

### curl/libcurl version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

[curl -V output]
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

### operating system
win10

**Comment by jay** [comment]
> error code: 1020

AFAICT that's not curl error output, so it is likely from the server. Try running curl with `-v` for verbose.

**Comment by bagder** [comment]
It is from the server, I can reproduce. `error code: 1020` is simply the response body.
