### ISSUE TITLE
 support in curl for using PKCS #11 keys (URIs) for SSH

### ISSUE THREAD

**Issue by sahanaprasad07** [curl/curl#5128]
libssh (master) now has PKCS #11 URI support ()
Instead of passing the private key file, if a PKCS #11 URI is passed, libssh detects it and imports the corresponding key through the openssl engine and uses it for SSH authentication.
Documentation: https://gitlab.com/libssh/libssh-mirror/-/commit/73f383a2e6d6351379e749d7d662dab3fdee396c

### 
I built the latest libssh master (with PKCS #11 URI support), created the srpm and installed it on f31.
And I tried to execute the following:
'su -c 'curl -kvu root: sftp://localhost --key pkcs11:token=softtoken;object=curl;type=private?pin-value=123456' -- libssh'

Error :
User: root
* Authentication using SSH public key file
* Could not load private key file pkcs11:token=softtoken
* Closing connection 0
curl: (67) Could not load private key file pkcs11:token=softtoken
### 
I expected that the PKCS #11 URI would be passed on to libssh.

curl should identify it as a PKCS #11 URI if it begins with pkcs11: and pass it on to libssh.

it would be nice to add this feature to curl so that it supports p11 keys for ssh.
### curl/libcurl version

[curl -V output]
curl 7.66.0 (x86_64-redhat-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.2/openssl/zlib nghttp2/1.39.2
### operating system
Linux ci-vm-10-0-139-187.hosted.upshift.rdu2.redhat.com 5.3.15-300.fc31.x86_64 #1 SMP Thu Dec 5 15:04:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[curl-libssh-pkcs11.txt](https://github.com/curl/curl/files/4359181/curl-libssh-pkcs11.txt)

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by sahanaprasad07** [comment]
sorry for raising this issue. 
The support I was looking for already exists in curl. 
Previously, I had tested with the incorrect version of libssh.

Here are the success logs :

:: [ 05:07:48 ] :: [  BEGIN   ] :: Test SSH access for test user to localhost by curl using PKCS #11 URI :: actually running 'curl -kvu root: sftp://localhost --key "pkcs11:token=softtoken;o
bject=curl;type=private?pin-value=123456"'
*   Trying ::1:22...
* TCP_NODELAY set
* Connected to localhost (::1) port 22 (#0)
* User: root
* Authentication using SSH public key file
* Completed public key authentication
* Authentication complete

So curl can be used with PKCS #11 URIs for SSH connections already :) [with the latest version of libssh (soon to be released in Fedora)]
