### ISSUE TITLE
JSON test 970 failing in autobuilds

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#5131]
### I did this
Test 970, recently added in https://github.com/curl/curl/commit/7631f2b752a00680ac16742753dd7bd78c3a32ac, is failing on different build machines.

Solaris (@dago):
https://curl.haxx.se/dev/log.cgi?id=20200320212806-10792#prob5

NetBSB (@mkauf):
https://curl.haxx.se/dev/log.cgi?id=20200321032432-19780#prob1

Windows (@MarcelRaad):
https://curl.haxx.se/dev/log.cgi?id=20200321055718-9075#prob1
https://curl.haxx.se/dev/log.cgi?id=20200321052431-19031#prob1

### I expected the following
The test to pass on all platforms.

### curl/libcurl version
https://github.com/curl/curl/commit/9b4990f06835a12ec264f4182017df1c1f7e43bd

### operating system
Solaris 10
NetBSD 8.1
Windows/MSYS

**Comment by jay** [comment]
According to the first one the output is missing (missing -foo- and "size_download":0) even though it was received in the trace

~~~diff
-foo-[LF]
-{"url_effective":"http://127.0.0.1:8990/970","http_code":200,"response_code":200,"http_connect":0,"time_total":0.000013,"time_namelookup":0.000013,"time_connect":0.000013,"time_appconnect":0.000013,"time_pretransfer":0.000013,"time_starttransfer":0.000013,"size_header":250,"size_request":85,"size_download":6,"size_upload":0,"speed_download":0.000013,"speed_upload":0.000013,"content_type":"text/html","num_connects":1,"time_redirect":0.000013,"num_redirects":0,"ssl_verify_result":0,"proxy_ssl_verify_result":0,"filename_effective":null,"remote_ip":"127.0.0.1","remote_port":8990,"local_ip":"127.0.0.1","local_port":13,"http_version":"1.1","scheme":"HTTP","curl_version":"curl-unit-test-fake-version"}
+{"url_effective":"http://127.0.0.1:8990/970","http_code":200,"response_code":200,"http_connect":0,"time_total":0.000013,"time_namelookup":0.000013,"time_connect":0.000013,"time_appconnect":0.000013,"time_pretransfer":0.000013,"time_starttransfer":0.000013,"size_header":250,"size_request":85,"size_download":0,"size_upload":0,"speed_download":0.000013,"speed_upload":0.000013,"content_type":"text/html","num_connects":1,"time_redirect":0.000013,"num_redirects":0,"ssl_verify_result":0,"proxy_ssl_verify_result":0,"filename_effective":null,"remote_ip":"127.0.0.1","remote_port":8990,"local_ip":"127.0.0.1","local_port":13,"http_version":"1.1","scheme":"HTTP","curl_version":"curl-unit-test-fake-version"}
~~~

~~~
22:20:16.217530 <= Recv data, 6 bytes (0x6)
0000: -foo-.
~~~

**Comment by bagder** [comment]
The netbsd error is different. It seems to get `"num_connects":0` which also seems wrong!

**Comment by bagder** [comment]
(btw, I added a "raw log download" link to the log viewer, reading those JSON diffs drew me crazy!)

**Comment by dfandrich** [comment]
Other tests are just skipped in similar cases (e.g. test75)

**Comment by mback2k** [comment]
> Other tests are just skipped in similar cases (e.g. test75)

I think we should strive to make tests cross-platform compatible instead of skipping them.

**Comment by bagder** [comment]
Let's see how #5135 and #5136 change things!

**Comment by bagder** [comment]
Hm. :disappointed:  It appears the NetBSD `num_connects` issue is still there: https://curl.haxx.se/dev/log.cgi?id=20200324032502-30192#prob1

**Comment by bagder** [comment]
@mkauf, do you have any chance of debugging this on the actual target to see how this happens?

**Comment by mkauf** [comment]
@bagder yes, I will have a look.
