### ISSUE TITLE
[Documentation improvement] LOW_LIMIT/SPEED options -y -Y

### ISSUE THREAD

**Issue by Bylon2** [curl/curl#5133]
Whishlist: Documentation improvement.
Importance: low

### I did this
Reading the manual of libcurl options: 
CURLOPT_LOW_SPEED_TIME
CURLOPT_LOW_SPEED_LIMIT

And the command line manual about corresponding options -y -Y

_I was wondering if said "low speed" limit was counting time spend by the "user"._

For the library, I mean time spent in the callbacks.
For curl command line, this "time spent" can easily be reproduced on the terminal with CTRL-Z to suspend a download, then resume with the command: `fg`.

### I expected the following

... expected that the "user" time be discounted (that is what I need)... and fortunately it is.
This is easily checked through command line with:

`curl https://example.com/bigfile -Y 1 -y 30 -o /dev/null`

Then do CTRL-Z to suspend and do:

`sleep 60; fg`

The download will resume... unless the server had a shorter keepalive in which case you can get a cryptic error like.

`curl: (56) GnuTLS recv error (-54): Error in the pull function.`

**Documentation suggestion:**

-1) Is this observed behaviour **intended by curl**? (which makes perfect sense!)
-2) If so, it should be briefly documented so that readers of the manual have no question about that.

_-3) if (unlikely) the observed behaviour was not what is intended by curl... then this is a bug!_

> Pass a long as parameter. It contains the time in number seconds that the transfer speed should be below the CURLOPT_LOW_SPEED_LIMIT for the library to consider it too slow and abort.

Could be

> Pass a long as parameter. It contains the time in number seconds that the transfer speed should be below the CURLOPT_LOW_SPEED_LIMIT for the library to consider it too slow and abort. **The  time spent in user callbacks does not count towards that limit**.

Of course you can probably find a better English sentence to explain that time spent in callbacks "does not count", and this parameter is only when curl is "actively" transferring data. This is probably also depending on the granularity of the speed counter (see below), and might not be true on short times spent in callbacks. The explanation then could become tricky!

I am not sure whether the same thing should be explained in the curl (command line) manual. I guess very few user would set the -y, -Y options and suspend, unless they are testing the behaviour as I did.

There could also be some side effects of this parameter with time spent in the callbacks and the granularity of the speed counter.
By reading https://github.com/curl/curl/issues/1345 I understand the granularity is around 1 second. If so and callbacks consume evenly 99% of the time, it can artificially trigger the low_speed error. Sorry I just read the explanation of the linked issue 1345, not the "new algorithm" that is mentioned, which could potentially take care of that!

But I guess anyway there is limited things these options can do, and if the user wants better control he can still use CURLOPT_XFERINFOFUNCTION and do his own speed computation!

**Comment by jay** [comment]
I'm not sure what was intended but personally I would think transfer time includes the time spent in the callbacks.

**Comment by bagder** [comment]
> I would think transfer time includes the time spent in the callbacks.

Absolutely. Anything else would be really weird and even hard to maintain.

**Comment by Bylon2** [comment]
Ok, then I don't explain why it does **NOT** exit on "low speed" on my suspended curl command line!

(I used the command line to avoid having to do a test callback to test that!)

**Comment by bagder** [comment]
I suspect it doesn't trigger. Like this: you sleep for 60 seconds and then of course the transfer is below one byte per second, but then you do 'fg' and the transfer continues. The low-speed check then *first* checks if it is still below the speed and then if it has been below for the given time.

In your case, when you fg  the process it is likely to be able to transfer a byte before the check is done again and then it sees that you're not below for this second and the timer is reset...

**Comment by Bylon2** [comment]
So there is "another timer" not documented, since indeed the transfer has been under 1b/s for more than 30sec in my command line example?

Let me write a quick callback to check this route too.

**Comment by Bylon2** [comment]
So here is exhibit 2:

Content of **download.c**
```
#include <stdio.h>
#include <string.h>
#include <curl/curl.h>
#include <unistd.h>

static size_t dump_head( const char *ptr, const size_t size,
			 const size_t nmemb, void *userdata)
{
	size_t chunk = size * nmemb;

	printf("%.*s", (int)chunk, ptr);
	return chunk;
}

off_t off = 0;

static size_t slow_down( const char *ptr, const size_t size,
			 const size_t nmemb, void *userdata)
{
	size_t chunk = size * nmemb;

	printf("Got %ld bytes at offset %ld\n", chunk, off);
	off += chunk;

	sleep(15);
	
	return chunk;
}
			       
int main(int argc, char *argv[]) {
	CURL *curl;
	CURLcode res;
	long http_code;

	if (argc < 2) {
		printf("Usage: %s URL_to_download\n", argv[0]);
		return 1;
	}

	if (CURLE_OK != curl_global_init(CURL_GLOBAL_ALL)) {
		printf("Error initialising curl.\n");
		return 1;
	}

	
	curl = curl_easy_init();
	if (NULL == curl) {
		printf("Error initialising curl handle.\n");
		return 1;
	}

	res = curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_TCP_KEEPIDLE, 30L);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_TCP_KEEPINTVL, 30L);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, dump_head);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, slow_down);


	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_LOW_SPEED_LIMIT, 1L);
	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_LOW_SPEED_TIME, 10L);


	if (CURLE_OK == res)
		res = curl_easy_setopt(curl, CURLOPT_URL, argv[1]);

	if (CURLE_OK != res) {
		printf("Some curl options could not be set.\n");
		return 1;
	}


	printf("Slowly downloading: %s\n", argv[1]);
	res = curl_easy_perform(curl);
	if (0 == res)
		res = curl_easy_getinfo(curl,
					CURLINFO_RESPONSE_CODE,
					&http_code);
	printf("\ncurl_easy_perform exited with: %d, http_code: %ld.\n",
		res, http_code);
	curl_easy_cleanup(curl);
	curl_global_cleanup();
	return 0;
}
```

Compile with:
`cc -Wall download.c $(pkg-config fuse --cflags --libs) $(curl-config --cflags --libs) -o download -g`

Run:
```
$ ./download https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html
Slowly downloading: https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 5063
Server: Apache
X-Frame-Options: SAMEORIGIN
Last-Modified: Tue, 21 Jan 2020 14:07:10 GMT
ETag: "13c7-59ca6ec82766b"
Cache-Control: max-age=60
Expires: Sun, 22 Mar 2020 09:11:26 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' www.fastly-insights.com; style-src 'unsafe-inline' 'self'
Strict-Transport-Security: max-age=31536000; includeSubDomains;
Content-Type: text/html
Via: 1.1 varnish
Accept-Ranges: bytes
Date: Sun, 22 Mar 2020 09:10:27 GMT
Via: 1.1 varnish
Age: 0
X-Served-By: cache-bma1629-BMA, cache-cdg20759-CDG
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1584868227.211772,VS0,VE72
Vary: Accept-Encoding

Got 1371 bytes at offset 0
Got 1371 bytes at offset 1371
Got 1371 bytes at offset 2742
Got 950 bytes at offset 4113

curl_easy_perform exited with: 0, http_code: 200.

```

As you can see we have instructed to allow consider "low_sped": 1byte/sec for 10 sec.

On purpose, the callback is waiting for 15 seconds, which means during these 15 secs there is no transfer at all and we are beneath the threshold.

Transfer goes as expected and curl_easy_perform exits with 0.

How do we explain that with the current documentation?

**Comment by bagder** [comment]
It doesn't exclude the callbacks (it would be really hard and complicated to do that), but again - when you return to libcurl from the callback, libcurl probably reads a few/many bytes of data before it checks the low-speed threshold and voila, you're above the limit again.

If we would move the check to happen immediately after the callback return, then you'd get your low speed trigger to happen for this case. I'm not sure why that would be preferable though.

**Comment by Bylon2** [comment]
So you explain it checks the speed before and after the callbacks. That make sense, but isn't is a synonym of "excluding callbacks" (or I am not explaining myself correctly)!

Anyway it's probably me not understanding correctly the documentation... but I'm glad I can instruct curl to consider "low_speed" 0 byte / 30 sec, and wait in the callback for how much time the server supports without closing the socket!

**Comment by bagder** [comment]
> isn't is a synonym of "excluding callbacks"

Is it? I think that for many (most?) cases and applications, the time spent in callbacks isn't at all affecting the network speed since the limiting factor to network speed is rarely the CPU. So, even if you speed time in callbacks every now and then, the rest of the CPU time is more than enough to drain the buffers and maintain network speed.

However, if you actually get data very slowly from a remote server, you want the low-speed check to detect that properly even if your callback at one point takes a little extra time. And I believe it does.

So what exactly do you think we don't have documented for this feature that we should add? I think I've lost track a little here...

**Comment by Bylon2** [comment]
The time spent in callback is inevitable when you write a fuse driver using fuse, because it depends on client program that ask for read/write, and you cannot know when the next piece of data is going to be queried. It can be immediately or10 minutes later!

I start to understand what you explain, it is quite obvious now that curl can measure only when in the library and not when in callbacks (since the "library" is not running there!).

But what is confusing is the algorithm used here.

With the above program I tried different combinations:
33 bytes/sec for 5 seconds ==> no error
99 bytes/sec for 15 seconds ==> gives the error 28.

Since in both case we have waited 15 seconds, if the library compute an "average" of speed transfer including time taken by the callbacks, shouldn't it give the same results for 33/5 and 99/15?

I am now being confused myself with the possible use of these options!

**Comment by Bylon2** [comment]
So maybe to make is a clean question for the documentation:

- When callback are "quick" and definitely way smaller than CURLOPT_LOW_SPEED_TIME, all is very clear (no need changing anything in the code or documentation)

- But when the callback take more than CURLOPT_LOW_SPEED_TIME, we are puzzled about how the limit applies -since obviously no transfer at all happened when in the callback-, and an indication of that in the documentation could be welcome.

**Comment by bagder** [comment]
> when the callback takes more than CURLOPT_LOW_SPEED_TIME, we are puzzled about how the limit applies -since obviously no transfer at all happened when in the callback

1. If your callback is that slow, then why don't you return an error yourself then if you know you're below the threshold?
2. Most systems have their TCP stack in the kernel and it may very well have received data while inside the callback, so as soon as the callback returns libcurl drains the kernel buffer and voila, lots of data arrives immediately and the average transfer speed of the last N seconds is now non-zero...

**Comment by Bylon2** [comment]
Ok, I got it reversed in my example.

So, in case the time spent is higher than CURLOPT_LOW_SPEED_TIME the functional rule is:

```
if (bytes_received < CURLOPT_LOW_SPEED_SPEED * (time_spent_between_measures / CURLOPT_LOW_SPEED_TIME)) {
        return CURLE_OPERATION_TIMEDOUT;
}

```
time_spent_between_measures is done in the library (can only be done there!) and thus includes time spend in the callbacks.

The functional rule is different when time spent by callback is much lower because the computation will wait at least the amount of time specified in CURLOPT_LOW_SPEED_TIME before return the error.

As for myself I have understood perfectly how it works now.

I let you decide if it is worth giving a little bit more explanation or not in the documentation (tricky subject with "long" callbacks), and close this ticket with or without documentation change!

**Comment by Bylon2** [comment]
Sorry to bother again... but coming back to the issue I try to fix, which is in fact **"upload"**, I am not quite sure I understand those parameters in that case.

In the case of "upload" it is the callback that feed data to libcurl, so as long as the callback does not return, there is no "upload speed"!

In that case, wouldn't it make sense to measure "time in the library only"?

Indeed what I was trying to protect from is the library not calling ever again my upload-callbacks because it is stuck trying to FTP-STOR some buffer. Maybe those options are the wrong tools for that job?

**Comment by Bylon2** [comment]
> I think that for many (most?) cases and applications, the time spent in callbacks isn't at all affecting the network speed since the limiting factor to network speed is rarely the CPU.

But we have to assume a callback is not only "doing CPU", but for example writing some data on a disk. As a matter of fact, I have a fibre landline at 1Gbps of which on some servers I can use the full bandwidth, but if the callback would try to write the data on, let's say, a USB 2 drive, the limiting factor is not CPU nor network, but the USB 2 writing... which happens to be in the callback!

So yes, measuring the "network speed" without the effect of callbacks could be useful, but I understood well that is not what these options do!

If the use case were to check the USB2 writing does not starve from network not quick enough, with this options we would have to factor also the write speed in the callback, which probably means changing those two parameters from within the callback itself... it that would work!

**Comment by jay** [comment]
IMO in this case you are trying to anticipate undocumented behavior. We can't (or shouldn't) imply that we'll guarantee this. I'm not trying to discourage this discussion from continuing it just appears academic to me. I suggest you implement your own timeout logic for this edge case via the progress function.

**Comment by Bylon2** [comment]
You are right, what lead me into error is the word **"transfer"** that I mistook for "network", when in fact it's the overall speed.

It might be because I am not English native and could be clear for anyone else.

And indeed the thing I am trying to do: network speed, rather points to the progress function.

Closing it now then.
