### ISSUE TITLE
LoadLibrary() blocks network

### ISSUE THREAD

**Issue by Leadwerks** [curl/curl#5134]
I am using LibCurl inside of a plugin for our software. The plugin is compiled to a Windows DLL and loaded by the main application with LoadLibrary(). I have determined that the plugin code works fine when compiled as an EXE, but it always fail to resolve the host name when using it as a DLL and times out.

I tried passing the full path to LoadLibrary, with the assumption it was blocking the network to prevent DLL hijacking attacks, but it made no difference.

Has anyone else encountered something like this? How do you get around the problem?

**Comment by jay** [comment]
I've never heard of anything like this. How did you build the libcurl dll and what is the curl_version()? Try enabling [CURLOPT_VERBOSE](https://curl.haxx.se/libcurl/c/CURLOPT_VERBOSE.html) to help debug it.

/cc @captain-caveman2k

**Comment by bagder** [comment]
It's very hard to see how this is a curl issue. It's not up to curl to control how it runs in the operating system.

**Comment by jay** [comment]
Possibly the reporter is using an overly sensitive anti-virus.

**Comment by bagder** [comment]
@Leadwerks, we will close this issue soon unless we get more data or info to act on. Right now we can't do anything.

**Comment by bagder** [comment]
Suspected anti-virus issue, not a curl bug. No response to follow-up questions after 18 days. Closing.

**Comment by Leadwerks** [comment]
No anti-virus is in use but I do suspect some type of protection in Windows is being activated.
