### ISSUE TITLE
curl: redirect 302: Not changing the method from POST to GET

### ISSUE THREAD

**Issue by sant527** [curl/curl#5145]
```
$ curl --version
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.1 nghttp2/1.36.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

I have a `url(/add_item)` to which i send data using a `POST` method. After finishing the task it will redirect to `url2 (/show_items)`

I using the curl command (POST method and also --location is used to auto redirect). The following is the command

    $ curl --verbose --location --request POST 'http://127.0.0.1:8000/add_item' \
    --header 'Content-Type: application/json' \
    --data-raw '{
    "item" : "new"
    }'

The output

    Note: Unnecessary use of -X or --request, POST is already inferred.
    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
    > POST /add_item HTTP/1.1
    > Host: 127.0.0.1:8000
    > User-Agent: curl/7.64.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 18
    > 
    * upload completely sent off: 18 out of 18 bytes
    < HTTP/1.1 302 Found
    < Date: Wed, 25 Mar 2020 08:02:37 GMT
    < Server: WSGIServer/0.2 CPython/3.7.3
    < Content-Type: text/html; charset=utf-8
    < Location: /show_items
    < Content-Length: 0
    < X-Content-Type-Options: nosniff
    < 
    * Connection #0 to host 127.0.0.1 left intact
    * Issue another request to this URL: 'http://127.0.0.1:8000/show_items'
    * Switch from POST to GET
    * Found bundle for host 127.0.0.1: 0x56410d38f180 [can pipeline]
    * Could pipeline, but not asked to!
    * Re-using existing connection! (#0) with host 127.0.0.1
    * Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
    > POST /show_items HTTP/1.1
    > Host: 127.0.0.1:8000
    > User-Agent: curl/7.64.1
    > Accept: */*
    > Content-Type: application/json
    > 
    < HTTP/1.1 500 Internal Server Error
    < Date: Wed, 25 Mar 2020 08:02:37 GMT
    < Server: WSGIServer/0.2 CPython/3.7.3
    < Content-Type: text/html
    < Content-Length: 99523
    < Vary: Cookie
    < X-Content-Type-Options: nosniff
    < 
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <body>
    ....
    </body>
    </head>
    </html>

Here I notice that 

    * Re-using existing connection! (#0) with host 127.0.0.1
    * Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
    > POST /show_items HTTP/1.1

Since its `< HTTP/1.1 302 Found` curl should use GET method instead of POST. But its using POST. How to stop this behaviour. 

It looks its trying to use GET

    * Issue another request to this URL: 'http://127.0.0.1:8000/show_items'
    * Switch from POST to GET

But later changes back to POST

How to ensure it uses GET

**Comment by jzakrzewski** [comment]
It's because you've used "--request", telling curl to only use POST. "--data-raw" should be enough to trigger POST request without that undesired effect.

**Comment by dfandrich** [comment]
On Wed, Mar 25, 2020 at 08:11:13AM -0700, Santhosh Kumar wrote:
> Note: Unnecessary use of -X or --request, POST is already inferred.

Heed this warning. It's likely the answer to your question.

**Comment by sant527** [comment]
I god this code from postman and just copy pasted it. Thank you very very much. Now i am using the following

Now both of the following as per your responses work:

remove `--request` ( but this takes more time i dont know why)
```
$ curl --verbose --location POST 'http://127.0.0.1:8000/login_register_password/api/user_login_via_otp_form_otp' \
--header 'Content-Type: application/json' \
--data-raw '{
"item" : "new"
}'
```

remove `--request POST` also since --data-raw is good enough (this is faster than the above.)
```
$ curl --verbose --location 'http://127.0.0.1:8000/login_register_password/api/user_login_via_otp_form_otp' \     
--header 'Content-Type: application/json' \
--data-raw '{
"item" : "new"
}'
```

**Comment by jzakrzewski** [comment]
"POST" is an argument to "--request" so when you only removed "--request" it tried to actually issue a request to "http://POST" - this is why you've observed a time increase.

As to "I got the curl code (with --request POST) from postman and just copy pasted.": There are a lot of tools that generate code like that. Postman and Swagger being at the top of my "naughty list". Then people replicate this, write blog posts... Probably at least half of the examples you can find on the Internet has this kind of mistake.

**Comment by bagder** [comment]
I made a slide for a curl presentation once on this topic! :grin: 

![slide-avoid-X-v2](https://user-images.githubusercontent.com/177011/77588598-773b5080-6eea-11ea-857e-048a6dc1c89c.jpg)

**Comment by bagder** [comment]
That was fun. This is not a curl bug. Closing.
