### ISSUE TITLE
OSX Keychain access causing segfaults

### ISSUE THREAD

**Issue by mikesiegel** [curl/curl#5154]
### I did this
/usr/local/opt/curl/bin/curl -E $CERTINKEYSTORE  https://example.com

### I expected the following
curl to attempt client certificate auth with example.com

### curl/libcurl version

curl 7.68.0 (x86_64-apple-darwin18.7.0) libcurl/7.68.0 SecureTransport zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli IDN IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

### operating system

OSX Mojave 10.14.6

### details
```
2020-03-27 09:23:07.291 curl[920:1513461] -[__NSArrayM length]: unrecognized selector sent to instance 0x7fed0fc107b0
2020-03-27 09:23:07.297 curl[920:1513461] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x7fed0fc107b0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4626ea7d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff70940a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff462e8886 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff462108ef ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff46210298 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff461c99da CFStringCompare + 24
	6   libcurl.4.dylib                     0x00000001079b1a76 sectransp_connect_common + 2844
	7   libcurl.4.dylib                     0x00000001079afa71 Curl_ssl_connect_nonblocking + 105
	8   libcurl.4.dylib                     0x0000000107973eab https_connecting + 23
	9   libcurl.4.dylib                     0x0000000107973e5a Curl_http_connect + 365
	10  libcurl.4.dylib                     0x000000010798fe82 multi_runsingle + 3779
	11  libcurl.4.dylib                     0x000000010798ef46 curl_multi_perform + 112
	12  libcurl.4.dylib                     0x00000001079897a6 curl_easy_perform + 287
	13  curl                                0x0000000107940b94 operate + 1196
	14  curl                                0x0000000107940260 main + 346
	15  libdyld.dylib                       0x00007fff7210e3d5 start + 1
	16  ???                                 0x0000000000000004 0x0 + 4
)
```
also sometimes I receive this.
```
2020-03-27 09:22:42.585 curl[882:1511708] *** NSForwarding: warning: object 0x7fe5cc527290 of class 'nil' does not implement doesNotRecognizeSelector: -- abort
[1]    882 illegal hardware instruction  /usr/local/opt/curl/bin/curl -E certymctestpants https://example.com
```

### troubleshooting

Had multiple coworkers try it, same results. Rebuilt from source, same results. Also seems to affect libcurl applications attempting to use keychain cert auth, like git.

**Comment by bagder** [comment]
Can you rebuild libcurl with debug symbols present so we can see details from that stack frame number 6?

**Comment by nickzman** [comment]
I cannot reproduce the problem with the latest code in the master branch, even if I use a self-signed identity in the keychain called "certymctestpants" as in the description. Does it work for you if you build from the master branch?

**Comment by mikesiegel** [comment]
we were able to resolve this by doing
`security execute-with-privilege /usr/local/opt/curl/bin/curl -E certymctestpants https://example.com`

So believe it's a result of some sort of hardening config we have. I'll see if I can sort it out next week w/ a debug version.

**Comment by bagder** [comment]
Any update?

**Comment by mikesiegel** [comment]
Can go ahead and close. homebrew apparently has issues creating debug symbols and the work around is the security command above.
