### ISSUE TITLE
Using unix sockets on Windows with `--unix-socket`

### ISSUE THREAD

**Issue by francislavoie** [curl/curl#5162]
I've recently found out that Windows 10 supports unix sockets https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

I expected `curl` on Windows to support this as well, but it seems like it doesn't recognize the `--unix-socket` option.

Context: I'm trying to verify the viability of unix sockets for the admin API endpoint on Windows for https://caddyserver.com, which would likely give better control than listening on port `2019` which is currently the default.

### I did this

I tried both the `curl` bundled in windows and a build from [`scoop`](https://scoop.sh/). Both gave the same result.

```
$ which curl
C:\Windows\system32\curl.EXE

$ curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

$ curl --unix-socket .\caddy.sock http://localhost/config
curl: (48) An unknown option was passed in to libcurl


$ scoop install curl
WARN  'curl' (7.69.1) is already installed.
Use 'scoop update curl' to install a new version.

$ ~\scoop\apps\curl\current\bin\curl.exe --version
curl 7.69.1 (x86_64-pc-win32) libcurl/7.69.1 OpenSSL/1.1.1d (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP brotli libz

$ ~\scoop\apps\curl\current\bin\curl.exe --unix-socket .\caddy.sock http://localhost/config
curl: (48) An unknown option was passed in to libcurl
```

### operating system

```
$ (Get-WmiObject Win32_OperatingSystem).Version
10.0.19041
```

**Comment by bagder** [comment]
The configure script tries to detect if unix domain sockets work and enables it in the build if so.

I presume you either didn't build with configure or that the configure script needs improvement.
I guess we need support for this in the more windows-centric build methods?

**Comment by francislavoie** [comment]
Okay thanks - that's right I didn't build myself, I just used the one that ships with Windows 10 Insider Preview, and the build from scoop, i.e. from https://github.com/ScoopInstaller/Main/blob/master/bucket/curl.json, which seems to just grab from `https://curl.haxx.se/windows/dl-$version/curl-$version-win64-mingw.tar.xz`

**Comment by bagder** [comment]
Someone on Windows needs to dive in and see what needs to be done to make it work in the build.

**Comment by gvanem** [comment]
Don't know about the build, but `AF_UNIX` on Win-10 gets enabled here:
[`config-win32.h`](https://github.com/curl/curl/blob/master/lib/config-win32.h#L721).

So a `curl  --unix-socket ` or `curl  --abstract-unix-socket ` seems to work fine.

**Comment by bagder** [comment]
thanks @gvanem, then I presume the reason our official windows builds don't support that is simply because curl-for-windows runs configure and isn't using `config-win32.h`. @vszakats, can you confirm? I tried to find the curl configure output for the latest cfw build but I failed...

**Comment by vszakats** [comment]
`curl-for-win` uses `Makefile.m32` to build, not `Configure`, but `config-win32.h` is used by either, so this isn't the issue.

The first problem is that the logic to enable `USE_UNIX_SOCKETS` is MSVC-specific: `defined(_MSC_VER) && (_MSC_VER >= 1500)`. While `curl-for-win` uses MinGW.

This could be fixed by also allowing `defined(__MINGW32__)`, though the next problem will be older/alternate MinGW versions/distros which do not ship with `sdkddkver.h`. This could fixed by adding a `HAVE_SDKDDKVER.H` and having this set either via `Configure`, by MSVC build paths, or manually (in the case of `curl-for-win`).

As far as I can see the latest MinGW release available on macOS _does_ have this header and the necessary values defined, so it _should_ work, or at least _build_ with this option.

**Comment by vszakats** [comment]
Okay, so this happens when this option is enabled with MinGW:
```
clang -I. -I../include -I"../../nghttp2/pkg/usr/local/include" -I"../../zlib/pkg/usr/local" -target x86_64-w64-mingw32 --sysroot /usr/local/opt/mingw-w64/toolchain-x86_64 -DCURL_STATICLIB -fno-ident -DNGHTTP2_STATICLIB -g -O2 -Wall -W -fno-strict-aliasing -m64 -D_AMD64_ -DBUILDING_LIBCURL -DUSE_NGHTTP2 -DUSE_SCHANNEL -DHAVE_LIBZ -DHAVE_ZLIB_H -DUSE_WIN32_IDN -DWANT_IDN_PROTOTYPES -DUSE_WINDOWS_SSPI -DENABLE_IPV6 -D_WIN32_WINNT=0x0501 -DHAVE_LDAP_SSL -c socks_gssapi.c -o socks_gssapi.o
curl_addrinfo.c:54:10: fatal error: 'afunix.h' file not found
#include <afunix.h>
         ^~~~~~~~~~
1 error generated.
```

It means the support for this is not fully supported by MinGW (or `mingw-w64`, `mingw-w64-crt`, `mingw-w64-headers`) yet.

It could still be useful to introduce `HAVE_SDKDDKVER_H` so that it can be enabled once supported by the toolchain.

**Comment by vszakats** [comment]
Having said all that, this patch should enable Unixsockets on supported systems (`HAVE_SDKDDKVER_H` should be manually enabled for non-MSVC toolchains):
```patch
diff --git a/lib/config-win32.h b/lib/config-win32.h
index d19665d71..a620c4dc2 100644
--- a/lib/config-win32.h
+++ b/lib/config-win32.h
@@ -720,11 +720,26 @@ Vista
 
 /* Define to use Unix sockets. */
 #if defined(_MSC_VER) && (_MSC_VER >= 1500)
+#define HAVE_SDKDDKVER_H
+#define HAVE_AFUNIX_H
+#endif
+
+#if defined(HAVE_SDKDDKVER_H)
 /* sdkddkver.h first shipped with Platform SDK v6.0A included with VS2008 */
 #include <sdkddkver.h>
 #if defined(NTDDI_WIN10_RS4)
 #define USE_UNIX_SOCKETS
 #endif
+#if defined(USE_UNIX_SOCKETS) && !defined(HAVE_AFUNIX_H)
+# if !defined(UNIX_PATH_MAX)
+# define UNIX_PATH_MAX 108
+# endif
+# include <ws2tcpip.h>
+  typedef struct sockaddr_un {
+    ADDRESS_FAMILY sun_family;
+    char sun_path[UNIX_PATH_MAX];
+  } SOCKADDR_UN, *PSOCKADDR_UN;
+#endif
 #endif
 
 /* ---------------------------------------------------------------- */
diff --git a/lib/curl_addrinfo.c b/lib/curl_addrinfo.c
index 16c4779c1..d769336fd 100644
--- a/lib/curl_addrinfo.c
+++ b/lib/curl_addrinfo.c
@@ -5,7 +5,7 @@
  *                            | (__| |_| |  _ <| |___
  *                             \___|\___/|_| \_\_____|
  *
- * Copyright (C) 1998 - 2019, Daniel Stenberg, <daniel@haxx.se>, et al.
+ * Copyright (C) 1998 - 2020, Daniel Stenberg, <daniel@haxx.se>, et al.
  *
  * This software is licensed as described in the file COPYING, which
  * you should have received as part of this distribution. The terms
@@ -50,7 +50,7 @@
 #  define in_addr_t unsigned long
 #endif
 
-#if defined(WIN32) && defined(USE_UNIX_SOCKETS)
+#if defined(WIN32) && defined(USE_UNIX_SOCKETS) && defined(HAVE_AFUNIX_H)
 #include <afunix.h>
 #endif
 ```

**Comment by vszakats** [comment]
Please correct me if I'm missing something, but this can be simplified to the following, and be enabled on _all_ Windows builds by default (it will still need a compatible Windows environment to actually be usable at runtime):
```patch
diff --git a/lib/config-win32.h b/lib/config-win32.h
index d19665d71..da9077f98 100644
--- a/lib/config-win32.h
+++ b/lib/config-win32.h
@@ -719,12 +719,14 @@ Vista
 #endif
 
 /* Define to use Unix sockets. */
-#if defined(_MSC_VER) && (_MSC_VER >= 1500)
-/* sdkddkver.h first shipped with Platform SDK v6.0A included with VS2008 */
-#include <sdkddkver.h>
-#if defined(NTDDI_WIN10_RS4)
 #define USE_UNIX_SOCKETS
-#endif
+#if !defined(UNIX_PATH_MAX)
+# define UNIX_PATH_MAX 108
+# include <ws2tcpip.h>
+  typedef struct sockaddr_un {
+    ADDRESS_FAMILY sun_family;
+    char sun_path[UNIX_PATH_MAX];
+  } SOCKADDR_UN, *PSOCKADDR_UN;
 #endif
 
 /* ---------------------------------------------------------------- */
diff --git a/lib/curl_addrinfo.c b/lib/curl_addrinfo.c
index 16c4779c1..6fd496d04 100644
--- a/lib/curl_addrinfo.c
+++ b/lib/curl_addrinfo.c
@@ -5,7 +5,7 @@
  *                            | (__| |_| |  _ <| |___
  *                             \___|\___/|_| \_\_____|
  *
- * Copyright (C) 1998 - 2019, Daniel Stenberg, <daniel@haxx.se>, et al.
+ * Copyright (C) 1998 - 2020, Daniel Stenberg, <daniel@haxx.se>, et al.
  *
  * This software is licensed as described in the file COPYING, which
  * you should have received as part of this distribution. The terms
@@ -50,7 +50,7 @@
 #  define in_addr_t unsigned long
 #endif
 
-#if defined(WIN32) && defined(USE_UNIX_SOCKETS)
+#if defined(USE_UNIX_SOCKETS) && !defined(WIN32)
 #include <afunix.h>
 #endif
```

**Comment by bagder** [comment]
@vszakats I propose you turn this into a proper PR and we can see how it works and take further discussions on the implementation details there.

**Comment by vszakats** [comment]
Opened https://github.com/curl/curl/pull/5170, with the latest version of the patch from this thread.

If everyone agrees, we can close this and continue there.

**Comment by francislavoie** [comment]
Thanks @vszakats!

Is there a build artifact I can grab to try this?

**Comment by vszakats** [comment]
@francislavoie Here's a local build (64-bit) you can try: [curl-dev-win64-mingw.zip](https://github.com/curl/curl/files/4432321/curl-dev-win64-mingw.zip)

**Comment by francislavoie** [comment]
Interesting, I no longer get a complaint about `--unix-socket` being an unknown option, but I get a different error and hanging instead. Probably not a problem with curl.

```
$ .\curl\bin\curl.exe -vvv --unix-socket .\caddy.sock http://localhost/config
* sa_addr inet_ntop() failed with errno 10047: Address family not supported
```

**Comment by vszakats** [comment]
FWIW, here the output with wine 4.0.2:
```console
$ wine64 curl.exe -vvv --unix-socket ./example.sock https://example.net/
[...]
0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv6 not supported in this platform
0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
0009:fixme:winsock:convert_af_w2u unhandled Windows address family 1
* Closing connection 0
curl: (7) Couldn't connect to server
```
I'm not familiar with Unix socket support on Windows, and have sufficiently updated Windows 10 system around. It would be interesting to compare current behavior with a stable, MSVC curl build with Unixsockets support enabled. That would show if anything may have degraded.

**Comment by francislavoie** [comment]
I think that a Windows 10 Insider build needs to be used for this, version 17063 or greater, I believe, as per https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
