### ISSUE TITLE
cacertinmem.c example

### ISSUE THREAD

**Issue by TomMettam** [curl/curl#5163]
I used the example exactly as provided.

It works fine on Windows. I expected the same behaviour on OSX, but the provided ssl context appears to be invalid (SSL_CTX_get_cert_store returns 0x01, which is undefined behaviour).

### curl/libcurl version

curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

### operating system

macOS Catalina 10.15.2 (19C57)

**Comment by bagder** [comment]
That sounds like a libressl issue. How did you build curl to use libressl like this?

**Comment by bagder** [comment]
I built with OpenSSL 1.1.1d on mac (from homebrew) and it did not reproduce.

**Comment by TomMettam** [comment]
Right on, I didn't notice the libressl output there. I think the issue is that it's pulling in the system curl rather than the project version which is compiled with OpenSSL. Sorry for the bother
