### ISSUE TITLE
curl_easy_setopt(curl, CURLOPT_SSLENGINE, "tpm2tss") returning error code on raspberry Pi

### ISSUE THREAD

**Issue by rlillback** [curl/curl#5172]
### I did this
1.) built tpm2tss-engine 
2.) verified openssl commands work with -engine tpm2tss switch
3.) built curl and installed libraries:
```
$ ./buildconf
$ ./configure
$ make -j$(nproc)
$ sudo make install
```
4.)Verified this engine is recognized by the curl build:
```
$ curl --engine list
Build-time engines:
  dynamic
  tpm2tss
```
5.) Created a program with the following program line:
```
int err = curl_easy_setopt(curl, CURLOPT_SSLENGINE, "tpm2tss");
```
6.) Compile and run program, and get:
```
err = CURLE_NOT_BUILT_IN 
```
### I expected the following
```
err = CURLE_OK
```
### curl/libcurl version
```
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
### operating system
```
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

**Comment by bagder** [comment]
I can't even see how that code flow can ever return `CURLE_NOT_BUILT_IN`... Can you set a break-point in libcurl and figure out what happens?

**Comment by rlillback** [comment]
badger, I tried this after re-configuring and building with the --enable-debug switch on:
```
./configure --enable-debug
make clean
make -j4
sudo make uninstall
sudo make install
```
Then, when I run gdb with a breakpoint of Curl_vsetopt, I don't hit a break point in the library.
If I set a breakpoint of curl_easy_setopt, and single step into the library, I get this data:
```
0x76f8e6f8 in curl_easy_setopt () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8e6fc in curl_easy_setopt () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8e700 in curl_easy_setopt () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba5c in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba60 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba64 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba68 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba6c in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba70 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb) s
0x76f8ba74 in ?? () from /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
(gdb)
```
Therefore it appears debugging information is not generated.
So, I am at a loss as to what to try next.

Here is my code fragment that catches the error:
```
    curl_easy_setopt(curl, CURLOPT_URL, url);
    curl_easy_setopt(curl, CURLOPT_POST, 1L);
    curl_easy_setopt(curl, CURLOPT_USERNAME, username);
    curl_easy_setopt(curl, CURLOPT_PASSWORD, password);
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, CONNECTION_TIMEOUT);
   
    log_verbose("%s%s-Setting cURL to use TPM as SSL Engine %s",
                  MODULE,FUNCTION, engine_id);
    int errNum = curl_easy_setopt(curl, CURLOPT_SSLENGINE, engine_id);
    if ( CURLE_OK != errNum )
    {
      /* When tracing, dump the error buffer to stderr */
			if ( is_log_trace() )
			{
				size_t len = strlen( errBuff );
				log_trace( "%s%s-libcurl: (%d) ", MODULE, FUNCTION, errNum );
				if ( len )
				{
					log_trace( "%s%s-%s%s", MODULE, FUNCTION,
									errBuff, ((errBuff[len-1] != '\n') ? "\n" : ""));

				}
				else
				{
					log_trace("%s%s-%s\n", MODULE, FUNCTION, curl_easy_strerror(errNum) );
				}
			}
			log_error("%s%shttp-WriteMemoryCallback-%s", MODULE, FUNCTION,
                                        curl_easy_strerror(errNum));

  		curl_easy_cleanup(curl);
      return errNum;
    }
```
Here is the output from that segment of code with tracing on:
```
[2020-04-01 16:34:06] - [VERBOSE] - httpclient-http_post_json--Setting cURL to use TPM as SSL Engine tpm2tss
[2020-04-01 16:34:06] - [TRACE]   - httpclient-http_post_json--libcurl: (4)
[2020-04-01 16:34:06] - [TRACE]   - httpclient-http_post_json--A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.

[2020-04-01 16:34:06] - [ERROR]   - httpclient-http_post_json-http-WriteMemoryCallback-A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
[2020-04-01 16:34:06] - [VERBOSE] - session-register_session-Session Response:
[2020-04-01 16:34:06] - [VERBOSE] - (null)
[2020-04-01 16:34:06] - [ERROR]   - session-register_session-Session registration failed with error code 4
```
Any assistance is appreciated!!

**Comment by rlillback** [comment]
Also, here is the output of the ```./configure --enable-debug``` command.  the -g option is enabled.
![image](https://user-images.githubusercontent.com/7303751/78163906-fbc02e80-7416-11ea-8f58-c82650625b9a.png)

**Comment by rlillback** [comment]
@bagder , I have found what my initial mistake was.  The command ```sudo make install``` does not overwrite the curl library used by the Raspberry Pi.  The Pi uses ```/usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4```.  I needed to override the library location to where I built the library.  Now the tpm engine gets called.  However, I have another issue -- how to set the keytype to engine instead of PEM.  
.
I am using a TPM so, the keyfile is encoded & must be decoded by the engine.
.
Typically, an openssl command uses the following switches (e.g.:
```openssl req -new -engine tpm2tss -keyform engine -key /home/pi/certs/client.key -out /home/pi/certs/client.csr```

Should I enter this as another bug or is it a lack of understanding on my part?

**Comment by bagder** [comment]
> Now the tpm engine gets called

Then this issue should be closed, right? As it wasn't an actual issue...

> Should I enter this as another bug or is it a lack of understanding on my part?

Since it isn't this (#5172) issue you should not just continue here when talking about different, correct.

I similarly can't see in the code how you can get that issue, but sure file an issue and describe it.

**Comment by bagder** [comment]
This issue was a user mistake.

**Comment by rlillback** [comment]
Thanks @badger
