### ISSUE TITLE
Unable to curl using a proxy to an onion v3 address.

### ISSUE THREAD

**Issue by codeoholic** [curl/curl#5195]
### I did this
**Case A**: curl -I --proxy socks5h://localhost:9050 http://blockchairt5d4pj.onion/

> Notice the Onion v2 address.

**Case B**: curl -I --proxy socks5h://localhost:9050 http://blkchairbknpn73cfjhevhla7rkp4ed5gg2knctvv7it4lioy22defid.onion/

> Notice the Onion v3 address.

### I expected the following
**Case A**: Works well and returns the header.
**Output A**:
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Tue, 07 Apr 2020 13:39:45 GMT
Connection: keep-alive
X-Auth: 429
Server-Timing: total;dur=1;desc="Nuxt Server Time"

**Case B**: Throws an error.
**Output B**:
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (1)

### curl/libcurl version

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

### operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

**Comment by bagder** [comment]
curl 7.35.0 is over six years old. We've improved the SOCKS code several times since back then. If you can reproduce this with a recent version I'll be happy do dig deeper but until then I think I'll hold off.

**Comment by codeoholic** [comment]
Thank you @bagder for pointing it. I no longer see this error on onion address v3 while using curl 7.58.0. It was surely an older installation which caused this on my server.
