### ISSUE TITLE
curl --compressed returns error code 23: Failed writing received data to disk/application

### ISSUE THREAD

**Issue by JCMais** [curl/curl#5200]
### I did this  
```
curl --insecure --compressed https://www.ponyexpress.ru/support/servisy-samoobsluzhivaniya/track/
```

### I expected the following  
It works

### curl/libcurl version  
7.64.1
Version: libcurl/7.64.1 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.39.2
Protocols: dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Features: AsynchDNS, IDN, IPv6, Largefile, NTLM, NTLM_WB, SSL, libz, brotli, TLS-SRP, HTTP2, UnixSockets, HTTPS-proxy

---

7.69.1
Version: libcurl/7.69.1-DEV OpenSSL/1.1.1d zlib/1.2.11 WinIDN libssh2/1.9.0_DEV nghttp2/1.40.0
Protocols: dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Features: AsynchDNS, IDN, IPv6, Largefile, SSPI, Kerberos, SPNEGO, NTLM, SSL, libz, HTTP2, HTTPS-proxy

### operating system  
Ubuntu Linux (Linux JCM 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux)
Windows 10

This was initially reported on the [`node-libcurl`](https://github.com/JCMais/node-libcurl) binding issue tracker: https://github.com/JCMais/node-libcurl/issues/193

It's probably related to https://github.com/curl/curl/issues/4092 and https://github.com/curl/curl/issues/3796

**Comment by bagder** [comment]
This is indeed the same story as before: the server sends a broken data stream and curl is pretty strict and thus return this error. The patch in #3825 will hide this error, but @monnerat and @jay weren't very keen in landing it back then and I think I agree with them. This *is* a broken server response and curl intentionally report this as an error. This is not a curl bug.

What can be discussed of course still is if a future curl should silently ignore the error the way #3825 suggested. I know that the worst possible answer in my mind is "add an option for it"...

**Comment by JCMais** [comment]
> server sends a broken data stream and curl is pretty strict and thus return this error

I suspected this was the case, thanks for confirming @bagder .

Feel free to close this issue if it's not needed to discuss the matter, in my opinion, if it's not a bug there is no need to include an option to work around some broken server response.

**Comment by bagder** [comment]
Closing. This is a bad server and curl is correctly pointing it out.
