### ISSUE TITLE
Remote recursive folder creation through SFTP protocol

### ISSUE THREAD

**Issue by zhanghlstudy** [curl/curl#5204]
I want to use the SFTP protocol to create folders on the remote SFTP server, without specifying the curl option. The option created on the FTP protocol is "CURLOPT_FTP_CREATE_MISSING_DIRS".
 Do you have any corresponding SFTP options?
Thanks for any help.

**Comment by bagder** [comment]
You mean the option that is documented like this?

> CURLOPT_FTP_CREATE_MISSING_DIRS - create missing dirs for FTP and SFTP

**Comment by zhanghlstudy** [comment]
CURLOPT_FTP_CREATE_MISSING_DIRS  this option can create missing dirs remotely on the server. Clients can use FTP protocol, but not SFTP protocol. I want to ask clients which option can be used to create missing dirs remotely on the server using SFTP protocol

**Comment by bagder** [comment]
> Clients can use FTP protocol, but not SFTP protocol

Why do you say that? Where does the documentation say so? Let me quote another piece of the man page I already quoted above:

> For SFTP requests, libcurl will attempt to create the remote directory if it can't obtain a handle to the target-location. The creation will fail if a file of the same name as the directory to create already exists or lack of permissions prevents creation.

**Comment by zhanghlstudy** [comment]
I'm sorry, my English is not very good. I use the SFTP protocol to create a non-existent folder on the remote server. The format of the folder is "/ smart / MNT / data / 20200409 /", and the SFTP server uses freehtpd. The creation is not successful. Next, I will post the print in the interaction.
Local file size: 14120 bytes.
UploadForCounters upload sRemoteFile = sftp://192.168.21.171/T0901A1904090343.t.winneryun.com/20200409/
* Found bundle for host 192.168.21.171: 0xae000ac0 [serially]
* Re-using existing connection! (#0) with host 192.168.21.171
* Connected to 192.168.21.171 (192.168.21.171) port 22 (#0)
* Upload failed: Permission denied (3/-31)
* Connection #0 to host 192.168.21.171 left intact
UploadForCounters upload tmp file res = 9

**Comment by zhanghlstudy** [comment]
My URL is "sftp://192.168.21.171/t0901e2003310003.t.wineryun.com/20200409 /". Here is a more detailed print.

*   Trying 192.168.21.171...
* TCP_NODELAY set
* Connected to 192.168.21.171 (192.168.21.171) port 22 (#0)
* SSH MD5 fingerprint: 30d9627c75550e1a3defa37fe38e6ae9
* SSH authentication methods available: password,publickey
* Using SSH private key file ''
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Initialized password authentication
* Authentication complete
* Could not open remote file for reading: Permission denied
* Connection #0 to host 192.168.21.171 left intact

**Comment by zhanghlstudy** [comment]
I have found a way to create a folder remotely, that is, to call commands remotely. In addition, I have a question about whether I can connect to the SFTP server once through libcurl.so, that is, upload the file, and then rename it. Because now I establish a connection to upload the file, and then establish a connection to rename it. That is to say, I call “curl_easy_perform” twice. I also want to know that a call to “curl_easy_perform” is to establish a connection?

**Comment by bagder** [comment]
For libcurl questions, like general usage, please use the curl-library mailing list.

Please show us a) a way to reproduce this "folder creation problem" and b) please tell us what libcurl version and ssh backend/library version you're using. Without that information, we can't do much.

**Comment by zhanghlstudy** [comment]
the software version I used to compile libcurl.so is "zlib-1.2.8.tar,openssl-0.9.8.tar.gz ,libssh2-1.8.0.tar,curl-7.61.0. Tar".Thank you for your help.
SFTP server I use is freeftpd, Serv-U, Serv-U can be created, freeftpd can not be created, freeftpd software version is '1.0.13 '. The source code of the file can not be created is as follows:

 long CFtp::SftpUploadForCounters(char *psLocalFile,	  char *psRemoteFile)//in use
  {
  CURLcode res;
  FILE *hd_src;
  struct stat file_info;
  curl_off_t fsize;
  curl_easy_reset(curl);
  if(!psLocalFile )
  {
	return R_FAIL;
  } 
  if(stat(psLocalFile, &file_info)) {
	printf("Couldnt open '%s': %s\n", psLocalFile, strerror(errno));
	return R_FAIL;
  }
  fsize = (curl_off_t)file_info.st_size;
  printf("Local file size: %" CURL_FORMAT_CURL_OFF_T " bytes.\n", fsize);
  hd_src = fopen(psLocalFile, "rb");
  
  if(curl) {

	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);	

	curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);

	curl_easy_setopt(curl, CURLOPT_READFUNCTION, read_callback); 

	curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
	
	curl_easy_setopt(curl, CURLOPT_FTP_CREATE_MISSING_DIRS, 1); 

	char sUserPass[256];
	memset(sUserPass,0,sizeof(sUserPass));
	snprintf(sUserPass, 256, "%s:%s", m_pstrUser, m_pstrPassword);
	curl_easy_setopt(curl, CURLOPT_USERPWD, sUserPass);

	char sRemoteFile[255];
	if( !m_pstrDir )
		snprintf(sRemoteFile, 255, "%s/%s", m_pstrHost, psRemoteFile);
	else
		snprintf(sRemoteFile, 255, "%s/%s/%s", m_pstrHost, m_pstrDir, psRemoteFile);

	strcat(sRemoteFile,".tmp");

	
	if (m_nMode == 0) // PORT mode
	{
		curl_easy_setopt(curl, CURLOPT_FTPPORT, "-");
	}	
	curl_easy_setopt(curl,CURLOPT_URL, sRemoteFile);
	curl_easy_setopt(curl, CURLOPT_PORT, m_nPort);
	curl_easy_setopt(curl, CURLOPT_FTP_USE_EPSV, TRUE);
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0);
	curl_easy_setopt(curl, CURLOPT_READDATA, hd_src);
	curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE,(curl_off_t)fsize);
	res = curl_easy_perform(curl);
	fclose(hd_src); 
	}

**Comment by bagder** [comment]
If it works with one server and not another, I would posit that this is likely to be a server side issue and not a curl problem.

Do you have any evidence or clue that contradict that theory?
