### ISSUE TITLE
___darwin_check_fd_set_overflow in macOS builds

### ISSUE THREAD

**Issue by bagder** [curl/curl#5210]
Lots of github CI jobs on macOS fail with this error message when linking sockfilt:
~~~
  CCLD     sockfilt
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _main in sockfilt-sockfilt.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~~~

Seems to be a bug in Apple's Xcode 11.4: https://openradar.appspot.com/FB7647406

**Comment by mback2k** [comment]
It looks like the problem is gone again, see latest successful macOS checks in #5188.

**Comment by bagder** [comment]
Lovely. I'll just keep this issue open for a little while more and close it soon if it remains fixed.

**Comment by bagder** [comment]
Closing, the problem seems to have vanished "by itself"...

**Comment by garnetliu** [comment]
I encountered same problem...Could you mention how you fixed it? Thanks

**Comment by garnetliu** [comment]
But my error is 
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      mavlinkcom_impl::UdpSocketImpl::pollin(unsigned int) in libMavLinkCom.a(UdpSocketImpl.cpp.o)
      mavlinkcom_impl::UdpSocketImpl::pollout(unsigned int) in libMavLinkCom.a(UdpSocketImpl.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [output/bin/AirLibUnitTests] Error 1
make[1]: *** [AirLibUnitTests/CMakeFiles/AirLibUnitTests.dir/all] Error 2
make: *** [all] Error 2

**Comment by mback2k** [comment]
We didn't fix it ourselves, it just went away. But you may be able to find more information here:
https://github.com/mono/mono/issues/19393#issuecomment-613639641 (not related to the curl project)

**Comment by akoeplinger** [comment]
@bagder I think your CI issue was only fixed because GitHub rolled back to using Xcode 11.3.1 again (the logs mention `/Applications/Xcode_11.3.1.app`).

As soon as they update to Xcode 11.4 you'll hit this again.

**Comment by bagder** [comment]
This is not a curl bug, this is an infrastructure/XCode bug. Reverting away from that was the right step. If Xcode 11.4 was the sole problem, then I presume that version won't be just reintroduced without necessary steps to have this fixed first.

**Comment by akoeplinger** [comment]
Well that is under GitHub's control and I'm not sure they're aware of that issue :)

**Comment by lizhanhui** [comment]
Hit the same issue with XCode 11.6 and Mac Catalina 10.15.6 (19G73).

**Comment by eng-osman** [comment]
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have the same problem, but I can't solve it xcode 11.3.1

**Comment by magic990619** [comment]
I had same problem with @eng-osman 
Found any solution?

**Comment by harshiththota** [comment]
I am also facing the same issue with Xcode 11.3.1.  Did anyone solved this problem?

**Comment by Arslan106** [comment]
i am also facing the same issue.....

**Comment by afrazahmad21** [comment]
hello is anyone able to solve this issue?

**Comment by anthager** [comment]
@afrazahmad21 For me it worked to update xcode. Dont remember what version I was on before I updated but I was on apple clang 11.0.0. Now Im on apple clang 11.0.3 and xcode 11.6 (11E801a)

**Comment by MonkeybreadSoftware** [comment]
I run into this today here.

I added this to my projects to overwrite the function from macOS with my own implementation and avoid the link problems:

```
#if TARGET_RT_MAC_MACHO

// wegen macOS 11.0 dependency in XCode 15!
int __darwin_check_fd_set_overflow(int, const void *, int)
{
	return 1;
}

#endif
```

Resulting library now loads on macOS 10.13 while built in Xcode 15.
