### ISSUE TITLE
DNS timing is wrong for page with redirects. 

### ISSUE THREAD

**Issue by chemicwepn** [curl/curl#522]
Hi,

I ran the following command.
 curl -A 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' -k -v -L -D - --max-time 240 --output /dev/null --silent --show-error --stderr - --write-out 'Timings: %{time_namelookup} %{time_connect} %{time_appconnect} %{time_pretransfer} %{time_redirect} %{time_starttransfer} %{time_total}\n' 'https://actionpacked.atlassian.net'

and the output is here:
Timings: 0.000 0.000 0.000 0.000 0.570 0.234 0.807
Somehow the dns timing is 0ms, which is not correct. If I run it without the -L, it actually returns back 4ms. So I am guessing the dns timing is for the last redirect page and it doesn't add up the previous dns timing values? In this case, the redirect doesn't get a new domain, so dns doesn't happen on the redirect and therefore it return 0ms. 

I am not sure if this is by design, but if it is, it's NOT very helpful for the user. Usually I want to know how long dns took in total from the beginning to the last byte, not just the dns timing of the last redirect. 

Let me know what you think. 
Thanks!

**Comment by bagder** [comment]
I agree that it would be neat. The code doesn't work like that now though. We need to change the assigns to adds...

**Comment by chemicwepn** [comment]
Do you think it will be  an easy fix? I can take a look at the source code and try to fix it.

**Comment by bagder** [comment]
I believe it could be as easy as making the 5 assignments starting https://github.com/bagder/curl/blob/master/lib/progress.c#L186 to just use '+=' instead of '='.

**Comment by fmrahman** [comment]
In which curl version this fix is available.

**Comment by bagder** [comment]
None, still listed as [a known bug](https://curl.haxx.se/docs/knownbugs.html#DNS_timing_is_wrong_for_HTTP_red)
