### ISSUE TITLE
configure: error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file.

### ISSUE THREAD

**Issue by 19504643** [curl/curl#5243]
### I did this
$ ./configure --disable-dependency-tracking --prefix=/mingw64 --with-nghttp2**=/d/api/library/libnghttp2** --with-ssl="/d/api/library/libopenssl" --with-zlib="/d/api/library/zlib-1.2.11" --with-libssh2=/d/api/library/libssh2 mingw64

**1.**
**Error:**

> configure: error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file.

So I remove the nghttp2 suffix path and it configure success
but the http2 feature is still disabled
![image](https://user-images.githubusercontent.com/4372492/79432206-17722a00-7ffe-11ea-88e2-a8ca95f18d49.png)

**2.**
make it ok and check the version, why does the http2 feature occurs
![image](https://user-images.githubusercontent.com/4372492/79432770-da5a6780-7ffe-11ea-9acf-44196d1a327e.png)

**3.**
I compared the shared dll files libcurl-4.dll with others, why is it much smaller than others
![image](https://user-images.githubusercontent.com/4372492/79433605-ea267b80-7fff-11ea-9510-e5181a59945b.png)

### curl/libcurl version
curl-7.69.1.tar.gz

$ gcc -v
Using built-in specs.
COLLECT_GCC=D:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/9.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
...
Thread model: posix
gcc version 9.3.0 (Rev2, Built by MSYS2 project)

$ make -v
GNU Make 4.3
Built for x86_64-pc-msys

[curl -V output]

### operating system
$ uname -a
MINGW64_NT-6.1-7600 yijiayi-PC 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys

**Comment by bagder** [comment]
> configure: error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file.

A normal `make install`  after having built nghttp2 installs its pkg-config file as `$PREFIX/lib/pkgconfig/libnghttp2.pc`. Do you have it there? Can you figure out why configure doesn't think so? Possibly config.log contains some clues after the check has failed.

**Comment by bagder** [comment]
(I could add that I ignored the rest of the post and focused on the primary issue)

**Comment by bagder** [comment]
Ten days passed and no response to my immediate follow-up question. I suspect a user error/mistake and I have nothing to act on. Closing.

**Comment by tachyonknave** [comment]
I was having a similar problem and followed your advice.  

I did a find on libnghttp2.pc which was found in /usr/local/lib/pkgconfig on my machine. 

The PKG_CONFIG_PATH env var was blank so I did an '$EXPORT PKGCONFIG_PATH=/usr/local/lib/pkgconfig/' and then pkg-config could find it. 

When I ran ./configure --enable-http2 it worked without issue

**Comment by majid-rafei** [comment]
> EXPORT PKGCONFIG_PATH

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
