### ISSUE TITLE
curl: support 'connected udp' for tftp protocol

### ISSUE THREAD

**Issue by borkmann** [curl/curl#5244]
For Linux kernel testing on UDP side, having the tftp:// option is very useful. However, it's only implemented as unconnected UDP (sendmsg/recvmsg). It would be super useful to be able to use curl tool with 'connected udp' as well (aka, calling connect() on the UDP socket and, then using plain send/recv for the tftp connection).

**Comment by bagder** [comment]
I hear you and I don't think it would hurt to switch over to that method, but I also can't see much benefit for common users. I would accept a PR!

**Comment by borkmann** [comment]
> I hear you and I don't think it would hurt to switch over to that method, but I also can't see much benefit for common users. I would accept a PR!

Ok, not "switching over" entirely, but instead have a cmdline switch to be able to select between the two (unconnected UDP / connected UDP). Any suggestions what name for such mode-switch parameter might be acceptable `--udp-connected`/`--udp-unconnected`?

**Comment by bagder** [comment]
I just have a hard time to accept such an option. Sure we have many fringe options already in curl, but this is a suggested option with no visible difference at all to anyone! (except perhaps to those working on the UDP stack itself). It feels like not even one in a million user would ever use it.

**Comment by emilengler** [comment]
Would an option in the build system be a better idea?

**Comment by bagder** [comment]
Yes, that would make it an entirely different discussion.

**Comment by bagder** [comment]
We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker. If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

This feels like such a fringe request though so I won't even add it to the TODO.
