### ISSUE TITLE
multissl: curl_global_cleanup doesn't restore Curl_ssl as its default (Curl_ssl_multi)

### ISSUE THREAD

**Issue by davidedec** [curl/curl#5255]
I noticed that after a `curl_global_cleanup` it's not possible to `curl_global_sslset` and `curl_global_init` again in order to change the ssl backend.

This can be achieved in vtls.c by setting back the `Curl_ssl = &Curl_ssl_multi` after the `Curl_ssl_cleanup`

The idea is to be able to change the backend in this sequence:
```
curl_global_sslset(CURLSSLBACKEND_SCHANNEL, NULL, NULL);
curl_global_init(CURL_GLOBAL_DEFAULT);
//....
curl_global_cleanup();

curl_global_sslset(CURLSSLBACKEND_OPENSSL, NULL, NULL);
curl_global_init(CURL_GLOBAL_DEFAULT);
//....
curl_global_cleanup();
```

Thanks

**Comment by jay** [comment]
The documentation says it can only be set once, but I would think it could be set after cleanup, in other words once each time it's uninitialized. @dscho

**Comment by dscho** [comment]
Makes sense.

I think it _should_ be as easy as adding the lines

```c
#ifdef CURL_SSL_MULTI
    Curl_ssl = &Curl_ssl_multi;
#endif
```

to https://github.com/curl/curl/blob/9c703ead3620535eb6b190c8ef87942ff8f08fc2/lib/vtls/vtls.c#L179-L186

@davidedec could you test that?

**Comment by davidedec** [comment]
@dscho thanks for your prompt reply.
I'll test that tomorrow and I'll come back to you. 

Thanks again

**Comment by dscho** [comment]
Actually, I think those three lines should go into `Curl_none_cleanup()`. Consequently, that function should be renamed to `Curl_multissl_cleanup()`, and it should be moved directly after `Curl_multissl_init()`.

**Comment by dscho** [comment]
Ah! And of course it should call `Curl_ssl->cleanup()`, unless `Curl_ssl` still points to `Curl_ssl_multi`.

**Comment by davidedec** [comment]
Right. Tomorrow I will tell you if it works and pass tests

**Comment by jay** [comment]
If it works can one of you turn it into a PR for review please

**Comment by dscho** [comment]
I actually pulled out the computer and am doing precisely that.

**Comment by dscho** [comment]
Phew, that took longer than I hoped for. I'm glad I tried to verify that my patch works, as my initial version (the one modifying `Curl_none_cleanup()`) totally did not work, like, at all.

@davidedec would you mind testing #5257?

**Comment by davidedec** [comment]
Just tested #5257 and worked as expected for me
