### ISSUE TITLE
Test 1700 failures

### ISSUE THREAD

**Issue by bagder** [curl/curl#5289]
### I did this

Test 1700 to 1702 (HTTP/2) fail occasionally in my dev system when *not* run stand-alone (also visible in [some CI jobs](https://travis-ci.org/github/curl/curl/jobs/678911198#L5911)). I can reproduce pretty reliably if I run tests 350 to 1700. I'm in the process of trying to narrow down the list.

The failing builds probably have alt-svc enabled too.

### curl/libcurl version

current git master

### operating system

I've seen it on Linux but expect this to be platform independent.

**Comment by emilengler** [comment]
You're not alone, however these tests fail for me:
165 962 963 964 965 966 967 1448 1700 1702 2046 2047

on that system
```
********* System characteristics ******** 
* curl 7.70.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.70.0-DEV OpenSSL/1.1.1d libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.36.0
* Features: AsynchDNS Debug HTTP2 HTTPS-proxy IDN IPv6 Largefile NTLM NTLM_WB PSL SSL TLS-SRP TrackMemory UnixSockets
* Disabled: 
* Host: debian
* System: Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
* OS: linux
*
*** DISABLES memory tracking when using threaded resolver
*
* Servers: HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: Valgrind 
* Seed: 232966
* Port range: 8990-8999
***************************************** 
```

**Comment by bagder** [comment]
The other test failures have other explanations. They don't fail for me nor in the CI jobs.

**Comment by bagder** [comment]
Repro with: `./runtests.pl 358 1523 1700`

Regression brought by 80d6515415

Explanation: test 1523 *kills* the HTTP server since it leaves it in a weird state, but the HTTP/2 proxy is already running and configured to speak to the original $HTTPORT. When the HTTP server is brought up again for test 1700 it will run on a new port but the HTTP/2 proxy doesn't know about it...
