### ISSUE TITLE
Bad response from server

### ISSUE THREAD

**Issue by Lifeda92** [curl/curl#5293]
Hello.

When i send request to server, i got "HTTP/1.1 302 Found".
Then i send request with same curl handle on location, which i got from previous request.
But in answer, i get just header with "HTTP/1.1 100 Continue".

If i use different curl handles for these requests - all is ok. Second request send me "HTTP/1.1 303 See Other" and body.
Why i need use different handles? Maybe have way to use one handle for all requests?

Thanks.

curl/libcurl version: libcurl/7.64.1-DEV Schannel WinIDN

[curl -V output]

operating system: Windows 10

**Comment by Lifeda92** [comment]
I know about option followlocation, but can without enable this option? I want make redirect in hand mode.

**Comment by bagder** [comment]
If you think this is a problem with curl, you need to help us *reproduce* the problem or if that's not possible, show heaps of more information.

> i get just header with "HTTP/1.1 100 Continue".

If you get nothing more than a 100 from the server and then nothing more, it sounds like a server bug.

**Comment by jay** [comment]
You can redirect manually by using [CURLINFO_REDIRECT_URL](https://curl.haxx.se/libcurl/c/CURLINFO_REDIRECT_URL.html).

**Comment by bagder** [comment]
@Lifeda92: this bug report is incomplete and we can't act on it. We need more information or we'll close it soon.

**Comment by bagder** [comment]
No response, closing.
