### ISSUE TITLE
CURLINFO_ACTIVESOCKET doc is misleading

### ISSUE THREAD

**Issue by jay** [curl/curl#5299]
### I did this

While investigating a mailing list [question](https://curl.haxx.se/mail/lib-2020-04/0037.html) I observed that [CURLINFO_ACTIVESOCKET](https://curl.haxx.se/libcurl/c/CURLINFO_ACTIVESOCKET.html) does not actually return the active socket until after the transfer is done. This appears to be due to legacy reasons, since it is a replacement for [CURLINFO_LASTSOCKET](https://curl.haxx.se/libcurl/c/CURLINFO_LASTSOCKET.html).

The socket can only be retrieved via ACTIVESOCKET after lastconnect is set, which only happens in multi_done:

https://github.com/curl/curl/blob/b81e0b07784dc4c1e8d0a86194b9d28776d071c0/lib/multi.c#L661-L676

https://github.com/curl/curl/blob/b81e0b07784dc4c1e8d0a86194b9d28776d071c0/lib/connect.c#L1373-L1413

### I expected the following

The documentation says _"Pass a pointer to a curl_socket_t to receive the active socket used by this curl session."_ That implies the socket is available before the session is done.

### curl/libcurl version

master branch
~~~
curl 7.70.0-DEV (i386-pc-win32) libcurl/7.70.0-DEV Schannel WinIDN
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
~~~

### operating system

Windows 7

**Comment by bagder** [comment]
We can certainly improve the phrasing. We generally never promise any results reliably from `curl_easy_getinfo` until post-transfer.
