### ISSUE TITLE
AcquireCredentialsHandle always return SEC_E_SECPKG_NOT_FOUND

### ISSUE THREAD

**Issue by kouzhudong** [curl/curl#5307]
![image](https://user-images.githubusercontent.com/18212165/80468678-10d6a180-8972-11ea-8a79-76fba914f3ce.png)

**Comment by kouzhudong** [comment]
But, "Microsoft Unified Security Protocol Provider" real exist.

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/80469870-c2c29d80-8973-11ea-8133-202a3a62641f.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/80469966-e2f25c80-8973-11ea-93ab-d2453a3a75f0.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/80471566-28b02480-8976-11ea-9ecd-e3445e286c87.png)

**Comment by kouzhudong** [comment]
![image](https://user-images.githubusercontent.com/18212165/80471782-79278200-8976-11ea-92bc-12aaf4120438.png)

**Comment by kouzhudong** [comment]
1: kd> k
 # Child-SP          RetAddr           Call Site
00 00000000`0b71dbf8 000007fe`f91afb0a libcurl_debug!Curl_failf [XXXXXlib\curl\lib\sendf.c @ 263] 
01 00000000`0b71dc00 000007fe`f91b18b2 libcurl_debug!schannel_connect_step1+0xb2a [XXXXXlib\curl\lib\vtls\schannel.c @ 689] 
02 00000000`0b71e1b0 000007fe`f91b1bbd libcurl_debug!schannel_connect_common+0xf2 [XXXXXlib\curl\lib\vtls\schannel.c @ 1369] 
03 00000000`0b71e240 000007fe`f91aaba5 libcurl_debug!Curl_schannel_connect_nonblocking+0x3d [XXXXXlib\curl\lib\vtls\schannel.c @ 1933] 
04 00000000`0b71e270 000007fe`f91333ea libcurl_debug!Curl_ssl_connect_nonblocking+0xa5 [XXXXXlib\curl\lib\vtls\vtls.c @ 278] 
05 00000000`0b71e2b0 000007fe`f91304ad libcurl_debug!https_connecting+0x3a [XXXXXlib\curl\lib\http.c @ 1575] 
06 00000000`0b71e2f0 000007fe`f916586f libcurl_debug!Curl_http_connect+0xfd [XXXXXlib\curl\lib\http.c @ 1497] 
07 00000000`0b71e330 000007fe`f9166400 libcurl_debug!protocol_connect+0x14f [XXXXXlib\curl\lib\multi.c @ 1484] 
08 00000000`0b71e370 000007fe`f9161748 libcurl_debug!multi_runsingle+0xb60 [XXXXXlib\curl\lib\multi.c @ 1793] 
09 00000000`0b71e6b0 000007fe`f9158537 libcurl_debug!curl_multi_perform+0xf8 [XXXXXlib\curl\lib\multi.c @ 2340] 
0a 00000000`0b71e7a0 000007fe`f9158769 libcurl_debug!easy_transfer+0x97 [XXXXXlib\curl\lib\easy.c @ 599] 
0b 00000000`0b71e840 000007fe`f9157a7a libcurl_debug!easy_perform+0x189 [XXXXXlib\curl\lib\easy.c @ 692] 
0c 00000000`0b71e890 00000001`3f1be777 libcurl_debug!curl_easy_perform+0x2a [XXXXXlib\curl\lib\easy.c @ 712]

**Comment by bagder** [comment]
I don't understand what you're trying to say with this series of images and a stack trace.

**Comment by kouzhudong** [comment]
为你们分析提供信息。

**Comment by bagder** [comment]
Not enough to act upon, closing.
