### ISSUE TITLE
Building static library for Windows (winbuild/Makefile.vc) should just "work"

### ISSUE THREAD

**Issue by slgoldberg** [curl/curl#5308]
### I did this

I wanted to build the static library for MS Visual C++ (to statically link with my project using Visual Studio 2017) and I followed the instructions carefully.  However, I got a raft of linker errors that took me literally 5 hours of painful troubleshooting to resolve.

In short, I built the static library following the instructions, but I am not an expert at Windows development, so I assumed somehow the arcane explanation of RTLIBCFG didn't apply to me (when it did -- and it does for the vast majority of uses when building a static version of the library).

As a result, I got pages-full of error messages from the linking stage, when trying to use the library built from my first pass at this (which only took about 10 minutes).

Then, I proceeded to waste the next 6 hours of my life, scouring websites, reading all about Windows DLLs and the oh-so many ways to compile for different CRLs, etc., etc. -- most of which I really didn't want to know, and really honestly shouldn't have needed to know, to do something that in the end was *such* a simple solution that I can't believe it took me 6 hours instead of 30 minutes total to get it working.

This bug report, therefore, is an attempt to elucidate and enumerate the issues with recommendations for how to make this better -- so other pour souls don't go through what I did, each time they want the common case use, which is: "I want to use libcurl in my cross-platform application, and my Windows Visual C++ version won't build because the instructions for building the static library on Windows makes me first learn all about CRL, which I shouldn't have to." :-)

So -- in the end -- the problem was two-fold (both of these are detailed below):

1. the documentation for building on Windows is confusing at best, not well organized, missing key information or simply not optimized for the *most common cases*, and wrong at worst; and
1. the makefile (`winbuild/Makefile.vc`) parameter `mode=static` leads (in a vast majority of cases) to broken builds and hours of wasted time trying to fix it.

### I expected the following

When I wanted to build the static library (`libcurl_a.lib`) for use with my Visual Studio 2017 C++ project on Windows, I followed the instructions and did the following:
`% cd curl-src/winbuild
% nmake /f Makefile.vc mode=static debug=false machine=x64`

I *expected* the `mode=static` flag in `winbuild`'s makefile environment to *build a static library*. But instead, it just build a file that *looked* like a static library but wouldn't link with the Windows version of my project (which is itself a DLL I want people to be able to use without having to also include multiple copies and versions of libcurl.dll for obvious reasons -- hence, "static").

In the FAQ, there are two arcane explanations buried in the text (and also in the read-me file that is in the `winbuild` directory) that are very confusing and should be fixed -- excerpt of current version follows:

> Static linking of Microsoft's C RunTime (CRT):
> ==============================================
> If you are using mode=static nmake will create and link to the static build of
> libcurl but *not* the static CRT. If you must you can force nmake to link in
> the static CRT by passing RTLIBCFG=static. Typically you shouldn't use that
> option, and nmake will default to the DLL CRT. RTLIBCFG is rarely used and
> therefore rarely tested. When passing RTLIBCFG for a configuration that was
> already built but not with that option, or if the option was specified
> differently, you must destroy the build directory containing the configuration
> so that nmake can build it from scratch.
> 
> Building your own application with a static libcurl
> ===================================================
> When building an application that uses the static libcurl library on Windows,
> you must define CURL_STATICLIB. Otherwise the linker will look for dynamic
> import symbols.

The above information *is* correct. However, it's confusing and really needs to be improved (and probably combined).

For one thing, the title of the first section ("Static linking... (CRT)") is too-much-information for most users.  What really matters is, "how do I build this so I can use it as a static library in my current application which I'm compiling and linking using Visual Studio?"

So, the "CRT" section should be moved *after* (or inside) the section titled "*Build your own application ... static libcurl*", and should include four things. (What four things? Scroll down to see my exact proposal of what should be included there.)

Next, I didn't expect to have to set RTLIBCFG=static when there is already a flag "`mode=static`". Why would I need both? (I know the answer, I'm just speaking rhetorically.)

In other words, it seems that building `libcurl` using `mode=static` uses the wrong default -- which I feel is actually useless for the vast majority of cases.  Essentially, since it won't have been built using the `/MT` compiler flag, it will result in tons of missing references to standard library functions at the linking phase when you try to use this in your project (as a static library as opposed to any other form).

To back up my claim that it's the wrong default, I have found too many postings to count, on forums where developers are asking why they get these linker errors when trying to use libcurl_a.lib supposedly built as a "static" library using the `nmake` command with`winbuild/Makefile.vc` and then trying to build against that library.  For all of these people, the solution was to simply use `RTLIBCFG=static`.

And yes, this requirement is clearly stated above. However, this leads me to two suggestions (the first framed as a question):

1.  *Shouldn't `mode=static` automatically set `RTLIBCFG=static`*?  In other words, I think it's a bug that `Makefile.vc` doesn't automatically add the `/MT` flag when compiling in "static" mode.
(I.e., when would it ever be useful to use `nmake ... mode=static ...` to build `libcurl_a.lib` in the `.../release/libcurl-static/..` library path, if you can't actually link with it in your MSVC project as a static library???) I am completely confused why this common case is not the default when `mode=static` and what it would even mean for it to be "static" but "not static" at the same time. This is extremely confusing.
The instructions should -- at a minimum -- just tell you to *always* include this flag when building the "static" version of the library for Windows.
    - Note: I'm not the only one who's been confused by this. Many, many people have posted about this exact issue, for a long time, and they too just assumed that the only reason to say `mode=static` is to make the static version; the lack of clear documentation of `RTLIBCFG=static` in the default flow for building libcurl as a static library on Windows, is a problem.
1. **Explain the *method* for setting `RTLIBCFG`** in the documentation (including the FAQ information quoted above).
This means *if* RTLIBCFG is a parameter (see below) to `nmake`, then it should be documented in the read-me file in the `winbuild` directory along with all the other options (but it's not).
Not everyone knows what you mean by "pass" -- in the phrasing used in the FAQ: 
"*you must for nmake to link in the static CRT by passing RTLIBCFG=static*".
But *how* does one "pass" this variable? And where?
In Google searches, I've seen people post about this using three different methods -- all in the Visual C++ shell tool (so, it's not because of different shell environments):
    - `% RTLIBCFG=static nmake /f Makefile.vc mode=static ...`
    - `% nmake /f Makefile.vc mode=static RTLIBCFG=static ... ` and
    - `% Set RTLIBCFG=static` followed by:
      `% nmake /f Makefile.vc mode=static ...`

    Which of the above is right?  (I think all of them work; but maybe not? If it works anywhere, then it should be listed in the read-me file as a usage option for `nmake`, just like all the other options like DEBUG and mode and etc.).
    Like many many people who just want to build the static library so they can use it in their Windows builds, I am a software engineer but not a Windows expert with arcane knowledge of all the tools, so I just need a script I can follow, not a complicated description that requires me to work backwards to figure out how to build this thing.

Also, the second part, above, titled, "Building your own application with a static libcurl" fails to bring it all together to make it understandable again.  It clearly spells out the important requirement that you must define the preprocessor macro, but in fact, *four* things are required to use libcurl static library in your project on Windows, not just one!! It would be swell if these were all documented in one place.  They are:
  1. **you must set preprocessor definition `CURL_STATICLIB`**;
  1. **you must have built the file `libcurl_a.lib` using the correct `RTLIBCFG=static` method** above
      - note: this option can't be set like `DEBUG` to generate an alternative deployment; rather, you must *delete all files in ../builds/* and re-build if you ever change `RTLIBCFG` (which makes it even harder because I figured this out midway through my haggling, but didn't realize I needed to delete everything, so it would recompile with `/MT`, so it didn't "take", as it were)
  1. **you must add paths** for (a) **includes** (i.e., `...\libcurl-vc-x64-release-static-ipv6-sspi-winssl\includes`), and for (b) **libraries** (i.e., `...\libcurl-vc-x64-release-static-ipv6-sspi-winssl\lib`); and finally,
  1. **you must add several files** (not just `libcurl_a.lib`) **to your library dependencies** in your build configuration:
        `libcurl_a.lib`
        `Ws2_32.lib`
        `Crypt32.lib`
        `Wldap32.lib`
        `Normaliz.lib`
      However, these requirements are summarized anywhere. I would expect them to be in the paragraph referenced above in the FAQ, about how to build using the static library libcurl_a.lib in your Windows application. (Which should also explain the other stuff here.)

If only all these instructions were clearly spelled out, in sequence, and/or if the `mode=static` simply did the right thing (which includes only putting files in the build directory called `...-static...` if they really *are* static libraries that can be linked with!), other folks like myself could save literally hours of wasted time and much  more readily adopt this awesome library.

This feels like it is a very common case. I don't understand why you've opted to have the default be backwards when `mode=static`. Can I convince you to change it?  When building a DLL (as I'm doing), I really want everything to be self-contained. I still can't picture any other logical (or likely) interpretation of "static library" than that it was built for ready linkage in my application without generating hundreds of linker errors for the standard library.

Note: I noticed [this issue](https://github.com/curl/curl/issues/254) when I was researching this; it's not exactly the same issue, but it's clear you even discussed the fact that this is confusing, but for some reason didn't solve it. I'm just confused why this isn't a higher priority since literally everyone who builds libcurl_a.lib for Windows runs into this problem eventually. And then it leads to lots of time wasted. Thanks for listening.

P.S. I am building a DLL; others may be building standalone Windows apps. I am not sure if I understand this well enough to answer this myself, but if it turns out the `mode=static` flag is correct for stand-alone applications, then please just say that in the description instead of talking about all the different runtime library options available in Windows development. I really just need to know, if I am building a DLL and want to use libcurl in my DLL, what the formula is for getting that to happen in the MS Visual Studio ecosystem.    And if that's different from the formula needed if I were building a standalone application, then fine -- break it out into two sections. But I really think it would be so much better and people would more readily adopt and use libcurl if they could have a clearer set of steps to follow to get it built as a static library for their case. (Also, I wish the binary distribution subproject supported this use as well; right now it appears to me all the options are third-party environments, not standard Windows; so I'm confused why they call themselves Windows binaries. But that's another issue.)

Thanks again.

### curl/libcurl version

Latest release.

### operating system

Windows 10 Professional with Microsoft Visual Studio 2017 and using the command line tool called "x64 Native Tools Command Prompt for VS 2017" when building the static library from sources.

**Comment by bagder** [comment]
I too would appreciate better and clearer instructions and documentation for building on Windows but I personally can't since this is all just mumbo jumbo to me.

We have a serious lack of contributors to who use and build on Windows - and those who do already know and understand how to build so they may not have the necessary "outsider's view" that could be good to get the docs better for this.

We appreciate help and pull-requests to improve the project in all aspects, including docs and build files for Windows!

**Comment by slgoldberg** [comment]
Wow, this is about as good (and fast) a response as I could have asked for -- thank you, Daniel.

I'm not exactly an expert myself at Windows development ins and outs, but (no promises) I may make a stab at at least a pull request for the read-me and FAQ sections if I can verify the information now that I have at least some handle this stuff.

I'm also kind of hopeful someone in your extended contributor group might be willing to take a look at this and confirm or deny my claim that it really does make sense to have the static mode for Windows default to using the static runtime library option (i.e., `/MT`) in the meanwhile.

Thanks.

**Comment by jay** [comment]
I don't think changes are necessary. If you are building static libraries on Windows IMHO you should know these things, which are not curl specific.

**Comment by MarcelRaad** [comment]
Documentation can always be improved, but I think defaulting to a dynamic CRT is fine for both static and dynamic libcurl. A dynamic CRT is required also for static libraries for some use cases like UWP apps and C++/CLI. And actually static libraries that end up in dynamic libraries if you're not exactly sure about the consequences.

**Comment by bagder** [comment]
I wouldn't mind having a separate document entirely devoted to how to build curl/libcurl on Windows. It could even be a subsection in the everything curl book (which currently is very sparse on [how to build on windows](https://ec.haxx.se/sourcecode/building/building-source#on-windows)). I couldn't write it though.

**Comment by bagder** [comment]
This issue has nothing real to act on other than a request that we get better documentation, something we all always want and we all work on. I don't think keeping this issue open longer will help us achieve anything. Therefor, I'm closing this issue.
