### ISSUE TITLE
curl_easy_perform() failed: Login denied

### ISSUE THREAD

**Issue by guyuehuanyu** [curl/curl#5321]
### I did this
$ curl --version
    curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.0.2g zlib/1.2.8
$ curl --url "smtp.qq.com:587"   --mail-from "xxx@qq.com" --mail-rcpt "xxxx@qq.com"  --user 'xxx.hu@qq.com:xxxxxxxxx'  -v  --upload-file mail.txt
result:
* TCP_NODELAY set
* Connected to smtp.qq.com (183.3.225.42) port 587 (#0)
< 220 newxmesmtplogicsvrszb5.qq.com XMail Esmtp QQ Mail Server.
> EHLO mail.txt
< 250-newxmesmtplogicsvrszb5.qq.com
< 250-PIPELINING
< 250-SIZE 73400320
< 250-STARTTLS
< 250-AUTH LOGIN PLAIN
< 250-AUTH=LOGIN
< 250-MAILCOMPRESS
< 250 8BITMIME
> AUTH PLAIN
< 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (67) Login denied
$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
$ curl --url "smtp.qq.com:587"   --mail-from "xxx@qq.com" --mail-rcpt "xxxx@qq.com"  --user 'xxx.hu@qq.com:xxxxxxxxx'  -v  --upload-file mail.txt
I got 235 Authentication successful

### I expected the following
curl 7.68.0 still get 235 Authentication successful
### curl/libcurl version
7.47.0 successful
7.68.0 fail
[curl -V output]

**Comment by emilengler** [comment]
See #4080

**Comment by guyuehuanyu** [comment]
Thanks, if I use the curl_easy_setopt function, which define variable should I set

**Comment by guyuehuanyu** [comment]
i just find curl_easy_setopt(curl, CURLOPT_LOGIN_OPTIONS, "AUTH=LOGIN");, thanks
