### ISSUE TITLE
broken build, windows 10 64bit, VS2019

### ISSUE THREAD

**Issue by JW-Schuetz** [curl/curl#5331]
### I did this
"nmake /f Makefile.vc mode=static" in the winbuild directory with the VS2019 console

### I expected the following
In the past that command worked fine. I expected that the build finished without errors but I got the error from nmake: fatal error U1073: "..\src\tool_hugehelp.c" could not generated

### curl/libcurl version
actual git content master-branch

[curl -V output]

### operating system
win 10 64bit, VS2019
[console-output.txt](https://github.com/curl/curl/files/4569887/console-output.txt)

**Comment by MonkeybreadSoftware** [comment]
Can you get a more verbose error there?
We just see that tool_hugehelp.c could not be build, but we don't see the error form the C compiler.

**Comment by JW-Schuetz** [comment]
Thats just all I see but I will try it. Just a moment.

**Comment by JW-Schuetz** [comment]
After a "make clean" for me the compiling of c-sources works fine. Also the linking step.
Then nmake copies some libs. And then the error occurs.

See console output:
[CurlConsoleOutput.txt](https://github.com/curl/curl/files/4570269/CurlConsoleOutput.txt)

**Comment by JW-Schuetz** [comment]
I found out that in the repository the file "tool_hugehelp.c" is missing!
Instead there is a file "tool_hugehelp.c.cvs".
I am shure thats the reason!

**Comment by bagder** [comment]
If you build from git then I trust you've read [GIT-INFO](https://github.com/curl/curl/blob/master/GIT-INFO)

**Comment by JW-Schuetz** [comment]
I mean the attached issue with red mark

[CURL-Files](https://user-images.githubusercontent.com/40438317/80917600-51626080-8d60-11ea-846d-a79c6388a18e.jpg)

**Comment by bagder** [comment]
Let me then just refer back to my [earlier comment](https://github.com/curl/curl/issues/5331#issuecomment-623121206).

**Comment by JW-Schuetz** [comment]
Oh yes! At the end of the file! :-)
That was what i just did to workaround this issue.
What I don't understand is why it worked in the past.

**Comment by JW-Schuetz** [comment]
In any case thanks for the help. Should I close or will you do it?

**Comment by bagder** [comment]
Building the code from git has worked like this since before we even used git. Possibly you built from a release archive previously, which don't need this extra step.
