### ISSUE TITLE
Azure windows build errors

### ISSUE THREAD

**Issue by bagder** [curl/curl#5332]
### I did this

Recent windows builds on azure fail with:

~~~
  CC     resolve-util.o
util.c:817:1: error: expected identifier or '(' before '}' token
  817 | }
      | ^
make[2]: *** [resolve-util.o] Error 1
~~~ 

[example build log](https://dev.azure.com/daniel0244/curl/_build/results?buildId=1682&view=logs&j=af6c44c1-336a-50ab-226d-cd44623abe3d&t=64751f9b-2c06-554a-f994-0343316604bb&l=78) and [another example](https://dev.azure.com/daniel0244/curl/_build/results?buildId=1682&view=logs&j=bd5492e8-8bcd-5aff-6ecb-c34ac3886b12&t=783a30bd-078f-5755-ed54-480fddb075ab&l=50)

I presume one of the more recent changes of the test servers causes this.

### I expected the following

The builds to work.

### curl/libcurl version

current git master

### operating system

Windows

**Comment by mback2k** [comment]
Interesting, I cannot reproduce this locally. I will take a deeper look this evening.

**Comment by bagder** [comment]
They also don't seem to happen on appveyor?

**Comment by mback2k** [comment]
I don't see it in any recent builds, do you?

**Comment by bagder** [comment]
They seem to have vanished! Closing this.
