### ISSUE TITLE
libcurl does not recognize [::] as a valid IPv6 address

### ISSUE THREAD

**Issue by volpav** [curl/curl#5344]
### I did this

1. Started a local server, providing the IPv6 binding of `[::]:12345`
2. Attempted to use libcurl to connect to the server

### I expected the following

libcurl successfully connecting to the server.

### instead, I got this

Received `URL using bad/illegal format or missing URL (code 3)` error from libcurl.

### curl/libcurl version

7.69.1 (with IPv6 enabled)

### operating system

Debian-based corporate build.

### notes

Changing `[::]` to `[::1]` fixes the problem.

Looks like the bug was introduced in https://github.com/curl/curl/commit/47066036a084a9ba0caf46db24072a429c44fabb. To comment on this, `[::]` (and even `::`) seems to be a valid IPv6 address according to https://en.wikipedia.org/wiki/0.0.0.0.

This works as expected in 7.66.0.

**Comment by jay** [comment]
It's a non-routable address used for binding, how is it a valid destination?

**Comment by bagder** [comment]
`::` is indeed a valid IPv6 address (consisting of all zeroes), I just didn't think about that case when I added that extra check in the URL parser. Should we accept it?

**Comment by volpav** [comment]
For posterity, the `[::]` (`0.0.0.0`), even though not being a valid destination, essentially means to listen to all interfaces when you perform a binding.

While `[::]`, theoretically-speakig, is not a valid destination (since it means "any destination"), it seem that there's a number of network stack implementations that would treat it as a loopback address. For Linux, this looks like a relevant piece of code: 

```c
if (!fl4->daddr) {
  fl4->daddr = fl4->saddr;
  if (!fl4->daddr)
    fl4->daddr = fl4->saddr = htonl(INADDR_LOOPBACK);
  
  // ...
}
```
_(source: [net/ipv4/route.c](https://github.com/torvalds/linux/blob/dc56c5acd8505e1e7f776d62650f3850ad2ce8e7/net/ipv4/route.c#L2598-L2599))_

**Comment by jay** [comment]
> Should we accept it?

I vote no

**Comment by bagder** [comment]
> I vote no

With what motivation? Why should our URL parser restrict what IP address the user can specify? It seems entirely arbitrary. We already accept `0.0.0.0` which also is a perfectly valid address. I think we should accept `::`.

**Comment by emilengler** [comment]
I agree with @bagder.
I don't think it is our task to tamper that much with the IP and OSI-Level 3 protocols in general as this is a task of the operating system or other lower level software

**Comment by jay** [comment]
I changed my mind. Those are all good points.
