### ISSUE TITLE
Make Install yields broken Lib

### ISSUE THREAD

**Issue by f1s3c** [curl/curl#5346]
### I did this
Compiling the static lib on windows with nmake yields libcurl_a.lib and a bunch of obj files, 

libcurl_a.lib needs to be in the folder with the obj files in order for my program to compile without unresolved externals.

I can't seem to disable certain curl features using nmake, the same way I can do with
./configure && make && make install

`./configure --disable-ares --disable-cookies --disable-crypto-auth --disable-ipv6 --disable-manual --disable-proxy --disable-verbose --disable-versioned-symbols --enable-hidden-symbols --without-libidn --without-librtmp --without-ssl --without-zlib --disable-dict --disable-file --disable-ftp --disable-gopher --disable-imap --disable-ldap --disable-ldaps --disable-pop3 --disable-rtsp --disable-smtp --disable-telnet --disable-tftp --prefix=/curl`

This is the configure command I use on git-bash sdk on that same windows VM, everything compiles without erros except the fact that all I get is the libcurl.a library.

Using it in my program (simple http-get request to read string)

`
#include "curl/curl.h"

#pragma comment (lib, "crypt32.lib")

#pragma comment (lib, "advapi32")

#pragma comment (lib, "ws2_32.lib")

#pragma comment (lib, "wldap32.lib")

#pragma comment (lib, "normaliz.lib")

#pragma comment (lib, "libcurl/libcurl.a")
`

 gives me 47 unresolved externals.
[pastebin](https://pastebin.com/fb34U0RF)

### I expected the following
`make install` to produce the libcurl_a.lib file

### curl/libcurl version
7.70.0

**Comment by bagder** [comment]
I'm sorry, but these errors are from *you* linking 'your* program with a static libcurl, right? How is that a libcurl issue?

When you link statically, it is your job to make sure all dependencies are provided and linked with as well, You seem to have missed a few.

**Comment by f1s3c** [comment]
I seem to have include all the ones from documentation.

Here's my ./configure [output](https://pastebin.com/x0dQKh3j)

The Libs: tag indicates it's only using ws2_32 or am I misinterpreting this?

Updated [unresolved externals](https://pastebin.com/GzExhTuB) (13)


That's why I thought there must be a problem with libcurl.
Anyways, do you have an idea what else I could be missing?

**Comment by bagder** [comment]
I struggle to see the curl issue. Can you build curl/libcurl fine? If so, where's the problem?

You seem to have an issue to build *your project* with the static libcurl you built and while I sympathize, it doesn't seem like an issue for our bug tracker. Track down the missing symbols and add the libs that provide them.

**Comment by jay** [comment]
Ref: https://curl.haxx.se/mail/lib-2020-05/0021.html
Ref: https://curl.haxx.se/mail/lib-2020-05/0027.html
