### ISSUE TITLE
misleading error message with NTLM/SSPI

### ISSUE THREAD

**Issue by wangp** [curl/curl#5349]
### I did this

I ran the curl command line tool from a PHP script running under IIS. The curl command attempts to load a resource over HTTP with NTLM authentication:
```
curl.exe -v http://localhost -u USER:PASS --ntlm -o ...
```
In the default IIS configuration, the curl process runs under the wrong user (something like that, I am not familiar with IIS or Windows authentication but can provide the steps to reproduce if required). The curl verbose output is:
```
* Rebuilt URL to: http://localhost/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host localhost left intact
curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

**The issue is the misleading error message.** NTLM support *is* built-in to this copy of libcurl but is being denied due to the environment it is running in. I tracked it down to these lines in ntlm_sspi.c:
```c
  /* Query the security package for NTLM */
  status = s_pSecFn->QuerySecurityPackageInfo((TCHAR *) TEXT(SP_NAME_NTLM),
                                              &SecurityPackage);
  if(status != SEC_E_OK)
    return CURLE_NOT_BUILT_IN;
```
In the case just described, QuerySecurityPackageInfo actually returns SEC_E_SECPKG_NOT_FOUND. I think that error code at least should be mapped to a more appropriate curl error code, or perhaps extra logging would be enough. Presumably the same change needs to apply to the other *_sspi.c files as well.

### I expected the following

curl should report a less misleading error message for the situation described.

### curl/libcurl version

curl 7.70.1-DEV (x86_64-w64-mingw32) libcurl/7.70.1-DEV Schannel
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI

### operating system

Windows 10

**Comment by bagder** [comment]
You're not using this curl 7.70.1 build there so maybe the build you're actually using has a different feature set built-in? The give-away is the `TCP_NODELAY set` message you see in the verbose output, because we removed that message in the 7.69.0 release (commit 1b6cfb9d2).

**Comment by wangp** [comment]
Ok, but the exact version doesn't really matter.

**Comment by bagder** [comment]
That's clearly the wrong return code to use there...
