### ISSUE TITLE
Saved ETag should not be removed for a 304 Not Modified response

### ISSUE THREAD

**Issue by hubgit** [curl/curl#5352]
### I did this

```sh
curl -vv --etag-save etag.txt --etag-compare etag.txt https://c19downloads.azureedge.net/downloads/data/data_latest.json -o data_latest.json
curl -vv --etag-save etag.txt --etag-compare etag.txt https://c19downloads.azureedge.net/downloads/data/data_latest.json -o data_latest.json
curl -vv --etag-save etag.txt --etag-compare etag.txt https://c19downloads.azureedge.net/downloads/data/data_latest.json -o data_latest.json
```

1. The first request (with `If-None-Match: ""`) received a 200 response. The value of the `ETag` response header was saved to `etag.txt`.
2. The second request (with `If-None-Match: "0x8D7F1D7257C74C5"`) received a 304 response. There was no `ETag` response header and **the contents of `etag.txt` was deleted**.
3. The first request (with `If-None-Match: ""`) received a 200 response. The value of the `ETag` response header was saved to `etag.txt`.

### I expected the following

1. The first request (with `If-None-Match: ""`) receives a 200 response. The value of the `ETag` response header is saved to `etag.txt`.
2. The second request (with `If-None-Match: "0x8D7F1D7257C74C5"`) receives a 304 response. As there's no `ETag` response header **the contents of `etag.txt` should remain unchanged**.
3. The third and subsequent requests (with `If-None-Match: "0x8D7F1D7257C74C5"`) will receive the same 304 response until the content changes.

### curl/libcurl version

```
curl 7.70.0 (x86_64-apple-darwin19.4.0) libcurl/7.70.0 SecureTransport zlib/1.2.11
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

### operating system

```
Darwin droid 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

**Comment by hubgit** [comment]
Closing as it seems the server isn't following [the spec for "304 Not Modified" responses](https://tools.ietf.org/html/rfc7232#section-4.1):

> The server generating a 304 response MUST generate any of the
   following header fields that would have been sent in a 200 (OK)
   response to the same request: Cache-Control, Content-Location, Date,
   ETag, Expires, and Vary.

**Comment by hubgit** [comment]
However, it can probably be implied that a 304 Not Modified response to a request with an `If-Non-Match` header would have included the same `ETag `header as the original response, if cURL did want to work around this behaviour.

**Comment by bagder** [comment]
Probably, yes. But then as you say this server violates a protocol MUST so I'm not personally going to spend a lot of effort trying to be friends with it. It could just as well fail in 22 other ways too if it can't follow the spec...

**Comment by hubgit** [comment]
That's fair enough - I've created [a bug report for the missing ETag header](https://developercommunity.visualstudio.com/content/problem/1021754/304-not-modified-response-must-also-contain-the-or.html).
