### ISSUE TITLE
CURLM_RECURSIVE_API_CALL ERROR

### ISSUE THREAD

**Issue by dangvohoanganhvn** [curl/curl#5354]
I am working with curl lib 7.64.1 for HTTP project. In this project, I use many POST/GET requests to get a small response (JSON strings) at the same time or new requests can be added when other requests are downloaded and callback finish. However, when I call **curl_multi_add_handle** sometime curllib return a **CURLM_RECURSIVE_API_CALL** ERROR and I retry add it again then everything is OK and sometimes it still remains returning **CURLM_RECURSIVE_API_CALL ERROR**. I don't call curl_multi_add_handle in any curl callback (write, read,..). Why did I get this error code? Please help me to solve this problem. Thanks

FYI,
curl/libcurl version 7.64.1
operating system: IOS and ANDROID

**Comment by bagder** [comment]
`CURLM_RECURSIVE_API_CALL ERROR` is returned when you call libcurl functions from within libcurl callbacks. We don't support doing that.

**Comment by dangvohoanganhvn** [comment]
No, as I mentioned above I don't call curl_multi_add_handle in any curl callback (write, read,..). I ran a debug of this return code and found that is not called from any callback. Do I misunderstand "within libcurl callbacks" mean?

**Comment by bagder** [comment]
Without more details from you, I can't do much more. That's what the return code means and I just browsed through the code to see if there could be a case that violates that contract but I couldn't spot any. I have no way to reproduce your problem. Maybe you've run into a bug we already fixed?

**Comment by dangvohoanganhvn** [comment]
Well, I have 1 thread for calling curl_multi_add_handle and other thread calls perform and check which easy handle is finish and callback to the upper layer. (When I want to download via a request, I will create a easy handle and add it to multi_curl). Actually I don't call curl_multi_add_handle in a callback function of curllib.

**Comment by bagder** [comment]
I trust you're protecting the handle accesses with a mutex or something then so you don't risk actually using the same handles simultaneously in two threads?

**Comment by dangvohoanganhvn** [comment]
yes, I have used multi handle in many threads. btw, I found that the function curl_set_in_callback is called when a callback is executed, At this time, how can I add a new easy handle to multi handle?

**Comment by bagder** [comment]
How can you get the mutex for the multi handle in thread A if libcurl is using it to call a callback in thread B?

**Comment by dangvohoanganhvn** [comment]
I have a class containing multi_handle and allowing another thread create new easy_handle and add it into multi_handle, and I use mutex to lock when call multi_perform,multi_wait,... ( this mutex is also used when add another easy handle).

**Comment by bagder** [comment]
Thread B that does the callback owns the mutex when multi_perform runs, right? So thread A can't add a handle during that time since it'll be waiting for the mutex to get released by thread B.

**Comment by dangvohoanganhvn** [comment]
Let me summarize my code for you.
I have a class download pool ( single tone class) and from another class/thread I call AddRequest in this class to add a new handle to multi_handle and it returns CURLM_RECURSIVE_API_CALL.

class downloadpool{
    CURLM *multi_handle;
    std::mutex _mutex;
    std::thread *_thread;

    //function
    void Run(){

        while (true){
            std::lock_guard<std::mutex> guard(_mutex);
            curl_multi_perform(multi_handle, &still_running);
            
            //check result 
            curl_multi_wait(multi_handle, nullptr, 0, MAX_WAIT_SECS, &numfds);

            //check result
            CheckEvent();

            //continue
        }
    }

    void CheckEvent(){
        //process result via curl_multi_info_read
        //remove handle if download finish, etc...
    }

public:
    void AddRequest(std::shared_ptr<Request> request){
        std::lock_guard<std::mutex> guard(_mutex);

        // I create easy_handle in Request class, init, set some callback function, etc...
        curl_multi_add_hanle(multi_handle, request->GetEasyHandle());
    }
}

**Comment by bagder** [comment]
That looks fine, as then you can't call `add_handle` while a libcurl callback is called since the mutex is already held then. So we're back to square one.

**Comment by dangvohoanganhvn** [comment]
thanks for your fast and enthusiastic responses, after reprocessing multithread flow, it seen to work well.

**Comment by bagder** [comment]
Thanks, then I guess this case can be closed again?
