### ISSUE TITLE
Cannot use #0 anywhere in file name or else will get failed writing body error

### ISSUE THREAD

**Issue by tarchive** [curl/curl#5360]
### I did this
```
curl -sS -o ./#0.png http://www.pngmart.com/files/3/Vector-PNG-File.png
   curl: (23) Failed writing body (0 != 2578)

curl -sS -o ./foo#0bar.png http://www.pngmart.com/files/3/Vector-PNG-File.png
   curl: (23) Failed writing body (0 != 1130)

```

### I expected the following
files to be saved as #0.png and foo#0bar.png

### curl/libcurl version

curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.1.1) libssh2/1.9.0 nghttp2/1.40.0
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets

### operating system

Linux Tower 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64 Intel(R) Xeon(R) CPU E5-2440 0 @ 2.40GHz GenuineIntel GNU/Linux

Also tested on windows 10 wsl Ubuntu with same result.

**Comment by jay** [comment]
What shell is this? Is that the actual command line? I would think # comments out the rest of the line, but that error suggests you are quoting it. If you quote it then curl will treat # as a metacharacter, refer to [`-o, --output <file>`](https://curl.haxx.se/docs/manpage.html#-o). Normally the numbers are 1+ . I've never seen `#0` used that is probably a bug.

curl -v -o "#0.png" www.google.com/foo
Warning: Failed to create the file www.google.com/foo.png: No such file or 
Warning: directory

Not reproducible in the latest curl. It looks like it was fixed (possibly inadvertently) between 7.68 and 7.69.1.

**Comment by tarchive** [comment]
Yes this is from bash command line on a [unraid system version 6.8.3](https://forums.unraid.net/topic/89462-unraid-os-version-683-available/)
Bash version: GNU bash, version 5.0.11(1)-release (x86_64-slackware-linux-gnu)

I didn't list every combination i tried to avoid cluttering and obscuring the initial post. But yes, i tried  quoting and other "tricks" i found from googling. The only way I was able to make it work was separating the # and 0.

For unraid, the packages are only updated when a new system update is released and I am at their latest stable version. 
If its not reproducible at the latest curl then this issue doesn't need to remain open here.
I will redirect these findings to the unraid forum for resolution.
Thank you.

**Comment by bagder** [comment]
Possibly related to #4812. I can repro with curl 7.68.0 on bash but not with curl 7.70.0.

**Comment by tarchive** [comment]
ugh I i swear i searched the repo and googled it too but there was not mention of "#0".
Apparently i need to work on that..

Yes badger, good find, i believe that is related.

I was running a bash script that i wrote a while ago which uses curl to download images and save the files as their unique URL. Recently a website used has changed its URL scheme and started including "#" within their URLs. Now it is very common to have "#0".."#9" within the file name. 
I wasn't aware of the "# number" usage when specifying -o until jay pointed that out so there may have been other ill effects that i have not noticed yet. "#0" was the only one to throw error to alert me.
I may have to rework the script to either ignore # numbers or just replace "#" with something else.

Thanks for checking with latest curl.

**Comment by jay** [comment]
You can use [`-g, --globoff`](https://curl.haxx.se/docs/manpage.html#-g)
