### ISSUE TITLE
libcurl compiled with openssl 1.1.1g failed because SSLv2_client_method not found

### ISSUE THREAD

**Issue by songday** [curl/curl#5378]
### I did this
I compiled libcurl with openssl-1.1.1g, when I check `config.log`, I found
```
configure:22924: checking for SSLv2_client_method
configure:22924: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers    -I/home/xiaozhi.zhang/openssl/include      -L/home/xiaozhi.zhang/openssl/lib   conftest.c -lssl -lcrypto -l:libssl-msxf.so.1.1 -l:libcrypto-msxf.so.1.1   -lz  >&5
/tmp/ccpCUOnO.o: In function `main':
conftest.c:(.text.startup+0x7): undefined reference to `SSLv2_client_method'
collect2: error: ld returned 1 exit status
```
in openssl1.1.1g, this method replaced with `SSLv23_client_method`
> https://www.openssl.org/docs/man1.1.1/man3/SSLv23_client_method.html

### I expected the following
compiled with openssl 1.1.1g

### curl/libcurl version
curl-7.70.0

[curl -V output]

### operating system
Linux s01cq-F1R18U1821-ai-app-200-12.host 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
`SSLv2_client_method` has been disabled in OpenSSL builds by default for a long time and curl's configure script has checked for it since years so that it won't try to use it.. It's a feature, not a bug.

**Comment by songday** [comment]
I see. thanks for your reply
