### ISSUE TITLE
curl_multi_setopt() API while using CURLMOPT_TIMERFUNCTION, is not re-trying on time-out

### ISSUE THREAD

**Issue by 0abhishek0** [curl/curl#5382]
### I did this

Here is the code snippet, which trying to get information from a server and on time-out expected for re-try instead of closing the connection.

  rc = curl_multi_setopt(
      request_handler->multi, CURLMOPT_TIMERFUNCTION, multi_timer_cb);
  GO_TO_ON_ASSERT(
      rc == CURLM_OK, "CURLMOPT_TIMERFUNCTION err\n", curl_setopt_error);

API definition for multi_timer_cb,
~~~c
static int multi_timer_cb(
    CURLM* multi,
    long timeout_ms,
    http2_request_handler_t* req_handler) {
  (void)multi; /* unused */

  if (req_handler == NULL) {
    RAD_PROXY_LOG_ERR("Request handler is null");
    return HTTP2_RH_ERROR;
  }

  ev_timer_stop(req_handler->loop, &req_handler->timer_event);
  if (timeout_ms >= 0) {
    ev_timer_set(&req_handler->timer_event, (ev_tstamp)timeout_ms / 1000., 0.);
    ev_timer_start(req_handler->loop, &req_handler->timer_event);
  }
  return 0;
}
~~~ 
### I expected the following
This code snippet trying to get information from a server and on time-out expected for re-try, which even works while using Curl version 7.58 but does not work since 7.62 & above; I tried even with Curl 7.70.0 and there too does not work.

### curl/libcurl version
Curl 7.62.1 & above does not work! Worked with Curl 7.58.0

[curl -V output]
curl 7.63.0 (arm-unknown-linux-uclibc) libcurl/7.63.0 OpenSSL/1.0.2q zlib/1.2.8 c-ares/1.7.4 nghttp2/1.41.0-DEV
Release-Date: 2018-12-12
Protocols: ftp ftps gopher http https smb smbs 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy 

### operating system
Linux Kernal 3.14.43 #1 SMP Mon May 11 23:00:49 EDT 2020 armv7l GNU/Linux

Note: Works when Build/Run the application on Standard Ubuntu or Cent OS installation! But not with Customised OS based on  Kernal # 3.14.43;

Developers,
Abhishek Ghosh <abhishek.ghosh@commscope.com> from Ruckus/CommScope
Govardhan Reddy <govi@fb.com> from Facebook

**Comment by bagder** [comment]
I'm sorry but this is not enough information for us to reproduce the problem, understand it and debug it. Can you perhaps provide a full source code example that shows the problem happen?

**Comment by 0abhishek0** [comment]
> I'm sorry but this is not enough information for us to reproduce the problem, understand it and debug it. Can you perhaps provide a full source code example that shows the problem happen?

Hi @bagder ,

Thanks for looking into this issue; Regarding code sharing, I am checking with my FB partner and will get back earliest.

Meantime attaching the Strace snippet for Non-Working scenario as captured while running in mentioned OS and working scenario as observed in Regular Linux installation ie. Ubuntu or CentOS ;

[Strace-NotWorkingScenario-CustomizedOS.log](https://github.com/curl/curl/files/4623165/Strace-NotWorkingScenario-CustomizedOS.log)
[Strace-WorkingScenario-Ubuntu-18.log](https://github.com/curl/curl/files/4623166/Strace-WorkingScenario-Ubuntu-18.log)
![Strace-Capture_Left-NonWorking__Right-Working](https://user-images.githubusercontent.com/11550143/81836301-e9322c80-9560-11ea-9f8a-16f04cf1192e.png)

**Comment by bagder** [comment]
Seeing an strace doesn't help me reproduce or understand the issue. Another way for you to help identify the culprit could possibly be to bisect until the offending commit.

And listen, and I want to emphasize this, **I do not want you to share your code**. I will not read or try to understand your code to hunt for this problem (that has been tried so many times before and that's almost always a hopeless task). I'm asking that you, based on what you've learned from the issue you see with your code, **write a new small and stand-alone application** that reproduces the issues. And that small source code can be shared with us and the world.

**Comment by 0abhishek0** [comment]
I understand and thank for being here. Shall provide the requested details here earliest.

**Comment by bagder** [comment]
Out of date, closing.
