### ISSUE TITLE
globbing with {} fails to download after first match

### ISSUE THREAD

**Issue by symulation** [curl/curl#5388]
Globbing using `{ }` in combination with `-O`  or `-o` (as per [https://ec.haxx.se/cmdline/cmdline-globbing](https://ec.haxx.se/cmdline/cmdline-globbing))  downloads appropriately for the first match but then prints every other match to standard out.  Globbing via `[ ]` works fine with `-O` and `-o`.  As soon as `{ }` are introduced it fails.

Seems to have been a problem before, as per [https://unix.stackexchange.com/questions/243134/curl-download-multiple-files-with-brace-syntax](https://unix.stackexchange.com/questions/243134/curl-download-multiple-files-with-brace-syntax)...

### I did this

`curl -O https://www.gutenberg.org/files/2701/2701-{0,h}.zip`

OR

`curl https://www.gutenberg.org/files/2701/2701-{0,h}.zip -o "file_#1.zip"`

### I expected:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  500k  100  500k    0     0   332k      0  0:00:01  0:00:01 --:--:--  332k
100  522k  100  522k    0     0   301k      0  0:00:01  0:00:01 --:--:--  301k
```

### I get:

 ```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  500k  100  500k    0     0   332k      0  0:00:01  0:00:01 --:--:--  332k
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

If text or HTML files are being requested instead of a binary file like the .zip in the example then it just starts dumping everything after the first hit to standard out. 

### curl/libcurl version

- `curl 7.70.0 (x86_64-apple-darwin19.4.0) libcurl/7.70.0 SecureTransport zlib/1.2.11`
- `curl 7.53.0 (x86_64-pc-linux-gnu) libcurl/7.53.0 OpenSSL/1.0.2k zlib/1.2.8 libssh2/1.7.0 nghttp2/1.14.1`

### operating system

- `Darwin SimpsonMBPro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
- `Linux cedar1.cedar.computecanada.ca 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 GNU/Linux`

**Comment by jzakrzewski** [comment]
I'm not quite sure, but I guess what's going on is the shell interaction. Some shells, like bash, expand the braces by themselves. That means that you command effectively becomes:
```curl -O https://www.gutenberg.org/files/2701/2701-0.zip https://www.gutenberg.org/files/2701/2701-h.zip```
To solve this problem try quoting like that:
```curl -O "https://www.gutenberg.org/files/2701/2701-{0,h}.zip"```

**Comment by jay** [comment]
I've submitted PRs to quote those URLs in the curl manpage and e-book.

**Comment by symulation** [comment]
Quotes work.  Thanks for the suggestion.

The PRs to update the manpage and e-book are appreciated.

**Comment by jay** [comment]
Thanks

**Comment by symulation** [comment]
Incidentally, this [Stack Exchange Issue](https://unix.stackexchange.com/questions/243134/curl-download-multiple-files-with-brace-syntax/586486#586486) has been updated to reflect this.

Thanks again.

**Comment by symulation** [comment]
Note that the quoting issue only arises with `{ }`.  I've never had a problem in BASH using only `[ ]`.
