### ISSUE TITLE
--tcp-fastopen not supported

### ISSUE THREAD

**Issue by TheGr33k** [curl/curl#5390]
### I did this

`curl --tcp-fastopen -L http://www.google.com`

### I expected the following

Success 

### I got this

curl: (55) Send failure: Operation not supported
 

### curl/libcurl version

```
curl 7.70.0 (x86_64-redhat-linux-gnu) libcurl/7.70.0 NSS/3.44 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.9.0 nghttp2/1.31.1
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL UnixSockets
```

### operating system

`Linux ns105856 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jay** [comment]
TCP fast open is not commonly used, it had some problems and I'm not surprised it would be disabled. See #3662. Probably we can't do anything about this.

**Comment by bagder** [comment]
@TheGr33k, what do you suggest curl should do about this? The "Operation not supported" is what your TCP stack returns...

**Comment by TheGr33k** [comment]
@bagder 

I would like to use the option to speedup curl requests.Is there a requirement that i am missing ?

**Comment by bagder** [comment]
You tell me. Do you have it enabled in your kernel?

**Comment by TheGr33k** [comment]
I forgot to enable tcp fast open in the kernel :man_facepalming:
