### ISSUE TITLE
Implement wget's --wait, --random-wait

### ISSUE THREAD

**Issue by jidanni** [curl/curl#5406]
curl could/should implement wget's

       --wait=seconds
           Wait the specified number of seconds between the
           retrievals... (I'm not talking about retries.)

       --random-wait
           Some web sites may perform log analysis to identify retriev...

Sure, curl has --limit-rate <speed>, but that's not the same.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by bagder** [comment]
Can you elaborate on your use case for these options?

**Comment by jidanni** [comment]
OK. Well for `--random-wait` my reason is the same as wget's (see their man page.)

And for `--wait`: a curl command might send a million requests. I want a
few seconds/minutes between each request, while testing, for me to make sure
nothing went nuts, on my end, the network, or the remote server.

Sure, I could make a shell script
```
for u in URL1 URL2 URL3...
do
        curl $u
        sleep 45
done
```

(But that might not always work the same as what we are hoping the single
curl run would do.)

**Comment by bagder** [comment]
Maybe a more interesting feature would be to implement support for the proposed [RateLimit HTTP headers](https://www.ietf.org/id/draft-polli-ratelimit-headers-02.html) and make sure curl can adhere to them.
