### ISSUE TITLE
Implement wget's --quota.

### ISSUE THREAD

**Issue by jidanni** [curl/curl#5407]
curl could/should implement wget's --quota.

And indeed make it total bytes fetched per this run combined, no matter what (unlike wget.)

Sure curl has

     --max-filesize <bytes>
          Specify  the  maximum  size  (in bytes) of a file to download.

But that is not a running tally of all bytes per this run.

Sure curl has

       -m, --max-time <seconds>
              Maximum time in seconds that you allow the whole operation
              to take. This is useful for preventing your batch jobs
              from hanging for hours due to slow networks or links going
              down.

So why not also a --max-bytes?

(Indeed, you might just go down the wget/wget2 manual page, implementing
into curl any other missing goodies.)

**Comment by bagder** [comment]
Can you elaborate on what ỳour use case for such an option is?

**Comment by jidanni** [comment]
Simply the same as curl's `--max-filesize`, but for the cases when we are downloading a set of files.

We don't allow junior to buy a Mercedes Benz, OK, but then our credit
card bill shows he instead purchased a thousand Volkswagens.

**Comment by jidanni** [comment]
To implement, simply increment (instead of resetting) the --max-filesize counter for new each file. 

For the "NOTE: The file size is not always known prior to download" case, simply add them to the total after each one is downloaded. (Mentioning this on the man page also.)

**Comment by jay** [comment]
wget has a recursive option that makes quota useful, but that is not in curl.

**Comment by bagder** [comment]
I also don't like "theoretical" use cases where we guess what features someone else *might* want to use at some point. If no such user can step forward and explain they want this feature and for what purpose, then it is probably not a feature worth working on right now.

**Comment by jidanni** [comment]
> wget has a recursive option that makes quota useful, but that is not in curl.

Yes, but from the curl man page
```
http://site.{one,two,three}.com
ftp://ftp.example.com/file[1-100].txt
ftp://ftp.example.com/file[001-100].txt
ftp://ftp.example.com/file[a-z].txt
http://example.com/archive[1996-1999]/vol[1-4]/part{a,b,c}.html
```
could easily result in the user getting more than what he bargained for. Thus just like he currently has a cap for one single file, he also wishes for a total cap.
