### ISSUE TITLE
CURL_LOCK_DATA_DNS threaded-shared-conn.c hangs

### ISSUE THREAD

**Issue by Fricker95** [curl/curl#5408]
### I did this
In _threaded-shared-conn.c_ from the examples, i added  CURL_LOCK_DATA_DNS to the curl share handle and the program hangs. I have tried to compile curl with --disable-threaded-resolver  and --enable-threaded-resolver both causes the same outcome.

### output

> Thread 0, gets http://www.example.com

> Thread 1, gets http://www.example.com

* Found bundle for host www.example.com: 0x7fa91e0045b0 [serially]
* Server doesn't support multiplex (yet)
* Hostname 'www.example.com' was found in DNS cache
*   Trying 93.184.216.34:80...
*   Trying 93.184.216.34:80...
* Connected to www.example.com (93.184.216.34) port 80 (#1)
* Connected to www.example.com (93.184.216.34) port 80 (#0)
> GET / HTTP/1.1
Host: www.example.com
Accept: */*

> GET / HTTP/1.1
Host: www.example.com
Accept: */*

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Age: 474184
< Cache-Control: max-age=604800
< Content-Type: text/html; charset=UTF-8
< Date: Mon, 18 May 2020 04:51:51 GMT
< Etag: "3147526947+gzip"
< Expires: Mon, 25 May 2020 04:51:51 GMT
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Server: ECS (sjc/4E74)
< Vary: Accept-Encoding
< X-Cache: HIT
< Content-Length: 1256
< 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Age: 348481
< Cache-Control: max-age=604800
< Content-Type: text/html; charset=UTF-8
< Date: Mon, 18 May 2020 04:51:51 GMT
< Etag: "3147526947+gzip"
< Expires: Mon, 25 May 2020 04:51:51 GMT
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Server: ECS (sjc/4E44)
< Vary: Accept-Encoding
< X-Cache: HIT
< Content-Length: 1256
< 

### curl/libcurl version
Occurs in both 7.70.0 & 7.69.0:

- curl 7.69.0 (x86_64-apple-darwin19.3.0) libcurl/7.69.0 SecureTransport zlib/1.2.11 libidn2/2.3.0 nghttp2/1.40.0
Release-Date: 2020-03-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTP2 IDN IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

- curl 7.70.0 (x86_64-apple-darwin19.4.0) libcurl/7.70.0 openssl/1.1.1d zlib/1.2.11 nghttp2/1.40.0
Release-Date: 2020-04-29
Protocols: DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP 
Features: SSL IPv6 UnixSockets libz NTLM NTLM_WB TLS-SRP HTTP2 HTTPS-proxy ( w/ & w/o AsynchDNS)

### operating system
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
"Added" means that you also share connection cache, right? That one is already a known bug: #4915  ...

**Comment by Fricker95** [comment]
Yes, ok thank you! Should I close this issue?

**Comment by bagder** [comment]
If the problem goes away when you don't share the connection cache anymore, then yes this is then a duplicate.
