### ISSUE TITLE
Potential security issue in lib/ftp.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [curl/curl#5412]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

3 instances of this defect were found in the following locations:
---
**Instance 1**
File : `lib/ftp.c` 
Function: `Curl_GetFTPResponse` 
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/ftp.c#L412
Code extract:

```cpp
    }
    else if(result & CURL_CSELECT_IN) {
      infof(data, "Ctrl conn has data while waiting for data conn\n");
      Curl_GetFTPResponse(&nread, conn, &ftpcode); <------ HERE

      if(ftpcode/100 > 3)
```

**How can I fix it?** 
Correct reference usage found in `lib/ftp.c` at line `3380`.
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/ftp.c#L3380
Code extract:

```cpp

      pp->response = Curl_now(); /* timeout relative now */

      result = Curl_GetFTPResponse(&nread, conn, &ftpcode); <------ HERE
      if(result)
        return result;
```

---
**Instance 2**
File : `lib/ftp.c` 
Function: `Curl_inet_ntop` 
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/ftp.c#L1060
Code extract:

```cpp
      break;
#endif
    default:
      Curl_inet_ntop(sa->sa_family, &sa4->sin_addr, hbuf, sizeof(hbuf)); <------ HERE
      break;
    }
```

**How can I fix it?** 
Correct reference usage found in `lib/connect.c` at line `650`.
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/connect.c#L650
Code extract:

```cpp
#ifdef ENABLE_IPV6
    case AF_INET6:
      si6 = (struct sockaddr_in6 *)(void *) sa;
      if(Curl_inet_ntop(sa->sa_family, &si6->sin6_addr, <------ HERE
                        addr, MAX_IPADR_LEN)) {
        unsigned short us_port = ntohs(si6->sin6_port);
```

---
**Instance 3**
File : `lib/ftp.c` 
Function: `Curl_printable_address` 
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/ftp.c#L3453
Code extract:

```cpp
                 int port)
{
  char buf[256];
  Curl_printable_address(ai, buf, sizeof(buf)); <------ HERE
  infof(conn->data, "Connecting to %s (%s) port %d\n", newhost, buf, port);
}
```

**How can I fix it?** 
Correct reference usage found in `lib/socks.c` at line `785`.
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/socks.c#L785
Code extract:

```cpp
      return CURLE_COULDNT_RESOLVE_HOST;
    }

    if(Curl_printable_address(hp, dest, sizeof(dest))) { <------ HERE
      size_t destlen = strlen(dest);
      msnprintf(dest + destlen, sizeof(dest) - destlen, ":%d", remote_port);
```

**Comment by siva-msft** [comment]
@bagder what do you think about instance 2?
In curl/lib/ftp.c; line 412 in 17b1405
`Curl_GetFTPResponse(&nread,` conn, &ftpcode);`

**Comment by bagder** [comment]
I already added a `(void)` in front of that function call to mark the not-using-the-returncode as deliberate. I don't think there's an issue there.

**Comment by siva-msft** [comment]
Okay, and how about this one?
`Curl_inet_ntop(sa->sa_family, &sa4->sin_addr, hbuf, sizeof(hbuf));`

**Comment by bagder** [comment]
I missed those. There seems to be two calls in ftp.c and one in if2ip.c that we should fix...
