### ISSUE TITLE
Potential security issue in lib/socks.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [curl/curl#5415]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `lib/socks.c` 
Function: `Curl_printable_address` 
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/socks.c#L283
Code extract:

```cpp
    if(dns)
      hp = dns->addr;
    if(hp) {
      Curl_printable_address(hp, buf, sizeof(buf)); <------ HERE

      if(hp->ai_family == AF_INET) {
```

**How can I fix it?** 
Correct reference usage found in `lib/socks.c` at line `785`.
https://github.com/curl/curl/blob/17b1405b20f7ea916995c224992b0ec592f73039/lib/socks.c#L785
Code extract:

```cpp
      return CURLE_COULDNT_RESOLVE_HOST;
    }

    if(Curl_printable_address(hp, dest, sizeof(dest))) { <------ HERE
      size_t destlen = strlen(dest);
      msnprintf(dest + destlen, sizeof(dest) - destlen, ":%d", remote_port);
```

**Comment by bagder** [comment]
Should be addressed by #5418

**Comment by jay** [comment]
@siva-msft is this your robot?

**Comment by bagder** [comment]
This is https://github.com/microsoft/MonocleAI, and I've given it permission to create these issues as a test to see if it is indeed helpful to us.

**Comment by bagder** [comment]
This issue was addressed by #5418, already landed

**Comment by siva-msft** [comment]
> @siva-msft is this your robot?

@jay Hi, I work in the Monocle AI Project.

**Comment by jay** [comment]
I wanted to know why it was opening so many issues but @badger has since explained. Also curious since we have a process for actual security issues not to post them on the issue tracker. IMO the "Potential security issue" prefix for things like this is overkill.

**Comment by bagder** [comment]
> IMO the "Potential security issue" prefix for things like this is overkill.

I agree and I've mentioned this in private feedback. *All* bugs are potential security issues if the circumstances are "right" (or maybe they are wrong?).

**Comment by siva-msft** [comment]
Thank you for letting me know. Your feedback is very important. We are implementing the changes on our end to improve the service and will certainly keep these points in mind.
