### ISSUE TITLE
Add GitHub issues/new/choose Bug and Feature Request divider

### ISSUE THREAD

**Issue by jidanni** [curl/curl#5425]
https://github.com/Perl/perl5/issues/new/choose is an example of a GitHub chooser page that could be added to curl's GitHub, to help assist the division of Bugs and Feature Requests, e.g., see https://github.com/curl/curl/issues/5406#issuecomment-629862293 .
This would be in addition to  https://curl.haxx.se/docs/todo.html .

**Comment by bagder** [comment]
Why? Filling up the issue tracker with ideas is not helpful. Ideas are easy and plentiful. We don't lack ideas. Never did.

**Comment by bagder** [comment]
This is not a curl issue. This is a discussion or meta-question about the project or perhaps the management of the project. If you want to argue for this and see what people think and maybe push for a change, I think the libcurl mailing list is the right venue.

**Comment by jidanni** [comment]
You could have two separate directories here on GitHub, one for bugs and  one for feature requests. Yes,  using the current file for the latter is great too.
