### ISSUE TITLE
Finally add --dry-run

### ISSUE THREAD

**Issue by jidanni** [curl/curl#5426]
In
https://stackoverflow.com/questions/6180162/echo-curl-request-header-body-without-sending-it and
https://stackoverflow.com/a/47694977/1118719
https://stackoverflow.com/a/36016711/1118719
we see users needing to make connections (even if just to localhost) to see what curl is actually sending. Imagine that, the only way to see what I am about to send is to send something. But then I already sent it. (OK, first 'send it into some sort of _condom_', and then examine what is in that _condom_. But must it be that way?)

But one day one might only get **only one** chance to send exactly the right
request(s) to a certain site. Any mistakes might make the difference of
downloading the Pentagon Papers vs. getting the authorities knocking
on one's door. (And no, "Just adjust the site name when you are finally
happy with the _condom_'s contents" doesn't give one full confidence.)

That's why curl needs simple concepts like:
```
WWW::Mechanize::Cookbook(3pm)
   See what will be sent without actually sending anything
           $mech->add_handler("request_send", sub { shift->dump; exit; });
           $mech->get("http://www.example.com");
```
(in the same spirit of:)

```
apt-get --print-uris --simulate --just-print --dry-run --no-act
```
and
```
rsync --dry-run #but alas no --just-print, --print-uris
```
Well, at least add it to https://curl.haxx.se/docs/todo.html . Thanks.

**Comment by emilengler** [comment]
I can fully understand you and would give a yes vote on this concept. I'm just a bit curious on how this should be handled on the technical point of view. Keep in mind that curl is just a tool which gets the best out of libcurl, which does the magic behind the stuff. My idea would be too add a new CURLOPT to libcurl and write all the following output to the write function (where usually the site content comes).

**Comment by jidanni** [comment]
I think it is great that you are working on this. All I know is "please give the user a way to see what would be sent (headers, URIs, or both) without sending anything."

**Comment by bagder** [comment]
If anyone would like to work on an implementation, I would recommend using `CURLOPT_OPENSOCKETFUNCTION` to setup a "private" socket, possibly a socketpair/pipe and return `CURL_SOCKOPT_ALREADY_CONNECTED`  from the callback. Then libcurl won't have to be touched to provide this feature.

**Comment by lindhe** [comment]
Is this included in a released version of `curl`? If so, which one?

**Comment by MarcelRaad** [comment]
@lindhe You can see that by looking at the tags of the commit this issue was closed in: https://github.com/curl/curl/commit/6c889a0dd1c36d12c0c072eb04aa1ea68632832f

**Comment by MarcelRaad** [comment]
@lindhe it's still in TODO: https://github.com/curl/curl/blob/master/docs/TODO

**Comment by sickcodes** [comment]
curl `--head` or `-I` is effectively a dry-run as it contains `Content-Length` & `Response Code`.

```console
[user@hostname ~]$ curl -I 'https://cve.mitre.org/data/downloads/allitems.csv.gz'
HTTP/1.1 200 OK
Date: Fri, 14 Jan 2022 08:45:49 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains
X-Frame-Options: SAMEORIGIN
Last-Modified: Fri, 14 Jan 2022 08:30:09 GMT
ETag: "12345-123123123123"
Accept-Ranges: bytes
Content-Length: 21509623
X-XSS-Protection: 1; mode=block
Content-Type: text/csv
Content-Encoding: x-gzip
```

If you want an offline dry-run, or you don't care about the error response, you can set resolver to something incorrect `--resolve host:80:127.0.0.999`:
```bash
curl --resolve '*:80:127.0.0.1' --resolve '*:443:127.0.0.1' 'https://github.com'
```

```console
[user@hostname ~]$ curl --resolve '*:80:127.0.0.1' --resolve '*:443:127.0.0.1' google.com
curl: (7) Failed to connect to google.com port 80 after 0 ms: Connection refused
```

```console
[user@hostname ~]$ curl --resolve '*:80:127.0.0.1' --resolve '*:443:127.0.0.1' https://google.com
curl: (7) Failed to connect to google.com port 443 after 0 ms: Connection refused
```

This tells curl to use 127.0.0.1 as the resolver for wildcard any domain, for both port 80 and 443, which is the fastest way I can envision, other than unplugging the internet

**Comment by jidanni** [comment]
- I don't want to alert the site that I am up to no good until I have my hack perfected.
- Why can't I simply see what this will generate?
```
curl \
--request PUT \
--header "Accept: application/vnd.github.v3+json" \
https://api.github.com/repos/jidanni/submission-cleaner/contents/riskfix \
--data ...
```

**Comment by bagder** [comment]
If you want to discuss development of new curl features, please use the dedicated mailing lists. Very few people will see or care about comments in old closed issues such as this.

**Comment by jidanni** [comment]
It's not that urgent.

Anyway maybe on the man page add an example of piping one curl into another, one sending the request, one getting it and then putting it on STDOUT, all without any Internet connection.
