### ISSUE TITLE
http-post.c example

### ISSUE THREAD

**Issue by 93873637** [curl/curl#5427]
### curl/libcurl version

[curl -V output]

**Comment by 93873637** [comment]
when i replace url="https://appr.tc/join/2125115795", fields=""
it errors:

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

what's the problem?

**Comment by bagder** [comment]
That's a server error, we cannot tell why that happens. Perhaps it found something unexpected in the post. This is not a curl issue.
