### ISSUE TITLE
Error SSL connection

### ISSUE THREAD

**Issue by southernedge** [curl/curl#5430]
Hello!

I can not download a file on **Windows 7**. Obviously the problem in the certificate of the site.

I use the following command to test
curl -v --insecure **https://www.mameworld.info/mameinfo/download/Mameinfo0221.zip**  -o file.html 2>_log
Curl version is **7.70.0.**

Using key "**--insecure**" not give any result. 
I expect that the file must precisely be downloaded using "--insecure" key.

What could be the problem and how to get around it?

Many thanks for any help!

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 35.169.251.179:443...
* Connected to www.mameworld.info (35.169.251.179) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [100 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4608 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=mameworld.info
*  start date: Mar  6 00:00:00 2020 GMT
*  expire date: Jun  4 23:59:59 2020 GMT
*  issuer: C=US; ST=TX; L=Houston; O=cPanel, Inc.; CN=cPanel, Inc. Certification Authority
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x9229a0)
} [5 bytes data]
> GET /mameinfo/download/Mameinfo0221.zip HTTP/2
> Host: www.mameworld.info
> user-agent: curl/7.70.0
> accept: */*
> 

{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
< HTTP/2 403 
< cache-control: private, no-cache, no-store, must-revalidate, max-age=0
< pragma: no-cache
< content-type: text/html
< content-length: 1228
< date: Tue, 19 May 2020 14:41:45 GMT
< server: LiteSpeed
< alt-svc: quic=":443"; ma=2592000; v="43,46", h3-Q043=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q050=":443"; ma=2592000, h3-25=":443"; ma=2592000, h3-27=":443"; ma=2592000
< 
{ [1050 bytes data]

100  1228  100  1228    0     0   1668      0 --:--:-- --:--:-- --:--:--  1668
100  1228  100  1228    0     0   1668      0 --:--:-- --:--:-- --:--:--  1668
* Connection #0 to host www.mameworld.info left intact

### In any case, I add the contents of the downloaded file.

<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
<title> 403 Forbidden
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">403</h1>
<h2 style="margin-top:20px;font-size: 30px;">Forbidden
</h2>
<p>Access to this resource on the server is denied!</p>
</div></div><div style="color:#f0f0f0; font-size:12px;margin:auto;padding:0px 30px 0px 30px;position:relative;clear:both;height:100px;margin-top:-101px;background-color:#474747;border-top: 1px solid rgba(0,0,0,0.15);box-shadow: 0 1px 0 rgba(255, 255, 255, 0.3) inset;">
<br>Proudly powered by  <a style="color:#fff;" href="http://www.litespeedtech.com/error-page">LiteSpeed Web Server</a><p>Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.</p></div></body></html>

**Comment by jzakrzewski** [comment]
If I understand all that correctly, curl works just fine but the server returns HTTP 403 code. That means the server is denying you access to that file. I did a quick test and it seems that the server is inspecting the user-agent header. So that actually worked:
```
curl -v --insecure https://www.mameworld.info/mameinfo/download/Mameinfo0221.zip -o file.zip -H "user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
```

**Comment by bagder** [comment]
I'd say that means case closed!

**Comment by southernedge** [comment]
Thank you for quick responses!
It works on win10, **but not working on win7**! Earlier, I wrote that the tests were made on win7.
