### ISSUE TITLE
querying domain whois servers with curl fails

### ISSUE THREAD

**Issue by sudheer1994** [curl/curl#5437]
i get response as "Neither object nor interpretation control keyword found"

            $query_begin = "";
		$query_end = "\r\n";
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $whoisserver);
		curl_setopt($ch, CURLOPT_PORT, 43);
		curl_setopt($ch, CURLOPT_PROXY, 'http://1.2.3.4:22225');
		curl_setopt($ch, CURLOPT_PROXYUSERPWD, 'user:password');
		curl_setopt($ch, CURLOPT_HTTPPROXYTUNNEL, 1); 
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_TIMEOUT, 60);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $query_begin.$domain.$query_end);
		$data = curl_exec ($ch);

Anyone please help me with this code.

**Comment by jay** [comment]
See #732.

**Comment by sudheer1994** [comment]
@jay thanks for pointing me out and i already saw that but didnt get any help with it and unable to resolve it. Can you please help me with the code.

**Comment by sudheer1994** [comment]
i admit that fsockopen work from #732 but i dont know how to use proxy with fsockopen.

and fsockopen request is as follows:

```
$port = 43;
$timeout = 10;
$fp = @fsockopen($whoisserver, $port, $errno, $errstr, $timeout) or die("Socket Error " . $errno . " - " . $errstr);

fputs($fp, $domain . "\r\n");
$out = "";
while(!feof($fp)){
    $out .= fgets($fp);
}
fclose($fp);
```

**Comment by bagder** [comment]
That's unfortunate for you, but not really a curl issue. curl is made to do internet transfers using any of the **25** supported protocols. WHOIS is not one of those. You can *probably* find a web service somewhere with an interface to do whois lookups and then curl could do those, but for plain whois lookups curl is not really a suitable tool.

**Comment by sudheer1994** [comment]
@bagder Thanks for correcting me. Now i have to look for other possibilities.

**Comment by jay** [comment]
phphelp.com or r/phphelp
