### ISSUE TITLE
ngtcp2_crypto_read_write_crypto_data() causes error in build

### ISSUE THREAD

**Issue by xquery** [curl/curl#5444]
func signature in ngtcp2 has changed which causes curl build (when building in ngtcp2 support) to fail.

vquic/ngtcp2.c:617:6: error: too many arguments to function ‘ngtcp2_crypto_read_write_crypto_data’
   if(ngtcp2_crypto_read_write_crypto_data(tconn, qs->ssl, crypto_level, data,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

guessing the fix is updating func invoke in vquic/ngtcp2.c

**Comment by xquery** [comment]
this is the relevant recent commit to ngtcp2 

https://github.com/ngtcp2/ngtcp2/commit/15833a15a1507d9cefa757a0ae47473aa95cd01e

**Comment by Lekensteyn** [comment]
This will be fixed by PR #5443.
