### ISSUE TITLE
Handshaking in HTTPS fails with error: SSL connect error in Windows

### ISSUE THREAD

**Issue by bhupeshpant19jan** [curl/curl#5456]
### Scenario:  Mutual auth
My request to HTTPS server is failing with the following errors

```
[25-05-2020 01-40-41Z] Level:Error Tag:AttestatationClientLib attest::curl::SendRequest:335 Failed sending curl request with error:SSL connect error
[25-05-2020 01-40-41Z] Level:Error Tag:AttestatationClientLib AttestationClientImpl::sendHttpRequest:453 Failed to send http request with error:Failed sending curl request with error:SSL connect error
[25-05-2020 01-40-41Z] Level:Error Tag:AttestatationClientLib AttestationClientImpl::sendAttestationRequest:243 Failed to send http request with error:Failed sending curl request with error:SSL connect error
[25-05-2020 01-40-41Z] Level:Error Tag:AttestatationClientLib AttestationClientImpl::Attest:100 Failed to send attestation request with error:Failed sending curl request with error:SSL connect error
[25-05-2020 01-40-41Z] Level:Error Tag:AttestatationClient Client::AttestAndDecrypt:82 Failed to attest with error:-7 description:Failed sending curl request with error:SSL connect error
```

Extended debug logging

```
* schannel: sending next handshake data: sending 4067 bytes...
* schannel: SSL/TLS connection with sharedwus.us.test.attest.azure.net port 443 (step 2/3)
* schannel: failed to receive handshake, SSL/TLS connection failed
* Closing connection 0
* schannel: shutting down SSL/TLS connection with sharedwus.us.test.attest.azure.net port 443
* schannel: clear security context handle
```

Basically, I am observing this failure when trying to do the handshake, the Windows machine for some reason is asking for the PIN to continue. If we put the correct pin the HTTPs communication is successful but in the machine that doesn't have the PIN setup it is failing, since we don't know what pin to use.

![image](https://user-images.githubusercontent.com/5937254/82844375-10f48f00-9e95-11ea-9929-383ea698e4f1.png)

I know the windows use this pin to contact the TPM and what I don't understand in this whole flow why do we need access to TPM?
Is this when trying to do root chain validation of the cert or storing cert in TPM?  We haven't seen this behavior in the earlier version of the CURL

Please note: we are running this code in VMs that has vTPM enabled in it.
Is there a flag that can bypass this check or contacting TPM?

**Comment by bagder** [comment]
What curl version are you using? Are you using the curl too? If so, what does your command line look like?

**Comment by bhupeshpant19jan** [comment]
Hi @bagder , Seems like this is happening only for the specific server endpoint. I am assuming that the server might have requested for the client cert as well that's why during the handshake our lib is trying to send the cert and hence trying to access the TPM. This is my guess. 
Btw, Is there a flag that I can use to disable sending the client cert? I know sending the client cert is not mandatory.

curl version:  **7.58.0**

**Comment by jay** [comment]
The client certificate is sent automatically if the Windows SSL backend is used. Refer to #2262 and [TODO 15.3](https://curl.haxx.se/docs/todo.html#Add_option_to_disable_client_cer). We don't have a way to disable this currently. I was not aware that Windows shows an interactive prompt if a PIN is required. Does the prompt time out at all, like if you ignore it for a few minutes will it go away on its own?

**Comment by bhupeshpant19jan** [comment]
@jay the interactive prompt doesn't go away at least in 2-3 minutes. I haven't waited for any longer and I can't even wait for any longer. Basically if you see the whole handshake is in wait state until I provide pin and that means whole https request is in wait.

I am only guessing, that any longer wait would only result in timeout for handshaking/

**Comment by bhupeshpant19jan** [comment]
UPDATED THE POST WITH SPECIFYING THE SCENARIO OF **MUTUAL AUTH**

**Comment by jay** [comment]
> I am only guessing, that any longer wait would only result in timeout for handshaking/

Makes sense.

> Is a way to send empty or null cert for the client? I know the server will not regard this as a failure.

There is, please refer to the issue I linked to earlier. Currently we don't have a way to do this. I'm not opposed to it just nobody has done it yet.

**Comment by bhupeshpant19jan** [comment]
@jay, 
I think I am looking for something like below from curl lib. The below information is from WinHTTP library
Link: [https://docs.microsoft.com/en-us/windows/win32/winhttp/ssl-in-winhttp#optional-client-ssl-certificates](https://docs.microsoft.com/en-us/windows/win32/winhttp/ssl-in-winhttp#optional-client-ssl-certificates)


> Starting in Windows Server 2008 and Windows Vista, the WinHttp API supports optional client certificates. When the server requests a client certificate, WinHttpSendRequest, or WinHttpRecieveResponse returns an ERROR_WINHTTP_CLIENT_AUTH_CERT_NEEDED error. If the server requests the certificate, but does not require it, the application can specify this option to indicate that it does not have a certificate. The server can choose another authentication scheme or allow anonymous access to the server. The application specifies the WINHTTP_NO_CLIENT_CERT_CONTEXT macro in the lpBuffer parameter of WinHttpSetOption as shown in the following code example. 

```
BOOL fRet = WinHttpSetOption ( hRequest,
                               WINHTTP_OPTION_CLIENT_CERT_CONTEXT,
                               WINHTTP_NO_CLIENT_CERT_CONTEXT,
                               0);
```

> If the WINHTTP_NO_CLIENT_CERT_CONTEXT is set, and the server still requires a client certificate, it may send a 403 HTTP status code. For more information, see the WINHTTP_OPTION_CLIENT_CERT_ISSUER_LIST option.

**Comment by bhupeshpant19jan** [comment]
from the earlier thread you pointed out, I concluded that in curl if the server is with mutual auth/ asking for client cert, the curl will automatically pick up the cert and share it with the server.  This is the default behavior and we cannot ignore it.
But can we try to  either,
1. Pass null cert 
2. specific the CA path, which will point to a dir that doesn't contain any cert and therefore the client will send the empty cert? Somethig like **CURLOPT_CAINFO**

> https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html

**Comment by jay** [comment]
As I [described](https://github.com/curl/curl/issues/2262#issuecomment-360581368) in the issue I referenced, I think [ISC_REQ_USE_SUPPLIED_CREDS](https://docs.microsoft.com/en-us/windows/win32/secauthn/performing-authentication-using-schannel) would have to be set. Try this

~~~diff
diff --git a/lib/vtls/schannel.c b/lib/vtls/schannel.c
index f149978..b205b67 100644
--- a/lib/vtls/schannel.c
+++ b/lib/vtls/schannel.c
@@ -886,7 +886,7 @@ schannel_connect_step1(struct connectdata *conn, int sockindex)
   /* setup request flags */
   BACKEND->req_flags = ISC_REQ_SEQUENCE_DETECT | ISC_REQ_REPLAY_DETECT |
     ISC_REQ_CONFIDENTIALITY | ISC_REQ_ALLOCATE_MEMORY |
-    ISC_REQ_STREAM;
+    ISC_REQ_STREAM | ISC_REQ_USE_SUPPLIED_CREDS;
 
   /* allocate memory for the security context handle */
   BACKEND->ctxt = (struct curl_schannel_ctxt *)
~~~

**Comment by jay** [comment]
> curl version: **7.58.0**

> Is a way to send empty or null cert for the client? I know the server will not regard this as a failure.

curl 7.60.0+ supports [CURLOPT_SSLCERT ](https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERT.html) for schannel.

**Comment by jay** [comment]
This issue is already noted in the TODO.

**Comment by bhupeshpant19jan** [comment]
Thanks @jay for the updates.

**Comment by bhupeshpant19jan** [comment]
@jay , do you have any item id or work item to track that?

**Comment by jay** [comment]
> @jay , do you have any item id or work item to track that?

[TODO 15.3](https://curl.haxx.se/docs/todo.html#Add_option_to_disable_client_cer)

**Comment by jay** [comment]
@hiic this issue was closed over a year ago. In the future please open a new discussion if you have a question, or open an issue if you are reporting a bug.

> 4\. == Info:  : schannel: failed to receive handshake, SSL/TLS connection failed

That's usually caused by the server. The server closed the connection either gracefully or not. There's a slight possibility that it's not a server issue but is instead a network issue or a client side resource issue. In any case it's not a curl issue. You can use Wireshark to investigate further. Also, please make sure your code follows the [thread safety guidelines](https://curl.se/libcurl/c/threadsafe.html).
