### ISSUE TITLE
Download/Upload to DFS SMB/CIFS share not working

### ISSUE THREAD

**Issue by quercus-robur** [curl/curl#5467]
Uploading to and downloading from a Windows DFS (Distributed File System) share does not work.
Plain SMB/CIFS share access no problem.

mount -t cifs, smbget and smbclient working. DFS access adaptions had to be done.

### I did this
Download
`curl -u '<domain>\<username>' smb://<DomainName>/<NameSpace>/<Share>/<file>`
curl: (9) Access denied to remote resource

Upload
`curl --upload-file <file> -u '<domain>\<username>' smb://<DomainName>/<NameSpace>/<Share>/<file>`
curl: (9) Access denied to remote resource

### I expected the following
A successful download/upload.

### curl/libcurl version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system
Linux <hostname> 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Comment by bagder** [comment]
curl only supports SMBv1 while that's typically not what servers have enabled these days. Are you sure this server you try supports SMBv1 accesses?

**Comment by quercus-robur** [comment]
Yes, SMB v1 enabled and active.
Output of mount:
//domain.corp/Filer/Share/ on /mnt/backup2 type cifs (rw,relatime,**vers=1.0**,...

nslookup domain.corp translates to the two domain controllers and not the two DFS file servers! Mounting DFS shares on Linux needs adaption as well. See articles in Web.

Trying one DFS server directly gives another error: (Share, directory and file are correct)
`curl -u 'domain\user1' smb://192.168.100.101/Filer/Share/backup/test.txt`
Enter host password for user 'domain\user1':
curl: (78) Remote file not found

Mounting the share directly works as well.
Output of mount:
//192.168.100.101/Filer/Share on /mnt/backup2 type cifs (rw,relatime,vers=1.0,...

Please understand my Issue as an NFR and not as a bug report.
