### ISSUE TITLE
Correspondence rules of curl-x.x.x source code version and libcurl.so.x.x.x version after compilation?

### ISSUE THREAD

**Issue by zuowanbushiwo** [curl/curl#5480]
I use curl-7.54.1.tar.bz2 and the output is libcurl.so.4.4.0 after compiling，and the output after compiling with curl-7.53.0.tar.bz2 is still libcurl.so.4.4.0, But the output after compiling with curl-7.61.0.tar.bz2 is libcurl.so.4.5.0
  Where can I see a detailed introduction of this corresponding rule? If I sometimes compile libcurl.so.5 and libcurl.so.5.4.0, is there something wrong with me? 
  thanks！

**Comment by jzakrzewski** [comment]
There is no direct correspondence between the two versions. The curl-x.x.x is simply a version number for the project. The number you see after .so denotes the ABI compatibility and depends on what kind of changes were made in particular curl version. The jump from 4.4.0 to 4.5.0 means that there are some new interfaces added.

**Comment by zuowanbushiwo** [comment]
@jzakrzewski  
      Thank you very much for your reply, but I still didn't understand it clearly. For example, I used curl-7.54.1.tar.bz2 to compile. Assuming that the output of the compilation is libcurl.so.4.4.0, where was specified 4.4.0 This version number? Where did I detect a change in the interface and then modify the version number?

**Comment by bagder** [comment]
> Assuming that the output of the compilation is libcurl.so.4.4.0, where was specified 4.4.0 This version number?

`4.4.0` there is not a version number. The version number is 7.54.1.  `4.4.0` is then the [soname](https://en.wikipedia.org/wiki/Soname) of the library, which @jzakrzewski already explained: it tells you something about the presumed ABI compatibility.

As a ground rule, we always ship libcurl SONAME 4.* which means all subsequent releases are binary and ABI compatible with the previous ones. But the minor number tells you when you cannot (without risk) go in the other direction.

You should very rarely have to care about the soname numbers.

> Where did I detect a change in the interface and then modify the version number?

You don't. We who ship curl do. The exact number used is generated from the input specified here:

https://github.com/curl/curl/blob/2110b996a6e9b8271d381c4204b5b930b762dc58/lib/Makefile.am#L69
