### ISSUE TITLE
Some data sharing missing for all easy handles in multi handle

### ISSUE THREAD

**Issue by mkauf** [curl/curl#5482]
https://ec.haxx.se/libcurl/libcurl-sharing states: 

> All easy handles added to the same multi handle automatically share cookies, connection cache, dns cache and SSL session id cache.

I have looked at the code and think it's implemented for the connection cache and the DNS cache, but not yet implemented for cookies and SSL session IDs.

See also https://curl.haxx.se/mail/lib-2015-07/0034.html

Maybe someone wants to start working on this?

**Comment by bagder** [comment]
We've deliberately not made it apply to cookies to make users more explicitly have to opt in to what handles that share cookies. Sharing cookies by default is probably not a good idea. I'll go and update that page and remove the cookie mention.

**Comment by mkauf** [comment]
Thanks. The documentation is correct now.

Maybe I'll try to implement the automatic SSL session ID sharing.

**Comment by bagder** [comment]
Thanks! As the docs is now fixed, I consider this case closed. (as we don't keep feature-requests around in the tracker)
