### ISSUE TITLE
security enhancement: add a signature verification funktion (like gpgv / usign or signify)

### ISSUE THREAD

**Issue by MaxPeal** [curl/curl#5486]
the most CI / Docker / automatic software builds are using curl to automatic download the source files or depenencys.
the most without any signature verification.

if its build in in curl, it do mybe the same push for integrity like letsencrypt.

**Comment by MaxPeal** [comment]
signify References https://www.openbsd.org/papers/bsdcan-signify.html

link to usign https://git.openwrt.org/?p=project/usign.git;a=blob;f=README;h=ac34e308c721a12b90b9bfae1e04c7a5c9d6e655;hb=HEAD

link to Portable version. of
OpenBSD tool to signs and verify signatures on files. 
 https://github.com/aperezdc/signify

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by bagder** [comment]
This would be (more) interesting if there existed a standard way for doing this, but there isn't one.
