### ISSUE TITLE
Incorrect doc and messages re "curl-ca-bundle.crt"

### ISSUE THREAD

**Issue by gitcnd** [curl/curl#5493]
I'm guessing that's not the right file, and probably something with cacert in the name is the real default?  The doc needs fixing.

### I did this

$curl -i  -m 160 'https://site.com'  
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.

$locate curl-ca-bundle.crt
(nothing found)

$ # strings  `which curl` | grep curl-ca-bundle
 bundle is named curl-ca-bundle.crt; you can specify an alternate file

### I expected the following

It looks like the real default is something else - cacert.pem perhaps?

### curl/libcurl version

irrelevant - this web site still makes mention of the wrong file - this needs fixing everywhere, not just in the source code

**Comment by gitcnd** [comment]
Maybe this is the "real" default?
$strings /usr/lib64/libcurl.so | grep ca-bund
/etc/pki/tls/certs/ca-bundle.crt

**Comment by gitcnd** [comment]
Bottom line - the error text needs to show the actual real default, not some hard-coded wrong text I think.

**Comment by jay** [comment]
What version of curl are you using? `curl -V`

curl-ca-bundle.crt is one of the filenames checked at build time to hard code a path.
https://github.com/curl/curl/blob/53cdc2c963e33bc0cc1a51ad2df79396202e07f8/acinclude.m4#L2225-L2242

For Windows builds it is also checked at runtime.
https://curl.haxx.se/docs/manpage.html#--cacert

**Comment by bagder** [comment]
Using `-v` shows the used paths in the verbose output.

**Comment by gitcnd** [comment]
This is where the mistake is:-

https://github.com/curl/curl/blob/180501cb0220c8451a38dc8ae04b6c58743025a8/docs/cmdline-opts/cacert.d#L16

It is a hard-coded constant which is no longer accurate.

**Comment by bagder** [comment]
how is that not accurate?

**Comment by bagder** [comment]
Ah now I saw it. You meant this wording: "The default bundle is named curl-ca-bundle.crt"

**Comment by bagder** [comment]
The error output doesn't say that anymore. It was modified in 7.56.0... via #1817

**Comment by gitcnd** [comment]
My above comment is a link to the live source code in the current branch which still carries the wrong wording.  Since it embedded in the program itself, and since the program does actually know the real "default", it should probably not be hard-coded (thus obsolete depending on build) - just replace it with the real actual default for the program in use (and perhaps not use the word "default" since, what with build options etc, there's no such thing as an all-users "default" anyhow.)

It's actually pretty rude that it *knows* the offending file, but the message doesn't tell us - it is always best to tell people where the problem was when you know that, instead of make them jump through a bunch of hoops to try and find out where the problem was...

**Comment by jay** [comment]
> My above comment is a link to the live source code in the current branch which still carries the wrong wording.

The error message was changed over 2 years ago and the doc says _"The windows version of curl will automatically look for a CA certs file named \'curl-ca-bundle.crt\'"_. How is that not correct?

**Comment by bagder** [comment]
> My above comment is a link to the live source code in the current branch which still carries the wrong wording

It links to *documentation* (not source) code, that describes the name curl on Windows looks for. Please elaborate on how this is incorrect.

> It's actually pretty rude that it knows the offending file, but the message doesn't tell us

I consider that a flawed description of the situation and I object to it and the used file paths are shown in the verbose (`-v`) output just fine already.

**Comment by bagder** [comment]
I don't see a bug here and the report is just too vague. Closing.
