### ISSUE TITLE
HTTP result status should (at least optionally) be output in errno (exit code), write_out interferes with stdout.

### ISSUE THREAD

**Issue by gschadow** [curl/curl#5494]
I've always wondered why cURL doesn't return the HTTP result status as an errno. I understand why it wasn't as easy as HTTP status 200 => errno=0 and all others errno=HTTP status. And you also do FTP which have different status. However, the --write_out '%{http_code}'  is a problem as it interferes with someone wanting to receive the response body on stdout. 

I can work around all this with a script like this:
```
transact() {
    response="$(curl --show-error --silent --write-out ' %{http_code}' $url)"
    errno=$?
    if [ $errno != 0 ] ; then
      ... deal with error conditions ...
    elif expr "$reponse" : '.* 503$' ; then
      ... deal with service temporarily not available ...
    fi
    echo "$response" |sed -e '$ s/^\(.*\) [0-9][0-9][0-9]/\1/'
}
```
but I find that cumbersome and error-prone. Especially if the server sends HTTP error pages in error conditions which we don't care about when scripting. If I had two flags of very general use:

-  --http-errno - overlays the HTTP status in the errno
   - current cURL errnos go from 0 to 90, leaving 10 more
   - http response codes start with 100 and maximally 999, so it even fits in short errno values
   - if you want, prefix the http status with 1, i.e., 1200 OK, 1503 - service unavailable, ...
- --http-ok - with --http-errno do not report 2xx status as errno, but as 0
- --http-stderr - sends the response body to stderr for anything but HTTP status 2xx status
   - this is to mimic the behavior of Java UrlConnection
- --http-noerr - throws away the response body for http status not 2xx, leaving stderr for curl error messages only.

The above options should be easy to add and would make scripting with curl so much easier, as people can choose to check normal error conditions as they would do with all UNIX tools, e.g.
```
if curl --http-errno --http-ok --http-stderr http://host/service/check/ ; then
    ... good ...
else
    ... bad ...
fi
```
which is super intuitive as it is the behavior of every other UNIX tool:
- return 0 if things are good, expect only good data in stdout
- return error messages in stderr, not stdout, and errno > 0 for any problems.

Then my use case above would be so much simpler:
```
transact() {
    if curl --show-error --silent --errno-http --http-ok --http-noerr $url ; then
       ... good ...
    elif [ $? = 503 ] ; then
        ... deal with service temporarily not available ...
    else 
        ... deal with other error conditions ...
    fi
}
```
you see, now I do not even need to capture the result, to later clean it up, it can flow right through because I don't need to worry about the error page HTML coming from servers.

I notice that you already have a --retry option for retrying transient errors, however, you consider all 5xx errors as transient, while really only 503 should be considered transient. Most systems' 500 errors are general crash conditions, which usually aren't transient (unless you consider the years it takes for bugs to be resolved a "transient condition"). This probably needs to be fixed to be more specific, i.e., add another flag:
- --http-retry <list> - comma separated list of HTTP codes to retry, e.g., --http-retry 503,404 would retry when service not available and until a file has been added to a server.

And while dealing with such retry resilience, you also need to consider the 102 - processing status. The server may send this response several times before the final response, to indicate it is still working, e.g., on a large synchronous job. The utility of the 102 condition is to
- keep the waiting client informed that it's still working (e.g., could trigger a ....... progress report) and
- keep a connection alive through a firewall with timeout, e.g., some firewalls might time out in 5 min but some synchronous jobs might take longer

Sorry, this has become somewhat of a full wish-list. But I consider these so urgent as to be bugs really. And also, I find this so important, that I would implement these things myself, but only if I have a chance for such contribution I would make to being accepted into the main code. I am sure this has come up in the decade or two of curl's existence, hence, I am doubtful if my contribution would be accepted.

**Comment by falconindy** [comment]
If you were to stub our your transact function with something that returns a value greater than 255, you'd quickly see that returning the transfer status code can't possibly work -- exit statuses are 8 bit values and will wrap on overflow.

```sh
$ r() { return 404; }; r; echo $?
148
```

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

Of course, as @falconindy points out, the suggested change wouldn't work as described.
