### ISSUE TITLE
cUrl says the certificate has expired when the Root CA certificate is expired

### ISSUE THREAD

**Issue by marcomarsala** [curl/curl#5496]
### I did this
`curl https://servizi.tek01.it` says:
`curl: (60) SSL certificate problem: certificate has expired`
but it is wrong. The site certificate is still valid until November 2020, just the Root CA (Comodo RSA) certificate is expired some days ago, but this is a legal situation.

Any browser on both Windows and Mac show that site as secure.

This break all libraries too (like PHP cURL)

### curl/libcurl version

[curl -V output]

curl 7.61.1 (x86_64-koji-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k zlib/1.2.7 libidn2/2.3.0 libssh2/1.4.3 nghttp2/1.39.2
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy Metalink

but it seems all recent versions show the same behavior.

### operating system
Tested on two systems:

Linux ip-172-31-19-7.eu-west-1.compute.internal 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Linux thenetworksolution.it 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is an OpenSSL bug. I believe they fixed it in 1.1.0. Your example site works perfectly fine with curl with OpenSSL 1.1.1g.

I think this is the verification bug where there are multiple chains and one of them leads to an expired cert. [GnuTLS also had this problem](https://gitlab.com/gnutls/gnutls/-/issues/1008).

This is not a curl bug.

**Comment by marcomarsala** [comment]
Thank you. What packets I should update to fix it?

**Comment by bagder** [comment]
The bug exists in your TLS library/libraries. You should report that to the distro/provider you're using and ask for their guidance on how to get this fixed.

You can of course build a fresh OpenSSL and a curl to use that, but we strongly advice against replacing your system (curl) libraries with your own custom build as that often causes unexpected secondary issues.
