### ISSUE TITLE
--disable-proxy causes test 970 to fail

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5501]
### I did this

Took a look at the recent AppVeyor CI failures and found that test 970 does not work if `--disable-proxy` is used:
https://ci.appveyor.com/project/curlorg/curl/builds/33251610/job/2l50ru85ekytacpk?fullLog=true#L3345

### I expected the following

Mostly green results except some flaky tests (which did not happen for some time now).

**Comment by mback2k** [comment]
For some reason the travis-ci build with `--disable-proxy` does not run test 970 at all:
https://travis-ci.org/github/curl/curl/jobs/693632114

**Comment by bagder** [comment]
Test 970 requires the `debug` feature, but the travis disabled-proxy job doesn't have that. That's why 970 doesn't run there.
