### ISSUE TITLE
Curl crash seen when TCP connection to server is down while verifying  server X509 certs

### ISSUE THREAD

**Issue by Jayashankara-DM-135** [curl/curl#5510]
Our client application using curl-7.63.0 to make connection to application server. 

Client makes connection request to server via curl_easy_perform(), Before making call to curl_easy_perform() client application registered a call back to do server x509 certificate verification (Which includes trust verification and revocation status checking).

For revocation check our client application uses cached CRL/OCSP response got it from server when it makes first time connections and It will be used for next 'X' days. 

Order of revocation check is OCSP first and then CRL.

Issue sequence:
1> Only CRL response is cached already (Where are not running CRL and OCSP server in this case)
2> Client register call back for Certificate verification.
3>  Calls curl_easy_perform()
4>  Certificate verification is called:
     4.a> Trust verification is done
     4.b> Check if there any cached OCSP response. ==> Not available  
     4.b> Waiting for OCSP response from OCSP responder, It will wait for 20 secs to get this ==> Kill server while waiting.
    4.C> After 20 sec , It will check for is there any CRL cached information.
    4.d> Since CRL information is present and It's proper , Certificate verification is Passed
   4.e> Call back routine return Success.
5> Now curl got success for certificate verification, but actual tcp connection to application server is lost. Hence Crash is seen.

Note: In case if step 4.e >returns failed , Then there is no crush is seen

**Comment by bagder** [comment]
What TLS backend are you using with which TLS library version? On what platform is this running?

What "call back for Certificate verification" are you talking about? All this talk about CRL and OSCP, how is that done?

When you get a crash, what's the stack trace? (preferably with debug symbols present)

**Comment by Jayashankara-DM-135** [comment]
What TLS backend are you using with which TLS library version?
Openssl 1.1.1c
------
On what platform is this running?
Linux
-----
When you get a crash, what's the stack trace? (preferably with debug symbols present) ?
We are not getting any core file for this crash, I am not aware how to enable core dump in case if crash is seen at library level, if crash is seen at our client code we are getting core dump.

Please let me know how get core file for curl crash .
------
What "call back for Certificate verification" are you talking about? All this talk about CRL and OSCP, how is that done?

Please find below sample code flow. No need worry about CRL and OCSP here since it's not related here, I just specified here because while verifying server certificates we have enough time to kill server before curl_easy_perform() completes it's execution.

int client-fun(http_msg)
{
   CURL *             pEasy_handle = nullptr;
    httpData           data         = {nullptr, 0, 0};
    struct curl_slist *curlHeader   = nullptr;
    CCurltHelper       clientWrapperObj;
 
    // Initialize the curl session.
    pEasy_handle = curl_easy_init();

    HttpClientPrepareCurlHeader(http_msg, curlHeader, pEasy_handle, data);

    // set the Curl header into the handle.
    curl_easy_setopt(pEasy_handle, CURLOPT_HTTPHEADER, curlHeader);

    // set the Curl URL into the handle.
    curl_easy_setopt(pEasy_handle, CURLOPT_URL, http_msg->GetSasUrl().c_str());

    // HTTP timeout : 60 sec
    curl_easy_setopt(pEasy_handle, CURLOPT_TIMEOUT, GetHttpTimeOut());


    // Register a call-back to receive response http headers from the server.
    curl_easy_setopt(pEasy_handle, CURLOPT_HEADERFUNCTION, HttpHeaderCallback);

    curl_easy_setopt(pEasy_handle, CURLOPT_WRITEHEADER, &clientWrapperObj);

    // Pass 'CHttpClientHelper' struct to the httpPayloadCallback function.
    curl_easy_setopt(pEasy_handle, CURLOPT_WRITEDATA, &clientWrapperObj);

    // Register a call-back to receive response http payload from the server.
    curl_easy_setopt(pEasy_handle, CURLOPT_WRITEFUNCTION, HttpPayloadCallback);

    curl_easy_setopt(pEasy_handle, CURLOPT_SSLCERT,
        clientcertpath);
    curl_easy_setopt(pEasy_handle, CURLOPT_SSLKEY,
        clientcertprivkeypath);

    // disable host and peer verification.
    curl_easy_setopt(pEasy_handle, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(pEasy_handle, CURLOPT_SSL_VERIFYHOST, 0L);

    curl_easy_setopt(
            pEasy_handle, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_3);

    curl_easy_setopt(pEasy_handle, CURLOPT_VERBOSE, 1L);

    curl_easy_setopt(pEasy_handle, CURLOPT_CAINFO,
        cacertpath);

    curl_easy_setopt(pEasy_handle, CURLOPT_SSL_CTX_FUNCTION, sslctx_function);


    curl_easy_setopt(pEasy_handle, CURLOPT_NOSIGNAL, 1L);

    CURLcode ret = curl_easy_perform(pEasy_handle);
    
    //Process Response payload from server.
   
    SetStrError(curl_easy_strerror(ret));

    return ret;
}


CURLcode CLASSNAME::sslctx_function(CURL *curl, void *sslctx, void *parm)
{
    CURLcode ret  = CURLE_ABORTED_BY_CALLBACK;
    SSL_CTX *pctx = (SSL_CTX *)sslctx;
    (void)parm;

    SSL_CTX_set_verify(pctx,
        (SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT |
            SSL_VERIFY_CLIENT_ONCE),
        NULL);
    SSL_CTX_set_cert_verify_callback(
        pctx, TLSRestriction::verifyServerCertificate, s_tlsHandler.get());

    SSL_CTX_set_cipher_list(pctx, ...);

    ret = CURLE_OK;
    return ret;
}

bool verifyServerCertificate() {
 True : Certificate verification is PASS
 False: Otherwise.
 """
 1> Extract OCSP server info from received server cert and trying to get that ocsp revocation information via TCP connection. 
    since OCSP server is not running here it will fail. (==> While it is waiting to get ocsp info, We killed application server for which client is verifying certs)	
 2> Client application is continued here to check is there CRL file available in system (in which client application  is running and made available here), so it will get this file and verfiys the server cert
 3> In our case this routine returns True.
	
 """
 
}

**Comment by bagder** [comment]
> Please let me know how get core file for curl crash.

Don't. Run your application with a debugger. When it crashes, type `bt` or `bt full` and show that.

**Comment by Jayashankara-DM-135** [comment]
I tried it again but no luck.

I will describe this issue in few sentence for better understanding:
"""
Client application uses curl_easy_perform() API  for making secure connection towards Server.  
Before making this connection, Client application registered one callback routine with curl for server certificate verification(as specified in above code sniff).
As part of curl_easy_perform() API, Client application receives required information from server for certificate verification and 
invokes the certificate verification routine, Before this routine completes its execution if server is down for some reason and  
later verification routine returns successes for certificate verification then crash is seen inside curl_easy_perfom().

Here curl assumes connection is still exist and continued with next steps, since it received all the required information from server and 
certificate verification is also successful. But this assumption is not true in this case.

But if certificate verification routine return failure in this case, then there is no crash seen at curl level.

Note: Ignore what happens inside verification code block which is irrelevant for this crash.
"""

**Comment by bagder** [comment]
> Here curl assumes connection is still exist and continued with next steps

It really doesn't. curl can (should) handle that the server dies at any given moment and never assumes that the server is up - that would be naive and reckless. But a dying server doesn't imply crashing...

I cannot reproduce this. I can't help you.

**Comment by Jayashankara-DM-135** [comment]
Can you please share if have client and server side sample code using curl ? I will tryout on my system and i will update you on this.

**Comment by bagder** [comment]
curl is client-side only, you won't find a server implementation using it.

**Comment by bagder** [comment]
We have lots of [examples using libcurl](https://curl.haxx.se/libcurl/c/example.html).

**Comment by Jayashankara-DM-135** [comment]
Hi,


* STATE: INIT => CONNECT handle 0x17ba888; line 1445 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 127.0.0.1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x17ba888; line 1497 (connection #0)
* Connected to 127.0.0.1 (127.0.0.1) port 9050 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x17ba888; line 1616 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ca.cert
  CApath: /pathtocacert/

Getting stuck here, Can please let me know what i am missing

**Comment by bagder** [comment]
1. run it with a debugger
2. press control-c when it gets stuck
3. investigate where it gets stuck and why

**Comment by Jayashankara-DM-135** [comment]
Thanks for response , I am able to proceed to next step.

sslctx_function will get called when we disable both PEER and HOST verification ? if it's yes when this will get called from curl.

code:
36 int verifyServerCertificate()
  37 {   
  38     int i = 10;
  39     while (i)
  40     {
  41         printf("JAI: Verify funcation is called");
  42         i = i - 1;
  43         fflush(stdout);
  44         sleep(1);
  45     }
  46     return 1;
  47 }

49 static CURLcode sslctx_function(CURL *curl, void *sslctx, void *parm)
  50 {   
  51     printf("sslctx funcation is called");
  52     SSL_CTX *pctx = (SSL_CTX *)sslctx;
  53     (void)curl;
  54     CURLcode ret;
  55     (void)parm;
  56     
  57     SSL_CTX_set_verify(pctx,
  58         (SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT |
  59             SSL_VERIFY_CLIENT_ONCE),
  60         NULL);
  61     SSL_CTX_set_cert_verify_callback(pctx, verifyServerCertificate, NULL);
  62     
  63     SSL_CTX_set_cipher_list(pctx,
  64         "AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-"
  65         "ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384");
  66     
  67     ret = CURLE_OK;
  68     printf("sslctx funcation is Done!!!");
  69     return ret;
  70 }

72 int main(void)
  73 {
  74     CURL *      curl;
  75     CURLcode    res;
  76     FILE *      headerfile;
  77     const char *pPassphrase = NULL;
  78 
  79     static const char *pCertFile   = "client.cert";
  80     static const char *pCACertFile = "ca.cert";
  81     static const char *pHeaderFile = "dumpit";
  82 
  83     const char *pKeyName;
  84     const char *pKeyType;
  85 
  86     const char *pEngine;
  87 
  88     pKeyName = "client.key";
  89     pKeyType = "PEM";
  90     pEngine  = NULL;
  91 
  92     headerfile = fopen(pHeaderFile, "wb");
  93 
  94     curl_global_init(CURL_GLOBAL_DEFAULT);
  95 
  96     curl = curl_easy_init();
  97     if (curl)
  98     {
  99         char errbuf[CURL_ERROR_SIZE];
 100 
 101         /* what call to write: */
 102         curl_easy_setopt(curl, CURLOPT_TIMEOUT, 0);
 103         curl_easy_setopt(curl, CURLOPT_URL, "https://127.0.0.1:9050");
 104         curl_easy_setopt(curl, CURLOPT_HEADERDATA, headerfile);
 105         curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);
 106         errbuf[0] = 0;
 107 
 108         do
 109         { /* dummy loop, just to break out from */
 110 
 111             /* cert is stored PEM coded in file... */
 112             /* since PEM is default, we needn't set it for PEM */
 113             curl_easy_setopt(curl, CURLOPT_SSLCERTTYPE, "PEM");
 114 
 115             /* set the cert for client authentication */
 116             curl_easy_setopt(curl, CURLOPT_SSLCERT, pCertFile);
 117 
 118             /* sorry, for engine we must set the passphrase
 119              *          (if the key has one...) */
 120             if (pPassphrase)
 121                 curl_easy_setopt(curl, CURLOPT_KEYPASSWD, pPassphrase);
 122 
 123             /* if we use a key stored in a crypto engine,
 124              *          we must set the key type to "ENG" */
 125             curl_easy_setopt(curl, CURLOPT_SSLKEYTYPE, pKeyType);
 127             /* set the private key (file or ID in engine) */
 128             curl_easy_setopt(curl, CURLOPT_SSLKEY, pKeyName);
 129 
 130             curl_easy_setopt(
 131                 curl, CURLOPT_CAPATH, "/home/jmallesh/Issue_Foxcon_Cisco/");
 132             /* set the file with the certs vaildating the server */
 133             curl_easy_setopt(curl, CURLOPT_CAINFO, pCACertFile);
 134 
 135             /* disconnect if we can't validate server's cert */
 136             curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
 137             curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
 138 
 139             // curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
 140             curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
 141             curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, sslctx_function);
 142             curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
 143             curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
 144             // curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS,
 145             // CURLSSLOPT_NO_REVOKE);
 146             /* Perform the request, res will get the return code */
 147             res = curl_easy_perform(curl);
 148             /* Check for errors */
 149             if (res != CURLE_OK)
 150             {
 151                 fprintf(stderr, "curl_easy_perform() failed: %s\n",
 152                     curl_easy_strerror(res));
 153                 size_t len = strlen(errbuf);
 154                 if (len)
 155                 {
 56                     fprintf(stderr, "%s%s", errbuf,
 157                         ((errbuf[len - 1] != '\n') ? "\n" : ""));
 158                 }
 159                 else
 160                 {
 161                     fprintf(stderr, "%s\n", curl_easy_strerror(res));
 162                 }
 163             }
 164             else
 165             {
 166                 fprintf(stdout, "Curl_easy_perform is Succssfull!!!: %s",
 167                     curl_easy_strerror(res));
 168             }
 169 
 170             /* we are done... */
 171         } while (0);
 172         /* always cleanup */
 173         curl_easy_cleanup(curl);
 174     }
 175 
 176     curl_global_cleanup();
 177 
 178     return 0;
 179 }


Output:

jmallesh@qcomubuntudev:~/Issue_Foxcon_Cisco$ ./out 
* STATE: INIT => CONNECT handle 0x1aa6888; line 1445 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 127.0.0.1...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x1aa6888; line 1497 (connection #0)
* Connected to 127.0.0.1 (127.0.0.1) port 9050 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x1aa6888; line 1616 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ca.cert
  CApath: /home/jmallesh/Issue_Foxcon_Cisco/
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x1aa6888; line 1630 (connection #0)
sslctx funcation is calledsslctx funcation is Done!!!JAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is calledJAI: Verify funcation is called* SSL connection using TLSv1.2 / AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; O=Wireless Innovation Forum; OU=WInnForum SAS Provider Certificate; CN=www.google-sas.com
*  start date: Jan 25 12:35:22 2020 GMT
*  expire date: Mar 30 12:35:22 2021 GMT
*  issuer: C=US; O=Wireless Innovation Forum; OU=RSA SAS Provider CA0001; CN=WInnForum RSA SAS Provider CA
*  SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x1aa6888; line 1651 (connection #0)
> GET / HTTP/1.1
Host: 127.0.0.1:9050
Accept: */*

* STATE: DO => DO_DONE handle 0x1aa6888; line 1713 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x1aa6888; line 1837 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x1aa6888; line 1852 (connection #0)
* HTTP 1.0, assume close after body
* Marked for [closure]: HTTP/1.0 close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/2.7.12
< Date: Fri, 05 Jun 2020 14:00:19 GMT
< Content-type: text/html; charset=UTF-8
< Content-Length: 2686
//some HTML contents 
* STATE: PERFORM => DONE handle 0x1aa6888; line 2049 (connection #0)
* multi_done
* Closing connection 0
* The cache now contains 0 members
Curl_easy_perform is Succssfull!!!: No error

**Comment by Jayashankara-DM-135** [comment]
Looks like curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L) this setting causing issue for me. When i disabled it (curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 0L)) i was able to get below message.

> curl_easy_perform() failed: Couldn't connect to server
Failed to connect to 127.0.0.1 port 9050: Connection refused

_**Can you please let me what happen if CURLOPT_NOSIGNAL =1 in my issue case ?**_

Thanks

**Comment by bagder** [comment]
It seems the wrong way around. Don't set options you don't know what they do. And if you don't know what they do, we spent a significant effort on documenting libcurl so please do read the docs.

Setting `CURLOPT_NOSIGNAL` without having your own signal handler will of course risk that your code crash. You asked for it. This is not a curl issue.

**Comment by bagder** [comment]
> Initially we were facing crash due DNS timeout . After reading below document (section: Signalling) we have added CURLOPT_NOSIGNAL = 1 to fix this issue.

If you get a crash, you probably another issue and should rather solve that independently of changing CURLOPT_NOSIGNAL. When switching off libcurl's signal handling you need to handle the situation yourself, which you don't seem to...

If you want to ask questions, please do that on the curl-library list or consider purchasing commercial support.
