### ISSUE TITLE
Solution for cURL error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by nicolas-santos** [curl/curl#5514]
Hello,

Could you update cacert.pem on https://curl.haxx.se/docs/caextract.html ? 

Juste remove  `AddTrust External Root` (expired on 30 may 2020) from the pem file - would have save me some time ^^ 

Thx for your work !

**Comment by bagder** [comment]
The point of the CA cert bundle provided there is that it is a straight conversion of the certs Mozilla hosts and uses for Firefox. We don't manually tamper with them. If AddTrust is still in there, that's because Mozilla still has it included. File a bug against Firefox!

**Comment by nicolas-santos** [comment]
Thx for your answer ^^
