### ISSUE TITLE
Windows version not properly using Schannel by default

### ISSUE THREAD

**Issue by bbodenmiller** [curl/curl#5515]
### I did this

```
> .\curl "https://myinternalsite.com"
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### I expected the following

Custom CA for site is installed to Windows certificate store so `curl` should work with site  since `Schannel` is default within parentheses (as per details on https://ec.haxx.se/usingcurl/usingcurl-tls#multiple-tls-backends, see output below).

When explicitly setting it works but I shouldn't need to per docs.

```
> $env:CURL_SSL_BACKEND="Schannel"
> .\curl "https://myinternalsite.com"
<html><body>You are being <a href="https://anothersite.com">redirected</a>.</body></html>
```

### curl/libcurl version

```
> ./curl -V output
curl 7.70.0 (x86_64-pc-win32) libcurl/7.70.0 OpenSSL/1.1.1g (Schannel) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets brotli libz
```

### operating system

```
> cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1158]
(c) 2018 Microsoft Corporation. All rights reserved.
```

**Comment by bagder** [comment]
This curl build you're using uses **OpenSSL** by default, but also has built-in support for schannel. It is visible by the fact that the prior name is *not* within parentheses while the second is, in the first line of the `curl -V` output.

If you want schannel to be the default TLS backend you need a different build.

**Comment by dscho** [comment]
> If you want schannel to be the default TLS backend you need a different build.

Or set `CURL_SSL_BACKEND=schannel`.

**Comment by bagder** [comment]
Right, but as the reporter talked about the *default* choice I figured that meant when not choosing anything at all...

**Comment by dscho** [comment]
> Right, but as the reporter talked about the _default_ choice I figured that meant when not choosing anything at all...

Sorry, what I meant is: the user can set this in their User environment in the System Properties. That's kind of setting it as a default ;-)
