### ISSUE TITLE
http2 seems to not work

### ISSUE THREAD

**Issue by selfboot** [curl/curl#5526]
### I did this

![image](https://user-images.githubusercontent.com/2769831/83874750-936c3100-a768-11ea-8278-a6d3ad4a4636.png)

### I expected the following

It should be:

```
HTTP/2 301
location: https://www.google.com/
content-type: text/html; charset=UTF-8
date: Fri, 05 Jun 2020 12:09:04 GMT
expires: Sun, 05 Jul 2020 12:09:04 GMT
cache-control: public, max-age=2592000
server: gws
content-length: 220
x-xss-protection: 0
x-frame-options: SAMEORIGIN
alt-svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

### operating system

centos 6.2

**Comment by bagder** [comment]
I would guess you maybe have a proxy set in the environment variables that curl uses? Adding `-v` to the command line would show.

As you can see, that's not even doing HTTP/2 there.

**Comment by selfboot** [comment]
I delete my curl and reinstall, can not be reproduced here. Just close this issue .
