### ISSUE TITLE
Code does not compile with -Werror

### ISSUE THREAD

**Issue by dragon512** [curl/curl#5528]
### I did this
Compile with gcc 8 by adding -Werror 

### I expected the following
I expected at most to have to add -Wno-error=?? related flags to allow for the build pass under a more strict build environment.

### What I saw

```
libtool: compile:  /opt/rh/devtoolset-8/root/usr/bin/gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -O0 -Wall -Werror -Wextra -Wno-error=unused-variable  -fvisibility=hidden -Wno-error=unused-variable -Werror-implicit-function-declaration -Wno-system-headers -pthread -MT libcurl_la-altsvc.lo -MD -MP -MF .deps/libcurl_la-altsvc.Tpo -c altsvc.c  -fPIC -DPIC -o .libs/libcurl_la-altsvc.o

In file included from curl_setup.h:673,
                 from altsvc.c:26:
curl_setup_once.h:109:8: error: redefinition of 'struct timeval'
 struct timeval {
        ^~~~~~~
In file included from /usr/include/sys/select.h:45,
                 from /usr/include/sys/types.h:219,
                 from ../include/curl/system.h:430,
                 from ../include/curl/curl.h:38,
                 from curl_setup.h:157,
                 from altsvc.c:26:
/usr/include/bits/time.h:30:8: note: originally defined here
 struct timeval

```
It would be nice if curl could compile with stricter settings.

**Comment by bagder** [comment]
We build curl in the CI with `-Werror` and I always use it for my own local builds. How did you put it among the flags? Adding -Werror shouldn't suddenly cause a redefined struct... 

I assume this is on Linux? What curl version?

**Comment by jay** [comment]
That's defined there only when struct timeval wasn't found.

https://github.com/curl/curl/blob/53cdc2c963e33bc0cc1a51ad2df79396202e07f8/lib/curl_setup_once.h#L108-L113

Here is the check for timeval:
https://github.com/curl/curl/blob/53cdc2c963e33bc0cc1a51ad2df79396202e07f8/acinclude.m4#L1377-L1432

**Comment by dragon512** [comment]
Yes 
it is one Linux Centos/rhel 7/8 with gcc 8.3

7_70_0 tag.

the configure summary is:

```
 Host setup:       x86_64-unknown-linux-gnu
  Install prefix:   /home/jkenny/code/build/_destdir/libcurl
  Compiler:         /opt/rh/devtoolset-8/root/usr/bin/gcc
   CFLAGS:          -Wno-builtin-macro-redefined -O0 -Wall -Wextra -Wno-error=unused-variable -Werror-implicit-function-declaration -Wno-system-headers -pthread
   CPPFLAGS:        -Wno-builtin-macro-redefined -O0 -Wall -Wextra -Wno-error=unused-variable -DDEBUG -isystem /home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libssh2_1.9.0_fe97/include -isystem /home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/openssl_1.1.1g_fe97/include -isystem /home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/nghttp2_1.39.2_fe97/include -isystem /home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/brotli_1.0.7_fe97/include -isystem /home/jkenny/code/build/_destdir/brotli/include -isystem /home/jkenny/code/build/_destdir/openssl/include -isystem /home/jkenny/code/build/_destdir/libssh2/include -isystem /home/jkenny/code/build/_destdir/nghttp2/include
   LDFLAGS:         -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath='$$ORIGIN/../lib',--enable-new-dtags -Wl,-rpath-link=/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libssh2_1.9.0_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/nghttp2_1.39.2_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/jemalloc_5.2.1_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libevent_2.1.11/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/openssl_1.1.1g_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/jansson_2.12_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libev_4.27_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libxml2_2.9.10_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libicu_65.1_fe97/lib:/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/brotli_1.0.7_fe97/lib -L/home/jkenny/code/build/_build/build_debug_posix-x86_64_gcc/libcurl -L/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/libssh2_1.9.0_fe97/lib -L/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/openssl_1.1.1g_fe97/lib -L/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/nghttp2_1.39.2_fe97/lib -L/home/jkenny/code/build/_sdk/debug_posix-x86_64_gcc/brotli_1.0.7_fe97/lib -L/home/jkenny/code/build/_destdir/brotli/lib -L/home/jkenny/code/build/_destdir/openssl/lib -L/home/jkenny/code/build/_destdir/libssh2/lib -L/home/jkenny/code/build/_destdir/nghttp2/lib
   LIBS:            -lnghttp2 -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lbrotlidec -lbrotlidec -lz

  curl version:     7.70.0-DEV
  SSL:              enabled (OpenSSL)
  SSH:              enabled (libSSH2)
  zlib:             enabled
  brotli:           enabled (libbrotlidec)
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          enabled
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   /etc/pki/tls/certs/ca-bundle.crt
  ca cert path:     no
  ca fallback:      no
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          no      (--enable-alt-svc)
  HTTP2:            enabled (nghttp2)
  HTTP3:            disabled (--with-ngtcp2, --with-quiche)
  ESNI:             no      (--enable-esni)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         SSL IPv6 UnixSockets libz brotli AsynchDNS NTLM NTLM_WB TLS-SRP HTTP2 HTTPS-proxy
```

I can probably make a reproducer of this whole build up to libcurl if it would help

**Comment by dragon512** [comment]
@jay Thanks for that tip. I wonder if there was something else hidden going on. Let me double check this.

**Comment by bagder** [comment]
`--enable-debug --enable-werror` are part of my standard configure flags for curl and they give me this amazing set of warning flags on debian unstable (gcc 9.3):

CFLAGS = -Werror-implicit-function-declaration -g -O0 -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wbad-function-cast -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wold-style-definition -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -ftree-vrp -Wdouble-promotion -Wformat=2 -Warray-bounds=2 -Wshift-negative-value -Wshift-overflow=2 -Wnull-dereference -fdelete-null-pointer-checks -Wduplicated-cond -Wunused-const-variable -Wduplicated-branches -Wrestrict -Walloc-zero -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough=4 -Wno-system-headers -Werror -pedantic-errors

**Comment by Billyzou0741326** [comment]
I was able to get a build to fail on centos7 with `CFLAGS=-Werror ./configure`, with a different error:
```
In file included from /usr/include/string.h:633:0,
                 from ../../lib/curl_setup_once.h:32,
                 from ../../lib/curl_setup.h:673,
                 from ../../src/tool_setup.h:36,
                 from ../../src/slist_wc.c:23:
../../src/tool_strdup.h:27:14: error: expected identifier or '(' before '__extension__'
 extern char *strdup(const char *str);
              ^
make[2]: *** [curl-slist_wc.o] Error 1
make[2]: Leaving directory `/root/curl/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/curl/build/src'
make: *** [all-recursive] Error 1
```

But the same build would succeed with `./configure --enable-debug --enable-werror`.

**Comment by dragon512** [comment]
I was able to track down that something I am adding to the configure line I causing HAVE_STRUCT_TIMEVAL to not be defined but HAVE_SYS_TIME_H to be defined in the curl_config.h

**Comment by dragon512** [comment]
I found that adding CFLAGS="-Wall" causes this to fail.

**Comment by bagder** [comment]
The configure checks don't do well with those options.

**Comment by bagder** [comment]
If you think fixing configure to work with `CFLAGS=-Werror` is a worthwhile task, then feel free to grab it and work on it. If not, I propose you just use `--enable-werror` instead.

**Comment by dragon512** [comment]
I can close the issue. I don't have time at the moment to fix the automake. If anything I have a builder in SCons that is building this via calling automake. Maybe when I get some time I can look at it more.

Just to clarify on the issue a little more. I can pass -Werror to CFLAGS without issues. The problem was pass -Wall with the -Werror. The addition of -Wall it seem cause the configure check for timeval struct to fail. My current fix is to not pass -Wall with the -Werror when calling the curl build system. Also I should add that I don't have that many -Wno-error flags being passes when building with gcc8. Maybe gcc9 is different. I only had to add the `-Wno-error=unused-variable` flag. The massive set you had referred to above was not needed.

**Comment by bagder** [comment]
> The massive set you had referred to above was not needed.

It is the list of option I get automatically using the options I described (you'd get almost the same with gcc8). I'm just showing that we (I) use these as-picky-options-as-possible already to make sure the code is written as clean as possible and without any warnings, preferably on any platforms - which I'm sorry to say we haven't been able to achieve (yet).

Anyway, as we've concluded here you can indeed build curl perfectly fine with -Wall and -Werror, you just cannot run configure with them.

**Comment by dragon512** [comment]
I understand. I myself work on build systems. There are a lot of issues that make it not as easy as one would like to have that simple to use build system. I think in this case, but have not proven it yet, that this issues with with the built in a predefined configure code for testing of this structure. I have found that a few other component (libevent as an example) have the exact same issue. This is hard as compiler change the way they look as the code as they improve. Thanks for your time on this.
