### ISSUE TITLE
curl not sending TCP Keep-Alive packets

### ISSUE THREAD

**Issue by carylewis** [curl/curl#5531]
I downloaded and compiled curl on cygwin, version  3.1.5-1  using:

./configure --disable-shared --enable-debug --prefix=/usr

The build completed correctly.

When I attempt to use curl to access an https:// REST endpoint that takes up to 5 minutes to respond with the:

`--keepalive-time 5`

command line option, and I watch the TCP traffic via wireshark, I do not see any TCP Keep-Alive packets. Without the keep-alive packets the request fails.

### curl/libcurl version
curl 7.71.0-DEV (x86_64-pc-cygwin) libcurl/7.71.0-DEV OpenSSL/1.1.1f zlib/1.2.11
Release-Date: [unreleased]

### operating system

CYGWIN_NT-10.0 IT008 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64 Cygwin

Running the win32 version of curl does work as expected, and I see the Keep-Alive packets being sent every 5 seconds, and the REST call does complete correctly.

**Comment by bagder** [comment]
Set a break-point in `lib/connect.c:tcpkeepalive()` and verify that the funtions get called. If they are, the problem is in cygwin, not curl...

**Comment by carylewis** [comment]
It appears as though both TCP_KEEPIDLE and TCP_KEEPINTVL are not defined,
so the code skips over the setting of the keepalive options.

I added
#define TCP_KEEPIDLE 1
#define TCP_KEEPINTVL 1

to lib/curl_setup.h, did a make clean, then a make, and now the code
attempts to set the keepalive idle and interval values, but I still don't
see any keepalive packets in wireshark.

Can you explain why  TCP_KEEPIDLE and TCP_KEEPINTVL weren't defined?

I'll post something to the cygwin mailing list - maybe someone there can
explain what's going on.

**Comment by bagder** [comment]
`TCP_KEEPIDLE` and `TCP_KEEPINTVL` are defines in the system headers. Typically `netinet/tcp.h`. curl includes that file if configure found it, and then if the symbols are defined properly in there they will be used in the source code.  Where does cygwin define them?

> #define TCP_KEEPIDLE 1
> #define TCP_KEEPINTVL 1

This obviously won't work. They need to be defined to their correct values, which the specific TCP stack should know about and therefor be defined properly in the headers!

**Comment by carylewis** [comment]
I see what you mean, I didn't look closely enough at the code to see that
the values of the constants were actually used in the set socket option
calls.

I'll follow up with the cygwin maintainers. Perhaps keep alives just aren't
emulated in the posix to windows translation layer.

The keep alive constants don't seem to be defined anywhere in /usr.

Maybe it's possible to use the winsock call to set the options, but I don't
know if we can mix and match the socket and winsock calls on the same
socket, probably not.

Sorry to bother you - but maybe it's worth a note somewhere warning
people that curl built on cygwin doesn't support the --keepalive-time
parameter?

**Comment by bagder** [comment]
> maybe it's worth a note somewhere warning people that curl built on cygwin doesn't support the --keepalive-time parameter?

To me, it seems a bit too specific to add a warning about cygwin in the generic man page where 99% of its readers won't be using cygwin... Since this is a cygwin problem, I consider this issue closed.
