### ISSUE TITLE
libcurl ssl handshake failed on some wireless router without error

### ISSUE THREAD

**Issue by everettli** [curl/curl#5559]
### I did this
I use libcurl easy API to download file throw HTTPS. In most cases, it can be downloaded successfully.
However, under certain routers such as Huawei Honor's 5G Wi-Fi, libcurl ssl handshake will be failed.
The following is the way I use the libcurl library to turn off SSL certificate verification.
```
    curl_easy_setopt(curl_handle, CURLOPT_URL, url);
    curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);
    curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, (void *) &chunk);
    curl_easy_setopt(curl_handle, CURLOPT_USERAGENT, USER_AGENT);
    curl_easy_setopt(curl_handle, CURLOPT_NOSIGNAL, 1L);
    curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(curl_handle, CURLOPT_TIMEOUT_MS, 30000);
```

When failed, the log and packet capture data are as follows:
<img width="1405" alt="9C1EE490-5239-4A8A-B6A3-0327D30CEA3A" src="https://user-images.githubusercontent.com/4630274/84483336-cca62300-accb-11ea-9aed-46be1a2fd0b2.png">

```
06-05 18:18:14.061 11068 11418 D curl:   Trying 139.196.135.155:443...
06-05 18:18:14.061 11068 11418 D curl: TCP_NODELAY set
06-05 18:18:15.122 11068 11418 D curl: Connected to iotx-vision-vod-vpc-sh.aliyun.com (139.196.135.155) port 443 (#0)
06-05 18:18:15.125 11068 11418 D curl: ALPN, offering http/1.1
06-05 18:18:15.125 11068 11418 D curl: SSL data out len= 5
06-05 18:18:15.125 11068 11418 D curl: TLSv1.2 (OUT), TLS handshake, Client hello (1):
06-05 18:18:15.125 11068 11418 D curl: SSL data out len= 228
06-05 18:18:15.165 11068 11418 D curl: SSL data in len= 5
06-05 18:18:15.165 11068 11418 D curl: TLSv1.2 (IN), TLS handshake, Server hello (2):
06-05 18:18:15.165 11068 11418 D curl: SSL data in len= 112
06-05 18:18:15.165 11068 11418 D curl: SSL data in len= 5
06-05 18:18:15.165 11068 11418 D curl: TLSv1.2 (IN), TLS handshake, Certificate (11):
06-05 18:18:15.165 11068 11418 D curl: SSL data in len= 6204
06-05 18:18:15.167 11068 11418 D curl: SSL data in len= 5
06-05 18:18:15.167 11068 11418 D curl: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
06-05 18:18:15.167 11068 11418 D curl: SSL data in len= 114
06-05 18:18:15.171 11068 11418 D curl: SSL data in len= 5
06-05 18:18:15.171 11068 11418 D curl: TLSv1.2 (IN), TLS handshake, Server finished (14):
06-05 18:18:15.171 11068 11418 D curl: SSL data in len= 4
06-05 18:18:15.172 11068 11418 D curl: SSL data out len= 5
06-05 18:18:15.172 11068 11418 D curl: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
06-05 18:18:15.172 11068 11418 D curl: SSL data out len= 37
06-05 18:18:15.173 11068 11418 D curl: SSL data out len= 5
06-05 18:18:15.173 11068 11418 D curl: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
06-05 18:18:15.173 11068 11418 D curl: SSL data out len= 1
06-05 18:18:15.173 11068 11418 D curl: SSL data out len= 5
06-05 18:18:15.173 11068 11418 D curl: TLSv1.2 (OUT), TLS handshake, Finished (20):
06-05 18:18:15.173 11068 11418 D curl: SSL data out len= 16
06-05 18:18:44.040 11068 11418 D curl: Operation timed out after 30001 milliseconds with 0 out of 0 bytes received
06-05 18:18:44.040 11068 11418 D curl: Closing connection 0
```

I also grabbed a successful network packet for reference.
<img width="1421" alt="EDFCE2FE-27A5-40D1-A2C3-F26CBF170976" src="https://user-images.githubusercontent.com/4630274/84483352-d0d24080-accb-11ea-828c-6844a06c1c7f.png">

It can be seen that the Client Key Exchange is lost during the SSL handshake phase when it fails compared to when it succeeds.  The strange thing is that the Client Key Exchange step can be seen in the log.

### I expected the following
The SSL handshake can succeed or know the reason for the handshake failure.

### curl/libcurl version
curl-7.67.0
openssl-1.1.0l
### operating system
Android OS

**Comment by bagder** [comment]
Surely this returned `CURLE_OPERATION_TIMEDOUT` and even some text in the error buffer? That is an error and explanation even if you perhaps would like another one.

If OpenSSL doesn't fail and give us an error for this, what else is curl going to do about this?

**Comment by Lekensteyn** [comment]
In frame 50 the server sends an Application Data message after the handshake which is rather odd since the client usually sends its request first.

To investigate this, consider setting the `SSLKEYLOGFILE` environment variable as described in https://ec.haxx.se/usingcurl/usingcurl-tls/tls-sslkeylogfile

For a more thorough treatment on Wireshark configuration for TLS decryption, see https://lekensteyn.nl/files/wireshark-tls-debugging-sharkfest19eu.pdf

**Comment by everettli** [comment]
@bagder Thank you. The way I expressed it is inaccurate, and there is indeed a CURLE_OPERATION_TIMEDOUT error returned. In fact, I want to know the specific reason why the handshake cannot be completed. This may be the problem of openssl, which is really strange.

**Comment by bagder** [comment]
> I want to know the specific reason why the handshake cannot be completed

Sure, that would be ideal, but... When the time-out is reached like this, the handshake hasn't completed so there's no SSL error (yet). It is *possible* that an error would appear eventually if you wait long enough.
