### ISSUE TITLE
CURLOPT_NETRC USERPROFILE

### ISSUE THREAD

**Issue by nu8** [curl/curl#5564]
On Windows, `CURLOPT_NETRC` can be found at `%HOME%/_netrc` or `%HOME%/.netrc`.
However `%USERPROFILE%/_netrc` and `%USERPROFILE%/.netrc` are not recognized.

This is unusual, as `HOME` is not predefined for any Windows OS, and
`USERPROFILE` is defined for every Windows OS. I think it would make sense to
look for `USERPROFILE` on Windows, as `HOME` is a Linux variable.

https://curl.haxx.se/libcurl/c/CURLOPT_NETRC.html

**Comment by jay** [comment]
Note the curl tool [homedir()](https://github.com/curl/curl/blob/curl-7_70_0/src/tool_homedir.c#L73-L86) uses `APPDATA` when `HOME` is not available.

**Comment by nu8** [comment]
APPDATA would be fine as well, basically any variable that is predefined by Windows, which `HOME` is not.

**Comment by bagder** [comment]
Are there other tools that find/use `.netrc` in that directory on Windows?

**Comment by nu8** [comment]
Git:

https://github.com/git/git/blob/eebb51ba/compat/mingw.c#L2572-L2594

**Comment by bagder** [comment]
We welcome patches. We have done decently for over twenty years already without supporting this...

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by nu8** [comment]
Workaround for PHP:

~~~php
$s = getenv('USERPROFILE');
curl_setopt($r_c, CURLOPT_NETRC_FILE, $s . '/_netrc');
curl_setopt($r_c, CURLOPT_NETRC, true);
~~~
