### ISSUE TITLE
SMTP sessions seem to have flaws (EHLO, full stop termination)

### ISSUE THREAD

**Issue by MulMic** [curl/curl#5572]
While sending email with -v turned on, it occurs to me that the output shows EHLO being sent with the name of the attached file rather than client address. (message in this case) 

Also the data transmission isn't terminated by a full stop, leading to false SPAM tickets (example yandex)

As reference I use ["https://www.samlogic.net/articles/smtp-commands-reference.htm"](url)

The output from `curl -v 'smtps://smtp.yandex.com:465' --ssl-reqd  --mail-from 'sender@yandex.com' --mail-rcpt 'recipient@gmail.com' --user 'sender@yandex.com:mysecretpw' --upload-file message > yandex.log 2>&1` is attached as file.

MulMic

### curl -V

curl 7.70.0 (x86_64-pc-linux-gnu) libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
Linux gigabyte 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
[yandex.log](https://github.com/curl/curl/files/4790642/yandex.log)

**Comment by bagder** [comment]
As documented in `CURLOPT_URL` for SMTP (which admittedly is a bit hidden for users of the cmdline tool):
~~~
The path part of a SMTP request specifies the host name to present during
communication with the mail server. If the path is omitted then libcurl will
attempt to resolve the local computer's host name. However, this may not
return the fully qualified domain name that is required by some mail servers
and specifying this path allows you to set an alternative name, such as
your machine's fully qualified domain name, which you might have obtained
from an external function such as gethostname or getaddrinfo.

smtp://mail.example.com - This connects to the mail server at example.com and
sends your local computer's host name in the HELO / EHLO command.

smtp://mail.example.com/client.example.com - This will send client.example.com
in the HELO / EHLO command to the mail server at example.com.

**Comment by bagder** [comment]
The trailing full stop line is (weirdly enough) presumed to be sent by the user. Just add a `.^m` as a last line in the content you upload. Clearly room for improvement, but this is actually how it is intended to work right now and is done by numerous test cases in the test suite as well.

**Comment by MulMic** [comment]
Thanks for the superfast reply. Yes, it works as advised, but, if I enter any part of the cited curl command-line curl sends the hostname as EHLO argument as expected, only when adding the --upload-file parameter it insists on taking the filename from there to EHLO. Doesn't sound right somehow, does it ? Even if I can override it by adding the hostname to the address part. 

Anything new on the trailing full stop "." ?

**Comment by MulMic** [comment]
OK, thanks

**Comment by bagder** [comment]
Works as documented. Could of course be enhanced.
