### ISSUE TITLE
Too many calls to Curl_now()

### ISSUE THREAD

**Issue by bagder** [curl/curl#5574]
### I did this

Reported at https://curl.haxx.se/mail/lib-2020-06/0050.html

I added debug code in `Curl_now()` to check the delta time between calls to identify the number of "wasted" calls. My code then counts all invokes where the delta is 50 or less *microseconds* since the previous invoke.

In a test invoke that downloads 512MB from localhost, I ended up with about 26274 total number of Curl_now invokes.

Out of those, 26255 had a delta of 50 or less microseconds.

(It will probably make a better test case to run with a more remote server.)

### I expected the following

Fewer calls (with very low delta times).

### curl/libcurl version

current git master

### operating system

Measured on Linux

**Comment by WGH-** [comment]
I wonder what's the reporter operating system is. On Linux, `gettimeofday` is vDSO-optimized, so instead of real system call it's just a memory fetch from a special page.

**Comment by bagder** [comment]
Until someone presents numbers where these cause problems, I'm dropping this.
