### ISSUE TITLE
Compiling Curl fails to support Brotli

### ISSUE THREAD

**Issue by Integralist** [curl/curl#5578]
## I did this

```bash
$ apt-get update && apt-get install -y autoconf automake libtool brotli

$ git clone https://github.com/curl/curl /tmp/curl
$ cd /tmp/curl/
$ ./buildconf
$ ./configure 
$ make
$ make install
```

### I expected the following

Executing:

```bash
curl --compressed https://httpbin.org/brotli
```

...should have returned compressed data and not an error:

```bash
curl: (61) Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.
```

### curl/libcurl version

```bash
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system

```bash
$ uname -a
Linux bcf344edf35e 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by Integralist** [comment]
Interestingly I'm seeing conflicting information as far as which curl version should be used.

**To clarify**: the system curl was found in `/usr/bin/curl` while the newly compiled curl is placed into `/usr/local/bin/curl` (this is fine and expected).

When running `which curl` I would see the latter path in the output (which is expected). If I check the `$PATH` environment variable I see that `/usr/local/bin` appears _before_ `/usr/bin` (again this is all fine and what I would expect).

But I get different version output when executing `curl -V` compared to `/usr/local/bin/curl -V` ?

**Example:**

```bash
$ curl -V
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

$ /usr/local/bin/curl -V
curl 7.71.0-DEV (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
WARNING: curl and libcurl versions do not match. Functionality may be affected.
```

Nearly all of the information is the same except for two things...

1. the release date is different (`curl -V` makes me think it's still using the system curl)
2. the warning `WARNING: curl and libcurl versions do not match. Functionality may be affected.` when using `/usr/local/bin/curl` (this makes me think that because of this the newly compiled curl maybe isn't installed correctly or because of this error the system curl is being used).

**Comment by bagder** [comment]
When `./configure` is done, it presents a summary of what it found and the build it is setup to do. There's a line in there that should look similar to:
~~~
  brotli:           enabled (libbrotlidec)
~~~
.... when brotli was detected and enabled properly. Is that present in your build summary?

> WARNING: curl and libcurl versions do not match. Functionality may be affected

Yes, this is your new curl tool finding and using your *old* libcurl. You need to make sure the new library is found and used instead. Possibly by changing the `ld.so.conf` file or similar.

**Comment by Integralist** [comment]
Yup the specific brotli line you mentioned does say brotli enabled.

I'm unfamiliar with `ld.so.conf`, do you have any advice on what I would need to set in that configuration file? Otherwise I'll try and have a poke around with it.

**Comment by Integralist** [comment]
So `/etc/ld.so.conf` looks to contain an include statement of any conf files found within `/etc/ld.so.conf.d/`:

```
include /etc/ld.so.conf.d/*.conf
``` 

While the contents of that directory is:

- `fakeroot-x86_64-linux-gnu.conf`
- `libc.conf`
- `x86_64-linux-gnu.conf`

## fakeroot-x86_64-linux-gnu.conf

```
/usr/lib/x86_64-linux-gnu/libfakeroot
```

## libc.conf

```
# libc default configuration
/usr/local/lib
```

## x86_64-linux-gnu.conf

```
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

**Comment by bagder** [comment]
`man ld.so` has all the info. This is not about curl, this is about how your linker finds shared libs.

**Comment by bagder** [comment]
Presumably curl works as expected. Closing.
