### ISSUE TITLE
Pass URLs into the config flag.

### ISSUE THREAD

**Issue by AdamKearn** [curl/curl#5581]
### curl/libcurl version

[curl -V output]

### operating system
Windows 10 1909

Hey guys,

Not an issue/bug just a question...
I was wondering if the `-K` flag could be adapted to accept URLs??? 
Then to download and install my batch script I can just do the following:
`curl -K script.domain.com`

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

But yes, you can provide URLs in the config file. `url = https://example.com`

**Comment by jay** [comment]
Ref: https://curl.haxx.se/mail/archive-2020-06/0045.html
