### ISSUE TITLE
quiche version fails to build, because of missing `quiche_conn_set_keylog_path`

### ISSUE THREAD

**Issue by T4cC0re** [curl/curl#5600]
### I did this

As part of updating my Arch Linux User Repository package [curl-http3](https://aur.archlinux.org/packages/curl-http3/) I ran into issues compiling it. (The link does not contain the failing build files)

I compiled curl 7.71.0 and quiche 0.4.0 as described here: https://github.com/curl/curl/blob/master/docs/HTTP3.md#quiche-version with minor adaptions to keep ArchLinux options in the configure step (details below).

However, the compile of curl fails with this output:

```
 CC       vquic/libcurl_la-vquic.lo
vquic/quiche.c: In function 'Curl_quic_connect':
vquic/quiche.c:220:5: error: implicit declaration of function 'quiche_conn_set_keylog_path'; did you mean 'quiche_conn_set_qlog_path'? [-Werror=implicit-function-declaration]
  220 |     quiche_conn_set_keylog_path(qs->conn, keylog_file);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     quiche_conn_set_qlog_path
cc1: some warnings being treated as errors
make[2]: *** [Makefile:2645: vquic/libcurl_la-quiche.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/t4cc0re/repos/aur.archlinux.org/curl-http3/src/curl-7.71.0/lib'
make[1]: *** [Makefile:1064: all] Error 2
make[1]: Leaving directory '/home/t4cc0re/repos/aur.archlinux.org/curl-http3/src/curl-7.71.0/lib'
make: *** [Makefile:984: all-recursive] Error 1
```

https://github.com/curl/curl/blob/master/lib/vquic/quiche.c#L220 as it seems (as of quiche 0.4.0?), `quiche_conn_set_keylog_path` does no longer seem to exist/has been removed in favor of `quiche_conn_set_qlog_path`. I have not looked into this, and that is a guess though. 

Exact build commands:
`_quiche_tag` = `0.4.0`  
`pkgver` = `7.71.0`  

```
  git clone --recursive --branch ${_quiche_tag} --depth 1 https://github.com/cloudflare/quiche.git

  ## Build quiche
  cd quiche  
  cargo build --release --features pkg-config-meta
  mkdir deps/boringssl/lib
  ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) deps/boringssl/lib/
  cd ..
 
  ## Build curl
  cd "curl-${pkgver}"

  ./buildconf
## Arch Linux build flags + BoringSSL and quiche
  ./configure \
      LDFLAGS="-Wl,-rpath,${PWD}/../quiche/target/release" \
      --with-ssl=$PWD/../quiche/deps/boringssl \
      --with-quiche=$PWD/../quiche/target/release \
      --enable-alt-svc \
      --prefix=/usr \
      --mandir=/usr/share/man \
      --disable-ldap \
      --disable-ldaps \
      --disable-manual \
      --disable-shared \
      --enable-ipv6 \
      --enable-threaded-resolver \
      --with-random=/dev/urandom \
      --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
  make
```

### I expected the following

curl would build

### curl/libcurl version

7.71.0 (from tarball at https://curl.haxx.se/download/curl-7.71.0.tar.gz)
quiche source is at `commit 09688f3a1dc4909e41519c15fcea304fac05ee96 (grafted, HEAD, tag: 0.4.0)`

### operating system

```
Linux rainbowdash 5.6.19.a-1-hardened #1 SMP PREEMPT Sat, 20 Jun 2020 15:16:50 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
The current doc mentions that you need the `qlog` feature enabled too in quiche:
~~~
cargo build --release --features pkg-config-meta,qlog

**Comment by T4cC0re** [comment]
> The current doc mentions that you need the `qlog` feature enabled too in quiche:
> 
> ```
> cargo build --release --features pkg-config-meta,qlog
> ```

@bagder I tried both with and without the `qlog`, sorry I did not specify that. The commands I posted were just the last version I have on disk.

**Comment by bagder** [comment]
Then I presume `0.4.0` is a too old quiche version. Any particular reason you want to stick with that? in curl we only ever make the latest version (master) work and I basically assume everyone does like that - which then also reflects how we adjust for alt-svc support etc.

**Comment by ghedo** [comment]
Note that this doesn't have anything to do with qlog. `quiche_conn_set_keylog_path` is a new function added after `0.4.0` to configure logging of TLS secrets. If you don't want to update to the latest quiche master you can simply remove that call (you'd lose keylog support, but everything else would work fine).

**Comment by T4cC0re** [comment]
@bagder I guess I can use master and just pin a specific commit.
So basically when a new curl version gets released, I can assume it will work with the current quiche master at that time?

I just compiled with the quiche master and that works just fine, so I guess we can close this issue :)
Thanks for clarifying that. Maybe it makes sense to add this as a note to the build instructions?

I previously just used the tagged versions to have an easy version to reference, but referencing a commit is fine by me too. So I'll just do that :)

**Comment by bagder** [comment]
> So basically when a new curl version gets released, I can assume it will work with the current quiche master at that time?

My ambition is to keep current curl work with current quiche until there's some kind of first release of quiche or something that indicates that they stabelize their API. So yes, that *should* make quiche master work with the latest curl release at the time of the release.

> Maybe it makes sense to add this as a note to the build instructions?

If you follow the build instructions in the doc verbatim right now, they work...  I'm not sure what to add in the docs that doesn't mostly complicate it. Suggestions?

**Comment by T4cC0re** [comment]
> My ambition is to keep current curl work with current quiche until there's some kind of first release of quiche or something that indicates that they stabelize their API. So yes, that should make quiche master work with the latest curl release at the time of the release.

This may be a bit off-topic, but I am not committed to using quiche. If ngtcp2 is more stable, I would also be able to switch to that. Do you have any observations to share regarding that?

> If you follow the build instructions in the doc verbatim right now, they work... ? I'm not sure what to add in the docs that doesn't mostly complicate it. Suggestions?

Hm. Yeah, I guess that makes sense. My pinning of quiche was a diversion of those instructions.

**Comment by bagder** [comment]
The situation with ngtcp2+nghttp3 is very similar: they update their APIs "at will" without any releases and we update accordingly when we notice and have time. Thus curl only (attempts to) work with their master branches at any given time.

**Comment by T4cC0re** [comment]
Alright :)

Thanks for that insight!

As there is no issue with the quiche master, I will close this issue.
