### ISSUE TITLE
libcurl+schannel does not provide an option to not send client certificates

### ISSUE THREAD

**Issue by MehtabSyed** [curl/curl#5609]
### I did this
Built libcurl (7.70.0 ) with schannel support on Visual Studio 2019. On connect to microsoft site 
https://dataservice.protection.outlook.com/PsorWebService/v1/ClientSyncFile/MipPolicies
got connection issues. Analyzing found the cause, server was asking for an optional client certificate and schannel was sending one of the certs from the Cert store. 
This certificate was invalid and server responded with a 403 forbidden error.

### I expected the following
Expected an option in libcurl to disable the behavior of schannel sending client certificate. The work around found was to modify libcurl code to pass SCH_CRED_NO_DEFAULT_CREDS to AcquireCredentialsHandle in schannel.c

Added line 
schannel_cred.dwFlags |= SCH_CRED_NO_DEFAULT_CREDS;
before AcquireCredentialsHandle
line no. 763 schannel.c 

### curl/libcurl version
curl 7.70.0

### operating system
Windows 10

**Comment by jay** [comment]
See [15.4 Add option to disable client certificate auto-send](https://curl.haxx.se/docs/todo.html#Add_option_to_disable_client_cer)

**Comment by MehtabSyed** [comment]
Thanks for the update. Which libcurl release will have this addressed ?

**Comment by bagder** [comment]
@MehtabSyed this is not "fixed" so there's no planned release with it. Feel free to work on a fix.
