### ISSUE TITLE
Connection failures with parallel HTTP/2 (TCP reset)

### ISSUE THREAD

**Issue by michaelforney** [curl/curl#5611]
I was experimenting with transferring lots of files over HTTP/2 using nginx and curl, and ran into some of the following errors:

```
curl: (92) HTTP/2 stream 0 was closed cleanly, but before getting  all response header fields, treated as error
curl: (55) Connection died, tried 5 times before giving up
curl: (56) Recv failure: Connection reset by peer
```

On IRC, @bagder suggested that nginx's `http2_max_requests` setting could be related to the connection dying. Sure enough, after bumping that above the number of files being transfered, the errors went away.

### I did this

I created a `src` directory with 200 files. I also created a curl config to download these files from localhost.

```sh
mkdir src dst
for i in $(seq -w 1 200); do echo "$i" >"src/$i"; done
printf 'remote-name\nurl = "http://127.0.0.1:8080/%s"\n' $(seq -w 1 200) >config
```

Then, I configured nginx to serve these files over HTTP/2 and started it. I used a low `http2_max_requests` setting to make the errors easier to reproduce. I also enabled debug logging on stderr, which slows down nginx enough to ensure that the problem shows up.

```sh
cat >nginx.conf <<EOF
error_log stderr debug;
pid nginx.pid;
daemon off;
events {}
http {
	server {
		listen 8080 http2;
		http2_max_requests 20;
		root src;
		access_log off;
	}
}
EOF
nginx -p "$PWD" -c nginx.conf
```

On a separate terminal, I ran curl in parallel mode to download these 200 files.

```sh
cd dst
curl -sS --http2-prior-knowledge -Z -K ../config
```

The number and types of errors seem to vary from run to run. If I set `--parallel-max 2`, I only get `curl: (56) Recv failure: Connection reset by peer` errors.

Here is a log with verbose output after adding `#define DEBUG_HTTP2` to `lib/http2.c`.
[curl-log.txt](https://github.com/curl/curl/files/4834614/curl-log.txt)

### I expected the following

All the transfers should complete successfully.

### curl/libcurl version

```
curl 7.71.1-DEV (x86_64-pc-linux-gnu) libcurl/7.71.1-DEV OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) nghttp2/1.40.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets
```

### operating system

Linux arrow 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### More info

After typing up this issue, I did some more research and found some relevant links:
https://trac.nginx.org/nginx/ticket/1250
https://bugs.chromium.org/p/chromium/issues/detail?id=796199
https://bugzilla.mozilla.org/show_bug.cgi?id=1050329#c14

Based on the information in those links, I'm not so sure if this is actually a bug in curl, or nginx, or a fundamental problem with HTTP/2 and TCP. not-a-bug might be an appropriate resolution here (that appears to be what chromium has done).

**Comment by sterchelen** [comment]
Hi @michaelforney, did you saw something in `nginx`'s logs? With turning `error_log` to debug.

**Comment by bagder** [comment]
Just to check. We just landed #5643 which closes connections (better) after a GOAWAY, did it change anything in regards to this issue?

**Comment by michaelforney** [comment]
It looks like nginx also just landed a fix for https://trac.nginx.org/nginx/ticket/1250. Testing with the latest curl and nginx with that patch backported, I believe the GOAWAY is now actually getting through. I'm no longer getting any TCP reset errors, but I am still getting a bunch of the following errors:

```
curl: (92) HTTP/2 stream 0 was closed cleanly, but before getting  all response header fields, treated as error
curl: (55) Connection died, tried 5 times before giving up
```

Here are the full verbose logs for curl and nginx (the same run):
[curl.log](https://github.com/curl/curl/files/4872211/curl.log)
[nginx.log](https://github.com/curl/curl/files/4872212/nginx.log)

I don't see anything unexpected in the nginx logs. On the curl side, after it receives the GOAWAY, all the streams it started beyond the first 20 get `REFUSED_STREAM` from nghttp2. When curl opens a new connection, it  requests the next batch of files starting at `/068`, which is the last one that it tried to request from the first connection. Files 21-67 fail with an error and are not retried. Again the first 20 succeed (`/068`-`/087`), and all those after `/087` get `REFUSED_STREAM`.

After that, I see a bunch of messages that I don't know what to make of:

```
* http2_recv: easy 0x7fd602de4060 (stream 0) win 33554352/4294967295
* end of stream
```

I'm not really able to follow what's going on after that.

**Comment by michaelforney** [comment]
Unfortunately, yes. I just tested with curl git and nginx git. After a bunch of runs, I've seen the following errors:

```
curl: (92) HTTP/2 stream 0 was closed cleanly, but before getting  all response header fields, treated as error
curl: (55) Connection died, tried 5 times before giving up
curl: (56) Failure when receiving data from the peer
```

In most runs, I only see error 92. Errors 55 and 56 are much less common. I think that the main problem is error 92. For some reason curl is not retrying those requests (whose streams were closed due to GOAWAY).

**Comment by bagder** [comment]
Added to KNOWN_BUGS now
