### ISSUE TITLE
Unpaired curl_global_init/curl_global_cleanup

### ISSUE THREAD

**Issue by qiandu2006** [curl/curl#5622]
https://github.com/curl/curl/blob/40b4fdb88fdec3627147129d1f71a815842ec638/docs/examples/multithread.c#L74

**Comment by sterchelen** [comment]
Thanks for your first issue @qiandu2006, but it is a bit too light. Could you add some context around it?

**Comment by qiandu2006** [comment]
In the document about [curl_global_cleanup](https://curl.haxx.se/libcurl/c/curl_global_cleanup.html)
`This function releases resources acquired by curl_global_init.

You should call curl_global_cleanup once for each call you make to curl_global_init, after you are done using libcurl.`

But in this file, there is no curl_global_cleanup called, so this may be an error?

**Comment by bagder** [comment]
It is indeed a bug.
