### ISSUE TITLE
HTTP/2 stream errors

### ISSUE THREAD

**Issue by ZockerBoysHD** [curl/curl#5649]
### I did this

download curl source, 
install libcurl4 , libcurl4-gnutls-dev and the nghttp2 package

executed ./configure --with-gnutls --with-nghttp2

but it wont configure with my stuff selected 
https://screens.egopvp.com/files/2020/07/03/ts3client_win64_KEii9sKLDH.png

### I expected the following
A configured curl version with http/2 and SSL support

### curl/libcurl version

curl - 7.71.0
libcurl - 7.71.0 (libcurl4)

[curl -V output]
https://screens.egopvp.com/files/2020/07/03/ts3client_win64_NaC9jIWu26.png

### operating system
Debian 10

Linux Debian-103-buster-64-minimal 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by ZockerBoysHD** [comment]
when i have libssl installed tho, ssl support works tho.

after i installed openssl today, i got this error tho:
Error state: HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) - CURL error code 92 (Stream error in the HTTP/2 framing layer)

when connecting to my FiveM server. 
I did activate http2 and ssl mod on apache too cause the webpage needs it. 

I can confirm that without curl ssl support i did not have the error at all.

**Comment by bagder** [comment]
This is like a mix of multiple issues. Can you make up your mind on what this issue is about and we can focus on that? Is your issue building curl or running http2 against some site?

**Comment by ZockerBoysHD** [comment]
yeah im sorry. i played arround with it and now got curl running with ssl & http/2 support.

so my only problem is this:

For some reason after i enabled ssl support, curl seems to be generating this error:
Error state: HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2) - CURL error code 92 (Stream error in the HTTP/2 framing layer)

without ssl enabled in libcurl it works normal and doesnt give me the error.  
I cant change anything about the command being executed cause its integrated into the FiveM client. But i can change the Curl installation on my server.

**Comment by ZockerBoysHD** [comment]
Current curl -V output:

curl 7.71.0 (x86_64-pc-linux-gnu) libcurl/7.71.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.36.0
Release-Date: 2020-06-24
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by ZockerBoysHD** [comment]
I suppose my traffic gets somehow routed through apache?? or gets a header applied and due to http/2 not supporting it it gives me this error. 
im gonna disable http/2 support and check again

**Comment by sterchelen** [comment]
Hard to guess what is happening without the command and the output. Could you post, here, the result of your command with the verbose mode activated, please?

**Comment by bagder** [comment]
We need to be able to reproduce the problem or you need to provide a lot of (more) details otherwise there's not a lot we can do about this issue.

**Comment by ZockerBoysHD** [comment]
i cant tell which commands are being sent or which exact answer the cleint gets. as i said its all built into the "FiveM" client.


i can supply some tcpdump of when i got that error tho. but idk. 

Still, can my apache conf have anything to do with this ? like is apache adding some headers to the requests even if i use my ip and a different port for the game than any of the ones apache is listening on?

**Comment by ZockerBoysHD** [comment]
the error above is the only thing the client or the server are giving me. no info where or what cause it

**Comment by bagder** [comment]
Then it's hard for us to do anything. I would urge you to try curl command lines against the sever to see if you can reproduce the problem, and if so, tell us what version of apache httpd the server runs.

**Comment by ZockerBoysHD** [comment]
it has the libhttp-client with a json containing info about version 0.1.0 
the libhttp-server with the same version.

it has a .so file of both client & server and a json for both of them. 
the libhttp-server.json contains this:

`{
	"name": "net:http-server",
	"version": "0.1.0",
	"dependencies": [
		"fx[2]",
		"net:tcp-server",
		"vendor:picohttpparser",
		"vendor:nghttp2"
	],
	"provides": []
}
`

i understand it as if it uses my os's nghttp2 version, which is the latest available for debian 10.3

**Comment by bagder** [comment]
We need to be able to reproduce the problem.

**Comment by StefanYohansson** [comment]
@ZockerBoysHD can you try to configure with `--enable-debug` and SSL enabled, make it and see if something useful is added to your output?

**Comment by StefanYohansson** [comment]
also for some reason, the CI of the FiveM deletes the latest version and installs one explicit version.

https://github.com/citizenfx/fivem/blob/9337fca3a0945da541b9f2f1f4ffd1935467f252/code/tools/ci/build_server_2.sh#L35

maybe you should try that version and see if it is on purpose.

**Comment by ZockerBoysHD** [comment]
Thanks Guys for your help but in some version along the Line it got fixxed. We never get this error at the moment. seemed like a FiveM problem. Tanks anyway!
