### ISSUE TITLE
How to get a frame of image data from RTSP stream

### ISSUE THREAD

**Issue by trungtv94** [curl/curl#5651]
I want to capture a frame of image from the ip camera with Curl. Is it possible?

I got example in https://curl.haxx.se/libcurl/c/rtsp.html, it work good but I dont know where I can get image data.

Other document I found that can use CURLOPT_INTERLEAVEFUNCTION and CURLOPT_INTERLEAVEDATA to get RTP data from RTSP sever. But I still don't understand where I can get image data.

Can you explain for me? Thank you so much.

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
