### ISSUE TITLE
http2 trailer show header 

### ISSUE THREAD

**Issue by MoMannn** [curl/curl#5663]
### I did this

So I called a http2 server that sends trailer headers (so headers frame after data frames) like so:

`curl url --http2-prior-knowledge --verbose`

I got the response as such:

```
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe0c900d600)
> GET / HTTP/2
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200 
< trailer: test
< 
* Connection #0 to host localhost left intact
Hello world!* Closing connection 0
```

### I expected the following

I expected that after data headers: `test: ok` would also be displayed.

### curl/libcurl version

curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2

### operating system

Mac os 10.15.4

**Comment by bagder** [comment]
This is a report for an older curl version. We changed the trailer handling in 7.71.0 (54a2b63c704cd96) but it seems to be broken currently anyway.

**Comment by bagder** [comment]
BTW, in order to reproduce I used thes cmdlines (invoked in the curl source root):
1. `nghttpd --no-tls --trailer 'foo: bar' 8000`
2. `./src/curl --http2-prior-knowledge --verbose localhost:8000/README`
