### ISSUE TITLE
windows make fail for curl 7.71.1

### ISSUE THREAD

**Issue by LJWxyz** [curl/curl#5674]
### I did this
>mingw32-make mingw32
mingw32-make -C lib -f Makefile.m32
mingw32-make[1]: Entering directory 'F:/ProgramSetup/open source/secure/curl-7.71.1/lib'
gcc -I. -I../include  -g -O2 -Wall -W -fno-strict-aliasing -m32 -DBUILDING_LIBCURL -c altsvc.c -o altsvc.o
In file included from curl_setup.h:75:0,
                 from altsvc.c:26:
config-win32.h:729:5: error: unknown type name 'ADDRESS_FAMILY'
     ADDRESS_FAMILY sun_family;
     ^~~~~~~~~~~~~~
Makefile.m32:375: recipe for target 'altsvc.o' failed
mingw32-make[1]: *** [altsvc.o] Error 1
mingw32-make[1]: Leaving directory 'F:/ProgramSetup/open source/secure/curl-7.71.1/lib'
Makefile:44: recipe for target 'mingw32' failed
mingw32-make: *** [mingw32] Error 2

-curl VER-
>curl -V
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

Did I do something wrong?

**Comment by bagder** [comment]
I would guess that mingw needs something more included to get `ADDRESS_FAMILY` defined?

**Comment by jay** [comment]
Winsock is supposed to define ADDRESS_FAMILY, is that missing from mingw winsock includes?

https://github.com/curl/curl/blob/5a1fc8d33808d7b22f57bdf9403cda7ff07b0670/lib/config-win32.h#L721-L732

**Comment by vszakats** [comment]
In [my copy](https://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v7.0.0.tar.bz2) of `mingw-w64-headers`, `ADDRESS_FAMILY` is defined in `winsock2.h` and `winsock2.h` is #included by `ws2tcpip.h`. Though it's possible this wasn't always the case.

@LJWxyz Can you verify the above in your mingw headers?

**Comment by LJWxyz** [comment]
yes it is included already in ws2tcpip.h

#if (defined _WINSOCK_H && !defined _WINSOCK2_H)
#error "ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."
#endif

#include <winsock2.h>
#ifdef  __cplusplus
extern "C" {
#endif

/**
*The IP ...

**Comment by LJWxyz** [comment]
Sorry I am quite new to github and this project the snnipet is at 
>a/lib/config-win32.h b/lib/config-win32.h
and the changes is simply remove(-) and add(+) right?
Just to confirm.

**Comment by jzakrzewski** [comment]
Yeah, it's a diff format. 
Means that in curl source code you should find lib/config-win32.h and few lines below line 723 replace ws2tcpip.h with winsock2.h

**Comment by LJWxyz** [comment]
replaced sadly it doesn't seem to work.Could my path included unnessary binaries? 
>
D:\Coding\C\ALLCinone>set PATH=D:\Coding\C\ALLCinone\MinGW64\mingw32\bin;D:\Coding\C\ALLCinone\MinGW64\bin;D:\Coding\C\ALLCinone\MinGW64\x86_64-w64-mingw32\bin;C:\Windows\system32;C:\Windows;....

D:\Coding\C\ALLCinone>cmd /k"set includepath=D:\Coding\C\ALLCinone\MinGW64\include"

D:\Coding\C\ALLCinone>cd F:\ProgramSetup\open source\secure\curl-7.71.1

F:\ProgramSetup\open source\secure\curl-7.71.1>mingw32-make mingw32
mingw32-make -C lib -f Makefile.m32
mingw32-make[1]: Entering directory 'F:/ProgramSetup/open source/secure/curl-7.71.1/lib'
gcc -I. -I../include  -g -O2 -Wall -W -fno-strict-aliasing -m32 -DBUILDING_LIBCURL -c altsvc.c -o altsvc.o
In file included from curl_setup.h:75:0,
                 from altsvc.c:26:
config-win32.h:729:5: error: unknown type name 'ADDRESS_FAMILY'
     ADDRESS_FAMILY sun_family;
     ^~~~~~~~~~~~~~
Makefile.m32:375: recipe for target 'altsvc.o' failed
mingw32-make[1]: *** [altsvc.o] Error 1
mingw32-make[1]: Leaving directory 'F:/ProgramSetup/open source/secure/curl-7.71.1/lib'
Makefile:44: recipe for target 'mingw32' failed
mingw32-make: *** [mingw32] Error 2

F:\ProgramSetup\open source\secure\curl-7.71.1>

**Comment by vszakats** [comment]
According to the mingw-w64 repo, `ADDRESS_FAMILY` was [added](https://github.com/mirror/mingw-w64/commit/cf6afc57179a5910621215f8f4037d406892072c#diff-7ec800822a43df5faa27eba737c7896d) back in 2010-08-10, released likely that year or 2011 latest.

@LJWxyz Is it possible that you're using a mingw environment that may predate that? Can you give us some hints of the mingw version/distro you're using?

**Comment by LJWxyz** [comment]
mingw-get-setup.exe ,file ver:0.603.243571
the copyright shows:2009-2013，MinGW.org project

**Comment by vszakats** [comment]
@LJWxyz Thank you!

It's been long I had a look at the original `mingw.org` project, and if I followed their pointers correctly, this is their latest Win32 header package: <https://osdn.net/projects/mingw/downloads/73281/w32api-5.3.4-mingw32-dev.tar.xz/>, dated 2020-07-06.

Interestingly, this release **doesn't** define `ADDRESS_FAMILY` anywhere. And even though the `mingw.org` page states to share Win32 headers with the Cygwin project, this no longer appears to be the case, as Cygwin had switched to the `mingw-w64` headers in the past and those are therefore up-to-date. I couldn't figure out where `mingw.org` keeps their repositories. It's possible they are still in CVS.

May I ask what is your mingw `gcc` version?

**Comment by janux75** [comment]
I have the same problem gcc 4.7.1

**Comment by vszakats** [comment]
Thank you, so this appears to affect classic mingw and/or 10+ year old mingw-w64 environments.

One crude solution is to check for a '#define' [committed](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/cf6afc57179a5910621215f8f4037d406892072c/) together with `ADDRESS_FAMILY` typedef. One such symbol is `LUP_SECURE`. This method may break if an alternate header implementation adds this `#define` without adding the typedef. 

Another option is to check `!defined(__MINGW32__) || defined(__MINGW64_VERSION_MAJOR)` which will enable this option on any platform except classic `mingw`. This will keep breaking on mingw-w64 released 10+ years ago.

**Comment by vszakats** [comment]
Please try this patch on various Windows platforms to see if the Unix sockets feature gets correctly enabled/disabled:
```diff
diff --git a/lib/config-win32.h b/lib/config-win32.h
index 76ee6b1a7..eeaa12655 100644
--- a/lib/config-win32.h
+++ b/lib/config-win32.h
@@ -718,18 +718,22 @@ Vista
 #define USE_WIN32_CRYPTO
 #endif
 
+/* On MinGW the ADDRESS_FAMILY typedef was committed [1] alongside LUP_SECURE,
+   so we use it to check for the presence of the typedef. */
+#include <ws2tcpip.h>
+#if !defined(__MINGW32__) || defined(LUP_SECURE)
 /* Define to use Unix sockets. */
 #define USE_UNIX_SOCKETS
 #if !defined(UNIX_PATH_MAX)
   /* Replicating logic present in afunix.h of newer Windows 10 SDK versions */
 # define UNIX_PATH_MAX 108
-# include <ws2tcpip.h>
   /* !checksrc! disable TYPEDEFSTRUCT 1 */
   typedef struct sockaddr_un {
     ADDRESS_FAMILY sun_family;
     char sun_path[UNIX_PATH_MAX];
   } SOCKADDR_UN, *PSOCKADDR_UN;
 #endif
+#endif
 
 /* ---------------------------------------------------------------- */
 /*                       ADDITIONAL DEFINITIONS                     */
```

It tested OK with the latest `mingw-w64`.
