### ISSUE TITLE
curl in iOS 13 & cellular & HTTPS is very slow in first connect

### ISSUE THREAD

**Issue by yuanjilee** [curl/curl#5678]
### I did this

I have try Wifi or HTTP or blew iOS 13, it's normal and fast.

Only timeout in first or second connect, after connected, the network request is recover OK.

### I expected the following

I expected the specific situation have a normal but not always timeout in first connect.

### curl/libcurl version

V7.71.1 （I have try the newest version）

[curl -V output]

### operating system
~~~
log : Request URL is https://office.project.sumpay.cn/api/approval/group-templates/for/me, method GET
log : Request URL is https://office.project.sumpay.cn/api/approvals/waiting/count, method GET
*   Trying 192.168.11.31:443...
*   Trying 192.168.11.31:443...
* Connected to office.project.sumpay.cn (192.168.11.31) port 443 (#0)
* ALPN, offering http/1.1
* Connected to office.project.sumpay.cn (192.168.11.31) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate: office.project.sumpay.cn
* Server certificate: Encryption Everywhere DV TLS CA - G1
* Server certificate: DigiCert Global Root CA
> GET /api/approvals/waiting/count HTTP/1.1


Host: office.project.sumpay.cn

Accept: */*

Content-type:application/json

User-Agent:Worktile-Enterprise

access-token:3ce9f2a927aa4242adcd0e1a9d2e2603

app-key:65dddfa99d3d42758fd9c02ea6554e41

client-version:7.3.0

device-id:33C1907B-7780-49B2-8643-C7B490C50582

signature:528b4c9f

store-from:AppStore

timestamp:1594360614

version:1



* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate: office.project.sumpay.cn
* Server certificate: Encryption Everywhere DV TLS CA - G1
* Server certificate: DigiCert Global Root CA
> GET /api/approval/group-templates/for/me HTTP/1.1


*   Trying 192.168.11.31:443...
*   Trying 192.168.11.31:443...
* Connection failed
* Connection failed
* connect to 192.168.11.31 port 443 failed: Operation timed out
* connect to 192.168.11.31 port 443 failed: Operation timed out
* Failed to connect to office.project.sumpay.cn port 443: Operation timed out
* Failed to connect to office.project.sumpay.cn port 443: Operation timed out
* Closing connection 0
* Closing connection 0
~~~

**Comment by jay** [comment]
It looks like a network issue, not a curl issue.

**Comment by yuanjilee** [comment]
> It looks like a network issue, not a curl issue.

I have the same guess first. But I have a lot of test,  the issue only occur in the specific situation.  with same condition， but on `Android`, or `iOS < 13`,  or with `Wifi`  or `HTTP`, all this situation is OK, but `iOS 13 & cellular & HTTPS` the first connect failed. I am trying to figure out if Apple does something in iOS 13. do someone have the same case?

**Comment by carenas** [comment]
192.168.11.31 is an internal (RFC1918 reserved IP) which shouldn't be routable in the public internet (what you should get when connected by cellular) resulting in "connection timeout".

**Comment by bagder** [comment]
If the only difference is the iOS version, then I blame the OS. I'm not aware of anything we need to do special as of iOS 13, but then I'm also not very knowledgeable about Apple details.

**Comment by yuanjilee** [comment]
> 192.168.11.31 is an internal (RFC1918 reserved IP) which shouldn't be routable in the public internet (what you should get when connected by cellular) resulting in "connection timeout".

Yes, I used VPN to access internal network, and i have exclude the problem of VPN.

**Comment by yuanjilee** [comment]
> If the only difference is the iOS version, then I blame the OS. I'm not aware of anything we need to do special as of iOS 13, but then I'm also not very knowledgeable about Apple details.

I find [Requirements for trusted certificates in iOS 13 and macOS 10.15](https://support.apple.com/en-us/HT210176), but my certificates conform all the requirements.  I am continue trying.

**Comment by hetz** [comment]
I get same problem

**Comment by bagder** [comment]
Run the code with a debugger and find out where in the code and in which state curl is when it seems to be slow/idle?

I presume you build curl to use Secure Transport for this, or what TLS library do you use?

**Comment by bagder** [comment]
Nobody seems to work on this and we have not gotten more info. The questions asked are not answered after months. The issue *sounds* like an OS/network stack issue and not a curl issue. Closing.
