### ISSUE TITLE
support smbv2/3 and/or update documentation

### ISSUE THREAD

**Issue by tbugfinder** [curl/curl#5679]
### I did this
Upload file from Linux to Windows share using curl.

### I expected the following
Authentication applied successfully and file copied.

Apart from an issue there isn't proper documentation included (or I least I didn't notice it) that curl only supports smbv1. It would be very convenient if it would support SMBv2/3 as those are the protocols used.

### curl/libcurl version

[curl -V output]
7.70

### operating system
Linux

**Comment by bagder** [comment]
It *is* mentioned in the docs already. The question is where did you expect to find this detail where you didn't see it this time?

(We don't keep feature-request issues open in this tracker, as we reserve that for bugs and problems.)

**Comment by tbugfinder** [comment]
Usually I start off reading man pages.
There I didn't came across the limit.

**Comment by bagder** [comment]
The `CURLOPT_URL` documentation/man page includes this information: https://curl.haxx.se/libcurl/c/CURLOPT_URL.html

**Comment by tbugfinder** [comment]
I read this one
https://curl.haxx.se/docs/manpage.html

**Comment by bagder** [comment]
And where in that page did you expect to find this information? Ie where would you say it would make sense to have it added?

**Comment by tbugfinder** [comment]
like right at the top, indeed.
