### ISSUE TITLE
NTLM Authenticate failed in curl 7.71.1 when missing getpeername

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#5693]
### I did this

After i have upgraded libcurl to 7.71.1,  the NTLM Authenticate will fail, which works well before upgrading (version is 7.55.1)

And i have get logs as follow. Could you please give some advise for this, many thanks.

 [my_curl_debug_callback] This: 5412314808 HEADER_IN :WWW-Authenticate: NTLM TlRMTVNTUAA..............................bwBvAG0ABwAIAMU9x7ajW9YBAAAAAA==
 
 [my_curl_debug_callback] This: 5412314808 HEADER_IN :WWW-Authenticate: Negotiate
 
[my_curl_debug_callback] This: 5412314808 HEADER_IN :X-Powered-By: ASP.NET
 
[my_curl_debug_callback] This: 5412314808 HEADER_IN :X-FEServer: WIN-1TRC9B5MS6A
 
[my_curl_debug_callback] This: 5412314808 HEADER_IN :Date: Thu, 16 Jul 2020 19:02:55 GMT
 
 [my_curl_debug_callback] This: 5412314808 HEADER_IN :Content-Length: 0
 
[my_curl_debug_callback] This: 5412314808 HEADER_IN :
 
 [my_curl_debug_callback] This: 5412314808 TEXT :Connection cache is full, closing the oldest one.
 
 [my_curl_debug_callback] This: 5412314808 TEXT :Closing connection 54
 
 [my_curl_debug_callback] This: 5412314808 TEXT :TLSv1.2 (OUT), TLS alert, close notify (256):
 
 [my_curl_debug_callback] This: 5412314808 TEXT :Maximum (5) redirects followed

### curl/libcurl version

7.71.1

### operating system

Android / iOS

**Comment by bagder** [comment]
What TLS library and version are you using?

We can probably not do much about this issue unless you help us reproduce the issue...

**Comment by ustcqidi** [comment]
@bagder many thanks for your response.

I am using openssl 1.1.1g

from the log, it seems always Issue another request when NTLM authentication. and then cause Maximum (5) redirects followed

![image](https://user-images.githubusercontent.com/2238185/87840902-949a8d00-c8d4-11ea-9e2d-235b7477927a.png)
