### ISSUE TITLE
libcurl DLL can't be deleted

### ISSUE THREAD

**Issue by CruiseYoung** [curl/curl#5696]
### I did this
1、MakefileBuild.vc
!IF "$(VC)"=="6"
CC_NODEBUG  = $(CC) /O2 /DNDEBUG
CC_DEBUG    = $(CC) /Od /Gm /Zi /D_DEBUG /GZ
CFLAGS      = /I. /I../lib /I../include /nologo /W4 /GX /DWIN32 /YX /FD /c /DBUILDING_LIBCURL /D_USING_V110_SDK71_ /D_UNICODE /DUNICODE /D_WIN32_WINDOWS=0x0501 /D_WIN32_WINNT=0x0501 /DWINVER=0x0501
!ELSE
CC_NODEBUG  = $(CC) /O2 /DNDEBUG
CC_DEBUG    = $(CC) /Od /D_DEBUG /RTC1 /Z7 /LDd
CFLAGS      = /I. /I ../lib /I../include /nologo /W4 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL /D_USING_V110_SDK71_ /D_UNICODE /DUNICODE /D_WIN32_WINDOWS=0x0501 /D_WIN32_WINNT=0x0501 /DWINVER=0x0501
!ENDIF

2、compile
nmake /f Makefile.vc mode=static RTLIBCFG=static ENABLE_IDN=no VC=14 GEN_PDB=yes DEBUG=no MACHINE=x86 WITH_SSL=static SSL_PATH=D:\comm\openssl\release_x86 WITH_ZLIB=static ZLIB_PATH=D:\comm\zlib\release_x86 WITH_PREFIX=D:\comm\cul\release_x86

3、.vcxproj
C/C++ -->Preprocessor -->Preprocessor Definitions:
CURL_STATICLIB

Linker -->Input -->Additional Dependeencies:
zlib.lib
libssl.lib
libcrypto.lib
libcurl_a.lib

4、Output File
xxx.dll

~~~c
#include <curl/curl.h>

class curl_environ
{
public:

    curl_environ()
        : sslset_result_(CURLSSLSET_OK)
        , init_result_(CURLE_OK)
    {
        sslset_result_ = curl_global_sslset(CURLSSLBACKEND_SCHANNEL, NULL, NULL);
        init_result_ = curl_global_init(CURL_GLOBAL_ALL);
    }

    ~curl_environ()
    {
        curl_global_cleanup();
    }

    operator bool() const
    {
        return sslset_result_ == CURLSSLSET_OK && init_result_ == CURLE_OK;
    }
private:
    CURLsslset sslset_result_;
    CURLcode init_result_;
};

#include <mutex>
#include "curl_environ.h"

std::shared_ptr<curl_environ> g_curl_env = nullptr;
int g_update_env_init_count = 0;
std::mutex g_update_env_init_mtx;

#   ifdef UPDATEDLL_EXPORTS
#       define UPDATEDLL_API extern "C" __declspec(dllexport)
#   else
#       define UPDATEDLL_API extern "C" __declspec(dllimport)
#   endif

UPDATEDLL_API bool UpdateEnvInit()
{
    std::lock_guard<std::mutex> lk(g_update_env_init_mtx);
    if (g_update_env_init_count++ != 0)
    {
        return true;
    }

    g_curl_env = std::make_shared<curl_environ>();
    return true;
}

UPDATEDLL_API void UpdateEnvUninit()
{
    std::lock_guard<std::mutex> lk(g_update_env_init_mtx);
    if (g_update_env_init_count == 0)
    {
        return;
    }

    if (--g_update_env_init_count != 0)
    {
        return;
    }

    g_curl_env.reset();
}
~~~

5、xxx_test

~~~c
#include <future>
#include "dll_parser.h"
#include <tchar.h>

int main(int argc, char *argv[])
{
    {
        auto test_future = std::async([]()
        {
            dll_parser_win dll;
            if (!dll.load(_T("xxx.dll"))) //LoadLibrary
            {
                return;
            }

            dll.excecute_function<bool()>("UpdateEnvInit");
            dll.excecute_function<void()>("UpdateEnvUninit");

            return; // FreeLibrary
        });

        test_future.wait();
    }
   system("pause");
    return 0;
}
~~~

6、 breakpoint : system("pause");

delete xxx.dll  
Can't delete xxx.dll 

### I expected the following
xxx.dll can be deleted

### curl/libcurl version
7.71.1

[curl -V output]
7.71.1

### operating system
Windows Servr 2008 R2 Datacenter/VS 2015 Update 3

Focus:
Curl_ossl_init
Curl_ossl_cleanup

**Comment by bagder** [comment]
I don't understand how libcurl is at all involved in a DLL not being possible to delete?

**Comment by CruiseYoung** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Daniel Stenberg <notifications@github.com>
发送时间: Saturday, July 18, 2020 1:32:24 AM
收件人: curl/curl <curl@noreply.github.com>
抄送: CruiseYoung <CruiseYoung@outlook.com>; Author <author@noreply.github.com>
主题: Re: [curl/curl] WITH_SSL=static Curl_ossl_init Curl_ossl_cleanup (#5696)


I don't understand how libcurl is at all involved in a DLL not being possible to delete?

―

**Comment by CruiseYoung** [comment]
The demo has been sent to daniel@haxx.se

**Comment by bagder** [comment]
I received it, but I don't understand what I'm supposed to do with it.

**Comment by CruiseYoung** [comment]
I mean the resources requested in Curl_ossl_init are not cleaned up in Curl_ossl_cleanup.



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Daniel Stenberg <notifications@github.com>
发送时间: Tuesday, July 21, 2020 4:32:25 PM
收件人: curl/curl <curl@noreply.github.com>
抄送: CruiseYoung <CruiseYoung@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [curl/curl] libcurl DLL can't be deleted (#5696)


I received it, but I don't understand what I'm supposed to do with it.

―

**Comment by CruiseYoung** [comment]
The resources requested in Curl_ossl_init are not cleaned up in Curl_ossl_cleanup

**Comment by bagder** [comment]
Wouldn't that cause a memory leak? We don't seem to get any leaks reported.

**Comment by CruiseYoung** [comment]
It should not be a memory problem, it will disappear when openssl dependency is removed.

**Comment by CruiseYoung** [comment]
/**
 * Global SSL init
 *
 * @retval 0 error initializing SSL
 * @retval 1 SSL initialized successfully
 */
static int Curl_ossl_init(void)
{
  OPENSSL_load_builtin_modules();

#ifdef USE_OPENSSL_ENGINE
  ENGINE_load_builtin_engines();
#endif

/* CONF_MFLAGS_DEFAULT_SECTION was introduced some time between 0.9.8b and
   0.9.8e */
#ifndef CONF_MFLAGS_DEFAULT_SECTION
#define CONF_MFLAGS_DEFAULT_SECTION 0x0
#endif

#ifndef CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG
  CONF_modules_load_file(NULL, NULL,
                         CONF_MFLAGS_DEFAULT_SECTION|
                         CONF_MFLAGS_IGNORE_MISSING_FILE);
#endif

#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) && \
    !defined(LIBRESSL_VERSION_NUMBER)
  /* OpenSSL 1.1.0+ takes care of initialization itself */
#else
  /* Lets get nice error messages */
  SSL_load_error_strings();

  /* Init the global ciphers and digests */
  if(!SSLeay_add_ssl_algorithms())
    return 0;

  OpenSSL_add_all_algorithms();
#endif

  Curl_tls_keylog_open();

  /* Initialize the extra data indexes */
  if(ossl_get_ssl_conn_index() < 0 || ossl_get_ssl_sockindex_index() < 0)
    return 0;

  return 1;
}

/* Global cleanup */
static void Curl_ossl_cleanup(void)
{
#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) && \
    !defined(LIBRESSL_VERSION_NUMBER)
  /* OpenSSL 1.1 deprecates all these cleanup functions and
     turns them into no-ops in OpenSSL 1.0 compatibility mode */
#else
  /* Free ciphers and digests lists */
  EVP_cleanup();

#ifdef USE_OPENSSL_ENGINE
  /* Free engine list */
  ENGINE_cleanup();
#endif

  /* Free OpenSSL error strings */
  ERR_free_strings();

  /* Free thread local error state, destroying hash upon zero refcount */
#ifdef HAVE_ERR_REMOVE_THREAD_STATE
  ERR_remove_thread_state(NULL);
#else
  ERR_remove_state(0);
#endif

  /* Free all memory allocated by all configuration modules */
  CONF_modules_free();

#ifdef HAVE_SSL_COMP_FREE_COMPRESSION_METHODS
  SSL_COMP_free_compression_methods();
#endif
#endif

  Curl_tls_keylog_close();
}

==============================


The problem occurs in the release of resources after the statement OPENSSL_load_builtin_modules().

**Comment by jay** [comment]
Are you using an old version of OpenSSL? This sounds like #3333 but I don't understand what it has to do with deleting the DLL.

**Comment by CruiseYoung** [comment]
I'm using the latest version of openssl 1.1.1g.

There is a business in the project that needs to delete the dll file that uses the libcurl library.

**Comment by jay** [comment]
How do you know there's a memory leak and what makes you think curl is responsible? Does whatever is reporting it to you identify the cause? I still don't understand what this has to do with deleting the DLL.

**Comment by CruiseYoung** [comment]
（1）nmake /f Makefile.vc mode=static RTLIBCFG=static ENABLE_IDN=no VC=14 GEN_PDB=yes DEBUG=no MACHINE=x86 WITH_ZLIB=static ZLIB_PATH=D:\comm\zlib\release_x86 WITH_PREFIX=D:\comm\cul\release_x86

（2）nmake /f Makefile.vc mode=static RTLIBCFG=static ENABLE_IDN=no VC=14 GEN_PDB=yes DEBUG=no MACHINE=x86 WITH_SSL=static SSL_PATH=D:\comm\openssl\release_x86 WITH_ZLIB=static ZLIB_PATH=D:\comm\zlib\release_x86 WITH_PREFIX=D:\comm\cul\release_x86

No changes to the demo.
It's just that the commands for compiling libcurl are different, and there will be different results. Command (1) did not introduce openssl, and the results of the demo operation met expectations.

Command (2) adds "WITH_SSL=static SSL_PATH=D:\comm\openssl\release_x86" to command (1), and introduces openssl to support https. Therefore, the Curl_ossl_init function is called in curl_global_init and the Curl_ossl_cleanup function is called in curl_global_cleanup. The result of the demo operation will lead to the result that the dll cannot be deleted.

Through the comparison operation, it can be determined that Curl_ossl_init and the Curl_ossl_cleanup operation does not correspond to each other, but I am not sure whether this problem is a bug in libcurl itself or a bug in openssl.

**Comment by bagder** [comment]
> Curl_ossl_init and the Curl_ossl_cleanup operation does not correspond to each other

If there's not a corresponding cleanup call, then there will be a memory leak. We don't see memory leaks and we don't see them reported. So we're back at: please elaborate.

**Comment by CruiseYoung** [comment]
I did not see a memory leak, but the same operation has different results in libcurl dependent and non-dependent openssl. This is where I am puzzled.

**Comment by jay** [comment]
> The result of the demo operation will lead to the result that the dll cannot be deleted.

How is this a curl problem? I still don't understand. Probably OpenSSL once the DLL is loaded it cannot actually be unloaded. I think we had considered the same thing for libcurl once. Once a DLL is loaded you may not be able to unload it, and if your program is still running then you cannot delete the DLL.

**Comment by CruiseYoung** [comment]
demo: [test_staitc_libcurl](https://github.com/CruiseYoung/test_staitc_libcurl.git)

**Comment by jay** [comment]
No evidence this is a curl problem.
