### ISSUE TITLE
CURLUPART_URL doesn't work as expected

### ISSUE THREAD

**Issue by sspiri** [curl/curl#5698]
### I did this

```c
int main(){
    CURLU* url = curl_url();
    curl_url_set(url, CURLUPART_URL, "google.com", CURLU_DEFAULT_SCHEME);
    curl_url_set(url, CURLUPART_URL, "instagram.com", CURLU_DEFAULT_SCHEME);

    char* s;
    curl_url_get(url, CURLUPART_URL, &s, 0);
    printf("%s\n", s);
    
    curl_free(s);
    curl_url_cleanup(url);
}
```

### I expected the following

I expected this prints `https://instagram.com/` but it prints `https://google.com/instagram.com`.

### curl/libcurl version
```code
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

`Linux somebody 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux`

**Comment by jay** [comment]
The [doc](https://curl.haxx.se/libcurl/c/curl_url_set.html) says: _If the handle already is populated with a URL, the new URL can be relative to the previous._

**Comment by bagder** [comment]
As @jay says: when there already us a URL set, the next URL will be handled as a redirect and then it can't use the default scheme by itself. We could probably clarify the documentation but I think this works as intended.

**Comment by bagder** [comment]
I got this idea:

If the URL handle already has contents set (so that setting CURLUPART_URL again will be treated as a redirect), then using CURLU_DEFAULT_SCHEME could be considered unsupported and cause an error to be returned.

Would that be better?

**Comment by sspiri** [comment]
@bagder i don't know if this deserves special error handling but I'm still missing a curl_url_strerror() function :)

**Comment by bagder** [comment]
Ok, let's leave things like this for now. I don't think I would object to a curl_url_strerror() function, but I don't think I'll work on one myself in the near future.
