### ISSUE TITLE
using --head ignores --silent flag

### ISSUE THREAD

**Issue by gelim** [curl/curl#5702]
### I did this

```
curl --silent --head http://www.google.com
```

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Date: Mon, 20 Jul 2020 08:45:36 GMT
Server: gws
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Transfer-Encoding: chunked
Expires: Mon, 20 Jul 2020 08:45:36 GMT
Cache-Control: private
Set-Cookie: 1P_JAR=2020-07-20-08; expires=Wed, 19-Aug-2020 08:45:36 GMT; path=/; domain=.google.com; Secure
Set-Cookie: NID=204=MhIa5UDTniGeZycVEhPmfBEVuPsmKlU-k86uCE6qAxn5UM8SbkhGGFVqkLDYwyX3_-CNXzF-PatkWBIuHLtfixqgMcva_wdBjeZxYSjr0dCMxo3JbrTnjTuKYlsX4UpBo6pNVTe6sWY5n0uQq9-kNvyGdfB4Vk6IevT7qHcxomU; expires=Tue, 19-Jan-2021 08:45:36 GMT; path=/; domain=.google.com; HttpOnly
```

### I expected the following

no terminal output, `--silent` is supposed to strip the HTTP headers on the server's answer.

### curl/libcurl version
```
curl 7.72.0-DEV (x86_64-pc-linux-gnu) libcurl/7.72.0-DEV OpenSSL/1.1.1 zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
### operating system

`Linux foobar 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by sterchelen** [comment]
Hi,
As the doc mentions 
```
 -s, --silent
    Silent or quiet mode. Don't show progress meter or error messages.
    Makes Curl mute. It will still output the data you ask for, potentially even to the terminal/stdout unless you redirect it.
```
**will still output the data you ask for** ... You asked for `head`, so it fetches the headers, again as the doc mentions it.

**Comment by gelim** [comment]
Well ok, I had different expectation for the "data you ask". Closing then

**Comment by dtantsur** [comment]
Sorry, but I think this bug should be reopened.

> You asked for head, so it fetches the headers

I asked for HEAD request, not for headers. If I want headers, I will use `-i`, no? And if I use `-s`, I explicitly ask for no output.

**Comment by bagder** [comment]
If you had argued this back in the late 1990s when it was made to work like this we could have had a fruitful discussion. Now, it is just how curl has worked for decades and we obviously cannot change that now.

**Comment by bagder** [comment]
If you want to do a HEAD without output, why not just redirect it to /dev/null or similar? There's no need for a new option.

    curl -I $URL -o /dev/null

**Comment by dtantsur** [comment]
Ahh, nice, I did not realize `-o` will work with the headers output. Thank you @bagder!

**Comment by bagder** [comment]
You can optionally use shell redirect:

    curl -I $URL > /dev/null
