### ISSUE TITLE
CURLOPT_FOLLOWLOCATION with CURLOPT_CURLU: infinitely following locations

### ISSUE THREAD

**Issue by sspiri** [curl/curl#5709]
### I did this

```c
#include <curl/curl.h>

int main(){
    CURLU* url = curl_url();
    curl_url_set(url, CURLUPART_URL, "https://google.com", 0);

    CURL* get = curl_easy_init();

    curl_easy_setopt(get, CURLOPT_CURLU, url);
    curl_easy_setopt(get, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(get, CURLOPT_VERBOSE, 1L);
    curl_easy_perform(get);

    curl_easy_cleanup(get);
    curl_url_cleanup(url);
}
```

### I expected the following

I expected this would follow to the desired location. Instead `curl_easy_perform()` is blocking forever, infinitely following the location. Just happens when I set the url with `CURLOPT_CURLU`, `CURLOPT_URL` is working as expected. Same error for multiple hosts.

### curl/libcurl version

```code
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

Linux 5.7.8-arch1-1

**Comment by jay** [comment]
I can reproduce this. It probably has something to do with [parseurlandfillconn](https://github.com/curl/curl/blob/curl-7_71_1/lib/url.c#L1832) which will set the url handle to the user setting (stored in data->set.uh), even on redirect.

https://github.com/curl/curl/blob/5a1fc8d33808d7b22f57bdf9403cda7ff07b0670/lib/url.c#L1840-L1848

data->state.uh where the redirect URL handle was stored is freed by up_free and then overwritten. That seems right though but I think something is missing like a data->change.uh to complement data->change.url so uh overwrites data->change.url?

**Comment by jay** [comment]
Try #5713
