### ISSUE TITLE
Most autobuilds failing because of TYPEDEFSTRUCT in stub_gssapi.h

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#5715]
### I did this

Look at https://curl.haxx.se/dev/builds.html

### I expected the following

Mostly green builds. All but one are red though because of a checksrc warning:

```
/tests/libtest/stub_gssapi.h:71:2: warning: typedef'ed struct (TYPEDEFSTRUCT)
typedef struct gss_buffer_desc_struct {
^
/tests/libtest/stub_gssapi.h:88:2: warning: typedef'ed struct (TYPEDEFSTRUCT)
typedef struct gss_OID_desc_struct {
^
/tests/libtest/stub_gssapi.h:93:2: warning: typedef'ed struct (TYPEDEFSTRUCT)
typedef struct gss_channel_bindings_struct {
^
```

Also, is it expected that checksrc warnings, in contrast to compiler warnings, prevent running the tests?

### curl/libcurl version

Everything still on the autobuilds page, which starts with 2020-07-10.

### operating system

Linux, Windows, Solaris

**Comment by bagder** [comment]
Odd. `tests/libtest/.checksrc` already contains `disable TYPEDEFSTRUCT` but it seems it doesn't work on some builds?

**Comment by bagder** [comment]
@MarcelRaad I can see your build at https://curl.haxx.se/dev/log.cgi?id=20200727044957-11233#prob5 reproduces this. Can you repro manually, perhaps on the same host? If so, can you figure out why the disabling of that warning doesn't work there?

**Comment by MarcelRaad** [comment]
I can reproduce it on any machine with testcurl.pl:
```
./tests/testcurl.pl --configure="--enable-debug --enable-static --disable-shared" --runtestopts="-a"
[...]
make[2]: Leaving directory '/build-12975/tests/unit'
make[2]: Entering directory '/build-12975/tests'
cd libtest && make checksrc
make[3]: Entering directory '/build-12975/tests/libtest'
  RUN      checksrc
/tests/libtest/stub_gssapi.h:71:2: warning: typedef'ed struct (TYPEDEFSTRUCT)
```

I haven't had the chance to look closer so far, but maybe it's something similar to https://github.com/curl/curl/pull/5288#issuecomment-619352038?

**Comment by bagder** [comment]
Thanks. I understand now...
