### ISSUE TITLE
CURLOPT_NOBODY became order-dependent in 7.71.0

### ISSUE THREAD

**Issue by sagebind** [curl/curl#5717]
### I did this

I am using libcurl (through Rust bindings) to send a HEAD request with a body, and upgrading from libcurl 7.70.0 to 7.71.1 broke my code. Here's essentially what I am doing to make this sort of request:

```c
curl_easy_setopt(curl, CURLOPT_UPLOAD, 1);
curl_easy_setopt(curl, CURLOPT_NOBODY, 1);
curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "HEAD");
// ...
```

I realize sending a body with a HEAD request is a pretty weird thing to want to do and is probably against spec, but I maintain a high-level HTTP client that wraps around libcurl that allows this behavior if the user really wants it. This was caught by one of my automated tests that began failing after an upgrade to 7.71.1.

If I re-order the option calls like this:

```c
curl_easy_setopt(curl, CURLOPT_NOBODY, 1);
curl_easy_setopt(curl, CURLOPT_UPLOAD, 1);
curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "HEAD");
// ...
```

Then it works like it did on 7.70.0. I don't know if this change was intentional or not but I didn't see it mentioned in the changelog nor in any GitHub or email conversations, so I assumed that this was a mistake. I also believe this commit was responsible for the change: https://github.com/curl/curl/commit/9c845be2797e2047547ec247cb037471aeb48bb0

### I expected the following

On 7.70.0 and earlier, curl performs the request like this (from verbose output):

```
*   Trying 127.0.0.1:37243...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 37243 (#0)
> HEAD / HTTP/1.1
Host: 127.0.0.1:37243
Accept: */*
Content-Length: 3362
Expect: 100-continue

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

This is what I would expect. Note the `Content-Length` is non-zero and curl intends to send the request body. On 7.71.0+, instead curl does this:

```
*   Trying 127.0.0.1:49251...
* Connected to 127.0.0.1 (127.0.0.1) port 49251 (#0)
> HEAD / HTTP/1.1
Host: 127.0.0.1:49251
Accept: */*
Content-Length: 0

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```

Note that the `Content-Length` changed to zero, and curl never attempts to send the request body at all. I believe this is because `CURLOPT_NOBODY` now implicitly changes the internal request type back to a HEAD and thus un-does the prior `CURLOPT_UPLOAD` call.

Here is a small C program that completely reproduces this problem: https://gist.github.com/sagebind/24f5824f44cd1f81e9a475951f888025

### curl/libcurl version

```sh
$ curl -V
curl 7.71.1-DEV (x86_64-pc-linux-gnu) libcurl/7.71.1-DEV OpenSSL/1.1.1f
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

(I checked out a Git tag to test the differences between versions.)

### operating system

```sh
$ uname -a
Linux Onyx 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
It certainly seems like a regression. The order of the options shouldn't have a meaning like this!

**Comment by bagder** [comment]
Looking at this closer, I'm not sure that the behavior you've relied on is documented or intended.

`CURLOPT_NOBODY` for HTTP transfers implies a `HEAD` request. `CURLOPT_UPLOAD` makes a `PUT` request (per documentation). When you set *both*, what do you actually mean? I don't think the documentation is clear as to which of the options that takes precedence but I think going with the last set option seems pretty reasonable.

Thus: if you first ask for PUT and then HEAD, then libcurl goes with HEAD.

As I understand you didn't consider it to work that way, I'm curious: what do you want from the `CURLOPT_NOBODY` option in your example code? To me, just using `CURLOPT_UPLOAD`  and `CURLOPT_CUSTOMREQUEST` seems to be enough ...

**Comment by sagebind** [comment]
I don't know if this is a correct usage of the option, but `CURLOPT_NOBODY` was being set in order to instruct libcurl to ignore the response body from the server and not wait for it, which seemed sort of how it was described in the docs. Basically "yes to request body" and "no to response body".

**Comment by bagder** [comment]
Then I should work on clarifying the docs.

There is no "ignore the body" option in curl. The `CURLOPT_NOBODY` means *don't ask for the body* - which in HTTP lingo means use a `HEAD` request which then according to the protocol doesn't get a body from the server.

In fact, if you set `CURLOPT_NOBODY` and then in fact do get a body anyway from the server, libcurl might get confused and misbehave on the subsequent request since a HEAD is said it **MUST NOT** have a body in the HTTP specs.

If you want to ignore receiving the HTTP body in a response, then you need to return an error from the write callback - and it will cause a transfer failure to be returned and with HTTP/1 it also means curl must forcibly close the connection and not re-use it in subsequent requests (while HTTP/2 and 3 can cut off a response early without sacrificing the connection). Optionally, you can read and discard the body in the callback, which then will allow curl to reuse the connection properly.

**Comment by sagebind** [comment]
That makes sense, thanks. This is an edge case where the user is behaving out-of-spec by trying to do anything with a body in either direction in the context of a `HEAD` request. I suppose from my end as a wrapper I just shouldn't set `CURLOPT_NOBODY` at all in this case and stick with `CURLOPT_UPLOAD` + `CURLOPT_CUSTOMREQUEST` for such weird requests.

**Comment by bagder** [comment]
@sagebind yes exactly! `CURLOPT_UPLOAD` or `CURLOPT_POSTFIELDS` + `CURLOPT_CUSTOMREQUEST` should be the way for an HEAD with a body.

BTW, I've also tried to extend the NOBODY documentation a little based on this discussion in #5729

**Comment by sagebind** [comment]
Those expanded docs look pretty good! 👍

I'll close this issue since it seems like things are working as intended.
