### ISSUE TITLE
Does `time_connect` work in curl 7.71.0 for HTTP/3?

### ISSUE THREAD

**Issue by chenyuezhou** [curl/curl#5719]
### I did this

~~~
$ src/curl --http3 https://www.cloudflare.com -so /dev/null -w '%{time_connect}'
0.210134d
~~~

### I expected the following

That it wouldn't work - as detailed in the [HTTP/3 wiki page](https://github.com/curl/curl/wiki/HTTP3).

in issue https://github.com/curl/curl/issues/4516 `time_connect` was always 0, but in my test it's not.

dose `time_connect` worked now？

### curl/libcurl version

![image](https://user-images.githubusercontent.com/45252179/88385589-32b0ba80-cde1-11ea-8e4b-6b49a0206b73.png)

### operating system

![image](https://user-images.githubusercontent.com/45252179/88385985-08133180-cde2-11ea-87e6-d0668305c104.png)

**Comment by bagder** [comment]
If it shows a non-zero value all the time and for both backends, then it works and we should remove it from that list of things that don't yet work for HTTP/3.

**Comment by bagder** [comment]
(please don't use images to submit text information, it makes it very hard to search and is inaccessible over email and more - I've now edited to show the first images as text instead)

**Comment by bagder** [comment]
`time_connect` does indeed work. Wiki page updated, case closed.
