### ISSUE TITLE
Disabling zstd results in empty state in configure output

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5720]
### I did this
`./configure  --without-zstd`

```
  curl version:     7.72.0-DEV
  SSL:              enabled (Windows-native, OpenSSL)
  SSH:              enabled (libSSH2)
  zlib:             no      (--with-zlib)
  brotli:           no      (--with-brotli)
  zstd:
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          enabled
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     no      (--enable-unix-sockets)
  IDN:              enabled (Windows-native)
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             enabled
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
...
```

### I expected the following
I expected a "no" behind "zstd:" instead of nothing.

### curl/libcurl version
current master

**Comment by mback2k** [comment]
@gvollant please take a look.

**Comment by gvollant** [comment]
pehaps anything like


`
gillesvollant@gv-w81x64:/mnt/n/devN$` diff  /mnt/n/forkcurl/configure.ac  /mnt/s/curl/configure.ac
149a150
>    curl_zstd_msg="no      (--with-zstd)"
`


*** /mnt/n/forkcurl/configure.ac        2020-07-12 18:16:50.798299000 +0200
--- /mnt/s/curl/configure.ac    2020-07-25 02:06:04.142077000 +0200
***************
*** 147,152 ****
--- 147,153 ----
      curl_ssh_msg="no      (--with-{libssh,libssh2})"
     curl_zlib_msg="no      (--with-zlib)"
   curl_brotli_msg="no      (--with-brotli)"
+    curl_zstd_msg="no      (--with-zstd)"
      curl_gss_msg="no      (--with-gssapi)"
  curl_tls_srp_msg="no      (--enable-tls-srp)"
      curl_res_msg="default (--enable-ares / --enable-threaded-resolver)"

**Comment by bagder** [comment]
@gvollant yes, seems accurate!
