### ISSUE TITLE
Setting and unsetting CURLOPT_NOBODY causes hang

### ISSUE THREAD

**Issue by causal-agent** [curl/curl#5725]
Since curl 7.71.0, setting and unsetting `CURLOPT_NOBODY` causes the request following unsetting it to hang. This behaviour was introduced in 9c845be2797e2047547ec247cb037471aeb48bb0, which sets the request method to HEAD when `CURLOPT_NOBODY` is set, but does not change it away from HEAD when it is unset. Notably, this comment and the behaviour it describes was removed https://github.com/curl/curl/commit/9c845be2797e2047547ec247cb037471aeb48bb0#diff-8fb104c402dc51bdffef05a372f32aa2L4000
```c
     /* ... but if unset there really is no perfect method that is the
        "opposite" of HEAD but in reality most people probably think GET
        then. The important thing is that we can't let it remain HEAD if the
        opt_no_body is set FALSE since then we'll behave wrong when getting
        HTTP. */
```

### I did this

```c
#include <curl/curl.h>
int main(void) {
	CURL *curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(curl, CURLOPT_URL, "https://gentoo.org");
	curl_easy_setopt(curl, CURLOPT_NOBODY, 1L);
	curl_easy_perform(curl);
	curl_easy_setopt(curl, CURLOPT_NOBODY, 0L);
	curl_easy_perform(curl);
}
```

### I expected the following

A HEAD request followed by a GET request (behaviour prior to 7.71.0). Instead, the second request is still a HEAD request, but curl waits to receive a body, causing a hang.

### curl/libcurl version

```
curl 7.71.0 (amd64-portbld-freebsd12.1) libcurl/7.71.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2020-06-24
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

```
FreeBSD [snip] 12.1-RELEASE-p7 FreeBSD 12.1-RELEASE-p7 GENERIC  amd64
```

**Comment by bagder** [comment]
This does indeed change the behavior, but let me also point out that setting `CURLOPT_NOBODY` to 0L is not how to reset a handle back to doing a GET (precisely because the "opposite" of HEAD is not necessarily GET) and it is not documented to do that. We added `CURLOPT_HTTPGET` for exactly that purpose

**Comment by causal-agent** [comment]
Yeah that's the workaround I found, although it wasn't obvious. Perhaps that should be called out more clearly in the documentation for `CURLOPT_NOBODY`.

**Comment by bagder** [comment]
@causal-agent do #5728 and #5729 improve things for you?

**Comment by causal-agent** [comment]
Looks good, thanks!
