### ISSUE TITLE
Libcurl sftp download half as fast as curl binary

### ISSUE THREAD

**Issue by Togtja** [curl/curl#5739]
### I did this

I am using libcurl to download files using SFTP, it takes my program using libcurl about twice as much times as it does using the curl executable. I simplified my code as much as possible, and it still is slower. I could not find any known bugs related to this.
I used [this](https://curl.haxx.se/libcurl/c/ftpget.html) when writing the code,
```cpp
size_t my_fwrite(char* buffer, size_t size, size_t nmemb, File* file)
{
    return size * nmemb; //Just return the size to prove that it's not the write
}

curl_global_init(CURL_GLOBAL_DEFAULT);
CURL* curl = curl_easy_init();

/** Setup URL/PORT/USERNAME/PASSWORD */

curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, my_fwrite);

CURLcode res = curl_easy_perform(curl);
if (CURLE_OK != res) {
    // we failed
    std::cout << "we failed due to '" << curl_easy_strerror(res) << "'\n";
}
curl_easy_cleanup(curl);
curl_global_cleanup();
```
I also tried with an actual callback function and `curl_easy_setopt(curl, CURLOPT_WRITEDATA, &ftpfile);`
When uploading files the executable and libcurl take about the same amount of time
### I expected the following
I expect the cURL executable and libcurl to run at about the same speed, so don't know what I might be doing wrong. Or if it is a bug of cURL
### curl/libcurl version
Windows 10 Enterprise, compiled with CMake on Visual Studio Build Tools 2019 (v 16.6.4):
```
curl 7.71.1 (Windows) libcurl/7.71.1 OpenSSL/1.1.1g libssh2/1.9.0_DEV
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM SSL
```
Ubuntu 20.04 (WSL), compiled with CMake on GCC 10.0.1:
```
curl 7.71.1 (Linux) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0_DEV
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets
```
uname -a
`Linux Tomas-Work-PC 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`
EDIT:
Made a StackOverflow [post](https://stackoverflow.com/questions/62829210/libcurl-half-as-fast-as-curl) a while ago about this, with some more info

**Comment by bagder** [comment]
If you run your tool command line with `--libcurl code.c` you can see what options the tool sets and compare with your application. My guess: curl sets a larger download buffer and your application doesn't. I don't think this is a bug...

**Comment by Togtja** [comment]
How come the curl binary that I compile, get a different download buffer than the libcurl I use from the same CMake script?

**Comment by jzakrzewski** [comment]
curl tool and libcurl are two distinct things. When curl performs a task, it passes some options to the libcurl to do the heavy lifting. Those options may differ from libcurl defaults. Mostly because the library must be more generic and more conservative than the tool.

**Comment by bagder** [comment]
> How come the curl binary that I compile, get a different download buffer

[CURLOPT_BUFFERSIZE](https://curl.haxx.se/libcurl/c/CURLOPT_BUFFERSIZE.html)

**Comment by gvanem** [comment]
And BTW, while struggling just now with curl + sftp to work, I found this:
https://github.com/libssh2/libssh2/issues/463  still an open issue :-(

curl gives `Failure establishing ssh session: -44, Unable to ask for ssh-userauth service` and a
`set CURL_SSL_BACKEND=schannel` does nothing. Would be nice to have `sftp` use `Schannel`.

**Comment by Togtja** [comment]
I see, then I have misunderstood a bit. I thought the buffer size was set at compile time. Setting the CURLOPT_BUFFERSIZE to the same that curl binary used made the speed match.
Thank you for the quick response and solution to my issue! And sorry for this issue
