### ISSUE TITLE
Windows curl and Russian letter "Р"

### ISSUE THREAD

**Issue by sdamo** [curl/curl#5740]
If url have russian letter **Р**, then receive 400 bad request

Russian letter **Р** - URL-code **%D0%A0**

![screenshot_2020-07-28_16-44-24](https://user-images.githubusercontent.com/5411099/88674098-115a1200-d0f2-11ea-8263-84f977500178.png)

**Comment by bagder** [comment]
How is this a (curl) problem? You pass in a URL that creates a request the server doesn't like.

**Comment by bagder** [comment]
if you add `--trace-ascii -' to the command line you can see the exact bytes curl sent, and you'll probably see that the input was not a valid URL byte sequence and when curl converted those two percent-encoded the lack of UTF-8 encoding in the windows command line prompt made them into something different that the server didn't expect.

curl doesn't support "Russian letter P" in the URL. It wants RFC 3986 URLs.
