### ISSUE TITLE
Curl 7.71.1 HTTP3 - the installed libcurl version doesn't support this

### ISSUE THREAD

**Issue by rusikf** [curl/curl#5746]
Hi curl hackers!
I did this( Before I installed it from source like described [here](https://geekflare.com/curl-installation/)
```
$ LD_LIBRARY_PATH=/usr/local/lib curl --http3 https://google.com
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information
```

### I expected the following
No errors, it must work with libcurl - it is 7.71.1 version

### curl/libcurl version
```
$ LD_LIBRARY_PATH=/usr/local/lib curl -V
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.39.2 librtmp/2.3

```
### operating system
`Linux rusikf-Inspiron-5547 5.3.0-62-generic #56-Ubuntu SMP Tue Jun 23 11:20:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by bagder** [comment]
You need to build it HTTP/3 enabled, which it doesn't by default. See [HTTP3.md](https://github.com/curl/curl/blob/master/docs/HTTP3.md).
