### ISSUE TITLE
Curl working with cacert on OSX and Windows but not Linux

### ISSUE THREAD

**Issue by lebanggit** [curl/curl#5751]
I to want request SECURI to somes website.

At here : https://curl.haxx.se/docs/sslcerts.html
I have get **cert.pem** with this command:
`echo quit | openssl s_client -showcerts -servername "www.google.com" -connect "www.google.com":443 > google.pem`

And run curl command:
`curl --cacert google.pem --location --silent 'https://www.google.com' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -v`

It work on OSX, Windows but not Linux (Ubuntu, Centos). It say:

`*   Trying 2607:f8b0:4006:803::2004:443...`
`* Connected to www.google.com (2607:f8b0:4006:803::2004) port 443 (#0)`
`* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH`
`* successfully set certificate verify locations:`
`*   CAfile: google.pem`
 ` CApath: none`
`* TLSv1.2 (OUT), TLS handshake, Client hello (1):`
`* TLSv1.2 (IN), TLS handshake, Server hello (2):`
`* NPN, negotiated HTTP1.1`
`* TLSv1.2 (IN), TLS handshake, Certificate (11):`
`* TLSv1.2 (OUT), TLS alert, unknown CA (560):`
`* SSL certificate problem: unable to get issuer certificate`
`* Closing connection 0`

Anyone can tell me why?

Thanks.

**Comment by bagder** [comment]
> `SSL certificate problem: unable to get issuer certificate`

That error message is typically the result of a missing intermediate cert in the CA bundle.

But other than that, I presume your diff platforms also run curl built to use different TLS backends?

**Comment by lebanggit** [comment]
I have try with --capth:

`curl --cacert google.pem -capth /etc/ssl/certs`

But still same error. Can i do to fix this error?

**Comment by bagder** [comment]
I think your PEM file is incomplete there. Try this instead: https://curl.haxx.se/docs/caextract.html - does it make the command line work?

**Comment by lebanggit** [comment]
@bagder: Yes..... google.com is example... and working fine.

But Some sites use Cloudflare not woking:

ex: pixabay.com

It show  403 Forbidden.

But on macos and windows it's fine.

**Comment by bagder** [comment]
If you get a 403 the TLS handshake worked fine so then there's no issue with the cacert bundle at all... The 403 is the server saying your request wasn't allowed. It is rarely a curl problem but more of a problem on how you should access the server.

**Comment by lebanggit** [comment]
problem is: same command curl.... but working on OSX and Windows and not on Linux....

so i'm guest CA is an issue.

**Comment by bagder** [comment]
No, the CA is not the issue of the TLS handshake completes successfully, and getting a 403 means that it did.

Again: this is not a curl issue. This is the server deciding that the client is not allowed to get this resource. I don't know why it makes curl act different on different platforms, but that is still the server making that decision - **not curl**.

**Comment by lebanggit** [comment]
Thanks
