### ISSUE TITLE
cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"

### ISSUE THREAD

**Issue by mahey1984** [curl/curl#5753]
I have an issue I am experiencing and was hoping you could help?

I get the following error message

error:
"2020-07-29 16:54:44 : cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"

This error is when I try to export jobs in Magento 2.3.5 I have also tried this in terminal

1) what kind of file are you trying to export?

We are trying to export an xlsx file

2) Are you using any Magento plugin to create an export job?

firebear import-export plugin using for the export job

this is error:
"2020-07-29 16:54:44 : cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
![image (9)](https://user-images.githubusercontent.com/69021907/89067431-27243d00-d367-11ea-9c97-3a36a321ba36.png)

libcurl - Error Codes
libcurl error codes . NAME. libcurl-errors - error codes in libcurl DESCRIPTION. This man page includes most, if not all, available error codes in libcurl.
curl.haxx.se

**Comment by bagder** [comment]
We need to understand what's going on in the libcurl-using app with lots of details and logs or preferably, get a full example source code that reproduces the problem. You did not even mention what libcurl version and which platform it runs.

The error string you quote seems to match `CURLM_ADDED_ALREADY`, but that is not number 2 in libcurl.

**Comment by bagder** [comment]
No response
