### ISSUE TITLE
Crash in Curl_closesocket on window

### ISSUE THREAD

**Issue by cwlmyjm** [curl/curl#5756]
### I did this
I am developing an im program and use curl_multi in the project, but sometimes program crash on Curl_closesocket in timer_cb callback, crash in WSPCloseSocket when call sclose in Curl_closesocket.
When I read the logs we record in program, the crash mostly happen on timeout connect. 
The first question is that, is it safe to use multi curl_multi in program and each curl_multi work on its own thread?
I am going to develop a demo to reproduce it.

### I expected the following
Fix the crash

### curl/libcurl version
7.65.3

[curl -V output]
libcurl/7.55.1 WinSSL
发布日期(未发表):
协议:dict文件ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
特点:AsynchDNS IPv6大文件SSPI Kerberos SPNEGO NTLM SSL

### operating system
Window 10-1809-17763.615

### crash stack
Thread 22 (crashed)
  0  wmswsock.pdb + 0xaa23
      eax = 0x00000000      ebp = 0x0cddf634
      ebx = 0x00000000      ecx = 0xffffffff
      edi = 0x00000ee4      edx = 0x00000001
     eflags = 0x00010286      eip = 0x71e7aa23
      esi = 0xffffffff      esp = 0x0cddf620
     Found by: given as instruction pointer in context
  1  ws2_32.pdb + 0xd450
      ebp = 0x0cddf668      eip = 0x76a8d451
      esp = 0x0cddf63c
     Found by: previous frame's frame pointer
  2  libcurl.pdb!Curl_closesocket [connect.c : 1354 + 0x6]
      ebp = 0x0cddf67c      eip = 0x6fcc26af
      esp = 0x0cddf670
     Found by: call frame info
  3  libcurl.pdb!conn_shutdown [url.c : 696 + 0x6]
      ebp = 0x0cddf690      eip = 0x6fcfaf73
      esp = 0x0cddf684
     Found by: call frame info
  4  libcurl.pdb!Curl_disconnect [url.c : 820 + 0x5]
      ebp = 0x0cddf6a8      eip = 0x6fcf9a6f
      esp = 0x0cddf698
     Found by: call frame info
  5  libcurl.pdb!multi_done [multi.c : 621 + 0x9]
      ebp = 0x0cddf7d0      eip = 0x6fce27f9
      esp = 0x0cddf6b0
     Found by: call frame info
  6  libcurl.pdb!multi_runsingle [multi.c : 1343 + 0xd]
      ebp = 0x0cddf838      eip = 0x6fce2b43
      esp = 0x0cddf7d8
     Found by: call frame info
  7  libcurl.pdb!multi_socket [multi.c : 2555 + 0xe]
      ebp = 0x0cddf88c      eip = 0x6fce3893
      esp = 0x0cddf840
     Found by: call frame info
  8  libcurl.pdb!curl_multi_socket_action [multi.c : 2668 + 0x10]
      ebp = 0x0cddf8b0      eip = 0x6fce227a
      esp = 0x0cddf894
     Found by: call frame info
  9  MyPopo.pdb!net::CurlNetworkSessionManager::PerformTimeoutAction [curl_network_session_manager_uv.cpp : 528 + 0x10]
     Found by: inlined into next frame
 10  MyPopo.pdb!net::CurlNetworkSessionManager::OnTimeout [curl_network_session_manager_uv.cpp : 523 + 0x10]
      ebp = 0x0cddf8e0      eip = 0x00db5954
      esp = 0x0cddf8b8
     Found by: call frame info

**Comment by bagder** [comment]
> The first question is that, is it safe to use multi curl_multi in program and each curl_multi work on its own thread?

As long as you don't use the same handle(s) in more than one thread simultaneously, yes.

> I am going to develop a demo to reproduce it.

Please do, just a crash dump is not enough to understand what's going on. Also, consider trying the same thing with the latest libcurl version to make sure the issue isn't already fixed...

**Comment by bagder** [comment]
Feel free to reopen this issue and provide the additional data when you get it.
