### ISSUE TITLE
"Test requires default test server host and port" for any test run

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#5761]
### I did this

Look at any CI build. Alternatively, run the tests with runtests.pl.

### I expected the following

Not to see this line in every single test suite run:
```
TESTINFO: "Test requires default test server host and port" 12 times (842, 843, 844, 845, 887, 888, 889, 890, 946 and 3 more)
```

Could it be that these tests cannot be run at all anymore since https://github.com/curl/curl/commit/80d651541537433e1363f7b4ba7497b08d0fb53f?

Also, there are a lot of warnings
```
Use of uninitialized value $HTTPSPORT in substitution (s///) at /tests/runtests.pl line 3271."
```
as visible e.g. in https://curl.haxx.se/dev/log.cgi?id=20200801191819-7235#prob12, which seems to be caused by the same commit.

### curl/libcurl version

7.72.0-DEV

### operating system

Linux, macOS, Windows, FreeBSD, Solaris

**Comment by bagder** [comment]
Correct, tests that require "default host and port" can no longer run (unless by a fluke the random port happens to land on the single port the test can run on). They need to be adjusted to work on "any" port number.

**Comment by jay** [comment]
~~~
=== Start of file http_server.log
21:03:54.633676 exit_signal_handler: 15
21:03:54.638788 signalled to die
21:03:54.639411 ========> IPv4 sws (port 55745 pid: 13877) exits with signal (15)
=== End of file http_server.log
=== Start of file https_stunnel.log
[ ] Clients allowed=125
[.] stunnel 5.50 on sparc-sun-solaris2.10 platform
[.] Compiled with OpenSSL 1.0.2o 27 Mar 2018
[.] Running with OpenSSL 1.0.2u 20 Dec 2019
[.] Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
[ ] errno: (*(___errno()))
[!] Invalid configuration file name "/build-17545/tests/https_stunnel.conf"
[!] realpath: Invalid argument (22)
[ ] Deallocating section defaults
=== End of file https_stunnel.log
~~~

**Comment by bagder** [comment]
@jay surely that's a separate problem?
