### ISSUE TITLE
fail to use ssl on windows when make a request whose cert is  self-signed 

### ISSUE THREAD

**Issue by hotbroker** [curl/curl#5766]
### I did this
				curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 1);
				curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1);
				//curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, *sslctx_function);
				curl_easy_setopt(curl, CURLOPT_CAINFO, __cert_path.data());
and url's cert is self-signed

### I expected the following
good to make a https request

### curl/libcurl version
7.68

[curl -V output]
schannel: CertGetCertificateChain trust error CERT_TRUST_REVOCATION_STATUS_UNKNOWN
![image](https://user-images.githubusercontent.com/50006539/89126082-8d4ec280-d515-11ea-83ec-81dc25b5134a.png)

### operating system
windows 10

there is a good way to fix this is providing a callback with its CA info passed when CERT_TRUST_REVOCATION_STATUS_UNKNOWN occurs

**Comment by bagder** [comment]
If the certificate can't be verified (when you asked for it), shouldn't curl return an error then? What's the problem with that?

**Comment by hotbroker** [comment]
> If the certificate can't be verified (when you asked for it), shouldn't curl return an error then? What's the problem with that?

curl_easy_perform() return:
 **failed: SSL peer certificate or SSH remote key was not OK**

**Comment by bagder** [comment]
The server could not be verified. That's a feature.

**Comment by hotbroker** [comment]
> The server could not be verified. That's a feature.

wait.i think this error occurs in many cases,one of theses is when this is a self-sigend cert .becase the Windows API(CertGetCertificateChain) would try to check CRL for this CA (my best guess), 

so,what can i do to avoid this error? (like setting any parmeter to ignore this CERT_TRUST_REVOCATION_STATUS_UNKNOWN, or giving me a chance to handle this error)

**Comment by bagder** [comment]
I don't understand what you're saying, but maybe [CURLSSLOPT_REVOKE_BEST_EFFORT](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) (added in 7.70.0) is for you?

**Comment by hotbroker** [comment]
> I don't understand what you're saying, but maybe [CURLSSLOPT_REVOKE_BEST_EFFORT](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) (added in 7.70.0) is for you?

great,this is what im looking for. thanks a lot, I will try this latter,
ps:It would be better if there is a way to make this opt works only for a specefic cert :)
`
  case CURLOPT_SSL_OPTIONS:
    arg = va_arg(param, long);
    data->set.ssl.enable_beast =
      (bool)((arg&CURLSSLOPT_ALLOW_BEAST) ? TRUE : FALSE);
    data->set.ssl.no_revoke = !!(arg & **CURLSSLOPT_NO_REVOKE**);
    break;
`

**Comment by bagder** [comment]
ps, if you want to help improve curl we accept pull-requests! :grinning:

**Comment by hotbroker** [comment]
> ps, if you want to help improve curl we accept pull-requests! 😀

thanks,Im glad to hear ,but I may not qulified  :)
