### ISSUE TITLE
Provide a way to set the modification date on an uploaded file (SFTP or FTP)

### ISSUE THREAD

**Issue by hummeleBop** [curl/curl#5768]
Right now, curl is not able to set the timestamp on a uploaded file.

This feature could be really useful in order to preserve the file timestamp (or set a new one) when Uploading a file.

**Comment by emilengler** [comment]
I strongly agree on that feature!
Some servers use that date as something like a publication date (e.g. forbid access to it until the timestamp was passed).

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by sebbu2** [comment]
well, it could be seen as a bug, -R, --remote-time should work both way, when downloading AND when uploading

**Comment by bagder** [comment]
except that `--remote-time` is documented to **Set the remote file's time on the local output**

**Comment by bagder** [comment]
For FTP I can't seem to find any standard command for changing the "modification time" of a file. There's a proposed `MFMT` command in an [old expired internet-draft](https://www.ietf.org/archive/id/draft-somers-ftp-mfxx-04.txt), but I have no idea how commonly supported those commands are.

For SFTP it is more straight forward as that's more of an API for a file system over SSH so the SSH libraries we use offer this functionality.

**Comment by hummeleBop** [comment]
For FTP, there are several commands : «SITE UTIME», «MFMT» (https://tools.ietf.org/html/draft-somers-ftp-mfxx-04#section-5.1) ; (https://tools.ietf.org/html/draft-somers-ftp-mfxx-04#section-5.7) ; (https://en.wikipedia.org/wiki/List_of_FTP_commands).
«SITE UTIME» is commonly used, but I don't find any reliable documentation about this.
The syntax of «SITE UTIME» follows : «SITE UTIME /remote/file/path yyyyMMddHHmmss yyyyMMddHHmmss yyyyMMddHHmmss UTC» (creation date, modification date, last access date).

Some SFTP don't allow the use of shell commands, SSH_FXP_SETSTAT  / SSH_FXP_FSETSTAT are probably the most relevant way to set the date.

The most straightforward way to bring the feature to curl could be by adding more commands in the **--quote** parameter.

**Comment by bagder** [comment]
`SITE UTIME` doesn't even have an outdated internet-draft so it's even less of a standard thing, but it seems to exist as a module for proftpd: http://www.proftpd.org/docs/contrib/mod_site_misc.html#SITE_UTIME
