### ISSUE TITLE
Curl Hangs on Particular Website on Ubuntu 16.04 but not 18.04 Even with Updated Version

### ISSUE THREAD

**Issue by freepi** [curl/curl#5780]
### I did this
`curl 'https://www.nasdaq.com/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -v`

but output hangs on "old SSL session...":

> *   Trying 104.81.179.248:443...
> * Connected to www.nasdaq.com (104.81.179.248) port 443 (#0)
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /home/ubuntu/anaconda2/ssl/cacert.pem
>   CApath: none
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *  subject: C=US; ST=Connecticut; L=Shelton; O=NASDAQ, INC.; CN=www.nasdaq.com
> *  start date: Jun 15 00:00:00 2020 GMT
> *  expire date: Oct 20 12:00:00 2020 GMT
> *  subjectAltName: host "www.nasdaq.com" matched cert's "www.nasdaq.com"
> *  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
> *  SSL certificate verify ok.
> > GET / HTTP/1.1
> > Host: www.nasdaq.com
> > Accept-Encoding: deflate, gzip
> > User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
> > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> > Accept-Language: en-US,en;q=0.5
> > DNT: 1
> > Connection: keep-alive
> > Upgrade-Insecure-Requests: 1
> > 
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * old SSL session ID is stale, removing
> 

### I expected the following
curl to download the webpage's html.  Curling other URLs works fine.

### curl/libcurl version & operating system

I have played around with the command on a number of different systems, sometimes it succeeds, sometimes it fails.  In general seems to succeed on Ubuntu 18.04 systems but not older Ubuntu versions even when curl has been updated to the most recent version (7.71.1).

**Ubuntu 14.04 (FAILS)**
uname -a:
Linux ip-aaa-aaa-aaa-aaa 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0

curl -V:
curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

**Stock AWS Ubuntu Server 16.04 Image (FAILS)**
uname -a:
Linux ip-aaa-aaa-aaa-aaa 4.4.0-1109-aws #120-Ubuntu SMP Fri Jun 5 01:26:57 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

curl -V:
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016

**Ubuntu 18.04 (SUCCEEDS)**
uname -a:
Linux username 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

curl -V:
curl 7.63.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.8.0
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

**Comment by bagder** [comment]
It seems as if `Newsession Ticket` might be a clue to the problem, but when I try the same command line I don't seem to get a new ticket and the problem doesn't reproduce for me...

**Comment by freepi** [comment]
Anything I can do to help diagnose the problem?  

One guaranteed way to recreate it is to just spin up a stock Ubuntu 16.04 AMI instance on AWS (even the free tier would do) and then try the command.  If you don't have access or want the hassle, I could spin one up for a bit and give you the login info and trust that you behave, hah.

**Comment by bagder** [comment]
I could try that. Bring me details to `daniel@haxx.se` or `@bagder` on twitter and we can take it from there.

**Comment by freepi** [comment]
Great. E-mailed you the credentials.

**Comment by bagder** [comment]
Sorry, I have not had a lot of time for this but I have not yet found anything couldn't just as well be the server acting this way.

It seems like the troubled clients are from the same IP? Can you make one work and one fail from the same host?

**Comment by freepi** [comment]
I think I follow what you're saying.  I don't think it's related to the IP address or the particular server because I've started multiple AWS instances, some based on AWS's Ubuntu 16.04 image, others on AWS's Ubuntu 18.04 image, and the 16.04 instances always had the problem while the 18.04 instances never did.

Unfortunately, I cannot control what IP address AWS assigns to an instance, but if it would help I can start an Ubuntu 18.04 instance that does not have the problem and give you access, but it'd have a different IP address.  A release upgrade on the 16.04 instance to 18.04 would keep the IP the same and could very well could solve the problem, but it seems like that might hide whatever the actual problem is.

**Comment by 62f** [comment]
* #Load the copy of that same data from my repo with the command
curl ‘https://raw.githubusercontent.com/62f/curl/master/nasdaq' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -v

**Comment by jay** [comment]
> * Load the copy of that same data from my repo with the command

I tried in Ubuntu 16 LTS using the packaged version of curl (what I assume you are using) but I can't reproduce with either your saved data or nasdaq.com

~~~
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
~~~

**Comment by freepi** [comment]
62f: Interesting idea. Requesting from your github worked fine for the AWS instance, but I just retried the request from nasdaq.com again as detailed above and it is still not working. 

jay: How strange, all of our version info seems to match and yet the command does not work on any 16.04 AWS instance I spin up.  I'd think nasdaq.com was just blocking AWS IP addresses for some reason, but if I spin up an 18.04 AWS instance, there's no problem.

**Comment by jay** [comment]
Set [SSLKEYLOGFILE](https://ec.haxx.se/usingcurl/usingcurl-tls/tls-sslkeylogfile), start packet capture w/ capture filter `host www.nasdaq.com` and then reproduce using a build of curl with OpenSSL.

**Comment by 62f** [comment]
Not the one having this issue, but how can curl even hang when it behaves so impatiently in times of unresponsiveness?: https://github.com/JuliaLang/julia/issues/37475#issue-696104021

**Comment by jay** [comment]
> how can curl even hang when it behaves so impatiently in times of unresponsiveness?: [JuliaLang/julia#37475 (comment)](https://github.com/JuliaLang/julia/issues/37475#issue-696104021)

That's unrelated. It looks like the transfer went below a minimum speed limit that was set, and probably some other timeouts were set as well.

**Comment by freepi** [comment]
> Set [SSLKEYLOGFILE](https://ec.haxx.se/usingcurl/usingcurl-tls/tls-sslkeylogfile), start packet capture w/ capture filter `host www.nasdaq.com` and then reproduce using a build of curl with OpenSSL.

I tried to do this, but as far as I can tell the file specified by SSLKEYLOGFILE was never generated perhaps because curl only outputs the file after a certain point in the request connection sequence that is never reached?  Repeating the same steps on my Ubuntu 18.04 machine for which the curl request works generated the file as expected.  Seemed like a good idea tho, thanks.

**Comment by freepi** [comment]
Perhaps there's another way to get at the encrypted curl traffic with wireshark?  Could [this](https://github.com/curl/curl/pull/2220) or another similar option be helpful?  I only have a very rudimentary understanding of SSL encryption, so it's hard for me to tell. One caveat is that the server is headless so it'd be much easier for me if I could transfer the pcap file and decryption key to another non-headless server for decryption and viewing, similar to [jinjiu's comment](https://github.com/curl/curl/pull/2220#issuecomment-356023885).  I just updated curl to 7.71.1 using conda and it still has the same problem as before, but hopefully that gives me other options for getting at the encrypted network traffic from curl.

**Comment by jay** [comment]
SSLKEYLOGFILE was enabled by default starting in 7.58.0 and only works for OpenSSL. If you're building a older version of curl w/ openssl then you'd have to check if it's supported and enable it manually by CPPFLAGS=-DENABLE_SSLKEYLOGFILE ../configure ...

**Comment by jay** [comment]
Another thing that occurs to me is on Windows we skip buffering so that the passwords are available immediately because it did not do well with line buffering. You could try that as well, see https://github.com/curl/curl/blob/curl-7_72_0/lib/vtls/keylog.c#L55-L59

**Comment by freepi** [comment]
I see.  Once I updated curl I was able to get everything working with Wireshark just fine. I've uploaded the pcap and tlskey files [here](https://github.com/freepi/curl).  I don't know how to interpret the results, but hopefully someone here does.

**Comment by jay** [comment]
What is the curl version `curl -V` of that capture? It shows the server sends the session ticket but then stops replying. One interesting thing I notice is only alpn protocol is http/1.1. If I use --http1.1 or disable alpn then I can reproduce. This seems like a server issue where it can't handle http/1.1, but I can't explain why it succeeds for you on Ubuntu 18. Would you mind taking a packet capture and keylog of a successful session?

**Comment by freepi** [comment]
@jay I've done as you suggested.  The 18.04 and 16.04 pcap and keylog files can be found again [here](https://github.com/freepi/curl).  It does seem like the problem is http 1.1 vs 2.0.  Using --http2 option on curl didn't fix the problem however as http 1.1 is used despite that. Any idea what this ALPN thing is and how I could force it to use http 2.0?

curl -V on the 16.04 instance:
curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

curl -V on the 18.04 instance:
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by jay** [comment]
ALPN is a TLS extension that is predominantly used to indicate to the server that the client supports HTTP/2. If HTTP/2 isn't built in then only HTTP/1.1 is sent in the ALPN protocol list. You cannot use HTTP/2 unless it is [built in](https://curl.haxx.se/docs/http2.html), as you can see in the features list as HTTP2.

Your original report says a successful transfer took place using a version of curl that does not support HTTP/2. However your most recent version information shows a different curl version for Ubuntu 18 that has HTTP2 support.

If I play with the headers I can make an HTTP/1.1 request work:
~~~
curl -v --http1.1 -H User-Agent: -H Accept: -H "Connection: keep-alive" -H "Accept-Encoding: gzip, deflate, br" https://www.nasdaq.com
~~~

I have seen this behavior from some caching servers. If a specific header combination is not cached then the request has to be passed to the origin server. If the origin server is unreachable a timeout occurs. So I think that's what's happening here.

**Comment by freepi** [comment]
I see, thanks for the info.  

Good catch regarding the different 18.04 curl -v's. The first 18.04 -v info I report is from my local machine.  The second 18.04 -v info is from an AWS instance in the same region as the 16.04 instance with the problem for consistency.  Checking again on my local 18.04 machine, you're right, it uses ALPN offering http/1.1 but for some reason works correctly.

The modified curl request you give above does not work on the 16.04 instance.

Does this new information change your conclusion or does it still seem like an ALPN and misconfigured server issue?

**Comment by jay** [comment]
It's a server issue. I contacted Nasdaq. Their contact us form was failing at the time as well, no doubt because it's a POST and has to be passed to the origin server. I haven't heard back.

**Comment by freepi** [comment]
I see, thanks for all the help and for reporting to Nasdaq!

**Comment by ilatypov** [comment]
It could be that an outgoing firewall on the client side or an incoming firewall on the server side interprets TLS in different ways.

Attempting the same download with curl 7.84.0 / OpenSSL 3.0.4 (Debian sid) hangs from one IP network but not from another.

https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/7.14.0/synopsys-detect-7.14.0.jar

```
{ echo -ne "GET /artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/7.14.0/synopsys-detect-7.14.0.jar HTTP/1.1\r\nHost: sig-repo.synopsys.com\r\n\r\n"; sleep 2; } | openssl s_client -connect sig-repo.synopsys.com:443 -servername sig-repo.synopsys.com 2>&1 | head -500 > synopsys-from-openssl-3.0.4-ONE-NETWORK.txt

diff -u synopsys-from-openssl-3.0.4-{ONE,ANOTHER}-NETWORK.txt
```

```
@@ -80,421 +80,73 @@
 Early data was not sent
 Verify return code: 0 (ok)
 ---
-HTTP/1.1 200
-Date: Thu, 14 Jul 2022 03:43:42 GMT
-Content-Type: application/java-archive
-Content-Length: 33148012
-Connection: keep-alive
-X-JFrog-Version: Artifactory/7.31.13 73113900
-X-Artifactory-Id: 008161788361eb9aa27f0224e9f393244c8d6905
-X-Artifactory-Node-Id: artifactory-0
-Last-Modified: Thu, 23 Jun 2022 18:54:47 GMT
-ETag: dc7fa7f686ccaf1614ca02b512f9ec4d6579441a
-X-Checksum-Sha1: dc7fa7f686ccaf1614ca02b512f9ec4d6579441a
-X-Checksum-Sha256: 1f3c580dbacc9bf55854e3af21c4dfc6ca40ec446f225c355581f70201619ded
-X-Checksum-Md5: 5d99a014a6ff707db42be67103e08d41
-Accept-Ranges: bytes
-X-Artifactory-Filename: synopsys-detect-7.14.0.jar
-Content-Disposition: attachment; filename="synopsys-detect-7.14.0.jar"; filename*=UTF-8''synopsys-detect-7.14.0.jar
-Strict-Transport-Security: always
-Set-Cookie: visid_incap_2638074=XefkkTl9RyCV3zHEUVVy+e2Qz2IAAAAAQUIPAAAAAAB80c80idUu1EDZ9g/+vunP; expires=Thu, 13 Jul >
-Set-Cookie: incap_ses_1445_2638074=SApufdMj6G+RYejrJKwNFO2Qz2IAAAAAF4+W5z0kh139msvWhNdZzA==; path=/; Domain=.synopsys.>
-X-CDN: Imperva
-X-Iinfo: 14-30600870-30600874 NNNN CT(38 37 0) RT(1657770221497 13) q(0 0 0 3) r(1 1) U5
-
-PK^C^D^T^@^H^H^H^@<B9>v<D7>T^@^@^@^@^@^@^@^@^@^@^@^@^T^@^@^@META-INF/MANIFEST.MFĽY<93><A2>l<B3>6z<FE>E<AC><FF><B0>^N<D>
[...]
<F5><C0><A3><D9>-<BA><F2><87><8F>&u<82><BD><E2><A8>ui<D1>"/<92>v<E2>Sn^]<A0>'R^O7ܱ<D2>e\^PB<C9>R<F0>!^<FD>M<F9>qkB<ED><>
+DONE
+---
+Post-Handshake New Session Ticket arrived:
+SSL-Session:
+    Protocol  : TLSv1.3
+    Cipher    : TLS_AES_128_GCM_SHA256
+    Session-ID: D22D318A7FFCA57A41342F75C6F725A356E8D92307ECAA6D86850EE34BEC8537
+    Session-ID-ctx:
+    Resumption PSK: D8EB52F5EE964242EA1EC7364DA75713280C1EA1AFACE38B8D593301DFCB3C55
+    PSK identity: None
+    PSK identity hint: None
+    SRP username: None
+    TLS session ticket lifetime hint: 7200 (seconds)
+    TLS session ticket:
+    0000 - 6e 4c 2d a6 09 7f 17 68-9c d7 4b 0c 58 0c 77 cc   nL-....h..K.X.w.
+    0010 - d9 f1 0a 1f 5d 2b 54 2f-97 79 c4 53 58 bf e7 bb   ....]+T/.y.SX...
+    0020 - 93 06 a4 aa b2 90 02 61-1f 64 f9 d9 ae 47 e6 84   .......a.d...G..
+    0030 - 3c 1f d9 84 62 e7 b5 cb-83 ab 24 0b b7 b9 94 af   <...b.....$.....
+    0040 - 97 7c b6 79 a3 f4 82 b9-17 65 36 9f 94 dc 11 2f   .|.y.....e6..../
+    0050 - 47 35 b4 0f 0b 2e a8 23-ef 32 f3 dc 0d d4 47 c5   G5.....#.2....G.
+    0060 - 9d 56 1e 8a e7 3f d9 3b-f2 21 fd 0a ea 03 ec ba   .V...?.;.!......
+    0070 - 84 c4 f7 52 24 8b a5 92-4b 44 79 d6 8b 65 1e f9   ...R$...KDy..e..
+    0080 - 1a a0 c1 9d f2 c3 b1 ba-65 6a 31 c3 11 ff 8f e3   ........ej1.....
+    0090 - d4 42 fa 31 e1 11 7f 9d-b9 89 8f d5 54 e2 5b b0   .B.1........T.[.
+    00a0 - ef 5c a4 60 5d a7 f0 37-f8 db 03 e7 df d3 cc f0   .\.`]..7........
+    00b0 - 3b 13 df 75 05 5b 7b 9a-b3 b0 ae 07 17 8a 88 da   ;..u.[{.........
+    00c0 - 75 8f ee 8e cb 9a 23 b1-90 e2 ce 79 00 0c ae 45   u.....#....y...E
+    00d0 - 16 03 fa b1 c1 d8 9f 43-69 3a 14 4d bc 4e 61 a2   .......Ci:.M.Na.

-~<DB><C6>n<E8>駁<DF>]2b@<DD>E<A5><AD>!<97>^Ti<F0>G<8D><B4><94><DD><F5>V^<A6>^L<C4>
[...]
-<A0><B6>Mm;-<8F><AB><9E>$<BC>w<E3>f<E1>^O<80><FF>wJ^R<BC>ɻ<CA><C4>^R<89><E1>^^C<B7>^P^M<B5>Z<8C>^XG<A9>E?<F5><FD><C8>^>
+    Start Time: 1657769181
+    Timeout   : 7200 (sec)
+    Verify return code: 0 (ok)
+    Extended master secret: no
+    Max Early Data: 0
+---
+read R BLOCK
+---
+Post-Handshake New Session Ticket arrived:
+SSL-Session:
+    Protocol  : TLSv1.3
+    Cipher    : TLS_AES_128_GCM_SHA256
+    Session-ID: 57A4D799807D7AB7B5A5FC73703CC8994E9EAD23EE525FEDEF3BFA5BC917D316
+    Session-ID-ctx:
+    Resumption PSK: 38EBB103038C1D325AC9964FF68D7C0C04C0A4602937B2F91E3532B98E9825C1
+    PSK identity: None
+    PSK identity hint: None
+    SRP username: None
+    TLS session ticket lifetime hint: 7200 (seconds)
+    TLS session ticket:
+    0000 - 6e 4c 2d a6 09 7f 17 68-9c d7 4b 0c 58 0c 77 cc   nL-....h..K.X.w.
+    0010 - 1e 98 52 4c 46 09 6e c0-8a 9c d9 66 70 0b fe 6a   ..RLF.n....fp..j
+    0020 - 0c d9 ff 32 3d 61 80 81-e7 2c 3f 21 ed c3 4f 98   ...2=a...,?!..O.
+    0030 - ef b3 0c 17 92 2d 43 f9-f0 fa 79 09 d0 55 32 c1   .....-C...y..U2.
+    0040 - 7f 23 aa 9b 21 75 28 bf-d1 d3 cd d0 3b 29 bd a6   .#..!u(.....;)..
+    0050 - d2 ad 9a e2 38 1f 42 c6-1d 57 dd 99 60 00 fa e1   ....8.B..W..`...
+    0060 - 40 2b c5 1f 2a c6 ec 77-de 0a 77 53 21 91 73 38   @+..*..w..wS!.s8
+    0070 - f9 21 f6 7c 51 8c ee 54-6a bd 7d c2 0e e6 b2 92   .!.|Q..Tj.}.....
+    0080 - c6 a9 11 ae 98 5b 7e f0-da 30 59 55 ac 48 17 9b   .....[~..0YU.H..
+    0090 - 56 f4 02 49 78 fb 68 ee-bb 2f de f1 82 a3 f6 57   V..Ix.h../.....W
+    00a0 - 83 79 ca 9a 02 14 0b 1c-cf 8d e8 b2 1e 71 11 80   .y...........q..
+    00b0 - 81 20 da d9 f1 7e 29 e3-c3 53 24 5f 66 19 ac 2a   . ...~)..S$_f..*
+    00c0 - b1 bc 96 bd 7f 0a 27 d6-c1 11 cd bd 18 c4 7e 6b   ......'.......~k
+
+    Start Time: 1657769181
+    Timeout   : 7200 (sec)
+    Verify return code: 0 (ok)
+    Extended master secret: no
+    Max Early Data: 0
+---
+read R BLOCK
```

Forcing TLS to TLSv1.2 in the hanging (ANOTHER) client shows a different "negotiation" yet a similar lock-up.

```
{ echo -ne "GET /artifactory/bds-integrations-release/com/synopsys/integration/synopsys-detect/7.14.0/synopsys-detect-7.14.0.jar HTTP/1.1\r\nHost: sig-repo.synopsys.com\r\n\r\n"; sleep 2; } | openssl s_client -connect sig-repo.synopsys.com:443 -servername sig-repo.synopsys.com -tls1_2 2>&1 | head -500 > synopsys-from-openssl-3.0.4-tls1.2-ANOTHER-NETWORK.txt

diff -u synopsys-from-openssl-3.0.4-{ONE,tls1.2-ANOTHER}-NETWORK.txt
```

```
@@ -68,433 +68,42 @@
 Peer signature type: RSA-PSS
 Server Temp Key: X25519, 253 bits
 ---
-SSL handshake has read 4686 bytes and written 387 bytes
+SSL handshake has read 4799 bytes and written 311 bytes
 Verification: OK
 ---
-New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
+New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
 Server public key is 2048 bit
-Secure Renegotiation IS NOT supported
+Secure Renegotiation IS supported
 Compression: NONE
 Expansion: NONE
 No ALPN negotiated
-Early data was not sent
-Verify return code: 0 (ok)
----
-HTTP/1.1 200
-Date: Thu, 14 Jul 2022 03:43:42 GMT
-Content-Type: application/java-archive
-Content-Length: 33148012
-Connection: keep-alive
-X-JFrog-Version: Artifactory/7.31.13 73113900
-X-Artifactory-Id: 008161788361eb9aa27f0224e9f393244c8d6905
-X-Artifactory-Node-Id: artifactory-0
-Last-Modified: Thu, 23 Jun 2022 18:54:47 GMT
-ETag: dc7fa7f686ccaf1614ca02b512f9ec4d6579441a
-X-Checksum-Sha1: dc7fa7f686ccaf1614ca02b512f9ec4d6579441a
-X-Checksum-Sha256: 1f3c580dbacc9bf55854e3af21c4dfc6ca40ec446f225c355581f70201619ded
-X-Checksum-Md5: 5d99a014a6ff707db42be67103e08d41
-Accept-Ranges: bytes
-X-Artifactory-Filename: synopsys-detect-7.14.0.jar
-Content-Disposition: attachment; filename="synopsys-detect-7.14.0.jar"; filename*=UTF-8''synopsys-detect-7.14.0.jar
-Strict-Transport-Security: always
-Set-Cookie: visid_incap_2638074=XefkkTl9RyCV3zHEUVVy+e2Qz2IAAAAAQUIPAAAAAAB80c80idUu1EDZ9g/+vunP; expires=Thu, 13 Jul >
-Set-Cookie: incap_ses_1445_2638074=SApufdMj6G+RYejrJKwNFO2Qz2IAAAAAF4+W5z0kh139msvWhNdZzA==; path=/; Domain=.synopsys.>
-X-CDN: Imperva
-X-Iinfo: 14-30600870-30600874 NNNN CT(38 37 0) RT(1657770221497 13) q(0 0 0 3) r(1 1) U5
-
-PK^C^D^T^@^H^H^H^@<B9>v<D7>T^@^@^@^@^@^@^@^@^@^@^@^@^T^@^@^@META-INF/MANIFEST.MFĽY<93><A2>l<B3>6z<FE>E<AC><FF><B0>^N<D>
[...]
-<F5><C0><A3><D9>-<BA><F2><87><8F>&u<82><BD><E2><A8>ui<D1>"/<92>v<E2>Sn^]<A0>'R^O7ܱ<D2>e\^PB<C9>R<F0>!^<FD>M<F9>qkB<ED><>
+SSL-Session:
+    Protocol  : TLSv1.2
+    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
+    Session-ID: 59A7826363BCFD78AE2BE89A9DA38777341F64271FD870264FB8FE8CF0A26E4C
+    Session-ID-ctx:
+    Master-Key: D5C3182B2AA92E498E773E731EE77D2327C785D63E8A6FEFA843068ACE91AF3678D5A31D547DD0EB8B57FF9B6CA52637
+    PSK identity: None
+    PSK identity hint: None
+    SRP username: None
+    TLS session ticket lifetime hint: 7200 (seconds)
+    TLS session ticket:
+    0000 - 6e 4c 2d a6 09 7f 17 68-9c d7 4b 0c 58 0c 77 cc   nL-....h..K.X.w.
+    0010 - 6a ef 64 c4 64 b1 a2 c7-bc 77 37 78 2a 00 08 e8   j.d.d....w7x*...
+    0020 - ce 86 ed c3 02 6b 22 12-81 ec 62 ec ab 77 ea 7f   .....k"...b..w..
+    0030 - 72 e0 d7 25 14 65 16 4e-37 e5 37 2d 93 5c 5a 30   r..%.e.N7.7-.\Z0
+    0040 - 6e 92 2a 39 0c 42 05 98-79 fc 23 a0 52 d3 c6 4e   n.*9.B..y.#.R..N
+    0050 - 0d d1 66 0d e8 71 ae 09-01 31 21 32 71 6e c3 98   ..f..q...1!2qn..
+    0060 - a7 69 aa 50 b8 d6 b5 77-2a ed 7c 98 c4 f3 9d 6a   .i.P...w*.|....j
+    0070 - 04 ef a2 d7 ed 20 df d5-d6 4e d1 66 d5 22 bc 9f   ..... ...N.f."..
+    0080 - 7b e9 1a f5 49 b7 c5 38-86 c7 2b 43 a6 9a 35 8f   {...I..8..+C..5.
+    0090 - bc 2e 6c 35 d7 27 31 d1-da 82 55 64 6e dc dc a0   ..l5.'1...Udn...
+    00a0 - 73 50 d3 c7 f7 71 18 dc-17 88 d8 b2 4a 19 b2 00   sP...q......J...
+    00b0 - 0c a0 4c 47 3b a6 fc 11-42 50 ae 65 42 9e 33 63   ..LG;...BP.eB.3c

-~<DB><C6>n<E8>駁<DF>]2b@<DD>E<A5><AD>!<97>^Ti<F0>G<8D><B4><94><DD><F5>V^<A6>^L<C4>
-<A0><B6>Mm;-<8F><AB><9E>$<BC>w<E3>f<E1>^O<80><FF>wJ^R<BC>ɻ<CA><C4>^R<89><E1>^^C<B7>^P^M<B5>Z<8C>^XG<A9>E?<F5><FD><C8>^>
+    Start Time: 1657771131
+    Timeout   : 7200 (sec)
+    Verify return code: 0 (ok)
+    Extended master secret: yes
+---
+DONE
```
