### ISSUE TITLE
curl 7.71.1 not work with cookie

### ISSUE THREAD

**Issue by iosola** [curl/curl#5781]
I've curl 7.71.1 in centos 7.

curl --version
curl 7.71.1 (x86_64-redhat-linux-gnu) libcurl/7.71.1 NSS/3.44 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.9.0 nghttp2/1.33.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL UnixSockets

Im trying to login in a web with user/pass and then navegate it for found a word.
This it works on curl 7.29, but I need upgrade curl.
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

I do:
curl -s -L -k -l 'URL' -H 'Cookie: JSESSIONID=XXX; _ga=XXX; _gid=XXX; __utma=XXX; __utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'  --dump-header /path/headers.file

I get the value in the new file:
<input type="hidden" name="execution" value="YYYY" />

And the value:
<input type="hidden" name="lt" value="ZZZZ" />

curl -v -s -L -k -l -b /path/headers.file 'URL' -H 'Cookie: JSESSIONID=XXX; _ga=XXX; _gid=XXX; __utma=XXX; __utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' --data 'username=USER&password=PASS&lt='ZZZZ'&execution='YYYY'&_eventId=submit&submit=Continuar' --dump-header /path/headers.login.file

the verbose show me this:
~~~
*   Trying IP:443...
* Connected to URL (IP) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* skipping SSL peer certificate verification
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: C=ES,CN=*.XXX
*       start date: Oct 15 06:43:41 2018 GMT
*       expire date: Oct 14 06:43:41 2020 GMT
*       common name: *.XXX.es
*       issuer: CN=Camerfirma XXXX
> POST URL HTTP/1.1
> Host: URL
> User-Agent: curl/7.71.1
> Accept: */*
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
> Content-Length: 121
> Content-Type: application/x-www-form-urlencoded
>
} [121 bytes data]
* upload completely sent off: 121 out of 121 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Wed, 05 Aug 2020 06:34:32 GMT
< Server: Apache
< Cache-Control: no-store
* Added cookie JSESSIONID="YYY" for domain XXX.es, path /XX, expire 0
< Set-Cookie: JSESSIONID=YYY; path=/XXX; secure; HttpOnly
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Location: https://URL
< Access-Control-Allow-Origin: https://URL
< X-Content-Type-Options: nosniff
< Content-Length: 0
<
* Connection #0 to host HOST left intact
* Issue another request to this URL: 'https://URL'
* Switch from POST to GET
* Found bundle for host URL: 0x14ae0 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host HOST
* Connected to HOST (IP) port 443 (#0)
> GET URL HTTP/1.1
> Host: HOST
> User-Agent: curl/7.71.1
> Accept: */*
> Cookie: JSESSIONID=YYYY
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 05 Aug 2020 06:34:32 GMT
< Server: Apache
< Cache-Control: no-store
* Replaced cookie JSESSIONID="YYYY" for domain XXX.es, path /XXX, expire 0
< Set-Cookie: JSESSIONID=YYYY; path=/XXX; secure; HttpOnly
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: https://URL
< X-Content-Type-Options: nosniff
< Content-Type: text/html;charset=ISO-8859-15
< Content-Length: 13418
<
{ [8184 bytes data]
* Connection #0 to host HOST left intact
~~~
But the content of the web show me that not do login, because is the same web that requires credentials.
All this with version curl 7.29.0 works, but now not and I dont know why, not error, not info..

Any idea?

**Comment by bagder** [comment]
Can you do the same operation with the working curl version and show us that log so that we compare the differences?

**Comment by iosola** [comment]
With curl 7.29

* About to connect() to HOST port 443 (#0)
*   Trying IP...
* Connected to HOST (IP) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: C=ES,CN=XXXX
*       start date: Oct 15 06:43:41 2018 GMT
*       expire date: Oct 14 06:43:41 2020 GMT
*       common name: *.XXX.es
*       issuer: CN=Camerfirma XXXX
> POST URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: HOST
> Accept: */*
> Cookie: JSESSIONID=YYYY
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
> Content-Length: 121
> Content-Type: application/x-www-form-urlencoded
>
} [data not shown]
* upload completely sent off: 121 out of 121 bytes
< HTTP/1.1 302 Found
< Date: Wed, 05 Aug 2020 09:29:38 GMT
< Server: Apache
< Cache-Control: no-store
* Added cookie CASPRIVACY="" for domain HOST, path /XXX/, expire 1596619778
< Set-Cookie: CASPRIVACY=; path=/XXX/; secure; HttpOnly; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:00 GMT
* Added cookie CASTGC="TGT-107-kBGT7I1ULkR5uMtqaBM1EfNtFNWtMuQwb3M4eimSBJ2j43Mloi-cas" for domain HOST.es, path /XXX/, expire 0
< Set-Cookie: CASTGC=TGT-107-kBGT7I1ULkR5uMtqaBM1EfNtFNWtMuQwb3M4eimSBJ2j43Mloi-cas; path=/XXX/; secure; HttpOnly
* Added cookie JSESSIONID=YYYY for domain HOST.es, path /XXX, expire 0
< Set-Cookie: JSESSIONID=YYYY; path=/XXX; secure; HttpOnly
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Location: URL
< Access-Control-Allow-Origin: URL
< X-Content-Type-Options: nosniff
< Content-Length: 0
<
* Connection #0 to host HOST left intact
* Issue another request to this URL: 'URL'
* Violate RFC 2616/10.3.3 and switch from POST to GET
* Found bundle for host HOST: 0x12cfbf0
* Re-using existing connection! (#0) with host HOST
* Connected to HOST (IP) port 443 (#0)
> GET URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: HOST
> Accept: */*
> Cookie: CASTGC=TGT-107-XXX; JSESSIONID=XXX; JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
< HTTP/1.1 302 Found
< Date: Wed, 05 Aug 2020 09:29:38 GMT
< Server: Apache
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Location: URL
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< Content-Length: 0
<
* Connection #0 to host HOST left intact
* Issue another request to this URL: 'URL'
* Found bundle for host HOST: 0x12cfbf0
* Re-using existing connection! (#0) with host HOST
* Connected to HOST (IP) port 443 (#0)
> GET URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: HOST
> Accept: */*
> Cookie: CASTGC=TGT-107-XXX; JSESSIONID=XXX; JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
>
< HTTP/1.1 200 OK
< Date: Wed, 05 Aug 2020 09:29:38 GMT
< Server: Apache
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: USL
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< Content-Type: text/html;charset=ISO-8859-1
< Content-Language: es-ES
< Content-Length: 16947
<
{ [data not shown]
* Connection #0 to host HOST left intact

**Comment by bagder** [comment]
I don't think you've done this right. You said you used this command line:

`curl -s -L -k -l 'URL' -H 'Cookie: JSESSIONID=XXX; _ga=XXX; _gid ...`

Ie the provided `Cookie:` header starts with JSESSIONID. Then you show your request and then the `Cookie:` looks like this:
~~~
Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
~~~
... *without* a JSESSIONID in there. Where did that go?

In your second (working) command line, that first request instead sends two `Cookie:` headers:
~~~
Cookie: JSESSIONID=YYYY
Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXXutmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
~~~

How did that happen?

**Comment by iosola** [comment]
uhm, I dont know :/
I rewritten the commands:

curl -v -s -L -k -l 'URL' -H 'Cookie: JSESSIONID=XXX; _ga=XXX; _gid=XXX; __utma=XXX; __utmc=XXX __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'  --dump-header /path/headers.file 

curl -v -s -L -k -l -b /path/headers.file 'URL' -H 'Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' --data 'username=USER&password=PASS&lt='CODE'&execution='CODE'&_eventId=submit&submit=Continuar' --dump-header /path/headers.login.file


The result of 2 curl on curl 7.29 is:

* About to connect() to URL port 443 (#0)
*   Trying IP...
* Connected to URL (IP) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: C=ES,CN=*XXX
*       start date: Oct 15 06:43:41 2018 GMT
*       expire date: Oct 14 06:43:41 2020 GMT
*       common name: *.XXX.es
*       issuer: CN=Camerfirma XXX
> POST URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: URL
> Accept: */*
> Cookie: JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
> Content-Length: 121
> Content-Type: application/x-www-form-urlencoded
>
} [data not shown]
* upload completely sent off: 121 out of 121 bytes
< HTTP/1.1 302 Found
< Date: Thu, 06 Aug 2020 09:07:31 GMT
< Server: Apache
< Cache-Control: no-store
* Added cookie CASPRIVACY="" for domain URL, path /XXX/, expire 1596704851
< Set-Cookie: CASPRIVACY=; path=/XXX/; secure; HttpOnly; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:00 GMT
* Added cookie CASTGC="XXX" for domain URL, path /XXX/, expire 0
< Set-Cookie: CASTGC=XXX; path=/XXX/; secure; HttpOnly
* Added cookie JSESSIONID="XXX" for domain URL, path /XXX, expire 0
< Set-Cookie: JSESSIONID=XXX; path=/XXX; secure; HttpOnly
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Location: URL
< Access-Control-Allow-Origin: URL
< X-Content-Type-Options: nosniff
< Content-Length: 0
<
* Connection #0 to host URL left intact
* Issue another request to this URL: 'URL'
* Violate RFC 2616/10.3.3 and switch from POST to GET
* Found bundle for host URL: 0x1353bf0
* Re-using existing connection! (#0) with host URL
* Connected to URL (IP) port 443 (#0)
> GET URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: URL
> Accept: */*
> Cookie: CASTGC=XXX; JSESSIONID=XXX; JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
>
< HTTP/1.1 302 Found
< Date: Thu, 06 Aug 2020 09:07:31 GMT
< Server: Apache
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Location: URL
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< Content-Length: 0
<
* Connection #0 to host URL left intact
* Issue another request to this URL: 'URL'
* Found bundle for host URL: 0x1353bf0
* Re-using existing connection! (#0) with host URL
* Connected to URL (IP) port 443 (#0)
> GET URL HTTP/1.1
> User-Agent: curl/7.29.0
> Host: URL
> Accept: */*
> Cookie: CASTGC=XXX; JSESSIONID=XXX; JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
>
< HTTP/1.1 200 OK
< Date: Thu, 06 Aug 2020 09:07:32 GMT
< Server: Apache
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: URL
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< Content-Type: text/html;charset=ISO-8859-1
< Content-Language: es-ES
< Content-Length: 16947
<
{ [data not shown]
* Connection #0 to host URL left intact

**Comment by bagder** [comment]
There's still a discrepancy. The command lines you show cannot generate the HTTP requests you show. So either the command line is wrong or your curl command is not a plain 7.29.0 build. Your first command line:

     curl -v -s -L -k -l 'URL' -H 'Cookie: JSESSIONID=XXX; _ga=XXX; _gid=XXX; __utma=XXX; __utmc=XXX __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' --dump-header /path/headers.file

It clearly sends a single cookie header, and yet in your verbose output the request is sent with *two* cookie headers:
~~~
> Cookie: JSESSIONID=XXX
> Cookie: _ga=XXX; _gid=XXX; __utma=XXX;__utmc=XXX; __utmz=XXX.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
~~~

**Comment by bagder** [comment]
This will be closed soon unless we get more explanations.

**Comment by iosola** [comment]
Sorry, I downgrade to curl 7.52 and it works.
Thanks.

**Comment by bagder** [comment]
Then we can progress more here and I will close this. If there truly is a cookie problem in current curl we don't know.
