### ISSUE TITLE
Windows 10 with MinGW: Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by DanteFalzone0** [curl/curl#5801]
### I did this

I installed libcurl with the following commands:

```bash
$ git clone https://github.com/curl/curl
$ cd curl
$ ./buildconf.bat
$ mingw32-make mingw32
$ cp lib/libcurl.a /c/MinGW/lib
$ cp -r include/curl/ /c/MinGW/include
```
I wrote this program to test it out:
```cpp
// main.cpp
#include <iostream>
#include <curl/curl.h>

int main(void) {
    CURL *curl;
    curl_global_init(CURL_GLOBAL_ALL);
    curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(curl, CURLOPT_URL, "https://api.ecs.rocks/v0/util/removeMessageHeader");
    curl_easy_perform(curl);
    curl_free(curl);
    return 0;
}
```

I built the C++ program with the following command:

```bash
$ g++ main.cpp -o curltest -m32 -DCURL_STATICLIB -lcurl -lws2_32 -lwldap32 -lwsock32 -lwinmm
```

And I ran it:

```bash
$ ./curltest.exe
```

### I expected the following

A response of some kind from https://api.ecs.rocks/v0/util/removeMessageHeader

### I got the following

```
* Protocol "https" not supported or disabled in libcurl
* Closing connection -1
```

### curl/libcurl version

```
curl 7.71.1 (x86_64-w64-mingw32) libcurl/7.71.1 OpenSSL/1.1.1g (Schannel) zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP
```

That's the version of `curl` I have, but my version of `libcurl` should be the most recent version because I built from source.

### operating system

MINGW64_NT-10.0-18363 ECSS-L01 3.1.6-340.x86_64 2020-07-09 14:33 UTC x86_64 Msys

**Comment by bagder** [comment]
That's not a bug. You selected to build it without SSL support.

The `INSTALL.md` mentions for example:  `mingw32-make mingw32-ssl-zlib` to build with SSL and Zlib enabled.

That said, I recommend you use configure (with msys) or cmake for building instead.

**Comment by DanteFalzone0** [comment]
Thank you, I tried `mingw32-make mingw32-ssl-zlib` and got this:

```
C:/mingw/bin/mingw32-make -C lib -f Makefile.m32 CFG=mingw32-ssl-zlib
mingw32-make[1]: Entering directory 'C:/Users/dfalzone/curl/lib'
Makefile.m32:264: *** Invalid path to OpenSSL package: ../../openssl-1.0.2a.  Stop.
mingw32-make[1]: Leaving directory 'C:/Users/dfalzone/curl/lib'
Makefile:61: recipe for target 'mingw32-ssl-zlib' failed
mingw32-make: *** [mingw32-ssl-zlib] Error 2
```

I understand that this means I need to install some libraries and specify the paths to those libraries, but I'm not clear on the details of how to do that. How do I install the requisite libraries and tell mingw32-make where to find them?

**Comment by jay** [comment]
OPENSSL_PATH. As bagder has said refer to [INSTALL.md](https://github.com/curl/curl/blob/curl-7_71_1/docs/INSTALL.md#mingw32).

**Comment by DanteFalzone0** [comment]
Okay, I'll try to figure it out. Thank you for your attention and your time.
