### ISSUE TITLE
Curl_cert_hostcheck inverted logic when match_pattern doesn't contain a wildcard

### ISSUE THREAD

**Issue by rmelch** [curl/curl#5807]
### When checking cert against a plain "match_pattern" with no wild cards 
`int match = Curl_cert_hostcheck("foo.bar.com","foo.bar.com");`

### I expected match to be true.

# Proposed fix:

strcasecompare() returns 0 for match!

[curl_hostcheck_no_wildcard.patch.txt](https://github.com/curl/curl/files/5066858/curl_hostcheck_no_wildcard.patch.txt)

```melcher@WS3641:~/workspace/curl/build$ git diff
diff --git a/lib/hostcheck.c b/lib/hostcheck.c
index 9e0db05fa..529f40f08 100644
--- a/lib/hostcheck.c
+++ b/lib/hostcheck.c
@@ -83,7 +83,7 @@ static int hostmatch(char *hostname, char *pattern)
   pattern_wildcard = strchr(pattern, '*');
   if(pattern_wildcard == NULL)
     return strcasecompare(pattern, hostname) ?
-      CURL_HOST_MATCH : CURL_HOST_NOMATCH;
+      CURL_HOST_NOMATCH : CURL_HOST_MATCH;
 
   /* detect IP address as hostname and fail the match if so */
   if(Curl_inet_pton(AF_INET, hostname, &ignored) > 0)
```

### curl/libcurl version curl-7_71_1

curl 7.72.0-DEV (Linux) libcurl/7.72.0-DEV OpenSSL/1.1.1f zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets

### operating system

Linux WS3641 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmelch** [comment]
Alternative fix could be:
` return strcasecmp(pattern, hostname) == 0 ? CURL_HOST_MATCH : CURL_HOST_NOMATCH;`
Which might be clearer.

**Comment by jay** [comment]
It looks like you're confusing [strcasecompare](https://github.com/curl/curl/blob/curl-7_71_1/lib/strcase.c#L180-L193) for strcasecmp. The former returns 1 for match and the latter returns 0 for match.

**Comment by rmelch** [comment]
Thank you for pointing out the obvious, The code I was looking at had been modified to use strcasecmp!
