### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by HideakiAtsuyo** [curl/curl#5809]
### I did this
Build + use the libs and headers in a project in a "curl" named folder
and
```cpp
#define CURL_STATICLIB
#define api "https://awebsite.com?url="
#include <iostream>
#include <stdio.h>
#include <string>
#include <Windows.h>
#include "curl/curl.h"

#ifdef _DEBUG
#pragma comment (lib, "curl/libcurl_a_debug.lib")
#else
#pragma comment (lib, "curl/libcurl_a.lib")
#endif
#pragma comment (lib, "Normaliz.lib")
#pragma comment (lib, "Ws2_32.lib")
#pragma comment (lib, "Wldap32.lib")
#pragma comment (lib, "advapi32.lib")


static size_t writefunciton(void* buffer, size_t size, size_t nmemb, void* param)
{
    std::string& text = *static_cast<std::string*>(param);
    size_t totalsize = size * nmemb;
    text.append(static_cast<char*>(buffer), totalsize);
    return totalsize;
}

 int main()
{
    SetConsoleOutputCP(CP_UTF8);
    std::wcout << "Link:" << std::endl;
    std::string link;
    std::getline(std::cin, link);
    std::string finallink = api;

    finallink += link;

    std::string result;
    CURL* curl;
    CURLcode res;
    curl_global_init(CURL_GLOBAL_DEFAULT);
    curl = curl_easy_init();
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, finallink);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writefunciton);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &result);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
        res = curl_easy_perform(curl);
        curl_easy_cleanup(curl);
        if (CURLE_OK != res) {
            std::cerr << "CURL error: " << res << '\n';
        }
    }
    curl_global_cleanup();
    std::cout << result << "\n\n";
}
```
### I expected the following

Work

### curl/libcurl version

7.55.1
But i have used the files of the 7.71.1 in my project i'm not using the files of path

### operating system

Windows 10 Professional 

https://i.imgur.com/2csuhFB.gif

**Comment by bagder** [comment]
Please show error messages as plain text for better accessibility (plenty of users read/write these issues over email for example). There seems to be lots of warnings on missing symbols starting with `__imp_`... ? 

It's unclear to me how this is a curl bug.

**Comment by MarcelRaad** [comment]
Some of the errors look like you have to additionally link to Crypt32.lib.
The others look like a static vs. dynamic CRT problem. Make sure you're using the same one for building curl and your project using libcurl.

**Comment by HideakiAtsuyo** [comment]
I have change it, now i'm using the curl nuget package but i have always 7 errors

https://i.imgur.com/xSxkR4p.png
"unresolved external symbol X referenced in function main"

**Comment by HideakiAtsuyo** [comment]
Now my code is like this with the 7 errors(they are not in the code)

```cpp
#define CURL_STATICLIB
#define api "https://awebsite.com?url="
#include <iostream>
#include <stdio.h>
#include <string>
#include <Windows.h>
#include <curl/curl.h>

static size_t writefunciton(void* buffer, size_t size, size_t nmemb, void* param)
{
    std::string& text = *static_cast<std::string*>(param);
    size_t totalsize = size * nmemb;
    text.append(static_cast<char*>(buffer), totalsize);
    return totalsize;
}

 int main()
{
    SetConsoleOutputCP(CP_UTF8);
    std::wcout << "Link:" << std::endl;
    std::string link;
    std::getline(std::cin, link);
    std::string finallink = api;

    finallink += link;

    std::string result;
    CURL* curl;
    CURLcode res;
    curl_global_init(CURL_GLOBAL_DEFAULT);
    curl = curl_easy_init();
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, finallink);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writefunciton);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &result);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
        res = curl_easy_perform(curl);
        curl_easy_cleanup(curl);
        if (CURLE_OK != res) {
            std::cerr << "CURL error: " << res << '\n';
        }
    }
    curl_global_cleanup();
    std::cout << result << "\n\n";
}
```

**Comment by jzakrzewski** [comment]
The linker errors suggest that you haven't linked the curl library (correctly).

Additionally this `curl_easy_setopt(curl, CURLOPT_URL, finallink);` will crash.

**Comment by HideakiAtsuyo** [comment]
I have used the nuget package manager...
And why this line will crash?

**Comment by jzakrzewski** [comment]
I know next to nothing about nuget but I suppose you still have to tell the linker to link to libcurl and set the right library directories so it can find the lib. How to do it - no idea - it's been a while since I did anything in VS.

The crash will happen because you pass `std::string` where `const char*` is expected. Since `curl_easy_setopt` is a variadic C function, the compiler is unable to check the types correctly.

**Comment by HideakiAtsuyo** [comment]
Without choose the directory for the libcurl he check in the solution directory

https://i.imgur.com/2pN14Oh.png (Additional Dependencies)
https://i.imgur.com/eW1rgde.png
https://i.imgur.com/i7uC9Bt.png (In my project folder with the cpp file

**Comment by jzakrzewski** [comment]
Those look like symbols from external dependencies (like WinSock). I don't know why you want linking with static libraries but in this case you have to identify all the dependencies and manually add them to "Additional Dependencies". I'd guess you probably need at least "ws2_32.lib", and "crypt32.lib". Possibly others - it depends on how exactly your curl library has been built.

**Comment by HideakiAtsuyo** [comment]
Well i have see a tuto with curl and i need some others libs i have linked like this:

Properties, C/C++, Input, Additional Dependencies: `curl/libcurl_a.lib;Normaliz.lib;Ws2_32.lib;Wldap32.lib;Crypt32.lib;advapi32.lib;`
In the curl folder i have all curl headers with the libcurl and all work now! Finaly!
I'm using the include by the files directly `#include "curl/curl.h"`
Thanks :)
