### ISSUE TITLE
FTPS is broken since libcurl 7.71

### ISSUE THREAD

**Issue by Zenju** [curl/curl#5816]
Hi,

FTPS access (using explicit SSL) is failing for me and my users when using the latest libcurl versions 7.71 and later:

```
curl_easy_perform error:
CURLE_RECV_ERROR: OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)

```
The error codes seem to vary:
```
curl_easy_perform:
CURLE_SSL_CONNECT_ERROR: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

```
These errors happen on all OSs Windows, Linux, macOS, so libcurl + FTPS is practically unusable currently in this state for my app. When turning off TLS and using libcurl unencrypted (= leave CURLOPT_USE_SSL at default) everything works fine again.

After a lot of testing I was able to narrow down the bug to have been introduced after libcurl-7.70.0 (working), and libcurl-7.71.0 (not working)

Further I have found this commit to be the culprit: https://github.com/curl/curl/commit/f002c850d98dc2dbed34d6547a38a6c0b4c89e10

If I use the latest version 7.71.1 and undo the previous commit, libcurl + TLS is working fine again for FreeFileSync!

It seems the change from Curl_ssl_close to Curl_ssl_shutdown doesn't consider the subsequent comment: 

```
       /* Note that we keep "use" set to TRUE since that (next) connection is
         still requested to use SSL */
```

In fact Curl_ssl_shutdown() sets:
```
conn->ssl[sockindex].use = FALSE
```

However, simply setting "conn->ssl[sockindex].use = TRUE" after Curl_ssl_shutdown() is not enough and the bug is still triggered, so it seems there is more that's going wrong.

Regards, Zenju

**Comment by bagder** [comment]
That commit has been partially reverted already. Please try current master.

**Comment by Zenju** [comment]
Master is working fine! Thanks!
