### ISSUE TITLE
SMTP attachment sending trouble

### ISSUE THREAD

**Issue by KonstantIMP** [curl/curl#5821]
### I did this 
I try to sent email with .jpg attachment using this example : https://curl.haxx.se/libcurl/c/smtp-mime.html
It sends, but I recieve it in incorrect. All '\n' characters was changed on "\r\n" and image is incorrect. I tried change mime type and also comment this line curl_mime_type(part, "multipart/alternative");. It doesn't work

### I expected the following 
Correctly sending

### curl/libcurl version :
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
Linux penguin 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

**Comment by bagder** [comment]
Please provide a full source code that reproduces the problem you see.

**Comment by KonstantIMP** [comment]
```
#include <stdio.h>
#include <string.h>
#include <curl/curl.h>
#define FROM    "<Kuzka30z@yandex.ru>"
#define TO      "<mihedovkos@gmail.com>"
#define CC      "<info@example.org>"
static const char *headers_text[] = {
  "Date: Tue, 22 Aug 2017 14:08:43 +0100",
  "To: " TO,
  "From: " FROM " (Example User)",
  "Cc: " CC " (Another example User)",
  "Message-ID: <dcd7cb36-16gb-487a-9f3a-e652a9458efd@"
    "rfcpedant.example.org>", /// I change ID every sending
  "Subject: example sending a MIME-formatted message",
  NULL
};
static const char inline_text[] =
  "This is the inline text message of the e-mail.\r\n"
  "\r\n"
  "  It could be a lot of lines that would be displayed in an e-mail\r\n"
  "viewer that is not able to handle HTML.\r\n";
static const char inline_html[] =
  "<html><body>\r\n"
  "<p>This is the inline <b>HTML</b> message of the e-mail.</p>"
  "<br />\r\n"
  "<p>It could be a lot of HTML data that would be displayed by "
  "e-mail viewers able to handle HTML.</p>"
  "</body></html>\r\n";

int main() {
  CURL *curl;
  CURLcode res = CURLE_OK;
  curl = curl_easy_init();
  if(curl) {
    struct curl_slist *headers = NULL;
    struct curl_slist *recipients = NULL;
    struct curl_slist *slist = NULL;
    curl_mime *mime;
    curl_mime *alt;
    curl_mimepart *part;
    const char **cpp;
    curl_easy_setopt(curl, CURLOPT_URL, "smtps://smtp.yandex.ru");
    curl_easy_setopt(curl, CURLOPT_MAIL_FROM, FROM);
    recipients = curl_slist_append(recipients, TO);
    recipients = curl_slist_append(recipients, CC);
    curl_easy_setopt(curl, CURLOPT_MAIL_RCPT, recipients);
    curl_easy_setopt(curl, CURLOPT_USERNAME, "Kuzka30z"); ///Yandex SMTP need another login, than email
    curl_easy_setopt(curl, CURLOPT_PASSWORD, "Password"); /// This password unreal
    for(cpp = headers_text; *cpp; cpp++)
      headers = curl_slist_append(headers, *cpp);
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
    mime = curl_mime_init(curl);
    alt = curl_mime_init(curl);
    part = curl_mime_addpart(alt);
    curl_mime_data(part, inline_html, CURL_ZERO_TERMINATED);
    curl_mime_type(part, "text/html")
    part = curl_mime_addpart(alt);
    curl_mime_data(part, inline_text, CURL_ZERO_TERMINATED);
    part = curl_mime_addpart(mime);
    curl_mime_subparts(part, alt);
    curl_mime_type(part, "image/jpeg"); ///O try to chnge mime and commented this line
    slist = curl_slist_append(NULL, "Content-Disposition: inline"); ///This line I tried comment too
    curl_mime_headers(part, slist, 1);  
    part = curl_mime_addpart(mime);
    curl_mime_filedata(part, "/home/konstantimp/Pictures/Background/akatsiia_listia_kust_181905_1280x720.jpg");
    curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);
    res = curl_easy_perform(curl);
        if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n",
              curl_easy_strerror(res));
    curl_slist_free_all(recipients);
    curl_slist_free_all(headers);
    curl_easy_cleanup(curl);
    curl_mime_free(mime);
  }
  return 0;
}
```

**Comment by KonstantIMP** [comment]
I don't know, how it works in C, because I use C++, but it can be trouble with file reading.
In C++ std::ifstream(object for reading from file) change '\n' to "\r\n" for multiplatform working if file had opened without binary_read flag(std::ios_base::binary). I looked and libCURL opens files with "rt" mode. 't' is a mode for work with text and I think, that text mode automaticly change '\n' to "\r\n" for multiplatform working.
When I download file from my reciever email, file is biger than original

**Comment by bagder** [comment]
I would recommend you to use DEBUGFUNCTION to get to see exactly the contents libcurl sends/receives and then adapt your code to work accordingly.

For example, you may want to not attach the JPEG image as plain binary but you probably want it base64 encoded. Use `curl_mime_encoder` to set an encode for a specific mime part.

The \r\n comment I don't understand. SMTP uses CRLF newlines. And no, libcurl does not "open files with `rt` mode" in general. It uses different modes depending on context and the fopen in the mime.c code uses "rb"
