### ISSUE TITLE
SSL/TLS Resumption

### ISSUE THREAD

**Issue by alenloncaric** [curl/curl#5823]
Guys hi,

I created a shared object that is global:
```
    static CURLSH* curl_session_share_object;
    curl_session_share_object = curl_share_init();
    curl_share_setopt(curl_session_share_object, CURLSHOPT_SHARE, CURL_LOCK_DATA_SSL_SESSION);
```

Then on each call i use this shared object in a curl handle:

```
void doCall()
{
    CURL* curl;
    curl = curl_easy_init();
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
    curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);
    if(curl_session_share_object!= NULL)
      	    curl_easy_setopt(curl, CURLOPT_SHARE, curl_session_share_object);
    curl_easy_setopt(curl, CURLOPT_URL, "www.google.com");
    CURLcode res;
    res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
}
```

I did mutliple doCall calls, but i can always see in the verbose (above function is for no clutter without debug trace funcs) a full client/server handshake.

What am i doing wrong ? Shouldn't this be enough to reuse SSL session in Openssl?
I would expect the session to be reused.

### curl/libcurl version
7.65.3

Thank you!

**Comment by gvanem** [comment]
This looks like the [`shared-connection-cache.c`](https://github.com/curl/curl/blob/master/docs/examples/shared-connection-cache.c)  example. Changing to `www.google.com` and a `set CURL_SSL_BACKEND=schannel` works fine for me.

An issue with OpenSSL only? Try another SSL-backend if you can.

**Comment by bagder** [comment]
@alenloncaric: so what TLS backend did you use? (`curl -V` output would suffice)

**Comment by bagder** [comment]
Okay, the report actually mentions openssl but no response in 21 days to point that out...

My primary question is however how come this example doesn't reuse the entire connection in the first place? It shouldn't need to resume any TLS session at all...

**Comment by bagder** [comment]
Seems we lost the reporter with lack of info in the report. Closing
