### ISSUE TITLE
Curl downloads 0 bytes of this URL

### ISSUE THREAD

**Issue by alex3kov** [curl/curl#5825]
### I did this
`curl -O 'https://oper.ru/video/getaudio/interview_prokhorov11.mp3'`
### I expected the following
Get an mp3 file (58Mb), wget works fine on this URL. I can post logs. Curl creates interview_prokhorov11.mp3 file of 0 bytes.
### curl/libcurl version
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux perslap 5.7.12-gnu-1 #1 SMP PREEMPT Fri, 07 Aug 2020 23:29:22 +0000 x86_64 GNU/Linux

**Comment by falconindy** [comment]
The http status returned by the server is a 302, so curl does the correct thing when it saves a 0 byte file. If you want to follow redirects, include the `-L` option.

**Comment by alex3kov** [comment]
Works with `-L`, thanks @falconindy
