### ISSUE TITLE
Poor output with --verbose

### ISSUE THREAD

**Issue by jmdavitt** [curl/curl#5826]
### I did this...

...while writing some code that receives, transforms, and runs curl requests.
 
curl -v -s -X GET -H ... 'https://api.XXXcom:443/sdxs/v1/director...'

### I expected....

...verbose output (lines starting with *, >, <, {, &c.) before the content.
But the line detailing CApath started with spaces!

Here is sample output Mmarkdown turned asterisks to bullets):
~~~
* About to connect() to api.us-eaXXX.com port 443 (#4922 
*   Trying 34.202.246.104...
* Connected to api.us-eXXXcom (34.XXX104) port 443
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
~~~
### curl/libcurl version

curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44
zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps
pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL
libz unix-sockets

### operating system

Linux davitja.vzbi.com 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
Why is that poor? What did you expect instead? You're using an **ancient** curl version.

**Comment by jmdavitt** [comment]
It's poor because the line should have started with an asterisk like all the accompanying output in that section.

Re "using an ancient curl version:" I agree... but I don't get to make those choices.

**Comment by bagder** [comment]
Aha, you speak of the `CApath` line. This output was introduced in curl in 1e98727c55, soon 17 years ago. Yeah, I agree, it would be more consistent to have it start with an asterisk on that line...
