### ISSUE TITLE
-G for libcurl

### ISSUE THREAD

**Issue by rafak360** [curl/curl#5828]
Here's the issue explained on: [stackoverflow](https://stackoverflow.com/questions/63444328/how-to-perform-get-encoded-json)

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by bagder** [comment]
libcurl (obviously) already features all the building blocks for doing `-G` so I'm not at all convinced it needs anything more...

**Comment by rafak360** [comment]
@bagder So could you please show me a simple example using a -G request?

**Comment by bagder** [comment]
1. Set `CURLOPT_HTTPGET`
2. Append the string to the end of the URL (if it doesn't end with a slash, add a '?` as a separator)

Remember: this is an issue tracker, not a helpdesk. Use the curl-library mailing list for help, questions and support.
