### ISSUE TITLE
CMake 3.10.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Togtja** [curl/curl#5830]
### I did this

I am normally running my project that uses libcurl on Ubuntu 20.04. However today I tried compiling it on WSL Ubuntu 18.04. Building failed due to a bunch of errors in Openssl's `dso_dlfcn.c`, similar to #1426.

I do not know exactly what caused this error, however, it seems to be related to CMake versions 
This error was fixed for me by updating to CMake 3.16.3 (The one currently supported on Ubuntu 20.04). Ubuntu 18.04s are normally running 3.10.2. 

The build errors
```
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:116: undefined reference to `dlopen'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:119: undefined reference to `dlerror'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:138: undefined reference to `dlclose'
[build] openssl/lib/libcrypto.a(dso_dlfcn.c.o): In function `dlfcn_unload':
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:161: undefined reference to `dlclose'
[build] openssl/lib/libcrypto.a(dso_dlfcn.c.o): In function `dlfcn_bind_func':
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:186: undefined reference to `dlsym'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:189: undefined reference to `dlerror'
[build] openssl/lib/libcrypto.a(dso_dlfcn.c.o): In function `dlfcn_pathbyaddr':
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:422: undefined reference to `dladdr'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:440: undefined reference to `dlerror'
[build] openssl/lib/libcrypto.a(dso_dlfcn.c.o): In function `dlfcn_globallookup':
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:447: undefined reference to `dlopen'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:450: undefined reference to `dlsym'
[build] /home/ubuntuold_work/curl_project/Packages/openssl/openssl/crypto/dso/dso_dlfcn.c:451: undefined reference to `dlclose'
```
### curl/libcurl version
7.71.1

### operating system
WSL Ubuntu 20.04

**Comment by bagder** [comment]
Without getting and seeing the exact errors it's hard to understand what problem you saw.

**Comment by Togtja** [comment]
I am trying to get back to the old cmake version, so give me 30 minutes, I accedently posted it, before I was ready

**Comment by Togtja** [comment]
There! Got my Ubuntu back to CMake 3.10.2 and ran a rebuild, so updated my issue with the log

**Comment by bagder** [comment]
Curious, that looks like they're all symbols from libdl, but why does the cmake version change anything about -ldl detection and use?

**Comment by Togtja** [comment]
I also found this very weird, if there is anything you want me to try out, just give me some suggestions. I have no idea how to even start tackling this issue.

**Comment by jzakrzewski** [comment]
I have a feeling that this https://gitlab.kitware.com/cmake/cmake/-/commit/8098bd5768d012ceb078fdefdc1b35e1b74e984a have fixed it on the CMake side.

**Comment by bagder** [comment]
Ah, seems highly relevant. I presume we can then consider this as a cmake issue. Using a fixed cmake makes the problem go away.
