### ISSUE TITLE
SCP upload file failed.

### ISSUE THREAD

**Issue by IamFive** [curl/curl#5831]
### I did this

I try to upload file using scp/sftp protocol with libcurl. The code for both protocol is almost the same except the `CURLOPT_URL` option. For sftp, the url is `sftp://user:urlencoded(pass)@example.com:port/path/filename`, while `scp://user:urlencoded(pass)@ example.com:port/path/filename` for scp. Everything works fine when protocol is sftp, but when switch to scp.

Main test code is pretty simple::

```
curl = curl_easy_init();
    if (!curl) {
        result->code = UTOOLE_CURL_INIT_FAILED;
        goto FAILURE;
    }

    /** reset CURL timeout for uploading file */
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, CURL_UPLOAD_TIMEOUT);

    /** setup CURL upload options */
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
    curl_easy_setopt(curl, CURLOPT_URL, remoteUrl);
    curl_easy_setopt(curl, CURLOPT_READFUNCTION, CurlReadLocalFileToStream);
    curl_easy_setopt(curl, CURLOPT_READDATA, uploadFileFp);
    curl_easy_setopt(curl, CURLOPT_INFILESIZE, (long) fileInfo.st_size);

    bool finished = false;
    curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);
    curl_easy_setopt(curl, CURLOPT_PROGRESSFUNCTION, CurlPrintUploadProgressCallback);
    curl_easy_setopt(curl, CURLOPT_PROGRESSDATA, &finished);

    /* enable verbose for easier tracing */
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

    /* Perform the request, res will get the return code */
    result->code = curl_easy_perform(curl);
```

- CURL verbose output for scp::

```
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 12222 (#0)
* SSH MD5 fingerprint: 32ad0d2fd32fa3e322fbf1dcd73e4fe9
* SSH authentication methods available: publickey,password
* Using SSH private key file '/root/.ssh/id_rsa'
* SSH public key authentication failed: Unable to extract public key from private key file: Method unimplemented in libgcrypt backend
* Initialized password authentication
* Authentication complete
* SSH CONNECT phase done
* Unknown error while getting error string
* Connection #0 to host x.x.x.x left intact
```

**sometimes the error is: "Error in the SSH layer".**

- CURL verbose output for sftp::

```
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 12222 (#0)
* SSH MD5 fingerprint: 32ad0d2fd32fa3e322fbf1dcd73e4fe9
* SSH authentication methods available: publickey,password
* Using SSH private key file '/root/.ssh/id_rsa'
* SSH public key authentication failed: Unable to extract public key from private key file: Method unimplemented in libgcrypt backend
* Initialized password authentication
* Authentication complete
* We are completely uploaded and fine
Uploading file... Progress: 100%.
* Connection #0 to host x.x.x.x left intact
```

### I expected the following
scp should work as sftp.

### curl/libcurl version

```
$ ./curl-config --version
libcurl 7.57.0-DEV
```

[curl -V output]

### operating system

Linux Qianbiao 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
1. Does SCP work against this server with other clients?
2. Have you tried with a more recent curl? That's a pretty old version.
3. What SSH library and version are you using?
4. Does it work against any other servers?

**Comment by IamFive** [comment]
1. Does SCP work against this server with other clients?
i can use scp command to upload file directly.

1. Have you tried with a more recent curl? That's a pretty old version.
no, did not. Our project does not allow to upgrade this lib.

1. What SSH library and version are you using?
libssh2.so.1.0.1

1. Does it work against any other servers?
will try, will update this later.

**Comment by bagder** [comment]
> no, did not. Our project does not allow to upgrade this lib.

So even if we fix a problem you cannot upgrade? That seems rather inflexible...

> libssh2.so.1.0.1

That's the SONAME, not the library version.

**Comment by IamFive** [comment]
1. So even if we fix a problem you cannot upgrade? That seems rather inflexible...
we can patch it.

1. That's the SONAME, not the library version.
i think the lib version is 1.0.1 as shown in filename.

**Comment by bagder** [comment]
> i think the lib version is 1.0.1 as shown in filename.

There never was a libssh2 version 1.0.1. See https://libssh2.org/changes.html

**Comment by IamFive** [comment]
hi, i tried some code on another type server. scp works too.

So, it seems this issue is caused by some compatibility problem. My target server is pretty differrent like common OS, it's an embed bmc server. But i can directly scp file to it using linux command `scp`.

> There never was a libssh2 version 1.0.1. See https://libssh2.org/changes.html
sorry, this is wierd. I thought the lib suffix identify the version~~, will try to get a real version now.

**Comment by IamFive** [comment]
libssh2 version is 1.5.0-2


Package: libssh2-1                       
State: installed
Automatically installed: yes
Multi-Arch: same
Version: 1.5.0-2ubuntu0.1
Priority: optional
Section: universe/libs
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 255 k
Depends: libc6 (>= 2.14), libgcrypt20 (>= 1.6.1), zlib1g (>= 1:1.1.4)
Description: SSH2 client-side library
 libssh2 is a client-side C library implementing the SSH2 protocol. It supports regular terminal, SCP and SFTP (v1-v5) sessions; port forwarding, X11 forwarding; password, key-based and
 keyboard-interactive authentication. 
 
 This package contains the runtime library.
Homepage: http://libssh2.org/

**Comment by bagder** [comment]
Since libssh2 is the library doing most of the heavy lifting in this case, I would recommend you start out by trying the latest version of that and see if it fixes the problem.

If not, a suitable next step is probably to try a libssh2-example using SCP (side-stepping curl completely) to see if that also reproduces the problem as then we can be *sure* if the problem is in curl code or in libssh2 code.

If that then shows to reproduce in a libssh2-only example application, the issue should rather be moved over to the libssh2 project.

**Comment by IamFive** [comment]
thanks for your adive @bagder, will try libssh2 and feedback.

**Comment by IamFive** [comment]
I have test curl with latest libssh2, still raise same error.  Not sure why libssh2 shows 1.8.0, I download libssh2 latest released source code 1.9.0.

[root@localhost bin]# ./curl --version
curl 7.57.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.57.0-DEV OpenSSL/1.0.2k zlib/1.2.7 libssh2/1.8.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy 

```
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 12222 (#0)
* SSH MD5 fingerprint: 32ad0d2fd32fa3e322fbf1dcd73e4fe9
* SSH authentication methods available: publickey,password
* Using SSH private key file ''
* SSH public key authentication failed: Unable to extract public key from private key file: Unable to open private key file
* Initialized password authentication
* Authentication complete
* SSH CONNECT phase done
* Unexpected channel close
* Connection #0 to host x.x.x.x left intact
```

**Comment by IamFive** [comment]
And finally, I test scp upload using libssh 1.9.0.  I run examples\scp_write.c directly and it outputs::

```
Fingerprint: 45 FC 54 6F 42 5E AB 21 A0 18 35 10 50 91 61 B0 A5 EF EB 93 
Unable to open a session: (-28) Unexpected channel close
all done
```

So, it seems the issue is caused by libssh2 lib.

**Comment by bagder** [comment]
Yes as clearly the problem still triggers when curl is out of the picture. I would recommend building libssh2 debug enabled and get a full trace from the failure and then continue here: https://github.com/libssh2/libssh2

A possible work-around could be to try building with libssh instead, as that's a separate implementation it isn't likely to suffer from the same set of bugs!

**Comment by IamFive** [comment]
I enabled trace with `libssh2_trace(session, LIBSSH2_TRACE_SCP);`, but it seems did not output more info.
We finally determinate to use sftp instread scp, work fine now.

```
[libssh2] 0.137847 SCP: Opening channel for SCP send
Unable to open a session: (-28) Unexpected channel close
all done
```

**Comment by stweil** [comment]
Debian bullseye still shows this bug.

**Comment by bagder** [comment]
@stweil this is the **curl** issue tracker. If you have a problem with the latest curl version then please submit an issue and describe it in detail. If you experience a problem with an old curl just because your distro hasn't updated, then file an issue with your distro. End of discussion here.
