### ISSUE TITLE
MS-DOS: CURL_CA_BUNDLE default?

### ISSUE THREAD

**Issue by joneskoo** [curl/curl#5844]
I'm trying to figure out what path cURL (CLI) searches for the CA bundle. I read that the file name should be curl-ca-bundle.crt but on MS-DOS file names cannot be that long.

Would it make sense to change the default to ca-bundle.crt on MS-DOS or is it too esoteric to change (and document as exception)?

`set CURL_CA_BUNDLE=C:\CACERT.PEM` seems to work as expected.

I'm using curl 7.64.1 (i386-pc-msdosdjgpp). Release date 2019-03-27.

**Comment by bagder** [comment]
I presume you then mean this section that is Windows specific? curl in general does not look for `curl-ca-bundle.crt`.
https://github.com/curl/curl/blob/d71ac6711a4616a851d048cfa82102d1d9e25bdd/src/tool_operate.c#L2415-L2420

**Comment by bagder** [comment]
The default (full) path used is what libcurl is built to use. I imagine a DOS build has no default path at all.

**Comment by joneskoo** [comment]
You are correct. I totally missed the "If you're using the curl command line tool **on Windows**" on earlier read. I blame reading the raw HTML in Vim.

My bad; setting the environment variable works in any case.

Considering the DOS distribution of cURL I have didn't ship a CA bundle to begin with, let's close this 😎. I'm still amazed TLS 1.3 works on DOS.

Thanks for quick response.

**Comment by bagder** [comment]
Thanks
