### ISSUE TITLE
curl: symbol lookup error: curl: undefined symbol: curl_url_cleanup

### ISSUE THREAD

**Issue by main1015** [curl/curl#5856]
### I did this
I installed it
```
./configure
make
sudo make install
```
Everything is normal when installed.
But I'm following orders
`curl -h`
Error reporting
`curl: symbol lookup error: curl: undefined symbol: curl_url_cleanup`

### curl/libcurl version
	
I downloaded version curl-7.70.0 or curl-7.72.0

[curl -V output]

**Comment by bagder** [comment]
This sounds like you're invoking a new curl that loads an old libcurl at run-time.

**Comment by emilengler** [comment]
Have a look at `man 8 ld.so`
