### ISSUE TITLE
curl_easy_perform blocked on read from a non-continuous stream

### ISSUE THREAD

**Issue by singku** [curl/curl#5869]
### I did this
I am setting read and write function via CURLOPT_READFUNCTION and CURLOPT_WRITEFUNCTION, the input is an iostream and the incoming streaming data is not continuous, which means sometimes the underlying stream buffer might have been drained and there is no data available. When there is no data in the underlying stream buffer, the read function could also be invoked, in this case, read from stream could be blocked until there is data coming, or `eof` is encountered. I then changed to `readsome` to do an unblock reading. Then if there is no data,  I want  the read data function to return 0, and let curl to keep processing the connection, either process input stream when there is more data coming or process response stream. But when read data function returns 0, it seems currently curl take it as eof `Returning 0 will signal end-of-file to the library and cause it to stop the current transfer.`

### I expected the following
curl can identify if a stream is eof or just didn't get any data from the stream.

### curl/libcurl version
7.65

### operating system
Mac Mojave

**Comment by dfandrich** [comment]
The easy interface is blocking; that's just how it's designed. It sounds like the multi interface would be better suited for this application.

**Comment by singku** [comment]
Okay, so after hours of investigating,  worked this around
by returning `CURL_READFUNC_PAUSE` in the read callback function.
and uses `curl_easy_pause()`  to unpause the streaming reading in the write callback function after processing write.

**Comment by singku** [comment]
Closing this issue because it is resolved.

**Comment by jay** [comment]
> Okay, so after hours of investigating, worked this around
> by returning `CURL_READFUNC_PAUSE` in the read callback function.
> and uses `curl_easy_pause()` to unpause the streaming reading in the write callback function after processing write.

Yes, that is an acceptable way to do it. The curl tool has a similar situation and handles it by pausing the stream and then unpausing it the next time the progress callback is called, which should be within a second or less.

https://github.com/curl/curl/blob/curl-7_72_0/src/tool_cb_rea.c#L34-L79

**Comment by jay** [comment]
Oops I did not read that fully. Unpause from the progress callback, not the write callback.

**Comment by singku** [comment]
Looks like CURLOPT_XFERINFOFUNCTION is a better idea in case there is no response stream.

**Comment by jay** [comment]
Yes, that's the progress function.
