### ISSUE TITLE
Slow response from curl with nss for LDAPS request

### ISSUE THREAD

**Issue by nosajsnikta** [curl/curl#5874]
Environment:
1. RHEL 7.8
2. Curl version 7.27 using NSS encryption

When attempting to make an LDAPS request to a Windows domain controller, I am finding curl to be incredibly slow (up to 10 minutes) to return a response (for what is a trivial amount of data).

To check if it was a problem with curl, I downloaded the latest source code 7.72, and rebuilt it with the following flags:

    configure --with-nss --enable-ldaps --enable-ldap
    make
    make install

I then repeated the LDAPS request and it was still painfully slow (but did complete eventually)

I then rebuilt curl with the --with-ssl option, so curl would use openssl instead. I re-run the request and the response was instant.

In addition to this, the slow performance does not happen on either RHEL6 or RHEL8 (curl built with openssl instead here). It is only RHEL7 with curl built to use NSS that is not working as expected.

Has anyone else come across similar issues of curl performing badly with nss?

**Comment by bagder** [comment]
Virtually nobody is using NSS as backend for curl anymore since Red Hat ditched it. The reward for investigating and fixing this issue is extremely low. I would recommend switching to another TLS library as a work-around, or consider options to persuade someone into working on this bug.

**Comment by bagder** [comment]
And isn't RHEL7 shipping curl 7.29.0?

**Comment by nosajsnikta** [comment]
Hi

Thanks for the reply.

Unfortunately the problem I have is that for our product, which is based on
red hat 7.8, we prefer to always use the native packages shipped by red hat
rather than create custom packages that end up giving us a maintenance
hassle.

I'm not expecting a fix of sorts as we know curl with openssl is fine, but
I would just like to know if anyone has experienced this problem and did
they find a workaround for it.

Thanks!

**Comment by Mafia1999** [comment]
Yes
