### ISSUE TITLE
Prototype mismatch: sub main::decode_base64 ($) vs none at getpart.pm line 36.

### ISSUE THREAD

**Issue by mback2k** [curl/curl#5885]
### I did this
`./runtests.pl -a TELNET`

shows:

`Prototype mismatch: sub main::decode_base64 ($) vs none at getpart.pm line 36.`

### I expected the following
No perl warning.

### curl/libcurl version
current master

### operating system
msys2

**Comment by bagder** [comment]
It appears in other occasions too. I wish I understood it better.
