### ISSUE TITLE
voutf handling of mute and showerror configs

### ISSUE THREAD

**Issue by htasta** [curl/curl#5894]
### I did this

curl -sS --retry 5 -o file.out https://www.url.with/error.429

### I expected the following

A message like this:
Warning: Transient problem: HTTP error Will retry in 1 seconds. 20 retries
Warning: left.

But it stayed silent instead.

### curl/libcurl version

newest master branch build

### operating system

linux

I quick-fixed this issue for myself like this:

```
/* tool_msgs.c line 43 */
int show_error = (strcmp(WARN_PREFIX, prefix) == 0 || strcmp(ERROR_PREFIX, prefix) == 0) && config->showerror;
if(!config->mute || show_error) {
```

This checks if showerror is set in the config and bypasses the mute config if the prefix is of type ERROR or WARNING.
This is not the way it should be done.

I think the showerror and mute configs should be handled outside voutf.
So voutf should not be called at all if mute is on and showerror is off inside notef, warnf and errorf.

If you agree, I will make a proper fix instead of the ugly hack above.
Perhaps even make a config option for show-warning because not everyone wants to see warning messages when show-error is on?

P.S.
Is it a bad idea to format the warning/error/note messages differently?
I think this is ugly:
```
Warning: Transient problem: HTTP error Will retry in 1 seconds. 20 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 1 seconds. 19 retries 
Warning: left.
```

imo this is much better:
```
Warning: Transient problem: HTTP error Will retry in 1 seconds. 20 retries 
         left.
Warning: Transient problem: HTTP error Will retry in 1 seconds. 19 retries 
         left.
```

**Comment by bagder** [comment]
1. The message clearly states `Warning:` - it is not an error.
2. `-s` is documented to "Don't show progress meter or error messages."
3. `-S` is documented tas "When used with -s, --silent, it makes curl show an  error  message if it fails."

There was no error. It didn't fail. You asked curl to be silent. I don't see a bug here.

**Comment by htasta** [comment]
Well I consider the http **error** code to be an error. But I guess you don't.

Also I never said it's a bug or there was an error or it failed. I merely stated what I expected and what was delivered.

The use case is not getting spammed by the progress meter but still see when there was an issue.

But I already figured it out myself, I just have to add the -f option which lets curl fail and print an error on 429 but it's not actually failing and still retrying.
So I get the notification of an issue I wanted just with a less descriptive message and the way to get it is .. well .. confusing.
So if I use the -f option curl considers HTTP 429 an error but if I don't use it it's not an error?
Can you see how that's rather confusing?

What about the message formatting? You don't like the white space indentation?

**Comment by bagder** [comment]
> Well I consider the http error code to be an error. But I guess you don't.

curl by default doesn't treat a non-200 HTTP response as an error, because it's not a transfer errorr of any kind. curl transferred the data perfectly fine. You could be using curl to check your server's error pages. It has worked like this since day 1, for over twenty years.

> Also I never said it's a bug or there was an error

You filed it as an issue, here. What else does it mean?

> The use case is not getting spammed by the progress meter but still see when there was an issue.

Then maybe `--no-progress-meter` is what you should rather use?

>  I just have to add the -f option which lets curl fail 

`-f` makes curl consider >= 400 http response code to be an error, yes.

> Can you see how that's rather confusing?

curl has hundreds of options, yes I understand that knowing which ones you use and when is tricky at times. We're working on enhancing `--help` as one way to reduce that complexity. Changing behavior of existing options that are well established and well documented does not help.

> What about the message formatting?

I'm not against the idea, but I when I wrote that code a long time ago I opted to not do it that way since I think it made the  output often look funny anyway and wasn't much of an improvement - especially when just one word is line wrapped. Perhaps that was wrong.

**Comment by htasta** [comment]
I filed an issue because it didn't work as I expected and considering I did some web searching before I wrote an issue here and wrote the quick fix for myself I am not alone with my expectation.
So confusing operation is neither a bug nor an error but it definitely is an issue, that's why I filed it here.

There is a notification of an issue that is printed to stderr (by default) and I used the option "show-error" yet that message is not visible. Nothing like this is documented like this when I ´man curl´ for show-error au contraire if I read the man page for ´--retry´:

>If a transient error is returned when curl tries to perform a transfer, it will retry this number of times before giving up. Setting the number to 0 makes curl do no retries (which is the default). Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408 or 5xx response code. 

It's clearly declared an error, so I'd say it's fair to assume that the option ´--show-error´ shows me this "transient error" the documentation is talking about. But it doesn't because only special errors are shown and these special errors are only triggered if you also enable the option -f to make curl fail.
Now here comes the very confusing part, the ´f-, --fail´ option doesn't even make it fail it chugs on like a happy little locomotive and diligently tries to get the requested resource until the number of retries are reached.


>Changing behavior of existing options that are well established and well documented does not help.

I fully understand this, this is why I asked if there should be an additional option "--show-warning" and I asked if it's a bad idea to change output formatting because some might be parsing that output.
I am not oblivious to the fact that your software is used in billions of devices in vastly different use cases so changes have to be well thought out.

---

**-S, --show-error**

_When used with -s, --silent, it makes curl show an error message if it fails. 
You have to use the option -f, --fail if you want transient errors to be shown.
Transient error means either: a timeout, an FTP 4xx response code or an HTTP 408 or 5xx response code._

Or maybe instead of writing the same explanation to different options make a section on errors where the different errors are explained and how they are triggered. So if someone checks the man page for --show-error they have an easy reference that explains why an error isn't shown despite this option being enabled.

**-S, --show-error**

_When used with -s, --silent, it makes curl show an error message if it fails. 
Check the [error-section](https://www.disney.com) to learn more about error handling in curl._

For the --no-progress-meter option. This indeed also solves my problem and gives me the better error message (with number of retries so I know if it's a single file that failed many times). But again, when reading the man page there is no link to this option in ´-s, --silent´ so it's not apparent that there is such an option and ´-sS´ seems to be the obvious choice·

**-s, --silent**

_Silent or quiet mode. Don't show progress meter or error messages. Makes Curl mute. It will still output the data you ask for, potentially even to the terminal/stdout unless you redirect it.

Use -S, --show-error in addition to this option to disable progress meter but still show error messages.

See also -v, --verbose, --stderr and --no-progress-meter. _


------------

Formatting:

The issue I have is the one I already mentioned. I read it as 4 warnings when it was only 2.
I understand that it would make the code less compact, much easier to just add the prefix on every line.

**Comment by bagder** [comment]
To me, it looks like `--no-progress-meter` satisfies your initial issue. Correct? If so, then I consider this issue closed.

**Comment by htasta** [comment]
Yes it does. I still think there should be more explanation on the different types of errors.
