### ISSUE TITLE
Add curl --mptcp option for testing mptcp

### ISSUE THREAD

**Issue by ericcurtin** [curl/curl#5900]
I could add myself and open the PR if it's ok?

I'll can do a

```
#ifdef IPPROTO_MPTCP

#endif
```

to avoid problems on the platforms that don't support it.

**Comment by bagder** [comment]
Seems totally reasonable. And frankly creating an issue for it is less reasonable as it serves no purpose...

**Comment by ericcurtin** [comment]
Closing...

**Comment by KB5201314** [comment]
@bagder As far as I know MPTCPv1 has been merged into upstream in Linux 5.6. Will there be support for mptcp in curl?

**Comment by bagder** [comment]
feel free to work on it!

(But please don't comment on closed issues to drive the progress.)
