### ISSUE TITLE
Windows VS2013+2017: Unresolved symbols when using the debug builds of libcurl

### ISSUE THREAD

**Issue by sesom42** [curl/curl#5910]
I have compiled the static build of libcurl 7.72.0 with Visual Studio 2013 and 2017. I used the following commands:

For VS2013:
nmake /f Makefile.vc mode=static VC=12 DEBUG=yes RTLIBCFG=static
nmake /f Makefile.vc mode=static VC=12 DEBUG=no RTLIBCFG=static

For VS2017:
nmake /f Makefile.vc mode=static VC=15 DEBUG=yes RTLIBCFG=static
nmake /f Makefile.vc mode=static VC=15 DEBUG=no RTLIBCFG=static

libcurl is compiled without errors. I copied the build results into my project and added CURL_STATICLIB to the preprocessor variables.

The release build of my project compiles and works without problems.

However, I cannot successfully create a debug build. Then I get lots of error messages about unresolved symbols:

error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_easy_escape@@12" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_free@@4" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_global_init@@4" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_slist_append@@8" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_slist_free_all@@4" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_easy_strerror@@4" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_easy_init@@0" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_easy_perform@@4" in Funktion ...
error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "curl_easy_cleanup@@4" in Funktion ...

Release build includes "libcurl_a.lib" and use /MT compiler switch, debug build includes "libcurl_a_debug.lib" and use /MTd compiler switch.

What have I missed?

**Comment by emilengler** [comment]
Would it be possible to provide messages in English rather than German?

**Comment by gvanem** [comment]
Looks like you have compiled your project with `-Gz`. I.e. `__stdcall`. Since `curl/curl.h` doesn't mandate a `__cdecl`, it could happen.

**Comment by sesom42** [comment]
@emilengler: It is almost impossible for Windows users to change the language. Sorry for posting localized error messages. They all mean "unresolved external symbol".

@gvanem: Every time I am amazed how quickly problems in the world of open source software are solved. The reference to __cdecl was just right. The setting /Gd (__cdecl) solved exactly that problem.

This should be mentioned in the documentation for Windows builds!

**Comment by gvanem** [comment]
> The setting /Gd (__cdecl) solved exactly that problem.

This is default AFAICS (so no need to set that). Unless your Makefile / `.vcxproj`-file did set something else. Did you?

**Comment by bagder** [comment]
> This should be mentioned in the documentation

We're always open for improving the docs. Maybe you have a suggestion of what to say and where? I guess https://github.com/curl/curl/blob/master/winbuild/README.md is a suitable file to edit?

**Comment by sesom42** [comment]
My project is already many years old. I don't remember why the /Gz switch was set in the debug build. And yes @gvanem you are right, the default is /Gd.

@bagder this file does not exist in my downloaded zip package. There the (apparently same file) is called winbuild/BUILD.WINDOWS.txt. This is a good place to mention the supported calling convention.

One more thing to say: Thanks for the quick help!
