### ISSUE TITLE
How to import curl to my project as a static library?

### ISSUE THREAD

**Issue by oft** [curl/curl#5960]
### curl/libcurl version

[curl -V output]

### operating system

I hope use curl in my project as a static library,  not a dylib. 

I clone this repo to my project  lib/curl

then add it to cmake file:
```
cmake_minimum_required(VERSION 3.5)

SET(TARGET_NAME app)
PROJECT(${TARGET_NAME})
add_definitions( -DCURL_STATICLIB )
set(ENV{OPENSSL_ROOT_DIR} /usr/local/Cellar/openssl@1.1/1.1.1g)
set(ENV{LIBSSH2_INCLUDE_DIR} /usr/local/Cellar/libssh2/1.9.0_1/include)
set(ENV{LIBSSH2_LIBRARY} /usr/local/Cellar/libssh2/1.9.0_1)

IF(APPLE)
    SET(ARCHITECTURE x64)
ELSEIF(CMAKE_CL_64)
    SET(ARCHITECTURE x64)
ELSE()
    SET(ARCHITECTURE x86)
ENDIF()

set( CURL_LIBRARY ${CMAKE_SOURCE_DIR}/lib )
set( CURL_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include )
find_package( CURL )

include_directories(${CURL_INCLUDE_DIRS})
add_subdirectory(lib/curl)
link_directories(${CURL_LIBRARYS})

FILE(GLOB_RECURSE SOURCE source/*.cpp)

SET(TARGET_SOURCE ${SOURCE})

ADD_EXECUTABLE(${TARGET_NAME} ${TARGET_SOURCE})

TARGET_LINK_LIBRARIES(${TARGET_NAME} ${LIBRARIES})
target_link_libraries(${TARGET_NAME} curl)

SET_PROPERTY(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 14)

SET_TARGET_PROPERTIES(${TARGET_NAME}
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin/${Configuration}"
    LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin/${Configuration}"
    RUNTIME_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin/${Configuration}"
    OUTPUT_NAME ${TARGET_NAME}.${ARCHITECTURE}
    VERSION 1.0 SOVERSION 0
)
```
but i got an error as below

```
CMake Error at CMakeLists.txt:57 (target_link_libraries):
  Target "curl" of type EXECUTABLE may not be linked into another target.
  One may link only to INTERFACE, OBJECT, STATIC or SHARED libraries, or to
  executables with the ENABLE_EXPORTS property set.
```
I don't know how to fix it, please help me.

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

**Comment by jzakrzewski** [comment]
@oft You're doing weird things there - you seem to add curl using `add_subdirectory()` AND `find_package()` typically it's one or the other.
If you'll go the `add_subdirectory()` method, I believe the library target is called `libcurl` - as the error message tells you, `curl` is the executable target.

**Comment by oft** [comment]
@jzakrzewski  sorry, i am a novice,  thank you for your help.

i modify my cmake content to `target_link_libraries(${TARGET_NAME} libcurl)`.

but i got a linker error when  i build this project

![image](https://user-images.githubusercontent.com/18000037/93089933-a202a680-f6ce-11ea-9979-4c165da77cae.png)

it seem generate a shared library `libcurl.dylib` and there is no correct link. that's why?

**Comment by jzakrzewski** [comment]
This looks like a Mac, so I'm out...
In any case, as @bagder already pointed out: [this is the best place to look for help](https://curl.haxx.se/mail/)

**Comment by oft** [comment]
@jzakrzewski  @bagder thank you.

**Comment by oft** [comment]
need add this option to cmake file

```cmake
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
```
