### ISSUE TITLE
Curl crashes on Raspberry Pi Zero

### ISSUE THREAD

**Issue by thoughtrefraction** [curl/curl#5967]
### I did this
curl --help
### I expected the following
help page
### curl/libcurl version
7.64.0-4+deb10u1
[curl -V output]
Can't run this.
### operating system
Raspbian armv6l GNU/Linux

I get an "Illegal instruction" error

**Comment by dfandrich** [comment]
The curl project doesn't supply binaries (except on Windows and Docker) so
you'll need to bring this problem up with whoever gave you the binaries you're
using. It sounds like they were compiled for an ARM architecture that you're
not running.

**Comment by bagder** [comment]
No response and this doesn't look like our issue at all. We also build and test on ARM continuously.
