### ISSUE TITLE
curl_easy_reset : fix HTTP Retry mechanism 

### ISSUE THREAD

**Issue by FreeYourSoul** [curl/curl#5974]
### I did this

By using the easy interface, I was using the same http connection (and reset it a each use) in order to not waste resources starting connection over and over, working perfectly fine on version 7.70, since version 7.72, it didn't work anymore

### The issue

The issue is comming from the retry mechanism that has been re factorized, the retry is now set in the state data of the connection in 
`conn->state.retrycount. `
But the issue is that this new value introduced is not reset to 0 when calling curl_easy_reset, which makes project using this reset feature not working anymore

### curl/libcurl version

7.72

I attach the fix directly to this issue

**Comment by bagder** [comment]
Forgot the attachment?

**Comment by FreeYourSoul** [comment]
https://github.com/curl/curl/pull/5975
