### ISSUE TITLE
HTTP/1.0 adds a "Host: " header

### ISSUE THREAD

**Issue by drwetter** [curl/curl#5976]
### I did this

``curl -visk -0 https://someurl``

As a sample:

```
myprompt % unset http_proxy
myprompt % curl -visk  --http1.0  http://testssl.sh
[..]
* Connected to testssl.sh (81.169.166.184) port 80 (#0)
> GET / HTTP/1.0
> Host: testssl.sh
> User-Agent: curl/7.64.0
> Accept: */*
[..]
```

### I expected the following

That curl doesn't automatically add a Host-Header. I think that was the case like 2 years back but I am not sure

### curl/libcurl version

```
curl 7.66.0 (x86_64-suse-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d-fips zlib/1.2.11 libidn2/2.2.0 libpsl/0.20.1 (+libidn2/2.2.0) libssh/0.8.7/openssl/zlib nghttp2/1.40.0
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

```
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

```

### operating system

opensuse 15.2, Debian 10, .CentOS 8

### Additional comment

The host header basically spoils a check, OWA divulges otherwise an internal IP address.

(PS: Not that it matters for this check but HTTP/0.9 doesn't work on either Opensuse or Debian, curl automatically sends ``GET / HTTP/1.1``. Dunno whether that was a compile time setting or you kissed good bye to HTTP/0.9. CentOS: ``): option --http0.9: is unknown``)

**Comment by bagder** [comment]
I'm pretty sure curl has sent a `Host:` header for HTTP/1.0 since perhaps before the year 2000, The reason being that while `Host:` wasn't mandatory in that version, lots of 1.0-servers back in the day still needed it so that they could do name based virtual hosting.

You can explicitly disable it with `-H Host:`

**Comment by drwetter** [comment]
Thanks!
