### ISSUE TITLE
libcurl 7.61.1: URL malformed 

### ISSUE THREAD

**Issue by hikmahgumelar** [curl/curl#5982]
### I did this
php artisan list 
this error suddenly and no updates have been made on my source code 
![image](https://user-images.githubusercontent.com/4201453/93666911-36448300-faac-11ea-924f-641b1fe2508e.png)

### I expected the following

![image](https://user-images.githubusercontent.com/4201453/93667158-da7af980-faad-11ea-9b67-0e2deab34b97.png)
and the weird only working with version curl with 7.55.1 and libcurl 7.55.1 
### curl/libcurl version
from curl/libcurl 
I trying using with 7.61 and 7.64 the result is same 
![image](https://user-images.githubusercontent.com/4201453/93666911-36448300-faac-11ea-924f-641b1fe2508e.png)

[curl -V output]
![image](https://user-images.githubusercontent.com/4201453/93667075-4315a680-faad-11ea-9480-498d1de6741c.png)

### operating system
linux amazon

![image](https://user-images.githubusercontent.com/4201453/93667067-31340380-faad-11ea-8b02-985fce2ac8c7.png)

**Comment by jzakrzewski** [comment]
First of all - please copy&paste text instead of screenshots.

It seems that curl does not like the URL it is called with. This may be already fixed - the current version of curl is 7.72. I urge you to try newer version first and if it doesn't work, provide the URL curl is complaining about.

**Comment by bagder** [comment]
I'm witnh @jzakrzewski. All we can see is a program that passes a bad URL to libcurl. That's libcurl working as intended.

**Comment by bagder** [comment]
No error seen and no response after 4 days after initial post. closing.
