### ISSUE TITLE
curl_easy_pause took 88% of runtime

### ISSUE THREAD

**Issue by CHUK-ANDREW** [curl/curl#5988]
We used libCurl for HTTP client. While data receive we call curl_easy_pause multiply times. And this works fine with libCurl 7.50.1.
Recently we decided to update libCurl (to 7.72.0) and got performance slow down.
curl_easy_pause started to use up to 88% of run time. Download speed is really slow.
Please check screenshot (libCurl 7.50.1 on the left and libCurl 7.72.0 on the right side)
![image_2020_09_21T12_00_20_319Z](https://user-images.githubusercontent.com/68962982/93766562-4466e080-fc1f-11ea-8f67-eacad9d012c8.png)

**Comment by bagder** [comment]
We need details to reproduce the issue, watching screenshots doesn't help!

Perhaps you can write up a sample program based on your program's logic that reproduces this problem?

**Comment by CHUK-ANDREW** [comment]
Thank you for reply. Will prepare test to reproduce.

**Comment by bagder** [comment]
Can you try applying #6013 to your build and see if that changes anything?

**Comment by CHUK-ANDREW** [comment]
Will try right now. Some research shows - last correct libCurl for me is 7.68.0, starting 7.69.0 - I got this issue. And issue seams to be only on Linux. Windows works fine with 7.70.0

**Comment by bagder** [comment]
I suspect the fa0216b294af4c commit, which shipped in 7.6.90

**Comment by CHUK-ANDREW** [comment]
https://github.com/curl/curl/pull/6013/commits/0ff5fbb03c4622d7c4045015921971cefde7bc52

Works like a charm! Get speed is back to normal. Thank you for a great work!

**Comment by CHUK-ANDREW** [comment]
https://github.com/curl/curl/pull/6013/commits/d2f9b717b436d3f1290985a1962c4aa77aa9d5f0

but not with this one - issue comes back again

**Comment by bagder** [comment]
don't close the issue until we have the fix landed, and it would be better if you comment the suggested fix in the actual PR...
