### ISSUE TITLE
getting weard errors while compiling

### ISSUE THREAD

**Issue by harshraj21** [curl/curl#5990]
![image](https://user-images.githubusercontent.com/49561994/93787051-a2122180-fc4d-11ea-8800-2006c713478b.png)
I am getting these errors no matter what i try....is this some kind of bug?

I am using curl version -> curl-7.72.0_3-win64-mingw

**Comment by bagder** [comment]
This is not a bug. You seem to not be linking with libcurl at all?

**Comment by harshraj21** [comment]
yea actually i am new....
Edit: i Found a tutorial step by step usefull for any new commers....
https://www.youtube.com/watch?v=q_mXVZ6VJs4
