### ISSUE TITLE
build: tcc throws warning when building with --enable-debug

### ISSUE THREAD

**Issue by emilengler** [curl/curl#6000]
### I did this
```
$ ./configure CC=tcc --enable-debug
$ make
  CC       libcurl_la-altsvc.lo
  CC       libcurl_la-amigaos.lo
  CC       libcurl_la-asyn-ares.lo
  CC       libcurl_la-asyn-thread.lo
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
  CC       libcurl_la-base64.lo
  CC       libcurl_la-conncache.lo
  CC       libcurl_la-connect.lo
  CC       libcurl_la-content_encoding.lo
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
tcc: warning: unsupported option '-fPIC'
...
```

### I expected the following
No warnings

### curl/libcurl version
3d64031fa7a80ac4ae3fd09a5939196268b92f81
tcc version 0.9.27 (x86_64 Linux)

### operating system

Linux debian 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by bagder** [comment]
Your title says `--enable-debug` was used, but your recipe doesn't?

I think `-fPIC` is added there by libtool? I can't see any logic of ours that does it...

**Comment by emilengler** [comment]
> Your title says `--enable-debug` was used, but your recipe doesn't?
> 
> 
> 
> I think `-fPIC` is added there by libtool? I can't see any logic of ours that does it...

I forgot to add that to the description but I am very sure I did it! Changed now. curl compiles fine under tcc without --enable-debug

**Comment by MarcelRaad** [comment]
That's a bug in autotools I actually reported a few years ago: https://debbugs.gnu.org/db/26/26644.html

**Comment by emilengler** [comment]
I think this can be closed then as it's something we cannot handle ourselves
