### ISSUE TITLE
Error: Error in curl::curl_fetch_memory(url, handle = handle): Failed initialization - Ubuntu 14

### ISSUE THREAD

**Issue by musigmaindlabs** [curl/curl#6002]
We are using R - httpcache library and hitting a GET request, tried clearing cache as well using clearCache, however after running for 2000 iterations this error pops up and never goes until I restart the code

**Comment by bagder** [comment]
This sounds like an issue you should file to team making that library as this is not a curl bug you mention. /cc @jeroen

**Comment by jeroen** [comment]
@musigmaindlabs you need to post this in the repo of the R bindings: https://github.com/jeroen/curl

If you want me to have a a look you need to include example code for me to reproduce this problem.

**Comment by bagder** [comment]
Closing this, as it is first a binding problem as described above. (It could still be a curl issue, but then we need to get the curl specifics separated from the binding specifics.)
