### ISSUE TITLE
curl_easy_send makes 16k uploads on windows.  

### ISSUE THREAD

**Issue by vhvb1989** [curl/curl#6009]
### I did this
Created C/C++ application to make PUT to upload 50Mb to a httpps server. (upload operation)
Then, setting Connect only and calling perform to open the connection.
Then, calling  `curl_easy_send` multiple times until all request is upload. Here is where `curl_easy_send` uploads max of 16K per call.
```c
CURL* ref_curl = curl_easy_init();
curl_easy_setopt(ref_curl, CURLOPT_URL, buffer); // buffer with http url
// set headers (host and content-length if not passed in request...

curl_easy_setopt(ref_curl, CURLOPT_CONNECT_ONLY, 1L));
curl_easy_perform(ref_curl); // Connection is open fine :)

// Write request to wire
for (size_t sentBytesTotal = 0; sentBytesTotal < bufferSize;)
  {
    for (CURLcode sendResult = CURLE_AGAIN; sendResult == CURLE_AGAIN;)
    {
      size_t sentBytesPerRequest = 0;
      sendResult = curl_easy_send(
          ref_curl,
          buffer + sentBytesTotal,
          bufferSize - sentBytesTotal,
          &sentBytesPerRequest);

// -> Issue here is that sentBytesPerRequest is always set to MAX `16384` (16K).
// Running same code on Linux/Mac makes 64k upload,

      switch (sendResult)
      {
        // handle CURL_CONTINUE, or timeout.. No problems here...
      }
    };
  }

```

Then I changed the code to work without `curl_easy_send`, and use the callbacks for writing payload, and on this case, I get 64K to write on every callback call:

```c
CURL* ref_curl = curl_easy_init();
curl_easy_setopt(ref_curl, CURLOPT_URL, buffer); // buffer with http url
// set headers (host and content-length if not passed in request...

// Not adding connect only, but setting callback
curl_easy_setopt(ref_curl, CURLOPT_UPLOAD, 1L));
curl_easy_setopt(ref_curl, CURLOPT_READFUNCTION, read_callback);
curl_easy_setopt(ref_curl, CURLOPT_READDATA, &body);
curl_easy_setopt(ref_curl, CURLOPT_INFILESIZE, (curl_off_t)size);

curl_easy_perform(ref_curl); // Connection is open fine :)

// Then, on read_callback
static int32_t read_callback(
    void* dst,
    size_t size,
    size_t nmemb,
    void* userdata)
{
  // Calculate the size of the *dst buffer
  int32_t dst_buffer_size = (int32_t)(nmemb * size);  // I get 64K here!  
..
..
```

### I expected the following
`curl_easy_send` should upload 64k on windows just like libcurl does on Linux and when uploading with read callback.
Uploading 16K at a time makes upload speed to be 1/4 from expected speed.

### curl/libcurl version
7.71
Getting libcurl as dependency with VCPGK and using cmacke project to build
![image](https://user-images.githubusercontent.com/24213737/94197880-43c28a00-fe6b-11ea-9f94-afbb90723422.png)

[curl -V output]

### operating system
Windows 10

**Comment by bagder** [comment]
Is this plain old HTTP (ie not HTTPS) ? I can't see where curl would impose such a limit...

(You really should not do HTTP with `curl_easy_send/recv`. For the protocols curl supports natively, using curl "proper" is a way better way forward the send/recv functions will always be a poor man's substitute.)

**Comment by vhvb1989** [comment]
using curl "proper" (is that the callbacks ? ) is not good for the requirements on the application I have.

Application needs to be able to decide when to read from the server response.  So, as soon as request is sent, one StreamBody object is produced, that stream can be used to pull/read directly from the socket (calling curl_easy_recv).

Using curl_easy_send/recv has been challenging (many details to be manually covered). 
Up to now, the only missing thing I haven't been able to solve is this performance issue.

I saw this `CURL_MAX_WRITE_SIZE` constant and wonder is might be related, 
https://github.com/curl/curl/blob/master/include/curl/curl.h#L247
However, I would need to manually build and link with this updated to see if it is related.

**Comment by bagder** [comment]
Yes, I mean the regular libcurl APIs that do the protocols for you (the easy and the multi interfaces). Using `curl_easy_send` to do one of the protocols curl speaks means that the application re-implements everything curl already can do itself (probably even in a better and more reliable way). If you need "to be able to decide when to read from the server response" I would recommend using the multi interface.

You didn't answer what protocol you are using. It is relevant. If HTTPS, what TLS backend does your build use? If you do use HTTPS, one experiment could be to try using another TLS backend.

> I saw this `CURL_MAX_WRITE_SIZE` constant and wonder if it might be related,

Possibly. But that has the same value when you use the "normal" transfer API and then you don't see this, so it seems a little more puzzling than this. Not to mention that most code is the same on Windows as on Linux and you mention this behavior doesn't exist on Linux.

**Comment by vhvb1989** [comment]
sorry, yes, I am using HTTPS, 
default on windows is winssl.

Looking at schannel code, I found
https://github.com/curl/curl/blob/master/lib/vtls/schannel.c#L1622

however, I would like to understand how using the regular libcurl performs faster (with the sane winssl backend)

**Comment by vhvb1989** [comment]
It looks like every time we write to socket, we need to cakk this win_update_buffer_size. 

```c
#if defined(WIN32) && !defined(USE_LWIPSOCK)
#ifndef SIO_IDEAL_SEND_BACKLOG_QUERY
#define SIO_IDEAL_SEND_BACKLOG_QUERY 0x4004747B
#endif

static void win_update_buffer_size(curl_socket_t sockfd)
{
  int result;
  ULONG ideal;
  DWORD ideallen;
  result = WSAIoctl(sockfd, SIO_IDEAL_SEND_BACKLOG_QUERY, 0, 0,
                    &ideal, sizeof(ideal), &ideallen, 0, 0);
  if(result == 0) {
    setsockopt(sockfd, SOL_SOCKET, SO_SNDBUF,
               (const char *)&ideal, sizeof(ideal));
  }
}
#else
#define win_update_buffer_size(x)
#endif
```

I will try to learn more about this later. For now, patching my code to call this after `curl_easy_send` has fixed the perf issue,

I will close this issue for now.  
Thank you for looking into it 👍

**Comment by bagder** [comment]
That's windows TCP networking in a nutshell... :cry:
