### ISSUE TITLE
HTTP2 RST_STREAM with code 0 is not treated as an aborted stream

### ISSUE THREAD

**Issue by kanongil** [curl/curl#6015]
### I did this

`curl https://a.http2.server/file` where the response starts without a 'content-length' header, and is eventually aborted with a `RST_STREAM` with code 0.

### I expected the following

Something like the http1.1 equivalent response: "transfer closed with outstanding read data remaining".

However, curl ends with succes.

This is almost certainly due to the reported nghttp2 bug here: https://github.com/nghttp2/nghttp2/pull/1508.

### curl/libcurl version

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

### operating system

mac OS 10.15.6

**Comment by bagder** [comment]
Does this still happen with a modern libcurl version?
Anyway we can reproduce this?

**Comment by kanongil** [comment]
I haven't tested, but I strongly believe that this is an open nghttp2 issue. It will directly forward the `RST_STREAM` error code to the `nghttp2_on_stream_close_callback`. So when a server sends it with code `0`, nghttp will [just forward the code to the callback](https://github.com/nghttp2/nghttp2/blob/2e44f23b053dac556d222674d1dccd0341e72280/lib/nghttp2_session.c#L2711-L2716).

My nghttp2 PR only fixes the issue when there is a `content-length` header to compare against.

**Comment by bagder** [comment]
The error code zero is defined (in RFC7540) to not imply an error: **"The associated condition is not a result of an error"**. Should curl really then necessarily treat it as an error?

**Comment by kanongil** [comment]
You are right. This is probably a server bug, and curl has no way to detect it (unless there is a mismatching content-length header).
