### ISSUE TITLE
FTP uploading not reporting CURLE_REMOTE_DISK_FULL

### ISSUE THREAD

**Issue by duncanwilcox** [curl/curl#6016]
### I did this
I used libcurl to upload a file to an FTP server, unfortunately I don't know what server it is. The server had exhausted the disk quota and after the STOR command the server returned a 552 error, which is appears to have been standardizes as meaning "disk full". Searching for "ftp 552" suggests it is widely supported.

Another FTP client (Transmit) reports the following:
2: Cmd: STOR test.mp4
2: 150: Opening BINARY mode data connection for test.mp4
2: Lost data connection to remote host after 458752 bytes had been sent: Broken pipe.
2: 552: Transfer aborted. Disk quota exceeded
2:       STOR: notice: quota reached: used 245791.84 of 245760.00 upload Kb
2:      STOR: notice: quota reached: 'test.mp4' removed

I thought this error might have been an interpretation on the client side so I used wireshark and actually saw the server responding 552:

Response: 552 STOR: notice: quota reached: 'test.mp4' removed

### I expected the following
I expected libcurl to return CURLE_REMOTE_DISK_FULL, instead libcurl reports CURLE_PARTIAL_FILE, which is not incorrect but is less specific, particularly when it comes to offering actionable information to the user.

### curl/libcurl version

We build libcurl ourselves, 7.72.0

### operating system

macOS 10.15.6

**Comment by bagder** [comment]
So, #6017 is pretty much what you would expect then?

**Comment by duncanwilcox** [comment]
Wow didn't expect this so soon. Yes that looks great!
