### ISSUE TITLE
Unable to enable HTTP3 in curl using open SSL patch

### ISSUE THREAD

**Issue by SuneethaYamani** [curl/curl#6019]
make[1]: Entering directory '/home/suneetha/openssl'
make[1]: Leaving directory '/home/suneetha/openssl'
make[1]: Entering directory '/home/suneetha/openssl'
make[1]: Nothing to be done for '_build_engines'.
make[1]: Leaving directory '/home/suneetha/openssl'
*** Installing engines
install engines/afalg.so -> /usr/local/lib/engines-1.1/afalg.so
install engines/capi.so -> /usr/local/lib/engines-1.1/capi.so
install engines/padlock.so -> /usr/local/lib/engines-1.1/padlock.so
make depend && make _build_programs
make[1]: Entering directory '/home/suneetha/openssl'
make[1]: Leaving directory '/home/suneetha/openssl'
make[1]: Entering directory '/home/suneetha/openssl'
make[1]: Nothing to be done for '_build_programs'.
make[1]: Leaving directory '/home/suneetha/openssl'
*** Installing runtime programs
install apps/openssl -> /usr/local/bin/openssl
install ./tools/c_rehash -> /usr/local/bin/c_rehash
suneetha@ELW3093:~/openssl$ curl --http3 https://nghttp2.org:8443/
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by SuneethaYamani** [comment]
I fallowed steps given i readme.md  still http 3 not enabled
"% git clone --depth 1 -b OpenSSL_1_1_1g-quic-draft-29 https://github.com/tatsuhiro-t/openssl
 % cd openssl
 % ./config enable-tls1_3 --prefix=<somewhere1>
 % make
 % make install_sw"

**Comment by bagder** [comment]
Sound like you didn't make sure your new build uses your new libcurl and instead uses the old version. `curl -V` would tell.

**Comment by SuneethaYamani** [comment]
curl  -V is giving "suneetha@ELW3093:~/QUIC/openssl1/openssl$ curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets"

**Comment by SuneethaYamani** [comment]
I removed old version curl and done build again "curl -V
-bash: /usr/bin/curl: No such file or directory
suneetha@ELW3093:~/QUIC/test/openssl$ cd build
suneetha@ELW3093:~/QUIC/test/openssl/build$ cd include/
suneetha@ELW3093:~/QUIC/test/openssl/build/include$ ls
openssl
suneetha@ELW3093:~/QUIC/test/openssl/build/include$ cd openssl/
suneetha@ELW3093:~/QUIC/test/openssl/build/include/openssl$ ls
aes.h       buffer.h     crypto.h     ec.h         kdferr.h      opensslconf.h  randerr.h    ssl.h       ui.h
asn1.h      buffererr.h  cryptoerr.h  ecdh.h       lhash.h       opensslv.h     rc2.h        ssl2.h      uierr.h
asn1_mac.h  camellia.h   ct.h         ecdsa.h      md2.h         ossl_typ.h     rc4.h        ssl3.h      whrlpool.h
asn1err.h   cast.h       cterr.h      ecerr.h      md4.h         pem.h          rc5.h        sslerr.h    x509.h
asn1t.h     cmac.h       des.h        engine.h     md5.h         pem2.h         ripemd.h     stack.h     x509_vfy.h
async.h     cms.h        dh.h         engineerr.h  mdc2.h        pemerr.h       rsa.h        store.h     x509err.h
asyncerr.h  cmserr.h     dherr.h      err.h        modes.h       pkcs12.h       rsaerr.h     storeerr.h  x509v3.h
bio.h       comp.h       dsa.h        evp.h        obj_mac.h     pkcs12err.h    safestack.h  symhacks.h  x509v3err.h
bioerr.h    comperr.h    dsaerr.h     evperr.h     objects.h     pkcs7.h        seed.h       tls1.h
blowfish.h  conf.h       dtls1.h      hmac.h       objectserr.h  pkcs7err.h     sha.h        ts.h
bn.h        conf_api.h   e_os2.h      idea.h       ocsp.h        rand.h         srp.h        tserr.h
bnerr.h     conferr.h    ebcdic.h     kdf.h        ocsperr.h     rand_drbg.h    srtp.h       txt_db.h"

**Comment by SuneethaYamani** [comment]
Now how do I run curl from this build?

**Comment by bagder** [comment]
First: build curl and openssl [as documented](https://github.com/curl/curl/blob/master/docs/HTTP3.md)

You may want to use `--prefix=$path` to curl's configure line to select where it goes when you install it.

Finally: when installed, you need to make sure that the binary 'curl' is found in your path and that it finds (the right) libcurl at run-time. That's not a curl specific problem.

**Comment by SuneethaYamani** [comment]
./config enable-tls1_3 --prefix=$PWD/build i tried this ,but i didn't get any exe file in this path




[curl build with open ssl.docx](https://github.com/curl/curl/files/5296933/curl.build.with.open.ssl.docx)

**Comment by bagder** [comment]
what exe did you expect in what path? That's one line out of quite a few, why would that single line generate an exe anywhere? Please follow the whole instruction. It involves building several sub components and then curl itself with those components.

**Comment by SuneethaYamani** [comment]
[curl build with open ssl.docx](https://github.com/curl/curl/files/5297025/curl.build.with.open.ssl.docx)
I followed all the steps ..PFA. after that I am trying to find curl in /build folder to execute curl -V ,but it is not found in that path

**Comment by bagder** [comment]
how is that document telling us anything? It seems to show you building OpenSSL ? It certainly doesn't show all steps from the instruction.

An advice: use a path for `--prefix` that doesn't involve `$PWD` since you need to point to that path in the curl build too, and you then presumably use another working path.

**Comment by SuneethaYamani** [comment]
suneetha@ELW3093:~/HTTP3$ git clone https://github.com/ngtcp2/nghttp3
Cloning into 'nghttp3'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 2139 (delta 100), reused 113 (delta 61), pack-reused 1975
Receiving objects: 100% (2139/2139), 755.51 KiB | 273.00 KiB/s, done.
Resolving deltas: 100% (1579/1579), done.
suneetha@ELW3093:~/HTTP3$ cd nghttp3
suneetha@ELW3093:~/HTTP3/nghttp3$ autoreconf -i
configure.ac:30: installing './compile'
configure.ac:35: installing './config.guess'
configure.ac:35: installing './config.sub'
configure.ac:39: installing './install-sh'
configure.ac:39: installing './missing'
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
lib/Makefile.am:33: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:33:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:33:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:33:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:33:   its definition is in aclocal's search path.
parallel-tests: installing './test-driver'
**autoreconf: automake failed with exit status: 1**

**Comment by bagder** [comment]
You need libtool installed, `sudo apt-get install libtool` on ubuntu/debian.

**Comment by SuneethaYamani** [comment]
suneetha@ELW3093:~/HTTP3/nghttp3$ sudo apt-get install libtool
Reading package lists... Done
Building dependency tree
Reading state information... Done
libtool is already the newest version (2.4.6-14).
The following package was automatically installed and is no longer required:
  libcurl4
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
suneetha@ELW3093:~/HTTP3/nghttp3$ autoreconf -i
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
suneetha@ELW3093:~/HTTP3/nghttp3$ ./configure --prefix=/home/suneetha/HTTP3/build2 --enable-lib-only
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
**./configure: line 12615: syntax error near unexpected token `0.20'
./configure: line 12615: `PKG_PROG_PKG_CONFIG(0.20)'
suneetha@ELW3093:~/HTTP3/nghttp3$ make
make: *** No targets specified and no makefile found.  Stop.**

**Comment by bagder** [comment]
I'm going to stop here. **These are not curl problems**. These are problems to build the dependencies and happen because you don't have the necessary prerequisites installed. Fix those issue first, build the dependencies and then build curl to use those.
