### ISSUE TITLE
unable to test HTTP3 with curl..need doc how to test HTTP3 with curl

### ISSUE THREAD

**Issue by SuneethaYamani** [curl/curl#6027]
~/HTTP3/curl$ curl -V
curl 7.73.0-DEV (x86_64-pc-linux-gnu) libcurl/7.73.0-DEV OpenSSL/1.1.1g ngtcp2/0.1.0-DEV nghttp3/0.1.0-DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets

```
~/HTTP3/curl$ curl --http3 https://www.google.com -v
*   Trying 172.217.27.196:443...
* Connect socket 5 over QUIC to 172.217.27.196:443
* connect to 172.217.27.196 port 443 failed: Resource temporarily unavailable
*   Trying 2404:6800:4007:806::2004:443...
* Immediate connect fail for 2404:6800:4007:806::2004: Invalid argument
* Failed to connect to www.google.com port 443: Resource temporarily unavailable
* Closing connection 0
curl: (7) Failed to connect to www.google.com port 443: Resource temporarily unavailable

```

**Comment by bagder** [comment]
HTTP/3 support is **experimental** and some of the missing things in the implementation right now are listed in [the wiki](https://github.com/curl/curl/wiki/HTTP3). HTTP/3 support in the test suite is one of them.

If you want to test the current HTTP/3 code, that's fine and we encourage that. I don't however think that we need to document how to do that. You're using early development code. If you cannot figure out how to test this I don't think added text to a document will help much.

See also https://bagder.github.io/HTTP3-test/

**Comment by bagder** [comment]
This works for me: `./src/curl --http3 https://nghttp2.org:4433/` 

You need to make sure the test server you try actually support the same QUIC/h3 draft version as the curl version you built does. Right now, I the back ngtcp2 will speak draft **-31** unless you modify source code.
