### ISSUE TITLE
Improper use of Autoconf cache variables in configure macros

### ISSUE THREAD

**Issue by bemoody** [curl/curl#603]
A number of macros used in curl's configure modify the Autoconf cache
variables, such as 'ac_cv_func_gethostbyname'.  This breaks caching,
causing the second run of './configure -C' to fail, or worse, could
potentially cause the second run to succeed while silently breaking
compilation somehow.

The example I ran into is that when cross-compiling for
x86_64-w64-mingw32, the CURL_CHECK_FUNC_GETHOSTBYNAME macro sets
ac_cv_func_gethostbyname="yes".  This is incorrect - the meaning of
"ac_cv_func_gethostbyname=yes" is that the gethostbyname function is
present in the standard C library, which is not true on mingw32 (it is
in the ws2_32 library instead.)

I cannot see why this line is included in curl-functions.m4 - none of
the curl macros actually make reference to $ac_cv_func_gethostbyname;
the *only* effect of setting that variable is to screw up Autoconf.
In this case, the effect is that the second run of configure fails at
an unrelated place ("checking for connect in libraries".)

There are many other places in curl-functions.m4, and a few in
curl-confopts.m4, where "ac_cv" variables are checked or modified.  In
general I would say this is a bad idea; Autoconf's variables have a
prefix for a reason.

Autoconf caching is a useful feature, and would be especially useful
in this case because the curl configure script is annoyingly slow when
cross-compiling for Windows.  Please don't break it, or if you must
break it, ensure that it's completely broken so users won't rely on
it.

**Comment by bagder** [comment]
We'll welcome all patches that improve the situation and the project!

**Comment by bagder** [comment]
> the CURL_CHECK_FUNC_GETHOSTBYNAME macro sets
ac_cv_func_gethostbyname="yes". This is incorrect - the meaning of
"ac_cv_func_gethostbyname=yes" is that the gethostbyname function is
present in the standard C library, which is not true on mingw32 (it is
in the ws2_32 library instead.)

That's not right. The configure check is there to detect if there's a gethostbyname() function, period. It doesn't matter if it is in a libc or ws2 library as long as it exists and can be used.

**Comment by bagder** [comment]
Can you please show us an example/use case where this habit screws up caching or the output?

**Comment by bemoody** [comment]
Sure.  On a Debian stable system, using the 'gcc-mingw-w64' package:
```
$ tar xfvz curl-7.46.0.tar.gz
$ cd curl-7.46.0
$ ./configure -C --host=x86_64-w64-mingw32
 [...]
checking whether to provide built-in manual... yes
checking whether to enable generation of C code... yes
checking whether to use libgcc... no
checking if X/Open network library is required... no
checking for gethostbyname... no
checking for gethostbyname in -lnsl... no
checking for gethostbyname in -lsocket... no
checking for gethostbyname in -lwatt... no
checking for gethostbyname with both nsl and socket libs... no
checking for gethostbyname in -lws2_32... yes
checking for strcasecmp... yes
checking for windows.h... (cached) yes
checking for winsock.h... (cached) yes
checking for winsock2.h... (cached) yes
checking for connect in libraries... yes
checking whether time.h and sys/time.h may both be included... yes
 [...]
configure: Configured to build curl/libcurl:

  curl version:     7.46.0
  Host setup:       x86_64-w64-mingw32
  Install prefix:   /usr/local
  Compiler:         x86_64-w64-mingw32-gcc
 [...]
$ ./configure -C --host=x86_64-w64-mingw32
 [...]
checking whether to provide built-in manual... yes
checking whether to enable generation of C code... yes
checking whether to use libgcc... no
checking if X/Open network library is required... no
checking for gethostbyname... (cached) yes
checking for strcasecmp... (cached) yes
checking for windows.h... (cached) yes
checking for winsock.h... (cached) yes
checking for winsock2.h... (cached) yes
checking for connect in libraries... cannot find connect
configure: error: cannot find connect function in libraries.
```
and config.log shows
```
configure:19773: checking for connect in libraries
configure:19800: x86_64-w64-mingw32-gcc -o conftest.exe -O2 -Wno-system-headers   conftest.c   >&5
/tmp/ccn5VnUH.o:conftest.c:(.text.startup+0x12): undefined reference to `__imp_connect'
collect2: ld returned 1 exit status
configure:19800: $? = 1
```
(it's not finding 'connect' because it expected the test for 'gethostbyname' would already have detected that '-lws2_32' was necessary.)
