### ISSUE TITLE
CMake based AppVeyor builds are no longer running tests

### ISSUE THREAD

**Issue by mback2k** [curl/curl#6052]
### I did this
I looked at the AppVeyor builds and saw the quite astonishing short build times for those builds with tests (approx. 10 minutes).

Then I saw this on [many builds](https://ci.appveyor.com/project/curlorg/curl/builds/35612236/job/3893jrrgtg54le20):
```
...
Warning: test3013 not present in tests/data/Makefile.inc
Warning: test3014 not present in tests/data/Makefile.inc
Warning: test3015 not present in tests/data/Makefile.inc
TESTFAIL: No tests were performed
TESTDONE: 1387 tests were considered during 116 seconds
```

Manually going back in time and bisecting the AppVeyor history shows that commit ad6416986755e417c66e2c646d532561b445a5b5 seems to [break the tests](https://ci.appveyor.com/project/curlorg/curl/builds/32811753/job/b928lt9spuw1saw0):
```
TESTDONE: 64 tests out of 64 reported OK: 100%
TESTDONE: 1299 tests were considered during 247 seconds.
TESTINFO: 1235 tests were skipped due to these restraints:
```

Unfortunately that commit points to the wrong PR and I cannot see if it was sufficiently tested before merging.

### I expected the following
Tests to be running like they did [before](https://ci.appveyor.com/project/curlorg/curl/builds/32811295/job/ljwhqe65mw2ao0rn) ad6416986755e417c66e2c646d532561b445a5b5:

```
TESTDONE: 1033 tests out of 1033 reported OK: 100%
TESTDONE: 1317 tests were considered during 707 seconds.
TESTINFO: 284 tests were skipped due to these restraints:
```

cc @bagder @MarcelRaad @Lekensteyn

**Comment by mback2k** [comment]
Lessons learned: maybe we can modify the CI to check for an expected minimum number of successful tests being run.

**Comment by bagder** [comment]
`TESTFAIL: No tests were performed` this in particular should at least be a reason for failure in the CI....

**Comment by bagder** [comment]
#6053 seems to do its job for the appveyor builds...

**Comment by bagder** [comment]
When cmake is used on appveyor, `make test` is not invoked and thus the test servers and tools are not built!?

Was that perhaps done by the default `cmake --build` before?

**Comment by mback2k** [comment]
> Was that perhaps done by the default `cmake --build` before?

Seems like this commit c2ab2494ef375bfc5d621b39badabeb9a0c86f6a before ad6416986755e417c66e2c646d532561b445a5b5 is the root cause for this.

**Comment by bagder** [comment]
It seems `cmake --build . -- testdeps` after the build will build the stuff in tests/.

**Comment by MarcelRaad** [comment]
@bagder 
> When cmake is used on appveyor, make test is not invoked and thus the test servers and tools are not built!?
>
> Was that perhaps done by the default cmake --build before?

That's what the `-DBUILD_TESTING` CMake argument is or was for.

**Comment by bagder** [comment]
Ah right. But that doesn't seem to work (anymore)...

**Comment by bagder** [comment]
I've tried numerous things now but I can't seem to fix this. I need help!

**Comment by mback2k** [comment]
@Lekensteyn @MarcelRaad can you a take a look at this maybe? Also: would #6036 be an option to solve this?

**Comment by MarcelRaad** [comment]
> @Lekensteyn @MarcelRaad can you a take a look at this maybe?

I'm not familiar enough with CMake to help here, sorry.

**Comment by jeroen** [comment]
Perhaps appveyor updated their cmake? https://www.appveyor.com/updates/

**Comment by snikulov** [comment]
I'm not 100% sure but suspect the [following removal](https://github.com/curl/curl/commit/ad6416986755e417c66e2c646d532561b445a5b5#diff-af3b638bc2a3e6c650974192a53c7291L1283) was the root cause. 
So
```
option(BUILD_TESTING "Build tests" "${PERL_FOUND}")
if(NOT PERL_FOUND)
  message(STATUS "Perl not found, testing disabled.")
elseif(BUILD_TESTING)
  include(CTest)  ### will enable_testing()
  add_subdirectory(tests)
endif()
```

**Comment by snikulov** [comment]
After digging changes and logs, looks like it was an intentional change.
It looks like the following command should build dependencies and then run tests ```cmake --build . --target test```.
Unfortunately, I'm unable to test it on Windows right now.

**Comment by snikulov** [comment]
@mback2k Could you please check if it's looking good for you? https://ci.appveyor.com/project/snikulov/curl-ckq2k/build/job/5hn7cqysanf4df0p

**Comment by mback2k** [comment]
@snikulov looks better, but the test flags seem to be missing and I don't get the point of your second commit. TFLAGS should work on Windows.

**Comment by snikulov** [comment]
@mback2k yes, TFAGS should work, but using ${...} is Unix specific. For Windows native shell it should be %...% AFAIK. I'm opposes bash usage, but you can try run CMake from bash. Probably it will work.

**Comment by snikulov** [comment]
And my assumption not working :( Adding %TFLAGS% to the command produce the error: 
```
Building Custom Rule C:/projects/curl-ckq2k/tests/CMakeLists.txt
  Unknown option: %TFLAGS%
```

**Comment by mback2k** [comment]
Okay, it seems like `TFLAGS` as an environment variable for `make` is not currently used in `appveyor.yml`, instead the following arguments are passed directly to `runtests.pl`: `-a -b$(($(echo '%APPVEYOR_API_URL%' | cut -d'/' -f3 | cut -d':' -f2)+1)) -p !flaky %DISABLED_TESTS%`.

You will at least need to find a way to pass the following via `cmake` to `runtests.pl`: `-a -p !flaky %DISABLED_TESTS%`. The parameter `-b` is not important anymore as the tests use dynamic ports anyway.

**Comment by snikulov** [comment]
yeah... still digging :) Added `- cmd: set TFLAGS=%DISABLED_TESTS%` to appveyor.yml try to figure out will it helps

**Comment by snikulov** [comment]
@mback2k Could you please check? https://ci.appveyor.com/project/snikulov/curl-ckq2k
Looks like it works now.
I removed curly from ${TFLAGS} placeholder because seems to me it was incorrectly processed with CMake (was cut off).
Now it works for Win32 as well as on Linux.

**Comment by mback2k** [comment]
@snikulov Looks much better, but I don't yet see the arguments `-a` and `-p` being passed into `runtests.pl`.

**Comment by snikulov** [comment]
@mback2k How can you see this?
See [this](https://github.com/curl/curl/blob/master/tests/CMakeLists.txt#L49). Target test-nonflaky will set those switches.
I execute exactly [this target](https://github.com/curl/curl/pull/6066/files#diff-92ab9a36df5d8e9f7076f2fdec59492d1ac2d9cf27ea046767a7fc4d542ef3dcR299)

**Comment by mback2k** [comment]
@snikulov ah, thank you very much. I missed that and already wondered if that target is CMake specific and how `!flaky` is passed.

**Comment by snikulov** [comment]
@mback2k @bagder BTW, should we also enable tests on Travis CMake builds? After this [change](https://github.com/curl/curl/commit/ad6416986755e417c66e2c646d532561b445a5b5) it's now possible.

**Comment by bagder** [comment]
Yes, we should!

**Comment by snikulov** [comment]
Ok then. Will submit another PR soon.
