### ISSUE TITLE
How to find return code/exit code after sending a mail command 

### ISSUE THREAD

**Issue by jlame646** [curl/curl#6059]
I am sending a mail using the command described in the docs and i want to know the status of the command that is ,Is the mail sent successfully?How can i do that?Below is an example command i am using and the screenshot and i notice that the connect is left intact .How can i close the connection after success.So basically,
I am sending mail to my gmail account from my gmail account and the mail is sent successfully but i want to know the return status of the command so that i can utilize it afterwards.In this case the connection is left intact at the end and i want to know how to find if the mail is sent succefully or not and also how to close this connect left intact.
`curl smtp://mail.example.com --mail-from myself@example.com --mail-rcpt
receiver@example.com --upload-file email.txt`

![Screenshot (5271)](https://user-images.githubusercontent.com/72685443/95673070-260f5780-0bc3-11eb-8664-4a194ecbd14d.png)

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

**Comment by bagder** [comment]
It was taken to the curl-users mailing list: https://curl.haxx.se/mail/archive-2020-10/0015.html
