### ISSUE TITLE
Unguarded reference to AF_INET6 in lib/connect.c

### ISSUE THREAD

**Issue by tgc** [curl/curl#6069]
There is an unguarded use of AF_INET6 in lib/connect.c:
https://github.com/curl/curl/blob/a32687798122fd9d4263caaf3ea844462bd69f50/lib/connect.c#L1337

It prevented curl 7.72.0 from building out of the box on Solaris 2.6 as it has no IPv6 support.
After a quick workaround of replacing AF_INET6 with AF_INET the build completed.

Test results after workaround:
TESTDONE: 1103 tests out of 1106 reported OK: 99%
TESTFAIL: These test cases failed: 1700 1701 1702 
TESTDONE: 1374 tests were considered during 660 seconds.

**Comment by bagder** [comment]
Can you give #6071 a try? I figure it should fix the build and make it work for you again.

**Comment by tgc** [comment]
I've tested the second patch posted by Jay, the one with AF_UNSPEC.
It seems to work fine, the build completes and the testresults are identical.

TESTDONE: 1103 tests out of 1106 reported OK: 99%
TESTFAIL: These test cases failed: 1700 1701 1702 
TESTDONE: 1374 tests were considered during 671 seconds.

**Comment by tgc** [comment]
Result for 7.73.0 + patch:
OK (1375 out of 1375, remaining: 00:00, took 0.050s, duration: 11:20)
TESTDONE: 1130 tests out of 1130 reported OK: 100%
TESTDONE: 1387 tests were considered during 680 seconds.

**Comment by bagder** [comment]
Thanks for verifying! Will merge this now...
