### ISSUE TITLE
Please consider change tagging convention

### ISSUE THREAD

**Issue by kloczek** [curl/curl#6076]
At the moment version git tag is used `curl-<ver_sion>` . 
First of all this repo holds curl so adding in that tag is:
- redundant
- it causes that autogenerated tar balls from  tags like https://github.com/curl/curl/archive/curl-7_73_0.tar.gz have inside base directory 'curl-curl-<ver_sion>' because gitlab and github frontend automagically assemblies that base directory out of repo name and git tag.

Second part problematic part is using underscores in accrual version. None of the packaging systems allows use underscores in version string, and second it is kind of duality that just released 7.73.0 version is tagged as 7_73_0.

Please use as git tag string just version with dots.

Autogenerated tar balls are important on packaging when actual dist tree needs to be patched using already committed into the repo patches. using prefix and underscores makes that packaging process, a bit more complicated.

If already tagging convention is used by some other components please at least consider add **secondary** tag which will be just version with dots.
Using tagging convention which is using just version with dots allow easier detect that new version just has been tagged.

I hope you will understood above and try to follow standards already used by more than +95% of all git based projects (yes curl is not only project which is using tag strings as versions 😊)
Feel free to close that ticket after reading.

Regards

**Comment by bagder** [comment]
> First of all this repo holds curl so adding in that tag is: redundant

It isn't redundant. We can and do also tag other things. Like tiny-curl and whatever else we come up with that we want to tag.

> it causes that autogenerated tar balls from tags ...

There should be virtually *zero* reasons for anyone to download github-generated tarballs of the curl releases. We provide proper tarballs for all releases: `https://curl.haxx.se/download/curl-[version].tar.gz`, where `[version]` is with dots. Or pick one of the other archive formats if you prefer.

Why do you need to use the ones on github?

> try to follow standards

That's not actually a "standard". A common pattern, sure.

**Comment by kloczek** [comment]
> > First of all this repo holds curl so adding in that tag is: redundant
> 
> It isn't redundant. We can and do also tag other things. Like tiny-curl and whatever else we come up with that we want to tag.

I really don't care about (seems only one time tagged) tinny curl.
What about use just version with dots for curl and whatever other convention for tiny?

> > it causes that autogenerated tar balls from tags ...
> 
> There should be virtually _zero_ reasons for anyone to download github-generated tarballs of the curl releases. We provide proper tarballs for all releases: `https://curl.haxx.se/download/curl-[version].tar.gz`, where `[version]` is with dots. Or pick one of the other archive formats if you prefer.
>
> Why do you need to use the ones on github?

Not all patches is possible sometimes apply on top of dist tar balls and it is necessary to do that against tagged tar ball.

> > try to follow standards
> 
> That's not actually a "standard". A common pattern, sure.

De jure not .. but de facto.
Just peaked on my on spec files library with +2400 spec files amongs which ~940 are with perl modules:
```
[tkloczko@barrel SPECS]$ grep "^Source0:.*/archive/" * |wc -l
966
```

**Comment by kloczek** [comment]
I want only add that I'm trying to change as much as possible my spec files to use tagged /archive/ tar balls because it creates king of good platform to be able instantly/automatically check each new commit against whole distribution.
In recent monts I was able to convince as many maintainers to standarise tagging to create such platform which in future will allow test single commit in single package against whole distribution.
curl for example now is one of tjhe most frequently used libraries.
Try to think about have early warning from such automation that some single commit caused that package XX is no longer building/generates new compile warnigs/test suite of package YY is failing after such curl commit.

**Comment by bagder** [comment]
> I really don't care about

I didn't say you would. I showed you an example of how the tag prefix isn't redundant. You can of course ignore that.

> Not all patches is possible sometimes apply on top of dist tar balls and it is necessary to do that against tagged tar ball.

Now you're talking about source code in general, and not curl right? Can you show us a single patch that could be applied against a tagged curl tarball but not a curl release tarball? If you can, it feels like you have identified a bug somewhere in our process.

To me, it feels like you insist on getting generated tarballs from github, when our official releases are release tarballs hosted on curl.haxx.se.

> What about use just version with dots for curl and whatever other convention for tiny?

Doing that as an additional tag would of course be easy.

The biggest reason against doing that is probably exactly the kind of work you seem to be doing: working with the tagged tarballs from github **as is they were releases** when they are just the source code state at the time of the release. Our actual releases are *generated* into release tarballs. They're also signed - which the tagged ones are not.

Assuming that you get a release by downloading a tagged tarballs is wrong and I don't want to contribute to misleading any more people into that notion.

**Comment by kloczek** [comment]
> The biggest reason against doing that is probably exactly the kind of work you seem to be doing: working with the tagged tarballs from github as is they were releases when they are just the source code state at the time of the release. Our actual releases are generated into release tarballs. They're also signed - which the tagged ones are not.

I can tell you only that with sometimes only minor changes sometimes in git repo like for example in case some python modules which are  taking version string directly from git repo tree (which is easy to fix/obey) in most of the cases it is possible to use tagged tar balls.
In case of project which is usimg ac/am/lt as build framework (like curl) difference between dist tar ball and what is tagged is only on those files generated by "autoreconf -fiv" command.
In my curl spec file becuse you are using buggy libtool I must regenerate ac/am/lt files before execute configiure. In other words .. my whole build procedure is exactly the same in case of using you dist tar ball and github autogenerated tagged tree.

Tags standarisations will allow people like me easier detect that something new has been released.

I want only to tell that tags standarisation will allows people like me way easier to interract with what is git repo and I'm 100% sure that such standarised platform could be used by many other things :)

Checking consistency of the dowloaded tree can be done on another layer.
At the momet most of the distros build pl;atforms are completly cut off from public network and whole input source code signs are verified on the same stage where dedicatd build end consisting from minimal system and what exactly is specified in build dependencies.
Git provides each commit hash. Those hashes on full migration to sha256 could be used automatically as kind of signatures.

I hope that we would be able to meet somewhere in the middle of our boths sides needs :P

**Comment by jzakrzewski** [comment]
> my whole build procedure is exactly the same in case of using you dist tar ball and github autogenerated tagged tree.

So it makes no difference which tarball you use...

I'm against changing the convention in curl repository as there are already many existing scripts (including mine) that do something with those tags. Having inconsistent tag format within one repository is worse than having them "non-standard". 

That being said I'm not objecting to adding additional tag if deemed useful.

**Comment by kloczek** [comment]
> So it makes no difference which tarball you use...

So far in case of curl and reguular build .. yes but that could not be always the case.
Using tagged tar balls will allow other things :)
Using exactly the same version string for tagged and dist tarbals is in this case **crucial detail**.
As I wrote on the begginnig I'm asking **only** to consider change tagging convention :)

**Comment by bagder** [comment]
>>  So it makes no difference which tarball you use...

> So far in case of curl and regular build .. yes but that could not be always the case.

When wouldn't it? And wouldn't that then signal a bug in our release procedure? And if they differ, why would you consider the one on GitHub to be the more correct version? We ship releases and we host them on `curl.haxx.se`. The generated tarballs are not curl releases.

>  Using tagged tar balls will allow other things :)

Please be specific. What else would it allow?

> In case of project which is usimg ac/am/lt as build framework (like curl) difference between dist tar ball and what is tagged is only on those files generated by "autoreconf -fiv" command.

That is certainly not the only difference. It is probably the most important change but it is not the only one. See the `maketgz` script for the details.

>  Using exactly the same version string for tagged and dist tarbals is in this case crucial detail.

I'm sorry but you have not provided arguments or evidence that show this. Your primary/single use case as I understand it is for downloading a release tarball using the version number verbatim in the URL - and we already provide release tarballs with the version number in them, with dots. And using correct directory names within the archives.

> As I wrote on the beginning I'm asking only to consider change tagging convention :)

Yes, but that means doubling the number of tags *and* by implication making them resemble the actual releases even more than today - and we already have a problem with people thinking that generated tarballs on GitHub is the same thing as the actual releases. So this wish comes at a price and I'm not yet seeing the benefits of paying this price.

**Comment by kloczek** [comment]
> When wouldn't it?

When in the same commit you will modify some file which is in repo but that file will be not included in dist tar ball.

> Please be specific. What else would it allow?

For example apply commits (inytentional or not) which will be changing files which are part of the dist tar ball and not.

> I'm sorry but you have not provided arguments or evidence that show this.

Again:  if tag string will be **exactly the same** as version string used in dist tar ball it will allow easier switching between those two type s of input resources (dist and autogenerated by github tagged tar balls).
For not it is not the case.

> Yes, but that means doubling the number of tags and by implication making them resemble the actual releases even more than today - and we already have a problem with people thinking that generated tarballs on GitHub is the same thing as the actual releases

And I have many problems with maintainers which are changing in the same commit files which at the end will land in dist tar ball and files which only satays in git repo.

In most of the cases to bi not sensitive on such commits is switching to tagged tar balls as input/base resource and tweak build procedure to implement even few necessary (pre)steps on building in rpm, dpkg, IPS package.

**Comment by bagder** [comment]
You say that you would use GitHub *in preference* to our release tarballs in case of mistakes - when the reverse is what we say users should do. Our releases are the generated tarballs we sign and host. Not the tagged ones GitHub offers (and building both tarballs from source even make them different and claim different version outputs).

If (when?) there are mistakes in our releases, those mistakes go into the release and they then make the release broken and then we fix the problems with a new subsequent release. Such a mistake would not make the tagged tarball from GitHub to suddenly become a better version of the release. **Because it isn't the release archive**.

If you want to get the curl code as a tarball from another point in time than an actual release, then using GitHub's tarball service makes a lot of sense - but not for downloading curl **releases**.

**Comment by kloczek** [comment]
> You say that you would use GitHub in preference [..]

No. I want to say that it would be good to start using git tag string which will be the same string version which is used for dist tar ball.
Please stop thinking about archive vs diist tar ball.
I've only explained you why usually it is better to use git tagged tar ball instead dist one. I'm not tryit to tell that this the curl case :)

Again: I'm only asking to **consider change tagging convention** ..  please :)

**Comment by bagder** [comment]
I've not found any compelling reason presented to adjust the current tagging policy in curl. Closing.
