### ISSUE TITLE
libCurl 7.73.0 CHKSTRINGS failure on OS400

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#6083]
### I did this
Attempted build of 7.73.0 on IBM i V7R3M0

### I expected the following

Build aborted with;
CZS1607:  Program CHKSTRINGS was created in library QMQMTMP on 10/14/20 at 09:23:48.
STRING_LASTZEROTERMINATED(77) is not expected value(76).…curl_easy_setopt_ccsid() in packages/OS400/ccsidcurl.c may need updating if new strings are provided as input via the curl API.…ERROR: CHKSTRINGS failed!

CURLOPT_SSL_EC_CURVES was added by https://github.com/curl/curl/pull/5892 but not added to ccsidcurl.c in packages/OS400.
EXPECTED_STRING_LASTZEROTERMINATED  in chkstrings.c should now be (STRING_SSL_EC_CURVES + 1)

### curl/libcurl version
libCurl 7.73.0
 
### operating system
IBM i V7R3M0

**Comment by jay** [comment]
Thanks
