### ISSUE TITLE
curl_url query urlencoding ignores + character

### ISSUE THREAD

**Issue by Rattenhirn** [curl/curl#6086]
### I did this
```
{
	Curl_URL* url = curl_url();

	const char* inQuery = "hash=Al2cO3tDkcDZ3EWE5Lh+LX8TPHs=";
	char* outQuery;

	curl_url_set(url, CURLUPART_QUERY, inQuery, CURLU_URLENCODE);
	curl_url_get(url, CURLUPART_QUERY, &outQuery, CURLU_URLDECODE);

	printf("In Query:  %s\n", inQuery);
	printf("Out Query: %s\n", outQuery);

	curl_free(outQuery);
	curl_url_cleanup(url);
}
```
and got:
```
In Query:  hash=Al2cO3tDkcDZ3EWE5Lh+LX8TPHs=
Out Query: hash=Al2cO3tDkcDZ3EWE5Lh LX8TPHs=
```

Note that the + is gone.

### I expected the following
```
In Query:  hash=Al2cO3tDkcDZ3EWE5Lh+LX8TPHs=
Out Query: hash=Al2cO3tDkcDZ3EWE5Lh+LX8TPHs=
```

I debugged into it, and it seems that there is conflict between replacing spaces with pluses, and url encoding those pluses.
Moving the plus encode part in curl_url_set below the url encode part, and removing the exception for pluses in the url encode part will probably fix the issue in this case. However, it make break other things, as this function is very semantically loaded. :)

### curl/libcurl version

Built from curl-7.72.0 tar

### operating system

Windows

**Comment by bagder** [comment]
I could reproduce and #6087 fixes it for me. I also added a test to verify but it would be good if you could try out the fix for your use case!

**Comment by Rattenhirn** [comment]
Fix verified!

**Comment by bagder** [comment]
Excellent, thanks!
