### ISSUE TITLE
"curl: (77) error setting certificate verify locations" error when valid capath is set

### ISSUE THREAD

**Issue by chrispaucar** [curl/curl#6090]
### I did this
I have curl configured to use both CApath and CAfile options. When `ca-certificates.crt` is valid, curl works. For testing, we deleted `ca-certificates.crt`.
### I expected the following
After `ca-certificates.crt` is deleted from the file system, I expect curl to realize it is invalid and use the CApath option. It does not.
```
# curl -Sv https://ipinfo.io
*   Trying 216.239.36.21:443...
* Connected to ipinfo.io (216.239.36.21) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
```
### curl/libcurl version
```
curl 7.72.0 (mipsel-openwrt-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1h
Release-Date: 2020-08-19
Protocols: file ftp ftps http https
Features: HTTPS-proxy IPv6 Largefile SSL
```
### operating system

`Linux mydevice 3.10.14 #33 SMP Thu Oct 15 12:30:14 EDT 2020 mips GNU/Linux`
It is compiled [from OpenWRT](https://github.com/openwrt/openwrt/blob/openwrt-19.07/package/network/utils/curl/)

**Comment by bagder** [comment]
Those two arguments are passed more or less directly to the underlying OpenSSL function ([SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_load_verify_locations.html)), and it then (obviously) returns error for this. I'm reluctant to try to work around that fact. Can't you just as a work-around make sure that the file exists but has no content instead of removing it completely?

**Comment by chrispaucar** [comment]
Hi @bagder Ok so I just tried with an empty file, so the expected behavior should be to fail validation on CAfile and move on to CApath. However I get the same error:
```
$ ll
-rw-r--r--    1 root     root           0 Oct 15 21:24 /etc/ssl/certs/ca-certificates.crt
$ curl -v https://ipinfo.io
*   Trying 216.239.38.21:443...
* Connected to ipinfo.io (216.239.38.21) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
``` 
I  have plenty of certs installed, what could the issue be here? I also see the same behavior on Ubuntu.
```
$ ll /etc/ssl/certs/ | wc -l
257
```

**Comment by chrispaucar** [comment]
I will add that `wget` and `openssl` both detect the invalid CAfile and use the fallback option, as expected. I am just confused on how to use curl in this scenario (where CAfile is bad). I double checked the hashes as well with the openssl c_rehash utility, the hash filenames are correct.

**Comment by bagder** [comment]
I find it interesting that wget doesn't even check the return code and that's why it doesn't care:

https://gitlab.com/gnuwget/wget/-/blob/master/src/openssl.c#L338

**Comment by chrispaucar** [comment]
That is interesting, however when CApath is valid, wget works as intended. When CApath is invalid, wget fails as intended. I just ran both tests with an invalid CAfile to wget.

So I guess the core question is: how is curl designed here? What should my configuration at compile time or run time be? The goal is to provide CAfile and CApath to curl, and if CAfile is invalid, it should use CApath or the SSL library's CA store (which does not work when compiled `--with-ca-fallback`).

**Comment by nu8** [comment]
I had this problem as well. My issue was this file:

~~~
/usr/ssl/certs/ca-bundle.crt
~~~

is by default just an empty file. So even if it exists, youll still get the
error as it doesnt contain any certificates. You can generate them like this:

~~~
p11-kit extract --overwrite --format pem-bundle /usr/ssl/certs/ca-bundle.crt
~~~

@bagder, I think the error message in this case could be better. As I (and I
assume many others) try furiously to set the correct path, when in reality the
path could already be correct, but because the file is empty HTTPS will not
work.

**Comment by bagder** [comment]
The problem is that we don't know why the function fails so its hard to provide a detailed and accurate error message here. But there might be reason to not have this failure be a hard error and instead just show a verbose output about the failed load...

**Comment by DeckerSU** [comment]
I faced exactly with the same error in my own build of libcurl 7.67.0 linked against OpenSSL 1.1.1f built with my own config opts. Every try of making HTTPS connection fails with:
```
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
```
The problem was in `no-stdio` config opt, passed to ./config of OpenSSL, when i removed it error is gone.

Steps to reproduce, if somebody interested:

Using Ubuntu 16.04.7 LTS, launch the following script to build curl with specified version of OpenSSL:
```
#!/bin/bash
curdir=$(pwd)
mkdir -p $curdir/depends
mkdir -p $curdir/res
cd $curdir/depends

version=1.1.1f
wget -qO- http://www.openssl.org/source/openssl-$version.tar.gz | tar xzv
cd openssl-$version
export CFLAGS=-fPIC
sed -i.old "s|\"engines\", \"apps\", \"test\"|\"engines\"|" Configure

./Configure no-shared no-stdio --prefix=${curdir}/res linux-x86_64
make -j1 build_libs libcrypto.pc libssl.pc openssl.pc
make install_sw

cd $curdir/depends
version=7.67.0
wget -qO- https://curl.haxx.se/download/curl-${version}.tar.gz | tar xzv
cd curl-${version}
PKG_CONFIG_LIBDIR="${curdir}/res/lib/pkgconfig" CPPFLAGS="-I${curdir}/res/include" LDFLAGS="-L${curdir}/res/lib" ./configure --prefix=${curdir}/res
make -j$(nproc)
make install
```
Test binary as:
```
./res/curl --verbose https://api.telegram.org
```
You will get something like:
```
*   Trying 149.154.167.220:443...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```
Now remove `no-stdio` config opt from build script and also remove `depends` and `res` folders and re-build.

Result will be:
```
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
...
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
* Connection #0 to host api.telegram.org left intact
```
So, `no-stdio` conf opt of OpenSSL somehow affect on certificate verify locations settings.

**Comment by jay** [comment]
> The problem was in `no-stdio` config opt, passed to ./config of OpenSSL

That's expected behavior, refer to openssl/openssl#7536.

**Comment by bagder** [comment]
I'm still at loss what people here suggest is the correct action if this is a bug. Are you suggesting we should ignore the error from OpenSSL if `SSL_CTX_load_verify_locations()` fails?

**Comment by bagder** [comment]
I think we should let the OpenSSL error code still mean error and return from that, as I think ignoring it risks leading to future much worse problems.

A user can work around this by specifying *working* paths. That's clearly what this function expects.

**Comment by joseluisr0307** [comment]
This error message indicates that curl is not able to establish a secure connection using openssl you can:

first

echo insecure >> ~/.curlrc
git config --global http.sslVerify false
then reinstall openssl and curl

HOMEBREW_CURLRC=1 brew reinstall openssl curl
last

sed -i '/^insecure$/d' ~/.curlrc
git config --global http.sslVerify true


https://stackoverflow.com/questions/45829588/brew-install-fails-curl77-error-setting-certificate-verify

**Comment by bagder** [comment]
Discussion seems to have died off with no real suggestion or good advice on what else we can do. I think curl still behaves the best way it can.

**Comment by serv-inc** [comment]
It makes sense to keep the behavior, the only thing that might be adjusted is the error message. Maybe something like "the given certificates either do not exist or contain errors" instead of or in addition to the current message, as the return code 0 means
> The operation failed because CAfile and CApath are NULL or the processing at one of the locations specified failed. Check the error stack to find out the reason.
