### ISSUE TITLE
7.72.0: content of tarballs on official web site is not consistent with related tag on github

### ISSUE THREAD

**Issue by SpaceIm** [curl/curl#6091]
I didn't make a full diff, but this file https://github.com/curl/curl/blob/curl-7_72_0/CMake/FindZstd.cmake is missing in 7.72.0 tarballs on https://curl.haxx.se (at least in https://curl.haxx.se/download/curl-7.72.0.tar.gz).

**Comment by bagder** [comment]
Fixed in 7.73.0 already since #5836 and commit 7f8863f741
