### ISSUE TITLE
CURLOPT_NOBODY man page:

### ISSUE THREAD

**Issue by basuke** [curl/curl#6097]
In the second sentence of the **Description**:

> For HTTP operations when CURLOPT_NOBODY has been set, unsetting the option (with 0) will make it a GET again - only if the method is still set to be HEAD. The proper way to get back to a GET request is to set CURLOPT_HTTPGET and for other methods, use the POST ur UPLOAD options.

in the very end, POST **or** UPLOAD options.

**Comment by bagder** [comment]
Thanks!
