### ISSUE TITLE
libcurl http(s) download file curl_easy_pause long time curl_easy_perform return CURLE_PARTIAL_FILE

### ISSUE THREAD

**Issue by yayexing** [curl/curl#610]
i'm chinese people,first inito this,english not good.
Please forgive me
i have problm ,i use libcurl (curl-7.46.0) download file by http(s), and i need to pause.
so i use curl_easy_pause by CURLPAUSE_RECV flag,and Wait a few minutes, i call curl_easy_pause by CURLPAUSE_RECV flag. it  will continue to receive a small piece of data and then the curl_easy_perform return CURLE_PARTIAL_FILE.
the file not download completed.
I don't know how to solve, help me please.
thanks.

**Comment by yayexing** [comment]
the other problem,i set below these markers:
CurlCode = curl_easy_setopt(pCurl, CURLOPT_LOW_SPEED_LIMIT, 1L);  
CurlCode = curl_easy_setopt(pCurl, CURLOPT_LOW_SPEED_TIME, 30); 
and after i call curl_easy_pause,wait 30 seconds ,curl_easy_perform return CURLE_OPERATION_TIMEDOUT.
I do not know this is the bug, or the normal design. so Is there anyone who can help me。

**Comment by bagder** [comment]
It is much better if you file one issue for each problem.

The first problem is most likely that something in your setup gives up waiting and closes the connection when you pause the transfer that long. It could be a NAT/firewall or it can be the server. Do you have keepalive enabled ? It could perhaps help keeping the connection alive, but pausing a transfer for any extended period of time will always risk this to happen. The only safe fix for this problem is unfortunately to not keep it paused for that long!

In the second case, what exactly were you expecting to happen? You ask libcurl to stop the transfer if it goes below one 1 byte/30 seconds and then you *force* that situation to occur and you're then surprised it happened?

**Comment by yayexing** [comment]
hi bagder,I'm glad you can reply me so soon. I was the first to use libcurl.
thanksyou.

I'm actually to do a download tool, he can support the pause function, set curlopt low speed time because there may exist suddenly broken network, I think in off network time to withdraw from the download, but I pause time long he will think is the timeout, to suspend my super and real in the download process of network instability timeout is not the same.

I am not very familiar with the libcurl, forgive me to mention the problem is very low.
But there's no doubt that I like libcurl very much..

**Comment by bagder** [comment]
I can see how this is surprising and possibly not what you'd like, but the reverse might also be true. What if you paused for 15 seconds and then resumed and you got no more data for another 15 seconds. Would that count as 30 seconds without data or not?

The best way (and won't force us to add a lot of logic) I can think of to support "30 seconds with 1 byte" and a pause in the middle is to clear the counters on resume, but that will then make the 30 seconds to restart when you resume a transfer.

Then you could spend 28 seconds with no transfer, pause it for another 30 seconds and when you resume, it would still need another 30 seconds to get timed out.

Or how would you suggest it works?

Whichever way we decide to go, we should make sure we document how it works.

**Comment by yayexing** [comment]
thank you  bagder.
You are very enthusiastic, I see you reply to a lot of people's questions, I finally used the similar method with your proposal to solve the.

By the way, http libcurl (s) to download, how to stop it, I am currently using curl_easy_cleanup () to stop the operation is being downloaded.

**Comment by bagder** [comment]
See this FAQ entry **How do I stop an ongoing transfer?**

http://curl.haxx.se/docs/faq.html#How_do_I_stop_an_ongoing_transfe

**Comment by bagder** [comment]
Does this mean this issue is solved for you?

**Comment by cyg1981** [comment]
Refer to this information。
https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html
In the your callback function, set the bytes of data zero.

**Comment by bagder** [comment]
@cyg1981: I'm sorry I don't understand what you're talking about. If you know of an existing problem, please file a new issue. If you have a comment/question, please take that to the curl-library mailing list.
