### ISSUE TITLE
Where can I find a version of OpenSSL that supports ECH?

### ISSUE THREAD

**Issue by geoff-nixon** [curl/curl#6100]
Or, does this symbol exist? This is the only reference to it on Google. 

https://github.com/curl/curl/blob/f3b7d72c57ed84189ce6e1ca3426e9681236ddf2/configure.ac#L4902

And, um, doesn't look like its happening tomorrow...  
https://github.com/openssl/openssl/issues/7482#issuecomment-706532742

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

Also, see `docs/ECH.md`

**Comment by egberts** [comment]
https://github.com/sftcd/openssl/commit/f4143b3f6122c8a3997a15dbbde10434524344ca

Now as a `ECH_DRAFT_10_VERSION` compiler flag and `ech_version` global variable.
