### ISSUE TITLE
SFTP download over HTTPS proxy stalls

### ISSUE THREAD

**Issue by bagder** [curl/curl#6113]
### I did this

Download an SFTP file over an HTTPS proxy. It seems to stall:

    curl -x https://127.0.0.1:8843 sftp://127.0.0.1/17M -o /dev/null --proxy-insecure -kv

### I expected the following

Downloading a directory from the same server and proxy setup seems to work!

### curl/libcurl version

Current git master.
~~~
curl 7.73.1-DEV (x86_64-pc-linux-gnu) libcurl/7.73.1-DEV OpenSSL/1.1.1h zlib/1.2.11 brotli/1.0.9 zstd/1.4.5 c-ares/1.16.1 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0_DEV nghttp2/1.41.0-DEV librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd
~~~

### operating system

Linux

**Comment by bagder** [comment]
Clearly the fix in #6021 was not sufficient...

**Comment by 0x447a** [comment]
Did you try using a different proxy?

**Comment by emilengler** [comment]
> Did you try using a different proxy?

I think it's rare that the problem lies in the server

**Comment by bagder** [comment]
I know it isn't about the server, a little simple debugging shows this. And anyone trying this should be able to reproduce fairly easily.
