### ISSUE TITLE
macOS | libcurl.4.dylib is not unloaded from process memory after dlclose

### ISSUE THREAD

**Issue by gabrieltarpian25** [curl/curl#6114]
Hello,
I have the 'libTestlib.dylib' which has Linked Dependency to libcurl.4.dylib (version 7.73.0).
If I call dlopen(libTestlib.dylib), library is loaded successfull and also libcurl.4.dylib is loaded in the process memory.
After dlclose(libTestlib), libcurl.4.dylib is still in the process memory (OS failed to unload it) causing our test library to also still be in the process memory.

If we remove libcurl4.dylib from Linked Dependency, the issue is not reproducing anymore.
Also, if we comment **std::stringstream** from our code, the issue is not reproducing.

It seems there are some issues with std::stringstream and libcurl.4.dylib together. Could you please help on this case and provide a solution on why the libcurl.4 library is still loaded in the process memory after dlclose?

I have attached both xcode projects, 'libTestlib' and 'SampleApp'. Also, the 'Reproduction' folder contains the already builted targets, to reproduce the issue just run
cd "...../Reproduction"
./SampleApp

This how the output should look like (if the issue is reproduced):
$ ./SampleApp

### Before dlopen 

dynamic libraries loaded in the process memory:

### After dlopen 

dynamic libraries loaded in the process memory:
   /Users/gtarpian/Desktop/Tickets/DLCLOSE/Reproduction/libTestlib.dylib

### After dlclose (closed code: 0)

dynamic libraries loaded in the process memory:
   /Users/gtarpian/Desktop/Tickets/DLCLOSE/Reproduction/libTestlib.dylib

P.S.: the SampleApp prints info only for libTestlib.dylib. You can modify it to print for all dylibs.

Many thanks in advance!
[dlclose_issue.zip](https://github.com/curl/curl/files/5421435/dlclose_issue.zip)

**Comment by bagder** [comment]
I'm sorry, but how is it a curl issue if the dl-functions for macOS don't work the way you think they should? Isn't that a system/macOS related issue then?

**Comment by gabrieltarpian25** [comment]
If we remove the libcurl.4.dylib Linked Dependency, the issue is no longer reproducible.
In the meantime, we manage to reproduce it with CoreServices.framework instead of libcurl.4.dylib. 
We now believe is related to Apple rather than libcurl.4.dylib.
We have created a Technical Support Incident to Apple to help us solve this case.

**Comment by bagder** [comment]
Closing, as this is (potentially) a macOS issue but not a curl bug.
