### ISSUE TITLE
Build failure 7.73.0

### ISSUE THREAD

**Issue by graxlop** [curl/curl#6122]
Hello,

I tried building the latest version of curl (7.73.0) and I get a build failure, the previous version (7.72.0) builds fine with the same configure line.

`./configure --prefix=/opt/curl --with-ssl=/opt/openssl --with-ca-bundle=/etc/ssl/certs/cacert.pem --disable-mqtt --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-ipv6 --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-unix-sockets --disable-proxy --without-gnutls --without-nss --without-libssh2 --without-librtmp --without-libidn`

In file included from vtls/openssl.c:55:
vtls/openssl.c: In function ‘ossl_connect_step1’:
vtls/openssl.c:2475:57: error: ‘struct ssl_config_data’ has no member named ‘authtype’; did you mean ‘cert_type’?
   const enum CURL_TLSAUTH ssl_authtype = SSL_SET_OPTION(authtype);
                                                         ^~~~~~~~
vtls/vtls.h:147:43: note: in definition of macro ‘SSL_SET_OPTION’
 #define SSL_SET_OPTION(var) data->set.ssl.var
                                           ^~~
vtls/vtls.h:147:42: error: ‘struct ssl_config_data’ has no member named ‘username’
 #define SSL_SET_OPTION(var) data->set.ssl.var
                                          ^
vtls/openssl.c:2802:33: note: in expansion of macro ‘SSL_SET_OPTION’
     char * const ssl_username = SSL_SET_OPTION(username);
                                 ^~~~~~~~~~~~~~
vtls/vtls.h:147:42: error: ‘struct ssl_config_data’ has no member named ‘password’
 #define SSL_SET_OPTION(var) data->set.ssl.var
                                          ^
vtls/openssl.c:2810:48: note: in expansion of macro ‘SSL_SET_OPTION’
     if(!SSL_CTX_set_srp_password(backend->ctx, SSL_SET_OPTION(password))) {
                                                ^~~~~~~~~~~~~~
make[2]: *** [Makefile:2623: vtls/libcurl_la-openssl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/opt/curl-7.73.0/lib'
make[1]: *** [Makefile:1073: all] Error 2
make[1]: Leaving directory '/opt/curl-7.73.0/lib'
make: *** [Makefile:994: all-recursive] Error 1

**Comment by bagder** [comment]
I believe this is already fixed since #6094

**Comment by bagder** [comment]
No response but likely a

Duplicate of #6094
