### ISSUE TITLE
Allow sending -w style to stderr

### ISSUE THREAD

**Issue by paulehoffman** [curl/curl#613]
-w is quite useful, but not to those of us who use curl without -o or -O (such as for scripting through a higher-level language). It would be nice to have an option that is exactly like -w but sends it to stderr instead. Proposed name: --write-stderr.

**Comment by bagder** [comment]
Thanks for this. Idea added to TODO. Closing this now, hoping someone will take it up.

**Comment by jay** [comment]
@paulehoffman Related discussion in #1106, I proposed a %{flags:stderr} if you have any feedback on that
