### ISSUE TITLE
CURLOPT_DNS_USE_GLOBAL_CACHE man page: Typo in description

### ISSUE THREAD

**Issue by liurui39660** [curl/curl#6131]
In section Description, there says "Do note use!", but since this option has no effect and is considered obsolete, is that sentence actually "Do not use!"?
Link: https://curl.haxx.se/libcurl/c/CURLOPT_DNS_USE_GLOBAL_CACHE.html

**Comment by jay** [comment]
> is that sentence actually "Do not use!"?

Yes, it was a typo. Thanks
