### ISSUE TITLE
curl_multi_poll always returns immediately if the wakeup socket has been disconnected

### ISSUE THREAD

**Issue by tomalakgeretkal** [curl/curl#6132]
`curl_multi_poll` delegates to `Curl_multi_wait`, which checks `multi->wakeup_pair[0]` for POLLIN activity then attempts to read from it.

Unfortunately, waking an iPad breaks the wakeup socket pair, triggering a `POLLIN` event and resulting in `SOCKERRNO` being set to `ENOTCONN` in `Curl_multi_wait`'s final `#ifdef ENABLE_WAKEUP` block.

This condition, and other possible error conditions on the wakeup socket, are not handled, so the condition remains on the FD and `curl_multi_poll` will never block again.

Even if the iOS wake scenario is to be considered an edge case, it seems to me we'd be best off looking for and handling any wakeup socket errors anyway.

**Comment by TXTT2016** [comment]
This problem reappear when iphone's OS version update to 16.x.
@rcombs

**Comment by TXTT2016** [comment]
> 

My base libcurl version is 7.80.0, and pick your commit to build

**Comment by bagder** [comment]
This issue was fixed in #6132 (07f80f968df365cbfb).

**Comment by TXTT2016** [comment]
> This issue was fixed in #9368 ([07f80f9](https://github.com/curl/curl/commit/07f80f968df365cbfb5bfcea149baf9eb20cb60f)).

Yes, I picked this commit , and it doesn't raise before, but recently, when iphone OS version update to 16.2, it raised again
