### ISSUE TITLE
Incomplete data received

### ISSUE THREAD

**Issue by lvpinrui** [curl/curl#6136]
//#pragma region Types
struct MemoryStruct 
{
	char *memory;
	size_t size;
};
//#pragma endregion
static size_t WriteMemoryCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
	size_t realsize = size * nmemb;
	struct MemoryStruct *mem = (struct MemoryStruct *)userp;

	//mem->memory = (char *)realloc(mem->memory, mem->size + realsize + 1);
	//if (mem->memory == NULL)
	//{
	//	/* out of memory! */
	//	printf("not enough memory (realloc returned NULL)\n");
	//	return 0;
	//}
	char *ptr = (char*)realloc(mem->memory, mem->size + realsize + 1);
	if (ptr == NULL)
	{
		/* out of memory! */
		printf("not enough memory (realloc returned NULL)\n");
		return 0;
	}

	mem->memory = ptr;
	memcpy(&(mem->memory[mem->size]), contents, realsize);
	cout << "****************LINE400 mem->size:"<< mem->size << endl;
	mem->size += realsize;
	mem->memory[mem->size] = 0;
	return realsize;
}
void Open()
{
	CURL *curl;
	CURLcode res;
	struct MemoryStruct chunk;
	static const char *postthis = "Field=1&Field=2&Field=3";
	chunk.memory = (char*)malloc(1);  //crecerá según sea necesario con el realloc
	chunk.size = 0;    //no hay datos en este punto
	FILE*fd = fopen("202010280909.txt", "w+");
    //inicializacion
	curl_global_init(CURL_GLOBAL_ALL);
	curl = curl_easy_init();
	if (curl)
	{
		/* specify URL to get */
		curl_easy_setopt(curl, CURLOPT_URL, "imap://imap.qq.com/INBOX/;UID=154");
		curl_slist* pHeads = NULL;
		pHeads = curl_slist_append(pHeads, "expect: ");
		curl_easy_setopt(curl, CURLOPT_HEADER, pHeads);
		curl_easy_setopt(curl, CURLOPT_USERNAME, "1358420042@qq.com");
		curl_easy_setopt(curl, CURLOPT_PASSWORD, "khnrhxshtybqjjii");
		curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);
		/* send all data to this function  */
		curl_easy_setopt(curl, CURLOPT_POST, 1);  //设置libcurl发送的协议 

	//	curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L);
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteMemoryCallback);
		/* we pass our 'chunk' struct to the callback function */
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)&chunk);
		/*curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, fwrite);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, fdd);*/
		//curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);
		/* some servers don't like requests that are made without a user-agent
		field, so we provide one */
		curl_easy_setopt(curl, CURLOPT_USERAGENT, "libcurl-agent/1.0");

		//curl_easy_setopt(curl, CURLOPT_POSTFIELDS, postthis);

		///* if we don't provide POSTFIELDSIZE, libcurl will strlen() by
		//itself */
		//curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, (long)strlen(postthis));
		//curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, 100000);

		//curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 1000*60*60*60*1000);
		//curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);       //设置返回的数据量

		//some servers needs this validation
		//curl_easy_setopt(curl, CURLOPT_USERAGENT, "libcurl-agent/1.0");

		res = curl_easy_perform(curl);

		if (res != CURLE_OK)
		{
			fprintf(stderr, "curl_easy_perform() failed: %s\n",
				curl_easy_strerror(res));
		}
		else
		{
			/*
			here is where you can work with the data inside the chunk...
			*/
			cout << "**********LINE412:" << endl;
			printf("%s\n", chunk.memory); //here is the information
			fprintf(fd, "chunk.memory:%s\n", chunk.memory);
			//fclose(fd);
			printf("%lu bytes retrieved\n", (long)chunk.size);
			//string srcData = chunk.memory;
			//cout << "********************LINE473 SRCDATA:"<< srcData << endl;
			parseEmail(chunk.memory);
		}
		/* always cleanup */
		curl_easy_cleanup(curl);
	}
	//se libera la memoria si hay datos
	if (chunk.memory)
		free(chunk.memory);
	fclose(fd);
	curl_global_cleanup();
}

int main(void)
{
	CURL *curl;
	CURLcode res = CURLE_OK;
	string data;
	curl = curl_easy_init();
	if (curl) {
		curl_easy_setopt(curl, CURLOPT_USERNAME, "xxxx@163.com");
		curl_easy_setopt(curl, CURLOPT_PASSWORD, "xxxx");
        curl_easy_setopt(curl, CURLOPT_URL,"imap://imap.163.com/INBOX");
		curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");//The problem is that the data is incomplete after adding this sentence.
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, httpDataWriter);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void*)&data);
                res = curl_easy_perform(curl);
		
		cout << data;

		if (res != CURLE_OK)
			cout << "err:" << curl_easy_strerror(res);
	   }	
		
	    curl_easy_cleanup(curl);
		
	    cin.get();
	return (int)res;
}
`
		
![1](https://user-images.githubusercontent.com/33376859/32442482-932098f8-c336-11e7-99c1-290f2fc7235b.jpg)
Used in the diagram above
“Curl_easy_setopt (curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");”
Printing data is incomplete
![2](https://user-images.githubusercontent.com/33376859/32442560-d71ce0f2-c336-11e7-8060-a02e1f435036.jpg)
Get rid of it in the chart above
“Curl_easy_setopt (curl, CURLOPT_CUSTOMREQUEST, "FETCH 1 BODY[]");”
Print data integrity。

Using the "CURLOPT_CUSTOMREQUEST" program to return data is incomplete. Please fix this problem. Thank you

_Originally posted by @yizhanfinish in https://github.com/curl/curl/issues/2055#issuecomment-342146106_

**Comment by lvpinrui** [comment]
The email attachment exceeds 10k and the read data is incomplete

**Comment by jay** [comment]
You posted your username and password to the list. I have removed them from the post. I suggest changing your password.

**Comment by lvpinrui** [comment]
hello,The password and account have been changed, but The email attachment content exceeds 10k or the reception is incomplete。
Here my account and password are hidden deliberately




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jay Satiro"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 下午2:33
收件人: "curl/curl"<curl@noreply.github.com&gt;; 
抄送: "。"<1358420042@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [curl/curl] Incomplete data received (#6136)





 
You posted your username and password to the list. I have removed them from the post. I suggest changing your password.
