### ISSUE TITLE
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54

### ISSUE THREAD

**Issue by ningkexin** [curl/curl#6142]
### I did this

```
curl -v https://openapi.tianquetech.com/
*   Trying 115.182.200.10:443...
* Connected to openapi.tianquetech.com (115.182.200.10) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /usr/local/etc/openssl@1.1/cert.pem
*  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=CN; ST=\U5317\U4EAC; L=\U5317\U4EAC; O=\U5317\U4EAC\U5929\U9619\U79D1\U6280\U6709\U9650\U516C\U53F8; CN=*.tianquetech.com
*  start date: Jul 11 02:27:57 2019 GMT
*  expire date: Jul 11 02:27:57 2021 GMT
*  subjectAltName: host "openapi.tianquetech.com" matched cert's "*.tianquetech.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: openapi.tianquetech.com
> User-Agent: curl/7.73.0
> Accept: */*
>
* OpenSSL SSL_read: Connection reset by peer, errno 54
* Closing connection 0
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 54
```
### curl/libcurl version

[curl -V output]
```
curl 7.73.0 (x86_64-apple-darwin19.6.0) libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 brotli/1.0.9 zstd/1.4.5 c-ares/1.16.1 libssh2/1.9.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zst
```
### operating system
MAC OS

```
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

openssl add conf stall fail
```
[system_default_sect]
CipherString = @SECLEVEL=1:kEECDH:DHE-RSA:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:!DES:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
MinProtocol = TLSv1
```

**Comment by bagder** [comment]
Why do you think this is a curl issue and not just the server closing the connection?

**Comment by ningkexin** [comment]
@bagder Sorry, maybe I should go to the openssl project to raise this question. The reason is that `Diffie-Hellman(DH)` is turned on for this domain name, and OpenSSL SECLEVEL is too high and it fails

**Comment by bagder** [comment]
I don't think that's the reason. If you have a too high seclevel, the TLS handshake fails (before curl sends its request) and it reports:

    curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small

**Comment by ningkexin** [comment]
@bagder  
Yes, what you said is right. This is the first error I encountered. The domain host has upgraded the SSL certificate and it has been supported. In addition, I’m sorry for the problem caused by the inaccessibility.

**Comment by MichaelBelgium** [comment]
I've got this problem too since long time and there's nowhere a solution online. We moved to a newer dedicated server (probably with a newer SSL and curl version) and this error comes up more frequently than ever. We use GuzzleHttp for HTTP requests towards Microsoft and Canvas LMS. And ~5 times a day this error occurs.

**Comment by jay** [comment]
@MichaelBelgium first use the latest curl. Next you'd have to check in wireshark or debug it some other way to see if the server is responsible for closing the connection. If it is not then give us a way to reproduce in C. Usually when users report errors like this or syscall it is because the server closed the connection unexpectedly and is not a bug in curl. If you think it is actually a bug in curl please open a new issue.

**Comment by MichaelBelgium** [comment]
> @MichaelBelgium first use the latest curl. Next you'd have to check in wireshark or debug it some other way to see if the server is responsible for closing the connection. If it is not then give us a way to reproduce in C. Usually when users report errors like this or syscall it is because the server closed the connection unexpectedly and is not a bug in curl. If you think it is actually a bug in curl please open a new issue.
> 
> Ref: https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/20#issuecomment-705426278

If nobody knows what the cause of that error is, idk what to do. So im checking every option basicly

**Comment by bagder** [comment]
@MichaelBelgium this is probably not a single error, it is just the same result in curl's end. It is the server closing the connection prematurely. I can be one out of many different reasons. Maybe it can even be caused by middlebox equipment?
