### ISSUE TITLE
curl_share_setopt man page: Bug for shared Connection Cache fixed in 7.68.0?

### ISSUE THREAD

**Issue by legion47T** [curl/curl#6143]
In the  section concerning **CURL_LOCK_DATA_CONNECT** a bug is mentioned:

> Note that due to a known bug, it is not safe to share connections this way between multiple concurrent threads. 

As far as I could asses, this refers to #4544 which according to changelog has been fixed in release 7.68.0.

If my assessment is correct and this is the only issue of interest here, one could maybe change above line to something like

> Before version 7.68.0 a bug existed, which made it unsafe to share connections this way between multiple concurrent threads. (`https://github.com/curl/curl/issues/4544`)

Also a meta-bug:
When opening this issue via the "File a new issue" link (`https://github.com/curl/curl/issues/new?title=curl_sahre_setopt%20man%20page:&labels=documentation`) on the site https://curl.haxx.se/libcurl/c/curl_share_setopt.html the automatically generated title had a typo: curl_s**ah**re_setopt...

**Comment by bagder** [comment]
It was believed to be fixed for a while, until #4915 proved that the problem is deeper and need more work for that note to get removed. So no, the problem is indeed very much still present in current curl.

**Comment by legion47T** [comment]
Alright, many thanks for the clarification!
