### ISSUE TITLE
cURL cross compile for arm architecture

### ISSUE THREAD

**Issue by yadav9997** [curl/curl#6152]
Hi,

i am new in using of curl, i am looking for any information regarding on how to cross compile the curl for "arm" architecture. 
can any please help (or) point out to any references.
sorry i couldn't find the one which works for arm compilation of curl.

Thanks a lot in advance.

Thanks,
Krishna

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
