### ISSUE TITLE
Making .pc file relocatable breaks properly configured cross compilation environment.

### ISSUE THREAD

**Issue by asavah** [curl/curl#6157]
### I did this

Tried building (crosscompilation <- important!) another project with libcurl dependency
I have defined the following var in my environment
```
export PKG_CONFIG_SYSROOT_DIR := /home/asavah/kross/build/asusb450eg/rootfs
```
### I expected the following

Clean build without warnings.

### Result 
Warnings that made no sense:
```
cc1: warning: /home/asavah/kross/build/asusb450eg/rootfs/home/asavah/kross/build/asusb450eg/rootfs/usr/lib/pkgconfig/../../include: No such file or directory [-Wmissing-include-dirs]
```
As you can see when PKG_CONFIG_SYSROOT_DIR is set pkg-config is smart enough to prefix it to the final inccludedir/libdir paths.
But it is not smart enough to deal with unintended use of ${pcfiledir} thus resulting in double sysroot prefix first due to SYSROOT_DIR and second due to misuse of ${pcfiledir}.
I have built hundreds of packages and I have hundreds more in /usr/lib/pkgconfig provided by distro.
A simple grep -r reveals that no package uses ${pcfiledir} to provide "relocatability"

Please revert or fix https://github.com/curl/curl/commit/3862c37b6373a55ca704171d45ba5ee91dec2c9f

### curl/libcurl version

[curl -V output]
```
curl 7.73.1-DEV (x86_64-pc-linux-gnu) libcurl/7.73.1-DEV OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libssh2/1.9.0_DEV nghttp2/1.42.0-DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets zstd
```
### operating system
irrelevant

**Comment by bagder** [comment]
cc @RedDwarf69

**Comment by asavah** [comment]
Maybe make it a configure-time switch like --enable-relocatable-pc (disabled by default) so those affected by the issue the aforementioned commit was trying to solve do have a solution which can be applied when needed.

**Comment by RedDwarf69** [comment]
FWIW I have created https://todo.sr.ht/~kaniini/pkgconf/21.

**Comment by bagder** [comment]
I think making into a configure option seems like a reasonable step.

**Comment by RedDwarf69** [comment]
FWIW I want to see what the pkgconf does before working on a patch. But I have noticed that https://github.com/curl/curl/commit/3862c37b6373a55ca704171d45ba5ee91dec2c9f is also breaking the libcurl.pc generation on cmake.
So it may be a good idea to revert it for now, and the configure/cmake option can be added later.
