### ISSUE TITLE
Curl Not Running Correctly From Batch File

### ISSUE THREAD

**Issue by Terrman** [curl/curl#6160]
When I run the following Curl command from the Windows command prompt, the site displays 70° as expected. However, when executed from a batch file, it becomes 70b0.

curl https://customcomplication.mikelyons.org/complicated/set/680fcb69/graphicCircular?value=70%c2%b0

Any ideas why this is?

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

**Comment by bagder** [comment]
Presumably this is due to the charset/encoding of the content and the charset/encoding you use when you view it. This is not a curl bug and therefore we will close this issue soon.
