### ISSUE TITLE
Why did curl disable session ticket when using mbedtls?

### ISSUE THREAD

**Issue by neufeng** [curl/curl#6163]
curl version: 7.72.0
I see in mbedtls.c, about line 452
in method mbed_connect_step1, below code
```
#if defined(MBEDTLS_SSL_SESSION_TICKETS)
  mbedtls_ssl_conf_session_tickets(&backend->config,
                                   MBEDTLS_SSL_SESSION_TICKETS_DISABLED);
#endif
```

Is it a Bug?

**Comment by bagder** [comment]
mbedTLS doesn't support TLS 1.3 so why not stick to session-id for legacy systems? Is it a bug? Does *not* disabling the tickets make any particular change?

(It comes from commit ab08d82648f6deed7e6)

**Comment by mkauf** [comment]
See the explanation in https://github.com/curl/curl/issues/1109#issuecomment-274346447
