### ISSUE TITLE
CMake build in Linux links libcurl to libdl

### ISSUE THREAD

**Issue by RedDwarf69** [curl/curl#6165]
The only use of dlopen seems to be in `packages/vms/report_openssl_version.c`. But in my Linux builds `-ldl` ends up in the CURL_LIBS variable, so:
- libcurl.so links to it
- it's included in the .pc file
- it's in CURL::libcurl's INTERFACE_LINK_LIBRARIES

**Comment by bagder** [comment]
some OpenSSL versions back in the day needed libdl, that's probably why

**Comment by RedDwarf69** [comment]
FWIW I am personally using https://github.com/RedDwarf69/curl/tree/cmake. I'm not creating PRs because I have not tried to make it ready for that (e.g I'm increasing the minimum required cmake version... and I gave no idea how much you want to keep cmake 3.2 support).
I'm solving this with https://github.com/RedDwarf69/curl/commit/92bcf439aee90ffb232b7b95a6337c3b340a9f1c
