### ISSUE TITLE
CURL::libcurl INTERFACE_LINK_LIBRARIES uses -lpthread instead of Threads::Threads

### ISSUE THREAD

**Issue by RedDwarf69** [curl/curl#6166]
Not sure why https://github.com/curl/curl/blob/master/CMakeLists.txt#L289 uses `CMAKE_THREAD_LIBS_INIT` when https://github.com/curl/curl/blob/master/CMakeLists.txt#L394 uses `OpenSSL::SSL OpenSSL::Crypto`.

At the very least this stop the user from getting the THREADS_PREFER_PTHREAD_FLAG usage honoured.

**Comment by RedDwarf69** [comment]
FWIW I am personally using https://github.com/RedDwarf69/curl/tree/cmake. I'm not creating PRs because I have not tried to make it ready for that (e.g I'm increasing the minimum required cmake version... and I gave no idea how much you want to keep cmake 3.2 support).
I'm solving this with https://github.com/RedDwarf69/curl/commit/c5d1ee5e8ff963f9c0051424f8ecd59b8fdc5824

**Comment by snikulov** [comment]
@RedDwarf69 you changes (at least use Threads::Threads) does not require the latest CMake. Imported target Threads::Threads already present since [v3.1](https://cmake.org/cmake/help/v3.1/module/FindThreads.html)
