### ISSUE TITLE
cmake: doesn't fail if zlib support is requested but the zlib library can't be found

### ISSUE THREAD

**Issue by RedDwarf69** [curl/curl#6173]
Running `cmake -DCURL_ZLIB:BOOL=ON` succeeds even if `find_package(ZLIB)` fails.

In general the checks are inconsistent. With `find_package(Brotli QUIET)` (https://github.com/curl/curl/blob/master/CMakeLists.txt#L653) immediately followed by `find_package(Zstd REQUIRED)` (https://github.com/curl/curl/blob/master/CMakeLists.txt#L665).

On autotools you have --with-zlib/--without-zlib and autodetection. If `--with-zlib` is used the configure script fails if the zlib library can't be found.

**Comment by snikulov** [comment]
@bagder should we completely mimic autotools? As I see it was the initial intention (12 years or so 600460ffc61c1b386e8bb5e744046e8e8af45900) not to fail if CURL_ZLIB=ON, but zlib is not found. 
Should we re-work CMakeLists.txt now to match autotools?

**Comment by bagder** [comment]
I don't think we need to "blindly" follow and mimic autotools in cmake (as it certainly has its flaws and peculiarities as well), but the things that are done "right" and that we like we certainly could.

I think when a user asks for enabling a feature, like zlib, we should fail if that can't be done - using any build system. If the user doesn't ask for it, then detecting it automatically and using it or not based on that seems reasonable. Right?

**Comment by jzakrzewski** [comment]
I'm with @bagder . CMake build should probably behave "the CMake way" mimicking autotools where it makes sense.
But in any case in autodetection mode we should be able to decide what to do if dependency is not found (like skip it) but if the user asks for a particular option and it cannot be delivered, that's a hard error.

**Comment by snikulov** [comment]
@jzakrzewski I'm also not arguing. Then we should re-write all CMake build to new rules.

**Comment by bagder** [comment]
It's good enough if we keep fixing things, one by one. Just like we always have!
