### ISSUE TITLE
Segmentation fault on MacOS when ran with -F flag

### ISSUE THREAD

**Issue by RakibFiha** [curl/curl#6174]
I am getting Segmentation fault on MacOS when I executed `curl` command with -F flag.

### I did this

```bash
$ curl -F shorten="www.google.com" https://ttm.sh
Segmentation fault
```

### I expected the following
`some shortened URL of google or whatever URL passed`

### curl/libcurl version

```bash
$ curl -V
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

### operating system

MacOS Catalina 10.15.7 (19H2)

```bash
$ uname -ar
Darwin MacBookPro-4.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by jay** [comment]
Reproduced in 7.64.1 and 7.73.0. "Segmentation fault" is the server's response, it is not from curl. I suggest report it to the site admin. If you add a URL scheme it should work.
