### ISSUE TITLE
time_namelookup is always above 4ms, even though the dns package returned in 1ms

### ISSUE THREAD

**Issue by biello** [curl/curl#6196]
### I did this
curl -o /dev/null -s -w "\ntime_namelookup: "%{time_namelookup}"\ntime_connect: "%{time_connect}"\ntime_appconnect: "%{time_appconnect}"\ntime_pretransfer: "%{time_pretransfer}"\ntime_starttransfer: "%{time_starttransfer}"\ntime_redirect: "%{time_redirect}"\ntime_total: "%{time_total}"\n" www.anyhost.com

time_namelookup: 0.004173
time_connect: 0.008418
time_appconnect: 0.000000
time_pretransfer: 0.008442
time_starttransfer: 0.018434
time_redirect: 0.000000
time_total: 0.018476

strace -tt curl -o /dev/null -s -w "\ntime_namelookup: "%{time_namelookup}"\ntime_connect: "%{time_connect}"\ntime_appconnect: "%{time_appconnect}"\ntime_pretransfer: "%{time_pretransfer}"\ntime_starttransfer: "%{time_starttransfer}"\ntime_redirect: "%{time_redirect}"\ntime_total: "%{time_total}"\n" www.anyhost.com

find it waits here for about 4ms:
![image](https://user-images.githubusercontent.com/11658142/98799223-ccac7980-2449-11eb-9c71-02288f9b8dc7.png)

what happens here?

### I expected the following

time_namelookup should be less then 0.004 

![image](https://user-images.githubusercontent.com/11658142/98797840-12684280-2448-11eb-8356-05baaa6d5574.png)

### curl/libcurl version

curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Linux node-zc6kd 4.19.91-21.al7.x86_64 #1 SMP Wed Sep 2 19:47:49 CST 2020 x86_64 GNU/Linux

**Comment by emilengler** [comment]
Can you try a newer curl version? Your current one is ancient

**Comment by bagder** [comment]
I'm pretty sure this is a problem we've fixed already

**Comment by bagder** [comment]
1. commit 3ef67c6861c9 (7.61.0) fixed the wait times 
2. commit eb9a604f8d7db8 (7.66.0) made the thread wait on a socketpair instead of using polling

If you experience anything similar in a recent curl version, do tell. Until then I consider this a dupe and closed.

**Comment by biello** [comment]
> 1. commit [3ef67c6](https://github.com/curl/curl/commit/3ef67c6861c9d6236a4339d3446a444767598a58) (7.61.0) fixed the wait times
> 2. commit [eb9a604](https://github.com/curl/curl/commit/eb9a604f8d7db859555adc0ddacdabd1ed986106) (7.66.0) made the thread wait on a socketpair instead of using polling
> 
> If you experience anything similar in a recent curl version, do tell. Until then I consider this a dupe and closed.

Thank you, this helps a lot!
