### ISSUE TITLE
Can support for websocket protocol be added?

### ISSUE THREAD

**Issue by dbyoung720** [curl/curl#6202]
Can support for websocket protocol be added?

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

WebSocket support is being [mentioned in the TODO](https://curl.se/docs/todo.html#Upgrade_to_websockets) already as an idea to explore. At least the connect/bootstrap part.

**Comment by dbyoung720** [comment]
OK thank.
