### ISSUE TITLE
libcurl SSL session reuse & connection reuse 

### ISSUE THREAD

**Issue by alenloncaric** [curl/curl#6203]
Hi all,

first off all thank you for all the good work!

I have a shared object that holds SSL session ticket and connection cache for our long poll operation.
Also while our long poll is alive we have some rest calls that are using also the same cache for ssl ticket reuse. The problem is that for this rest calls connections are also added to connection cache. Is there a way to prevent this ?

I don't want to use 2 shared object with 2 ssl tickets. But would be ok with copying ssl ticket from one to another and having the second one without lock connection. Or is there another way?

So having connection that i want to reuse i have some config and some that are one off connections i want to avoid adding them to cache.

With kind regards,
Lonko

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
