### ISSUE TITLE
The ngtcp2 travis CI job fail several tests consistently

### ISSUE THREAD

**Issue by bagder** [curl/curl#6204]
The test failures seem rather consistent now since a while back, but I've failed to reproduce them locally. [example](https://travis-ci.org/github/curl/curl/jobs/743355013).

They only seem to happen in the ngtcp2+nghttp3 build and nowhere else.

The individual tests that fail are:

~~~
TESTFAIL: These test cases failed: 1630 1631 1632 1904 2050 2055

**Comment by jay** [comment]
Those are all http(s)-proxy. Every http(s)-proxy test fails starting at 1630. Probably a networking issue, where the proxy server died and can't be restarted. I don't see anything earlier in the output though, just my guess. For example connection refused when stunnel (ie https-proxy) tries to connect to http-proxy in 1630:
~~~
 2020.11.13 08:36:21 LOG5[0]: Service [curltest] accepted connection from 127.0.0.1:57680
 2020.11.13 08:36:21 LOG3[0]: s_connect: connect 127.0.0.1:44351: Connection refused (111)
 2020.11.13 08:36:21 LOG3[0]: s_connect: connect ::1:44351: Network is unreachable (101)
 2020.11.13 08:36:21 LOG3[0]: No more addresses to connect
~~~
Another weird thing is why are there two https2_stunnel.log shown for that one test. [1](https://travis-ci.org/github/curl/curl/jobs/743355013#L7968), [2](https://travis-ci.org/github/curl/curl/jobs/743355013#L8039)

**Comment by bagder** [comment]
how can there be a networking issue consistently for just this CI job?

**Comment by jay** [comment]
Networking issue as in connection refused which is what all the tests are failing with because the proxy server died (apparently)

**Comment by jay** [comment]
Since we don't know what this is and it can't be reproduced locally I've created PR #6236 so that we can experiment with different ideas. First idea: Enable runtests verbose mode. Feel free to force push or rebase on it once the results are in.

**Comment by bagder** [comment]
They don't fail consistently at all anymore...
