### ISSUE TITLE
Test suite only runs without valgrind on OpenBSD

### ISSUE THREAD

**Issue by emilengler** [curl/curl#6210]
## I did this
```bash
export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16
./buildconf
./configure --enable-debug
make LIBTOOL=/usr/bin/libtool -j4
make LIBTOOL=/usr/bin/libtool test -j4
```

### I expected the following
Test suite should run fine

### curl/libcurl version
24f909cebd8b79abf7b7368b649f5dace1a2449f

### operating system
OpenBSD-current

### Research
When executing `./runtests.pl -n` everything works more or less as expected without an instant failure of every test.

**Comment by emilengler** [comment]
I will have some free time beginning on Wednesday. I will try to fix the problem on my on then.

**Comment by jay** [comment]
Use the -p switch to see the full runtests output. Are you running or did you build with another analyzer? valgrind may not work with some sanitizers like address or undefined.

**Comment by emilengler** [comment]
> Use the -p switch to see the full runtests output. Are you running or did you build with another analyzer? valgrind may not work with some sanitizers like address or undefined.

As far as I know I haven't built it with any analyzer nor sanitizer

**Comment by emilengler** [comment]
> btw you can specify test flags via TFLAGS like so: make test TFLAGS=-n

Possible but this doesn't fix the problem. IMO it should work out just fine out of the box without any additional configuration. Otherwise it should be documented somewhere at least

**Comment by bagder** [comment]
And you have a working valgrind in the path? If so, how come the `checkcmd`in runtests.pl doesn't find it?

**Comment by emilengler** [comment]
> And you have a working valgrind in the path? If so, how come the checkcmd function in runtests.pl doesn't find it?

What do you mean by working valgrind? I indeed have valgrind in my $PATH but valgrind is very experimental on non Linux/macOS systems.

**Comment by bagder** [comment]
The function just checks for an executable with the name 'valgrind' in `$PATH` (and some other dirs) and if found, it will be used.

The question is then why that doesn't work on your setup!?

**Comment by bagder** [comment]
If valgrind doesn't work, then I don't think we can blame curl's test suite for not working with it. Then use `-n` or similar. I don't think that's curl's job to fix.
