### ISSUE TITLE
cmake : change import library name on non Visual Studio platform

### ISSUE THREAD

**Issue by vtorri** [curl/curl#6222]
in lib/CMakeLists.txt, , On Windows, when building shared lib, the suffix is chenged to "_imp.lib"

I propose to change it like that for Visual Studio platform, and to .dll.a otherwise.

this change is motivated by the usage of pkg-config on MSYS2.  Indeed, when 'pkg-config libcurl' is used, -lcurl is passed to ld. The documentation of ld :

https://sourceware.org/binutils/docs/ld/WIN32.html

lists, in the 'direct linking to a dll' section, the pattern of the searched import library, and libcurl_imp.lib is not there.

**Comment by vtorri** [comment]
@MarcelRaad what do you think about such change ? I have a patch for this, if you agree on this change

**Comment by vtorri** [comment]
see PR #6225

**Comment by jzakrzewski** [comment]
#6225  has been merged - closing.
