### ISSUE TITLE
Cannot resolve socks5 hostname with socks5 protocol scheme

### ISSUE THREAD

**Issue by emilengler** [curl/curl#6233]
### I did this
```sh
$ curl -x socks5://127.0.0.1:9050 http://b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
curl: (97) Could not resolve host: b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
$ curl --socks5-hostname 127.0.0.1:9050 http://b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
curl: (97) Could not resolve host: b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
```

### How it works
```
curl --socks5-hostname 127.0.0.1:9050 http://b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
```

### I expected the following
The page is downloaded successfully through tor.

### curl/libcurl version
0d16a49c16a868524a3e51d390b5ea106ce9b51c

### operating system
OpenBSD-current with tor 0.4.3.6

**Comment by emilengler** [comment]
Turns out this isn't a big, just a invalid use of curl. I should have used "socks5h://"

**Comment by dfandrich** [comment]
On Sat, Nov 21, 2020 at 08:44:21AM -0800, Emil Engler wrote:
> $ curl --socks5-hostname 127.0.0.1:9050 http://b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion
> curl: (97) Could not resolve host: b64ig4oeqfjxnr5zt7bbqnmlccrhjsn63antgtitdubfxcvahpwvbjid.onion

I would have expected this one to work, though.

**Comment by jay** [comment]
> I would have expected this one to work, though.

Probably an issue with Tor. I used exactly that command line and tried from master with all resolver backends (synch, threaded, ares) to a local ssocksd instance which was passed the remote resolve every time. I also tried adding doh url (maybe in his curlrc) to see if that was it.
