### ISSUE TITLE
unresolved external symbol Visual Studio 2019 Community Edition, C++

### ISSUE THREAD

**Issue by virusivv** [curl/curl#6246]
Hello Everyone,

I was using the pre-compiled version of CURL it was working fine, but I needed to enable SFTP so I downloaded from this repo, ran the bat file then compiled the CURL using x64 Native Tools Command Prompt for VS 2019 with the command: 
`nmake /f Makefile.vc mode=static MACHINE=x64 WITH_SSL=static SSL_PATH=..\openssl-x64 WITH_SSH2=static SSH2_PATH=..\libssh2-x64
`
the compilation was fine without any errors, I then copied the folders bin, include, lib to my project folder (previously pre-compiled libcurl) and then I get errors for:
curl_global_init
curl_easy_init
curl_easy_setopt
curl_easy_perform
curl_easy_cleanup
curl_global_cleanup
meanwhile running curl.exe works as a charm!

Errors can be seen:
https://i.imgur.com/OHMmFOQ.jpg

### I did this

I tried different combination of compiling the libcur but to no avail

### I expected the following

I was expecting to be able to connect to SFTP with C++ app

### curl/libcurl version

```
curl.exe -V
curl 7.74.0-DEV (x86_64-pc-win32) libcurl/7.74.0-DEV OpenSSL/1.1.1g WinIDN libssh2/1.9.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets alt-svc
```

### operating system

Windows 10 x64

**Comment by bagder** [comment]
Using a static libcurl? Do you define `CURL_STATICLIB` ?

**Comment by virusivv** [comment]
> Using a static libcurl? Do you define `CURL_STATICLIB` ?

Yes, it is already defined in Preprocessor Definitions

**Comment by bagder** [comment]
Since numerous users manage to link with libcurl all the time, this is presumably a mistake in your build setup for your project and not a curl issue. If you can show anything that indicate otherwise, please let us know.
