### ISSUE TITLE
Some tests fail on macOS with c-ares 1.17.1

### ISSUE THREAD

**Issue by mback2k** [curl/curl#6247]
### I did this

See https://github.com/curl/curl/pull/6234/checks?check_run_id=1449769820

Test 506 fails for an (to me) unknown reason, the output order is invalid.
Tests 711 till 715 show a memory issue on macOS if build with c-ares.

### I expected the following

Should be working correctly, or did something change recently?

### curl/libcurl version

current master and PRs

### operating system

macOS CI

**Comment by bagder** [comment]
That doesn't look like a stable nor frequent failure? Most CI rounds seem to do fine for those tests. I just ran those tests locally in c-ares builds on both mac and Linux here, and none of the tests failed even once (on current master).
~~~
./runtests.pl --repeat=21 -R 506 711 712 713 714 715

**Comment by mback2k** [comment]
I am seeing the same issue repeat for CI on master for at least these recent commits:
![image](https://user-images.githubusercontent.com/231943/100321752-7734a880-2fc3-11eb-80b3-e9a0f5faae18.png)

Maybe it is related to the c-ares version used in the CI?

**Comment by mback2k** [comment]
It actually looks like 37cdc2a05c964a7212848149725e8072741f4213 introduced the CI failure.

**Comment by bagder** [comment]
I'll dig deeper.

**Comment by bagder** [comment]
I upgraded my mac's c-ares from 1.16.1 to 1.17.1 and test 506 started to fail. Works fine with 1.17.1 on Linux...
