### ISSUE TITLE
Python 2 support for tests

### ISSUE THREAD

**Issue by jay** [curl/curl#6259]
### I did this

make test from master in Ubuntu 16. 

~~~
== Contents of files in the log/ dir after test 1452
Traceback (most recent call last):
  File "./negtelnetserver.py", line 358, in <module>
    setup_logging(options)
  File "./negtelnetserver.py", line 320, in setup_logging
    handler = ClosingFileHandler(options.logfile)
  File "/home/owner/curl/tests/util.py", line 41, in __init__
    self.setStream(None)
AttributeError: 'ClosingFileHandler' object has no attribute 'setStream'
~~~

This is a problem since #6206 landed. The error is from attempting to start the server and because it can't start the server I guess it doesn't count those tests. This error appears to be because Python 2 doesn't have setStream in [StreamHandler](https://docs.python.org/2/library/logging.handlers.html#streamhandler).

Tests don't fail because of this, instead the server fails silently and it appears those tests don't run.

[Also a problem in the CI.](https://travis-ci.org/github/curl/curl/jobs/745287390#L8856)

We've had other issues with Python 2 , I think there was a problem with the SMB server as well. I think the larger issue is should Python 2 still be supported for tests. I would think if only because I have LTS builds that package it.

### curl/libcurl version

Ubuntu 16 LTS
Python 2.7.12
curl 7.73.1-DEV (x86_64-pc-linux-gnu) libcurl/7.73.1-DEV OpenSSL/1.1.1h zlib/1.2.8 nghttp2/1.41.0 librtmp/2.3

/cc @mback2k

**Comment by emilengler** [comment]
> We've had other issues with Python 2 , I think there was a problem with the SMB server as well. I think the larger issue is should Python 2 still be supported for tests. I would think if only because I have LTS builds that package it.

No, please no more Python 2 support! It reached end of life on January 1st this year and I think we should accept that decision.

**Comment by bagder** [comment]
I'm with @emilengler, I rather think we should work on making python2 fail gracefully. Although if someone wants to work on fixing python 2 stuff I won't stand in the way. It just seems like the wrong thing to put a lot of effort into.

**Comment by mback2k** [comment]
I am with @emilengler and @bagder, but will try to fix it anyway this time.
