### ISSUE TITLE
curl 7.73 built with --enable-debug causes failures

### ISSUE THREAD

**Issue by BrianInglis** [curl/curl#6266]
Cygwin error report [curl release package is a debug build](https://sourceware.org/pipermail/cygwin/2020-November/246916.html)
curl release package being a debug build is causing it to fail on success in some cases e.g.
```
$ curl --cacert mycert.pem https://localhost:80
curl: (56) OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
```
The only thing related to this bug I could find is that msys2 had the same issue in their curl package 
Msys2 error report [Curl is being built in debug mode](https://github.com/msys2/MSYS2-packages/issues/2223)
Curl fails in corner cases where it shouldn't in release, however, it informs the user that it's failure is fatal due to it being a debug build.
A clear and concise description of what the issue is.
```
error: failed retrieving file 'mingw-w64-x86_64-icu-debug-libs-67.1-1-any.pkg.tar.zst' from sourceforge.net : OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)
```
Steps to Reproduce the Problem
Run 'pacman'
Do something 'install a package with a slow or inconsistent internet connection (such as with a mobile device using WIFI hotspot features).'
Describe what happens?
the package installation fails because curl can't recover from the error due to the build not being in release mode.
What did you expect to happen instead?
The bin utilities that ship with MSYS to be compiled in release mode.
```
$ curl -V
curl 7.73.0 (x86_64-pc-cygwin) libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.2.11 brotli/1.0.9 zstd/1.4.5 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.0.4) libssh2/1.7.0 nghttp2/1.37.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli Debug GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SP NEGO SSL TLS-SRP TrackMemory UnixSockets zstd
$ uname -srvmo
CYGWIN_NT-10.0 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
$ win-ver
Windows 10 Home Client Core Multiprocessor Free 6.3 1909 19h1_release 10 0 18363 1139
```
These builds have used --enable-debug for a long time with no reported issues until now.

**Comment by jay** [comment]
> curl: (56) OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)

This isn't a bug unless you can give us a way to reproduce that shows the server did not close the connection abruptly.

**Comment by rinxor** [comment]
I can confirm the server was not sending an SSL close_notify to terminate the connection gracefully because I was not aware of that requirement and only used release curl builds before. I was mistaken by interpreting "errno 0 (Fatal because this is a curl debug build)" as a successful call that only became fatal because it was a debug build. Thank you for the replies.

**Comment by bagder** [comment]
This is the code that is triggered:

https://github.com/curl/curl/blob/0d75bf9ae99f62ac5aab46cd281fd5a7e0760a69/lib/vtls/openssl.c#L4244-L4259

So on purpose, put there to make us aware of the situation and reflect a little... :smile:

**Comment by BrianInglis** [comment]
Thanks very much for the pointer to the explanation. 
I think we will pass along the explanation and rebuild and redeploy with --disable-error as this appears to be breaking downstream workflows.

**Comment by BrianInglis** [comment]
Appears that with --disable-debug, the build does not generate debuginfo files. 
Are there config options that allow generation of debuginfo files without triggering the strict check, or should we use our own local patch to the referenced source?

**Comment by bagder** [comment]
I don't think we have any convenient option for doing that, no. The debug options we have do more than just adding debug symbols.

**Comment by bagder** [comment]
We will continue to keep the freedom to make debug builds do things a normal release build does, to help us improve curl further. I thus cannot consider this to be a bug or an issue. If this thing turn out really annoying, we could of course convert it into just a warning message instead. I personally use the debug build very frequently when toying with curl and I very rarely run into this problem.
