### ISSUE TITLE
Typos in man page

### ISSUE THREAD

**Issue by emanruse** [curl/curl#6273]
This is a documentation "bug".

### I did this
```
man curl
```

In section '--etag-compare':

'OMPARISON: There are 2 types of comparison or ETags, Weak and Strong.  This option expects, and uses a strong comparison.'

should be (add the missing leading 'C' and fix punctuation):

'COMPARISON: There are 2 types of comparison or ETags: Weak and Strong.  This option expects and uses a strong comparison.'

In section '--etag-save':

'A server can send a week ETag'
should be (week->weak)
'A server can send a weak ETag'.

'It an ETag wasn't send by the server or it cannot be parsed, and empty file is created.'
should be (send->sent, and->an)
'If an ETag wasn't sent by the server or it cannot be parsed, an empty file is created.'

### curl/libcurl version

curl 7.73.0 (i586-suse-linux-gnu) libcurl/7.73.0 OpenSSL/1.1.1h-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.41.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

openSUSE Tumbleweed

**Comment by danielgustafsson** [comment]
Fixed, thanks!
