### ISSUE TITLE
curl wont download youtube-dl.exe

### ISSUE THREAD

**Issue by rgiuffre** [curl/curl#6279]
trying to download Windows executable .exe file:

curl -O --verbose https://www.youtube-dl.org/downloads/latest/youtube-dl.exe

Curl downloads only 3 bytes of data.  Tried in Windows 7 Pro 64-Bit and Windows 10 Pro Command Prompt and Powershell, with the same results.

Output:

C:\Users\Downloads> curl -O --verbose https://www.youtube-dl.org/downloads/latest/youtube-dl.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2001:1a50:11:0:5f:8f:acaa:177...
* TCP_NODELAY set
* Connected to www.youtube-dl.org (2001:1a50:11:0:5f:8f:acaa:177) port 443 (#0)
* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 189 bytes...
* schannel: sent initial handshake data: sent 189 bytes
* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 1194
* schannel: encrypted data buffer: offset 1194 length 4096
* schannel: received incomplete message, need more data
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 2/3)
* schannel: encrypted data got 371
* schannel: encrypted data buffer: offset 1565 length 4096
* schannel: sending next handshake data: sending 574 bytes...
* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with www.youtube-dl.org port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /downloads/latest/youtube-dl.exe HTTP/1.1
> Host: www.youtube-dl.org
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 309
* schannel: encrypted data buffer: offset 309 length 103424
* schannel: decrypted data length: 248
* schannel: decrypted data added: 248
* schannel: decrypted data cached: offset 248 length 102400
* schannel: encrypted data length: 32
* schannel: encrypted data cached: offset 32 length 103424
* schannel: decrypted data length: 3
* schannel: decrypted data added: 3
* schannel: decrypted data cached: offset 251 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 251 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 251
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 302 Found
< Date: Sat, 05 Dec 2020 00:34:54 GMT
< Server: Apache/2.2.15 (CentOS)
< Location: https://www.youtube-dl.org/downloads/2020.12.05/youtube-dl.exe
< Content-Length: 3
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
{ [3 bytes data]
100     3  100     3    0     0      3      0  0:00:01 --:--:--  0:00:01     3
* Closing connection 0
* schannel: shutting down SSL/TLS connection with www.youtube-dl.org port 443
* schannel: clear security context handle

**Comment by gvanem** [comment]
Note that the file is found elsewhere:

>     < HTTP/1.1 302 Found
>     < Date: Sat, 05 Dec 2020 00:34:54 GMT
>     < Server: Apache/2.2.15 (CentOS)
>     < Location: https://www.youtube-dl.org/downloads/2020.12.05/youtube-dl.exe

Add the `-L` / `--location` option. But trying myself, there was an issue with my `Auth:`headers.
So this works:
`c:\> curl --no-netrc -OL --verbose https://www.youtube-dl.org/downloads/latest/youtube-dl.exe`
