### ISSUE TITLE
curl duplicates User-Agent header when reading headers from a file

### ISSUE THREAD

**Issue by alexnerd123** [curl/curl#6291]
When saving a flat text file with multiple headers, and one of them is User-Agent, when I call `curl -H "$(cat headerFile)"`, curl passes both my custom User-Agent header, and its built in User-Agent: curl/7.58.0. This doesnt happen if I pass the headers one-by-one as multiple -H arguments. And also doesn't happen if the headers file has just one single header (User-Agent).
```
$ cat testHeaders
x-dummy: foobar
User-Agent: Some-Custom-UA
```
```
$ curl -v -H "$(cat testHeaders)" httpbin.org/get
*   Trying 184.72.216.47...
* TCP_NODELAY set
* Connected to httpbin.org (184.72.216.47) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.58.0================This is curls built in header=============
> Accept: */*
> x-dummy: foobar
> User-Agent: Some-Custom-UA=================This is my custom header==============
>
< HTTP/1.1 200 OK
< Date: Wed, 09 Dec 2020 15:03:44 GMT
< Content-Type: application/json
< Content-Length: 311
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.58.0,Some-Custom-UA",
    "X-Amzn-Trace-Id": "Root=1-5fd0e750-5e5b299378a2ef9168fb12d5",
    "X-Dummy": "foobar"
  },
  "origin": "71.204.0.138, 104.129.205.126",
  "url": "http://httpbin.org/get"
}
* Connection #0 to host httpbin.org left intact
```

This is causing the webserver I'm hitting (which is probably poorly written!) to crash, saying I've specified an invalid header name.
To fix, I can specify `-H "User-Agent:"` after my file, and it seems to "cancel out" and pass just the header I want

```
$ curl -v -H "$(cat testHeaders)" -H "User-Agent:" httpbin.org/get
*   Trying 184.72.216.47...
* TCP_NODELAY set
* Connected to httpbin.org (184.72.216.47) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> Accept: */*
> x-dummy: foobar
> User-Agent: Some-Custom-UA ======= Notice it only passes my custom UA=========
>
< HTTP/1.1 200 OK
```
Passing the headers manually one by one also resolves the issue (but is unwieldy with tons of headers)

```
$ curl -v -H "x-dummy: foobar" -H "User-Agent: Some-Custom-UA" httpbin.org/get
*   Trying 3.211.1.78...
* TCP_NODELAY set
* Connected to httpbin.org (3.211.1.78) port 80 (#0)
> GET /get HTTP/1.1
> Host: httpbin.org
> Accept: */*
> x-dummy: foobar
> User-Agent: Some-Custom-UA
>
```

Having just one single header (User-Agent) in the file also resolves the issue, but defeats the point of using a file to store headers

The docs say

(HTTP)  Extra  header  to  use  when getting a web page. You may specify any number of extra headers. Note that if you should add a custom header that has the same name as one of the internal ones curl would use, your externally set
header will be used instead of the internal one. This allows you to make even trickier stuff than curl would normally do. **You should not replace internally set headers without knowing perfectly well  what  you’re  doing**.  Remove  an
internal header by giving a replacement without content on the right side of the colon, as in: -H "Host:".

Suffice to say i do know what I'm doing 😛 

This was quite a headscratcher....... the "Exact same call" worked in postman, but failed in curl. Took me a while to find that its duplicating the header

**Comment by jzakrzewski** [comment]
Well, curl expects the argument to "-H" to be a header line in format "name: value", so the file content with line breaks will not work.
That is unless you use the build-in @-syntax. Have you tried the documented way to do it:
```curl -v -H @testHeaders httpbin.org/get```
?

**Comment by bagder** [comment]
As @jzakrzewski says, this is a case of "garbage in garbage out". `-H` is documented to take **a single header** or `@filename`. Thus, passing in a single header with CRLF newlines and another header following that to `-H` will make it funny. That's not a bug.

**Comment by alexnerd123** [comment]
Thanks all. At work, our servers all run different versions of curl. We have both 7.58.0, and 7.19.7. And I see (in the updated man page) that @filename syntax was added in 7.55.0. I'll see what I can do to update the curl on our servers.

Cheers!

**Comment by bagder** [comment]
Otherwise you can easily script your way around it.

Put all headers in a text file, one line per header. Then make a script that reads that file and generates the correct command line with one `-H` per line:

~~~shell
#!/bin/sh
while read line; do
  args="$args -H '$line'";
done
curl $args $URL
~~~
Invoke the script like this:

    $ sh script.sh < header_file

(from [an old stackoverflow answer](https://stackoverflow.com/a/12688993/93747) of mine)
