### ISSUE TITLE
Build failed with GnuTLS , nghttp3 and ngtcp2

### ISSUE THREAD

**Issue by icebluey** [curl/curl#6298]
OS: rhel 7
gnutls Version: 3.7.0
curl version: 7.74.0
nghttp3 version: nghttp3-git
ngtcp2 version: ngtcp2-git

`./configure --build=x86_64-linux-gnu --host=x86_64-linux-gnu --with-libz --enable-ipv6 --enable-shared --enable-static --prefix=/usr --libdir=/usr/lib64 --includedir=/usr/include --sysconfdir=/etc --enable-versioned-symbols --with-libssh2 --enable-ares --enable-doh --with-gnutls --without-ssl --with-nghttp3=/home/build/nghttp3/build --with-ngtcp2=/home/build/ngtcp2/build`

configure: Configured to build curl/libcurl:

  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /usr
  Compiler:         x86_64-linux-gnu-gcc
   CFLAGS:          -Werror-implicit-function-declaration -O2 -Wno-system-headers -Wenum-conversion
   CPPFLAGS:        -isystem /usr/include/p11-kit-1 -isystem /home/build/ngtcp2/build/include -isystem /home/build/ngtcp2/build/include -isystem /home/build/nghttp3/build/include
   LDFLAGS:         -L/home/build/ngtcp2/build/lib -L/home/build/ngtcp2/build/lib -L/home/build/nghttp3/build/lib
   LIBS:            -lcares -lnghttp3 -lngtcp2_crypto_gnutls -lngtcp2 -lnghttp2 -lidn2 -lssh2 -lssh2 -lnettle -lgnutls -lldap -llber -lzstd -lbrotlidec -lz

  curl version:     7.74.0
  SSL:              enabled (GnuTLS)
  SSH:              enabled (libSSH2)
  zlib:             enabled
  brotli:           enabled (libbrotlidec)
  zstd:             enabled (libzstd)
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          enabled
  resolver:         c-ares
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              enabled (libidn2)
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   /etc/pki/tls/certs/ca-bundle.crt
  ca cert path:     no
  ca fallback:      no
  LDAP:             enabled (OpenLDAP)
  LDAPS:            enabled
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          enabled
  HTTP2:            enabled (nghttp2)
  HTTP3:            enabled (ngtcp2 + nghttp3)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         AsynchDNS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 NTLM NTLM_WB SSL TLS-SRP UnixSockets alt-svc brotli libz zstd

  WARNING:  HTTP3 enabled but marked EXPERIMENTAL. Use with caution!

`make`
Making all in lib
make[1]: Entering directory '/tmp/curl-7.74.0/lib'
make  all-am
make[2]: Entering directory '/tmp/curl-7.74.0/lib'
  CC       libcurl_la-altsvc.lo
In file included from quic.h:29,
                 from urldata.h:134,
                 from altsvc.c:30:
vquic/ngtcp2.h:65:3: error: unknown type name ‘nghttp3_conn_settings’
   65 |   nghttp3_conn_settings h3settings;
      |   ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1677: libcurl_la-altsvc.lo] Error 1
make[2]: Leaving directory '/tmp/curl-7.74.0/lib'
make[1]: *** [Makefile:1077: all] Error 2
make[1]: Leaving directory '/tmp/curl-7.74.0/lib'
make: *** [Makefile:996: all-recursive] Error 1

**Comment by bagder** [comment]
Fix in master since #6296

**Comment by icebluey** [comment]
It works!
