### ISSUE TITLE
Test 1564 fails: lib1564.c:64 curl_multi_wakeup() failed, with code 9 (Wakeup is unavailable or failed)

### ISSUE THREAD

**Issue by Whissi** [curl/curl#6299]
### I did this
`/usr/bin/perl -I/var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests /var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests/runtests.pl -p 1564`

### I expected the following
Test should pass.

### curl/libcurl version
```
curl 7.74.0 (i686-pc-linux-gnu)
libcurl/7.74.0 (GnuTLS/3.6.15) OpenSSL/1.1.1i zlib/1.2.11 libidn2/2.3.0 nghttp2/1.41.0
```

### operating system
```
$ /usr/bin/perl -I/var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests /var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests/runtests.pl -p 1564
********* System characteristics ********
* curl 7.74.0 (i686-pc-linux-gnu)
* libcurl/7.74.0 (GnuTLS/3.6.15) OpenSSL/1.1.1i zlib/1.2.11 libidn2/2.3.0 nghttp2/1.41.0
* Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL TLS-SRP UnixSockets
* Disabled:
* Host: gentoo-x86
* System: Linux gentoo-x86 5.4.80-gentoo-x86 #1 SMP PREEMPT Wed Nov 25 11:46:01 CET 2020 i686 GNU/Linux
* OS: linux
* Servers: HTTP-IPv6 HTTP-unix FTP-IPv6
* Env: Valgrind
* Seed: 207723
*****************************************
test 1564...[wakeup before poll with no easy handles]

lib1564 returned 123, when expecting 0
 exit FAILED
== Contents of files in the log/ dir after test 1564
=== Start of file commands.log
 ../libtool --mode=execute /usr/bin/valgrind --tool=memcheck --quiet --leak-check=yes --suppressions=/var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests/valgrind.supp --num-callers=16 --log-file=log/valgrind1564 ./libtest/lib1564 - >log/stdout1564 2>log/stderr1564
=== End of file commands.log
=== Start of file ftpserver.cmd
 Testnum 1564
=== End of file ftpserver.cmd
=== Start of file stderr1564
 URL: -
 /var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/tests/libtest/lib1564.c:64 curl_multi_wakeup() failed, with code 9 (Wakeup is unavailable or failed)
=== End of file stderr1564

 - abort tests
TESTDONE: 0 tests out of 1 reported OK: 0%

TESTFAIL: These test cases failed: 1564

TESTDONE: 1 tests were considered during 2 seconds.

```

**Comment by Whissi** [comment]
Looks like a regression, worked in v7.72.0. Is failing since v7.73.0.

**Comment by Whissi** [comment]
Not just failing for x86, also amd64 on Gentoo.

**Comment by bagder** [comment]
I can be noted that this runs fine in the CI jobs very frequently and I've never seen this fail in my local tests. Suggesting there are more to it.

How do you build curl? Which configure options?

**Comment by Whissi** [comment]
Downstream-Bug (with detailed logs): https://bugs.gentoo.org/757342

```/var/tmp/portage/net-misc/curl-7.74.0/work/curl-7.74.0/configure --prefix=/usr --build=i686-pc-linux-gnu --host=i686-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/curl-7.74.0 --htmldir=/usr/share/doc/curl-7.74.0/html --with-sysroot=/ --libdir=/usr/lib --disable-alt-svc --enable-crypto-auth --enable-dict --disable-ech --enable-file --enable-ftp --disable-gopher --disable-hsts --enable-http --enable-imap --disable-ldap --disable-ldaps --disable-mqtt --disable-ntlm-wb --enable-pop3 --enable-rt --enable-rtsp --disable-smb --without-libssh2 --enable-smtp --disable-telnet --enable-tftp --enable-tls-srp --disable-ares --enable-cookies --enable-dateparse --enable-dnsshuffle --enable-doh --disable-get-easy-options --enable-hidden-symbols --enable-http-auth --enable-ipv6 --enable-largefile --enable-manual --enable-mime --enable-netrc --enable-progress-meter --enable-proxy --disable-sspi --disable-socketpair --disable-static --enable-threaded-resolver --enable-pthreads --disable-versioned-symbols --without-amissl --without-bearssl --without-cyassl --without-darwinssl --without-fish-functions-dir --with-libidn2 --with-gssapi=/usr --without-libmetalink --with-nghttp2 --without-libpsl --without-nghttp3 --without-ngtcp2 --without-quiche --without-librtmp --without-brotli --without-schannel --without-secure-transport --without-spnego --without-winidn --without-wolfssl --with-zlib --without-zstd --without-gnutls --without-mbedtls --without-nss --without-polarssl --without-ssl --without-winssl --without-ca-fallback --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt --with-gnutls --with-nettle --with-ssl --with-ca-path=/etc/ssl/certs --with-default-ssl-backend=openssl```

**Comment by bagder** [comment]
`--disable-socketpair`is a pretty good clue I guess. Those tests should probably not run when built like that...

(It seems very odd to build a default libcurl for a distro this way, but I'll ignore that.)

**Comment by Whissi** [comment]
Thank you for this suggestion, I'll forward to our package maintainer.

**Comment by bagder** [comment]
You might want to question `--disable-mqtt` and `--disable-get-easy-options` too while you're at it. Those are enabled by default in curl for a reason. It would be very interesting to learn the rational for why gentoo thinks they're not good to ship?

**Comment by jzakrzewski** [comment]
Looking at the ebuild here: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/curl/curl-7.74.0-r1.ebuild there seem to be few options that cuold be put behind USE flags instead of being arbitrary set. (I'm no expert in ebuilds but I can more or less read simple ones like this)

**Comment by Whissi** [comment]
Package is maintained conservative and it was probably assumed that these option would either pull in additional deps or would enable experimental features. I am gonna enable them soon. Thank you for any suggestions, appreciated!
