### ISSUE TITLE
error 500 when trying Digest Auth it fails even that the request works when done manually 

### ISSUE THREAD

**Issue by minanagehsalalma** [curl/curl#6309]
the command that works 

`curl  "http://123.456.789:12345/ctrlt/DeviceUpgrade_1"  -vv -d @test.xml -H "Content-Type: text/xml;charset=utf-8" --header "Authorization: Digest username=dslf-config, realm=HuaweiHomeGateway, nonce=88645cefb1f9ede0e336e3569d75ee30, uri=/ctrlt/DeviceUpgrade_1, response=3612f843a42db38f48f59d2a3597e19c, algorithm=MD5, qop=auth, nc=00000001, cnonce=248d1a2560100669"
`
the password is admin and the response is generated manually using the steps described here 
[Digest access authentication wiki](https://en.wikipedia.org/wiki/Digest_access_authentication)

this what should work normally

`curl  "http://123.456.789:12345/ctrlt/DeviceUpgrade_1"  -vv -d @test.xml -digest -u dslf-config:admin
`
but it doesn't for some reason , so since that it works manually but doesn't work with the --digest in curl i assume that curl misses something .... i even tried -u username and entered the password when required 

here is the headers i get when i don't use the -digest option 

`HTTP/1.1 401 Unauthorized
WWW-Authenticate: Digest realm="HuaweiHomeGateway",nonce="3c5d8f92f03d9f1afd5dd55a7b172ee8", qop="auth", algorithm="MD5"  
`
**the response error** 

```
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/xml; charset="utf-8"
< Server: Linux UPnP/1.0 Huawei-ATP-IGD
< EXT:
< Connection: Keep-Alive
< Content-Length: 398
<

<s:Envelope
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription></errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
* Connection #0 to host 123.456.789 left intact
```

the version : curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Comment by jay** [comment]
> curl "http://123.456.789:12345/ctrlt/DeviceUpgrade_1" -vv -d @test.xml -digest -u dslf-config:admin

You're missing the double dash in --digest. -digest is the same as writing -d igest which is then appended to your post data. As noted in [the doc](https://curl.se/docs/manpage.html#-d) the default -d content type is application/x-www-form-urlencoded so if you need xml content type then you'll need to pass that header.

**Comment by minanagehsalalma** [comment]
> You're missing the double dash in --digest. -digest is the same as writing -d igest which is then appended to your post data

@bagder  ah, it's a pasting typo here i am using the normal double dash sorry about that.

still the same error when using that content header 

`curl "http://123.456.789:12345/ctrlt/DeviceUpgrade_1" -vv -d @test.xml --digest -u dslf-config:admin --header "Content-Type:application/x-www-form-urlencoded"
`

also this is the content type i am getting when not sending the auth digest 
`< Content-Type: text/xml; charset="utf-8"
`

**Comment by jay** [comment]
> --header "Content-Type:application/x-www-form-urlencoded"

That is the default content type that is already sent. What I am saying is you need to change it to the other one that you used in your example:

> -H "Content-Type: text/xml;charset=utf-8"

**Comment by minanagehsalalma** [comment]
> That is the default content type that is already sent. What I am saying is you need to change it

@jay i though the same, but how ?

**Comment by jay** [comment]
`curl "http://123.456.789:12345/ctrlt/DeviceUpgrade_1" -vv -d @test.xml --digest -u dslf-config:admin -H "Content-Type: text/xml;charset=utf-8"`

**Comment by minanagehsalalma** [comment]
> `curl "http://123.456.789:12345/ctrlt/DeviceUpgrade_1" -v -d @test.xml --digest -u dslf-config:admin -H "Content-Type: text/xml;charset=utf-8"`

@jay  i have tried that since the start and it changed nothing !

**Comment by jay** [comment]
Are you using the version of curl that comes with Windows 10

**Comment by bagder** [comment]
@minanagehsalalma how does the request look like when using that command line and how does it differ from the manual one you made that you originally crafted that works?

**Comment by minanagehsalalma** [comment]
> how does the request look like when using that command line and how does it differ from the manual one you made that you originally crafted that works?

@bagder  you mean a screen shot of wireshark ? in a minute :)

**Comment by bagder** [comment]
`-v` shows the requests, you can just snap them from there.

**Comment by minanagehsalalma** [comment]
> `-v` shows the requests, you can just snap them from there.

it doesn't tell much but okay.

**Comment by minanagehsalalma** [comment]
@bagder  **the one that doesn't work** 

```
curl "http://192.168.1.1:37215/ctrlt/DeviceUpgrade_1" -vv -d @GG.xml  -H "Content-Type: text/xml;charset=utf-8" --digest -u dslf-config:admin

*   Trying 192.168.1.1...
* TCP_NODELAY set
* Connected to 192.168.1.1 (192.168.1.1) port 37215 (#0)
* Server auth using Digest with user 'dslf-config'
> POST /ctrlt/DeviceUpgrade_1 HTTP/1.1
> Host: 192.168.1.1:37215
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: text/xml;charset=utf-8
> Content-Length: 0
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/xml; charset="utf-8"
< Server: Linux UPnP/1.0 Huawei-ATP-IGD
< EXT:
< Connection: Keep-Alive
< Content-Length: 398
<
<s:Envelope
xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
<errorCode>401</errorCode>
<errorDescription></errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>
* Connection #0 to host 192.168.1.1 left intact

```

**the one that works** 

```
curl "http://192.168.1.1:37215/ctrlt/DeviceUpgrade_1" -vv -d @GG.xml  -H "Content-Type: text/xml;charset=utf-8" --header "Authorization: Digest username=dslf-config, realm=HuaweiHomeGateway, nonce=88645cefb1f9ede0e336e3569d75ee30, uri=/ctrlt/DeviceUpgrade_1, response=3612f843a42db38f48f59d2a3597e19c, algorithm=MD5, qop=auth, nc=00000001, cnonce=248d1a2560100669"

*   Trying 192.168.1.1...
* TCP_NODELAY set
* Connected to 192.168.1.1 (192.168.1.1) port 37215 (#0)
> POST /ctrlt/DeviceUpgrade_1 HTTP/1.1
> Host: 192.168.1.1:37215
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: text/xml;charset=utf-8
> Authorization: Digest username=dslf-config, realm=HuaweiHomeGateway, nonce=88645cefb1f9ede0e336e3569d75ee30, uri=/ctrlt/DeviceUpgrade_1, response=3612f843a42db38f48f59d2a3597e19c, algorithm=MD5, qop=auth, nc=00000001, cnonce=248d1a2560100669
> Content-Length: 293
>
* upload completely sent off: 293 out of 293 bytes
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Type: text/xml; charset="utf-8"
< Server: Linux UPnP/1.0 Huawei-ATP-IGD
< Date: Sat, 01 Jan 2000 23:43:39 GMT
< EXT:
< Content-Length: 403
<
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<SOAP-ENV:Body>
<m:GetSoftwareVersionResponse xmlns:m="urn:www-huawei-com:service:DeviceUpgrade:1">
<NewSoftwareVersion>V696969696969696969 ISPNAME</NewSoftwareVersion>
</m:GetSoftwareVersionResponse>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
* Connection #0 to host 192.168.1.1 left intact
```

**Comment by bagder** [comment]
Sure, but a 500 response is the server acting up, it's not necessarily curl fault even. It is an *internal server error* after all.

Digest is an auth method where the client first submits a request, gets a challenge back and *then* issues the full auth headers in a second request based on the challenge. In your case here you see that the server is being silly already on the first request so curl never gets the chance to actually send the auth.

If I were to guess, this is because the server doesn't link the empty post in that first request. But that's just a guess, and also one that isn't too easily to work around with curl.

**Comment by minanagehsalalma** [comment]
> that the server is being silly already on the first request so curl never gets the chance to actually send the auth.

@bagder  what do you mean by that? 

so what is this : 
`* Server auth using Digest with user 'dslf-config'
`
> where the client first submits a request, gets a challenge back

yeah this what happens when i remove the --digest.

> and also one that isn't too easily to work around with curl.

so what now ? is there an alternative , at least? 

the manually generating of the response value is so annoying... also i noticed that there is no need to change the anonce nor the cnonce nor the qop nor the nc values while doing so. (changing them makes no problem too i tested the ones provided by the server not made up ones)

just the uri value and hash and of course the response.

**Comment by bagder** [comment]
I'm blaming the server.

Since curl knows the first request will simply be made to get an auth response back, it makes it with a empty request body to avoid wasting time and bandwidth, but the server doesn't support it and instead falls over. It could also be something else that triggers it, but the point is that the server fails and stops the processing there and then curl can't continue and thus cannot send the second *real* request.

> so what now ? is there an alternative , at least?

Since this isn't a bug in curl, it's tricky. I'm also guessing parts of this and might be wrong. If my guess is correct, then you'd need to patch curl to act differently in order to avoid the server bug.

**Comment by bagder** [comment]
Maybe try `--anyauth` instead of `--digest` ?

**Comment by minanagehsalalma** [comment]
> Since curl knows the first request will simply be made to get an auth response back, it makes it with a empty request body to avoid wasting time and bandwidth, but the server doesn't support it and instead falls over.

@bagder  Yup tested that and you are right 

> Maybe try `--anyauth` instead of `--digest` ?

@bagder lol i can't believe that it worked !! i have started learning about UPNP and TR064 a couple of months ago and when tested this it on my device i fail into this problem and looked the whole web for a fix but couldn't find any until i found out about sending the request manually and now it worked using curl ! 😃

when asked about the auth digest no one suggested or said anything about --anyauth 

so if it works better than --digest and fixes problems like this , why it's there  and not just anyauth ? 

thanks a lot mate :)

**Comment by bagder** [comment]
> so if it works better than --digest and fixes problems like this , why it's there and not just anyauth ?

Because it asks for *any* auth and not just digest and some users actually want to specify exactly what auth method they want curl to use. It just took me a little while to realize that using this switch could actually be a neat way to work around that server issue of yours, as with `--anyauth` curl also takes into account that it might not have any auth at all so it will send the entire request body already in the first request and not do that first empty one I mentioned above.

So again. This wasn't a curl bug but now this case is solved and done anyway! :grin:

**Comment by jay** [comment]
--anyauth is not as efficient as --digest because it sends the content twice. the server should ask for authorization without the content.

**Comment by minanagehsalalma** [comment]
> --anyauth is not as efficient as --digest because it sends the content twice. the server should ask for authorization without the content.

@jay Yup it turned out to be server problem.
