### ISSUE TITLE
winbuild: HTTP header has "Accept: */*" in the place of "Connection: Keep-Alive" after migrating form Winhttp to Curl

### ISSUE THREAD

**Issue by ganeshkamath89** [curl/curl#6326]
We have migrated a project that was using WinHTTP to now use Curl.

In the HTTP headers, when we compare the wireshark TCP flow, we are observing a slight change:

**Header with WinHTTP:**
```
POST /wsman HTTP/1.1
Connection: Keep-Alive
Content-Type: application/soap+xml;charset=UTF-8
User-Agent: Openwsman
Content-Length: 888
Host: 10.138.140.37:623
```

**Header with Curl:**
```
POST /wsman HTTP/1.1
Accept: */*
Content-Type: application/soap+xml;charset=UTF-8
User-Agent: Openwsman
Content-Length: 888
Host: 10.138.140.37:623
```

I have tried adding the following to our existing Curl code to check if it changes, but it is not making any difference.

```
  /* enable TCP keep-alive for this transfer */
  curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);
 
  /* keep-alive idle time to 120 seconds */
  curl_easy_setopt(curl, CURLOPT_TCP_KEEPIDLE, 120L);
 
  /* interval time between keep-alive probes: 60 seconds */
  curl_easy_setopt(curl, CURLOPT_TCP_KEEPINTVL, 60L);
```

Code taken from: https://curl.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

Do I need to change something else to get the **Connection: Keep-Alive** in the HTTP Header?

Setup Info:
1) I am using Libcurl 0.73 from source
2) For TLS backend I am using OpenSSL
3) I am running my application on Window 10 Enterprise and Windows Server 2016

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!

- there's no version "0.73"
- `Connection: Keep-Alive` serves no purpose and curl does not use it. You need to set it yourself if you want it.

**Comment by ganeshkamath89** [comment]
Sorry.
Lib curl version: 7.73.0.

Thank you. I didn't know that **Connection: Keep-Alive** serves no purpose.

**Comment by jay** [comment]
> I didn't know that **Connection: Keep-Alive** serves no purpose.

https://en.wikipedia.org/wiki/HTTP_persistent_connection
