### ISSUE TITLE
mk-ca-bundle.pl: missed "OISTE WISeKey Global Root GA CA" in output

### ISSUE THREAD

**Issue by fijiol** [curl/curl#6329]
Hello!

I've noticed that latest published caccert.pem has not OISTE WISeKey Global Root GA CA certificate:
```
# https://curl.haxx.se/ca/cacert-2020-12-08.pem
 $ curl -L -s http://curl.haxx.se/ca/cacert.pem | grep 'OISTE'
OISTE WISeKey Global Root GB CA
OISTE WISeKey Global Root GC CA
```

In opposite to older one:
```
 $ curl -s https://curl.haxx.se/ca/cacert-2020-07-22.pem | grep 'OISTE'
OISTE WISeKey Global Root GA CA
OISTE WISeKey Global Root GB CA
OISTE WISeKey Global Root GC CA
```

Meanwhile, accordingly https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport the certificate still is valid.

```
 $ curl -s https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt | grep '# Certificate.*OISTE'
# Certificate "OISTE WISeKey Global Root GA CA"
# Certificate "OISTE WISeKey Global Root GB CA"
# Certificate "OISTE WISeKey Global Root GC CA"
```

Local run of mk-ca-bundle.pl script give next result:
```
 $ perl lib/mk-ca-bundle.pl -f -q ; cat ca-bundle.crt | grep OISTE
OISTE WISeKey Global Root GB CA
OISTE WISeKey Global Root GC CA
```

Recently added distrust fields for certificate was not set: 
```
 $ curl -s https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt | sed -n -e '/#\ Certificate.*OISTE.*GA/,/#\ Certificate/ p' | grep 'CKA_NSS_.*_DISTRUST'
CKA_NSS_SERVER_DISTRUST_AFTER CK_BBOOL CK_FALSE
CKA_NSS_EMAIL_DISTRUST_AFTER CK_BBOOL CK_FALSE
```

It seems the certificate need to be included as before.

**Comment by fijiol** [comment]
It seems that mentioned certificate listed by Mozilla for email protection only:
```
 $ curl -s https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt | sed -n -e '/#\ Certificate.*OISTE.*GA/,/#\ Certificate/ p' | grep 'CKA_TRUST_'
CKA_TRUST_SERVER_AUTH CK_TRUST CKT_NSS_MUST_VERIFY_TRUST
CKA_TRUST_EMAIL_PROTECTION CK_TRUST CKT_NSS_TRUSTED_DELEGATOR
CKA_TRUST_CODE_SIGNING CK_TRUST CKT_NSS_MUST_VERIFY_TRUST
CKA_TRUST_STEP_UP_APPROVED CK_BBOOL CK_FALSE
```

and it is the reason why it is not in cacerts.pem

**Comment by bagder** [comment]
then this isn't a bug, is it?

**Comment by fijiol** [comment]
In case if the contract is to publish here [http://curl.haxx.se/ca/cacert.pem] only certificates marked as [ CKA_TRUST_SERVER_AUTH CK_TRUST CKT_NSS_TRUSTED_DELEGATOR ] I think yes it is not an issue anymore. 
(However I personally do not know if there are some email clients/servers that depends on published pem archive)

The only last minor question that probably should be clarified is what has changed since cacert-2020-07-22.pem until cacert-2020-10-04.pem (when certificate disappeared)

As far as I can see there aren't related changes in certdata.txt: https://hg.mozilla.org/mozilla-central/log/tip/security/nss/lib/ckfw/builtins/certdata.txt

and also I do not see changes in mk-ca-bundle script in this time-range:
```
$ git log --since 2020-07-22 --until 2020-10-04 lib/mk-ca-bundle.pl
$
```

**Comment by bagder** [comment]
First: let's focus on the script here and only secondary what is hosted. The script's output is what gets hosted and the script either does what it should or it doesn't.

I don't think it is crystal clear if it should include email-only certs but are you sure that's the case? It seems odd for Firefox to include such certs in the first place.

Maybe the only fix here is to clarify in the docs for mk-ca-bundle.pl that the output CA cert is for authenticating web servers?

**Comment by fijiol** [comment]
> It seems odd for Firefox to include such certs in the first place.
Mozilla's certdata.txt as far as I can see contains for example:
Verisign Class 1 Public Primary Certification Authority - G3
So probably it always contained all certificates approved by Mozilla for all goals.

But please notice that [Verisign Class 1 Public Primary Certification Authority - G3] was never posted on curl.haxx.se/ca/cacert.pem (so usually cacert.pem didn't contain at least some of email-only certificates)

> First: let's focus on the script here and only secondary what is hosted. The script's output is what gets hosted and the script either does what it should or it doesn't.
At the moment I agree -- script is fine (the behavior with cert [OISTE WISeKey Global Root GA CA] should be same as with [Verisign Class 1 Public Primary Certification Authority - G3] and now it matches)

> Maybe the only fix here is to clarify in the docs for mk-ca-bundle.pl that the output CA cert is for authenticating web servers?
I agree, in case if it was ran with no args or with default -p<default> args. For those who wants all certificates [mk-ca-bundle.pl -pALL:ALL] probably will be the option.

**Comment by bagder** [comment]
The documentation for the converter tool is [here](https://curl.haxx.se/docs/mk-ca-bundle.html).

What would you say we should add/change in there to make it clearer what it does by default?

**Comment by fijiol** [comment]
The only probably misleading thing is very first line, in my opinion:
> mk-ca-bundle - convert mozilla's certdata.txt to PEM format

I think "convert" doesn't assume filtering, so I would like to suggest to change "convert" to "exports certificates from".

Another minor note: "(default)" was written on next line after "SERVER_AUTH" and it takes time to notice. would be great to put non-breaking space between them if possible.

The rest looks perfect to me.

**Comment by bagder** [comment]
> I think "convert" doesn't assume filtering

Maybe not, but the first sentence in the DESCRIPTION outlines it pretty accurately. That first line should very short and it really can't describe subtleties.

> would be great to put non-breaking space between them if possible

It's not, because the line wrap position will differ depending on how you display the man page.
