### ISSUE TITLE
Help compiling with icc 2021.1 on macOS

### ISSUE THREAD

**Issue by mathomp4** [curl/curl#6330]
The issue here is that today I installed the new free(?) Intel oneAPI Base and HPC Toolkits: https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html

This gave me Intel C, C++, and Fortran:
```console
❯ ifort -V
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1 Build 20201112_000000
Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.

❯ icc -V
Intel(R) C Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1 Build 20201112_000000
Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.

❯ icpc -V
Intel(R) C++ Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1 Build 20201112_000000
Copyright (C) 1985-2020 Intel Corporation.  All rights reserved.
```
I then went on to trying to build cURL in a set of libraries I maintain. (Note that I use Git Submodules, so below you'll note I'm using `autoreconf`). But things failed.

I will attach my [make log output](https://github.com/curl/curl/files/5698055/makeinstall.intel-2021.1.1_openmpi-4.0.5.curl.log) and [config.log](https://github.com/curl/curl/files/5698058/config.log) for any help. 

Note that *usually* I build with Intel Fortran and ***clang*** on my mac because I only have a license for Intel Fortran. But with oneAPI, I seem to have `icc` and so I thought I'd try that. And things might be wonky. (I'm going to try the Intel+Clang...)

### I did this
```
$ autoreconf -f -v -i
$ ./configure --prefix=/Users/mathomp4/installed/MPI/intel-2021.1.1/openmpi-4.0.5/Baselibs/6.0.26/Darwin \
--includedir=/Users/mathomp4/installed/MPI/intel-2021.1.1/openmpi-4.0.5/Baselibs/6.0.26/Darwin/include/ \
--libdir=/Users/mathomp4/installed/MPI/intel-2021.1.1/openmpi-4.0.5/Baselibs/6.0.26/Darwin/lib \
--with-zlib=/Users/mathomp4/installed/MPI/intel-2021.1.1/openmpi-4.0.5/Baselibs/6.0.26/Darwin \
--disable-ldap --enable-manual --disable-shared --enable-static \
--without-libidn --without-libidn2 --without-nghttp2 --without-nghttp3 \
CC=icc CXX=icpc FC=/opt/intel/oneapi/compiler/2021.1.1/mac/bin/intel64/ifort
...
checking if compiler accepts some basic options... yes
configure: compiler options added: -Qunused-arguments
checking if compiler accepts debug disabling options... yes
configure: compiler options added:
checking if compiler optimizer assumed setting might be used... yes
checking if compiler accepts optimizer enabling options... yes
configure: compiler options added: -Os
checking if compiler halts on compilation errors... yes
checking if compiler halts on negative sized arrays... yes
checking if compiler halts on function prototype mismatch... no
configure: error: compiler does not halt on function prototype mismatch.

make[1]: *** [GNUmakefile:583: curl.config] Error 1
make[1]: Leaving directory '/Users/mathomp4/Baselibs/ESMA-Baselibs-6.0.26/src'
make: *** [GNUmakefile:356: install] Error 2
```

### I expected the following

`configure` not to fail 🤷🏼‍♂️ 

### curl/libcurl version

I'm trying to build curl 7.74.0

### operating system

macOS 10.15.7 (Catalina)

**Comment by mathomp4** [comment]
Update: Definitely happier if `CC=clang`. (Though I found that my build system was preferring `icc` if found in `PATH`. Lazy coding by me.)

**Comment by bagder** [comment]
> configure: error: compiler does not halt on function prototype mismatch.

That's the `CURL_CHECK_COMPILER_HALT_ON_ERROR` macro in `m4/curl-compilers.m4`. If you want that error to rather be a warning, you need to change the `AC_MSG_ERROR` call to a `AC_MSG_ WARN`.

**Comment by mathomp4** [comment]
> > configure: error: compiler does not halt on function prototype mismatch.
> 
> That's the `CURL_CHECK_COMPILER_HALT_ON_ERROR` macro in `m4/curl-compilers.m4`. If you want that error to rather be a warning, you need to change the `AC_MSG_ERROR` call to a `AC_MSG_WARN`.

Hmm. Do I want to do that? I guess I don't know if that's important to the point where, yes, it'll build, but it won't work. (I'm a master of that sort of thing 😄 )

**Comment by bagder** [comment]
I can't tell you what you want. You're the person trying out a crazy compiler. Why wouldn't it work?

**Comment by bagder** [comment]
If you're not willing to try out this fix, then I don't know what else we can do here... maybe you can add some option to `CFLAGS` to force the compiler to react on bad prototypes?

**Comment by mathomp4** [comment]
I'll try and give it a try soon. I'll have to make sure the patch is pretty tight as I think icc on my Linux cluster doesn't react this way. Fun with ifs and GNU make!

**Comment by mathomp4** [comment]
> I can't tell you what you want. You're the person trying out a crazy compiler. Why wouldn't it work?

I am testing this now, but I have to ask, why do you consider the Intel C Compiler a crazy compiler? As seen in (this whitepaper by Colfax Research)[https://colfaxresearch.com/compiler-comparison/#sec-3-1], the Intel C Compiler can often be much more performant than the GNU compiler. Does curl not support ICC? 

And if it is a "crazy compiler", why is Intel C considered in `m4/curl-compilers.m4`:
https://github.com/curl/curl/blob/a7696c73436f643d5d31ce0c3d48d282c79f4b5d/m4/curl-compilers.m4#L48
https://github.com/curl/curl/blob/a7696c73436f643d5d31ce0c3d48d282c79f4b5d/m4/curl-compilers.m4#L250-L289

Should I make an issue/PR to remove support for Intel C if it is not longer considered a supported compiler for cURL?

**Comment by mathomp4** [comment]
Changing the macro did not seem to help. I'll ask on Intel.
