### ISSUE TITLE
7.47.0 -o switch saving into an incorrect path

### ISSUE THREAD

**Issue by westor7** [curl/curl#636]
Hello,

I use the 'curl.exe' downloaded from "https://bintray.com/vszakats/generic/curl/" and when i use to download an file from my server it does not working. it download the file into a wrong path with a incorrect filename.

For example i use this command from CMD: `"C:\Users\westor\Documents\RafaeLLa IRC Bot Services by westor\data\32\curl.exe" -o "C:\Users\westor\Documents\RafaeLLa IRC Bot Services by westor\files\join.txt" http://westor.ucoz.com/rafaella/files/join.txt`
The file will be downloaded into the path `"C:\Users\westor\Documents\RafaeLLa IRC Bot Services by westor\"`with the filename `"C__Users_westor_Documents_RafaeLLa IRC Bot Services by westor_files_join.txt"` this problem is only occurred into 7.47.0 version both 32 and 64 bits versions of curl.exe.

With 7.46.0 it working perfect.

- Thanks!

**Comment by jay** [comment]
This is a known issue (#624) in 7.47.0. It is fixed in the repo and the fix will be in 7.47.1 which will be released in the next few days.
