### ISSUE TITLE
Curl CMakeFiles fails to avoid libidn2 detection

### ISSUE THREAD

**Issue by wrowe** [curl/curl#6361]
https://github.com/envoyproxy/envoy/issues/14506#issuecomment-749719422

We've identified an issue that it's not possible to escape libidn2 using a conventional CURL_DISABLE_IDN2 toggle. This makes curl unusable in our static release builds at envoy and other projects.

**Comment by jay** [comment]
Please try #6362

**Comment by wrowe** [comment]
We've introduced 6362 patch into the envoy release 1.17.0 and all appears well. Looking forward to this hitting a curl release soon!
