### ISSUE TITLE
Excessive HTTP/2 packets with TCP_NODELAY

### ISSUE THREAD

**Issue by Hello71** [curl/curl#6363]
### Steps to reproduce

    wireshark &
    curl https://google.com
    curl --no-tcp-nodelay https://google.com

### Expected behavior

HTTP/2 GET is sent together with TLS Finished (optimally) or in one packet thereafter (realistically) in both cases.

### Actual behavior

Unless --no-tcp-nodelay is specified, HTTP/2 GET is sent in four separate TCP packets after TLS Finished: Magic, SETTINGS, WINDOW_UPDATE, HEADERS.

### Additional information

curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 nghttp2/1.42.0

Although it doesn't cause additional RTT, three packets is still (40+32+22)*3 = 282 bytes on IPv6, plus PHY overhead. Additionally, the server usually sends four ACKs back when one would suffice, eating up 216 bytes on the way back. That's a decent chunk on slow cellular devices, considering that as far as I know there's no good reason to send those bytes.

Firefox and Chromium send one Magic+SETTINGS+WINDOW_UPDATE packet, then a separate HEADERS packet. This seems reasonable, if suboptimal. Firefox also sends a large number of PRIORITY messages in the first packet, perhaps in an effort to "warm up" multiplexing.

**Comment by bagder** [comment]
Does it look sane for HTTP/2 when `TCP_NODELAY` is not set then?

**Comment by Hello71** [comment]
Yes, if --no-tcp-nodelay is specified, then all four are collapsed into one packet. However, that packet is delayed until the TLS Finished is acknowledged, which is one additional RTT.

**Comment by bagder** [comment]
Ok, so then the current state is at least better than the opposite, as wasting a few bytes because of too many packets seems to generally be preferred to being slower. Personally, I don't think this issue gets on the top of my TODO list so I'll appreciate if someone else wants to dig in and polish this...

**Comment by Hello71** [comment]
As I see it, there are two solutions here: the simpler solution is to simply call `setsockopt(sock, IPPROTO_TCP, TCP_CORK, &(int){1}, sizeof(int))` before and `setsockopt(sock, IPPROTO_TCP, TCP_CORK, &(int){0}, sizeof(int))` after queuing the nghttp2 messages. However, that involves two additional system calls for each connection. The more complicated solution is to figure out why nghttp2 is immediately calling the send callback, and either pause that, or buffer those messages inside curl before sending them out with writev if available.

**Comment by bagder** [comment]
> that involves two additional system calls for each connection

... and it is a Linux specific solution.

**Comment by Hello71** [comment]
mneh, there's TCP_NOPUSH on bsd including mac, and windows sucks on network efficiency anyways. the only difference is that TCP_CORK is mandatory whereas TCP_NOPUSH is advisory, but it doesn't matter here (as long as the TCP buffer isn't set absurdly small). there's also MSG_MORE, which avoids the two extra syscalls, but is also Linux-specific.
