### ISSUE TITLE
no response or timeout on Android

### ISSUE THREAD

**Issue by dangvohoanganhvn** [curl/curl#6368]
Hi, I have a problem with curl lib C++ Android. I have an application that downloads many files from a server. The problem is that sometimes I use no good 3G network and switch to a good wifi network curl is stuck in about 2 minutes although I use options **curl_easy_setopt(m_easy_handler, CURLOPT_CONNECTTIMEOUT, 5L)** and **curl_easy_setopt(m_easy_handler, CURLOPT_TIMEOUT, 20L);**. I expect that after 20s curl must return error 28 however it's up to 2 minutes. I try to debug and I found that curl eventually calls the function I specified in option **CURLOPT_XFERINFOFUNCTION**. The similar code I use for IOS does not have this problem. Please help me to address this issue. Thanks

I'm using Realme 6i with Android 10;
Curl version: 7.71

**Comment by bagder** [comment]
Can you reproduce this on other systems? If so, can you provide a small example that does it?

**Comment by dangvohoanganhvn** [comment]
With s10e samsung, The problem has a bit different the curl return error 28 in some minutes although I switch to a good network.

**Comment by dangvohoanganhvn** [comment]
> Can you reproduce this on other systems? If so, can you provide a small example that does it?

In IOS, I used to have the same problem, however, after set config build for **poll** instead of **select** the problem was resolved. In Android, it seems to set to poll by default.

**Comment by bagder** [comment]
Without a way to reproduce or **a lot** of details, we cannot do anything about this. This is not a known problem.

**Comment by bagder** [comment]
No further details, no way to reproduce.

**Comment by Ashokkadavul** [comment]
DNS resolver is configured to synchronous DNS. I can see both USE_ARES and USE_THREADS_WIN32 are commented.
