### ISSUE TITLE
Output is not in seconds 

### ISSUE THREAD

**Issue by fardayaran** [curl/curl#6373]
Hello , I run this command :
 curl -s -w 'Testing Website Response Time for: %{url_effective}\n\nLookup Time:\t\t%{time_namelookup}\nConnect Time:\t\t%{time_connect}\nPre-transfer Time:\t%{time_pretransfer}\nStart-transfer Time:\t%{time_starttransfer}\n\nTotal Time:\t\t%{time_total}\n' -o /dev/null http://www.google.com

 But i get back strange output (it is not in  second)
I didnt have this problem in curl 7.66 version

[curl -V output] 
Lookup Time:            6887
Connect Time:           12491
Pre-transfer Time:      12569
Start-transfer Time:    54497

Total Time:             60246

### curl/libcurl version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.0.2k-fips zlib/1.2.7 zstd/1.4.5 nghttp2/1.42.0
Release-Date: 2020-12-09
----
### operating system
CentOS Linux release 7.9.2009 (Core)
#####

**Comment by bagder** [comment]
Duplicate of #6321 fixed in master already

**Comment by fardayaran** [comment]
> Duplicate of #6321 fixed in master already

thank you
