### ISSUE TITLE
curl fails to resolve file URIs pointing to directories on Windows

### ISSUE THREAD

**Issue by kevinushey** [curl/curl#6379]
First -- happy holidays! I hope the season is treating you well.

tl;dr: On *nix machines, it looks like `curl file:///path/to/directory` can be used to query the existence of a directory, while that same sort of invocation fails on Windows. I'm calling this a bug just because the behavior differs between platforms; please feel free to close with prejudice if you disagree!

#### macOS

```
$ curl -I file://$HOME
Content-Length: 5440
Accept-ranges: bytes
Last-Modified: Fri, 25 Dec 2020 07:07:09 GMT
```

#### Windows

```
C:\Users\kevinushey\bin>curl.exe -I file:///C:/Users/kevinushey/bin
curl: (37) Couldn't open file C:/Users/kevinushey/bin

C:\Users\kevinushey\bin>curl.exe -I file:///C:/Users/kevinushey/bin/curl.exe
Content-Length: 4395640
Accept-ranges: bytes
Last-Modified: Sat, 26 Dec 2020 05:35:49 GMT
```

### I expected the following

- A 0 status code (success) when attempting to resolve an existing directory;
- Headers describing the directory size + modified time if available.

### curl/libcurl version

```
C:\Users\kevinushey\bin>curl -V
curl 7.74.0 (x86_64-pc-win32) libcurl/7.74.0 OpenSSL/1.1.1i (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 WinIDN libssh2/1.9.0 nghttp2/1.42.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets alt-svc brotli libz zstd
```

### operating system

Windows 10 Build 19042.

**Comment by jay** [comment]
Fails because open() in windows doesn't open directories. I don't think this is a bug.

https://github.com/curl/curl/blob/curl-7_74_0/lib/file.c#L184

**Comment by dfandrich** [comment]
That's really just an implementation detail. curl could ensure that the API
returns the same result on both platforms if it wanted to, and it probably
should.

**Comment by bagder** [comment]
I would probably argue that the Content-Length for the dir is a lie too as if you get it without `-I`, you will not get that amount of data...

**Comment by jay** [comment]
IMO I don't think we'd be better off homogenizing the results though I agree that Content-Length for a directory doesn't make sense.

**Comment by bagder** [comment]
Should curl really successfully return anything for `-I` on a directory when "getting" it without `-I` won't return anything at all? Since it can't "get" it, shouldn't it then rather return an error like it does on Windows?

**Comment by dfandrich** [comment]
A directory still has metadata, especially Last-Modified:, that could be needed
by some applications (e.g., a remote virtual filesystem driver). Could that
feature be defined by WebDAV? I have no idea what the specs say about the
harmonization of HEAD and GET, though.

**Comment by bagder** [comment]
Right, but something working against a remote resource wouldn't use a `file://` URL surely?

**Comment by dfandrich** [comment]
An networked application that didn't want to write special code for local file
access could let the user specify a URL and let libcurl just transparently
handle it. This proposal would lead to differing behaviour on the local vs
remote scenario. I'm willing to bet there are applications out there that are
depending on being able to access a directory with file: , whether to get the
metadata or simply whether to determine if it exists or not, and disallowing
that would break them. Unless some spec says that this shouldn't be allowed,
I'd leave it alone. I'd even be hesitant about doing something like removing
Content-Length: on a directory, since that's valid metadata on a POSIX
filesystem. Maybe removing that on Windows is an option if there's no possible
way to get that info (but what do Cygwin and MSYS do in that case?)

**Comment by bagder** [comment]
I suppose the counter proposal is to instead document this behavior. I would think the new `URL-SYNTAX.md` document would be a suitable place for that...

**Comment by kevinushey** [comment]
In case it's useful, the main reason I was exploring this was just to see if I could use `curl` to "pretend" my local filesystem was a simple file server; e.g. similar to what you might see with `python -m http.server`.

While I think the behavior when attempting to access files is pretty uniform across such servers (you get the file you asked for), they usually differ in how they handle requests for "directories".

For that reason, I was expecting that querying a directory via a `file` URI would at least report whether the directory existed (ie: 200 status code if it does exist), even if the actual contents associated with that URI might not be specified / reliable. Does that seem reasonable?

**Comment by bagder** [comment]
@kevinushey so if I read you correctly, you would rather have the Windows code *also* not return error for a directory?

For a long time I considered we should make it possible to list a directory over `file://` when specifying a directory, maybe when ending with a slash, like we do for FTP and SFTP but it has just never happened.

**Comment by kevinushey** [comment]
Right, that's what I believe would be ideal. If the file or directory exists, then an attempt to access it should succeed; otherwise it should fail.

> For a long time I considered we should make it possible to list a directory over file:// when specifying a directory, maybe when ending with a slash, like we do for FTP and SFTP but it has just never happened.

This feels like the right behavior to me as well -- using `file://` URIs is sort of like pretending your filesystem is a local FTP server anyhow?

**Comment by dfandrich** [comment]
I just remembered this right now, but I actually had a situation where this
would have saved me some effort maybe a year ago. I had a script that needed to
get a directory listing from either an ftp site or a local mirror. I wanted to
be able to specify a ftp:// or file:// URL but because of the lacking file:
support, I needed to special case it and hook in some filesystem code to get a
local directory listing. That definitely would have saved me some effort, but
I never got around to fixing curl after I hacked my script to work.

**Comment by bagder** [comment]
1. I'll remove `Content-Length:` for directories with #6421
2. For making FILE:// accesses a directory on Windows consistent with non-windows, I personally will not work on that - I rather leave that to someone who actually develops on Windows. Alternatively, we add it to `KNOWN_BUGS` later if nobody steps up to help out.
3. For actually listing directory contents for a directory over FILE:, I'll add the idea in the TODO document but I don't plan on working on it myself.

**Comment by kevinushey** [comment]
> For making FILE:// accesses a directory on Windows consistent with non-windows, I personally will not work on that - I rather leave that to someone who actually develops on Windows. Alternatively, we add it to KNOWN_BUGS later if nobody steps up to help out.

I would be willing to take a look if I find some time. Do you have any preference for what the solution would look like? (We could just have separate code paths for directories vs. non-directories in each of the file_* routines here?)

Unfortunately Windows doesn't provide any way to refer to a directory via a plain file descriptor in the same way *nix does, so there'd ultimately be some branching based on the file type.

**Comment by bagder** [comment]
> We could just have separate code paths for directories vs. non-directories in each of the file_* routines here?

Yes, there's no need to do anything more complicated than so!

> Unfortunately Windows doesn't provide any way to refer to a directory via a plain file descriptor in the same way *nix does, so there'd ultimately be some branching based on the file type.

Sure, that's pretty much expected and nothing strange about it.

**Comment by bagder** [comment]
Already mentioned as a TODO here:

https://curl.se/docs/todo.html#Directory_listing_for_FILE
