### ISSUE TITLE
Encoding problem with cURL

### ISSUE THREAD

**Issue by Uckpa** [curl/curl#638]
Hi Team,

Looks like cURL has encoding problem with Russain text.
`
$ curl http://hideme.ru
`
`
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"><title>HideME.ru � ������, ��-���: ����� �� ���, ���� ����� � �������</title><link rel='stylesheet' href='http://46.4.152.129/cdn/s2.css' 
`
`
.... etc.
`
A lot of bad text.
`
$ curl -V
`
`
curl 7.35.0 (i686-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
`
-B, --use-ascii doesn't help.
The same problem was found on my work computer(curl 7.42.1). Ubuntu is used there.

Thanks,
Andrey

**Comment by bagder** [comment]
I'm afraid this is not a curl problem. curl downloads that the server delivers and that is what you see there. If you want that translated, converted or handled in any other way than plain pass-through then you need to do that yourself. iconv is a good tool for translating between charsets.

**Comment by Uckpa** [comment]
Possible that you are right, however a lot of other web-sites with Russian text works correctly.
`
$ curl http://hideme.ru > hide 2>&1
`
`
$ cat hide | iconv -f WINDOWS-1251 -t UTF-8
`
It works fine. Text was showed correctly.

Thanks,
Andrey

**Comment by bagder** [comment]
I am right on this: curl does no translations at all.

**Comment by gvanem** [comment]
> `$ curl http://hideme.ru > hide 2>&1 `
> `$ cat hide | iconv -f WINDOWS-1251 -t UTF-8 `

I imagined this should pretty much do what libcurl *could* do if you built it with *libiconv*.
```
-DCURL_DOES_CONVERSIONS -DHAVE_ICONV   \
-DCURL_ICONV_CODESET_OF_NETWORK=xxx   \
-DCURL_ICONV_CODESET_OF_HOST=yyy 
```
From your `curl -V` above, it shows your curl don't use *libiconv*.
