### ISSUE TITLE
Request going through in firefox but failing with `copy as cURL`

### ISSUE THREAD

**Issue by lobstrio** [curl/curl#6387]
### SUMMARY

 I visited this website with firefox, then tried the request with cURL. I've been using same IP address with cURL and with firefox

### WEBSITE

**https://www.newpharma.fr/**

### STEPS

1) I disabled javascript in firefox
2) I removed all cookies in firefox

4) The request goes through in firefox (200 status code)

5) copy as cURL, and tried the request in my terminal. 

6) I got access denied in my terminal -> 403, blocked by cloudflare.

7) I retried the request many times in firefox, and got 200 everytime.

8) I retried many times with curl, and still getting 403, blocked by cloudflare, everytime.

### REMARK

I tried the same with old curl version (curl 7.47.0) and got better results: 

1) request working when putting cookies in the request
2) getting a captcha when sending the request without cookies

### curl/libcurl version

curl 7.54.0 (x86_64-pc-none) libcurl/7.54.0 OpenSSL/1.1.1 zlib/1.2.11 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system

Linux simon-MS-7B85 5.5.4-050504-generic #202002150446 SMP Sat Feb 15 09:50:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sashaboulouds** [comment]
Hello @lobstrio, 

I get **exactly** same issue:

* `curl` sends back `CaptchaPage`
* `modify and send` from `Firefox` sends 200 status code

CURL

```
curl 'https://www.newpharma.fr/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Proxy-Authorization: Basic bHVtLWN1c3RvbWVyLWNfZjllYjhkODktem9uZS10ZXN0X3VzX2FtYXpvbl8yMDIwMTIyOS1pcC0xODEuMjE0LjE2Ni44Mjo0N2ZhM2NwbDVmeXY=' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```

CURL version

```
sashabouloudnine@MBP-de-Sasha-2 ~ % curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

0S

```
sashabouloudnine@MBP-de-Sasha-2 ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
```

🤔

**Comment by dfandrich** [comment]
This is for a CAPTCHA page? Those are explicitly designed to only work a single
time.

And note that you've just published your proxy user name and password to the
world.

**Comment by lobstrio** [comment]
@dfandrich this is not a captcha page. This is a regular html page. We only get a captcha going through cURL

**Comment by sashaboulouds** [comment]
@dfandrich 

Apologies it's `AccessDeniedPage`, just fixed

> And note that you've just published your proxy user name and password to the
world.

I guess I am **generous** man

😌 

NB: just removed it, thanks for update

**Comment by bagder** [comment]
When I go there with my Firefox (on Linux) and make "copy as curl" and run that command line, I get a 200 back.

But my command line contains lots of cookies and other things you didn't show:

~~~
curl 'https://www.newpharma.fr/' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://github.com/curl/curl/issues/6387' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: __cfduid=d20f368730af0e90de6be4a6777fe125c1609279780; DEVICE_IS=%7B%22v%22%3A%22computer%22%2C%22e%22%3A1609884580%7D; PHPSESSID=532pdl38nkd5l7taki5afdovpf; language=%7B%22v%22%3A%22fr%22%2C%22e%22%3A2114377200%7D; lang=%7B%22v%22%3A%22fr%22%2C%22e%22%3A2114377200%7D; visitor_unique_id=%7B%22v%22%3A%22rMuIePROM9dp692QoucWbKc4rk5sDiMN%22%2C%22e%22%3A1617055780%7D; CurrencySymbolAB_checksum=%7B%22v%22%3A%224696e1220102c08143a47de7e186e7af%22%2C%22e%22%3A1641420580%7D; CurrencySymbolAB=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641420580%7D; popular_and_recommended_products=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641420580%7D; ProductPageRedesignAB_checksum=%7B%22v%22%3A%22fa15605d04fc2004f5fa448bc52c633c%22%2C%22e%22%3A1641420580%7D; ProductPageRedesignAB=%7B%22v%22%3A%22A%22%2C%22e%22%3A1641420580%7D; main_menu_categories=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641420580%7D; SESSION_NUMBER=%7B%22v%22%3A1%2C%22e%22%3A1640815780%7D; gdpr-agree-cookie=0; gdpr-consent-cookie-level2=0; gdpr-consent-cookie-level3=0; h2p=%7B%22v%22%3A%22a95f9618b98078d8421940b8e0f920157583b9dd%22%2C%22e%22%3A1609884580%7D; cookiesession1=0FC3B471CXURRTKDY825IYMUYKSM3BFA; __cf_bm=ce8473f53364738f704aa3c87e6d6cb3d3e76e13-1609279780-1800-AQUKs4VpRWv0/5a4VvCyUSk2ucaRN8672MMAOClfOgxrbVBp60pNGb5AeTlA2jBTrMlyNsrbN3iwQo08pC3GH/o=; __fo_s=i; _rpai_id.newpharma.fc06=f63758d027bdabac.1609279782.1.1609279782.1609279782.; _rpai_ref.newpharma.fc06=%5B%22%22%2C%22%22%2C1609279782%2C%22https%3A%2F%2Fgithub.com%2Fcurl%2Fcurl%2Fissues%2F6387%22%5D; _rpai_ses.newpharma.fc06=*' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -H 'TE: Trailers'

**Comment by lobstrio** [comment]
@bagder I you try to modify the request (**remove all the cookies**) and resend your request from fiferox, you'll see that we get 200 status code, without any issue.
You can resend this request without any cookies as many time as needed, and only get 200.

If we copy this request as curl, we get back a 403.

Does that make sense ?

**Comment by bagder** [comment]
Even if so, this is not a curl problem. curl sends exactly what you ask it and the server decides to return a 403 for that. It is not because of a bug or issue in curl. This is a deliberate action on the server's part. The trick is "only" to figure out exactly what little detail the server insists on.

**Comment by sashaboulouds** [comment]
@bagder 

Even with `cookies`, I get: 

* with `browser` a proper full-of-data answer
* with `curl` an `AccessDeniedPage`

CURL

```
curl 'https://www.newpharma.fr/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Cookie: __cfduid=d2d43319d6169589600959fd685b246111609325732; DEVICE_IS=%7B%22v%22%3A%22computer%22%2C%22e%22%3A1609930532%7D; PHPSESSID=s4ke8gnss2lgrq4l9p4idmt9sd; language=%7B%22v%22%3A%22fr%22%2C%22e%22%3A2114377200%7D; lang=%7B%22v%22%3A%22fr%22%2C%22e%22%3A2114377200%7D; visitor_unique_id=%7B%22v%22%3A%22wtBaK07NAHi1tXnjEkkkPYC2Fhm40mjn%22%2C%22e%22%3A1617101732%7D; CurrencySymbolAB_checksum=%7B%22v%22%3A%224696e1220102c08143a47de7e186e7af%22%2C%22e%22%3A1641466535%7D; CurrencySymbolAB=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641466535%7D; popular_and_recommended_products=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641466535%7D; ProductPageRedesignAB_checksum=%7B%22v%22%3A%22fa15605d04fc2004f5fa448bc52c633c%22%2C%22e%22%3A1641466535%7D; ProductPageRedesignAB=%7B%22v%22%3A%22A%22%2C%22e%22%3A1641466535%7D; main_menu_categories=%7B%22v%22%3A%22B%22%2C%22e%22%3A1641466535%7D; SESSION_NUMBER=%7B%22v%22%3A1%2C%22e%22%3A1640861732%7D; gdpr-agree-cookie=1; gdpr-consent-cookie-level2=1; gdpr-consent-cookie-level3=1; h2p=%7B%22v%22%3A%22a95f9618b98078d8421940b8e0f920157583b9dd%22%2C%22e%22%3A1609930532%7D; cookiesession1=0FC3B4715J06TI3Q4H8DX9AOX3URF241; __cf_bm=92a189bc7e3e44cd460851831545ffe3e35aa6b5-1609325733-1800-AQvOqET2FIF+2FjoI2WXNlRpXr7nM09jeLlgYDB25/YSZMJCJibPwewY3LIMc4FwDJkBgwplhiJWjKqJxYJ1ZvIbTXFFaDxqnXSzVGZjn3jxIUnI1SpgSK18UYQsK+PuIMGbqwtHGdNDYB2TkORZR8RMA7GYIrns1fUr8F8FIg/N; __fo_s=i; _ga=GA1.1.967974390.1609325734; _gid=GA1.2.1476538078.1609325734; _rpai_id.newpharma.fc06=ff1bfb49a9382a4b.1609325734.1.1609325736.1609325734.; _rpai_ses.newpharma.fc06=*; __cfruid=8f5e5cc9c83147fd8607a560256f1b5cfcf72478-1609325735; _gcl_au=1.1.393604583.1609325736; _gaclientid=967974390.1609325734; _gasessionid=20201230|03022452; _gahitid=11:55:36; _gat_UA-5388649-1=1; _ga_6FGTFEDMTR=GS1.1.1609325736.1.0.1609325736.60; scarab.visitor=%227F7423676B3F269D%22; _gat=1; _fbp=fb.1.1609325737219.1365409021' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'
```

CURL version

```
sashabouloudnine@MBP-de-Sasha-2 ~ % curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

Is there a way from Server Side to differentiate a `curl` from a request sent from browser?

🤔

**Comment by lobstrio** [comment]
@bagder I suspect this can be something related to another protocol layer.

I'll close the issue now. Thanks for your help

**Comment by dylanarmstrong** [comment]
I think this issue should be kept open, as it's still an issue on master.

**Comment by dylanarmstrong** [comment]
@lobstrio, I think this issue should be kept open, as it's still an issue on master.

**Comment by jay** [comment]
> I think this issue should be kept open, as it's still an issue on master.

What specifically? Copy as cURL requests failing are almost never a curl issue.

**Comment by dylanarmstrong** [comment]
I assumed it meant that cURL was sending something that was detectable by the server, but you're saying that it's probably that the browser 'Copy as cURL' is not giving an accurate command to use? I tested with Safari & Firefox for getting the command.

**Comment by jay** [comment]
Ok but what specifically are you reporting? Do you have the same exact steps to reproduce as the OP? The command should be accurate but that doesn't mean using it to resend the browser request will have the same effect to yield the same result.

**Comment by dylanarmstrong** [comment]
Correct,

Safari:
```
curl 'https://www.newpharma.fr/' -X 'GET' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Host: www.newpharma.fr' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15' -H 'Accept-Language: en-us' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' --verbose
```

Firefox:
```
curl 'https://www.newpharma.fr/' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --verbose
```

I've manually added `--verbose` onto both commands. This is using curl compiled with brotli support.

Neither request includes cookies as this was private browsing. On the browser, this works as expected. On the console, this gives a 403.

**Comment by jay** [comment]
> Neither request includes cookies as this was private browsing.

cloudflare blocks that site with a captcha that you fill out and then it sets a cookie for future requests. If the browsers aren't including the cookies when in incognito mode then they should. If you open a browser issue please reference it here.

> Assuming you have `mitmdump` running on port 8080, this command will work:

Why that works in mitmproxy I don't know but it might be the [sticky cookies](https://docs.mitmproxy.org/stable/overview-features/#sticky-cookies) feature.

**Comment by dylanarmstrong** [comment]
This is actually quite interesting. I don't think it's sticky cookies as that has to be manually enabled, and this is running `mitmproxy -p 8080`, and I restarted it to verify nothing has been previously set.

Working trace:
```
0180: 6e 6f 6e 65 0d 0a 73 65 63 2d 66 65 74 63 68 2d none..sec-fetch-
0190: 75 73 65 72 3a 20 3f 31 0d 0a 74 65 3a 20 74 72 user: ?1..te: tr
01a0: 61 69 6c 65 72 73 0d 0a 0d 0a                   ailers....
== Info: Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
<= Recv header, 13 bytes (0xd)
0000: 48 54 54 50 2f 32 20 32 30 30 20 0d 0a          HTTP/2 200 ..
```

Bad trace:
```
0180: 6e 6f 6e 65 0d 0a 73 65 63 2d 66 65 74 63 68 2d none..sec-fetch-
0190: 75 73 65 72 3a 20 3f 31 0d 0a 74 65 3a 20 74 72 user: ?1..te: tr
01a0: 61 69 6c 65 72 73 0d 0a 0d 0a                   ailers....
== Info: Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
<= Recv header, 13 bytes (0xd)
0000: 48 54 54 50 2f 32 20 34 30 33 20 0d 0a          HTTP/2 403 ..
```

The actual bytes sent to the server after the handshake is completed are identical between a working and non-working curl command.

**Comment by jay** [comment]
can you show the whole trace of both

**Comment by dylanarmstrong** [comment]
[bad-trace.txt](https://github.com/curl/curl/files/7033946/bad-trace.txt)
[working-trace.txt](https://github.com/curl/curl/files/7033953/working-trace.txt)

Here you go

**Comment by jay** [comment]
Yes the requests are the same, so that's interesting. cloudflare must be factoring in the SSL handshake signature when deciding whether to require a captcha.

**Comment by jay** [comment]
While researching this I found a bug in Chrome's Copy as cURL (cmd), filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1242803).

**Comment by megalancast** [comment]
It looks like cloudlfare indeed uses some kind of tls fingerprinting..  https://stackoverflow.com/a/69987605/15404876

**Comment by Dan-Do** [comment]
I have the same issue when using curl command in the terminal and using as libcurl.
Here is the command running in terminal. It returned status 200 OK:
```
curl -v --http2 -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0" https://truyenyy.vip/truyen/de-ton/ > /tmp/error.html
```
Here is my pseudo code using as libcurl. It returned status 403:
```
curl = LibCurl.curl_easy_init
LibCurl.curl_easy_setopt curl, LibCurl::CURLoption::CURLOPT_URL, "https://truyenyy.vip/truyen/de-ton/"
LibCurl.curl_easy_setopt curl, LibCurl::CURLoption::CURLOPT_HEADER, "user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
LibCurl.curl_easy_setopt curl, LibCurl::CURLoption::CURLOPT_FOLLOWLOCATION, 1
LibCurl.curl_easy_perform curl
LibCurl.curl_easy_cleanup curl
```
Maybe I missed something in my code?

**Comment by dfandrich** [comment]
Those aren't the equivalent options as set by the CLI. Try using the --libcurl
option to try to get them to better match.
