### ISSUE TITLE
Add "PATCH" and "DELETE" request method

### ISSUE THREAD

**Issue by HideakiAtsuyo** [curl/curl#6396]
Add "PATCH" and "DELETE" request method

**Comment by jay** [comment]
> Add "PATCH" request method

Can you use curl [-X](https://curl.se/docs/manpage.html#-X) PATCH

**Comment by HideakiAtsuyo** [comment]
I mean in the libcurl(i can't find them)

**Comment by bagder** [comment]
[CURLOPT_CUSTOMREQUEST](https://curl.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html) ?

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by bagder** [comment]
You can already issue such requests.
