### ISSUE TITLE
libcurl doesn't follow redirect to gopher://

### ISSUE THREAD

**Issue by huyndnse63331** [curl/curl#6401]
### I did this
Curl acts very weird when i tried to curl to `gopher://` to make request memcached server.
- curl directory to `gopher://` &rarr; works normally

![image](https://user-images.githubusercontent.com/25204246/103450337-8b1caa00-4ce7-11eb-930a-41761152fefe.png)

- curl to a redirector (redirector will redirect to `gopher://`) &rarr; not work

Redirector:
![image](https://user-images.githubusercontent.com/25204246/103450353-b56e6780-4ce7-11eb-895f-a4f44a5b2c07.png)

Start a PHP server:
![image](https://user-images.githubusercontent.com/25204246/103450366-eb135080-4ce7-11eb-8025-b80923189173.png)

Curl to redirector:
![image](https://user-images.githubusercontent.com/25204246/103450397-4b09f700-4ce8-11eb-8fb1-70a4aea18530.png)

Curl hits redirector and get redirected:
![image](https://user-images.githubusercontent.com/25204246/103450403-6b39b600-4ce8-11eb-9bf8-638aee9e29bd.png)

### I expected the following
I would like when curl hits redirector (redirecting to `gopher://`), i expect the behaviour exactly like when curl directly to `gopher://`.

### curl/libcurl version
[curl -V output]
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
Ubuntu 20.04.1 (amd64)
`uname -a`: Linux astr0 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
Sounds like you're seeing 
https://github.com/curl/curl/commit/6080ea098d97393da32c6f66eb95c7144620298c

**Comment by emilengler** [comment]
FWIW I think your Gopher URL looks weird.
See https://tools.ietf.org/html/rfc4266

**Comment by bagder** [comment]
As mentioned by @dfandrich, the key is in the [CURLOPT_REDIR_PROTOCOLS](https://curl.se/libcurl/c/CURLOPT_REDIR_PROTOCOLS.html) option. This is working as indented!
