### ISSUE TITLE
https://🧡🦊.ws

### ISSUE THREAD

**Issue by Bubu** [curl/curl#6423]
(I've read https://github.com/curl/curl/issues/1441 and https://gitlab.com/libidn/libidn2/-/issues/25)

I think this should be supported but it seems that #1441 was never completely solved.

### I did this

```
$ curl https://🧡🦊.ws
curl: (3) Failed to convert 🧡🦊.ws to ACE; string contains a disallowed character
```

### I expected the following

It works in browsers and in wget. getting converted to the punycode https://xn--9s9hnf.ws/

### curl/libcurl version
```
$ curl -V
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
$ uname -a
Linux bubutux 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
See also https://daniel.haxx.se/blog/2015/02/24/curl-smiley-urls-and-libc/ - IDN names are part of the "URL mess" I often talk about...
