### ISSUE TITLE
left of 'specifier' specifies undefined struct/union 'Curl_share'

### ISSUE THREAD

**Issue by 89z** [curl/curl#6441]
Using this command:

~~~
nmake /f Makefile.vc mode=static
~~~

the build gets pretty far, but then I get this:

~~~
cl /O2 /DNDEBUG /MD /DCURL_STATICLIB /I. /I ../lib /I../include /nologo /W4
/EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL  /DUSE_WIN32_IDN /DWANT_IDN_PROTOTYPES
/DUSE_IPV6  /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL
/Fo"..\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel-obj-lib/vtls/vtls.obj"
..\lib\vtls\vtls.c
vtls.c
..\lib\vtls\vtls.c(349): error C2037: left of 'specifier' specifies undefined
   struct/union 'Curl_share'
..\lib\vtls\vtls.c(350): warning C4013: 'Curl_share_lock' undefined; assuming
   extern returning int
..\lib\vtls\vtls.c(359): error C2037: left of 'specifier' specifies undefined
   struct/union 'Curl_share'
..\lib\vtls\vtls.c(360): warning C4013: 'Curl_share_unlock' undefined; assuming
   extern returning int
..\lib\vtls\vtls.c(402): error C2037: left of 'specifier' specifies undefined
   struct/union 'Curl_share'
..\lib\vtls\vtls.c(403): error C2037: left of 'sessionage' specifies undefined
   struct/union 'Curl_share'
~~~

am I missing some flag?

**Comment by bagder** [comment]
What curl version is this?

**Comment by 89z** [comment]
I think I figured out the issue. I was defining environment variable `CL` similar to this:

~~~
CL=/IC:\Windows Kits\10\Include\10.0.19041.0\ucrt
~~~

but for some reason, the order of the includes makes a difference. For example, if I manually build that file like this:

~~~
cl /O2 /DNDEBUG /MD /DCURL_STATICLIB /I"C:\visage\Windows Kits\10\Include\10.0.19041.0\ucrt" /I ../lib
~~~

I get the same error, but if I swap them:

~~~
cl /O2 /DNDEBUG /MD /DCURL_STATICLIB /I ../lib /I"C:\visage\Windows Kits\10\Include\10.0.19041.0\ucrt"
~~~

then it builds fine. Instead of `CL`, I think I will try to modify `CURL_CFLAGS` or something.

**Comment by 89z** [comment]
Hm, actually, unlike the MinGW Makefile:

https://github.com/curl/curl/blob/3831043eff9ed412428150537374facb609e5b33/lib/Makefile.m32#L107

The MSVC Makefile doesnt allow for extra flags:

https://github.com/curl/curl/blob/3831043eff9ed412428150537374facb609e5b33/winbuild/MakefileBuild.vc#L53

**Comment by jay** [comment]
> The MSVC Makefile doesnt allow for extra flags:

It can be done by setting CC but there is no separate extras variable. Please include curl version and what directions you are using because I can't recall anyone else reporting this.

**Comment by 89z** [comment]
basically just this:

~~~
git clone --depth 1 git://github.com/curl/curl
Set-Location curl/winbuild
nmake /f Makefile.vc mode=static
~~~

**Comment by jay** [comment]
Either way it would be prepended. Did you read https://github.com/curl/curl/blob/curl-7_74_0/winbuild/README.md#open-a-command-prompt ? What version of VS are you using?

**Comment by 89z** [comment]
The page you linked wasnt helpful, but I did find this:

> 2. If specified using a #include directive in angle bracket form, or if the
> local directory search has failed, it searches directories specified by using
> the `/I` option, in the order that `CL` encounters them on the command line.
>
> Directories specified in the `INCLUDE` environment variable.

https://docs.microsoft.com/cpp/build/reference/i-additional-include-directories

So items under the `INCLUDE` variable, are added after everything else, which is
exactly what I am needing. So instead of using `CL` environment variable, instead
I did something like this:

~~~
INCLUDE=C:\Windows Kits\10\Include\10.0.19041.0\um;C:\Windows Kits\10\Include\10.0.19041.0\ucrt
~~~

and I was able to bypass the error reported above. Frustratingly, I wasnt able to
find any official documentation on the variable syntax, but I did find an example
here:

https://stackoverflow.com/questions/60516987

**Comment by jay** [comment]
Visual Studio prompt or vcvarsall (which is what is called before the prompt starts) should set the proper variables one of them INCLUDE. Again what version of VS and curl, and what prompt are you using? I don't think VS has an accepted build environment in powershell.

**Comment by 89z** [comment]
> Again what version of VS

Visual Studio 2019 (version 16)

> and curl

I was just using `master`, but I think I will switch to 7.74 so I can avoid
running `buildconf.bat`.

> what prompt are you using? I don't think VS has an accepted build environment
> in powershell.

I reverse engineered the Visual Studio installer:

https://github.com/89z/visage

So I am using cURL as a test to see if my Visual Studio install can actually
build something.

**Comment by jay** [comment]
I don't see a bug here, your build environment is custom.

**Comment by gvanem** [comment]
@89z  So the root cause was that the Windows-Kit's `<share.h>` shadowed libcurl's `<share.h>`?
If that was the case, you would have trouble compiling any C-package. Not just curl/libcurl. 

I suppose a construct like (in `urldata.h`?):
```
#if defined(_INC_SHARE) && !defined(HEADER_CURL_SHARE_H)
#error "You I-path is messed up"
#endif
```
could detect this. But it's not curl's job to teach programmers to setup their compiler & environment.

**Comment by 89z** [comment]
> So the root cause was that the Windows-Kit's `<share.h>` shadowed libcurl's
> `<share.h>`?

Yeah, looks like this is the culprit:

~~~
Windows Kits\10\Include\10.0.19041.0\ucrt\share.h
~~~

> I suppose a construct like (in `urldata.h`?):
> 
> ```
> #if defined(_INC_SHARE) && !defined(HEADER_CURL_SHARE_H)
> #error "You I-path is messed up"
> #endif
> ```

I think a better fix would be just adding a link to this:

https://docs.microsoft.com/cpp/build/reference/i-additional-include-directories

here:

https://github.com/curl/curl/blob/master/winbuild/README.md

> But it's not curl's job to teach programmers to setup their compiler &
> environment.

Id say thats harsh, given that as far as I know, Im the first person to ever use
Visual Studio like this.

**Comment by 89z** [comment]
Is it possible to build just LibCurl with Visual Studio? I looked through the `MakefileBuild.vc`, but it seems to always build the tool as well.

**Comment by jay** [comment]
Not with winbuild build method. You can try cmake, which should generate the curl tool and curl library projects, then you could build only the library project from the command line. Also there are project files in some common configurations in projects/ and you can build only the library project that way.
