### ISSUE TITLE
Document -w time_pretransfer parameter more precicely

### ISSUE THREAD

**Issue by gavenkoa** [curl/curl#6452]
It is a common to define shell function:

```
mycurl() {
  curl -w "\n\
   namelookup:  %{time_namelookup}\n\
      connect:  %{time_connect}\n\
   appconnect:  %{time_appconnect}\n\
  pretransfer:  %{time_pretransfer}\n\
     redirect:  %{time_redirect}\n\
starttransfer:  %{time_starttransfer}\n\
-------------------------\n\
        total:  %{time_total}\n" "$@"
}
```

and use it as:

    mycurl https://google.com

But the man page is confusing:

```
time_pretransfer
                         The time, in seconds, it  took from the start until the file transfer  was just about to begin.
                         This includes all  pre-transfer commands and negotiations that
                         are specific to the particular protocol(s) involved.
```

Check struggles, misconceptions and guesses here:

https://stackoverflow.com/questions/17638026/calculating-server-processing-time-with-curl

Please improve documentation of `time_pretransfer` option, give a concrete example the difference between HTTP vs HTTPS as the most practical examples!

**Comment by gavenkoa** [comment]
There is nice picture in the post https://blog.cloudflare.com/a-question-of-timing/

https://blog.cloudflare.com/content/images/2018/10/Screen-Shot-2018-10-16-at-14.51.29-1.png

Still it is unclear that for HTTPS `time_pretransfer` includes symmetric cipher initialization time (or what?).

**Comment by bagder** [comment]
So what's confusing? It's a time stamp that is set after the "send me the file" instruction has been sent to the server. When libcurl internally switches from the "DO" state (which usually ). (It struck me just now that for FTP for example this is misleading, I'm going to do a PR to change the internals slightly.)

**Comment by bagder** [comment]
I think #6453 did the job.
