### ISSUE TITLE
Unable to send http header bigger than 16K when using https

### ISSUE THREAD

**Issue by copbint** [curl/curl#6460]
### I did this
Use curl to send an http**s** request with header bigger than 16K to a nginx server(nginx large_client_header_buffers para have been changed to: large_client_header_buffers 8 160K; )

### I expected the following
Normally get response from server.

### other information
1. If we use header smaller than 16K， curl works well。
2. If we use http, not https, with header bigger than 16K, curl also works well.
3. If use postman/wget to visit same nginx server with same requet use https, postman/wget works well.

### curl/libcurl version
root@workstation:/opt/openresty# curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

[curl -V output]
```
root@workstation:/opt/openresty# curl -v -k  https://localhost:8080 -H "X-Auth-Token:$token"
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=CN; ST=ubuntu-1; L=ubuntu-1; O=ubuntu-1; OU=ubuntu-1; CN=ubuntu-1
*  start date: Nov 23 03:25:47 2020 GMT
*  expire date: Nov 21 03:25:47 2030 GMT
*  issuer: C=CN; ST=envoy-test; L=envoy-test; O=envoy-test; OU=envoy-test; CN=envoy-test
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> X-Auth-Token:...........................(a very long token, 16295byte)


Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server 
```  

Actually, the token is bigger than 16295byte, curl failed to send rest byte of token and hangs。After a minute, server send a Finish packet, and the connection is closed. curl says: "Empty reply from server"

We can see, curl totally send exactlly 16834(1024*16K)byte。
```
GET / HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.68.0
Accept: */*
X-Auth-Token:
```
is 89 byte, add to 16295, result is 16834 byte. 

### operating system
Linux workstation 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
I created #6470 in an attempt to reproduce this problem with a curl test case. The test runs fine in my dev machine.

This test case makes a simple HTTPS GET and includes a custom request header that is 49006 bytes long.

**Comment by bagder** [comment]
... that PR runs test 410 on several platforms with lots of TLS backends (except mesalink). So it wasn't just on my dev machine it wasn't reproducible!

**Comment by copbint** [comment]
After more test, I find this issue may only exist with early versions like "7.68.0"(default version of ubuntu 20.04).
I downloaded source code of the latest version "7.74.0" and compiled a exautable file from it, and it works well with big header.

**Comment by copbint** [comment]
More information: I have an CentOS 8 with curl 7.61.1, and it works well too.

**Comment by bagder** [comment]
Since this works in the latest release, we consider this case closed.
