### ISSUE TITLE
Python bindings page outdated

### ISSUE THREAD

**Issue by p** [curl/curl#647]
https://curl.haxx.se/libcurl/python/

- Current website is http://pycurl.io/
- PycURL has an installation document (http://pycurl.io/docs/latest/index.html#installation)
- There are quickstart examples (http://pycurl.io/docs/latest/quickstart.html) and the other examples are on github (https://github.com/pycurl/pycurl/tree/master/examples)
- There is quite a bit of documentation written (http://pycurl.io/docs/latest/index.html)
- Download link should point to pypi (https://pypi.python.org/pypi/pycurl) or bintray (https://bintray.com/pycurl/pycurl/pycurl/view)
- We have a couple more authors now (https://raw.githubusercontent.com/pycurl/pycurl/master/COPYING-MIT)

Thanks!

**Comment by JCMais** [comment]
you can make a Pull Request for the changes you think that should be done: https://github.com/curl/curl-www/blob/master/libcurl/python/_index.html

**Comment by p** [comment]
Will do, thanks!
