### ISSUE TITLE
SFTP uploaded file is unexpectedly empty

### ISSUE THREAD

**Issue by rmettes** [curl/curl#6480]
### I did this
curl --key [path to key] -vvv -u [upload user]: -T file.xml sftp://[redacted servername]/

This creates an empty (xml) file on the SFTP server.

### I expected the following

It should upload the file contents to the server

### Workaround
Using the trace option instead of verbose or silent fixes the issue

curl --key [path to key] --trace - -u [upload user]: -T file.xml sftp://[redacted servername]/

### curl/libcurl version
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.6 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink 

[curl -V output]
curl --key [path to key] -vvv -u [upload user]: -T file.xml sftp://[redacted servername]/
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
* Trying [redacted IP]...
* TCP_NODELAY set
* Connected to [redacted servername] ([redacted IP]) port 22 (#0)
* User: [redacted user]
* Authentication using SSH public key file
* Completed public key authentication
* Authentication complete
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
* Connection #0 to host [redacted host] left intact

### operating system
Linux [redacted hostname] 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
I cannot reproduce. I ran your command line with these two versions without issues:

## current dev master using libssh

$ curl -V
curl 7.75.0-DEV (x86_64-pc-linux-gnu) libcurl/7.75.0-DEV (GnuTLS/3.7.0) OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 c-ares/1.17.1 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.42.0-DEV librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink MultiSSL NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd

## current Debian unstable with libssh2

$ curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.42.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

**Comment by rmettes** [comment]
Yup, it's a weird thing.. on the same machine it works without problems with other sftp servers but this one won't work normally.
Maybe it's helpful to know what kind of server I'm connecting to when experiencing this problem:
SSH-2.0-Cleo VLProxy/3.8.2.0 SSH FTP server

**Comment by bagder** [comment]
Helpful, but unless we can reproduce the problem we can only provide advice for you to track it down.

I would propose you start out building an example from libssh2 and try to cut out curl completely from the equation. If that still reproduces the problem, then you add tracing and take it to the libssh2 project. If it doesn't reproduce the problem, then the issue is in the curl side and we can continue from there.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
