### ISSUE TITLE
Visual Studio project generator broken

### ISSUE THREAD

**Issue by jay** [curl/curl#649]
~~~
>generate vc10
20743/ was unexpected at this time.
~~~

This is an unusual one. The command interpreter may still process special characters in `REM` comments in batch files, and in this case interprets a question mark in a URL as path globbing or some such.

~~~
>rem /?foo=bar/
bar/ was unexpected at this time.
~~~

Introduced in https://github.com/curl/curl/commit/d49881c#diff-227457f73d3f44861a493547a1a5a59e

To remedy this I'm going to remove that NOTE. FYI @captain-caveman2k @vszakats

**Comment by mback2k** [comment]
Thanks @jay. @captain-caveman2k and I always wondered why vc10 fails.

**Comment by vszakats** [comment]
@jay Sorry about this. Another, potentially better solution would be to switch
to use `::` as comment marker. It would resolve this issue and looks cleaner too.
It's supported way back into MS-DOS, so it should be safe:
```batch
:: https://blogs.msdn.microsoft.com/oldnewthing/20080926-00/?p=20743/
```

**Comment by vszakats** [comment]
Patch:
https://github.com/vszakats/curl/commit/a197b880f38f1bfd35f199886f1b418d4904087b

**Comment by jay** [comment]
It's not your fault, just a bug. I would argue it's a Windows bug but the way they document it you can't really be sure. I've programmed a lot of batch and I've never seen that happen before. I don't think it's necessary to change all .bat comments from `rem` to `::` to address this issue. That note is stale anyway since we no longer set the errorlevel.
