### ISSUE TITLE
getaddrinfo thread failed to start

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#6495]
I have encountered the issue of failed to start getaddrinfo thread on windows. 

logs as follow:

**[my_curl_debug_callback] This: 56903720 TEXT :getaddrinfo() thread failed to start**

I am using libcurl 7.74.0 without c-ares. No more trace from the logs, is there any possible reason ? Many thanks.

**Comment by jay** [comment]
Are you able to reproduce this all the time? How did you build libcurl, what OS are you running?

Also please run this:
~~~c
  curl_version_info_data *ver = curl_version_info(CURLVERSION_NOW);
  
  printf("%s\n", curl_version());

  if(!(ver->features & CURL_VERSION_ASYNCHDNS))
    printf("synchronous\n");
  else if(!ver->age || ver->ares_num)
    printf("ares\n");
  else
    printf("threaded\n");
~~~

**Comment by ustcqidi** [comment]
@jay Many thanks for your feedback.

**Here is the OS infos:**
Windows 10 Version 17134 MP (8 procs) Free x64
Product: WinNt, suite: SingleUserTS
Edition build lab: 17134.1.amd64fre.rs4_release.180410-1804

**Here is the curl info, collect from the above code**
libcurl/7.74.0 OpenSSL/1.1.1i 
threaded

I Have build the libcurl using libcur.vcxproj, which locate at curl-7.74.0\projects\Windows\VC15\lib

**Comment by jay** [comment]
So is it reproducible, and how often? There are very few ways that thread init could fail. Are we supporting unix sockets in Windows 10? In socketpair.h try commenting out `/* #define USE_SOCKETPAIR 1 */` see if that helps
https://github.com/curl/curl/blob/e052859759b34d0e05ce0f17244873e5cd7b457b/lib/socketpair.h#L33-L34

**Comment by ustcqidi** [comment]
@jay   Thanks, i will try.

It could be reproduced easily but not everytime on the computer of our customer. I could not reproduce it on my computer.

One more information, when using libcurl version 7.55.1 could not reproduce the issue, which have not the logic of socketpair logic in init_thread_sync_data

`
static
int init_thread_sync_data(struct thread_data *td,
                           const char *hostname,
                           int port,
                           const struct addrinfo *hints)
{
...

#ifdef USE_SOCKETPAIR
  /* create socket pair, avoid AF_LOCAL since it doesn't build on Solaris */
  if(Curl_socketpair(AF_UNIX, SOCK_STREAM, 0, &tsd->sock_pair[0]) < 0) {
    tsd->sock_pair[0] = CURL_SOCKET_BAD;
    tsd->sock_pair[1] = CURL_SOCKET_BAD;
    goto err_exit;
  }
#endif
...
`

**Comment by ustcqidi** [comment]
@jay 

After commenting out /* #define USE_SOCKETPAIR 1 */ , everything is OK.

What's the problem, if we remove the support of socketpair ?

**Comment by jay** [comment]
> After commenting out /* #define USE_SOCKETPAIR 1 */ , everything is OK.
> 
> What's the problem, if we remove the support of socketpair. Could we dynamically set whether support socketpaire via CURLOPT_ ?

You won't be able to wake up a [curl_multi_poll](https://curl.se/libcurl/c/curl_multi_poll.html) call from a different thread by calling [curl_multi_wakeup](https://curl.se/libcurl/c/curl_multi_wakeup.html). Is your client using a local firewall that is interfering with the creation of local sockets, or accepting connections on them? I would think it would be 100% reproducible if that was the case.

I've added some debug output to that function, please see branch [jay:debug_Curl_socketpair](https://github.com/jay/curl/tree/debug_Curl_socketpair). You can also download it as a patch, https://github.com/curl/curl/compare/master...jay:debug_Curl_socketpair.diff

**Comment by ustcqidi** [comment]
@jay 

Got it, Many thanks

We are checking with our customer. There have PAC script and firewall config in the enviroment
Possibly related with the local config of the environment, this issue only occur on some few machines.

I will update the information here, once I got new findings.

**Comment by ustcqidi** [comment]
@jay 

Sorry for late reply.

We have reproduce the issue with more logs.

Per the system and application level, it seems to the issue occur when connect/accept

```
if(connect(socks[0], &a.addr, sizeof(a.inaddr)) == -1)
    goto error;
  socks[1] = accept(listener, NULL, NULL);
```

Here is the System level trace

```
[0]4A14.2A3C::01/26/21-11:12:36.9045951 [Microsoft-Windows-TCPIP/Diagnostic] TCP: connection 0xFFFF860FE64889A0 (local=127.0.0.1:60177 remote=127.0.0.1:9000) connect proceeding. 16, 127.0.0.1:60177, 16, 127.0.0.1:9000, STATUS_SUCCESS, 0
[2]0000.0000::01/26/21-11:12:37.9053517 [Microsoft-Windows-TCPIP/Diagnostic] TCP: connection 0xFFFF860FE64889A0 (local=127.0.0.1:60177 remote=127.0.0.1:9000) retransmitting connect attempt, RexmitCount = 1. 0xFFFF860FE64889A0, 16, 127.0.0.1:60177
[2]0000.0000::01/26/21-11:12:37.9053517 [Microsoft-Windows-TCPIP/Diagnostic] TCP: connection 0xFFFF860FE64889A0 (local=127.0.0.1:60177 remote=127.0.0.1:9000) retransmitting connect attempt, RexmitCount = 1. 0xFFFF860FE64889A0, 16, 127.0.0.1:60177
```

**Comment by bagder** [comment]
Since there's only supposed to be a single connect to the listener, why would it need more than 1 in queue?

Is there something else that connects to that listener on this system?

**Comment by ustcqidi** [comment]
@bagder 

Should not have connects to the listener. We are not sure what special settings in the machine, but this issue occur sometimes.

**Comment by jay** [comment]
Maybe there are no ports available and SO_REUSEADDR means it could reuse an existing port?

**Comment by ustcqidi** [comment]
I have uploaded the system trace to google drive, which maybe have some useful infos.

https://drive.google.com/file/d/1wXlJFe9-DdjN4EVhzHseY3C4tZ5iuFzz/view

**Comment by jay** [comment]
> I have uploaded the system trace to google drive, which maybe have some useful infos.

That looks like a trace specific to your application. Please try the debug code I suggested, also try commenting out setsockopt SO_REUSEADDR.

**Comment by ustcqidi** [comment]
@jay  OK,  I have closed the issue. Will give update here once I got new findings. Thanks.

**Comment by smanolache** [comment]
Hello,

I have the same issue, but this time in Linux, so it doesn't seem to be a Windows-related issue. I'm using version 7.72.0 linked with gnutls, linux kernel 5.9.0.

In my case the problem appears when my code runs as a module of nginx (version 1.18.0). Maybe nginx executes some calls (ioctls?) that interfere with libcurl.

**Comment by bagder** [comment]
@smanolache then you should start trying to figure out exactly what that fails or even try to come up with a way that we can do to reproduce the issue. nginx shouldn't be able to interfere with libcurl.

**Comment by smanolache** [comment]
I found something, but I don't know where it might come from.

The message ``getaddrinfo() thread failed to start`` comes from a failed ``socketpair`` syscall in libcurl. The surprising errno is ``EMFILE``, namely the per-process limit of open file descriptors is exceeded. I've checked ``/proc/<pid>/fd`` and indeed I had 1024 open files.

What's strange is that I had about 5-7 open files just before the http request that my server attempts to serve. So I've started the web server afresh (it has absolutely no traffic, it receives only the requests that I perform manually) and run ``strace -f -p pid``. Here's an excerpt of the output of ``strace``:

```
recvfrom(3, "POST /privacy/v1/auth/ids HTTP/1"..., 1024, 0, NULL, NULL) = 255
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 11
close(11)                               = 0
socketpair(AF_UNIX, SOCK_STREAM, 0, [11, 12]) = 0
fcntl(11, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(11, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
fcntl(12, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(12, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 13
close(13)                               = 0
socketpair(AF_UNIX, SOCK_STREAM, 0, [13, 14]) = 0
fcntl(13, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
fcntl(14, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(14, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
```

After the webserver receives the request, the ``socket`` system call is invoked with UDP6 arguments (by whom? I suppose it is not libcurl because I didn't find SOCK_DGRAM in its http code), then the socket is closed. Then a ``socketpair`` call is performed, some ``fcntl`` calls, and then the whole thing repeats until the number of permitted open files is exhausted. When libcurl calls ``socketpair`` it'll get the ``EMFILE`` error, as said.

I'll dig further and keep you posted, but as it looks, libcurl is not the culprit.

**Comment by 3F51B5** [comment]
It was me his ole lady

**Comment by smanolache** [comment]
As usual, my fault. I simply created too big a connection pool and I reached the limit of open file descriptors. Sorry for bothering you.

**Comment by jay** [comment]
Not a bother, thanks for the update.
