### ISSUE TITLE
HTTP/3: Problem uploading file

### ISSUE THREAD

**Issue by maksvel** [curl/curl#6510]
Uploading files gets interrupted at certain file size. 
Server: nginx with http/3 support 

client:

![image](https://user-images.githubusercontent.com/9415635/105611363-13591100-5db5-11eb-8826-cfb5d39aebb7.png)
small file: everything is fine, the file is uploaded

But greater files, i.e. 100 K gives this:
![image](https://user-images.githubusercontent.com/9415635/105611369-279d0e00-5db5-11eb-97fb-ff547579ea82.png)

The upload cannot be made if the file is greater than cca 10 K.

With openlitespeed  server things are very similar

(I tried another quic implementation (openssl, ngtcp2, nghttp3): things were even worst.)

**Comment by bachue** [comment]
@maksvel I met this error before and I gave the PR to resolve it: https://github.com/curl/curl/pull/6319
