### ISSUE TITLE
Add option to disable removing double-dot components from URLs

### ISSUE THREAD

**Issue by ygale** [curl/curl#652]
Since 7.32.0 curl applies the [algorithm in RFC 3986](http://tools.ietf.org/html/rfc3986#section-5.2.4) to remove double-dot components from URLs. That is fine if you want to load a URL simply as if you are a browser. But one of the principle uses of curl is for testing and debugging servers. Due to the RFC, the ability to request URLs that do contain double-dot components is critical. Can we please add an option to disable this new behavior of curl, including during `--location` redirects? Thanks.

**Comment by bagder** [comment]
You mean like [--path-as-is](https://curl.haxx.se/docs/manpage.html#--path-as-is) ?

**Comment by ygale** [comment]
Sure, that would be great. I'll trust you completely on the name - no bikeshedding from this direction. :)

**Comment by bagder** [comment]
Sorry I wasn't clear: this option already exists. My suggestion is that you make use of it! =)

**Comment by patrikhson** [comment]
Hey,

Have you read the latest article written by me? Just take a look, it's very interesting. Please read here <http://styminufra.firstjudicialclaims.net/xyhkm>

Cheers, paf@frobbit.se
