### ISSUE TITLE
Unuseful warnings with --xattr/--remote-time + --output /dev/null

### ISSUE THREAD

**Issue by vszakats** [curl/curl#6533]
When using the pattern `curl <URL> --output /dev/null` (typically in conjunction with `--write-out '%{<format>}'` to read the `<format>` value without actually retrieving the URL content), _while_ having `--xattr` and/or `--remote-time` options enabled (e.g. via `.curlrc` or a `curl` alias), the warnings below may (remote time only when the server returns a `Last-Modified:` header) appear on `stderr`, respectively:
```
Warning: Error setting extended attributes: Operation not permitted
Failed to set filetime <unixtime> on outfile: Operation not permitted
```

Example (for \*nix platforms):
```shell
$ curl --xattr --remote-time --output /dev/null https://example.org/ --write-out '%{content_type}'`
```

Actual console output:
```console
Warning: Error setting extended attributes: Operation not permitted
Failed to set filetime <unixtime> on outfile: Operation not permitted
text/html; charset=UTF-8
```
Expected console output:
```console
text/html; charset=UTF-8
```

An inconvenience rather than a bug per se, yet I think it'd be an improvement to try mitigating this, either by suppressing the warning when a non-file output is used, or by bringing `--remote-time` behavior closer to `--xattr` and omit the warning if the `--silent` option is used.

**Comment by bagder** [comment]
This *is* file output for all curl knows...

**Comment by vszakats** [comment]
Indeed, that's the difficult part. This specific value can be hard-coded (which is rather unelegant), but I was wondering if there is a better (and possibly platform-agnostic) option.

Many thanks for your quick PR, and if I read it correctly, this will also silence it like it is done with `--xattr`, which I think should resolve this nicely. Definitely LGTM.

**Comment by bagder** [comment]
Yes, the PR will make the time-setting error message truly respect `--silent` as well, which of course was a bug to begin with.
