### ISSUE TITLE
CURLE_BAD_FUNCTION_ARGUMENT on win32 platform.

### ISSUE THREAD

**Issue by jiazhanfeng1989** [curl/curl#6541]
### I did this
std::string data;
data.assign(1024,'a');

auto res = curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE_LARGE, data.length());

### I expected the following
expected: res == CULR_OK
actual: res ==CURLE_BAD_FUNCTION_ARGUMENT

### curl/libcurl version
[curl -V output]
7.68

### operating system
win32

Root cause:
curl_off_t is 8 byte , std::string::size_type is 4 byte on win32.
Due to the different length of the cur_off_t and string::size_type on 32-bit platforms,
curl resolvers CURLOPT_POSTFIELDSIZE_LARGE with a random value, and when the value is less than -1,  it returns CURLE_BAD_FUNCTION_ARGUMENT.

https://github.com/curl/curl/blob/62e0fe21561eab43837154d918f1e9676f10bb14/lib/setopt.c#L526

**Comment by jay** [comment]
This isn't a bug you will need to cast it (curl_off_t)data.length()
