### ISSUE TITLE
Compile curl for Microsoft Game Development Kit

### ISSUE THREAD

**Issue by jzer0** [curl/curl#6546]
Hi cURL,

I'm looking to build curl libs for use with applications compiled using the Microsoft Game Development Kit (https://www.microsoft.com/en-us/software-download/gdk) for the Gaming.Desktop.x64 and Gaming.Xbox.Scarlett.x64 platform configurations. Installing this package provides for the following configurations in Visual Studio:

![image](https://user-images.githubusercontent.com/8395705/106264982-b03d0380-6226-11eb-9a5b-699cbe2d3a7d.png)

I would like to know whether this is currently possible or supported to compile curl for these platform configurations.

**Comment by jzakrzewski** [comment]
I'm almost sure there is a way to do this with CMake. However you'd probably have to figure that out on your own. 
This may be as easy as `cmake -G "Visual Studio 16 2019" -A "Gaming.Desktop.x64"` but I don't actually know.

**Comment by bagder** [comment]
Hi!

Thanks for your interest in curl and related manners, but you seem to have asked a question or help, and this is an issue tracker that we reserve for dealing with issues/bugs really.

Please ask questions and ask for support etc on the [dedicated mailing lists](https://curl.haxx.se/mail/). You will also reach a lot more people that way!
