### ISSUE TITLE
 curl-7.74.0 -- Protocol “https” not supported or disabled in libcurl

### ISSUE THREAD

**Issue by patpatpat123** [curl/curl#6550]
Small question regarding curl and the error Protocol “https” not supported or disabled in libcurl please.

I built a curl version, a very recent one, 7.74.0, using:
```
cd /curl-7.74.0; sh configure --with-ssl --with-darwinssl; make; make install
```

And I tried other combinations of make, doing most of the permutation between make, make clean, make test, make install.

And I tried between configure , configure --with-ssl --with-darwinssl, configure --with-ssl --with-libssh2, configure adding the path of my openssl.

Sadly, on every permutation, it yields:
```
curl --version
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0
Release-Date: 2020-12-09
Protocols: dict file ftp gopher http imap mqtt pop3 rtsp smtp telnet tftp
Features: alt-svc AsynchDNS IPv6 Largefile UnixSockets
```

Is it a bug where there is no https in this version? 

Thank you

**Comment by bagder** [comment]
You can build with a number of different TLS libraries with this version and I've done it personally too, not to mention in the CI builds.

I tried just now to check out 7.74.0 and build it with Secure Transport:
~~~
$ ./src/curl -V
curl 7.74.0-DEV (x86_64-apple-darwin19.6.0) libcurl/7.74.0-DEV SecureTransport zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 nghttp2/1.42.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS Debug HTTP2 IDN IPv6 Largefile libz NTLM NTLM_WB SSL TrackMemory UnixSockets zstd

**Comment by patpatpat123** [comment]
Many thanks for the answer @bagder If I may, could you please tell me how did you "build it with Secure Transport"?

Something like ``` .cd /curl-7.74.0; sh configure --with-Secure-Transport; make; make install ``` ?

**Comment by Mandymoore680** [comment]
What's this all about I'm new sorry but thanks

**Comment by bagder** [comment]
@patpatpat123: not very complicated:

    CC=clang ./configure --with-darwinssl

but `--with-secure-transport` should work equally good. I just happened to use the former because my old script does this.

**Comment by bagder** [comment]
No further details or feedback, closing

**Comment by patpatpat123** [comment]
Indeed, this was the fix. Many thanks!
