### ISSUE TITLE
Example progressfunc.c does not compile

### ISSUE THREAD

**Issue by demhademha** [curl/curl#6551]
### I did this
1: download the source code from https://curl.se/libcurl/c/progressfunc.html
2: compile with clang ($clang progressfunc.c) 
### I expected the following
i expected it to compile
Actual output:
progressfunc.c:114:5: error: unterminated /* comment
    /* xferinfo was introduced in 7.32.0, no earlier libcurl versions will
    ^
progressfunc.c:113:2: error: unterminated conditional directive
#if LIBCURL_VERSION_NUM >= 0x072000
 ^
progressfunc.c:119:42: error: expected '}'
       callback, making the older callbac
                                         ^
progressfunc.c:107:12: note: to match this '{'
  if(curl) {
           ^
progressfunc.c:119:42: error: expected '}'
       callback, making the older callbac
                                         ^
progressfunc.c:101:1: note: to match this '{'
{
^
4 errors generated.
 
### curl/libcurl version
not applicable 
[curl -V output]
not applicable 
### operating system
Ubuntu 21.04 

Linux ahmed-T90B-Pro 5.8.0-36-generic #40+21.04.1-Ubuntu SMP Thu Jan 7 11:35:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
It looks like your compiler is broken.

1. The comment on line 114 is not unterminated. It ends on line 122.
2. The conditional directive on line 113 is not unterminated, it ends on line 128 or 132
3. There's no closing brace on line 119!

... and I don't know why you think the libcurl version isn't relevant. It certainly is!
