### ISSUE TITLE
fix appveyour-ci link to windows msvs builds

### ISSUE THREAD

**Issue by snikulov** [curl/curl#656]
After moving to curl organization appveyour-ci stop checking pull requests.
I suspect it was because it moved to new link from https://ci.appveyor.com/project/bagder/curl
@bagder Could you please re-enable appveyour-ci for Curl organization?

**Comment by bagder** [comment]
Yeah, unfortunately appveyor is really annoying to use for github organizations. I need to create a new appeveyor account for the org, pretending its a new user and it has to use a different email address than my personal email - for no good reason.

**Comment by bagder** [comment]
I've attempted to fix it now, let's see...

**Comment by bagder** [comment]
here: https://ci.appveyor.com/project/curlorg/curl/build/7.47.0.1 

Seems to work now, thanks for pointing it out!
