### ISSUE TITLE
OS400 7.75.0 build broken - missing updated for CURLOPT_AWS_SIG4

### ISSUE THREAD

**Issue by jonrumsey** [curl/curl#6560]
### I did this
Attempted to build 7.75.0 on OS400 V7R2M0 - this failed with;
STRING_LAST(80) is not expected value(79).…curl_easy_setopt_ccsid() in packages/OS400/ccsidcurl.c may need updating if new strings are provided as input via the curl API.…ERROR: CHKSTRINGS failed!

The addition of CURLOPT_AWS_SIG4 under https://github.com/curl/curl/pull/5703 did not have compensating changes to the RPG copybook, ccsidcurl.c and chkstrings.c.

### I expected the following
Clean build.

### curl/libcurl version
7.75.0

### operating system
OS/400 V7R2M0

**Comment by bagder** [comment]
Unfortunately that was expected. There's nobody looking after the OS400 builds and there's no CI builds to verify them either... :cry:
