### ISSUE TITLE
Compile failure with CURL_DISABLE_HTTP_AUTH

### ISSUE THREAD

**Issue by bnason-nf** [curl/curl#6567]
Hi,

When compiling curl-7_75_0 with `CURL_DISABLE_HTTP_AUTH` set, http.c has an error. It looks like this is because the signature of the `Curl_http_output_auth()` function was changed in commit 215db086e09665ee7af9b646ad6c4d6e281001ac for the `#ifndef CURL_DISABLE_HTTP_AUTH` case, but not for the `#else` case.

Thanks,
Benbuck

**Comment by jay** [comment]
Thanks
