### ISSUE TITLE
don't know how to generate "..\src\tool_hugehelp.c"

### ISSUE THREAD

**Issue by oneonce** [curl/curl#6575]
ENV: 
WINDOWS10 + vs2019 Community

Tool:
x86 Native Tools Command Prompt for VS 2019

CMD: 
nmake /f Makefile.vc mode=static VC=14 MACHINE=x86 DEBUG=no

error:
Nmake: fatal error u1073: Don't know how to make ".. src\tool_ hugehelp.c”
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\nmake.exe"": fatal error "0x2"
Stop.

**Comment by jay** [comment]
If you are building curl from git repo then you need to run buildconf.bat, as mentioned in the winbuild [README](https://github.com/curl/curl/blob/master/winbuild/README.md#building-straight-from-git).
