### ISSUE TITLE
Error: Unable to generate src\tool_hugehelp.c

### ISSUE THREAD

**Issue by oneonce** [curl/curl#6584]
when run buildconf.bat, there is a error: Error: Unable to generate src\tool_hugehelp.c

F:\work\open-source\curl\curl-master>buildconf.bat

Generating prerequisite files
* F:\work\open-source\curl\curl-master\Makefile
* F:\work\open-source\curl\curl-master\src\tool_hugehelp.c

Error: Unable to generate src\tool_hugehelp.c

**Comment by jay** [comment]
Did it partially generate it or just not at all? Check if src\tool_hugehelp.c exists, and if so post the contents.

**Comment by oneonce** [comment]
src\tool_hugehelp.c is exists
contents:
`#include "tool_setup.h"
#include "tool_hugehelp.h"

void hugehelp(void)
{
  puts("This is a silly replacement for the actual file.");
}`

**Comment by jay** [comment]
Given that output this is the only place it could fail:
https://github.com/curl/curl/blob/2f33be817cbce6ad7a36f27dd7ada9219f13584c/buildconf.bat#L226-L230

Run these two commands and post the output
~~~
findstr "/C:void hugehelp(void)" src\tool_hugehelp.c
echo %ERRORLEVEL%
~~~

**Comment by bagder** [comment]
@oneonce we need your continued input on this issue, since nobody else sees this.

**Comment by bagder** [comment]
No response

**Comment by erick-thompson** [comment]
I've just run into this issue as well. In my case the file does not exist. Any ideas?

```
findstr "/C:void hugehelp(void)" src\tool_hugehelp.c
FINDSTR: Cannot open src\tool_hugehelp.c
```

**Comment by bagder** [comment]
@erick-thompson when you build from git and after you ran `buildconf.bat` ?

**Comment by erick-thompson** [comment]
I didn't see that - once I ran buildconf.bat it worked correctly. Thanks!
