### ISSUE TITLE
`--retry-all-errors` doesn't retry on 404

### ISSUE THREAD

**Issue by tammersaleh** [curl/curl#6601]
### I did this

``` console
$ curl --head  --max-time 3 --retry 1000 --retry-delay 3 --retry-max-time 10 --retry-all-errors https://superorbital.io/whaever 
```
### I expected the following

I expected curl to retry for 10 seconds and then return 404.  Instead, it returns the initial 404 immediately:

```
HTTP/2 404 
cache-control: public, max-age=0, must-revalidate
content-length: 0
content-type: text/html; charset=utf-8
date: Fri, 12 Feb 2021 22:25:01 GMT
etag: 1504309864-ssl
age: 1
server: Netlify
x-nf-request-id: d34fdd5a-7ad3-414e-931e-87afd5386542-1172095
```

### curl/libcurl version

```
curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
Linux redacted 5.3.0-1032-gcp #34~18.04.1-Ubuntu SMP Tue Jul 14 22:07:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
This is actually working as intended. By default, curl does not consider a 404 a failure so it won't retry on that. You can however tell curl to treat it as an error with `--fail` and then `--retry-all-errors` will retry for this case as well.

**Comment by tammersaleh** [comment]
Ah, thanks - that's working for me!  This might be an opportunity for better documentation, possibly in `curl -h` under `--retry-all-errors`?  I'll close this issue, though, as it sounds like it's working as indended.
