### ISSUE TITLE
Output flag does not work correctly when provided before URL on Windows

### ISSUE THREAD

**Issue by seppestas** [curl/curl#6609]
The --output / -o flag does not seem to work correctly when passed before the URL when downloading a zip archive on Windows, resulting in an archive that can not be opened if passed before the URL.

This is likely a Windows specific bug. I was not able to reproduce this on MacOS.

### I did this

Download a zip file using cURL

```
curl -o cmock.zip https://codeload.github.com/ThrowTheSwitch/CMock/zip/v2.5.3
```

### I expected the following

The cmock.zip file to be a valid zip file. Neither Windows Explorer nor Info-Zip (UnZip 6.00) can open the resulting file.

Error from Info-Zip:

```
Archive:  cmock.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

Interestingly, the following *does work*

```
curl https://codeload.github.com/ThrowTheSwitch/CMock/zip/v2.5.3 -o cmock.zip
```

### curl/libcurl version

curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

Clink v0.4.9 [git:2fd2c2]
Windows Terminal Version: 1.5.10411.0

### operating system

Windows 10 Pro 1909 OS build 18363.1316 [Version 10.0.18363.1316]
MSYS_NT-10.0-18363 [computer name] 3.1.4-340.x86_64 2020-05-19 12:55 UTC x86_64 Msys

**Comment by seppestas** [comment]
Sorry for the inconvenience. This was caused by a mistake in my Makefile, causing the URL to be incorrectly generated.

**Comment by 3F51B5** [comment]
Ok
