### ISSUE TITLE
cmake: superflously defines RANDOM_FILE

### ISSUE THREAD

**Issue by bagder** [curl/curl#6618]
### I did this

Build curl with cmake on Linux. I found that after the cmake invocation, `lib/curl_config.h` contained this line:
~~~c
#define RANDOM_FILE "/dev/urandom"
~~~

### I expected the following

That `RANDOM_FILE` would not be set and instead have the code use the internal defaults. That's what the configure build does.

### curl/libcurl version

current git master as of now (94719e7285bb3)

Reported here: https://github.com/c-ares/c-ares/pull/396#issuecomment-780565678 by @demian51

**Comment by bagder** [comment]
I think I was wrong. The configure build also figures out what file to use to load random from...

**Comment by jzakrzewski** [comment]
I thought it does but I don't understand configure enough...

**Comment by bagder** [comment]
configure checks and adds the define for it if OpenSSL is used, and openssl.c is in fact the only user of the define - and the string is probably not even used there if OpenSSL >= 1.1.0 is used...

Closing this.
