### ISSUE TITLE
test1188 failures in only one appveyor CI configuration

### ISSUE THREAD

**Issue by jay** [curl/curl#6621]
I've noticed a trend of [test1188](https://github.com/curl/curl/blob/curl-7_75_0/tests/data/test1188) failures in a specific configuration on appveyor, it is the 3rd from last:
~~~
Environment: APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2015, BUILD_SYSTEM=autotools, TESTING=ON, DISABLED_TESTS=!19 ~1056 !1233, CONFIG_ARGS=--enable-debug --enable-werror --disable-threaded-resolver --disable-proxy
~~~

1188 is supposed to check the error message for connection refused, but for some reason in this specific configuration it's always connection timed out. Here's an excerpt from today from a PR:

~~~diff
--- log/check-expected	2021-02-18 02:21:55.733575000 +0000
+++ log/check-generated	2021-02-18 02:21:55.733575000 +0000
@@ -1 +1 @@
-0 says 7 Failed to connect to 127.0.0.1 port 47: Connection refused[LF]
+0 says 28 Connection timed out after 300747 milliseconds[LF]
~~~

https://ci.appveyor.com/project/curlorg/curl/builds/37827144/job/seasuoqejsng25c0?fullLog=true#L3895

I usually write these things off as random ci nonsense but I've seen this one quite a few times. Could it be a bug in the test?

**Comment by bagder** [comment]
The test uses the somewhat risky %NOLISTENPORT to trigger a connection failure. But since this test is there to verify `--write-out` variables, I think we can change that error to be a more reliable one and still verify the functionality. I'll create a PR for it in a sec.
