### ISSUE TITLE
AC_HELP_STRING is obsolete in autoconf 2.70

### ISSUE THREAD

**Issue by emilengler** [curl/curl#6647]
### I did this
```
./buildconf
```
[stdout](http://ix.io/2QvV), [stderr](http://ix.io/2QvT)

The stderr starts like this:
~~~
*** Do not use buildconf. Instead, just use: autoreconf -fi
configure.ac:45: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:45: You should run autoupdate.
/usr/local/share/autoconf-2.70/autoconf/general.m4:203: AC_HELP_STRING is expanded from...
m4/curl-confopts.m4:173: CURL_CHECK_OPTION_DEBUG is expanded from...
configure.ac:45: the top level
configure.ac:46: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:46: You should run autoupdate.
/usr/local/share/autoconf-2.70/autoconf/general.m4:203: AC_HELP_STRING is expanded from...
m4/curl-confopts.m4:228: CURL_CHECK_OPTION_OPTIMIZE is expanded from...
configure.ac:46: the top level
configure.ac:47: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:47: You should run autoupdate.
/usr/local/share/autoconf-2.70/autoconf/general.m4:203: AC_HELP_STRING is expanded from...
m4/curl-confopts.m4:386: CURL_CHECK_OPTION_WARNINGS is expanded from...
configure.ac:47: the top level
configure.ac:48: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:48: You should run autoupdate.
/usr/local/share/autoconf-2.70/autoconf/general.m4:203: AC_HELP_STRING is expanded from...
m4/curl-confopts.m4:417: CURL_CHECK_OPTION_WERROR is expanded from...
configure.ac:48: the top level
configure.ac:49: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:49: You should run autoupdate.
~~~

### I expected the following
No obsolete warnings

### curl/libcurl version
fb98a436a74bffa5e65a3c2579ccb9af269f2d10

### operating system
OpenBSD-current, autoconf-2.70, automake-1.16

**Comment by bagder** [comment]
For the moment, I'd advice you to either stick with autoconf 2.69 or do as the warnings suggest: run autoupdate before you run autoconf.

2.70 is claimed to "not able to maintain perfect backward compatibility with existing Autoconf scripts" which of course is terribly annoying if we want to support both newer and older versions.

**Comment by bagder** [comment]
`AC_HELP_STRING` is now [deprecated](https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Obsolete-Macros.html#Obsolete-Macros) but can be replaced with [AS_HELP_STRING](https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Pretty-Help-Strings.html#AS%5fHELP%5fSTRING) - which seems to indicate that this dangerous-looking warning is completely uncalled for.

I guess we should provide a private `AS_HELP_STRING` macro for users of autoconf <= 2.69 and then do the replace.

**Comment by Hemant2000-karens** [comment]
yes, in 2.71, it says same
