### ISSUE TITLE
update manpage to match curl -V features

### ISSUE THREAD

**Issue by adgross** [curl/curl#6677]
The manpage for curl -V list all [available features](https://github.com/curl/curl/blob/24f850f4a49ffd1638f4bfb8b594d8f0bc34ced2/docs/cmdline-opts/version.d#L14-L15) and the available features are listed by [feats array](https://github.com/curl/curl/blob/24f850f4a49ffd1638f4bfb8b594d8f0bc34ced2/src/tool_help.c#L856). Comparing both, the manpage and curl -V output, the manpage don't list:
1. TrackMemory
2. Unicode
3. Kerberos
4. NTLM_WB
5. zstd
6. gsasl

For NTLM, the manpage list NTLM two times, probably one of them was supose to be NTLM_WB.
https://github.com/curl/curl/blob/24f850f4a49ffd1638f4bfb8b594d8f0bc34ced2/docs/cmdline-opts/version.d#L53-L56

Also, the feature "krb4" still listed in manpage, but [is deprecated](https://github.com/curl/curl/blob/master/docs/libcurl/symbols-in-versions#L1031) and is not present in feats array.

**Comment by jay** [comment]
Thanks
