### ISSUE TITLE
heads up on sscanf() requiring quadratic time

### ISSUE THREAD

**Issue by vszakats** [curl/curl#6686]
After reading the article listed as the first reference, I've noticed that curl makes use of `sscanf()` in a few places. After a quick skimming, these places aren't supposed to parse large buffers in most use-cases, but it may still be interesting in corner cases, or just as a general warning of an easy-to-miss performance fallout (or potential for DoS).

Ref: https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/ ([discussion](https://news.ycombinator.com/item?id=26296339))
Ref: https://www.mattkeeter.com/blog/2021-03-01-happen/ ([discussion](https://news.ycombinator.com/item?id=26337046))

**Comment by bagder** [comment]
It seems libcurl uses sscanf() on 24 places right now, but afaik none of those has ever been identified as a bottle neck in performance measurements...

**Comment by vszakats** [comment]
Not wanting to push this, just "raising awarness". If those calls aren't supposed to process larger (say more than a few 100KB) buffers, and those are unlikely to be controlled by a 3rd party, things are alright. I'm guessing it's enough to keep this `sscanf()` propery in mind in the long run and no action to be taken at this point.

Leaving this open for a few days to share thoughts.

**Comment by bagder** [comment]
I suppose some of them *can* be used on really hard input data in edge cases. Like for example the ones in http.c that checks for the beginning of a HTTP response...
