### ISSUE TITLE
smtp-authzid.c example

### ISSUE THREAD

**Issue by snehal2016-dev** [curl/curl#6689]
Got below error:
curl_easy_perform() failed:failed sending data to the peer.
Please tell why this error occur?

**Comment by jay** [comment]
Possibly your server does not support it? Turn on [verbose mode](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html), curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

**Comment by snehal2016-dev** [comment]
Setting  this ,then got 5.7.3 STARTTLS is required to send mail error
Any idea why I get this error

**Comment by jay** [comment]
> 5.7.3 STARTTLS is required

That means the connection must be upgraded to TLS. Try [CURLOPT_USE_SSL](https://curl.se/libcurl/c/CURLOPT_USE_SSL.html): `curl_easy_setopt(curl, CURLOPT_USE_SSL, CURLUSESSL_ALL);`.

**Comment by snehal2016-dev** [comment]
Try this ,
but same error occure

**Comment by bagder** [comment]
@snehal2016-dev so it didn't send a STARTRLS command then? Please provide more information and tell us more about what you do and what your verbose logs show.

Nothing in your report points to an actual curl problem (and this is the curl bug tracker).

**Comment by snehal2016-dev** [comment]
I copy paste  smtp-authzid.c program as it is and did some below changes:
curl_easy_setopt(curl, CURLOPT_URL, "smtp.office365.com:587");

 curl_easy_setopt(curl, CURLOPT_USERNAME, "kurt");  //put my username
    curl_easy_setopt(curl, CURLOPT_PASSWORD, "xipj3plmq");  //put my password

Please check the output i got after execution of program.
(https://user-images.githubusercontent.com/79255492/110067955-b6c91880-7d9a-11eb-9c49-ba0a9b6655af.jpg)

**Comment by jay** [comment]
Did you build libcurl with SSL support? What's your curl_version()? `printf("%s\n", curl_version());`

**Comment by snehal2016-dev** [comment]
libcurl/7.75.0

**Comment by jay** [comment]
Your libcurl is missing SSL support. You'll have to build libcurl with SSL support to communicate with that server.

Also, you publicly posted a password earlier and if that is your real password then you should change it because this is a public tracker and anyone can see it.

**Comment by snehal2016-dev** [comment]
Thanks for your support,i did suggested chages,
now i got another error ==> ssl certification problem:unable to get local issue certificate
Please check the output i got after execution of program.
![output](https://user-images.githubusercontent.com/79255492/110076656-dc5e1e00-7daa-11eb-8aad-e711bd5b3542.jpg)

**Comment by bagder** [comment]
That means libcurl cannot verify the server certificate.

**Comment by jay** [comment]
Please read https://curl.se/docs/sslcerts.html and you can download certificates from https://curl.se/docs/caextract.html. Another option is building libcurl with schannel ssl backend instead of openssl ssl backend, and the OS CA certificates are used.

**Comment by bagder** [comment]
This is not a curl issue.
