### ISSUE TITLE
SFTP keyboard-interactive authentication fails

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#6695]
We see an issue with 7.75.0 when doing SFTP login:

  Trying xxx:22...
Connected to ebibkom.deutschepost.de (xxx) port 22 (#0)
SSH MD5 fingerprint: xxx
SSH authentication methods available: publickey,keyboard-interactive
Authentication failure
Closing connection 0

Same code with older build of library, probably 7.74.0 worked:

  Trying xxx:22...
Connected to ebibkom.deutschepost.de (xxx) port 22 (#0)
SSH MD5 fingerprint: xxx
SSH authentication methods available: publickey,keyboard-interactive
Initialized keyboard interactive authentication
Authentication complete
Connection #0 to host ebibkom.deutschepost.de left intact

Also we see connections simply timing out:

 Trying 192.168.2.235:22...
Connected to 192.168.2.235 (192.168.2.235) port 22 (#0)
SSH MD5 fingerprint: 53d15d36a75a43c7c565df4dc0c22009
SSH authentication methods available: publickey,password,keyboard-interactive
Operation timed out after 30000 milliseconds with 0 out of 0 bytes received
Closing connection 0

Anyone knows about those?

**Comment by MonkeybreadSoftware** [comment]
On my local server, I can login via password and keyboard-interactive.

But if I enable both, I get a timeout.
The timeout is due to libssh2_userauth_keyboard_interactive_ex returning LIBSSH2_ERROR_EAGAIN until we get to our connection timeout after 90 seconds. kbd_callback is not called.

But only if it tried libssh2_userauth_password_ex before. If we configure to not use CURLSSH_AUTH_PASSWORD, the keyboard interactive works and reports correctly the failure.

**Comment by MonkeybreadSoftware** [comment]
We can prevent the libssh2_userauth_keyboard_interactive_ex after libssh2_userauth_password_ex by handling error and then skipping the libssh2_userauth_keyboard_interactive_ex in the lines after libssh2_userauth_password_ex call:

```
      if (rc == LIBSSH2_ERROR_AUTHENTICATION_FAILED)
      {
        infof(data, "Password authentication failed.\n");
        state(data, SSH_AUTH_DONE);
        break;
      }
```

Not sure if such a behavior is much better?

**Comment by jay** [comment]
> The timeout is due to libssh2_userauth_keyboard_interactive_ex returning LIBSSH2_ERROR_EAGAIN until we get to our connection timeout after 90 seconds. kbd_callback is not called.

That sounds like a libssh2 bug?

**Comment by bagder** [comment]
Does the fixing of #6691 change anything?

**Comment by bagder** [comment]
No response, closing as I believe this is already adressed
