### ISSUE TITLE
lib1537.c : check ptr against NULL before dereferencing it

### ISSUE THREAD

**Issue by kokke** [curl/curl#6707]
### I did this

Hi guys,

I am testing a homemade static analysis tool on a few code bases.
I checked out your master-branch and ran my tool and fell over this curiosity, which I think is indicative of a bug.

From [tests/libtest/lib1537.c : 49-51](https://github.com/curl/curl/blob/master/tests/libtest/lib1537.c#L49)

```C
49  ptr = curl_escape((char *)a, asize);
50  printf("%s\n", ptr);
           ^^^^^^^^^^^  'ptr' gets dereferenced here, before the NULL-check
51  if(!ptr) {
52    res = TEST_ERR_MAJOR_BAD;
53    goto test_cleanup;
54  }
```

**Comment by kokke** [comment]
@gvanem AFAIK not all implementations of `printf` output `(null)` given `printf("%s", 0)`.

As far as I am aware, it is undefined behavior (not even just implementation-defined). See e.g. https://trust-in-soft.com/blog/2019/07/09/printing-a-null-pointer-with-s-is-undefined-behavior/

**Comment by kokke** [comment]
Then it seem the issue is non-problematic for you. Thanks for quick response :)

**Comment by jay** [comment]
> 1. we don't use those implementations

https://stackoverflow.com/questions/11589342/what-is-the-behavior-of-printing-null-with-printfs-s-specifier

try it

**Comment by bagder** [comment]
@jay what do you mean? Are you suggesting we build without using our own implementation at times?

**Comment by kokke** [comment]
@bagder is right that many `printf` implementations work around this problem (because it commonly occurs in code) but it is technically undefined behavior.

If you dont care much about UB in test code, that is understandable as well.

**Comment by bagder** [comment]
If we use our printf() implementation where we deal with this perfectly fine (to my knowledge). How can that be UB?

**Comment by kokke** [comment]
@bagder do you use your own `printf` implementation and not the built-in from cstdlib? If so there is no UB and the issue should be closed. The standard specifies UB for the `printf`-implementation from the standard library. My tool thinks all calls to `printf` invoke the standard-implementation. That is often a sound assumption; but apologies for wasting time and energy if that is not the case here :)

**Comment by jay** [comment]
> @jay what do you mean? Are you suggesting we build without using our own implementation at times?

I forgot about that, withdrawn!
