### ISSUE TITLE
Curl not showing response headers/body for 400s/500s statuses

### ISSUE THREAD

**Issue by dhowden** [curl/curl#673]
### I did this

    $ curl -D - -o - google.com/asdfhjashdf
    curl: (22) The requested URL returned error: 404 Not Found

### I expected the following

    HTTP/1.1 404 Not Found
    Date: Mon, 22 Feb 2016 00:41:31 GMT
    Content-Type: text/html
    Server: HTTP server (unknown)
    Content-Length: 49
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN
    
    <html><body><h1>404 Not Found</h1></body></html>

### curl/libcurl version

    curl 7.46.0 (x86_64-apple-darwin15.0.0) libcurl/7.46.0 SecureTransport zlib/1.2.5
    Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
    Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

### operating system

OS X, El Capitan (10.11.3).

**Comment by jay** [comment]
You might have a .curlrc with `--fail` in it. [Please try disabling .curlrc by making the first parameter `-q`](https://curl.haxx.se/docs/manpage.html#-q). It must be the first parameter.
`curl -q -D - -o - google.com/asdfhjashdf`

**Comment by dhowden** [comment]
Perfect, found it!  Thanks.
