### ISSUE TITLE
The order of the request headers

### ISSUE THREAD

**Issue by accountantM** [curl/curl#6732]
Hello @bagder  , @jay
This post is related to [this issue ](https://github.com/curl/curl/issues/3282)

I'm sorry I opened a new issue, this should be a question/feature request.

**Is there any way now we can tell curl to order the headers the way we want ?**

curl (our general-purpose http library) is being blocked now by many websites that implement (a browser/bots fingerprinting) :(
even if the bots are not doing any harmful thing, just because the order of the headers is different from the browser we pretend to be in the user-agent, and of course if we set the user-agent to "curl" we get blocked.

I know the specifications [stated](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) that the order is not significant, that is why a curl user should not be tied to the curl hard-wired header orders.

I hope you guys give this feature another look and give us the ability to order the headers as we want, thank you very much guys for your time, have a good day, bye.

**Comment by jay** [comment]
As @bagder mentioned in that issue, header reordering is in the TODO. My opinion is/was we shouldn't do it. If servers are banning you based on header order that is, as far as I know, highly unusual. I can't think of any other reports like this.

**Comment by bagder** [comment]
We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker. And this idea already there.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get! (Optionally, you can pay someone to work on it and we offer such services at @wolfSSL - see https://curl.se/support.html)
