### ISSUE TITLE
HTTP request timeout with CURLMOPT_MAX_TOTAL_CONNECTIONS set low

### ISSUE THREAD

**Issue by bagder** [curl/curl#6744]
(Issue filed [on behalf of Andrei Bica](https://curl.se/mail/lib-2021-03/0013.html))

I've managed to produce this behavior by using a modified multi-poll.c example (see below) which makes 10 HTTP requests to "example.org:8200", set `CURLOPT_TIMEOUT_MS` to 1000 for each request and
`CURLMOPT_MAX_TOTAL_CONNECTIONS` to 1 for the multi handle.

I've used iptables to drop all packets going to URL address:

    iptables -A OUTPUT -p tcp --destination-port 8200 -j DROP

I would expect the runtime to be around 1000 ms (the value of `CURLOPT_TIMEOUT_MS`), but instead I get a runtime of about 7000 ms.

~~~c
#include <stdio.h>
#include <string.h>

/* somewhat unix-specific */
#include <sys/time.h>
#include <unistd.h>

/* curl stuff */
#include <curl/curl.h>

#define COUNT 10
#define URL "example.org:8200"

int main(void)
{
  CURL *http_handles[COUNT];
  CURLM *multi_handle;
  int still_running = 1; /* keep number of running handles */

  curl_global_init(CURL_GLOBAL_DEFAULT);

  multi_handle = curl_multi_init();
  curl_multi_setopt(multi_handle, CURLMOPT_MAX_TOTAL_CONNECTIONS, 1l);

  for (int i = 0 ; i < COUNT ; i++) {
    http_handles[i] = curl_easy_init();
    curl_easy_setopt(http_handles[i], CURLOPT_URL, URL);
    curl_easy_setopt(http_handles[i], CURLOPT_TIMEOUT_MS, 1000l);
    curl_multi_add_handle(multi_handle, http_handles[i]);
  }

  while(still_running) {
    CURLMcode mc; /* curl_multi_poll() return code */
    int numfds;

    /* we start some action by calling perform right away */
    mc = curl_multi_perform(multi_handle, &still_running);

    if(still_running)
      /* wait for activity, timeout or "nothing" */
      mc = curl_multi_poll(multi_handle, NULL, 0, 100, &numfds);

    if(mc != CURLM_OK) {
      fprintf(stderr, "curl_multi_wait() failed, code %d.\n", mc);
      break;
    }
  }

  for (int i = 0 ; i < COUNT ; i++) {
    curl_multi_remove_handle(multi_handle, http_handles[i]);
    curl_easy_cleanup(http_handles[i]);
  }

  curl_multi_cleanup(multi_handle);
  curl_global_cleanup();

  return 0;
}
~~~

### operating system

Linux

**Comment by bagder** [comment]
Why this happens:

When a connection is moved from the PENDING state (waiting for a connection) it is moved to CONNECT state and the `TIMER_STARTSINGLE` time stamp is set (again).

`Curl_timeleft()` is the function that checks how long time a handle has left until timed out, and "during connect" it will check if the time since TIMER_STARTSINGLE until now is larger than the timeout (or the `CURLOPT_CONNECTTIMEOUT` if that is set).

This has the effect that with `CURLOPT_TIMEOUT` set to 1000ms, it will allow each handle 1000ms to connect after having been moved to CONNECT and when it fails, it will move in the next handle that then also will wait...

I haven't yet really figured out exactly how I think this should be fixed...

**Comment by jay** [comment]
> This has the effect that with `CURLOPT_TIMEOUT` set to 1000ms, it will allow each handle 1000ms to connect after having been moved to CONNECT and when it fails, it will move in the next handle that then also will wait...
> 
> I haven't yet really figured out exactly how I think this should be fixed...

He set an option that limits the number of connections. I don't see the bug, what am I missing?

**Comment by bagder** [comment]
> He set an option that limits the number of connections

That's why the queued transfers are in the PENDING state.

> I don't see the bug, what am I missing?

`CURLOPT_TIMEOUT` is documented to be the max time a transfer is allowed to spend while in the report some of them takes much longer time to get cancelled. I didn't reproduce (yet) but I read the code and it is obvious it can happen as I explained above.

**Comment by jay** [comment]
They take 1000ms to get canceled just not including queue time, and that's the rub, if I understand you correctly.

**Comment by bagder** [comment]
Basically, yes. Which isn't how it is supposed to work. `CURLOPT_TIMEOUT` is meant to include the queue time. The maximum time allowed for a transfer to be "in operation" no matter in which internal state the transfer is or isn't in or transitions through.

I have a local fix I think is decent and very simple. I'll only test it out a little bit more first...

**Comment by mezzatto** [comment]
Should https://github.com/curl/curl/blob/master/tests/unit/unit1303.c have been updated to reflect this change?
