### ISSUE TITLE
curl_multi_socket_action() Deadlock

### ISSUE THREAD

**Issue by zjs604381586** [curl/curl#6752]
### Thread stack：
Thread 21 (Thread 0x7eff883be700 (LWP 31494)):
#0  0x00007eff8fc19c8d in read () from /lib64/libc.so.6
#1  0x00007eff8fba4500 in __GI__IO_file_xsgetn () from /lib64/libc.so.6
#2  0x00007eff8fb98fef in fread () from /lib64/libc.so.6
#3  0x00007eff91334373 in Curl_fillreadbuffer () from /lib64/libcurl.so.4
#4  0x00007eff91334f4f in Curl_readwrite () from /lib64/libcurl.so.4
#5  0x00007eff9133ec3b in multi_runsingle () from /lib64/libcurl.so.4
#6  0x00007eff9133f90a in multi_socket () from /lib64/libcurl.so.4
#7  0x00007eff9133f9f7 in curl_multi_socket_action () from /lib64/libcurl.so.4

Thread 2 (Thread 0x7eff7ebab700 (LWP 3925)):
#0  0x00007eff8fc3689c in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x00007eff8fb990af in _L_lock_55 () from /lib64/libc.so.6
#2  0x00007eff8fb98fca in fread () from /lib64/libc.so.6
#3  0x00007eff91334373 in Curl_fillreadbuffer () from /lib64/libcurl.so.4
#4  0x00007eff91334f4f in Curl_readwrite () from /lib64/libcurl.so.4
#5  0x00007eff9133ec3b in multi_runsingle () from /lib64/libcurl.so.4
#6  0x00007eff9133f90a in multi_socket () from /lib64/libcurl.so.4
#7  0x00007eff9133f9f7 in curl_multi_socket_action () from /lib64/libcurl.so.4

### issue describe：
I have two executors, each executor has a CURLM *_multi inside, so that the request is load balanced, each executor adopts curl+epoll mode

**Comment by bagder** [comment]
Thanks for your report. You have however reported an issue with a curl version that is fairly old and chances are we have fixed your problem already in a more recent version.

We don't have bandwidth or energy to support and debug really old curl versions but we instead request that you upgrade and try to reproduce the problem with a modern curl version instead. Thanks!

**Comment by bagder** [comment]
No response. The problem is probably not present in modern versions.
