### ISSUE TITLE
--create-dirs mode should be more open (that's what umask is for)

### ISSUE THREAD

**Issue by lindes** [curl/curl#6757]
It seems to me that `curl --create-dirs` should create directories with mode 0777, 0775, or 0755 [more below] as modified by the user's umask.  This is what most UNIX utilities do, and is what would be least surprising (notwithstanding people expecting the behavior that curl has long done; see below).  If people want the 0750 permissions that currently get set, they can always set umask to 027.  (The converse, though, isn't the case.  There's no way, with the current code, for a user to specify more relaxed permissions.)  IMHO, merely documenting the behavior (see #4766) is insufficient.  The problem is the actual choice of mode passed to `mkdir(2)`.

An example justification for why this might be important: trying to mirror content to a local cache, served by a web server -- that's running as a different user (and group) as the user running `curl`, the created files aren't able to be served... And (at least with nginx serving the static files) they don't get a 403, but a 404, because the `stat(2)` call fails... so it's not immediately obvious that it's a permissions problem.

If it's deemed to be a major problem to change, because of the what-curl-has-always-done factor, then please consider this a feature request for a `--create-dirs-mode` option or similar, that will be used in place of the 000750 that's [currently used](https://github.com/curl/curl/blob/fbbbf5aae0fe9bb5b57e4ffa9f34ccfd7a6d89d4/src/tool_dirhie.c#L156).

I'm obviously coming in with a certain perspective of what's "right", and of course you're free to disagree with me.  If so, though, it would be nice to hear a justification for why this mode was chosen.  (For example, I can see why SSH would have particular reasons for both setting and checking permissions on `~/.ssh/`.  With curl, though, while certainly some sensitive data _could_ be involved, it hardly seems like that's anything like a given.)

As for the choice between 0777, 0775, and 0755... I did a little bit of wading through [a search](https://github.com/search?l=C&q=mkdir&type=Code), and it seems most things (at least in the first few pages of results) use either 0775 or 0755, which is perhaps enough justification in my mind to excuse something more restrictive than what `mkdir(1)` does by default... though this latter is why I suggested 0777.

### I did this

```
umask 0
curl -o path/to/file.ext --create-dirs http://example.com/some/file.ext
```

(Note: I would normally have my umask at the default 022, or, depending on environment, something more restrictive.  I set it to 0 for this test, to more fully understand what `curl` was doing.)

### I expected the following

* for the `path/` and `path/to/` directories to be mode one of:
    * 0777 (`drwxrwxrwx`)
    * 0775 (`drwxrwxr-x`)
    * 0755 (`drwxr-xr-x`)
* for `path/to/file.ext` to be mode 0666 (`-rw-rw-rw-`)

### But I got the following

* Both `path/` and `path/to/` were mode 0750 (`drwxr-x---`)
* `path/to/file.ext` was indeed mode 0666 (`-rw-rw-rw-`)

### curl/libcurl version

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

### operating system

`Linux [hostname elided] 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

**Comment by bagder** [comment]
As mentioned in #6759, we have not come up with a way to change this without at the same time risking that existing users somehow might get directories created with "wider" restrictions than expected.

**Comment by bagder** [comment]
Closing this as "won't fix". Not because we think the report is wrong, but because we can't think of a clean fix that's worth doing.
