### ISSUE TITLE
Testsuite tests with SSH server were skipped with OpenSSH 7.1p2

### ISSUE THREAD

**Issue by Karlson2k** [curl/curl#676]
Step to reproduce:

0. Make sure that OpenSSH (client and daemon) 7.0 or later is installed
1. Build libcurl for git sources with `configure` and `make`
2. Run `make test-full`.
3. Notice string in final results `TESTINFO: "failed starting SSH server" 56 times (564, 582, 583, 600, 601, 602, 603, 604, 605 and 47 more)`

From ssh_server.log:
````
Connection from 127.0.0.1 port 49934 on 127.0.0.1 port 8999
debug1: Client protocol version 2.0; client software version OpenSSH_7.1p2 Debian-2
debug1: match: OpenSSH_7.1p2 Debian-2 pat OpenSSH* compat 0x04000000
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1p2 Debian-2
debug2: fd 3 setting O_NONBLOCK
debug1: list_hostkey_types: 
No supported key exchange algorithms
debug1: do_cleanup
````
This is from Debian Testing machine. Same problem on Win64/Msys2.
Suspect that reason can be that OpenSSH disabled DSA since version 7.0.

Possibly related PR #675

**Comment by kdudka** [comment]
This is a workaround for the problem I have installed for Fedora builds:

http://pkgs.fedoraproject.org/cgit/rpms/curl.git/commit/?id=e57a7415

I believe we can solve it this way in upstream curl, too.

**Comment by kdudka** [comment]
The fix could be as easy as this:
```
sed -e 's/ds[as]/rsa/g' -i tests/ssh{help.pm,server.pl}
```

**Comment by Karlson2k** [comment]
@kdudka Thanks!

**Comment by patrikhson** [comment]
Hi,

Have you heard the latest news? It's gonna be a pleasant surprise for you, just take a look <http://styburuky.adampalsma.com/xylsum>

Speak to you later, paf@frobbit.se
