### ISSUE TITLE
Locale issue on test1188

### ISSUE THREAD

**Issue by Oumph** [curl/curl#6765]
(very similar to my previous report https://github.com/curl/curl/issues/2436 )

### I did this
I compiled a curl 7.75.0 version, on Debian Buster (to celebrate the 23th birthday and write, in French,  https://linuxfr.org/users/oumph/journaux/compilation-de-curl-7-75-sur-debian-buster ; btw the previous report was related to the 20th birthday...)

(basically the issue is due to the locale fr_FR.UTF-8 during the test)

### I expected the following

```
--- log/check-expected	2021-03-20 18:47:13.380099937 +0100
+++ log/check-generated	2021-03-20 18:47:13.380099937 +0100
@@ -1 +1 @@
-0 says 7 Failed to connect to 127.0.0.1 port 47: Connection refused[LF]
+0 says 7 Failed to connect to 127.0.0.1 port 47: Connexion refusée[LF]
```
 
 # Verify data after the test has been "shot"

Trivial fix:

```
diff -ru curl-7.75.0.old/tests/data/test1188 curl-7.75.0/tests/data/test1188
--- curl-7.75.0.old/tests/data/test1188 2021-02-01 08:16:42.000000000 +0100
+++ curl-7.75.0/tests/data/test1188     2021-03-20 18:55:36.118158381 +0100
@@ -29,6 +29,9 @@
 <command>
 http://%HOSTIP:%NOLISTENPORT/we/want/our/1188 http://%HOSTIP:%HTTPPORT/we/want/our/1188 -w '%{onerror}%{stderr}%{urlnum} says %{exitcode} %{errormsg}\n' -s
 </command>
+<setenv>
+LC_MESSAGES=C
+</setenv>
 </client>
```

### curl/libcurl version

curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux vanta 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux

**Comment by bagder** [comment]
This test has already been modified in git since so it doesn't get that error string anymore. See #6637 (which followed up #6623)

**Comment by Oumph** [comment]
I confirm that the new test works without any extra locale setting. Sorry, I should have checked the git version. Thank you.

**Comment by bagder** [comment]
no worries, thanks for confirming!
