### ISSUE TITLE
Prerequisites for tests: en_US.UTF-8 locale and maybe python-is-python[23] package on Debian/Ubuntu

### ISSUE THREAD

**Issue by Oumph** [curl/curl#6768]
### I did this

I compiled both a curl 7.75.0 version and a fresh git master branch version, on Debian Buster (to celebrate the 23th birthday and write, in French, https://linuxfr.org/users/oumph/journaux/compilation-de-curl-7-75-sur-debian-buster)

### I expected the following

I expected all tests from `make check` to be OK.

I got:
- 10 tests failed due to the lack of `en_US.UTF-8`  locale (I only had en_GB.UTF-8 and fr_FR.UTF-8 at that time). So it should probably be mentioned https://github.com/curl/curl/blob/master/tests/README.md  (the 10 failing tests were  165 448 962 963 964 965 966 967 2046 2047, but a total of 21 tests mention `en_US.UTF-8` locale, according to `grep -lr en_US.UTF-8 tests/data/`).
- another small remark for tests/README.md: on recent Debian/Ubuntu, `python-is-python3` (or `python-is-python2`) may be needed, to avoid "/usr/bin/env: «·python·»: no such file or directory" (3 tests initially failed due to that on my box)
- 41 other tests failing, regarding libssh2 afaik, don't know why yet, but the same tests on 7.75.0 and git master branch

### curl/libcurl version

curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

curl 7.76.0-DEV (x86_64-pc-linux-gnu) libcurl/7.76.0-DEV OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux vanta 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux

**Comment by bagder** [comment]
> 10 tests failed due to the lack of en_US.UTF-8 locale

That's not a known limitation, that's a bug that should be fixed. The tests should either work or be automatically skipped. Please tell us what happens.

> python-is-python3 (or python-is-python2) may be needed

Tests should detect if they can't run and then don't. What happens and/or what do you suggest should be done?

> 41 other tests failing, regarding libssh2 afaik

We to many builds without libssh2 and they don't fail tests normally. You need to elaborate.

**Comment by mback2k** [comment]
I run tests with Python 2.7 and 3 without issues.

**Comment by Oumph** [comment]
Regarding python:  the issue was that "python" was not available as in "/usr/bin/python" and some tests use "env python" to find python. You are perfectly right: it was detected and test were not run. So it is not an "hard" prerequisite, just a way to run more tests.

```
$ grep -r "env python" .
./smbserver.py:#!/usr/bin/env python
./negtelnetserver.py:#!/usr/bin/env python
./util.py:#!/usr/bin/env python
./dictserver.py:#!/usr/bin/env python
$ /usr/bin/env python 
/usr/bin/env: 'python': No such file or directory
$ /usr/bin/env python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
(...)
$ ls -l /usr/bin/python
ls: cannot access '/usr/bin/python': No such file or directory
$ sudo apt install python-is-python3
(...)
$ ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Nov  3 09:20 /usr/bin/python -> python3
```

In https://github.com/curl/curl/blob/master/tests/README.md you explain tests require python and python-impacket. Just mention that python-is-python3 or python-is-python2 may also be useful to test on recent Ubuntu/Debian.

Just to show you that I got 3 extra tests that way (from 1192 tests to 1195):

```
$ make check
(...)
TESTDONE: 1418 tests were considered during 629 seconds.
TESTDONE: 1192 tests out of 1233 reported OK: 96%

TESTFAIL: These test cases failed: 582 600 601 602 603 604 605 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 633 634 635 636 637 638 639 640 641 642 664 665 1446 2004
$ sudo apt install python-is-python3
$ make check
(...)
TESTDONE: 1418 tests were considered during 482 seconds.
TESTDONE: 1195 tests out of 1236 reported OK: 96%

TESTFAIL: These test cases failed: 582 600 601 602 603 604 605 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 633 634 635 636 637 638 639 640 641 642 664 665 1446 2004
```

**Comment by Oumph** [comment]
Regarding the `en_US.UTF-8` locale:

```
$ sudo dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  fr_FR.UTF-8... done
Generation complete.
$ ./runtests.pl 962
********* System characteristics ******** 
* curl 7.76.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.76.0-DEV OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
* Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
* Disabled: 
* Host: vanta
* System: Linux vanta 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux
* OS: linux
* Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 235836
***************************************** 
test 0962...[SMTP without SMTPUTF8 support - UTF-8 based sender (host part only)]

 962: protocol FAILED:
--- log/check-expected	2021-03-21 17:40:34.142579728 +0100
+++ log/check-generated	2021-03-21 17:40:34.142579728 +0100
@@ -1,5 +1,5 @@
 EHLO 962[CR][LF]
-MAIL FROM:<sender@xn--4cab6c.se>[CR][LF]
+MAIL FROM:<sender@åäö.se>[CR][LF]
 RCPT TO:<recipient@example.com>[CR][LF]
 DATA[CR][LF]
 QUIT[CR][LF]

 - abort tests
Killed
TESTDONE: 1 tests were considered during 1 seconds.
TESTDONE: 0 tests out of 1 reported OK: 0%

TESTFAIL: These test cases failed: 962 
```

With a log: "17:40:34.142089 == Info: Failed to convert åäö.se to ACE; could not convert string to UTF-8"
And: "/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)"

Add the locale and test again:

```
$ sudo dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  en_US.UTF-8... done
  fr_FR.UTF-8... done
Generation complete.
 ./runtests.pl 962
********* System characteristics ******** 
* curl 7.76.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.76.0-DEV OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
* Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
* Disabled: 
* Host: vanta
* System: Linux vanta 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux
* OS: linux
* Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 235836
***************************************** 
test 0962...[SMTP without SMTPUTF8 support - UTF-8 based sender (host part only)]
--p-u--e--- OK (1   out of 1  , remaining: 00:00, took 1.075s, duration: 00:01)
Killed
TESTDONE: 1 tests were considered during 1 seconds.
TESTDONE: 1 tests out of 1 reported OK: 100%
```

**Comment by Oumph** [comment]
Regarding the "41 other tests failing, regarding libssh2 afaik", I don't get it for now, I was trying to understand before reporting some hints... The common logs are "= Info: SSH public key authentication failed: Callback returned error" and "Failed publickey for XXXX from 127.0.0.1 port XXX ssh2: RSA SHA256:...." and "curl: (67) Authentication failure". So I believe it's a single one issue.

```
Packages are installed:
libssh2-1:amd64       1.9.0-2
libssh2-1-dev:amd64   1.9.0-2
```

```
curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) **libssh2/1.9.0** nghttp2/1.43.0 librtmp/2.3
curl 7.76.0-DEV (x86_64-pc-linux-gnu) libcurl/7.76.0-DEV OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) **libssh2/1.9.0** nghttp2/1.43.0 librtmp/2.3
```

**Comment by bagder** [comment]
`tests/README.md` lists python as a requirement. Don't python installations usually provide a `python` binary?

The locale problem in test 962 seems to be because yes, it sets the locale to `en_US.UTF-8` and assumes that will work, which then obviously requires that such a local actually exists on the machine. The precheck could probably be improved for that.

**Comment by dfandrich** [comment]
FWIW, through experimentation I found that the "UTF-8" locale (i.e.,
LC_ALL=UTF-8) works in more environments than any other when running
cross-platform tests in another project. If the tests are happy with that
locale, then that would be an easy change to make.

**Comment by Oumph** [comment]
It seems that the not-yet released bullseye from Debian, and the development version sid from Debian have specific packages to provide the symlink /usr/bin/python.
https://packages.debian.org/search?keywords=python-is-python3
bullseye (testing) (python): symlinks /usr/bin/python to python3
sid (unstable) (python): symlinks /usr/bin/python to python3 
https://packages.debian.org/search?keywords=python-is-python2
bullseye (testing) (oldlibs): symlinks /usr/bin/python to the DEPRECATED python2
sid (unstable) (oldlibs): symlinks /usr/bin/python to the DEPRECATED python2 

And apparently the same for Ubuntu since the 20.04:

https://packages.ubuntu.com/search?keywords=python-is-python2
focal (20.04LTS) (oldlibs): symlinks /usr/bin/python to the DEPRECATED python2 [universe]
groovy (20.10) (oldlibs): symlinks /usr/bin/python to the DEPRECATED python2 [universe]
hirsute (oldlibs): symlinks /usr/bin/python to the DEPRECATED python2 [universe] 
https://packages.ubuntu.com/search?keywords=python-is-python3
focal (20.04LTS) (python): symlinks /usr/bin/python to python3
groovy (20.10) (python): symlinks /usr/bin/python to python3
hirsute (python): symlinks /usr/bin/python to python3

**Comment by bagder** [comment]
@dfandrich in #6799 it looks like using plain `UTF-8` doesn't work on FreeBSD... I think I'll instead just document `en_US.UTF-8` as a requirement or something.

**Comment by dfandrich** [comment]
It worked on FreeBSD (Cirrus CI) on my other project. Maybe something has
changed, or maybe the locale is missing something that curl needs. It's too
bad, because I couldn't find another single locale that worked everywhere for
me.
