### ISSUE TITLE
CURLOPT_TIMEOUT default is 1 hour (on TFTP) 

### ISSUE THREAD

**Issue by Togtja** [curl/curl#6774]
### I did this
I used libcurl to download over a very slow (but stable) TFTP link, and it keeps timing out after 3600 seconds aka 1 hour.
Then I set the option to be 0 `curl_easy_setopt(curl, CURLOPT_TIMEOUT, 0L);` it still times out after 3600 seconds.
So I thought it might have to do with the server timing out after 1 hour, but when setting the `CURLOPT_TIMEOUT` to 4000, it times out after 4000 seconds.

I wish to timeout using the stability of the connection aka `CURLOPT_LOW_SPEED_LIMIT` and `CURLOPT_LOW_SPEED_TIME`, both of which are also set
### I expected the following
According to [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) and [CURLOPT_TIMEOUT_MS](https://curl.se/libcurl/c/CURLOPT_TIMEOUT_MS.html) documentation, the default should be 0 and if it is 0 it should never time out

### curl/libcurl version
curl 7.75.0 (Linux) libcurl/7.75.0 OpenSSL/1.1.1g zlib/1.2.11 libssh2/1.9.0_DEV
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets
I also ran this on 7.74.0, same issues
### operating system
Linux tomas-ubuntu 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gvollant** [comment]
#6774 / #6776 introduced windows warning, fix on #6779
