### ISSUE TITLE
Chunked encoding gives output AFTER 'Connection #0 to host xxx left intact'

### ISSUE THREAD

**Issue by EmielBruijntjes** [curl/curl#6784]
### I did this

I gave the following command:
```
curl -v --output - https://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx
```
### I expected the following

I expected to see a response more or less like this:
```
<a lot of binary data>
* Connection #0 to host www.httpwatch.com left intact
```

However, in reality I received this response:
```
<a lot of binary data>
* Connection #0 to host www.httpwatch.com left intact
<even more binary data>
```
It seems like CURL still receives data, _after_ it has considered the connection to be ready / reusable.

### curl/libcurl version

```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

```
Linux xxx 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
Isn't this simply because the verbose output is sent to stderr and the data to stdout?

**Comment by EmielBruijntjes** [comment]
Possible. I honestly don't know whether it is a bug or not. I just found it remarkable and worth mentioning.

**Comment by bagder** [comment]
It's just how you perceive it because the stderr stream shortcuts the stdout stream in the terminal. It's not how the data is actually sent from curl.
