### ISSUE TITLE
security/feature request: read headers from file --header @filename (similar to --cookie or --form)

### ISSUE THREAD

**Issue by arainchik** [curl/curl#679]
This is something that would be useful  when using curl in REST API environments, where authorization information is passed in HTTP Headers

**Issue:**

The only way to pass auth headers is to include them in command line using --header like this

    $ curl --header "Authorization: AWS AWSAccessKeyId:Signature" https://...

Someone else running "ps" command on the same server will be able to see Authorization header. "ps" output is often passed around when troubleshooting issues as well.

**Feature Request:**

If curl will be able to get HTTP headers from the file in the same fashion as it does for cookies of forms, it will improve security, as only the filename will be visible in "ps" output, not the actual headers.

    $ cat headerfile.txt
    Authorization: AWS AWSAccessKeyId:Signature
    $ curl --header @headerfile.txt https://...

or slightly more complicated, similar to --form

    $ cat headerfile.txt
    AWS AWSAccessKeyId:Signature
    $ curl --header "Authorization: @headerfile.txt" https://...

**Comment by bagder** [comment]
Using the [-K/--config option](https://curl.haxx.se/docs/manpage.html#-K) is very close to that functionality. All you need then is to prepend each header with -H.

**Comment by jay** [comment]
Daniel's suggestion  -K/--config works well for this.

**Comment by patrikhson** [comment]
Hi,

I've recently came across some interesting information, what do you thin about it? Please read here and tell me your opinion <http://thofrireka.bitmapcat.com/xyfxjic>

In haste, paf@frobbit.se

**Comment by schnatterer** [comment]
Example: 
`curl.config`:
```
header = "Authorization: AWS AWSAccessKeyId:Signature"
```
`curl  --config curl.config https://...`
