### ISSUE TITLE
Inconsistent cert verification errors returned between TLS 1.2 and 1.3

### ISSUE THREAD

**Issue by c29reid** [curl/curl#6790]
### I did this

Some bad cert cases that failed with `CURLE_PEER_FAILED_VERIFICATION` when using TLS 1.2 are failing with `CURLE_SSL_CONNECT_ERROR` when using TLS 1.3.

```
$ curl https://self-signed.badssl.com/ --verbose --tlsv1.3
*   Trying 104.154.89.105:443...
* TCP_NODELAY set
* Connected to self-signed.badssl.com (104.154.89.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure


$ curl https://self-signed.badssl.com/ --verbose --tls-max 1.2
*   Trying 104.154.89.105:443...
* TCP_NODELAY set
* Connected to self-signed.badssl.com (104.154.89.105) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Another case of this is with `tlsv1 alert unknown ca (SSL_R_TLSV1_ALERT_UNKNOWN_CA)`

### I expected the following

I'm not sure if this error change is intended or not with TLS 1.3.

### curl/libcurl version
```
curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.41.0 librtmp/2.3
Release-Date: 2021-02-03
```

### operating system
Ubuntu 20.10

**Comment by bagder** [comment]
I don't think this report shows the same error. The `self-signed.badssl.com` fails to connect with TLS1.3, so it fails before it even checks the certificate.

**Comment by c29reid** [comment]
Ahh right, it doesn't look like badssl supports TLS 1.3.
I manually set up a self signed site with TLS 1.3 and it is returning CURLE_PEER_FAILED_VERIFICATION with unknown CA as expected.

I'll close this issue. Thanks!

**Comment by c29reid** [comment]
I think I have the core issue I was originally seeing narrowed down some more.
I originally reported it with badssl in hopes it would be easier to repro there.

This error code mismatch I was originally seeing only seems to happen with curl + libressl on TLS 1.3. curl + libressl on TLS 1.2 and curl + OpenSSL is okay.
My last comment where a basic local site serving self generated certs with TLS 1.3 returns `CURLE_PEER_FAILED_VERIFICATION` was only true for curl + OpenSSL.

When switching to curl with libressl on TLS 1.3 it returns `CURLE_PEER_FAILED_VERIFICATION`:
```
$ curl https://localhost:443 --verbose --tlsv1.3
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
Client sending ClientHello
Client receiving ServerHello
Client recv returned -3
Client receiving ServerHello
Client receiving EncryptedExtensions
Client receiving CertificateRequest
* error:1404B418:SSL routines:ST_CONNECT:tlsv1 alert unknown ca
* Closing connection 0
curl: (35) error:1404B418:SSL routines:ST_CONNECT:tlsv1 alert unknown ca
```

I'm not sure the reasoning but libressl with TLS 1.3 first pushes `SSL_R_TLSV1_ALERT_UNKNOWN_CA` on the error list [here](https://github.com/openbsd/src/blob/master/lib/libssl/tls13_lib.c#L150).
Then later on `SSL_R_CERTIFICATE_VERIFY_FAILED` gets pushed on the error list.
So when curl gets the top error `SSL_R_TLSV1_ALERT_UNKNOWN_CA` is returned instead of the expected `SSL_R_CERTIFICATE_VERIFY_FAILED` since `SSL_R_TLSV1_ALERT_UNKNOWN_CA` is the top error.

I'm guessing this is a libressl issue and not a curl issue though so I can keep this ticket closed.
