### ISSUE TITLE
Specified TLSv1.3 but the first two lines of output (Client Hello and Server Hello) are TLSv1.2

### ISSUE THREAD

**Issue by D4v1dH03** [curl/curl#6796]
### I did this
Run the command `curl -vL https://google.com --tlsv1.3"
However the output is as follows:
```
curl -vL https://google.com --tlsv1.3
*   Trying 142.251.33.110:443...
* Connected to google.com (142.251.33.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
```
### I expected the following
Using TLSv1.3 throughout all the handshake process
### curl/libcurl version
`curl 7.76.0-DEV (x86_64-pc-linux-gnu) libcurl/7.76.0-DEV`
[curl -V output]
```
curl 7.76.0-DEV (x86_64-pc-linux-gnu) libcurl/7.76.0-DEV BoringSSL zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) nghttp2/1.44.0-DEV quiche/0.7.0 libgsasl/1.8.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz Metalink NTLM NTLM_WB PSL SSL UnixSockets zstd
```
### operating system
`Linux fedora 5.11.9-300.fc34.x86_64 #1 SMP Wed Mar 24 12:06:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jay** [comment]
I can't reproduce that here, maybe it's specific to BoringSSL.

~~~
curl 7.75.0 (x86_64-pc-linux-gnu) libcurl/7.75.0 OpenSSL/1.1.1i zlib/1.2.8 nghttp2/1.43.0 librtmp/2.3
curl 7.76.0-DEV (i386-pc-win32) libcurl/7.76.0-DEV OpenSSL/1.1.1j nghttp2/1.43.0
~~~

**Comment by D4v1dH03** [comment]
Well. I have no other way :-( because the GnuTLS build is broken, and OpenSSL has deferred to support QUIC even in OpenSSL 3 alpha

**Comment by D4v1dH03** [comment]
But it is impossible to alter the TLS version after `Server Hello`

**Comment by jay** [comment]
The code is pretty straightforward. If BoringSSL tells us the first handshake messages are TLS1_2_VERSION there's nothing we can do about that. Also TLS 1.3 uses 1.2 in the client and server version fields for compatibility.
https://github.com/curl/curl/blob/2f33be817cbce6ad7a36f27dd7ada9219f13584c/lib/vtls/openssl.c#L2077-L2112

**Comment by bagder** [comment]
> Well. I have no other way :-( because the GnuTLS build is broken

except of course that we build that successfully for every commit in the CI setup...

> and OpenSSL has deferred to support QUIC even in OpenSSL 3 alpha

There's also the MS/Akamai openssl fork as an option: https://github.com/quictls/openssl

**Comment by D4v1dH03** [comment]
Since it is not a bug can I close this now?
