### ISSUE TITLE
SMTP feature request: add option to exit during points in transaction

### ISSUE THREAD

**Issue by jootuom** [curl/curl#680]
I often use curl for debugging purposes since you can get the raw protocol dialog with the -v option which is really convenient.

For SMTP, it would be really convenient to be able to stop the transaction at specific points to avoid actually sending emails during testing (or when only testing specific things). Currently that doesn't seem to be possible? It would be awesome to have an option that allows you to make curl end the transaction at specific points.

SWAKS is a tool for debugging SMTP and it provides this option.

I'll just quote its [manual](http://www.jetmore.org/john/code/swaks/latest/doc/ref.txt) for the specific breakpoints:

    -q, --quit-after [stop-point]
    Point at which the transaction should be stopped. When the requested
    stopping point is reached in the transaction, and provided that
    swaks has not errored out prior to reaching it, swaks will send
    "QUIT" and attempt to close the connection cleanly. These are the
    valid arguments and notes about their meaning.
    
    CONNECT, BANNER
        Terminate the session after receiving the greeting banner from
        the target.
    
    FIRST-HELO, FIRST-EHLO, FIRST-LHLO
        In a STARTTLS (but not tls-on-connect) session, terminate the
        transaction after the first of two HELOs. In a non-STARTTLS
        transaction, behaves the same as HELO (see below).
    
    XCLIENT
        Quit after XCLIENT is sent
    
    TLS Quit the transaction immediately following TLS negotiation. Note
        that this happens in different places depending on whether
        STARTTLS or tls-on-connect are used. This always quits after the
        point where TLS would have been negotiated, regardless of
        whether it was attempted.
    
    HELO, EHLO, LHLO
        In a STARTTLS or XCLIENT session, quit after the second HELO.
        Otherwise quit after the first and only HELO.
    
    AUTH
        Quit after authentication. This always quits after the point
        where authentication would have been negotiated, regardless of
        whether it was attempted.
    
    MAIL, FROM
        Quit after MAIL FROM: is sent.
    
    RCPT, TO
        Quit after RCPT TO: is sent.

Could this be added into curl?

**Comment by jay** [comment]
I think that's probably better suited for your debugger. It is possible though, there is a function [`state`](https://github.com/curl/curl/blob/curl-7_47_1/lib/smtp.c#L308-L336) in smtp.c which is called after a command is sent. Function [`smtp_perform_starttls`](https://github.com/curl/curl/blob/curl-7_47_1/lib/smtp.c#L394-L405) is an example of how the state is changed. So you could hook in state and then wait for the command. If it's `COMMAND` then that's a custom command like `VRFY, EXPN, NOOP, RSET and HELP` but it should default to `VRFY` if there's recipients or `HELP` if there's none.

**Comment by bagder** [comment]
Ideas are rarely the problem, implementations and how to provide it in a usable manner to users are.

Also, since you quote a tool that does exactly this already I'm not seeing the reason why curl would implement the same thing? I'm no @jay's side here. 

No response in months, so I'm closing.

**Comment by patrikhson** [comment]
Hello, I've got something new for you, you'll definetely love it, take a look at <http://thecryspyvy.morganwilk.com/xydig>

Best wishes, paf@frobbit.se
