### ISSUE TITLE
LDAP segfaults on non-tls connections

### ISSUE THREAD

**Issue by bagder** [curl/curl#6804]
This time it segfaults on non-tls connections :-( Should be
```
     if(li->ld) {
+      if(conn->ssl[FIRSTSOCKET].use) {
         Sockbuf *sb;
         ldap_get_option(li->ld, LDAP_OPT_SOCKBUF, &sb);
         ber_sockbuf_add_io(sb, &ldapsb_tls, LBER_SBIOD_LEVEL_TRANSPORT, data);
+      }
       ldap_unbind_ext(li->ld, NULL, NULL);
       li->ld = NULL;
     }
```

_Originally posted by @monnerat in https://github.com/curl/curl/issues/6787#issuecomment-808818947_

**Comment by monnerat** [comment]
Thanks for commit :-)

**Comment by monnerat** [comment]
Needs a follow-up again :-(
If ldaps is used, `conn->ssl[FIRSTSOCKET].use` is set even if the negotiation failed.
This again causes a segfault in `ldap_disconnect().`
I suggest to replace:
`      if(conn->ssl[FIRSTSOCKET].use) {`
by:
`      if(li->recv) (`
in the sequence above.
This will make sure the ldapsb stuff is executed only if it has been installed.
