### ISSUE TITLE
Segmentation fault while performing curl_easy_perform.

### ISSUE THREAD

**Issue by rahul233343** [curl/curl#6823]
### I did curl_easy_perform on Curl * by setting up the parameters using curl_easy_setopt.
But after that i received segmentation fault. Below are stack trace 
#8  0x00007f95893da80d in poll () at ../sysdeps/unix/syscall-template.S:84
#9  0x00007f958af2e513 in Curl_poll () from /home/user1/pre/curl/build/lib/libcurl.so
#10 0x00007f958af25769 in curl_multi_wait () from /home/user1/pre/curl/build/lib/libcurl.so
#11 0x00007f958af1b9f7 in easy_transfer () from /home/user1/pre/curl/build/lib/libcurl.so
#12 0x00007f958af1bcc8 in easy_perform () from /home/user1/pre/curl/build/lib/libcurl.so
#13 0x00007f958af1bd2f in curl_easy_perform () from /home/user1/pre/curl/build/lib/libcurl.so
#14 0x0000000000821562 in makePrivateRequest (this=0x27719d0) at /home/user9/session.cpp:684

It was working fine from the start of the feature. 
And after some time it worked fine. Is it an issue with server?

### I expected result in sResult field.
curl_easy_setopt(curl, CURLOPT_WRITEDATA, &sResult);

### curl/libcurl version 7.47.0

[curl -V output]

**Comment by dfandrich** [comment]
That's not how CURLOPT_WRITEDATA works. I suggest reading the documentation
more closely and looking at one of the example programs to see how to use it.
Please also direct questions about the libcurl API to the curl-library mailing
list.

**Comment by bagder** [comment]
No response, user mistake. Closing.

**Comment by rahul233343** [comment]
I am using the CURLOPT_WRITEDATA as per documentation and my application is working fine. But on that day it crashed with above mentioned stack trace. I am just confirming whether this may be from the server side or not. so that i inquire from server team.

**Comment by dfandrich** [comment]
What you write above isn't according to the documentation. Feel free to post
your code to the curl-library mailing list for more detailed help.
