### ISSUE TITLE
Compile failure in hostip.c without USE_CURL_ASYNC

### ISSUE THREAD

**Issue by bnason-nf** [curl/curl#6831]
Hi,

When building the latest curl (7.76.0) without asynchronous name resolution (`USE_CURL_ASYNC` is undefined), hostip.c fails to compile because the `failf()` call references the `async` member which doesn't exist. Probably this whole function can be omitted in this scenario.

Thanks,
Benbuck

**Comment by jay** [comment]
I can reproduce this but only if the DNS backend is synchronous and DOH is disabled. See #6832

**Comment by bnason-nf** [comment]
Hi @jay,

I appreciate the quick response, and yes, our configuration is probably pretty unusual. I think maybe it would be good to add the same ifdef to Curl_resolver_error() in hostip.h for consistency?

Thanks,
Benbuck

**Comment by jay** [comment]
Thanks
