### ISSUE TITLE
Compile failure in curl_ntlm_core.c with OPENSSL_NO_DES

### ISSUE THREAD

**Issue by bnason-nf** [curl/curl#6833]
Hi,

With the latest release of curl (7.76.0), curl_ntlm_core.c doesn't compile when `OPENSSL_NO_DES` is set because it references DES types in several places. I'm guessing this isn't a scenario that is intended to be supported, so maybe `USE_CURL_NTLM_CORE` shouldn't be enabled when DES is disabled like this? This issue may have existed in previous versions, but I think this was broken for my configuration in commit 33ba0ecf482302b9906d9f6c4c1ab4fb2b2a3ef3. That commit enables `USE_CURL_NTLM_CORE` now where instead it used to disabled when `CURL_DISABLE_NTLM` was set. 

Thanks,
Benbuck

**Comment by jay** [comment]
How do you build? Did you have CURL_DISABLE_NTLM defined somewhere?

**Comment by bnason-nf** [comment]
Hi @jay,

Yes, prior to the 7.76.0 release, we had CURL_DISABLE_NTLM defined. I see that I can achieve the same thing by defining CURL_DISABLE_CRYPTO_AUTH, even though it's not as granular, so I have started doing that now. With that change, this isn't an issue for me. but I thought you might like to be aware of the incompatibility when disabling DES.

Thanks,
Ben

**Comment by bagder** [comment]
Generally, we cannot make libcurl work with all OpenSSL's build combinations and don't try to. They're just too many special purpose ones.

**Comment by bnason-nf** [comment]
Hi @bagder,

Fair enough, I'll close this then.

Thanks,
Benbuck
