### ISSUE TITLE
File opening in browser but not downloading

### ISSUE THREAD

**Issue by marekkowalczyk** [curl/curl#6837]
### I did this

```
$ curl -o siec.png https://static1.squarespace.com/static/55c247fce4b0c477e3227a33/t/5714c1222fe13107b62146aa/1460977971611/Zasady+zarządzania+przepływem+wg+Goldratta

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

$ ls -lh

-rw-r--r--   1 marekkowalczyk  staff     0B Apr  2 08:18 siec.png
```
### I expected the following

File `siec.png` downloaded, not empty.

### curl/libcurl version

```
curl 7.67.0 (x86_64-apple-darwin18.7.0) libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.1.1)
Release-Date: 2019-11-06
```

### operating system

```
Darwin MKO.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
```

**Comment by jay** [comment]
It's empty because the location is redirected and you haven't enabled following redirects by using the [-L option](https://curl.se/docs/manpage.html#-L).

**Comment by marekkowalczyk** [comment]
Thank you. As a regular user I would appreciate an error message rather than a silent fail with an empty file.

**Comment by jay** [comment]
HTTP code 3xx is not considered an error. If following redirects is disabled then curl will download whatever content is in the 3xx response.

**Comment by marekkowalczyk** [comment]
IMHO creating an empty file rather than emitting some kind of a message is a misleading result. It is *not* the case that there is an empty file at the given URL --- but I still get it without any warning that it's not the requested resource.

**Comment by jay** [comment]
The file is empty because the response had no content, so it is technically correct. I suggest use both -L and [-f](https://curl.se/docs/manpage.html#-f) to get the behavior you want downloading files.
