### ISSUE TITLE
How to create package with c-ares support?

### ISSUE THREAD

**Issue by MaximKiselev** [curl/curl#684]
Hi, i want to create deb from deb-src `http://ftp.debian.org/ testing main contrib nonfree`
curl 7.47 this is latest package.
If i edit debian/rules and add flag --enable-ares and after run dpkg-buildpackage. Curl build, but library not supports ares.
Do you have the detailed manual for this? Thanks! 
libc-ares-dev installed

**Comment by bagder** [comment]
Debian packaging is done by the Debian project, not the curl project, so for questions around that this isn't the suitable place.

If you run configure with --enable-ares, the result summary at the end should mention it uses c-ares. if it does not, you can investigate your config.log to see details on what exactly failed in the check for c-ares.

**Comment by MaximKiselev** [comment]
@bagder, big thanks. i found problem. problem was with choosing the resolve of dns .
