### ISSUE TITLE
Why i not might send JSON in UTF-8 code? In windows CMD

### ISSUE THREAD

**Issue by bottookku** [curl/curl#6855]
i send this request `curl https://api.powerbi.com/v1.0/myorg/datasets/8d642b7a-3220-4029-12da-75a0c2f369e6/tables/%D0%9F%D0%97/rows -H "Content-Type: application/json" -d "{\"rows\":[{\"Название КУ\":\"sex\",\"Деньги\": 1331}]}" -v -H "Authorization: Bearer asllmkwepsd"`.
I try change codepage UTF-8 from CMD windows.. chcp 65001 but it not help. i try copy curl command from Notepad++ with codepage utf-8 but it not help

I can correct send request from file -d @11.json, but i want send request only from CMD without file..

This command correct send from linux, but Windows is not correct codepage sending.

![3333](https://user-images.githubusercontent.com/15849878/113729351-e79dc400-9731-11eb-84f3-85c024f86099.png)
this method work only windows 10+, i want on all windows and it not stable betta testing

**Comment by bagder** [comment]
curl sends whatever you pass to it. It makes no conversions or translations of the content. I don't know how to make "cmd" use and accept UTF-8.

**Comment by bottookku** [comment]
\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\
OEMCP = 65001

**Comment by bottookku** [comment]
\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage\
OEMCP = 65001
