### ISSUE TITLE
HTTP/2 not supporting after upgrading to 7.76

### ISSUE THREAD

**Issue by kiran-gupta** [curl/curl#6858]
### I did this
Upgrade curl from 7.75 to 7.76
### I expected the following
HTTP/2 support will continue 
### curl/libcurl version

[curl -V output]
curl 7.76.0 (x86_64-redhat-linux-gnu) libcurl/7.76.0 NSS/3.44 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.9.0 nghttp2/1.21.1
Release-Date: 2021-03-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL UnixSockets

### operating system

Linux xxxxxxxxx.com 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Eariler in version 7.75 it showing HTTP/2 but now after upgrading it shows the following:

$ curl -I   https://nghttp2.org/
**HTTP/1.1 200 OK**
Date: Wed, 07 Apr 2021 07:41:50 GMT
Content-Type: text/html
Last-Modified: Tue, 02 Feb 2021 11:41:51 GMT
Etag: "60193a7f-19d8"
Accept-Ranges: bytes
Content-Length: 6616
X-Backend-Header-Rtt: 0.001031
Strict-Transport-Security: max-age=31536000
Server: nghttpx
Via: 2 nghttpx
alt-svc: h3-29=":443"; ma=3600
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

**Comment by bagder** [comment]
Duplicate of #6825 sort of.
Fixed by #6827
