### ISSUE TITLE
curl "-H key: value" yields " key: value" in headers for http1.x (leading space)

### ISSUE THREAD

**Issue by weltonrodrigo** [curl/curl#6866]
### I did this
`curl --http1.1 -v -H "Authorization: Bearer 1234123-4123412" https://httpbin.org/bearer` yeilds: 
```
> GET /bearer HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer 1234123-4123412
> 
< HTTP/1.1 200 OK
```

`curl --http1.1 -v "-H Authorization: Bearer 1234123-4123412" https://httpbin.org/bearer` yields: 

```
> GET /bearer HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.64.1
> Accept: */*
>  Authorization: Bearer 1234123-4123412
> 
< HTTP/1.1 401 UNAUTHORIZED
```
**Note the space before `Authorization`**

Also:

`curl --http1.1 -v "--header Authorization: Bearer 1234123-4123412" https://httpbin.org/bearer `
```
curl: option --header Authorization: Bearer 1234123-4123412: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

Same is true for `--http1.0` but not for `--http2`.

### I expected the following
Not sure what would be the best, to make "-H key:value" yield the correct header or reject it at all like "--header key:value" does.

### curl/libcurl version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

### operating system

Darwin <REDACTED> 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
When you put the quotes *before* `-H` you make the initial space part of the provided string. Ie: you asked for this to happen. The fix; don't ask for what you don't want. Put the quotes before the header name instead.
