### ISSUE TITLE
Random - timed out before SSL handshake

### ISSUE THREAD

**Issue by adnan-kamili** [curl/curl#6870]
We are using libcurl in one of our apps. When we run lot of instances of our app which send POST requests to our server, some of the instances randomly fail with following error (network timeout set in code is 30s):

```
*   Trying 51.11.*****...
* TCP_NODELAY set
* Connected to api.***.***.io (51.11.2***) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: ignoring value of ssl.verifyhost
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* timed out before SSL handshake
* Closing connection 0
Network error: Timeout was reached
Time taken for network request: 4.47s
```

And most of them succeed succeed:

```
*   Trying 51.11.*.*...
* TCP_NODELAY set
* Connected to api.*.*.io (51.11.*.*) port 443 (#0)
* warning: ignoring value of ssl.verifyhost
*   CAfile: none
  CApath: none
* skipping SSL peer certificate verification
* ALPN, server accepted to use http/1.1
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=api.*.*.io
* 	start date: Apr 06 11:56:39 2021 GMT
* 	expire date: Jul 05 11:56:39 2021 GMT
* 	common name: api.*.*.io
* 	issuer: CN=R3,O=Let's Encrypt,C=US
```

This happens randomly and when system is low on memory. Any guidance you can provide on this?

Curl options we set:

```
curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);  //30 seconds
curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10L);  //10 seconds
curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 3L);  // max redirects 3
curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
curl_easy_setopt(curl, CURLOPT_FORBID_REUSE, 1L);
curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, ResponseWriter);
curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
curl_easy_setopt(curl, CURLOPT_SSL_OPTIONS, CURLSSLOPT_ALLOW_BEAST | CURLSSLOPT_NO_REVOKE);
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
```

We recently added `curl_easy_setopt(curl, CURLOPT_FORBID_REUSE, 1L); `assuming it may be caused due to a lot of open connections, but didn't help.

### curl/libcurl version
libcurl v7.58.0

### operating system

CentOS 7

**Comment by bagder** [comment]
This looks like something very early on in that process (setting up TLS) takes a long time, can you add timestamps to the log output or something?

Also note that your curl version is fairly old by now and you're using a TLS backend that is more or less abandoned by the rest of the world: NSS.

**Comment by adnan-kamili** [comment]
The log is generated by libcurl verbose option, so I don't know how to add a timestamp to the curl log. 

Do you want me to update to the latest version and see if it replicates?

We can't use openssl as it causes many compatibility issues across different Linux operating systems. The single version of NSS works almost everywhere on Linux.

**Comment by bagder** [comment]
> The log is generated by libcurl verbose option, so I don't know how to add a timestamp to the curl log.

If you use `CURLOPT_DEBUGFUNCTION` instead to output the verbose messages it is easy to add a timestamp. [debug.c](https://curl.se/libcurl/c/debug.html) is an example using that option.

> Do you want me to update to the latest version and see if it replicates?

That would be highly interesting, yes!

**Comment by adnan-kamili** [comment]
I tried compiling the latest version but get following issue when enabling https:

`checking for SSL_VersionRangeSet in -lnss3... no`

**Comment by bagder** [comment]
My guess: you have more than one NSS installation in your system and configure finds the other one.

**Comment by adnan-kamili** [comment]
Got the compilation working by installing the `libnss3-dev` package. After compiling the latest version of curl, and replacing the old version with the new version, now it can no more connect to our server. We get the following error:

```
* Trying 51.*.*.*:443...
* Connected to api.***.***.io (51.*.*.*) port 443 (#0)
* warning: ignoring value of ssl.verifyhost
*  CAfile: none
*  CApath: none
* NSS error -12190 (SSL_ERROR_PROTOCOL_VERSION_ALERT)
* Peer reports incompatible or unsupported protocol version.
* Closing connection 0
Network error: SSL connect error
libcurl v7.76.0
Time taken for network request: 0.00s
```

The only change was replacing libcurl v7.58.0 with v7.76.0

**Comment by bagder** [comment]
The differences in the verbose output between your original libcurl and this new build seem to indicate unintended differences, don't they? Did you really build the second version exactly like the first one was?

**Comment by adnan-kamili** [comment]
Yes, we have the build script in the GitHub repository which we always use to build the libcurl. Here is the command:

```
CPPFLAGS="-I/usr/include/nspr" ./configure --prefix=$PWD/build/libcurl3 --with-nss --without-ssl --with-pic --disable-ftp --disable-file --disable-ldap --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-ares --disable-debug  --disable-rtmp  --without-librtmp --without-zlib --without-libidn --disable-shared

make

make install
```

**Comment by bagder** [comment]
> * Initializing NSS with certpath: sql:/etc/pki/nssdb

This doesn't seem to happen now?

> * loaded libnssckbi.so

... and this sounds like a rather notable change?

**Comment by adnan-kamili** [comment]
We used the same OS (Debian 7) as well as the same command for compilation. Can you suggest what can be the issue? Can the issue be with CenOS 7 where the app is failing now.

**Comment by adnan-kamili** [comment]
Here is the log when the app runs on Debian 9, so I guess the issue seems to be some missing lib in CentOS 7. But the problem is if the old libcurl works fine on CentOS 7 then why the latest version fails. We won't be able to release our library with this issue as it will be a breaking change.

*   Trying 54.*.*.93:443...
* Connected to api.*.* (54.*.*.93) port 443 (#0)
* Initializing NSS with certpath: none
* WARNING: failed to load NSS PEM library libnsspem.so. Using OpenSSL PEM certificates will not work.
* warning: ignoring value of ssl.verifyhost
*  CAfile: none
*  CApath: none
* loaded libnssckbi.so
* skipping SSL peer certificate verification
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
* 	subject: CN=cryptlex.com
* 	start date: Mar 28 00:00:00 2021 GMT
* 	expire date: Apr 26 23:59:59 2022 GMT
* 	common name: *.com
* 	issuer: CN=Amazon,OU=Server CA 1B,O=Amazon,C=US

**Comment by bagder** [comment]
I don't think I have enough information to tell what's going on and as I cannot reproduce this issue I can't figure it out either. If I were you, I'd work on reproducing the issue against a publicly accessible URL so that others can assist better.

**Comment by adnan-kamili** [comment]
Here is a publicly accessible URL for which it replicates on CentOS 7:

https://api.licensing.rsds.io/v3/status

**Comment by bagder** [comment]
What's "it" in this context?

So it only fails on CentOS 7 and not on other Linux distros? And you build libcurl and NSS yourself with the same version for all distros?

**Comment by adnan-kamili** [comment]
Some more investigation, it fails on CentOS as well as Debian if the server supports

TLS 1.3 and TLS 1.2 only.

If the server supports TLS 1.0 through 1.3 then it works with older as well as newer verision. But the older library works for all and newer library doesn't work.

**Comment by jay** [comment]
Take a wireshark capture of the success and fail cases to https://api.licensing.rsds.io/v3/status and we'll take a look. Use a capture filter for only that problem host. Note the capture may contain mac addresses, ip addresses, etc.

**Comment by adnan-kamili** [comment]
I don't have experience with Wireshark, but I will try if I can get something. 

One more info, I tried using the libcurl 7.76.0 build on ubuntu:latest docker image and it always fails with the error (even if the server supports TLS 1.0 through TLS 1.3)

```
* Trying 54.*.*.93:443...
* Connected to api.*.com (54.*.*.93) port 443 (#0)
* Initializing NSS with certpath: none
* WARNING: failed to load NSS PEM library libnsspem.so. Using OpenSSL PEM certificates will not work.
* NSS error -12168 (SSL_ERROR_INVALID_VERSION_RANGE)
* SSL version range is not valid.
* Closing connection 0
Network error: SSL connect error
```

**Comment by bagder** [comment]
I just built curl with NSS on Debian and this worked fine:
~~~
$ curl https://api.licensing.rsds.io/v3/status 
{"status":"Healthy","version":"3.40.2"}
$ curl -V
curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV NSS/3.63 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 c-ares/1.17.1 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) nghttp2/1.43.0 librtmp/2.3 libgsasl/1.10.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TrackMemory UnixSockets zstd

**Comment by adnan-kamili** [comment]
I am sorry, but due to time constraints we decided to drop nss altogether and switch to a new SSL backend. We tried mbedTLS and it still timed out in few cases though the frequency was less:

success:

```
* Trying 51.11.2*.*:443...
* Connected to api.*.*.io (51.11.26.143) port 443 (#0)
* Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed
* mbedTLS: Connecting to api.*.*.io:443
* mbedTLS: Set min SSL version to TLS 1.0
* mbedTLS: Handshake complete, cipher is TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
* Dumping cert info:
* cert. version     : 3
****
* SSL connected
```

failed:

```
* Trying 51.*.*.143:443...
* Connected to api.*.*.io (51.*.*.143) port 443 (#0)
* Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed
* mbedTLS: Connecting to api.*.*.io:443
* mbedTLS: Set min SSL version to TLS 1.0
* Operation timed out after 10103 milliseconds with 0 out of 0 bytes received
* Closing connection 0
Network error: Timeout was reached
libcurl v7.76.0
Time taken for network request: 2.49s
```

**Comment by jay** [comment]
There's nothing there that indicates a curl problem.

**Comment by adnan-kamili** [comment]
Thanks for confirming. So is it a server issue or the client machine is over loaded? What is your best guess?

**Comment by jay** [comment]
> Thanks for confirming. So is it a server issue or the client machine is over loaded? What is your best guess?

I don't have a best guess here, it could be either of those things.

**Comment by adnan-kamili** [comment]
Ok thanks @bagder and @jay  for your valuable time.

**Comment by adnan-kamili** [comment]
Hi,

We are again facing this issue on some machines, this time with mbedTLS SSL backend on Linux (Ubuntu). On one machine this always fails with an SSL Timeout issue. But if we use the system curl to make the same request it succeeds. So, I suspect some issues with the SSL backend.

You can download the Wireshark dump from the link below. For the machines where it works and where it doesn't work.

https://www.dropbox.com/s/eaaa8vxs4f9h7wy/tcp_dump.zip?dl=0

**Comment by bagder** [comment]
With a new backend and probably even another curl version, this is not the same bug. Please create a new one and submit all the details we need to understand and reproduce.,
