### ISSUE TITLE
Certain mime attachments are truncated

### ISSUE THREAD

**Issue by dansebcar** [curl/curl#6872]
### I did this

I'm using libcurl in a C application which sends a multipart/mixed message with 155-byte and 2239-byte multipart/alternative body texts, and a 45118-byte attachment over SMTP.

Under these circumstances, the attachment becomes truncated to 44889 bytes. I've extracted (and anonymised) the relevant parts of my application into one file, which resembles the smtp-mime example:

```c
#include <curl/curl.h>
#include <glib.h>

GString* get_body(gsize size)
{
	GString* body = g_string_new(NULL);
	for (gsize i = 0; i < size; i++) {
		g_string_append_c(body, 'a');
	}
	return body;
}

int main(void)
{
	CURL* curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(curl, CURLOPT_URL, "smtp://smtp.sendgrid.net");
	curl_easy_setopt(curl, CURLOPT_USERNAME, "apikey");
	curl_easy_setopt(curl, CURLOPT_PASSWORD, API_KEY);
	curl_easy_setopt(curl, CURLOPT_MAIL_FROM, FROM_ADDR);

	struct curl_slist* recipients = NULL;
	recipients = curl_slist_append(recipients, TO_ADDR);
	curl_easy_setopt(curl, CURLOPT_MAIL_RCPT, recipients);

	struct curl_slist* headers = NULL;
	g_autoptr(GDateTime) now = g_date_time_new_now_utc();
	g_autofree gchar* date = g_date_time_format(now, "Date: %a, %d %b %Y %T %z");
	headers = curl_slist_append(headers, date);
	headers = curl_slist_append(headers, "From: " FROM_ADDR);
	headers = curl_slist_append(headers, "To: " TO_ADDR);
	headers = curl_slist_append(headers, "Subject: curl_mime_test");
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

	curl_mime* mime = curl_mime_init(curl);
	curl_mime* body_alt = curl_mime_init(curl);
	curl_mimepart* part = NULL;
	GString* body = NULL;

	part = curl_mime_addpart(body_alt);
	body = get_body(2239);
	curl_mime_type(part, "text/html; charset=\"UTF-8\"");
	curl_mime_encoder(part, "base64");
	curl_mime_data(part, body->str, body->len);

	part = curl_mime_addpart(body_alt);
	body = get_body(155);
	curl_mime_type(part, "text/plain; charset=\"UTF-8\"");
	curl_mime_encoder(part, "base64");
	curl_mime_data(part, body->str, body->len);

	part = curl_mime_addpart(mime);
	curl_mime_type(part, "multipart/alternative");
	curl_mime_subparts(part, body_alt);
	struct curl_slist* body_headers = curl_slist_append(NULL, "Content-Disposition: inline");
	curl_mime_headers(part, body_headers, 1);

	part = curl_mime_addpart(mime);
	curl_mime_type(part, "application/gzip");
	curl_mime_encoder(part, "base64");
	curl_mime_filedata(part, "attachment");
	curl_mime_filename(part, "a");

	curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);

	CURLcode res = curl_easy_perform(curl);
	curl_easy_cleanup(curl);

	return (int)res;
}
```

I don't think it matters which bytes form the attachment, I can reproduce the issue with 45118 null bytes (`dd if=/dev/zero of=attachment bs=45118 count=1`).

When I use `CURLOPT_DEBUGFUNCTION` to look at the protocol data corresponding to the attachment, I see the character 'A' 59852 times. That decodes to the null byte 44889 times, so I'm certain the attachment is truncated before it leaves my application.

### I expected the following

That the attachment would be 45118 bytes on receipt.

### curl/libcurl version

```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system

debian buster
Linux D001234 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

### additional information

The truncation is the same when I replace the call to `curl_mime_filedata` with the equivalent call to `curl_mime_data`.

I've tested several attachment sizes. Everything I've tested smaller than 44889 bytes is not truncated. Everything I've tested between 44889 and 45118 bytes becomes truncated to 44889 bytes. However, everything I've tested larger than 45208 bytes (inclusive) is not truncated at all.

I suspect that there is some range of attachment sizes, contained within the range between 44889 and 45208 bytes, within which the attachment becomes truncated to 44889 bytes.

The size of the mime parts preceding the attachment are relevant. For example, if I shrink the body parts to 2230 and 150 bytes respectively, the 45118 byte attachment is instead truncated to 44922 bytes. For a different example, if I name the attachment "aaaaa" instead of "a", it is truncated to 44886 bytes.

I'm happy to tinker with these ranges further, if that would be useful.

**Comment by bagder** [comment]
@monnerat does this ring any bells? I know we've fixed a few things since this version...

**Comment by monnerat** [comment]
> does this ring any bells?

Not at all. But I must say a lot of things changed around it with commit ed0f357f.
That said, I can't reproduce even with 7.64.0.

**Comment by bagder** [comment]
@dansebcar could you perhaps first try the latest libcurl version to see if you can still reproduce this issue?

**Comment by dansebcar** [comment]
@bagder sure. The script above delivers the full attachment without truncation under debian bullseye, which currently provides:

```
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

I bulk-checked attachment sizes between 100 and 200,000 bytes (in increments of 100) using a modified script which uploads one file over http. I didn't see any truncation on bullseye, so I think this issue has already been fixed since curl 7.64.

---

In case anyone else is curious about the issue, here is what I found using the modified script:

```c
#include <curl/curl.h>

int main(int argc, char** argv)
{
	CURL* curl = curl_easy_init();
	curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:5000");

	struct curl_slist* headers = NULL;
	headers = curl_slist_append(headers, "Expect:");
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

	curl_mime* mime = curl_mime_init(curl);
	curl_mimepart* part = NULL;

	part = curl_mime_addpart(mime);
	curl_mime_type(part, "application/gzip");
	curl_mime_encoder(part, "base64");
	curl_mime_filedata(part, "atmt");
	curl_mime_name(part, "atmt");

	curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);

	CURLcode res = curl_easy_perform(curl);
	curl_easy_cleanup(curl);

	return (int)res;
}
```

These attachment sizes lead to truncation with curl 7.64:

attachment size | truncated to
-- | --
47800 - 48000 | 47763
95700 - 95900 | 95652

Other attachment sizes between 100 and 200,000 bytes are not affected.

Also I observed that when the attachment is truncated, less bytes are delivered than specified in the Content-Length header, in proportion to the amount truncated.

**Comment by bagder** [comment]
Thanks for the added details. Then since this issue seems to already be fixed in later versions we can close this, can't we?

**Comment by dansebcar** [comment]
Indeed. Cheers!
