### ISSUE TITLE
Problem with variables on OS Windows

### ISSUE THREAD

**Issue by nahimov** [curl/curl#6877]
Hello!

curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

I have problem with variables on Windows OS. When a variable is used in a request like %Var1%, they did not understand, when i use at linux like $variable, the work well. Is it possible to fix it, because on all latest version of Windows curl are work.

Thank you!

**Comment by bagder** [comment]
What variables? Please show us what doesn't work.

**Comment by nahimov** [comment]
like example i want to update DynamicDNS by API at one of the service site, first of all I must understand what ip address i have, we can use some of site to understant it, like example "curl http://ifconfig.co", this string return our real ip address, we can use variable to set this ip to string update like: curl -H "PddToken: SDFLKJSLKFJEIJFSIRGIOJFSNEVIEONFSIROJOISRGIOSJECSONRVSUONRVUSRUVNSV" -d "domain=MYDOMAIN.COM&record_id=35590034&subdomain=NAMEPC&ttl=21600&content=IPADDRESS" "https://pddimp.yandex.ru/api2/admin/dns/edit" So if we want create automatic script, we must use variable at ...content=IPADDRESS" So at Linux we use variable like $Variable and work well, but in Windows we can use only like %Variable%, and curl did not understand this.

**Comment by bagder** [comment]
Those variables are done and handled by the shell, not by curl. curl does not even know you use variables because it just gets the contents. This is not a curl issue.

**Comment by nahimov** [comment]
please tell me how to write correctly

C:\Users\Mr.Hunt>set var1=curl http://ifconfig.co

C:\Users\Mr.Hunt>**%var1%**
5.5.5.5

C:\Users\Mr.Hunt>curl -H "PddToken: DFKGJDSFKLJGDSFKGJSDLFKGJSDLKFGJSLDKFJGSLKDFJGLKDSFJGDLFKG" -d "domain=instation.ru&record_id=316464617&subdomain=dell&ttl=21600&co
ntent=**%var1%**" "https://pddimp.yandex.ru/api2/admin/dns/edit"
**{"error": "bad_content", "domain": "instation.ru", "success": "error"}**
C:\Users\Mr.Hunt>
C:\Users\Mr.Hunt>curl -H "PddToken: DFKGJDSFKLJGDSFKGJSDLFKGJSDLKFGJSLDKFJGSLKDFJGLKDSFJGDLFKG" -d "domain=instation.ru&record_id=316464617&subdomain=dell&ttl=21600&co
ntent=**5.5.5.5**" "https://pddimp.yandex.ru/api2/admin/dns/edit"
**{"record_id": 31790017, "record": {"content": "5.5.5.5", "record_id": 31790017, "fqdn": "dell.instation.ru", "ttl": 21600, "domain": "instation.ru", "priority":
 "", "subdomain": "dell", "type": "A"}, "domain": "instation.ru", "success": "ok"}**

I'll try to use '' and "" and have no luck, i don't know why.....

**Comment by nahimov** [comment]
Please tell me how to write correctly then

because when i insert variable set var1=curl http://ifconfig.co

**Comment by nahimov** [comment]
Thank you!
