### ISSUE TITLE
compiler warning when building C++ application

### ISSUE THREAD

**Issue by abzh423** [curl/curl#6883]
```
// CheckerTest.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <cstdio>
#include <iostream>
#include <curl/curl.h>
using namespace std;

int main(void)
{
	CURL* curl;
	CURLcode res;
	// init the conditions
	curl_global_init(CURL_GLOBAL_ALL);
	// init the handle or session
	curl = curl_easy_init();
	// check if it returns NULL smth's wrong
	if (curl) 
	{
		curl_easy_setopt(curl, CURLOPT_URL, "https://vk.com./");
		curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "name=abc&surname=abc");
		res = curl_easy_perform(curl);
		if (res != CURLE_OK)
		{
			cout << "The curl_easy_perform respond with error" << endl;
		}
		curl_easy_cleanup(curl);
	}
	curl_global_cleanup();
}

```
causes error on my machine, i specified everything right. 
Error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26812	The enum type 'CURLcode' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	CheckerTest	C:\Users\abuka\source\repos\CheckerTest\CheckerTest.cpp	12	
```

Thx in advance.

**Comment by bagder** [comment]
1. That's a warning, not an error
2. libcurl provides a C header and a C API, not a C++ one

What are you suggesting we can do about this?

**Comment by bagder** [comment]
I claim this is an overzealous compiler. I advice you switch off that warning in your compiler, at least for (external) C headers such a curl. I don't think this is a curl issue.

**Comment by jzakrzewski** [comment]
You should probably define curl headers as "external" to your project (equivalent of -isystem on gcc). See: https://devblogs.microsoft.com/cppblog/broken-warnings-theory/ for some details. Otherwise you could disable warnings for the 3-party headers you include for example like that:
```
#pragma warning(push, 0)
#include <curl/curl.h>
#pragma warning(pop)
```

**Comment by MarcelRaad** [comment]
This is not even a compiler warning. curl headers are clean from compiler warnings with MSVC. This warning is from the C++ Core Guidelines Checker. As the C++ Core Guidelines mostly don't apply to C, you can disable it with the instructions here: https://docs.microsoft.com/en-us/cpp/code-quality/using-the-cpp-core-guidelines-checkers?view=msvc-160#macros.

**Comment by bagder** [comment]
Thank you @jzakrzewski and @MarcelRaad for the additional details. I hereby consider this issue closed.
