### ISSUE TITLE
ngtcp2 + gnutls fails to connect h3: "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by bagder** [curl/curl#6896]
It looks like boringssl backed server does not like ClientHello generated by GnuTLS.  It is hard for me to debug this because it is TLS internal stuff.

Similar to #6864 but this only happens with GnuTLS builds now.

_Originally posted by @tatsuhiro-t in https://github.com/curl/curl/issues/6864#issuecomment-819625790_

**Comment by tatsuhiro-t** [comment]
It looks like GnuTLS sends legacy session ID which must be prohibited in QUIC: https://tools.ietf.org/html/draft-ietf-quic-tls-34#section-8.4
Now I have to find how to make GnuTLS stop sending this.
Meanwhile it seems that OpenSSL does not check this thing out, which smells like a bug.

**Comment by tatsuhiro-t** [comment]
@ueno Is there any way to tell GnuTLS to disable TLSv1.3 compatibility mode?

It looks like `#undef TLS13_APPENDIX_D4` disables it, but it is a compile time option.

**Comment by ueno** [comment]
Not currently, but it should be easy to add. I've filed an issue at:
https://gitlab.com/gnutls/gnutls/-/issues/1208

**Comment by bagder** [comment]
I'm going to close this issue here since this has been determined to be a GnuTLS bug and it isn't very useful for us to keep it open here as well. This should work with curl once GnuTLS is fixed to do right.
