### ISSUE TITLE
When building with static openssl libs, can't build curl executable

### ISSUE THREAD

**Issue by jade2k11598** [curl/curl#6902]
### I did this
I'm trying to build a (mostly) statically linked curl such that it's linked to static openssl libs and static libcurl.  So I passed the following cmake options:
```
cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jade/thirdParty/curl-release -DOPENSSL_INCLUDE_DIR=/home/jade/thirdParty/openssl-release/include -DOPENSSL_CRYPTO_LIBRARY=/home/jade/thirdParty/openssl-release/lib/libcrypto.a -DOPENSSL_SSL_LIBRARY=/home/jade/thirdParty/openssl-release/lib/libssl.a -Dpkgcfg_lib__OPENSSL_crypto=/home/jade/thirdParty/openssl-release/lib/libcrypto.a -Dpkgcfg_lib__OPENSSL_ssl=/home/jade/thirdParty/openssl-release/lib/libssl.a ..
```
But when attempting to build, it fails to link the curl executable:
```
/usr/bin/cc  -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wfloat-equal -Wsign-compare -Wundef -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wvla -Wdouble-promotion -Wno-long-long -Wno-multichar -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -O3 -DNDEBUG   CMakeFiles/curl.dir/slist_wc.c.o CMakeFiles/curl.dir/tool_binmode.c.o CMakeFiles/curl.dir/tool_bname.c.o CMakeFiles/curl.dir/tool_cb_dbg.c.o CMakeFiles/curl.dir/tool_cb_hdr.c.o CMakeFiles/curl.dir/tool_cb_prg.c.o CMakeFiles/curl.dir/tool_cb_rea.c.o CMakeFiles/curl.dir/tool_cb_see.c.o CMakeFiles/curl.dir/tool_cb_wrt.c.o CMakeFiles/curl.dir/tool_cfgable.c.o CMakeFiles/curl.dir/tool_convert.c.o CMakeFiles/curl.dir/tool_dirhie.c.o CMakeFiles/curl.dir/tool_doswin.c.o CMakeFiles/curl.dir/tool_easysrc.c.o CMakeFiles/curl.dir/tool_filetime.c.o CMakeFiles/curl.dir/tool_formparse.c.o CMakeFiles/curl.dir/tool_getparam.c.o CMakeFiles/curl.dir/tool_getpass.c.o CMakeFiles/curl.dir/tool_help.c.o CMakeFiles/curl.dir/tool_helpers.c.o CMakeFiles/curl.dir/tool_homedir.c.o CMakeFiles/curl.dir/tool_hugehelp.c.o CMakeFiles/curl.dir/tool_libinfo.c.o CMakeFiles/curl.dir/tool_main.c.o CMakeFiles/curl.dir/tool_metalink.c.o CMakeFiles/curl.dir/tool_msgs.c.o CMakeFiles/curl.dir/tool_operate.c.o CMakeFiles/curl.dir/tool_operhlp.c.o CMakeFiles/curl.dir/tool_panykey.c.o CMakeFiles/curl.dir/tool_paramhlp.c.o CMakeFiles/curl.dir/tool_parsecfg.c.o CMakeFiles/curl.dir/tool_progress.c.o CMakeFiles/curl.dir/tool_strdup.c.o CMakeFiles/curl.dir/tool_setopt.c.o CMakeFiles/curl.dir/tool_sleep.c.o CMakeFiles/curl.dir/tool_urlglob.c.o CMakeFiles/curl.dir/tool_util.c.o CMakeFiles/curl.dir/tool_vms.c.o CMakeFiles/curl.dir/tool_writeout.c.o CMakeFiles/curl.dir/tool_writeout_json.c.o CMakeFiles/curl.dir/tool_xattr.c.o CMakeFiles/curl.dir/__/lib/strtoofft.c.o CMakeFiles/curl.dir/__/lib/nonblock.c.o CMakeFiles/curl.dir/__/lib/warnless.c.o CMakeFiles/curl.dir/__/lib/curl_ctype.c.o CMakeFiles/curl.dir/__/lib/curl_multibyte.c.o CMakeFiles/curl.dir/__/lib/version_win32.c.o CMakeFiles/curl.dir/__/lib/dynbuf.c.o  -o curl ../lib/libcurl.a -ldl -lpthread /home/jade/thirdParty/openssl-release/lib/libssl.a /home/jade/thirdParty/openssl-release/lib/libcrypto.a /usr/lib/x86_64-linux-gnu/libz.so
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1a4): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x262): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x2d2): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x349): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x382): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x431): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x499): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x662): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
src/CMakeFiles/curl.dir/build.make:798: recipe for target 'src/curl' failed
make[2]: *** [src/curl] Error 1
```
I notice that the ordering of libs in the linking line (as shown above), the `dl` library is not in the correct order for static linking of curl.  It should be placed **_after_** the openssl libs `/home/jade/thirdParty/openssl-release/lib/libssl.a /home/jade/thirdParty/openssl-release/lib/libcrypto.a /usr/lib/x86_64-linux-gnu/libz.so
/home/jade/thirdParty/openssl-release/lib/libcrypto.a` instead of before it.

I verified this by editing `src/CMakeLists.txt` such that line 100 is changed from
```
#Build curl executable
target_link_libraries(${EXE_NAME} libcurl ${CURL_LIBS})
```
to 
```
#Build curl executable
target_link_libraries(${EXE_NAME} libcurl ${CURL_LIBS} dl)
```
adding dl after the list of `${CURL_LIBS}` and the builds passes, successfully linking a (mostly) statically linked curl.

I'm not suggesting that line 100 of `src/CMakeLists.txt` necessarily needs to be updated as such, but the way `${CURL_LIBS}` is appended, it would be best to put libs such as `dl` and `pthread` to be appended at the end of that list (which should work for both static or dynamic linking).

### I expected the following
I expected the build to pass (e.g. curl should have linked fine)

### curl/libcurl version

This was from git tag branch `curl-7_76_1`

### operating system

Linux 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jay** [comment]
Is that a normal way to link static OpenSSL?

**Comment by jade2k11598** [comment]
I'm not sure what you're asking here.  It's a way of linking curl with a static OpenSSL libs.  This Openssl lib was locally built (didn't want to pick up what's installed on the OS since our software wants to have better control over what version it links to, not subject what ever is installed on an OS).

I'm can only pass in the locations of the openssl includes/libs based on the cmake options that were provided in the curl repo (as noted in the cmake command I noted in the 1st post).

The problem here is, how the top level CMakeLists appends the `${CURL_LIBS}`.  For a static build to work, the ordering of libraries when linking is important.  Since openssl lib has a dependency on `dl` and `pthread` libs, it's best to put those low level libs at the of the list of libraries.

**Comment by jay** [comment]
Would you have that problem if had you used OPENSSL_ROOT_DIR? [FindOpenSSL.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake) is supposed to account for dl and pthread isn't it?

**Comment by jzakrzewski** [comment]
I suspect CMake version before 3.16. It seems that the code that handles adding the threads and DL dependencies in FindOpenSSL.cmake landed in 3.16.

**Comment by bagder** [comment]
Related: https://github.com/moparisthebest/static-curl/ by @moparisthebest

**Comment by gshaotianguo** [comment]
Same problem using config make, but building the lib succeed. How can I build the lib only without executable?

**Comment by jade2k11598** [comment]
@gshaotianguo add `-DBUILD_CURL_EXE=OFF` as a cmake argument to not build the executable.

@jay so I tried using that`OPENSSL_ROOT_DIR`:
```
cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jade/thirdParty/curl-release -DOPENSSL_ROOT_DIR=/home/jade/thirdParty/openssl-release ..
```
But doesn't work because all it does is specify the directory but won't specify to link against the STATIC lib of openssl and not the dynamic.  As shown by the linker it's picking up the dynamic libs of openssl:
```
 -o curl -Wl,-rpath,/home/jade/thirdParty/openssl-release/lib: ../lib/libcurl.a -ldl -lpthread /home/jade/thirdParty/openssl-release/lib/libssl.so /home/jade/thirdParty/openssl-release/lib/libcrypto.so /usr/lib/x86_64-linux-gnu/libz.so 
make[2]: Leaving directory '/home/jade/thirdParty/curl/build'
```
I'm trying to get a static build of curl linked against a specific static version of openssl.  

Now I did look at `FindOpenSSL.cmake` and it did sample this variable `OPENSSL_USE_STATIC_LIBS`, so I passed that parameter as ON in my cmake parameters:
```
cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jade/thirdParty/curl-release -DOPENSSL_ROOT_DIR=/home/jade/thirdParty/openssl-release -DOPENSSL_USE_STATIC_LIBS=ON ...
```
So with that parameter set on, it is linking against the static openssl libs, but it seems that (at least my version of cmake 3.12) `FindOpenSSL.cmake` still has the ordering wrong, failing the build:
```
-o curl ../lib/libcurl.a -ldl -lpthread /home/jade/thirdParty/openssl-release/lib/libssl.a /home/jade/thirdParty/openssl-release/lib/libcrypto.a /usr/lib/x86_64-linux-gnu/libz.so 
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x1a4): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x262): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x2d2): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x349): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x382): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x431): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x499): undefined reference to `dlerror'
/home/jade/thirdParty/openssl-release/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x662): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
```
Since `FindOpenSSL.cmake` doesn't seem to set the ordering of the libraries together (someone should file a bugfix to cmake on that), I think the best thing to do in the meantime is edit `src/CMakeLists.txt` at line 100 and add that `dl` at the end of that library listing.  But only add it if `dl` is available on the machine.

**Comment by jzakrzewski** [comment]
As I have written before - the thread and dl dependecies are added by CMake first in CMake 3.16, so I suspect it'll work if you update your CMake. 
That being said we should probably work this around.

**Comment by jade2k11598** [comment]
@jzakrzewski I don't necessarily have the luxury of upgrading the CMake version since this has to run on our build machines (long story but required by company).  One would have to go through a lot of bureaucracy to just get them to upgrade the CMake version ...

**Comment by jzakrzewski** [comment]
It has only been a comment to you suggesting opening a bug on CMake side. I know the pain of not being able to upgrade certain things all too well...

**Comment by jay** [comment]
> That being said we should probably work this around.

Maybe? I don't think we should have to be responsible for static dependencies. If the user's pkgconfig / etc provides it then great. It is interesting that dl and pthread are used beforehand though. My solution to this is the user updates their cmake, but I'm not against other solutions.

**Comment by bagder** [comment]
> I don't think we should have to be responsible for static dependencies.

Agreed. It's a never-ending race that can't be won and will change over time and between platforms.

**Comment by bagder** [comment]
Building with static dependencies will continue to put the burden on the person doing the build to provide and specify the set of extra libraries necessary for the exact build they're doing.
