### ISSUE TITLE
curl sftp much slower than openssh sftp

### ISSUE THREAD

**Issue by ctheune** [curl/curl#6903]
### I did this

`curl -v -k sftp://a.nice.ip.ihave/tmp/ -u "<myuser>:" -T <a13gibfile>`

and I came out with only around 3MiB/s transfer speed.

### I expected the following

Full saturation of bandwidth. This is a WAN link from a VM with 1G uplink on the host and 10g in the data center, none of the links are saturated. I could perform full end-to-end link saturation with various tools (iperf to the host, the router and various endpoints behind the WAN) and also with SCP and the openssh SFTP utility.

### curl/libcurl version

```
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1k zlib/1.2.11 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

but also 7.61.1 and 7.76.1 all compiled against the same dependencies.

### operating system

`Linux ... 5.4.108 #1-NixOS SMP Wed Mar 24 10:26:46 UTC 2021 x86_64 GNU/Linux`

and 

`Linux ... 4.4.91 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`

### Other notes

I already went through the issue tracker and mailing list archives and found various indications over time that SFTP (upload) speed has had issues in various situations every now and then but was never properly resolved. One aspect appears to be the way that the max write size needs to be set and this seems to be a trade-off with shared code for other protocols.

As I spend a while debugging this and am currently recommending my customer to leverage OpenSSHs SFTP/SCP as an alternative I'd suggest to not necessarily spend more time fixing this issue but maybe documenting the situation for posterity to avoid others having to debug this again and again. Maybe a warning in the documentation and a bit more clarification here about why it is the way it is would be helpful.

Big thanks and love!

**Comment by bagder** [comment]
SFTP is a complicated protocol to get good performance out of. In general you can compensate for that for with libcurl by increasing the buffer sizes (`CURLOPT_UPLOAD_BUFFERSIZE` for uploads) and it would be interesting to see how curl compares with (much) larger buffers.

Another option could be to try the other SSH backends to see how they compare speed-wise, as libssh2 is just one of the three different libraries curl supports for SFTP.

Other than that, development and debugging efforts would need to get invested to boost performance even further.

I don't think curl's comparably worse performance warrants a warning.

**Comment by ctheune** [comment]
Thanks for picking this up!

AFAIK CURLOPT_UPLOAD_BUFFERSIZE is a compile time option and people have reported success by increasing it before but it's quite inflexible and previous discussions showed that you'd like to keep this small.
OpenSSH has moved their buffer size from 16k (IIRC) to 1MiB and is achieving linespeed on at least 1G interfaces.

We are seeing > 400mbit/s+ in real world WAN scenarios with OpenSSH's SCP and SFTP. Getting only 8mbit/s from the same setup with curl was dramatic enough that I had to investigate the issue and didn't find this well-documented. 8mbit to 400mbit means curl is performing at only 2% of OpenSSH and I don't think people would suspect curl to be the issue here. We started investigating this as a network issue and only when nothing else was left over I started digging into curl ... I'd appreciate if you would reconsider your stance on adding a warning (or an information) here.

I'm not sure whether just simply making the CURLOPT_UPLOAD_BUFFERSIZE more flexible and use a bigger buffer if you're doing SFTP is viable - I don't have a deeper understanding of the curl code right now ... At least previously I understood that just generally increasing that option is not something you'd like to do.

Hugs!

**Comment by ctheune** [comment]
Note that my mbit/s statements are a bit conflicting as shown above: we used to get around 30-40mbit/s (~4MiB/s) and saw a sharp dropoff to 8mbit/s recently which triggered the investigation. 30-40mbit/s was not ideal but feasible and we switched to SCP now as 8mbit/s was not feasible any longer.

I understand that curl is a "swiss army knife" tool and swiss army knives might never be the best for any specific job, but they give you lots of options and that's what makes them cool!

**Comment by bagder** [comment]
> AFAIK CURLOPT_UPLOAD_BUFFERSIZE is a compile time option and people have reported success by increasing it before but it's quite inflexible and previous discussions showed that you'd like to keep this small.

We've also not had the conversation in a long time, plus we changed how we handle upload buffers ilibcurl since we had it last: now they're allocated on demand which means that transfers without uploads still have 0 bytes upload buffers instead of wasting that memory. I think that could be reasons to reconsider what buffer size curl could set by default if we can assume a big enough performance increase.

It's never too late to improve.

> OpenSSH has moved their buffer size from 16k (IIRC) to 1MiB and is achieving linespeed on at least 1G interfaces.

There are of course also many more factors than just buffer size. It's also a matter of exactly how the buffer is used, and libcurl is more limited there as we have an API and ABI that we cannot break that limits what we can do - which OpenSSH does not so they can in fact also use their buffer in a better/more SFTP-friendly way than we can.

> We are seeing > 400mbit/s+ in real world WAN scenarios with OpenSSH's SCP and SFTP.

SCP is an entirely different beast. It should be much easier to make perform good without requiring super huge buffers.

> Getting only 8mbit/s from the same setup with curl was dramatic enough that I had to investigate the issue and didn't find this well-documented. 8mbit to 400mbit means curl is performing at only 2% of OpenSSH and I don't think people would suspect curl to be the issue here.

I'm not convinced that difference is typical or to be expected for average use cases either.

**Comment by ctheune** [comment]
Alright then - thanks for your thought's! I'm fine with leaving this discussion here for now without adding to anyone's maintenance effort for now.

I've put OpenSSH's SCP/SFTP in the same basket as I they both performed equally in my tests. 

I'm happy if we're the absolute edge case here and not this issue will serve as a reminder for other's if they stumble upon it. Happy if you close it as I don't have the mental bandwidth currently to offer a patch.

**Comment by bagder** [comment]
Thanks for all the feedback.

There's certainly room for improving SFTP and SCP performance in curl and one easy first step would be to experiment how just increasing buffer sizes can help - and if so, what we should do by default going forward. There's no practical reason why curl and libcurl cannot perform these transfers at a similar speed as openssh can, but it will take some work and dedication to make it happen.

As I don't think this issue has any particular points left to act on right now, I close it.
