### ISSUE TITLE
CMake build with MIT Kerberos does not work since 7.71

### ISSUE THREAD

**Issue by jzakrzewski** [curl/curl#6904]
Minimum CMake version has been bumped in curl 7.71.0 (#5358)
Since CMake 3.2 `try_compile` started respecting the `CMAKE_EXE_FLAGS`. 
The code dealing with MIT Kerberos detection sets few variables to potentially weird mix of space, and `;`-separated flags. It had to blow up at some point. All the CMake checks that involve compilation are doomed from that point, the configured tree cannot be built.

I intend to fix it but I'm short on time at the moment, so filing the issue so it won't be forgotten.

Example of what's not working:
```cmake ../curl-$VERSION -DCMAKE_PREFIX_PATH:PATH=$PREFIX_DIR -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_USE_GSSAPI=ON -DGSS_ROOT_DIR=$PREFIX_DIR -G Ninja ```

**Comment by bagder** [comment]
@jzakrzewski should we instead add a mention to the `KNOWN_BUGS` document and close this for now?

**Comment by jzakrzewski** [comment]
I'm really sorry that I have no time to fix properly (I have a very dirty fix in the scripts I use in my company's product but I won't even propose such an abomination here). I have in my head that this is something to work on but the earliest I could invest any time is probably when we update to the new version.
So I guess you could add it to `KNOWN_BUGS` for now. :(
