### ISSUE TITLE
Curl does memory leak with specific characters

### ISSUE THREAD

**Issue by mobines96** [curl/curl#6914]
### I did this
 Hi im doing request with curl library in c++ but the server response contains Characters like this string
The string : ¥ò▲ƒ♠▀Å♀p0☻♦4═< ïù≥₧♠¥/♂▄á0▼¶↕¢I½ë↨½♀╖du²├J╝
and it cause memory leak i think curl_easy_cleanup method cannot free them from memory
im here to find fix of this issue. Thanks

 //CleanUp
	curl_easy_cleanup(curl); // Curl Handle
	curl_slist_free_all(chunk); //curl_slist
 //End CleanUp
### I expected the following
no memory leak
### curl/libcurl version
curl 7.76.1
### operating system
Windows 10

**Comment by bagder** [comment]
Can you please provide a full example source code that leaks memory for you?

**Comment by mobines96** [comment]
Here is the Example Source Code ->


       size_t CurlWrite_CallbackFunc_StdString(void* contents, size_t size, size_t nmemb, std::string* s)
              {
	        size_t newLength = size * nmemb;
        	try
        	{
 		s->append((char*)contents, newLength);
         	}
	        catch (std::bad_alloc& e){
	       	return 0;
         	}
	         return newLength;
               }


                CURL* curl_handle = curl_easy_init();
	        struct curl_slist* postchunk = NULL;
                try {
                string post ="email=exampleemail";
                std::string response;
		std::string responseheader;
		
		if (curl_handle) {
			curl_easy_setopt(curl_handle, CURLOPT_URL, "URL");
			curl_easy_setopt(curl_handle, CURLOPT_POSTFIELDS, post.cstr());
			curl_easy_setopt(curl_handle, CURLOPT_WRITEFUNCTION, CurlWrite_CallbackFunc_StdString);
			curl_easy_setopt(curl_handle, CURLOPT_WRITEDATA, &response);
			curl_easy_setopt(curl_handle, CURLOPT_HEADERDATA, &responseheader);
			curl_easy_setopt(curl_handle, CURLOPT_CONNECTTIMEOUT, 10L);
			curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYPEER, 0L);
			curl_easy_setopt(curl_handle, CURLOPT_SSL_VERIFYHOST, 0L);
			curl_easy_setopt(curl_handle, CURLOPT_TIMEOUT, 15L);
			curl_easy_setopt(curl_handle, CURLOPT_SSL_ENABLE_ALPN, 1L);
			curl_easy_setopt(curl_handle, CURLOPT_TCP_KEEPALIVE, 1L);
			curl_easy_setopt(curl_handle, CURLOPT_SSL_ENABLE_NPN, 1L);
			curl_easy_setopt(curl_handle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
			postchunk = NULL;
			postchunk = curl_slist_append(postchunk, "Host: Example Host");
			postchunk = curl_slist_append(postchunk, "Connection: Keep-Alive");
			postchunk = curl_slist_append(postchunk, content_length);
			postchunk = curl_slist_append(postchunk, "Accept-Encoding: identity");
			postchunk = curl_slist_append(postchunk, "Content-Type: application/x-www-form-urlencoded");

			curl_easy_setopt(curl_handle, CURLOPT_HTTPHEADER, postchunk);
			curl_easy_perform(curl_handle);

			curl_easy_cleanup(curl_handle);
			curl_slist_free_all(postchunk);
                  }
               }
             catch (const std::exception&) {
		curl_easy_cleanup(curl_handle);
		curl_slist_free_all(postchunk);
	      }

**Comment by dfandrich** [comment]
It's unlikely the problem is related the contents of the data. There are some
questionable parts of the code, though.

1. libcurl is C code that won't throw exceptions and isn't exception aware. I'm
not sure what would happen to libcurl's state if a callback throws an exception
in middle of a transfer.

2. The Host: Connection: Content-Length: and Accept-Encoding: should normally
not be set by the application as they are all handled by libcurl itself, and
changing them under its nose could cause issues. Set them implicitly using the
appropriate CURLOPT_* options instead.

3. Disabling CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST is dangerous and
nullify much of TLS' security.

4. Setting CURLOPT_SSL_ENABLE_NPN and CURLOPT_SSL_ENABLE_ALPN don't help much
when the application is only using HTTP/1.1

**Comment by mobines96** [comment]
> It's unlikely the problem is related the contents of the data. There are some questionable parts of the code, though. 1. libcurl is C code that won't throw exceptions and isn't exception aware. I'm not sure what would happen to libcurl's state if a callback throws an exception in middle of a transfer. 2. The Host: Connection: Content-Length: and Accept-Encoding: should normally not be set by the application as they are all handled by libcurl itself, and changing them under its nose could cause issues. Set them implicitly using the appropriate CURLOPT_* options instead. 3. Disabling CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST is dangerous and nullify much of TLS' security. 4. Setting CURLOPT_SSL_ENABLE_NPN and CURLOPT_SSL_ENABLE_ALPN don't help much when the application is only using HTTP/1.1

i know all of them, those are not realated to my memory leak problem. its just a sample code of my short program.

**Comment by jay** [comment]
That isn't enough, we need a minimal self contained example that reproduces the issue.

**Comment by mobines96** [comment]
> That isn't enough, we need a minimal self contained example that reproduces the issue.

**Comment by mobines96** [comment]
Hi i made an example api for this problem ,here is an example that leaks memory.



    size_t CurlWrite_CallbackFunc_StdString(void* contents, size_t size, size_t nmemb, std::string* s)
    {
           
	size_t newLength = size * nmemb;
	try
	{
		s->append((char*)contents, newLength);
	}
	catch (std::bad_alloc& e)
	{
		return 0;
	}
	return newLength;
    }


	CURL* curl = curl_easy_init();
	struct curl_slist* chunk = NULL;

	std::string response;

	if (curl) {
		curl_easy_setopt(curl, CURLOPT_URL, "https://88.218.17.24/api");
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, CurlWrite_CallbackFunc_StdString);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
		curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
		curl_easy_setopt(curl, CURLOPT_TIMEOUT, 15L);
		curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);
		curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
		chunk = NULL;
		chunk = curl_slist_append(chunk, "Host: 88.218.17.24");
		chunk = curl_slist_append(chunk, "Connection: Keep-Alive");
		curl_easy_setopt(curl, CURLOPT_HTTPHEADER, chunk);
		curl_easy_perform(curl);

	        curl_easy_cleanup(curl);
            curl_slist_free_all(chunk);
               }

**Comment by bagder** [comment]
How do you spot the leak? Does it identify where the leak originated?

**Comment by bagder** [comment]
Did you build libcurl to use winidn ?

**Comment by bagder** [comment]
No response
