### ISSUE TITLE
Incorrect IPv4 normalization

### ISSUE THREAD

**Issue by siiptuo** [curl/curl#6916]
### I did this

curl +127.-0.-0.+1

### I expected the following

"Could not resolve host: +127.-0.-0.+1" i.e. "+127.-0.-0.+1" should not be normalized as "127.0.0.1".

`ipv4_normalize` introduced in 56a037cc0ad1b2a770d0c08d3d09dee1ce600f0f parses numbers using `strtoul` which supports leading whitespace and optional sign.
Whitespace characters seem to be disallowed before normalization.

### curl/libcurl version

curl 7.77.0-DEV

### operating system

Linux 5.11.14

**Comment by bagder** [comment]
Thanks for the report. Good thinking!
