### ISSUE TITLE
--with-wolfssl not recognized

### ISSUE THREAD

**Issue by tiolan** [curl/curl#6931]
### I did this

build libcurl like this
```
MY_INSTALL_DIR="$(pwd)/install"
```
```
    autoreconf -fi
    ./configure --enable-debug --prefix="$MY_INSTALL_DIR" --without-ssl --with-wolfssl="$MY_INSTALL_DIR"
    make -j $(nproc) install
```
build wolfssl like this
```
    autoreconf -i
    ./configure --enable-debug --enable-errorstrings CFLAGS="-DSHOW_SECRETS -DWOLFSSL_SSLKEYLOGFILE -Wno-error=cpp" --prefix="$MY_INSTALL_DIR" --enable-static --enable-shared=no --enable-tls13 --enable-ipv6 --enable-base64encode=no --enable-examples=no --enable-crypttests=no --enable-pkcs12=no
    make -j "$(nproc)" install
```
print supported protocols
```
  auto protos = curl_version_info(CURLVERSION_NOW)->protocols;
  int i = 0;
  while (protos[i]) {
    printf("protocols: %s\n", protos[i]);
    i++;
  }
```
I also tried with `--without-openssl` on master branch instead of `--with-ssl` with no difference.

Potentially related #6874 ?
### I expected the following
Expecting to have TLS protocols included, but
```
protocols: dict
protocols: file
protocols: ftp
protocols: gopher
protocols: http
protocols: imap
protocols: mqtt
protocols: pop3
protocols: rtsp
protocols: smtp
protocols: telnet
protocols: tftp
```
Also other TLS related functions do not seem to be compiled in. E.g.:
```
  auto ver = curl_version_info(CURLVERSION_NOW)->ssl_version;
  if (ver)
    printf("%s\n", ver);
  else
    printf("NULL\n");
```
```
NULL
```
or on connection attempt
```
* STATE: INIT => CONNECT handle 0x5639d8e272c8; line 1753 (connection #-5000)
* Protocol "https" not supported or disabled in libcurl
* Closing connection -1
* Expire cleared (transfer 0x5639d8e272c8)
Error: Unsupported protocol
```

### curl/libcurl version
curl-7_76_0
and master

[curl -V output]

### operating system
Linux Ubuntu-dev 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
1. Check `config.log` after configure fails to the find library - the summary at the end of the configure run should say it found and will use wolfSSL if it is successful. Search for "wolfSSL" in that file and see what it says about what it checked for and what the failures were
2. In general, finding and using static library dependencies is error-prone and likely to not work with configure unless you provide the necessary extra flags needed to find and use extra dependencies. Not sure if that's the case here.

**Comment by tiolan** [comment]
Oh I was not aware of this logfile.
It fails when building `conftest`
```
wolfssl/wolfcrypt/src/dh.c:985: undefined reference to `pow'
wolfssl/wolfcrypt/src/dh.c:986: undefined reference to `log'
wolfssl/wolfcrypt/src/dh.c:986: undefined reference to `pow'
```
The build of `conftest` does not `-lm`.
Let me see how to do and handle this.

Does not seem to be curl related then, so please feel free to close the ticket.
Thanks a lot!

**Comment by bagder** [comment]
Try `LDFLAGS-lm ./configure...` then as a next step...

**Comment by tiolan** [comment]
Yes, it was `LIB="-lm" ./configure...`
