### ISSUE TITLE
Curl 7.76.1 Segfault with openldap while using ldaps with self signed certificate

### ISSUE THREAD

**Issue by extrimexxx** [curl/curl#6934]
Bug or not? Segfault in curl 7.76.1 with openldap while using ldaps with ldap server with self signed certificate

### I did this

without `-k` argument:
`curl ldaps://www.zflexldap.com/` > Segmentation fault (core dumped)

with `-k` argument:
`curl -k ldaps://www.zflexldap.com/` > work good but authentication failed

with `-k` argument:
`curl -k "ldaps://www.zflexldap.com/dc=zflexsoftware,dc=com?cn" -u "uid=guest1,ou=users,ou=guests,dc=zflexsoftware,dc=com:guest1password"` > work good, say's `DN: DC=ZFLEXSOFTWARE,DC=COM`

without `-k` argument:
`curl "ldaps://www.zflexldap.com/dc=zflexsoftware,dc=com?cn" -u "uid=guest1,ou=users,ou=guests,dc=zflexsoftware,dc=com:guest1password"` > Segmentation fault (core dumped)

### I expected the following
on another server with normal certificate work good:

with `-k` argument:
`curl -k ldaps://db.debian.org/` > say's `DN: objectClass: top objectClass: OpenLDAProotDSE`

without `-k` argument:
`curl ldaps://db.debian.org/` > say's `DN: objectClass: top objectClass: OpenLDAProotDSE`

### curl/libcurl version

```
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.4 zstd/1.3.3 c-ares/1.17.1 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) libssh2/1.8.0 librtmp/2.3 libgsasl/1.8.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd
```

### operating system
```
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-142-generic x86_64)
Linux ubuntu 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
I can reproduce.

**Comment by extrimexxx** [comment]
i tested it #6935, now works, thanks!
