### ISSUE TITLE
-Z / --parallel breaks --fail-early --fail

### ISSUE THREAD

**Issue by luke-clifton** [curl/curl#6939]
### I did this

```
curl --parallel-max 1 -Z --fail --fail-early https://curl.se/nothere[1-3]
```

### I expected the following

Stop as soon as one as we know something failed, and return a non-0 exit code.

### What actually happens

curl will attempt every single url, and then exit with a 0.

### curl/libcurl version

I did it on master:

```
curl 7.77.0-DEV (x86_64-apple-darwin19.6.0) libcurl/7.77.0-DEV OpenSSL/1.1.1k
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

But also other version.

### operating system

Darwin BLAH 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/pull/6921

It might be a bug, I'm not sure myself. It seems [--fail-early](https://curl.se/docs/manpage.html#--fail-early) wasn't meant for parallel transfers. The transfers in progress would need to be properly cleaned up.

**Comment by luke-clifton** [comment]
Haha, OK. So I was a couple of days short on my master build. I see that the error code is not discarded anymore.

But the `--fail-early` (as you mention in your PR) is still an issue.

I'll agree that I'm not sure what the best thing to do would be: finish in-flight transfers, or close everything down. But I certainly feel that starting new transfers is not what should happen.

**Comment by bagder** [comment]
> It seems [--fail-early](https://curl.se/docs/manpage.html#--fail-early) wasn't meant for parallel transfers.

It was added long before we did parallel transfers and I think we just haven't adapted parallel mode properly to deal with it. I think it sounds like a proper bug...

**Comment by jay** [comment]
We could set a flag in the multi loop and then abort from the progress callback.

~~~diff
diff --git a/src/tool_progress.c b/src/tool_progress.c
index da6c2bc..4123e93 100644
--- a/src/tool_progress.c
+++ b/src/tool_progress.c
@@ -101,6 +101,9 @@ int xferinfo_cb(void *clientp,
   per->ultotal = ultotal;
   per->ulnow = ulnow;
 
+  if(per->abort)
+    return -1;
+
   if(config->readbusy) {
     config->readbusy = FALSE;
     curl_easy_pause(per->curl, CURLPAUSE_CONT);
~~~

**Comment by bagder** [comment]
We'd have to discuss what the option should do about other **already started** transfers...

**Comment by luke-clifton** [comment]
I'd say `--fail-early` should kill it as early as possible. Perhaps another `--fail-gracefully` option would allow transfers to finish. If you let `--fail-early` finish transfers, you are going to end up needing a `--fail-really-early` for the other case.

**Comment by bagder** [comment]
I'm fine with killing off the already started ones too, as long as we document that this is to be expected when `-Z` is used with this option.

**Comment by jay** [comment]
> We'd have to discuss what the option should do about other **already started** transfers...

Aborting from the progress callback would kill them off

**Comment by bagder** [comment]
@jay will you make a PR based on your proposed fix?

**Comment by jay** [comment]
> @jay will you make a PR based on your proposed fix?

#6984 to abort via progress callback but it would mean setting CURLOPT_NOPROGRESS to 0L.
~~~
> curld --parallel-max 1 -Z --fail --fail-early https://curl.se/nothere[1-3]

[1/3]: https://curl.se/nothere1 --> <stdout>
--_curl_--https://curl.se/nothere1
curl: (22) The requested URL returned error: 404
curl: (22) HTTP response code said error
~~~

~~~
> curld --fail --fail-early -Z https://httpbin.org/status/404 https://httpbin.org/delay/10
curl: (22) The requested URL returned error: 404
curl: (42) Callback aborted
~~~

I'm not sure what to do about the return code in the latter case or if it's ok to always set noprogress to 0. Have a look
