### ISSUE TITLE
Connect to remote site via curl, proxy, and https results in a 405 error

### ISSUE THREAD

**Issue by jeffreykutcher** [curl/curl#6941]
Using curl to talk to a remote site via proxy. 

From curl to remote site direct works fine and expected response 
is correct. When a proxy is introduced, handshaking between curl 
and remote site via proxy works fine. From there, a 405 error is 
being returned and would like to understand why.

Post handshaking, when curl talks direct, it next sends a GET request:

> GET /relpath HTTP/1.1
> Host: api.giphy.com
> User-Agent: curl/7.68.0
> Accept: */*

When curl talks via proxy, a CONNECT occurs followed by a 405 error:

> CONNECT host:port HTTP/1.1
> Host: host:port
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
...
< HTTP/1.1 405 Method Not Allowed
< Connection: close
< Content-Length: 16
< content-type: text/plain; charset=utf-8

Please offer suggestions to resolve this issue or thoughts as to 
why this might be happening.

Curl options used are: 
  -trace 
  --verbose
  --proxy-insecure 
  --no-alpn 
  --no-buffer

Thanks

**Comment by bagder** [comment]
This is your proxy saying it doesn't allow `CONNECT`. This is not curl problem. You should talk to your proxy admin.

**Comment by jeffreykutcher** [comment]
I was under the impression that the proxy simply relays the information it receives. Shouldn't that connect or isn't that connect meant for the remote site, not the proxy?

**Comment by bagder** [comment]
> I was under the impression that the proxy simply relays the information it receives.

Yes, that's more or less what a proxy does. But it can still deny clients to use it. Like for your case here.

`CONNECT` is used by a client that wants to speak HTTPS to a remote server via the proxy.

**Comment by jeffreykutcher** [comment]
Additionally, curl and the proxy are already connected via the fact handshaking has already been established. I would assume that curl and remote site would communicate simply by the proxy passing the data it receives to and from each of the  applications (curl and remote site). Because the data is encrypted via https, the proxy should know nothing of what is being communicated other than it should be moving the data along. I didn't specify the CONNECT host and port, but in the debug output, the host and port values are the remote site (port being 443), not the proxy. The proxy shouldn't care about a CONNECT. That CONNECT should be for the remote site, or that would be my assumption.

**Comment by jeffreykutcher** [comment]
You're telling me the CONNECT is for the proxy and not the remote site?

**Comment by jeffreykutcher** [comment]
(And thanks for the responses)

**Comment by bagder** [comment]
curl doesn't speak to the remote site when a proxy is used. It only speaks with the proxy, which in turns speaks with the remote site. So yes, the CONNECT is to the proxy; asking it to connect to the remote site.

**Comment by bagder** [comment]
It is returning a very correct response. It says you're not allowed to send a CONNECT to it.

**Comment by jeffreykutcher** [comment]
I wrote the proxy and all it does is pass information to and from curl to the remote site. The proxy doesn't speak http or https. It assumes that curl will send it information and that information is intended to be sent to a remote site. When information is returned from the remote site, it should be sent back to the client, in this case curl. Because the remote site is expecting https, the proxy is connecting to the remote site via 443. From there I would expect anything that curl sent the proxy, if forwarded to the remote site, communicating would occur as if the proxy weren't there. I'm beginning to understand that curl is assuming that the proxy needs to speak http. Is there a curl option to turn that feature off?

**Comment by bagder** [comment]
curl supports several different kinds of proxies, but a HTTP proxy speaks HTTP so yes it will need to understand HTTP

**Comment by jeffreykutcher** [comment]
... turn that feature off when curl is speaking thru a proxy. That is, curl should assume that it's talking to the remote site, though it's sending it's information to a proxy. It's the remote site that is doing the deciphering of the data, not the proxy.

How do you turn off http (https) speak in curl when talking to a proxy, but keep https on because the data captured by the proxy is being relayed to the remote site?

**Comment by dfandrich** [comment]
You may be looking for this:
https://curl.se/docs/faq.html#How_do_I_get_HTTP_from_a_host_us

**Comment by jeffreykutcher** [comment]
The proxy as is, sends communication back and forth, blindly. The tunnel between curl and the remote site is established (via proxy). The handshaking has occurred (message from curl: Establish HTTP proxy tunnel to <host>:443). Communication between curl and the remote site now has the agreed upon protocol. There should be no need to "CONNECT" to the proxy since the connection already exists to the proxy and proxy to the remote site via tunnel. HTTPs, the protocol used between curl and remote site should now happen seamlessly through the established tunnel. There should be no need to speak http with the proxy meaning either that CONNECT shouldn't happen if it's intended for the proxy, or it's part of the protocol being sent to the remote site and it's the remote site returning the "405 Method not allowed". I can tell you for a fact that the proxy doesn't recognize CONNECT and it doesn't speak http or https. The tunnel is already established. The proxy at this point is literally the middle guy and just passes information. And because it's a tunnel, the proxy only sees gibberish. And because it's a tunnel, the proxy shouldn't even know the information being passed is http or https.

**Comment by jeffreykutcher** [comment]
... (message from curl: Establish HTTP proxy tunnel to host:443) ... where host is the remote host, not the proxy.

**Comment by jeffreykutcher** [comment]
And the "HTTP/1.1 405 Method Not Allowed" has to be coming from the remote site because the proxy has no protocol and only forwards communications.

**Comment by dfandrich** [comment]
What you're describing sounds like a transparent proxy that looks to the
outside world like the remote server it's proxying. In such as case, you want
curl to connect to the proxy (running on a specific host and port) but act like
it's talking to the real, remote server. That's what the instructions in the
FAQ explain how to do.

**Comment by jeffreykutcher** [comment]
I think that assumes that the proxy speaks http or https.

**Comment by dfandrich** [comment]
No, but it does assume that the remote server speaks HTTP or HTTPS.

**Comment by jeffreykutcher** [comment]
Which it does. Is curl assuming that the information it sends to the proxy is sending the request to the remote server on it's behalf, or is curl assuming that the information it sends to the proxy is going to be sent directly to the remote server verbatim? I would think the latter since the tunnel is already established. Information sent via curl should travel encrypted and only be deciphered at it's destination.

**Comment by dfandrich** [comment]
curl uses no notion of a proxy of any sort using that technique. It just
assumes it's talking to the remote server, just using an odd IP address. This
technique is very useful in the common case when talking to a virtual HTTP host
without a proper DNS address, or when talking through a reverse proxy, or in
your case through (essentially) a transparent proxy.

**Comment by jeffreykutcher** [comment]
So curl does assume the server it talks to knows http. Thanks Dan.

**Comment by dfandrich** [comment]
If you give curl an HTTP URL, then it assumes the server it talks to knows
HTTP.

**Comment by jeffreykutcher** [comment]
Well ... if the environment variable, https_proxy, is set to the proxy host:port, curl will talk to that proxy host:port, handshake and set up a tunnel with the remote host:port given in the url provided to curl on the command line, via the proxy. That works as expected. If there's http communication going on at this point, I'm unable to tell. The next part however, curl tries talking http (makes a CONNECT call). I'm unable to tell if this call is for the proxy or remote host. The tunnel has been established so I figured all further communication would occur through the tunnel, similar to the initial set up which would mean that the remote host is getting the CONNECT request. From the "transparent" proxy perspective, nothing has changed. It continues to move information in one direction or the other, the difference being now the traffic is encrypted because it's being tunneled. That doesn't seem to be the case. Is there a way to make that the case? What is that CONNECT trying to do? The tunnel has already been established.

**Comment by jay** [comment]
curl is trying to establish a tunnel but the proxy rejects it as not allowed. this has already been explained. https://tools.ietf.org/html/rfc2817#section-5.2

if you have a transparent proxy then don't specify it as a proxy to curl

**Comment by jeffreykutcher** [comment]
Thanks Jay, Dan and Dan.
