### ISSUE TITLE
TLS backends rely on USE_NGHTTP2 to send "h2" ALPN

### ISSUE THREAD

**Issue by jsha** [curl/curl#6949]
Right now, if you build with Hyper, but without nghttp2, curl will never send the "h2" ALPN protocol and therefore will never negotiate HTTP/2. The TLS backends currently check USE_NGHTTP2 when deciding whether to send "h2", in part because they rely on these two macros from nghttp2: NGHTTP2_PROTO_VERSION_ID and NGHTTP2_PROTO_VERSION_ID_LEN.

We should introduce a new #define, USE_HTTP2, which is defined by both Hyper and nghttp2. We should also define constants within curl for the "h2" ALPN value and its length (which are set by standard), so implementations don't have to use values from different backends.

/cc @kevinburke, who helped find this.

**Comment by bagder** [comment]
Fixed by #6959
