### ISSUE TITLE
CONNECT fails if it can't send the entire request in one go

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#6950]
### I did this

There are Proxy which need Kerberos Authentication, but the authentication flow sometimes failed . This not easy to reproduce.

After checking the wireshark captured file and source code of libcurl. We find the possible root cause of the issue.

```
CURLcode Curl_buffer_send(struct dynbuf *in,
                          struct connectdata *conn,
                          /* add the number of sent bytes to this
                             counter */
                          curl_off_t *bytes_written,
                          /* how much of the buffer contains body data */
                          size_t included_body_bytes,
                          int socketindex)
{
...
sendsize = CURLMIN(size, CURL_MAX_WRITE_SIZE);
...

else {
      if((size_t)amount != size)
        /* We have no continue-send mechanism now, fail. This can only happen
           when this function is used from the CONNECT sending function. We
           currently (stupidly) assume that the whole request is always sent
           away in the first single chunk.

           This needs FIXing.
        */
        return CURLE_SEND_ERROR;
    }
}
```
When the Kerberos Auth challenge is bigger than CURL_MAX_WRITE_SIZE (16384) , the request with auth will be failed. (Will be fallbacked to using NTLM in our user's proxy environment.)

![image](https://user-images.githubusercontent.com/2238185/115946008-0f8e7500-a4f1-11eb-98f9-9084aea4ae16.png)

### curl/libcurl version

7.74.0

### operating system

Windows

**Comment by bagder** [comment]
Any proposal on how to fix this?

**Comment by ustcqidi** [comment]
@bagder 
We are fixing this by a workaround, just send the "real" size when sending "proxy-authorization header"

here is the code diff, could you please help to review whether is it make sense ? Thanks.

https://github.com/curl/curl/pull/7019

**Comment by bagder** [comment]
btw, is this perchance in a `CONNECT` request?

**Comment by ustcqidi** [comment]
yes, in the function of CONNECT of http_proxy.c

static CURLcode CONNECT(struct connectdata *conn,
                        int sockindex,
                        const char *hostname,
                        int remote_port)

**Comment by bagder** [comment]
I figured out how to write a test case for this issue that reproduces your problem and shows that http_proxy.c:CONNECT needs to be fixed:

[test363](https://github.com/curl/curl/files/6433311/test363.txt)

This test limits the initial CONNECT request send to 100 bytes, which breaks curl.
