### ISSUE TITLE
Remove strlen call in Curl_client_write

### ISSUE THREAD

**Issue by jsha** [curl/curl#6952]
In #6951, an uninitialized read was caused because Curl_client_write has two code paths: It can take a buf and a len, or if `len` is zero, it treats the input as a NUL-terminated string.

https://github.com/curl/curl/blob/f014eeceb218200c5864ce91a8de2cc21d951c32/lib/sendf.c#L604-L620

It looks like the strlen code path was originally introduced in 2000: 39abde5db5b095bc20b9203d8c0174e4f047fee2.

I think we should introduce Curl_client_write_str, which take a ptr, calls strlen, and passes both to Curl_client_write. Then we should update all the callsites that depend on the "len 0" semantics so they call Curl_client_write_str instead.

**Comment by bagder** [comment]
Fixed in #6954
