### ISSUE TITLE
Rustls compilation should include CoreFoundation and Security frameworks on Mac

### ISSUE THREAD

**Issue by kevinburke** [curl/curl#6955]
Without these frameworks compiled in, the `--with-rustls` flag on Macs fails with a bunch of errors related to missing symbols that are present in the CoreFoundation or Security frameworks.

People may not notice this because compilation does not error if you include the `--with-secure-transport` flag - that one appends the correct CoreFoundation framework flags to LDFLAGS. Unfortunately including that flag means that curl chooses SecureTransport for TLS and not rustls, so as is, it's essentially impossible to use rustls for TLS on Mac.

**Comment by bagder** [comment]
@jsha, thoughts?

**Comment by jsha** [comment]
I think this is correct, and sent an approval on the corresponding PR (#6956)
