### ISSUE TITLE
GET HTT CODE 403 WHEN USING CURL

### ISSUE THREAD

**Issue by dangvohoanganhvn** [curl/curl#6974]
### Hi, I have some problems when i use cmd:
 curl 'https://download.apkpure.com/b/APK/Y29tLnppbmcuemFsb18xMjEwMDU0OV8zOTU3MTU0ZA?_fn=WmFsbyBWaWRlbyBDYWxsX3YyMC4xMS4wMV9hcGtwdXJlLmNvbS5hcGs&as=cd413a537b589da8f6727774e84ea1f460868c63&ai=1092328977&at=1619430379&_sa=ai%2Cat&k=0d1773f2e39d520a1ae68811babe75b160892eeb&_p=Y29tLnppbmcuemFsbw&c=1%7CCOMMUNICATION%7CZGV2PVphbG8lMjBHcm91cCZ0PWFwayZzPTcwMjg0ODEyJnZuPTIwLjExLjAxJnZjPTEyMTAwNTQ5' . 
 Curl always return 403 HTTP code although I can download this file on chrome or safari. I try add option -A (agent) to above cmd however it does not work too. Is there any solution for this case. Thanks

**Comment by jzakrzewski** [comment]
Just run it with the `-v` and you'll see that the server sends a HTML page with that 403 that has some magic (JavaScript, forms) and something like ```<h1 data-translate="managed_challenge_headline">Please wait...</h1>
        <h2 class="cf-subheadline"><span data-translate="managed_checking_msg">We are checking your browser...</span> download.apkpure.com</h2>
``` inside. There's also CAPTCHA, checking for cookies, etc. 

curl cannot possibly pass those tests as it's not a browser. Whoever set this thing up really didn't want any automatic tools (like curl) to download this stuff.

**Comment by dangvohoanganhvn** [comment]
Thanks for very helpful anwser.
