### ISSUE TITLE
curl doesn't redirect with GET method when receiving 302 status code.

### ISSUE THREAD

**Issue by valfur03** [curl/curl#6976]
### I did this

I made a HTTP request with a POST method (https://signin.intra.42.fr/users/sign_in). The server responds with a 302 code, which redirects to the same URL, and curl is supposed to follow this URL with the GET method.

Here is the command:

```shell
curl -L -X POST "https://signin.intra.42.fr/users/sign_in"
```

### I expected the following

The problem is that curl doesn't redirect with the GET method, as it should according to the man. And because of that, it repeats the exact same request over and over, until this `error curl: (47) Maximum (50) redirects followed`.

> When curl follows a redirect and if the request is a POST, it will do the following request with a GET if the HTTP response was 301, 302, or 303.

### curl/libcurl version

[curl -V output] on MacOS:

```
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
```

[curl -V output] on Linux:

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

### operating system

MacOS: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

Linux: Linux 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
You're asking for this with your `-X` use.

[Explained in more words here](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/)

**Comment by valfur03** [comment]
Indeed, it works better with `-d`. Is it then a `man` problem ? It is a little ambiguous how both `-L` and `-X` work...

**Comment by gevaerts** [comment]
The manpage says "The method string you set with -X, --request will be used for all requests, which if you for example use -L, --location may cause unintended side-effects when curl  doesn't change request method according to the HTTP 30x response codes - and similar."
