### ISSUE TITLE
Spack dosent work well on cluster

### ISSUE THREAD

**Issue by cdelv** [curl/curl#6978]
I Tied to install some packages with these commands
`spack install zlib`

`spack install berkeley-db-18.1.40`

the log error for Zlib is 

`==> zlib: Executing phase: 'install'

==> [2021-04-27-11:33:35.419240] './configure' '--prefix=/homes/orionsan/cdelv/spack/opt/spack/linux-fedora26-westmere/gcc-9.2.0/zlib-$

Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).

** ./configure aborting.
´

The log error for Berkeley is

`configure: error: C compiler cannot create executables
`
Mycompilers .yaml file:

`- compiler:

    spec: gcc@7.3.1

    paths:

      cc: /usr/lib64/ccache/gcc

      cxx: /usr/lib64/ccache/g++

      f77: /usr/bin/gfortran

      fc: /usr/bin/gfortran

    flags: {}

    operating_system: fedora26

    target: x86_64

    modules: []

    environment: {}

    extra_rpaths: []

- compiler:
- 
    spec: gcc@9.2.0

    paths:

      cc: /usr/local/gcc-9.2/bin/gcc-9.2

      cxx: /usr/local/gcc-9.2/bin/g++-9.2

      f77: /usr/local/gcc-9.2/bin/gfortran-9.2
`

**Comment by dfandrich** [comment]
I think you've posted this to the wrong project.

**Comment by cdelv** [comment]
That's write sorry.
