### ISSUE TITLE
Feature: Option to persist SSL session-ID in a file for reusing between invocations

### ISSUE THREAD

**Issue by ggrandes** [curl/curl#698]
### I did this

```bash
  curl -q -f -sS -m 180 --retry 3 \
    --proto https --proto-redir https \
    --cacert "ca.crt" \
    --cert "client.crt" \
    --key "client.key" \
    "https://www.acme.com/xxxxx"
```

From 40 cURL-clients (always same machines), every minute (pooling)... connecting to [Tomcat](https://tomcat.apache.org/tomcat-7.0-doc/config/http.html#SSL_Support) server with ```TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384``` (RSA-2048bits) and SSL cache enabled (24h)... but without ssl-cache support in cURL client, the server CPU jumps to 100% long time.

### I expected the following

```--file-sessionid FILE```  Option to persist SSL session-ID in a file for reusing between invocations.

### curl/libcurl version

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

### operating system

Ubuntu 14.04.4 LTS

**Comment by bagder** [comment]
Thanks!

This is really a lacking functionality in libcurl, and that functionality has been mentioned in the TODO file for a very long time to get added: https://curl.haxx.se/docs/todo.html#Export_session_ids

Once that is implemented, adding the command line options for it will be trivial. I don't think we need to keep this entry around for that reason only.
