### ISSUE TITLE
mesalink backend considers 127.0.0.1* to be localhost

### ISSUE THREAD

**Issue by piru** [curl/curl#6989]
### I did this

Connected to https://127.0.0.10, https://127.0.0.199 or any address beginning with "https://127.0.0.1". Due to botched `strncmp` in lib/vtls/mesalink.c `mesalink_connect_step1` these URLs are all considered "localhost" by mesalink code.

### I expected the following

Hostnames other than "127.0.0.1" and "[::1]" not being considered "localhost".

### curl/libcurl version

curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) nghttp2/1.43.0 librtmp/2.3

### operating system

Linux hostname 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

**Comment by bagder** [comment]
That's only for debug-builds and it was made to be able to work with the test suite since mesalink uses rustls and rustls still (?) doesn't support IP addresses in certificates.

The comparison can be fixed but the logic can probably not until someone fixes rustls.

**Comment by piru** [comment]
Somehow missed the debug ifdef, closing as no action is really needed.
