### ISSUE TITLE
rustls: Various bugs in send path

### ISSUE THREAD

**Issue by jblazquez** [curl/curl#7007]
### I did this

Enabled the `rustls` backend in our internal application which has historically used OpenSSL. We immediately found a number of issues, detailed below.

The first issue - on the receive path - was reported and fixed here: https://github.com/curl/curl/pull/6894

There are three more issues - this time on the send path - that we have encountered. No repro steps are provided but they should be trivial to reproduce by performing a multi-megabyte upload, and the description below should hopefully clarify what the bugs are:

1. This [assert](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L266) can trigger during normal circumstances that are not error conditions. It will trigger when the first socket `send` operation for a TLS record returned by `rustls_client_session_write_tls` encounters a full send buffer, even if several other TLS records have been sent beforehand during this `cr_send` call. In essence, the debug check is wrong, because it's asking "was I able to send any data from this TLS record?" - but [as the comment implies](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L263-L264) - the correct question to ask is "was I able to send any data during this whole `cr_send` call?". If this debug check is important, it should not use the `tlswritten` variable, which is set to zero on each iteration of the outer `while` loop.

2. This [`break`](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L267) statement that happens when the socket send buffer fills up is incorrect, because it's breaking out of the [inner loop](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L259) but potentially looping again on the [outer loop](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L243) to retrieve further TLS records. It should return from the function instead, since there's no way we'll be able to send further TLS records during this `cr_send` call.

3. The [handling of a socket send buffer full condition](https://github.com/curl/curl/blob/70cf50fb4aa5e55ca2e732716a4f455d39192088/lib/vtls/rustls.c#L262-L268) is incorrect, because it's not handling the very likely possibility that the send buffer will fill up without having written the entirety of the TLS record returned by the last call to `rustls_client_session_write_tls`. For example, if the socket fills up and can only take half of the TLS record, this function is dropping the other half of the record on the floor, since it's not persisting the value of `tlswritten` across `cr_send` calls. The next time `cr_send` is called, a new TLS record is read into the same `backend->tlsbuf` buffer, overwriting the unsent part of the previous record. The `rustls` backend needs to persist state across `cr_send` calls and ensure that the remaining bytes of the previous TLS record are sent before pulling new records from the session.

### I expected the following

I expected the `rustls` backend to perform multi-megabyte upload requests successfully.

### curl/libcurl version

7.76.1

### operating system

Windows.

**Comment by jsha** [comment]
Thanks for the detailed report. I've repro'ed locally and will work on a fix. I did test large uploads early in the development process, but looks like it regressed during a subsequent refactoring. I'll add a test case too.

**Comment by jsha** [comment]
Posted https://github.com/abetterinternet/crustls/issues/92 with a proposed API change in crustls to solve this. What do you think?

**Comment by jblazquez** [comment]
Thanks for opening that issue. I’m interested to see what the crustls developers say.

**Comment by jsha** [comment]
@jblazquez I think the merged PR #7071 fixes all three of the issues you raised here. Can you confirm?

**Comment by jblazquez** [comment]
We no longer use the rustls backend in our application, so I can't confirm within the context of our app, but if you have verified that performing large uploads works successfully then I think it is fixed.

Thanks!

**Comment by jsha** [comment]
Yep, I've verified large uploads are sent and received correctly.

**Comment by bagder** [comment]
Then we assume the problems mentioned here are gone now and if we find more/new ones we create new issues! Thanks!
