### ISSUE TITLE
Feature: Enable sharing cURL instances (like ssh ControlMaster)

### ISSUE THREAD

**Issue by ggrandes** [curl/curl#702]
Feature request:
Like OpenSSH [ControlMaster/ControlPath/ControlPersist](http://manpages.ubuntu.com/manpages/trusty/en/man5/ssh_config.5.html), this is an alternative approach to [ToDo #698]. Persistent cURL instance will Speedup SSL negotiation and Connection Reuse between invocations.

_Extracted from man page of ssh_config_:
```
ControlMaster
             Enables the sharing of multiple sessions over a single network
             connection.  When set to “yes”, ssh(1) will listen for
             connections on a control socket specified using the ControlPath
             argument.  Additional sessions can connect to this socket using
             the same ControlPath with ControlMaster set to “no” (the
             default).  These sessions will try to reuse the master instance's
             network connection rather than initiating new ones, but will fall
             back to connecting normally if the control socket does not exist,
             or is not listening.
````

**Comment by bagder** [comment]
Thanks, but we don't keep feature requests in this issue tracker. Ideas are easy, implementations are what counts. This idea is now summarized in the TODO for someone to potentially grab and work on: https://curl.haxx.se/docs/todo.html#keep_running_read_instructions

**Comment by ggrandes** [comment]
:+1:
