### ISSUE TITLE
cmake: Unix Sockets support on Win32 platform is missing 

### ISSUE THREAD

**Issue by lixinwei715** [curl/curl#7029]
Currently, cmake only check "sys/un.h" to decide whether Unix Sockets should be enabled, but windows does not have this header file.

CMakeLists.txt  line 793-799 (latest master branch):
```cmake
option(ENABLE_UNIX_SOCKETS "Define if you want Unix domain sockets support" ON)
if(ENABLE_UNIX_SOCKETS)
  include(CheckStructHasMember)
  check_struct_has_member("struct sockaddr_un" sun_path "sys/un.h" USE_UNIX_SOCKETS)
else()
  unset(USE_UNIX_SOCKETS CACHE)
endif()
```

In Winbuild and configure, we have workaround in src/config-win32.h, but cmake does not use this file.

lib/config-win32.h line 716-731 (latest master branch):
```c
/* On MinGW the ADDRESS_FAMILY typedef was committed alongside LUP_SECURE,
   so we use it to check for the presence of the typedef. */
#include <ws2tcpip.h>
#if !defined(__MINGW32__) || defined(LUP_SECURE)
/* Define to use Unix sockets. */
#define USE_UNIX_SOCKETS
#if !defined(UNIX_PATH_MAX)
  /* Replicating logic present in afunix.h of newer Windows 10 SDK versions */
# define UNIX_PATH_MAX 108
  /* !checksrc! disable TYPEDEFSTRUCT 1 */
  typedef struct sockaddr_un {
    ADDRESS_FAMILY sun_family;
    char sun_path[UNIX_PATH_MAX];
  } SOCKADDR_UN, *PSOCKADDR_UN;
#endif
#endif
```

How to make this workaround also available for cmake? The solution I can think of is that creating a new header file (may be named to "unix_sockets_win32.h") and moving codes above to this header file.  This new header file will be shared by both cmake and other configure ways. Is this solution feasible?  Or could you please find out a better solution?

Thanks!

**Comment by bagder** [comment]
> The solution I can think of is that creating a new header file (may be named to "unix_sockets_win32.h") and moving codes above to this header file.

That could work. Or you can move that logic into `curl_setup.h` instead.

**Comment by sirzooro** [comment]
On Windows you can include afunix.h instead sys/un.h, if present.
More details: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
