### ISSUE TITLE
ngtcp2 build errors with 7.76.1

### ISSUE THREAD

**Issue by andy-isoc** [curl/curl#7030]
### I did this
Following the instructions at https://github.com/curl/curl/blob/master/docs/HTTP3.md, I tried to build cURL with http3 and alt-svc enabled. Builds of patched OpenSSL, nghttp3 and ngtcp2 all seemed ok with no errors.

### I expected the following
Build to succeed. Output from configure looked good.

### curl/libcurl version
curl 7.76.1

### operating system
Linux pulse-ubuntu 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`make` returned the following errors:
vquic/ngtcp2.c:121:22: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  121 | quic_from_ossl_level(OSSL_ENCRYPTION_LEVEL ossl_level)
      |                      ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:256:40: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  256 |                                        OSSL_ENCRYPTION_LEVEL ossl_level,
      |                                        ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:280:46: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  280 | static int quic_add_handshake_data(SSL *ssl, OSSL_ENCRYPTION_LEVEL ossl_level,
      |                                              ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:295:43: warning: ‘enum ssl_encryption_level_t’ declared inside parameter list will not be visible outside of this definition or declaration
  295 | static int quic_send_alert(SSL *ssl, enum ssl_encryption_level_t level,
      |                                           ^~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:295:66: error: parameter 2 (‘level’) has incomplete type
  295 | static int quic_send_alert(SSL *ssl, enum ssl_encryption_level_t level,
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
vquic/ngtcp2.c:305:8: error: unknown type name ‘SSL_QUIC_METHOD’
  305 | static SSL_QUIC_METHOD quic_method = {quic_set_encryption_secrets,
      |        ^~~~~~~~~~~~~~~
vquic/ngtcp2.c:305:39: error: ‘quic_set_encryption_secrets’ undeclared here (not in a function)
  305 | static SSL_QUIC_METHOD quic_method = {quic_set_encryption_secrets,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:306:39: error: ‘quic_add_handshake_data’ undeclared here (not in a function)
  306 |                                       quic_add_handshake_data,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:306:39: warning: excess elements in scalar initializer
vquic/ngtcp2.c:306:39: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c:307:39: warning: excess elements in scalar initializer
  307 |                                       quic_flush_flight, quic_send_alert};
      |                                       ^~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:307:39: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c:307:58: warning: excess elements in scalar initializer
  307 |                                       quic_flush_flight, quic_send_alert};
      |                                                          ^~~~~~~~~~~~~~~
vquic/ngtcp2.c:307:58: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c: In function ‘quic_ssl_ctx’:
vquic/ngtcp2.c:330:3: error: implicit declaration of function ‘SSL_CTX_set_quic_method’; did you mean ‘SSL_CTX_get_ssl_method’? [-Werror=implicit-function-declaration]
  330 |   SSL_CTX_set_quic_method(ssl_ctx, &quic_method);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
      |   SSL_CTX_get_ssl_method

**Comment by bagder** [comment]
How about instead using this updated OpenSSL instruction:

~~~diff
diff --git a/docs/HTTP3.md b/docs/HTTP3.md
index 569daeabb..2f377fd35 100644
--- a/docs/HTTP3.md
+++ b/docs/HTTP3.md
@@ -31,11 +31,11 @@ in the master branch using pull-requests, just like ordinary changes.
 
 ## Build with OpenSSL
 
 Build (patched) OpenSSL
 
-     % git clone --depth 1 -b OpenSSL_1_1_1g-quic-draft-29 https://github.com/tatsuhiro-t/openssl
+     % git clone --depth 1 -b OpenSSL_1_1_1k+quic https://github.com/quictls/openssl
      % cd openssl
      % ./config enable-tls1_3 --prefix=<somewhere1>
      % make
      % make install_sw

**Comment by andy-isoc** [comment]
Same, or similar errors, using that:
```
  CC       vquic/libcurl_la-ngtcp2.lo
vquic/ngtcp2.c:121:22: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  121 | quic_from_ossl_level(OSSL_ENCRYPTION_LEVEL ossl_level)
      |                      ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:256:40: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  256 |                                        OSSL_ENCRYPTION_LEVEL ossl_level,
      |                                        ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:280:46: error: unknown type name ‘OSSL_ENCRYPTION_LEVEL’
  280 | static int quic_add_handshake_data(SSL *ssl, OSSL_ENCRYPTION_LEVEL ossl_level,
      |                                              ^~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:295:43: warning: ‘enum ssl_encryption_level_t’ declared inside parameter list will not be visible outside of this definition or declaration
  295 | static int quic_send_alert(SSL *ssl, enum ssl_encryption_level_t level,
      |                                           ^~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:295:66: error: parameter 2 (‘level’) has incomplete type
  295 | static int quic_send_alert(SSL *ssl, enum ssl_encryption_level_t level,
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
vquic/ngtcp2.c:305:8: error: unknown type name ‘SSL_QUIC_METHOD’
  305 | static SSL_QUIC_METHOD quic_method = {quic_set_encryption_secrets,
      |        ^~~~~~~~~~~~~~~
vquic/ngtcp2.c:305:39: error: ‘quic_set_encryption_secrets’ undeclared here (not in a function)
  305 | static SSL_QUIC_METHOD quic_method = {quic_set_encryption_secrets,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:306:39: error: ‘quic_add_handshake_data’ undeclared here (not in a function)
  306 |                                       quic_add_handshake_data,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:306:39: warning: excess elements in scalar initializer
vquic/ngtcp2.c:306:39: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c:307:39: warning: excess elements in scalar initializer
  307 |                                       quic_flush_flight, quic_send_alert};
      |                                       ^~~~~~~~~~~~~~~~~
vquic/ngtcp2.c:307:39: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c:307:58: warning: excess elements in scalar initializer
  307 |                                       quic_flush_flight, quic_send_alert};
      |                                                          ^~~~~~~~~~~~~~~
vquic/ngtcp2.c:307:58: note: (near initialization for ‘quic_method’)
vquic/ngtcp2.c: In function ‘quic_ssl_ctx’:
vquic/ngtcp2.c:330:3: error: implicit declaration of function ‘SSL_CTX_set_quic_method’; did you mean ‘SSL_CTX_get_ssl_method’? [-Werror=implicit-function-declaration]
  330 |   SSL_CTX_set_quic_method(ssl_ctx, &quic_method);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
      |   SSL_CTX_get_ssl_method
cc1: some warnings being treated as errors
```

**Comment by bagder** [comment]
I manually rebuilt curl with ngtcp2 and quictls just now with no problems.

It seems your curl build uses the wrong OpenSSL headers since `OSSL_ENCRYPTION_LEVEL` is provided in `include/openssl/ssl.h` in the quictls install.

**Comment by andy-isoc** [comment]
Should that OpenSSL include dir be listed in the output from configure?
```
  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /usr/local
  Compiler:         gcc
   CFLAGS:          -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread
   CPPFLAGS:        -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/nghttp3/include
   LDFLAGS:         -Wl,-rpath,/root/curl-libs/openssl/lib -L/root/curl-libs/ngtcp2/lib -L/root/curl-libs/ngtcp2/lib -L/root/curl-libs/nghttp3/lib
   LIBS:            -lnghttp3 -lngtcp2_crypto_openssl -lngtcp2 -lssl -lcrypto -lssl -lcrypto

  curl version:     7.76.1
  SSL:              enabled (OpenSSL)
```

**Comment by bagder** [comment]
You can run `make V=1` to get to see the entire compiler command lines, and they should indeed include the path to where the quictls headers are.

**Comment by andy-isoc** [comment]
```
grep OSSL_ENCRYPTION_LEVEL /root/curl-libs/openssl/include/openssl/ssl.h
} OSSL_ENCRYPTION_LEVEL;
    int (*set_encryption_secrets)(SSL *ssl, OSSL_ENCRYPTION_LEVEL level,
    int (*add_handshake_data)(SSL *ssl, OSSL_ENCRYPTION_LEVEL level,
__owur size_t SSL_quic_max_handshake_flight_len(const SSL *ssl, OSSL_ENCRYPTION_LEVEL level);
__owur OSSL_ENCRYPTION_LEVEL SSL_quic_read_level(const SSL *ssl);
__owur OSSL_ENCRYPTION_LEVEL SSL_quic_write_level(const SSL *ssl);
__owur int SSL_provide_quic_data(SSL *ssl, OSSL_ENCRYPTION_LEVEL level,
```

**Comment by andy-isoc** [comment]
Not sure where I'm looking in the output from `make V=1`. The last few lines before the errors are
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I../include -I../lib -I../lib  -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/nghttp3/include  -fvisibility=hidden -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread  -MT vquic/libcurl_la-ngtcp2.lo -MD -MP -MF vquic/.deps/libcurl_la-ngtcp2.Tpo -c -o vquic/libcurl_la-ngtcp2.lo `test -f 'vquic/ngtcp2.c' || echo './'`vquic/ngtcp2.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/ngtcp2/include -isystem /root/curl-libs/nghttp3/include -fvisibility=hidden -Werror-implicit-function-declaration -O2 -Wno-system-headers -pthread -MT vquic/libcurl_la-ngtcp2.lo -MD -MP -MF vquic/.deps/libcurl_la-ngtcp2.Tpo -c vquic/ngtcp2.c  -fPIC -DPIC -o vquic/.libs/libcurl_la-ngtcp2.o
```

**Comment by bagder** [comment]
It's not there. It should be listed among the `CPPFLAGS` in the configure summary.

Load your `config.log` file and search for "openssl". It shows where it detects it and should contain lines like this:

(this is verbatim from my file so it uses paths to my custom quictls install in my home dir)

~~~
configure:23860: PKG_CONFIG_LIBDIR will be set to "/home/daniel/build-quictls/lib/pkgconfig"
configure:23929: checking for pkg-config
configure:23960: result: /usr/bin/pkg-config
configure:23985: checking for openssl options with pkg-config
configure:23999: result: found
configure:24028: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure:24030: pkg-config: SSL_LDFLAGS: "-L/home/daniel/build-quictls/lib"
configure:24032: pkg-config: SSL_CPPFLAGS: "-I/home/daniel/build-quictls/include"

**Comment by andy-isoc** [comment]
```
configure:20645: checking for openssl options with pkg-config
configure:20659: result: found
configure:20688: pkg-config: SSL_LIBS: "-lssl -lcrypto"
configure:20690: pkg-config: SSL_LDFLAGS: ""
configure:20692: pkg-config: SSL_CPPFLAGS: ""
```
I can't see any lines in the log that match `PKG_CONFIG_LIBDIR`

**Comment by andy-isoc** [comment]
Should `--with-openssl=/root/curl-libs/openssl` in the configure options be `--with-ssl=/root/curl-libs/openssl`?

**Comment by andy-isoc** [comment]
```
root@pulse-ubuntu:~/curl-7.76.1# src/curl --version
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1k ngtcp2/0.1.0-DEV nghttp3/0.1.0-DEV
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
All good now :-)
Thanks for your help. Do you want me to submit a PR to update the docs?

**Comment by bagder** [comment]
We've introduced and are pushing for `--with-openssl` in current master and in the future. It just happens that online docs are built from master so this discrepancy vanishes with the next release.
