### ISSUE TITLE
SFTP listed in the configure and link time protocols, but not avaible at runtime on macOS

### ISSUE THREAD

**Issue by ribtoks** [curl/curl#7046]
### I did this

I'm trying to get `SFTP` to work in curl on macOS 10.14.6. To achieve that I've downloaded `openssl-1.1.1k`, `libssh2-1.9.0` and `curl-7.76.1`.

First I build openssl:
```
./config --prefix="${ROOT_DIR}/libs/debug" \
            --openssldir="${ROOT_DIR}/libs/debug/bin" \
            zlib-dynamic threads shared no-tests \
            --debug
make
make install_sw
```

Then I build libssh2: (note, that it finds openssl because it's installed in the proper directory passed in `CMAKE_INSTALL_PREFIX`)
```
cmake .. -DCMAKE_BUILD_TYPE="debug" \
         -DCMAKE_INSTALL_PREFIX="${ROOT_DIR}/libs/debug" \
         -DCMAKE_PREFIX_PATH="${ROOT_DIR}/libs/debug" \
         -DBUILD_SHARED_LIBS=ON \
         -DCRYPTO_BACKEND=OpenSSL \
         -DBUILD_EXAMPLES=OFF \
         -DBUILD_TESTING=OFF \
         -DENABLE_ZLIB_COMPRESSION=ON \
         -DCMAKE_MACOSX_RPATH=1
make
make install
```

And then I build curl+libcurl via another `CMakeLists.txt` where I apply these options:
```
set(CMAKE_USE_SECTRANSP ON CACHE BOOL "use darwinssl on mac" FORCE)
set(CMAKE_USE_OPENSSL ON CACHE BOOL "use openssl additionally" FORCE)
set(CMAKE_USE_LIBSSH2 ON CACHE BOOL "enable libssh2" FORCE)
```

Note, that my build log has these lines:
```
-- curl version=[7.76.1-DEV]
-- Enabled features: SSL IPv6 unixsockets libz AsynchDNS Largefile alt-svc NTLM MultiSSL HTTPS-proxy
-- Enabled protocols: DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS LDAP MQTT SCP SFTP SMB SMBS TELNET TFTP
-- Enabled SSL backends: OpenSSL Secure Transport
```

(full build log: [build-log.txt](https://github.com/curl/curl/files/6458958/build-log.txt))

After that I run `curl -V` to see the result: (note missing `SFTP`)

```
> DYLD_LIBRARY_PATH=../lib:$DYLD_LIBRARY_PATH ./curl -V
curl 7.76.1-DEV (x86_64-apple-darwin18.7.0) libcurl/7.76.1-DEV SecureTransport zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

### I expected the following

`SFTP` is also present in the runtime

### curl/libcurl version

7.76.1

### operating system

macOS 10.14.6

```
> uname -a
Darwin Tarass-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64 x86_64
```

**Comment by bagder** [comment]
Did you try the configure script as a work-around?

**Comment by bagder** [comment]
> Currently cannot resolve error

I recommend you:
1. build from a release tarball
2. build from a newly unpacked source code tree

**Comment by ribtoks** [comment]
Hi Daniel. Thanks for the suggestion, it worked. I can confirm that when built from the release tarball, curl binary has `SFTP` in the available protocols. Only when building with `cmake` on macOS it does not. Although, `cmake` variant worked for me on Windows 10 and Ubuntu 20.04.

**Comment by bagder** [comment]
I could build with libssh2 on mac:
~~~
$ brew install libssh2
$ cd curl-source-dir
$ mkdir build
$ cd build
$ cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_USE_LIBSSH2=ON ..
$ make -sj
$ ./src/curl -V
curl 7.77.0-DEV (Darwin) libcurl/7.77.0-DEV OpenSSL/1.1.1k zlib/1.2.11 libssh2/1.9.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp

**Comment by ribtoks** [comment]
Ok, I retested the `cmake` variant by adding `OPENSSL_ROOT_DIR` parameter and removing `CMAKE_USE_OPENSSL` parameter and it worked! Huge thanks for your time and help!

P.S. I did not understood from docs that this is the exact way I should use the parameters.
