### ISSUE TITLE
curl can't write file to the dir with leading dot

### ISSUE THREAD

**Issue by YuriGor** [curl/curl#7050]
### I did this
`~/.test$ curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1`
but outpu was:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file node.test: Permission denied
  0 21.2M    0  1085    0     0  20865      0  0:17:45 --:--:--  0:17:45 20865
curl: (23) Failure writing output to destination
```
### I expected the following
```
~/test$ curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.2M  100 21.2M    0     0  66.2M      0 --:--:-- --:--:-- --:--:-- 66.2M
```
notice how it works fine in `test` dir, but fails in `.test` with leading dot while trying same command.

### curl/libcurl version
```
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 libgsasl/1.8.1
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli gsasl GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

Ubuntu21.04:
`Linux fathership 5.11.0-16-generic #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

I found this issue trying to install node using nvm and then found an issue report with same error in nvm project:
https://github.com/nvm-sh/nvm/issues/2504

So this issue is reproducible by others.
Notice wget is working fine in same directories with same URL, so it should not be permissions issue, at least not straightforward.
Maybe curl is trying to use some forbidden tmp dirs under the hood?

**Comment by bagder** [comment]
1.curl doesn't use any "forbidden tmp dirs"
2.I cannot reproduce on my debian unstable box, works perfectly fine:
~~~
$ mkdir .foo
$ cd .foo
$ curl -o hello example.com
$ ls -l hello 
-rw-r--r-- 1 daniel daniel 1256 May 12 08:03 hello

**Comment by jay** [comment]
> Update: works exactly as fine when I repeated this on Ubuntu 20.04

I can't reproduce either. Ubuntu 16 LTS

**Comment by YuriGor** [comment]
For me it also worked on 20.04, but once i installed fresh 21.04 on new laptop - faced with this. Maybe it's for 21.04 only, that guy from nvm issue reported same error as me and hi is on 21.04

**Comment by bagder** [comment]
Either way, I can't see how this is curl doing something wrong or strange. But I can't rule out that ubuntu 21.04 is crazy.

**Comment by jay** [comment]
strace?

**Comment by YuriGor** [comment]
Hi @jay 
`~/.test$ strace curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1`
https://pastebin.ubuntu.com/p/fxHdzsgHbw/

**Comment by jay** [comment]
I don't see anything in that, can you please take one of the success case as well and then we can compare.

**Comment by YuriGor** [comment]
Sure:
`~/test$ strace curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1`
https://pastebin.ubuntu.com/p/bxwxMSvjRm/

btw in snap store all permissions are fine:
![image](https://user-images.githubusercontent.com/6861317/117939492-64f7be00-b308-11eb-908b-5641f1ee2ba9.png)

Will try to remove snap version and install somehow else.

**Comment by bagder** [comment]
I suspect the snap/apparmor stuff we see filling up the strace...

**Comment by YuriGor** [comment]
I removed snap version and installed curl with apt-get - now it works :tada: 
Looks like this issue should go to snapcraft or let it be here?

**Comment by YuriGor** [comment]
Just created a bug there:
https://bugs.launchpad.net/snapcraft/+bug/1928185

**Comment by bagder** [comment]
Then I think we can conclude that this is not a curl bug?

**Comment by YuriGor** [comment]
Guess so, thank you all for help!
