### ISSUE TITLE
autoreconf: 'configure.ac' or 'configure.in' is required

### ISSUE THREAD

**Issue by lvyinggithub** [curl/curl#7052]
When I use Dockerfile, I get an error. linux version is centos:8

### I did this
RUN yum install -y autoconf 
RUN git clone https://github.com/curl/curl.git && \
    autoreconf -fi && \
    ./curl/buildconf  && \
    ./configure --with-ssl --enable-dict --enable-ftp --enable-imap \
    --enable-ldap --enable-ldaps --enable-pop3 --enable-proxy \
    --enable-rtsp --enable-smtp --enable-telnet --enable-tftp \
    --enable-zlib --without-ca-bundle --without-gnutls --without-libidn \
    --without-librtmp --without-libssh2 --without-nss --without-zlib && \
    make && \
    make install && \
    curl -V 

### curl/libcurl version

https://github.com/curl/curl/commit/a9bc819c89cae273bacc375ebcd71debbfaa79fe

error 

Step 12/68 : RUN git clone https://github.com/curl/curl.git &&     autoreconf -fi &&     ./curl/buildconf  &&     ./configure --with-ssl --enable-dict --enable-ftp --enable-imap     --enable-ldap --enable-ldaps --enable-pop3 --enable-proxy     --enable-rtsp --enable-smtp --enable-telnet --enable-tftp     --enable-zlib --without-ca-bundle --without-gnutls --without-libidn     --without-librtmp --without-libssh2 --without-nss --without-zlib &&     make &&     make install &&     curl -V
 ---> Running in 6b6afe153770
Cloning into 'curl'...
autoreconf: 'configure.ac' or 'configure.in' is required
The command '/bin/sh -c git clone https://github.com/curl/curl.git &&     autoreconf -fi &&     ./curl/buildconf  &&     ./configure --with-ssl --enable-dict --enable-ftp --enable-imap     --enable-ldap --enable-ldaps --enable-pop3 --enable-proxy     --enable-rtsp --enable-smtp --enable-telnet --enable-tftp     --enable-zlib --without-ca-bundle --without-gnutls --without-libidn     --without-librtmp --without-libssh2 --without-nss --without-zlib &&     make &&     make install &&     curl -V' returned a non-zero code: 1

**Comment by dfandrich** [comment]
On Tue, May 11, 2021 at 08:30:15PM -0700, rain wrote:
> When I use Dockerfile, I get an error. linux version is centos:8
> 
> I did this
> 
> RUN yum install -y autoconf
> RUN git clone https://github.com/curl/curl.git &&
> autoreconf -fi &&
> ./curl/buildconf &&

The CWD must be ./curl/ in order to run buildconf/autoconf.

> ./configure --with-ssl --enable-dict --enable-ftp --enable-imap
> --enable-ldap --enable-ldaps --enable-pop3 --enable-proxy
> --enable-rtsp --enable-smtp --enable-telnet --enable-tftp
> --enable-zlib --without-ca-bundle --without-gnutls --without-libidn
> --without-librtmp --without-libssh2 --without-nss --without-zlib &&
> make &&
> make install &&
> curl -V

**Comment by lvyinggithub** [comment]
Thank you very much!!
 I modified the code , it was installed successfully,
but,The LDAP configuration file is not valid. I can't find any information about LDAP,


RUN git clone https://github.com/curl/curl.git && \
    cd ./curl/ && \
    ls && \
    ./buildconf && \
    ./configure --with-ssl --enable-dict --enable-ftp --enable-imap \
    --enable-ldap --enable-ldaps --enable-pop3 --enable-proxy \
    --enable-rtsp --enable-smtp --enable-telnet --enable-tftp \
    --enable-zlib --without-ca-bundle --without-gnutls --without-libidn \
    --without-librtmp --without-libssh2 --without-nss --without-zlib &&\
    make &&\
    make install &&\
    curl -V

I ignored the message:  *** Do not use buildconf. Instead, just use: autoreconf -fi


successful info:

ubuntu@ip-172-20-224-176:~/rain/test-docker-wukong$ docker run curl:test /bin/bash -c "curl -V"
curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/1.1.1g-fips
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets



Unable to connect to LDAP successfully:

ubuntu@ip-172-20-224-176:~/rain/test-docker-wukong$ docker run a:tag /bin/bash -c "curl ldap://xxx:389"
curl: (1) Protocol "ldap" not supported or disabled in libcurl

**Comment by lvyinggithub** [comment]
I've tried other installation methods,
but,LDAP is not enabled properly, did I miss something?

RUN wget https://curl.haxx.se/download/curl-7.76.1.tar.gz && \
    gunzip -c curl-7.76.1.tar.gz | tar xvf - && \
    cd curl-7.76.1 && \
    ./configure --prefix=/usr/local/curl/ --enable-ldap --with-ssl --enable-ldaps --with-ldap-lib  --with-lber-lib && \
    make && \
    make install && \
    mv /usr/bin/curl /usr/bin/curl.bak && \
    ln -s /usr/local/curl/bin/curl /usr/bin/curl && \
    ldconfig && \
    curl -V

**Comment by bagder** [comment]
> LDAP is not enabled properly, did I miss something?

This is an issue tracker, not a support forum. The issue you posted about was solved.

If you need help, use the curl-library mailing list or try the "[discussions](https://github.com/curl/curl/discussions)" here on github.

(you need the openldap dev package installed)

**Comment by jzakrzewski** [comment]
@bagder For me it's a bug that the build succeeds silently discarding explicit user request for LDAP.

**Comment by bagder** [comment]
Then please raise it as an issue!

**Comment by lvyinggithub** [comment]
There must be a lot of people who have the same problem,hope this page can help others.
I think I found the issue because version 7.76.1 didn't work, but I switched to source compilation and after installing the dependencies, LDAP worked fine, maybe one of the changes fixed the issue,without going to GitHub, this issue  might not be solved.



RUN yum install -y libgsasl libpsl autoconf  openldap-devel.x86_64
#apt-get install libldap2-dev

 7.76.1.tar.gz is fail:


Step 11/16 : RUN  yum  install openldap-devel.x86_64 -y
 ---> Using cache
 ---> 7052fe5af5ba
Step 12/16 : RUN wget https://curl.haxx.se/download/curl-7.76.1.tar.gz && gunzip -c curl-7.76.1.tar.gz | tar xvf - && cd curl-7.76.1 && ./configure --prefix=/usr/local/curl/ --enable-ldap --with-ssl --enable-ldaps --with-ldap-lib --with-lber-lib && make && make install && mv /usr/bin/curl /usr/bin/curl.bak && ln -s /usr/local/curl/bin/curl /usr/bin/curl && ldconfig && curl -V
 ---> Using cache

ubuntu@ip-172-20-224-176:~/rain/test-docker-wukong$ docker run -t a:tag /bin/bash -c "curl -V"
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1g-fips zlib/1.2.11
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets




source code version is ok:


Step 12/16 : RUN git clone https://github.com/curl/curl.git &&     cd ./curl/ &&     ls &&     ./buildconf &&     ./configure --with-ssl --enable-dict --enable-ftp --enable-imap     --enable-ldap --enable-ldaps  &&    make &&    make install &&    curl -V
 ---> Using cache
 ---> 6ac87d029d1e


ubuntu@ip-172-20-224-176:~/rain/test-docker-wukong$ docker run -t a:tag /bin/bash -c "curl -V"                                                                                               curl 7.77.0-DEV (x86_64-pc-linux-gnu) libcurl/7.77.0-DEV OpenSSL/1.1.1g-fips zlib/1.2.11
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**Comment by bagder** [comment]
> because version 7.76.1 didn't work

Sorry, but I've not seen you mention or report anything that didn't work with 7.76.1. The issue you raised here above was because of a user error on your part. Can you please elaborate on what the problem is with 7.76.1 ?

**Comment by lvyinggithub** [comment]
In 7.76.1 version,
the test environment is Dockerfile(FROM centos:8),
the use of the command is invalid(--enable-ldaps --with-ldap),


curl -V

missing LDAP that should be enabled,



normal :

Protocols: dict file ftp ftps gopher gophers http https imap imaps (ldap ldaps) mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp

**Comment by bagder** [comment]
There has been no change in the LDAP library detection logic in configure between 7.76.1 and current git master.

**Comment by lvyinggithub** [comment]
I don't know why,this is script. 

$ docker -v
Docker version 20.10.5, build 55c4c88

$ docker build -t a:tag .

$ docker run a:tag /bin/bash -c "curl -V"
curl 7.76.1 (x86_64-pc-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1g-fips zlib/1.2.11
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets



Dockerfile:


FROM centos:8


MAINTAINER Ying Lv


#64 bit

RUN rpm -iUvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN yum install -y libcurl-devel

RUN yum install -y libgsasl libpsl autoconf libtool 

# Upgrade...

RUN yum upgrade  -y




RUN yum install -y python3 expect openssl-devel python ansible java-1.8.0-openjdk wget unzip openssh-clients gcc-c++ make jq  zip unzip git  --skip-broken



RUN  yum  install openldap-devel.x86_64 -y



#ok
RUN wget https://curl.haxx.se/download/curl-7.76.1.tar.gz && \
    gunzip -c curl-7.76.1.tar.gz | tar xvf - && \
    cd curl-7.76.1 && \
    ./configure --prefix=/usr/local/curl/ --enable-ldap --with-ssl --enable-ldaps --with-ldap-lib --with-lber-lib && \
    make && \
    make install && \
    mv /usr/bin/curl /usr/bin/curl.bak && \
    ln -s /usr/local/curl/bin/curl /usr/bin/curl && \
    ldconfig && \
    curl -V
#failure
#RUN git clone https://github.com/curl/curl.git && \
#    cd ./curl/ && \
#    ls && \
#    ./buildconf && \
#    ./configure --with-ssl --enable-dict --enable-ftp --enable-imap \
#    --enable-ldap --enable-ldaps  &&\
#    make &&\
#    make install &&\
#    curl -V

**Comment by bagder** [comment]
So you don't install any openldap devel package?

**Comment by lvyinggithub** [comment]
RUN yum install openldap-devel.x86_64 -y

**Comment by lvyinggithub** [comment]
The above is the complete code, including OpenLDAP

**Comment by lvyinggithub** [comment]
Maybe you can try it in Docker

**Comment by lvyinggithub** [comment]
Source code is normal, using tar.gz is error

**Comment by bagder** [comment]
As always when configure doesn't do what you expect, I recommend 
When configure fails to do what you expected it to, for example to find the libraries you wanted it to find, then the standard next step is to open `config.log` in a text editor, search for the library/test that didn't go the way you expected and see what you can figure out based on that.

We've learned that this is a very effective way and reading this file often reveals details that can take you further in debugging your build/configure issue.
