### ISSUE TITLE
libcurl 7.68.0 - SIGTERM now returns error code 43

### ISSUE THREAD

**Issue by carlzogh** [curl/curl#7059]
Hello,

I'm having an issue with a C++ application that makes use of libcurl since updating to `7.68.0` (validated that the breaking change was introduced in that release and is still in `7.76.1`).

Looking at the [changelog for 7.68.0](https://curl.se/changes.html#7_68_0) nothing jumps out at me so I'd appreciate a help in identifying and addressing (or mitigating) the regression if there is one, or navigating my way through the behavior change if this was intentional.

### I did this
The application starts an HTTP GET request (with `curl_easy_perform`) to an endpoint and gets shut down with SIGTERM. Previously to `7.68.0` this would return a 0 exit code to my application but now it returns an exit code of `43: CURLE_BAD_FUNCTION_ARGUMENT`.

Compiled libcurl with `--enable-debug` and I can see the following logs:
```
{Start curl HTTP GET request to PATH}
[DEBUG] CURL DBG: STATE: INIT => CONNECT handle 0x7fea282d7de8; line 1605 (connection #-5000)
[DEBUG] CURL DBG: Found bundle for host {HOST}: 0x7fea282d9e68 [serially]
[DEBUG] CURL DBG: Re-using existing connection! (#0) with host {HOST}
[DEBUG] CURL DBG: Connected to {HOST} ({HOST}) port {PORT} (#0)
[DEBUG] CURL DBG: STATE: CONNECT => DO handle 0x7fea282d7de8; line 1654 (connection #0)
[DEBUG] CURL DBG: GET /{PATH} HTTP/1.1
[DEBUG] CURL DBG: STATE: DO => DO_DONE handle 0x7fea282d7de8; line 1870 (connection #0)
[DEBUG] CURL DBG: STATE: DO_DONE => PERFORM handle 0x7fea282d7de8; line 1991 (connection #0)

{SIGTERM received}

[DEBUG] CURL DBG: Marked for [closure]: Removed with partial response
[DEBUG] CURL DBG: multi_done
[DEBUG] CURL DBG: Closing connection 0
[DEBUG] CURL DBG: The cache now contains 0 members

=> curl exit code: 43
```

### I expected the following
```
=> curl exit code: 0
```

### curl/libcurl version

`7.68.0`+

### operating system

Amazon Linux 2

**Comment by jay** [comment]
Sometimes if a process has a time limit it is sent a SIGTERM. Also your callbacks may have something to do with it. Error 43 is CURLE_BAD_FUNCTION_ARGUMENT which is used a number of places in the library. You could try [bisecting](https://github.com/curl/curl/wiki/how-to-git-bisect).

**Comment by carlzogh** [comment]
Thanks @jay - bisecting points to https://github.com/curl/curl/commit/f3c35e371cc70f1b6bc33f7faa904d37d1567eb3 as being the first bad commit that introduced this error

**Comment by carlzogh** [comment]
Removing `#define ENABLE_WAKEUP` fixed the issue - diff:
```diff
diff --git lib/multihandle.h lib/multihandle.h
index a26fb619a..cc0062a9c 100644
--- lib/multihandle.h
+++ lib/multihandle.h
@@ -67,9 +67,6 @@ typedef enum {
 
 #define CURLPIPE_ANY (CURLPIPE_MULTIPLEX)
 
-#if defined(USE_SOCKETPAIR) && !defined(USE_BLOCKING_SOCKETS)
-#define ENABLE_WAKEUP
-#endif
 
 /* This is the struct known as CURLM on the outside */
 struct Curl_multi {
```

Digging further, I've reverted the above diff and found that the offending code is https://github.com/curl/curl/pull/4608/files#diff-f25cb725c8f9fcc9a6532bed11a8f9c22b60c17edd2d4a3615bd7ceaa6ad8c18R1143-R1149 and removing it cleared the issue
```diff
diff --git lib/multi.c lib/multi.c
index f30e41a65..e80bad546 100755
--- lib/multi.c
+++ lib/multi.c
@@ -1140,14 +1140,6 @@ static CURLMcode Curl_multi_wait(struct Curl_multi *multi,
     ++nfds;
   }
 
-#ifdef ENABLE_WAKEUP
-  if(use_wakeup && multi->wakeup_pair[0] != CURL_SOCKET_BAD) {
-    ufds[nfds].fd = multi->wakeup_pair[0];
-    ufds[nfds].events = POLLIN;
-    ++nfds;
-  }
-#endif
-
   if(nfds) {
     int pollrc;
     /* wait... */
```

**Comment by bagder** [comment]
That also removes the functionality.

We would appreciate if you could tell us how to reproduce this issue as then we could help you with it from our ends!

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!
