### ISSUE TITLE
Bad font change in curl_easy_recv.3

### ISSUE THREAD

**Issue by eric-s-raymond** [curl/curl#706]
Patch follows.

--- curl_easy_recv.3-unpatched	2016-03-03 08:51:09.090412391 -0500
+++ curl_easy_recv.3	2016-03-03 08:51:20.306375341 -0500
@@ -42,7 +42,7 @@
 bytes.
 
 To establish the connection, set \fBCURLOPT_CONNECT_ONLY(3)\fP option before
-calling \fIcurl_easy_perform(3)\fP or \cIcurl_multi_perform(3)\fP. Note that
+calling \fIcurl_easy_perform(3)\fP or \fIcurl_multi_perform(3)\fP. Note that
 \fIcurl_easy_recv(3)\fP does not work on connections that were created without
 this option.

**Comment by jay** [comment]
Thanks but this was already fixed in bb0acba.
