### ISSUE TITLE
curiosity: "curl  -X POST -H 'Transfer-Encoding: chunked'  http://example.com" hangs

### ISSUE THREAD

**Issue by dkegel-fastly** [curl/curl#7076]
Sending a GET with a body provokes ill-defined behavior (cf. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET ).
I did it accidentally while constructing a smoke test which sent a bunch of fetches both with and without chunked encoding, and was surprised to find that curl hangs in this case.

The command

```
$ curl  -H 'Transfer-Encoding: chunked' http://example.com
```

hangs; with tcpdump you can see it is sending a GET request, has sent the header but has not indicated the body has ended,
and so the server does not begin replying.

I suppose I expect curl to realize there is no body, and indicate the end of the request body with a zero-length terminating chunk.

You can rescue the command by adding a body, e.g.
```
$ curl -d dummy  -H 'Transfer-Encoding: chunked'  http://example.com
```
in which case it sends a POST request with a body, and all is well.

But just forcing POST does not rescue it; the command

```
$ curl -X POST -H 'Transfer-Encoding: chunked'  http://example.com
```
also hangs.  That is also not an especially useful request, but probably should not hang.

```
$ curl -V
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

$ uname -a
Darwin Dans-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

**Comment by piru** [comment]
I don't think this is a bug. There are numerous ways you can get curl to get stuck like this. One (obvious) example:
`curl -H "content-length: 3000" http://example.com`
In my opinion it is not up to curl to try to second-guess the user and try to "correct" the behaviour in these cases.

**Comment by dkegel-fastly** [comment]
Either way, this is probably of little practical consequence.  
I filed the issue report for completeness, and to document the (obvious?) workaround.

**Comment by bagder** [comment]
I don't consider this a bug, this is just the nature of HTTP and what happens if you "trick" curl by including funny headers. There are numerous ways you can do this, and there's no way curl can or want to prevent that.
