### ISSUE TITLE
Unrecognized link option /MANIFEST:NO warning is issued when building with CMake

### ISSUE THREAD

**Issue by freejack811** [curl/curl#7084]
### I did this
1. Use CMake to build curl's MSVC project.
2. "Visual Studio 15 2017" is specified as the generator.
3. Use MSVC2017 to compile the project.
4. Unrecognized link option /MANIFEST:NO warning is issued

### I expected the following
Avoid the warning.

### curl/libcurl version
curl-7_73_0

[curl -V output]

### operating system
Windows Platform

**Comment by jay** [comment]
What is the error you see? [/MANIFEST:NO](https://docs.microsoft.com/en-us/cpp/build/reference/manifest-create-side-by-side-assembly-manifest?view=msvc-150) is supposed to be supported by the Microsoft linker.

https://github.com/curl/curl/blob/566b74a0e19b9aa610f4931e5bfd339bcf8e9147/CMakeLists.txt#L1264-L1266

@vszakats

**Comment by freejack811** [comment]
This is the content of the output window of the MSVC IDE, line ”.......Omit.......“ means omitted content:
2> Microsoft (R) Build Engine version **15.9.21**+g9802d43bc3 for .NET Framework
2> Copyright (C) Microsoft Corporation. All rights reserved.
2>
2>  Checking Build System
2>  Building Custom Rule D:/CurrentWorks/curl-7_73_0/lib/CMakeLists.txt
2>  altsvc.c
2>  amigaos.c
2>  asyn-ares.c
.......Omit.......
2>  Generating Code...
2>LINK : warning LNK4044: unrecognized option “/MANIFEST:NO”；ignored [D:\CurrentWorks\STLibrarys1_0\2017\lib\libcurl.vcxproj]
2>  libcurl.vcxproj -> D:\CurrentWorks\STLibrarys1_0\2017\lib\Debug\libcurl-d.lib

**Comment by freejack811** [comment]
I think the "/MANIFEST:NO" option can only be used when generating dynamic link libraries and executable programs, not when generating static libraries. Therefore, I used the MSVC wizard to generate two projects for testing, one to generate a static library and the other to generate a dynamic library, and all added "/MANIFEST:NO" option to the link command line. The result was the same as I expected.

The following is the output of the generated static library:
1>------ Build started: Project: StaticLib1, Configuration: Debug Win32 ------
1>pch.cpp
1>StaticLib1.cpp
1>LINK : warning LNK4044: **unrecognized option “/MANIFEST:NO”**；ignored
1>StaticLib1.vcxproj -> d:\test\StaticLib1\Debug\StaticLib1.lib
1>Done building project “StaticLib1.vcxproj”.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

The following is the output of the generated dynamic library:
1>------ Build started: Project: Dll1, Configuration: Debug Win32 ------
1>pch.cpp
1>dllmain.cpp
1>Dll1.vcxproj -> d:\test\Dll1\Debug\Dll1.dll
1>Done building project “Dll1.vcxproj”.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by jzakrzewski** [comment]
From what I remember, `CMAKE_EXE_LINKER_FLAGS` are not supposed to be applied to the static library. I don't see how the `/MANIFEST:NO` makes it's way to static library flags.

**Comment by freejack811** [comment]
> @vszakats
So I searched the source code tree of curl. As you mentioned, the CMake script of curl only assigns the "/MANIFEST:NO" option to the CMake variable CMAKE_EXE_LINKER_FLAGS, but it is strange that CMake applies it to libcurl that generates static libraries. engineering. I opened the libcurl.vcxproj generated by CMake, there will be the following lines:
.......Omit.......
    </Midl>
    <Lib>
      **<AdditionalOptions>%(AdditionalOptions) /machine:X86 /machine:X86 /MANIFEST:NO</AdditionalOptions>**
    </Lib>
  </ItemDefinitionGroup>
.......Omit.......
My CMake Version is : 3.20.2

**Comment by freejack811** [comment]
Eventually I found the source of the bug. The curl CMake script first assigned the "/MANIFEST:NO" option to CMAKE_EXE_LINK_FLAGS:

Content of curl-7_73_0\CMakeLists.txt(1258)
------------------------------------------------------------
if(MSVC)
  # Disable default manifest added by CMake
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO")
.......Omit.......

then, the CMakeList.txt which in lib directory assigned the value of CMAKE_EXE_LINKER_FLAGS to the STATIC_LIBRARY_FLAGS property of static library.
Content of curl-7_73_0\lib\CMakeLists.txt(92)
------------------------------------------------------------
if(MSVC AND NOT BUILD_SHARED_LIBS)
  set_target_properties(${LIB_NAME} PROPERTIES STATIC_LIBRARY_FLAGS ${CMAKE_EXE_LINKER_FLAGS})
endif()

**Comment by freejack811** [comment]
Please forgive me for wasting your precious time. I found that the bug has actually been corrected in curl 7.74.0. very sorry. I have revised the comment I submitted.
