### ISSUE TITLE
hyperstream: couldn't get response when using hyper

### ISSUE THREAD

**Issue by kevinburkemeter** [curl/curl#7122]
Commit c3eefa95c31f55657f0af422e8268d738f689066 contains a fix for #7064. Unfortunately, when I try to compile curl with rustls+hyper using this patch, I get:

```
curl: (56) hyperstream: couldn't get response
```

And then no response output where I would expect to see it.

on a variety of HTTP responses, HTTP/1.1, TLS with HTTP/2. I can reproduce using either http://public.meter.com or https://public.meter.com (both of which are Amazon ALB's), for example.

On other sites, for example https://jsonip.com, I see `curl: (56) hyperstream: couldn't get response` but then the response also prints out.

If I revert the commit mentioned there, I don't see the issue appearing anymore, and I also can't reproduce the 1 second sleep I was occasionally seeing (perhaps something changed in crustls or Hyper?)

Here are more logs from success and failure cases. https://gist.github.com/kevinburkemeter/c7fd42f5da7b78e2683179d874f0a475

**Comment by bagder** [comment]
I think we should start with reverting this. I can't even run test case 1 if I don't revert c3eefa9 ... 

I'll make a PR
