### ISSUE TITLE
curl 7.76.1-DEV with quiche POST file failed

### ISSUE THREAD

**Issue by gangbanlau** [curl/curl#7125]
### I did this
POST request failed when use curl with quiche upload file to nginx-quiche. 

how to reproduce this error:
. setup nginx-quiche as http3 reverse proxy in front of python upload server. I have prepared docker-compose test bed.

    git clone https://github.com/gangbanlau/docker-nginx-quiche.git
    cd docker-nginx-quiche
    copy https cert files into nginx_data directory. filename should be fullchain.pem and privkey.pem
    check env file "./env"
    docker-compose --env-file ./env up -d --build
    use browser with http3 enabled access https://your-hostname:6443/upload
    the file should be uploaded successfully. you can access https://your-hostname:6443/ to verify file uploaded. I verified file uploaded with google chrome Version 90.0.4430.212 (Official Build) (64-bit). the md5sum is matched.

. use curl with quiche POST file.
docker run -it --rm ymuski/curl-http3 curl -V

```
curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV BoringSSL quiche/0.8.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL UnixSockets
```

docker run -it --rm -v $PWD:/work ymuski/curl-http3 curl -v https://your-hostname:6443/upload --http3 -F "file_1=@/work/yourfile"

```
*   Trying 192.168.32.72:6443...
* Connect socket 5 over QUIC to 192.168.32.72:6443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* Connected to your-hostname () port 6443 (#0)
* h3 [:method: POST]
* h3 [:path: /upload]
* h3 [:scheme: https]
* h3 [:authority: your-hostname:6443]
* h3 [user-agent: curl/7.76.1-DEV]
* h3 [accept: */*]
* h3 [content-length: 23303]
* h3 [content-type: multipart/form-data; boundary=------------------------22f6515dab408e16]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55ba9c564350)
> POST /upload HTTP/3
> Host: your-hostname:6443
> user-agent: curl/7.76.1-DEV
> accept: */*
> content-length: 23303
> content-type: multipart/form-data; boundary=------------------------22f6515dab408e16
> 
* Pass on 23303 body bytes to quiche
* Pass on 11479 body bytes to quiche
* Connection #0 to host your-hostname left intact
curl: (55) Failed sending data to the peer
```

### I expected the following

Upload file success.

### curl/libcurl version

[curl -V output]

curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV BoringSSL quiche/0.8.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL UnixSockets

### operating system

Linux 26b157a0d0b7 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gangbanlau** [comment]
curl with quiche 0.8.1 failed too.

docker run -it --rm gang/curl-quiche:0.8.1 curl -V
```
curl 7.76.1-DEV (x86_64-pc-linux-gnu) libcurl/7.76.1-DEV BoringSSL quiche/0.8.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL UnixSockets
```

success with http1.1

docker run -it --rm -v $PWD:/work gang/curl-quiche:0.8.1 curl -v https://your-hostname:6443/upload --http1.1 -F ```
"file_1=@/work/m-1-399650655.m4s"
*   Trying 192.168.32.72:6443...
* Connected to your-hostname (192.168.32.72) port 6443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=your-hostname
*  start date: May 11 03:15:37 2021 GMT
*  expire date: Aug  9 03:15:37 2021 GMT
*  subjectAltName: host "your-hostname" matched cert's "your-hostname"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> POST /upload HTTP/1.1
> Host: your-hostname:6443
> User-Agent: curl/7.76.1-DEV
> Accept: */*
> Content-Length: 23303
> Content-Type: multipart/form-data; boundary=------------------------9ddf23a98cbefb5f
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.16.1
< Date: Tue, 25 May 2021 04:36:46 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 460
< Connection: keep-alive
< alt-svc: h3-29=":6443"; ma=86400,h3=":6443"; ma=86400
< 
<!DOCTYPE html>
<html>
<head>
<title>File Upload</title>
<meta name="viewport" content="width=device-width, user-scalable=no" />
<style type="text/css">
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: #fff;
  }
}
</style>
</head>
<body>
<h1>File Upload</h1>
<form action="upload" method="POST" enctype="multipart/form-data">
<input name="file_1" type="file" />
<br />
<br />
<input type="submit" />
</form>
</body>
* Connection #0 to host your-hostname left intact
</html>
```
failed with http3

docker run -it --rm -v $PWD:/work gang/curl-quiche:0.8.1 curl -v https://your-hostname:6443/upload --http3 -F "file_1=@/work/m-1-399650655.m4s"
```
*   Trying 192.168.32.72:6443...
* Connect socket 5 over QUIC to 192.168.32.72:6443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* Connected to your-hostname () port 6443 (#0)
* h3 [:method: POST]
* h3 [:path: /upload]
* h3 [:scheme: https]
* h3 [:authority: your-hostname:6443]
* h3 [user-agent: curl/7.76.1-DEV]
* h3 [accept: */*]
* h3 [content-length: 23303]
* h3 [content-type: multipart/form-data; boundary=------------------------0061dcedd0bdcc9c]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55619870c350)
> POST /upload HTTP/3
> Host: your-hostname:6443
> user-agent: curl/7.76.1-DEV
> accept: */*
> content-length: 23303
> content-type: multipart/form-data; boundary=------------------------0061dcedd0bdcc9c
> 
* Pass on 23303 body bytes to quiche
* Pass on 11479 body bytes to quiche
* Connection #0 to host your-hostname left intact
curl: (55) Failed sending data to the peer
```

**Comment by bagder** [comment]
I recommend always trying with curl's git master (and quiche master) before deeming it doesn't work. But also: we have several known bugs already regarding curl's HTTP/3 functionality so unfortunately it is not expected to behave correctly yet, We greatly appreciate all the help we can get to fix those issues.

**Comment by gangbanlau** [comment]
I have make a trial with curl git master and quiche git master. POST file failed.

docker run -it --rm -v $PWD:/work gang/curl-quiche:master curl -V
```
curl 7.77.1-DEV (x86_64-pc-linux-gnu) libcurl/7.77.1-DEV BoringSSL quiche/0.8.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL UnixSockets

```

```
docker run -it --rm -v $PWD:/work gang/curl-quiche:master curl -v https://your-server:6443/upload --http3 -F "file_1=@/work/m-1-399650655.m4s"
*   Trying 192.168.32.72:6443...
* Connect socket 5 over QUIC to 192.168.32.72:6443
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
* Connected to your-server () port 6443 (#0)
* h3 [:method: POST]
* h3 [:path: /upload]
* h3 [:scheme: https]
* h3 [:authority: your-server:6443]
* h3 [user-agent: curl/7.77.1-DEV]
* h3 [accept: */*]
* h3 [content-length: 23303]
* h3 [content-type: multipart/form-data; boundary=------------------------f6cb65fbca70ad02]
* Using HTTP/3 Stream ID: 0 (easy handle 0x5558750b6410)
> POST /upload HTTP/3
> Host: your-server:6443
> user-agent: curl/7.77.1-DEV
> accept: */*
> content-length: 23303
> content-type: multipart/form-data; boundary=------------------------f6cb65fbca70ad02
> 
* Pass on 23303 body bytes to quiche
* Pass on 11479 body bytes to quiche
* Connection #0 to host lowlatency.tfiproject.com left intact
curl: (55) Failed sending data to the peer
```

Dockerfile from github for this evaluation

```
FROM ubuntu:18.04 AS builder

LABEL maintainer="Yury Muski <muski.yury@gmail.com>"

WORKDIR /opt

ARG CURL_VERSION=master
ARG QUICHE_VERSION=master

RUN apt-get update && \
    apt-get install -y build-essential git autoconf libtool cmake golang-go curl;

# https://github.com/curl/curl/blob/master/docs/HTTP3.md#quiche-version

# install rust & cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y -q;

RUN git clone --recursive https://github.com/cloudflare/quiche

# build quiche
RUN export PATH="$HOME/.cargo/bin:$PATH" && \
    cd quiche && \
    git checkout $QUICHE_VERSION && \
    cargo build --release --features ffi,pkg-config-meta,qlog && \
    mkdir deps/boringssl/src/lib && \
    ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) deps/boringssl/src/lib/


# add curl
RUN git clone https://github.com/curl/curl
RUN cd curl && \
    git checkout $CURL_VERSION && \
    ./buildconf && \
    ./configure LDFLAGS="-Wl,-rpath,/opt/quiche/target/release" --with-ssl=/opt/quiche/deps/boringssl/src --with-quiche=/opt/quiche/target/release --enable-alt-svc && \
    make && \
    make DESTDIR="/ubuntu/" install


FROM ubuntu:18.04
RUN apt-get update && apt-get install -y curl

COPY --from=builder /ubuntu/usr/local/ /usr/local/
COPY --from=builder /opt/quiche/target/release /opt/quiche/target/release

# Resolve any issues of C-level lib
# location caches ("shared library cache")
RUN ldconfig

WORKDIR /opt
# add httpstat script
RUN curl -s https://raw.githubusercontent.com/b4b4r07/httpstat/master/httpstat.sh >httpstat.sh && chmod +x httpstat.sh

CMD ["curl"]

```
