### ISSUE TITLE
OpenSSL's new multi-threading API breakage

### ISSUE THREAD

**Issue by gvanem** [curl/curl#713]
Building with OpenSSL 1.1.0-pre4 (from OpenSSL Github repo at 3-March 2016), now causes this compile error:
```
vtls/openssl.c: In function 'Curl_ossl_cleanup':
vtls/openssl.c:745:3: error: too many arguments to function 'ERR_remove_thread_state'
   ERR_remove_thread_state(NULL);
   ^
```

The OpenSSL API-change that broke this is `Convert ERR_STATE to new multi-threading API`: https://github.com/openssl/openssl/commit/8509dcc9f319190c565ab6baad7c88d37a951d1c

In `openssl/err.h` it is now prototyped as `void ERR_remove_thread_state(void);`
So maybe for this `new multi-threading API`, we can we do:
```
@@ -732,7 +732,11 @@

   /* Free thread local error state, destroying hash upon zero refcount */
 #ifdef HAVE_ERR_REMOVE_THREAD_STATE
+  #if (OPENSSL_VERSION_NUMBER >= 0x10100004L)
+  ERR_remove_thread_state();
+  #else
   ERR_remove_thread_state(NULL);
+  #endif
 #else
   ERR_remove_state(0);
 #endif
```

**Comment by bagder** [comment]
Thanks! I modified the logic slightly to avoid the nested #ifdefs before I merged it.

**Comment by gvanem** [comment]
IMHO, nothing wrong with nested `#if defined(xx)` if indented clearly. But that's probably an issue for you new *CODING-standard* :smile:

**Comment by bagder** [comment]
heh, no I wouldn't say there's anything wrong per se, I just think that I manged to improve the readability in this case this way! 

BTW I ran straight into #717 after this...
