### ISSUE TITLE
travis-ci shuts down the free tier for us

### ISSUE THREAD

**Issue by bagder** [curl/curl#7150]
We've run CI on travis-ci since 2013. We've used their free tier as an open source project. For a while they also graciously boosted our CPU performance to help sponsor us (that plan silently ended on March 6, 2021).

Now, travis-ci is transitioning to their new .com domain and the current (old) .org version is being shut down.

On the new home we can ask for the Open source tier. To be considered for that tier there are a few requirements. Here's a list from an email when the status was requested for another project:

- You are a project lead or regular committer (latest commit in the last month)
- Project must be at least 3 months old and is in active development (with regular commits and activity)
- Project meets the OSD specification
- Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
- Project can not provide commercial services or distribute paid versions of the software

In particular the fourth item we cannot comply with. I earn my living doing curl support and I can work on curl during work hours because of this. Apparently travis doesn't approve of paychecks in combination with open source, so we do not meet the criteria for the tree tier.

Maybe we need to transition the travis CI jobs over to other services? As of this writing, we have 33 separate jobs on travis.

## Self-hosted runners

Maybe github actions [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) is the way for us?

## Travis Pricing?

Another option would be to use the curl fund to pay for travis. [pricing](https://travis-ci.com/account/plan). $129/month **"2 Concurrent plan"** is probably roughly the setup we had?

## Previous travis quote

Quote from their site in 2020: "Testing your open source projects will always be free!":

![Screenshot_2021-05-31 Travis CI - Test and Deploy Your Code with Confidence](https://user-images.githubusercontent.com/177011/120146781-e6df5680-c1e5-11eb-86ed-67d1035ffaf1.png)

## Other CI Services in use

We already make heavy use of Azure Pipelines, Github Actions and Appveyor. We also use Cirrus CI but it could be used more.

**Comment by yawaramin** [comment]
Plan prices are here https://travis-ci.com/plans

**Comment by bagder** [comment]
Thanks, updated accordingly!

**Comment by roidelapluie** [comment]
Do you have an idea of the resource / time consumed by travis CI?

**Comment by bagder** [comment]
> Do you have an idea of the resource / time consumed by travis CI?

A recent "round" was sumed up by travis like this: "Total time 12 hrs 30 min 23 sec ". Not sure it answers your question, but I don't think I can extract that info with much more detail?

**Comment by roidelapluie** [comment]
https://travis-ci.org/github/curl?tab=insights

**Comment by bagder** [comment]
I'm afraid that page is completely broken when I look at it:

![Screenshot_2021-05-31 curl - Travis CI](https://user-images.githubusercontent.com/177011/120122791-5dab2e00-c1ab-11eb-8e56-772a1574ebaf.png)

**Comment by roidelapluie** [comment]
Oh, same here. I was thinking it was a permission issue.

By digging:
![s500](https://user-images.githubusercontent.com/291750/120122820-92b78080-c1ab-11eb-897b-03c51694f26f.png)

**Comment by roidelapluie** [comment]
This is a lot. I was thinking about circleci but the open source tier would be like 300 hours/months on a medium machine.

**Comment by ahmeddrawy** [comment]
Interested to help, can you tell me what's the prerequisites?
I worked with Gitlab CI/CD, Github actions, K8S before

**Comment by mnaser** [comment]
I brought up this offer over Twitter but putting it down here as well to have a documented option.

We would be happy to run this over our Zuul service from VEXXHOST (Zuul is an open source gating systems that was born out of OpenStack - https://zuul-ci.org/) -- so the whole thing would be transparent.  Alternatively, we're happy to supply a fleet of VMs in our public cloud that can run GitHub Actions self-hosted runners -- we can run both x86 and aarch64 runners as well.

We're involved in open source for a long time, run a full open source stack and have been providing resources to several open source projects such as some Terraform providers, Gophercloud, OpenStack infrastructure and much more -- and that's not changing anytime soon (not as long as I continue to be around :))

**Comment by directionless** [comment]
> GitHub Actions self-hosted runners

I'm not sure how you'd use it, but GitHub strong _discourages_ using self hosted runners for community contributed PRs. https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

> We recommend that you only use self-hosted runners with private repositories. This is because forks of your repository can  potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

I spent awhile trying to see if I could find something workable security wise, and ultimately I gave up. The core issue, is that there is no supported way to ensure a runner only runs a single job.

**Comment by koobs** [comment]
You may already be aware, but noting here for reference, CirrusCI provides sponsored CI service to OpenSource projects. Also they support FreeBSD, and any OS project that provides Azure images is automatically supported and updated.

**Comment by jay** [comment]
Ask Travis for an exception. Travis uses curl. curl uses Travis. Makes sense to me.

**Comment by mback2k** [comment]
> Another option would be to use the curl fund to pay for travis. [pricing](https://travis-ci.com/account/plan). $129/month **"2 Concurrent plan"** is probably roughly the setup we had?

Looking at [this twitter conversation](https://twitter.com/mback2k/status/1240337055097462786) it seems like we had 20 parallel builds on travis-ci.org in 2020.

**Comment by bagder** [comment]
Thanks @mback2k ... that's even way more than the new 249USD/month tier...

**Comment by julianxhokaxhiu** [comment]
There are plenty of choices to CI curl:
- AppVeyor
- Azure Devops
- Github CI

Are just the first that comes to my mind. Personally I'm using Azure DevOps to CI all of my projects ( https://dev.azure.com/julianxhokaxhiu/Github/_build ). It's true I'm not baked by any commercial company but I think the only catch in the DevOps FOSS plan is to have your source public. And as this is your case too, all you'd have to do is migrate your scripts.

If you need help, feel free to ask!

Thanks for maintaining this project for so long, I feel your pains and I really admire you for not giving up so far. Admirable commitment, keep up the good work. Cheers :)

**Comment by bagder** [comment]
@julianxhokaxhiu: we already use those three CI services (and cirrus CI).

**Comment by mback2k** [comment]
@bagder you may wanna include the badges of the CI we already use in the first comment to avoid people suggesting them again and again: [![Travis-CI Build Status](https://travis-ci.org/curl/curl.svg?branch=master)](https://travis-ci.org/curl/curl) [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/l1vv31029huhf4g4?svg=true)](https://ci.appveyor.com/project/curlorg/curl) [![Azure DevOps Build Status](https://dev.azure.com/daniel0244/curl/_apis/build/status/curl.curl?branchName=master)](https://dev.azure.com/daniel0244/curl/_build/latest?definitionId=1&branchName=master) [![Cirrus Build Status](https://api.cirrus-ci.com/github/curl/curl.svg?branch=master)](https://cirrus-ci.com/github/curl/curl)

**Comment by bagder** [comment]
We've done the transition to the `.com` now and we still get builds done by Travis. It is not clear what plan this is based on....

**Comment by jimeh** [comment]
Any reason regular GitHub-hosted GitHub Actions hasn't really been suggested yet? It's completely [free on public repositories](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions):
> _GitHub Actions usage is free for both public repositories and self-hosted runners._

As far as I can tell, the repo being public or not is the only criteria used to determine if GitHub Actions is free.

As for concurrent jobs, I've never pushed it that far myself, but according to [documentation](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration), free accounts/organization can have up to 20 concurrent jobs on linux-based runners, and 5 on macOS-based runners.

Based on my own past experiences, converting a `.travis.yml` file to GitHub Actions workflow(s) is pretty simple and straight forward for the most part. I'd be happy to contribute some time to such a conversion.

**Comment by akx** [comment]
@jimeh When Travis started showing signs of becoming hostile for OSS projects, I actually wrote a converter... It doesn't handle all cases, of course, since Travis is a surprisingly complex beast, but it might help. https://akx.github.io/travis-to-github-actions/

**Comment by mback2k** [comment]
Again, we are already making heavy use of GitHub Actions. Please see comments above.

**Comment by jerdog** [comment]
@bagder I replied on Twitter (IAmJerdog) - feel free to hit me up and we can discuss how we can support your project.

**Comment by jay** [comment]
They said earlier today they'll assign us credits as per our usage so I guess we'll see how that goes.

**Comment by bagder** [comment]
Since it seems this is not an immediate problem for us, I'll close this issue again. We need to keep monitoring the situation and have alternatives in mind if we need to act later down the line.

**Comment by bagder** [comment]
Ok, it seems we ran out of credits within the first days of June so unless we get quite a lot more in an automatic fashion this won't hold.

**Comment by Tachi107** [comment]
It seems that [Drone CI](https://www.drone.io) hasn't been suggested yet. Would it be a viable solution for curl?

**Comment by bagder** [comment]
We're not picky, we can move to *any* service that interfaces with github decently. It's more about someone doing the actual heavy lifting of converting travis jobs to *other-service*-job.

**Comment by fkorotkov** [comment]
Since you are already using Cirrus CI and if Travis tasks can be containerized, you can take a look at [Cirrus CLI](https://github.com/cirruslabs/cirrus-cli) which can run Cirrus tasks on any host with Docker installed. It might help with the migration effort since one can quickly iterate locally on the configuration. Also in case of a future migration you won't be vendor locked with the CI config.

FYI curl project is using Cirrus CI only for FreeBSD and Windows so you still [can use up to 16 cores for Linux tasks](https://cirrus-ci.org/faq/#are-there-any-limits). We don't have any monthly limits like the one you have issues with.

**Comment by martinjeret** [comment]
We use cURL every day and would love to support you and pay something back. If you need macOS instances then we can help with Codemagic.io. We have CPU optimised Linux instances as well with 8 cores, but no Windows or FreeBSD ones. 

There's a github app available in the marketplace https://github.com/marketplace/codemagic-ci-cd 

you can send email to info@codemagic.io. I can check if we can perhaps help with migration if you're interested.

**Comment by mnaser** [comment]
Hi @bagder -- I'm going to work on a small fork here with curl running tests on our CI.

Ill probably have something by EOD :)

**Comment by mnaser** [comment]
Just an update: I'm still tracking on getting this done. Just got sucked into a few things :)

Should aim for today.

**Comment by mnaser** [comment]
I've set things up and they're running just fine, you can see an example of 2 of the jobs running like so:

https://github.com/vexxhost/curl/pull/1

@bagder: what do you think should be best for next steps?  Would you like me to port over all of the remainder of the Travis CI jobs?  Would you like to perhaps have a chat over what/how Zuul does before we dive in deeper?

The Zuul community hangs out at #zuul on OFTC but also happy to come by #curl on Libera to chat over some of this stuff.  The OSS community behind Zuul is quite excited to see Zuul testing cURL.

**Comment by bagder** [comment]
@mnaser: I wouldn't mind an initial pull-request that adds this first job already now (and removes the corresponding from travis). That way we get to see how this is done and others might be able to help out or just see the progress. Then I figure we want the rest of the jobs ported over too, yes. Some of them are a little work since they need more dependencies built etc.

How much CPU power/performance will get have at Zuul? Can it muster taking on all the 33 jobs from travis?

**Comment by mnaser** [comment]
> @mnaser: I wouldn't mind an initial pull-request that adds this first job already now (and removes the corresponding from travis). That way we get to see how this is done and others might be able to help out or just see the progress. Then I figure we want the rest of the jobs ported over too, yes. Some of them are a little work since they need more dependencies built etc.

Sure.  I'm happy to do that, I think we'll need the [VEXXHOST CI](https://github.com/apps/vexxhost-ci) GitHub application installed to the repository so that it can start running jobs against it.

> How much CPU power/performance will curl get at Zuul? Can it muster taking on all the 33 jobs from travis?
We've seen Zuul installations scale up to thousands of jobs per day easily.  Zuul starts up a single-use VM for every job which runs inside our public cloud.  Once the job is completed, the VM is destroyed.

This effectively means that we'll be launching 33 VMs for all 33 jobs which all around seem to be taking ~30 minutes each, resulting in some ~10 VM-hours for a change.   Based on reviewing the existing usage of cURL, I think there shouldn't be a problem for us to continue to provide the project with those resources..

Also, I think it will attract a lot of the Zuul developers that have expressed a lot of interest in contributing changes to help improve the CI using Zuul!

**Comment by mnaser** [comment]
FWIW, we've got a Zuul contributor (@albinvass) that's went ahead and ported even more jobs, so happy to push in that PR once we got the GitHub application added!

https://github.com/vexxhost/curl/pull/2

**Comment by bagder** [comment]
> Keep in mind that's still without doing any type of caching which could speed things up if that's wanted.

I've just never managed to get caching working on travis the way I wanted it to, but yes "speedy" is a very good property we want to aim for! =)

**Comment by jay** [comment]
Just an FYI travis support has not returned my latest followup so I don't know what's happening now. Maybe we use a lot more CPU than we used to.

**Comment by bagder** [comment]
We're now up on Zuul CI and Circle CI as replacements for Travis. There are some remaining things we still run on travis in other respos but once they've also transitioned we can remove travis completely from the project.

**Comment by jay** [comment]
travis added 2.4 million credits, not sure how they came to that calculation but they said reach out to support again when it runs low so it's like last time it's not going to be automated
