### ISSUE TITLE
SMTP fails with NTLM or GSSAPI without error in log

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [curl/curl#7156]
Reported in CURL 7.75.0, client tries SMTP and got:

> \* OK The Microsoft Exchange IMAP4 service is ready.
> A001 CAPABILITY
> \* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
> A001 OK CAPABILITY completed.
> Closing connection 0
 
So the server can do PLAIN, NTLM and GSSAPI. Curl is compiled for Windows to enable NTLM and GSSAPI as far as I know.
Result of Perform is 94: An authentication function returned an error.

The problem is:

CURL picks one auth mechanism and tries to authenticate, but it doesn't log which one is tried and it doesn't indicate the error in the log, e.g. "Authentication failed with GSSAPI.". So every time someone runs into this with our software, this causes a support request.

Since three ways exist and PLAIN seems to work for the client (I asked to use LoginOptions with AUTH=PLAIN), may CURL also try PLAIN if NTLM and GSSAPI failed? Like with SSH where it tries different ways.

Before I submit a patch, I'd love to hear some opinions from you guys.

**Comment by dfandrich** [comment]
If GSSAPI is advertised but it doesn't work, that sounds like the server is
broken. Should curl really try all the auth options in that case? There's a
danger that it will fall back to PLAIN in that case which on an unencrypted
connection will pass credentials in the clear, which may not be what the client
wants or expects.

**Comment by monnerat** [comment]
Some changes are pending for GSSAPI: https://github.com/curl/curl/pull/7008.
Maybe these will resolve your problem.

You can also try `AUTH=NTLM` to avoid using GSSAPI: the advantage over `PLAIN` is the password is not transmitted.

Curl does not fallback to another mechanism if the server reports a failing authentication. The main reason is: if the credentials are wrong, multiple unsuccessful authentication attempts may lock the account !

**Comment by bagder** [comment]
> CURL picks one auth mechanism and tries to authenticate, but it doesn't log which one is tried and it doesn't indicate the error in the log, e.g. "Authentication failed with GSSAPI.".

I don't think that's ever guaranteed or promised by curl though. Does it return an error? Then I think it sounds like curl is actually working as defined. Can it be improved to provide said information? sure!
