### ISSUE TITLE
Running curl through a proxy with low timeouts randomly creates a "glibc ... double free or corruption" crash

### ISSUE THREAD

**Issue by kylex** [curl/curl#7195]
This error is consistent (but random).
When using curl with a proxy, and timeouts are low and specified (mine were set to 4 seconds), and then the timeout occurs, it will randomly crash with the following error:
`*** glibc detected *** /opt/cpanel/ea-php71/root/usr/bin/php: double free or corruption (!prev): 0x0000000002c1de00 ***`

Full error attached.

[error_details_curl.txt](https://github.com/curl/curl/files/6600332/error_details_curl.txt)

**Comment by jay** [comment]
We need more information. Can you give us steps to reproduce using the latest libcurl without php?
