### ISSUE TITLE
--ciphers parameter will include other, unspecified ciphers in SSL handshake.

### ISSUE THREAD

**Issue by user1020** [curl/curl#7198]
### I did this
Ran the following command 
`curl -v --ciphers ECDHE-ECDSA-AES256-GCM-SHA384 https://some_server_host/`

### I expected the following
Expect that the SSL CLIENT_HELLO will only use the cipher specified in the command line. Server will either accept it (if it supports this cipher) or reject it. There is a chance to run some testing on this cipher.

But the CLIENT_HELLO contains a bunch of other ciphers, 
```
Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
```

### curl/libcurl version

[curl -V output]
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
### operating system
Ubuntu 20.04
Linux 1c6674402ba0 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
Can it be that you're using TLS 1.3? If so then you want to use `--tls13-ciphers` instead. Or in addition to perhaps if you want to cover older versions too.

**Comment by user1020** [comment]
Thanks @bagder for the question. I checked the network packets (using Wireshark) and it used TLS1.2.

Interestingly, I created a simple C program using libcurl and when running it, specified the desired cipher as the parameter.
Network packets showed that the CLIENT_HELLO has the other ciphers (not specified from command line) too.

```
#include <stdio.h>
#include <curl/curl.h>
int main(int argc, char *argv[]) {
	CURL *curl = curl_easy_init();
	int ret;
	if(curl) {
		curl_easy_setopt(curl, CURLOPT_URL, "https://some_server/test"
);
		/* switch off session-id use! */
		curl_easy_setopt(curl, CURLOPT_SSL_SESSIONID_CACHE, 1L);
		curl_easy_setopt(curl, CURLOPT_SSL_CIPHER_LIST, argv[1]);
		ret = curl_easy_perform(curl);
		curl_easy_cleanup(curl);
	}
}
```
Really hope we could have more precise control on the ciphers in the request for our testing. Thanks!

**Comment by jay** [comment]
Those are [Mandatory-to-Implement Cipher Suites](https://datatracker.ietf.org/doc/html/rfc8446#section-9.1) in TLS 1.3, so maybe OpenSSL has to send them if TLS 1.3 is a possibility.

**Comment by user1020** [comment]
Hi Jay, thanks for the link! It's very good to know that these ciphers are mandatory. I have two questions

- I am using TLS 1.2, not sure if it has same requirement as on 1.2
- In the case of TLS 1.3, if the client didn't include the mandatory ciphers in the CLIENT_HELLO cipher list, is it a violation

It looks like the requirement (thanks for sharing the link) can have 2 interpretations:

1.  Each compliant client should advertise these mandatory ciphers and each compliant server should accept any of these mandatory ciphers.
2. A compliant client doesn't have to advertise the list of mandatory ciphers, but have the implementation so that if a user *wants* to use any of the mandatory ciphers, it should work with a compliant server. 

Thanks again.

**Comment by user1020** [comment]
Thank you so much Jay, your recommendation of "--tls-max 1.2" works for me!

When I run command like
```
curl --tls-max 1.2 --ciphers ECDHE-ECDSA-AES256-GCM-SHA384 https://example.com
```
It sent a client_hello with two ciphers in the list, one is what's specified in the command line, the other one is TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff), which most likely won't be chosen by the server.

Thanks again, it helped A LOT!
