### ISSUE TITLE
POSIX violation in type naming

### ISSUE THREAD

**Issue by emilengler** [curl/curl#7210]
### [B.2.12 Data Types](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap02.html)
[...] To allow implementors to provide their own types, all conforming applications are required to avoid symbols ending in "_t", which permits the implementor to provide additional types. [...]

The code contains various typedefed types having this `_t` suffix.

The following extends checksrc.pl to detect these violations:
```diff
diff --git a/lib/checksrc.pl b/lib/checksrc.pl
index a35535c19..be74fd5b4 100755
--- a/lib/checksrc.pl
+++ b/lib/checksrc.pl
@@ -82,6 +82,7 @@ my %warnings = (
     'SNPRINTF'         => 'use of snprintf',
     'ONELINECONDITION' => 'conditional block on the same line as the if()',
     'TYPEDEFSTRUCT'    => 'typedefed struct',
+    'TYPEDEF_T'        => 'typedef ending in _t',
     'DOBRACE'          => 'A single space between do and open brace',
     'BRACEWHILE'       => 'A single space between open brace and while',
     'EXCLAMATIONSPACE' => 'Whitespace after exclamation mark in expression',
@@ -749,6 +750,13 @@ sub scanfile {
                       "typedef'ed struct");
         }
 
+        # typedef ending in _t
+        if($nostr =~ /} .+_t;$/) {
+            checkwarn("TYPEDEF_T",
+                      $line, length($1)+1, $file, $ol,
+                      "typedef ending in _t");
+        }
+
         if($nostr =~ /(.*)! +(\w|\()/) {
             checkwarn("EXCLAMATIONSPACE",
                       $line, length($1)+1, $file, $ol,
```

**Comment by bagder** [comment]
1. Some of those occurrences in the code are used on purpose for public symbols and cannot be changed now. This check also doesn't catch typedefs that aren't enums, as done for `curl_off_t` and `curl_socket_t` etc.
2. It complains on `Use of uninitialized value $1`

**Comment by emilengler** [comment]
> Some of those occurrences in the code are used on purpose for public symbols and cannot be changed now.

True forgot it apparently, no hard feelings then
