### ISSUE TITLE
configure: inconsistent configure option "get-easy-option"

### ISSUE THREAD

**Issue by Bastian-Krause** [curl/curl#7211]
Hi,

the help text and the configure option `get-easy-option`/`get-easy-options` are inconsistent:
https://github.com/curl/curl/blob/a3a298da5ee5bdc2199a819aa2a20df9b4d6268e/configure.ac#L3803-L3809

I am not sure which variant is correct here, so I'm opening this issue instead of a PR.

**Comment by bagder** [comment]
Since this sets the define `CURL_DISABLE_GETOPTIONS` with a plural s, maybe go with that for all of them?
