### ISSUE TITLE
nothing happens when uploading a file with -F when filename has a comma in it

### ISSUE THREAD

**Issue by jrwren** [curl/curl#7214]
### I did this

curl -v -s -XPOST -F"sample=@RE,ReXReXFurnitures.xlsx" -Fapi_key=MYKEY https://myserver

What I got was nothing. No output, and no http request. The command simply returned with an exit value of 26. It appears to be the comma in the filename is a problem. If I rename the filename without the comma... Only as I type this am I realizing the comma might mean something to the -F parameter... *goes to read man page*... but no, I don't see it documented.

### I expected the following

Verbose output and a POST request with the multipart file upload.

### curl/libcurl version

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux delays 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
First a quote from [the man page](https://curl.se/docs/manpage.html#-F):

> If filename/path contains ',' or ';', it must be quoted by double-quotes

To upload the file name `READ,ME`:

    curl -F 'file=@"READ,ME"' $URL

**Comment by jrwren** [comment]
GAH! I see it now. I feel like a fool. TY for pointing that out to me. My apologies for opening this issue unnecessarily.
