### ISSUE TITLE
Crash on macOS: pointer being freed was not allocated

### ISSUE THREAD

**Issue by zhihaoy** [curl/curl#7226]
### I did this

Send HTTPS requests periodically using `curl_multi_perform`.

### curl/libcurl version

curl 7.76.0-DEV (x86_64-apple-darwin19.6.0) libcurl/7.76.0-DEV OpenSSL/1.1.1k zlib/1.2.11 c-ares/1.14.0
Release-Date: [unreleased]
Protocols: http https mqtt smb smbs
Features: alt-svc AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets

### operating system

Darwin toors-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

### Crash report

```
Application Specific Information:
abort() called
[_appname_] malloc: *** error for object 0x800007fdd5cfc98: pointer being freed was not allocated

Thread 10 Crashed:
0   libsystem_kernel.dylib        __pthread_kill + 10
1   libsystem_pthread.dylib       pthread_kill + 430
2   libsystem_c.dylib             abort + 120
3   libsystem_malloc.dylib        malloc_vreport + 548
4   libsystem_malloc.dylib        malloc_report + 151
5   mylib.so                      asn1_string_embed_free (in mylib.so) + 45
6   mylib.so                      asn1_primitive_free (in mylib.so) + 158
7   mylib.so                      asn1_template_free (in mylib.so) + 156
8   mylib.so                      asn1_item_embed_free (in mylib.so) + 268
9   mylib.so                      asn1_template_free (in mylib.so) + 156
10  mylib.so                      asn1_item_embed_free (in mylib.so) + 268
11  mylib.so                      asn1_template_free (in mylib.so) + 156
12  mylib.so                      asn1_item_embed_free (in mylib.so) + 268
13  mylib.so                      ASN1_item_free (in mylib.so) + 23
14  mylib.so                      X509_OBJECT_free (in mylib.so) + 35
15  mylib.so                      OPENSSL_sk_pop_free (in mylib.so) + 59
16  mylib.so                      X509_STORE_free (in mylib.so) + 216
17  mylib.so                      SSL_CTX_free (in mylib.so) + 185
18  mylib.so                      ossl_close (in mylib.so) + 63
19  mylib.so                      Curl_ossl_close (in mylib.so) + 30
20  mylib.so                      Curl_ssl_close (in mylib.so) + 22
21  mylib.so                      Curl_disconnect (in mylib.so) + 156
22  mylib.so                      create_conn (in mylib.so) + 7713
23  mylib.so                      Curl_connect (in mylib.so) + 75
24  mylib.so                      multi_runsingle (in mylib.so) + 652
25  mylib.so                      curl_multi_perform (in mylib.so) + 133
26  mylib.so                      [...]
```

Initially I thought this might be a bug in OpenSSL. But later I realized that if this is OpenSSL code trying to "free" a piece of embedded string, the issue should be reproducible. Every run of the program I'm accessing the same set of websites, so presumably loading the same set of certificates. But this issue happens very rarely, so now I'm tend to believe that it's a double-free caused by some form of racy code in libcurl.

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by zhihaoy** [comment]
We have difficulty reproducing it as well. All URLs are API endpoints that need credentials. And as you can tell, it went to `Curl_disconnect` within `create_conn`'s frame, so it's probably some unusual network condition :/

**Comment by bagder** [comment]
Both calls to `Curl_disconnect` from within that function happens when it kills off an older connection from the connection cache. But that's not enough for me to go on.

**Comment by clive40** [comment]
Hi, I am recieving these over the past 2 weeks trying to uninstall ethereum development, enviroment and general clean up of my mac i am using clean my mac to assist, though i am still getting these kernel crashes and panic reports,and the more i dig to remove old stuff the more they happen
![Screenshot 2021-06-16 at 13 55 47](https://user-images.githubusercontent.com/84251106/122224373-f3cd9c80-ceab-11eb-9cfb-4be473a784db.jpg)

**Comment by clive40** [comment]
I have tried, grep | and killed any connection or API still running though there is still one that will not disconnect , i have flushed my DNS and kill any active PIDS though it is still there ,I reckon it is something to do with mysql an offgrid connection they install when you use there services or could be a docker issue, It is a connection inherited from a blockchain build thats were i have narrowed it down to.

**Comment by bagder** [comment]
@clive40 I don't see how your problem is related to this issue and there's not even a single mention of curl in there. Also: a kernel crash in macOS means a bug in their kernel. Talk to Apple.

**Comment by zhihaoy** [comment]
Several teams are working on adding ASan to our libcurl+openssl+c-ares build.
New version (7.77) is also in the pipeline.

**Comment by bagder** [comment]
Since we can't act on this, and nobody can reproduce I'm closing it. If you can reproduce a problem with the latest curl, please create a new issue and tell us how!
