### ISSUE TITLE
libcurl 7.77.0 with libuv crashes on ARM when doing two parallel transfers

### ISSUE THREAD

**Issue by X-Crack** [curl/curl#7247]
The compiler I use: 10.2-2020.11-x86_64-arm-none-linux-gnueabihf

// CURL 7.77.0
./configure CC=/usr/bin/arm-none-linux-gnueabihf-gcc CXX=/usr/bin/arm-none-linux-gnueabihf-g++ AR=/usr/bin/arm-none-linux-gnueabihf-ar RANLIB=/usr/bin/arm-none-linux-gnueabihf-gcc-ranlib CPPFLAGS="-I/home/dev/Projects/Shattrath/arm/include" LDFLAGS="-L/home/dev/Projects/Shattrath/arm/lib" --host=arm-linux --with-ssl --disable-shared --enable-static --disable-dict --disable-ftp --disable-imap --disable-ldap --disable-ldaps --disable-pop3 --disable-proxy --disable-rtsp --disable-smtp --disable-telnet --disable-tftp --disable-zlib --without-ca-bundle --without-gnutls --without-libidn --without-librtmp --without-libssh2 --without-nss --without-zlib --prefix=/home/dev/Projects/Shattrath/arm

make -j8 && make install

// openssl openssl1.1.1k
./config -static -static-libgcc -fPIC -Wl,-Bstatic no-asm no-shared no-async --prefix=/home/dev/Projects/Shattrath/arm --cross-compile-prefix=arm-none-linux-gnueabihf-

make CC=arm-none-linux-gnueabihf-gcc -j8 && make install

### other instructions: I follow the official combination of LIBUV and LIBCURL to implement asynchronous IO processing to download files, and downloading a file will not cause problems.

If you download two files at the same time, the program will crash!

```
int main(int argc, char **argv)
{
    loop = uv_default_loop();

    if(curl_global_init(CURL_GLOBAL_ALL)) {
        fprintf(stderr, "Could not init curl\n");
        return 1;
    }

    uv_timer_init(loop, &timeout);

    curl_handle = curl_multi_init();
    curl_multi_setopt(curl_handle, CURLMOPT_SOCKETFUNCTION, handle_socket);
    curl_multi_setopt(curl_handle, CURLMOPT_TIMERFUNCTION, start_timeout);

    add_download("http://mirrors.163.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso", 1);
    add_download("http://mirrors.163.com/centos/7/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso", 2);

    uv_run(loop, UV_RUN_DEFAULT);
    curl_multi_cleanup(curl_handle);

    return 0;
}

**Added download http://mirrors.163.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso -> 1.download
Added download http://mirrors.163.com/centos/7/isos/x86_64/CentOS-7-x86_64-NetInstall-2009.iso -> 2.download
Segmentation fault**

```

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by X-Crack** [comment]
curl 7.77.0 (arm-unknown-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k **c-ares/1.17.1**
Release-Date: 2021-05-26
Protocols: file gopher gophers http https mqtt smb smbs 
Features: alt-svc AsynchDNS HSTS IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets
root@am335x:~/io_service# uname -a
Linux am335x 3.2.0 #595 Wed Jan 31 00:13:29 PST 2018 armv7l GNU/Linux
root@am335x:~/io_service# 


--------------------------------------------------------------------------------------------------------------------------------------
There will be no crashes after I use c-ares.
However, https can't be used. There will be many warnings when I compile, because I compile statically, and my program runs on an arm development board, and the hard disk is only 256M, unable to install too many dynamic runtime libraries.

Helpless, can only use static compilation mode.


**### The following is my clion compilation log**
--------------------------------------------------------------------------------------------------------------------------------------

===================[ Build | all | Default ]===================================
/opt/clion/bin/cmake/linux/bin/cmake --build /home/dev/Projects/Shattrath/bin/download_example --target all -- -j 3
[ 50%] Building CXX object CMakeFiles/download_example.dir/source/test.cpp.o
[100%] Linking CXX executable download_example
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcrypto.a(dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x8): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcurl.a(libcurl_la-netrc.o): in function `Curl_parsenetrc':
netrc.c:(.text+0x37e): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
b_addr.c:(.text+0x678): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
b_sock.c:(.text+0x2c): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcares.a(libcares_la-ares_getaddrinfo.o): in function `ares_getaddrinfo':
ares_getaddrinfo.c:(.text+0x442): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/local/bin/gcc-arm-x86/bin/../lib/gcc/arm-none-linux-gnueabihf/10.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: /home/dev/Projects/Shattrath/download_example/../arm/lib/libcares.a(libcares_la-ares_getnameinfo.o): in function `lookup_service.part.0.constprop.0':
ares_getnameinfo.c:(.text+0x172): warning: Using 'getservbyport_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[100%] Built target download_example

Build finished

**Comment by bagder** [comment]
I'm sorry, but I think you have problems that is due to your build and your environment and not because of a bug in curl.

Without a complete stand-alone program that causes the problem that we can reproduce this with, I don't see what else we can do than perhaps provide some debugging tips.

For example: build with debug symbols present and get a stack trace from the crash?

**Comment by X-Crack** [comment]
@bagder 

[download_example.zip](https://github.com/curl/curl/files/6643253/download_example.zip)

This is a complete static program. argv[0] = url address argc = port supports a maximum of 1 URL. Currently, the program will not crash, but https cannot be used.

**Comment by X-Crack** [comment]
@bagder 


![54555555555555555555555](https://user-images.githubusercontent.com/45416520/121815405-e72d2680-cca8-11eb-9099-3c324aede8a2.png)

Hello, this is my latest compiled curl. It did not collapse phenomenon, but still can not support HTTPS / SSL in ARM V7 systems.

If you help me test the problem, I would really appreciate it. Because my side of the system is really too old.

This can also fully reflect whether it is a code bug or an original problem of the system.

[curl.zip](https://github.com/curl/curl/files/6644297/curl.zip)

**Please, put the "dynamic" folder in the root directory of the ARM system, so that the program can find the dynamic link library**

### My compilation parameters
// CURL 7.77.0
---
./configure CC=/usr/bin/arm-none-linux-gnueabihf-gcc CXX=/usr/bin/arm-none-linux-gnueabihf-g++ AR=/usr/bin/arm-none-linux-gnueabihf-ar RANLIB=/usr/bin/arm-none-linux-gnueabihf-gcc-ranlib \
--host=arm-linux --disable-shared --enable-static  --enable-libssh2 --enable-zlib --enable-ares --enable-threaded-resolver --with-ssl --with-ca-path=/etc/ssl/certs --with-libssh2=/home/dev/Projects/Shattrath/arm/include \
--enable-dict --enable-ftp --enable-imap --disable-ldap --disable-ldaps --enable-pop3 --enable-proxy --disable-rtsp --enable-smtp --enable-telnet --enable-tftp --with-zlib=/home/dev/Projects/Shattrath/arm/include --enable-ca-bundle --enable-gnutls --without-libidn --enable-librtmp --enable-nss --prefix=/home/dev/Projects/Shattrath/arm \
LDFLAGS="-L/home/dev/Projects/Shattrath/arm/lib/ -Wl,-rpath=/dynamic/ -Wl,--dynamic-linker=ld-linux-armhf.so.3"  \
CPPFLAGS="-I/home/dev/Projects/Shattrath/arm/include/ -L/home/dev/Projects/Shattrath/arm/lib/" \
LIBS="-lcares -lz -lssh2 -lssl -lcrypto -lpthread -ldl -lrt" 
---

// openssl1.1.1k
---
./config -Wl,-rpath=/dynamic/ -Wl,--dynamic-linker=ld-linux-armhf.so.3 zlib no-asm no-async \
--with-zlib-include=/home/dev/Projects/Shattrath/arm/include --with-zlib-lib=/home/dev/Projects/Shattrath/arm/lib \
--prefix=/home/dev/Projects/Shattrath/arm \
--openssldir=/home/dev/Projects/Shattrath/arm/openssl --cross-compile-prefix=arm-none-linux-gnueabihf-
---
// cres
---
./configure CC=/usr/bin/arm-none-linux-gnueabihf-gcc CXX=/usr/bin/arm-none-linux-gnueabihf-g++ AR=/usr/bin/arm-none-linux-gnueabihf-ar RANLIB=/usr/bin/arm-none-linux-gnueabihf-gcc-ranlib --host=arm-linux LDFLAGS="-Wl,-rpath=/dynamic/ -Wl,--dynamic-linker=ld-linux-armhf.so.3" --prefix=/home/dev/Projects/Shattrath/arm
---

// zlib
---
export CC=arm-none-linux-gnueabihf-gcc
./configure -static --prefix=/home/dev/Projects/Shattrath/arm
---

**Comment by bagder** [comment]
> This is a complete static program

We need the complete **source code** to said program.

**Comment by X-Crack** [comment]
> > This is a complete static program
> 
> We need the complete **source code** to said program.

Hello, the complete **source code** is here.

https://github.com/X-Crack/libuv-evpp/tree/master/source

**Comment by bagder** [comment]
> the complete source code is here

Sorry, I meant to a sample source code *as small as possible* that reproduces the problem. I can't debug your application for you.

> In this part, I did not use my own program. Using your CURL

What do you mean? What "part" ? This issue is about doing transfers in parallel. Let's stick to one problem in this one issue.

**Comment by X-Crack** [comment]
> > the complete source code is here
> 
> Sorry, I meant to a sample source code _as small as possible_ that reproduces the problem. I can't debug your application for you. (Unless of course you purchase support)
> 
> > In this part, I did not use my own program. Using your CURL
> 
> What do you mean? What "part" ? This issue is about doing transfers in parallel. Let's stick to one problem in this one issue.


**_Sorry, after two days of argumentation, the reason is OPENSSL. I changed to wolfssl and everything is fine. Excuse me, if anyone encounters a problem like mine. Please ask him to review our conversation, thank you very much._**

**Comment by X-Crack** [comment]
After a long version test. Finally, "**openssl-OpenSSL_1_1_1a**" is suitable for **arm335x armv7l**
In addition, an error was reported: curl: (35) error:1007C06B:elliptic curve routines:EC_POINT_set_affine_coordinates_GFp:point is not on curve
Solution: need to add **setarch linux32 or setarch i386** during openssl compilation
------
For example: setarch linux32 ./config -Wl,-rpath=/dynamic/ -Wl,--dynamic-linker=/dynamic/ld-linux-armhf.so.3 no-asm -march=armv7-a -D__ARM_MAX_ARCH__=7 zlib \
--with-zlib-include=/home/dev/Projects/Shattrath/arm/include --with-zlib-lib=/home/dev/Projects/Shattrath/arm/lib \
--prefix=/home/dev/Projects/Shattrath/arm \
--openssldir=/home/dev/Projects/Shattrath/arm/openssl --cross-compile-prefix=arm-none-linux-gnueabihf-
