### ISSUE TITLE
Need to clear the send data which may include secret information

### ISSUE THREAD

**Issue by peterlaser** [curl/curl#725]
### I did this
transfer.c in libcurl
k->uploadbuf in readwrite_upload points to a 16K buffer which cached the data will be sent. If curl has uploaded all the buffer, then we expect the cached data which may include the secret info could be cleared. Can not find any curl interface to clear the buffer. 

### I expected the following
Changes for two scenarios:
1.Clear it if we've uploaded that buffer. 
2. Clear it if send data fail
So please help to review if the patch is safe and whether can be included in your next release.  

[transferc.patch.txt](https://github.com/curl/curl/files/185491/transferc.patch.txt)

### libcurl version
7.46
### operating system 
all

**Comment by bagder** [comment]
Can you elaborate on exactly what this protects you against? Your application already fed that data into libcurl so if the application wanted the data it could already have read it. What does zeroing out this buffer add?

Also, strlen() on the data to find the size is not going to work since we can upload binary data and then a strlen() on it can return too short or too long.

**Comment by peterlaser** [comment]
1) Assume that one app may send user’s account sensitive info to server side. After libCurl send out the data, user may collect the process dump. Then you will see the secret info still in the dump. So we hope that, after libcurl send the data out, zero the send data buffer(k->uploadbuf) immediately.

2) In the callback of function Curl_fillreadbuffer, after we copied the send data to libcurl layer. We will clear our cache immediately, but libcurl doesn’t do this. So we can still see the secret info from the process dump.

3) k->uploadbuf is a 16K buffer. If strlen() is not a good solution, how about use BUFSIZE directly, like memset(k->uploadbuf, 0, BUFSIZE);. I just want to make sure zero buffer here is OK and libcurl does not need the old buffer again, Thanks.

**Comment by dfandrich** [comment]
The transmit buffer is not the only place where secrets are held. User passwords, proxy passwords, certificate passwords, the contents of the netrc file, etc. can all potentially be stored in RAM and therefore end up in a core dump. Plus, a core dump could occur before the memset, making this patch useless. If this is the threat model you're protecting against, you have a lot more work cut out for you. Better would be to simply disable core dumps on your system.

**Comment by jay** [comment]
What you're asking is just not a guarantee we can make. You can get some degree by using [`curl_global_init_mem`](https://curl.haxx.se/libcurl/c/curl_global_init_mem.html) to override the memory callbacks. In this way you can create a curl easy handle, perform, and cleanup. When cleanup is called it will free the memory and will call your curl_free_callback. In that callback you zero memory or whatever your OS offers before you actually free the memory. *Be warned some compilers may optimize out zeroing memory. An OS may have a specific call for it to prevent that.* However if your "secret information" has been passed on to the SSL library (or any other library libcurl is using) that library may have made its own copies of the information and it may still be in memory. And surely you got it into memory somehow, so there might be copies from however you did that (whether you explicitly did it or not).

**Comment by patrikhson** [comment]
Hi,

Here is a nice selection of great places to visit, just take a look at my list <http://tawiproxu.milkneverhaditsogood.com/xybehtk>

Yours sincerely, paf@frobbit.se
