### ISSUE TITLE
WinBuild : Documentation does not include VC 16

### ISSUE THREAD

**Issue by HughMacdonald** [curl/curl#7253]
This is a tiny thing, and apologies if I've misunderstood anything.

I'm running Visual Studio 16.10.0 here, which I'm guessing is the same version as VC. In the winbuild/README.md, the options for the -VC flag include up to 15, but should probably include 16 too. Running it with -VC=16 worked fine for me.

**Comment by bagder** [comment]
It probably should, yes. Or be rephrased to work generically since the only check that's currently done with that variable if it is version 6, all others are treated the same...

**Comment by HughMacdonald** [comment]
Cool stuff - thanks! It only threw me for a second, and it seemed to build just fine.
