### ISSUE TITLE
--fail without --location should treat 3xx as a failure

### ISSUE THREAD

**Issue by jay** [curl/curl#727]
### I did this
~~~
curl -v --fail -O https://github.com/curl/curl/archive/curl-7_48_0.tar.gz
~~~
The server returns `HTTP/1.1 302` and a location, in addition to some content stating the location has moved. Curl writes that information to curl-7_48_0.tar.gz.
~~~
cat curl-7_48_0.tar.gz
<html><body>You are being <a href="https://codeload.github.com/curl/curl/tar.gz/curl-7_48_0">redirected</a>.</body></html>
~~~
### I expected the following
That `--fail` without `--location` would treat 3xx as a failure.
### curl/libcurl version
~~~
curl 7.48.0-DEV (i686-w64-mingw32) libcurl/7.48.0-DEV mbedTLS/2.2.1 zlib/1.2.8 libidn/1.32 libssh2/1.7.0 nghttp2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz HTTP2
~~~
### operating system
Windows 7 x64 Enterprise

**Comment by jay** [comment]
In [CURLOPT_FAILONERROR](https://curl.haxx.se/libcurl/c/CURLOPT_FAILONERROR.html) it is documented as fail if >= 400, so we'd be breaking with the doc.

**Comment by bagder** [comment]
Right, `--fail` would then need to check for 3xx on it own or we need to change behavior slightly in the library. I've never really liked `CURLOPT_FAILONERROR` in the library anyway...

**Comment by jay** [comment]
I wonder if there's any reason someone would want to capture the output of a 3xx with fail.

**Comment by bagder** [comment]
`--fail` is already cutting off the response body for 4xx so it would rather be inconsistent to do it for 3xx... 

That said, we *have* gotten requests from people that want to store the response _and_ have `--fail` return error. But introducing that would change behavior quite drastically I'd say.

**Comment by jay** [comment]
Ok. To be clear I'm not suggesting `--fail` allow output on fail, quite the opposite. I'm looking for any reason someone who currently uses `--fail` w/o `--location` or `CURLOPT_FAILONERROR` w/o `CURLOPT_FOLLOWLOCATION` would rely on 3xx not failing and expect the captured output.

Also I don't understand what you mean by it is inconsistent to discard output for 3xx the same as 4xx if we're treating them both as failures.

**Comment by bagder** [comment]
> I'm looking for any reason someone who currently uses --fail w/o --location would rely on 3xx not failing and expect the captured output.

I doubt we'll find any by asking, that's the sort of usage that'll pop up with someone screaming 3 years down the road.

**Comment by bagder** [comment]
> Also I don't understand what you mean by it is inconsistent to discard output for 3xx the same as 4xx if we're treating them both as failures.

I mean that we would need to act the same for both series.
