### ISSUE TITLE
Extern symbol allocators visibility issue.

### ISSUE THREAD

**Issue by moe123** [curl/curl#7279]
Hello,

building a shared library, we are using a reduced part of libcurl APIs as a private backend (so we build all curl objects with visibility hidden, using the exact same settings than provided makefiles, except that we are more selective), however, with have issues with those symbols being exposed: (those are marked as extern, so global symbols)

```
D Curl_ccalloc
D Curl_cfree
D Curl_cmalloc
D Curl_crealloc
D Curl_cstrdup
```

is there a way to disable those custom allocators? we would like very much not to have to tell  our users you can use whatever you want except libcurl and our shared lib: that's a feature.

Thank you.

**Comment by bagder** [comment]
These symbols are not exposed by a "normal" libcurl build, only `curl_` symbols are. We have *many* private library-wide symbols prefixed with `Curl_` that are not meant for outsiders to use.

**Comment by dfandrich** [comment]
Is the problem only that those symbols are exported? You should be able to get
away with prefixing those variable definitions with:

  __attribute__ ((__visibility__ ("hidden")))

if you're using gcc (or probably also clang) or the equivalent for whatever other
compiler you're using.

**Comment by moe123** [comment]
nope we build visibility hidden, so T Curl* are gone except those as they are marked extern, we'd break the inner mechanism of setting allocators at runtime, this is a feature a libcurl which should be made optional.

**Comment by bagder** [comment]
> except those as they are marked extern

How are these more "extern" than the other Curl_ globals?

**Comment by moe123** [comment]
Because I guess they are function pointers, so they remained exposed. Just built the entire lib with visibility hidden:

```
D Curl_ccalloc
D Curl_cfree
D Curl_cmalloc
D Curl_crealloc
D Curl_cstrdup
```

**Comment by dfandrich** [comment]
I just built the lib from git HEAD on x86_64 using gcc 10.3.0 with
--enable-symbol-hiding and got the following:

$ nm  lib/.libs/libcurl.so | grep -E 'Curl_c(cal|fre|mal|real|str)'
00000000000766a8 d Curl_ccalloc
00000000000766c0 d Curl_cfree
00000000000766c8 d Curl_cmalloc
00000000000766b8 d Curl_crealloc
00000000000766b0 d Curl_cstrdup

i.e. local symbols.  What platform and compiler are you using?

**Comment by moe123** [comment]
for now focusing on clang and android ABI current,  but not specific to it, I noticed the same on an ubuntu box,  btw `nm -D` that's what matters.

**Comment by dfandrich** [comment]
Those symbols don't show up for me at all with -D, using gcc or clang.

**Comment by moe123** [comment]
And so? doesn't help anything, this is working on your computer, as per see this is an ABI "issue" and that's very blocking having those showing up as dynamic symbols; it could be handled differently (programmatically speaking) would not cause that kind of issue.

**Comment by dfandrich** [comment]
You've already said that you're using a customized version of libcurl and I've
shown how a standard libcurl compile doesn't produce that issue. We don't have
access to your build environment here, so without more information, Works
For Me is my answer. What is different in your environment that could cause
this?

**Comment by moe123** [comment]
- I stated we used a small set; reduced; where is the customization in that?
- I stated to have tested with the whole library and having the exact same result.

so it is resulting in those conclusions:
```
 it impacts all arm-v7 ABI targets; x86, x86-64, aarch64 are safe. So arm-v7 passing extern func-pointers bad juju, can't make a safe shared object with libcurl.
```

**Comment by danielgustafsson** [comment]
Can you post a full repro script such that someone with an armv7 environment can reproduce the issue and potentially assist?

**Comment by MonkeybreadSoftware** [comment]
Why don't you guys use a custom list for exported functions?
e.g. for our build system we use:

 -Xlinker --retain-symbols-file -Xlinker ExportsLinux.txt

to point the linker in the clang/gcc calls to where the file is, which names exactly which symbols to export.

**Comment by bagder** [comment]
> Why don't you guys use a custom list for exported functions?

How is that better/easier than the pattern-based method we use now?
