### ISSUE TITLE
Backward compatibility broken after #5050

### ISSUE THREAD

**Issue by valeriodigregorio** [curl/curl#7289]
I can see that after #5050 (see https://github.com/curl/curl/commit/e54b1885d19dee5ed04761295020a0a84b8296ca) backward compatibility with `curl_easy_pause()` is broken. I used to use 7.66.0 and now 7.72.0. Reason is the function now returns `CURLE_BAD_FUNCTION_ARGUMENT` because `conn == NULL`. In previous version (same case) the function was returning `CURLE_OK`.  I think pausing an unexisting connection should just result in `curl_easy_pause()` to exit with `CURLE_OK` like it used to do in the past.

### I did this
I called `curl_easy_pause()` with `data->conn == NULL`.

### I expected the following
Return `CURLE_OK`.

### curl/libcurl version
7.72.0

### operating system
RHEL 8.2

**Comment by jzakrzewski** [comment]
I think the behaviour now is correct (you shouldn't pass invalid handle to the API functions).
But regardless, this change is in for over a year (8 versions if I count correctly) and this alone tells me we shouldn't revert it now.

**Comment by bagder** [comment]
> I think pausing an unexisting connection should just result in curl_easy_pause() to exit with CURLE_OK like it used to do in the past.

But why? I think you need to provide a reason for why this should be considered legitimate and fine way to use the API. The fact that it used to do it is not a valid reason if the previous behavior was considered a bug!

**Comment by valeriodigregorio** [comment]
I would need you to confirm whether `CURLE_BAD_FUNCTION_ARGUMENT` is returned if and only if `conn == NULL`. If that's the case I'll fix my code and I'll accept `CURLE_OK` and `CURLE_BAD_FUNCTION_ARGUMENT` as successes. If there's any other case `curl_easy_pause()` can return `CURLE_BAD_FUNCTION_ARGUMENT`, then I (and all the other users) of the library won't be able to understand if this is really an error case or just the broken backward compatibility.

**Comment by bagder** [comment]
That it is certainly not the case. We will never promise that a specific return code will only be returned for a single error case. That's not how we use error codes.

It would help if you could explain why pausing a transfer without a connection should be considered okay.

**Comment by valeriodigregorio** [comment]
Let me clarify, it's not like I want the pausing without connection to be ok or not. I just want to get my code working again and overcome the broken backward compatibility introduced by the above-mentioned commit.

My code is like this:
```c
rc = curl_easy_pause(hndl, mask);
if (rc != CURLE_OK) {
    return -1;
}
```
Now the team maintaining our internal SDK is going to upgrade libcurl. How do I fix this? My quick&dirty fix was:
```c
rc = curl_easy_pause(hndl, mask);
if (rc != CURLE_OK && rc != CURLE_BAD_FUNCTION_ARGUMENT) {
    return -1;
}
```
But you pointed out I cannot assume `CURLE_BAD_FUNCTION_ARGUMENT` to be returned if and only if `conn == NULL`. So how do I sort this out? I would then need something like `curl_easy_connection_exists`:
```c
if (curl_easy_connection_exists(hndl)) {
    rc = curl_easy_pause(hndl, mask);
    if (rc != CURLE_OK) {
        return -1;
    }
}
```
Can you propose a solution?

I don't know if you see my point, backward compatibility has been broken, I'm fine with that. Have you put in place a way to handle that breakage form application code?

**Comment by bagder** [comment]
Why is pausing a transfer without a connection okay? You're clearly using a handle that isn't transfering anything and you ask libcurl to pause it. It can't pause it because there's no transfer going on. The fix: don't pause handles without transfers.

**Comment by valeriodigregorio** [comment]
And how can I possibly know I don't have a transfer? I already called the curl_multi_add_handle, isn't that enough?
