### ISSUE TITLE
MacOS (Arm64) crash on curl += 7.76

### ISSUE THREAD

**Issue by richardmarion** [curl/curl#7308]
With the addition of the statement of "full-size = (size_t) data->set.max_send_speed" on line 1179-1182 in http.c in commit https://github.com/curl/curl/commit/24e469f6d61635f85bd4a0845c07aef0c6be661b#diff-14c8235d370910f1781de1a00ed1957ec948e84e88fdc52db87bd4eb7c7167ff made for 7.76, MacOS crashes in memcpy on line 1205.   

I did this.    Built version 7.75 and version 7.76 from sources for arm64 target.     Once I took out line 1179-1182 from http.c, I was able to run overnight without memory violation crashes.

 I expected the following.     I expected both versions to work

curl/libcurl version - 7.75 & 7.76

[curl -V output]

MacOS 11.4

**Comment by bagder** [comment]
But why does it crash there? Isn't `fullsize` smaller than `http->postsize` in that case so that it copies *less* data than it would otherwise?

**Comment by richardmarion** [comment]
Hi Daniel,

Not sure why assigning fullsize crashes the app.  Let me instrument the code and log fullsize.    I can also send .crashes if it helps.

Rick



From: Daniel Stenberg ***@***.***>
Reply-To: curl/curl ***@***.***>
Date: Monday, June 28, 2021 at 9:14 AM
To: curl/curl ***@***.***>
Cc: Richard Marion ***@***.***>, Author ***@***.***>
Subject: Re: [curl/curl] MacOS (Arm64) crash on curl += 7.76 (#7308)


But why does it crash there? Isn't fullsize smaller than http->postsize in that case so that it copies less data than it would otherwise?

**Comment by bagder** [comment]
> I can also send .crashes if it helps

Nah, I wouldn't know what to do with it.

**Comment by jay** [comment]
https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/lib/http.c#L1163-L1170
https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/lib/http.c#L1179-L1182
https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/lib/http.c#L1205

fullsize should not be larger than the passed in fullsize which is the size of buffer. My guess is the max speed that is assigned to fullsize is larger than the passed in fullsize.

~~~diff
diff --git a/lib/http.c b/lib/http.c
index 6d5d8fb..7b44198 100644
--- a/lib/http.c
+++ b/lib/http.c
@@ -1177,6 +1177,7 @@ static size_t readmoredata(char *buffer,
   data->req.forbidchunk = (http->sending == HTTPSEND_REQUEST)?TRUE:FALSE;
 
   if(data->set.max_send_speed &&
+     (data->set.max_send_speed < fullsize) &&
      (data->set.max_send_speed < http->postsize))
     /* speed limit */
     fullsize = (size_t)data->set.max_send_speed;
~~~

**Comment by bagder** [comment]
@jay looks correct. Make a PR?

**Comment by bagder** [comment]
I decided it would be quicker if I just made a PR out of @jay's proposal. See #7315

**Comment by jay** [comment]
I was working on the commit message at the same time you opened so I force pushed to your branch
