### ISSUE TITLE
ca cert file error after setting CURLOPT_SSL_VERIFYPEER = 0L

### ISSUE THREAD

**Issue by shmn18** [curl/curl#7312]
~~~c++
static const char *postthis = "moo mooo moo moo"; 
std::string chunk;
CURLcode res;

   curl = curl_easy_init();

	if (curl)

	{

      curl_easy_setopt(curl, CURLOPT_URL, "https://example.com");



      struct curl_slist* headers = NULL;

		headers = curl_slist_append(headers, "Content-Type: application/json");

		curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);



		curl_easy_setopt(curl, CURLOPT_POSTFIELDS, postthis);

		curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, 23L);

		curl_easy_setopt(curl, CURLOPT_WRITEDATA, (std::string*)&chunk);

		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, handleResponseCallback);

		curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

               curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);



		 

		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);

		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);



      res = curl_easy_perform(curl);

      curl_slist_free_all(headers);

      

      

      if (res != CURLE_OK)

      {

         std::cout << stderr << "curl_easy_perform() failed: " << std::endl;

         curl_easy_strerror(res);

      }

         

      curl_easy_cleanup(curl);

      

   }

	else

	{

      throw std::runtime_error("Curl init error");

	}

**Comment by bagder** [comment]
Which libcurl version on what platform? Which TLS library and version?

**Comment by shmn18** [comment]
curl version is 7.73.0 and openSSL version 1.0.1s. curl -k command works fine when I try to post and get from the server.

**Comment by bagder** [comment]
>  curl_easy_setopt(m_curl, CURLOPT_SSL_VERIFYHOST, 0L);

That looks really wrong.

**Comment by shmn18** [comment]
Yeah its curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);. Sorry wrong copy and paste. But it still complaints about cert file. 
""error reading ca cert file /etc/ssl/certs/ca-certificates.crt (Error while reading file.)""

**Comment by bagder** [comment]
The message appears in the verbose output, yes, but it doesn't return an error when `CURLOPT_SSL_VERIFYPEER` is disabled:

https://github.com/curl/curl/blob/278b46751ec0950a1732f1e8de3438f0bf570abf/lib/vtls/openssl.c#L3096

**Comment by bagder** [comment]
What does `curl_easy_perform()` return?

**Comment by shmn18** [comment]
if(res != CURLE_OK)

   {

      std::cout << stderr << "curl_easy_perform() failed: %s\n" << std::endl;

      curl_easy_strerror(res);

   }

I have this if statement and it returns ### 0x76402cd8curl_easy_perform() failed: %s ###

**Comment by bagder** [comment]
That message doesn't help. It doesn't show what `res` contained nor what `curl_easy_strerror` returns for that error...

**Comment by shmn18** [comment]
CURLcode res;

**Comment by bagder** [comment]
Yes, but what does it contain when curl_easy_perform() returns?

**Comment by shmn18** [comment]
* Hostname was NOT found in DNS cache
*   Trying 10.1.135.37...
* Connected to http.fast.fmpopt.scania.com (10.1.135.37) port 443 (#0)
* error reading ca cert file /etc/ssl/certs/ca-certificates.crt (Error while reading file.)
* gnutls_handshake() failed: Handshake failed
* Closing connection 0
0x76466cd8curl_easy_perform() failed: %s

This the output I get.

**Comment by piru** [comment]
@shmn18 

When reporting problems, it is generally frowned upon to include partial / modified information (such as source code) vs the actually used one. Doing so makes it difficult and often impossible to find out what is wrong.

From your responses it seems to me that you're relatively new into C++ programming. That's ok, but I'd recommend that you'd concentrate more on basic concepts of C++ programming before tackling something as complex as this.

**Comment by bagder** [comment]
> gnutls_handshake() failed: Handshake failed

So you're using GnuTLS, not OpenSSL...

After `res = curl_easy_perform(curl);`

Add: `printf("res = %d\n", res);` to show what the variable holds.

Also note that your program passes on a `CURLOPT_POSTFIELDSIZE` that is larger than the buffer you pass to libcurl, which nobody should do.

**Comment by shmn18** [comment]
@bagder   
### * Closing connection 0
res = %d
35 ###

It prints out the above message.

**Comment by bagder** [comment]
That's `CURLE_SSL_CONNECT_ERROR` and it is not related to `CURLOPT_SSL_VERIFYPEER`. This is not a curl bug. This is GnuTLS failing to negotiate a TLS connection with that server. Unfortunately, it doesn't provide a very good error description to help you figure out what to do next.
