### ISSUE TITLE
curl appends extra headers in whois queries

### ISSUE THREAD

**Issue by Roundik** [curl/curl#732]
Hello! 
I think, curl appends its extra headers in whois queries:

`$domain = "google.info";
$whois_server = "whois.afilias.net";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $whois_server.":43"); // Whois Server
//curl_setopt($ch, CURLOPT_PORT, 43);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $domain."\x0D\x0A"); // Query
$whois = curl_exec ($ch);  

echo "RESULT: ".$whois;
echo "<br/>";
echo curl_errno ($ch);
echo "<br/>";`

I get the following error from server

> 
RESULT: Neither object nor interpretation control keyword found
<br/>0<br/>

**Comment by bagder** [comment]
What "extra headers" ? curl will send an HTTP request to that site and a normal default HTTP request will include a few headers. curl has no special whois support. You adding CRLF to `CUSTOMREQUEST` will however make the request an illegal HTTP request, not to mention that the request you specify isn't a known HTTP request.

**Comment by Roundik** [comment]
simple fsockopen is ok with the same query $domain."\x0D\x0A" or $domain."\r\n"

There is an option to disable all http headers?

I thought "CURLOPT_CUSTOMREQUEST" would help to turn them off, but is not.

**Comment by bagder** [comment]
> simple fsockopen is ok

I don't see how that is relevant, and why don't you just use that then if it works? Also recall that curl/libcurl is used by a bazillion other apps and languages than PHP and is not specifically made for PHP.

> There is an option to disable all http headers?

When asking curl to speak HTTP it will use the default set. You can disable the headers curl will use but you have to disable them explicitly one by one. I don't think "disable all headers" is commonly requested. Note that even disabling all headers doesn't stop libcurl from still talking and presuming HTTP to this host. 

> I thought "CURLOPT_CUSTOMREQUEST" would help to turn them off, but is not.

I don't think there's anything in the `CURLOPT_CUSTOMREQUEST` documentation that implies said functionality, do you?

**Comment by Roundik** [comment]
CURL is very simple and useful for multithreaded operations.

So, if it is our fault that we did not know the documents - perhaps you can help?

We are grateful.

**Comment by bagder** [comment]
> perhaps you can help?

I thought I was already helping.

libcurl actually has an API for doing "raw" socket operations but I strongly discourage people from using it unless you understand the implications and how to use it perfectly. libcurl is really aimed and best used when you want to transfer data using one of the many protocols it supports, not when you just want to do some random TCP operations (using another protocol than what libcurl natively supports) - like in this case for the whois server. This behavior and functionality is not expected to change, as it is sort of fundamentally what libcurl is.

So, what more help are you looking for?
