### ISSUE TITLE
Tests for cross compiling, server fails to start!

### ISSUE THREAD

**Issue by pranav-vm** [curl/curl#7321]
Hi I know curl doesn't support running tests during cross compiling, but when I ran make test during the compilation I found out the test suite was built. So I copied the test directory along with the necessary files to support it to my target machine. But to my surprise certain test cases ran but most of them failed saying, the server couldn't be started.

failed starting HTTP server

 command: ./runtests.pl -g 9
output:
RUN: Unknown server on our http port: 35079 (28)
RUN: HTTP server failed verification
Terminated 
== Contents of files in the log/ dir after test 9
=== Start of file http_server.log
 09:18:34.358580 Running HTTP IPv4 version on port 35079
 09:18:34.362202 Wrote pid 952 to .http_server.pid
 09:18:34.363873 Wrote port 35079 to .http_server.port
 09:18:48.135136 exit_signal_handler: 15
 09:18:48.137112 signalled to die
 09:18:48.142238 ========> IPv4 sws (port 35079 pid: 952) exits with signal (15)
=== End of file http_server.log
=== Start of file http_verify.log
 *   Trying 127.0.0.1:35079...
 * Connection timed out after 13003 milliseconds
 * Closing connection 0
=== End of file http_verify.log
test 0009 SKIPPED: failed starting HTTP server
TESTDONE: 1 tests were considered during 19 seconds.
TESTINFO: 1 tests were skipped due to these restraints:
TESTINFO: "failed starting HTTP server" 1 time (9)

TESTFAIL: No tests were performed

This is the case for most of the tests in the data folder. I believe that the server is either not starting or even though the server starts the tests fails to connect with them. I am not sure how it works, I am new here, so please guide me through even if it sounds silly. Thanks  :)

**Comment by dfandrich** [comment]
It's best to ask on the curl-library mailing list rather than using a Github
issue. Try running the tests with verbose logging with "make test TEST_Q='-a -p
-n -d -v'" to get some more clues and report what you see there.

**Comment by pranav-vm** [comment]
Sorry, I did not know the procedure, but the build is happening similar. 

I was cross compiling and my target machine doesn't support IPv4  and I guess predominant of the testsuite is designed in such a way to run tests in IPv4. Sorry for disturbing you, I guess we can close this.

Also a small doubt, do other tests like FTP and such  uses IPv4?

Secondly when running the ./resolve (present in tests/server) output of resolve.c I presume, is not resolving connections that is pertaining to IPv6.

This is the output form the terminal. This line is taken from /tests/data/test241 (https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/tests/data/test241) check the <precheck>tag.

./resolve --ipv6 ip6-localhost                                               
Resolving IPv6 'ip6-localhost' didn't work

test output:
test 0241 SKIPPED: Resolving IPv6 'ip6-localhost' didn't work
Terminated 

I  don't know why it happened, if you could help me with this thanks a lot in advance. Also if I am facing anymore issues I'll definitely ask in the curl-mailing list. Thanks.

**Comment by bagder** [comment]
> I was cross compiling and my target machine doesn't support IPv4 and I guess predominant of the testsuite is designed in such a way to run tests in IPv4.

Yes, the test suite assumes that IPv4 works to to connect to 127.0.0.1, yes.

You're welcome to help us improve it for systems where IPv4 doesn't work.

> Also a small doubt, do other tests like FTP and such uses IPv4?

Most tests use IPv4. Some use IPv6.

> ./resolve --ipv6 ip6-localhost
> Resolving IPv6 'ip6-localhost' didn't work

That checks a **resolve** of that host name, it doesn't check if IPv6 "works".

**Comment by pranav-vm** [comment]
Okay, but why does the output of ./runtests.pl 241 shows that output. I guessed that it couldn't resolve. So just wanted to know the cause.

**Comment by bagder** [comment]
I don't know what more to tell. It tries to resolve `ip6-localhost` but failed. It does the check because the test uses that host name. Most likely your system doesn't have such a host name setup.

**Comment by pranav-vm** [comment]
Well thanks for your help. I am closing this comment. Cheers mate!
