### ISSUE TITLE
rtsp wrong statuscodes

### ISSUE THREAD

**Issue by DenTricky73** [curl/curl#7323]
### I did this 
curl -v  rtsp://IP:554/12

### I expected the following

λ curl -v  rtsp://IP:554/12
~~~
*   Trying IP:554...
* Connected to IP(IP) port 554 (#0)
> OPTIONS * RTSP/1.0
> CSeq: 1
> User-Agent: curl/7.77.0
>
< RTSP/1.0 200 OK               <<<    Password protected  should be  401
< CSeq: 1
< Server: Hipcam RealServer/V1.0
< Public: OPTIONS,DESCRIBE,SETUP,TEARDOWN,PLAY,SET_PARAMETER,GET_PARAMETER
~~~

also

curl -v  rtsp://IP:554/justnonsensdir
~~~
RTSP/1.0 200 OK   << should be  404
~~~
### curl/libcurl version

[curl -V output]   curl 7.77.0 (x86_64-w64-mingw32)

**Comment by bagder** [comment]
Those response codes are given by **the server**. curl only shows you what the server said. This is not a curl issue.
