### ISSUE TITLE
cannot get full html of web page

### ISSUE THREAD

**Issue by Yang09701194** [curl/curl#7332]
### I did this

I'm using code follow, when getting `https://docs.microsoft.com/en-us/cpp/?view=msvc-160` it can get full html correctly,

but when getting `https://docs.microsoft.com/fr-fr/cpp/?view=msvc-160` it only get top half partially html. Normally it should get full html. can you help check it?

Code:

```
class CURLplusplus  // from https://stackoverflow.com/a/27026683/4573839
{
private:
	CURL* curl;
	stringstream ss;
	long http_code;
public:
	CURLplusplus()
		: curl(curl_easy_init())
		, http_code(0)
	{

	}
	~CURLplusplus()
	{
		if (curl) curl_easy_cleanup(curl);
	}
	std::string Get(const std::string& url)
	{
		CURLcode res;
		curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
		curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
		curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_data);
		curl_easy_setopt(curl, CURLOPT_WRITEDATA, this);

		ss.str("");
		http_code = 0;
		res = curl_easy_perform(curl);
		if (res != CURLE_OK)
		{
			throw std::runtime_error(curl_easy_strerror(res));
		}
		curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
		return ss.str();
	}
	long GetHttpCode()
	{
		return http_code;
	}
private:
	static size_t write_data(void *buffer, size_t size, size_t nmemb, void *userp)
	{
		return static_cast<CURLplusplus*>(userp)->Write(buffer, size, nmemb);
	}
	size_t Write(void *buffer, size_t size, size_t nmemb)
	{
		ss.write((const char*)buffer, size*nmemb);
		return size * nmemb;
	}
};

int main()
{
        CURLplusplus client;
	string y = client.Get("https://docs.microsoft.com/en-us/cpp/?view=msvc-160");
	cout << y << endl;   //  Here can get full html

	cout << "==================" << endl;

	string x = client.Get("https://docs.microsoft.com/fr-fr/cpp/?view=msvc-160");
	cout << x << endl;  //  Here cannot get  complete full html, only top half partially
}
```

### curl/libcurl version
7.68.0-DEV

### operating system
Windows 10

**Comment by bagder** [comment]
If the curl command line tool shows the full response (and it does, doesn't it?), then the problem is likely in your code and not in libcurl and then you're better off asking for help on the curl-library mailing list. We use this tracker for bugs.

**Comment by bagder** [comment]
> 		ss.write((const char*)buffer, size*nmemb);

Let me guess: that should rather be some kind of append?

**Comment by Yang09701194** [comment]
ok, I test with curl cmd it can get full html correctly, I'll try to find where to improve in the code, thank you.

**Comment by gvanem** [comment]
> string x = client.Get("https://docs.microsoft.com/fr-fr/cpp/?view=msvc-160");
> 	cout << x << endl;  //  Here cannot get  complete full html, only top half partially

Your example works fine for me. Giving approx 60 kByte for each URL.

**Comment by gvanem** [comment]
> are you using visual studio

Yes. MSVC-2019 / 32-bit. But from the cmd-line.

**Comment by Yang09701194** [comment]
Thank you. After some try I solve it. First I find that my console is freezed after `cout` the partially html, screenshot:
![image](https://i.imgur.com/cZxMaHE.png)

then all followed `cout` code not print to console, the console lost effect, so I guess there's some problem in cout printing, e.g some special encoding word crash the `cout`, or maybe `cout` has max length limit each print, string too long will length overflow.

so I try a basic method, flush after each one word cout, and it can successfully print complete html.  Code is:

```
string gethtml = client.Get("https://docs.microsoft.com/fr-fr/cpp/?view=msvc-160");
int len = gethtml.size();  //  it's correctly 60K
int idx = 0;
while (idx < len)
{
cout << gethtml.substr(idx, 1) << std::flush;
idx += 1;
}

```

Besides I try write the html to `ofstream` to txt file is complete html, so it is some unknown internal problem of my `cout console` or maybe computer env language setting. 

So `Get()` does correctly get full html, it's good code, and I can print all html succesfully.

**Comment by Yang09701194** [comment]
I have new discovery, if I use cmd first run `chcp 65001` to use `utf-8` `unicode` , then use cmd run the program, then simple `cout << gethtml << endl; ` works fine.  if I directly run the program, or use VS2017 debugging run the program, the console will be freezed. So it should be default code page setting of console not support Unicode, and I find that run `chcp` in cmd can get the currently used code page.

reference to :
https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
https://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using
https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

**Comment by jay** [comment]
I've never heard of the console freezing due to bad character output. The curl tool used to set the console code page to UTF-8 but since 7.63.0 it instead converts the UTF-8 output to UTF-16 and uses WriteConsoleW to output it to the console, which is safer. You could try something similar in your program. Refer to #3212.
