### ISSUE TITLE
Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by jesusyang** [curl/curl#7336]
Bug：
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _RAND_poll in IJKMediaPlayer(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My configuration：
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15 19A583 darwin-x64, locale
    zh-Hans-CN)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Connected device (1 available)

**Comment by bagder** [comment]
Which curl version? How do you buiid it?

**Comment by bagder** [comment]
No response.
