### ISSUE TITLE
Windows build with static OpenSSL

### ISSUE THREAD

**Issue by DBLouis** [curl/curl#7337]
Is it possible to build curl with a static OpenSSL for Windows 10, using cargo with `--target x86_64-pc-windows-gnu`?

**Comment by jay** [comment]
We don't use cargo (for rust? as far as I know) but I think you can use a static OpenSSL with any of the other build systems. For example pre-generated projects [README](https://github.com/curl/curl/blob/curl-7_77_0/projects/README) or winbuild [README](https://github.com/curl/curl/blob/curl-7_77_0/winbuild/README.md). For the former it would be a build configuration like `LIB Release - LIB OpenSSL` and for the latter it would be by using nmake argument `WITH_SSL=static`

**Comment by DBLouis** [comment]
My mistake, I am using the rust crate, so I should report to their repo, but somehow I posted here 🤔
