### ISSUE TITLE
can not build with quiche

### ISSUE THREAD

**Issue by alexliyu7352** [curl/curl#7338]
configure: -l is -lquiche
configure: -I is -I/opt/code_test/code/quiche/include
configure: -L is -L/opt/code_test/code/quiche/target/release
checking for quiche_connect in -lquiche... no
configure: error: couldn't use quiche

quiche is the latest version

**Comment by dfandrich** [comment]
Take a look at the setup.log file to get some clues as to why it's not finding
your quiche library.

**Comment by alexliyu7352** [comment]
Sorry, it was my mistake.

**Comment by theDEADpool** [comment]
> Sorry, it was my mistake.

May I ask how do you solve this problem？
