### ISSUE TITLE
--ipv4 not working when using proxy

### ISSUE THREAD

**Issue by shithappens2016** [curl/curl#7345]
network has both ipv6 & ipv4
`--ipv4` wouldn't working when using proxy

```shell
curl --ipv4 -x socks4://111.111.111.111:9090  https://www.cloudflare.com
```
curl still gonna try to connect ipv6 address

end up:

```shell
SOCKS4 connection to 2409:8728:5eff:1005:3::3fe not supported
```

**Comment by bagder** [comment]
Any chance you can try #7346 and see if it fixes the issue for you?

**Comment by shithappens2016** [comment]
yes
It seems to be OK

**Comment by bagder** [comment]
Thanks!
