### ISSUE TITLE
MinGW libcurl static build issues linking with nghttp2

### ISSUE THREAD

**Issue by brechtsanders** [curl/curl#7353]
When libcurl (7.77.0) is built with nghttp2 (1.43.0) for Windows using MinGW-w64 there are linker errors when building against static libcurl related to missing symbols from nghttp2.

I was able to solve this issue by adding
```
#if defined(BUILDING_LIBCURL) && !defined(DLL_EXPORT)
#define NGHTTP2_STATICLIB
#endif
```
at the top of:

- lib/http2.c
- lib/http.c

This solution makes sure no dllimport is used when calling nghttp2 functions.

Other people are experiencing the same issue, see for example:
https://stackoverflow.com/questions/68265857/using-static-libcurl-a-in-c-program-by-mingw64/68267767#68267767

**Comment by bagder** [comment]
In general, building static is a roller coaster left for the users to deal with on their own as its such a never-ending race for us to try to support.

The proposed solution here doesn't seem to be enough. Where is `DLL_EXPORT` coming from? This will define `NGHTTP2_STATICLIB` for pretty much all builds...

**Comment by midnqp** [comment]
@bagder Not to bother you - just a little thing, please. 

I'm directly using the static libs from https://curl.se/windows/. They're working really great, and I'm very close to statically linking `libcurl` to my C program. 

But only I'm getting **undefined references** to `BrotliTransformDictionaryWord` `_kBrotliContextLookupTable` and 4 other like this. These are supposed to, I guess, be inside `libbrotlicommon-static.a`.

**Comment by brechtsanders** [comment]
@bagder Yes static builds can involve some puzzling, even when using `pkg-config`, ant to make matters worse MinGW is picky about the order of the `-l` library flags.

Defining `NGHTTP2_STATICLIB` on all platforms for static builds should be fine, but it's only really needed on Windows because of the `dllimport`/`dllexport` stuff. However if you don't trust it you can always add `defined(_WIN32)` to narrow it down to Windows only.

The define `DLL_EXPORT` is defined by autoconf tools for shared builds. When using cmake there should be a similar thing, but there the define is based on the library name passed to `add_library` by appending `_EXPORT` to the library name. So I guess `libcurl_EXPORT` should be defined for shared cmake builds (`-DBUILD_SHARED_LIBS:BOOL=ON `).

So the fix should probably be something more like this:
```c
#if defined(_WIN32) && defined(BUILDING_LIBCURL) && !(defined(DLL_EXPORT) || defined(libcurl_EXPORT))
#define NGHTTP2_STATICLIB
#endif
```

**Comment by midnqp** [comment]
@bagder  @brechtsanders  Guys, super good news! I finally succeeded to **statically link curl** into my project, and even compile my whole project statically!! This is my project: [Chat@Terminal:~$](https://github.com/midnqp/terminal.chat).
<br>
The idea behind the project is:  
  - just upload a PHP file to your server
  - and, you've started your own chat network.
  - invite people to your network, and start talking with them.
  
  The full MinGW command which I used to statically build the project will be found in the `make.bash`.

**Comment by brechtsanders** [comment]
@midnqp I still see no reason that it needs to be a static build.
If you make a shared build and make sure all DLLs are in the same folder as  the EXE(s) it should work just as well, but save you a lot of headaches building it.
I have a project at https://github.com/brechtsanders/pedeps that provides a tool which can copy an `.exe` file and all the `.dll` files it needs (`copypedeps -r`).

**Comment by bagder** [comment]
> So the fix should probably be something more like this:

How can the curl build know that you want to build with a static nghttp2? The symbols you mention here refer to the build of libcurl specifically! You seem to suggest that if you build a static libcurl you must also build with a static nghttp2...

**Comment by brechtsanders** [comment]
Both autotools and cmake assume you are building shared libraries with the dependancies also linked shared, and static libraries linked with the dependancies also linked static.

But it is true you can build a shared DLL that has all it's dependancies statically linked in.
If you support this in some way via autotools and/or cmake, then it should be possible to keep track of this with some define (`-D` compiler flag)...

**Comment by jay** [comment]
This issue sounds similar to #2516. Use CFLAGS and pkg-config --static. pkg-config does not support a separate/additional cflags just for static builds.
