### ISSUE TITLE
Kerberos SPN look up failed when the proxy URL is "CNAME" instead of "A Record"

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#7363]
The Kerberos SPN should be looked up based on A record, not CNAME. The issue we’re having is that libcurl is looking up the CNAME for our proxy instead of its A record.

For Kerberos, it’s necessary to fully resolve any CNAMEs down to the underlying A record to get the SPN. Some implementations don’t do this properly or need to be configured to do it. For example, let’s say we have the following DNS setup:

aaa.net is a CNAME that resolves to bbb.net
bbb.net is a CNAME that resolves to ccc.net
ccc.net is an A record that resolves to xx.xxx.xxx.xx

The issue is when proxy URL is ‘aaa.net’, libcurl needs to keep resolving each CNAME until it gets to an A record, in this case ‘ccc.net’. At this point, it performs an SPN lookup of that A record and gets a Kerberos ticket for it.

### I expected the following
Successfully get Kerberos ticket when using CNAME

### curl/libcurl version

7.71.1

### operating system

Windows

**Comment by bagder** [comment]
I don't understand how you use curl to see this issue. Can you show us a full command line?

Note that curl is using the regular name resolving functions (in most builds) and they resolve name to IP without even telling if the name was a CNAME or A or AAAA etc so curl cannot easily tell the difference. But also: CNAME or A, they will resolve to the same IP...

**Comment by ustcqidi** [comment]
@bagder Thanks .

Actually, we are not using command line, but using libcurl embeded in our application.

We are tring to connect the proxy with Kerberos and NTLM authentication, based on the negoticate.  But, it seems to the authentication always negoticated as NTLM, even we configed prefered to Kerberos.

After digging into about this  issue, we found if we using the proxy url with A Record directly, everything works as normal.  But if we using the proxy url which is a CNAME, will cause get kerberos ticket failed. 

The ticket we get here looks like following,  which is not a Kerberos ticket,

Proxy-Authorization: Negotiate TlRMTVNTUAABAAAAt4II4gAAAAAAAAAAAAAAAAAAAAAKADk4AAAADw==\r\n

Related function:
Curl_auth_decode_spnego_message in spnego_sspi.c

**Comment by ustcqidi** [comment]
It seems to some guys also post similar dicusstion about this.

https://curl.se/mail/archive-2019-01/0014.html#replies

**Comment by bagder** [comment]
I don't know anything about this and I don't use Windows, but a quick googling on the topic suggests that it will not work correctly with CNAMEs in general even with other tools so isn't this a problem in your setup then rather than in curl?

One source is answers to this serverfault question: https://serverfault.com/questions/481289/will-kerberos-work-with-cnames-if-i-have-the-spn-created-for-the-a-record-as-wel

curl cannot easily figure out the A name of a CNAME entry.

**Comment by ustcqidi** [comment]
@bagder Thanks for your feedback about this.
