### ISSUE TITLE
LibCurl build fails if _POSIX_C_SOURCE=200809L and -std=c11 are set

### ISSUE THREAD

**Issue by Dani-Hub** [curl/curl#7365]
### I did this
We are building libcurl via cmake using gcc9 and gcc10 by using (among others) the compiler flags
```
-std=c11 -D_POSIX_C_SOURCE=200809L
```
The result is that the build fails, as shown by the following Jenkins output:
```
[INFO] /home/jenkins/workspace/dmb1/se.haxx.libcurl-linux-x86_64-gcc10/src/lib/if2ip.c: In function 'Curl_if2ip':
[INFO] /home/jenkins/workspace/dmb1/se.haxx.libcurl-linux-x86_64-gcc10/src/lib/if2ip.c:188:16: error: storage size of 'req' isn't known
[INFO]   188 |   struct ifreq req;
[INFO]       |                ^~~
```

It seems that the feature ifreq is not unconditionally available and it depends on the combination of compiler settings whether or not the feature is provided. We fixed the problem in our copy of libCurl using the following patch file:

```
Index: src/lib/if2ip.c
===================================================================
--- src/lib/if2ip.c	(revision 820)
+++ src/lib/if2ip.c	(working copy)
@@ -20,6 +20,10 @@
  *
  ***************************************************************************/
 
+#ifndef _GNU_SOURCE
+# define _GNU_SOURCE
+#endif
+
 #include "curl_setup.h"
 
 #ifdef HAVE_NETINET_IN_H
```
With this single patch of one file the complete libCurl build succeeds. I'm willing to provide a pull request, if agreement to this suggested change exists.

### I expected the following
A successful build.

### curl/libcurl version
7.77.0

### operating system
Debian 10

**Comment by danielgustafsson** [comment]
curl and libcurl aren't written in C11, so compiling with `-std=c11` is probably not going to yield good results.

The presence of `struct ifreq` is tested for by `CURL_CHECK_FUNC_IOCTL_SIOCGIFADDR` in `m4/curl-functions.m4`. Do you have a system where `HAVE_IOCTL_SIOCGIFADDR` is set but `struct ifreq` isn't available?

**Comment by Dani-Hub** [comment]
As our general guideline we build all common sources (We build libCurl as static library) using exactly the same compiler settings, so we use C11 here as in our other C-based sources. Yes, the test for `HAVE_IOCTL_SIOCGIFADDR` sets this define, but later the actual build fails since `struct ifreq`is not defined except when `_GNU_SOURCE` is defined.

**Comment by bagder** [comment]
I don't think it is our job to make the code work with whatever crazy flags you throw at it. If you break the build by adding custom flags, the easiest build fix is rather to remove those custom flags...

**Comment by danielgustafsson** [comment]
> On 8 Jul 2021, at 20:36, Daniel Krügler ***@***.***> wrote:

> As our general guideline we build all common sources (We build libCurl as static library) using exactly the same compiler settings, so we use C11 here as in our other C-based sources.

Fair enough, but then you also need a guideline to keep local patches to fix builds which breaks due to that.

> Yes, the test for HAVE_IOCTL_SIOCGIFADDR sets this define, but later the actual build fails since struct ifreqis not defined except when _GNU_SOURCE is defined.

libcurl isn’t written in GNU C so defining _GNU_SOURCE isn’t correct.

**Comment by Dani-Hub** [comment]
In my opinion this issue has been prematurely closed without sufficient reasoning. Assertions like "whatever crazy flags you throw at it" do not sound like an objective measure of the problem described. Keep in mind that in theory this flag combination could have been among the default flags of a compiler. Can you please explain why you consider the here described flag combination as insane? Furthermore, this is an issue, not a concrete pull request. I was _suggesting_ an approach to solve this issue and if you disagree with that approach you should either provide a better approach or at least should allow the issue submitter to work on a more agreeable solution. Simply closing the issue because you don't like the suggested fix seems a rude way to get rid of this issue. In my opinion a preferable solution would be a source code fix (instead of a fix in the cmake code), because that makes the code more portable and future-proof. But if your preferred solution would be fix in the libcurl cmake code this should at least be discussed, since in this case it seems necessary to override the setting, if the default compiler setting would be as described in this issue.

**Comment by bagder** [comment]
It was closed because we don't consider it to be a curl issue. That's not personal nor anything against you. It just reflects the way several of us view the explained problem. If it's not a curl issue, we close it to mark it as such and to let everyone know they don't need to spend time on this issue.

The options are in my mind "crazy" because they seriously alter how the compiler deals with the code. I can't see how we can practically take responsibility to make curl work with custom additional compiler options that alter the compiler's action to such an extend as these options. I also don't understand why we would - putting over the work of fixing your build on curl instead of just fixing it in your build scripts.
