### ISSUE TITLE
Content-Type unnecessarily sent when no body included in POST request

### ISSUE THREAD

**Issue by nathankellenicki** [curl/curl#7381]
Hi,

We're calling an internal endpoint via POST for which no message body is expected by the server. It seems that when doing this, libcurl automatically adds a Content-Type of `application/x-www-form-urlencoded`.

https://github.com/curl/curl/blob/e7416cfd2bd58d256b8524f31ef22a43aa23a970/lib/http.c#L2544-L2546

We use an internal framework that validates incoming requests against our own Client/Server Interaction Standards, one of which is that we only support `application/json`. As a result, the server rejects the request based on the Content-Type alone.

We've since modified the framework to only validate the Content-Type header if the message length > 0. This seems like the correct thing to do as why should a server that's expecting no body care about the Content-Type of the non-existent body.

On the flip-side however, it seems to me that perhaps curl shouldn't be adding this header by default. Unless I'm misreading it, [The HTTP 1.1 spec](https://datatracker.ietf.org/doc/html/rfc2616#section-7.2.1) implies that the header is optional when no body is provided. Aside from saving on precious few bytes when not required, it's making an opinionated choice to add the header under the assumption that the user forgot to add it, which may not be correct in all circumstances (such as ours).

We considered simply specifying the header as `application/json` just to get around the issue, but our client code is autogenerated from OpenAPI specifications describing our endpoints. To do so we'd add the header to the spec, but it seems there's no semantically accurate way to describe this scenario in the OpenAPI standard. See this StackOverflow question: https://stackoverflow.com/questions/58923812/how-to-add-a-content-type-on-a-post-request-with-no-body-in-openapi-3-0

As the header is optional, it seems to me that the header shouldn't be included by default, or at least an option be provided to disable the behavior.

Many thanks,
Nathan

### I did this

Sent a POST request with a zero length body. A Content-Type header with `application/x-www-form-urlencoded` was included in the request.

### I expected the following

No Content-Type header to be included in the request, as it is unnecessary for zero length bodies.

### curl/libcurl version

curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

**Comment by jay** [comment]
[CURLOPT_POST](https://curl.se/libcurl/c/CURLOPT_POST.html) is documented as _"A parameter set to 1 tells libcurl to do a regular HTTP post. This will also make the library use a `Content-Type: application/x-www-form-urlencoded` header."_

and

> As the header is optional, it seems to me that the header shouldn't be included by default, or at least an option be provided to disable the behavior.

_"You can override the default POST Content-Type: header by setting your own with CURLOPT_HTTPHEADER."_

IMO it's appropriate to include it by default. I'd be worried about breakage from the opposite, what would happen if we don't include Content-Type by default for a known 0 bytes and some server still expects a specific type.

**Comment by nathankellenicki** [comment]
> > _"You can override the default POST Content-Type: header by setting your own with CURLOPT_HTTPHEADER."_

I described in my issue why it is not possible for us to do this.

> IMO it's appropriate to include it by default. I'd be worried about breakage from the opposite, what would happen if we don't include Content-Type by default for a known 0 bytes and some server still expects a specific type.

Well, as I also described, the reverse is also true. :) Our server broke because it was receiving a Content-Type it didn't support which we didn't set.

I do however understand the concern for backwards compatibility, so I proposed an option to **turn off** the default header behavior.

It seems correct, as the HTTP spec allows, to allow the option for no Content-Type header to be sent **at all** if no message body is to be sent.

**Comment by jay** [comment]
> > > _"You can override the default POST Content-Type: header by setting your own with CURLOPT_HTTPHEADER."_
> 
> I described in my issue why it is not possible for us to do this. In addition, the HTTP spec does not require it.

Yeah but what you are describing is a limitation of the way you are using libcurl and not libcurl itself. The header can be deleted by using [CURLOPT_HTTPHEADER](https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html) and I don't see why we would add a special option to do that.

_"If you add a header with no content as in 'Accept:' (no data on the right side of the colon), the internally used header will get disabled. With this option you can add new headers, replace internal headers and remove internal headers."_

**Comment by nathankellenicki** [comment]
> Yeah but what you are describing is a limitation of the way you are using libcurl and not libcurl itself.

Of course. No dispute.

> The header can be deleted by using [CURLOPT_HTTPHEADER](https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html) and I don't see why we would add a special option to do that.
> 

Because IMO it's a negative that curl is providing opinionated defaults that may break certain servers, despite them being spec compliant.


> _"If you add a header with no content as in 'Accept:' (no data on the right side of the colon), the internally used header will get disabled. With this option you can add new headers, replace internal headers and remove internal headers."_
> 

Thanks, I wasn't aware of that detail, that's useful. But that still requires being set on a per request basis. I do feel that an option to "turn off opinionated default headers" would be useful.

**Comment by jay** [comment]
> Let me reframe the question a little - does it make sense for curl to include a header declaring an arbitrary Content-Type when content is non existent?

It's not arbitrary and that's how it's documented. There's already a way to turn it off. I don't think a new option would be useful but I'll leave this open for a bit to gather more feedback.

**Comment by bagder** [comment]
I'm totally agreeing with @jay here.

**Comment by bagder** [comment]
Not a bug.

**Comment by utdream** [comment]
Found this post because I was attempting to test a JSON-only API using curl and found that curl was arbitrarily adding this content type header and ruining my requests. I would get a "Bad Request" error from Apache because there were two "Content Type" header statements in my requests. The one I told curl to add: -H 'Content Type: application/json', and the one that Curl was arbitrarily adding without my request or permission.

I realize my opinion doesn't matter, but Nathan is making an excellent point here, and he did so very professionally. It's a shame neither of you listened to him.

To have curl arbitrarily dump this header in when I'm already giving it a 'content type' header to use, makes curl a less valuable tool. As the user, I should be the one to decide what headers are sent - not have curl do it for me simply because it thinks that's what I need.
