### ISSUE TITLE
on passing self signed certificate with --cacert or --cert in windows it is giving error 

### ISSUE THREAD

**Issue by Mukund106** [curl/curl#7384]
###  i downloaded certificate from a server and then running curl cmd "curl -s -o /dev/null -w "%{http_code}" --cacert cert.pem https://myown.iot.com"
Getting error  "curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted." in windows but in case of linux system it is giving proper output.
Here cert.pem is self signed certificate

### curl/libcurl version
curl 7.55.1 
[curl -V output]
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
windows 10

**Comment by icing** [comment]
You cannot just treat a self-signed server certificate as a CA certificate. There are difference in how those certificates are made.

If you want a local set of CA and server certificates, I'd recommend https://trustme.readthedocs.io/en/latest/

**Comment by Mukund106** [comment]
@icing 
But when i am running same cmd in linux system it is not giving this error .it is coming up with 200 as output.

**Comment by icing** [comment]
That depends on what the underlying SSL library is willing to accept as a CA certificate. Unfortunately, there are differences.

**Comment by Mukund106** [comment]
@icing 
is there any way to establish https connection using curl if certificate is self-signed in case of windows?

**Comment by icing** [comment]
Not a windows expert. There is always `--insecure`, but you know that probably.

**Comment by jay** [comment]
I can reproduce this in 7.55.0 but not the latest version 7.77.0.

curl 7.77.0-DEV (i386-pc-win32) libcurl/7.77.0-DEV Schannel WinIDN

**Comment by Mukund106** [comment]
Thanks @jay 
Updating curl to 7.77.0 worked

**Comment by Mukund106** [comment]
@jay 
What’s the earliest version that supports --cacert in windows?
i.e there is no need of installation of certificate

**Comment by jay** [comment]
> What’s the earliest version that supports --cacert in windows?

7.60.0
