### ISSUE TITLE
curl / libCurl does not work with mbedTLS 3.0.x.

### ISSUE THREAD

**Issue by wyattoday** [curl/curl#7385]
### I did this

Attempt to compile the latest curl using the latest mbedTLS (currently 3.0.0) with MBEDTLS_DEPRECATED_REMOVED defined.

### I expected the following

A successful compilation with a working TLS library.

### curl/libcurl version

7.77.0

### operating system

CentOS 7.

## The problem

There are a number of issues (breaking changes) made in mbedTLS 3.0. Some of them are covered in [the mbedTLS 3.0 migration guide](https://github.com/ARMmbed/mbedtls/blob/development/docs/3.0-migration-guide.md).

The largest changes effecting curl are:

1. Dropping of md4 in the library (effects NTLM). This is an easy enough fix (`#  if defined(USE_MBEDTLS) && defined(MBEDTLS_MD4_C)` in curl_setup.h)

2. Some header changes. Another easy fix:

Instead of...

```
#include <mbedtls/config.h>
#include <mbedtls/version.h>
```

Do this...

```
#include <mbedtls/version.h>

#if (MBEDTLS_VERSION_MAJOR < 3)
#include <mbedtls/config.h>
#else
#include <mbedtls/mbedtls_config.h>
#endif
```

3. The hashing functions return by default, and the "return" version of the hash functions no longer exist. Again, another easy fix. For example, for md5:

```
static void MD5_Init(MD5_CTX *ctx)
{
#if !defined(HAS_MBEDTLS_RESULT_CODE_BASED_FUNCTIONS) || (MBEDTLS_VERSION_MAJOR >= 3)
  (void) mbedtls_md5_starts(ctx);
#else
  (void) mbedtls_md5_starts_ret(ctx);
#endif
}
```

4. The largest breaking changes are curl's use of internal structures in the "pinned key" checking in `mbed_connect_step2`. Namely, the use of `peercert->raw.p` and `peercert->raw.len` which are both private struct members now. This is the thing I haven't had time to work on. Namely, to do it correctly and in a backwards compatible way.

I haven't had time to work on this to completion, so I'll leave this here until either I have time to circle back to it or someone else steps in.

**Comment by bagder** [comment]
I consider this an "enhancement" and not a bug because clearly mbedTLS has deliberately decided to not maintain its API and thus supporting their v3 is a job for someone who wants it done.

**Comment by danielgustafsson** [comment]
I propose to add this to the TODO document and leave it at that until someone picks it up. Unless there  are objections I will do so shortly.

**Comment by Benau** [comment]
https://github.com/Benau/curl/commit/a5a82e86b54c4754806d97e4f833446f485a3b8d

Works in android, other OS not tested

FYI, https://github.com/curl/curl/discussions/7376#discussioncomment-995479

**Comment by bagder** [comment]
@Benau so how about making a "proper" PR out of it?
