### ISSUE TITLE
--connect-to appears not respected for specific build same version, produces seemingly incorrect debug output

### ISSUE THREAD

**Issue by alex-shafer-ceshop** [curl/curl#7392]
### I did this

On my mac, using `curl 7.77.0 (x86_64-apple-darwin20.4.0) libcurl/7.77.0 (SecureTransport) OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.5`, I tried:

```
curl --connect-to ::my-aws-alb-with-http2-support.amazonaws.com: https://mytest.org
...
* Connected to <the --connect-to host>
...
* ALPN, server accepted to use h2
* Server certificate:
*  <the cert for the --connect-to host>
*  SSL certificate verify ok.
```

In docker, running an image based on `ubuntu:20.04`, using `curl 7.77.0 (x86_64-pc-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.5`

```
curl --connect-to ::my-aws-alb-with-http2-support.amazonaws.com: https://mytest.org
...
* Connected to <the --connect-to host>
...
* ALPN, server did not agree to a protocol
* Server certificate:
*  <the cert for mytest.org>
*  SSL certificate verify ok.
``` 

### I expected the following

All curl builds with the same version respect `--connect-to` equally, and produce accurate debug output about which host was connected to regardless of the use of this option.

### curl/libcurl version

From my mac:

```
curl 7.77.0 (x86_64-apple-darwin20.4.0) libcurl/7.77.0 (SecureTransport) OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.5
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

From the docker image:

```
curl 7.77.0 (x86_64-pc-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.5
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

Both were installed with homebrew.

### operating system

From my mac:

```
Darwin CEAdmins-MBP 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

From the docker image:

```
Linux 9ebda9105ee9 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jay** [comment]
> * Connected to <the --connect-to host>

did you check the IP addresses, is this an issue in your docker where my-aws-alb-with-http2-support.amazonaws.com resolves to the same IP as mytest.org, or is the former hosting the latter by chance? what happens if you request httpbin.org instead of mytest.org

**Comment by alex-shafer-ceshop** [comment]
Yes, both show the exact same IP address. The docker container has nothing special regarding DNS resolution. (To be clear the actual hostnames are different than these; they have been modified for redaction)

Testing with httpbin.org produces the same results, where, according to the connection-level debugging information it's connecting to my ALB (the `--connect-to` host), but the TLS debugging info and the HTTP response comes from the direct URL (`https://httpbin.org`) -- only when running the curl build in my docker container.

On my mac, I get the expected TLS validation failure, because it's getting the cert from my ALB which is not valid for httpbin.org.

When testing entirely with my hosts, the difference is clear in the cert, because while they are both valid for the URL, they have different issuers and start/end dates.

**Comment by jay** [comment]
It's unclear to me if it is the amazon host that is causing the issue. Can you run this command in docker, and attach the outfile: `curl --trace outfile --connect-to ::example.com: https://httpbin.org`

**Comment by alex-shafer-ceshop** [comment]
For what it's worth, the ALB is configured to respond only with specific Host header matches, and the default is to return a 404.

Here's the full trace from the requested command: https://pastebin.com/iiT8mTxQ

I am seeing the same buggy behavior:

"Connected to example.com"
```
* Connecting to hostname: example.com
*   Trying 93.184.216.34:443...
* Connected to example.com (93.184.216.34) port 443 (#0)
```

Getting a cert for httpbin.org
```
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Dec 21 00:00:00 2020 GMT
*  expire date: Jan 19 23:59:59 2022 GMT
*  subjectAltName: host "httpbin.org" matched cert's "httpbin.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
```

Response body appropriate to httpbin.org
```
    <title>httpbin.org</title>
```

**Comment by jay** [comment]
> "Connected to example.com"
> 
> ```
> * Connecting to hostname: example.com
> *   Trying 93.184.216.34:443...
> * Connected to example.com (93.184.216.34) port 443 (#0)
> ```
> 
> Getting a cert for httpbin.org
> 
> ```
> * Server certificate:
> *  subject: CN=httpbin.org
> *  start date: Dec 21 00:00:00 2020 GMT
> *  expire date: Jan 19 23:59:59 2022 GMT
> *  subjectAltName: host "httpbin.org" matched cert's "httpbin.org"
> *  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
> *  SSL certificate verify ok.
> ```

maybe curl's verbose connect output is wrong. can you try `strace -f -e trace=network -o outfile curl -v --connect-to ::example.com: https://httpbin.org` and upload outfile

**Comment by alex-shafer-ceshop** [comment]
Still, why would it ignore the `--connect-to` only in the linux-gnu build in docker? If the HTTP response is from httpbin.org, then it's definitely actually connecting to httpbin.org, right?

Getting that strace, standby ...

**Comment by alex-shafer-ceshop** [comment]
Here's the strace: https://pastebin.com/gktZSz6K

After noticing this:
```
connect(7, {sa_family=AF_INET6, sin6_port=htons(443), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "2606:2800:220:1:248:1893:25c8:1946", &sin6_addr), sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Cannot assign requested address)
```

I repeated with `curl -4 ...` and got the same results.

**Comment by jay** [comment]
The strace matches the curl output and appears normal.

`125   connect(5, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("93.184.216.34")}, 16) = -1 EINPROGRESS (Operation now in progress)`

Possibly some middlebox is intercepting based on the SNI, which is (correctly) httpbin.org. You can use packet capture (optionally with SSLKEYLOGFILE) to confirm but to share the trace of that may include personal detail such as MAC address. Basically, you want to see if the server hello reply followed by the certificate reply is actually coming from 93.184.216.34, and then check that certificate array to see if it has example.org or httpbin.org.

(I should point out I chose this wrong SNI scenario to example.com purposely because they will still serve the example.org/example.com certificate when an unknown SNI is passed, and many servers don't do that instead sending a generic certificate when there is no recognized SNI.)

**Comment by alex-shafer-ceshop** [comment]
Fascinating, docker is the only thing in the middle, so I tried running the container with host networking, which produced the expected results (TLS validation failure due to mismatch between example.com and httpbin.org).

Thanks so much for helping narrow this down, clearly not a curl issue at this point.
