### ISSUE TITLE
libcurl with SSL

### ISSUE THREAD

**Issue by aerjali** [curl/curl#7399]
We are developing an application using C and libcurl to call some SOAP API. using dbx debugger on AIX we got following call stack after the crash of the application: 
0x0900000006567214  ssl3_new() + 0x34
0x090000000658abb8  tls1_new() + 0x18
0x09000000150f7f50  SSL_CTX_check_private_key() + 0x68
0x0900000014d6831c  ossl_connect_step1(??, ??) + 0xaec
0x0900000014d696a4  ossl_connect_common(??, ??, ??, ??) + 0x184
0x0900000014d60858  Curl_ssl_connect_nonblocking(??, ??, ??) + 0x9c
0x0900000014d773bc  https_connecting(??, ??) + 0x20
0x0900000014d79214  Curl_http_connect(??, ??) + 0x168
0x0900000014d71738  multi_runsingle(??, ??, ??) + 0x608
0x0900000014d72cf4  curl_multi_perform(??, ??) + 0xf4
0x0900000014d5e0f8  curl_easy_perform(??) + 0x158

Machine: AIX, version: 7.1.0.0

The version of OpenSSL is: #: openssl version OpenSSL 1.0.2u 20 Dec 2019

CURL version:

#: curl --version curl 7.73.0 (powerpc-ibm-aix6.1.9.0) libcurl/7.73.0 OpenSSL/1.0.2t libssh2/1.9.0 Release-Date: 2020-10-14 Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets

We suspect that there is an issue with SSL but not sure what it's. Please let us know if you have faced such errors.

**Comment by jay** [comment]
> We suspect that there is an issue with SSL but not sure what it's. Please let us know if you have faced such errors.

I'm not aware of any issue like this.

**Comment by jay** [comment]
It's unlikely this is a libcurl issue. Unless you can give us a way to reproduce I'm going to close.

**Comment by aerjali** [comment]
This is more about an issue with OpenSSL on AIX. I will close this issue.
