### ISSUE TITLE
Install curl gives : Threaded resolver enabled but no thread library found

### ISSUE THREAD

**Issue by aerjali** [curl/curl#7402]
I'm trying to install libcurl from code source. I have the issue below when running : ./configure --with-openssl
checking for pthread_create in -lpthread... no
configure: error: Threaded resolver enabled but no thread library found

cURL version: 7.77. 
OS: AIX, version 7.1.0.0

**Comment by dfandrich** [comment]
The error message seems pretty self explanatory. Either disable use of the
threaded resolver (with --disable-threaded-resolver or --enable-ares) or make
sure pthreads is available. On AIX, the latter might mean supplying
LIBS=-lpthread or something similar to explicitly link to a pthread library.

**Comment by aerjali** [comment]
Thanks for the reply! I tried with --disable-threaded-resolver and it's really working fine but I want to compile with pthread. what's strange is that I have this library under /usr/lib. I believe it should take it. I will try with your proposal and see...Thanks a lot!

**Comment by bagder** [comment]
This sounds like the configure script doesn't find the pthread library correctly on AIX.

**Comment by aerjali** [comment]
It's not working even with setting LIBS variable. I tried with an old release(7.50) and it's not giving this error.
