### ISSUE TITLE
curl 7.77.0 cause http request timeout

### ISSUE THREAD

**Issue by corznoc** [curl/curl#7403]
### I did this
i use curl to send the http request，with content-type：application/json
it’s ok for curl 7.76 or oldder version
when i switched to curl 7.77.0，therequest always timeout.
### I expected the following
get http response without timeout.

### curl/libcurl version
7.77.0

[curl -V output]

### operating system
centos 7

**Comment by corznoc** [comment]
the server is normal.

**Comment by jay** [comment]
Do you have a way that we can reproduce?

> the server is normal.

Have you tried enabling [verbose mode](https://curl.se/docs/manpage.html#-v) to compare the requests?

**Comment by corznoc** [comment]
i am sorry, i use the libcurl 's esay api.
i my case, i use the same CURL handler for reuse the connection.
i can got response from the first time, after about 10 requests later, all the request will be timedout.

**Comment by corznoc** [comment]
the curl handler is a thread local variable

**Comment by jay** [comment]
Sorry but without additional information that we can use to reproduce there's nothing we can do here. I suggest examine the differences in the requests by using verbose mode.

> the curl handler is a thread local variable

Please review [libcurl thread safety guidelines](https://curl.se/libcurl/c/threadsafe.html).
