### ISSUE TITLE
doc: forms example for `,`/`;` should include example of `,`/`;`

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7415]
https://github.com/curl/curl/blob/bc035f5c9dc4e0387a615d2cc5914f37a90be1e2/docs/cmdline-opts/form.d#L60-L66

>  If filename/path contains ',' or ';', it must be quoted by double-quotes like: 
>  
>  curl -F "file=@\\"localfile\\";filename=\\"nameinpost\\"" example.com 
>  
> or 
>  
>  curl -F 'file=@"localfile";filename="nameinpost"' example.com 

The examples here only have a `;` between the file and the filename, but that `;` is probably not the semicolon the doc is talking about.

It'd be helpful if the example was more like:

> curl -F 'file=@"local,file";filename="name;in;post"' example.com 

Possibly explaining that `local,file` is a file (it's probably less important to clarify that there is no local file named `name;in;post`, although it wouldn't be harmful to indicate that it's the name to be sent as the filename over the wire).

**Comment by bagder** [comment]
Sounds like a reasonable suggestion to me!
