### ISSUE TITLE
Operation timed out when downloading a special https page

### ISSUE THREAD

**Issue by Q5211191** [curl/curl#7422]
The page below can be opened by chrome and firefox, but when I'm using libcurl, it's always operation timed out:

https://www.cmegroup.com/trading/price-limits.html

Firefox 70.0.1 and earlier version will time out too, while Firefox 71.0 and later version works fine.

My code:

	CURLcode res;
	CURL* curl = curl_easy_init();
	if(NULL == curl)
	{
		return CURLE_FAILED_INIT;
	}

	char h1[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9";
	char h2[] = "Accept-Encoding: gzip, deflate, br";
	char h3[] = "Accept-Language: zh-CN,zh;q=0.9";
	char h4[] = "Connection: keep-alive";
	char h5[] = "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36";
	char h6[] = "Host: www.cmegroup.com";
	char h7[] = "sec-ch-ua: \" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"";
	char h8[] = "sec-ch-ua-mobile: ?0";
	char h9[] = "Sec-Fetch-Dest: document";
	char h10[] = "Sec-Fetch-Mode: navigate";
	char h11[] = "Sec-Fetch-Site: none";
	char h12[] = "Sec-Fetch-User: ?1";
	char h13[] = "Upgrade-Insecure-Requests: 1";
	char h14[] = "Cache-Control: max-age=0";

	struct curl_slist *curlHeader = NULL;
	curlHeader = curl_slist_append(curlHeader, h1);
	curlHeader = curl_slist_append(curlHeader, h2);
	curlHeader = curl_slist_append( curlHeader, h3 );
	curlHeader = curl_slist_append( curlHeader, h4 );
	curlHeader = curl_slist_append( curlHeader, h5 );
	curlHeader = curl_slist_append( curlHeader, h6 );
	curlHeader = curl_slist_append( curlHeader, h7 );
	curlHeader = curl_slist_append( curlHeader, h8 );
	curlHeader = curl_slist_append( curlHeader, h9 );
	curlHeader = curl_slist_append( curlHeader, h10 );
	curlHeader = curl_slist_append( curlHeader, h11 );
	curlHeader = curl_slist_append( curlHeader, h12 );
	curlHeader = curl_slist_append( curlHeader, h13 );
	curlHeader = curl_slist_append( curlHeader, h14 );

	curl_easy_setopt(curl, CURLOPT_URL, "https://www.cmegroup.com/trading/price-limits.html");
	char szError[256] = { 0 };
	curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, szError);
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
	curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);
	curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1 );
	curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1 );
	curl_easy_setopt(curl, CURLOPT_HTTPHEADER, curlHeader);
	curl_easy_setopt(curl, CURLOPT_READFUNCTION, NULL);
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curl_onWriteData);
	curl_easy_setopt(curl, CURLOPT_WRITEDATA, (void *)pszpath);
	curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 30);
	curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30);

	res = curl_easy_perform(curl);
	curl_slist_free_all(curlHeader);
	curl_easy_cleanup(curl);

**Comment by bagder** [comment]
It works for me when I try this:

    curl 'https://www.cmegroup.com/trading/price-limits.html' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed

**Comment by bagder** [comment]
IOW: this is the server just refusing to send back content for a certain set of request headers, it's not a curl issue.

**Comment by Q5211191** [comment]
Thanks, but your command doesn't work for me, maybe the server checks both IP and headers.
I tried my best to simulate Chrome's headers, almost the same, just wondering how the server can tell the difference between chrome and my code.

**Comment by bagder** [comment]
I used "copy as curl" in Firefox to get a command line that worked for me.

**Comment by bagder** [comment]
also: if you redirect the output to somewhere (with `-o`) you'll get a progress meter which shows how curl is just waiting for data that never arrives.

**Comment by Q5211191** [comment]
Thank you!
