### ISSUE TITLE
http://curl.haxx.se/libcurl/c/libcurl-errors.html

### ISSUE THREAD

**Issue by Mayss77** [curl/curl#7426]
http://curl.haxx.se/libcul/c/libcurl-errors.html

**Comment by Nyholm** [comment]
I assume you want to report that this URL says 404. 
From where did you get this URL?

**Comment by Mayss77** [comment]
Код ошибки 185

**Comment by Nyholm** [comment]
> Error code 185

Okey. Thank you. 
What version of curl are you running?

**Comment by Mayss77** [comment]
Не знаю. Должна была ссылка с магазина придти ссылка с фотографией, а пришло вот что
 Ошибка на 185 строке: cURL error 7: Failed to connect to exchapi port 1337: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Попробуйте еще раз или обратитесь в помощь

**Comment by Mayss77** [comment]
Ошибка на 185 строке: cURL error 7: Failed to connect to exchapi port 1337: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Попробуйте еще раз или обратитесь в помощь

**Comment by Nyholm** [comment]
Oh. I see. Curl error 7 means that it is something wrong with the server you are connecting to. 

This is not an issue with curl itself. You should try contact the service/servers that you are trying to connect to. 

The port 1337 makes me believe it is not a public service. 

I suggest closing this issue.

**Comment by Mayss77** [comment]
А в какой именно сервер надо писать?

**Comment by Mayss77** [comment]
Что это такое?
