### ISSUE TITLE
curl_easy_strerror man page:

### ISSUE THREAD

**Issue by Mayss77** [curl/curl#7430]
Здраствуйте ссылка не работает

**Comment by Mayss77** [comment]
Ошибка на 185 строке: cURL error 7: Failed to connect to exchapi port 1337: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Попробуйте еще раз или обратитесь в помощь

**Comment by jzakrzewski** [comment]
This message looks like it comes from a 3-party software and not curl itself.
What are you using to get this message?

**Comment by Mayss77** [comment]
Пыталась открыть эту ссылку через яндекс, гугл, пуфин ни чего не выходит. Должна была придти ссылка с фото!

**Comment by bagder** [comment]
The man page explains error 7. What else should it do? (and please use English)
