### ISSUE TITLE
doc: Inconsistent tense in help

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7434]
### I did this

https://github.com/curl/curl/search?q=%22is+provided%22+extension%3Ad
https://github.com/curl/curl/search?q=%22was+provided%22+extension%3Ad

(n.b. one should try other searches and review the rest of the doc corpus, this was a spot check as I was going through the files, specifically this was from `help.d`.)

### I got this
https://github.com/curl/curl/blob/265b14d6b37c4298bd5556fabcbc37d36f911693/docs/cmdline-opts/version.d#L18
https://github.com/curl/curl/blob/265b14d6b37c4298bd5556fabcbc37d36f911693/docs/cmdline-opts/version.d#L76
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/help.d#L7-L11
These two have both:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/key.d#L14-L16
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/cert.d#L30-L32

### I expected the following

Exclusively present tense or past tense (personal preference is for present tense)

**Comment by jay** [comment]
seems fine

**Comment by bagder** [comment]
Insignificant problem that can be fixed when we address other things in these docs in the future.
