### ISSUE TITLE
doc: Warning / WARNING / **WARNING**

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7435]
### I did this

https://github.com/curl/curl/search?q=WARNING+extension%3A.d

### I got this

**WARNING**:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/remote-header-name.d#L18
Note that this case doesn't capitalize the first letter:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/header.d#L39

WARNING:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/hsts.d#L8

... WARNING:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/ssl-allow-beast.d#L9

Warning:
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/url.d#L18

### I expected the following

Consistent use of a single warning style (with toleration for perhaps 2 styles if there is a slight gradient).

**Comment by jay** [comment]
seems fine. some warnings are more important than others
