### ISSUE TITLE
doc: instead be (verb) / be (verb) instead

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7437]
### I did this

https://github.com/curl/curl/search?q=%22instead+be%22+extension%3Ad
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/krb.d#L10
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/get.d#L11

https://github.com/curl/curl/search?q=%22used+instead%22+extension%3Ad
https://github.com/curl/curl/blob/85f54a150d4eb53e3aaf4c5fc94643e719a51296/docs/cmdline-opts/dns-servers.d#L8
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/ftp-skip-pasv-ip.d#L15
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/anyauth.d#L10
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/request.d#L8
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/header.d#L12

### I expected the following

Only one style (preferably: `be (verb) instead`)

**Comment by jay** [comment]
seems fine

**Comment by bagder** [comment]
This is not a bug, the docs seem clear enough here for readers.
