### ISSUE TITLE
doc: limit-rate clarify base unit

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7439]
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/cmdline-opts/limit-rate.d#L12-L13

I presume that this `k` is 2^10, but Wikipedia pretends it means 10^3. (I'm not endorsing this notation, but docs should be clear.)

**Comment by bagder** [comment]
They're all 1024-based. So K is 1024, M is 1024 * 1024 and G is 1024 * 1024 * 1024.

**Comment by jsoref** [comment]
I don't have prose and I'm not sure how many places should mention it, but this seems like a place that should include it. Happy to talk it out online.

**Comment by jsoref** [comment]
https://github.com/curl/curl/blob/265b14d6b37c4298bd5556fabcbc37d36f911693/docs/cmdline-opts/page-header#L164
