### ISSUE TITLE
crash on curl 7.77 when configure a http proxy and timeout

### ISSUE THREAD

**Issue by caizhibo2016** [curl/curl#7443]
crash when http proxy timeout, stack:
#0  0x00007ffff5d02b7c in free () from /lib64/libc.so.6
#1  0x00007ffff7ba25ba in Curl_free_request_state (data=data@entry=0x66f1f0) at ../../lib/url.c:2168
#2  0x00007ffff7b84f58 in multi_done (data=data@entry=0x66f1f0,
    status=status@entry=CURLE_OPERATION_TIMEDOUT, premature=premature@entry=true)
    at ../../lib/multi.c:697
#3  0x00007ffff7b85b4f in multi_runsingle (multi=multi@entry=0x66def0,
    nowp=nowp@entry=0x7fffffffdd30, data=data@entry=0x66f1f0) at ../../lib/multi.c:1743
#4  0x00007ffff7b865a6 in curl_multi_perform (multi=multi@entry=0x66def0,
    running_handles=running_handles@entry=0x7fffffffde38) at ../../lib/multi.c:2520
#5  0x00007ffff7b644bb in easy_transfer (multi=<optimized out>) at ../../lib/easy.c:606
#6  easy_perform (events=false, data=0x66f1f0) at ../../lib/easy.c:696
#7  curl_easy_perform (data=0x66f1f0) at ../../lib/easy.c:715
#8  0x0000000000412616 in serial_transfers (share=0x658890, global=0x7fffffffdfd0)
    at ../../src/tool_operate.c:2395
#9  run_all_transfers (result=<optimized out>, share=0x658890, global=0x7fffffffdfd0)
    at ../../src/tool_operate.c:2569
#10 operate (global=global@entry=0x7fffffffdfd0, argc=argc@entry=24, argv=argv@entry=0x7fffffffe158)
    at ../../src/tool_operate.c:2685
#11 0x000000000040311b in main (argc=24, argv=0x7fffffffe158) at ../../src/tool_main.c:277

### curl/libcurl version
[curl -V output]
curl -V
curl 7.77.0 (x86_64-redhat-linux-gnu) libcurl/7.77.0 OpenSSL/1.0.1e-fips zlib/1.2.7 c-ares/1.15.0 libssh2/1.4.3 OpenLDAP/2.4.44
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets

operating system
centos7.1, Linux 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

My analysis
in multi_done, calls function conn_free to  free the conn and its connect_state, then call Curl_free_request_state to free the http because connect_init function set http point to connect_state's http_proxy, then it causes double free and crash

**Comment by bagder** [comment]
Duplicate of #7236, fixed since #7237
