### ISSUE TITLE
Cannot link with nghttp2_static.lib

### ISSUE THREAD

**Issue by zedalaye** [curl/curl#7446]
Hi,

I'm trying to build libcurl.dll on Windows with Visual Studio 2017 with OpenSSL and nghttp2 as dependencies.

Link fails, telling it's unable to find `nghttp2_static.lib`. I found that build/link works if I change this line, removing the "_static" part.

https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/winbuild/MakefileBuild.vc#L160

Here is how I build NgHttp2 on Windows (`$` means `C:\Users\Me\Projects\externals\build-2021-07-19\`) :

```bash
$ git clone ...
$ cd nghttp2
$ cmake -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_INSTALL_PREFIX=..\deps ^
              -DENABLE_LIB_ONLY=ON ^
              -DENABLE_STATIC_LIB=ON ^
              -DENABLE_SHARED_LIB=OFF ^
              -H. ^
              -Bbuild
$ cmake --build build --config Release --target install
```

I'm not sure if it is due to a change in NgHttp2 or due to my build environment.

**Comment by jay** [comment]
The name was nghttp2_static.lib for a brief period, now the basename suffix is optional so you probably have nghttp2.lib. Please try #7447

**Comment by zedalaye** [comment]
I can confirm it's OK for me. Thank you.
