### ISSUE TITLE
doc: mail-auth odd start

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7450]
https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/mail-auth.d#L9-L10

>  Specify a single address. This will be used to specify the authentication 
 address (identity) of a submitted message that is being relayed to another 

`Specify a single address` seems like a really odd start.

**Comment by jsoref** [comment]
This isn't quite as bad:
https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/mail-from.d#L9

even though it has the same start. But the sentence itself covers what the flag does...

**Comment by jay** [comment]
pass
