### ISSUE TITLE
doc: mail-rcpt is confused about reader for mail transfer

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7452]
### I did this

https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/mail-rcpt.d#L11-L12

### I expected the following

text talking to the curl user

### I got

confusing text that talks as if i'm the recipient which doesn't make sense

compare:
https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/mail-rcpt.d#L14-L16
https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/mail-rcpt.d#L18-L20
which use `should be` instead of `should specify`.

**Comment by jay** [comment]
> confusing text that talks as if i'm the recipient which doesn't make sense

Seems fine to me. What's wrong with saying "the recipient should be specified as xxxx"?

**Comment by jsoref** [comment]
`recipient`  in `the recipient should specify` could be saying "dear recipient please specify how you want to be addressed"

But the text is actually trying to say "dear user, please use `recipient` to specify the ..."

**Comment by jay** [comment]
what? It says recipient should _be_ specified

**Comment by jsoref** [comment]
No, it doesn't. It could be written to say that. The others aren't ambiguous in this manner:
>  When performing a mail transfer, the recipient should specify a valid email 
 address to send the mail to.

**Comment by jay** [comment]
Ok, I see now you are referring to the first one, which says: _"When performing a mail transfer, the recipient should specify a valid email address to send the mail to."_

That sentence seems unnecessary and I don't know why it's phrased like that. See #7495 for proposed fix.

Ref: [--mail-rcpt](https://curl.se/docs/manpage.html#--mail-rcpt)
