### ISSUE TITLE
doc: max-filesize is it limited to http/ftp?

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7453]
### I did this

https://github.com/curl/curl/blob/9a7a60dbd1109d923d064a40b33ae68fcd5642c1/docs/cmdline-opts/max-filesize.d#L17

### I expected the following

> Protocols:

**Comment by jsoref** [comment]
I suspect that max-filesize applies to more than those two protocols, in which case the text should say something like:

> For protocols where the size is not known in advance (including FTP and HTTP) ...

Instead of burying the caveat at the end.

**Comment by jay** [comment]
I've changed the wording and added MQTT to the list of supported protocols in the libcurl options. Thanks

**Comment by jsoref** [comment]
Looks better. Shouldn't you add `protocols: (those 3)` to the top of the `.d` file?

**Comment by jay** [comment]
> Shouldn't you add `protocols: (those 3)` to the top of the `.d` file?

I did that in 9a6f974 which reverted the caveat wording. Since all the max filesize options have a protocol list now it's clearer to warn of unknown file sizes without mentioning specific protocols in that paragraph.
