### ISSUE TITLE
hardcoded -lssh2 dependancy conflicts with --with-libssh2= option

### ISSUE THREAD

**Issue by gitcnd** [curl/curl#746]
### I did this

./configure --enable-static --with-ssl=~/newcurl/openssl-1.0.1s --prefix=~/newcurl --exec-prefix=~/newcurl --with-libssh2=~/newcurl/libssh2-master/

### I expected the following

worked

### I encountered:

configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssh2 -lz -lrt

### operating system

Red Hat

**Comment by bagder** [comment]
> one or more libs available at link-time are not available run-time

That means configure found the libs it needs but when it tested and ran a program using them, it failed. That's not a "hardcoded -lssh2 dependancy"
