### ISSUE TITLE
doc: some proxy-* and have different shape than most proxy-*

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7464]
### I did this

https://github.com/curl/curl/blob/5ea3145850ebff1dc2b13d17440300a01ca38161/docs/cmdline-opts/proxy-digest.d#L6-L7
https://github.com/curl/curl/blob/5ea3145850ebff1dc2b13d17440300a01ca38161/docs/cmdline-opts/proxy-negotiate.d#L7-L9
https://github.com/curl/curl/blob/master/docs/cmdline-opts/proxy-ntlm.d
https://github.com/curl/curl/blob/master/docs/cmdline-opts/proxy-pinnedpubkey.d

### I expected the following

https://github.com/curl/curl/blob/5ea3145850ebff1dc2b13d17440300a01ca38161/docs/cmdline-opts/proxy-ciphers.d#L7

### note that 
https://github.com/curl/curl/blob/master/docs/cmdline-opts/digest.d

exists...

And for this:
https://github.com/curl/curl/blob/5ea3145850ebff1dc2b13d17440300a01ca38161/docs/cmdline-opts/negotiate.d#L12-L14
it explicitly mentions additional requirements not covered in the proxy flavor, which I suspect argues in favor of one-lining the proxy version to avoid the discrepancy.

This has way more content:
https://github.com/curl/curl/blob/5ea3145850ebff1dc2b13d17440300a01ca38161/docs/cmdline-opts/pinnedpubkey.d#L17-L33

---
https://github.com/curl/curl/blob/master/docs/cmdline-opts/proxy-service-name.d#L7
is a bit of an odd duck
https://github.com/curl/curl/blob/master/docs/cmdline-opts/service-name.d#L7-L9

I think the former should have SPNEGO in its text, and probably should have an example line. But I could understand wanting to have a distinct file instead of just "Same as"...

---
https://github.com/curl/curl/blob/master/docs/cmdline-opts/proxy-user.d
is quite a bit shorter than
https://github.com/curl/curl/blob/master/docs/cmdline-opts/user.d

As it has a `-U` / `-u` distinction, I don't think it can be collapsed as such, but I think suggesting people read the other item is probably worthwhile (`See help for --user for more details` ?)

**Comment by bagder** [comment]
This seems like something that could be enhanced but without any inherent *problem* or actual *issue* that requires it to happen.
