### ISSUE TITLE
doc: quote paragraphs are contradictory

### ISSUE THREAD

**Issue by jsoref** [curl/curl#7465]
https://github.com/curl/curl/blob/f6401b26c88433c9e25c886f91ebdee8aa3b8aa6/docs/cmdline-opts/quote.d#L17-L22

Line 17 says that the chain will unconditionally abort. Line 21 says "well, actually,...".

It'd be better if the prose from 21 was incorporated into the paragraph for 17.

**Comment by bagder** [comment]
It could probably be better phrased, but I disagree that this is a bug. I think the functionality is still clear to readers.

**Comment by jsoref** [comment]
Thoughts on:
```diff
-If the server returns failure for one of the commands, the entire operation 
-will be aborted. You must send syntactically correct FTP commands as RFC 959 
-defines to FTP servers, or one of the commands listed below to SFTP servers. 
- 
-Prefix the command with an asterisk (*) to make curl continue even if the 
-command fails as by default curl will stop at first failure. 
+By default curl will stop at first failure. To make curl continue even if the
+command fails, prefix the command with an asterisk (*). Otherwise, if the server
+returns failure for one of the commands, the entire operation will be aborted.
+
+You must send syntactically correct FTP commands as RFC 959 defines to FTP
+servers, or one of the commands listed below to SFTP servers.
```

Note that there are a couple of fairly unrelated changes here:
* The `*` text is moved before the the abort on failure.
* The syntactically correct bit is split to its own paragraph -- because afaict it's totally unrelated.

I'm not sure about the order of the two paragraphs. The reason I've split it after is that I think that the `*` stuff should be closer to the `-` and `+` stuff.
