### ISSUE TITLE
All string after symbol '&' in URL are ignored

### ISSUE THREAD

**Issue by NechukhrinN** [curl/curl#7469]
### I did this
curl -v -X GET http://localhost:9124/some_service/logic/test&test3=0

### I expected the following
> Trying 127.0.0.1:9124...
> Connected to localhost (127.0.0.1) port 9124 (#0)
> GET /some_service/logic/test&test3=0 HTTP/1.1
> Host: localhost:9124
> User-Agent: curl/7.76.1
> Accept: */*

### I got this
>  Trying 127.0.0.1:9124...
> Connected to localhost (127.0.0.1) port 9124 (#0)
> GET /some_service/logic/test HTTP/1.1
> Host: localhost:9124
> User-Agent: curl/7.76.1
> Accept: */*

### curl version
curl 7.76.1

### OS

Ubuntu 20.04.2 LTS

**Comment by bagder** [comment]
That's because your shell does that for you. Quote the string, double or single quotes, and it'll work.

**Comment by NechukhrinN** [comment]
Thanks for help!
