### ISSUE TITLE
7.78.0 breaks static linking

### ISSUE THREAD

**Issue by moparisthebest** [curl/curl#7475]
[static-curl](https://github.com/moparisthebest/static-curl) started spitting out dynamically linked instead of static executables starting with 7.78.0, the script has not changed, and I verified 7.77.0 in the same alpine container produces a static executable as expected.  I ran a git bisect using bisect.sh which is pasted at the end of this issue, with instructions, which pointed to 265b14d6b37c4298bd5556fabcbc37d36f911693 as the first bad commit.  I further determined that `git checkout 9cf516adc67b67388e22bb8c33cb3fabd68f2ac6 -- configure.ac 'src/Makefile.am'` makes static linking work at both master and 265b14d6b37c4298bd5556fabcbc37d36f911693 , I believe the exact culprit is [this change to src/Makefile.am](https://github.com/curl/curl/commit/265b14d6b37c4298bd5556fabcbc37d36f911693#diff-4cb884d03ebb901069e4ee5de5d02538c40dd9b39919c615d8eaa9d364bbbd77L69) but I'm not versed enough in autotools to figure out exactly why.

bisect.sh:
```sh
#!/bin/sh

# run these in order, in a directory with this script:
# docker run --rm -v $(pwd):/tmp -w /tmp -it alpine sh
# apk add git autoconf automake libtool build-base clang
# git clone https://github.com/curl/curl
# cd curl
# git bisect start curl-7_78_0 curl-7_77_0 --
# git bisect run /tmp/bisect.sh
# last good: 9cf516adc67b67388e22bb8c33cb3fabd68f2ac6
# first bad: 265b14d6b37c4298bd5556fabcbc37d36f911693

set -exu

export CC=clang

git clean -dxf
autoreconf -fi

# set up any required curl options here
LDFLAGS="-static" PKG_CONFIG="pkg-config --static" ./configure --disable-shared --enable-static --disable-libcurl-option --without-brotli --disable-manual --disable-unix-sockets --disable-dict --disable-file --disable-gopher --disable-imap --disable-smtp --disable-rtsp --disable-telnet --disable-tftp --disable-pop3 --without-zlib --disable-threaded-resolver --disable-ipv6 --disable-smb --disable-ntlm-wb --disable-tls-srp --disable-crypto-auth --without-ngtcp2 --without-nghttp2 --disable-ftp --disable-mqtt --disable-alt-svc --disable-largefile  --without-ssl

make -j4 V=1 curl_LDFLAGS=-all-static

strip src/curl

ls -lah src/curl
file src/curl

./src/curl -V

set +e

ldd src/curl && exit 1 || exit 0
```

**Comment by piru** [comment]
The said commit removed `curl_LDFLAGS` and thus using in in the `make` command line doesn't do anything at all. This makes it build a static version for me:

> make -j4 V=1 LDFLAGS="-static -all-static"

I have no idea is this is the preferred way to do this however.

**Comment by bagder** [comment]
Yeps, `curl_LDFLAGS` served no purpose anymore when metalink was removed. @piru's way would then be the new approach I'd think.

**Comment by jay** [comment]
It served a purpose in that it let you set the ld flags for just the curl tool and not libcurl. I know I've used curl_LDFLAGS in some scripts, though I don't remember why I used it instead of LDFLAGS.

**Comment by jay** [comment]
> though I don't remember why I used it instead of LDFLAGS.

libtool can strip from LDFLAGS but not curl_LDFLAGS, see [here](https://github.com/curl/curl/issues/503#issuecomment-150680789)

**Comment by bagder** [comment]
Since it works with `LDFLAGS` instead of `curl_LDFLAGS` I consider this case closed.

**Comment by jay** [comment]
> Since it works with `LDFLAGS` instead of `curl_LDFLAGS` I consider this case closed.

It may for @piru but not in mingw. In the comment I linked to you can see LDFLAGS is passed to configure conftest and mingw gcc doesn't recognize -all-static so tests fail, but for curl_LDFLAGS that is only used to build curl. It was several years ago and I don't remember a lot about it. I'd like to hear from @moparisthebest

**Comment by moparisthebest** [comment]
Indeed it fixes *my* problem using `LDFLAGS` instead of `curl_LDFLAGS`, I appreciate it!

**Comment by s1shed** [comment]
> > Since it works with `LDFLAGS` instead of `curl_LDFLAGS` I consider this case closed.
> 
> It may for @piru but not in mingw. In the comment I linked to you can see LDFLAGS is passed to configure conftest and mingw gcc doesn't recognize -all-static so tests fail, but for curl_LDFLAGS that is only used to build curl. It was several years ago and I don't remember a lot about it. I'd like to hear from @moparisthebest

I was bitten by this since I was also using `curl_LDFLAGS`. 

If I set `LDFLAGS=-all-static` at the same time as running `configure` it fails with 

```
checking for a BSD-compatible install... /usr/bin/install -c
checking for x86_64-linux-gcc... x86_64-linux-musl-gcc
checking whether the C compiler works... no
configure: error: in `/build/curl-7.78.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

In config.log:

```
configure:4365: x86_64-linux-musl-gcc  -I/build/openssl-1.1.1k/include         -I/build/zlib-1.2.11         -I/build/openldap-2.5.5/include         -I/build/libssh2-1.9.0         -I/build/zstd-1.5.0/lib         -I/build/brotli-1.0.9/c/include/ -L/build/openssl-1.1.1k           -L/build/zlib-1.2.11           -L/build/openldap-2.5.5/libraries/libldap/.libs           -L/build/openldap-2.5.5/libraries/libutil/.libs           -L/build/openldap-2.5.5/libraries/liblber/.libs           -L/build/zstd-1.5.0/lib           -L/build/libssh2-1.9.0/src/.libs           -L/build/brotli-1.0.9/ -static -all-static conftest.c -lbrotli -lzstd >&5
x86_64-linux-musl-gcc: error: unrecognized command line option '-all-static'
``` 

I worked around it with `make LDFLAGS="$LDFLAGS -all-static"`, specifying `LDFLAGS` along with `configure` as well.
