### ISSUE TITLE
Race condition in c-hyper.c, Curl_http()

### ISSUE THREAD

**Issue by divergentdave** [curl/curl#7486]
### I did this
I'm working on a patch for how curl passes URLs to hyper, (https://github.com/divergentdave/curl/tree/hyper-http2-scheme-and-authority) but I've been running into unrelated issues while testing it. When I run my newly-defined test 1704, it works fine without Valgrind, but spins its progress bar forever with Valgrind.

I think I have diagnosed the cause of the issue as being the last `hyper_executor_poll` call in `c-hyper.c:Curl_http`. This call is in a loop that will poll the executor until there are no longer any ready tasks. It checks if each ready task is an error, and propagates the error if so. The issue is that, at this point, the task from `hyper_clientconn_send` was just pushed onto the executor. If the remote server can respond faster than this loop can poll tasks/futures, the task for the response future may finish, be returned from hyper_executor_poll, and drop on the floor. Then, when `Curl_hyper_stream` is called, the call to `hyper_executor_poll` there can never return a response. (since it has already done so).

Presumably the overhead due to Valgrind, combined with the speed of the test server running on localhost, are why this race condition can be triggered reliably in the test suite. I added some logging around these `hyper_executor_poll` calls, and here's what I found:

* No Valgrind
  * A HYPER_TASK_EMPTY task is returned once in `Curl_http`.
  * Tasks of type HYPER_TASK_EMPTY, HYPER_TASK_RESPONSE, and HYPER_TASK_EMPTY are returned `Curl_hyper_stream`.
* With Valgrind
  * Tasks of type HYPER_TASK_EMPTY, HYPER_TASK_EMPTY, HYPER_TASK_RESPONSE, and HYPER_TASK_EMPTY are returned in `Curl_http`.
  * No tasks are returned in `Curl_hyper_stream`.

To fix this issue, I think we should add another field to `struct hyptransfer` to store the response task or its value, as a way to pass it from `Curl_http` to `Curl_hyper_stream`, in case the response is returned early during this error-checking loop.

The underlying issue is that the three call sites of `hyper_executor_poll` are effectively acting as an event loop, but they are each handled slightly differently. Moreover, the earlier call in `Curl_http`, for the handshake, makes implicit assumptions that (a) it will be ready on the first call, (b) it won't output an error (c) there are no internally-generated tasks with output type EMPTY that would be returned first. As a larger redesign, it might make sense to annotate each submitted task using `hyper_task_set_userdata`, and write one common method to handle polling the executor, checking the user data, and storing the clientconn, response, or related error for subsequent use.

### curl/libcurl version
See branch mentioned above.

```
curl 7.78.0-DEV (x86_64-pc-linux-gnu) libcurl/7.78.0-DEV crustls/0.6.1/rustls/0.19.0 zlib/1.2.11 zstd/1.3.8 libidn2/2.0.5 nghttp2/1.36.0 Hyper/0.14.9 libgsasl/1.8.0 OpenLDAP/2.4.47
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s smtp smtps telnet tftp 
Features: alt-svc AsynchDNS Debug gsasl GSS-API HSTS HTTP2 IDN Kerberos Largefile libz SPNEGO SSL TrackMemory UnixSockets zstd
```

### operating system
Linux desktop 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

**Comment by bagder** [comment]
Lovely catch. I started out by ripping out the executor_poll loop from `Curl_http` because it doesn't seem to be necessary there at all. See: #7499

**Comment by bagder** [comment]
If this is still a problem, please provide a recipe on how to reproduce it.
