### ISSUE TITLE
progressfunc.c exampleОшибка на 185 строке: cURL error 7: Failed to connect to exchapi port 1337: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) Попробуйте еще раз или обратитесь в помощь откройте эту ссылку

### ISSUE THREAD

**Issue by Mayss77** [curl/curl#7487]

**Comment by dfandrich** [comment]
It's not curl's fault if you're getting a "Failed to connect" error, assuming
the host and port are correct. Try a host and port that are open.

**Comment by bagder** [comment]
And please submit issues in English. It's way better if you do the translation once instead of dozens of us having to redo it each and every one.
