### ISSUE TITLE
Cannot build 7.78.0 with wolfssl (msys2+MinGW) openssl/*.h not found

### ISSUE THREAD

**Issue by resokou** [curl/curl#7488]
I'm trying to build **libcurl 7.78** with static *zlib-1.2.11* and *wolfssl-4.8.1-stable* on Windows+msys2 with MinGW. Everything works fine, including the configure process:
```
  curl version:     7.78.0-DEV
  SSL:              enabled (WolfSSL)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
...
  Protocols:        FILE FTP FTPS HTTP HTTPS
  Features:         AsynchDNS HSTS IPv6 Largefile NTLM SSL alt-svc libz
```
except when I start the build process with *make* and it tries to find the headers in the *openssl* directory:
```
curl_ntlm_core.c:58:12: fatal error: openssl/des.h: No such file or directory
   58 | #  include <openssl/des.h>
      |            ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:2124: libcurl_la-curl_ntlm_core.lo] Error 1
make[2]: Leaving directory '/home/curl-curl-7_78_0/lib'
make[1]: *** [Makefile:1359: all] Error 2
make[1]: Leaving directory '/home/curl-curl-7_78_0/lib'
make: *** [Makefile:1262: all-recursive] Error 1
```
wolfssl was compiled with `--enable-opensslextra` and it has the openssl headers in `/home/build/include/wolfssl/openssl`:
```
$ sh autogen.sh
$ CFLAGS="-fPIC -O2" LDFLAGS="-lws2_32" ./configure --prefix=/home/build --enable-static --disable-shared --enable-opensslextra
$ make
$ make install
```

libcurl:
```
$ autoreconf -i
$ automake
$ autoconf
$ CFLAGS="-fPIC" CPPFLAGS="-DCURL_STATICLIB" ./configure --prefix=/home/build --disable-shared --enable-static --with-wolfssl=/home/build --with-zlib=/home/build --enable-file --enable-ipv6 --enable-cookies --enable-ftp --disable-ares --disable-ldap --disable-ldaps --disable-rts --disable-rtsp --disable-dict -disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-sspi --disable-manual --disable-debug --without-libidn2 --disable-mqtt
$ make
... <ERROR>
```
I haven't tried a different version of wolfssl as I suspected it's a problem with libcurl building process. Correct me if I'm wrong.

**Comment by bagder** [comment]
That openssl include directory should exist in your `$wolfssl/include/wolfssl` directory, where `$wolfssl` is the prefix where you installed it.

**Comment by resokou** [comment]
Thanks for your reply.

my **{prefix}** path is `/home/build` and has:

```
/ bin
/ include
    / cyassl
    / nghttp2
    / wolfssl
        / openssl
          ...
          des.h <-- (make error)
          ...
        / wolfcrypt
          callbacks.h
          ...
          wolfio.h
        zconf.h
        zlib.h
/ lib
/ share
```
I used `/` to denote folders.


My configure summary, again is:
```
  Host setup:       x86_64-pc-msys
  Install prefix:   /home/build
  Compiler:         gcc
   CFLAGS:          -fPIC -Werror-implicit-function-declaration -O2 -Wno-system-headers
   CPPFLAGS:        -DCURL_STATICLIB -isystem /home/build/include -isystem /home/build/include
   LDFLAGS:         -L/home/build/lib -L/home/build/lib
   LIBS:            -ladvapi32 -lcrypt32 -lwolfssl -lm -lz -lws2_32

  curl version:     7.78.0-DEV
  SSL:              enabled (WolfSSL)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
...
  Protocols:        FILE FTP FTPS HTTP HTTPS
  Features:         AsynchDNS HSTS IPv6 Largefile NTLM SSL alt-svc libz
```
and make `V=1`:
```
Making all in lib
make[1]: Entering directory '/home/curl-curl-7_78_0/lib'
make  all-am
make[2]: Entering directory '/home/curl-curl-7_78_0/lib'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I../include -I../lib -I../lib  -DBUILDING_LIBCURL -DCURL_STATICLIB  -DCURL_STATICLIB -isystem /home/build/include -isystem /home/build/include   -fPIC -Werror-implicit-function-declaration -O2 -Wno-system-headers  -MT libcurl_la-curl_ntlm_core.lo -MD -MP -MF .deps/libcurl_la-curl_ntlm_core.Tpo -c -o libcurl_la-curl_ntlm_core.lo `test -f 'curl_ntlm_core.c' || echo './'`curl_ntlm_core.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_STATICLIB -DCURL_STATICLIB -isystem /home/build/include -isystem /home/build/include -fPIC -Werror-implicit-function-declaration -O2 -Wno-system-headers -MT libcurl_la-curl_ntlm_core.lo -MD -MP -MF .deps/libcurl_la-curl_ntlm_core.Tpo -c curl_ntlm_core.c -o libcurl_la-curl_ntlm_core.o
curl_ntlm_core.c:58:12: fatal error: openssl/des.h: No such file or directory
   58 | #  include <openssl/des.h>
      |            ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:2124: libcurl_la-curl_ntlm_core.lo] Error 1
make[2]: Leaving directory '/home/curl-curl-7_78_0/lib'
make[1]: *** [Makefile:1359: all] Error 2
make[1]: Leaving directory '/home/curl-curl-7_78_0/lib'
make: *** [Makefile:1262: all-recursive] Error 1
```

**Comment by bagder** [comment]
Then the configure script fails in this section which is the one that should add the 'wolfssl' subdirectory:

https://github.com/curl/curl/blob/83245d9ff352b742753cff1216781ff041e4e987/m4/curl-wolfssl.m4#L133-L154

**Comment by bagder** [comment]
Output from my configure when building with wolfssl 4.8.1 from a custom prefix. Bolding the openssl include line:

checking for wolfssl options with pkg-config... no
configure: Check dir yes/lib/pkgconfig
configure: Add -L/home/daniel/build-wolfssl/lib to LDFLAGS
configure: Add -I/home/daniel/build-wolfssl/include to CPPFLAGS
configure: Add -lwolfssl to LIBS
checking for wolfSSL_Init in -lwolfssl... yes
configure: detected wolfSSL
checking size of long long... 8
checking for wolfSSL_get_peer_certificate... yes
checking for wolfSSL_UseALPN... yes
checking for wolfSSL_DES_ecb_encrypt... yes
**configure: Add -I/home/daniel/build-wolfssl/include/wolfssl to CPPFLAGS**
configure: Added /home/daniel/build-wolfssl/lib to CURL_LIBRARY_PATH

**Comment by resokou** [comment]
Thanks for the input, it seems some checks fail in my configure:

checking for pkg-config... no
configure: Check dir /home/pycurl/lib/pkgconfig
configure: Add -L/home/pycurl/lib to LDFLAGS
configure: Add -I/home/pycurl/include to CPPFLAGS
configure: Add -lwolfssl to LIBS
checking for wolfSSL_Init in -lwolfssl... yes
configure: detected wolfSSL
checking size of long long... 8
checking for wolfSSL_get_peer_certificate... yes
**checking for wolfSSL_UseALPN... no**
**checking for wolfSSL_DES_ecb_encrypt... no**
configure: Added /home/pycurl/lib to CURL_LIBRARY_PATH
configure: built with one SSL backend

Is there any specific option I need to enable when building wolfssl?

**Comment by resokou** [comment]
Using `<flags> ./configure <options> --enable-alpn` works to make curl's **wolfSSL_UseALPN** check pass. 

However I cannot get **wolfSSL_DES_ecb_encrypt** to pass. I tried adding `--enable-des3` too but it doesn't get detected.

https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/openssl/des.h#L85

**Comment by bagder** [comment]
I tried:

    CFLAGS="-DWOLFSSL_DES_ECB" ./configure --prefix=/home/daniel/build-wolfssl --enable-opensslextra --enable-alpn

but it didn't work. I know `--enable-all` works, but then of course you get a rather maximized wolfssl...

**Comment by resokou** [comment]
Thanks! I got it to work with both `--enable-des3` and `-DWOLFSSL_DES_ECB`. The former seems to enable some basic DES functionality, while the latter enables DES ECB specifically, needed for curl configure check to pass and add the -I flags.

Hence, __using__ `-DWOLFSSL_DES_ECB` __only is useless, as it's inside another #ifdef enabled only by__ `--enable-des3` (the logic is actually reversed because it's a #ifndef but it's the same principle).

To recap my full configure command now is:
```
CFLAGS="-fPIC -O2 -DWOLFSSL_DES_ECB" LDFLAGS="-lws2_32" ./configure --prefix=/home/build --enable-static --disable-shared --enable-opensslextra --enable-alpn --enable-des3
```
which resutls in the wolfssl configure summary:
```
   * C++ Compiler:
   * C++ Flags:
   * CPP Flags:
   * CCAS Flags:                 -fPIC -O2 -DWOLFSSL_DES_ECB
   * LIB Flags:                   -pie
   * Debug enabled:              no
   * Coverage enabled:
   * Warnings as failure:        no
   * make -j:                    9
   * VCS checkout:               no

   Features
...
   * DES3:                       yes
...
   * ALPN:                       yes
```
And finally curl configure showing:

checking for pkg-config... no
configure: Check dir /home/build/lib/pkgconfig
configure: Add -L/home/build/lib to LDFLAGS
configure: Add -I/home/build/include to CPPFLAGS
configure: Add -lwolfssl to LIBS
checking for wolfSSL_Init in -lwolfssl... yes
configure: detected wolfSSL
checking size of long long... 8
**checking for wolfSSL_get_peer_certificate... yes**
**checking for wolfSSL_UseALPN... yes**
**checking for wolfSSL_DES_ecb_encrypt... yes**
**configure: Add -I/home/build/include/wolfssl to CPPFLAGS**
configure: Added /home/build/lib to CURL_LIBRARY_PATH
configure: built with one SSL backend

which leads to a successful build.

From what I understand DES ECB is used by NTLM in curl, though I don't understand why not halt the configure process altogether if that function check fails or even why not print a warning or something to alert the user something is not right.

**Comment by bagder** [comment]
> why not halt the configure process altogether if that function check fails or even why not print a warning or something to alert the user something is not right

1. Feel free to improve
2. It didn't cause a build error for me, I just got a build without NTLM
