### ISSUE TITLE
#include <sys/select.h> needed in CYGWIN

### ISSUE THREAD

**Issue by altpapier** [curl/curl#749]
### I did this
tried to compile a target (pianobar) on CYGWIN, that includes curl.h

### I expected the following
successful compile, but this was only possible when including '#include \<sys/select.h\>' manually.
without this I got the error: 
    In file included from /usr/include/curl/curl.h:2400:0,
    from src/libpiano/request.c:26:
    /usr/include/curl/multi.h:151:40: error: unknown type name 'fd_set' fd_set *read_fd_set, ...

So it looks like CYGWIN could be added to the defines of the following block to solve this

    /* HP-UX systems version 9, 10 and 11 lack sys/select.h and so does oldish
    libc5-based Linux systems. Only include it on systems that are known to
    require it! */ 
    #if defined(_AIX) || defined(__NOVELL_LIBC__) || defined(__NetBSD__) || \
      defined(__minix) || defined(__SYMBIAN32__) || defined(__INTEGRITY) || \
      defined(ANDROID) || defined(__ANDROID__) || defined(__OpenBSD__) || \
     (defined(__FreeBSD_version) && (__FreeBSD_version < 800000))
     #include <sys/select.h>
     #endif

### curl/libcurl version
7.48 0-1

### operating system
Windows XP / 7 with CYGWIN 32 Bit (64 bit I have not tested yet)

**Comment by bagder** [comment]
That puzzles me. AFAIK, people have built curl and libcurl for cygwin since over a decade and that #ifdef logic has been there for a very very long time. Did all the other users modify their source like that without pointing this out to us or has something changed in cygwin land recently?

**Comment by altpapier** [comment]
thank you for the response !
... it might be a problem on my side as well (bad compiler configuration ?). I'll try doing more checks and get back then.

**Comment by altpapier** [comment]
I see the effect on the following 64 bit versions of Cygwin as well:
Cygwin 64 bit / 2.2.1 (2015/08/20) / Windows 10
Cygwin 64 bit / 2.4.1 (2016/01/24) / Windows 10

**Comment by bagder** [comment]
It seems to also be an acknowledged bug in cygwin, see this [sys/select.h commit log](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git&a=search&h=HEAD&st=commit&s=sys%2Fselect.h) and specially this [commit from March 18th](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=ee97c4b22491b205fd3b7697e03c909e02b652d3) that brings back the inclusion of sys/select.h from within sys/types.h.

**Comment by bagder** [comment]
So, as cygwin has backpeddled on this, @altpapier do you still think we should do anything here?

**Comment by altpapier** [comment]
Hi @bagder, 
that is a good question, in my opinion if the header select.h is used by curl.h, adding __CYGWIN__ to the header is not an error I think. On the other hand as you said it has worked as it is now for more than a decade, and will work again with future Cygwin versions (but could break again in the future).
Can adding it to curl.h have negative side effects / risks as well ? In that case I would rather leave it as it is.
At least for my use case of this issue, I will no longer need a change if Cygwin does that roll-back.

**Comment by bagder** [comment]
I think I prefer to not rock the boat unless necessary so I'm going to leave things as they are, since this has already been acknowledge to be a cygwin problem and the change has been reverted in their end.

The risk of doing this change in the libcurl header *anyway* is small, and if we end up here again within the next decade that's what we'll do.

Thanks for the report and working with us on this!

**Comment by altpapier** [comment]
that's ok for me, thank you for looking into this!
