### ISSUE TITLE
Download speed extremely slow compared to chrome

### ISSUE THREAD

**Issue by peterwilson136** [curl/curl#7493]
I am trying to download a small csv file, ~150kb. Running the link on google chrome downloads the file instantaneously, however in C++, downloading the file takes 2-3 seconds every time. The link for the file is https://asx.api.markitdigital.com/asx-research/1.0/companies/directory/file?access_token=83ff96335c2d45a094df02a206a39ff4 and here is my code.
```
std::chrono::steady_clock::time_point start, finish;
start = std::chrono::steady_clock::now();
curl_easy_setopt(m_MyHandle, CURLOPT_URL, "https://asx.api.markitdigital.com/asx-research/1.0/companies/directory/file?access_token=83ff96335c2d45a094df02a206a39ff4");

std::string dataBuff;
curl_easy_setopt(m_MyHandle, CURLOPT_WRITEDATA, &dataBuff);
m_Result = curl_easy_perform(m_MyHandle);
finish = std::chrono::steady_clock::now();

long double t = std::chrono::duration_cast<std::chrono::nanoseconds>(finish - start).count();
t /= 1000000000.0;
std::cout << "Time taken to load data " << t << std::endl;
```
My download speed is near 1gbps so it doesn't make sense to me that it takes that long for such a small file.

**Comment by dfandrich** [comment]
It's likely that Chrome caches the file so it doesn't have to download
anything. It could also be that it's using a TLS session cache or already has
an open TCP connection.  Try logging the equivalent of the various --write-out
time_* timers to try to get a sense of where the time is being taken.

Try asking on the curl-users mailing list.  That's a better forum for help than
Github bugs.

**Comment by peterwilson136** [comment]
Thank you for the reply.
I am pretty new to this, would you be able to give me an example of how to use the various --write-out time_* timers?
Also, sure, i'll try and ask on there.

**Comment by bagder** [comment]
For me, at ~130 ms ping time from that server, the download seems to take a little over one second on repeated tries with the curl command line tool (and I too have a gigabit connection to the world). Using `--trace-time` to get time stamped output it seems that the server simply isn't sending the response very fast. I think @dfandrich's theory about it being cached by Chrome is a likely explanation.

**Comment by bagder** [comment]
How do you measure the download time chrome uses to download this?

**Comment by peterwilson136** [comment]
It's not the most scientific (or fair - against chrome), however I have tested it on chrome, edge and explorer. From the second I hit enter on the top search bar to the time it takes to open the actual csv in excel, I just time it on a stopwatch. Its surprising that it takes less time to do all that than it does to just download the file into a string in C++. Also, i've restarted my computer and tried the same upon startup - if that does anything to chrome caching it, and for that matter, internet explorer and microsoft edge too, they take pretty much the same time.

Also, I did try this repeatedly and it too does take a little over 1 second. Only thing is, however, the first initial download takes over 2 seconds and then comes down which seems a little odd to me.

**Comment by bagder** [comment]
The browsers ask for a compressed response and `--compressed` seems to decrease the time somewhat.

When you have written the URL in the bar, the browser has probably already resolved the host name and even connected to the host which makes it a terrible comparison. You need to start the timer before you enter the first byte in the URL bar the first time (with a clean browser cache). With such a manual and error-prone process, I

Even so. I can't spot any obvious mistakes or big time gaps in the server response curl gets when I try that URL. If you want dig deeper on this, then try to identify exactly what in the transfers that takes longer when curl does it than when chrome does it.

**Comment by peterwilson136** [comment]
Ok, I think you were both correct, because it seems that all those browsers sped the download up by caching. Upon deleting it for all of them, it takes roughly the same time. Surprisingly, internet explorer takes the shortest time ~even slower than CURL. Anyway it is roughly about 1 - 2 seconds for each of them, and 1 second for internet explorer. This time aligns with the _average_ for the program, but not for the initial. That is still bothering me, but it looks like the caching was the real reason for the "instantaneous" download.
