### ISSUE TITLE
cacert.pem is incomplete for digicert SHA2 certificates!!!

### ISSUE THREAD

**Issue by PayCheckout** [curl/curl#751]
### I did this

You will hit error : "Peer's Certificate issuer is not recognized."

### curl/libcurl version
any version...

### operating system
linux

Resolve by adding the missing intermediate certificates!

DigiCertSHA2ExtendedValidationServerCA
======================================
-----BEGIN CERTIFICATE-----
MIIEtjCCA56gAwIBAgIQDHmpRLCMEZUgkmFf4msdgzANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTEzMTAyMjEyMDAwMFoXDTI4MTAyMjEyMDAwMFowdTEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTE0MDIGA1UEAxMrRGlnaUNlcnQgU0hBMiBFeHRlbmRlZCBW
YWxpZGF0aW9uIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBANdTpARR+JmmFkhLZyeqk0nQOe0MsLAAh/FnKIaFjI5j2ryxQDji0/XspQUY
uD0+xZkXMuwYjPrxDKZkIYXLBxA0sFKIKx9om9KxjxKws9LniB8f7zh3VFNfgHk/
LhqqqB5LKw2rt2O5Nbd9FLxZS99RStKh4gzikIKHaq7q12TWmFXo/a8aUGxUvBHy
/Urynbt/DvTVvo4WiRJV2MBxNO723C3sxIclho3YIeSwTQyJ3DkmF93215SF2AQh
cJ1vb/9cuhnhRctWVyh+HA1BV6q3uCe7seT6Ku8hI3UarS2bhjWMnHe1c63YlC3k
8wyd7sFOYn4XwHGeLN7x+RAoGTMCAwEAAaOCAUkwggFFMBIGA1UdEwEB/wQIMAYB
Af8CAQAwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
BQcDAjA0BggrBgEFBQcBAQQoMCYwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
Z2ljZXJ0LmNvbTBLBgNVHR8ERDBCMECgPqA8hjpodHRwOi8vY3JsNC5kaWdpY2Vy
dC5jb20vRGlnaUNlcnRIaWdoQXNzdXJhbmNlRVZSb290Q0EuY3JsMD0GA1UdIAQ2
MDQwMgYEVR0gADAqMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5j
b20vQ1BTMB0GA1UdDgQWBBQ901Cl1qCt7vNKYApl0yHU+PjWDzAfBgNVHSMEGDAW
gBSxPsNpA/i/RwHUmCYaCALvY2QrwzANBgkqhkiG9w0BAQsFAAOCAQEAnbbQkIbh
hgLtxaDwNBx0wY12zIYKqPBKikLWP8ipTa18CK3mtlC4ohpNiAexKSHc59rGPCHg
4xFJcKx6HQGkyhE6V6t9VypAdP3THYUYUN9XR3WhfVUgLkc3UHKMf4Ib0mKPLQNa
2sPIoc4sUqIAY+tzunHISScjl2SFnjgOrWNoPLpSgVh5oywM395t6zHyuqB8bPEs
1OG9d4Q3A84ytciagRpKkk47RpqF/oOi+Z6Mo8wNXrM9zwR4jxQUezKcxwCmXMS1
oVWNWlZopCJwqjyBcdmdqEU79OX2olHdx3ti6G8MdOu42vi/hw15UJGQmxg7kVkn
8TUoE6smftX3eg==
-----END CERTIFICATE-----

DigiCert SHA2 Secure Server CA
==============================
-----BEGIN CERTIFICATE-----
MIIElDCCA3ygAwIBAgIQAf2j627KdciIQ4tyS8+8kTANBgkqhkiG9w0BAQsFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0xMzAzMDgxMjAwMDBaFw0yMzAzMDgxMjAwMDBaME0xCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJzAlBgNVBAMTHkRpZ2lDZXJ0IFNIQTIg
U2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
ANyuWJBNwcQwFZA1W248ghX1LFy949v/cUP6ZCWA1O4Yok3wZtAKc24RmDYXZK83
nf36QYSvx6+M/hpzTc8zl5CilodTgyu5pnVILR1WN3vaMTIa16yrBvSqXUu3R0bd
KpPDkC55gIDvEwRqFDu1m5K+wgdlTvza/P96rtxcflUxDOg5B6TXvi/TC2rSsd9f
/ld0Uzs1gN2ujkSYs58O09rg1/RrKatEp0tYhG2SS4HD2nOLEpdIkARFdRrdNzGX
kujNVA075ME/OV4uuPNcfhCOhkEAjUVmR7ChZc6gqikJTvOX6+guqw9ypzAO+sf0
/RR3w6RbKFfCs/mC/bdFWJsCAwEAAaOCAVowggFWMBIGA1UdEwEB/wQIMAYBAf8C
AQAwDgYDVR0PAQH/BAQDAgGGMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYY
aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6
Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwN6A1
oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RD
QS5jcmwwPQYDVR0gBDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8v
d3d3LmRpZ2ljZXJ0LmNvbS9DUFMwHQYDVR0OBBYEFA+AYRyCMWHVLyjnjUY4tCzh
xtniMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA0GCSqGSIb3DQEB
CwUAA4IBAQAjPt9L0jFCpbZ+QlwaRMxp0Wi0XUvgBCFsS+JtzLHgl4+mUwnNqipl
5TlPHoOlblyYoiQm5vuh7ZPHLgLGTUq/sELfeNqzqPlt/yGFUzZgTHbO7Djc1lGA
8MXW5dRNJ2Srm8c+cftIl7gzbckTB+6WohsYFfZcTEDts8Ls/3HB40f/1LkAtDdC
2iDJ6m6K7hQGrn2iWZiIqBtvLfTyyRRfJs8sjX7tN8Cp1Tm5gr8ZDOo0rwAhaPit
c+LJMto4JQtV05od8GiG7S5BNO98pVAdvzr508EIDObtHopYJeS4d60tbvVS3bR0
j6tJLp07kzQoH3jOlOrHvdPJbRzeXDLz
-----END CERTIFICATE-----

**Comment by bagder** [comment]
Sorry, but this project doesn't host *any* certificates or PEM files (outside of the test directory) so you should rather direct this effort to those that do.

**Comment by PayCheckout** [comment]
But a lot of people download the cacert.pem file from http://curl.haxx.se/ca/cacert.pem to be used in cURL and that file is missing above certificates. Beside posting a bug I didn't know where to ask to update that file!

**Comment by bagder** [comment]
That file is already up-to-date. It gets updated daily to the latest version hosted by Mozilla (as used by Firefox). If there's a cert missing in that bundle, it is most likely because it has been removed by Mozilla - or there's a bug in the conversion script.

**Comment by PayCheckout** [comment]
I wanted to have these added as a convenience to fellow developers, because it took us quit sometime time to figure out these two where missing.
Mozilla should add these two certificates because all new SHA2 digicert certifcates use them… Any idea where I should request for this at Mozilla?

Met vriendelijke groeten/With kind regards,

MARTIEN POELS ▷ CTO/FOUNDER

Noorderhof 24, 5804 BV VENRAY The Netherlands ▷ T +31 (0)478 51 76 70 ▷ www.paycheckout.com

This message including any attachments is intended exlusively to the addressee(s) , and may not be passed on to,or made available
for use by any person other than the addressee(s). PayCheckout BV rules out any and every liability resulting from any electronic transmission

**Comment by bagder** [comment]
I think you should contact digitcert about that because I think you need them to ask for inclusion. The Mozilla policy and guidelines for this is at: https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/

**Comment by PayCheckout** [comment]
Ok, thanks.

Met vriendelijke groeten/With kind regards,

MARTIEN POELS ▷ CTO/FOUNDER

Noorderhof 24, 5804 BV VENRAY The Netherlands ▷ T +31 (0)478 51 76 70 ▷ www.paycheckout.com

This message including any attachments is intended exlusively to the addressee(s) , and may not be passed on to,or made available
for use by any person other than the addressee(s). PayCheckout BV rules out any and every liability resulting from any electronic transmission

**Comment by jay** [comment]
The two certificates you posted are [Digicert intermediate authorities](https://www.digicert.com/digicert-root-certificates.htm#intermediates) not root. Your server should be sending the intermediate certificates. Try the SSL certificate checker https://www.digicert.com/help/

**Comment by PayCheckout** [comment]
I Checked, no problems reported. However cURL without the cacert.pem file expanded with the intermediate certificates would not connect.

[cid:image001.png@01D19048.6E47CF60]

Strange enough when I added the intermediate authorities, curl started to connect, without them added I could not connect to the server?

With kind regards,


Martien Poels

**Comment by jay** [comment]
Give us the information then like what server and what curl version (curl -V).

**Comment by PayCheckout** [comment]
Hi Jay,

When I’m at the office tomorrow I will get this information for you.

Regards,

Martien

**Comment by PayCheckout** [comment]
Hallo Jay,

This is what I have for you:

[admin@vps ~]$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[admin@vps ~]$ curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.15.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz



Met vriendelijke groeten / with kind regards,

[PayCheckout B.V.]<https://www.paycheckout.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>

Martien Poels | CTO / Founder
m.poels@paycheckout.com<mailto:m.poels@paycheckout.com>
PayCheckout B.V. | www.paycheckout.com<https://www.paycheckout.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>
Noorderhof 24, 5804 BV Venray
T: +31 (0)478 51 76 70
[Twitter]<https://twitter.com/paycheckout>[Facebook]<https://www.facebook.com/PayCheckout/>[LinkedIn]<https://www.linkedin.com/company/paycheckout-bv>

This message including any attachments is intended exlusively to the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). PayCheckout BV rules out any and every liability resulting from any electronic transmission.

**Comment by jay** [comment]
I mean the server hostname, the one you said you tested at the digicert website and it told you was configured correctly. That way we can try the server with our versions of curl and tell you if we see the same thing.

**Comment by PayCheckout** [comment]
Hello Jay,

The server is “sandbox.paycheckout.com”  this server is normally controlled with post (rest api) requests.
If you want to perform a normal “get” you can call a get request at url https://sandbox.paycheckout.com/alive.html.


Met vriendelijke groeten / with kind regards,

[PayCheckout B.V.]<https://www.paycheckout.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>

Martien Poels | CTO / Founder
m.poels@paycheckout.com<mailto:m.poels@paycheckout.com>
PayCheckout B.V. | www.paycheckout.com<https://www.paycheckout.com/?utm_source=signature&utm_medium=email&utm_campaign=signature>
Noorderhof 24, 5804 BV Venray
T: +31 (0)478 51 76 70
[Twitter]<https://twitter.com/paycheckout>[Facebook]<https://www.facebook.com/PayCheckout/>[LinkedIn]<https://www.linkedin.com/company/paycheckout-bv>

This message including any attachments is intended exlusively to the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). PayCheckout BV rules out any and every liability resulting from any electronic transmission.

**Comment by bagder** [comment]
curl https://sandbox.paycheckout.com/alive.html --cacert [bundle]

Works fine for me with the extracted ca-cert bundle with curl using either OpenSSL or GnuTLS.

So, I'd say it could be a problem with the older curl or the NSS backend...

**Comment by jay** [comment]
I can't reproduce this in curl using the latest mbedTLS, OpenSSL, WinSSL or wolfSSL. I tried some old versions as well for good measure. Also I can't reproduce in CentOS 7.1.1503 using that same preinstalled curl.

**Comment by PayCheckout** [comment]
Hello Jay,

Then we leave it as is, our problem was resolved by supplying the intermediate certificates. So we’re set.
BTW: we asked another developer with the same problem and he was running Ubuntu. Also his problem was gone with supplying the intermediate certificates.
Windows versions show no problems.
It’s not that the client could not reach internet, because both servers where directly hooked up to the internet with no firewalls or other limiting software/hardware.
We are a bit puzzled on how this could happen but nevertheless it works like a charm now.

Thanks for you cooperation.

Regards,

Martien Poels

**Comment by jay** [comment]
I tried in Ubuntu 14 as well using the packaged curl. The only other thing I can think of is there's a load balancer and one of the servers behind it is configured without the intermediate or the connection is renegotiated with different certificates and doesn't include the right intermediate. In any case this doesn't appear to be a curl problem.

**Comment by PayCheckout** [comment]
Hello Jay,

We will recheck all 3 servers that are behind the load balancers on the sandbox.paycheckout.com domain. There could be a difference Thanks. I let you know if we find anything. Due to load balancer settings it's likely that your hooked to a server with all certificates in place and others might not.

Regards Martien



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Jay Satiro <notifications@github.com>
Datum: 09-04-16 22:16 (GMT+01:00)
Aan: curl/curl <curl@noreply.github.com>
Cc: Martien Poels <m.poels@paycheckout.com>
Onderwerp: Re: [curl/curl] cacert.pem is incomplete for digicert SHA2 certificates!!! (#751)


I tried in Ubuntu 14 as well using the packaged curl. The only other thing I can think of is there's a load balancer and one of the servers behind it is configured without the intermediate or the connection is renegotiated with different certificates and doesn't include the right intermediate. In any case this doesn't appear to be a curl problem.

-
