### ISSUE TITLE
curl returns "404 page not found" while accessing a local application.

### ISSUE THREAD

**Issue by abcd-ABCD-1234** [curl/curl#7513]
### I did this
My application is running on the host with IP 192.168.4.235 on the port 7080. When I curl the same IP and port, it seems connection has been set, but still I get 404 page not found error, as below:

```
$ curl --verbose http://192.168.4.235:7080

*   Trying 192.168.4.235:7080...
* TCP_NODELAY set
* Connected to 192.168.4.235 (192.168.4.235) port 7080 (#0)
> GET / HTTP/1.1
> Host: 192.168.4.235:7080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 28 Jul 2021 14:20:17 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 192.168.4.235 left intact
```

But when I run a postgres service on port 5432, and connect using curl on port 5432, it gets connected and returns an empty reply.

Can someone please guide me on what is wrong here? I think the curl should return an empty reply with the application running on port 7080, but returning 404 not found is something I can't digest.

### I expected the following
Curl was expected to return an empty reply.

### curl/libcurl version

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1j zlib/1.2.11 libidn2/2.3.0 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
This is unlikely to be a problem with curl, but rather the application. curl
does a request for the root URL and the server returns 404. That's completely
legitimate and you need to figure out why the server is doing that if you don't
want it to.

Trying to access a postgres server using HTTP is unlikely to result in anything
useful.

**Comment by abcd-ABCD-1234** [comment]
Thank you @dfandrich for the information.

Ohkk then I think curl is not the culprit here. So does that mean curl expects some page to be found on this URL, but found nothing? And can you please suggest to me if there are more options to debug with curl...

**Comment by dfandrich** [comment]
curl doesn't expect anything except what HTTP allows. In this case, the server
sent a valid 404 error code back and curl dutifully notified you of that fact.
There are lots of options that can help with curl debugging, but it's probably
not necessary in this case. You need to fix the application to return something
other than a 404 error at that URL, or you need to change the URL to point to
one that has something more interesting to offer.

**Comment by abcd-ABCD-1234** [comment]
okay. Thank you for the details.
I will close this issue now.
