### ISSUE TITLE
Can't build curl with libnghttp2 on MacOs

### ISSUE THREAD

**Issue by rruipinheiro** [curl/curl#7514]
### I did this
Build libnghttp2 with vcpkg and brew (didn't work).
The configure run is:
```
./configure --prefix=... --with-openssl=.. --with-zlib=... --with-nghttp2=... --disable-shared --enable-static --disable-ldap
```

### Result
```
checking for libnghttp2 options with pkg-config... found
configure: -l is -lnghttp2
configure: -I is -I...lib/pkgconfig/../../include
configure: -L is -L...lib/pkgconfig/../../lib
checking for nghttp2_session_set_local_window_size in -lnghttp2... no
...
HTTP2:            no      (--with-nghttp2, --with-hyper)
```

### I expected the following
`HTTP2:            enable      (--with-nghttp2, --with-hyper)`

### curl/libcurl version
Host - x86_64-apple-darwin20.2.0
curl - 7.78.0-DEV
OpenSSL/1.1.1
libnghttp2 - 1.44.0
zlib - 1.2.11

**Comment by jay** [comment]
> configure: -L is -L...lib/pkgconfig/../../lib

is this what it actually says or did you modify it? I'd expect no more than 2 dots per segment. Did you actually check the path to see if it contains the lib?

**Comment by jay** [comment]
Nevermind, looks like I broke it. Discussion in #7515.

**Comment by rruipinheiro** [comment]
I still can't build with nghtt2p with these fixes...

**Comment by bagder** [comment]
@rruipinheiro are you perhaps using relative paths on the command line where you point out the locations of various paths?

**Comment by rruipinheiro** [comment]
@bagder I put this '...' in my paths to not show them but I point out to the location on the installed packages folder of vcpkg. When I tried using brew I didn't provide any path location to nghttp

**Comment by bagder** [comment]
When configure fails to do what you expected it to, for example to find the libraries you wanted it to find, then the standard next step is to open `config.log` in a text editor, search for the library/test that didn't go the way you expected and see what you can figure out based on that.

We've learned that this is a very effective way and reading this file often reveals details that can take you further in debugging your build/configure issue.

**Comment by rruipinheiro** [comment]
@bagder The pr: [#7515](https://github.com/curl/curl/pull/7515) worked for me! Thanks!
