### ISSUE TITLE
curl_off_t undeclared in tiny-cul-7.72

### ISSUE THREAD

**Issue by llcool** [curl/curl#7518]
### I did this

>  ./configure CFLAGS='-isystem -mlinux -Wall -Wshadow -O2 -g' --prefix=/home/lloyd/devboard-R2_01/target/cris-axis-linux-gnu --host=cris-axis-linux-gnu --with-ssl=/home/lloyd/devboard-R2_01/target/cris-axis-linux-gnu --disable-ftp --disable-file --disable-ldap --disable-rtmp --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-manual --enable-libcurl-option --disable-ipv6 --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-cookies --disable-soname-bump --without-zlib --enable-static=no
> 
### I expected the following
>  curl version:     7.72.0
  SSL:              enabled (OpenSSL)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             no      (--with-zlib)
  brotli:           no      (--with-brotli)
  zstd:             no      (--with-zstd)
  GSS-API:          no      (--with-gssapi)
  TLS-SRP:          no      (--enable-tls-srp)
  resolver:         POSIX threaded
  IPv6:             no      (--enable-ipv6)
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=no
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             no      (--enable-rtsp)
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          no      (--enable-alt-svc)
  HTTP2:            disabled (--with-nghttp2)
  HTTP3:            disabled (--with-ngtcp2, --with-quiche)
  ESNI:             no      (--enable-esni)
  Protocols:        HTTP HTTPS
  Features:         AsynchDNS HTTPS-proxy SSL UnixSockets
>

### actual output
>checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... (assumed) yes
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to enable c-ares for DNS lookups... no
checking whether to disable dependency on -lrt... (assumed no)
checking whether to enable ESNI support... no
checking for path separator... :
checking for sed... /bin/sed
checking for grep... /bin/grep
checking for egrep... /bin/grep -E
checking for cris-axis-linux-gnu-ar... /usr/local/cris/bin/cris-axis-linux-gnu-ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for cris-axis-linux-gnu-gcc... cris-axis-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cris-axis-linux-gnu-gcc accepts -g... yes
checking for cris-axis-linux-gnu-gcc option to accept ISO C89... none needed
checking whether cris-axis-linux-gnu-gcc understands -c and -o together... yes
checking how to run the C preprocessor... cris-axis-linux-gnu-gcc -E
checking for a sed that does not truncate output... (cached) /bin/sed
checking for code coverage support... no
checking whether build environment is sane... yes
checking for cris-axis-linux-gnu-strip... cris-axis-linux-gnu-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of cris-axis-linux-gnu-gcc... gcc3
checking curl version... 7.72.0
checking build system type... i686-pc-linux-gnu
checking host system type... cris-axis-linux-gnu
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for egrep... /bin/grep -E
checking if OS is AIX (to define _ALL_SOURCE)... no
checking if _THREAD_SAFE is already defined... no
checking if _THREAD_SAFE is actually needed... no
checking if _THREAD_SAFE is onwards defined... no
checking if _REENTRANT is already defined... no
checking if _REENTRANT is actually needed... no
checking if _REENTRANT is onwards defined... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cris-axis-linux-gnu-gcc... /usr/local/cris/cris-axis-linux-gnu/bin/ld
checking if the linker (/usr/local/cris/cris-axis-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/local/cris/bin/cris-axis-linux-gnu-nm -B
checking the name lister (/usr/local/cris/bin/cris-axis-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert i686-pc-linux-gnu file names to cris-axis-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/local/cris/cris-axis-linux-gnu/bin/ld option to reload object files... -r
checking for cris-axis-linux-gnu-objdump... cris-axis-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for cris-axis-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for cris-axis-linux-gnu-ar... /usr/local/cris/bin/cris-axis-linux-gnu-ar
checking for archiver @FILE support... no
checking for cris-axis-linux-gnu-strip... (cached) cris-axis-linux-gnu-strip
checking for cris-axis-linux-gnu-ranlib... cris-axis-linux-gnu-ranlib
checking command to parse /usr/local/cris/bin/cris-axis-linux-gnu-nm -B output from cris-axis-linux-gnu-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for cris-axis-linux-gnu-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cris-axis-linux-gnu-gcc supports -fno-rtti -fno-exceptions... yes
checking for cris-axis-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if cris-axis-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if cris-axis-linux-gnu-gcc static flag -static works... yes
checking if cris-axis-linux-gnu-gcc supports -c -o file.o... yes
checking if cris-axis-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the cris-axis-linux-gnu-gcc linker (/usr/local/cris/cris-axis-linux-gnu/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to build shared libraries with -version-info... yes
checking whether to build shared libraries with -no-undefined... no
checking whether to build shared libraries with -mimpure-text... no
checking whether to build shared libraries with PIC... yes
checking whether to build static libraries with PIC... no
checking whether to build shared libraries only... yes
checking whether to build static libraries only... no
checking for inline... inline
checking if cpp -P is needed... no
checking if compiler is DEC/Compaq/HP C... no
checking if compiler is HP-UX C... no
checking if compiler is IBM C... no
checking if compiler is Intel C... no
checking if compiler is clang... no
checking if compiler is GNU C... yes
checking if compiler is LCC... no
checking if compiler is SGI MIPSpro C... no
checking if compiler is SGI MIPS C... no
checking if compiler is SunPro C... no
checking if compiler is Tiny C... no
checking if compiler is Watcom C... no
checking if compiler accepts some basic options... yes
configure: compiler options added: -Werror-implicit-function-declaration 
checking if compiler accepts debug disabling options... yes
configure: compiler options added: 
checking if compiler optimizer assumed setting might be used... no
checking if compiler accepts strict warning options... yes
configure: compiler options added: -Wno-system-headers 
checking if compiler halts on compilation errors... yes
checking if compiler halts on negative sized arrays... yes
checking if compiler halts on function prototype mismatch... yes
checking if compiler supports hiding library internal symbols... no
checking for windows.h... no
checking whether build target is a native Windows one... no
checking whether build target supports WIN32 file API... no
checking for good-to-use Mac CFLAGS... no
checking to see if the compiler supports __builtin_available()... no
checking whether to support http... yes
checking whether to support ftp... no
checking whether to support file... no
checking whether to support ldap... no
checking whether to support ldaps... no
checking whether to support rtsp... no
checking whether to support proxies... yes
checking whether to support dict... no
checking whether to support telnet... no
checking whether to support tftp... no
checking whether to support pop3... no
checking whether to support imap... no
checking whether to support smb... yes
checking whether to support smtp... no
checking whether to support gopher... no
checking whether to support mqtt... no
checking whether to provide built-in manual... no
checking whether to enable generation of C code... yes
checking whether to use libgcc... no
checking if X/Open network library is required... no
checking for gethostbyname... yes
checking for windows.h... (cached) no
checking for winsock.h... (cached) no
checking for winsock2.h... (cached) no
checking for proto/bsdsocket.h... no
checking for connect in libraries... yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/types.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for monotonic clock_gettime... no
configure: WARNING: zlib disabled
checking for BrotliDecoderDecompress in -lbrotlidec... no
checking brotli/decode.h usability... no
checking brotli/decode.h presence... no
checking for brotli/decode.h... no
checking for ZSTD_createDStream in -lzstd... no
checking zstd.h usability... no
checking zstd.h presence... no
checking for zstd.h... no
checking whether to enable IPv6... no
checking if argv can be written to... no
configure: WARNING: the previous check could not be made default was used
checking if GSS-API support is requested... no
checking whether to enable Windows native SSL/TLS (Windows native builds only)... no
checking whether to enable Secure Transport... no
checking whether to enable Amiga native SSL/TLS (AmiSSL)... no
checking for HMAC_Update in -lcrypto... yes
checking for SSL_connect in -lssl... yes
checking openssl/x509.h usability... yes
checking openssl/x509.h presence... yes
checking for openssl/x509.h... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking openssl/crypto.h usability... yes
checking openssl/crypto.h presence... yes
checking for openssl/crypto.h... yes
checking openssl/pem.h usability... yes
checking openssl/pem.h presence... yes
checking for openssl/pem.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking for RAND_egd... yes
checking for SSLv2_client_method... yes
checking for OpenSSL_version... no
checking for BoringSSL... no
checking for libressl... no
checking for OpenSSL >= v3... no
checking for OpenSSL headers version... 0.9.7 - 0x0090706FL
checking for OpenSSL library version... 0.9.7
checking for OpenSSL headers and library versions matching... yes
configure: WARNING: skipped the /dev/urandom detection when cross-compiling
checking for SRP_Calc_client_key in -lcrypto... no
configure: built with one SSL backend
checking default CA cert bundle/path... configure: WARNING: skipped the ca-cert path detection when cross-compiling
no
checking whether to use builtin CA store of SSL library... no
checking for library containing psl_builtin... no
configure: WARNING: libpsl was not found
checking for RTMP_Init in -lrtmp... no
checking whether versioned symbols are wanted... no
checking whether to enable Windows native IDN (Windows native builds only)... no
checking whether to build with libidn2... (assumed) yes
checking for cris-axis-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking for libidn2 options with pkg-config... no
configure: IDN_LIBS: "-lidn2"
configure: IDN_LDFLAGS: ""
configure: IDN_CPPFLAGS: ""
configure: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... no
checking idn2.h usability... no
checking idn2.h presence... no
checking for idn2.h... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
checking for cris-axis-linux-gnu-pkg-config... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libnghttp2 options with pkg-config... no
checking for cris-axis-linux-gnu-pkg-config... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libngtcp2 options with pkg-config... no
checking for cris-axis-linux-gnu-pkg-config... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for quiche options with pkg-config... no
checking for cris-axis-linux-gnu-pkg-config... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for fish options with pkg-config... no
checking for ANSI C header files... (cached) yes
checking for malloc.h... yes
checking for memory.h... no
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for sys/select.h... yes
checking for sys/socket.h... yes
checking for sys/ioctl.h... yes
checking for sys/uio.h... yes
checking for assert.h... yes
checking for unistd.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for arpa/inet.h... yes
checking for net/if.h... yes
checking for netinet/in.h... yes
checking for netinet/in6.h... no
checking for sys/un.h... yes
checking for linux/tcp.h... yes
checking for netinet/tcp.h... yes
checking for netdb.h... yes
checking for sys/sockio.h... no
checking for sys/stat.h... (cached) yes
checking for sys/param.h... yes
checking for termios.h... yes
checking for termio.h... yes
checking for sgtty.h... yes
checking for fcntl.h... yes
checking for alloca.h... yes
checking for time.h... (cached) yes
checking for io.h... no
checking for pwd.h... yes
checking for utime.h... yes
checking for sys/utime.h... no
checking for sys/poll.h... yes
checking for poll.h... yes
checking for socket.h... no
checking for sys/resource.h... yes
checking for libgen.h... yes
checking for locale.h... yes
checking for errno.h... yes
checking for stdbool.h... yes
checking for arpa/tftp.h... yes
checking for sys/filio.h... no
checking for sys/wait.h... yes
checking for setjmp.h... yes
checking for an ANSI C-conforming const... yes
checking for compiler support of C99 variadic macro style... yes
checking for compiler support of old gcc variadic macro style... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for time.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for struct timeval... yes
checking size of size_t... 4
checking size of long... 4
checking size of int... 4
checking size of short... 2
checking size of time_t... 4
checking size of off_t... 8
checking size of curl_off_t... configure: error: cannot determine a size for curl_off_t
>
[config.log](https://github.com/curl/curl/files/6907003/config.log)

### curl/libcurl version
>
7.72.0
>
[curl -V output]

### operating system
>Linux door-DEV 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:00 UTC 2021 i686 i686 i686 GNU/Linux
>

### target OS
>Linux axis-00408cbe00df 2.6.15 #1110 PREEMPT Mon Jun 28 14:33:16 BST 2021 cris unknown
>

### my workaround
>--- include/curl/system-original.h      2021-07-30 11:52:28.003181447 +0100
+++ include/curl/system.h       2021-07-30 11:53:09.530818118 +0100
@@ -452,6 +452,16 @@

>  # define CURL_TYPEOF_CURL_SOCKLEN_T int
>  #endif
>  
> +/* If all else fails use old 32 bit style */
> +#if !defined(CURL_TYPEOF_CURL_OFF_T)
> +# define CURL_TYPEOF_CURL_OFF_T     long
> +# define CURL_FORMAT_CURL_OFF_T     "ld"
> +# define CURL_FORMAT_CURL_OFF_TU    "lu"
> +# define CURL_SUFFIX_CURL_OFF_T     L
> +# define CURL_SUFFIX_CURL_OFF_TU    UL
> +# define CURL_TYPEOF_CURL_SOCKLEN_T int
> +#endif
> +
>  #ifdef _AIX
>  /* AIX needs <sys/poll.h> */
>  #define CURL_PULL_SYS_POLL_H
>

**Comment by bagder** [comment]
This doesn't reproduce on my linux hosts. Why isn't the final generic `#else` clause good enough?

**Comment by llcool** [comment]
You will not be able to reproduce unless you are cross compiling for cris-axis arm processor.

More info here:- http://developer.axis.com/wiki/doku.php%3Fid=axis:compiling_for_cris_howto.html

**Comment by bagder** [comment]
So shouldn't the gcc on arm 32 bit section match?

**Comment by llcool** [comment]
I would have thought so, but it fails with curl_off_t undeclared, so I patched include/curl/system.h
As a side note I did not have these problems with curl 7.35.0

**Comment by bagder** [comment]
> I would have thought so, but it fails with curl_off_t undeclared

Obviously, but why? I would hate to just apply an "illogical" fix just because it happens to work without understanding why the existing code doesn't work as intended.

> As a side note I did not have these problems with curl 7.35.0

Just about everything in handling different platforms in the public headers were modified in the six years between those two versions...

**Comment by llcool** [comment]
As I have a workaround for this issue and not wanting you wasting your time on this. I am closing this issue.
