### ISSUE TITLE
Remote file name has no length

### ISSUE THREAD

**Issue by FrostShock** [curl/curl#7519]
### Feature request
Please implement a switch for extracting the filename from the downloaded link. When you use curl like this:
    `curl -k -O https://www.github.com`

you get:
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application

Please add a switch like --extract-file-name-from-link to make it assign names to downloaded files like wget does

**Comment by bagder** [comment]
The man page says it quite clearly:

> The  remote file name to use for saving is extracted from the given URL, nothing else

**Comment by FrostShock** [comment]
In this case I changed the issue from bug report to feature request

**Comment by bagder** [comment]
A feature request to ask us to change how `-O` works? That's not likely and we really don't handle feature requests. If you want a feature, please argue for it on the mailing list or perhaps start working on it and submit a PR for it. We have hundreds of ideas listed already are drowning in them. Ideas are easy. Implementing them are not.
