### ISSUE TITLE
Can't cross-compile statically with android ndk

### ISSUE THREAD

**Issue by Zackptg5** [curl/curl#7526]
### I did this
Cross compiled for android with my build script here: https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/blob/testing/build_script/build.sh

### I expected the following
Static link but got dynamic link

### curl/libcurl version
7.78.0
last working: 7.77.0

### operating system
Compile system: Manjaro on WSL2
Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
Could you highlight that 1000 line script for us? Specifically, what does
curl's configure command look like?

**Comment by Zackptg5** [comment]
The main stuff for curl is [here at line 360](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/blob/master/build_script/build.sh#L360). It compiles dependencies, then configures. The make part is at [line 869](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/blob/master/build_script/build.sh#L869).
The exact same commands and versions for curl's dependencies work fine for v7.77.

`./configure CFLAGS="$CFLAGS" CPPFLAGS="$CFLAGS -I$prefix/include -DANDROID" LDFLAGS="$LDFLAGS -L$prefix/lib" LIBS="$LIBS" \
        --host=$target_host --target=$target_host \
        $flags--prefix=$prefix \
        --enable-optimize \
        --enable-symbol-hiding \
        --disable-manual \
        --enable-threaded-resolver \
        --enable-alt-svc \
        --enable-hsts \
        --with-ssl=$prefix \
        --with-brotli=$prefix \
        --with-zstd=$prefix \
        --with-ca-path=/system/etc/security/cacerts \
        --with-nghttp2=$prefix \
        --with-libidn2=$prefix \
        --with-libssh2=$prefix \
        --with-quiche=$prefix/lib/pkgconfig`

Where for a static compile:
CFLAGS="-static -O2"
LDFLAGS="-static"
LIBS="-lidn2 -lunistring -ldl -lm"
flags="--enable-ares=$prefix --disable-shared"
prefix=<destination directory>

Then for the make command:
`make$flags install -j$jobs`

where here, flags=" curl_LDFLAGS=-all-static"

**Comment by Zackptg5** [comment]
Just tried it with all the dependencies removed except boringssl and same results if that helps at all

**Comment by dfandrich** [comment]
What does the link command-line look like? Does it contain your LDFLAGS? Is it even possible to link fully static on Android? Are all the static libraries you want available to the linker?

**Comment by Zackptg5** [comment]
Ya, it's in there. I link fully static for most of my binaries. Everything's available to it during compile. As I said, I tried it with no extras at all and it still linked statically

**Comment by dfandrich** [comment]
If curl is passing the right flags to the linker and the linker still isn't
doing the right thing, then it sounds to me like a linker problem, not a curl
problem.

**Comment by Zackptg5** [comment]
That's what I initially thought but if I run the exact same commands/build system/etc on curl 7.77, it compiles static as expected which is why I'm thinking something changed in 7.78

**Comment by dfandrich** [comment]
If it worked before, then there must be a difference in the options given to
the linker. What are those differences?

**Comment by Zackptg5** [comment]
Nope. What I'm saying is that literally everything is exactly the same except curl 7.77 vs curl 7.78

**Comment by dfandrich** [comment]
I would have suggested removing all library dependencies except for bionic and
try again, but you said you already tried that. I can't think of what would
cause this. If everything is the same except for a few code differences in curl
itself, I don't know what would cause this. What is the output of ldd for the
old and new curls?

**Comment by Zackptg5** [comment]
For 7.77:
```
# ldd
not a dynamic executable
# file
ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
# configure output
Host setup:       aarch64-unknown-linux-android
  Install prefix:   /home/zack/build_script/build-static/curl/aarch64
  Compiler:         aarch64-linux-android-clang
   CFLAGS:          -static -Qunused-arguments -Os
   CPPFLAGS:        -static -isystem /home/zack/build_script/build-static/curl/aarch64/include -DANDROID
   LDFLAGS:         -static -L/home/zack/build_script/build-static/curl/aarch64/lib
   LIBS:            -lz

  curl version:     7.77.0-DEV
  SSL:              no      (--with-{openssl,gnutls,nss,mbedtls,wolfssl,schannel,secure-transport,mesalink,amissl,bearssl,rustls} )
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
  brotli:           no      (--with-brotli)
  zstd:             no      (--with-zstd)
  GSS-API:          no      (--with-gssapi)
  GSASL:            no      (libgsasl not found)
  TLS-SRP:          no      (--enable-tls-srp)
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:
  ca fallback:
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  Metalink:         no      (--with-libmetalink)
  PSL:              no      (libpsl not found)
  Alt-svc:          enabled (--disable-alt-svc)
  HSTS:             no      (--enable-hsts)
  HTTP1:            enabled (internal)
  HTTP2:            no      (--with-nghttp2, --with-hyper)
  HTTP3:            no      (--with-ngtcp2, --with-quiche)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP GOPHER HTTP IMAP MQTT POP3 RTSP SMTP TELNET TFTP
  Features:         AsynchDNS IPv6 Largefile UnixSockets alt-svc libz
```
For 7.78: 
```
# ldd
not a dynamic executable
# file
ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
# configure
Host setup:       aarch64-unknown-linux-android
  Install prefix:   /home/zack/build_script/build-static/curl/aarch64
  Compiler:         aarch64-linux-android-clang
   CFLAGS:          -static -Qunused-arguments -Os
   CPPFLAGS:        -static -isystem /home/zack/build_script/build-static/curl/aarch64/include -DANDROID
   LDFLAGS:         -static -L/home/zack/build_script/build-static/curl/aarch64/lib
   LIBS:            -lz

  curl version:     7.78.0-DEV
  SSL:              no      (--with-{openssl,gnutls,nss,mbedtls,wolfssl,schannel,secure-transport,mesalink,amissl,bearssl,rustls} )
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
  brotli:           no      (--with-brotli)
  zstd:             no      (--with-zstd)
  GSS-API:          no      (--with-gssapi)
  GSASL:            no      (libgsasl not found)
  TLS-SRP:          no      (--enable-tls-srp)
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     enabled
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=no, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:
  ca fallback:
  LDAP:             no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS:            no      (--enable-ldaps)
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  PSL:              no      (libpsl not found)
  Alt-svc:          enabled (--disable-alt-svc)
  HSTS:             no      (--enable-hsts)
  HTTP1:            enabled (internal)
  HTTP2:            no      (--with-nghttp2, --with-hyper)
  HTTP3:            no      (--with-ngtcp2, --with-quiche)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP GOPHER HTTP IMAP MQTT POP3 RTSP SMTP TELNET TFTP
  Features:         AsynchDNS IPv6 Largefile UnixSockets alt-svc libz
```

**Comment by Zackptg5** [comment]
readelf does show it as dynamic:
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0xdd00
  Start of program headers:          64 (bytes into file)
  Start of section headers:          479936 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         25
  Section header string table index: 24
```

**Comment by Zackptg5** [comment]
I'm going to try at different commits and see what happens

**Comment by bagder** [comment]
Line 396:

>       $static && flags=" curl_LDFLAGS=-all-static" || flags=""

The `curl_LDFLAGS` variable doesn't exist in our makefile anymore. This is not a curl bug...

**Comment by Zackptg5** [comment]
That fixed it, sorry and thanks!
