### ISSUE TITLE
HTTP3 quiche upload large file failed

### ISSUE THREAD

**Issue by MegatronKing** [curl/curl#7532]
### I did this

Case 1: 
_curl -v --http3 -T image.jpg "https://quic.aiortc.org/echo"_

image.jpg => 47530

*   Trying 34.247.69.99:443...
* Connect socket 6 over QUIC to 34.247.69.99:443
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
*   Trying 2a05:d018:ce9:8100:cd2a:e2fd:b3be:c5ab:443...
* Immediate connect fail for 2a05:d018:ce9:8100:cd2a:e2fd:b3be:c5ab: Network is unreachable
* Connected to quic.aiortc.org () port 443 (#0)
* h3 [:method: PUT]
* h3 [:path: /echo]
* h3 [:scheme: https]
* h3 [:authority: quic.aiortc.org]
* h3 [user-agent: curl/7.79.0-DEV]
* h3 [accept: */*]
* h3 [content-length: 47530]
* Using HTTP/3 Stream ID: 0 (easy handle (nil))
> PUT /echo HTTP/3
> Host: quic.aiortc.org
> user-agent: curl/7.79.0-DEV
> accept: */*
> content-length: 47530
> 
* Pass on 47530 body bytes to quiche
* Pass on 35665 body bytes to quiche
* Connection #0 to host quic.aiortc.org left intact
curl: (55) Failed sending data to the peer

Case 2:

_curl -v --http3 -T image.jpg "https://quic.aiortc.org/echo"_

image.jpg => 83

*   Trying 34.247.69.99:443...
* Connect socket 6 over QUIC to 34.247.69.99:443
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
*   Trying 2a05:d018:ce9:8100:cd2a:e2fd:b3be:c5ab:443...
* Immediate connect fail for 2a05:d018:ce9:8100:cd2a:e2fd:b3be:c5ab: Network is unreachable
* Connected to quic.aiortc.org () port 443 (#0)
* h3 [:method: PUT]
* h3 [:path: /echo]
* h3 [:scheme: https]
* h3 [:authority: quic.aiortc.org]
* h3 [user-agent: curl/7.79.0-DEV]
* h3 [accept: */*]
* h3 [content-length: 83]
* Using HTTP/3 Stream ID: 0 (easy handle (nil))
> PUT /echo HTTP/3
> Host: quic.aiortc.org
> user-agent: curl/7.79.0-DEV
> accept: */*
> content-length: 83
> 
* Pass on 83 body bytes to quiche
* We are completely uploaded and fine
< HTTP/3 405
< server: aioquic/0.9.15
< date: Wed, 04 Aug 2021 03:10:16 GMT
< content-length: 18
< content-type: text/plain; charset=utf-8
< 
* Connection #0 to host quic.aiortc.org left intact

### curl/libcurl version
curl => master branch
quiche => master branch

_curl --version_
`curl 7.79.0-DEV (arm-unknown-linux-android) libcurl/7.79.0-DEV BoringSSL zlib/1.2.11 nghttp2/1.44.0 quiche/0.9.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets`

### operating system
Android armeabi-v7a
Android arm64-v8a

**Comment by MegatronKing** [comment]
curl bug? quiche bug?
https://github.com/cloudflare/quiche/issues/940

**Comment by bagder** [comment]
We also have **6** previous known bugs with the HTTP/3 implementation: https://curl.se/docs/knownbugs.html

**Comment by bagder** [comment]
Nobody is working on HTTP/3  in curl which makes it mostly accumulate bug reports... :disappointed:
