### ISSUE TITLE
HTTP3(quiche) not work with socks5 proxy

### ISSUE THREAD

**Issue by GongT** [curl/curl#7533]
### I did this
1. `ncat -kvvl 12345` # A
1. `ncat -uvvl 12345` # B
2. `./src/curl --http3 -v --proxy socks5://127.0.0.1:12345 https://www.google.com`

### I expected the following
curl should make TCP connection to A, then create a UDP bridge. B should recv nothing.

### What I got
curl send UDP packet to B

log:
```
* Uses proxy env variable NO_PROXY == '10.*,192.*,127.*,172.*'
*   Trying 127.0.0.1:12345...
* Connect socket 5 over QUIC to 127.0.0.1:12345
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
```

### curl/libcurl version

curl 7.78.0-DEV (x86_64-pc-linux-gnu) libcurl/7.78.0-DEV BoringSSL zlib/1.2.11 quiche/0.9.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets

### operating system
Linux developmentenvironment 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is not a feature anyone has implemented. It should indeed be possible.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

QUIC uses UDP so I suspect doing it over TCP in the last hop will not "just work" without some additional quirks being applied. I don't know of anyone working on this for any project anywhere.

**Comment by FightingForFun** [comment]
curl 8.14.1-DEV (x86_64-pc-linux-musl) libcurl/8.14.1-DEV OpenSSL/3.5.1 zlib/1.3.1 brotli/1.1.0 zstd/1.5.7 libidn2/2.3.7 libpsl/0.21.5 nghttp2/1.67.0-DEV ngtcp2/1.14.0-DEV nghttp3/1.1

Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets zstd

> HTTP/3 is not supported over a SOCKS proxy.
