### ISSUE TITLE
Trying to receive multiple files via active ftp and configure port range is extremely slow

### ISSUE THREAD

**Issue by mhdstg** [curl/curl#7534]
### I did this

I am trying to retrieve two files via ftps from an IBM z/OS host.

- performance in passive mode is fine (two small files are retrieved one 1s each)
- performance in active mode with parameter `-P` set to `<adress>:0 is also fine (same as passive mode)
- if a single port number or port range (` -P <address>:50000-50100`) is explicitly specified, it take about one minute to retrieve the second file. The retrieval of the first file in most tests was 1s, but sometimes it also takes about 30s (instead of 1s)

This is how I executed curl.exe:

Good performance
```
curl -v -user:password  -k -P 10.0.0.29:0 --ssl ftp://ZSYSTEM:21/TESTEDZ.MACROWIN(DCDPR) ftp://ZSYSTEM:21/TESTEDZ.MACRO(DCMPRO) -o DCDPR -o DCMPRO
````

Extremely bad performance
```
curl -v -user:password  -k -P 10.0.0.29:50000-50100 --ssl ftp://ZSYSTEM:21/TESTEDZ.MACROWIN(DCDPR) ftp://ZSYSTEM:21/TESTEDZ.MACRO(DCMPRO) -o DCDPR -o DCMPRO
````

### I expected the following

The time used to retrieved the second file should be the same as for the for first.

### curl/libcurl version

```
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
```

We have the same bad performance with libcurl 7.76.

### operating system
 
Microsoft Windows 10 connected to IBM z/OS 2.3.

### verbose output

```
D:\tmp\curltest>curl -v -u user:password  -k -P 10.0.0.29:50000-50100 --ssl ftp://ZSYSTEM:21/TESTEDZ.MACROWIN(DCDPR) ftp://ZSYSTEM:21/TESTEDZ.MACRO(DCMPRO) -o DCDPR -o DCMPRO
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.0.0.35:21...
* Connected to ZSYSTEM (10.0.0.35) port 21 (#0)
< 220-FTPD1 IBM FTP CS V2R3 at ZSYSTEM.DELTA-SOFTWARE.LOCAL, 15:38:21 on 2021-08-05.
< 220 Connection will close if idle for more than 5 minutes.
> AUTH SSL
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< 234 Security environment established - ready for negotiation
} [5 bytes data]
...
* SSL connection using TLSv1 / AES256-SHA
...
> USER user
{ [5 bytes data]
< 331 Send password please.
} [5 bytes data]
> PASS herbie
{ [5 bytes data]
< 230 user is logged on.  Working directory is "USER.".
} [5 bytes data]
> PBSZ 0
{ [5 bytes data]
< 200 Protection buffer size accepted
} [5 bytes data]
> PROT P
{ [5 bytes data]
< 200 Data connection protection set to private
} [5 bytes data]
> PWD
{ [5 bytes data]
< 257 "'USER.'" is working directory.
} [5 bytes data]
> SYST
* Entry path is ''USER.''
{ [5 bytes data]
< 215 MVS is the operating system of this server. FTP Server is running on z/OS.
* Request has same path as previous transfer
} [5 bytes data]
> EPRT |1|10.0.0.29|50000|
* ftp_perform ends with SECONDARY: 1
{ [5 bytes data]
< 200 EPRT request OK
* Connect data stream actively
} [5 bytes data]
> TYPE I
{ [5 bytes data]
< 200 Representation type is Image
} [5 bytes data]
> SIZE TESTEDZ.MACROWIN(DCDPR)
{ [5 bytes data]
< 501 command aborted -- FTP server not configured for SIZE
} [5 bytes data]
> RETR TESTEDZ.MACROWIN(DCDPR)
{ [5 bytes data]
< 125 Sending data set USER.TESTEDZ.MACROWIN(DCDPR) FIXrecfm 80
* Maxdownload = -1
* Getting file with size: -1
* Preparing for accepting server on data port
* Checking for server connect
* Ready to accept data connection from server
* Connection accepted from server
* Doing the SSL/TLS handshake on the data stream
* SSL re-using session ID
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
...
* TLSv1.0 (IN), TLS alert, close notify (256):
{ [2 bytes data]
* Remembering we are in dir ""
} [5 bytes data]
* TLSv1.0 (OUT), TLS alert, close notify (256):
} [2 bytes data]
< 250 Transfer completed successfully.
100  8720    0  8720    0     0   8160      0 --:--:--  0:00:01 --:--:--  8164
* Connection #0 to host ZSYSTEM left intact
* Found bundle for host ZSYSTEM: 0x1c387bc8a80 [serially]
* Re-using existing connection! (#0) with host ZSYSTEM
* Connected to ZSYSTEM (10.0.0.35) port 21 (#0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Request has same path as previous transfer
* Hostname 10.0.0.29 was found in DNS cache
} [5 bytes data]
> EPRT |1|10.0.0.29|50000|
* ftp_perform ends with SECONDARY: 1
{ [5 bytes data]
< 200 EPRT request OK
* Connect data stream actively
} [5 bytes data]
> SIZE TESTEDZ.MACRO(DCMPRO)
{ [5 bytes data]
< 501 command aborted -- FTP server not configured for SIZE
} [5 bytes data]
> RETR TESTEDZ.MACRO(DCMPRO)
  0     0    0     0    0     0      0      0 --:--:--  0:01:04 --:--:--     0{ [5 bytes data]
< 125 Sending data set MH.TESTEDZ.MACRO(DCMPRO) FIXrecfm 80
* Maxdownload = -1
* Getting file with size: -1
* Preparing for accepting server on data port
* Checking for server connect
* Ready to accept data connection from server
* Connection accepted from server
* Doing the SSL/TLS handshake on the data stream
* SSL re-using session ID
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [81 bytes data]
* TLSv1.0 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* TLSv1.0 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.0 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* SSL connection using TLSv1 / AES256-SHA
---
< 250 Transfer completed successfully.
100 32000    0 32000    0     0    489      0 --:--:--  0:01:05 --:--:--  7101
* Connection #0 to host ZSYSTEM left intact
```

**Comment by dfandrich** [comment]
Where do the delays happen? Can you repeat the trace with --trace-time to show that?
This is more likely to be an issue with a firewall or something else in the
network than a curl problem. Does --ftp-ssl-ccc help?

**Comment by mhdstg** [comment]
Thanks for your quick answer. 

I also suspected the firewall, but I get the same behavior with the firewall turned off. The problem also occurs on a Linux system.

--ftp-ssl-ccc does not help at all. If I set this option I get an error:

```
> PWD
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0* response reading failed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
* Closing connection 0
curl: (56) response reading failed
```

This is the trace output. It's the RETR command that need about 1 moin before it comes back:
```
08:25:41.672481 < 501 command aborted -- FTP server not configured for SIZE
08:25:41.687239 } [5 bytes data]
08:25:41.696358 > RETR TESTEDZ.MACRO(DCMPRO)
08:26:41.976418 { [5 bytes data]
08:26:41.997253 < 125 Sending data set USER.TESTEDZ.MACRO(DCMPRO) FIXrecfm 80
08:26:42.016838 * Maxdownload = -1
08:26:42.023988 * Getting file with size: -1
```

For me, the strange thing is that it works with a freely selectable port, but with a restricted port then the performance drops on the second file.

**Comment by bagder** [comment]
> 08:25:41.696358 > RETR TESTEDZ.MACRO(DCMPRO)
> 08:26:41.976418 { [5 bytes data]

curl does nothing in there except for waiting for data to arrive and it takes a minute. I believe this isn't a curl problem but a firewall/server issue that delays the traffic somehow.

**Comment by mhdstg** [comment]
I did some more research and I noticed a different behavior depending on whether a local port is specified or not.

If I specify "*" as local port the following happens:

- for the first file curl sends: `EPRT |1|10.0.0.29|52964|`. 
- for the second file curl chooses the next free port and sends: `EPRT |1|10.0.0.29|52965|`

In a second test I specified a port range of 50000-50100. Now something different happens:

- for the first file curl sends: `EPRT |1|10.0.0.29|50000|`
- for the seconds file curl does not choose a new free port and sends: `EPRT |1|10.0.0.29|50000|`

Why this different behavior? Is it a bug or a feature? I would expect the same behavior.

It seems that the port used to retrieve the content of the first file is not immediately released after the file was completely retrieved. After about 60s the port is free, and it is used to retrieve the second file. That's why we the transfer works better if "*" is used for the local port.

BTW: I also did a test with FileZilla. If I configure a local port range, FileZilla used the first free port for the first file and the next free port for the second file ... If I only allow one port, then FileZilla also has problems if I want to retrieve more than one file. There is a similar wait time of 60s before the second file can be retrieved. There really seems to be a problem in our (network) configuration or in the IBM z/OS ftp server implementation.

**Comment by bagder** [comment]
> for the seconds file curl does not choose a new free port and sends: EPRT |1|10.0.0.29|50000|

Why is that not free? curl will use the range and try the first port number and use that if its available and iterate over them when binding the port fails. So when it uses a port like that, then presumably it could bind the port number and it is ready to be used by curl.

**Comment by mhdstg** [comment]
> Why is that not free? curl will use the range and try the first port number and use that if its available and iterate over them when binding the port fails.

I was wondering about the different behavior with "*" and when defining a range. With "*" a new port is used for each file and this works then. 

When using a range, the same port is used for each file and there is a blockade. Therefore my assumption.

However, other tools like FileZilla seem to behave the same way. Therefore I suspect the problem at the moment on the side of the ftp server on z/OS.

**Comment by bagder** [comment]
When you don't restrict the port number, curl will ask the TCP stack for one and then it'll get one in a semi random fashion. When you ask for a range, curl will pick one from the range and it'll use the first one that works.

**Comment by jay** [comment]
This doesn't sound like a curl bug to me

**Comment by mhdstg** [comment]
You are right. In the mean time I made some tests with other ftps clients. Most of them had the exactly the same behaviour. 
One library (Chilkat) works a bit different if a local port range is used: they are using for each get another port. So the problem does not occur if the range is larger than the number of files.

Therefore I will close this issue.
