### ISSUE TITLE
[curl.config] perhaps small bug 

### ISSUE THREAD

**Issue by dnmTX** [curl/curl#7537]
Hi there 👋 . 
I was debating with myself to report this or not as i'm still not sure is it a bug or by design so apologies upfront if it isn't.
As the manual states one can use short names in the config file,fo example instead of `--ipv4` i can do `ipv4` only.
Indeed no problems until i decided to restrict the protocols in use. The original command/option is `--proto =http,https...` and so on,so logically thinking here the short name of this should be `proto = http,https` correct?
Well it's not,only the original option works for this specific command only,which made me think what else doesn't accept short names. I tested all of my entries but you guys either need to set some standart or add some warning in the `help` next to each affected entry.
Other then that it's all good and thank you all for the hard work 👍 

### curl/libcurl version

```
curl 7.77.0 (arm-uclibc-linux) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11.zlib-ng
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
Using it on my DD-WRT router and i know it's not the latest version but it's up to the developer when it comes to feature updates.

### operating system

`Linux DD-WRT 4.4.276 #3725 SMP Mon Jul 26 03:02:07 +07 2021 armv7l DD-WRT`

**Comment by bagder** [comment]
> logically thinking here the short name of this should be proto = http,https correct?

No, The parameter **starts** with a `=` letter and the documentation for `--config` says:

> If the parameter contains whitespace (or starts with : or =), the parameter must be enclosed within quotes. 

Thus it should be something like

    proto = "=http,https"

**Comment by dnmTX** [comment]
`proto = "=http,https"`  worked 👍  also `proto "=http,https"` worked as well.
@bagder thanks for clarifying this,i guess your manual is better then the one i found online 😉 
Closing this as resolved,turned out to be more like a lack of knowledge on my part then a bug 🤔
Thanks again and keep up the good work 👍
