### ISSUE TITLE
build fails when enabling nghttp3

### ISSUE THREAD

**Issue by shoober420** [curl/curl#7539]
### curl/libcurl version
```
curl 7.79.0-DEV (x86_64-pc-linux-gnu) libcurl/7.79.0-DEV (GnuTLS/3.7.2) OpenSSL/1.1.1k zlib/1.2.11 zstd/1.5.0 quiche/0.9.0                                                                     
Release-Date: [unreleased]
Protocols: dict file http https mqtt rtsp 
Features: HSTS HTTP3 Largefile libz MultiSSL NTLM SSL TLS-SRP UnixSockets zstd
```
Built from https://github.com/curl/curl/commit/1390fc097776f734a0b693c446b6ff7712a68a98

### operating system
`Linux gentoo 5.13.0-pf5+ #1 SMP Thu Aug 5 04:48:11 EDT 2021 x86_64 GNU/Linux`

Pardon my ignorance, but I'm experimenting with trying to get nghttp3 working on my Gentoo machine, and get a build error during the 32bit lib compilation. Here is a snippet of the error with the full log. I also tried to compile with default build flags (-march=native -O2 -pipe) and build still failed the same way.

[buildcurl.log](https://github.com/curl/curl/files/6945598/buildcurl.log)

```
In file included from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/quic.h:32,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/urldata.h:142,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/conncache.c:28:
/var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/vquic/quiche.h:31:8: error: redefinition of 'struct quic_handshake'
   31 | struct quic_handshake {
      |        ^~~~~~~~~~~~~~
In file included from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/quic.h:29,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/urldata.h:142,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/conncache.c:28:
/var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/vquic/ngtcp2.h:37:8: note: originally defined here
   37 | struct quic_handshake {
      |        ^~~~~~~~~~~~~~
In file included from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/quic.h:32,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/urldata.h:142,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/conncache.c:28:
/var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/vquic/quiche.h:38:8: error: redefinition of 'struct quicsocket'
   38 | struct quicsocket {
      |        ^~~~~~~~~~
In file included from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/quic.h:29,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/urldata.h:142,
                 from /var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/conncache.c:28:
/var/tmp/portage/net-misc/curl-9999/work/curl-9999/lib/vquic/ngtcp2.h:44:8: note: originally defined here
   44 | struct quicsocket {
      |        ^~~~~~~~~~
make[2]: *** [Makefile:2017: libcurl_la-bufref.lo] Error 1
make[2]: *** [Makefile:2031: libcurl_la-conncache.lo] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-misc/curl-9999/work/curl-9999-abi_x86_32.x86/lib'
make[1]: *** [Makefile:1360: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-misc/curl-9999/work/curl-9999-abi_x86_32.x86/lib'
make: *** [Makefile:1262: all-recursive] Error 1
```

**Comment by bagder** [comment]
What makes you say this is related to 32 bit builds?

**Comment by bagder** [comment]
What did your configure line look like?

**Comment by bagder** [comment]
Also, see #7541 that just recently synced the build with the latest nghttp3 and friends.

**Comment by shoober420** [comment]
When I skimmed the logs, I thought I saw it stop compilation during the 32bit phase. Looking back now I read it wrong.

`libtool: compile:  x86_64-pc-linux-gnu-gcc -m32`

I saw m32, but theres a minus infront, and it says "x86_64" prior, so my apologize.

Here is my configure line. I use Gentoo so its an ebuild.

https://github.com/shoober420/shoober420-overlay/blob/main/net-misc/curl/curl-9999.ebuild#L183

I'll build curl tonight and see if that pull request fixes it.

**Comment by shoober420** [comment]
I just compiled and its still seems to stop at the same spot.

[buildcurl2.log](https://github.com/curl/curl/files/6952575/buildcurl2.log)

**Comment by shoober420** [comment]
I just read this blog post, https://candrews.integralblue.com/2019/10/http-3-support-added-to-curl-in-gentoo/, and decided to disable the "quiche" use flag, and just leave "nghttp3" set. The build still doesnt complete unfortunately. Here is the log. Its a big log.

[buildcurlnoquiche.log](https://github.com/curl/curl/files/6952612/buildcurlnoquiche.log)

**Comment by bagder** [comment]
We can't take responsibility for gentoo's build. It seems to enable *both* ngtcp2 and quiche in the build. You should/can only use one of them.

**Comment by shoober420** [comment]
Awesome, adding "--without-ngtcp2" fixed the build. I also disabled http2 since it shouldnt be needed either I only have "quiche" and "nghttp3" enabled and all went well. Thank you for the explanation.
