### ISSUE TITLE
Downloading file to `tmp` folder fails without error

### ISSUE THREAD

**Issue by a-kuharenko** [curl/curl#7550]
### I did this
```
curl -L -o "/tmp/test.html" "http://example.com"
```

### I expected the following
File "test.html" appeared in "/tmp" directory

### Actual result
File did not appear, no error message in console.

### curl/libcurl version

> curl 7.78.0 (x86_64-pc-linux-gnu) libcurl/7.78.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 libgsasl/1.8.1 OpenLDAP/2.4.49
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

> Linux 5.11.0-25-generic # 27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Everything works fine on `curl 7.74.0`

**Comment by bagder** [comment]
> no error message in console.

You are using `-s` which silences all error messages...

**Comment by a-kuharenko** [comment]
> > no error message in console.
> 
> You are using `-s` which silences all error messages...

Without this flag still no message

**Comment by jay** [comment]
`strace -f -e trace=file -P /tmp/test.html curl -L -v -o "/tmp/test.html" "http://example.com"`

**Comment by dfandrich** [comment]
Are you running curl in some kind of environment with namespaces or somesuch
(e.g. Docker) where /tmp is different for curl than for whatever process you're
using to look at /tmp?

**Comment by aleksandr-kuharenko** [comment]
> `strace -f -e trace=file -P /tmp/test.html curl -L -v -o "/tmp/test.html" "http://example.com"` 

![result](https://user-images.githubusercontent.com/55990287/128994402-1cbcbdc0-2d17-4bb1-a588-59ce12da31fa.png)

**Comment by a-kuharenko** [comment]
> `strace -f -e trace=file -P /tmp/test.html curl -L -v -o "/tmp/test.html" "http://example.com"` 

![result](https://user-images.githubusercontent.com/55990287/128994402-1cbcbdc0-2d17-4bb1-a588-59ce12da31fa.png)

**Comment by a-kuharenko** [comment]
> Are you running curl in some kind of environment with namespaces or somesuch (e.g. Docker) where /tmp is different for curl than for whatever process you're using to look at /tmp?

No, I run curl in my ubuntu terminal

**Comment by bagder** [comment]
That screenshot says **curl/7.68.0** ...

**Comment by sergio-nsk** [comment]
The errno 6 is ENXIO: “No such device or address.” The system tried to use the device represented by a file you specified, and it couldn’t find the device. This can mean that the device file was installed incorrectly, or that the physical device is missing or not correctly attached to the computer.

Something wrong with the mounted /tmp. The output of `mount` would be useful.

**Comment by bagder** [comment]
> The errno 6 is ENXIO

No, `openat()` returns a normal file descriptor. That's the 6 in this case. It means it worked just fine.

**Comment by bagder** [comment]
@a-kuharenko your screenshot was made with a third mentioned curl version. It didn't make the confusion here any less.

**Comment by bagder** [comment]
No more responses. Closing.
