### ISSUE TITLE
php curl error: cURL error 60: Peer's certificate has an invalid signature

### ISSUE THREAD

**Issue by bpavesi** [curl/curl#7557]
### I did this

We use a web application to access an external resourse through a proxy wich do paket ispection, but we can't connect.

### I expected the following

Could connect to the external resource through the proxy.

### curl/libcurl version

curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0

### operating system

Linux myserver 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
> curl 7.29.0

Released over **eight years** ago.

If you can reproduce this with a modern curl version, please tell us how!

**Comment by bpavesi** [comment]
Hello, we have two identical istances of the same web application (also same curl version), and one is working fine. I think we need to know, on the instance with the erro, where curl is verifing the CA files? if i understood what the error means.

**Comment by bagder** [comment]
That error message probably comes from NSS, so you need to check it's documentation/source code to see what it means.

Since you're using ancient versions, I assume that the problems are gone in recent versions. So until you tell me otherwise, you're on your own.

**Comment by bpavesi** [comment]
ok thank you
