### ISSUE TITLE
Recent changes to .gitattributes appears to cause auto-mutation of several files in the winbuild directory

### ISSUE THREAD

**Issue by bretambrose** [curl/curl#756]
### I did this
git clone https://github.com/curl/curl.git
cd curl
git status

### I expected the following
A fresh source tree with no changes

### I got the following instead
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   winbuild/Makefile.msvc.names
    modified:   winbuild/MakefileBuild.vc

no changes added to commit (use "git add" and/or "git commit -a")

### curl/libcurl version
N/A (current)

### operating system
Ubuntu 12
Git 2.8.1

This causes a cmake-built project that is pulling in curl via Add_External_Project to fail because cmake pulls curl in via a git clone, followed by a git checkout to a specific revision.  The git checkout fails because of the changed files.

**Comment by bagder** [comment]
Thanks, I reverted that change again.
