### ISSUE TITLE
curl-7.78.0 has some silent breakage

### ISSUE THREAD

**Issue by stefson** [curl/curl#7572]
hey there, 

I'm a user of deadbeef music player, and am using one of its plugins (vfs_curl) to listen to a radio station stream. This stopped working, when I updated my systems curl vom curl-7.77.0 to curl-7.78.0 , this is revertable when downgrading back to curl-7.77.0

the streaming url is this one: https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3

right now I'm back on the older curl-7.77.0:

```
curl 7.77.0 (x86_64-pc-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k zlib/1.2.11 libidn2/2.3.1 nghttp2/1.43.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps http https imap imaps mqtt pop3 pop3s rtsp smtp smtps tftp 
Features: AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets
```

I'm on gentoo-linux (amd64)

my kernel ist linux-5.4.140 (gentoo amd64): 

```
Linux 5.4.140-gentoo #109 SMP Thu Aug 12 14:52:11 CEST 2021 x86_64 AMD Ryzen 5 2600 Six-Core Processor AuthenticAMD GNU/Linux
```

**Comment by stefson** [comment]
some more things I did to poke this: 

- fetching the mp3 stream is not a problem with both curl versions, the dumped mp3 file plays nicely
- my systems libcurl uses the openssl backend, I tried switchting to gnutls, but that to no positive results
- I read about problems with static linking in curl-7.78.0, but was told that I don't use static linking in my build
- deadbeef has the ability to log vfs_curl and its action, it returns error code 3 = CURLE_URL_MALFORMAT

any suggestions?

**Comment by stefson** [comment]
this is the log from deadbeef vfs_curl: 

```
resume: track -1 pos -1.000000 playlist -1
http_get_content_type
http_get_content_type waiting for response...
vfs_curl: started loading data https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3 
vfs_curl: calling curl_easy_perform (status=0)...
vfs_curl: curl_easy_perform retval=3
curl error:

vfs_curl: break loop
vfs_curl: thread ended normally
http_close 0x7f757c011220
abort vfs_curl stream: 1
added file to abort list: 1
http_close done
Failed to play track: https://wdr-1live-live.icecastssl.wdr.de/wdr/1live/live/mp3/128/stream.mp3 
```

**Comment by jzakrzewski** [comment]
It looks like there is a space at the end of your URL. AFAIR rejecting spaces is something that has been implemented fairly recently. In fact accepting them unencoded was a bug.

**Comment by stefson** [comment]
> It looks like there is a space at the end of your URL. AFAIR rejecting spaces is something that has been implemented fairly recently. In fact accepting them unencoded was a bug.

thank you, this is correct and removing the arbitary blank line makes vfs_curl work again with curl-7.78.0

shall I close, or do you still need it to be open?

**Comment by bagder** [comment]
Let's close it, as this is not a curl bug.
