### ISSUE TITLE
Mac M1 arm64 two-level namespace is not enabled by default

### ISSUE THREAD

**Issue by czlitony** [curl/curl#7573]
### I did this
Build arm64 libcurl for Mac M1.

### I expected the following
Expect it can work well, but it always crashes when debugging with XCode on Mac M1.
This is because the built libcurl two-level namespace is not enabled, it mixes with system libcurl and causes the dynamic linking issue when debugging with XCode.
Need enable two-level namespace for M1 arm64 build to avoid such issue.

### curl/libcurl version

7.74.0

### operating system

Mac M1

**Comment by bagder** [comment]
What does that mean more specifically?

**Comment by czlitony** [comment]
@bagder  this is what we got from Apple:

> 
> And there’s our smoking gun.  libcurl is importing curl_multi_cleanup from the dynamic linker’s flat namespace.  The flat namespace is deprecated on our platforms and libcurl’s use of it is the root cause of this bug.  Here’s how this happens:
> 	1.	When you run from Xcode, something is causing the system’s libcurl to be loaded in your process.  It’s not clear what that is, but that’s besides the point.  It could just as easily be a system framework loading the system’s libcurl.
> 	2.	Your app (well, one of its plug-ins) loads and runs your libcurl by calling the _curl_easy_perform function.  This works because your code imports this symbol using the two-level namespace, with the first level being the library name, that is, libcurl.  So the dynamic linker looks in your libcurl for _curl_easy_perform, finds it, and calls it.
> 	3.	In frame 9 your libcurl calls curl_multi_cleanup.  It imports this symbol using the flat namespace, so the dynamic linker does not know to resolve the symbol by searching in your libcurl.  Rather, it searches for the first instance of curl_multi_cleanup it finds.  This happens to be in the system’s libcurl!
> 	4.	So your libcurl calls the system’s libcurl.  These are built from different versions of the libcurl source, and so the system’s libcurl crashes trying to work with data structures that were set up by your libcurl.
> 
> 
> This crash only happens when running from Xcode because something about Xcode’s debugging infrastructure causes the process to load the system’s libcurl.  However, this is not a bug in the debugging infrastructure, because it could just as easily be some system framework that loaded libcurl.
> 
> The real bug is that your libcurl is built using the flat namespace.  The flat namespace was deprecated because it leads to exactly this sort problem.  To fix this bug rebuild your libcurl to use the two-level namespace.
> 
> You should also survey your code for other libraries that use the flat namespace, because such libraries are a disaster waiting to happen.

**Comment by bagder** [comment]
I was hoping for a command line option or something that is needed at link-time or something. We build curl identically on most *nix-like platforms including macOS. They've now changed something. What's now required on our part to build libcurl with a "two-level namespace" ? I presume it is libcurl only, not the curl tool? Or is it the other way around?

**Comment by bagder** [comment]
Also: how **did** you build in the first place?

**Comment by bagder** [comment]
> The static linker enables the two-level namepace option (-twolevel_namespace) by default in Mac OS X 10.1.
([source](https://mirror.informatimago.com/next/developer.apple.com/releasenotes/DeveloperTools/TwoLevelNamespaces.html))

**Comment by czlitony** [comment]
@bagder I have not tried to build libcurl from this repo directly. I met this problem when building libcurl 7.74.0 and 7.78.0 for Apple M1, I find that the built libcurl.dylib doesn't enable two-level namespace. We can check if two-level namespace is enabled with below command, there is no `TWOLEVEL` in the output.
```
✗ otool -hV libcurl.dylib
 ...
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    21       2088 DYLDLINK NO_REEXPORTED_DYLIBS
```
As a comparation, we have another library libcrypto.dylib has enabled two-level namespace, we can see`TEWLEVEL` in the output.
```
✗ otool -hV libcrypto.dylib
 ...
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    16       1752   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIB
```
Now we have found a workaroud in version 7.78.0 to fix this issue by replacing `$wl-flat_namespace $wl-undefined ${wl}suppress` with `$wl-undefined ${wl}dynamic_lookup`. On master branch, I have not found `flat_namespace` related codes, seems this is already fixed?

**Comment by bagder** [comment]
> I met this problem when building libcurl 7.74.0 and 7.78.0 for Apple M1,

So again: how did you build libcurl?

**Comment by bagder** [comment]
> we have found a workaroud in version 7.78.0 to fix this issue by replacing $wl-flat_namespace $wl-undefined ${wl}suppress with $wl-undefined ${wl}dynamic_lookup

Could it be libtool or autoconf that put them there on macOS? They're not present in git and on Linux they don't appear. On macOS I can see them in generated files...!

**Comment by bagder** [comment]
I can't recall any change *ever* in curl regarding this.

A fresh build on my mac shows twolevel enabled:
~~~
$ otool -hV lib/.libs/libcurl.dylib 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    24       2504   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS

**Comment by czlitony** [comment]
> > I met this problem when building libcurl 7.74.0 and 7.78.0 for Apple M1,
> 
> So again: how did you build libcurl?

Build with commands:
```
./configure --enable-ipv6 --enable-http --enable-tftp --enable-ftp --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-manual --enable-file --without-zlib --without-ca-bundle --without-ca-path --with-ssl=ssl_folder --enable-debug --enable-curldebug --with-gssapi --enable-shared=yes DYLID_LIBRARY_PATH=ssl_folder/lib --host=aarch64-apple-darwin
make V=1
```

**Comment by czlitony** [comment]
> > we have found a workaroud in version 7.78.0 to fix this issue by replacing $wl-flat_namespace $wl-undefined ${wl}suppress with $wl-undefined ${wl}dynamic_lookup
> 
> Could it be libtool or autoconf that put them there on macOS? They're not present in git and on Linux they don't appear. On macOS I can see them in generated files...!

I have not tried to generate the `configure` by myself, I used the `configure` in https://github.com/curl/curl/releases/download/curl-7_78_0/curl-7.78.0.tar.gz

**Comment by czlitony** [comment]
> I can't recall any change _ever_ in curl regarding this.
> 
> A fresh build on my mac shows twolevel enabled:
> 
> ```
> $ otool -hV lib/.libs/libcurl.dylib 
> Mach header
>       magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
> MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    24       2504   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
> ```

@bagder I see that you are building x86_64, there is no problem with arch x86_64, it only happens when building libcurl for Mac M1 which arch is arm64. You can add `-arch arm64` to build arm64 library for M1.

**Comment by bagder** [comment]
Either way, those are not instructions put there by us. The come from autoconf or libtool. ... :confused:

**Comment by bagder** [comment]
Seen in the generated configure script (line 10454 in my case, using autoconf 2.69):
~~~shell
    case $host_os in
    rhapsody* | darwin1.[012])
      _lt_dar_allow_undefined='$wl-undefined ${wl}suppress' ;;
    darwin1.*)
      _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
    darwin*) # darwin 5.x on
      # if running on 10.5 or later, the deployment target defaults
      # to the OS version, if on x86, and 10.4, the deployment
      # target defaults to 10.4. Don't you love it?
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
	10.0,*86*-darwin8*|10.0,*-darwin[912]*)
	  _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
	10.[012][,.]*)
	  _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
	10.*|11.*)
	  _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac
    ;;

**Comment by czlitony** [comment]
@bagder agree with you this should be related with autoconf or libtool which I'm not familar with. I will make further investigation, will update later if I have new findings. Thanks for your kind of help.

**Comment by bagder** [comment]
More specifically it seems to be related to cross-compiling since it doesn't show otherwise. I think an interesting part is that it seems to check for specific Darwin versions and change flags depending on what it finds, and that seems "difficult" when cross-compiling. As the snippet I showed indicates, you can change this behavior with the `MACOSX_DEPLOYMENT_TARGET` environment variable.

**Comment by bagder** [comment]
This appears to be a libtool/autotool issue. Closing.
