### ISSUE TITLE
libcurl.so core seen occasionally  with _int_free() call  in multi_runsingle()

### ISSUE THREAD

**Issue by kshang510** [curl/curl#7579]
Ran script with "Enable http with proxy sessions then disable them" multiple times, encountered core occasionally after        disabled the sessions.

Core decode back trace:
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f23c42e8c41 in __GI_abort () at abort.c:79
#2  0x00007f23c4328dd9 in __libc_message (action=action@entry=do_abort,
    fmt=fmt@entry=0x7f23c442d402 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f23c432f31a in malloc_printerr (
    str=str@entry=0x7f23c442b4d6 "corrupted size vs. prev_size") at malloc.c:5336
#4  0x00007f23c43302b4 in _int_free (av=0x7f23b0000020, p=<optimized out>,
    have_lock=<optimized out>) at malloc.c:4281
#5  0x00007f23c409405a in multi_runsingle () from /isan/lib/libcurl.so.4
#6  0x00007f23b072c950 in ?? ()
#7  0x000000000000001c in ?? ()
#8  0x00007f23c40772c5 in ftp_state_retr () from /isan/lib/libcurl.so.4
#9  0x00007f23c4090613 in singleipconnect () from /isan/lib/libcurl.so.4
#10 0x00007f23c406bc8d in Curl_pgrsUpdate () from /isan/lib/libcurl.so.4
#11 0x000000001cd2fdc7 in ?? ()
#12 0x00007f23b072c950 in ?? ()
#13 0x00007f23c407deaf in parse_login_details () from /isan/lib/libcurl.so.4
#14 0x00007f239464c6d0 in ?? ()
#15 0x00007f239464c7b8 in ?? ()
#16 0x00007f23c40662cf in ?? () from /isan/lib/libcurl.so.4

ported fix from https://github.com/curl/curl/pull/7237/commits/7d0d245df80b11f2e5459338a239e5482aceccb1
Core still seen with below slightly different backtrace:

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f34c4a6ec41 in __GI_abort () at abort.c:79
#2  0x00007f34c4aaedd9 in __libc_message (action=action@entry=do_abort,
    fmt=fmt@entry=0x7f34c4bb3402 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f34c4ab531a in malloc_printerr (
    str=str@entry=0x7f34c4bb4da0 "double free or corruption (out)") at malloc.c:5336
#4  0x00007f34c4ab6260 in _int_free (av=0x7f34c4beac40 <main_arena>, p=0x7f34b5125720,
    have_lock=<optimized out>) at malloc.c:4264
#5  0x00007f34c481905a in multi_runsingle () from /isan/lib/libcurl.so.4
#6  0x00007f34b507a8b0 in ?? ()
#7  0x000000000000001c in ?? ()
#8  0x00007f34c47fc2c5 in ftp_state_retr () from /isan/lib/libcurl.so.4
#9  0x00007f34c4815613 in singleipconnect () from /isan/lib/libcurl.so.4
#10 0x00007f34c47f0c8d in Curl_pgrsUpdate () from /isan/lib/libcurl.so.4
#11 0x0000000003dbb577 in ?? ()
#12 0x00007f34b507a8b0 in ?? ()
#13 0x00007f34c4802eaf in parse_login_details () from /isan/lib/libcurl.so.4
#14 0x00007f3494dcf6d0 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007f3494dcf7b8 in ?? ()
#16 0x00007f34c47eb2cf in ?? () from /isan/lib/libcurl.so.4
#17 0x0000000000001ff8 in ?? ()
#18 0x0000000000000000 in ?? ()

### Using url/libcurl 7.77

bash-4.4# curl -V
curl 7.77.0 (x86_64-nxos-linux-gnu) libcurl/7.77.0 OpenSSL/1.1.1k-fips zlib/1.2.11 libidn2/2.3.0
Release-Date: 2021-05-26
Protocols: file ftp ftps http https 
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets

### operating system - NXOS

bash-4.4# uname -a
Linux n9k-telemetry 4.19.190 #1 SMP Thu Aug 5 22:34:06 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
On Mon, Aug 16, 2021 at 12:20:45PM -0700, kshang510 wrote:
> Ran script with "Enable http with proxy sessions then disable them" multiple
> times, encountered core occasionally after
>     disabled the sessions.

What script is this? And what sessions are you talking about disabling?

**Comment by bagder** [comment]
Please tell us what your application is doing (in detail). Please tell us how we can reproduce the problem.

Otherwise there's not a lot we can do to help you.

**Comment by kshang510** [comment]
The application is switch telemetry feature to stream out data  from switch thru http sessions. https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/programmability/guide/b_Cisco_Nexus_9000_Series_NX-OS_Programmability_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_Programmability_Guide_7x_chapter_011000.html

The script performed below configuration then disable the feature by killing the telemetry process. The script passed most of the time, but occasionally it would crash in libcurl.so during feature disable.
The first core decode without loading libcurl.so.4 explicitly into target is:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f23c42e8c41 in __GI_abort () at abort.c:79
#2  0x00007f23c4328dd9 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f23c442d402 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f23c432f31a in malloc_printerr (str=str@entry=0x7f23c442b4d6 "corrupted size vs. prev_size") at malloc.c:5336
#4  0x00007f23c43302b4 in _int_free (av=0x7f23b0000020, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4281
#5  0x00007f23c409405a in ?? () from /isan/lib/libcurl.so.4
#6  0x00007f23c40772c5 in ?? () from /isan/lib/libcurl.so.4
#7  0x00007f23c4077fa4 in ?? () from /isan/lib/libcurl.so.4
#8  0x00007f23c4078f7e in curl_multi_perform () from /isan/lib/libcurl.so.4
#9  0x00007f23c4057aa3 in curl_easy_perform () from /isan/lib/libcurl.so.4
#10 0x00007f23c45cc457 in ?? () from /isan/lib/libtranshttp.so

The configs applied are in below, there are a few subscription utilized http/curl/proxy sessions, such as subscriptions 1,2 & 600. 
I don't think the issue could be reproduced easily. Hoping the backtrace info is  enough 
to pin point if this crash is a known issue or not.
-----------------  Enable feature -----------------------------------------------------
feature telemetry

telemetry
  certificate trustpoint trustpoint1 foo.test.google.fr
  destination-profile
    use-nodeid filter_test
  destination-group 1
    host 172.19.216.78 port 50010 protocol gRPC encoding GPB
      proxy 172.27.254.13 port 3128 username proxyclient password 7 fewhg
    host 172.19.216.78 port 50021 protocol HTTP encoding JSON
      proxy 172.27.254.13 port 3128 username proxyclient password 7 fewhg
    filter file /bootflash/parser.json md5 497bead9dfbe89121cd2f4bd131c2393
  destination-group 2
    host 172.19.216.78 port 50024 protocol HTTP encoding JSON
      proxy 173.36.240.173 port 80
    filter file /bootflash/parser.json md5 497bead9dfbe89121cd2f4bd131c2393
  destination-group 3
    filter file /bootflash/parser.json md5 497bead9dfbe89121cd2f4bd131c2393
    kafka-broker br3 encoding GPB-compact
    kafka-topic try2
  destination-group 4
    filter file /bootflash/parser.json md5 497bead9dfbe89121cd2f4bd131c2393
    kafka-broker br4 encoding GPB
    kafka-topic try3
  destination-group 5
    filter file /bootflash/parser.json md5 497bead9dfbe89121cd2f4bd131c2393
    kafka-broker br5 encoding JSON
    kafka-topic try4
  destination-group 100
    ip address 172.25.238.13 port 50070 protocol gRPC encoding GPB
  destination-group 101
    ip address 172.25.238.13 port 50071 protocol HTTP encoding JSON
  destination-group 103
    ip address 172.25.238.13 port 50072 protocol gRPC encoding GPB-compact
  destination-group 600
    host 172.19.216.78 port 50012 protocol HTTP encoding JSON
      proxy 173.36.240.173 port 80
    host 2001:0db8:85a3:0000:0000:8a2e:0370:7334 port 50013 protocol gRPC encoding GPB
      certificate trustpoint trustpoint2 foo.test.google.fr
    host sjc-vinci-ucs10 port 50061 protocol UDP encoding JSON
    host tm-ucs-1 port 50010 protocol gRPC encoding GPB
      grpc-async
      proxy proxy-wsa.esl.cisco.com port 80
  sensor-group 1
    data-source DME
    path sys/fm depth unbounded
  sensor-group 2
    data-source NX-API
    path "show environment power"
  sensor-group 3
    data-source NATIVE
    path mac-all
    path rib
  sensor-group 4
    path sys/ospf depth unbounded
  sensor-group 100
    data-source NX-API
    path "show system internal flash"
  sensor-group 103
    path sys/intf depth unbounded
  sensor-group 600
    path sys/intf depth unbounded
  subscription 1
    dst-grp 1
    dst-grp 2
    snsr-grp 1 sample-interval 10000
  subscription 2
    dst-grp 2
    snsr-grp 2 sample-interval 15000
  subscription 3
    dst-grp 3
    snsr-grp 3 sample-interval 0
  subscription 4
    dst-grp 4
    snsr-grp 4 sample-interval 12000
  subscription 5
    dst-grp 5
  subscription 100
    dst-grp 100
    snsr-grp 100 sample-interval 10000
  subscription 103
    dst-grp 103
    snsr-grp 103 sample-interval 0
  subscription 600
    dst-grp 600
    snsr-grp 600 sample-interval 10000

----- Disable feature. --------------
no feature telemetry

**Comment by jay** [comment]
Sorry but this isn't enough information. We need a small self-contained example to reproduce. Also you posted one of the proxy passwords. I removed it via edit but these issues are sent out publicly so I suggest change the password.

**Comment by bagder** [comment]
Without a way to reproduce in our ends, we can only help you debug this problem on your own: I advice you rebuild your libcurl and keep all the debug symbols, then run it again and do a new stack trace when it crashes. But you also need to explain to us how you're using libcurl. This is FTP isn't it?

**Comment by bagder** [comment]
Reporter stopped responding.
