### ISSUE TITLE
curl.1 problem

### ISSUE THREAD

**Issue by MelnikovAG** [curl/curl#7596]
bug

**Comment by bagder** [comment]
Please explain in detail what's wrong!

**Comment by MelnikovAG** [comment]
> Пожалуйста, объясните подробно, что случилось!

дорабатывая систему для потока информации, в стади теста, провожу настройки,  это происшествие не должно влиять на рабочие процессы и надеюсь на  сотрудничество,  да современные технологи совершенствуются и я, думаю, что и вы работаете для этого

**Comment by MelnikovAG** [comment]
решение за вами,  как дальше будем совершенствовать новые технологи

**Comment by gvanem** [comment]
@MelnikovAG Напишите что-нибудь толковое на английском. Ты робот?

**Comment by jay** [comment]
English please
