### ISSUE TITLE
Compiling curl-7.78.0 in AIX 7.1

### ISSUE THREAD

**Issue by avalosbal** [curl/curl#7620]
./configure --with-openssl

configure: error: Cannot find a type to use in place of in_addr_t

### curl/libcurl version

curl-7.78.0

### operating system

AIX bydbha02 1 7 00CB7FC74C00

The interesting thing that I successfully compiled on two other AIX systems with same OS level.

**Comment by jay** [comment]
please attach config.log

**Comment by bagder** [comment]
@avalosbal, on these systems what does the documentation say the `inet_addr()` function returns? Ie what type does the function return. "man inet_addr" should say.

**Comment by avalosbal** [comment]
Hi Daniel,

man inet_addr Subroutine
Purpose
       Converts Internet addresses to Internet numbers.
Library
       Standard C Library (libc.a)
Syntax
       #include <sys/socket.h>
       #include <sys/socketvar.h>
       #include <netinet/in.h>
       #include <arpa/inet.h>
       in_addr_t inet_addr ( CharString)
       register const char *CharString;Description
       The inet_addr subroutine converts an ASCII string containing a valid Internet address using       dot notation into an Internet address number typed as an unsigned integer value. An example       of dot notation is 120.121.5.123. The inet_addr subroutine returns an error value if the       Internet address notation in the ASCII string supplied by the application is not valid.
       Note: Although they both convert Internet addresses in dot notation to Internet numbers, the       inet_addr subroutine and inet_network process ASCII strings differently. When an application       gives the inet_addr subroutine a string containing an Internet address value without a       delimiter, the subroutine returns the logical product of the value represented by the string       and 0xFFFFFFFF. For any other Internet address, if the value of the fields exceeds the       previously defined limits, the inet_addr subroutine returns an error value of -1.
       When an application gives the inet_network subroutine a string containing an Internet       address value without a delimiter, the inet_network subroutine returns the logical product       of the value represented by the string and 0xFF. For any other Internet address, the       subroutine returns an error value of -1 if the value of the fields exceeds the previously       defined limits.
       All applications containing the inet_addr subroutine must be compiled with the _BSD macro       set to a specific value. Acceptable values are 43 and 44. In addition, all socket       applications must include the BSD libbsd.a library.
       Sample return values for each subroutine are as follows:
Application String              inet_addr Returns               inet_network Returns       0x1234567890abcdef              0x090abcdef 0xFFFFFFFF (= -1)   0x000000ef 0x0000ef00       0x1234567890abcdef.             0xFFFFFFFF (= -1)               0x00010203       256.257.258.259
       The ASCII string for the inet_addr subroutine must conform to the following format:
       string::=  field  |  field delimited_field^1-3  |  delimited_field^1-3       delimited_field::=  delimiter  field  |  delimiter       delimiter::=  .       field::=  0X  |  0x  |  0Xhexadecimal*  |  0x  hexadecimal*  |  decimal*  |  0  octal       hexadecimal::=  decimal  |a|b|c|d|e|f|A|B|C|D|E|F       decimal::=  octal  |8|9       octal::= 0|1|2|3|4|5|6|7
 Note:       1    ^n indicates n repetitions of a pattern.       2    ^n-m indicates n to m repetitions of a pattern.       3    * indicates 0 or more repetitions of a pattern, up to environmental limits.       4    The Backus Naur form (BNF) description states the space character, if one is used. Text            indicates text, not a BNF symbol.
       The inet_addr subroutine requires an application to terminate the string with a null       terminator (0x00) or a space (0x30). The string is considered invalid if the application       does not end it with a null terminator or a space. The subroutine ignores characters       trailing a space.
       The following describes the restrictions on the field values for the inet_addr subroutine:       Format            Field Restrictions (in decimal)       a            Value_a < 4,294,967,296       a.b            Value_a < 256; Value_b < 16,777,216       a.b.c            Value_a < 256; Value_b < 256; Value_c < 65536       a.b.c.d            Value_a < 256; Value_b < 256; Value_c < 256; Value_d < 256
Applications that use the inet_addr subroutine can enter field values exceeding these       restrictions. The subroutine accepts the least significant bits up to an integer in length,       then checks whether the truncated value exceeds the maximum field value. For example, if an       application enters a field value of 0x1234567890 and the system uses 16 bits per integer,       then the inet_addr subroutine uses bits 0 -15. The subroutine returns 0x34567890.
       Applications can omit field values between delimiters. The inet_addr subroutine interprets       empty fields as 0.
       Note:       1    The inet_addr subroutine does not check the pointer to the ASCII string. The user must            ensure the validity of the address in the ASCII string.       2    The application must verify that the network and host IDs for the Internet address            conform to either a Class A, B, or C Internet address. The inet_attr subroutine            processes any other number as a Class C address.
Parameters
       Item            Description       CharString            Represents a string of characters in the Internet address form.
Return Values
       For valid input strings, the inet_addr subroutine returns an unsigned integer value       comprised of the bit patterns of the input fields concatenated together. The subroutine       places the first pattern in the most significant position and appends any subsequent       patterns to the next most significant positions.
       The inet_addr subroutine returns an error value of -1 for invalid strings.
       Note: An Internet address with a dot notation value of 255.255.255.255 or its equivalent in       a different base format causes the inet_addr subroutine to return an unsigned integer value       of 4294967295. This value is identical to the unsigned representation of the error value.       Otherwise, the inet_addr subroutine considers 255.255.255.255 a valid Internet address.


Files
       Item            Description       /etc/hosts            Contains host names.       /etc/networks
        Contains network names.




Thanks

    On Monday, August 23, 2021, 01:58:08 PM PDT, Daniel Stenberg ***@***.***> wrote:  
 
 


@avalosbal, on these systems what does the documentation say the inet_addr() function returns? Ie what type does the function return. "man inet_addr" should say.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by avalosbal** [comment]
Here is the config.log


    On Monday, August 23, 2021, 11:33:07 AM PDT, Jay Satiro ***@***.***> wrote:  
 
 


please attach config.log

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bagder** [comment]
There's no log here!

**Comment by avalosbal** [comment]
On Monday, August 23, 2021, 03:02:23 PM PDT, Daniel Stenberg ***@***.***> wrote:  
 
 


There's no log here!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jay** [comment]
Try attaching it through the web interface.

**Comment by avalosbal** [comment]
[config.log](https://github.com/curl/curl/files/7035234/config.log)

**Comment by avalosbal** [comment]
The version of gcc on the systems that worked:
gcc -v
Using built-in specs.
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,java --prefix=/opt/freeware --enable-threads --enable-version-specific-runtime-libs --host=powerpc-ibm-aix6.1.0.0 --target=powerpc-ibm-aix6.1.0.0 --build=powerpc-ibm-aix6.1.0.0 --disable-libjava-multilib
Thread model: aix
gcc version 4.2.0


-----------------------------------
On the system that did not compiled:

 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/lto-wrapper
Target: powerpc-ibm-aix6.1.1.0
Configured with: ../gcc-6.3.0/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit --enable-bootstrap --host=powerpc-ibm-aix6.1.1.0
Thread model: aix
gcc version 6.3.0 (GCC)

**Comment by jay** [comment]
There seems to be some conflict on your system between netinet/in.h and sys/socket.h. both exist but HAVE_NETINET_IN_H is not defined since there are build errors when detecting it

~~~
configure:30822: checking for netinet/in.h
configure:30822: gcc -c -Werror-implicit-function-declaration -O2 -Wno-system-headers    conftest.c >&5
In file included from conftest.c:91:0:
/usr/include/netinet/in.h:542:8: error: redefinition of 'struct sockaddr'
 struct sockaddr {
        ^~~~~~~~
In file included from conftest.c:77:0:
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/include-fixed/sys/socket.h:320:8: note: originally defined here
 struct sockaddr {
        ^~~~~~~~
~~~

despite that other tests also have a similar failure, netinet/in.h is included from some other include but sys socket has already defined sockaddr

**Comment by avalosbal** [comment]
As I indicated earlier, on the system that works, gcc version is 4.2.0; the one that fails has gcc version 6.3.0.

Different paths:
curl works!
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.2.0/include/sys #
ignal.h  types.h   wait.h

curl not working
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.1.0/6.3.0/include-fixed/sys
dir.h        param.h      socket.h     types.h
localedef.h  signal.h     times.h      wait.h

**Comment by jay** [comment]
This seems to be a problem with your build environment and I can't think of a way we could work around it in our configure script.

**Comment by avalosbal** [comment]
Only difference that I see in our environment is the different versions of gcc, everything else is the same. Same power architecture, same OS level.

**Comment by rsbeckerca** [comment]
@avalosbal Are you potentially including gcc 4.2 header files while using gcc 6.3 compilers? That will not work correctly.

**Comment by avalosbal** [comment]
I am not making any changes to any other files.

I am not including any gcc 4.2 header files on the machine that has gcc 6.3. I am just doing the same ./configure --with-openssl on both the gcc 4.2 and the gcc 6.3 machines.

**Comment by bagder** [comment]
This seems to be a problem with your build environment. We cannot act on this. We can help you work on it, but then you need to drive it.

**Comment by avalosbal** [comment]
What do I need to do on the gcc 6.3.0 environment?

Thanks

**Comment by bagder** [comment]
@avalosbal make sure that the include files can be used

**Comment by avalosbal** [comment]
Ok. Can you provide the steps I need to do?
Thanks

**Comment by jay** [comment]
This is a problem with your development environment that in my opinion is out of scope as a curl issue. https://gcc.gnu.org/bugs/

**Comment by bagder** [comment]
I'm closing this issue as the signs are pointing to a compiler installation/setup issue.
