### ISSUE TITLE
Basic auth gets dropped sometimes in >=7.76.1 when multiple urls are provided

### ISSUE THREAD

**Issue by syslaila** [curl/curl#7622]
Initial issue: https://github.com/mamba-org/mamba/issues/1132

In an internal setup, we have a server with multiple endpoints that require basic auth for access purposes. An example call is:

`curl https://:$TOKEN@host/url`

When using curl v. 7.75.0, we didn't have any issues curl'ing multiple urls: 
`curl -vv -I https://:$TOKEN@host/url1 https://:$TOKEN@host/url2 https://:$TOKEN@host/url3`
where TOKEN = JWT token (https://en.wikipedia.org/wiki/JSON_Web_Token#Structure

When using curl v. 7.76.0, we started getting random 401 errors for some of the urls - meaning we did not get any "`Authorization`" header in the request. The only header keys we would get for those requests were: `headerKeys: [Accept Host Accept-Encoding Content-Type]`

We were also able to find that this issue only comes up when the connection is being re-used. This is not to say that if the connection was reused, the auth header is dropped, but more like -> we never saw this issue come up unless the connection was reused.

Notably, we saw this in the logs:

for a request that got a 401 response:
```
* Connection #4 to host localhost left intact
* Couldn't find host localhost in the (nil) file; using defaults
* Found bundle for host localhost: 0x7fbd8fd4a640 [serially]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Transfer was pending, now try another
> GET /service/noarch/repodata.json HTTP/1.1
Host: localhost:8080
Accept: */*
Accept-Encoding: gzip, deflate, compress, identity
Content-Type: application/json
```

and for a successful, non 401, request:

```
* Couldn't find host localhost in the (nil) file; using defaults
* Found bundle for host localhost: 0x7f8fe0e08f30 [serially]
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user ''
> GET /service/noarch/test-package-0.1-0.tar.bz2 HTTP/1.1
Host: localhost:8080
Authorization: Basic KG5pbCk6dGVzdA==
Accept: */*
```

It's interesting to see * Server auth using Basic with user '' show up in the successful one, but not in the failing one. And that seems to be the case for all the logs I have.

### I did this

curl -vv -I https://:$TOKEN@host/<url1> https://:$TOKEN@host/<url2> https://:$TOKEN@host/<url3>

### I expected the following

The "Authorization" header key present in all requests, but sometimes it was not

### curl/libcurl version

[curl -V output]
curl 7.76.1
the following version seems to work: 7.75.0 - we were unable to reproduce the issue on this libcurl version

### operating system

A few code snippets and results: 
![image (2)](https://user-images.githubusercontent.com/25724655/130644556-d2a4e706-1069-4377-9db4-7d342ce136e2.png)
![image (3)](https://user-images.githubusercontent.com/25724655/130644580-f4d9489f-d614-4caf-a2e4-b5ec7fd81a85.png)
Note - some of the requests have an empty "Authorization" header

**Comment by bagder** [comment]
This looks like a problem with re-used connections we've fixed already. I just fail at finding the exact fix right now. Any chance you can retry with the latest release to verify?

**Comment by syslaila** [comment]
Thanks @bagder for the quick reply, we were able to test with a few curls with the latest version and we only got 200s!
