### ISSUE TITLE
"--resolve" argument partly ignored

### ISSUE THREAD

**Issue by olebru** [curl/curl#7627]
### I did this
curl --resolve google.com:443:111.222.111.222 https://google.com:443 -v
### I expected the following
An error since the IP injected to the dns cache via --resolve, 111.222.111.222 should not respond on port 443.

Here is the first part of the output where it states incorrectly that a connection has been made to 111.222.111.222:443: 

* Added google.com:443:111.222.111.222 to DNS cache
* Hostname google.com was found in DNS cache
*   Trying 111.222.111.222...
* TCP_NODELAY set
* Connected to google.com (111.222.111.222) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
... Shortened.
### curl/libcurl version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
### operating system
OSX 11.4 Big Sur

**Comment by bagder** [comment]
I think you're wrong and that there indeed is a server there.

I adjusted the command line to work with a publicly accessible HTTPS server and it works as advertised:
~~~
$ curl --resolve google.com:443:151.101.2.49 https://google.com -vk
... [success] ...
$ curl -V
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

**Comment by olebru** [comment]
Hi, I should have included more of the command output. Any IP entered in the resolve string will end up with a connection to google.com's servers. (As seen by the certificate presented from the server) here is another example using 1.2.3.4 as the injected IP:

curl --resolve google.com:443:1.2.3.4 https://google.com:443 -v 

* Added google.com:443:1.2.3.4 to DNS cache
* Hostname google.com was found in DNS cache
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to google.com (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.google.com
*  start date: Jul 26 01:37:23 2021 GMT
*  expire date: Oct 18 01:37:22 2021 GMT
*  subjectAltName: host "google.com" matched cert's "google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.

**Comment by bagder** [comment]
Then something is very strange in your setup. The same version and command line on my mac:
~~~
$ curl --resolve google.com:443:1.2.3.4 https://google.com:443 -v
* Added google.com:443:1.2.3.4 to DNS cache
* Hostname google.com was found in DNS cache
*   Trying 1.2.3.4...
* TCP_NODELAY set
[stuck for some time]
* Connection failed
* connect to 1.2.3.4 port 443 failed: Operation timed out
* Failed to connect to google.com port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to google.com port 443: Operation timed out
~~~

**Comment by olebru** [comment]
Hm, yes agreed, your output I was I was expecting.

**Comment by olebru** [comment]
Changed to a different network and got the expected result as well. This has to be related to our network. Thanks for the swift reply! Closing.
