### ISSUE TITLE
HTTPs connection dropped on SSL_ERROR_WANT_WRITE when using pipelining

### ISSUE THREAD

**Issue by amevaidy** [curl/curl#764]
### I did this

Making pipelined HTTPs requests to a web server with a custom HTTPs client built on top of libcurl with openssl for TLS/SSL layer.
Whenever SSL_write() returns SSL_ERROR_WANT_WRITE or SSL_ERROR_WANT_READ, the connection gets broken and a new connection is established.
1. Create a multi-handle with the following settings:
   CURLMOPT_MAX_HOST_CONNECTIONS = 1
   CURLMOPT_PIPELINING = 1
   CURLMOPT_MAX_PIPELINE_LENGTH = 50
2. Create 50 easy curl handles for making HTTPs requests to the _same_ HTTPs web server
3. The issue will be easier to reproduce if TLS renegotiation is not disabled on both sides
4. Add all easy handles to the multi-handle
5. Run the multi-handle to completion
6. Simultaneously take a packet capture at the client side

The packet capture shows that a connection gets established, some requests are completed on it, then it is RSTed from the client side and a fresh connection is established.
In effect, several connections can get established and torn down before all requests can be completed
### I expected the following

A single TCP connection is established to the web server and all requests are pipelined over it
### curl/libcurl version
1. Version details ((HTTPs client side)
       libcurl: 7.47.1
       Openssl: 1.0.1m  

[curl -V output perhaps?]
### operating system

Platform: FreeBSD 9.2 64 bit
### Impact

Several thousand clients connect to a single web server for our business application.
The client and server are designed to maintain a single persistent connection for a long time and pipeline all requests over HTTPs.
Each connection setup and tear-down is an expensive operation for the server.
The existing behaviour results in too many connection setup/teardown operations thus overloading the server.
### Analysis
1. The libcurl implementation uses non-blocking sockets with multiple requests pipelined over the same connection.
2. It maintains a two-way association between requests and connections (sockets)
3. It maintains queues of reader and writer requests and the socket is “awarded” in FIFO order to each request to perform its pending read/write operation
4. If a read/write operation did not complete because the socket was not ready (EWOULDBLOCK), the socket can still be taken away from the request and awarded to the next one in queue
   - An EWOULDBLOCK in the “DO” phase results in an HTTPs request directly moving to the “DONE” phase
   - The next request in the queue can then be awarded the socket
5. For plain HTTP, this has no functional impact; the request that could not complete gets pushed  to the back of the queue and will be retried when its turn comes next
6. However, this behaviour is incorrect from OpenSSL PoV due to the way SSL_write() works (https://www.openssl.org/docs/manmaster/ssl/SSL_write.html)
   
   "If the underlying BIO is non-blocking, SSL_write() will also return, when the underlying BIO could not satisfy the needs of SSL_write() to continue the operation. In this case a call to SSL_get_error with the return value of SSL_write() will yield SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE …… When an SSL_write() operation has to be repeated because of SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE, it must be repeated with the same arguments.”
7. Obviously, after an SSL_ERROR_WANT_XXX, due to lib curl’s behaviour in point (5), the SSL_write(…) gets invoked on a different request (i.e. with different arguments) resulting in a write failure that leads to the connection being aborted.
### Suggested Fix

Introduce a “DOING” phase for HTTPs. I have prototype code for this fix and it seems to be working fine for our use-case.

``` diff
--- curl-7.47.1.orig/lib/http.h 2016-02-02 15:02:44.000000000 -0800
+++ curl-7.47.1/lib/http.h      2016-02-26 01:51:46.000000000 -0800
@@ -77,6 +77,7 @@

/* protocol-specific functions set up to be called by the main engine */
CURLcode Curl_http(struct connectdata *conn, bool *done);
+CURLcode Curl_http_doing(struct connectdata *conn, bool *done);
CURLcode Curl_http_done(struct connectdata *, CURLcode, bool premature);
CURLcode Curl_http_connect(struct connectdata *conn, bool *done);
CURLcode Curl_http_setup_conn(struct connectdata *conn);

--- curl-7.47.1.orig/lib/http.c 2016-02-04 06:17:13.000000000 -0800
+++ curl-7.47.1/lib/http.c      2016-03-03 10:18:38.000000000 -0800
@@ -135,7 +135,7 @@
  ZERO_NULL,                            /* do_more */
  Curl_http_connect,                    /* connect_it */
  https_connecting,                     /* connecting */
-  ZERO_NULL,                            /* doing */
+  Curl_http_doing,                      /* doing */
  https_getsock,                        /* proto_getsock */
  http_getsock_do,                      /* doing_getsock */
  ZERO_NULL,                            /* domore_getsock */
@@ -1754,6 +1754,10 @@
  return result;
}

+CURLcode Curl_http_doing(struct connectdata *conn, bool *done)
+{
+  return Curl_http(conn, done);
+}
/*
 * Curl_http() gets called from the generic Curl_do() function when a HTTP
 * request is to be performed. This creates and sends a properly constructed
@@ -2431,10 +2435,14 @@
                                    &data->info.request_size, 0, FIRSTSOCKET);
      if(result)
        failf(data, "Failed sending POST request");
-      else
-        /* setup variables for the upcoming transfer */
-        Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE, &http->readbytecount,
-                            -1, NULL);
+      else {
+        if((conn->handler->flags & PROTOPT_SSL) && (data->info.request_size == 0))
+          *done = FALSE;
+        else
+          /* setup variables for the upcoming transfer */
+          Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE, &http->readbytecount,
+                             -1, NULL);
+      }
      break;
    }

@@ -2501,11 +2509,15 @@
                                  &data->info.request_size, 0, FIRSTSOCKET);
    if(result)
      failf(data, "Failed sending POST request");
-    else
-      /* setup variables for the upcoming transfer */
-      Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
-                          &http->readbytecount, FIRSTSOCKET,
-                          &http->writebytecount);
+    else {
+        if((conn->handler->flags & PROTOPT_SSL) && (data->info.request_size == 0))
+          *done = FALSE;
+        else
+          /* setup variables for the upcoming transfer */
+          Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
+                              &http->readbytecount, FIRSTSOCKET,
+                              &http->writebytecount);
+    }

    if(result) {
      Curl_formclean(&http->sendit); /* free that whole lot */
@@ -2556,11 +2568,15 @@
                                  &data->info.request_size, 0, FIRSTSOCKET);
    if(result)
      failf(data, "Failed sending PUT request");
-    else
-      /* prepare for transfer */
-      Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
-                          &http->readbytecount, postsize?FIRSTSOCKET:-1,
-                          postsize?&http->writebytecount:NULL);
+    else {
+        if((conn->handler->flags & PROTOPT_SSL) && (data->info.request_size == 0))
+          *done = FALSE;
+        else
+          /* prepare for transfer */
+          Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
+                              &http->readbytecount, postsize?FIRSTSOCKET:-1,
+                              postsize?&http->writebytecount:NULL);
+    }
    if(result)
      return result;
    break;
@@ -2715,10 +2731,14 @@

    if(result)
      failf(data, "Failed sending HTTP POST request");
-    else
-      Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
-                          &http->readbytecount, http->postdata?FIRSTSOCKET:-1,
-                          http->postdata?&http->writebytecount:NULL);
+    else {
+        if((conn->handler->flags & PROTOPT_SSL) && (data->info.request_size == 0))
+          *done = FALSE;
+        else
+          Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE,
+                              &http->readbytecount, http->postdata?FIRSTSOCKET:-1,
+                              http->postdata?&http->writebytecount:NULL);
+    }
    break;

  default:
@@ -2732,11 +2752,15 @@

    if(result)
      failf(data, "Failed sending HTTP request");
-    else
-      /* HTTP GET/HEAD download: */
-      Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE, &http->readbytecount,
-                          http->postdata?FIRSTSOCKET:-1,
-                          http->postdata?&http->writebytecount:NULL);
+    else {
+        if((conn->handler->flags & PROTOPT_SSL) && (data->info.request_size == 0))
+          *done = FALSE;
+        else
+          /* HTTP GET/HEAD download: */
+          Curl_setup_transfer(conn, FIRSTSOCKET, -1, TRUE, &http->readbytecount,
+                              http->postdata?FIRSTSOCKET:-1,
+                              http->postdata?&http->writebytecount:NULL);
+    }
  }
  if(result)
    return result;
```

**Comment by jay** [comment]
If I understand this correctly you're saying that if the non-blocking socket would/could block sending a request, and as a result we've received `SSL_ERROR_WANT_` then that socket must be effectively tied to that transfer until that condition is resolved? Does your fix address this? You'll have to forgive me, I'm not familiar with the pipelining code, but I notice nobody else has given any feedback in 2 months. I know there's a [`writechannel_inuse`](https://github.com/curl/curl/blob/curl-7_49_1/lib/urldata.h#L1015-L1016) in `struct connectdata`, I thought it was supposed to take care of situations like that. In other words the write channel is in use by easy handle foo until it resends that data? Maybe someone more experienced in this area has some comments on this?

**Comment by bagder** [comment]
I haven't responded to this issue because I haven't spent enough time to analyze this problem and suggested solution. The pipelining code in libcurl is unfortunately not rock solid, getting tests for it is really tedious due to its timing sensitivity and as we don't have that terribly many people using pipelining (or at least suffering from its problems) it has not risen very high on my own agenda.
