### ISSUE TITLE
HSTS doc links lead to 404

### ISSUE THREAD

**Issue by jschauma** [curl/curl#7650]
### I did this

The URL included in the HSTS file does not work.

```
$ curl --hsts /tmp/f https://www.netmeister.org
$ cat /tmp/f
# Your HSTS cache. https://curl.se/docs/hsts.html
# This file was generated by libcurl! Edit at your own risk.
.www.netmeister.org "20220831 02:54:35"
$ curl -s -I https://curl.se/docs/hsts.html | head -1
HTTP/2 404 
```

### I expected the following

Something similar to https://daniel.haxx.se/blog/2020/11/03/hsts-your-curl/, perhaps?

### curl/libcurl version

curl 7.77.0 (x86_64-apple-darwin20.4.0) libcurl/7.77.0 (SecureTransport) OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.5
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

macOS 11.5.2 with curl from homebrew as above

**Comment by bagder** [comment]
Oops. Thanks for pointing this out. Will fix!

**Comment by bagder** [comment]
Fixed now, the page is generated from [this doc](https://github.com/curl/curl/blob/master/docs/HSTS.md).

**Comment by jschauma** [comment]
Great, thanks for the quick fix!
