### ISSUE TITLE
getinfo with CURLINFO_CONTENT_LENGTH_DOWNLOAD return an error value 

### ISSUE THREAD

**Issue by jaykizhou** [curl/curl#7655]
getinfo with CURLINFO_CONTENT_LENGTH_DOWNLOAD return an error value if  a response message is received with both a Transfer-Encoding and a Content-Length header field.

response message:

```
HTTP/1.1 200 OK
Host: ******
Date: Wed, 01 Sep 2021 11:11:52 +0800
Content-Length: 32
Transfer-Encoding: chunked
Content-type: text/html; charset=UTF-8

139e
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.......
```

CURLINFO_CONTENT_LENGTH_DOWNLOAD  return 32，but it is wrong, I expected -1.

**Comment by bagder** [comment]
You didn't say which version that is using, but I believe this was fixed very recently in 8a16e54c0cc71e

**Comment by jaykizhou** [comment]
Tks,  I use 7.44.0

**Comment by bagder** [comment]
Believed to have been fixed already.
