### ISSUE TITLE
Support secure enclaves by referencing key-pairs by name instead of passing actual key(s)

### ISSUE THREAD

**Issue by pprindeville** [curl/curl#7659]
Mobile platforms (iOS, Android) have hardware backed keystores in the TEE (trusted execution environment/Secure Enclaves in ARM nomenclature).  Therefore private keys aren't directly accessible, and key operations (creation, deletion, encryption, decryption, signing, etc.) require pushing the data to be operated on and the key identifier (a name in string representation, in this case) into the Strongbox or Keystore subsystem.

In these environments, `CURLOPT_SSLKEY` or `CURLOPT_SSLKEY_BLOB` isn't an option.

Proposing a new option: `CURLOPT_SSLKEY_HANDLE` (since other environments like TPM, etc.) might use other handles for keys like unsigned integers, etc. as well.

**Comment by pprindeville** [comment]
Will provide a PR in a couple of days for review.

**Comment by bagder** [comment]
Thanks, but this description sounds as if you're asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!
