### ISSUE TITLE
curl CERT_TRUST_REVOCATION_STATUS_UNKNOWN on Windows

### ISSUE THREAD

**Issue by ahmedyarub** [curl/curl#7664]
### I did this
Tried to connect to a Kubernetes cluster with SSL certificate validation https://github.com/kubernetes-client/c/blob/master/kubernetes/src/apiClient.c#L380

### I expected the following
Works on all operating systems, but it didn't work on Windows.

### But had the following
CertGetCertificateChain trust error CERT_TRUST_REVOCATION_STATUS_UNKNOWN

### I worked around it by
Disabling SSL verification on Windows

### curl/libcurl version
7.78.0 (from vcpkg)

[curl -V output]
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: 2017-11-14, security patched: 2019-11-05
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

Note: this is not the same curl.exe built by vcpkg.

### operating system
Windows 11 22000.168

**Comment by bagder** [comment]
> Note: this is not the same curl.exe built by vcpkg.

Why are you showing the version output of a different curl than the one you used?

**Comment by ahmedyarub** [comment]
> > Note: this is not the same curl.exe built by vcpkg.
> 
> Why are you showing the version output of a different curl than the one you used?

Because I thought that you would be interested in the other details. That doesn't seem to be the case though...
Anyways it's the one that ships with vcpkg. Here is the building script: https://github.com/microsoft/vcpkg/blob/master/ports/curl/portfile.cmake

**Comment by bagder** [comment]
> Because I thought that you would be interested in the other details.

Unfortunately those details are very specific only for that other build and the one you use can use an entirely different set of features and versions.

**Comment by ahmedyarub** [comment]
OK then I'll build the executable files together and send you the details soon.

**Comment by jay** [comment]
> https://github.com/kubernetes-client/c/blob/master/kubernetes/src/apiClient.c#L380

The line you referenced uses the master pointer which means it's going to change. As of today it points to disabling SSL verify. Are you reporting that even when SSL verification is disabled there is still a revocation check? That should not happen. However if you are reporting just that the revocation check can't take place with your certificate chain then you can [disable](https://curl.se/docs/manpage.html#--ssl-no-revoke) or [soften](https://curl.se/docs/manpage.html#--ssl-revoke-best-effort) the check.

**Comment by ahmedyarub** [comment]
> > https://github.com/kubernetes-client/c/blob/master/kubernetes/src/apiClient.c#L380
> 
> The link you referenced uses the master pointer which means the line is going to change. As of today it points to disabling SSL verify. Are you reporting that even when SSL verification is disabled there is still a revocation check? That should not happen. However if you are reporting just that the revocation check can't take place with your certificate chain then you can [disable](https://curl.se/docs/manpage.html#--ssl-no-revoke) (libcurl: [CURLSSLOPT_NO_REVOKE](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html)) or [soften](https://curl.se/docs/manpage.html#--ssl-revoke-best-effort) (libcurl: [CURLSSLOPT_REVOKE_BEST_EFFORT](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html)) the check.

Hi Jay thank you for joining the conversation. Revocation check fails only when SSL verification is enabled. I vaguely remember testing the other two options and they didn't work. I'll be testing them again today.
Regardless of that, how can I help debugging this problem? Do you want me to conduct some specific tests?

**Comment by jay** [comment]
What is the output of `printf("%s\n", curl_version());`?

**Comment by ahmedyarub** [comment]
Looks like this has been a temporary issue related to a Windows Insider version. It fixed itself.

**Comment by kmahyyg** [comment]
> Looks like this has been a temporary issue related to a Windows Insider version. It fixed itself.

Unfortunately, this issue still exist on Windows Server 2022 now (Build 20348). I've no idea how to get it fixed. Even if I trusted my CA and intermediate CA, and all certs does NOT contains a CRL distribution point or OCSP server, it still tells me the same error like yours.

**Comment by jay** [comment]
Does it work if you relax the settings: [--ssl-revoke-best-effort](https://curl.se/docs/manpage.html#--ssl-revoke-best-effort) (libcurl: [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) CURLSSLOPT_REVOKE_BEST_EFFORT)

**Comment by kmahyyg** [comment]
> Does it work if you relax the settings: [--ssl-revoke-best-effort](https://curl.se/docs/manpage.html#--ssl-revoke-best-effort) (libcurl: [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) CURLSSLOPT_REVOKE_BEST_EFFORT)

This should work on curl itself. I am facing with a third-party app linked against libcurl, so I guess I need to work on my own to hook something. Thanks for your help.
