### ISSUE TITLE
configure: disable HSTS support

### ISSUE THREAD

**Issue by MAntoniak** [curl/curl#7669]
I download a curl library from daily snapshots. I am trying to set up a build with openssl but no hsts support.
Looks like the use of:
```
./configure
./configure --disable-hsts
./configure --enable-hsts=no
```
gives the same result:
```
   curl version: 7.79.0-20210903
...
   HSTS: enabled (--disable-hsts)
```
I'm not sure if this is correct behavior? What am I missing?

**Comment by bagder** [comment]
I can reproduce, but I haven't yet figured out *why* it does this...
