### ISSUE TITLE
How can I add "curl -d --data-binary" option   by libcurl setting,thanks

### ISSUE THREAD

**Issue by polyGithub** [curl/curl#767]
as:.
curl -X POST --data-binary @/mnt/hgfs/share2ubuntu/data/train_images/airplanes/image_0001.jpg  http://localhost:4212/index/searcher

how can I to set?
        curl = curl_easy_init();  
        curl_easy_setopt(curl, CURLOPT_URL, POSTURL);  
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, POSTFIELDS);  
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_data);  
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, fptr);  
        curl_easy_setopt(curl, CURLOPT_POST, 1);  
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1);  
        curl_easy_setopt(curl, CURLOPT_HEADER, 1);  
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);  
        curl_easy_setopt(curl, CURLOPT_COOKIEFILE, "/Users/zhu/CProjects/curlposttest.cookie");  
        res = curl_easy_perform(curl);  

thank you very many for you surport

**Comment by bagder** [comment]
Please send questions on how to use libcurl to the curl-library mailing list. The `--libcurl`command line option helps you to show what code the corresponding curl command line would use.

You can send the file contents with `CURLOPT_POSTFIELDS` or use a read callback set with `CURLOPT_READFUNCTION`. You pick.

**Comment by polyGithub** [comment]
by my test:
#include <stdio.h>
#include <curl/curl.h>
#include <unistd.h>
static size_t get_return(void *ptr, size_t size, size_t nmemb, void *stream)
{
 printf("%s\n",ptr);
 printf("%d\n",nmemb);
 return nmemb;
}

static size_t post_return(void *ptr, size_t size, size_t nmemb, void *stream)
{
 printf("%s\n",ptr);
 printf("%d\n",nmemb);
 return nmemb;
}

bool getUrl(void)
{
    CURL *curl;
    CURLcode res;
    struct curl_slist *headers = NULL;
    headers = curl_slist_append(headers, "Accept: Agent-007");
    curl = curl_easy_init();    // 初始化
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);// 改协议头
        curl_easy_setopt(curl, CURLOPT_URL,"http://127.0.0.1:4212/index/imageIds");
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, get_return);  
        res = curl_easy_perform(curl);   // 执行
        if (res != 0) {
            curl_slist_free_all(headers);
            curl_easy_cleanup(curl);
        }
        return true;
    }
}

bool postUrl( char* fileimage)
{
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, fileimage);    // 指定post内容
        curl_easy_setopt(curl, CURLOPT_URL, "http://localhost:4212/index/images/3");   // 指定url
	curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, post_return);  
        res = curl_easy_perform(curl);
        curl_easy_cleanup(curl);
    }
    return true;
}
int main(int argc, char *argv[])
{
    postUrl(argv[1]);    
    getUrl(); 
}

运行我的测试程序如下（run myself test program）
root@poly:build# ./my_curl 
{"type":"MISFORMATTED_REQUEST"}
32
{"image_ids":[3,1,2],"type":"INDEX_IMAGE_IDS"}
47

在终端运行命令如下：（run curl command by as follows）
root@poly:.libs# curl -X PUT --dblata-binary @/home/poly/pastec/build/image_0003.jpg http://localhost:4212/index/images/3
{"image_id":3,"nb_features_extracted":979,"type":"IMAGE_ADDED"}


normal status should be "type":"IMAGE_ADDED",but do my test progrom, respose "type":"MISFORMATTED_REQUEST"
