### ISSUE TITLE
continue-at and remote-header-name cannot be used together

### ISSUE THREAD

**Issue by c-zx** [curl/curl#7670]
### I did this
`curl http://example.com/download?token=xxx -O -J -C -`, with existing partial file `example.zip`.

### I expected the following
curl resume the download.

### actual behavior
curl failed with:
> Warning: Failed to create the file example.zip: File
> Warning: exists
> curl: (23) Failed writing header

### curl/libcurl version

> curl 7.78.0 (x86_64-pc-linux-gnu) libcurl/7.78.0 OpenSSL/1.1.1l zlib/1.2.11 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.44.0
> Release-Date: 2021-07-21
> Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
> Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

> Linux archlinux 5.10.61-1-lts #1 SMP Fri, 27 Aug 2021 21:20:32 +0000 x86_64 GNU/Linux

**Comment by c-zx** [comment]
related: https://superuser.com/questions/1632477/curl-continue-and-remote-header-name-cannot-be-used-together

**Comment by c-zx** [comment]
This appears to be a known bug though:

> 4.2 -J with -C - fails
> 
>  When using -J (with -O), automatically resumed downloading together with "-C
>  -" fails. Without -J the same command line works! This happens because the
>  resume logic is worked out before the target file name (and thus its
>  pre-transfer size) has been figured out!
>  https://curl.se/bug/view.cgi?id=1169

**Comment by c-zx** [comment]
If fixing this bug requires too much work, perhaps considering add a warning when these arguments are used together?

**Comment by bagder** [comment]
> If fixing this bug requires too much work, perhaps considering add a warning when these arguments are used together?

I wouldn't object to such a warning.

**Comment by c-zx** [comment]
There is a possible(simple) fix:

When "-C -" and "-O -J" are used together, Instead of setting write head callback to get file descriptor, use HEAD method to get remote name. If succeeded, use it later in resume logic (to get file descriptor).

Drawback: one more connection caused more delay.(And it's probably not standard behavior)

**Comment by bagder** [comment]
Since this is already a known and documented issue, there's no point in keeping this issue open.

Fixing this problem will require a custom fix and probably needs to involve more than one HTTP request.
