### ISSUE TITLE
I got "error LNK2019: unresolved external symbol __imp_curl_global_init referenced" using a static-libcurl on windows10

### ISSUE THREAD

**Issue by flyinskyin2013** [curl/curl#7671]
### I did this
1. On window10, I build static-libcurl using vs2019 , then I get a lib(libcurl.lib) and header-files(like:curl.h).(I enable this macro BUILDING_LIBCURL)
2. I implement a other program using libcurl.
3. When I build it, then I get the the msg("error LNK2019: unresolved external symbol __imp_curl_global_init referenced").
4. After I add this "#define BUILDING_LIBCURL" to curl.h:4, then my program is ok.

### This is a mistake.
The reason of it why is that:
1. we get libcurl.lib with dllexport. but the curl.h don't have define BUILDING_LIBCURL and don't export curl_global_init .
2. so, when we use it, we will get above error.

### Suggestion
1. Insert a line like '#define BUILDING_LIBCURL' at the head of curl.h.

**Comment by bagder** [comment]
You need to define `CURL_STATICLIB` when you build to on Windows to use a static libcurl. Mentioned among other places in the FAQ: https://curl.se/docs/faq.html#Link_errors_when_building_libcur

**Comment by flyinskyin2013** [comment]
Thanks. 

It's my fault. I don't see the FAQ about it.
