### ISSUE TITLE
Can't compile ftpupload.c

### ISSUE THREAD

**Issue by sberlinux** [curl/curl#7684]
Can't compile ftpupload.c file

`g ++ -o program ftpupload.c`

[https://github.com/curl/curl/blob/master/docs/examples/ftpupload.c](https://github.com/curl/curl/blob/master/docs/examples/ftpupload.c)

I get the error:

```

ftpupload.c: In function ‘size_t read_callback(char*, size_t, size_t, void*)’:
ftpupload.c:57:50: error: invalid conversion from ‘void*’ to ‘FILE* {aka _IO_FILE*}’ [-fpermissive]
   size_t retcode = fread(ptr, size, nmemb, stream);
                                                  ^
In file included from ftpupload.c:22:0:
/usr/include/stdio.h:646:15: note:   initializing argument 4 of ‘size_t fread(void*, size_t, size_t, FILE*)’
 extern size_t fread (void *__restrict __ptr, size_t __size,
               ^~~~~
```
What exactly do I need to fix?

**Comment by bagder** [comment]
Use a C compiler to compile C. This is not a C++ example.

**Comment by sberlinux** [comment]
@bagder What command to write for Ubuntu 20.04.3 LTS?

**Comment by bagder** [comment]
gcc -o program ftpupload.c -lcurl
