### ISSUE TITLE
Protocol «file://» and path with spaces

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7686]
### I did this
Version 7.78.0_5:
curl.exe -o OutPut "file://C:\Te st\InPut"
curl: (3) URL using bad/illegal format or missing URL
### I expected the following
Version 7.77.0:
curl.exe -o OutPut "file://C:\Te st\InPut"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
I.e OK.
### curl/libcurl version
Last and previous COMPARING.
[curl -V output]
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd

compare with

curl 7.77.0 (x86_64-pc-win32) libcurl/7.77.0 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.43.0 libgsasl/1.10.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP Unicode UnixSockets zstd

### operating system
MS Windows 10-21H1, all updates.

**Comment by dfandrich** [comment]
URLs are not allowed to have spaces. They should be percent encoded to %20.
This used to be allowed but was tightened up in commit b67d3ba7.  This command
should work:

curl.exe -o OutPut "file://C:\Te%20st\InPut"

**Comment by 7-904-001-67-28** [comment]
Version 7.77.0 from 2021-05-26 works without «%20».  What happened?

**Comment by 7-904-001-67-28** [comment]
What about space in file name:
curl.exe -o OutPut "file://C:\Test\In%20Put"

**Comment by dfandrich** [comment]
Any spaces in a URL need to be encoded. Also, Windows file paths with their drive letters and backslashes map a bit weirdly to URL, but I think this is a more widely-compatible URL encoding for the last example: file:///C:/Test/In%20Put"

**Comment by 7-904-001-67-28** [comment]
I repeated the «wrong» command a few times and and it began to work.  Why?
curl.exe -o OutPut "file://C:\Test\In%20Put"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

This has been happening for a long time.  Perhaps a pause affects.  Can you fix this bug?

**Comment by dfandrich** [comment]
I doubt you tried exactly the same command with the same files with the same program several times and it suddenly began to work. curl supporting spaces in URLs only worked before by accident, and that bug was fixed to return an error on invalid URLs. That's the bug that was fixed. Use a proper URL and it will work.

**Comment by bagder** [comment]
As explained, spaces need to be encoded to be part of a URL for curl.

**Comment by gvanem** [comment]
Dan Fandrich wrote:

> curl.exe -o OutPut "file://C:\Te%20st\InPut"

What shell does this work with?
For me, only  a `curl.exe -o OutPut "file://C:\Te%%20st\InPut"` works. The `%` must be escaped.

**Comment by dfandrich** [comment]
I don't have a Windows system easily available for testing, but that command
works for me as-is from the wine shell. I thought literal percents only needed
doubling in Windows batch files.

**Comment by gvanem** [comment]
>  I thought literal percents only needed doubling in Windows batch files.

On the command-line too.

**Comment by dfandrich** [comment]
Wine's shell, at least, lets through percents that are unpaired or paired with
a nonexistent environment variable. Not sure if Windows does the same.
