### ISSUE TITLE
Couldn't open file with encoded space in name (very old bug)

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7687]
### I did this
With space:
curl.exe -o OutPut "file://C:\Test\In%20Put"
curl: (37) Couldn't open file C:\Test\In%20Put
### I expected the following
Without space:
curl.exe -o OutPut "file://C:\Test\InPut"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
I.e. OK.
### curl/libcurl version
Build 7.78.0_5
[curl -V output]
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10-21H1

**Comment by 7-904-001-67-28** [comment]
I've been renaming my files for a long time to avoid this mistake.

**Comment by 7-904-001-67-28** [comment]
With normal space, non-encoded:
curl.exe -o OutPut "file://C:\Test\In Put"
curl: (3) URL using bad/illegal format or missing URL

**Comment by bagder** [comment]
I cannot reproduce on Linux:
~~~shell
$ echo mooo  > /tmp/test\ me
$ curl file:///tmp/test%20me
mooo

**Comment by jay** [comment]
I can't reproduce this from the command prompt in Windows 7, with or without the drive letter in the path.

~~~
> curld file:///temp/test%20me
> curld file://x:/temp/test%20me
~~~

~~~
curl 7.79.0-DEV (i386-pc-win32) libcurl/7.79.0-DEV OpenSSL/1.1.1j nghttp2/1.43.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IPv6 Largefile NTLM SSL Unicode UnixSockets alt-svc
~~~

**Comment by bagder** [comment]
In Windows shells/batch files, `%` is often treated specially and requires it to be escaped (duplicated) to work. As mentioned by @gvanem in #7686: https://github.com/curl/curl/issues/7686#issuecomment-915856504

**Comment by bagder** [comment]
@7-904-001-67-28 does if work if you duplicate the percent?  Like this:

    curl.exe -o OutPut "file://C:\Test\In%%20Put"

**Comment by 7-904-001-67-28** [comment]
> does if work if you duplicate the percent?

It works with SINGLE percent, but crash in unpredictable moment.  Now I am using another program for that purpose, more specialized for local file operations.

**Comment by 7-904-001-67-28** [comment]
> In Windows shells/batch files, `%` is often treated specially and requires it to be escaped (duplicated) to work. As mentioned by @gvanem in #7686: [#7686 (comment)](https://github.com/curl/curl/issues/7686#issuecomment-915856504)

I use the PowerShell to work and command line console for error reporting.  I have not batch files of MS-DOS in reality.

**Comment by bagder** [comment]
> It works with SINGLE percent

You started this issue saying it doesn't work.

> but crashes in unpredictable moment

That's a new bug/description, What does "crashes" mean exactly?

**Comment by 7-904-001-67-28** [comment]
> What does "crashes" mean exactly?

«Crashes» means than error №37 appears and my script stops (and I have to figure out what to do next).
Sorry my English, please.  I am ashamed.

This is a very old mistake and I was just renaming the file to «TempFile» and back.

**Comment by bagder** [comment]
> «Crashes» means than error №37 appears 

I don't understand how you can say it works if it returns error 37. That would rather mean it doesn't work with one percent, doesn't it?

**Comment by jay** [comment]
AFAICT this is not a bug. OP is invoking curl via powershell script which may require different methods for escaping arguments and reading the standard streams. Also, I cannot reproduce from a powershell prompt. I can access `file://x:\temp\test%20me` and `file://x:/temp/test%20me`

**Comment by 7-904-001-67-28** [comment]
> I don't understand how you can say

Perhaps my English is to blame.  I was wroting, that my script works with SINGLE percent, but the error №37 appears in unpredictable moment.  After a few minutes pause this error may be disappears and the script may continue.
I had use variable length pauses in my script. They are convenient if access to the Internet can be disappear and appears at any time (because I live at Russia, see my account name).  After a pause of variable length this error sometimes disappears.  Sometimes.  Sometimes not disappears.
But it is easier to just rename a file.  And it is even more convenient to use a specialized for local file operations program.  Now I am testing this program.
