### ISSUE TITLE
Minor typo in Windows src\makefile.vc6

### ISSUE THREAD

**Issue by rodwiddowson** [curl/curl#769]
This may be in purpose  in which case please close.

I note that in makefile.vc6 (and derivatives) the debug objects usually have 'd' appended to their names 	(nonblockd.obj  rawstrd.obj  &c), but slist_wc.obj doesn't.  The net result is that if you type

nmake .... release 

followed by

name .... debug

nmake whines 

NMAKE : warning U4004: too many rules for target 'slist_wc.obj'

**Comment by bagder** [comment]
Thanks!
