### ISSUE TITLE
Header and JSON-report are combined.

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7691]
### I did this
In MS Windows Command Prompt:
curl.exe -D "Header.txt" -I -w %{JSON} "https://curl.se/windows/dl-7.78.0_6/curl-7.78.0_6-win64-mingw.zip"
HTTP/2 200
server: nginx/1.17.6
content-type: application/zip
x-frame-options: SAMEORIGIN
last-modified: Wed, 21 Jul 2021 04:46:56 GMT
etag: "595c91-5c79adc273000"
cache-control: max-age=31536000
expires: Fri, 09 Sep 2022 03:27:52 GMT
x-content-type-options: nosniff
content-security-policy: default-src 'self' curl.haxx.se www.curl.se curl.se www.fastly-insights.com fastly-insights.com; style-src 'unsafe-inline' 'self' curl.haxx.se www.curl.se curl.se
strict-transport-security: max-age=31536000
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 71892
date: Thu, 09 Sep 2021 23:26:03 GMT
x-served-by: cache-bma1635-BMA, cache-pwk4978-PWK
x-cache: HIT, HIT
x-cache-hits: 0, 0
x-timer: S1631229964.758959,VS0,VE1
content-length: 5856401

{"content_type":"application/zip","errormsg":null,"exitcode":0,"filename_effective":null,"ftp_entry_path":null,"http_code":200,"http_connect":0,"http_version":"2","local_ip":"10.17.0.48","local_port":1041,"method":"HEAD","num_connects":1,"num_headers":19,"num_redirects":0,"proxy_ssl_verify_result":0,"redirect_url":null,"referer":null,"remote_ip":"151.101.66.49","remote_port":443,"response_code":200,"scheme":"HTTPS","size_download":0,"size_header":767,"size_request":119,"size_upload":0,"speed_download":0,"speed_upload":0,"ssl_verify_result":0,"time_appconnect":10.039547,"time_connect":0.435443,"time_namelookup":0.018937,"time_pretransfer":10.040318,"time_redirect":0.000000,"time_starttransfer":12.832902,"time_total":12.864742,"url":"https://curl.se/windows/dl-7.78.0_6/curl-7.78.0_6-win64-mingw.zip","url_effective":"https://curl.se/windows/dl-7.78.0_6/curl-7.78.0_6-win64-mingw.zip","urlnum":0,"curl_version":"libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0"}

Is it normally?  Look the content of header:
Type Header.txt
HTTP/2 200
server: nginx/1.17.6
content-type: application/zip
x-frame-options: SAMEORIGIN
last-modified: Wed, 21 Jul 2021 04:46:56 GMT
etag: "595c91-5c79adc273000"
cache-control: max-age=31536000
expires: Fri, 09 Sep 2022 03:27:52 GMT
x-content-type-options: nosniff
content-security-policy: default-src 'self' curl.haxx.se www.curl.se curl.se www.fastly-insights.com fastly-insights.com; style-src 'unsafe-inline' 'self' curl.haxx.se www.curl.se curl.se
strict-transport-security: max-age=31536000
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 71892
date: Thu, 09 Sep 2021 23:26:03 GMT
x-served-by: cache-bma1635-BMA, cache-pwk4978-PWK
x-cache: HIT, HIT
x-cache-hits: 0, 0
x-timer: S1631229964.758959,VS0,VE1
content-length: 5856401

### I expected the following
Header and JSON-report are NOT combined.  Header must be in file only.
### curl/libcurl version
Build 7.78.0_5
[curl -V output]
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10-21H1

**Comment by dfandrich** [comment]
On Thu, Sep 09, 2021 at 04:42:24PM -0700, 7-904-001-67-28 wrote:
> curl.exe -D "Header.txt" -I -w %{JSON} "https://curl.se/windows/dl-7.78.0_6/

This command requests the headers twice—once to be written to a file (-D) and
once to be included in stdout (-I). If you want a HEAD request and to store
both the headers and the JSON variable output in separate places, you'll
probably need to get creative in utilizing all output streams (stdout, stderr
and files), e.g. with a Bourne shell you could do something like this:

curl -s -D "Header.txt" -I -w "%{stderr}%{JSON}" https://curl.se/windows/dl-7.78.0_6/ >/dev/null 2> vars.json

I'm not sure how you'd do the same with a Windows shell.

**Comment by 7-904-001-67-28** [comment]
Sorry, I do not know anything about «Bourne shell».  This works:
curl.exe -I -o Out.txt -w %{JSON} https://curl.se/windows/dl-7.78.0_6/curl-7.78.0_6-win64-mingw.zip

But I requiesting ONE header and using option to write it to file.  Is not it?

**Comment by dfandrich** [comment]
Good idea. I thought -o sent all of stdout to a file, but it only sends the
transfer output—the headers in this case.

**Comment by 7-904-001-67-28** [comment]
My ideas are always great.☺
