### ISSUE TITLE
Wrong error number 61

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7703]
### I did this
In MS Windows Command Prompt:
curl.exe -C 1 --compressed -o HTML.txt https://curl.se/windows/
** Resuming transfer from byte position 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 37  2395   37   904    0     0    221      0  0:00:10  0:00:04  0:00:06   222
curl: (61) Error while processing content unencoding: incorrect header check

### I expected the following
Error №2 or №3.

### curl/libcurl version
Build: 7.78.0_6
[curl -V output]
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10-21H1

**Comment by jay** [comment]
AFAIK there's no way to resume compressed data like that which is why you see bad header. The data is needed from the start to decompress. We should probably warn about it or stop it entirely.

**Comment by 7-904-001-67-28** [comment]
> The data is needed from the start to decompress.

Here is what experts who configure servers write.  Experts, not diletants.
curl.exe --compressed -I https://curl.se/windows/
HTTP/2 200
server: nginx/1.17.6
content-type: text/html
x-frame-options: SAMEORIGIN
last-modified: Thu, 09 Sep 2021 03:25:04 GMT
etag: "1eea-5cb878b724db1-gzip"                                 ← Even here «gzip» mentioned.
cache-control: max-age=60
expires: Fri, 10 Sep 2021 18:41:54 GMT
content-encoding: gzip                                 ← «gzip» again.
x-content-type-options: nosniff
content-security-policy: default-src 'self' curl.haxx.se www.curl.se curl.se www.fastly-insights.com fastly-insights.com; style-src 'unsafe-inline' 'self' curl.haxx.se www.curl.se curl.se
strict-transport-security: max-age=31536000
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes                                 ← Resume (i.e. option «--continue-at») is supported.
date: Sat, 11 Sep 2021 12:55:10 GMT
age: 0
x-served-by: cache-bma1632-BMA, cache-fty21367-FTY
x-cache: MISS, HIT
x-cache-hits: 0, 1
x-timer: S1631364910.118245,VS0,VE408
vary: Accept-Encoding
content-length: 2396

If you want to be a specialist, read the full☺ manuals (i.e. RTFM).

**Comment by 7-904-001-67-28** [comment]
From manual:
43     Internal error. A function was called with a bad parameter.
Instead of №61 or №3.

**Comment by bagder** [comment]
I don't think the error code is the primary problem here. The problem is rather that if the combination of options doesn't work, curl should warn about it earlier...

**Comment by 7-904-001-67-28** [comment]
> curl should warn about it earlier

Of course you are right.  Thank you!

**Comment by 7-904-001-67-28** [comment]
To Badger: please, look at combination of options «-C» and «-JO»:
curl.exe -C 1 -J -L -O -R https://github.com/PowerShell/vscode-powershell/releases/download/v2021.9.0/powershell-2021.9.0.vsix
curl: (23) Failed writing header

HEADER, not output.  Real dump of header terminates on the sixth line of the second header.

**Comment by 7-904-001-67-28** [comment]
To Badger: please, look at combination of options «-JO» and main page of your site:
curl.exe -J -O https://curl.se/windows/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Remote filename has no length!
 11  7914   11   928    0     0    360      0  0:00:21  0:00:02  0:00:19   360
curl: (23) Failure writing output to destination

But «size_download» NOT equals to zero.  Downloaded, but NOT SAVED.  And I can not get a warning «Remote filename has no length!» from the script.  Only an error message is available.
