### ISSUE TITLE
Wrong error numbers 35 and 56

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7704]
### I did this
1) curl.exe -I https://curl.se/windows/
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

2) I do not remember (took from archive):
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
### I expected the following
«error:0A000126:SSL routines::unexpected eof while reading» – one number of error for single message, not two numbers.
### curl/libcurl version
Build: 7.78.0_6
[curl -V output]
curl 7.78.0 (x86_64-pc-win32) libcurl/7.78.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10-21H1

**Comment by bagder** [comment]
In what way are those "wrong" ?

**Comment by 7-904-001-67-28** [comment]
> In what way are those "wrong" ?

Due to ambiguity.  Complicates me from using your program.

**Comment by bagder** [comment]
Sorry, but that's your problem not bug in curl.
