### ISSUE TITLE
Feature: parallel download (HTTP)

### ISSUE THREAD

**Issue by typekpb** [curl/curl#772]
### I expected the following
I'd love to see curl supporting out of the box multiple (parallel) HTTP connections download (see:
http://stackoverflow.com/questions/8378899/downloading-with-curl-using-multiple-connections)

**Comment by bagder** [comment]
You're not alone, which is why this feature is mentioned as a [TODO](https://curl.haxx.se/docs/todo.html#simultaneous_parallel_transfers)

**Comment by typekpb** [comment]
sry, missed that

**Comment by MoSal** [comment]
@typekpb 
Check out [saldl](https://github.com/saldl/saldl). It could be the tool you're looking for.
