### ISSUE TITLE
test 1184 fails in version 7.79.0

### ISSUE THREAD

**Issue by RiderALT** [curl/curl#7725]
full log attached.

 10:46:51.248531 == Info: Issue another request to this URL: 'http://127.0.0.1.1184:36377/we/want/that/page/11840002'
 10:46:51.248654 == Info: Hostname 127.0.0.1 was found in DNS cache
 10:46:51.248701 == Info:   Trying 127.0.0.1:33317...
 10:46:51.248816 == Info: Connected to 127.0.0.1 (127.0.0.1) port 33317 (#1)
 10:46:51.248837 == Info: allocate connect buffer
 10:46:51.248867 == Info: Establish HTTP proxy tunnel to 127.0.0.1.1184:36377
 10:46:51.248917 => Send header, 124 bytes (0x7c)
 0000: CONNECT 127.0.0.1.1184:36377 HTTP/1.1
 0027: Host: 127.0.0.1.1184:36377
 0043: User-Agent: curl/7.79.0
 005c: Proxy-Connection: Keep-Alive
 007a: 
 10:46:51.255086 <= Recv header, 33 bytes (0x21)
 0000: HTTP/1.1 200 Mighty fine indeed
 10:46:51.255192 <= Recv header, 26 bytes (0x1a)
 0000: Server: test tunnel 2000
 10:46:51.255219 <= Recv header, 2 bytes (0x2)
 0000: 
 10:46:51.255237 == Info: Proxy replied 200 to CONNECT request
 10:46:51.255250 == Info: CONNECT phase completed
 10:46:51.255310 => Send header, 109 bytes (0x6d)
 0000: GET /we/want/that/page/11840002 HTTP/1.1
 002a: Host: 127.0.0.1.1184:36377
 0046: Accept: */*
 0053: User-Agent: 1184-agent
 006b: 
 10:46:52.261405 == Info: Empty reply from server
 10:46:52.261538 == Info: Closing connection 1
=== End of file trace1184

[trace1184.txt](https://github.com/curl/curl/files/7169467/trace1184.txt)

**Comment by bagder** [comment]
That test seems to be flaky for some reason.
