### ISSUE TITLE
curl 7.79 does not compile on linux and mac with debug flags

### ISSUE THREAD

**Issue by tawmoto** [curl/curl#7733]
I am trying to build curl as I do it for years, with the same flags.

```
FLAGS=" -Wa,-compress-debug-sections=none -fPIC -DPIC -m64" LDFLAGS=" -Wl,-compress-debug-sections=none" ./configure --enable-ftp --enable-proxy --enable-ipv6 --enable-http --enable-nonblocking --enable-crypto-auth --enable-hidden-symbols --enable-soname-bump --enable-static --disable-shared --disable-dict --disable-ares --disable-telnet --disable-tftp --disable-manual --disable-rtsp --disable-file --disable-pop3 --disable-imap --disable-smtp --disable-ldap --disable-ldaps --disable-sspi --without-libssh2 --without-zlib --without-gnutls --without-nss --without-libidn --without-libidn2 --without-nghttp2 --without-librtmp --without-brotli --without-libpsl --prefix="some_install_dir" --with-ssl="ssl_dir" --disable-rt --disable-threaded-resolver --enable-debug --enable-curldebug
```
I get this error
```
d	16-Sep-2021 14:49:36		[DEBUG] 	CC       vtls/libcurlu_la-wolfssl.lo
build	16-Sep-2021 14:49:36		[DEBUG] 	CC       vquic/libcurlu_la-ngtcp2.lo
build	16-Sep-2021 14:49:36		[DEBUG] 	CC       vquic/libcurlu_la-quiche.lo
build	16-Sep-2021 14:49:36		[DEBUG] 	CC       vquic/libcurlu_la-vquic.lo
build	16-Sep-2021 14:49:37		[DEBUG] 	CC       vssh/libcurlu_la-libssh.lo
build	16-Sep-2021 14:49:37		[DEBUG] 	CC       vssh/libcurlu_la-libssh2.lo
build	16-Sep-2021 14:49:37		[DEBUG] 	CC       vssh/libcurlu_la-wolfssh.lo
build	16-Sep-2021 14:49:37		[DEBUG] 	CCLD     libcurlu.la
build	16-Sep-2021 14:49:37		[DEBUG] 	RUN      checksrc
build	16-Sep-2021 14:49:38		[DEBUG] 	./strerror.c:734:20: warning: Unused ignore: STRERROR (UNUSEDIGNORE)
build	16-Sep-2021 14:49:38		[DEBUG] 	/* !checksrc! disable STRERROR 2 */
build	16-Sep-2021 14:49:38		[DEBUG] 	^
build	16-Sep-2021 14:49:38		[DEBUG] 	checksrc: 0 errors and 1 warnings
build	16-Sep-2021 14:49:38		[DEBUG] 	checksrc: 0 errors and 7 warnings suppressed
build	16-Sep-2021 14:49:38		[DEBUG] 	Makefile:206412: recipe for target 'checksrc' failed
build	16-Sep-2021 14:49:38		[DEBUG] 	make[2]: *** [checksrc] Error 5
```

The problem seems this line:
https://github.com/curl/curl/commit/2f0bb864c126892afc822e0cf5547d7ea5094212#r56567123

Problem is reproducible on Linux and MacOS with curl 7.79.0

Thanks

**Comment by tawmoto** [comment]
@bagder thank you very much for the fix, but I tried to implement it on my local machine and I still get the error. (i mean this change: https://github.com/curl/curl/commit/73b55e43aa25683ce87bb77903cc20bd64f3775c)
Maybe I should change something in my building flags? I am using them for years without any problem.
Btw, the error occurs only I use `--enable-debug` flag.

Thank you

**Comment by bagder** [comment]
> I tried to implement it on my local machine and I still get the error

So what exactly did you do to "implement it" ?

**Comment by tawmoto** [comment]
> So what exactly did you do to "implement it" ?

Downloaded 7.79.0, unpacked it, did that change (by adding `.checksrc` string in the `lib/Makefile.am ` file, like in your PR), ran `configure` (like in my original post) and `make install`.

**Comment by bagder** [comment]
You want to put a file in the `lib/` directory and call that file `.checksrc` and it should have the contents shown here: https://github.com/curl/curl/blob/master/lib/.checksrc

The fix I did makes sure to include that file in release tarballs.

**Comment by tawmoto** [comment]
> You want to put a file in the `lib/` directory and call that file `.checksrc` and it should have the contents shown here: https://github.com/curl/curl/blob/master/lib/.checksrc
> 
> The fix I did makes sure to include that file in release tarballs.

Thanks a lot for the solution, it work!
I guess 7.79.1 won't be released too soon with this fix, so I will create a patch on my side.

Cheers and thanks again!

**Comment by bagder** [comment]
[7.79.1 will ship on Sep 22](https://curl.se/mail/lib-2021-09/0049.html)
