### ISSUE TITLE
Content-length no longer reported since 7.79 when interrupting the download

### ISSUE THREAD

**Issue by rouault** [curl/curl#7736]
When a function set by CURLOPT_WRITEFUNCTION stops downloading after having read the HTTP headers, curl_easy_getinfo(, CURLINFO_CONTENT_LENGTH_DOWNLOAD) returns a negative size since commit 8a16e54c0cc71e15ef78d9eaf1f9155a0204202d
```
Author: Daniel Stenberg <daniel@haxx.se>
Date:   Mon Aug 30 17:49:25 2021 +0200

    http: ignore content-length if any transfer-encoding is used
    
    Fixes #7643
    Closes #7649
```

However, in my use case no transfer-encoding header is emitted. See logs:
```
> GET /foo.s3.amazonaws.com/test_redirected/test.bin?Signature=foo&Expires=1530 HTTP/1.1
Host: localhost:8080
Accept: */*

* STATE: DO => DID handle 0x1ce0b18; line 2068 (connection #3)
* STATE: DID => PERFORMING handle 0x1ce0b18; line 2187 (connection #3)
* Mark bundle as not supporting multiuse
* HTTP 1.1 or later with persistent connection
< HTTP/1.1 200
< Server: foo
< Date: Thu, 01 Jan 1970 00:25:00 GMT
< Content-type: text/plain
< Content-Length: 1000000
< Connection: close
* Failed writing header
* multi_done
* The cache now contains 0 members
* Closing connection 3
* Expire cleared (transfer 0x1ce0b18)
```

**Comment by bagder** [comment]
If you interrupt the transfer before curl knows the last header has arrived, the content-length header cannot be "trusted" and therefore it can't know for sure what it will be.

**Comment by rouault** [comment]
> If you interrupt the transfer before curl knows the last header has arrived, the content-length header cannot be "trusted" and therefore it can't know for sure what it will be.

That was it. My callback returned 0 when seeing the '\r\n' line marking the end of the header section. I've changed it to return 0 at the next call and that works now.
