### ISSUE TITLE
Failure to build against custom/latest OpenSSL on CentOS/RHEL

### ISSUE THREAD

**Issue by voetsjoeba** [curl/curl#774]
On CentOS and RHEL systems, curl 7.48.0 fails to build against a custom version of OpenSSL (verified on RHEL6 and CentOS 7).

The actual compile and link of both libcurl and the curl binary itself succeed, but the make invocation dies at the end due to a broken `curl` invocation in scripts/Makefile, apparently to create zsh completions. The curl invocation fails because the binary is unable to find the custom OpenSSL libraries it was built against -- seems like it would need an LD_LIBRARY_PATH to be in place before invoking it, or otherwise the library location added to the binary's RPATH.

How to reproduce:
 - Download openssl-1.0.2g and `./config --prefix=$HOME/local/openssl shared threads no-ssl2 no-ssl3 && make depend && make && make install`
 - Download curl-7.48.0 and `./configure --prefix=$HOME/local/curl --with-ssl=$HOME/local/openssl`

Error output:
```
...
<build goes fine>
...
  CC       ../lib/curl-warnless.o
  CCLD     curl
make[2]: Leaving directory `/home/vmuser/local/curl-7.48.0/src'
make[1]: Leaving directory `/home/vmuser/local/curl-7.48.0/src'
make[1]: Entering directory `/home/vmuser/local/curl-7.48.0/include'
  king all in curl
▽ake[2]: Entering directory `/home/vmuser/local/curl-7.48.0/include/curl'
make  all-am
make[3]: Entering directory `/home/vmuser/local/curl-7.48.0/include/curl'
make[3]: Leaving directory `/home/vmuser/local/curl-7.48.0/include/curl'
make[2]: Leaving directory `/home/vmuser/local/curl-7.48.0/include/curl'
make[2]: Entering directory `/home/vmuser/local/curl-7.48.0/include'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/vmuser/local/curl-7.48.0/include'
make[1]: Leaving directory `/home/vmuser/local/curl-7.48.0/include'
Making all in scripts
make[1]: Entering directory `/home/vmuser/local/curl-7.48.0/scripts'
/usr/bin/perl ./zsh.pl ../src/curl > _curl
/home/vmuser/local/curl-7.48.0/src/.libs/lt-curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
curl returned 127 with output:
make[1]: *** [_curl] Error 127
make[1]: Leaving directory `/home/vmuser/local/curl-7.48.0/scripts'
make: *** [all-recursive] Error 1
```

An obvious fix would be to disable the zsh completions generation using this `--configure` option:

```
  --without-zsh-functions-dir
                          Do not install zsh completions
```
Unfortunately, this doesn't actually do anything; scripts/Makefile will still invoke the zsh.pl script.

**Comment by bagder** [comment]
I believe this is already fixed with commit ccfa8407a

**Comment by voetsjoeba** [comment]
That's good news; let me get a copy of the current HEAD and verify

**Comment by voetsjoeba** [comment]
Yep, builds cleanly against latest HEAD at the time of writing: ad3d40d40707f1c5f37f878a61de4a8f0aeac2b8. Thanks!

**Comment by bagder** [comment]
thanks for verifying!
