### ISSUE TITLE
`curl -DELETE -u user:password` should report an error

### ISSUE THREAD

**Issue by jamshid** [curl/curl#7741]
### I did this

```
curl -v -DELETE -u user:password http://localhost/foo
```

### I expected the following

Colleague had unexpected behavior because they missed a `-X` but I was surprised that curl did not complain about invalid options. I guess each of those letters are valid options but shouldn't curl complain that required parameters for `-T` and -E` are missing?

### curl/libcurl version

```
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

### operating system

```
Darwin X 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

**Comment by jay** [comment]
That may somehow be valid. I'd have to check but the value for -T likely becomes -u and so on. Otherwise you'd get error `option -T: requires parameter`. Though I realize it makes no sense to -DELETE it seems technically correct to parse, so I don't think we should do anything here.

**Comment by bagder** [comment]
`-D` takes a file name as argument and you gave it `ELETE`. That's not a problem for curl's command line parser.

**Comment by bagder** [comment]
This behavior is also documented. Closing.

**Comment by jamshid** [comment]
Ah ok, thanks. I was also confused that `curl -v -GET -u user:password http://localhost/foo` works but curl uses `T` as the argument to `-E` and then ignores the fact that cert file `T` does not exist because the url is not `https`.

**Comment by bagder** [comment]
For some more "fun" command lines you can make thanks to this feature in the parser, see https://github.com/bagder/docs/blob/master/fun-commandlines.md
