### ISSUE TITLE
LNK1181 Windows linking error with x86 but no with x64

### ISSUE THREAD

**Issue by pipawoz** [curl/curl#7743]
Hi, I am trying to compile a program with curl. 

I am trying with the latest version 7.79 (also with master). To compile on windows I use "nmake /f Makefile.vc mode=static vc=16 debug=no" in both visual studio tools for x86 and for x64 native tools prompt. 

After compiling, I look in `build/libcurl-vc16-x86-release-static-ipv6-sspi-schannel` for the `libcurl_a.lib` library which I add in my makefile (I also add `Ws2_32.lib Crypt32.lib Wldap32.lib Normaliz.lib`).

When I compile with 64 I have no errors and my program compiles/link correctly, but when I compile in 32 the following error appears `LINK : fatal error LNK1181: cannot open input file libs\curl\32\libcurl_a.lib` (my program folder)

This happens with both release and debug only in the case of x86. The compilation does not give any error.   The .exe file on bin works fine.  Im using Windows 10 x64

Any ideas? My first guess would be that is a compatibility issue but cant find how to fix it and i need to compile my program for both x86 and x64. 

Thanks

**Comment by jay** [comment]
> LINK : fatal error LNK1181: cannot open input file libs\curl\32\libcurl_a.lib

I don't know where libs\curl\32 comes from. The file should be in builds\libcurl-vc16-x86-release-static-ipv6-sspi-schannel\lib

Can you please try switching to the examples directory and building the simple.c example:

cd curl\docs\examples
cl /W4 /MD /DCURL_STATICLIB /I..\..\builds\libcurl-vc16-x86-release-static-ipv6-sspi-schannel\include simple.c /link /LIBPATH:..\..\builds\libcurl-vc16-x86-release-static-ipv6-sspi-schannel\lib libcurl_a.lib advapi32.lib crypt32.lib normaliz.lib wldap32.lib ws2_32.lib

**Comment by pipawoz** [comment]
Hi. Thanks for the reply.
By using that line i was able to find that i had an issue in my makefile, the line works ok for the example and with the fix now im able to compile my program with curl.

Thanks!
