### ISSUE TITLE
curl 7.79 compile with wolfssl error:  undefined reference to 'wolfSSL_ERR_clear_error'

### ISSUE THREAD

**Issue by rampageX** [curl/curl#7745]
It's a tiny version, curl 7.78 with wolfssl 4.8.1 was fine:

```
done/git/Tiny/curlt: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped

curl 7.78.0 (armv7l-unknown-linux-uclibceabi) libcurl/7.78.0 wolfSSL/4.8.1
Release-Date: 2021-07-21
Protocols: http https
Features: AsynchDNS HSTS SSL
```

but not 7.79:

```
/mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-wolfssl.o): in function `wolfssl_shutdown':
wolfssl.c:(.text+0xd4): undefined reference to `wolfSSL_ERR_clear_error'
/mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-wolfssl.o): in function `wolfssl_send':
wolfssl.c:(.text+0x11c): undefined reference to `wolfSSL_ERR_clear_error'
/mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-wolfssl.o): in function `wolfssl_recv':
wolfssl.c:(.text+0x1bc): undefined reference to `wolfSSL_ERR_clear_error'
/mmc/lib/gcc/arm-tomatoware-linux-uclibcgnueabi/10.3.0/../../../../arm-tomatoware-linux-uclibcgnueabi/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-wolfssl.o): in function `wolfssl_connect_common':
wolfssl.c:(.text+0xdc4): undefined reference to `wolfSSL_ERR_clear_error'
```

**Comment by bagder** [comment]
I presume you need to make sure your wolfSSL build has `wolfSSL_ERR_clear_error` enabled.

**Comment by rampageX** [comment]
I have tried to recompile wolfSSL with `--enable-all`, but I still get these error when i compile curl 7.79

**Comment by rampageX** [comment]
I rollback https://github.com/curl/curl/commit/797bacf9c5a39f68d337d13f488407eeb507a9fc fix my problem.

> If wolfSSL is built in certain ways (OPENSSL_EXTRA or Debug)

I am sure i didn't enable openssl_extra and debug when build wolfssl (both [default=no]):

```
--enable-opensslextra   Enable extra OpenSSL API, size+ (default: disabled)
--enable-debug          Add debug code/turns off optimizations (yes|no)
                          [default=no]
```

**Comment by bagder** [comment]
Curious. The wolfSSL CI build works and it builds wolfSSL 4.7.0 like this: `./configure --enable-tls13 --enable-all`

**Comment by bagder** [comment]
I just double-checked. I built and installed wolfSSL 4.8.1 locally with `./configure --prefix=/home/daniel/build-wolfssl-481 --enable-all` and the built curl to use it with `LD_LIBRARY_PATH=$HOME/build-wolfssl-481/lib ./configure --disable-shared --with-wolfssl=/home/daniel/build-wolfssl-481 --enable-debug --enable-werror --enable-maintainer-mode`

No problemos.

I also checked the wolfSSL code and as the commit message for 797bacf says: the function *exists* if when it does nothing so it should never cause a link problem. It would rather indicate that your wolfSSL lib is an incomplete one or a stripped build somehow.

**Comment by rampageX** [comment]
Maybe cause by OpenSSL/wolfSSL co-exist. I will dig it at other times.

**Comment by maggie0002** [comment]
Looks like there is already some changes in the mix for this, but to add some clarification that could have helped me:

`--enable-opensslextra` fixes the issue, but increases the size significantly.

Ended up manually reverting the changes in https://github.com/curl/curl/commit/797bacf9c5a39f68d337d13f488407eeb507a9fc as mentioned above. Hopefully next version will be ok.

**Comment by bagder** [comment]
> Hopefully next version will be ok.

The calls to `ERR_clear_error();` are in the current wolfssl.c code and we've had no work by anyone trying to remove them. Feel free to work on that.

**Comment by maggie0002** [comment]
Not sure how this is related: https://github.com/buildroot/buildroot/commit/6ee815f77b8e1b8e8fcb7922d41042379b4ce0b1

**Comment by bagder** [comment]
> Could wrap them in a conditional that queries if the enable-opensslextra mode is active

Yes, that seems doable.

**Comment by maggie0002** [comment]
> > Could wrap them in a conditional that queries if the enable-opensslextra mode is active
> 
> Yes, that seems doable.

Took a quick look, now struggling to reproduce the `--enable-opensslextra` fix. Will have to try and come back to it.
