### ISSUE TITLE
CURL Error: 60 - Peer's Certificate issuer is not recognized

### ISSUE THREAD

**Issue by zerobl0ck** [curl/curl#7749]
Hi, 

I have updated curl from 7.29 to 7.79 using city-fan.org repo.

OS: CentOS 7

After update I have getting following error: 
Unexpected recaptcha verification result: CURL Error: 60 - Peer's Certificate issuer is not recognized.

Can you please guide me how to resolve it? Or how to downgrade the version.

**Comment by dfandrich** [comment]
It sounds like the new curl uses a different certificate store than the old
one. Try running "curl -v https://example.com" with the new and old curl
versions and see what they say about the certpath or cafile. It might be that
the new version expects a different set of certificates that have to be
installed separately.

**Comment by zerobl0ck** [comment]
Yes you are right.
I have check with old version of curl 7.68 and there the took right path of CAfile and CApath but when I tired with latest version it is not taking that those paths and showing 
"
*  CAfile: none
*  CApath: none
"

So how I can modify or set the correct path in latest version?

Thank you for helping me.

**Comment by dfandrich** [comment]
You could use the --cacert or --capath options, or set them in ~/.curlrc. Or,
contact whoever built the RPM and ask that it be changed to use the standard
paths.
