### ISSUE TITLE
7.79 could not load PEM client certificate

### ISSUE THREAD

**Issue by MusiqueGraeme** [curl/curl#7750]
### I did this
I attempted with cURL 7.79.0_1 to download a file from an https website that uses TLS1.2 using a pem certificate that worked with cURL 7.78.

### I expected the following
The download to work and the file to appear in the given folder. None of the files or commandline used had changed from before the update to 7.79. 

### curl/libcurl version
C:\WINDOWS\system32>U:\Settings\cURL\Win64New\bin\curl.exe  -V
curl 7.79.0 (x86_64-pc-win32) libcurl/7.79.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.44.0 libgsasl/1.10.0
Release-Date: 2021-09-15
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd

[curl -V output]
* ALPN, offering http/1.1
* could not load PEM client certificate, OpenSSL error error:0A00018E:SSL routines::ca md too weak, (no key found, wrong pass phrase, or wrong file format?)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (58) could not load PEM client certificate, OpenSSL error error:0A00018E:SSL routines::ca md too weak, (no key found, wrong pass phrase, or wrong file format?)

### operating system
 have a Windows 10 version 21H1.

**Comment by MusiqueGraeme** [comment]
I don't know - I used cURL 7.78.0 until 17 Sept 21. What version of OpenSSL it used is presumably dependent on the distributor of cURL. It came, I think from https://curl.haxx.se/windows/dl-7.78.0/curl-7.78.0-win64-mingw.zip

**Comment by MusiqueGraeme** [comment]
It would seem that the new version is using OpenSSL 3.0.0... This was released on 7 Sep 21

**Comment by jzakrzewski** [comment]
The OpenSSL tells you exactly what it doesn't like: "SSL routines::ca md too weak". It seems that your certificate is signed with an MD5 or SHA1 (more probably the latter since the former gives this since some time already).

**Comment by MusiqueGraeme** [comment]
Is there a way to accept that or do I need to reissue the certs... I didn't see this issue in the change log.

**Comment by jzakrzewski** [comment]
It is mentioned in the OpenSSL changelog and https://github.com/openssl/openssl/blob/master/doc/man7/migration_guide.pod :
> X509 certificates signed using SHA1 are no longer allowed at security level 1 and above.
> In TLS/SSL the default security level is 1. It can be set either using the cipher string with @SECLEVEL, or calling SSL_CTX_set_security_level(3). If the leaf certificate is signed with SHA-1, a call to SSL_CTX_use_certificate(3) will fail if the security level is not lowered first. Outside TLS/SSL, the default security level is -1 (effectively 0). It can be set using X509_VERIFY_PARAM_set_auth_level(3) or using the -auth_level options of the commands.

You'll probably have to fiddle with your global OpenSSL configuration.
In any case it doesn't seem to be a curl issue.

**Comment by MusiqueGraeme** [comment]
If you pass on program changes like that without any notification it seems like a curl issue to me. Thanks for you help. I just use cURL as I imagine others might, without being aware that OpenSSL is doing the work.

**Comment by MusiqueGraeme** [comment]
By the way - are those suggestions of yours for using with cURL or with OpenSSL. I use a cURL command to do the download. So cURL has to pass on the new settings - doesn't it?

**Comment by bagder** [comment]
@MusiqueGraeme you're using a curl package provided by someone. Possibly you even changed to using a curl packaged provided by someone else. Somewhere along the line a config was changed in that curl package. I don't understand what you want us to do about that. We don't provide that package and you don't seem to have made perfectly sure that you get a package with all details unchanged.

**Comment by MusiqueGraeme** [comment]
I just thought that somewhere there should have been a mention that the OpenSSL which is somehow used - I'm not experienced enough to know how - has changed. I don't know if that change happened in the package creation or in the curl program but it seems that there should be a way to retain compatibility. Your colleague provided what he thought was helpful but it wasn't as I don't know how OpenSSL config is affected in the use of cURL. I guess I need to find a solution elsewhere. Maybe I'll keep using 7.78.0 until the certs of the whole company can be changed.

**Comment by bagder** [comment]
I'm happy to offer you that support service at a fair price. Until then, I suggest you ask the people you get your curl package from how they build it and if you have requirements, ask them. This issue is hereby closed.
