### ISSUE TITLE
Tab completion does not work for `--output-dir`

### ISSUE THREAD

**Issue by archiif** [curl/curl#7755]
### I did this
`curl --output /tm` &#11134; `curl --output /tmp/`
`curl --output-dir /tm` &#11134; `curl --output-dir /tm`

### I expected the following
`curl --output /tm` &#11134; `curl --output /tmp/`
`curl --output-dir /tm` &#11134; `curl --output-dir /tmp/`

### curl/libcurl version
```
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.5/openssl/zlib nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
### operating system
```
Linux [hostname] 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
What tab completion is that? If it isn't `scripts/completion.pl` it isn't provided by us...

**Comment by bagder** [comment]
I guess this user is using a tab completion setup provided by someone else, so not our bug.
