### ISSUE TITLE
Disable brace expansion

### ISSUE THREAD

**Issue by 89z** [curl/curl#7757]
I found this information [1]:

~~~
You can specify multiple URLs or parts of URLs by writing part sets within
braces and quoting the URL as in:

"http://site.{one,two,three}.com" 
~~~

but I dont want cURL to do this. I want cURL to just pass the characters literally, without any special interpreting. Is it possible?

1. https://curl.se/docs/manpage.html

**Comment by dfandrich** [comment]
On Wed, Sep 22, 2021 at 09:11:07AM -0700, Steven Penny wrote:
> but I dont want cURL to do this. I want cURL to just pass the characters
> literally, without any special interpreting. Is it possible?

https://curl.se/docs/faq.html#How_can_I_use_or_to_sp

**Comment by 89z** [comment]
Thanks. I missed that, as I was searching for `brace`, and that section does not include that word, nor does this section:

https://curl.se/docs/manpage.html#-g

I think both sections should include the word `brace`, as people will likely be searching for that. Thanks again
