### ISSUE TITLE
Configure reports error detecting OpenSSL 3 headers

### ISSUE THREAD

**Issue by rsbeckerca** [curl/curl#7758]
When configure runs, the following is reported:
```
checking for OpenSSL headers version... sed: -e expression #1, char 0: no previous regular expression
unknown - 0x
```
I cannot find this error in `config.log` - `stderr` is not captured for this sed instance. This does not actually impact the final result.

### I did this

```
CPPFLAGS="-D_XOPEN_SOURCE_EXTENDED=1 -WIEEE_float -I/usr/local-ssl3.0_32/openssl/include" LDFLAGS="-L/usr/local-ssl3.0_32/lib" ./configure --prefix=/usr/local-ssl3.0 --with-ssl=/usr/local-ssl3.0_32 --with-ca-path=/usr/local-ssl3.0/ssl/certs --disable-pthreads --disable-threaded-resolver --enable-ipv6
```

### I expected the following

The OpenSSL version in the header displayed, but I understand that it is more complex than in version 1.

### curl/libcurl version
```
curl 7.79.1 (nsx-tandem-nsk) libcurl/7.79.1 OpenSSL/3.0.0 zlib/1.2.8
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smtp smtps telnet tftp
Features: alt-svc HSTS HTTPS-proxy IPv6 libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
### operating system
```
NONSTOP_KERNEL mysys L20 10 NSX-D NSX NSX-D NonStop Kernel
```

**Comment by bagder** [comment]
I would presume it is the sed line added in commit f09030b63867 but that works on all the systems I've seen it run on so I can't really tell why it causes a problem for you.

**Comment by rsbeckerca** [comment]
> 
> 
> I would presume it is the sed line added in commit [f09030b](https://github.com/curl/curl/commit/f09030b63867895cccffbd3d61ef6d3dd86c4307) but that works on all the systems I've seen it run on so I can't really tell why it causes a problem for you.

I have tried the `sed` command from that commit, with no trouble. The issue is that the command is being executed inside a sub-shell, so ksh needs a double escape for `"`, as in `\\"`. Instead of `sed s/\"//g`, could you use a more stable `sed 's/"//g'` instead?

**Comment by bagder** [comment]
See #7764

**Comment by rsbeckerca** [comment]
> 
> 
> See #7764

I applied the change and manually to `configure`:

`checking for OpenSSL headers version... 3.0.0 - 0x300`

That looks good. Thanks.

**Comment by bagder** [comment]
excellent!
