### ISSUE TITLE
Progress bar not working for SFTP resumed upload

### ISSUE THREAD

**Issue by beslick5** [curl/curl#7760]
When using -# option to display progress bar for file uploads the progress bar instantly shows 100% (no matter how much of the file is processed)

In prior versions the progress bar correctly and accurately shows percentage of file uploaded.

Issue found in curl 7.79.0 and curl 7.79.1

Example command to reproduce the issue...

curl -k -C - -# -u "MYUSER":"MYPASS" --ftp-ssl --retry 100 --retry-delay 60 -T c:\temp\BIGFILE.7z sftp://ftp.server.com.au/backups/

**Comment by bagder** [comment]
It does not repeat for me:
~~~
$ ./src/curl -u u:p sftp://localhost//var/www/html/8GB -o store -# -C -
##                                                                            3.1%^C
$ ./src/curl -u u:p sftp://localhost//var/www/html/8GB -o store -# -C -
####                                                                          6.2%^C
$ ./src/curl -u u:p sftp://localhost//var/www/html/8GB -o store -# -C -
#######                                                                      10.6%^C
$ ./src/curl -u u:p sftp://localhost//var/www/html/8GB -o store -# -C -
###########                                                                  16.0%^C
$ ./src/curl -u u:p sftp://localhost//var/www/html/8GB -o store -# -C -
################                                                             21.6%^C

**Comment by beslick5** [comment]
Hi Daniel,

I suspect it has something to do with the actual settings being applied.

I can reproduce the issue every time per the example command structure/settings advised in my ticket.

Please try with the same settings I advised.

More proof of the issue below.

***@***.***


Best regards

Brett Eslick
[https://www.sihot.com/wp-content/uploads/signatur/sihot-flosse.png]

Brett Eslick
Director of IT
        p. +61 7 5634 9527<callto:+61%207%205634%209527>
m. +61 403400000<callto:+61%20403400000>
e. ***@***.******@***.***>

SIHOT Asia/Pacific Pty Ltd.
Level 4 | Suite 39 | 46 Cavill Avenue
Surfers Paradise, QLD 4217
AUSTRALIA

**Comment by beslick5** [comment]
I've confirmed the issue is when there is a combination of "-C -" (resume file) and "-#" (progress bar).

If you DO NOT use the "resume" option (-C -) then the progress bar works as expected.

This was never an issue in version 7.39.0 or prior. Have only noticed this issue since recently upgrading to v7.79.0 and v7.79.1

**Comment by beslick5** [comment]
Here is a more simplified example...

Issue occurs with any transfer with "-# -C -" options together...
   curl -# -C - -k -u "user":"pass" -T C:\temp\BIG_FILE.7z sftp://ftp.server.com

Take out the "-C -" option and the progress bar works as expected...
   curl -# -k -u "user":"pass" -T C:\temp\BIG_FILE.7z sftp://ftp.server.com

Attached image demonstrates the issue/output per working examples...
![image](https://user-images.githubusercontent.com/91231093/134465788-2c9ce2d8-faf9-4cbd-a993-707a652a44b8.png)
