### ISSUE TITLE
support for setting qos/dscp in libcurl

### ISSUE THREAD

**Issue by sashang** [curl/curl#777]
Hi

Is there support for setting qos/dscp bits in libcurl or is it still unimplemented?

I found the following links and it looks like it's not  done.
https://curl.haxx.se/mail/tracker-2012-11/0025.html

**Comment by bagder** [comment]
Can't you accomplish this with [CURLOPT_SOCKOPTFUNCTION](https://curl.haxx.se/libcurl/c/CURLOPT_SOCKOPTFUNCTION.html) ?

**Comment by dfandrich** [comment]
You can do that yourself on the raw socket using one of the socket callback
functions.
