### ISSUE TITLE
Build with BoringSSL fails

### ISSUE THREAD

**Issue by Paco112** [curl/curl#7773]
### I did this

I compiling curl and BoringSSL with method on https://everything.curl.dev/source/build/tls/boringssl

but make command return error :

/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'sk_pop_free_ex'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_mode'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'BIO_reset'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_set_tlsext_host_name'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'sk_value'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_add0_chain_cert'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'OPENSSL_malloc'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_msg_callback_arg'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'BIO_read_filename'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'EVP_MD_CTX_destroy'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'BIO_get_mem_ptr'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_clear_chain_certs'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_add_extra_chain_cert'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'OPENSSL_free'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_get_ex_new_index'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_session_cache_mode'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_max_proto_version'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'SSL_CTX_set_min_proto_version'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'EVP_MD_CTX_create'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'sk_num'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'BIO_set_ssl'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'sk_pop'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to 'BIO_get_mem_data'
collect2: error: ld returned 1 exit status

### I expected the following

Successful compilation

### curl/libcurl version

7.76.1

### operating system

`Linux dev 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`

**Comment by bagder** [comment]
I tried now and I built fine from git.

I have "mybuild.sh" looking like this in my boringssl source tree root. It builds both shared and static versions of boring:
~~~sh
#!/bin/sh
CXX=g++ CC=gcc cmake -H. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=release -DBUILD_SHARED_LIBS=1 && cmake --build build
cp ./build/crypto/libcrypto.so ./lib/
cp ./build/ssl/libssl.so ./lib/

cmake --build build --target clean
rm -f build/CMakeCache.txt

CXX="g++" CC="gcc" cmake -H. -Bbuild -GNinja -DCMAKE_POSITION_INDEPENDENT_CODE=on && cmake --build build
cp ./build/crypto/libcrypto.a ./lib/
cp ./build/ssl/libssl.a ./lib/
~~~

Then in my curl source tree root I run this:
~~~sh
LIBS=-lpthread ./configure --disable-shared --enable-debug --enable-maintainer-mode --with-ssl=$HOME/src/boringssl
make -sj6
~~~

The `--with-ssl` points to the source tree root where I built BoringSSL.

This makes curl built to use the shared version, so you need to make sure `LD_LIBRARY_PATH` or whatever is set correctly.

**Comment by Paco112** [comment]
Ok thanks for your answer and your reactivity, the compilation with your method works.
