### ISSUE TITLE
imap-append.c example: incorrect pointer check in payload_source()

### ISSUE THREAD

**Issue by achuykov** [curl/curl#7774]
Hi,

This condition is always true because even incorrect offset produces valid (non-NULL) pointer: 
`  data = &payload_text[upload_ctx->bytes_read];`
`  if(data) {`

I expect that "if" condition should check the end end of ASCIIZ string:
`  if(*data) {`

Thanks,
Alexander

**Comment by bagder** [comment]
Yes, makes perfect sense!
