### ISSUE TITLE
"curl -M" date

### ISSUE THREAD

**Issue by gvanem** [curl/curl#7780]
At the end of my generated manual printed with `curl -M`, there is `Curl 7.52.0                    16 Dec 2016                    curl(1)`
which looks strange. Since I built from todays snap-shot of `7.80.0-DEV`.

This old date comes from `docs/cmdline-opts/gen.pl`:
```perl
    if($standalone) {
        print ".TH curl 1 \"30 Nov 2016\" \"curl 7.52.0\" \"curl manual\"\n";
        print ".SH OPTION\n";
        print "curl $opt\n";
    }
```

I know next to nothing of Perl. So I fail to understand what `$standalone` means.

But for reference, these are the steps that my `src/tool_hugehelp.c` gets produced here:

```
cd ../docs/cmdline-opts 
perl.exe ./gen.pl mainpage *.d > ../curl.1
cd ../../src
groff -Tascii -man -P -c  ../docs/curl.1 > tool_hugehelp.tmp
perl.exe -w ./mkhelp.pl -c < tool_hugehelp.tmp >  tool_hugehelp.c
```

Correct?  Or should `sed` be used to replace `\"30 Nov 2016\" \"curl 7.52.0\"` with something more appropriate?

**Comment by gvanem** [comment]
Okay, so it's `src/mkhelp.pl` that is responsible for cutting away such lines:
```perl
    if($line =~ /^([ \t]*\n|curl)/i) {
        # cut off headers and empty lines
```
 
It didn't here since I had modified `mkhelp.pl`.

But I'd think it would be nice **not** to cut this off. But leave a sensible date and version at the bottom instead.

**Comment by bagder** [comment]
Is it really necessary in the -M output when the version number is already visible with -V?

I made #7782 to make sure the date and version gets generated in the generated curl.1 file.

**Comment by gvanem** [comment]
> Is it really necessary in the -M output when the version number is already visible with -V?

Not really. But the date isn't in `curl -V` (here at least).

**Comment by bagder** [comment]
The `Release-Date:` is present in builds that are built from release tarballs...

**Comment by bagder** [comment]
I think we provide the information "good enough" this way. @gvanem, do you think we need to do more?

**Comment by gvanem** [comment]
I've tried those PRs. It looks better now.
