### ISSUE TITLE
content length not available in header function

### ISSUE THREAD

**Issue by sergio-nsk** [curl/curl#7804]
The write header function receives "\r\n" that indicates all http headers are received. The info CURLINFO_CONTENT_LENGTH_DOWNLOAD_T returns -1.

This change in [http.c](https://github.com/curl/curl/commit/8a16e54c0cc71e15ef78d9eaf1f9155a0204202d#diff-14c8235d370910f1781de1a00ed1957ec948e84e88fdc52db87bd4eb7c7167ffL3416) breaks the old behavior.

### I expected the following

The headers are:
```
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Last-Modified: Fri, 22 May 2015 18:34:31 GMT
Accept-Ranges: bytes
ETag: "597cb7f1bd94d01:0"
Server: Microsoft-IIS/8.5
Date: Fri, 01 Oct 2021 16:57:05 GMT
Content-Length: 3822

```
CURLINFO_CONTENT_LENGTH_DOWNLOAD_T returns 3822 as it was in libcurl 7.77.0.

### curl/libcurl version

libcurl 7.79.1

### operating system

All

**Comment by bagder** [comment]
You've relied on undocumented behaviors - that's your right to do, but then you're also in a hole you dug yourself.

The `curl_easy_getinfo` is manpage is quote clear in my view:

>  The data pointed-to will be filled in accordingly and can be relied upon only if the function returns CURLE_OK. Use this function AFTER a performed transfer if you want to get transfer related data. 

This was a *bug-fix* as previously your application might've believed the prematurely reported `Content-Length` that could've been invalided a few headers down.

**Comment by sergio-nsk** [comment]
I use it in the header functions after the blank header is received. That quote can be understood ambiguousуly.
> if you want to get transfer related data.

Headers are transferred, Content-Length is a header related data.
