### ISSUE TITLE
 --pinnedpubkey for unsupported TLS backends

### ISSUE THREAD

**Issue by bagder** [curl/curl#781]
### I did this

Used  `--pinnedpubkey` with curl built with a TLS backend without support for it. But it doesn't complain on bad keys.

### I expected the following

It needs to warn or error out when the option is used without support in libcurl so that the problem is not silently ignored.

[Ray's initial patch for this](https://curl.haxx.se/mail/lib-2016-04/0074.html)

Also see this [additional gskit patch](https://curl.haxx.se/mail/lib-2016-04/0083.html)

I'm assigning you Jay since you were on track on this before. Let me know if you're not fine with that, then I can take over instead.

cc: @moparisthebest

**Comment by moparisthebest** [comment]
I'll paste and update this from my mailing list email as well:

these backends
implementations are unsupported:

axtls.c - looks unlikely to ever be supported after glance at docs
darwinssl.c - [stalled](https://stackoverflow.com/questions/36843572/public-key-bytes-from-seckeyref)
schannel.c - Ray said someone was working on this? who/where?

and these have partial support:

cyassl.c only support #ifdef KEEP_PEER_CERT
gskit.c only support pem/der, needs curlssl_sha256sum defined for hash
support

of course that leaves these with full support:

gtls.c
mbedtls.c
nss.c
openssl.c
polarssl.c

**Comment by bagder** [comment]
Committed a fix for this in commit 283babfaf8d8f. Please try it out and see if there's anything missing now.
