### ISSUE TITLE
Wrong error code 33 at http_code 504

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7831]
### I did this
I started the continue of HTTP-downloading:
curl.exe -A Mozilla/5.0 -C - --connect-timeout 20 -D Header.txt -o Win11_Russian_x64.iso -R -w "%{JSON}" -y 20 -Y 1024 "https://software-download.microsoft.com/db/Win11_Russian_x64.iso?t=8287814e-ba3f-4cda-a2eb-ad474064422f&e=1633731230&h=73429b0b1ca281f29b004dc27423c752"

** Resuming transfer from byte position 1170439685
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   357    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
{"content_type":"text/html","errormsg":"HTTP server doesn't seem to support byte ranges. Cannot resume.","exitcode":33,"filename_effective":"Win11_Russian_x64.iso","ftp_entry_path":null,"http_code":504,"http_connect":0,"http_version":"2","local_ip":"10.2.0.2","local_port":1037,"method":"GET","num_connects":1,"num_headers":6,"num_redirects":0,"proxy_ssl_verify_result":0,"redirect_url":null,"referer":null,"remote_ip":"152.199.19.160","remote_port":443,"response_code":504,"scheme":"HTTPS","size_download":0,"size_header":197,"size_request":230,"size_upload":0,"speed_download":0,"speed_upload":0,"ssl_verify_result":0,"time_appconnect":2.119492,"time_connect":0.308604,"time_namelookup":0.072753,"time_pretransfer":2.120117,"time_redirect":0.000000,"time_starttransfer":7.299083,"time_total":7.299657,"url":"https://software-download.microsoft.com/db/Win11_Russian_x64.iso?t=8287814e-ba3f-4cda-a2eb-ad474064422f&e=1633731230&h=73429b0b1ca281f29b004dc27423c752","url_effective":"https://software-download.microsoft.com/db/Win11_Russian_x64.iso?t=8287814e-ba3f-4cda-a2eb-ad474064422f&e=1633731230&h=73429b0b1ca281f29b004dc27423c752","urlnum":0,"curl_version":"libcurl/7.79.1 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.45.1 libgsasl/1.10.0"}

### I expected the following
The error code corresponding to the situation.  See «https://duckduckgo.com/?q=HTTP+code+504»
### curl/libcurl version
7.79.1
[curl -V output]
curl 7.79.1 (x86_64-pc-win32) libcurl/7.79.1 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.45.1 libgsasl/1.10.0
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10-21H1

**Comment by jay** [comment]
4xx and 5xx HTTP codes are not transfer errors. You can use [--fail](https://curl.se/docs/manpage.html#-f) to treat it as a transfer error.

[4.4 Why do I get downloaded data even though the web page doesn't exist?](https://curl.se/docs/faq.html#Why_do_I_get_downloaded_data_eve)
[4.20 curl doesn't return error for HTTP non-200 responses!](https://curl.se/docs/faq.html#curl_doesn_t_return_error_for_HT)
