### ISSUE TITLE
Multiple mail recipients documentation

### ISSUE THREAD

**Issue by mgendre** [curl/curl#784]
Hello,

I tried to send mails with the command line to multiple recipients in 1 curl command.

I've seen that repeating --mail-rcpt does the work but didn't find any documentation on [your web man page](https://curl.haxx.se/docs/manpage.html)

It may be great to add in your documentation that this option could be used multiple times

Best regards

**Comment by bagder** [comment]
Good idea. Any suggestion on what to say?

**Comment by mgendre** [comment]
> _--mail-rcpt <address> (SMTP) Specify a single address, user name or mailing list name._

Repeat this option for multiple recipients

**Comment by bagder** [comment]
Thanks, merged!
