### ISSUE TITLE
Curl crashing in function "ossl_connect_common" when multiple network calls are made in parallel.

### ISSUE THREAD

**Issue by sbanethia** [curl/curl#7850]
Crashed: Thread
0 libsystem_pthread.dylib 0x5948 pthread_rwlock_rdlock + 110
1 XYZ 0x259ac08 CRYPTO_THREAD_read_lock + 10241200
2 XYZ 0x251a184 int_err_get_item + 9714220
3 XYZ 0x2519f0c ERR_lib_error_string + 9713588
4 XYZ 0x2519cd4 ERR_error_string_n + 9713020
5 XYZ 0x260bbfc ossl_strerror + 10704036
6 XYZ 0x260c4e4 ossl_connect_common + 10706316
7 XYZ 0x2610538 Curl_ssl_connect_nonblocking + 10722784
8 XYZ 0x25e2df8 https_connecting + 10536608
9 XYZ 0x25e2d90 Curl_http_connect + 10536504
10 XYZ 0x25f0990 multi_runsingle + 10592824
11 XYZ 0x25f049c curl_multi_perform + 10591556
12 XYZ 0x25d8d28 curl_easy_perform + 10495440

_Operating Version_ : **IOS 15**
_Curl Version_ : **7.76.1**

**Issue : We are making multiple network calls(get/post/multipart)in multiple threads and it works but after some times it crashes when device goes into background.**

**Comment by sbanethia** [comment]
> What OpenSSL version are you using? Are you following the [threading rules](https://curl.se/libcurl/c/threadsafe.html)?
> 
> This is almost certainly a user-error.

Our current OpenSSL version is **OpenSSL 1.1.1k  25 Mar 2021**

**Comment by jay** [comment]
This doesn't look like a curl problem. It seems openssl is crashing obtaining a lock. As noted 1.1.x usually has locking built in if the OS supports it. Are you overriding their locking with your own?

**Comment by jay** [comment]
Closing because there is no indication that this is a curl problem.

**Comment by wonderffee** [comment]
Maybe your  app crash on exit, see https://github.com/curl/curl/issues/1055
