### ISSUE TITLE
curl hangs on SMB upload over stdin

### ISSUE THREAD

**Issue by mikeTWC1984** [curl/curl#7896]
### I did this
```sh
 cat test.txt | curl -T . smb://user:password@localhost/share/test.txt
```
This creates empty test.txt file on smb share and then curl hangs
Tried both Windows and Linux smb shares. Tried several curl versions on alpine, centos, ubuntu, but getting same issue.
### I expected the following
test.txt copied to smb share
Issue occurs only if piping file from stdin. Command like below works as expected
 ```sh
curl -T test.txt smb://user:password@localhost/share/test.txt
```
### curl/libcurl version

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system

Linux  5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mback2k** [comment]
My guess would be that curl needs to know the final file size before creating the file via SMB, therefore dynamic input from `stdin` may not be supported.

**Comment by bagder** [comment]
Added to `KNOWN_BUGS`.
