### ISSUE TITLE
Configure flag --without-zsh-functions-dir ignored

### ISSUE THREAD

**Issue by andrewrynhard** [curl/curl#790]
### I did this
./configure --prefix=/usr/local --without-zsh-functions-dir
### I expected the following
successful build when perl is not installed
### curl/libcurl version
7.48

### operating system
Built in a chroot

I get the following error:
````
Making all in scripts
No perl: can't install zsh.pl
/bin/sh: ./zsh.pl: /usr/bin/perl: bad interpreter: No such file or directory
make[1]: *** [_curl] Error 126
Makefile:549: recipe for target '_curl' failed
make: *** [all-recursive] Error 1
Makefile:890: recipe for target 'all-recursive' failed
````

**Comment by bagder** [comment]
Fixed in git since commit ccfa8407a67
