### ISSUE TITLE
option --data-urlencode: out of memory

### ISSUE THREAD

**Issue by SnehaBheemireddy** [curl/curl#7915]
### I did this
for PDB in *.pdb; 
	do
  	curl --data-urlencode pdb@${PDB} --data forcefield=FF99 --data environment=SOLVENT --data hydrogens=ADD --output ${PDB%pdb}zip --post302 --location https://bioinfo.uochb.cas.cz/INTAA/energy/download/data.zip;
	done

[1ir2.txt](https://github.com/curl/curl/files/7431563/1ir2.txt)

Please rename 1ir2.txt as 1ir2.pdb!

### I expected the following
Expected it to download a zip

### curl/libcurl version
curl 7.71.1 (x86_64-conda_cos6-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1h zlib/1.2.11 libssh2/1.9.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

### operating system
Linux gnr 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
I build from HEAD and ran a similar command locally (to a local server) and curl used 8.5MB of RAM at peak. Even changing the argument to --data-urlencode @1ir2.pdb (so it posts the data from the file) it "only" required about 31 MB. Are you running the command on a ram-limited machine? What is the output of "free;ulimit"?

**Comment by bagder** [comment]
@SnehaBheemireddy your machine probably for some reason actually runs out of memory and then curl outputs this message. It's not a bug, it's working as intended.

**Comment by jay** [comment]
@SnehaBheemireddy If you do not think it is actually running out of memory then you can build [the latest curl](https://curl.se/download.html) with --enable-debug and walk through the code starting [here](https://github.com/curl/curl/blob/curl-7_79_1/src/tool_getparam.c#L1372) to find out what exactly causes the out of memory result.
