### ISSUE TITLE
Test 1112 seems to be main source of CI failures on Windows

### ISSUE THREAD

**Issue by mback2k** [curl/curl#7919]
### I did this

Checked the [Azure DevOps Test failure report](https://dev.azure.com/daniel0244/curl/_test/analytics?definitionId=1&contextType=build) for the last 14 days and tests ran from the master branch:

<img width="1146" src="https://user-images.githubusercontent.com/231943/139280139-30cb9a40-597c-424d-9378-3d6d4b630df2.png">

Example test logs:
https://dev.azure.com/daniel0244/curl/_build/results?buildId=7572&view=logs&j=bd08dbef-08e3-5745-a81d-7c3800301c2d&t=76cab039-f851-5b33-4624-8c2f90dc0d9c&l=2132
https://dev.azure.com/daniel0244/curl/_build/results?buildId=7572&view=logs&j=6a6ea3eb-38f1-597e-37da-5b989815a2b5&t=2286d0ab-4abf-561d-a3b7-391498212136&l=1793
https://dev.azure.com/daniel0244/curl/_build/results?buildId=7572&view=logs&j=d92e4884-bf10-5ffa-02e6-2c5b330d9917&t=d1ab0fcf-55eb-5d3e-6812-6a91adffb8c7&l=1793

Potentially there is a relation to the error "ftps server unexpectedly alive".

### I expected the following

Test 1112 to be working stable on Windows, especially after all the improvements to socket-handling on Windows this year.

I am just putting this here as a heads up that this is right now the most prominent source of CI failures on Windows and maybe people can join me in trying to fix this.

**Comment by bagder** [comment]
and news on this @mback2k ?

**Comment by mback2k** [comment]
Unfortunately not yet due to me being fully pulled into work since middle of November. I am trying to get back to improving the tests and Windows CIs again once time frees up. Unfortunately I don't have an ETA for that yet, sorry.

**Comment by mback2k** [comment]
Looking at the last 14 days now it no longer seems like test 1112 is sticking out:
![image](https://user-images.githubusercontent.com/231943/147888273-42a0cdfc-15f4-4746-82b0-119f8a324bed.png)

Grouped by build variant it again looks very random to me:
![image](https://user-images.githubusercontent.com/231943/147888312-95b69960-ab90-44b9-91c9-ed96ccc89784.png)

**Comment by mback2k** [comment]
Closing this as there still does not seem to be a single problematic test case anymore.
