### ISSUE TITLE
Possible improper locking issues

### ISSUE THREAD

**Issue by ryancaicse** [curl/curl#7926]
HI, in this function, it is possible that the lock `lock` **(Line 71)** is not released properly because the execution does not enter the `while(j < num_urls)`? Also, it also seems that the lock `lock` could be released multiple times in the while loop at **Line 97**.

Thanks for checking.

https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/docs/examples/smooth-gtk-thread.c#L68-L113

**Comment by bagder** [comment]
It does indeed look very wrong. You up for writing a pull request and fix it?

**Comment by ryancaicse** [comment]
Sorry, I don't know which is the best way to fix them due to being unaware of the shared data protected by the lock. But, here is my try. Is this enough to fix this issue?
```
 void *pull_one_url(void *NaN) 
 { 
   /* Stop threads from entering unless j is incremented */ 
   pthread_mutex_lock(&lock); 
   while(j < num_urls) { 
     ...;
     if(curl) { 
      ...;
       pthread_mutex_unlock(&lock); 
  
       ...;
       pthread_mutex_lock(&lock); // new added
     } 
     ...;
   } /* end while */ 
    pthread_mutex_unlock(&lock); // new added
   return NULL; 
 }
```

**Comment by bagder** [comment]
I think it needs more than that. See #7931 for my proposed fix.

**Comment by ryancaicse** [comment]
OK, thanks
