### ISSUE TITLE
Unexpected behaviour when combing --create-dirs and --etag-compare/--etag-save

### ISSUE THREAD

**Issue by Earnestly** [curl/curl#7942]
### I did this
With the following config file:
```
url https://www.youtube.com/feeds/videos.xml?channel_id=UCl9OJE9OpXui-gRsnWjSrlA
etag-save bar/etag
etag-compare bar/etag
output bar/xml
next
url https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g
etag-save foo/etag
etag-compare foo/etag
output foo/xml
```

I used:

```
% mkdir bar
% curl --create-dirs -ZK - < config
Warning: Failed to open foo/etag
curl: (23) Failed writing received data to disk/application
curl: (23) Failed writing received data to disk/application
```

### I expected the following

It appears that all multiplexed connections to youtube will fail if the parent directory of the `etag` file doesn't exist for one of the config sections.

The most ideal result would be that curl would create the leading directory for the etag file just as it would for `--output`.

### curl/libcurl version
```
curl 7.79.1 (x86_64-pc-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.46.0
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system
```
Linux teapot 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64 GNU/Linux
```

**Comment by dfandrich** [comment]
--create-dirs is clearly documented to NOT create such directories, and I'm
personally hesitant to make it do so. There are a number of config files that
curl uses like this one, and in most cases they will exist before curl starts.
There are probably also people who rely on the current error behaviour to catch
typos, etc.  The difference between config files and data files is a big one,
as typically a single configuration is used to download multiple files, making
--create-dirs more broadly useful. I don't think it's a big imposition for the
user to ensure that the directories that explicitly specified already exist,
but if this feature were added, it should probably be with a new option.

**Comment by bagder** [comment]
I'm with @dfandrich. This is only unexpected if you didn't read the documentation, and changing the behavior like this would cause new undesired side-effects.

**Comment by Earnestly** [comment]
`--etags-create-dirs`?  Heh

**Comment by dfandrich** [comment]
"mkdir foo" is shorter :-)

**Comment by bagder** [comment]
> Additionally should curl outright fail if it cannot write an etag?

That can certainly be discussed, but I took that decision so that the issue gets very obvious to the user. After all, the user asked for the file to get saved and the saving of it failed.

> Could also the error message be clearer?

Yes indeed. How about instead using this:

`"Failed creating file for saving etags: %s"`

**Comment by Earnestly** [comment]
This is very much not obvious when using `--parallel`, as i've mentioned every time.  If only one of the requests lacks a directory, should all the others which don't also fail?

@dfandrich I'm not really amused by these comments.

**Comment by bagder** [comment]
> This is very much not obvious when using --parallel

I'm not sure what **This**  refers to here. You mean the failing of the transfer?

**Comment by Earnestly** [comment]
Both the failing transfer and the related error messages

**Comment by bagder** [comment]
I don't understand what you're saying. What else do you think curl should do?

**Comment by Earnestly** [comment]
The other requests should succeed as their directories exist.

**Comment by bagder** [comment]
> The other requests should succeed as their directories exist

Yes they should. Do you have a setup/command line where one transfer's failure impacts others?

> if the "create-dirs" feature isn't going to create directories in a consistent manner across all flags

It isn't and it can't. It is documented to only create directories for `--output`.

**Comment by Earnestly** [comment]
My reproduction example in the first post shows both youtube urls failing despite the directory existing for one of them.

**Comment by bagder** [comment]
I can reproduce. The issue here is that the failure is detected already when setting up the transfer, which the code right now counts as an error serious enough to stop for.

I've played a little to make the code just ignore the transfer for which the etag file cannot be created, but I need to then also add some extra logic to make it return an error if that is the *only* transfer done...

**Comment by bagder** [comment]
The etag save issue has been fixed in git. I think that then closes this issue.
