### ISSUE TITLE
curl tip does not compile with rustls-ffi tip

### ISSUE THREAD

**Issue by kevinburke** [curl/curl#7947]
Using rustls-ffi commit 60d9c2adcbe26cbcb3f6ee4c32cc79ca85c1b9c1, and curl commit 90e74206b98180b7a185d83d6d20071190e2df59, I get the following compile errors:

```
vtls/rustls.c: In function 'cr_init_backend':
vtls/rustls.c:312:3: error: implicit declaration of function 'rustls_client_config_builder_set_protocols'; did you mean 'rustls_client_config_builder_set_alpn_protocols'? [-Werror=implicit-function-declaration]
  312 |   rustls_client_config_builder_set_protocols(config_builder, alpn, 2);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   rustls_client_config_builder_set_alpn_protocols
vtls/rustls.c:312:3: warning: nested extern declaration of 'rustls_client_config_builder_set_protocols' [-Wnested-externs]
vtls/rustls.c: In function 'cr_set_negotiated_alpn':
vtls/rustls.c:360:3: error: implicit declaration of function 'rustls_connection_get_alpn_protocol'; did you mean 'rustls_connection_alpn_protocol'? [-Werror=implicit-function-declaration]
  360 |   rustls_connection_get_alpn_protocol(rconn, &protocol, &len);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   rustls_connection_alpn_protocol
vtls/rustls.c:360:3: warning: nested extern declaration of 'rustls_connection_get_alpn_protocol' [-Wnested-externs]
vtls/rustls.c: At top level:
vtls/rustls.c:553:3: warning: initialization of 'size_t (*)(char *, size_t)' {aka 'long unsigned int (*)(char *, long unsigned int)'} from incompatible pointer type 'struct rustls_str (*)(void)' [-Wincompatible-pointer-types]
  553 |   rustls_version,                  /* version */
      |   ^~~~~~~~~~~~~~
vtls/rustls.c:553:3: note: (near initialization for 'Curl_ssl_rustls.version')
```

I believe that these are due to a recent refactoring in rustls-ffi. I will submit a PR shortly, but wanted to create a tracking issue first.

I believe that we don't currently have a compatibility guarantee with rustls/rustls-ffi besides "you should target the most recent commit" so that's what I'll target as well.

CC @jsha

**Comment by jsha** [comment]
> I believe that these are due to a recent refactoring in rustls-ffi.

Yes, that's correct. curl currently depends on 0.7.0 of rustls: https://github.com/curl/curl/blob/master/docs/RUSTLS.md, and we haven't yet done the work to update to the new APIs established with the upgrade to rustls 0.20.

If you're planning to submit a PR to curl, I think we should wait until we have a new version of rustls-ffi released. To do that, I'd like to do a cleanup round and make sure all the API changes are as we'd like them, then do the release. If you have time to do a thorough lookthrough of the API changes and give feedback on what might need to be cleaned up, I'd definitely appreciate that!
