### ISSUE TITLE
`curl --limit-rate -T` does not effectively limit upload transfer rate for small files

### ISSUE THREAD

**Issue by wnrph** [curl/curl#7965]
### I did this
```terminal
$ small_file=$(mktemp); echo "very small file" > $small_file; wc -c $small_file
16 /tmp/tmp.z6w5UAxAV6

$ curl -v -H Expect: --limit-rate 1 -T $small_file http://httpbin.org/put
*   Trying 54.156.165.4:80...
* TCP_NODELAY set
* Connected to httpbin.org (54.156.165.4) port 80 (#0)
> PUT /put HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 16
> 
* We are completely uploaded and fine
```
Curl produced the log output (including the last line) immediately. I also captured network traffic with tcpdump which confirmed that the file was sent immediately without limiting the rate.

I get the same result when using the `--no-buffer` option

### I expected the following
I expected curl to limit the rate at which bytes were transmitted. At one byte per second the header and a 16 byte file should take at least a minute or so to upload

### curl/libcurl version
```terminal
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
#### uname -a
Linux 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
#### lsb_release
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by bagder** [comment]
Correct, and I think the best "fix" for this is to enhance the documentation to set the expectations right.

The rate limiting logic works on *averaging* the transfer speed to (no more than) the set limit of bytes/sec over a period of multiple seconds. For very small transfers or very quick ones, curl will not do a very accurate job. I don't think it is worth a lot of effort to make curl better at this.

**Comment by wnrph** [comment]
Well you're description seems not to match what is being done in `Curl_buffer_send` (http.c):

```c

  /* Make sure this doesn't send more /*
 * Curl_buffer_send() sends a header buffer and frees all associated
 * memory.  Body data may be appended to the header data if desired.
 *
 * Returns CURLcode
 */
CURLcode Curl_buffer_send(struct dynbuf *in,
                          struct Curl_easy *data,
                          /* add the number of sent bytes to this
                             counter */
                          curl_off_t *bytes_written,
                          /* how much of the buffer contains body data */
                          curl_off_t included_body_bytes,
                          int socketindex)
{
/*
:
:
*/

    /* Make sure this doesn't send more body bytes than what the max send
       speed says. The request bytes do not count to the max speed.
    */
    if(data->set.max_send_speed &&
       (included_body_bytes > data->set.max_send_speed)) {
      curl_off_t overflow = included_body_bytes - data->set.max_send_speed;
      DEBUGASSERT((size_t)overflow < size);
      sendsize = size - (size_t)overflow;
    }
    else
      sendsize = size;

}
```

**Comment by wnrph** [comment]
Well it seems code snippet I've cited is pretty new and was added in [response](https://github.com/curl/curl/pull/6797) to a [similar bug report](https://curl.se/mail/lib-2021-03/0042.html)

**Comment by bagder** [comment]
> Well your description seems not to match what Curl_buffer_send (http.c) does

Feel free to rerun your example on the latest curl release then. It still won't limit the rate to one byte per second for tiny uploads.

**Comment by bagder** [comment]
If someone wants to work on improving this logic, I would be fine with that as long as the changes aren't intrusive or massive. Until then I think we can keep it as-is, now documented a little more to better convey its functionality.
