### ISSUE TITLE
Lying manual

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#7985]
### I did this
Readed in manual, that «-I, --head» and «-i, --include».  Started bugged prog to query header:
curl.exe -I -J "И вечный глюк"
curl: --include and --remote-header-name cannot be combined
curl: try 'curl --help' or 'curl --manual' for more information
### I expected the following
The manual was written by honest people, not liars.
### curl/libcurl version
7.79.1_4
[curl -V output]
curl 7.79.1 (x86_64-pc-win32) libcurl/7.79.1 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 libgsasl/1.10.0
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
### operating system
MS Windows 10

**Comment by bagder** [comment]
Banned used for 7 days for repeated use of offensive language.
