### ISSUE TITLE
Curl CMake script uses identifiers reserved by CMake.

### ISSUE THREAD

**Issue by Boris-Rasin** [curl/curl#7988]
From here: https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html
```
CMake reserves identifiers that:
    begin with CMAKE_ (upper-, lower-, or mixed-case)
```
Following identifiers are declared by curl CMake script (there may be more):

CMAKE_USE_SCHANNEL
CMAKE_USE_SECTRANSP
CMAKE_USE_OPENSSL
CMAKE_USE_MBEDTLS
CMAKE_USE_BEARSSL
CMAKE_USE_NSS
CMAKE_USE_WOLFSSL

I suggest changing these identifiers to use CURL_ prefix instead:

CURL_USE_SCHANNEL
CURL_USE_SECTRANSP
CURL_USE_OPENSSL
CURL_USE_MBEDTLS
CURL_USE_BEARSSL
CURL_USE_NSS
CURL_USE_WOLFSSL

### curl/libcurl version

7.80.0

**Comment by jzakrzewski** [comment]
I'm all in for the change. Just note that it'll break scripts (if any) that build curl using CMake.
