### ISSUE TITLE
Connection though proxy app fails

### ISSUE THREAD

**Issue by squromiv** [curl/curl#7989]
I try to use Curl with https proxy software named HandyCache. 
Result of attempt to connect though proxy to "https://httpbin.org/ip":
[Curl v. 7.79.1](http://s01.geekpic.net/di-D8WXJW.jpeg)
[Curl v.7.40](http://s01.geekpic.net/di-2QSY1R.jpeg)
So old version is able to work, but one of the last versions fails.
Windows 8.1x64

**Comment by bagder** [comment]
I suspect you're proxy isn't a HTTPS proxy at all. The reason 7.40 worked is because it ignored the scheme in the proxy string and connected to it as a HTTP proxy - 7.40 didn't have https proxy support.

**Comment by squromiv** [comment]
Sorry, I attached wrong screenshots. Please, check another one for v. 7.40.
[Screen](http://s01.geekpic.net/di-2QSY1R.jpeg)
Actually, it works with HTTPS, as I understand. Also, I can see relevant entries in log-files of proxy.

**Comment by bagder** [comment]
"HTTPS proxy support via `https://` protocol prefix was added  in 7.52.0"

Your proxy is a HTTP proxy. Of course HTTPS to the *server* still worked. Just not HTTPS to the proxy. Trying to speak HTTPS to a HTTP proxy won't work though.

**Comment by jay** [comment]
Please put the curl output in the post, don't link to a screenshot of it

I think the confusion is because the `https://` scheme was ignored in older versions. That is noted in the manual for [`-x, --proxy [protocol://]host[:port]`](https://curl.se/docs/manpage.html#-x)

> Unrecognized and unsupported proxy protocols cause an error since 7.52.0. Prior versions may ignore the protocol and use http:// instead.

So try `-x 192.168.10.30:9054`

**Comment by bagder** [comment]
Closed. This behavior is documented.
