### ISSUE TITLE
rustls backend fails test 312

### ISSUE THREAD

**Issue by bagder** [curl/curl#8004]
### I did this

- Build with rustls-ffi 0.8.0
- Run test 312
- See how the test case fails

~~~
test 0312...[HTTPS GET to localhost and null-prefixed CN cert]

curl returned 35, when expecting 60
 exit FAILED
~~~

Also visible in CI builds [like here](https://curl.zuul.vexxhost.dev/build/e051cdafa74344af86e4b24f336d4ffd)

### I expected the following

It should work.

### curl/libcurl version

current git master

### operating system

Linux, but should be universal

**Comment by bagder** [comment]
This happens because `rustls_connection_process_new_packets()` returns 7120.

7120 is stored in `rresult` and is then converted to a CURLcode with the `map_error` function.

The `map_error` function calls `rustls_result_is_cert_error()` but does not consider 7120 to be a cert error and returns `CURLE_READ_ERROR` for this instead of `CURLE_PEER_FAILED_VERIFICATION`. I think this is a mistake because this really is a cert error. The cert is bogus/broken.

Since crustls.h doesn't provide any defines or other ways to work with 7120 I assume we are not meant to use it directly and map that ourselves.

This then requires one of these to happen:
1. the error codes to get accessible
2. rustls-ffi to change and consider 7120 a cert error
3. we modify the test case to accept another return code in the rustls case

**Comment by jsha** [comment]
> rustls-ffi to change and consider 7120 a cert error

[I'll do this](https://github.com/rustls/rustls-ffi/issues/226).

**Comment by bagder** [comment]
Thanks! :+1:

**Comment by bagder** [comment]
@jsha any chance this is fixed soon? Otherwise I'll go ahead and disable the test for rustls bulds.

**Comment by jsha** [comment]
Interesting. I fixed this in #227. I'm surprised the test case is still failing. I'll look at it.

**Comment by bagder** [comment]
@jsha we're still using 0.8.2, is that maybe why?

**Comment by jsha** [comment]
Aha, I actually need to cut a new release with the fix. Thanks!
