### ISSUE TITLE
CURLE_URL_MALFORMAT when URL contains spaces

### ISSUE THREAD

**Issue by VladimirPlus** [curl/curl#8015]
### I did this
curl --ftp-ssl -k "ftp://localhost/src_folder/New folder/" --user xxx:yyy
curl: (3) URL using bad/illegal format or missing URL

The bug can be reproduced if URL contains at least one space symbol.
Otherwise content of folder outputs correctly.

### curl/libcurl version
curl 7.80 has been compiled from source codes.

### operating system
Win10 x64

**Comment by bagder** [comment]
A URL can in fact not legally contain spaces. It needs to be passed in encoded like %20. We recently made the URL parser slightly more strict in this regard.

**Comment by VladimirPlus** [comment]
OK, but according to RFC 3986, "ftp://localhost/src_folder/New folder/" must be represented as "ftp%3A%2F%2Flocalhost%2Fsrc_folder%2FNew%20folder%2F". Isn't it?
Or CURL escapes just strings between path delimiters?

Also, FTP servers use different charset encoding, depends on system settings.
So CURLOPT_URL in curl_easy_setopt must be defined in used charset on server side.
This statement counters CURL requirements to encoding URL in RFC 3986.

I guess you need to add some settings or policies to control content of CURLOPT_URL more precisely.
For now, I'll use 7.79.1 because I can use different charsets depends on FTP settings.

Thanks for your job, Daniel.

**Comment by bagder** [comment]
> OK, but according to RFC 3986, "ftp://localhost/src_folder/New folder/" must be represented as "ftp%3A%2F%2Flocalhost%2Fsrc_folder%2FNew%20folder%2F". Isn't it?

Not at all.

>  Or CURL escapes just strings between path delimiters?

curl parses the URL! If you read the spec you see that the colons and slashes are fine in there but the space is not.

> Also, FTP servers use different charset encoding, depends on system settings.

I don't see how that is relevant.

>  For now, I'll use 7.79.1 because I can use different charsets depends on FTP settings.

You do what you think is best for you, but 7.79.1 and 7.80.0 support different charsets over FTP exactly the same (non-existant) way.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;I remember &#x60;curl&#x60; was once unable to properly handle "/" (Solidus) (U+002F, 0x2F, &amp;<span>#</span>47;) in HTTP GET parameters. (mistreating which as Directory Separators of path)
&#xA0;&#xA0;&#xA0;&#xA0;The behavior is no more reproducible with &#x60;curl&#x60; 7.82 onward. While it was still reproducible with 7.72 (perhaps 7.75?).
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Could someone please point out the commit (or approximate &#x60;curl&#x60; version) that had the issue addressed?

**Comment by bagder** [comment]
@MasterInQuestion I don't recognize that as a (past) problem. Also this is a closed issue about something else.
