### ISSUE TITLE
 Documentation is unclear how curl works under TLS hostname validation under the case of SNI (Server name indication)

### ISSUE THREAD

**Issue by edwardt** [curl/curl#8026]
It is not clear from documentation how the library works under TLS hostname validation under the case of SNI (Server name indication). Does it use the hostname set by SNI extension used in hostname validation or it is not used? It will be great if it also reference which/what RFCs for justification.

**Comment by edwardt** [comment]
@bagder I will let you decide where to document it. There are legacy use cases where people still use SNI. It is better to surface this information and let them decide their next step.

**Comment by bagder** [comment]
legacy? SNI is used widely all over, in just about every HTTPS use case. I honestly don't understand what you want to have documented about it.
