### ISSUE TITLE
Max TLS1.1 but OUT is TLS 1.3 (like #5356), but openssl works (RHEL 8.4)

### ISSUE THREAD

**Issue by juspence** [curl/curl#8032]
### I did this
Similar to https://github.com/curl/curl/issues/5356, I ran:
$ curl --tlsv1 --tls-max 1.0 https://example.com/
$ openssl s_client -tls1 -connect example.com:443

### I expected the following
A working connection in curl and openssl, but I got:
curl: (35) error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available

The openssl connection worked fine, so I think this is a bug in curl and not in openssl (different than #5356).

### curl/libcurl version
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

openssl version
OpenSSL 1.1.1g FIPS  21 Apr 2020

### operating system
4.18.0-305.19.1.el8_4.x86_64 (RHEL 8.4)

**Comment by dfandrich** [comment]
Are you sure both curl and the openssl command-line tool are using the same
OpenSSL library version? Does this happen with a recent curl version? 7.61.1 is
over 3 years old and there have been over 2600 bug fixes since then.

**Comment by juspence** [comment]
@dfandrich Both versions above report OpenSSL 1.1.1g. This is a RHEL system so I can't upgrade to a newer version of curl - the one I'm using is the most recent one available. I can check for newer CentOS RPMs and try with those in a bit.

**Comment by dfandrich** [comment]
You could also try compiling curl 7.80.0 against that OpenSSL version just to see
if the problem goes away. If so, then you can contact Red Hat to back-port the
fix.

**Comment by bagder** [comment]
That command line works just fine with my tests using 7.79.1 and 7.80.0 with OpenSSL on Linux.

**Comment by juspence** [comment]
Thanks for confirming, and sorry for the delay in getting back. I'll open a ticket with Red Hat to backport a fix.
