### ISSUE TITLE
curl tries to read known_hosts from wrong location

### ISSUE THREAD

**Issue by jeffrson** [curl/curl#8033]
### I did this
curl -u user:pass -T file.dat sftp://host.domain.tld/folder

### I expected the following

upload "file.dat" to host.domain.tld/folder

### what happened

although host.domain.tld is contained in known_hosts there's an error message:
curl: (60) SSL peer certificate or SSH remote key was not OK

AFAICT, curl tries to load known_hosts from %APPDATA%\\.ssh (user\\AppData\\Roaming\\.ssh), while it should look at %USERPROFILE%\\.ssh (user\\.ssh), which is user's actual home folder and is used by OpenSSH integrated in Windows as well.

BTW, would be great to have an example of how to get the hash for --hostpubmd5 and --hostpubsha256 in the documentation (ie, what data to hash exactly).

### curl/libcurl version

[curl -V output]
```
curl 7.80.0 (x86_64-pc-win32) libcurl/7.80.0 OpenSSL/3.0.0 (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.46.0 libgsasl/1.10.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets zstd
```

### operating system

Windows 10 21H1

**Comment by bagder** [comment]
> it should look at %USERPROFILE%\.ssh

Is this practice/order documented or mandated somewhere official? curl has preferred `APPDATA` to `USERPROFILE` for finding the user's "home dir" since 8be602cdfd, **18** years ago...

**Comment by jeffrson** [comment]
Well, that's interesting.

I'm just using curl with SFTP for the first time and I stumbled across the certificate warning. So I was going to research.

So what does it mean "official"?
Some tools want to follow [XDG base directories](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), other tools try to mimic Linux behaviour by using %USERPROFILE% as $HOME (that's what sounds reasonable to me). Yet another tools rely on explizit %HOME%.

Also, there hasn't been "official" SSH until a few years ago in some Windows 10 update. Now, this ssh is using %USERPROFILE%\\.ssh and I think it's practical to use the same data in curl as well, isn't it? It's not really useful to have two different known_hosts.

BTW, IMO it's not too well documented that curl is using %APPDATA%. I actually had used Procmon to check whether it reads my known_hosts file.

Do you know of other apps search .ssh at %APPDATA%?

Maybe you could read %USERPROFILE%\\.ssh, if the other does not exist? Or if it doesn't contain known_hosts?

**Comment by bagder** [comment]
curl also never actually use `%USERPROFILE%` now, it always uses `%USERPROFILE%\Application Data` - if `APPDATA` isn't set.

**Comment by bagder** [comment]
@jeffrson, Would you be able to try out #8035  ?

**Comment by jeffrson** [comment]
Great work, thank you very much!

Unfortunately I don't have any local builds for curl :-( and I'm afraid I can't set it up in the short term either.

Also I could not find a nightly or autobuild version - can you recommend one?
