### ISSUE TITLE
--dump-header causes error when used within a config file

### ISSUE THREAD

**Issue by vd4** [curl/curl#8037]
-D or --dump-header causes error (23) when used within a config file and specifies a fullpathname (windows curl 7.80.0 32bit).
It works fine when used from command line or when a plain filename is used.

**Comment by bagder** [comment]
Can you please give us an example of what you've tried?

**Comment by vd4** [comment]
Trying to describe in details the problem, I realised that inside the
config file our code created a line
--dump-header "c:\tmp\prosyfape\test\header.txt"
instead of the correct
--dump-header "c:\\tmp\\prosyfape\\test\\header.txt"

So there is no bug.
Please accept our apologies, and thank you very much for your quick reply.

Vassilis Dimitriadis

Στις Παρ, 19 Νοε 2021 στις 11:48 μ.μ., ο/η Daniel Stenberg <
***@***.***> έγραψε:

**Comment by bagder** [comment]
Ah, excellent. Yes I suspected that could've been the case. Thanks for confirming. Closing this!
