### ISSUE TITLE
curl/libcurl does not honor RFC 3484/6724 and resolves addresses in unexpected order

### ISSUE THREAD

**Issue by Roguelazer** [curl/curl#808]
### I did this

Created a DNS record containing a mixture of A and AAAA records which resolved to addresses in different networks, then attempt to use curl against that name.

### I expected the following

I expected curl to resolve that name to the "best" address as per [RFC 3484](https://www.ietf.org/rfc/rfc3484.txt)/[RFC 6724](https://tools.ietf.org/html/rfc6724), preferably also honoring my custom preferences set in `/etc/gai.conf`. Lacking that, I would at least prefer to get the default c-ares behavior when `AF_UNSPEC` /`PF_UNSPEC` is passed (try AAAA first and only perform an A lookup if the AAAA lookup fails).

The specific offending behavior is in `asyn-ares.c`, which dispatches an A and an AAAA request in parallel (with the A request being issued first by about 90µs on my hardware), and then returns results based solely on which request returns first. So far as I can tell, no attempt is made to sort the results (the `compound_results` function merely appends results in-order to a linked list).

At the very least, it would be nice to be able to tell curl to *prefer* IPv6 addresses when both IPv4 and IPv6 addresses are available (without entirely disabling IPv4 resolution the way CURL_IPRESOLVE_V6 does).

### curl/libcurl version

> curl 7.43.0 (x86_64-redhat-linux-gnu) libcurl/7.43.0 OpenSSL/1.0.1e zlib/1.2.3 c-ares/1.10.0 libidn/1.18 libssh2/1.4.2
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

Based on the code, I expect the same behavior from cURL 7.48.0

### operating system

CentOS 6.7 + various backports

**Comment by bagder** [comment]
This is actually a limitation in c-ares which doesn't offer a proper `getaddrinfo` alternative, it is not libcurl's job. If you rebuild with the threaded or synchronous resolver backends you'll notice that it works.

**Comment by Roguelazer** [comment]
libcurl could at least pass through the AF_UNSPEC and give c-ares a chance. As it stands, c-ares only gets explicit and separate AF_INET and AF_INET6 lookups. 

-- 
James Brown,
currently mobile

**Comment by bagder** [comment]
Sure it could, but it wouldn't make any difference with the current c-ares implementation as you'll find out if you try it or just read the c-ares source code. libcurl uses c-ares like that because of the c-ares limitations, not because we think it is great. We couldn't *just* use `AF_UNSPEC` anyway.

If c-ares would get this ability, we would of course adjust the libcurl code to make sure it takes advantage of it.

**Comment by Roguelazer** [comment]
In c-ares (at least master and 1.10.0, I haven't looked to see when this was added), a lookup with `AF_UNSPEC` will explicitly prefer AAAA/IPv6 records over A/IPv4 records. It's not as good as actually implementing proper gai behavior, but it's a step in the right direction from my perspective.

[ares_gethostbyname.c:139](https://github.com/c-ares/c-ares/blob/master/ares_gethostbyname.c#L139)

**Comment by bagder** [comment]
Then please suggest a patch because I can't see it working. Even if I would prefer a patch for c-ares that makes it do the right thing on its own...

**Comment by bagder** [comment]
This is a limitation in c-ares. The moment c-ares supports this properly, we should adapt our code accordingly.
