### ISSUE TITLE
URL fragments are discarded by curl, also despite --path-as-is

### ISSUE THREAD

**Issue by dune73** [curl/curl#8080]
Submitting an URI fragment as part of a request is obviously stupid. But it has its uses in security testing. And having `--path-as-is` trigger this behavior seems to be the most natural approach to this for me (even if I am aware it's `--path-as-is` and not `--uri-as-is`).

### I did this

`curl --verbose --path-as-is "http://localhost/index.html#fragment"`

### I expected the following

```
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /index.html#fragment HTTP/1.1
...
```

### curl/libcurl version

curl 7.71.1

### operating system

Linux leander 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
curl does this because the fragment in a URL is not part of the path that is sent in the HTTP request to the server. The fragment string is for the browser to keep locally to find a place in the document/content from that URL

**Comment by bagder** [comment]
If you want `#` as part of a path, send it as `%23` or craft your own request target with `--request-target`.

**Comment by dune73** [comment]
Thank you. `--request-target` does the job. Closing this.

**Comment by ignaciogutierrez** [comment]
Use ```--request-target``` as this:
```bash
curl -si http://localhost  --request-target http://localhost/index.html#fragment
```
