### ISSUE TITLE
Disable msys2 path interpretation in Cirrus CI

### ISSUE THREAD

**Issue by jay** [curl/curl#8084]
### I did this

[This test failure](https://cirrus-ci.com/task/5748643199188992?logs=test#L2926) from Cirrus CI shows test3021 failing:

` curl: (60) Denied establishing ssh session: mismatch sha256 fingerprint. Remote �z�i/XEa"��P�R��h�]��wl�q��) is not equal to C:/msys64/Ad6smkvWEVhIs/nUM1S2fOjaL9djxb6d2zkcbQUgik`

The error message is supposed to show two sha256 fingerprints in base64 format. The gibberish came from a printing mistake and I landed 3467e89b to fix it. The reason the match failed was not because of that but because one of the keys is `C:/msys64/Ad6smkvWEVhIs/nUM1S2fOjaL9djxb6d2zkcbQUgik`, note the erroneous `C:/msys64/`. There should be just a base64 string there.

Tracing it back I don't see anything unusual.
https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/lib/vssh/libssh2.c#L623
https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/tests/data/test3021#L27
https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/tests/runtests.pl#L2291-L2294
https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/tests/sshserver.pl#L402-L404

### I expected the following

My guess is this has something to do with msys2 path interpretation. Maybe the base64 string had a leading / and so msys2 converted that to `C:/msys64/`. There is an msys2 environment variable MSYS2_ARG_CONV_EXCL that can be set to stop msys2 from tampering with arguments. That is already done in appveyor configs, for example:

https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/appveyor.yml#L145

I think that should be done for Cirrus CI as well.

**Comment by MarcelRaad** [comment]
I added that for the MSYS-based CMake builds because of https://github.com/curl/curl/blob/82d334001f1069b08f72797350fffd6c9f81526a/src/CMakeLists.txt#L48. If it's needed for a test, it should be set by the test itself to also work outside of our CI system. See e.g. https://github.com/curl/curl/pull/2765/files.

**Comment by jay** [comment]
Unfortunately this is still an issue, but much less so. For example [this test 3021 CI failure](https://dev.azure.com/daniel0244/5571c33c-81e1-43d7-93ee-d3d4152f27b2/_apis/build/builds/8396/logs/162):

~~~
2022-01-23T11:16:54.9314783Z  11:16:54.265727 == Info: SSH SHA256 public key: +C:/msys64/EYG2YDzDGm6yiwepEMSuExgRRMoTi8Di1UN3kixZw
2022-01-23T11:16:54.9317248Z  11:16:54.265745 == Info: SSH SHA256 fingerprint: +/EYG2YDzDGm6yiwepEMSuExgRRMoTi8Di1UN3kixZw=
2022-01-23T11:16:54.9319293Z  11:16:54.265754 == Info: Denied establishing ssh session: mismatch sha256 fingerprint. Remote +/EYG2YDzDGm6yiwepEMSuExgRRMoTi8Di1UN3kixZw= is not equal to +C:/msys64/EYG2YDzDGm6yiwepEMSuExgRRMoTi8Di1UN3kixZw
~~~

MSYS2 porting doc [says](https://www.msys2.org/wiki/Porting/):

> Setting MSYS2_ARG_CONV_EXCL=* prevents any path transformation.

Would that work as expected?

**Comment by mback2k** [comment]
Yes, please give it a try for those tests.
