### ISSUE TITLE
without-gnutls broken?

### ISSUE THREAD

**Issue by nocturo** [curl/curl#809]
### I did this
On Ubuntu 12.04 I tried to get rid of gnutls support due to issues connecting to TLSv1_2 server and it seemed pretty obvious to run:
`./configure --prefix=$HOME --without-gnutls`
```bash
configure: Configured to build curl/libcurl:

  curl version:     7.48.0
  Host setup:       x86_64-pc-linux-gnu
  Install prefix:   /home/nick.zeljkovic
  Compiler:         gcc
  SSL support:      enabled (OpenSSL)
  SSH support:      no      (--with-libssh2)
  zlib support:     enabled
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  enabled
  resolver:         default (--enable-ares / --enable-threaded-resolver)
  IPv6 support:     enabled
  Unix sockets support: enabled
  IDN support:      enabled
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   /etc/ssl/certs/ca-certificates.crt
  ca cert path:     no
  ca fallback:      no
  LDAP support:     enabled (OpenLDAP)
  LDAPS support:    enabled
  RTSP support:     enabled
  RTMP support:     enabled (librtmp)
  metalink support: no      (--with-libmetalink)
  PSL support:      no      (libpsl not found)
  HTTP2 support:    disabled (--with-nghttp2)
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP LDAPS POP3 POP3S RTMP RTSP SMB SMBS SMTP SMTPS TELNET TFTP
```
### I expected the following
```bash
$ ldd ./lib/.libs/libcurl.so|grep gnutls
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007ffa2935e000)
```
not to be linked against it.
### curl/libcurl version
7.48.0

### operating system
Ubuntu 12.04

**Comment by bagder** [comment]
Unfortunately, I think this is an indirect dependency that gets sucked in. If you make clean and then rerun your make command like `make V=1`, you'll get the full link command at the end and in there you'll see the full list of libs that we use.

In my case when I build with OpenSSL and a bunch of 3rd party libs, it lists: "-lidn -lrtmp -lpsl -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lz -ldl -lpthread" ... and yet when I check what libs my curl build uses, it includes gnutls (I build with a static libcurl so I ldd my curl binary instead):

    $ ldd src/curl | grep gnutls
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f3b575f1000)

**Comment by bagder** [comment]
`ldd -v` is useful to see where it comes from. In my case it seems librtmp brings it.

**Comment by nocturo** [comment]
Thanks, it appears unfortunately so. On my system it pulled from librtmp and ldap so I had to:
`./configure --prefix=$HOME --without-gnutls --without-librtmp --disable-ldap`

in case it helps anyone else. Blame good ol' curl for nothing :(
