### ISSUE TITLE
Would curl like some free MFA tokens? Please tell us by 2021-12-20 and preferably sooner!

### ISSUE THREAD

**Issue by david-a-wheeler** [curl/curl#8093]
@bagder and all other curl developers:

Hello! I am David A. Wheeler and I work with the Developer Best Practices Working Group of the Linux Foundation's Open Source Security Foundation (OpenSSF) at <https://github.com/ossf/wg-best-practices-os-developers>

We'd like to give your project *free* multi-factor authentication (MFA) hardware tokens from Google and GitHub, for use by your maintainers. We'd especially like to give them to any of your maintainers who aren't already using any. This is part of the "The Great MFA Distribution Project". <https://github.com/ossf/great-mfa-project> for developers of open source software (OSS)/Free Software to improve confidence in authentication and integrity of code being delivered.

By **2021-12-20** and preferably much sooner, let us know how many you'd like. We can provide your project up to 3 Titan tokens from Google and up to 3 Yubikey tokens from GitHub.  If you could use more, please let us know that too. We know many projects could use more, and we may be able to provide more at some point. In your response, tell us an email address where we can *privately* send you the coupon codes and validation codes needed to get the tokens.

We would send you coupon codes and validation codes to the private email address. You would send then distribute those codes to the maintainers you choose. The recipients would use the coupon codes and validation codes to "buy" the tokens from the Google Store and/or GitHub Shop, who would ship the tokens directly to recipients.  These codes are use-once, so. make sure you can keep the codes private until they're used by the intended person.

**Important**: The Google coupon codes **must be used by 2021-12-31** on the Google Store or they expire.

To qualify, each token recipient must:

1. Be a maintainer or contributor to this critical open source software (OSS)
   project, or to another OSS project that this project depends on
   (the dependency may be indirect).
2. Try to use an MFA token once they receive the token.
   We'd like recipients to use MFA tokens from then on, but at least try.
3. Not reuse the token between different people (the token must not be shared).
4. Consider providing feedback to us (so we can try to fix problems).

We also need each project that receives coupon codes and/or validation codes
to tell us these numbers (preferably within 30 days of getting the codes):

1. How many tokens did you distribute from just Google? From just GitHub?
2. How many people received tokens from just Google? From just GitHub? From both?
3. How many people didn’t have hardware tokens they used for OSS who received tokens from just Google? From just GitHub? From both?

We ask for this information so we can tell others some simple measures of success. We don't need nor want the names of any individuals participating.

Please note that the tokens are shipped from the US, so while they can be shipped internationally, we can't ship somewhere if that is forbidden (sanctioned) under US law. So at this time we are unable to ship to individuals in China, Afghanistan, Russia, Ukraine, North Korea, Iran, Sudan, and Syria. Sorry about that. More information is here: <https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information>

For more information including how-tos and other setup information can be found at the "Great Multi-Factor Authentication (MFA) Distribution Project" site: <https://github.com/ossf/great-mfa-project>

**Comment by bagder** [comment]
I forwarded the call [to the curl-library mailing list](https://curl.se/mail/lib-2021-12/0004.html).

**Comment by david-a-wheeler** [comment]
Awesome! Thank you!

You're one of the very first projects we've contacted, so feedback on how we do this would be appreciated too. As noted in the message, we may be able to offer more, but we have to make sure we can give what we offer :-).

**Comment by bagder** [comment]
So far we've received a *yes-please* from four persons in [the curl maintainer team](https://github.com/orgs/curl/people)

**Comment by david-a-wheeler** [comment]
Awesome! How many Titans from Google,, how many Yubikeys from GitHub?

I expect some projects will say "no" & we can share more with you soon. We're being conservative. I don't want to promise anything we can't deliver.

**Comment by danielgustafsson** [comment]
I would prefer a Yubikey, thanks!

**Comment by bch** [comment]
On Mon, Dec 6, 2021 at 11:54 David A. Wheeler ***@***.***>
wrote:

> Awesome! How many Titans from Google,, how many Yubikeys from GitHub?
>

Prefer yubikey.


-bch


I expect some projects will say "no" & we can share more with you soon.

**Comment by xquery** [comment]
yubikey

**Comment by MarcelRaad** [comment]
I don't care which one. If everyone else wants to Yubikey, I'll happily take a Titan :-)

**Comment by david-a-wheeler** [comment]
Okay, I'll guess 3 Yubikey & 1 Titan. The Titan coupon codes expire at the end of December, so I gotta hurry. I'll send the codes to @bagder who can then distribute.

**Comment by david-a-wheeler** [comment]
Emails have been sent to @bagder for further redistribution. Let me ( @david-a-wheeler ) know if you have any problems (you *shoudn't* but of course bad things can happen). Enjoy!!!

And once again, thanks for curl!! I use it all the time.

**Comment by bagder** [comment]
Thanks!

**Comment by xquery** [comment]
@david-a-wheeler received yubikey, engaged ... thx!

**Comment by MarcelRaad** [comment]
My new Google Titan works great too. Thank you very much @david-a-wheeler & project team!

**Comment by david-a-wheeler** [comment]
Excellent! I'm so glad!!

Again, my thanks to all the curl developers for your great work!
