### ISSUE TITLE
Fix bug in example /docs/examples/smtp-mime.c

### ISSUE THREAD

**Issue by nnosov** [curl/curl#8095]
### I did this
I tried /docs/examples/smtp-mime.c to send Email with alternative "text/html" and plain text body together as alternative to client using libCURL

After compile example (with my credentials) I always got from Google SMTP server an error:
"252 2.1.5 Send some mail, I'll try my best a28sm1064377ljm.65 - gsmtp"

To fix that in example, enough to add *curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);*
before issuing *curl_easy_perform(curl);*
since authors forgot to add MIME part to the handle before execution of request.

I think this fix will help other users of libCURL to avoid this problem in future.
Thanks!

### I expected the following
Successful send of SMTP message in example when I provided right credentials and other stuff.

### curl/libcurl version
curl 7.68.0

[curl -V output]
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system
Linux cola-nettop 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nnosov** [comment]
Sorry, I mix up smtp-mime.c & smtp-mail.c examples. It's about smtp-mime.c

**Comment by bagder** [comment]
> To fix that in example, enough to add _curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);_
> before issuing _curl_easy_perform(curl);_

Isn't this done already?

https://github.com/curl/curl/blob/a40160aee83acae504fd4b30e39c28ff8dbab24c/docs/examples/smtp-mime.c#L134

**Comment by nnosov** [comment]
Seems that I used outdated version. Sorry
