### ISSUE TITLE
TCP connection reuse issue with curl 7.48.0

### ISSUE THREAD

**Issue by Simon45** [curl/curl#810]
### I did this
........
.........
	curl_global_init(CURL_GLOBAL_ALL);
	g_curl = curl_easy_init(); 
	curl_easy_setopt(g_curl, CURLOPT_URL, "http://10.11.1.4:9200/cn_es_rt_w_prod_risk_ex/cn_es_rt_w_prod_risk_ex");
	curl_easy_setopt(g_curl, CURLOPT_VERBOSE, 0L);
	curl_easy_setopt(g_curl, CURLOPT_NOPROGRESS, 1L);
	curl_easy_setopt(g_curl, CURLOPT_WRITEFUNCTION, noop_cb);
	
	curl_version_info_data	*curl_ver_info = curl_version_info( CURLVERSION_NOW );	
	printf ("curl version: %s\n", curl_ver_info->version);

As shown below, call to  easy_perform happens in an conditional infinite loop. Curl handle is reused. 
while (!exit_flag)
{
............
................
............

curl_easy_setopt(g_curl, CURLOPT_POSTFIELDS,bfr_ptr); /// bfr_ptr is updated via records coming out of a FIFO..
res = curl_easy_perform(g_curl);  
}

### I expected the following
That the single instance of curl_easy would reuse the connection. Attached PCAP file capture output below.  

### curl/libcurl version
curl 7.48.0 (x86_64-pc-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.1e zlib/1.2.3 libidn/1.18
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

### OS version
centos-release-6-5.el6.centos.11.2.x86_64
Linux 36-JBOD 2.6.32-431.3.1.el6.x86_64 #1 

### PCAP shows new connection for each easy_perform

PCAP: Each easy_perform results in a NEW TCP connection

![image](https://cloud.githubusercontent.com/assets/6722046/15316121/54f98fe4-1bd0-11e6-9651-b0a9669079a5.png)

**Comment by bagder** [comment]
The recipe is incomplete. Can you provide a full example that repeats the problem so that we can try it out in our ends or better figure out what exactly libcurl is or isn't doing?

Often you get a hint by enabling VERBOSE and see what the debug logging says.

**Comment by grosch** [comment]
Here's the output when I try to make two connections:

    *   Trying 17.143.164.136...
    * Connected to api.push.apple.com (17.143.164.136) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /usr/local/etc/openssl/cert.pem
      CApath: none
    * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
    * ALPN, server accepted to use h2
    * Server certificate:
    *  subject: CN=api.push.apple.com; OU=management:idms.group.533599; O=Apple Inc.; ST=California; C=US
    *  start date: Aug 28 19:03:46 2015 GMT
    *  expire date: Sep 26 19:03:46 2017 GMT
    *  subjectAltName: host "api.push.apple.com" matched cert's "api.push.apple.com"
    *  issuer: CN=Apple IST CA 2 - G1; OU=Certification Authority; O=Apple Inc.; C=US
    *  SSL certificate verify ok.
    * Using HTTP2, server supports multi-use
    * Connection state changed (HTTP/2 confirmed)
    * TCP_NODELAY set
    * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
    * Using Stream ID: 1 (easy handle 0x7f9a13800000)
    > POST /3/device/my_device_token_was_here_but_now_removed HTTP/1.1
    Host: api.push.apple.com
    Accept: */*
    apns-topic: deleted_topic_was_here
    Content-Length: 42
    Content-Type: application/x-www-form-urlencoded

    * Connection state changed (MAX_CONCURRENT_STREAMS updated)!
    * We are completely uploaded and fine
    < HTTP/2.0 200
    < apns-id:0A08A038-2C35-E1A6-E68A-3D3AA4C0D49E
    <
    * Connection #0 to host api.push.apple.com left intact
    * Found bundle for host api.push.apple.com: 0x7f9a12670800 [can multiplex]
    * Hostname api.push.apple.com was found in DNS cache
    *   Trying 17.143.164.136...
    * Connected to api.push.apple.com (17.143.164.136) port 443 (#1)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /usr/local/etc/openssl/cert.pem
      CApath: none
    * SSL re-using session ID
    * Unknown SSL protocol error in connection to api.push.apple.com:443
    * Closing connection 1


This was the code that I used to make the connections. I used the same device token for both just to test whether I'd get the push twice, as expected.  One came through, the second one got the error you can see above.



    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ["apns-topic: $apns_topic"]);
    curl_setopt($ch, CURLOPT_SSLCERT, $pem_file);
    curl_setopt($ch, CURLOPT_VERBOSE , true);

    // -----

    $sample_alert = '{"aps":{"alert":"hi 1","sound":"default"}}';
    $url = "https://api.push.apple.com/3/device/$device_token";
    curl_setopt($ch, CURLOPT_POSTFIELDS, $sample_alert);
    curl_setopt($ch, CURLOPT_URL, "{$url}");
    $response = curl_exec($ch);
    $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    // -----

    $sample_alert = '{"aps":{"alert":"hi 2","sound":"default"}}';
    $url = "https://api.push.apple.com/3/device/$device_token";
    curl_setopt($ch, CURLOPT_POSTFIELDS, $sample_alert);
    curl_setopt($ch, CURLOPT_URL, "{$url}");
    $response = curl_exec($ch);
    $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

**Comment by grosch** [comment]
Please note I just upgraded to 7.49.0 and this now works without issue.  Good job!  👍

**Comment by bagder** [comment]
Lovely, thanks for reporting back. Closing this as it seems to work now.
