### ISSUE TITLE
curl hangs after returning from the CURLOPT_XFERINFOFUNCTION callback

### ISSUE THREAD

**Issue by bnousilal** [curl/curl#8108]
Hi All, 
Facing an issue with the curl sftp transfer,  to check the upload/download I have registered a callback "CURLOPT_XFERINFOFUNCTION".  when the progress is stalled for 1 minute returning the non zero from the callback. after returning non zero (abort) from the callback curl hangs.

Client ID 338435 upload stalled. Aborting...

libcurl version 7.65.3

This issue happening in the multi client handle environment.
in the callback function of the CURLOPT_XFERINFOFUNCTION returning non zero, do I need to set any flag?

this issue can be reproduced easily by blocking the sftp port using iptable rule after the connection is established and first chunk bytes are transferred. 

logs
Dec  7 11:12:04 localhost  Upload of /opt/pw/crashes/nousilal.gz is 28% complete
Dec  7 11:12:10 localhost  Upload of /opt/pw/crashes/nousilal.gz is 28% complete
Client ID 338435 upload stalled. Aborting...

**Comment by bnousilal** [comment]
Client ID 338435 upload stalled. Aborting...

**Comment by bagder** [comment]
> libcurl version 7.65.3

That's a fairly old release. Can you try with a modern version and see that the problem actually still remains?

**Comment by bnousilal** [comment]
Thank you so much for the response.
is there any dependency issue with the modern version for CentOS 7?

**Comment by bagder** [comment]
Using current libcurl and libssh2 1.10.0 I  cannot reproduce. I tried both upload and download, based on the example below.

~~~c
#include <stdio.h>
#include <curl/curl.h>

#define STOP_AFTER_THIS_MANY_BYTES 6000

static int xferinfo(void *p, curl_off_t dltotal, curl_off_t dlnow,
                    curl_off_t ultotal, curl_off_t ulnow)
{
  if(ulnow > STOP_AFTER_THIS_MANY_BYTES)
    return 1;
  return 0;
}

int main(int argc, char **argv)
{
  CURL *curl;
  CURLcode res = CURLE_OK;
  FILE *readfile;

  if(argc < 3)
    return 2;

  readfile = fopen(argv[2], "r");
  if(!readfile)
    return 3;

  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_URL, argv[1]);
    curl_easy_setopt(curl, CURLOPT_XFERINFOFUNCTION, xferinfo);
    curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 0L);
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
    curl_easy_setopt(curl, CURLOPT_READDATA, readfile);
    res = curl_easy_perform(curl);

    if(res != CURLE_OK)
      fprintf(stderr, "%s\n", curl_easy_strerror(res));

    /* always cleanup */
    curl_easy_cleanup(curl);
  }
  fclose(readfile);

  return (int)res;
}

**Comment by bnousilal** [comment]
Hi Badger,

thanks lot.
yes, not reproducible with the current version of the curl and libssh2 1.10.
