### ISSUE TITLE
Crash in multi_done; seemingly a race condition

### ISSUE THREAD

**Issue by rcombs** [curl/curl#8111]
### I did this

I'm using libcurl with the `CURLSH` feature, and some of my users are encountering seemingly-random segfaults.

Looking at their stack traces, it appears that they're happening here: https://github.com/curl/curl/blob/4d97fe547322c4ad0868e2282476b1a7d2027f86/lib/multi.c#L689

Specifically in the read from `conn->connection_id`; `conn` is of course not null here.

This appears to be a potential race condition: if I understand the code correctly, the crashing thread's call to `Curl_conncache_return_conn` didn't free `conn`, but this code runs unlocked, so another thread may have called `Curl_conncache_return_conn` at nearly the same time. If I'm correct, this could also result in `Curl_conncache_return_conn` itself crashing when it sets `conn->lastused` (since `conn` may have just been freed at that point as well).

### I expected the following

(No crashes)

### curl/libcurl version

7.73.0-315ee3f (I know this is somewhat outdated, but it doesn't appear that anything in the relevant code has changed).

### operating system

Seeing this on a variety of Linux versions, primarily on x86_64; also at least one instance on macOS.

**Comment by bagder** [comment]
> I'm using libcurl with the CURLSH feature,

Please tell us what you are sharing in that share object. It makes a world of difference.

**Comment by rcombs** [comment]
I'm using these:
```
SHSETOPT(CURLSHOPT_SHARE, CURL_LOCK_DATA_DNS)
SHSETOPT(CURLSHOPT_SHARE, CURL_LOCK_DATA_SSL_SESSION)
SHSETOPT(CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT)
```

(And I have appropriate lock/unlock callbacks configured)

**Comment by bagder** [comment]
Allow me then to highlight a section in the CURLOPT_SHARE.3 man page about **CURL_LOCK_DATA_CONNECT**:

> Note that due to a known bug, it is not safe to share connections this way between multiple concurrent threads.

I believe you see exactly that problem. Mentioned here: https://curl.se/docs/knownbugs.html#A_shared_connection_cache_is_not

**Comment by bagder** [comment]
Are you sharing the connection cache in the share object between multiple threads?

**Comment by rcombs** [comment]
Yes, this appears to be the issue you referenced. I'm going to work around this by moving all my curl I/O to a single thread using the multi interface, but IMO if this isn't likely to be fixed soon, the docs for `CURLSHOPT_LOCKFUNC` should make it clearer that it doesn't actually provide thread-safety for connection caches; same with the [share interface overview](https://curl.se/libcurl/c/libcurl-share.html). I'll close this out as a dupe of #4915, I suppose.
