### ISSUE TITLE
CURLMOPT_SOCKETFUNCTION returning error puts transfer in limbo

### ISSUE THREAD

**Issue by bagder** [curl/curl#8114]
Since #8089 (2b3dd01b779) landed, libcurl now acts on errors returned from the `CURLMOPT_SOCKETFUNCTION` callback.

When the socket callback has returned error `curl_multi_socket_action` subsequently returns an error back, and the application then **doesn't know what socket actions to wait for**. That leaves the application with only a timeout - at best. An application event-loop might then get stuck with nothing to wait for and no timeout. If `curl_multi_info_read()` is called then, it just returns NULL since the transfer is still considered "alive".

This problem can be reproduced and detected by torture testing 530 with the following patch applied.

~~~diff
diff --git a/tests/libtest/lib530.c b/tests/libtest/lib530.c
index 517f890c8..243661e09 100644
--- a/tests/libtest/lib530.c
+++ b/tests/libtest/lib530.c
@@ -305,10 +305,11 @@ static int testone(char *URL, int timercb, int socketcb)
     else if(maxFd <= 0) {
       tv.tv_sec = 0;
       tv.tv_usec = 100000;
     }
 
+    assert(maxFd);
     select_test((int)maxFd, &readSet, &writeSet, NULL, &tv);
 
     /* Check the sockets for reading / writing */
     checkFdSet(m, &sockets.read, &readSet, CURL_CSELECT_IN, "read");
     checkFdSet(m, &sockets.write, &writeSet, CURL_CSELECT_OUT, "write");
~~~

## Fix?

We need to make sure all the existing transfers are completed when the multi handle fails like this, so that `curl_multi_info_read()` will properly say so.

I don't think we can tell make applications to call `curl_multi_socket_action()` again just because it returned error. That's counter-intuitive and no anything we've stated before.

**Comment by bagder** [comment]
This state can also be reached when other errors happen for the multi stack, for example resource allocation failures. It goes beyond "just" those two callbacks.

**Comment by bagder** [comment]
New thought: when `curl_multi_perform()` or `curl_multi_socket_action()` return error, **that means** all transfers have failed and calling one of them again without first removing all the handles and added a new one should just return an error again...

**Comment by jay** [comment]
That sounds reasonable to me for curl_multi_perform since the individual transfer results are not going to affect its return code. I am interested in what @juchem and other users of the event interface think. I do notice the doc for timer and socket functions already says "If this callback returns error, all transfers currently in progress in this multi handle will be aborted and fail."

**Comment by bagder** [comment]
> If this callback returns error, all transfers currently in progress in this multi handle will be aborted and fail.

Yes, I believe that is true for those particular errors (and test 530 verifies that). But as I've been struggling with a torture failure in test 530 I've realized that there are more potential errors that can be returned (like out of memory) that will not necessarily abort all transfers before an error is returned.

**Comment by juchem** [comment]
> When the socket callback has returned error `curl_multi_socket_action` subsequently returns an error back

I'm curious about whether `curl_multi_socket_action` follows up a `CURLMOPT_SOCKETFUNCTION` callback error with a `CURL_POLL_REMOVE` for the appropriate file descriptor, before returning an error.

**Comment by juchem** [comment]
I'm also not sure of what's being proposed. Would the semantics of `curl_multi_socket_action` change when an error is returned?

The biggest concern I would have in that case is backwards compatibility. Would all applications written using the async API just work or do they have to adapt? The collective cost of a change in semantics could be devastating.

**Comment by bagder** [comment]
> I'm also not sure of what's being proposed.

I*m not proposing anything really. I'm clarifying what errors returned from these functions actually mean, as the docs is not very elaborate on that. I'll bring a separate PR with a docs update.

**Comment by bagder** [comment]
When I fixed my tests to actually abort properly on curl_multi errors (#8121) I can't reproduce any problems anymore. Closing this issue.
