### ISSUE TITLE
TLS fingerprinting

### ISSUE THREAD

**Issue by 89z** [curl/curl#8119]
Using request like this:

~~~
curl -v --http1.1 \
-d sdk_version=20 \
-d Email=srpen6%40gmail.com \
-d EncryptedPasswd=AFcb4KSjxg1UFj4IwEe6vESCI6xrqCUpTX0_MfQD5gg4dmL5RUt6brYU... \
https://android.clients.google.com/auth 
~~~

I get this result:

~~~
HTTP/1.1 403 Forbidden

Error=BadAuthentication
~~~

whereas with another client and the same request, I get this result:

~~~
HTTP/1.1 200 OK

Token=aas_et/AKppINZkQ5A5-wnTTfIWjzVYaHkW2Fy26vzAzv07QWfgVTcaq-f97kd0cex_IMze...
~~~

After some testing, it seems the issue is that the server is using TLS fingerprinting, and reject requests that dont match the expected fingerprint. I see that cURL has some options to deal with this [1][2], but I dont see any option to control the TLS extensions, which would be needed to make a successful request here.

1. https://curl.se/docs/manpage.html#--ciphers
2. https://curl.se/docs/manpage.html#--curves

**Comment by jay** [comment]
Custom handshakes are outside the scope of curl. You can use libcurl and CURLOPT_SSL_CTX_FUNCTION to set options for some SSL libraries but you would likely have to modify the SSL library to get it to send a handshake the exact way you want.

**Comment by 89z** [comment]
Thanks for the response. I think this is an important issue, as nothing is stopping any company from adding this to their server. For example, in addition to the Google example above, I have also see examples of Amazon doing this, as well as CloudFlare. So its possible the issue is only going to get worse.

I would recommend that cURL support a TLS library that can control these options, otherwise cURL is going to be reduced in effectiveness. If someone cannot use cURL to communicate with a server, then they will just find some tool that can. Granted this is a new problem, so that could be some time yet.

**Comment by bagder** [comment]
It's not a new thing. Sites and services have been trying to detect bots and automated clients for a long time, and using details from the TLS handshake is one step along that way. Others include exact HTTP header order and contents as well as details in the HTTP/2 framing layer - and more.

I'm not sure exactly what you mean with "controlling TLS extensions" but if someone wants to work on that, I'm willing to discuss.

**Comment by 89z** [comment]
Included in the TLS Client Hello, is a list of TLS extensions. I have found that server can check for the presence of an extension, and even the order. Here is an example list:

~~~
&tls.RenegotiationInfoExtension{Renegotiation:0}
&tls.SNIExtension{ServerName:""}
&tls.UtlsExtendedMasterSecretExtension{}
&tls.SessionTicketExtension{Session:(*tls.ClientSessionState)(nil)}
&tls.SignatureAlgorithmsExtension{SupportedSignatureAlgorithms:[]tls.SignatureScheme{0x804, 0x403, 0x807, 0x805, 0x806, 0x401, 0x501, 0x601, 0x503, 0x603, 0x201, 0x203}}
&tls.ALPNExtension{AlpnProtocols:[]string{"http/1.1"}}
&tls.SupportedPointsExtension{SupportedPoints:[]uint8{0x0}}
&tls.SupportedCurvesExtension{Curves:[]tls.CurveID{0x17}}
~~~

**Comment by bagder** [comment]
You want to be able to change the order the TLS extensions are reported? I doubt any TLS library curl uses actually has built-in functionality for that, but I'm not an expert on this.

**Comment by 89z** [comment]
Personally I don't want to have to do any of this, but its necessary in the current landscape regarding some servers. As shown in the example in the original post, this is a real problem, not a theoretical one. Different companies are already utilizing this technology to prevent certain clients from connecting to their servers.

**Comment by bagder** [comment]
I'm trying to understand exactly what you want to do with the extensions.

Have you managed to "fool" these servers by changing the order of the extensions and that is why you suggest we should offer that functionality? There are many more details in the TLS stack that can be fingerprinted than the extension order.

**Comment by 89z** [comment]
> Have you managed to "fool" these servers by changing the order of the extensions and that is why you suggest we should offer that functionality?

Yes. I captured PCAP from a client I knew to be working, then I used the Client Hello from that handshake in a new request on a different client. I utilized an existing package, that allows you to contruct TLS client hello, and even offers some common ones for easy use (Chrome, Firefox, Safari):

https://github.com/refraction-networking/utls

Ideally the cURL tool would be able to handle this use case as well, or if not the tool then LibCurl.

**Comment by bagder** [comment]
You are asking for a new feature/change. We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker.

If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by momala454** [comment]
I think that changing the order of extensions is not enough, because curl doesn't have the same extensions as chrome by example.
Even compiled using boringssl (the same tls lib as chrome), the following tls extensions are missing :
35 session_ticket (renamed from "SessionTicket TLS") 	
5 status_request
18 signed_certificate_timestamp
27 compress_certificate
21 padding

and grease cypher is also missing

**Comment by jay** [comment]
I don't think this should be in the TODO. I see very little upside and a lot of downside.

**Comment by momala454** [comment]
"very little upside". At some point a lot of websites will block requests matching curl tls fingerprint, so curl will be useless

**Comment by jay** [comment]
There is no single curl fingerprint or handshake. Depending on how you built curl, what SSL backend is used and what options are set will contribute to a fingerprint. There are many, many combinations. Just because whatever combination you are using is blocked does not make curl useless for everyone. The downside is that if we implement techniques specifically to randomize the handshake then these CDNs will need another way to detect rogue clients and more curl users may be affected. IMO this does not make things better.

**Comment by 89z** [comment]
> There is no single curl fingerprint or handshake. Depending on how you built curl, what SSL backend is used and what options are set will contribute to a fingerprint. There are many, many combinations.

I know all that. I wrote my own [TLS fingerprinter][1], so I understand whats involved here. The most likely scenario that will play out, is that a website will choose the most common cURL fingerprint, or maybe the top few. Its very easy for them to determine this, they can just look at their logs, and create a histogram of fingerprints.

So then, the cURL users in question would either just stop using cURL, since they dont know or understand what the problem is, or if the do understand the problem, then maybe they will come across this thread, where the maintainers are saying that not only will this not be fixed, but its not even worth putting on a todo list. This problem is not going away. cURL doesnt need to necessarily randomize the handshakes, in fact, the default can be for cURL to just do nothing, or send whatever handshake its sending now. But, just as cURL has options for cipher suite, it could also have option for TLS extensions, so that if people are hit by this, then they at least have some option to fix it, other than "just use another client".


[1]:https://github.com/89z/parse/tree/master/crypto

**Comment by momala454** [comment]
CURLOPT_SSL_CTX_FUNCTION is not available everywhere, like in CLI or in PHP curl

**Comment by divinity76** [comment]
> CURLOPT_SSL_CTX_FUNCTION is not available everywhere, like in CLI or in PHP curl

som1 should complain on php bugtracker

**Comment by 89z** [comment]
Adding JA3 for people searching for that. Also linking to new article, since it seems people are finally taking this seriously:

https://daniel.haxx.se/blog/2022/09/02/curls-tls-fingerprint
