### ISSUE TITLE
__mips__ is defined for both 32 and 64bit mips on Android

### ISSUE THREAD

**Issue by tomaz82** [curl/curl#813]
#**I did this**

Custom compile script for Android, compiling for mips64 fails due to CURL_SIZEOF_LONG not matching sizeof(long)

**I expected the following**

curlbuild.h line 532 `defined(__mips__)` is true for both 32 and 64 bit mips when compiling for Android, changing it to `(defined(__mips__) && !defined(__LP64__))` fixes it.

**curl/libcurl version**

version 7.48

**OS version**

Compiling for Android in Windows 7

**Comment by bagder** [comment]
This has been mentioned before ([here](https://curl.haxx.se/mail/archive-2015-12/0005.html) for example). That file (curlbuild.h as it appears in the distribution tarball) is really not intended to be used on systems that can run configure and generate its proper header, which should include most systems that can run on MIPS. When configure runs, it outputs a generated version for that particular system.

I could still see a value in fixing this so that maybe we can work on, long-term, move (back) toward not generating a system specific curlbuild.h at build time.

Can you suggest a full patch that you deem proper for this to build fine for you?

**Comment by tomaz82** [comment]
In understand that it's a generic header not meant to be used, but when building for Android from Windows using jni, there are no easy way to run configure

The fix I suggested that checks if __mips__ is defined AND that __LP64__ isn't defined is sufficient. I have that in my local version and can build libcurl for Android just fine on all 7 major architectures ( armeabi, armeabi-v7a, mips, x86, arm64-v8a, mips64 and x64 ).

**Comment by bagder** [comment]
And you really need `LP64` checked there and not `__LP64__` ? We check the latter symbol for the 64 bit case so I figure it would make it more consistent if we would check the same!

**Comment by tomaz82** [comment]
Yeah I meant the `__LP64__`, the formatting in this issue tracker turned it into bold text.

**Comment by bagder** [comment]
Something like this?

~~~diff
diff --git a/include/curl/curlbuild.h.dist b/include/curl/curlbuild.h.dist
index 58323d0..ae95095 100644
--- a/include/curl/curlbuild.h.dist
+++ b/include/curl/curlbuild.h.dist
@@ -525,13 +525,13 @@
 /* ===================================== */
 /*    KEEP GENERIC GCC THE LAST ENTRY    */
 /* ===================================== */
 
 #elif defined(__GNUC__)
-#  if defined(__ILP32__) || \
+#  if !defined(__LP64__) && (defined(__ILP32__) || \
       defined(__i386__) || defined(__ppc__) || defined(__arm__) || \
-      defined(__sparc__) || defined(__mips__) || defined(__sh__)
+      defined(__sparc__) || defined(__mips__) || defined(__sh__))
 #    define CURL_SIZEOF_LONG           4
 #    define CURL_TYPEOF_CURL_OFF_T     long long
 #    define CURL_FORMAT_CURL_OFF_T     "lld"
 #    define CURL_FORMAT_CURL_OFF_TU    "llu"
 #    define CURL_FORMAT_OFF_T          "%lld"

**Comment by tomaz82** [comment]
That might work I guess, I did it different, as mentioned in my initial bug report, trying to add a patch here but the formatting keeps messing it up.

**Comment by tomaz82** [comment]
```
diff -r 342d4b87724b thirdparty/curl-7.48.0/include/curl/curlbuild.h
--- a/thirdparty/curl-7.48.0/include/curl/curlbuild.h	Wed May 18 14:12:01 2016 +0200
+++ b/thirdparty/curl-7.48.0/include/curl/curlbuild.h	Wed May 18 14:12:29 2016 +0200
@@ -529,7 +529,7 @@
 #elif defined(__GNUC__)
 #  if defined(__ILP32__) || \
       defined(__i386__) || defined(__ppc__) || defined(__arm__) || \
-      defined(__sparc__) || defined(__mips__) || defined(__sh__)
+      defined(__sparc__) || (defined(__mips__) && !defined(__LP64__)) || defined(__sh__)
 #    define CURL_SIZEOF_LONG           4
 #    define CURL_TYPEOF_CURL_OFF_T     long long
 #    define CURL_FORMAT_CURL_OFF_T     "lld"
```

**Comment by bagder** [comment]
Right, I prepended that 64bit check because I figured it is such an important define that it set on any platform it implies 64bit.

**Comment by tomaz82** [comment]
That will work

**Comment by bagder** [comment]
Thanks!
