### ISSUE TITLE
Wrong OpenSSL version information

### ISSUE THREAD

**Issue by lllaffer** [curl/curl#8154]
Setting, OpenSSL 3.0.1:

    Acc. Dependency Walker:                                                                                 Version
	c:\program files\+++\CURL.EXE			10.11.2021 17:03    10.11.2021 17:03       781.824	7.80.0.0
	c:\program files\+++\LIBCRYPTO-3.DLL	        15.12.2021 02:10    15.12.2021 02:09     3.665.408	3.0.1.0    <<<  
	c:\program files\+++\LIBSSH2.DLL    		24.07.2021 18:35    24.07.2021 18:35       184.320	1.9.0.0  
	c:\program files\+++\LIBSSL-3.DLL   		15.12.2021 03:16    15.12.2021 03:16       615.936	3.0.1.0    <<<
	c:\program files\+++\ZLIB1.DLL      		30.06.2018 07:36    30.06.2018 07:36        74.240	1.2.11.0 

cURL states:
```
curl 7.80.0 (i386-pc-win32) libcurl/7.80.0 OpenSSL/3.0.0a zlib/1.2.11 WinIDN libssh2/1.9.0
_____________________________________________________^^^^
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets alt-svc libz
```

!?

btw
Setting, OpenSSL 3.0.0:

    Acc. Dependency Walker:                                                                                 Version
	c:\program files\+++\CURL.EXE			10.11.2021 17:03    10.11.2021 17:03       781.824	7.80.0.0
	c:\program files\+++\LIBCRYPTO-3.DLL		 09.09.2021 08:21   09.09.2021 08:21      3.655.168	3.0.0.0    <<<v
	c:\program files\+++\LIBSSH2.DLL    		 24.07.2021 18:35   24.07.2021 18:35        184.320	1.9.0.0
	c:\program files\+++\LIBSSL-3.DLL   		 09.09.2021 09:42   09.09.2021 09:42        615.424	3.0.0.0    <<<
	c:\program files\+++\ZLIB1.DLL      		 30.06.2018 07:36   30.06.2018 07:36         74.240	1.2.11.0

curl 7.80.0 (i386-pc-win32) libcurl/7.80.0 OpenSSL/3.0.0 zlib/1.2.11 WinIDN libssh2/1.9.0
_____________________________________________________^^^^
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets alt-svc libz

!!

**Comment by rsbeckerca** [comment]
OpenSSL has changed its version numbering. The initial 3.0.x release was designated 3.0.0. The release issued yesterday is designated 3.0.1 not 3.0.0a as with the 1.1.1x series.

**Comment by jay** [comment]
https://github.com/curl/curl/blob/9e560d11aad028de74addc0d1edfefa5667884f4/lib/vtls/openssl.c#L4380-L4384

[OpenSSL_version](https://www.openssl.org/docs/man3.0/man3/OpenSSL_version.html) doc says this:

> OPENSSL_VERSION_STR is a convenience macro to get the short version identifier string, "MAJOR.MINOR.PATCH".

So either OpenSSL_version is returning that value or OpenSSL_version wasn't detected at compile time, which it should have been, so instead libcurl uses the #else block. How did you build curl?

**Comment by lllaffer** [comment]
cURL was built on/with Win732 / VS 2019 BuildTools

**Comment by vszakats** [comment]
I can confirm the same phenomenon with the official curl-for-win builds.

**Comment by jay** [comment]
Ok I see it, pr coming up...

**Comment by vszakats** [comment]
New curl-for-win build is out that fixes the issue: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/41906972/artifacts (soon also on: https://curl.se/windows/)

**Comment by jay** [comment]
Thanks
