### ISSUE TITLE
bearssl resource leak

### ISSUE THREAD

**Issue by ryancaicse** [curl/curl#8172]
`fclose(fp)` should be put before Line 128 to prevent resource leaks

https://github.com/curl/curl/blob/60738f398cdd66312bce6ce92a87f19e71feacf4/lib/vtls/bearssl.c#L122-L128

**Comment by bagder** [comment]
Seems accurate, even if also a bit hard to reach! :grinning:

**Comment by ryancaicse** [comment]
Oh, I am sorry to report a false bug

**Comment by bagder** [comment]
No worries, more eyes on the code is good and not having a bug there is good! :raised_hands:
