### ISSUE TITLE
multi-single.c example

### ISSUE THREAD

**Issue by danger89** [curl/curl#8200]
Hi,

I was questioning if this ifdefs regarding sleep portability is still required, at the top of the multi-single example: https://github.com/curl/curl/blob/master/docs/examples/multi-single.c#L37 ?

I think this should be part of the curl library itself, if it isn't already 😄 .

```c 
#ifdef _WIN32
#define WAITMS(x) Sleep(x)
#else
/* Portable sleep for platforms other than Windows. */
#define WAITMS(x)                               \ 
  struct timeval wait = { 0, (x) * 1000 };      \ 
  (void)select(0, NULL, NULL, NULL, &wait)
#endif
```

Regards,
Melroy van den Berg

**Comment by jay** [comment]
> I think this should be part of the curl library itself, if it isn't already

You mean add a curl_sleep()? I don't see much use of it.

**Comment by bagder** [comment]
`WAITMS()` is not even *used* in the example code ... :smile:  I'll remove it.

**Comment by danger89** [comment]
Thank you Daniel. This is what I was thinking as well.

**Comment by danger89** [comment]
I think this multi_poll code has a sleep. To avoid busy waiting.
