### ISSUE TITLE
curl_multi_init - return NULL

### ISSUE THREAD

**Issue by Optimus1111** [curl/curl#8211]
This simple code causes an error:

This simple code causes an error on Windows 10 VS2019:

```
#define CURL_STATICLIB   

#include <iostream>
#include <curl.h> 
//----------------------------Windows DDL:------------------------
#pragma comment(lib, "Normaliz.lib")
#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Wldap32.lib")
#pragma comment(lib, "Crypt32.lib")
#pragma comment(lib, "advapi32.lib")
//---------------------------------------------------------------------

int main()
{

    int curl_global_init_status = curl_global_init(CURL_GLOBAL_ALL);
    std::cout << "curl_global_init_status:" << curl_global_init_status << std::endl;  //always OK (0)


    CURLM* CURLM_ = curl_multi_init();
    std::cout << "CURLM_:" << CURLM_ << std::endl;    //Return NULL!!!randomly every other time or every 3 -5 times


    curl_multi_cleanup(CURLM_);
    curl_global_cleanup();
}
```

curl_multi_init returns a non-zero value, zero in another code run, then zero again, then zero again, then not zero again, then zero again, and so on...

**Comment by bagder** [comment]
I propose you single-step into libcurl with a debugger and figure out why this happens to you. It is not common and I've never seen it happen.

**Comment by jay** [comment]
multi init can fail due to lack of memory or resources (OS handles). Also, it calls curl_easy_init to make an internal curl handle for the multi. Do you see similar behavior if you call curl_easy_init instead?

**Comment by bagder** [comment]
There's not a lot more we can do. It will return NULL when there's a problem detected. That is working as intended.
