### ISSUE TITLE
Dead link in opencollective sponsor 6

### ISSUE THREAD

**Issue by stamp-cmd** [curl/curl#8222]
# This is documentation link error.

<https://opencollective.com/curl/sponsor/6/website> link to <https://www.uffizzi.cloud>
 that send invalid responses.
[linkcheck.yml](https://github.com/curl/curl/blob/master/.github/workflows/linkcheck.yml) check that link is dead link.
the web that is open now is <https://uffizzi.cloud> (redirect to <https://uffizzi.com>)
![image](https://user-images.githubusercontent.com/76716475/148000885-75b75ab2-8e3d-4430-bf5f-8863ead216d3.png)

**Comment by stamp-cmd** [comment]
## Also other screenshot
![image](https://user-images.githubusercontent.com/76716475/148001939-454b2a72-b13e-43c5-963d-f6b0a03be009.png)

**Comment by bagder** [comment]
Right, but that's a problem "upstream" that I don't think we can fix very well on our side. Removing the link from the readme for this seems a little drastic.

**Comment by stamp-cmd** [comment]
### Change to <https://uffizzi.cloud/?utm_source=opencollective&utm_medium=github&utm_campaign=curl> for temporary doesn't solve opencollective problem, but there's no dead link after for now

**Comment by bagder** [comment]
We don't link any sponsor directly from the README to avoid having to constantly update it as they come and go.

**Comment by stamp-cmd** [comment]
so, there're no fixes (for now) and close this issue now?

**Comment by bagder** [comment]
I think so. Hopefully that broken link is not going to be there forever.
