### ISSUE TITLE
"make distclean" loops to infinity, on MacOS Monterey

### ISSUE THREAD

**Issue by forrie** [curl/curl#8225]
### I did this

make distclean

loops to infinity, with 100's of lines like this:

[ ... ]
rm -f vquic/.deps/libcurl_la-quiche.Plo # am--include-marker
rm -f vquic/.deps/libcurl_la-vquic.Plo # am--include-marker
rm -f vquic/.deps/libcurlu_la-ngtcp2.Plo # am--include-marker
rm -f vquic/.deps/libcurlu_la-quiche.Plo # am--include-marker
rm -f vquic/.deps/libcurlu_la-vquic.Plo # am--include-marker
rm -f vssh/.deps/libcurl_la-libssh.Plo # am--include-marker
rm -f vssh/.deps/libcurl_la-libssh2.Plo # am--include-marker
rm -f vssh/.deps/libcurl_la-wolfssh.Plo # am--include-marker
rm -f vssh/.deps/libcurlu_la-libssh.Plo # am--include-marker
rm -f vssh/.deps/libcurlu_la-libssh2.Plo # am--include-marker
rm -f vssh/.deps/libcurlu_la-wolfssh.Plo # am--include-marker
rm -f vtls/.deps/libcurl_la-bearssl.Plo # am--include-marker
rm -f vtls/.deps/libcurl_la-gskit.Plo # am--include-marker
rm -f vtls/.deps/libcurl_la-gtls.Plo # am--include-marker
rm -f vtls/.deps/libcurl_la-keylog.Plo # am--include-marker
rm -f vtls/.deps/libcurl_la-mbedtls.Plo # am--include-marker
[ ... ]

### I expected the following

A completed distribution clean, and final exit

### curl/libcurl version

Source distribution, github, up to date

### operating system

Darwin MacbookPro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

**Comment by bagder** [comment]
Unfortunately an already known issue. See #7716  and the [known bugs](https://curl.se/docs/knownbugs.html#make_distclean_loops_forever).

**Comment by bagder** [comment]
This is believed to be an automake problem but we don't know of a fix.
