### ISSUE TITLE
curl.haxx.se is down for maintenance

### ISSUE THREAD

**Issue by bagder** [curl/curl#823]
# curl.haxx.se is inaccessible

Starting 22:49 Central European time, May 21 2016, the server that hosts **curl.haxx.se**, **cool.haxx.se** and several other services was taken down for reboot and it didn't manage to come back alive. Personnel is meant to get to the machine on the afternoon of the 22nd.

The reboot was made because our network card started to spew out large quantities of broken network packets which caused large packet loss counts and caused downloads and transfers from and to the server to become *terribly slow*.

# Mailing lists are also down

The mailing lists are also hosted and run on the same server. They will be down for as long as the web site is down. And so will all email addresses ending with "@haxx.se".

# Download mirrors in the mean time

Two mirrors that are useful to know about while the main site is down:

http://www.execve.net/curl/
http://curl.askapache.com/download/

# Sorry for this

**Update:** we're now hoping for the afternoon on the 22nd, worst case morning of the 23rd.

**Comment by jay** [comment]
also the documentation is available on internet archive

curl_easy_setopt:
https://web.archive.org/web/20160319102725/https://curl.haxx.se/libcurl/c/curl_easy_setopt.html

curl.1 the man page
https://web.archive.org/web/20160403092831/https://curl.haxx.se/docs/manpage.html

**Comment by bagder** [comment]
It came back online around 14:45 on May 22nd. The slow network situation (broken packets) that triggered the reboot seems to have been resolved for now. Long term however, we will look into upgrading our infrastructure.

**Comment by iantearle** [comment]
Still down.
