### ISSUE TITLE
Wrong coding

### ISSUE THREAD

**Issue by 7-904-001-67-28** [curl/curl#8231]
.\curl.exe -I "https://rr3---sn-5hneknee.googlevideo.com/videoplayback?expire=1641445341&ei=fSPWYcq6L8i4mLAPldaKoAY&ip=78.110.173.172&id=o-AD59IMs80-W1AInJlj538lj22yr6_UQJGYicDi7m0T9W&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&ns=xuag_3aEIBW3xH2evJ6re2oG&cnr=14&ratebypass=yes&dur=3567.304&lmt=1641408177845900&fexp=23886206,24001373,24007246&beids=23886206&c=WEB&txp=5532434&n=13nYxvgU4PaM1w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALtdKWZ0UzoGEGSfVA066Z6YN5o86wxVbDxjwfaNk_UrAiEAjXVzdMcvdiH0FZIfgMeSUpO9Mu2otWkV2rIRz-ksedk%3D&title=%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5%20%D0%BD%D0%B0%D1%81%D1%82%D1%83%D0%BF%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D1%82%D0%B0%D1%80%D0%B8%D0%B7%D0%BC%D0%B0%3F&redirect_counter=1&rm=sn-aigez67s&req_id=32ab84cd98cba3ee&cms_redirect=yes&ipbypass=yes&mh=pL&mip=190.2.132.214&mm=31&mn=sn-5hneknee&ms=au&mt=1641429420&mv=m&mvi=3&pl=22&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIhAIqs7eddtpCQSd5fW8uQgQ5g0TmNl8WMgca7k4ojOPK4AiAd5qtVhFrxRIKXXxYn4rmAXAQhv_xvUJo7ZaHmHULi6A%3D%3D"
HTTP/1.1 200 OK
Last-Modified: Wed, 05 Jan 2022 18:42:57 GMT
Content-Type: video/mp4
Content-Disposition: attachment; filename="╨У╨╗╨╛╨▒╨░╨╗╤М╨╜╨╛╨╡ ╨╜╨░╤Б╤В╤Г╨┐╨╗╨╡╨╜╨╕╨╡ ╨░╨▓╤В╨╛╤А╨╕╤В╨░╤А╨╕╨╖╨╝╨░?.mp4"
Date: Thu, 06 Jan 2022 00:39:33 GMT
Expires: Thu, 06 Jan 2022 00:39:33 GMT
Cache-Control: private, max-age=15468
Accept-Ranges: bytes
Content-Length: 121566256
Connection: close
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Vary: Origin
Cross-Origin-Resource-Policy: cross-origin
X-Content-Type-Options: nosniff
Server: gvs 1.0

Correct file name is «Глобальное наступление авторитаризма_.mp4».

**Comment by dfandrich** [comment]
That's the file name provided by the server, there in the logs. What exactly
are you questioning here?
