### ISSUE TITLE
multi-app.c example - missing call + question

### ISSUE THREAD

**Issue by danger89** [curl/curl#8234]
You are missing a `curl_multi_remove_handle()` call in the [multi-app.c](https://curl.se/libcurl/c/multi-app.html) example. Right?

You could also clean-up the easy handles inside the curl_multi_info_read() method, correct?

Unrelated question: [Sometimes I see](https://curl.se/libcurl/c/crawler.html) the `while(..curl_multi_info_read())` inside the main `while(still_running)`. But this [multi-app.c](https://curl.se/libcurl/c/multi-app.html) example the two while loops are after each other.

What is the best way to execute `curl_multi_info_read()`? **Inside** the while loop of the other while (like crawler.c or 10-at-a-time.c examples), or **after each other** like the multi-app.c example?

Thanks!

Regards,
Melroy van den Berg

**Comment by bagder** [comment]
It does miss them, but that's actually fine and this code doesn't leak any memory. We should probably fix it though and not encourage that style.

They are examples and I think its good that they work differently. They show concepts and that there's not just one way to it in an application. You decide what's best for your application.

**Comment by danger89** [comment]
Maybe grep over the examples files. Since I can not promise this is the only example case with the multi API interface.

**Comment by bagder** [comment]
> regarding this curl_multi_info_read() usage, it was and still is unclear to me if there is any difference between doing this check inside the other while loop, or after each other.

What would the difference be? The API works as defined and documented. You can then select how to use those functions. This particular example chose to invoke the functions like this.

**Comment by danger89** [comment]
> What would the difference be? The API works as defined and documented. You can then select how to use those functions. This particular example chose to invoke the functions like this.

Yes indeed, what would be the difference indeed. That was my question. But I think there is no difference, which is the answer I needed. Thank you.
