### ISSUE TITLE
C-ares Compile Error With Curl

### ISSUE THREAD

**Issue by jeonghyun1** [curl/curl#8237]
I try to use c-ares in libcurl. with cross compile and got the error msg.

/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libcares.so.2, needed by ../lib/.libs/libcurl.so, not found (try using -rpath or -rpath-link)
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_freeaddrinfo'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_set_local_dev'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_getaddrinfo'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_init_options'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_getsock'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_destroy'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_cancel'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_timeout'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_set_servers_ports_csv'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_set_local_ip6'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_library_init'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_set_local_ip4'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_process_fd'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_version'
/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.1.0/../../../../arm-linux-gnueabihf/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `ares_library_cleanup'
collect2: error: ld returned 1 exit status
Makefile:983: recipe for target 'curl' failed
make[2]: *** [curl] Error 1
make[2]: Leaving directory '/home/ljh/work/addares/curl-7.80.0/src'
Makefile:1471: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ljh/work/addares/curl-7.80.0/src'
Makefile:1263: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

My Operation System:
Ubuntu 18.04.6 LTS
type: "vmware" arhitecture:"x86_64"
compiler : gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf
openssl:                     version: 3.1.0-dev
libcurl:                     version: 7.80.0
zlib:                        version: 1.2.11
c-ares:                      version: 1.18.1

Prepare Work.
1. openssl
git clone https://github.com/openssl/openssl.git
cd openssl
./Configure linux-generic32 --prefix=/tmp/openssl --openssldir=/tmp/openssl --cross-compile-prefix=/opt/toolchains/gcc-sigmastar-9.1.0-2020.07-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
make && make install

2. zlib
git clone https://github.com/madler/zlib.git
cd zlib
CHOST=arm-linux-gnueabihf ./configure --prefix=/tmp/zlib
make && make install

3. c-ares
wget https://c-ares.haxx.se/download/c-ares-1.18.1.tar.gz
tar xvf c-ares-1.18.1.tar.gz
cd c-ares-1.18.1
./configure --host=arm-linux-gnueabihf --prefix=/tmp/c-ares --build=i586-pc-linux-gnu
make && make install

4. 
wget http://curl.haxx.se/download/curl-7.80.0.tar.gz
tar xzf curl-7.80.0.tar.gz curl-7.80.0/
cd curl-7.80.0
export TARGETDIR="/tmp"
export CROSS_COMPILE="arm-linux-gnueabihf"
export CPPFLAGS="-I${TARGETDIR}/openssl/include -I${TARGETDIR}/zlib/include -I${TARGETDIR}/c-ares/include"
export LDFLAGS="-L${TARGETDIR}/openssl/libs -L${TARGETDIR}/zlib/libs -L${TARGETDIR}/c-ares/lib"
export LIBS="-lssl -lcrypto"
./configure --prefix=${TARGETDIR}/build --target=${CROSS_COMPILE} --host=${CROSS_COMPILE} --build=i586-pc-linux-gnu --with-ssl --with-zlib --enable-ares=${TARGETDIR}/c-ares

result 
[config.log](https://github.com/curl/curl/files/7826208/config.log)
[Makefile.txt](https://github.com/curl/curl/files/7826214/Makefile.txt)

plz.. help

**Comment by bagder** [comment]
I don't think this is a curl bug. configure seems to detect c-ares correctly and generate a Makefile that uses it. I don't know why your linker then ultimately doesn't like to link with your c-ares library.

**Comment by jeonghyun1** [comment]
The purpose of using c-ares is that curl can't find the dns on the target board.
After compiling with the exception of c-ares, it ran without any problems as a result of running it on the Raspberry Pi.
If you run curl after setting dns in /etc/resolv.conf on the target board, it is still ./curl -I -v www.google.com
* Could not resolve host: www.google.com
* Closing connection 0
curl: (6) Could not resolve host: www.google.com
An error occurs.
what to fix

**Comment by dfandrich** [comment]
I'm not sure of what is working and what is not working for you. Are you saying
curl with the stock resolver works but curl with c-ares doesn't? Do the c-ares
test programs work to resolve names, e.g. "src/adig curl.se" ?

**Comment by jeonghyun1** [comment]
It doesn't work because c-ares doesn't compile in curl.
So, as a result of testing the compiled curl on Raspberry Pi except for c-ares, it works normally.
However, on the target board, the error curl: (6) Could not resolve host: always appears even if dns is set.
Additionally, the same error occurs even if ipv6 is disabled.

**Comment by bagder** [comment]
> It doesn't work because c-ares doesn't compile in curl.

I build curl with c-ares daily and we run such builds in the CI. It works. Your problem is probably more specifically for your setup/environment.

> However, on the target board, the error curl: (6) Could not resolve host

That's likely a problem with your system/network setup and not a problem with curl.

**Comment by jeonghyun1** [comment]
Is the dns server file referenced by curl other than /etc/resolv.conf?

**Comment by jay** [comment]
curl is built to use resolver libraries and does not do the resolving itself. However, DoH (DNS-over-HTTPS via [--doh-url](https://curl.se/docs/manpage.html#--doh-url)) is an exception to this: curl uses the resolver library to resolve the DoH address and then curl does its own DoH resolves using that address.

So, as long curl is not using DoH to resolve your host then it's pretty likely that on *nix /etc/resolv.conf is used, regardless of which resolver library (c-ares or what comes with your OS like libresolv getaddrinfo etc) is used.

c-ares I think uses /etc/resolv.conf exclusively on *nix unless some other configuration file is set, which we don't set. OTOH if you built curl to use the resolver library that comes with your OS (ie you did not build with c-ares) then that library may read /etc/resolv.conf and/or read nameservers from other locations. For example IIRC in Ubuntu you can set specific DNS servers in the DHCP configurations.

I agree with @bagder this sounds like an issue with your system/network and not curl. Generally speaking if other commands which use the OS included resolve library work then curl should work. ping google.com, host google.com, dig +short google.com, etc

**Comment by bagder** [comment]
We need additional data and info for this issue to move anywhere.
