### ISSUE TITLE
Appveyor CI doesn't have autoreconf anymore

### ISSUE THREAD

**Issue by bagder** [curl/curl#8248]
It seems the autotools builds on appveyor now permafail because `./buildconf` fails when it runs `autoreconf`:
~~~
*** Do not use buildconf. Instead, just use: autoreconf -fi
./buildconf: line 4: exec: autoreconf: not found
Command exited with code 127
~~~
[example log](https://ci.appveyor.com/project/curlorg/curl/builds/42129185/job/pvgioxqlky4m0gw7)

**Comment by MarcelRaad** [comment]
IIRC, MSYS2 not having some required packages in newer AppVeyor images was exactly the reason why I used the Visual Studio 2015 image in https://github.com/curl/curl/commit/0f234a5cdebd455f324cdf64b604b4a1340dbbfe. Strange that it seems to have worked then by https://github.com/curl/curl/commit/b667bbe2caf7e7d285b225794f6ae041bdf36093 and broke again now.

I wanted to prepare a PR to update to the VS 2022 images anyway, so I'd just use a consistent working image for all autotools builds (2015 or 2017). Or does anyone have a strong opinion on using a newer image? I'd like to avoid installing packages if possible, which sometimes fails in other CI systems.
