### ISSUE TITLE
`--netrc` option ignores machine environment if default is set on top of `.netrc` file

### ISSUE THREAD

**Issue by filfreire** [curl/curl#8256]
### I did this

I defined my `.netrc` file as:
```
default login bbbbb password bbbbb
machine petstore.swagger.io login aaaaa password aaaaa
```

And then ran the following curl:
```
curl --netrc \
 --request POST \
 --url https://petstore.swagger.io/v2/user  \
 --header 'Content-Type: application/json'   \
--data '{"id":0,"username":"string","firstName":"string","lastName":"string","email":"string","password":"string","phone":"string","userStatus":0}' -v
```
With the above `.netrc` file, `curl` will send the following auth:
```
authorization: Basic YmJiYmI6YmJiYmI=

# if you run echo "YmJiYmI6YmJiYmI=" | base64 --decode
bbbbb:bbbbb
```

So `curl` is using `default` instead of the `machine petstore.swagger.io` entry details.

### I expected the following

I expected the `machine petstore.swagger.io` entry to be used instead. 

If I change the order of the `.netrc` file and place `default` entry in the bottom, like this:

```
machine petstore.swagger.io login aaaaa password aaaaa
default login bbbbb password bbbbb
```

`curl` will use the machine one for the correct hostname when it exists, not overriding it with `default` entry:
```
authorization: Basic YWFhYWE6YWFhYWE=

# if you run echo "YWFhYWE6YWFhYWE=" | base64 --decode
aaaaa:aaaaa
```

### curl/libcurl version

```
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

### operating system

MacOS Monterey 12.1 (21C52) 
```
Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

**Comment by bagder** [comment]
Ack. Still works like this is the latest version...

**Comment by bagder** [comment]
The question is of course if is actually is **supposed** to work like you want.

The [inetutils netrc docs](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) seem to suggest otherwise. Emphasis below added by me:

> ‘default’  This is the same as machine name except that default matches any name. There can be only one default token, and **it must be after all machine tokens**.

**Comment by filfreire** [comment]
@bagder thank you for sharing [this](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html) and looking into the issue.

I had suspicions that maybe it was "by design", and the GNU documentation indeed confirms it. Going to close this issue then. Cheers 👍
