### ISSUE TITLE
Unexpected timeout

### ISSUE THREAD

**Issue by cooljacket** [curl/curl#8259]
We set option “**CURLOPT_TIMEOUT_MS = 1000ms**”，but it perform **abort after just less than 10ms,** while return CURLE_OPERATION_TIMEDOUT(28).

And it happens randomly, about 10% probability, not 100%, which confuses us a lot.

Besides, we use libcurl-0.7.2, looking forward your answer, thanks!

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

> we use libcurl-0.7.2, looking

Are you perhaps referring to 7.72.0 ? On what platform?

**Comment by cooljacket** [comment]
I'm sorry that it's hardly to reproduce the problem.
Maybe we can change a way to find out the truth: **could you please tell me all the ways to return the error code CURLE_OPERATION_TIMEDOUT(28)**.

According to google search results, I know two ways:
1. Really time out
2. Satisfied the **CURLOPT_LOW_SPEED_LIMIT** and **CURLOPT_LOW_SPEED_TIME** option setting.

Is there any other way to abort request and return error code CURLE_OPERATION_TIMEDOUT(28)?

**Comment by bagder** [comment]
> all the ways to return the error code CURLE_OPERATION_TIMEDOUT(28).

That's not an effective way to go about this:
~~~
$ git grep CURLE_OPERATION_TIMEDOUT | wc -l
62
~~~

> curl-7.41.0

Then I strongly suggest your first action is to try something newer. Your version will soon celebrate its 7th birthday.
