### ISSUE TITLE
can't compile on windows 10

### ISSUE THREAD

**Issue by makarhuyaker** [curl/curl#8269]
PS N:\Projects\not-my\cURL\winbuild> nmake /f MakeFile.vc mode=static DEBUG=yes

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

configuration name: libcurl-vc-x86-debug-static-ipv6-sspi-schannel
        cl /Od /D_DEBUG /RTC1 /Z7 /LDd /MDd /DCURL_STATICLIB /I. /I ../lib /I../include /nologo /W4 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL  /DUSE_WIN32_IDN /DWANT_IDN_PROTOTYPES  /DUSE_IPV6  /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL /Fo"..\builds\libcurl-vc-x86-debug-static-ipv6-sspi-schannel-obj-lib/altsvc.obj"  ..\lib\altsvc.c
altsvc.c
N:\Projects\not-my\cURL\include\curl/curl.h(46) : fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\nmake.exe"' : return code '0x2'
Stop.

**Comment by bagder** [comment]
> Cannot open include file: 'stdio.h': No such file or directory

This doesn't sound like a curl problem. This sounds like a "broken compiler" problem.

**Comment by jay** [comment]
[Use a Visual Studio Command Prompt](https://github.com/curl/curl/blob/curl-7_81_0/winbuild/README.md#open-a-command-prompt)

**Comment by makarhuyaker** [comment]
i already fixed it but i have another problem i have everything compile to .exe file but i need dll

**Comment by makarhuyaker** [comment]
ok i tried to use mode=dynamic instead of mode=dll
