### ISSUE TITLE
windows dll load error (R6034)

### ISSUE THREAD

**Issue by intliang** [curl/curl#827]
### curl/libcurl version is curl 7.49.1-DEV (i386-pc-win32) libcurl/7.49.1-DEV WinSSL WinIDN

[curl -V output ]
curl 7.49.1-DEV (i386-pc-win32) libcurl/7.49.1-DEV WinSSL WinIDN
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
### operating system
windows 10 (x64) enterprise version

**Comment by intliang** [comment]
mt.exe should be add in MakefileBuild.vc.
@if exist $(LIB_DIROBJ)\$(LIB_NAME_DLL) @mt.exe -manifest $(LIB_DIROBJ)\$(LIB_NAME_DLL).manifest -outputresource:$(LIB_DIROBJ)\$(LIB_NAME_DLL);2 && copy $(LIB_DIROBJ)\$(LIB_NAME_DLL) $(DIRDIST)\bin\ /y >nul 2<&1 && @if exist $(LIB_DIROBJ)\$(LIB_NAME_STATIC) copy $(LIB_DIROBJ)\$(LIB_NAME_STATIC) $(DIRDIST)\lib\ /y >nul 2<&1

**Comment by gvanem** [comment]
Do you mean a message such as: "**An application has made an attempt to load the C runtime library incorrectly. Please contact the application's support team for more information.**"?

Which seems related to the manifest stuff as you hinted above.

**Comment by intliang** [comment]
@gvanem yes, I added signature by mt.exe to satisfy windows new deployment model available since Windows XP(On versions of Windows that do not support deployment of shared side-by-side assemblies, such as Windows 98 and Windows 2000 Server, the Visual C++ libraries are installed in the System32 folder and WinSxS folder under the operating system root directory, refer to https://msdn.microsoft.com/en-us/library/ms235624(v=vs.80).aspx).
May this issue to be some useful for others.

**Comment by bagder** [comment]
ping @captain-caveman2k, @mback2k - any comments on this?

**Comment by bagder** [comment]
This issue is stuck here since nobody has more input and helpful comments on it. I don't know this Windows stuff. Is it any better since af8eb69cb fixed how to build with embedded manifest?

**Comment by bagder** [comment]
Out-of-date and no more feedback.
