### ISSUE TITLE
Build fails on Clang 14

### ISSUE THREAD

**Issue by lilianmoraru** [curl/curl#8293]
https://github.com/curl/curl/blob/52826d3b791e0436a2338ed36e38a2f7e1f4e9a6/include/curl/curl.h#L114

```
linux/include/curl/curl.h:120:41: error: too few arguments provided to function-like macro invocation
      __has_declspec_attribute(dllimport))
                                        ^
```

On Linux, Clang 14.0.0(built from the `main` branch), this error is being thrown.
Clang 13.0.1(same build config but built from the `release/13.x` branch) works fine.

Reporting early and will reconfirm with a release candidate when that comes out.

**Comment by bagder** [comment]
Given that warning it sounds as if they've changed that macro in 14? I can't seem to find any docs for it though... :disappointed:

**Comment by lilianmoraru** [comment]
Might be a regression from this change: https://github.com/llvm/llvm-project/commit/2edb89c746848c52964537268bf03e7906bf2542#diff-d8dd6191130efea27aca1a54b23fc45eeeb1cc377147f9d6f5ec8b00ff56fafc

**Comment by bagder** [comment]
The curl header has had this setup since #3616 (50482b8c0a2cf531), February 2019, so it feels like something clang shouldn't just break purposely.

**Comment by lilianmoraru** [comment]
I reverted the commit mentioned above https://github.com/llvm/llvm-project/commit/2edb89c746848c52964537268bf03e7906bf2542#diff-d8dd6191130efea27aca1a54b23fc45eeeb1cc377147f9d6f5ec8b00ff56fafc and the issue is fixed.
Sorry, it's an LLVM regression.
I will close this and report to LLVM.

**Comment by lilianmoraru** [comment]
Tracking issue: https://github.com/llvm/llvm-project/issues/53269
