### ISSUE TITLE
image  binary coding problem, thanks

### ISSUE THREAD

**Issue by polyGithub** [curl/curl#830]
### I did this
I want to do this comman by libcurl as follows
 curl -X POST --data-binary @/mnt/hgfs/share2ubuntu/tes27.jpg http://192.168.1.133:4812/search

my code :
ret = curl_formadd(&formpost, &lastptr, CURLFORM_COPYNAME, "POST", CURLFORM_FILE, "/mnt/hgfs/share2ubuntu/test/27.jpg", CURLFORM_CONTENTTYPE, "application/octet-stream", CURLFORM_END);
printf("formadd ret = %d\n",ret);
curl_easy_setopt(curl,CURLOPT_HTTPPOST,formpost);

### I expected the following
IMAGE binary coding

### curl version 7.48.0

[curl -V output perhaps?]
~~~
*   Trying 192.168.1.133...
* Connected to 192.168.1.133 (192.168.1.133) port 4812 (#0)
* WARNING: Using weak random seed
> POST /searcher HTTP/1.1
Host: 192.168.1.133:4212
Accept: */*
Content-Length: 31855
Expect: 100-continue
Content-Type: multipart/form-data; boundary=------------------------4e721b723f7d6af5

< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Content-Length: 29
< Date: Fri, 27 May 2016 03:47:19 GMT
< 
CBL:{"type":"IMAGE_NOT_DECODED"}

CBL:29
* Connection #0 to host 192.168.1.133 left intact
44formadd ret = 0
Speed: 7672206.000 bytes/sec during 0.004 seconds
~~~

**Comment by jay** [comment]
You don't need to use `-X` to set the method to POST in curl. Please read [unnecessary use of curl -X](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/).

What you are experiencing is not a bug, the content encoding types are different. In curl you are POSTing the data using the type x-www-form-urlencoded. In libcurl you are POSTing the data using the type multipart/form-data.

If curl works to post it but what you're doing in libcurl doesn't then to solve this you should send the content x-www-form-urlencoded. To do that enable [`CURLOPT_POST`](https://curl.haxx.se/libcurl/c/CURLOPT_POST.html), set [`CURLOPT_READDATA`](https://curl.haxx.se/libcurl/c/CURLOPT_READDATA.html) to your file handle and [`CURLOPT_POSTFIELDSIZE_LARGE`](https://curl.haxx.se/libcurl/c/CURLOPT_POSTFIELDSIZE_LARGE.html) to your file size (must pass as `(curl_off_t)` type).

I can't find we have an example that does exactly that, so I've attached one: [postfile.zip](https://github.com/curl/curl/files/287596/postfile.zip).

In the future if you have an issue like this and you cannot find the answer in the documentation then please e-mail the question to the [libcurl mailing list](https://cool.haxx.se/mailman/listinfo/curl-library).
