### ISSUE TITLE
Curl Progress-Bar Issue

### ISSUE THREAD

**Issue by agamsol** [curl/curl#8302]
### I did this
```curl -#fkLo "%temp%\Source.txt" "https://pastebin.com/raw/HaAPSSR2"```

### I expected the following
it used to show the progress bar like it always did
`###################################################### 100/100%`

### Actual result
```##O=#    #```  (Gif Below)
![GIF](https://cdn.agamsol.xyz:90/media/cmd_dZzU1K0wBB.gif)

### curl/libcurl version

curl -V output:
- **Windows 11:**
    ```cmd
    C:\Users\Agam>curl -V
    curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
    Release-Date: 2021-09-22
    Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
    Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
    ```
- **WIndows 10:**
    ```bat
    C:\Users\Almo>curl -V
    curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
    Release-Date: 2021-09-22
    Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
    Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
    ```
### operating system
Command was tested on windows 10 and 11

**Comment by bagder** [comment]
The progress bar was before curl 7.58.0 quite confused for contents without a known size, like the one you get in the example above. It could in fact not know when it reached a 100% before the actual end happened. It then used to output a character per data size, which could lead to excessive amounts of output on screen.

I changed that progress bar back in 2018, as can be seen in my [blog post](https://daniel.haxx.se/blog/2018/01/22/a-flying-curl-progress-bar/) about it.

**Comment by agamsol** [comment]
I gave the command to 4 people and they attempted it

all the 4 had the exact same problem and it is not usual
can you attempt to run the command in your system and see?

**Comment by bagder** [comment]
"The usual" has not been "the usual" since 2018

**Comment by agamsol** [comment]
it is not how it acted 2 days ago

2 days ago it worked just fine on the same machine and it would print the expected output

**Comment by bagder** [comment]
2 days ago you were using an ancient curl version. Then you ran windows update and voila, you got your curl updated to a modern version. Now you run a newer curl version. A version with a differently styled `-#` progress bar.

**Comment by Illegal-Services** [comment]
If it was working in a 2 days ago version, then it means this issue can be solved.
So why not patching this unwanted behaviour again, or create a parameter for it?

**Comment by bagder** [comment]
It is not a bug. It just shows the progress bar for a transfer with unknown size differently.

**Comment by Illegal-Services** [comment]
Yeah, for your program it isn't an issue, it's a feature, I agree with that.
but for thee developers using curl to display web request progress bar in the console of their scripts:
The normal users of those scripts aren't supposed to understand the progress bar meatning anymore.

**Comment by agamsol** [comment]
if there was a parameter to set the style and behavior of the progress bar to the old one it would make me (and probably others) really satisfied

or at least bringing back the old style of the progress bar of those who prefer

I use curl a lot and it is running the experience while using curl

**Comment by bagder** [comment]
1. You are using Microsoft Windows and the software you're using here, your curl installation, is **delivered from Microsoft** so go complain to them if you are dissatisfied with they provide to you. We don't owe you nor Microsoft anything since neither of you paid us anything.
2. We're always keen and interested in fixing bugs and problems in curl when we learn about them. In this case you insist this is a bug, but you ignore my explanation as to *why* this change was done.
3. If you want to stick with 7.55.1 forever, go build that version yourself and live happily ever after (I wouldn't recommend it though).
4. To perhaps change the existing behavior, then don't duck for the facts and realities but instead accept what they are and propose different ways to deal with them. I am the first to acknowledge that there are many ways to do that and I am convinced that this existing progress-bar can be improved. Just don't expect **me** to put that very high up on my agenda unless you intend to pay me to do it.

**Comment by agamsol** [comment]
1. I couldn't find any place to ask Microsoft to make changes in curl

2. I hope you understand the main reason I'm here, in the end you own curl.. I'm just trying to report a bug- you said it is not a bug, see this as a suggestion from me and @Illegal-Services who complain about the same thing,

4. Again, we are here complaining it because it is not how people expect it to behave.

Imagine a random person who uses a script which is depended on curl
he would just see the output which now replaces the progress bar and think for himself that its just an issue

do whatever you want, I'm just saying it as an unsatisfied curl user
