### ISSUE TITLE
--tlsv1.3 does not seem to work as expected

### ISSUE THREAD

**Issue by icing** [curl/curl#8309]
### I did this

In my Apache httpd test suite for mod_tls(rustls) I run

```
> curl --tlsv1.3 url
```
and a TLSv1.2 connection is negotiated.

### I expected the following

I expected either a connection with TLSv1.3 or a failure if not supported/negotiated.

Using a locally build curl 7.81.0 with OpenSSL 3.0.1 works as expected. Maybe this is some half-baked libressl 1.3 support?

### curl/libcurl version

```
> curl --version
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
[curl -V output]
```

### operating system

macOS Monterey 12.1

**Comment by bagder** [comment]
Apparently TLS 1.3 is supported by default since libressl [3.1.1](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.1.1-relnotes.txt). The preprocessor symbols seem to exist before that.

**Comment by bagder** [comment]
Ah no, I misdiagnosed. PR pending.

**Comment by icing** [comment]
Thanks!
