### ISSUE TITLE
curl: (35) gnutls_handshake() failed: Error in the push function.

### ISSUE THREAD

**Issue by zhanghqgit** [curl/curl#832]
$ rvm reinstall 2.1.5
ruby-2.1.5 - #removing src/ruby-2.1.5..
ruby-2.1.5 - #removing rubies/ruby-2.1.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/16.04/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/zhanghengqiang/.rvm/rubies/ruby-2.1.5, this may take a while depending on your cpu(s)...
ruby-2.1.5 - #downloading ruby-2.1.5, this may take a while depending on your connection...
ruby-2.1.5 - #extracting ruby-2.1.5 to /home/zhanghengqiang/.rvm/src/ruby-2.1.5....
ruby-2.1.5 - #configuring.....................................................
ruby-2.1.5 - #post-configuration..
ruby-2.1.5 - #compiling.............................................................................................
ruby-2.1.5 - #installing.................................
ruby-2.1.5 - #making binaries executable..
ruby-2.1.5 - #downloading rubygems-2.4.8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0     91      0  0:00:01  0:00:01 --:--:--    91
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
**curl: (35) gnutls_handshake() failed: Error in the push function.**
**There was an error(35).**
Checking fallback: https://github.com/rubygems/rubygems/archive/v2.4.8.tar.gz
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error while trying to fetch rubygems. 
Halting the installation.

**Comment by jay** [comment]
I think this is unlikely to be a curl issue. Please run `curl -V` and give us your version information. What happens when you try to retrieve that resource directly?
`curl -OL https://github.com/rubygems/rubygems/archive/v2.4.8.tar.gz`

**Comment by zhanghqgit** [comment]
zhanghengqiang@ubuntu16:~/python-pycurl-openssl/first$ curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

ubuntu 16.04

**Comment by zhanghqgit** [comment]
zhanghengqiang@ubuntu16:~/python-pycurl-openssl/first$ curl -OL https://github.com/rubygems/rubygems/archive/v2.4.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0     64      0 --:--:--  0:00:01 --:--:--    64
100  435k    0  435k    0     0  75635      0 --:--:--  0:00:05 --:--:--  125k
zhanghengqiang@ubuntu16:~/python-pycurl-openssl/first$ ll
total 468
drwxrwxr-x 3 zhanghengqiang zhanghengqiang   4096 May 28 22:05 ./
drwxrwxr-x 3 zhanghengqiang zhanghengqiang   4096 May 28 15:41 ../
drwxrwxr-x 8 zhanghengqiang zhanghengqiang   4096 May 28 15:41 .git/
-rw-rw-r-- 1 zhanghengqiang zhanghengqiang      8 May 28 15:41 README.md
-rw-rw-r-- 1 zhanghengqiang zhanghengqiang 445479 May 28 22:05 v2.4.8.tar.gz



no problem

**Comment by zhanghqgit** [comment]
sorry for this, I think it's my virtualbox's network problem.
