### ISSUE TITLE
SOVERSION missing in cmake recipe?

### ISSUE THREAD

**Issue by infn-ke** [curl/curl#8324]
A cmake build of libcurl 7.81 does not give any so version files. I only get `libcurl.so`, but expected to also get so version files, e.g. `libcurl.so.4` and `libcurl.so.4.5.0`. Typically this can be done in a cmake recipe like this;

```cmake
set_target_properties(${LIB_NAME}
  PROPERTIES
  VERSION x.y.z
  SOVERSION x.y.z
)
```

**Comment by jzakrzewski** [comment]
It's a long-standing issue. The problem is that the SOVERSION is determined by libtool and rules to are very platform-dependent. I took a stab at this ones but ended up with an ugly mess that did not got merged.

**Comment by infn-ke** [comment]
But isn't setting SOVERSION using cmake portable? 

Or is the problem that libcurl tries to support multiple build systems, e.g. autoconf and cmake? I guess the libtool there is autoconf specific?

**Comment by jzakrzewski** [comment]
Setting yes. But choosing the value to set to - not really. Currently we have `VERSIONINFO=-version-info 11:0:7`, which on Linux creates `libcurl.so.4 -> libcurl.so.4.7.0` but, for example, on Darwin `libcurl.so.12 -> libcurl.so.12.0`

**Comment by infn-ke** [comment]
I can see this issue in known bugs. It links to a PR that is closed;

https://github.com/curl/curl/pull/5935

**Comment by bagder** [comment]
It was closed without getting merged yes. Feel free to bring the effort back on the table!

**Comment by infn-ke** [comment]
I decided to use automake for doing my build. The cmake build had more unwanted side effects that I don't want (e.g. depends on `dl`, https://github.com/curl/curl/issues/6165)

**Comment by bagder** [comment]
Also listed as a "known bug" for quite some time: https://curl.se/docs/knownbugs.html#use_correct_SONAME

**Comment by bagder** [comment]
> depends on dl

That's not a dependency that cmake adds. That dependency usually comes with OpenSSL. But unrelated to this issue.

**Comment by jzakrzewski** [comment]
@bagder unfortunately: https://github.com/curl/curl/blob/e35637f193c259d2e44ef6163db800326a1d35e9/CMakeLists.txt#L333

**Comment by bagder** [comment]
Ah, so I was wrong, sorry. Well, that's still a separate issue.
