### ISSUE TITLE
`curl -XPOST` falls back to POST method after being redirected with `303 See other` when using with `--location`.

### ISSUE THREAD

**Issue by JayDoubleu** [curl/curl#8327]
### I did this
```shell
curl --location --request POST 'https://apim-releases-api.azure-api.net/test/curl' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "curl",
"source": "github",
"repo": "curl/curl",
"release": "latest",
"asset" : "curl-7.81.0.tar.gz"
}'
```
### I expected the following

Curl should follow links : `POST  > 303 > GET > 302 > GET 200`

Instead it falls back to POST method after 303 redirect: `POST > 303 > POST`

Removing `--request POST` makes it behave correctly. Also working with wget, python postman etc without having to remove method.
```shell
curl --location 'https://apim-releases-api.azure-api.net/test/curl' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "curl",
"source": "github",
"repo": "curl/curl",
"release": "latest",
"asset" : "curl-7.81.0.tar.gz"
}'
```
### curl/libcurl version

```
curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1l-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.45.1 OpenLDAP/2.4.59
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

`Linux hostname 5.15.16-200.fc35.x86_64 #1 SMP Thu Jan 20 15:38:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bagder** [comment]
This is the documented and expected behavior.

**Comment by JayDoubleu** [comment]
@bagder Are you referring to below? : 

> When curl follows a redirect and if the request is a POST, it will send the following request with a GET if the HTTP response was 301, 302, or 303. If the response code was any other 3xx code, curl will re-send the following request using the same unmodified method.

**Comment by bagder** [comment]
I'm referring to [this](https://curl.se/docs/manpage.html#-X):

> The method string you set with --request will be used for all requests, which if you for example use --location may cause unintended side-effects when curl does not change request method according to the HTTP 30x response codes - and similar.

**Comment by JayDoubleu** [comment]
I see. I must say I'm a little bit confused about this.

What if I want to make first call specifically with POST and rest should just follow GET when used with `--location`

Manpage also mentions below which suggests there is a dedicated `--post` which I can use for this purpose with `--location`.

> Normally you do not need this option. All sorts of GET, HEAD, POST and PUT requests are rather invoked by using dedicated command line options.

**Comment by bagder** [comment]
In your case above, you remove `--request POST` from the command line to make it "correct". Since the `--data*` options imply POST by themselves.

**Comment by jzakrzewski** [comment]
You can just use an empty body: `curl -L -d "" example.com` will send a POST request to `example.com` and will follow redirects as expected. 
-X / --request force request type for the entire transfer and don't really care what the request type is - you could write `-X GUGUS` and it will send that ;)

**Comment by JayDoubleu** [comment]
I see and I guess having things like first call made with PATCH or PUT usually doesn't redirect anywhere hence the options are not needed for those ? Or is there another way to make it go via those methods only in first call ?

**Comment by bagder** [comment]
For non-POST operations the story is possibly different. But that's another issue. With #8130 we might soon merge support for only changing the first request.
