### ISSUE TITLE
crash on docker 20.10.12 / debian 10 (OSX 12.1)

### ISSUE THREAD

**Issue by asah** [curl/curl#8328]
[Dockerfile.txt](https://github.com/curl/curl/files/7933696/Dockerfile.txt)

```
$ docker build .
[+] Building 7.2s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 212B                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/debian:10                                                                                                                   0.7s
 => CACHED [1/4] FROM docker.io/library/debian:10@sha256:94ccfd1c5115a6903cbb415f043a0b04e307be3f37b768cf6d6d3edff0021da3                                                      0.0s
 => [2/4] RUN apt-get update                                                                                                                                                   2.4s
 => [3/4] RUN apt-get install --no-install-recommends -y ca-certificates curl                                                                                                  3.6s
 => ERROR [4/4] RUN curl -fLO https://registry.npmjs.org/yarn/-/yarn-1.22.17.tgz                                                                                               0.5s
------
 > [4/4] RUN curl -fLO https://registry.npmjs.org/yarn/-/yarn-1.22.17.tgz:
#7 0.183   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 0.183                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Segmentation fault
------
executor failed running [/bin/sh -c curl -fLO https://registry.npmjs.org/yarn/-/yarn-1.22.17.tgz]: exit code: 139
```

### curl/libcurl version

$ curl --version
curl 7.64.0 (aarch64-unknown-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

### operating system

Mac OSX 12.1 Monterey
Docker Engine 20.10.12 (desktop 4.4.2)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -a
Linux 130c8fe5c32c 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 GNU/Linux

(on the host env)

$ uname -a
Darwin hadid 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 x86_64

**Comment by bagder** [comment]
Does running `curl -fLO https://registry.npmjs.org/yarn/-/yarn-1.22.17.tgz` crash (consistently) when run on the aarch64 host?

**Comment by asah** [comment]
also, curl'ing other files works fine in the docker env:

$ curl -fLO
https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_dark_2x_r2.png
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100  8043  100  8043    0     0  19287      0 --:--:-- --:--:-- --:--:--
19287

**Comment by asah** [comment]
hmmm... I can try that but FYI this is the default setup under vagrant and
using the default (debian 10) version of curl... I'm surprised you can't
repro... perhaps it's an ARM issue? e.g. diff software versions for ARM?

I'm also running into issues with cargo and rust...

Is the release process tested on ARM?

**Comment by bagder** [comment]
Well, you can't repro either with just curl you said, which I think says something. That made me not try very hard.

curl runs on gazillions of ARM machines with no problems. Every commit we merge is tested on arm as well.

**Comment by asah** [comment]
but super helpful to know about the CI test - I'll continue looking on my
end as well... maybe it's something it's docker ?  or the particular debian
version ?

anyway, thx!! for the quick reply - really appreciate it. I'll keep looking.

**Comment by bagder** [comment]
And we have done **25** releases since the version you're using. With 2489 documented bug fixes.

**Comment by asah** [comment]
sorry!  I'm just a the luser :-) caught in the middle... I'll try forcing
debian to use a later version and see if that fixes it.

(I understand that segfaults imply security issues, which is why I reported
it...)

one sec... (and thx again!)

**Comment by asah** [comment]
ok, I spun up an ARM instance in google cloud (n2d machine type) and it
worked fine. So, I'm going to assume the culprit is somewhere between OSX
and Docker... reinstalling Docker from scratch, will report back...

**Comment by asah** [comment]
ok this is really crazy - starting from a clean VM, I also got wget 1.20.3
to crash on that URL !  I also switched the VM to ubuntu 20.04 and got that
to crash on curl 7.68.0

I'm starting to think this is maybe something with OSX 12.1 (newly
released) or with docker (constantly getting updates)...

anyway, sorry for the weird bug report - obviously, feel free to
close/ignore until someone else reports it... I switched to wget2 and that
seems to work.

**Comment by andersk** [comment]
I can reproduce this crash in a Debian 10 VM, and I can still reproduce it with curl compiled from Git `master`. But I was able to avoid the crash using `--ciphers ECDHE-ECDSA-AES128-GCM-SHA256`. (By default it picks `ECDHE-ECDSA-CHACHA20-POLY1305` and crashes.) This suggests the issue is likely in OpenSSL.

I’m running the `debian:10` image in Docker 20.10.12 on macOS 12.1, MacBook Air (M1, 2020).

**Comment by andersk** [comment]
Yeah, if I run `openssl s_client -connect npmjs.org:443` and type `GET /`, it segfaults, but if I do the same with `openssl s_client -connect npmjs.org:443 -cipher ECDHE-ECDSA-AES128-GCM-SHA256`, it works. So I think this issue can be closed.

**Comment by andersk** [comment]
Bisecting OpenSSL shows that the crash was introduced in openssl/openssl@2cf7fd698ec1375421f91338ff8a44e7da5238b6 (`OpenSSL_1_1_1b~37`) and fixed in openssl/openssl@5795acffd8706e1cb584284ee5bb3a30986d0e75 (`OpenSSL_1_1_1i~21`).

**Comment by bagder** [comment]
Duplicate of #7932

**Comment by bagder** [comment]
thanks for that great research @andersk!
