### ISSUE TITLE
Threaded resolver and signals

### ISSUE THREAD

**Issue by ukaea-chah** [curl/curl#8339]
### I did this

Used libcurl with the threaded resolver, in software which uses only a single thread (and is not thread-safe)

### I expected the following

I reasoned that the resolver thread would not interfere with the application, since no common code was used.

However, when investigating a fault (not directly related to libcurl), I realised from a stack trace that my assumption was not entirely true: signal handlers were being run in the context of the resolver thread(s).  This could potentially cause a problem thus:

- The application and a signal handler manipulate some shared data

- The main application blocks relevant signals while modifying the shared data, believing that this will protect it

- But the signal may get delivered to and handled by the resolver thread while the main application thread is modifying the data

Now, I realise that this may be a vanishingly small corner case (use of threaded resolver in signal-safe but not thread-safe
application), but I nevertheless bring it to your attention as a potential problem.

I shall be applying a local patch to libcurl to block signals around pthread_create, so that the resolver thread inherits a fully-blocked signal mask and so never handles any signal.

### curl/libcurl version

(overdue for an update, but the situation still applies)

curl 7.60.0 (sparc-sun-solaris2.10) libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.3
Release-Date: 2018-05-16
Protocols: ftp ftps http https smb smbs 
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy 

### operating system

SunOS gen-pub-51 5.10 Generic_153153-01 sun4v sparc sun4v

**Comment by bagder** [comment]
It is unclear what you say the bug here is, but libcurl offers [CURLOPT_NOSIGNAL](https://curl.se/libcurl/c/CURLOPT_NOSIGNAL.html) for applications to tell it to not do anything signal-wise.

Also, note that you're using a (by now) rather old libcurl version.

**Comment by ukaea-chah** [comment]
It's debatable whether to class it as a bug.  Perhaps worthy of a mention in FAQ 5.18 that the use of an internal thread by libcurl may compromise the signal-safety of a single-threaded application.

**Comment by bagder** [comment]
Let me see if I understand this correctly:
1. You use libcurl (without setting `CURLOPT_NOSIGNAL` to true). It should then ignore all signals caused while libcurl is invoked.
2. Yet you get a signal from the resolver thread

Is that what happens? If so, then I think it is a bug.

What is causing the resolver thread to generate the signal?

**Comment by ukaea-chah** [comment]
I guess the application could bracket all calls into libcurl with code to block the relevant (or all) signals, then any resolver thread from libcurl's pthread_create would inherit the blocked signal mask.

**Comment by jay** [comment]
This issue is a program design issue and not a curl issue. You assume you have control over all threads and that's not guaranteed. Any call may start a thread. (Maybe in practice that is a greater possibility in Windows than *nix?) It is well known that what you can do safely in a signal handler is limited.
