### ISSUE TITLE
Asterisk in data replaced with directory listing

### ISSUE THREAD

**Issue by iftikharhaidry** [curl/curl#8348]
I am sending some data in JSON, the data is save in a file named **datafile** that looks like this;
```
{
        "title": "Test-Notebook", "text": " * some-message * "
}
```
While making post request, Asterisk * around _some-message_ is replaced with directory listing of the current directory when data is received at the remote end, which is not my intended operation. My curl post request looks like this;
`curl -H 'Content-Type: application/json' -X POST http://someurl/api --data-binary "@datafile"`

**Comment by dfandrich** [comment]
I'm not able to reproduce this.

curl doesn't perform globbing, and especially not on the contents of a binary
data file. What I guess is probably happening is that the datafile contents is
generated with a shell script that is not properly quoting its data and the
shell performs globbing before writing the contents into datafile. Take a look
at the contents of datafile manually and I think you'll find the directory
listing is already there.

Also, drop the -X POST: https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

**Comment by iftikharhaidry** [comment]
Thanx @dfandrich , that's exactly what was happening.
