### ISSUE TITLE
SOCKS proxy not working via IPv6

### ISSUE THREAD

**Issue by azrdev** [curl/curl#835]
### I did this
`curl --proxy "socks://hostname-with-AAAA-record" qrdn.de`
Result:
~~~
curl: (7) Can't complete SOCKS4 connection to 95.143.172.200:109. (91), request rejected or failed.
~~~
Where the address is the IPv4 address of `qrdn.de`, and the port varies between invocations. Same happens with `socks4`, `socks4a`, and `socks5`.

### I expected the following
Access via the proxy.

### curl/libcurl version
On Ubuntu wily
~~~
curl 7.43.0 (x86_64-pc-linux-gnu) libcurl/7.43.0 GnuTLS/3.3.15 zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
~~~

On Fedora 23
~~~
curl 7.43.0 (x86_64-redhat-linux-gnu) libcurl/7.43.0 NSS/3.22 Basic ECC zlib/1.2.8 libidn/1.32 libssh2/1.6.0 nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink 
~~~

### Additional info
There is an old thread [here][1] which tells you don't care about this issue. Is this still true, and would you accept a patch nevertheless?

[1]: <https://curl.haxx.se/mail/archive-2005-08/0041.html>

**Comment by bagder** [comment]
> which tells you don't care about this issue

No, that mail was written by a random person saying that. Not someone talking for the project.

And yes, we would absolutely accept a patch that fixes this flaw.

**Comment by azrdev** [comment]
adding this do known bugs is a good thing, but IMHO that doesn't close the issue here

**Comment by bagder** [comment]
Bugs that aren't being worked on are dealt with this way to not clutter the view of the active bugs. Doesn't imply the bug is fixed, just that we're not able to work on it now.

**Comment by mback2k** [comment]
@bagder If I remember correctly, I implemented this in 2012 according to https://github.com/curl/curl/commit/f332f141021e027d603d2adf62cebaedd469575f. Maybe something broke in the meantime?

**Comment by bagder** [comment]
It doesn't matter what the reason is, I believe the report and nobody is working on a fix so I'm making sure it is not forgotten or falling through any cracks and I've added it as a known bug. I'd be delighted if someone either fixed it or just told me it works in the latest version.

**Comment by mback2k** [comment]
I just digged out an old security related project of mine that initially made me add IPv6 support to curl, because I required it in order to test the projects functionality. And even after upgrading to the current git head it works like a charm:
```
marc@alice:~/src/curl$ ./src/curl -V
curl 7.50.2-DEV (i686-pc-linux-gnu) libcurl/7.50.2-DEV OpenSSL/1.0.1e zlib/1.2.7
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

marc@alice:~/src/curl$ ./src/curl --socks5 [::1]:12348 -g http://[feca::]/whoami.php
You are connecting from the following IP address

feca:68f2:82fc:64a1:ffa9:501e:a6ba:13f5
marc@alice:~/src/curl$ ./src/curl --socks5 [::1]:12348 -g http://[fecb::]/whoami.php
You are connecting from the following IP address

fecb:0:5577:d440:2ad5:e5b5:f731:595c
marc@alice:~/src/curl$ ./src/curl --socks5 [::1]:12348 -g http://alice/whoami.php
You are connecting from the following IP address

feca:ccbe:e16f:513f:bf73:490f:7068:4958
marc@alice:~/src/curl$ ./src/curl --socks5 [::1]:12348 -g http://bob/whoami.php
You are connecting from the following IP address

fecb:0:ec61:a3b2:c49a:ddfc:dc79:ad7d

marc@alice:~/src/curl$ cat /etc/hosts
feca::0 alice
fecb::0 bob
```

**Comment by mback2k** [comment]
I just successfully tested the following proxy connections using the --socks5-hostname option:
```
curl --socks5-hostname 127.0.0.1:1080 http://ipv6.whatismyv6.com/
curl --socks5-hostname [::1]:1080 http://ipv6.whatismyv6.com/
curl --socks5-hostname 127.0.0.1:1080 http://ipv4.whatismyv6.com/
curl --socks5-hostname [::1]:1080 http://ipv4.whatismyv6.com/
```
At least from my perspective there is no longer a (known) issue. Please give it another try.

**Comment by mback2k** [comment]
It looks like the only combination that does not work is a connection to a IPv6-only hostname with local lookup (e.g. using the --socks5 instead of --socks5-hostname option):
```
curl --socks5 127.0.0.1:1080 http://ipv6.whatismyv6.com/
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (8)
curl --socks5 [::1]:1080 http://ipv6.whatismyv6.com/
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (8)
```

**Comment by mback2k** [comment]
I just verified that connections to a IPv6 host over an IPv6 SOCKS5 proxy connection do also work:
`./src/curl -v --socks5 ip6-localhost:12348 http://ipv6.whatismyv6.com/`
To me this means that all combinations of IPv4, hostname and IPv6 connections work and there is no open issue at the moment. At least one I can reproduce. So I would like to revert your KNOWN_BUGS commit @bagder, if that is okay with you?

**Comment by bagder** [comment]
go go go! 👍

**Comment by mback2k** [comment]
Thanks @bagder. I reverted the commit now. I think @azrdev mainly ran into an issue, because SOCKS4 does not and can not support IPv6 destinations, because the protocol does not support IPv6.
