### ISSUE TITLE
CURLPAUSE_ALL not invoking socket callback

### ISSUE THREAD

**Issue by fsbs** [curl/curl#8360]
### I did this

There appeared inconsistencies when testing socket callback (`CURLMOPT_SOCKETFUNCTION`) in _pycurl_ on different platforms: on Linux pausing a transfer (`CURLPAUSE_ALL`) does invoke the socket callback, but on macOS.

I wrote a test just in _libcurl_ and the same issue appeared on Linux as well. Here is the code: https://gist.github.com/fsbs/e3a14cc683d307c78f1854150564fad4

Output:
```
libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.40.0 librtmp/2.3 OpenLDAP/2.4.49
multi_add_handle()
 - timer_callback(): 0 ms
multi_socket_action()
 - socket_callback(): socket=5, event=1
 - timer_callback(): 1 ms
easy_pause(PAUSE_ALL)   <--- no callback invoked
easy_pause(PAUSE_CONT)
 - timer_callback(): 0 ms
cleanup
 - socket_callback(): socket=5, event=4
* Closing connection 0
 - timer_callback(): -1 ms
```

My understanding is that pausing a transfer should inform downstream application about which sockets to remove from its polling list - if the application was previously told to add those sockets to its polling list, as seen in the output above.

Seems like `singlesocket()` in lib/easy.c does not detect any differences and therefore doesn't call `multi->socket_cb()`.

### I expected the following

1. `curl_multi_add_handle()` calls a timer callback with 0 ms to schedule an immediate kickstart via `curl_multi_socket_action()`
2. the initial `curl_multi_socket_action()` calls a socket callback to inform the application about the socket(s) that it needs to poll
3. **`curl_easy_pause(curl, CURLPAUSE_ALL)` calls a socket callback to inform the application which sockets it should stop waiting on**

In the above test steps 1 and 2 work as expected, but not step 3. I expected the following output:

```
easy_pause(PAUSE_ALL)
 - socket_callback(): socket=5, event=4
easy_pause(PAUSE_CONT)
 - timer_callback(): 0 ms
 - socket_callback(): socket=5, event=1
```

### curl/libcurl version

```
libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.40.0 librtmp/2.3 OpenLDAP/2.4.49
```

### operating system

```
Linux 5.4.0-96-generic #109-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
How do you know there are no sockets left for libcurt to wait for in the first place? I could easily reproduce this case when the resolver file descriptor is the one libcurl waits for and I don't see how or why the pause should stop that.

**Comment by fsbs** [comment]
My bad, my initial test was with a local server on Linux, so without resolving or handshakes the socket callback was invoked in step 3 - but not on macOS, which tripped me off.

I'll close the issue.
