### ISSUE TITLE
[AIX] Curl SMB is not inserting the right dialects in the negotiate protocol request

### ISSUE THREAD

**Issue by Pazzeo** [curl/curl#8371]
I'm using the following curl version
```
curl 7.72.0 (powerpc-ibm-aix5.1.0.0) libcurl/7.72.0 OpenSSL/1.0.2u zlib/1.2.11
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```
Trying to connect to a Windows Server SMB v1, I have the following error:
`curl: (7) Couldn't connect to server`

The command used is the following:
`curl -T test.txt -u "DOMAIN\user:password" smb://REMOTE_SERVER_IP/SHARE/`

Debuging the request, I discovered that the negotiate protocol request generated by curl is without ny dialects, while it should be present.

**Comment by bagder** [comment]
> the negotiate protocol request generated by curl is without ny dialects

I'm afraid I have no idea what that means nor how to reproduce this.

**Comment by Pazzeo** [comment]
Thanks bagder, may I ask you if you can do a test from your side doing a network capture?

**Comment by bagder** [comment]
When I do what? The only SMB I have is test 1451, and that is very basic.

**Comment by bagder** [comment]
What does it say with you add `-v` to the command line? Error 7 sounds like it fails to TCP connect to the server.

**Comment by bagder** [comment]
This issue will be closed unless you provide more information that indicates that this is actually a bug.

**Comment by bagder** [comment]
No response. Closing.
