### ISSUE TITLE
Cannot pass the :scheme header from command line.

### ISSUE THREAD

**Issue by siddharthchhabrap** [curl/curl#8381]
### I did this
curl -v http://127.0.0.1 --http2-prior-knowledge --header ":scheme:aaa"
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Failed sending HTTP request
* Connection #0 to host 127.0.0.1 left intact
curl: (55) Failed sending HTTP request

### I expected the following
I expected the :scheme header to be passed for the http2 request and get a server response.

### curl/libcurl version
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSocket

### operating system
Mac OS X 12.1 Monterey.

**Comment by jay** [comment]
> I expected the :scheme header to be passed for the http2 request and get a server response.

Can you give an example where it would be useful to set scheme?

**Comment by bagder** [comment]
Ah yes! h2 (and h3) psuedo headers cannot be replaced, removed or added actually. I consider this a mistake we should fix.

**Comment by mkauf** [comment]
The new log message contains a typo: "pseduo"

**Comment by jay** [comment]
> The new log message contains a typo: "pseduo"

Thanks, landed in 592f114.
