### ISSUE TITLE
Test 1165 [Verify configure.ac and source code CURL_DISABLE_-sync] failing

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#8384]
### I did this

Look at the autobuilds at https://curl.se/dev/builds.html.

### I expected the following

All green :-)
Instead, test 1165 was failing with
```
Present in configure.ac, not used by code: CURL_DISABLE_NTLM
Documented, but not used by code: CURL_DISABLE_NTLM
```

The last usage of `CURL_DISABLE_NTLM` was removed with https://github.com/curl/curl/commit/1bf3643f7b1760f7f92cbb42df2dbdc94e29bf96#diff-9f7d1f1e2f497cabfc05b279c04b116f9213b2f2ea8f6b4c4ec795252fd1905e.

### curl/libcurl version

master

### operating system

all

**Comment by bagder** [comment]
It is still used in code.

https://github.com/curl/curl/blob/a6e9196724be781a580d19805cddb9548029c665/lib/curl_setup.h#L630

I'm not sure why this test fails on some systems...

**Comment by bagder** [comment]
I just realized why... PR pending.
