### ISSUE TITLE
compiling p5-www-curl error DID_MEMORY_FUNC_TYPEDEFS

### ISSUE THREAD

**Issue by spagu** [curl/curl#839]
### I did this
compiling error

clang -c -I/usr/include -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -pipe -O2 -pipe -march=native -DVERSION=\"4.17\" -DXS_VERSION=\"4.17\" -fPIC "-I/usr/lib64/perl5/5.24.0/x86_64-linux-thread-multi/CORE" Curl.c
In file included from Curl.xs:574:
./curlopt-constants.c:19:58: error: non-void function 'constant' should return a value [-Wreturn-type]
if (strEQ(name, "DID_MEMORY_FUNC_TYPEDEFS")) return 

### curl/libcurl version
curl 7.49

### operating system
freebsd 10.1/11

**Comment by bagder** [comment]
Sorry, but p5-www-curl is not part if the curl project, you need to report problems with it to that team!

**Comment by spagu** [comment]
I think problem lies in https://github.com/curl/curl/blob/master/include/curl/curl.h on line 388 that is in this project. I am not sure compiler trigger for this. 

```
#ifndef CURL_DID_MEMORY_FUNC_TYPEDEFS
/*
 * The following typedef's are signatures of malloc, free, realloc, strdup and
 * calloc respectively.  Function pointers of these types can be passed to the
 * curl_global_init_mem() function to set user defined memory management
 * callback routines.
 */
typedef void *(*curl_malloc_callback)(size_t size);
typedef void (*curl_free_callback)(void *ptr);
typedef void *(*curl_realloc_callback)(void *ptr, size_t size);
typedef char *(*curl_strdup_callback)(const char *str);
typedef void *(*curl_calloc_callback)(size_t nmemb, size_t size);
#define CURL_DID_MEMORY_FUNC_TYPEDEFS
#endif
```
Change was here : https://github.com/curl/curl/commit/a9a1d303f5d8d2d2899c5efffe6360bfc09aa50e 

I am not an expert but I think by adding parameter to define would work
```
#define CURL_DID_MEMORY_FUNC_TYPEDEFS 0
```
then code compiles without problems. I do not know implications for this and what to do.

I am just saying this....

**Comment by bagder** [comment]
But there's nothing wrong with the particular define there, having just a define without a value works perfectly fine. The problem is that the perl module seems to parse CURL_ * defines and wrongly goes crazy if they have no values. That define really shouldn't be used/exported by the perl binding anyway and could be seen as an associated bug.
