### ISSUE TITLE
Build with BoringSSL and nghttp2 fails

### ISSUE THREAD

**Issue by Stalinko** [curl/curl#8416]
I'm trying to compile the latest cURL with BoringSSL and nghttp2 following this instruction:
https://everything.curl.dev/source/build/tls/boringssl

This is what I did:

```
#Build BoringSSL in "/tmp/boringssl"
cd /tmp
git clone https://boringssl.googlesource.com/boringssl
cd boringssl

mkdir build
cd build
cmake ..
make

#set up the build tree to get detected by curl's configure
cd ..
mkdir lib
cd lib
ln -s ../build/ssl/libssl.a
ln -s ../build/crypto/libcrypto.a

#Build nghttp2
cd /tmp
git clone https://github.com/tatsuhiro-t/nghttp2.git
cd nghttp2
autoreconf -i
automake
autoconf
./configure
make
sudo make install

#build curl
cd /tmp
wget https://curl.se/download/curl-7.81.0.tar.gz
tar -xf https://curl.se/download/curl-7.81.0.tar.gz
cd curl-7.81.0
./buildconf
LIBS=-lpthread ./configure --with-nghttp2=/usr/local --with-ssl=/tmp/boringssl
make
```

After all I get:

```
/usr/bin/ld: /tmp/boringssl/lib/libcrypto.a(bcm.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1550: libcurl.la] Error 1
make[2]: Leaving directory '/tmp/curl-7.81.0/lib'
make[1]: *** [Makefile:1359: all] Error 2
make[1]: Leaving directory '/tmp/curl-7.81.0/lib'
make: *** [Makefile:1261: all-recursive] Error 1
```

I'm not familiar with this stack at all that's why I have no idea how to solve that :(

**Can anybody help or hint at least?**

My environment is Ubuntu 20.04 (the official ubuntu package from dockerhub) with the following packages: git cmake build-essential golang wget autoconf libtool

**Comment by bagder** [comment]
This is not a curl issue. This is just an issue to build with a third party library. The CI job for BoringSSL makes weird double builds, where the second build uses `-DCMAKE_POSITION_INDEPENDENT_CODE=on`:

https://github.com/curl/curl/blob/d9c61a9792cc4961dbc5258693843983b87ae485/scripts/zuul/before_script.sh#L73-L88

**Comment by jzakrzewski** [comment]
For me it looks like the first build is to build shared objects and the second one builds a static library but with PIC enabled, so that one can link it from a different shared object.
Building boringSSL with `-DCMAKE_POSITION_INDEPENDENT_CODE=on` should be enough to get it going IMO.

**Comment by Stalinko** [comment]
@jzakrzewski thanks a lot! it worked!

For the future readers:
When you build BoringSSL you need to change this:

`cmake ..`

to this:

`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=on ..`

**Comment by bagder** [comment]
The instructions in the book you first looked at is also already updated accordingly....
