### ISSUE TITLE
-q doesn't work as advertised in 7.49.0

### ISSUE THREAD

**Issue by cyberrufus** [curl/curl#842]
Output command not working with -q and remote-name in config file. Curl uses working directory.

Expected output command to work rather than file in working directory.

curl version 7.49, 7.49.1. Functions correctly in 7.48

Windows 10 x64

**Comment by bagder** [comment]
I'm sorry, but can you please give us a full command line that doesn't work for you?

**Comment by cyberrufus** [comment]
curl -q http:url-to-download.txt -o C:\path-to-output.txt

Downloads to working directory rather than specified output. Curl appears to be reading remote-name in config file in spite of the -q command.
