### ISSUE TITLE
It fails when downloading a lot files using bash shell under MAC OS X 10.11.5

### ISSUE THREAD

**Issue by arliang** [curl/curl#843]
### I did this
I downloaded a lot of files (485 files, about 9 GB in summary) in my windows PC, I wanted to transfer them to my MAC BOOK PRO.
Then I tried SMB, but failed.
At last, I started an HTTP server on windows, and wrote a shell like this in MAC OSX

```bash
curl localdomain.com/file1.mp4 -o file1.mp4
curl localdomain.com/file2.mp4 -o file2.mp4
curl localdomain.com/file3.mp4 -o file3.mp4
```

Then something strange happened:

It **goes wrong when downloading a lot of files ( 485 files )** in a bash file.
But **it goes well when downloading two files** in a bash file.

### curl/libcurl version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets  

### operating system
OS X El Capitan 10.11.5

http server  [serve (installing by npm install -g serve)]
appache 2.2.22
servers in win 10

**I solve this by add a `sleep 1` after each curl command.**
How to solve this problem without adding sleep command?

**Comment by bagder** [comment]
You have to give us more details to have anything to go on here. To me it sounds like this is more likely to be a server issue. What does "It goes wrong" mean **exactly** ? Return codes, HTTP response headers etc will help us understand this issue.

**Comment by arliang** [comment]
OMG, I finally found that I forgot to full-fill the URL in the first shell script file😭 
I should have checked my bash shell file twice or more.
I'm very sorry for troubling you.
