### ISSUE TITLE
Unify GetVersionEx calls in libcurl

### ISSUE THREAD

**Issue by bagder** [curl/curl#845]
We currently call GetVersionEx() in three places in the library and we're now discussing adding a fourth (in #840). The function call is used to figure out which Windows version libcurl runs on, and takes decisions based on that.

I think we should consider making it so we call GetVersionEx() exactly once (in the global init perhaps) and we assign booleans for the uses we have "has alpn" (for #840), "needs sndbuf" (see Curl_sndbufset in connect.c), "has security.dll" (for curl_sspi.c) etc.

Thoughts @jay, @captain-caveman2k, @mback2k ?

**Comment by captain-caveman2k** [comment]
This was one of the reasons for adding system_win32 in the recent security patch - i am hoping to at least centralise this functionality.

**Comment by chris-araman** [comment]
`GetVersionEx` has been deprecated. Why not use the Version Helper Functions instead?
https://msdn.microsoft.com/en-us/library/windows/desktop/dn424972.aspx

**Comment by bagder** [comment]
I don't care about which exact function call to use - use the most appropriate one. My point is that we could centralize the invocation of whatever function should be used instead of calling it in 4 different places (and most existing invokes already use a more complicated approach than just GetVersionEx as is quite obvious when reading the code). But then I'm not a windows developer nor expert so I won't be the one to write the patch...

**Comment by captain-caveman2k** [comment]
Curl_verify_windows_version() added - comments and suggestions welcome.
