### ISSUE TITLE
Error: Building package curl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Kelta-King** [curl/curl#8463]
I am trying to install curl with vcpkg. Here is the command that I used.
```
vcpkg install curl:x64-windows
```
The error message is as follows...
```
Error: Building package curl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+curl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[curl]+Build+error
including:
  package: curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 7.81.0
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: fe63cf718 2022-02-16 (67 minutes ago)
```
After getting this error, I updated the vcpkg with git pull. Strill I'm getting the same error. I don't understand what is going wrong here.

I am using windows operating system and trying to use curl in my c++ project.

**Comment by bagder** [comment]
The vcpkg is not provided nor maintained by us. You need to contact the vcpkg maintainers about this issue.

**Comment by bagder** [comment]
I see you already created https://github.com/microsoft/vcpkg/issues/23136

**Comment by Kelta-King** [comment]
Thanks @bagder for your response. I tried every possible ways that I know with vcpkg. But it didn't solve my issue. So, I thought that maybe there might be some issue with curl with vcpkg. So, I created with issue. 
Anyways, thanks for clearing my doubt :-)

**Comment by gvanem** [comment]
Try with a `vcpkg install curl:x64-windows --debug` for some hints.

**Comment by Kelta-King** [comment]
Okay @gvanem
Thanks...
