### ISSUE TITLE
340bb19 breaks intended usage of curl_multi_assign

### ISSUE THREAD

**Issue by m6w6** [curl/curl#8480]
### I did this
Watched CI break with curl 7.81.

Seriously, 340bb1905f88b13655e89760ca6f4f2d02dc011a breaks the intended usage of `curl_multi_assign`.
> **Quoting [docs](https://curl.se/libcurl/c/curl_multi_socket_action.html):**  
> 
> In a typical application you allocate a struct or at least use some kind of semi-dynamic data for each socket that we must wait for action on when using the [curl_multi_socket_action](https://curl.se/libcurl/c/curl_multi_socket_action.html) approach.
>
> When our socket-callback gets called by libcurl and we get to know about yet another socket to wait for, we can use [curl_multi_assign](https://curl.se/libcurl/c/curl_multi_assign.html) to point out the particular data so that when we get updates about this same socket again, we do not have to find the struct associated with this socket by ourselves.

### I expected the following
`curl_multi_assign` to work from within callbacks.

Coincidentally, `docs/examples/hiperfifo.c` and `docs/examples/multi-event.c` are broken, too.

### curl/libcurl version
7.81/master

### operating system
POSIX

**Comment by jay** [comment]
try #8483

**Comment by jay** [comment]
Thanks
