### ISSUE TITLE
cross-compiling for Android yields incompatible libcurl.a

### ISSUE THREAD

**Issue by 257** [curl/curl#8497]
### I did this
`sh build.sh`

[[`build.sh`]](https://gist.github.com/960a9f3e35e58f07c0e72e9dff9d5a04)
[[`CMakeLists.txt`]](https://gist.github.com/3a5c52b4b24680303942156169bc1112)

`fetch_cli.c` is just a _hello world_ with `#include <curl/curl.h>`
### I expected the following
`libcurl.a` i can link to
### curl/libcurl version
commit e2e340822268f9503038faccffaa0bc7ced42e9b (HEAD, origin/master, origin/HEAD, master)
[curl -V output]
NA
### operating system
host: Linux
target: Android

Linux p51 5.16.9-gentoo-p51 #2 SMP PREEMPT Tue Feb 15 13:36:39 EST 2022 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux

**Comment by jzakrzewski** [comment]
And what DID you get instead?

**Comment by bagder** [comment]
This build seems to use cmake features that aren't provided nor edited at all by us, so if this misbehaves it seems like its done outside of our control anyway?

**Comment by jzakrzewski** [comment]
Partially for sure but from the first glance it should work. They do nothing more than starting curl CMake build from their own superbuild, which should work in my opinion. This is why I asked what is the actual output.
Other interesting thing would be to try a build with the same arguments "standalone" and see if that gives the expected results.

**Comment by 257** [comment]
`ANDROID_LLVM_TRIPLE` needs to be set and it's not trivial for a newbie to figure out how to pass that to `ExternalProject_Add()`.
this works for me, i think, (not sure if i'm linking to `libcurl.a` or `libcurl.so`):
[[`CMakeLists.txt`]](https://gist.github.com/257/69a0c93a2c7d775b184ef16d349b2380)
[[`fetch/CMakeLists.txt`]](https://gist.github.com/2ab4cb81510d6551ccc6fb22ad3a13b6)

sorry for the noise.
