### ISSUE TITLE
Windows file:/// paths with drive letter but without colon no longer work

### ISSUE THREAD

**Issue by bagder** [curl/curl#8510]
### Discussed in https://github.com/curl/curl/discussions/8508

<div type='discussions-op-text'>

<sup>Originally posted by **imichael66** February 25, 2022</sup>
Hello,
Seems to be a problem with the "file://" scheme
after recompiling curl i have this error

$ ./curl  file:///D/fileA.txt
curl: (37) Couldn't open file /D/fileA.txt

I know the file exists D:\fileA.txt

Extra info:
-----------
(1) Here is my ./configure output:
configure: Configured to build curl/libcurl:

  Host setup:       x86_64-w64-mingw32
  Install prefix:   /mingw64
  Compiler:         gcc
   CFLAGS:          -Werror-implicit-function-declaration -O2 -Wno-system-headers -Wenum-conversion
   CPPFLAGS:        -isystem C:/msys64/mingw64/include -isystem ../openssl-3.0.1/include -isystem ../openssl-3.0.1/include/openssl -DOPENSSL_SUPPRESS_DEPRECATED
   LDFLAGS:         -LC:/msys64/mingw64/lib -L../openssl-3.0.1/lib
   LIBS:            -ladvapi32 -lcrypt32 -lssl -lcrypto -lgdi32 -lwldap32 -lzstd -lz -lws2_32

  curl version:     7.81.0
  SSL:              enabled (OpenSSL v3+)
  SSH:              no      (--with-{libssh,libssh2})
  zlib:             enabled
  brotli:           no      (--with-brotli)
  zstd:             enabled (libzstd)
  GSS-API:          no      (--with-gssapi)
  GSASL:            no      (libgsasl not found)
  TLS-SRP:          enabled
  resolver:         POSIX threaded
  IPv6:             enabled
  Unix sockets:     no      (--enable-unix-sockets)
  IDN:              no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  enabled
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  Code coverage:    disabled
  SSPI:             no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP:             enabled (winldap)
  LDAPS:            enabled
  RTSP:             enabled
  RTMP:             no      (--with-librtmp)
  PSL:              no      (libpsl not found)
  Alt-svc:          enabled (--disable-alt-svc)
  HSTS:             enabled (--disable-hsts)
  HTTP1:            enabled (internal)
  HTTP2:            no      (--with-nghttp2, --with-hyper)
  HTTP3:            no      (--with-ngtcp2, --with-quiche)
  ECH:              no      (--enable-ech)
  Protocols:        DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP
  Features:         AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM SSL TLS-SRP alt-svc libz zstd

(2) im compiling for Windows 10 and Mingw64
MINGW64_NT-10.0-19042 SKMT-003 3.3.3-341.x86_64 2022-01-18 13:00 UTC x86_64 Msys

</div>

**Comment by jay** [comment]
> the thing is the distribution curl gets the file $ **curl** file:///D/fileA.txt ---------------oTHIS IS A TEST FROM fileA.txto----------------
> 
> but the recompiled one get the error $ **./curl** file:///D/fileA.txt curl: (37) Couldn't open file /D/fileA.txt

IMO this is user error. I don't know why older curl was supporting drives without colons.

**Comment by imichael66** [comment]
You suggested a user error, could yu elaborate pls ?

**Comment by jay** [comment]
> You suggested a user error, could yu elaborate pls ?

You need the colon after the drive letter. file:///D:/fileA.txt

**Comment by imichael66** [comment]
Look like you are right when putting the semi-colon, things work correctly!

$ ./curl  file:///D:/fileA.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0  90140      0 --:--:-- --:--:-- --:--:-- 90140
---------------oTHIS IS A TEST FROM fileA.txto----------------

Isn't this a regression?
regards

**Comment by jay** [comment]
> Isn't this a regression?

IMO no, but we can leave this open for a while in an attempt to gather more feedback.

**Comment by imichael66** [comment]
Ok, 
I'll be monitoring this thread.
Thanks for your help.
Cheers.

**Comment by BrianInglis** [comment]
Users should also remember that '|' has always been a synonym for ':' in the file URI scheme (when more convenient for a platform or scripting language) and considerations for other platforms and file systems in [RFC 8089 Appendix E. Nonstandard Syntax Variations](https://datatracker.ietf.org/doc/html/rfc8089#appendix-E) including total omission of the authority in RFC compliant clients.

**Comment by bagder** [comment]
My reading of this is that we agree that the colon or pipe should be in there in the path to become a proper Windows path, and then this is not a bug. Closing.
