### ISSUE TITLE
curl_multi_remove_handle() blocks when there are outstanding threads blocked in getaddrinfo()

### ISSUE THREAD

**Issue by codewiz** [curl/curl#8515]
This NetworkManager bug seems to be caused by libcurl blocking in curl_multi_remove_handle():
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/934

More analysis here:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/404#note_1275795

This is libcurl-7.81.0-2.fc36.x86_64 from Fedora 36, which is built with --enable-threaded-resolver: 
https://src.fedoraproject.org/rpms/curl/blob/rawhide/f/curl.spec#_245

### curl/libcurl version
curl 7.81.0 (x86_64-redhat-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.0 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.6.1
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Fedora 36

Linux giskard 5.17.0-0.rc5.102.fc36.x86_64 #1 SMP PREEMPT Mon Feb 21 19:16:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
I believe this is the known bug mentioned here: https://curl.se/docs/knownbugs.html#Multi_perform_hangs_waiting_for

**Comment by codewiz** [comment]
Thank you for the quick response, Daniel! Could you please suggest a workaround?

On glibc systems, a possible solution would be switching to getaddrinfo_a() and eliminating the threads.

On Linux, BSD and many other systems, res_nmkquery() + res_nsend() provide a do-it-yourself asynchronous resolver API.

res_nsend() is present on Bionic, but it's always been broken (does not forward the query to netd and application processes don't have have any resolvers configured). Instead, the Android NDK provides an async dns API very similar to res_nsend():
https://developer.android.com/ndk/reference/group/networking#android_res_nsend

**Comment by dfandrich** [comment]
Have you tried compiling with c-ares?

**Comment by bagder** [comment]
Introducing a new resolver backend is not easy and will take time and effort. It's much more than "just" sending DNS requests that's needed.

I think we maybe should consider creating an option for libcurl that says "don't wait for sub-threads" which then possibly could lead to memory leaks, but most important would avoid this kind of "hang".

**Comment by codewiz** [comment]
> Introducing a new resolver backend is not easy and will take time and effort. It's much more than "just" sending DNS requests that's needed.

Yeah, I agree.

> I think we maybe should consider creating an option for libcurl that says "don't wait for sub-threads" which then possibly could lead to memory leaks, but most important would avoid this kind of "hang".

One thing we did in the past when dealing with non-cancellable blocking RPC libraries is to simply detach the threads after setting an "orphaned" flag so the thread knows it has to cleanup itslelf when the blocking call returns.

It's not a perfect solution, because you could end up with a pile of blocked threads if an application starts and cancels operations in rapid succession. But it's still better than blocking the main thread for 10-15 seconds, I guess.

**Comment by bagder** [comment]
As this is a known issue, and one that nobody is currently working on addressing I'm closing this. Anyone and everyone is of course still encouraged to work on fixing this issue.
