### ISSUE TITLE
http/3: transfer closed with n bytes remaining to read

### ISSUE THREAD

**Issue by sunng87** [curl/curl#8523]
### I did this

I'm using curl to call http/3 server provided by [jetty](https://github.com/eclipse/jetty.project/). I'm getting error like `curl: (18) transfer closed with 8 bytes remaining to read`:

```
curl3 --http3 -vv -k https://localhost:5443/
*   Trying 127.0.0.1:5443...
* Connect socket 5 over QUIC to 127.0.0.1:5443
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
* Connected to localhost () port 5443 (#0)
* h3 [:method: GET]
* h3 [:path: /]
* h3 [:scheme: https]
* h3 [:authority: localhost:5443]
* h3 [user-agent: curl/7.81.0]
* h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55ae2ab50d20)
> GET / HTTP/3
> Host: localhost:5443
> user-agent: curl/7.81.0
> accept: */*
>
< HTTP/3 200
< server: Jetty(10.0.9-SNAPSHOT)
< content-length: 8
* transfer closed with 8 bytes remaining to read
* Connection #0 to host localhost left intact
curl: (18) transfer closed with 8 bytes remaining to read
```

### I expected the following

When I switch to the client provided by quiche code base, it received the whole body without error. 
From Jetty debug log, the response should have been written to curl. I [filed an issue](https://github.com/eclipse/jetty.project/issues/7643) to Jetty and it seems curl didn't deal with response in two QUIC packets.

### curl/libcurl version

```
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 BoringSSL zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) nghttp2/1.47.0 quiche/0.11.0
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL UnixSockets zstd
```

### operating system

```
Linux bulldog14s 5.16.11-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 24 Feb 2022 02:18:22 +0000 x86_64 GNU/Linux
```

**Comment by sunng87** [comment]
@bagder I just tested with 7.82.0 unfortunately the issue persists. The new `curl -V` output:

```
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 BoringSSL zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) nghttp2/1.47.0 quiche/0.12.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL UnixSockets zstd
```

Output for `curl`ing the server is almost same as 7.81

```
*   Trying 127.0.0.1:5443...
* Connect socket 5 over QUIC to 127.0.0.1:5443
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
* Skipped certificate verification
* Connected to localhost () port 5443 (#0)
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: localhost:5443]
* h2h3 [user-agent: curl/7.82.0]
* h2h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x5558dbd3bd40)
> GET / HTTP/3
> Host: localhost:5443
> user-agent: curl/7.82.0
> accept: */*
>
< HTTP/3 200
< server: Jetty(10.0.9-SNAPSHOT)
< content-length: 8
* transfer closed with 8 bytes remaining to read
* Connection #0 to host localhost left intact
curl: (18) transfer closed with 8 bytes remaining to read

```

I will look at jetty side to see if it's possible to provide you a reproducible server for debugging, because the it is still on development without a stable release.

**Comment by bagder** [comment]
> I will look at jetty side to see if it's possible to provide you a reproducible server for debugging

Thanks, that would help a lot!

**Comment by sunng87** [comment]
Steps to run a debugging server:

- checkout the latest jetty branch: `git clone https://github.com/eclipse/jetty.project.git`
- switch to the `10.0.x` branch if it's not default
- install jetty locally as maven module `mvn install -DskipTests`
- make sure you have **libquiche 0.11.0** installed on your system since current jetty HEAD have version check on libquiche
- checkout my [clojure jetty project](https://github.com/sunng87/ring-jetty9-adapter): `git clone https://github.com/sunng87/ring-jetty9-adapter.git`
- switch to http3 branch: `git checkout feature/http-3`
- make sure your have [lein](https://leiningen.org/#install) installed, and run the example http/3 server via `lein with-profiles default,example-http3 run`. This will start http/3 server on localhost, port 5443. It prints debug log of jetty to stderr by default.
- call the server with curl `curl --http3 -v -k https://localhost:5443/` to see the issue

**Comment by bagder** [comment]
Thanks, but that's a mighty complicated setup that I don't expect to do myself.

**Comment by dfandrich** [comment]
Maybe if you provided a Dockerfile and a command-line to run it, it would
significantly reduce the difficulty to others in reproducing the problem.

**Comment by sunng87** [comment]
I finally managed to create a docker image to reproduce this:

https://hub.docker.com/r/sunng/rj9a-http3

**Comment by cowwoc** [comment]
It doesn't sound like this issue was actually fixed. Does anyone have an update on this?

**Comment by bagder** [comment]
The h3 support in curl has been improved a lot lately. Very old issues no longer apply. If there are issues with h3 in 8.1.0,please submit new ones.
