### ISSUE TITLE
makefile.vc6 builds are currently broken

### ISSUE THREAD

**Issue by captain-caveman2k** [curl/curl#853]
Following 6cabd78531 makefile.vc6 based builds are currently broken - as can be seen from my Windows auto builds.

**Comment by bagder** [comment]
#854 is supposedly the fix...

**Comment by bagder** [comment]
I added the missing object file now in commit 05a69ce32, but I assume we also need crypt32.lib in there? Can we do that unconditionally?

**Comment by bagder** [comment]
I added what I believe should work. I'll monitor the autobuilds for a while and see that they get going again...

**Comment by jay** [comment]
> I added the missing object file now in commit 05a69ce, but I assume we also need crypt32.lib in there? Can we do that unconditionally?

crypt32 comes starting in Windows 2000, I'm not sure about earlier.
`12/07/1999  08:00a             476,944 crypt32.dll`
As far as the lib file goes it stands to reason that if the DLL is there the earlier versions of SDK come with crypt32.lib. The earliest SDK I have is VC6 w/PSDK February 2003, and it has crypt32.lib.

**Comment by bagder** [comment]
Thanks for that info @jay, then I'll leave it used there unconditionally!
