### ISSUE TITLE
option  CURL_IPRESOLVE_V4 doesn't work

### ISSUE THREAD

**Issue by algorithmn** [curl/curl#8530]
### I did this
 I change curl version from 7.68.0 to 7.79.1
 add option CURL_IPRESOLVE_V4 
 But I can still observe ipv6 dns request,and response is slow, curl_easy_perform return -28(Resolving timed out after 5001 milliseconds).
 then ,I rollback curl version(7.68.0) ,and don't modify my code, everything is ok, and there is no ipv6 dns request
### I expected the following
There is no ipv6 dns request when I add CURL_IPRESOLVE_V4  option.
### curl/libcurl version

[curl -V output]
curl 7.68.0 (arm-unknown-linux-gnueabi) libcurl/7.68.0 OpenSSL/1.1.1l zlib/1.2.11 c-ares/1.18.1 nghttp2/1.43.0
Release-Date: 2020-01-08
Protocols: file gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps
Features: AsynchDNS Debug HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP TrackMemory UnixSockets

curl 7.79.1 (arm-unknown-linux-gnueabi) libcurl/7.79.1 OpenSSL/1.1.1l zlib/1.2.11 c-ares/1.18.1 nghttp2/1.43.0
Release-Date: 2021-09-22
Protocols: file gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps
Features: alt-svc AsynchDNS Debug HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP TrackMemory UnixSockets

### operating system
aarch64 GNU/Linux

**Comment by bagder** [comment]
The option will prevent IPv6 from being used, not necessarily avoid it being requested.

**Comment by algorithmn** [comment]
I refer to example.c again. It explains the same reason as you said
but I did another experiment with curl-7.68.0
curl -v www.google.com (ipv4 & ipv6  be resolved，connect with ipv6 address)
curl -v -4 www.google.com (only ipv4  be resolved，connect with ipv4 address)

Is this expected ？

**Comment by algorithmn** [comment]
> The option will prevent IPv6 from being used, not necessarily avoid it being requested.

I refer to example.c again. It explains the same reason as you said
but I did another experiment with curl-7.68.0
curl -v [www.google.com](http://www.google.com/) (ipv4 & ipv6 be resolved，connect with ipv6 address)
curl -v -4 [www.google.com](http://www.google.com/) (only ipv4 be resolved，connect with ipv4 address)

Is this expected ？

**Comment by algorithmn** [comment]
> > The option will prevent IPv6 from being used, not necessarily avoid it being requested.
> 
> I refer to example.c again. It explains the same reason as you said but I did another experiment with curl-7.68.0 curl -v [www.google.com](http://www.google.com/) (ipv4 & ipv6 be resolved，connect with ipv6 address) curl -v -4 [www.google.com](http://www.google.com/) (only ipv4 be resolved，connect with ipv4 address)
> 
> Is this expected ？

@bagder

**Comment by bagder** [comment]
This connects to IPv6 addresses only:

`curl -v6 www.google.com -o /dev/null`

This connects to IPv4 addresses only:

`curl -v4 www.google.com -o /dev/null`

**Comment by algorithmn** [comment]
> This connects to IPv6 addresses only:
> 
> `curl -v6 www.google.com -o /dev/null`
> 
> This connects to IPv4 addresses only:
> 
> `curl -v4 www.google.com -o /dev/null`

@bagder, I know that. I wonder why curl - 4 doesn't have IPv6 DNS request when I use curl-7.68.0

**Comment by bagder** [comment]
Sorry, I was under the impression this was a bug-report that says "CURL_IPRESOLVE_V4 doesn't work" and now you say you know it works?

curl 7.68.0 is already a rather old version and it used a slightly different logic back then. In particular commit 84d2839740ca, shipped in curl 7.77.0, is probably what you're seeing.

**Comment by algorithmn** [comment]
> curl 7.68.0 is already a rather old version and it used a slightly different logic back then. In particular commit [84d2839](https://github.com/curl/curl/commit/84d2839740ca78041ac7419d9aaeac55c1e1c729), shipped in curl 7.77.0, is probably what you're seeing.

@bagder ，Thank you sincerely for your explanation，I originally thought the logic has not changed from 7.68.0 to 7.79.1 .
 In addition， Is there any way to solve  or avoid this problem(easy perform return  28 because ipv6 resolve timeout，ipv4 resolve is successful) ？

**Comment by jay** [comment]
I notice libcurl has c-ares do two lookups in parallel, one for IPv4 and one for IPv6. The query_completed_cb [comments](https://github.com/curl/curl/blob/curl-7_82_0/lib/asyn-ares.c#L587) say that's intended, but I'm curious what kind of difference you see with just a single request:
~~~diff
diff --git a/lib/asyn-ares.c b/lib/asyn-ares.c
index fd0bb6c..c614908 100644
--- a/lib/asyn-ares.c
+++ b/lib/asyn-ares.c
@@ -798,13 +798,11 @@ struct Curl_addrinfo *Curl_resolver_getaddrinfo(struct Curl_easy *data,
 #ifdef HAVE_CARES_IPV6
     if(Curl_ipv6works(data)) {
       /* The stack seems to be IPv6-enabled */
-      res->num_pending = 2;
+      res->num_pending = 1;
 
       /* areschannel is already setup in the Curl_open() function */
       ares_gethostbyname((ares_channel)data->state.async.resolver, hostname,
-                          PF_INET, query_completed_cb, data);
-      ares_gethostbyname((ares_channel)data->state.async.resolver, hostname,
-                          PF_INET6, query_completed_cb, data);
+                          PF_UNSPEC, query_completed_cb, data);
     }
     else
 #endif
~~~

**Comment by bagder** [comment]
> I notice libcurl has c-ares do two lookups in parallel, one for IPv4 and one for IPv6.

That's only for outdated versions of c-ares, as it didn't used to support both versions at once.

**Comment by bagder** [comment]
>  Is there any way to solve or avoid this problem(easy perform return 28 because ipv6 resolve timeout，ipv4 resolve is successful) ？

Maybe c-ares should behave better for this situation? Are you setting any timeout or is it the defaults?

**Comment by algorithmn** [comment]
> Maybe c-ares should behave better for this situation? Are you setting any timeout or is it the defaults?

@bagder 
 Will you optimize this situation in the future ？, I set 5s timeout

**Comment by bagder** [comment]
>  Will you optimize this situation in the future ？, I set 5s timeout

I think this is something that could be considered for enhancing in c-ares so that it would return the IPv4 results here instead of timing out waiting for the IPv6 ones as well. I could consider working on this, sure.

**Comment by algorithmn** [comment]
@bagder 
Thank you for your help, I have no more question.

**Comment by bagder** [comment]
I figure this then ends up as not really a curl bug, but more of a possible improvement for c-ares to handle timeouts of an individual family better.
