### ISSUE TITLE
.net P/Invoke x86 error

### ISSUE THREAD

**Issue by Kumhy** [curl/curl#8549]
### my code
```
//internal delegate int WriteCallback(IntPtr buf, int size, int nmemb, IntPtr userdata);

public static void Main(string[] args)
{
    NativeMethods.curl_global_init();
    using (Curl curl = NativeMethods.Easy.curl_easy_init())
    {
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.URL, "http://test.ipw.cn");
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.HEADER, 1L);
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.WRITEFUNCTION, (data, size, nmemb, userp) =>
        {
            int realsize = size * nmemb;
            //var buffer = new byte[realsize];
            //Marshal.Copy(data, buffer, 0, realsize);
            //content.Write(buffer, 0, realsize);
            return realsize;
        });

        NativeMethods.Easy.curl_easy_perform(curl);
    }
    NativeMethods.curl_global_cleanup();
}
```
### working condition
x64 run is success
x86 run is error
Program crashes after writecallback debug returns realsize
error info:
`System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”`

### curl/libcurl version
```
curl 7.81.0 (i386-pc-win32) libcurl/7.81.0 OpenSSL/3.0.1 (Schannel) zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets
```

**Comment by bagder** [comment]
I suspect you did something wrong in your build. Verify by trying a 32 bit [official windows build](https://curl.se/windows/).  I believe it doesn't show this problem and still uses the same callback.

**Comment by Kumhy** [comment]
> I suspect you did something wrong in your build. Verify by trying a 32 bit [official windows build](https://curl.se/windows/). I believe it doesn't show this problem and still uses the same callback.

I did not compile it from the source code, the dll is extracted from the official binary version

**Comment by bagder** [comment]
l have to defer how that is supposed to work or not to someone else.

**Comment by gvanem** [comment]
@Kumhy You're invoking managed code (the lambda) from unmanaged code. 
How can you be sure that the correct `libcurl.dll` gets loaded? 
IMHO, use a local function instead where you test if `IntPtr.Size` is correct

**Comment by Kumhy** [comment]
> 

```
//internal delegate int WriteCallback(IntPtr buf, int size, int nmemb, IntPtr userdata);
private static int cb(IntPtr data, int size, int nmemb, IntPtr userp)
{
    int realsize = size * nmemb;
    //var buffer = new byte[realsize];
    //Marshal.Copy(data, buffer, 0, realsize);
    //content.Write(buffer, 0, realsize);
    return realsize;
}

public static void Main(string[] args)
{
    WriteCallback callback = new WriteCallback(cb);
    IntPtr ptr = Marshal.GetFunctionPointerForDelegate(callback);

    NativeMethods.curl_global_init();
    using (Curl curl = NativeMethods.Easy.curl_easy_init())
    {
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.URL, "http://test.ipw.cn");
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.HEADER, 1L);
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.WRITEFUNCTION, ptr);

        NativeMethods.Easy.curl_easy_perform(curl);
    }
    NativeMethods.curl_global_cleanup();
}
```
x64 call succeeded
x86 call failed
still the same error

**Comment by Kumhy** [comment]
> @Kumhy You're invoking managed code (the lambda) from unmanaged code. How can you be sure that the correct gets loaded? IMHO, use a local function instead where you test if is correct`libcurl.dll``IntPtr.Size`

```
//internal delegate int WriteCallback(IntPtr buf, int size, int nmemb, IntPtr userdata);
private static int cb(IntPtr data, int size, int nmemb, IntPtr userp)
{
    int realsize = size * nmemb;
    //var buffer = new byte[realsize];
    //Marshal.Copy(data, buffer, 0, realsize);
    //content.Write(buffer, 0, realsize);
    return realsize;
}

public static void Main(string[] args)
{
    WriteCallback callback = new WriteCallback(cb);
    IntPtr ptr = Marshal.GetFunctionPointerForDelegate(callback);

    NativeMethods.curl_global_init();
    using (Curl curl = NativeMethods.Easy.curl_easy_init())
    {
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.URL, "http://test.ipw.cn");
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.HEADER, 1L);
        NativeMethods.Easy.curl_easy_setopt(curl, CURL_OPT.WRITEFUNCTION, ptr);

        NativeMethods.Easy.curl_easy_perform(curl);
    }
    NativeMethods.curl_global_cleanup();
}
```
x64 call succeeded
x86 call failed
still the same error

**Comment by gvanem** [comment]
Shouldn't it be:
```
private static UIntPtr cb(IntPtr data, UIntPtr size, UIntPtr nmemb, IntPtr userp) {
  return size * nmemb;
}
```

to match the signature of a `curl_write_callback`.

*PS*. I know almost next to nothing about C# and Pinvoke.

**Comment by Kumhy** [comment]
> Shouldn't it be:
> 
> ```
> private static UIntPtr cb(IntPtr data, UIntPtr size, UIntPtr nmemb, IntPtr userp) {
>   return size * nmemb;
> }
> ```
> 
> to match the signature of a `curl_write_callback`.
> 
> _PS_. I know almost next to nothing about C# and Pinvoke.

It doesn't work either, I tested it
It's okay, I'll try another way

**Comment by Kumhy** [comment]
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int WriteCallback(IntPtr buf, int size, int nmemb, IntPtr userdata);

That's it

**Comment by Cmo1976** [comment]
I need help processing packages

**Comment by bagder** [comment]
@Cmo1976 this is not the place for that
