### ISSUE TITLE
curl_multi_perform blocks until SMTP responses to POST DATA

### ISSUE THREAD

**Issue by worawatt** [curl/curl#8555]
TBH, I am not sure if this is a bug or not because the function that blocks is actually called `smtp_block_statemach`

### I did this
I am using curl multi perform to send emails over SMTP and I observed that if the SMTP server is non-responsive, the curl_multi_perform will block.
The same behavior also happens on the example: https://github.com/curl/curl/blob/master/docs/examples/smtp-multi.c
I just modified the example to print the time spent by curl_multi_perform:
```c++
#include <string.h>
#include <curl/curl.h>
#include <chrono>
#include <iostream>
#include <iomanip>

  /* This is an example showing how to send mail using libcurl's SMTP
   * capabilities. It builds on the smtp-mail.c example to demonstrate how to use
   * libcurl's multi interface.
   */

#define FROM_MAIL     "<sender@example.com>"
#define TO_MAIL       "<recipient@example.com>"
#define CC_MAIL       "<info@example.com>"

static const char* payload_text =
"Date: Mon, 29 Nov 2010 21:54:29 +1100\r\n"
"To: " TO_MAIL "\r\n"
"From: " FROM_MAIL "\r\n"
"Cc: " CC_MAIL "\r\n"
"Message-ID: <dcd7cb36-11db-487a-9f3a-e652a9458efd@"
"rfcpedant.example.org>\r\n"
"Subject: SMTP example message\r\n"
"\r\n" /* empty line to divide headers from body, see RFC5322 */
"The body of the message starts here.\r\n"
"\r\n"
"It could be a lot of lines, could be MIME encoded, whatever.\r\n"
"Check RFC5322.\r\n";

struct upload_status {
    size_t bytes_read;
};

static size_t payload_source(char* ptr, size_t size, size_t nmemb, void* userp)
{
    struct upload_status* upload_ctx = (struct upload_status*)userp;
    const char* data;
    size_t room = size * nmemb;

    if ((size == 0) || (nmemb == 0) || ((size * nmemb) < 1)) {
        return 0;
    }

    data = &payload_text[upload_ctx->bytes_read];

    if (data) {
        size_t len = strlen(data);
        if (room < len)
            len = room;
        memcpy(ptr, data, len);
        upload_ctx->bytes_read += len;

        return len;
    }

    return 0;
}

int main(void)
{
    CURL* curl;
    CURLM* mcurl;
    int still_running = 1;
    struct curl_slist* recipients = NULL;
    struct upload_status upload_ctx = { 0 };

    curl_global_init(CURL_GLOBAL_DEFAULT);

    curl = curl_easy_init();
    if (!curl)
        return 1;

    mcurl = curl_multi_init();
    if (!mcurl)
        return 2;

    /* This is the URL for your mailserver */
    curl_easy_setopt(curl, CURLOPT_URL, "smtp://localhost:5555");

    /* Note that this option is not strictly required, omitting it will result in
     * libcurl sending the MAIL FROM command with empty sender data. All
     * autoresponses should have an empty reverse-path, and should be directed
     * to the address in the reverse-path which triggered them. Otherwise, they
     * could cause an endless loop. See RFC 5321 Section 4.5.5 for more details.
     */
    curl_easy_setopt(curl, CURLOPT_MAIL_FROM, FROM_MAIL);

    /* Add two recipients, in this particular case they correspond to the
     * To: and Cc: addressees in the header, but they could be any kind of
     * recipient. */
    recipients = curl_slist_append(recipients, TO_MAIL);
    recipients = curl_slist_append(recipients, CC_MAIL);
    curl_easy_setopt(curl, CURLOPT_MAIL_RCPT, recipients);

    /* We are using a callback function to specify the payload (the headers and
     * body of the message). You could just use the CURLOPT_READDATA option to
     * specify a FILE pointer to read from. */
    curl_easy_setopt(curl, CURLOPT_READFUNCTION, payload_source);
    curl_easy_setopt(curl, CURLOPT_READDATA, &upload_ctx);
    curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);

    /* Tell the multi stack about our easy handle */
    curl_multi_add_handle(mcurl, curl);

    do {
        auto t_start = std::chrono::high_resolution_clock::now();
        CURLMcode mc = curl_multi_perform(mcurl, &still_running);
        auto t_end = std::chrono::high_resolution_clock::now();
        double elapsed_time_ms = std::chrono::duration<double, std::milli>(t_end - t_start).count();
        std::cout << std::setprecision(3) << std::fixed
            << "curl_multi_perform took " << elapsed_time_ms / 1000 << " seconds." << std::endl;

        if (still_running) {
            /* wait for activity, timeout or "nothing" */
            mc = curl_multi_poll(mcurl, NULL, 0, 1000, NULL);
        }

        if (mc)
            break;
    } while (still_running);

    std::cout << "Done." << std::endl;

    /* Free the list of recipients */
    curl_slist_free_all(recipients);

    /* Always cleanup */
    curl_multi_remove_handle(mcurl, curl);
    curl_multi_cleanup(mcurl);
    curl_easy_cleanup(curl);
    curl_global_cleanup();

    return 0;
}
```

Slow SMTP server mock:
```python
import socket
from threading import Event, Thread
import time


class MockSmtpServer:
    def __init__(self) -> None:
        self._acceptor = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._acceptor.bind(('', 5555))
        self._acceptor.listen(0)
        _, self.port = self._acceptor.getsockname()
        print(f"listening to localhost:{self.port}")

        self._stop = Event()
        self.thread = Thread(target=self.accept)
        self.thread.start()
        self.received = []
        self.received_counter = 0

    def accept(self):
        self._acceptor.settimeout(0.1)
        try:
            while not self._stop.is_set():
                try:
                    conn, _ = self._acceptor.accept()
                    conn.settimeout(0.1)
                    conn.sendall(
                        b'220 mse_test Simple Mail Transfer Service Ready\r\n')
                    received_data = False

                    while not self._stop.is_set():
                        try:
                            msg = conn.recv(4096)
                            print(msg)

                            self.received.append(msg)
                            if received_data:
                                # received email body
                                self.received_counter += 1
                                received_data = False

                            if msg.startswith(b'DATA'):
                                received_data = True
                                conn.sendall(
                                    b'354 Start mail input; end with <CRLF>.<CRLF>\r\n')

                                # Sleep before read and response to POST DATA.
                                time.sleep(5)
                            else:
                                conn.sendall(b'250 OK\r\n')
                        except socket.timeout:
                            pass
                        except socket.error:
                            break
                except socket.timeout:
                    pass
        finally:
            self._acceptor.close()

    def stop(self):
        self._stop.set()
        self.thread.join()


mock = MockSmtpServer()

```
Output:
```
curl_multi_perform took 0.005 seconds.
curl_multi_perform took 0.000 seconds.
curl_multi_perform took 0.000 seconds.
curl_multi_perform took 0.000 seconds.
curl_multi_perform took 0.000 seconds.
curl_multi_perform took 0.000 seconds.
curl_multi_perform took 5.013 seconds.
Done.
```

### I expected the following
I expected that the curl_multi_perform does not block so that when one of the remote SMTP sever is non-responsive, it does not affect other requests on the same curl multi.

### curl/libcurl version
libcurl 7.81.0

### operating system
Windows 10

**Comment by bagder** [comment]
It is a known issue, and is actually mentioned in the [TODO](https://curl.se/docs/todo.html#More_non_blocking) already. It is the "done" action for several protocols that is blocking. I don't know of anyone working on solving the problem so there's no fix in sight.

**Comment by worawatt** [comment]
Thank you so much for your quick response.

**Comment by bagder** [comment]
Since this is already mentioned in the TODO as a known problem, I'm closing this issue.

**Comment by madgbec** [comment]
> TBH, I am not sure if this is a bug or not because the function that blocks is actually called `smtp_block_statemach`
> 
> 
> 
> ### I did this
> 
> I am using curl multi perform to send emails over SMTP and I observed that if the SMTP server is non-responsive, the curl_multi_perform will block.
> 
> The same behavior also happens on the example: https://github.com/curl/curl/blob/master/docs/examples/smtp-multi.c
> 
> I just modified the example to print the time spent by curl_multi_perform:
> 
> ```c++
> 
> #include <string.h>
> 
> #include <curl/curl.h>
> 
> #include <chrono>
> 
> #include <iostream>
> 
> #include <iomanip>
> 
> 
> 
>   /* This is an example showing how to send mail using libcurl's SMTP
> 
>    * capabilities. It builds on the smtp-mail.c example to demonstrate how to use
> 
>    * libcurl's multi interface.
> 
>    */
> 
> 
> 
> #define FROM_MAIL     "<sender@example.com>"
> 
> #define TO_MAIL       "<recipient@example.com>"
> 
> #define CC_MAIL       "<info@example.com>"
> 
> 
> 
> static const char* payload_text =
> 
> "Date: Mon, 29 Nov 2010 21:54:29 +1100\r\n"
> 
> "To: " TO_MAIL "\r\n"
> 
> "From: " FROM_MAIL "\r\n"
> 
> "Cc: " CC_MAIL "\r\n"
> 
> "Message-ID: <dcd7cb36-11db-487a-9f3a-e652a9458efd@"
> 
> "rfcpedant.example.org>\r\n"
> 
> "Subject: SMTP example message\r\n"
> 
> "\r\n" /* empty line to divide headers from body, see RFC5322 */
> 
> "The body of the message starts here.\r\n"
> 
> "\r\n"
> 
> "It could be a lot of lines, could be MIME encoded, whatever.\r\n"
> 
> "Check RFC5322.\r\n";
> 
> 
> 
> struct upload_status {
> 
>     size_t bytes_read;
> 
> };
> 
> 
> 
> static size_t payload_source(char* ptr, size_t size, size_t nmemb, void* userp)
> 
> {
> 
>     struct upload_status* upload_ctx = (struct upload_status*)userp;
> 
>     const char* data;
> 
>     size_t room = size * nmemb;
> 
> 
> 
>     if ((size == 0) || (nmemb == 0) || ((size * nmemb) < 1)) {
> 
>         return 0;
> 
>     }
> 
> 
> 
>     data = &payload_text[upload_ctx->bytes_read];
> 
> 
> 
>     if (data) {
> 
>         size_t len = strlen(data);
> 
>         if (room < len)
> 
>             len = room;
> 
>         memcpy(ptr, data, len);
> 
>         upload_ctx->bytes_read += len;
> 
> 
> 
>         return len;
> 
>     }
> 
> 
> 
>     return 0;
> 
> }
> 
> 
> 
> int main(void)
> 
> {
> 
>     CURL* curl;
> 
>     CURLM* mcurl;
> 
>     int still_running = 1;
> 
>     struct curl_slist* recipients = NULL;
> 
>     struct upload_status upload_ctx = { 0 };
> 
> 
> 
>     curl_global_init(CURL_GLOBAL_DEFAULT);
> 
> 
> 
>     curl = curl_easy_init();
> 
>     if (!curl)
> 
>         return 1;
> 
> 
> 
>     mcurl = curl_multi_init();
> 
>     if (!mcurl)
> 
>         return 2;
> 
> 
> 
>     /* This is the URL for your mailserver */
> 
>     curl_easy_setopt(curl, CURLOPT_URL, "smtp://localhost:5555");
> 
> 
> 
>     /* Note that this option is not strictly required, omitting it will result in
> 
>      * libcurl sending the MAIL FROM command with empty sender data. All
> 
>      * autoresponses should have an empty reverse-path, and should be directed
> 
>      * to the address in the reverse-path which triggered them. Otherwise, they
> 
>      * could cause an endless loop. See RFC 5321 Section 4.5.5 for more details.
> 
>      */
> 
>     curl_easy_setopt(curl, CURLOPT_MAIL_FROM, FROM_MAIL);
> 
> 
> 
>     /* Add two recipients, in this particular case they correspond to the
> 
>      * To: and Cc: addressees in the header, but they could be any kind of
> 
>      * recipient. */
> 
>     recipients = curl_slist_append(recipients, TO_MAIL);
> 
>     recipients = curl_slist_append(recipients, CC_MAIL);
> 
>     curl_easy_setopt(curl, CURLOPT_MAIL_RCPT, recipients);
> 
> 
> 
>     /* We are using a callback function to specify the payload (the headers and
> 
>      * body of the message). You could just use the CURLOPT_READDATA option to
> 
>      * specify a FILE pointer to read from. */
> 
>     curl_easy_setopt(curl, CURLOPT_READFUNCTION, payload_source);
> 
>     curl_easy_setopt(curl, CURLOPT_READDATA, &upload_ctx);
> 
>     curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
> 
> 
> 
>     /* Tell the multi stack about our easy handle */
> 
>     curl_multi_add_handle(mcurl, curl);
> 
> 
> 
>     do {
> 
>         auto t_start = std::chrono::high_resolution_clock::now();
> 
>         CURLMcode mc = curl_multi_perform(mcurl, &still_running);
> 
>         auto t_end = std::chrono::high_resolution_clock::now();
> 
>         double elapsed_time_ms = std::chrono::duration<double, std::milli>(t_end - t_start).count();
> 
>         std::cout << std::setprecision(3) << std::fixed
> 
>             << "curl_multi_perform took " << elapsed_time_ms / 1000 << " seconds." << std::endl;
> 
> 
> 
>         if (still_running) {
> 
>             /* wait for activity, timeout or "nothing" */
> 
>             mc = curl_multi_poll(mcurl, NULL, 0, 1000, NULL);
> 
>         }
> 
> 
> 
>         if (mc)
> 
>             break;
> 
>     } while (still_running);
> 
> 
> 
>     std::cout << "Done." << std::endl;
> 
> 
> 
>     /* Free the list of recipients */
> 
>     curl_slist_free_all(recipients);
> 
> 
> 
>     /* Always cleanup */
> 
>     curl_multi_remove_handle(mcurl, curl);
> 
>     curl_multi_cleanup(mcurl);
> 
>     curl_easy_cleanup(curl);
> 
>     curl_global_cleanup();
> 
> 
> 
>     return 0;
> 
> }
> 
> ```
> 
> 
> 
> Slow SMTP server mock:
> 
> ```python
> 
> import socket
> 
> from threading import Event, Thread
> 
> import time
> 
> 
> 
> 
> 
> class MockSmtpServer:
> 
>     def __init__(self) -> None:
> 
>         self._acceptor = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> 
>         self._acceptor.bind(('', 5555))
> 
>         self._acceptor.listen(0)
> 
>         _, self.port = self._acceptor.getsockname()
> 
>         print(f"listening to localhost:{self.port}")
> 
> 
> 
>         self._stop = Event()
> 
>         self.thread = Thread(target=self.accept)
> 
>         self.thread.start()
> 
>         self.received = []
> 
>         self.received_counter = 0
> 
> 
> 
>     def accept(self):
> 
>         self._acceptor.settimeout(0.1)
> 
>         try:
> 
>             while not self._stop.is_set():
> 
>                 try:
> 
>                     conn, _ = self._acceptor.accept()
> 
>                     conn.settimeout(0.1)
> 
>                     conn.sendall(
> 
>                         b'220 mse_test Simple Mail Transfer Service Ready\r\n')
> 
>                     received_data = False
> 
> 
> 
>                     while not self._stop.is_set():
> 
>                         try:
> 
>                             msg = conn.recv(4096)
> 
>                             print(msg)
> 
> 
> 
>                             self.received.append(msg)
> 
>                             if received_data:
> 
>                                 # received email body
> 
>                                 self.received_counter += 1
> 
>                                 received_data = False
> 
> 
> 
>                             if msg.startswith(b'DATA'):
> 
>                                 received_data = True
> 
>                                 conn.sendall(
> 
>                                     b'354 Start mail input; end with <CRLF>.<CRLF>\r\n')
> 
> 
> 
>                                 # Sleep before read and response to POST DATA.
> 
>                                 time.sleep(5)
> 
>                             else:
> 
>                                 conn.sendall(b'250 OK\r\n')
> 
>                         except socket.timeout:
> 
>                             pass
> 
>                         except socket.error:
> 
>                             break
> 
>                 except socket.timeout:
> 
>                     pass
> 
>         finally:
> 
>             self._acceptor.close()
> 
> 
> 
>     def stop(self):
> 
>         self._stop.set()
> 
>         self.thread.join()
> 
> 
> 
> 
> 
> mock = MockSmtpServer()
> 
> 
> 
> ```
> 
> Output:
> 
> ```
> 
> curl_multi_perform took 0.005 seconds.
> 
> curl_multi_perform took 0.000 seconds.
> 
> curl_multi_perform took 0.000 seconds.
> 
> curl_multi_perform took 0.000 seconds.
> 
> curl_multi_perform took 0.000 seconds.
> 
> curl_multi_perform took 0.000 seconds.
> 
> curl_multi_perform took 5.013 seconds.
> 
> Done.
> 
> ```
> 
> 
> 
> ### I expected the following
> 
> I expected that the curl_multi_perform does not block so that when one of the remote SMTP sever is non-responsive, it does not affect other requests on the same curl multi.
> 
> 
> 
> 
> 
> ### curl/libcurl version
> 
> libcurl 7.81.0
> 
> 
> 
> ### operating system
> 
> Windows 10
