### ISSUE TITLE
SSL_read won't return after disconnect network during downloading a big file on ios

### ISSUE THREAD

**Issue by TXTT2016** [curl/curl#8564]
### I did this

I have found just on IOS platform, SSL_read function won't return until 10mins timeout when you are downloading a big file. But it will return quickly on windows and androids.

### I expected the following

Is it possible that all platforms have the same behavior？

### curl/libcurl version

7.80.0

[curl -V output]

**Comment by dfandrich** [comment]
Is this the issue you're seeing? 
https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro

**Comment by TXTT2016** [comment]
> Is this the issue you're seeing? https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro

Thank you for reply !

I did not use the --speed-limit、--speed-time or --max-time, but set the keepalive-time.

just like this for all connections:

```
    /* enable TCP keep-alive for this transfer */
    VOID_CURL_METHOD(curl_easy_setopt, m_curlHandle.get(), CURLOPT_TCP_KEEPALIVE, 1L);
    /* keep-alive idle time to 60 seconds */
    VOID_CURL_METHOD(curl_easy_setopt, m_curlHandle.get(), CURLOPT_TCP_KEEPIDLE, 60L);
    /* interval time between keep-alive probes: 60 seconds */
    VOID_CURL_METHOD(curl_easy_setopt, m_curlHandle.get(), CURLOPT_TCP_KEEPINTVL, 60L);
```

Maybe Unplugging a cable is not an error situation exactly, Is this just a platform differences for the download connection ?

**Comment by bagder** [comment]
That sounds like a problem with the underlying TCP and TLS stacks rather than actual curl code. 

Maybe 10 minutes is too short to detect it if the number of probes is 9, which seems to be default on some systems?

 TCP_KEEPCNT: The number of unanswered probes required to force closure of the socket

**Comment by jay** [comment]
SSL_read the way we use it is supposed to be nonblocking so I'm not sure how this is a curl problem

**Comment by TXTT2016** [comment]
> That sounds like a problem with the underlying TCP and TLS stacks rather than actual curl code.
> 
> Maybe 10 minutes is too short to detect it if the number of probes is 9, which seems to be default on some systems?
> 
> TCP_KEEPCNT: The number of unanswered probes required to force closure of the socket

Thanks for reply !

It seems you are right, maybe this is just a platform differences with the underlying TCP and TLS stacks.

If i want to make them have the same behavior in this situation, is there a way to do this by using curl interface ? 

Maybe --speed-limit or --speed-time option for the connection ?

**Comment by bagder** [comment]
> Maybe --speed-limit or --speed-time option for the connection ?

That should at least make it possible for you to detect the situation and terminate it earlier.

**Comment by dfandrich** [comment]
FWIW, I've created PR#8570 to document that it takes several probes for a
broken connection to be detected.
