### ISSUE TITLE
unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)

### ISSUE THREAD

**Issue by yupwei68** [curl/curl#8571]
```
* Connected to proxy.int.internal.ea.com (###) port 80 (#0)
* Establish HTTP proxy tunnel to ###:443
> CONNECT ###:443 HTTP/1.1
> Host: ###:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)
* NSS error -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)
* Unknown PKCS #11 error.
* Closing connection 0
curl: (58) unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)

```
### I did this
``curl -X POST -x proxy.int.internal.ea.com:80 --cert ./###.p12:### -kv  https://###``

curl with proxy and certificate

### I expected the following
connection success

### curl/libcurl version

[curl -V output]
curl 7.29.0
### operating system

Linux 3.10.0-1160.42.2.el7.x86_64

**Comment by bagder** [comment]
Your curl version is over nine years old. Your NSS version probably as well (even though you didn't show that). We have fixed **thousands** of bugs since then.

Unless you can provide a way for us to reproduce this problem with a modern curl version, I'm afraid you're left to debug this yourself.

**Comment by jay** [comment]
No response, closing.
