### ISSUE TITLE
scp downloads larger than 2GB may be truncated in Windows

### ISSUE THREAD

**Issue by jay** [curl/curl#858]
It was [reported](https://github.com/curl/curl/pull/451#issuecomment-222376460) that libcurl/7.49.0 libssh2/1.7.0 may truncate scp downloads in Windows. I can't reproduce in my builds, however I could in Viktor Szakats' build:
~~~
curl 7.49.0 (x86_64-pc-win32) libcurl/7.49.0 OpenSSL/1.0.2h zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.10.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2
~~~
Viktor has run [several checks](https://github.com/curl/curl/pull/451#issuecomment-222961430), all of which appear to have the expected results.

**Comment by jay** [comment]
I made an x64 build (84a48e5 2016-06-05) but I can't reproduce there either.
~~~
curl 7.50.0-DEV (x86_64-w64-mingw32) libcurl/7.50.0-DEV mbedTLS/2.2.1 zlib/1.2.8 libidn/1.32 libssh2/1.7.0 nghttp2/1.11.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz HTTP2
~~~

**Comment by vszakats** [comment]
I could also reproduce it locally using Bitwise SSH Server 6.47 with both:
```
curl 7.49.1 (i386-pc-win32) libcurl/7.49.1 OpenSSL/1.0.2h zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.11.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp.
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2.
```
and
```
curl 7.49.1 (x86_64-pc-win32) libcurl/7.49.1 OpenSSL/1.0.2h zlib/1.2.8 WinIDN libssh2/1.7.0 nghttp2/1.11.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp.
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2.
```

Command-line:
`curl -k -v -u <creds> scp://localhost/<paths>/large.iso -o test.bin --trace test.txt`

By _reproducing_, I mean to see `2047M` instead of the real size as the `Total` value.

**Comment by bagder** [comment]
So could it possibly be a server-side problem?

**Comment by jay** [comment]
I doubt it. I'm using the same server and I can't reproduce. There's probably some difference in how libcurl is built that's causing this, we just don't know what it is.

**Comment by vszakats** [comment]
Having reviewed my build settings, there don't seem to be anything peculiar that's a suspect (speaking of both [libssh2](https://github.com/vszakats/harbour-deps/blob/master/libssh2.sh) and [curl](https://github.com/vszakats/harbour-deps/blob/master/curl.sh)). Of course as their author, I'm possibly the worst reviewer here. I'm using `makefile.m32`, what may be out the mainstream though. No local patches either.

**Comment by jay** [comment]
The problem is likely in the libssh2 build. I built curl using mingw32-make and the msys2 libssh2 and it worked fine. Then I relinked the same curl tool object files to your libssh2.a and I could reproduce.

**Comment by jay** [comment]
The changes that added large file support to libssh2 are at libssh2/libssh2@6c84a42 and in 1.7.0 I can see it's supposed to enable large file support for mingw32...
https://github.com/libssh2/libssh2/blob/libssh2-1.7.0/include/libssh2.h#L160-L162
Interested what happens there when you build.

**Comment by vszakats** [comment]
Thanks @jay, it was indeed libssh2 build related. `HAVE_STRTOI64` needs to be manually enabled when using `makefile.m32`. Fix: https://github.com/vszakats/harbour-deps/commit/204b0b033d5501e5f02866bf55f7c16f33d6248b. New curl binaries &mdash; replacing the current ones &mdash; will be uploaded shortly.

**Comment by bagder** [comment]
Closing this as it wasn't actually curl bug!
