### ISSUE TITLE
curl sftp blocking

### ISSUE THREAD

**Issue by just-for-meal** [curl/curl#8583]
When the SFTP server's network port is intact, I establish the connection and use curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "LIST") to fetch the directory without releasing it and saving CURL* with map, since frequent init and cleanup are time consuming. When the connection is established, use "ifdown em1" to close the network port of the SFTP server. If cleanup is performed, it will block for 930 seconds, if not, it will block for 60 seconds, regardless of the timeout setting.

VERBOSE：
* Re-using existing connection! (#0) with host 192.168.8.31
* Connected to 192.168.8.31 (192.168.8.31) port 22 (#0)
* Could not open directory for reading: Unknown error in libssh2
* Connection #0 to host 192.168.8.31 left intact
* Error in the SSH layer
curl_easy_perform(79) failed: Error in the SSH layer

**Comment by bagder** [comment]
`CURLOPT_CUSTOMREQUEST` has no purpose for SFTP in libcurl. Instead it will treat URLs with a trailing slash as a directory and show the contents of that.

You haven't showed us your curl and libssh2 versions or mentioned what platform this runs on.

**Comment by just-for-meal** [comment]
client ：libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0；CentOS Linux release 7.6.1810 (Core)
server：CentOS release 6.5 (Final)

**Comment by bagder** [comment]
> 7.29.0

I believe modern libcurl versions behave better. You're using a libcurl that is more than **nine** years old.

**Comment by just-for-meal** [comment]
That's right！thans a lot!
Using: libcurl/7.82.0 OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.7 zstd/1.5.1 libssh2/1.8.0 nghttp2/1.33.0 libgsasl/1.8.0

sftp server ifdown em1 shut down the network port, the set timeout takes effect.
