### ISSUE TITLE
SSH keys not read from ~/.ssh/id_ecdsa, id_ed25519 etc.

### ISSUE THREAD

**Issue by CyberShadow** [curl/curl#8586]
The [documentation for the `--key` option](https://curl.se/docs/manpage.html#--key) has the following:

> For SSH, if not specified, curl tries the following candidates in order: `~/.ssh/id_rsa`, `~/.ssh/id_dsa`, `./id_rsa`, `./id_dsa`. 

Now that libssh2 supports newer key types, and especially now that the key types above (RSA and DSA) are deprecated by default in OpenSSH, I think it would be nice to expand the list above to the default key locations for the newer key types supported by libssh2.

Something that may warrant discussion is the backwards-compatibility aspect. Should we prepend the new key types to the list, because we should prefer newer/stronger algorithms? That could be a breaking change when the user already has a file with the new key type, but the remote host doesn't have it in their `authorized_keys`. Or should we append them, flipping the compromise? If libssh2 supports this, we could read and try *all* keys (which is also what the OpenSSH client does) instead of just the first readable file as a prerequisite to changing this list.

### I did this

```console
$ ssh-keygen -t ed25519
$ ssh-copy-id user@host
$ curl sftp://user@host/
```

### I expected the following

Should use the ed25519 key file from the default location.

### curl/libcurl version

```
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

Linux t580.thecybershadow.net 5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux

**Comment by bagder** [comment]
It would be nice to have this supported. But as this is more of a feature-request/enhancement and nobody seems to work on this, we are adding this proposal to the TODO document and will close this issue. Feel free to work on this to make it happen as we would love to support this!

**Comment by CyberShadow** [comment]
Hi Daniel,

Happy to work on this (code changes should be trivial) but I think it needs an executive decision about how to answer the backwards compatibility question :)

**Comment by bagder** [comment]
@CyberShadow I'm not sure I understand the options/choice we need to make. Can we do a fall-back to the older way if we fail in a "modern" take?

**Comment by CyberShadow** [comment]
Here are the options as far as I can tell:
1. Try the first key we find, looking for keys with older algorithms first. Pro: backwards compatibility, con: if a key with newer algorithm is available, we are preferring one with an older/weaker algorithm.
2. Try the first key we find, looking for keys with newer algorithms first. Pro: we prefer the newer/stronger algorithms, con: if the user has a key with this newer algorithm but it's not configured as an accepted key on the remote host then after updating cURL, login will now fail.
3. Load all keys we can find and try to log in with all of them, strongest to weakest. Pro: both of the above, con: might require refactoring, further discussion due to cURL trying multiple keys whereas currently there is no way to specify more than one key via an option; some firewalls (fail2ban) might not like remote hosts trying to unsuccessfully log in with several keys in a short time window.
