### ISSUE TITLE
CURLOPT_PROTOCOLS invisible to the preprocessor when compiling against curl.h

### ISSUE THREAD

**Issue by julik** [curl/curl#859]
### I did this

Used the following ifdef guard when building against libCURL:

   #ifdef CURLOPT_PROTOCOLS
     curl_easy_setopt(curl, CURLOPT_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS);
   #endif

The code within the `#ifdef` got stripped because apparently CURLOPT_PROTOCOLS is not visible to the preprocessor (CURLPROTO_HTTP is though).

### I expected the following

On my machine, I expected the ifdef to work (the option is available), and the requisite code within
the guard to be compiled.

What am I doing wrong? Should I check for the availability of the option using some other means in the API?

### curl/libcurl version

libcurl/7.43.0 SecureTransport zlib/1.2.

### operating system

OSX / Darwin 15.4.0

**Comment by jay** [comment]
Not a bug. CURLOPTs are part of the enumerated type `CURLoption` so you can't do it that way. `CURLOPT_PROTOCOLS` has been around about 6 or 7 years so unless you are using an ancient version of libcurl it should be available. Generally speaking though you can check the return code of `curl_easy_setopt` to see if the option was recognized or not.

**Comment by bagder** [comment]
Also, we provide the [symbols-in-versions](https://curl.haxx.se/libcurl/c/symbols-in-versions.html) file for exactly that reason...

**Comment by julik** [comment]
Understood, thanks!
