### ISSUE TITLE
Compiling Static Library results in a fake static library.

### ISSUE THREAD

**Issue by PiotrKFtw** [curl/curl#8591]
I'm compiling static library of curl for Windows Visual C++ 2017 using nmake x64.
`nmake /f Makefile vc-x64 mode=static VC=17 RTLIBCFG=static DEBUG=no ENABLE_WINSSL=yes MACHINE=x64`

I expected to get a static library that doesn't require any dynamic link libraries, however, after importing the static library in my project, I was presented with libcurl.dll missing error.
~~~
#pragma comment(lib, "libcurl_a.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "Normaliz.lib")
#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Wldap32.lib")
#define CURL_STATICLIB
#include <curl/curl.h>
#include <curl/easy.h>
~~~
![image](https://user-images.githubusercontent.com/33489788/158076292-4e6ea143-e379-4ad3-90bc-2a2d118d796e.png)

Operating System: Windows 10 20H2

**Comment by jay** [comment]
I've tried to clarify the readme on this issue, can you take a look at the [proposed example](https://github.com/curl/curl/blob/7f259cb19e8d8b4796b84379948af3c2921f1106/winbuild/README.md#building-your-own-application-with-libcurl-visual-studio-example) and tell me if you are doing anything different?

> nmake /f Makefile vc-x64 mode=static VC=17 RTLIBCFG=static DEBUG=no ENABLE_WINSSL=yes MACHINE=x64

That is not a valid build command, vc-x64 does not exist. I assume you mean Makefile.vc. What is the actual command you used? Did you follow the RTLIBCFG warning in the README that says delete old builds?

**Comment by PiotrKFtw** [comment]
> I've tried to clarify the readme on this issue, can you take a look at the [proposed example](https://github.com/curl/curl/blob/7f259cb19e8d8b4796b84379948af3c2921f1106/winbuild/README.md#building-your-own-application-with-libcurl-visual-studio-example) and tell me if you are doing anything different?
> 
> > nmake /f Makefile vc-x64 mode=static VC=17 RTLIBCFG=static DEBUG=no ENABLE_WINSSL=yes MACHINE=x64
> 
> That is not a valid build command, vc-x64 does not exist. I assume you mean Makefile.vc. What is the actual command you used? Did you follow the RTLIBCFG warning in the README that says delete old builds?

Visual Studio created that file in root repository director and it simply links to Makefile.vc. Yes I did follow the RTLIBCFG Warning in readme.
Translating Visual Studio file results in :
`nmake /f Makefile.vc mode=static VC=17 RTLIBCFG=static DEBUG=no ENABLE_WINSSL=yes MACHINE=x64`

**Comment by jay** [comment]
Ok. I assume you have an output directory like ..\builds\libcurl-vc17-x64-release-static-ipv6-sspi-schannel. After building libcurl are you able to build the simple.c example?

~~~
nmake /f Makefile.vc mode=static VC=17 RTLIBCFG=static DEBUG=no ENABLE_WINSSL=yes MACHINE=x64
cl /MT /DCURL_STATICLIB /I..\builds\libcurl-vc17-x64-release-static-ipv6-sspi-schannel\include ..\docs\examples\simple.c /link /LIBPATH:..\builds\libcurl-vc17-x64-release-static-ipv6-sspi-schannel\lib libcurl_a.lib advapi32.lib crypt32.lib normaliz.lib ws2_32.lib wldap32.lib
simple.exe
~~~

Also please note these two things (neither of which explain what's going on):

- ENABLE_WINSSL was renamed to ENABLE_SCHANNEL in curl 7.72.0.
- Visual Studio 2022 (aka Visual Studio 17.0) uses VC14.3 not VC17.

**Comment by bagder** [comment]
Is there anything (left) to act on in this issue?

**Comment by jay** [comment]
> Is there anything (left) to act on in this issue?

Waiting on the reporter. It's been more than two months so I'm going to close.
