### ISSUE TITLE
SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

### ISSUE THREAD

**Issue by sjadhavar** [curl/curl#8598]
Seeing issue "SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway." after #7892 

libcurl (with the OpenSSL backend) performs server certificate verification even if verifypeer == 0 and the verification result is available using CURLINFO_SSL_VERIFYRESULT. 
The application code assumes that libcurl (with the OpenSSL backend) will perform the server certificate verification even if verifypeer == 0 and that the verification result will be available using CURLINFO_SSL_VERIFYRESULT.

The [commit ](https://github.com/curl/curl/pull/7892/commits/e6ac5b27de7a484d21f6a54e7fb6bf8f76408ef0) caused the CURLINFO_SSL_VERIFYRESULT to not have useful information for the verifypeer == 0 use case (it would always have X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY).

Below is the code snippet.

    lerr = SSL_get_verify_result(backend->handle);
    SSL_SET_OPTION_LVALUE(certverifyresult) = lerr;
    if(lerr != X509_V_OK) {
      if(SSL_CONN_CONFIG(verifypeer)) {
        /* We probably never reach this, because SSL_connect() will fail
           and we return earlier if verifypeer is set? */
        if(strict)
          failf(data, "SSL certificate verify result: %s (%ld)",
                X509_verify_cert_error_string(lerr), lerr);
        result = CURLE_PEER_FAILED_VERIFICATION;
      }
      else
        infof(data, " SSL certificate verify result: %s (%ld),"
              " continuing anyway.",
              X509_verify_cert_error_string(lerr), lerr);
    }
    else
      infof(data, " SSL certificate verify ok.");

**Comment by sjadhavar** [comment]
This issue was also reported earlier for PR #2290
See comment https://github.com/curl/curl/pull/2290#issuecomment-378230863

Code had been reverted to fix the issue.

**Comment by bagder** [comment]
> The application code assumes that libcurl (with the OpenSSL backend) will perform the server certificate verification even if verifypeer == 0 and that the verification result will be available using `CURLINFO_SSL_VERIFYRESULT`.

That's an assumption that doesn't seem to be based on what is documented:

The [CURLINFO_SSL_VERIFYRESULT](https://curl.se/libcurl/c/CURLINFO_SSL_VERIFYRESULT.html) man page says:

> Pass a pointer to a long to receive the result of the server SSL certificate verification that was requested (using the [CURLOPT_SSL_VERIFYPEER](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html) option).

**Comment by sjadhavar** [comment]
Yes... we do pass `pointer to long` in our application to get the verification result after curl operation.

`curl_easy_getinfo(curl, CURLINFO_SSL_VERIFYRESULT, &result)`

And we are getting `20`.

**Comment by bagder** [comment]
You need to help me here and explain to me why your application didn't just happen to work by a random fluke. Your app does not seem to have followed what is documented and now when we changed behavior and libcurl **still works as documented** your app doesn't work anymore.

Why do you think it should verify the certificate when you specifically asked it not to? It seems rather peculiar to me.

**Comment by sjadhavar** [comment]
Please see the comment in lib/vtls/openssl.c

```
  /* OpenSSL always tries to verify the peer, this only says whether it should
   fail to connect if the verification fails, or if it should continue
    anyway. In the latter case the result of the verification is checked with
    SSL_get_verify_result() below. */
  SSL_CTX_set_verify(backend->ctx,
                     verifypeer ? SSL_VERIFY_PEER : SSL_VERIFY_NONE, NULL);
```
Based on this even if `verifypeer == 0` it will try to verify the peer and will not fail connection and continue anyway.

Our application checks the verify result by calling `curl_easy_getinfo(curl, CURLINFO_SSL_VERIFYRESULT, &result)`
and gets `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` i.e. 20

and libcurl outs below log
**"SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway."**

**Comment by bagder** [comment]
Thanks, you've now repeated basically the same thing several times without answering my question. I don't know what else I can do.

**Comment by sjadhavar** [comment]
Sorry If I have confused you.

> Why do you think it should verify the certificate when you specifically asked it not to? It seems rather peculiar to me.

Answer to above query is that even if `verifypeer == 0` then also libcurl with OpenSSL tries to verify the peer. And it is commented/documented in the code as well. See above https://github.com/curl/curl/issues/8598#issuecomment-1072438216.

Before changes made in PR https://github.com/curl/curl/pull/7892, curl was loading the CA certificate even if verifypeer was not requested and OpenSSL was able to verify the peer (server certificate verification).

After changes in PR https://github.com/curl/curl/pull/7892, libcurl is loading the CA certificate only if verifypeer is requested.
So now even if application has not requested to verifypeer, libcurl (with OpenSSL) always tries to verify the peer and it fails as CA certificate is not loaded. 

```
SSL_CTX_set_verify(backend->ctx,
                     verifypeer ? SSL_VERIFY_PEER : SSL_VERIFY_NONE, NULL);
```
If `verifypeer ==0`  then libcurl sets `SSL_VERIFY_NONE` as mode to `SSL_CTX_set_verify()` in API.

SSL_VERIFY_NONE means:
> Client mode: if not using an anonymous cipher (by default disabled), the server will send a certificate which will be checked. The result of the certificate verification process can be checked after the TLS/SSL handshake using the [SSL_get_verify_result(3)](https://www.openssl.org/docs/man1.0.2/man3/SSL_get_verify_result.html) function. **The handshake will be continued regardless of the verification result.**

See https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_verify.html

**So are you suggesting that application should NOT check for the `CURLINFO_SSL_VERIFYRESULT` if `verifypeer == 0` ?**

**Comment by bagder** [comment]
I haven't made up my mind what I think curl should do for this case. So far I've not been convinced that libcurl does anything wrong here.

I think the documentation for `CURLINFO_SSL_VERIFYRESULT` is clear. It says it will:

**receive the result of the server SSL certificate verification that was requested (using the CURLOPT_SSL_VERIFYPEER option)**

I maintain that this is what libcurl still does. Your application depends on undocumented behavior but you have not helped us by explaining why you need to do that. It would help us if you can explain why you need libcurl to act like this and why it helps the community that libcurl continues doing this.

**Comment by sjadhavar** [comment]
I agree that libcurl changes are as per documentation and it works as mentioned in doc.

Let me check if we can do anything from our application side to handle the case where application still checks the `CURLINFO_SSL_VERIFYRESULT` even if `verifypeer == 0`.

**Comment by bagder** [comment]
Since this is working as documented, I don't think we should consider it a bug. You just happened to get a lucky behavior previously that acted contrary to documentation.
