### ISSUE TITLE
build fails @ undef'd ref to deprecated/no-op'd `SSL_COMP_free_compression_methods'

### ISSUE THREAD

**Issue by pgnd** [curl/curl#860]
upgrading to latest git tag, 7_49_1

    git log | head
        commit cf93a7b364a70b56150cf6ea77492b799ec02a45
        Author: Daniel Stenberg <daniel@haxx.se>
        Date:   Fri May 27 16:58:43 2016 +0200

            RELEASE-NOTES: 7.49.1

        commit 6df916d751e72fc9a1febc07bb59c4ddd886c043
        Author: Steve Holme <steve_holme@hotmail.com>
        Date:   Sun May 29 22:57:40 2016 +0200

    git branch -a
        * curl-7_49_1
        ...

config/build as usual

    ./buildconf
    ./configure \
    --prefix=/usr/local \
    --enable-shared --disable-static \
    --libdir=/usr/local/lib64 \
    --with-ssl \
    --with-nghttp2 \
    --disable-sspi \
    --disable-ldap --disable-ldaps \
    --enable-threaded-resolver \
    --with-gnu-ld

fails at build

    make
        ...
        Making all in lib
        make[1]: Entering directory '/usr/local/src/curl/lib'
        make  all-am
        make[2]: Entering directory '/usr/local/src/curl/lib'
        make[2]: Leaving directory '/usr/local/src/curl/lib'
        make[1]: Leaving directory '/usr/local/src/curl/lib'
        Making all in src
        make[1]: Entering directory '/usr/local/src/curl/src'
        make  all-am
        make[2]: Entering directory '/usr/local/src/curl/src'
          CCLD     curl
        ../lib/.libs/libcurl.so: undefined reference to `SSL_COMP_free_compression_methods'
        collect2: error: ld returned 1 exit status
        Makefile:782: recipe for target 'curl' failed
        make[2]: *** [curl] Error 1
        make[2]: Leaving directory '/usr/local/src/curl/src'
        Makefile:661: recipe for target 'all' failed
        make[1]: *** [all] Error 2
        make[1]: Leaving directory '/usr/local/src/curl/src'
        Makefile:893: recipe for target 'all-recursive' failed
        make: *** [all-recursive] Error 1

I'm linking against current release openssl,

    openssl version
        OpenSSL 1.0.2h  3 May 2016

As of April 4, 2016, 'SSL_COMP_free_compression_methods' has been deprecated

    Deprecate SSL_COMP_free_compression_methods() and make it a no-op
    https://github.com/openssl/openssl/commit/03b0e735556ed

In curl source

    grep -rlni SSL_COMP_free_compression_methods .
        ./lib/vtls/openssl.c

    cat ./lib/vtls/openssl.c
        ...
    751    #if OPENSSL_VERSION_NUMBER >= 0x10002003L && \
            OPENSSL_VERSION_NUMBER <= 0x10002FFFL
          SSL_COMP_free_compression_methods();
        #endif
        ...

my openssl source reports as

    grep OPENSSL_VERSION_NUMBER /usr/local/ssl/include/openssl-1.0.2h/crypto/opensslv.h
        # define OPENSSL_VERSION_NUMBER  0x1000208fL

and my build flags are

    echo $CPPFLAGS
        -I/usr/local/ssl/include -I/usr/local/include -I/usr/include -O3 -Wall -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=native -mtune=native -D_FORTIFY_SOURCE=2

    echo $LDFLAGS
        -L/usr/local/ssl/lib64 -Wl,-rpath,/usr/local/ssl/lib64 -L/usr/local/lib64 -Wl,-rpath,/usr/local/lib64

    echo $LIBS
        -lssl -lcrypto -lssh2

**Comment by jay** [comment]
Yeah it's been deprecated but we need it for 1.0.2. Try `nm /usr/local/ssl/lib64/libssl.so.1.0.0 | grep SSL_COMP_free_compression_methods` and if it finds the function then try `make V=1` and post the output when it links.

**Comment by bagder** [comment]
Also, commit c9b4e6e8 already corrected the use of that function based on the use of `OPENSSL_NO_COMP`

**Comment by jay** [comment]
Ah, didn't know that. That's probably it.

**Comment by bagder** [comment]
so @pgnd, does the problem remain in master or does that work for you?

**Comment by pgnd** [comment]
switching to head

    git log | head
        commit 1aa899ff38548a5d1c196f5c9ad7047f0fae3f5a
        Author: Jay Satiro <raysatiro@yahoo.com>
        Date:   Sun Jun 5 03:13:32 2016 -0400

            http: Fix HTTP/2 connection reuse
            
            - Change the parser to not require a minor version for HTTP/2.
            
            HTTP/2 connection reuse broke when we changed from HTTP/2.0 to HTTP/2
            in 8243a95 because the parser still expected a minor version.

config/build as before

    ./buildconf
    ./configure \
    ...
        ...
        configure: Added /usr/local/ssl/lib64 to LD_LIBRARY_PATH
        checking for OpenSSL headers version... 1.0.2 - 0x1000208fL
        checking for OpenSSL library version... 1.0.2
        checking for OpenSSL headers and library versions matching... yes
        checking for "/dev/urandom"... yes
        checking for SRP_Calc_client_key in -lcrypto... yes
        checking default CA cert bundle/path... /etc/ssl/certs/ (capath)
        checking whether to use builtin CA store of SSL library... no
        checking for library containing psl_builtin... -lpsl
        checking for libssh2_channel_open_ex in -lssh2... yes
        checking libssh2.h usability... yes
        checking libssh2.h presence... yes
        checking for libssh2.h... yes
        ...
        configure: Configured to build curl/libcurl:

          curl version:     7.50.0-DEV
          Host setup:       x86_64-suse-linux-gnu
          Install prefix:   /usr/local
          Compiler:         /usr/bin/gcc-6
          SSL support:      enabled (OpenSSL)
          SSH support:      enabled (libSSH2)
        ...

now, looks good at build

    make V=1
    make install
    which curl
        /usr/local/bin/curl

    curl -V
        curl 7.50.0-DEV (x86_64-suse-linux-gnu) libcurl/7.50.0-DEV OpenSSL/1.0.2h zlib/1.2.8 libidn/1.32 libpsl/0.13.0 (+libicu/52.1) libssh2/1.7.0_DEV nghttp2/1.12.0-DEV
        Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
        Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets PSL 

so, recent commit looks like it takes care of the problem.

possible to push a new release tag, or update current, so others can have a buildable _release_?

**Comment by jay** [comment]
How do you build OpenSSL? I don't build it with compression but I don't have OPENSSL_NO_COMP enabled in either Windows or Linux.

**Comment by pgnd** [comment]
@jay

currently, my ssl config recipe is

    ./config \
     --openssldir=/usr/local/ssl \
     --libdir=lib64 \
     -D_GNU_SOURCE \
     -DOPENSSL_NO_BUF_FREELISTS \
     -DOPENSSL_NO_HEARTBEAT \
     -DPURIFY \
     -DSSL_FORBID_ENULL \
     -DTERMIO \
     -Wa,--noexecstack \
     -Wl,-z,relro,-z,now \
     -Wall \
     -Wl,-rpath=/usr/local/ssl/lib64 \
     -fno-common \
    threads shared \
    no-comp no-zlib no-zlib-dynamic \
    enable-ec_nistp_64_gcc_128 \
    enable-rfc3779 \
    enable-ecdsa \
    no-idea \
    no-mdc2 \
    no-rc2 \
    no-rc5 \
    no-ssl2 \
    no-ssl3 \
    no-weak-ssl-ciphers

fwiw, it's been this^ for awhile, certainly across 1+ libcurl tag bumps

**Comment by bagder** [comment]
The function call this issue points out was added in commit 3caaeffbe8, which is only released in the 7.49.1 release and no earlier.

**Comment by jay** [comment]
It's the `no-comp`. Isn't compression disabled by default in OpenSSL? It looks like no-comp is to disable the compression functions at build time? Are a lot of people doing this? I don't see a reason for a patch release, we really haven't heard much about it. Not that your case isn't important it just doesn't seem to affect a lot of people.

**Comment by pgnd** [comment]
> ... lot of people ... 

depends.

'most' won't, because 'most' don't think/bother about their builds, and simply use whatever defaults distro pkg'ers use, and they often just use openssl defaults

here, it's not unheard of

    https://www.google.com/search?q=openssl+no-comp

here,

    https://wiki.openssl.org/index.php/Compilation_and_Installation

it's certianly offered as an option to

    Disables compression independent of zlib. OPENSSL_NO_COMP will be defined in the OpenSSL headers.

if you make the choice to NOT have multiple openssl compression methods lying around, and instead choose to use zlib, then ^^^ ...

and, 'tho just "I" am working on Sunday, on Monday, 100+ build instances get built/pushed across our env.

There's nothing at all unstable/beta/etc about 'no-comp' in ssl.

And I prefer a releases-must-build policy.

Of course, there's a fix, above.  If need by, I can simply mark libcurl as unstable here, and switch to master until whenever it a stable release has the fix.  Personally, I'd rather not, as it's just more thrash that later needs to be undone ...

'close' or 'update', at your discretion

**Comment by jay** [comment]
Thanks for your report. This issue isn't enough for a patch release. My suggestion is check out 7.49.1 on a new branch and then cherry pick the commit that fixes the issue.
~~~
git checkout -b curl-7_49_1-patched curl-7_49_1
git cherry-pick c9b4e6e
~~~
