### ISSUE TITLE
FTP prequotes ignored if URL is directory

### ISSUE THREAD

**Issue by anon00000000** [curl/curl#8602]
### I did this
```
$ curl -v ftp://anonymous@user/pub/ -Q '+DELE dummy'
*   Trying 192.9.210.201...
* TCP_NODELAY set
* Connected to user (192.9.210.201) port 21 (#0)
< 220 (vsFTPd 3.0.3)
> USER anonymous
< 230 Login successful.
> PWD
< 257 "/" is the current directory
* Entry path is '/'
> CWD pub
* ftp_perform ends with SECONDARY: 0
< 250 Directory successfully changed.
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||18251|)
*   Trying 192.9.210.201...
* TCP_NODELAY set
* Connecting to 192.9.210.201 (192.9.210.201) port 18251
* Connected to user (192.9.210.201) port 21 (#0)
> TYPE A
< 200 Switching to ASCII mode.
> LIST
< 150 Here comes the directory listing.
* Maxdownload = -1
-rw-rw-rw-    1 ftp      ftp          2367 Mar 17 10:12 dummy
* Remembering we are in dir "pub/"
< 226 Directory send OK.
* Connection #0 to host user left intact
```
### I expected the following
`DELE dummy` command sent after CWD.
### curl/libcurl version
Reproduced with the latest (7.82.0) static build from the download page.

### operating system
Ubuntu 18.04.6

`Linux ZBook-user 5.4.0-104-generic #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

A debug build of curl git did assure me the prequotes were ignored. Using postquotes work.

**Comment by jay** [comment]
I don't think it ever worked like that and I don't know why it doesn't... Try this: `ftp://anonymous@user/pub/dummy -Q '+DELE dummy'`

**Comment by anon00000000** [comment]
Hmmm, thanks, it works, but I indeed expected the original to work too.

**Comment by bagder** [comment]
It seems the state machine was just never done for doing "prequotes" for directory listings!

**Comment by bagder** [comment]
I'm not too eager to work on polishing the FTP state machine to make this work. At least not in the short term. I personally will prefer to document this as a known limitation for the prequote functionality.
