### ISSUE TITLE
[Windows] Reserved filenames issue

### ISSUE THREAD

**Issue by gvanem** [curl/curl#8608]
I have a problem in curl with reserved names like `AUX` or `LPT1` under Windows.

A simple `curl.exe --output aux.txt https://curl.se` takes a whopping 61 seconds to finish. 
And off-course no `aux.txt` gets created. The same issue with the `curl.exe` bundled with Windows-10.

A `curl.exe --output aux_.txt https://curl.se` finishes in approx. 0.4 seconds.

AFAIK, the function `rename_if_reserved_dos_device_name()` should check for such a name and rename the file if needed. 
It does not happen since the line in my `%CURL_MEMDEBUG` has:
`FILE tool_cb_wrt.c:84 fopen("aux.txt","wb") = 0x12decd0`

So I modified `lib/memdebug.c` to print delta-timestamps using `Curl_now()` and `Curl_timediff()`. 
The above line and the one following it are now:
```
 0,000 FILE tool_cb_wrt.c:84 fopen("aux.txt","wb") = 0x160db70
30,633 MEM multi.c:655 free(0x207e010)
 0,010 MEM multi.c:721 free(0x1628fa8)
 0,000 MEM url.c:2207 free(0x1642100)
 0,008 FILE tool_operate.c:591 fclose(0x160db70)
29,481 MEM asyn-thread.c:128 free(0x161bf78)
```

Meaning it takes 30,633 sec to create the file and 29,481 sec to close it!
It's sum of 61 sec is what I see.

**Comment by bagder** [comment]
Surely that wait is caused by Windows itself and not by anything curl itself does? Can we actually do anything about this?

**Comment by gvanem** [comment]
Something inside Windows for sure. But what is the purpose of `sanitize_file_name()` and 
`rename_if_reserved_dos_device_name()` then? Shouldn't a `--output file` be sanitized too?

**Comment by bagder** [comment]
Should it?

**Comment by jzakrzewski** [comment]
I don't think it's curl's job in this case.

**Comment by gvanem** [comment]
> I don't think it's curl's job in this case.

Well OK. Closing.
