### ISSUE TITLE
cURL multi transfers not terminating with HTTP2 + future time condition

### ISSUE THREAD

**Issue by foutrelis** [curl/curl#8626]
### I did this

Used [10-at-a-time.c.gz](https://github.com/curl/curl/files/8331404/10-at-a-time.c.gz) (modified curl example) to simulate part of what `pacman` from Arch Linux is doing (when parallel downloads are enabled).

I am seeing 100% CPU usage and `dload_progress_cb` being called repeatedly, with `curl_multi_perform` reporting a couple active transfers.

### I expected the following

All 10 downloads to succeed, which they do if I leave `CURLOPT_TIMECONDITION` unset.

Changing the time condition to be in the past (e.g. `time(NULL) - 604800`) also allows curl to complete all transfers.

### curl/libcurl version

```
$ curl -V
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
$ uname -a
Linux notbad 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux

$ pacman -Q curl libnghttp2 openssl
curl 7.82.0-1
libnghttp2 1.47.0-1
openssl 1.1.1.n-1
```

**Comment by bagder** [comment]
Thanks, I can reproduce the issue with the provided recipe.

**Comment by foutrelis** [comment]
Applying 9fd0270c0a7ae78642ddecb1d755c0cb25d95571 on top of `7.82.0` does NOT seem to fix the issue for me. I'll check with a local master build next.

**Comment by bagder** [comment]
Update: nah, I was mistaken. I had edits in the code that made it succeed. The problem is still there with #8662 present.
