### ISSUE TITLE
tests: HTTP tests often skipped since March 22

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#8627]
### I did this

Look at autobuilds (Windows/MSYS2, Linux, Solaris, and NetBSD) and master branch CI builds (Windows/MSYS2 and Ubuntu HTTPS-only)

### I expected the following

HTTP tests run. Instead, they were skipped (but not for all other configurations) with

```
RUN: Unknown server on our http port: XXXXX (4)
RUN: HTTP server failed verification
```

### curl/libcurl version

For Ubuntu HTTPS-only:

last good run:
https://github.com/curl/curl/commit/bdc664a64002a7df66f34159454844e6b6f5515f
https://dev.azure.com/daniel0244/curl/_build/results?buildId=9158&view=logs&jobId=17489ae2-179d-52f7-8dc0-532a62d9859e&j=17489ae2-179d-52f7-8dc0-532a62d9859e&t=19d67132-212d-5d5b-3a2f-a8d45e26e5be

first bad run:
https://github.com/curl/curl/commit/d79b1ead74377481de34ac543f2503b1b416e2f4
https://dev.azure.com/daniel0244/curl/_build/results?buildId=9160&view=logs&jobId=17489ae2-179d-52f7-8dc0-532a62d9859e&j=17489ae2-179d-52f7-8dc0-532a62d9859e&t=19d67132-212d-5d5b-3a2f-a8d45e26e5be

(with a lot of commits in between not tested by CI)

### operating system

Windows, Ubuntu Linux, NetBSD

**Comment by bagder** [comment]
Thanks. That makes it look like my headers API merge broke something. Investigating.

**Comment by bagder** [comment]
This reminds me that I need to come up with a system to detect when tests are erroneously silently just skipped, as it makes them not go red in the CI builds...
