### ISSUE TITLE
sftp blocking and infinite loop problem

### ISSUE THREAD

**Issue by jiexuelc** [curl/curl#8632]
### Discussed in https://github.com/curl/curl/discussions/8629

<div type='discussions-op-text'>

<sup>Originally posted by **jiexuelc** March 24, 2022</sup>
## Program running environment
The curl(7.66.0) is built with libssh (0.9.6) to support sftp protocol.

## Q1: curl get stuck when network disconnected
I see that in SSH_SFTP_INIT state, the ssh session working mode is set to blocking mode. If the network is suddenly disconnected during sftp transmission, curl will be stuck, even if curl is configured with a timeout. 
Is the sftp transport designed to work only in blocking mode? Is there a way to change the working mode to non-blocking in sftp transfer?
Below is the blocking log
The log when curl is blocking may be as follows:：
```
* STATE: INIT => CONNECT handle 0xe91e8; line 1491 (connection #-5000)
* Found bundle for host 10.17.115.43: 0xe8fe0 [serially]
* Re-using existing connection! (#0) with host 10.17.115.43
* Connected to 10.17.115.43 (10.17.115.43) port 22 (#0)
* STATE: CONNECT => DO handle 0xe91e8; line 1540 (connection #0)
* DO phase starts
* SSH 0xe3a20 state change from SSH_STOP to SSH_SFTP_QUOTE_INIT (line 2329)
* SSH 0xe3a20 state change from SSH_SFTP_QUOTE_INIT to SSH_SFTP_GETINFO (line 864)
* SSH 0xe3a20 state change from SSH_SFTP_GETINFO to SSH_SFTP_TRANS_INIT (line 1056)
* SSH 0xe3a20 state change from SSH_SFTP_TRANS_INIT to SSH_SFTP_UPLOAD_INIT (line 1076)
[2022/03/23 15:33:57.472285, 3] sftp_open:  Opening file /sftp/test/uv_test_7 with sftp flags 1a
[2022/03/23 15:33:57.472417, 3] ssh_packet_need_rekey:  packet: [data_rekey_needed=0, out_blocks=98353, in_blocks=131
[2022/03/23 15:33:57.472702, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
[2022/03/23 15:33:57.472805, 3] packet_send2:  packet: wrote [type=94, len=64, padding_size=9, comp=54, payload=54]
[2022/03/23 15:33:57.472911, 3] channel_write_common:  channel_write wrote 45 bytes
[2022/03/23 15:33:57.472995, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:07.483150, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:17.493366, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:27.503549, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:37.513723, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:47.523886, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:34:57.534059, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:07.544233, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:17.554410, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:27.564569, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:37.574720, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:47.584868, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:35:57.595021, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:07.605193, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:17.615353, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:27.625507, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:37.635683, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:47.645834, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:36:57.655991, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:37:07.666142, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:37:17.676291, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:37:27.686441, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
[2022/03/23 15:37:37.696587, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
```

## Q2: curl infinitely tries to create directory
When configuring CURLOPT_FTP_CREATE_MISSING_DIRS option for curl, the directory will be created automatically if it does not exist. However, if the server is disconnected frequently, it may lead to infinite creation of directories. The reason is that when libssh fails to write data to the server, the error code is set to SSH_FX_FAILURE. 
Is it possible to remove this error code in the error judgment condition? Or can we add a limit on the number of failures?
The log when there is infinite creation of directories may be as follows：
```
* STATE: INIT => CONNECT handle 0x74f4bd88; line 1491 (connection #-5000)
* Found bundle for host 10.17.115.43: 0x2468ae0 [serially]
* Re-using existing connection! (#104) with host 10.17.115.43
* Connected to 10.17.115.43 (10.17.115.43) port 22 (#104)
* STATE: CONNECT => DO handle 0x74f4bd88; line 1540 (connection #104)
* DO phase starts
* SSH 0x24b1db8 state change from SSH_STOP to SSH_SFTP_QUOTE_INIT (line 2322)
* SSH 0x24b1db8 state change from SSH_SFTP_QUOTE_INIT to SSH_SFTP_GETINFO (line 864)
* SSH 0x24b1db8 state change from SSH_SFTP_GETINFO to SSH_SFTP_TRANS_INIT (line 1056)
* SSH 0x24b1db8 state change from SSH_SFTP_TRANS_INIT to SSH_SFTP_UPLOAD_INIT (line 1076)
* SSH 0x24b1db8 state change from SSH_SFTP_UPLOAD_INIT to SSH_SFTP_CREATE_DIRS_INIT (line 1135)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_INIT to SSH_SFTP_CREATE_DIRS (line 1225)
* Creating directory '/--ffff-10.17.115.137'
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_CREATE_DIRS_MKDIR (line 1238)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_MKDIR to SSH_SFTP_CREATE_DIRS (line 1264)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_UPLOAD_INIT (line 1241)
* SSH 0x24b1db8 state change from SSH_SFTP_UPLOAD_INIT to SSH_SFTP_CREATE_DIRS_INIT (line 1135)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_INIT to SSH_SFTP_CREATE_DIRS (line 1225)
* Creating directory '/--ffff-10.17.115.137'
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_CREATE_DIRS_MKDIR (line 1238)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_MKDIR to SSH_SFTP_CREATE_DIRS (line 1264)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_UPLOAD_INIT (line 1241)
* SSH 0x24b1db8 state change from SSH_SFTP_UPLOAD_INIT to SSH_SFTP_CREATE_DIRS_INIT (line 1135)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_INIT to SSH_SFTP_CREATE_DIRS (line 1225)
...
* Creating directory '/--ffff-10.17.115.137'
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_CREATE_DIRS_MKDIR (line 1238)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_MKDIR to SSH_SFTP_CREATE_DIRS (line 1264)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS to SSH_SFTP_UPLOAD_INIT (line 1241)
* SSH 0x24b1db8 state change from SSH_SFTP_UPLOAD_INIT to SSH_SFTP_CREATE_DIRS_INIT (line 1135)
* SSH 0x24b1db8 state change from SSH_SFTP_CREATE_DIRS_INIT to SSH_SFTP_CREATE_DIRS (line 1225)
```</div>

**Comment by bagder** [comment]
> Is the sftp transport designed to work only in blocking mode?

Everything in libcurl is (or should be) non-nonblocking.

Note that you're using a fairly old libcurl version, but I'm not sure the libssh backend has been changed a lot since then.

> Is there a way to change the working mode to non-blocking in sftp transfer?

If  there's something blocking while SFTP'ing. It's a bug. Either in libssh or in curl itself.

**Comment by bagder** [comment]
> Either in libssh or in curl itself.

This output:
~~~
[2022/03/23 15:33:57.472995, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
~~~
... makes it sound like it is the libssh function that gets stuck and never returns. Can you verify if that is indeed the case? If so, then this is a libssh problem.

**Comment by jiexuelc** [comment]
> ... makes it sound like it is the libssh function that gets stuck and never returns. Can you verify if that is indeed the case? If so, then this is a libssh problem.

yes, the libssh gets stuck on  the following log.
```
 [2022/03/23 15:33:57.472995, 3] ssh_channel_read_timeout:  Read (4) buffered : 0 bytes. Window: 1279138
```

**Comment by bagder** [comment]
> libssh gets stuck

Then that bug is a libssh problem

**Comment by PengZheng** [comment]
We try libssh because libssh2_sftp_close_handle is blocking. IIRC, this is a very old issue with libssh2:
https://marc.info/?l=libssh2-devel&m=121498802311288&w=4

The use case is as following: 
When PIR detected an object, our device is powered up,  capture a picture,  sending it to a remote server via SFTP, and then power down. If the network happens to disconnect when we call libssh2_sftp_close_handle, the device gets stuck, and precious battery energy is wasted.

We use libcurl so that we can switch between libssh and libssh2. Unfortunately, it seems that both have problems. 

@jiexuelc may have additional information to share with @bagder

**Comment by bagder** [comment]
> it seems that both have problems

It sounds to me that you should put some work in and fix the situation in the SSH library end first.

**Comment by PengZheng** [comment]
> > it seems that both have problems
> 
> It sounds to me that you should put some work in and fix the situation in the SSH library end first.

Yes. I tend to add options to libssh2_stfp_close_handle, so that if user set timeout happens, it will not wait for the remote end, and free all the local resources. But I'm not sure about the general API design. If you could provide some guidance on this, I can make a PR. The current "solution" in our code is horrible hack, and thus is not suitable for upstream.

Or if you would like to solve it directly upstream, I guess we can sponsor to make that happen? Honestly I has little experience on that.

What do you think?

**Comment by bagder** [comment]
Did you try with libssh2 and libcurl >= 7.78.0 ?  Since fa34353d07e1d libcurl will give up on the disconnect if it seems to take a while.

**Comment by PengZheng** [comment]
> Did you try with libssh2 and libcurl >= 7.78.0 ? Since [fa34353](https://github.com/curl/curl/commit/fa34353d07e1d3053ae55b91d3971edf548d238a) libcurl will give up on the disconnect if it seems to take a while.

@jiexuelc Let's try it in our environment.

**Comment by PengZheng** [comment]
> Did you try with libssh2 and libcurl >= 7.78.0 ? Since [fa34353](https://github.com/curl/curl/commit/fa34353d07e1d3053ae55b91d3971edf548d238a) libcurl will give up on the disconnect if it seems to take a while.

I believe it should solve the problem we encounter in the above use case. 

Does https://github.com/curl/curl/commit/fa34353d07e1d3053ae55b91d3971edf548d238a means a minor resource leak? 
IIRC, we have no other means to release sftp_handle than calling `libssh2_sftp_close_handle`.

Here comes another use case: the user changes SFTP server settings, so that we need to disconnect from some weird server, which keeps triggering disconnect timeout.

**Comment by PengZheng** [comment]
> > libssh gets stuck
> 
> Then that bug is a libssh problem

@jiexuelc read the source code, and he found that:

> SSH_SFTP_INIT state, the ssh session working mode is set to blocking mode. 

Thus the problem lies with libcurl's libssh integration.

**Comment by bagder** [comment]
This comment from `lib/vssh/libssh.c` I think explains the situation:
https://github.com/curl/curl/blob/795ed0508497e89ab583925c3ed867f2710679b1/lib/vssh/libssh.c#L1819-L1820

... so yes, it should **not** be set blocking, but according to the comment (made by @nmav), libssh doesn't work properly if not. So, it looks we're back to it being a libssh problem! :disappointed:

**Comment by firexinghe** [comment]
I'm using curl with libssh, about fa34353, will it merge to curl/lib/vssh/libssh.c ?

**Comment by bagder** [comment]
I would need some research to see if it applies there and how.
