### ISSUE TITLE
IOS platform, multi interface, poll return immediatly but info_read don't read done message

### ISSUE THREAD

**Issue by TXTT2016** [curl/curl#8634]
### I did this

My ios app has a file download by using curl multi interface to make request.

When this request is performing, my app switch to background or iphone go to sleep for a while. Then I switch my app to foreground or wake up the iphone, this problem happened.

curl_multi_poll return immediatly and curl_multi_info_read returned msg is null, my multi perform thread fall into a infinite loop.
(curl_multi_perform returnd running_handles is not 0)

### I expected the following

Is there a way to solve this problem?  My app needs to do some requests when switch to background, and this not appear on other plateforms.

### curl/libcurl version
7.80.0
[curl -V output]

### operating system
IOS

**Comment by bagder** [comment]
Sorry, but this is just comments without sufficient details for us to make any conclusions.

What protocol are you using? How do you know its an "infinite loop"? What's the status of the connection at that point? What's the status of the transfer?

**Comment by TXTT2016** [comment]
> Sorry, but this is just comments without sufficient details for us to make any conclusions.
> 
> What protocol are you using? How do you know its an "infinite loop"? What's the status of the connection at that point? What's the status of the transfer?

Thanks for your reply, I will make a try to gather these infomation lately

**Comment by TXTT2016** [comment]
> Sorry, but this is just comments without sufficient details for us to make any conclusions.
> 
> What protocol are you using? How do you know its an "infinite loop"? What's the status of the connection at that point? What's the status of the transfer?

Protocol is HTTP/1.1

```cpp
// multi perform loop

int msgsLeft = 0;
int still_running = 0;
CURLMsg* msg;
auto handle = curl_multi_init();
do
{
    CURLMcode code;
    code = curl_multi_perform(handle, &still_running);
    if (code != CURLM_OK)
    {
        break;
    }

    msg = curl_multi_info_read(handle, &msgsLeft);
    while (msg && msg->msg == CURLMSG_DONE)
    {
        curl_multi_remove_handle(handle, msg->easy_handle);
        msg = curl_multi_info_read(handle, &msgsLeft);
    }

    if (still_running)
    {
        code = curl_multi_poll(handle, NULL, 0, 1000, NULL);
        if (code != CURLM_OK)
        {
            break;
        }
    }
} while (still_running);

```

I have created a thread to run this multi perform loop. In the upper situation, curl_multi_poll return immediatly and I don't get msg from curl_multi_info_read.

I have opened curl debug verbose, these are this connection infomation. The "MSTATE_XXX" are log patchs to determined this connection's status. More debug logs remained are all "MSTATE_PERFORMING". So I think this connection maybe in performing status?

```log
CURL [0x13a01ea08]: MSTATE_CONNECT
CURL [0x13a01ea08]: MSTATE_RESOLVING
CURL [0x13a01ea08]: MSTATE_CONNECTING
CURL [0x13a01ea08]: MSTATE_CONNECTING
CURL [0x13a01ea08]: MSTATE_CONNECTING
CURL [0x13a01ea08]: MSTATE_PROTOCONNECT
CURL [0x13a01ea08]: TLSv1.2 (OUT), TLS handshake, Client hello (1):
CURL [0x13a01ea08]: MSTATE_PROTOCONNECTING
CURL [0x13a01ea08]: TLSv1.2 (IN), TLS handshake, Server hello (2):
CURL [0x13a01ea08]: TLSv1.2 (IN), TLS handshake, Certificate (11):
CURL [0x13a01ea08]: TLSv1.2 (IN), TLS handshake, Server key exchange (12):
CURL [0x13a01ea08]: TLSv1.2 (IN), TLS handshake, Server finished (14):
CURL [0x13a01ea08]: TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
CURL [0x13a01ea08]: TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
CURL [0x13a01ea08]: TLSv1.2 (OUT), TLS handshake, Finished (20):
CURL [0x13a01ea08]: MSTATE_PROTOCONNECTING
CURL [0x13a01ea08]: MSTATE_PROTOCONNECTING
CURL [0x13a01ea08]: TLSv1.2 (IN), TLS handshake, Finished (20):
CURL [0x13a01ea08]: MSTATE_DID
CURL [0x13a01ea08]: MSTATE_PERFORMING
CURL [0x13a01ea08]: MSTATE_PERFORMING
CURL [0x13a01ea08]: MSTATE_PERFORMING
CURL [0x13a01ea08]: MSTATE_PERFORMING
CURL [0x13a01ea08]: MSTATE_PERFORMING
```

**Comment by TXTT2016** [comment]
When I use the easy interface to do this download in that situation(When this request is performing, my app switch to background or iphone go to sleep for a while. Then I switch my app to foreground or wake up the iphone).

This request will return when I switch my app to foreground or wake up the iphone.

I have seen the easy interface source code, it used the multi interface to make request exactly. So this really confused me why it happend by use the multi interface.

**Comment by bagder** [comment]
`MSTATE_PERFORMING` means the transfer is ongoing, it has started and it hasn't completed yet.

**Comment by TXTT2016** [comment]
> `MSTATE_PERFORMING` means the transfer is ongoing, it has started and it hasn't completed yet.

Yes. But this request won't return after that, and the multi perform thread fall into a infinite loop.

Is there a way to solve this problem by use multi interface? Just like the easy interface, return error code is ok.  When I use the easy interface, this won't happen.

**Comment by bagder** [comment]
The easy interface is itself implemented using the multi interface, so the multi interface is always used when doing transfers.

**Comment by jay** [comment]
You may be seeing what you think is a difference between the easy and multi interface but actually isn't, instead it's just arbitrary variations in the network that cause different behavior. Likely in the worst case the network stack takes a while to tell curl the connection is dead. See also #8345

**Comment by bagder** [comment]
> iphone go to sleep for a while. Then I switch my app to foreground or wake up the iphone, this problem happened

When it comes back "alive", is the TCP connection still up? Does libcurl read any bytes from the connection when woken up? What TLS library are you using?

**Comment by TXTT2016** [comment]
> When it comes back "alive", is the TCP connection still up? Does libcurl read any bytes from the connection when woken up? What TLS library are you using?

TLS library is openSSL.

> When it comes back "alive", is the TCP connection still up?

I'm not sure how to confirm this TCP connection's status, is there a way by using curl interface? Maybe compile the to debug type or add more log to see?

> Does libcurl read any bytes from the connection when woken up?

I'll try to add some log to confirm it.

**Comment by bagder** [comment]
This issue has nothing for us to act on, we can only await new info that has not arrived in over a month. The primary suspicion is that this is a platform specific effect/bug/quirk and that perhaps something special is needed - but it takes someone using this platform to work it out. Feel free to reopen if we get further info that can take this further.

**Comment by TXTT2016** [comment]
https://github.com/curl/curl/issues/6132

**Comment by TXTT2016** [comment]
Not only for the wakeup socket, if your connection is performing while the app go to sleep by switch it to background, this connection's socket will also break. `Curl_socket_check` returnd read event, but `readwrite_data` can't read anything. `curl_multi_poll` returnd immediatly and will never block again
