### ISSUE TITLE
consider utilizing `Requires.private` directives in `libcurl.pc` instead of `Libs.private`

### ISSUE THREAD

**Issue by vapier** [curl/curl#864]
the curl build system goes through a good amount of effort to try and figure out when some external libs need other external libs, often for static linking purposes.  for example, it probes openssl and then tries to see if openssl also needs zlib and libdl.  this doesn't always work (new libs get added and curl doesn't probe those, or the libs get rebuilt which means curl needs to be rebuilt simply to reprobe the library).

ideally the `libcurl.pc` file, instead of looking like:
```
Libs.private: -lnghttp2 -lssl -lcrypto -lssl -lcrypto -lz
```

it would look like:
```
Libs.private:
Requires.private: libnghttp2 openssl zlib
```

now (1) the data will always be up-to-date regardless of how those other libs were configure/rebuilt/updated, and (2) curl wouldn't have to do all that probing.

NB: (1) can be done now and generally w/out pain, but (2) would mean that curl's build system itself would now rely on pkg-config being available/sane at build time.  not sure if non-pkg-config builds is something curl cares about.

**Comment by bagder** [comment]
Thanks! I think this suggestion makes perfect sense. Having our produced pkg-config file rely on the others also being pkg-config compatible seems reasonable. You up to making a PR for this change, @vapier ?

**Comment by ajdavis** [comment]
Hi, I'm investigating similar questions in my own C library, libmongoc. Can you tell me what changes resolved this issue in curl?

**Comment by jay** [comment]
The issue is unresolved, it was closed as a known bug
https://curl.haxx.se/docs/knownbugs.html#Utilize_Requires_private_directi
