### ISSUE TITLE
curl -X HEAD slower than curl -I

### ISSUE THREAD

**Issue by robocoder** [curl/curl#8642]
### I did this
```
# time curl -v -X HEAD http://localhost/api/1.0/
...
real	0m5.132s
user	0m0.014s
sys	0m0.001s
```

### I expected the following

Closer to 
```
# time curl -v -I http://localhost/api/1.0/
...
real	0m0.017s
user	0m0.009s
sys	0m0.005s
```

Custom access.log shows the requests were handled fairly quickly by apache
```
localhost:80 127.0.0.1 - - [28/Mar/2022:03:26:24 +0000] "HEAD /api/1.0/ HTTP/1.1" 200 298 "-" "curl/7.68.0" (863)
localhost:80 127.0.0.1 - - [28/Mar/2022:03:26:27 +0000] "HEAD /api/1.0/ HTTP/1.1" 200 298 "-" "curl/7.68.0" (1216)
```

### curl/libcurl version
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

`Linux ubuntu-focal 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by dfandrich** [comment]
On Sun, Mar 27, 2022 at 08:28:11PM -0700, Anthon Pang wrote:
> I did this
> 
> # time curl -v -X HEAD http://localhost/api/1.0/
[...]
> I expected the following
> 
> Closer to
> 
> # time curl -v -I http://localhost/api/1.0/

Those two commands don't do the same thing, so I'm not surprised to hear they
act differently. For one thing, a GET request that says HEAD (the -X version)
will try to download the number of bytes in Content-Length: which will never
come. If the server takes 5 seconds before closing the connection, it might
explain what you're seeing.

Recent versions of curl warn you when you try to run commands like this that
are likely incorrect.

Dan

**Comment by robocoder** [comment]
IIRC I set `Content-Length: 0` in the response header and didn't see it making a difference.

**Comment by dfandrich** [comment]
I gave just one theory. There are few good reasons to use -X HEAD so rather
than tying down which one is causing this difference, just stop doing it. But,
if you really want to know, start by comparing the debug logs between the two
commands.

**Comment by robocoder** [comment]
I already looked at the code. Should this be a documentation clarification (wrt CURLOPT_NOBODY/HTTPGET/POST/CUSTOMREQUEST) or code change (eg for -X HEAD to be an alias for -I)?

**Comment by bagder** [comment]
This is already documented in several places, plus the warning @dfandrich mentioned. What more can we document?

We will not make `-X HEAD` an alias, as that would break the ones that have an actual use for it the way it works.
