### ISSUE TITLE
Proposed ALPN failure clarification: append ", continuing with post-TLS negotiation"

### ISSUE THREAD

**Issue by ncoghlan** [curl/curl#8643]
Following up on the previous reports of the technically accurate but confusing to non-experts ALPN notification, a clarification that would have helped me would be:

    ALPN: server did not agree on a protocol, continuing with post-TLS negotiation

I would have submitted a PR, but this message appears in multiple places, so I wasn't sure if the preferred approach would be to just change them all or to factor them out as a shared constant (assuming that the proposed change is even acceptable in the first place).

(I would have commented on https://github.com/curl/curl/issues/2749 instead of filing a new ticket but it's locked)

**Comment by bagder** [comment]
I'm personally not convinced this suggested new wording will change much. I figure the fact it continues is already visible.

The string could indeed get moved into vtls.c somehow to get shared and used by all TLS backends since right now they all use their own duplicated version of it.

**Comment by bagder** [comment]
My change makes it instead say:

    ALPN: server did not agree on a protocol. Uses default.
