### ISSUE TITLE
--head shows wrong error code

### ISSUE THREAD

**Issue by Rohlik** [curl/curl#8674]
### I did this
I compared output of `/usr/bin/curl -I http://localhost:8000/en-US/custom/splunk_app_stream/ping` and `/usr/bin/curl -v http://localhost:8000/en-US/custom/splunk_app_stream/ping` and error code doesn't match.

With `-I`:
```
/usr/bin/curl -I http://localhost:8000/en-US/custom/splunk_app_stream/ping                              
HTTP/1.1 404 Not Found
Date: Tue, 05 Apr 2022 11:40:35 GMT
Content-Type: text/html
X-Content-Type-Options: nosniff
Content-Length: 57064
Vary: Accept-Encoding, Cookie
Connection: Keep-Alive
Set-Cookie: session_id_8000=11e00fdb078cdf3c9162775ca2d8856316efa2bc; expires=Tue, 05 Apr 2022 21:40:35 GMT; HttpOnly; Max-Age=36000; Path=/
Server: Splunkd
```

Without `-I`:
```
/usr/bin/curl -v http://localhost:8000/en-US/custom/splunk_app_stream/ping
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /en-US/custom/splunk_app_stream/ping HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 05 Apr 2022 11:42:39 GMT
< Content-Type: text/json;charset=utf-8
< X-Content-Type-Options: nosniff
< Content-Length: 527
< Vary: Accept-Encoding, Cookie
< Connection: Keep-Alive
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: session_id_8000=518492ae011ce12c8c4adbe0bff303fcf06e553a; expires=Tue, 05 Apr 2022 21:42:39 GMT; HttpOnly; Max-Age=36000; Path=/
< Server: Splunkd
```

### I expected the following
I expect code `200` also for `-I` as it is a correct one.
### curl/libcurl version

[curl -V output]
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.6/openssl/zlib nghttp2/1.33.0
### operating system
Linux splunk 5.15.26-1.gdc.el8.x86_64 #1 SMP Mon Mar 7 16:02:05 CET 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Rohlik** [comment]
Ok, but it is at least confusing as the default method is `GET`, right? So, code output should be the same 🤔.

**Comment by bagder** [comment]
curl shows you what the server sends. If that confuses you, then maybe you should talk to the admin of the server in question?

**Comment by Rohlik** [comment]
Thank you. I was able to solve my "_issue_" with:
`/usr/bin/curl -XGET -I http://localhost:8000/en-US/custom/splunk_app_stream/ping`, now I get `200` code output.
