### ISSUE TITLE
HTTP test server 'connection-monitor' problems

### ISSUE THREAD

**Issue by bagder** [curl/curl#868]
### I did this

Build curl and libcurl

$ cd tests && ./runtests.pl 1509 1525

... this causes the 1525 test to fail:

```
test 1525...[CURLOPT_PROXYHEADER is ignored CURLHEADER_UNIFIED]

 1525: proxy FAILED:
--- log/check-expected  2016-06-09 00:49:53.810105313 +0200
+++ log/check-generated 2016-06-09 00:49:53.810105313 +0200
@@ -1,3 +1,4 @@
+[DISCONNECT][LF]
 CONNECT the.old.moo.1525:8990 HTTP/1.1[CR][LF]
 Host: the.old.moo.1525:8990[CR][LF]
 User-Agent: Http Agent[CR][LF]

 - abort tests
TESTDONE: 1 tests out of 2 reported OK: 50%
TESTFAIL: These test cases failed: 1525 
TESTDONE: 2 tests were considered during 8 seconds.
```

The key is the `DISCONNECT` text which is put there when the connection monitor feature is enabled, which test 1509 does and it somehow "leaks" over into the subsequent test.
### I expected the following

Both tests to run fine
### curl/libcurl version

```
$ git describe 
curl-7_49_1-32-g608d161
$ curl -V
curl 7.50.0-DEV (x86_64-pc-linux-gnu) libcurl/7.50.0-DEV OpenSSL/1.0.2h zlib/1.2.8 libidn/1.32 libpsl/0.11.0 (+libicu/55.1) libssh2/1.7.0_DEV nghttp2/1.11.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets PSL 
```
### operating system

Debian Linux.

**Comment by xquery** [comment]
can confirm issue shows up on CentOS Linux release 7.2.1511

note that there are other tests with [DISCONNECT] that do not trigger this error, for example:

```
./runtests.pl 1008 1525
```
runs fine, while the only other test (with [DISCONNECT]) that emulates same issue like 1509 is 503

```
./runtests.pl 503 1525
```

tests 503 and 1509  both set http-proxy ... still investigating.
