### ISSUE TITLE
make curl_global_init thread-safe

### ISSUE THREAD

**Issue by fche** [curl/curl#8681]
(Not sure whether this counts as an RFE rather than a bug but:)

```
static CURLcode global_init(long flags, bool memoryfuncs)
{
  if(initialized++)
    return CURLE_OK;

```
If this test were mutex-protected or c11 atomic, libcurl-side problems from concurrent initialization could be solved.

**Comment by bagder** [comment]
I worked on a bit in #5017 but then shelved it for later.

#8680 is a new PR on a thread-safe init

**Comment by jay** [comment]
#8680 fixed this. If you use cmake build there is still work needed for atomic detection, see #8982.
