### ISSUE TITLE
iOS: timeout error when network changed

### ISSUE THREAD

**Issue by pingkai** [curl/curl#8686]
1.  open Wi-Fi and 4G network on a iPhone
2. Do a http2 request  use a multi handle eg. https://curl.se/
3. Close the Wi-Fi
4. Do the same requese in 2. And use the same multi handle again, and this request will fail or timeout

This problem only can be reproduced on iOS.

I think the step 4 use the same tcp socket in step 2, but the tcp socket was unavailable after step 3, but the OS don't report the error of this socket for a long time, and the requese 4 will wait until the error report.

And in some application this wait is can be bore. What can I do ?

Best regard

**Comment by jay** [comment]
This sounds like #8634, the network stack does not reset the connection right away. Also see [4.19 Why does not curl return an error when the network cable is unplugged?](https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro)

**Comment by pingkai** [comment]
> This sounds like #8634, the network stack does not reset the connection right away. Also see [4.19 Why does not curl return an error when the network cable is unplugged?](https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro)

@jay  Thanks for your reply, and I think you are right, and I have done some thing that mentioned in https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro. I have set the -speed-limit = 1  and --speed-time = 15s; but this will use 15s to get the error, and I Can't set it too little, because it will lead more error.
And I have monitor the iOS OS-specific mechanism,  I will cancel the stream when network changed, And 
1. set CURLOPT_FORBID_REUSE to 1 
2. curl_multi_remove_handle
3.  curl_easy_init() a new handle
4. set CURLOPT_FRESH_CONNECT to 1
5. make a new http2 request use the same mulit handle.

And it works well for the situation that the network change during I make the h2 request.

BUT, if I do not make any h2 requests, or my requests were done , and the network changed from Wi-Fi to 4g, then I do a new http2 request, and this request will reuse the old and dead tcp connection that use the Wi-Fi network, and my new request will return a timeout error after 15s, because I set the -speed-limit = 1  and --speed-time = 15s

After the timeout error, I will use  curl_easy_init() a new handle and set CURLOPT_FRESH_CONNECT to 1 to redo the request, and also it will ok, but it will wait for 15s, and I want to avoid this waiting, what can I do ?

I think if there is a way to mark all the connections cached in mulit handle forbid to reuse, and I will mark them when I know the network was changed. But didn't find this api.

And I have thought another way, curl_multi_init() a new multi handle after the network changde, and use the new multi handle to do the new request. and curl_multi_cleanup the old handle after no one useit. I think it will work, but it need lots of work to do in my code, and I don't think it is a good way...

**Comment by pingkai** [comment]
@jay I've tried the TCP keepalive opts, and I set CURLOPT_TCP_KEEPIDLE to 5s and CURLOPT_TCP_KEEPINTVL to 1s, and it works, but I think the time I set is too short, it will lead the client  have a bad behavior to the server, right? if so, I'll try the multiple connection caches solution.

Best regard

**Comment by pingkai** [comment]
@jay I have finished the multiple connection caches solution, it works well !

Best regard
