### ISSUE TITLE
EINTR changes (#4840) have introduced "select/poll error: 4" errors on FTP and FTPS file transfers.

### ISSUE THREAD

**Issue by phearus** [curl/curl#8703]
The changes EINTR made in [#4840](https://github.com/curl/curl/pull/4840) - specifically removing explicit checking and retrying on EINTR in lib/select.c - has introduced select/poll error: 4" errors on FTP and FTPS.

Other protocol file transfers are likely also now broken in a similar manner - but I cannot speak to these as I haven't attempted using them.

The changes made in [#4840](https://github.com/curl/curl/pull/4840) have catastrophically broken libcurl and thus requires additional work or reverting the original patch to reintroduce the socket EINTR check and retry pattern.

Interrupted syscalls that result in an EINTR socket status is not a catastrophic error - the socket checks resulting in EINTR need only be retried in the same loop the check occurs.

Adding explicit logic to check a socket for EINTR and thus allowing the loop to continue (e.g. retry the socket check without throwing an error) resolves the issue introduced in [#4840](https://github.com/curl/curl/pull/4840).

### I did this

Our application utilizes libcurl to transfer files over FTP and FTPS. 

### I expected the following

Before the change in [#4840](https://github.com/curl/curl/pull/4840) these file transfers always worked without error. We now see the following errors.

FTPS transfers now fail with the following error.
    "Failed(select/poll on SSL socket, errno: 4)"

FTP transfers now fail with the following error.
    "Failed(FTP response aborted due to select/poll error: 4)"

### curl/libcurl version
[curl -V output]

curl 7.81.0 (arm-openwrt-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1k
Release-Date: 2022-01-05
Protocols: file ftp ftps http https mqtt tftp 
Features: alt-svc HSTS HTTPS-proxy IPv6 Largefile SSL

### operating system

We are running version 4.14.267 armv7l Linux kernel.

**Comment by bagder** [comment]
Does #8961 improve this EINTR situation for you?

**Comment by jay** [comment]
> Does #8961 improve this EINTR situation for you?

Note that landed a month ago for select and #9091 just landed with the same change for poll. The reporter should try master.

**Comment by carenas** [comment]
Seems by context that this bug should be already closed and the fix released in 7.86.0

**Comment by bagder** [comment]
Fixed
