### ISSUE TITLE
Build curl lib with Mingw compiler

### ISSUE THREAD

**Issue by medbsl** [curl/curl#8705]
I want to use the curl lib in my project (c++ QT creator on windows), I download the zip lib file from the website https://curl.se/download.html (Version 7.82.0) and I wanted to build it using the Makefile with this commend mingw32-make mingw32 as described in the documentation https://curl.se/docs/install.html

but unfortunately, I am getting an error

mingw32-make mingw32
[....]
gcc   -s -m32 -static -o curl.exe curl.res slist_wc.o tool_binmode.o tool_bname.o 
tool_cb_dbg.o tool_cb_hdr.o tool_cb_prg.o tool_cb_rea.o tool_cb_see.o tool_cb_wrt.o 
tool_cfgable.o tool_dirhie.o tool_doswin.o tool_easysrc.o tool_filetime.o tool_findfile.o 
tool_formparse.o tool_getparam.o tool_getpass.o tool_help.o tool_helpers.o tool_hugehelp.o 
tool_libinfo.o tool_listhelp.o tool_main.o tool_msgs.o tool_operate.o tool_operhlp.o 
tool_panykey.o tool_paramhlp.o tool_parsecfg.o tool_progress.o tool_strdup.o tool_setopt.o 
tool_sleep.o tool_urlglob.o tool_util.o tool_vms.o tool_writeout.o tool_writeout_json.o 
tool_xattr.o strtoofft.o nonblock.o warnless.o curl_ctype.o curl_multibyte.o version_win32.o 
dynbuf.o -L../lib -lcurl -lwldap32 -lws2_32
../lib\libcurl.a: error adding symbols: Archive has no index; run ranlib to add one
collect2.exe: error: ld returned 1 exit status
make[1]: *** [curl.exe] Fehler 1
make[1]: Leaving directory `D:/Dev/API/curl-7.82.0/src'
make: *** [mingw32] Fehler 2

I tried to run ranlib lib\libcurl.a but the issue is still there,

does anyone have an idea about it?

One more question: is it possible also to build it with mingw64?

**Comment by bagder** [comment]
Both mingw32 and mignw64 should work. but I suspect that makefile target is not working.

If you want to build with mingw, then you should probably go all msys and do configure + make the autotools style: https://everything.curl.dev/build/autotools

Thoughts @jay or @vszakats ?

**Comment by vszakats** [comment]
This build method is used for curl-for-win (official Windows builds) so it should generally work. `ranlib` is run as part of the process. There are many versions/builds of mingw32, perhaps this specific one behaves differently than expected. In most cases the original mingw32 is best be avoided (it's rather outdated) and mingw-w64 is the better option (including the one shipping with MSYS2), so trying that may help.

**Comment by bagder** [comment]
> This build method

And by **this method** I assume you mean autotools/configure. I am going to update docs/INSTALL to rather suggest that for mingw builds.

**Comment by vszakats** [comment]
@bagder No, sorry. I mean the bare/native mingw-build, aka `Makefile.m32`, which can be invoked via the default `Makefile` found in the source disto root. I'm assuming this Issue referred to that build method, because of the `mingw32` argument passed to the make tool. Such argument isn't necessary with the autotools/configure method.

**Comment by bagder** [comment]
ok, I misunderstood. Then I think I'll just close #8717. Thanks!

**Comment by bagder** [comment]
This issue now sits in a limbo since this doesn't reproduce and we recommend using mingw-w64. I don't see what more we can do unless something change or more info is provided.
