### ISSUE TITLE
rm/dele files with spaces

### ISSUE THREAD

**Issue by hpellegrino3105** [curl/curl#871]
### I did this 

curl -k --ftp-ssl -u uname:pwd -Q "rm /myfolder/myfile with spaces.txt" sftp://ftp.myserver.com:22

### I expected the following

file to be deleted

### curl/libcurl version

7.49.1 - x86_64-pc-win32

[curl -V output perhaps?]

curl: (21) rm command failed: no such file or directory

### operating system

Windows 2008 , 64bit

tried escaping with %20 or \x20 same thing... is it the windows cmd shell or ftp host culprit?

thanks

Horacio Pellegrino

**Comment by bagder** [comment]
curl passes on the string exactly as specified to the libssh2 API call, and it uses it as-is as well, so it's hard to tell...

**Comment by jay** [comment]
You have to escape the quotes, try this:
~~~
curl -k --ftp-ssl -u uname:pwd -Q "rm \"/myfolder/myfile with spaces.txt\"" sftp://ftp.myserver.com:22
~~~

**Comment by hpellegrino3105** [comment]
Jay, your solution was perfect! It worked as a charm from the very beginning! Send me your address so I can send cookies! :-)

**Comment by jay** [comment]
Glad it worked. Please note this is an issue tracker, and in the future if you have a question you can't find the answer to ask on one of the [mailing lists](https://curl.haxx.se/mail/), curl-users (curl) or curl-library (libcurl).
