### ISSUE TITLE
CPU utilization is reaching 100% - libCurl

### ISSUE THREAD

**Issue by Harishreddy01** [curl/curl#8710]
### I did this
Hi all,
I have a single threaded application which uses libCurl. My use case is like my application connects to Sti-server (STIR/SHAKEN server) to make transfers. We are using curl_multi API's in our application. So, the issue is like when there is some network issue (network latency) or if my server is slow/overloaded , my application is trying to continuously open lot's of tcp connections towards sti-server an ending up spiking CPU percent to 100%. I tried to do some profiling on my application using perf top and the output looks like below during the issue:

    11.34%  usbc              [.] Curl_pgrsUpdate      
     6.99%  [kernel]          [k] __fget
     6.25%  [kernel]          [k] do_sys_poll
     5.39%  [kernel]          [k] sock_poll
     4.71%  usbc              [.] Curl_readwrite
     4.66%  [kernel]          [k] tcp_poll
     4.28%  [vdso]            [.] 0x0000000000000747
     4.14%  usbc              [.] Curl_single_getsock
     3.19%  usbc              [.] curl_multi_perform
     3.33%  [vdso]            [.] 0x0000000000000747
     2.92%  usbc              [.] 0x00000000023bfb60
     1.96%  [kernel]          [k] syscall_return_via_sysret
     1.67%  [kernel]          [k] fput_many
     1.56%  libc.so.6         [.] poll
     1.40%  usbc              [.] 0x00000000023b8771
     1.32%  [kernel]          [k] entry_SYSCALL_64_after_hwframe
     1.07%  usbc              [.] 0x00000000023ba458
     0.99%  [kernel]          [k] do_syscall_64
     0.94%  libc.so.6         [.] 0x000000000010c6a4
     0.92%  libtcmalloc.so    [.] tc_deletearray
     0.82%  [kernel]          [k] copy_user_generic_unrolled
     0.78%  usbc              [.] 0x00000000023b878b
     0.73%  [kernel]          [k] entry_SYSCALL_64
     0.72%  usbc              [.] 0x0000000000f244b4
     0.71%  libc.so.6         [.] 0x000000000010c707
     0.71%  usbc              [.] Curl_speedcheck
     0.68%  usbc              [.] Curl_timeleft
     0.67%  usbc              [.] curl_multi_wait

And from this output i am suspecting, its spending more time on polling and got struck on some loop.

So i tried limiting the number of tcp connections to 100 using CURLMOPT_MAX_TOTAL_CONNECTIONS API. However, i still end up in same problem but my bt from perf top looks some what different.

    41.98%  usbc              [.] 0x00000000024139b1
    17.57%  usbc              [.] curl_multi_perform
     2.85%  usbc              [.] 0x00000000024154a3
     1.76%  usbc              [.] curl_multi_wait
     1.13%  usbc              [.] Curl_pgrsUpdate
     1.09%  usbc              [.] 0x0000000002415640
     1.06%  libtcmalloc.so    [.] tc_deletearray
     0.89%  [kernel]          [k] __fget
     0.74%  [kernel]          [k] do_sys_poll
     0.65%  usbc              [.] 0x00000000024154d8
     0.62%  [vdso]            [.] 0x0000000000000747
     0.57%  libc.so.6         [.] _IO_vfscanf
     0.57%  usbc              [.] Curl_connect
     0.54%  [kernel]          [k] tcp_poll
     0.51%  [kernel]          [k] sock_poll
     0.45%  [kernel]          [k] syscall_return_via_sysret
     0.45%  usbc              [.] 0x00000000024139e3
     0.44%  usbc              [.] Curl_splay
     0.43%  usbc              [.] Curl_readwrite
     0.42%  usbc              [.] 0x00000000024139bb
     0.40%  usbc              [.] Curl_conncache_extract_oldest
     0.37%  libtcmalloc.so    [.] tc_malloc
     0.34%  usbc              [.] 0x0000000000f37624
     0.34%  usbc              [.] Curl_dedotdotify
     0.32%  usbc              [.] Curl_single_getsock
     0.31%  usbc              [.] Curl_strncasecompare
     0.28%  usbc              [.] 0x000000000241551e
     0.28%  libc.so.6         [.] poll

### I expected the following
1) connection not getting struck or spending more time on polling.
2) when limiting number of connections to 100, expected cpu to not spike to 100%

### curl/libcurl version
url -V
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k libssh2/1.8.0 nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: file ftp ftps http https scp sftp
Features: AsynchDNS IPv6 Largefile SSL HTTP2 UnixSockets HTTPS-proxy

### operating system
Linux 5.4.17 #17 SMP PREEMPT Thu Apr 14 05:32:20 UTC 2022 x86_64 GNU/Linux

**Comment by dfandrich** [comment]
On Thu, Apr 14, 2022 at 04:42:44AM -0700, Harishreddy01 wrote:
> curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.0.2k libssh2/
> 1.8.0 nghttp2/1.33.0
> Release-Date: 2018-09-05

This version is over 3 years old. We've fixed approximately 2961 bugs since
then. Does it still happen with a recent version?

**Comment by Harishreddy01** [comment]
we didn't tried on the latest versions. If possible, can you please point out to any such related bugs (100% CPU spike) which got fixed in versions after 7.61.1.

**Comment by dfandrich** [comment]
I recall the topic of 100% CPU spikes coming up recently, but I don't remember
bug numbers. There are lots of instances of the terms "busy loop" and "busy
wait" in the commit comments. Here are the first few I found:

d293bf4a789e7a02dd5ea40bcd81d23698859641
c7f95fa0cc252167cb210e1c0ab4f8bbabc1c371
2a41e236716da4c41ebc1132bd36d9273bd0321f
2258b7bcc265b5fe9bfa79ddd079f57e61557da7
4e1eee1500202a6a21fbedbd6e84d0e6c9af4b50

**Comment by Harishreddy01** [comment]
Thank you @dfandrich.
