### ISSUE TITLE
Make fails with: invalid use of undefined type 'struct Curl_share'

### ISSUE THREAD

**Issue by DanTheMann15** [curl/curl#8723]
Host OS: Windows 7 SP1
Target System: x86_64-w64-mingw32
Toolchain: [MSYS2](https://www.msys2.org) 20220319 (latest packages)

CURL Version: 7.82.0 (release tarball), 7.83.0 Latest (.git)

I don't know if a recent update to a package or something with MSYS2 did this, or some change in CURL. but over the past couple of months i have been getting this error, sometimes it will compile, but most of the time it does not.

Configuration: `--enable-static --disable-shared --prefix=/tmp/tsschecker_build_win64 --disable-dependency-tracking --disable-manual --enable-ipv6 --with-winssl --with-schannel --with-winidn --without-ssl --with-zlib`

Console Log: [buildlog.txt](https://github.com/curl/curl/files/8510349/buildlog.txt)

**Comment by bagder** [comment]
Curious, because `lib/vtls/vtls.c` includes `share.h` which has that struct defined ...

**Comment by DanTheMann15** [comment]
damn, quick response. but yeah, it baffles me too. i just tried the latest git from this repository and i get the same problem.

i may need to try a few other things, but yeah.

**Comment by DanTheMann15** [comment]
ok, just tried this: i edited the `#include "../share.h"` on line 59 in lib/vtls/vtls,c to `#include "../share.h"` and now it builds like a charm! seems like the header isn't found as it looks inside the vtls directory while the share.h header is in the upper folder.

**Comment by bagder** [comment]
If that would be the case, then I would imagine it would fail on all platforms and builds, not just yours... The makefile in lib/ does set `-I` to include the lib dir.

**Comment by bagder** [comment]
I suspect you have another share.h file in your include tree that for some reason shadows the curl one and gets picked up by the compiler instead of the "real" one since you don't get an error about a missing include file...

I do not believe this is a curl bug.

**Comment by DanTheMann15** [comment]
i believe it's an MSYS2 bug, but i still don't know for sure.

i have one share.h file in the mingw64 include folder here's the contents of it:

> 
> /**
>  * This file has no copyright assigned and is placed in the Public Domain.
>  * This file is part of the mingw-w64 runtime package.
>  * No warranty is given; refer to the file DISCLAIMER.PD within this package.
>  */
> #ifndef _INC_SHARE
> #define _INC_SHARE
> 
> #ifndef _WIN32
> #error Only Win32 target is supported!
> #endif
> 
> #define _SH_COMPAT 0x00
> #define _SH_DENYRW 0x10
> #define _SH_DENYWR 0x20
> #define _SH_DENYRD 0x30
> #define _SH_DENYNO 0x40
> #define _SH_SECURE 0x80
> 
> #ifndef	NO_OLDNAMES
> #define SH_COMPAT _SH_COMPAT
> #define SH_DENYRW _SH_DENYRW
> #define SH_DENYWR _SH_DENYWR
> #define SH_DENYRD _SH_DENYRD
> #define SH_DENYNO _SH_DENYNO
> #endif
> 
> #endif
> 

Regardless of this, i'm gonna try building curl with Cygwin64 and Ubuntu 20.04 (mingw64) to see if i can repeat this issue there.

if you have time though at all, do you mind installing MSYS2 on a Windows machine and trying to build curl using it via mingw32/64? you most-likely will be able to pick-up on something i miss.

i'll let you know how it goes on Cygwin64/Ubuntu, be back soon.

**Comment by DanTheMann15** [comment]
On Cygwin64 Curl compiled without a hitch with the same configuration.

here's the share.h contents from Cygwin64 found in `/usr/x86_64-w64-mingw32/sys-root/mingw/include`

> > /**
>  * This file has no copyright assigned and is placed in the Public Domain.
>  * This file is part of the mingw-w64 runtime package.
>  * No warranty is given; refer to the file DISCLAIMER.PD within this package.
>  */
> #ifndef _INC_SHARE
> #define _INC_SHARE
> 
> #ifndef _WIN32
> #error Only Win32 target is supported!
> #endif
> 
> #define _SH_COMPAT 0x00
> #define _SH_DENYRW 0x10
> #define _SH_DENYWR 0x20
> #define _SH_DENYRD 0x30
> #define _SH_DENYNO 0x40
> #define _SH_SECURE 0x80
> 
> #ifndef	NO_OLDNAMES
> #define SH_COMPAT _SH_COMPAT
> #define SH_DENYRW _SH_DENYRW
> #define SH_DENYWR _SH_DENYWR
> #define SH_DENYRD _SH_DENYRD
> #define SH_DENYNO _SH_DENYNO
> #endif
> 
> #endif

**Comment by gvanem** [comment]
@DanTheMann15 Maybe you have a `$C_INCLUDE_PATH` pointing to the MSYS's `share.h`?

**Comment by DanTheMann15** [comment]
my $C_INCLUDE_PATH is set to /usr/local/include. msys2 itself doesn't define a $C_INCLUDE_PATH.
the only paths it defines are for pkgconfig ($PKG_CONFIG_PATH) and bin ($PATH).

but now that you mention it, i should try setting some include paths to /msys64/include and see what happens.

**Comment by DanTheMann15** [comment]
> my $C_INCLUDE_PATH is set to /usr/local/include. msys2 itself doesn't define a $C_INCLUDE_PATH. the only paths it defines are for pkgconfig ($PKG_CONFIG_PATH) and bin ($PATH).
> 
> but now that you mention it, i should try setting some include paths to /mingw64/include and see what happens.

and that fixed it... so turns out the compilers can't find share.h in msys2 at all. - what the fuck?
well... now that we know the cause, this issue can be closed.

The cure it to make sure that if compiling for mingw64 (whether x86_64 or i686) to set the include paths accordingly.
i wish msys2 set it for you if you install mingw64/32 tools, but i guess they made it that way for user customizability.
