### ISSUE TITLE
trying to compile and install curl with -http3 from the source code 

### ISSUE THREAD

**Issue by ShawnBian** [curl/curl#8733]
I just strictly follow the below links to install curl with http3 from my centos8, unfortunately, it is failed and really drive me crazy :
https://github.com/curl/curl/blob/master/docs/HTTP3.md

[root@centos8 curl]# LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" ./configure --with-openssl=/usr/local/openssl --with-nghttp3=/usr/local/nghttp3 --with-ngtcp2=/usr/local/ngtcp2 --enable-alt-svc
it throw below error when I tried the last step:
checking for libidn2 options with pkg-config... no
configure: IDN_LIBS: "-lidn2"
configure: IDN_LDFLAGS: ""
configure: IDN_CPPFLAGS: ""
configure: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... no
checking idn2.h usability... no
checking idn2.h presence... no
checking for idn2.h... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libnghttp2 options with pkg-config... no
checking for nghttp2_session_set_local_window_size in -lnghttp2... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libngtcp2 options with pkg-config... found
configure: -l is -lngtcp2 
configure: -I is -I/usr/local/ngtcp2/include 
configure: -L is -L/usr/local/ngtcp2/lib 
checking for ngtcp2_conn_client_new_versioned in -lngtcp2... yes
checking ngtcp2/ngtcp2.h usability... yes
checking ngtcp2/ngtcp2.h presence... yes
checking for ngtcp2/ngtcp2.h... yes
configure: Added /usr/local/ngtcp2/lib to CURL_LIBRARY_PATH
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libngtcp2_crypto_openssl options with pkg-config... no
configure: error: --with-ngtcp2 was specified but could not find ngtcp2_crypto_openssl pkg-config file.

really appreciated it if someone know the reason for the error above. thanks

**Comment by bagder** [comment]
>  configure: error: --with-ngtcp2 was specified but could not find ngtcp2_crypto_openssl pkg-config file.

It means there is no `$PREFIX/lib/pkgconfig/libngtcp2_crypto_openssl.pc` file where curl's configure expected there to be one and where ngtcp2 is expected to install one on make install.

**Comment by jay** [comment]
You may need to set PKG_CONFIG_PATH. configure will check for libngtcp2_crypto_openssl.pc (example: /home/owner/ngbuild/lib/pkgconfig/libngtcp2_crypto_openssl.pc) if curl is being built with OpenSSL as the SSL backend, or libngtcp2_crypto_gnutls.pc if curl is being built with GnuTLS as the SSL backend.

**Comment by ShawnBian** [comment]
Thank you two for the feedback, Actually, I do have already install ngtcp2 and there is no that file you mention above.

[root@centos8 pkgconfig]# pwd
/usr/local/ngtcp2/lib/pkgconfig
[root@centos8 pkgconfig]# ls
libngtcp2.pc
[root@centos8 pkgconfig]# 

How could that be for there is no such file named "libngtcp2_crypto_gnutls.pc" . Since I just strictly followed the official link to finish all the steps, even though there are many error outputs thrown during the process . finally, I have resolved them all to make it forward.
Anyway,did I just miss something during the whole compile process or how could I resolve this issue? Thanks in advance.

**Comment by bagder** [comment]
I just rebuilt and reinstalled ngtcp2 from its git main and I get it installed on `make install` just fine.

Are you using the latest ngtcp2? What configure options do you pass to it?

**Comment by ShawnBian** [comment]
thank you for the quick response , here is the command history regarding how to compile and install ngtcp2 
53   git clone https://github.com/ngtcp2/ngtcp2
   54  ls
   55  cd ngtcp2/
   56  ls
   57  autoreconf -fi
   58  ./configure PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig:/usr/local/nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" --prefix=/usr/local/ngtcp2
   59  echo $?
   60  make
   61  echo $?
   62  make install

**Comment by bagder** [comment]
@tatsuhiro-t any idea what's going on here?

**Comment by tatsuhiro-t** [comment]
If libngtcp2_crypto_openssl.pc is missing, it means that ngtcp2 configure script failed to find quictls flavored openssl.  Running ngtcp2 configure with --with-openssl will error out if it failed to find quictls/openssl.

**Comment by ShawnBian** [comment]
appreciated for the feedback , it throw below error output:

checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking whether g++ supports C++17 features with -std=c++17... yes
checking for CUNIT... no
configure: WARNING: Package 'cunit', required by 'virtual:world', not found
checking for CU_initialize_registry in -lcunit... no
checking for OPENSSL... no
configure: Package 'openssl', required by 'virtual:world', not found
configure: error: openssl was requested (--with-openssl) but not found
[root@centos8 ngtcp2]# ./configure PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig:/usr/local/nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" --prefix=/usr/local/ngtcp2 --with-openssl

**Comment by ShawnBian** [comment]
I just run the configure again:
./configure PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig:/usr/local/nghttp3/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" --prefix=/usr/local/ngtcp2 --with-openssl=/usr/local/openssl/

it seems to configure it successfully .

configure: summary of build options:

    Package version: 0.4.0-DEV
    Library version: 2:0:0
    Install prefix:  /usr/local/ngtcp2
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++ -std=c++17
      CXXFLAGS:       -g -O2
      LDFLAGS:        -Wl,-rpath,/usr/local/openssl/lib
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Libtool:
      LIBTOOL_LDFLAGS: 
    Crypto helper libraries:
      libngtcp2_crypto_openssl:   no
      libngtcp2_crypto_gnutls:    no
      libngtcp2_crypto_boringssl: no
      libngtcp2_crypto_picotls:   no
    Test:
      CUnit:          no (CFLAGS='' LIBS='')
    Debug:
      Debug:          no (CFLAGS='')
    Libs:
      OpenSSL:        no (CFLAGS='' LIBS='')
      Libev:          no (CFLAGS='' LIBS='')
      Libnghttp3:     yes (CFLAGS='-I/usr/local/nghttp3/include ' LIBS='-L/usr/local/nghttp3/lib -lnghttp3 ')
      Jemalloc:       no (CFLAGS='' LIBS='')
      GnuTLS:         no (CFLAGS='' LIBS='')
      BoringSSL:      no (CFLAGS='' LIBS='')
      Picotls:        no (CFLAGS='' LIBS='')
    Examples:         no

**Comment by ShawnBian** [comment]
then I go back to build curl and running below command:LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" ./configure --with-openssl=/usr/local/openssl --with-nghttp3=/usr/local/nghttp3 --with-ngtcp2=/usr/local/ngtcp2 --enable-alt-svc

it seems got the same error output:
[root@centos8 curl]# LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" ./configure --with-openssl=/usr/local/openssl --with-nghttp3=/usr/local/nghttp3 --with-ngtcp2=/usr/local/ngtcp2 --enable-alt-svc



checking for libidn2 options with pkg-config... no
configure: IDN_LIBS: "-lidn2"
configure: IDN_LDFLAGS: ""
configure: IDN_CPPFLAGS: ""
configure: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... no
checking idn2.h usability... no
checking idn2.h presence... no
checking for idn2.h... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libnghttp2 options with pkg-config... no
checking for nghttp2_session_set_local_window_size in -lnghttp2... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libngtcp2 options with pkg-config... found
configure: -l is -lngtcp2 
configure: -I is -I/usr/local/ngtcp2/include 
configure: -L is -L/usr/local/ngtcp2/lib 
checking for ngtcp2_conn_client_new_versioned in -lngtcp2... yes
checking ngtcp2/ngtcp2.h usability... yes
checking ngtcp2/ngtcp2.h presence... yes
checking for ngtcp2/ngtcp2.h... yes
configure: Added /usr/local/ngtcp2/lib to CURL_LIBRARY_PATH
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for libngtcp2_crypto_openssl options with pkg-config... no
configure: error: --with-ngtcp2 was specified but could not find ngtcp2_crypto_openssl pkg-config file.

**Comment by tatsuhiro-t** [comment]
--with-openssl=/usr/local/openssl/ does not work.  It effectively evaluates to --without-openssl.  The output clearly saied:

```
  OpenSSL:        no (CFLAGS='' LIBS='')
```

**Comment by ShawnBian** [comment]
thank you for the feedback. if that does not work, may I know how should it be? thank in advance

**Comment by tatsuhiro-t** [comment]
Please make sure that openssl is installed under /usr/local/openssl.

**Comment by bagder** [comment]
... and that it is an OpenSSL branch that works with ngtcp2.

**Comment by ShawnBian** [comment]
yes , openssl is installed under /usr/local/openssl
[root@centos8 bin]# pwd
/usr/local/openssl/bin
[root@centos8 bin]# ls
c_rehash  openssl
[root@centos8 bin]#

**Comment by bagder** [comment]
> openssl is installed

But *which* OpenSSL ?

**Comment by ShawnBian** [comment]
thank you for the feedback during the weekend. 

before I run the command: which openssl ,it outputs below:
[root@centos8 openssl]# which openssl
/usr/bin/openssl

now I just changed the ENV variable from /etc/profile"
PATH=/usr/local/openssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
export PATH

now it is changed to:

[root@centos8 openssl]# which openssl
/usr/local/openssl/bin/openssl
[root@centos8 openssl]# 

Should I do that modification? Looking forward to your reply. thanks

**Comment by bagder** [comment]
I would point you to ngtcp2's [requirements section](https://github.com/ngtcp2/ngtcp2#requirements) where it lists 4 different TLS alternatives. The OpenSSL one says **[OpenSSL with QUIC support](https://github.com/quictls/openssl/tree/OpenSSL_1_1_1n+quic)**. Your "normal" OpenSSL installation will not qualify.

**Comment by ShawnBian** [comment]
thank you for the feedback, If the installation of OpenSSL is not qualified, I can follow the links [OpenSSL with QUIC support](https://github.com/quictls/openssl/tree/OpenSSL_1_1_1n+quic) to install it again from new centos8 environment. 
but the above link is just installed OpenSSL by default which means does not specify any parameter during the config(such as --prefix or enable-tls1_3 ).

I am a little bit confused about which docs I can follow to finish the installation.

**Comment by tatsuhiro-t** [comment]
I'm not sure the your current openssl installation is from https://github.com/quictls/openssl/tree/OpenSSL_1_1_1n+quic or not, but if it is not, you need to install it with the desired prefix.  If you want to install the quictls/openssl under /usr/local/openssl, run config script with --prefix=/usr/local/openssl and build and install the openssl library.  After the installation, please check /usr/local/openssl/lib and  /usr/local/openssl/lib/pkgconfig directories.

**Comment by ShawnBian** [comment]
thank you for the feedback during the weekend.
did you mean I just follow https://github.com/quictls/openssl/tree/OpenSSL_1_1_1n+quic to install OpenSSL , not https://github.com/quictls/openssl/tree/openssl-3.0.2+quic ?
Honestly, these docs really make me confused a lot(Since these docs do not cover too much, during the process of installation, there are tons of errors happened ).  it does not matter that the OpenSSL installed the directory under /usr/local/openssl or somewhere else. I just wanna be simple to make it work.



thanks in advance ,

**Comment by tatsuhiro-t** [comment]
If you know how PKG_CONFIG_PATH and other configuration path parameters work, it is fine to choose whatever path you like.  But in this case, it seems you are struggling with the installation path, therefore it is better to fix the installation path to /usr/local/openssl to fix this issue quickly.  OpenSSL 3.0 is tend to be buggy and slow.  But it should still work.  And if you use OpenSSL 3.0, you need to specify /usr/local/openssl/lib64/pkgconfig in PKG_CONFIG_PATH.

**Comment by ShawnBian** [comment]
Got it, I will try to refer https://github.com/quictls/openssl/tree/OpenSSL_1_1_1n+quic to install it from a new centos8 environment.

Much appreciated the help even for the weekend.

**Comment by ShawnBian** [comment]
if I install openssl (OpenSSL_1_1_1n+quic) under the directory of /usr/local/openssl .and not it seem works fine

[root@centos8 bin]# pwd
/usr/local/openssl/bin
[root@centos8 bin]# ./openssl version
OpenSSL 1.1.1n+quic  15 Mar 2022

Now I am trying to install ngtcp2 

 % ./configure PKG_CONFIG_PATH=<somewhere1>/lib/pkgconfig:<somewhere2>/lib/pkgconfig LDFLAGS="-Wl,-rpath,<somewhere1>/lib" --prefix=<somewhere3> --enable-lib-only

Could you please help to explain what is the meaning of somwhere1 and somewhere2 and somewhere3? 
and what directory should be filled in here?

many thanks

**Comment by tatsuhiro-t** [comment]
I do not understand somewhere1, 2, 3.  Where are they from?
Assuming that you installed openssl 1.1.1n+quic under /usr/local/openssl and ./configure PKG_CONFIG_PATH=/usr/local/openssl/lib/pkgconfig cannot find openssl, then I have no idea why it does not work.

**Comment by ShawnBian** [comment]
% cd ..
 % git clone https://github.com/ngtcp2/ngtcp2
 % cd ngtcp2
 % autoreconf -fi
 % ./configure PKG_CONFIG_PATH=<somewhere1>/lib/pkgconfig:<somewhere2>/lib/pkgconfig LDFLAGS="-Wl,-rpath,<somewhere1>/lib" --prefix=<somewhere3> --enable-lib-only
 % make
 % make install
from this link :https://github.com/curl/curl/blob/master/docs/HTTP3.md

thank you for the answering

**Comment by bagder** [comment]
They are used in the instruction steps above and should be replaced with the actual paths you use.

**Comment by ShawnBian** [comment]
thank you . I understand that should be replaced with the actual paths. but I don't know how to replace it or use what to replace .

Since I don't know somwhere1 and somewhere2 and somewhere3 refer to? 

in my case , openssl is installed under the /usr/local/openssl , nghttp3 is installed under the /usr/local/nghttp3.
I intend to install ngtcp2 under the /usr/local/ngtcp2

$ ./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"

if I make the configure like above ,is that correct ?

**Comment by ShawnBian** [comment]
I am almost gonna give that up . this is really really confused and dont have detailed explaination 

before give it up ,I will do the last try:

I just have done this configure:

./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"

it seems still not work ,right ?

config.status: executing depfiles commands
configure: summary of build options:

    Package version: 0.4.0-DEV
    Library version: 2:0:0
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C preprocessor: gcc -E
      CPPFLAGS:       
      C compiler:     gcc
      CFLAGS:         -g -O2
      C++ compiler:   g++
      CXXFLAGS:       
      LDFLAGS:        -Wl,-rpath,/usr/local/openssl/build/lib
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Libtool:
      LIBTOOL_LDFLAGS: 
    Crypto helper libraries:
      libngtcp2_crypto_openssl:   no
      libngtcp2_crypto_gnutls:    no
      libngtcp2_crypto_boringssl: no
      libngtcp2_crypto_picotls:   no
    Test:
      CUnit:          no (CFLAGS='' LIBS='')
    Debug:
      Debug:          no (CFLAGS='')
    Libs:
      OpenSSL:        no (CFLAGS='' LIBS='')
      Libev:          no (CFLAGS='' LIBS='')
      Libnghttp3:     no (CFLAGS='' LIBS='')
      Jemalloc:       no (CFLAGS='' LIBS='')
      GnuTLS:         no (CFLAGS='' LIBS='')
      BoringSSL:      no (CFLAGS='' LIBS='')
      Picotls:        no (CFLAGS='' LIBS='')
    Examples:         no

**Comment by wangfuyu** [comment]
> I am almost gonna give that up . this is really really confused and dont have detailed explaination
> 
> before give it up ,I will do the last try:
> 
> I just have done this configure one more time:
> 
> ./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"
> 
> it seems still not work,right?
> 
> config.status: executing depfiles commands configure: summary of build options:
> 
> ```
> Package version: 0.4.0-DEV
> Library version: 2:0:0
> Install prefix:  /usr/local
> System types:
>   Build:         x86_64-pc-linux-gnu
>   Host:          x86_64-pc-linux-gnu
>   Target:        x86_64-pc-linux-gnu
> Compiler:
>   C preprocessor: gcc -E
>   CPPFLAGS:       
>   C compiler:     gcc
>   CFLAGS:         -g -O2
>   C++ compiler:   g++
>   CXXFLAGS:       
>   LDFLAGS:        -Wl,-rpath,/usr/local/openssl/build/lib
>   WARNCFLAGS:     
>   WARNCXXFLAGS:   
>   EXTRACFLAG:     -fvisibility=hidden
>   LIBS:           
> Library:
>   Shared:         yes
>   Static:         yes
> Libtool:
>   LIBTOOL_LDFLAGS: 
> Crypto helper libraries:
>   libngtcp2_crypto_openssl:   no
>   libngtcp2_crypto_gnutls:    no
>   libngtcp2_crypto_boringssl: no
>   libngtcp2_crypto_picotls:   no
> Test:
>   CUnit:          no (CFLAGS='' LIBS='')
> Debug:
>   Debug:          no (CFLAGS='')
> Libs:
>   OpenSSL:        no (CFLAGS='' LIBS='')
>   Libev:          no (CFLAGS='' LIBS='')
>   Libnghttp3:     no (CFLAGS='' LIBS='')
>   Jemalloc:       no (CFLAGS='' LIBS='')
>   GnuTLS:         no (CFLAGS='' LIBS='')
>   BoringSSL:      no (CFLAGS='' LIBS='')
>   Picotls:        no (CFLAGS='' LIBS='')
> Examples:         no
> ```

If you use OpensSSL-3.0.3+quic, then you should replace:
lib/pkgconfig ===> lib64/pkgconfig

**Comment by dfandrich** [comment]
On Thu, Apr 21, 2022 at 10:01:20PM -0700, ShawnBian wrote:
> I just stickly follow below links to install curl with http3 from my centos8
> ,but it is failed :
> https://github.com/curl/curl/blob/master/docs/HTTP3.md
> 
> ***@***.*** curl]# LDFLAGS="-Wl,-rpath,/usr/local/openssl/lib" ./configure
> --with-openssl=/usr/local/openssl --with-nghttp3=/usr/local/nghttp3
> --with-ngtcp2=/usr/local/ngtcp2 --enable-alt-svc

This command isn't found on that page. Where did you get it? It's generally
better to manipulate PKG_CONFIG_PATH to specify the paths to the various .pc
files rather than specifying paths in the --with-* options.

> checking for libngtcp2_crypto_openssl options with pkg-config... no
> configure: error: --with-ngtcp2 was specified but could not find
> ngtcp2_crypto_openssl pkg-config file.

This error means that it couldn't find that pkg-config file. Try setting
PKG_CONFIG_PATH to point to where it is on your system.

**Comment by hzwyihao** [comment]
> thank you. I understand that should be replaced with the actual paths. but I don't know how to replace it or use what to replace it.
> 
> Since I don't know what somwhere1 and somewhere2 and somewhere3 refer to or mean for?
> 
> in my case , openssl is installed under the /usr/local/openssl , nghttp3 is installed under the /usr/local/nghttp3. I intend to install ngtcp2 under the /usr/local/ngtcp2
> 
> $ ./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"
> 
> if I make the configure like above , is that correct?

Probably openssl use lib64 instead of lib, while you use /usr/local/openssl/**lib**/pkgconfig to build ngtcp2

**Comment by jurisuk** [comment]
I have experienced something similar. NB: I am installing on Raspberry Pi OS (Debian). The error message I got was:
```
configure: error: --with-ngtcp2 was specified but could not find ngtcp2_crypto_quictls pkg-config file.
```

On my Ubuntu install, the path to pkg-config is `$somewhere1/lib64/pkgconfig`, so I was trying the same on the RPi OS. However, the OpenSSL file on RPi was placed in `$somewhere1/lib/pkgconfig`. Having corrected that (PKG_CONFIG_PATH) I got curl working with http3.

**Comment by Lxy12138** [comment]
OpensSSL-3.0.3+quic, replace lib/pkgconfig ===> lib64/pkgconfig when you build ngtcp2.

**Comment by echeng1514** [comment]
> > I am almost gonna give that up . this is really really confused and dont have detailed explaination
> > before give it up ,I will do the last try:
> > I just have done this configure one more time:
> > ./configure PKG_CONFIG_PATH=/usr/local/openssl/build/lib/pkgconfig:/usr/local/nghttp3/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,/usr/local/openssl/build/lib"
> > it seems still not work,right?
> > config.status: executing depfiles commands configure: summary of build options:
> > ```
> > Package version: 0.4.0-DEV
> > Library version: 2:0:0
> > Install prefix:  /usr/local
> > System types:
> >   Build:         x86_64-pc-linux-gnu
> >   Host:          x86_64-pc-linux-gnu
> >   Target:        x86_64-pc-linux-gnu
> > Compiler:
> >   C preprocessor: gcc -E
> >   CPPFLAGS:       
> >   C compiler:     gcc
> >   CFLAGS:         -g -O2
> >   C++ compiler:   g++
> >   CXXFLAGS:       
> >   LDFLAGS:        -Wl,-rpath,/usr/local/openssl/build/lib
> >   WARNCFLAGS:     
> >   WARNCXXFLAGS:   
> >   EXTRACFLAG:     -fvisibility=hidden
> >   LIBS:           
> > Library:
> >   Shared:         yes
> >   Static:         yes
> > Libtool:
> >   LIBTOOL_LDFLAGS: 
> > Crypto helper libraries:
> >   libngtcp2_crypto_openssl:   no
> >   libngtcp2_crypto_gnutls:    no
> >   libngtcp2_crypto_boringssl: no
> >   libngtcp2_crypto_picotls:   no
> > Test:
> >   CUnit:          no (CFLAGS='' LIBS='')
> > Debug:
> >   Debug:          no (CFLAGS='')
> > Libs:
> >   OpenSSL:        no (CFLAGS='' LIBS='')
> >   Libev:          no (CFLAGS='' LIBS='')
> >   Libnghttp3:     no (CFLAGS='' LIBS='')
> >   Jemalloc:       no (CFLAGS='' LIBS='')
> >   GnuTLS:         no (CFLAGS='' LIBS='')
> >   BoringSSL:      no (CFLAGS='' LIBS='')
> >   Picotls:        no (CFLAGS='' LIBS='')
> > Examples:         no
> > ```
> 
> If you use OpensSSL-3.0.3+quic, then you should replace: lib/pkgconfig ===> lib64/pkgconfig

Perfect answer
