### ISSUE TITLE
Build getting failed on version 7.82.0

### ISSUE THREAD

**Issue by Harishreddy01** [curl/curl#8734]
I am trying to build libcurl 7.82.0 latest version but ended up in the below error
rpm used - curl-7.82.0-2.0.cf.rhel8.src.rpm

linux/shared/libcurl/usbc_gnu_src/lib/vssh/libssh2.c:650:11: error: implicit declaration of function 'Curl_sha256it'; did you mean 'Curl_ssl_init'? [-Werror=implicit-function-declaration]
       if(!Curl_sha256it(hash, (const unsigned char *) hostkey, len))
           ^~~~~~~~~~~~~
           Curl_ssl_init
cc1.exe: some warnings being treated as errors

**Comment by bagder** [comment]
This is not a problem we've seen others have with our release. I recommend building curl from the original curl releases. For building RedHat sources, I suggest you ask in a RedHat forum for how they propose it should be done.

**Comment by bagder** [comment]
Do you get the same issue with a "real" release?
