### ISSUE TITLE
Issues with ftps through CONNECT

### ISSUE THREAD

**Issue by MarvinWinks** [curl/curl#8737]
Using curl executable, directory listings against several ftps sites stopped working as of version 7.77 of curl. I tried compiling and testing against each of the versions from 7.76 to 7.82.

On versions 7.77 and after, the TLS handshake completes successfully. But the directory listing does not return.

I also tried writing a simple main.cpp using libcurl. I am finding that starting with v7.77, CURLOPT_WRITEFUNCTION does not get called.

### I did this

I ran the curl executable to do a directory listing of an ftps site. Command-line options used:

  -vv
  -x <proxy>
  -u <username:password>
  --ftp-ssl
  --proxytunnel
  <ftp site with scheme as ftp://>

### I expected the following

The directory listing as output.

### curl/libcurl version

I tried several versions:
*Newest version that works: 7.76.1*
curl 7.76.1 (x86_64-unknown-linux-gnu) libcurl/7.76.1 OpenSSL/1.0.2zd zlib/1.2.11 libssh2/1.9.0
Release-Date: 2021-04-14
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

*Newest version tried (that does not work): 7.82.0*
curl 7.82.0 (x86_64-unknown-linux-gnu) libcurl/7.82.0 OpenSSL/1.0.2zd zlib/1.2.11 libssh2/1.9.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

### operating system

Linux <hostname redacted> 3.10.0-957.35.2.el7.x86_64 #1 SMP Wed Sep 18 05:51:28 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jay** [comment]
Is there a public server that we can use to reproduce?

**Comment by MarvinWinks** [comment]
Hi Jay,

No, they are all logins. I realize this severely limits your ability to diagnose. Are there any verbose logs that I can send you to help?

Jeff

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jay** [comment]
You can try [bisecting](https://github.com/curl/curl/wiki/how-to-git-bisect).

**Comment by MarvinWinks** [comment]
Using git bisect with good=curl-7_76_1 and bad=curl-7_77_0, the offending commit was `566b74a`.
