### ISSUE TITLE
http3(quiche): always timeout when reuse a http3 connection in pool which timeout once

### ISSUE THREAD

**Issue by Cering** [curl/curl#8764]
### I did this
- send http3(quiche) request with multi interface continuously, and try reusing connection in the pool, the major code like this: 
```c++
curl_multi_setopt(multi_handle, CURLMOPT_MAXCONNECTS, 10L);
std::vector<std::string> url_list; 
...
while(true) {
    for(auto url : url_list) {
        curl_easy_setopt(http_handle, CURLOPT_DEBUGFUNCTION, mycurl_debug);
        curl_easy_setopt(http_handle, CURLOPT_ALTSVC, "altsvc_cache.txt"); // try http3
        ...
        curl_multi_add_handle(multi_handle, http_handle);
        do {
            curl_multi_wait(multi_handle, NULL, 0, 10, &numfds);
            curl_multi_perform(multi_handle, &still_running);
            mycurl_process(multi_handle); // output curl info here, then call multi_remove() and easy_cleanup()
        } while(still_running); // force sync request
        sleep(5); 
    }
}
```
- if the connection is http/1.1 or http/2, it will work well
- however, when using http/3 from altsvc, if the request was failed because of timeout, thIS http3 connection still remain in pool
- after that, all requests with the same domain will try reusing the http3 connection in pool, and always get a timeout error
- the curl debug output info like this: 
> **curl_version() OUTPUT**
***libcurl/7.73.0 BoringSSL zlib/1.2.7 brotli/1.0.9 nghttp2/1.41.0 quiche/0.6.0***

> **FIRST HTTP3 REQUEST FROM ALTSVC**
New Request[1]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]:   Trying 52.55.120.73:443...
curl_debug[0]: Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
curl_debug[0]: Connected to www.litespeedtech.com (52.55.120.73) port 443 (#1)
curl_debug[0]: h3 [:method: GET]
curl_debug[0]: h3 [:path: /]
curl_debug[0]: h3 [:scheme: https]
curl_debug[0]: h3 [:authority: www.litespeedtech.com]
curl_debug[0]: h3 [accept: */*]
curl_debug[0]: h3 [alt-used: www.litespeedtech.com:443]
***curl_debug[0]: Using HTTP/3 Stream ID: 0 (easy handle 0x17c9c28)***
curl_debug[0]: Unknown alt-svc protocol "h3", skipping...
curl_debug[0]: Added alt-svc: www.litespeedtech.com:443 over h3-29
curl_debug[0]: Unknown alt-svc protocol "h3-Q050", skipping...
curl_debug[0]: Unknown alt-svc protocol "h3-Q046", skipping...
curl_debug[0]: Unknown alt-svc protocol "h3-Q043", skipping...
curl_debug[0]: Unknown alt-svc protocol "quic", skipping...
***curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact***
mycurl_process: https://www.litespeedtech.com/, curl_code: 0(No error), http_version: 30, total_time: 1.100166, connect_time: 0.873423, download_bytes: 1688, download_speed: 1534

> **REUSING HTTP3 CONNECTION AND SUCCESS**
New Request[5]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]: Found bundle for host www.litespeedtech.com: 0x17cc438 [can multiplex]
***curl_debug[0]: Re-using existing connection! (#1) with host www.litespeedtech.com***
...
curl_debug[0]: Using HTTP/3 Stream ID: 8 (easy handle 0x17c9c28)
curl_debug[0]: Got h3 for stream 4, expects 8
***curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact***
mycurl_process: https://www.litespeedtech.com/, curl_code: 0(No error), http_version: 30, total_time: 0.225826, connect_time: 0.000051, download_bytes: 1688, download_speed: 7502

> **FIRST TIME REUSING HTTP3 CONNECTION AND FAIL**
New Request[13]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]: Found bundle for host www.litespeedtech.com: 0x17cc438 [can multiplex]
***curl_debug[0]: Re-using existing connection! (#1) with host www.litespeedtech.com***
...
curl_debug[0]: Using HTTP/3 Stream ID: 18 (easy handle 0x17c9c28)
curl_debug[0]: Got h3 for stream 20, expects 24
***curl_debug[0]: Operation timed out after 5000 milliseconds with 0 bytes received***
***curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact***
mycurl_process: https://www.litespeedtech.com/, curl_code: 28(Operation timed out after 5000 milliseconds with 0 bytes received), http_version: 0, total_time: 4.999733, connect_time: 0.000050, download_bytes: 0, download_speed: 0 

> **THE FOLLOW UP REQUEST WILL ALWAYS TIMEOUT**
New Request[15]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]: Found bundle for host www.litespeedtech.com: 0x17cc438 [can multiplex]
curl_debug[0]: Re-using existing connection! (#1) with host www.litespeedtech.com
...
curl_debug[0]: Using HTTP/3 Stream ID: 1c (easy handle 0x17c9c28)
***curl_debug[0]: Operation timed out after 5000 milliseconds with 0 bytes received***
curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact
mycurl_process: https://www.litespeedtech.com/, curl_code: 28(Operation timed out after 5000 milliseconds with 0 bytes received), http_version: 0, total_time: 4.999625, connect_time: 0.000060, download_bytes: 0, download_speed: 0

### curl/libcurl version

```bash
curl 7.73.0 (x86_64-pc-linux-gnu) libcurl/7.73.0 BoringSSL zlib/1.2.7 brotli/1.0.9 nghttp2/1.41.0 quiche/0.6.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TrackMemory UnixSockets
```

### operating system

`Linux mylinux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Cering** [comment]
upload whole demo code and output info: 
- [demo.cpp.txt](https://github.com/curl/curl/files/8579229/demo.cpp.txt) (please rename to `demo.cpp`)
- [output.log](https://github.com/curl/curl/files/8579231/output.log)

**Comment by bagder** [comment]
We improve the HTTP/3 code a lot in every release so I would encourage you to try out the very latest curl version first, with an up-to-date quiche.

**Comment by Cering** [comment]
> We improve the HTTP/3 code a lot in every release so I would encourage you to try out the very latest curl version first, with an up-to-date quiche.

- Hello @bagder, I tried to update the curl and quiche to latest version like this: 
> curl 7.83.0 (x86_64-pc-linux-gnu) libcurl/7.83.0 BoringSSL zlib/1.2.7 brotli/1.0.9 nghttp2/1.41.0 quiche/0.12.0
Release-Date: 2022-04-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TrackMemory UnixSockets

- But it seems that the reusing connection timeout error still exist: 

> **FIRST TIME REUSING HTTP3 CONNECTION AND FAIL**
New Request[13]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]: Found bundle for host: 0xb6bdc8 [can multiplex]
curl_debug[0]: Re-using existing connection #1 with host www.litespeedtech.com
curl_debug[0]: Connected to www.litespeedtech.com () port 443 (#1)
curl_debug[0]: h2h3 [:method: GET]
curl_debug[0]: h2h3 [:path: /]
curl_debug[0]: h2h3 [:scheme: https]
curl_debug[0]: h2h3 [:authority: www.litespeedtech.com]
curl_debug[0]: h2h3 [accept: */*]
curl_debug[0]: h2h3 [alt-used: www.litespeedtech.com:443]
curl_debug[0]: Using HTTP/3 Stream ID: 18 (easy handle 0xa849b8)
curl_debug[0]: Got h3 for stream 20, expects 24
curl_debug[0]: Operation timed out after 5000 milliseconds with 0 bytes received
curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact
mycurl_process: https://www.litespeedtech.com/, curl_code: 28(Operation timed out after 5000 milliseconds with 0 bytes received), http_version: 0, total_time: 4.999173, connect_time: 0.000070, download_bytes: 0, download_speed: 0

> **THE FOLLOW UP REQUEST WILL ALWAYS TIMEOUT**
New Request[15]: https://www.litespeedtech.com/
curl_debug[0]: Alt-svc connecting from [h2]www.litespeedtech.com:443 to [h3-29]www.litespeedtech.com:443
curl_debug[0]: Found bundle for host: 0xb6bdc8 [can multiplex]
curl_debug[0]: Re-using existing connection #1 with host www.litespeedtech.com
curl_debug[0]: Connected to www.litespeedtech.com () port 443 (#1)
curl_debug[0]: h2h3 [:method: GET]
curl_debug[0]: h2h3 [:path: /]
curl_debug[0]: h2h3 [:scheme: https]
curl_debug[0]: h2h3 [:authority: www.litespeedtech.com]
curl_debug[0]: h2h3 [accept: */*]
curl_debug[0]: h2h3 [alt-used: www.litespeedtech.com:443]
curl_debug[0]: Using HTTP/3 Stream ID: 1c (easy handle 0xa849b8)
curl_debug[0]: Operation timed out after 5000 milliseconds with 0 bytes received
curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact
mycurl_process: https://www.litespeedtech.com/, curl_code: 28(Operation timed out after 5000 milliseconds with 0 bytes received), http_version: 0, total_time: 4.999152, connect_time: 0.000108, download_bytes: 0, download_speed: 0

**Comment by bagder** [comment]
I enabled quiche debug in quiche.c and then I get some extra logs that shows the QUIC connection is ... closed?

The last few lines before the timeout usually then look like below.

The ASCII sequence for the "reason" in the CONNECTION_CLOSE says `user aborted connection`.

~~~
curl_debug[0]: STATE: DO => DID handle 0x55b6c5bb7408; line 2145 (connection #1)
curl_debug[0]: STATE: DID => PERFORMING handle 0x55b6c5bb7408; line 2264 (connection #1)
quiche: 031631a83874dffcf2863d356fb33b26c915e323 rx pkt Short dcid=031631a83874dffcf2863d356fb33b26c915e323 key_phase=false len=450 pn=6
quiche: 031631a83874dffcf2863d356fb33b26c915e323 rx frm CRYPTO off=0 len=428
quiche: 031631a83874dffcf2863d356fb33b26c915e323 rx frm HANDSHAKE_DONE
quiche: 031631a83874dffcf2863d356fb33b26c915e323 dropped epoch 1 state
quiche: 031631a83874dffcf2863d356fb33b26c915e323 rx pkt Short dcid=031631a83874dffcf2863d356fb33b26c915e323 key_phase=false len=44 pn=8
quiche: 031631a83874dffcf2863d356fb33b26c915e323 rx frm CONNECTION_CLOSE err=0 frame=0 reason=[75, 73, 65, 72, 20, 61, 62, 6f, 72, 74, 65, 64, 20, 63, 6f, 6e, 6e, 65, 63, 74, 69, 6f, 6e]
curl_debug[0]: Operation timed out after 5000 milliseconds with 0 bytes received
curl_debug[0]: multi_done: status: 28 prem: 1 done: 0
curl_debug[0]: Connection #1 to host www.litespeedtech.com left intact
curl_debug[0]: Expire cleared (transfer 0x55b6c5bb7408)
mycurl_process: https://www.litespeedtech.com/, curl_code: 28(Operation timed out after 5000 milliseconds with 0 bytes received), http_version: 0, total_time: 5.000071, connect_time: 0.212821, download_bytes: 0, download_speed: 0

**Comment by Cering** [comment]
Hello, I'm back again.

For this issue, I found some useful info in quiche's docs(https://docs.quic.tech/quiche/h3/index.html#http3-protocol-errors):
> If an HTTP/3 error occurs, quiche will close the connection and send an appropriate CONNECTION_CLOSE frame to the peer

Once a http3 request is failed, the quiche will close the connection. But curl still keep the connection in pool and try reusing, that lead to a CONNECTION_CLOSE error and Operation timed out.
