### ISSUE TITLE
building with --disable-http-auth fails with "undefined reference to `Curl_allow_auth_to_host'"

### ISSUE THREAD

**Issue by michaelolbrich** [curl/curl#8772]
### I did this
configure with `--disable-http-auth`

### I expected the following
building curl shoud succeed

### curl/libcurl version
7.83.0

The problem is here: https://github.com/curl/curl/blob/685170b729a1b704233036381cc66b1275732af4/lib/http.c#L1920

This call to `Curl_allow_auth_to_host()` is not protected by a `CURL_DISABLE_HTTP_AUTH` check but the implementation of the function is.

**Comment by bagder** [comment]
Fixed in commit d7b970e46ba29a7e558e21d19f485977ffed6266
