### ISSUE TITLE
local_ip and local_port are not stored for failed connects

### ISSUE THREAD

**Issue by doekerqhtv** [curl/curl#8794]
local_ip is returning a blank in case when curl fails to connect
local_port is returning a zero in case when curl fails to connect

### I did this

$ curl -m1 -w "%{local_ip}:%{local_port}\n" https://www.google.com:8443
curl: (28) Failed to connect to www.google.com port 8443 after 732 ms: Operation timed out
:0

$ curl -m1 -w "%{local_ip}:%{local_port}\n" http://127.0.0.1:8443      
curl: (7) Failed to connect to 127.0.0.1 port 8443 after 0 ms: Connection refused
:0

### I expected the following

Expected IP address that was used to initiate connection.
Expected Source Port Number that was used to initiate connection.

### curl/libcurl version

curl 7.83.0

**Comment by bagder** [comment]
That info is not stored until after a successful connect. Many host names resolve to multiple addresses and curl can then have tried *multiple* connects so there would not be any single local port (or even IP) to report. Should it then report the last attempt only?

See also https://curl.se/docs/todo.html#Expose_tried_IP_addresses_that_f

**Comment by bagder** [comment]
Presumably, this would then also need to say if the PORT was UDP or TCP to support HTTP/3.

Currently, the only way for `curl_easy_getinfo()` to return a set of data (one or more results) to the caller is to create an `curl_list` linked list with "strings" returned, so one way to implement this feature could be to return a list of strings using a set format like maybe:

    SRC-IP:SRC-PORT:DST-IP:DST-PORT:PROTOCOL

**Comment by bagder** [comment]
I expanded the TODO document slightly now with more ideas and info from this issue. Since I don't think anyone is working on this or has shown any interest in doing so now, this issue will be closed within shortly.
