### ISSUE TITLE
--aws-sigv4 is missing the amz-content-sha256 header?

### ISSUE THREAD

**Issue by vlovich** [curl/curl#8810]
R2 from Cloudflare requires x-amz-content-sha256 to be present on every request. This is part of the SigV4 docs: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

> Note: The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. If there is no payload, you must provide the hash of an empty string.

### I did this
```
curl https://<account>.r2.cloudflarestorage.com/mybucket/myfile --user '<id>:<secret>' --aws-sigv4 "aws:amz:auto:s3"
```

When I use `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` as the content-sha256 then it seems to works (i.e. `x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`).

However, this is incorrect for POST requests which fail with:
```
<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided &apos;x-amz-content-sha256&apos; header does not match what was computed.</Message></Error>
```
since `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` is not the payload.

### I expected the following
A successful get and post.

### curl/libcurl version

```
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
Linux vlovich 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux
```

**Comment by jamshid** [comment]
I get that error even listing an AWS S3 bucket:

```
% docker run -ti curlimages/curl -v 'https://s3.amazonaws.com/X' -u 'X:X' --aws-sigv4 "aws:amz:auto:s3"  
*   Trying 52.217.236.192:443...
* Connected to s3.amazonaws.com (52.217.236.192) port 443 (#0)
...
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Server auth using AWS_SIGV4 with user 'X'
> GET /X HTTP/1.1
> Host: s3.amazonaws.com
> Authorization: AWS4-HMAC-SHA256 Credential=X/20220511/auto/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=9759b4858ad651f203e5b5c58ce5f61e0ec9591e2a037c53932c7222291f6243
> X-Amz-Date: 20220511T093443Z
> User-Agent: curl/7.83.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< x-amz-bucket-region: us-east-1
< x-amz-request-id: C4103CSY2PYJEBKJ
< x-amz-id-2: Gq4s6DKTpvI+4fHaMWvJSCgmuUi7GmPsrNWXrgXqAalBOW8kU1bkFYBiqqsgpGV2gpPwuQJwaIo=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Wed, 11 May 2022 09:34:43 GMT
< Server: AmazonS3
< Connection: close
< 
<?xml version="1.0" encoding="UTF-8"?>
* Closing connection 0
* TLSv1.2 (IN), TLS alert, close notify (256):
* TLSv1.2 (OUT), TLS alert, close notify (256):
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: x-amz-content-sha256</Message><RequestId>C4103CSY2PYJEBKJ</RequestId><HostId>Gq4s6DKTpvI+4fHaMWvJSCgmuUi7GmPsrNWXrgXqAalBOW8kU1bkFYBiqqsgpGV2gpPwuQJwaIo=</HostId></Error>%                 
```

**Comment by bagder** [comment]
Was this fixed with #9804? /cc @cbodley

**Comment by cbodley** [comment]
@bagder not quite! we still need to add this header to s3 requests that don't have it, as discussed in https://github.com/curl/curl/pull/8935. i'll follow up on that now that https://github.com/curl/curl/pull/9804 merged

**Comment by cbodley** [comment]
see https://github.com/curl/curl/pull/9995

**Comment by cbodley** [comment]
this should be resolved now that https://github.com/curl/curl/pull/9995 has merged

**Comment by jamshid** [comment]
Yay this works:
`docker run -ti curlimages/curl:8.00.1 -v 'https://s3.amazonaws.com/X' -u 'X:X'  --aws-sigv4 "aws:amz:us-east-1:s3"`
Using `auto` in place of the region name does not work though.

**Comment by onpaws** [comment]
> Yay this works: `docker run -ti curlimages/curl:8.00.1 -v 'https://s3.amazonaws.com/X' -u 'X:X' --aws-sigv4 "aws:amz:us-east-1:s3"` Using `auto` in place of the region name does not work though.

Finally a `curl` snippet that actually works on my S3 bucket, thanks! 🎉

With v7.81° I experienced issues, which seemed a bit surprising since according to [this](https://curl.se/libcurl/c/CURLOPT_AWS_SIGV4.html) I thought releases >= v7.75.0 should be supported. 

No clue what's happening but glad to see v8 working as I expected. Takk Daniel and contributors! 🥂

```
curl --aws-sigv4 "aws:amz:eu-west-2:s3" --user "AKI<redacted>:<redacted>" https://<redacted>.s3.eu-west-2.amazonaws.com
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: x-amz-content-sha256</Message><RequestId>RNZCTV58TT9AN5EF</RequestId><HostId><redacted></HostId></Error>
```


° Version details in case it's helpful
```
$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
