### ISSUE TITLE
incorrect initialization order for mbedtls

### ISSUE THREAD

**Issue by ajleite** [curl/curl#8812]
I am sorry if this is the wrong place to post but it appears that tiny-curl is being developed in private by many of the same people as curl (@bagder perhaps?).

`tiny-curl-7.79.1/lib/vtls/mbedtls.c` has the following passage (lines 445-453):

```
  mbedtls_ssl_init(&backend->ssl);
  if(mbedtls_ssl_setup(&backend->ssl, &backend->config)) {
    failf(data, "mbedTLS: ssl_init failed");
    return CURLE_SSL_CONNECT_ERROR;
  }
  ret = mbedtls_ssl_config_defaults(&backend->config,
                                    MBEDTLS_SSL_IS_CLIENT,
                                    MBEDTLS_SSL_TRANSPORT_STREAM,
                                    MBEDTLS_SSL_PRESET_DEFAULT);
```

This prevents any SSL activities from initializing properly because `mbedtls_ssl_setup` checks that `backend->config` has been initialized with min and max TLS versions to proceed, and that only happens in `mbedtls_ssl_config_defaults`.

This issue is not present in curl (ref: https://github.com/curl/curl/blob/master/lib/vtls/mbedtls.c#L508-L522). This initially led me to think I had corrupted my copy of tiny-curl myself. The code there is also better-organized and should probably be adopted directly for tiny-curl.

I've fixed the issue in my own build but I thought it might be helpful to others with the same use case if you could apply this fix. Thank you very much for your time!

**Comment by bagder** [comment]
tiny-curl is just a small patch set on top of ordinary curl, the mbedtls code is identical. It's just that we haven't done any tiny-curl release recently so you're probably looking at different curl versions. If this is fine in curl, then it will be fine in the next tiny-curl release as well.

**Comment by ajleite** [comment]
Thanks very much for the quick reply. I didn't realize this when I was looking at the git blame earlier but I now see that https://github.com/curl/curl/pull/8238 addressed this issue.

Sorry for the bother, and thank you for your hard work on this important project!
