### ISSUE TITLE
(🐞) Double quotes are removed from `-d`/`--data`/`--data-raw` on Windows

### ISSUE THREAD

**Issue by KotlinIsland** [curl/curl#8818]
### I did this
`curl -v -d '"a"'`

### I expected the following
`> Content-Length: 3`

### Instead I actually got
`> Content-Length: 1`

### curl/libcurl version

```
> curl -V
curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
Release-Date: 2021-09-22
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
```
### operating system
Windows 10 21H2

### FYI
On `curl 7.81.0 (x86_64-pc-linux-gnu)` this works correctly and doesn't remove the double quotes.

### Additional info
```powershell
> curl -v -d '"' "https://example.com"
curl: no URL specified!
```
Hmm, I think there is a url specified.

**Comment by jzakrzewski** [comment]
AFAIK Windows CMD does not consider single quotes as special, so you have to quote the parameters using double quotes and escape any double quotes that are a part of the parameters.
This is a shell thing, not a curl issue.

**Comment by jay** [comment]
The Windows command prompt does not use literal quotes like Unix shells do. You will have to double quote the argument and then escape inner double quotes with a backslash `\`. I made a program called [getargs](https://gist.github.com/jay/19aba48653bd591cf4b90eb9249a302c) that can show the arguments passed to it:

~~~
getargs -v -d '"' "https://example.com"

argv[0]: getargs
argv[1]: -v
argv[2]: -d
argv[3]: '' https://example.com
~~~

The command shell interpreter is removing the double quotes and keeping the single quotes, which is likely not what you intended.

~~~
getargs  -v -d '"a"'

argv[0]: getargs
argv[1]: -v
argv[2]: -d
argv[3]: 'a'
~~~

~~~
getargs -v -d "\"a\""

argv[0]: getargs
argv[1]: -v
argv[2]: -d
argv[3]: "a"
~~~

**Comment by KotlinIsland** [comment]
@jzakrzewski @jay This isn't using CMD, this is using PowerShell I didn't even bother using CMD.

CMD:
```cmd
> echo '"' a   b  '"'
'"' a   b  '"'

PS:
```powershell
> echo '"' a   b '"'
"
a
b
"
```

**Comment by KotlinIsland** [comment]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2

Same thing with a "Here String":
```powershell
> curl -v -d @"
"a"
"@ https://example.com

...
> Content-Length: 1
...
```

**Comment by KotlinIsland** [comment]
@jay Could you run getargs in Powershell?

**Comment by jay** [comment]
curl isn't a powershell script it's a command console program so powershell is passing the arguments to the command interpreter and may not do that correctly. I've tried to clarify the Windows quoting in the FAQ, see #8823.

In powershell I can do it but it's trickier, 
~~~
getargs  -v -d "\`"foo bar\`""
~~~

**Comment by KotlinIsland** [comment]
Ok, screw this, I have no idea what is going on.
```ps
> cmd /c echo '"b"'     a      "asdf"
" a asdf
> pwsh /c echo '"b"'     a      "asdf"
b
a
asdf
> python -c "import sys;print(sys.argv)" '"'   a    "asdf"
['-c', ' a asdf']
```
It's like there's secret layers of escaping that trigger under different conditions or something. Just seems like a mess of intuitive, unusable nonsense. 

@jay what's the output of `getargs` in powershell for:
```ps
> getargs '"'      a    "asdf"`
```

**Comment by jay** [comment]
> ```postscript
> > getargs '"'      a    "asdf"`
> ```

The last character is a backtick which is an escape in powershell which means it wants more input. Without the backtick `argv[1]:  a asdf`. To test more you will need to run the commands yourself.

**Comment by KotlinIsland** [comment]
Sorry, that backtick was a typo...

> Without the backtick `argv[1]: a asdf`. 

That's absolutely absurd.

> To test more you will need to run the commands yourself.

I have no idea how to build or run c programs.

Thanks for the help :)

**Comment by odegroot** [comment]
To help anyone else running into this:
This isn't an issue with curl or with Windows, it's an issue with how PowerShell passes arguments to non-PowerShell commands. This is what removes the quotes.

Details + explanation here: https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features#psnativecommandargumentpassing

The argument passing behaviour was changed in PowerShell 7.3. Upgrading PowerShell from 7.2 to 7.3 fixed the problem for me.
