### ISSUE TITLE
Cygwin curl 7.83.1 make install installs curl-config.1 twice so fails with already exists in DESTDIR

### ISSUE THREAD

**Issue by BrianInglis** [curl/curl#8839]
### I did this
Configure, build, and install *curl* in `DESTDIR`

### I expected the following
`DESTDIR` populated with built files

### What actually happened
`make install` `docs/curl-config.1` installed in *DESTDIR*`/usr/share/man/man1/` **twice** so install failed with message: 
`/usr/bin/install: cannot create regular file '.../usr/share/man/man1/curl-config.1': File exists` in *DESTDIR* - see log for config and install details: 
[curl-cygport-64-all-check.log](https://github.com/curl/curl/files/8683736/curl-cygport-64-all-check.log) - lightly sanitized
looked in docs/Makefile but no obvious rules to use MANS twice but under install-man1 there are two loops to install pages - any ideas about possible causes or workarounds? see: [build/docs/Makefile](https://github.com/curl/curl/files/8683829/Makefile.txt) and [curl-7.83.1-1-install.log](https://github.com/curl/curl/files/8683846/curl-7.83.1-1-install.log) - lightly sanitized

### curl/libcurl version
7.83.1

### operating system
Cygwin 3.3.4 under Windows 10 21H2

built with cyport 0.35.0, autoconf 2.71, automake 1.16.5

**Comment by bagder** [comment]
Is this a new bug or has this been in there for a while? I can't recall us having modified anything in this area for a long time so if something changed recently, it could be a tooling update causing it.

**Comment by BrianInglis** [comment]
7.83.0 was fine: just this update has the man install issue. 
I did not find any non-trivial differences (only .0->.1) between the generated `build/docs/Makefile`. 
When `make install` is run, runs `Making install in ../docs`:
` /usr/bin/install -c -m 644 .../curl-7.83.1-1.x86_64/src/curl-7.83.1/docs/curl-config.1 .../curl-7.83.1-1.x86_64/build/docs/curl.1 '.../curl-7.83.1-1.x86_64/inst/usr/share/man/man1'`
then `make-recursive`? runs `(cd docs && make install)`: 
`/usr/bin/install -c -m 644 .../curl-7.83.1-1.x86_64/src/curl-7.83.1/docs/curl-config.1 .../curl-7.83.1-1.x86_64/build/docs/curl.1 '.../curl-7.83.1-1.x86_64/inst/usr/share/man/man1'`
which appears to miss that the targets have already been installed!
