### ISSUE TITLE
Curl hangs pureftpd file listing

### ISSUE THREAD

**Issue by bcecchinato** [curl/curl#884]
Hi there !

I'm facing a weird issue on my server, and didn't found a way to solve it. I'm running a `pureftpd` server on `Debian 8.4`, and an app that uses plowshare to upload files on uptobox, or jheberg.

The issue is the following : when i start an upload with the plowup command, i'm unable to list directories on my ftp server. The connection hangs, until the upload is finished.

I've made further tests, and saw that it is not really plowup, but the curl command used to upload. For instance, the following command is launched : 
```bash
curl -vvv --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0" -F "upload_type=file" -F "sess_id=XXXXXXX" -F "srv_tmp_url=http://www57.uptobox.com/tmp" -F "file_1=@1Gio.dat;type=application/octet-stream;filename=1Gio.dat" -F "tos=1" -F "submit_btn=Upload" "http://www57.uptobox.com/cgi-bin/upload.cgi?X-Progress-ID=XXXXX&upload_id=XXXXX&js_on=1&utype=prem&upload_type=file" --show-error
```
The issue happens only when sending a file via a form using the -F option. If i download a file, then there is no issue.

I was using the version 7.31 of curl, and then tried with version 7.50-DEV. The issue seems to be same. The output of curl -V : 
```bash
curl 7.50.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

Why is curl blocking the listing on ftp ? This also occurs on sftp subsystem.

Regards,

**Comment by bagder** [comment]
Since this curl command has nothing to do with FTP, I can only assume that you're seeing some sort of drawback or limitation in the FTP server implementation. I think you should rather investigate the FTP end. A form based HTTP upload with curl is just sending data to a HTTP server that is formatted according to some rules. It does not and it cannot make any particular locks that would cause this. 

If you instead upload this with a browser or another tool you'll most probably see the same effect.

**Comment by bcecchinato** [comment]
hi @bagder and thx for the quick reply. I would agree with you if it was only affecting the ftp. But I also have the same issue if I try to connect using sftp. I also tried to change my client, but both Filezilla and Winscp failed to list directories.

When i launch the curl command, and run a listing in parallel, I get a timeout on the listing. If I kill the curl command, then it responds immediatly.

**Comment by bcecchinato** [comment]
@bagder I've found something interesting. If i limit the upload with the --limit-rate option, then its ok. I guess curl is using too much bandwith. I've added wondershaper to add a limit on upload, it seems to have solved my problem.

If this tells you something :)

**Comment by bagder** [comment]
It is just another strong hint that the problem is in the server/network end. curl sends exactly as fast as it can and is allowed by the peer and general network conditions. It sounds as if you're just seeing the network bandwidth from the server being starved out by the upload.

**Comment by bcecchinato** [comment]
Yeah that's what it seems. I don't have enought technical skills on network to understand this. But issue is closed.
