### ISSUE TITLE
CURL SSL certificate problem when AVAST HTTPS scanning enabled

### ISSUE THREAD

**Issue by rentanadviser** [curl/curl#8848]
### problem
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

### I did this
- CURL was working good with Avast HTTPS scanning enabled.
- also "ca-bundle.crt" manually updated from "https://curl.se/ca/cacert.pem"
- "C:\ProgramData\ca-bundle.crt" also updated (environment variable)
- same problem with other websites too, e.g. youtube
- Sent bug report to avast (probably avast side problem when re-signing intercepted connection)
- when "AVAST HTTPS scanning disabled" CURL worked as expected.

### curl/libcurl version
curl 7.82.0 (i386-pc-win32) libcurl/7.82.0

[curl -V output]
curl 7.82.0 (i386-pc-win32) libcurl/7.82.0 OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets

### operating system
Edition	Windows 10 Pro
Version	21H2
Installed on	‎4/‎10/‎2022
OS build	19044.1706

### cmd VERBOSE Test
curl.exe "https://curl.se/ca/cacert.pem" -o curl-ca-bundle.crt -v

### cmd output
* Connected to curl.se (151.101.193.91) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: C:\ProgramData\ca-bundle.crt
*  CApath: none
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [964 bytes data]
* TLSv1.2 (OUT), TLS header, Unknown (21):
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by jzakrzewski** [comment]
Avast intercepts HTTPs connections and replaces websites' certificates with its own. It adds the certificate to "popular" browsers and to the Windows Certificate Store but it knows nothing about the bundle. You'd have to manually add it there.

I really dislike this feature. They are basically doing a MITM, wchich HTTPS is designed to prevent, but, because they could install their certificate on your machine, you're supposed to not notice this.

**Comment by bagder** [comment]
This shows that curl works exactly as it is meant to: it detected a MITM so it failed the transfer.

**Comment by sebbu2** [comment]
If you want to explicitely allow that single MITM (but keep ssl verification), you can go to avast setting, go to the search bar, type "geek:area", then look for the mail shield section and export its certificate.
It is in der format, so you can convert it to pem and add it to cacert 😄 .

Note that the SSLKEYLOGFILE env variable also allow for MITM (or at least inspection).
