### ISSUE TITLE
Add cmake config file generation

### ISSUE THREAD

**Issue by Cyberunner23** [curl/curl#885]
It would be very nice if cURL would support [config file packages](https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#config-file-packages) so that people using cmake can easily incorporate cURL in their project. Incrporating cURL into a project would look something like:

```cmake
find_package(curl CONFIG REQUIERD)
add_executable(proj-using-curl ${SOURCE})

# "curl::" is a namespace
target_link_libraries(curl::curl)
```

Some examples can be found [here](https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file).

**Comment by bagder** [comment]
Asking for someone to do work for you here is not fruitful. This is an issue tracker for problems people are having. The best way to get a feature added that you miss is to get started on it and then reach out for help from the wider community, either on the curl-library mailing list or perhaps by submitting a first pull-request and asking for feedback, comments or help.
