### ISSUE TITLE
local hostname leak with NTLM authentication

### ISSUE THREAD

**Issue by bestrocker221** [curl/curl#8859]
Hi, I am pretty sure this is by design, but I do not see the real reason behind it.
While using curl with  `--ntlm` or `--negotiate`, the local hostname is sent out to the server.

This is seen in the `NTLMSSP_AUTH` packet.

Is this really needed? If so, I would be delighted to learn the reason.
It seems a bit like an unnecessary information leak.

### curl/libcurl version

```
curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11
```

### operating system
Debian 5.16.14

**Comment by bagder** [comment]
The host name is passed in the auth messaging, by design. Are you proposing we should rather invent a fake name to pass on? I don't know how much checking of the host name is actually done by real world servers.

NTLM is a horrible thing. Don't use it.

**Comment by bestrocker221** [comment]
I see that Firefox for example, sets the hostname to "WORKSTATION".
Quickly reading the protocol description, it does not mention the hostname we are referring to, the 'workstation name' can be optionally supplied, when using `negotiate` but also, that is not a default.

I did a couple of tests with the NTLM auth and a fake hostname and it does not seem to have any effect, also, the `nmap` ntlm enumeration script sets the hostname to "null", for example.

I think that setting the hostname to either "WORKSTATION" or "null" can be an option and would not leak by default the host hostname. Of course more testing is ideal.  Just a thought. 

Thanks for the work with curl!
