### ISSUE TITLE
Connection times out at 75% of --connnection-timeout

### ISSUE THREAD

**Issue by Nuru** [curl/curl#8876]
### I did this

```
time curl -v --connect-timeout 20  https://BD71190E2FE991E56354DF0200B85B61.gr7.us-east-1.eks.amazonaws.com
*   Trying 10.10.78.234:443...
* After 9997ms connect time, move on!
* connect to 10.10.78.234 port 443 failed: Connection timed out
*   Trying 10.10.81.137:443...
* After 4997ms connect time, move on!
* connect to 10.10.81.137 port 443 failed: Connection timed out
* Failed to connect to BD71190E2FE991E56354DF0200B85B61.gr7.us-east-1.eks.amazonaws.com port 443: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to BD71190E2FE991E56354DF0200B85B61.gr7.us-east-1.eks.amazonaws.com port 443: Connection timed out

real	0m14.998s
user	0m0.005s
sys	0m0.008s
```

### I expected the following

I expected `curl` to wait `--connection-timeout` seconds for the connection to succeed. Instead it waits half that time, then retries the connection waiting 1/4 of the `connection_timeout`, then quits.

### curl/libcurl version

Current version for Debian 11.3:

curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

### operating system

Debian 11.3
Linux 8024f36bbeba 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is done on purpose, so that curl doesn't "waste" the entire timeout time on the first address when it has multiple ones to try within the given time-out. Then it has an algorithm to rather continue to the next to try that as well and so on.

**Comment by Nuru** [comment]
> This is done on purpose, so that curl doesn't "waste" the entire timeout time on the first address when it has multiple ones to try within the given time-out. Then it has an algorithm to rather continue to the next to try that as well and so on.

`--connect-timeout` is documented as a time limit on the connection phase, so `curl` should use up that amount of time trying to connect, not quit 25% early. If the target host has 2 addresses, I am OK with it using 50% of the time on the first one and 50% of the time on the second one, but not this current behavior. The current behavior makes more sense when you only set `--max-time`, in that it reserves some time for the actual connection, but not when you explicitly set only `--connect-timeout`.

Also, for people who might find this via search, note that in `curl 7.64.1` (which ships with MacOS), when you specify `--connect-timeout` with `--retry` and the connection times out, it is not retried. Same when you specify `--max-time`.

**Comment by bagder** [comment]
> curl should use up that amount of time trying to connect

The timeout is the maximum time it is allowed to spend trying. It doesn't mean that it *must* spend that time.

We've previously experimented with improving the timeout handling for multiple addresses and I would still be open for it if someone brings something better.

**Comment by Nuru** [comment]
> The timeout is the maximum time it is allowed to spend trying. It doesn't mean that it _must_ spend that time.

The standard behavior across all flavors of Unix is that setting a timeout tells the underlying function not to quit before (approximately) that amount of time elapses unless it has some other reason to believe the operation has failed in a way that waiting longer will not resolve. If I expect an operation to take 60 seconds and I want to allow for it, I set a timeout of 60 or 65 seconds. With `--connect-timeout` I need to set it to 80 or 87 seconds when there are 2 addresses, but only 60 or 65 when there is 1 address. That is highly inconvenient, since it means I how have to figure out how many addresses the host has in order to set the timeout correctly. 

At the very least, this behavior is unexpected and should be more explicitly documented.

I propose that `--connect-timeout` be evenly divided among addresses rather than use some exponential scheme, with an option to use the entire time trying to connect to the first address.

**Comment by bagder** [comment]
I recall someone who said:

> We've previously experimented with improving the timeout handling for multiple addresses and I would still be open for it if someone brings something better.

This is not a bug but there's certainly room for improvement.

**Comment by Nuru** [comment]
@bagder wrote:
>This is not a bug but there's certainly room for improvement.

Can we keep this open as a feature request?

**Comment by bagder** [comment]
We only use this issue tracker for (active) bugs, features/ideas/suggestions are listed in `docs/TODO` and long-standing bugs in `docs/KNOWN_BUGS`.

A little over a year ago I propose this approach: #6814
