### ISSUE TITLE
CURLOPT_WRITEFUNCTION man page: improvement

### ISSUE THREAD

**Issue by XianwuLin** [curl/curl#8878]
https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

It should be pointed out in this example that mem->response needs to be free.

the memory is malloc by ptr, and then, there is nowhere to free this piece of memory.

I know that free memory is a common sense，but there should be additional tips for newbies to prevent unnecessary mistakes.

**Comment by jay** [comment]
I disagree, the EXAMPLE section in the doc is just meant to show how each option works.

**Comment by XianwuLin** [comment]
But like this man page: https://curl.se/libcurl/c/curl_slist_append.html, it has clean job(curl_slist_free_all).

**Comment by danielgustafsson** [comment]
> But like this man page: https://curl.se/libcurl/c/curl_slist_append.html, it has clean job(curl_slist_free_all).

That's IMO a different case as the man page itself is documenting an API for allocating memory which should be freed in a specific way, CURLOPT_WRITEFUNCTION is not.
