### ISSUE TITLE
New summed-up timings from 7.56.0 gets pretty useless 

### ISSUE THREAD

**Issue by jarthod** [curl/curl#8892]
### I did this

After I upgraded libcurl from 7.50.3 to 7.68.0 I noticed this change in timings (#1602) which sums up times for all redirect requests instead of only returning the final request times. Although I understand this change I believe it leads to quite a lot of information loss and some of these numbers do not really mean anything now. Here is an example:

```
> curl -w "\n\nRedir: %{time_redirect}\n  DNS: %{time_namelookup}\n  TCP: %{time_connect}\n  TLS: %{time_appconnect}\nStart: %{time_starttransfer}\n ----------\nTotal: %{time_total}\n" -ILk http://rbx.updn.io
HTTP/1.1 301 Moved Permanently
[...]
Location: https://rbx.updn.io/
[...]

HTTP/2 200 
[...]

Redir: 0.471983
  DNS: 0.002144
  TCP: 0.472127
  TLS: 0.481746
Start: 1.189250
 ----------
Total: 1.189551
```

In this example there is one request to an http endpoint redirecting to an https endpoint. We can tell how much time was spent during the first redirection (with no details), for DNS time we have the sum which is acceptable although we can't tell what time is from the first or second query. But the problem starts with TCP and TLS time which are counted from the start because now we have the sum of connection time from 2 requests and the sum of handshake time from **only one** request (the second). So if we try to make a difference now we can't tell how long the hanshake took (here the difference would be about 9ms which is ridiculous and not representative of reality) and this difference can even be negative in some cases.

At least if we were summing the duration of each step we would still get the time of the one TLS hanshake (which was about 460ms), but here it's totally lost. So in the end we have the total time and redirection time which is fine, the DNS time which is a sum but still acurate, and all the others are pretty much inaccurate unless we're in a specific case where all timings are present and all requests successful.

### I expected the following

With a previous version of curl (7.50.3) we were getting these numbers (with a similar network latency):
```
Redir: 0.459
  DNS: 0.000
  TCP: 0.228
  TLS: 0.465
Start: 0.692
 ----------
Total: 1.152
```

Don't get me wrong, I'm not saying this change is bad for me and so it needs to be reverted, but I would like to open a discussion because it seems like a regression in acuracy and usefulness IMO, which could be very confusing. It might has been missed because the initial ticket was speaking about DNS time only (#522). Or maybe I am missing something here?

### Context

To give a bit more context about how I'm using this, I use libcurl in my monitoring service and produce performance charts like this:
![image](https://user-images.githubusercontent.com/201687/169534887-19fc3292-c000-44cd-a612-f0aabb4536fe.png)

Where I tried to put as much details as offered by libcurl to provide my clients with valuable metrics. In this screenshot you can see the Tokyo server is actually showing the metrics I gave in the example above (I'm using it to try 7.68.0). I was trying to think about how I could change this visualisation to make use the new time format, even if it means loosing the redirection split and the details on the last query (showing only sum), but even if I try showing just a global sum with no details, it would still get invalid results for TLS handshake and other step in some cases (connection errors, etc..)

One thing I could do in my case is stop using curl redirect and implement the redirection on my end (so I would get timings for each requests independently), but by doing so I expose myself to a more brittle implementation as opposed to curl's battle-tested one. Also it would be acklowledging that libcurl has regressed on this front and make command line debugging harder, so I would prefer to help improving it for everybody :)

### My take

I don't have any good suggestion on what to change here at the moment. Ideally for my use-case what I would prefer is to get the timings for each requests separately (this way there's no ambiguity, people can sum or average however they want). But I suppose that would be a big change and introduce more complexity.

One option which would avoid the summing problem I discussed here could be to return time difference with the previous step (so only handshake time and not time from start) for all steps after DNS, this way the sum would preserve valid values. But it would be a breaking change for a lot of integrations so maybe not desirable, also it would still mean no way to know which time was spend in which request (the global redirection time being impossible to split again).

Maybe the recommendation for this case should be to let people implement redirection on their end? in which case do you have a recommendation on pattern to follow, weird cases to handle, sample code, etc? in order to match curl's behavior as closely as possible.

@joshhe if you any input on the matter as you wrote #522 please let us know!

### curl/libcurl version

Basically any version above `7.56.0` and below `7.81.0` (highest I tested). The above example is tested with:
```
> curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### operating system

Mostly Ubuntu 20.04.4 LTS:
```
Linux tok.updn.io 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
But also tested on 22.04 with curl 7.81.0.

**Comment by bagder** [comment]
This is not something we will back out now anyway almost 5 years later. I would advice that you either work your way around it or work on providing a fix/update that make things better.

**Comment by jarthod** [comment]
Yes sure, that's why I'm not asking to back out but rather to improve this to make it more meaningful for redirects. For my situation I am gonna implement the redirect on my end anyway as I don't see any better option for the moment, this way I will have more detailed and reliable metrics. But the the general curl use-case I am sure what would be best so if you feel ok with the current behavior we can sit on it for the moment and wait until more people comment on this.

**Comment by bagder** [comment]
This is not a bug and I'm open for ways and suggestions on how to improve this for the future.

**Comment by jarthod** [comment]
Ok :+1:
