### ISSUE TITLE
LDAP: updated documentation per #878 changes

### ISSUE THREAD

**Issue by snikulov** [curl/curl#890]
I've implemented usage of different auth methods for WinLDAP in #878

I've expecting documentation changes per code change

7.50.0-DEV (Windows)

**Comment by snikulov** [comment]
@bagder Daniel, could you please assign this on me? Thank you.

**Comment by snikulov** [comment]
PR #891 submitted.

**Comment by bagder** [comment]
This is now PR #891 instead.
