### ISSUE TITLE
multi_wait() ignores Curl_poll() errors

### ISSUE THREAD

**Issue by piru** [curl/curl#8921]
`multi_wait()` ignores the potential error from `Curl_poll()` at https://github.com/curl/curl/blob/d67f41acd3c7c5f6f0ce46ae9a1c1db1457b90d3/lib/multi.c#L1315

If `Curl_poll()` returns immediately the function will then return `CURLM_OK` right away without performing any waiting. This will lead `curl_multi_poll()`/`curl_multi_wait()` to return immediately as well. Effectively this will lead to  a busyloop as there is no status returned that would lead to terminating a loop of a typical `curl_multi_perform()`  + `curl_multi_poll()` app, at least if the app doesn't bail out once the connections are completed (`still_running == 0` doesn't lead to loop termination).

### I did this

Had condition where `poll()` (or `select()` if using `poll()` emulation) return a permanent error without waiting.

### I expected the following

`curl_multi_poll()` / `curl_multi_wait()` to return an error if `Curl_poll()` fails.

The question is what error to return though as none of the `CURLM_` errors seem to fit the bill.

### curl/libcurl version

7.83.1

### operating system

This is a generic issue, but it is likely more likely to get triggered on specific platforms.

**Comment by bagder** [comment]
I don't think all poll/select errors are permanent though, are they? Should all underlying errors make curl_multi_poll()/wait() return error?

**Comment by piru** [comment]
```
ERRORS
       EFAULT fds  points  outside the process's accessible address space.  The array given as
              argument was not contained in the calling program's address space.

       EINTR  A signal occurred before any requested event; see signal(7).

       EINVAL The nfds value exceeds the RLIMIT_NOFILE value.

       EINVAL (ppoll()) The timeout value expressed in *ip is invalid (negative).

       ENOMEM Unable to allocate memory for kernel data structures.
```
Indeed, `EINTR` probably should not be considered fatal.

**Comment by piru** [comment]
lib/easy.c `wait_or_timeout()` seems to have the same issue btw
https://github.com/curl/curl/blob/a77d14d22ae93aa15670522e453f78744649b8cc/lib/easy.c#L509

lib/asyn-ares.c `waitperform()` as well. `waitperform()` result is not checked, which seems to be wrong as well.
https://github.com/curl/curl/blob/a77d14d22ae93aa15670522e453f78744649b8cc/lib/asyn-ares.c#L342
