### ISSUE TITLE
curl: (56) Failure when receiving data from the peer when running the service as "System"

### ISSUE THREAD

**Issue by bhupeshpant19jan** [curl/curl#8946]
The issue is with the libCurl default behavior when running as a standard user Vs when running as a System user. 
Our test application works as expected when I run the application as the standard user but when I trigger the application as "System" the application fails to get the response from our server.

I have enabled the verbosity flag on the curl calls and there we are able to clearly see that the failure is happening at the “close_notify” event. As far as I understand, this is a non-essential protocol to signal the end of the response and thus close any further communication Both Client and server need to respect this. 

```
schannel: client wants to read 16384 bytes
* schannel: encdata_buffer resized 17408
* schannel: encrypted data buffer: offset 0 length 17408
* schannel: server closed the connection
* schannel: encrypted data buffer: offset 0 length 17408
* schannel: encrypted data buffer: offset 0 length 17408
* schannel: decrypted data buffer: offset 0 length 4096
* schannel: schannel_recv cleanup
* schannel: server closed abruptly (missing close_notify)
* Closing connection 0
* schannel: shutting down SSL/TLS connection with sharedeus2.eus2.attest.azure.net port 443
* schannel: clear security context handle
failed with [GetCert] Request Failed. Request Id: 0886ad2c-4542-4e85-8aa0-1c7253156b2e, Error: Data creation failure, Details: Client Api failed for: https://abcdefghijk.com/xyz/test?api-version=2020-10-01, with Failure. Desc: **Failed sending curl request with error: Failure when receiving data from the peer**

```

I am able to replicate this even in the system using the curl command for the same server endpoint. Below is the output for the same.

```
D:\Windows\system32>curl -X POST -H "Content-Type: application/json, Connection: close " -d '{"": ""}' -v --ignore-content-length https://abcdefghijk.com/xyz/test?api-version=2020-10-01
curl -X POST -H "Content-Type: application/json, Connection: close " -d '{"": ""}' -v --ignore-content-length https://abcdefghijk.com/xyz/test?api-version=2020-10-01
curl: (3) [globbing] unmatched close brace/bracket in column 1
Note: Unnecessary use of -X or --request, POST is already inferred.
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0* Trying 20.40.225.60...
* TCP_NODELAY set
...
* schannel: SSL/TLS connection with https://abcdefghijk.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> POST /attest/sevsnpvm?api-version=2020-10-01 HTTP/1.1
> Host: https://abcdefghijk.com
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: application/json, Connection: close
> Content-Length: 3
>
} [3 bytes data]
* upload completely sent off: 3 out of 3 bytes
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: server closed the connection
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 0 length 4096
* schannel: schannel_recv cleanup
* schannel: server closed abruptly (missing close_notify)
100 3 0 0 100 3 0 3 0:00:01 --:--:-- 0:00:01 13
* Closing connection 0
* schannel: shutting down SSL/TLS connection with https://abcdefghijk.com port 443
* schannel: clear security context handle
curl: (56) Failure when receiving data from the peer
D:\Windows\system32>
```

At this point I am not sure, what is instigating this difference in behavior, and/or does it have to do anything with the server behavior?  

Is there anything we can do to ensure, that connection abrupt cancellation can be handled by the client or server don't do abrupt connection closure?

At a high level, I have 2 questions,

1. why is the server abruptly closing the connection without appropriately signaling the client? I probably need more details on "schannel: server closed abruptly (missing close_notify)" to understand the behavior better.
2. What is causing the difference in behavior, when running the application/command as a user Vs as a system?

This issue seems similar to this one: https://github.com/curl/curl/issues/4427 but it is different in a way that it is reproducible only in cases when the application is triggered with certain user type.

**Comment by jay** [comment]
What version of libcurl? Use curl_version() to get the version. Can you give us a way to reproduce?

**Comment by bhupeshpant19jan** [comment]
The version is 7.61.
@bagder , those post params are just dummy to as the actual params are lengthy and I was able to replicate the issue with these ones as well.

**Comment by vszakats** [comment]
Is it possible that there are two different `curl.exe`s, one with version 7.55.1 (as seen in OP) and another with 7.61 (in https://github.com/curl/curl/issues/8946#issuecomment-1143646580), perhaps with different SSL backends/features or other config differences?

**Comment by jay** [comment]
> Is there a way to send no certs in the client auth? I have confirmed with the server, they only do the client auth if the client certs are present otherwise, it passes the auth. If the client cert is passed and it can't be validated, the connection would still fail.

Sounds like you are affected by #2262. Older versions of libcurl with schannel will automatically attempt to locate a client certificate and send it to the server. Try the latest libcurl.

**Comment by bagder** [comment]
No response but presumed to already be fixed, closing.
