### ISSUE TITLE
SET_ERRNO macro in Windows should likely map to _set_errno

### ISSUE THREAD

**Issue by jay** [curl/curl#895]
In lib/curl_setup_once.h there is [this code](https://github.com/curl/curl/blob/curl-7_49_1/lib/curl_setup_once.h#L438-L449):

``` c
/*
 * Macro ERRNO / SET_ERRNO() returns / sets the NOT *socket-related* errno
 * (or equivalent) on this platform to hide platform details to code using it.
 */

#if defined(WIN32) && !defined(USE_LWIPSOCK)
#define ERRNO         ((int)GetLastError())
#define SET_ERRNO(x)  (SetLastError((DWORD)(x)))
#else
#define ERRNO         (errno)
#define SET_ERRNO(x)  (errno = (x))
#endif
```

Windows has a CRT that uses errno, and you can set it with [_set_errno](https://msdn.microsoft.com/en-us/library/hf1920a7%28v=vs.80%29.aspx). Though it is supposedly compatible with all of Windows, early versions of SDK don't seem to have the prototype. In VC6 (earliest I have) if the static library is used the errno is a global variable and you can set it directly. Update: _set_errno is available starting in VS2005.

[SetLastError](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680627%28v=vs.85%29.aspx) is for the Windows API (which the CRT calls internally) and afaik does not match up with errno. When we do stuff like `SET_ERRNO(ERANGE);` then in Windows it becomes SetLastError(ERANGE) and I'm pretty sure that's not correct.

**Comment by bagder** [comment]
Without knowing a lot about these details your arguments seem reasonable to me. But if `_set_errno` is the right choice to *set* errno, isn't [_get_errno](https://msdn.microsoft.com/en-us/library/wwfcfxas(v=vs.80).aspx) then the proper call to *get* it?

**Comment by jay** [comment]
No, errno is in thread-local storage now in most cases and is usually defined by stdlib.h or errno.h to something like this:
~~~c
#define errno   (*_errno())
~~~
If < VS2005 errno is a static variable, but I assume the compiler somehow is storing it thread safe when the threaded version of the CRT is used.

Therefore this should be fine in any case:
`#define ERRNO         (errno)`

Unfortunately SET_ERRNO won't be as simple. Original mingw doesn't have _set_errno in its crt import lib and less than <VS2005 and I assume neither do some older compilers. This is actually important though because certain versions of the CRT don't have _set_errno. The appropriate way would probably be to detect it dynamically. This way if mingw built curl is run on a system using a more recent default CRT with _set_errno (typical) it will properly use it.

**Comment by bagder** [comment]
so @jay, you think we can land a fix or should we close?

**Comment by jay** [comment]
I tested all the way back to Windows 2000 CRT (v6.1.8637.0, apparently the same as in Windows ME) and I can set errno in the CRT using just `errno = num`. I've also reviewed the CRT sources for the versions of Visual Studio that I have and `_set_errno` is just basically errno = value, errno defined as (*_errno()) as usual. So I'm pretty baffled why they added _set_errno.

I think if possible we should get rid of ERRNO/SET_ERRNO and just use errno. Windows has the errno for the CRT and GetLastError for the WinAPI, why conflate them. There's also [SOCKERRNO/SET_SOCKERRNO](https://github.com/curl/curl/blob/curl-7_50_3/lib/curl_setup_once.h#L424-L435) which seems [helpful](https://msdn.microsoft.com/en-us/library/windows/desktop/ms737828%28v=vs.85%29.aspx) though.

Any opinions here?

/cc @gvanem since ca1b34b
/cc @yangtse since d21e4eb
