### ISSUE TITLE
Sftp key authentication 

### ISSUE THREAD

**Issue by ssonata** [curl/curl#8955]
Curl version:7.47.1
 sftp in libcurl  being used.
Other than rsa key (ecdsa,dsa) are not connected.
How can habdle this?
I use this options
CURLOPT_SSH_AUTH_TYPES
CURLOPT_USERNAME
CURLOPT_SSH_PRIVATE_KEYFILE
CURLOPT_KEYPASSWD

**Comment by bagder** [comment]
> Curl version:7.47.1

That 6+ years old. I would recommend using a more modern version, and also a more modern version of the ssh library involved.

**Comment by bagder** [comment]
No response, closing.
