### ISSUE TITLE
FeatureRequest: support multiple proxy servers

### ISSUE THREAD

**Issue by peterlaser** [curl/curl#896]
###
1. Create pac file like this:
function FindProxyForURL(url, host)
{
	return "PROXY PROXY1:3128;PROXY PROXY2:3128";
}
2. Use the pac script as proxy in client hosts.
3. Run App/libcurl to connect to server side through the proxy configuration.

### I expected the following
App is able to connect to server through the proxy1, if the proxy1 is N/A, then failover to proxy2

### curl/libcurl version
7.49.1
[curl -V output perhaps?]

### operating system
All

Note:
There was a email thread discussed about it. https://curl.haxx.se/mail/archive-2000-11/0032.html

**Comment by bagder** [comment]
Thanks! I agree that this is a nice suggestion for a feature that would fit nicely within libcurl. But as this is not a feature request tracker, I will add the idea to the `TODO` file and close this entry in a near future unless someone intends to start working on this feature soonish.
