### ISSUE TITLE
curl: (58) could not parse PKCS12 file error

### ISSUE THREAD

**Issue by mikeduglas** [curl/curl#8966]
### This script works as expected in curl v7.78.0:
curl.exe --request POST --url "https://api.mybank.com:8443/prod/tokens/v2/oauth" ^
--header "authorization: Basic xxxxxxxx==" ^
--header "accept: application/json" ^
--header "content-type: application/x-www-form-urlencoded" ^
--header "rquid: xxxxxxxx" ^
--header "x-ibm-client-id: xxxxxxxx" ^
--data "grant_type=client_credentials&scope=https://api.mybank.com/qr/order.create" ^
--cert "xxxxxxxx.p12:xxxxxxxx" ^
--cert-type "P12"

### Same script in any newer curl version starting from 7.79.0 produces following error:
curl: (58) could not parse PKCS12 file, check password, OpenSSL error error:0308010C:digital envelope routines::unsupported

### curl/libcurl version

[curl 7.83.1 (i386-pc-win32) libcurl/7.83.1 OpenSSL/3.0.2 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 ngtcp2/0.5.0 nghttp3/0.4.1 libgsasl/1.10.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets]

### operating system
Windows 7, 10, 11

**Comment by bagder** [comment]
That sounds like OpenSSL not liking the input. Did you use the same OpenSSL version with both curl versions you tested?

**Comment by mikeduglas** [comment]
curl -V reports:

7.78.0: OpenSSL/1.1.1k (only this works)
7.79.0: OpenSSL/3.0.0
7.80.0: OpenSSL/3.0.0
7.83.1: OpenSSL/3.0.2

**Comment by mikeduglas** [comment]
Same error in 7.84.0, OpenSSL/3.0.4. Should I repost this in OpenSSL GitHub repo?

**Comment by OrkhanAlikhanov** [comment]
I could not enable legacy support in openssl or I could not make curl use it, either way my app was not working. I ended up converting pkcs file to the new format after reading @jay's response carefully. https://stackoverflow.com/a/72600724/5555803 answer helped me to do that
