### ISSUE TITLE
curl: (6) Could not resolve host: https://port.ping.pe/

### ISSUE THREAD

**Issue by Illegal-Services** [curl/curl#8967]
It happen that curl gives me a (6) error when I think it shouldn't, and if I'm running do the same request right after, it will just work fine.
Is there any reason for this? I'm just trying to understand why it does that.

I also forgot to mention:
1. This issue is NOT specific to "https://port.ping.pe/", it's happening randomly, on any host.
2. This issue is at least for me, impossible to reproduce, and RARE.

**Comment by Illegal-Services** [comment]
For the curious, that's one of the way I've catched several times them:

![Illegal_Services_2022-06-06_12-55](https://user-images.githubusercontent.com/62464560/172147910-acd22838-ce09-4665-9b69-4b07dbfaeaca.png)

code:
```bat
                for /f "tokens=1-3delims=`" %%D in ('curl.exe -fIks -X GET -A "!user_agent!" "!url_src!" --connect-timeout 0 --max-time 60 -w "%%{exitcode}`%%{http_code}`%%{redirect_url}"') do (
```

**Comment by Illegal-Services** [comment]
Just restarted the scan on this and got the problem again, on a different host ...

**Comment by Illegal-Services** [comment]
i just ran again the scan and again got "https://port.ping.pe/" as '6_000'

**Comment by bagder** [comment]
To me, this sounds like a problem outside of curl.

**Comment by bagder** [comment]
I think this because nobody else is reporting name resolver problem and we have not modified those areas in a long time.
This said, you didn't say which curl version you're using so maybe that's just a buggy release.

Without much more details I have no idea what this is happening to you.

**Comment by jay** [comment]
I don't see how this is a curl issue. You can investigate further by monitoring DNS in Wireshark.

**Comment by mrmusa24** [comment]
i need install command ubuntu 22.04
