### ISSUE TITLE
Progress function not called on a paused transfer

### ISSUE THREAD

**Issue by dwwoelfel** [curl/curl#8983]
### I did this

Used the multi socket interface to start a transfer and returned `CURL_WRITEFUNC_PAUSE` from the `CURLOPT_WRITEFUNCTION` callback after downloading some data.

### I expected the following

I expected the `CURLOPT_PROGRESSFUNCTION` callback to be called until I unpaused the handle, but it was only called ~5 times.

I was able to replicate this with a small example program at https://github.com/dwwoelfel/curl/blob/pause/docs/examples/ephiperfifo.c, which slightly modifies the default epoll example to pause the handle. The diff from the official example is https://github.com/curl/curl/compare/master...dwwoelfel:pause

### curl/libcurl version

curl 7.84.0-DEV (x86_64-pc-linux-gnu) libcurl/7.84.0-DEV OpenSSL/1.1.0l
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL threadsafe-init TLS-SRP TrackMemory UnixSockets

### operating system

```
uname -a
Linux host 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
```

**Comment by bagder** [comment]
The [CURLOPT_PROGRESSFUNCTION man page](https://curl.se/libcurl/c/CURLOPT_PROGRESSFUNCTION.html) says:

> If you transfer data with the multi interface, this function will not be called during periods of idleness unless you call the appropriate libcurl function that performs transfers.

A paused transfer is idle and you typically will not call libcurl for those transfers and thus it won't call the progress callback in that state. This is by design.

**Comment by dwwoelfel** [comment]
Thanks for the reply.

> A paused transfer is idle and you typically will not call libcurl for those transfers and thus it won't call the progress callback in that state. 

How does one unpause the transfer, since `curl_easy_pause` must be called in a callback? Is there some function that will trigger a callback?

**Comment by jay** [comment]
> How does one unpause the transfer, since `curl_easy_pause` must be called in a callback? Is there some function that will trigger a callback?

You don't have to call it in a callback. Is there documentation that says that? You do have to call it from the same thread handling the transfer though.

I think the way the progress function is explained in curl_easy_pause doc is misleading and I've proposed a clarification in #9015.
