### ISSUE TITLE
curl_mime_filedata uploads the wrong binary file

### ISSUE THREAD

**Issue by Frozen1084** [curl/curl#9011]
I use libcurl.dll and refer to the smtp-mime.c example to send from gmail to another gmail. if a text attachment is sent, the sha1 value of the download will not change.
If a binary attachment is sent, such as a zip or an image, the file is tampered with. It seems that curl_mime_filedata still reads it as text and inserts the new characters.

This screenshot is a comparison, between the original image (260KB), and the downloaded attached image (263KB). You can see that "0D" has been inserted between "38 32 0A FF"
https://i.imgur.com/SSAc449.png

Sorry, I'm new to programming and I can't tell if this is a lack of setting certain options that is causing this problem, or if this is a gmail problem, or if this is a bug?

**Comment by dfandrich** [comment]
smtp-mime.c deals with text attachments only, whereas zip files or (most)
images are binary. Your code needs to deal with that appropriately, such as
base64 encoding the data. Take a look at curl_mime_encoder(3).

**Comment by Frozen1084** [comment]
> 

Many thanks! I think we should add curl_mime_encoder to the example.
