### ISSUE TITLE
The Zuul CI jobs are gone

### ISSUE THREAD

**Issue by bagder** [curl/curl#9026]
According to https://curl.zuul.vexxhost.dev/builds, the last curl Zuul CI build ran on June 12 but we've had numerous PRs and commits since then that should have triggered jobs there!

/cc @mnaser

**Comment by bagder** [comment]
Different than #7522 because this time they don't seem to run at all.

**Comment by bagder** [comment]
We need to transition away the remainder of the Zuul jobs over to other services. They are right now:

      - curl-normal-with-openssl-gssapi-libssh2-checksrc
      - curl-novalgrind-boringssl-with-openssl
      - curl-novalgrind-boringssl-with-openssl-quiche
      - curl-novalgrind-libressl
      - curl-novalgrind-ngtcp2-with-openssl
      - curl-novalgrind-ngtcp2-gnutls
      - curl-debug-clang-disable-alt-svc-with-openssl
      - curl-debug-clang-with-gnutls
      - curl-cmake-boringssl-quiche
      - curl-cmake-ngtcp2
      - curl-torture
      - curl-fuzzer
      - curl-tidy
      - curl-debug-clang-with-openssl-dl-ubsan

**Comment by bagder** [comment]
This is how we have the jobs distributed over the different services as of June 28, 2022:

![Screenshot 2022-06-28 at 11-01-08 curl - Project status dashboard](https://user-images.githubusercontent.com/177011/176139163-319bb454-19ad-427e-8df4-e5fc25e21b0b.png)

**Comment by mnaser** [comment]
@bagder is there any interest if I look into this or is the project moving on?  I've been dealing with some health issues that got me afk for a little bit.

**Comment by levitte** [comment]
Do you have a preference as to where they get migrated?

**Comment by bagder** [comment]
Not really, no. It might make sense to move them to one of the lesser used ones to "even out the load", but I would also be perfectly okay with piling on more on GHA or Azure.

**Comment by bagder** [comment]
They're not gone anymore.
