### ISSUE TITLE
curl-www lacks information where issues can be filed

### ISSUE THREAD

**Issue by JensRantil** [curl/curl#903]
**Background:**
 * I wanted to file an issue against information missing in https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html.
 * I wanted to file an issue about [the README](https://github.com/curl/curl-www/blob/bb3ee16bd98d2e7909eda53f528d5a87fdf4ded5/README) stating the repository still doesn't document how the site is built.

**Problem:** The README says nothing, there is no CONTRIBUTING/CONTRIB file in the repository and Github issues is disabled.

**Proposed solution:** Fix any of the problems above ;)

**Comment by bagder** [comment]
1. that's documentation just converted from the source code repo so you'd file a bug/PR in the normal curl source repo for that. See https://github.com/curl/curl/blob/master/docs/libcurl/opts/CURLOPT_PROXY.3
 2. Fixed in curl-www commit 9891e852f6 just now

**Comment by JensRantil** [comment]
👏

**Comment by bagder** [comment]
Oh, and I also enabled issues in curl-www, it wasn't really intentional. Thanks for pointing these out!
