### ISSUE TITLE
Different results with different curl versions. Only old version is accurate to wget and firefox.

### ISSUE THREAD

**Issue by T200proX7** [curl/curl#9034]
Works:

```
Very old Debian (server):

curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/2.2.0 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

Does not work: 
```
Newer Debian (server):

curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

Does not work:

```
Arch Linux (Desktop)

curl 7.83.1 (x86_64-pc-linux-gnu) libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

I access an adult website using Curl and one would think that when I access the URL from all the above versions the result (HTML) should be the same.

Firefox and Chrome show a 404 error page. This also does the Curl version 7.52.1. Wget as well.

The other two newer versions return some cached page.

The HTTP request header is the same and I'm not completely without technical knowledge either, which is why I'm surprised to get different results here.

I have certainly spent two hours now trying to get the same results. I did not succeed.

**Comment by bagder** [comment]
This does not include enough details for us to understand where (if any) the issue is. It could very well be the server's choice.

**Comment by T200proX7** [comment]
As written its an adult website.. How should I post these stuff here. I really doubt its the servers choice. It also does not make sense. I can send you per e-mail several logfiles/access. Then you can check.

**Comment by T200proX7** [comment]
I just send you an email on the daniel@*.se. Subject: Github Curl Issues 9034
Please check the several textfiles in the attachment.

**Comment by T200proX7** [comment]
I can not tell you exactly. I am not so deep into this topic.

For my understanding a website with `script.php?key=[ID]` checks if a ID exists.. If this ID does not exist it shows Error 404 page. Different IDs usually show different database records.

On 3-4 devices (firefox+chrome, aria2c, wget, php fwrapper) the behaviour when accessing several urls (of that kind) is correct but on the newer curl version it always brings up a cached version - always the same cached page (for every id, no matter which and no matter if it exists or not). Using curl --http1.1 does not change anything.

For me that looks like something is wrong. If you think everything is fine then OK. You are the expert, you know. 
From my understanding: If 5-10 Urls are accessible from everywhere, every device, with every tool (including curl 7.52) but not with newer curl this looks like something is wrong. To be honest, I can't tell more to it, because I have no qualitification in this.

So if I was able to understand you correct, you think they identified the TLS fingerprint of newer curl version and therefore always serve the same/this one single cached page for any request?

**Comment by T200proX7** [comment]
I just found out that with "--tlsv1.2 --tls-max 1.2" i receive correct results. Whatever it means...
