### ISSUE TITLE
libcurl  connect.c@566  crashed

### ISSUE THREAD

**Issue by C2018List** [curl/curl#9072]
### I did this
server stoped while logining! the libcurl of my client crashed!
### curl/libcurl version
https://github.com/curl/curl.git   commitid  801bd5138ce31aa0d906fa4e2eabfc599d74e793 7.81.0
https://github.com/openssl/openssl.git    commitid  b4e83ed7cd99c12d27e0e220c3afa1745a68f921  3.0.1
https://github.com/libssh2/libssh2.git     commitid  635caa90787220ac3773c1d5ba11f1236c22eae8  1.10.0
[curl -V output]

### operating system
Windows

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can you provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by C2018List** [comment]
> Thanks a lot for your report!
> 
> I've failed to reproduce this problem myself, so can you provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

I'm trying to find a way to reproduce the problem and give an example

**Comment by bagder** [comment]
Nothing to act on. If you get additional details or a way to reproduce, we can reopen.
