### ISSUE TITLE
URL parser treats blank user as no user (CURLUE_NO_USER)

### ISSUE THREAD

**Issue by jay** [curl/curl#9088]
### I did this

`http://:@corporate_proxy:8080/` from jeroen/curl#237. It seems to me the reporter @OscarLane wants to be able to set ALL_PROXY with a blank user/pass so that libcurl w/SSPI will use his Windows credentials.

When the username is retrieved from the CURLU it returns CURLUE_NO_USER which is documented as "There is no user part in the URL."

https://github.com/curl/curl/blob/45ac4d019475df03562fe0ac54eb67e1d1de0ca7/lib/url.c#L2502-L2513

### I expected the following

I'm not sure on this one. Is this expected?

### curl/libcurl version

~~~
curl 7.84.1-DEV (i386-pc-win32) libcurl/7.84.1-DEV Schannel WinIDN
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS Debug HSTS IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI Unicode UnixSockets
~~~

---

/cc @jeroen

**Comment by bagder** [comment]
> Is this expected?

I don't think anyone has thought about it. The entire "set blank user name to trigger X" is a somewhat of a kludge, so it's not always easy to tell how it *should* work!

**Comment by jay** [comment]
I don't see any downsides to changing it. The change below fixes it but then will also do it even if the login string is empty, for example `http://@test.com`

~~~diff
diff --git a/lib/url.c b/lib/url.c
index 1114c6c..0ce1aa1 100644
--- a/lib/url.c
+++ b/lib/url.c
@@ -2894,7 +2894,7 @@ CURLcode Curl_parse_login_details(const char *login, const size_t len,
                                  (size_t)(login + len - osep)) - 1 : 0);
 
   /* Allocate the user portion buffer */
-  if(userp && ulen) {
+  if(userp) {
     ubuf = malloc(ulen + 1);
     if(!ubuf)
       result = CURLE_OUT_OF_MEMORY;
~~~
