### ISSUE TITLE
proxy-negotiate fails, but only for POST (SPNEGO problem)

### ISSUE THREAD

**Issue by paulharris** [curl/curl#909]
Hi,

I am using curl.exe to POST to a URL (multipart/form method) through an NTLM/negotiate proxy.

When POST fields are included, the proxy server panics.  But only when "negotiate" proxy auth is used.
I will change my compile options to drop the negotiate support (I assume its SPNEGO that is the problem), but I thought you might like to know about this problem...

I'm testing with the latest 7.49.1

The precompiled curl.exe I found via the website either don't execute for some reason, or they run and upload fine.  Probably because there is no SPNEGO support compiled in.

eg: 

> curl.exe --version
> curl 7.49.1 (i386-pc-win32) libcurl/7.49.1 OpenSSL/1.0.2h nghttp2/1.11.1
> Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp
> smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IPv6 Largefile NTLM SSL HTTP2

MY compiled version also includes SPNEGO support.
It is NOT able to upload as it seems to panic the proxy server.

> my_curl.exe --version
> curl 7.49.1-DEV (Windows) libcurl/7.49.1-DEV WinSSL zlib/1.2.7
> Protocols: http https
> Features: IPv6 SSPI Kerberos SPNEGO NTLM SSL libz
> 
> my_curl.exe "http://host.com/upload.cgi" -F "label=value" -x the.proxy:8080 --proxy-user username:pass  --proxy-any
## RESPONSE (I've trimmed some of the HTML stuff)

<TITLE>Appliance Error</TITLE>
<big>Appliance Error (internal_error)</big>
An unrecoverable error was encountered: "The IWA direct realm encountered an unm
apped error code, contact your system administrator."
This problem is unexpected. Please use the contact information below to obtain assistance.
For assistance, contact your network support team.
## </BODY></HTML>

Forcing NTLM with --proxy-ntlm, it works perfectly.
Without the -F "label=value", it works perfectly.
Changing it to -d "label=value", it also works perfectly.

I have some traces that I'll paste below.
trace_any.txt -- with ANY (this fails)
trace_ntlm.txt -- with NTLM (this succeeds)
trace_noform.txt -- with ANY, but no FORM fields (this succeeds)

[trace_any.txt](https://github.com/curl/curl/files/356507/trace_any.txt)
[trace_ntlm.txt](https://github.com/curl/curl/files/356505/trace_ntlm.txt)
[trace_noform.txt](https://github.com/curl/curl/files/356506/trace_noform.txt)

If you want me to do further tests, please let me know soon.
The test system is not mine...

cheers,
Paul

**Comment by paulharris** [comment]
Confirmed works without SPNEGO - I had to comment out this line in lib/curl_setup.h
```
/* Single point where USE_SPNEGO definition might be defined */
#if !defined(CURL_DISABLE_CRYPTO_AUTH) && \
    (defined(HAVE_GSSAPI) || defined(USE_WINDOWS_SSPI))
// #define USE_SPNEGO
#endif
```

**Comment by michael-o** [comment]
Provide the verbose output of curl during that post.

**Comment by michael-o** [comment]
Please retry the `POST` without expect continue. This might be the issue with your proxy. The `any` output is weird because the proxy says continue without saying 401 first.

**Comment by paulharris** [comment]
Sorry for the delay, I haven't followed up on this yet.

Looking back,
I had already turned off expect-continue in my normal program that uses libcurl directly, so I would expect that turning off expect-continue with curl.exe would cause the same problem.

Would you still like me to try again?  I can possibly get access to the system.
I assume I just need to add this to the curl command line : -H "Expect:"

**Comment by michael-o** [comment]
If you still think that this is a bug in curl, yes please because I cannot reproduce this.
