### ISSUE TITLE
Sending large files on Windows causes timeout

### ISSUE THREAD

**Issue by webmaster128** [curl/curl#910]
I use libcurl in a software that sets `CURLOPT_TIMEOUT_MS` to 1 minute.

On Windows 7, my file upload terminates after 57 seconds with a `CURLE_OPERATION_TIMEDOUT`. On other systems (including Windows Server 2008 R2), the upload continues for 2:30 minutes and ends successfully.

Is that expected behavior? I do not really understand, what exactly the timeout stands for. If it is really the maximal time for the entire transfer operation, as stated in [CURLOPT_TIMEOUT_MS.3](https://github.com/curl/curl/blob/master/docs/libcurl/opts/CURLOPT_TIMEOUT_MS.3), why is the timeout not triggered on all Non-Windows 7-Systems?

Environment:

* libcurl version 7.49.1
* HTTPs via schannel
* HTTP-Operation: POST
* Content-type: multipart/form-data

**Comment by jungle-boogie** [comment]
How large is the file?

**Comment by webmaster128** [comment]
93 MB

**Comment by webmaster128** [comment]
I improved my debugging and now get the following detailed error message:

> HTTP exception: 'Timeout was reached' in curl::curl_easy::perform
> Details: Operation timed out after 60015 milliseconds with 0 bytes received

**Comment by webmaster128** [comment]
The issue is not Windows 7 only but Windows 10 as well. For a given machine, it depends on the network it is connected to, weather or not the timeout is triggered.

**Comment by bagder** [comment]
> Is that expected behavior?

libcurl is expected to perform transfers as fast as possible. I assume you have checked that other tools can upload faster than this to the particular sites over these networks?

**Comment by webmaster128** [comment]
I think I found my problem: it is not depending on the OS but on the network only. The timeout is triggered whenever a network is not slow enough.

What confused me was that the process of sending the same file took 2:30 on some fast networks and no timeout was triggered. But it looks like the real sending was < 60 seconds and the rest was local IO before/after curl.
