### ISSUE TITLE
Cross compiling for armv6 (musl): undefined reference to `__atomic_is_lock_free'

### ISSUE THREAD

**Issue by JonasVautherin** [curl/curl#9119]
I am cross-compiling curl and linking it against OpenSSL 3.0.3 for various platforms, including musl armv6, armv7 and arm64. I am actually using the images from [musl.cc/armv6-linux-musleabihf-cross.tgz](http://musl.cc/armv6-linux-musleabihf-cross.tgz) (and similar for armv7 and arm64).

For most platforms, including arm64-musl, curl builds successfully. Also when using OpenSSL 1, that works. I am just getting this error when building for armv6:

```
[100%] Linking C executable curl
/usr/xcc/armv6-linux-musleabihf-cross/bin/../lib/gcc/armv6-linux-musleabihf/11.2.1/../../../../armv6-linux-musleabihf/bin/ld: /work/build/linux-armv6-musl/third_party/install/lib/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_atomic_or':
threads_pthread.c:(.text+0x168): undefined reference to `__atomic_is_lock_free'
/usr/xcc/armv6-linux-musleabihf-cross/bin/../lib/gcc/armv6-linux-musleabihf/11.2.1/../../../../armv6-linux-musleabihf/bin/ld: threads_pthread.c:(.text+0x1ec): undefined reference to `__atomic_fetch_or_8'
/usr/xcc/armv6-linux-musleabihf-cross/bin/../lib/gcc/armv6-linux-musleabihf/11.2.1/../../../../armv6-linux-musleabihf/bin/ld: /work/build/linux-armv6-musl/third_party/install/lib/libcrypto.a(libcrypto-lib-threads_pthread.o): in function `CRYPTO_atomic_load':
threads_pthread.c:(.text+0x228): undefined reference to `__atomic_is_lock_free'
/usr/xcc/armv6-linux-musleabihf-cross/bin/../lib/gcc/armv6-linux-musleabihf/11.2.1/../../../../armv6-linux-musleabihf/bin/ld: threads_pthread.c:(.text+0x278): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
```

I have seen some issues about libatomic recently. I tried building with the latest `master` branch from tonight, but this still happens.

Could it be something missing in Curl for OpenSSL 3.0.3 on that system? Or is it more likely that I am missing something on my end? :innocent:

**Comment by jay** [comment]
Check curl config.log for how OpenSSL was detected. Those CRYPTO_ functions are OpenSSL functions not curl functions. It looks like it's trying to link a static build of OpenSSL which means you will need to be responsible for providing any extra dependencies. Maybe -latomic? We actually check for some dependencies used by static OpenSSL during configure like -ldl and -lpthread, but we can't be responsible for all static dependencies. You may also try `PKG_CONFIG="pkg-config --static" ./configure ...`

**Comment by JonasVautherin** [comment]
Oh, I see. It works when I set `-DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-as-needed -latomic -Wl,--as-needed"` when building curl.

I guess that's on my side then. Thanks a lot!
