### ISSUE TITLE
[Known Bugs]1.11 CURLOPT_SEEKFUNCTION not called with CURLFORM_STREAM

### ISSUE THREAD

**Issue by nickychen123456** [curl/curl#9120]
I did this

I had the same problem as https://github.com/curl/curl/issues/768 , when set the CURLOPT_SEEKFUNCTION with CURLFORM_STREAM, the function not called.

curl_easy_setopt(m_hCurl, CURLOPT_SEEKFUNCTION, my_seek_callback);

the my_seek_callback not called when post a file and reveived a 307 redirect status code.

I have made a pull request https://github.com/curl/curl/pull/9116, could you please help to review it, thanks

**Comment by bagder** [comment]
The PR died, and the fix should be to move to the current API, not the deprecated one.
