### ISSUE TITLE
Header "TE: Trailers" causes PROTOCOL_ERROR on some websites

### ISSUE THREAD

**Issue by smbape** [curl/curl#9129]
### I did this
curl-7.84.0_4-win64-mingw\bin\curl.exe "https://www.google.com/" -H "TE: Trailers"
curl-7.84.0_4-win64-mingw\bin\curl.exe "https://docs.microsoft.com/fr-fr/" -H "TE: Trailers"
curl-7.84.0_4-win64-mingw\bin\curl.exe "https://github.com/" -H "TE: Trailers"

### I expected the following
The content of the response

### curl/libcurl version

[curl -V output]
curl 7.84.0 (x86_64-pc-win32) libcurl/7.84.0 OpenSSL/3.0.5 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.48.0 ngtcp2/0.6.0 nghttp3/0.5.0 libgsasl/1.10.0
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets

### operating system
Windows 10 x64

### Additional information
There was no problem with version 7.81
The problem appears since 7.82 on Linux (WSL ubuntu) and Windows
curl-7.84.0_4-win64-mingw\bin\curl.exe "https://curl.se/" -H "TE: Trailers" has no problem

**Comment by bagder** [comment]
Presumably because you send that header over HTTP/2 when it isn't permitted?

**Comment by smbape** [comment]
> Presumably because you send that header over HTTP/2 where it isn't permitted?
I doubt that. "TE: Trailers" is an header sent by Firefox. That header not being permitted means Firefox not being permitted.
Which is why I doubt it is the case.

After further inspection, Firefox 68 puts "TE: **T**railers", Firefox 98+ now puts "TE: **t**railers" instead "TE: **T**railers"
and curl-7.84.0_4-win64-mingw\bin\curl.exe "https://www.google.com/" -H "TE: **t**railers" is fine

Was 7.81 wrong when showing the response and 7.82+ is now right?

**Comment by bagder** [comment]
Could the difference perhaps be due to different nghttp2 library versions?

**Comment by smbape** [comment]
> Could the difference perhaps be due to different nghttp2 library versions?

No it is not. Same error with the nghttp2 version of 7.81

[curl -V output]
curl 7.84.0-DEV (x86_64-pc-linux-gnu) libcurl/7.84.0-DEV BoringSSL zlib/1.2.11 brotli/1.0.9 nghttp2/1.46.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe UnixSockets

**Comment by bagder** [comment]
Okay. The server closes the stream with `PROTOCOL_ERROR` and it's not obvious to me why it does this *sometimes* when including this header. I can't see any bug in curl's handling of this.

**Comment by smbape** [comment]
Maybe comparing with what is done differently in 7.81 can help.
I checked again
curl-7.81.0-win64-mingw\bin\curl.exe "https://www.google.fr/" -H "TE: Trailers" is fine

[curl -V output]
curl 7.81.0 (x86_64-pc-win32) libcurl/7.81.0 OpenSSL/3.0.1 (Schannel) zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 libgsasl/1.10.0
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI TLS-SRP UnixSockets

**Comment by bagder** [comment]
We removed the special treatment of the `TE: trailers` header in 9f985a11e, which is between 7.81.0 and 7.82.0. So, you don't see the error in the earlier version because then curl would filter it out and not send it. That filtering is not done anymore and when the header is included the server closes the stream. This is not a curl bug.

**Comment by smbape** [comment]
Thank you for the clarification.
