### ISSUE TITLE
waiting for name resolver threads before quitting can cause delays even with --max-time

### ISSUE THREAD

**Issue by ferrieux** [curl/curl#9137]
The issue #2975 has been marked as "stale" and "resolved" out of lack of activity.
Still, this is an awful wart in the face of Curl, just violating its own manpage.

To summarize:
  - assume no DNS response
  - the threaded resolver calls the blocking gethostbyname() in a separate thread.
  - the main thread honours `-m $DT` and times out after `$DT` seconds
  - however, some cleanup code insists on waiting for the thread to finish before exiting
  
In #2975 it was argued that leaking or killing are not acceptable for `libcurl`, which makes sense.
But someone also pointed out that the client `curl` can very well decide to leak, since it is about to call exit() anyway.
This is obviously the only way of honouring the manpage for option `-m`, and putting to rest this unjustified regression.

**Comment by bagder** [comment]
This is the already documented [known bug](https://curl.se/docs/knownbugs.html#Multi_perform_hangs_waiting_for). Creating another issue for the same problem will not make it fixed. I would rather suggest you work on a fix instead.

**Comment by ferrieux** [comment]
With pleasure; however the original issue being closed and locked against comments, I figured it was the only way to reopen the discussion. Please tell me if there was another way.

**Comment by bagder** [comment]
All the bugs already listed as known bugs are... bugs that aren't fixed. There's no need to open a new issue for any of them. We obviously know about them already. If you want to work on a fix for one, then please do so and submit a pull-request.

**Comment by ferrieux** [comment]
DONE: #9147

**Comment by bagder** [comment]
Fixed via #9147
