### ISSUE TITLE
Wrong HTTP status code after connection timeout

### ISSUE THREAD

**Issue by saendigPhilip** [curl/curl#9138]
### I did this

I experienced this issue while writing tests for the libcurl wrapper [libcpr](https://github.com/libcpr/cpr). 

The tests are supposed to simulate slow connections and test the timeout feature. For this purpose, the server does the following:
1. Send and drain the HTTP header with the status code 200
2. Timeout: Wait for 2 seconds to simulate a slow connection
3. Send the remaining message (the body, which is "Hello world!" in this case) 

Using mongoose as a server, the code for the callback creating the HTTP response is available [here](https://github.com/saendigPhilip/cpr/blob/5a2a1b44499c061bc94ede058f41df207e94bb07/test/httpServer.cpp#L86-L92).

The client simply makes a request with a timeout of 1 second. This results in a timeout error as the message is not transmitted completely during the timeout. The HTTP code, however, is 200, even though the request fails. 

For demonstrating the issue and for making sure that this is not an issue of libcpr I created a small code snippet using libcurl in C++:
```c++
#include <cassert>
#include <curl/curl.h>
#include <iostream>

int main() {
    auto curl = curl_easy_init();
    long response_code;
    char error[CURL_ERROR_SIZE];

    curl_easy_setopt(curl, CURLOPT_URL, "localhost:61936/low_speed.html");
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 1);
    curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, error);
    curl_easy_perform(curl);
    curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &response_code);
    curl_easy_cleanup(curl);

    std::cout << "Error message: " << error << '\n'; // Timeout error
    std::cout << "HTTP Response code: " << response_code << '\n';

    // We expect the HTTP code to be 0, however it is 200.
    // Therefore, the assertion fails
    assert(response_code == 0);
    return 0;
}

```

With the server described above running locally, this results in the following output:
```
Error message: Operation timed out after 1000 milliseconds with 0 out of 12 bytes received
HTTP Response code: 200
int main(): Assertion `response_code == 0' failed.
Aborted (core dumped)
```

### I expected the following

The HTTP response code should be 0 since the response was not fully received within the timeout.

### curl/libcurl version

```
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
Linux x541uj 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dfandrich** [comment]
>     curl_easy_perform(curl);

You're not checking the return code from this function. This is where the
indication of a timeout is returned.

>     curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &response_code);

This returns the response code from the server. If the server returns 200,
that's what you will get here.

>     // We expect the HTTP code to be 0, however it is 200.

The manual explains what you should and shouldn't expect here (and elsewhere).
