### ISSUE TITLE
test 3026...[curl_global_init thread-safety] failure

### ISSUE THREAD

**Issue by SukanyaHanumanthu** [curl/curl#9141]
Test 3026 failed in Curl `7.84.0`, fails on linux

```
test 3026...[curl_global_init thread-safety]

lib3026 returned 255, when expecting 0
 exit FAILED
== Contents of files in the log/ dir after test 3026
=== Start of file commands.log
 ./libtest/lib3026 none >log/stdout3026 2>log/stderr3026
=== End of file commands.log
=== Start of file ftpserver.cmd
 Testnum 3026
=== End of file ftpserver.cmd
=== Start of file stderr3026
 URL: none
 lib3026.c:59 Have pthread but the CURL_VERSION_THREADSAFE feature flag is not set
=== End of file stderr3026
```
Looks like [this](https://github.com/curl/curl/commit/2ed101256414ea5274e85e6f3d4c011b46442ac4) commit introduced the error, Is there a fix?

**Comment by bagder** [comment]
How did you build curl? Did you by any chance use cmake to do it?

**Comment by SukanyaHanumanthu** [comment]
Did the below as we applied a minor patch to `multihandle.h`
```
    make && \
    make test-full && \
    make install
```

**Comment by bagder** [comment]
but how did you generate the makefile?

**Comment by bagder** [comment]
**When curl is built with cmake, it is not threadsafe** see #8982 for pending work on that

**Comment by SukanyaHanumanthu** [comment]
Used GNUMake for the above and not cmake, is it a know incompatibility?

**Comment by bagder** [comment]
but _before_ make you invoked configure or cmake surely?

**Comment by SukanyaHanumanthu** [comment]
* removed cmake which was part of the install script and tested which had no change in behaviour, just an unwanted line.
* correct about the configure part, which had the below lines before `make test`
```
        --disable-shared \
        --with-pic \
        --without-ssl \
        --without-zlib && \
```
Does this affect the test?

**Comment by bagder** [comment]
Well, now you're complicating this issue. I think you now see "no difference" because you didn't properly rebuild everything after you changed from cmake to configure. Also, do you *really* want `--without-ssl` ? It is very unusual.

The fix for the original issue you submitted has been proposed in #9142 though.

**Comment by SukanyaHanumanthu** [comment]
Thank you for the above, configure was present before/after removing the cmake (always there), though cmake was installed on linux (removed now and tested), it was never used, the code always used GNU Make only.
