### ISSUE TITLE
GNU GPL copyleft in curl_rtmp.c 

### ISSUE THREAD

**Issue by ArenzD** [curl/curl#9145]
Hello everyone,

I have a license question regarding one very specific file: [curl_rtmp.c](https://github.com/curl/curl/blob/72516ba1fe6a9a76dcd2fac0836b1e913c38a8f2/lib/curl_rtmp.c)

The file header indicated curl's project [license](https://github.com/curl/curl/blob/master/COPYING)
https://github.com/curl/curl/blob/72516ba1fe6a9a76dcd2fac0836b1e913c38a8f2/lib/curl_rtmp.c#L11

However:
https://github.com/curl/curl/blob/72516ba1fe6a9a76dcd2fac0836b1e913c38a8f2/lib/curl_rtmp.c#L65
Points to a GNU General Public License V2.0 

**Question/Suggestion:** Could this line be removed without violating [rtmpdump's license](https://rtmpdump.mplayerhq.hu) ?

**Comment by bagder** [comment]
My interpretation is that this code was written with inspiration/docs from rtmpdump, not that it is a derivative.

@hyc I think you once wrote this comment. How do you consider it today? Would you be fine if we remove it from the code to remove this doubt?

**Comment by ArenzD** [comment]
@hyc Thank's for the clarification! That makes it clear!

To be honest I stoped reading the page referenced at line 3 where it said **License: GPLv2** 😇
![image](https://user-images.githubusercontent.com/88773196/178540014-e8f0f0ba-27c7-41fd-884d-48f5a836f7bd.png)

One whould wonder why it doesn't indicate **License: LGPLv2.1** if thats what the current version V2.4 ≥ V2.2 is 🧐

**Comment by hyc** [comment]
The rtmpdump program is GPLv2. The protocol guts of it were ripped out and packaged as librtmp, licensed LGPL.
