### ISSUE TITLE
possible buffer overrun in Curl_infof 

### ISSUE THREAD

**Issue by yiyuaner** [curl/curl#9149]
In the file `lib/sendf.c`, the function `Curl_infof` has the following [code](https://github.com/curl/curl/blob/e0c68f02552511df57f2afec2e62bc3ee684e12f/lib/sendf.c#L243):

```
void Curl_infof(struct Curl_easy *data, const char *fmt, ...) {
    ...
    size_t len;
    char buffer[MAXINFO + 2];
    len = mvsnprintf(buffer, MAXINFO, fmt, ap);
    buffer[len++] = '\n';
}
```
Since the function `mvsnprintf` may return `-1` (see the code [here](https://github.com/curl/curl/blob/e0c68f02552511df57f2afec2e62bc3ee684e12f/lib/mprintf.c#L597)), the following buffer access `buffer[len++]` can trigger a buffer overrun.

Similarly, the code for `Curl_failf` may trigger buffer overrun too:
```
void Curl_failf(struct Curl_easy *data, const char *fmt, ...) {
    size_t len;
    char error[CURL_ERROR_SIZE + 2];
    len = mvsnprintf(error, CURL_ERROR_SIZE, fmt, ap);
    error[len++] = '\n';
}
```

**Comment by bagder** [comment]
It is indeed an error, but luckily I think `dprintf_formatf` never actually returns -1 inside libcurl so this error never happens. Should still fix of course.
