### ISSUE TITLE
data race on ipv6_works

### ISSUE THREAD

**Issue by bprodoehl** [curl/curl#915]
### I did this
I ran a multi-threaded app that uses libcurl under Clang 3.9 ThreadSanitizer.

### I expected the following
Clean operation.

### curl/libcurl version
7.44

### operating system
Ubuntu 14.04, x86_64.

I encountered a data race with two threads calling Curl_ipv6works() at the same time.  I think perhaps the call to Curl_ipv6works() should be moved into curl_global_init() to avoid this.

**Comment by bagder** [comment]
Sounds like an excellent suggestion to me. You up to providing such a change as a pull request?

**Comment by bprodoehl** [comment]
Sure thing. I should be able to put that together and test it tonight.

**Comment by jay** [comment]
Thanks, landed in c509808.
