### ISSUE TITLE
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by tooptoop4** [curl/curl#9158]
getting error:
```curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled```

is there any environment variable i can set for this to work on bash script? i saw some reference to CURLOPT_SSL_CTX_FUNCTION but no idea what value it should be. SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION=true does not work, i don't want to edit files like openssl.conf

### I did this
curl -L https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/19.13.0.0.1/ojdbc8-19.13.0.0.1.jar -o o.jar

### I expected the following
file downloaded

### curl/libcurl version

curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/3.0.4 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12

### operating system

debian 11 bullseye

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/issues/8943#issuecomment-1151942200

It can be done with libcurl but not curl, unless you modify the source.

~~~c
#include <openssl/ssl.h>

...

CURLcode ssl_ctx_callback(CURL *curl, void *ssl_ctx, void *userptr)
{
  long bitmask = SSL_CTX_set_options((SSL_CTX *)ssl_ctx,
    SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION);

  return (bitmask & SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION) ?
    CURLE_OK : CURLE_ABORTED_BY_CALLBACK;
}

main()
{
...
curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, ssl_ctx_callback);
...
}
~~~

**Comment by tooptoop4** [comment]
@jay any chance u can make curl allow this without modifying source?

**Comment by jay** [comment]
As I said in the other issue I don't see enough use to add an option. Every option we add has a maintenance cost.

**Comment by tooptoop4** [comment]
now stuck! versions before 7.84 have CVEs but  7.84 no longer functionally works due to this error

**Comment by rkiddy** [comment]
Wow. This seems a bit lame. There are still sites out there that need this.

Eg https://downloads.leginfo.legislature.ca.gov/

**Comment by AstrobioMike** [comment]
I dig that demand needs to be high enough for this to be worth dealing with implementing/maintaining, so I'm just adding a vote as another person that thinks an option to enable this as suggested here and touched upon in https://github.com/curl/curl/issues/8943 would be stellar. 🙏

**Comment by jtpereyda** [comment]
Linking a workaround here that doesn't require recompilation: https://github.com/curl/curl/issues/8943#issuecomment-1261547899

The comment links to https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled which explains how to set a custom SSL config file using the `OPENSSL_CONF` environment variable. File contents:
```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
```
