### ISSUE TITLE
[Question] Is such DoH (DNS over HTTPS) implementation a brilliant folly?

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9160]
[[
```console
> curl --trace "%" -I --doh-url "https://1.1.1.1/dns-query" "https://www.torproject.org/"

...

== Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
=> Send SSL data, 512 bytes (0x200)
0000: 01 00 01 fc 03 03 56 4a 0a 23 de a3 5b 51 6e 89 ......VJ.#..[Qn.
0010: 14 c8 d9 6f d6 05 ab 69 c4 a4 98 1a ca 20 20 37 ...o...i.....  7
0020: b6 2f 6c c9 cc e6 20 82 de ea 40 85 21 3d d3 38 ./l... ...@.!=.8
0030: c7 54 fd 1f cc 96 c6 d4 3a 81 32 c1 14 28 50 9e .T......:.2..(P.
0040: 94 53 f0 26 ed 00 87 00 3e 13 02 13 03 13 01 c0 .S.&....>.......
0050: 2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00 ,.0.........+./.
0060: 9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0 ..$.(.k.#.'.g...
0070: 14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00 ..9.....3.....=.
0080: 3c 00 35 00 2f 00 ff 01 00 01 75 00 00 00 17 00 <.5./.....u.....
0090: 15 00 00 12 77 77 77 2e 74 6f 72 70 72 6f 6a 65 ....www.torproje
00a0: 63 74 2e 6f 72 67 00 0b 00 04 03 00 01 02 00 0a ct.org..........
00b0: 00 16 00 14 00 1d 00 17 00 1e 00 19 00 18 01 00 ................
00c0: 01 01 01 02 01 03 01 04 33 74 00 00 00 10 00 0e ........3t......
00d0: 00 0c 02 68 32 08 68 74 74 70 2f 31 2e 31 00 16 ...h2.http/1.1..
00e0: 00 00 00 17 00 00 00 31 00 00 00 0d 00 2a 00 28 .......1.....*.(
00f0: 04 03 05 03 06 03 08 07 08 08 08 09 08 0a 08 0b ................
0100: 08 04 08 05 08 06 04 01 05 01 06 01 03 03 03 01 ................
0110: 03 02 04 02 05 02 06 02 00 2b 00 09 08 03 04 03 .........+......
0120: 03 03 02 03 01 00 2d 00 02 01 01 00 33 00 26 00 ......-.....3.&.
0130: 24 00 1d 00 20 10 49 6d c5 51 58 9d 0e a1 38 dc $... .Im.QX...8.
0140: b3 7f d6 21 35 52 8e ec 6b 96 d0 e6 73 76 57 08 ..!5R..k...svW.
0150: bf 35 d0 36 27 00 15 00 a7 00 00 00 00 00 00 00 .5.6'...........
0160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
01f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
== Info: TLSv1.0 (OUT), TLS header, Unknown (21):
=> Send SSL data, 5 bytes (0x5)
0000: 15 03 01 00 02                                  .....
== Info: TLSv1.3 (OUT), TLS alert, decode error (562):
=> Send SSL data, 2 bytes (0x2)
0000: 02 32                                           .2
== Info: error:0A000126:SSL routines::unexpected eof while reading
== Info: Closing connection 0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
```
]]
&#xA0;&#xA0;&#xA0;&#xA0;Would not the whole purpose of encrypted DNS be completely defeated: were the domain name to still leak through some other channel? (culprit be TLS SNI extension in Client Hello in this case)

&#xA0;&#xA0;&#xA0;&#xA0;Related:
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [https://github<i>.</i>com/curl/curl/pull/4468](https://github.com/curl/curl/pull/4468)
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| [https://github<i>.</i>com/curl/curl/issues/3119](https://github.com/curl/curl/issues/3119)

**Comment by bagder** [comment]
The SNI "leak" of the target host name is a long-standing known issue. We don't need to deal with it here. The solution for that is called ECH.

**Comment by MasterInQuestion** [comment]
Actually a bit more than that. More details to follow.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-18 21:31:52 UTC:
[https://github<i>.</i>com/curl/curl/issues/9160#issuecomment-1188335629](https://github.com/curl/curl/issues/9160#issuecomment-1188335629)
&#xA0;&#xA0;&#xA0;&#xA0;Doesn't sound like a topic for a curl issue nonetheless. ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;Indeed specifically not an issue for &#x60;curl&#x60; only.
&#xA0;&#xA0;&#xA0;&#xA0;Seemingly applies to... all current implementations network related.

&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-17 21:32:41 UTC:
[https://github<i>.</i>com/curl/curl/issues/9160#issuecomment-1186610908](https://github.com/curl/curl/issues/9160#issuecomment-1186610908)
&#xA0;&#xA0;&#xA0;&#xA0;The SNI "leak" of the target host name is a long-standing known issue. ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;Long-standing, known by few.
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-17 21:32:41 UTC:
[https://github<i>.</i>com/curl/curl/issues/9160#issuecomment-1186610908](https://github.com/curl/curl/issues/9160#issuecomment-1186610908)
&#xA0;&#xA0;&#xA0;&#xA0;We don't need to deal with it here. ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;Perhaps we don't. But we may.
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-17 21:32:41 UTC:
[https://github<i>.</i>com/curl/curl/issues/9160#issuecomment-1186610908](https://github.com/curl/curl/issues/9160#issuecomment-1186610908)
&#xA0;&#xA0;&#xA0;&#xA0;The solution for that is called ECH. ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;Yes, somewhat. But a critical issue of ECH is that requires both Client Server support.
&#xA0;&#xA0;&#xA0;&#xA0;And as of yet ECH seems to have been only deployed on measly amount of sites. [ [https://github<i>.</i>com/mozilla-mobile/fenix/issues/4584#issuecomment-1186094287](https://github.com/mozilla-mobile/fenix/issues/4584#issuecomment-1186094287) ]
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Meanwhile we may still optimize the flow of ECH support:
&#xA0;&#xA0;&#xA0;&#xA0;|1| Attempt ECH if Server supports.
&#xA0;&#xA0;&#xA0;&#xA0;|2| Send no SNI if Server doesn't support ECH:
&#xA0;&#xA0;&#xA0;&#xA0;|2.1| Server may actually return a valid result: success.
&#xA0;&#xA0;&#xA0;&#xA0;|2.2| Server returns wrong certificate: prompt for using "-k" or "--leak-sni".
&#xA0;&#xA0;&#xA0;&#xA0;|2.3| Server complains "Unrecognized Name" or whatsoever error: prompt for "--leak-sni".
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Also we shall pay attention to other possible leak sources (mostly on other aspects of TLS protocol).

**Comment by bagder** [comment]
Sorry, but I don't understand what you're saying here.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;Huh..? Which part specifically?
&#xA0;&#xA0;&#xA0;&#xA0;And do you rely on some machine translator for the parsing?

**Comment by bagder** [comment]
All parts. You submitted an issue about DoH here that isn't a curl bug. Case closed. You seem to want to drag it on but it seems to just bring it even more off-topic. If you want discuss DoH and its technicalities, then please find a forum for DoH interested people. If you have a curl issue, then please submit it.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;[ Quote MasterInQuestion @ CE 2022-07-19 05:15:45 UTC:
[https://github<i>.</i>com/curl/curl/issues/9160#issuecomment-1188602124](https://github.com/curl/curl/issues/9160#issuecomment-1188602124)
&#xA0;&#xA0;&#xA0;&#xA0;Meanwhile we may still optimize the flow of ECH support:
&#xA0;&#xA0;&#xA0;&#xA0;|1| Attempt ECH if Server supports.
&#xA0;&#xA0;&#xA0;&#xA0;|2| Send no SNI if Server doesn't support ECH (only when using encrypted DNS):
&#xA0;&#xA0;&#xA0;&#xA0;|2.1| Server may actually return a valid result: success.
&#xA0;&#xA0;&#xA0;&#xA0;|2.2| Server returns wrong certificate: prompt for using "-k" or "--leak-sni".
&#xA0;&#xA0;&#xA0;&#xA0;|2.3| Server complains "Unrecognized Name" or whatsoever error: prompt for "--leak-sni". ]
<.>&#xA0;&#xA0;&#xA0;&#xA0;Would not, at least this part, even if &#x60;curl&#x60; does not yet support ECH: still be applicable for current &#x60;curl&#x60;?

**Comment by bagder** [comment]
We want to see ECH support in curl, yes.
