### ISSUE TITLE
Getting a directory listing from a FTPS Server hanging on Windows / SChannel

### ISSUE THREAD

**Issue by grafster** [curl/curl#9161]
### I did this

I set up a local ftps server following these instructions.

https://itnext.io/using-a-local-ftps-server-for-testing-6f2d77873bab

And uploaded some files to it (the problem does not occur if there are no files on the server, but it doesn't seem to matter what files you upload)

I build libcurl using vcpkg on windows, and created and ran the attached program to get the file listing from the remote server. It works correctly on Linux but not in Windows, when curl is compiled with schannel as opposed to OpenSSL.

I got similar results from running:-

curl  --ssl-reqd -k --insecure ftp://localhost:21/ --user "foo:pass" --verbose

### I expected the following

I expected the program to exit after displaying the file listing, but it hangs indefinitely.

### curl/libcurl version

libcurl/7.84.0-DEV Schannel zlib/1.2.12

[curl -V output]

### operating system

Windows 10 21H2

[Source.cpp.txt](https://github.com/curl/curl/files/9122363/Source.cpp.txt)

**Comment by grafster** [comment]
I've been doing a bit more digging on this one, and it seems that the problem is partly down to the behaviour of the server. With a different FTP server, after getting the directory listing, the next call to "select" returns 1, and somewhere recv_sspi_close_notify is being get set to true. On this ftp server, the "select" call returns 0, and curl seems to keep calling select until it turns to 1, which it never will.

**Comment by grafster** [comment]
The problem doesn't seem to be isolated to the pure-ftpd server above.  
I can also reproduce the issue with vsftpd installed from here https://hub.docker.com/r/bfren/ftps

**Comment by jay** [comment]
I couldn't get the docker working for this. If you have a step by step way to reproduce without docker I will try that.
