### ISSUE TITLE
[Bug] `--trace` hexdump view did not escape `\x7F`

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9162]
&#xA0;&#xA0;&#xA0;&#xA0;As displayed in [ [https://github<i>.</i>com/curl/curl/issues/9160#issue-1305810315](https://github.com/curl/curl/issues/9160#issue-1305810315) ].
&#xA0;&#xA0;&#xA0;&#xA0;I suppose it's unintended. As the behavior seems to be inconsistent with &#x60;hexdump&#x60;.

**Comment by vszakats** [comment]
Thank you @MasterInQuestion, it should be fixed now.

**Comment by MasterInQuestion** [comment]
=== Off-Topic ===

&#xA0;&#xA0;&#xA0;&#xA0;There's semantic difference between "&#x60;" (Grave Accent) (U+0060, 0x60, &amp;<span>#</span>96;) and &#x60;"&#x60; (Quotation Mark) (U+0022, 0x22, &amp;<span>#</span>34;).
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;E.g.
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| &#x60;&#x5C;x7F&#x60; means:
(Character Sequence)
[[
|1| &#x60;&#x5C;&#x60; (Reverse Solidus) (U+005C, 0x5C, &amp;<span>#</span>92;)
|2| "x" (Latin Small Letter X) (U+0078, 0x78, &amp;<span>#</span>120;)
|3| "7" (Digit 7) (U+0037, 0x37, &amp;<span>#</span>55;)
|4| "F" (Latin Capital Letter F) (U+0046, 0x46, &amp;<span>#</span>70;)
]]
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| "&#x5C;x7F" means "&#x5C;x7F" (Delete) (U+007F, 0x7F, &amp;<span>#</span>127;).

**Comment by vszakats** [comment]
It's a Markdown markup here, meaning to display it as code.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;I know. And such sophisticated markup creates general interoperability issue.
&#xA0;&#xA0;&#xA0;&#xA0;See [ [https://github<i>.</i>com/curl/curl/issues/9153#issuecomment-1185051870](https://github.com/curl/curl/issues/9153#issuecomment-1185051870) ].

**Comment by vszakats** [comment]
Speaking of GitHub Issues, I think it's the opposite.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;For GitHub yet has broken rendering on some very fundamental thing.
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;What's the purpose of all these sophisticated markups if things may be very well clearly expressed in Plain Text?

**Comment by vszakats** [comment]
The purpose of it is to make posts easier to read and harder to misunderstand. For example code markup will retain spaces and other things. It also indicates that it is code/command/input/output, or a `keyword`. Yet it remain readable as plain text as well.

**Comment by vszakats** [comment]
You can always access the original text for your own submissions. For others, you can do the same with the "Quote reply" option, if that's necessary.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;Not always (e.g. locked topic). And the practice is bothersome (not only login required, and the apparent more).
&#xA0;&#xA0;&#xA0;&#xA0;Even if so:

&#xA0;&#xA0;&#xA0;&#xA0;Readable in one way, unreadable in another:
&#xA0;&#xA0;&#xA0;&#xA0;The doomed fate of Markdown, and similar sophisticated markups:
&#xA0;&#xA0;&#xA0;&#xA0;That demand sophisticated post-rendering to be properly displayed.
