### ISSUE TITLE
[Suggestion] `--doh-url` should not assert `http://` when omitted protocol

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9163]
&#xA0;&#xA0;&#xA0;&#xA0;DNS over HTTPS hence only HTTPS would be plausible.
&#xA0;&#xA0;&#xA0;&#xA0;It's value handling should be special-cased.

&#xA0;&#xA0;&#xA0;&#xA0;Also, would it be proper to add an option "--doh" simply as the alias for "--doh-url"?
&#xA0;&#xA0;&#xA0;&#xA0;Or perhaps making "--doh" a boolean switch controlling whether to use DoH or not?

**Comment by vszakats** [comment]
Thanks for your report @MasterInQuestion. Fixed now.

Regarding `--doh`, discussions are welcome here, or even better in a new Issue dedicated for it.
