### ISSUE TITLE
OpenSSL SSL_Error

### ISSUE THREAD

**Issue by ayjin-dev** [curl/curl#9168]
This is my host details.
OS: archlinux
CurlVersion:curl 7.71.1 (x86_64-conda_cos6-linux-gnu)
Curl-config-ca: /opt/anaconda/ssl/cacert.pem

When i try to yay mendeley-fcitx plugin support, it show some errors.

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by ayjin-dev** [comment]
Thank for your reply at first. :thumbsup: I think I've skipped this question when I switched to another proxy node. Maybe this is my proxy question i think.

**Comment by jay** [comment]
Closing. No evidence this is anything other than an issue with OP's proxy.
