### ISSUE TITLE
test3026 fails on i686 (and probably on other 32-bit platforms as well)

### ISSUE THREAD

**Issue by ericonr** [curl/curl#9172]
### I did this

I ran the testsuite in a i686 chroot and test 3026 fails with the following:

```
URL: none
lib3026.c:67 Couldn't create thread, errno 11
```

I think making thread creation failures in the test non fatal might be enough, but I don't know if that's desired.

### I expected the following

The testsuite should complete without failure.

### curl/libcurl version

7.84.0

### operating system

`Linux $hostname 5.16.20_1 #1 SMP PREEMPT Thu Apr 14 17:43:53 UTC 2022 x86_64 GNU/Linux` (this was run in an i686 chroot)

**Comment by bagder** [comment]
But why does this fail specifically on i686 and how do you know it is i686-specific?

**Comment by bagder** [comment]
Does #9173 make it work?

**Comment by ericonr** [comment]
> But why does this fail specifically on i686 and how do you know it is i686-specific?

It ran to completion on x86_64. And glibc default thread stack size should be 8MB, so it makes sense that they can't fit 1000 of those in the 4GB (or 3GB, I never remember how the split goes exactly) of address space available.

I will test!
