### ISSUE TITLE
curl reports "wrong signature type"

### ISSUE THREAD

**Issue by krypton612** [curl/curl#9186]
I receive this error when doing curl, I was reading and everything seems to indicate that it is the ssl certificate, how could I solve it?

curl: (35) error:0A000172:SSL routines::wrong signature type

### I expected the following

api response, requests work on the site https://reqbin.com/curl

### curl/libcurl version

curl 7.83.1 (x86_64-pc-linux-gnu) libcurl/7.83.1 OpenSSL/3.0.3 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0 librtmp/2.3 OpenLDAP/2.5.12
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

### operating system

Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali5 (2022-07-04) x86_64 GNU/Linux

**Comment by bagder** [comment]
This seems to happen because OpenSSL considers the signature used for the server certificate to be "bad". I found a credible explanation [here](https://updown.uservoice.com/knowledgebase/articles/1989757-what-does-the-wrong-signature-type-ssl-error-mea). This also means that this isn't actually a curl issue.

The hard-to-understand error message from OpenSSL about this is certainly unfortunate but not very easy to fix.

**Comment by ndaniel** [comment]
any workaround for *forcing* curl to proceed with the download?

**Comment by dfandrich** [comment]
Have you tried -k  ?

**Comment by ndaniel** [comment]
I tried. It does not work :-(

**Comment by anenasa** [comment]
This works for me:
1. Copy `/etc/ssl/openssl.cnf` to `/path/to/openssl.cnf` (You choose a convenient path)
2. In `/path/to/openssl.cnf`, change line `openssl_conf = openssl_init` to `openssl_conf = default_conf`
3. Append this to the end of `/path/to/openssl.cnf`:
```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=0
```
4. Run `export OPENSSL_CONF=/path/to/openssl.cnf` before curl command
Reference: https://askubuntu.com/questions/1423215/ubuntu-22-04-how-to-set-lower-ssl-security-level

**Comment by wuyudi** [comment]
I don't know whether it's on topic, but `wget` can bypass this. (So just on this case, if don't mind, use wget).

example:

```sh
curl -v -k https://ccb.jhu.edu/software/glimmerhmm/dl/GlimmerHMM-3.0.4.tar.gz -o /dev/null
```

vs

```sh
wget https://ccb.jhu.edu/software/glimmerhmm/dl/GlimmerHMM-3.0.4.tar.gz -O /dev/null
```

**Comment by bugsoftware** [comment]
This should fix it:
update-crypto-policies --set LEGACY
