### ISSUE TITLE
[Suggestion] "--doh" boolean switch for controlling whether to use DoH

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9189]
&#xA0;&#xA0;&#xA0;&#xA0;Follow up [ [https://github<i>.</i>com/curl/curl/issues/9163#issue-1306494038](https://github.com/curl/curl/issues/9163#issue-1306494038) ].

&#xA0;&#xA0;&#xA0;&#xA0;Proposed implementation: &#x60;( --doh | --no-doh ) [${Boolean Flag}]&#x60;
&#xA0;&#xA0;&#xA0;&#xA0;; where:
&#xA0;&#xA0;&#xA0;&#xA0;${Boolean Flag} = <a href="https://regex101.com/?regex=(?:0|false|F(?:alse|ALSE)?)(*:0)|(?:1|true|T(?:rue|RUE)?)(*:1)&flags=">/(?:0|false|F(?:alse|ALSE)?)(&#x2A;:0)|(?:1|true|T(?:rue|RUE)?)(&#x2A;:1)/</a>:
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| Branch 0: false
&#xA0;&#xA0;&#xA0;&#xA0;|&#x2A;| Branch 1: true
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Assume true when omitted ${Boolean Flag}.
&#xA0;&#xA0;&#xA0;&#xA0;Last occurrence of "--doh" takes precedence.

&#xA0;&#xA0;&#xA0;&#xA0;The design should be compatible with current "--doh-*" definition.

**Comment by bagder** [comment]
But why? You need to set a URL for the DoH server anyway so why have an additional option for on/off?

**Comment by bagder** [comment]
Also, we cannot have optional parameters to command line options due to how the parser works. It would have to be `--doh` only (and the `--no-` version as for all boolean options)

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;Your editing to the main post screwed up the formatting seriously (and caused misinformation). I reverted your change for readability. [Note 1]

&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-20 21:05:45 UTC:
[https://github<i>.</i>com/curl/curl/issues/9189#issuecomment-1190757373](https://github.com/curl/curl/issues/9189#issuecomment-1190757373)
&#xA0;&#xA0;&#xA0;&#xA0;You need to set a URL for the DoH server anyway so why have an additional option for on/off? ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;For the convenience of quickly switching DoH on/off.
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Consider the below use case:
(Unix Shell)
[[
```shell
	exec '/usr/bin/curl' -q \
	--no-progress-meter \
	--compressed \
	-A '' \
	--doh-url '1.1.1.1/dns-query' \
	--no-doh \
	-g "$@";
```
]]
; which is a script named "curl" and cloaks the regular calling of &#x60;curl&#x60;. [Note 2]

&#xA0;&#xA0;&#xA0;&#xA0;[ Quote bagder @ CE 2022-07-20 21:09:37 UTC:
[https://github<i>.</i>com/curl/curl/issues/9189#issuecomment-1190760333](https://github.com/curl/curl/issues/9189#issuecomment-1190760333)
&#xA0;&#xA0;&#xA0;&#xA0;Also, we cannot have optional parameters to command line options due to how the parser works.
&#xA0;&#xA0;&#xA0;&#xA0;It would have to be "--doh" only (and the "--no-" version as for all boolean options). ]
<^>&#xA0;&#xA0;&#xA0;&#xA0;Please point out the relevant codes. I (or others) might consider implement it when have the interest.
\
\
\
\
== Notes ==

[ [Note 1]
&#xA0;&#xA0;&#xA0;&#xA0;Markdown is just such tricky for general use.
&#xA0;&#xA0;&#xA0;&#xA0;See [ [https://github<i>.</i>com/github-community/community/discussions/20921](https://github.com/github-community/community/discussions/20921) ] if you'd like further discussion. ]

[ [Note 2]
&#xA0;&#xA0;&#xA0;&#xA0;Each occurrence of "--doh-url" should always imply "--doh".
&#xA0;&#xA0;&#xA0;&#xA0;E.g. With the above script, &#x60;curl --doh-url "${URI}" ...&#x60; should active DoH.

&#xA0;&#xA0;&#xA0;&#xA0;Off-Topic: Perhaps an alias "--doh-uri" is needed for "--doh-url". ]

**Comment by jzakrzewski** [comment]
> Your editing to the main post screwed up the formatting seriously (and caused misinformation). I reverted your change for readability. [Note 1]

Sorry, but I find your post completely unreadable with weird formatting. Quoting, notes, jumping around... Markdown compared to that is crystal clear.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;Markdown related Off-Topic to [ [https://github<i>.</i>com/github-community/community/discussions/20921](https://github.com/github-community/community/discussions/20921) ], thanks.

**Comment by bagder** [comment]
I'm with @jzakrzewski. All this weirdly formatted mumbo jumbo makes it very hard to extract the actual content that might be in there somewhere.

So, again *why* would we want this new option? (please reply without all the funny formatting)

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;For the convenience of quickly switching DoH on/off.
&#xA0;&#xA0;&#xA0;&#xA0;.
&#xA0;&#xA0;&#xA0;&#xA0;Pardon my inability of expressing anything more detailed under such formatting constraint.

**Comment by bagder** [comment]
IMHO, that is not a good enough reason for such an additional option. You can easily create an alias for that purpose or your own wrapper-script that has such an option.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;The "--doh-url" option once applied there seems to be no way to disable it?
&#xA0;&#xA0;&#xA0;&#xA0;If so, writing an equivalent script achieving the very purpose would be rather sophisticated. (demands additional parameter parsing)

&#xA0;&#xA0;&#xA0;&#xA0;Is there any reason for reserving the "--doh" option for other purposes?

**Comment by jay** [comment]
Call it what you want but you've been formatting some of your posts in a way that is harder for us to read.

> The "--doh-url" option once applied there seems to be no way to disable it?

If the option is used then it is enabled until --next is used to start another operation with different local options.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;("--next") As I've fathomed. That's a much undesirable way for achieving the mentioned purpose.

&#xA0;&#xA0;&#xA0;&#xA0;("readability") I'd suggest taking a look at the previous post:
&#xA0;&#xA0;&#xA0;&#xA0;|*| [https://github<i>.</i>com/curl/curl/issues/9189#issuecomment-1192456554](https://github.com/curl/curl/issues/9189#issuecomment-1192456554)

**Comment by bagder** [comment]
Also, `--doh-url ""` can be used to nix DoH use.

**Comment by jay** [comment]
> Also, `--doh-url ""` can be used to nix DoH use.

That doesn't work, it currently maps to curl_easy_setopt(curl, CURLOPT_DOH_URL, "") and also it isn't documented.

~~~
* curl_url_set rejected : No host part in the URL
* Closing connection -1
* Expire cleared (transfer 0x5a1e68)
* a DoH request is completed, 1 to go
* DoH request URL using bad/illegal format or missing URL
~~~

**Comment by bagder** [comment]
I made #9207 to make sure it actually works.

**Comment by bagder** [comment]
Possibly, but that's a way to achieve the same effect without adding a new option.

**Comment by MasterInQuestion** [comment]
= Belated sorry, whatsoever I shall express =

    Some my wording at the time may be indeed somehow inappropriate. (notably the ["Your editing screwed up the formatting seriously"](https://github.com/curl/curl/issues/9189#issuecomment-1192447537) one)
    Sorry for the bother.
    .
    My posts when are not as rigorously reviewed as now:
    Some not so appropriate lines may indeed have slipped through.

    No bad words indeed and guaranteed "civil"...
    Hardly offensive but indeed somewhat malapropos.
