### ISSUE TITLE
Using argument --cacert doesn't check if supplied cert is in fact CA=true

### ISSUE THREAD

**Issue by azgabur** [curl/curl#9191]
### I did this

1. I exported *just* the server certificate for https://example.com and saved as **example.pem**
2. This certificate is CA=false, as it should be
3. I run `curl -v https://example.com --cacert example.pem`
4. Connection was successful

### I expected the following

Either one:

- Connection to fail and and get error "unable to get local issuer certificate"
- Connection to be successful as it is now, but issue a warning that curl used certificate that is not CA
- Have information about this behavior in the man page

### curl/libcurl version

```
curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

`Linux ntbk 5.18.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:02 +0000 x86_64 GNU/Linux`

**Comment by bagder** [comment]
This is functionality that the TLS libraries provide and this has "always" worked like this. Feel free to suggest what documentation you think should be adjusted to make it clearer to users.

**Comment by azgabur** [comment]
That is interesting behavior of used libraries. For example _openssl_ reacts this way:
```
$ openssl s_client -connect example.com:443 --CAfile example.pem
...

---
SSL handshake has read 3772 bytes and written 739 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---

...
```

**Comment by azgabur** [comment]
If you wish to keep this behavior I would change "docs/cmdline-opts/cacert.d" like this:

```
Tells curl to use the specified certificate file to verify the peer. The file may contain multiple CA certificates.
```

to say:

```
Tells curl to use the specified certificate file to verify the peer. The file may contain multiple CA certificates or matching server certificate of peer which does not need to be CA.
```

**Comment by bagder** [comment]
Ok, now I understand what you mean. curl sets `X509_V_FLAG_PARTIAL_CHAIN` (since 94f1f771586913add) which the openssl tool probably doesn't.

**Comment by azgabur** [comment]
If I understand the openssl flag `X509_V_FLAG_PARTIAL_CHAIN` correctly, it changes behavior where just intermediate CA certificates signature are enough to pass verification if in trust store. 
But if there is a non-CA certificate in trust store, I think it should be ignored as it cant sign certificates.
This seems like openssl issue with that flag, because I tested this problem with `wget` and it behaves the same as `curl`
I didnt find a way to (un)set that flag myself when using openssl directly so I cant test it yet how it behaves.

**Comment by bagder** [comment]
In my view, you use `--cacert` to tell curl what certs that are CA certs to use to verify the remote certificate with. You say it is a CA cert. Then curl uses it like it is.

**Comment by bagder** [comment]
I don't think this is an error, I think this is doing what the user asks for.
