### ISSUE TITLE
After cloning the curl repository, the configure command does not work correctly as in the documentation.

### ISSUE THREAD

**Issue by Sugar0612** [curl/curl#9193]
### bug
     
When I implement the android platform cross-compilation on linux according to "the INSTALL document." in the document, according to the document when I configure the environment, then I should use the ./configure command to configure the next step, linux reminds me that there is no such thing command, and then I found that there is only a configure.ac file in the cloned warehouse, and there is no configure file. So this leads me to have no way to execute the command "./configure --host aarch64-linux-android --with-pic --disable-shared" or use "./configure --host aarch64-linux- after configuring openssl" android --with-pic --disable-shared --with-openssl="$TOOLCHAIN/sysroot/usr" ".

### I did this
no idea..

### I expected the following
Should I add a configure file to the curl repository to make it easier for beginners to curl, because I feel overwhelmed and confused when I encounter such a situation. .

### curl/libcurl  version
git clone version used directly.

[curl -V output]

### operating system
linux

**Comment by emilengler** [comment]
When you use the git clone, you have to run `autoreconf -fi` before you can invoke `./configure`.

**Comment by emilengler** [comment]
Beside this, I'm also curious why you are using the current git master instead of a release tarball found on the curl.se website, which already contain a working `configure` script. Release tarballs are generally the recommended way for installing curl, unless you plan to do bleeding-edge development.

**Comment by Sugar0612** [comment]
> 除此之外，我也很好奇你为什么使用当前的 git master 而不是 curl.se 网站上的发布 tarball，它已经包含一个工作`configure`脚本。发布 tarball 通常是安装 curl 的推荐方式，除非您打算进行前沿开发。

First of all, thank you very much for your answer! I use curl like this because I used openssl to go to git clone and generate the .a and .so files I want through android-ndk, and then I need to use curl as well, because the openssl repository has a ./configure file. Direct configuration, I thought that curl should also have this thing, but it turned out that it didn't, and then I was confused. . .

**Comment by Sugar0612** [comment]
> Beside this, I'm also curious why you are using the current git master instead of a release tarball found on the curl.se website, which already contain a working `configure` script. Release tarballs are generally the recommended way for installing curl, unless you plan to do bleeding-edge development.

Honestly, I'm kind of stupid

**Comment by bagder** [comment]
This fact is also documented in `GIT-INFO` in the root of the source tree.

**Comment by Sugar0612** [comment]
> This fact is also documented in `GIT-INFO` in the root of the source tree.

thanks~!

**Comment by KarimH22** [comment]
Hi
Why does not appear in the web site neither readme ?
can you add a file INSTALL just give that command please

**Comment by bagder** [comment]
@KarimH22 The file `docs/INSTALL.md` already has a mention of how to build from git and it mentions the additional `GIT-INFO` file. What are you saying is missing?

**Comment by KarimH22** [comment]
It is quite tricky not really clear unlike some other projects
at root path, no INSTALL file, you have to go to docs and there you have to come back to root path ....
in this case why not to add the link to GIT-INFO in the INSTALL.md please ? it will highlight it.  

thank you
