### ISSUE TITLE
build warnings with Visual Studio unicode builds since bf7e887b24

### ISSUE THREAD

**Issue by bagder** [curl/curl#9195]
[build log](https://ci.appveyor.com/project/curlorg/curl/builds/44255779/job/3drakckomc27qqtt)

~~~
C:/projects/curl/src/tool_getparam.c: In function 'parse_args':
C:/projects/curl/src/tool_getparam.c:2450:17: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
           clear = argv[i + 1];
                 ^
[ 87%] Building C object src/CMakeFiles/curl.dir/tool_help.c.obj
cc1.exe: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/curl.dir/build.make:294: src/CMakeFiles/curl.dir/tool_getparam.c.obj] Error 1

**Comment by jay** [comment]
I submitted #9154 earlier for this. I think we just shouldn't cleanarg on windows, that is probably a better solution because it seems to me the arguments are not pointers into the command line but rather copies parsed from the command line, which isn't visible to other users anyway.

**Comment by bagder** [comment]
> I think we just shouldn't cleanarg on windows

Well we don't, since the proper define isn't set there. So it doesn't happen. That's why I didn't like #9154 as it is written right now.

**Comment by jay** [comment]
Ok fair enough I closed it.
