### ISSUE TITLE
[Suggestion] "--tls-min" option as parallel for "--tls-max"?

### ISSUE THREAD

**Issue by MasterInQuestion** [curl/curl#9198]
&#xA0;&#xA0;&#xA0;&#xA0;Refer to [ [https://curl.se/docs/manpage.html#--tls-max](https://curl.se/docs/manpage.html#--tls-max) ].
\
\
=== Off-Topic ===

&#xA0;&#xA0;&#xA0;&#xA0;"default" is too long, adding the below 3 aliases might be desirable:
&#xA0;&#xA0;&#xA0;&#xA0;|1| "-"
&#xA0;&#xA0;&#xA0;&#xA0;|2| "0"
&#xA0;&#xA0;&#xA0;&#xA0;|3| "-1"

&#xA0;&#xA0;&#xA0;&#xA0;And a form like "--no-tls-min" (or "--no-tls-max") also seems valid.

**Comment by bagder** [comment]
This is already provided by the separate options for TLS versions: `--tlsv1`, `--tlsv1.1`, `--tlsv1.2` and `--tlsv1.3` etc

I don't think we need to introduce a way to duplicate this functionality.

**Comment by MasterInQuestion** [comment]
&#xA0;&#xA0;&#xA0;&#xA0;I know.
&#xA0;&#xA0;&#xA0;&#xA0;For semantical completeness and ease of access.

**Comment by bagder** [comment]
While I agree there's inconsistency in the way the options work, mostly because we didn't anticipate this future back in the 90s, I am still against adding a plain alias for this functionality. Every new option is a maintenance burden and a load on users.

**Comment by MasterInQuestion** [comment]
I'm rather interested in how would some mere aliases even pose a maintenance burden to the option parsing system...
    Added load indeed, but in many cases way too insignificant.

**Comment by jay** [comment]
I don't think it's worth it. Everything has a cost. I suppose we can leave this open for a bit to gather more feedback.

**Comment by MasterInQuestion** [comment]
Probably just hang it there until someone who was bothered enough to implement it. (points valid, though not significantly matter)

**Comment by bagder** [comment]
Not worth it.
