### ISSUE TITLE
Crash when both CURLOPT_VERBOSE and CURLOPT_DEBUGFUNCTION are set to 1L.

### ISSUE THREAD

**Issue by topherchen** [curl/curl#920]
I just create a simple testcase with the following code snippets and it crashes at curl_easy_perform().

`int main(int argc, char* argv[]) {`
`curl_global_init(CURL_GLOBAL_DEFAULT);`
`CURL* conn = curl_easy_init();`
`curl_easy_setopt(conn, CURLOPT_URL, "http://www.google.com");`
`curl_easy_setopt(conn, CURLOPT_DEBUGFUNCTION, 1L);`
`curl_easy_setopt(conn, CURLOPT_VERBOSE, 1L);`
`CURLcode code = curl_easy_perform(conn);`
`return 0;`
`}`

When either `curl_easy_setopt(conn, CURLOPT_DEBUGFUNCTION, 1L);` or `curl_easy_setopt(conn, CURLOPT_VERBOSE, 1L);` is commented out, then the program can run successfully. Am I not supposed to use both options at the same time?

I'm using g++ 4.8.5 with libcurl 7.37.0 and 7.49.1 and they both crashes on this case.

**Comment by bagder** [comment]
CURLOPT_DEBUGFUNCTION is a callback and must be made to point to a correct function.

**Comment by topherchen** [comment]
Oops, somehow I didn't catch that from the document. Comment out the CURLOPT_VERBOSE make it run successfully make me think I'm using it correctly but apparently I'm not. Thanks for clarification!
