### ISSUE TITLE
Cirrus CI FreeBSD builds failing due to missing py38-pip

### ISSUE THREAD

**Issue by jay** [curl/curl#9201]
Since Jul 8, FreeBSD 13.1 build has been failing and now also 12.3.
~~~
pkg: No packages available to install matching 'py38-pip' have been found in the repositories
~~~

Ref: https://github.com/curl/curl/pull/8783

@pheiduck @danielgustafsson

**Comment by pheiduck** [comment]
Hey @jay, will work on it.
