### ISSUE TITLE
HTTP/3: Busy loop due to IP_RECVERR

### ISSUE THREAD

**Issue by tatsuhiro-t** [curl/curl#9209]
### I did this

Upload a large file with HTTP/3.
Lots of POLLIN event occurs but recvfrom read nothing.

It is caused by IP_RECVERR socket option [1] set for UDP socket.  ngtcp2 does UDP Path MTU Discovery and it might send larger packet than the path can sustain.  In this case ICMP message is received, it is resulted in POLLERR, which is translated into POLLIN by curl code.  Because IP_RECVERR, the normal recvfrom call does not clear error queue, thus poll keeps returning POLLERR.
It is only cleared by recvmsg with MSG_ERRQUEUE.  But it looks like there is no code in curl to do this.

[1] https://github.com/curl/curl/blob/e28edb6678cd02aea7fc73340c223f26dba8f5b7/lib/connect.c#L1670-L1682

### curl/libcurl version

curl master branch with ngtcp2 QUIC backend
[curl -V output]

### operating system

Linux

**Comment by tatsuhiro-t** [comment]
The simple fix is not set this option for QUIC.
I'm curious that IP_RECVERR really works in libcurl as expected because I could not find recvmsg + MSG_ERRQUEUE in libcurl code.
If libcurl accepts file descriptor from an application, it can do recvmsg, but not sure it is supported and there are any indication from libcurl to show the error is enqueued.

**Comment by bagder** [comment]
#6341 and d13179db3e88d brought the `IP_RECVERR` use. Maybe we should revert that again?

/cc @crrodriguez

**Comment by crrodriguez** [comment]
huh.. well..this is probably the only widespread use of UDP sockets with CURL.. I guess you can revert it safely.

**Comment by bagder** [comment]
Well, curl has as also done TFTP since 2005...
