### ISSUE TITLE
curl_addrinfo.c error: 'getaddrinfo' undeclared in old-MinGW CI builds

### ISSUE THREAD

**Issue by bagder** [curl/curl#9214]
The appveyor CI builds with cmake using Visual Studio 2022 are permafailing since a while back. See [log](https://ci.appveyor.com/project/curlorg/curl/builds/44285128/job/78pv85j280cnnghh)

The compiler errors are:
~~~
C:/projects/curl/lib/curl_addrinfo.c: In function 'Curl_getaddrinfo_ex':
C:/projects/curl/lib/curl_addrinfo.c:192:5: error: implicit declaration of function 'freeaddrinfo'; did you mean 'getaddrinfo'? [-Werror=implicit-function-declaration]
  192 |     freeaddrinfo(aihead);
      |     ^~~~~~~~~~~~
      |     getaddrinfo
C:/projects/curl/lib/curl_addrinfo.c:192:5: error: nested extern declaration of 'freeaddrinfo' [-Werror=nested-externs]
C:/projects/curl/lib/curl_addrinfo.c: In function 'curl_dbg_getaddrinfo':
C:/projects/curl/lib/curl_addrinfo.c:556:14: error: 'getaddrinfo' undeclared (first use in this function); did you mean 'addrinfo'?
  556 |   int res = (getaddrinfo)(hostname, service, hints, result);
      |              ^~~~~~~~~~~
      |              addrinfo
C:/projects/curl/lib/curl_addrinfo.c:556:14: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: all warnings being treated as errors
make[2]: *** [lib/CMakeFiles/libcurl.dir/build.make:242: lib/CMakeFiles/libcurl.dir/curl_addrinfo.c.obj] Error 1

**Comment by gvanem** [comment]
Looks like a `_WIN32_WINNT >= 0x0602` is not set on AppVeyor. But I fail to understand which SDK is used and how CMake uses it.

**Comment by mback2k** [comment]
Ping @MarcelRaad

**Comment by MarcelRaad** [comment]
This is the classic MinGW build, which uses MinGW's own SDK and defaults to `_WIN32_WINNT`= 0x500`. I haven't investigated yet what broke it.

**Comment by MarcelRaad** [comment]
https://github.com/curl/curl/commit/8ba22ffb2030ed91312fc8634e29516cdf0a9761 removed forcing `_WIN32_WINNT` to `0x501`, which previously made `getaddrinfo` and `freeaddrinfo` available for classic MinGW.
But why does https://github.com/curl/curl/blob/d48dd1573c93594284b9d2695df90646d19adf88/CMakeLists.txt#L1069 set `HAVE_GETADDRINFO`? The autotools builds correctly determine it to be unavailable, and I currently don't have a CMake setup usable with classic MinGW 😕

**Comment by vszakats** [comment]
@MarcelRaad: In `CMake/Platforms/WindowsCache.cmake` there is this:
```cmake
    if(ENABLE_IPV6)
      set(HAVE_GETADDRINFO 1)
    else()
      set(HAVE_GETADDRINFO 0)
    endif()
```

Can it be related to your issue?
