### ISSUE TITLE
iOS sectransp breaks unless CURL_CA_BUNDLE=none is passed at configure time

### ISSUE THREAD

**Issue by redbaron** [curl/curl#9225]
### I did this

Built curl for iOS with `sectransp` TLS backend and didn't pass CURL_CA_BUNDLE=none at configuration time. Then attempted to make HTTPS request. Request fails on the iOS device, because it can't find /etc/ssl/cert.pem (value detected on my Mac at curl configuration time).

Confusingly, request didn't fail on iphone simulator, presumably because it was able to locate that file.

Passing CURL_CA_BUNDLE=none  at configure time fixes the problem.

Note, that my dependency manager (vcpkg) already passed CURL_CA_PATH=none, so possibly CURL_CA_PATH has same negative effect on iOS .

### I expected the following

Request doesn't fail with SSL error

### curl/libcurl version

7.82

### operating system

iOS

**Comment by nickzman** [comment]
How are you building curl? I just tried configuring it with simply `--with-secure-transport` set, and the cert bundle was disabled as expected.

If you configure it with a certificate bundle, then Secure Transport probably won't work unless that bundle is present. I don't think that's a bug.

And yes, I would expect that to work with the iOS Simulator, since the simulator can load and save files outside of the app's sandbox.

**Comment by redbaron** [comment]
@nickzman , 

These options were passed to CMakeLists.txt:

```
  -DUSE_NGHTTP2=OFF -DCURL_USE_OPENSSL=OFF -DCURL_USE_MBEDTLS=OFF
  -DCURL_USE_LIBSSH2=OFF -DBUILD_CURL_EXE=OFF -DENABLE_ARES=OFF
  -DCURL_WINDOWS_SSPI=OFF -DCURL_BROTLI=OFF -DCURL_USE_SCHANNEL=OFF
  -DCURL_USE_SECTRANSP=ON -DUSE_LIBIDN2=OFF -DUSE_WIN32_IDN=OFF
  -DUSE_WIN32_LDAP=OFF -DHTTP_ONLY=ON -DCURL_DISABLE_LDAP=ON
  -DCURL_CA_PATH=none  -DBUILD_TESTING=OFF
  -DENABLE_MANUAL=OFF -DCURL_STATICLIB=1 -DCMAKE_DISABLE_FIND_PACKAGE_Perl=ON
  -DENABLE_DEBUG=ON -DCURL_CA_FALLBACK=ON
  ```
  
  adding `-DCURL_CA_BUNDLE=none`  fixes SSL for the iOS build for me.

**Comment by nickzman** [comment]
I don't consider this to be a bug, sorry. If a certificate bundle is set, then the bundle has to be present for curl to load the certificates. Looking at some of the other back-ends, this is consistent with what they do as well so far as I can tell.

Also, the CMake build may set a bundle by default; I wouldn't dare change that, or it would screw up [others' workflows](https://xkcd.com/1172/).

**Comment by redbaron** [comment]
Combination of -DCURL_USE_SECTRANSP and -DCURL_CA_BUNDLE=none produces broken build, do you agree? Changing CURL_CA_BUNDLE default to none if SECTRANSP is in use will solve it

**Comment by nickzman** [comment]
No, because the build worked for me when I tried it. And I don't feel comfortable with messing with CMake defaults that might break some peoples' workflows. Just set `CURL_CA_BUNDLE_SET` to false if you're using CMake to build curl, and you don't want curl to use a CA bundle by default.
