### ISSUE TITLE
When http redirect to https,curl failed and lost body，why?

### ISSUE THREAD

**Issue by MingningShao** [curl/curl#923]
### I did this
I open https with spring boot,and redirect http requests to https,used differenced port.I want to sent request with curl,but post redirected to get,put/delete lost body.I used postman else,but it worked fun.
For example,a post request:
curl -L -k -i -X POST -H "Content-Type: application/json" http://localhost:port/data --data 'JsonValue'
status 400
curl -i -X POST -H "Content-Type: application/json" http://localhost:port/data --data 'JsonValue'
status 302
### I expected the following
operation succeed.status code 200,but in fact is returns 400 or 302.
### curl/libcurl version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
[curl -V output perhaps?]
### operating system
Ubuntu

**Comment by bagder** [comment]
1. You're using a fairly old curl version
2. Your use of -X will override what curl would otherwise do (act on the particular response code)
3. Can you please show us *exactly* what curl sent and received so that we can understand the issue better?

**Comment by bagder** [comment]
No response, probably user error.

**Comment by MingningShao** [comment]
@bagder When i curl -L,it returned a 302.I googled,somebody said ,
When curl follows a redirect and the request is not a plain GET (for example POST or PUT), it will do the following request with a GET if the HTTP response was 301, 302, or 303. If the response code was any other 3xx code, curl will re-send the following request using the same unmodified method.

To keep your data, you mustn't use a 301, 302 or 303 redirection but the 307 redirection.

Dose it make any sense?

**Comment by jay** [comment]
You are using curl incorrectly. Please read [Unnecessary use of curl -X](https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/), in particular:

> One of most obvious problems is that if you also tell curl to follow HTTP redirects (using -L or –location), the -X option will also be used  on the redirected-to requests which may not at all be what the server asks for and the user expected. Dropping the -X will make curl adhere to what the server asks for. And if you want to alter what method to use in a redirect, curl already have dedicated options for that named [--post301](http://curl.haxx.se/docs/manpage.html#--post301), [--post302](http://curl.haxx.se/docs/manpage.html#--post302) and [--post303](http://curl.haxx.se/docs/manpage.html#--post303)!

**Comment by MingningShao** [comment]
@jay Well,the command --post302 worked.
That's interesting.
Finally i read the official doc and find what i want. 
Thank a lot.
@bagder Thanks!
