### ISSUE TITLE
curl_easy_header fails when requesting CURLH_PSEUDO headers

### ISSUE THREAD

**Issue by charonn0** [curl/curl#9235]
### I did this
Call `curl_easy_header` with the `CURLH_PSEUDO` origin, either alone or in a bitmask of other origins.

### I expected the following
To receive a pointer to the header struct. Instead libcurl returns `CURLHE_BAD_ARGUMENT`. It looks like pseudo headers were omitted from a sanity check: https://github.com/curl/curl/blob/master/lib/headers.c#L77

### curl/libcurl version
libcurl/7.84.0 OpenSSL/3.0.4 (Schannel) zlib/1.2.12 brotli/1.0.9 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.48.0 ngtcp2/0.6.0 nghttp3/0.5.0 libgsasl/1.10.0

### operating system
Windows 10 x64

**Comment by bagder** [comment]
Seems entirely correct. Feel free to submit a PR or I will do it soon.
