### ISSUE TITLE
./configure gives warnings regarding functions recently deleted

### ISSUE THREAD

**Issue by Futaura** [curl/curl#9238]
### I did this

Since commit 4d73854462f30948acab12984b611e9e33ee41e6 ./configure is giving warnings like this:

```
./configure: line 22756: CURL_CHECK_HEADER_LDAPSSL: command not found
./configure: line 30552: CURL_CHECK_HEADER_MALLOC: command not found
./configure: line 30553: CURL_CHECK_HEADER_MEMORY: command not found
./configure: line 37071: CURL_CHECK_FUNC_IOCTL: command not found
./configure: line 37497: CURL_CHECK_FUNC_LOCALTIME_R: command not found
./configure: line 40068: CURL_CHECK_FUNC_STRSTR: command not found
./configure: line 40367: CURL_CHECK_FUNC_WRITEV: command not found
```

These functions were removed from acinclude.m4, but the corresponding function calls were not (mostly in configure.ac I think).

### I expected the following

No warnings.

### curl/libcurl version

Latest github master code

### operating system

n/a

**Comment by vszakats** [comment]
Thank you @Futaura, these warnings should be fixed now.
