### ISSUE TITLE
Big files are corrupted after download with 7.83.1

### ISSUE THREAD

**Issue by Antiarchitect** [curl/curl#9242]
### I did this

We use following bash code in order to download ~1.5G zip files served by nginx via secure connection:
```
info "Downloading file..."
curl -q --progress-bar -o "$download_tmp_filename" "$url" || fail "Downlading failed"

info "Extracting archive..."
mkdir "$unzip_tmp_dir"
unzip "$download_tmp_filename" -d "$unzip_tmp_dir" || fail "Archive unpack failed"
```

### I expected the following

Download successful. Zip file matches its checksum.

But sometimes rarely all goes normal with no errors (download and unzipping), but zip file doesn't match it's checksum, moreover internal content of the file (iso, tar) have small zero-filled area where it shouldn't be. I know it sounds misteriousely and leaving issue in hope of other people faced it before.

### curl/libcurl version

```
curl 7.83.1 (armv7l-unknown-linux-gnueabihf) libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

```
Linux localhost 5.15.34-2-rpi-ARCH #1 SMP Fri Jun 3 06:14:48 MSK 2022 armv7l GNU/Linux
```

**Comment by jay** [comment]
Is the URL HTTP(S)? Use options [--fail](https://curl.se/docs/manpage.html#-f) (fail without output on server errors, >= HTTP code 400) and [--location](https://curl.se/docs/manpage.html#-L) (follow redirects on 3xx HTTP code) to ensure the output you are getting is the intended output and not the server replying with error content or redirect content.

Once that is addressed do you have any way for us to reproduce this issue?

**Comment by dfandrich** [comment]
Have you ruled out filesystem corruption as the cause?  If this is an embedded
system might it be poor quality flash or RAM causing this? That seems a more likely
cause to me than curl, since this is the most basic of downloading command used
by just about every curl installation.

**Comment by Antiarchitect** [comment]
@dfandrich I understand the mystery of this case. And statistically wget is doing well for some reason. If this is an fs issue it's very sophisticated too.

**Comment by bagder** [comment]
It seems likely that the lack of `-f` is the reason and there was some non-2xx response with content. That's not a curl bug.

**Comment by Antiarchitect** [comment]
Closing for now - leaving for the history.

**Comment by dfandrich** [comment]
I don't see how lack of -f would cause zero-filled areas in the file.

**Comment by jay** [comment]
> I don't see how lack of -f would cause zero-filled areas in the file.

There's not enough information to know what is happening.
