### ISSUE TITLE
unresolved external symbol __imp__unlink

### ISSUE THREAD

**Issue by kajakoenders1** [curl/curl#9246]
### I did this
Compiled CURl libs, added them to VS
### I expected the following
To be able to use the library
### curl/libcurl version
curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
### operating system
Windows 10

PROBLEM:

![image](https://user-images.githubusercontent.com/65176671/182893838-af9bbf34-3955-4038-a90a-02abdcafed18.png)

Still getting these errors
```unresolved external symbol __imp__unlink```

**Comment by jay** [comment]
> Still getting these errors
> `unresolved external symbol __imp__unlink`

Did you build curl using the same version of Visual Studio that you are using to build your project? What version of Visual Studio? Can you tell us how to reproduce this?

**Comment by MarcelRaad** [comment]
These are symbols from the CRT, and the `__imp__` prefix means dynamic CRT (/MD(d)). Are you trying to link an application using a static CRT (/MT(d)) to a libcurl built against the dynamic CRT?

**Comment by kajakoenders1** [comment]
It works whenever I use "Multi-threaded DLL (/MD)" but I need to use "Multi-threaded (/MT)", how can I fix this?

**Comment by kajakoenders1** [comment]
> 

yes, 2022

**Comment by kajakoenders1** [comment]
> > Still getting these errors
> > `unresolved external symbol __imp__unlink`
> 
> Did you build curl using the same version of Visual Studio that you are using to build your project? What version of Visual Studio? Can you tell us how to reproduce this?

Yes, 2022

**Comment by MarcelRaad** [comment]
> It works whenever I use "Multi-threaded DLL (/MD)" but I need to use "Multi-threaded (/MT)", how can I fix this?

Build libcurl with the static runtime too. How to do this depends on the build system used for building libcurl.

**Comment by bagder** [comment]
This is not a curl bug, but a matter of building things on Windows.
