### ISSUE TITLE
The TCP handshake is well done, but no Client Hello of TLS sent from client since 7.82

### ISSUE THREAD

**Issue by ustcqidi** [curl/curl#9249]
### I did this
After upgrading libcURL to version 7.82.0, we have encountered the connection issues sometimes. Everything works OK when we use version 7.74.0

The TCP handshake is well done, but no TLS Client Hello sent from client, and cause Server shutdown the connections after about 30 seconds.

Here is the screenshot from wireshark, it seems to some status or flags about the TCP connection is incorrect and make TLS conections stuck.

![image](https://user-images.githubusercontent.com/2238185/182991684-bf2c9bac-7c5e-4737-a1d5-f1df23eb0434.png)

We can not easily reproduce this issue, which was reported by TA testing

### curl/libcurl version
we are using 7.82.0 with OpenSSL/1.1.1n

### operating system
windows / mac

**Comment by ustcqidi** [comment]
We can not easily reproduce this issue, which was reported by TA testing

**Comment by gvanem** [comment]
This is a normal closure of the connection. 
Add `CURLOPT_VERBOSE` to your code see why it gets closed. 
Or try the same in `curl -v <url>` and different SSL backends:
 `c:\>set CURL_SSL_BACKEND=schannel` (`openssl`, `rustls` etc).

**Comment by bagder** [comment]
@ustcqidi please tell us more details. Like for example how to reproduce the problem and what happens

**Comment by bagder** [comment]
Lack of details and info. Closing.
