### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by martrix78** [curl/curl#925]
### I did this
configure and make
### I expected the following
Вход в каталог `/home/martrix/tmp/3333/curl/lib'
  CC       vtls/libcurl_la-openssl.lo
vtls/openssl.c: In function 'ssl_ui_writer':
vtls/openssl.c:333:5: error: invalid storage class for function 'cert_stuff'
 int cert_stuff(struct connectdata *conn,
     ^
vtls/openssl.c:642:12: error: invalid storage class for function 'x509_name_oneline'
 static int x509_name_oneline(X509_NAME *a, char *buf, size_t size)
            ^
vtls/openssl.c:673:14: error: invalid storage class for function 'ossl_strerror'
 static char *ossl_strerror(unsigned long error, char *buf, size_t size)
              ^
vtls/openssl.c:1070:17: error: invalid storage class for function 'verifyhost'
 static CURLcode verifyhost(struct connectdata *conn, X509 *server_cert)
                 ^
vtls/openssl.c:1270:17: error: invalid storage class for function 'verifystatus'
 static CURLcode verifystatus(struct connectdata *conn,
                 ^
vtls/openssl.c:1402:20: error: invalid storage class for function 'ssl_msg_type'
 static const char *ssl_msg_type(int ssl_ver, int msg)
                    ^
vtls/openssl.c:1464:20: error: invalid storage class for function 'tls_rt_type'
 static const char *tls_rt_type(int type)
                    ^
vtls/openssl.c:1488:13: error: invalid storage class for function 'ssl_tls_trace'
 static void ssl_tls_trace(int direction, int ssl_ver, int content_type,
             ^
vtls/openssl.c:1599:1: error: invalid storage class for function 'select_next_protocol'
 select_next_protocol(unsigned char **out, unsigned char *outlen,
 ^
vtls/openssl.c:1615:1: error: invalid storage class for function 'select_next_proto_cb'
 select_next_proto_cb(SSL *ssl,
 ^
vtls/openssl.c:1652:1: error: invalid storage class for function 'get_ssl_version_txt'
 get_ssl_version_txt(SSL *ssl)
 ^
vtls/openssl.c:1674:17: error: invalid storage class for function 'ossl_connect_step1'
 static CURLcode ossl_connect_step1(struct connectdata *conn, int sockindex)
                 ^
vtls/openssl.c:2125:17: error: invalid storage class for function 'ossl_connect_step2'
 static CURLcode ossl_connect_step2(struct connectdata *conn, int sockindex)
                 ^
vtls/openssl.c:2252:12: error: invalid storage class for function 'asn1_object_dump'
 static int asn1_object_dump(ASN1_OBJECT *a, char *buf, size_t len)
            ^
vtls/openssl.c:2275:13: error: invalid storage class for function 'pubkey_show'
 static void pubkey_show(struct Curl_easy *data,
             ^
vtls/openssl.c:2308:12: error: invalid storage class for function 'X509V3_ext'
 static int X509V3_ext(struct Curl_easy *data,
            ^
vtls/openssl.c:2361:17: error: invalid storage class for function 'get_cert_chain'
 static CURLcode get_cert_chain(struct connectdata *conn,
                 ^
vtls/openssl.c:2602:17: error: invalid storage class for function 'pkp_pin_peer_pubkey'
 static CURLcode pkp_pin_peer_pubkey(struct Curl_easy *data, X509* cert,
                 ^
vtls/openssl.c:2666:17: error: invalid storage class for function 'servercert'
 static CURLcode servercert(struct connectdata *conn,
                 ^
vtls/openssl.c:2824:17: error: invalid storage class for function 'ossl_connect_step3'
 static CURLcode ossl_connect_step3(struct connectdata *conn, int sockindex)
                 ^
vtls/openssl.c:2888:18: error: invalid storage class for function 'ossl_recv'
 static Curl_recv ossl_recv;
                  ^
vtls/openssl.c:2889:18: error: invalid storage class for function 'ossl_send'
 static Curl_send ossl_send;
                  ^
vtls/openssl.c:2891:17: error: invalid storage class for function 'ossl_connect_common'
 static CURLcode ossl_connect_common(struct connectdata *conn,
                 ^
vtls/openssl.c: In function 'ossl_connect_common':
vtls/openssl.c:2989:29: error: 'ossl_recv' undeclared (first use in this function)
     conn->recv[sockindex] = ossl_recv;
                             ^
vtls/openssl.c:2989:29: note: each undeclared identifier is reported only once for each function it appears in
vtls/openssl.c:2990:29: error: 'ossl_send' undeclared (first use in this function)
     conn->send[sockindex] = ossl_send;
                             ^
vtls/openssl.c: In function 'ssl_ui_writer':
vtls/openssl.c:3032:16: error: invalid storage class for function 'ossl_send'
 static ssize_t ossl_send(struct connectdata *conn,
                ^
vtls/openssl.c:3086:16: error: invalid storage class for function 'ossl_recv'
 static ssize_t ossl_recv(struct connectdata *conn, /* connection data */
                ^
vtls/openssl.c:3218:1: error: expected declaration or statement at end of input
 }
 ^

### curl/libcurl version
7.50.1

### operating system
Linux Mint 17.2

**Comment by bagder** [comment]
> 7.50.1

You mean straight off git then? There's not been any release of 7.50.1 yet.

What openssl version are you using? What configure line did you use? What compiler and version are you using?

**Comment by bagder** [comment]
No response, probably user error.
