### ISSUE TITLE
Curl does not parse correctly the "qop=" parameter of Digest authentication

### ISSUE THREAD

**Issue by vlubart** [curl/curl#9264]
When parsing the "qop=" parameter of the digest authentication Curl uses “,” delimiter. See function auth_digest_get_qop_values() in https://github.com/curl/curl/blob/40b6206085987a48c711fe30f1613d2e3c522ace/lib/vauth/digest.c#L235   : 
  token = strtok_r(tmp, ",", &tok_buf);
The same at https://github.com/curl/curl/blob/40b6206085987a48c711fe30f1613d2e3c522ace/lib/vauth/digest.c#L244 .

According to RFC https://www.ietf.org/rfc/rfc7616.html the qop delimiter can actually include a whitespace , as in the example that appears in the RFC : 
   HTTP/1.1 401 Unauthorized
   WWW-Authenticate: Digest
       realm="http-auth@example.org",
       qop="auth, auth-int",
(comma-whitespace instead of just comma)

In this case Curl would wrongly parse a token " auth-int" (with leading whitespace) instead of just "auth-int".
Found on Ubuntu 21.04

**Comment by vlubart** [comment]
Thanks for the quick resolution! When a release with this fix can be expected ?

**Comment by bagder** [comment]
This will be including in the next release. 7.85.0 is expected to ship on August 31.
