### ISSUE TITLE
error when cross-compiling with musl toolchain on glibc 

### ISSUE THREAD

**Issue by scuderia666** [curl/curl#9273]
### I did this

I am making a Linux distro and curl is the last package I need to complete the toolchain, I could compile all of the other packages but somehow I couldn't get curl working. I need libcurl for the package manager.

**configure options:**
i passed the root containing the libraries to --with-sysroot, and the --host. Changing other options didn't make any difference.

CCLD     libcurl.la
/bin/sed: can't read /usr/lib/libcrypto.la: No such file or directory
libtool:   error: '/usr/lib/libcrypto.la' is not a valid libtool archive

**lib/libcurl.la has this:**
dependency_libs=' /home/satou/rootfs/usr/lib/libssl.la /usr/lib/libcrypto.la /home/satou/rootfs/usr/lib/libcrypto.la -lz'

i dont know why /usr/lib/libcrypto.la is there, because after that i have /home/satou/rootfs/usr/lib/libcrypto.la which works.

**more info:**
found in curl-config:
echo ${CURLLIBDIR}-lcurl -lssl -lcrypto -lssl -lcrypto -lz

### I expected the following

a working libcurl.la

### curl/libcurl version

7.84.0

### operating system

cross-compiling with musl x84_64 toolchain on glibc x86_64 host

**Comment by bagder** [comment]
This doesn't contain enough details for us to reproduce the problem, nor did you provide logs that could make us understand what happened to you. I don't see what we can do here.

**Comment by scuderia666** [comment]
> This doesn't contain enough details for us to reproduce the problem, nor did you provide logs that could make us understand what happened to you. I don't see what we can do here.

Oh sorry, here is the log: https://rentry.co/8sduqg

**Comment by bagder** [comment]
curl's configure script itself does not put `/usr/lib/libcrypto.la` in there so it needs to come from somewhere. You need to research how it appears. Did you check the other .la files you might be using in the build? I know in the past we've seen errors like this when (other) packages insert /usr/lib for example in the pkg-config output, but I couldn't see anything like that in the log you link to...

**Comment by scuderia666** [comment]
I don't know why and how but using '--without-ssl' worked. Also I know that problem is caused by my pkgconf and I will fix it later. Thank you for your help.
