### ISSUE TITLE
Http digest authentication doesn't support 'stale=true'

### ISSUE THREAD

**Issue by tarek112** [curl/curl#928]
### I did this

Build using cmake with default options under windows (so using windows SSPI). Loop on a GET request to reach a digest authenticated resource. Reuse easy handle between requests.
### I expected the following

Keep working after 401 ... "stale=true".  
First authentication works well but after that first nonce expire, curl doesn't handle any further authentication. It keep using the initial nonce. 
### curl/libcurl version

7.50.0
### operating system

Windows

I think I've found were the issue comes from and I should provide a pull request soon.

**Comment by tarek112** [comment]
I tested you patch, it's working good. Thank you

**Comment by tarek112** [comment]
Hello, still no issue with your patch. Is there something I can do to help with MR ?

**Comment by bagder** [comment]
Are you referring to @jay's commit from July 26th?

**Comment by tarek112** [comment]
Yes indeed: https://github.com/jay/curl/commit/22c44c73dffac239df2bb8caca535a8c46ca5c4a

**Comment by bagder** [comment]
@jay any news or thoughts on where this is going?

**Comment by jay** [comment]
Thanks, landed in af5fbb1.
