### ISSUE TITLE
curl 7.50.0 compiles error on Mac OSX

### ISSUE THREAD

**Issue by eaglewangy** [curl/curl#930]
### Mac OS 10.11.5

make[2]: *** No rule to make target `http_negotiate_sspi.c', needed by `libcurl_la-http_negotiate_sspi.lo'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by eaglewangy** [comment]
Wangs-iMac:curl wangying$ make
Making all in lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       libcurl_la-file.lo
  CC       libcurl_la-timeval.lo
  CC       libcurl_la-base64.lo
  CC       libcurl_la-hostip.lo
  CC       libcurl_la-progress.lo
  CC       libcurl_la-formdata.lo
  CC       libcurl_la-cookie.lo
  CC       libcurl_la-http.lo
  CC       libcurl_la-sendf.lo
  CC       libcurl_la-ftp.lo
  CC       libcurl_la-url.lo
  CC       libcurl_la-dict.lo
  CC       libcurl_la-if2ip.lo
  CC       libcurl_la-speedcheck.lo
  CC       libcurl_la-ldap.lo
ldap.c:220:8: warning: 'ldap_url_parse' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
  rc = ldap_url_parse(data->change.url, &ludp);
       ^
/usr/include/ldap.h:2065:1: note: 'ldap_url_parse' has been explicitly marked deprecated here
ldap_url_parse LDAP_P((
^
ldap.c:225:35: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    failf(data, "LDAP local: %s", ldap_err2string(rc));
                                  ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:263:3: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
  ldap_set_option(NULL, LDAP_OPT_NETWORK_TIMEOUT, &ldap_timeout);
  ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:265:3: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
  ldap_set_option(NULL, LDAP_OPT_PROTOCOL_VERSION, &ldap_proto);
  ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:339:12: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      rc = ldap_set_option(NULL, LDAP_OPT_X_TLS_CACERTFILE, ldap_ca);
           ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:342:17: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                ldap_err2string(rc));
                ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:351:10: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    rc = ldap_set_option(NULL, LDAP_OPT_X_TLS_REQUIRE_CERT, &ldap_option);
         ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:354:15: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_err2string(rc));
              ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:358:14: warning: 'ldap_init' is deprecated: first deprecated in OS X 10.10 - use ldap_initialize
      [-Wdeprecated-declarations]
    server = ldap_init(host, (int)conn->port);
             ^
/usr/include/ldap.h:1526:1: note: 'ldap_init' has been explicitly marked deprecated here
ldap_init LDAP_P(( /* deprecated, use ldap_create or ldap_initialize */
^
ldap.c:366:10: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    rc = ldap_set_option(server, LDAP_OPT_X_TLS, &ldap_option);
         ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:369:15: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_err2string(rc));
              ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:394:14: warning: 'ldap_init' is deprecated: first deprecated in OS X 10.10 - use ldap_initialize
      [-Wdeprecated-declarations]
    server = ldap_init(host, (int)conn->port);
             ^
/usr/include/ldap.h:1526:1: note: 'ldap_init' has been explicitly marked deprecated here
ldap_init LDAP_P(( /* deprecated, use ldap_create or ldap_initialize */
^
ldap.c:406:8: warning: 'ldap_simple_bind_s' is deprecated: first deprecated in OS X 10.10 - use ldap_sasl_bind_s
      [-Wdeprecated-declarations]
  rc = ldap_simple_bind_s(server, user, passwd);
       ^
/usr/include/ldap.h:1291:1: note: 'ldap_simple_bind_s' has been explicitly marked deprecated here
ldap_simple_bind_s LDAP_P(( /* deprecated, use ldap_sasl_bind_s */
^
ldap.c:409:5: warning: 'ldap_set_option' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    ldap_set_option(server, LDAP_OPT_PROTOCOL_VERSION, &ldap_proto);
    ^
/usr/include/ldap.h:984:1: note: 'ldap_set_option' has been explicitly marked deprecated here
ldap_set_option LDAP_P((
^
ldap.c:410:10: warning: 'ldap_simple_bind_s' is deprecated: first deprecated in OS X 10.10 - use ldap_sasl_bind_s
      [-Wdeprecated-declarations]
    rc = ldap_simple_bind_s(server, user, passwd);
         ^
/usr/include/ldap.h:1291:1: note: 'ldap_simple_bind_s' has been explicitly marked deprecated here
ldap_simple_bind_s LDAP_P(( /* deprecated, use ldap_sasl_bind_s */
^
ldap.c:413:54: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    failf(data, "LDAP local: ldap_simple_bind_s %s", ldap_err2string(rc));
                                                     ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:418:8: warning: 'ldap_search_s' is deprecated: first deprecated in OS X 10.10 - use ldap_search_ext_s
      [-Wdeprecated-declarations]
  rc = ldap_search_s(server, ludp->lud_dn, ludp->lud_scope,
       ^
/usr/include/ldap.h:1925:1: note: 'ldap_search_s' has been explicitly marked deprecated here
ldap_search_s LDAP_P((  /* deprecated, use ldap_search_ext_s */
^
ldap.c:422:36: warning: 'ldap_err2string' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    failf(data, "LDAP remote: %s", ldap_err2string(rc));
                                   ^
/usr/include/ldap.h:1384:1: note: 'ldap_err2string' has been explicitly marked deprecated here
ldap_err2string LDAP_P((
^
ldap.c:427:32: warning: 'ldap_first_entry' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
  for(num = 0, entryIterator = ldap_first_entry(server, ldapmsg);
                               ^
/usr/include/ldap.h:1623:1: note: 'ldap_first_entry' has been explicitly marked deprecated here
ldap_first_entry LDAP_P((
^
ldap.c:429:23: warning: 'ldap_next_entry' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      entryIterator = ldap_next_entry(server, entryIterator), num++) {
                      ^
/usr/include/ldap.h:1628:1: note: 'ldap_next_entry' has been explicitly marked deprecated here
ldap_next_entry LDAP_P((
^
ldap.c:453:25: warning: 'ldap_get_dn' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      char *dn = name = ldap_get_dn(server, entryIterator);
                        ^
/usr/include/ldap.h:1662:1: note: 'ldap_get_dn' has been explicitly marked deprecated here
ldap_get_dn LDAP_P((
^
ldap.c:462:9: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
        ldap_memfree(dn);
        ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:473:9: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
        ldap_memfree(dn);
        ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:483:9: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
        ldap_memfree(dn);
        ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:493:7: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      ldap_memfree(dn);
      ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:497:21: warning: 'ldap_first_attribute' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    for(attribute = ldap_first_attribute(server, entryIterator, &ber);
                    ^
/usr/include/ldap.h:1804:1: note: 'ldap_first_attribute' has been explicitly marked deprecated here
ldap_first_attribute LDAP_P((
^
ldap.c:499:21: warning: 'ldap_next_attribute' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
        attribute = ldap_next_attribute(server, entryIterator, ber)) {
                    ^
/usr/include/ldap.h:1810:1: note: 'ldap_next_attribute' has been explicitly marked deprecated here
ldap_next_attribute LDAP_P((
^
ldap.c:517:14: warning: 'ldap_get_values_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      vals = ldap_get_values_len(server, entryIterator, attribute);
             ^
/usr/include/ldap.h:1820:1: note: 'ldap_get_values_len' has been explicitly marked deprecated here
ldap_get_values_len LDAP_P((
^
ldap.c:522:13: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_value_free_len(vals);
            ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:526:13: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_memfree(attribute);
            ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:528:15: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ber_free(ber, 0);
              ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:536:13: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_value_free_len(vals);
            ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:540:13: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_memfree(attribute);
            ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:542:15: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ber_free(ber, 0);
              ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:549:13: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_value_free_len(vals);
            ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:553:13: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_memfree(attribute);
            ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:555:15: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ber_free(ber, 0);
              ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:571:15: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_value_free_len(vals);
              ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:575:15: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_memfree(attribute);
              ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:577:17: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                ber_free(ber, 0);
                ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:587:17: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                ldap_value_free_len(vals);
                ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:591:17: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                ldap_memfree(attribute);
                ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:593:19: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                  ber_free(ber, 0);
                  ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:605:15: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_value_free_len(vals);
              ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:609:15: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ldap_memfree(attribute);
              ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:611:17: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
                ber_free(ber, 0);
                ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:621:13: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_value_free_len(vals);
            ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:625:13: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
            ldap_memfree(attribute);
            ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:627:15: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
              ber_free(ber, 0);
              ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:636:9: warning: 'ldap_value_free_len' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
        ldap_value_free_len(vals);
        ^
/usr/include/ldap.h:1830:1: note: 'ldap_value_free_len' has been explicitly marked deprecated here
ldap_value_free_len LDAP_P((
^
ldap.c:643:7: warning: 'ldap_memfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
      ldap_memfree(attribute);
      ^
/usr/include/ldap.h:2002:1: note: 'ldap_memfree' has been explicitly marked deprecated here
ldap_memfree LDAP_P((
^
ldap.c:653:8: warning: 'ber_free' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
       ber_free(ber, 0);
       ^
/usr/include/lber.h:454:1: note: 'ber_free' has been explicitly marked deprecated here
ber_free LDAP_P((
^
ldap.c:658:5: warning: 'ldap_msgfree' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    ldap_msgfree(ldapmsg);
    ^
/usr/include/ldap.h:1869:1: note: 'ldap_msgfree' has been explicitly marked deprecated here
ldap_msgfree LDAP_P((
^
ldap.c:664:5: warning: 'ldap_free_urldesc' is deprecated: first deprecated in OS X 10.11 - use OpenDirectory Framework
      [-Wdeprecated-declarations]
    ldap_free_urldesc(ludp);
    ^
/usr/include/ldap.h:2074:1: note: 'ldap_free_urldesc' has been explicitly marked deprecated here
ldap_free_urldesc LDAP_P((
^
ldap.c:666:5: warning: 'ldap_unbind_s' is deprecated: first deprecated in OS X 10.10 - use ldap_unbind_ext_s
      [-Wdeprecated-declarations]
    ldap_unbind_s(server);
    ^
/usr/include/ldap.h:1971:1: note: 'ldap_unbind_s' has been explicitly marked deprecated here
ldap_unbind_s LDAP_P(( /* deprecated, use ldap_unbind_ext_s */
^
55 warnings generated.
  CC       libcurl_la-version.lo
  CC       libcurl_la-getenv.lo
  CC       libcurl_la-escape.lo
  CC       libcurl_la-mprintf.lo
  CC       libcurl_la-telnet.lo
  CC       libcurl_la-netrc.lo
  CC       libcurl_la-getinfo.lo
  CC       libcurl_la-transfer.lo
  CC       libcurl_la-strequal.lo
  CC       libcurl_la-easy.lo
  CC       libcurl_la-security.lo
  CC       libcurl_la-curl_fnmatch.lo
  CC       libcurl_la-fileinfo.lo
  CC       libcurl_la-ftplistparser.lo
  CC       libcurl_la-wildcard.lo
  CC       libcurl_la-krb5.lo
  CC       libcurl_la-memdebug.lo
  CC       libcurl_la-http_chunks.lo
  CC       libcurl_la-strtok.lo
  CC       libcurl_la-connect.lo
  CC       libcurl_la-llist.lo
  CC       libcurl_la-hash.lo
  CC       libcurl_la-multi.lo
  CC       libcurl_la-content_encoding.lo
  CC       libcurl_la-share.lo
  CC       libcurl_la-http_digest.lo
  CC       libcurl_la-md4.lo
  CC       libcurl_la-md5.lo
  CC       libcurl_la-http_negotiate.lo
  CC       libcurl_la-inet_pton.lo
  CC       libcurl_la-strtoofft.lo
  CC       libcurl_la-strerror.lo
  CC       libcurl_la-amigaos.lo
  CC       libcurl_la-hostasyn.lo
  CC       libcurl_la-hostip4.lo
  CC       libcurl_la-hostip6.lo
  CC       libcurl_la-hostsyn.lo
  CC       libcurl_la-inet_ntop.lo
  CC       libcurl_la-parsedate.lo
  CC       libcurl_la-select.lo
  CC       libcurl_la-tftp.lo
  CC       libcurl_la-splay.lo
  CC       libcurl_la-strdup.lo
  CC       libcurl_la-socks.lo
  CC       libcurl_la-ssh.lo
  CC       libcurl_la-rawstr.lo
  CC       libcurl_la-curl_addrinfo.lo
  CC       libcurl_la-socks_gssapi.lo
  CC       libcurl_la-socks_sspi.lo
  CC       libcurl_la-curl_sspi.lo
  CC       libcurl_la-slist.lo
  CC       libcurl_la-nonblock.lo
  CC       libcurl_la-curl_memrchr.lo
  CC       libcurl_la-imap.lo
  CC       libcurl_la-pop3.lo
  CC       libcurl_la-smtp.lo
  CC       libcurl_la-pingpong.lo
  CC       libcurl_la-rtsp.lo
  CC       libcurl_la-curl_threads.lo
  CC       libcurl_la-warnless.lo
  CC       libcurl_la-hmac.lo
  CC       libcurl_la-curl_rtmp.lo
  CC       libcurl_la-openldap.lo
  CC       libcurl_la-curl_gethostname.lo
  CC       libcurl_la-gopher.lo
  CC       libcurl_la-idn_win32.lo
make[2]: *** No rule to make target `http_negotiate_sspi.c', needed by `libcurl_la-http_negotiate_sspi.lo'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by jay** [comment]
That doesn't look right. http_negotiate_sspi was removed in 7.49 since it's now handled by http_negotiate, see 4adee19. If you're building from the repo run ./buildconf and then ./configure again. If you're building from a release tarball extract it to a clean directory instead of overwriting your existing directory.

**Comment by eaglewangy** [comment]
Thanks Jay, after clean the original source then configure & make, it works now. Thanks again.

**Comment by jay** [comment]
No problem, thanks for letting us know it's resolved.
