### ISSUE TITLE
Segmentation fault when misusing the -F argument.

### ISSUE THREAD

**Issue by stefncb** [curl/curl#9302]
### I did this

`curl -F"file@=aaa" https://example.com`

### I expected the following

An error message telling me that @= isn't a thing.

### I got the following

A segmentation fault.

### curl/libcurl version

(I just cloned the repository on master and built it, after initially coming across the issue on the one from the Debian repos)

```
curl 7.85.0-DEV (x86_64-pc-linux-gnu) libcurl/7.85.0-DEV OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
```

### operating system

`Linux eyethree 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux`

**Comment by bagder** [comment]
This does not reproduce for me, with or without valgrind, on Linux.

**Comment by stefncb** [comment]
> This does not reproduce for me, with or without valgrind, on Linux.

I spotted the issue. I replaced the URL I was checking on with https://example.com, but forgot to actually check if it still does it! It reproduces with a URL that actually has a form that accepts `file`, such as https://0x0.st.

Sorry for that.

**Comment by bagder** [comment]
You mean the site that returns a **body** to curl that contains the words `Segmentation fault` and outputs them to the terminal? Add `-v` and you'll see it more clearly.

**Comment by stefncb** [comment]
> You mean the site that returns a **body** to curl that contains the words `Segmentation fault` and outputs them to the terminal? Add `-v` and you'll see it more clearly.

Well that's embarrassing.

**Comment by emanuele6** [comment]
> I spotted the issue. I replaced the URL I was checking on with https://example.com/, but forgot to actually check if it still does it! It reproduces with a URL that actually has a form that accepts file, such as https://0x0.st/.

You are generalising for no reason... (have you tried any other site "that actually has a form that accepts file"?) That "issue" (there is no real issue except that you sent `file@` set to "aaa" while expects `file` set to an attached file, so it will obviously not work/upload the file correctly) only occurs on `0x0.st`.
And the "issue" is that 0x0.st (surely intentionally, not because of a bug) responds with a body containing "Segmentation fault" when you didn't upload the file correctly.

```
bash-5.1$ curl -i -F file@=file.png 0x0.st; echo "$?"
Segmentation fault
0
bash-5.1$ curl -i -F file@=file.png 0x0.st
HTTP/1.1 400 BAD REQUEST
Server: nginx
Date: Fri, 12 Aug 2022 12:16:15 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 19
Connection: keep-alive

Segmentation fault
```
Other similar webites respond with different error messages when they get an unexpected form entry, e.g. `ix.io`:
```
bash-5.1$ curl -F file@=file.jpg ix.io
ERROR file@: file.png
```

**Comment by emanuele6** [comment]
```python3
@app.errorhandler(400)
@app.errorhandler(404)
@app.errorhandler(411)
@app.errorhandler(413)
@app.errorhandler(414)
@app.errorhandler(415)
@app.errorhandler(451)
def ehandler(e):
    try:
        return render_template(f"{e.code}.html", id=id), e.code
    except TemplateNotFound:
        return "Segmentation fault\n", e.code
```

https://git.0x0.st/mia/0x0/src/commit/c7a728ce84111b9a73edf84491afe349a3d0761c/fhost.py#L366

**Comment by stefncb** [comment]
@emanuele6 

I wrongly assumed it's a parsing problem since that's pretty much the only website I use curl to upload files too. Daniel already made me realize my embarrassing mistake.

Thanks for the detailed response though...

**Comment by emanuele6** [comment]
> Daniel already made me realize my embarrassing mistake.

Whoops! sorry :)
