### ISSUE TITLE
curl_easy_init() malloc failure

### ISSUE THREAD

**Issue by 0x3Alex** [curl/curl#9308]
I wanted to play around with CURL in C
I didi:
```
    char *country = "peru";
    char *request = calloc(1,(strlen("https://restcountries.com/v3.1/name/") + strlen(country)));
    strcpy(request,"https://restcountries.com/v3.1/name/");
    strcat(request,country);
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if(!curl) exit(-1);
    curl_easy_setopt(curl,CURLOPT_URL,request);
    res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
```

When running the problem it crashes at the curl = curl_easy_init() with the error message

`Fatal glibc error: malloc assertion failure in sysmalloc: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)`

I do not see a reason for this to crash, because i took (the steps to create a CURL execution) out of a tutorial. 
On StackOverflow they do the same things as me, and it works for them

I am on Linux Manjaro, 64-Bit with 16 GB RAM

**Comment by 0x3Alex** [comment]
When i put the calloc() of my char-array after the curl_easy_init() it works fine, why though?!

**Comment by bagder** [comment]
The `strcat()` overwrites your allocated memory by one byte since the allocation doesn't take the terminating null byte into account. This is not a problem in curl.

You could use valgrind to spot this as well.

**Comment by 0x3Alex** [comment]
I am pretty new to C... never heard about Valgrind though. Gonna check it out. So if i would allocate the everything +1 it should work?
