### ISSUE TITLE
curl with IPv6 address and not valid port output contains "No route to host" instead of "Connection refused"

### ISSUE THREAD

**Issue by silviaserafini** [curl/curl#9323]
### I did this
in one teminal I sent a curl requestl with IPv6 address and not valid port using curl and telnet, getting different outputs:

```
telnet <FQDN> 50937`
Trying <IPv6>                                                                                            
telnet: connect to address <Ipv6>: Connection refused   
```

```
curl -6 http://<FQDN>:50937                            
curl: (7) Failed to connect to <FQDN> port 50937: No route to host
```

In both cases I sent and received the same packages:
```
[# ~]$ tcpdump -i baremetal tcp port 50937
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on baremetal, link-type EN10MB (Ethernet), capture size 262144 bytes

13:29:44.274351 IP6<FQDN>:.47682 > <FQDN>:.50937: Flags [S], seq 4189608559, win 28800, options [mss 1440,sackOK,TS val 1361598992 ecr 0,nop,wscale 7], length 0
13:29:44.274777 IP6 <FQDN>:.50937 > registry.ocp-edge3.lab.eng.tlv2.redhat.com.47682: Flags [R.], seq 0, ack 4189608560, win 0, length 0   
```          
```
13:30:52.255897 IP6<FQDN>:.47686 > <FQDN>: Flags [S], seq 4000682417, win 28800, options [mss 1440,sackOK,TS val 1361666968 ecr 0,nop,wscale 7], length 0
13:30:52.256352 IP6 <FQDN>:> registry.ocp-edge3.lab.eng.tlv2.redhat.com.47686: Flags [R.], seq 0, ack 4000682418, win 0, length 0 `
```

### I expected the following

I expected "Connection refused" in output for both commands (And not No riute to host)

### Notes
In dual stack env, if I force IPv4 I get  the expected answer "Connection refused"
```
[# ~]$ curl -4 <FQDN>:50937
curl: (7) Failed to connect to <FQDN>: port 50937: Connection refused
[# ~]$ curl -6 <FQDN>:50937
curl: (7) Failed to connect to openshift-<FQDN>: No route to host

```

### curl/libcurl version

curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink 

### operating system

[# ~]$ uname -a
Linux 4.18.0-240.el8.x86_64 #1 SMP Wed Sep 23 05:13:10 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
That error explanation is in fact what strerror returns for the particular errno error that the system returned when it failed to connect. If it is wrong, then your kernel/libc sends the wrong value.

**Comment by reihl** [comment]
Can you explain why in telnet we get the "right" error? It's seem like something went wrong with curl that it got the wrong message. Either way, telnet and curl with IPv6 get the same packets from the host

**Comment by bagder** [comment]
I cannot explain it, no, but I have not tried to research it very deep. Here's the libcurl code creating the error message:

https://github.com/curl/curl/blob/ebe3fdb0e36b6fe8929e5fc90bbaf4e97f9cb962/lib/connect.c#L1072

Here's me getting connection refused from ipv6 hosts:

~~~
$ curl -6 localhost:23232
curl: (7) Failed to connect to localhost port 23232 after 0 ms: Connection refused
$ ./src/curl -6 localhost:23232
curl: (7) Failed to connect to localhost port 23232 after 0 ms: Connection refused
$ curl -6 www.haxx.se:81
curl: (7) Failed to connect to www.haxx.se port 81 after 9 ms: Connection refused

$ curl -V
curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0 librtmp/2.3 OpenLDAP/2.5.12

**Comment by bagder** [comment]
I don't see anything else to do here.
