### ISSUE TITLE
curl scp gets stuck

### ISSUE THREAD

**Issue by sindhura730** [curl/curl#933]
I tried to use curl to scp,
$ curl -k -o output scp://sindhu:<pwd>@172.24.1.119://home/sindhu/work/downtech.deb 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 81.8M    1 1616k    0     0  23891      0  0:59:54  0:01:09  0:58:45    

But the command gets stuck, doesn't increase after 1616k. 

$ curl --version
curl 7.50.0-DEV (x86_64-pc-linux-gnu) libcurl/7.50.0-DEV OpenSSL/1.0.2g zlib/1.2.8 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by jay** [comment]
This may be related to [sftp download error in 7.49.1](https://curl.haxx.se/mail/lib-2016-07/0057.html). I reverted the offending commit in a test branch, can you try https://github.com/jay/curl/commit/62da741

**Comment by sindhura730** [comment]
It worked. Thank you.

**Comment by sindhura730** [comment]
Any idea when we can expect a new version with this issue fixed?

**Comment by jay** [comment]
Still testing, latest fix is at https://curl.haxx.se/mail/lib-2016-08/0005.html If you can try it that would be helpful

**Comment by bagder** [comment]
Fix merged commit 6eb60c2dc5. Would be nice if we could get it confirmed it fixes this bug.
