### ISSUE TITLE
macOS: curl can't access certificate in keychain as root

### ISSUE THREAD

**Issue by wAuner** [curl/curl#9339]
### I did this
macOS 12.5.1, curl 7.84.0

I've followed the [official build instructions](https://curl.se/docs/install.html) to build curl locally for macOS with Secure Transport. I adapted them slightly to build a universal binary (x86_64 + arm64):

```
ARCH=arm64
SDK=macosx
DEPLOYMENT_TARGET=10.15

export CFLAGS="-arch $ARCH -arch x86_64 -isysroot $(xcrun -sdk $SDK --show-sdk-path) -m$SDK-version-min=$DEPLOYMENT_TARGET"
./configure --host=$ARCH-apple-darwin --host $ARCH-apple-darwin --prefix $(pwd)/artifacts --with-secure-transport --without-libidn2 --without-nghttp2 --without-zlib -disable-ldap

```

With this build of the CLI as well as a small test program I am able to connect to company url that uses a certificate signed by our internal root CA. This rot CA certificate is added to my macOS system keychain and trusted.
However, when I run my test program or the self compiled cli as root with sudo I get an `Invalid certificate chain`. 
When I do the same with the curl/libcurl that comes with the OS, it works in both cases.

### I expected the following
that my compiled version can access the keychain like the system version, namely as root as well.

### curl/libcurl version

```
OS version
➜ curl -V
curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

```
compiled version
➜ ./curl -V
curl 7.84.0 (aarch64-apple-darwin) libcurl/7.84.0 SecureTransport
Release-Date: 2022-06-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS IPv6 Largefile NTLM NTLM_WB SSL threadsafe UnixSockets
```

### operating system

```
➜ uname -a
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

Am I doing something wrong or is this a bug?

**Comment by nickzman** [comment]
Is the self-signed certificate marked as trusted for all users?

**Comment by wAuner** [comment]
Yes, it is in the system keychain and set to always trust. When I link against the system provided libcurl or use the system curl I am able to connect as the normal user as well as root.

When I do the same with my build it only works as normal user and gives me an error as root.

The only somehow related information I could find, is a [5 year old post on Apple's developer forum](https://developer.apple.com/forums/thread/72686).

**Comment by bagder** [comment]
> With this build of the CLI as well as a small test program I am able to connect to company url that uses a certificate signed by our internal root CA

Did you set a specific TLS backend then or did you use the default? If so, the one in your OS defaults to libressl...

**Comment by wAuner** [comment]
I did not specify a specific TLS backend.
The exact tests I've performed:
```
CLI
./curl companyurl # works
sudo ./curl companyurl # invalid certificate chain

curl companyurl # works 
sudo curl companyurl # works
```
Same results for the`https.c` example code with the same companyurl. 
When I link against Apple's OS curl distribution it works as root as well. But when I link against my compiled version, it fails as root.

Is there something obvious I'm missing here?

**Comment by bagder** [comment]
I don't know if you miss it or not, but your OS libcurl is built to use **libressl** for TLS and your own build uses Secure Transport. It suggests they have to very different code paths to executing your wishes. I'm just thinking it may explain or help explain the differences.

**Comment by wAuner** [comment]
Thanks for your help. 
Yes I get that I didn't compile with libressl. I just followed the official build instruction which suggested that Secure Transport is the way to go for accessing the certificates in the macOS keychain.

> because Secure Transport uses the certificates stored in the Keychain to evaluate whether or not to trust the server.
[Docs](https://curl.se/docs/install.html)

I was hoping that this might be enough.
But I realize that I'm out of my depth here.

**Comment by bagder** [comment]
I don't think there is anything we can do here. The TLS behavior and how it works with root on a macOS system seems to be outside of curl's realm.
