### ISSUE TITLE
Travis CI OS X builds not working

### ISSUE THREAD

**Issue by jay** [curl/curl#934]
buildconf fails due to missing libtoolize:
```
$ ./buildconf
buildconf: autoconf version 2.69 (ok)
buildconf: autom4te version 2.69 (ok)
buildconf: autoheader version 2.69 (ok)
buildconf: automake version 1.14.1 (ok)
buildconf: aclocal version 1.14.1 (ok)
buildconf: libtoolize not found.
  You need GNU libtoolize 1.4.2 or newer installed.
```
I tried `brew install libtool` but it's already installed: `Error: libtool-2.4.2 already installed`.

So I'm not sure what's going on here. In buildconf [there's a check for libtoolize and also glibtoolize](https://github.com/curl/curl/blob/master/buildconf#L192-L220), and beyond that my understanding of this is just about limited to [this stackoverflow question](http://stackoverflow.com/q/15448582).

**Comment by snikulov** [comment]
Hello @jay. The problem is related to Travis environment. It is not related to curl's build itself.
Here the same issue https://github.com/neovim/homebrew-neovim/issues/167
Workaround - re-installing libtool.
I've provided PR #939 for that.

**Comment by DomT4** [comment]
You shouldn't need to reinstall `libtool` from source; the bottle was updated when we fixed this issue. `brew reinstall libtool` should suffice.

Travis doesn't upgrade the formulae pre-installed on the boxes themselves super regularly so sometimes things like this linger.

**Comment by snikulov** [comment]
@DomT4 could you please tell is when we'll remove this reinstall completely?

**Comment by DomT4** [comment]
That's not something I have power over sadly, that's a Travis decision. We're hoping to persuade them to rebuild the boxes once we've finished making this current series of design/feature tweaks to brew, but I can't stick a date on that yet & I can't promise Travis won't turn around and say no.

**Comment by snikulov** [comment]
So the only thing I should do - just change current line to ```brew reinstall libtool``` and remove ```-s``` flag? Am I correct?

**Comment by DomT4** [comment]
Not sure if your comment got deleted or I'm having caching issues locally but:

> So the only thing I should do - just change current line to brew reinstall libtool and remove -s flag? Am I correct?

Yes.

**Comment by snikulov** [comment]
I re-read your first comment and delete mine :)
Sorry for noise.

**Comment by DomT4** [comment]
No worries 😄. I tend to quickly glance through `curl` issues but if there's something specifically Homebrew related feel free to @ one of the team for an opinion.
