### ISSUE TITLE
Curl fails to transfer files to server via webdav

### ISSUE THREAD

**Issue by bak-nisz** [curl/curl#9343]
Using Curl with LibreOffice as for saving files to remote servers via WebDAV fails. The LibreOffice uses that since its 7.3 series and when i debugged the code of the office I have found an 501 HTTP response from the Vibe server, and than the transfer failed. After a while i have tried to upload with Curl only without the office and there was no output on the console, but the content were not updated. After that i have cloned this repo, and using the build of the current master, tried it again, which also failed. After that i started to debug the Curl with GDB (with the help of the fresh build of Seer  frontend on Ubuntu 20.04 focal fossa) and that pointed me out that after Curl calls the execution of the given command (the transfer in my case) the return of the execution is the same as it was before: HTTP  501 unimplemented instead CURL_OK (if i remember well i did it few weeks ago). Because the lack of time, i stopped the debug, so I have no detailed information. Maybe i can put that additionally, when i debugged the office there was helper method what called the logging of the Curl and printed that out to a file. There were among other things the exact HTTP requests and responses as well, and that was almost the same as the previous previous requests what were done by the previous client before Curl. (Only difference was the capitalism of UTF8 vs utf8 and the header part also was included in the log with Curl but not with the previous client, but this is not seems me so relevant change) However with the previous client the transfer still works with that server with the same settings but not with Curl. Unfortunately i have no idea and time to find out the problem, so i kindly ask for investigating. Hope my novel helped  a bit, and thank you for any kind of help in advance!

Version of the Curl (master where I debugged that issue, and the OS):

$ ./curl --version 
curl 7.85.0-DEV (x86_64-pc-linux-gnu) libcurl/7.85.0-DEV OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0)
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug HSTS HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP TrackMemory UnixSockets

and 

$ bash --version 
GNU bash, 5.0.17(1)-release (x86_64-pc-linux-gnu) version
Copyright (C) 2019 Free Software Foundation, Inc.
A licenc GPLv3+: a GNU GPL 3. vagy újabb változata

Linux osboxes 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

In case of any question about the issue please ask me here and i will response as soon as possible.

**Comment by bagder** [comment]
Thanks a lot for your report!

I've failed to reproduce this problem myself, so can I ask you to provide us with more details on how to go ahead and repeat this. Preferably with a command line or a stand-alone program we can run from our ends against a public URL to trigger the problem?

**Comment by bak-nisz** [comment]
Dear badger,

Thanks for your answer. Sorry for the late reply, unfortunately i  have been flagged and i was unable to write the message.
Yes, you are right it is hard to reproduce without exact command and url, but unfortunately i has no right to give the exact url, and that is not public i think. What can i say there is a Novell/Microfocus Vibe 4 on a SLES server having a password and username account. I does not know the exact configuration too. I got a test account before with a test file only. I does not remember the command because that was a month before when i tested and there is no history in the bash. The command was similar to the following:
curl -T localfile remotefileuri username:pass
Not really remember for the exact syntax. If i remember well there was no error message, i got back the prompt. After debug turned out the 501 http error. If i will have possibility i will try to debug that. Sorry for the tiny information. If i get more data i will let you know.

**Comment by bagder** [comment]
Then please bring more details when you have some so that we can work on it. We can reopen the issue then, as right now there is nothing for us to do here.
