### ISSUE TITLE
CURLSSLOPT_NATIVE_CA disabled by default

### ISSUE THREAD

**Issue by depler** [curl/curl#9350]
Why don't you enable CURLSSLOPT_NATIVE_CA by default so `curl` could use system certificates instead of external file?

**Comment by vszakats** [comment]
As far as I can see, this functionality is already built into Windows binaries by default. So curl-for-win builds do have it.

As for enabling it by default, I think this would be an unexpected break for everyone using `CURLOPT_CAINFO`, which would then be ignored.

Closing this in favour of discussion: https://github.com/curl/curl/discussions/9348. Feel free to re-open this if necessary.
