### ISSUE TITLE
While using c-ares, a lot of time is spent in ares__readaddrinfo

### ISSUE THREAD

**Issue by bsergean** [curl/curl#9351]
### I did this

I built curl to use the c-ares DNS backend, and I do send a lot of outgoing http requests (using the multi-api, with libuv).

### I expected the following

Our /etc/hosts files are quite large (500k), and we need to parse them over and over each time we make a new query. It would be really nice to build, once and ahead of time, the list of domain names (and aliases ?) that are parsed from /etc/hosts, by ares__readaddrinfo. I see that there are lots of way to tweak the interaction with c-ares, and set options on channels, thanks to the CURLOPT_RESOLVER_START_FUNCTION and friends (https://curl.se/libcurl/c/CURLOPT_RESOLVER_START_FUNCTION.html).

See also https://github.com/c-ares/c-ares/issues/458

It sounds like most of the work could be done in C-Ares directly if we had such a 'channel' option.

### curl/libcurl version

7.84

### operating system

Linux (ubuntu 18.04) and macOS

**Comment by bagder** [comment]
I don't think anyone would object if this could be made more effective, even if a 500K hosts file sounds like something that really is an edge case. DNS was sort of made for solving this kind of issues.

**Comment by bagder** [comment]
As you filed this in curl (in addition to c-ares), what do you expect us to do with this? This seems like logic done entirely within c-ares.

**Comment by bsergean** [comment]
Yes we should probably close the curl ticket.

Btw when you were saying that ‘DNS’ should fix this, did you mean that long host files are not a great idea, and instead an intermediary dns cache should be used maybe ? We use chef (https://docs.chef.io/ <https://docs.chef.io/>) to manage servers and it generate very long list of machines in the /etc/host file.

We have libuv available that has an asynchronous DNS resolver (which uses thread too), and we have code that use this, and then set the appropriate curl options so that the internal curl dns resolution is bypassed, but it feels like extra complexity that requires maintenance, which is why I wished that the C-ares way was optimal.
