### ISSUE TITLE
Should unit1303.c have been updated to reflect timeout change?

### ISSUE THREAD

**Issue by sgamerw** [curl/curl#9355]
Should https://github.com/curl/curl/blob/master/tests/unit/unit1303.c have been updated to reflect timeout change?

_Originally posted by @mezzatto in https://github.com/curl/curl/issues/6745#issuecomment-857104315_

**Comment by bagder** [comment]
Can you please use some more words to describe this issue?

**Comment by sgamerw** [comment]
Hi, bagder, just want to know if unit 1303 have been updated to reflect the PR below.
https://github.com/curl/curl/pull/6745#issuecomment-857104315

it seems the unit1303 does not reflect the PR6745.

**Comment by sgamerw** [comment]
![image](https://user-images.githubusercontent.com/4711277/186173115-481d0200-0835-4427-9ccb-c75a7d92534c.png)
btw, the unit1303 seems has something wrong, comment says it's connecting, but the fiveth param is FALSE.

**Comment by bagder** [comment]
> it seems the unit1303 does not reflect the PR6745.

How are you suggesting it should be updated? 
>  btw, the unit1303 seems has something wrong, comment says it's connecting, but the fiveth param is FALSE.

Oh, nice catch, yes that seems to be wrong. But changing those four lines to `TRUE`as  the fifth argument works just as fine. I'll make a PR to fix this.

**Comment by sgamerw** [comment]
> How are you suggesting it should be updated?
![image](https://user-images.githubusercontent.com/4711277/186176321-7a17a917-3591-4f76-b38e-6adff2717564.png)

OK, I found the unit test which connect timeout is the longer one.
should we add one case for not connecting?
> {BASE + 4, 0,      10000, 12000, FALSE, 6000, "6 seconds should be left"},

the second question is how does the connect timeout and transfer timeout work?
in my opinion, every request will go through the connect and transfer stage one by one. so the `total timeout = connect timeout + transfer timeout`, after https://github.com/curl/curl/pull/6745, transfer timeout will limit connect timeout.
so it goes to:
1. connect timeout(10s), transfer timeout(5s), total time will be 10s = connect timeout(limit to 5s) + transfer timeout(5s)
2. connect timeout(10s), transfer timeout(10s), total time will be 20s = connect timeout(10s) + transfer timeout(10s)
3. connect timeout(10s), transfer timeout(15s), total time will be 25s = connect timeout(10s) + transfer timeout(15s)

if this is not correct, can you show me the logic of timeout.

**Comment by sgamerw** [comment]
```c++
    curl_easy_setopt(curl_handle, CURLOPT_CONNECTTIMEOUT, (long) 10);
    curl_easy_setopt(curl_handle, CURLOPT_TIMEOUT, (long) 5);
```
in my cpp code, I set connect timeout to 10s, transfer timeout to 5s, but when I request in the first time, it will callback after 30s in super bad network.
it callback after 13s in the second try.
after minutes, I tried for third time, it callback after 30s.

so i'm confused with the timeout logic, why it not callback in 15s each time?

**Comment by bagder** [comment]
First, the timeouts are explained in the [CURLOPT_TIMEOUT](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) and [CURLOPT_CONNECTTIMEOUT](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html) man pages. They both start at the same time but the latter only covers the connection phase.

Your issue with your code is not related to unit1303 either, but I suspect it is the known issue when curl [waits for the threaded resolver](https://curl.se/docs/knownbugs.html#Multi_perform_hangs_waiting_for),

**Comment by bagder** [comment]
so I guess there is nothing wrong with unit1303.c ?
