### ISSUE TITLE
curl: (7) Failed to connect to 127.0.0.1 port 20170: Connection refused

### ISSUE THREAD

**Issue by iMohammadd** [curl/curl#9358]
### I did this
hey guys  
i everytime trying to use curl i got this following error:  
```curl: (7) Failed to connect to 127.0.0.1 port 20170: Connection refused```   
what should i do?

### curl/libcurl version

curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1n zlib/1.2.11 libidn2/2.3.3 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

### operating system

SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

**Comment by dfandrich** [comment]
Sounds to me like nothing is listening on port 20170 on localhost.

**Comment by iMohammadd** [comment]
> Sounds to me like nothing is listening on port 20170 on localhost.
> 

what should be listening to this port?

**Comment by bagder** [comment]
That's a question for you. curl connects to the port number given in the URL, we don't know what runs there.

You also did not tell us how you run curl or how we can reproduce your problem.

**Comment by iMohammadd** [comment]
> That's a question for you. curl connects to the port number given in the URL, we don't know what runs there.
> 
> You also did not tell us how you run curl or how we can reproduce your problem.

i simply trying to get google first page or every site else with curl, it's dosen't matter which url i trying to get, i always get this error. 
```curl google.com```

**Comment by bagder** [comment]
Add `-v` to the command line and see what it does. Do you perhaps have a `.curlrc` with a default URL or something?

**Comment by bagder** [comment]
Or an environment variable pointing out a local proxy

**Comment by iMohammadd** [comment]
> Add `-v` to the command line and see what it does. Do you perhaps have a `.curlrc` with a default URL or something?

i don't know why, but when i used `-v` flag it's start working!!  
thank you for your help

**Comment by bagder** [comment]
That doesn't make much sense either though.

**Comment by bagder** [comment]
This is for all we can tell not a curl bug but something funny in the user's environment.
