### ISSUE TITLE
Cannot build curl statically and use static dependencies - Mac OS X

### ISSUE THREAD

**Issue by jammerxd** [curl/curl#9359]
Hi there,

I'm trying to build libcurl on Apple Mac OS X 11. 

I'm doing a minimal build with HTTPS and HTTP/2.

I have built out openssl, zlib, and nghttp2 as static libraries -> libssl.a, libcrypto.a, libz.a. The files exist in that path as needed and the configure script picks them up correctly.

However, despite passing --disable-shared, the configure script errors out with:
`configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2 -lssl -lcrypto -lz`

And of course the .dylibs for those don't exist - they're static. I'm trying to do a fully 100% independent build of curl that has no reliance on any other dependencies - except for mac os x frameworks. I want my static openssl, my static nghttp2, and my static zlib.

Here is my full configure command:

`./configure --disable-shared --with-secure-transport --without-librtmp --without-libidn2 --with-zlib=/Users/jammerxd/Desktop/Git/cplusplusdependencies/zlib-1.2.11/MacOSX/x86_64/ --with-openssl=/Users/jammerxd/Desktop/Git/cplusplusdependencies/openssl-1.1.1m/MacOSX/x86_64 --disable-ldaps --disable-ntlm --disable-telnet --disable-proxy --disable-debug --enable-optimize --disable-curldebug --enable-symbol-hiding --disable-ftp --disable-rtsp --disable-dict --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-mqtt --disable-ntlm-wb --disable-tls-srp --disable-http-auth --disable-doh --disable-netrc --enable-progress-meter --disable-alt-svc --disable-ldap --disable-file  --disable-dependency-tracking --with-nghttp2=/Users/jammerxd/Desktop/Git/cplusplusdependencies/nghttp2-1.49.0/MacOSX/x86_64/`

If I try to prefix the above command with:
`LDFLAGS="-static" PKG_CONFIG="pkg-config --static"`
the configure tool errors out with:
```
checking whether the C compiler works... no
configure: error: in `/Users/jammerxd/Desktop/Git/cplusplusdependencies/curl-7.84.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Looking on how I'm supposed to be able to build curl statically then have it link to the dependencies statically as well.

Thanks,
jammerxd

**Comment by dfandrich** [comment]
Building libcurl fully statically is not supported automatically by the build 
tools.  There are too many chains of static dependencies to try to keep track 
of and they can change over time. You will need to add all the static 
dependencies to LIBS so that the build system can know about them.

**Comment by jammerxd** [comment]
What does that look like/mean? Do I remove the --with-nghttp2 from the configure command?
What directories does LIBS need?
Is it as simple as `LIBS="/Users/jammerxd/Desktop/Git/cplusplusdependencies/openssl-1.1.1m/MacOSX/x86_64:/Users/jammerxd/Desktop/Git/cplusplusdependencies/zlib-1.2.11/MacOSX/x86_64"`?

**Comment by jammerxd** [comment]
If I try
`LIBS="-l/Users/jammerxd/Desktop/Git/cplusplusdependencies/openssl-1.1.1m/MacOSX/x86_64/lib/libssl.a -l/Users/jammerxd/Desktop/Git/cplusplusdependencies/openssl-1.1.1m/MacOSX/x86_64/lib/libcrypto.a -l/Users/jammerxd/Desktop/Git/cplusplusdependencies/zlib-1.2.11/MacOSX/x86_64/lib/libz.a -l/Users/jammerxd/Desktop/Git/cplusplusdependencies/nghttp2-1.49.0/MacOSX/x86_64/lib/libnghttp2.a" ./configure --disable-shared --with-secure-transport --without-librtmp --without-libidn2 --with-zlib=/Users/jammerxd/Desktop/Git/cplusplusdependencies/zlib-1.2.11/MacOSX/x86_64/ --with-openssl=/Users/jammerxd/Desktop/Git/cplusplusdependencies/openssl-1.1.1m/MacOSX/x86_64 --disable-ldaps --disable-ntlm --disable-telnet --disable-proxy --disable-debug --enable-optimize --disable-curldebug --enable-symbol-hiding --disable-ftp --disable-rtsp --disable-dict --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-mqtt --disable-ntlm-wb --disable-tls-srp --disable-http-auth --disable-doh --disable-netrc --enable-progress-meter --disable-alt-svc --disable-ldap --disable-file  --disable-dependency-tracking --with-nghttp2=/Users/jammerxd/Desktop/Git/cplusplusdependencies/nghttp2-1.49.0/MacOSX/x86_64/`

I get an error from configure:
```
configure: error: in `/Users/jammerxd/Desktop/Git/cplusplusdependencies/curl-7.84.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by dfandrich** [comment]
LIBS is a pseudo-standard variable, and it looks like you've figure out how to
use it. Take a look at config.log to see why it's not working. My guess is that
you're missing static libraries that libnghttp2.a or others require. Which
means you've started to fall into the rabbit hole.

**Comment by jammerxd** [comment]
I've gotten farther than I was previously.
I ended up switching to using cmake's build system. But now the problem is no matter what I do, curl is linking dynamically to nghttp2 - despite having CPPFLAGS="-DNGHTTP2_STATICLIB". I can't use the ./configure because it just breaks....

**Comment by jammerxd** [comment]
After a lot of messing around I figured out nghttp2 was not compiled statically - despite having -DENABLE_STATIC_LIB=ON - I needed the additional -DENABLE_SHARED=NO.

So how I compile NGHTTP2:

```
cd ${CPlusPlusDependencies}/nghttp2-1.49.0
/Applications/CMake.app/Contents/bin/cmake . -DENABLE_THREADS=1 -DENABLE_LIB_ONLY=1 -DENABLE_STATIC_LIB=1 -DENABLE_DOC=0 -DCMAKE_INSTALL_PREFIX=${CPlusPlusDependencies}/nghttp2-1.49.0/builds/MacOSX/11/x86_64 -DOPENSSL_ROOT_DIR=${CPlusPlusDependencies}/openssl-1.1.1q/builds/MacOSX/11/x86_64/release -DZLIB_ROOT=${CPlusPlusDependencies}/zlib-1.2.12/builds/MacOSX/11/x86_64 -DZLIB_USE_STATIC_LIBS=ON -DOPENSSL_CRYPTO_LIBRARY=${CPlusPlusDependencies}/openssl-1.1.1q/builds/MacOSX/11/x86_64/release/lib/libcrypto.a -DOPENSSL_SSL_LIBRARY=${CPlusPlusDependencies}/openssl-1.1.1q/builds/MacOSX/11/x86_64/release/lib/libssl.a -DCMAKE_CXX_FLAGS="-DUSE_SSLEAY -DUSE_OPENSSL" -DCMAKE_C_FLAGS="-DUSE_SSLEAY -DUSE_OPENSSL" -DENABLE_SHARED_LIB=OFF
make clean
make install
cd builds/MacOSX/11/x86_64
```

How I build curl:
```
./configure --disable-shared --disable-ldap --disable-ldaps --without-librtmp --without-libidn2 --with-zlib=${CPlusPlusDependencies}/zlib-1.2.12/builds/MacOSX/11/x86_64 --with-secure-transport --with-nghttp2=${CPlusPlusDependencies}/nghttp2-1.49.0/builds/MacOSX/11/x86_64 --prefix=${CPlusPlusDependencies}/curl-7.84.0/builds/MacOSX/11/x86_64
make clean
make install
```
