### ISSUE TITLE
SocketIsDead is not working on Linux

### ISSUE THREAD

**Issue by jane-mao** [curl/curl#9366]
### I did this
I'm using libcurl to perform http get repeatedly like below:

```
int main(void)
{
  CURL *curl;
  CURLcode res;
  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 60);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, (long) 1);
    curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, (long) 1);
    curl_easy_setopt(curl, CURLOPT_TCP_KEEPIDLE, 120L);
    /* interval time between keep-alive probes: 60 seconds */
    curl_easy_setopt(curl, CURLOPT_TCP_KEEPINTVL, 60L);
    curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, CdkBasicHttpDebugCurlCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, CdkBasicHttpWriteCallback);
    curl_easy_setopt(curl, CURLOPT_URL, "http://www.example.com");

    int i = 0;
    while (i < 10) {
       i++;
      /* Perform the request, res will get the return code */
      res = curl_easy_perform(curl);
      printf("Sleeping 30 seconds, you can disconnect your network now.\n\n\n");
      g_usleep(30000000);
    }

    /* always cleanup */
    curl_easy_cleanup(curl);
  }

  return 0;
}


char *formatLogPrefix()
{
   static char timestr[32];
   static char timezone[8];
   static glong oldSec = 0;
   GTimeVal curTime;
   int index = 0, i = 0;
   char *formatMsg = NULL;

   g_get_current_time(&curTime);
   if (curTime.tv_sec != oldSec) {
      time_t now;
      struct tm localNow;

      time(&now);
      localNow = *localtime(&now);

      strftime(timestr, sizeof(timestr), "%Y-%m-%d %H:%M:%S", &localNow);
      if (strftime(timezone, sizeof(timezone), "%z", &localNow) != 0) {
         // format timezone info to +hh:mm or -hh:mm style.
         index = strlen(timezone) + 1;
         // move "mm" and '\0' backward by on char position.
         for (i = 0; i < 3; i++) {
            timezone[index] = timezone[index - 1];
            index--;
         }
         timezone[index] = ':';
      }

      oldSec = curTime.tv_sec;
   }

   formatMsg = g_strdup_printf("%s.%.03d%s", timestr,
                            (int)(curTime.tv_usec / 1000),
                            timezone);
   return formatMsg;
}


size_t
CdkBasicHttpWriteCallback(void *buffer,                     /* IN */
                          size_t size,                      /* IN */
                          size_t nmemb,                     /* IN */
                          void *clientData)                 /* IN */
{
   char *prefix = formatLogPrefix();
   printf("%s: %lu bytes data received.\n", prefix, nmemb);
   g_free(prefix);
   return nmemb;
}


int
CdkBasicHttpDebugCurlCallback(CURL *curl,          /* IN */
                              curl_infotype type,  /* IN */
                              char *msg,           /* IN */
                              size_t msgLen,       /* IN */
                              void *clientData)    /* IN */
{
   const char *typeStr = "TEXT";

   switch (type) {
   case CURLINFO_TEXT: {
      char *prefix = formatLogPrefix();
      printf("%s: curl (%s): %.*s", prefix, typeStr, (int)msgLen, msg);
      g_free(prefix);
      break;
   }
   default:
      break;
   }

   return 0;
}
```

### I expected the following
Disconnecting the network before the second curl_easy_perform(), I expected the "connection 0 seems to be dead", but the connection was reused:
curl (TEXT): Found bundle for host: 0x561ae3c0fcf0 [serially]
curl (TEXT): Re-using existing connection #0 with host 45.113.192.101
curl (TEXT): Connected to 45.113.192.101 (45.113.192.101) port 80 (#0)

### curl/libcurl version
libcurl version: 7.84.0

[curl -V output]

### operating system
Linux ubuntu 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
... but what happens next, when it sends the request? Did sending the request work as well? If so, then clearly the connection was not dead. I don't think you show us enough details here to see that it actually failed to detect.

The SocketIsDead() is a best-effort, it is not foolproof and it is also a race there as it might not be dead then but die 2 milliseconds later, so we need to handle later detection as well.

**Comment by jane-mao** [comment]
> 

Hi Bagder,

Thanks for your so quick response.

>> but what happens next, when it sends the request?
Yes, it reused the connection to send the request, then no response and got hang there.

From the code, I can see SocketIsDead() is invoked twice, one is in prune_dead_connections() before create a new connection, the second one is in ConnectionExists().

And from my the running output:
curl (TEXT): Found bundle for host: 0x56409b26dcf0 [serially]
curl (TEXT): Re-using existing connection #0 with host 45.113.192.101
curl (TEXT): Connected to 45.113.192.101 (45.113.192.101) port 80 (#0)

The first check was failed because "Found bundle for host" from connection cache, the second check was failed too.

**Comment by bagder** [comment]
And how do you know the connection was dead? Again, you crop the curl debug log so much we can't really say what it did.

**Comment by jane-mao** [comment]
Hi Bagder,

Have updated the code, removed the unnecessary code and added timestamp for each log line.

Here are the running result:
```
2022-08-25 22:15:27.791+08:00: curl (TEXT):   Trying 45.113.192.101:80...
2022-08-25 22:15:28.021+08:00: curl (TEXT): Connected to 45.113.192.101 (45.113.192.101) port 80 (#0)
2022-08-25 22:15:28.306+08:00: curl (TEXT): Mark bundle as not supporting multiuse
2022-08-25 22:15:28.306+08:00: 9508 bytes data received.
2022-08-25 22:15:28.306+08:00: curl (TEXT): Connection #0 to host 45.113.192.101 left intact
Sleeping 30 seconds, you can disable your network now.


2022-08-25 22:15:58.307+08:00: curl (TEXT): Found bundle for host: 0x5652c6ba9cf0 [serially]
2022-08-25 22:15:58.307+08:00: curl (TEXT): Re-using existing connection #0 with host 45.113.192.101
2022-08-25 22:15:58.307+08:00: curl (TEXT): Connected to 45.113.192.101 (45.113.192.101) port 80 (#0)
2022-08-25 22:15:58.592+08:00: curl (TEXT): Mark bundle as not supporting multiuse
2022-08-25 22:15:58.592+08:00: 9508 bytes data received.
2022-08-25 22:15:58.592+08:00: curl (TEXT): Connection #0 to host 45.113.192.101 left intact
Sleeping 30 seconds, you can disable your network now.


2022-08-25 22:16:28.592+08:00: curl (TEXT): Found bundle for host: 0x5652c6ba9cf0 [serially]
2022-08-25 22:16:28.592+08:00: curl (TEXT): Re-using existing connection #0 with host 45.113.192.101
2022-08-25 22:16:28.592+08:00: curl (TEXT): Connected to 45.113.192.101 (45.113.192.101) port 80 (#0)
2022-08-25 22:35:24.298+08:00: curl (TEXT): Recv failure: Connection timed out
2022-08-25 22:35:24.298+08:00: curl (TEXT): Connection died, retrying a fresh connect (retry count: 1)
2022-08-25 22:35:24.299+08:00: curl (TEXT): Closing connection 0
2022-08-25 22:35:24.299+08:00: curl (TEXT): Issue another request to this URL: 'http://45.113.192.101/'
2022-08-25 22:35:24.299+08:00: curl (TEXT):   Trying 45.113.192.101:80...
2022-08-25 22:35:24.299+08:00: curl (TEXT): Immediate connect fail for 45.113.192.101: Network is unreachable
2022-08-25 22:35:24.299+08:00: curl (TEXT): Closing connection 1
Sleeping 30 seconds, you can disable your network now.
```

In the code, I added sleep 30 seconds after each http request, so that I can disconnect network during the 30 seconds.
Then during the test, I disconnected the network between the 2rd and 3rd request. I expected the cached connection #0 should be regarded as dead when network was disconnected, was that correct?

**Comment by bagder** [comment]
Ok, let's switch the discussion around. Do you have an actual problem?

**Comment by dfandrich** [comment]
On Thu, Aug 25, 2022 at 06:50:16PM -0700, jane-mao wrote:
> Then during the test, I disconnected the network between the 2rd and 3rd
> request. I expected the cached connection #0 should be regarded as dead when
> network was disconnected, was that correct?

No. See https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro

**Comment by jane-mao** [comment]
Yes, we are using libcurl 7.84.0 in our product to communicate between two services, e.g.
 a. authentication.
 b. get connection information.
 c. set up the connection with above information.

The above steps a and b are performed via libcurl with http request. And there is a test case, disconnecting the network before start b, it is expected to return with error when executing b, but it hangs there for a long time on Linux. 

However our product works well on Window, the task b returns quickly with error (from the log I can see "connection #0 seems to be dead"). 

I searched the keywords "seems to be dead", found it is reported by SocketIsDead(). So I raised this issue here.

**Comment by jane-mao** [comment]
> 

As my understanding, https://curl.se/docs/faq.html#Why_does_not_curl_return_an_erro it means disconnecting the network during the sending or receiving, I meant to disconnect network before setting up a new connection.
Thanks.

**Comment by bagder** [comment]
It's not before you set it up. `SocketIsDead()` is called because the connection is already setup and present.

**Comment by jane-mao** [comment]
> It's not before you set it up. `SocketIsDead()` is called because the connection is already setup and present.

I meant before performing the http request not set it up.

On Windows, `SocketIsDead()` works well, so the connection already setup was detected as dead and then was closed, so a new connection was setup and failed due to network error.

However on Linux, the existing connection was still reused.

**Comment by bagder** [comment]
Again, that's not a problem that's just how things work. SocketIsDead() detects if the socket is signaled to have "died", and if there is no such signal there's not a lot curl can do about it. So it has other mechanisms to make sure it can work even if the connection actually is dead even if not detected so.
