### ISSUE TITLE
HTTPS Connection Failed

### ISSUE THREAD

**Issue by aerjali** [curl/curl#9374]
I'm trying to run a a program with libcurl using https but my program just crash when trying to perform https call. 
tried to disable verify peer/host but no luck: 
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

the program was working before and this time I have strange behavior. no update on the OS or anything similar.
Stack: 
0x09000000005ce9d0  _p_nsleep(??, ??) + 0x10
0x0900000000040f04  nsleep(??, ??) + 0xe4
0x090000000018d46c  sleep@AF4_1(??) + 0x2c
0x0000000100001b68  sig_segment_violation(0x400000004) + 0xc8
<signal>
0x00000000000b2ad4  _hkeyset_update_userkeys() + 0x4
0x00000000000b1cb8  copyin(??, ??, ??) + 0x78
0x000000000020c3f0  krestart_wait(??, ??, ??) + 0x270
0x090000000aeada28  BIO_new_ef() + 0x88
0x080000000003f180  ssl3_init_finished_mac() + 0x20
0x0800000000026844  tls_setup_handshake() + 0x24
0x0800000000012544  state_machine() + 0x424
0x080000000000f6cc  SSL_do_handshake@AF1922_922() + 0xec
0x080000000000785c  SSL_do_handshake() + 0x1c
0x0800000000008ff4  SSL_connect() + 0x54
0x090000000d431624  ossl_connect_step2() + 0x84
0x090000000d42eb18  ossl_connect_common() + 0x118
0x090000000d42c19c  Curl_ssl_connect_nonblocking() + 0xbc
0x090000000d466ba8  https_connecting() + 0x28
0x090000000d4688ac  Curl_http_connect() + 0xac
0x090000000d41cfdc  protocol_connect@AF99_6() + 0x9c
0x090000000d417b84  IPRA.$multi_runsingle() + 0x8e4
0x090000000d41b7bc  curl_multi_perform() + 0x9c
0x090000000d45f97c  easy_transfer@AF31_6() + 0x17c
0x090000000d45fb68  easy_perform@AF32_5() + 0x1a8
0x000000010005da40  SendWsCurlMsg(0xb4000000b4, 0x1135ec950, 0x200000002, 0x1135ed700, 0x1135ee4b8) + 0x420

**Comment by bagder** [comment]
How do we reproduce this? What curl version on what platform?

**Comment by gvanem** [comment]
>  BIO_new_ef()

What kind of OpenSSL library is this? (Google came up pretty blank on this function).

**Comment by aerjali** [comment]
Sorry I miss those details: 

srv222:/data/pwrcard/bocdev>curl -V
curl 7.82.0 (powerpc-ibm-aix7.1.5.0) libcurl/7.82.0 OpenSSL/1.1.1n
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets



machine: Aix
Version: 
oslevel -s
7100-03-09-1717

**Comment by bagder** [comment]
Does it happen repeatedly on the same URL? Show us a URL it happens on.

The stack trace from the crash shows a crash deep inside OpenSSL. I am fully convinced that curl uses OpenSSL correctly, which could imply that this bug is not curl's, it's OpenSSL's.

Also, both OpenSSL and curl have released at least two updates since the versions you use that you would be encouraged to also try out just to check the problem isn't already fixed.

**Comment by bagder** [comment]
No response, looks like an OpenSSL issue.
