### ISSUE TITLE
running curl command succeeded but using libcurl API got status 400 back

### ISSUE THREAD

**Issue by allen-k-liu** [curl/curl#9377]
I was able to run curl command to login a device but on the same machine running a login program using curl_easy_perf got status 400 back.  Compare the wireshark for both cases.  The curl command contains User-Agent part that is missing from API and that HTTP response 400.  That's the only difference.  The 
POST field, Host, accpept, content-Type all the same for both case.
My curl version 7.47
Thanks!

**Comment by bagder** [comment]
This does not sound like a curl issue. The server probably insists on a user-agent field so you should probably pass on in your request!
