### ISSUE TITLE
SSL certificate verification failing with the BearSSL backend

### ISSUE THREAD

**Issue by Kartatz** [curl/curl#9388]
### I did this

I compiled libcurl with CMake:

```bash
cmake \
    -DBUILD_CURL_EXE=OFF \
    -DHTTP_ONLY=ON \
    -DENABLE_THREADED_RESOLVER=OFF \
    -DCURL_USE_BEARSSL=ON \
    -DCURL_USE_OPENSSL=OFF \
    -DCURL_USE_LIBPSL=OFF \
    -DCURL_DISABLE_ALTSVC=ON \
    -DCURL_DISABLE_CRYPTO_AUTH=ON \
    -DCURL_DISABLE_COOKIES=ON \
    -DCURL_DISABLE_HSTS=ON \
    -DCURL_DISABLE_HTTP_AUTH=ON \
    -DCURL_DISABLE_NETRC=ON \
    -DUSE_LIBIDN2=OFF \
    -DENABLE_UNIX_SOCKETS=OFF \
    -DCURL_USE_LIBSSH2=OFF \
    -DCURL_CA_BUNDLE=none \
    -DCURL_CA_PATH=none \
    ./
```

Here is a minimal reproducible example:

```C
#include <stdio.h>
#include <string.h>

#include <curl/curl.h>

static const char CACERT[] = 
    "-----BEGIN CERTIFICATE-----\n"\
    "MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJRTESMBAGA1UE\n"\
    "ChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3li\n"\
    "ZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoXDTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMC\n"\
    "SUUxEjAQBgNVBAoTCUJhbHRpbW9yZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFs\n"\
    "dGltb3JlIEN5YmVyVHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKME\n"\
    "uyKrmD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjrIZ3AQSsB\n"\
    "UnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeKmpYcqWe4PwzV9/lSEy/C\n"\
    "G9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSuXmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9\n"\
    "XbIGevOF6uvUA65ehD5f/xXtabz5OTZydc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjpr\n"\
    "l3RjM71oGDHweI12v/yejl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoI\n"\
    "VDaGezq1BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEB\n"\
    "BQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT929hkTI7gQCvlYpNRh\n"\
    "cL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3WgxjkzSswF07r51XgdIGn9w/xZchMB5\n"\
    "hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsa\n"\
    "Y71k5h+3zvDyny67G7fyUIhzksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9H\n"\
    "RCwBXbsdtTLSR9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp\n"
    "-----END CERTIFICATE-----";

int main() {
    
    curl_global_init(CURL_GLOBAL_ALL);
    CURL* ch = curl_easy_init();
    
    curl_easy_setopt(ch, CURLOPT_URL, "https://www.ubook.com/");
    
    struct curl_blob blob = {
        .data = (char*) CACERT,
        .len = strlen(CACERT),
        .flags = CURL_BLOB_COPY
    };
    
    curl_easy_setopt(ch, CURLOPT_CAINFO_BLOB, &blob);
    
    CURLcode code = curl_easy_perform(ch);
    
    curl_easy_cleanup(ch);
    curl_global_cleanup();
    
    printf("%s\n", curl_easy_strerror(code));
    
    return code;
    
}
```

### I expected the following

Pass SSL certificate verification without errors.

### curl/libcurl version

7.85.0-DEV ([56f1bbd](https://github.com/curl/curl/commit/56f1bbdd0c8b81d4e997afac695afc39e9ddd49d))

### operating system

```
$ uname -a
Linux localhost 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jay** [comment]
Do you have the same problem if libcurl loads the ca certificate from a file? What is the verbose output and your `curl_version()`?

Is anyone using BearSSL that can assist?

/cc @AzazKamaz

**Comment by Kartatz** [comment]
> Do you have the same problem if libcurl loads the ca certificate from a file?  
No, it works just fine.

Here is the verbose output of curl when using the certificate blob:

```
*   Trying 172.67.75.226:443...
* Connected to www.ubook.com (172.67.75.226) port 443 (#0)
* error importing CA certificate blob
* Closing connection 0
```

Output of `curl_version()`:

```
libcurl version libcurl/7.85.0-DEV BearSSL zlib/1.2.11
```

**Comment by jay** [comment]
I built curl against bearssl 0.6 and walked through it. br_pem_decoder_push consumes `-----BEGIN CERTIFICATE-----\n` from the blob during the first call, and then the second call consumes everything else. When br_pem_decoder_event is called the second time (to get the event from the br_pem_decoder_push second call) it returns 0 instead of BR_PEM_END_OBJ, and then basically breaks from the loop without having fully parsed the certificate.

https://github.com/curl/curl/blob/45ac4d019475df03562fe0ac54eb67e1d1de0ca7/lib/vtls/bearssl.c#L152-L170

If I add a linefeed to the end tag like `"-----END CERTIFICATE-----\n"` then br_pem_decoder_event returns BR_PEM_END_OBJ and it works.

**Comment by jay** [comment]
It seems to me this is not a bug in curl and probably expected behavior in bearssl.

/cc @pornin

**Comment by Kartatz** [comment]
> If I add a linefeed to the end tag like "`-----END CERTIFICATE-----\n`" then br_pem_decoder_event returns BR_PEM_END_OBJ and it works.

Oh, I see. Thanks for pointing this!

> It seems to me this is not a bug in curl and probably expected behavior in bearssl.

Yes, I think so. I wrongly assumed it was something on curl's side. Sorry about that.
