### ISSUE TITLE
curl built against OpenSSL (not Darwin) crashes

### ISSUE THREAD

**Issue by mario-grgic** [curl/curl#940]
I'm on Mac OS X 10.11.6 and trying to build curl-7.50.0. I have OpenSSL 1.0.2h installed in /usr/local/ssl,. I configure curl build as follows:

./configure --with-openssl 

which correctly finds (using pkg-config) open ssl includes and libraries and generates a makefile, which successfully builds curl. 

But then when I run curl I get:

$ curl
curl: try 'curl --help' or 'curl --manual' for more information
dyld: lazy symbol binding failed: Symbol not found: _SSL_COMP_free_compression_methods
  Referenced from: /usr/local/lib/libcurl.4.dylib
  Expected in: flat namespace

dyld: Symbol not found: _SSL_COMP_free_compression_methods
  Referenced from: /usr/local/lib/libcurl.4.dylib
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by mario-grgic** [comment]
It seems this is due to curl enabling ssh2 and linking against libssh2. But libssh2 was also built against same OpenSSL. So not sure why it crashes.

**Comment by bagder** [comment]
Why do you say it is related to ssh2/libssh2?

`SSL_COMP_free_compression_methods()` should exist in your OpenSSL version, unless you built it without compression but then your headers should define `OPENSSL_NO_COMP`.

Our conditional logic is here: https://github.com/curl/curl/blob/master/lib/vtls/openssl.c#L125

**Comment by mario-grgic** [comment]
Because when I build curl with libssh2 disabled, it does not crash.

**Comment by bagder** [comment]
and `otool -L [path to your curl]` shows the correct OpenSSL libs being used when you link with and without libssh2?

**Comment by mario-grgic** [comment]
curl statically links OpenSSL libraries (I don't have any OpenSSL dynamic libraries in /usr/local/ssl). 

If I however build curl against Darwin's built-in SSL, it does not crash.

So to recap:

curl built against /usr/local/ssh crashes.
curl built against DarwinSSL (with-darwinssl config option) does not crash.

However, in either case I am linking against a slew of libraries. And at this point it is hard to tell what is actually causing the crash.

./configure --mandir=/usr/local/man/ --enable-optimize --enable-http --enable-ftp --enable-file --enable-ldap --enable-ldaps --enable-rtsp --enable-proxy --enable-dict --enable-telnet --enable-tftp --enable-pop3 --enable-imap --enable-smtp --enable-gopher --enable-manual --enable-ipv6 --enable-threaded-resolver --enable-sspi --enable-crypto-auth --enable-tls-srp --enable-cookies --with-libmetalink --with-gssapi --with-spengo --with-openssl --with-nghttp2

**Comment by jay** [comment]
When you say *crash* you mean it doesn't run? Is it possible you have more than one copy of OpenSSL libraries, and it is not linking to the right one?

**Comment by bagder** [comment]
> curl statically links OpenSSL libraries (I don't have any OpenSSL dynamic libraries in /usr/local/ssl).

Right, but you also link with libssh2, is that also only static or is it perhaps dynamically using (another) OpenSSL ?

**Comment by mario-grgic** [comment]
I have recompiled the libssh2 to statically link against /usr/local/ssl libraries
$ otool -L libssh2.1.dylib
libssh2.1.dylib:
	/usr/local/lib/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	/usr/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.7)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$

Before, it used to link against /usr/lib/libssl.0.9.8.dylib. But curl still crashes if I build against the same /usr/local/ssl libraries (and not if I link against darwin openssl in /usr/lib).

This is what curl links against after building it against /usr/local/ssl library:

$ otool -L /usr/local/bin/curl
/usr/local/bin/curl:
	/usr/local/lib/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	/usr/local/lib/libmetalink.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/lib/libidn.11.dylib (compatibility version 18.0.0, current version 18.11.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/lib/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.7)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$

And if I run it, same thing again:

$ curl
curl: try 'curl --help' or 'curl --manual' for more information
dyld: lazy symbol binding failed: Symbol not found: _SSL_COMP_free_compression_methods
  Referenced from: /usr/local/lib/libcurl.4.dylib
  Expected in: flat namespace

dyld: Symbol not found: _SSL_COMP_free_compression_methods
  Referenced from: /usr/local/lib/libcurl.4.dylib
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by bagder** [comment]
First, it isn't a *crash* when it just refuses to start.

Then, if you'd really built with a static library then I don't understand why it would complain on a SSL symbol at the time you invoke the command - it should've done that already at the time it was linked. Can you explain how that can happen? The "lazy symbol binding" text would also imply that it is done at load-time and that then implies a shared library... doesn't it?

**Comment by mario-grgic** [comment]
You are right, I did have another libssl in /usr/local/lib installed by who knows what and apparently curl build was linking against it. Once I removed it everything is fine.
