### ISSUE TITLE
libCurl return HTTP code 0, when window is minimized

### ISSUE THREAD

**Issue by devblackhunter** [curl/curl#9402]
### I did this
I use libcurl in a dll that is injected into another program. And sometimes, when the program is minimized, libcurl returns the HTTP code 0 during requests
### curl/libcurl version

7.83.0-DEV

### operating system
Windows (All versions, from 7)

**Comment by bagder** [comment]
I don't think this is enough details for us to work on. curl obviously does not know nor care about any windows or their states.

HTTP code 0 seems to imply that the transfer failed and then it is supposed to return 0 for the "HTTP code".

**Comment by bagder** [comment]
No response.
