### ISSUE TITLE
coredump when using libcurl multithreading for https download file

### ISSUE THREAD

**Issue by liwang54321** [curl/curl#9407]
coredump info as follow， Hope some experts can help
![image](https://user-images.githubusercontent.com/38935780/187820949-016e4fef-6bfb-46fb-8b53-96171be1f91d.png)

curl code
```cpp
 target_fp = fopen(file_path.c_str(), "w");
  if (target_fp == nullptr) {
    curl_easy_cleanup(curl_p);
    return -1;
  }
  CURL *curl_p = curl_easy_init();
  if (curl_p == nullptr) {
    return -1;
  }

// set download URL
  if (curl_easy_setopt(curl_p, CURLOPT_URL, url.c_str()) != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }
if (curl_easy_setopt(curl_p, CURLOPT_SSL_VERIFYPEER, 1L) != 0) {
      fclose(target_fp);
      curl_easy_cleanup(curl_p);
      return -1;
    }

    if (curl_easy_setopt(curl_p, CURLOPT_SSL_VERIFYHOST, 2L) != 0) {
      fclose(target_fp);
      curl_easy_cleanup(curl_p);
      return -1;
    }

    if (curl_easy_setopt(curl_p, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2) !=
        0) {
      fclose(target_fp);
      curl_easy_cleanup(curl_p);
      return -1;
    }

  int net_rate_p = max_rate_kb * 1024;
  if (curl_easy_setopt(curl_p, CURLOPT_MAX_RECV_SPEED_LARGE,
                       (curl_off_t)net_rate_p) != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  // Content-Encoding
  // Sets the contents of the Accept-Encoding: header sent in an HTTP request
  // enables decoding of a response when a Content-Encoding: header is
  // received
  if (curl_easy_setopt(curl_p, CURLOPT_ACCEPT_ENCODING, "gzip") != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  if (curl_easy_setopt(curl_p, CURLOPT_NOSIGNAL, 1) != CURLE_OK){
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  // register object tracking output file
  if (curl_easy_setopt(curl_p, CURLOPT_WRITEDATA, target_fp) != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  // register callback for writing downloaded file data
  if (curl_easy_setopt(curl_p, CURLOPT_WRITEFUNCTION,
                       DownloadFileCbWriteData) != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  // Enable fail on error (>400 HTTP responses)
  if (curl_easy_setopt(curl_p, CURLOPT_FAILONERROR, 1) != CURLE_OK) {
    fclose(target_fp);
    curl_easy_cleanup(curl_p);
    return -1;
  }

  CURLcode curl_code = curl_easy_perform(curl_p);
```

**Comment by bagder** [comment]
Thanks for your report!

Can you tell us more about the curl/libcurl version you used when you ran into this issue? A `curl -V` output is perfect as it also tells us about your TLS library (version) and more.

**Comment by liwang54321** [comment]
> Thanks for your report!
> 
> Can you tell us more about the curl/libcurl version you used when you ran into this issue? A `curl -V` output is perfect as it also tells us about your TLS library (version) and more.
Thank you,  The version number screenshot is as follows 
![image](https://user-images.githubusercontent.com/38935780/187851195-eb9aa2dc-ea66-47ae-8726-86c7366046a3.png)
![image](https://user-images.githubusercontent.com/38935780/187851735-91ecbfbd-7b3b-4ded-b6d8-30147747a1b7.png)

**Comment by liwang54321** [comment]
> Thanks for your report!
> 
> Can you tell us more about the curl/libcurl version you used when you ran into this issue? A `curl -V` output is perfect as it also tells us about your TLS library (version) and more.
The probability of this alarm occurring is relatively low, but sometimes it occurs

**Comment by bagder** [comment]
Please provide information as *text*, not as screenshots. curl 7.68.0 OpenSSL 1.1.1f

This is a crash inside OpenSSL and it look like in its malloc. I would first suspect a memory error in your code: have you verified that valgrind is happy when used on this?

Secondary, I would propose you try newer versions of both libcurl and OpenSSL, at least as an experiment to see if this problem might already have been fixed. 

If that doesn't help

- build a debug version of curl and get some symbols and local variables at the crash point
- provide a smaller stand-alone program that reproduces the problem that you can share with us

**Comment by liwang54321** [comment]
> 

ok, thank you

**Comment by bagder** [comment]
Closed due to inactivity for a problem suspected to be in OpenSSL.
