### ISSUE TITLE
Body is empty on https download

### ISSUE THREAD

**Issue by 6543** [curl/curl#9409]
### I did this

```sh
curl https://crates.io/api/v1/crates/bitflags/1.3.2/download -o dl.raw
file dl.raw
```
> dl.raw: empty

### I expected the following
> dl.raw: gzip compressed data, was "bitflags-1.3.2.crate", max compression, original size modulo 2^32 128000

### curl/libcurl version
 - curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.49.0
  Release-Date: 2022-06-27
  Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
  Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
- curl 7.84.0 (riscv64-alpine-linux-musl) libcurl/7.84.0 OpenSSL/3.0.5 zlib/1.2.12 brotli/1.0.9 nghttp2/1.49.0
  Release-Date: 2022-06-27
  Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
  Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
- curl 7.85.0 (riscv64-unknown-linux-musl) libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.12 brotli/1.0.9 nghttp2/1.49.0
  Release-Date: 2022-08-31
  Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
  Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

### operating system
- `Linux 5.19.2-artix1-2 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 10:48:27 +0000 x86_64 GNU/Linux`
- `Linux riscv64_alpine 5.19.2-artix1-2 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 10:48:27 +0000 riscv64 Linux`
  (binfmt-qemu-static: qemu-riscv64-static)

### verbose download
<summary>

 <details>

`curl https://crates.io/api/v1/crates/bitflags/1.3.2/download -o dl.raw --verbose`:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 13.32.99.28:443...
* Connected to crates.io (13.32.99.28) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4968 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=crates.io
*  start date: Apr  1 00:00:00 2022 GMT
*  expire date: Apr 30 23:59:59 2023 GMT
*  subjectAltName: host "crates.io" matched cert's "crates.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* h2h3 [:method: GET]
* h2h3 [:path: /api/v1/crates/bitflags/1.3.2/download]
* h2h3 [:scheme: https]
* h2h3 [:authority: crates.io]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x55a110e48d30)
} [5 bytes data]
> GET /api/v1/crates/bitflags/1.3.2/download HTTP/2
> Host: crates.io
> user-agent: curl/7.84.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [124 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 302 
< content-length: 0
< location: https://static.crates.io/crates/bitflags/bitflags-1.3.2.crate
< server: nginx
< date: Thu, 01 Sep 2022 10:47:22 GMT
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< content-security-policy: default-src 'self'; connect-src 'self' *.ingest.sentry.io https://docs.rs https://play.rust-lang.org https://static.crates.io; script-src 'self' 'unsafe-eval' 'sha256-n1+BB7Ckjcal1Pr7QNBh/dKRTtBQsIytFodRiIosXdE='; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; font-src https://code.cdn.mozilla.net; img-src *; object-src 'none'
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000
< via: 1.1 vegur, 1.1 ca8cb14c76df16342491237cea8cfed6.cloudfront.net (CloudFront)
< vary: Accept,Accept-Encoding,Cookie
< x-cache: Miss from cloudfront
< x-amz-cf-pop: FRA60-P3
< x-amz-cf-id: 9Nh2ZEUSeEAF2ROZ_WHVIXstARu21pZCoJmmgTYem1tCi1rPaxaxhw==
< 
{ [0 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host crates.io left intact
```
`file dl.raw`:
```
dl.raw: empty
```

 </details>
<summary>

**Comment by vszakats** [comment]
Did you try adding `--location` (to follow redirects)?

**Comment by bagder** [comment]
To prove @vszakats' point:
~~~
$ curl -I https://crates.io/api/v1/crates/bitflags/1.3.2/download
HTTP/2 302 
location: https://static.crates.io/crates/bitflags/bitflags-1.3.2.crate
...

**Comment by 6543** [comment]
-L
