### ISSUE TITLE
SSL connection timeout with mbedtls on some machines

### ISSUE THREAD

**Issue by adnan-kamili** [curl/curl#9416]
Our app uses libcurl and we are facing SSL connection timeout issue on some machines. On one machine this always fails with an SSL Timeout issue. But if we use the system curl to make the same request it succeeds. So, I suspect some issues with the SSL backend (mbedTLS).

You can download the Wireshark dump from the link below. For the machines where it works and where it doesn't work.

https://www.dropbox.com/s/eaaa8vxs4f9h7wy/tcp_dump.zip?dl=0

### curl/libcurl version

libcurl v7.76.0

### operating system

Linux 5dc6475798-5j28l 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 GNU/Linux

**Comment by bagder** [comment]
So they fail to complete the TLS connect in time? Does it happen on specific sites? All sites? Can you show a libcurl version message log from a failure? Can you show us a small example code that reproduces this for you?

**Comment by adnan-kamili** [comment]
The curl connection timeout is set to 10s but we get the SSL timeout error in less than 2 secs.

```
void LexHttpClient::SetOptions()
{
	if (curl)
	{
            curl_easy_setopt(curl, CURLOPT_TIMEOUT, 30L);  //30 seconds
            curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT, 10L);  //10 seconds
	    curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 3L);  // max redirects 3
            curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
            curl_easy_setopt(curl, CURLOPT_FORBID_REUSE, 1L);
	    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, ResponseWriter);
	    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
            curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
		...
	}
}
```

Does it happen on specific sites? All sites?

Our client only connects to api.cryptlex.com and this happens only on few machines on a pod running inside K8s. But the same request succeeds if we use curl installed on the system to send the same request. Of course, the system curl uses HTTP2 + OpenSSL and our libcurl uses HTTP1 and mbedSSL.



Can you show a libcurl verbose message log from a failure?

```
*   Trying 35.xx.xxx.31:443...
* Connected to api.cryptlex.com (35.xx.xxx.31:443) port 443 (#0)
* mbedTLS: Connecting to api.cryptlex.com:443
* mbedTLS: Set min SSL version to TLS 1.0
* SSL connection timeout
* Closing connection 0

Time taken for network request: 1.62s
```

**Comment by bagder** [comment]
There are three places in lib/vtls/mbedtls.c that can output `SSL connection timeout` - but I can't quite figure out which one that you fall over as none of them should trigger before the set timeout. Can you figure out which one it is?

**Comment by adnan-kamili** [comment]
I am sorry I don't have any working knowledge of this library.

**Comment by bagder** [comment]
If you can't debug this at all, then you need to provide an example code for us that reproduced this problem. I can't reproduce it. Otherwise there is nothing we can do!

**Comment by adnan-kamili** [comment]
Upgrading libcurl and mbedTLS to the latest versions and adding support for nghttp2 fixed the issue.
