### ISSUE TITLE
CURLOPT_MAX_RECV_SPEED_LARGE causes multi-uv.c to fail

### ISSUE THREAD

**Issue by zjx20** [curl/curl#942]
### I did this

Downloaded the example code [multi-uv.c](https://curl.haxx.se/libcurl/c/multi-uv.html) and added just one line `curl_easy_setopt(handle, CURLOPT_MAX_RECV_SPEED_LARGE, (curl_off_t)500 * 1024);` to add_download(). The modified version of multi-uv exits too early to finish the download.

Steps to reproduce:
1. Save the modified code https://gist.github.com/zjx20/fda1da4b71f206cd6cadf234e105c55e as multi-uv.c
2. Prepare libcurl 7.50.0 and libuv 1.9.1 (`brew install libuv`)
3. Compile the code: `gcc -lcurl -luv multi-uv.c -o multi-uv`
4. Create a dummy file and run http server locally: `mkfile -n 5m sparseFile && python -m SimpleHTTPServer`
5. Run multi-uv: `./multi-uv http://127.0.0.1:8000/sparseFile`
6. The program should exit immediately. The downloaded file should be named "1.download", but the file size is 98304 while 5242880 is expected.

Also see #793
### I expected the following

It should download the file correctly.
### curl/libcurl version

libcurl 7.50.0

[curl -V output perhaps?]
### operating system

macOS 10.11.6

**Comment by zjx20** [comment]
@bagder Please take a look, thanks!
I believe there is something wrong in either the [multi-uv.c](https://curl.haxx.se/libcurl/c/multi-uv.html) example or libcurl itself.

**Comment by bagder** [comment]
So what happens with the socket callback when the speed limiter hits? Isn't it called to remove the specific socket?

**Comment by zjx20** [comment]
I added printf calls to handle_socket() and start_timeout(). I had also updated the [gist](https://gist.github.com/zjx20/fda1da4b71f206cd6cadf234e105c55e), you can check it out if you like. 

The program outputs few lines and then exits:

```
$ ./multi-uv http://127.0.0.1:8000/sparseFile
Call start_timeout(0x7ff998c0c100, 1, 0x0)
Added download http://127.0.0.1:8000/sparseFile -> 1.download
Call start_timeout(0x7ff998c0c100, 1, 0x0)
Call handle_socket(0x7ff999010e00, 11, 2, 0x0, 0x0)
Call start_timeout(0x7ff998c0c100, 1, 0x0)
Call handle_socket(0x7ff999010e00, 11, 1, 0x0, 0x7ff998e007e0)
Call handle_socket(0x7ff999010e00, 11, 4, 0x0, 0x7ff998e007e0)
Call start_timeout(0x7ff998c0c100, 161, 0x0)
Call handle_socket(0x7ff999010e00, 11, 1, 0x0, 0x0)
Call start_timeout(0x7ff998c0c100, 28, 0x0)
Call handle_socket(0x7ff999010e00, 11, 4, 0x0, 0x7ff998c14d80)
```

The third parameter of handle_socket()  is "action", which means:
```
#define CURL_POLL_NONE   0
#define CURL_POLL_IN     1
#define CURL_POLL_OUT    2
#define CURL_POLL_INOUT  3
#define CURL_POLL_REMOVE 4
```

One more thing: I found that it can finish the download after I added the printf. So I decreased the speed limit to 100KB/s, and now it can finish downloading **occasionally**.

**Comment by jay** [comment]
Sorry to say not a lot of us are using libuv with curl. There were some fixes made a month or two ago to the multi-uv example, could you try the latest version from the repo and see what happens?

/cc @bsnote

**Comment by zjx20** [comment]
@jay Thank you for mentioning the example code has been updated. I have tried the latest example, but the issue is still present. And I have also tried it with the latest version of libcurl (7.51.0) and libuv (1.10.1), it didn't work either.

**Comment by mkauf** [comment]
I have proposed a bugfix in pull request #1233.
