### ISSUE TITLE
CURLOPT_PROXY_SSLCERT_BLOB man page:

### ISSUE THREAD

**Issue by ProceduralMan** [curl/curl#9434]
The option is available for All TLS based protocols: HTTPS, FTPS, IMAPS, POP3S, SMTPS etc. 

But, being "an alternative to [CURLOPT_PROXY_SSLCERT](https://curl.se/libcurl/c/CURLOPT_PROXY_SSLCERT.html) which instead expects a file name as input."

Shouldn't it have the same availability that CURLOPT_PROXY_SSLCERT (that is, only for HTTPS proxies)?

**Comment by bagder** [comment]
Correct. Good catch!
