### ISSUE TITLE
err: Failed writing body (1 != 126) on ubuntu20.04

### ISSUE THREAD

**Issue by chen435889286** [curl/curl#9439]
hello 
I tried it in Ubuntu20.04
curl
cmake --version 3.24.0
sudo ./a.out
err: Failed writing body (1 != 126)

./a.out
err: Failed writing body (165 != 127)

**Comment by bagder** [comment]
Please explain what that `a.out` is and how that is related to curl.

**Comment by bagder** [comment]
No response
