### ISSUE TITLE
IOS: Multi handle hanging when cleanup

### ISSUE THREAD

**Issue by TXTT2016** [curl/curl#9445]
### I did this
Use multi handle do transfer, but when a new easy handle added to perform, there are to many strange debug logs output. just like this, is this a normal log?
![image](https://user-images.githubusercontent.com/26682461/188769031-d42ef5fe-2685-499e-a2bc-2cfc967dc3f0.png)

And the multi perform transfering stucked by the last output logs.
![image](https://user-images.githubusercontent.com/26682461/188769546-47eaaf4c-b278-4702-95bd-47d5597a5376.png)

This easy handle's debug logs are also strange.
```code
	行 88865: 2c3b 09-03 22:35:09.506+08:00(15412:2199451)I/: HttpConnection init: [0x11be759c8], Curl handler init: [0x11cac9000]
	行 88900: 2c54 09-03 22:35:09.508+08:00(15412:2199460)I/: CURL [0x11cac9000]: STATE: INIT => CONNECT
	行 88902: 2c55 09-03 22:35:09.508+08:00(15412:2199460)I/: CURL [0x11cac9000]: STATE: INIT => CONNECT handle 0x11cac9000; line 1789 (connection #-5000)
	行 88904: 2c56 09-03 22:35:09.508+08:00(15412:2199460)I/: CURL [0x11cac9000]: Found bundle for host uc.yealink.com: 0x282ddfde0 [serially]
	行 88906: 2c57 09-03 22:35:09.509+08:00(15412:2199460)I/: CURL [0x11cac9000]: STATE: CONNECT => RESOLVING
	行 88908: 2c58 09-03 22:35:09.509+08:00(15412:2199460)I/: CURL [0x11cac9000]: STATE: CONNECT => RESOLVING handle 0x11cac9000; line 1835 (connection #148)
	行 88964: 2c74 09-03 22:35:09.696+08:00(15412:2199460)I/: CURL [0x11cac9000]: Hostname in DNS cache was stale, zapped
	行 89044: 2c9e 09-03 22:35:09.717+08:00(15412:2199460)I/: CURL [0x11cac9000]: Hostname in DNS cache was stale, zapped
	行 89327: 2d32 09-03 22:35:09.771+08:00(15412:2199460)I/: CURL [0x11cac9000]: Hostname in DNS cache was stale, zapped
	行 89704: 2e00 09-03 22:35:09.850+08:00(15412:2199460)I/: CURL [0x11cac9000]: Hostname in DNS cache was stale, zapped
	行 91104: 30e4 09-03 22:35:10.337+08:00(15412:2199460)I/: CURL [0x11cac9000]: multi_done
```

Then when i clean the multi handle to stop the transfering, the operator also stucked. This is the stucked stack:
```code
Curl_thread_join (in aqua-http) + 32
Curl_resolver_kill (in aqua-http) + 36
multi_done (in aqua-http) + 92
curl_multi_cleanup (in aqua-http) + 132
```

### I expected the following
I can normally cleanup the multi handle, this operator wont stucked
### curl/libcurl version
7.80.0
[curl -V output]

### operating system
just happened on IOS

**Comment by bagder** [comment]
You probably need to tell us a lot more about your libcurl use or provide a small source code that we can use to reproduce.

The wait in cleanup might be this known issue: https://curl.se/docs/knownbugs.html#Multi_perform_hangs_waiting_for

**Comment by TXTT2016** [comment]
> You probably need to tell us a lot more about your libcurl use or provide a small source code that we can use to reproduce.
> 
> The wait in cleanup might be this known issue: https://curl.se/docs/knownbugs.html#Multi_perform_hangs_waiting_for

Yes, my problem is the same as this issue(https://github.com/curl/curl/issues/2975)

**Comment by TXTT2016** [comment]
By using c-ares, `Curl_resolver_kill` not block the `multi_done` func.

Can this problem fixed by using c-ares to do dns resolve?

**Comment by bagder** [comment]
Yes, or the #9147 approach.
