### ISSUE TITLE
Livo doesn't produce correct downloaded file

### ISSUE THREAD

**Issue by lpicquet-metapack** [curl/curl#9456]
### I did this
curl -ivL --fail -u "${artifactoryUser}:${artifactoryPassword}" https://some.jfrog.io/some_artifact.jar -o some_artifact.jar

head some_artifact.jar

and I got the following file content:
HTTP/1.1 302 Found
Date: Thu, 08 Sep 2022 13:37:30 GMT
Transfer-Encoding: chunked
Connection: keep-alive
X-JFrog-Version: Artifactory/7.41.7 74107900
X-headers removed
Location: https://jfrog-prod-euw1-shared-ireland-main.s3.amazonaws.com/some url to be redirected to
Strict-Transport-Security: max-age=15724800; includeSubDomains

removing i and v from the command line options produced the correct outcome.

the file size seems to be set correctly (clearly matches the size of the expected downloaded file)

### I expected the following
all redirects to be followed, information to be output and a jar file downloaded

### curl/libcurl version

curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

### operating system

Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

**Comment by dfandrich** [comment]
By using the -i option, you are requesting that curl include protocol 
response headers in the output, as well as the content of the URL itself. curl 
is doing exactly what you asked.

**Comment by lpicquet-metapack** [comment]
shouldn't the content produced by the -i option be sent to stderr? stdout shouldn't be polluted with the HTTP exchange...

**Comment by bagder** [comment]
`-i` ask for the headers to get sent to the same place as the body. Maybe you are looking for `-D` ?

**Comment by lpicquet-metapack** [comment]
I can use -D instead thanks, that will be useful for my use case.
According to this: https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html, then informational output should be on stderr. In my opinion, the content delivered at the requested url should be the only one on stdout. Maybe the docs can be updated with an example to make it clear which standard stream is being used for -i, -D and -v?

**Comment by bagder** [comment]
It isn't "informational" anymore when you *explicitly* ask to "Include the HTTP response headers in the output" as the man page says.
