### ISSUE TITLE
CURL_RUN_IFELSE sets LD_LIBRARY_PATH, which causes configure to fail

### ISSUE THREAD

**Issue by AdrianVovk** [curl/curl#9457]
### I did this

I ran `configure --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc  --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib  --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/usr/com  --mandir=/usr/share/man --infodir=/usr/share/info  --enable-deterministic-archives --disable-static --enable-shared --disable-Werror --disable-dependency-tracking --with-openssl --with-ca-bundle=/etc/ssl/cert.pem --enable-debug --disable-static --enable-optimize`

And got the following output:
```
checking run-time libs availability... /buildstream/carbonOS/pkgs/curl.bst/configure: line 33817:  2207 Segmentation fault      (core dumped) cat confdefs.h - <<_ACEOF > conftest.$ac_ext
/* end confdefs.h.  */

int main()
{
  return 0;
}

_ACEOF

/buildstream/carbonOS/pkgs/curl.bst/configure: line 2466:  2210 Segmentation fault      (core dumped) sed 's/^/| /' conftest.$ac_ext 1>&5
/buildstream/carbonOS/pkgs/curl.bst/configure: line 2466:  2211 Segmentation fault      (core dumped) rm -rf conftest.dSYM conftest_ipa8_conftest.oo
failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto  -lz 
/buildstream/carbonOS/pkgs/curl.bst/configure: line 30:  2221 Segmentation fault      (core dumped) sed -n "/^[_$as_cr_alnum]*_cv_[_$as_cr_alnum]*=/p"
/buildstream/carbonOS/pkgs/curl.bst/configure: line 29:  2216 Broken pipe             ( set ) 2>&1
      2217 Done(139)               | case $as_nl`(ac_space=' '; set) 2>&1` in 
    *${as_nl}ac_space=\ *)
        sed -n "s/'/'\\\\''/g;
          s/^\\([_$as_cr_alnum]*_cv_[_$as_cr_alnum]*\\)=\\(.*\\)/\\1='\\2'/p"
    ;;
    *)
        sed -n "/^[_$as_cr_alnum]*_cv_[_$as_cr_alnum]*=/p"
    ;;
esac
      2218 Segmentation fault      (core dumped) | sort
/buildstream/carbonOS/pkgs/curl.bst/configure: line 85:  2222 Broken pipe             for ac_var in $ac_subst_vars;
do
    eval ac_val=\$$ac_var; case $ac_val in 
        *\'*)
            ac_val=`printf "%s\n" "$ac_val" | sed "s/'/'\\\\\\\\''/g"`
        ;;
    esac; printf "%s\n" "$ac_var='$ac_val'";
done
      2223 Segmentation fault      (core dumped) | exit $1
/buildstream/carbonOS/pkgs/curl.bst/configure: line 85:  2230 Segmentation fault      (core dumped) exit $1
/buildstream/carbonOS/pkgs/curl.bst/configure: line 88:  2231 Segmentation fault      (core dumped) exit $1
```

If I look at coredumpctl, I can see that all the tools that `configure` tries to run segfault:

```
Thu 2022-09-08 14:19:17 EDT  127104 1000 1000 SIGSEGV present  /tools/bin/cat                                                    17.7K
Thu 2022-09-08 14:19:17 EDT  127184 1000 1000 SIGSEGV present  /tools/bin/gcc                                                    26.3K
Thu 2022-09-08 14:19:17 EDT  127279 1000 1000 SIGSEGV present  /tools/bin/sed                                                    17.6K
Thu 2022-09-08 14:19:17 EDT  127303 1000 1000 SIGSEGV present  /tools/bin/rm                                                     17.3K
Thu 2022-09-08 14:19:17 EDT  127378 1000 1000 SIGSEGV present  /tools/bin/sed                                                    17.7K
Thu 2022-09-08 14:19:17 EDT  127481 1000 1000 SIGSEGV present  /tools/bin/sort                                                   17.9K
Thu 2022-09-08 14:19:17 EDT  127494 1000 1000 SIGSEGV present  /tools/bin/sed                                                    17.6K
Thu 2022-09-08 14:19:17 EDT  127588 1000 1000 SIGSEGV present  /tools/bin/sed                                                    17.6K
Thu 2022-09-08 14:19:17 EDT  127581 1000 1000 SIGSEGV present  /tools/bin/sort                                                   17.9K
Thu 2022-09-08 14:19:17 EDT  127698 1000 1000 SIGSEGV present  /tools/bin/sed                                                    17.6K
Thu 2022-09-08 14:19:17 EDT  127819 1000 1000 SIGSEGV present  /tools/bin/cat                                                    17.6K
Thu 2022-09-08 14:19:17 EDT  127877 1000 1000 SIGSEGV present  /tools/bin/rm                                                     17.3K
```

My build setup is probably a bit unconvnentional, but it shouldn't cause problems like this. Basically, curl is being built in an early bootstrapping environment for a distro. I have a complete toolchain + userspace installed into /tools (coreutils, gcc, binutils, etc). The binaries in `/tools/bin` all depend on libraries in `/tools/lib`. HOWEVER, the binaries produced by this build environment are configured to load libraries from `/usr/lib`. So for instance, if you use `/tools/bin/gcc main.c -o main`, the created `main` binary
will link against libc in `/usr/lib/libc.so.6`, whereas `/tools/bin/gcc` itself links against `/tools/lib/libc.so.6`. The libraries in `/tools/lib` and `/usr/lib` are not necessarily the same version. From the perspective of curl's build system, this setup shouldn't matter whatsoever. `/tools/bin/gcc` behaves exactly like a normal `/usr/bin/gcc` would. The binaries it produces link against the standard locations and can run (so it's not a cross-compiling situation!).

I investigated, and turns out that the build system sets LD_LIBRARY_PATH in CURL_RUN_IFELSE. This, in turn, causes every `/tools` binary (gcc, rm, cat, sed, etc) to prefer libaries in `/usr/lib` over those in `/tools/lib`. This includes libc, which means that these tools are launched against a different (ABI incompatible) build of glibc, which immediately makes them segfault.

### I expected the following

`configure` doesn't force my build tools to load libraries from the wrong location

### curl/libcurl version

7.85.0

### operating system

- carbonOS 2022.2 (indev)
- `Linux adrians-macbook 5.18.10-mainline #1 SMP PREEMPT_DYNAMIC Wed Jul 27 03:12:31 UTC 2022 x86_64 GNU/Linux`

**Comment by bagder** [comment]
I understand that this becomes an issue for you, but I do not have any immediate fix or comfort. The `LD_LIBRARY_PATH` trick used in the current configure script was added a long time ago because before that users would often get configure errors that were hard to understand and track down.

**Comment by bagder** [comment]
This is basically a variation of the known bug: https://curl.se/docs/knownbugs.html#configure_finding_libs_in_wrong

**Comment by AdrianVovk** [comment]
> basically a variation of the known bug

Eh I don't really see the similarity. In the known bug curl links itself against the wrong libraries. In this bug curl is forcing the toolchain to load the wrong libraries... But whatever helps you keep track of the issue; you're the maintainer after all :)

For now I have this workaround: `sed -i '/LD_LIBRARY_PATH=/d' m4/curl-functions.m4`

**Comment by bagder** [comment]
Similar in that it happens because when pointing out one lib it finds others that get used accidentally.

**Comment by bagder** [comment]
I consider this a known issue, nobody is working on a fix and I don't even know how to fix this in a way that doesn't just shift the problem around and cause other problems instead. Problems we fixed by adding this `LD_LIBRARY_PATH` approach...

Fortunately, @AdrianVovk found a workaround.

Unless someone takes on this issue or shows some initiative to solve it, I will close it soon.
