### ISSUE TITLE
curl smtp uses name of --upload-file for EHLO

### ISSUE THREAD

**Issue by Daniel-Nashed** [curl/curl#9464]
Without `--upload-file` the EHLO used is the hostname component of the resolved local name.
I would expect it to be the full FQDN. But this isn't the problem here.
Having a way to specify the EHLO string would be also helpful.

### Invoked command:

```
curl -v -k --ssl-reqd --mail-from jdoe@acme.com --mail-rcpt fadmin@notes.lab smtp://127.0.0.1 --upload-file /local/notesdata/email.txt
```

### Result

```
EHLO email.txt
```
### Result with more context

```
 TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> EHLO email.txt
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
< 250-automation.notes.lab Hello email.txt ([127.0.0.1]), pleased to meet you
< 250-HELP
< 250-AUTH LOGIN
< 250-SIZE
< 250 PIPELINING
```

### Expected result

```
HELO myhostname
```

### curl/libcurl version

```
curl 7.83.1 (x86_64-unknown-linux-gnu) libcurl/7.83.1 OpenSSL/3.0.3 zlib/1.2.11 zstd/1.5.2 libssh2/1.9.0
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
```

### operating system

**VMware Photon OS 4.0** --> because it has a very current curl version out of the box. Same behavior also in older versions/platforms.

```
Linux automation.notes.lab 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 GNU/Linux
```

This is a minor issue for my use-case, but for production email the EHLO can be important, because of anti-spam sanity checks on remote hosts.

**Comment by bagder** [comment]
This behavior is documented here: https://curl.se/docs/url-syntax.html#smtp

Unfortunately, there is no way for curl to figure out the FQDN on its own.

I don't think this is a bug.

**Comment by Daniel-Nashed** [comment]
Thanks for you quick reply! 
Using the file name as the HELO isn't expected, but we could life with it, if this is the intended behavior.

Let me try if we can have names with more than one dot. IMHO having a separate parameter would be a more clear way to specify the name.

**Comment by Daniel-Nashed** [comment]
Tested and it works. I can create a file with the name I want as the EHLO. 
This is a very unusual way to specify the FQDN. 
Maybe this could be a separate parameter in future?

**Comment by bagder** [comment]
>  Maybe this could be a separate parameter in future?

I would imagine so, yes. The current approach is... a little weird.

**Comment by Daniel-Nashed** [comment]
So this is not a bug, but a potential improvement in future. 
Thanks for your quick help!
