### ISSUE TITLE
error during libcurl compilation

### ISSUE THREAD

**Issue by testssl** [curl/curl#947]
i am facing compilation error related to "ASN1_OBJECT". Error is as given below :-

asn1.h:530: error: expected specifier-qualifier-list before 'ASN1_OBJECT'
asn1.h:783: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
asn1.h:784: error: expected ')' before '*' token
asn1.h:785: error: expected ')' before '*' token
asn1.h:786: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
asn1.h:788: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
asn1.h:917: error: expected declaration specifiers or '...' before 'ASN1_OBJECT'
asn1.h:921: error: expected declaration specifiers or '...' before 'ASN1_OBJECT'
asn1.h:924: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token

this above error is coming while compiling for "libcurl" - curl-7.46.0.

Is there any dependency of curl version for openssl 1.0.2h?

**Comment by bagder** [comment]
More details please!

On what platform? Exactly how do you build curl? That looks like an OpenSSL header. Is it openssl 1.0.2h and did you build it yourself ?

**Comment by testssl** [comment]
we are building curl using PTXdist tool. 

earlier we were using openssl 1.0.1q, and libcurl curl-7.46.0 was building well with that.

Now we are upgrading from 1.0.1q to 1.0.2h, and facing this error.

I can see that the asn1.h file of openssl is modified in 1.0.2h and some definitions are not available in same file as it used to be in 1.0.1q

so do we need to upgrade libcurl too?

**Comment by bagder** [comment]
I just tried building curl 7.46.0 from git with OpenSSL 1.0.2g on Debian and apart from a non-related compiler warning, it works just fine. I don't get any OpenSSL-related problems.

I'm inclined to say there's something funny with your OpenSSL file based on that warning.
