### ISSUE TITLE
RESUME_FROM_LARGE OverflowError for offset > 2 GB

### ISSUE THREAD

**Issue by valgur** [curl/curl#948]
I am trying to continue an interrupted download of a 4.5 GB file, where 3.3 GB is already on disk. 
Among the usual setup I am doing something along the lines of
```python
size = os.path.getsize("x.zip")
print("File size is {} bytes on disk".format(size))
c.setopt(pycurl.RESUME_FROM_LARGE, size)
```
This results in
> File size is 3333858173 bytes
>
> **OverflowError: Python int too large to convert to C long**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> ...
> SystemError: &lt;built-in method setopt of pycurl.Curl object at 0x0000020D055970D8&gt; returned a result with an error set

### curl/libcurl version
Installed from pip (pycurl-7.43.0-cp35-none-win_amd64.whl):
PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2e zlib/1.2.8 c-ares/1.10.0 libssh2/1.6.0

### operating system
64-bit Windows 10
Python 3.5.2 :: Anaconda custom (64-bit)

**Comment by bagder** [comment]
That sounds like a [pycurl issue](https://github.com/pycurl/pycurl/issues), which is separate from libcurl. The `RESUME_FROM_LARGE` option takes a `curl_off_t` type which is 64 bits on all modern platforms-

**Comment by valgur** [comment]
Oh, this was indeed intended for the pycurl github issue tracker. Apologies for the mixup!
