### ISSUE TITLE
lib1597.c nonstandard extension used : 'exp' : cannot be initialized using address of automatic variable

### ISSUE THREAD

**Issue by bagder** [curl/curl#9524]
commit 9d5132904 landed a change to lib1597.c that isn't C89 compliant and some [builds on appveyor](https://ci.appveyor.com/project/curlorg/curl/builds/44805354/job/xnlccnpi5d7b5mty#L983) caught it.

The same change caused another warning but that is handled in #9522 

/cc @monnerat

**Comment by monnerat** [comment]
Sorry for that!
I think putting this table and CURLcode vars in global scope will fix the problem.
I'll soon submit a PR for it.
