### ISSUE TITLE
7.85.0: curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by emanruse** [curl/curl#9526]
### I did this

0. Searched and found a [similar issue](https://github.com/curl/curl/issues/3206)

1. `curl -v https://www.schneier.com/feed/atom/`

2. Got output:
```
curl -v https://www.schneier.com/feed/atom/
*   Trying 199.16.173.239:443...
* Connected to www.schneier.com (199.16.173.239) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=tls.automattic.com
*  start date: Jul 22 09:18:38 2022 GMT
*  expire date: Oct 20 09:18:37 2022 GMT
*  subjectAltName: host "www.schneier.com" matched cert's "www.schneier.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /feed/atom/]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.schneier.com]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x19981f0)
> GET /feed/atom/ HTTP/2
> Host: www.schneier.com
> user-agent: curl/7.85.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Connection #0 to host www.schneier.com left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

The result is similar with https://blog.trailofbits.com/feed/

3. Tested the same URLs with the known `--http1.1` workaround.

Result: correct download.

4. Tested the same URLs in Firefox

Result: correct download using HTTP/2

### I expected the following

Correct curl download of the RSS feed using HTTP/2.

### curl/libcurl version

```
curl 7.85.0 (i586-suse-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### operating system

openSUSE Tumbleweed
5.19.2-1-pae #1 SMP PREEMPT_DYNAMIC Thu Aug 18 05:06:49 UTC 2022 (6c252ef) i686

### More info

In the older issue it [is said](https://github.com/curl/curl/issues/3206#issuecomment-439551883) that "This is a broken server and not a curl problem." However, those same URLs tested directly in Firefox work fine using HTTP/2 (looking at the network console of the browser).

**Comment by bagder** [comment]
This is nghttp2 1.49.0 that started to reject header fields with trailing whitespace, as that is an RFC violation. Also discussed here: #9479

The next nghttp2 release (1.50.0) has an option to switch off that behavior and curl will use that if available. But nghttp2 1.50.0 has not been released yet and neither has a curl version with that added logic.

This is not a curl bug. This is changed behavior in nghttp2. Our advice is to either downgrade nghttp2 to 1.48.0 again for the time being, or to apply a patch to nghttp2 to make it go back to its previous behaviors.

**Comment by bagder** [comment]
It looks like both these are Wordpress feeds.

**Comment by bagder** [comment]
I'm saying that nghttp2 added this check and curl uses nghttp2 for HTTP/2. This check is backed up by wording in RFC 9113. curl did not change anything to make this happen. Yes, the browsers don't care about that wording and neither will curl in coming releases - once nghttp2 provides the option for us to switch it off.

**Comment by exussum12** [comment]
Not sure what is different about my setup but the example commands work

```
> GET /feed/atom/ HTTP/2
> Host: www.schneier.com
> user-agent: curl/7.81.0
> accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200 
< server: nginx
< date: Sat, 17 Sep 2022 21:27:07 GMT
< content-type: application/atom+xml; charset=UTF-8
< strict-transport-security: max-age=31536000
< vary: Accept-Encoding
< x-nananana: Batcache-Hit
< host-header: Pressable
< vary: Cookie
< last-modified: Fri, 16 Sep 2022 21:01:19 GMT
< etag: "022e1df437915d134c34862de9519f96"
< link: <https://www.schneier.com/wp-json/>; rel="https://api.w.org/"
< x-ac: 4.lhr _atomic_ams 
< 
<?xml version="1.0" encoding="UTF-8"?><feed
	xmlns="http://www.w3.org/2005/Atom"
	xmlns:thr="http://purl.org/syndication/thread/1.0"
	xml:lang="en-US"
	
	xmlns:georss="http://www.georss.org/georss"

```


Happy to report or even fix this if I can see what header is causing the issue here

**Comment by bagder** [comment]
> Not sure what is different about my setup but the example commands work

not using nghttp2 1.49.0 perhaps?

**Comment by exussum12** [comment]
Yeah sorry I should have spotted that.

The issue is not wordpress (the open source project) but the host of wordpress.com (Automattic). Self hosted blogs are not effected.

**Comment by bagder** [comment]
> Self hosted blogs are not effected.

How can you tell? Do you know why it happens?

**Comment by exussum12** [comment]
It's a header from Automattic hosted content (x-ac in this case) 

`00000000: 3c20 782d 6163 3a20 312e 6c68 7220 5f61  < x-ac: 1.lhr _a
00000010: 746f 6d69 635f 616d 7320 0a0a            tomic_ams ..
`
 The trailing space is seen there.

https://wordpress.org/support/topic/explanation-of-x-ac-header/

That header does not exist in the wordpress code base.

The first blog is not wordpress.com but pressable - from this page https://pressable.com/wordpress-cloud-hosting-platform/

> Why choose our powerful cloud hosting platform?
> Created by Automattic – the same company behind WordPress.com

**Comment by bagder** [comment]
Thanks everyone for your assistance. To sum up:

 - this is an issue due to new stricter checks in nhttp2 1.49.0
 - nghttp2 1.48.0 did not have these checks
 - it happens because servers send non-compliant header fields over HTTP/2
 - the popular browsers don't check or complain about this violation
 - in nghttp2 1.50.0 a new function exists that allows applications to disable this stricter check
 - in the pending curl version 7.86.0 - if built with nghttp2 1.50.0 (or later) curl will disable this stricter check

Thanks for flying curl. Fun for everyone.

**Comment by bazza** [comment]
Sorry for the trouble!  We have deployed a fix for the trailing whitespace on our (Automattic) side.

**Comment by bagder** [comment]
lovely @bazza !

**Comment by dbl001** [comment]
I'm getting the same error downloading: ggml-alpaca-7b-q4.bin 
Any ideas?
```
% curl -v -o ./models/ggml-alpaca-7b-q4.bin -C - https://ipfs.io/ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1
** Resuming transfer from byte position 3843573698
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 209.94.90.1:443...
* Connected to ipfs.io (209.94.90.1) port 443 (#0)
* ALPN: offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /Users/davidlaxer/anaconda3/ssl/cacert.pem
*  CApath: none
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4082 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.i.ipfs.io
*  start date: Mar 27 17:15:30 2023 GMT
*  expire date: Jun 25 17:15:29 2023 GMT
*  subjectAltName: host "ipfs.io" matched cert's "ipfs.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
} [5 bytes data]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1]
* h2h3 [:scheme: https]
* h2h3 [:authority: ipfs.io]
* h2h3 [range: bytes=3843573698-]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7fa633809a00)
} [5 bytes data]
> GET /ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1 HTTP/2
> Host: ipfs.io
> range: bytes=3843573698-
> user-agent: curl/7.88.1
> accept: */*
> 
{ [5 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/2 206 
< server: openresty
< date: Fri, 14 Apr 2023 17:03:31 GMT
< content-type: application/octet-stream
< content-length: 369281323
< access-control-allow-methods: GET
< cache-control: public, max-age=29030400, immutable
< etag: "QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1"
< x-ipfs-gateway-host: ipfs-bank14-sv15
< x-ipfs-path: /ipfs/QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1
< x-ipfs-roots: QmUp1UGeQFDqJKvtjbSYPBiZZKRjLp8shVP9hT8ZB9Ynv1
< x-ipfs-pop: ipfs-bank14-sv15
< timing-allow-origin: *
< x-ipfs-datasize: 4212855021
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, OPTIONS
< access-control-allow-headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
< access-control-expose-headers: Content-Range, X-Chunked-Output, X-Stream-Output
< x-ipfs-lb-pop: gateway-bank1-sv15
< x-bfid: e373b659d3ed75692a108bc47e7ffd1d
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-proxy-cache: MISS
< content-range: bytes 3843573698-4212855020/4212855021
< 
{ [15624 bytes data]
 19  352M   19 67.1M    0     0   528k      0  0:11:21  0:02:09  0:09:12     0* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
 19  352M   19 68.1M    0     0   536k      0  0:11:12  0:02:10  0:09:02  244k
* Connection #0 to host ipfs.io left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
(base) davidlaxer@bluediamond llama.cpp % 

```

**Comment by tnt** [comment]
Getting the same error on ArchLinux with this [url](https://chinarising.puntopress.com/wp-content/uploads/2023/04/Press-TV-KSA-Iran.mp3) (also wordpress).

    curl --version  
    curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0
    Release-Date: [unreleased]
    Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
    Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

**Comment by exussum12** [comment]
not 100% sure its the same issue here

HTTP/2 404 

is the only line with a trailing space, but I *think* thats a generated line in http2? 

also you are using a patched version (nghttp2/1.52.0)

**Comment by courtens** [comment]
I got **curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL  (err 1)** using
```
C:\ProgramData\chocolatey\bin>curl --version
curl 8.7.1 (x86_64-w64-mingw32) libcurl/8.7.1 LibreSSL/3.8.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.5 WinIDN libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.60.0 ngtcp2/1.4.0 nghttp3/1.2.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL SSPI threadsafe UnixSockets zstd
```

> Thanks everyone for your assistance. To sum up:
> 
>     * this is an issue due to new stricter checks in nhttp2 1.49.0
> 
>     * nghttp2 1.48.0 did not have these checks
> 
>     * it happens because servers send non-compliant header fields over HTTP/2
> 
>     * the popular browsers don't check or complain about this violation
> 
>     * in nghttp2 1.50.0 a new function exists that allows applications to disable this stricter check
> 
>     * in the pending curl version 7.86.0 - if built with nghttp2 1.50.0 (or later) curl will disable this stricter check
> 
> 
> Thanks for flying curl. Fun for everyone.

Anything to be concerned about, or should I just ignore it?

**Comment by jay** [comment]
> Anything to be concerned about, or should I just ignore it?

This issue you are commenting on was solved over a year ago. If you have a bug to report please open a [new issue](https://github.com/curl/curl/issues/new?assignees=&labels=&projects=&template=bug_report.yml) and give us a way to reproduce.
