### ISSUE TITLE
Curl is waiting for read while it should be writing in HTTP upload

### ISSUE THREAD

**Issue by jethrogb** [curl/curl#953]
### I did this

In terminal 1:
```
nc -l -p 4443|head -n15
```

In terminal 2:
```
yes|head -c $((1024*1024)) > /tmp/1MB
time curl -k http://localhost:4443/files/1MB --data-binary @/tmp/1MB
```

Terminal 1 output:
```
POST /files/1MB HTTP/1.1
Host: localhost:4443
User-Agent: curl/7.50.0
Accept: */*
Content-Length: 1048576
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

y
y
y
y
y
y
y
write(stdout): Broken pipe
```
**Note:** there is a 1-second delay between the headers showing up and the first `y`.

Terminal 2 output:
```
curl: (56) Recv failure: Connection reset by peer

real	0m1.029s
user	0m0.010s
sys	0m0.013s
```

Same exact thing happens using `openssl s_server`+HTTPS.

### I expected the following

I expected this to take less than 1 second. `strace` reveals that both endpoints are selecting/polling for read (only), and no progress is until there is a timeout in Curl's poll. Curl shouldn't be polling only for read since there is data to be sent.

### curl/libcurl version

curl 7.50.0 (x86_64-pc-linux-gnu) libcurl/7.50.0 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

### operating system

Arch Linux

**Comment by bagder** [comment]
Of course it should "hang", it waits for a HTTP response after having uploaded the file. That's how HTTP works.

**Comment by jethrogb** [comment]
Sorry, should've been more clear. Updated above.

**Comment by bagder** [comment]
First, the one second delay is the client waiting for the 100-continue, until it gives up waiting. That's expected and you can disable that.

But I cannot reproduce this problem. I just did `curl localhost:8080 --data-binary @512MB -o /dev/null` and it too worked as expected: it sent 512MB of zeroes and then sat waiting for a response that never comes.

Using curl 7.50.1 here but I doubt the difference matters.

**Comment by jethrogb** [comment]
You're right, and `-v` is telling me that's what's going on. Setting `--expect100-timeout 0.000001` fixes the issue, but there doesn't seem to be a way to disable the header in its entirety.

**Comment by bagder** [comment]
`-H Expect:`

**Comment by jethrogb** [comment]
Ok so two issues remain, which are mostly a matter of preference I suppose:

1. I think `--expect100-timeout 0` should be the same as `-H Expect:`
2. I think the default behavior of the command-line client should be to not send `Expect: 100-continue` (this behavior is optional on the client according to the RFC)

**Comment by bagder** [comment]
Neither is a bug though, so this issue will be closed. I'd urge you to take such change suggestions to the [curl-library](https://curl.haxx.se/mail/list.cgi?list=curl-library) mailing list for discussions.

1. I'm not entirely convinced, it would be a bit surprising to remove a header when you change a timeout value. But of course, maybe curl should do it on its own and not libcurl...
2. That's a change of behavior I'm rather reluctant to do just for old times sake, but it would be interesting to hear what others have to say about that.
