### ISSUE TITLE
Time condition issue

### ISSUE THREAD

**Issue by lukatop** [curl/curl#9537]
Hi everyone, I tried couple of things with curl, and cannot get the excepted output: 

### I did this

```
lukatopalovic@Lukas-MacBook-Pro ~> curl -f -o 1000G_omni.hg38.vcf.gz -z 1000G_omni.hg38.vcf.gz https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz                                          (base)
Warning: Illegal date format for -z, --time-cond (and not a file name).
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50.7M  100 50.7M    0     0  12.4M      0  0:00:04  0:00:04 --:--:-- 12.4M

lukatopalovic@Lukas-MacBook-Pro ~> curl -f -o 1000G_omni.hg38.vcf.gz -z 1000G_omni.hg38.vcf.gz https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz                                          (base)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 ```

```  
lukatopalovic@Lukas-MacBook-Pro ~> curl -f -o 102M.pdb.gz -z 102M.pdb.gz https://files.rcsb.org/download/102M.pdb.gz                                                                                                                          (base)
Warning: Illegal date format for -z, --time-cond (and not a file name).
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34497  100 34497    0     0  58737      0 --:--:-- --:--:-- --:--:-- 58668
lukatopalovic@Lukas-MacBook-Pro ~> curl -f -o 102M.pdb.gz -z 102M.pdb.gz https://files.rcsb.org/download/102M.pdb.gz                                                                                                                          (base)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34497  100 34497    0     0  63544      0 --:--:-- --:--:-- --:--:-- 63530
```

### I expected the following

I would except that curl will reuse the already downloaded file, like in the example with 1000G_omni.hg38.vcf.gz file. With other file 102M.pdb.gz it won't reuse, and will download again. Can you help why? 

### curl/libcurl version
curl -V                                                                                                                                                                                                    (base)

> curl 7.78.0 (x86_64-apple-darwin13.4.0) libcurl/7.78.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.9.0 nghttp2/1.41.0
> Release-Date: 2021-07-21
> Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
> Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets

### operating system

> Darwin Lukas-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

**Comment by bagder** [comment]
This is unfortunately the server just ignoring that part of your request and unconditionally serving the file. You can see that if you add `-v` as then you'll see the `If-Modified-Since:` header in the request and that still response with a full file with a 200 response.

**Comment by lukatop** [comment]
Ok, thanks for the explanation. I didn't know what was behind of this behaviour.
