### ISSUE TITLE
attached files corrupted

### ISSUE THREAD

**Issue by filipdns** [curl/curl#9539]
Hello,

When I attached simple jpeg file, the mail received has corrupted one like below, same for xlsx file, it can not be open due corrupted.
![test](https://user-images.githubusercontent.com/35229046/191070332-c08f3b4a-a0f9-4fb6-a6a6-de7488d2cdfa.jpeg)
### 

        part = curl_mime_addpart(alt);
        curl_mime_data(part, msg.toStdString().c_str(), CURL_ZERO_TERMINATED);
        curl_mime_type(part, "text/html; charset=utf-8 ");

        /* Create the inline part. */
        part = curl_mime_addpart(mime);
        curl_mime_subparts(part, alt);
        curl_mime_type(part, "multipart/alternative");
        slist = curl_slist_append(nullptr, "Content-Disposition: inline");
        curl_mime_headers(part, slist, 1);

        /* Add the current source program as an embbeded image. */
        part = curl_mime_addpart(mime);
        QString logo=QApplication::applicationDirPath()+"/Images/logo.jpeg";
        curl_mime_filedata(part, logo.toStdString().c_str());

        // Add the current source program as an attachment.
        part = curl_mime_addpart(mime);
        curl_mime_filedata(part, quotefile.toStdString().c_str());

        // Add the current source program as an attachment.
        /*part = curl_mime_addpart(mime);
        for(int i=0;i<fileList.count();i++)
        {
            QString filename="./"+fileList[i];
            if(fileList[i]!="")
                curl_mime_filedata(part, filename.toStdString().c_str());
        }*/
        curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);

        /* Send the message */
        res = curl_easy_perform(curl);
### 

### 
libcurl version 7.85

**Comment by dfandrich** [comment]
If the message passes through a mail gateway that is not 8 bit clean, then a
binary attachment is going to be corrupted. Binary mail attachments should be
encoded with base64 in the general case. See curl_mime_encoder.

**Comment by bagder** [comment]
How do you determine that the file "is corrupt" when curl sends it? Can you please make a complete source code that we can use to reproduce the issue against our own server(s) ?

**Comment by filipdns** [comment]
> How do you determine that the file "is corrupt" when curl sends it? Can you please make a complete source code that we can use to reproduce the issue against our own server(s) ?

Because the file sent can not be open anymore.

I solved the issue with dfandrich suggestion, ising curl_mime_encoder:

part = curl_mime_addpart(mime);
        QString logo=QApplication::applicationDirPath()+"/Images/logoIgn.jpeg";
        curl_mime_filedata(part, logo.toStdString().c_str());
        **curl_mime_encoder(part, "base64");**
