### ISSUE TITLE
curl_multi_perform does not transfer the whole file

### ISSUE THREAD

**Issue by xinsuinizhuan** [curl/curl#9543]
breake at the function curl_multi_perform:
int running_handles;
~~~c
while (CURLM_CALL_MULTI_PERFORM == curl_multi_perform(g_async_multi, &running_handles)) {
   log_msg_ex("running_handles:%d", running_handles);
}
~~~
![图片](https://user-images.githubusercontent.com/40679769/191219639-29dedb02-152e-43f0-83fc-00f9b2d399c2.png)

I send the 183036 bytes, but the buffer is 65535.

But when i run the server first, then run the client, it works.

**Comment by bagder** [comment]
That code snippet is not enough to reliably download anything. I would urge you to go back and read the documentation for [curl_multi_perform](https://curl.se/libcurl/c/curl_multi_perform.html) again. 

If you think this is an issue, then please provide a complete example that reproduces the problem.

**Comment by xinsuinizhuan** [comment]
//init param
static CURLM* g_async_multi = nullptr;
curl_global_init(CURL_GLOBAL_ALL);
g_async_multi = curl_multi_init();

my add function:
int32 http_client_async_post(char* url, char* content, int32 contentsize, OUT char** ret_buf, OUT int32* bufsize)
{
	CURL* easy_handle = curl_easy_init();
	curl_easy_setopt(easy_handle, CURLOPT_URL, url);
	curl_easy_setopt(easy_handle, CURLOPT_HEADER, 0L);
	curl_easy_setopt(easy_handle, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_NOSIGNAL, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POST, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POSTFIELDS, content);
	curl_easy_setopt(easy_handle, CURLOPT_POSTFIELDSIZE, contentsize);
	curl_multi_add_handle(g_async_multi, easy_handle);
	return 0;
}

my thread:
void* async_http_thr(void* arg)
{
	int still_running = 1;
	struct CURLMsg* m;
	while (true)
	{
		int running_handles;
		CURLMcode mc = curl_multi_perform(g_async_multi, &still_running);

		if (!mc && still_running)
		{
			/* wait for activity, timeout or "nothing" */
			mc = curl_multi_poll(g_async_multi, NULL, 0, 1000, NULL);
		}
		else {
			os_sleep(50);
		}

		int msgs_left = 0;
		CURLMsg* msg;
		while (msg = curl_multi_info_read(g_async_multi, &msgs_left)) {
			if (CURLMSG_DONE == msg->msg) {
				//CHttpRequestCollect::iterator itd;
				//curl_easy_getinfo(msg->easy_handle, CURLINFO_PRIVATE, &itd);
				if (msg->easy_handle != NULL)
				{
					curl_multi_remove_handle(g_async_multi, msg->easy_handle);
					curl_easy_cleanup(msg->easy_handle);
				}
			}
		}
	}
	curl_multi_cleanup(g_async_multi);
	curl_global_cleanup();
	return NULL;
}

I read the video and the call the fucntion http_client_async_post to add, then the thread curl_multi_perform, when my server is not fun it works, but when i run the my projection, then run the server, it break at the curl_multi_perform. but when run the server fisrt, then run my projetion, it ok.

**Comment by bagder** [comment]
> but when i run the my projection, then run the server, it break at the curl_multi_perform

Doesn't that just mean that curl then fails to connect to the server since it isn't running? Maybe if you enabled `CURLOPT_VERBOSE` and checked the return code from the transfer you would learn more.

**Comment by bagder** [comment]
I will also note that your updated example does not at all use that same loop you showed initially...

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/191281536-ffe93b0d-448c-469a-9823-571d08eb0eec.png)

**Comment by bagder** [comment]
It is hard to understand what you mean, but I suspect that the data you told curl to send in the POST is no longer available. `CURLOPT_POSTFIELDS` does **not** copy the data, it only points to the buffer you told it about. You might want to consider `CURLOPT_COPYPOSTFIELDS` instead which then actually do copy the data.

**Comment by xinsuinizhuan** [comment]
yes, when i instand of CURLOPT_POSTFIELDS to CURLOPT_COPYPOSTFIELDS, it not break, but have no data transfor, no data server received:
curl_easy_setopt(easy_handle, CURLOPT_COPYPOSTFIELDS, content);
curl_easy_setopt(easy_handle, CURLOPT_POSTFIELDSIZE, contentsize);

**Comment by piru** [comment]
I think this would be more suitable for some generic curl discussion instead of a bug ticket.

**Comment by dfandrich** [comment]
Try using docs/examples/multi-post.c as the basis to write your program.

**Comment by dfandrich** [comment]
You need to set CURLOPT_POSTFIELDSIZE before CURLOPT_COPYPOSTFIELDS, otherwise there's no way to tell the binary length to copy.

**Comment by xinsuinizhuan** [comment]
> You need to set CURLOPT_POSTFIELDSIZE before CURLOPT_COPYPOSTFIELDS, otherwise there's no way to tell the binary length to copy.

int32 STDCALL http_client_async_post_json(char* url, char* content, int32 contentsize)
{
	CURL* easy_handle = curl_easy_init();
	curl_easy_setopt(easy_handle, CURLOPT_URL, url);
	curl_easy_setopt(easy_handle, CURLOPT_HEADER, 0L);
	curl_easy_setopt(easy_handle, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_NOSIGNAL, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POST, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POSTFIELDSIZE, contentsize);
	curl_easy_setopt(easy_handle, CURLOPT_COPYPOSTFIELDS, content);
	curl_multi_add_handle(g_async_multi, easy_handle);
	return 0;
}

It also no work, the server receive no data.

**Comment by piru** [comment]
There is still insufficient information to be able to help, really.

Either way, I find it exceedingly unlikely this would be a bug in curl.

**Comment by dfandrich** [comment]
Agreed. Try 1) checking all error codes returned by curl functions, 2) enabling libcurl debug logging, 3) trace the requests with Wireshark or similar, 4) read the documentation, not necessarily in that order.

**Comment by xinsuinizhuan** [comment]
> There is still insufficient information to be able to help, really.
> 
> Either way, I find it exceedingly unlikely this would be a bug in curl.

Add send data to g_async_multi:
int32 http_client_async_post_json(char* url, char* content, int32 contentsize)
{
	CURL* easy_handle = curl_easy_init();
	curl_easy_setopt(easy_handle, CURLOPT_URL, url);
	curl_easy_setopt(easy_handle, CURLOPT_HEADER, 0L);
	curl_easy_setopt(easy_handle, CURLOPT_FOLLOWLOCATION, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_NOSIGNAL, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_VERBOSE, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POST, 1L);
	curl_easy_setopt(easy_handle, CURLOPT_POSTFIELDSIZE, contentsize);
	curl_easy_setopt(easy_handle, CURLOPT_COPYPOSTFIELDS, content);
	curl_multi_add_handle(g_async_multi, easy_handle);
	return 0;
}

and in thread to send the data:
void* async_http_thr(void* arg)
{
	int still_running = 1;
	struct CURLMsg* m;
	while (true)
	{
		int running_handles;
		CURLMcode mc = curl_multi_perform(g_async_multi, &still_running);

		if (!mc && still_running)
		{
			/* wait for activity, timeout or "nothing" */
			mc = curl_multi_poll(g_async_multi, NULL, 0, 1000, NULL);
		}
		else {
			os_sleep(50);
		}

		int msgs_left = 0;
		CURLMsg* msg;
		while (msg = curl_multi_info_read(g_async_multi, &msgs_left)) {
			if (CURLMSG_DONE == msg->msg) {
				//CHttpRequestCollect::iterator itd;
				//curl_easy_getinfo(msg->easy_handle, CURLINFO_PRIVATE, &itd);
				if (msg->easy_handle != NULL)
				{
					curl_multi_remove_handle(g_async_multi, msg->easy_handle);
					curl_easy_cleanup(msg->easy_handle);
				}
			}
		}
	}
	curl_multi_cleanup(g_async_multi);
	curl_global_cleanup();
	return NULL;
}

Then the server receive no data. still insufficient information?

**Comment by dfandrich** [comment]
On Tue, Sep 20, 2022 at 07:40:40PM -0700, xinsuinizhuan wrote:
> Then the server receive no data. still insufficient information?

You still haven't given us enough information. The problem could be as simple
as the URL being wrong, and you've given no indication that you've even checked
that the server is being contacted. Logs would go a long way to helping see
what's going on, including logging all the error codes being returned.

**Comment by xinsuinizhuan** [comment]
If i use the curl_easy_setopt(easy_handle, CURLOPT_COPYPOSTFIELDS, content), how to release the copyed data. I only want to send the data, but when the server not run, the curl_multi_perform will false, then i want to remove and clean it, like UDP.how should i do?

**Comment by xinsuinizhuan** [comment]
> This is an _issue_, a _bug report_, on libcurl. We keep the discussion here strictly on topic about what is reported and only that.
> 
> If you have questions on how to use libcurl and its API, please take them to [the curl-library mailing list](https://lists.haxx.se/listinfo/curl-library) or a [GitHub discussion](https://github.com/curl/curl/discussions).

OK. Thank you!

**Comment by bagder** [comment]
This is not a libcurl bug, this is the result of some sort of wrong use but since you have not provided a complete source code that reproduces the problem we cannot help you further.
