### ISSUE TITLE
Mismatching/wrong error message for connect failure

### ISSUE THREAD

**Issue by edo9300** [curl/curl#9549]
I use libcurl in my application, and some times I kept getting users having issues with teh application downloading contents, in my application I log all curl errors via the recommended approach, by both passing ``CURLOPT_ERRORBUFFER`` and calling ``curl_easy_strerror`` on the return code.
Those users were getting logged as the error
```
Couldn't connect to server (Failed to connect to pics.ygopro.co port 2096: Winsock library not initialised)
```
pretty weird error to get, especially since winsock is initialized in the application and the other networking parts of the application worked fine.
By providing a build of my program where I also set ``CURLOPT_VERBOSE`` in the operation, now in stderror the actual error is printed
![image](https://user-images.githubusercontent.com/18705342/191370013-71de3892-deb3-4d4e-a1ae-554fa91ef05d.png)
but the error description returned in the error buffer still contains the wrong message.
It also turned out that those users can't access that domain even via browser, so it might be a domain blocked by their ISP (hence the timeout).

**Comment by bagder** [comment]
Which libcurl version on which operating system?

**Comment by edo9300** [comment]
> Which libcurl version on which operating system?

Had just realized i forgot the version and was adding it, the application is linked to a static curl 7.71.1

**Comment by edo9300** [comment]
https://github.com/edo9300/edopro/blob/62125259f2050cbcbf4a9dd5c1a8111193cec193/gframe/image_downloader.cpp#L85-L92
https://github.com/edo9300/edopro/blob/62125259f2050cbcbf4a9dd5c1a8111193cec193/gframe/image_downloader.cpp#L159-L171 this is the code in that performs the download in my application.

**Comment by bagder** [comment]
It looks like it uses the wrong errno so it gets the completely wrong text in there. The code has changed a bit since 7.71.0 but the current code has the same `Curl_strerror()` call:

https://github.com/curl/curl/blob/8e5b1b66c11c7470ae51f4d77e041271e63374f8/lib/connect.c#L1073-L1081
