### ISSUE TITLE
curl 7.85 can not be built with musl-libc

### ISSUE THREAD

**Issue by georgthegreat** [curl/curl#9560]
Compilation is broken with the following output:

```
In file included from contrib/libs/curl/lib/easy.c:89:
In file included from contrib/libs/curl/lib/easy_lock.h:53:
contrib/libs/musl/include/sched.h:84:7: error: redefinition of 'Curl_ccalloc' as different kind of symbol
void *calloc(size_t, size_t);
      ^
contrib/libs/curl/lib/curl_memory.h:128:29: note: expanded from macro 'calloc'
#define calloc(nbelem,size) Curl_ccalloc(nbelem, size)
                            ^
contrib/libs/curl/lib/curl_memory.h:107:29: note: previous definition is here
extern curl_calloc_callback Curl_ccalloc;
                            ^
In file included from contrib/libs/curl/lib/easy.c:89:
In file included from contrib/libs/curl/lib/easy_lock.h:53:
/home/thegeorg/arcadia/contrib/libs/musl/include/sched.h:85:6: error: redefinition of 'Curl_cfree' as different kind of symbol
void free(void *);
     ^
contrib/libs/curl/lib/curl_memory.h:132:19: note: expanded from macro 'free'
#define free(ptr) Curl_cfree(ptr)
                  ^
contrib/libs/curl/lib/curl_memory.h:104:27: note: previous definition is here
extern curl_free_callback Curl_cfree;
```

Upon brief research it looks like curl by default (i. e. when no CURLDEBUG is defined) goes through double definition chain (i. e. defining `#define free(ptr) Curl_cfree(ptr)` and invoke `free()` from `Curl_cfree`.

In musl it is impossible to `#undef free`, as free is not a macro in musl.

By studying the diff I was unable to find a changeset causing the problem.
Could you, please, take a look?

**Comment by bagder** [comment]
> In musl it is impossible to #undef free, as free is not a macro in musl.

It is not a define virtually anywhere (the undef is but a precaution for some edge case we ran into decades ago) and in C, undef'ing a symbol that isn't defined is just a no-op.

**Comment by georgthegreat** [comment]
7.84.0 is buildable with musl, so it is the minor update that caused the issie.

**Comment by bagder** [comment]
Yes, but it is not the undef causing it...

**Comment by bagder** [comment]
Try #9561, I think it fixes the issue!

**Comment by georgthegreat** [comment]
Thanks, this worked.
