### ISSUE TITLE
Test 972 failure leads to test 973 failure

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#9563]
### I did this

Look at the Solaris autobuilds, like
https://curl.se/dev/log.cgi?id=20220921085805-1968482#prob9

### I expected the following

A green test 973. Instead, it failed because of extra output from test 972, which had previously failed.

### curl/libcurl version

https://github.com/curl/curl/commit/9eec75452c5bc616434dab28cdc7f46ff8263e1d (see autobuilds)

### operating system

Solaris 10

**Comment by bagder** [comment]
Curios, the `<precheck>` command outputs  `sh: jsonlint-php: not found` but does not return error, so curl continues anyway.

Then that leads to the noted follow-up problem...
