### ISSUE TITLE
HTTP/2 downloads slower with default flow control

### ISSUE THREAD

**Issue by panzhongxian** [curl/curl#9571]
Hi, @bagder @jay I have read the ISSUE #1102 and you have solve it by add calling `nghttp2_session_set_local_window_size` in lib/http2.c.

Recently, I used the libcurl library. I found I can't set the window size explicitly because the connection and other struct member are hidden to users.

Can you add a `curl_easy_setopt` option to support this? So that the window size can be set by user self.

Or is there any roundwork to set it?

Here is the window size changing, from 400k to zero again and again:

![CurlHttp2WindowSize](https://user-images.githubusercontent.com/11887422/191724149-c244780e-e59c-4b39-b7d6-a2132dfd1f2f.png)

**Comment by bagder** [comment]
Questions that come to mind:

1. why isn't the 32 MB default window enough?
2. how big did you have to set it to make it better?

**Comment by jay** [comment]
Ref: https://curl.se/mail/lib-2020-02/0051.html
Ref: https://github.com/curl/curl/issues/4939

**Comment by panzhongxian** [comment]
Thanks for your directory. It's helpful. @jay

**Comment by panzhongxian** [comment]
Hi @bagder Thanks for your reply.

The 32MB window is enough for me and I believe it's OK for most condition.

There two reasons user may ask for a setopt function for the window:

- User can hardly find out calling `curl_easy_pause()` can changethe window size unless we reached the refs supplied by jay. Although it's easy to find out `Curl_http2_switched` and `Curl_http2_stream_pause` will call `nghttp2_session_set_local_window_size` to change the window, I had no clue which public API will invoke these two functions.
- Generally I think a window size scaled with CURLMOPT_MAX_CONCURRENT_STREAMS or concurrent stream numbers may be better the a fixed value.

I believe it's more convinient if updating http2-download.c or adding a new example to use the `curl_easy_pause()` with commenting the default window size(like [4939.c](https://github.com/curl/curl/files/4231898/4939.c.txt)).

**Comment by bagder** [comment]
I'm sorry, I don't understand this at all. curl sets the window to 32MB by default, and unless you have transfers at very high speeds (and high latency) that ought to be enough.

You seem to say that there are situations where the window size is changed but maybe not restored correctly again, like when a paused connection is again unpaused. Is that the case?

The window size should really *not* be dependent on number of streams.

**Comment by panzhongxian** [comment]
Hi, @bagder . You said "curl sets the window to 32MB by default". Does that mean both the excutable curl and the API use the default window?

I used version `7.85.0` curl library and did a little change([http2-download.c.txt](https://github.com/curl/curl/files/9642431/http2-download.c.txt) replace the url with large pictures http2 website). The network capture is as following:

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/11887422/192178711-5c4ff7c2-7a2a-47f6-938c-9eed34ad20d6.png">

I have seen the 32MB window size. It's a 64Ki at first SYN and 400K at last ack in handshaking.

System info(`uname -a`):
> Darwin xxx-MB1 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

Now I just want to use the 32MB, could you give me some direction?

**Comment by bagder** [comment]
if it uses less than 32MB to begin with, that's a bug.

**Comment by bagder** [comment]
See:

https://github.com/curl/curl/blob/2481dbe5f4f581a3556b56cdc5a6d46be35e827d/lib/http2.c#L1218-L1219

**Comment by panzhongxian** [comment]
@bagder I confirmed that the code reached the code you mentioned and it also called `rv = nghttp2_session_set_local_window_size(httpc->h2, NGHTTP2_FLAG_NONE, 0, HTTP2_HUGE_WINDOW_SIZE);` but the window size is still small.

Do you think I should test the nghttp2 directly rather than test libcurl on my MacOS?

**Comment by panzhongxian** [comment]
I'm so sorry about that poor knowledge made me have HTTP/2 flow control confuded with TCP flow control(window size).
By changing some system config, I can change the TCP window size to perform more effectively.

Thanks for you patient replies. @bagder
