### ISSUE TITLE
CURLOPT_CERTINFO not working with HTTP/3 (either backend)

### ISSUE THREAD

**Issue by eloydegen** [curl/curl#9584]
Although I am using `pycurl` and not directly calling the `libcurl` API from C, I think this is the most appropriate place to report the bug. According to the documentation, only OpenSSL is supported. This uses the BoringSSL fork with the Quiche library for QUIC. I suspect that it could be a missing API in Quiche, but I'm not sure.

### I did this
```
import pycurl
from pprint import pprint

TEST_URL = 'https://facebook.com'

def certinfo_demo(url=TEST_URL):
    c = pycurl.Curl()
    c.setopt(pycurl.URL, url)
    c.setopt(pycurl.WRITEFUNCTION, lambda x: None)
    c.setopt(pycurl.VERBOSE, True)
    c.setopt(pycurl.OPT_CERTINFO, True)
    c.setopt(pycurl.HTTP_VERSION, c.CURL_HTTP_VERSION_3)
    c.perform()
    return c.getinfo(pycurl.INFO_CERTINFO)

if '__main__' == __name__:
    pprint(certinfo_demo())
```
### I expected the following
I expected it to print the certificate information. When the `    c.setopt(pycurl.HTTP_VERSION, c.CURL_HTTP_VERSION_3)` line is removed, it works fine. I was using a local test server but replace it with Facebook to make it reproducible. It prints an empty list when using HTTP/3.

### curl/libcurl version
PycURL/7.45.1 libcurl/7.86.0-DEV BoringSSL quiche/0.14.0

### operating system
Fedora Linux 36, in a Python venv

**Comment by bagder** [comment]
First double-check that the correct and same logic is done in libcurl for the QUIC case as it is for normal TLS when this option is set.

**Comment by bagder** [comment]
I built curl from git master right now using quiche from their master, using the [certinfo example](https://curl.se/libcurl/c/certinfo.html),  and it worked fine for me!

And I don't think this is due to any recent changes done in curl at least.

**Comment by bagder** [comment]
The reason for this problem is that no QUIC code calls the necessary `get_cert_chain()` function which is also static in lib/vtls/openssl.c...

**Comment by bagder** [comment]
This problem exists for all QUIC backends.
