### ISSUE TITLE
Uses wrong OpenSSL at run-time 

### ISSUE THREAD

**Issue by plicease** [curl/curl#9599]
### I did this

✅ doublethink% pkg-config --libs openssl
-L/home/ollisg/opt/perl/5.37.4/lib/site_perl/5.37.4/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib -lssl -lcrypto -ldl -pthread 
✅ doublethink% ./configure --with-openssl

[full log here](https://gist.github.com/plicease/91aca7b3518c81112dc20f9320649b30)

error:

```
  CCLD     curl
make[2]: Leaving directory '/home/ollisg/dev/Alien-curl/curl-7.85.0/src'
make[1]: Leaving directory '/home/ollisg/dev/Alien-curl/curl-7.85.0/src'
make[1]: Entering directory '/home/ollisg/dev/Alien-curl/curl-7.85.0'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/ollisg/dev/Alien-curl/curl-7.85.0'
✅ doublethink% ./src/curl --version
curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/not available zlib/1.2.11
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
```

key diagnostic:

https://gist.github.com/plicease/91aca7b3518c81112dc20f9320649b30#file-curl-uses-wrong-ssl-txt-L647

```
   LDFLAGS:         -L/usr/lib/x86_64-linux-gnu -L/home/ollisg/opt/perl/5.37.4/lib/site_perl/5.37.4/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib
```

### I expected the following

I expected curl to compile with the OpenSSL headers provided by `pkg-config` (which I believe it did), and link against the libraries provided by `pkg-config` (which it did not).  Because configure sets the system library directory before the OpenSSL library directory it is instead linking against the system OpenSSL.

I manually modified the Makefiles in the build root and in `src` to put the system library directory after OpenSSL, I was able to get it to work:

[full log here](https://gist.github.com/plicease/2ce541b04351dc4f1495efb6c02a68b8)

### curl/libcurl version

(when it did build)
```
✅ doublethink% ./src/curl -V
curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/not available zlib/1.2.11
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets
```

### operating system

```
✅ doublethink% uname -a
Linux doublethink 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
You mix build-time with run-time. Those options you show *are* used when curl is *built*.

When you then invoke curl, you need to make sure that the *run-time linker* also finds the correct lib then.

`man ld.so` is a good first guide

Some tricks you could use:

- edit `/etc/ld.so.conf` (and rerun `ldconfig`)
- set `LD_LIBRARY_PATH`
- pass `LDFLAGS="-Wl,-rpath,[directory]` to the build to "hard code" a particular path to load the library from

**Comment by plicease** [comment]
> You mix build-time with run-time. Those options you show _are_ used when curl is _built_.
> 
> When you then invoke curl, you need to make sure that the _run-time linker_ also finds the correct lib.
> 
> `man ld.so` is a good first guide
> 
> Some tricks you could use:
> 
>     * edit `/etc/ld.so.conf` (and rerun `ldconfig`)
> 
>     * set `LD_LIBRARY_PATH`
> 
>     * pass `LDFLAGS="-Wl,-rpath,[directory]` to the build to "hard code" a particular path to load the library from

I disagree with this.

OpenSSL was built _static_.  the run-time linker ... if I had even gotten to that point ... is irrelevant.  The error is clearly coming from `ld`, not the runtime linker.

**Comment by bagder** [comment]
If it was built with a static OpenSSL then it couldn't "pick the wrong one" at run-time. Then it was wrong at build-time.

**Comment by plicease** [comment]
Yes!  It was wrong at built time because it inserts `-L` for the system directory in front of the one provided by `pkg-config`.  Was kind of my point.

**Comment by plicease** [comment]
I just realized I made a cut-and-paste error in the original submission.  This is the error:

```
  CCLD     curl
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `EVP_PKEY_get_id'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_get1_peer_certificate'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_load_verify_dir'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_load_verify_file'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `EVP_PKEY_get_bn_param'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:991: curl] Error 1
make[2]: Leaving directory '/home/ollisg/dev/Alien-curl/curl-7.85.0/src'
make[1]: *** [Makefile:1478: all-recursive] Error 1
make[1]: Leaving directory '/home/ollisg/dev/Alien-curl/curl-7.85.0/src'
make: *** [Makefile:1240: all-recursive] Error 1
```

For some reason I posted the good outcome twice (where I reordered the linker flags by hand).  I've updated the original description.  The full logs are still there for both the linker error and the good outcome.

**Comment by bagder** [comment]
> -L for the system directory in front

If you investigate your `config.log` I think you'll learn that this `-L` is added there by another (bad) pkg-config rule. It is not done by curl's configure itself. I think I have seen it done by the libz one in the past.

**Comment by plicease** [comment]
> If you investigate your `config.log` I think you'll learn that this `-L` is added there by another (bad) pkg-config rule. It is not done by curl's configure itself. I think I have seen it done by the libz one in the past.

Thanks, this was useful!  zlib.pc was indeed providing the system lib directory for some reason.  Now I have a ticket to file somewhere else.
