### ISSUE TITLE
ftp DELE returns error 19 on successful deletion of file

### ISSUE THREAD

**Issue by loomy** [curl/curl#9602]
### I did this

output of request:
```
curl -vvv -u testuser:testpass -X 'DELE /home/testuser/ftp/backup-2022-09-27T07-43-50Z+0000.tar.gz' ftp://10.1.135.137/
< 220 (vsFTPd 3.0.3)
> USER testuser
< 331 Please specify the password.
> PASS testpass
< 230 Login successful.
> PWD
< 257 "/home/testuser" is the current directory
> EPSV
< 229 Entering Extended Passive Mode (|||47331|)
> TYPE A
< 200 Switching to ASCII mode.
> DELE /home/testuser/ftp/backup-2022-09-27T07-43-50Z+0000.tar.gz
< 250 Delete operation successful.
* RETR response: 250
curl: (19) RETR response: 250
```

### I expected the following

returning 0

### curl/libcurl version

# curl -V
curl 7.82.0 (x86_64-poky-linux-gnu) libcurl/7.82.0 OpenSSL/3.0.5 zlib/1.2.12 libssh2/1.10.0
Release-Date: 2022-03-05
Protocols: file ftp ftps http https scp sftp 
Features: alt-svc AsynchDNS Debug HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets

### operating system

Linux host 5.10.130-yocto-standard #1 SMP Thu Jul 14 18:49:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jzakrzewski** [comment]
I believe, you're using wrong command here. It should probably be something like that:
`curl -v -u testuser:testpass -Q 'DELE /home/testuser/ftp/backup-2022-09-27T07-43-50Z+0000.tar.gz' ftp://10.1.135.137/`

**Comment by loomy** [comment]
> I believe, you're using wrong command here. It should probably be something like that: `curl -v -u testuser:testpass -Q 'DELE /home/testuser/ftp/backup-2022-09-27T07-43-50Z+0000.tar.gz' ftp://10.1.135.137/`

thx. it returns 0 with -Q, but issues a LIST Command after deletion is there a way to avoid that?

```
# curl -vvv -u testuser:testpass -Q 'DELE /home/testuser/ftp/backup-2022-09-27T08-28-54Z+0000.tar.gz' ftp://10.1.135.137/
< 220 (vsFTPd 3.0.3)
> USER testuser
< 331 Please specify the password.
> PASS testpass
< 230 Login successful.
> PWD
< 257 "/home/testuser" is the current directory
> DELE /home/testuser/ftp/backup-2022-09-27T08-28-54Z+0000.tar.gz
< 250 Delete operation successful.
> EPSV
< 229 Entering Extended Passive Mode (|||35480|)
> TYPE A
< 200 Switching to ASCII mode.
> LIST
< 150 Here comes the directory listing.
drwxr-xr-x    2 1000     1000         4096 Aug 08 00:00 annikabk
drwxrwxr-x    2 1000     1000         4096 Jan 13  2020 bkups
-rw-rw-r--    1 1000     1000          264 Apr 22  2020 diskusage
drwxrwxr-x    2 1000     1000         4096 Sep 27 10:31 ftp
drwxrwxr-x    2 1000     1000         4096 Jan 09  2020 ftpalt
< 226 Directory send OK.
```

**Comment by bagder** [comment]
Note that curl only has one level of verbose, using multiple `-v` has no extra effect.

You can stop the "body" from getting transferred in the command line above by adding `-I`.
