### ISSUE TITLE
crash when execute curl_easy_perform

### ISSUE THREAD

**Issue by SunnySun852963** [curl/curl#9603]
### I did this
Use curl_easy_perform to upload json text or file
### I expected the following
curl_easy_perform is executed successfully.
### curl/libcurl version
7.66

### operating system
windows
### Crash stack
0e 000000b4`21bfea10 00007ffc`03404224     CrashRpt!Ordinal10+0x70fd
0f 000000b4`21bfeaf0 00007ffc`03405064     CrashRpt!Ordinal10+0x4224
10 000000b4`21bff150 00007ffc`2a7c8774     CrashRpt!Ordinal10+0x5064
11 000000b4`21bff1e0 00007ffc`2a7c86b0     ucrtbase!_invalid_parameter_internal+0xac
12 000000b4`21bff230 00007ffc`2a7c8679     ucrtbase!invalid_parameter+0x2c
13 000000b4`21bff2b0 00007ffc`2a7f76e6     ucrtbase!invalid_parameter_noinfo+0x9
14 000000b4`21bff2f0 00007ffc`2a7f2bbf     ucrtbase!_read_nolock+0x4ffa6
15 000000b4`21bff390 00007ffc`2a7a6fce     ucrtbase!_fread_nolock_s+0x4bbaf
16 000000b4`21bff400 00007ffc`2a7a6f58     ucrtbase!fread_s+0x5e
17 000000b4`21bff450 00007ffb`eaceac55     ucrtbase!fread+0x18
18 000000b4`21bff490 00007ffb`eaceb556     libcurl!mime_file_read+0x75 [curl\lib\mime.c @ 710] 
19 000000b4`21bff4c0 00007ffb`eaceb9f1     libcurl!read_part_content+0xd6 [curl\lib\mime.c @ 820] 
1a 000000b4`21bff500 00007ffb`eaceb115     libcurl!readback_part+0x391 [curl\lib\mime.c @ 961] 
1b 000000b4`21bff560 00007ffb`eaceb50a     libcurl!mime_subparts_read+0x175 [curl\lib\mime.c @ 1056] 
1c 000000b4`21bff5c0 00007ffb`eaceb9f1     libcurl!read_part_content+0x8a [curl\lib\mime.c @ 802] 
1d 000000b4`21bff600 00007ffb`eace9ec8     libcurl!readback_part+0x391 [curl\lib\mime.c @ 961] 
1e 000000b4`21bff660 00007ffb`ead076bf     libcurl!Curl_mime_read+0x38 [curl\lib\mime.c @ 1638] 
1f 000000b4`21bff690 00007ffb`ead09170     libcurl!Curl_fillreadbuffer+0x13f [curl\lib\transfer.c @ 247] 
20 000000b4`21bff720 00007ffb`ead08246     libcurl!readwrite_upload+0x120 [curl\lib\transfer.c @ 1059] 
21 000000b4`21bff7a0 00007ffb`eacf0e92     libcurl!Curl_readwrite+0x116 [curl\lib\transfer.c @ 1264] 
22 000000b4`21bff810 00007ffb`eacef570     libcurl!multi_runsingle+0xcd2 [curl\lib\multi.c @ 2147] 
23 000000b4`21bff920 00007ffb`eaccd473     libcurl!curl_multi_perform+0x80 [curl\lib\multi.c @ 2423] 
24 (Inline Function) --------`--------     libcurl!easy_transfer+0x3c [curl\lib\easy.c @ 593] 
25 000000b4`21bff9a0 00007ffb`8b1e40ce     libcurl!easy_perform+0x1b3 [curl\lib\easy.c @ 683] 
26 000000b4`21bff9f0 00007ffb`8b1e3443     RoomsHostMgr!curl_easy_perform+0x82e [C:\workspace\CommonCI-Rooms-Windows-Feature-Build-Auto-Generate\rcvrooms-windows\src\core\pal\platform\windows\src\network\multi_part_request_provider.cpp @ 229]  
### How many times did it happen？
Twice （I am not sure how many times it has been executed，but sure it is much more than twice）
It's not easy to reproduce

### Code Snippet
Note:  The following code is executed in its own thread.
```                               
                                auto curl = curl_easy_init();
                                 std::string fullUrl = req.host + req.path;
                                 curl_easy_setopt(curl, CURLOPT_URL, fullUrl.c_str());
                                 // head process
                                 struct curl_slist *listHeaders = nullptr;
                                 for (auto pair : req.header)
                                 {
                                     if (pair.first == "Accept-Encoding")
                                     {
                                         curl_easy_setopt(curl, CURLOPT_ACCEPT_ENCODING, pair.second.c_str());
                                         continue;
                                     }
                                     listHeaders = curl_slist_append(listHeaders, (pair.first + ":" + pair.second).c_str());
                                 }

                                 listHeaders = curl_slist_append(listHeaders, "Expect:");

                                 curl_easy_setopt(curl, CURLOPT_HTTPHEADER, listHeaders);
                                 curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);

                                 // data process
                                 std::string realData = req.data;

                                 auto fiels = _parseMultiPartField(realData);
                                 curl_mime *multipart = curl_mime_init(curl);
                                 for (auto item : fiels)
                                 {
                                     curl_mimepart *part = curl_mime_addpart(multipart);
                                     curl_mime_name(part, item->name.c_str());
                                     if (item->type == "file")
                                     {
                                         curl_mime_filedata(part, item->value.c_str());
                                     }
                                     else if (item->type == "jsonData")
                                     {
                                         curl_mime_type(part, "application/json;charset=UTF-8");
                                         curl_mime_data(part, item->value.c_str(), CURL_ZERO_TERMINATED);
                                     }
                                 }

                                 curl_easy_setopt(curl, CURLOPT_MIMEPOST, multipart);
                                 // curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

                                 // response process
                                 std::string response_body;
                                 curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, NetworkCommon::writeFunction);
                                 curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_body);

                                 std::string response_headers;
                                 curl_easy_setopt(curl, CURLOPT_HEADERDATA, &response_headers);
                                 curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, &NetworkCommon::header_callback);

                                 auto retCode = curl_easy_perform(curl);

                                 _handleResponse(req, curl, response_headers, response_body, callback);

                                 // clean up
                                 curl_easy_cleanup(curl);
                                 curl_mime_free(multipart);
                                 curl_slist_free_all(listHeaders);
```

**Comment by bagder** [comment]
I would urge you to try a newer version first. We've done some 24 releases since your version, and chances are your problem has already been fixed.

If that that doesn't fix the problem, then please work harder on coming up with a recipe to reproduce this because otherwise it will be hard for anyone to act on this.
