### ISSUE TITLE
CURLOPT_ACCEPT_ENCODING man page:

### ISSUE THREAD

**Issue by ProceduralMan** [curl/curl#9614]
"Four encodings are supported: identity, meaning non-compressed, deflate which requests the server to compress its response using the zlib algorithm, gzip which requests the gzip algorithm, (since curl 7.57.0) br which is brotli and (since curl 7.72.0) zstd which is zstd"

'identity', 'deflate', 'gzip', 'br' and 'zstd'... hmmm, I count five ;-)

**Comment by bagder** [comment]
Counting is hard! :grin:
