### ISSUE TITLE
Unconditional free(ufds) in curl_multi_wait()

### ISSUE THREAD

**Issue by judaykiran** [curl/curl#965]
I see an unconditional free(ufds) in curl_multi_wait() function
~~~
CURLMcode curl_multi_wait(struct Curl_multi *multi,
                          struct curl_waitfd extra_fds[],
                          unsigned int extra_nfds,
                          int timeout_ms,
                          int *ret)
{
...
  if(nfds || extra_nfds) {
    ufds = malloc(nfds * sizeof(struct pollfd)); >>> WE ALLOCATE CONDITONALLY
    if(!ufds)
      return CURLM_OUT_OF_MEMORY;
  }
...
  free(ufds); >>> FREEING UNCONDITIONALLY
...
}
~~~
If we pass no file descriptors (libcurl handles) then there could be
invalid free.

**Comment by jay** [comment]
No that's fine because ufds is initially defined NULL and the C standard says free(NULL) no action occurs.

**Comment by judaykiran** [comment]
Yes...Still did not look right and can avoid extra free call...We could just add a check on fd's.

**Comment by jay** [comment]
Thank you for the suggestion but unconditional free is acceptable in these cases.
