### ISSUE TITLE
HTTP2 not being used on php curl

### ISSUE THREAD

**Issue by kohdesmond** [curl/curl#969]
### I did this
I'm trying to use php curl to post an APNS through HTTP/2 on Windows.

### I expected the following
the Post to be successful. However i got this:
curl response = �@@�HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f332f6465766963652f666562663939646433 

from error.log, * ALPN, server did not agree to a protocol

### curl/libcurl version

curl_version()["version"]: curl version = 7.49.1
apache_get_version: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.9
OpenSSL version text: OpenSSL 1.0.2h 3 May 2016
MSVC14 (Visual C++ 2015)
PHP Version 7.0.9

[curl -V output perhaps?]
Output from PHP
 curl version = Array
(
    [version_number] => 471297
    [age] => 3
    [features] => 266141
    [ssl_version_number] => 0
    [version] => 7.49.1
    [host] => i386-pc-win32
    [ssl_version] => OpenSSL/1.0.2h
    [libz_version] => 1.2.8
    [protocols] => Array
        (
            [0] => dict
            [1] => file
            [2] => ftp
            [3] => ftps
            [4] => gopher
            [5] => http
            [6] => https
            [7] => imap
            [8] => imaps
            [9] => ldap
            [10] => pop3
            [11] => pop3s
            [12] => rtsp
            [13] => scp
            [14] => sftp
            [15] => smtp
            [16] => smtps
            [17] => telnet
            [18] => tftp
        )
)

### operating system
Windows NT RHO1 6.1 build 7601 (Windows Server 2008 R2 Enterprise Edition Service Pack 1) i586

thanks for reading and wonder what i did wrong or missed out.

**Comment by jay** [comment]
Features 266141 is
CURL_VERSION_IPV6
CURL_VERSION_SSL
CURL_VERSION_LIBZ
CURL_VERSION_NTLM
CURL_VERSION_ASYNCHDNS
CURL_VERSION_SPNEGO
CURL_VERSION_LARGEFILE
CURL_VERSION_IDN
CURL_VERSION_SSPI
CURL_VERSION_KERBEROS5

There's no CURL_VERSION_HTTP2 flag so that means libcurl was not built with HTTP2 support. Also see
https://curl.haxx.se/mail/curlphp-2016-04/0000.html
http://stackoverflow.com/questions/34606801/how-do-i-send-a-http-2-post-request-in-php

> HTTP/2 client preface string missing or corrupt.

That is a message from api.push.apple.com because afaict it requires HTTP/2

**Comment by kohdesmond** [comment]
Hi @jay thanks for the reply!

I'm using the the curl from PHP7, how can i build libcurl to enable support HTTP2 on windows?

Regards

Desmond

**Comment by jay** [comment]
[HTTP/2 with curl](https://curl.haxx.se/docs/http2.html)
libcurl needs nghttp2. Use configure option `--with-nghttp2`. I would ask whoever made your php w/libcurl build for windows to consider supporting it. You can download a libcurl built with http2, see [the download page](https://curl.haxx.se/download.html#Win32) Darren Owen and Viktor Szakáts both build with nghttp2.

@bagder maybe worthwhile to add an HTTP2 column to the download page?

**Comment by kohdesmond** [comment]
@jay thanks for the speedy reply!

I downloaded PHP 7 from the official site http://windows.php.net/download/

I'm using Windows server and on http://php.net/manual/en/curl.installation.php

the web said:
Note: Note to Win32 Users
In order to enable this module on a Windows environment, libeay32.dll and ssleay32.dll must be present in your PATH. You don't need libcurl.dll from the cURL site.

all i did on php was to enable **php_curl.dll** in php.ini
