### ISSUE TITLE
CURLOPT_PROXY_SSL_VERIFYHOST man page:

### ISSUE THREAD

**Issue by ProceduralMan** [curl/curl#9695]
Hi!

Description for the options when value is 1 include versions previous to the versión the option was added

I guess it should read something like this:

If verify value is set to 1:

From 7.52.0 to 7.65.3: setting it to 1 made curl_easy_setopt() return an error and leaving the flag untouched.

From 7.66.0: treats 1 and 2 the same. 

Cheers!

**Comment by bagder** [comment]
Sorry, but I don't understand. Does it not already say this (and a little more)?
