### ISSUE TITLE
Cirrus CI FreeBSD 13.1 job failing pubkey pinning tests

### ISSUE THREAD

**Issue by jay** [curl/curl#9696]
### I did this

Since eada2900 landed on October 5 these tests have been failing in the FreeBSD 13.1 job:

~~~
TESTFAIL: These test cases failed: 2034 2037 2041 
~~~

https://github.com/curl/curl/runs/8731979873

### What I see so far

The failures are the same. Initially the https test server cannot be created on random port 24682 because it's already in use. (Because of the way the random seed is somewhat constricted based on curl version and year/month hash this is true of all the failures since which use the same "random" port.) However runtests [tries up to 10x](https://github.com/curl/curl/blob/curl-7_85_0/tests/runtests.pl#L1728) and so it seems on the second iteration it eventually does start with a port, but then it cannot actually forward the connection to the HTTP server which, as far as I can tell is running normally.

~~~
=== Start of file http_verify.log
 * STATE: INIT => CONNECT handle 0x8014e8808; line 1880 (connection #-5000)
 * Added connection 0. The cache now contains 1 members
 * family0 == v4, family1 == v6
 *   Trying 127.0.0.1:16541...
 * STATE: CONNECT => CONNECTING handle 0x8014e8808; line 1941 (connection #0)
 * Connected to 127.0.0.1 (127.0.0.1) port 16541 (#0)
...
~~~

~~~
=== Start of file https_stunnel.log
 2022.10.10 14:00:00 LOG5[ui]: stunnel 5.65 on amd64-portbld-freebsd13.1 platform
 2022.10.10 14:00:00 LOG5[ui]: Compiled/running with OpenSSL 1.1.1o-freebsd  3 May 2022
 2022.10.10 14:00:00 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
 2022.10.10 14:00:00 LOG5[ui]: Reading configuration from file /tmp/cirrus-ci-build/tests/https_stunnel.conf
 2022.10.10 14:00:00 LOG5[ui]: UTF-8 byte order mark not detected
 2022.10.10 14:00:00 LOG4[ui]: Insecure file permissions on /tmp/cirrus-ci-build/tests/certs/Server-localhost-sv.pem
 2022.10.10 14:00:00 LOG5[ui]: Configuration successful
 2022.10.10 14:00:01 LOG5[0]: Service [curltest] accepted connection from 127.0.0.1:16543
 2022.10.10 14:00:01 LOG3[0]: s_connect: connect ::1:16541: Connection refused (61)
 2022.10.10 14:00:01 LOG3[0]: s_connect: connect 127.0.0.1:16541: Connection refused (61)
...
~~~

https://cirrus-ci.com/task/5234155444240384?logs=test#L2935

Notably only the pubkey pinning tests that are supposed to be successful (sans Schannel, which for our purposes does not matter here) are failing, because those are the tests where the transfer must receive an http response. I guess it's always these 3 tests repeatedly because the randomness is predictable in a sense.

**Comment by bagder** [comment]
They do not fail like this consistently (any more?). Example from a [recent commit](https://github.com/curl/curl/runs/9721766307).
