### ISSUE TITLE
SChannel certificate chain order reversed in Windows 11 22H2

### ISSUE THREAD

**Issue by nmoinvaz** [curl/curl#9706]
### I did this

```c
curl_easy_getinfo(curl_handle, CURLINFO_CERTINFO, &cert_info)
```

### I expected the following

The ordering of the certificate chain should be consistent across different versions of Windows and different platforms.

### Problem details

This problem report follows in the foot steps of:

* https://github.com/curl/curl/pull/4519
* https://github.com/curl/curl/issues/4518
* Commit: https://github.com/curl/curl/pull/4519/commits/55a143c8d3800b6634ff0dc0afa284ebf736ec60
* Mailing list mention: https://curl.se/mail/lib-2018-10/0099.html

Older versions of Chromium that used SChannel for TLS/SSL implementation reported:

```c
  // In testing, enumerating the store returned from SChannel appears to
  // enumerate certificates in reverse of the order they were added, meaning
  // that issuer certificates appear before the subject certificates. This is
  // likely because the default Windows memory store is implemented as a
  // linked-list. Reverse the list, so that intermediates are ordered from
  // subject to issuer.
  // Note that the store also includes the end-entity (server) certificate,
  // so exclude this certificate from the set of |intermediates|.
```

https://github.com/youtube/h5vcc/blob/7da685fe633dac18fd8db35624f7bade8619c977/external/chromium/net/socket/ssl_client_socket_win.cc#L1559

Chromium now uses BoringSSL, but you can see there was a problem with the way that SChannel returned certificate chains.

In Windows 11 22H2 it appears that the incorrect ordering of certificates has been corrected and that subject certificates are now correctly appearing before issuer certificates. So reversing the ordering of certificates in the chain in curl is no longer necessary according to how newer versions of Windows are behaving.

I have also filed the issue on Microsoft Feedback Hub to get clarification, but I am not hopeful. I want to bring awareness about the issue and hopefully we can get a solution for `CURLINFO_CERTINFO` when using SChannel that works consistently in all versions of Windows.

### curl/libcurl version

7.84

### operating system

Windows 11 22H2 OS Build 22621.674

**Comment by jay** [comment]
> I have also filed the issue on Microsoft Feedback Hub to get clarification

Is there a public link to this issue?

**Comment by bagder** [comment]
Do we need to add a run-time version-check (for Windows 11 22H2?) to figure out what order to use?

**Comment by nmoinvaz** [comment]
> Is there a public link to this issue?

It requires Feedback Hub app: https://aka.ms/AAic9qq

**Comment by nmoinvaz** [comment]
I have also filed a Microsoft Q&A here: https://learn.microsoft.com/en-us/answers/questions/1044186/schannel-certificate-ordering-in-windows-11-22h2-u.html.

**Comment by nmoinvaz** [comment]
> Do we need to add a run-time version-check (for Windows 11 22H2?) to figure out what order to use?

If it turns out to be the case, I think so.

**Comment by jay** [comment]
> https://aka.ms/AAic9qq

Feedback Hub says "Your account does not have access to this feedback." Can you tell us what is happening with it?

**Comment by nmoinvaz** [comment]
There has been no reply. Maybe somebody else has Microsoft contacts.

**Comment by nmoinvaz** [comment]
I was using Windows 11 since the beginning and only started seeing it with the 22H2 update.

**Comment by shanselman** [comment]
checking

**Comment by nmoinvaz** [comment]
I posted on the developer community forums and it just got ignored.
https://developercommunity.visualstudio.com/t/Schannel-certificates-returned-in-revers/10184194

**Comment by nmoinvaz** [comment]
Tested against 22621.755 and the problem persists. I thought it might be fixed since the change log states:
> It addresses an issue that affects certificate mapping. When it fails, lsass.exe might stop working in schannel.dll.

**Comment by nmoinvaz** [comment]
@shanselman were you able to get anywhere with the check? Thanks in advance.

**Comment by nmoinvaz** [comment]
According to https://github.com/MicrosoftDocs/win32/pull/1384, there is no guarantee that the certificate store returned by Microsoft will have the certificates in any relationship ordering, even though TLS may have its own ordering/relationship guarantees. However, curl in https://github.com/curl/curl/issues/4518 tries to confer a particular order.

It sounds like Microsoft's position is that the certificates returned can be in any particular random order, however in practice we have not found that they are random. Instead, prior to Windows 11 22H2 they are in order from issuer to subject and after 22H2, they are in order from subject (leaf) to issuer (root). And subject to issuer ordering is what TLS guarantees itself.

It may be possible to build the chain using `CertGetCertificateChain`, however that might be an expensive operation. Or it might also be possible to detect the order using `CertGetIssuerCertificateFromStore` in curl's certificate traversal function to see if the first certificate is the issuer certificate. However, it might be better to go with I have in my PR.

**Comment by jay** [comment]
> It sounds like Microsoft's position is that the certificates returned can be in any particular random order, however in practice we have not found that they are random. Instead, prior to Windows 11 22H2 they are in order from issuer to subject and after 22H2, they are in order from subject (leaf) to issuer (root). And subject to issuer ordering is what TLS guarantees itself.

How about QueryContextAttributes [SECPKG_ATTR_REMOTE_CERT_CONTEXT](https://learn.microsoft.com/en-us/windows/win32/secauthn/querycontextattributes--schannel#SECPKG_ATTR_REMOTE_CERT_CONTEXT) to get the server certificate, determine if that comes first or last, and use that to infer the order?

**Comment by nmoinvaz** [comment]
Curl already calls `QueryContextAttributes` with `SECPKG_ATTR_REMOTE_CERT_CONTEXT`, and then enumerates the certificates in the cert context buffer. The problem is that the chain ordering isn't consistent across versions of Windows.

**Comment by jay** [comment]
It's supposed to contain the "end certificate" and we already rely on that elsewhere as the server certificate. See [Curl_verify_certificate](https://github.com/curl/curl/blob/curl-7_87_0/lib/vtls/schannel_verify.c#L566) in schannel_verify and I recently proposed a PR #10056 which adds independent alt name verification using the same method. Are you saying it is incorrect to assume the end certificate is the server certificate?

**Comment by nmoinvaz** [comment]
> It's supposed to contain the "end certificate" and we already rely on that elsewhere as the server certificate.

I think that the "end certificate/server certificate" (according to the MS docs) actually is a chain of certificates. You can use `CertEnumCertificatesInStore` to enumerate all the certificates in a `CERT_CONTEXT`. For your PR, it is likely that `CertGetNameString` enumerates all the certificates in the chain looking for the subject alternative name extension (at least that is what it looks like from ReactOS code). When it finds whatever certificate in the `CERT_CONTEXT` certificate store that contains the extension then it returns that value.

This issue is primarily related to PR #4518 which no longer works on newer versions of Windows 11. If the purpose of that PR was to guarantee a particular ordering of the certificates returned from curl then it fails. If curl no longer makes this guarantee, then perhaps it is best to remove the odd code that is PR #4518 and just let Windows return it, in whatever order.

**Comment by bitcrazed** [comment]
Looping in @DHowett here as he owns Windows' version of Curl.

**Comment by DHowett** [comment]
I'm sorry, I only own the ingestion of the tool build of _curl.exe_ into Windows. I don't have any specific insight into how the `CURLINFO_CERTINFO` curleasy option should work, and I have not been able to find anybody with local SChannel expertise. :smile:

**Comment by nmoinvaz** [comment]
I had been discussing this with @alvinashcraft in https://github.com/MicrosoftDocs/win32/pull/1384#issuecomment-1370420956 and the response he got from his contacts at Microsoft was posted to Q&A [here](https://learn.microsoft.com/en-us/answers/questions/1044186/schannel-certificate-ordering-in-windows-11-22h2-u.html). But it is essentially, as I had mentioned in my previous comment above.

> there is no guarantee that the certificate store returned by Microsoft will have the certificates in any relationship ordering...

So it remains only a curl problem: what is the expected behavior from curl and how we can achieve it.

**Comment by nmoinvaz** [comment]
@bagder do you support reverting #4518?

**Comment by bagder** [comment]
I suppose, although it shouldn't matter then because the order is to be considered as random to users. :disappointed:

**Comment by nmoinvaz** [comment]
You are right in that respect. It would remove a few lines of code and an extra variable in `Adder_args` that was used to ensure a particular order.

**Comment by jay** [comment]
Though Windows may not guarantee a specific order it sounds like in practice it will order one of two ways, ascending and descending.

**Comment by bagder** [comment]
As the order is not known nor guaranteed, this is not a bug.

**Comment by nmoinvaz** [comment]
Should the commit made that tries to guarantee an order for curl be reverted?

**Comment by nmoinvaz** [comment]
Ok I will open a PR to revert that change. It should simplify the code a bit.
