### ISSUE TITLE
avoid hard-dependency on pkg-config in configure.ac

### ISSUE THREAD

**Issue by bagder** [curl/curl#972]
As [pointed out](https://github.com/curl/curl/commit/c2f9b78afe15bfb9e0fa89bbb93e7b4aafd9d7b4#commitcomment-18709942) by @mback2k, the commit c2f9b78afe15bf added a hard dependency on pkg-config.

Most people will manage without using that so we should make sure the configure script can be built without pkg-config.

@mback2k can you check if the patch below fixes the case for you?

~~~diff
diff --git a/configure.ac b/configure.ac
index 3c00ae1..5e76930 100644
--- a/configure.ac
+++ b/configure.ac
@@ -890,17 +890,20 @@ else
   if test "$OPT_ZLIB" = "yes" ; then
     OPT_ZLIB=""
   fi
 
   if test -z "$OPT_ZLIB" ; then
-    PKG_CHECK_MODULES([ZLIB], [zlib],
+
+    m4_ifdef([PKG_CHECK_MODULES], [
+      PKG_CHECK_MODULES([ZLIB], [zlib],
         [ LIBS="${ZLIB_LIBS} $LIBS"
           CPPFLAGS="${ZLIB_CFLAGS} $CPPFLAGS"
           HAVE_LIBZ="1"
         ],
         [
         ])
+    ])
 
     if test -z "$HAVE_LIBZ"; then
 
       dnl Check for the lib without setting any new path, since many
       dnl people have it in the default path

**Comment by mback2k** [comment]
@bagder Thanks for the patch. It does indeed fix the problem for me. (I added pkg-config to my build environment in the meantime, but removed it to reproduce this issue and verify the patch.)

**Comment by bagder** [comment]
Thanks for confirming, @mback2k!

**Comment by nickzman** [comment]
Hmm, it didn't fix the problem for me.

Commit c2f9b78 broke the buildconf script for me, even though I have the pkg-config tool installed in /usr/local/bin. After upgrading to the latest HEAD, commit 7ad50a6, I'm still getting the following error:

> % ./buildconf
> buildconf: autoconf version 2.69 (ok)
> buildconf: autom4te version 2.69 (ok)
> buildconf: autoheader version 2.69 (ok)
> buildconf: automake version 1.13.4 (ok)
> buildconf: aclocal version 1.13.4 (ok)
> buildconf: libtoolize version 2.4.2 (ok)
> buildconf: GNU m4 version 1.4.6 (ok)
> buildconf: running libtoolize
> glibtoolize: putting auxiliary files in `.'.
> glibtoolize: copying file `./ltmain.sh'
> glibtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
> glibtoolize: copying file `m4/libtool.m4'
> glibtoolize: copying file `m4/ltoptions.m4'
> glibtoolize: copying file `m4/ltsugar.m4'
> glibtoolize: copying file `m4/ltversion.m4'
> glibtoolize: copying file `m4/lt~obsolete.m4'
> glibtoolize: Remember to add `LT_INIT' to configure.ac.
> buildconf: converting all mv to mv -f in local m4/libtool.m4
> buildconf: running aclocal
> buildconf: converting all mv to mv -f in local aclocal.m4
> buildconf: running autoheader
> buildconf: running autoconf
> configure.ac:1456: error: possibly undefined macro: PKG_CONFIG_LIBDIR
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> buildconf: autoconf command failed

Maybe I need to re-install pkg-config...? Any suggestions on how I debug this...?

**Comment by bagder** [comment]
Okay, so what something like this patch. It removes the use of PKG_* macros and instead uses pkg-config to find zlib, the same way we do elsewhere in the script already:

~~~diff
From a03e9f0f1c29de651eff1e02698b1352c9b0d80e Mon Sep 17 00:00:00 2001
From: Daniel Stenberg <daniel@haxx.se>
Date: Wed, 24 Aug 2016 13:49:53 +0200
Subject: [PATCH] configure: detect zlib with our pkg-config macros

... instead of relying on the pkg-config autoconf macros to be present.
---
 configure.ac | 20 ++++++++++----------
 1 file changed, 10 insertions(+), 10 deletions(-)

diff --git a/configure.ac b/configure.ac
index 5e76930..083e18c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -889,21 +889,21 @@ if test "$OPT_ZLIB" = "no" ; then
 else
   if test "$OPT_ZLIB" = "yes" ; then
     OPT_ZLIB=""
   fi
 
-  if test -z "$OPT_ZLIB" ; then
+  CURL_CHECK_PKGCONFIG(zlib)
 
-    m4_ifdef([PKG_CHECK_MODULES], [
-      PKG_CHECK_MODULES([ZLIB], [zlib],
-        [ LIBS="${ZLIB_LIBS} $LIBS"
-          CPPFLAGS="${ZLIB_CFLAGS} $CPPFLAGS"
-          HAVE_LIBZ="1"
-        ],
-        [
-        ])
-    ])
+  if test "$PKGCONFIG" != "no" ; then
+    LIBS="`$PKGCONFIG --libs-only-l zlib` $LIBS"
+    LDFLAGS="`$PKGCONFIG --libs-only-L zlib` $LDFLAGS"
+    CPPFLAGS="`$PKGCONFIG --cflags-only-I zlib` $CPPFLAGS"
+    OPT_ZLIB=""
+    HAVE_LIBZ="1"
+  fi
+
+  if test -z "$OPT_ZLIB" ; then
 
     if test -z "$HAVE_LIBZ"; then
 
       dnl Check for the lib without setting any new path, since many
       dnl people have it in the default path
-- 
2.9.3

**Comment by nickzman** [comment]
That change fixed the buildconf script for me. Thanks!
