### ISSUE TITLE
How to compile curl? No rule to make target 'curl_ctype.c', needed by 'libcurl_la-curl_ctype.lo'

### ISSUE THREAD

**Issue by markg85** [curl/curl#9720]
Hi,

I'm quite sure this is a user error. My error.
But just to be sure, reporting it here.

I can compile curl just fine but with **cmake**! I can't compile curl with configure/make.
What i'm trying to do is configure curl exactly how Archlinux is doing it in their [PKGBUILD file](https://github.com/archlinux/svntogit-packages/blob/packages/curl/trunk/PKGBUILD).

So what i'm doing:
```
git clone <curl>
cd curl
mkdir build
cd build
../configure \
  --disable-ldap \
  --disable-ldaps \
  --disable-manual \
  --enable-ipv6 \
  --enable-threaded-resolver \
  --with-gssapi \
  --with-libssh2 \
  --with-openssl \
  --with-random='/dev/urandom' \
  --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt'
```
Next is `make` which outputs this:
```
Making all in lib
make[1]: Entering directory '/home/mark/GitProjects/curl/build/lib'
make  all-am
make[2]: Entering directory '/home/mark/GitProjects/curl/build/lib'
  CC       libcurl_la-altsvc.lo
  CC       libcurl_la-amigaos.lo
  CC       libcurl_la-asyn-ares.lo
  CC       libcurl_la-asyn-thread.lo
  CC       libcurl_la-base64.lo
  CC       libcurl_la-bufref.lo
  CC       libcurl_la-c-hyper.lo
  CC       libcurl_la-conncache.lo
  CC       libcurl_la-connect.lo
  CC       libcurl_la-content_encoding.lo
  CC       libcurl_la-cookie.lo
  CC       libcurl_la-curl_addrinfo.lo
make[2]: *** No rule to make target 'curl_ctype.c', needed by 'libcurl_la-curl_ctype.lo'.  Stop.
make[2]: Leaving directory '/home/mark/GitProjects/curl/build/lib'
make[1]: *** [Makefile:1345: all] Error 2
make[1]: Leaving directory '/home/mark/GitProjects/curl/build/lib'
make: *** [Makefile:1221: all-recursive] Error 1
```
I'm quite sure i'm missing something somewhere because the Arch build system can build curl locally just fine. Usually i can just mimic the configure in PKGBUILD and that makes it work just fine. For curl this doesn't seem to be the case and i just keep getting that **No rule to make target 'curl_ctype.c', needed by 'libcurl_la-curl_ctype.lo'**.

Any idea what i'm doing wrong here?

Sidenote: I've been building curl from the very begin with cmake, which works just fine.

**Comment by markg85** [comment]
To answer myself.
`autoreconf -fi` in the source folder fixed it for me.

I don't get why or how. Arch isn't doing that. But this is the solution that made the build work for me.
Feel free to close. Just leaving it open as i'm very curious to hear other peoples thoughts on this.

**Comment by bagder** [comment]
> make[2]: *** No rule to make target 'curl_ctype.c', needed by 'libcurl_la-curl_ctype.lo'.  Stop.

This happened because you built curl already before and then you've refreshed to a newer git repo where `lib/curl_ctype.c` has been removed. Nothing strange.

**Comment by markg85** [comment]
Interesting! I did think my build repo was clean.
While my builds mostly are clean ("shadow" builds in a different folder), the main repo is a bit contaminated with old files from months ago. That's probably the cause. Thanx for the hint! :)

I'll close this one.
