### ISSUE TITLE
--xattr stores the final, instead of the original URL in user.xdg.origin.url

### ISSUE THREAD

**Issue by vszakats** [curl/curl#9766]
### I did this

```
$ curl -LO --xattr https://github.com/curl/curl/releases/download/curl-7_85_0/curl-7.85.0.tar.xz
$ xattr -l curl-7.85.0.tar.xz
user.xdg.origin.url: https://objects.githubusercontent.com/github-production-release-asset-2e65be/
569041/ce852[...]a60?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AK[...]%2F20221018
%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221018T[...]Z&X-Amz-Expires=300
&X-Amz-Signature=[...]&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=569041
&response-content-disposition=attachment%3B%20filename%3Dcurl-7.85.0.tar.xz
&response-content-type=application%2Foctet-stream
```

### I expected the following

```
user.xdg.origin.url: https://github.com/curl/curl/releases/download/curl-7_85_0/curl-7.85.0.tar.xz
```

I expected the original (unglobbed) URL be stored in `user.xdg.origin.url` when the request triggered redirects.

### curl/libcurl version

curl 7.85.0

Original comment with a workaround (with unwanted side-effects): https://github.com/curl/curl/pull/9757#issuecomment-1282199798

**Comment by jay** [comment]
Freedesktop [says](https://www.freedesktop.org/wiki/CommonExtendedAttributes/):

- user.xdg.origin.url: Set on a file downloaded from a url. _Its value should equal the url it was downloaded from._

I think that's a little ambiguous. I also think the original makes more sense.
