### ISSUE TITLE
Bugs in all curl_set_opt calls with enum arguments as values.

### ISSUE THREAD

**Issue by sergio-nsk** [curl/curl#9779]
### I did this

Let's consider the example with [CURLOPT_SSLVERSION](https://curl.se/libcurl/c/CURLOPT_SSLVERSION.html).

#### The function synopsis
```c
CURLcode curl_easy_setopt(CURL *curl, CURLoption option, ...);
```
#### The call semantics
```c
CURLcode curl_easy_setopt(CURL *handle, CURLOPT_SSLVERSION, long version);
```
#### [Example](https://curl.se/libcurl/c/CURLOPT_SSLVERSION.html)
```c
curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
```
#### Reading the value (shortened)
```c
  case CURLOPT_SSLVERSION:
      arg = va_arg(param, long);
```
The issue on all 64 bit OSes except Windows: the enum value `CURL_SSLVERSION_TLSv1` promoted to `int` (32 bit) is used for the call to the variable arg function, the value is read as `long` (64 bit), a possible buffer over-read vulnerability.

### I expected the following

enum values are passed as long values.

### curl/libcurl version

libcurl 7.84.0

### operating system

Ubuntu 22.04.1, macOS 12.4

**Comment by bagder** [comment]
The documentation for this option says:

> Pass a long as parameter to control...

A **long**.

**Comment by sergio-nsk** [comment]
> The documentation for this option says:
> 
> > Pass a long as parameter to control...
> 
> A **long**.

Right. And the manual example passes `int`.
