### ISSUE TITLE
[VISUAL STUDIO] WARNING__NULL_IMPORT_DESCRIPTOR

### ISSUE THREAD

**Issue by clshack** [curl/curl#979]
### I did this
I compiled the static version of curl using vc 2015 in multi thread mode. 
I linked the static lib as addition dependencies to another static lib.
I use the final static library that include mine code and curl with the google test framework. 
### I expected the following
No warning.
### curl/libcurl version
7.50.1
### operating system
Windows 10 with SDK 10

All works fine but I have these warnings:
```
1>libcurl_a.lib(WLDAP32.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR already defined in libcurl_a.lib(ADVAPI32.dll); second definition ignored
1>libcurl_a.lib(WS2_32.dll) : warning LNK4006: __NULL_IMPORT_DESCRIPTOR already defined in libcurl_a.lib(ADVAPI32.dll); second definition ignored
```

**Comment by bagder** [comment]
[Visual Studio, Linker Tools Warning LNK4006](https://msdn.microsoft.com/en-us/library/1zzf962b.aspx) says:

> You can get this warning if you try to merge two import libs into one.

It also offers a few solutions. I don't see how this is a curl issue.
