### ISSUE TITLE
Build fails with `./configure --enable-shared --disable-static` on Windows

### ISSUE THREAD

**Issue by lazka** [curl/curl#9803]
This issue is a continuation from https://github.com/curl/curl/pull/9521#issuecomment-1291864501

### I did this

```bash
# using gcc/clang + mingw-w64
autoreconf -vfi
./configure --enable-shared --disable-static --with-schannel
make -j
```

```bash
libtool: compile:  windres -I../include -DCURL_EMBED_MANIFEST -i curl.rc  -DDLL_EXPORT -DPIC -o .libs/curl.o
  CCLD     curl.exe
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find curl.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

git bisect -> 6de7322c03d5b4d915

```bash
$ git bisect good
6de7322c03d5b4d91576a7d9fc893e03cc9d1057 is the first bad commit
commit 6de7322c03d5b4d91576a7d9fc893e03cc9d1057
Author: Viktor Szakats
Date:   Sun Sep 18 12:05:35 2022 +0000
```

### I expected the following

it to build

### curl/libcurl version

7.86.0

### operating system

Windows 11

**Comment by lazka** [comment]
> @lazka: Thanks! A separate Issue would be helpful indeed. `--enable-shared --disable-static` is the exact combination where in curl-for-win I explicitly _skip_ building `curl.exe` (due to fatal `ltwrapper` issues post-link, and we also happen to not need this binary). This explains why this escaped my local tests. We also miss it from CI tests apparently. I could reproduce it now.
> 
> Do you have any suggestion for a fix?

Do you mean for the `ltwrapper` issue (context?) or the windres issue? Likely for neither though. I could try porting our package recipe to cmake :D

**Comment by vszakats** [comment]
[ Deleted `--with-schannel` from title, it's not necessary for it to fail. Also added Windows. ]

**Comment by lazka** [comment]
I've reverted those two commits now downstream, so there is need no hurry.

I don't understand the libtool/autotools magic, but as a lead:  removing `$(LIBTOOL) --tag=RC --mode=compile ` makes it work. libtool writes it into `./.libs/curl.o` while the link command expects it at `./curl.o` somehow.

**Comment by vszakats** [comment]
Yeah, that might work, but as luck has it, building libcurl _does_ seem to require the translation "magic":
```
2022-10-26T10:13:20.5922663Z libtool: compile:  windres -I../include -i libcurl.rc  -o .libs/libcurl.o
```

Having to use `libtool` in `lib` and bare `RC` in `src`, looks... kind of strange. I'll make some tests later.

In the meantime, everyone is welcome for suggestions on what is the autotools-way of solving this.

**Comment by vszakats** [comment]
Odd as it is, using `windres` directly in `src` seems to fix it, while also not breaking static `curl.exe` builds.

`autotools`-ways are really mysterious, so I'm not 100% confident this doesn't break some other scenario, but till we have a better idea about this, I suggest going with this one.

PR: #9805
