### ISSUE TITLE
MacOS build linking with OpenSSL yields - symbol not found in flat namespace '_CFRelease'

### ISSUE THREAD

**Issue by treahard** [curl/curl#9806]
### I did this
Built MacOS fat binary with the following settings:

  CMAKE_ARGS
    -D BUILD_SHARED_LIBS=OFF
    -D CURL_USE_OPENSSL=ON
    -D OPENSSL_ROOT_DIR=${CMAKE_BINARY_DIR}/openssl
    -D OPENSSL_USE_STATIC_LIBS=ON
    -D BUILD_CURL_EXE=OFF
    -D HTTP_ONLY=ON
    -D ZLIB_USE_STATIC_LIBS=ON
    -D ZLIB_ROOT=${CMAKE_BINARY_DIR}/zlib

### I did not expect the following

symbol not found in flat namespace '_CFRelease'
hostip.c contains the following which does not link to any Mac system library

      CFDictionaryRef dict = SCDynamicStoreCopyProxies(NULL);
      if(dict)
        CFRelease(dict);

All other occurrences of CFRelease are in sectransp.c which are ifdef'd out with "#ifdef USE_SECTRANSP" as it is not defined because we are linking OpenSSL

Removing CFRelease in hostip.c causes SCDynamicStoreCopyProxies to generate the same symbol not found error.

### curl/libcurl version
7.85.0

### operating system

Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

##

**Comment by bagder** [comment]
Not seen this before and we and others build for mac quite often.

Can you figure out if it is one of the cmake flags you use that triggers this?

**Comment by treahard** [comment]
Glad to hear you build for mac quite often!  We build for win32, win64 with VS2010, VS2013, VS 2022, MacOS, and Linux x64, and Linux arm - cmake handling it all.  I saw all the deprecation messages on mac for the Secure Transport and decided to link against OpenSSL as we had previously.  That is how I came across this.  I will check the cmake flags as you suggest.

**Comment by abitmore** [comment]
The code block is about IPv6 support but not that related to OpenSSL.

`SCDynamicStoreCopyProxies` requires the System Configuration framework, and `CFRelease` requires the Core Foundation framework. The error means these two frameworks aren't being linked correctly. Looks like CMake didn't find that you're building for Mac.

**Comment by treahard** [comment]
When I linked the Core Foundation with the static version of libcurl I was building, linking worked as you suggested.  Thank you for the pointer.
