### ISSUE TITLE
A memory-leak bug

### ISSUE THREAD

**Issue by ycaibb** [curl/curl#9809]
Hi, it seems that the file at Line 116 is not close, when Line 138 is executed

https://github.com/curl/curl/blob/5b059ba8954c6dcf305ff4def77fe394c7b57401/src/tool_parsecfg.c#L115-L139

**Comment by jay** [comment]
file is closed after the while block that is ended by the break statement
https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/src/tool_parsecfg.c#L277-L278
