### ISSUE TITLE
CMakeFile produces VS2015 Projects with Link Errors

### ISSUE THREAD

**Issue by SparhawkSoftware** [curl/curl#981]
Ran cmake to create VS0125 projects with
-DHTTP_ONLY:BOOL=ON -DBUILD_CURL_EXE:BOOL=OFF
msbuild /p:Configuration=Debug CURL.sln

I expected it to work but a bunch of test programs failed with linker errors.

The cmake options don't make a difference. 
Same problem with no options.

I reverted to 7_48_0 and everything was fine.

**Comment by bagder** [comment]
Can you please show us some of those errors too?

**Comment by SparhawkSoftware** [comment]
```
build\tests\unit\unit1603.vcxproj" (default target) (135) ->
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_init referenced in function _unit_setup [\src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_add referenced in function _test [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_delete referenced in function _test [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_pick referenced in function _test [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_destroy referenced in function _unit_stop [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_clean referenced in function _test [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_hash_str referenced in function _test [src\curl\build\tests\unit\unit1603.vcxproj]
  unit1603.obj : error LNK2019: unresolved external symbol _Curl_str_key_compare referenced in function _unit_setup [src\curl\build\tests\unit\unit1603.vcxproj]
  src\curl\build\tests\unit\Debug\unit1603.exe : fatal error LNK1120: 8 unresolved externals [src\curl\build\tests\unit\unit1603.vcxproj]

    1 Warning(s)
    38 Error(s)
```

**Comment by bagder** [comment]
Ok, yes the unit tests can only build with debug versions of libcurl since it requires that a bunch of otherwise hidden symbols are available - to get tested. As they're not part of the regular API, they're not reachable in a normal build.

I suppose the cmake build files need to skip building the unit tests unless that condition is met. That's what the autoconf based build does.

**Comment by bagder** [comment]
I should add that all the 16xx tests (that are in tests/unit) are such unit tests.

**Comment by SparhawkSoftware** [comment]
A cmake option to disable all tests would be nice,
When you use cmake to build for Visual Studio you end up with a single solution and you cannot pick and choose which projects build to without using the GUI (which is not good for automated builds).

**Comment by jay** [comment]
-DBUILD_TESTING=OFF 

I tried building the tests just now, I also ran into problems.

**Comment by bagder** [comment]
Right, the cmake build should only try to build the unit tests when asked to build debug builds as otherwise it fails like this...

**Comment by snikulov** [comment]
@bagder @SparhawkSoftware @jay In fact Curl_hash_init symbols will be available if ```-DCURL_STATICLIB=ON```

@SparhawkSoftware So if you want to fix build use ```-DBUILD_TESTING=OFF``` or enable static linking with ```-DCURL_STATICLIB=ON```

**Comment by bagder** [comment]
It is probably still a good idea to have the build script check if the unit tests *can* get built before doing that, to avoid this build error.

**Comment by snikulov** [comment]
@bagder Linux exports all symbols by default. So all Curl_hash is in ```libcurl.so``` library.
So here you should decide if same for Windows and Curl_hash... should use dllexport or not.

**Comment by bagder** [comment]
Aha! but that's a bug - it should hide symbols by default and what's what it does in the autoconf build! That's why the "regular" build can't be used for the unit test. Also, some unit tests use symbols that are otherwise marked **static** and I'm not sure they're always made available even if symbols aren't hidden.

**Comment by SparhawkSoftware** [comment]
Confirmed that -DBUILD_TESTING=OFF fixes my issue.

**Comment by bagder** [comment]
The build should simply not build the unit tests if it can't link them...

**Comment by snikulov** [comment]
@SparhawkSoftware According to [documentation](https://cmake.org/cmake/help/v3.1/module/CTest.html) this option already there and ON by default.

@bagder So what's the decision? Are ```Curl_hash_``` functions optional? From which build option it depends?

**Comment by bagder** [comment]
@snikulov They're not "optional". They're internal functions that are tested with unit tests. Those functions are not public and will never be, they're not part of any official API. All functions in libcurl that start with an uppercase 'C' are like that. They're also subject to change at any time, but then we of course also need to update the tests.

**Comment by SparhawkSoftware** [comment]
@snikulov the option statement with a comment makes it clearer.

@bagder the issue comes from the way cmake works with VisualStudio because cmake adds all projects to the solution and msbuild always builds all projects in the solution. It is not possible to remove the test projects without manually editing the outputs of cmake which defeat the purpose of using cmake.

**Comment by bagder** [comment]
I'm just saying that when cmake is invoked, it can determine if the unit tests can get built or not and only if they *can* it should attempt that.

**Comment by SparhawkSoftware** [comment]
The fix does not works:
if (NOT CURL_HIDDEN_SYMBOLS)
	include(CTest)
	if(BUILD_TESTING)
		add_subdirectory(tests)
	endif()
endif()

**Comment by verybigbadboy** [comment]
Hey guys, source tarbals from download page does not provide cmakemodules required for this feature.
cmake fails because of "include(CurlSymbolHiding)" and missing module in cmake dir.
download page url:
https://curl.haxx.se/download.html
thank you in advance :)

**Comment by pedro-vicente** [comment]
I have a similar problem, in Windows.
It's not in the curl build itself, but on a library (netcdf) that uses curl. When using

`-DCURL_STATICLIB=ON`

, the windows sockets library is missing from the curl library , so you get linking errors

`libcurl-d.lib(select.obj) : error LNK2019: unresolved external symbol __imp__select@20 referenced in function _Curl_socket_check`

one way to fix this is to manually edit the generated libcurl.vcxproj and add 


```
<Lib>
      <AdditionalOptions>%(AdditionalOptions) /machine:X86 /machine:X86</AdditionalOptions>
      <AdditionalDependencies>ws2_32.lib</AdditionalDependencies>
    </Lib>

```

but this should be fixed in some way on the curl Cmake script

to reproduce the bug, do

```
https://github.com/pedro-vicente/nco_bld
cd nco_bld
clone.bat
bld.bat
```

this clones and builds curl and netcdf
