### ISSUE TITLE
URL Globbing and name variable

### ISSUE THREAD

**Issue by svpace** [curl/curl#9819]
### I did this
`curl -O "http://example.com/{v1,v2}/my-file-#1"`

### I expected the following

Download files:
- http://example.com/v1/my-file-v1
- http://example.com/v2/my-file-v2

### curl/libcurl version

curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### operating system

Linux zero 5.10.148-1-MANJARO #1 SMP PREEMPT Sat Oct 15 13:41:09 UTC 2022 x86_64 GNU/Linux

**Comment by bagder** [comment]
This is simply not how the globbing works. The "variables" specified as `#[num]` cannot be used within the URL itself. They can be used in the `-o` argument fine.

This way *could* be made supported if someone put in the work.

**Comment by svpace** [comment]
Is there a way to achieve this? Having the same value in multiple parts of
the url seems like a common enough situation

Em sex., 28 de out. de 2022 03:19, Daniel Stenberg ***@***.***>
escreveu:

**Comment by bagder** [comment]
The only way is by adding the support.

**Comment by svpace** [comment]
Ok, could we convert this issue in a feature request?

Em sex., 28 de out. de 2022 13:14, Daniel Stenberg ***@***.***>
escreveu:

**Comment by bagder** [comment]
We use this tracker for bugs and issues only, we put ideas to work on in the future in the TODO document. We basically drown in good ideas so they don't do much use in our tracker. If you really want to see this happen, start working on an implementation and submit a PR for it or join the mailing list and talk up more interest for it and see what help from others you can get!

**Comment by svpace** [comment]
Sounds good to me. Thanks

Em sex., 28 de out. de 2022 13:20, Daniel Stenberg ***@***.***>
escreveu:
