### ISSUE TITLE
New behaviour of -O option (stripping query) breaks existing user scripts

### ISSUE THREAD

**Issue by martinwhitaker** [curl/curl#9826]
### I did this

`curl -O 'http://mirrors.mageia.org/api/mageia.9.i586.list?reason=upgrade'`

### I expected the following

The transferred data to be stored in a file named `mageia.9.i586.list?reason=upgrade`.

### curl/libcurl version

curl 7.86.0 (i586-mageia-linux-gnu) libcurl/7.86.0 OpenSSL/3.0.5 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.10.4/gnutls/zlib nghttp2/1.50.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets

### operating system

Linux localhost 6.0.6-desktop-1.mga9 #1 SMP PREEMPT_DYNAMIC Sat Oct 29 10:40:13 UTC 2022 i686 GNU/Linux

**Comment by bagder** [comment]
Every bugfix is a behavior change, but this is one we want to stick with and it has not caused a lot of blow back.
