### ISSUE TITLE
Support OpenSSL 1.1.0 lib names in Windows non-configure builds

### ISSUE THREAD

**Issue by jay** [curl/curl#984]
### I did this

winbuild, projects and probably others link to ssleay32.lib and libeay32.lib for OpenSSL. Since the release of OpenSSL 1.1.0 they have changed the library names to libssl.lib and libcrypto.lib.
### I expected the following

Even though these build systems aren't dynamically generated I think we will need a way to determine what libs to link to, since any lib that is not found causes an error. I started a [thread](https://mta.openssl.org/pipermail/openssl-dev/2016-August/008340.html) in openssl-dev about this, but I expect I'll be told to just use the new names.

Related https://curl.haxx.se/mail/lib-2016-08/0104.html cc @rodwiddowson

**Comment by gvanem** [comment]
BTW if using BoringSSL (as a drop-in replacement for OpenSSL), some of it's functions have been moved to `decrepit.lib`. AFAICS they are `BIO_set_ssl()` and `BIO_f_ssl()`. Which complicates building on Windows even more.

**Comment by Mellnik** [comment]
Please add support for OpenSSL 1.1.0 Series
