### ISSUE TITLE
Results in two build warnings (promoted to errors in CI) with old MSVC envs:

### ISSUE THREAD

**Issue by 1234567808** [curl/curl#9877]
Results in two build warnings (promoted to errors in CI) with old MSVC envs:
- Microsoft Visual Studio 9.0 (2008), `_MSC_VER == 1500`:
  ```
  2>.\hostip.c(156) : warning C4090: 'function' : different 'const' qualifiers
  2>.\hostip.c(163) : warning C4090: 'function' : different 'const' qualifiers
  ```
  https://ci.appveyor.com/project/curlorg/curl/builds/45022310/job/kjjcasgg0f0bi7ke#L346

- Microsoft Visual Studio 10.0 (2010), `_MSC_VER == 1600`:
  ```
  [C:\projects\curl\lib\libcurl.vcxproj]
  hostip.c(156): warning C4090: 'function' : different 'const' qualifiers [C:\projects\curl\lib\libcurl.vcxproj]
  hostip.c(163): warning C4090: 'function' : different 'const' qualifiers [C:\projects\curl\lib\libcurl.vcxproj]
  ```
  https://ci.appveyor.com/project/curlorg/curl/builds/45022310/job/hp87c4479og4m36v#L283

_Originally posted by @vszakats in https://github.com/curl/curl/issues/9689#issuecomment-1273846683_

**Comment by jay** [comment]
Didn't @vszakats fix this a month ago to use libcurl's ntop?

**Comment by vszakats** [comment]
This was detected by our CI and the patch certainly fixed that.

@1234567808 What is your compiler version and the curl version/revision you're compiling?

**Comment by vszakats** [comment]
This issue seems like it has been created accidentally. If this wasn't the case, please reopen with the necessary details.
