### ISSUE TITLE
Wrong "Everything curl - the book"

### ISSUE THREAD

**Issue by u20221022** [curl/curl#9881]
### I did this
1) GoTo "https://github.com/bagder/everything-curl/blob/master/usingcurl/copyas.md" or "https://everything.curl.dev/usingcurl/copyas". Read carefully. Start "Google Chrome", press Ctrl+Shift+i and select "Network".
2) GoTo "https://curl.se/windows/" and start download "https://curl.se/windows/dl-7.86.0_1/curl-7.86.0_1-win64-mingw.zip".
3) Call the context menu at UNIQUE link and select "Copy --> Copy as cURL (cmd)".
Paste to "Cmd.exe" window. Got a lot of mistakes (including "Warning: Binary output can mess up your terminal.") BEFORE press "Enter".
4) Paste to "NotePad.exe" window, remove line breaks with "^", add option "-o", REpaste to "Cmd.exe" window and retry. This is result (BackSlashes are not displayed here):
curl -o "test.exe" "https://curl.se/windows/dl-7.86.0_1/curl-7.86.0_1-win64-mingw.zip"   -H "authority: curl.se"   -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"   -H "accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"   -H "referer: https://curl.se/windows/"   -H "sec-ch-ua: ^\^"Google Chrome^\^";v=^\^"107^\^", ^\^"Chromium^\^";v=^\^"107^\^", ^\^"Not=A?Brand^\^";v=^\^"24^\^""   -H "sec-ch-ua-mobile: ?0"   -H "sec-ch-ua-platform: ^\^"Windows^\^""   -H "sec-fetch-dest: document"   -H "sec-fetch-mode: navigate"   -H "sec-fetch-site: same-origin"   -H "sec-fetch-user: ?1"   -H "upgrade-insecure-requests: 1"   -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"   --compressed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 10.0M    2  271k    0     0  86586      0  0:02:02  0:00:03  0:01:59 86763^C
5) Repeat all actions IN THE SAME WAY with site "https://github.com/balena-io/etcher/releases/" and link "https://github.com/balena-io/etcher/releases/download/v1.9.0/balenaEtcher-Setup-1.9.0.exe", but use LAST link from two (i.e. redirected: "https://objects.githubusercontent.com/github-production-release-asset-2e65be/45055693/134a116d-a627-481c-9f0f-a90647f624b6?X-Amz-Algorithm=AWS4-HMAC-SHA256&…").  Got many-many errors (described in https://github.com/curl/curl/issues/9880).
### I expected the following
All files are handled the same way.
### curl/libcurl version
[curl -V output]
curl 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.7 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0
Release-Date: 2022-10-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli gsasl HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL SSPI threadsafe TLS-SRP UnixSockets zstd
### operating system
Microsoft "Windows 10" (last version with all updates).

**Comment by jay** [comment]
Again, this is not a curl bug it is a bug in Chromium that generates an incorrect command line. I have proposed amending that section in the everything curl book to link to the Chromium bug, refer to bagder/everything-curl#263.
