### ISSUE TITLE
OS400 sh makefile.sh > makelog 2>&1 fails.

### ISSUE THREAD

**Issue by johnsherrill** [curl/curl#9896]
File CHANGES has line(s) that are longer that 240 bytes. It can not be copied to ${TARGETLIB]/DOCS, makefile.sh ends with these lines in makelog:
CPC7305:  Member CHANGES added to file DOCS in CURLIBMI1.
CPDA037:  Could not write to member CHANGES in file DOCS in library CURLIBMI1.
CPC7309:  Member CHANGES removed from file DOCS in CURLIBMI1.
CPFA0D4:  File system error occurred.  Error number 3003.

Editing the file to remove the long line(s) allows it to work.

**Comment by bagder** [comment]
Who knew a system could refuse to copy a file if it has too long lines!

The `CHANGES` file in the release tarball is generated by [log2changes.pl](https://github.com/curl/curl/blob/master/scripts/log2changes.pl)

**Comment by johnsherrill** [comment]
Another option is since all the documentation is available in the curl directory and easily accessible there, there is really no reason to copy the documentation to a physical file (IBMi term for a non-stream-file). So just eliminate the copy.
