### ISSUE TITLE
Misleading flag in generated `configure` script

### ISSUE THREAD

**Issue by torrefatto** [curl/curl#9909]
### I did this

Using shell completion and looking into the `configure` script generated by `autoreconf`, I would have expected to be able to disable `gsasl` using the flag `--without-gsasl`. This failed to be acknowledge by the script.

### I expected the following

To be able to disable `GSASL`. The flag that is acknowledged is `--without-libgsasl`, instead.

### curl/libcurl version

`master`

### operating system

`Linux ada 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux` (irrelevant)

**Comment by vszakats** [comment]
The project distributed its gsasl and libgsasl packages separately, of which the latter was used by curl. This summer there was an update where libgsasl has been made part of gsasl. So now you download gsasl, and build against libgsasl which is included in it. For practical purposes the names are interchangable. It'd be nice to make it consistent, but it would introduce too much breakage.
