### ISSUE TITLE
Package/OS400 sh makefile.sh > makelog 2>&1 fails with CZS0601:  Module OS400 is not created because statement errors occurred.

### ISSUE THREAD

**Issue by johnsherrill** [curl/curl#9910]
The root of the problem turns out to be "cat".  A temp source file is created using this code in initscript.sh
echo "#line 1 \"${2}\"" > __tmpsrcf.c
echo "#pragma convert(819)" >> __tmpsrcf.c
echo "#line 1" >> __tmpsrcf.c
cat "${2}" >> __tmpsrcf.c         

a search for "cat" finds more that one "cat" utility.  
Now that open source code is much more available on IBMi it is possible that a users default PATH statement may be this:
PATH=/QOpenSys/pkgs/bin:/usr/bin:.:/QOpenSys/usr/bin.  The cat utility found in /QOpenSys/pkgs/bin does not handle EBCDIC and ASCII. The cat which is found in /usr/bin works perfectly.

So I suggest that line 214 in initscript.sh be this
- cat "${2}" >> __tempsrcf.c
+ /usr/bin/cat "${2}" >> __tempsrcf.c

**Comment by johnsherrill** [comment]
fix should be 
Remove -> cat "${2}" >> __tempsrcf.c
Add       -> /usr/bin/cat "${2}" >> __tempsrcf.c

**Comment by bagder** [comment]
If you replace your system cat with a broken one, then I think *that* is the problem and not the script that assumes cat to work as it always has.

**Comment by johnsherrill** [comment]
Okay point taken.
