### ISSUE TITLE
Payload is corrupted with rustls tls backend

### ISSUE THREAD

**Issue by fchandur** [curl/curl#9920]
### I did this
```
./curl --url https://requestbin.io/xzr0ahxz --cacert cacert.pem --trace-time --trace "curl-debug-https-requestbin.txt" -o "curl-res-requestbin" -d "file=OMDULCYGYWAM... HAXAF"
```
full command: 
[testcurl-requestbin-command.txt](https://github.com/curl/curl/files/10014521/testcurl-requestbin-command.txt)

### I expected the following
Payload to be correctly uploaded to the server.

### problem details
- Issue should be reproducible for payloads exceeding 64K.
- Upon inspection, data uploaded to the server is not the same as data provided in the request:
https://requestbin.io/xzr0ahxz?inspect
- Trace file:
[curl-debug-https-requestbin.txt](https://github.com/curl/curl/files/10014356/curl-debug-https-requestbin.txt)
- cacert file: https://curl.se/ca/cacert.pem

### curl/libcurl version
```
$ ./curl --version
curl 7.86.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.86.0-DEV rustls-ffi/0.9.1/rustls/0.20.4 zlib/1.2.11 libssh2/1.9.0
```
### operating system

```
$ uname -a
Linux loan21523lxlap 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bagder** [comment]
Just to be clear: the "payload" you talk about being corrupted is the data you send in this transfer, right?

**Comment by fchandur** [comment]
> Just to be clear: the "payload" you talk about being corrupted is the data you send in this transfer, right?

Yes.  The data being sent ("payload") is not what the server receives.

**Comment by jsha** [comment]
Thanks for the report! I'll take a look.

**Comment by bagder** [comment]
I tried to write up a curl test to reproduce this, but I failed. This is what I did:

[test446.gz](https://github.com/curl/curl/files/10018926/test446.gz)

(uncompress in tests/data, then `./runtests.pl 446` in the tests dir should work)

**Comment by fchandur** [comment]
#### notes
- Issue was reproducible when using randomized series of characters, but not with repeated sequence.
- Issue was easy to reproduce over slower 4G connection (Speed ~133k):
   ```
  $ ./curl --url https://requestbin.io/xzr0ahxz --cacert cacert.pem --trace-time --trace "curl-debug-https-requestbin.txt" -o "curl-res-requestbin" -d "file=OMDULCYGYWAM... HAXAF" 
  %      Total       %    Received    %       Xferd    AverageDload    SpeedUpload    CurrentSpeed
   100    66568      100       3      100      66565         12            133k             133k
   ```
   but not over faster connection (Speed ~280k):
   ```
   $ ./curl --url https://requestbin.io/xzr0ahxz --cacert cacert.pem --trace-time --trace "curl-debug-https-requestbin.txt" -o "curl-res-requestbin" -d "file=OMDULCYGYWAM... HAXAF" 
  %      Total       %    Received    %       Xferd    AverageDload    SpeedUpload    CurrentSpeed
   100    66568      100       3      100      66565         12            279k             280k
   ```
- I should clarify ''corrupt": right number of bytes were being sent but they were wrong bytes.

The test failed ([log.zip](https://github.com/curl/curl/files/10026108/log.zip)), but perhaps for another reason:
```
$ ./runtests.pl  446
********* System characteristics ******** 
* curl 7.86.0-DEV (x86_64-pc-linux-gnu) 
* libcurl/7.86.0-DEV rustls-ffi/0.9.1/rustls/0.20.4
* Features: alt-svc AsynchDNS HSTS IPv6 Largefile SSL threadsafe UnixSockets
* Disabled: 
* Host: lxlap
* System: Linux loan21523lxlap 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* OS: linux
* Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6 
* Env: 
* Seed: 245871
***************************************** 
Warning: test446 not present in tests/data/Makefile.inc
test 0446...[HTTPS POST 80KB]

 446: protocol FAILED:
--- log/check-expected	2022-11-16 16:07:58.689462921 -0600
+++ log/check-generated	2022-11-16 16:07:58.689462921 -0600
@@ -1,8 +1,8 @@
-POST /446 HTTP/1.1[LF]
-Host: 127.0.0.1:24635[LF]
-User-Agent: curl/7.86.0-DEV[LF]
-Accept: */*[LF]
-Content-Length: 80005[LF]
-Content-Type: application/x-www-form-urlencoded[LF]
-[LF]
+POST /446 HTTP/1.1[CR][LF]
+Host: 127.0.0.1:24635[CR][LF]
+User-Agent: curl/7.86.0-DEV[CR][LF]
+Accept: */*[CR][LF]
+Content-Length: 80005[CR][LF]
+Content-Type: application/x-www-form-urlencoded[CR][LF]
+[CR][LF]
 data=ireallyhopethisworks...
 - abort tests
TESTDONE: 1 tests were considered during 2 seconds.
TESTDONE: 0 tests out of 1 reported OK: 0%

TESTFAIL: These test cases failed: 446

```

**Comment by bagder** [comment]
Those particular header differences show there as a result of test 446, is probably only because some line endings did not survive through properly in the test file and are probably not really indicators of any problems.

**Comment by fchandur** [comment]
I've not been able to reproduce this issue with localhost.

**Comment by jsha** [comment]
I tried reproducing this live against `requestbin.io`, but it appears to be down at the moment (I get a Heroku "Application Error").

I tried reproducing against http://httpbin.org/post instead, and the reflected value I get back in the JSON response (`form.file`) does match the commandline parameter, so so far I can't reproduce.

If you replace `https://requestbin.io/xzr0ahxz` with `http://httpbin.org/post` in your example command, can you still reproduce?

**Comment by bagder** [comment]
@fchandur ?

**Comment by bagder** [comment]
No response.
