### ISSUE TITLE
Curl should resolve HTTP proxy name before using DoH

### ISSUE THREAD

**Issue by colemar** [curl/curl#9926]
### I did this
```
curl -v -x http://user:pass@myproxy.local:8080 https://9.9.9.9/
*   Trying 11.22.33.44:8080...
* Connected to myproxy.local (11.22.33.44) port 8080 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to 9.9.9.9:443
* Proxy auth using Basic with user 'user'
> CONNECT 9.9.9.9:443 HTTP/1.1
> Host: 9.9.9.9:443
> Proxy-Authorization: Basic youwish=
> User-Agent: curl/7.83.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.0 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed
* schannel: disabled automatic use of client certificate
* schannel: using IP address, SNI is not supported by OS.
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
> GET / HTTP/1.1
> Host: 9.9.9.9
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 File Not Found
< Date: Wed, 16 Nov 2022 13:31:43 GMT
< Connection: keep-alive
< Content-Length: 9
< Server: h2o/dnsdist
< content-type: text/plain; charset=utf-8
```
^^^This demonstrates that 9.9.9.9:443 is reachable via local proxy.

```
curl -v -x http://user:pass@myproxy.local:8080 --doh-url https://9.9.9.9/dns-query https://clbin.com/
*   Trying 9.9.9.9:443...
* Found bundle for host: 0x2142183d0a0 [serially]
* Hostname 9.9.9.9 was found in DNS cache
*   Trying 9.9.9.9:443...
* connect to 9.9.9.9 port 443 failed: Timed out
* Failed to connect to 9.9.9.9 port 443 after 21065 ms: Timed out
* Closing connection 1
* a DoH request is completed, 1 to go
* DoH request Timeout was reached
* connect to 9.9.9.9 port 443 failed: Timed out
* Failed to connect to 9.9.9.9 port 443 after 21066 ms: Timed out
* Closing connection 2
* a DoH request is completed, 0 to go
* DoH request Timeout was reached
* DoH: Too small type A for myproxy.local
* DoH: Too small type AAAA for myproxy.local
* Closing connection 0
curl: (6) Couldn't resolve host name
```

(myproxy.local IP address is 11.22.33.44)

```
curl -v -x http://user:pass@11.22.33.44:8080 --doh-url https://9.9.9.9/dns-query https://clbin.com/
*   Trying 1.22.33.44:8080...
* Connected to 11.22.33.44 (11.22.33.44) port 8080 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to clbin.com:443
* Proxy auth using Basic with user 'user'
> CONNECT clbin.com:443 HTTP/1.1
> Host: clbin.com:443
> Proxy-Authorization: Basic youwish=
> User-Agent: curl/7.83.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.0 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET / HTTP/1.1
> Host: clbin.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-type: text/html; charset=UTF-8
< Accept-Ranges: bytes
< Content-Length: 1354
< Date: Wed, 16 Nov 2022 14:02:34 GMT
< Server: httpd 1.3
<
<!DOCTYPE html><head><title>clbin: command line pastebin.</title><meta name="description" content="Command Line Pastebin - Use curl, wget, python, php, and other command line tools to store text and images online. Post, paste, upload, share, terminal output."><meta name="keywords" content="Pastebin,paste,bash,curl,wget,upload,text,images,cli,code,share,php,python"><style>a{text-decoration:none}</style></head>
<body>
<pre>
clbin(1)                          CLBIN                          clbin(1)

NAME
    clbin: command line pastebin:
...
```

### I expected the following
Curl should make a plain vanilla dns request to resolve proxy name, then it should attempt to contact the remote host (via proxy).

### curl/libcurl version
curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
Release-Date: 2022-05-13
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets

### operating system
Windows 10 (ver 10.0.19044.2006)

**Comment by bagder** [comment]
I don't think that's what using DoH implies. If you want to use a HTTP proxy that cannot be resolved with DoH, then why use DoH at all for this?

**Comment by colemar** [comment]
When behind a proxy you have no choice but using the proxy.
Before using the proxy curl must resolve its name to know its ip address. It cannot resolve it via DoH because:
1. To contact the DoH server it must use the proxy (catch 22).
2. Anyway, the proxy is usually a local host which name is only registered in the local DNS.

I believe it makes sense to use DoH even if the first dns request is made via plain local DNS. After all, it is a local nameserver.

**Comment by colemar** [comment]
Well, I realize now that http proxy and DoH are kind of mutually exclusive: if you specify a proxy the standard behaviour of curl should be to delegate name resolution to the proxy (i.e. send command `CONNECT clbin.com:443` rather than `CONNECT 142.54.160.171:443`), therefore ignore the DoH server. And in the last example above it does exactly that.
Then, why does it try to contact the DoH server (second-last example) when the proxy is specified by name?

**Comment by bagder** [comment]
>  Then, why does it try to contact the DoH server (second-last example) when the proxy is specified by name?

To resolve the proxy name.

**Comment by colemar** [comment]
> > Then, why does it try to contact the DoH server (second-last example) when the proxy is specified by name?
> 
> To resolve the proxy name.

Yes, makes sense.
But DoH is more useful when the nameserver is public, and it is unlikely that a proxy (usually local) is resolvable via a public nameserver.

**Comment by bagder** [comment]
> DoH is more useful when the nameserver is public

I think you are letting your own use case color your view on this. DoH is just a mechanism for resolving names. You are resolving a name and you ask curl to use DoH for this.

Introducing a method for curl in which it would deliberately *not* use DoH for name resolving even if you tell it to, would require something new.

> a (usually local) proxy is unlikely to be resolvable through a public nameserver.

curl does not know if that proxy is "local" or not. You tell curl to use a proxy and it uses it. There are many users who use non-local proxies with curl. If you specify the proxy with a name, curl needs to resolve that name in order to connect to it. If you then ask curl to use DoH to resolve names, it uses DoH.

**Comment by colemar** [comment]
I agree.
