### ISSUE TITLE
curl: (35) error:0A00010B:SSL routines::wrong version number

### ISSUE THREAD

**Issue by Karthikdasari0423** [curl/curl#9931]
~~~
*   Trying 127.0.0.1:8443...
* Connect socket 5 over QUIC to 127.0.0.1:8443
* Skipped certificate verification
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN: offers http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:0A00010B:SSL routines::wrong version number
* Connection #0 to host 127.0.0.1 left intact
curl: (35) error:0A00010B:SSL routines::wrong version number
~~~
### I did this

curl -k -v --http3 https://127.0.0.1:8443/

### I expected the following

~~~
*   Trying 127.0.0.1:8443...
* Connect socket 5 over QUIC to 127.0.0.1:8443
* Skipped certificate verification
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: 127.0.0.1:8443]
* h2h3 [user-agent: curl/7.86.1-DEV]
* h2h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55e3ba63bf40)
> GET / HTTP/3
> Host: 127.0.0.1:8443
> user-agent: curl/7.86.1-DEV
> accept: */*
>
* ngh3_stream_recv returns 0 bytes and EAGAIN
< HTTP/3 200
< server: nginx/1.23.2
< date: Thu, 17 Nov 2022 06:40:56 GMT
< content-type: text/html
< content-length: 612
< last-modified: Tue, 21 Apr 2020 14:09:01 GMT
< etag: "5e9efe7d-264"
< alt-svc: h3=":8443"; ma=86400
< accept-ranges: bytes
<
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
~~~
### curl/libcurl version
curl 7.87.0-DEV (x86_64-pc-linux-gnu) libcurl/7.87.0-DEV OpenSSL/3.0.0 zlib/1.2.11 ngtcp2/0.12.0-DEV nghttp3/0.8.0-DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

[curl -V output]

~~~
*   Trying 127.0.0.1:8443...
* Connect socket 5 over QUIC to 127.0.0.1:8443
* Skipped certificate verification
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN: offers http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:0A00010B:SSL routines::wrong version number
* Connection #0 to host 127.0.0.1 left intact
curl: (35) error:0A00010B:SSL routines::wrong version number
~~~

### operating system
Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-131-generic x86_64)

**Comment by bagder** [comment]
This output is confusing. Are you saying it works sometimes and sometimes not?

**Comment by Karthikdasari0423** [comment]
Hi @bagder 

Thank you for replying back.

i have 2 linux ubuntu machines and installed curl on both. 

on one ubuntu machine(curl working ) i have installed curl on 11 November by using steps provided by you.
on this machine curl is working fine

on another ubuntu machine also (curl not working) i have installed curl on 17 November by using same steps but on this machine i am getting error.

i was just wondering is this issue related to ssl routine function or openssl issue

**Comment by bagder** [comment]
Does the problem reproduce if you try a public URL we too can access? Like `https://curl.se` for example?

**Comment by Karthikdasari0423** [comment]
root@ubuntu:~# curl -v -k --http3 https://curl.se/
*   Trying [2a04:4e42:800::347]:443...
* Connect socket 5 over QUIC to 2a04:4e42:800::347:443
*   Trying 151.101.193.91:443...
* Connect socket 6 over QUIC to 151.101.193.91:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:800::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:400::347]:443...
* Connect socket 7 over QUIC to 2a04:4e42:400::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 151.101.193.91 port 443 failed: Failed sending data to the peer
*   Trying 151.101.65.91:443...
* Connect socket 8 over QUIC to 151.101.65.91:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:400::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:200::347]:443...
* Connect socket 9 over QUIC to 2a04:4e42:200::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 151.101.65.91 port 443 failed: Failed sending data to the peer
*   Trying 151.101.1.91:443...
* Connect socket 10 over QUIC to 151.101.1.91:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:200::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42::347]:443...
* Connect socket 11 over QUIC to 2a04:4e42::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 151.101.1.91 port 443 failed: Failed sending data to the peer
*   Trying 151.101.129.91:443...
* Connect socket 12 over QUIC to 151.101.129.91:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:600::347]:443...
* Connect socket 13 over QUIC to 2a04:4e42:600::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 151.101.129.91 port 443 failed: Failed sending data to the peer
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:600::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:a00::347]:443...
* Connect socket 14 over QUIC to 2a04:4e42:a00::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:a00::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:c00::347]:443...
* Connect socket 15 over QUIC to 2a04:4e42:c00::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:c00::347 port 443 failed: Failed sending data to the peer
*   Trying [2a04:4e42:e00::347]:443...
* Connect socket 16 over QUIC to 2a04:4e42:e00::347:443
* ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT
* connect to 2a04:4e42:e00::347 port 443 failed: Failed sending data to the peer
* Failed to connect to curl.se port 443 after 80044 ms: Failed sending data to the peer
* Closing connection 0
curl: (55) ngtcp2_conn_handle_expiry returned error: ERR_HANDSHAKE_TIMEOUT

**Comment by dvrajkiran** [comment]
I have gotten the same error in wsl2(ubuntu 22.04.1) by doing this

 **curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash**

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

**curl: (35) error:0A00010B:SSL routines::wrong version number**


but alternatively ihave used 
**wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash**

it installed nvm but doesnt showing any node versions to install(when this command is used  **nvm ls-remote** ) . its just showing N/A. but its displaying nvm -version as 0.39.2. i want to install node >=16 version. how to come out of this problem

**Comment by bagder** [comment]
I can reproduce. Researching.

@dvrajkiran that's not using http3 so its not the same issue

**Comment by bagder** [comment]
dafdb20a26d0c890e83dea61a104b75408481ebd is the first bad commit, according to my bisect. /cc @icing

**Comment by Karthikdasari0423** [comment]
Thank you @bagder for investigating

adding temporary solution here who might have urgent requirment (using curl version 7.86.0 is working fine with --http3)

git clone --branch curl-7_86_0 https://github.com/curl/curl.git

cd curl

autoreconf -fi

LDFLAGS="-Wl,-rpath,/var/local/openssl/lib64" ./configure --with-openssl=/var/local/openssl --with-nghttp3=/var/local/nghttp3 --with-ngtcp2=/var/local/ngtcp2

make

make install

**Comment by icing** [comment]
A fix PR for master is currently being CI'ed: #9945

**Comment by Karthikdasari0423** [comment]
Thank you @icing and @bagder

**Comment by Karthikdasari0423** [comment]
Thank you @bagder and @icing for investing and closing issue.

**Comment by arvindpdmn** [comment]
Encountered this error `curl: (35) error:0A00010B:SSL routines::wrong version number` on Ubuntu 22.04 running in GitHub Actions. Curl version is:
```
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

**Comment by Karthikdasari0423** [comment]
I recommend you to Update to latest curl version

**Comment by dfandrich** [comment]
The fix in this issue landed in 7.87.0,

**Comment by DowneyFlyfan** [comment]
fatal: unable to access 'https://github.com/DowneyFlyfan/downeyflyfan.github.io/': OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number. 

Well, What is that problem? Can anyone help me please?

**Comment by dfandrich** [comment]
What curl version is that? If it's less than 7.87.0 then try 7.87.0.

**Comment by tibu** [comment]
I had the same issue. I changed from Ubuntu LTS to Normal, upgraded to latest ubuntu, curl was upgraded to 7.85 and the issue has been solved.

**Comment by B353S** [comment]
I have same issue 
curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.5
Release-Date: 2023-02-20
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL threadsafe TLS-SRP UnixSockets

Trying everything without success. Can anyone help me , please?

**Comment by dfandrich** [comment]
@B353S that curl doesn't support HTTP/3 so it's not the same issue.

**Comment by alinmiron** [comment]
using it through Guzzle I get this:

GuzzleHttp\Exception\ConnectException: cURL error 35: error:0A00010B:SSL routines::wrong version number (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://graph.facebook.com/v3.3/me?

Before few hours ago, I wasn't getting the error.

**Comment by dfandrich** [comment]
What changed in the last few hours?

**Comment by istiak101** [comment]
In my case I was having this issue when I did a curl on a url that was hosted on the same machine. And curl after resolving dns tried with the loopback address but not the public IP of that machine. And that vhost was listening on public_ip:port and curl tried with loopback:port which didn't have any SSL.

After deleting default loopback vhost for nginx I now have a new issue because curl will try the loopback and there is nothing listening on the loopback interface on that port. I wonder why curl tries to connect to loopback.

So I had to change to `listen      ip:port ssl;` to `listen     port ssl; to get curl working for testing.

**Comment by istiak101** [comment]
In my case I was having this issue when I did a curl on a url that was hosted on the same machine. And curl after resolving dns tried with the loopback address but not the public IP of that machine. And that vhost was listening on public_ip:port and curl tried with loopback:port which didn't have any SSL.

After deleting default loopback vhost for nginx I now have a new issue because curl will try the loopback and there is nothing listening on the loopback interface on that port. I wonder why curl tries to connect to loopback.

So I had to change to `listen      ip:port ssl;` to `listen     port ssl;` to get curl working for testing.

**Comment by alinmiron** [comment]
It seems that the guys responsible with the office infrastructure were testing some new equipment and firewalls.
Temporary there was no access to facebook. So you should check your network setup.

**Comment by istiak101** [comment]
Looks like I must force this with --interface flag and for php CURLOPT_INTERFACE exists which I was working with.

**Comment by abhayasingh** [comment]
Am also getting this error, I have taken the lastest curl from https://curl.se/, compiled it with ./configure --with-openssl
am using SMTPS protocol to send email via curl, below is the command am running 

curl --ssl-reqd --url "smtps://$SERVER:$PORT" \
    --user "$USER:$PASS" \
    --mail-from "$SENDER_ADDRESS" \
    --mail-rcpt "$RECIPIENT_ADDRESS" \
    --upload-file "$MAIL_CONTENT_FILE"

The error is

curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number

Can someone please help

**Comment by jay** [comment]
When an issue is closed like this for several months it is better to open a new issue instead of commenting on the old one. The issue was fixed in curl 7.87.0 so what you are seeing means either it is not entirely fixed or there is a problem with the server you are connecting to. I think the latter is more likely since there have been no other reports.

> curl --ssl-reqd --url "smtps://$SERVER:$PORT"

> curl: (35) OpenSSL/3.0.8: error:0A00010B:SSL routines::wrong version number

> curl 8.3.0 (x86_64-pc-linux-gnu) libcurl/8.3.0 OpenSSL/3.0.8 zlib/1.2.11 brotli/1.0.9 OpenLDAP/2.4.57

Your command uses [`--ssl-reqd`](https://curl.se/docs/manpage.html#--ssl-reqd) but that is not necessary for an smtps URL as you can see in the documentation. Possibly what is happening is you are connecting to a plaintext SMTP server that can be upgraded to SSL. That is called _explicit_ SSL where you ask a server for SSL in plaintext before actually attempting it, as opposed to _implicit_ SSL where you attempt it immediately without asking.

Try connecting to your server in plaintext without sending any mail and see what happens:

curl -v smtp://$SERVER:$PORT

If the server is plaintext then curl should connect and send the HELP command.

If I were you I would find out if your server supports implicit SSL. The port will be different. Usually it is the default port 465, for example `smtps://smtp.gmail.com`.

And if my hunch is wrong please open a new issue and show verbose (-v) output.

**Comment by abhayasingh** [comment]
Thanks, for the response and very sorry for posting on Closed Thread,

**Comment by A-tao01** [comment]
fatal: unable to access 'https://210.76.168.252:7999/kcsos/shop-platform.git/': OpenSSL/3.1.4: error:0A00010B:SSL routines::wrong version number
谁能帮帮我，怎么解决？

**Comment by jay** [comment]
As discussed in this thread there can be several reasons. For example you are connecting to a port that is not using TLS or there is a middlebox interfering with the connection or your server is using a very old implementation of ssl. You will have to diagnose it and open a new issue written in English if you still think curl is causing the problem.
