### ISSUE TITLE
curl returning error code 0 for failed request

### ISSUE THREAD

**Issue by nirvikb** [curl/curl#9951]
### curl/libcurl version

[curl -V output]

### operating system

The code was using curlMulti 7.29.0 in C on oracle linux for HTTP post message to write to a cloud object storage. The curl error code returned was 0 and the http error code was 0, however there was a curl error message "necessary data rewind wasn't possible". The write to cloud object storage was not successful still curl returned 0 but with the aforementioned  error message. The http response header was empty

**Comment by bagder** [comment]
If the HTTP transfer/request worked, then curl considers that a fine transfer. For you, that might not have been fine because of what it returned over HTTP.  This is by design. libcurl returns information about the HTTP transfer, and that worked.

We offer `CURLOPT_FAILONERROR` to make libcurl return error on (some) HTTP response codes that might be what you want.

**Comment by jay** [comment]
> there was a error message necessary data rewind wasn't possible". The write to cloud object storage was not successful still curl returned 0 but with the aforementioned error message.

Can you give us your curl version and a way to reproduce? If data rewind fails then curl should return an error.

https://github.com/curl/curl/blob/cd95ee9f771361acf241629d2fe5507e308082a2/lib/transfer.c#L439-L441

Callers should bubble up that error.

**Comment by nirvikb** [comment]
@jay curl_version() libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Interesting thing is the HTTP code also returned 0 and the HTTP response header was empty.

We had used CURLOPT_READDATA, CURLOPT_READFUNCTION but not CURLOPT_SEEKDATA, CURLOPT_SEEKFUNCTION

**Comment by jay** [comment]
That version is almost 10 years old. Please try the [latest version](https://curl.se/download.html).
