### ISSUE TITLE
10-at-a-time example skips result of the last url in single MAX_PARALLEL mode

### ISSUE THREAD

**Issue by kuznetsov-m** [curl/curl#9953]
### I did this
Take [10-at-a-time.c](https://github.com/curl/curl/blob/master/docs/examples/10-at-a-time.c) example and change next:
- MAX_PARALLEL new value is 1
- urls - left 3 items

then build and run.

### I expected the following
```
R: 0 - No error <https://www.microsoft.com>
R: 0 - No error <https://opensource.org>
R: 0 - No error <https://www.google.com>
```
### I received the following
```
R: 0 - No error <https://www.microsoft.com>
R: 0 - No error <https://opensource.org>
```
result of last url has been skipped.

### operating system
Darwin MBP.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Comment by jay** [comment]
Please try #9953

**Comment by kuznetsov-m** [comment]
Yes, it works! Alternative fix also looks great! Many thanks for the quick fix!
