### ISSUE TITLE
Missing call to OPENSSL_cleanup() causes leaks

### ISSUE THREAD

**Issue by n1kaaa** [curl/curl#9955]
### Using curl 7.86.0 with OpenSSL 1.1.1i on Windows 11

`ossl_init()` initialises libcrypto and libssl via `OPENSSL_init_ssl()`. However no calls to `OPENSSL_cleanup()` were made during curl cleanup thus causing several memory leaks in my application.

I built curl from source with the following command:
> nmake /f Makefile.vc mode=static RTLIBCFG=static VC=14 WITH_SSL=static SSL_PATH=..\deps\openssl WITH_ZLIB=static ZLIB_PATH=..\deps\zlib CC="cl /DCURL_DISABLE_LDAP" ENABLE_IDN=no DEBUG=yes MACHINE=x86

Memory leaks were detected using [Microsoft's CRT library ](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2015). After adding `OPENSSL_cleanup()` to the `ossl_cleanup()` function here:
```diff
/* Global cleanup */
static void ossl_cleanup(void)
{
#if (OPENSSL_VERSION_NUMBER >= 0x10100000L) && \
    !defined(LIBRESSL_VERSION_NUMBER)
  /* OpenSSL 1.1 deprecates all these cleanup functions and
     turns them into no-ops in OpenSSL 1.0 compatibility mode */
+    OPENSSL_cleanup();
#else
  /* Free ciphers and digests lists */
  EVP_cleanup();

#ifdef USE_OPENSSL_ENGINE
  /* Free engine list */
  ENGINE_cleanup();
#endif

  /* Free OpenSSL error strings */
  ERR_free_strings();

  /* Free thread local error state, destroying hash upon zero refcount */
#ifdef HAVE_ERR_REMOVE_THREAD_STATE
  ERR_remove_thread_state(NULL);
#else
  ERR_remove_state(0);
#endif

  /* Free all memory allocated by all configuration modules */
  CONF_modules_free();

#ifdef HAVE_SSL_COMP_FREE_COMPRESSION_METHODS
  SSL_COMP_free_compression_methods();
#endif
#endif

  Curl_tls_keylog_close();
}
```
all fixed.

**Comment by jay** [comment]
If you are using OpenSSL as a static library then it will not automatically clean up all resources on thread and process exit. Refer to OpenSSL 1.1.1 [OPENSSL_cleanup NOTES](https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_cleanup.html#NOTES). It is not libcurl's responsibility to clean up those resources.
