### ISSUE TITLE
CURLOPT_CAPATH don't work

### ISSUE THREAD

**Issue by bird-rookie** [curl/curl#9961]
### I did this
I ran a sample code to test.
The certificates path on Android is /system/etc/security/cacerts
~~~c
curl_easy_setopt(curl_.get(), CURLOPT_SSL_VERIFYPEER, 1L);
curl_easy_setopt(curl_.get(), CURLOPT_CAPATH, "/system/etc/security/cacerts");
~~~
one more thing, i use a pem file, put it in this path, and set it to curl through CURLOPT_CAINFO. it works well.
but when i use CURLOPT_CAPATH, no matter it has the pem file or not, it doesn't work.

i search the internet for help.  i have token some method. 
such as 
1.  build wiht -DCURL_CA_PATH=/system/etc/security/cacerts
2.  modify the by_dir.c at openssl source    X509_NAME_hash to X509_NAME_hash_old
both dont work,
### I e xpected the following
https connect successfully.
### curl/libcurl version
curl version is 7.78.0
openssl version is 1.1.1k
[curl -V output]
Send perform connect failed, Problem with the SSL CA cert (path? access rights?), 77
### operating system
Andorid phone

**Comment by bagder** [comment]
This path name is passed mostly as-is on to an OpenSSL function (`X509_STORE_load_locations`), which would indicate that either the OpenSSL function doesn't work for you or that you haven't set up that directory correctly.

**Comment by bird-rookie** [comment]
@bagder  hello bagder， thank you for your replay. 
you mean this issue it due to some bugs in OpenSSL?  
have you ever been with it or do you konw some link which can fix this problem.

**Comment by bird-rookie** [comment]
> Have you used "openssl rehash" to set up that directory?

Do you mean to modify the source code of openssl?
i just use the interface from libcurl.

**Comment by dfandrich** [comment]
No, I mean running the command "openssl rehash".

**Comment by bird-rookie** [comment]
> No, I mean running the command "openssl rehash".
