### ISSUE TITLE
CURL command is not working (command execution is blocked) while WDAC is enabled

### ISSUE THREAD

**Issue by mzeyeni** [curl/curl#9967]
### curl 7.86.0 
Release-Date: 2022-10-26

[curl -V output]
url 7.86.0 (x86_64-w64-mingw32) libcurl/7.86.0 OpenSSL/3.0.5 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 WinIDN libssh2/1.10.0 nghttp2/1.50.0 ngtcp2/0.10.0 nghttp3/0.7.1 libgsasl/2.2.0

**Comment by bagder** [comment]
How is this curl's problem?

**Comment by mzeyeni** [comment]
Hello,

The WDAC scan was performed while the CURL.exe was present. So, I was expecting the CURL.exe to be in the white list and not be blocked with WDAC.

I was wondering if you have already faced this issue and if you have a workaround solution ?

Kind regards,
Mehdi Zeyeni

De : Daniel Stenberg ***@***.***>
Envoyé : mercredi 23 novembre 2022 00:24
À : curl/curl ***@***.***>
Cc : ZEYENI-LANGUAROUDI, MEHDI (RC-FR SI EA SO A ENG) ***@***.***>; Author ***@***.***>
Objet : Re: [curl/curl] CURL command is not working (command execution is blocked) while WDAC is enabled (Issue #9967)


How is this curl's problem?

-

**Comment by OSPanel** [comment]
This problem has nothing to do with CURL. You need to configure the WDAC.
