### ISSUE TITLE
macos x86_64 link error: alignments

### ISSUE THREAD

**Issue by egorpugin** [curl/curl#9975]
macos 13.0.1, arm64 (m1 pro)
curl 7.86.0, custom build
target arch x86_64

```
./4082357521269540648.sh                                      
[sw.client.sw.gui-0.4.0]
ld: warning: alignment (2) of atom '_Curl_krb5_mech_oid' is too small and may result in unaligned pointers 
ld: warning: alignment (2) of atom '_Curl_spnego_mech_oid' is too small and may result in unaligned pointers 
ld: warning: pointer not aligned at page boundary address 0x103576FFC ('_Curl_spnego_mech_oid' + 4 from /Users/egor/.sw/storage/pkg/23/45/56a4/obj/bld/179130/lib/liborg.sw.demo.badger.curl.libcurl-7.86.0.a(curl_gssapi.c.e3cc4e27.o))
ld: unaligned pointer(s) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nickzman** [comment]
I was able to build the latest code for x86_64 just fine with `--with-gssapi` enabled on macOS 13.0.1. Are you sure you're using the latest version of Xcode (14.1) **and** the corresponding command line tools?

**Comment by bagder** [comment]
@egorpugin tell us how to reproduce this or we can't help you much.

**Comment by egorpugin** [comment]
Well, curl (lib and bin) itself builds without such issue.
But in my project the error happens.

I was able to build 7.86 for x86_64 targetting minimum macos 11.0.

**Comment by egorpugin** [comment]
Setting alignment to 8 helps.
```
__attribute__((aligned(8)))
gss_OID_desc Curl_spnego_mech_oid = {
  6, (char *)"\x2b\x06\x01\x05\x05\x02"
};
__attribute__((aligned(8)))
gss_OID_desc Curl_krb5_mech_oid = {
  9, (char *)"\x2a\x86\x48\x86\xf7\x12\x01\x02\x02"
};
```

Cant find simple repro yet, but you could try to build my project. It will download and build a lot. You can create new user for this and remove later. I build on arm64 macos13 host.
```
git clone https://github.com/SoftwareNetwork/sw
cd sw
wget https://software-network.org/client/sw-master-macos_arm64-client.tar.gz
*unpack here*
sw build -static -platform x64 -Dwith-gui=true
```

**Comment by egorpugin** [comment]
But as I said this is a custom curl build. Wrong flags are possible in case if they can control alignment of vars.

**Comment by bagder** [comment]
To me, it seems likely that you introduce this problem in your build if you cannot reproduce this with a regular curl build. This specific code has also been like this for a while already without anyone else having any problems with it. I can't see how this is a curl bug.
