### ISSUE TITLE
curl with darwinssl omits the SNI TLS extension when used with the `-k` flag.

### ISSUE THREAD

**Issue by Lukasa** [curl/curl#998]
### I did this

`curl -k https://http2bin.org/get`

### I expected the following

The SNI extension present in the Client Hello packet.

### curl/libcurl version

```
curl 7.50.2-DEV (x86_64-apple-darwin16.0.0) libcurl/7.50.2-DEV SecureTransport zlib/1.2.8 libssh2/1.7.0 nghttp2/1.14.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets 
```

### operating system

macOS 10.12 Sierra Beta 4

### other notes

This problem appears to be specific to darwinssl: OpenSSL is not affected by it. I can reproduce back several versions: at the very least, the version of curl shipped with my OS is affected:

```
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

**Comment by bagder** [comment]
ping @nickzman, any idea?

**Comment by Lukasa** [comment]
A quick dive into the code for Security.framework and coreTLS shows that the following things happen when `SSLSetPeerDomainName` is called:

1. First, `tls_handshake_set_peer_hostname` (inside coreTLS) is called by `SSLSetPeerDomainName`. This stores the hostname in the `peerDomainName` field in the handshake structure.
2. During the TLS handshake, coreTLS checks whether the `peerDomainName` has been set. If it has, it fills in the SNI extension. If not, it doesn't.
3. Once the handshake is complete, Security.framework validates the certs and uses `tls_handshake_get_peer_hostname` to extract the previously-stored hostname to use to validate the leaf cert.

That means that *probably* it's impossible to have SNI without having hostname validation in DarwinSSL. I'd suggest that probably the best action here is to file a radar and then consider this a known limitation in Security.framework.

**Comment by nickzman** [comment]
It's as @Lukasa said above - with Secure Transport, you can have both SNI and host name validation, or you can have neither. I doubt Apple will change this.
